### ISSUE TITLE
建议：在软件的启动界面上加上新手指引相关内容

### ISSUE THREAD

**Issue by Jackiexiao** [siyuan-note/siyuan#1]
![image](https://user-images.githubusercontent.com/18050469/92359691-43618980-f11e-11ea-93b3-09ad430aee4e.png)

**Comment by 88250** [comment]
用户指南在右上问号，是感觉这个图标不够醒目还是觉得内容不易上手？或者说应该有个其他引导方式吗？

**Comment by Jackiexiao** [comment]
要把用户想成傻白甜....像我这样用了很多工具的，打开思源笔记也是一脸懵，模拟一下普通用户看到的感受：

“打开笔记本”，笔试本是啥？是文件夹吗？“webdev”又是啥子东西

像Vscode，各种网站，都会有很好的新手指引的，很多用户是不知道要到右上角去点击那个问号的（都没这个习惯）

**Comment by 88250** [comment]
嗯，那就来个“文字版”的导航，这样醒目一点。

**Comment by Jackiexiao** [comment]
不要嫌我烦，吐槽这个思源社区，我之前注册过，有段时间没有用，想上去反馈问题，接连遇到几个问题

1. 登录：（我忘记自己是微信还是github还是啥子注册了），然后github登录，遇到404，微信登录，遇到404（正常应该是没有这个用户就自动引导注册吧）
![image](https://user-images.githubusercontent.com/18050469/92360571-9b4cc000-f11f-11ea-92dc-51fcd6ce1a9e.png)
2. 登录2：终于想起自己注册过，成功登录，唉，怎么跳转到主页，不应该自动跳转到思源社区吗？回去，我再打开思源的官网，滚轮滚啊滚，找到思源社区的图标，点击再跳转一遍..
3. 想发新贴：在页面找了好久找不到发新贴的按钮（印象中新用户是不能发言还是啥的..）。Die...于是来github吐槽了（貌似以前还吐槽过那个社区注册很麻烦）

**Comment by 88250** [comment]
感谢反馈，最近社区端正在调整，目前已经统一使用手机号注册了，后续会继续改进 🙏
