### ISSUE TITLE
 为什么编辑完 还会有 id

### ISSUE THREAD

**Issue by jweny** [siyuan-note/siyuan#10]
为什么编辑完 还会有 id

**Comment by 88250** [comment]
麻烦详述

**Comment by jweny** [comment]
![Uploading image.png…]()
图片不知道传没传上来  就是编辑完 有一堆这个东西
{: id="20200918113655-r40ftju"}

{: id="20200918105054-nffyypp"}

{: id="20200918105723-kzwerj2"}

{: id="20200918114015-5yve7zm"}

**Comment by 88250** [comment]
思源笔记使用的是 [kramdown](https://kramdown.gettalong.org) 语法进行内容块标记，如果你需要导出标准 Markdown 可以使用导出功能。

**Comment by 88250** [comment]
技术原理方面请参考[Markdown 实现块级引用双向链接的探索](https://ld246.com/article/1597226949061)。
