### ISSUE TITLE
支持中文数字排序

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10007]
数据库中文排序问题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

选项排序既没有按照中文语境，也没有按照自定义的顺序排序，升序降序均有问题

### Expected result

支持中文语序或自定义顺序

### Screenshot or screen recording presentation

![a401a793b8edf74c4832e76443e289c2](https://github.com/siyuan-note/siyuan/assets/154863885/333e69b3-174e-479e-b3e3-d555ef0056c2)
![fd01d1a2e96d8f35aee07c1b37a1a93a](https://github.com/siyuan-note/siyuan/assets/154863885/4670b058-4609-414d-8261-a2f5db89036a)

![PixPin_2023-12-28_23-22-04](https://github.com/siyuan-note/siyuan/assets/154863885/d439cafb-e8e0-4501-b5d4-b515f3ea9ac1)

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13787661/system-log.zip)

原文档数据太大不好上传，辛苦D大复现一下

**Comment by 88250** [comment]
你好，该列类型是？

**Comment by 88250** [comment]
我知道问题了，这个短期内恐怕处理不了，暂时搁置，谢谢。

**Comment by 88250** [comment]
中文数字排序实现比较困难，该情况建议还是手动排序，谢谢。

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/154863885/3d3aba15-fc23-4aac-91ec-14e8200a0864)
不支持中文排序也行，可它也不支持我自己设置的排序啊

**Comment by 88250** [comment]
你说的是行排序吗？

**Comment by AvoidantPerDis** [comment]
对，不是给了排序功能吗

**Comment by 88250** [comment]
自定义排序的话不要使用排序功能，然后直接拖动行排序就行了。

**Comment by AvoidantPerDis** [comment]
数量多了，还是按自定义排序好呀，不用一个个拖

**Comment by AvoidantPerDis** [comment]
后面加入的也能自动排序好

**Comment by 88250** [comment]
这个只能手动拖动排序。
