### ISSUE TITLE
闪卡复习页面的 闪卡数量表示不能实时变化

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10001]
### In what scenarios do you need this feature?

这里主要指的是待复习卡片的数量，不能随着刷卡数量的增多而减少

### Describe the optimal solution

希望能够实时变化，让自己掌握目前的剩余数量，而不是要自己计算

**Comment by 88250** [comment]
麻烦下载最新的 dev 版测试看看，应该已经修复。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by QQQOrange** [comment]
> 麻烦下载最新的 dev 版测试看看，应该已经修复。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

好的
