### ISSUE TITLE
复制代码文本，结果包含'`'符号

### ISSUE THREAD

**Issue by feng-kui** [siyuan-note/siyuan#10004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

假设有代码：
关键字是`OK`

在只读模式下，选择OK并复制，结果会是:
```
`OK`
```

### Expected result

正常来说，结果应该只有`OK`

### Version environment

```markdown
- Version:  v2.11.4
- Operating System: Mac
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请考虑使用这个选项复制：

![image](https://github.com/siyuan-note/siyuan/assets/873584/a0bc6057-fd45-4b16-a075-de3c99abb130)

Rel https://github.com/siyuan-note/siyuan/issues/9630

**Comment by feng-kui** [comment]
> 请考虑使用这个选项复制：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/293197788-a0bc6057-fd45-4b16-a075-de3c99abb130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4Mjk3ODYsIm5iZiI6MTcwMzgyOTQ4NiwicGF0aCI6Ii84NzM1ODQvMjkzMTk3Nzg4LWEwYmM2MDU3LWZkNDUtNGIxNi1hMDc1LWRlM2M5OWFiYjEzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwNTU4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjkyZDcyMmVjZDZhMmNiMGE0MjJkOTVjYWI4NjQ1ZGJkMjYwNDUxZWZkZTMyMzljNDhhYjI2ODQ0ZDE2NjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rZtWbR6GKJkIaeK2rb3JXMwuB5ZMX1TVvBHP3Y3CEyY)
> 
> Rel #9630

666，没毛病
