### ISSUE TITLE
Reset the dialog interface size when the dialog box exceeds the window

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

简单说，就是闪卡复习页面的布局，在外接显示器上显示是居中（默认形式），拔掉连接线后，笔记本电脑不能显示同样的布局。

### Expected result

能有一个相同比例的布局

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win11
- Browser (if used):edge
```

### Log file

无

**Comment by 88250** [comment]
方便截图对比看下吗，谢谢。

**Comment by QQQOrange** [comment]
> 方便截图对比看下吗，谢谢。

![image](https://github.com/siyuan-note/siyuan/assets/62794181/fa29a065-f4b0-49a1-a2e6-30bb75400aee)
![image](https://github.com/siyuan-note/siyuan/assets/62794181/9a3d34fc-dd57-4b1c-a75b-ce9c4933c569)
di第一张是显示器 第二张是笔记本

**Comment by Vanessa219** [comment]
有没有移动过位置或修改过大小？

**Comment by QQQOrange** [comment]
> 有没有移动过位置或修改过大小？

没有的，都是默认的位置。

**Comment by AvoidantPerDis** [comment]
#10048 我也有同样问题

**Comment by Vanessa219** [comment]
> > 有没有移动过位置或修改过大小？
> 
> 没有的，都是默认的位置。

在设置中点击 `恢复默认窗口` 重置后再试试。

**Comment by Vanessa219** [comment]
> #10048 我也有同样问题

你的问题是由于拖拽导致，和楼主的不太一样。目前只能计算大小后，发现显示不下后，将其重置为默认大小。

**Comment by AvoidantPerDis** [comment]
确实不一样

**Comment by Vanessa219** [comment]
没有太好的计算方法，先按照`显示不下后，将其重置为默认大小`进行修改是否可行？

**Comment by QQQOrange** [comment]
> 没有太好的计算方法，先按照`显示不下后，将其重置为默认大小`进行修改是否可行？

试一下咯 不会影响到其他页面的布局吧

**Comment by Vanessa219** [comment]
不会。
