### ISSUE TITLE
Add plugin event bus `lock-screen`

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10006]
https://github.com/siyuan-note/bazaar/pull/1327

**Comment by zxkmm** [comment]
实在抱歉，可能我两天前回复在code review区的评论没有通知，所以在这边重新发一遍。    
> 啊啊啊抱歉抱歉，应该是我没有表达清楚。我目前并不是需要感知锁屏操作。我的需求是需要插件能够直接调用锁屏操作，而不是感知锁屏操作。所以最后的这个更新不是我的需求，谢谢老大。

**Comment by Vanessa219** [comment]
还真没收到通知，我重新建一个 issue 吧。
