### ISSUE TITLE
闪卡复习页面红标识的含义能与anki一致

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10002]
### In what scenarios do you need this feature?

蓝色与绿色分别表示新卡与待复习卡片，这部分没有疑问。（最好数量能够实时变化）
主要是红色部分，目前思源红色部分表示的是已复习卡片，但是标识内容还是比较模糊，一张卡片如果点击的是重来按钮，那么这种卡片首先因为复习过了而被记录到红色部分，但是这部分卡片在短期内需要再次复习，那么这钟卡片的数量就不知道。

### Describe the optimal solution

直接用anki的标示思路。
红色表示重来，也即是下一次复习时间在24小时内的卡片，这样能够直观的知道哪一些卡片是复习了但是没记住，短期内仍需要复习的。
而成功复习的卡片则不需要在红色里面显示，只需在绿色标识里扣除数量即可，顺利复习完的卡片没必要标识。
这是anki长期以来的方案，足够成熟，也足够令人容易接受，并且没有歧义。
再加上大量anki用户因为渐进阅读而加入思源，这能让这一群体更快的接受思源闪卡的逻辑。

**Comment by 88250** [comment]
> 红色表示重来，也即是下一次复习时间在24小时内的卡片

这个确定是 24 小时吗？确定的话我们就按照这个方案来实现看看。

**Comment by QQQOrange** [comment]
> > 红色表示重来，也即是下一次复习时间在24小时内的卡片
> 
> 这个确定是 24 小时吗？确定的话我们就按照这个方案来实现看看。

稍等 我去找anki的相关制作人员确认一下

**Comment by QQQOrange** [comment]
> > 红色表示重来，也即是下一次复习时间在24小时内的卡片
> 
> 这个确定是 24 小时吗？确定的话我们就按照这个方案来实现看看。

要加的，要是重来的卡片时间超过了24小时，那就不会被算在当天的卡片里，而是会在重来卡片对应的时间节点复习。不会被算入红色计数

**Comment by 88250** [comment]
也就是说确定是当天（24 点以前）而不是 24 小时以内？

**Comment by QQQOrange** [comment]
> 也就是说确定是当天（24 点以前）而不是 24 小时以内？

anki里面可以自行设置第二天卡片的刷新时间，所以具体还是要按照思源的卡片刷新时间来定，例如要是思源是每24点前刷出新卡片，就是24点以前

**Comment by 88250** [comment]
思源没有这个概念，每一轮复习（触发间隔重复）都是独立的。

**Comment by QQQOrange** [comment]
> 思源没有这个概念，每一轮复习（触发间隔重复）都是独立的。

那就按思源的方案来就行，只要红色表示的是点击重来的卡片，同时卡片的出现时间在当晚24点之前

**Comment by 88250** [comment]
时间我们就不限制了，否则会和其他地方（比如新卡、复习卡上限配置）不一致，只将红色计数表示这次复习中评分为 重来 的数量。

**Comment by QQQOrange** [comment]
> 时间我们就不限制了，否则会和其他地方（比如新卡、复习卡上限配置）不一致，只将红色计数表示这次复习中评分为 重来 的数量。
 数字不是要实时变化吗，重来的卡片也会重新进入复习，那么重新复习后，这张卡片还是会被红色计数吗

**Comment by QQQOrange** [comment]
> 数字不是要实时变化吗，重来的卡片也会重新进入复习，那么重新复习后，这张卡片还是会被红色计数吗

数字不是要实时变化吗，重来的卡片也会重新进入复习，那么重新复习后，这张卡片还是会被红色计数吗

**Comment by QQQOrange** [comment]
> 时间我们就不限制了，否则会和其他地方（比如新卡、复习卡上限配置）不一致，只将红色计数表示这次复习中评分为 重来 的数量。

数字不是要实时变化吗，重来的卡片也会重新进入复习，那么重新复习后，这张卡片还是会被红色计数吗

**Comment by QQQOrange** [comment]
> 时间我们就不限制了，否则会和其他地方（比如新卡、复习卡上限配置）不一致，只将红色计数表示这次复习中评分为 重来 的数量。

而且要是只记录此次 那么当重来卡片下一次出现是在半小时后 而当前的复习十分钟就结束了，那么在半小时后再次复习的情况下，上次被记录为红色的卡片，这次要以绿色来显示吗

**Comment by QQQOrange** [comment]
> 时间我们就不限制了，否则会和其他地方（比如新卡、复习卡上限配置）不一致，只将红色计数表示这次复习中评分为 重来 的数量。

总之 要是打算采取一种新的方式 那么各种问题太多了 而且还增加了额外的学习成本，不如直接用现成的

**Comment by 88250** [comment]
> 那么重新复习后，这张卡片还是会被红色计数吗

之前说过，每一次复习都是独立的，所以只是在这一次复习中显示，和下一次复习没有关联。所以如果要做到和 Anki 一摸一样是不大可能了，我关闭了，见谅。
