### ISSUE TITLE
移动端使用新的交互方式

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10019]
### In what scenarios do you need this feature?

移动端的交互方式还是电脑那一套，使用起来误触非常多。
例如打开文档树，看下下一级文档，点击的时候却总是成了打开当前文档。
以及菜单，经常想打开某一个文档的菜单，变成点开这一篇文档。

### Describe the optimal solution

使用移动端的交互方式，例如每一篇文档默认点击为展开下级文档，打开文档使用额外的最右边增加新文档整合进菜单，长按文档出现菜单等等。

### Describe the candidate solution

当然 ，不要求立刻做出改变，但至少要加入日程，不然移动端的使用太反人类了

**Comment by 88250** [comment]
计划明年下半年开始调整移动端交互，感谢反馈。

**Comment by AvoidantPerDis** [comment]
补充一下，希望能改进模板的调用方式，目前调用方式会造成输入法反复弹出，最简单的办法可以是恢复对/的响应，只要按回车就能调用最常用的第一顺位模板了
