### ISSUE TITLE
安卓端 主题能够自动更新

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10014]
### In what scenarios do you need this feature?

不然每次软件更新之后，还需要在网络伺服里更新，太麻烦了

### Describe the optimal solution

不然每次软件更新之后，还需要在网络伺服里更新，太麻烦了

**Comment by 88250** [comment]
移动端目前暂时不开放集市，主要是应用商店审核会有问题，后续等有空我们再考虑一下，谢谢。

**Comment by QQQOrange** [comment]
> 移动端目前暂时不开放集市，主要是应用商店审核会有问题，后续等有空我们再考虑一下，谢谢。

主要是应用主题之后，如果软件更新，而主题有一部分不能使用的话，可能移动端的设置都进不去，要卸载重装才行

**Comment by 88250** [comment]
目前移动端不建议使用主题。

**Comment by QQQOrange** [comment]
> 目前移动端不建议使用主题。

嗷嗷嗷

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/17151
