### ISSUE TITLE
闪卡复习页面能够显示完整面包屑

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10012]
### In what scenarios do you need this feature?

现在如果当前闪卡存在于一个文档名称比较长或者文档层级比较多的文档中，那么当闪卡复习时，不能显示全部面包屑

### Describe the optimal solution

能够显示全部面包屑

**Comment by 88250** [comment]
是移动端还是桌面端？

**Comment by QQQOrange** [comment]
> 是移动端还是桌面端？

桌面端，手机端最好也能够默认显示全部，不然每次看都要点击面包屑 比较繁琐

**Comment by 88250** [comment]
请截图看下。

**Comment by QQQOrange** [comment]
> 请截图看下。

![Screenshot_20231229_092934.jpg](https://github.com/siyuan-note/siyuan/assets/62794181/58eb489a-1db7-4137-8728-fbac0d8b3f55)

![Screenshot_20231229_092937.jpg](https://github.com/siyuan-note/siyuan/assets/62794181/8ca7a9b7-9668-4e5f-aeca-dd36443b76f5)

这是安卓端，需要点击面包屑之后才能看见详细

**Comment by 88250** [comment]
* 移动端需要点击进入查看是设计如此，之前讨论过的
* 如果文本太长会省略，这个也是设计如此

感谢反馈。

**Comment by QQQOrange** [comment]
> * 移动端需要点击进入查看是设计如此，之前讨论过的
> * 如果文本太长会省略，这个也是设计如此
> 
> 感谢反馈。

桌面端能通过使用几行文字来显示面包屑吗

**Comment by 88250** [comment]
使用自定义 CSS 应该可以。

**Comment by QQQOrange** [comment]
> 使用自定义 CSS 应该可以。

涉及到知识盲区了 求提供代码片段

**Comment by 88250** [comment]
链滴或者 Q 群问一下吧……

**Comment by QQQOrange** [comment]
> 链滴或者 Q 群问一下吧……
好吧

**Comment by AvoidantPerDis** [comment]
[层级插件实现了类似效果](https://github.com/OpaqueGlass/syplugin-hierarchyNavigate/issues/43?notification_referrer_id=NT_kwDOCTsJDbQ5Nzc5NjY2OTQxOjE1NDg2Mzg4NQ)
