### ISSUE TITLE
安卓端闪卡 不能及时出现文字

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当点击间隔重复的时候，闪卡页面能迅速出现，但第一张闪卡的正面文字要几秒才能出现

### Expected result

能够及时出现

### Version environment

```markdown
- Version: 2.11。4
- Operating System:  安卓11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
麻烦录屏演示一下，谢谢。

**Comment by QQQOrange** [comment]
> 麻烦录屏演示一下，谢谢。

https://github.com/siyuan-note/siyuan/assets/62794181/a677b6d4-4de8-46c9-8fe6-ede5ad4529eb

**Comment by 88250** [comment]
相同的数据在桌面端是正常的吗？如果是的话请在移动端 重建索引 后再看看是否有改善。

**Comment by QQQOrange** [comment]
> 相同的数据在桌面端是正常的吗？如果是的话请在移动端 重建索引 后再看看是否有改善。

桌面端没出过这种问题 但是移动端每次都是这样 无论什么版本，重建索引后也是如此

**Comment by 88250** [comment]
试一下移动端伺服，桌面端访问复习是否正常。

**Comment by QQQOrange** [comment]
> 试一下移动端伺服，桌面端访问复习是否正常。

这个我不懂啊

**Comment by 88250** [comment]
在 Android 端右侧栏面板关于中打开 网络伺服 功能，然后在桌面端浏览器通过 Android 端伺服的 IP 地址访问看看。

**Comment by QQQOrange** [comment]
> 在 Android 端右侧栏面板关于中打开 网络伺服 功能，然后在桌面端浏览器通过 Android 端伺服的 IP 地址访问看看。

这样一点就出来了 不用等待

**Comment by 88250** [comment]
如果安装了插件、主题等扩展的话禁用后再看看。

**Comment by QQQOrange** [comment]
> 如果安装了插件、主题等扩展的话禁用后再看看。

全部禁用后还是需要等待

**Comment by 88250** [comment]
暂时无法定位问题了，保持打开 issue 一段时间，看看其他用户是否也遇到该问题。

**Comment by QQQOrange** [comment]
> 暂时无法定位问题了，保持打开 issue 一段时间，看看其他用户是否也遇到该问题。

嗯嗯

**Comment by Jiangshuon** [comment]
我之前版本也这样，不过只是第一张闪卡会慢，后面闪卡不会。现在版本没有这个问题。我是红米手机，你是红米或者小米吗

**Comment by QQQOrange** [comment]
> 我之前版本也这样，不过只是第一张闪卡会慢，后面闪卡不会。现在版本没有这个问题。我是红米手机，你是红米或者小米吗

我是iqoo的 和你之前的情况一样

**Comment by 88250** [comment]
暂时关闭了，谢谢。
