### ISSUE TITLE
Search and replace fails in some cases

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10016]
批量替换失效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用搜索页面的替换功能，将搜索到的文字替换为别的 不会成功

### Expected result

能够成功

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
是不是因为 替换类型 没有勾选？

**Comment by QQQOrange** [comment]
> 是不是因为 替换类型 没有勾选？

不是的 类型里面几乎全被勾选了

**Comment by 88250** [comment]
请导出能够重现问题的 .sy.zip 以便测试，谢谢。

**Comment by QQQOrange** [comment]
[system-log.zip](https://github.com/siyuan-note/siyuan/files/13790748/system-log.zip)


> 请导出能够重现问题的 .sy.zip 上传以便测试，谢谢。

**Comment by 88250** [comment]
老铁，不是日志文件，需要 文档 导出 .sy.zip 和重现步骤，比如类型、替换类型的截图或者录屏。

**Comment by QQQOrange** [comment]
> 请导出能够重现问题的 .sy.zip 上传以便测试，谢谢。

[2.4.1_社会文化结构的一般特征-cards__(Duplicated_2023-12-29_122140).sy.zip](https://github.com/siyuan-note/siyuan/files/13790918/2.4.1_.-cards__.Duplicated_2023-12-29_122140.sy.zip)

将社会意识替换为1，事实上替换我就没成功过，无论在哪一个文档

**Comment by 88250** [comment]
感谢提供数据集，已经能够重现问题，下个版本修复。
