### ISSUE TITLE
数据库名称修改不生效

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

对引用快锚文本进行修改，刷新后复原

### Expected result

记录修改

### Screenshot or screen recording presentation

![PixPin_2023-12-29_09-52-12](https://github.com/siyuan-note/siyuan/assets/154863885/2be3ec0c-822d-4c99-823a-617128beb0d9)

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/13791360/system-log.1.zip)

**Comment by 88250** [comment]
主键如果绑定了块，则不支持（虽然目前界面支持粘贴修改）修改内容，内容是根据定义块锚文本计算而来的。

后续会考虑进行控制，感谢反馈。
