### ISSUE TITLE
Improve adding rows of the filtered database table view

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10025]
在筛选多选时无法排除空值

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在最新版本依然无法准确处理属性未定义时导致空值无法准确筛选的问题。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/838365fc-d829-4068-bfe1-ecfaa1033ee6)

### Expected result

建议不要在后端增加复杂的判断逻辑了，在database增加列时默认为所有行赋一个空值，这样能解决大量问题。

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win10 
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
感谢反馈，下个版本改进。
