### ISSUE TITLE
移动端适配 PWA 模式

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#10022]
### In what scenarios do you need this feature?

局域网伺服保存为 PWA 使用。

### Describe the optimal solution

需要针对PWA模式进行样式上的调整，**改动可能较大。**

### Other information

目前思源 mobile-browser (应该是这个？) 模式没有针对 PWA 进行适配，导致 PWA 模式下不够“沉浸”。

- 思源：v2.11.4
- 设备：iPhone 14 pro
- 系统：iOS 17

以下是思源目前在我手机上，PWA模式下的效果：

https://github.com/siyuan-note/siyuan/assets/16909518/af48ccb3-0602-4d73-a1e8-509bf89e1acd

这是我魔改了以后的效果：

<img width="635" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/6f6a1837-798a-4a88-a8eb-234fce8e4d3c">

<img width="628" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/c79bd13c-0af0-46e3-bd20-19194d8d77ae">

<img width="634" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/489624bf-66f3-4496-a94b-58905410149c">

但是这种修改治标不治本，还是会有一些页面会存在问题，比如搜索功能的分组👇

<img width="637" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/dcfd7769-e9c9-4397-95ba-48975677a398">

我尝试过给主体进行 PR，但是出于以下一些原因，最后还是放弃了：

1. 对思源代码还不够熟悉，对整体页面构造逻辑不了解。不确定一些改动方案是否会影响到现有逻辑。（比如我想过把body下的内容，重新放到一个新的元素里，然后再做适配）
2. 如果 PR 至思源主体，需要考虑的情况比较多，比如顶部状态栏、底部小黑条高度的动态适配等。毕竟插件可以小打小闹，主体不能。

之所以会出现这个需求，是因为思源目前没有实时同步的方案，而我在家的时候，经常会电脑手机来回换着用，内容实时同步是一个非常刚需的需求，所以我采用了伺服并保存为 PWA 的模式。至少在家里的情况下，我可以无缝在多设备上切换使用。

这个 issue 主要是为了记录这个场景，D大、V姐你们可以自行考虑一下后续是否需要加入排期。我本人的话，目前用自己的这个版本也够用了。

另外，D大，这个issue就先不关了吧？要是其他作者看到了，有时间处理了也可以？我最近没啥精力处理这块内容，要是后面有时间了，也可以考虑优化一下。

如果其他人看到了有兴趣，可以联系我交流这块的更改。

**Comment by 88250** [comment]
我们暂时没有时间研究了，还有就是怕影响现有的 APP。

Issue 会保持打开一段时间，谢谢。

**Comment by ssln5014** [comment]
> ### In what scenarios do you need this feature?
> 局域网伺服保存为 PWA 使用。
> 
> ### Describe the optimal solution
> 需要针对PWA模式进行样式上的调整，**改动可能较大。**
> 
> ### Describe the candidate solution
> _No response_
> 
> ### Other information
> 目前思源 mobile-browser (应该是这个？) 模式没有针对 PWA 进行适配，导致 PWA 模式下不够“沉浸”。
> 
> * 思源：v2.11.4
> * 设备：iPhone 14 pro
> * 系统：iOS 17
> 
> 以下是思源目前在我手机上，PWA模式下的效果：
> 
>  RPReplay_Final1703832289-1.mp4 
> 这是我魔改了以后的效果：
> 
> <img alt="image" width="635" src="https://private-user-images.githubusercontent.com/16909518/293321636-6f6a1837-798a-4a88-a8eb-234fce8e4d3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjYyMDcsIm5iZiI6MTcwNDM2NTkwNywicGF0aCI6Ii8xNjkwOTUxOC8yOTMzMjE2MzYtNmY2YTE4MzctNzk4YS00YTg4LWE4ZWItMjM0ZmNlOGU0ZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwNTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZjdmZDQ1NDY5OTY4Y2FjNmUxZGJiNGQ2Y2M4NTAxYjM2Njk1OWI1NWYzYWU4ZTg5YzQ2ZmYyNTdiZDcxNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AtGqg1LIEee6x3kEOc5hUmUFyyIq8Ozu2l5kb9TCkx0"> <img alt="image" width="628" src="https://private-user-images.githubusercontent.com/16909518/293321674-c79bd13c-0af0-46e3-bd20-19194d8d77ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjYyMDcsIm5iZiI6MTcwNDM2NTkwNywicGF0aCI6Ii8xNjkwOTUxOC8yOTMzMjE2NzQtYzc5YmQxM2MtMGFmMC00NmUzLWJkMjAtMTkxOTRkOGQ3N2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwNTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YzhlYjcyYjc1OTVmYjg2ZDZjNmY4NWU3YmFiMjJkZjVmMTYxOGI2NmNmMTlmOWY4ZjI3MDUzZGYxZmE4NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3IL3H0hvrY1M6PKATZ-N35cgqMvQWDKifF6a1OLHfL0"> <img alt="image" width="634" src="https://private-user-images.githubusercontent.com/16909518/293321707-489624bf-66f3-4496-a94b-58905410149c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjYyMDcsIm5iZiI6MTcwNDM2NTkwNywicGF0aCI6Ii8xNjkwOTUxOC8yOTMzMjE3MDctNDg5NjI0YmYtNjZmMy00NDk2LWE5NGItNTg5MDU0MTAxNDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwNTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYjhhYzE3YzBhYzU4ZjViOTE3ODVkNzdlY2Q0NDUwOWM4MWNhNWQ3NTkxNWE2OTYxMzNlYmU2ZmJhZjZkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.raVlKkT4GDlVxdKOyO3wLFP-MZ5ZcElTNlBbDDG6xS0">
> 但是这种修改治标不治本，还是会有一些页面会存在问题，比如搜索功能的分组👇
> 
> <img alt="image" width="637" src="https://private-user-images.githubusercontent.com/16909518/293321743-dcfd7769-e9c9-4397-95ba-48975677a398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjYyMDcsIm5iZiI6MTcwNDM2NTkwNywicGF0aCI6Ii8xNjkwOTUxOC8yOTMzMjE3NDMtZGNmZDc3NjktZTljOS00Mzk3LTk1YmEtNDg5NzU2NzdhMzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwNTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NmU5NjY5ZmQzODczOTA5NGNmMDk5OTM4M2M2MmRiZDBkNjQ5Y2YyMThiMjA2YmZmMTUwODY3MTg0Y2E3NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W_h9O-t5aNYVoMd4FJ8igc_A_cBPIaqp0UvJ1kVoBcM">
> 我尝试过给主体进行 PR，但是出于以下一些原因，最后还是放弃了：
> 
> 1. 对思源代码还不够熟悉，对整体页面构造逻辑不了解。不确定一些改动方案是否会影响到现有逻辑。（比如我想过把body下的内容，重新放到一个新的元素里，然后再做适配）
> 2. 如果 PR 至思源主体，需要考虑的情况比较多，比如顶部状态栏、底部小黑条高度的动态适配等。毕竟插件可以小打小闹，主体不能。
> 
> 之所以会出现这个需求，是因为思源目前没有实时同步的方案，而我在家的时候，经常会电脑手机来回换着用，内容实时同步是一个非常刚需的需求，所以我采用了伺服并保存为 PWA 的模式。至少在家里的情况下，我可以无缝在多设备上切换使用。
> 
> 这个 issue 主要是为了记录这个场景，D大、V姐你们可以自行考虑一下后续是否需要加入排期。我本人的话，目前用自己的这个版本也够用了。
> 
> 另外，D大，这个issue就先不关了吧？要是其他作者看到了，有时间处理了也可以？我最近没啥精力处理这块内容，要是后面有时间了，也可以考虑优化一下。
> 
> 如果其他人看到了有兴趣，可以联系我交流这块的更改。

这个效果是怎样改的，能分享一下方法吗？

**Comment by 88250** [comment]
关闭 issue 了，谢谢。
