### ISSUE TITLE
代码块高亮和显示问题

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#10024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

两个问题：
1.shell代码块没有高亮
2.!= 显示成了 ≠
![image](https://github.com/siyuan-note/siyuan/assets/20038464/7558802f-a44b-494a-b708-03300227dcb9)

### Expected result

1.希望支持shell代码高亮
2.代码块中不要改变符号显示

### Version environment

```markdown
- Version: 2.11.4
- Operating System: MacOS
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
1. 使用 `bash`
2. 关闭 设置 - 编辑器 - 代码块连字

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
