### ISSUE TITLE
Converting PDF annotation ref to text fails after setting the appearance

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10029]
PDF引用文本设置外观后转换为文本功能失效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

PDF引用文本设置外观后转换为文本功能失效

### Expected result

PDF引用文本设置外观后转换为文本变成默认样式 或是保留外观去除引用

### Screenshot or screen recording presentation

![PixPin_2023-12-30_16-14-53](https://github.com/siyuan-note/siyuan/assets/154863885/b16fe947-e884-4c0e-ae76-008c8885ce49)

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

[system-log (2).zip](https://github.com/siyuan-note/siyuan/files/13797507/system-log.2.zip)

**Comment by AvoidantPerDis** [comment]
对了，转化成文本能否给个快捷键，特别是当前块只有PDF引用的时候，效率能高不少

**Comment by Vanessa219** [comment]
是什么场景下需要这样频繁的操作呢？

**Comment by AvoidantPerDis** [comment]
额，有时候复制的pdf被我转成思源文档了，就会用上

**Comment by Vanessa219** [comment]
那就先不加了 😄

**Comment by AvoidantPerDis** [comment]
可以，我用quicker也能搞定

**Comment by HibernalGlow** [comment]
时隔一年我又来了 能不能加个转换为文本* 纯文本方便编辑 *用于保留pdf引用 （或者复制标注给个复制为文本*）
