### ISSUE TITLE
在闪卡复习完成页面 仍然可以使用快捷键撤回上一张卡片

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10026]
### In what scenarios do you need this feature?

原因在于如果最后一张卡按错了回答 导致此次复习结束 那么这一张卡就有了错误的学习信息
但是已经无法撤回了

### Describe the optimal solution

希望在复习完成页面按撤回快捷键仍然可以撤回最后一张卡

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/8207

**Comment by linyuan-muyu** [comment]
在没有实现手动调整闪卡排期之前，个人认为这个功能是有必要的，虽然频次不多，但是只要出现一次，同时还没有有效的补救措施的情况下，会非常影响使用和对软件的信任程度的，而间隔重复本身就是建立在对软件的信任之上的

**Comment by 88250** [comment]
@linyuan-muyu 近期会实现闪卡自定义到期时间 https://github.com/siyuan-note/siyuan/issues/10326
