### ISSUE TITLE
支持 PowerShell 代码块高亮

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1002]
PowerShell是Windows下的主力Shell
但是我发现居然没有高亮支持，所以希望考虑添加一下

**Comment by yeshaopeng6688** [comment]
希望也能支持 hql（hive sql）代码块高亮。

**Comment by 88250** [comment]
@yeshaopeng6688 目前高亮用的是 https://highlightjs.org 好像不支持 HQL 哦。
