### ISSUE TITLE
Support plsql syntax highlighting

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#10023]
### In what scenarios do you need this feature?

Support plsql syntax highlighting

### Describe the optimal solution

Support plsql syntax highlighting

**Comment by 88250** [comment]
`pgsql`

Ref: https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

**Comment by siulo2** [comment]
pgsql is not same as plsql. 
and the language tag 'pgsql' not work as expected.
