### ISSUE TITLE
The primary key are no longer shown in the attribute panel database

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10027]
在属性面板中隐藏主键

### In what scenarios do you need this feature?

块的主键就是它本身。本身显示这一项就令人困惑，特别是加入到database的块比较大或者不是常规的段落块，如列表块、超级块的时候。

如果加入到多个database里，还会导致出现多个重复项，这其实不是很符合用户的直觉。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/cbaf36e5-7906-4ce6-ae1e-3304eb7c1adc)

### Describe the optimal solution

在属性面板中隐藏主键

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/10142 中实现 key 排序，如果没有主键的话排序可能会有问题，所以我们得恢复显示主键了。

**Comment by zxhd863943427** [comment]
什么叫key排序？

**Comment by 88250** [comment]
表格里的列排序



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 20, 2024 23:55 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] The primary key are no longer shown in theattribute panel database (Issue #10027)




 
什么叫key排序？

**Comment by 88250** [comment]
@TCOTC 还是不隐藏吧，现在是和视图独立了，但是排序的时候依然需要主键。
