### ISSUE TITLE
当快速使用alt+d 挖空的时候，偶尔会出现重复对上一次选中的文字使用命令，而忽略本次选中的文字

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

出现的频率不高，但偶尔会出现

### Expected result

解决这个bug

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
这里重现不了，选中是快捷键操作还是有鼠标辅助？

有没有可能是操作太快导致选中状态还没更新造成的。

**Comment by QQQOrange** [comment]
> 这里重现不了，选中是快捷键操作还是有鼠标辅助？
> 
> 有没有可能是操作太快导致选中状态还没更新造成的。

没错，就是使用鼠标宏来实现的。

**Comment by Vanessa219** [comment]
能不能把宏时间延长一点，这个有可能是操纵系统没有识别出来选中的当前内容。

**Comment by QQQOrange** [comment]
> 能不能把宏时间延长一点，这个有可能是操纵系统没有识别出来选中的当前内容。

好吧

**Comment by Vanessa219** [comment]
那我就先关闭了，后续还有问题的话继续回复即可。
