### ISSUE TITLE
移动端特定文档间隔重复打开效率提升

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10031]
### In what scenarios do you need this feature?

在pc端特定文档间隔重复可以直接快捷键呼出
移动端即左滑用文档树定位要4步，文档块点击要3步

https://github.com/siyuan-note/siyuan/assets/154863885/006e0f65-8b77-4d67-9ddd-2208cb862ba9

### Describe the optimal solution

在面包屑一栏加上闪卡的小标

### Describe the candidate solution

插件？

**Comment by Vanessa219** [comment]
移动端的面包屑也是需要点击才会出来的，操作步骤并不会少。可以单独用插件做一个常用闪卡的功能。

**Comment by AvoidantPerDis** [comment]
我的意思是利用![image](assets/image-20231231092222-ihauedi.png)旁边的空余

**Comment by Vanessa219** [comment]
间隔重复包含了子文档，而且不是每个文档都设置过间隔重复，因此这个按钮不太好判断显示与否。
