### ISSUE TITLE
移动端支持搜索时自动弹出键盘

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10037]
### In what scenarios do you need this feature?

移动端

### Describe the optimal solution

无

**Comment by Vanessa219** [comment]
如果只是想查看搜索结果弹出来的话会有点干扰。

**Comment by Jiangshuon** [comment]
> 如果只是想查看搜索结果弹出来的话会有点干扰。

打开搜索功能后，还没开始搜，没有搜索结果吧，显示的只是最近更新的块，干扰是指什么

打开搜索功能就是为了输入关键字然后搜索嘛，现在打开搜索功能后，还要在搜索框点一下才能弹出键盘开始打字。目前好像所有手机app都是点击搜索后自动弹出键盘的。

**Comment by Vanessa219** [comment]
搜索可以记忆的，如果输入框里哟内容，会显示搜索的结果。看了下 notion 点搜索并没有弹出键盘。
