### ISSUE TITLE
siyuan docker 版本加载某些挂件之后挂死, 并且集市界面点击切换挂件异常

### ISSUE THREAD

**Issue by ccxuy** [siyuan-note/siyuan#10035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

siyuan docker 版本加载某些挂件之后挂死, 并且集市界面点击切换挂件异常
![image](https://github.com/siyuan-note/siyuan/assets/720603/9fc71125-4669-444c-9dc3-2384747889e2)

### Expected result

正常切换

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/720603/22dee985-874b-436f-ba19-8eab15677142)

### Version environment

```markdown
- Version: v2.11.4
- Operating System: docker
- Browser (if used): chrome
```

### Log file

I 2023/12/31 00:21:56 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/12/31 00:21:56 runtime.go:74: kernel is booting:
    * ver [2.11.4]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/docker/siyuan]
I 2023/12/31 00:21:56 conf.go:280: upgraded from version [2.11.1] to [2.11.4]
I 2023/12/31 00:21:56 runtime.go:123: use network proxy [system]
I 2023/12/31 00:21:56 serve.go:120: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2023/12/31 00:21:56 blocktree.go:495: read block tree [14 MB] to [/docker/siyuan/temp/blocktree], elapsed [0.30s]
I 2023/12/31 00:21:56 conf.go:765: database size [130 MB], tree/block count [473/39965]
I 2023/12/31 00:21:57 working.go:192: kernel booted
I 2023/12/31 00:21:57 conf.go:968: upgrading user guide box [20210808180117-6v0mkxr]
I 2023/12/31 00:21:58 index.go:138: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.27s], tree [count=61, size=1.1 MB]
I 2023/12/31 00:21:58 conf.go:980: upgraded user guide box [20210808180117-6v0mkxr]
I 2023/12/31 00:21:58 conf.go:968: upgrading user guide box [20210808180117-czj9bvb]
I 2023/12/31 00:21:58 index.go:138: rebuilt database for notebook [20210808180117-czj9bvb] in [0.15s], tree [count=64, size=1.2 MB]
I 2023/12/31 00:21:58 conf.go:980: upgraded user guide box [20210808180117-czj9bvb]
I 2023/12/31 00:22:00 box.go:76: auto stat [trees=473, blocks=39965, dataSize=808 MB, assetsSize=592 MB]
W 2023/12/31 00:22:04 blocktree.go:552: save block tree [size=14 MB] to [/docker/siyuan/temp/blocktree], elapsed [2.07s]
I 2023/12/31 00:58:33 serve.go:212: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36]
I 2023/12/31 01:12:06 ref.go:66: updated local latest to [device=cnx80jhjadp2/linux, id=7eab38b50fc963edaf96fcedbadf0cec5d46438e, files=9307, size=799 MB, created=2023-12-31 01:11:10]
I 2023/12/31 01:13:15 store.go:61: purging data repo [/docker/siyuan/repo/]
I 2023/12/31 01:13:15 store.go:229: purged data repo [/docker/siyuan/repo/], [0] indexes, [0] objects, [0] bytes
W 2023/12/31 01:14:01 transaction.go:127: op tx [2819ms]
W 2023/12/31 01:14:59 transaction.go:127: op tx [2612ms]
W 2023/12/31 01:15:43 transaction.go:127: op tx [3147ms]
W 2023/12/31 01:28:59 transaction.go:127: op tx [4066ms]
E 2023/12/31 01:54:01 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:54:03 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:54:08 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:54:13 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:54:16 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:54:33 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:55:29 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:55:41 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:55:47 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:55:59 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:56:06 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:56:13 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:56:37 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:56:43 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 01:57:19 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:05:17 theme.go:64: get bazaar package [https://oss.b3logfile.com/package/LaneDu/Knowledge-Show@eafde5a4688a42bfc31a124c648d52f338e4bde6/theme.json] failed: 504
E 2023/12/31 02:06:27 plugin.go:65: get bazaar package [https://oss.b3logfile.com/package/terwer/siyuan-plugin-local-service@81cbf98a8817cf92ce58e189b33dc21b86c66189/plugin.json] failed: 504
E 2023/12/31 02:06:33 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:06:41 package.go:551: get bazaar package [https://oss.b3logfile.com/package/ScottXjw/SimplePlan@f993ffc547348fa781f2de02f181644ebf6e7da3/README_zh_CN.md] failed: 504
E 2023/12/31 02:06:48 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 504
E 2023/12/31 02:07:14 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
I 2023/12/31 02:14:16 serve.go:212: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36]
E 2023/12/31 02:16:03 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:16:09 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:19:56 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:20:01 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
I 2023/12/31 02:22:02 box.go:76: auto stat [trees=474, blocks=40664, dataSize=893 MB, assetsSize=616 MB]
E 2023/12/31 02:22:33 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:22:54 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:22:59 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
E 2023/12/31 02:23:30 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404

### More information

E 2023/12/31 02:23:30 widget.go:63: get bazaar package [https://oss.b3logfile.com/package/muhanstudio/siyuan-widget-Color-Calendar@3618012d665a257c9c4b1c8ea54e30392ad01c8c/widget.json] failed: 404
2023/12/31 02:23:31 http: panic serving 192.168.3.147:8108: runtime error: invalid memory address or nil pointer dereference
goroutine 23104 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1e8a360?, 0x3688d50?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/model.matchPackage({0xc0016ecf80?, 0x1, 0x27331b8?}, 0xc0065a3e00)
	/go/src/github.com/siyuan-note/siyuan/kernel/model/bazzar.go:354 +0x7c
github.com/siyuan-note/siyuan/kernel/model.filterWidgets({0xc003cb9f00, 0xe, 0x414bfa?}, {0xc004766178?, 0xc002df4240?})
	/go/src/github.com/siyuan-note/siyuan/kernel/model/bazzar.go:127 +0xb7
github.com/siyuan-note/siyuan/kernel/model.InstalledWidgets({0xc004766178, 0x8})
	/go/src/github.com/siyuan-note/siyuan/kernel/model/bazzar.go:136 +0x2c
github.com/siyuan-note/siyuan/kernel/api.getInstalledWidget(0xc0011aa200)
	/go/src/github.com/siyuan-note/siyuan/kernel/api/bazaar.go:169 +0x109
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.CheckAuth(0xc0011aa200)
	/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:221 +0x10f5
github.com/gin-gonic/gin.(*Context).Next(0xc0011aa200)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/siyuan-note/siyuan/kernel/server.Serve.Sessions.func4(0xc0011aa200)
	/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 +0x17d
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-contrib/gzip.(*gzipHandler).Handle(0xc001124060, 0xc0011aa200)
	/go/pkg/mod/github.com/gin-contrib/gzip@v0.0.6/handler.go:60 +0x2e6
github.com/gin-gonic/gin.(*Context).Next(0xc0011aa200)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/siyuan-note/siyuan/kernel/server.Serve.corsMiddleware.func2(0xc0011aa200)
	/go/src/github.com/siyuan-note/siyuan/kernel/server/serve.go:563 +0x11f
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.Recover(0xc0011aa200)
	/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:320 +0x62
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.Timing(0xc0011aa200)
	/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:293 +0x2c3
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.ControlConcurrency(0xc0011aa200)
	/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:343 +0x171
github.com/gin-gonic/gin.(*Context).Next(...)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000602680, 0xc0011aa200)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000602680, {0x274e3c0?, 0xc0079e6000}, 0xc0011aa100)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0x2748610?}, {0x274e3c0?, 0xc0079e6000?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc006248ea0, {0x2754490, 0xc0011247b0})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 76
	/usr/local/go/src/net/http/server.go:3086 +0x5cb

**Comment by 88250** [comment]
关联 https://github.com/muhanstudio/siyuan-widget-Color-Calendar/issues/1
