### ISSUE TITLE
希望能新增删除文章的垃圾箱的功能, 以及导出网页或pdf分享给他人(微信好友)

### ISSUE THREAD

**Issue by ccxuy** [siyuan-note/siyuan#10034]
### In what scenarios do you need this feature?

1. 误删文章的时候使用
2. 比如分享行程
另外似乎有个奇怪的bug, 通过chrome插件收录文章后, 由于发现部分图片未正常下载, 重新通过插件收录文章不生效(但其他网页正常)

### Describe the optimal solution

提供策略, 比如超30天自动真正删除

**Comment by ccxuy** [comment]
https://mp.weixin.qq.com/s/UoazVrgQ9Ml79d0__Wyzbw
BUG 通过chrome插件收录文章后, 由于发现部分图片未正常下载, 重新通过插件收录文章不生效(但其他网页正常)
网页是这个

**Comment by 88250** [comment]
1. 请使用 数据历史 功能
2. 桌面端支持导出 PDF，移动端不支持，不过可以考虑使用导出图片

剪藏的问题我这里无法重现（图片可以正常拉取到本地），请等下个版本再试试，感谢反馈。
