### ISSUE TITLE
数据库内块在原文档显示指定属性

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10033]
### In what scenarios do you need this feature?

我目前在用数据库做任务管理，其中优先级列我希望能在原文档显示出来
![image](https://github.com/siyuan-note/siyuan/assets/154863885/91f84a1d-98ab-471e-9399-a452f733d84e)

### Describe the optimal solution

类似命名别名的显示方式在行上方显示
![image](https://github.com/siyuan-note/siyuan/assets/154863885/406d49d2-15d4-406c-b6cf-51de0c6cf0c7)

### Describe the candidate solution

1. 数据库条目在块下方单独展示
![image](https://github.com/siyuan-note/siyuan/assets/154863885/b7af6521-d4c0-4d8c-8343-b702eed58f0d)

2. 数据库属性界面挂在块下方
![image](https://github.com/siyuan-note/siyuan/assets/154863885/a0f65a6c-0d2f-4f64-ab79-b829ad97544e)

**Comment by 88250** [comment]
这个暂时不考虑了，请使用属性面板或者等待相应的社区插件实现，谢谢。
