### ISSUE TITLE
链接被识别为标签

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#10032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文本内容：

```
tekton cicd实战 https://mp.weixin.qq.com/s?__biz=MjM5OTg2MTM0MQ==&mid=2247483705&idx=1&sn=f121deb3b87b48f6cbfb6f0c1395c0bb&chksm=a7344c0b9043c51dba72dbea32dbd1caeae376051bb2f0d6f51b32d6c693e71c939f41e916a2&scene=21#wechat_redirect
pipeline各参数说明 https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#workspaces-in-tasks-and-taskruns
```

复制到资源笔记后被识别为标签：
<img width="667" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/a82d59af-7b49-41c4-8a47-c6a1b8efc3c5">

### Expected result

希望不被识别为标签
是不是复制的时候自动换行就可以了？

### Version environment

```markdown
- Version: 2.11.1
- Operating System:  MacOS
- Browser (if used):
```

### Log file

[test.sy.zip](https://github.com/siyuan-note/siyuan/files/13797630/test.sy.zip)

**Comment by 88250** [comment]
标签的语法是 `#foo#`，所以上面的文本内容中的部分会被解析为标签。

可以粘贴的时候使用 Ctrl+K 作为超链接粘贴，这样就不会被解析为标签了。

**Comment by kylehz** [comment]
如果用Ctrl+K 复制的话，会变成一个链接，但我这个是两行内容
我的意思是能不能复制的时候加个换行 这样就不会被识别为标签了

**Comment by 88250** [comment]
恐怕没法判断加不加，有的时候是需要识别为标签的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月30日(周六) 下午5:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 链接被识别为标签 (Issue #10032)




 
如果用Ctrl+K 复制的话，会变成一个链接，但我这个是两行内容
 我的意思是能不能复制的时候加个换行 这样就不会被识别为标签了

**Comment by kylehz** [comment]
标签不需要换行吧

**Comment by 88250** [comment]
标签内容是不需要换行的。我想表达的是如果用换行作为区分是否解析为标签也不能解决此类问题，毕竟有不带换行且匹配标签语法的情况。

**Comment by kylehz** [comment]
那这个两行的内容复制过去是不是应该识别成两个块，而不是一个块

**Comment by 88250** [comment]
中间没有空行分隔的话是一个段落块。
