### ISSUE TITLE
rollup 汇总列的值汇总统计出错

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

关联

https://github.com/siyuan-note/siyuan/issues/10025

https://github.com/siyuan-note/siyuan/issues/9958

新版本的汇总出现的问题是同样原因引起的

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/5f6f82f0-1a7c-4252-984d-7c691f27a521)

建议还是采用我说的做法吧……这个不填充默认值的方案可以预见在未来会造成很多类似的问题，每次都需要修改后端逻辑。

话说D大依然是选择改进后端筛选逻辑而不是在创建时增加默认值的原因是什么？

### Expected result

在创建列或行时写入默认空值

### Version environment

```markdown
- Version: 2.11.4dev2
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
刷新一下表格试试，或者等下个 dev 版本，今早改了一些逻辑。这个应该和默认值没有关系，因为汇总列不存在默认值，都是实时计算的。

**Comment by 88250** [comment]
一直是填充默认值的，所以我不太明白你指的不填充默认值是啥意思……具体可参见 FillAttributeViewTableCellNilValue 函数。

另外，有的列类型只能实时计算，比如模板列、汇总列、创建/更新时间列。

**Comment by 88250** [comment]
对了，有确定重现步骤的话麻烦告诉我一下，多谢。

**Comment by zxhd863943427** [comment]
> 刷新一下表格试试，或者等下个 dev 版本，今早改了一些逻辑。这个应该和默认值没有关系，因为汇总列不存在默认值，都是实时计算的。

就是4个小时前拉取后打的包，应该就是最新的。

> 一直是填充默认值的，所以我不太明白你指的不填充默认值是啥意思……

就是据我观察来说，database中一行中的所有数据似乎并不是都在json里面储存了值的，假如一个值没有在database里点击一下，它会不储存在json中。

比如说，在块的属性面板的database属性中，有些database中的列对应的属性是没有显示出来的。

**Comment by zxhd863943427** [comment]
我看了一下json的文档，确实是没有对应值的

[20231227224406-95s78hb.json](https://github.com/siyuan-note/siyuan/files/13801750/20231227224406-95s78hb.json)

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/8e6c20bf-7af7-468c-b70a-d8db8b4c5682)

这是database两个空的行，在json里面只储存了第一行的值。区别只是，我在第一行先赋值又清空了。

**Comment by 88250** [comment]
这些列的值不会持久化的，因为值都是实时计算的。

**Comment by zxhd863943427** [comment]
啊？不会持久化？那json里储存的是什么？

**Comment by zxhd863943427** [comment]
这些列是文本、数字、单选这些普通列啊。

**Comment by zxhd863943427** [comment]
https://github.com/siyuan-note/siyuan/assets/74853597/f57e3295-5109-4b89-af31-caed209e3387

**Comment by 88250** [comment]
我说的是上面提到的那几种列不持久化。另外，不持久化的还有未创建的值，也就是用户没有编辑过的值。

**Comment by zxhd863943427** [comment]
一个复现视频，结果又出现了2个问题，一个是新建属性后没法点击，需要按键esc两次才能继续编辑。一个是第一次无法删除单选或多选的选中项。

**Comment by zxhd863943427** [comment]
> 不持久化的还有未创建的值，也就是用户没有编辑过的值。

我认为这个就是需要持久化的，需要给其提供一个默认值。这个不持久化的原因是什么？

**Comment by 88250** [comment]
没有值不需要持久化啊，没有特殊原因啊。

**Comment by zxhd863943427** [comment]
> 没有值不需要持久化啊，没有特殊原因啊。

我认为问题就在于这了，因为没有提供一个默认值进行持久化，导致了很多复杂的边界情况，容易出错。

我在编辑后又删除，理论上应该跟未编辑过的值一个样，但表现出来却经常不是，无论是筛选、汇总、属性面板中都这样。

因此我觉得最好能在新建行、列的时候提供一个默认的初始值进行持久化。

**Comment by 88250** [comment]
> 一个复现视频，结果又出现了2个问题，一个是新建属性后没法点击，需要按键esc两次才能继续编辑。一个是第一次无法删除单选或多选的选中项。

第一个问题暂时不太确定是不是界面的问题，试试默认主题。第二个编辑单选多选我这里测试正常。

**Comment by zxhd863943427** [comment]
> 因此我觉得最好能在新建行、列的时候提供一个默认的初始值进行持久化。

这样子直接就能精简掉后端的很多判断是否有值的逻辑了。

**Comment by zxhd863943427** [comment]
> 第一个问题暂时不太确定是不是界面的问题，试试默认主题。

测试中用的就是默认的daylight，并且已经关闭全部代码片段和插件

**Comment by 88250** [comment]
估计得看看 console 或者内核是否有报错，或者帮忙 debug 一下了，我这里目前重现不了。

**Comment by zxhd863943427** [comment]
> 第一个问题暂时不太确定是不是界面的问题

重载几遍后复现不了了，之后能复现再看吧。

**Comment by zxhd863943427** [comment]
能复现了，问题貌似是遮挡多生成了

**Comment by 88250** [comment]
我大概明白你说的默认值的意思了，你指的应该是表格新增行列的时候填充？有两个原因：

* 底层存储的列值结构是不能确定上层视图的行的，或者说这个依赖关系不能反过来看，否则就被上层视图（目前是表格）给框死了
* 就算可以反过来设计，底层就用行列结构存储，那么新增行/列比如面临大量的空间浪费，性能也不会好

**Comment by zxhd863943427** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/16e9ac08-0d51-4f6f-b0b5-670ce047776a)

应该是未知原因导致重复生成了，但是菜单在上面的那个 z-index 40 里，被z-index 41的下方生成的给遮挡了。

**Comment by 88250** [comment]
好的，等早上 @Vanessa219 看一下吧。

我先睡了哦，晚安。

**Comment by zxhd863943427** [comment]
嗯，晚安，明天再说吧。

**Comment by Vanessa219** [comment]
第一个应该是报错了，没有选择关联就选择了属性，已经进行提示。第二个重现不了。

**Comment by zxhd863943427** [comment]
> 没有选择关联就选择了属性

其实是选中了关联的，点的有点快而已。

另外发现了另一个复现条件了，在一个protyle里面有多个镜像database.

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/61b6aaf9-2e42-491e-9ad8-e68d0f2de222)

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/7b3cc25f-fb9e-4504-bf1a-0c1ad2f86acd)

我创造了3个镜像database，所以就重复产生了3遍。

**Comment by zxhd863943427** [comment]
[database.sy.zip](https://github.com/siyuan-note/siyuan/files/13803770/database.sy.zip)

**Comment by zxhd863943427** [comment]
这个是database，我导出并导入到另一个工作空间可以复现。

**Comment by 88250** [comment]
初始化默认值的问题已经改进了，麻烦测试。

**Comment by zxhd863943427** [comment]
嗯，下午回来会打包测试一下。

**Comment by zxhd863943427** [comment]
经过测试，现在汇总是正常了，但是属性面板中出现了问题：

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/d257aa96-8a01-4de3-8ad0-bcfd323a6375)

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/eedec6af-6cc4-4d29-bacd-2d0533ec82c4)

报错在这个api上 ： /api/av/getAttributeViewKeys 。

另外我觉得对于属性面板，用户没有填的值最好也能返回默认值，屏蔽掉编辑过和没有编辑过的区别。

**Comment by zxhd863943427** [comment]
> 底层存储的列值结构是不能确定上层视图的行的，或者说这个依赖关系不能反过来看，否则就被上层视图（目前是表格）给框死了

话说D考虑的是什么视图？我考虑的是database实际上就是对于关系型数据库的模拟，行的每一列都是需要填充值，起码需要向上层提供的时候是有值的。

**Comment by 88250** [comment]
> 起码需要向上层提供的时候是有值的。

对，现在需要补齐这部分，比如上面说的属性面板，稍后改进。

**Comment by 88250** [comment]
getAttributeViewKeys  报错的情况麻烦导出一个文档以便测试。

**Comment by 88250** [comment]
> 这个是database，我导出并导入到另一个工作空间可以复现第二种情况。

还有属性面板补全字段这两个问题已经改进。

**Comment by 88250** [comment]
这个 issue 稍后关闭了，等后面发布 v2.12.0 以后再看看，如果还有问题，可以新开 issue 或者直接在这个 issue 上跟帖，谢谢。

**Comment by zxhd863943427** [comment]
ok，打包新版本后就会进行测试。

**Comment by zxhd863943427** [comment]
[database.sy.zip](https://github.com/siyuan-note/siyuan/files/13804945/database.sy.zip)

**Comment by zxhd863943427** [comment]
getAttributeViewKeys 的问题依旧，尝试查询子文档111、222、222内部的段落6666时都会出错，但查询没有添加到database的id不会出错。

**Comment by 88250** [comment]
多谢，稍后解决。
