### ISSUE TITLE
闪卡标题块支持文档大纲定位

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10039]
### In what scenarios do you need this feature?

![PixPin_2024-01-01_10-57-04](https://github.com/siyuan-note/siyuan/assets/154863885/d2d1618d-d93e-4c00-9f3d-3732612f8a48)
我习惯以最小标题块为单位制卡，以单独文档进行间隔重复，但是不想丢失与大标题的联系，面包屑可以看到母标题。当时看不到相邻子标题。原生大纲支持点击标题定位，但是闪卡内好像不支持

### Describe the optimal solution

闪卡在页签打开时，标题块支持文档大纲定位

### Describe the candidate solution

1. 提供可以查看相邻标题的方式（目前可行的是，用插件提取静态大纲，再用块右上角的引用查看，奈何静态大纲用起来不更新，也没有原生大纲直观和高效）
![image](https://github.com/siyuan-note/siyuan/assets/154863885/d5cc4029-5abc-4c56-ad43-34091beced20)

**Comment by 88250** [comment]
这个估计是无法支持，大纲只能限定在文档页签中定位。

关于“看不到相邻子标题”的问题请关注 https://github.com/siyuan-note/siyuan/issues/2613

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
