### ISSUE TITLE
标题块句首#不弹出标签选项

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10036]
### In what scenarios do you need this feature?

![PixPin_2023-12-31_10-47-02](https://github.com/siyuan-note/siyuan/assets/154863885/2bec1fa1-9c9f-4ae4-b683-b4379ac46fad)
我习惯在标题块句首打标签，这样在大纲看起来很直观，但每次打#比较麻烦。

### Describe the optimal solution

1. 通过#号修改标题级数很方便，但是一级标题修改需求不大，可以考虑一个#时候弹出菜单
2. 快捷键相比鼠标速度慢，而且打字也费时间

### Describe the candidate solution

提供标签弹出菜单快捷键（其实就是#的功能）

### Other information

祝 D 和 V 2024年新年快乐

**Comment by 88250** [comment]
一级标题虽然需求不大，但是还是有需求的，并且要保证设计的一致性，所以不考虑变更了。

感谢反馈，新年快乐。
