### ISSUE TITLE
提前复习当天稍晚刷新出的闪卡

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10044]
### In what scenarios do you need this feature?

例如昨天玩了一天，晚上要补复习，这样部分显示一天后的卡片，要在第二天晚上十点后才能刷新出来，这样就影响了第二天刷卡。

### Describe the optimal solution

希望能提前复习当天将要刷新，但还没有刷新的卡片。最好每天都是定时刷新，也即是到了第二天，就无论卡片是应当晚上刷新还是早上刷新，都能在特定的时间一次性全部刷新出来

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。

另外，思源里面的间隔重复不是按天计算的。
