### ISSUE TITLE
Database-bound block primary key supports setting static anchor text

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10049]
希望数据库的块引支持静态锚文本

### In what scenarios do you need this feature?

比如我搞了一个TODO数据库，我先前已经建立了一个以文献标题命名的文档，我现在想要建立一个待办，阅读xx文献
但是目前的话，即使手动更改了数据库主键的块引锚文本，刷新之后，又会变为原来的文档标题
![image](https://github.com/siyuan-note/siyuan/assets/60436214/cc884895-a63e-4bbe-a1e3-e36804cf4eab)
![image](https://github.com/siyuan-note/siyuan/assets/60436214/687cfde3-02bf-4fb5-8f29-24e50fdb54dd)

### Describe the optimal solution

希望数据库的主键块引支持静态锚文本

**Comment by 88250** [comment]
最新版已经屏蔽绑定块主键的右键菜单，暂时不考虑支持“静态锚文本”了，感谢提议。

**Comment by 88250** [comment]
补充一下：绑定块的主键渲染遵循动态锚文本渲染规则，即可以考虑使用块命名来改变此处的渲染。

**Comment by Achuan-2** [comment]
由于思源笔记的一个块可以属于多个数据库，有的时候是希望在不同数据库，这个块的命名是不同的
不支持修改锚文本的话其实挺难受的。
比如TODO这个数据库，我添加了一个todo《写一篇关于熬夜危害的博客》，将其转化为文档后，我可能就要对这个文档进行命名，比如《熬夜的危害》。现在思源的机制，数据库里的这个块主键自动变为《熬夜的危害》，就不像一个TODO名称了，如果我把这个文档的命名设置为《写一篇关于熬夜危害的博客》，那之后我把这个文档又想添加到《博客》这个数据库里，又想显示为《熬夜的危害》就会冲突

可以的话，还是非常希望数据库的块引也是支持静态锚文本的

**Comment by Achuan-2** [comment]
能否在绑定块的整个行的右键菜单添加「修改绑定块标题」呢？
![Clip_2024-06-02_17-06-28](https://github.com/siyuan-note/siyuan/assets/60436214/5d2eb4e7-4b91-4576-974f-95aef0b3c9a9)

**Comment by 88250** [comment]
正如前面所说，绑定块后显示的是块的动态锚文本，无法支持单独设置内容。

**Comment by Achuan-2** [comment]
没办法兼容静态锚文本显示吗

**Comment by 88250** [comment]
目前没有办法，我们先打开，后续有空再看看能否实现。

**Comment by Achuan-2** [comment]
谢谢，辛苦🙇‍♂️

**Comment by Achuan-2** [comment]
发了一个投票帖子：https://ld246.com/article/1730621536283

**Comment by TCOTC** [comment]
用户需求：

- https://ld246.com/article/1728823724405

**Comment by 88250** [comment]
> 正如前面所说，绑定块后显示的是块的动态锚文本，无法支持单独设置内容。

现在已经单独实现了主键内容构建 `getNodeAvBlockText`，应该可以类似 icon 一样通过自定义属性实现静态锚文本存取。

**Comment by TCOTC** [comment]
修改主键锚文本的交互应该怎么做？

**Comment by 88250** [comment]
估计是右键弹菜单吧

**Comment by TCOTC** [comment]
我感觉可以这样：如果在绑定块的条目的主键上右键，就在弹出的菜单顶上多加个锚文本输入框

![image](https://github.com/user-attachments/assets/6f2641c2-b28b-48be-8b0e-769cbed43bb4)

**Comment by SaXz2** [comment]
我觉得楼上的方案更好一点，右键菜单会多三四步，修改内容多了就有点繁琐了，如果可以像notion一样也行，不过考虑现在的文档块不支持链接或者块引用，不太好实现

**Comment by 88250** [comment]
图标就不支持设置静态锚文了，只有文档标题支持为不同的库设置不同的静态锚文本。

**Comment by 88250** [comment]
还是直接编辑单元格吧，不用菜单了。

**Comment by TCOTC** [comment]
我这里好像还不行，控制台会报错

**Comment by 88250** [comment]
开发环境下？贴一下报错

**Comment by TCOTC** [comment]
点击主键之后整个界面都动不了：

[video.webm](https://github.com/user-attachments/assets/e8371f2f-22b8-4712-b031-38a3291ccc3e)

![image](https://github.com/user-attachments/assets/17c7d5df-b413-4517-b7c7-f5f92d140cee)

**Comment by 88250** [comment]
确实有问题，稍后解决。

**Comment by TCOTC** [comment]
主键锚文本能不能支持换行？

**Comment by SaXz2** [comment]
![PixPin_2024-12-24_16-50-49](https://github.com/user-attachments/assets/c232a2d4-f359-47d0-ba6e-52bef628444c)
图标会出现对不齐的情况，出现在：自定义图标和动态图标

**Comment by TCOTC** [comment]
这个回复到 https://github.com/siyuan-note/siyuan/issues/13437 吧

**Comment by 88250** [comment]
不支持换行；复制锚文本的问题稍后改进 @Vanessa219

**Comment by TCOTC** [comment]
不支持换行的原因是什么？

**Comment by TCOTC** [comment]
这里的逻辑还有点问题，用户只要误触一下就会变成静态锚文本了：

[video.webm](https://github.com/user-attachments/assets/cde65e57-3b64-416f-b128-331b5577bb21)

**Comment by 88250** [comment]
> 不支持换行的原因是什么？

属性里用换行可能有问题

**Comment by 88250** [comment]
> 误触一下就会变成静态锚文本

@Vanessa219

**Comment by TCOTC** [comment]
> 属性里用换行可能有问题

我感觉这就跟纯文本主键一样，应该不会有啥问题

**Comment by 88250** [comment]
等继续看看需求

**Comment by TCOTC** [comment]
先记录 https://github.com/siyuan-note/siyuan/issues/13746
