### ISSUE TITLE
闪卡支持移动到新窗口快捷键/增加一键打开新窗口按钮

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10040]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/154863885/dc8a2f1e-09d4-4e9f-98dc-1ca0012896fd)
经测试，快捷键无法直接打开闪卡新窗口

### Describe the optimal solution

支持移动到新窗口快捷键

### Describe the candidate solution

在移动到页签旁边加个移动到新窗口

**Comment by Vanessa219** [comment]
出于以下问题，请确认是否还需要该特性。
* 打开新窗口只能用页签方式，无法像 alt+f 那样全屏
* 右侧已有很多按钮，按钮可能不添加了，

**Comment by AvoidantPerDis** [comment]
那算了吧
