### ISSUE TITLE
Show PDF tab title in full

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10045]
PDF页签鼠标悬浮不显示完整名称

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![PixPin_2024-01-01_21-22-16](https://github.com/siyuan-note/siyuan/assets/154863885/3daa7894-ba37-41f4-bd21-a064f18169fa)

### Expected result

PDF页签鼠标悬浮显示完整名称

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13804679/system-log.zip)

**Comment by Jiangshuon** [comment]
老哥似乎临近期末，高强度用思源啊，提了好多issue，哈哈

**Comment by AvoidantPerDis** [comment]
确实，我12.31用了6.5h思源。不过以前是在群里给D大上强度

**Comment by AvoidantPerDis** [comment]
人生第一次写年终总结也是用思源的日记+反链写完的

**Comment by AvoidantPerDis** [comment]
可以我只会Python，没办法pr，现在时间也不够，只能让DV辛苦一下了
