### ISSUE TITLE
软件有时候会卡死 点击任何按钮都失效 包括退出按钮

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

就是卡死

### Expected result

就是卡死

### Version environment

```markdown
- Version: 2.11.4
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13803941/system-log.zip)

**Comment by 88250** [comment]
这个问题在最新的 dev 版应该已经修复，感谢反馈。

**Comment by ywgdjryf** [comment]
一样  是很频繁的经常会卡死

**Comment by QQQOrange** [comment]
> 一样  是很频繁的经常会卡死，
> 
> 每次还会弄坏我一天的笔记数据，笔记回退到一天前，真的恶心。

你更新一下最新版试试，这个问题已经好久没遇到过。
