### ISSUE TITLE
Double-click the doc title image to preview

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10041]
### In what scenarios do you need this feature?

有时候想看题头图全图，发现右键和双击没反应，上下拖动又会丢失原来位置

### Describe the optimal solution

双击查看？

### Describe the candidate solution

定位到asset文件夹？

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/4279ac88-0b32-496e-8756-c5887a8690ba)

@Vanessa219 考虑在 链接 中的这个位置加个 打开 按钮？

**Comment by AvoidantPerDis** [comment]
我都没发现链接还可以用于本地图片，这样也能看了
