### ISSUE TITLE
Keep tabs visible when window shrinks

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10048]
### In what scenarios do you need this feature?

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/caa231d2-3566-4fa0-ad3d-e4a4d3902516)
如图，在27寸的显示器上是简单三等分布局，在14寸笔记本中间页面被挤压到消失，开关自适应宽度无效（分辨率都是2K）

### Describe the optimal solution

布局能够记住比例长宽自动调整大小

### Describe the candidate solution

提供固定布局样式？

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/154863885/3449d45f-bd55-49ef-b988-c5d4bed538e7)
另外，搜索，闪卡这些界面在切换屏幕后好像都会因为与已经保存的大小不同错位

**Comment by Vanessa219** [comment]
查看了多个软件，页签窗口被拖拽调整过大小后都不是使用百分比的，可能是在用户调整应用大小后想保持面板大小。目前可以改进的是页签窗口不压缩至最小，保持一个最小值，方便拖拽。

自适应宽度无效指的是页签被挤压后看不到么？

弹窗问题合并到 https://github.com/siyuan-note/siyuan/issues/10000 中

**Comment by AvoidantPerDis** [comment]
保持最小值也行，现在是拖不动

**Comment by AvoidantPerDis** [comment]
补个变化过程
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/c92de0f7-ed1c-4e7d-b7ed-1f400d1c3f8d)
