### ISSUE TITLE
docker nginx pdf.js导致不能访问

### ISSUE THREAD

**Issue by xibaoning** [siyuan-note/siyuan#10047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker pull 升级到最新版(2024/1/2),  F12观察网络发现 pdf.js端口仍然是6806, 但其他文件(比如 /stage/build/desktop/main.0e473a8f1a05dd34d107.js)端口正常, 由于pdf端口错误导致进不了笔记系统, 这个好像是老bug之前也出现过, 但好像一直没有从根本解决掉, 之前的帖子: https://github.com/siyuan-note/siyuan/issues/3566
降级到v2.11.1就能正常访问, 说明不是nginx配置问题, 希望官方查明原因, 如需远程协助请联系QQ 23763864

### Expected result

正常访问

### Version environment

```markdown
- Version: 今日pull的,不清楚版本,应该是最新版
- Operating System: docker
- Browser (if used): edge
```

### Log file

I 2024/01/02 12:20:08 process.go:36: received os signal [terminated], exit kernel process now
I 2024/01/02 12:20:08 conf.go:497: exiting kernel [force=false, execInstallPkg=1]
I 2024/01/02 12:20:08 database.go:1218: closed database
I 2024/01/02 12:20:08 conf.go:892: cleared workspace temp
I 2024/01/02 12:20:08 sync.go:672: sync websocket closed
I 2024/01/02 12:22:14 working.go:95: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/01/02 12:22:14 runtime.go:49: kernel is booting:
    * ver [1.6.3]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20211218]
    * workspace directory [/home/siyuan/Documents/SiYuan, data 297 MB]
    * pandoc [2.13]
I 2024/01/02 12:22:14 conf.go:250: local serve path [https://127.0.0.1:6806]
I 2024/01/02 12:22:14 serve.go:68: kernel is booting [http://0.0.0.0:6806]
I 2024/01/02 12:22:14 database.go:73: reinitialized database [/home/siyuan/Documents/SiYuan/temp/siyuan.db]
I 2024/01/02 12:22:14 conf.go:466: pre-init database size [4.1 kB]
I 2024/01/02 12:22:14 index.go:204: rebuilt database for notebook [20230117095122-kbgnbao] in [0.02s], tree stat [count=9, size=40 kB]
I 2024/01/02 12:22:14 index.go:204: rebuilt database for notebook [20221127161309-gityk23] in [0.02s], tree stat [count=2, size=79 kB]
I 2024/01/02 12:22:15 index.go:204: rebuilt database for notebook [20221024135432-c2whga9] in [0.97s], tree stat [count=86, size=3.7 MB]
I 2024/01/02 12:22:15 index.go:204: rebuilt database for notebook [20220512162000-r2matx2] in [0.11s], tree stat [count=13, size=543 kB]
I 2024/01/02 12:22:15 index.go:204: rebuilt database for notebook [20220512155856-o0lq2ji] in [0.16s], tree stat [count=6, size=567 kB]
I 2024/01/02 12:22:15 index.go:204: rebuilt database for notebook [20211211105607-v0gevam] in [0.07s], tree stat [count=39, size=100 kB]
I 2024/01/02 12:22:15 index.go:204: rebuilt database for notebook [20211206162526-824p52o] in [0.01s], tree stat [count=1, size=2.7 kB]
I 2024/01/02 12:22:15 index.go:214: resolving refs...
I 2024/01/02 12:22:15 index.go:355: resolved refs
I 2024/01/02 12:22:15 conf.go:487: post-init database size [6.7 MB], tree stat [count=156, size=5.0 MB]
I 2024/01/02 12:22:15 working.go:135: kernel booted

**Comment by xibaoning** [comment]
加入--servePath参数解决pdf.js访问问题, 记得之前好像取消这参数, 最近又加上了是么
command: [--ssl=true,--servePath=www.xxx.com:1009]

**Comment by 88250** [comment]
好的，那我关闭了，谢谢。
