### ISSUE TITLE
Filter conditions cannot be added to database table view check column

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当我尝试给checkbox添加筛选调节的时候，默认是未完成，当我就想给数据库添加未完成的筛选条件时，发现添加失败
需要先添加已完成的筛选条件，再改为未完成才能行的通
![思源数据库筛选反馈](https://github.com/siyuan-note/siyuan/assets/60436214/2f32d2bd-c560-4233-a2f3-bd38993865e1)

### Expected result

希望能够正常添加筛选条件，
此外，希望优化下交互，筛选能添加一个确定按钮
<img width="200" alt="Snipaste_2024-01-02_17-22-43" src="https://github.com/siyuan-note/siyuan/assets/60436214/e7862603-d9f0-4670-8a75-3846664a9110">

### Version environment

```markdown
- Version: 2.12.0
- Operating System: Win11
- Browser (if used):
```

### Log file

don't need it

**Comment by Vanessa219** [comment]
由于可以便捷的删除和修改，确定按钮就不加了，有点累赘。
