### ISSUE TITLE
希望数据库支持粘贴块引建立主键

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10051]
### In what scenarios do you need this feature?

之前的文档主要用块引moc来组织，如果想改为数据库组织的话，目前的方式主要靠粘贴块id，然后搜索文档建立，有点繁琐
如果能够直接通过粘贴块引自动建立主键，就会非常便捷了

### Describe the optimal solution

数据库支持粘贴块引建立主键

**Comment by 88250** [comment]
粘贴操作可能会有冲突，比如后续如果支持富文本单元格的话，应该是可以允许粘贴引用元素的，这种情况下就无法区分创建行了。为了避免潜在的问题，所以目前不考虑支持通过粘贴创建绑定行了，谢谢。
