### ISSUE TITLE
Only block marked as flashcards are hidden based on configuration

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

上个版本和最新版都有这问题，退出聚焦就会跑到最上面的标题块，且只显示标题

![6fdf7d8d3913a4ebef1840a89d11962](https://github.com/siyuan-note/siyuan/assets/67137548/9f6caaaf-aeda-4aaf-93f7-0cf8668cf18e)

![9e9f1d0bd75d2dcf940e272626b061b](https://github.com/siyuan-note/siyuan/assets/67137548/87b5ff12-13c5-4a8a-aaa3-6aeabdc66d14)

![846de8a3ec278fa88cbf9e2a7f8f7bb](https://github.com/siyuan-note/siyuan/assets/67137548/e8cbb6e6-2b99-4934-a198-392e8377efe7)

### Expected result

。。

### Version environment

```markdown
- Version: 最新和上一版
- Operating System: 
- Browser (if used):
```

### Log file

。。

**Comment by Vanessa219** [comment]
点击显示答案看看，是不是这个配置导致的
<img width="1069" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/67e63e84-0875-4f25-abef-e34e2696830b">

**Comment by Jiangshuon** [comment]
> 点击显示答案看看，是不是这个配置导致的 <img alt="image" width="1069" src="https://private-user-images.githubusercontent.com/970828/293708064-67e63e84-0875-4f25-abef-e34e2696830b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDQ5MDUsIm5iZiI6MTcwNDIwNDYwNSwicGF0aCI6Ii85NzA4MjgvMjkzNzA4MDY0LTY3ZTYzZTg0LTA4NzUtNGYyNS1hYmVmLWUzNGUyNjk2ODMwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNDEwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDhlNGY0YzFkZTY2Yjc5ZDk0NDVkNGUxNjhmZDA1ZDhhNTcyZDNlZjE1YmRkMWFkNDM3MDY5ZmZhODFhMzBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x97iB9TIgq0FENvSnEG86rc1m4z64utLhtjl1Q0fgyA">

是的，这个选项是打开的，不过我并没有把“测试标题"这个标题制作为闪卡

**Comment by Jiangshuon** [comment]
> 点击显示答案看看，是不是这个配置导致的 <img alt="image" width="1069" src="https://private-user-images.githubusercontent.com/970828/293708064-67e63e84-0875-4f25-abef-e34e2696830b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDQ5MDUsIm5iZiI6MTcwNDIwNDYwNSwicGF0aCI6Ii85NzA4MjgvMjkzNzA4MDY0LTY3ZTYzZTg0LTA4NzUtNGYyNS1hYmVmLWUzNGUyNjk2ODMwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNDEwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDhlNGY0YzFkZTY2Yjc5ZDk0NDVkNGUxNjhmZDA1ZDhhNTcyZDNlZjE1YmRkMWFkNDM3MDY5ZmZhODFhMzBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x97iB9TIgq0FENvSnEG86rc1m4z64utLhtjl1Q0fgyA">

这个问题应该是最近几个版本出现的

**Comment by Vanessa219** [comment]
应该是一直都有的问题，只是以前可能没有顶层标题或超级块之类的。

**Comment by Jiangshuon** [comment]
@Vanessa219 v大这个问题最新版又出现了

**Comment by Vanessa219** [comment]
退出聚焦以后是正常的，具体的问题是？

<img width="1010" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/99e53d8a-07d0-4433-9c1a-b1fe96ee1f15">

**Comment by Jiangshuon** [comment]
> 退出聚焦以后是正常的，具体的问题是？
> 
> <img alt="image" width="1010" src="https://private-user-images.githubusercontent.com/970828/318403160-99e53d8a-07d0-4433-9c1a-b1fe96ee1f15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjYxNDMsIm5iZiI6MTcxMTk2NTg0MywicGF0aCI6Ii85NzA4MjgvMzE4NDAzMTYwLTk5ZTUzZDhhLTA3ZDAtNDQzMy05YzFhLWIxZmU5NmVlMWYxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMDA0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGFjN2UwYzNhMjFhODYzYWU0ZTgwZDllZDg3ODRmOTdjNzI2NGZkYzg2YzI2MDkwZmNjMTk1ZmNmYzI4NmJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xFem5Ngjj1r2zyvaGuxTrg264nl3vhiWj-drVJGxdM4">

把heading2和“得到的”都制作成闪卡，然后复习到“得到的”时，点击退出聚焦（不要点击显示答案），发现会聚焦到heading2

**Comment by Vanessa219** [comment]
因为这个界面“得到的”被隐藏了，无法找到，只能定位到其他元素上。
