### ISSUE TITLE
使用 ctrl 按键区分 database 两种主键点击

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10053]
### In what scenarios do you need this feature?

目前database新建文档和打开文档的方式依然有一些繁琐，且逻辑不统一。归根结底，是我们希望 '更多' 这个位置所在的按钮能够承担多种功能：新建文档、打开文档、绑定到现有文档、更新绑定文档，这导致在使用一种方案实现所有操作的情况下会显得操作繁琐。

但是，这多种功能可以归类为两种要求：

1. 打开绑定的文档，假如原来没有绑定就新建一个同名文档并打开
2. 更新绑定的文档，假如原来没有绑定就新增绑定。

因此，只需要使用 ctrl 按键来辅助区分两种功能，那么就可以简化操作，统一操作逻辑。

### Describe the optimal solution

使用 ctrl 按键来辅助区分两种功能，假设把点击设定为第一种功能，ctrl+点击设定为第二种功能，那么需要实现下面的操作：

1. 直接点击按钮，假如已经绑定到块就直接打开块，没有就新建子文档后打开文档。
2. ctrl+点击按钮，假如未绑定到块就进行绑定，已有绑定就更新绑定。

### Other information

这个逻辑可能在移动端比较难实现，因为移动端没有ctrl按键。

这个方案实行后，可以考虑：

1. 移动端保留原种效果
2. 移动端使用长按实现更新绑定功能
3. 移动端的database菜单增加选项，可以从菜单中更新绑定
4. 移动端放弃更新绑定功能，让其使用电脑端完成操作。

**Comment by zxhd863943427** [comment]
另外，假如实现了这个需求，那可以考虑使用一个 icon 图标统一替代掉 `更多` 和 `更新` 这些文本内容。

**Comment by 88250** [comment]
关联社区投票贴 https://ld246.com/article/1704187613018

**Comment by 88250** [comment]
考虑后决定不改变交互了，谢谢。
