### ISSUE TITLE
数据库单行连续指定单选项只有第一个生效

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

上版本好像也会有延迟，这个版本稳定复刻了，没法连续选上2个以上单选项，必须点一下空白处，才能选第2个

### Expected result

能连续选择

### Screenshot or screen recording presentation

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/d01b9b2d-7d03-435d-b44a-8b7d8a89ab6a)

### Version environment

```markdown
- Version: 2.12
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/13808578/system-log.1.zip)

**Comment by AvoidantPerDis** [comment]
多选好像没问题

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/10052 中解决，谢谢。
