### ISSUE TITLE
按下回车后不断滚动并自动回顶

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

不确定是不是动态加载导致的，以前有类似bug，不过不频繁，这个bug比较恼人，重启一般可以解决

### Expected result

正常回车效果

### Screenshot or screen recording presentation

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/4b049116-a709-4e3e-b30b-2f46fa6d9ce5)

### Version environment

```markdown
- Version: 2.12
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log (2).zip](https://github.com/siyuan-note/siyuan/files/13809468/system-log.2.zip)

**Comment by 88250** [comment]
方便的话请导出 .sy.zip 发给我们测试看看 845765@qq.com

另外，还需要提供一下 设置 - 编辑器 - 动态加载块数 设置项的值。

**Comment by AvoidantPerDis** [comment]
@88250 动态加载块数128，我试过64也出现过，往上没测过

**Comment by AvoidantPerDis** [comment]
目前复现不出来，感觉是卡出来的bug
