### ISSUE TITLE
Improve database table view `Select` cell value input

### ISSUE THREAD

**Issue by lushan2866** [siyuan-note/siyuan#10052]
数据库多维列表，第一次无法键入，第二次才可以键入

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如GIF所示。
![GIF 2024-1-2 15-57-12](https://github.com/siyuan-note/siyuan/assets/5708881/34f52e57-e470-48a4-a6cc-0d1d27240e31)

### Expected result

一次键入。

### Version environment

```markdown
- Version: 2.12.0
- Operating System: win
- Browser (if used):
```

### Log file

暂无，如需补充再说。

**Comment by AvoidantPerDis** [comment]
#10057 连续单选也有这个bug
