### ISSUE TITLE
Back to maintain scroll position

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#10050]
### In what scenarios do you need this feature?

比如如下场景
1 页面如下，22在屏幕中间
![image](https://github.com/siyuan-note/siyuan/assets/97490782/5c4cf01c-8c1e-4e26-9359-243eca32cd48)
2 点击22行，跳转到子文档
3 点击“后退”，会变成下面这样，光标和22行移动到了最上面去
![image](https://github.com/siyuan-note/siyuan/assets/97490782/bbbd3720-ebc8-42e2-9ecb-f88aca2e584a)

一般前进后退时，光标和屏幕位置都会保持不变，在第三步点击“后退”时，光标回来了，但是是否能把屏幕位置也恢复成图1的样子，让22行居中

### Describe the optimal solution

点击链接跳转时记住屏幕的位置，点击“后退”时恢复屏幕位置，而不只是恢复光标位置

**Comment by Jiangshuon** [comment]
这本书超棒！还有王爽的《汇编语言》
