### ISSUE TITLE
emoji表情风格不统一

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#10062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/42575324/681fd022-d5be-46ae-b9b1-c81e03f7a7e1)

### Expected result

如图所示不知道从哪个版本开始，出现了风格不同的emoji表情，一部分是黑折的

### Version environment

```markdown
- Version: 2.12.0
- Operating System: 
- Browser (if used):
```

### Log file

none

**Comment by Temacc0531** [comment]
这个应该和系统字体有关，可以试试集市里面的Emoji插件

**Comment by 88250** [comment]
这个问题一直存在，这两天刚好定位到了，请关注 https://github.com/siyuan-note/siyuan/issues/8910
