### ISSUE TITLE
database的汇总多选时使用原值显示会导致整个database变成一列

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/fb08465b-37f3-401b-b40b-3b18a4b7c388)

原database

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/f87aee1f-dd39-4105-9dbb-7301daf33edf)

启用原值显示后

另外多加一个多选后莫名其妙就恢复了

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/08139ea4-a636-4c7f-aca5-dcbcc000750a)

### Expected result

正常显示

### Version environment

```markdown
- Version: 2.12.0
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

[database.sy.zip](https://github.com/siyuan-note/siyuan/files/13816520/database.sy.zip)

这是问题文件

**Comment by zxhd863943427** [comment]
需要提醒的是，在多加一个多选恢复正常后，汇总列的第二和第三个选项之间出现了一个逗号，这感觉并不是预期的显示效果。

**Comment by Vanessa219** [comment]
感谢反馈，已修复
