### ISSUE TITLE
嵌入块为文档类型时显示文档名

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#10064]
### In what scenarios do you need this feature?

目前嵌入块为文档类型时只会显示内容，不显示文档名。

1. 与标题块行为不一致
2. 使用 SQL 方法 random 随机漫游时没有文档名丢失了最重要的信息

### Describe the optimal solution

如题

**Comment by 88250** [comment]
打开嵌入块面包屑设置项就可以看到了。

**Comment by aGolduck** [comment]
好的，感谢
