### ISSUE TITLE
Add plugin function `lockScreen`

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10063]
实在抱歉，可能我两天前回复在code review区的评论没有通知，所以在这边重新发一遍。    
> 啊啊啊抱歉抱歉，应该是我没有表达清楚。我目前并不是需要感知锁屏操作。我的需求是需要插件能够直接调用锁屏操作，而不是感知锁屏操作。所以最后的这个更新不是我的需求，谢谢老大。

_Originally posted by @zxkmm in https://github.com/siyuan-note/siyuan/issues/10006#issuecomment-1872533362_

**Comment by zxkmm** [comment]
谢谢老大
