### ISSUE TITLE
`Untitled` is displayed when the original record primary key value of the related column is empty

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10067]
database 关联时，假如原表中主键为空值，会显示出id

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图所示：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/b84c89df-864b-4ab2-8555-72e1bfc025b0)

### Expected result

我个人是希望显示空白值，但是这样确实就找不到了对应的列了，不知道这个是不是bug。

### Version environment

```markdown
- Version: 2.12.0
- Operating System: win10 
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
似乎显示 `Untitled` 要更好一些？

**Comment by zxhd863943427** [comment]
我去问一下胖哥吧，看看wolai、flowus之类的是怎么处理的

**Comment by zxhd863943427** [comment]
哦还有一个刚刚发现的问题我就不打算单独开issue了，在不编辑的情况下，relation返回的默认值是null，而不是空列表[ ]，这会导致属性面板出错的
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/105f1fc1-8e8d-49fa-85d8-15facae59e40)
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/1abd0f1a-4e0d-4e11-a82a-1d8c9b471392)

**Comment by 88250** [comment]
收到。
