### ISSUE TITLE
数据库列名修改为领域，整个页面就卡住了，重启再改还是一样

### ISSUE THREAD

**Issue by 397334469** [siyuan-note/siyuan#10061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库列名修改为领域，整个页面就卡住了，重启再改还是一样
![image](https://github.com/siyuan-note/siyuan/assets/51410244/923908d0-85eb-48ff-bb3d-1cad3072cf47)

### Expected result

能修改

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请在默认主题下测试看看。

**Comment by 397334469** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/51410244/a027e9fc-14dd-458e-bc34-27a937eb31b2)
默认主题一样，主键这个修改列名有异常，这个输入框也取消不了，只能重启

**Comment by 88250** [comment]
主键列修改确实有问题，下个版本修复，感谢反馈。

@Vanessa219

**Comment by 88250** [comment]
我这里目前在开发版上已经无法重现问题了，麻烦等下个 dev 版本发布后帮忙测试看看。

Issue 先关闭了，如果后面还有问题请随时跟帖反馈给我们，多谢！
