### ISSUE TITLE
闪卡页面偶尔出现一个奇怪光标

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/62794181/fac38bd3-97d2-4270-be69-808e36684714)
这个光标不影响刷卡，但是当按到非刷卡快捷键的时候就会变成打字输入，撤销后可以继续刷卡，但是要是打出字来了，就必须用鼠标点击闪卡框后才能正常刷卡

### Expected result

期待修复

### Version environment

```markdown
- Version: 2,12
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
是否还有能够重现问题的文档，麻烦导出 .sy.zip 给我们看看 845765@qq.com

**Comment by QQQOrange** [comment]
> 是否还有能够重现问题的文档，麻烦导出 .sy.zip 给我们看看 [845765@qq.com](mailto:845765@qq.com)
[system-log.zip](https://github.com/siyuan-note/siyuan/files/13815001/system-log.zip)
这个

**Comment by 88250** [comment]
这个是日志文件，需要的是文档导出的 .sy.zip 哦。

**Comment by QQQOrange** [comment]
> 这个是日志文件，需要的是文档导出的 .sy.zip 哦。

要导出哪一个文档呢

**Comment by 88250** [comment]
截图里面有光标的这个，需要可以重现再导出哦。

**Comment by 88250** [comment]
老铁，还有这个可以重现问题的文档吗？

**Comment by QQQOrange** [comment]
> 老铁，还有这个可以重现问题的文档吗？

尴尬 没在出现过了

**Comment by 88250** [comment]
收到，那我们暂时先关闭了，后面如果还有问题请随时跟帖，谢谢。

**Comment by QQQOrange** [comment]
> 收到，那我们暂时先关闭了，后面如果还有问题请随时跟帖，谢谢。

再次出现了，附上闪卡文件和截图
![image](https://github.com/siyuan-note/siyuan/assets/62794181/d2dd17f6-08b3-41fe-b9f7-8311d3a012f8)
[1.1从自然界到人类社会的巨大飞跃.sy.zip](https://github.com/siyuan-note/siyuan/files/13853036/1.1.sy.zip)

**Comment by 88250** [comment]
里面闪卡太多了，我一时半会无法找到张卡片，能否制作一个能够重现问题的最小数据集，谢谢。

**Comment by QQQOrange** [comment]
> 里面闪卡太多了，我一时半会无法找到张卡片，能否制作一个能够重现问题的最小数据集，谢谢。

这个我咋整啊

**Comment by 88250** [comment]
复习到的时候编辑一下看看。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月9日(周二) 下午3:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 闪卡页面偶尔出现一个奇怪光标 (Issue #10060)




  
里面闪卡太多了，我一时半会无法找到张卡片，能否制作一个能够重现问题的最小数据集，谢谢。
  
这个我咋整啊

**Comment by QQQOrange** [comment]
> 复习到的时候编辑一下看看。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月9日(周二) 下午3:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 闪卡页面偶尔出现一个奇怪光标 (Issue #10060) 里面闪卡太多了，我一时半会无法找到张卡片，能否制作一个能够重现问题的最小数据集，谢谢。 这个我咋整啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

okok 下次遇见的时候 我试试

**Comment by QQQOrange** [comment]
> 复习到的时候编辑一下看看。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月9日(周二) 下午3:28 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 闪卡页面偶尔出现一个奇怪光标 (Issue #10060) 里面闪卡太多了，我一时半会无法找到张卡片，能否制作一个能够重现问题的最小数据集，谢谢。 这个我咋整啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

知道了，和具体闪卡的内容没关系，编辑当前闪卡后切换到别的应用再回来就会出现。
如果是修改的闪卡的话，修改完成后点击闪卡窗口，光标消失，切换应用后会再次出现，并且就是编辑的形式，刷卡快捷键失效。
如果上一张卡编辑过，那么下一张的页面切换窗口后回来，卡片最前面就会出现光标，可正常使用刷卡快捷键，但是其他按键就是编辑

**Comment by 88250** [comment]
@Vanessa219 帮忙看看。

**Comment by Vanessa219** [comment]
下个版本改进
