### ISSUE TITLE
闪卡复习页面锁屏后再解锁，不能直接使用快捷键刷卡

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题

### Expected result

如题

### Screenshot or screen recording presentation

无

### Version environment

```markdown
- Version: 2.12.0
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
解锁后会重新刷页面，需要再次打开闪卡。这个是不是和上次说的是一个问题？

**Comment by QQQOrange** [comment]
> 解锁后会重新刷页面，需要再次打开闪卡。这个是不是和上次说的是一个问题？

不是不是。上次是点进闪卡页面之后，不能立刻用快捷键刷卡，需要用鼠标点一下闪卡复习的那个框。现在是这个问题没有了，但是新的问题是我在闪卡复习的页面锁屏之后。再解锁，那么呈现的还是这个闪卡复习的页面，在这个页面里面还是要先点一下闪卡复习的框，然后再使用快捷键才能刷卡。

场景不一样

**Comment by QQQOrange** [comment]
> 是类似这个界面的闪卡么？是的话解锁后这个界面是没有的，会恢复到主界面。
> 
>  QQ20240105-091233-HD.mp4

就是桌面端正常按alt+0出现的闪卡复习页面

**Comment by Vanessa219** [comment]
那对的，参照视频总，无法重现你说的问题。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
