### ISSUE TITLE
macOS 10.15.5 下载dmg安装包安装后打开，界面为一片空白

### ISSUE THREAD

**Issue by xiaotoucai** [siyuan-note/siyuan#1007]
### 描述问题 Describe the problem

macOS 10.15.5 下载dmg安装包安装后打开，界面为一片空白

### 期待的结果 Expected result

提供一个可以使用的界面

### 截屏或录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/63988708/104150998-c53c2900-5416-11eb-8567-6034152de1a6.mov

### 版本环境 Version environment

* 版本 Version：10.15.5
* 操作系统 Operating system：macOS
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，请尝试使用最新版本 v0.5.9。如果还是空白请删除 ~/.siyuan 配置文件夹后重启，如果还是空白，请贴一下日志，谢谢。
