### ISSUE TITLE
Add internal kernel API `/api/filetree/upsertIndexes` and `/api/filetree/removeIndexes`

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10079]
局部的索引重建及API支持

### In what scenarios do you need this feature?

想要一个局部的索引重建。而不是全局的。
在有的时候文件的更改，实际上用户是已知的，比如说在资源管理器中，从外部文件夹直接将.sy文件拖出来到对应的sy文档文件目录下。但是这个时候肯定需要重建索引，那么一个局部的索引重建就显得有必要，而且不光提供这个功能特性，还可能需要api的支持。

### Describe the optimal solution

它可以指定以哪个文档节点或者笔记本为根部，然后将所有的后代文件进行索引的重建。

但是在有的时候可能用户自己清楚在某个文件夹下新增了哪些文件，那么只需要对新增的文件进行索引重建即可。
比如说，我原来有一个文件夹下面有500个.sy文件，那这样的话我新增了10个，可能要做510次的索引重建，这样的话其实是很不划算的，如果用户能指定对哪个文件进行索引重建，用户只需要给出一个列表来，相当于对他登记入库。
这就很好了。

反正通过提供不同的api来说可能会比较好。

**Comment by 88250** [comment]
下个版本提供两个内部内核 API 来支持根据指定的路径重建/删除索引。这两个 APIs 的参数都是传入一个路径数组，路径为相对于工作空间的文件路径，比如：

* `/data/20210808180117-czj9bvb/20200812220555-lj3enxa.sy`：以 .sy 结尾的话就作为实际的文档路径了
* `/data/20210808180117-czj9bvb/20200812220555-lj3enxa/`：以 `/` 结尾的话会作为父目录路径，API 会进行批量操作
