### ISSUE TITLE
个别emoji表情，页面渲染样式与所见不同

### ISSUE THREAD

**Issue by codercplus** [siyuan-note/siyuan#10076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

对于“双感叹号”表情，emoji列表中展示样式为**红色图形**，但实际输入后，页面中展示为**黑白字符**。

补充描述：

1. 思源笔记中，如果手动增加CSS样式，将字体设为Segoe UI Emoji，则会显示正常；

![Snipaste_2024-01-04_16-06-00](https://github.com/siyuan-note/siyuan/assets/63757163/acb6f7a4-ec26-49a2-9043-210369972f85)

2. 同一台电脑中，其他不同应用程序对此表情的展示有所不同；
①chrome中显示为黑白字符；②firefox、记事本、WORD中，显示为彩色图形。
![Snipaste_2024-01-04_15-57-23](https://github.com/siyuan-note/siyuan/assets/63757163/61b4b985-a6db-4d57-a117-30c5bd0c8d68)

### Expected result

应展示为彩色图形，与预览的emoji列表样式相一致。

### Version environment

```markdown
- Version: v2.12.1-dev1
- Operating System: Windows 11 专业版  23H2
- Browser: 
Chrome版本 120.0.6099.130（正式版本） （64 位），
Firefox版本120.0.1 (64 位)
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13827637/siyuan.log)

**Comment by 88250** [comment]
正如你的测试结果，这个受字体影响，需要字体支持。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
