### ISSUE TITLE
输入“双感叹号“emoji时，只能作为文字显示，不能作为表情显示

### ISSUE THREAD

**Issue by codercplus** [siyuan-note/siyuan#10074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当通过表情，选择双感叹号的emoji时，实际输入效果变成了仅为文字（两个普通感叹号字符），无表情颜色等，与所见效果不一致。

### Expected result

应显示为红色emoji表情

### Screenshot or screen recording presentation

![Snipaste_2024-01-04_02-00-35](https://github.com/siyuan-note/siyuan/assets/63757163/bd4583e4-3cc5-49a7-99c1-e85715ad785c)

### Version environment

```markdown
- Version: v2.12.0
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13822009/siyuan.log)

**Comment by 88250** [comment]
你好，这个问题应该已经在 https://github.com/siyuan-note/siyuan/issues/8910 中修复，方便的话请下载最新 dev 版进行测试，谢谢。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
