### ISSUE TITLE
最新版资源文件端口错误

### ISSUE THREAD

**Issue by Zynismus16** [siyuan-note/siyuan#10070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/61103213/a757682f-77f8-482d-b4f2-f487148e6278)
调用该文件会自带端口，我使用的是bridge模式，主机端口为6688，访问域名+6688加载该文件变成了域名 +6806
![image](https://github.com/siyuan-note/siyuan/assets/61103213/e50b0a9b-37e9-495b-8797-1579abd87042)

### Expected result

让其跟随当前访问域名+端口

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/61103213/a757682f-77f8-482d-b4f2-f487148e6278)
![image](https://github.com/siyuan-note/siyuan/assets/61103213/e50b0a9b-37e9-495b-8797-1579abd87042)

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

D 2024/01/03 15:47:19 conf.go:108: check device locale failed [detect: not detected], using default language [en_US]
I 2024/01/03 15:47:19 conf.go:250: local serve path [http://127.0.0.1:6806]
I 2024/01/03 15:47:19 serve.go:68: kernel is booting [http://0.0.0.0:6806]
I 2024/01/03 15:47:19 database.go:73: reinitialized database [/home/siyuan/Documents/SiYuan/temp/siyuan.db]
I 2024/01/03 15:47:19 conf.go:466: pre-init database size [4.1 kB]
I 2024/01/03 15:47:19 index.go:214: resolving refs...
I 2024/01/03 15:47:19 index.go:355: resolved refs
I 2024/01/03 15:47:19 conf.go:487: post-init database size [4.1 kB], tree stat [count=0, size=0 B]
I 2024/01/03 15:47:19 working.go:135: kernel booted

### More information

无

**Comment by 88250** [comment]
1.6.3 应该是很古老的版本了，建议升级到最新版后再试试。
