### ISSUE TITLE
Snapshot comparison interface supports key selection of files

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10078]
数据快照比对新增功能按键

### In what scenarios do you need this feature?

在比对数据快照的时候，希望在不同的文件之间进行切换。
目前来说只能通过鼠标点击的方式来进行选择，这样的话感觉还需要移动鼠标。

一个解决方式是使用键盘按键 ↑、↓，以此来检查对应的文件变化情况。同时有可能的话，可以支持page up / down，home、end。
![FXT$6RQ97JAX7 S5J (4JR8](https://github.com/siyuan-note/siyuan/assets/54077803/e85d7fc3-87e5-40b5-bc32-49cd26c8ff3c)

### Describe the optimal solution

添加两个按键即可实现最方便的切换。

**Comment by Vanessa219** [comment]
没有分页，就不添加 page up / down

**Comment by LGRemdo** [comment]
> 没有分页，就不添加 page up / down

可以如愿的添加其他的按键对不对？

**Comment by Vanessa219** [comment]
嗯
