### ISSUE TITLE
数据库条目的菜单按钮位置问题

### ISSUE THREAD

**Issue by CKlimeths** [siyuan-note/siyuan#10080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

拖动数据库横向滚动条后，数据库条目的按钮也向左移动，出现在错误的位置，可能遮挡左侧侧栏的面板。

### Expected result

拖动数据库横向滚动条后，数据库条目的按钮保持原位。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/86591721/44aff184-6704-49af-a21b-fc330790fe3b)
![image](https://github.com/siyuan-note/siyuan/assets/86591721/a231b757-53ec-4ee3-949b-d2523c137287)
![image](https://github.com/siyuan-note/siyuan/assets/86591721/dc499e16-68d9-4e65-bdaa-6e98c474ed38)

### Version environment

```markdown
- Version: v2.12.0
- Operating System: Win10 LTSC2021
- Browser (if used): None
```

### Log file

None

### More information

None

**Comment by Vanessa219** [comment]
昨天刚修复 942a434f0c9dd12351bd5d36e00100551c82d804
