### ISSUE TITLE
移动笔记原引用文件应自动删除、增加删除图片文件和一键清理无引用 assets 文件功能

### ISSUE THREAD

**Issue by ZIP97** [siyuan-note/siyuan#1008]
1. 把一个 md 文件移动到该笔记本下另一个文件夹，**原来引用的图片依然在移动前的 assets 下面**。也就是说，移动笔记之后，引用的文件会在两个地方，无用文件积压更加严重。
2. 删除已经插入的本地图片应该有两种方式：删除图片引用、**删除图片文件**（目前实现这个功能要定位到 assets 下的文件，然后再删除。这个功能是必须的吧，否则会积压很多未引用的垃圾图片；而且手工删除会容易误删、删除效率低下）
2. 手工删除本地图片文件之后，**md 编辑器里面依然存在**（正常应该是消失的），再次点击图片不再有引用路径了，然而右键定位到文件会**定位到错误的文件上面**。
3. 针对无用文件的积压问题，希望可以有**一键清理 assets 文件下的无引用文件**的功能（或者思源支持插件开发之后 有人能看到这个需求 : )

**Comment by 88250** [comment]
你好，设置 - 资源里面已经有清理无引用资源的功能，但是反向的功能（手动删除资源文件以后 md 排版不删除）这个应该不会引入，谢谢。

**Comment by zhaoyao91** [comment]
在文档中删除图片时，可以自动删除无引用的图片吗
