### ISSUE TITLE
Improve internal kernel API `/api/av/setAttributeViewBlockAttr`

### ISSUE THREAD

**Issue by InEase** [siyuan-note/siyuan#10084]
希望能开放关于数据库操作的内核API

### In what scenarios do you need this feature?

再次感谢D大V姐在思源笔记上的辛勤耕耘！

目前思源数据库的功能已经趋于完备，也有越来越多用户使用数据库存储结构性信息。但是同时关于`文档级属性面板`的呼声也越来越大。虽然说目前可以通过`Shift + 点击块标`的方式查看属性面板，但是总归没有直接在文档下显示出来方便，直观。相关讨论可见：

- [官方有无计划支持在文档开头显示数据库属性 - 链滴](https://ld246.com/article/1704444484983)
- https://github.com/siyuan-note/siyuan/issues/2829#issuecomment-974774605

但是官方也多次表示，`文档级属性面板`这方面需要靠社区支持，因为思源不仅仅是文档具有属性，所有块都可以设置属性，考虑到操作，界面的统一性，官方不会推出这方面的功能：

- https://github.com/siyuan-note/siyuan/issues/2829#issuecomment-1750699655
- https://github.com/siyuan-note/siyuan/issues/2829#issuecomment-975441250
- https://github.com/siyuan-note/siyuan/issues/10033#issuecomment-1872525187
- https://ld246.com/article/1704444484983/comment/1704445641190

> 但是还是想D大V大再考虑一下！！事实上，因为文档块还是有其特殊性，它是其他所有块的载体，给它特殊待遇一下也不是不行叭QAQ，因为目前官方对各种数据库类型的支持已经相当完善了，只需要把属性面板下放到标题下方即可完成，减轻社区开发者的工作量和后期维护成本～

但是目前这个功能仍然是刚需，社区的相关插件目前只支持显示内置属性，尚不支持显示数据库属性，主要的困难就在于目前数据库数据`获取`和`修改`的API实在是有点复杂，而且处于开发阶段还不稳定，不敢轻易对接。

https://github.com/InEase/SiYuan-Attributes-Panel/issues/4#issuecomment-1876578298

虽然官方曾表示等后期数据库公测稳定之后再考虑开放API：

https://github.com/siyuan-note/siyuan/issues/9898#issuecomment-1859171242

但是考虑到：

1. 目前这个功能非常刚需，社区呼声较大

2. 目前数据库的底层结构已经趋于稳定，可以尝试开放API给开发者测试

所以希望D大V姐可以再考虑一下！可以暂时先开放一些测试接口给插件测试～暂时仅限于**查询**和**修改**即可～正好也可以测试相关bug嘛，麻烦D大V姐了，祝思源越来越好～

### Describe the optimal solution

增加数据库操作相关内核API

**Comment by 88250** [comment]
请帮忙整理一下目前需要的 APIs，谢谢。

**Comment by InEase** [comment]
我去，刚刚去整理的时候，突然发现，我之前一直以为修改属性必须要通过`transaction`，忽略了上面还有一个`setAttributeViewBlockAttr`，如果用`transaction`的话肯定不行，太复杂了，但是`setAttributeViewBlockAttr`这个就已经很简洁了。（捂脸

**Comment by InEase** [comment]
辛苦D大了！那看起来好像做属性面板所需的**数据库查改**已经没问题啦~但是还有几个小点：

1. 在修改属性的时候连续发送了三个请求，如果由外部调用`setAttributeViewBlockAttr` API修改对应的属性之后，不调用`transaction` 会导致其他问题吗~
![image](https://github.com/siyuan-note/siyuan/assets/88016816/87eaa1fc-6c47-48b2-9efd-261b066a6eed)

2. 在数据读取方面，目前已经有API `/api/av/getAttributeViewKeys` 可以通过`块id`查询关联的数据库内容，主要问题就是API返回的信息有点太多了，解析起来可能要花点功夫，如果可以以键值对的方式返回就更加方便了（参考飞书多维表格 https://open.feishu.cn/document/server-docs/docs/bitable-v1/app-table-record/list ）。不过问题不大，返回的信息丰富一点也是一个好处，这方面暂时应该不需要另外设计API啦~

3. 其实属性面板的API已经齐了（只是之前没看到，捂脸），但是如果要完善插件体系，可能还需要以下API：
    1. 在数据库中增加一列：对应用户在页面中增加属性
    2. 在数据库中增加 / 删除某一行：例如导入数据时，比如让数据库与子文档对应
    3. 添加`Eventbus`事件，（例如修改单元格数据，增删行列等）：可以借助插件实现一些自动化操作
 
目前暂时想到的就这些，辛苦D大V大~

**Comment by InEase** [comment]
诶不过修改数据的时候发现，有几个类型（日期，单选，多选）目前好像还是通过`transaction`完成修改的嘛，这方面的修改API可不可以也使用`setAttributeViewBlockAttr`，这样会方便很多！谢谢~

https://github.com/siyuan-note/siyuan/blob/cb6a843cd9570b443b4b0775660b1cd49353951a/app/src/protyle/render/av/blockAttr.ts#L204-L219

**Comment by zxhd863943427** [comment]
据我观察，不使用transaction只会有一个问题：没有撤回功能了。

**Comment by 88250** [comment]
> 辛苦D大了！那看起来好像做属性面板所需的**数据库查改**已经没问题啦~但是还有几个小点：
> 
> 1. 在修改属性的时候连续发送了三个请求，如果由外部调用`setAttributeViewBlockAttr` API修改对应的属性之后，不调用`transaction` 会导致其他问题吗~
>    ![image](https://private-user-images.githubusercontent.com/88016816/294542117-87eaa1fc-6c47-48b2-9efd-261b066a6eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjI4NjgsIm5iZiI6MTcwNDUyMjU2OCwicGF0aCI6Ii84ODAxNjgxNi8yOTQ1NDIxMTctODdlYWExZmMtNmM0Ny00OGIyLTllZmQtMjYxYjA2NmE2ZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA2MjkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTczZTE4Zjk2NjYzNWM1ZmU2NzM0OTk1YTZlY2Y3MzlkZWY5MWUxOTRhMmY3MTEzYWU5YWVjODVmMjljZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qKuB0_LGebXnaokX7BZuOZLx3qBCBiP_2er28dB-LE)
> 2. 在数据读取方面，目前已经有API `/api/av/getAttributeViewKeys` 可以通过`块id`查询关联的数据库内容，主要问题就是API返回的信息有点太多了，解析起来可能要花点功夫，如果可以以键值对的方式返回就更加方便了（参考飞书多维表格 https://open.feishu.cn/document/server-docs/docs/bitable-v1/app-table-record/list ）。不过问题不大，返回的信息丰富一点也是一个好处，这方面暂时应该不需要另外设计API啦~
> 3. 其实属性面板的API已经齐了（只是之前没看到，捂脸），但是如果要完善插件体系，可能还需要以下API：
>    
>    1. 在数据库中增加一列：对应用户在页面中增加属性
>    2. 在数据库中增加 / 删除某一行：例如导入数据时，比如让数据库与子文档对应
>    3. 添加`Eventbus`事件，（例如修改单元格数据，增删行列等）：可以借助插件实现一些自动化操作
> 
> 目前暂时想到的就这些，辛苦D大V大~

1. 我这里看在 属性面板 - 数据库 中修改只有一个请求
   
   ![image](https://github.com/siyuan-note/siyuan/assets/873584/a0d0e90e-6370-4d98-9428-d1d75360cb1c)

   不调用 transaction 不会有影响。
2. 嗯
3. 目前 属性面板 - 数据库 暂时不支持新建列、删除列和调整排序列，后面再考虑支持；自动化相关触发机制也要等后面一点考虑

---

> 诶不过修改数据的时候发现，有几个类型（日期，单选，多选）目前好像还是通过`transaction`完成修改的嘛，这方面的修改API可不可以也使用`setAttributeViewBlockAttr`，这样会方便很多！谢谢~
> 
> https://github.com/siyuan-note/siyuan/blob/cb6a843cd9570b443b4b0775660b1cd49353951a/app/src/protyle/render/av/blockAttr.ts#L204-L219

目前确实是这样的，下个版本应该可以通过 `setAttributeViewBlockAttr` 进行支持。

**Comment by 88250** [comment]
@InEase 刚刚看了下，`setAttributeViewBlockAttr` 接口实际上是支持传入任何类型的 value 的，只是目前前端较为复杂，为了复用界面组件的一些逻辑所以走的是 transaction，插件的话这些逻辑应该都是自己开发的，所以不存在这个复用，直接用这个接口并传入列类型对应的 value 就行了。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by InEase** [comment]
好的，收到收到～！因为周末有些事情没有及时回复，感谢！

**Comment by 88250** [comment]
考虑了下，后续会单独提供内核接口 https://github.com/siyuan-note/siyuan/issues/10160
