### ISSUE TITLE
导入md图片如果是缩放的，显示不出来，希望优化一下

### ISSUE THREAD

**Issue by Celestial32085** [siyuan-note/siyuan#10092]
### In what scenarios do you need this feature?

在Typora里的图片缩放，直接导入到思源显示失败

### Describe the optimal solution

希望官方可以稍微优化下

**Comment by 88250** [comment]
麻烦上传实例文件或者展示 md 代码，谢谢。

**Comment by Celestial32085** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/65842560/f0a996db-4fa2-4fc7-add0-5aa1a7efd53b)

<img src="images/2022-10-18_11-00-29.jpg" alt="2022-10-18_11-00-29" style="zoom:80%;" />

**Comment by Celestial32085** [comment]
md代码：<img src="images/2022-10-18_11-00-29.jpg" alt="2022-10-18_11-00-29" style="zoom:80%;" />

**Comment by Celestial32085** [comment]
<img src="images/2022-10-18_11-00-29.jpg" alt="2022-10-18_11-00-29" style="zoom:80%;" />

**Comment by Celestial32085** [comment]
代码“<img src="images/2022-10-18_11-00-29.jpg" alt="2022-10-18_11-00-29" style="zoom:80%;" />”

**Comment by Celestial32085** [comment]
img src="images/2022-10-18_11-00-29.jpg" alt="2022-10-18_11-00-29" style="zoom:80%;" /

**Comment by 88250** [comment]
抱歉，思源不支持大部分 HTML 元素导入，对于图片仅支持 Markdown 语法：`![foo](bar.jpg)`。
