### ISSUE TITLE
Improve `F3` to prevent creating duplicated doc

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10091]
希望 ctrl+F3 功能 改为查找现有同名文档，如果没有再创建。

### In what scenarios do you need this feature?

ctrl+F3 （新建文档名为）功能，目前会把选择文字转为引用，但问题是会产生同名文档。

### Describe the optimal solution

希望 ctrl+F3 （新建文档名为）功能，改为查找现有同名文档，如果没有再创建。有就使用它做为引用。

**Comment by 88250** [comment]
@Vanessa219 需要关注已有的 issues：

* https://github.com/siyuan-note/siyuan/issues/6107
* https://github.com/siyuan-note/siyuan/issues/6053
* https://github.com/siyuan-note/siyuan/issues/6854
* https://github.com/siyuan-note/siyuan/issues/6420
