### ISSUE TITLE
聚焦无法退出导致文档异常卡顿

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

聚焦无法退出，不清楚什么导致的，正在尝试复现。通过折叠大标题发现流畅度提升，可能是一口气加载了全部的块？

### Expected result

流畅浏览

### Screenshot or screen recording presentation

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/0d40701d-9516-42e7-8239-14da135d4204)

### Version environment

```markdown
- Version: 2.12.1dev2
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13850143/system-log.zip)

**Comment by AvoidantPerDis** [comment]
之前点到过保持已加载内容，现代无法退出

**Comment by AvoidantPerDis** [comment]
重装也没用诶

**Comment by AvoidantPerDis** [comment]
回退2.12也不行

**Comment by AvoidantPerDis** [comment]
我聚焦一下再退出又好了

**Comment by AvoidantPerDis** [comment]
额，虽然解决了，但感觉确实是个bug，因为我保存布局就能稳定复现

**Comment by 88250** [comment]
估计得制作一个能够重现问题的数据集，否则不好排查，谢谢。
