### ISSUE TITLE
移动块时如果文档内存在同名数据库将无法区分

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10102]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/154863885/b6f299a4-ef1f-4ee4-8424-f1f7ac4e6ab7)
如图，不知道哪个是文档

### Describe the optimal solution

为数据库添加标识
![image](https://github.com/siyuan-note/siyuan/assets/154863885/7119eea9-04c9-43f1-9496-79eedacb8959)

### Describe the candidate solution

隐藏数据库

**Comment by AvoidantPerDis** [comment]
只有移动时进行搜索才会出现，用文档树不会

**Comment by AvoidantPerDis** [comment]
奇怪的是好像该现象跟时间早晚没关系，图中文档建立时间并不相同

**Comment by 88250** [comment]
好像和数据库没有关系吧？移动面板中列出的都是文档块，没有数据库块的。

**Comment by AvoidantPerDis** [comment]
怪了，那我也不知道为啥有重复了

**Comment by 88250** [comment]
试试重建索引。
