### ISSUE TITLE
可以单独购买 webdav的权限吗？

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#10109]
### In what scenarios do you need this feature?

因为有nas 没必要用官方的云同步 所以就只想买s3 webdav这样的权限 不知道是按年 还是永久

### Describe the optimal solution

哎

### Describe the candidate solution

哎

### Other information

哎

**Comment by edward-kyle** [comment]
官网有这个售卖选项
https://b3log.org/siyuan/pricing.html
![Clip_2024-01-08_17-25-41](https://github.com/siyuan-note/siyuan/assets/78415230/17a1b60f-857f-49f2-8801-200717dfb084)

**Comment by zhuhaisto** [comment]
好叻 感谢 看到了 真便宜 还是永久版
________________________________
发件人: ***@***.*** ***@***.***> 代表 BeforetheAbyss ***@***.***>
发送时间: 2024年1月8日 01:26
收件人: siyuan-note/siyuan ***@***.***>
抄送: zhuhaisto ***@***.***>; Author ***@***.***>
主题: Re: [siyuan-note/siyuan] 可以单独购买 webdav的权限吗？ (Issue #10109)


官网有这个售卖选项
https://b3log.org/siyuan/pricing.html
Clip_2024-01-08_17-25-41.png (view on web)<https://github.com/siyuan-note/siyuan/assets/78415230/17a1b60f-857f-49f2-8801-200717dfb084>

―

**Comment by 88250** [comment]
我关闭了，谢谢。
