### ISSUE TITLE
希望可以提供是否进入聚焦的设置

### ISSUE THREAD

**Issue by oufu99** [siyuan-note/siyuan#10100]
### In what scenarios do you need this feature?

大部分时候都只是想阅读,而不用进入聚焦,但是查阅列表的时候,很容易误点击,然后就会进入聚焦模式

### Describe the optimal solution

在设置中添加一个开关,用于控制点击了元素是否进入聚焦状态,如果关闭了聚焦这个功能,点击了列表的元素也不会进入聚焦模式

**Comment by 88250** [comment]
你好，这个之前讨论过很多次了，我们不会考虑提供设置项来关闭这个特性，谢谢。
