### ISSUE TITLE
Add internal kernel API `/api/repo/getRepoFile`

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10101]
支持从快照中获取文件

### In what scenarios do you need this feature?

目前的 api 支持获取快照列表、快照对比、回滚快照，但是没有办法从快照中提取单个文件，无法指定回滚一个部分。希望能增加一个这个功能或 api

### Describe the optimal solution

最好的角度来说，希望能在数据快照对比和文档右键菜单的文档历史里找到快照并回滚

### Describe the candidate solution

如果不行或太麻烦，那希望能够根据快照文档id返回文档，目前的打开快照文档的api直接返回的是文档渲染后的dom，希望能提供一个api直接返回sy文件或其他类型文档本身。

**Comment by 88250** [comment]
麻烦描述一下入参和返回值。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月7日(周日) 晚上8:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 支持从快照中获取文件 (Issue #10101)




 
In what scenarios do you need this feature?
 
目前的 api 支持获取快照列表、快照对比、回滚快照，但是没有办法从快照中提取单个文件，无法指定回滚一个部分。希望能增加一个这个功能或 api
 
Describe the optimal solution
 
最好的角度来说，希望能在数据快照对比和文档右键菜单的文档历史里找到快照并回滚
 
Describe the candidate solution
 
如果不行或太麻烦，那希望能够根据快照文档id返回文档，目前的打开快照文档的api直接返回的是文档渲染后的dom，希望能提供一个api直接返回sy文件或其他类型文档本身。
 
Other information
 
No response

**Comment by 88250** [comment]
刚刚看了下，应该是已经有接口的了 openRepoSnapshotDoc

在快照对比界面随便点一个文档：

![image](https://github.com/siyuan-note/siyuan/assets/873584/8f044b73-d940-4831-a9cc-ef711139d956)

如果是资源文件的话返回是这样的：

![image](https://github.com/siyuan-note/siyuan/assets/873584/03ffca31-2c0e-44c3-816e-bb643b1ad230)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by zxhd863943427** [comment]
额，我的意思就是说，希望能传入 openRepoSnapshotDoc 同样的参数，但返回原始的、没有解析过的数据，类似于getFile api的返回，而不是解析后的dom和一行路径

**Comment by 88250** [comment]
明白了，下个版本添加一个内部内核 API `/api/repo/getRepoFile`，谢谢。
