### ISSUE TITLE
希望能支持直接存取md file

### ISSUE THREAD

**Issue by loochao** [siyuan-note/siyuan#10107]
### In what scenarios do you need this feature?

logseq和obsidian可以共用一个文件夹 因为它们的存取格式默认是markdown file
也可以用emacs vim typora直接edit 或者grep查找
siyuan是json file 虽然是纯文本 但不太容易和别的软件共用 需要再解析一步

### Describe the optimal solution

能不能加一个全局选项 可以设置文件的默认存储格式

**Comment by 88250** [comment]
你好，思源不是基于 markdown 文件存储的，所以无法直接读写 markdown 文件，感谢建议。

**Comment by 88250** [comment]
补充一下我们使用 JSON 作为存储的考虑 https://ld246.com/article/1626313293676
