### ISSUE TITLE
缩放图片后不居中问题

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1010]
### 描述问题 Describe the problem

![s1](https://user-images.githubusercontent.com/69628966/104153221-bfe1dd00-541c-11eb-8b37-d3ac423f8fd1.gif)

### 版本环境 Version environment

* 版本 Version：0.5.9
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by yeshaopeng6688** [comment]
D大，能否显示完整的图片缩放语法，这样能够自定义缩放比例。虽然提供了常用的缩放比例，但是实操中如果不是这些常用比例，使用那种滑来滑去的太麻烦了
![image](https://user-images.githubusercontent.com/69628966/104279813-e3248f00-54e5-11eb-9310-3e5e7b415b56.png)

**Comment by 88250** [comment]
等专家模式 #868
