### ISSUE TITLE
How to use database ?

### ISSUE THREAD

**Issue by amatya-aditya** [siyuan-note/siyuan#10106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I installed SiYuan thinking that it has database feature like notion ? Does it have it ? How can I use it ?

### Expected result

Couldn't find the way to use it.

### Version environment

```markdown
I have installed latest version of siyuan and using it on windows 11.
```

### Log file

![image](https://github.com/siyuan-note/siyuan/assets/63241408/1e3d4720-212e-4d44-b98c-8102f9ab1150)
![image](https://github.com/siyuan-note/siyuan/assets/63241408/dda44cce-72da-4e75-b53e-4c7f10694e46)

**Comment by 88250** [comment]
Hello, SiYuan Database is currently in the paid testing phase, and you need to pay PRO Features or subscribe to experience it first. https://b3log.org/siyuan/en/pricing.html

This feature is very similar to the Notion Database, except that currently there is only a table view, thank you.

**Comment by amatya-aditya** [comment]
Will it be available for as free features ? If yes, Is there any tentative date of release ?

**Comment by 88250** [comment]
We will officially launch the database feature when we release v3.0.0, which will be available to all users around the 20th of next month, so stay tuned.
