### ISSUE TITLE
数据库多选可以多次选择属性

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10105]
### In what scenarios do you need this feature?

有时候需要批量指定多个属性，目前是选择一次属性就取消全选了

### Describe the optimal solution

保持选中

### Describe the candidate solution

无

**Comment by AvoidantPerDis** [comment]
批量指定属性

**Comment by 88250** [comment]
没太理解你的意思，麻烦再补充一下。

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/1aef013c-c956-4de8-bafd-09867c189b6b)
如图，我希望不用反复选择，一次批量指定多个属性

**Comment by 88250** [comment]
哦哦，明白了，请关注 https://github.com/siyuan-note/siyuan/issues/9867

**Comment by AvoidantPerDis** [comment]
好的 😄
