### ISSUE TITLE
data history: rollback subdocuments

### ISSUE THREAD

**Issue by sublimeclemency** [siyuan-note/siyuan#10114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

pressing the rollback button for `01` folder doesn't recover its subdocuments

### Expected result

if it's intended that folder rollback does not rollback subdocuments,
please provide the option to rollback all changes in a snapshot
(in case many documents were accidentally deleted, which requires them to be recovered one by one)

### Screenshot or screen recording presentation

![screenshot](https://github.com/siyuan-note/siyuan/assets/124845026/7dca1bd2-30c3-4094-b1d4-7203582cb23b)

### Version environment

```markdown
2.12.0
```

### Log file

ㅤ

**Comment by 88250** [comment]
Sorry, batch rollback cannot be supported, only single document rollback is supported.
