### ISSUE TITLE
数据库汇总关联列已完成占比在取消关联列选中后必然内核错误

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

稳定复现，在汇总关联列已完成占比时一开始没问题，修改后直接报错

### Expected result

正常使用

### Screenshot or screen recording presentation

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/c0bb8188-c136-4303-8b6f-b86ad5898d22)

### Version environment

```markdown
- Version: 2.12.1
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13868026/system-log.zip)

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/206b3885-dac1-4fa4-a009-86f77c88cb4c)
简单测试又好像无法复现

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/154863885/5d622719-4410-45a1-be15-9d2665220e9f)
这个bug还会导致数据库始终处于加载状态，只能回滚解决

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/22348e88-5704-4487-b18c-a8e2b1020bb5)
找到bug了，取消关联列的选中就能复现

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/154863885/b4d1704f-5a3d-4452-b13d-91f2f257267c)

**Comment by AvoidantPerDis** [comment]
[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/13868091/system-log.1.zip)

**Comment by 88250** [comment]
感谢反馈，下个版本修复。
