### ISSUE TITLE
The database is dragged into the super block and the block icon Bug is triggered.

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

超级块为几个正常的块进行水平分栏，然后把数据库块拖进去，块菜单图标出现问题：

![image](https://github.com/siyuan-note/siyuan/assets/54077803/899cf4c2-3717-4738-9d60-e618194db464)

### Expected result

修复即可

### Version environment

```markdown
- Version: 2.12.1
- Operating System: win10
- Browser (if used):
```

### Log file

no

**Comment by 88250** [comment]
你好，我从截图上没看出问题，麻烦标注补充一下，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by LGRemdo** [comment]
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

![image](https://github.com/siyuan-note/siyuan/assets/54077803/e6861cdc-be1e-429c-a53b-b20edf02a361)

**Comment by 88250** [comment]
这个是正常的，块标出现在块的右上角。
