### ISSUE TITLE
Improve relation column cell value interfaction

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10118]
### In what scenarios do you need this feature?

如图

![image](https://github.com/siyuan-note/siyuan/assets/54077803/23239089-6da5-4216-8057-5db2f94e885c)

### Describe the optimal solution

如图，更多的，还可以支持 alt shift 快捷键 + click

**Comment by 88250** [comment]
改进：对于已经绑定块的主键可以悬浮预览，对于没有绑定的主键还是仅支持显示文本。
