### ISSUE TITLE
使用chrome插件收藏CSDN文章时docker

### ISSUE THREAD

**Issue by C50714003** [siyuan-note/siyuan#10117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### 使用chrome插件收藏CSDN文章时报错
收藏的文章：[https://blog.csdn.net/qq_28785507/article/details/129268442](url)
报错日志如下：
`2024/01/09 10:16:45 http: panic serving 172.17.0.1:51640: runtime error: invalid memory address or nil pointer dereference
goroutine 1273 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ecf2e0?, 0x36fad80?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/api.extensionCopy(0xc001a04400)
        /go/src/github.com/siyuan-note/siyuan/kernel/api/extension.go:46 +0xea
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.CheckAuth(0xc001a04400)
2024/01/09 10:17:14 http: panic serving 172.17.0.1:51734: runtime error: invalid memory address or nil pointer dereference
goroutine 1385 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ecf2e0?, 0x36fad80?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/api.extensionCopy(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/api/extension.go:46 +0xea
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.CheckAuth(0xc002a9f500)
github.com/siyuan-note/siyuan/kernel/server.Serve.Sessions.func4(0xc002a9f500)
        /go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 +0x17d
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-contrib/gzip.(*gzipHandler).Handle(0xc0013d2030, 0xc002a9f500)
        /go/pkg/mod/github.com/gin-contrib/gzip@v0.0.6/handler.go:60 +0x2e6
github.com/gin-gonic/gin.(*Context).Next(0xc002a9f500)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/siyuan-note/siyuan/kernel/server.Serve.corsMiddleware.func2(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/server/serve.go:558 +0x11f
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.Recover(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:320 +0x62
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:293 +0x2c3
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.ControlConcurrency(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:344 +0x1a2
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0013d0000, 0xc002a9f500)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0013d0000, {0x279f348?, 0xc0043230a0}, 0xc0026b3f00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0x2799570?}, {0x279f348?, 0xc0043230a0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0026cd950, {0x27a54b8, 0xc0013d2780})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
2024/01/09 10:22:45 http: panic serving 172.17.0.1:51896: runtime error: invalid memory address or nil pointer dereference
goroutine 1728 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ecf2e0?, 0x36fad80?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/api.extensionCopy(0xc0026b2e00)
        /go/src/github.com/siyuan-note/siyuan/kernel/api/extension.go:46 +0xea
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174`

### Expected result

正常收藏网页

### Version environment

```markdown
- Version: 2.12.1
- Operating System: docker arch [amd64]
- Browser (if used): chrome 版本 120.0.6099.199（正式版本） （64 位）
```

### Log file

` 2024/01/09 10:09:04 working.go:146:
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/01/09 10:09:04 runtime.go:74: kernel is booting:
    * ver [2.12.1]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/01/09 10:09:04 conf.go:276: upgraded from version [2.11.4] to [2.12.1]
I 2024/01/09 10:09:04 runtime.go:123: use network proxy [system]
I 2024/01/09 10:09:04 serve.go:115: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/01/09 10:09:04 blocktree.go:495: read block tree [3.3 MB] to [/siyuan/workspace/temp/blocktree], elapsed [0.17s]
I 2024/01/09 10:09:04 conf.go:770: database size [34 MB], tree/block count [205/11501]
I 2024/01/09 10:09:04 working.go:192: kernel booted
I 2024/01/09 10:09:04 conf.go:978: upgrading user guide box [20210808180117-6v0mkxr]
I 2024/01/09 10:09:05 box.go:76: auto stat [trees=205, blocks=11501, dataSize=997 MB, assetsSize=987 MB]
I 2024/01/09 10:09:06 index.go:197: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.01s], tree [count=61, size=1.1 MB]
I 2024/01/09 10:09:06 conf.go:990: upgraded user guide box [20210808180117-6v0mkxr]
I 2024/01/09 10:09:06 conf.go:978: upgrading user guide box [20210808180117-czj9bvb]
I 2024/01/09 10:09:08 index.go:197: rebuilt database for notebook [20210808180117-czj9bvb] in [0.02s], tree [count=64, size=1.2 MB]
I 2024/01/09 10:09:08 conf.go:990: upgraded user guide box [20210808180117-czj9bvb]
W 2024/01/09 10:09:48 blocktree.go:552: save block tree [size=3.2 MB] to [/siyuan/workspace/temp/blocktree], elapsed [43.77s]
W 2024/01/09 10:10:58 blocktree.go:552: save block tree [size=367 kB] to [/siyuan/workspace/temp/blocktree], elapsed [3.74s]
2024/01/09 10:12:09 http: panic serving 172.17.0.1:51190: runtime error: invalid memory address or nil pointer dereference
goroutine 606 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ecf2e0?, 0x36fad80?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/api.extensionCopy(0xc001b21b00)
        /go/src/github.com/siyuan-note/siyuan/kernel/api/extension.go:46 +0xea
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.CheckAuth(0xc001b21b00)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:221 +0x10f5
github.com/gin-gonic/gin.(*Context).Next(0xc001b21b00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/siyuan-note/siyuan/kernel/server.Serve.Sessions.func4(0xc001b21b00)
        /go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 +0x17d
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-contrib/gzip.(*gzipHandler).Handle(0xc0013d2030, 0xc001b21b00)
        /go/pkg/mod/github.com/gin-contrib/gzip@v0.0.6/handler.go:60 +0x2e6
github.com/gin-gonic/gin.(*Context).Next(0xc001b21b00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/siyuan-note/siyuan/kernel/server.Serve.corsMiddleware.func2(0xc001b21b00)
        /go/src/github.com/siyuan-note/siyuan/kernel/server/serve.go:558 +0x11f
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.Recover(0xc001b21b00)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:320 +0x62
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.Timing(0xc001b21b00)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:293 +0x2c3
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.ControlConcurrency(0xc001b21b00)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:344 +0x1a2
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0013d0000, 0xc001b21b00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0013d0000, {0x279f348?, 0xc0004ddea0}, 0xc002963600)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0x2799570?}, {0x279f348?, 0xc0004ddea0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc002bf8480, {0x27a54b8, 0xc0013d2780})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 26
        /usr/local/go/src/net/http/server.go:3086 +0x5cb
I 2024/01/09 10:12:40 index.go:197: rebuilt database for notebook [20240109101240-28kduhf] in [0.00s], tree [count=0, size=0 B]
I 2024/01/09 10:12:40 index.go:269: resolved refs [64] in [33ms]
W 2024/01/09 10:13:01 blocktree.go:552: save block tree [size=395 kB] to [/siyuan/workspace/temp/blocktree], elapsed [7.27s]
W 2024/01/09 10:15:59 blocktree.go:552: save block tree [size=374 kB] to [/siyuan/workspace/temp/blocktree], elapsed [3.82s]
W 2024/01/09 10:16:31 blocktree.go:552: save block tree [size=611 kB] to [/siyuan/workspace/temp/blocktree], elapsed [6.50s]
2024/01/09 10:16:45 http: panic serving 172.17.0.1:51640: runtime error: invalid memory address or nil pointer dereference
goroutine 1273 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ecf2e0?, 0x36fad80?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/api.extensionCopy(0xc001a04400)
        /go/src/github.com/siyuan-note/siyuan/kernel/api/extension.go:46 +0xea
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.CheckAuth(0xc001a04400)
2024/01/09 10:17:14 http: panic serving 172.17.0.1:51734: runtime error: invalid memory address or nil pointer dereference
goroutine 1385 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ecf2e0?, 0x36fad80?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/api.extensionCopy(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/api/extension.go:46 +0xea
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.CheckAuth(0xc002a9f500)
github.com/siyuan-note/siyuan/kernel/server.Serve.Sessions.func4(0xc002a9f500)
        /go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 +0x17d
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-contrib/gzip.(*gzipHandler).Handle(0xc0013d2030, 0xc002a9f500)
        /go/pkg/mod/github.com/gin-contrib/gzip@v0.0.6/handler.go:60 +0x2e6
github.com/gin-gonic/gin.(*Context).Next(0xc002a9f500)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
github.com/siyuan-note/siyuan/kernel/server.Serve.corsMiddleware.func2(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/server/serve.go:558 +0x11f
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.Recover(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:320 +0x62
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:293 +0x2c3
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/siyuan-note/siyuan/kernel/model.ControlConcurrency(0xc002a9f500)
        /go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:344 +0x1a2
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0013d0000, 0xc002a9f500)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0013d0000, {0x279f348?, 0xc0043230a0}, 0xc0026b3f00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0x2799570?}, {0x279f348?, 0xc0043230a0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0026cd950, {0x27a54b8, 0xc0013d2780})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
2024/01/09 10:22:45 http: panic serving 172.17.0.1:51896: runtime error: invalid memory address or nil pointer dereference
goroutine 1728 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1ecf2e0?, 0x36fad80?})
        /usr/local/go/src/runtime/panic.go:920 +0x270
github.com/siyuan-note/siyuan/kernel/api.extensionCopy(0xc0026b2e00)
        /go/src/github.com/siyuan-note/siyuan/kernel/api/extension.go:46 +0xea
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174`

**Comment by 88250** [comment]
我这里在桌面端上测试没有发现问题。

从报错日志上看可能是因为剪藏扩展版本低或者和其他扩展冲突了，导致参数不全。建议如下：

* 确保 Chrome 剪藏扩展和 Docker 镜像都是最新版
* 排除其他 Chrome 扩展影响

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by C50714003** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/20850707/c7ca28f2-9018-455e-8e02-bb1f2e55a466)
![image](https://github.com/siyuan-note/siyuan/assets/20850707/8365de21-63d9-4c5c-8def-719ee9f4ef38)
- 插件和镜像都是最新的，仍然有该问题
- 停用浏览器其它插件，问题依然存在
- 使用edge上的也出现该问题
