### ISSUE TITLE
Realize the experience enhancement of the database from many angles, such as differentiation, filtering conditions, etc.

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10116]
### In what scenarios do you need this feature?

许久没有使用了，体验了一下，发现增强了不少。
但就目前的体验而言，我觉得应该从4个角度继续改进。

1. **汇总列的数值类型显示**：有关于关联链的汇总这一列，在计算特定的内容的时候，应该确保输出格式为整型，而不是浮点型。比如“个数/行数”之类的。
2. **关联列内容的区分度**：关联列中，关联的行之间无法有效的区分。目前是通过空格的方式计算，我觉得可以修改样式，来增强区分度。实际上，这是必要的。比如见2的说明图a，对于空的主键，关联似乎就是“消失”了一样。改进的方向可以参考飞书。
3. **针对单选多选的筛选条件提升**：在飞书当中，它的筛选其实做得非常好，主要是有包含和不包含。并且包含和不包含是可以有多个选项同时存在的！！！而不是只能选择一条。
![image](https://github.com/siyuan-note/siyuan/assets/54077803/10c5b442-0344-4f0c-b5dd-b20301e4894d)
4. 关联类类型的区分度：目前关联分为两种，一个是单向，一个是双向，但是这两种模式之间没有区分度。

———————说明图———————
1说明图
![image](https://github.com/siyuan-note/siyuan/assets/54077803/c9f9c7a0-c6c8-4911-a598-7ed174173b4b)

2说明图
![image](https://github.com/siyuan-note/siyuan/assets/54077803/bdfe0f73-f914-46b5-8e7e-85ebbf7181e8)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/0218fa16-9b27-46d4-b758-a7da76bbae71)

3说明图
![image](https://github.com/siyuan-note/siyuan/assets/54077803/6254ec27-580a-4b16-b48d-010f8ff517b2)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/ad1a9d3f-7989-413a-a141-f8fb5ccd010b)

4说明图
![image](https://github.com/siyuan-note/siyuan/assets/54077803/9bd2e947-7af2-4acb-a272-38796921bcfb)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/2f899746-b659-4a7b-9116-84d418828304)

### Describe the optimal solution

都可以参考飞书，目前来说体验还是做得非常不错的。

**Comment by mozhux** [comment]
飞书做的确实好，但飞书这种是多维表格，和文档属性相关的还是不完全一样。

**Comment by 88250** [comment]
1. 汇总列的数值类型显示
2. 关联列内容的区分度

这两个最新版应该已经改进过了，有空的话请帮忙测试最新版。

3. 针对单选多选的筛选条件提升

后面考虑通过条件组合实现。

4. 关联类类型的区分度

暂时不考虑区分了。


感谢反馈。
