### ISSUE TITLE
ubuntu桌面端上无法导出markdown或sy.zip

### ISSUE THREAD

**Issue by f2w00** [siyuan-note/siyuan#10110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

系统信息:

ubuntu23.10,plasma5.27

思源版本:v2.12.0,appimage和tar版本同样

点击导出markdown或者导出sy.zip没有反应,导出图片和pdf都没问题

但是使用浏览器localhost:6806打开思源笔记之后可以正常导出

### Expected result

正常导出markdown/sy.zip

### Version environment

```markdown
- Version: 2.12.0
- Operating System: ubuntu 23.10
- Browser (if used):
```

### Log file

查看日志点击前后没变化

**Comment by 88250** [comment]
这个多半是默认浏览器设置的问题，请检查一下，我关闭 issue 了，谢谢。
