### ISSUE TITLE
复习完正常闪卡可以继续复习当天需再次复习的卡片，而无需要再次点击间隔重复按钮

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10123]
### In what scenarios do you need this feature?

更新的模式有点可怕，每次复习当中必然有需要再次复习的卡片，当集中复习这些卡片的时候，又需要点击一次间隔重复按钮。

完全可以在当次复习完之后弹出对话框询问是否需要继续复习，之后通过enter或者space确认来接着复习。这样能达到一个流畅的流程。

现在太繁琐了

### Describe the optimal solution

更新的模式有点可怕，每次复习当中必然有需要再次复习的卡片，当集中复习这些卡片的时候，又需要点击一次间隔重复按钮。

完全可以在当次复习完之后弹出对话框询问是否需要继续复习，之后通过enter或者space确认来接着复习。这样能达到一个流畅的流程。

现在太繁琐了

**Comment by 88250** [comment]
请参考 https://github.com/siyuan-note/siyuan/issues/10087

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/10130
