### ISSUE TITLE
闪卡红色计数只需要记录下次复习时间仍在当天的卡片

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10121]
### In what scenarios do you need this feature?

现在的闪卡中，红蓝绿计数中的红色计数指的是刷过一次的卡片，无论刷过的卡片下次复习是什么时候。

**刷过的卡如果当天不用再次复习，完全可以不用记入红色数字，红色计数只需要记录下次复习时间仍在当天的卡片就可以了。**这样就能知道自己当天复习过并且仍需再次复习的卡片数量

对于已复习并且当天不需再次复习的卡片完全没必要计数。

### Describe the optimal solution

希望修正

**Comment by 88250** [comment]
这个之前已经讨论过多次，思源只支持“轮次”复习，不支持按天复习。
