### ISSUE TITLE
能够暂停部分闪卡

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10124]
### In what scenarios do you need this feature?

例如某一个文档下的闪卡，暂时不需要复习，但是未来仍需复习，那么就可以使用暂停功能，将这部分闪卡暂停复习，等需要再次复习的时候可以点击恢复

### Describe the optimal solution

右键文档树，在闪卡选项中添加暂停

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/8832
