### ISSUE TITLE
空行开头使用 “【】” 变成了任务列表

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#10122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

空行开头使用 “【】” 变成了任务列表

![PixPin_2024-01-09_15-11-12](https://github.com/siyuan-note/siyuan/assets/72399630/efc7aa0b-5870-439c-ae14-f0417788a586)

### Expected result

这应该是个BUG吧……！希望使用 “【” 的时候不变成任务列表

### Version environment

```markdown
- Version: v2.12.0
- Operating System: Windows 23H2
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13870309/system-log.zip)

**Comment by shuojie819** [comment]
对了，打一个“【】” 会变成任务列表，而且光标会到上一行最后。

**Comment by 88250** [comment]
这是特性，但是光标移到上一行最后我这里无法重现，暂时先关闭了，感谢反馈。
