### ISSUE TITLE
思维导图浏览小窗口

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#1012]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
导图比较大时，使用预览窗口可以更高效地查看全局和定位

### 描述最优的解决方案 Describe the optimal solution
- 参考 [xmind](https://www.xmind.cn/) 的实现
![思维导图浏览小窗口](https://user-images.githubusercontent.com/15924513/104174452-7a83d680-5441-11eb-8989-93c20614c5be.gif)

- 参考[百度脑图](https://github.com/fex-team/kityminder)已有的实现：
![图片](https://user-images.githubusercontent.com/15924513/104183698-529a7000-544d-11eb-8243-9bbc96d800a8.png)

**Comment by 88250** [comment]
收到，后期考虑。

**Comment by 88250** [comment]
以后再考虑了，先关闭，谢谢。
