### ISSUE TITLE
支持Tiff图片预览

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10137]
### In what scenarios do you need this feature?

Tiff 是 tagged image file format 的缩写。在科研领域，该格式非常常用，用于无损保存实验图片。
目前思源是不支持预览Tiff图片的，如果支持显示Tiff图片，将有助于用思源整理实验数据

### Describe the optimal solution

希望思源将来能预览Tiff图片

**Comment by 88250** [comment]
浏览器没有默认支持的格式暂时不考虑了，谢谢。

**Comment by Achuan-2** [comment]
https://github.com/seikichi/tiff.js/?tab=readme-ov-file
这个可以参考下
