### ISSUE TITLE
闪卡只读状态与文档同步

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10139]
### In what scenarios do you need this feature?
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/0719b28b-94ed-4dcd-91e5-be3e21d54468)

目前闪卡界面始终可编辑，移动端闪卡键盘频繁弹出，影响体验

### Describe the optimal solution

只读状态与文档同步

**Comment by Vanessa219** [comment]
闪卡会包含子文档，但是用户不可能对每一个子文档都去设置。建议开启设置中的只读模式即可。

**Comment by 88250** [comment]
我关闭了，谢谢。
