### ISSUE TITLE
在数据库顶部时，无法方便滑动查看右侧的属性

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10132]
### In what scenarios do you need this feature?

这个滑动条只在底部存在，如果行过多，一个屏幕容不下，滑动条只在底部存在，如果当前在看顶部的行，想看右侧的属性时做不到，只能滑到最下面，然后右滑滑动条，再滑动到上面看顶部的行，很不方便

![image](https://github.com/siyuan-note/siyuan/assets/67137548/6fcb8e83-1d2e-43d6-9611-93621eb9069d)

### Describe the optimal solution

无

**Comment by 88250** [comment]
按住 Shift 后使用滚轮就是横向滚动了。
