### ISSUE TITLE
闪卡模式折叠标题状态不变

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10134]
### In what scenarios do you need this feature?

目前折叠的会展开

### Describe the optimal solution

保持默认

**Comment by 88250** [comment]
折叠状态目前都是统一的，无法做到根据场景不同分离折叠状态。

**Comment by AvoidantPerDis** [comment]
> 折叠状态目前都是统一的，无法做到根据场景不同分离折叠状态。

那就是bug了，我这边闪卡折叠的会展开

**Comment by AvoidantPerDis** [comment]
对了，还有只读也是，闪卡一直可修改，在移动端，浏览器，和win测试过了

**Comment by AvoidantPerDis** [comment]
标题是折叠的，内容却出来了
![Screenshot_2024-01-10-08-08-06-619_mark via-edit](https://github.com/siyuan-note/siyuan/assets/154863885/30e52b07-2a58-4146-a0ee-c21acf8b792b)

**Comment by 88250** [comment]
麻烦用默认主题测试。
