### ISSUE TITLE
文档树、大纲、收集箱 在钉住后不单独记录宽度

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10135]
### In what scenarios do you need this feature?

钉住后宽度一致 不然每次点击文档树、大纲、收集箱  编辑器宽度都变了 原本的浏览进度就被打乱，需要找到之前的浏览位置后才能继续浏览

### Describe the optimal solution

钉住后宽度一致

**Comment by 88250** [comment]
这个是特性，每个面板都可以有不同的宽度。

**Comment by Temacc0531** [comment]
关联 #5350
