### ISSUE TITLE
反链里的容器块处理逻辑

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#1013]
内部内容块已经被链接过的容器块在「提及」里应该排除出去，release note 里最后一次提到这个问题是 057，但是看了一下这个问题 059 还是存在的。

![image](https://user-images.githubusercontent.com/32661922/104177666-19113700-5444-11eb-8089-74981288f18f.png)

除了列表块之外，超级块之类的容器块也是同样的问题，容器块的作用在这个地方没法得到体现，因为提及里把容器块再显示一遍确实也没提供什么更多的信息。

我导入的很多笔记被链接的次数比较多，比如六七次，然后「提及」里面一整屏的列表块结果，基本上就是把上方链接里的内容复制了一遍。

列表块的问题困扰了我很长时间，我感觉现在终于把这个处理逻辑梳理清楚了：无论一个内容块有没有被真正链接过，在「链接」或「提及」里都应该显示容器块（列表块和超级块），因为偶尔内容块特别短的时候也许能显示出更多的上下文；但是这个容器块要么出现在链接里，要么出现在提及里，不能两头都显示。

**Comment by 88250** [comment]
感谢反馈，我们稍后再调整看看，谢谢。

**Comment by deerainw** [comment]
谢谢，我 P 了一张典型情况下的完成效果图，供参考 😂

<img width="787" alt="反链展示效果" src="https://user-images.githubusercontent.com/32661922/104191535-9777d400-5458-11eb-8efa-85e0c5ffcb34.png">

**Comment by deerainw** [comment]
补一张删掉上面内容块的：

<img width="783" alt="无内容块" src="https://user-images.githubusercontent.com/32661922/104192360-ae6af600-5459-11eb-83ea-b261c688777a.png">

**Comment by 88250** [comment]
你好，v0.6.5 通过子块排除父块的逻辑做了简化，即提及中如果出现子块则排除掉所有父块：

![image](https://user-images.githubusercontent.com/873584/105053407-d4bd1100-5aab-11eb-8f40-3f04817fd2e2.png)

不过现在的实现上还是有问题，即未连接的父块会被排除（下图方块部分），我这里逻辑上还是有点矛盾。

![image](https://user-images.githubusercontent.com/873584/105054870-6ed18900-5aad-11eb-93a5-34584a902621.png)

先这样，等过几个版本我们在反链上下文层级 #295 中继续处理了，谢谢。
