### ISSUE TITLE
Attribute Panel - Database supports adding key and sorting key

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10142]

**Comment by mozhux** [comment]
刚试用了，想哭了，交互好别扭，市面上面板添加列都很成熟了，可以直接用的。
点击添加就弹窗字段标题和对应的字段类型很好的交互了，比notion的还好。notion还要两步。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/e47e1c6c-ebe5-4b62-b36c-f24eb9e14448)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/b08f8b5b-a588-48eb-a159-206eab955a9e)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/ad96491b-a92b-42d0-aeef-b1543b617406)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/cbbe827e-dc06-457a-9bfa-1481c30ac135)
