### ISSUE TITLE
新学闪卡数量与实际设置不一致

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

例如设置了新学50张卡片，学完之后又会自动添加50个

### Expected result

能够依据实际设置来

### Version environment

```markdown
- Version: 2.12.2
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13896711/system-log.zip)

**Comment by 88250** [comment]
上限设置是每次间隔重复的上限，不是按天的，这个解释过很多次了哦。
