### ISSUE TITLE
复习完闪卡后提示是否学习新卡

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10148]
### In what scenarios do you need this feature?

复习完当天的旧卡以及学习完规定的新卡数量之后可以快捷的学习更多的新卡，并且不会更改闪卡中新卡学习数量设置。
例如我还有400张卡片没有学习完成，每天设置的学习新卡数量为50，那么当学习完这50张新卡后，还想继续学习剩下的350张新卡中的一部分，那么就可以在闪卡复习完毕的窗口中点击学习更多新卡，设置好当次想学习的更多新卡数量后，可以立即开始学习。

而不用跑到 设置-闪卡 里重新设置

### Describe the optimal solution

在复习结束窗口提供增加当次新卡学习数量按钮

**Comment by 88250** [comment]
这个暂时不考虑改变了，请在设置中修改，谢谢。
