### ISSUE TITLE
没有加密文本吗？

### ISSUE THREAD

**Issue by JF950908** [siyuan-note/siyuan#10156]
### In what scenarios do you need this feature?

希望可以支持文本加密

### Describe the optimal solution

希望可以支持文本加密，加密后的文本直接显示****，解密显示原文本

**Comment by pakeh2866** [comment]
这个好像讨论过

**Comment by JF950908** [comment]
> 这个好像讨论过

这个可以有

**Comment by 88250** [comment]
目前不考虑了，感谢提议。
