### ISSUE TITLE
有时pushMsg无法显示出消息框

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

/api/notification/pushMsg 经常出现下面的情况，只有一个对钩，没有内容框。

![image](https://github.com/siyuan-note/siyuan/assets/3294007/a222d531-d4a6-4ee9-bbc8-4036f437cdaa)

### Expected result

有内容

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

None

**Comment by 88250** [comment]
感觉是 msg 参数为空了吧……不太确定，下个版本我们加个校验为空看看，先排除这个可能性。

Issue 我暂时关闭了，后续如果还有问题请继续跟帖反馈，多谢。

**Comment by IAliceBobI** [comment]
@88250 我刚才看到了具体过程，就是弹出瞬间，已经看到有个框了，隐约看到文字，但完全弹出后框没了。

另外还有一个框时间到缩回去。

是否有这样的bug，在一个框弹出瞬间，可能会被其他框缩回去框影响。

**Comment by Vanessa219** [comment]
id 相同的话会的。

**Comment by IAliceBobI** [comment]
@Vanessa219 id  是 requestID? 我在哪里设置？

**Comment by 88250** [comment]
pushMsg 接口会返回生成的消息 id，是个 7 个字符的随机字符串。

**Comment by IAliceBobI** [comment]
> pushMsg 接口会返回生成的消息 id，是个 7 个字符的随机字符串。

按道理概率不高，但实际上，这个概率够高的，经常出现，不然我也不提issue了。

或者还有其他隐藏问题导致。

**Comment by 88250** [comment]
那估计还得找找重现步骤，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月13日(周六) 中午1:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 有时pushMsg无法显示出消息框 (Issue #10153)




  
pushMsg 接口会返回生成的消息 id，是个 7 个字符的随机字符串。
  
按道理概率不高，但实际上，这个概率够高的，经常出现，不然我也不提issue了。
 
或者还有其他隐藏问题导致。
