### ISSUE TITLE
mac  m1 bug

### ISSUE THREAD

**Issue by zyxcambridge** [siyuan-note/siyuan#10151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.14.0 → 8.14.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.14.1   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Done in 4.5s
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm setup
Appended new lines to /Users/zhangyixin/.zshrc

Next configuration changes were made:
export PNPM_HOME="/Users/zhangyixin/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

To start using pnpm, run:
source /Users/zhangyixin/.zshrc
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done
Done in 2.2s
(base) zhangyixin@zhangyixin siyuan % pnpm run dev
 ERR_PNPM_NO_SCRIPT  Missing script: dev

Command "dev" not found.
(base) zhangyixin@zhangyixin siyuan % cd app 
(base) zhangyixin@zhangyixin app % pnpm run dev

> SiYuan@2.12.1 dev /Users/zhangyixin/Desktop/siyuan/app
> webpack --mode development

command not found: webpack
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % pnpm run start

> SiYuan@2.12.1 start /Users/zhangyixin/Desktop/siyuan/app
> NODE_ENV=development electron ./electron/main.js

command not found: electron
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % code ..  
(base) zhangyixin@zhangyixin app % 

### Expected result

(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.14.0 → 8.14.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.14.1   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Done in 4.5s
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm setup
Appended new lines to /Users/zhangyixin/.zshrc

Next configuration changes were made:
export PNPM_HOME="/Users/zhangyixin/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

To start using pnpm, run:
source /Users/zhangyixin/.zshrc
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done
Done in 2.2s
(base) zhangyixin@zhangyixin siyuan % pnpm run dev
 ERR_PNPM_NO_SCRIPT  Missing script: dev

Command "dev" not found.
(base) zhangyixin@zhangyixin siyuan % cd app 
(base) zhangyixin@zhangyixin app % pnpm run dev

> SiYuan@2.12.1 dev /Users/zhangyixin/Desktop/siyuan/app
> webpack --mode development

command not found: webpack
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % pnpm run start

> SiYuan@2.12.1 start /Users/zhangyixin/Desktop/siyuan/app
> NODE_ENV=development electron ./electron/main.js

command not found: electron
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % code ..  
(base) zhangyixin@zhangyixin app % 

### Screenshot or screen recording presentation

(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.14.0 → 8.14.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.14.1   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Done in 4.5s
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm setup
Appended new lines to /Users/zhangyixin/.zshrc

Next configuration changes were made:
export PNPM_HOME="/Users/zhangyixin/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

To start using pnpm, run:
source /Users/zhangyixin/.zshrc
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done
Done in 2.2s
(base) zhangyixin@zhangyixin siyuan % pnpm run dev
 ERR_PNPM_NO_SCRIPT  Missing script: dev

Command "dev" not found.
(base) zhangyixin@zhangyixin siyuan % cd app 
(base) zhangyixin@zhangyixin app % pnpm run dev

> SiYuan@2.12.1 dev /Users/zhangyixin/Desktop/siyuan/app
> webpack --mode development

command not found: webpack
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % pnpm run start

> SiYuan@2.12.1 start /Users/zhangyixin/Desktop/siyuan/app
> NODE_ENV=development electron ./electron/main.js

command not found: electron
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % code ..  
(base) zhangyixin@zhangyixin app % 

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.14.0 → 8.14.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.14.1   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Done in 4.5s
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm setup
Appended new lines to /Users/zhangyixin/.zshrc

Next configuration changes were made:
export PNPM_HOME="/Users/zhangyixin/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

To start using pnpm, run:
source /Users/zhangyixin/.zshrc
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done
Done in 2.2s
(base) zhangyixin@zhangyixin siyuan % pnpm run dev
 ERR_PNPM_NO_SCRIPT  Missing script: dev

Command "dev" not found.
(base) zhangyixin@zhangyixin siyuan % cd app 
(base) zhangyixin@zhangyixin app % pnpm run dev

> SiYuan@2.12.1 dev /Users/zhangyixin/Desktop/siyuan/app
> webpack --mode development

command not found: webpack
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % pnpm run start

> SiYuan@2.12.1 start /Users/zhangyixin/Desktop/siyuan/app
> NODE_ENV=development electron ./electron/main.js

command not found: electron
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % code ..  
(base) zhangyixin@zhangyixin app % 

### More information

(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 8.14.0 → 8.14.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.14.1   │
   │                Run "pnpm add -g pnpm" to update.                 │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Done in 4.5s
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm setup
Appended new lines to /Users/zhangyixin/.zshrc

Next configuration changes were made:
export PNPM_HOME="/Users/zhangyixin/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

To start using pnpm, run:
source /Users/zhangyixin/.zshrc
(base) zhangyixin@zhangyixin siyuan % pnpm add -g pnpm
Nothing to stop. No server is running for the store at /Users/zhangyixin/Library/pnpm/store/v3
 ERR_PNPM_NO_GLOBAL_BIN_DIR  Unable to find the global bin directory

Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
(base) zhangyixin@zhangyixin siyuan % pnpm install electron@27.2.0 -D
Already up to date
Progress: resolved 75, reused 75, downloaded 0, added 0, done
Done in 2.2s
(base) zhangyixin@zhangyixin siyuan % pnpm run dev
 ERR_PNPM_NO_SCRIPT  Missing script: dev

Command "dev" not found.
(base) zhangyixin@zhangyixin siyuan % cd app 
(base) zhangyixin@zhangyixin app % pnpm run dev

> SiYuan@2.12.1 dev /Users/zhangyixin/Desktop/siyuan/app
> webpack --mode development

command not found: webpack
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % pnpm run start

> SiYuan@2.12.1 start /Users/zhangyixin/Desktop/siyuan/app
> NODE_ENV=development electron ./electron/main.js

command not found: electron
 ELIFECYCLE  Command failed with exit code 127.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
(base) zhangyixin@zhangyixin app % code ..  
(base) zhangyixin@zhangyixin app %

**Comment by 88250** [comment]
Please refer to https://github.com/siyuan-note/siyuan/blob/master/.github/CONTRIBUTING.md
