### ISSUE TITLE
Distinguish the type of task list block and normal list block

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#1015]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
目前我使用动态查询功能在当天的日记中将所有的笔记中和任务有关的内容查询显示在当天的日记笔记中。
希望可以区分任务列表和普通列表，以及列表当前的状态
目前我的作法是采用标签的方式

### 描述最优的解决方案 Describe the optimal solution
动态查询内容类型区分任务列表与其他列表
查询任务列表是否完成条件的查询支持
如果被引用的内容如果可以设置显示被引用的块所在文档标题，目前为鼠标移动上去显示，那么ToDo功能就相当完美了，可以配合日记+模板完美实现

**Comment by 88250** [comment]
的确，这个问题我们也考虑一段时间了，似乎是有必要把任务列表块独立类型，我们后面再考虑一下，应该会改的这部分。

目前可以通过查询 `markdown` 字段（不使用 `content` 字段），`markdown` 是原始内容，然后 `LIKE %[ ]% OR LIKE '%[x]%'` 来实现捞待办。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/1481
