### ISSUE TITLE
集市-已下载 添加 “所有” 类别

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10158]
### In what scenarios do you need this feature?

希望可以添加一个“所有”类别，一下子将所有下载的东西进行展示，下载后还需要切换到挂件或者主题，进行操作，不太方便
![image](https://github.com/siyuan-note/siyuan/assets/16383685/68b65d98-aaa8-4969-b49e-4f2071366472)

### Describe the optimal solution

添加“所有”类别，展示所有下载的东西

**Comment by 88250** [comment]
暂时不考虑改动了，谢谢。
