### ISSUE TITLE
支持引用数据库的主键

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#10150]
### In what scenarios do you need this feature?

数据库的主键那一行，也视为一种块，可以进行双向引用

应用案例：
比如有个数据库存放了各种软件名，可以在别的地方直接引用软件名，而不需要把数据库的主键转换为新文档再引用

### Describe the optimal solution

数据库增加一个选项，支持默认创建主键的新文档？感觉不如上面的方案好

**Comment by mozhux** [comment]
有关联列

**Comment by 88250** [comment]
是的，这个场景请使用关联列和汇总列。

**Comment by HowcanoeWang** [comment]
关联列好像是在数据库里引用另一个数据库？

在普通文本里面进行引用数据库的主键有什么可以实现吗

**Comment by 88250** [comment]
> 关联列好像是在数据库里引用另一个数据库？

是的，引用另一个库，然后用汇总列可以渲染列值。

> 在普通文本里面进行引用数据库的主键有什么可以实现吗

普通文本列实现不了，要用汇总列。

**Comment by HowcanoeWang** [comment]
是普通页面的文本块中引用，不是在数据库中的文本列中引用

**Comment by 88250** [comment]
哦哦，那没有办法了，引用元素只能作用到块级，作用不到数据库块中的行。

**Comment by HowcanoeWang** [comment]
所以后续能不能支持引用到数据库中的行，感觉会更方便一点

**Comment by 88250** [comment]
估计是不行，数据库行不是块哦。要做的话得单独设计，我估计优先级不会高，后续看需求吧。

**Comment by 88250** [comment]
对了，如果现在要用可以通过行绑定块，然后引用块。

**Comment by HowcanoeWang** [comment]
> 主键转换为新文档再引用

是的，现在就是主键转换为新文档再引用，但感觉一个键单开一个空白文档不就回到notion那个设计上了

**Comment by 88250** [comment]
不一定非要用文档块，其他块也行的。

**Comment by mozhux** [comment]
其实我还是觉得照飞书弄比照notion弄好点。。notion都是按文档结构设计的，飞书这些不限制是否是文档。

**Comment by HowcanoeWang** [comment]
> 其实我还是觉得照飞书弄比照notion弄好点。。notion都是按文档结构设计的，飞书这些不限制是否是文档。

同意，notion每个主键都是一个新文档感觉就是块粒度不够细的妥协产物
