### ISSUE TITLE
数学公式不支持$

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

$$\int_{a}^{b}f(x)dx=\mu(b-a) 变成公式后应该是这样
![74fb9394f115ce9fba82d47e64257c79](https://github.com/siyuan-note/siyuan/assets/62794181/070b6bab-7172-450a-ab42-739444ebed1f)
思源显示的是这样
![image](https://github.com/siyuan-note/siyuan/assets/62794181/31170084-f103-49e7-8b98-7990e92fbca0)
去掉$$后变成的公式是这样
![0d905492b7799a11c5ee732cab9f0651](https://github.com/siyuan-note/siyuan/assets/62794181/2b78346c-eedc-4873-a698-beaa76ce62cb)

### Expected result
好像不是思源的问题 麻烦关闭issue

### Version environment

```markdown
- Version: 2.12.2
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
> 好像不是思源的问题 麻烦关闭issue

老铁，你自己也可以关闭的，谢谢。

**Comment by noenif** [comment]
老大公式确实有问题   
我就这两个月没有整文档  然后发现有点问题,以前 我给定以下内容,会自动渲染,但是现在不太行
我用了老版本的vditor3.9.8,是可以成功渲染的.
本来我是用mathpix +这个思源,

latex:
工作量与持续时间之比 $T_1 / T_{\infty}$ 给出了多线程计算的并行度 (parallelism)。我们可以从三个角度来诠释并行度。作为一个比值, 并行度表示沿着关键路径每一步可被并行执行的平均合计工作量。作为一个上界, 并行度给出了最大的可能加速比, 这是在任何数目的处理器上所能达到的。最后, 也许是最重要的, 并行度给出了获得完美线性加速的一个限制。具体地讲, 一旦处理器数目超过了并行度, 计算就不可能达到完美线性加速。为了明白最后一点, 假设 $P>T_1 / T_{\infty}$,此时由持续时间定律可以推得, 加速比满足 $T_1 / T_P \leqslant T_1 / T_{\infty}<P$ 。此外, 如果理想计算机中的处理器数 $P$ 远远超过了并行度, 即 $P \gg T_1 / T_{\infty}$, 那么就有 $T_1 / T_P \ll P$, 所以加速比会远小于处理器的数目。换句话说, 我们使用超出并行度越多的处理器数目, 加速比就会越不完美。

作为一个例子, 考虑图 27-2 中的 P-FIB(4) 计算, 假设每个链耗费单位时间。工作量为 $T_1=$ 17 , 持续时间为 $T_{\infty}=8$, 并行度是 $T_1 / T_{\infty}=17 / 8=2.125$ 。所以, 不论使用多少个处理器, 要达到加速比的翻番及更多都是不可能的。然而, 对于更大的输人规模, 我们将会看到 P-FIB $(n)$ 展示出更大的并行度。

对于一台有 $P$ 个处理器的理想计算机上执行的一个多线程计算, 定义 (并行) 松驰度 (slackness) 为 $\left(T_1 / T_{\infty}\right) / P=T_1 /\left(P T_{\infty}\right)$, 这是一个有关计算并行度超出机器中处理器数目的因子。因此, 如果松驰度小于 1 , 就得不到完美线性加速, 这是因为 $T_1 /\left(P T_{\infty}\right)<1$, 且由持续时间定律知, $P$ 个处理器上的加速比满足 $T_1 / T_P \leqslant T_1 / T_{\infty}<P$ 。实际上, 随着松驰度从 1 降到 0 , 加速比越来越远离完美线性加速。然而, 如果松驰度大于 1 , 每个处理器就有工作量方面的要求。后面我们将看到, 随着松驰度从 1 开始继续增加, 一个好的调度器可以使算法的加速比越来越接近完美线性加速。

**Comment by noenif** [comment]
latex:


`工作量与持续时间之比 $T_1 / T_{\infty}$ 给出了多线程计算的并行度 (parallelism)。我们可以从三个角度来诠释并行度。作为一个比值, 并行度表示沿着关键路径每一步可被并行执行的平均合计工作量。作为一个上界, 并行度给出了最大的可能加速比, 这是在任何数目的处理器上所能达到的。最后, 也许是最重要的, 并行度给出了获得完美线性加速的一个限制。具体地讲, 一旦处理器数目超过了并行度, 计算就不可能达到完美线性加速。为了明白最后一点, 假设 $P>T_1 / T_{\infty}$,此时由持续时间定律可以推得, 加速比满足 $T_1 / T_P \leqslant T_1 / T_{\infty}<P$ 。此外, 如果理想计算机中的处理器数 $P$ 远远超过了并行度, 即 $P \gg T_1 / T_{\infty}$, 那么就有 $T_1 / T_P \ll P$, 所以加速比会远小于处理器的数目。换句话说, 我们使用超出并行度越多的处理器数目, 加速比就会越不完美。

作为一个例子, 考虑图 27-2 中的 P-FIB(4) 计算, 假设每个链耗费单位时间。工作量为 $T_1=$ 17 , 持续时间为 $T_{\infty}=8$, 并行度是 $T_1 / T_{\infty}=17 / 8=2.125$ 。所以, 不论使用多少个处理器, 要达到加速比的翻番及更多都是不可能的。然而, 对于更大的输人规模, 我们将会看到 P-FIB $(n)$ 展示出更大的并行度。

对于一台有 $P$ 个处理器的理想计算机上执行的一个多线程计算, 定义 (并行) 松驰度 (slackness) 为 $\left(T_1 / T_{\infty}\right) / P=T_1 /\left(P T_{\infty}\right)$, 这是一个有关计算并行度超出机器中处理器数目的因子。因此, 如果松驰度小于 1 , 就得不到完美线性加速, 这是因为 $T_1 /\left(P T_{\infty}\right)<1$, 且由持续时间定律知, $P$ 个处理器上的加速比满足 $T_1 / T_P \leqslant T_1 / T_{\infty}<P$ 。实际上, 随着松驰度从 1 降到 0 , 加速比越来越远离完美线性加速。然而, 如果松驰度大于 1 , 每个处理器就有工作量方面的要求。后面我们将看到, 随着松驰度从 1 开始继续增加, 一个好的调度器可以使算法的加速比越来越接近完美线性加速。`

**Comment by noenif** [comment]
[公式.txt](https://github.com/siyuan-note/siyuan/files/15286170/default.txt)

**Comment by noenif** [comment]
可以了开启了
![image](https://github.com/siyuan-note/siyuan/assets/25174520/c52d126a-e5ac-491a-b291-b8b6ef25d885)
