### ISSUE TITLE
数据库多选选项能否选择按使用频率自动排序，还是自己手动排序

### ISSUE THREAD

**Issue by 915480091** [siyuan-note/siyuan#10157]
### In what scenarios do you need this feature?

1.数据库选择选项时，有时不按照默认排序，想按照使用频率将使用最多的放在最上面，有的选项是按照固定手工排序。
2.数据库选项能不能设置默认值，或者和notion一样设置个自动化，符合什么条件时将某个选项设置为某值。类似待办视图中默认选项选择待办

### Describe the optimal solution

分出几个选择项来，用以指定按什么排序还是手动排序

**Comment by 88250** [comment]
这个只能按已有的排序，不考虑按使用频率自动排序了，见谅。

关于默认值，目前也不考虑了，后面会支持多选填充，请关注 https://github.com/siyuan-note/siyuan/issues/9867
