### ISSUE TITLE
特性建议：添加相关文档功能

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10165]
### In what scenarios do you need this feature?

思源的双向链接很方便，可以在一个文档的反链面板查看相关文档，但是反链面板可能既有块，也有文档，既有dailynote，也有整理完善的概念笔记，这就对筛选重要相关文档造成了一定麻烦

并且，我习惯用Moc组织文档，新建文档、块引新建文档都是按月份存放，希望不受制于文档树的单一分类，可以随心所欲在不同的MOC文档放链接。但是这样也有一个很大的问题，比如我有一个笔记《Matlab 深度学习丨训练CNN用于手写数字识别》，是放到《@Matlab 深度学习》这个MOC页面里的
<img width="537" alt="Snipaste_2024-01-13_13-12-15" src="https://github.com/siyuan-note/siyuan/assets/60436214/8426b48b-998c-47aa-a4a7-3eb8dfdcbb9c">
但是当我从《Matlab 深度学习丨训练CNN用于手写数字识别》，想回到《@Matlab 深度学习》时，只能通过反链面板返回，而反链面板常常有其他文档，就会造成一定的干扰
<img width="261" alt="Snipaste_2024-01-13_13-16-53" src="https://github.com/siyuan-note/siyuan/assets/60436214/87c03813-b6f2-43c2-b38f-ce5f74aa6e77">

手动的方法当然也可以在笔记前面放置相关文档，方便跳转，但是会污染笔记内容，不方便分享到网络，且需要翻到笔记最上面或最下面才能跳转

我现在有一个想法是，思源可以新建一个dock按钮， 展开后可以手动给这篇笔记添加、删除、排序相关文档，手动给两篇笔记建立单向链接关系或双向链接

我个人认为双向链接是比较任意、尽可能建立链接，而我这边指的相关文档功能，更倾向于建立筛选过后重要的链接
### Describe the optimal solution

在dock面板添加相关文档功能

### Describe the candidate solution

在属性面板添加相关文档这个功能，用户可以在上面添加人工筛选的文档，
<img width="640" alt="Snipaste_2024-01-13_13-07-35" src="https://github.com/siyuan-note/siyuan/assets/60436214/a0ab9f7a-a028-40c8-a654-e0d124041a64">

### Other information
此外，我发现反链面板的筛选，貌似不能根据文档名筛选，我的moc页面都会以@为前缀，但是使用@就无法搜索到moc页面了
<img width="227" alt="Snipaste_2024-01-13_13-24-31" src="https://github.com/siyuan-note/siyuan/assets/60436214/29c975a5-943e-4332-8cf9-3a2220e33eb9">

**Comment by Achuan-2** [comment]
哈哈哈，你这样一说确实 @tcmtom

**Comment by 88250** [comment]
暂时不考虑了，也许可以期待一下相关插件，感谢提议。
