### ISSUE TITLE
Flashcards are not allowed to be modified during data sync to avoid data overwriting

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10167]
win端和安卓端混合复习情况下会导致当日已学习闪卡变成未学习状态

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

大概是上午学习了100张闪卡，同步后中午使用手机复习一段时间，手机端同步数据之后，电脑端发现已学习卡片变成未学习状态了

### Expected result

希望修复

### Version environment

```markdown
- Version: 2.12。2
- Operating System: 
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13927321/system-log.zip)
[8.3真理及其与价值的关系.sy.zip](https://github.com/siyuan-note/siyuan/files/13927322/8.3.sy.zip)

**Comment by 88250** [comment]
电脑端是不是一直开着闪卡间隔重复界面？

**Comment by QQQOrange** [comment]
> 电脑端是不是一直开着闪卡间隔重复界面？

没有的 电脑关机了

**Comment by 88250** [comment]
麻烦再上传一下各个端的日志，以便分析。

**Comment by QQQOrange** [comment]
> 麻烦再上传一下各个端的日志，以便分析。

已传的是电脑端，补上手机端的

**Comment by QQQOrange** [comment]
[system-log.zip](https://github.com/siyuan-note/siyuan/files/13928079/system-log.zip)


> > 麻烦再上传一下各个端的日志，以便分析。
> 
> 已传的是电脑端，补上手机端的



> 麻烦再上传一下各个端的日志，以便分析。

**Comment by 88250** [comment]
找到问题了，在 app 的日志上：

```
W 2024/01/13 11:14:32 diff.go:56: prevent old upsert left [6b1dd47327a5444c0a42de31df49cf245bacdd92, /storage/riff/20230218211946-2kw8jgx.deck, 2024-01-13 10:27:11] overwrite right [9dcacd6987067bba3e99562490bccdd0e7695a34, /storage/riff/20230218211946-2kw8jgx.deck, 2024-01-13 11:13:33]
```

说明在同步执行过程中使用了闪卡（制卡或者复习），这时同步还没有完成，导致 app 产生了新的数据变动所以覆盖了云端 10:27 的数据。

麻烦回忆一下当时使用的是制卡还是复习，谢谢。

**Comment by QQQOrange** [comment]
> 找到问题了，在 app 的日志上：
> 
> ```
> W 2024/01/13 11:14:32 diff.go:56: prevent old upsert left [6b1dd47327a5444c0a42de31df49cf245bacdd92, /storage/riff/20230218211946-2kw8jgx.deck, 2024-01-13 10:27:11] overwrite right [9dcacd6987067bba3e99562490bccdd0e7695a34, /storage/riff/20230218211946-2kw8jgx.deck, 2024-01-13 11:13:33]
> ```
> 
> 说明在同步执行过程中使用了闪卡（制卡或者复习），这时同步还没有完成，导致 app 产生了新的数据变动所以覆盖了云端 10:27 的数据。
> 
> 麻烦回忆一下当时使用的是制卡还是复习，谢谢。

这个时间电脑没关，思源也是开着的，所以但是我记不清那个时候手机的思源开没开了

**Comment by 88250** [comment]
和电脑关系不大，主要是 app 上同步的过程中使用了闪卡，但是我想知道是使用了制卡还是间隔重复。

**Comment by 88250** [comment]
稍后我们会改进这个地方，在同步期间不允许制卡/取消制卡，以避免数据覆盖，感谢反馈。

**Comment by QQQOrange** [comment]
> 和电脑关系不大，主要是 app 上同步的过程中使用了闪卡，但是我想知道是使用了制卡还是间隔重复。

制卡吧

**Comment by 88250** [comment]
收到。



---Original---
From: ***@***.***&gt;
Date: Sun, Jan 14, 2024 06:36 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Flashcards are not allowed to be modifiedduring data sync to avoid data overwriting (Issue #10167)




  
和电脑关系不大，主要是 app 上同步的过程中使用了闪卡，但是我想知道是使用了制卡还是间隔重复。
  
制卡吧
