### ISSUE TITLE
文档块支持备注

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#1016]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
当我们收集文档的时候我们一般需要对文档的作者、来源、关键启等进行描述，结合标签等内容可以进行美化作用
配合动态探索使用非常完美，比如我可以做一个模板是某个作者，某个来源的，这样就可以不依赖文件夹树，而可以发挥动态搜索的功能，查询结果可以保存起来随时使用，就像数据达到一定数量，文件的管理方式明细是SQL的方式效率要高很多，如果支持SQL方式的操作文档那就更完美了，比如批量的删除，更新等

### 描述最优的解决方案 Describe the optimal solution
类似源代码的注释功能，不限于对于文档的元描述，也可以其他类型的块的无描述
例如引用文档时可以只显示一下本文档的元描述块，比单一显示一个标题要或者修改替代文字要好很多

**Comment by 88250** [comment]
我们对于 SQL 数据库是限于只读的，这一点估计短时间内不会改变，因为数据库是临时创建的，不作为持久化使用信息。需要放置的元信息目前只能放在文本里或者配置文件里，以后可能会在笔记本下面加 .siyuan 文件夹来放更多的元数据。

**Comment by GlowBlur** [comment]
其实就是想放一些信息可以被检索但是又不想被展示，但是放一起又折叠嘛又不是特别美观

**Comment by 88250** [comment]
放到内容块备注里面如何？

**Comment by GlowBlur** [comment]
但是文档块如何处理呢

**Comment by 88250** [comment]
文档块后面会加上备注支持的，再等等，谢谢。

**Comment by roverway** [comment]
文档块的备注用markdown文件的front matters解决，感觉很合适。
这是typora的样式，思源笔记也类似：
![image](https://user-images.githubusercontent.com/657850/104258278-249f4500-54ba-11eb-8a2b-bdbf26a4eb13.png)
其实思源笔记可以考虑对front matters做更好的支持，front matters天然适合用于描述文档块元信息，比如在识别其中的tag，alias等等，用于搜索或者形成图谱等等。

**Comment by 88250** [comment]
@roverway 感谢建议，之前我们考虑过使用 YAML Front Matter 的，但在思源中更适合的是通过 kramdown IAL 来进行统一，因为 YFM 限制有点大，比如只能用在文档块上，只能写在开头。

**Comment by GlowBlur** [comment]
@roverway 老哥我想到的就是想实现这样的效果

**Comment by roverway** [comment]
> @roverway 老哥我想到的就是想实现这样的效果

现在在思源笔记也可以这么用，思源笔记当正文的一部分处理了。看起来像这样：

![image](https://user-images.githubusercontent.com/657850/104275744-69d56e00-54de-11eb-80d1-25b9b5de0c3f.png)

**Comment by deerainw** [comment]
@88250 

通过 kramdown IAL 来进行统一是好事，但是文档的命名和内容块的命名有个关键区别，那就是文档的别名一般都会用上多个，而内容块一般单个命名就够了。不知道现在这种路线能否实现 Obsidian 这种单个文档多个别名？🤔

![image](https://user-images.githubusercontent.com/32661922/104812790-a6d39480-583f-11eb-9e99-10e7b46aa97b.png)

另外将来在优化导入导出的时候是不是也考虑一下这个元素的转换... 其它 YAML 元素其实意义不大，文档别名如果没了的话大量提及项就直接报废了，如果能把 Obsidian 的 aliases 项在导入时直接转成思源的 kramdown IAL 也有利于 Obsidian 重度用户直接转过来，反正据我了解 9.17 版本之后还在继续用 Obsidian 的用户基本都比较依赖别名功能

**Comment by 88250** [comment]
@deerainw 之前支持内容块命名的时候本来想直接支持多个别名属性的，后来觉得用处不大就暂时没加了……块的别名属性等后面应该会支持，目前需求不是太强，因为思源里面的块引不区分文档和非文档，也许实际上非文档的块引用户用得更多。

**Comment by roverway** [comment]
> @deerainw 之前支持内容块命名的时候本来想直接支持多个别名属性的，后来觉得用处不大就暂时没加了……块的别名属性等后面应该会支持，目前需求不是太强，因为思源里面的块引不区分文档和非文档，也许实际上非文档的块引用户用得更多。
> 
> 导入我们打算靠社区贡献，因为底层 Markdown 引擎是开源的，所以理论上基于这个应该能比较容易实现各类系统的导入或者导出，暂时是这样考虑的。

别名可以理解为块的关键词或者含义的概括，一个块从不同角度看总是可以提炼出不同的关键词的，用于构建或者发现块之间的联系，别名还是很有用的一个特性。 @88250

**Comment by 88250** [comment]
内容块别名请关注 https://github.com/siyuan-note/siyuan/issues/1126
