### ISSUE TITLE
设置中按esc回到上一个设置页面而不是退出设置

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10169]
### In what scenarios do you need this feature?

例如我在设置-集市-主题 中 点开某一个主题，看完介绍后想退出看其他的主题，按了一下esc，就可以推到集市的主题页面，而不是直接退出设置

### Describe the optimal solution

例如我在设置-集市-主题 中 点开某一个主题，看完介绍后想退出看其他的主题，按了一下esc，就可以推到集市的主题页面，而不是直接退出设置

**Comment by 88250** [comment]
这个交互暂时不考虑改变了，谢谢。
