### ISSUE TITLE
Add some database related internal kernel APIs

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10160]
* /api/av/addAttributeViewKey
* /api/av/removeAttributeViewKey
* /api/av/sortAttributeViewKey

**Comment by 88250** [comment]
@InEase 麻烦有空的时候测试下，谢谢。

**Comment by InEase** [comment]
好嘞收到！ 没问题！ 感谢 & 赞美 DV！！！

**Comment by 88250** [comment]
排序接口有变更，参考 https://github.com/siyuan-note/siyuan/issues/11428
