### ISSUE TITLE
文字替换功能失效

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

例如我想替换某一个文档树下的全部的“1”为空值，那么在搜索框输入1，第二个输入框什么都不输入，点击替换，软件自动重启页面之后“1”，都在
目的在于删除文档中的所有“1”

### Expected result

希望解决

### Version environment

```markdown
- Version: 2.12。2
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
我这里测试正常，请确认 替换类型 是否正确。

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/122d8a39-135b-4dd7-aaff-d94a22e2eec7)

先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by QQQOrange** [comment]
> 我这里测试正常，请确认 替换类型 是否正确。
> 
>  issue.webm 
> 先关闭了，如果还有问题请继续跟帖，谢谢 🙏

我这边是失效的，都不说子文档了，当前文档都失效，替换的是②，替换类型均全部勾选

这是替换之前
![image](https://github.com/siyuan-note/siyuan/assets/62794181/53a84388-dca3-49cc-9fc8-dcb983aaf9bb)
这是替换页面
![image](https://github.com/siyuan-note/siyuan/assets/62794181/d80692b0-dfc5-4a29-b012-9c27cc100705)
这是替换结果
![image](https://github.com/siyuan-note/siyuan/assets/62794181/9a053951-e71e-4a60-8b2e-8b5c24033513)
这是日志
[system-log.zip](https://github.com/siyuan-note/siyuan/files/13919647/system-log.zip)
这是具体文档
[1 一 《哲学的贫困》在对蒲鲁东唯心史观的批判中对唯物史观的发展和完善.sy.zip](https://github.com/siyuan-note/siyuan/files/13919649/1.sy.zip)

**Comment by Jiangshuon** [comment]
> > 我这里测试正常，请确认 替换类型 是否正确。
> > issue.webm
> > 先关闭了，如果还有问题请继续跟帖，谢谢 🙏
> 
> 我这边是失效的，都不说子文档了，当前文档都失效，替换的是②，替换类型均全部勾选
> 
> 这是替换之前 ![image](https://private-user-images.githubusercontent.com/62794181/296254887-53a84388-dca3-49cc-9fc8-dcb983aaf9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTQ4ODctNTNhODQzODgtZGNhMy00OWNjLTlmYzgtZGNiOTgzYWFmOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODU4YWFhNWY5NzNlMDdhOWM3YjEwNmQ4YWJmZGM0YjMxYmViNWZjOWQzZDczYzkxYTA2NDYyZmY1N2YyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rvfU4NMSRyGmFD1CxoydCqYJQ85E_L9nrt3g-mdXco) 这是替换页面 ![image](https://private-user-images.githubusercontent.com/62794181/296255368-d80692b0-dfc5-4a29-b012-9c27cc100705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTUzNjgtZDgwNjkyYjAtZGZjNS00YTI5LWIwMTItOWMyN2NjMTAwNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZmZiZDEyNmI1NmNlNWIyZTQ4ZTY1MDYzOTVlZDViZWJkZjEwNGFlNjZhZmQ0YTg2YTk4MTZiMjg5ODhhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwdZtepoYChyODfGpdCjB1tGklIaxsydFIkmDQhBeE8) 这是替换结果 ![image](https://private-user-images.githubusercontent.com/62794181/296255408-9a053951-e71e-4a60-8b2e-8b5c24033513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTU0MDgtOWEwNTM5NTEtZTcxZS00YTYwLThiMmUtOGI1YzI0MDMzNTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZThlMGM5MDEzMjE2OGZiMzhmYTZiOTgxYWI0MDg0NWNhNmVmNDY4ODA3ZTMxODg3MmUwMjYxMDU2OGVjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4tzPGTJ3oUo3XAwWYDLvoRwHwX4Psr5vLP4IY7hJZw) 这是日志 [system-log.zip](https://github.com/siyuan-note/siyuan/files/13919647/system-log.zip) 这是具体文档 [1 一 《哲学的贫困》在对蒲鲁东唯心史观的批判中对唯物史观的发展和完善.sy.zip](https://github.com/siyuan-note/siyuan/files/13919649/1.sy.zip)

你用了文档分组，不用分组应该可以成功

**Comment by QQQOrange** [comment]
> > > 我这里测试正常，请确认 替换类型 是否正确。
> > > issue.webm
> > > 先关闭了，如果还有问题请继续跟帖，谢谢 🙏
> > 
> > 
> > 我这边是失效的，都不说子文档了，当前文档都失效，替换的是②，替换类型均全部勾选
> > 这是替换之前 ![image](https://private-user-images.githubusercontent.com/62794181/296254887-53a84388-dca3-49cc-9fc8-dcb983aaf9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTQ4ODctNTNhODQzODgtZGNhMy00OWNjLTlmYzgtZGNiOTgzYWFmOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODU4YWFhNWY5NzNlMDdhOWM3YjEwNmQ4YWJmZGM0YjMxYmViNWZjOWQzZDczYzkxYTA2NDYyZmY1N2YyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rvfU4NMSRyGmFD1CxoydCqYJQ85E_L9nrt3g-mdXco) 这是替换页面 ![image](https://private-user-images.githubusercontent.com/62794181/296255368-d80692b0-dfc5-4a29-b012-9c27cc100705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTUzNjgtZDgwNjkyYjAtZGZjNS00YTI5LWIwMTItOWMyN2NjMTAwNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZmZiZDEyNmI1NmNlNWIyZTQ4ZTY1MDYzOTVlZDViZWJkZjEwNGFlNjZhZmQ0YTg2YTk4MTZiMjg5ODhhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwdZtepoYChyODfGpdCjB1tGklIaxsydFIkmDQhBeE8) 这是替换结果 ![image](https://private-user-images.githubusercontent.com/62794181/296255408-9a053951-e71e-4a60-8b2e-8b5c24033513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTU0MDgtOWEwNTM5NTEtZTcxZS00YTYwLThiMmUtOGI1YzI0MDMzNTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZThlMGM5MDEzMjE2OGZiMzhmYTZiOTgxYWI0MDg0NWNhNmVmNDY4ODA3ZTMxODg3MmUwMjYxMDU2OGVjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4tzPGTJ3oUo3XAwWYDLvoRwHwX4Psr5vLP4IY7hJZw) 这是日志 [system-log.zip](https://github.com/siyuan-note/siyuan/files/13919647/system-log.zip) 这是具体文档 [1 一 《哲学的贫困》在对蒲鲁东唯心史观的批判中对唯物史观的发展和完善.sy.zip](https://github.com/siyuan-note/siyuan/files/13919649/1.sy.zip)
> 
> 你用了文档分组，不用分组应该可以成功
 主要是一本书内容太多了 不分组的话 想要明确知道自己的阅读进度，或者使用渐进学习插件的话 就比较困难

**Comment by Jiangshuon** [comment]
@88250 

> > > > 我这里测试正常，请确认 替换类型 是否正确。
> > > > issue.webm
> > > > 先关闭了，如果还有问题请继续跟帖，谢谢 🙏
> > > 
> > > 
> > > 我这边是失效的，都不说子文档了，当前文档都失效，替换的是②，替换类型均全部勾选
> > > 这是替换之前 ![image](https://private-user-images.githubusercontent.com/62794181/296254887-53a84388-dca3-49cc-9fc8-dcb983aaf9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTQ4ODctNTNhODQzODgtZGNhMy00OWNjLTlmYzgtZGNiOTgzYWFmOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODU4YWFhNWY5NzNlMDdhOWM3YjEwNmQ4YWJmZGM0YjMxYmViNWZjOWQzZDczYzkxYTA2NDYyZmY1N2YyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rvfU4NMSRyGmFD1CxoydCqYJQ85E_L9nrt3g-mdXco) 这是替换页面 ![image](https://private-user-images.githubusercontent.com/62794181/296255368-d80692b0-dfc5-4a29-b012-9c27cc100705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTUzNjgtZDgwNjkyYjAtZGZjNS00YTI5LWIwMTItOWMyN2NjMTAwNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZmZiZDEyNmI1NmNlNWIyZTQ4ZTY1MDYzOTVlZDViZWJkZjEwNGFlNjZhZmQ0YTg2YTk4MTZiMjg5ODhhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwdZtepoYChyODfGpdCjB1tGklIaxsydFIkmDQhBeE8) 这是替换结果 ![image](https://private-user-images.githubusercontent.com/62794181/296255408-9a053951-e71e-4a60-8b2e-8b5c24033513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTU0MDgtOWEwNTM5NTEtZTcxZS00YTYwLThiMmUtOGI1YzI0MDMzNTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZThlMGM5MDEzMjE2OGZiMzhmYTZiOTgxYWI0MDg0NWNhNmVmNDY4ODA3ZTMxODg3MmUwMjYxMDU2OGVjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4tzPGTJ3oUo3XAwWYDLvoRwHwX4Psr5vLP4IY7hJZw) 这是日志 [system-log.zip](https://github.com/siyuan-note/siyuan/files/13919647/system-log.zip) 这是具体文档 [1 一 《哲学的贫困》在对蒲鲁东唯心史观的批判中对唯物史观的发展和完善.sy.zip](https://github.com/siyuan-note/siyuan/files/13919649/1.sy.zip)
> > 
> > 
> > 你用了文档分组，不用分组应该可以成功
> > 主要是一本书内容太多了 不分组的话 想要明确知道自己的阅读进度，或者使用渐进学习插件的话 就比较困难

不是，我意思是你在**搜索界面**用了文档分组功能，所以替换失效。搜索时不分组可以替换成功，所以目前，你想替换的时候要先取消文档分组功能。大佬这似乎是个bug  @88250

**Comment by QQQOrange** [comment]
> @88250
> 
> > > > > 我这里测试正常，请确认 替换类型 是否正确。
> > > > > issue.webm
> > > > > 先关闭了，如果还有问题请继续跟帖，谢谢 🙏
> > > > 
> > > > 
> > > > 我这边是失效的，都不说子文档了，当前文档都失效，替换的是②，替换类型均全部勾选
> > > > 这是替换之前 ![image](https://private-user-images.githubusercontent.com/62794181/296254887-53a84388-dca3-49cc-9fc8-dcb983aaf9bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTQ4ODctNTNhODQzODgtZGNhMy00OWNjLTlmYzgtZGNiOTgzYWFmOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhODU4YWFhNWY5NzNlMDdhOWM3YjEwNmQ4YWJmZGM0YjMxYmViNWZjOWQzZDczYzkxYTA2NDYyZmY1N2YyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4rvfU4NMSRyGmFD1CxoydCqYJQ85E_L9nrt3g-mdXco) 这是替换页面 ![image](https://private-user-images.githubusercontent.com/62794181/296255368-d80692b0-dfc5-4a29-b012-9c27cc100705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTUzNjgtZDgwNjkyYjAtZGZjNS00YTI5LWIwMTItOWMyN2NjMTAwNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZmZiZDEyNmI1NmNlNWIyZTQ4ZTY1MDYzOTVlZDViZWJkZjEwNGFlNjZhZmQ0YTg2YTk4MTZiMjg5ODhhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwdZtepoYChyODfGpdCjB1tGklIaxsydFIkmDQhBeE8) 这是替换结果 ![image](https://private-user-images.githubusercontent.com/62794181/296255408-9a053951-e71e-4a60-8b2e-8b5c24033513.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzMwNjQsIm5iZiI6MTcwNTA3Mjc2NCwicGF0aCI6Ii82Mjc5NDE4MS8yOTYyNTU0MDgtOWEwNTM5NTEtZTcxZS00YTYwLThiMmUtOGI1YzI0MDMzNTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZThlMGM5MDEzMjE2OGZiMzhmYTZiOTgxYWI0MDg0NWNhNmVmNDY4ODA3ZTMxODg3MmUwMjYxMDU2OGVjMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R4tzPGTJ3oUo3XAwWYDLvoRwHwX4Psr5vLP4IY7hJZw) 这是日志 [system-log.zip](https://github.com/siyuan-note/siyuan/files/13919647/system-log.zip) 这是具体文档 [1 一 《哲学的贫困》在对蒲鲁东唯心史观的批判中对唯物史观的发展和完善.sy.zip](https://github.com/siyuan-note/siyuan/files/13919649/1.sy.zip)
> > > 
> > > 
> > > 你用了文档分组，不用分组应该可以成功
> > > 主要是一本书内容太多了 不分组的话 想要明确知道自己的阅读进度，或者使用渐进学习插件的话 就比较困难
> 
> 不是，我意思是你在**搜索界面**用了文档分组功能，所以替换失效。搜索时不分组可以替换成功，所以目前，你想替换的时候要先取消文档分组功能。大佬这似乎是个bug @88250

确实是 给大佬跪了

**Comment by 88250** [comment]
@Jiangshuon 感觉定位问题，下个版本会进行提示：

> 按文档分组后不支持替换操作，请使用取消分组后再进行替换
