### ISSUE TITLE
Remove database table view menu when switching or adding tabs

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在数据库编辑框内使用ALt+5跳入新页面后，编辑框无法自动消失。
![GIF 2024-1-13 21-15-41](https://github.com/siyuan-note/siyuan/assets/5708881/be566319-6000-4e21-a0fb-3a3b62b619cf)

### Expected result

如题

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

暂无

**Comment by 88250** [comment]
感谢反馈，下个版本解决。
