### ISSUE TITLE
块引搜索，段落块会在文档块之前

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

最近几个版本发现块引搜索，段落块会在文档块之前
<img width="612" alt="Snipaste_2024-01-13_12-16-06" src="https://github.com/siyuan-note/siyuan/assets/60436214/00d694ef-090d-4202-a247-51ebe67d0c09">
<img width="625" alt="Snipaste_2024-01-13_12-19-10" src="https://github.com/siyuan-note/siyuan/assets/60436214/a4879e58-64a4-4ca2-abaa-d3dfab2a8197">

想知道这个是bug，还是我设置问题？
还是特性？貌似在前面的几个块都有关键词多个命中

### Expected result

块引搜索，文档块默认在其他块之前

### Version environment

```markdown
- Version: v2.12.2
- Operating System: 
- Browser (if used):
```

### Log file

none

**Comment by Achuan-2** [comment]
哦哦，我发现我没开启这个
<img width="771" alt="Snipaste_2024-01-13_12-28-12" src="https://github.com/siyuan-note/siyuan/assets/60436214/69b86968-9043-4842-91c8-077ec3009c19">

**Comment by 88250** [comment]
块引搜索有个排序算法，大致是这样的：

```
	orderBy := ` order by case
             when name = '${keyword}' then 10
             when alias = '${keyword}' then 20
             when memo = '${keyword}' then 30
             when content = '${keyword}' and type = 'd' then 40
             when content LIKE '%${keyword}%' and type = 'd' then 41
             when name LIKE '%${keyword}%' then 50
             when alias LIKE '%${keyword}%' then 60
             when content = '${keyword}' and type = 'h' then 70
             when content LIKE '%${keyword}%' and type = 'h' then 71
             when fcontent = '${keyword}' and type = 'i' then 80
             when fcontent LIKE '%${keyword}%' and type = 'i' then 81
             when memo LIKE '%${keyword}%' then 90
             when content LIKE '%${keyword}%' and type != 'i' and type != 'l' then 100
             else 65535 end ASC, sort ASC, length ASC`
```

我关闭了，感谢反馈。

**Comment by Achuan-2** [comment]
【【可以指定只搜索文档，选中文字之后Ctrl+【可以设置只搜索文档吗，目前我有好多次搜索都出现了代码块会在文档块之前的情况，此外感觉代码块的权重比文档块还高了？因为只是命中一次而已
<img width="169" alt="Snipaste_2024-01-16_22-53-32" src="https://github.com/siyuan-note/siyuan/assets/60436214/ce6fc44d-3ae3-45aa-b128-d1569d9e40ec">
<img width="391" alt="Snipaste_2024-01-16_22-54-15" src="https://github.com/siyuan-note/siyuan/assets/60436214/c06c9f6b-e0ce-4256-987a-205f429bb0d3">

**Comment by Achuan-2** [comment]
Ctrl+P搜索是正常的
<img width="766" alt="Snipaste_2024-01-16_23-09-39" src="https://github.com/siyuan-note/siyuan/assets/60436214/08990200-a63a-4cb3-903c-3e5e3004341f">

但是Ctrl+【就是段落块和代码块会在文档块之前
<img width="352" alt="Snipaste_2024-01-16_23-10-29" src="https://github.com/siyuan-note/siyuan/assets/60436214/a231e8e2-0d11-4525-a3d8-81c961387366">

**Comment by 88250** [comment]
麻烦制作一个能够重现问题的最小数据集，我调试看看。

**Comment by 88250** [comment]
定位到问题了，是在 https://github.com/siyuan-note/siyuan/issues/8886 中引入的 bug，下个版本修复，多谢。

**Comment by Achuan-2** [comment]
好滴，辛苦
