### ISSUE TITLE
闪卡正面按钮文字显示被选中

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

闪卡页面的正面按钮上的文字显示被选中的状态
![image](https://github.com/siyuan-note/siyuan/assets/62794181/6a27e34f-f6f1-4b70-b3a3-e9e213dd4a57)
![image](https://github.com/siyuan-note/siyuan/assets/62794181/2d88bad8-60d6-4f60-bd88-0081b96e0f80)

实际上应该是这样
![image](https://github.com/siyuan-note/siyuan/assets/62794181/da4dcfe2-961e-49da-a4f6-43945c757ddd)
![image](https://github.com/siyuan-note/siyuan/assets/62794181/1c1299b2-915a-49fb-a7d7-683c5585aa52)

默认主题的这种问题显示的不明显 但是连续换了几个主题都是这样，应该是思源本身的问题

### Expected result

期待修复

### Version environment

```markdown
- Version: 2.12.2
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
我这里无法重现问题，请检查是否是插件或者代码片段等扩展影响。

**Comment by QQQOrange** [comment]
> 我这里无法重现问题，请检查是否是插件或者代码片段等扩展影响。

把拓展和代码片段全关了 再重启应用后 还有
[system-log.zip](https://github.com/siyuan-note/siyuan/files/13930447/system-log.zip)

**Comment by Vanessa219** [comment]
已修改
e46453b5318032eabf2dda830e8625bffebc9044
