### ISSUE TITLE
数据库添加记录，默认的主键不为空

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/16383685/18345113-5072-43c7-b096-979a288bbf6c

### Expected result

新建记录的主键应该为空

### Version environment

```markdown
- Version: 2.12.2
- Operating System: Windows 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13930368/siyuan.log)

**Comment by 88250** [comment]
在添加了过滤的情况下只能复制上一行的值，否则添加行后就不可见了。
