### ISSUE TITLE
Focus block does not add the title when exporting as an image

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在思源笔记里聚焦标题
<img width="609" alt="Snipaste_2024-01-14_13-45-47" src="https://github.com/siyuan-note/siyuan/assets/60436214/a4d52308-ac17-4759-92d1-1ea47b4237f3">
导出图片后，发现上方margin过大
<img width="558" alt="Snipaste_2024-01-14_13-46-37" src="https://github.com/siyuan-note/siyuan/assets/60436214/5003ab25-1f34-4264-98b1-7983a8387304">

### Expected result

个人觉得要么这个位置展示标题，要么就margin调为正常导出的margin

### Version environment

```markdown
- Version: 2.12.2
- Operating System: Win11
- Browser (if used):
```

### Log file

none

**Comment by Vanessa219** [comment]
我用这个导出是正常的，是不是文档有什么特殊的空行？
![image](https://github.com/siyuan-note/siyuan/assets/970828/255bd1f0-2aad-469d-9a43-4714cf6b1673)

**Comment by Achuan-2** [comment]
@Vanessa219 V姐这个是聚焦到一个块导出吗？我导出是这样
![image](https://github.com/siyuan-note/siyuan/assets/60436214/a9a9d952-7b06-4ed6-8368-9e633efcaa60)
