### ISSUE TITLE
pdf 导出丢失背景颜色

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="531" alt="Snipaste_2024-01-14_03-48-51" src="https://github.com/siyuan-note/siyuan/assets/60436214/5e58ad5b-be38-41c7-b13e-d430bb7b8697">

笔记中是给引述块添加背景颜色的，导出之后颜色就消失了

<img width="462" alt="Snipaste_2024-01-14_03-47-35" src="https://github.com/siyuan-note/siyuan/assets/60436214/af77a764-a994-415f-a5f8-405bee9edec6">

主题给标题设置的背景颜色也会消失

### Expected result

pdf导出保留背景颜色

### Version environment

```markdown
- Version: 2.12.2
- Operating System: 
- Browser (if used):
```

### Log file

none

**Comment by Vanessa219** [comment]
https://github.com/electron/electron/issues/20583
