### ISSUE TITLE
主界面加入漫游笔记和日记按钮

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#1017]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
当不打开任务文档时，希望主页面大按钮除了目前的几个外，因为后续功能增加，希望增加日记和漫游笔记的大按钮

**Comment by 88250** [comment]
日记按钮在顶部工具栏上已经有了，随机漫游需要模板支持，这个再缓缓，后面可能会上线模板集市，谢谢。
