### ISSUE TITLE
虚拟引用关键字排除列表手机不能和电脑设置的一致

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

电脑上设置了不少，但手机上一个都没有

### Expected result

手机上能同步相关的内容

### Version environment

```markdown
- Version: 2.12.2
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log-1.zip](https://github.com/siyuan-note/siyuan/files/13934187/system-log-1.zip)

**Comment by QQQOrange** [comment]
手机是安卓的

**Comment by 88250** [comment]
配置不支持同步的，这个只能手动填一下，谢谢。
