### ISSUE TITLE
闪卡页面缩小后比例不对

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

闪卡窗口这样
![image](https://github.com/siyuan-note/siyuan/assets/62794181/b2a72ebe-8550-4464-a271-c82d5e84325c)
点击最大化还原按钮后 缩小后这样
![image](https://github.com/siyuan-note/siyuan/assets/62794181/e288c6a4-e0f2-4fe7-9d95-ef32bafb6d34)

### Expected result

缩小后保持相同比例

### Version environment

```markdown
- Version: 2.12.2
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
拖拽后会记住拖拽的大小和位置，因此就没有办法等比缩放，只能重置布局了。
