### ISSUE TITLE
Improve dynamic anchor text auto-refresh stability

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#10181]
锚文本UI提供刷新按钮

### In what scenarios do you need this feature?

有时候更新了原本的文本块(引用的块)，然后引用的地方不会自动更新，需要手动刷新锚文本 (锚文本内输入一个空格然后再删除)

![image](https://github.com/siyuan-note/siyuan/assets/19968935/0e7c8506-daae-4155-85c4-2478749bc5c2)

希望能提供一个手动刷新的按钮UI来省略这个步骤，或者修复一下能自动刷新(见下面的备选方案)

### Describe the optimal solution

思源笔记可以自动侦测原始文档发生了改变，然后去自动刷新该块的引用块

```
if  当前文本块发生了编辑操作 and 光标移到了别的块   # 认为结束编辑
   if 命名不为空且没发生改变
        # 存在命名，则不需要改变锚文本
        pass
   else
       sql查询当前块的引用块
       更新所有引用块的锚文本
```

这样似乎不用全局重建索引？

**Comment by HowcanoeWang** [comment]
似乎之前存在类似的问题？#5891

不过这次是块引用，不是文档标题

**Comment by 88250** [comment]
麻烦留意不能刷新的场景，我们尽量先解决确定的问题场景，谢谢。

**Comment by HowcanoeWang** [comment]
我这边体验下来，所有的块引用都是需要手动刷新的

放一个mac上的录屏 (屏蔽了所有的插件和主题)

https://github.com/siyuan-note/siyuan/assets/19968935/5afc8740-e99b-448c-bab9-e433e26ffb91

然后新建的块，似乎可以通过F5刷新页面实现更新，但是一些老的块(比如22年建立的引用)，F5并不会更新

https://github.com/siyuan-note/siyuan/assets/19968935/26723196-5ea8-4ab8-8bcd-aa8b5a471185

**Comment by 88250** [comment]
问题有点奇怪，不能稳定重现。

我们需要一点时间考虑是否添加 刷新 按钮，谢谢。

**Comment by HowcanoeWang** [comment]
> 问题有点奇怪，不能稳定重现。
> 
> 我们需要一点时间考虑是否添加 刷新 按钮，谢谢。

我这边比较稳定的是，如果修改完不f5刷新当前页面，那锚文本一定不会更新。

刷新页面或重启思源，部分块引用有概率永远无法刷新，除非手动修改锚文本刷新。

**Comment by 88250** [comment]
可能需要一个类似持久化队列的机制来保证锚文本的自动刷新，我再考虑下看看。

**Comment by 88250** [comment]
对了，之前有过一个相同的列表块动态锚文本不刷新问题 https://github.com/siyuan-note/siyuan/issues/8234 

这样，我们统一在 #8234 中改进动态锚文本自动刷新机制吧，这个 issue 就关闭了。
