### ISSUE TITLE
Improve parsing code block pasted from web page

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#10183]
支持从稀土掘金复制代码块

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

[原文](https://juejin.cn/post/7283037880086708258)是这样的：
<img width="795" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/6146a297-a9dc-4ed8-9dff-7c7effcd4d18">
复制过来变成了这样：
<img width="785" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/ffd1698a-98c2-4789-ade8-186b2077e3db">

### Expected result

希望能把代码正常复制到代码块里面，类似这样的效果：
<img width="838" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/8575e2b0-181d-4fa0-88fc-132327b2fd00">

### Version environment

```markdown
- Version: 2.12.2
- Operating System: MacOS 11.7 BigSur
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
抱歉，无法兼容一些网页的 DOM 结构，这种情况下只能仅复制代码内容，然后填到代码块里了，谢谢。

**Comment by 88250** [comment]
后续有空的时候考虑，谢谢。
