### ISSUE TITLE
锁定云端同步目录失败 2.12.2Please enter the title of the bug report

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/5708881/2436618c-a549-4913-8310-f2c48af0dc46)
系统日志：
[system-log.zip](https://github.com/siyuan-note/siyuan/files/13938710/system-log.zip)

2024-01-15 上午出现此问题。
2024-01-15 14:58 更新：家里 PC 同步无问题，单位 PC 和 IOS 端出现此提示。
2024-01-15 20:11 IOS、家里无问题了，单位PC依旧提示此问题……

help

### Expected result

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
win  2.12.2  edge
```

### Log file

详见附件

**Comment by 88250** [comment]
你好，日志中的情况和 https://ld246.com/article/1705290157412 一模一样，请参考我的回帖处理，谢谢。
