### ISSUE TITLE
自定义词条

### ISSUE THREAD

**Issue by JeGIniiiii** [siyuan-note/siyuan#10190]
### In what scenarios do you need this feature?

使用词条来阅读效率和理解程度

### Describe the optimal solution

是否可以创建自定义词条，并在文档中通过点击这些词条来触发解释卡片的弹出？如今，许多公开文档中含有一些读者可能不熟悉的专业术语，若要为每个术语编写解释会相当耗时。如果能够添加一个功能，让在提及这些词条时，只需点击便能在笔记本中显示其定义，那将极大地提升阅读效率和理解程度。希望字条弹出的卡片中可以添加链接可以添加图片和一些富文本。可以参考飞书文档中的词典功能。

**Comment by 2234839** [comment]
是否需要的是虚拟引用

**Comment by 88250** [comment]
请试试虚拟引用。

**Comment by JeGIniiiii** [comment]
虚拟应用在体验上并和我所描述的功能是类似的，但是虚拟引用没有办法过滤哪些词可以解释

**Comment by 88250** [comment]
可以设置包含和排除列表的。



---原始邮件---
发件人: "Ge ***@***.***&gt;
发送时间: 2024年1月16日(周二) 下午2:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 自定义词条 (Issue #10190)




 
虚拟应用在体验上并和我所描述的功能是类似的，但是虚拟引用没有办法过滤哪些词可以解释
