### ISSUE TITLE
字体颜色为什么没有黑色

### ISSUE THREAD

**Issue by ywgdjryf** [siyuan-note/siyuan#10192]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/149993388/1a3aed0e-6e2b-41a4-b499-e184c20218c5)

### Describe the optimal solution
除了默认颜色黑色以外什么颜色都有，
不能从其他颜色变回来，每次只能删除重新输入
真是服了

**Comment by 88250** [comment]
请使用 清除样式
