### ISSUE TITLE
initKernel fail even if getting system version successfully

### ISSUE THREAD

**Issue by mingpepe** [siyuan-note/siyuan#10197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

After getting the system version, the `finally` block still to check if it reaches the limit count.
Hence it's possible to show error message even if app got system version successfully.

### Expected result

Do not check retry count if success.

### Version environment

```markdown
- Version: 2.12.3
- Operating System: Windows
- Browser (if used):
```

### Log file

NA

**Comment by 88250** [comment]
Hello, thanks for your contribution, I will review it later.
