### ISSUE TITLE
希望内容块的名称或备注能够显式的被看到

### ISSUE THREAD

**Issue by hopebird** [siyuan-note/siyuan#1019]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

我想用内容块的名称或备注，对内容块进行分类，并用内容块动态查询对某一类的内容块进行汇总
### 描述最优的解决方案 Describe the optimal solution

比如我写了个todo，是一个会议。我可以把这个块命名为“会议”，可以在块的开头或末尾用小字把块名显示出来。 我在另外的文档里新建一个动态查询，可以把所有叫“会议”的块汇集在一起，再结合时间，就能统计出今年、某个月开了多少会。
如果一件事用了多个内容块，则可以人工用超级块把它们包裹起来，并命名。这样也能进行查找汇总了。

**Comment by 88250** [comment]
你好，0.6.0 发布以后可以通过 `!{{ name:内容块名称}}` 进行查询。
