### ISSUE TITLE
When adding notes to content with formulas, the formulas will become plain text.

### ISSUE THREAD

**Issue by xiaoheimissu** [siyuan-note/siyuan#10191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When adding notes to content with formulas, the formulas will become plain text.
![image](https://github.com/siyuan-note/siyuan/assets/68829841/7d0d3ad9-9e68-49df-a5b6-864729d6d4de)

### Expected result

Similar to adding underlines, adding notes should not change the content of the text.

### Version environment

```markdown
- Version: 2.12.2
- Operating System: Win11 Pro
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13945362/siyuan.log)

**Comment by 88250** [comment]
Hello, the two elements formula and memo cannot be superimposed.
