### ISSUE TITLE
优化打开文档和文档树的操作

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10195]
### In what scenarios do you need this feature?

现在打开文档树下的子文档需要点击文档名左边的按钮，这样偶尔会出现误触，希望能够提供一个可选的功能。

例如单击鼠标打开文档树，双击打开该文档

或者单击鼠标打开该文档，双击打开文档树

这样的一个好处就在于避免电脑上的误触，还能避免手机上想打开子文档却屡屡大概该文档的窘境

### Describe the optimal solution

当然，不是要求默认强制打开，最好是提供一个选项，这样适应也有操作方式的人也不用做出修改

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/9924
