### ISSUE TITLE
==高亮语法，影响预览换行

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#102]
![I922 3TH)4Z77(S{`HBNQ~5](https://user-images.githubusercontent.com/66795040/94342368-2c3df980-0043-11eb-96a7-8855379324f3.png)

**Comment by 88250** [comment]
麻烦详细描述问题。

**Comment by wbooooooo** [comment]
上下文，内容一样，部分高亮以后，高亮部分不会自动换行。变成另起一行了，粗体、行内代码块没这个问题。

**Comment by 88250** [comment]
请告诉我你是怎么操作的。

**Comment by 88250** [comment]
Q 群里已经沟通，这里就关闭了。

**Comment by Vanessa219** [comment]
已修复
