### ISSUE TITLE
插入链接拉取转换为卡片（书签）样式

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#1020]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
有时候希望以卡片的样式来显示引用的链接
特别是外链，例如引用了豆瓣，网易云，B站等的俩捏

### 描述最优的解决方案 Describe the optimal solution
类似豆列
类似语雀和Notion的样式
或者用自定义主题来实现

https://www.yuque.com/yuque/changelog/drocko
可以此链接中对于卡片模式的描述和效果
https://www.douban.com/doulist/44314945/
豆列的样式是这样

期望效果
![image](https://user-images.githubusercontent.com/42575324/104806855-6d862f00-5815-11eb-8132-47e9a02a0487.png)
![image](https://user-images.githubusercontent.com/42575324/104806870-8262c280-5815-11eb-92a9-de6428b8bff0.png)

**Comment by 88250** [comment]
你好，麻烦截图看下，谢谢。

**Comment by GlowBlur** [comment]
https://www.yuque.com/yuque/changelog/drocko
可以此链接中对于卡片模式的描述和效果

**Comment by GlowBlur** [comment]
https://www.douban.com/doulist/44314945/
豆列的样式是这样

**Comment by 88250** [comment]
书签目前已经有显示的地方了，需要打开这个设置：
![image](https://user-images.githubusercontent.com/873584/104264204-22db7e80-54c6-11eb-9043-76cf6c0fa230.png)

**Comment by GlowBlur** [comment]
不好意思，我没有把问题描述清查，是正文的笔记引用了外链时可以以一种书签的样式渲染

**Comment by GlowBlur** [comment]
![image](https://user-images.githubusercontent.com/42575324/104806855-6d862f00-5815-11eb-8132-47e9a02a0487.png)
![image](https://user-images.githubusercontent.com/42575324/104806870-8262c280-5815-11eb-92a9-de6428b8bff0.png)

**Comment by GlowBlur** [comment]
@88250 老铁看看是不是跟进下

**Comment by 88250** [comment]
依赖网络功能的暂时不考虑……因为预览卡片引入以后可能会有更新或者 404 等情况，这个有点复杂，现阶段不考虑了，谢谢。
