### ISSUE TITLE
闪卡复习第二轮的卡片数量不会刷新，仍然是第一轮的数量

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复习时，当例如第一轮的复习数量是100，在这一轮中点击重来的卡片有20张，那么第二轮的时候复习的数量是20张，但实际显示的数量还是100

那么是不是第二轮的时候应该显示的是第二轮应该复习的闪卡数量呢

### Expected result

能够正确显示当轮应该复习闪卡数量

### Version environment

```markdown
- Version: 2.12.3
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个暂时不调整了，谢谢。
