### ISSUE TITLE
I made a translation into Russian for myself

### ISSUE THREAD

**Issue by OlZin** [siyuan-note/siyuan#10209]
### In what scenarios do you need this feature?

I just wanted to get acquainted with your program

### Describe the optimal solution

Make localization into Russian

### Describe the candidate solution

- I made a translation into Russian for myself
- Added the translation file to the folder with the program "...\AppData\Local\Programs\SiYuan\resources\appearance\langs\ru_RU.json"
- On the Settings Appearance/Language selection the file is selected, the translation is correct
- But Notebooks in the Doc Tree don't work. The list does not expand, you cannot select notes
- I don't know how to fix it
- I just wanted to get acquainted with your program
- The translation file is available at the link https://disk.yandex.com/d/r-zEvR7vBxPwMQ

**Comment by 88250** [comment]
Hello, please submit a PR if it is convenient and we will continue to follow up on this issue, thank you.

**Comment by zxhd863943427** [comment]
I don't quite understand your question. Can you provide a screenshot?

**Comment by OlZin** [comment]
Bro,
- I translated the language pack from English into Russian,
- the interface now speaks Russian,
- the Doc Tree really doesn't work,
- I do not know why.
- 
https://github.com/siyuan-note/siyuan/assets/34469363/2dcba845-6629-4c40-87fa-6b87da29fc22

**Comment by zxhd863943427** [comment]
I see why: do you understand that documents in the Doc Tree are obviously not supposed to be renamed themselves? It is impossible for your translator to translate all the document names in the Doc Tree. If you need to display a translation of the help document, you need to delete the current help document and reopen it-if a Russian version of the help document is provided

**Comment by OlZin** [comment]
- Language pack with Russian language is working
    - a bug was fixed in 1121 line,
    - I have significantly improved the translation.
- Just copy it to the program folder at the specified path
    - `"...\AppData\Local\Programs\SiYuan\resources\appearance\langs\ru_RU.json"​`
- Notes for developers:
    - noticed that if the parameters, for example `"GoBack"​` begins with a capital `G`​, then the translation of the value does not work. You need to change it to `"goBack": "Вернуться назад"`​. (371 lines, and others).
    - if you change the localization to RU, there is no loading of Help from the Main Menu, it works in other languages. Please correct me, I don't know why.
- Thank you for your attention to my proposal.
- The language pack file with Russian language is attached to the message
[ru_RU.json](https://github.com/siyuan-note/siyuan/files/13977189/ru_RU.json)
