### ISSUE TITLE
数据库格子出现圆点时无法点击鼠标输入（键盘按键可以）

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

右下角这个小圈一旦出现，点击鼠标就没反应

![Y8{G0F)VTE49ZYJ$X $0006](https://github.com/siyuan-note/siyuan/assets/67137548/9d6f0a3a-0c3f-40a7-9de3-701445d4b3e0)

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by Jiangshuon** [comment]
另外补充下，这种情况下如果按空格键，数据库界面会跳动

**Comment by Jiangshuon** [comment]
所以最新版本数据库没办法使用了

**Comment by Vanessa219** [comment]
小圆点是用于拖拽填充数据的，出现的时候不要点击小圆点，除非是想要点击拖拽填充数据。我这里按空格是正常的，关闭插件使用默认主题试试。

https://github.com/siyuan-note/siyuan/assets/970828/84aedad8-682e-4b5c-8069-b2ed0a824694

**Comment by Jiangshuon** [comment]
Uploading 1705490088891.mp4…

**Comment by Jiangshuon** [comment]
https://github.com/siyuan-note/siyuan/assets/67137548/b8eae116-06c0-4e28-996f-5d057be8bd95

**Comment by Jiangshuon** [comment]
大佬能看到录屏吗？不知为啥我这录屏无法在线播放，应该可以下载看吧

![image](https://github.com/siyuan-note/siyuan/assets/67137548/bb754c77-1132-4244-9a72-36d4aa082a8c)  

已经关闭插件和主题了，反正就是单击、双击单元格没反应，光标在标题哪儿闪烁

**Comment by 88250** [comment]
我这里也重现不了，请看录屏：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/e8a82ea3-7990-4bba-a819-2879f684f868)


请确认使用默认主题（我看到样式还是不对劲）、关闭所有插件、代码片段再测试，或者在新的工作空间中测试。

**Comment by Jiangshuon** [comment]
大佬找到问题了，搜狗输入法会这样，百度输入法和微软输入法不会

**Comment by 88250** [comment]
我这里也是搜狗输入法……

**Comment by Jiangshuon** [comment]
那就奇怪了，我这搜狗是100%复现 ，不管了，我换输入法就行了

**Comment by 88250** [comment]
好的，暂时这样顶顶，幸苦了。

**Comment by 88250** [comment]
楼主，搜索输入法如果不是最新版的话请升级一下再帮忙测试看看。

![image](https://github.com/siyuan-note/siyuan/assets/873584/17a5ae92-690f-4733-9c73-45496527898b)

**Comment by 88250** [comment]
输入法上有做过什么设置吗？

**Comment by Jiangshuon** [comment]
只是设了个双拼

**Comment by 88250** [comment]
我这里切换到双拼也正常，看来是其他某个地方的问题。请试下打开开发者工具 Console 然后再测试看看是否有报错。

**Comment by Jiangshuon** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/67137548/5efdbb3a-e7e7-47f6-9849-f1e0e39f443c)

**Comment by 88250** [comment]
这个应该没有影响，是其他的报错。

**Comment by Jiangshuon** [comment]
那就没有报错了，我重新打开软件测试，没有报错
![image](https://github.com/siyuan-note/siyuan/assets/67137548/644fa7b4-bd01-49b1-9ad8-e42a47c12266)

**Comment by 88250** [comment]
收到。

**Comment by Vanessa219** [comment]
是要输入后单击才会么？我看 https://ld246.com/article/1705675165888  这个里面直接点击就不行了。

**Comment by Vanessa219** [comment]
我这里没办法重现，尝试着改了一下，还麻烦下个 dev 版本帮忙看看。非常感谢。

**Comment by Jiangshuon** [comment]
> 是要输入后单击才会么？我看 https://ld246.com/article/1705675165888 这个里面直接点击就不行了。

是的，直接点击就不行，和这个链接一样

**Comment by Jiangshuon** [comment]
> 我这里没办法重现，尝试着改了一下，还麻烦下个 dev 版本帮忙看看。非常感谢。

是在这里下吗，新版还没有打包吧

![image](https://github.com/siyuan-note/siyuan/assets/67137548/2b7ff872-6814-4c2e-aa49-b4e068d63a1f)

**Comment by 88250** [comment]
@Jiangshuon 稍后会打个 dev 包，请关注 releases，谢谢。

**Comment by 88250** [comment]
最新 dev 版已经发布，请帮忙测试，谢谢。

**Comment by Jiangshuon** [comment]
666 ，解决了！
