### ISSUE TITLE
Use ⌃0-9 instead of ⌥0-9 in macOS

### ISSUE THREAD

**Issue by OrNatosY** [siyuan-note/siyuan#10218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

macOS 客户端中文输入法下用 option + 5 快捷键打开日历之后输入文字时会额外输入一个 5

可以参考下图，我用 option + 5 快捷键进入日记界面，然后在一个空白的地方输入了 ceshi，输入法获得的输入为 5ceshi

![image](https://github.com/siyuan-note/siyuan/assets/43162204/173c49e2-397c-4e9a-b163-bdb9b50400a6)

### Expected result

输入法获得的输入希望为 ceshi

### Screenshot or screen recording presentation

![Uploading 5661705653731_.pic.jpg…]()

### Version environment

```markdown
- Version: 2.12.3
- Operating System: macOS
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13986508/siyuan.log)

**Comment by Vanessa219** [comment]
Mac 下拼音输入法 alt+数字再输入其他字母都会有这个问题，好像没有解决的方案。如果换为 ⌃+数字 可以接受么？

**Comment by OrNatosY** [comment]
> Mac 下拼音输入法 alt+数字再输入其他字母都会有这个问题，好像没有解决的方案。如果换为 ⌃+数字 可以接受么？

感谢回复，似乎是系统级的问题，我可以接受替换的
