### ISSUE TITLE
数据库新建行自动赋值多项列表

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如GIF所示：
![GIF 2024-1-18 21-30-52](https://github.com/siyuan-note/siyuan/assets/5708881/b0bef725-2479-4292-963e-18297f005978)

### Expected result

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个列如果设置了过滤的话会沿用上一行的值填充。
