### ISSUE TITLE
中文右双引号无法输入

### ISSUE THREAD

**Issue by xiaotoucai** [siyuan-note/siyuan#1021]
### 描述问题 Describe the problem

中文输入法的双引号只能显示前半部分
按两次书名号，无法显示单书名号（单书名号不是小于号）

### 期待的结果 Expected result

希望可以准确输入双引号和单书名号

### 截屏或录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/63988708/104253172-dafd2d00-54ae-11eb-98ad-da4b75a03063.mov

https://user-images.githubusercontent.com/63988708/104253178-ddf81d80-54ae-11eb-9d9c-8ab39af0dab8.mov

### 版本环境 Version environment

* 版本 Version：0.5.9
* 操作系统 Operating system：macOS10.15.5
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，请问你使用的输入法是什么？

**Comment by xiaotoucai** [comment]
> 你好，请问你使用的输入法是什么？

你好，我使用的是苹果自带的系统输入法🙏

**Comment by Vanessa219** [comment]
单书名号可以，但是右双引号确实不行。
![image](https://user-images.githubusercontent.com/970828/105171635-70f12180-5b59-11eb-9c93-1d436dee7141.png)

**Comment by Vanessa219** [comment]
好像输入法有点问题，现在在一般的输入框里面都打不出来了。我先尽力修一下吧

《《《《
