### ISSUE TITLE
默认不显示emoji，必须手动更换默认字体

### ISSUE THREAD

**Issue by codercplus** [siyuan-note/siyuan#10224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

全新安装思源笔记，主题为官方默认。然后插入几个emoji表情，此时页面能看到有占位，但表情没显示出来。
然后，去设置里，将字体由“默认”更改为：XXX UI Emoji，再回到文档，才显示正常。

### Expected result

字体为“默认”时，也应该可显示emoji。

### Screenshot or screen recording presentation

![Snipaste_2024-01-21_21-23-25](https://github.com/siyuan-note/siyuan/assets/63757163/ea042b37-2883-4bcc-8153-c457676493a2)
![Snipaste_2024-01-21_21-23-50](https://github.com/siyuan-note/siyuan/assets/63757163/94fb755c-6471-4630-83e2-8ca07b765c6c)

### Version environment

```markdown
- Version: v2.12.4-dev2
- Operating System: Win 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14001448/siyuan.log)

**Comment by Vanessa219** [comment]
默认主题中 --b3-font-family 这个变量里面已经包含了 Segoe UI Emoji，还麻烦设置为默认后打开开发者工具看一下最终使用的字体是什么？

**Comment by codercplus** [comment]
问题解决了。需要在集市里，额外找一款插件，叫什么emoji。安装完后，即使字体改回默认，笔记和对话框里的关于emoji也都能正常显示。

但我确实想说，emoji是个很“基础”的功能，原生就该默认支持。现在还得用户自己额外去装个插件才能显示，这操作就很反人性化。对普通人来说，发现问题后光寻找原因和解决办法就得耗费很多很多时间。

所以建议软件发布后就默认配置好、内置好一些高频的基础功能。默认就是开启并可用的状态。 不要“故意”给用户创造与困难相遇的机会。

**Comment by codercplus** [comment]
![Snipaste_2024-01-21_22-49-09](https://github.com/siyuan-note/siyuan/assets/63757163/3a34cc33-25fa-463e-990c-be6b791a8b92)
![Snipaste_2024-01-21_22-51-08](https://github.com/siyuan-note/siyuan/assets/63757163/bcb710ea-17d2-4db7-997b-25eaa3ec96d1)
恢复成默认主题，元素属性如上。


------------------------------
另外我发现问题的解决办法了。需要在集市里，额外找一款插件，叫什么emoji。安装完后，即使字体改回默认，笔记和对话框里的关于emoji也都能正常显示。

但我确实想说，emoji是个很“基础”的功能，原生就该默认支持。现在还得用户自己额外去装个插件才能显示，这个操作逻辑就很反人性化。建议官方改进一下。

**Comment by codercplus** [comment]
再补一张默认主题下，字体使用 UI emoji时的元素属性。
![Snipaste_2024-01-21_23-12-38](https://github.com/siyuan-note/siyuan/assets/63757163/cb64f7db-c00d-4d1a-89c0-2f4a6eaad1cb)

**Comment by codercplus** [comment]
![Snipaste_2024-01-21_23-24-31](https://github.com/siyuan-note/siyuan/assets/63757163/6fcf0522-7371-4978-ad7b-4db53f0ea33a)

**Comment by Vanessa219** [comment]
截图中可以看到默认是带有 `Segoe UI Emoji` 这个字体的，那个插件是帮你下载一个表情字体。我们是使用的系统默认的表情。是不是你电脑上下载过 "Apple Color Emoji", "Noto Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols" 这些损坏的表情字体？

<img width="369" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/60ac38eb-1833-40c2-bf3f-343407d2e670">

**Comment by codercplus** [comment]
> 截图中可以看到默认是带有 `Segoe UI Emoji` 这个字体的，那个插件是帮你下载一个表情字体。我们是使用的系统默认的表情。是不是你电脑上下载过 "Apple Color Emoji", "Noto Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols" 这些损坏的表情字体？
> 
> <img alt="image" width="369" src="https://private-user-images.githubusercontent.com/970828/298392907-60ac38eb-1833-40c2-bf3f-343407d2e670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDI1NDksIm5iZiI6MTcwNTkwMjI0OSwicGF0aCI6Ii85NzA4MjgvMjk4MzkyOTA3LTYwYWMzOGViLTE4MzMtNDBjMi1iZjNmLTM0MzQwN2QyZTY3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwNTQ0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTE1Mzk1YWNlMTQ3ODUyOGZiMzhiYzRhYWJkNzNhNmU0Y2QzMThmYzQ5M2ExOTNjMDU2MjA1OTlmMWYyZDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D-UlkP-O4tZhqRIMkSwxgLICJL7wiFQmgk73ZVHOWOA">

暂时解决了。删除了电脑中一个叫"Noto Color Emoji"的字体。
