### ISSUE TITLE
杀毒软件报错软件无法运行

### ISSUE THREAD

**Issue by marcusbai** [siyuan-note/siyuan#1022]
思源版本：siyuan-0.5.9-win.zip
安装方式：压缩包
症状：windows 安全中心提示发现危险，之后软件无法运行
![安全中心](https://user-images.githubusercontent.com/16847894/104258951-6da3c900-54bb-11eb-9eeb-13d3539fd0b0.png)
![软件错误](https://user-images.githubusercontent.com/16847894/104258955-6ed4f600-54bb-11eb-85bb-4a35e20d7364.png)
感谢

**Comment by 88250** [comment]
你好，请加到信任区里，谢谢。
