### ISSUE TITLE
ipad 连接键盘后输入法候选框颜色显示问题

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#10228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

深色主题下（所有的深色主题），ipad 连接蓝牙键盘后，输入法候选框的候选字背景高亮为白色，和字混在一起了，打开其他软件发现没有此问题

### Expected result

输入法候选框的候选字背景高亮为蓝色或其他
或者候选字呈黑色

### Screenshot or screen recording presentation

![004412566faeb2b454bcd5a515c03e4](https://github.com/siyuan-note/siyuan/assets/47842345/c5925ffe-f28c-4050-9863-bbd81eed3f8f)

### Version environment

```markdown
- Version: 
- Operating System: IOS
- Browser (if used):
```

### Log file

NA

**Comment by 88250** [comment]
抱歉，我们目前暂时没有办法改进这部分，后续请关注 https://github.com/siyuan-note/siyuan/issues/4238
