### ISSUE TITLE
让外观样式支持自定义

### ISSUE THREAD

**Issue by codercplus** [siyuan-note/siyuan#10226]
### In what scenarios do you need this feature?

写文档时，修改外观样式绝对是个基础、高频功能。不论高手、低手，都常用。但目前的外观设置有3个缺点。

1. 无法修改或自定义。改主题门槛太高、麻烦，另外虽说有款插件叫“配色方案”，但实际体验下来，bug太多，尤其在导出pdf时，输出效果很不稳定，常常发生外观错乱。都不如原生支持来得实在。
2. 操作低效。当前的外观只能分别设置背景色、字体色、粗细、字号等，如果我想要一个“加粗14px蓝色字灰色背景”，需要设置4次才能实现。无法将“一套”效果整体作为一个“样式”，点一下就完成。
3. 效果不稳定。之前施加的外观，换个主题，就完全变了样，所以说效果很不稳定。

如果能自己定义样式的话，就可以新建一个独立的样式名出来，这样就不会因更换主题而导致样式也随之更改、被覆盖。最主要，还是方便、高效，可以方便地获得自己想要的样式和效果。

![Snipaste_2024-01-22_16-25-38](https://github.com/siyuan-note/siyuan/assets/63757163/a3765ba4-4345-4978-8ccf-45c074c7cea5)

### Describe the optimal solution

如上图

**Comment by 88250** [comment]
你好，暂时不考虑了，感谢提议。
