### ISSUE TITLE
更新到 v2.12.3 后 webdav 同步到 alist 失败 已购买该功能

### ISSUE THREAD

**Issue by wanghao123456** [siyuan-note/siyuan#10220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源日志：
![image](https://github.com/siyuan-note/siyuan/assets/23393153/708707c8-e13f-4ff2-92fb-6f474f43e68e)
![image](https://github.com/siyuan-note/siyuan/assets/23393153/6ab77c67-a9e4-4c6e-ab98-ccfc3c3aaea2)

alist 日志：
[GIN] 2024/01/19 - 17:04:58 | 401 |     132.707µs |     192.168.1.8 | GET      "/dav/"
🔧[33mWARN🔧[0m[2024-01-19 17:04:58] failed get /aliyun/backup/siyuan/repo/lock-sync: object not found 
🔧[31mERRO🔧[0m[2024-01-19 17:04:58] GET /dav/backup/siyuan/repo/lock-sync object not found
github.com/alist-org/alist/v3/internal/op.Get
	github.com/alist-org/alist/v3/internal/op/fs.go:227
github.com/alist-org/alist/v3/internal/fs.get
	github.com/alist-org/alist/v3/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	github.com/alist-org/alist/v3/internal/fs/fs.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleGetHeadPost
	github.com/alist-org/alist/v3/server/webdav/webdav.go:225
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	github.com/alist-org/alist/v3/server/webdav/webdav.go:61
github.com/alist-org/alist/v3/server.ServeWebDAV
	github.com/alist-org/alist/v3/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	github.com/alist-org/alist/v3/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	github.com/alist-org/alist/v3/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
runtime.goexit
	runtime/asm_arm64.s:1197 
[GIN] 2024/01/19 - 17:04:58 | 404 |  254.452911ms |     192.168.1.8 | GET      "/dav/backup/siyuan/repo/lock-sync"
🔧[33mWARN🔧[0m[2024-01-19 17:04:58] failed get /aliyun/backup/siyuan/repo/lock-sync: object not found 
🔧[31mERRO🔧[0m[2024-01-19 17:04:58] GET /dav/backup/siyuan/repo/lock-sync object not found
github.com/alist-org/alist/v3/internal/op.Get
	github.com/alist-org/alist/v3/internal/op/fs.go:227
github.com/alist-org/alist/v3/internal/fs.get
	github.com/alist-org/alist/v3/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	github.com/alist-org/alist/v3/internal/fs/fs.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handleGetHeadPost
	github.com/alist-org/alist/v3/server/webdav/webdav.go:225
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	github.com/alist-org/alist/v3/server/webdav/webdav.go:61
github.com/alist-org/alist/v3/server.ServeWebDAV
	github.com/alist-org/alist/v3/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	github.com/alist-org/alist/v3/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	github.com/alist-org/alist/v3/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
runtime.goexit
	runtime/asm_arm64.s:1197 
[GIN] 2024/01/19 - 17:04:58 | 404 |    79.13033ms |     192.168.1.8 | GET      "/dav/backup/siyuan/repo/lock-sync"
🔧[33mWARN🔧[0m[2024-01-19 17:04:58] failed get /aliyun/backup/siyuan/repo/objects: object not found 
🔧[31mERRO🔧[0m[2024-01-19 17:04:58] PROPFIND /dav/backup/siyuan/repo/objects/ object not found
github.com/alist-org/alist/v3/internal/op.Get
	github.com/alist-org/alist/v3/internal/op/fs.go:227
github.com/alist-org/alist/v3/internal/fs.get
	github.com/alist-org/alist/v3/internal/fs/get.go:38
github.com/alist-org/alist/v3/internal/fs.Get
	github.com/alist-org/alist/v3/internal/fs/fs.go:36
github.com/alist-org/alist/v3/server/webdav.(*Handler).handlePropfind
	github.com/alist-org/alist/v3/server/webdav/webdav.go:612
github.com/alist-org/alist/v3/server/webdav.(*Handler).ServeHTTP
	github.com/alist-org/alist/v3/server/webdav/webdav.go:75
github.com/alist-org/alist/v3/server.ServeWebDAV
	github.com/alist-org/alist/v3/server/webdav.go:46
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server.WebDAVAuth
	github.com/alist-org/alist/v3/server/webdav.go:113
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	github.com/alist-org/alist/v3/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
runtime.goexit
	runtime/asm_arm64.s:1197 
[GIN] 2024/01/19 - 17:04:58 | 404 |  237.413366ms |     192.168.1.8 | PROPFIND  "/dav/backup/siyuan/repo/objects/"

🔧[31m2024/01/19 17:04:59 [Recovery] 2024/01/19 - 17:04:59 panic recovered:
runtime error: makeslice: cap out of range
runtime/slice.go:33 (0x45e7b7)
runtime/slice.go:100 (0x45e7a0)
github.com/alist-org/alist/v3/internal/stream/stream.go:100 (0xb308d3)
github.com/alist-org/alist/v3/drivers/aliyundrive_open/upload.go:246 (0x11e98db)
github.com/alist-org/alist/v3/drivers/aliyundrive_open/driver.go:196 (0x11e7783)
github.com/alist-org/alist/v3/internal/op/fs.go:543 (0x87153f)
github.com/alist-org/alist/v3/internal/fs/put.go:69 (0xcbdb83)
github.com/alist-org/alist/v3/internal/fs/fs.go:96 (0xcbbfbb)
github.com/alist-org/alist/v3/server/webdav/webdav.go:341 (0x150812b)
github.com/alist-org/alist/v3/server/webdav/webdav.go:65 (0x1505d73)
github.com/alist-org/alist/v3/server/webdav.go:46 (0x151106f)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x15119df)
github.com/alist-org/alist/v3/server/webdav.go:113 (0x15119c4)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x14a5f27)
github.com/alist-org/alist/v3/server/middlewares/check.go:14 (0x14a5f0c)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xcae4ef)
github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0xcae4d4)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xcad88f)
github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0xcad860)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xcac9c3)
github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0xcac6ec)
github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0xcac30f)
net/http/server.go:2938 (0x70695b)
net/http/server.go:2009 (0x702d57)
runtime/asm_arm64.s:1197 (0x47cfc3)
🔧[0m
[GIN] 2024/01/19 - 17:04:59 | 500 |   383.84368ms |     192.168.1.8 | PUT      "/dav/backup/siyuan/repo/lock-sync"

### Expected result

老版本无问题，更新到新版本后功能不可用。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/23393153/02571f13-adaf-4aae-ba1f-d8285536797f)
![image](https://github.com/siyuan-note/siyuan/assets/23393153/de971660-a79a-40e2-85ba-d59b27773d32)

### Version environment

```markdown
- Version: v2.12.3
- Operating System: linux
- Browser (if used): chorme
```

### Log file

![image](https://github.com/siyuan-note/siyuan/assets/23393153/7113ce47-ca9d-47fd-9ee7-792784bd81f2)

**Comment by 88250** [comment]
你好，从 alist 日志上看是因为 alist 内部发生了 panic，所以导致思源 WebDAV 客户端判断为服务不可用，请给 alist 项目反馈该问题，谢谢。

```
[31m2024/01/19 17:04:59 [Recovery] 2024/01/19 - 17:04:59 panic recovered:
runtime error: makeslice: cap out of range
runtime/slice.go:33 (0x45e7b7)
runtime/slice.go:100 (0x45e7a0)
github.com/alist-org/alist/v3/internal/stream/stream.go:100 (0xb308d3)
github.com/alist-org/alist/v3/drivers/aliyundrive_open/upload.go:246 (0x11e98db)
github.com/alist-org/alist/v3/drivers/aliyundrive_open/driver.go:196 (0x11e7783)
```
