### ISSUE TITLE
能否加个开关，关闭超过‘最大列出数量’的提示。

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10235]
### In what scenarios do you need this feature?

每次打开/悬浮涉及超过‘最大列出数量’的文件时到弹出一个提示，分散注意力。希望用户能控制以关闭此提示。

### Describe the optimal solution

配置里给个开关。谢谢！

**Comment by 88250** [comment]
将 设置 - 文档树 - 最大列出数量 调整大应该有用。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by IAliceBobI** [comment]
@88250 
1：我其实是故意调到100的，但里面超过了100。因为我这个文件夹是放一些概念类的引用。展示太多也没什么用。
2：每次都有一个提示，因该与我打开“始终定位打开的文档”有关。但我需要打开这个选项。

我也知道，不提示用户，会造成其他麻烦。

我先自己注释掉go里代码，自己用着，可能其他人也没这个需求。
