### ISSUE TITLE
Move dock plugin icon does not maintain its position

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

插件在Dock栏的位置无法保存，「移动到X侧X方」的操作无效，在下次打开思源笔记时会恢复默认的位置。

实际问题见：https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/issues/25

### Expected result

保存插件在Dock栏的位置，并在打开软件时正确加载。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/78434827/33b00acf-cb87-4fe3-a60d-1c320b337fc2)

### Version environment

```markdown
- Version: v2.12.4
- Operating System: Windows 10
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14027927/system-log.zip)

**Comment by Vanessa219** [comment]
这个应该是插件的问题，

**Comment by TCOTC** [comment]
重新加载界面就会有这个问题

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 目前插件添加的侧边栏加载的逻辑还有问题, 无论保存的界面布局如何, 相关的配置(侧边栏位置, 是否展开, 宽度等)在每次加载时都会被忽略, 导致实际上保存的侧边栏布局是无效的

**Comment by Vanessa219** [comment]
> @Vanessa219 目前插件添加的侧边栏加载的逻辑还有问题, 无论保存的界面布局如何, 相关的配置(侧边栏位置, 是否展开, 宽度等)在每次加载时都会被忽略, 导致实际上保存的侧边栏布局是无效的

最新代码还有问题？

**Comment by Zuoqiu-Yingyi** [comment]
> 最新代码还有问题？

目前看暂时没啥问题了

**Comment by winter60** [comment]
@Vanessa219  
![image](https://github.com/siyuan-note/siyuan/assets/23653326/75a82212-6881-4f21-bc45-87cf23c22072)
不知道是不是这个的问题。 开启后，经常重置布局。
![image](https://github.com/siyuan-note/siyuan/assets/23653326/819fa1a3-9c14-4333-910e-e5c85b4f7995)

**Comment by TCOTC** [comment]
> ![image](https://private-user-images.githubusercontent.com/23653326/303930385-75a82212-6881-4f21-bc45-87cf23c22072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NjgyNTcsIm5iZiI6MTcwNzY2Nzk1NywicGF0aCI6Ii8yMzY1MzMyNi8zMDM5MzAzODUtNzVhODIyMTItNjg4MS00ZjIxLWJjNDUtODdjZjIzYzIyMDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE2MTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZmVmMzY1MGU1MTU1YTUyM2ZkNmMxY2E1NjFkODg4NmM3OTdlNDNlYTZkODIxNWViZWQ1YmFhMDFhODk1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yShRWXpmvETjV7MzWfVSoq2KD3bkTi-HlSQgD5VezS8) 不知道是不是这个的问题。 开启后，经常重置布局。 ![image](https://private-user-images.githubusercontent.com/23653326/303930557-819fa1a3-9c14-4333-910e-e5c85b4f7995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NjgyNTcsIm5iZiI6MTcwNzY2Nzk1NywicGF0aCI6Ii8yMzY1MzMyNi8zMDM5MzA1NTctODE5ZmExYTMtOWMxNC00MzMzLTkxMGUtZTVjODViNGY3OTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE2MTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMWFhMTNjNTMzMzU2MTY5MDFkYjBjZGNkNDg3ZWZlZDI2NDFlYWViMDQ0MDY5ZDY5Yzk0ZTExZTNlZDFmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1-r6Hml21o-n1bSLOQaZLSs67p2EwCo2ONx4s51NQzk)

我没开，一直会重置

**Comment by Vanessa219** [comment]
@TCOTC 什么情况下会重置？

@winter60 我这里是正常的，是因为安装了什么插件么？

**Comment by winter60** [comment]
> @winter60 我这里是正常的，是因为安装了什么插件么？

文件资源管理器、代码编辑、收集箱这三个。

**Comment by TCOTC** [comment]
> @TCOTC 什么情况下会重置？

哦，我说的是 2.12.4 版本的时候，现在新版暂时还没遇到会重置的情况

**Comment by Vanessa219** [comment]
>文件资源管理器、代码编辑、收集箱这三个。
移除了还回重置么？

**Comment by winter60** [comment]
> 移除了还会重置么？

不会了

**Comment by Vanessa219** [comment]
@winter60 有具体的重现步骤么？

**Comment by winter60** [comment]
https://github.com/siyuan-note/siyuan/assets/23653326/fe5ea1a5-183d-4d1f-ae01-9b372da1bc61

@Vanessa219

**Comment by Vanessa219** [comment]
可以重现了，下个版本改进。多谢。
