### ISSUE TITLE
2.12.4当安装了集成编辑环境时，打开默认不为文件树

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#10239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

2.12.4当安装了集成编辑环境时，打开默认不为文件树，以前版本没有该问题
插件：https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor

### Expected result

当打开思源时，应该焦点在文件树

### Version environment

```markdown
- Version: 2.12.4
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
可能和这个 https://github.com/siyuan-note/siyuan/issues/10237 是一个问题，请等发布新版本（v2.12.5）后再试试。

我先关闭了，如果新版还有问题，麻烦跟帖反馈，谢谢。

**Comment by hackerhui** [comment]
@88250 2.12.5版本问题依旧，因此打开

**Comment by 88250** [comment]
“打开默认不为文件树 ”具体问题是？

**Comment by 88250** [comment]
“打开默认不为文件树 ”具体问题是？我这里安装插件后除了插件图标没显示需要整体刷新界面才能显示，其他好像正常。

**Comment by hackerhui** [comment]
@88250 具体步骤
第一步：安装这个插件
第二步：关闭思源
第三步：启动思源
可以看到默认焦点是在这个编辑器，正常情况下应该是在文件树
![image](https://github.com/siyuan-note/siyuan/assets/42575324/23478349-8ed0-499b-aa53-d4665f898702)

**Comment by 88250** [comment]
我这里测试，如果上次退出的时候焦点在哪个面板图标，下次启动后焦点就在那个面板图标了，这应该是预期行为。

**Comment by hackerhui** [comment]
@88250 退出时焦点在文件树，退出重新进就跑到编辑器了，是不是我把大纲移别的dock的关系？

**Comment by 88250** [comment]
我这里测试正常，请看操作录屏：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/6740c483-4e1e-405c-953b-a3429cbfab2f)

**Comment by 88250** [comment]
抱歉，上面那个录屏是 v2.12.4 的，我用 v2.12.5 重新录了一个，也是正常的：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/1c53a1d2-4c7e-44a2-b6c8-9679d4e13946)

**Comment by hackerhui** [comment]
@88250 可以了，需要重新再点下文档树，如果不去手动点下文档树，默认就会是编辑器，谢谢
