### ISSUE TITLE
挖空的位置有不同样式的文字会出现多个【…】样式

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/62794181/47c28b14-e7ca-4d85-9123-92d342450521)
![image](https://github.com/siyuan-note/siyuan/assets/62794181/1e94fc1f-1fe6-4b35-86ee-e3b3d5a4cacb)

### Expected result

如图 期望只有一个样式

### Version environment

```markdown
- Version: 2.12.4
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个目前没有办法了，因为编辑器中处理叠加元素的时候是平铺的，比如 mark 中加粗 strong 的情况这个 mark  就会被平铺为 3 个 mark，其中一个 mark 叠加 strong，所以最后在闪卡中就会显示多个 [...] 样式。
