### ISSUE TITLE
`openTab`能否提供一个不聚焦的选项？

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10244]
### In what scenarios do you need this feature?

openTab({ app: this.plugin.app, doc: { id }});
这个前端接口，能否提供一个不聚焦的选项？
类似 `siyuan://` 协议的效果。

### Describe the optimal solution

供一个不聚焦的选项

**Comment by Vanessa219** [comment]
action 传入 `cb-get-hl` 这个试试
<img width="1016" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/cba3cbf9-0c8c-47d9-bfba-3c4e8a70c7a4">

**Comment by Vanessa219** [comment]
这个会缩放并将光标定位
```
                      doc: {
                            action: ["cb-get-focus"],
                            zoomIn: true,
                            id: "20210428212840-8rqwn5o",
                        }
```

这个不会缩放并高亮（高亮需更新代码）
```
                       doc: {
                            action: ["cb-get-hl", "cb-get-context"],
                            id: "20210428212840-8rqwn5o",
                        }
```
