### ISSUE TITLE
能否暴露`reloadProtyle`给前端插件框架？

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10243]
### In what scenarios do you need this feature?

用途：比如调用刷新虚拟引用api后，我可以调用reloadProtyle。如果用reload()又影响太大。

### Describe the optimal solution

暴露`reloadProtyle`给前端插件框架

**Comment by Vanessa219** [comment]
可以直接使用 
<img width="486" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/eb61d7a8-8737-46a3-9537-a5e3e1401832">

**Comment by IAliceBobI** [comment]
@Vanessa219 用了，就是protyle.reload不是一个方法的报错。

**Comment by Vanessa219** [comment]
如下测试没有报错
```
this.protyleSlash = [{
      filter: ["insert emoji \u{1F60A}", "\u63D2\u5165\u8868\u60C5 \u{1F60A}", "crbqwx"],
      html: `<div class="b3-list-item__first"><span class="b3-list-item__text">${this.i18n.insertEmoji}</span><span class="b3-list-item__meta">\u{1F60A}</span></div>`,
      id: "insertEmoji",
      callback(protyle) {
        protyle.insert("\u{1F60A}");
        debugger;
        protyle.reload(false);
      }
    }];
```

**Comment by IAliceBobI** [comment]
@Vanessa219 

感谢您的耐心解答。protyleSlash、loaded-protyle事件、快捷键我都找到了。


还有一个不知道如何做，就是右键菜单。 eventBus.on("open-menu-content") 里如何触发reload.

**Comment by IAliceBobI** [comment]
@Vanessa219 

感谢您的耐心解答。protyleSlash、loaded-protyle事件、快捷键我都找到了。


还有一个不知道如何做，就是右键菜单。 eventBus.on("open-menu-content") 里如何触发reload.

**Comment by Vanessa219** [comment]
参数 details 中有 protyle。这个是每个编辑器一个，切换后就不好使了。
