### ISSUE TITLE
复制粘贴，或者剪切粘贴时，能够提供类似于Excel单元格那样的，按value粘贴，或者按公式粘贴（即整个cut出来的subgraph能够重构它们之间的link关系）

### ISSUE THREAD

**Issue by kiritocode** [siyuan-note/siyuan#1024]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

比如我在一个巨大的文档（比如日记）里乱七八糟的记录了很多东西。

```
# 事项1

第一段，巴拉巴拉巴拉， keyword1

第二段，巴拉巴拉巴拉，((block-id-of-第一段 `keyword1`))
```

日后，整理这些日记时，我想这个`事项1`整体剪切出来，放到一个新的文档中去。
但是，现在的版本不支持这点，现在版本的复制粘贴，相当于Excel里面那种”值粘贴“，第二行那个link是copy as-is的，
所以它指向的还是原来文档的那个块。如果是剪切情况，那个块都已经不存在了。或者仅仅是复制的时候，
虽然原有的块还存在，但也可能不是我的意图，

![image](https://user-images.githubusercontent.com/77135994/104264028-c710f580-54c5-11eb-9208-bdaf166144ce.png)

比如这个图，复制完了后，我希望是把图结构copy过去，而不是只是把这个link copy过去。

### 描述最优的解决方案 Describe the optimal solution

我自己感觉也是很tricky的功能；最接近的解决方案就是类似Excel里的复制粘贴功能了。

提供`paste as value`就是现在默认行为，link被copy as-is的。

提供`paste as auto formula`，相当于把一个子图完整的deep clone过来。里面的link如果指向子图外面，还是保持不动，如果时子图自己的边，那么要修改link，使得它有效。

### 描述候选解决方案 Describe the candidate solution

暂无

### 其他信息 Other information

暂无

**Comment by 88250** [comment]
你好，如果是标题块的话建议使用标题块和文档块转换功能，后期我们会提供跨文档的块移动支持，谢谢建议。

**Comment by kiritocode** [comment]
看了下几个相关的issue，这个确实比较难搞。

假设选中了一块区域，本质上是选中了一块 subgraph。  假设原来的大文档是 G , 选中的区域是 $G' \subset G$ 是子图，那么有三类边都要处理：

1. G-G' 指向 G' 的
2. G' 指向 G-G' 的
3. G‘ 内部的

# 剪切情况

G'到了一个新的文档，G' 里的所有块id都重新生成了，那么 (3) 的部分修正使得G' is consistent是没有太大异议的。
(2)就不能变，必须copy as-is，而（1）也是要修正的。

# Copy的情况

如果只是copy，那么用户的意图确实就不明了，这时实际是三块，记为 ：

- B = G - G'   是选中区域以外的部分
- G' 是选中的部分
- G'' = G'.clone()  是G'的copy

所以上面的（1，2，3）到底是要如何连接其实并没有well-defined.

# 建议

至少对于剪切的情况，按照上面建议修正应该是没问题的。不然剪切完了，不修正(1,3)的话，(1,3)就相当于都变成”野指针“了。

**Comment by 88250** [comment]
为了简单，我觉得还是通过移动来明确意图比较好，谢谢帮忙考虑。
