### ISSUE TITLE
Dock icon support drag

### ISSUE THREAD

**Issue by MoonBottle** [siyuan-note/siyuan#10247]
### In what scenarios do you need this feature?

like idea toolbar 
![recording](https://github.com/siyuan-note/siyuan/assets/12904505/69a62e19-96d4-4a2d-b44a-cba9a141d138)
![image](https://github.com/siyuan-note/siyuan/assets/12904505/b910b679-3b2b-44c3-97d8-3c776496606e)

### Describe the optimal solution

like idea toolbar

**Comment by TCOTC** [comment]
希望顶栏上的图标也可以拖动调整

**Comment by TCOTC** [comment]
主要是顶栏上一堆按钮，想自定义排序。

用 CSS 好像能实现，但要一个个按钮查 id ，写起来应该很麻烦，如果思源能支持排序就好了

**Comment by shuojie819** [comment]
希望可以像obsidian那样。
1. 单边（左边或右边）可以放多个功能栏，标签、文档树、书签……多个，上下高度拖拽调整。
2. 按上面的功能栏说法，每个功能栏可以放多个功能，标签、文档树、书签……多个。（都是可以自行拖拽调整的）
![图片](https://github.com/siyuan-note/siyuan/assets/72399630/060ed720-ca74-4f02-993c-fa91f5a35daf)

**Comment by Vanessa219** [comment]
> 希望可以像obsidian那样。

设计不同，这个可能没法一样，只能先支持拖拽。

**Comment by TCOTC** [comment]
@Vanessa219 还需要改进一点，比如将收集箱拖拽到书签上方的空白位置就应该可以放置了，不需要拖到书签的图标上：

[dock1.webm](https://github.com/siyuan-note/siyuan/assets/78434827/7077fb8b-e62a-4a23-91a0-6fd73fa381eb)

**Comment by TCOTC** [comment]
@Vanessa219 我发现我这里拖不动了
