### ISSUE TITLE
随手机日夜间模式换主题时，会自动回到主页面

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

例如在刷闪卡，这时候手机根据设置的时间转换日夜间模式 这时候会自动回到编辑器页面，手机上想复习特地文档内的卡太复杂，这样会导致重复一次麻烦的步骤，希望能够转换模式的时候不能退出当时的页面

### Expected result

例如在刷闪卡，这时候手机根据设置的时间转换日夜间模式 这时候会自动回到编辑器页面，手机上想复习特地文档内的卡太复杂，这样会导致重复一次麻烦的步骤，希望能够转换模式的时候不能退出当时的页面

### Version environment

```markdown
- Version: 2.12.4
- Operating System: 安卓
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
第三方主题的话是因为使用了 theme.js 所以需要整体刷新界面，这个没有其他办法。

theme.js 已经不推荐主题使用 https://github.com/siyuan-note/siyuan/issues/8178
