### ISSUE TITLE
Latex "="无法显示正常

### ISSUE THREAD

**Issue by ConanMusk** [siyuan-note/siyuan#10251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当我使用latex进行公式编辑时，如果时求和大括号，下标中的“=”显示为“-”
![image](https://github.com/siyuan-note/siyuan/assets/67884112/e9273359-dfdb-46a9-8408-d00e5c70d708)

``` latex
latex代码
L=\sum_{t=1}^T\gamma_t\left\|\mathcal{O}-\mathcal{B}-\mathcal{R}^{(t)}\right\|_F^2

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/67884112/141b30cb-6296-410f-8681-b8aa92bd7567)


### Screenshot or screen recording presentation

_No response_

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by WingDr** [comment]
这个大概是渲染的原因，你把字体放大一点就能看到等号正常渲染了。应该是KaTex的公式字体问题？
