### ISSUE TITLE
斜杠菜单支持根据使用频率自动排序

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10257]
### In what scenarios do you need this feature?

斜杠菜单支持根据使用频率自动排序
![image](https://github.com/siyuan-note/siyuan/assets/16383685/7d947cf7-7381-413c-b415-afec4c725848)

### Describe the optimal solution

斜杠菜单支持根据使用频率自动排序

**Comment by 88250** [comment]
不考虑了，请使用搜索自动补全。
