### ISSUE TITLE
复制块超链接（Markdown）快捷键功能异常

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#10259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/32903588/d8aa7540-fab9-4205-8ec1-f882608a3e63)
使用快捷键时，与使用鼠标去点击块菜单操作复制，粘贴后结果不一致
使用快捷键复制后的结果是异常的

### Expected result

修复

### Version environment

```markdown
- Version: 2.12.5
- Operating System: windows
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
帮助文档中这个块复制出来都是以下这个
<img width="743" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/b9cbb1c6-51a4-463b-8efa-b6b6cb14bc38">
```
[如果在 ``` 后面跟随语言名称，可以有语法高亮的效果哦，比如：](siyuan://blocks/20210104091228-zbx0a7k)
```

**Comment by TinkMingKing** [comment]
请对文档块进行尝试 @Vanessa219

**Comment by 88250** [comment]
我这里测试好像正常，请看操作录屏：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/dbbfc9cc-2054-48a8-b1be-fadf930ab92f)

**Comment by TinkMingKing** [comment]
> 我这里测试好像正常，请看操作录屏：
> 
> [issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/dbbfc9cc-2054-48a8-b1be-fadf930ab92f)
> 

从文档树操作试试呢

**Comment by 88250** [comment]
这个是编辑器快捷键，文档树上没有作用的，所以在编辑器中：

![image](https://github.com/siyuan-note/siyuan/assets/873584/a1f0017e-923b-4ed7-8b11-6e65550968f7)

但是在文档树上：

![image](https://github.com/siyuan-note/siyuan/assets/873584/6d23663c-784d-4f6f-b7d8-cbdaaff737d3)

**Comment by TinkMingKing** [comment]
@88250 问题是在文档树上有用，还会得到一个异常的结果

**Comment by 88250** [comment]
我这里测试焦点在文档树上时按快捷键，没有写入剪切板。

**Comment by TinkMingKing** [comment]
@88250 发现问题了，对内容为空的块使用后，粘贴会得到一个异常的结果

**Comment by 88250** [comment]
明白了，稍后我们改进一下，空块复制 Markdown 时默认使用 ID 来填充锚文本，即 `[20240127101305-tbm0r1t](siyuan://blocks/20240127101305-tbm0r1t)`
