### ISSUE TITLE
数字块多行公式渲染问题

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#10266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数字块多行公式渲染问题使用
\begin{align}
\end{align}
会在右边出现序号

### Expected result

测试公式
\begin{align}
F&=A\times\left(F/A,i,n\right)\times\left(1+i\right)\\
&=A\times\left\lbrack\left(F/A,i,n-1\right)+1\right\rbrack\\
&=A\times\left\lbrack\left(F/A,i,n+1\right)-1\right\rbrack
\end{align}

### Screenshot or screen recording presentation

问题
![image](https://github.com/siyuan-note/siyuan/assets/42575324/537e3510-71ea-41b5-a0a1-d13d177272fe)
预期
![image](https://github.com/siyuan-note/siyuan/assets/42575324/b212b409-8fa1-439b-a1f4-f9f158cef051)

### Version environment

```markdown
- Version: 2.12.5
- Operating System: 
- Browser (if used):
```

### Log file

nome

**Comment by 88250** [comment]
这个应该没有问题，KaTex 官网也是这样渲染的：

![image](https://github.com/siyuan-note/siyuan/assets/873584/c7b211b8-75ef-42ad-982a-ba5d77c96144)

**Comment by hackerhui** [comment]
@88250 原来是 Katex啊
要用
\begin{aligned}
\end{aligned}
就没有问题了，谢谢

**Comment by noenif** [comment]
> @88250 原来是 Katex啊 要用 \begin{aligned} \end{aligned} 就没有问题了，谢谢

![image](https://github.com/siyuan-note/siyuan/assets/25174520/1ffc93d9-9e0d-4eb6-bb2d-c30f3dfa37ed)
