### ISSUE TITLE
能否提供另外一种，在文档树中，定位文档的功能

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10267]
### In what scenarios do you need this feature?

希望一个快捷键，打开文档树+折叠文档树+定位当前文档。

这样有利于更快找到文档在树中的位置，还不被文档树中已经展开的文档干扰。

### Describe the optimal solution

提供一个快捷键。

**Comment by 88250** [comment]
这个暂时不考虑了，建议使用 Ctrl+F 来定位路径。
