### ISSUE TITLE
数据库勾选框能否添加css类或css变量，方便主题更改颜色增加区别

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10262]
### In what scenarios do you need this feature?

目前勾选框列完成和未完成都是一个颜色，能否提供css变量或添加css类，来更改默认的样色，以更好的区分勾选和未勾选状态
<img width="433" alt="Snipaste_2024-01-26_19-05-46" src="https://github.com/siyuan-note/siyuan/assets/60436214/08137eff-a1d8-48b0-a911-22b4fa11dcfd">

### Describe the optimal solution

提供css变量，分别设置勾选框列完成和未完成的svg颜色

### Describe the candidate solution

为勾选框列完成和未完成添加css类，方便区分

**Comment by Vanessa219** [comment]
"av__cell-check" ,"av__cell-uncheck"

**Comment by Achuan-2** [comment]
感谢！
