### ISSUE TITLE
pc端全屏刷卡时，弹出其他应用通知后，刷卡快捷键失效

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

需要点击一下闪卡的窗口才能继续使用快捷键刷卡，使用了其他的刷卡软件没有这种情况下

弹出应用通知的软件为滴答清单，其他的刷卡软件为anki

### Expected result

其他软件弹出通知后不影响闪卡刷卡

### Version environment

```markdown
- Version: 2.12.5
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
焦点不在应用中时无法使用快捷键的。
