### ISSUE TITLE
Add a Ref export mode `Anchor hash` for notebook Markdown exporting

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10265]
https://liuyun.io/article/1700915419894

**Comment by zxhd863943427** [comment]
能描述一下这个导出的效果吗

**Comment by 88250** [comment]
和 流云 上帖子描述差不多：

![image](https://github.com/siyuan-note/siyuan/assets/873584/376ac429-f8b2-43bd-b5ec-e27f7dfdae40)

![image](https://github.com/siyuan-note/siyuan/assets/873584/2925bd5d-e114-49fd-92f9-8e5074896b3b)

**Comment by zxhd863943427** [comment]
很不错！
