### ISSUE TITLE
在一个超级长的块中，在块中最下方粘贴文字会自动拉倒块的上部分。

### ISSUE THREAD

**Issue by Frank1003** [siyuan-note/siyuan#10272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在一个超级长的块中，在块中最下方粘贴文字会自动拉倒块的上部分。

### Expected result

文字在在哪粘贴就显示在哪，不会自动跳到块的最上部分

### Version environment

```markdown
- Version: v2.12.0
- Operating System: win10
- Browser (if used):
```

### Log file

I 2023/11/17 18:28:42 working.go:121: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/

**Comment by 88250** [comment]
你好，请升级到最新版后再测试看看，如果还能重现问题，麻烦录屏演示操作，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Frank1003** [comment]
升级后没有复现 。谢谢
