### ISSUE TITLE
The status bar color on Android is incorrect

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10278]
最新版移动端顶栏显示不正常（一直为黑色）

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

默认主题、关闭所有css情况下也一样

![26777b3569e9c6bb9a6933f9e6f0d39](https://github.com/siyuan-note/siyuan/assets/67137548/7330b649-40af-4fad-b499-092864299ede)

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
我这里测试 Android 版本正常：

![Screenshot_2024-01-31-09-50-06-450_org b3log siyu](https://github.com/siyuan-note/siyuan/assets/873584/dcbd506b-1d3c-4ba8-b139-dc0d0a8d362f)

**Comment by 88250** [comment]
老铁，试过重新安装吗？

**Comment by Jiangshuon** [comment]
没呢大佬，我等下周新版本试试，安卓重装太费事了

**Comment by QQQOrange** [comment]
> 我这里测试 Android 版本正常：
> 
> ![Screenshot_2024-01-31-09-50-06-450_org b3log siyu](https://private-user-images.githubusercontent.com/873584/301013028-dcbd506b-1d3c-4ba8-b139-dc0d0a8d362f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MTc3NzUsIm5iZiI6MTcwNjkxNzQ3NSwicGF0aCI6Ii84NzM1ODQvMzAxMDEzMDI4LWRjYmQ1MDZiLTFkM2MtNGJhOC1iMTM5LWRjMGQwYThkMzYyZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQyMzQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjUxZDBjYzc1MDEwMjU3YjdiYzBmZTg2NWNmODZiN2RjZDE3MThjYmFhYTk3N2ViMmFkNGUwY2NmZTQ1M2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._-dkHt2xvbZyBdISjemQX-_3GZjbg_pPaQdjmTcVvJM)

我也出现这种情况，默认主题的日间模式没问题，但是夜间模式的任务栏和主题色不一样，也是安卓

**Comment by QQQOrange** [comment]
> 老铁，试过重新安装吗？

第三方主题的日间模式任务栏也是和楼主说的一样

**Comment by QQQOrange** [comment]
> 我这里测试 Android 版本正常：
> 
> ![Screenshot_2024-01-31-09-50-06-450_org b3log siyu](https://github.com/siyuan-note/siyuan/assets/873584/dcbd506b-1d3c-4ba8-b139-dc0d0a8d362f)
> 

![Screenshot_20240203_074651.jpg](https://github.com/siyuan-note/siyuan/assets/62794181/423002ac-bf51-46ef-a6e9-7c0194e821d0)

![Screenshot_20240203_074707.jpg](https://github.com/siyuan-note/siyuan/assets/62794181/02bcfc2a-773f-4eed-8cc1-b9e42ce1ce04)

第一张是写味主题，第二张是默认主题。

**Comment by QQQOrange** [comment]
> 我这里测试 Android 版本正常：
> 
> ![Screenshot_2024-01-31-09-50-06-450_org b3log siyu](https://github.com/siyuan-note/siyuan/assets/873584/dcbd506b-1d3c-4ba8-b139-dc0d0a8d362f)
> 

![Screenshot_20240203_074920.jpg](https://github.com/siyuan-note/siyuan/assets/62794181/e35dc34d-ea8f-4cf7-ac3b-d993b6c3d2eb)

这是日间模式的第三方主题。

**Comment by 88250** [comment]
找到问题了，下个版本解决，谢谢。

**Comment by mustakshif** [comment]
v3.0.8 还是有第三方主题在亮色模式下状态栏变黑的情况，如使用pink-room主题的绿色配色方案后重新进入应用会复现：
![screenshot](https://github.com/siyuan-note/siyuan/assets/100056458/bf96b479-a98e-4412-af14-f2e15fbfac30)

状态栏的颜色是取自 --b3-theme-background 吗，我发现如果该 css 变量的值是 hex 颜色的话状态栏颜色就和背景色一致，如果是 rgb、hsl 等状态栏就是黑的

**Comment by 88250** [comment]
> 我发现如果该 css 变量的值是 hex 颜色的话状态栏颜色就和背景色一致，如果是 rgb、hsl 等状态栏就是黑的

有可能是这部分代码还有问题 https://github.com/siyuan-note/siyuan-android/blob/ef6e616bbf5e8b28ba2555ae24e0d2bec23fe4de/app/src/main/java/org/b3log/siyuan/JSAndroid.java#L162 

方便的话请试着帮忙排查，谢谢。

**Comment by mustakshif** [comment]
> > 我发现如果该 css 变量的值是 hex 颜色的话状态栏颜色就和背景色一致，如果是 rgb、hsl 等状态栏就是黑的
> 
> 有可能是这部分代码还有问题 https://github.com/siyuan-note/siyuan-android/blob/ef6e616bbf5e8b28ba2555ae24e0d2bec23fe4de/app/src/main/java/org/b3log/siyuan/JSAndroid.java#L162
> 
> 方便的话请试着帮忙排查，谢谢。

小白一枚，我没学过java和安卓开发，不太懂😂。

不过看代码应该是解决了rgb色彩的解析，但我测试了一下还是会变成默认的深灰色：
![rgb](https://github.com/siyuan-note/siyuan/assets/100056458/2119250b-0161-40b5-839e-29a9ad2fad8f)
```css
--b3-theme-background: rgb(245, 177, 177);
```

hsl颜色没有解析，所以也是默认：
![hsl](https://github.com/siyuan-note/siyuan/assets/100056458/d6174c99-6125-48cc-8766-2898c20d64af)
```css
--b3-theme-background: hsl(0, 77%, 83%);
```

hex颜色值能正常解析，可以跟随主题背景色：
![WechatIMG36](https://github.com/siyuan-note/siyuan/assets/100056458/5b8d442c-6f00-4100-91e3-f80a06522386)
```css
--b3-theme-background: #f5b2b2;
```

……其他色彩空间应该不能解析了。
https://github.com/siyuan-note/siyuan-android/blob/ef6e616bbf5e8b28ba2555ae24e0d2bec23fe4de/app/src/main/java/org/b3log/siyuan/JSAndroid.java#L187
这里，感觉简单的解决方式就是亮色模式的默认值设为白色，而深色模式时默认值为深灰，这样就不用考虑主题作者用什么色彩空间了

**Comment by 88250** [comment]
暂时用 hex 吧。
