### ISSUE TITLE
Markdown Import Option Missing

### ISSUE THREAD

**Issue by meichthys** [siyuan-note/siyuan#10276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The Markdown Import option seems to be missing on both Android & Web.

### Expected result

We should see the "Import > Markdown" option.

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/10717998/abde272f-a191-4c4b-82c9-5b625bec57b9)

### Version environment

```markdown
- Version: 2.12.6
- Operating System: Linux / Android
```

### Log file

Not sure how to provide this for android?

**Comment by 88250** [comment]
Hello, importing Markdown is only supported on the desktop.
