### ISSUE TITLE
右键添加到数据库，键值显示错误

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#10279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

键添加到“版本更新前，建立的数据库”，键值显示错误；版本更新后，新建的数据库，可以正常使用。

### Expected result

希望排查一下，建议文档也可以右键添加到数据库

### Screenshot or screen recording presentation

![F1OAL{J1Q6%TKLZAZ3SV5X6](https://github.com/siyuan-note/siyuan/assets/101880110/9bee94fc-37f3-4fec-990a-ecb0ca1b7383)

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
v2.12.6
```

### Log file

无

**Comment by 88250** [comment]
你好，我这里无法重现该问题，将新建的块添加到之前的数据库中，然后打开属性面板显示正常。

文档块后续会在文档标题块标菜单和文档树菜单上支持 添加到数据库 入口，谢谢。

![image](https://github.com/siyuan-note/siyuan/assets/873584/a0af99f2-318f-49be-a708-dbbd1ee07eca)

**Comment by 88250** [comment]
@tcmtom 从楼主截图看应该没有命名或者别名，否则块角标会显示：

![image](https://github.com/siyuan-note/siyuan/assets/873584/84f19634-c0c6-40fb-ba5f-bf1b09217cee)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
