### ISSUE TITLE
Crash after switching some community themes on iPad

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#10275]
ipad 如果因为主题的问题闪退后，就再也打不开

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Ipad下，在夜间模式下使用Asri主题，或者Rem craft主题的时候，思源有很大几率闪退，闪退之后就会再也打不开，点击图标之后一进入主界面就会立马闪退，只有卸载重装才能解决问题。

### Expected result

希望正常进入，或者有在外部安全启动的方法。
希望有安全启动的方案，即在长按图标后，选择安全启动，可以禁用主题启动，这样不会导致打不开而需要重装软件。

### Version environment

```markdown
- Version: 
- Operating System: IpadOS
- Browser (if used):
```

### Log file

NA

**Comment by 88250** [comment]
我们先找下问题，请问是否有稳定重现步骤？

**Comment by lisontowind** [comment]
有的，如果一开始ipad处于深色模式，思源界面在浅色模式，这个时候将深色的主题换成Asri或者Rem craft（这个时候如果自动切换深色模式大概率就会闪退），然后将主题设置为跟随系统或者深色模式，这个时候就会闪退，然后再也无法开启。

**Comment by 88250** [comment]
收到，稍后 @Vanessa219 试下在开发模拟器上能否重现。
