### ISSUE TITLE
想问一下，如何彻底从云端删除一个笔记本？

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#1027]
在本地客户端的这个地方点击了删除按钮，云端的该笔记本内容被清空，但是云端该笔记本还是存在，而且网页端的右键菜单没有删除选项：

![image](https://user-images.githubusercontent.com/32661922/104278902-51685200-54e4-11eb-88a3-1f5f8f360b9f.png)

![image](https://user-images.githubusercontent.com/32661922/104279020-8eccdf80-54e4-11eb-8ee5-eef22996fb64.png)

**Comment by deerainw** [comment]
先关闭了，等个解答...

**Comment by 88250** [comment]
点删除以后，云端空间应该就已经删掉了，如果还显示的话关闭网页，等 30s 后重新进入应该就看不到了。
