### ISSUE TITLE
插件相关的变更在数据快照中不进行展示

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10271]
### In what scenarios do you need this feature?

现在每次更新插件，插件相关的变更都会在数据快照中进行展示，希望可以屏蔽下不进行展示

### Describe the optimal solution

如上

**Comment by 88250** [comment]
目前暂时不考虑改变了，因为插件是数据的一部分，是纳入同步的，所以需要在快照中显示。
