### ISSUE TITLE
Unable to delete table block before database block

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10284]
如果表格后跟着数据库，无法删除表格

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

通过 块标里的删除、Esc+Backspace、Esc+Delete 都无效

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e616d78b-a69c-4799-ab0d-c944f929a495)

### Expected result

正常删除表格

### Version environment

```markdown
- Version: v2.12.6
- Operating System: Win 10
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14108573/system-log.zip)

**Comment by 88250** [comment]
我这里测试无法重现问题，请看操作录屏：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/3f85facc-a096-4bc7-8fff-eea1a63d9e88)

**Comment by TCOTC** [comment]
删除后关闭文档再打开，表格又会出现

**Comment by TCOTC** [comment]
好奇D大录屏显示快捷键用的是什么软件？

**Comment by 88250** [comment]
> 删除后关闭文档再打开，表格又会出现

确实如此，是个 bug。

> 好奇D大录屏显示快捷键用的是什么软件？

https://github.com/NickeManarin/ScreenToGif

**Comment by Vanessa219** [comment]
24ee5d14bebab8facc6bdf04f3ae3c47b5f3e10f
