### ISSUE TITLE
能增加代码块的备注功能吗？建议代码块借鉴flowus

### ISSUE THREAD

**Issue by JackeyLov5** [siyuan-note/siyuan#10287]
### In what scenarios do you need this feature?

高效写作

### Describe the optimal solution

 flowus已经实现该功能

### Describe the candidate solution

<img width="753" alt="image" src="https://github.com/siyuan-note/siyuan/assets/130417202/c60f8ca3-d3a6-4fd6-b6a0-a80ee5fcf521">

**Comment by 88250** [comment]
你好，这个不考虑支持了，感谢提议。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5662
