### ISSUE TITLE
Improve the activation prompt dialog box after downloading the plugin

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10285]
在关闭所有插件的情况下，新下载的插件仍能直接启用，但重启软件后就会禁用

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/78434827/aee542bb-59a5-4d3d-8518-7afa54ac24f5)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/aa65bfb0-7d9d-4095-ad4e-536df9172428)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8b3468ba-0230-4b35-9de0-0330d83c17f8)

不过重启后就禁用了

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/78434827/488528b4-50d9-4827-a2c5-849e564286a2)

### Version environment

```markdown
- Version: v2.12.6
- Operating System: Win 10
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14109266/system-log.zip)

**Comment by 88250** [comment]
感谢反馈，把弹出是否启用的对话框改为弹出“目前所有插件已经被置为禁用状态，后续可以在 [已下载 - 插件] 中进行启用、禁用或者卸载 ”。
