### ISSUE TITLE
Zoom in and Zoom out in read-only mode

### ISSUE THREAD

**Issue by AiurQIAN** [siyuan-note/siyuan#10289]
### In what scenarios do you need this feature?

有些时候会有 present 的需求， 可能会直接将某些笔记投在大屏幕上， 这时候原本的文字大小就不太合适， 如果能在 read-only 的情况下局部的放大缩小， 就能更好的展示.

### Describe the optimal solution

read-only 时可以通过 ctrl + 滚轮 进行局部放大

### Describe the candidate solution

可能一些其他方式能够进行放大

**Comment by 88250** [comment]
你好，我这里测试在只读模式下可以通过鼠标滚轮调整编辑器字体大小，请看操作录屏：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/717d7547-9a97-4cb4-899c-c9869a49ef8c)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
