### ISSUE TITLE
希望作者大大添加 表格列支持 有序列表、代码块等功能

### ISSUE THREAD

**Issue by qihensan** [siyuan-note/siyuan#10283]
### In what scenarios do you need this feature?

以表格组织信息会更加方便、美观

### Describe the optimal solution

类似于飞书文档的表格列功能

![image](https://github.com/siyuan-note/siyuan/assets/45647444/58b54048-b5ab-46ca-89ce-4733089ee07d)

**Comment by TCOTC** [comment]
如果现有的表格不能动了，那再做一个「高级表格」我觉得也不是不行

**Comment by 88250** [comment]
单元格内无法支持块级元素，抱歉抱歉。

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/19188
