### ISSUE TITLE
请求增强插件框架的回调`updateCards`，支持自动跳过闪卡的功能

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10293]
### In what scenarios do you need this feature?

通过 updateCards ，目前可以改变闪卡展示顺序，实现优先级，和低优先级闪卡有小概率优先展示的功能。目前已经很好用。感谢思源。

我还想实现`暂停/自动跳过`功能。

### Describe the optimal solution

我希望能够返回部分闪卡，其他没返回的闪卡都自动执行跳过功能。如下的示意代码：

```
    async updateCards(options: ICardData) {
        options.cards = options.cards.slice(0,3);
        return options;
    }
```

### Describe the candidate solution

或者用`options.skippedCards`来标示哪些是被跳过的。这样处理起来更方便。

```
    async updateCards(options: ICardData) {
        options.skippedCards = options.cards.slice(3); 
        return options;
    }
```

**Comment by Vanessa219** [comment]
对没有传过来卡片调用 `api/riff/skipReviewRiffCard` 这个接口可以满足么？

**Comment by IAliceBobI** [comment]
可以的。感谢大V！
