### ISSUE TITLE
钉住面板后dock附近的触发宽度希望能跟随主题修改

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#10295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这是个在我主题上的老问题了，因为我的主题是各种元素设计的紧凑主题会遇到这个问题。
但最近想着升级版本顺便兼容主题在于是还是将这个问题发出来了。
如视频，或下图在极限边距块标鼠标移动或拖动的时候就会触发弹出面板。
![image](https://github.com/siyuan-note/siyuan/assets/97731736/38dbb8c6-a500-4c75-bf4a-d50298aa8ba1)

### Expected result

我觉得这个触发宽度应该跟随主题修改后的宽度更好，不应该定死，不排除想要动停靠栏宽度的人（或者主题可以修改但是我没发现请告诉我修改方法）
触发宽度应该跟随主题

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/97731736/ebee3940-116c-4f8a-aee3-f6d48f9e4593

### Version environment

```markdown
- Version: v2.12.6
- Operating System: 
- Browser (if used):
```

### Log file

1

### More information

1

**Comment by Vanessa219** [comment]
> 大大，这个改动过后 Windows 上隐藏停靠栏后完全无法触发浮动面板了，请问是特性吗

不是，是个 bug，下个版本修复。
