### ISSUE TITLE
文档快的引用计数功能

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1029]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

如图，这是一个标题被引用的引用计数
![image](https://user-images.githubusercontent.com/46141646/104284925-cdb36300-54ed-11eb-8aa9-b3b793a50020.png)

但是，思源 目前 **并没有文档快的引用计数**
而文档快的引用计数又是**有必要的**
因为**文档块级别的引用频率较高**
比如ob只有文档快，**全是文档块的引用**

### 描述最优的解决方案 Describe the optimal solution

文档块的引用计数 无法显示在文档中
那么可以显示在**文件树 文件名 左方**，如图
![image](https://user-images.githubusercontent.com/46141646/104285009-ee7bb880-54ed-11eb-8553-9704951e446d.png)

**直接进行显示，而非移动鼠标到文件名才显示**
因为用户希望这个信息是暴露的，而不是“不知道这个文件被引用了没，每个都移过去看看”

**Comment by 88250** [comment]
感谢提议，请关注 https://github.com/siyuan-note/siyuan/issues/1005
