### ISSUE TITLE
集市添加一键更新

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10298]
### In what scenarios do you need this feature?

需要此按钮的原因在于，现在每次更新都需要滚动到相应插件或主题的位置后点击更新按钮，如果插件或者主题多的话，找需要更新的插件也是一个麻烦；或者同时有几个插件或主题更新的话，又要找，又要一个个的更新，也太麻烦且复杂。

要是有一个一键更新按钮，就不需要如此麻烦，能方便不少

### Describe the optimal solution

大概就是将需要更新的插件或主题集中显示，并且出现一键更新按钮，这样能直观的知道那些插件或主题需要更新，并且进行了一键操作

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/8390
