### ISSUE TITLE
Display flashcard style after exiting focus

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

快捷栏出现后会快速消失，这样就没办法正常编辑了。

另外希望“退出聚焦”后，闪卡黄色竖线能显示出来，不然在此界面制作新卡时都没啥反馈，都不知道制作成功没有

![7e959e6e7fda9dcfb30e8953f1e8a7c](https://github.com/siyuan-note/siyuan/assets/67137548/c3348c4d-d25d-478d-aa71-97b6f3d19f54)

![cbb57faf2c2d4b7ac8fa36e4799bb50](https://github.com/siyuan-note/siyuan/assets/67137548/41cdd863-4d6c-4a85-a2f5-0aa16dd0b0c1)

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by QQQOrange** [comment]
老哥 你这个制卡违反了信息最小化原则额

**Comment by Jiangshuon** [comment]
> 老哥 你这个制卡违反了信息最小化原则额

看情况吧，有些闪卡是要精确背诵的（需要最小化原则），有些闪卡只是为了大概知道，能回忆起大概意思即可，有些闪卡是让我知道有这么个东西存在，所以粗糙点无所谓的

**Comment by QQQOrange** [comment]
> > 老哥 你这个制卡违反了信息最小化原则额
> 
> 看情况吧，有些闪卡是要精确背诵的（需要最小化原则），有些闪卡只是为了大概知道，能回忆起大概意思即可，有些闪卡是让我知道有这么个东西存在，所以粗糙点无所谓的

嗷嗷嗷

**Comment by Vanessa219** [comment]
我这里不会消失，是进行了什么操作后消失了呢？

退出聚焦后显示闪卡标识这个可以改进。

**Comment by Jiangshuon** [comment]
@Vanessa219 好的，多谢大佬改进，快捷栏这个我又复现不了了，后面我注意下
