### ISSUE TITLE
Support flashcard set review mode

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10303]
能够选择先学新卡还是先复习旧卡

### In what scenarios do you need this feature?

闪卡分布在多个文档下的时候，挨个文档点间隔重复比较麻烦。
但是如果选全局复习的话，又会先推送新卡。如果新卡少的话，还不算麻烦。如果新卡多的话，就很难以复习到需要复习的卡。
希望能够在闪卡设置里面提供一个选项，也即是选择先复习旧卡还是先学习新卡

### Describe the optimal solution

闪卡分布在多个文档下的时候，挨个文档点间隔重复比较麻烦。
但是如果选全局复习的话，又会先推送新卡。如果新卡少的话，还不算麻烦。如果新卡多的话，就很难以复习到需要复习的卡。
希望能够在闪卡设置里面提供一个选项，也即是选择先复习旧卡还是先学习新卡

**Comment by 88250** [comment]
已经有这个设置项了，即 设置 - 闪卡 - 新卡上限/复习卡上限

**Comment by QQQOrange** [comment]
> 已经有这个设置项了，即 设置 - 闪卡 - 新卡上限/复习卡上限

你的意思是说我要想先复习再学习就需要把新卡数量调整为0再去。如果复习完想要学新卡再去设置里面调，对吗

**Comment by 88250** [comment]
是的。

**Comment by QQQOrange** [comment]
> 是的。

这样太麻烦了吧，在设置里面添加一个选择的按钮不行吗？

或者在复习完成的页面添加一个继续学习若干卡片的对话框也行啊

**Comment by 88250** [comment]
先保持 issue 打开状态吧，需要时间考虑下。

**Comment by QQQOrange** [comment]
> 先保持 issue 打开状态吧，需要时间考虑下，支持 3 中复习模式：
> 
> * 先新后新
> * 先旧后新
> * 新旧混合（目前的模式）

好呀好呀

**Comment by AvoidantPerDis** [comment]
有同样的需求
