### ISSUE TITLE
请求支持typst数学公式

### ISSUE THREAD

**Issue by yong900630** [siyuan-note/siyuan#10301]
### In what scenarios do you need this feature?

思源笔记目前支持latex的数学公式，但latex数学公式可读性差，书写不方便，已苦typst已久。
2023年出现了一款开源的typst软件（latex的竞争对手），其数学公式非常强大，具有良好是可读性。
开源链接地址https://github.com/typst/typst
typst数学公式的介绍https://typst.app/docs/reference/math/

### Describe the optimal solution

直接使用typst开源里头关于处理数学公式的代码，或者直接用typst进行编译数学公式即可。typst很小很小

**Comment by 88250** [comment]
目前已经集成了一些 KaTex 扩展，并且 KaTex 没有明显短板，所以不考虑支持 typst 了，感谢提议。

另外，应该可以通过挂件块实现，看社区是否有开发者贡献，谢谢。

**Comment by Clouder0** [comment]
Typst 目前依然不支持 HTML 输出，很遗憾短期内看不到类似 KaTeX 的方案。

Obsidian 社区有一个现成的插件 https://github.com/fenjalien/obsidian-typst ，用的是渲染成 svg 的方案，挺有意思，也是一个实现的路径。

走这个路线，通过挂件块渲染 Block 级别的 Math Equation 应该是没问题的。Inline 难度就会大很多。

**Comment by Roseleaves** [comment]
Typst 0.1.13开始支持HTML输出，基于此的Typst实现方案可以做了
