### ISSUE TITLE
数据库数字类型转文本类型时数字应该保留

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10302]
### In what scenarios do you need this feature?

数据库数字类型转文本类型时数字应该保留

### Describe the optimal solution

RT

**Comment by 88250** [comment]
不能做转换的，因为我们会保留之前类型的值，比如 文本列 转换 数字列 再转换 文本列，那么文本列的值还是之前的值，不会被 数字列 覆盖。
