### ISSUE TITLE
清除选中内容中的所有字体格式

### ISSUE THREAD

**Issue by lowwor** [siyuan-note/siyuan#1030]
1.多了字体颜色高亮后，希望增加清除格式功能，比如说一大段多处改了颜色，可以直接选中一大段，清除所有高亮。
2.增加默认颜色，就是选中后，下次直接点，不用再选颜色
![image](https://user-images.githubusercontent.com/5444033/104286863-985c4480-54f0-11eb-9f9b-1bfb3f1812a9.png)

**Comment by 88250** [comment]
清楚字体样式应该是已经有了，不过会保留加粗，这个我们后续看下是否能去掉。

![image](https://user-images.githubusercontent.com/873584/104287372-4f58c000-54f1-11eb-8e0e-0a02c910181c.png)

上一次选中颜色的保留后续改进，谢谢。

**Comment by lowwor** [comment]
现在这个清楚字体样式是只能选中有颜色的地方清除才有效，一个段落多处有颜色，选中整个段落，清除并不生效。

**Comment by Vanessa219** [comment]
颜色设置已添加到右键菜单中，格式刷功能就先不做了。
