### ISSUE TITLE
在外部程序打开外链 (块超链接) 的时候，在当前桌面弹出新窗口显示内容

### ISSUE THREAD

**Issue by VSpade7** [siyuan-note/siyuan#10300]
### In what scenarios do you need this feature?

希望增加一个开关，在外部程序点击打开外链(块超链接)的时候在当前桌面弹出新窗口并显示。

在其他软件通过外链联动思源，点击外链跳转到对应内容。
我会在 win 上开多个虚拟桌面，对应不同的事务，每个虚拟桌面里是对应事务的其他软件 + 一个打开多个相关文档的思源新窗口。
![image](https://github.com/siyuan-note/siyuan/assets/46594083/738405b5-6ba5-4b89-98b2-2651f70fb26b)

### Describe the optimal solution

目前的使用流程，需要：
1. 点击其他软件里的思源外链调整到主窗口对应的文档。
2. 将打开的对应文档挪到对应虚拟桌面上的思源新窗口。

功能的行为如下：
1. 点击外链检测当前桌面是否有思源的新窗口
2. 如果有的话，文档作为新页签打开
3. 如果没有，则新建窗口

实现上述功能后，思源可以作为其他软件的一种信息补充，提高联动效率。

如果检测当前桌面是否有思源新窗口有困难，直接在当前桌面新建窗口也能接受。

**Comment by UFDXD** [comment]
感觉不错，可以增强思源新窗口的功能性

**Comment by 88250** [comment]
加开关的话不太灵活，应该是超链接上加参数，比如 `siyuan://blocks/xxx?mode=1`？

**Comment by VSpade7** [comment]
> 加开关的话不太灵活，应该是超链接上加参数，比如 `siyuan://blocks/xxx?mode=1`？

也可以，这样感觉更好。在复制的那个菜单里增加一个选项？

**Comment by 88250** [comment]
等考虑一下，谢谢。

**Comment by suka233** [comment]
这种基于现有api，插件应该能做到，但是能官方原生支持的话也不错

**Comment by 88250** [comment]
试了下，虚拟桌面（任务视图）没有办法判断，所以只能新建窗口了，无法定位到已有窗口上。

**Comment by 88250** [comment]
@VSpade7 只能在思源所在的主窗口新建，无法在当前桌面新建。

我先关闭了，等 Electron 支持（ 不过那个 issue 8 年没有动静了，估计有点难）后再考虑，谢谢。
