### ISSUE TITLE
Language changes every time I open a newly created workspace.

### ISSUE THREAD

**Issue by kyota-iino** [siyuan-note/siyuan#10304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. I created an empty directory for the new workspace.
2. I created a new workspace by specifying that directory from the already open SiYuan menu.
3. The display language of the workspace opened in the new window will be randomized.

This problem occurs only on the first launch of a new workspace. Once an arbitrary language is set, it will be displayed in that language from the next startup.

### Expected result

If possible, I would like it to be displayed in the language I have set for my operating system. That is Japanese. But that is not supported by SiYuan. So, as a compromise, I would like it to be displayed in English.

### Version environment

```markdown
- Version: v2.12.6
- Operating System: Pop!_OS 22.04 LTS (Ubuntu 22.04 LTS Based)
- Browser (if used):
```

### Log file

```
2024-02-03 16:11:42 ui version [2.12.6], booting kernel [/tmp/.mount_siyuanR1Bbxo/resources/kernel/SiYuan-Kernel --port 34091 --wd /tmp/.mount_siyuanR1Bbxo/resources --workspace /home/myName/tmp/test]
```

### More information

Once the workspace is set to English, the argument `--lang en_US` is passed to SiYuan-Kernel at startup. However, when opening a completely new workspace, this argument is not specified. The value of the environment variable `$LANG` is `ja_JP.UTF-8`.

**Comment by 88250** [comment]
Hello, ja_JP is currently not supported, so the default language (en_US) will be used when creating a new workspace.
