### ISSUE TITLE
Editing features for multi-column layouts

### ISSUE THREAD

**Issue by kyota-iino** [siyuan-note/siyuan#10306]
### In what scenarios do you need this feature?

I like the ease of creating multi-columns in Notion, and I am having difficulty trying to create the same structure in SiYuan or extending the structure I have created.

For example, a layout like this
![Screenshot from 2024-02-04 03-35-26](https://github.com/siyuan-note/siyuan/assets/26924886/e6f3cda5-ea69-42a8-813f-bbfbdafbfafa)

I like this kind of layout because of its ease of listing information. In fact, Notion provides a slash command to create such a layout, so we can assume that there are a certain number of users who like it.

![Screenshot from 2024-02-04 03-51-00](https://github.com/siyuan-note/siyuan/assets/26924886/6bc46c1c-b414-4f54-a6e1-dfda2fcc0891)

Creating this structure in SiYuan currently seems difficult.
First, since there is no dedicated slash command, I try to create this structure by drag and drop. However, this is difficult.

https://github.com/siyuan-note/siyuan/assets/26924886/2a1ac3cf-cd22-4bc5-83a6-bf6a9b078d1e

Sorry if my poor manipulation has frustrated you.

It is especially complicated by the fact that if you try to create a new block from the Enter key in a column, the new column is created on the right side.

In this case, I tried a multi-column layout with headings and paragraphs, but other multi-column layouts with headings and lists have similar problems and are difficult to create.

### Describe the optimal solution

There are a couple of ideal solutions for me.

First, I would be happy to have a slash command for creating multi-column structures. That is, there should be slash commands like `2 columns` or `3 columns` as in Notion.

And within each column, the direction of creation of new blocks should be vertical. Currently, as shown earlier, pressing the Enter key creates a new column to the right of the current column. Originally, we want the new block to be on the bottom side without creating a new column.

And it would be even better if it were easier to create multi-column structures by drag-and-drop.

**Comment by 88250** [comment]
Hello, for a horizontal structure like heading-paragraph, you can do this:

[issue1.webm](https://github.com/siyuan-note/siyuan/assets/873584/65d41566-ad29-465a-9f10-7e1e17d5c4ff)

This can then be saved as a template for next time:

[issue2.webm](https://github.com/siyuan-note/siyuan/assets/873584/399357c2-5235-4407-b68d-02f867b6ed51)

**Comment by kyota-iino** [comment]
It seems that it already had all the features I was looking for.

Thanks to you, I now know how to use the superblock. This is a very useful feature !
Also, it is true that different people have different layout preferences, so I think the template feature is suitable to achieve this.

I look forward to taking notes from now on !
