### ISSUE TITLE
when siyuan tells me 'block not found', could it provide more information

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#10319]
### In what scenarios do you need this feature?

when siyuan tells me 'block not found' as below, could it provide more information, for example, which block is missing and block ID
![image](https://github.com/siyuan-note/siyuan/assets/5683995/93b84c54-3734-4d6b-ac1f-141be178cf6c)

I have checked siyuan.log, and there is nothing found

### Describe the optimal solution

provide more info.

**Comment by 88250** [comment]
Please open the developer tools Network and find out which request returned the error, thank you.

**Comment by 88250** [comment]
If there is no further information, I close this issue. Feel free to add more at any time, thank you.
