### ISSUE TITLE
标签支持拖拽形成层级

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10316]
### In what scenarios do you need this feature?

现在的标签层级要在文档中通过#1/2/3#的方式才能创建，太过麻烦，要是在标签页面能够拖拽标签来实现层级，那么标签的使用就不必拘泥于繁琐的操作方式，已创建的标签也能够方便的整理

### Describe the optimal solution

像拖拽文档一样拖拽标签设定标签层级

**Comment by 88250** [comment]
暂时不考虑拖拽了，目前可以使用右键 重命名 替代，谢谢。

**Comment by QQQOrange** [comment]
> 暂时不考虑拖拽了，目前可以使用右键 重命名 替代，谢谢。

那这和拖拽没啥本质区别啊，只是相对拖拽来说更麻烦了
