### ISSUE TITLE
The count is not refreshed after switching the doc tree during flashcard review

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10312]
闪卡复习页面，闪卡数量显示bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/62794181/c4bec43d-8dd2-4f4f-9288-3feb6abb35fe)
使用alt+0全局复习时，通过闪卡页面的漏斗图标选择某一文档复习的时候，数量显示的不是这个文档下闪卡数量，而是整个思源所有闪卡的数量

### Expected result

能够显示 准确数量

### Version environment

```markdown
- Version: 2.12.6
- Operating System: win11 安卓
- Browser (if used):edge
```

### Log file

无

**Comment by Vanessa219** [comment]
ddf3fc32cf7caf1b8200f94313f93a2d46094bec
