### ISSUE TITLE
标签页签上下文展现

### ISSUE THREAD

**Issue by fengchaobio** [siyuan-note/siyuan#1031]
如图，目前标签下的文件没有突出显示文件名 or 文件的标题。如果能突出显示文件名或者文件下的一级标题是否会好一些？
![image](https://user-images.githubusercontent.com/65841298/104292244-8c27b580-54f7-11eb-98d6-32dc8b13fe4d.png)

**Comment by 88250** [comment]
你好，这个和反链那块比较像 #295 我们先处理反链，标签页签暂时保持目前的样子，等反链处理以后再回过头来看这里，谢谢。
