### ISSUE TITLE
Improve floating window triggering method

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10317]
https://ld246.com/article/1707025017418

将 设置 - 编辑器 - 悬停出现浮窗 改为 浮窗触发方式，包括：

* 鼠标悬停 `0`
* Ctrl+鼠标悬停 `1`
* 不触发 `2`

**Comment by UFDXD** [comment]
@88250  增加第三种方式根本还是输入用到CTRL 和SHIFT 导致鼠标在引用上误触发。所以为什么不考虑改成 检测到输入编辑的时候（改动时间检测，比如两秒内时间或许用户可以自己定义） 无论鼠标悬浮还是 CTRL  都不触发悬浮窗呢，毕竟没有人是触手怪在键盘输入的时候，还用到鼠标吧。这里只是一个建议，具体能不能很好的实现没有深究

**Comment by 88250** [comment]
目前这个方式已经较为稳妥了，暂时不改变了，谢谢。
