### ISSUE TITLE
无法显示文档编辑界面

### ISSUE THREAD

**Issue by xiaotoucai** [siyuan-note/siyuan#1032]
### 描述问题 Describe the problem

无法显示文档编辑界面

### 期待的结果 Expected result
正确显示

### 截屏或录屏演示 Screenshot or screen recording presentation
https://user-images.githubusercontent.com/63988708/104294074-b7130900-54f9-11eb-8680-059996c41b18.mov

### 版本环境 Version environment

* 版本 Version：0.5.9
* 操作系统 Operating system：macOS10.15.5
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log
I 2021/01/12 17:14:03 main.go:122: kernel [v0.5.9] is booting, runtime mode is [prod], working directory is [/Applications/SiYuan.app/Contents/Resources], temp directory is [/var/folders/7x/s2jktl1x07g1j0t1ggrjx0c40000gn/T/siyuan], read only [false]
I 2021/01/12 17:14:03 lang.go:67: initialized languages
D 2021/01/12 17:14:03 conf.go:89: loaded conf [/Users/chenliang/.siyuan/conf.json]
I 2021/01/12 17:14:03 conf.go:179: local serve path [http://192.168.31.174:6806]
I 2021/01/12 17:14:03 conf.go:183: initialized conf
I 2021/01/12 17:14:03 main.go:186: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/12 17:14:03 webdav.go:37: initialized WebDAV server
I 2021/01/12 17:14:03 box.go:362: indexing [13] trees, cpus [8]
D 2021/01/12 17:14:04 box.go:397: indexed box [http://127.0.0.1:6806/siyuan/siyuan/_posts/]
I 2021/01/12 17:14:04 box.go:362: indexing [3] trees, cpus [8]
D 2021/01/12 17:14:04 box.go:397: indexed box [http://127.0.0.1:6806/siyuan/1610344677162/硕士论文修改/]
I 2021/01/12 17:14:04 box.go:362: indexing [38] trees, cpus [8]
D 2021/01/12 17:14:04 box.go:397: indexed box [http://127.0.0.1:6806/siyuan/1610344677162/思源笔记用户指南/]
I 2021/01/12 17:14:04 box.go:362: indexing [1177] trees, cpus [8]
I 2021/01/12 17:14:05 box.go:374: indexed [100] docs
I 2021/01/12 17:14:05 box.go:374: indexed [200] docs
I 2021/01/12 17:14:05 box.go:374: indexed [300] docs
I 2021/01/12 17:14:05 box.go:374: indexed [400] docs
I 2021/01/12 17:14:05 box.go:374: indexed [500] docs
I 2021/01/12 17:14:06 box.go:374: indexed [600] docs
I 2021/01/12 17:14:06 box.go:374: indexed [700] docs
I 2021/01/12 17:14:06 box.go:374: indexed [800] docs
I 2021/01/12 17:14:06 box.go:374: indexed [900] docs
I 2021/01/12 17:14:06 box.go:374: indexed [1000] docs
I 2021/01/12 17:14:07 box.go:374: indexed [1100] docs
I 2021/01/12 17:14:07 box.go:389: indexed [100] refs
I 2021/01/12 17:14:07 box.go:389: indexed [200] refs
I 2021/01/12 17:14:07 box.go:389: indexed [300] refs
I 2021/01/12 17:14:07 box.go:389: indexed [400] refs
I 2021/01/12 17:14:07 box.go:389: indexed [500] refs
I 2021/01/12 17:14:07 box.go:389: indexed [600] refs
I 2021/01/12 17:14:07 box.go:389: indexed [700] refs
I 2021/01/12 17:14:07 box.go:389: indexed [800] refs
I 2021/01/12 17:14:07 box.go:389: indexed [900] refs
I 2021/01/12 17:14:07 box.go:389: indexed [1000] refs
I 2021/01/12 17:14:07 box.go:389: indexed [1100] refs
D 2021/01/12 17:14:07 box.go:397: indexed box [http://127.0.0.1:6806/siyuan/1610344677162/2020-12-15/]
I 2021/01/12 17:14:07 box.go:362: indexing [11] trees, cpus [8]
D 2021/01/12 17:14:07 box.go:397: indexed box [http://127.0.0.1:6806/siyuan/1610344677162/社会资本/]
I 2021/01/12 17:14:07 conf.go:300: initialized box
I 2021/01/12 17:14:08 repo.go:39: initialized git repo

**Comment by 88250** [comment]
请打开开发者工具 
![image](https://user-images.githubusercontent.com/873584/104295599-a368a200-54fb-11eb-9b6f-488d75143484.png) 

看下 Console 里是否有报错，谢谢。

**Comment by xiaotoucai** [comment]
<img width="1428" alt="截屏2021-01-12 下午5 44 37" src="https://user-images.githubusercontent.com/63988708/104297480-e3c91f80-54fd-11eb-92cb-7c1702e7ada7.png">
谢谢🙏

**Comment by 88250** [comment]
看上去是因为内核进程挂了，麻烦重启时观察一下系统监视器中 kernel-darwin 进程的内存占用情况。

**Comment by xiaotoucai** [comment]
<img width="771" alt="截屏2021-01-12 下午6 52 44" src="https://user-images.githubusercontent.com/63988708/104305223-61455d80-5507-11eb-9237-bd22240cd8ca.png">

**Comment by 88250** [comment]
系统开了 VPN 之类的网络代理程序吗？

**Comment by xiaotoucai** [comment]
> 系统开了 VPN 之类的网络代理程序吗？

开了，请问要关闭吗？

**Comment by xiaotoucai** [comment]
> 系统开了 VPN 之类的网络代理程序吗？

关了就能用了。感谢🙏

**Comment by 88250** [comment]
可以把代理程序配置一下，不要代理 6806 和 6807 这两个端口。

祝使用愉快 :)
