### ISSUE TITLE
Upgrade KaTex v0.16.9

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#10321]
a math rendering issue: when using sum, the equal symbol is not very clear

### In what scenarios do you need this feature?

It looks like below, among the two horizontal lines in the equals sign, the lower one is not very clear.

![image](https://github.com/siyuan-note/siyuan/assets/5683995/a6419164-721f-4c52-b63a-0b66801869f7)

### Describe the optimal solution

make it clear

**Comment by 88250** [comment]
Fixed in aa6e044cc5e17aea44702bb6ca16e1eb0f5984b2

**Comment by zhoutaosheng** [comment]
@88250 The issue occurs again in version 3.0.3

![image](https://github.com/siyuan-note/siyuan/assets/5683995/7fba7ef7-6b08-4321-98f4-43bc2668b4fd)

![image](https://github.com/siyuan-note/siyuan/assets/5683995/d54c4145-feff-4638-b93f-3c2e658e86d3)

**Comment by 88250** [comment]
@Vanessa219 帮忙看一下

**Comment by Vanessa219** [comment]
@88250 Mac 上是正常的，由于 https://github.com/siyuan-note/siyuan/issues/10346 将字体大小移除。需要在 Windows 上找一个合适字体的大小。

**Comment by 88250** [comment]
@zhoutaosheng 尝试了一下，在 Windows 上可以将 KaTex 字体大小设置为 1.36em：

![image](https://github.com/siyuan-note/siyuan/assets/873584/d0113a9a-fd91-4364-aa43-17b57421b799)

但是这会带来 https://github.com/siyuan-note/siyuan/issues/10346 问题，所以我们不做调整了，如果需要请尝试自定义 CSS 代码片段。
