### ISSUE TITLE
Data sync may cause data loss on Android 14

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10323]
https://github.com/siyuan-note/siyuan/issues/10205#issuecomment-1928838726

**Comment by AvoidantPerDis** [comment]
补充一下，应该跟小米的焕新存储没关系，我丢失文件的那天没有触发这个

**Comment by 88250** [comment]
@AvoidantPerDis 麻烦发封邮件给我 845765@qq.com 我发一个刚刚打包的 apk 给你帮忙测试一下。

**Comment by AvoidantPerDis** [comment]
3090253564@qq.com

**Comment by 88250** [comment]
@hihaojie

**Comment by hihaojie** [comment]
hihaojie@163.com

**Comment by 88250** [comment]
均已发送，结果麻烦两位回复 issue，不要回复邮件，谢谢。

**Comment by AvoidantPerDis** [comment]
具体怎么测试，这个触发方式我也没搞懂

**Comment by 88250** [comment]
开着 app 不要退出，大概每隔 10 分钟会进行一次索引校验，校验过程中如果报错了就可能会有问题，类似之前贴过的日志：

![image](https://github.com/siyuan-note/siyuan/assets/873584/5ff2b2d1-6956-4a26-bdb2-4d34dc08fd43)

**Comment by 88250** [comment]
还是得观察具体的数据是否丢失



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 6, 2024 14:56 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Data sync may cause data loss on Android 14(Issue #10323)




 
等校验索引完发日志是吗？

**Comment by AvoidantPerDis** [comment]
目前同步好像没问题

**Comment by hihaojie** [comment]
安装新APP后，我这里已复现
![image](https://github.com/siyuan-note/siyuan/assets/25772523/ed6eb987-c49d-4af1-9ee0-c5eb9cd8ad07)

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14175880/system-log.zip)

为了提高复现概率，我安装后将历史生成间隔改为了“1分钟”，下面是丢失的文件快照：
![image](https://github.com/siyuan-note/siyuan/assets/25772523/c5b3d1a1-dd40-4baf-9a4c-aec66c67e533)

在此期间，未进行过清理后台、清理数据等操作

**Comment by hihaojie** [comment]
> 安装新APP后，我这里已复现 ![image](https://private-user-images.githubusercontent.com/25772523/302532704-ed6eb987-c49d-4af1-9ee0-c5eb9cd8ad07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDM4MjksIm5iZiI6MTcwNzIwMzUyOSwicGF0aCI6Ii8yNTc3MjUyMy8zMDI1MzI3MDQtZWQ2ZWI5ODctYzQ5ZC00YWYxLTllZTAtYzVlYjljZDhhZDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA3MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1OGZhMTU5N2UxMmNlNzRmZWIwY2E1YjQ1OTRmODIyZTgyZGZjY2Y1NzczODQ4NDZhMjg2ZjhhN2E2ZTVlOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zPr3ZLgvUwaCMhJyzf0hmR1Tw9oDwU7aSsLA9DhZLqU)
> 
> [system-log.zip](https://github.com/siyuan-note/siyuan/files/14175880/system-log.zip)
> 
> 为了提高复现概率，我安装后将历史生成间隔改为了“1分钟”，下面是丢失的文件快照： ![image](https://private-user-images.githubusercontent.com/25772523/302533191-c5b3d1a1-dd40-4baf-9a4c-aec66c67e533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDM4MjksIm5iZiI6MTcwNzIwMzUyOSwicGF0aCI6Ii8yNTc3MjUyMy8zMDI1MzMxOTEtYzViM2QxYTEtZGQ0MC00YmFmLTlhNGMtYWVjNjZjNjdlNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA3MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkN2FmOTA5N2RlZWI5ZjJiMmI3ZDkwOTIyZjlhOWJhMmJhMmM0MzE5MzczNDE3ZWYzYWRjZjU3NWFjZGExNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c5P_Sw0uh1RujfpEJlCJio-s6CWkobIZ37DpB2gOD2E)
> 
> 在此期间，未进行过清理后台、清理数据等操作

不好意思，这好像是安装之前的，时间太近了，我没意识到
