### ISSUE TITLE
PDF annotation supports setting associated block ID list

### ISSUE THREAD

**Issue by CSMsamuel** [siyuan-note/siyuan#10327]
希望高亮的文本可以聚焦到多个块或者一个超级块

### In what scenarios do you need this feature?

![image.png](https://b3logfile.com/file/2024/02/image-jz7XQ2h.png)

如图所示，我需要在pdf上高亮并做一个注释，但这个注释只能聚焦到一个内容块。这导致了我无法使用行间公式，而如果我需要备注更复杂的内容则无法完成。

![image.png](https://b3logfile.com/file/2024/02/image-gHV9fGB.png)

![image.png](https://b3logfile.com/file/2024/02/image-KIKiO6q.png)

如果我在聚焦的窗口中打字，再次聚焦依然不能成功

![image.png](https://b3logfile.com/file/2024/02/image-l0AtWbd.png)

合并成超级块也是不行的

### 方案一

高亮的文本可以聚焦到多个块或者一个超级块，这样高亮文本的浮动窗口才更能发挥其意义。

### 方案二

高亮文本的注释附着在pdf上，且能够批量导出。

![image.png](https://b3logfile.com/file/2024/02/image-QnKleNk.png)

**Comment by 88250** [comment]
嗯，是个好主意。对 PDF 中的标注添加一个绑定 ID 的列表，这样悬浮时就不调用 `getRefIDsByFileAnnotationID` 了，而是直接用设置的 IDs 查询，
