### ISSUE TITLE
添加摘录型闪卡

### ISSUE THREAD

**Issue by edward-kyle** [siyuan-note/siyuan#10325]
### In what scenarios do you need this feature?

> 在supermemo的渐进阅读中，阅读一篇文章的一部分后，会对其中的部分文字处理为「摘录卡片」或者说「摘录闪卡」。
之后可以选择继续阅读其他文章，或者开始刷闪卡。
这种「摘录卡片」在间隔重复时，会被记忆算法推送到用户面前（就像其他普通的闪卡那样）。但是，「摘录闪卡」应当是没有挖空的，只有摘录后的句子。
当「摘录卡片」被推送到用户面前时，可以对「摘录卡片」里的句子进行进一步的加工处理（例如，添加上下文线索，缩短或加长文本，改进措辞，把一个摘录卡片制作为多张挖空闪卡，等等）。
上述的「进一步的加工处理」也应当是渐进地做这样的小工作，也就是在间隔重复中遇到「摘录闪卡」和「普通闪卡」（普通闪卡应当也是可以在刷闪卡的时候进行编辑的）
也就是说，不仅要在阅读时渐进，在知识的后续加工和表述中也要渐进。
在摘录片段、生成填空卡片和编辑它们方面的工作都应该是渐进的。在每一次复习中，只对学习材料做必要的工作。

在上面的流程中，siyuan唯一缺少的就是「摘录」这一个动作。

目前的siyuan只能直接在块中标记，制作出「挖空闪卡」，却不能制作「摘录闪卡」。

### Describe the optimal solution

> 在「闪卡增强」插件中，解决方法(在「渐进学习」插件中也有类似的解决办法)如下：
使用alt+q对文章内容进行标记（不同于alt+d的标记），之后在文章下会生成一个包含「摘录闪卡」子文档。之后，在这个子文档中，进一步加工处理为挖空闪卡。

希望上述的alt+q的「摘录标记」可以在siyuan本体中实现。

### Other information

希望「摘录闪卡」可以和issue里已有的搁置闪卡、暂停闪卡等功能相结合。

**Comment by edward-kyle** [comment]
其实还有一个不太成熟的建议。

文档树窗口是笔记库中所有笔记、知识的结构呈现。

希望闪卡也可以有自己的「文档树窗口」，让所有的闪卡按照树状结构呈现。

「闪卡文档树」的树状结构是非常重要的，它决定着阅读材料的学习，以及今后的复习。
树形结构将帮助你组织知识 ，方便检索和可视化。

但这就意味着要单独存储阅读材料和制作出的闪卡。

**Comment by suka233** [comment]
文档也能制成闪卡的，看我图的操作：
![image](https://github.com/siyuan-note/siyuan/assets/43712875/f0a65772-891a-4635-a0ea-0f93e84261f6)
以下是动图：
![recording](https://github.com/siyuan-note/siyuan/assets/43712875/8cc9ef64-eac5-4100-9251-cc369effaed4)

**Comment by edward-kyle** [comment]
原来可以不挖空做闪卡吗？我还以为只能做挖空闪卡。

打扰D大了，感谢回复。

**Comment by edward-kyle** [comment]
不过闪卡是否需要单独的文档树，我还是持保留意见。

后续整理一下思路后再提吧。
