### ISSUE TITLE
updateCards returns the completion page when the card is 0

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10320]
### In what scenarios do you need this feature?

目前数量不准确。希望重新统计。或者简单显示插件拦截的数量也行。

另外一个问题是：如果`updateCards`一个卡都没返回，目前是空白页面+错误的数量统计。

在一个卡都没返回的情况下，希望直接展示全部复习完的那个页面。

**Comment by Vanessa219** [comment]
是移除后返回的数量么？这个可能需要自己减去移除的卡片数字。

卡片返回为空会进行以下判断的，要怎么重现空白页？
<img width="608" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/22a10500-edcb-449c-971b-07502b3a79c6">

**Comment by IAliceBobI** [comment]
@Vanessa219 

**数量**

我修改过数量，但页面没变化。

**空白页**

复现也简单:

```
    async updateCards(options: ICardData) {
        options.cards = [];
        return options;
    }
```

**Comment by Vanessa219** [comment]
数字不起作用应该是 https://github.com/siyuan-note/siyuan/issues/10312 这个问题。空白页可重现。

**Comment by IAliceBobI** [comment]
@Vanessa219 还有一个问题：

alt+0在2.12.7没问题，但 openTab()中打开闪卡，回调参数为null.   

async updateCards(options: ICardData) ，options一直是null
