### ISSUE TITLE
移动端闪退（只发现一次）

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

是上个版本，2.12.16版本。我瞎猜有可能和windows的杀毒有关，所以还是提一下，兴许能发现原因。

我电脑2.12.16版本出现内核丢失后，重装2.12.15版本一直没出问题，好像2.12.15版本抵抗力更强。

![e2160ab44ecad04b421b1f1ff38012f](https://github.com/siyuan-note/siyuan/assets/67137548/bd992e91-a7ab-4e4c-9e79-76672089418f)

### Expected result

无

### Version environment

```markdown
- Version: 2.12.16
- Operating System: 
- Browser (if used):
```

### Log file

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f91ed0a u0 org.b3log.siyuan/.KeepLiveService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2074)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8056)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14182881/system-log.zip)

**Comment by Jiangshuon** [comment]
进行的操作就是思源长期挂在后台（移动端pc端均如此）

**Comment by 88250** [comment]
和最近 Microsoft Defender 报毒的问题没有关联。

闪退报错 android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): 这个问题我查了一下暂时没有找到原因，不排除是系统或者 Android 自身的问题，麻烦后续留意稳定重现步骤，多谢。

**Comment by 88250** [comment]
这样，我加个 try catch 日志，看看后续能否记录到，感谢反馈。
