### ISSUE TITLE
Flagged as virus

### ISSUE THREAD

**Issue by fahadalisarwar1** [siyuan-note/siyuan#10338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

After update to the new version microsoft is blocking the application labelling it as a virus 
DETECTED: Trojan:Win32/Wacatac.B!ml
unable to use the app

### Expected result

app to work propoerly

### Version environment

```markdown
- Version: 2.12.7
- Operating System: Windows 11 
- Browser (if used):
```

### Log file

no logs

**Comment by 88250** [comment]
Hello, please try to update the virus database and then scan again. I tested Windows Defender 1.403.3364.0 here and no longer falsely reported virus trojans.

**Comment by eulores** [comment]
Latest Windows Defender 1.403.3380.0 continues to mark this as a trojan.
Also, if you submit the kernel file to virustotal.com, you'll see 3 engines flagging this as trojan.

Please keep this issue open for some days, so it is easier to find by other people.

**Comment by lpartan** [comment]
win 10, up to date, SiYuan kernel v2.12.7 quarantined by Defender 1.403.3385.0

**Comment by eulores** [comment]
Latest Windows Defender (1.403.3522.0) no longer flags SiYuan kernel v2.12.7 as a trojan or virus. So you might want to consider closing this issue as completed.

**Comment by ericma15** [comment]
好的，我加白了
