### ISSUE TITLE
Add internal kernel API `/api/attr/batchSetBlockAttrs`

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10337]
请求提供 `/api/attr/setBlockAttrs` 接口的批量版本

### In what scenarios do you need this feature?

请求提供 `/api/attr/setBlockAttrs` 接口的批量版本。

由于写接口串行化了，执行上千个改属性请求比较慢。望能提供一个批量接口。

用户经常操作大量闪卡的属性，所以提高写入性能的需求比较多。

`setBlockAttrs( [id] ,  attrs)`

或者

`setBlockAttrs( [ {id, attrs} ] ) `

或者

`setBlockAttrs( [ {id, attrs} ], defaultAttrs ) ` 可以通用一点。没传`attrs`就用`defaultAttrs`

**Comment by QQQOrange** [comment]
支持支持

**Comment by AvoidantPerDis** [comment]
支持

**Comment by 88250** [comment]
接口：`/api/attr/batchSetBlockAttrs`
参数：

```json
{
    "blockAttrs": [
        {
            "id": "20240211165506-f9nzfkv",
            "attrs": {
                "custom-foo1": "bar1"
            }
        },
        {
            "id": "20240211165630-h83esse",
            "attrs": {
                "custom-foo2": "bar2"
            }
        }
    ]
}
```
