### ISSUE TITLE
2.12.7被win自带安全中心报木马！

### ISSUE THREAD

**Issue by chenyuyou** [siyuan-note/siyuan#10335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源笔记报木马，window自带的安全程序
![image](https://github.com/siyuan-note/siyuan/assets/7900395/4e2b219c-9f8b-4452-8006-c9c2ba60ee59)

### Expected result

报木马后，思源直接挂了。

### Version environment

```markdown
- Version: 2.12.7
- Operating System: win11
- Browser (if used):
```

### Log file

没有

**Comment by lhp0906** [comment]
![2222](https://github.com/siyuan-note/siyuan/assets/12708681/9cfbe4bb-25f0-466e-8c98-550ad74df9d9)
一样的问题，昨天更新的，今天直接报木马，这是什么操作？！！！

**Comment by 88250** [comment]
是误报，加信任列表/排除项吧，感谢反馈。

**Comment by 88250** [comment]
请升级病毒库后再检测看看，我这里升级病毒库后 1.403.3364.0 已经不再误报。

**Comment by 88250** [comment]
好像还是会有杀毒引擎误报，后续请关注 https://github.com/siyuan-note/siyuan/issues/10338
