### ISSUE TITLE
希望大纲页添加折叠全部打开或者全部折叠的按钮

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#1033]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

当折叠打开太多了，期望一键全部关闭。
寻找内容时，期望一键全部打开，帮忙快速定位到内容处。

### 描述最优的解决方案 Describe the optimal solution

添加两个按钮，一个全部打开，一个全部折叠。

**Comment by 88250** [comment]
你好，请关注 #564
