### ISSUE TITLE
Unable to search and replace `-`

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10334]
搜索替换失效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

搜索-，将其替换为~，失效
### Expected result

能够替换
[0 第二章 个人总结.sy.zip](https://github.com/siyuan-note/siyuan/files/14188575/0.sy.zip)

### Version environment

```markdown
- Version: 2.12.7
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
原因是这个数据类型不是思源内置的数据类型，不建议自行修改行级/块级元素类型，否则可能会有不可预知的问题。

![image](https://github.com/siyuan-note/siyuan/assets/873584/084a9dde-42d3-4a4f-a137-5d6a8e8e78f2)
