### ISSUE TITLE
Add shortcut keys for flashcard review

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10333]
添加新的左手刷卡快捷键

### In what scenarios do you need this feature?

右手刷卡的体验非常棒，手掌不需要张开很多，并且撤回按键点击非常方便。
但是左右的刷卡却不是这样，因为触发按键是1234，手掌需要打开的幅度大不少，也累不少，再加上撤回按键是p，导致左手不能方便的按撤回。

### Describe the optimal solution

增加新的刷卡按键以适配左手，例如使用asdf对应1234的按钮，q对于p的按钮，这样左手也能有很好的刷卡体验。
当然最好是增加而不是替换，相信原来的刷卡方式也保留了一定的受众。

**Comment by 88250** [comment]
考虑增加 asdf、跳过 x，上一个 q

**Comment by QQQOrange** [comment]
> 考虑增加 asdf、跳过 x，上一个 q

好呀好呀！！
