### ISSUE TITLE
Improve formula font size

### ISSUE THREAD

**Issue by lindahua** [siyuan-note/siyuan#10346]
行内公式字体大小不协调

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

行内公式的字体过大，导致和同一行的普通文本很不协调。如下图所示：

<img width="394" alt="Screenshot 2024-02-11 at 07 56 44" src="https://github.com/siyuan-note/siyuan/assets/1900250/0602505e-ea3c-49a5-b838-c09a722f4a68">

这个问题应该是近期update的版本才开始出现的。

### Expected result

希望把行内公式字体调到相对协调的状态。

### Version environment

```markdown
- Version: 2.12.7
- Operating System: macOS
- Browser (if used):
```

### Log file

Not related

**Comment by 88250** [comment]
Ref:

* https://github.com/siyuan-note/siyuan/issues/10251
* https://github.com/siyuan-note/siyuan/issues/10321
