### ISSUE TITLE
ios经常会出现一个不要惊慌的弹窗

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

简单说，在思源保持几分钟后台再进入的时候就会弹出，如果思源能够在后台刷新应该能解决此问题。

### Expected result

解决此问题

### Version environment

```markdown
- Version: 2.12.7
- Operating System: ios
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个目前没有办法解决，因为 iOS 端挂后台或者切换应用后连接会断开，只能手动重连。

**Comment by QQQOrange** [comment]
> 这个目前没有办法解决，因为 iOS 端挂后台或者切换应用后连接会断开，只能手动重连。

有啊，我看了下，思源在ios设置里面没有后台app刷新那个按钮，要是有的这个按钮点击的话应该就行了
