### ISSUE TITLE
ios端导入密匙同步会失败，密匙没问题

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

ios端第一次同步，密匙没问题

### Expected result

能够同步

### Version environment

```markdown
- Version: 2.12.7
- Operating System: ios
- Browser (if used):
```

### Log file

无

**Comment by QQQOrange** [comment]
重建一个云端目录能解决，但不知道这是否是bug，毕竟安卓端可以正常同步

**Comment by 88250** [comment]
应该是因为密钥不正确，这部分代码多端都是一样的，没有差别。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by QQQOrange** [comment]
> 应该是因为密钥不正确，这部分代码多端都是一样的，没有差别。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

不是的 密匙是没问题的，我用电脑和其他手机都导出了密匙，用的是收集箱功能发到新手机上在同步的，还是用了密码生成密匙，也不行。后来建立新云端目录后，用同样的方式生成密匙后才成功的

**Comment by 88250** [comment]
如果使用新的云端目录可以正常的话，说明是之前的云端目录数据已经有不正确密钥加密的数据了。
