### ISSUE TITLE
Improve `window.destroyTheme` when switching dark and light in the same theme

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10341]
目前发现一个 `window.destroyTheme` 机制的 bug，在同一个主题下的亮暗色切换时稳定触发，分两种情况：

1. 完全重载；
2. 仅刷新，但是主题的 `theme.js` 不会再执行，并且 `theme.css` 的 `:root{}` 中的声明会被默认主题覆盖。

两种情况交替出现，如果亮切暗时情况1，则暗切亮时情况2，或相反。

默认主题下是正常的

_Originally posted by @mustakshif in https://github.com/siyuan-note/siyuan/issues/8178#issuecomment-1931698783_

**Comment by mustakshif** [comment]
> `theme.css` 的 `:root{}` 中的声明会被默认主题覆盖

V大，最新版的这个问题似乎还没解决。同一主题的亮暗色切换一次后复现，以 odyssey 主题为例：

![compare](https://github.com/siyuan-note/siyuan/assets/100056458/80e4f0dd-a497-4599-b113-bf0941862a72)

也测试了 tsundoku 主题，也有这种情况

**Comment by Vanessa219** [comment]
odyssey， Dark+ 和 Savor 这几个我试过了，是正常的，不正常的表现是？

odyssey 暗色主题需要看 appearance/themes/Odyssey/style/topbar/ocean.css 这个，会被这个重置。

**Comment by mustakshif** [comment]
这些主题不明显，因为他们的全局变量要么是后加载的，要么在body下，但是root中与默认主题重合的变量是会被覆盖的。odyssey是theme.css中的字体相关变量会被默认主题覆盖，颜色相关变量由配套的css覆盖，正常情况下应该是odyssey的字体相关变量不会被默认覆盖才对。

那麻烦V大把亮暗色模式下的主题都设为 tsundoku，然后切换一次亮暗色模式呢，这个主题可以明显看到root下的声明在切换一次亮暗模式后被默认主题覆盖

**Comment by Vanessa219** [comment]
@mustakshif 多谢，下个版本继续修改。
