### ISSUE TITLE
Supports some shortcut keys on the mobile

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

第一次使用就发现用不了，换了两个键盘都不行

但是可以正常的编辑器打字

### Expected result

第一次使用就发现用不了，换了两个键盘都不行

但是可以正常的编辑器打字

### Version environment

```markdown
- Version: 2.12.7
- Operating System: 安卓
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你指的是 Android 伺服，然后桌面端浏览器上使用吗？

**Comment by QQQOrange** [comment]
> 你指的是 Android 伺服，然后桌面端浏览器上使用吗？

就是单纯的用手机，没有用伺服

**Comment by 88250** [comment]
移动端不支持快捷键的……伺服的话应该支持。

我关闭了，感谢反馈。

**Comment by QQQOrange** [comment]
> 移动端不支持快捷键的……伺服的话应该支持。
> 
> 我关闭了，感谢反馈。

为啥不支持啊，要是安卓平板咋整呢

**Comment by 88250** [comment]
平板端应该是支持的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月10日(周六) 中午11:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 移动端不能用外接键盘刷卡 (Issue #10342)




  
移动端不支持快捷键的……伺服的话应该支持。
 
我关闭了，感谢反馈。
  
为啥不支持啊，要是安卓平板咋整呢

**Comment by QQQOrange** [comment]
> 平板端应该是支持的。
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2024年2月10日(周六) 中午11:03
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.***&gt;;"State ***@***.***&gt;;
> 主题: Re: [siyuan-note/siyuan] 移动端不能用外接键盘刷卡 (Issue #10342)
> 
> 
> 
> 
>   
> 移动端不支持快捷键的……伺服的话应该支持。
>  
> 我关闭了，感谢反馈。
>   
> 为啥不支持啊，要是安卓平板咋整呢
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好家伙

**Comment by luo-chuan** [comment]
如果是刻意为之，建议解除限制

**Comment by 88250** [comment]
等有空研究一下 @Vanessa219

**Comment by Vanessa219** [comment]
移动端目前是支持编辑器快捷键的，插件的可以进行统一添加，但全局的由于功能的差异只能根据实际情况进行部分添加。

<img width="330" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/e1c326a3-d932-484c-952c-30c919e01d68">

**Comment by Vanessa219** [comment]
先支持 alt1-7 和 add to database，其余的在 https://github.com/siyuan-note/siyuan/issues/11133  中进行支持。
