### ISSUE TITLE
移动端app

### ISSUE THREAD

**Issue by clark-cui** [siyuan-note/siyuan#1034]
我看了项目计划，没有看到移动端app的计划。请问是否不打算做移动端app呢？

**Comment by 88250** [comment]
思源的移动端目前是基于浏览器的方案，已经基本可用。原生 APP 暂时没有计划，谢谢。

**Comment by ugenehan** [comment]
也就是说手机端无法离线使用？

**Comment by 88250** [comment]
@ugenehan 目前是的，需要联网才能用。
