### ISSUE TITLE
ios端伺服默认提供的链接不能使用，使用第二个链接才能使用

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

希望默认第一个链接就能使用，而不是第二个，而且值得一提的是默认的提供的链接和win端提供的一样，也就是说输入默认链接并且win端在后台的话会直接进入win端的伺服

### Expected result

希望解决

### Version environment

```markdown
- Version: 2.12.7
- Operating System: ios
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
127.0.0.1 的地址是本地环回地址，只能在本地使用，后面的地址是网卡（虚拟网卡）地址，无法判断到底是否能用，所以只能这样了，感谢反馈。
