### ISSUE TITLE
Support custom AI request User-Agent header

### ISSUE THREAD

**Issue by fengailin** [siyuan-note/siyuan#10351]
AI功能修改请求头

### In what scenarios do you need this feature?

![图片](https://github.com/siyuan-note/siyuan/assets/91138941/6871f49c-0369-4d9b-8535-e22a9ca5de23)
思源笔记AI功能的默认请求头容易触发部分网站的cloudflare防御
![图片](https://github.com/siyuan-note/siyuan/assets/91138941/b1aebca3-ed63-4531-abfd-6bc1ef86209f)

希望能修改成主流浏览器的请求头

### Describe the optimal solution

希望能修改成主流浏览器的请求头，比如
![图片](https://github.com/siyuan-note/siyuan/assets/91138941/6a80095f-b7c3-4e13-bba4-debec1b72bd3)

**Comment by 88250** [comment]
下个版本支持在 设置 - AI - User-Agent 中进行配置，感谢提议。
