### ISSUE TITLE
自定义功能菜单

### ISSUE THREAD

**Issue by Xiaobaishushu25** [siyuan-note/siyuan#10350]
### In what scenarios do you need this feature?

思源笔记是否支持功能菜单常驻显示？就像大部分富文本编辑器那样，在编辑区上面一个bar，目前是否只能使用/（或其他快捷键）唤出功能菜单？
并且目前的功能菜单对我来说放在上面的都是不常用的，常用的要按下/朝下翻才能找到。

### Describe the optimal solution

能否支持将自定义常用的功能放到一个常驻的bar中提高效率。
是否可以自定义功能菜单的item呢。

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。
