### ISSUE TITLE
添加更多云同步方式

### ISSUE THREAD

**Issue by xyfx666** [siyuan-note/siyuan#10354]
### In what scenarios do you need this feature?

云同步的时候

### Describe the optimal solution

兼容百度网盘，阿里网盘，OneDrive等网盘

**Comment by 88250** [comment]
百度网盘应该是没有办法，因为没有接口。

其他两个网盘应该可以通过其他软件提供 WebDAV 接口，由于精力有限，暂时不考虑直接支持了。

建议还是使用 S3 存储服务，性能高且更稳定，感谢反馈。
