### ISSUE TITLE
Support custom AI models

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10355]
https://ld246.com/article/1707290836413

**Comment by zdevc** [comment]
如何配置自定义模型？哪里有说明么？

**Comment by 88250** [comment]
@zdevc https://platform.openai.com/docs/models/overview

**Comment by zdevc** [comment]
D大，能否先支持一家国内厂商的 AI，比如智谱清言、讯飞星火、文心一言等？虽然不如 OpenAI，但是毕竟更容易在国内网络环境下获得，可以满足很多用户需要

**Comment by 88250** [comment]
@zdevc 请关注：

* https://github.com/siyuan-note/siyuan/issues/9261
* https://github.com/siyuan-note/siyuan/issues/9024
