### ISSUE TITLE
反链面包屑可以滚动

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#10353]
### In what scenarios do you need this feature?

在其他编辑区域太长的面包屑可以滚动，而且默认定位，但是在反链面包屑中没有发现。在反链面包屑中面包屑太长就只显示开头，如果是特意设计如此如可以一览看到根级面包屑，那么希望可以优化一下让它可以滚动

### Describe the optimal solution

可以不定位，但可以滚动

### Other information

https://github.com/siyuan-note/siyuan/assets/97731736/aef4b1cc-23fe-4925-a56b-a08c1ac0a0ae

**Comment by Vanessa219** [comment]
按住 shift 就可以了。
