### ISSUE TITLE
文档闪卡与全局闪卡卡片数量同步

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10356]
### In what scenarios do you need this feature?

在针对文档进行复习时，每个文档的复习卡与新卡数量都是独立的，与全局不同步
在多个文档进行复习时会造成过多复习。
不清楚是故意这么设计，还是没有做打通

### Describe the optimal solution

共用一套计数

### Describe the candidate solution

提供切换选项？

**Comment by 88250** [comment]
请参考用户指南 闪卡 章节：

![image](https://github.com/siyuan-note/siyuan/assets/873584/6d7efeb5-8b76-4a66-8a25-d5b27ea6d961)
