### ISSUE TITLE
数据库列支持复制列到其他数据库

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10363]
### In what scenarios do you need this feature?

有些数据库的列是通用的配置，但又不想把整个数据库作为模板，可否支持复制列

### Describe the optimal solution

类似于重复列那种操作?

**Comment by 88250** [comment]
Notion 上好像没有类似操作，可能有潜在的问题，我们也暂时不考虑了，感谢提议。
