### ISSUE TITLE
块类型转换支持设置快捷键

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10361]
能够通过快捷键快捷的把几段话变成无序列表或有序列表

### In what scenarios do you need this feature?

现在的要通过鼠标多层级操作比较麻烦，要是能够通过快捷键就好了

### Describe the optimal solution

希望能够通过快捷键来操作

**Comment by 88250** [comment]
可以使用 Shift+↑/↓ 扩选多块，然后 Ctrl+/ 唤出菜单后选择 转换为

**Comment by QQQOrange** [comment]
> 可以使用 Shift+↑/↓ 扩选多块，然后 Ctrl+/ 唤出菜单后选择 转换为

一个快捷键能搞定的事儿，非要这么麻烦吗

**Comment by QQQOrange** [comment]
> r

你说的方案要点好几下呀，而且还要点某一个固定的选项，操作起来比较繁琐

如果有一个单独的快捷键的话通过鼠标选中后，按一下就好了，只要能够把段落变成无序列表，或有序列表就可以了。选中那是另外的工作嘛

当然你也可以直接在快捷键那一栏里面，让这个可以搜索得到，这样能自己设定快捷键

**Comment by QQQOrange** [comment]
> 一个快捷键的话不可能多选吧？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月17日(周六) 上午8:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 能够通过快捷键快捷的把几段话变成无序列表或有序列表 (Issue #10361) 可以使用 Shift+↑/↓ 扩选多块，然后 Ctrl+/ 唤出菜单后选择 转换为 一个快捷键能搞定的事儿，非要这么麻烦吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你说的方案要点好几下呀，而且还要点某一个固定的选项，操作起来比较繁琐

如果有一个单独的快捷键的话通过鼠标选中后，按一下就好了，只要能够把段落变成无序列表，或有序列表就可以了。选中那是另外的工作嘛

当然你也可以直接在快捷键那一栏里面，让这个可以搜索得到，这样能自己设定快捷键

**Comment by 88250** [comment]
用鼠标的话还是点菜单吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月17日(周六) 上午8:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 能够通过快捷键快捷的把几段话变成无序列表或有序列表 (Issue #10361)




  
r
  
你说的方案要点好几下呀，而且还要点某一个固定的选项，操作起来比较繁琐
 
如果有一个单独的快捷键的话通过鼠标选中后，按一下就好了，只要能够把段落变成无序列表，或有序列表就可以了。选中那是另外的工作嘛
 
当然你也可以直接在快捷键那一栏里面，让这个可以搜索得到，这样能自己设定快捷键

**Comment by QQQOrange** [comment]
> 用鼠标的话还是点菜单吧。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月17日(周六) 上午8:44 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 能够通过快捷键快捷的把几段话变成无序列表或有序列表 (Issue #10361) r 你说的方案要点好几下呀，而且还要点某一个固定的选项，操作起来比较繁琐 如果有一个单独的快捷键的话通过鼠标选中后，按一下就好了，只要能够把段落变成无序列表，或有序列表就可以了。选中那是另外的工作嘛 当然你也可以直接在快捷键那一栏里面，让这个可以搜索得到，这样能自己设定快捷键 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

就是鼠标点击不快捷，选中后又要移动鼠标点击按钮，又要移动鼠标点选项，要是有快捷键的话，方便太多了

**Comment by 88250** [comment]
等我们考虑下，先保持打开吧。

**Comment by QQQOrange** [comment]
> 等我们考虑下，先保持打开吧。

好嘞

**Comment by TCOTC** [comment]
@88250 是否在 #11634 中解决了？

**Comment by AvoidantPerDis** [comment]
> @88250 是否在 #11634 中解决了？

应该是，我已经用上了

**Comment by 88250** [comment]
> @88250 是否在 #11634 中解决了？

应该是解决了，我关闭这个了。
