### ISSUE TITLE
显示的时候没有斜杠符号，复制出来却有，也能通过搜索搜到

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/62794181/fed1a3c6-e396-46ec-8879-32af77a7f74e)
搜索“斜杠符号+>”后，在结果中能够明显的看到并没有斜杠符号，但却能够通过搜索搜出来，并且复制的时候也会多一个斜杠符号
[1.1.3 三、马克思和恩格斯的政治立场和思想的转变.sy.zip](https://github.com/siyuan-note/siyuan/files/14320632/1.1.3.sy.zip)

### Expected result

期待早日修复

### Version environment

```markdown
- Version: 2.12.8
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
输入的转义符会被保留的，所以搜索和复制时都会带有转义符 `\`。

**Comment by QQQOrange** [comment]
> 输入的转义符会被保留的，所以搜索和复制时都会带有转义符 `\`。

不能默认删除吗

**Comment by 88250** [comment]
不能删，有的用户需要搜索转义符。
