### ISSUE TITLE
Add internal kernel API `/api/block/appendDailyNoteBlock`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10368]
https://ld246.com/article/1708187266088

参数：

```json
{
    "data": "foo",
    "dataType": "markdown",
    "notebook": "20220407175815-lceq17w"
}
```

**Comment by zxhd863943427** [comment]
假如日记不在会创建日记吗？

**Comment by 88250** [comment]
会的。



---Original---
From: ***@***.***&gt;
Date: Sun, Feb 18, 2024 17:07 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Add internal kernel API`/api/block/appendDailyNoteBlock` (Issue #10368)




 
假如日记不在会创建日记吗？

**Comment by pakeh2866** [comment]
想通过这个建一个ios的快捷指令，构建post如下，显示code :-1还请D大帮忙看一下哪里错了？
1.post细节如下
![9b35deb6ab079d2f318f45243494cdc7](https://github.com/siyuan-note/siyuan/assets/5708881/2db1d7d8-2a2a-4ffe-865b-9aa39fd935ae)
2.返回的结果
![d1f48e3a340a366cfe89ecb10d62e02c](https://github.com/siyuan-note/siyuan/assets/5708881/fc4351f6-bf0a-4f86-b24b-22b6b5f7d414)

**Comment by pakeh2866** [comment]
把鉴权码删掉后成功了…
鉴权码的字段是什么？
