### ISSUE TITLE
希望保存路径不在assets的pdf也能通过思源内置的pdf阅读器打开

### ISSUE THREAD

**Issue by CSMsamuel** [siyuan-note/siyuan#10364]
### In what scenarios do you need this feature?

通过alt+拖拽导入的pdf，点击链接时会用电脑默认pdf阅读器打开，而不是思源内置的pdf阅读器。

### Describe the optimal solution

希望能通过思源笔记内部pdf阅读器打开

**Comment by 88250** [comment]
请使用符号链接，参考 https://ld246.com/article/1658912803699
