### ISSUE TITLE
选中文字后，拖拽文字不能到指定位置

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

选中一句话中的某几个文字后，可以拖动，但是并不能够拖到最后鼠标指向的位置

### Expected result

应该是 bug，希望早日修复

### Version environment

```markdown
- Version: 2.12.8
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个不支持，请看 https://github.com/siyuan-note/siyuan/issues/6169

**Comment by QQQOrange** [comment]
> 这个不支持，请看 #6169

好的
