### ISSUE TITLE
添加数据库功能中的数据库列表建议按数据库更新时间排序

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10360]
### In what scenarios do you need this feature?

目前好像是按照创建时间排序的

### Describe the optimal solution

无

**Comment by 88250** [comment]
你指的是添加行时的排序吗？默认是按自定义排序的。

**Comment by 88250** [comment]
这个是固定添加到首行，不是按时间排序的。

**Comment by Jiangshuon** [comment]
大佬，我是指这个，应该把最近使用的数据库显示在前面

<img width="468" alt="405b80e8d1faf2916298eb7606f9d18" src="https://github.com/siyuan-note/siyuan/assets/67137548/57929b41-af93-4d05-9912-ad2ce3add00d">

**Comment by Jiangshuon** [comment]
@88250 大佬差点忘了，我是说数据库的排序按更新时间。最近使用的数据库应该排到前面

![image](https://github.com/siyuan-note/siyuan/assets/67137548/2f680a5c-4d53-460b-bd81-af033100f34f)

**Comment by Jiangshuon** [comment]
https://github.com/siyuan-note/siyuan/issues/10546，就是按“添加数据库”这个快捷键后出现的数据库列表

**Comment by 88250** [comment]
现在应该就是按数据库更新时间排序的，不过只有更新数据库名称、修改单元格值的时候会更新时间，添加/删除行还不行，后面我看看能不能解决。

**Comment by 88250** [comment]
@Vanessa219 增减行和列的时候也加一下 tx 
![image](https://github.com/siyuan-note/siyuan/assets/873584/3771e65b-adac-4f7e-8671-19bd1c3a1f0b)

**Comment by Jiangshuon** [comment]
好的，多谢大佬，这个蛮重要的，目前通过块菜单不断添加块到数据库时很累，要不断搜索
