### ISSUE TITLE
在标题下新建小标题时，文档大纲中该标题不会自动展开以显示小标题

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

例如，这里有一个三级标题，这个三级标题下面目前没有任何的四级以下的标题。那么在这个三级标题下面新建一个四级标题。这时候这个文档大纲中三级标题默认是处于折叠状态，而不是展开状态

### Expected result

照理来说，应该是处于展开状态

### Version environment

```markdown
- Version: 2.12.8
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
启用这个就可以了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/83eca7b1-ccb8-4384-902e-2d52d5697d13)

**Comment by QQQOrange** [comment]
> 启用这个就可以了：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/305691769-83eca7b1-ccb8-4384-902e-2d52d5697d13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTUwMzcsIm5iZiI6MTcwODI1NDczNywicGF0aCI6Ii84NzM1ODQvMzA1NjkxNzY5LTgzZWNhN2IxLWNjYjgtNDM4NC05MDJlLTJkNTJkNTY5N2QxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMTEyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjE1Nzk0YWZmMTY1YmYwNjg2MGJmZjkzOGJjOGRiMWEwNjk4ZDZjOTNkM2MzMzcwZDQ3NGQxYTM5ODFjOTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9d6dpLR-UdyCeZCmPHald5KLdjPds7vNvHoXfzvHOAU)

默认是折叠的，可以提供一个选项，选择默认展开吗？
