### ISSUE TITLE
有一定几率启动失败，

### ISSUE THREAD

**Issue by windoversnow** [siyuan-note/siyuan#1036]
### 描述问题 Describe the problem

比较轻微的失败是，内核未能成功启动，重启软件就好了，但不知为什么内核这么容易启动失败

比较严重的失败是，整个界面编程白屏，全白，什么都没有，这时去配置文件夹看，会发现配置文件变成了空文件

https://s3.ax1x.com/2021/01/13/stZb5j.png

@88250

**Comment by windoversnow** [comment]
https://github.com/siyuan-note/siyuan/issues/996#issuecomment-757139293

我看有别人有类似问题，不行下个版本时，默认把配置文件放到安装目录吧，或者可以用户指定位置

**Comment by 88250** [comment]
你好，谢谢反馈。配置目录是可以指定位置的，请看帮助文档启动参数一节。

**Comment by FastStonewkx** [comment]
为啥我出现白屏必须重启电脑。
![image](https://user-images.githubusercontent.com/36177654/104844248-17df7e80-590a-11eb-8420-93c6fe766589.png)

**Comment by FastStonewkx** [comment]
![siyuan_error](https://user-images.githubusercontent.com/36177654/104844438-24b0a200-590b-11eb-913e-905219e179fa.gif)

**Comment by 88250** [comment]
@FastStonewkx 请贴一下日志文件。

**Comment by windoversnow** [comment]
我觉得内核的失败还是发生在读写文件上，包括读写配置文件，和读写md文件，我昨天故意试了试，启动正常后，开始点文件树刷新，刷几次就肯定能刷崩溃，屡试不爽。 @88250

**Comment by windoversnow** [comment]
启动正常后，如果什么操作也没有，单单放在那里，几个小时也不会崩，
看任务管理器里，I/O信息，只要一点都不操作软件，I/O信息就也一动不动，

**Comment by windoversnow** [comment]
> 我觉得内核的失败还是发生在读写文件上，包括读写配置文件，和读写md文件，我昨天故意试了试，启动正常后，开始点文件树刷新，刷几次就肯定能刷崩溃，屡试不爽。 @88250

如果说读写配置文件，涉及到用户默认文件夹，有权限，那我放在非c盘的笔记md文件有个啥权限呢，刷新几次文件树必定崩溃，具体软件工作过程我不清楚，但觉得读写文件时，确实会容易触发内核崩溃，这也跟我之前提到过的一点比较类似，有的文件就是容易让内核崩溃，文件太长？图片太多？kramdown语法编译有缺陷？不懂

**Comment by 88250** [comment]
> 我觉得内核的失败还是发生在读写文件上，包括读写配置文件，和读写md文件，我昨天故意试了试，启动正常后，开始点文件树刷新，刷几次就肯定能刷崩溃，屡试不爽。 @88250

@windoversnow 请试下将笔记本关闭，只保留一个自带的帮助文档笔记本，看下是否还能重现问题，谢谢。

**Comment by FastStonewkx** [comment]
上一次我是找过你的，也是这个问题。白屏最后是重启电脑恢复了，搞了一整天，因为我一般不会轻易重启电脑。还有日志上次看过，你说是端口占用，但是真没找到。
https://github.com/siyuan-note/siyuan/issues/467

**Comment by FastStonewkx** [comment]
[app.log](https://github.com/siyuan-note/siyuan/files/5829412/app.log)

**Comment by FastStonewkx** [comment]
这次依旧是重启解决了

**Comment by 88250** [comment]
> [app.log](https://github.com/siyuan-note/siyuan/files/5829412/app.log)

麻烦再传一下 siyuan.log

**Comment by FastStonewkx** [comment]
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5831388/siyuan.log)

**Comment by FastStonewkx** [comment]
还是端口问题吗

**Comment by 88250** [comment]
> 我看出来了，是端口占用的问题
> ![image](https://user-images.githubusercontent.com/36177654/104942126-ff955f80-59ee-11eb-9244-4b64c74c8c1e.png)
> 不清楚你们有没有打算把端口号设置高一点

能进一步帮忙看看是什么程序占用的么？这个端口号被其他程序占用的可能性较小，多半还是思源内核自己在用。

界面启动时如果发现已经有能用的内核是不会再去拉起内核启动的，内核启动过程中也会检查端口占用情况，如果之前已经有内核进程用了 6806 则本次启动的内核会自动退出，理论上不会出现这行日志。

这个过程有点复杂，所以也有可能是代码缺陷导致，我们会继续排查下代码逻辑，谢谢。

**Comment by windoversnow** [comment]
> > 我觉得内核的失败还是发生在读写文件上，包括读写配置文件，和读写md文件，我昨天故意试了试，启动正常后，开始点文件树刷新，刷几次就肯定能刷崩溃，屡试不爽。 @88250
> 
> @windoversnow 请试下将笔记本关闭，只保留一个自带的帮助文档笔记本，看下是否还能重现问题。另外，请提供一下日志文件，谢谢。

https://s3.ax1x.com/2021/01/19/scO7Ox.png

I 2021/01/19 09:08:53 working.go:82: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/19 09:08:53 working.go:83: kernel [v0.6.1] is booting, runtime mode is [prod], working directory is [E:\Program Files\SiYuan\resources], temp directory is [C:\Users\967\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/19 09:08:54 lang.go:67: initialized languages
D 2021/01/19 09:08:54 conf.go:76: loaded conf [E:\Program Files\SiYuan\.siyuan\conf.json]
I 2021/01/19 09:08:54 conf.go:166: local serve path [http://10.12.70.6:6806]
I 2021/01/19 09:08:54 conf.go:170: initialized conf
I 2021/01/19 09:08:54 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/19 09:08:55 webdav.go:37: initialized WebDAV server
I 2021/01/19 09:08:56 box.go:338: indexing [70] trees, cpus [16]
D 2021/01/19 09:08:57 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/SIFORME/]
I 2021/01/19 09:08:57 conf.go:287: initialized box
I 2021/01/19 09:09:10 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:10 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:10 webdav.go:178: opened local box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:14 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/SIFORME/]
D 2021/01/19 09:09:14 webdav.go:66: closed box [http://127.0.0.1:6806/siyuan/1607934760589/SIFORME/]
I 2021/01/19 09:09:24 repo.go:39: initialized git repo
D 2021/01/19 09:09:29 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:29 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:29 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:35 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:35 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:35 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:39 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:39 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:39 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:39 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:39 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:39 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:39 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:39 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:40 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:40 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:40 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:40 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:40 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:40 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:40 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:40 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:40 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:40 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:40 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:40 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:40 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:40 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:40 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:41 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
D 2021/01/19 09:09:41 box.go:401: unindexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
I 2021/01/19 09:09:41 box.go:338: indexing [38] trees, cpus [16]
D 2021/01/19 09:09:41 box.go:373: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/思源笔记用户指南/]
F 2021/01/19 09:09:43 conf.go:244: write conf [E:\Program Files\SiYuan\.siyuan\conf.json] failed: open E:\Program Files\SiYuan\.siyuan\conf.json: The requested operation cannot be performed on a file with a user-mapped section open.

**Comment by 88250** [comment]
@windoversnow 

> F 2021/01/19 09:09:43 conf.go:244: write conf [E:\Program Files\SiYuan\.siyuan\conf.json] failed: open E:\Program Files\SiYuan\.siyuan\conf.json: The requested operation cannot be performed on a file with a user-mapped section open.

还是这个报错影响了内核读取配置文件。从网络上了解到的信息看，是因为有其他程序进程通过内存映射的方式打开了这个文件，这会导致思源去读取的时候失败。
