### ISSUE TITLE
开启只读模式，新建笔记还得手动关只读模式才可编辑。

### ISSUE THREAD

**Issue by UPToZ-Core** [siyuan-note/siyuan#10379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

开了只读模式后，新建笔记还得手动关只读模式才可编辑。

### Expected result

新建笔记时，应该默认关闭掉只读模式。

### Version environment

```markdown
- Version:  v2.12.8
- Operating System: 
- Browser (if used):
```

### Log file

none

**Comment by LGRemdo** [comment]
这难道不是正常的特性吗。。。。

**Comment by UPToZ-Core** [comment]
> 这难道不是正常的特性吗。。。。

这难道是正常的逻辑？我新建笔记就是为了编写，为啥不会自动去掉只读呢？难不成我开了只读模式以后，每次新建笔记还要手动解锁一下，为什么不是新建笔记就自动进行解锁呢？

**Comment by 88250** [comment]
只读模式指的是编辑器只读，不涉及其他地方的操作，感谢反馈。
