### ISSUE TITLE
希望PDF复制标注支持自定义格式

### ISSUE THREAD

**Issue by holduan** [siyuan-note/siyuan#10370]
### In what scenarios do you need this feature?

在文档内做PDF阅读笔记时，有使用场景需要可以更便捷地编辑锚文本的功能。
格式可以是：XXX  回链。
目前是通过quicker替换文本实现，，希望思源可以原生支持，效果如下图：
![image](https://github.com/siyuan-note/siyuan/assets/80377040/fe005621-85ca-4cf1-8784-e92e4a083b2b)

### Describe the optimal solution

现思源内复制标注的格式：
`<<assets/支持笔交互的手写设备设计与实现-20221213220532-ugr6tfp.pdf/20240218164430-kw28f0i "实验室结果表明，F-Pad 能够完整实现对笔交互过程中全力信息的获取，并在没有引入复杂数据处理算法基础上提供一种“所写即所见”的自然交互效果。">>`

自定义格式例子：
`- 实验室结果表明，F-Pad 能够完整实现对笔交互过程中全力信息的获取，并在没有引入复杂数据处理算法基础上提供一种“所写即所见”的自然交互效果。  <<assets/支持笔交互的手写设备设计与实现-20221213220532-ugr6tfp.pdf/20240218164430-kw28f0i "*">>`

**Comment by 88250** [comment]
编辑器中的标注元素是行级元素，所以无法作用在块级元素上。

如果只是希望在 PDF 阅读器中的标注关联到块的话，可以使用 关联 设置 块 ID 列表：

![image](https://github.com/siyuan-note/siyuan/assets/873584/a4bc4537-a3b2-423d-be04-ab2b1ba16203)

**Comment by holduan** [comment]
> 编辑器中的标注元素是行级元素，所以无法作用在块级元素上。
> 
> 如果只是希望在 PDF 阅读器中的标注关联到块的话，可以使用 关联 设置 块 ID 列表：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/305705313-a4bc4537-a3b2-423d-be04-ab2b1ba16203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjA1ODAsIm5iZiI6MTcwODI2MDI4MCwicGF0aCI6Ii84NzM1ODQvMzA1NzA1MzEzLWE0YmM0NTM3LWEzYjItNDIzZC1iZTA0LWFiMmIxYmExNjIwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMjQ0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmNlOGY1OWNjYWYxYjFhMzQ4ODY4MDgyMjE1ZTAwYjE4ZWZjZmMwYzVhMDg1MTY1MzQ0ODk4ZjdmMmQ4MzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uo2nl5UQU58N-yrua2e-84h_1vzinTkKYM_ArKeuT0k)

嗯嗯，其实是想便捷地实现在粘贴标注文本（非锚文本形式）的同时带上一个回链
