### ISSUE TITLE
添加一个《信息面板》，显示「工作空间」的信息

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10378]
### In what scenarios do you need this feature?

我希望添加一个新的功能，快捷键激活显示空间信息的面板。

为什么需要这个功能呢？

- 背景：因为我个人的原因，我会在便携式移动u盘里面实现笔记的编辑。在这种情况下，一般来说我的电脑是不具备原始或者是最新版本的数据的。但是在我的部分办公电脑当中，部分机械/固态硬盘会存在较为落后的版本的数据，这可能是因为同步不及时所导致的。
- 错误的发生：在这样的背景下，有的时候我就会运行 siyuan 笔记的时候，可能会在**错误的工作空间**当中实现笔记的更新，这就导致了一个问题 —— 版本错位。

我已经被这种情况误导不下4次了，每一次都会让我怀疑是不是 SiYuan 存在笔记丢失的情况。因此，急需这个功能，能够提示我，让我检查一下是不是正确的工作环境。

### Describe the optimal solution

希望能够弹出一个面板，能够显示当前的工作空间信息，比如说名字、路径，然后为了让面板不再空旷，可以添加一些其他额外的信息，比如说笔记本的数量等等之类的。

为了能够让这个面板显示的更加方便，可以配备快捷键。

**Comment by 88250** [comment]
* 设置 - 关于中有程序版本信息
* 左上角主菜单中有工作空间路径信息

其他统计信息暂时不考虑添加了，请使用 SQL 或者 API 查询，谢谢。
