### ISSUE TITLE
集市可以设置快捷键直达

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10376]
### In what scenarios do you need this feature?

每次打开思源第一件事就是打开集市，看看有没有插件和主题更新。

但每次打开用鼠标点得点好几下

如果用快捷键的话，也只能打到设置层面，还得再点几下。

希望能够有一个集市的直达快捷键

可以提供选项，让用户自己设置

### Describe the optimal solution

希望提供快捷键

**Comment by QQQOrange** [comment]
> 这个不考虑了，感谢提议。

自己设定快捷键的都不可以吗

**Comment by 88250** [comment]
对于大部分用户来说不是高频功能，所以暂时不考虑了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月19日(周一) 下午4:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 集市可以设置快捷键直达 (Issue #10376)




  
这个不考虑了，感谢提议。
  
自己设定快捷键的都不可以吗

**Comment by QQQOrange** [comment]
> 对于大部分用户来说不是高频功能，所以暂时不考虑了。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月19日(周一) 下午4:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 集市可以设置快捷键直达 (Issue #10376) 这个不考虑了，感谢提议。 自己设定快捷键的都不可以吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好吧

**Comment by LGRemdo** [comment]
我给你提供一个方案，就是用 Quicker 按下多个快捷键实现。

先打开设置，然后发送文本到窗口“集市”

**Comment by QQQOrange** [comment]
主要的目的是为了方便，但这样搞就不方便了。因为如果有一个直达快捷键的话，那我按一下就好了。
如果用 quicker 来实现的话，我要先唤起，然后再点击，那就和我通过打开设置设置再点一样，谢谢老哥 笔芯

> 我给你提供一个方案，就是用 Quicker 按下多个快捷键实现。
> 
> 先打开设置，然后发送文本到窗口“集市”

**Comment by LGRemdo** [comment]
> 主要的目的是为了方便，但这样搞就不方便了。因为如果有一个直达快捷键的话，那我按一下就好了。 如果用 quicker 来实现的话，我要先唤起，然后再点击，那就和我通过打开设置设置再点一样，谢谢老哥 笔芯
> 
> > 我给你提供一个方案，就是用 Quicker 按下多个快捷键实现。
> > 先打开设置，然后发送文本到窗口“集市”

我的意思是你可以直接设置一个动作，然后让这个动作的激活方式更改为快捷键就行了。
