### ISSUE TITLE
数据库排序异常

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#10377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

排序后，向数据库添加一行数据时会发生异常，撤销也会导致异常

### Expected result

修复

### Version environment

```markdown
- Version: 3.0.0-dev2
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你指的“异常”是？

**Comment by TinkMingKing** [comment]
假如以主键排序，新添加一行，就会自动添加主键列，值为末尾行的值，以其他列排序，就会添加其他列的最后一行的值



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 中午1:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 数据库排序异常 (Issue #10377)




 
你指的“异常”是？

**Comment by 88250** [comment]
这是正常的预期，否则在排序状态下添加行后行无法添加到末尾。
