### ISSUE TITLE
文档树排序不为自定义排序时，笔记本排序为自定义排序使用不了在上方/下方新建文档功能

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#10381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/38906705/a5e6e1b3-11e9-4ec7-aea7-c015852cfb6c)
![image](https://github.com/siyuan-note/siyuan/assets/38906705/66b014c6-d044-41f3-aa71-d612092b28fa)
![image](https://github.com/siyuan-note/siyuan/assets/38906705/5883bf02-58e5-45f3-9b0d-c26a319ad99f)

### Expected result

1. 文档树排序不为自定义排序时，笔记本排序为自定义排序可使用上方/下方新建文档功能
2. 笔记本排序不为自定义排序时应该隐藏使用上方/下方新建文档功能

### Version environment

```markdown
- Version: v3.0.0
- Operating System: win10
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
这个只有在自定义排序模式下才能启用，感谢反馈。

**Comment by royc01** [comment]
哦哦，我以为笔记本排序的优先级比文档树高

**Comment by 88250** [comment]
后续我们再确认下 @Vanessa219

**Comment by Vanessa219** [comment]
是有问题，已改进
