### ISSUE TITLE
可以集成 Drawio 到思源笔记里吗?

### ISSUE THREAD

**Issue by JasonDong97** [siyuan-note/siyuan#10387]
### In what scenarios do you need this feature?

有的时候想要画一些流程图、UML 之类的, 但发现思源笔记似乎不支持画图

### Describe the optimal solution

希望可以集成 drawio 功能，或者预览 drawio 文件。

**Comment by JasonDong97** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/21983909/26700d0c-ab63-484d-b794-523c29c93a4c)

**Comment by suka233** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/43712875/0fff59fb-bc71-4064-8337-0bf7ec52e029)

**Comment by JasonDong97** [comment]
> ![image](https://private-user-images.githubusercontent.com/43712875/306489995-0fff59fb-bc71-4064-8337-0bf7ec52e029.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODkyMzksIm5iZiI6MTcwODQ4ODkzOSwicGF0aCI6Ii80MzcxMjg3NS8zMDY0ODk5OTUtMGZmZjU5ZmItYmM3MS00MDY0LTgzMzctMGJmN2VjNTJlMDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA0MTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNjU1NmNiNGZjMDgzYjNmMzRlZGY2MTc0NGIzNTgzMWFlNTE5N2MzOTJkZmU5ZTdkN2ZjODlmMmQ0YTMxZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2r0n9JbaUULGCIyz9qJPQSY5ACvAk8_Xh1re5k_10rI)

非常感谢~
