### ISSUE TITLE
思源动态读取excel数据-强化思源表格功能-excel插件化

### ISSUE THREAD

**Issue by reedtop** [siyuan-note/siyuan#1038]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
需要动态将excel里面的数据,引入思源文档类文件时

情景1
excel记账
当excel添加或者修改数据后,汇总界面的对应位置金额数据  被思源读取,展现在某些位置 
模版或者报表

情景2
结合excel和文档的笔记需求
例如一份excel的接口文档   每个接口都在一个页面
思源在引入对应页面的数据
放到文档中  
达到文本表格混排  同时自动更新的目的

情景3
excel插件化
思源本身的计算函数功能不够强大
如果在excel中使用excel自身的函数进行计算,再引入到思源中展示

相当于另一种意义上的插件
只是这个插件本身是excel及其对应的全部生态

可以描述为
打开excel插件  excel计算数据  组合数据  思源更新展示数据

### 描述最优的解决方案 Describe the optimal solution
思源
引入excel文件
引入页面数据
引入页面范围数据
引入单元格数据

思源
直接打开引用数据的excel

**Comment by 88250** [comment]
等插件机制建立后再考虑，感谢提议。

**Comment by vanxuing** [comment]
> ### 你在什么场景下需要该功能？ In what scenarios do you need this function?
> 需要动态将excel里面的数据,引入思源文档类文件时
> 
> 情景1 excel记账 当excel添加或者修改数据后,汇总界面的对应位置金额数据 被思源读取,展现在某些位置 模版或者报表
> 
> 情景2 结合excel和文档的笔记需求 例如一份excel的接口文档 每个接口都在一个页面 思源在引入对应页面的数据 放到文档中 达到文本表格混排 同时自动更新的目的
> 
> 情景3 excel插件化 思源本身的计算函数功能不够强大 如果在excel中使用excel自身的函数进行计算,再引入到思源中展示
> 
> 相当于另一种意义上的插件 只是这个插件本身是excel及其对应的全部生态
> 
> 可以描述为 打开excel插件 excel计算数据 组合数据 思源更新展示数据
> 
> ### 描述最优的解决方案 Describe the optimal solution
> 思源 引入excel文件 引入页面数据 引入页面范围数据 引入单元格数据
> 
> 思源 直接打开引用数据的excel
> 
> ### 描述候选解决方案 Describe the candidate solution
> ### 其他信息 Other information

这个问题可以从新考虑了么？？
