### ISSUE TITLE
建议关系图画布的导航模式添加切换`鼠标`/`触控板`的配置项

### ISSUE THREAD

**Issue by curlykay** [siyuan-note/siyuan#10385]
### In what scenarios do you need this feature?

对于使用触控板控制光标用户而言，关系图画布中双指滑动操作触发画布拖动是比触发画布缩放而言更舒适的交互体验。

### Describe the optimal solution

提供一个配置项，用于设置关系图在画布中操作方式是`鼠标`还是`触控板`。切换操作方式为`触控板`时，在画布上双指同方向滑动会触发画布拖动效果而不是画布缩放效果

可以体验参照https://app.boardos.online/dashboard
<img width="1429" alt="image" src="https://github.com/siyuan-note/siyuan/assets/35558285/fd2ff04b-bfd2-454e-988c-940bdf969a92">

**Comment by 88250** [comment]
抱歉，这个可能无法实现了，感谢反馈。
