### ISSUE TITLE
设定标题时会把跟这个标题不相邻的一整段话一起变为标题并且连接起来

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

[2.4.1 一、未来社会经济关系一般性质的分析.sy.zip](https://github.com/siyuan-note/siyuan/files/14352774/2.4.1.sy.zip)
![image](https://github.com/siyuan-note/siyuan/assets/62794181/b9655ad9-8212-49ac-a03d-2878bb07cfd6)
要把图片中的 未来社会劳动分配理论 设为标题三、按下快捷键的时候，这一句话上面的一大段话会被一起设为标题，并且中间的空会删除，最后变成这样
![image](https://github.com/siyuan-note/siyuan/assets/62794181/662bb8ee-0d3a-45d7-bd80-30734f48df60)

### Expected result

早日修复

### Version environment

```markdown
- Version: 3.0
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请提供能够重现问题的 .sy.zip 谢谢。

**Comment by QQQOrange** [comment]
> 请提供能够重现问题的 .sy.zip 谢谢。

已经上传了，你网上瞅瞅

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/fbd4951c-032b-4b60-be83-d309c1e8e051)

这里是同一个块。

**Comment by QQQOrange** [comment]
> ![image](https://private-user-images.githubusercontent.com/873584/306580528-fbd4951c-032b-4b60-be83-d309c1e8e051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTAyNTAsIm5iZiI6MTcwODUwOTk1MCwicGF0aCI6Ii84NzM1ODQvMzA2NTgwNTI4LWZiZDQ5NTFjLTAzMmItNGI2MC1iZTgzLWQzMDljMWU4ZTA1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxMDA1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzdhNDg3YTlhMjQ4NjAyYWE2OWFjOWM4Y2E1NjIyZWQwMjY2NmViODMzN2UyZjFkODUyMGIxYWFhYTcxNWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yvV-xzx50onKGq-6eIj7TbEHO3Xq6xdpccBMw2g1qGU)
> 
> 这里是同一个块。

你可以看我的截图 连续换行多次之后，设标题还是会有我说的这个问题

**Comment by 88250** [comment]
麻烦录屏演示操作。

**Comment by QQQOrange** [comment]
> 麻烦录屏演示操作。

录屏的话，我不太会，你可以做成我截图的那个形式来尝试

**Comment by 88250** [comment]
这个文档是手动编辑的还是如何产生的？这个段落块的 DOM 结构好像有问题。

**Comment by QQQOrange** [comment]
> 这个文档是手动编辑的还是如何产生的？这个段落块的 DOM 结构好像有问题。

这个文档是 doc 文档通过导入插件导入的

**Comment by 88250** [comment]
把这两个地方的 `*` 删除了再回车编辑就正常了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/f9790ccf-f117-4403-8848-3b965bb6f8b0)

**Comment by QQQOrange** [comment]
> 把这两个地方的 `*` 删除了再回车编辑就正常了：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/306586976-f9790ccf-f117-4403-8848-3b965bb6f8b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTE1MzUsIm5iZiI6MTcwODUxMTIzNSwicGF0aCI6Ii84NzM1ODQvMzA2NTg2OTc2LWY5NzkwY2NmLWYxMTctNDQwMy04ODQ4LTNiOTY1YmI2ZjhiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQxMDI3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjVmYWQ5YzgzYzE1ZDRkNGRhZDYxMzJhZWY3MTcxYjYxZDgzNjkzM2JhOTJmYjY3YzUzMmViODY0ZjJkY2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ceaGgrL9St8xBTNQYLMwkjvPbxlhNSaLuXI0YS24l34)

哦哦 谢谢老哥

**Comment by 88250** [comment]
这种情况我们后续会在 https://github.com/siyuan-note/siyuan/issues/10391 中进行改进，感谢反馈。
