### ISSUE TITLE
删除文档末尾的行后，光标位置异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

删除文档末尾的行后，光标会跑到行的开头

### Expected result

光标应该在文本的末尾

### Screenshot or screen recording presentation

![删除行](https://github.com/siyuan-note/siyuan/assets/78434827/3306eab3-19ed-48ab-ab14-948bf9cf0ce2)

![删除行2](https://github.com/siyuan-note/siyuan/assets/78434827/1979c575-df72-4f66-bc04-4d648381d4df)

### Version environment

```markdown
- Version: 3.0.0
- Operating System: Windows 10
```

### Log file

无

**Comment by 88250** [comment]
@Vanessa219 可能和这个是同一个问题 https://github.com/siyuan-note/siyuan/issues/10389

**Comment by Vanessa219** [comment]
同 https://github.com/siyuan-note/siyuan/issues/10389
