### ISSUE TITLE
Support listing blocks with invalid references in the search dialog

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10396]
支持列出失效的块引用

特性建议：搜索面板添加查找无效块引和块链接

### In what scenarios do you need this feature?

目前使用MOC管理笔记有一个问题，删除文档后，链接不会删除，现在的方法是需要手动删除块链接，如果程序自动删除转化为纯文本，可能也会对笔记内容造成破坏

![Clip_2024-02-22_10-10-48](https://github.com/siyuan-note/siyuan/assets/60436214/85eb28a3-f8de-40b9-8168-d3cc17bd376e)

### Describe the optimal solution

有一个可行的方法是，搜索面板添加查找无效块引和块链接，就如同查找无效资源一样，用户经过一段时间后，自己手动查找无效块引和块链接，根据需要自行选择删除内容块、转化链接为锚文本。

除了有利于使用MOC管理笔记外，还有以下好处
1. 一个块有很多反向链接，用户有可能不小心删除了，通过这一功能，可以知道哪些块被删除了
2. 因为不正常的同步，一些块被删除，也能通过这一功能，得知可以知道其中的一部分块没有被正常同步

### Describe the candidate solution

无

**Comment by UFDXD** [comment]
提一个类似的，就是现在我用“引用”代替标签，但是问题就是，两个差不多的引用标签意义合并，另一个文档被代替，其他所有引用这个文档的失效描文本也要全部找出来一个一个删。数量上十来个就很烦。这个需求点是需要一个文档删除其他所有失效引用引用描文本要自动删除。

**Comment by TCOTC** [comment]
@UFDXD 可以看看「转移引用」插件能不能满足你的需求

![image](https://github.com/siyuan-note/siyuan/assets/78434827/84449e20-9790-4246-b7a5-b6accb690f35)

**Comment by UFDXD** [comment]
@TCOTC  转移引用我知道但思源自带的就足够。矛盾点是引用当标签，假设一个内容块xxxx文本中打了 两个同义但不同词的两个引用标签【xxxxxx((A1))((A2))xxxxxx】，后期回顾抽到了就要合并两个标签，但由于这两个标签已经用于了很多其他条目内容块，那么合并，其中大量((A1))需要转移给((A2))，在动态描文本机制下((A1))不会删除而是变成((A2))，那么大量转移后的内容块中就存在两个((A2))了类似：【xxxxxx((A1))((A2))xxxxxx】，那么虽然重要的反链功能不会受到影响，但为舒服期间其中一个就要删除。另外为什么会出现打了两个近义标签，当时就不注意。这是因为打标签这种事情多用了就会发生的难免的状况，只能后期回顾时发现，所以标签体系标签是一个经常需要更新动态的一个过程。用引用标签还是因为不得已，思源原本的标签改个名字就像重启刷新，批量改标签是不可能的事情，还有标签删除需要到标签树中去找而没有搜索功能，在几千个庞杂的标签树中找一个光翻就要很长时间了。

**Comment by Achuan-2** [comment]
@88250 和【丢失的资源文件】实现机制会不一样吗
![Clip_2024-02-24_11-08-23](https://github.com/siyuan-note/siyuan/assets/60436214/4364960b-80a3-45c3-b0fb-6cc082b82bcb)

**Comment by 88250** [comment]
@Achuan-2 原理差不多，但是区别在于 资源文件 这里是只计算一次，而要做文档内失效引用查询的话每次打开文档都需要计算一遍，开销太大。

**Comment by 88250** [comment]
你的意思是不再编辑器里显示吗？

**Comment by Achuan-2** [comment]
嗯，我希望的是在搜索面板添加这个功能

**Comment by 88250** [comment]
抱歉抱歉，看漏了，我理解错了 :joy:

我考虑下看看。

**Comment by 88250** [comment]
功能入口位于搜索界面右上角：

![image](https://github.com/siyuan-note/siyuan/assets/873584/2c1bb792-72e7-4f8d-9316-a851587a772e)

**Comment by AvoidantPerDis** [comment]
能否一键将无效引用转化为静态文本？

**Comment by HowcanoeWang** [comment]
> 这个可能有问题，因为引用如果是动态锚文本的话在定义块丢失的情况下是无法查询到锚文本的。

这就不得不提到我之前提出个一个feature request了 #4071

**Comment by AvoidantPerDis** [comment]
> > 这个可能有问题，因为引用如果是动态锚文本的话在定义块丢失的情况下是无法查询到锚文本的。
> 
> 这就不得不提到我之前提出个一个feature request了 #4071

我也是这么想的，不过目前还是先整闪卡吧，这些都小事
