### ISSUE TITLE
Improve deletion of the empty block below thematic breaks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10393]
在分隔线下方的图片删除后，无法正常删除空行

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 图片在分隔线下方
2. 删除（Delete）图片
3. 无法正常删除（Backspace）分隔线后的空行

### Expected result

按一次退格键即可删除空行

### Screenshot or screen recording presentation

忽略上下两行 1 和 2 ：

![无法删除](https://github.com/siyuan-note/siyuan/assets/78434827/55111ec2-203a-4644-a720-273f1666856e)

### Version environment

```markdown
- Version: 3.0.0
- Operating System: Windows 10
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14358734/system-log.zip)

**Comment by Vanessa219** [comment]
删除图片后继续删除，光标会在分割线后，再点删除即可

https://github.com/siyuan-note/siyuan/assets/970828/dc55b7af-1603-4391-b07a-19d72953d8bd

**Comment by TCOTC** [comment]
@Vanessa219 我说的是「无法正常删除空行」，不是要删除分隔线

**Comment by 88250** [comment]
@TCOTC 懂了，谢谢。

**Comment by TCOTC** [comment]
@Vanessa219 v3.0.6-dev3 还有同样的问题

**Comment by Vanessa219** [comment]
我这里无法重现
https://github.com/siyuan-note/siyuan/assets/970828/24db526f-dbce-40e1-b052-d05d95b3db08

**Comment by TCOTC** [comment]
要选中图片，光标不是在图片后面

**Comment by Vanessa219** [comment]
选中图片后，光标就会落在图片后面

**Comment by TCOTC** [comment]
思源重启之后又复现不了了，不知道是什么原因，但暂时没问题了

**Comment by Vanessa219** [comment]
好的，可以重现的话 at 我。谢谢
