### ISSUE TITLE
搜索页签

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#104]
搜索结果分为两层：

```markdown
文档块1（匹配 5 ）
    内容块1
    内容块2
    ... 展开更多
文档块2（匹配 10 ）
    内容块1
    内容块2
    ... 展开更多
```

**Comment by Invoker2017** [comment]
搜索加上简单的操作符，如Everything的：
输入 内容A|内容B（含有内容A或内容B） 
输入 !内容C （当前结果排除含有内容C）
输入 内容A 内容B（文块内同时含有内容A或内容B）

正则表达式什么的入门太深了，我感觉这个功能用的好足够完成类似Notion的DataBase筛选功能，单纯的搜索还是不支持复杂的数据库。

**Comment by Invoker2017** [comment]
可以加一项信息，参考RE的大纲

文档块1（匹配 5 ）
内容块上级标题（如果有）（小字）
    内容块1
    内容块2
    ... 展开更多

搜到的内容是这样的：
# 内容块上级标题
## （其他不显示在搜索结果）
## 内容块1
## （其他不显示在搜索结果）

**Comment by 88250** [comment]
> 搜索加上简单的操作符，如Everything的：
> 输入 内容A|内容B（含有内容A或内容B）
> 输入 !内容C （当前结果排除含有内容C）
> 输入 内容A 内容B（文块内同时含有内容A或内容B）
> 
> 正则表达式什么的入门太深了，我感觉这个功能用的好足够完成类似Notion的DataBase筛选功能，单纯的搜索还是不支持复杂的数据库。

搜索条件会在 https://github.com/siyuan-note/siyuan/issues/72 中完成。

**Comment by wbooooooo** [comment]
1、关于搜索页签，建议可以搜索指定文件夹，或指定文档。
2、搜索结果展示，建议能到段落级别。特别是文档页内搜索。
3、对于同一篇文档的搜索结果，建议按先后顺序排序。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/586#issue-750916709

**Comment by deerainw** [comment]
偶然又看到这个 issue，顺手回复一下，在全局搜索内容的时候，Obsidian 的这个默认收起选项真的挺重要的：

![image](https://user-images.githubusercontent.com/32661922/102958439-d2e94780-4517-11eb-97c9-ce96f24d5891.png)
