### ISSUE TITLE
Update outline after closing all editors

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

例如我正在看一篇文章，然后给这篇文章设定好了大纲。然后这篇文章看完之后，我把这篇文章给叉掉，照理来说，这篇文章的大纲应该会一起关闭。但是实际上，这篇文章的大纲却仍然会展现出来。

### Expected result

理想的解决方案是关闭文章之后，大纲一起关闭，同时打开文档树

### Version environment

```markdown
- Version: 3.0
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by UFDXD** [comment]
是指的所有页签关闭后大纲没有关闭吧。我也想起来有这个问题的，看视频最后确实没有清空


https://github.com/siyuan-note/siyuan/assets/97731736/8d386e2b-aaa2-44d3-83c4-3c3aaf30796f

**Comment by QQQOrange** [comment]
> 是指的所有页签关闭后大纲没有关闭吧。我也想起来有这个问题的，看视频最后确实没有清空
> 
>  explorer_WpbzaAM64e.mp4

是的，我改改
