### ISSUE TITLE
不知道什么原因被折叠起来的大纲，偶尔会自己打开

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/62794181/f4a2af1f-9ae2-491f-96a6-9e1038644b81

具体可以观看以上视频

### Expected result

我也不知道什么原因，就希望折叠之后，如果没有经过展开的操作的话，不会自己展开

### Version environment

```markdown
- Version: 3.0
- Operating System: win11
- Browser (if used):
```

### Log file

[3.5.3 三、在批判伯恩施坦主义中捍卫马克思主义.sy.zip](https://github.com/siyuan-note/siyuan/files/14382298/3.5.3.sy.zip)
[system-log.zip](https://github.com/siyuan-note/siyuan/files/14382302/system-log.zip)

**Comment by 88250** [comment]
我这里无法重现问题，请使用默认主题并关闭所有插件、代码片段后测试。

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/2f0dd7c1-0391-4343-91ce-6af236f5b7de)

**Comment by QQQOrange** [comment]
> 我这里无法重现问题，请使用默认主题并关闭所有插件、代码片段后测试。
> 
>  issue.webm

关闭所有插件使用默认主题后，仍然能够重现

https://github.com/siyuan-note/siyuan/assets/62794181/067e06cb-f19d-4706-99df-68de2a512e67

**Comment by 88250** [comment]
保持全部展开的话肯定是全部展开啊，你把这个关了试试。

**Comment by QQQOrange** [comment]
> 保持全部展开的话肯定是全部展开啊，你把这个关了试试。

我之后也点击了全部折叠按钮。

**Comment by 88250** [comment]
是折叠起来了，但是后面内容变了所以要保持展开。

**Comment by QQQOrange** [comment]
> 是折叠起来了，但是后面内容变了所以要保持展开。

好的，我正在尝试

**Comment by QQQOrange** [comment]
> 是折叠起来了，但是后面内容变了所以要保持展开。

你是对的，我看了视频，第二次尝试的时候，确实是把那个按钮打开了。

我现在再进行尝试的时候，没再出现这种状况。

但是我看了最开始发的那个视频，那时候保持折叠的按钮是没有点的

**Comment by QQQOrange** [comment]
> 这个得排除插件或者主题影响。

关闭主题和插件后没有再出现了，但不知道原因，如果再次发生的话，我再来挖坟
