### ISSUE TITLE
*(* 无法正常显示

### ISSUE THREAD

**Issue by Xiaobaishushu25** [siyuan-note/siyuan#10404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

输入 *(* 会自动渲染成一个斜的括号

### Expected result

正常显示*(*

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/76581880/88851705-9f3c-4730-9c29-7e65b4d888d6)

### Version environment

```markdown
- Version: 2.12.7
- Operating System:  windows10
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
请使用 `\` 转义 `*`，即 `\*(\*`。
