### ISSUE TITLE
在文档没有任何属性的时候，在属性位置留有图标，点击后能够快速编辑属性

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10402]
### In what scenarios do you need this feature?

现在如果想要给一篇没有任何额外属性的文档添加属性的话，非常麻烦

但是如果给这篇文章添加一个属性之后，会在文章标题右上角多出相关的内容，点击能够修改属性

希望给文章第一次添加属性的过程更加简易一点

### Describe the optimal solution

在文章没有任何属性的时候，给显示属性的位置添加一个按钮，点击后能够快速的编辑属性

**Comment by 88250** [comment]
你指的属性是自定义属性吗？

**Comment by QQQOrange** [comment]
> 你指的属性是自定义属性吗？

自定义属性什么意思我不太懂，大概就是 control 加 art 加 a 换起来的那个页面输入东西后会在标题的右上角出现相应的数据，在没东西的时候，那里点击也能够换出属性页面

**Comment by 88250** [comment]
默认应该没有 Ctrl+Alt+A 这个快捷键，麻烦截图看下吧。

**Comment by QQQOrange** [comment]
> 默认应该没有 Ctrl+Alt+A 这个快捷键，麻烦截图看下吧。

有的
![image](https://github.com/siyuan-note/siyuan/assets/62794181/ecfc985b-3f8e-4f80-9545-e32725a95aab)

**Comment by QQQOrange** [comment]
> 哦，我记错了抱歉，确实有，这个快捷键是唤出属性面板的。已经有快捷键唤出了，还有哪里不方便的吗？

老哥，我说半天，你是一点没记着啊。

在属性面板里面输入任何东西，然后这个东西就会呈现在文档的标题右上角，点击之后就能够不通过快捷键而唤出这个页面。

但是如果属性面板里啥都没有的话，想编辑，要么按快捷键，要么就得通过鼠标慢慢点，

能不能在那个位置，哪怕没输东西，也没有任何东西的时候，也能有一个按钮，点击后直接唤起属性面板

**Comment by 88250** [comment]
如果一直存在属性（命名/别名/备注/书签）角标的话有两个问题：

1. 无法区别是否有属性
2. 所有块都会有角标，极度干扰视角

这样设计不是那么合理就不考虑了，感谢反馈。

**Comment by QQQOrange** [comment]
> 如果一直存在属性（命名/别名/备注/书签）角标的话有两个问题：
> 
> 1. 无法区别是否有属性
> 2. 所有块都会有角标，极度干扰视角
> 
> 这样设计不是那么合理就不考虑了，感谢反馈。

主要是看到标题，那里不是有个添加标签的按钮吗？能在那旁边放一个吗
