### ISSUE TITLE
Support importing data from CSV to the database

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#10405]
希望数据库增加导入功能

### In what scenarios do you need this feature?

一个一个打太慢了也不能批量复制贴贴，特别麻烦

### Describe the optimal solution

1. 增加一个导入CSV的功能
2. 可以将普通表格转换为数据库表格

类似于Obsidian 的 DataLoom 插件也可以
![image](https://github.com/siyuan-note/siyuan/assets/72399630/670d76a5-0888-48a3-9724-ebf050fcda15)

**Comment by 88250** [comment]
第二点暂时不考虑了，感谢提议。

**Comment by shuojie819** [comment]
> 第二点暂时不考虑了，感谢提议。

好的👌，拥有一种方式也就足够用了。

**Comment by AvoidantPerDis** [comment]
支持

**Comment by KrzysztofChrisMaciejczuk** [comment]
Is this features already released? Where do I find it? I wish to import a CSV file into SiYuan as a database table. Thank you.

**Comment by shuojie819** [comment]
> Is this features already released? Where do I find it? I wish to import a CSV file into SiYuan as a database table. Thank you.

导入CSV的功能还没有发布，但是现在已经支持从Excel中复制了（你可以使用Excel打开CSV文件，再复制到数据库表格中）
The CSV import feature has not been released yet, but now it is supported to copy from Excel (you can open the CSV file with Excel and then copy it into the database table).

**Comment by KrzysztofChrisMaciejczuk** [comment]
Ok, thanks! That helps a lot.

Though as I understand - I first need to create enough space for the data I am copying, is that correct?
Is there a workaround, if I have 590 rows to copy?
Is there a planned date for releasing CSV/Excel import?
Thank you!

**Comment by shuojie819** [comment]
> Ok, thanks! That helps a lot.
> 
> Though as I understand - I first need to create enough space for the data I am copying, is that correct? Is there a workaround, if I have 590 rows to copy? Perhaps I could use API to make SQL insert to the table? Is there a planned date for releasing CSV/Excel import? Thank you!

你可以批量插入空行后进行粘贴。
You can insert blank lines in bulk and then paste afterwards.
![image](https://github.com/siyuan-note/siyuan/assets/72399630/514d5caa-bf03-421e-8190-f38f02b7e04b)

**Comment by 88250** [comment]
这个不考虑，就用 Excel 中转拷贝一下吧。

**Comment by pongfcnkl** [comment]
docker网页版和安卓版好像没法复制进去
