### ISSUE TITLE
提高大纲的反应速度

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10407]
### In what scenarios do you need this feature?

在一篇文章中，设定好标题之后，通常要两秒左右，大纲里才会显示出新的标题。

或者说对现有的标题做出任何的修改，大纲要两秒左右才会反应过来

### Describe the optimal solution

希望能够即时的反应

作用在于能够快速的审视自己大纲的层级、自己大纲的内容在整体的一个位置和作用

**Comment by 88250** [comment]
现在的速度已经是优化后的了，暂时找不到更优的实现方案了，感谢反馈。

**Comment by QQQOrange** [comment]
> 现在的速度已经是优化后的了，暂时找不到更优的实现方案了，感谢反馈。

好吧，谢谢老哥
