### ISSUE TITLE
表格内 Tab 键切换单元格问题

### ISSUE THREAD

**Issue by oslog** [siyuan-note/siyuan#1040]
1. 双击全选某单元格的文字，按下快捷键（如删除线command+d），表格变成了markdown代码；
2. 编辑完某单元格后，按下Tab键应跳转到下一个单元格，但实际情况是在当前单元格加了空Tab；
3. 表格各单元格中全部是英数时，表格会被撑开，有中文时会换行（应该是主题的问题）;

* 版本 Version：0.5.9
* 操作系统 Operating system：mac os

**Comment by 88250** [comment]
你好，第一个问题我这里重现不了 
![issue](https://user-images.githubusercontent.com/873584/104405263-82ee2580-5597-11eb-89a4-3e18147eea39.gif)

第二个问题稍后我们看下，谢谢。
