### ISSUE TITLE
快捷键冲突时没有弹出提示

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

换出属性的快捷键是 ctrl 加 alt 加 a 这与 QQ 的截图快捷键是重合的。因此在后台挂 QQ 的时候，按下这个快捷键会直接出现 QQ 的截图功能，并且思源不会展现出属性。

但是这时候思源没有弹出提示

### Expected result

希望在与其他软件快捷键发生冲突的时候，能够弹出提示

### Version environment

```markdown
- Version: 3.0
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个探测不到的，感谢反馈。
