### ISSUE TITLE
支持同步思源客户端设置

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#10410]
### In what scenarios do you need this feature?

出于一些需要，经常会重装电脑，此时再安装思源，需要再重新设置一遍设置。所以希望能够简化这个过程，将客户端设置也同步到云端存储服务中。

### Describe the optimal solution

支持将客户端设置同步到云端存储服务中

### Other information

比如VSCode提供的设置同步功能，就是一个很好的实例，完全避免了重装系统或者换电脑时迁移客户端设置的麻烦

**Comment by 88250** [comment]
这个涉及到密钥同步，处于安全性考虑所以不支持。

如果是 S3/WebDAV 的话，可以使用导出/导入设置功能，感谢反馈。

**Comment by cesaryuan** [comment]
> 这个涉及到密钥同步，处于安全性考虑所以不支持。

密钥可以不同步呀，密钥设置为唯一不同步的设置项，然后通过密钥实现端到端加密的客户端设置同步

**Comment by 88250** [comment]
配置项暂时不考虑同步，因为很多配置项可能无法跨平台。

**Comment by cesaryuan** [comment]
> 配置项暂时不考虑同步，因为很多配置项可能无法跨平台。

那有没有可能提供一个导出和导入设置为本地文件的选项呢

**Comment by 88250** [comment]
主要就是因为有的配置项无法跨平台，所以提供不了。

**Comment by cesaryuan** [comment]
> 主要就是因为有的配置项无法跨平台，所以提供不了。

那目前要在不同的客户端间保证配置一样的话，只能一个一个的打开多达13个设置tab进行手动调整吗？

**Comment by WangCaoMing** [comment]
是不是可以分端进行同步，比如mac上的设置就同步为conf.mac.json, 安卓上的设置就同步为conf.android.json，这样既可以避免设置无法跨平台的问题，又可以实现客户端设置的同步。
