### ISSUE TITLE
Feature Request: Implement Efficient Workspace Switching with Global Search Functionality

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10418]
### In what scenarios do you need this feature?

The idea is inspired by the Arc browser's concept of "spaces." The goal is to enhance the current workspace functionality in SiYuan by allowing users to switch between different spaces (workspaces) using keyboard shortcuts, without opening a new instance of the application for each workspace. This approach aims to streamline the user experience and improve efficiency.

Problem:
Currently, switching between workspaces in SiYuan (similar to vaults in Obsidian) requires opening a new instance of the application for each workspace. This method is not only resource-intensive but also disrupts the workflow by cluttering the desktop with multiple application windows.

### Describe the optimal solution

**Proposed Solution:**
Introduce a "spaces" feature that allows users to:
- Switch between different spaces using predefined keyboard shortcuts.
- Perform global searches across all spaces without the need to switch contexts manually.

**Benefits:**
- Enhanced user experience by reducing the need to manage multiple application instances.
- Improved productivity through quick and easy access to different workspaces.
- Streamlined workflow with the ability to search across all spaces, making information retrieval more efficient.

**Additional Notes:**
This feature request is inspired by the functionality observed in the Arc browser, tailored to fit the context of note-taking and workspace management in SiYuan.

**Comment by 88250** [comment]
The existing structure is not considered to be changed. Thanks for the suggestion.

**Comment by MrIntellectX** [comment]
No problem, I'm a dev too, and I understand. I just wanted to share my thoughts on that.
