### ISSUE TITLE
Video Link Widget Fails to Process Video URLs

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

After providing the YouTube video URL, the widget appears to start processing the URL, but then nothing happens. No error message is displayed, and the video does not load.

### Expected result

The widget processes the URL and displays the video.

### Screenshot or screen recording presentation

![SiYuan_9I60JgpJoF](https://github.com/siyuan-note/siyuan/assets/36538038/0ba04bb8-83a7-4c40-bbed-381cb1cd71a5)

### Version environment

```markdown
- Version: 3.0.0
- Operating System: Windows 11 Pro
- Browser (if used): No
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14390750/siyuan.log)

### More information

I've tried a local video from assets, and it's working, but URL videos are not.

**Comment by 88250** [comment]
Please try to load it using IFrame block.

**Comment by MrIntellectX** [comment]
While iframes do work well, they don't look great for video purposes. I hope you understand what I mean.

![SiYuan_ZihfUl1tly](https://github.com/siyuan-note/siyuan/assets/36538038/60c75dcb-1c6b-41ef-9a2c-cef49443900c)

**Comment by 88250** [comment]
IFrame probably can only do this. As for the Video block, the existing design remains unchanged for the time being. Thank you for your understanding.

**Comment by rishacha** [comment]
@UsmanTechJive @88250  - I propose a solution, can I try and raise a PR for this? 

If it's a youtube video, to make it easily renderable and previewable, all we need to do is add parsing to the youtube link and then switch to an iFrame block 

## Solution

Given a URL like this - `https://www.youtube.com/watch?v=AaZ_RSt0KP8&t=45s`
Convert it to an embedded URL like this - https://www.youtube.com/embed/AaZ_RSt0KP8

And place this in an iFrame. It works fine - 
<img width="898" alt="image" src="https://github.com/user-attachments/assets/c1c8e1ba-07e4-4aae-aa77-eda8f926e8e1">

Please let me know if I can add an option like this to the UI. Thanks.
