### ISSUE TITLE
Feature Request: Add Currency Field with Calculation Support to Database

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10416]
### In what scenarios do you need this feature?

I would like to request a new feature, a currency field in the database that supports all global currencies and can perform calculations.

### Describe the optimal solution

The optimal solution would involve implementing a dedicated currency field type in the database that:

- Supports all global currencies (ISO 4217 codes).
- Automatically handles currency conversion based on real-time or periodically updated exchange rates.
- Allows for basic arithmetic operations (addition, subtraction, multiplication, division) directly within the field.

**Comment by 88250** [comment]
Please use number fields to format the currency. The exchange rate cannot be calculated. Thanks for the suggestion.

**Comment by MrIntellectX** [comment]
Currently, this is what I'm doing, but I would appreciate it if you could implement this. This is what I meant.

![notion_vip__format_database_numbers](https://github.com/siyuan-note/siyuan/assets/36538038/6cc2962a-f732-4c36-845e-e6f39bac1b51)
