### ISSUE TITLE
Carousel Slider in Siyuan

### ISSUE THREAD

**Issue by amatya-aditya** [siyuan-note/siyuan#10412]
### In what scenarios do you need this feature?

To display multiple images in a single space, and swipe through them horizontally. 
To group similar images together, save space, and make your notes more organized and attractive.

### Describe the optimal solution

Create an image slider with thumbnails, next and previous button as shown in the image and video below.

![image](https://github.com/siyuan-note/siyuan/assets/63241408/86eba8bf-8cad-49a7-9e50-e34b917baf7d)

[Image Slider](https://www.youtube.com/watch?v=4K93y2C2Mbo)
https://github.com/vertis/obsidian-image-layouts/blob/main/docs/carousel-with-thumbnails.jpg

**Comment by 88250** [comment]
This should be possible through plugins or widgets. The native implementation is not considered for the time being. Thanks for the suggestion.
