### ISSUE TITLE
不能将\替换为无

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

[3.1.1 一、马克思和恩格斯同形形色色的机会主义的斗争.sy.zip](https://github.com/siyuan-note/siyuan/files/14391303/3.1.1.sy.zip)
搜索\能搜出来，但是替换不了

### Expected result

希望能替换

### Version environment

```markdown
- Version: 3.0
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
作为转义符时 `\` 不能被替换掉，否则会影响原有元素，导致破坏笔记结构；作为单个符号的话可以被替换。

**Comment by QQQOrange** [comment]
> 作为转义符时 `\` 不能被替换掉，否则会影响原有元素，导致破坏笔记结构；作为单个符号的话可以被替换。

作为单个符号的话，不可以被替换。

以我的实验是这样的，

你可以打开我那个文档搜索这个符号后替换来看看

**Comment by 88250** [comment]
我看了的，你的文档是作为转义符，转义了 `<`

**Comment by QQQOrange** [comment]
> 我看了的，你的文档是作为转义符，转义了 `<`

我把<替换为单书名号〈后再替换的/ 这还属于转义符的吗

**Comment by 88250** [comment]
替换不掉的话是属于转义符。

**Comment by QQQOrange** [comment]
> 替换不掉的话是属于转义符。

像这种不能替换的，能不能在点替换的时候弹一个窗口说不能替换呢。

不然一下替换2000多个，跑完五六分钟，结果点进去一看，没被替换
