### ISSUE TITLE
Enhancement Request: Implement GitHub-Style Visual Tags for Improved Usability

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10428]
### In what scenarios do you need this feature?

I'm wondering if we could have tags similar to those on GitHub. Users often navigate and organize their notes using tags. A visually appealing and easily identifiable tag system, similar to GitHub's rounded, modern tags, would enhance user experience by making tags more noticeable and easier to manage at a glance.

![Arc_E3bWz2U5Dl](https://github.com/siyuan-note/siyuan/assets/36538038/eddaa892-db54-4d8e-bffa-17f0b738e59b)

### Describe the optimal solution

- The ability to assign colors to tags for visual distinction.
- Optional icon assignment to tags for further visual cues and quicker identification.
- When a user hovers over a tag, it should also display an option to remove the tag by clicking on a close icon.
- A simple UI for tag management (creation, modification, deletion) that supports the above features.

**Comment by 88250** [comment]
Hello, this is not considered to be changed. If necessary, please specify different tag colors through CSS.

**Comment by MrIntellectX** [comment]
That's okay, but if possible, can't we get color options on normal tags like we have in the table, as shown in the picture below?

![SiYuan_4URe2oNyYj](https://github.com/siyuan-note/siyuan/assets/36538038/4d390888-e922-40b2-92a8-dc93e74c9f4c)

I would appreciate it if we could have those color options in this menu as well.

![GtPrd0P5ZS](https://github.com/siyuan-note/siyuan/assets/36538038/3d8c2659-ee80-45b6-9c29-faa2e3a14fc7)

**Comment by 88250** [comment]
This value can only be specified through CSS, and the interface cannot provide support, sorry.
