### ISSUE TITLE
Issues with Excelidraw Plugin: Mode State Saving, Data Loss, and Language Barrier

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The Excelidraw plugin in SiYuan is facing several issues:
- It does not save the state between dark mode and light mode upon restarting the app.
- Occasional data loss occurs, specifically with pictures.
- The plugin interface is entirely in Chinese, making it difficult for non-Chinese speakers to use.
- The overall experience does not feel as integrated and native as the highly optimized Excelidraw plugin in Obsidian.
- There is a lack of a feature to utilize note data within Excelidraw.

### Expected result

- The plugin should remember the last used mode (dark/light) and maintain this state.
- No data loss should occur, ensuring all inserted pictures, data, and drawings are saved correctly.
- An English version of the interface, or multi-language support, should be provided for broader accessibility.
- The plugin should feel as integrated and native to SiYuan as possible, similar to its implementation in Obsidian.
- A feature should be implemented to allow the utilization of note data within Excelidraw, enhancing its functionality and integration with SiYuan notes.

### Version environment

```markdown
- Version: 3.0.0
- Operating System: Windows 11 Pro
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14392257/siyuan.log)

**Comment by 88250** [comment]
Hello, please give feedback on the plugin repository issues, thank you.

**Comment by MrIntellectX** [comment]
Got it, thanks.

**Comment by MrIntellectX** [comment]
I apologize, but I'm unable to locate the plugin repository. Could you please assist me?

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/44a043ea-fc07-437d-bcc0-3dd80e849494)

**Comment by luo-chuan** [comment]
https://github.com/zuoez02/siyuan-plugin-excalidraw
