### ISSUE TITLE
Request for English Documentation for Plugin Development

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10429]
### In what scenarios do you need this feature?

I've facing challenges with the limited English documentation, especially for developing plugins, themes, and widgets. This makes it hard for non-Chinese speakers like me to fully use and contribute to Siyuan.

### Describe the optimal solution

Could you please provide more detailed English documentation, especially for plugin, theme, and widget development? This would greatly help a worldwide audience and encourage more people to participate.

If such documentation already exists and I've missed it, please let me know. Currently, SiYuan seems to be behind Obsidian in terms of plugin support. However, I am optimistic that with comprehensive documentation, we can quickly achieve a comparable pace of plugin availability in the marketplace.

Thank you for looking into this request.

### Other information

I was trying to implement AnyType bottom navigation bar to explore how plugins can be built and work, purely for testing purposes. However, I'm struggling to find a way to call a function to push or pop navigation.

![Ret72c2P9L](https://github.com/siyuan-note/siyuan/assets/36538038/cf0a5409-b81e-4472-8597-d664c3e39c91)

**Comment by suka233** [comment]
Here is some samples: https://github.com/siyuan-note/bazaar/blob/main/README.md
and API: https://github.com/siyuan-note/siyuan/blob/master/API.md

There are many APIs not listed in the documentation. You can take a look at the Go language source code, where all the APIs are located:
[https://github.com/siyuan-note/siyuan/blob/master/kernel/api/router.go](https://github.com/siyuan-note/siyuan/blob/master/kernel/api/router.go)

And this: https://docs.siyuan-note.club/en/

This document does not have an English version, but you can use Google Translate to get a rough understanding of the database design and fields: https://www.yuque.com/siyuannote/docs/go7uom?utm_source=ld246.com

Lastly, you can check the GitHub repositories of most plugins and widgets in the marketplace, as many of them are open source.

**Comment by MrIntellectX** [comment]
Thanks for the resources! I'll dive into the docs, API, and source code to get a better grasp of the project. If I have further questions, I'll reach out. Appreciate your help!

**Comment by MrIntellectX** [comment]
I've checked the resources, but I'm not able to figure out how I can implement this navigation in the plugin. I would appreciate any help.

![SiYuan_eM3wrA2Xln](https://github.com/siyuan-note/siyuan/assets/36538038/a916e9b3-712a-428a-b316-2d8573f23f8b)

**Comment by mozhux** [comment]
sy-plugin-enhance
This plugin has achieved a similar effect on the mobile end. Perhaps you can go to its GitHub to learn more about it

**Comment by MrIntellectX** [comment]
Sure, will check out the sy-plugin-enhance. Thanks!
