### ISSUE TITLE
jan.ai集成、闪卡语音交互、迁移的三个重要革新功能建议

### ISSUE THREAD

**Issue by msjsc001** [siyuan-note/siyuan#10424]
---
思源的开发者你们好，我想到了可以给思源注入更多活力的三个重要实用功能建议。这三个功能和思源很好的融合后相信思源会更受笔记用户的欢迎，而且加强了思源不可替代的独创唯一性。未来的笔记会是往AI的功能走，看谁先做，希望思源的开发者们能重视。

---
### **jan.ai** 
![image](https://github.com/siyuan-note/siyuan/assets/93178788/f2e290f2-ce35-4095-88ff-50aa4a7abd89)
 jan.ai 是一款傻瓜式的AI模型聊天UI工具，界面颜值较高很傻瓜好用，思源和它集成将会有离线AI的领先优势，现在还没有1款软件有离线AI功能！未来能和自己的笔记聊天，利用聊天界面操作思源会是很不一样的笔记体验。

建议思源抢先和 jan.ai 进行集成（ https://jan.ai/guides/integrations/ ），非常有利于思源未来的**离线AI功能的拓展**（比如做知识库能**和自己笔记聊天**将会给思源笔记灵魂，离线AI也能保证隐私，相信很多使用离线笔记的用户使用思源的用户都会很喜欢**和自己笔记离线聊天**方式。 ），现在笔记上只有VS Code 这个说不上笔记的笔记软件和 jan.ai 集成（ https://star-history.com/#siyuan-note/siyuan&janhq/jan&Date ）。

jan.ai 的 star 就像火箭起飞如果集成 jan.ai 思源在传播上也有优势能被 jan.ai 带上，**现在还没1款笔记软件与 jan.ai 集成过**，最重要的就是思源用户能轻松的用上大量不同的离线模型。我对比过很多AI的UI界面工具它可以说是最易用最有潜力的。

现在在llm.extractum.io上评分超过70的基本幻觉都比较小了，而且离线模型每天还在迭代我想思源集成未 jan.ai 后会是很后前途的，也相当于思源把离线AI的这块**免费交给了一个比较好的团队**上，未来都不用自己太耗时耗力开发。

集成AI后未来更高级的操作思源可以像 https://www.pdfgear.com/zh/ 一样**用聊天直接操作思源**，这一定是未来笔记能具备的功能，思源做到后又算是一个领先。

---
### **闪卡语音交互**
添加语音交互功能，能解放双手！**记忆软件圈子现在缺的不是功能，而是AI交互解放双手，现在没现在还没有1款记忆软件闪卡软件有这样的功能！**
最简单的语音交互插件可以是在 "显示答案 "后对几个选项进行语音交互，这样我们就不用频繁地按键盘或触碰手机屏幕来完成闪卡的复习。

更高级的是让卡片自动朗读后 "显示答案"，显示答案后用语音交互选择几个需要手选的选项，这样我们在运动、散步、泡澡、闭目养神时都可以不依赖屏幕进行复习。

更高级的可以是 AI 语音问答互动（这部分可能要结合离线AI或在线AI功能才能实现），这样就更解放双手了！

---
### **迁移**
笔记这圈子实际就那么些人，笔记软件火了那么几年到现在更多人是**陷在A笔记里迁移不到B笔记**。用户在A笔记软件的笔记量到几百个页面以上只要和B笔记数据不通就几乎不能迁移，想用B笔记就用不了，长时间记笔记的用户群体基本都会在上千页面，想换软件的阻碍就很大，再怎么宣传这部分人有强烈意愿想用思源也都迁移不来思源。

建议思源开发者，安排时间，支持下其它几款主流笔记软件无损迁移到思源的迁入功能，可以按它们使用人数多少来决定先支持谁，我想大多迁移主要想保留的都是双链的块、嵌入块这些，
![image](https://github.com/siyuan-note/siyuan/assets/93178788/612cf4ff-5ea2-4497-a181-f867fbe84659)
我截个RemNote 做的迁入的图给D大参考下，RemNote 的迁入就做的很好，但它的笔记方式功能和思源是不一样的，功能上也不符合需要思源的人的需求。

**Comment by zxhd863943427** [comment]
这个的主要问题是太大了。

**Comment by luo-chuan** [comment]
迁移可能有点难做，性价比不一定高。其实瞄准增量用户也挺好的，比如学生群体。
我在别的软件上也有笔记，就让它们留着呗，也懒得迁移，反正新的笔记我都放在思源里。

**Comment by luo-chuan** [comment]
说下我如何使用AI，很简单，直接网页版chatgpt，不花钱，不折腾。

**Comment by msjsc001** [comment]
> 这个的主要问题是太大了。

是的，算是三个大功能，也特别符合现阶段的笔记趋势潮流，

AI是未来笔记软件趋势，现在不做未来的笔记大部分必然也会内置做到，只是思源做到有一个先机，可能会带来些流量上的好处。**喜欢AI功能的用户也会被吸引到思源来。**

闪卡AI语音交互复习，市面上也是几乎没有这样的软件，做的好**anki的用户群吸引过来**。

迁移嘛就是笔记圈子已有的大积数的**老用户吸到思源来**。

我个人认为，思源只要把这三点融合好做好，未来5年在笔记圈会是流量大头。

**Comment by msjsc001** [comment]
补充一下，闪卡的语音交互 主要带来的是“**娱乐沉浸式的学习复习体验**”这是前所未有的。解放双手是附带，如果做好了思源可能成为未来ANKI的替代品！（anki的人群量是相当大的）

**Comment by msjsc001** [comment]
补充2：知识库，就像比较强的一个克隆全能人一样，对话起来相当有意思的。我用《学会提问》这本书做GPT4的例子演示在下图，也是是思源能实现离线or在线模型笔记做为知识库给AI，也会是这种效果。
![P7S9W5WC%RIQTVSZVI) @{N](https://github.com/siyuan-note/siyuan/assets/93178788/a7bf2cba-9aa7-4dbf-947c-98e56449361f)
![(O93{U77BRV2%XVA41_@DZ7](https://github.com/siyuan-note/siyuan/assets/93178788/f4676584-76b1-434d-aca1-6bfa3af7d0e5)

**Comment by msjsc001** [comment]
猴哥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月24日(星期六) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] jan.ai集成、闪卡语音交互、迁移的三个重要革新功能建议 (Issue #10424)





 
非常支持，特别是迁移的功能，能够快速从其他软件上面没有压力转移笔记数据

**Comment by 88250** [comment]
1 和 2 基于 AI 来做技术上是可行的，但是本地 AI 的话目前难度较大，还需要时间观望。3 目前不考虑了，因为没有时间精力开发。

思源是完全开源的，期待社区开发者可以帮忙完成 AI 相关插件以及数据导入/导出程序。

感谢反馈！
