### ISSUE TITLE
支持在文档顶部管理数据库属性

### ISSUE THREAD

**Issue by aleegreat** [siyuan-note/siyuan#10425]
【功能请求】请求在正文中展示块属性或文档属性，而不需要通过右键查看

### In what scenarios do you need this feature?

目前块属性只能通过右键查看、编辑，在使用方面很不方便，操作步骤比较繁琐。
另外，目前模板只支持块级别属性，不能通过模板设置文档级别属性，希望这方面也能完善。

### Describe the optimal solution

希望思源能支持类似Logseq的文档属性功能，在文档界面就可以方便的查看、编辑 文档属性或块属性 。

谢谢谢谢

![image](https://github.com/siyuan-note/siyuan/assets/14324428/975acef7-f91a-40e6-bfc1-26e1fa26c629)

**Comment by 88250** [comment]
文档的属性社区应该是有插件实现了（或者正在实现）；其他块的属性建议还是通过属性面板，否则会对正文形成较大干扰。

模板文档块属性的需求是需要创建日记的时候使用吗？

**Comment by aleegreat** [comment]
谢谢D大回复。

文档属性不仅仅是创建日记使用，包括读书、工作中需求、项目记录等高频率记录笔记的场景中都有使用。如果能模板能支持，确实能提供较大便利。

另外，我还是想请您再认真考虑一下 块的属性在正文中显示/编辑这个功能（或者只显示用户自定义的属性，不显示内置属性），可以提供一个开关由用户决定是否启用（如果可行的话）。 
理由如下：
    1. 用户自定义的属性本身就是用户关注的信息，对正文的干扰确实存在，但可以通过CSS样式来减轻或上述功能开关来消除。
    2. 相对目前的操作步骤，文档中支持自定义属性的快捷查看、编辑功能，不会打断记录思路，能保持记录流畅性，同时其操作便捷性也带来很大改善。 

在此，请D大务必再考虑，我再次万分感谢~

**Comment by 88250** [comment]
目前只有创建日记的时候才能使用模板，所以估计只能在日记模板上支持了。

文档属性编辑目前不考虑改变了，谢谢。

**Comment by aleegreat** [comment]
好的，尊重您的决定。 希望未来有一天能你能重新审视这个功能请求并实现，感谢感谢。

**Comment by luo-chuan** [comment]
很好的建议

**Comment by 397334469** [comment]
支持+1

**Comment by Achuan-2** [comment]
其实现在发现点击数据库图标管理也挺方便的，也适合一个文档放多个数据库
![Clip_2024-02-28_10-08-47](https://github.com/siyuan-note/siyuan/assets/60436214/303d8aaf-3255-488a-b91a-99ccb1414e91)
