### ISSUE TITLE
Add internal kernel API `/api/riff/batchSetRiffCardsDueTime`

### ISSUE THREAD

**Issue by suka233** [siyuan-note/siyuan#10423]
### In what scenarios do you need this feature?

请求新增API：设置闪卡到期时间

### Describe the optimal solution

前端可能的调用方式：
`batchSetRiffDate( [ {id ,date} ] : IBatchSetRiffDate[] )`

```ts
interface IBatchSetRiffDate {
  id: string;
  // YYYYMMDDhhmmss
  date: string;
}
```

这里我有一点疑惑，就是闪卡的到期时间有1分钟，5分钟，10分钟这样的，如果手动把这张闪卡的到期日设置为11分钟后，会扰乱FSRS算法对于这张卡的安排么？

**Comment by suka233** [comment]
>这里我有一点疑惑，就是闪卡的到期时间有1分钟，5分钟，10分钟这样的，如果手动把这张闪卡的到期日设置为11分钟后，会扰乱FSRS算法对于这张卡的安排么？


@L-M-Sherlock 请教一下叶佬

**Comment by zxhd863943427** [comment]
从储存的结构来说会，目前我的思路是提前复习而非修改到期时间。

**Comment by L-M-Sherlock** [comment]
不会扰乱

**Comment by zxhd863943427** [comment]
发现自己看错了……@L-M-Sherlock 所以叶佬修改到期时间是直接改due么？

**Comment by 88250** [comment]
`http://127.0.0.1:6806/api/riff/batchSetRiffCardsDueTime`

```json
{
    "cardDues": [
        {
            "id": "20240118200836-wr0eg52",
            "due": "20240224214400"
        },
        {
            "id": "20240118200836-qsoo1fu",
            "due": "20240224214412"
        }
    ]
}
```
