### ISSUE TITLE
块级的反向链接和提及

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1042]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在进行随便化的记录或者思考时，比如日记中记录某些灵感时，需要实时反馈一些反链和提及功能，有助于我们将已有的知识串起来，现在的反向链接和提及都是文档级的，无法在实时输入时帮助我们进行思考。

### 描述最优的解决方案 Describe the optimal solution
![image](https://user-images.githubusercontent.com/37007969/104425713-f6099300-55bb-11eb-9841-ff5f8c090ef8.png)
可以尝试通过单击引用的双向链接，实现右侧展示反向链接和提及；通过ctrl+单击实现跳转；点击标题，或者空白处，则展示文档级的双向链接。

**Comment by 88250** [comment]
你好，反链目前已经是块级的，只是没有上下文关系，上下文关系改进请关注 #295 ，谢谢。
