### ISSUE TITLE
支持 High contrast代码块主题

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1043]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
暗黑模式下支持 High contrast代码块主题
![image](https://user-images.githubusercontent.com/69628966/104429490-a083b500-55c0-11eb-84e5-42dbae05d1f8.png)

**Comment by Vanessa219** [comment]
思源对代码块已经内置 98 个主题了，欢迎挑选你喜欢的，或者直接提供 css 代码也是可以的。
