### ISSUE TITLE
移动端闪卡支持手势

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10439]
### In what scenarios do you need this feature?

在移动端刷闪卡的话会出现一些问题。例如用右手刷卡的话，那么最左边的按钮会难以按到

如果能够支持手势的话就能够设置往左滑点重来，往右滑回答良好，往上滑回答简单等等

操作也更加直观，也不用担心误触

### Describe the optimal solution

移动端支持手势

**Comment by 88250** [comment]
感谢提议，但不考虑了，因为容易误触且手势不够用。

**Comment by QQQOrange** [comment]
> 感谢提议，但不考虑了，因为容易误触且手势不够用。

误触的话。不用担心，anki移动端用这么多年也没看到有几个反馈说误触

要是觉得手势不够用，那就搞一个悬浮球专门用来刷卡的。按住悬浮球上下滑来回答案例。

**Comment by luo-chuan** [comment]
有趣的想法，未来可以继续讨论
