### ISSUE TITLE
在文档树当中使用CTRL+↑是否可以不要全部折叠而只折叠到当前笔记的上一层目录

### ISSUE THREAD

**Issue by johnnyqko0124** [siyuan-note/siyuan#10434]
### In what scenarios do you need this feature?

我在使用文档树的时候有时会需要跳转到其他的笔记或是到上一层的目录结构，而全部折叠会导致我需要再次点击好几下才能打开到我想要的目录结构，或是我直接使用搜索跳转到该目录笔记，但我有时会忘记该笔记的名字

### Describe the optimal solution

如果可以在文档树设定成CTRL+↑只收缩一层目录，而如果想多收缩几层就多按几下CTRL+↑似乎会比较便捷?
同理，是否可以多设定个快捷键CTRL+↓为展开?

**Comment by 88250** [comment]
你好，文档树的折叠功能是全部折叠，这样才能方便将多余展开的文档进行折叠。

文档树的全部展开请关注 #2577
