### ISSUE TITLE
闪卡的自动延期功能

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10436]
### In what scenarios do you need this feature?

这个功能的主要作用在于，例如我今天要复习500张卡，但是因为日常的事情让自己最多只复习了300张，或者说干脆就没复习，可能这500张卡跟第二天的卡片一起复习，复习量可能会增加到800张。如果连续几天都在忙的话，那么复习量可能会变成好几千张，最后会造成一个非常非常严重的闪卡堆积问题

如果有自动延期的功能的话，到第二天第一次打开软件的时候，能够自动计算昨天有多少张卡片在复习，然后给它分散到接下来的好几天当中，让接下来的一段时间复习压力没有那么大

### Describe the optimal solution

能够有自动延期的功能

自动延期的功能，它本质上只是减缓闪卡复习的压力，它仍然会有一定的闪卡堆积，但它会把闪卡堆积的数量压到最少

**Comment by luo-chuan** [comment]
这个要不问问叶神？说不定算法已经考虑到了？

**Comment by QQQOrange** [comment]
> 这个要不问问叶神？说不定算法已经考虑到了？

问过了，实质上并没有

他做的插件里面有这个功能，但是算法里面没有

**Comment by luo-chuan** [comment]
> 问过了，实质上并没有
> 
> 他做的插件里面有这个功能，但是算法里面没有

那个插件有开源地址吗？

**Comment by L-M-Sherlock** [comment]
有推迟功能，但没有做自动推迟。因为自动推迟需要有优先级系统。

**Comment by 88250** [comment]
看各位讨论这个需求比较高阶，我们也暂时不考虑了，谢谢。

**Comment by QQQOrange** [comment]
> 看各位讨论这个需求比较高阶，我们也暂时不考虑了，谢谢。

删除当前闪卡功能不高阶啊。这个为什么不做呢

**Comment by 88250** [comment]
上面讨论的好像是自动延期吧？

**Comment by QQQOrange** [comment]
> 上面讨论的好像是自动延期吧？

上面讨论的是自动延期，我在另一个issue下面问了过后，你没回我。

**Comment by 88250** [comment]
请在那个 issue 下面留言，谢谢。
