### ISSUE TITLE
删除当前闪卡、闪卡优先级功能、闪卡暂停功能

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10437]
### In what scenarios do you need this feature?

目前这三个功能虽然能够通过第三方插件来实现，但第三方插件实现时会有一定的体验问题

例如，删除当前闪卡后，不会自动跳到下一张闪卡，和插件作者沟通后，表明这是插件能做到的极限了，如果能够原生支持，就不会有类似的事情。当然这仅仅是其中的一个例子。

另一个就是关于闪卡的优先级功能，通过相关的插件能够实现闪卡的优先级，但是这功能在手机上支持并没有那么的好，并且批量暂停闪卡功能，因为插件的限制，如果要暂停上千张卡的话，速度非常慢，通常是以10分钟为单位的。如果思源本身能够解决的话，那么无疑会让使用者能有一个更好的体验

### Describe the optimal solution

综上所述，虽然这些功能目前都能通过插件实现，但插件实现的过程并没有那么的完美，并且因为插件本身的限制，体验难以完善。

如果能够原生实现的话，那么会有一个更好的体验，在移动端也会使用的更加舒适

**Comment by 88250** [comment]
* 删除闪卡的话需要在闪卡管理界面操作
* 优先级暂时不考虑了
* 暂停功能 https://github.com/siyuan-note/siyuan/issues/8832

**Comment by QQQOrange** [comment]
> * 删除闪卡的话需要在闪卡管理界面操作
> * 优先级暂时不考虑了
> * 暂停功能 https://github.com/siyuan-note/siyuan/issues/8832

删除闪卡在闪卡管理页面太太牵强了，退出闪卡页面后，精准找到那张卡，并且删除？
就算你能精准的找到。再点击删除。那会不会太麻烦了？
直接在复习页面删不行吗

**Comment by luo-chuan** [comment]
其实在刷卡时，也可以通过直接“点块标 -> 快速制卡”来删除闪卡。

**Comment by luo-chuan** [comment]
删除闪卡，关联：
https://ld246.com/article/1679808702515
https://ld246.com/article/1673100293107

**Comment by QQQOrange** [comment]
> 其实在刷卡时，也可以通过直接“点块标 -> 快速制卡”来删除闪卡。

如果一张卡片里面同时有两个快呢？这种操作原来我用过，但是容易误触。就是当有两个块的时候。可能会把某一个块再次制成卡片。

**Comment by luo-chuan** [comment]
优先级的话，插件作者是如何实现的？采用了怎样的算法或逻辑？

**Comment by IAliceBobI** [comment]
@QQQOrange 

另一个就是关于闪卡的优先级功能，通过相关的插件能够实现闪卡的优先级，但是这功能在手机上支持并没有那么的好，并且批量暂停闪卡功能，因为插件的限制，如果要暂停上千张卡的话，速度非常慢，通常是以10分钟为单位的。如果思源本身能够解决的话，那么无疑会让使用者能有一个更好的体验

====
目前是批量做的。可以试试，应该不慢。

手机支持确实不好。

**Comment by IAliceBobI** [comment]
@luo-chuan 

目前实现比较简单。

优先级数值大的排在复习队列前面，优先复习。少量的低优先级有小概率插入的复习队列前面。

**Comment by QQQOrange** [comment]
> @QQQOrange 
> 
> 另一个就是关于闪卡的优先级功能，通过相关的插件能够实现闪卡的优先级，但是这功能在手机上支持并没有那么的好，并且批量暂停闪卡功能，因为插件的限制，如果要暂停上千张卡的话，速度非常慢，通常是以10分钟为单位的。如果思源本身能够解决的话，那么无疑会让使用者能有一个更好的体验
> 
> ====
> 目前是批量做的。可以试试，应该不慢。
> 
> 手机支持确实不好。
> 
> 
> 

嗷嗷嗷

**Comment by QQQOrange** [comment]
> * 删除闪卡的话需要在闪卡管理界面操作
> * 优先级暂时不考虑了
> * 暂停功能 [Flashcard support suspend #8832](https://github.com/siyuan-note/siyuan/issues/8832)

删除闪卡在闪卡管理页面太太牵强了，退出闪卡页面后，精准找到那张卡，并且删除？
就算你能精准的找到。再点击删除。那会不会太麻烦了？
直接在复习页面删不行吗

**Comment by 88250** [comment]
> 其实在刷卡时，也可以通过直接“点块标 -> 快速制卡”来删除闪卡。

上面已经有人回复过了。

**Comment by QQQOrange** [comment]
> > 其实在刷卡时，也可以通过直接“点块标 -> 快速制卡”来删除闪卡。
> 
> 上面已经有人回复过了。

如果一张卡片里面同时有两个快呢？这种操作原来我用过，但是容易误触。就是当有两个块的时候。可能会把某一个块再次制成卡片。

**Comment by 88250** [comment]
选择好对应的块吧，制卡错了的话再按一次快捷键就删了。

**Comment by QQQOrange** [comment]
> 选择好对应的块吧，制卡错了的话再按一次快捷键就删了。

这误触的概率可不低啊，直接提供一个稳妥的删除选项不可以吗

**Comment by 88250** [comment]
那可以用菜单的。

**Comment by QQQOrange** [comment]
> 那可以用菜单的。

你看视频


https://github.com/siyuan-note/siyuan/assets/62794181/9862a502-2200-41b0-a61b-06fb009efd5b

你说的这种方式，如果在闪卡中编辑了新的内容的话，再点击后就失效了。反而会把新的内容按照块重新创建成若干张卡片

**Comment by QQQOrange** [comment]
> 那可以用菜单的。

而且默认的快捷制卡，还有一个问题

https://github.com/siyuan-note/siyuan/assets/62794181/5f81b29e-5b48-4608-82c7-ab05617fbe1a

如果多选了一行的话，哪怕那一个那一行是空行，他也不会取消制卡，反而会把那一张空行制成卡片

**Comment by 88250** [comment]
> > 那可以用菜单的。
> 
> 你看视频
> 
>  QQ2024226-101343-HD.mp4 
> 你说的这种方式，如果在闪卡中编辑了新的内容的话，再点击后就失效了。反而会把新的内容按照块重新创建成若干张卡片

这是预期行为啊，因为你多选了块。

**Comment by 88250** [comment]
> > 那可以用菜单的。
> 
> 而且默认的快捷制卡，还有一个问题
> 
>  QQ2024226-101712.mp4 
> 如果多选了一行的话，哪怕那一个那一行是空行，他也不会取消制卡，反而会把那一张空行制成卡片

同上。

**Comment by QQQOrange** [comment]
> > > 那可以用菜单的。
> > 
> > 
> > 你看视频
> > QQ2024226-101343-HD.mp4
> > 你说的这种方式，如果在闪卡中编辑了新的内容的话，再点击后就失效了。反而会把新的内容按照块重新创建成若干张卡片
> 
> 这是预期行为啊，因为你多选了块。

那问题是 闪卡添加新的内容之后，这张闪卡之后不想要了，那该怎么删呢

而且这样会不会太不直观了，会不会太不友好

**Comment by 88250** [comment]
直接点闪卡块的菜单制卡就删了，我不知道你指的不直观、不友好是啥问题。

**Comment by luo-chuan** [comment]
是这样的，制卡的逻辑就是一个块对应一张卡。你想在刷卡界面增加新的行的话，建议用软回车。不过看了你的录屏，我觉得应该阻止用户通过鼠标点击下方空白处增加新的块，因为这可能会造成实际效果与用户预期不一致。

**Comment by QQQOrange** [comment]
> 直接点闪卡块的菜单制卡就删了，我不理解你指的不直观、不友好是啥问题。

![image](https://github.com/siyuan-note/siyuan/assets/62794181/ad947ae6-1562-4eae-8145-efb2acb841de)

![image](https://github.com/siyuan-note/siyuan/assets/62794181/6b25af56-9a0d-452d-9cbf-9ca523571fde)

如果不是选中多个块，在菜单里面快捷制卡外，就没有其他方式了

**Comment by luo-chuan** [comment]
感觉是这么个意思。刷卡界面，没有左边的卡片标记（就是那条黄色竖线），无法判断是否成功删除卡片。这里应该：
① 要么显示左边那条黄色竖线
② 要么菜单里根据情况显示为“取消快速制卡”。这里根据情况的意思就是先判断一下选中块是否已被制成卡片。

**Comment by 88250** [comment]
之前考虑过，显示黄线的话太干扰视觉了，因为肯定都是黄线。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月26日(周一) 中午11:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 删除当前闪卡、闪卡优先级功能、闪卡暂停功能 (Issue #10437)




 
感觉是这么个意思。刷卡界面，没有左边的卡片标记（就是那条黄色竖线），无法判断是否成功删除卡片。这里应该：
 ① 要么显示左边那条黄色竖线
 ② 要么菜单里根据情况显示为“取消快速制卡”。这里根据情况的意思就是先判断一下选中块是否已被制成卡片。

**Comment by luo-chuan** [comment]
>  ② 要么菜单里根据情况显示为“取消快速制卡”。这里根据情况的意思就是先判断一下选中块是否已被制成卡片。

这里好像也有点逻辑陷阱。毕竟多选块的时候，有的块已被制成卡片，有的块没被制成卡片，这时候就有点麻烦。
还有种思路，刷卡页面中，没有被制卡的块改变一下显示效果。

**Comment by luo-chuan** [comment]
> ② 要么菜单里根据情况显示为“取消快速制卡”。这里根据情况的意思就是先判断一下选中块是否已被制成卡片。

考虑到多选块，才用这样的逻辑如何？如果选中的多个块中至少存在一个没有被制卡，右键菜单就显示“快速制卡”，否则就显示“取消快速制卡”

**Comment by 88250** [comment]
@Vanessa219 这个菜单逻辑是否可行？

**Comment by QQQOrange** [comment]
> > ② 要么菜单里根据情况显示为“取消快速制卡”。这里根据情况的意思就是先判断一下选中块是否已被制成卡片。
> 
> 考虑到多选块，才用这样的逻辑如何？如果选中的多个块中至少存在一个没有被制卡，右键菜单就显示“快速制卡”，否则就显示“取消快速制卡”

老哥逻辑清晰，完美嘴替，给老哥跪了

**Comment by 88250** [comment]
删除当前闪卡请关注 https://github.com/siyuan-note/siyuan/issues/10452
