### ISSUE TITLE
Improve add menu on the mobile

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10430]
### In what scenarios do you need this feature?

在输入、dailynote等其他场景中，插入图片（含视频）是一个比较常见的场景，但是目前的插入图片按钮太靠后了，建议提前。

详见视频(ios端）

https://github.com/siyuan-note/siyuan/assets/5708881/23571a28-43af-4be2-8e2d-14a8860b09f6

### Describe the optimal solution

目前的插入图片按钮太靠后了，建议提前。

**Comment by suka233** [comment]
支持，确实是一个用着不太爽的点

**Comment by Vanessa219** [comment]
1. 移除其中的行内菜单
2. 插入图片置前
