### ISSUE TITLE
能否设置png的底色为白色

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#10433]
### In what scenarios do you need this feature?

png为透明背景的时候，看不清楚png图片
原图：
![Tz5iAgBh6xNSW3jdQIzSBD5Tb54fc6Q6nuvEkgZPdcM](https://github.com/siyuan-note/siyuan/assets/20038464/d3bd0afd-1b65-4c0d-bbd0-dafb3735047e)

笔记内效果（暗黑模式）：
<img width="635" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/d3eba101-7668-4f8f-bfd4-0cf45d78a043">

期望效果：
<img width="632" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/a4d5d514-c70a-45f0-8da1-bca06f8f3649">

### Describe the optimal solution

系统设置中可以设置png的底色为白色，而不是透明

**Comment by 88250** [comment]
请参考 https://ld246.com/article/1708817814311

**Comment by kylehz** [comment]
```
/* 图片透明通道添加背景色 CSS片段 */
.img img {
  background-color: #f0f0f0; /* 设置背景色，可以根据需要修改颜色值 */
}
```

用这个吗 请问如何设置

**Comment by kylehz** [comment]
谢谢 了解了
