### ISSUE TITLE
当打开大纲功能后，关闭所有文档时一起关闭大纲，打开文档后再打开相应的大纲

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10449]
### In what scenarios do you need this feature?

现在是关闭所有文档之后，大纲只是清空了，但大纲的位置还是在那里，里面一片空白，这个显示就毫无意义

理想情况下，应该是关闭所有文档之后一起关闭大纲，同时打开文档树

当打开某一个文档之后，再关闭文档树 ，打开大纲

### Describe the optimal solution

期待早日补充

**Comment by 88250** [comment]
可以从其他地方（比如搜索）打开文档的，所以大纲最好还是不要自动收起，感谢反馈。

**Comment by QQQOrange** [comment]
> 可以从其他地方（比如搜索）打开文档的，所以大纲最好还是不要自动收起，感谢反馈。

提这个不是为了打开文档，而是现在的这个页面显示的没意义，没有文档的时候显示大纲页面，有这个必要吗

另一点就在于关闭所有文档后，如果想要继续使用思源，那么必然是要打开某一个文档或者新建一个文档，那么关闭所有文档后默认转到文档树既符合直觉，也能减少操作，还能提升体验

不能说可以通过一些繁琐的途径达到目的就行了，用任何软件不都是图一个方便吗

**Comment by 88250** [comment]
关闭了所有文档，但是可能马上就会打开新文档，页签很多的时候这样用很方便。

**Comment by QQQOrange** [comment]
> 关闭了所有文档，但是可能马上就会打开新文档，页签很多的时候这样用很方便。

可以把大纲页面收短，没有大纲内容的时候，大纲页面占了非常多空的地方，可以让文档树显示在它的上面或者下面都可以，例如这样
![image](https://github.com/siyuan-note/siyuan/assets/62794181/70cafeb8-5279-4d44-97a0-5bbac47232a2)
打开一个文档之后，再把文档树隐藏或者这样显示
![image](https://github.com/siyuan-note/siyuan/assets/62794181/567980f0-6103-4efd-8f69-56826c246fe8)

**Comment by 88250** [comment]
@Vanessa219 参考一下。

**Comment by QQQOrange** [comment]
> @Vanessa219 参考一下。

老哥 这个在考虑了吗

**Comment by Vanessa219** [comment]
这个面板的高度是靠拖拽红框中的线而自定义的，不仅作用于大纲，在图中还作用于文档树和收集箱

<img width="287" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/fca4f64b-6e3e-4c74-94cc-8bd38ad93413">
