### ISSUE TITLE
Close the user guide but not the tab when exiting

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10441]
https://ld246.com/article/1708782043043

**Comment by 88250** [comment]
1f22ee3d7e010844c6b61e5eae1363b6de4d3a71

**Comment by TCOTC** [comment]
@88250 话说如果用户打开了用户指南，但在关闭思源前没有关闭文档页面，是不是说明用户想在下次打开思源的时候继续看用户指南？如果每次关闭思源时都自动关闭用户指南的话，在有的情况下用户会有点恼火（比如打开了用户指南的多个文档，但重启思源后却全部关闭了）

关联：#10446
