### ISSUE TITLE
日历功能

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#1044]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
目前点击日记标签点开的是当天的日记
当日记笔记达到一定数量，通过文件树查找定位不方便

### 描述最优的解决方案 Describe the optimal solution

希望支持日历面签，点击对应日期可以打开对应当天的日记
没有那天的日记可选择是否新建，那天没有日记可以在日历面签按颜色区分
这样的好处是今天可以把明天要做的事情提前规划好，以便提高生产力，目前为手动新建明天的日记

**Comment by 88250** [comment]
谢谢提议，后期考虑。

**Comment by PumpkinSin** [comment]
只是跳转到某天日记的话可以用表格吧

**Comment by 88250** [comment]
后面靠插件丰富，先关闭了，谢谢提议。
