### ISSUE TITLE
AI 功能支持百度文心大模型ernie 

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10440]
### In what scenarios do you need this feature?

目前的 AI 功能需要魔法，普通用户使用的话比较困难，但是文心大模型普通用户使用的话相对比较容易，希望能够早日支持

### Describe the optimal solution

早日支持

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/9024
