### ISSUE TITLE
打开用户指南文档时不应该自动关闭用户指南笔记本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10446]
### In what scenarios do you need this feature?

如果用户打开了用户指南，但在关闭思源前没有关闭文档页面，是不是说明用户想在下次打开思源的时候继续看用户指南？如果每次关闭思源时都自动关闭用户指南的话，在有的情况下用户会有点恼火（比如打开了用户指南的多个文档，但重启思源后却全部关闭了）

### Describe the optimal solution

打开用户指南文档时不应该自动关闭用户指南笔记本

**Comment by 88250** [comment]
这个是设计如此，主要有两个用意：

1. 新用户如果将数据保存在用户指南中，可以在最大程度上减小连续误用导致数据丢失的可能性
2. 避免搜索到用户指南中多余的数据
