### ISSUE TITLE
用拖拽的方式将嵌入块移动到别的地方之后，原先的嵌入块儿可能会依然显示

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1045]
![image](https://user-images.githubusercontent.com/38101170/104529288-5b08cb80-5644-11eb-8ddd-64fe81b2b326.png)
![image](https://user-images.githubusercontent.com/38101170/104529312-652aca00-5644-11eb-833a-8ce8b3535dd9.png)

![image](https://user-images.githubusercontent.com/38101170/104529300-60feac80-5644-11eb-9008-51ca05cfd6f7.png)

**Comment by Andy-AO** [comment]
之后更严重的问题出现了，我本来想关闭这个标签页，重新打开
以便内容可以正常显示
但是关闭标签页之后没有办法继续打开了，点击是无效的
![image](https://user-images.githubusercontent.com/38101170/104529434-b89d1800-5644-11eb-924a-560dad78bfd7.png)

**Comment by Andy-AO** [comment]
重新启动思源笔记之后问题消失.
![image](https://user-images.githubusercontent.com/38101170/104529499-d9656d80-5644-11eb-92a4-17645069ae12.png)

**Comment by 88250** [comment]
感谢建议，合并到 https://github.com/siyuan-note/siyuan/issues/1051 中一起处理。
