### ISSUE TITLE
Don't pop up the keyboard when selecting a doc for the flash card on the mobile

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在安卓闪卡间隔，文档树页面点进去后，它会弹出输入法，将输入法收起后再点击，它会再次弹出来

### Expected result

照理说没点击输入框的时候，输入法不应该自己弹起来

### Version environment

```markdown
- Version: 3.01
- Operating System: 安卓11
- Browser (if used):
```

### Log file

无

**Comment by luo-chuan** [comment]
要不录个屏看看。一般安卓手机都自带录屏，下拉控制中心看看。

**Comment by QQQOrange** [comment]
> 要不录个屏看看。一般安卓手机都自带录屏，下拉控制中心看看。

https://github.com/siyuan-note/siyuan/assets/62794181/6221c5d8-e60e-487a-8944-a4d0e59a3ca0
