### ISSUE TITLE
明亮模式下的鼠标悬浮提示的文字依旧为黑色

### ISSUE THREAD

**Issue by CaoMeiYouRen** [siyuan-note/siyuan#10455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在明亮模式下，悬浮提示的文字和背景均为黑色，完全看不清；在暗黑模式下正常。
在尝试切换明亮/暗黑模式后依旧复现该问题

### Expected result

在明亮模式下，悬浮提示的文字应该为白色

### Screenshot or screen recording presentation

![QQ截图20240227165354](https://github.com/siyuan-note/siyuan/assets/40430746/5cfe1cb2-f01b-4f1a-aa39-553e10ff8144)
![QQ截图20240227165656](https://github.com/siyuan-note/siyuan/assets/40430746/eb468fd3-cdf7-4d28-a545-094cea569416)

### Version environment

```markdown
- Version: 3.0.0
- Operating System: Windows 11
- Browser (if used):
```

### Log file

I 2024/02/27 16:38:09 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/02/27 16:38:09 runtime.go:74: kernel is booting:
    * ver [3.0.0]
    * arch [amd64]
    * os [Microsoft Windows 11 Home China]
    * pid [68672]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_3.0.0.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\siyuan-data]
I 2024/02/27 16:38:09 conf.go:313: using Microsoft Store edition
I 2024/02/27 16:38:09 runtime.go:123: use network proxy [system]
I 2024/02/27 16:38:09 serve.go:115: kernel [pid=68672] http server [127.0.0.1:52369] is booting
I 2024/02/27 16:38:09 blocktree.go:495: read block tree [2.9 MB] to [D:\siyuan-data\temp\blocktree], elapsed [0.05s]
I 2024/02/27 16:38:09 conf.go:795: database size [28 MB], tree/block count [160/9920]
I 2024/02/27 16:38:09 working.go:192: kernel booted
I 2024/02/27 16:38:09 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=D:\siyuan-data\temp\pandoc\bin\pandoc.exe]
I 2024/02/27 16:38:09 conf.go:1030: pandoc initialized, set pandoc bin to [D:\siyuan-data\temp\pandoc\bin\pandoc.exe]
I 2024/02/27 16:38:09 box.go:76: auto stat [trees=160, blocks=9920, dataSize=10 MB, assetsSize=465 kB]
I 2024/02/27 16:38:09 disk.go:33: disk usage [total=296 GB, used=258 GB, free=38 GB]
I 2024/02/27 16:38:10 serve.go:128: reverse proxy server [127.0.0.1:6806] is booting
I 2024/02/27 16:39:35 index.go:197: rebuilt database for notebook [20210808180117-czj9bvb] in [0.02s], tree [count=68, size=1.3 MB]
I 2024/02/27 16:39:35 index.go:269: resolved refs [30] in [131ms]
W 2024/02/27 16:39:43 blocktree.go:552: save block tree [size=3.6 MB] to [D:\siyuan-data\temp\blocktree], elapsed [3.57s]
I 2024/02/27 16:41:30 conf.go:547: exiting kernel [force=false, execInstallPkg=0]
I 2024/02/27 16:41:33 conf.go:1020: closed user guide box [20210808180117-czj9bvb]
I 2024/02/27 16:41:33 database.go:1244: closed database

**Comment by luo-chuan** [comment]
不像默认主题？如果是第三方主题的话，建议先给主题作者反馈。

**Comment by royc01** [comment]
更新主题

**Comment by CaoMeiYouRen** [comment]
> 不像默认主题？如果是第三方主题的话，建议先给主题作者反馈。

抱歉，确实不是默认主题，是 `Savor` 主题，应该是没有更新的缘故
