### ISSUE TITLE
 Font switching not working in v3.0.1

### ISSUE THREAD

**Issue by Crowds21** [siyuan-note/siyuan#10454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

- [Relevant blog](https://ld246.com/article/1709001679757)

- 新建空笔记本
  - 更纱黑体 以及 霞鹜文楷 字体显示效果相同
  - <img width="302" alt="image" src="https://github.com/siyuan-note/siyuan/assets/48215334/221a2ac5-ebb1-4762-a127-e0edaafadd46">

- 旧笔记本(设置了一些 css 和插件)
   - 更纱黑体 以及 霞鹜文楷 字体显示效果相同
   - <img width="1084" alt="image" src="https://github.com/siyuan-note/siyuan/assets/48215334/507260a1-b163-48a9-a9a2-9bb4396934dd">

### Expected result

- 正确显示不同字体

### Version environment

```markdown
- Version: v3.0.1
- Operating System: Macos
- Browser (if used):
```

### Log file

I 2024/02/27 15:43:52 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/02/27 15:43:52 runtime.go:74: kernel is booting:
    * ver [3.0.0]
    * arch [arm64]
    * os [darwin]
    * pid [72335]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/crowds/Notes]
I 2024/02/27 15:43:52 conf.go:156: initialized language [zh_CN] based on device locale
I 2024/02/27 15:43:52 runtime.go:123: use network proxy [system]
I 2024/02/27 15:43:52 serve.go:115: kernel [pid=72335] http server [127.0.0.1:50781] is booting
I 2024/02/27 15:43:52 database.go:89: the database structure is changed, rebuilding database...
I 2024/02/27 15:43:52 database.go:109: reinitialized database [/Users/crowds/Notes/temp/siyuan.db]
I 2024/02/27 15:43:52 conf.go:795: database size [4.1 kB], tree/block count [0/0]
I 2024/02/27 15:43:52 working.go:192: kernel booted
I 2024/02/27 15:43:52 box.go:76: auto stat [trees=0, blocks=0, dataSize=37 kB, assetsSize=0 B]
I 2024/02/27 15:43:52 disk.go:33: disk usage [total=494 GB, used=390 GB, free=104 GB]
I 2024/02/27 15:43:53 index.go:197: rebuilt database for notebook [20210808180117-czj9bvb] in [0.01s], tree [count=68, size=1.3 MB]
I 2024/02/27 15:43:53 index.go:269: resolved refs [30] in [9ms]
I 2024/02/27 15:43:59 pandoc.go:155: initialized built-in pandoc [ver=3.1.1, bin=/Users/crowds/Notes/temp/pandoc/bin/pandoc]
I 2024/02/27 15:43:59 conf.go:1030: pandoc initialized, set pandoc bin to [/Users/crowds/Notes/temp/pandoc/bin/pandoc]
I 2024/02/27 15:44:06 updater.go:166: downloading install package [https://release.b3log.org/siyuan/siyuan-3.0.1-mac-arm64.dmg]
I 2024/02/27 15:44:13 conf.go:547: exiting kernel [force=false, execInstallPkg=0]
I 2024/02/27 15:44:16 conf.go:1020: closed user guide box [20210808180117-czj9bvb]
I 2024/02/27 15:44:16 database.go:1244: closed database
I 2024/02/27 15:44:16 conf.go:958: cleared workspace temp
I 2024/02/27 15:44:16 sync.go:713: sync websocket closed
I 2024/02/27 15:44:17 conf.go:603: exited kernel
I 2024/02/27 15:45:35 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/02/27 15:45:35 runtime.go:74: kernel is booting:
    * ver [3.0.1]
    * arch [arm64]
    * os [darwin]
    * pid [72781]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/crowds/Notes]
I 2024/02/27 15:45:35 conf.go:278: upgraded from version [3.0.0] to [3.0.1]
I 2024/02/27 15:45:35 runtime.go:123: use network proxy [system]
I 2024/02/27 15:45:35 serve.go:115: kernel [pid=72781] http server [127.0.0.1:50912] is booting
I 2024/02/27 15:45:35 blocktree.go:495: read block tree [256 B] to [/Users/crowds/Notes/temp/blocktree], elapsed [0.01s]
I 2024/02/27 15:45:35 conf.go:795: database size [7.4 MB], tree/block count [0/0]
I 2024/02/27 15:45:35 working.go:192: kernel booted
I 2024/02/27 15:45:35 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=/Users/crowds/Notes/temp/pandoc/bin/pandoc]
I 2024/02/27 15:45:35 conf.go:1039: pandoc initialized, set pandoc bin to [/Users/crowds/Notes/temp/pandoc/bin/pandoc]
I 2024/02/27 15:45:36 box.go:76: auto stat [trees=0, blocks=0, dataSize=53 kB, assetsSize=0 B]
I 2024/02/27 15:45:36 disk.go:33: disk usage [total=494 GB, used=391 GB, free=104 GB]
I 2024/02/27 15:45:36 serve.go:128: reverse proxy server [127.0.0.1:6806] is booting
I 2024/02/27 15:45:53 conf.go:547: exiting kernel [force=false, execInstallPkg=0]
I 2024/02/27 15:45:53 database.go:1244: closed database
I 2024/02/27 15:45:53 conf.go:958: cleared workspace temp
I 2024/02/27 15:45:54 sync.go:713: sync websocket closed
I 2024/02/27 15:45:54 conf.go:603: exited kernel

**Comment by 88250** [comment]
已经确认是 Electron 的问题，下个版本降级 Electron https://github.com/siyuan-note/siyuan/issues/10463
