### ISSUE TITLE
Mistral.ai AI support

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#10467]
### In what scenarios do you need this feature?

Mistral.ai 具有以下优点：

1. 性价比高：Mistral-Medium 开销小于 GPT-3.5 但是性能却超过 3.5；Mistral-Large 的性能想当接近 GPT-4
2. LLM 圈内口碑好。
3. 国内友好：官网没有被 great wall，且支持绑定国内发行的海外信用卡
4. 有现成的轮子：官方提供了一个 go 语言的 client

### Describe the optimal solution

mistral 文档
https://docs.mistral.ai/platform/client/#go

go client
https://github.com/Gage-Technologies/mistral-go

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/9262#issuecomment-2009177382
