### ISSUE TITLE
AI 只能对快操作，不能对快里已选中的文字操作

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

有时候 AI 的使用是要查阅一句话里面的某一个名词，但是选中几个字之后，并不能够直接使用AI

### Expected result

能够对选中的几个字，也能进行 AI 操作

### Version environment

```markdown
- Version: 3.01
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
感谢反馈，目前暂时不考虑行级操作了。

**Comment by 88250** [comment]
没用计划的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月28日(周三) 晚上8:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] AI 只能对快操作，不能对快里已选中的文字操作 (Issue #10466)




  
感谢反馈，目前暂时不考虑行级操作了。
  
短期内都没有计划吗
