### ISSUE TITLE
虚拟引用没有根据别名进行搜索

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#10465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

依虚拟引用的官方介绍：
> 根据已有块引的锚文本/定义块文本、块的命名和别名作为关键字搜索，如果在当前内容块的纯文本元素上搜索到这些关键字，那么就会作为虚拟引用。

但是我这里只检测到了块本身，而没检测到其别名

### Expected result

正确检测别名

### Screenshot or screen recording presentation

![Xnip2024-02-28_10-45-04](https://github.com/siyuan-note/siyuan/assets/2016363/e5d1be08-b1b2-4f60-b933-f0b1ef30edc9)
![Xnip2024-02-28_10-45-31](https://github.com/siyuan-note/siyuan/assets/2016363/3e9c1638-7139-4806-8607-cfa4d49f299e)

### Version environment

```markdown
- Version: v3.0.0
- Operating System: macOS 14
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
打开这个选项了吗？

![image](https://github.com/siyuan-note/siyuan/assets/873584/3039f7cf-f483-4dfd-b6fa-52ae2e55bd52)

**Comment by aGolduck** [comment]
没有。感谢。这里是不是默认打开比较好。毕竟帮助文本这么写很容易让人默认是打开的。

**Comment by 88250** [comment]
别名默认是关闭的，稍后我们补充一下用户指南，感谢反馈。
