### ISSUE TITLE
Source Mode View

### ISSUE THREAD

**Issue by YukimeGPT** [siyuan-note/siyuan#10461]
### In what scenarios do you need this feature?

Useful for editing mardown in source mode then switch back to normal view like in Obsidian

### Describe the optimal solution

Add in Source Mode View like in Obsidian or if there's another workaround available

**Comment by 88250** [comment]
Please try to use this plugin:

![image](https://github.com/siyuan-note/siyuan/assets/873584/d9c947cd-f645-4d73-b270-6c218a0f79ae)
