### ISSUE TITLE
Improved doc tree expansion button scope on the mobile 

### ISSUE THREAD

**Issue by eya46** [siyuan-note/siyuan#10477]
### In what scenarios do you need this feature?

习惯性点 > 和 ⅴ 来展开和收起，但是app上图标范围太小，总容易点进笔记里，很折磨人
![IMG20240301103740](https://github.com/siyuan-note/siyuan/assets/61458340/c49480be-a136-4b58-9f8c-0da3ab7a7fe5)

### Describe the optimal solution

最好是点击多次也不容易误触 进入笔记

**Comment by Vanessa219** [comment]
目前上下有4个像素的间距，如果不小心点到这个间距可能会打开文档。我先优化这个点，下个版本麻烦再看看。
