### ISSUE TITLE
Add hotkey to open AI

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10472]
### In what scenarios do you need this feature?

现在使用人工智能的相关功能比较麻烦，要先换出菜单，再点击二级菜单。如果是自定义的话，还要再点击三级菜单，比较麻烦

希望有一个快捷键，能够直接唤起人工智能相关功能，这样能够提高操作的效率

### Describe the optimal solution

希望有一个快捷键能够快捷的唤出人工智能的相关功能

就像 shift 加点击唤出属性面板一样

能够通过一快捷键唤出人工智能面板

**Comment by darrelwangsz** [comment]
现在的交互做的有点糟糕，能不能请求后就在某个侧边栏给结果然后可以直接插入就好了，不要有一个弹窗加载影响工作开展。

**Comment by QQQOrange** [comment]
> 现在的交互做的有点糟糕，能不能请求后就在某个侧边栏给结果然后可以直接插入就好了，不要有一个弹窗加载影响工作开展。

而且现在的只能对快操作，不能够对行距文本进行操作。如果想要对行距文本进行操作的话，得把那几个字复制出来，单做一个块，然后再操作，非常的麻烦

**Comment by HowcanoeWang** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/19968935/351a0a12-1647-41d6-8662-185b0f1357b2)

目前这个按钮，左键和右键弹出的菜单是一样的，似乎可以把其中一个改成AI菜单会不会更方便（左右键提供设置，可以让用户自行决定是左键AI还是右键AI）

**Comment by Vanessa219** [comment]
1. 添加一个为空的快捷键，自己配置
2. 请求后继续其他操作可能会影响返回结果插入的位置，或者导致无法插入
3. 支持对行内元素操作
4. 菜单键有些用户喜欢点击，有些喜欢用右键。这个保持不变，添加一个快捷键就好

**Comment by HowcanoeWang** [comment]
> 而且现在的只能对快操作，不能够对行距文本进行操作。如果想要对行距文本进行操作的话，得把那几个字复制出来，单做一个块，然后再操作，非常的麻烦

希望在选中文字的弹出菜单里，也能增加一个AI按钮，来对选中文字的部分进行AI操作，并且把结果直接替换？(如果发现AI出来的不满意，ctrl+z撤销即可，不需要在选中文字后面插入然后用户再手动把前面的删除)

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/bb7018f0-f8b1-4b00-be98-f2f96e0e1984)

**Comment by HowcanoeWang** [comment]
> 请求后继续其他操作可能会影响返回结果插入的位置，或者导致无法插入

对于整块的AI操作，应该可以记录一下发送AI请求的块ID在缓存里？然后结果返回后直接用API在块的下面插入新块

对于块内的选中部分文字的AI操作，可以考虑在sy文件里，给选中部分打上<ai_waiting>这样的tag并且记录改块的ID，AI结果返回后直接对块ID里面的tab部分进行替换操作？

这是我的想法，不知道实现起来难度如何

**Comment by HowcanoeWang** [comment]
> 现在的交互做的有点糟糕，能不能请求后就在某个侧边栏给结果然后可以直接插入就好了，不要有一个弹窗加载影响工作开展。

前端可以给正在AI的块或者选中的文字部分(有<ai_waiting> tag的部分)，修改一下颜色并且增加一下文字跳跃动画，来告诉用户AI正在后台运行，来避免弹窗的出现？(配合上面提到的块ID缓存+tag的方法，应该可以解决无法找到结果插入的位置)

**Comment by Vanessa219** [comment]
用户操作的场景过多，无法一一阻止和防备。参考了下 notion，可以不遮罩，但是会进行提示

<img width="927" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/66a1c3b6-cd8e-4979-8380-75ae2e8e162e">

**Comment by QQQOrange** [comment]
> > 请求后继续其他操作可能会影响返回结果插入的位置，或者导致无法插入
> 
> 对于整块的AI操作，应该可以记录一下发送AI请求的块ID在缓存里？然后结果返回后直接用API在块的下面插入新块（如果担心用户直接把块给删掉了，那就顺便再多记录一下文档的信息，如果块不存在则直接在文档最后面插入新块）
> 
> 对于块内的选中部分文字的AI操作，可以考虑在sy文件里，给选中部分打上<ai_waiting>这样的tag(标上这个tag的部分暂时不可修改和删除)，并且记录该块的ID到缓存中，AI结果返回后直接对块ID里面的tab部分进行替换操作或者取消tag标记？
> 
> 这是我的想法，不知道实现起来难度如何

我也觉得，现在的AI会直接把文字插在正文里面，有时候分不清楚ai的文字和原本文字之间的一个界限。最好能够把AI做出来的文字放到引述里面

**Comment by Vanessa219** [comment]
目前返回会插入到最后一个块的末尾。

**Comment by QQQOrange** [comment]
> 目前返回会插入到最后一个块的末尾。

因为样式的原因和正常的文字都是一个样式。就难以区分开来。

**Comment by Vanessa219** [comment]
嗯，后面会改进这块插入的交互 https://github.com/siyuan-note/siyuan/issues/10540
