### ISSUE TITLE
Support taking photos for inserting on Android

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10479]
https://ld246.com/article/1709264611954

仅支持 Android 10 以上。

**Comment by pisceswb** [comment]
请问能否支持录音和录制视频插入？

**Comment by 88250** [comment]
从目前收集到的反馈看，几乎没有这方面需求，所以暂时不做开发计划了，谢谢。

**Comment by metaasty** [comment]
请问是否会在iOS支持该特性呢
