### ISSUE TITLE
搜索支持拼音首字母查询

### ISSUE THREAD

**Issue by QuQu** [siyuan-note/siyuan#10489]
### In what scenarios do you need this feature?

在搜索的时候，经常需要切换输入法。感觉很不方便。

### Describe the optimal solution

如果能够支持拼音首字母搜索内容，就可以避免切换输入法。

### Other information

 [来源](https://github.com/Chaoses-Ib/IbEverythingExt) Chaoses-Ib/IbEverythingExt: Everything 拼音搜索、快速选择扩展 

everything的这个插件，用起来就非常顺手。解决了切换输入法的问题。

**Comment by 88250** [comment]
感谢提议，但实现不了，见谅。
