### ISSUE TITLE
希望加入刷新功能

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1048]
由于bug的影响，经常需要重新关闭并且打开文档，没有发现刷新的功能，这导致使用效率下降更多，希望能够尽快补上这个基本功能.

还有就是最好有Ctrl+Shift+T将关闭的标签页打开，这个常用快捷键好像也没有.

**Comment by 88250** [comment]
等继续修复问题，理论上是要做到不手动刷新的。重开页签还有页签切换后续增加，谢谢。
