### ISSUE TITLE
Improve copy and cut after multiple selection of cells in the table

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10488]
https://ld246.com/article/1709137932420/comment/1709391576381?r=Vanessa#comments

剪切或复制多个单元格后，最终粘贴出来都是一个完整的表格

**Comment by TCOTC** [comment]
关联 #4785

**Comment by TCOTC** [comment]
希望还能支持复制 A 表格的一部分粘贴到 B 表格里

**Comment by TCOTC** [comment]
用户需求：

- https://ld246.com/article/1729943519845

**Comment by TCOTC** [comment]
```
|                  | 变量 | 默认图标 | 设置的图标 |
| ------------------ | ------ | ---------- | ------------ |
| 普通文档         | `siyuan.storage["local-images"].file`     | 📄`1F4C4`       |            |
| 含有子文档的文档 | `siyuan.storage["local-images"].folder`     | 📑`1f4d1`       | 📁`1F4C1`         |
| 笔记本           | `siyuan.storage["local-images"].note`     | 🗃`1f5c3`       | 🗂️`1F5C2`       |
```

直接粘贴到段落块没问题，但粘贴到表格会有一点问题（见第一个录屏）：

1. 粘贴第二次才粘贴完整
2. 单元格高亮没有同步移动

此外还有两点：

3. 特定情况无法多选单元格（第二个录屏里只演示了行级代码，不知道其他行级样式会不会影响）
4. 希望能接着再解决一下 #11388

[视频.webm](https://github.com/user-attachments/assets/0ff3396a-6c1d-4b07-a2a1-003a3fa5ff54)

[视频.webm](https://github.com/user-attachments/assets/308fb2b2-f1bf-4aa6-9a49-648046b1c79f)

**Comment by TCOTC** [comment]
希望再支持一下从数据库复制粘贴到表格：

[视频.webm](https://github.com/user-attachments/assets/387ffe4e-9cb1-4ad0-8f31-5d70591a0c35)

**Comment by Achuan-2** [comment]
从表格A选中部分复制到表格B，现在必须要先选中B对应数量单元格，才能成功粘贴，这个能否改进下呢。可以直接在B表格粘贴

复制A表格的一部分
![image](https://github.com/user-attachments/assets/cd9646ee-640f-4d64-a09b-fd72da30a20f)
选择B表格要粘贴的单元格
![image](https://github.com/user-attachments/assets/f8c53d55-8338-4d55-9a13-86cbe73a0266)

**Comment by Vanessa219** [comment]
@TCOTC 由于和 notion 设计不同，选中后都会标记当前光标位置，第一点就不进行修改了。
用上数据库一般就不会转换为表格了，等后续看看此需求的用户比例。

@Achuan-2 不选择单元格的话会有以下问题


https://github.com/user-attachments/assets/73d8e255-f33f-4a47-af59-f3f9dfad63c4

**Comment by TCOTC** [comment]
> 用上数据库一般就不会转换为表格了

有时候我会发现用数据库太“重”了，几个单元格的事情没必要用上数据库，所以就想把数据库转换回普通表格

**Comment by TCOTC** [comment]
> 不选择单元格的话会有以下问题

有没有办法像数据库这样，空的单元格也不影响粘贴：

[video.webm](https://github.com/user-attachments/assets/dd0a41c5-e728-4b76-8ce6-2cd8cc45bbe2)

**Comment by Vanessa219** [comment]
那可以搞一个数据库转换为表格的功能岂不是更快。
目前先按照用户划选的范围进行粘贴吧，后面有空再继续完善表格的功能。

**Comment by TCOTC** [comment]
> 可以搞一个数据库转换为表格的功能岂不是更快

快是快了，但数据库可以筛选排序，有的场景下会需要排好序之后复制粘贴出表格，直接转换的话就是没有排序的了

**Comment by Vanessa219** [comment]
可以转换为不排序的

**Comment by TCOTC** [comment]
一个数据库有多个视图，每个视图排序都不同的话交互会更麻烦，还是复制单元格粘贴符合直觉。

你看 Wolai 这个交互就很丝滑：

[video.webm](https://github.com/user-attachments/assets/c77444ef-259c-4821-a2da-ec723c53dc1c)

**Comment by TCOTC** [comment]
> 由于和 notion 设计不同，选中后都会标记当前光标位置，第一点就不进行修改了。

如果用户选中单元格，那就是要对单元格进行操作，为什么还要光标？

**Comment by Vanessa219** [comment]
目前数据库复制粘贴后是文本，可以看一下大家是否需要粘贴为表格。
选中块对块操作也是有光标的，保持一致的设计。

**Comment by TCOTC** [comment]
> 选中块对块操作也是有光标的

把这个也改掉吧，留着光标没用
