### ISSUE TITLE
Adding rows after setting the sort field in the database table view no longer fills in the default value

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10486]
数据库表格视图设置排序字段后添加行不再填充默认值

某字段设置为排序字段后，如果在表格末尾插入则不参与排序；如果在其他位置插入则插入到末尾，不参与排序。

**Comment by Achuan-2** [comment]
这个改进有点问题，在数据表最前面添加新行，会自动到最后。
我目前在数据表添加新行，都是点击右上方的按钮，在最前面添加新行，因为就不必滚动到最后添加了。

**Comment by 88250** [comment]
不移除排序的话是这样的，参考 Notion。



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 5, 2024 14:24 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Adding rows after setting the sort field inthe database table view no longer fills in the default value (Issue #10486)




 
这个改进有点问题，在数据表最前面添加新行，会自动到最后。
 我目前在数据表添加新行，都是点击右上方的按钮，在最前面添加新行，因为就不必滚动到最后添加了。

**Comment by Achuan-2** [comment]
感觉改成

- 在最前面添加行，就把行放在最前面，暂时不参与排序
- 在最后面添加行，就把行放在最后面，暂时不参与排序
这样更好吧
否则倾向在最前面添加行的用户，依然只能在没有排序的视图添加行。在最后面添加行，只适用于数据不多的情况吧

**Comment by 88250** [comment]
放在前面的话分页的情况有问题。



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 5, 2024 15:16 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Adding rows after setting the sort field inthe database table view no longer fills in the default value (Issue #10486)




 
感觉改成
  
在最前面添加行，就把行放在最前面，暂时不参与排序
 
在最后面添加行，就把行放在最后面，暂时不参与排序
 这样更好吧
 否则倾向在最前面添加行的用户，依然只能在没有排序的视图添加行。在最后面添加行，只适用于数据不多的情况吧

**Comment by 88250** [comment]
我说错了，和分页没关系，只要和当前滚动位置有关系。


如果是最前面的话实际和最后面是等价的吧，都需要滚动。如果说的是可视区域的顶部，那实现不了的，因为这个地方是排序数据连续的中间位置。



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 5, 2024 15:25 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Adding rows after setting the sort field inthe database table view no longer fills in the default value (Issue #10486)




 
默认放在后面的话，如果这个排序的数据库内容很多，新建完当前页是找不到，需要不断翻到最后一页，也是有问题的。
 放在前面，分页有什么问题呢

**Comment by Achuan-2** [comment]
说的是放在最前面
感觉还是不一样的，放在最前面，我通过右上方的添加按钮，就是在最前面添加内容，不需要什么滚动
而放在最后面，我在视图的下方点击添加按钮，创建的内容放在最后面，如果当前还有页数没有加载，我是看不到的，需要不断翻到最后才能看到

**Comment by Achuan-2** [comment]
D大可以试试创建超过10行的数据库，把数据库页数设置为10，就知道问题了

**Comment by 88250** [comment]
我知道你说的问题，但是放到最前面会导致排序混乱的。

参考 Notion 所以统一放到最后。

**Comment by Achuan-2** [comment]
好吧，我就建议下，我个人习惯搞一个没有排序和排序的总表，在总表添加数据
