### ISSUE TITLE
When will the content be converted to html?

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#10480]
### In what scenarios do you need this feature?

想知道思源笔记内部在什么时候会将内容转换成 HTML 块。

### Describe the optimal solution

暂无

## 具体情况

由于我担心自己不小心会修改了以前的内容，因此我在插件里，根据更新时间禁用了段落的编辑。

<img width="561" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/d3350614-93fb-4ef5-a1c4-c03e7520f0eb"> 

<br><br>
但是在我将内容拖拽到文档里以后，重新打开文档，这个拖拽进来的内容将会变成HTML块。

就像下面这个图，Mac平台，按住 `ctrl` 重复拖拽出的块。

<img width="761" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/3922bf53-8f6f-4ee6-a916-81b42813dc8f">

如果刷新【智能家居】这篇文档，这个块的内容将会变成下图这样的 HTML 块。

<img width="424" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/52f56e5c-e6da-4838-96d4-b0266dbd963e">

## 我的分析

出现这个情况，我猜应该是我设置了 `contenteditable="false"` 的原因，如果我取消这个锁定功能，是不会出现这个问题的。

---

**并不是一个需要改进的逻辑**，我可以在整理前取消这个锁定的功能。

但是我希望在锁定的情况下，依旧能够完成”拖拽整理“这样的操作，而不是产生这样的非预期的情况。

因为锁定是为了锁定段落内容不会被修改，防止动了内容的更新时间。比如我就出现过没注意光标位置，然后按了空格、回车、或者直接输入的情况。

如果 D 大和 V 姐有时间的话，或者其他朋友知道的话，希望能告知一下这里的转换规则。

**Comment by 88250** [comment]
CommonMark 里面定义的 HTML 块 https://spec.commonmark.org/0.31.2/#html-blocks

解析器比较复杂，不建议直接修改 DOM 结构，否则可能很难排查相关细节。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
