### ISSUE TITLE
Additional Flashcard question format: True/False, Multiple Answer, and Typed Response

### ISSUE THREAD

**Issue by Shina-SG** [siyuan-note/siyuan#10481]
### In what scenarios do you need this feature?

In general for most, gamify the flashcard system into an instant reward/punish should be more effective in remember/learning than the traditional flip card way (https://quizlet.com/blog/selecting-question-formats-to-maximize-the-testing-effect).

### Describe the optimal solution

For True/False I think we could simply add a True/False option, Typed Response with the same format but with a box to type in, and Multiple Answer then a list of answer randomized that turn into A, B, C, D

**Comment by 88250** [comment]
Hello, we are not considering expanding the flashcard type at the moment, thanks for the suggestion.
