### ISSUE TITLE
数据库绑定主键块支持反向跳转回原数据库并高亮提醒

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10499]
### In what scenarios do you need this feature?

数据库数据行多起来后很难找，每次用筛选和搜索也很麻烦

### Describe the optimal solution

能跳回数据库所在行

### Describe the candidate solution

用行号？

**Comment by Vanessa219** [comment]
指的是点击红框处么？
<img width="827" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/58cdb598-4da7-4e2f-bd55-4b31ecad068b">

**Comment by AvoidantPerDis** [comment]
也行，不过希望有更方便的入口

**Comment by Vanessa219** [comment]
那大概是什么样的场景呢？

**Comment by AvoidantPerDis** [comment]
一个数据库绑定的键附近有块需要绑定到数据库，但是数据库太多行，中文排序又不生效的时候

**Comment by 88250** [comment]
一个块存在于多个数据库中的时候无法跳转，所以还是使用上面 V 提到的浮窗比较好。

关于行太多时的定位和高亮 V 评估一下能否实现。

另外，近期可以等 #10419 实现后通过表格内搜索顶顶。

**Comment by Vanessa219** [comment]
那应该是解决中文排序不生效的问题才对呀。

**Comment by 88250** [comment]
和排序没多大关系，行数据多了都有这个问题。

**Comment by Vanessa219** [comment]
目前没有定位到行的链接和入口，因此还是不太理解。是拖拽块插入到行的时候不太方便么？

**Comment by AvoidantPerDis** [comment]
是的，希望保持我自定义的顺序

**Comment by Vanessa219** [comment]
自定义顺序应该是可以保持的，如果保持不了的话可以说一下重现步骤嘛？

**Comment by AvoidantPerDis** [comment]
额，中文会有排序错误问题https://github.com/siyuan-note/siyuan/issues/10007
不过我目前更希望闪卡的改进

**Comment by Vanessa219** [comment]
好的，我们安排一下。
