### ISSUE TITLE
siyuan 3.0.1 windows defender report virus and deleted kernel

### ISSUE THREAD

**Issue by feitian124** [siyuan-note/siyuan#10495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

today after i update siyuan, the windows defender report virus and automatically deleted kernel:
The kernel program is not found, please reinstall SiYuan and add SiYuan Kernel prgram into the trust list of your antivirus software.

### Expected result

siyuan should work as normal

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/1425383/b488c1a3-94a4-4167-a5ef-4d2a06c7bf05)
![image](https://github.com/siyuan-note/siyuan/assets/1425383/1999a21f-aa2e-4fa4-9256-f5594f88a141)

### Version environment

```markdown
- Version: 3.0.1
- Operating System: windows 11
- Browser (if used): chrome latest
```

### Log file

did not find the log

**Comment by feitian124** [comment]
@88250

**Comment by 88250** [comment]
Please refer to https://github.com/siyuan-note/siyuan/issues/10493

**Comment by feitian124** [comment]
好的，谢谢。添加排除项后ok。
试了 3.0 不会触发误报，3.0.1就会，不晓得啥特征变化了？

**Comment by 88250** [comment]
不晓得……
