### ISSUE TITLE
集市多一个刷新按钮

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10497]
### In what scenarios do you need this feature?

思源每次如果有新插件更新之后，要把软件重启后，才集市里面才能看得到，非常麻烦。

希望集市里面能够有一个刷新的按钮，与以避免每次从其他渠道收到插件更新的消息，但却要重启思源后才能更新插件的问题

第一张图是重启之前，第二张图是重启之后
![image](https://github.com/siyuan-note/siyuan/assets/62794181/e5dbde41-f1d0-49fd-a38f-3c958b8033d1)
![image](https://github.com/siyuan-note/siyuan/assets/62794181/cd15ea22-142c-4029-8bf5-15062c5f29b4)

### Describe the optimal solution

在集市添加刷新按钮

**Comment by 88250** [comment]
集市索引是缓存 6 小时的，所以集市包作者更新后至少要 6 小时以后才能在集市中看到。重启会重新计算时间，不重启的话建议等待后再看看，感谢反馈。

**Comment by TCOTC** [comment]
我经常折腾插件，也发现这个问题了。想看看插件更新没有就必须先重启思源才能确认，好麻烦，所以想要一个刷新按钮。

**Comment by TCOTC** [comment]
经常出现在链滴看到作者说插件已经上架了，还要重启一下思源才能在集市看到插件的情况

**Comment by TCOTC** [comment]
还有，重启完文档树就都折叠起来了，有点不方便

**Comment by 88250** [comment]
不提供刷新按钮了；文档树展开状态保持请关注 #10652
