### ISSUE TITLE
没有网络连接时，暂停自动同步

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#10496]
### In what scenarios do you need this feature?

开启了自动同步后，在出差移动中没有网络时，频繁弹出同步失败。虽然可以手动在设置里修改成手动同步，但回到办公地点还得把设置再改回来，比较麻烦

### Describe the optimal solution

没有网络连接时，不推送上面的同步失败通知

**Comment by QQQOrange** [comment]
赞同

**Comment by 88250** [comment]
不提示的话存在忘记同步的风险，所以不考虑了，感谢反馈。
