### ISSUE TITLE
希望可以提供分层搜索（Hierarchical Search）功能 

### ISSUE THREAD

**Issue by QuQu** [siyuan-note/siyuan#10490]
### In what scenarios do you need this feature?

非常多的资料都有类似的层级结构。
比如，几乎每一部法律，都有「第二十条」。
比如，很多书，都有「第二章」。

如果，直接搜索「第二十条」或「第二章」的话，就会有非常多的候选。需要查找。

### Describe the optimal solution

RemNote解决这个问题的方式是提供了分层搜索（Hierarchical Search）功能 。
比如想要搜索《刑法》的第二十条的话。

1. 先输入「刑法」，
2. 候选中《刑法》文档后，按 TAB 键
3. 输入「第二十条」，此时的候选结果，只会出现《刑法》文档内的第二十条。

### Other information

 [来源](https://www.youtube.com/watch?v=8vnDQXlLeyU) (8) RemNote Tutorial #16: Hierarchical Search - YouTube 
这是 RemNote 中分层搜索的用法视频。

**Comment by 88250** [comment]
你好，不考虑支持层级化搜索了，可考虑 AND 逻辑连接关键字（使用 查询语法 搜索方式或者 关键字 搜索方式下 使用空格分隔关键字），感谢提议。

**Comment by QuQu** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/961425/3b21f3e8-bb5c-4467-bae0-55dd1904056b)
请教一下，如果是这样的文档结构。我想搜索公司法的第一条，要如何使用 AND 连接关键字呢？

**Comment by 88250** [comment]
公司法 是文档名的话只能用 SQL 搜索，关键字 和 查询语法 实现不了。
