### ISSUE TITLE
Copy database without mirroring

### ISSUE THREAD

**Issue by Cyber-Syntax** [siyuan-note/siyuan#10494]
### In what scenarios do you need this feature?

I need a separate database for my projects, but I use the same attributes in each project. Naturally, instead of creating it manually, I want to copy it as a separate database without mirroring feature..

### Describe the optimal solution

Making mirroring feature optional? Maybe new copy option?

**Comment by 5kyfkr** [comment]
https://github.com/siyuan-note/siyuan/issues/10443
I also raised this requirement and the developer has recorded it
@88250 @Vanessa219 D大V姐这个为了这个需求每天都会看一眼github有没有closed😂

**Comment by 5kyfkr** [comment]
You can save the document where the database you want to copy is located as a template, and then call this document through the template function. This enables database content reuse.

**Comment by 5kyfkr** [comment]
> > You can save the document where the database you want to copy is located as a template, and then call this document through the template function. This enables database content reuse.
> 
> I looked up templates guides for go and siyuan but didn't understood anything. I don't know go language yet. I am gonna learn eventually but it's not my priority for now. It would be great if you write how to do basic to-do database template for siyuan.

See the picture below, just create and use the template like this
![image](https://github.com/siyuan-note/siyuan/assets/63196026/529a9d67-5c71-4d34-b398-4f17e3d0a4c0)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/ac0533c6-5148-4018-b51d-1a111daae2cb)

**Comment by Cyber-Syntax** [comment]
@5kyfkr You are wonderful! That's what I needed, thank you very much :)
