### ISSUE TITLE
数据库添加筛选后主界面所有菜单无响应

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在最新版本v3.0.2-dev2中，如下图，对数据库点击筛选后就会造成主界面工具栏及数据库的按钮无响应
![image](https://github.com/siyuan-note/siyuan/assets/63196026/c83f26af-9233-46e3-9739-9f96addd8080)

### Expected result

应能正常筛选不造成界面无响应

### Version environment

```markdown
- Version:  v3.0.2-dev2
- Operating System: win10
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
是设置单选吗？

**Comment by 5kyfkr** [comment]
我这边随便设置哪一列都会引发

**Comment by 88250** [comment]
收到，稍后排查，多谢。

**Comment by Vanessa219** [comment]
67503a3e01f0d1075bb8bbd6c3e3fac25d9e1965
