### ISSUE TITLE
Ctrl+F的搜索功能无法导航到文本的具体的位置

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1049]
Ctrl+F的搜索功能好像无法导航到文本的具体的位置

这是严重影响使用效率的

https://user-images.githubusercontent.com/38101170/104531663-9954b980-5649-11eb-9746-8e9e97520926.mp4

**Comment by 88250** [comment]
表格内的定位已在 #922 中改进，谢谢。
