### ISSUE TITLE
最新版本（v3.0.1）被win11自带安全软件报毒，之前没有

### ISSUE THREAD

**Issue by ericma15** [siyuan-note/siyuan#10493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/27952575/6b8c170d-46f3-4716-9b99-6f813a88367e)
版本为3.0.1

### Expected result

正常问题

### Version environment

```markdown
- Version: v3.0.1
- Operating System: win11 22H2
- Browser (if used):
```

### Log file

无

**Comment by ericma15** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/27952575/44941dc8-c273-4674-b371-05d461ee0b90)

**Comment by 88250** [comment]
没有办法，Windows Defender 容易误报，之前也发生过，请参考 https://github.com/siyuan-note/siyuan/issues/10338

**Comment by 88250** [comment]
解决方案是加入排除项，请参考 https://ld246.com/article/1707326088452
