### ISSUE TITLE
将嵌入块整个全选之后，执行删除操作，却只能删除最前面的叹号

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1050]
将嵌入块整个全选之后，执行删除操作，却只能删除最前面的叹号

全选两次删除，才能够执行正确的操作

https://user-images.githubusercontent.com/38101170/104532099-737be480-564a-11eb-8f91-1d7fd2e1b8db.mp4

**Comment by Vanessa219** [comment]
最新版无法重现，请更新后重试。如果还能重现，请继续留言。
