### ISSUE TITLE
Improve flashcard review count display

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10502]
间隔重复界面添加刷新按钮

### In what scenarios do you need this feature?

闪卡右上角的数字只是刚点进去的状态，如果碰到一次复习较多，闪卡花费时间较长的情况下，上面的数字就不能很好的反映当前要学习和复习的闪卡数量

### Describe the optimal solution

数字实时刷新

### Describe the candidate solution

提供主动刷新按钮

**Comment by AvoidantPerDis** [comment]
不是啊，就是正常复习

**Comment by AvoidantPerDis** [comment]
复习掉一些的时候数量应该变化比较直观

**Comment by Vanessa219** [comment]
是需要区分新卡和旧卡这样显示么？
<img width="199" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/becaa242-922c-4f8c-ab7e-262e67d73b07">

**Comment by AvoidantPerDis** [comment]
这样也需要，注意是实时更新数字

**Comment by Vanessa219** [comment]
点击后会更新红色数字，蓝色是新卡总数，绿色是旧卡总数。

**Comment by 88250** [comment]
> 对了，不知道这个数据是否可以作为数据库的一列，与主键关联

可能可以作为模板字段的内置变量，后续我们研究下看看。

**Comment by 88250** [comment]
@AvoidantPerDis 技术上可以实现，但是使用场景感觉不多，你认为呢？

**Comment by AvoidantPerDis** [comment]
可能跟闪卡管理功能重复了，优先级可以降低（某个小版本没重点的时候可以加一下），用来与数据库结合利好宣传

**Comment by 88250** [comment]
嗯，等有使用场景再考虑吧。

**Comment by AvoidantPerDis** [comment]
而且可能跟重构有冲突

**Comment by 88250** [comment]
闪卡的重构还不确定能不能做。

**Comment by AvoidantPerDis** [comment]
不急，现在也够用

**Comment by luo-chuan** [comment]
> @AvoidantPerDis 技术上可以实现，但是使用场景感觉不多，你认为呢？
> 
> ![image](https://private-user-images.githubusercontent.com/873584/311407234-522f234f-b79c-4128-a647-be1b1c970bc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NTY2MzQsIm5iZiI6MTcwOTk1NjMzNCwicGF0aCI6Ii84NzM1ODQvMzExNDA3MjM0LTUyMmYyMzRmLWI3OWMtNDEyOC1hNjQ3LWJlMWIxYzk3MGJjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwMzUyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDgwMDU5YmY3ZWYwMzllNDVjZTc3ZDEwYWJiNjk4YzI3MjBmYjgxZTFlZTNmM2QwMmViZmYyZGRiMDgzYjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ylYTCvcB5emveRBfIvS-77iHnO7caDAh0G1J-ckrnAQ)
> 
> 如果是作为统计用，用起来就比较麻烦了，需要手动添加到数据库，统计的话还是等 #10438

如果是图片里的这种UI，说实话，没啥用。如果不能预览闪卡，只看id根本不知道内容是啥。

**Comment by 88250** [comment]
主键那里可以浮窗。



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 9, 2024 11:54 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve flashcard review count display(Issue #10502)




  
@AvoidantPerDis 技术上可以实现，但是使用场景感觉不多，你认为呢？
 

 
如果是作为统计用，用起来就比较麻烦了，需要手动添加到数据库，统计的话还是等 #10438
  
如果是图片里的这种UI，说实话，没啥用。如果不能预览闪卡，只看id根本不知道内容是啥。

**Comment by zxhd863943427** [comment]
闪卡功能投票：https://ld246.com/article/1709964739844
