### ISSUE TITLE
标签宽度是否能支持可配置

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#10508]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/13564117/90ecfaa1-d875-4ce6-9ecc-8bdc89f992b9)
如上图所示，文档标题长过多少时就会以...代替，能否增加可配置项或者自适应宽度？

### Describe the optimal solution

增加可配置项或者自适应宽度

**Comment by Vanessa219** [comment]
可以使用代码片段重置这个样式
<img width="276" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/d591e205-42b1-43d5-b411-c15da550fa87">
