### ISSUE TITLE
/api/block/appendDailyNoteBlock 能否先校验一下是否已经存在dailynote

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用这个api，在笔记本直接给我新建了两个dailynote

### Expected result

略

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

略

**Comment by 88250** [comment]
会检查的，建议重建索引以后再测试看看。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by pakeh2866** [comment]
发现问题了，因为写入api的时候，siyuan iOS处于启动状态，索引没有校验完。
两种测试情况：
启动中，未索引完的情况下，会新建新的dailynote。
启动中，等待4秒，校验完后，不会出错。 @88250

**Comment by 88250** [comment]
那估计只能等等了，感谢反馈。
