### ISSUE TITLE
关于数据库表格视图的几个建议

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#10509]
### In what scenarios do you need this feature?

1、数据库表名目前长度固定，表名文字内容过长无法完全显示，可否设置为自适应
![image](https://github.com/siyuan-note/siyuan/assets/13564117/e049d2a3-0194-48e7-8f8e-a206b7924436)

2、对于大部分用户来说期望的个人觉得应该所见即所得，那些编辑状态的（下图红框显示的内容）并不是用户想要一直显示出来的吧，如果需要编辑了选中右键菜单触发编辑或者其它方式触发编辑模式，感觉整体效果会更好点。
![image](https://github.com/siyuan-note/siyuan/assets/13564117/f56d1749-2f3a-4db8-a0e2-0e0b028bd72d)

3、筛选好像不支持组合条件，比如开头为"测试"或者开头为"思源"这种组合的逻辑。

4、单列属性是否可以组合，比如文本 + 日期，勾选 + 文本
![image](https://github.com/siyuan-note/siyuan/assets/13564117/92751571-f5cc-464e-a3f0-b0e744320232)

### Describe the optimal solution

参见上述场景描述

**Comment by 88250** [comment]
3. 后期考虑
4. 不支持

1、2 @Vanessa219 看一下

**Comment by Vanessa219** [comment]
关于 UI 每个用户需求不一样，目前这样是参考其产品给出的一个较为合理的展现方式。如果有特殊需求可以使用 css 代码片段进行修改。
