### ISSUE TITLE
Embed websites can store cookies/sessions

### ISSUE THREAD

**Issue by Shina-SG** [siyuan-note/siyuan#10501]
### In what scenarios do you need this feature?

Able to save account on embed website without having to login everytime reopen

### Describe the optimal solution

Currently I don't know much since iframe can do so much, so any work around or potential lead is very much helpful, thanks

**Comment by 88250** [comment]
Hello, we have no restrictions. If you need to log in again, it may be that the expiration time of the cookie on the target website is short.
