### ISSUE TITLE
Support click to open virtual reference on mobile

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#10513]
### In what scenarios do you need this feature?

桌面版本鼠标悬浮即可看到对应的引用，iOS 版无悬浮鼠标操作，可否增加点击进入功能

### Describe the optimal solution

如上

**Comment by Jiangshuon** [comment]
> 虚拟引用会涉及到多个块，点击进入编辑的话只能进入第一个，不全。

能点击进入一个块总比完全无法点击要好，希望大佬还是加上，目前该功能在移动端几乎无法发挥作用，明明这么好用的功能(ಡωಡ)
