### ISSUE TITLE
Link type in database doesn't support the anchor text

### ISSUE THREAD

**Issue by amatya-aditya** [siyuan-note/siyuan#10512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Anchor text of the link type not supported in the database.
![image](https://github.com/siyuan-note/siyuan/assets/63241408/97707c30-2d89-45dd-9d0b-ce1b2242a1f0)

### Expected result

I'm expecting to see the anchor text of the link (database type) when added to the database. This is because of the reason that the pdf does have longer links when uploaded to SiYuan. It makes database messy.

### Version environment

```markdown
- Version: 3.0.2
- Operating System: Windows x64
- Browser (if used):
```

### Log file

I don't think log file is required. If required, I can send it.

**Comment by TCOTC** [comment]
I agree with
