### ISSUE TITLE
Importing Markdown no longer refreshes the entire interface

### ISSUE THREAD

**Issue by amatya-aditya** [siyuan-note/siyuan#10510]
Everytime I import the markdown file, it flashes and restarts from Refresh window

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

As soon as I select the markdown file to import, it flashes and starts from the refresh windows. 

### Expected result

Can this be done smoothly, maybe in the background using the progress button?

### Version environment

```markdown
- Version: 3.0.2
- Operating System: Windows 64
- Browser (if used):
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/03/05 09:22:25 runtime.go:74: kernel is booting:
    * ver [3.0.2]
    * arch [amd64]
    * os [Microsoft Windows 11 Home]
    * pid [5300]
    * runtime mode [prod]
    * working directory [C:\Users\ConvolutedMind\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuan]
I 2024/03/05 09:22:26 conf.go:278: upgraded from version [3.0.1] to [3.0.2]
I 2024/03/05 09:22:26 runtime.go:123: use network proxy [system]
I 2024/03/05 09:22:26 serve.go:115: kernel [pid=5300] http server [0.0.0.0:6334] is booting
I 2024/03/05 09:22:27 serve.go:128: reverse proxy server [0.0.0.0:6806] is booting
I 2024/03/05 09:22:28 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=D:\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/03/05 09:22:28 conf.go:1039: pandoc initialized, set pandoc bin to [D:\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/03/05 09:22:29 blocktree.go:495: read block tree [231 kB] to [D:\SiYuan\temp\blocktree], elapsed [1.14s]
I 2024/03/05 09:22:29 conf.go:795: database size [2.9 MB], tree/block count [34/813]
I 2024/03/05 09:22:29 working.go:192: kernel booted
I 2024/03/05 09:22:32 box.go:76: auto stat [trees=34, blocks=813, dataSize=114 MB, assetsSize=81 MB]
I 2024/03/05 09:22:32 disk.go:33: disk usage [total=324 GB, used=300 GB, free=24 GB]
I 2024/03/05 09:25:12 file.go:1468: removed doc [20240217184121-bv6s9k2/20240304115117-4v8otgu.sy]
W 2024/03/05 10:24:13 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/05 10:24:18 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/05 10:24:23 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/05 11:07:36 blocktree.go:552: save block tree [size=42 kB] to [D:\SiYuan\temp\blocktree], elapsed [2.35s]
W 2024/03/05 11:13:23 blocktree.go:552: save block tree [size=53 kB] to [D:\SiYuan\temp\blocktree], elapsed [2.24s]
I 2024/03/05 11:16:51 file.go:1468: removed doc [20240217184121-bv6s9k2/20240305110706-pe3kdfu/20240305110652-48xkc2x.sy]
I 2024/03/05 11:16:56 file.go:1468: removed doc [20240217184121-bv6s9k2/20240305110706-pe3kdfu/20240305111243-ijtuvsi.sy]
W 2024/03/05 11:16:59 blocktree.go:552: save block tree [size=68 kB] to [D:\SiYuan\temp\blocktree], elapsed [2.85s]
I 2024/03/05 11:17:00 file.go:1468: removed doc [20240217184121-bv6s9k2/20240305110706-pe3kdfu/20240305111557-elwyry3.sy]
W 2024/03/05 11:17:06 blocktree.go:552: save block tree [size=31 kB] to [D:\SiYuan\temp\blocktree], elapsed [2.04s]
W 2024/03/05 11:17:58 blocktree.go:552: save block tree [size=44 kB] to [D:\SiYuan\temp\blocktree], elapsed [2.27s]

**Comment by Vanessa219** [comment]
fa1e63302f467066c54c046959424a756faed356

**Comment by amatya-aditya** [comment]
I'm using open quicksnippets menu plugin to toggle on and off some CSS. While doing that, it refreshes the entire interface. Could you solve that too?

**Comment by amatya-aditya** [comment]
Can this feature of toggling on/off the CSS from the homepage just like in the plugin be integrated as the core feature of SiYuan? It would be a great enhancement to the already available feature.

**Comment by Vanessa219** [comment]
Most users probably won’t use this feature very often, so it won’t be added to the homepage at the moment. I’m very sorry.

**Comment by Vanessa219** [comment]
We have many functions, and it is impossible to add all the buttons that users have common needs on the homepage. If possible, the plug-in author can make modifications. I hope you understand.
