### ISSUE TITLE
通过剪切和粘贴来移动嵌入块,会导致嵌入块直接失效,而且剪切的位置仍然保留此前的渲染

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1051]
https://user-images.githubusercontent.com/38101170/104533262-0584ec80-564d-11eb-8f61-e936cb4e3e07.mp4

**Comment by Andy-AO** [comment]
重启之后变成这样了

![image](https://user-images.githubusercontent.com/38101170/104533335-29483280-564d-11eb-8f2e-bb59bfd0ad1e.png)

**Comment by 88250** [comment]
你好，这个问题在 061 里面应该已经修复，粘贴的时候需要选择粘贴块嵌入，默认的粘贴是块引用。
