### ISSUE TITLE
Use the path ending with `/` when loading the widget

### ISSUE THREAD

**Issue by xiaoyi510** [siyuan-note/siyuan#10520]
挂件访问地址301跳转导致nginx反向代理会报错500的问题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源挂件默认访问地址为 /widgets/drawio  
     然后他会301自动跳转到 /widgets/drawio/

思源使用了nginx反向代理之后  此操作会导致nginx 500报错

### Expected result

要么访问地址直接已 / 结尾

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/20254874/8fa5b034-4df5-47f2-8e01-0c99405eeaeb)

### Version environment

```markdown
- Version: 3.0.2
- Operating System: docker
- Browser (if used): chrome
```

### Log file

none

**Comment by 88250** [comment]
挂件的地址手动带上 `/` 能够解决问题吧？

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by xiaoyi510** [comment]
我是nginx 转发的.没办法手动带上 / 呢 挂件都是第三方开发的

**Comment by xiaoyi510** [comment]
应该让siyuan这边直接不要301跳转 或者设置增加一个 /

**Comment by 88250** [comment]
插入挂件的时候手动微末加上 / 试试

**Comment by xiaoyi510** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/20254874/d3e0754b-9a97-43a6-9a9d-a51838f2f9a8)

**Comment by 88250** [comment]
点击挂件块块标，菜单里面有。

**Comment by xiaoyi510** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/20254874/44ce9881-08bd-453b-8613-1c6df17968ae)

对不起 小弟真没看到
属性里面也没有

**Comment by 88250** [comment]
抱歉，我记错了，记成和 iframe 块一样了。稍后我看看能不能直接就请求带 /

**Comment by xiaoyi510** [comment]
还有一个304 响应导致500报错的问题  

建议在文档中写一个nginx反向代理设置以下两个能解决

```
proxy_set_header If-Modified-Since "";

proxy_set_header If-None-Match "";
```

现在就差这个301的错误解决了 反向代理就没啥问题了

**Comment by 88250** [comment]
这个修复不做已有数据订正，所以只有新插入的挂件才会以 / 结尾，请悉知。
