### ISSUE TITLE
增加仅伺服（浏览器端）或非127地址取消鉴权选项

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10529]
### In what scenarios do you need this feature?

我的情况是使用s3同步，有偶尔在多台设备（手机电脑）上快速切换操作的需求，云同步的速度太慢，开启局域网伺服需要鉴权，这样每次进入思源都要输密码真的很麻烦，因为我平时用不到密码。希望有仅伺服（浏览器端）鉴权或鉴权非127地址取消鉴权选项，这样会方便很多

### Describe the optimal solution

仅伺服（浏览器端）取消鉴权选项

### Describe the candidate solution

或鉴权非127地址取消鉴权

**Comment by 88250** [comment]
Docker 部署时可以通过环境变量 `SIYUAN_ACCESS_AUTH_CODE_BYPASS` 跳过。

其他环境伺服还是需要授权码的，谢谢。
