### ISSUE TITLE
Improve block floating window for relation and rollup values

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10527]
数据库关联文档可以点击打开或增加打开按钮

### In what scenarios do you need this feature?

如下，目前关联的文档没办法在关联列或者文档的数据库面板直接打开，这样关联功能显得只能看到关联文档却不能跳转过去，那这关联功能只是达到了字面上的关联，实际还得自己去那个数据库找到对应文档，不太合理。
![image](https://github.com/siyuan-note/siyuan/assets/63196026/f585f4a9-b887-4233-b004-27410ccfb2f0)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/b375b91b-a2a2-4a9e-8594-7c8537897bfc)

### Describe the optimal solution

建议按notion的操作方式点击文档名可以跳转
![image](https://github.com/siyuan-note/siyuan/assets/63196026/b48f5595-36a8-4e3f-9c5f-08cde8a251ec)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/6842e8e1-dd9c-46d4-8853-ecd500404203)

### Describe the candidate solution

或者增加文档打开悬浮按钮，滑到关联文档名称上方的时候显示打开文档的按钮，反正能点击跳转就行

**Comment by 88250** [comment]
如果是文档块的话应该是可以浮窗显示的，如果不能可能是 bug ，比如关联/汇总中的文档块：

![image](https://github.com/siyuan-note/siyuan/assets/873584/df3cb959-3e46-42d5-97bc-bd0a0b945c8b)

目前只有悬浮汇总中的会显示，关联中的不会，并且下划线不统一 @Vanessa219

属性面板中这两种类型都不能悬浮，并且下划线不统一 @Vanessa219 

![image](https://github.com/siyuan-note/siyuan/assets/873584/dc844004-a21a-43c4-935b-24df384d439e)

**Comment by 88250** [comment]
如果没有绑定块的话，目前还没有想到合适的方案，欢迎讨论。

**Comment by 88250** [comment]
好的，我们先处理绑定块的浮窗问题。
