### ISSUE TITLE
Improve interactive guidance after creating an empty doc

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10528]
https://ld246.com/article/1673160071322/comment/1709687770948?r=Vanessa#comments

**Comment by TCOTC** [comment]
我觉得像飞书这样把模板放在空白页面的底部也不错，不会干扰到正常输入：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bbef9948-d665-482f-9c3a-f57106d2a901)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f96aff36-6cd8-4a47-bda2-dda8427d7650)

**Comment by TCOTC** [comment]
还可以参考 Notion ：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d43d236e-6b28-438a-8b43-ac5f6b580eaf)

**Comment by TCOTC** [comment]
#11770

### In what scenarios do you need this feature?

新建文档的时候，正文首行可以加一行浅灰色文本，比如 `输入文本，或按下 "/" 插入元素` ：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/abe1a739-ea59-4e84-83fb-08d06587bb6b)


### Describe the optimal solution

类似这样的效果：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ec6dea04-f27c-45bb-add3-6bd14f7b2f51)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c95293dc-038c-4700-a222-6de4744f3351)

**Comment by Vanessa219** [comment]
这个好像更简洁了，只需要在第一个空段落中加一下提示。

**Comment by TCOTC** [comment]
我觉得在页面底下列出模板会比呼出菜单方便得多，点一下就能应用模板了

**Comment by Vanessa219** [comment]
新建的时候可以指定模版，好像没有必要了，如果是新手的话，默认的模版是空的。

**Comment by TCOTC** [comment]
所以没有模板的就不需要显示这个

**Comment by Vanessa219** [comment]
新用户没有模版本身就不需要显示。
老用户已经知道使用规则，感觉也不需要了。不然的话首先的去设置，然后还需要设置需要的模版。如果实在需要的话可以使用日记来替代，然后选择需要使用的模版。

**Comment by TCOTC** [comment]
那就只加一句 `输入文本，或按下 "/" 插入元素` ，模板功能留给插件实现好了。

**Comment by TCOTC** [comment]
@Vanessa219 如果文档中已经有其他内容了，就不需要一直显示「写点什么，或按下 ' / ' 查看命令」

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/de6676dc-09cb-4c24-894f-0b6b356668c3)

**Comment by TCOTC** [comment]
@Vanessa219 这个貌似是用 API 插入内容块，希望也能处理一下：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/beb2ad09-1897-499d-bab3-12724964331c)

**Comment by Vanessa219** [comment]
这个 API 前端无法拦截，需要插件作者自己处理一下

```
editorElement.querySelectorAll(".protyle-wysiwyg--empty").forEach(item => {
  item.classList.remove("protyle-wysiwyg--empty");
});
```

**Comment by jabobian** [comment]
能否提供开关，不要显示这个 ·写点什么, 或按下'/' 查看命令·
真的感觉没有必要，新建一个文档显示一片空白多好，一张白纸。看到一段重复出现的文字，脑子感觉是被重复洗脑。

这个文字以前版本本来就没有。

**Comment by Vanessa219** [comment]
高级用户用插件吧
