### ISSUE TITLE
插入图片后下面会紧接一个空行

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#10521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/32903588/5812eff6-ea75-4b78-bb39-0c6bed780e4f)

插入图片后，图片下面会紧接一个空行，无法删除，影响排版

### Expected result

去除它

### Version environment

```markdown
- Version: 3.0.2
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
无法重现，麻烦使用默认主题，禁用插件后再试一下。

**Comment by shuojie819** [comment]
[最近两个版本，插入图片，会多空行 - 链滴](https://ld246.com/article/1682663273936#comments)
图片太大了，你把图片缩小一下那个空格就跑到图后面了不会单独占一行

**Comment by Vanessa219** [comment]
我这里图片太大也不会独占一行。是不是有什么特殊操作导致的？

**Comment by shuojie819** [comment]
> 我这里图片太大也不会独占一行。是不是有什么特殊操作导致的？

![image](https://github.com/siyuan-note/siyuan/assets/72399630/f7383e46-a98b-42d2-b62c-6f2a3f62d2a5)
可以拿这张图试一下，我这里会多出空行

**Comment by 88250** [comment]
我这里也重现不了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/54d191c6-0b70-4bbb-a9d4-ef7907beeebd)

**Comment by 88250** [comment]
之前好像有个类似的问题 https://github.com/siyuan-note/siyuan/issues/8887 应该是插件、代码片段等扩展影响的。

**Comment by shuojie819** [comment]
是的，创建了一个新库无法重现。

**Comment by HowcanoeWang** [comment]
一直在用 Savor 主题，一直有这个问题

但是右键把图片宽度设置成100%，空行就自动没了

**Comment by 88250** [comment]
如果确认是主题或插件等扩展影响我们就关闭 issue 了哦？

**Comment by HowcanoeWang** [comment]
> 如果确认是主题或插件等扩展影响我们就关闭 issue 了哦？

不，我屏蔽了主题和插件，发现问题还在，但是新开一个工作空间就没法复现。后来经过css样式的仔细对比，发现了问题：

正常的style：
![图片](https://github.com/siyuan-note/siyuan/assets/19968935/ce21f576-cfd8-4147-9926-25cd3495a9fc)

把上面的16改成18，就是我有问题的工作空间里面的css样式

**Comment by 88250** [comment]
> > 如果确认是主题或插件等扩展影响我们就关闭 issue 了哦？
> 
> 不，我屏蔽了主题和插件，发现问题还在，但是新开一个工作空间就没法复现。后来经过css样式的仔细对比，发现了问题：
> 
> 正常的style： ![图片](https://private-user-images.githubusercontent.com/19968935/310401711-ce21f576-cfd8-4147-9926-25cd3495a9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTA1ODMsIm5iZiI6MTcwOTcxMDI4MywicGF0aCI6Ii8xOTk2ODkzNS8zMTA0MDE3MTEtY2UyMWY1NzYtY2ZkOC00MTQ3LTk5MjYtMjVjZDM0OTVhOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA3MzEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MDZlMTI0ZDBmNTI5NWRjYjVkMzM0OTQ4NmIzODE1NzllZGNhYmYwMDU1NDUzMzIyMzg0MTFiNGE0ZWJkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OBIDJl5CJgloGx4tiLRYgroa413hQ-2ylHX352V1yD8)
> 
> 把上面的16改成18，就是我有问题的工作空间里面的css样式

@Vanessa219

**Comment by HowcanoeWang** [comment]
开启savor主题，会修改上面的16为18，导致问题出现，然后关闭主题后，数字并没有恢复为默认

@royc01

**Comment by royc01** [comment]
> 开启savor主题，会修改上面的16为18，导致问题出现，然后关闭主题后，数字并没有恢复为默认
> 
> @royc01

没明白咋回事

**Comment by HowcanoeWang** [comment]
> 没明白咋回事

主题里面有修改上面css数值的代码吗？

**Comment by royc01** [comment]
那空行是什么元素的？

**Comment by HowcanoeWang** [comment]
> 那空行是什么元素的？

图片块的css，空行没有任何元素，感觉像是字体从16改成18px后，“挤”下去的

**Comment by royc01** [comment]
> > 那空行是什么元素的？
> 
> 图片块的css，空行没有任何元素，感觉像是字体从16改成18px后，“挤”下去的

那跟主题应该没关系，字号大于18的时候，大图片贴进去好像就会有空行 @88250

**Comment by HowcanoeWang** [comment]
> > > 那空行是什么元素的？
> > 
> > 
> > 图片块的css，空行没有任何元素，感觉像是字体从16改成18px后，“挤”下去的
> 
> 那跟主题应该没关系，字号大于18的时候，大图片贴进去好像就会有空行 @88250

我的思源设置里，字号确实是18。。。破案了，思源前端需要改一下 @Vanessa219

**Comment by 88250** [comment]
这问题我印象里可能存在好几年了，看来有希望解决 😂

**Comment by Vanessa219** [comment]
终于破案了，下个版本改进。
