### ISSUE TITLE
去除重复搜索结果

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#10526]
### In what scenarios do you need this feature?

我的文本内容只有这些
<img width="296" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/1b650069-403c-427d-840d-f3c9940b2a0d">

但是搜索结果却有三个，指向的块是一样的，只是块的类型不同
<img width="553" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/b4497b1a-8bdd-4bcc-95e0-271c34b090dc">

一条相关内容能否只显示一个搜索结果，特别是文档多的时候，很展示很多搜索结果，体验很差

### Describe the optimal solution

一条相关内容能否只显示一个搜索结果

**Comment by 88250** [comment]
可配置 搜索类型 进行过滤。

**Comment by kylehz** [comment]
这个搜素类型可以保存上一次的设置吗，不然每次搜索都要重新过滤
<img width="544" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/15665498-cfec-46f4-a699-7db1b759f3f9">

**Comment by 88250** [comment]
使用 保存查询 条件
