### ISSUE TITLE
数据库界面，能否添加一个搜索按钮，方便搜索本数据库内的数据条目？

### ISSUE THREAD

**Issue by songshua295** [siyuan-note/siyuan#10524]
### In what scenarios do you need this feature?

对于数据库单个条目的搜索功能目前好像比较鸡肋，使用ctrl p或者ctrl f都只是会弹出对应内容所在的数据库，并不会跳转到内容所指定的位置。

### Describe the optimal solution

添加一个搜索按钮，支持模糊搜索条目
![image](https://github.com/siyuan-note/siyuan/assets/65521386/8c37df08-856b-4715-ac1f-ba93d098b27d)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10419
