### ISSUE TITLE
数据库关联后未显示对应文档

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下图，点击关联文档后，会出现未找到相关内容，搜索会搜不到的已解决，现在是没有把已关联的文档固定下来，似乎也是跑了一遍旧代码的搜索有很大概率没有遍历到，刷新文档有几率正常显示。备注：文章库有135篇文章，版本为最新3.0.3 dev1
![image](https://github.com/siyuan-note/siyuan/assets/63196026/860fee92-3090-47a2-ae18-d5298eb3df2c)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/837fbb22-048f-4a87-b605-668b1e71799d)
下图更为直观，有24个已关联文档，实际显示的不足10个
![image](https://github.com/siyuan-note/siyuan/assets/63196026/0635714a-2b43-4eba-a704-0227202a5e45)

### Expected result

可以正常显示已关联文档，当然算不上大问题，就是有点难受

### Version environment

```markdown
- Version: 3.0.3 dev1
- Operating System: win10
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
感谢反馈，在 https://github.com/siyuan-note/siyuan/issues/10523 中继续改进。

对于已经关联的条目完全显示的话可能会卡，我们还是只固定列出部分来比较好。
