### ISSUE TITLE
搜索时左边不应该显示出来网址而是应该显示锚文本

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#10537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/98648589/b1d1f317-db7c-49d2-b50c-eb6c73693ec0)
希望搜索结果中把网址仍然时按照锚文本的形式展示，不然会很混乱看不懂是什么

### Expected result

如上

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这是特性，有的时候需要按路径搜索。
