### ISSUE TITLE
资源文件引用检测存在一些极端个例

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#10530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

# 案例1: 同时出现在未引用资源和丢失的资源文件中

使用几年下来，仅此一例，尚未找到复现方法。

一个excel文件，同时出现在未引用资源文件和丢失的资源文件中，重建索引并不能解决这个问题

**有没有可能是日语文字造成的影响？**

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/0075e8dc-1279-4dcc-aab4-6238c4d68ae7)

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/92d584ae-d948-40c7-bff7-f818904aef21)

但是在正文中和assets中是存在的：

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/cb50c4f1-9e92-412b-a13f-ec8ed15f509e)

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/7ed5ca0f-8ffc-4765-8134-fb9ac6b7c7da)

# 案例2: pdf的矩形框标注产生的图片，正文中使用了但是出现在未引用资源列表中：

感觉是某个版本的bug，后续再也没遇到过

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/6ef923aa-936e-411a-a086-db9be5a13ea9)

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/b4b6e67b-51da-4aeb-9c0b-36e64d6eb8dc)

---

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/6dd2bca6-36b5-4776-928c-32853ba902fb)

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/b2579733-35db-4b5c-bb64-96a7e43157f8)

### Expected result

后续都没有出现，感觉是某个版本的遗留问题。但如果有兴趣研究的话，我可以分享数据库供debug

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

NA

**Comment by 88250** [comment]
如果目前版本无法重现的话暂时忽略了，如果能够重现，估计需要提供测试数据集 845765@qq.com

我先关闭 issue 了，谢谢。
