### ISSUE TITLE
分享到社区：文章发布后视频资源无法打开

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文章sy：
[思源iOS快捷指令：保存文本至思源.sy.zip](https://github.com/siyuan-note/siyuan/files/14517911/iOS.sy.zip)
发布后的链接：https://ld246.com/article/1709644656556

### Expected result

如上所述。

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你好，订阅用户支持单个文件 10MB，免费用户 3MB

参考 https://github.com/siyuan-note/siyuan/issues/2004
