### ISSUE TITLE
HTML Widget Issue: CSS Hover Effects and JavaScript Not Working

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Recently, I was testing the HTML widget of SiYuan and I noticed that some CSS code doesn't work at all. For example, in this video, you can see that when I hover over the numbers, they don't show up, even though I've tested this in an .html file and it worked flawlessly. Also, I noticed that JavaScript `<script>` tags don't work either.

### Expected result

When integrating custom HTML and CSS into the SiYuan HTML widget, the following behaviors are expected:

1. **CSS Hover Effects:** CSS code, especially hover effects, should be fully functional within the widget. For instance, when a user hovers over elements (such as numbers or links), any specified CSS hover effects should be triggered and visible to the user. This functionality should mirror the behavior observed when the same HTML and CSS code is tested in a standalone `.html` file outside of SiYuan.

2. **JavaScript Execution:** JavaScript code embedded within `<script>` tags should execute as intended within the HTML widget. This includes any DOM manipulations, event listeners, or dynamic content changes triggered by the JavaScript code. The execution and outcome of the JavaScript should be consistent with its performance when the code is run in a standard web environment.

### Screenshot or screen recording presentation

Recorded SiYuan Video:

https://github.com/siyuan-note/siyuan/assets/36538038/5a273e42-6ed4-4015-bb9c-9aa148132d86

Recorded Browser Video:

https://github.com/siyuan-note/siyuan/assets/36538038/8b415667-b835-4aec-9d87-83991d48a7b0

### Version environment

```markdown
- Version: v3.0.2
- Operating System: Windows 11 Pro
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14543512/siyuan.log)

**Comment by Vanessa219** [comment]
Use `:host` instead of `:root`

**Comment by MrIntellectX** [comment]
Thanks, I tried `:host` and it works, but I tried another example with JavaScript in the HTML widget seems not to be working.

As you can see, this works in the browser. When I press the toggle button, it works properly.

https://github.com/siyuan-note/siyuan/assets/36538038/c75e4746-9bb5-421d-b307-ca43f6f0d2e0



But when I click on that HTML widget toggle button, it's not working.


https://github.com/siyuan-note/siyuan/assets/36538038/2de7fdd8-93f4-4707-891b-381c3c7845e2


Here's the code for reference:
    
[Toggle_Button.txt](https://github.com/siyuan-note/siyuan/files/14547828/Toggle_Button.txt)


Any help would be appreciated.

**Comment by Vanessa219** [comment]
We use [Custom Elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements) to render html code block. So to access the dom use `shadowRoot`

For example:
````
// id is your html block id
const iframeWidget = document.querySelector(`[data-node-id="20240310103238-3j71s17"] protyle-html`).shadowRoot.querySelector(".iframe-container")
````
