### ISSUE TITLE
Feature Request: Add Support for Aggregate Functions in SQL Queries for Embedded Blocks

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10548]
### In what scenarios do you need this feature?

Currently, when using SQL queries on embedded blocks, we're unable to execute aggregate functions (e.g., SUM, AVG), the query does not return the expected result.

![SiYuan_4RWvcIdbyk](https://github.com/siyuan-note/siyuan/assets/36538038/e82a45ac-31c4-4b41-a5d3-7559205e4d8c)

![SiYuan_I1OZRitvVq](https://github.com/siyuan-note/siyuan/assets/36538038/59afa7d6-b2d8-442e-94f1-8eee7a7ff1d8)

### Describe the optimal solution

The optimal solution would involve supporting the SQL query processing capabilities for embedded blocks to fully support aggregate functions, such as `SUM()`, `AVG()`, `COUNT()`, etc. For instance, if a user wants to calculate the total price of items within a block, they should be able to use a query like:

SELECT SUM("Price") AS total_price FROM blocks WHERE id='20240226045157-aamgpcf'

**Comment by 88250** [comment]
Hello, embed blocks only support the full field projection of the blocks table, that is, "SELECT *". If other calculations are needed, please consider implementing it through the development of widgets or plugins. Thank you for your feedback.

**Comment by MrIntellectX** [comment]
First and foremost, I want to express my sincere gratitude for your hard work and dedication to improving the SiYuan app. I've been using it for a few weeks now, and I'm really impressed with how much it helps me get things done. I'm even thinking about upgrading to the premium version because of how useful it's been and also I want to support as well.

I wanted to share a couple of thoughts on how the app could be even better. Right now, I love that we can use "SELECT *" for embed blocks, but it would be amazing if the app could do more SQL queries natively built right in. Implementing these features natively could streamline the user experience and make the app even more powerful and accessible.

I'm also excited about the new features like kanban and gallery views that have already been added to the roadmap. I'm eagerly really looking forward to them. One thing I've found a bit tricky, though, is that some plugins, especially excelidraw, aren't in English, and I know I've already raised that request on the excelidraw plugin, and now all I can do is just hope someday the dev will bring the next update. I really like how Obsidian has a native visual board, and I'm hoping for something similar in SiYuan in future.

I know adding these features and making changes is a big job, but I think they could really help make SiYuan even better, especially for users from different parts of the world.

Thanks again for all your amazing work on SiYuan. I can't wait to see how it keeps getting better. Your efforts are truly appreciated, and I'm really grateful for everything you've done.

**Comment by MrIntellectX** [comment]
I just noticed that we can't use `data-col-id`, but we can use `data-node-id`, which is the database table block ID. It would be better if we could also use `class="av__calc av__calc--ashow"` -> `data-col-id` in embedded blocks, as shown in the picture below.


![image](https://github.com/siyuan-note/siyuan/assets/36538038/95f91749-1123-426d-ac87-4c575c60290b)
