### ISSUE TITLE
Display the database title on the block superscript

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10545]
内容块数据库角标显示数据库标题

* https://ld246.com/article/1706364438422
* https://ld246.com/article/1709884600899

**Comment by AvoidantPerDis** [comment]
强烈支持，之前我就提了https://github.com/siyuan-note/siyuan/issues/10033

**Comment by 88250** [comment]
@AvoidantPerDis 这个只是在角标上显示数据库标题，不是显示属性。
