### ISSUE TITLE
使用AI功能的时候不会影响操作

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10543]
### In what scenarios do you need this feature?

你现在使用AI的时候，它会出个进度条，一直在那里动，以至于他那个进度条跑完之前，你什么都不能做。然而，由于国内的环境问题，哪怕你通过特殊手段来使用AI。也会有个十几秒的处理过程。然后这段时间就什么都做不了，只能在那里等着。

### Describe the optimal solution

使用AI功能的时候，它在后台工作，不影响前台，我前台仍然可以继续阅读或者做笔记

这个功能结合把AI内容放到引述块，就完全不影响AI使用的同时做其他的事情。

简单说就是使用AI之后会出一个提示，说这在使用AI。使用完成之后，他会跟你说，使用完成。这时候，再去看引述块里的内容。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10540
