### ISSUE TITLE
failed: invalid character ':' after array element

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我135篇文章的文章库好像打不开，其他数据库能正常打开，帮忙看看是哪可能出问题了，我也排查下

![image](https://github.com/siyuan-note/siyuan/assets/63196026/35eb4195-9576-4ae6-ac0b-33f35f3c4d10)

### Expected result

无报错

### Version environment

```markdown
- Version: 3.0.3 dev2
- Operating System: win10
- Browser (if used):
```

### Log file

I 2024/03/08 11:49:11 disk.go:33: disk usage [total=511 GB, used=129 GB, free=382 GB]
E 2024/03/08 11:49:12 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:12 node.go:576: parse attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:12 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:12 attribute_view.go:612: parse attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:12 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:12 node.go:555: parse attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:49:19 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:50:42 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:50:42 node.go:576: parse attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:50:42 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:50:42 attribute_view.go:612: parse attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:50:42 av.go:239: unmarshal attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element
E 2024/03/08 11:50:42 node.go:555: parse attribute view [20240215114822-0p947vw] failed: invalid character ':' after array element

**Comment by 88250** [comment]
麻烦导出 .sy.zip 给我们测试。

最好是出问题的一份，还有出问题之前（可以通过快照回滚）的一份以便对比。

**Comment by 5kyfkr** [comment]
> 麻烦导出 .sy.zip 给我们测试 [845765@qq.com](mailto:845765@qq.com)
> 
> 最好是出问题的一份，还有出问题之前（可以通过快照回滚）的一份以便对比。

已发送问题文档，在手机旧版的3.02是显示正常的，只有在3.0.3 dev2显示报错

**Comment by 88250** [comment]
已经定位到问题，下午修复。

另外，因为改了底层数据结构，后面升级以后旧版本估计会报错。

**Comment by 5kyfkr** [comment]
> 已经定位到问题，下午修复。
> 
> 另外，因为改了底层数据结构，后面升级以后旧版本估计会报错，得所有设备都更新到最新版。

没问题，对我这个升级狂魔这点小事
