### ISSUE TITLE
能够将AI反馈的文字放到引述里，而不是直接插到正文里。

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10542]
### In what scenarios do you need this feature?

现在出现这样的情况，就是如果你在正文中间使用AI功能的话，它就会把AI反馈的文字插入到。这个块和下一个块的中间。
这样就模糊了AI的文字和原本文字之间的界限。

### Describe the optimal solution

最好能够把AI的文字放到引述块输入里面，这样能够非常清晰明了的看到AI的文字是在哪里，也不会干扰自己进一步的阅读文章接下来的相关内容。

**Comment by 88250** [comment]
应该可以提示 AI 返回的内容用 `>` 开头，即让 AI 知道你需要以什么格式返回。
