### ISSUE TITLE
支持 PlantUML 在线渲染

### ISSUE THREAD

**Issue by shirayner** [siyuan-note/siyuan#1054]
希望增加一些绘图工具的支持： 比如 Plant uml 等

**Comment by 88250** [comment]
你好，咨询一下 PlantUML 好像需要服务端支持对吗？

**Comment by 88250** [comment]
目前已经支持一些绘图库了，但是需要服务端支持的库比较麻烦，暂时不考虑了，谢谢。

**Comment by shirayner** [comment]
> 你好，咨询一下 PlantUML 好像需要服务端支持对吗？

PlantUML 确实需要服务端支持。好吧

**Comment by Vanessa219** [comment]
http://www.plantuml.com/plantuml 先用这个顶顶，后期支持用户配置自己的的服务端吧。

**Comment by 88250** [comment]
> http://www.plantuml.com/plantuml 先用这个顶顶，后期支持用户配置自己的的服务端吧。

https://github.com/siyuan-note/siyuan/issues/3671
