### ISSUE TITLE
database 展示优化

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10553]
### In what scenarios do you need this feature?

多行文本如果开启了换行功能，其他列的内容的展示就不居中了，是位于偏上的位置。
其他列数据垂直居中展示会不会更好些。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/a783b2cf-74d7-4baa-95db-e8189d4dc77d)

### Describe the optimal solution

RT

**Comment by Vanessa219** [comment]
如果行太高的话可能居中也不太好，如果个人喜欢的话可以使用 css 代码片段修改看看。
