### ISSUE TITLE
BUG：从asset中复制文件A到桌面,更名为文件A1，将文件A1放入思源另外一个文档，生成文档内Link[A1]，[A1]仍是引用的asset中的文件A。

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

从asset中复制文件A到桌面生成文件A1，将文件A1放入思源另外一个文档，生成文档内Link[A1]，[A1]仍是引用的asset中的文件A。

### Expected result

如题

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

需要的话可以提供复现视频。

**Comment by 88250** [comment]
这个是特性，数据相同的文件会自动复用，不占用额外空间。
