### ISSUE TITLE
关联列筛选只能筛选了第一个添加的文档名称

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图，数据库一个项目关联了两个文档，只能筛选出关联的第一个文档的字段，第二个及以后的关联文档无法被筛选出
![image](https://github.com/siyuan-note/siyuan/assets/63196026/059f48e0-0508-4769-a0db-6cdc47f018c5)

### Expected result

应能筛选所有关联的文档名称 

### Version environment

```markdown
- Version: 3.0.3 dev3
- Operating System: win11
- Browser (if used):
```

### Log file

无报错

**Comment by 88250** [comment]
感谢反馈，稍后改进。
