### ISSUE TITLE
筛选后增加列自动填充的标签不正确

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

筛选后增加列自动填充的标签不正确，会产生多余的标签

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/e0091790-f056-4489-8ff2-be45caee6a7f)

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/04cffd7a-bea1-4637-8977-98db25fc7d32)

### Expected result

仅产生筛选中的标签

### Version environment

```markdown
- Version: v3.0.3-dev4
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by 5kyfkr** [comment]
我觉得筛选的视图下应该自动把筛选的项目赋在新行上，现在好像是新行默认不添加任何属性，这样总是需要在一个不包含的筛选的视图下才能看到新建的行，比较不方便新建

**Comment by 88250** [comment]
@zxhd863943427 目前是使用上一行的值填充的，这样便于新建行时沿用。

@5kyfkr 如果筛选的列也用作排序的话不会填充。

**Comment by zxhd863943427** [comment]
> @zxhd863943427 目前是使用上一行的值填充的，这样便于新建行时沿用。
> 
> @5kyfkr 如果筛选的列也用作排序的话不会填充。

但是，我的新建是使用了开头的新建。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/83903674-c74d-46da-b386-fda689095b5e)

这个应该是没有上一行的概念的吧。

**Comment by 88250** [comment]
是按照最后一行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 晚上7:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 筛选后增加列自动填充的标签不正确 (Issue #10557)




  
@zxhd863943427 目前是使用上一行的值填充的，这样便于新建行时沿用。
 
@5kyfkr 如果筛选的列也用作排序的话不会填充。
  
但是，我的新建是使用了开头的新建。
 
default.png (view on web)
 
这个应该是没有上一行的概念的吧。

**Comment by zxhd863943427** [comment]
那我觉得这就不符合认知了……我觉得最多只用在选定行的上下使用相同填充，其他情况使用筛选填充就行了。

昨天我在录入书签时频繁删除多选很麻烦的。

**Comment by 88250** [comment]
确实应该使用“最近的”行相关值来填充，稍后改进。

**Comment by zxhd863943427** [comment]
我的意思是，最多只有这个需要：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/d482191b-362b-43c5-b2c4-90f72ca52bf1)

其他情况只使用筛选值填充即可。

**Comment by 88250** [comment]
不能按筛选值填充的，要看筛选的操作符。这个计算太复杂了，所以沿用“最近的”行方案比较折中。
