### ISSUE TITLE
闪卡面包屑类remnote界面

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10551]
### In what scenarios do you need this feature?

![如图](https://img2.imgtp.com/2024/03/09/VuMnZnv3.png)
除移动端均可使用插件完成，对于结构化的知识，面包屑的作用相当重要
移动端的面包屑可以说完全起不到这种作用

### Describe the optimal solution

1. 移动端折行显示面包屑
2. 显示标题面包屑，前面插件替代
3. 实在不行，与pc端同步样式

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10012
