### ISSUE TITLE
开启伺服后，在firefox浏览器中 插件搜索区的高斯模糊不显示

### ISSUE THREAD

**Issue by hsopen** [siyuan-note/siyuan#10559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

开启伺服后，在firefox浏览器中 插件搜索区的高斯模糊不显示
![图片](https://github.com/siyuan-note/siyuan/assets/61812401/c817498e-7f34-42a6-a209-b03ff09747ea)

### Expected result

![图片](https://github.com/siyuan-note/siyuan/assets/61812401/547483f5-4a70-48de-9cbf-d9b83c8a5020)

### Version environment

```markdown
- Version: 3.0.2
- Operating System: windows
- Browser (if used): firefox
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14546574/siyuan.log)

**Comment by 88250** [comment]
没有兼容支持 Firefox，仅支持 Chrome，感谢反馈。
