### ISSUE TITLE
Optimize document moving and renaming performance

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#10560]
在现在文档树文件移动文件是否过于慢了

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

虽然不是最新版，但也没离几个版本。

就也没多少个文件，就文档树文件普通移动，但是现在就是这么多一个包含子文件的文件移动到其他文件下，甚至同级移动改一个顺序就要花很多时间，已经感觉不能忍受了。反馈看看是不是BUG问题
![image_74](https://github.com/siyuan-note/siyuan/assets/97731736/dcbb9132-dd7a-4290-96c3-826ab299e47f)

### Expected result

文件普通移动操作不应该花费这么长时间。

### Screenshot or screen recording presentation

1

### Version environment

```markdown
- Version: v2.12.8
- Operating System: 
- Browser (if used):
```

### Log file

[部分日志.txt](https://github.com/siyuan-note/siyuan/files/14547230/default.txt)

**Comment by UFDXD** [comment]
另外备注，我最后移动操作移动的文件就是截图中的这个文件，就是同级移动改个顺序，就花费了漫长的时间。

**Comment by 88250** [comment]
是移动的父文档还是多选子文档移动？

**Comment by UFDXD** [comment]
@88250

  都有吧，子文档也可以是有子文档的吧。这个使用场景上无法小心的区分开来，不然的放着移动父文档不用，要展开子文档要一个一个多选有些离谱（存在限制展开多少子文档选项，如果子文档很多超过200，我限制显示100，那么多的就无法手动选择完全，即使花时间一个一个手点和还有一个shift+下批量快捷选中都是不方便的和无法全部选中的）。


还有反馈一个类似的性能问题，如果这个文档有很多子文档子文档正常有自己的子文档，那么像上面截图的体量文件的话，改变文件名就会缓慢。现象就是，文档打开的文档名是已经改好了，但是文档树的文档名没有变（有时候看文档树的没变会重新改一次，然后我怀疑后台会重新加入队列任务重新跑一边改动），下栏可以看到后台在以一个小批量一次的比较缓慢的速度改变着什么。

**Comment by 88250** [comment]
目前的逻辑是移动文档超过 16 个的话（不算子文档，只算移动的这一层）会弹进度遮罩 https://github.com/siyuan-note/siyuan/issues/9356

目前的实现代码暂时找不到优化空间了，主要是移动的时候需要加载解析文档和在文件系统上移动文件，如果子文档很多的话确实会比较慢。

移动和重命名逻辑上是一样的，都需要修改 hpath，所以重命名也会比较慢。

我关闭了，后续如果有优化空间的话再打开，感谢反馈。

**Comment by 88250** [comment]
下个版本会优化索引性能，麻烦帮忙对比测试 https://github.com/siyuan-note/siyuan/issues/10624

**Comment by UFDXD** [comment]
@88250 好的

**Comment by UFDXD** [comment]
@88250  还是这个文件（包含这么多子文件），尝试移动到它的父级。时间感官上花了将近半个小时（看直播去了），可能有速度提升吧，但是和还是比较慢。
[部分日志.txt](https://github.com/siyuan-note/siyuan/files/14634153/default.txt)

**Comment by UFDXD** [comment]
发现这个用户和我差不多的的问题，不过还没有被回复，这里贴一下关联一下。https://ld246.com/article/1710474212925

**Comment by 88250** [comment]
看一下启动后打印的数据量日志，就是这一部分：

```
I 2024/03/18 20:00:00 conf.go:807: database size [1.4 GB], tree/block count [10077/509386]
I 2024/03/18 20:00:00 working.go:192: kernel booted
I 2024/03/18 20:00:01 box.go:76: auto stat [trees=10077, blocks=509386, dataSize=1.3 GB, assetsSize=974 MB]
```

移动文档后需要批量重建索引，这样才能保证搜索路径和引用路径的正确性，以目前的结构来看，优化空间很小了。

估计只能考虑将不常用的文档存档以降低总的数据索引量来顶顶了。

**Comment by UFDXD** [comment]
@88250 对我来说不可能封存的，因为我是引用当标签的呀，就是通过标签反链（这是思源的优势而且实际体验下来只要标签打的好非常好用，现在我大到文档小到碎片信息一句话打上标签就丢文档里面了），日后在笔记里找素材的时候就是能看到丢在那个角落的文档。封存了就没记笔记的意义了。而且现在移动文档速度感人，不敢大批量移动。总之我觉得如果现阶段找不到优化办法的话，后面每个深度思源笔记用户都会遇到这个问题（除非完全砍了文档树，但以现在用户体量来说不现实，而且文档树有文档树的优势）相信会有越来越多用户反映（其实应该有不少用用户发现了，但是就像我对思源有极大的忍耐性，因为思源是敏捷开发BUG多是常是但都在两到三个小版本内就解决了，所以都看看是否有其他人提，都有观望性，不到难受到极点自己是不会说的）

**Comment by UFDXD** [comment]
@88250 总之如果实在没有优化办法的话，就只能将就这用了。

**Comment by TCOTC** [comment]
@UFDXD 只能说预先一次性设计好笔记本的层级和架构，整理一遍，之后尽可能少大批量移动文档

**Comment by TCOTC** [comment]
@UFDXD 我今天也在整理文档树，因为文档不多所以没什么感觉。看来以后也要注意了。

**Comment by TCOTC** [comment]
好吧，刚才移动了一个子文档稍微多点的，卡住10秒，确实太慢了

**Comment by UFDXD** [comment]
😥

**Comment by 88250** [comment]
目前性能瓶颈主要在修改块的 HPath 上 https://github.com/siyuan-note/siyuan/blob/95764092ecea75d0c6e7c8e59839d7bec9d5b2f0/kernel/sql/database.go#L1214

各位有空可以帮忙想想办法。

**Comment by TCOTC** [comment]
整理文档树会时不时卡住几十秒真的是灾难，希望有办法优化🙏

另外问了一下 GPT-4 ，回复可能没什么卵用，但还是附在这里了：

> 针对您提供的代码和描述的性能瓶颈问题，我会给出一些建议来尝试提高性能。
>
> ##### 1. 批量更新
>
> 首先，如果 `batchUpdateHPath` 函数被频繁调用，每次只更新少量记录，那么可以考虑将多个更新操作合并为批量更新，以减少数据库操作的次数。但是，基于您提供的代码片段，这里的更新操作已经是针对特定条件的批量更新，因此这个建议可能不适用。
>
> ##### 2. 索引优化
>
> 确保 `blocks` 和 `blocks_fts` 以及 `blocks_fts_case_insensitive` 表上的 `box` 和 `root_id` 字段有适当的索引。缺乏索引会导致更新操作非常缓慢，尤其是在大数据量的情况下。
>
> ##### 3. 减少不必要的更新
>
> 如果 `hpath` 的新值与旧值相同，那么不执行更新操作可以节省时间。这需要您在代码中添加逻辑来检查 `hpath` 是否真的发生了变化。
>
> ##### 4. 并行处理
>
> 如果业务逻辑允许，并且您的数据库能够处理并发写入，您可以考虑将更新操作分散到多个事务中并行执行。但请注意，这可能会增加复杂性，并且需要确保数据一致性和事务隔离级别。
>
> ##### 5. 减少事件总线的负载
>
> `eventbus.Publish` 调用可能是一个隐藏的性能瓶颈，尤其是如果它执行了一些耗时的操作，或者等待某些资源（如网络I/O）。考虑异步发布事件或优化事件处理程序。

https://github.com/siyuan-note/siyuan/blob/95764092ecea75d0c6e7c8e59839d7bec9d5b2f0/kernel/sql/database.go#L1214C1-L1233C2

**Comment by 88250** [comment]
@TCOTC 稍后我试试，多谢。

**Comment by 88250** [comment]
找到个优化方案可以大概提升 40% 的时间：

* 减少 UPDATE ... WHERE 条件，从 box AND root_id 减少为 root_id，因为 id 跨笔记本也是唯一的
* blocks 表 root_id 加索引

**Comment by 88250** [comment]
嗯，这些情况得考虑到。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Tue, Mar 19, 2024 17:28 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Optimize document moving and renamingperformance (Issue #10560)




  
输入标题时待用户确认以后（焦点离开）再调用重命名
  
如果焦点没离开就关闭了思源，不知道会不会有问题

**Comment by 88250** [comment]
和 V 讨论了下，焦点离开提交修改比较危险，容易漏提交数据，所以这部分交互暂时还是不动了，这个 issue 仅优化后端性能。

**Comment by UFDXD** [comment]
@88250  还是这个文档，这次将其还原移动到原来的父级，也就是作为子文件夹。花费时间感觉还是不容乐观。

I 2024/03/21 02:56:37 conf.go:827: database size [1.5 GB], tree/block count [3841/370223]
I 2024/03/21 02:56:37 serve.go:128: reverse proxy server [127.0.0.1:6806] is booting
I 2024/03/21 02:56:37 working.go:192: kernel booted
I 2024/03/21 02:56:39 box.go:76: auto stat [trees=3841, blocks=370223, dataSize=3.6 GB, assetsSize=3.3 GB]
I 2024/03/21 02:56:39 disk.go:33: disk usage [total=90 GB, used=32 GB, free=57 GB]
W 2024/03/21 02:56:43 file.go:360: build docs [9] elapsed [591ms]
W 2024/03/21 02:56:47 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:56:47 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:56:52 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:56:52 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:56:57 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:56:57 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:57:02 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:57:02 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:57:07 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:57:07 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:57:12 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
W 2024/03/21 02:59:16 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.02s]
I 2024/03/21 03:00:01 queue.go:157: database op tx [50293ms]
W 2024/03/21 03:00:04 blocktree.go:552: save block tree [size=89 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [2.47s]
I 2024/03/21 03:00:40 queue.go:157: database op tx [38007ms]
W 2024/03/21 03:00:48 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.07s]
I 2024/03/21 03:01:26 queue.go:157: database op tx [44645ms]
W 2024/03/21 03:01:33 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.10s]
I 2024/03/21 03:01:53 queue.go:157: database op tx [26573ms]
I 2024/03/21 03:02:24 queue.go:157: database op tx [30281ms]
W 2024/03/21 03:02:34 blocktree.go:552: save block tree [size=137 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.88s]
I 2024/03/21 03:04:47 queue.go:157: database op tx [140944ms]
I 2024/03/21 03:05:15 queue.go:157: database op tx [27561ms]
W 2024/03/21 03:05:19 blocktree.go:552: save block tree [size=136 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.70s]
I 2024/03/21 03:06:56 queue.go:157: database op tx [98266ms]
I 2024/03/21 03:07:37 queue.go:157: database op tx [40149ms]
W 2024/03/21 03:07:45 blocktree.go:552: save block tree [size=99 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [2.84s]
I 2024/03/21 03:09:01 queue.go:157: database op tx [82076ms]
W 2024/03/21 03:09:08 blocktree.go:552: save block tree [size=106 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.09s]
I 2024/03/21 03:10:46 queue.go:157: database op tx [102399ms]
W 2024/03/21 03:10:53 blocktree.go:552: save block tree [size=144 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.73s]
I 2024/03/21 03:12:35 queue.go:157: database op tx [106123ms]
W 2024/03/21 03:12:42 blocktree.go:552: save block tree [size=144 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.04s]
I 2024/03/21 03:13:43 queue.go:157: database op tx [66094ms]
W 2024/03/21 03:13:51 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.39s]
I 2024/03/21 03:13:54 queue_history.go:106: database history op tx [11114ms]
W 2024/03/21 03:14:01 blocktree.go:552: save block tree [size=147 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.69s]
I 2024/03/21 03:21:48 queue.go:157: database op tx [473899ms]
W 2024/03/21 03:21:56 blocktree.go:552: save block tree [size=147 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.04s]
I 2024/03/21 03:23:32 queue.go:157: database op tx [101505ms]
W 2024/03/21 03:23:39 blocktree.go:552: save block tree [size=88 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.29s]
I 2024/03/21 03:23:55 queue.go:157: database op tx [22307ms]
W 2024/03/21 03:24:04 blocktree.go:552: save block tree [size=147 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.28s]
I 2024/03/21 03:25:32 queue.go:157: database op tx [95392ms]
I 2024/03/21 03:26:08 queue.go:157: database op tx [35000ms]
I 2024/03/21 03:27:06 queue.go:157: database op tx [56778ms]
I 2024/03/21 03:27:37 queue.go:157: database op tx [30099ms]
I 2024/03/21 03:29:44 queue.go:157: database op tx [124567ms]
W 2024/03/21 03:29:53 blocktree.go:552: save block tree [size=148 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.26s]
I 2024/03/21 03:30:23 conf.go:565: exiting kernel [force=false, setCurrentWorkspace=true, execInstallPkg=0]
I 2024/03/21 03:30:23 database.go:1249: closed database
I 2024/03/21 03:30:23 conf.go:990: cleared workspace temp
I 2024/03/21 03:30:24 sync.go:712: sync websocket closed
I 2024/03/21 03:30:24 conf.go:635: exited kernel

**Comment by 88250** [comment]
暂时只能这样了，后面看看还有没有其他优化空间。



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 21, 2024 03:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Optimize document moving and renamingperformance (Issue #10560)




 
@88250  还是这个文档，这次将其还原移动到原来的父级，也就是作为子文件夹。花费时间感觉还是不容乐观。
 
I 2024/03/21 02:56:37 conf.go:827: database size [1.5 GB], tree/block count [3841/370223]
 I 2024/03/21 02:56:37 serve.go:128: reverse proxy server [127.0.0.1:6806] is booting
 I 2024/03/21 02:56:37 working.go:192: kernel booted
 I 2024/03/21 02:56:39 box.go:76: auto stat [trees=3841, blocks=370223, dataSize=3.6 GB, assetsSize=3.3 GB]
 I 2024/03/21 02:56:39 disk.go:33: disk usage [total=90 GB, used=32 GB, free=57 GB]
 W 2024/03/21 02:56:43 file.go:360: build docs [9] elapsed [591ms]
 W 2024/03/21 02:56:47 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:56:47 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:56:52 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:56:52 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:56:57 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:56:57 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:57:02 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:57:02 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:57:07 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:57:07 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:57:12 queue.go:141: too many tasks [task.database.index.fix], ignore show its status
 W 2024/03/21 02:59:16 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.02s]
 I 2024/03/21 03:00:01 queue.go:157: database op tx [50293ms]
 W 2024/03/21 03:00:04 blocktree.go:552: save block tree [size=89 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [2.47s]
 I 2024/03/21 03:00:40 queue.go:157: database op tx [38007ms]
 W 2024/03/21 03:00:48 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.07s]
 I 2024/03/21 03:01:26 queue.go:157: database op tx [44645ms]
 W 2024/03/21 03:01:33 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.10s]
 I 2024/03/21 03:01:53 queue.go:157: database op tx [26573ms]
 I 2024/03/21 03:02:24 queue.go:157: database op tx [30281ms]
 W 2024/03/21 03:02:34 blocktree.go:552: save block tree [size=137 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.88s]
 I 2024/03/21 03:04:47 queue.go:157: database op tx [140944ms]
 I 2024/03/21 03:05:15 queue.go:157: database op tx [27561ms]
 W 2024/03/21 03:05:19 blocktree.go:552: save block tree [size=136 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.70s]
 I 2024/03/21 03:06:56 queue.go:157: database op tx [98266ms]
 I 2024/03/21 03:07:37 queue.go:157: database op tx [40149ms]
 W 2024/03/21 03:07:45 blocktree.go:552: save block tree [size=99 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [2.84s]
 I 2024/03/21 03:09:01 queue.go:157: database op tx [82076ms]
 W 2024/03/21 03:09:08 blocktree.go:552: save block tree [size=106 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.09s]
 I 2024/03/21 03:10:46 queue.go:157: database op tx [102399ms]
 W 2024/03/21 03:10:53 blocktree.go:552: save block tree [size=144 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.73s]
 I 2024/03/21 03:12:35 queue.go:157: database op tx [106123ms]
 W 2024/03/21 03:12:42 blocktree.go:552: save block tree [size=144 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.04s]
 I 2024/03/21 03:13:43 queue.go:157: database op tx [66094ms]
 W 2024/03/21 03:13:51 blocktree.go:552: save block tree [size=146 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.39s]
 I 2024/03/21 03:13:54 queue_history.go:106: database history op tx [11114ms]
 W 2024/03/21 03:14:01 blocktree.go:552: save block tree [size=147 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.69s]
 I 2024/03/21 03:21:48 queue.go:157: database op tx [473899ms]
 W 2024/03/21 03:21:56 blocktree.go:552: save block tree [size=147 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.04s]
 I 2024/03/21 03:23:32 queue.go:157: database op tx [101505ms]
 W 2024/03/21 03:23:39 blocktree.go:552: save block tree [size=88 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [3.29s]
 I 2024/03/21 03:23:55 queue.go:157: database op tx [22307ms]
 W 2024/03/21 03:24:04 blocktree.go:552: save block tree [size=147 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.28s]
 I 2024/03/21 03:25:32 queue.go:157: database op tx [95392ms]
 I 2024/03/21 03:26:08 queue.go:157: database op tx [35000ms]
 I 2024/03/21 03:27:06 queue.go:157: database op tx [56778ms]
 I 2024/03/21 03:27:37 queue.go:157: database op tx [30099ms]
 I 2024/03/21 03:29:44 queue.go:157: database op tx [124567ms]
 W 2024/03/21 03:29:53 blocktree.go:552: save block tree [size=148 MB] to [H:\My-Instrument\Software\思源笔记\思源工作空间\temp\blocktree], elapsed [4.26s]
 I 2024/03/21 03:30:23 conf.go:565: exiting kernel [force=false, setCurrentWorkspace=true, execInstallPkg=0]
 I 2024/03/21 03:30:23 database.go:1249: closed database
 I 2024/03/21 03:30:23 conf.go:990: cleared workspace temp
 I 2024/03/21 03:30:24 sync.go:712: sync websocket closed
 I 2024/03/21 03:30:24 conf.go:635: exited kernel

**Comment by 88250** [comment]
@UFDXD 对了，要重建索引以后再测试，应该有近一半的性能提升。

**Comment by UFDXD** [comment]
@88250  连续测试了三次（其实四次）结果就是，太坐牢了。这里贴出测试结果（日志里我写了一些方便查看开始结束的备注）
[日志.txt](https://github.com/siyuan-note/siyuan/files/14692883/default.txt)

**Comment by 88250** [comment]
收到，这部分后面再看看还能不能有其他方案，如果有其他开发者看见也可以帮我们想想，多谢！
