### ISSUE TITLE
docker 部署思源，WS 反向代理是否必须配置？不配置可正常使用，配置了反而影响使用

### ISSUE THREAD

**Issue by iswbm** [siyuan-note/siyuan#10561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用 Docker 部署思源，不配置 WS 反向代理，可正常访问。但通过F12查看，ws 请求一直处于 Pending
<img width="802" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22311419/03dbb41a-29e2-440e-82a6-55b12c996dd7">

看部署文档说 WS 反向代理需要配置，于是我配置了
```nginx
        location /ws {
            proxy_pass http://127.0.0.1:6806/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'Upgrade';
        }
```
但通过浏览器访问，反而会一直提示
<img width="520" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22311419/961160ab-b481-48db-9717-b140515f7a41">
F12 的 ws 请求变成 closed 了
<img width="729" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22311419/12e4c2e4-7b57-4eed-8f7e-3edadc4ecfe9">

### Expected result

1、不配置 ws 反向，会影响什么功能吗？
2、如何在配置 ws 反向后，可正常使用？

### Version environment

```markdown
- Version: v3.0.2
- Operating System: OpenEuler
- Browser (if used): Chrome
```

### Log file

<img width="2102" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22311419/811398ad-45ed-4428-a7cc-ce3e8feb7cf0">

**Comment by iswbm** [comment]
通过学习这帖子：https://ld246.com/article/1677207724771
 ws反向代理的规则，修改如下，不会再报错
```
         location /ws {
             proxy_pass http://127.0.0.1:6806;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection 'Upgrade';
         }
```
但 F12 的ws 请求始终是 Pending，但状态又是 101，可能这种状态正常连接中吧？请问我的理解对吗？
<img width="801" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22311419/ad659e79-4513-4cd0-a5ae-8cd2aacfccff">

**Comment by 88250** [comment]
能用的话说明是对的 :)
