### ISSUE TITLE
排序状态下新增行会消失

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

排序状态：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/b85d192a-719e-46e7-bbd6-a753e175d3d2)

新增一行：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/b6e14a7e-c501-4dd6-bb4f-d954d13f327d)

自动跳到末尾：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/22ab2afa-f8ad-4384-ae1c-9566b469edcf)

出现错误内容：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/23237288-44b4-4701-825c-315259026238)

编辑：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/f3cdad16-e99a-4725-9539-324a85c1f6dc)

完成编辑：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/f75b0619-2487-431b-8bf5-13821adfcd1b)

取消排序，出现在行首，编辑内容消失：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/f09cfe12-4412-4c4c-b078-5d3b20400b9b)

### Expected result

正常新增

### Version environment

```markdown
- Version: dev6
- Operating System:win10 
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
这是设计如此，排序状态下新增行会添加到末尾，不参与排序，编辑以后才参与排序。

**Comment by zxhd863943427** [comment]
> 这是设计如此，排序状态下新增行会添加到末尾，不参与排序，编辑以后才参与排序。

问题在于它的位置被顶掉了，根本无法进行编辑操作。

**Comment by zxhd863943427** [comment]
还是发一个视频吧，我认为这不太可能是设计的效果


https://github.com/siyuan-note/siyuan/assets/74853597/9da9eeef-9319-4504-b422-a1f814dbe883

**Comment by 88250** [comment]
新建行以后右上角应该会提示不参与排序。编辑框的出现是有点问题，应该是因为分页加载了 @Vanessa219 

> 另外，使用上面的那个按钮添加，我觉得出现在行首更合理吧。

排序状态下统一添加到末尾，否则排序会混乱。

**Comment by Vanessa219** [comment]
是由于存在分页时，新增行由于排序条件导致接口没有返回。

前端目前将修改为和后端一致，不显示新增行。
