### ISSUE TITLE
database删除行后，所关联的块立刻编辑会发生错误。

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#10564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

开始状态：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/232a81f9-5eb5-40a3-b46e-924c691095af)

删除行：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/eafb9451-3926-45ee-b58e-a33935b966c3)

进行编辑：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/0c213412-46c9-4159-9175-f450b4312629)

重新打开文档：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/d030d082-34f0-40cf-807b-dcecd072a7b3)

另外打开开发者工具可以发现删除行后并没有正确删除属性，只是移除了database标

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/5307c61c-fca6-40f8-accd-c9c9567c72f1)

另外能问下为啥要填充到av-name吗？不能直接返回到protyle-attr里吗？

### Expected result

正常删除

### Version environment

```markdown
- Version: 3.0.2dev4
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
感谢反馈，下个版本修复。
