### ISSUE TITLE
Extensions can be used successfully without using the correct API token

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#10569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

拓展没有填入正常的 API token 仍可以正常使用

### Expected result

API token 错误时应报错

### Version environment

```markdown
- Version: v3.0.2
- Operating System: Windows 11
```

### Log file

null

**Comment by Temacc0531** [comment]
这个是对内网地址单独处理了无需校验吗

**Comment by 88250** [comment]
是的，对于 127.0.0.1 访问时如果不设置 API token 则也不校验。
