### ISSUE TITLE
双链、标签输入提示优化

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#10579]
### In what scenarios do you need this feature?

以标签为例。

例如，现在我有一个 #双向链接 标签。
后来我忘了我有这个标签，我输入成了 #双链 标签。
我希望在我输入 #双链 时软件就能提示我还有一个 #双向链接 标签，
也就是说，我的期望是如果已有一个 #ABCDEFG 标签，那么以后我输入 #AD #AC #BD #EG #CEF 时都能提示出这个标签。（不过输入 #GF 的时候就不要提示这个标签了）
我觉得适用场景主要是一些缩写词和全称。

<img width="366" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/d313e2ad-9b84-46eb-82d2-307c82c5d93d">

是，我知道可以后续在标签面板里修改标签名把两者合并，但是如果标签都已经成海洋了，怎么整理，根本注意不到……

双链也一样：
<img width="368" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/14eb6f3d-1d5b-48f3-8fb2-42bbcb35611b">

不过双链涉及的范围可就大了……

我不知道有没有人持反对意见？我觉得这个提议应该是对需要的人很有用，对不需要的人负担很小。

### Describe the optimal solution

.

**Comment by UFDXD** [comment]
标签，就算了。引用的话，如果是文档的话，可以给文档加别名。

**Comment by LoneFireBlossom** [comment]
> 标签，就算了。引用的话，可以给块或文档加别名。

为啥说标签就算了呢

**Comment by LoneFireBlossom** [comment]
> 标签，就算了。引用的话，可以给块或文档加别名。

双链这个加引用是个解决方法，但如果软件自己能提供更简便的解决方法就更好了。我这个提议就是在想优化思源的使用体验
