### ISSUE TITLE
Add an ordinal column to the database

### ISSUE THREAD

**Issue by allblue** [siyuan-note/siyuan#10574]
### In what scenarios do you need this feature?

When there are many rows in the database, it is easier to count them by sequence number. The ordinal number column is the same as the current check column, which is only used for database display and is not listed as a note attribute.

当数据库行目较多时，通过序号可以较容易对其计数。序号列与现在的勾选列一样，只作为数据库展示用，不列为笔记属性

![image](https://github.com/siyuan-note/siyuan/assets/844763/bd1c0a34-a19c-44c0-98a0-cf382f60561d)

### Describe the optimal solution

none.

**Comment by TCOTC** [comment]
[数据库的几个功能需求 - 链滴](https://ld246.com/article/1712645912571) Point 2

数据库条目过多时方便视觉定位

---

数据库增加行号（列），不参与排序，始终是 1、2、3、4、5……

可能作为一个视图属性（就像隐藏标题）

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/pull/11008 中跟进。
