### ISSUE TITLE
Improve menu interaction with inline elements

### ISSUE THREAD

**Issue by littlecoby** [siyuan-note/siyuan#10577]
### In what scenarios do you need this feature?

见下

### Describe the optimal solution

https://ld246.com/article/1710125974263

**Comment by Vanessa219** [comment]
剪切好像没有必要吧？

**Comment by littlecoby** [comment]
> 剪切好像没有必要吧？
> 
> 总结一下，需要改进的地方：
> 
> * [ ]  块引：-
> * [ ]  链接： [链接右键菜单增加 `复制` #11807](https://github.com/siyuan-note/siyuan/issues/11807)
> * [ ]  标签：增加复制
> * [ ]  行内公式：增加复制、删除
> * [ ]  行内代码：增加删除

剪切可以一键复制+删除，还是有用的吧，比如想移动某个元素的时候

**Comment by TCOTC** [comment]
@Vanessa219 复制和剪切的已经是标签了，粘贴出来的就应该是标签，而不是 `#` 包裹的文本：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/c2885327-0fea-4105-a7a0-1209b5fd4fa0)

**Comment by Vanessa219** [comment]
使用菜单只能写入纯文本到剪切板里面，因此复制和剪切都是 md，和 https://github.com/siyuan-note/siyuan/issues/11604 是一类问题。
