### ISSUE TITLE
数学公式块居左

### ISSUE THREAD

**Issue by yahhossu** [siyuan-note/siyuan#1057]
1、请问数学公式块如何居左？
2、行内公式的字母大小比例不协调。
3、希望能加入手动调节公式块大小的功能。
4、谢谢D大和V姐。
![image](https://user-images.githubusercontent.com/77004889/104596784-67763e00-56af-11eb-8bc9-4fc4df528674.png)

**Comment by 88250** [comment]
你好，后期考虑，谢谢。

**Comment by Clouder0** [comment]
![image](https://user-images.githubusercontent.com/41664195/104755159-12acf300-5795-11eb-8e70-5e53016d9a45.png)

对于分式太小，可以使用`\dfrac{}{}`来达到较好的显示效果。
目前看来，行内公式显示得比整行公式粗大，需要居左可以直接用行内公式 - -
```
行内公式： $2\pi\dfrac{\dfrac{as}{big}}{\dfrac{as}{\dfrac{you}{want}}}$

对照组： $2\pi\frac{\frac{as}{big}}{\frac{as}{\frac{you}{want}}}$

整行公式：

$$
\omega_n^k = 2\pi\dfrac{k}{n}
```

**Comment by yahhossu** [comment]
> 你好，后续考虑，谢谢。

好的，谢谢

**Comment by yahhossu** [comment]
> ![图片](https://user-images.githubusercontent.com/41664195/104755159-12acf300-5795-11eb-8e70-5e53016d9a45.png)
> 
> 对于看来式太小，可以使用`\dfrac{}{}`来达到更好的显示效果。
> 总体看来，行内公式显示得比整行公式粗大，需要居左可以直接用行内公式--
> 
> ```
> 行内公式： $2\pi\dfrac{\dfrac{as}{big}}{\dfrac{as}{\dfrac{you}{want}}}$
> 
> 对照组： $2\pi\frac{\frac{as}{big}}{\frac{as}{\frac{you}{want}}}$
> 
> 整行公式：
> 
> $$
> \omega_n^k = 2\pi\dfrac{k}{n}
> ```

好的，谢谢，学到了

**Comment by 88250** [comment]
我关闭了，感谢分享讨论。
