### ISSUE TITLE
使用 shift 加点击唤出属性之后，输入法会显示点击过 shift，从而由中文输入变成了英文输入

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在使用 shift 加点击换出块的属性面板之后，会转换中英文输入模式

### Expected result

希望唤出属性面板之后，shift 能够默认再按回一次，不知道笔记软件能不能实现

### Version environment

```markdown
- Version: 3.02
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
没找到改变输入法的方法，要不改一下输入法切换方式？😓

**Comment by QQQOrange** [comment]
> 没找到改变输入法的方法，要不改一下输入法切换方式？😓

好吧

**Comment by Vanessa219** [comment]
回复的好快，我还没修改完。。。
那我就关闭了哦。感谢理解。

**Comment by QQQOrange** [comment]
> 回复的好快，我还没修改完。。。 那我就关闭了哦。感谢理解。

嗯呐
