### ISSUE TITLE
改进数据库自动填充

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10573]
### In what scenarios do you need this feature?

像这种情况下希望能按顺序继续填充，而不是重复

![image](https://github.com/siyuan-note/siyuan/assets/78434827/44da6112-bed5-4f92-899c-5646c224f15e)

### Describe the optimal solution

按顺序填充数字

**Comment by 88250** [comment]
筛选启用的情况下按“最近的”行值填充才行，否则无法确保值在筛选条件内。

**Comment by TCOTC** [comment]
没有筛选，就是随便新建的数据库

**Comment by 88250** [comment]
那也可能会和建立的筛选条件冲突的，所以不考虑自动按某种规则填充默认值了。

**Comment by TCOTC** [comment]
那有没有什么方法能批量添加序号呢？

[链滴：数据库是否能增加一个序号列](https://ld246.com/article/1710138926299)
