### ISSUE TITLE
希望在块属性的数据库界面可以直接删除该行

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10581]
### In what scenarios do you need this feature?

在该页面虽然可以预览整个数据库，但是没办法直接定位到该行，需要自己进行搜索或筛选找到该行，然后删除，比较麻烦

希望右侧加一个删除按钮

![image](https://github.com/siyuan-note/siyuan/assets/67137548/9b73d7b0-64d2-4d9d-8955-0601f1beb31e)

### Describe the optimal solution

无

**Comment by 88250** [comment]
不考虑在这个位置加入删除了，面板主要还是做数据的更新，不做添加和删除，感谢反馈。

**Comment by TCOTC** [comment]
既然不加入删除，那现在有办法直接跳转到对应的数据库吗？如果能跳转到数据库的话也能很快删除

**Comment by Jiangshuon** [comment]
> 既然不加入删除，那现在有办法从属性界面直接跳转到对应的数据库吗？如果能跳转到数据库的话也能很快删除

现在可以的，鼠标移动到数据库标题的位置，会出现弹窗。但关键是不会自动定位到这一行，需要搜索、筛选才可以，所以很麻烦

**Comment by TCOTC** [comment]
> 鼠标移动到数据库标题的位置，会出现弹窗

我说怎么鼠标点击没反应，原来是浮窗

**Comment by Jiangshuon** [comment]
> @Jiangshuon 虽然没有删除按钮，但我感觉已经很快了，几秒就可以搞定：
> 
> ![数据库](https://private-user-images.githubusercontent.com/78434827/316314452-577eb7e9-1d7b-46b0-a3b5-590c4200107e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODk2OTksIm5iZiI6MTcxMTI4OTM5OSwicGF0aCI6Ii83ODQzNDgyNy8zMTYzMTQ0NTItNTc3ZWI3ZTktMWQ3Yi00NmIwLWEzYjUtNTkwYzQyMDAxMDdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE0MDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZmM2NGUzNzUzMjdkOWU5MmViZTJkMDAxMzk2NTgxZTZmYjZkZDE3YjI5Mjk5ODRjOWIxZmQxY2Q3NzMwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yXQWu2Vq7hI3lQ1QqPIuOiQ1vDb4CiDBh88HvRIRyjc) [ ![数据库](https://private-user-images.githubusercontent.com/78434827/316314452-577eb7e9-1d7b-46b0-a3b5-590c4200107e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODk2OTksIm5iZiI6MTcxMTI4OTM5OSwicGF0aCI6Ii83ODQzNDgyNy8zMTYzMTQ0NTItNTc3ZWI3ZTktMWQ3Yi00NmIwLWEzYjUtNTkwYzQyMDAxMDdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE0MDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZmM2NGUzNzUzMjdkOWU5MmViZTJkMDAxMzk2NTgxZTZmYjZkZDE3YjI5Mjk5ODRjOWIxZmQxY2Q3NzMwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yXQWu2Vq7hI3lQ1QqPIuOiQ1vDb4CiDBh88HvRIRyjc) ](https://private-user-images.githubusercontent.com/78434827/316314452-577eb7e9-1d7b-46b0-a3b5-590c4200107e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODk2OTksIm5iZiI6MTcxMTI4OTM5OSwicGF0aCI6Ii83ODQzNDgyNy8zMTYzMTQ0NTItNTc3ZWI3ZTktMWQ3Yi00NmIwLWEzYjUtNTkwYzQyMDAxMDdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE0MDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZmM2NGUzNzUzMjdkOWU5MmViZTJkMDAxMzk2NTgxZTZmYjZkZDE3YjI5Mjk5ODRjOWIxZmQxY2Q3NzMwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yXQWu2Vq7hI3lQ1QqPIuOiQ1vDb4CiDBh88HvRIRyjc) [ ](https://private-user-images.githubusercontent.com/78434827/316314452-577eb7e9-1d7b-46b0-a3b5-590c4200107e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODk2OTksIm5iZiI6MTcxMTI4OTM5OSwicGF0aCI6Ii83ODQzNDgyNy8zMTYzMTQ0NTItNTc3ZWI3ZTktMWQ3Yi00NmIwLWEzYjUtNTkwYzQyMDAxMDdlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE0MDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZmM2NGUzNzUzMjdkOWU5MmViZTJkMDAxMzk2NTgxZTZmYjZkZDE3YjI5Mjk5ODRjOWIxZmQxY2Q3NzMwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yXQWu2Vq7hI3lQ1QqPIuOiQ1vDb4CiDBh88HvRIRyjc)

至少要5s以上吧。有个按钮1s就够了

**Comment by TCOTC** [comment]
> 有个按钮1s就够了

这个容错就太低了

**Comment by TCOTC** [comment]
在 https://github.com/siyuan-note/siyuan/issues/13375 中改进
