### ISSUE TITLE
Fill in the alt text after converting network images to local

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#10583]
云端图片下载到本地无法被块引用

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

原因应该是下载功能没有提示文本和标题，所以复制图片块引用后粘贴失败。

现在的块引用结果是这样的  ((20240312104724-6zap072 '​ ​')) 可以看到引号里面是空的所以没办法引用

希望不单单只是让以后的下载有标题和提示文本，因为我已经下载很多云端图片了只是现在才发现不能被引用，希望以后加个判断，如果没有标题和提示文本那就获取图片名

### Expected result

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
无
```

### Log file

无

**Comment by 88250** [comment]
请描述重现步骤。

**Comment by 88250** [comment]
感谢反馈，下个版本改进。
