### ISSUE TITLE
筛选关联列的数据库内新建行优化

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10585]
### In what scenarios do you need this feature?

如下图，数据库筛选了关联列且没有开启排序，然后新建新一行的时候会无法看到新建的行
![image](https://github.com/siyuan-note/siyuan/assets/63196026/7f717add-2163-4d8e-a1b4-88a1cd34fb60)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/90d2cc05-6cf9-450a-9198-51bec553efdd)

### Describe the optimal solution

建议能自动添加筛选项字段最接近的关联项目，notion是只会把筛选的文档关联进去，但是思源现在是字段筛选，可能需要识别与字段最接近的进行关联会更好。
![image](https://github.com/siyuan-note/siyuan/assets/63196026/800cba1d-d65d-454a-bb0d-f0f57bffd242)

### Describe the candidate solution

如果无法实现就直接附上最近行的关联项目也行，总之不要一添加新行看不见就行

**Comment by 88250** [comment]
关联、汇总和模板等渲染类型的字段不做筛选填充，否则逻辑会有问题，比如 Notion 的汇总也是没有填充的，和关联会不一致，所以我们统一不做填充处理。

**Comment by 5kyfkr** [comment]
> 关联、汇总和模板等渲染类型的字段不做筛选填充，否则逻辑会有问题，比如 Notion 的汇总也是没有填充的，和关联会不一致，所以我们统一不做填充处理。

了解，现在这样就是直接新建文档会麻烦点，新建了要去没有筛选的视图改属性，然后再切回来，增加了两步，或者就单独弄个没有筛选的镜像数据库的视图放上面，总之还是增加了点步骤，但问题不大
