### ISSUE TITLE
Disable updating table in read-only mode

### ISSUE THREAD

**Issue by hscui** [siyuan-note/siyuan#10586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

只读模式下可在表格中插入行或列，而且此时无法使用Ctrl+Z撤销上述操作。

### Expected result

修复问题

### Version environment

```markdown
- Version: 3.03
- Operating System: WIN10
- Browser (if used):Firefox 123.0.1
```

### Log file

无法上传

**Comment by Vanessa219** [comment]
可以演示一下怎么操作的？界面上没有对应的按钮。

**Comment by hscui** [comment]
![只读模式下表格修改](https://github.com/siyuan-note/siyuan/assets/7949195/7c40d9a4-58a9-4213-8682-ede687483929)

**Comment by Vanessa219** [comment]
哦，明白了，多谢。
