### ISSUE TITLE
`Add to Database` no longer autofills filter values

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10587]
希望改进下"添加到数据库”功能中添加到视图的逻辑

### In what scenarios do you need this feature?

1、新建数据库A
2、建立两个视图：a、b，并切换为a视图
3、新建数据库A的镜像数据库B，并切换为b视图
4、对块使用“添加到数据库”功能，发现块加入了b视图中

发现块添加到哪个视图只和数据库B有关系，无论数据库A怎么切换视图，都不会影响块的添加逻辑

最后一个镜像是什么视图，块就加到哪个视图

这个逻辑不太合理，希望大佬优化下

### Describe the optimal solution

无

**Comment by Jiangshuon** [comment]
希望给数据库列表增加二级菜单，菜单里面展示该数据库的视图，这样才能添加到指定视图。

**Comment by 88250** [comment]
镜像数据库块的数据源是同一个，所以任何一个镜像块添加数据都会影响其他镜像。

**Comment by 88250** [comment]
要不使用 添加到数据库 的时候就不填充筛选值了？否则还要再选一层用起来比较麻烦吧。

**Comment by Jiangshuon** [comment]
好的大佬

**Comment by Jiangshuon** [comment]
大佬，用了一天，不带筛选值太痛苦了，我很多视图都是4、5个筛选条件，添加起来好累呀

希望还是加一个视图的二级菜单，如果还能记住上次添加的是哪一个视图就更好了，把该视图排在前面

至于操作麻烦，如果点击enter就直接添加到第一个视图，点击方向键才会进入二级菜单，如果能实现的话，这样也不麻烦吧

![image](https://github.com/siyuan-note/siyuan/assets/67137548/5bbf7b38-9468-444d-80ef-e0cccfb5d377)

**Comment by 88250** [comment]
唉，暂时还是不动了，等考虑一下，先缓缓，见谅。



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 20, 2024 00:27 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] `Add to Database` no longer autofills filtervalues (Issue #10587)




 
大佬，用了一天，不带筛选值太痛苦了，我很多视图都是4、5个筛选条件，添加起来好累呀
 
希望还是加一个视图的二级菜单，如果还能记住上次添加的是哪一个视图就更好了，把该视图排在前面
 
至于操作麻烦，如果点击enter就直接添加到第一个视图，点击方向键才会进入二级菜单，如果能实现的话，这样也不麻烦吧
 
image.png (view on web)

**Comment by Jiangshuon** [comment]
好的D大，居然还没睡，早点休息~

**Comment by 88250** [comment]
刚躺下，你也早点睡，晚安。



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 20, 2024 01:00 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] `Add to Database` no longer autofills filtervalues (Issue #10587)




 
好的D大，居然还没睡，早点休息~

**Comment by 88250** [comment]
后续关联 https://github.com/siyuan-note/siyuan/issues/10659

**Comment by 88250** [comment]
v3.3.0 后还是回归填充筛选值 https://github.com/siyuan-note/siyuan/issues/11966
