### ISSUE TITLE
Return document blocks when search hits different block content

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#10584]
目前搜索文档块（往往）不能通过搜索正文内容搜索到，所以希望支持「搜索命中不同块内容时返回文档块」

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

设想这样一个场景：
我在思源里写了一篇文章：

```
# 思源真好用

它支持富文本编辑。


它支持块引用。


它支持标签。

……

```

渐渐地，我在思源里写了很多很多笔记。然后，我想找这篇文章，于是要搜索，要多加关键词。
于是我搜索“富文本 标签”，**发现竟然搜不到！**
这就很尴尬。

再比如，根据用户指南，「整个文档是一个块」：
<img width="325" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/dd4e986f-4588-4284-9113-fec013263d2a">

标签用于对块进行标记：
<img width="652" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/bdb136c2-59b7-4737-a8ec-a8fcc4626080">

我对文档块设置#think#标签，然后搜索#think# 和文档块正文中的内容，搜不出该文档块。
<img width="1054" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/9522bf6c-15cd-43a6-8e05-3e23779fe00c">

### 希望能实现的效果

最直接的想法是，希望在搜索时，如果搜索关键词位于文档块里的好几个块，那么这个文档块就应该出现在搜索结果中。

真正实现起来的话，为了搜索结果尽量不要重复，可能得实现得麻烦一些，也就是说，如果搜索结果中还包含这个文档块中的任意结果，那就不要在搜索结果中出现这个文档块。
换句话说，如果搜索结果中不包含这个文档块中的任何块了，但是整个文档块还包含搜索关键词，那么此时再在搜索结果中出现这个文档块。

**Comment by LoneFireBlossom** [comment]
<img width="512" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/e75551f2-9207-4a14-9417-881feb6f6620">
搜索类型我都开了。


不过我又试了试，我这个issue涵盖面很广啊……
思源是不允许搜索文档块里的内容吗？这样也搜不出来。那文档块怎么能称之为“整个文档是一个块”呢？
<img width="1049" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/9a119352-cf2c-4d93-b820-6e21963b7e50">

**Comment by 88250** [comment]
标签测试正常：

![image](https://github.com/siyuan-note/siyuan/assets/873584/88f0eb0c-a2bd-4ded-ad81-5533887ec570)

后面一个是不支持搜索内容的，社区里搜索一下，有个比较复杂的 SQL 可以支持。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by LoneFireBlossom** [comment]
> 标签测试正常：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/311946056-88f0eb0c-a2bd-4ded-ad81-5533887ec570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjAwMDYsIm5iZiI6MTcxMDIxOTcwNiwicGF0aCI6Ii84NzM1ODQvMzExOTQ2MDU2LTg4ZjBlYjBjLWEyYmQtNGRlZC1hZDgxLTU1MzM4ODdlYzU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwNTAxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmY0ZTllNDgwZjIyZjA4MWMzOTI2YTc3MTQ3NjRmZTBkNThhMjQ4ZTk2OTFhZWRkZTY0MzlkYmNjNDkzZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JKPcYZIBQRsGA1TI6s2xxTIf4a2mnQXvAhKJDqmThD4)
> 
> 后面一个是不支持搜索内容的，社区里搜索一下，有个比较复杂的 SQL 可以支持。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

是标签+内容搜不出来啊

**Comment by LoneFireBlossom** [comment]
> 标签测试正常：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/311946056-88f0eb0c-a2bd-4ded-ad81-5533887ec570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjAwMDYsIm5iZiI6MTcxMDIxOTcwNiwicGF0aCI6Ii84NzM1ODQvMzExOTQ2MDU2LTg4ZjBlYjBjLWEyYmQtNGRlZC1hZDgxLTU1MzM4ODdlYzU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwNTAxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmY0ZTllNDgwZjIyZjA4MWMzOTI2YTc3MTQ3NjRmZTBkNThhMjQ4ZTk2OTFhZWRkZTY0MzlkYmNjNDkzZjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JKPcYZIBQRsGA1TI6s2xxTIf4a2mnQXvAhKJDqmThD4)
> 
> 后面一个是不支持搜索内容的，社区里搜索一下，有个比较复杂的 SQL 可以支持。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

整个文档是一个块，结果搜索这个块里的词语搜不出这个块，这根本就不合理，不是SQL支持就完事儿了啊……

**Comment by LoneFireBlossom** [comment]
这个问题核心是文档块在有些地方是包含正文的在有些地方不包含，得解决啊

**Comment by 88250** [comment]
不解决了，设计如此。

**Comment by LoneFireBlossom** [comment]
我依旧不理解。
我想写一篇普通的文档，事后想要用关键词搜索这个文档，岂不是会陷入“越加关键词越搜不出来，减少关键词的话又看到一大堆无关内容，在搜索结果的海洋里找不到东西”的困境。

比如这个文档。
<img width="362" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/b421df00-57cc-4e9f-97ec-7f5a70acd762">
我搜两个关键词就搜不出来，这是不是有点过分了。
<img width="922" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/108ecdde-e496-4ae1-b8b0-6a4c1da27188">

在我的理解中，文档搜索是基础中的基础……

**Comment by LoneFireBlossom** [comment]
所以……开发者认为用户不应该进行文档内的关键词搜索？

**Comment by 88250** [comment]
搜索毋庸置疑很重要，但是现在确实不好解决，只能考虑用 SQL 顶顶了。你如果有技术方案可以提出我们讨论看看，谢谢。

**Comment by LoneFireBlossom** [comment]
哦，原来是技术问题啊，我还以为是设计理念不一样…
那没事了。

**Comment by LoneFireBlossom** [comment]
还有一个问题啊，对于这种未来肯定要解决，现在是因为遇到了困难，或者优先疾病不是那么高，所以搁置的问题，真的关闭这个issue就好了吗？我觉得是不是用一个其他的方法更好。比如说虽然关掉了这个issue，但是打上一个future plan之类的标签。

**Comment by LoneFireBlossom** [comment]
如果只是关闭了这个帖子，而没有做一些备注或者统计的话，以后可能会忘掉其中的一部分提议。我开发者可能会忘掉，用户可能也会忘掉，或者流失了，不再提这个建议了。

**Comment by 88250** [comment]
好的，我们保持打开，后面看看有没有方案可以实现，也欢迎大家帮忙，谢谢。

**Comment by LoneFireBlossom** [comment]
我目的不是说仅仅把这一个issue打开，而是需要标注所有「值得后续优化的问题」issue。但如果这种issue都保持打开状态的话恐怕不符合开发者的习惯吧，我看思源的issue区，open状态的很少，和某些攒了上千个open issue的项目很不一样。
所以可以考虑加标签这种方式，等大工程都搞得差不多了再从关闭的带相关标签的issue里随机抽一些拿出来研究怎么改进

**Comment by 88250** [comment]
保持打开收集反馈看看，如果需要的人多的话再考虑下一步措施，谢谢。

**Comment by LoneFireBlossom** [comment]
好的，但是你说的和我说的不是同一个事情啊…😂在 2024年4月5日，18:27，D ***@***.***> 写道：﻿
保持打开收集反馈看看，如果需要的人多的话再考虑下一步措施，谢谢。

**Comment by 88250** [comment]
保持打开可能更容易被其他人看到，如果需求较多，再提高优先级。

**Comment by TCOTC** [comment]
我感觉这个应该是大家都有需求的，搜索文档时一般只会对几个关键词有印象，而这些关键词是分布在文档中不同的块内的。

平常最苦恼的就是明明记得文档里有什么关键词，搜一个词出来一大堆搜索结果，搜两个词又搜索不出来东西了。

**Comment by vodecs001** [comment]
+1

**Comment by LoneFireBlossom** [comment]
开发者说这个需求的实现有技术上的困难，我理解。
现在实现不了，但未来总归要实现。搜索功能对笔记软件来说极其重要，我觉得算是“一个笔记软件应该满足的条件”中的T1级别。

比如，设想一个场景，我给别人推荐思源笔记，别人问我，这个思源笔记搜索做的怎么样？我告诉他，搜索功能很好，只是搜文档很有可能搜不出来。如果你要想搜文档搜出来，就得用大纲写。
我觉得听到这话的人，都会觉得很奇葩，其中有相当一部分人就不会选择思源了。
至于我用思源、用文档而非大纲的形式写东西，是怀着“未来思源一定会、一定能解决文档搜索”的信心用下去的。

因为我不懂技术所以下面只是我的胡思乱想：
既然现在实现不了、未来一定要实现这个功能，那么我觉得最好在这条路上尽量避免“会对未来实现这个功能造成困难”的软件设计。

**Comment by Jiangshuon** [comment]
你们不知道《简单搜索》插件吗？很早就解决这个问题了，我用了很久了。D大可以参考下

![image](https://github.com/siyuan-note/siyuan/assets/67137548/b53b7fc0-1b37-4bef-a57c-4afb3153d58d)

**Comment by haolly** [comment]
既然插件能实现，那么为啥不把插件功能整合进思源里面去呢？

**Comment by 88250** [comment]
欢迎提 PR 谢谢

**Comment by TCOTC** [comment]
相关需求：

- https://github.com/siyuan-note/siyuan/issues/12716

**Comment by Achuan-2** [comment]
期待这个功能改进，目前思源搜文档确实不方便，我只能在标题尽量添加足够的信息

**Comment by 88250** [comment]
目前基本实现了，稍后发布 dev 版。但是目前有两个问题：

* 性能不好：需要分组合并所有块的内容，然后再匹配
* 按类型排序问题：文档会被放到最全面，精确匹配的块在后面

**Comment by TCOTC** [comment]
在“更多”里面给个开关吧

**Comment by 88250** [comment]
v3.1.11-dev1 已经发布，欢迎大家测试。

**Comment by TCOTC** [comment]
可以用 文档名关键词 和 内容块关键词 组合搜索吗？

**Comment by 88250** [comment]
> 可以用 文档名关键词 和 内容块关键词 组合搜索吗？

可以的。

**Comment by Achuan-2** [comment]
试用了下，感觉不是要解决排序的问题，而是应该要解决重复的问题，命中关键词的这个块的文档和这个块会重复出现，也就是原来列表的一炮三响，现在文档树也有了（一炮二响）
![PixPin_2024-10-24_21-34-00](https://github.com/user-attachments/assets/9335c8c9-503b-45c1-b903-b0f678acb322)
按照文档分组这个问题更明显
![PixPin_2024-10-24_21-36-49](https://github.com/user-attachments/assets/0ac440a6-5af1-455d-a39f-bf413dbef089)

文档树分组的情况下，建议文档块的标题没有命中关键词，就不显示这个文档块

搜索类型这里，关于文档块的描述需要更新，现在这个只能关闭搜索文档标题，不能关闭搜索文档块的子块而返回文档块
![PixPin_2024-10-24_21-46-33](https://github.com/user-attachments/assets/12bc1bdc-ad7c-4ffd-ad74-05115ca5e5de)

对于类型排序，初步建议是，可以的话，添加一个按钮或搜索类型，仅搜索文档块标题，而不是只能搜索包含子块。

**Comment by Achuan-2** [comment]
> 问题2解决了问题1还存在

+1，我也有新建文档，不显示的问题，以前版本不会

**Comment by TCOTC** [comment]
我这里也是，新建的子文档有时候不会显示出来，需要折叠上级再展开

**Comment by Jiangshuon** [comment]
采用这种算法是不是更简单——如果单块搜索结果为空，才调用跨块搜索代码去搜索文档，不为空则不调用

这样是不是可以同时解决效率和显示问题

**Comment by SaXz2** [comment]
提一个新的搜索改进建议，有助于更直观的查看
- 按文档分组应该只显示文档名称
- 路径信息应该跟不分组统一，都保持在右下角
- 搜索结果应该支持多行显示

以下是对比图，可以看出路径长的眼花缭乱
![cef9d4a659338bbffb013937d80890eb](https://github.com/user-attachments/assets/42d03460-2676-4a93-b04c-86f57ce8173a)

**Comment by 88250** [comment]
@SaXz2 麻烦单独开 issue 讨论

**Comment by 88250** [comment]
综合考虑了下，新增一种搜索方式 `全文关键字`，在这种搜索方式下**仅返回文档块**（也就是跨块搜索关键字结果返回文档），这样考虑原因如下：

* 不影响已有的搜索方式，无论是功能还是性能
* 已有的搜索方式（比如关键字）已经能够解决大部分问题了，全文关键字仅作为一种搜索兜底方式

大家觉得呢？

**Comment by TCOTC** [comment]
我认为样式可以像按文档分组这样，返回文档以及匹配到关键词的块：

![image](https://github.com/user-attachments/assets/8e6174e7-ff28-42a5-a4f5-625b12a07fb9)

**Comment by SaXz2** [comment]
![Clip_2024-10-25_22-22-42](https://github.com/user-attachments/assets/fe9078f5-245e-4a6b-beb0-ac832ce05d4f)
可以参考上图插件 「基于文档搜索」

**Comment by 88250** [comment]
要不咱不改了，用插件吧 😂

**Comment by TCOTC** [comment]
别，我不想装插件

p.s.我已经在尽量去插件化了

**Comment by 88250** [comment]
v3.1.11-dev2 已经打包完毕，各位帮忙测试一下。

目前这几个块式编辑应用 Notion/Wolai/FlowUs 都没有支持跨块搜索，我觉得我们暂时也可以不动，因为社区插件已经解决了这个问题，如果要在原生中支持，新添加搜索方式比较合理，但是也会带来其他问题（比如无法支持搜索替换）。

这个改动目前我还是持保守意见，先不要做改动了。

**Comment by TCOTC** [comment]
搜索方式 `全文关键字` 的情况下屏蔽替换

**Comment by 88250** [comment]
目前参考 [基于文档搜索](https://github.com/Misuzu2027/syplugin-document-search) 代码实现了一下，性能问题已经解决。

稍后发布 dev3 大家版本测试看看。

**Comment by TCOTC** [comment]
今天用了一下，文档全排在前面确实比较难用。

如果不新增搜索方式或者开关的话我感觉这样排序搜索结果会合理一点：

1. 标题匹配到关键词的文档块
2. 其他匹配到关键词的块
3. 文档内容匹配到关键词的文档块

不过我觉得新增一个搜索方式，像 `按文档分组` 那样返回文档以及匹配到关键词的块会更合适。能看到文档匹配到关键词的是哪些块，比只看到一个文档标题更好判断。

**Comment by 88250** [comment]
排序方式已经改了，等发布 dev 再试试，我觉得现在已经比较好用了。

**Comment by TCOTC** [comment]
@88250 目前是只有多于 1 个关键词的情况下才会搜索并返回包含对应关键词的文档吗？

只有一个搜索关键词的情况下不影响原有的搜索性能，感觉合理很多

**Comment by 88250** [comment]
一个关键字也是新的实现逻辑，性能和之前没有差太多。

**Comment by 88250** [comment]
考虑了下，单关键字的情况下还是走 FTS 搜索。

**Comment by TCOTC** [comment]
1. 我觉得显示匹配到的块数会方便一点
2. 匹配到块数多的文档应该排在前面

![image](https://github.com/user-attachments/assets/d699b434-2ad1-4dc1-b76d-2f695c15dc27)

**Comment by 88250** [comment]
我没法实现匹配到的块统计和排序，有人有方案的话可以帮忙 PR。

**Comment by cordinGH** [comment]
> 我没法实现匹配到的块统计和排序，有人有方案的话可以帮忙 PR。

关于块统计，或许可以参考一下插件 「基于文档搜索」，该插件基本实现了这个功能

**Comment by Wetoria** [comment]
如果我希望“测试”能搜到“测什么测，试试这个”这句话， @88250 你会不会打我。

**Comment by 88250** [comment]
> 如果我希望“测试”能搜到“测什么测，试试这个”这句话

v3.8.0 实现 https://github.com/siyuan-note/siyuan/issues/17788

效果：

<img width="627" height="754" alt="Image" src="https://github.com/user-attachments/assets/ad90fbfa-2ee8-4001-b599-cda63a78377b" />
