### ISSUE TITLE
移动端在阅读文章内某一部分内容时，能够将该部分标题固定于最上方

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10582]
### In what scenarios do you need this feature?

移动端的阅读相较于 PC 端有非常大的缺陷，例如不能够方便的看大纲，需要经常在文档和大纲中切换

那么这就会出现这样一个问题，有时候你阅读想看你这部分的标题是什么，你得往上滑。看标题，看完标题后，你再往下滑，找到之前阅读的地方非常的麻烦且繁琐

### Describe the optimal solution

希望能够在阅读有标题内容的时候，在标题划出页面时，能够将标题字体缩小且固定在内容的最上方

这样的作用在于能够明确的知道自己目前阅读的这部分内容，在文章中处于什么标题下面

**Comment by QQQOrange** [comment]
当然，也可以在文章中提供一个悬浮按钮，点击后能够迅速呈现出本文的大纲

**Comment by Vanessa219** [comment]
右滑动可以选择大纲，后续打开也是大纲的展示界面。

标题过多都堆叠在上方可能堆不下。

**Comment by QQQOrange** [comment]
> 右滑动可以选择大纲，后续打开也是大纲的展示界面。
> 
> 标题过多都堆叠在上方可能堆不下。

只显示当前的一个标题可以吗，或者有一个悬浮的按钮点击一下出现大纲

右滑的那个，可能不同手机的原因，我右滑的话就退出当前页面了

而且因为唤起的按钮在左上方单手操作的时候也不方便

而且文档树和大纲也都集成在右滑的上面，不能够共存

**Comment by Vanessa219** [comment]
只需要标题的话可以点击左上角的面包屑查看
滑动的时候不要从边缘开始滑动。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by QQQOrange** [comment]
> 大概懂了，短期内应该是没有这么大的重构计划了，等后期再考虑，谢谢。

妥妥的，先存着嘛，未来有可能就行
