### ISSUE TITLE
Enhance Table Database Search Speed to Match Real-Time Performance

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

SiYuan's table database search has a minor but noticeable delay compared to Notion's real time search results.

### Expected result

Optimize search to update results instantly as queries are typed, matching Notion's real-time performance, to enhance user satisfaction and competitiveness.

### Screenshot or screen recording presentation

Notion Search Speed Test:

https://github.com/siyuan-note/siyuan/assets/36538038/7d17afef-ea30-4a53-8931-83be9c1069ac

SiYuan Search Speed Test:

https://github.com/siyuan-note/siyuan/assets/36538038/2336d226-37d9-4f7d-aa64-748f15baa7d2

### Version environment

```markdown
- Version: 3.0.3
- Operating System: Windows 11 Pro
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14580210/siyuan.log)

**Comment by 88250** [comment]
This is already the fastest speed we can achieve currently. We will try our best to optimize it if it can be optimized in the future. Thank you for your feedback.
