### ISSUE TITLE
移动端闪卡手势功能

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10590]
### In what scenarios do you need this feature?

这个功能之前也提过，主要就在于提升刷卡的体验。

现在的手机屏幕越来越大，有时候想触碰到另一边的按钮，比较困难，

### Describe the optimal solution

如果有个手势的话，那就能够通过左滑、右滑之类的功能，快速的实现就方便很多

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10439

请不要重复提议，如果后续能做的话我们会考虑重开的。
