### ISSUE TITLE
Feature Request: Add Custom Ratings Feature to Database Tables

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10591]
Feature Request: Add Custom Ratings Feature to Database Tables

### In what scenarios do you need this feature?

When managing books, projects, or tracking progress within database tables, a visual and customizable rating system (e.g., stars) would be great to have like in this picture below.

![Arc_GbhVpYhe5w](https://github.com/siyuan-note/siyuan/assets/36538038/6ef03bec-ed0f-4742-94b7-ca9b4db228cc)

This is currently what we have now in SiYuan.

![Screenshot 2024-03-12 194256](https://github.com/siyuan-note/siyuan/assets/36538038/239a275c-191a-4d35-9dc6-16d73671dbbc)

### Describe the optimal solution

Implement a feature allowing users to insert customizable rating icons (stars, dots etc.) directly into database table cells, with the ability to define the scale (e.g., 1-5, 1-10) and choose custom icons or images for ratings.

**Comment by 88250** [comment]
Hello, please use single select instead, passing Emoji as an option, something like:

![image](https://github.com/siyuan-note/siyuan/assets/873584/d7ed648b-5cf3-4821-9bb3-95ac44072f77)

The independent Rating column is not considered to be added for now, thanks for the suggestion.

**Comment by MrIntellectX** [comment]
Yes, that would also work, but in the future, please consider adding this option. Thanks.
