### ISSUE TITLE
支持 asciinema 嵌入播放

### ISSUE THREAD

**Issue by heshang233** [siyuan-note/siyuan#106]
现阶段asciinema支持markdown的嵌入，但不支持原页面播放，仅能点击跳转。

作为开发或运营，asciinema如果能支持嵌入的话，那就非常方便了，根据[官网信息](https://asciinema.org/docs/embedding)其支持：
`
asciinema supports oEmbed, Open Graph and Twitter Card APIs. When you share an asciicast on Twitter, Slack, Facebook, Google+ or any other site which supports one of these APIs, the asciicast is presented in a rich form (usually with a title, author, description and a thumbnail image), linking to your recording on asciinema.org.
`
官网地址如下：https://asciinema.org/

**如果很复杂的话，建议就不支持了，毕竟并不是一个很重要的功能。**

**Comment by 88250** [comment]
感谢反馈，计划在 v0.2.4 中进行支持。

**Comment by Vanessa219** [comment]
如下使用后 `[asciinema](https://asciinema.org/a/234965)` 在预览中可见

**Comment by Vanessa219** [comment]
499453dd4506aa81cc7d197bcad9f54911bbc8b2
