### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by Laimic** [siyuan-note/siyuan#10600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

WebDAV 获取云端同步目录的时候显示 " 网络异常，请稍后再试 (Provider: WebDAV)"
![image](https://github.com/siyuan-note/siyuan/assets/6868488/24014b7e-fde9-4a68-aacb-bb1b46c620f3)

WebDAV 链接能够保证没有问题,因为可以正确链接,并且其他笔记软件能够正常同步

### Expected result

能够成功获取 WebDAV 并能成功同步

### Version environment

```markdown
- Version: 3.0.3
- Operating System: Windows 11
- Browser (if used):
```

### Log file

E 2024/03/13 22:16:47 sync_lock.go:159: upload lock sync failed: ReadDir siyuan/siyuan/repo: Propfind "http://***************/siyuan/repo": EOF
E 2024/03/13 22:16:47 repository.go:1280: sync data repo failed: lock cloud repo failed
I 2024/03/13 22:16:47 conf.go:547: exiting kernel [force=false, execInstallPkg=0]
I 2024/03/13 22:16:47 sync.go:192: sync before exit
I 2024/03/13 22:16:47 repository.go:1258: syncing data repo [device=236885ee-06b6-4182-99a5-c125f5a2b1b5, kernel=5pkr9m2, provider=3, mode=a/false]
I 2024/03/13 22:16:47 ref.go:50: got local latest [device=236885ee-06b6-4182-99a5-c125f5a2b1b5/windows, id=355f551906f4de8769db08d295e59bfd2a2e4d85, files=30, size=1.2 MB, created=2024-03-13 21:22:35]
I 2024/03/13 22:16:47 repo.go:595: walk data [files=30] cost [25.3933ms]
I 2024/03/13 22:16:47 ref.go:50: got local latest [device=236885ee-06b6-4182-99a5-c125f5a2b1b5/windows, id=355f551906f4de8769db08d295e59bfd2a2e4d85, files=30, size=1.2 MB, created=2024-03-13 21:22:35]
E 2024/03/13 22:16:51 sync_lock.go:159: upload lock sync failed: ReadDir siyuan/siyuan/repo: Propfind "http://***************/siyuan/repo": EOF
E 2024/03/13 22:16:51 repository.go:1280: sync data repo failed: lock cloud repo failed
I 2024/03/13 22:16:51 conf.go:547: exiting kernel [force=false, execInstallPkg=0]
I 2024/03/13 22:16:51 sync.go:192: sync before exit
I 2024/03/13 22:16:51 repository.go:1258: syncing data repo [device=236885ee-06b6-4182-99a5-c125f5a2b1b5, kernel=5pkr9m2, provider=3, mode=a/false]
I 2024/03/13 22:16:51 ref.go:50: got local latest [device=236885ee-06b6-4182-99a5-c125f5a2b1b5/windows, id=355f551906f4de8769db08d295e59bfd2a2e4d85, files=30, size=1.2 MB, created=2024-03-13 21:22:35]
I 2024/03/13 22:16:51 repo.go:595: walk data [files=30] cost [21.1822ms]
I 2024/03/13 22:16:51 ref.go:50: got local latest [device=236885ee-06b6-4182-99a5-c125f5a2b1b5/windows, id=355f551906f4de8769db08d295e59bfd2a2e4d85, files=30, size=1.2 MB, created=2024-03-13 21:22:35]
E 2024/03/13 22:16:55 sync_lock.go:159: upload lock sync failed: ReadDir siyuan/siyuan/repo: Propfind "http://***************/siyuan/repo": EOF
E 2024/03/13 22:16:55 repository.go:1280: sync data repo failed: lock cloud repo failed
I 2024/03/13 22:16:55 conf.go:547: exiting kernel [force=false, execInstallPkg=0]
E 2024/03/13 22:16:55 sync.go:269: failed to auto-sync too many times, delay auto-sync 64 minutes
I 2024/03/13 22:16:55 conf.go:547: exiting kernel [force=false, execInstallPkg=0]
E 2024/03/13 22:16:55 sync.go:269: failed to auto-sync too many times, delay auto-sync 64 minutes

**Comment by 88250** [comment]
```
E 2024/03/13 22:16:47 sync_lock.go:159: upload lock sync failed: ReadDir siyuan/siyuan/repo: Propfind "http:///siyuan/repo": EOF
E 2024/03/13 22:16:47 repository.go:1280: sync data repo failed: lock cloud repo failed
```

可能是目录权限或者路径配置错了（不确定是不是多配置了一层 `siyuan/siyuan/repo`），建议检查一下，我关闭 issue 了，谢谢。
