### ISSUE TITLE
Support plugin.docks configuration hotkeys

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#10603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

官方插件demo的addDock的快捷键没有在设置里
![Clip_2024-03-14_10-11-03](https://github.com/siyuan-note/siyuan/assets/48077521/ed8395d4-c7c8-4ea7-99ab-293386d708ee)

### Expected result

能出现在设置里,以便进行修改或禁用

### Version environment

```markdown
- Version: v3.0.2
- Operating System:  win10
- Browser (if used):
```

### Log file

1

**Comment by Vanessa219** [comment]
指的是这个么？
<img width="1089" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/3f2af0b9-395f-4b7e-9b09-3df0aeb0f706">

**Comment by iamqiz** [comment]
@Vanessa219 对

**Comment by Vanessa219** [comment]
篮框里面显示的就是官方插件的快捷键。没太明白没有出现指的是？

**Comment by iamqiz** [comment]
@Vanessa219 addDock的快捷键没有在设置里 😂
![Clip_2024-03-17_12-19-26](https://github.com/siyuan-note/siyuan/assets/48077521/893786b2-975c-478a-8797-75d9bc4a42e0)
