### ISSUE TITLE
移动端增加后退按钮

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#10602]
### In what scenarios do you need this feature?

移动端跳转后回到上次阅读只能靠页面定位导航，可否增加后退按钮方便快速返回。

### Describe the optimal solution

增加后退按钮

**Comment by 88250** [comment]
Android 端贴边往中间滑动。

**Comment by aGolduck** [comment]
iOS能否提供类似功能

**Comment by Vanessa219** [comment]
iOS 没有贴边滑动的特性，上面的笔记软件也都没有配置滑动功能。可以使用右侧菜单中的最近文档。
