### ISSUE TITLE
Cannot read properties of undefined (reading 'menu')

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#10606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

有个问题，老是看到这个报错。

https://github.com/siyuan-note/siyuan/blob/3ec2ff243f746e30224753f914c82996e03dbee2/app/src/block/popover.ts#L181
```
Uncaught TypeError: Cannot read properties of undefined (reading 'menu')
    at Jb (main.1c3dfd32b3694caf341e.js:4620:2825)
    at main.1c3dfd32b3694caf341e.js:4620:1258
Jb @ main.1c3dfd32b3694caf341e.js:4620
(anonymous) @ main.1c3dfd32b3694caf341e.js:4620
setTimeout (async)
(anonymous) @ main.1c3dfd32b3694caf341e.js:4620
```
![image](https://github.com/siyuan-note/siyuan/assets/3294007/382f7b93-035b-46b0-9829-068dd17d71b8)

 

### Version environment

```markdown
- Version: 
- Operating System: windows 10
- Browser (if used):
```

**Comment by Vanessa219** [comment]
怎么弄出来的？

**Comment by IAliceBobI** [comment]
没说个你听之前一直有，说了之后，到现在都没了。下次再打开。
