### ISSUE TITLE
打字打到最底部一行的时候，会被最下面的状态栏遮住文字

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

打字打到最底部一行的时候，会被最下面的状态栏遮住文字
![image](https://github.com/siyuan-note/siyuan/assets/62794181/e350117b-63ee-4855-a046-fe16cb959b8e)
希望在打字打到这个位置的时候，页面能够往上滑一点，至少不会让状态栏把文字遮住

### Expected result

希望在打字打到这个位置的时候，页面能够往上滑一点，至少不会让状态栏把文字遮住

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/62794181/fa3be7e4-80ea-43b6-b3e2-3ded327cb88b)

### Version environment

```markdown
- Version: 3.03
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by royc01** [comment]
主题特性，暂时只能这样

**Comment by QQQOrange** [comment]
> 主题特性，暂时只能这样

哦哦哦
