### ISSUE TITLE
Enhance Graph View for Improved User Experience

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10611]
### In what scenarios do you need this feature?

- When zooming in and out of the graph view, the current experience is not as smooth as expected.
- Clicking on switches to enable tags view, sliders results in a loading progress bar, causing a delay in the display of information.

### Describe the optimal solution

I propose the following enhancements to the graph view feature in SiYuan to improve overall user experience and functionality:

- Improve animations and smoothness during zoom in and out operations. The goal is to achieve a seamless and fluid experience similar to Obsidian's graph view.
- Optimize the loading process for menu options. Ideally, clicking on switches or sliders should instantly display the requested information without any loading progress bar.
- Ultimately, strive to make SiYuan's graph view better than Obsidian's in terms of UI, node hover effects, animations, and overall performance.

Obsidian Graph View:

https://github.com/siyuan-note/siyuan/assets/36538038/99e14cf3-d3dc-4c1c-a4a7-a6b6f7becaa8

SiYuan Graph View:

https://github.com/siyuan-note/siyuan/assets/36538038/b9604033-16ae-4d55-a4a3-15ad060f5403

### Other information

These enhancements are crucial for users who primarily rely on the graph view for their daily workflows. I understand that these improvements may require time and resources, but I believe they will significantly benefit the user experience. Thank you for considering this request.

**Comment by 88250** [comment]
Hello, we have reached a consensus with the community before that the automatically generated relationship graph is not very useful, so we will no longer improve the relationship graph in the future. Thank you for your understanding.
