### ISSUE TITLE
Support export and import settings

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10617]
支持导出和导入配置项

### In what scenarios do you need this feature?

新建工作空间想对齐配置很麻烦，尤其是快捷键的配置

关联 #10410 、[请问思源笔记能否同步“设置”呢？ - 链滴](https://ld246.com/article/1710303034640)

### Describe the optimal solution

- 像 S3/WebDAV 那样，能够导出和导入 [可以跨平台的](https://github.com/siyuan-note/siyuan/issues/10410#issuecomment-1961357804) 客户端配置项
- 不包含登录的账户信息、不包含云端配置，以便将配置分享给他人
- 另外，跟 S3/WebDAV 不同，这些不是隐私信息，所以最好也能支持「上传」配置到云端，然后能在其他客户端中「下载并使用」配置（差不多像 云端快照/布局 那样，支持给不同的配置 命名、切换、更新）

**Comment by TCOTC** [comment]
关联按需同步配置：#10831

**Comment by 88250** [comment]
稍后调整，谢谢。
