### ISSUE TITLE
Unreadable titles in tabs

### ISSUE THREAD

**Issue by utilisateuralpha** [siyuan-note/siyuan#10612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Hello
On the Siyuan application interface, the tab titles are sometimes illegible.
Take a look at the picture attached
I'm using Ubuntu 22.04 

I think you need to add an option in the application to disable 'GPU rasterization'. The deactivation could solve this problem

### Expected result

tab titles must be readable

### Screenshot or screen recording presentation

![siyuanonglets](https://github.com/siyuan-note/siyuan/assets/89381501/d7fe8ab6-1fdb-47ec-a05e-8471d5be335d)
![ongletsiyuanbis](https://github.com/siyuan-note/siyuan/assets/89381501/775e713b-da30-48da-8ab2-a62faf260738)

### Version environment

```markdown
- Version: 3.0
- Operating System: Ubuntu 22.04
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14608757/siyuan.log)

**Comment by 88250** [comment]
Hello, please try to start SiYuan with the command line argument `--disable-gpu`.
