### ISSUE TITLE
Add internal kernel API `/api/file/globalCopyFiles`

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#10614]
插件无法使用 putFile API 通过文件路径上传文件

### In what scenarios do you need this feature?

在插件中需要上传一些资源文件，目前的方法是用fs.copyFile，但是D大表示这样的操作可能会导致数据分块损坏。在研究了一下putFile这个API之后，发现js无法直接根据文件路径形成form-data中的文件。

### Describe the optimal solution

希望能够只提供文件的绝对路径（工作空间外），然后后端进行上传操作

**Comment by 88250** [comment]
`/api/file/globalCopyFiles`

参数：

```json
{
    "srcs": ["C:\\Users\\User1\\Desktop\\444.log", "C:\\Users\\User1\\Desktop\\123.pdf", "C:\\Users\\User1\\Desktop\\siyuan\\"],
    "destDir": "/data/assets/"
}
```

* srcs：源文件绝对路径，支持文件夹
* destDir：相对于工作空间的路径

返回：

```json
{
    "code": 0,
    "msg": "",
    "data": null
}
```

报错的话 code 不为 0。
