### ISSUE TITLE
Android APP

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1061]
## 背景

手机的性能比起云服务器来好太多了，最重要的是手机是随身携带的，它完全可以成为每个人都能随身携带的服务器。

## 方案

将内核程序和界面资源编译打包为 Android 应用，在手机上能够拉起内核服务，最终通过浏览器使用。

将手机作为主要服务器以后，理论上已经不需要进行数据同步，因为数据是集中存放在手机上的，无论是在手机上通过浏览器使用还是 PC 上通过浏览器使用，只要浏览器能够访问手机伺服的内核就能够使用。

### 文件结构

初次启动后在  `/sdcard/siyuan/` 文件夹下展开如下文件夹：

* `app`：存放外观、用户指南和界面程序
* `conf`：存放配置文件
* `data`：存放数据，下面的每个文件夹是一个笔记本 https://github.com/siyuan-note/siyuan/issues/1085
* `temp`：临时数据

### 备份

手机作为移动服务器虽然方便，但是有个比较致命的缺点就是不够稳定，比如容易损坏或者丢失，所以需要数据备份。用户可考虑使用手机自带的网盘或者其他网盘服务。

手机上的大致操作步骤如下：

1. 通过手机文件管理功能进入 `内部存储设备/siyuan/` 文件夹
2. 选择 `data` 文件夹并进行压缩
3. 将压缩后生成的 `data.zip` 上传到云盘

## 耗电

用完可手动退出，不会太占资源和耗电。

**Comment by HaujetZhao** [comment]
建议也打包一个可以在 Termux 上运行的二进制包。Termux 是 Android 上的一个终端工具，它有一个包管理器 pkg，也可以使用 dpkg 安装 deb 包。
