### ISSUE TITLE
期待功能：大纲-思维导图的转换，脑图的样式修正，标题的样式设置，横向排版的优化

### ISSUE THREAD

**Issue by H-a-r-r-o-w** [siyuan-note/siyuan#1062]
首先是现在推出了思维导图，可不可以参考一下RoamEdit的大纲-思维导图之间的转换，推出类似的应用？现在的缩进转思维导图非常奇怪...
![IMG_0791](https://user-images.githubusercontent.com/77455480/104625254-84bb0480-56cf-11eb-8e2a-87bd8526b09b.PNG)
二来是现在导图如果字数较多，将会以“...”代替后续内容且无法展开，可否增加相关的设置？
三是标题，现在H1和H2都会自带分隔线，请问可不可以增加相关的设置取消分割线？不然多重标题嵌套看起来会很混乱。
最后是希望可以优化横向排版，参考Notion的横向块并列，这样单个笔记内的排版就可以更有序了。
感谢D大Orz，并不懂代码不清楚这方面的实现难度，如果发出了愚蠢发言的话真的非常抱歉Orz

**Comment by 88250** [comment]
你好，导图的渲染是设计如此，所有内容块都会在导图上渲染；大纲分隔线样式请用主题扩展，有的主题没有分隔线；横向排版能力后期应该会引入，请关注 #790 ，谢谢。
