### ISSUE TITLE
希望有更多能默认将不同块连在一起的默认样式

### ISSUE THREAD

**Issue by CSMsamuel** [siyuan-note/siyuan#10628]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/105100795/8a381fca-c671-4abb-b852-f25d0acbd8ac)

如图，希望能够有像markdown默认语法类似效果的块样式，实现不同块之间默认连在一起。

### Describe the optimal solution

增加一些默认选项

**Comment by CSMsamuel** [comment]
图片中用的是默认的信息样式。

**Comment by 88250** [comment]
块之间的区隔是设计如此，可以尝试通过自定义 CSS 修改样式。
