### ISSUE TITLE
Improve rendering of inline code, kbd and tag to avoid repeated rendering of zero-width spaces on the right

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#10629]
行内代码异常现象

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

行内代码在重启思源后会额外增加一个zeroWidthSpace,如下
![Clip_2024-03-17_01-29-04](https://github.com/siyuan-note/siyuan/assets/48077521/f2bb90f0-eb28-4b7c-b1b0-64a811b8ce60)

### Expected result

重启后依然是2个zwsp

### Version environment

```markdown
- Version: v3.0.3
- Operating System:  win10
- Browser (if used):
```

### Log file

1

**Comment by iamqiz** [comment]
@Vanessa219  为啥加两个zeroWidthSpace呢?
![Clip_2024-03-17_12-21-50](https://github.com/siyuan-note/siyuan/assets/48077521/f51ca191-5bcb-4643-94eb-70fcc7f03305)

**Comment by 88250** [comment]
为实现←和→跳出



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 17, 2024 12:24 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve rendering of inline code, kbd andtag to avoid repeated rendering of zero-width spaces on the right (Issue#10629)




 
@Vanessa219  为啥加两个zeroWidthSpace呢?
 Clip_2024-03-17_12-21-50.png (view on web)
