### ISSUE TITLE
增加「最近关闭的文档」

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10623]
### In what scenarios do you need this feature?

[是否应该增加「最近关闭的文档」功能？ - 链滴](https://ld246.com/article/1710251093938)

在桌面端，如果是最近看过的文档，我当然知道是在哪个页签。

通常情况下我使用「最近的文档」功能是为了找到刚才不小心关闭的页签，但这个页签可能放在上面很久都没打开看过，这时候就没法在「最近的文档」里找到刚才关闭的页签。

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dba2c807-1179-4429-a968-4abf30123aab)

### Describe the optimal solution

1. 在界面上增加「最近关闭的文档」，和目前的「最近浏览的文档」共存
2. 增加 `Ctrl+Shift+T` 快捷键以打开最近关闭的页签/窗口

**Comment by MrIntellectX** [comment]
I was about to post the same.

**Comment by TCOTC** [comment]
> I was about to post the same.

Thanks. It would be nice if the code could be merged into SiYuan, and of course the plugin would be nice too.

**Comment by MrIntellectX** [comment]
> > > I was about to post the same.
> > 
> > 
> > Thanks. It would be nice if the code could be merged into SiYuan, and of course the plugin would be nice too.
> 
> It's also possible that you meant "我也正要提出相同的 issue", then I misunderstood your reply. After all, I haven't learned English specifically.

 "我也正要提出相同的 issue" <- Yes, this is what I meant.

**Comment by QQQOrange** [comment]
好功能，支持

**Comment by Achuan-2** [comment]
+1，同需要最近关闭文档功能，我自己大多数情况ctrl+e，都是在找最近关闭的文档，
目前ctrl+e是最近打开文档，这就导致有些文档，并不是最近打开，但是被我不小心关闭或暂时关闭了，我就得在最近打开文档下拉找了，不是很方便

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/11189 中处理。
