### ISSUE TITLE
Bilibili iframe block disables autoplay

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10621]
https://ld246.com/article/1710416498631

**Comment by AvoidantPerDis** [comment]
测了好像无效？

**Comment by AvoidantPerDis** [comment]
代码还是
> <iframe src="https://player.bilibili.com/player.html?aid=32333800&amp;bvid=BV1xW411z75i&amp;cid=56568351&amp;p=1" data-src="//player.bilibili.com/player.html?aid=32333800&amp;bvid=BV1xW411z75i&amp;cid=56568351&amp;p=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" style="width: 727px; height: 410px;"></iframe>

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/1aa01e05-dfea-4088-8eb5-1710bb619e72)

**Comment by AvoidantPerDis** [comment]
还是得加&autoplay=0

**Comment by AvoidantPerDis** [comment]
[测试.sy.zip](https://github.com/siyuan-note/siyuan/files/14644446/sy.zip)

**Comment by houzy** [comment]
下载了最新的3.0.4，还是会直接播放，没有修复呀？

**Comment by houzy** [comment]
我知道了，以前加的资源要删除重新添加，重新添加的是不会自动播放的

**Comment by Vanessa219** [comment]
嗯嗯，不会去改动用户以前的数据的。
