### ISSUE TITLE
svg 格式图片，如果没有写width和height，但给了 viewbox，显示有问题

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#10627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

It shwo
![image](https://github.com/siyuan-note/siyuan/assets/5683995/386a095e-f2c9-4d01-9239-d85edf5c4014)
测试svg图片
https://docs.unity3d.com/6000.0/Documentation/uploads/Main/BestPracticeLightingPipeline5.svg

### Expected result

能正确显示

### Version environment

```markdown
- Version: 3.0.3
- Operating System: Win11 
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
使用 img 引入 svg 不会读取 viewbox 的值，可以手动设置一下宽度为 100%
