### ISSUE TITLE
支持阿里云盘数据同步

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10630]
https://ld246.com/article/1690962819321

**Comment by banjuer** [comment]
这个好，阿里网盘目前还没有明显限速，就是不知道会不会对读写频率有要求

**Comment by zongqir** [comment]
关了吧 这个需求 有S3就够了啊
云盘后续关了 岂不是浪费开发时间！

**Comment by TCOTC** [comment]
> 关了吧 这个需求 有S3就够了啊 云盘后续关了 岂不是浪费开发时间！

你这完全不管小白了啊

**Comment by TCOTC** [comment]
好像没有必要支持阿里云盘了 https://www.nodeseek.com/post-98493-1

**Comment by 88250** [comment]
不考虑了，还是推荐 S3 存储。
