### ISSUE TITLE
自动删除备注中的特殊符号

### ISSUE THREAD

**Issue by xiaoheimissu** [siyuan-note/siyuan#10639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当备注中有特殊符号时, 特别时是'$', 在某些情况下会自动删除备注中的特殊符号, 复现的情况是在编辑完成一个块, 点击回车键之后.

https://github.com/siyuan-note/siyuan/assets/68829841/c7697b96-fc08-41b9-9fe7-9abd06caf8eb

### Expected result

不应当在未经同意的情况下更改备注中的内容, 这导致了一些问题, 比如在开发备注相关的插件时:
![image](https://github.com/siyuan-note/siyuan/assets/68829841/0dc86613-5605-4a98-8e9c-abe93f509f33)
其会引发一些连带bug:
![image](https://github.com/siyuan-note/siyuan/assets/68829841/085f8098-d6e0-4edc-98ae-2fd9cd28e397)
使得插件无法识别备注中的内容

(之前的测试是在未装任何插件和默认主题下, 并不是插件引起的)

### Version environment

```markdown
- Version: v3.0.2
- Operating System: Windows 11 Enterprise 
- Browser (if used): None
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14628184/siyuan.log)

**Comment by xiaoheimissu** [comment]
> 这个好像是有意为之（设计如此）

可能是为了防止xss攻击？但是对于笔记软件感觉并没有太多必要。

**Comment by 88250** [comment]
备注中只能包含纯文本（不能包含其他行级元素标记符），否则会导致解析问题。
