### ISSUE TITLE
可否提供更多关于asset/upload 的api指引？

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

配置如下：
![IMG_9306](https://github.com/siyuan-note/siyuan/assets/5708881/2cb270cc-892e-40a4-8a2a-561c2276b8e6)
返回报错如下：
![image](https://github.com/siyuan-note/siyuan/assets/5708881/55daa058-9544-4952-b293-62a43bfc1e12)

可否提供更多关于asset/upload 的api指引？

### Expected result

如图

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

如图

**Comment by 88250** [comment]
请在思源中打开开发者工具，通过参考 Network 请求进行开发。
