### ISSUE TITLE
Can I open the same local folder in another directory??

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#1063]
I want to open two:  both same directory `user-guide-en_US`.  One is in directory `old`, other one is `new`

I can not open the both.

![sg1](https://user-images.githubusercontent.com/15811943/104666851-76062a80-569a-11eb-8670-62ad9425aa2e.gif)

**Comment by 88250** [comment]
Hello, SiYuan do not support open different folder path with the same base name.

**Comment by jakekwak** [comment]
Thanks, I want to catch up everything.
