### ISSUE TITLE
数据库界面搜索按钮无法粘贴

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#10631]
数据库界面搜索按钮无法粘贴

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库界面搜索按钮无法粘贴
已关闭所有插件、代码片段、使用daylight主题

### Expected result

数据库界面搜索按钮可以粘贴

### Version environment

```markdown
- Version: v3.0.3
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
下个版本改进，感谢反馈。
