### ISSUE TITLE
History Modification of Each Block

### ISSUE THREAD

**Issue by abd-liac** [siyuan-note/siyuan#10638]
### In what scenarios do you need this feature?

When implementing daily note strategy, we may firstly spot the feeling but only have a vague expression, and over time it will be clear enough to convey or record.
It is interesting and meaningful to observe how the idea gradually grow to make sense.

### Describe the optimal solution

Like docs, we can check the history of each block individually, maybe like git blame.

### Other information

I don't currently have a good visualization, and technical issue may raise, so it is okay to let the issue remain draft if you feel directionless as well.

**Comment by zxhd863943427** [comment]
check plugin "block history"
