### ISSUE TITLE
Eliminate Whitespace When Double Click on The Word

### ISSUE THREAD

**Issue by abd-liac** [siyuan-note/siyuan#10640]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/88515612/a8e237ea-ec6d-4178-928a-f9826b6899fd)
*to visualize*

### Describe the optimal solution

Eliminate whitespace when double click on the word.

**Comment by 88250** [comment]
https://superuser.com/questions/282568/is-there-a-way-to-not-select-whitespace-after-a-word-when-double-clicking
