### ISSUE TITLE
单独粘贴 # 为什么会另起一行？

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#10648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![CleanShot 2024-03-19 at 11 00 07](https://github.com/siyuan-note/siyuan/assets/50087596/0e8d401a-e8ce-4325-a030-cbb1c590e82f)
如gif所示。

### Expected result

不是应该直接粘贴到后面吗？
![CleanShot 2024-03-19 at 11 02 04](https://github.com/siyuan-note/siyuan/assets/50087596/514c9f91-fe86-4b77-818b-552d311fb669)

### Version environment

```markdown
- Version: 3.0.4
- Operating System: macOS Ventura
- Browser (if used):
```

### Log file

*

**Comment by TCOTC** [comment]
可以复现

**Comment by 88250** [comment]
因为 `#` 命中了 Markdown 标题块语法，所以另起一行转换为 H1。如果需要粘贴 `#` 的话可以试试 `粘贴转义文本`。

**Comment by LoneFireBlossom** [comment]
> 因为 `#` 命中了 Markdown 标题块语法，所以另起一行转换为 H1。

哦，原来是feature。那我知道了

**Comment by TCOTC** [comment]
这个问题在之后已经修复了，复制粘贴符号到非块首是不应该转换块类型的
