### ISSUE TITLE
在表格中输入任何内容表头会出现{: class="fr-fix-ea6afdda"}

### ISSUE THREAD

**Issue by Hualoong** [siyuan-note/siyuan#10642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在表格中输入任何内容表头会出现{: class="fr-fix-ea6afdda"}

### Expected result

在表格中输入任何内容表头内容不会变化

### Version environment

```markdown
- Version: v3.0.3
- Operating System: Debian 12 / Docker version 25.0.3, build 4debf41
- Browser (if used): Microsoft Edge 122.0.2365.9
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14631745/siyuan.log)

**Comment by 88250** [comment]
我这里无法重现问题，请关闭所有插件、代码片段，在默认主题下测试看看。

**Comment by Hualoong** [comment]
![QQ截图20240321132410](https://github.com/siyuan-note/siyuan/assets/863450/1b1e8aaf-6c13-4ac4-97c6-54d6a7a77218)
删除所有主题、插件、挂件等问题依旧；
删除Docker容器后重新创建容器，问题依旧。
