### ISSUE TITLE
Search type filtering supports Audio, Video, IFrame and Widget block

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#10645]
一个小问题，搜索时，搜索类型设置为只有文档，但所有视频资源也被检索出来了

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下，搜索类型，设置为只搜索文档

![image](https://github.com/siyuan-note/siyuan/assets/5683995/9d246c20-c24b-4449-afe9-b379b3cc9019)

以搜索 Control 为例，出现了很多名字带有 Control 的视频文件

![image](https://github.com/siyuan-note/siyuan/assets/5683995/ec99d9d1-666f-432f-9524-4f699c3f49fa)

### Expected result

不包括视频文件

### Version environment

```markdown
- Version: 3.0.3
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
勾选了 设置 - 搜索 - 索引资源文件路径 ？

**Comment by zhoutaosheng** [comment]
> 勾选了 设置 - 搜索 - 索引资源文件路径 ？

并没有勾选
![image](https://github.com/siyuan-note/siyuan/assets/5683995/2f3bc881-2809-429d-b074-f50b9f1b82f9)

**Comment by 88250** [comment]
收到，稍后排查。
