### ISSUE TITLE
颜色取消后，粗体页需要取消

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#1064]
1. When I click on the color, the color panel should disappear.

2.  undo the color( ALT+X),  still remain ****

![sg3](https://user-images.githubusercontent.com/15811943/104668469-be731780-569d-11eb-904f-825c0d5d8fae.gif)

**Comment by Vanessa219** [comment]
1. I am worried that users need to try a few more colors
2. This can be improved
