### ISSUE TITLE
建议增加 自动、同步生成markdown本地文件夹 的功能，保证数据一致性，避免反复导出或复制文本。

### ISSUE THREAD

**Issue by PayneSnow** [siyuan-note/siyuan#1065]
现在思源笔记支持手动导出markdownown文件。

希望增加一个插件，在使用或者关闭思源笔记的时候，将整个思源笔记或者**某个文件夹下的笔记自动、同步生成Markdown文件的备份本地文件夹**。

需求：笔记一般内存不太大。希望能够直接**打通思源笔记和普通的Markdown编辑器**，**保证数据一致性**。比如，关闭思源笔记后，我可以直接使用ulysses打开，而使用完ulysses后，我又可以直接用思源笔记打开。

场景：如果一份文档，我先用思源笔记编辑，然后再使用ulysses修改。这样的话，我需要**先手动**从思源笔记**导出**，然后在使用ulysses修改后，又会**产生一个新版本的文档**。这个时候，为了保证数据一致性，我**还需要再次将新版本的文档直接复制至思源笔记**。

**Comment by 88250** [comment]
你好，思源在导入的时候会生成块 ID，如果重新导入的话 ID 会变，这样会引入其他问题。所以导出后的 Markdown 思源认为应该是“只读”的。

实时导出之前有，但是后来去掉了，这部分我们考虑后期通过插件进行支持，谢谢。

**Comment by PayneSnow** [comment]
感谢，期待后期增加插件。


| |
余富强
|
|
pilgrim112@163.com
|
签名由网易邮箱大师定制


在2021年01月15日 09:35，D<notifications@github.com> 写道：

Closed #1065.
