### ISSUE TITLE
3.0.4更新后Database资源连接无法单击打开

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#10658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

3.0.4更新后Database本地链接无法单击打开
点击如图database中的本地链接无反应，
上一个版本可以正常打开记事本和资源管理器的

![image](https://github.com/siyuan-note/siyuan/assets/5226690/e3dadcdd-fc6a-4cb6-a798-eeeba65067eb)

### Expected result

恢复能能够单击打开默认程序

### Version environment

```markdown
- Version: 3.0.4
- Operating System: win11
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
感谢反馈，合并到 https://github.com/siyuan-note/siyuan/issues/10650 中解决。
