### ISSUE TITLE
Persistent document tree expansion state

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10652]
持久化文档树展开状态 ，存储每个层级的文档树展开状态

### In what scenarios do you need this feature?

笔记本比较多、文档层级也很深，每次都要重新展开文档树比较麻烦，所以需要在重载界面、重启软件后恢复上次的文档树展开状态

[如何保持文档树展开状态？投票 - 链滴](https://ld246.com/article/1701949943081)

#6098

### Describe the optimal solution

在重载界面、重启软件后恢复上次的文档树展开状态

**Comment by TCOTC** [comment]
另外不要折叠一下展开的文档就把低层级的文档也全部折叠了，举个例子就是：

原本是这样展开的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5c54904b-d8d0-4841-93fe-4177f6073a13)

但折叠了 `【领域】创作` 之后再展开，就会发现 `写作` 也被折叠了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7642e67d-3f7f-4a29-805d-cf9e6ebbe429)

**Comment by 88250** [comment]
保留子级的折叠状态在需要收起时会很麻烦，所以暂时不考虑了。

**Comment by realysy** [comment]
> 保留子级的折叠状态在需要收起时会很麻烦，所以暂时不考虑了。

需要收起时，对收起按钮双击或者长按方便实现吗？

![图片](https://github.com/siyuan-note/siyuan/assets/55436543/9587a635-a10b-46a9-848b-22a1553d9da3)

**Comment by 88250** [comment]
@realysy 双击操作不考虑了，会和展开冲突。长按的话好像桌面端没有这种交互逻辑，也不考虑了哦。

**Comment by realysy** [comment]
好的吧

**Comment by Dayflare** [comment]
i would really like this feature. It's useful especially if you have many documents in your tree.

**Comment by LoneFireBlossom** [comment]
> @realysy 双击操作不考虑了，会和展开冲突。长按的话好像桌面端没有这种交互逻辑，也不考虑了哦。

这个操作参考macOS Finder，按住option键，在这种视图下，按住option键点击箭头可以一键展开所有目录；在箭头展开的情况下，按住option键点击箭头可以一键收起整个目录。
<img width="386" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/3d6bc833-2443-415b-ba21-e4aa50e4ab93">

**Comment by TCOTC** [comment]
保存布局时也保存文档树状态：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/20aacf46-3d29-4d0d-89ee-99d889e3b477)

**Comment by TCOTC** [comment]
https://ld246.com/article/1718336173522

**Comment by Chenm4** [comment]
我也是强烈建议持久化文档树展开状态，很需要。每次都是给我折叠了，但是层级深了很麻烦。希望能在配置文件中保存当前文档树状态

**Comment by KuiyueRO** [comment]
赞同，移动笔记后也会折叠低层级的文档，整理的时候总是需要展开

**Comment by 5kyfkr** [comment]
喜大普奔，终于支持了

**Comment by TCOTC** [comment]
> 保存布局时也保存文档树状态

@Vanessa219 还需要实现这个

**Comment by TCOTC** [comment]
> 保留子级的折叠状态在需要收起时会很麻烦，所以暂时不考虑了。

@88250 保留子级的折叠状态真的会方便很多（比如用 VSCode 的时候，一直保持子级展开，可以临时折叠父级），需要全部层级折叠的话用文档树上的 `折叠` 按钮来实现就好了。

**Comment by 88250** [comment]
不一定方便，比如 JetBrains 就不保留。

**Comment by TCOTC** [comment]
要不发个投票看看？

**Comment by 88250** [comment]
不需要了吧，只要有人觉得不需要保留那就不保留了。

**Comment by TCOTC** [comment]
那就先不考虑保留了。

再解决一下这个需求：

> 保存布局时也保存文档树状态

**Comment by 88250** [comment]
@Vanessa219

**Comment by TCOTC** [comment]
> 保留子级的折叠状态在需要收起时会很麻烦，所以暂时不考虑了。

VScode 有一个专门的按钮用来清除展开与折叠的状态，恢复到全部折叠：

<img width="962" height="414" alt="Image" src="https://github.com/user-attachments/assets/90724f98-bb8f-4993-a1e1-f66a96108715" />
