### ISSUE TITLE
Clicking on the asset should open with the default program

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10650]
点击资源文件应使用默认程序打开

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

因为浏览器不支持很多格式的文件，所以目前点击资源文件(大多数情况下)会打开浏览器下载。要使用默认程序打开还要打开二级菜单，非常麻烦。

[思源笔记 3.0.4 点击附件弹出浏览器下载 - 链滴](https://ld246.com/article/1710823686305)

[升级之后打开笔记内的 excel 文件变成默认浏览器下载了 - 链滴](https://ld246.com/article/1710818133060)

### Expected result

至少在桌面端，点击资源文件应使用默认程序打开

### Version environment

```markdown
- Version: v3.0.4
- Operating System: Windows 10
```

### Log file

无

**Comment by TCOTC** [comment]
#10604

**Comment by TCOTC** [comment]
#10641

**Comment by TCOTC** [comment]
还有个 BUG ：无论使用哪种方式点击，都会先唤起浏览器下载。而打开菜单点击就正常

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fec02eab-9d84-4408-9705-382885fd230e)

**Comment by 5kyfkr** [comment]
另外在移动端有没可能实现直接跳转打开word excel ppt等文件？现在也是先下载到浏览器才能打开，在平板端可以内部打开pdf，手机端pdf也是跳到浏览器下载了

**Comment by 88250** [comment]
手机端只能浏览器统一对接



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 19, 2024 18:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Clicking on the asset should open with thedefault program (Issue #10650)




 
另外在移动端有没可能实现直接跳转打开word excel ppt等文件？现在也是先下载到浏览器才能打开，在平板端可以内部打开pdf，手机端pdf也是跳到浏览器下载了

**Comment by TCOTC** [comment]
能不能实现点击之后弹出手机自带的「打开方式...」界面？

**Comment by 88250** [comment]
@TCOTC 

> 能不能实现点击之后弹出手机自带的「打开方式...」界面？

暂时不确定如何实现，请单独开一个 issue 记录。

**Comment by Vanessa219** [comment]
目前为了保持一致，click 为右侧打开；alt+click 为当前页签打开；ctrl+click 为打开当前文件所在的文件夹；shift+click 为使用默认程序打开。其中：
1. 基于以上原则，如果为思源内部文件且后缀不为  [".apng", ".ico", ".cur", ".jpg", ".jpe", ".jpeg", ".jfif", ".pjp", ".pjpeg", ".png", ".gif", ".webp", ".bmp", ".svg", ".avif", ".mp3", ".wav", ".ogg", ".m4a", ".mov", ".weba", ".mkv", ".mp4", ".webm", ".pdf"] 的， click、alt+click、shift+click 都为使用默认程序打开
2. 如果不是思源内部资源文件则使用浏览器打开
3. 如果无法调用默认程序打开、无法打开所在文件位置的则由各端使用对应的方式进行打开。

**Comment by luo-chuan** [comment]
> 目前为了保持一致，click 为右侧打开；alt+click 为当前页签打开；ctrl+click 为打开当前文件所在的文件夹；shift+click 为使用默认程序打开。

V大，我想让ctrl+click为默认程序打开

**Comment by TCOTC** [comment]
> > 目前为了保持一致，click 为右侧打开；alt+click 为当前页签打开；ctrl+click 为打开当前文件所在的文件夹；shift+click 为使用默认程序打开。
> 
> V大，我想让ctrl+click为默认程序打开
> 
> 

请看 #10641
