### ISSUE TITLE
Can't switch workspaces on mobile app

### ISSUE THREAD

**Issue by Yoqazij** [siyuan-note/siyuan#10654]
Switch Workspace Android

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When trying to switch the workspace the app closes and afterwards, when I restart the app, the same workspace opens up and not the one I picked. 

### Expected result

Workspace should change on startup 

### Version environment

```markdown
- Version: 3.0.4
- Operating System: Android
```

### Log file

Cant find the log file on android.

**Comment by 88250** [comment]
还有些问题，在 https://github.com/siyuan-note/siyuan/issues/16544 中继续修复。
