### ISSUE TITLE
Support adding multiple rows in database table view

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10667]
https://ld246.com/article/1710486417808
支持数据库表格添加多行的功能

**Comment by TCOTC** [comment]
能不能像飞书那样，右键点击后默认填充数字 `1` ，然后左键点一下就可以添加行（我用的 v3.0.5-dev2 只能输入数字之后按Enter）

**Comment by Vanessa219** [comment]
试了下好像不行，要 Enter 呀

**Comment by TCOTC** [comment]
GIF：

![飞书](https://github.com/siyuan-note/siyuan/assets/78434827/9e9b4f40-5e22-478b-9d2a-9bd8218b704b)

**Comment by Vanessa219** [comment]
此操作好隐蔽
