### ISSUE TITLE
Data snapshots support pagination navigation

### ISSUE THREAD

**Issue by VxRain** [siyuan-note/siyuan#10662]
### In what scenarios do you need this feature?

目前我的云端快照有149页，如果想要浏览记录，只能上一页或者下一页，这样一下一下的点，太麻烦了。

### Describe the optimal solution

云端快照新增分页导航，支持跳转页面。
文件历史最好也加上分页，保持一致。

**Comment by 88250** [comment]
已在 https://github.com/siyuan-note/siyuan/pull/12548 中改进。

**Comment by TCOTC** [comment]
还缺少分页导航

**Comment by 88250** [comment]
PR 已经可以指定页码导航了。
