### ISSUE TITLE
Remove translation part to simplify block AI menu

### ISSUE THREAD

**Issue by AsafMah** [siyuan-note/siyuan#10669]
Customize AI menu/ more languages?

### In what scenarios do you need this feature?

Currently, the artificial intelligence menu shows a bunch of languages, most users won't know/need them all.
Same with the actions.

### Describe the optimal solution

1. Let us choose/edit the languages we care about to translate. Personally, I need only Hebrew and English.
2. Let us edit the menu permanently, so we can keep the menu simple and to the point.

**Comment by 88250** [comment]
We will remove the translation part in the near future, and this part can be replaced by user-defined actions.

**Comment by adocampo** [comment]
I used the translation a lot, how can I get it back?

**Comment by 88250** [comment]
Please use custom action instead.



---Original---
From: "Angel ***@***.***&gt;
Date: Wed, Apr 3, 2024 19:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Remove translation part to simplify block AImenu (Issue #10669)




 
I used the translation a lot, how can I get it back?

**Comment by Eyion** [comment]
如何配置AI
