### ISSUE TITLE
操作优化 | 调整 Dock 栏图标的布局顺序

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#10664]
### In what scenarios do you need this feature?

当前只能允许侧边栏 icon 在几个 dock bar 当中移动位置，但是不允许用户在当前 dock bar 中自由调整顺序。

如果想要调整顺序，必须先心中想好想要调整成什么样子，然后按照一定的顺序把 icon 一次顶到dock bar的顶部，操作起来非常麻烦。

### Describe the optimal solution

在 dock 菜单下方，增加两个按钮

- 上移：将 icon 向上移动一个位置
- 下移：将 icon 向下移动一个位置

![image](https://github.com/siyuan-note/siyuan/assets/27268127/961d79c4-1155-444f-9252-20d9c423ad93)

**Comment by 88250** [comment]
这个不加了吧，搞定 #10247 就可以了，感谢提议。

**Comment by frostime** [comment]
> > 这个不加了吧，搞定 #10247 就可以了，感谢提议。
> 
> Fine, 这个更好

期待尽早加入 Milestone 😁
