### ISSUE TITLE
移动块支持双击选定

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10663]
交互优化：如GIF鼠标位置应该双击直接选定。

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如GIF所示，应该双击（或单击）直接选定。
![交互优化](https://github.com/siyuan-note/siyuan/assets/5708881/8525a62b-a534-4c87-995d-6fd83ea6acd0)

### Expected result

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
无
```

### Log file

无

**Comment by Vanessa219** [comment]
那就用回车，比双击更快速
