### ISSUE TITLE
AI supports configuration randomness and context number

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10660]
AI 支持配置随机性和上下文数

**Comment by QQQOrange** [comment]
> AI 支持配置随机性和上下文数

精简翻译也求求了

**Comment by 88250** [comment]
不动了，以便便捷使用。



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 20, 2024 09:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] AI supports configuration randomness andcontext number (Issue #10660)




  
AI 支持配置随机性和上下文数
  
精简翻译也求求了

**Comment by 88250** [comment]
去掉翻译后续请关注 https://github.com/siyuan-note/siyuan/issues/10669

**Comment by QQQOrange** [comment]
> 去掉翻译后续请关注 https://github.com/siyuan-note/siyuan/issues/10669

！！！！ 大佬牛逼
