### ISSUE TITLE
尝试在列表中间按两次enter键时，会导致工作区重新加载，输入的列表内容也会消失

### ISSUE THREAD

**Issue by shiyukonghui** [siyuan-note/siyuan#10677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在输入以下格式文本时，当我尝试在列表中间按两次enter键时，会导致工作区重新加载，输入的列表内容也会消失。
1. 为Main节点添加一个新脚本
2. 在Main节点下添加一个Timer定时器，命名为MobTimer

    1. 将Wait Time设置为0.5s，打开Autostart
3. 在Main方法中添加一个`OnMobTimerTimeout()`方法
4. 将M

### Expected result

工作区不会重新加载并导致输入的内容丢失。

### Version environment

```markdown
- Version: 3.0.4
- Operating System: win10
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14681354/system-log.zip)

**Comment by shiyukonghui** [comment]
[Video_2024-03-21_113259.zip](https://github.com/siyuan-note/siyuan/files/14681444/Video_2024-03-21_113259.zip)

**Comment by 88250** [comment]
你好，我这里测试正常。

请使用默认主题并关闭所有插件、代码片段等扩展后再测试。
