### ISSUE TITLE
`Unreferenced assets` support copy file name

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10676]
优化未引用资源文件功能

### In what scenarios do you need this feature?

希望在箭头处添加复制按钮，该按钮的功能是复制该文件的资源链接，方便用户在合适的地方重新进行引用
![image](https://github.com/siyuan-note/siyuan/assets/16383685/31d0d136-1906-40c9-8e24-21ec7d5c5805)

### Describe the optimal solution

RT

**Comment by 88250** [comment]
前面的部分可以划选然后 Ctrl+C，需要插入的地方 /资源 然后 Ctrl+V

**Comment by woniuxia** [comment]
> 前面的部分可以划选然后 Ctrl+C，需要插入的地方 /资源 然后 Ctrl+V

但是不太顺手，希望能优化下体验。
直接点一下按钮，然后直接ctrl+v 更丝滑。

**Comment by 88250** [comment]
考虑过的，复制会有歧义，比如是复制文本还是文件？交互有歧义的地方不引入为好。

**Comment by woniuxia** [comment]
那有没有可能增加两个按钮，一个是复制资源引用链接，一个是复制文件

**Comment by 88250** [comment]
没有必要吧……

**Comment by woniuxia** [comment]
虽然小改动，但是使用体验大幅度提升。
@Vanessa219 V大瞅瞅呢。

**Comment by 88250** [comment]
获取可以提供一个复制文件名的按钮，这样既方便在 /资源 搜索，也方便在系统文件浏览器上搜索

**Comment by woniuxia** [comment]
可以的，辛苦D大

**Comment by Vanessa219** [comment]
复制`丢失的资源文件`也修改为复制文件名
