### ISSUE TITLE
Supports specifying the notebook to save new docs

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10671]
新建文档支持指定笔记本

### In what scenarios do you need this feature?

最近在看 [双向链接时代的快速无压记录](https://www.yuque.com/deerain/gannbs/ffqk2e) ，尝试用 daily notes ，想把新建的文档集中到同一个笔记本里（一层文档），但发现只能新建到当前焦点文档的笔记本。所以希望新建文档支持指定笔记本。

[希望新建文档支持指定笔记本 - 链滴](https://ld246.com/article/1710952748934)

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/78434827/40cb1830-bfbc-446a-ab4a-227bd751fbfb)

- 当前笔记本（默认位置）
- 指定笔记本
  - 后面没有指定路径 (`/`) 的情况下，指定笔记本无效，新建的文档仍存放到默认位置
  - 指定笔记本关闭时，新建的文档存放到默认位置，重新打开后继续存放到指定笔记本
  - 指定笔记本删除后，设置项恢复为默认位置

**Comment by TCOTC** [comment]
[希望新建文档支持指定笔记本 - NishikigiReeves 的回帖 - 链滴](https://ld246.com/article/1710952748934/comment/1711071855666#comments) 增加一条：

> 增加一种新建文档默认在当天 dailynotes 下面的方式。
> 
> 如果是笔记本，时间长了会堆积好长好长，但是如果新建的文档自己归拢到当天的 dailynotes 下面，就清爽又有迹可循了

**Comment by 88250** [comment]
> [希望新建文档支持指定笔记本 - NishikigiReeves 的回帖 - 链滴](https://ld246.com/article/1710952748934/comment/1711071855666#comments) 增加一条：
> 
> > 增加一种新建文档默认在当天 dailynotes 下面的方式。
> > 如果是笔记本，时间长了会堆积好长好长，但是如果新建的文档自己归拢到当天的 dailynotes 下面，就清爽又有迹可循了

这个应该可以用日记模板实现吧。

**Comment by TCOTC** [comment]
确实这个目前就可以实现：

把日记的路径 `/daily note/{{now | date "2006/01"}}/{{now | date "2006-01-02"}}/{{now | date "20060102150405"}}` 填写到下面：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a996f0af-dc63-452a-91c5-e620a7b4fe6e)

**Comment by Jiangshuon** [comment]
[[建议把新建的页面放入之前指定好的笔记本 - 链滴 (ld246.com)](https://ld246.com/article/1704286951023)](https://ld246.com/article/1704286951023)

[[希望新建文档支持指定笔记本 - 链滴 (ld246.com)](https://ld246.com/article/1710952748934)](https://ld246.com/article/1710952748934)

[[希望能加强【无压力记录】的相关功能 - 链滴 (ld246.com)](https://ld246.com/article/1698646168172)](https://ld246.com/article/1698646168172)

[[如何设置块引新建文档存放位置为另一笔记本？ - 链滴 (ld246.com)](https://ld246.com/article/1691228966084)](https://ld246.com/article/1691228966084)

[[“块引新建文档存放位置”设置 - 链滴 (ld246.com)](https://ld246.com/article/1659286426157)](https://ld246.com/article/1659286426157)

[[如何将多个笔记本新建的引用块文档指定在同一个目录下？ - 链滴 (ld246.com)](https://ld246.com/article/1635410666721)](https://ld246.com/article/1635410666721)

[[Ctrl+N 新建文档位置无法固定 - 链滴 (ld246.com)](https://ld246.com/article/1656834415701)](https://ld246.com/article/1656834415701)

[[笔记本的块引新建文档存放位置怎么设置成另一个笔记本？ - 链滴 (ld246.com)](https://ld246.com/article/1647333953780)](https://ld246.com/article/1647333953780)

**Comment by Jiangshuon** [comment]
再顶顶！思源重度用户一枚，每天手动高频移动文档。。

**Comment by TCOTC** [comment]
新建文档为笔记本的第一层文档时，`/` 会自动变成 `/Untitled` ：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3b04d114-0d44-49da-8b41-6a8c328a290b)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a280f993-d515-4ba9-8b13-95d46d18af89)

新建文档为某个文档的子文档就不会变：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ed7d24b8-12d5-492d-9a9b-676bb80aa5e8)

然后就会分别创建出带标题的文档和不带标题的文档：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b5245392-1460-4904-abd3-4d84f7622425)

@88250 `/` 应该没必要变成 `/Untitled` 吧？

**Comment by 88250** [comment]
这个只能这样，不然会有其他问题 https://github.com/siyuan-note/siyuan/issues/10305

**Comment by TCOTC** [comment]
总感觉有点奇怪，只能自动加上文档名而没有其他方式处理吗？

**Comment by 88250** [comment]
是的，这个路径填的是最终文档的 HPath，不是父路径，所以必须精确到文档名。

**Comment by 88250** [comment]
要指定文档名的，不指定的话 / 就在根路径上了。

**Comment by Jiangshuon** [comment]
什么意思，我现在没有指定“/"，可以正常工作呀，创建直接就在默认笔记本的第一级别了，我只是指定了下笔记本

**Comment by Jiangshuon** [comment]
另外，全局设置和笔记本设置，两者的关系是什么呢，笔记本设置后就可以完全覆盖全局设置吗？

**Comment by TCOTC** [comment]
> 什么意思，我现在没有指定“/"，可以正常工作呀，创建直接就在默认笔记本的第一级别了，我只是指定了下笔记本

你可以在这个笔记本里的文档内按 `Ctrl+N` 新建文档，会在该文档下创建子文档

**Comment by 88250** [comment]
> 什么意思，我现在没有指定“/"，可以正常工作呀，创建直接就在默认笔记本的第一级别了，我只是指定了下笔记本

上面说的是设置为 `/` 时会自动补全为 `/Untitled`。

**Comment by TCOTC** [comment]
> 另外，全局设置和笔记本设置，两者的关系是什么呢，笔记本设置后就可以完全覆盖全局设置吗？

我才发现笔记本设置里也有

**Comment by 88250** [comment]
> 另外，全局设置和笔记本设置，两者的关系是什么呢，笔记本设置后就可以完全覆盖全局设置吗？

对

**Comment by Jiangshuon** [comment]
> > 什么意思，我现在没有指定“/"，可以正常工作呀，创建直接就在默认笔记本的第一级别了，我只是指定了下笔记本
> 
> 你可以在这个笔记本里的文档内按 `Ctrl+N` 新建文档，不以 `/` 开头会在该文档下创建子文档
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/325842604-e0c9fda3-f8b1-44d6-8dd3-64b642ffafae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDU0MDAsIm5iZiI6MTcxNDEwNTEwMCwicGF0aCI6Ii83ODQzNDgyNy8zMjU4NDI2MDQtZTBjOWZkYTMtZjhiMS00NGQ2LThkZDMtNjRiNjQyZmZhZmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA0MTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWIwZTJlNjVjNWJiNDBjMDAzMTFhODM1OTc4Zjg5MTgzNGJkZmM2MTRlYzMwMmVkMDc1MTI0MTNiZjRhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1Rmlj2GrxDSly4sYKYBPshsO7Czp4HiG7IXyoSZVqPQ)

嗯，确实。。不想出现untitle主要是因为有点不舒服是吧，尽管效率上是一样的。我全局设置没加“/”，收集箱笔记本加了“/"，这样只有在收集箱中新建笔记才会出现untitle，好一丢丢

**Comment by TCOTC** [comment]
> 全局设置没加“/”，收集箱笔记本加了“/"，这样只有在收集箱中新建笔记才会出现 Untitled

是个不错的思路
