### ISSUE TITLE
In Dataview mirroring, allow each database mirror to have its specific unique views

### ISSUE THREAD

**Issue by alexjp** [siyuan-note/siyuan#10675]
### In what scenarios do you need this feature?

Hi,
First of all, thank you very much for SiYuan and version 3 with databases!

I would like to have a "tasks" database, in which I would mirror the database to other pages.

Each page would have its specific views, like for "Today", "Inbox of ideas" (kinda like GetThingsDone), tasks with specific filters, etc

### Describe the optimal solution

The optimal solution for my case, would be to have a "Main Task" Database, with a view for all tasks.

Then in specific "Dashboard pages" and other pages, I would have that tasks database mirrored, but with very specific filters.

### Describe the candidate solution

How it currently works, but allowing to hide views in database mirroring.

### Other information

I am kinda new to SiYuan, so I apologize in advance if I am requesting does not make sense!

**Comment by 5kyfkr** [comment]
This function has been implemented. You only need to create table views with different filters in the database, then copy the database ctrl+c to other documents, and then select the view you need to display in that document. That view will remain as long as you do not switch manually. It is fixed there. Of course, copying the same database view to the same page and then switching the view will also save the corresponding switching position.

**Comment by alexjp** [comment]
> This function has been implemented. You only need to create table views with different filters in the database, then copy the database ctrl+c to other documents, and then select the view you need to display in that document. That view will remain as long as you do not switch manually. It is fixed there. Of course, copying the same database view to the same page and then switching the view will also save the corresponding switching position.

Yes, the database view does that, and would be a good workaround. The issue, is that for example for tasks, I would have many `database mirrors`. I would like, at least my current pattern, is to have things like `today`, `yesterday`, `tomorrow`, `inbox`, `next`, etc. And then in those, have some specific like `inbox` but with filter for clientA, and etc.

Maybe this pattern is wrong for SiYuan. I will try to find another way of doing things. In the meanwhile, I will have to wait, because views are not autofilling if there isn't a previous record. (ex: I mean... if I have a view with a filter of `today` and I already have a row of today already in the view, it will add a new one with the `schedule` of today. If I don't have any row in the view, it won't work, it will not add any new row. I am thinking this is bug https://github.com/siyuan-note/siyuan/issues/10659)

**Comment by 88250** [comment]
Hello, if you drag and drop a block into a view with a filter or create a row directly in the database view, the default value will be filled in according to the current view filter, so that after adding the data, you can see it in the current filtered view.

However, if you use the `Add to Database` of the block menu, no value will be populated because the specific view that needs to be added cannot be determined at this time. This may be improved in the future, please pay attention to #10659.

I have closed the issue. If you still have any questions, please feel free to post. Thank you.

**Comment by 88250** [comment]
Please pay attention to https://github.com/siyuan-note/siyuan/issues/10734 for subsequent progress.

**Comment by alexjp** [comment]
> Please pay attention to #10734 for subsequent progress.

Thanks for the feedback :) I have subscribed to that issue.
