### ISSUE TITLE
导图层级和显示逻辑优化

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1067]
### 描述问题 Describe the problem

这是思源的官方帮助文档，这个场景是高频场景
MD中 层级逻辑 映射到 导图 不一致

![image](https://user-images.githubusercontent.com/46141646/104669287-be622e80-5714-11eb-9827-6a95e3e0d991.jpg)

如图，**两个项子列表项 明显是 属于 段落“……。监听端口：”的**
我们从 MD 和 冒号的语义 都能看得出来
**但是显示在导图中 两个列表项和 “……。监听端口：” 属于同一个层级**

### 期待的结果 Expected result

**导图中 两个子列表项，显示为 “……。监听端口：” 的子主题**

目前 在普通段落 shift enter 然后写列表  和 直接enter写列表 **完全没有区别**
我们可以在这个地方做出这个区别：
shift enter 比 enter 少空一行，shift enter 的表项都是属于上方的普通段落的
否者和上方的普通段落属于同一级

shift enter 在列表中可以做到无限层级，但是父级是普通段落时候 shift enter就失效了
我们可以把父级也作为 一个 表项，但是这对用户的MD编辑是一种破环
因为太多 这样 我们写一句话，然后用一个列表进行解释的场景了

### 补充 Expected result

冗余结点也是一个问题，期待解决
![image](https://user-images.githubusercontent.com/46141646/104670351-a25f8c80-5716-11eb-9b9d-63b93ce9e30f.png)

对于用户视角而言这个结点 **完全是冗余 甚至 有误的**，目前的显示逻辑充斥着大量这种冗余结点
我目前想到的是 **直接在显示上去掉冗余结点的层级**
**然后显示各个表项时候显示为和MD一致的 点号 或 数字 的前缀**
这样和MD可达到高度的一致

### 版本环境 Version environment

* 版本 Version：0.6
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，这些节点不是冗余节点，如果没有这些节点的话层级逻辑不对，感谢讨论。
