### ISSUE TITLE
加粗文本搜索不出来

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/62794181/0ebea8ff-77ba-4e68-a55b-7be13bcfbc65)
在图片里可以看到，搜索出来的第一项是被箭头指着的那一个，但前面那个加粗的文本却不在搜索出来的列表当中
![image](https://github.com/siyuan-note/siyuan/assets/62794181/0ff8c96b-4f22-41d5-8faf-52e6998da7f4)
这是搜索选的类型

### Expected result

希望能够搜索出来

### Version environment

```markdown
- Version: 3.04
- Operating System: WIN11
- Browser (if used):
```

### Log file

nothing

**Comment by 88250** [comment]
应该在的，只是标题权重较高所以排在前面了，你找一下下面命中的段落块。

**Comment by QQQOrange** [comment]
> 应该在的，只是标题权重较高所以排在前面了，你找一下下面命中的段落块。

可以这样吗？

同时，高亮所有搜索的文本同时按顺序来显示。

这样的一个逻辑就和浏览器页面搜索的逻辑一样的。

**Comment by 88250** [comment]
不支持的，基本逻辑就是按块搜索的。

**Comment by QQQOrange** [comment]
> 不支持的，基本逻辑就是按块搜索的。

好吧
