### ISSUE TITLE
优化数据库表格视图下拉填充交互

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10685]
### In what scenarios do you need this feature?

[希望数据库支持剪切板中的内容按相应的分割粘贴进对应的列中，下拉填充交互优化 - 链滴](https://ld246.com/article/1710994328668) 第二点

目前的下拉填充点正常人很难触发操作，需要在单元格横向滑动一下才出来。建议优化为更直观的取消编辑聚焦后就出现。

### Describe the optimal solution

操作步骤如下：

1.单击单元格编辑

2.单击单元格外的其他区域，取消这个编辑，但框选还在单元格内，此时要出现下拉填充的圆点。

理想的操作：

![其他产品操作-bd44GrC](https://github.com/siyuan-note/siyuan/assets/78434827/d8dea7f6-7d88-4a82-872d-08bdbaf0540a)

实际思源的操作：

![思源操作-h3ByfI3](https://github.com/siyuan-note/siyuan/assets/78434827/e121486c-8621-4e00-ac08-98f023872beb)

**Comment by TCOTC** [comment]
@mozhux

**Comment by mozhux** [comment]
试了下新版，交互可以了，但是UI上，那个⭕️可能在的位置不太对吧？一般是在单元格的交界，如图所示
![image](https://github.com/siyuan-note/siyuan/assets/46953371/c8a4fb24-f76b-4e84-b0c2-f67475e0561e)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/96056ed2-2bd8-41d2-8f75-598422d634da)

**Comment by Vanessa219** [comment]
这个受限于 dom 结构，怕改出其他 bug 。弄成实心的会不会好一点
<img width="271" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/01134a88-4e9c-4cd0-afb9-4a4e8c978428">

**Comment by TCOTC** [comment]
实心好点，不过颜色还是再淡点吧

**Comment by mozhux** [comment]
> 这个受限于 dom 结构，怕改出其他 bug 。弄成实心的会不会好一点 <img alt="image" width="271" src="https://private-user-images.githubusercontent.com/970828/316282260-01134a88-4e9c-4cd0-afb9-4a4e8c978428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTk4MDUsIm5iZiI6MTcxMTI1OTUwNSwicGF0aCI6Ii85NzA4MjgvMzE2MjgyMjYwLTAxMTM0YTg4LTRlOWMtNGNkMC1hZmI5LTRhNGU4Yzk3ODQyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQwNTUxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjAwOGI4ODdhN2Y4ODg4YzJhNTk2ZmRhYzkwY2M5MTI2Mjg2YWM3Mjg3MzliODk3Njk0ZWRhYmM1MmQ4MzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EKTiR8MRQc-Nlm9dBRAQGVxjuspX-Jh5HjcQPjt2YlY">

改不了的话就默认现在的就行

**Comment by Vanessa219** [comment]
那就先这样吧。
