### ISSUE TITLE
siyuan docker 无法登录账号/集市插件无法加载

### ISSUE THREAD

**Issue by licsvip** [siyuan-note/siyuan#10683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

siyuan docker 当前最新镜像，无法登录账号/集市插件无法加载，日志提示： rhy.go:42: get version meta info failed: [unexpected end of JSON input]  ，更换为V3.0.4无此问题
![siyuan_log](https://github.com/siyuan-note/siyuan/assets/68700973/40ea1fa7-1eaa-41c1-bd95-1611522fb5b5)

### Expected result

更换为V3.0.4版本无此问题

### Version environment

```markdown
- Version: latest
- Operating System: docker
- Browser (if used): edge
```

### Log file

![siyuan_log](https://github.com/siyuan-note/siyuan/assets/68700973/2caa3df3-637c-41d6-ae63-75bfa79c078e)

**Comment by 88250** [comment]
建议检查容器所在网络，目前思源云端服务正常。
