### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by Hualoong** [siyuan-note/siyuan#10681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在表格中输入任何内容表头会出现{: class="fr-fix-xxxxx"}

删除所有主题、插件、挂件等问题依旧；
删除Docker容器后重新创建容器，问题依旧。

![QQ截图20240321132410](https://github.com/siyuan-note/siyuan/assets/863450/25b2ca6f-040d-4303-a416-95a46aff779c)

### Expected result

在表格中输入任何内容表头内容不会变化

### Version environment

```markdown
- Version: v3.0.3
- Operating System: Debian 12 / Docker version 25.0.3, build 4debf41
- Browser (if used): Microsoft Edge 122.0.2365.9
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14686363/siyuan.log)

### More information

![QQ截图20240321132410](https://github.com/siyuan-note/siyuan/assets/863450/25b2ca6f-040d-4303-a416-95a46aff779c)

**Comment by Hualoong** [comment]
删除所有主题、插件、挂件等问题依旧；
删除Docker容器后重新创建容器，问题依旧。

**Comment by 88250** [comment]
建议检查是否是某些浏览器扩展导致。
