### ISSUE TITLE
Blockquote newline exception

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#10686]
引述块换行错误

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在视频中最后换行的时候光标跳到上面，此时如果撤销可能报错
https://github.com/siyuan-note/siyuan/assets/97731736/0fe2d70f-a8e9-4bf5-b7ea-e39cdafdbd8c

### Expected result

正确换行

### Screenshot or screen recording presentation

1

### Version environment

```markdown
- Version: 3.0.5-dev1 版

- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by TCOTC** [comment]
可以复现

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c9eb9f4e-383b-4b24-86b3-2db4b0e521a8)

**Comment by Vanessa219** [comment]
由于 https://github.com/siyuan-note/siyuan/issues/10653 修改而导致的错误
