### ISSUE TITLE
无法把标签替换为引用块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

最近在研究 daily notes ，因为 [某篇文章](https://www.yuque.com/deerain/gannbs/ffqk2e) 上说在文档型笔记软件里使用 daily notes 不适合用标签，所以突发奇想，如果能把标签批量替换为某个块的引用块，就能实现先无压记录、之后有空再关联到主题文档。

但是发现好像不能把标签批量替换为某个块的引用块：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e0f6f7f4-1d8f-4e71-9f8b-553d8b5b4f60)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e043f017-076a-42f7-8f37-1705ea851d68)

[无法把标签替换为块引用 - 链滴](https://ld246.com/article/1710949535103)

### Expected result

允许把标签替换为引用块

### Version environment

```markdown
- Version: v3.0.5-dev2
- Operating System: Windows 10
```

### Log file

无

### More information

不排除是我操作的问题，但没人帮我复现，只能创建一个 issue 了

**Comment by 88250** [comment]
思源的编辑器不是文本编辑器，所以不支持语法替换，仅支持替换内容。

**Comment by TCOTC** [comment]
@88250 我又研究了一下，无法把标签替换为任何内容

**Comment by 88250** [comment]
我这里正常的，发一下测试数据我导入试试。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年3月22日(周五) 下午2:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 无法把标签替换为引用块 (Issue #10689)




 
@88250 我又研究了一下，无法把标签替换为任何内容

**Comment by TCOTC** [comment]
[替换标签.sy.zip](https://github.com/siyuan-note/siyuan/files/14719727/sy.zip)

以下是我的操作：

https://github.com/siyuan-note/siyuan/assets/78434827/89157869-a280-4ba3-84f3-19d45c4f51b5

**Comment by 88250** [comment]
搜索内容不要带 `#`，这样才能替换到标签内容。

**Comment by TCOTC** [comment]
原来如此。麻烦 D 大再帮我看看这个锚文本为什么替换不了（感觉只是重载了一下界面）：

[替换链接.sy.zip](https://github.com/siyuan-note/siyuan/files/14720774/sy.zip)

https://github.com/siyuan-note/siyuan/assets/78434827/51c7b961-ba97-4136-a4e8-e60b21c456d9

**Comment by 88250** [comment]
无法替换超链接锚文本是个 bug，稍后修复，感谢反馈。
