### ISSUE TITLE
Feature | 在属性编辑器窗口中加入 "style" 属性

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#10684]
### In what scenarios do you need this feature?

目前块的 style 属性似乎是完全不对用户开放的，只能通过调用 API 来设置，感觉有点浪费。

### Describe the optimal solution

建议在备注下面在加一个编辑框，允许用户编辑块的内联样式。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/5ed11bd4-636e-4cbf-93b1-db2b33e9ae26)

**Comment by 88250** [comment]
这个暂时不考虑了，手工编辑有损坏的风险。
