### ISSUE TITLE
Enhance Database Document Entries

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10687]
### In what scenarios do you need this feature?

To make using SiYuan easier and more efficient, I suggest two main improvements. These changes will help users work with database documents directly from the main interface and manage a large number of database documents more easily.

### Describe the optimal solution

1. **Modal Popups for Database Entries:** Implement modal popups similar to Notion's user interface when users click on a database entry or doc. This feature should:
   - Open the content in a centered modal overlay within the same window, allowing users to view or edit details without opening a new window directly.
   - Include an option within the modal to "Open in Full Screen" or "Open in New Tab" for more detailed editing, providing flexibility based on user preference.

2. **Streamlined Doc Tree Management:** Adopt a document management approach similar to Notion and Anytype, where pages created within a database table do not appear in the main document tree. This will:
   - Keep the document tree uncluttered, especially with databases that contain a large number of entries, for example, let's say over 500+ docs.

### Describe the candidate solution

I've attached sample videos from both Notion and Anytype for reference.

Notion:

https://github.com/siyuan-note/siyuan/assets/36538038/7a9d23c5-5915-4279-8bee-b12fa41797c7

Anytype:

https://github.com/siyuan-note/siyuan/assets/36538038/5ac5b331-f0df-4a4d-a7d2-c6e59509014b

### Other information

**Additional Suggestion:**
- Show attributes and properties of docs in database tables when viewed in a modal or full screen, similar to how Notion does it.

![Notion_zH3LAJkbdV](https://github.com/siyuan-note/siyuan/assets/36538038/a760ecc8-24d6-42fb-bab6-fa005b5a7e39)

**Why it matters:**
- These improvements are crucial for making SiYuan more user-friendly and competitive with apps like Notion and Anytype. They aim to simplify how users interact with and manage their documents, enhancing their overall experience.

**Special Request:**
- Please consider this request seriously. Implementing these features is very important for improving SiYuan and making it a better tool for users.

**Comment by 88250** [comment]
SiYuan is not organized by Page, but by Block, and the database supports unbound Blocks (that is, ordinary row additions), so:

1. Only the row bound to a Block can open a new editor (you can open a new window through a floating window, or open a new tab through the floating window breadcrumb)
2. SiYuan supports placing a block in multiple databases, so there is no parent-child relationship between the bound row blocks and the database, and there is no relationship between sub-document trees.

This is the difference in design between SiYuan and other Notion-like products. We think this is more flexible, thank you.

**Comment by MrIntellectX** [comment]
Okay, I understand, but I think it would be better if, for instance, I just want to quickly update the content of 'Testing' in this example. If I press Ctrl + hold, it shows me a floating window, which isn't quite useful specifically in this case. I have to resize it and center it before I can easily write. That's what I was saying: it would be great if, by default, when someone clicks on a doc in the database table, it should open like in Notion. This is actually what I meant. Moreover, if users want to open it in a new window or fullscreen, like we have the option already in this floating window at the top right, the user simply clicks on it. I would greatly appreciate it if you could enhance this experience.

Video for reference:
 
https://github.com/siyuan-note/siyuan/assets/36538038/7c156e19-7415-419a-80dc-2d51962d2b79



Lastly, I know there is definitely a difference between SiYuan and others, but isn't there a way that I can show attributes and properties in that 'Testing' doc? This is only for docs that I'm creating inside the database table. Like this... 

![image](https://github.com/siyuan-note/siyuan/assets/36538038/320b908d-d3fa-4f9c-8852-3936295095e0)

**Comment by MrIntellectX** [comment]
Please consider this request if possible. Thank you.

**Comment by 88250** [comment]
Hello, please watch the screen recording demo:

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/1d9c8cb7-671e-49e0-bb70-453e7ddac2d3)

**Comment by MrIntellectX** [comment]
I really appreciate that screen recording. I totally get what you are trying to say.

Pardon me if I was not able to explain clearly before.

What I'm trying to say, as you can see in the video below, is that when we click on a doc block, by default it is opening in a new tab. This is just for user experience enhancement, the default behavior should be a centered floating window.

https://github.com/siyuan-note/siyuan/assets/36538038/9ca4db2d-58a8-49df-a156-60a9b7b0fdaa

In this video, you can see that when I hover over a doc block, it opens a floating window at the center with better height and width. I used a custom CSS snippet, but it's not a great fix and not an efficient way to use. Also, the doc block floating window should display a banner and an icon if doc has.

https://github.com/siyuan-note/siyuan/assets/36538038/a5dedc6e-586e-4931-9fb2-1a763e5b232e

**Comment by 88250** [comment]
The default behavior when clicking the primary key of the binding block is to jump. As mentioned above, if you need to open a new tab, you need to use Alt/Shift. This is a default rule in SiYuan, including references and breadcrumb clicks.

There is currently no good tech implementation for calculating the size of floating windows because the height is difficult to calculate. @Vanessa219 will think of a solution later.

Thanks.

**Comment by MrIntellectX** [comment]
Got it, appreciate that.
