### ISSUE TITLE
启用插件后「快捷键」界面空白无法显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

安装了 [v3.0.5-dev1](https://github.com/siyuan-note/siyuan/releases/tag/v3.0.5-dev1) ，发现「快捷键」界面与集成编辑环境插件冲突，无法显示。

只要打开这两个选项的其中一个：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3a1fc754-3db0-40d1-a21e-8863dec0f604)

就会导致「快捷键」界面一片空白：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/caa6ea74-f2f9-470b-bd79-dbcdf39547fa)

同时控制台会产生一条报错：

```
main.f60697176fa84716dbb1.js:9 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at J (main.f60697176fa84716dbb1.js:9:4468)
    at main.f60697176fa84716dbb1.js:4682:122
    at Array.forEach (<anonymous>)
    at main.f60697176fa84716dbb1.js:4682:34
    at Array.forEach (<anonymous>)
    at Object.genHTML (main.f60697176fa84716dbb1.js:4672:54)
    at iw (main.f60697176fa84716dbb1.js:6211:1368)
    at HTMLLIElement.<anonymous> (main.f60697176fa84716dbb1.js:6250:727)
J @ main.f60697176fa84716dbb1.js:9
（匿名） @ main.f60697176fa84716dbb1.js:4682
（匿名） @ main.f60697176fa84716dbb1.js:4682
genHTML @ main.f60697176fa84716dbb1.js:4672
iw @ main.f60697176fa84716dbb1.js:6211
（匿名） @ main.f60697176fa84716dbb1.js:6250
```

### Expected result

正常显示「快捷键」界面

### Screenshot or screen recording presentation

是从 v3.0.5-dev1 开始才出现这个问题的，不确定是思源还是插件的问题

### Version environment

```markdown
- Version: v3.0.5-dev1
- Operating System: Windows 10
```

### Log file

无

**Comment by TCOTC** [comment]
https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/issues/28

**Comment by TCOTC** [comment]
整个过程的视频演示（有点卡，见谅）：

https://github.com/siyuan-note/siyuan/assets/78434827/e8b26a7d-509c-4864-9580-da36347f3c66

**Comment by TCOTC** [comment]
现在我把集成编辑环境插件关了也还有这个问题，用二分法排查插件也没有发现是哪个插件的问题，只有一键关闭所有插件才能显示「快捷键」界面，而新建的工作空间又一切正常，我定位不了问题是怎么产生的。

回退到 v3.0.4 ，一切正常；升级到 v3.0.5-dev2 ，问题又重现了。

**Comment by TCOTC** [comment]
我导出了最精简的能复现问题的 Data (8MB)，希望 @88250 看看能不能定位到问题。

[新的工作空间-20240322053811.zip](https://github.com/siyuan-note/siyuan/files/14711464/-20240322053811.zip)

我的复现流程：

1. 安装 v3.0.5-dev2
2. 打开一个已有的工作空间（不要关）
3. 新建工作空间
4. 设置 > 导出 > 导入Data
5. 设置 > 集市 > 信任、开启插件
6. 关闭工作空间
7. 从已打开的工作空间重新打开刚才新建的工作空间
8. 打开设置 > 快捷键 ，此时界面空白无法显示

**Comment by 88250** [comment]
@Vanessa219 我这里可以重现。

**Comment by Vanessa219** [comment]
由于 https://github.com/siyuan-note/siyuan/issues/10603 导致，就不记录到版本中了。

**Comment by TCOTC** [comment]
这个问题又复现了（但我没试过老版本有没有这个问题）：

1. 下载 Data.zip：[工作空间Data.zip](https://github.com/siyuan-note/siyuan/files/14815079/Data.zip)
2. 安装 [v3.0.6-dev3](https://github.com/siyuan-note/siyuan/releases/tag/v3.0.6-dev3)
3. 打开一个已有的工作空间（不要关）
4. 新建工作空间
5. 设置 > 导出 > 导入Data
6. 设置 > 集市 > 信任
7. 在开启插件的情况下关闭所有插件：
![image](https://github.com/siyuan-note/siyuan/assets/78434827/8857fa61-8e05-449d-8317-99ac937183c0)
8. 在 集市 > 主题 找到 Savor 主题，下载
9. 设置 > 外观 > 主题 ，设置「暗黑模式下使用主题」为 Savor ，设置「明亮模式下使用主题」为 daylight
10. 关闭工作空间
11. 从已打开的工作空间重新打开刚才新建的工作空间
12. 打开集市，开启所有插件
13. 设置 > 外观 > 主题 ，设置「明亮模式下使用主题」为 Savor
14. 打开设置 > 快捷键 ，此时界面空白无法显示

https://github.com/siyuan-note/siyuan/assets/78434827/d9d6a551-35d8-49bc-a35c-13e0bfe119a7

**Comment by 88250** [comment]
@Vanessa219 我这里按照上述步骤可以重现：

![image](https://github.com/siyuan-note/siyuan/assets/873584/4e6c971b-dabf-4349-a0d2-35bb32bebeb7)
