### ISSUE TITLE
快捷搜索并链接块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10688]
### In what scenarios do you need this feature?

最近在尝试使用 daily notes ，有个要点是尽量避免在文档中滥用块引，否则会污染反链。所以在没有必要的情况下都使用普通的链接。

目前选中文本后可以按 `Alt + [` 引用，快捷搜索并引用块。但因为没有快捷搜索并链接块的功能，所以只能先引用块，再右键点击引用转换为链接，操作非常繁琐。

![image](https://github.com/siyuan-note/siyuan/assets/78434827/234a5a18-5233-42c3-84e2-aa46787fbd1d)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5ce42f3f-04f6-455b-bbb1-613dbbff5858)

[需要一个快速链接其他 文档 / 块 的功能 - 链滴](https://ld246.com/article/1710947961241)

### Describe the optimal solution

实现快捷搜索并链接块。想要跟 `Alt + [` 引用 一样的交互，快捷键可以使用 `Alt + K` ：

![引用](https://github.com/siyuan-note/siyuan/assets/78434827/0d73b646-e00d-4411-b7ab-87de959aa3a4)

**Comment by 88250** [comment]
块超链接不考虑搜索了，谢谢。

**Comment by TCOTC** [comment]
这个不好做吗？

**Comment by 88250** [comment]
设计上不考虑超链接支持搜索。
