### ISSUE TITLE
 Support pasting Excel into database table view

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10695]
https://ld246.com/article/1710994328668
支持 excel 粘贴到数据库

**Comment by mozhux** [comment]
V大好，这个其实不只是excel, 一般来讲网络上复制表格应该都行，比如直接从别的数据表格如wolai、notion、flowus复制过来的

**Comment by 88250** [comment]
已经是按 HTML Table 转换实现的了。

**Comment by mozhux** [comment]
我体验了一下测试版，基本支持了粘贴，但是有个问题很影响体验，就是如果复制的数据有空的列，比如这样的
![image](https://github.com/siyuan-note/siyuan/assets/46953371/24a37b30-c7bf-48a7-95f2-4b2711b47b62)
复制到思源，对于空列会跳过，变成下一行的，导致格式错乱
![image](https://github.com/siyuan-note/siyuan/assets/46953371/432c7313-f878-4d1f-90bd-b253fa401435)
wolai等其他产品的就是正常的，空列就不管，希望可以再改进一下。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/554fe06a-85fe-4edb-bbaf-85e5d4ab5897)

**Comment by Vanessa219** [comment]
感谢反馈，稍后再试试。

**Comment by Vanessa219** [comment]
感谢反馈，稍后再试试。
