### ISSUE TITLE
增强关系图graph: 使支持显示当前笔记的所有关联笔记，包括间接关联

### ISSUE THREAD

**Issue by realysy** [siyuan-note/siyuan#10699]
### In what scenarios do you need this feature?

需要的功能如题，如果有这个功能，将有助于用户对笔记之间的关联有更全面、深入的认识。

 * 在关系图`Alt+8`中只能显示与当前笔记直接关联的笔记，而这些关联笔记进一步关联的其它笔记（间接关联的笔记）无法显示；

 * 在全局关系图`Alt+9`中无法快速定位到当前笔记的位置，使用关系图的`搜索`只能显示当前节点，无法显示节点的关联节点；

### Describe the optimal solution

所以期望的最佳实现是：在关系图`Alt+8`中，同时显示当前笔记的直接关联笔记 & 间接关联笔记

### Describe the candidate solution

在全局关系图`Alt+9`的上方，添加一个类似聚焦的按钮，点击后能定位到当前笔记，这样在笔记关联不太多的情况下也能看清当前笔记的所有关联笔记。

### Other information

Win10
v3.0.4

**Comment by zxhd863943427** [comment]
看看关系图增强插件

**Comment by 88250** [comment]
关系图不考虑改进了，抱歉。

**Comment by realysy** [comment]
> 看看关系图增强插件

@zxhd863943427 谢谢，这个插件正是我需要的
