### ISSUE TITLE
Database table view primary key supports pasting reference block

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10690]
### In what scenarios do you need this feature?

如果搜索支持识别包含块ID的引用块、超链接，就不需要删去ID前后的文本了。

目前可以用 ID 搜索到对应的块：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3a1a4f15-5a2a-412a-bb48-b0d1d999073f)

但用包含块ID的引用块、超链接就无法搜索了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4c9565f7-9200-4424-be55-df684e7d2238)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/03a2d8dd-c743-4cf4-9c70-9fce9c23b42f)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8285d984-246f-419a-94be-b1ea67eb4421)

[希望数据库能识别引用块 - 链滴](https://ld246.com/article/1711013008506)

### Describe the optimal solution

希望这几种方式都能搜索到对应ID的块

**Comment by 88250** [comment]
复制引用块应该可以考虑，其他几种复制不考虑了 @Vanessa219

**Comment by TCOTC** [comment]
其他几种不能顺便做吗？

**Comment by 88250** [comment]
@Vanessa219 有空时评估一下

**Comment by Vanessa219** [comment]
这个和引用是一致的，如果使用其他就不进行解析了。

**Comment by TCOTC** [comment]
所以现在是只增加支持了第一种吗：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cf2c3cf9-8d1f-4765-a8c3-5432b0a6ca4b)

**Comment by Vanessa219** [comment]
只有这个在段落块中粘贴会被识别为饮用，其余的为链接和文本。因此数据库里面保持一致。链接和文本就不进行识别，以免用户只是想粘贴内容而不是引用。
```
((20200812220555-lj3enxa '请从这里开始'))
```

**Comment by TCOTC** [comment]
总感觉跟预期有点不一样，粘贴在上面还是不能搜索到

![image](https://github.com/siyuan-note/siyuan/assets/78434827/38a1ac62-57ff-4d85-a58d-72a15899f900)

**Comment by TCOTC** [comment]
> 总感觉跟预期有点不一样，粘贴在上面还是不能搜索到

我原本想要的是「搜索支持识别包含块ID的引用块、超链接，不需要删去块 ID 前后的文本」

**Comment by Vanessa219** [comment]
呃，以为是粘贴的时候可以直接粘贴为引用。搜索的话 @88250 看能不能处理一下？

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/10848
