### ISSUE TITLE
在超级块内回车，自动组成垂直布局向下创建块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10696]
在水平布局的超级块内回车，应在下方创建块，自动组成垂直布局

### In what scenarios do you need this feature?

[notion 一样的个人主页设置 - Soon1y 的回帖 - 链滴](https://ld246.com/article/1706516766994/comment/1711071319954#comments)

视频中用户的目的是在段落块「分栏1」的下方创建内容，但结果是创建新的分栏，比较反直觉：

https://github.com/siyuan-note/siyuan/assets/78434827/ce706893-ac9e-4b80-8e62-044b6591df48

### Describe the optimal solution

我在用的 飞书 和 FlowUs 都是这样的逻辑：

![飞书](https://github.com/siyuan-note/siyuan/assets/78434827/50c91c40-ce6e-4ece-aa9e-0321ea6e068c)

![FlowUs](https://github.com/siyuan-note/siyuan/assets/78434827/97f5fc57-582f-446d-a9f8-01dddda9dd12)

**Comment by Vanessa219** [comment]
是有一点奇怪。但如果此时竖向添加的话，会把这个块再用一个垂直布局的超级块包裹起来。这样就会导致默认改变了块的结构，也有点不太好。

**Comment by TCOTC** [comment]
如果用户要往下添加内容，就必然需要组合一个垂直布局的超级块，所以把这个操作自动化更好

**Comment by Vanessa219** [comment]
那要横着填咋办？

**Comment by TCOTC** [comment]
1. 先填好所有横着的，再转为水平布局超级块
2. 额外加上的块，手动拖进去就可以了

**Comment by Vanessa219** [comment]
再看看其他用户反馈吧。这个以前说明过，可能大家都适应了。

**Comment by TCOTC** [comment]
至少新用户肯定不会适应，时不时会有人在链滴上问分栏之后怎么往下插入块。

我去链滴发个投票看看

**Comment by zxhd863943427** [comment]
我觉得最简单的操作应该最符合第一印象的感觉，这个操作是符合认知的，之前的操作是符合思源逻辑但别扭的。

**Comment by UFDXD** [comment]
改了之后想要横着增加就要解除超级块然后再增加吧，那么最大的那个超级快引用失效怎么办。而且垂直增加里面拖两个段落快就可以一直回车增加了，我个人觉得没必要该，改了之后有引用失效的问题

**Comment by UFDXD** [comment]
用视频验证现在的逻辑使用完全没问题也没有不方便的地方
https://github.com/siyuan-note/siyuan/assets/97731736/ade7aba7-0435-4b6a-b012-ce460389fdab

**Comment by UFDXD** [comment]
还不如将精力花在其他改进方面

**Comment by TCOTC** [comment]
> 视频中现在的逻辑使用完全没问题 https://github.com/siyuan-note/siyuan/assets/97731736/ade7aba7-0435-4b6a-b012-ce460389fdab

但对很多用户会造成困扰，因为大家都习惯回车之后新增下一行

**Comment by TCOTC** [comment]
而且现在的分栏已经很方便了，但是在下方插入一个块却是每个分栏都要靠拖动。

新增分栏：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dae495ea-2bf8-4091-a87b-de4e81576baa)

**Comment by TCOTC** [comment]
@Vanessa219 下面是 [更简单的分栏！来投票吧 - 链滴](https://ld246.com/article/1711344299333) 截至目前的投票：

绝大多数投票的用户是支持改进这个逻辑的

<img width="1521" height="536" alt="Image" src="https://github.com/user-attachments/assets/188a2bf2-21d5-4d59-8811-6b67f0b88829" />

> 再看看其他用户反馈吧。这个以前说明过，可能大家都适应了。

看起来老用户也不想适应~

**Comment by TCOTC** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/1ab40e63-d4db-479d-bebd-6ed000ac8391)

**Comment by TCOTC** [comment]
Notion 分栏之后也是按 Enter 向下创建块，我觉得思源的超级块交互需要跟其他软件更接近才行

**Comment by TCOTC** [comment]
https://ld246.com/article/1717240455713

**Comment by Lethe20** [comment]
我也曾被这个问题困扰过。希望思源笔记能够更符号用户的习惯操作，让软件来适应用户的直观、普遍的操作习惯，而不是困扰用户一段时间，让用户去在这段时间内去寻找解决办法或慢慢适应以符合软件的逻辑。

**Comment by TCOTC** [comment]
@88250 这个得考虑改一改了，只要是新用户都很不适应

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2740abd1-f5a8-49f3-a7e5-05d2855d96d7)

**Comment by 88250** [comment]
@Vanessa219



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年6月28日(周五) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 在超级块内回车，自动组成垂直布局向下创建块 (Issue #10696)




 
@88250 这个得考虑改一改了，只要是新用户都很不适应
 
image.png (view on web)

**Comment by TCOTC** [comment]
https://ld246.com/article/1721972371666

**Comment by TCOTC** [comment]
https://ld246.com/article/1724295803305
