### ISSUE TITLE
文档制卡，间隔重复界面显示文档标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10693]
### In what scenarios do you need this feature?

打算通过把文档加入间隔重复，每次看到就多写一点内容。但是发现不显示文档标题

### Describe the optimal solution

显示文档标题

**Comment by 88250** [comment]
文档标题在面包屑上可以看到。

**Comment by TCOTC** [comment]
看面包屑太麻烦了，我觉得真不如直接在上面显示标题。

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6dfdf674-c576-49c0-b3d8-2c64ee680d67)

**Comment by 88250** [comment]
@Vanessa219 你考虑一下吧。

**Comment by TCOTC** [comment]
@Vanessa219 在页签看的时候感觉更奇怪了，我觉得还是显示标题更方便

![image](https://github.com/siyuan-note/siyuan/assets/78434827/badc7912-9190-48f6-86e1-cab7af858cb7)

**Comment by Vanessa219** [comment]
显示标题的话，需要考虑标题进行修改或删除时对应的更新，如果标题有图标的话，就会出现2个图标。

**Comment by TCOTC** [comment]
好吧，听起来不是很容易实现，那我就适应一下好了，手动把标题复制到第一行

**Comment by Vanessa219** [comment]
这里很清晰呀，还有路径

<img width="273" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/97cb9c83-6738-4d56-833c-30961d68a76f">

**Comment by TCOTC** [comment]
在面包屑上，路径对标题的干扰比较严重（尤其是路径很长的时候，标题甚至会被顶到后面不显示）：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a05b36d6-55b0-44c2-a574-98461a52f078)

所以会希望能像编辑器那样直接显示标题

**Comment by Vanessa219** [comment]
路径好长。如果路径短的就左上角可能就会比较重复。
