### ISSUE TITLE
嵌入文档(内容块)指定渲染模式, 如脑图

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#1069]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

在一个大的文档中, 为了让文档看起来更有逻辑性, 文档中部分内容块使用脑图,其他地方依然是即时渲染.

### 描述最优的解决方案 Describe the optimal solution

再嵌入文档时可以定义嵌入文档的渲染模式, 比如脑图

### 描述候选解决方案 Describe the candidate solution

当一个文档渲染模式为脑图时, 嵌入后显示为脑图. 当为即时渲染时, 嵌入后显示为即时渲染.
嵌入后的文档如果不是即时渲染, 不能编辑只显示也是可以的. 用户可以通过打开文档进入编辑模式

### 其他信息 Other information

当有其他编辑模式时, 如流程. 那么嵌入后显示流程图.

**Comment by roverway** [comment]
补充一下，不知道是否可以新增特性：允许用户对于正常文档内容（非嵌入内容）的某个标题及其以下内容，切换正常显示模式或脑图模式（嵌入在文档中）。

**Comment by 88250** [comment]
混合模式暂时不考虑了……在文档即时渲染模式里有脑图语法，单独使用比较好。

后续如果有时间我们重开看看，谢谢。
