### ISSUE TITLE
Editor List Conversion Issue with Asterisk (*) and Plus (+) Symbols

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

In the editor, when typing an asterisk (*) followed by a space, or a plus (+) followed by a space, the text automatically converts into a bulleted list. This behavior is unexpected for these symbols, as traditionally, only the hyphen (-) followed by a space should trigger the creation of a bulleted list. This automatic conversion disrupts the intended formatting when using asterisks and plus signs for other purposes.

Video for reference:

https://github.com/siyuan-note/siyuan/assets/36538038/77d8bb3b-f044-4903-9480-e1883b9cae3a

### Expected result

Typing an asterisk (*) or a plus (+) followed by a space should not convert the text into a bulleted list. Only typing a hyphen (-) followed by a space should initiate the creation of a bulleted list, adhering to common markdown conventions.

### Version environment

```markdown
- Version: 3.0.4
- Operating System: Windows 11 Pro
- Browser (if used): -
```

### Log file

.

**Comment by 88250** [comment]
Hello, this is the syntax expectation of standard Markdown, please refer to https://spec.commonmark.org/0.31.2/#bullet-list-marker
