### ISSUE TITLE
自适应宽度模式关闭的情况下，希望可以编辑区域可以宽一点（或者可以能让用户设置宽度）

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#10701]
### In what scenarios do you need this feature?

很多人会关闭自适应宽度时，这样在不同的显示器上，有相近的编辑体验。
![image](https://github.com/siyuan-note/siyuan/assets/5683995/a7ed810c-1a0d-4a7e-b4aa-57efc40e2f2f)

但现在编辑宽度，略微有点窄，是否可以宽一点，尤其在以下场景时：
1. 左右显示两张对比图片时（这非常常用），可能两张并排的图片会显得有点小
    左右显示两个视频块，也是如此
3. 显示代码块时，可能需要来回滚动下面的滚动条（将其设置为自动换行，也不好看）
4. 等等其他情况

或者是否可以开放给用户设置

> 注：试过第三方插件（siyuan-center-width），有bug，而且是按照百分比的，会让不同设备的表现不一致

### Describe the optimal solution

希望官方给支持用户设置编辑区宽度

**Comment by 88250** [comment]
这个不考虑了，固定宽度的话可能有其他问题，请通过自定义 CSS 自行修改，感谢反馈。

**Comment by zhoutaosheng** [comment]
> 这个不考虑了，固定宽度的话可能有其他问题，请通过自定义 CSS 自行修改，感谢反馈。

@88250 窃以为，如果是对的事情，需求是正确、合理且普遍的，有问题，不应该是解决问题吗？
当然，如果需求不合理，当然就算了

**Comment by 88250** [comment]
会有其他问题，所以还是自定义吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月23日(周六) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 自适应宽度模式关闭的情况下，希望可以编辑区域可以宽一点（或者可以能让用户设置宽度） (Issue #10701)




  
这个不考虑了，固定宽度的话可能有其他问题，请通过自定义 CSS 自行修改，感谢反馈。
  
@88250 窃以为，如果是对的事情，需求是正确、合理且普遍的，有问题，不应该是解决问题吗？
 当然，如果需求不合理，当然就算了
