### ISSUE TITLE
拥有idea编辑器那样的多行编辑能力

### ISSUE THREAD

**Issue by lunzilunzi** [siyuan-note/siyuan#1070]
在idea下，
按住 alt + 鼠标左键按住滑动，能实现以下效果
![Peek 2021-01-15 10-15](https://user-images.githubusercontent.com/26265113/104672574-fd937e00-571a-11eb-8fcd-216a9df33f8a.gif)
按住 alt + shift + 鼠标左键点击，能实现以下效果
![Peek 2021-01-15 10-19](https://user-images.githubusercontent.com/26265113/104672702-40555600-571b-11eb-89df-7fdb9d51c560.gif)
基于这两种功能，可以实现一下两种操作，有时候批量记录数据时，也可以更方便的
![Peek 2021-01-15 10-10](https://user-images.githubusercontent.com/26265113/104672806-6ed33100-571b-11eb-8209-92f14b485f59.gif)
![Peek 2021-01-15 10-12](https://user-images.githubusercontent.com/26265113/104672812-72ff4e80-571b-11eb-8832-394b21e72a87.gif)

**Comment by 88250** [comment]
你好，即时渲染模式估计支持不了，专家模式应该能支持，请关注 #868 谢谢
