### ISSUE TITLE
用翻页键建议留一行文字距离衔接

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#10702]
### In what scenarios do you need this feature?

我用思源看小说，习惯用翻页键浏览，但是思源用键盘翻页经常刚好卡在文字中间，因为每次翻页都是翻一整页，没有留缓冲的高度，所以总会有一行字被截一半看不清字。
一般浏览器上翻页都会有大概两行的衔接，对比可以看这两个视频：
浏览器翻页示例：

https://github.com/siyuan-note/siyuan/assets/57566668/0276e1b6-ff1f-4774-8162-f1c9a39fe2b0

思源翻页示例：

https://github.com/siyuan-note/siyuan/assets/57566668/f8e1951f-4213-45fe-b279-a2a2cceaebe7

### Describe the optimal solution

用翻页键翻页时留一行以上文字高度的距离衔接

**Comment by TCOTC** [comment]
我觉得翻页占页面高度的 2/3 为宜

> 我去试了一下飞书，PgUp 和 PgDn 都是翻一页半，更离谱。

**Comment by QQQOrange** [comment]
对我也遇见了这样的问题，但我的想法竟然是换用滚动的方式，而不是用翻页来阅读。这方面，还是要向老哥学习，遇见问题要及时反馈，而不是将就

**Comment by gdy106** [comment]
> 我觉得翻页占页面高度的 2/3 为宜
> 
> > 我去试了一下飞书，PgUp 和 PgDn 都是翻一页半，更离谱。

翻一页半就完全是bug了吧！
但是三分之二对小屏幕太不友好了，13寸墨水屏的空间实在捉襟见肘。
我个人看法是文字缓冲一两行差不多够用，如果可以的话最好翻页时可以显示完整的图片。
