### ISSUE TITLE
0.6.0版本对于插入的文件，打开文件位置没有反应

### ISSUE THREAD

**Issue by lhx-JIPS** [siyuan-note/siyuan#1071]
### 描述问题 Describe the problem

使用0.6.0版本，对插入到笔记中的文件，右击选择【资源】→【打开文件位置】，没有反应，不像以前一样能打开文件所在的\assets文件夹。

### 期待的结果 Expected result

能正常打开文件所在的位置。

### 版本环境 Version environment

* 版本 Version：0.6.0
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，我们进行了一些修复，请等 v0.6.1 发布后帮忙回测验证，我先关闭了，如果回测还有问题请继续跟帖，谢谢。
