### ISSUE TITLE
无序列表中的代码块无法调整。外观字体大小

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#10710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/62794181/c6425921-f766-434b-a690-a47af5d0afae
具体如视频当中

### Expected result

希望在无序列表当中代码块能够自己调节字体大小

### Version environment

```markdown
- Version: 3.04
- Operating System:win11
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
实际上是：无序列表不支持修改字体大小

**Comment by QQQOrange** [comment]
> 实际上是：列表不支持修改字体大小

啊。准确的说是不支持直接的改。因为你可以在。段落块中把它改好后再移过去，那时候它仍然会保持原有样式。

**Comment by TCOTC** [comment]
我觉得列表不支持修改字体大小是因为列表前的序号和原点不能自动匹配段落字体的大小

**Comment by QQQOrange** [comment]
> 我觉得列表不支持修改字体大小是因为列表前的序号和原点不能自动匹配段落字体的大小

哦哦

**Comment by 88250** [comment]
是的，列表无法跳转，但是可以跳转里面的子块。
