### ISSUE TITLE
Improve database table view URL field display

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10712]
### In what scenarios do you need this feature?

像这种情况，链接填进去了就很难编辑了，点击就会打开网页：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/637f3dfb-ba98-4b89-bdd5-44c46199c36f)

试了一下，发现链接列、资源列、邮箱列都有差不多的问题

### Describe the optimal solution

1. 像主键那样在后面放一个「更新」按钮
2. 点击不会打开网页，而是在后面放一个「访问链接」按钮（下图是 FlowUs 的操作）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fe2769fa-5bfa-4a8b-a1e0-e75b6a0bdf14)

**Comment by TCOTC** [comment]
希望能跟 #10713 一起改进

**Comment by shuojie819** [comment]
我觉得可以加一个按钮或者保持现在……
现在不点击链接也是可以编辑的，点击链接跳转，就挺好的……但编辑确实不太好点
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/0ec13393-e28b-479a-9dd8-adc87cd07c05)

**Comment by 88250** [comment]
不考虑了，这里的交互参考 Notion。

**Comment by TCOTC** [comment]
我觉得这里没必要跟Notion一样，Notion的这个地方做得也不方便

**Comment by 88250** [comment]
先这样，改成其他交互可能会有冲突。

**Comment by TCOTC** [comment]
那链接和邮箱前能不能多留一点空位，这样好点一些：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/af524b3e-dfdc-4888-b405-0f2456165284)

**Comment by Vanessa219** [comment]
可以在上下空白位置进行点击

**Comment by TCOTC** [comment]
不太好点击，不小心就会点到链接打开网页

**Comment by Vanessa219** [comment]
上下的空间是比较多的，如果左侧调整了比上下空间大，整个表格空白会比较多显示的内容就会比较少。

**Comment by TCOTC** [comment]
那就再隐藏链接前面的 `http(s)://(www)` ，这样链接显示的内容就比原来还多

**Comment by TCOTC** [comment]
Notion的链接前面留了一块地方：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4eb6db44-481e-4819-8106-5e9abe05d26e)

**Comment by TCOTC** [comment]
以及要不再把数据库里链接的字号缩小一些？

**Comment by Vanessa219** [comment]
字号已经缩小过了，左右空白我再加一点，然后移除协议。
