### ISSUE TITLE
Improve export PDF window

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10711]
导出PDF界面支持调整窗口大小

### In what scenarios do you need this feature?

现在的窗口大小是固定的，在某些分辨率下会出现问题，例如宽度不够显示不完整，希望能支持调整大小。

1. 链滴上的用户：[v3.0.4 导出界面是不是有问题？ - Mustakshif 的回帖 - 链滴](https://ld246.com/article/1711156056266/comment/1711177209646#comments)

https://github.com/siyuan-note/siyuan/assets/78434827/3cfd6f4b-1385-4881-b1be-546f645cb41d

2. 我自己的电脑：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4d3fadfa-de60-4cb4-a3d8-ec2359b54836)

### Describe the optimal solution

导出PDF界面支持调整窗口大小

**Comment by TCOTC** [comment]
dev4 可以调窗口大小了，但这个界面还是有点奇怪。

要不让窗口大小默认铺满编辑器？还有给窗口加个外框

![image](https://github.com/siyuan-note/siyuan/assets/78434827/92f72f58-7e25-4971-9f31-4d02b52ac7d4)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a9ac5b1a-2684-4da0-9327-4e045d74d344)

**Comment by 88250** [comment]
我这里正常，使用 dev 版可能需要禁用缓存+强制刷新：

![image](https://github.com/siyuan-note/siyuan/assets/873584/7cd6fda8-ae80-4332-ab7a-1ff31375310c)

**Comment by TCOTC** [comment]
那我等 3.0.5 再看看

**Comment by TCOTC** [comment]
3.0.5 还是跟文档区分不清（都是白色），窗口大小也不够大

![image](https://github.com/siyuan-note/siyuan/assets/78434827/00ab5315-e752-44e4-ba21-a321b3b4b1c6)

**Comment by TCOTC** [comment]
显示器分辨率：2560*1440 ，缩放：100%

**Comment by TCOTC** [comment]
还有这里都是白色，看不出纸张的范围：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/72a4c545-5e71-4e40-9b9c-cc6096c978ac)

**Comment by 88250** [comment]
@TCOTC 禁用所有插件、代码片段等扩展（或者在新工作空间）测试看看。

**Comment by TCOTC** [comment]
> 禁用所有插件、代码片段等扩展（或者在新工作空间）测试看看。

是同样的

**Comment by 88250** [comment]
我这里实在无法重现。

**Comment by TCOTC** [comment]
确实换台设备就复现不了了，以后找到稳定的复现方法再说。

另外，还有下面这个问题：

> 还有这里都是白色，看不出纸张的范围：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/316725571-72a4c545-5e71-4e40-9b9c-cc6096c978ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjE4OTMsIm5iZiI6MTcxMTQ2MTU5MywicGF0aCI6Ii83ODQzNDgyNy8zMTY3MjU1NzEtNzJhNGM1NDUtNWU3MS00ZTQwLTliOWMtY2M2MDk2Yzk3OGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEzNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NWY1M2I5MzFmZWJlM2VmOWYzMmZhMzU5NmRiOGY1NTg1NTVmMDQ5NzY3MmM4YjYwZGJmNzlmOTQ3ZDU1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jtAhCvSf-SBXhPNFEqqOGqnpTmHQ2Y4WiD6p5_Z2YKg)

**Comment by 88250** [comment]
这个图片看不到哦。
