### ISSUE TITLE
数据库链接列支持多个链接、邮箱列支持多个邮箱

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10713]
### In what scenarios do you need this feature?

有时候需要在一行内添加多个链接或邮箱，但又不能增加一个就多加一列

### Describe the optimal solution

像资源列那样，还可以调整顺序：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a502cfa6-5917-4bc8-b88c-798b9f5b2f4f)

**Comment by TCOTC** [comment]
希望能跟 #10712 一起改进

**Comment by shuojie819** [comment]
支持
确实，有的有多个网址确实不太好，需要多列，有的只有单个网址，就很……

**Comment by 88250** [comment]
不考虑了，这里的交互参考 Notion。

**Comment by TCOTC** [comment]
刚刚发现资源列是可以放链接的，不过我觉得一个链接应该只占一行

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c2f2061c-50ef-45d1-a095-35eb2eaea251)

**Comment by 88250** [comment]
这里好像是空格分隔的

**Comment by TCOTC** [comment]
> 这里好像是空格分隔的

空格分隔是指什么？

**Comment by 88250** [comment]
多个资源在表格中显示上是以空格+底色分隔的，不是换行分隔。

**Comment by TCOTC** [comment]
我想表达的是，图里的第二个链接无论有多长都应该只占一行，现在这个链接长得很奇怪：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/97db77a7-268f-40fc-92f1-6ee549c8a04a)

**Comment by 88250** [comment]
有时间看看 @Vanessa219

**Comment by Vanessa219** [comment]
修改为这样吧
<img width="236" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/730e86e9-3318-4be2-a350-2bd693761138">

**Comment by TCOTC** [comment]
能不能自动隐藏前面的 `http(s)://(www)` ？

**Comment by Vanessa219** [comment]
可以填写标题
