### ISSUE TITLE
Asset link element prompt shows more information

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10714]
资源文件提示显示更多信息

### In what scenarios do you need this feature?

有时候会想知道某个附件的大小，此时只能「打开文件位置」用系统资源管理器查看，有点不方便，如果能直接显示就好了。

除了文件大小，如果能再显示创建时间、修改时间之类的就更好了。

### Describe the optimal solution

除了显示链接外，再增加显示更多信息

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b25fbc6e-e33b-40ce-ac7d-cdcf73c8c899)

**Comment by TCOTC** [comment]
或者在右键菜单中显示

**Comment by jim555666888** [comment]
希望能做成这样

<img width="1247" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/f8bdb4ee-6d09-4d3c-bcc3-056545061390">

<img width="423" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/e348b3cf-ec6e-4fb8-8ea5-88f8476b17b9">

**Comment by TCOTC** [comment]
图1 是数据库增加一个字段，自动获取资源文件的大小

图2 得靠插件
