### ISSUE TITLE
增加搜索面板关键词高亮接口

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#10723]
### In what scenarios do you need this feature?

#9950，目前SQL搜索时没有关键词高亮，希望增加一个插件接口，传入一系列关键词，然后在搜索面板的搜索结果中高亮这些关键词

### Describe the optimal solution

关键词高亮接口

**Comment by 88250** [comment]
请描述参数和返回值我们讨论下。

**Comment by choyy** [comment]
比如我想高亮“关键词1”、“关键词2”这两个关键词，这时我传入一个关键词数组`["关键词1", "关键词2"]`，然后搜索结果中高亮这两个关键词，至于返回值我觉得不需要。
想要实现的效果是用`关键词1 关键词2`搜索和用`select * from blocks where content like "%关键词1%" and content like "%关键词2%"`搜索是等效的

**Comment by 88250** [comment]
SQL 搜索结果做不了高亮。

**Comment by choyy** [comment]
在搜索结果高亮关键词难以实现吗这个，还跟关键词搜索不一样吗

**Comment by 88250** [comment]
不好实现，现在的高亮用的是 SQLite snippet 函数。

**Comment by choyy** [comment]
那能不能这样: 
我在搜索之前传入关键词，传入之后我用sql搜索，搜索结果用之前传入的关键词高亮结果，对于用的不是sql搜索的则忽略传入的关键词

**Comment by 88250** [comment]
你指的是哪个接口？

**Comment by choyy** [comment]
插件能用的接口

**Comment by 88250** [comment]
具体是哪个……？

**Comment by choyy** [comment]
不是还没有吗...
是希望有个东西能在插件里高亮sql搜索的关键词，sql搜索就是ctrl p搜索面板的sql搜索

**Comment by 88250** [comment]
SQL 结果目前高亮不了的。

**Comment by choyy** [comment]
那还是就算提前知道关键词也没法高亮是吧

**Comment by 88250** [comment]
是的，SQL 查询不支持 snippet 函数。

**Comment by choyy** [comment]
我还以为snippet是sql的东西
还是等着看后面会不会改高亮方法吧，目前高亮好像不能高亮数据库和代码块，有个搜索插件倒是自己写了这个的高亮
