### ISSUE TITLE
Feature Request: Native Attribute Panel with Show/Hide Options per Doc Block

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10725]
### In what scenarios do you need this feature?

Currently, there is a plugin for SiYuan that tries to do this, but it has some problems. First, the plugin's interface isn't fully translated into English. Also, its design and functionality don't meet expectations, and it lacks the ability to show or hide the attributes panel for each document block. This is an issue for a user coming from Obsidian, where a native attribute panel is a default feature.

### Describe the optimal solution

I'd like to propose the addition of a native attribute panel in SiYuan, similar to the one found in Obsidian. This feature would significantly improve the user experience by allowing users to show or hide the attribute panel for each document block depending on the user requirements.

For reference, Obsidian has a built-in attribute panel that serves as a great example of how this feature could look and operate in SiYuan.

![SiYuan_OHEAQT1yCN](https://github.com/siyuan-note/siyuan/assets/36538038/68d3bbe3-c5d5-4eee-984b-c81993b047ae)

Implementing a native attribute panel with the option to customize its visibility on a per-document basis would be a valuable addition to SiYuan.

Here is the attribute panel plugin for SiYuan, for reference.
[SiYuan Attribute Panel](https://github.com/InEase/siyuan-attributes-panel)

**Comment by 88250** [comment]
Hello, we have considered this requirement before and will not plan to implement it in the short term. Please refer to (in Chinese) https://github.com/siyuan-note/siyuan/issues/10425

**Comment by MrIntellectX** [comment]
Can we expect this by the end of this year? 🥲

**Comment by 88250** [comment]
The design has not been decided yet, because in SiYuan both the document block and other blocks can be added to the database, so adding an editor panel only for the document block will break this consistent design. Therefore, the design consideration is to open the Attribute panel - Database through the block database superscript icon.
