### ISSUE TITLE
Select field is added by default when creating a database

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10720]

**Comment by TCOTC** [comment]
还有可以默认添加 3 行

**Comment by 88250** [comment]
默认行暂时不加了，后面看看反馈。

**Comment by TCOTC** [comment]
我觉得怎么着也得默认添加 1 行，用户创建数据库就肯定需要手动点击加号添加一行

**Comment by 88250** [comment]
@TCOTC 可能是拖拽块。

**Comment by TCOTC** [comment]
说实话我觉得大部分人都是会直接添加一行的。

---

另外「添加」按钮可以再宽一些吧？或者像Notion那样只要点击最后一行就可以添加：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5e06d790-fdf9-4a58-946c-e330cb52cab5)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a8742bda-0faa-4e5f-b290-010c99ad7d2a)

**Comment by 88250** [comment]
暂时不默认添加行了。添加按钮宽度 @Vanessa219 看看。

**Comment by TCOTC** [comment]
@Vanessa219 要不把「加载更多」移到右边，然后把「添加」拉宽？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/86f36a37-c62c-427e-8a98-41a09812d3aa)
