### ISSUE TITLE
网页剪藏的API文档

### ISSUE THREAD

**Issue by Vincentdu-cn** [siyuan-note/siyuan#10728]
### In what scenarios do you need this feature?

配合微信去调用网页剪藏的API，实现微信文章自动网页剪藏。

### Describe the optimal solution

没找到这个API的调用方式

**Comment by 88250** [comment]
请看用户指南收集箱章节，但是不支持剪藏，仅支持录入数据，微信文章剪藏可以通过思源公众号或者思源小助手完成。
