### ISSUE TITLE
Enhancement: Integrate 'Turn Into' Menu and Color Selection for Marker/Highlighter into Toolbar with Dropdown Menu

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10726]
### In what scenarios do you need this feature?

In SiYuan, we currently have a "Turn Into" menu option for headings, paragraphs, etc. However, it would be significantly improved if we could access this in the toolbar when we select the text. Additionally, there are no color options for the mark/highlighter.

### Describe the optimal solution

I would like to request moving the "Turn Into" menu inside the toolbar, with nice dropdown animations similar to those in this video example. Also, please add color drop down menu options for the marker/highlighter.

https://github.com/siyuan-note/siyuan/assets/36538038/cace19b2-2eda-4137-87e7-be3fb1d557df

![SnippingTool_tfQgd6Vl92](https://github.com/siyuan-note/siyuan/assets/36538038/42a41d23-883f-4f64-8067-756d7701ee40)

**Comment by 88250** [comment]
Only some block-level elements can be converted to each other; the highlight mark does not distinguish text. If you want to distinguish, please define the color through CSS yourself, thank you.

**Comment by MrIntellectX** [comment]
1. I meant to move this menu into the toolbar, as that would be more accessible and faster for users. 

![SnippingTool_x1pW8YU0jQ](https://github.com/siyuan-note/siyuan/assets/36538038/20fc4815-6682-4e34-b1b1-aa3a7c22344d)

2. Even though I define my highlighter color through a CSS snippet, I don't have multiple highlighter drop-down options and I don't think it would be difficult to add those options and move the menu into the toolbar. 

I would appreciate it if these features could be implemented. Thank you.

**Comment by 88250** [comment]
1. There is a clear distinction between block-level elements and inline-level elements. After selecting the text, the inline-level element toolbar appears
2. It is recommended to use the Appearance

   ![image](https://github.com/siyuan-note/siyuan/assets/873584/05203f05-d640-4da1-9a2f-bfd79063152c)
