### ISSUE TITLE
笔记中插入超链接或者附件，链接文本混乱而且失效，且不能定位所在文件夹

### ISSUE THREAD

**Issue by lhx-JIPS** [siyuan-note/siyuan#1073]
### 描述问题 Describe the problem

0.6.0之前的版本插入超链接是正常的，而且链接文本显示正常，比如`[国家农业图书馆](http://www.nais.net.cn/publish/default/)`。0.6.0版本插入超链接，就会显示如下：`[国家农业图书馆](%5Bhttp://www.nais.net.cn/publish/default/%5D(http://www.nais.net.cn/publish/default/)%E2%80%B8)`，Ctrl+单机并不会跳出网页，而是跳转到“我的电脑”位置。

从工具栏中“上传图片或文件”按钮插入附件，之前版本显示`[CN110699465A一种分子标记及应用.pdf](assets/20201223154446-8ibakup-CN110699465A-一种快速提高鸭群体青壳率的分子标记及应用.pdf)`，现在版本显示`[CN110699465A一种分子标记及应用.pdf](assets/20210115104425-rod1909-CN110699465A-%E4%B8%80%E7%A7%8D%E5%BF%AB%E9%80%9F%E6%8F%90%E9%AB%98%E9%B8%AD%E7%BE%A4%E4%BD%93%E9%9D%92%E5%A3%B3%E7%8E%87%E7%9A%84%E5%88%86%E5%AD%90%E6%A0%87%E8%AE%B0%E5%8F%8A%E5%BA%94%E7%94%A8.pdf)`，很乱，虽然也能打开，但是不能通过右键→【资源】→【打开文件位置】来定位所在的\assets文件夹。
注：之前版本已经插入的文件，也即0.6.0版本中仍能正常显示为`[CN110699465A一种分子标记及应用.pdf](assets/20201223154446-8ibakup-CN110699465A-一种分子标记及应用.pdf)`的 文件还是可以定位\assets文件夹的。

### 期待的结果 Expected result

插入超链接或者附件，仍然显示为`[CN110699465A一种分子标记及应用.pdf](assets/20201223154446-8ibakup-CN110699465A-一种快速提高鸭群体青壳率的分子标记及应用.pdf)`这种正常文字的，而不是一堆%这样的内容，而且能够正确打开网页和定位文件夹。

### 版本环境 Version environment

* 版本 Version：0.6.0
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，061 已经修复，感谢反馈。
