### ISSUE TITLE
Support opening images through other apps on the Android

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10736]

**Comment by TCOTC** [comment]
希望支持直接下载到相册

**Comment by 88250** [comment]
保存到相册还支持不了，现在弹出打开方式，选择用某种 app 打开。

**Comment by Soltus** [comment]
> 保存到相册还支持不了，现在只能做到弹出打开方式，选择用某种 app 打开。

我好像已经实现了https://github.com/Hi-Windom/Sillot-android/blob/main/app/src/main/java/org/b3log/siyuan/JSAndroid.java#L325-L355

**Comment by pisceswb** [comment]
请求能够通过其它应用打开PDF文件。这样手写功能就能用了

**Comment by TCOTC** [comment]
> 请求能够通过其它应用打开PDF文件。这样手写功能就能用了

v3.0.5 开始应该就行了，至少我这里可以

**Comment by pisceswb** [comment]
> > 请求能够通过其它应用打开PDF文件。这样手写功能就能用了
> 
> v3.0.5 开始应该就行了，至少我这里可以

是在链接上长按吗？等我回去试一下

**Comment by TCOTC** [comment]
> > v3.0.5 开始应该就行了，至少我这里可以
> 
> 是在链接上长按吗？等我回去试一下

我这里是单击 PDF 链接后等两三秒，就会弹出手机系统自带的面板

**Comment by pisceswb** [comment]
那我这边好像不行，点击链接后，会像PC那样，直接在思源笔记内部打开。
