### ISSUE TITLE
Support search code snippets

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10739]
### In what scenarios do you need this feature?

When managing a large collection of CSS/JS snippets in SiYuan, it becomes increasingly difficult to quickly locate specific snippets. The absence of a search feature slows down the workflow, making it cumbersome to scroll through potentially hundreds of snippets to find the one needed.

### Describe the optimal solution

Implement a search bar in the CSS/JS Snippets window for real-time, case-insensitive filtering. Supports partial matches to quickly find snippets.

![SiYuan_XwhAjTqga3](https://github.com/siyuan-note/siyuan/assets/36538038/ceb7d8d6-b73a-49e2-accd-1d9f0bf8e7bc)

**Comment by TCOTC** [comment]
刚想提这个。我也需要，代码太多了

**Comment by TCOTC** [comment]
还希望增加排序功能

**Comment by 88250** [comment]
拖拽排序不考虑了，下个版本可以试试手动在 标题 中添加数字序号，我们按字符串升序排序。

**Comment by 88250** [comment]
> 还希望增加手动排序功能

不考了排序了，因为代码片段多了以后没有太大用处，搜索过滤更实用。
