### ISSUE TITLE
当图片位于页面底部时，没有办法直接换行

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1074]
https://user-images.githubusercontent.com/38101170/104675422-73e6af00-5720-11eb-85ae-4376db9404d9.mp4

**Comment by Andy-AO** [comment]
现在看来比较好的变通方法是先按一下空格键，然后可以操作了，操作完成之后再删除空格就行了

**Comment by 88250** [comment]
一些情况可能需要用这个，谢谢 :)
![image](https://user-images.githubusercontent.com/873584/104753059-71bd3880-5792-11eb-88e1-a12b33cc04e7.png)
