### ISSUE TITLE
无法替换html标签

### ISSUE THREAD

**Issue by psyuhen** [siyuan-note/siyuan#10743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/6522440/dd640e52-69a2-446f-a79f-c7b13aa411fd)
x比如说我要替换掉图中的<span>，使用Ctrl+F能搜索出来，但要将其替换为空字符串时，压根替换不了。

### Expected result

能正常替换

### Version environment

```markdown
- Version: v3.0.4
- Operating System: windows 11家庭版
- Browser (if used):
```

### Log file

没找到日志

**Comment by 88250** [comment]
替换类型 中是否已经勾选 行级代码？

![image](https://github.com/siyuan-note/siyuan/assets/873584/b586a7ca-210b-4e7e-9c5a-710cb4149153)

**Comment by 88250** [comment]
我先关闭了，如果还有补充请继续跟帖，谢谢 :pray:
