### ISSUE TITLE
偶现更新报错

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#10744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

退出时安装更新报错
![image](https://github.com/siyuan-note/siyuan/assets/32903588/85934558-2ac6-4f4b-809a-aa6431b3b132)

### Expected result

修复

### Version environment

```markdown
- Version: 3.0.4
- Operating System: win10
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/14751817/system-log.1.zip)

**Comment by TCOTC** [comment]
一直以来都有这个问题

**Comment by 88250** [comment]
这是系统的问题，请参考 https://ld246.com/article/1678285508141
