### ISSUE TITLE
Easy color costumization (Quoteblocks, Callouts, etc)

### ISSUE THREAD

**Issue by n12k0** [siyuan-note/siyuan#10742]
### In what scenarios do you need this feature?

When importing highlights from Zotero using the citation plugin, the default colors used by Siyuan for the text within callout or quote blocks do not provide enough contrast against the background colors of these elements, which are automatically applied based on the highlight color from Zotero. This issue significantly impacts readability, and manually adjusting each instance is impractical due to the volume of highlights I work with.

### Describe the optimal solution

I propose adding a feature or setting that allows users to easily customize font and background colors within callout and quote blocks amongst others to ensure readability and user customization

### Describe the candidate solution

If not, maybe there is a possibility to utilize a CSS snippet or another method within Siyuan to systematically change the font color inside callout or quote blocks. 
Make the documentation for this easily available. 

### Other information

I am using the dark theme. One workaround is changing themes, but this does not eliminate the problem, it simply reduces it. 

Thank you for your time and consideration.

**Comment by 88250** [comment]
Hi, as you mentioned in the candidate solution, this problem can be solved using CSS snippets, thanks.
