### ISSUE TITLE
failed create dailynote with "name"

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#10747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

#10698 support create dailynote with attribute "name", however, when I test it, nothing happens.

I wrote this two lines in the top line of template markdown file, respectively, and some other template formula. However, non of them works, the other template formula works fine.
`{: id="20240322095922-wtmxs1m" type="doc" name="测试命名"}`
`{: id="20240301230416-xxxxxxx" type="doc" name="星期.action{ now | WeekdayCN }"}`

what's wrong or how to use this function?

### Expected result

-

### Version environment

```markdown
- Version: 3.0.5
- Operating System: win11
- Browser (if used):-
```

### Log file

-

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/f717cf90-6c35-45cd-bac8-122e50349377)

![image](https://github.com/siyuan-note/siyuan/assets/873584/ec0664a4-2651-4d49-9d9f-f53ee426ee26)


你好，我这里测试两个模板都能正常工作，请确认内核版本以及笔记本设置创建时使用的模板：

![image](https://github.com/siyuan-note/siyuan/assets/873584/60b1cf60-69d2-4fe5-8ef7-07082aa4c6bb)

**Comment by XinLi0111** [comment]
抱歉，已确认能使用，之前是通过日历插件创建的，所以不能识别
