### ISSUE TITLE
Improve the handling of empty values in database multi-field sorting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10758]
改进数据库多字段排序包含空值处理

### In what scenarios do you need this feature?

目前数据库多字段排序时，包含空字段的行是不参与排序的。但数据库不可能每行每个用来排序的字段都填满

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f73a0a0f-da2d-4288-a99e-b19b2c7d55b7)

### Describe the optimal solution

包含空字段的行应该按条件先后参与排序，先满足前一个排序条件，再满足后一个排序条件，**依次满足**，直到包含空字段时置底

比如在 Notion 中是参与排序的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b6c91d63-9a57-4cc1-b344-3accba5bcc9c)

### Other information

关联：[数据库多列排序功能反馈](https://ld246.com/article/1711436602110)

**Comment by 88250** [comment]
这个点不考虑改变了，谢谢。

**Comment by TCOTC** [comment]
飞书：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3b6d4893-f05f-4c42-b6d3-595931bcc880)

FlowUs：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/76c0608f-938b-428b-b00a-ee4b7bc3d5b5)

Excel 就更不用再看了

**Comment by TCOTC** [comment]
确实大家都是这样排序的

**Comment by TCOTC** [comment]
用了dev版，顺序好像反了，空值排在开头了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3505c892-5214-443e-813d-1e40034188a8)

**Comment by 88250** [comment]
发一下排序规则。
