### ISSUE TITLE
删除书签时不需要确认

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10757]
### In what scenarios do you need this feature?

每次删除书签都要点确认，好麻烦

### Describe the optimal solution

像文档树这样给个配置项：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5b897d93-3dc7-4482-8abe-1ed09b4b1581)

### Other information

另外，删除**标签**时的确认应该继续保留

**Comment by 88250** [comment]
和标签一样，统一保留。
