### ISSUE TITLE
对于被选中的部分执行'引用'操作的时候会有遗漏

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1076]
https://user-images.githubusercontent.com/38101170/104676022-8f05ee80-5721-11eb-9b20-ffda7502e0a9.mp4

**Comment by Andy-AO** [comment]
现在感觉是不能够实现跨块儿的执行
但我认为这个操作还是挺常用的

**Comment by wo4wangle** [comment]
> 现在感觉不能多选内容块执行,但我认为这个操作还是挺常用的.
> 很多时候想要对连成片的文本进行这个操作，之间会有些换行，如果没有办法直接操作的话会繁琐很多.

我也是多选党，批量这种事情应该交给工具，而不是用户
目前能想到的就是超级快 顶一顶了

**Comment by Andy-AO** [comment]
> > 现在感觉不能多选内容块执行,但我认为这个操作还是挺常用的.
> > 很多时候想要对连成片的文本进行这个操作，之间会有些换行，如果没有办法直接操作的话会繁琐很多.
> 
> 我也是多选党，批量这种事情应该交给工具，而不是用户
> 目前能想到的就是超级快 顶一顶了

你不说我都忘了，其实我早就写好脚本了，改一下就能够实现.

**Comment by 88250** [comment]
你好，请关注 #132
