### ISSUE TITLE
FR: plugin eventbus for `switch-protyle` on mobile device

### ISSUE THREAD

**Issue by OpaqueGlass** [siyuan-note/siyuan#10766]
### In what scenarios do you need this feature?

在移动端切换文档时，似乎并不能够触发`switch-protyle`事件；目前层级导航插件使用`loaded-protyle-static`，在侧滑返回时不能触发更新；

### Describe the optimal solution

希望有一个适配移动端的编辑器切换事件；

**Comment by OpaqueGlass** [comment]
另外请教一下，移动端都没有“model”，无法判断是正常打开文档还是插件打开的，有区分办法吗？

**Comment by Vanessa219** [comment]
文档打开的目前为 window.siyuan.mobile.editor

**Comment by OpaqueGlass** [comment]
@Vanessa219  打扰一下，在移动端，`switch-protyle`触发的似乎有点早，事件出现的时候，event detail中的Protyle、`window.siyuan.mobile.editor.protyle`还是上一个文档的，请问这个可以处理一下吗？

**Comment by Vanessa219** [comment]
下个版本再看看

**Comment by OpaqueGlass** [comment]
问题已经解决，谢谢
