### ISSUE TITLE
Search type setting distinguishes between container blocks and leaf blocks

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#10762]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/31495943/75d434b9-b18c-4f39-96e3-78e56ab238bd)
show some information to help user easily determining which type they want to choose.

### Describe the optimal solution

maybe give a classification (container VS leaf block) of all blocks.

### Describe the candidate solution

arrange the container block at the left/ top position, and the leaf at the right/bottom position.

**Comment by TCOTC** [comment]
赞同。或者至少可以把搜索类型分为两栏，更有效利用空间

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8216b1d6-5bd6-4ef7-b45b-8821195e32ec)

**Comment by 88250** [comment]
关联 https://ld246.com/article/1713763756846

**Comment by TCOTC** [comment]
桌面端能不能把这些选项分成两列来显示？
