### ISSUE TITLE
Improv database asset edit

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10768]
数据库资源列支持编辑链接

### In what scenarios do you need this feature?

v3.0.5 目前插入的链接只能编辑标题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3044a1af-42fd-446b-98ff-ac2812fa42e7)

### Describe the optimal solution

支持编辑链接

**Comment by Vanessa219** [comment]
链接也记不住，确认添加以后应该不需要修改

**Comment by TCOTC** [comment]
有些资源的链接是会变的，偶尔要更新链接。

目前的情况下只能：

**编辑 → 全选复制标题 → 删除 → 新插入链接 → 粘贴标题 → 填写链接**

如果支持修改链接的话就是：

**编辑 → 修改链接**

方便多了

**Comment by TCOTC** [comment]
另外只能看到标题的话也不知道链接是啥，希望鼠标悬停在上面的时候能显示链接：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bedb6fab-f823-4f3e-807e-c511a8ddb9fc)

**Comment by TCOTC** [comment]
另外还发现一个问题：

![数据库](https://github.com/siyuan-note/siyuan/assets/78434827/7dc2902b-4ba9-437f-8efd-864697359646)

**Comment by Vanessa219** [comment]
1. 拖拽消失
2. 链接提示 url，图片提示标题
3. 支持链接编辑 url
4. 改进当 url 相同时的编辑和删除

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/11031
