### ISSUE TITLE
删除资源功能优化

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10771]
### In what scenarios do you need this feature?

当前删除图片资源，只是将图片链接删除，图片资源仍然保留在 asset 目录下，很多人可能对这个事情没有感知。
希望添加彻底删除功能，如果某个资源只有当前这一个唯一的引用，点击彻底删除可以将文件同时删除，
![image](https://github.com/siyuan-note/siyuan/assets/16383685/bdb2af38-4450-48e2-a32f-2ab9efb75f75)

### Describe the optimal solution

RT

**Comment by 88250** [comment]
这个不考虑提供了，谢谢。

**Comment by Temacc0531** [comment]
未引用的资源可以到 设置-资源 里面统一管理

**Comment by woniuxia** [comment]
嗯嗯，这个知道，是想要更方便的删除资源的功能
