### ISSUE TITLE
Prompt when dragging and inserting a folder

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10779]
https://github.com/siyuan-note/siyuan/issues/10770#issuecomment-2024241962

**Comment by TCOTC** [comment]
能否支持复制整个文件夹并 `Ctrl+V` 粘贴插入？

我看到是支持链接到文件夹的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5a95d467-a768-402d-b97d-f98143acf610)

**Comment by 88250** [comment]
现在应该也支持，但是只能复制超链接。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sat, Mar 30, 2024 12:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Prompt when dragging and inserting a folder(Issue #10779)




 
能否支持复制整个文件夹并 Ctrl+V 粘贴插入？
 
我看到是支持链接到文件夹的：
 
image.png (view on web)

**Comment by TCOTC** [comment]
希望支持粘贴文件夹时复制文件夹到 assets 下并自动链接为 `[文件夹名](assets/文件夹名/)`

**Comment by 88250** [comment]
复制文件不行的，这会导致其他问题，另外跨平台也支持不了复制文件。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sat, Mar 30, 2024 13:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Prompt when dragging and inserting a folder(Issue #10779)




 
希望支持粘贴文件夹时复制文件夹到 assets 下并自动链接为 [文件夹名](assets/文件夹名/)

**Comment by TCOTC** [comment]
好的。我还有一个问题，如果是在 `assets/文件夹名/` 下的文件是不是不支持搜索：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/02b6e7a0-077e-47be-a4c5-4d56c5469361)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/67c87449-8797-4617-93ec-9112acbb8a8f)

**Comment by 88250** [comment]
文件内容搜索吗？



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sat, Mar 30, 2024 13:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Prompt when dragging and inserting a folder(Issue #10779)




 
好的。我还有一个问题，如果是在 assets/文件夹名/ 下的文件是不是不支持搜索：
 
image.png (view on web)
 
image.png (view on web)

**Comment by TCOTC** [comment]
那现在就有两个问题：

1. 插入资源文件时搜索
2. 文件内容搜索

不知道会不会跟「笔记本级资源文件」是一样的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1980c4fc-cc4b-4d7c-ba98-edf631644188)

**Comment by 88250** [comment]
我这里试了一下可以 /资源 搜索：

![image](https://github.com/siyuan-note/siyuan/assets/873584/88f4636c-d4f9-40fc-84cd-d1ca6f527b3b)

文件内容搜索的话不支持。

**Comment by TCOTC** [comment]
> 复制文件不行的，这会导致其他问题，另外跨平台也支持不了复制文件。

我看到好像是有能实现上传文件夹的 API ？

[文件与目录条目 API - Web API | MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/File_and_Directory_Entries_API)
