### ISSUE TITLE
Unified Left Panel Toggle for Enhanced Usability

### ISSUE THREAD

**Issue by MrIntellectX** [siyuan-note/siyuan#10777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Currently, when we click on the doc tree, it shows/hides flawlessly. However, once we click on other icons like the bookmark at the bottom left, tags, or plugins, clicking on the doc tree does not hide the overall left panel and I understand that this behavior occurs because the doc tree and the bottom left panel are separate. Sometimes, this can be confusing, especially when in a hurry.

https://github.com/siyuan-note/siyuan/assets/36538038/8261c105-47ca-40e5-ba4d-d5d60ca42b83

### Expected result

In Affine, Obsidian, and Notion, there is a single button that controls the complete show/hide functionality of the left panel, and accessible via a shortcut. I believe SiYuan should also implement a main icon to manage the visibility of the entire left panel comprehensively.

For the icon and reference, please take a look at each picture.

Notion:
![Notion_PgSkuZPbmS](https://github.com/siyuan-note/siyuan/assets/36538038/7fa37ec9-514b-429b-8d5c-f2b4483dde21)

Affine:
![AFFiNE_BkvkGi8gcK](https://github.com/siyuan-note/siyuan/assets/36538038/e47fe6dd-8f88-4c4e-923c-9f7d0e28e1d0)

Obsidian:
![Obsidian_6d45nn2SoU](https://github.com/siyuan-note/siyuan/assets/36538038/286018f5-7bdc-4606-9fc6-932767bed629)

I think Affine & Obsidian do a great job, their icons look clearer and better.

### Version environment

```markdown
- Version: 3.0.5
- Operating System: Win 11 Pro
- Browser (if used): -
```

### Log file

.

**Comment by 88250** [comment]
We refer to the logic of the JetBrains series for this part of the design and will not consider modifying it. Thank you.

**Comment by MrIntellectX** [comment]
I'm not requesting a change, but rather the addition of a main toggle button to open/close the entire left panel. This is because I sometimes want to focus solely on the editor. Currently, I use the shortcut Alt+1, which only works to open/close the left panel when no bottom left icon is selected. If an icon is selected, it doesn't work as it's supposed to. Implementing a toggle button to control the entire left panel would greatly improve usability. I appreciate your consideration of this request. Thanks.

**Comment by 88250** [comment]
You can move the dock icon in the lower left corner to the upper left corner (right-click move), so that it is concentrated in one panel.

**Comment by MrIntellectX** [comment]
Well, that trick works pretty well, but there is a problem. I usually need web apps to be at the bottom and the document tree above. With this trick, I can only show either web apps or the document tree, which is not an efficient solution. This is why I'm requesting a separate toggle button, if possible. Maybe it takes your time, no need to hurry, but try to add one main toggle button.

**Comment by 88250** [comment]
This part of the design will not change, please forgive me.

**Comment by MrIntellectX** [comment]
Its okay.
