### ISSUE TITLE
Database sort by multiple fields work not expected

### ISSUE THREAD

**Issue by zhenzou** [siyuan-note/siyuan#10775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

多字段排序不符合预期。如下截图

### Expected result

测试中的应该排在规划中前面，在 3.0.5 之前的版本正常。

### Screenshot or screen recording presentation

<img width="408" alt="image" src="https://github.com/siyuan-note/siyuan/assets/7829073/c5af2ee6-9799-48dd-8581-83de96e9631b">

<img width="346" alt="image" src="https://github.com/siyuan-note/siyuan/assets/7829073/e5b27ceb-30b2-49dd-a05c-1ddcdb685db2">

### Version environment

```markdown
- Version: 3.0.5
- Operating System: MacOS
- Browser (if used):
```

### Log file

[siyuan2.log](https://github.com/siyuan-note/siyuan/files/14776534/siyuan2.log)

**Comment by 88250** [comment]
单选已经改为按选项设置顺序排序，请在选项设置中手动拖拽顺序。
