### ISSUE TITLE
隐藏收集箱

### ISSUE THREAD

**Issue by FEI352** [siyuan-note/siyuan#10778]
### In what scenarios do you need this feature?

能否出个隐藏收集箱的功能，看者碍眼。如果免费版本出于吸引用户的一种策略，要它一直存在；那末功能特性付费了之后能否出个隐藏的按钮。

### Describe the optimal solution

出个隐藏掉收集箱的设置选项。

**Comment by 88250** [comment]
不考虑了，抱歉。

**Comment by shuojie819** [comment]
集市里面有个 “移除按钮” 的插件
![image](https://github.com/siyuan-note/siyuan/assets/72399630/4b9b06a7-7820-4e3d-80e5-3ae629fc56e4)
