### ISSUE TITLE
面包屑中 `&` 的显示问题

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#10781]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/72399630/0b223dc5-de3a-47bc-9622-9fa8d984c6ac)

### Describe the optimal solution

希望显示成“测试&测试”

**Comment by TCOTC** [comment]
是有这个问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/df15e650-569b-4f88-a7c0-2884fdeb89fc)

**Comment by 88250** [comment]
版本应该是 v3.0.6-dev 吧？合并到 https://github.com/siyuan-note/siyuan/issues/10753 中处理。

**Comment by shuojie819** [comment]
> 版本应该是 v3.0.6-dev 吧？合并到 #10753 中处理。

是的 3.0.6-dev1
