### ISSUE TITLE
输入回车后公式全不见

### ISSUE THREAD

**Issue by dream-tentacle** [siyuan-note/siyuan#10786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在一个有公式的自然段按下回车，这一段的公式全没了。在不同的文件中尝试都有此问题。

### Expected result

修复bug

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/127286614/b1aeea38-4d8b-4520-918e-a850e5e035e5

### Version environment

```markdown
- Version: 3.0.5
- Operating System: Windows
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14798366/siyuan.log)

**Comment by 5kyfkr** [comment]
https://github.com/siyuan-note/siyuan/issues/10751
下3.0.6的dev2，已经修好了

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/10751
