### ISSUE TITLE
Support editing saved layouts

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10783]
### In what scenarios do you need this feature?

[建议支持布局的多端云同步和布局更新 - 链滴](https://ld246.com/article/1687918406189) Point 2

目前创建一个同名的布局就能覆盖原来的布局，但每次更新布局都要重新输入一次布局名称非常繁琐

### Describe the optimal solution

在删除的左边添加一个更新布局按钮

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ac2cbba7-8ab6-4c2e-b6eb-540a400b9f40)

**Comment by 5kyfkr** [comment]
可以，这个建议非常好

**Comment by Vanessa219** [comment]
其它窗口的保持后面有时间再优化，目前先这样吧。

**Comment by TCOTC** [comment]
> 保存了单独窗口的PDF

还有这种操作。我的副屏有用武之地了

**Comment by TCOTC** [comment]
> 能不能保存主窗口外的窗口，现在好像只能保存主界面内的布局，我保存了单独窗口的PDF也没办法再下次打开

@Vanessa219 这个能实现吗？

**Comment by TCOTC** [comment]
@Vanessa219 用了 v3.0.6-dev3 ，跟我想的不一样，应该是我表述的问题。

虽然支持编辑布局名称也很好，但我所说的「更新」是指将当前的页面布局覆盖保存到一个已有的布局名称中

**Comment by TCOTC** [comment]
可以考虑在保存布局的时候支持从已保存的布局中选择

直接在这个界面下方列出已保存的布局：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/aedda4b2-aca4-445d-af5a-20e60aaa7291)

**Comment by TCOTC** [comment]
现在点击确定的时候会同时保存编辑后的备注和当前的布局，但此处的确定只应该保存备注的文本：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/709ab2d1-cbdd-42c6-aab5-47c87f284ab3)

**Comment by TCOTC** [comment]
然后按钮的顺序很奇怪，我改了一下： #10804

**Comment by Vanessa219** [comment]
> > 能不能保存主窗口外的窗口，现在好像只能保存主界面内的布局，我保存了单独窗口的PDF也没办法再下次打开
> 
> @Vanessa219 这个能实现吗？

这个应该是可以实现的。

点击保存是可以 将当前布局更新到已有保存好的布局之中。现在是不能更新还是什么问题？

按钮顺序和人工智能编辑是一致的，还麻烦一起进行调整。

**Comment by 5kyfkr** [comment]
> > > 能不能保存主窗口外的窗口，现在好像只能保存主界面内的布局，我保存了单独窗口的PDF也没办法再下次打开
> > 
> > 
> > @Vanessa219 这个能实现吗？
> 
> 这个应该是可以实现的。
> 
> 点击保存是可以 将当前布局更新到已有保存好的布局之中。现在是不能更新还是什么问题？

V姐，是两个需求：
1.可以直接在每个已保存的视图的名称上有个更新或保存按钮，如下图，这样就不用在手打一遍名称
![image](https://github.com/siyuan-note/siyuan/assets/63196026/2bc8b54c-b0e4-4f70-8593-8ce86a6e09b7)
2.例如下图，有两个单独窗口的情况下，只能保存主窗口的布局，下次无法打开左边的PDF窗口
![image](https://github.com/siyuan-note/siyuan/assets/63196026/f79c029c-0809-4571-8854-719102efb574)

**Comment by Vanessa219** [comment]
第一个需求在 dev 版本中实现了，是有什么问题么？第二点可以实现，但是可能会带来其他问题，目前先不在这个 issue 里面处理。

**Comment by 5kyfkr** [comment]
> 第一个需求在 dev 版本中实现了，是有什么问题么？第二点可以实现，但是可能会带来其他问题，目前先不在这个 issue 里面处理。
是指实现这个更新名字嘛，我们想的是更新视图，名字其实一开始都想好了不怎么需要更新，就是视图比如我高数今天学了一章，保存了一个视图，第二天学第二章，这时候就想直接在昨天保存的视图上点更新，就把现在的视图替换到昨天的视图了
![image](https://github.com/siyuan-note/siyuan/assets/63196026/e4f115c6-e604-4e16-acaa-ae5ef20e2d91)

**Comment by 5kyfkr** [comment]
> 有两个单独窗口的情况下，只能保存主窗口的布局，下次无法打开左边的PDF窗口
https://github.com/siyuan-note/siyuan/issues/10807
我开了个，这个功能感觉还是有用的，能利用多屏幕的优势

**Comment by TCOTC** [comment]
> 第一个需求在 dev 版本中实现了，是有什么问题么？第二点可以实现，但是可能会带来其他问题，目前先不在这个 issue 里面处理。
> 
> > 是指实现这个更新名字嘛，我们想的是更新视图，名字其实一开始都想好了不怎么需要更新，就是视图比如我高数今天学了一章，保存了一个视图，第二天学第二章，这时候就想直接在昨天保存的视图上点更新，就把现在的视图替换到昨天的视图了

现在的问题是大家都以为是更新备注用的，实际上点击「确定」后会同时保存备注和当前的页面布局，把之前的布局覆盖了

**Comment by 5kyfkr** [comment]
> 覆盖更新布局应该有一个单独的按钮

好家伙原来可以保存，那现在这个按钮应该叫更新名称及视图会合理一点

**Comment by TCOTC** [comment]
> > 覆盖更新布局应该有一个单独的按钮
> 
> 好家伙原来可以保存，那现在这个按钮应该叫更新名称及布局会合理一点

但这样就没办法只更新名称(备注)了，所以功能要分离

**Comment by Vanessa219** [comment]
又更新了下 

<img width="525" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/9bbcfaab-417c-4435-a226-fd967f4af389">

**Comment by TCOTC** [comment]
「更新」看着让人有点迷糊，感觉怪怪的

也许改成「更新布局」？

也许鼠标悬浮在上面的时候给个提示？比如「更新为当前页面布局」

**Comment by Vanessa219** [comment]
ok

**Comment by TCOTC** [comment]
也许可以再把 重命名 改为 重命名布局 ，以更显著地区分开这两个对布局的操作。

**Comment by Vanessa219** [comment]
这个应该没有歧义了，就先这样吧，按钮文案不宜过长。
