### ISSUE TITLE
重命名文档，打一个字符执行一遍索引

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#10780]
### In what scenarios do you need this feature?

重命名文档，打一个字符执行一遍索引
一个文档下面有很多个子文档，会卡好长时间，改一个字符就执行一遍……，第一个字符还在执行，然后写了第二个第三个（中间停顿一下），就把第二个也执行一遍再执行第三个……这是BUG吧？
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/bcca6cdd-61a3-4768-a1ba-71225b0198b5)

文件少的时候没什么多了就得卡好一会（执行好几遍索引）……

### Describe the optimal solution

应该确认重命名后再执行索引，当我按下回车，或者停顿多长时间，再给我重命名

**Comment by TCOTC** [comment]
感觉可以优化一下，目前是编辑文档名时立即执行「更新文档的可读路径」，但如果此时文档名还没编辑完，所以就要等第一次「更新文档的可读路径」完成再重新执行一次。

可以适当延长一下时间，比如当文档名 5s 无变动后、焦点离开时再「更新文档的可读路径」

**Comment by 88250** [comment]
暂时没有优化方案了，关联之前的讨论 https://github.com/siyuan-note/siyuan/issues/10560

**Comment by UFDXD** [comment]
你可以想好名字打出来然后粘贴进去

**Comment by shuojie819** [comment]
> 你可以想好名字打出来然后粘贴进去

其实可以直接 `F2` 修改

**Comment by TCOTC** [comment]
> > 你可以想好名字打出来然后粘贴进去
> 
> 其实可以直接 `F2` 修改

没发现还有这种操作

**Comment by 88250** [comment]
暂时关闭了，一次性输入顶顶吧，谢谢。
