### ISSUE TITLE
内核被 windows defender 报告威胁

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#1078]
![image](https://user-images.githubusercontent.com/32661922/104678554-a5fb0f80-5726-11eb-9745-8617c3b89c69.png)

**Comment by 88250** [comment]
这个问题我们不知道如何处理……

**Comment by deerainw** [comment]
那我暂时先在这里记录一下...

彻底卸载思源并重新安装，在安装完成的瞬间 windows defenfer 出现上述警告

启动思源，不停出现以下警告，无法启动

![image](https://user-images.githubusercontent.com/32661922/104680388-b7deb180-572a-11eb-95f0-855e030f8913.png)

**Comment by deerainw** [comment]
回退到 059 版本，无此问题
