### ISSUE TITLE
VIM Mode in the editor

### ISSUE THREAD

**Issue by navakelvin** [siyuan-note/siyuan#10785]
### In what scenarios do you need this feature?

There is not much to say. VIM mode for faster editing.

### Describe the optimal solution

I don't know what editor the Siyuan editor is based on, but if it is CodeMirror this is more than possible.

### Other information

Thank you. I hope this can be added, it is such a useful feature that many would appreciate.

**Comment by 88250** [comment]
Sorry, VIM mode cannot be implemented, it is not based on CodeMirror.

**Comment by schmoelder** [comment]
Actually, codemirror comes with a VIM mode. This is also used by other apps such as Joplin. For more information, see also here: https://codemirror.net/5/demo/vim.html

**Comment by LF-Flores** [comment]
> That being said, vim mode is essential for many people for considering your very promising app.

I second this. Got interested in the app, but can't really use it without VIM mode.

**Comment by cosmos-wonder** [comment]
> > That being said, vim mode is essential for many people for considering your very promising app.
> 
> I second this. Got interested in the app, but can't really use it without VIM mode.

I also need VIM.

**Comment by oruamy** [comment]
Yes. VIM is a must!

**Comment by Mohamed-Gibreel** [comment]
@88250, just curious if there will be any plans on this feature ?

**Comment by 88250** [comment]
Sorry, we are unable to implement this feature.

**Comment by Palayoub** [comment]
+1 for VIM support

**Comment by sober-wang** [comment]
Or Can you  recommand support vim mode plugin?
