### ISSUE TITLE
Support batch selection and deletion of data snapshots 支持多选删除数据快照

### ISSUE THREAD

**Issue by liao-zh** [siyuan-note/siyuan#10787]
### In what scenarios do you need this feature?

Currently (v3.0.5), local/cloud tagged snapshots can only be selected and deleted one by one. If I want to delete multiple snapshots, such operation is inconvenient. Hope that batch selection and deletion is supported.

By the way, the English text is currently displayed as "Local/Cloud (tag) snapshot". Should it be "Local/Cloud (tagged) snapshots"?

### Describe the optimal solution

see above

**Comment by 88250** [comment]
Hello, please use the Data repo purge function:

Local: 
![image](https://github.com/user-attachments/assets/c3f58afc-4bef-4c84-8e1f-2853525fe9a1)

Cloud: 
![image](https://github.com/user-attachments/assets/f70669df-d14f-4bdc-bfe3-5e17c86f46eb)

**Comment by liao-zh** [comment]
> Hello, please use the Data repo purge function:
> 
> Local: ![image](https://private-user-images.githubusercontent.com/873584/369042707-c3f58afc-4bef-4c84-8e1f-2853525fe9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODcyMTMsIm5iZiI6MTcyNjk4NjkxMywicGF0aCI6Ii84NzM1ODQvMzY5MDQyNzA3LWMzZjU4YWZjLTRiZWYtNGM4NC04ZTFmLTI4NTM1MjVmZTlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNjM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNmE1ZWM4ZDBkYzYwYTk0ZGFhOTk5ODAxM2U3NjMyYzA2NTU5YWJkZjYwMzRlNGI2OTk2ZWYxMzQzZmUzNTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fZbhrFX2XWJzGCyzrEvJmZs8ANZg3Gno3RYK5zuld6E)
> 
> Cloud: ![image](https://private-user-images.githubusercontent.com/873584/369043177-f70669df-d14f-4bdc-bfe3-5e17c86f46eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODcyMTMsIm5iZiI6MTcyNjk4NjkxMywicGF0aCI6Ii84NzM1ODQvMzY5MDQzMTc3LWY3MDY2OWRmLWQxNGYtNGJkYy1iZmUzLTVlMTdjODZmNDZlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNjM1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGVjMjViZDRkYzc5MTc1MTUxMmFjYTdlNGQwNDM5OGUwMjQzNjQ3Y2ExNjFjYzVlOWM1YTRiZGY0MDQ3ZmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._iAoZS9q5glL_ETZMqkRqQof3_MUxJR9BwtyvIPcMmI)

需求是删除部分快照（主要是本地和云端标记的快照），而不是删除全部快照。不能多选的话只能一个个删除，本地删除一遍，云端再删除一遍，比较繁琐。

**Comment by 88250** [comment]
抱歉，目前不考虑手动删除，后续可能会考虑按清理策略自动清理。

**Comment by liao-zh** [comment]
> 抱歉，目前不考虑手动删除，后续可能会考虑按清理策略自动清理。

有道理，我一般的需求是删除那些比较旧的快照

**Comment by liao-zh** [comment]
现在是3.1.25版，要不要考虑一下重开这个issue？

现在能自动清理的是未标记的快照，本地和云端标记的快照还是不能多选删除。标记一个快照的时候，我一般会选标记并上传，即本地有一份，云端也有一份。要删除的话，需要本地一个一个删除，然后云端一个一个再删除一遍，比较麻烦。

对于标记的快照，希望可以多选删除，可以把“删除”按钮放在“创建快照”旁边。

@88250

**Comment by 88250** [comment]
暂时不考虑改进了，等继续收集需求再看看，感谢反馈。
