### ISSUE TITLE
Data history supports querying in all notebooks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10788]
数据历史增加「所有笔记本」选项

### In what scenarios do you need this feature?

一个笔记本一个笔记本看非常繁琐，增加「所有笔记本」选项配合搜索来用更合适

### Describe the optimal solution

就像旁边的「所有操作」一样，增加「所有笔记本」

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2e16abae-fadc-4255-9595-0a33a8afaafc)

### Other information

关联：[建议增加回收站功能](https://ld246.com/article/1711685504371)

**Comment by TCOTC** [comment]
另外建议在前面补上中文翻译，这几个操作我也就认得 update delete sync ，另外3个我就不知道是干嘛用的了

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1773ec42-3ae3-4b23-89d9-24a5185f30f9)

**Comment by 88250** [comment]
> 另外建议在操作前面补上中文翻译

这个不考虑了，要和文件系统上 history 下的文件夹对应的。

**Comment by zxhd863943427** [comment]
非要实现这个需求的话，英文后面加括号，内带中文即可。

另外尽量改进数据历史以避免用户直接操作文件系统应该是目标才对，所以我觉得直接用中文也没啥不好……难道真的有用户会这么操作？我表示怀疑。

**Comment by TCOTC** [comment]
> > 另外建议在操作前面补上中文翻译
> 
> 这个不考虑了，要和文件系统上 history 下的文件夹对应的，以便用户在文件系统上操作。

@88250 补上中文翻译并不妨碍「和文件系统上 history 下的文件夹对应」吧？

**Comment by 88250** [comment]
谁去 PR 一下吧。

**Comment by TCOTC** [comment]
> 谁去 PR 一下吧，顺便把 外观 里面的默认主题也搞一下，多谢。

1. 在 #10793 加上了数据历史操作的翻译。
2. 好像有些代码写死了 daylight 和 midnight ，我不会改

**Comment by 88250** [comment]
好的，多谢。

**Comment by TCOTC** [comment]
对了，补充一句：跟默认选择「所有操作」一样，打开界面时默认选择「所有笔记本」

**Comment by 88250** [comment]
新工作空间的话会默认所有，之前的工作空间会按最后一次选择记录。

**Comment by TCOTC** [comment]
意思就是更新之后默认打开不是选择「所有笔记本」，需要先选择一次「所有笔记本」再关闭，下次打开就会选择「所有笔记本」吗？

总结一下就是跟随上次的选择？

**Comment by TCOTC** [comment]
意思就是更新之后默认打开不是选择「所有笔记本」，需要先选择一次「所有笔记本」再关闭，下次打开就会选择「所有笔记本」吗？

总结一下就是跟随上次的选择？

**Comment by 88250** [comment]
是的，这个逻辑一直都是这样，不是这次更新加的。

**Comment by TCOTC** [comment]
怎么 closed 了

**Comment by TCOTC** [comment]
看到提交了
