### ISSUE TITLE
引用预览窗口存在不必要的闪烁

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1079]
https://user-images.githubusercontent.com/38101170/104680568-2459b080-572b-11eb-8e87-7ee5209e510d.mp4

**Comment by wo4wangle** [comment]
诶，你这是啥番茄软件，感觉比我的番茄计时可能好用一点

**Comment by Andy-AO** [comment]
> 诶，你这是啥番茄软件，感觉比我的番茄计时可能好用一点

我的番茄工作法软件是自己用JavaFX写的

忘记是什么时候了，反正可能很多年前吧

用遍了所有番茄工作法软件，PC端没有让我满意的

要不就是付费价格很高，要不就是卡的不行，我也不知道为什么这么个功能就没人设计好

自己写了之后又一直用的很舒服

在GitHub开源发布了

**Comment by Andy-AO** [comment]
> 诶，你这是啥番茄软件，感觉比我的番茄计时可能好用一点

当然bug有点多啊,但由于用户就我,所以那些bug对我的使用不造成影响,我就根本没动.
之后可能会用C sharp再写一个类似的，这次弄个网站发布出去，免费给大家用用.

**Comment by Andy-AO** [comment]
> 诶，你这是啥番茄软件，感觉比我的番茄计时可能好用一点

可以尝试一下,不过你应该有Java+JavaFX环境,Java8最推荐,因为那个版本自带JavaFX.
之后C#版本就没这些要求了，因为可能会用WPF,只要是Windows就应该会有.

https://github.com/Andy-AO/MyTomato

**Comment by 88250** [comment]
你好，编辑的时候会重新渲染元素，所以悬浮框会闪烁，这个暂时解决不了，谢谢。
