### ISSUE TITLE
Browser clipping extension supports configuring document tags

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10797]
剪藏扩展支持配置文档标签

### In what scenarios do you need this feature?

我需要给每个剪藏的文档打上 #剪藏 标签来区分我写的内容和剪藏的内容，但每次都要手动在思源里操作，并且不是每一次都记得打标签，所以需要剪藏时自动添加

### Describe the optimal solution

剪藏的文档自动添加文档标签。

如果可能的话，支持自定义任意个标签，比如：`#剪藏, #存档/网页` 

### Other information

https://github.com/siyuan-note/siyuan-chrome

[希望剪藏插件增加功能 - 链滴](https://ld246.com/article/1710596302316)

**Comment by 88250** [comment]
这个考虑在剪藏扩展上支持，或者直接剪藏到“剪藏笔记本”。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年3月30日(周六) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 剪藏的文档自动添加文档标签 (Issue #10797)




 
In what scenarios do you need this feature?
 
我需要给每个剪藏的文档打上 #剪藏 标签来区分我写的内容和剪藏的内容，但每次都要手动在思源里操作，并且不是每一次都记得打标签，所以需要剪藏时自动添加
 
Describe the optimal solution
 
剪藏的文档自动添加文档标签。
 
如果可能的话，支持自定义任意个标签，比如：#剪藏, #存档/网页
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by TCOTC** [comment]
> 或者直接剪藏到“剪藏笔记本”

我确实是有个笔记本用来临时存放剪藏的文档，但一般我剪藏下来都是要挪到其他地方的。

比如剪藏了一篇跟前端有关的文档，我要移动到 `【领域】计算机科学与技术 > Web技术 > 网页前端` 文档下，但时不时会忘记给文档添加 #剪藏 标签，可能会跟其他文档弄混

**Comment by 88250** [comment]
> 但时不时会忘记给文档添加 #剪藏 标签，可能会跟其他文档弄混

这个怕是只能整理的时候注意下了。

**Comment by TCOTC** [comment]
所以还是在剪藏扩展上支持最好了

**Comment by 88250** [comment]
嗯，我把 issue 改一下。

**Comment by woniuxia** [comment]
（眼泪汪汪）D大，剪藏支持绑定数据库也支持下呗。

**Comment by 88250** [comment]
> （眼泪汪汪）D大，剪藏支持绑定数据库也支持下呗。

请建个 issue 描述下需求和交互。

**Comment by 88250** [comment]
需要升级剪藏扩展 v1.3.0

**Comment by woniuxia** [comment]
https://github.com/siyuan-note/siyuan/issues/10824?utm_source=ld246.com

D大，这个有啥进展吗

**Comment by 88250** [comment]
没有



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 20, 2024 14:44 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Browser clipping extension supportsconfiguring document tags (Issue #10797)




 
https://github.com/siyuan-note/siyuan/issues/10824?utm_source=ld246.com
 
D大，这个有啥进展吗

**Comment by KuiyueRO** [comment]
D大这个有考虑过吗 https://ld246.com/article/1726584345622

**Comment by 88250** [comment]
需求不太多，暂时不考虑了。
