### ISSUE TITLE
增加默认assets位置选择

### ISSUE THREAD

**Issue by YiHui-Liu** [siyuan-note/siyuan#10790]
### In what scenarios do you need this feature?

现在所有的文件都在`data/assets`目录下面，不方便管理

### Describe the optimal solution

可提供自定义选项，是否开启为笔记本或者子文档单独新建assets

**Comment by 88250** [comment]
请看用户指南资源文件章节。

**Comment by YiHui-Liu** [comment]
这并没有解决问题：
> 如果需要默认将插入的资源文件放置在文档同级 assets 文件夹下，则需要先手动创建名为 assets 的文件夹，这样思源会优先选择该 assets 文件夹来存放资源文件。
建议尽量不要使用笔记本级资源文件，因为这会带来一些副作用：
> * 删除该笔记本时，为保证跨笔记本资源文件引用正常工作，该笔记本下的资源文件会被批量复制到全局 assets 中
> * 不支持在数据历史中查看笔记本级资源文件历史
> * 不支持使用 `/资源` 搜索
> * 不支持重命名

**Comment by 88250** [comment]
手动新建 assets 文件夹以后应该是可以的，但是会有如上提到的限制。
