### ISSUE TITLE
数据库中通过“重复”或者“+”新建1个重复的数据库后，新建的表和原表的内容会有联动，即改了新表中的内容，原表也会变动。

### ISSUE THREAD

**Issue by cxyshine** [siyuan-note/siyuan#10791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库中通过“重复”或者“+”新建1个重复的数据库后，新建的表和原表的内容会有联动，即改了新表中的内容，原表也会变动。

### Expected result

同一个数据库中的不同表应该是各自独立的，可以通过“重复”或“+”复制原表到新建的表，但是新表建立后编辑原表内容应该不会影响到原表内容的变化，编辑原表也不会影响新表中的内容。

### Screenshot or screen recording presentation

no

### Version environment

```markdown
- Version: v3.0.5
- Operating System: mac
- Browser (if used): no
v3.0.5  、mac 、no
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14801584/siyuan.log)

### More information

no

**Comment by 88250** [comment]
这是设计特性，复制的数据库块是镜像块。
