### ISSUE TITLE
Improve API Token authentication

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10792]
https://ld246.com/article/1711591523782

Authorization 标头值支持 `Token`/`token` 和 `Bearer`/`bearer` 开头。

另外也调整桌面端 设置 - 关于 - API token 的界面交互。

**Comment by Zuoqiu-Yingyi** [comment]
Authorization 标头 `Bearer` 是 [OAuth 2.0 (RFC 6750)](https://datatracker.ietf.org/doc/html/rfc6750) 认证字段, 将其视为令牌不符合规范👀

**Comment by 88250** [comment]
> Authorization 标头 `Bearer` 是 [OAuth 2.0 (RFC 6750)](https://datatracker.ietf.org/doc/html/rfc6750) 认证字段, 将其视为令牌不符合规范👀

这个以业界通用做法为准吧，比如 GitHub REST API 也是这样的 https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api
