### ISSUE TITLE
[idea] 增强查询面板（优化当前搜索界面）

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10794]
### In what scenarios do you need this feature?

比关键词搜索更近一步，不懂正则表达式和 SQL 也能进行 **“高级检索”**

### 更多查询条件(过滤器)（参考了Notion、飞书）

- 范围
  - 在 某个/某些 笔记本/文档 中 （目前的「指定路径」功能增加多选）
- 时间
  - 编辑时间
  - 创建时间
  - 浏览时间（类似目前的「最近的文档」功能）
  - 指定前三者的时间段
    - A ~ B
    - \>= A
    - <= A
- 块类型
  - 目前的搜索类型
  - 块属性（组合搜索和单独搜索）
    - 内置属性
    - 数据库字段
    - 自定义属性
- 文本类型
  - 各种行级元素（组合搜索和单独搜索）
- 更多……

### 更美观的查询面板

- 一堆按钮放在右上角的方式还有优化的余地：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5316b082-a6c3-4abf-afa8-deeff84a6522)

- 更多呈现搜索结果的方式

**Comment by 88250** [comment]
考虑插件支持吧，现在这个保持不变了，谢谢。

**Comment by TCOTC** [comment]
关联：搜索功能ui重新设计 #1319
