### ISSUE TITLE
Improve web clip table parsing

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10799]
改进浏览器剪藏扩展处理表头

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

剪藏这个网址：https://cloud.tencent.com/developer/article/2362589

剪藏不了表头：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a6ba4edf-1a23-4c70-87a7-a697ed919840)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bdccd79a-a264-4da5-bbc2-efb7131217aa)

### Version environment

```markdown
- Version: 3.0.6-dev2
- Operating System: Win10
- Browser (if used):
```

**Comment by 88250** [comment]
简单看了下，应该是因为 https://github.com/siyuan-note/siyuan-chrome/blob/main/lib/Readability.js 中提取表格内容的时候把 table 标头单元格内容剔除了，这个定位起来有点麻烦，暂时先记录下。
