### ISSUE TITLE
ubuntu导入错误

### ISSUE THREAD

**Issue by cctv130** [siyuan-note/siyuan#10798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

windows导出的数据 在ubuntu倒入提示
This is not a valid Data archive. If the archive was exported from [Doc tree], please import it from [Doc tree] v3.0.5

### Expected result

能够在ubuntu倒入

### Version environment

```markdown
- Version：latest
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14810522/siyuan.log)

**Comment by 88250** [comment]
你好，Windows 上是从 设置 - 导出 - 导出 Data 中导出的吗？如果是从文档树导出的，请在文档树右键导入，这两个地方导出导入需要对应。

**Comment by 88250** [comment]
我这里测试了下，在 Windows 文档树上导出笔记本.sy.zip 和导出文档.sy.zip 两种，均可在 Ubuntu Appimage 文档树上导入。

我先关闭了，欢迎随时补充问题描述，谢谢 :pray:
