### ISSUE TITLE
进入预览后无法返回编辑模式

### ISSUE THREAD

**Issue by kiritocode** [siyuan-note/siyuan#1080]
### 描述问题 Describe the problem

进入预览后无法返回编辑模式。

右键context菜单或`<Alt-N>`进入预览后，没有返回编辑的方法。上面`Destop, Tablet, ...`按钮也不再是乒乓按钮了，按不掉。

还有，帮助文档里写的快捷键不起作用：
![image](https://user-images.githubusercontent.com/77135994/104683743-85d14d80-5732-11eb-8bc5-6c1513071972.png)

这里`Ctrl-Alt-7,8,9`都没有作用，需要更新文档？

### 期待的结果 Expected result

能够提供返回编辑模式的方法。
现在除了关闭再打开就没有办法回到编辑模式。

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/77135994/104683984-fd9f7800-5732-11eb-93a1-15811a1a7cce.png)
上面按钮点击多次也没用，无法回到编辑模式。

设置里面也找不到“回到编辑模式”这样的快捷键。

### 版本环境 Version environment

* 版本 Version：060
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：

**Comment by Vanessa219** [comment]
可以在工具栏上点击
![image](https://user-images.githubusercontent.com/970828/104717734-b6ca7600-5764-11eb-96bd-676795606267.png)

快捷键需要在这里配置一下
![image](https://user-images.githubusercontent.com/970828/104717655-98647a80-5764-11eb-8296-9724f186c6c6.png)

**Comment by kiritocode** [comment]
确认了下，旧版那个*模式切换*按钮也按不动。新版062里已修复了。
