### ISSUE TITLE
布局支持保存多窗口布局

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10807]
### In what scenarios do you need this feature?

如下图有两个单独窗口的情况下，只能保存主窗口的布局，下次无法打开左边的PDF窗口
![image](https://github.com/siyuan-note/siyuan/assets/63196026/9b621d62-6f74-42b3-908f-24c2cee9d5d3)

### Describe the optimal solution

可以正常保存多窗口布局，充分利用多屏幕工作场景下其他屏幕

**Comment by 88250** [comment]
邀请楼主参讨论一下这个 https://github.com/siyuan-note/siyuan/issues/10809

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/10809 中一并考虑了，谢谢。

**Comment by 5kyfkr** [comment]
> 合并到 #10809 中一并考虑了，谢谢。

没问题，那样更好，直接变成完全体
