### ISSUE TITLE
搜索文档时，显示文档标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10800]
### In what scenarios do you need this feature?

文档标题很不明显：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6e40b9b2-9458-4c9f-b820-1789b79dff66)

### Describe the optimal solution

跟正常打开文档一样显示标题

**Comment by TCOTC** [comment]
或许跟 #10693 一起考虑

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/64d84e4f-5499-4cf9-b918-ad408913137a)

**Comment by TCOTC** [comment]
不，我说的是字体太小的问题，不是说没有标题

**Comment by 88250** [comment]
这里全部用一个大小应该没有多大问题。

**Comment by TCOTC** [comment]
就是说这个文档标题的字体比文档内容还小，所以想加上个标题在最前面

**Comment by 88250** [comment]
抱歉，确实比内容小一点，我觉得目前这个效果没有问题，调整成一样的会显得标题太大。

![image](https://github.com/siyuan-note/siyuan/assets/873584/e597f64f-8aea-4266-9e2c-e21523e17bf1)

![image](https://github.com/siyuan-note/siyuan/assets/873584/e4da3302-4689-4756-9d21-87f3f5a8993d)

**Comment by TCOTC** [comment]
行吧，这个暂时不管了。

我另外有一个问题，按文档分组之后为什么不支持替换呢？

**Comment by 88250** [comment]
分组后替换是不支持的 https://github.com/siyuan-note/siyuan/issues/10161 因为分组条件传入以后搜索只能命中文档块，会导致 全部替换 失效。

**Comment by TCOTC** [comment]
> 分组后替换是不支持的 #10161 因为分组条件传入以后搜索只能命中文档块，会导致 全部替换 失效。

1. 意思是不全部替换就可以吗？但现在我点击「替换」和「全部替换」都会提示要取消分组。
2. 分组时搜索的结果和取消分组后搜索的结果会有不同吗？如果没有不同的话分组后理应和不分组一样可以全部替换

**Comment by 88250** [comment]
1. 放开限制的话单个替换可以支持，但是为了保持统一所以都禁用了
2. 比较困难，主要是这个函数要改
  
   ![image](https://github.com/siyuan-note/siyuan/assets/873584/22cc951f-cae3-480d-9556-67eb38633943)

因为取消分组也可以达到目的，所以暂时就不动了，先搞其他任务。

**Comment by TCOTC** [comment]
@88250 用浮窗打开文档的情况下，有办法复制文档标题吗？

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
菜单里面有个复制可读路径 @TCOTC

**Comment by TCOTC** [comment]
> 菜单里面有个复制可读路径

感觉还是差了一些，这个等于是把整个路径所有的文档名都复制了

**Comment by Vanessa219** [comment]
这个更完整，什么场景下需要复制标题呢？

**Comment by TCOTC** [comment]
除了复制之外，有时候还需要修改文档标题，能直接在浮窗里显示会更方便

**Comment by Vanessa219** [comment]
选中要浮窗 F2 试试。

**Comment by TCOTC** [comment]
F2 重命名的时候浮窗被关闭了诶

还有就是这里的菜单也需要一个重命名：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7e50a449-1d83-4e0b-a54c-b3c272e5a752)

**Comment by Vanessa219** [comment]
悬浮窗的功能本来就是预览。需要更多操作的话可以钉住或打开页签。

**Comment by TCOTC** [comment]
> 需要更多操作的话可以钉住或打开页签。

这就不得不提到 #11127 了

**Comment by TCOTC** [comment]
用户需求：https://ld246.com/article/1735908653643

**Comment by Vanessa219** [comment]
https://ld246.com/article/1735908653643/comment/1735963045965?r=Vanessa#comments

**Comment by TCOTC** [comment]
用户需求：https://ld246.com/article/1739958581880

**Comment by Vanessa219** [comment]
https://ld246.com/article/1739958581880/comment/1740019212439?r=Vanessa#comments
