### ISSUE TITLE
数据库数据存在，内容无法显示。

### ISSUE THREAD

**Issue by pakeh2866** [siyuan-note/siyuan#10819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/5708881/ea61aa49-8a29-462e-b278-754f75f1ee1e)

### Expected result

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by pakeh2866** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/5708881/b699ba36-b3e3-406a-8f59-7cd1e0d338e8)
其他数据库也不行了，需要补充什么信息？

**Comment by 88250** [comment]
请导出系统日志上传。

**Comment by 88250** [comment]
另外，建议在默认主题、关闭所有插件、代码片段后进行测试。

**Comment by pakeh2866** [comment]
更新到3.06dev版没了……不折腾了先。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
