### ISSUE TITLE
Export PDF and add watermarks no longer covered by images

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#10818]
导出PDF添加水印会被内容（比如图片）盖住

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

类似下面这样的设置，只在没有内容的地方显示了水印
![image](https://github.com/siyuan-note/siyuan/assets/5683995/4f21013d-a60e-4575-92ac-d7a60249f2cf)

### Expected result

用户希望水印在最上方

### Version environment

```markdown
- Version: 3.0.5
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by Achuan-2** [comment]
另外想问问导出图片的水印貌似无法添加
![Clip_2024-04-03_11-44-51](https://github.com/siyuan-note/siyuan/assets/60436214/28f707ee-73ba-4d0a-b138-46fcc92a1b09)
水印的设置反而到了图片底部
![Clip_2024-04-03_11-45-24](https://github.com/siyuan-note/siyuan/assets/60436214/cd11060b-acc5-448c-a1e8-47be43c2a882)

**Comment by 88250** [comment]
图片那个的意思是用图片作为 PDF 水印



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 3, 2024 11:46 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Export PDF and add watermarks no longercovered by images (Issue #10818)




 
另外想问问导出图片的水印貌似无法添加
 Clip_2024-04-03_11-44-51.png (view on web)
 水印的设置反而到了图片底部
 Clip_2024-04-03_11-45-24.png (view on web)

**Comment by Achuan-2** [comment]
不是，我指的是导出图片的水印设置貌似有问题（还是我设置不对，但是我导出pdf的水印是正常的），而不是导出pdf设置图片水印

**Comment by 88250** [comment]
@Vanessa219 帮忙看看。

**Comment by Vanessa219** [comment]
<img width="1017" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/d6ac7ce0-7c7d-4f37-8864-35eef9b5af2b">

**Comment by Achuan-2** [comment]
@Vanessa219 好吧，原来要用html，建议官方文档补充下水印这一方面的内容，毕竟是付费会员才能用，估计很多人都不懂用……

**Comment by Vanessa219** [comment]
水印样式为空的时候就会使用水印文本

<img width="950" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/892ae97e-f606-4438-900b-8d38d176cb24">

**Comment by Achuan-2** [comment]
> 水印样式为空的时候就会使用水印文本
> 
> <img alt="image" width="950" src="https://private-user-images.githubusercontent.com/970828/319228121-892ae97e-f606-4438-900b-8d38d176cb24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTQ4MzcsIm5iZiI6MTcxMjE1NDUzNywicGF0aCI6Ii85NzA4MjgvMzE5MjI4MTIxLTg5MmFlOTdlLWY2MDYtNDQzOC05MDBiLThkMzhkMTc2Y2IyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxNDI4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzE3ODhhZTJmMTNkNGIzNjY0MmZkMmQ4ZTI4N2NjZGU2ZmUxNWE3OGJiOTg2MTZjMmI1NTBlZGFiNjJjMDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JrETl7Gj8sqasSPeHKcE8iLrFEyb7kaOfKCKMdO47Uw">

ok，谢谢V姐
