### ISSUE TITLE
Template supports numerical calculations when using rollup

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10810]
模板使用汇总时支持数字计算

https://ld246.com/article/1711802472353

**Comment by TCOTC** [comment]
我觉得不是不支持计算

![image](https://github.com/siyuan-note/siyuan/assets/78434827/71fc2729-eb06-4868-84dd-9e306f4f480e)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/efefa796-d583-4ca4-b1f8-bd07f5fb63df)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/95104a46-09f2-4541-8ee8-de8c5207b936)

**Comment by 88250** [comment]
收到，明早我再看看，晚安。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Mon, Apr 1, 2024 00:18 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Template supports numerical calculationswhen using rollup (Issue #10810)




 
我觉得不是不支持计算
 
image.png (view on web)
 
image.png (view on web)
 
image.png (view on web)

**Comment by 88250** [comment]
这问题有点奇怪哦，我这里测试老和格式化没有关系，不格式化也不能进行计算：

![image](https://github.com/siyuan-note/siyuan/assets/873584/1ccf97f1-e6ea-4135-99da-f7b59cb5fad2)

![image](https://github.com/siyuan-note/siyuan/assets/873584/eece81b0-22d2-4761-b6d9-e4a7dd3cd2e5)

你上面那个截图麻烦导出一个 .sy.zip 我测试看看。

**Comment by TCOTC** [comment]
[测试用文档.sy.zip](https://github.com/siyuan-note/siyuan/files/14819501/sy.zip)

在我这里是这样的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/39a65ff6-0707-4e67-a7cd-1952444486f5)

**Comment by 88250** [comment]
@TCOTC 找到问题了，确实是格式化的问题，早上我看错代码了，多谢。
