### ISSUE TITLE
集市待更新列表在线获取新版 README ，不使用本地旧版本 README

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10811]
### In what scenarios do you need this feature?

点击已下载中待更新列表，目前会打开本地的旧版 README，导致要查看更新内容时还是要找到插件才能查看：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2417bb5b-391e-42f5-9bcf-f52b7de7b65c)

这样的话跟之前没有「全部更新」的时候完全没有区别，还是要一个个找到了点开来看，看 README 的时候顺便就能更新了，「全部更新」的作用不大。

而且在已下载列表里就可以查看本地的旧版 README 了，待更新列表完全不需要重复展示。

### Describe the optimal solution

集市待更新列表在线获取新版 README ，不使用本地旧版本 README

**Comment by 88250** [comment]
使用的本地的，要更新以后才显示最新的。

**Comment by TCOTC** [comment]
同样是更新插件，我认为在这两个地方查看的 README 应该保持一致：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3443eb61-a6be-4be1-8c5b-946a19979fcd)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d054c5cf-015a-446e-8fa1-89230a0f8d84)

**Comment by 88250** [comment]
不一样的，已下载的要使用本地 README 才能和版本配套，显示最新的反而会有问题。

**Comment by TCOTC** [comment]
应该是这么个关系：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/706ebe47-3d71-4d7c-8e23-668776d0e94d)

**Comment by 88250** [comment]
上面这个部分列出的是待更新的包，都是在 已下载 这个大类下的。

**Comment by TCOTC** [comment]
有点怪。更新插件之前肯定是想看一下更新了什么的

**Comment by 88250** [comment]
这有点难办，还是以当前版本匹配保险。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年4月1日(周一) 凌晨0:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 集市更新区域应显示最新的README (Issue #10811)




 
有点怪。更新插件之前肯定是想看一下更新了什么的

**Comment by TCOTC** [comment]
@88250 我受不了了，现在更新插件还是跟以前一样要一个个找到查看 README 。

> 不一样的，已下载的要使用本地 README 才能和版本配套，显示最新的反而会有问题。

目前在待更新列表里显示的是旧版 README ，与更新后的版本显然是不匹配的，不显示新版的 README 才会有问题。

上面的列表是更新新版，那就应该显示新版的 README ；下面的列表是已下载的旧版，那就应该显示旧版的 README 。

目前的逻辑会出现这样的情况：用户查看上面的插件 README ，以为是新版的 README ，发现没有什么变化所以就更新了：

1. 但实际上这个插件可能更新了一大堆功能导致与旧版数据不兼容，所以在新版 README 里说明了要删除插件后重新下载，但用户会因为没有看到新版 README 所以不知道。
2. 但实际上这个插件可能更改了一大堆功能导致用户需要的旧功能没有了，所以在新版 README 里说明了更新后的内容并提示用户按需更新，但用户会因为没有看到新版 README 所以不知道。

![image](https://github.com/siyuan-note/siyuan/assets/78434827/706ebe47-3d71-4d7c-8e23-668776d0e94d)

**Comment by mozhux** [comment]
我也觉得比较怪。。我甚至三次怀疑我没有更新成功。。昨天才点的更新怎么今天又有。然后还显示安装是昨天的。

**Comment by 88250** [comment]
@TCOTC 文档和代码要匹配这是基本原则，下载到本地的集市包肯定只能用包中自带的 README。如果要查看某个集市包的更新， 只能到集市列表中点进去看，这个就是最新版集市包匹配的 README。

所以这个 issue 不考虑改变了，谢谢。

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/16947#issuecomment-3831158028

**Comment by TCOTC** [comment]
@88250 这个不用 no plan

**Comment by 88250** [comment]
v3.5.5
