### ISSUE TITLE
Database table view select column does not set default selection

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当前单选/多选选项第一个选项的背景色是加深的，类似鼠标悬浮的效果，感觉好像不对劲。
明明是选中了其他的选项，当前这个感觉就像选中了第一个选项
![image](https://github.com/siyuan-note/siyuan/assets/16383685/3af988d7-1ae0-42f5-abcc-f8c44083287a)

### Expected result

第一个选项展示正常

### Version environment

```markdown
- Version:  v3.0.6
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
应该是 #10738 导致的，目前是始终着重显示首个选项

**Comment by woniuxia** [comment]
> 应该是 #10738 造成的，目前是始终着重显示首个选项

自己提的 feature，自己来提 bug，哈哈哈哈

**Comment by TCOTC** [comment]
> 自己提的 feature，自己来提 bug，哈哈哈哈

我也提了一堆，都要自己跟进才行

**Comment by Vanessa219** [comment]
背景高亮指的的是当前选中项，可以使用快捷键上下、回车进行操作的项。后面有勾选的才是单元格中已有的项。

**Comment by TCOTC** [comment]
我知道后面有勾选，但现在的问题不是这个嘛：

> 当前单选/多选选项第一个选项的背景色是加深的，明明是选中了其他的选项，当前这个感觉就像选中了第一个选项

**Comment by woniuxia** [comment]
@Vanessa219 V大，现在第一个选项不论是否被选中都是背景加深的，不符合预期

**Comment by Vanessa219** [comment]
背景高亮指的的是当前选中项，可以使用快捷键上下、回车进行操作的项。后面有勾选的才是单元格中已有的项。

**Comment by TCOTC** [comment]
确实。

不过这个勾是不是放到前面更好？离得太远了也没什么意义

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8e5b19be-3467-41c9-b088-de66dc8f48e7)

**Comment by TCOTC** [comment]
@Vanessa219 另外这个地方有点不对：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/0dd309c1-696a-40fd-a6dd-6c9eb4fe0c24)

**Comment by TCOTC** [comment]
感觉还是奇怪并且不好看，要不别用勾了，想想其他的形式

**Comment by TCOTC** [comment]
比如说选中的就在前面加一个色块：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7a6e2719-cf40-4ed6-a751-e0e696d87afa)

**Comment by TCOTC** [comment]
这个样式感觉挺好

**Comment by Vanessa219** [comment]
不好看呀，而且表现不出是已选中的数据

**Comment by TCOTC** [comment]
> 不好看呀

可以再看看怎么改

> 表现不出是已选中的数据

用户用几次就知道是怎么回事了

**Comment by TCOTC** [comment]
我也看过，所以思源做了就更方便

**Comment by TCOTC** [comment]
@Vanessa219 其他地方是要先按一次 ↑/↓ 才会出现背景高亮的：

![选择](https://github.com/siyuan-note/siyuan/assets/78434827/e31ba903-599d-4a1b-904d-14ecd3b0f0da)

**Comment by Vanessa219** [comment]
好像很有道理

**Comment by TCOTC** [comment]
@Vanessa219 我又想到了，没有选则的话是灰色，选则的就变亮：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dd10b67b-c15f-4e34-961f-7d5af06d4d15)

**Comment by Vanessa219** [comment]
变亮和上下键选中和鼠标移动样式会有冲突

**Comment by TCOTC** [comment]
> 变亮和上下键选中和鼠标移动样式会有冲突

@Vanessa219 只是在前面加一个明显的色块，应该不会跟灰色背景冲突吧？

p.s. 是方形圆角的色块，而不是像闪卡高亮那样的

**Comment by Vanessa219** [comment]
先不动了，一般选中都是整个背景高亮。
