### ISSUE TITLE
剪藏插件功能优化提议：绑定数据库

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10824]
### In what scenarios do you need this feature?

[关联](https://ld246.com/article/1711354462273/comment/1711415335638#comments)
数据库上线后，对整理信息有很大的帮助。

我当前每次剪藏完网页，都在一个数据库中将信息维护起来，现在比较麻烦。

所有希望剪藏插件可以支持绑定数据库，当剪藏网页后，自动将网页信息填充到一个数据库中。

填充的信息应该包括网页对的基本信息比如：标题、网页链接。

更进一步拓展，可以支持调用 ai 接口进行总结，填充到总结列。
类似下图的效果。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/301ab48f-0155-4ec5-b9fc-60bb484413f8)

### Describe the optimal solution

RT

**Comment by 88250** [comment]
> 自动将网页信息填充到一个数据库中

填到哪一个数据库中是配置还是选择？

**Comment by woniuxia** [comment]
他这个是提前配置好的。不过他这个配置是用来处理微信小助手的剪藏的，因为微信转发没法配置这些信息，所以需要提前配置。
这个大概看下形式就好，和咱们的架构不同。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/30c32de3-9747-457f-82c1-e8e827338ee1)
咱们要做的话，推荐搞成选择的，先选择笔记本，在选择数据库，数据库可以留空，表示不加入到数据库。
还可以加一个文本框用户可以简单备注和描述一些东西，还可以加个标签选择框方便用户做标签。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/1981c6fb-d42d-4c38-98e0-01635ba14842)
这是另外一家的情况，可以填写的内容比较丰富。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/5d66b781-95a1-44c6-80f0-5ca4b08cbaa4)

**Comment by TCOTC** [comment]
期望靠数据库实现该功能 #10863

**Comment by woniuxia** [comment]
关联：https://ld246.com/article/1712975513276

**Comment by Achuan-2** [comment]
+1，希望剪藏能将剪藏文档自动添加到数据库

**Comment by Achuan-2** [comment]
@88250 
最近剪藏插件添加了可以添加标签和指定存放路径，希望也添加剪藏后自动添加数据库的功能
可以参考【添加到数据库】功能和现在剪藏插件新增搜索路径功能，新增一个input框，输入数据库名称，进行搜索
用户选择后，剪藏时剪藏的文档自动添加到指定的数据库中

**Comment by TCOTC** [comment]
我觉得可以在 Database Automations #10863 支持添加一个 `剪藏新建文档` 的触发器、添加一个 `添加文档到数据库` 的执行操作。

**Comment by 5kyfkr** [comment]
非常支持

**Comment by 88250** [comment]
这个考虑通过插件实现吧，如果需要新增参数请告诉我们，谢谢。
