### ISSUE TITLE
粘贴时处理 HTML 标签

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1082]
某些文本被粘贴到编辑器后直接消失不见无法查看,例如` [[-MockWith] <ScriptBlock>]`.

https://user-images.githubusercontent.com/38101170/104686013-5244f200-5737-11eb-815f-b5ff15d8bcca.mp4

**Comment by Andy-AO** [comment]
![image](https://user-images.githubusercontent.com/38101170/104686083-7b658280-5737-11eb-9dd0-e6170eb711da.png)
Typora的处理方式就非常好，不会出现这种'幽灵'现象

**Comment by 88250** [comment]
谢谢反馈，HTML 标签的处理目前还没有细化，后期考虑。

**Comment by 88250** [comment]
粘贴原文还是按照原文处理比较好，如果原文是 `` `<tag>` `` 这样的应该没有问题，但如果只是 `<tag>` 的话会认为是 HTML 标签。这个逻辑暂时不动了，谢谢。
