### ISSUE TITLE
汇总支持模板列字段，并进行数学计算

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10820]
### In what scenarios do you need this feature?

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/49329782-3660-4c9b-a1bd-f6a6a84a61c6)
如图，想用数据库统计学习时间，模板已经搞定，但是汇总时发现无法使用模板列数字，不知道能否改进
另外虽然可以新建视图筛选关联，但是一个个弄很麻烦，还不能在一个表看完

### Describe the optimal solution

类似[#10810](https://github.com/siyuan-note/siyuan/issues/10810#issue-2217048499)反过来

### Describe the candidate solution

汇总支持模板列字段，并进行数学计算

**Comment by AvoidantPerDis** [comment]
另外这个用法需要默认选择具体时间选项，希望新增行时选项可以跟上一个同步，或是有数据库级别的默认选项，见https://github.com/siyuan-note/siyuan/issues/10558

**Comment by 88250** [comment]
这个之前考虑过，实现不了，仅支持模板中使用汇总，谢谢。

**Comment by AvoidantPerDis** [comment]
> 另外这个用法需要默认选择具体时间选项，希望新增行时选项可以跟上一个同步，或是有数据库级别的默认选项，见#10558

那这个可以吗

**Comment by 88250** [comment]
这个没看懂……

**Comment by AvoidantPerDis** [comment]
> 这个没看懂……

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/8d1a8bd7-2c7c-44d8-bf9e-888e80bad3fe)

**Comment by AvoidantPerDis** [comment]
最好是默认填充当前时间，现在的设计还是要点，手机上记不方便

**Comment by 88250** [comment]
默认填充后面再考虑，现在可以用拖拽填充。

**Comment by AvoidantPerDis** [comment]
拖拽了时间不就都一样了吗

> 默认填充后面再考虑，现在可以用拖拽填充。

**Comment by 88250** [comment]
哦哦，我理解成你需要的就是一样的……

**Comment by 88250** [comment]
后续请关注 https://github.com/siyuan-note/siyuan/issues/10823

**Comment by 88250** [comment]
汇总模板字段请关注 https://github.com/siyuan-note/siyuan/issues/12384
