### ISSUE TITLE
搜索条件支持大小写

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#10827]
### In what scenarios do you need this feature?

我知道设置里有大小写的开关，能否在搜索框右边加个大小写的选项，这样方便一点
<img width="288" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/6d301a30-b13c-4937-8c11-9d64fde3d19f">

主流编译器搜索的时候都会有大小写的选项，比如Vscode是这样的
<img width="207" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/480e1350-6e98-4fb5-8388-ecd1a9c07db1">

### Describe the optimal solution

搜索框右边加个大小写的选项

**Comment by 88250** [comment]
这个搞不定，因为设置大小写需要全量重建索引。如果有技术方案能解决索引问题的话就可以在这里加开关了。
