### ISSUE TITLE
Database date field supports filling the current time by default

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10823]
数据库日期字段支持默认填充当前时间

**Comment by AvoidantPerDis** [comment]
希望具体时间和结束时间这2了选项的开关能保持

**Comment by woniuxia** [comment]
结束时间保持常开+1

**Comment by 88250** [comment]
这两个选项暂时不考虑了，这个 issue 仅考虑默认填充创建时的时间，谢谢。

**Comment by Vanessa219** [comment]
`setAttrViewColDate {avID, id, data:bool}`

**Comment by TCOTC** [comment]
能不能指定默认不填具体时间？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b2b58d87-8505-4a7b-859e-84dc54eecda4)

**Comment by Vanessa219** [comment]
目前默认是没有具体时间的

**Comment by TCOTC** [comment]
默认填充有哦：

![日期](https://github.com/siyuan-note/siyuan/assets/78434827/80678960-c0f6-45d2-9af6-1308f9b3d2a8)

**Comment by Vanessa219** [comment]
@88250 看过来

**Comment by 88250** [comment]
这个是填充具体时间的。

**Comment by TCOTC** [comment]
> 这个是填充具体时间的。

就是说能不能给个选项不默认填充？或者就改成下拉菜单

- 默认填充创建时间
  - 不填充
  - 填充日期
  - 填充具体时间

**Comment by 88250** [comment]
这个暂时不调整了，按具体时间吧。

**Comment by 88250** [comment]
或者再建个 issue 记录下，谢谢。

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/10955
