### ISSUE TITLE
Outline drag function is abnormal

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10828]
大纲拖拽功能异常

1. 要拖拽到同级大纲下才能拖拽成功
2. 拖拽后如果不改变位置会置顶

![大纲2](https://github.com/siyuan-note/siyuan/assets/78434827/39de8991-945d-4459-930a-26fdec90e7e4)

![大纲](https://github.com/siyuan-note/siyuan/assets/78434827/1344cbcf-2a16-49fb-8216-786474ebcdd9)

### Version environment

```markdown
- Version: 3.0.6
- Operating System: Win10
- Browser (if used):
```

**Comment by TCOTC** [comment]
关联 #10826

**Comment by TCOTC** [comment]
[v3.0.6 大纲拖曳列表标题吞块 - 链滴](https://ld246.com/article/1712033329859)

![5ejto-7q7mb-F98GGdk](https://github.com/siyuan-note/siyuan/assets/78434827/c0d95be6-afa3-407e-bb29-5f40d2819f8b)

**Comment by TCOTC** [comment]
单纯点击时不应该拖拽

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a9a98f44-0bad-4b03-9aca-73f602025c1a)

**Comment by TCOTC** [comment]
在特殊情况下大纲能被带走：

![大纲3](https://github.com/siyuan-note/siyuan/assets/78434827/5e0db530-06cb-4500-9ab5-225adb409f00)

**Comment by TCOTC** [comment]
大纲不能拖拽为其他大纲的子层级（应该只限制不能拖拽为6级大纲的子层级）

**Comment by TCOTC** [comment]
大纲层级异常降低：

![大纲4](https://github.com/siyuan-note/siyuan/assets/78434827/19a65398-7466-4497-a199-52e3a9818743)

**Comment by TCOTC** [comment]
层级6拖拽到层级3，会变成层级4

**Comment by 88250** [comment]
> [v3.0.6 大纲拖曳列表标题吞块 - 链滴](https://ld246.com/article/1712033329859)
> 
> ![5ejto-7q7mb-F98GGdk](https://private-user-images.githubusercontent.com/78434827/318651477-c0d95be6-afa3-407e-bb29-5f40d2819f8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzg0NDksIm5iZiI6MTcxMjAzODE0OSwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTE0NzctYzBkOTViZTYtYWZhMy00MDdlLWJiMjktNWY0MGQyODE5ZjhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YTQxYmRjMmNiMDBkYjUyOGE0NGQ5ZWZhNzdjNzMzZmI3N2JhODg3OGY2MzFiMDYwZGYwNzNlYTk5NjhmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pmKFR8PUqaGmvccHn1bhgNfgMyXbU-u48qy6sWZATiY) [ ![5ejto-7q7mb-F98GGdk](https://private-user-images.githubusercontent.com/78434827/318651477-c0d95be6-afa3-407e-bb29-5f40d2819f8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzg0NDksIm5iZiI6MTcxMjAzODE0OSwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTE0NzctYzBkOTViZTYtYWZhMy00MDdlLWJiMjktNWY0MGQyODE5ZjhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YTQxYmRjMmNiMDBkYjUyOGE0NGQ5ZWZhNzdjNzMzZmI3N2JhODg3OGY2MzFiMDYwZGYwNzNlYTk5NjhmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pmKFR8PUqaGmvccHn1bhgNfgMyXbU-u48qy6sWZATiY) ](https://private-user-images.githubusercontent.com/78434827/318651477-c0d95be6-afa3-407e-bb29-5f40d2819f8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzg0NDksIm5iZiI6MTcxMjAzODE0OSwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTE0NzctYzBkOTViZTYtYWZhMy00MDdlLWJiMjktNWY0MGQyODE5ZjhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YTQxYmRjMmNiMDBkYjUyOGE0NGQ5ZWZhNzdjNzMzZmI3N2JhODg3OGY2MzFiMDYwZGYwNzNlYTk5NjhmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pmKFR8PUqaGmvccHn1bhgNfgMyXbU-u48qy6sWZATiY) [ ](https://private-user-images.githubusercontent.com/78434827/318651477-c0d95be6-afa3-407e-bb29-5f40d2819f8b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzg0NDksIm5iZiI6MTcxMjAzODE0OSwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTE0NzctYzBkOTViZTYtYWZhMy00MDdlLWJiMjktNWY0MGQyODE5ZjhiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YTQxYmRjMmNiMDBkYjUyOGE0NGQ5ZWZhNzdjNzMzZmI3N2JhODg3OGY2MzFiMDYwZGYwNzNlYTk5NjhmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pmKFR8PUqaGmvccHn1bhgNfgMyXbU-u48qy6sWZATiY)

这个问题我们得加一些限制了，不支持容器块下的标题拖拽，仅支持文档根节点下的直接标题子节点拖拽。

**Comment by 88250** [comment]
撤销这个问题不太确定是不是上面其他问题引起的 https://github.com/siyuan-note/siyuan/issues/10828#issuecomment-2031117282

**Comment by 88250** [comment]
> 层级6拖拽到层级3，会变成层级4

这个是设计如此，拖入到父级中后层级+1

**Comment by Vanessa219** [comment]
> 在特殊情况下大纲能被带走（在文档树拖拽文档时则不会发生这种情况）：
> 
> ![大纲3](https://private-user-images.githubusercontent.com/78434827/318654032-5e0db530-06cb-4500-9ab5-225adb409f00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDU1MDQsIm5iZiI6MTcxMjA0NTIwNCwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTQwMzItNWUwZGI1MzAtMDZjYi00NTAwLTlhYjUtMjI1YWRiNDA5ZjAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA4MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTA1ZDExOWQ2OWZkYTZmYzhmMDYzNDYxMThkN2I0NGJhNTA0NWY3ODI0NzQ2ZTVlZjE2ZGZmNjk4M2M1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zl6AO2bd2ajTRrXzBxTpq3Cnkq1BBekSG5aW0JTnMuA) [ ![大纲3](https://private-user-images.githubusercontent.com/78434827/318654032-5e0db530-06cb-4500-9ab5-225adb409f00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDU1MDQsIm5iZiI6MTcxMjA0NTIwNCwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTQwMzItNWUwZGI1MzAtMDZjYi00NTAwLTlhYjUtMjI1YWRiNDA5ZjAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA4MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTA1ZDExOWQ2OWZkYTZmYzhmMDYzNDYxMThkN2I0NGJhNTA0NWY3ODI0NzQ2ZTVlZjE2ZGZmNjk4M2M1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zl6AO2bd2ajTRrXzBxTpq3Cnkq1BBekSG5aW0JTnMuA) ](https://private-user-images.githubusercontent.com/78434827/318654032-5e0db530-06cb-4500-9ab5-225adb409f00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDU1MDQsIm5iZiI6MTcxMjA0NTIwNCwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTQwMzItNWUwZGI1MzAtMDZjYi00NTAwLTlhYjUtMjI1YWRiNDA5ZjAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA4MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTA1ZDExOWQ2OWZkYTZmYzhmMDYzNDYxMThkN2I0NGJhNTA0NWY3ODI0NzQ2ZTVlZjE2ZGZmNjk4M2M1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zl6AO2bd2ajTRrXzBxTpq3Cnkq1BBekSG5aW0JTnMuA) [ ](https://private-user-images.githubusercontent.com/78434827/318654032-5e0db530-06cb-4500-9ab5-225adb409f00.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDU1MDQsIm5iZiI6MTcxMjA0NTIwNCwicGF0aCI6Ii83ODQzNDgyNy8zMTg2NTQwMzItNWUwZGI1MzAtMDZjYi00NTAwLTlhYjUtMjI1YWRiNDA5ZjAwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA4MDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTA1ZDExOWQ2OWZkYTZmYzhmMDYzNDYxMThkN2I0NGJhNTA0NWY3ODI0NzQ2ZTVlZjE2ZGZmNjk4M2M1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zl6AO2bd2ajTRrXzBxTpq3Cnkq1BBekSG5aW0JTnMuA)

这个要怎么操作？

**Comment by 88250** [comment]
> 要拖拽到同级大纲下才能拖拽成功

这个演示没太看懂，我这里可以将 H1 拖入到 H2 中的，或者拖为 H2 的平级。

**Comment by TCOTC** [comment]
> > 在特殊情况下大纲能被带走（在文档树拖拽文档时则不会发生这种情况）
>
> 这个要怎么操作？

我是在拖拽的过程中用快捷键唤起 [PixPin](https://pixpinapp.com/) 截图

**Comment by TCOTC** [comment]
> > > 要拖拽到同级大纲下才能拖拽成功
> > 
> > 
> > 这个演示没太看懂，我这里可以将 H1 拖入到 H2 中的，或者拖为 H2 的平级。
> 
> 现在懂了，不用再补充了，多谢。

我刚录完：

![截图](https://github.com/siyuan-note/siyuan/assets/78434827/04463e5c-b1e0-421d-95f8-c0ac2c7ae16c)

**Comment by TCOTC** [comment]
@88250 什么时候发个dev版看看？

**Comment by 88250** [comment]
我现在打一个，稍等。

**Comment by TCOTC** [comment]
应该插入到标题与标题前一个块的中间，而不是把前面的块包进去：

![标题](https://github.com/siyuan-note/siyuan/assets/78434827/828639d7-b3ff-49a0-bb8f-f4e2c4204b9e)

**Comment by TCOTC** [comment]
这里还有点问题：

![拖拽](https://github.com/siyuan-note/siyuan/assets/78434827/c94e8196-33a7-46f4-b181-9b2a17a1a64b)

**Comment by 88250** [comment]
> 应该插入到标题与标题前一个块的中间，而不是把前面的块包进去：
> 
> ![标题](https://private-user-images.githubusercontent.com/78434827/318832527-828639d7-b3ff-49a0-bb8f-f4e2c4204b9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzA5NzMsIm5iZiI6MTcxMjA3MDY3MywicGF0aCI6Ii83ODQzNDgyNy8zMTg4MzI1MjctODI4NjM5ZDctYjNmZi00OWEwLWJiOGYtZjRlMmM0MjA0YjllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYjdhZTAxODU2MWFjNDBlNzA2YzA5YjA0ZGQ3M2M3NDc1ZTZjN2M0ODRmM2Y1NTM4ZjFiMmIxNjdkNmEwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Oj6PFEchBQLQxF1ipXFaTU_VyvYAeJphAB3gsF4-zA) [ ![标题](https://private-user-images.githubusercontent.com/78434827/318832527-828639d7-b3ff-49a0-bb8f-f4e2c4204b9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzA5NzMsIm5iZiI6MTcxMjA3MDY3MywicGF0aCI6Ii83ODQzNDgyNy8zMTg4MzI1MjctODI4NjM5ZDctYjNmZi00OWEwLWJiOGYtZjRlMmM0MjA0YjllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYjdhZTAxODU2MWFjNDBlNzA2YzA5YjA0ZGQ3M2M3NDc1ZTZjN2M0ODRmM2Y1NTM4ZjFiMmIxNjdkNmEwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Oj6PFEchBQLQxF1ipXFaTU_VyvYAeJphAB3gsF4-zA) ](https://private-user-images.githubusercontent.com/78434827/318832527-828639d7-b3ff-49a0-bb8f-f4e2c4204b9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzA5NzMsIm5iZiI6MTcxMjA3MDY3MywicGF0aCI6Ii83ODQzNDgyNy8zMTg4MzI1MjctODI4NjM5ZDctYjNmZi00OWEwLWJiOGYtZjRlMmM0MjA0YjllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYjdhZTAxODU2MWFjNDBlNzA2YzA5YjA0ZGQ3M2M3NDc1ZTZjN2M0ODRmM2Y1NTM4ZjFiMmIxNjdkNmEwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Oj6PFEchBQLQxF1ipXFaTU_VyvYAeJphAB3gsF4-zA) [ ](https://private-user-images.githubusercontent.com/78434827/318832527-828639d7-b3ff-49a0-bb8f-f4e2c4204b9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzA5NzMsIm5iZiI6MTcxMjA3MDY3MywicGF0aCI6Ii83ODQzNDgyNy8zMTg4MzI1MjctODI4NjM5ZDctYjNmZi00OWEwLWJiOGYtZjRlMmM0MjA0YjllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1MTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYjdhZTAxODU2MWFjNDBlNzA2YzA5YjA0ZGQ3M2M3NDc1ZTZjN2M0ODRmM2Y1NTM4ZjFiMmIxNjdkNmEwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Oj6PFEchBQLQxF1ipXFaTU_VyvYAeJphAB3gsF4-zA)

这个应该没有问题，因为之前的第一部分上方没有标题块，所以把标题块放到最上面以后就会包括它。

**Comment by TCOTC** [comment]
> > 应该插入到标题与标题前一个块的中间，而不是把前面的块包进去：
> 
> 这个应该没有问题，因为之前的第一部分上方没有标题块，所以把标题块放到最上面以后就会包括它。

我觉得不对，一般不会在开头放标题的，写文章开头一般先有一部分引言，然后才是第一个标题

**Comment by TCOTC** [comment]
> > 这里还有点问题：
> 
> 这个演示没看明白，能否帮忙用个简单的测试用例再演示一下，谢谢。

1. 把 02 拖到 01 下变成子标题（没问题）
2. 把 02 拖到与 01 同级的下方时，把刚才与 02 同级的 3、4、5 也一起带走了（有问题）
3. 此时撤回，没有恢复到产生问题之前的状态（有问题）

**Comment by 88250** [comment]
> > > 这里还有点问题：
> > 
> > 
> > 这个演示没看明白，能否帮忙用个简单的测试用例再演示一下，谢谢。
> 
> 1. 把 02 拖到 01 下变成子标题（没问题）
> 2. 把 02 拖到与 01 同级的下方时，把刚才与 02 同级的 3、4、5 也一起带走了（有问题）
> 3. 此时撤回，没有恢复到产生问题之前的状态（有问题）

懂了，多谢！

**Comment by TCOTC** [comment]
拖拽一次之后有段时间是用来排序的，此时进行下一次拖拽操作，在大纲刷新之后鼠标拖着的标题就看不见了：

![阻止](https://github.com/siyuan-note/siyuan/assets/78434827/550df5e6-c2b2-432b-a16c-642308ae0344)

**Comment by 88250** [comment]
@Vanessa219 界面可能需要阻塞一下。

**Comment by TCOTC** [comment]
@Vanessa219 感觉应该还能再优化一下：

![优化](https://github.com/siyuan-note/siyuan/assets/78434827/2d30514a-8da5-4d95-a1af-5f6ed2208dc5)

![优化](https://github.com/siyuan-note/siyuan/assets/78434827/022fdf64-ab10-4415-acc6-3db771a02776)

**Comment by Vanessa219** [comment]
没看明白

**Comment by TCOTC** [comment]
1. 标题正在排序的过程中，编辑文档会被吞字，排序的过程中应该阻止编辑文档
2. 拖拽大纲之后，排序的过程中仍然可以拖拽大纲，但要等到排完序之后才显示拖拽的是哪一条。排序的过程中应该阻止拖拽
