### ISSUE TITLE
在默认编辑器中打开

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1083]
有的时候需要对MarkDown进行直接的修改

就需要在默认的编辑器中打开当前文件

但目前好像没有这个快捷键，这就导致打开的过程比较繁琐

希望能够提供在默认编辑器中打开的选项

当然也可以配置编辑器以及新命令行参数，以便实现更灵活的功能，比如说在某个特定的编辑系统打开，而且直接跳转到某一行

另一个解决方案是提供源代码模式，但是这个提议好像已经被否决了

那么这个功能就显得非常重要了

**Comment by wo4wangle** [comment]
n早前我就提出这个了，大家想法都是差不多的其实

**Comment by roverway** [comment]
源码模式就是思源的专家模式，还在路线图里

**Comment by 88250** [comment]
你好，请关注 https://github.com/siyuan-note/siyuan/issues/868
