### ISSUE TITLE
支持按需同步配置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10831]
背景 https://github.com/siyuan-note/siyuan/issues/8806#issuecomment-2031169900

快捷键、外观、同步、搜索、闪卡、AI 等

**Comment by TCOTC** [comment]
关联导出导入配置：#10617

**Comment by 88250** [comment]
配置同步风险较高（比如数据冲突），不打算支持了。

后续仅提供手动导入导出 https://github.com/siyuan-note/siyuan/issues/10617
