### ISSUE TITLE
Database relation field Ctrl+Hover not open the floating window

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10836]
数据库关联列 Ctrl + 悬停 无效

### In what scenarios do you need this feature?

1. 更方便跳转到关联的数据库
2. 在数据库关联列中为关联的数据库创建新的行
3. 鼠标悬停时跳转并定位到关联数据库 (的对应的那一行)
4. 关联列支持自定义排序 #10835

### 1. 更方便跳转到关联的数据库

![image](https://github.com/siyuan-note/siyuan/assets/78434827/eb5cce56-c2da-46d2-b8e8-6eccb3d79237)

### 2. 在数据库关联列中为关联的数据库创建新的行：

![Notion](https://github.com/siyuan-note/siyuan/assets/78434827/d6d9b52b-318f-4a07-a382-121b7b2fdaaf)

### 3. 跳转并定位到关联数据库对应的那一行：（修改了一下）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e214860c-f200-40e6-b17f-5a5dae7aa3a1)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d545fc91-2986-49f2-8ced-a317f1ddfed3)

### Other information

参考了油管视频 https://www.youtube.com/watch?v=ZdUanaWigkY

**Comment by TCOTC** [comment]
> 支持改进前两点，第三点思源已经可以直接悬浮窗显示

要怎么操作？能录屏说明一下吗？

**Comment by 5kyfkr** [comment]
> > 支持改进前两点，第三点思源已经可以直接悬浮窗显示
> 
> @5kyfkr 要怎么操作？能录屏说明一下吗？

是不是开了按下ctrl键才显示悬浮窗，我这边没开，直接鼠标移上去关联文档就会有浮窗
![image](https://github.com/siyuan-note/siyuan/assets/63196026/a35fdab8-2c47-43ad-a672-0a36bf2095aa)

**Comment by TCOTC** [comment]
> > > 支持改进前两点，第三点思源已经可以直接悬浮窗显示
> > 
> > @5kyfkr 要怎么操作？能录屏说明一下吗？
> 
> 是不是开了按下ctrl键才显示悬浮窗，我这边没开，直接鼠标移上去关联文档就会有浮窗
> 

确实是开了，但我这边即使按下了 Ctrl 也不会悬浮显示

**Comment by 5kyfkr** [comment]
> > 是不是开了按下ctrl键才显示悬浮窗，我这边没开，直接鼠标移上去关联文档就会有浮窗
> 
> 确实是开了，但我这边即使按下了 Ctrl 也不会悬浮显示

测试了是bug，选择悬停能正常打开，选择了按下ctrl悬停浏览无法显示

**Comment by TCOTC** [comment]
> > > 是不是开了按下ctrl键才显示悬浮窗，我这边没开，直接鼠标移上去关联文档就会有浮窗
> > 
> > 
> > 确实是开了，但我这边即使按下了 Ctrl 也不会悬浮显示
> 
> 测试了是bug，选择悬停能正常打开，选择了 按住ctrl悬停 则无法显示

@Vanessa219

**Comment by TCOTC** [comment]
> 支持改进前两点，第三点思源已经可以直接悬浮窗显示

@5kyfkr 我试了一下，你说支持「悬浮窗显示」的是主键关联的那个文档，而我的需求是「跳转并定位到关联数据库对应的那一行」，所以还是不行

**Comment by 5kyfkr** [comment]
> > 支持改进前两点，第三点思源已经可以直接悬浮窗显示
> 
> @5kyfkr 我试了一下，你说支持「悬浮窗显示」的是主键关联的那个文档，而我的需求是「跳转并定位到关联数据库对应的那一行」，所以还是不行

这个有点难度，试了notion也没有这样跳转的能力

**Comment by TCOTC** [comment]
> > > 支持改进前两点，第三点思源已经可以直接悬浮窗显示
> > 
> > 我试了一下，你说支持「悬浮窗显示」的是主键关联的那个文档，而我的需求是「跳转并定位到关联数据库对应的那一行」，所以还是不行
> 
> 这个有点难度，试了notion也没有这样跳转的能力，现在的逻辑就是直接打开对应的文档了

Notion 是点击之后直接打开页面的，但思源的数据库没有页面这个概念，所以只能看看能不能是「跳转并定位到关联数据库对应的那一行」

**Comment by 88250** [comment]
拆分了一下，前两点近期应该可以改进，第三点中对于未绑定块行的定位较为困难，要考虑分页加载的情况，对于已绑定块行悬浮块目前已经支持（Ctrl 悬停的问题 @Vanessa219 看一下 ）。

1. https://github.com/siyuan-note/siyuan/issues/10915
2. https://github.com/siyuan-note/siyuan/issues/10914
3. https://github.com/siyuan-note/siyuan/issues/10916
