### ISSUE TITLE
Abnormal sorting of database relation fields

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10835]
关联列支持自定义排序

### In what scenarios do you need this feature?

[测试用文档.sy.zip](https://github.com/siyuan-note/siyuan/files/14834050/sy.zip)

目前的排序有点问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9ce8dbd9-4137-4a38-826f-08678e437e67)

### Describe the optimal solution

希望可以像多选列一样给已经关联的排序

多选列的排序：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/033841dd-6af7-452d-98ef-aca05da6aa7e)

目前的关联列没有排序：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/abd17652-9962-4893-a901-e3c730146dc5)

**Comment by 88250** [comment]
关联值目前是按 string 排序的，因为主键内容是文本的，但如果能转换 number 就按数字排序。

上面的数据排序异常是因为判断是否是编辑过的数据的时候有问题，我们先解决这个 bug。
