### ISSUE TITLE
Side panel auto hide on the mobile

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10837]
https://ld246.com/article/1712033763001

**Comment by Vanessa219** [comment]
f5b7def958fddf9ebf2d0b9a52e57e0df42af5e2

**Comment by 5kyfkr** [comment]
哪里下apk呀，release里没有

**Comment by 88250** [comment]
移动端没有 dev 版，还是得等正式版。

**Comment by 88250** [comment]
移动端没做自动打包，如果能有 GitHub Action 打包的话就好了，得等个大佬来支持一下 😂

**Comment by 5kyfkr** [comment]
> 移动端没做自动打包，如果能有 GitHub Action 打包的话就好了，得等个大佬来支持一下 😂

相当于打包移动端要花几小时以上吗，我一直以为action打包docker版也会顺便打包apk  (○o○)

**Comment by 88250** [comment]
本地只打 apk 的话可能 5 分钟吧。

**Comment by 5kyfkr** [comment]
> 本地只打 apk 的话可能 5 分钟吧。

听着还好吧，像这个主菜单日常经常用的地方的bug感觉可以发一个

**Comment by 88250** [comment]
考虑到商店版更新的用户签名可能不适用，所以最好还是不发吧，不然要卸载安装才能用的。

**Comment by 88250** [comment]
对，我想起来了，之前好像有人帮忙试过 GitHub Action 打包，签名这里有问题。

**Comment by 5kyfkr** [comment]
> 对，我想起来了，之前好像有人帮忙试过 GitHub Action 打包，签名这里有问题。

好吧，那除非升版本号到3.0.7才行了吧，那就等等吧

**Comment by 5kyfkr** [comment]
> 或者这个版本我们手动上传一个……

也可以考虑，急的就来这下个

**Comment by 88250** [comment]
呃，这次打包构建太慢了，现在还在打着……

**Comment by 5kyfkr** [comment]
> 呃，这次打包构建太慢了，现在还在打着……

不慌，不死机就行

**Comment by 88250** [comment]
被 Defender 卡了半天 😓 刚刚已经上传到最新的 dev 版 release 中了。

**Comment by 88250** [comment]
试试卸载重装。

**Comment by 5kyfkr** [comment]
> 试试卸载重装，版本号没有变，前端资源不会覆盖。

卸载重装好了，了解

**Comment by Soltus** [comment]
安卓打包action就是签名的问题
