### ISSUE TITLE
数据插入异常问题

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#10839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我在一个文档的结尾加了两段内容，突然思源刷新了一下，内容没有了，自己看发现内容突然被移到最开始的位置了。
辛苦D大排查下。

### Expected result

希望修复

### Version environment

```markdown
- Version: 3.0.6
- Operating System: windows 11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14835242/system-log.zip)
[命令.sy.zip](https://github.com/siyuan-note/siyuan/files/14835256/sy.zip)

**Comment by woniuxia** [comment]
稳定复现 

https://github.com/siyuan-note/siyuan/assets/16383685/c6e275a8-aa68-4953-a719-cc0f5f6d52e4

**Comment by 88250** [comment]
这个大纲点击的问题在 https://github.com/siyuan-note/siyuan/issues/10828 中修复，谢谢。
