### ISSUE TITLE
编辑文档过程中弹出「正在打开，请稍等…」

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

排查了半天，发现只要关闭 WakaTime 插件就不会再弹通知

在编辑数据库多选列时尤其频繁：

![插件](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-wakatime/assets/78434827/da66d50d-a5fe-4af3-87b3-013e537700e8)

### Expected result

已知在打开用户指南的时候会弹，但我想知道我的这个情况是什么造成的

### Version environment

```markdown
- Version: 3.0.6
- Operating System: Win10
- Browser (if used):
```

### Log file

无

### More information

关联：https://github.com/Zuoqiu-Yingyi/siyuan-plugin-wakatime/issues/24

**Comment by TCOTC** [comment]
日志：[system-log.zip](https://github.com/siyuan-note/siyuan/files/14835385/system-log.zip)

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/10772 中改进的，如果传入的块 id 在索引中找不到，则会在文件系统上遍历搜索一次以便自动建立索引。

测试了下，应该是因为编辑表格的时候插件会调用 getBlockInfo，但是传入的 id 不是块 id 导致的：

![image](https://github.com/siyuan-note/siyuan/assets/873584/d6af6a40-c43a-45e6-ac35-f5167036702a)

**Comment by 88250** [comment]
我先关闭了，麻烦 @Zuoqiu-Yingyi 抽空看下，谢谢。
