### ISSUE TITLE
Database rollup calculation misses null values

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10843]
数据库汇总关联列已完成占比与真实数据不一致

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库汇总关联列已完成占比与真实数据不一致

### Expected result

同步

### Screenshot or screen recording presentation

![PixPin_2024-04-02_23-05-22.gif](https://img2.imgtp.com/2024/04/02/hJkyj9qs.gif)

### Version environment

```markdown
- Version: 3.0.6
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/14839120/system-log.1.zip)

**Comment by TCOTC** [comment]
可以复现

**Comment by 88250** [comment]
> 可以复现

可否帮忙导出一个数据集以便测试，谢谢。

**Comment by TCOTC** [comment]
> > 可以复现
> 
> 可否帮忙导出一个数据集以便测试，谢谢。

好奇怪，这个数值只要从100变成了50之后就再也变不回100了，应该导出也没用

**Comment by TCOTC** [comment]
大概就是这样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b83f1d3e-4b90-452f-91b6-fcedbdf0ad70)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1447295e-5e20-49ca-9b7c-6ea5ad5bd050)

**Comment by 88250** [comment]
我这里测试似乎正常：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/31a74e72-ed46-44cd-b86f-df1852edf55b)

**Comment by TCOTC** [comment]
又复现了，我试试看导出行不行

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4e30c742-1d0d-44c5-a977-8d24f9f09fa8)

**Comment by 88250** [comment]
这种情况下 F5 刷新会恢复正常么？

**Comment by TCOTC** [comment]
[高考数据库.sy.zip](https://github.com/siyuan-note/siyuan/files/14839597/sy.zip)

刷新也不会恢复

**Comment by 88250** [comment]
导入后能够重现了，但是点击以后会恢复，稍后排查，感谢。

**Comment by TCOTC** [comment]
@AvoidantPerDis 你的数据库中「进度」列的模板代码可以分享一下吗？那个进度条很棒的亚子

**Comment by TCOTC** [comment]
> > 你的数据库中「进度」列的模板代码可以分享一下吗？那个进度条很棒的亚子
> 
> 我从链滴毛的https://ld246.com/article/1708829169284

感谢 @AvoidantPerDis 

```
.action{$a:= index . "考点进度" }
.action{$b:= 100 }
.action{$c:= mul $a 100}
.action{$d:= div $c $b}
<span style="background-color: rgba(175,184,193,0.2); width: 100%; display: inline-block;height: 12px;border-radius: 6px;align-self: center;overflow: hidden;">
    <span style="text-align: right; font-size: 12px; width: .action{$d}%; background-color: rgb(45,164,78); display: inline-block;height: inherit;vertical-align: top;"></span>
</span>
```

**Comment by AvoidantPerDis** [comment]
> > > 你的数据库中「进度」列的模板代码可以分享一下吗？那个进度条很棒的亚子
> > 
> > 我从链滴毛的https://ld246.com/article/1708829169284
> 
> 感谢 @AvoidantPerDis 
> 
> ```
> .action{$a:= index . "考点进度" }
> .action{$b:= 100 }
> .action{$c:= mul $a 100}
> .action{$d:= div $c $b}
> <span style="background-color: rgba(175,184,193,0.2); width: 100%; display: inline-block;height: 12px;border-radius: 6px;align-self: center;overflow: hidden;">
>     <span style="text-align: right; font-size: 12px; width: .action{$d}%; background-color: rgb(45,164,78); display: inline-block;height: inherit;vertical-align: top;"></span>
> </span>
> ```

能写个渐变色吗？我小白

**Comment by TCOTC** [comment]
> 能写个渐变色吗？我小白

@AvoidantPerDis 你想怎样渐变？

**Comment by AvoidantPerDis** [comment]
> > 能写个渐变色吗？我小白
> 
> @AvoidantPerDis 你想怎样渐变？

跟热力图那样不同程度不同深浅的绿色

**Comment by TCOTC** [comment]
> > > 能写个渐变色吗？我小白
> > 
> > 
> > 你想怎样渐变？
> 
> 跟热力图那样不同程度不同深浅的绿色

@AvoidantPerDis 这种吗，"考点进度"的数值越接近100，进度条就越绿：

你可以试试看

```
.action{$a:= index . "考点进度" }
.action{$b:= 100 }
.action{$c:= mul $a 100}
.action{$d:= div $c $b}
.action{$e:= addf (mulf (divf $d 100) 0.8) 0.2}
<span style="background-color: rgba(175,184,193,0.2); width: 100%; display: inline-block;height: 12px;border-radius: 6px;align-self: center;overflow: hidden;">
    <span style="text-align: right; font-size: 12px; width: .action{$d}%; background-color: rgba(45,164,78,.action{$e}); display: inline-block;height: inherit;vertical-align: top;"></span>
</span>
```

**Comment by AvoidantPerDis** [comment]
> > > > 能写个渐变色吗？我小白
> > > 
> > > 
> > > 你想怎样渐变？
> > 
> > 
> > 跟热力图那样不同程度不同深浅的绿色
> 
> @AvoidantPerDis 这种吗，"考点进度"的数值越接近100，进度条就越绿：
> 
> 你可以试试看
> 
> ```
> .action{$a:= index . "考点进度" }
> .action{$b:= 100 }
> .action{$c:= mul $a 100}
> .action{$d:= div $c $b}
> .action{$e:= addf (mulf (divf $d 100) 0.8) 0.2}
> <span style="background-color: rgba(175,184,193,0.2); width: 100%; display: inline-block;height: 12px;border-radius: 6px;align-self: center;overflow: hidden;">
>     <span style="text-align: right; font-size: 12px; width: .action{$d}%; background-color: rgba(45,164,78,.action{$e}); display: inline-block;height: inherit;vertical-align: top;"></span>
> </span>
> ```

有效的谢谢
