### ISSUE TITLE
文档树更多按钮提示闪烁

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10840]
### Describe the problem

其他按钮没试过，只是偶然发现文档树的更多按钮有这个问题

特殊角度特殊位置：

![闪烁](https://github.com/siyuan-note/siyuan/assets/78434827/7bb2f5aa-69c1-4cc8-9911-21f1bc4229a3)

### Version environment

```markdown
- Version: 3.0.6
- Operating System: Win10
- Browser (if used):
```

**Comment by 88250** [comment]
我这里试了几次重现不了 :joy:

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/8d1d9475-094a-4bc1-8425-fd36d8a65181)

[issue1.webm](https://github.com/siyuan-note/siyuan/assets/873584/550e3254-8e12-421a-b7c6-95895b8c2b80)

**Comment by TCOTC** [comment]
用 `Ctrl` + `+` 把界面调到最大再试试？

我这里很容易复现

![image](https://github.com/siyuan-note/siyuan/assets/78434827/06cf2ce7-60d0-4a84-b8d4-0d2b274cbe0d)

**Comment by 88250** [comment]
调大以后我这里在光标延边缘微量移动的情况下会出现闪烁 @Vanessa219
