### ISSUE TITLE
Improve block ref search ID extraction

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10848]
https://github.com/siyuan-note/siyuan/issues/10690

**Comment by TCOTC** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/cf2c3cf9-8d1f-4765-a8c3-5432b0a6ca4b)

**Comment by 88250** [comment]
理论上只要包含了 ID 格式的都行。

**Comment by TCOTC** [comment]
那如果粘贴了两个 ID ，是不是能搜出两个块？

**Comment by 88250** [comment]
只返回第一个
