### ISSUE TITLE
Database primary key supports unbinding block

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10849]
数据库主键支持取消关联

### In what scenarios do you need this feature?

数据库主键从纯文本变成关联某个块之后，就无法取消关联恢复为纯文本了

### Describe the optimal solution

取消关联时保留关联的块名称为纯文本。举个例子就是下面这个关联的文档，取消关联之后仍然保留文档名，而不是直接清空主键

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ee7b350b-ab47-49a5-a0ae-28e7385180b0)

**Comment by 5kyfkr** [comment]
支持，这个可以弄
