### ISSUE TITLE
插件 API 请求 | Protyle 对象添加 `clearSlash` 方法

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#10841]
### In what scenarios do you need this feature?

有时候我使用 `/` 命令只是为了触发一些特定的命令，不打算插入任何东西。

不过我尝试 `insert('')` 发现不起作用，经过弘哥的提醒后发现可以使用 `protyle.insert(window.Lute.Caret, false, false);` ，在不插入任何东西的情况下清理掉 `/xxx` 文本。

但是我觉得这种非常常见的操作最好还是显示提供一个 API。

### Describe the optimal solution

提供 `protyle.clearSlash` 方法，作用是清理掉前面的 `/xxx` 内容。

**Comment by Vanessa219** [comment]
用 protyleSlash 不会清空么？

**Comment by frostime** [comment]
> 用 protyleSlash 不会清空么？

我是说清空编辑器里面输入的这部分内容：
![image](https://github.com/siyuan-note/siyuan/assets/27268127/66d6cf46-4c0a-4e65-896b-eb454fde24e7)

**Comment by Vanessa219** [comment]
这部分内容需要使用 protyleSlash ，没有方法可以提供。可以看一下事例。
