### ISSUE TITLE
Improve flashcard menu

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10857]
### Describe the problem

这个「快速制卡」太显眼了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2f3fab15-18c4-404b-85ee-b7e7967ec298)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b3383109-3859-4fba-a057-970a62f9a455)

### Version environment

```markdown
- Version: 3.0.7
- Operating System: Win10
- Browser (if used):
```

**Comment by Vanessa219** [comment]
这样么？

<img width="176" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/c2bae25a-cb41-4010-bb4a-3003247dbb83">

**Comment by TCOTC** [comment]
感觉要不改成「删除制卡」？「取消快速制卡」怪怪的

**Comment by TCOTC** [comment]
> 然后我有个问题，在文档树上的这个快速制卡是做什么用的？

原来是把整个文档作为一个闪卡。不如叫「文档制卡」更直观点

**Comment by TCOTC** [comment]
> 应该是写漏了。

不对，我研究了一下，其他地方的「快速制卡」点一下是制卡，点第二下是取消制卡，只有文档树上的这两个操作是分开的。

其他地方的操作是合并的，是因为这两个地方需要打开文档才能点击，而打开文档就知道当前文档是否制卡了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1853c98b-7ad6-4312-a2b1-5ad921086e81)

文档树上的不合并是因为没打开文档的情况下不知道该文档是否已经制卡，所以点击「快速制卡」就能确保文档被制卡、点击「取消快速制卡」就能确保文档不被制卡

**Comment by TCOTC** [comment]
所以就只是这个外观有点问题，功能没有问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2f3fab15-18c4-404b-85ee-b7e7967ec298)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f414247a-2939-4943-ae45-5ed3f0ef912b)

**Comment by Vanessa219** [comment]
当初好像是这么想来着，还没看代码。那就先改一下文案为"移除闪卡"
