### ISSUE TITLE
/api/export/exportResources无法导出目录

### ISSUE THREAD

**Issue by tengfei-xy** [siyuan-note/siyuan#10852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在[文档](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md)里给出示例参数有 `"/conf/appearance/boot",`但我试了下，

命令

```bash
curl -s 'http://127.0.0.1:49334/api/export/exportResources' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://127.0.0.1:49334' \
  -H 'Referer: http://127.0.0.1:49334/stage/build/desktop/?r=behyr4s' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  --data-raw '{"path":["/conf/appearance/boot"],"name":"boot"}' | jq
```

返回

```bash
{
  "code": 0,
  "msg": "",
  "data": {
    "path": "temp/export/boot.zip"
  }
}
```

这个boot.zip解压后，仅有 `boot`文件夹，而没有 `/conf/appearance/boot`文件夹下的任何文件。

对于以下命令，执行后也没有文件

```bash
  curl -s 'http://127.0.0.1:49334/api/export/exportResources' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://127.0.0.1:49334' \
  -H 'Referer: http://127.0.0.1:49334/stage/build/desktop/?r=behyr4s' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  --data-raw '{"path":["/conf/appearance/boot","/conf/appearance/boot/icon.png"],"name":"boot"}' | jq

```

### Expected result

给出的参数如果是文件，是压缩文件吧？
给出的参数如果是文件夹，是压缩文件夹和里面的每个文件吧？

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/61930212/ce768bc7-778f-47e6-a33b-e7da5ccca7a6

### Version environment

```markdown
- Version: 
    3.0.6
- Operating System: 
    System Version: macOS 14.4 (23E214)
    Kernel Version: Darwin 23.4.0
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14848149/siyuan.log)

**Comment by tengfei-xy** [comment]
不好意思，请求参数应该是paths，写错了，不过对于path这个参数都能生成压缩包，，emmm

**Comment by tengfei-xy** [comment]
提交了个pr请求，来让path和paths同义，https://github.com/siyuan-note/siyuan/pull/10855

**Comment by 88250** [comment]
后续我们在 PR 上讨论，感谢反馈和贡献。
