### ISSUE TITLE
Allow to have templates with links to a database

### ISSUE THREAD

**Issue by alexjp** [siyuan-note/siyuan#10856]
### In what scenarios do you need this feature?

Hi,

While using SiYuan more, I have stumbled upon a nice workflow for tasks/project management.

* I create a global `Tasks database` with columns `status`, `priority`, `schedule`, etc.
* I create a simple todo (Ctrl+L)
* Add it to the database and set fields like `status`, `priority`, etc.

This is awesome, but the issue is the amount of work it needs.

I was thinking making it easier by using templates, creating a template with a single todo (Ctrl+L) added to a database and some fields already selected (like image below):

![Screenshot_20240403_110139](https://github.com/siyuan-note/siyuan/assets/85806/1c8459dd-c916-435d-ab11-3ac51aea9cec)

But this does not seem to work, since when using the template, the new todo line is not linked to the database.

Could templates have linked databases, or a simpler method to create linked auto filled todo items?

Thanks!!!

### Describe the optimal solution

I would only have to select between "task templates" that would already be linked to the "Tasks database" and have already selected values for some fields

### Describe the candidate solution

Allow templates to apply also database link and selected values on field.

### Other information

Thank you!

**Comment by 88250** [comment]
Hello, you can implement default value filling by adding different filter views.

[issue.webm](https://github.com/user-attachments/assets/de2bf039-b8b9-4253-8024-77e923a448e7)
