### ISSUE TITLE
Android 端支持打开 data 文件夹下的笔记本

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1085]
内核 ls `/sdcard/siyuan/data/` 下的文件夹作为笔记本路径，前端按需选择。

**Comment by Tregyn-cc** [comment]
后续会支持选择指定的手机文件夹嘛

**Comment by 88250** [comment]
@Tregyn-cc 暂时不会做。

**Comment by Tregyn-cc** [comment]
> @Tregyn-cc 暂时不会做。

okk，D大注意身体哈哈

**Comment by 88250** [comment]
@Tregyn-cc 正准备躺下，晚安 :)

**Comment by Tregyn-cc** [comment]
> @Tregyn-cc 正准备躺下，晚安 :)

晚安啦

**Comment by Tregyn-cc** [comment]
> 后续会支持选择指定的手机文件夹嘛

@88250 已用 Folder Sync这个app暂时满足这个功能，可以自动实现安卓手机两个文件夹之间的映射

**Comment by HowcanoeWang** [comment]
> @Tregyn-cc 暂时不会做。

安卓13之后似乎不支持跨应用访问数据了，能不能支持自定义工作空间文件夹？

PS：似乎安卓端不支持多工作空间，也不能打开工作空间？（2.9.9版本的安卓）

**Comment by 88250** [comment]
@HowcanoeWang 不支持自定义工作空间路径；可以在右侧面板 关于 中设置多个工作空间。

**Comment by HowcanoeWang** [comment]
> @HowcanoeWang 不支持自定义工作空间路径；可以在右侧面板 关于 中设置多个工作空间。

手机端确实有多个空间且无法指定路径 (屏蔽文件夹选择的考虑是什么？防止用户随手删除数据？)

在平板模式下似乎没有多个工作空间的选项？

![image](https://github.com/siyuan-note/siyuan/assets/19968935/a07e6a67-2225-49c7-a902-9e71c02c3c74)

**Comment by 88250** [comment]
@HowcanoeWang 避免第三方网盘/软件同步文件系统造成数据损坏，Pad 下切换工作空间会在 https://github.com/siyuan-note/siyuan/issues/8948 中支持。
