### ISSUE TITLE
Creating a new block may cause the tab to close

### ISSUE THREAD

**Issue by tcmtom** [siyuan-note/siyuan#10851]
粘贴少量文字后页面闪退

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，除此之外
更新到3.0.6后，在文档最后一行回车，右上角会闪出疑似block not found的横条（闪得太快）看不到内容

### Expected result

不闪退

### Version environment

```markdown
- Version: 3.0.6
- Operating System: 
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/14847868/system-log.1.zip)

**Comment by 88250** [comment]
这个问题在最新版应该已经解决，麻烦测试，如果还有问题请继续反馈，我先关闭了。

**Comment by AvoidantPerDis** [comment]
希望dev1就能修复，太难受了

**Comment by AvoidantPerDis** [comment]
右上角会闪出疑似block not found的横条的bug我也遇到了
