### ISSUE TITLE
Creating new content block triggers 'search content block does not exist' error.

### ISSUE THREAD

**Issue by KhunHnao** [siyuan-note/siyuan#10862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Happens especially when page is long, yellow text that says 'search content block does not exist' appears and app cannot be used until refreshed.

### Expected result

To continue typing as usual

### Screenshot or screen recording presentation

https://streamable.com/gwp1bk

### Version environment

```markdown
- Version: Siyuan 3.0.6
- Operating System: Android
- Browser (if used):
```

### Log file

n/a

### More information

n/a

**Comment by 88250** [comment]
Please update to the latest version. This problem should have been fixed. If you still encounter this problem in the new version, please continue to feedback. We close this issue now. Thank you.
