### ISSUE TITLE
Database column width adjustment fails

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#10865]
数据库每列的宽度都不可以调整了，会自动变成默认宽度……

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库每列的宽度都不可以调整了，会自动变成默认宽度……
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/c774bf96-3ea0-4dbd-b982-c6b4b3e62bf9)

### Expected result

……

### Version environment

```markdown
- Version: 3.0.7
- Operating System: Windows 11 24H2
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/14853707/system-log.zip)

**Comment by TCOTC** [comment]
@88250 这个问题有点烦，要不先发个dev版？

**Comment by 88250** [comment]
明早吧，谢谢，晚安。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Fri, Apr 5, 2024 00:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database column width adjustment fails(Issue #10865)




 
@88250 这个问题有点烦，要不先发个dev版？
