### ISSUE TITLE
单元格外观改进

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10867]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/970828/319250340-e1471313-72e2-45c7-94a9-4ee7d874d14b.png">

![image](https://github.com/siyuan-note/siyuan/assets/78434827/0dd309c1-696a-40fd-a6dd-6c9eb4fe0c24)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/10829#issuecomment-2034241790_

**Comment by TCOTC** [comment]
这里的圆角也有问题：

![image](https://github.com/user-attachments/assets/9c38d9d5-a327-40d4-b80a-8f8899387559)

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/pull/13435

**Comment by Badboyboom** [comment]
****
