### ISSUE TITLE
大纲移动时出现问题

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#10860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1.大纲容易移动到最上面
2.大纲移动层次不明确，容易归到其他标题下

### Expected result

1

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/107289739/65c435d8-f057-477c-b947-b89f51a7aad3

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14851925/siyuan.log)

**Comment by 88250** [comment]
请升级到最新版，应该已经修复。
