### ISSUE TITLE
Incorporating a reading comments mode can be considered

### ISSUE THREAD

**Issue by hualr** [siyuan-note/siyuan#10868]
### In what scenarios do you need this feature?

When users try to read a note, they can comment and view previous comments, similar to Word's comment mode. This way, every time they review the notes, users can see the previous comment information. I personally believe that notes are not only for writing, but frequent reading after writing is also a key part of learning.

### Describe the optimal solution

1. Firstly, in read-only mode, support adding comments, highlighting, underlining, etc.

2. In non-editable mode, it would be great to quickly see previous comment information, similar to the experience in Kindle reading software.

### Describe the candidate solution

Why not consider referencing the reading mode of Amazon Kindle's Android app?

**Comment by TCOTC** [comment]
在只读模式下不应该允许编辑文档，要做也只能再增加一个模式了，但那样就太多了。

我的建议是之后优化移动端编辑模式的体验。

**Comment by zongqir** [comment]
只读模式应该是禁止编辑
阅读模式是允许对阅读场景下的编辑
确实手机非常有用 我也赞同出个类似阅读模式的场景
类似于微信读书就好了

**Comment by 88250** [comment]
We are not considering adding this mode, thanks for the suggestion.
不考虑增加这个模式了，感谢提议。
