### ISSUE TITLE
Auto verify the database name when clicking the block superscript icon

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10861]
https://ld246.com/article/1712136527080

**Comment by TCOTC** [comment]
文档的这个是没处理吗？我点了也去不掉

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ccd400ff-553f-44ca-b589-d30e49d99ac2)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/62f45997-9a0b-4b01-ba14-88819fd06720)

**Comment by 88250** [comment]
处理了的，我使用文档的 复制为副本 测试正常，可以自动清理掉角标。

**Comment by TCOTC** [comment]
奇怪耶，副本都还有，我研究一下：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5eb89b02-7b21-4976-9256-77495a64e21a)

**Comment by TCOTC** [comment]
@88250 用 dev2 导入这个：[最近任务 (Duplicated 2024-04-08 165844).sy.zip](https://github.com/siyuan-note/siyuan/files/14903364/Duplicated.2024-04-08.165844.sy.zip)

在文档右上角会显示一个未命名

**Comment by 88250** [comment]
收到，av.json 不存在的情况处理漏了，稍后不上。

**Comment by TCOTC** [comment]
> 收到，av.json 不存在的情况处理漏了，稍后补上。

能更进一步，在文档打开的时候就去掉吗？不只是点击 block superscript icon 才检验
