### ISSUE TITLE
图片路径编辑问题

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1087]
编辑图片路径时,'当前输入位置'会突然回到行首，后面有同样操作在Typora上的演示,作为参考

https://user-images.githubusercontent.com/38101170/104723455-3c9cf000-576a-11eb-9f9a-ec52ef6823fc.mp4

**Comment by Andy-AO** [comment]
@88250 这个'当前输入位置'比较公认的名字是什么？想了半天没想出来是什么名字，就干脆用了一个最直白的名字.

**Comment by canondin** [comment]
借楼，想问下`0.60`版本，我在`Typora`里面复制桌面图片，图片可以显示。用`siyuan`打开图片显示不了。
![image](https://user-images.githubusercontent.com/14855855/104730992-fd749c00-5775-11eb-9385-c0ad06ee0ce3.png)

**Comment by 88250** [comment]
> @88250 这个'当前输入位置'比较公认的名字是什么？想了半天没想出来是什么名字，就干脆用了一个最直白的名字.

光标插入位置吧，这个能看懂就行。

> 借楼，想问下`0.60`版本，我在`Typora`里面复制桌面图片，图片可以显示。用`siyuan`打开图片显示不了。
> ![image](https://user-images.githubusercontent.com/14855855/104730992-fd749c00-5775-11eb-9385-c0ad06ee0ce3.png)

前面加 `file://` 试试。

**Comment by Andy-AO** [comment]
@88250 补充一下，删除部分图片路径操作也是无效的，而且会直接跳到很远的地方

https://user-images.githubusercontent.com/38101170/104790005-3f7efb80-57d1-11eb-8eb0-d90156d3aa07.mp4

**Comment by 88250** [comment]
@Andy-AO 嗯，061 修复。
