### ISSUE TITLE
字体 外观设置 显示问题

### ISSUE THREAD

**Issue by 0xChrisJL** [siyuan-note/siyuan#10871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用 ctrl+alt+x 设置字体大小，选择alt+x 使用最近一次 字体
字体大小是正常生效的，但是如果单独选中某个块，查看字体 还是之前的大小，但是实际上字体已经是正常修改的。显示问题

### Expected result

块设置，与选中设置 显示一致性

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

~

**Comment by 88250** [comment]
行级元素和块级元素的外观设置是独立的，块级外观后续会考虑支持批量设置，请关注 #8554
