### ISSUE TITLE
Parsing YAML Front Matter as document custom attributes when importing Markdown files

### ISSUE THREAD

**Issue by parasiteoflife** [siyuan-note/siyuan#10878]
Please add support for importing MD files with Front Matter section

### In what scenarios do you need this feature?

I've been trying SiYuan and so far works great but as you understand most of the people already uses other applications for notes because of this I need to import all my notes from Joplin to SiYuan, I can do this with the markdown import feature but it wont restore the creation and last modified dates for the notes (you know metadata is important), fortunately Joplin has an option to export notes with a Front Matter which adds a section like this:

```md
---
title: Note 1
updated: 2023-08-27 14:34:08Z
created: 2020-01-24 08:17:18Z
latitude: some-lat
longitude: some-long
altitude: some-alt
---
```

To the top of each note, but SiYuan has no support for this. Can you please add it so we can migrate from other apps like Joplin to SiYuan?

### Describe the optimal solution

Being able to import markdown files with front matter sections.

### Describe the candidate solution

Add another import option that supports markdown + front matter.

**Comment by 88250** [comment]
Please follow #12962 for further improvements.
