### ISSUE TITLE
在输入框外松开鼠标时，不退出输入框

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10877]
### In what scenarios do you need this feature?

就是这种可以任意拖动大小的输入框，偶尔选中文本后会在输入框外面松开鼠标，结果就退出去了：

![选择](https://github.com/siyuan-note/siyuan/assets/78434827/c76e6ba6-1ef2-4a92-a1e9-b6376ecfd729)

### Describe the optimal solution

在输入框外松开鼠标时，不退出输入框

除了数据库，好像在其他地方也看到过这种可以拖动大小的输入框，如果其他地方也有相同的问题，希望能一起改了

**Comment by Vanessa219** [comment]
不记得有啥地方了，先改这个吧

**Comment by TCOTC** [comment]
找了一下，编辑 IFrame 链接的时候也可以优化：

![链接](https://github.com/siyuan-note/siyuan/assets/78434827/dedc3b9d-376e-4009-a5ea-1930d1ae0b2e)

**Comment by TCOTC** [comment]
我也重现不了了，不管了
