### ISSUE TITLE
Improve selection of iframe block

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10879]
### Describe the problem

如 GIF：

只尝试了空的 IFrame 块，不知道有内容的 IFrame 块是否也是如此。

![多选](https://github.com/siyuan-note/siyuan/assets/78434827/e9efa83a-9c60-42cd-9ff9-b300b0a3089c)

### Version environment

```markdown
- Version: 3.0.7
- Operating System: Win10
- Browser (if used):
```

**Comment by TCOTC** [comment]
@Vanessa219 刚刚发现挂件块也有同样的问题，会一起修复吗？

**Comment by Vanessa219** [comment]
应该是修改了
