### ISSUE TITLE
Support adding database blocks to a database

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10876]
支持把数据库块「添加到数据库」

发现数据库主键可以关联另一个数据库块，但是无法通过块标菜单中的「添加到数据库」把数据库块添加到另一个数据库中

3.0.7

**Comment by TCOTC** [comment]
另外有个问题：为什么数据库不能把自己添加到自己里？

**Comment by 88250** [comment]
前期设计的时候担心出现意外情况所以禁止了，目前看来可以放开该限制。

**Comment by TCOTC** [comment]
@88250 现在能把数据库自己发送到自己，但在主键搜索的时候搜索不到自己

**Comment by 88250** [comment]
收到，下个版本改进。
