### ISSUE TITLE
「添加到数据库」支持搜索到根据数据库块的别名搜索到数据库

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#10875]
### In what scenarios do you need this feature?

目前「添加到数据库」功能可以很方便的和dailynote笔记法结合，进行自下而上的积累，具体见我的分享https://ld246.com/article/1712235934222

希望还能再改进下「添加到数据库」功能，目前「添加到数据库」的搜索只能搜索数据库的标题，能否通过给数据库块添加别名
，「添加到数据库」也能以别名搜索到对应的别名呢。因为数据库的标题就如同文档标题一样，用一个名称总是不够的，这也是思源为什么要设计块别名的原因吧。比如我做图书目录的数据库，这本书实际是英文书，我起一个英文标题《Neuroscience: Exploring the Brain 》，但还是想有一个中文标题。
![Clip_2024-04-04_23-47-05](https://github.com/siyuan-note/siyuan/assets/60436214/da5dadd7-9411-499a-aaf3-b2a13b7168c4)

### Describe the optimal solution

「添加到数据库」支持搜索到根据数据库块的别名搜索到数据库

### Describe the candidate solution

none

### Other information

none

**Comment by TCOTC** [comment]
我这里使用「添加到数据库」可以根据 命名 和 别名 搜索到对应的数据库

**Comment by Achuan-2** [comment]
ok，是可以的，抱歉之前看错了。
