### ISSUE TITLE
在搭配PDF阅读和标注使用的优化建议

### ISSUE THREAD

**Issue by 0xChrisJL** [siyuan-note/siyuan#10872]
### In what scenarios do you need this feature?

1、在阅读PDF中，希望能够再PDF内添加文字，比如修改PDF中的错误，当然也可以直接写到左边的文本中，然后引用到对应位置，但目前PDF只能阅读和标注，没法插入文字，除非用第三方插入再导入进来，希望能够直接在思源 一体化 完成。
2、阅读PDF时候，我们经常标注，但是每次标注，都需要挨个复制到左边md文本中。或者直接把PDF中的文字复制出来，再文本中进行标注。但是在复制文字的过程中 需要调整字体、段落、然后再去标注，增加了步骤。不知是否可以，直接再PDF阅读和标注，然后直接选择一段内容（带有标注和未标注的文字内容）复制到左边。这样在阅读时候 直接进行了挖空，工作流更顺畅

### Describe the optimal solution

1、PDF 标注后希望可以再导出另存 PDF，PDF 内可以插入文字或者一些最基础的编辑功能
2、在 PDF 标注了高亮，可以直接复制到文本，并带有高亮

**Comment by TCOTC** [comment]
需要 [pdf.js](https://github.com/mozilla/pdf.js) 提供支持

参考 #9205

**Comment by hualr** [comment]
单纯把文档塞到思源 会导致后面笔记本很臃肿的
你的PDF通常100M左右 50本书就几个G了 这就导致你后面同步也会很麻烦的 不管你是用官方的还是自己的S3 
如果你是离线使用就当我没说吧哈哈

**Comment by TCOTC** [comment]
> 单纯把文档塞到思源 会导致后面笔记本很臃肿的 你的PDF通常100M左右 50本书就几个G了 这就导致你后面同步也会很麻烦的 不管你是用官方的还是自己的S3 如果你是离线使用就当我没说吧哈哈

确实，我看我的笔记文件，文本不到 10MB，插件超过 200MB，图片和PDF之类的超过 800MB

**Comment by 0xChrisJL** [comment]
> 如果你是离线使用就当我没说吧哈哈

嗯嗯 确实是这样的 哈哈哈，目前思源 与PDF 搭配，相当于是个摘录、查找的功能。当然核心就是查找汇总。那么我就会写更多的内容到左边文档进行辅助，同时内容要处理2道，再右边标注了pdf，如果想加入别的文字，我就会再复制出来，重新标注，再进行加入自己的整理。最后再生成需要的anki 反而把时间成本增加了。  
已经用回传统的PDF编辑器要好点。现在还是用BookxNote了 或者直接用PDF编辑器进行编辑批注再保存。背诵法条

**Comment by 0xChrisJL** [comment]
> > 单纯把文档塞到思源 会导致后面笔记本很臃肿的 你的PDF通常100M左右 50本书就几个G了 这就导致你后面同步也会很麻烦的 不管你是用官方的还是自己的S3 如果你是离线使用就当我没说吧哈哈
> 
> 确实，我看我的笔记文件，文本不到 10MB，插件超过 200MB，图片和PDF之类的超过 800MB。笔记软件里笔记是最少的😓

我目前就处理30多页的PDF内容，看了下data 200M 当然里面还有一些插件，轻度使用

**Comment by 88250** [comment]
这个可能无法改进了，感谢理解和讨论。

**Comment by xeahsoon** [comment]
> ### In what scenarios do you need this feature?
> 1、在阅读PDF中，希望能够再PDF内添加文字，比如修改PDF中的错误，当然也可以直接写到左边的文本中，然后引用到对应位置，但目前PDF只能阅读和标注，没法插入文字，除非用第三方插入再导入进来，希望能够直接在思源 一体化 完成。 2、阅读PDF时候，我们经常标注，但是每次标注，都需要挨个复制到左边md文本中。或者直接把PDF中的文字复制出来，再文本中进行标注。但是在复制文字的过程中 需要调整字体、段落、然后再去标注，增加了步骤。不知是否可以，直接再PDF阅读和标注，然后直接选择一段内容（带有标注和未标注的文字内容）复制到左边。这样在阅读时候 直接进行了挖空，工作流更顺畅
> 
> ### Describe the optimal solution
> 1、PDF 标注后希望可以再导出另存 PDF，PDF 内可以插入文字或者一些最基础的编辑功能 2、在 PDF 标注了高亮，可以直接复制到文本，并带有高亮
> 
> ### Describe the candidate solution
> _No response_
> 
> ### Other information
> _No response_

@88250 第一点不支持很赞同，但是第二点确实也是个刚需。通常阅读 PDF 的过程中很喜欢先标注后总结，一旦标注的东西没有拷贝出来，之前标注了哪些内容都找不到了。尝试通过 SQL 查询好像也找不到单独有数据表存储 PDF 中标注信息
