### ISSUE TITLE
在表格前无法用 `Delete` 删除空段落块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10883]
### Describe the problem

在表格前能用 `Backspace` 而无法用 `Delete` 删除空段落块：

![表格](https://github.com/siyuan-note/siyuan/assets/78434827/a126f6e8-b74a-4ace-97a2-02c531cd7083)

### Expected result

当前段落块为空、后面是表格时，用 `Delete` 可以删除空段落块，然后光标移到表格的首个字符前

### Version environment

```markdown
- Version: 3.0.7
- Operating System: Win10
- Browser (if used):
```

**Comment by Vanessa219** [comment]
delete 为向后删除，应该是删除表格，但是由于表格比较特殊就不进行删除了。
