### ISSUE TITLE
移除数据库视图右键菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10889]
### In what scenarios do you need this feature?

右键视图显示的是：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3293e085-248c-4b14-ab8a-8526408dc447)

然后无论点击「重命名」还是「设置」，都会打开同一个界面：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/530dc522-33ba-475b-ae06-e019a18fc8c8)

而且「复制为副本」和「删除」也都有。

### Describe the optimal solution

那么弹出第一个菜单完全是多此一举啊，直接打开第二个界面就好了，还能少点击一次

**Comment by Vanessa219** [comment]
如果点击的视图不是当前视图就不再需要先点击视图再移到右侧点击更多菜单。

**Comment by TCOTC** [comment]
> 如果点击的视图不是当前视图就不再需要先点击视图再移到右侧点击更多菜单。

我说的应该跟这个没关系。现在是有两个功能重复的菜单，只留第二个就够了，右键视图的时候就弹出第二个菜单

**Comment by Vanessa219** [comment]
这个参考的 notion，它可能只想让 tab 负责看的到的范畴内的操作，其他更多的设置会干扰。

**Comment by TCOTC** [comment]
Notion 这样做应该是因为 Database 的各种主要设置菜单都放在右边（而不是浮窗），所以右键视图之后需要有一个过渡的操作，而不是在左边点击右键，却在右边弹出菜单

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b93102b4-d50d-4daa-813d-a0d3e202f841)

**Comment by Vanessa219** [comment]
我们的菜单和他浮窗一直，只是外观不同

**Comment by TCOTC** [comment]
好吧，但我觉得「重命名」和「设置」是同样的功能就很怪，不如合并成「编辑视图」，然后把下面的分隔线去掉

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c46f0db7-fb2f-4f96-822a-61c7f190edb5)

**Comment by Vanessa219** [comment]
对用户直观上来说还是有点不一样的，先不动了
