### ISSUE TITLE
减小数据库视图默认图标和标题的间距

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10887]
### In what scenarios do you need this feature?

离得太远了，感觉很分散：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/645eac15-560e-489f-bfb8-2f493719c5d6)

### Describe the optimal solution

减小数据库视图图标和标题的间距：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ec14f933-157b-487b-9d15-74b89ff54aeb)

**Comment by TCOTC** [comment]
看了一下，减少 4px 应该是没问题的，也不会影响到其他 emoji

**Comment by TCOTC** [comment]
还有就是图标换成 emoji 之后，位置明显偏下了，最好居中对齐：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/da53fe5b-b540-464e-a9a2-af06ca687c1e)

**Comment by TCOTC** [comment]
好吧，换了个字体之后就变奇怪了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/837d17ff-9eac-4cb6-8be4-f8a65f9bf037)

只能把 issue 改成“减小数据库视图**默认图标**和标题的间距”

**Comment by UFDXD** [comment]
你提了好多issue呀

**Comment by Vanessa219** [comment]
每套 emoji 的大小都不太一致，这个只能尽量。
