### ISSUE TITLE
数据库块引只显示数据库标题 (或者命名)，不显示视图名称

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10880]
### In what scenarios do you need this feature?

视图多起来之后会很奇怪：

数据库主键 ↓

![image](https://github.com/siyuan-note/siyuan/assets/78434827/38a4306b-fa4a-4ad6-9bce-ff8a5e486856)

无锚文本块引 ↓

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5d30691b-77c8-4570-9fc0-ec299b11aec8)

### Describe the optimal solution

数据库块引只显示数据库标题 (或者命名)，不显示视图名称

**Comment by 88250** [comment]
这个情况最好使用静态锚文本，因为多视图无法确定引用的具体视图，（引用元素无法支持指定视图）。

**Comment by TCOTC** [comment]
> 引用元素无法支持指定视图

既然如此，我觉得也没有必要显示所有视图名称，只显示数据库名就够了

**Comment by 88250** [comment]
有道理，下个版本改进。
