### ISSUE TITLE
优化数据库勾选框图标显示效果

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10885]
### 只有勾选框的图标特别黑：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cc2e897e-7d10-4afc-a30b-32e5675c3963)

### 不居中对齐，不好看：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4cd9388b-5571-4e0d-82dd-2f517a9a8256)

### 换一个不那么显眼的勾选框图标：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8065b292-4758-414f-9867-0601c8ac87fe)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e8f237f9-10ab-4b8b-8e60-aa73c6e8511b)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5cc841f5-5b9c-40dc-84a5-64e959b0b01d)

### 调整大小（上面小，下面大）、居中对齐：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/367686f0-f8be-4bee-a7b8-b4039e92221a)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/af1e1285-f5de-4e5a-b2c9-c210992b9923)

**Comment by Vanessa219** [comment]
这里图片和大小是一致的。
<img width="252" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/1be96390-4533-441f-ba61-22e5c0f11687">

对不齐是由于，要不然还是改回原来的左右间隔大小吧？
https://github.com/siyuan-note/siyuan/issues/10712

**Comment by TCOTC** [comment]
不能单独改勾选列吗？

**Comment by Vanessa219** [comment]
表头改成和单元格一样宽度了

**Comment by Vanessa219** [comment]
要用默认主题吧，我这里时一样的

<img width="164" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/c21a3e37-7605-4cdf-9e6c-adcf0e168a70">

**Comment by TCOTC** [comment]
原来是图标包的问题。

**Comment by TCOTC** [comment]
我知道为什么对不齐了，这个没有跟随字号变化：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5ad78895-74dd-4ba0-8d73-32fb471c675b)

**Comment by Vanessa219** [comment]
字体改动时适配一下内容

<img width="1265" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/36d3619d-c459-4b29-9060-7b571290ad83">

**Comment by TCOTC** [comment]
@Vanessa219 还有这个：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e0f7d368-a04f-411b-a978-5e10183e2530)

**Comment by TCOTC** [comment]
@Vanessa219 感觉还是不对，现在变成上面的按钮不会变化大小了

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8a5ec2cb-7d28-472f-aa78-d35fb5262ee8)
