### ISSUE TITLE
新建文档的存放路径如果包含emoji，新建文档时无法识别

### ISSUE THREAD

**Issue by o-ut-man** [siyuan-note/siyuan#1088]
![image](https://user-images.githubusercontent.com/34265164/104727938-221a4500-5771-11eb-8b14-ad4194b5e178.png)
日记的路径包含emoji可以正确识别文件夹并建立文档，但新建文档的路径如果包含emoji，新建的文档只会在笔记的根目录下新建

**Comment by 88250** [comment]
0.6.0 这个问题应该解决了，请升级看看。
