### ISSUE TITLE
When editing a cell, right-click outside the input box to save

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10895]
### Describe the problem

左键点击弹出输入框之后再右键其他地方，就会呈现一种很奇怪的状态（黄色为左键点击，红色为右键点击）：

![输入框](https://github.com/siyuan-note/siyuan/assets/78434827/5cfc1699-0cc6-4bb1-95ed-4c1735cf40f4)

### Expected result

在输入框外右键点击的效果应该跟在输入框外左键点击的效果一致，都是关闭输入框。

### Version environment

```markdown
- Version: 3.0.7
- Operating System: Win10
- Browser (if used):
```

**Comment by Vanessa219** [comment]
右键有取消的意思，点击了以后如果修改过编辑内容，是否不进行更新。如果不更新可能用户认为丢数据，如果更新，有的用户又可能认为应该取消。所以先不动了。

**Comment by TCOTC** [comment]
> 右键有取消的意思，点击了以后如果修改过编辑内容，是否不进行更新

右键哪里来的取消的意思？一般取消都是用 Esc，而编辑数据库时按 Esc 都是会更新内容的，按右键更没理由不更新内容。

而且「取消」是没有意义的，毕竟编辑都编辑了，想恢复编辑前的状态只能按 Ctrl+Z 。

**Comment by TCOTC** [comment]
在 Notion 中，在数据库文本输入框外右键点击，效果是跟左键点击一样的，都会关闭输入框

**Comment by Vanessa219** [comment]
那就左键右键点击后都进行保存吧
