### ISSUE TITLE
改进表格内的右键菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10890]
### In what scenarios do you need this feature?

有些操作（增/删）是比较高频的，但每次都要先找到「表格」再进到子菜单里找，比较繁琐，可以移出来。

排版用的可以留在里面。

![image](https://github.com/siyuan-note/siyuan/assets/78434827/83df464e-25d8-4904-8a74-873674e9169b)

**Comment by 5kyfkr** [comment]
这个支持，移出来起码表格不会太难用了

**Comment by MrIntellectX** [comment]
I support this +1

**Comment by TCOTC** [comment]
不用和块标统一，这个东西就跟在数据库上右键一样，是独立于块标的、专门为表格优化

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f0e15a07-853f-4db6-b9fe-b1a9195cc083)

**Comment by TCOTC** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/392f48e7-4af2-4fdb-baa1-aad3965bc291)

如果表格也能做到这个的话就更好了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/edd8432c-72d4-48eb-814a-73635939d909)

**Comment by Vanessa219** [comment]
能是能，但是菜单太多了，这种用快捷键也方便。

**Comment by 88250** [comment]
这个仅稍微调整，不拉进版本了。
