### ISSUE TITLE
标签系统管理微小优化

### ISSUE THREAD

**Issue by hualr** [siyuan-note/siyuan#10893]
### In what scenarios do you need this feature?

当前软件虽然支持块级别的标签 但是这部分块级别的标签本身缺乏管理
这就导致标签会非常非常多 到后期都不敢随便记录标签
这样一种标签不好用的情况  我想是导致论坛很多人不敢随便使用标签的主要原因吧.

### Describe the optimal solution

1. 通过聚焦 实现只展示这个文档的标签 (包括这个文档和其子文档)
![image](https://github.com/siyuan-note/siyuan/assets/40055178/85344e26-81db-47ca-97c8-bb31d2b00565)

这个地方可以添加一个聚焦按钮 
效果为根据我们当前的工作区范围直接聚焦到这个工作区的所有标签信息
![image](https://github.com/siyuan-note/siyuan/assets/40055178/2e4cd752-4f25-4947-ae38-cad44466391e)
比如 我们选中笔记本 标签就自动焦距到该笔记本下的所有标签
或者 我们选中一个文档 标签就自动焦距该文档和子文档下的所有标签

2. 第二步 在选中该标签 搜索直接搜索当前范围下的信息 不必展示其他范围的标签(等于这里涉及到一个搜索内容的SQL触发)
(红色框部分就是我们的范围)
![image](https://github.com/siyuan-note/siyuan/assets/40055178/64ed6a78-a55b-4de7-91d1-01d03890f03e)

### Describe the candidate solution

或者引入一套比较完整的标签面板进行管理?但是这就麻烦了.我认为这种消耗大的操作不太有投入的性价比.

### Other information

![image](https://github.com/siyuan-note/siyuan/assets/40055178/8e179071-b55f-4690-ba1f-ceab15ab2e64)
可以类似于这个按钮
白色地方可以添加一个聚焦按钮 从而实现切换到该笔记本/该文档下的所有标签筛选展示
注意到 这里选中标签后的搜索 也是基于当前范围的搜索

### Describe the candidate solution

或者引入一套比较完整的标签面板进行管理?
个人认为我的这种方案是有效整理的一个利器.

### Other information

![image](https://github.com/siyuan-note/siyuan/assets/40055178/8e179071-b55f-4690-ba1f-ceab15ab2e64)
可以类似于这个按钮

**Comment by hualr** [comment]
这个功能很明显是一种以编码成本比较小的方式达成了一个非常大的效果
其带来的影响是 整个标签系统就完全可以用起来了
目前完全用不起来 因为一旦用起来 会发现标签太多了 也没有比较成熟的标签面板 根本就不好找

我想这里出现的这个标签自动缩起来的功能也是为了解决标签多的问题吧.但是其实标签本身就不应该嵌套太多.如果嵌套很多的标签其实很就更难以用起来了.所以正常使用场景下 标签通常只有一级

![image](https://github.com/siyuan-note/siyuan/assets/40055178/b2fd505a-d721-4fd7-b59d-963d03d050ae)

**Comment by UFDXD** [comment]
试试引用标签吧，集市有个插件 能标签转引用

**Comment by Achuan-2** [comment]
个人目前使用标签仅仅是为了发链滴才用
如果思源的数据库可以添加标签列，标签列添加标签直接为文档和块添加，我才觉得标签有点用，也方便对文档标签进行管理

**Comment by hualr** [comment]
> 试试引用标签吧，集市有个插件 能标签转引用

可是就算用引用 也无法解决基于一篇文档直接查看引用的需求?

**Comment by hualr** [comment]
要是书签功能 能实现的话 也好啊
书签目前似乎在这种需求上更加好使唤

**Comment by zongqir** [comment]
同意！！！！太棒了这样！！！！！！

**Comment by TCOTC** [comment]
关联：[标签树筛选 · Issue #11039 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/11039)
