### ISSUE TITLE
Right-click on the input to provide a copy menu

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10896]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/cb0fb1f6-d7f4-4ece-bafd-2d15b5825708)

### Describe the optimal solution

像在其他地方右键那样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c19f6ec0-a944-4648-a370-d7bbb27808b5)

**Comment by TCOTC** [comment]
编辑 IFrame 链接时也许也需要：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/de8ac58a-0a6a-491b-964d-d1adb31383da)

**Comment by Vanessa219** [comment]
iframe 链接好像不需要呀

**Comment by TCOTC** [comment]
我也不清楚，只是想让每个可以输入文本的地方都有右键菜单方便粘贴文本

**Comment by mozhux** [comment]
其实可以再借鉴一下notion，每个格子放上去还有一个复制按钮
![image](https://github.com/siyuan-note/siyuan/assets/46953371/62f216d2-7f7f-4acd-a654-edaa0c931152)

**Comment by Vanessa219** [comment]
> 其实可以再借鉴一下notion，每个格子放上去还有一个复制按钮 ![image](https://private-user-images.githubusercontent.com/46953371/322164346-62f216d2-7f7f-4acd-a654-edaa0c931152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzA1NjcsIm5iZiI6MTcxMjk3MDI2NywicGF0aCI6Ii80Njk1MzM3MS8zMjIxNjQzNDYtNjJmMjE2ZDItN2Y3Zi00YWNkLWE2NTQtZWRhYTBjOTMxMTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAxMDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMjkwMjUxZDFiZjA3YTlmZGJmYzM5ZGM3NTJhMGMxNzAzN2Y1MmE0NzFmMTRmZTI5YjE1YWY0NjM3Mzg3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vEV4t1sYngnbgR0LJ-hywoR1g9foV4GbjhHQ-NIG1Vk)

我们的也有呀
<img width="227" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/2ac9eb31-cbd7-4526-9951-a632162d8e22">

**Comment by Vanessa219** [comment]
* 由于浏览器限制只能读取到剪贴板中的纯文本，粘贴的时候都为纯文本，因此粘贴为纯文本选项就不需要了
* 输入框没有转义的处理，也就不需要此项了

**Comment by mozhux** [comment]
> > 其实可以再借鉴一下notion，每个格子放上去还有一个复制按钮 ![image](https://private-user-images.githubusercontent.com/46953371/322164346-62f216d2-7f7f-4acd-a654-edaa0c931152.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzA1NjcsIm5iZiI6MTcxMjk3MDI2NywicGF0aCI6Ii80Njk1MzM3MS8zMjIxNjQzNDYtNjJmMjE2ZDItN2Y3Zi00YWNkLWE2NTQtZWRhYTBjOTMxMTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAxMDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMjkwMjUxZDFiZjA3YTlmZGJmYzM5ZGM3NTJhMGMxNzAzN2Y1MmE0NzFmMTRmZTI5YjE1YWY0NjM3Mzg3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vEV4t1sYngnbgR0LJ-hywoR1g9foV4GbjhHQ-NIG1Vk)
> 
> 我们的也有呀 <img alt="image" width="227" src="https://private-user-images.githubusercontent.com/970828/322165905-2ac9eb31-cbd7-4526-9951-a632162d8e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzY3MTAsIm5iZiI6MTcxMjk3NjQxMCwicGF0aCI6Ii85NzA4MjgvMzIyMTY1OTA1LTJhYzllYjMxLWNiZDctNDUyNi05OTUxLWE2MzIxNjJkOGUyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwMjQ2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWExY2I4NDRjMjRhZjZjMjRkNjFiNjk5MDczYWE1YzdkN2I2OWNmZTdlZWRmNWU1ZWQ3OTQ2MjI2MWYwODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gWpQTM_S8gq-2Fmlqug1veNTIxDwPCiKS6Zydc92GWA">

我的问题。自己整的图标没认出来
