### ISSUE TITLE
改进数据库视图设置菜单隐藏或显示标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10908]
### In what scenarios do you need this feature?

1. 隐藏或显示标题后还需要调整其他设置，还要再打开一次设置菜单
2. 鼠标移上去才会显示眼睛图标（按钮），可以简化一下

![image](https://github.com/siyuan-note/siyuan/assets/78434827/17c566f0-8b66-4503-af73-d4600d6b4e47)

### Describe the optimal solution

1. 数据库隐藏或显示标题后不关闭视图设置菜单
2. 改进交互：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c5b72831-a7e8-48df-89b5-d407f23a0bbf)

**Comment by Vanessa219** [comment]
修改为这样吧

<img width="300" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/229ef85d-1365-4f13-a7a6-afeef44e0797">
