### ISSUE TITLE
数据库横向滚动条在超出界面之后仍然显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10905]
### In what scenarios do you need this feature?

这个滚动条：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dfddf546-c815-4507-9558-d6a342e6c632)

目前在超出界面之后不会显示：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7a50b9cb-750f-47da-bd17-c9ecd3281740)

### Describe the optimal solution

数据库横向滚动条在超出界面之后仍然显示，方便横向滚动

**Comment by Vanessa219** [comment]
这个由于数据库没有纵向滚动条，它和文档是公用一个滚动条的。因此数据库的横向滚动条只能在最底部，上图的情况由于底部在下面，因此滚动条也只能在下面了。这个暂时没有办法进行修改。

**Comment by shuojie819** [comment]
`Shift + 滚轮` 可以横向滚动哦

**Comment by TCOTC** [comment]
> `Shift + 滚轮` 可以横向滚动哦

有用户反馈长按 Shift 会来回切换输入法，所以必须要有一个滚动条
