### ISSUE TITLE
Improve appearance setting theme name display

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10903]
改进外观设置主题名称显示

- [ ] 外观设置中的主题名称使用 displayName
  - [ ] 把默认主题的名称也国际化一下，叫「默认明亮主题」和「默认暗黑主题」，其他语种不翻译默认用英文也行（Default light theme）
- [x] 挂件菜单中的挂件名称使用 displayName #10917

### In what scenarios do you need this feature?

很多主题都有中文名，但菜单里名称使用的是 json 中的 name 字段

![image](https://github.com/siyuan-note/siyuan/assets/78434827/da64c61e-9af7-4dc6-8620-98f327acd24e)

挂件我真的认不出来哪个是哪个：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2bf827a4-d02e-4815-99cc-ad1c9115c650)

**Comment by Achuan-2** [comment]
+1

**Comment by 88250** [comment]
拆分一下，挂件名称显示改进请关注 https://github.com/siyuan-note/siyuan/issues/10917
