### ISSUE TITLE
超级块缺陷报告

### ISSUE THREAD

**Issue by Duan-Wuya** [siyuan-note/siyuan#1090]
### 描述问题 Describe the problem

目前发现三个问题：

1. 输入超级块的 {{{ 会导致折叠内容展开：
2. 公式块无法在超级块内编辑
3. 行内公式的代码部分无法收起

### 期待的结果 Expected result

1. 在文章任何地方输入 {{{ 不影响已经折叠的部分
2. 超级块内可以显示数学块的代码部分
3. 超级块中可以在不编辑行内公式的时候收起代码

### 截屏或录屏演示 Screenshot or screen recording presentation

超级块导致折叠展开：

![超级块导致折叠展开](https://user-images.githubusercontent.com/59379633/104731100-2d23a400-5776-11eb-8269-114858b231d3.gif)

超级块内无法编辑数学块：

![超级块中公式块](https://user-images.githubusercontent.com/59379633/104731236-63612380-5776-11eb-8577-6cb18f317b03.gif)

行内公式代码部分无法收起：

![超级块行内公式](https://user-images.githubusercontent.com/59379633/104731343-87246980-5776-11eb-963a-f0427befb946.gif)

### 版本环境 Version environment

* 版本 Version：0.6.0
* 操作系统 Operating system：Windows
* 浏览器（如果使用）Browser (if used)：无

### 日志文件 Log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5820695/siyuan.log)

### 更多信息 More information

暂无更多详细信息。

**Comment by 88250** [comment]
这里比较复杂，估计要延后处理，谢谢。

**Comment by Asukaleo-aa** [comment]
也发现这个bug了，现在可以在专家模式里面先顶顶

**Comment by 88250** [comment]
这部分已经在 v1.2.0 中重写了，等发布以后请帮忙测试，谢谢。

新版中主要靠拖拽来形成超级块，后面估计会做一个组合（Group）操作来形成超级块。

![demo](https://user-images.githubusercontent.com/873584/116701549-9e702580-a9fa-11eb-979a-e00a3f60de45.gif)

**Comment by Duan-Wuya** [comment]
没问题，期待v1.2.0
