### ISSUE TITLE
Support creating new rows when filling in the database relation field

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10914]
数据库关联字段填值时支持创建新行

https://github.com/siyuan-note/siyuan/issues/10836 Point 2

**Comment by TCOTC** [comment]
创建新行时，不根据视图筛选条件填充默认值

**Comment by 88250** [comment]
关联字段填不了。

**Comment by TCOTC** [comment]
没听懂，我们说的是同一件事吗？

**Comment by 88250** [comment]
我指的是过滤器如果设置了关联，无法自动填值。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sun, Apr 7, 2024 12:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support creating new rows when filling inthe database relation field (Issue #10914)




 
没听懂，我们说的是同一件事吗？

**Comment by TCOTC** [comment]
我的意思是（举个例子）：

假设关联的数据库有「主键」和「单选」两个属性，只有一个视图，并且该视图添加了筛选条件「单选 等于 进行中」，那么在关联列向其关联的数据库中创建新行时，不应该根据其视图的筛选条件为新行的单选属性填充默认值「进行中」——不应该默认填充任何属性。

**Comment by 88250** [comment]
懂了，后面实现的时候会考虑到这一点，谢谢。

**Comment by TCOTC** [comment]
参考

在数据库关联列中为关联的数据库创建新的行

![Notion](https://github.com/siyuan-note/siyuan/assets/78434827/d6d9b52b-318f-4a07-a382-121b7b2fdaaf)

**Comment by TCOTC** [comment]
用户需求：

![image](https://github.com/user-attachments/assets/016dd4cf-f352-4ab5-9ee5-1da9d3964ad1)

**Comment by KuiyueRO** [comment]
另外通过浮窗创建新内容后，选项列表不会及时更新，需要点击外部关闭选项列表再打开。

![image](https://github.com/user-attachments/assets/a3d78533-5bc1-4444-bb5f-215b757ebe80)

**Comment by 13953889506** [comment]
这个功能在数据库管理应用中很实用的，请技术团队及时给用户们提供下！

**Comment by TCOTC** [comment]
@Vanessa219 这个没实现：https://github.com/siyuan-note/siyuan/issues/10914#issuecomment-2081465904

> - 无论输入的文本是否能筛选出条目，都可以新建条目
> - 按钮放在最底下

**Comment by Vanessa219** [comment]
什么按钮放最下面？

**Comment by TCOTC** [comment]
新建条目的那个按钮

**Comment by Vanessa219** [comment]
好的，都已修改。

**Comment by TCOTC** [comment]
issue 标题要改成 创建新**条目**
