### ISSUE TITLE
Support floating window to open the unbound block row when filling in the database relation field

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10916]
数据库关联字段填值时支持浮窗打开未绑定块行

https://github.com/siyuan-note/siyuan/issues/10836 Point 3

**Comment by TCOTC** [comment]
参考

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9baccb69-0e2d-4cf9-999c-9dae83a7c2da)

**Comment by TCOTC** [comment]
- 这个设计有点问题，不能判断应该打开哪个数据库块的哪个视图。
- 参考 Notion 的逻辑换成这个方案：#12101

@88250 这个 issue 关掉吧
