### ISSUE TITLE
群晖上搭建思源笔记，局域网没问题，Nginx Proxy Manager反代理外网访问报错。

### ISSUE THREAD

**Issue by anonymouswhac** [siyuan-note/siyuan#10922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

群晖上搭建思源笔记，局域网没问题，Nginx Proxy Manager反代理外网访问报错。

报错内容如下：

💔 Don't panic... v3.0.7
Your data should be safe, please check whether the network connection and kernel process are normal, and then restart SiYuan
If the problem persists, please look for help or report bugs here

### Expected result

不知道是哪里出了问题。

### Screenshot or screen recording presentation

![屏幕截图 2024-04-07 151524](https://github.com/siyuan-note/siyuan/assets/12844646/7a04bff6-7578-44dc-8c7b-0f5b8491d6ae)

### Version environment

```markdown
- Version: 
- Operating System: Synology
- Browser (if used):Chrome
```

### Log file

none

**Comment by Temacc0531** [comment]
是否配置了Websockets

**Comment by anonymouswhac** [comment]
已解决，确实是Websockets没开启

**Comment by sevensky** [comment]
> 已解决，确实是Websockets没开启

docker运行  nginx反代的， Websockets 怎么配置啊。

**Comment by saitolerr** [comment]
> > 已解决，确实是Websockets没开启
> 
> ```
>     location / {
>         proxy_pass          http://127.0.0.1:10080;
>         proxy_http_version  1.1;
>         proxy_set_header    Upgrade $http_upgrade;
>         proxy_set_header    Connection upgrade;
>         proxy_set_header    Host $host;
>         proxy_set_header    X-Real-IP $remote_addr;
>         proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header    X-Forwarded-Proto $scheme;
>     }
> ```

太感谢啦
