### ISSUE TITLE
Improve doc icon, background and tag editing interaction

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10926]
改进文档添加图标

目前添加图标的操作：点击「随机图标」，生成随机 emoji → 点击图标，弹出窗口 → 选择图标

希望改为：点击「添加图标」，生成随机 emoji ，弹出窗口 → 选择图标

**包含 3 点改动：**

1. 文本由「随机图标」改为「添加图标」
2. 添加随机图标后立即弹出选择 emoji 的窗口
3. 如果文档已有图标，点击「添加图标」后只会弹出窗口，不会生成随机的图标
    - 如果能更进一步的话，当文档已有图标时，文本由「添加图标」变为「修改图标」，反之亦然

**Comment by TCOTC** [comment]
[文档的添加标签，图标，图片，是不是在文档标题进入编辑状态，就展示出来。隐藏的太深了 - 链滴](https://ld246.com/article/1712491063918)

将鼠标移到标题后就显示：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/20b1faad-f1b8-481b-b3be-845ffaedf759)

**Comment by TCOTC** [comment]
> @TCOTC 有空能帮忙 PR 一下吗？

没学过 ts ，第二点「添加随机图标后立即弹出选择 emoji 的窗口」我不会搞

**Comment by 88250** [comment]
收到，那还是等 @Vanessa219 搞吧。

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/ae8b7419-2299-4253-9f20-fabbd1d36321)
能不能这里再加个文档属性图标，我觉得这个挺常用的，主要是添加书签的时候经常要点进去

**Comment by Vanessa219** [comment]
@5kyfkr 这里加了会太重复，这个入口很多地方都有，使用图标 shift+click 吧。

**Comment by 5kyfkr** [comment]
> @5kyfkr 这里加了会太重复，这个入口很多地方都有，使用图标 shift+click 吧。

能把书签提一级出来相信书签会更好用，现在书签藏的有点深了，像notion有个星标功能其实就是书签的变种，体验就很好，我还是觉得文档级别应该可以有个更快的书签添加入口，其他别名命名那些我从没用过。
![image](https://github.com/siyuan-note/siyuan/assets/63196026/858dc27c-fbe7-42dd-afd4-dc1e3e736f82)

**Comment by 88250** [comment]
@5kyfkr 文档树星标有单独的提议 https://github.com/siyuan-note/siyuan/issues/9466 书签功能就不动了。

**Comment by TCOTC** [comment]
@Vanessa219 文档不能添加多个标签了。「添加标签」按钮应该始终保留

![image](https://github.com/siyuan-note/siyuan/assets/78434827/378b8339-a113-4edc-a812-0b1ae8c363c3)

**Comment by TCOTC** [comment]
还有题头图的这个不是「随机」，我觉得应该改成「选择」：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/340d96bd-4ef2-45b1-bf8b-f0d6f66e5a19)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9a985b89-9443-4c61-8ecd-f538ba553397)

**Comment by Vanessa219** [comment]
1234 后面有个➕

**Comment by TCOTC** [comment]
> 1234 后面有个➕

现在才发现，不过这个加号一直显示是不是有点不太好看？我觉得悬浮显示可能好一点

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/c50931f8-bfe5-4a5d-8b8e-0142bbae542c)
@Vanessa219 V姐，没有标签的时候标题上方空行太多了，建议和以前一样放在文档图标旁边

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/cf2c1a50-3bfa-48bb-a354-2cce15cc21f3)
在有标签没有图标的时候也有空行

**Comment by 5kyfkr** [comment]
好像notion也是这个样子，如果不好整就算了
![image](https://github.com/siyuan-note/siyuan/assets/63196026/df393552-0847-4678-919f-1f45f708130d)

**Comment by Vanessa219** [comment]
鼠标移动上去就没有空行了。先这样吧

**Comment by mustakshif** [comment]
<img width="888" alt="截屏2024-04-28 13 30 06" src="https://github.com/siyuan-note/siyuan/assets/100056458/00edb6b9-efb2-4fc4-97fa-78bc30968b6d">

新版文档图标和标签区域缺少右外边距，标签较多的情况下会超出页面文字流边界，破坏观感，请问会考虑添加吗

**Comment by mustakshif** [comment]
打开新页签时题头图区域会出现线框，文档内容出现后消失。默认主题，已排除插件影响。


https://github.com/siyuan-note/siyuan/assets/100056458/54c8ba5f-a23d-4d5f-9fc6-1cc399aa6f18

**Comment by TCOTC** [comment]
@Vanessa219 我觉得这个还是悬浮显示吧，页面上方一直显示「＋添加标签」有点不好看：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9c0882c4-bf9e-4a87-94d6-fa5a0a6445df)

**Comment by Vanessa219** [comment]
什么样的悬浮？下面的按钮和这个是一样的。

**Comment by TCOTC** [comment]
@Vanessa219 就是像下面的按钮那样，鼠标接近了再显示：

![标签](https://github.com/siyuan-note/siyuan/assets/78434827/8eda8bc0-5d3f-44af-b8bb-75fca6d78945)

**Comment by Vanessa219** [comment]
这样会不会找不到按钮呀,显示的时候第一眼都没看到 😄

**Comment by 5kyfkr** [comment]
> 这样会不会找不到按钮呀,显示的时候第一眼都没看到 😄

逻辑一致吧，原来没有标签的时候都是隐藏起来的，有标签后反而一直显示怪怪的，一直隐藏问题不大，或者能做成自动展开的，只留一个+号，鼠标移上去展开成+添加标签

**Comment by royc01** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/38906705/0dc00b2a-79e5-4f4f-a7a5-147c3ef97646)
我是改成这样了

**Comment by Vanessa219** [comment]
那就保持一致吧，我再改改。

**Comment by TCOTC** [comment]
有改吗？我这里还是一直显示：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7b5bb0ee-034c-4f02-8f5b-aaa280931ba0)

**Comment by Achuan-2** [comment]
标签建议放在emoji上面，现在标签和emoji都放在上面，反而与标题有很大距离了，感觉不好看
![Clip_2024-04-30_17-36-20](https://github.com/siyuan-note/siyuan/assets/60436214/bb2a96ae-f521-4c2c-b29f-661fab65fea9)

**Comment by TCOTC** [comment]
要不这样改：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3458bb31-0c32-418d-b608-ff6f13f5e73e)

**Comment by Achuan-2** [comment]
> 要不这样改：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/326762043-3458bb31-0c32-418d-b608-ff6f13f5e73e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzIzNDgsIm5iZiI6MTcxNDQ3MjA0OCwicGF0aCI6Ii83ODQzNDgyNy8zMjY3NjIwNDMtMzQ1OGJiMzEtMGMzMi00MThkLWI2MDgtZmY2ZjEzZjVlNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEwMTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZjcyZDlkN2ZhYzY5NzlmNTUzOTIxZmJiYzRhYWQ5MWFjYzVlNTM4NzVlMzRjZjhjMmZhZDBlNjM5ZDAxY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GDQf0JLXq2gAqX_BEvmk7W5dY5oEVC_lVLpd1r3yJq0)

wolai是这样设计的，也可以参考下，根据emoji、标签、题头图的实际位置来分配按钮位置
![Clip_2024-04-30_18-16-27](https://github.com/siyuan-note/siyuan/assets/60436214/45bee804-86ef-44da-bd04-ad4d0f742d6c)

**Comment by Vanessa219** [comment]
@TCOTC 改了，鼠标不要放在那一块区域看看。分开两行的话会比较明确，放在表情后面好像要修改表情一样。

@Achuan-2 以前的设计有用户会觉得头部空白太多，这样就更多了。

**Comment by TCOTC** [comment]
> 改了，鼠标不要放在那一块区域看看。分开两行的话会比较明确，放在表情后面好像要修改表情一样。

看了一下提交的时间，是在发版之后才提交的，要等下个版本才能看到效果了
