### ISSUE TITLE
Blocks bound in the database support `Add to Database`

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10929]
数据库中绑定的块支持 `添加到数据库` 和 `移动到数据库`

数据库主键可以添加到其他数据库

### In what scenarios do you need this feature?

如题，我现在dailynote会先记录然后直接发到一个中转数据库，然后后续再移动到其他数据库，多这样一步也更能实现前期无压记录，不用想着分类到哪个数据库，希望能在单选和多选项提供添加到数据库功能，这样就能直接转发添加过去了，不用再去文档里面选择对应段落添加，也能为多选提供更多操作空间

![image](https://github.com/siyuan-note/siyuan/assets/63196026/13da08ce-bab5-432b-bc54-769d81b79c70)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/f77bfe59-7b64-45b8-98c9-0885186fcfff)

### Describe the optimal solution

如果可以还可以再加个添加后删除的选项，这样就又少一步删除的步骤

**Comment by Jiangshuon** [comment]
顶顶顶

希望能有两种操作——

1、移动到其他数据库
2、添加到其他数据库

第一种方式就能自动删除在本数据库中的记录

**Comment by 5kyfkr** [comment]
> 顶顶顶
> 
> 希望能有两种操作——
> 
> 1、移动到其他数据库 2、添加到其他数据库
> 
> 第一种方式就能自动删除在本数据库中的记录

移动比添加后删除直观点，但可能得提示一下在当前库的属性不会被转移过去

**Comment by TCOTC** [comment]
保险一点，属性也应该考虑一下

菜单：

- 转移条目
  - **将主键**复制到数据库
  - **将主键**移动到数据库
  - **将主键及属性**复制到数据库
  - **将主键及属性**移动到数据库

移动属性时：

- 如果目标数据库**有**对应的同名属性列，就直接添加；
- 如果目标数据库**没有**对应的同名属性列，就自动创建

**Comment by 88250** [comment]
字段不考虑复制移动了，库不一样复用值会有问题，先做添加块和移动块。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Mon, Apr 8, 2024 12:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Blocks bound in the database support `Add toDatabase` and `Move to Database` (Issue #10929)




 
保险一点，属性也应该考虑一下
 
菜单：
  
转移条目  
将主键复制到数据库
 
将主键移动到数据库
 
将主键及属性复制到数据库
 
将主键及属性移动到数据库
  
  
移动属性时：
  
如果目标数据库有对应的同名属性列，就直接添加；
 
如果目标数据库没有对应的同名属性列，就自动创建

**Comment by TCOTC** [comment]
但是移动块没法撤回，只移动主键，属性咋办？

**Comment by 5kyfkr** [comment]
> 但是移动块没法撤回，只移动主键的话，属性咋办？

移动属性也要做完整感觉要花挺多精力，毕竟每个库的字段可能都不一样，我这里主键能方便添加过去就基本够用了

**Comment by 5kyfkr** [comment]
如果要做属性合并或复制应该需要做个对比界面，就是对比现有库的字段要放到目标库的哪一列，给个对应选择的功能会直观很多

**Comment by 88250** [comment]
那要不还是仅先做 添加 吧



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Mon, Apr 8, 2024 12:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Blocks bound in the database support `Add toDatabase` and `Move to Database` (Issue #10929)




 
但是移动块没法撤回，只移动主键，属性咋办？

**Comment by 5kyfkr** [comment]
> 那要不还是仅先做 添加 吧

可以，先做添加，或者做个移动但是有弹窗提示确认会丢失属性(移动可以减少删除现有库行的重复操作)，后续也会知道有多少人需要移动属性的功能。

**Comment by 88250** [comment]
还是就仅考虑 添加 吧。

**Comment by TCOTC** [comment]
> @5kyfkr : 数据库主键可以添加到其他数据库

@Vanessa219 不应该只是主键绑定了块的条目可以 `Add to Database` ，纯文本主键也需要

![image](https://github.com/siyuan-note/siyuan/assets/78434827/37cb9d38-01fc-4b47-a596-9849763f837f)

@Vanessa219 多选条目也需要

**Comment by 5kyfkr** [comment]
> @Vanessa219 不应该只是主键绑定了块的条目可以 `Add to Database` ，纯文本主键也需要

确实这个我没发现，需要补上好点

> @Vanessa219 多选条目也需要

多选如果实现复杂就算了，我大部分情况下够用

**Comment by TCOTC** [comment]
> 多选如果实现复杂就算了，我大部分情况下够用

我刚好需要这个多选添加，所以我是非常支持的

而且如果纯文本主键能 `Add to Database ` 了，就是说所有主键都能了，那么在这个基础上增加多选应该是没太大难度的

**Comment by TCOTC** [comment]
> 纯文本添加不了，必须是一个已有块才行。

没有办法实现吗？

**Comment by Vanessa219** [comment]
@88250

**Comment by 5kyfkr** [comment]
或者多选能不能不做纯文本的，多选时纯文本项目不给点选，我不习惯放纯文本到数据库里，因为纯文本无法在数据库里制卡

**Comment by 88250** [comment]
> > 纯文本添加不了，必须是一个已有块才行。
> 
> 没有办法实现吗？

* 如果采用绑定块的方案，必须创建文档块然后绑定
* 如果不采用绑定块的方案，那和复制粘贴主键就一样了，和其他绑定块的处理不一致

这两种方案都有各自的问题，所以最好还是不处理。

**Comment by 5kyfkr** [comment]
> > > 纯文本添加不了，必须是一个已有块才行。
> > 
> > 
> > 没有办法实现吗？
> 
> * 如果采用绑定块的方案，必须创建文档块然后绑定
> * 如果不采用绑定块的方案，那和复制粘贴主键就一样了，和其他绑定块的处理不一致
> 
> 这两种方案都有各自的问题，所以最好还是不处理。

不能同时两种方案一起弄进去嘛，毕竟是两种类型不可能用相同方案整的吧

**Comment by 88250** [comment]
@5kyfkr 没明白你的意思

**Comment by 5kyfkr** [comment]
> > 不能同时两种方案一起弄进去嘛，毕竟是两种类型不可能用相同方案整的吧
> 
> @5kyfkr 没明白你的意思

就是能否添加前先判断主键是纯文本还是绑定块，如果是纯文本就执行方案二，绑定块就执行方案一

**Comment by 88250** [comment]
> 就是能否添加前先判断主键是纯文本还是绑定块，如果是纯文本就执行方案二，绑定块就执行方案一

这两个方案都是针对非绑定块的，因为绑定块已经有很明确的方案了：直接添加即可。

但是就像上面说的，对于非绑定块，这两个方案都有各自的问题，所以并不可行。

**Comment by 5kyfkr** [comment]
> > 不能同时两种方案一起弄进去嘛，毕竟是两种类型不可能用相同方案整的吧
> 
> @5kyfkr 没明白你的意思。对于非绑定块如果要 `添加到数据库`，这两种方案都有问题，还有其他方案么？

就执行复制粘贴就行了，能移过去就完事

**Comment by 88250** [comment]
问题就是可能会不一致，因为之前只有块才能 添加到数据库

**Comment by 5kyfkr** [comment]
> 问题就是可能会不一致，因为之前只有块才能 添加到数据库

噢噢我理解了，那就这样：
判断：是否是数据库内的主键的纯文本（排除笔记里的纯文本）。
如果是就执行复制粘贴到目标数据库
如果不是，就执行绑定块的操作到目标数据库

**Comment by TCOTC** [comment]
> > > 纯文本添加不了，必须是一个已有块才行。
> > 
> > 
> > 没有办法实现吗？
> 
> * 如果采用绑定块的方案，必须创建文档块然后绑定
> * 如果不采用绑定块的方案，那和复制粘贴主键就一样了，和其他绑定块的处理不一致
> 
> 这两种方案都有各自的问题，所以最好还是不处理。

绑定了块的主键可以直接添加过去，那纯文本主键直接复制粘贴过去会遇到什么问题吗？

**Comment by 88250** [comment]
技术上没有问题，我说的是设计上的不一致要不要考虑。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/11093

**Comment by 5kyfkr** [comment]
> 技术上没有问题，我说的是设计上的不一致要不要考虑。

这个issue本质上是方便数据在数据库之间的转移，如何数据库本身支持纯文本，那应该是需要一起转过去的，非绑定这个设计应该是数据库一开始主键特性讨论的范畴吧，这个只是特性的延伸

**Comment by TCOTC** [comment]
> 技术上没有问题，我说的是设计上的不一致要不要考虑。

还是应该考虑的，所有**主键**都应该能 `添加到数据库` ，这个是主键的一致性；所有**块**都可以 `添加到数据库` ，这个是块的一致性。应该分开考虑

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/11093 中实现复制非绑定块。
