### ISSUE TITLE
Please enter the title of the feature request

### ISSUE THREAD

**Issue by github123-hzg** [siyuan-note/siyuan#10921]
### In what scenarios do you need this feature?

代码框升级建议

### Describe the optimal solution

能不能想截图一样给代码框添加局部重点标记
<img width="1536" alt="Snipaste_2024-04-07_14-59-50" src="https://github.com/siyuan-note/siyuan/assets/55234137/04c9b798-b87e-4754-ab38-215fcf27fd7e">

**Comment by 88250** [comment]
抱歉这个实现不了。
