### ISSUE TITLE
通过/api/attr/setBlockAttrs接口为父任务块设置自定义属性会导致子任务块的自定义属性被清除

### ISSUE THREAD

**Issue by syh19** [siyuan-note/siyuan#10928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [x] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="251" alt="image" src="https://github.com/siyuan-note/siyuan/assets/47665360/bfe2b35b-a167-4912-99df-767c881ed6c1">

有三个任务节点关系如上图所示。在插件开发过程中，点击勾选任务前面的复选框，借助`/api/attr/setBlockAttrs`接口为`子任务节点111`添加了自定义属性`plugin-task-list-finished=\"20240407231618\"`，此时已成功添加到字段`ial`中。但是当勾选父任务节点通过接口为父节点添加自定义属性`plugin-task-list-finished`后，父节点添加成功了，然而子任务的自定义属性被清除了。

### Expected result

期望修改父任务节点的自定义属性时不要干扰到子节点的自定义属性。

### Version environment

```markdown
- Version: v3.0.7
- Operating System: MacOS M1
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/14897764/siyuan.log)

**Comment by 88250** [comment]
> 点击勾选任务前面的复选框

这个动作是在编辑器中做的吗？插件操作实现的过程麻烦再补充一下，或者补充一下我在不安装插件的情况下应该如何重现该问题，谢谢。

**Comment by syh19** [comment]
> > 点击勾选任务前面的复选框
> 
> 这个动作是在编辑器中做的吗？插件操作实现的过程麻烦再补充一下，或者补充一下我在不安装插件的情况下应该如何重现该问题，谢谢。

对的，这个动作是在思源的编辑器中实现的，具体实现逻辑如下：监听事件`ws-main`，通过解析这个时间的回调参数来判断当前编辑的节点是否是任务节点，如果不是任务节点则忽略，如果是任务节点就根据DOM节点中`protyle-task--done`类来判断完成状态，进而通过接口`setBlockAttrs`来为该节点添加自定义属性`plugin-task-list-finished`。完成添加具体时间，取消完成就把这个属性置空。

不安装插件的话我觉的可以先设置一组父子任务节点，然后通过postman之类的工具进行接口调用：
1. 使用接口`setBlockAttrs`首先为子节点设置自定义属性【不要加`custom-`前缀】
2. 然后通过`/api/query/sql`查询接是否成功添加了`ial`字段，此时子节点已经添加成功
3. 为父节点通过接口`setBlockAttrs`添加同样的自定义属性
4. 最后通过`/api/query/sql`查询这两个节点，发现父节点成功添加，而子节点的自定义属性被清空了

**Comment by 88250** [comment]
收到，明天我测试看看。

**Comment by 88250** [comment]
看了下，是因为自定义属性没有以 `custom-` 开头，一旦编辑就会被去掉。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by syh19** [comment]
> 看了下，是因为自定义属性没有以 `custom-` 开头，一旦编辑就会被去掉。

好的 D大，那我添加上`custom-`前缀吧。
