### ISSUE TITLE
行级公式异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复现流程：

1. 在一个空段落块内随便填点内容
2. 复制为引用块
3. 粘贴到另一个空段落块内
4. 修改锚文本
5. 转换为链接
6. 在后面添加行级公式

![公式](https://github.com/siyuan-note/siyuan/assets/78434827/d68be830-09e7-483a-9c50-31b85a904c70)

点击异常的行级公式后有概率导致点击页面按钮无响应

### Expected result

修复行级公式异常

### Version environment

```markdown
- Version: v3.0.8-dev1.5
- Operating System: 
- Browser (if used):
```

### Log file

.

**Comment by Vanessa219** [comment]
由于是概率问题，还麻烦更新后再测测。多谢。
