### ISSUE TITLE
改进列表折叠与展开，优化单个列表块的性能

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10936]
### In what scenarios do you need this feature?

目前的列表一次性加载全部层级的内容，这个机制对纯大纲使用者不太友好，在使用一个列表块的情况下打开文档要加载完整个文档的内容，列表项块数越多性能就越差。改为像标题折叠与展开那样动态加载的话能提高性能、使用更流畅

### Describe the optimal solution

打开文档时优先加载展开的内容块，预加载 ( #10935 ) 折叠的内容块

![image](https://github.com/siyuan-note/siyuan/assets/78434827/314e5402-9008-4d4f-99a8-2cc38a6d47dd)

**Comment by UFDXD** [comment]
不推荐。
会引出很多问题。
如果要提升性能的话，不如考虑优先 https://github.com/siyuan-note/siyuan/issues/10809 分散主窗口渲染压力

**Comment by TCOTC** [comment]
> 不推荐。 会引出很多问题。 如果要提升性能的话，不如考虑优先 #10809 分散主窗口渲染压力

#10809 似乎与该 issue 无关，并不能提高纯大纲笔记的性能

**Comment by UFDXD** [comment]
> > 不推荐。 会引出很多问题。 如果要提升性能的话，不如考虑优先 #10809 分散主窗口渲染压力
> 
> #10809 似乎与该 issue 无关，并不能提高纯大纲笔记的性能

几十个分屏，几十个大文档，你到新窗口再看，实际体验才有发言权

**Comment by TCOTC** [comment]
> 几十个分屏，几十个大文档，你到新窗口再看，实际体验才有发言权

那就是在极少数特定情况下了。

我提的这个 issue 是能显著提高性能的，只是如果不实现「预加载」的话，「动态加载」反而会降低非纯大纲笔记用户的体验，所以只能暂时搁置本 issue 了。

**Comment by UFDXD** [comment]
@TCOTC 其实这个要动态加载，就得像标题那样 折叠展开延迟一两秒了

**Comment by zongqir** [comment]
觉得没什么意义
这个也应该记住上次的关闭操作吧 这就太麻烦了
作者只有两个人啊

**Comment by TCOTC** [comment]
> 觉得没什么意义

你应该不用纯大纲

> 这个也应该记住上次的关闭操作吧 这就太麻烦了

如果你指的是折叠状态，现在就是会“记忆”的

**Comment by jih3657** [comment]
关注一下 以前试过用纯大纲编辑多层级的内容很卡

**Comment by 88250** [comment]
不考虑了，没有好的实现方案。
