### ISSUE TITLE
`Add to Database` search on database title only

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#10934]
添加到数据库功能搜索数据库第一个字符时无法匹配

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下图，这是在全新的工作空间下，除了那个主题概念库是从我的笔记本中导出来的，其他都是刚创建的库
![image](https://github.com/siyuan-note/siyuan/assets/63196026/0b43a4fe-ce86-474d-88a8-99f5d485eb68)
搜索新建的库打第一个“文”字的时候会出现对应的库，这是正常情况。
![image](https://github.com/siyuan-note/siyuan/assets/63196026/e89a8c95-6673-4f0c-a547-8b50aea76c19)
可是打“主”字的时候，感觉没有搜索到对应的主题库，显示了许多无关项目
![image](https://github.com/siyuan-note/siyuan/assets/63196026/84d15fc4-50d8-493e-b74b-c58a3f02d187)
然后再多打一个字就会正常搜到
![image](https://github.com/siyuan-note/siyuan/assets/63196026/815c3e23-5d39-4096-ba5e-d3ba16624eda)

以下是导出的笔记本，可以复现
[123.sy.zip](https://github.com/siyuan-note/siyuan/files/14902458/123.sy.zip)

### Expected result

打第一个字应能正常搜索

### Version environment

```markdown
- Version: 3.0.8 Dev2
- Operating System:win10 
- Browser (if used):
```

### Log file

无报错

**Comment by TCOTC** [comment]
好像只要是单个字就会有问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/aa66e4c2-2d0c-4aed-8dee-a5bfdd804972)

**Comment by 5kyfkr** [comment]
> 好像只要是单个字就会有问题：

是滴，很奇怪，新建工作空间的新数据库又没问题

**Comment by 88250** [comment]
因为这是在数据库块上搜索（和全局搜索一样），所以会匹配中数据库中的内容。

**Comment by 5kyfkr** [comment]
> 因为这是在数据库块上搜索（和全局搜索一样），所以会匹配中数据库中的内容。

不太好吧，这个只是对数据库标题进行搜索应该就够了

**Comment by 5kyfkr** [comment]
> 因为这是在数据库块上搜索（和全局搜索一样），所以会匹配中数据库中的内容。

不太好吧，这个只是对数据库标题进行搜索应该就够了

**Comment by 88250** [comment]
嗯，那就改成仅搜索数据库标题吧。

**Comment by 88250** [comment]
不需要重建索引，之前发的信息有误，抱歉抱歉。

**Comment by 5kyfkr** [comment]
> 不需要重建索引，之前发的信息有误，抱歉抱歉。

好滴

**Comment by 5kyfkr** [comment]
试了好用很多，妈妈再也不用担心我找不到对应的数据库了
