### ISSUE TITLE
块转化为 有序列表、无序列表、任务列表 快捷键的设置

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10944]
### In what scenarios do you need this feature?

https://ld246.com/article/1699335828699

### Describe the optimal solution

块转化为 有序列表、无序列表、任务列表 可以设置快捷键

**Comment by leeyaunlong** [comment]
多个连续的无序列表/任务列表能同时合并吗?

**Comment by 88250** [comment]
> 多个连续的无序列表/任务列表能同时合并吗?

不能，因为有的情况是刻意分开的。

**Comment by 88250** [comment]
楼主后续请关注 https://github.com/siyuan-note/siyuan/issues/10361
