### ISSUE TITLE
加载界面适配明亮模式

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10943]

**Comment by Vanessa219** [comment]
需要获取主题

**Comment by 88250** [comment]
这个不是那么重要，大部分程序的加载界面一般也是统一的，不会和主题模式匹配，所以不考了。

**Comment by TCOTC** [comment]
系统是浅色、主题是明亮模式，重载界面的时候整个黑下来就感觉很别扭

**Comment by TCOTC** [comment]
用户反馈：

![Image](https://github.com/user-attachments/assets/0299030e-b505-433b-8b85-dbce0298b350)
