### ISSUE TITLE
---的菜单项不应该添加至数据库

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图所示，---的菜单项不应该添加至数据库。

![image](https://github.com/siyuan-note/siyuan/assets/54077803/3df99963-7191-42b3-a919-12f321b8bf68)

### Expected result

1

### Version environment

```markdown
- Version: 3.0.7
- Operating System: win10
- Browser (if used):
```

### Log file

no

**Comment by TCOTC** [comment]
其实我觉得留着也可以，能用来定位。实现 #10946 之后还能给分隔线块命名

**Comment by 88250** [comment]
分隔线本身是个块级元素，不支持加的话有的不统一。另外，加了好像也没有副作用。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
