### ISSUE TITLE
数据库筛选支持逻辑判断

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10949]
### In what scenarios do you need this feature?

[数据库的几个功能需求 - 链滴](https://ld246.com/article/1712645912571) Point 3

> 比如无法过滤出“A 列的值=5，或者 A 列的值=6”的行，目前一列只能做一次过滤条件

### Describe the optimal solution

比如这样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c25abcd2-8ef7-47e6-88cd-a1cfdfe38b22)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10550
