### ISSUE TITLE
为---块，添加自定义属性，用于css美化

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#10946]
### In what scenarios do you need this feature?

一般来说，---可以用作文档的分割用来划分不同的区域板块。
但是在很多场景下分割的意义有所不同，希望可以通过改变样式来进行区分。

为其添加样式一个最简单的方法就是监测这个块对应的html元素属性。
我在想能不能通过 SiYuan 内置的添加自定义属性来，尝试实现我想要的效果。

![image](https://github.com/siyuan-note/siyuan/assets/54077803/40e57c62-11f3-402e-a206-5e52aa0ac639)

### Describe the optimal solution

允许为这个块设置自定义属性。

**Comment by LGRemdo** [comment]
> 我觉得直接改就好了，用自定义属性有点多余
> 
> ```css
> /* 更改分割线样式 CSS片段 */
> .hr {
>   border: none;
>   position: relative;
> }
> 
> .hr::before {
>   content: "";
>   position: absolute;
>   top: 50%;
>   left: 0;
>   right: 0;
>   height: 2px; /* 粗细 */
>   background-color: yellow; /* 颜色 */
>   transform: translateY(-50%);
> }
> ```

我需要很多类别的，比如蓝色的红色的、双线的单线、虚线的、实线的。。。
不同场景不同含义

**Comment by 5kyfkr** [comment]
> 我需要很多类别的，比如蓝色的红色的、双线的单线、虚线的、实线的。。。 不同场景不同含义

分割线也可以添加背景颜色，应该够用了吧，虚线确实没辙了

**Comment by UFDXD** [comment]
以前可以，我也高过自定义样式，不过早就改了

**Comment by Achuan-2** [comment]
这就跟blockquote自定义样式一样，建议看看自定义块样式插件，自己改改，加个分割线功能的

**Comment by 88250** [comment]
抱歉这个不考虑改变了，感谢反馈。

**Comment by TCOTC** [comment]
可以做个插件往里面写 Style

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1e8ecb13-d496-42c9-b722-12087b5a4174)

**Comment by LGRemdo** [comment]
> 可以做个插件往里面写 Style
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/332268386-1e8ecb13-d496-42c9-b722-12087b5a4174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4ODQ5NjMsIm5iZiI6MTcyMTg4NDY2MywicGF0aCI6Ii83ODQzNDgyNy8zMzIyNjgzODYtMWU4ZWNiMTMtZDQ5Ni00MmM5LWI3MjItMTIwODdiNWE0MTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA1MTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkM2NmYzg0MGMyMjVmOGU0ZmMyMGQ1NWY2NmY2OWNlMTI2NjZkOGY3ZTIxNTRjZGZlYjIwYTI0NTMxNDFkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M221W8H-kK3iTzzCbwF56BKYZdA8WItfscEZ_R4_sVE)

这个只可以写一次
