### ISSUE TITLE
折叠块编辑时没有新建一个块

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#1094]
### 描述问题 Describe the problem

现状：在折叠块后继续编辑把内容附加到被折叠的块上

### 期待的结果 Expected result
在折叠块后继续编辑应该新建一个块而不是把内容附加到被折叠的块上

### 截屏或录屏演示 Screenshot or screen recording presentation

![siyuan](https://user-images.githubusercontent.com/16791452/104741235-e63cab00-5783-11eb-9c85-4907583af465.gif)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by Vanessa219** [comment]
这个取决于折叠块下的块是否属于该折叠块。
