### ISSUE TITLE
希望支持触控手势

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#1095]
希望支持触控手势
比如触屏的缩放和移动功能
这点在使用脑图试图的时候感觉比较实用

**Comment by 88250** [comment]
你好，现在应该是支持缩放的，只是可能响应有点慢，如果不好用的话还是用工具的缩放按钮，这块暂时没有精力改进，见谅。

**Comment by yanyu2015** [comment]
> 你好，现在应该是支持缩放的，只是可能响应有点慢，如果不好用的话还是用工具的缩放按钮，这块暂时没有精力改进，见谅。


刚刚试了下，关系图的确是支持手势的
D大加油吧，等正式版出了有时间可以支持下脑图的手势
