### ISSUE TITLE
Set cursor after "add to database"

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10958]
### In what scenarios do you need this feature?

在处于编辑状态时，使用快捷键将块添加到数据库后，光标不应该消失，应该保持编辑状态。和快速制卡一样。

### Describe the optimal solution

无

**Comment by Jiangshuon** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/67137548/a2405087-53cf-4a63-a57d-66e05a0376cd)


这个新版本好像没实现，我意思是这个光标在《添加到数据库》后不要消失，不然还要用鼠标重新进入编辑状态

**Comment by Jiangshuon** [comment]
@Vanessa219 大佬瞅瞅

**Comment by Vanessa219** [comment]
这里最后添加好以后光标在行首

https://github.com/siyuan-note/siyuan/assets/970828/4d0cb9c5-0cb7-4067-ac37-4cdec125b449
