### ISSUE TITLE
Horizontal scroll bar do not appear in tab dock by default

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#10954]
https://ld246.com/article/1712641046582/comment/1712642767861?r=Vanessa#comments

**Comment by TCOTC** [comment]
好像还没修好

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e03aea04-5447-4c55-ad46-68711729a811)

**Comment by TCOTC** [comment]
> 好像还没修好

自己打包的 dev 版不行，3.0.9 就行了

**Comment by Vanessa219** [comment]
要强制刷新一下
<img width="525" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/36680a0e-b5a2-4874-9ae2-bbeed67230d5">
