### ISSUE TITLE
最新版本，点击《添加到数据库》后，展示出来的数据库列表不再按更新时间排序了

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

好像每次都不一样。

之前是按更新时间排序的。

https://github.com/siyuan-note/siyuan/issues/10360

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
确实。

按更新时间排序挺方便的，不需要搜索就可以直接添加了

**Comment by 88250** [comment]
感谢反馈，这个问题在 https://github.com/siyuan-note/siyuan/issues/10952 中一并解决。
