### ISSUE TITLE
列表项中包含的代码块没有正确折叠

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#1096]
### 描述问题 Describe the problem

目前思源对列表项中的代码块没有折叠
### 期待的结果 Expected result

如果代码块属于某个列表项，应当一并折叠

### 截屏或录屏演示 Screenshot or screen recording presentation

![siyuan](https://user-images.githubusercontent.com/16791452/104745549-323e1e80-5789-11eb-9ce0-242fba362e18.gif)

### 版本环境 Version environment

* 版本 Version：win 10
* 操作系统 Operating system：0.6.0
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，这样折叠的只是列表项下面第一个段落块，折叠列表项的话用这个：

![image](https://user-images.githubusercontent.com/873584/104807965-c659c580-581d-11eb-8184-9e79d8bd23b9.png)
