### ISSUE TITLE
调整宽度时右键操作栏透明

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#10963]
### In what scenarios do you need this feature?

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/5e79e683-756c-47b4-bf12-6dbfab08a327)
如图，完全被挡住了

### Describe the optimal solution

调宽度其他选项也用不到，变透明可以吗

### Describe the candidate solution

做成可选项

**Comment by Vanessa219** [comment]
没太理解，是篮框里面的内容变透明，也就是消失么？
<img width="396" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/e3833325-0a55-4da6-8c8c-4d6cc4638781">

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/154863885/083292b6-8eee-48c0-83da-4a52a60009e9)
我希望是这部分透明

**Comment by AvoidantPerDis** [comment]
它挡住调整宽度的内容了

**Comment by TCOTC** [comment]
@Vanessa219 意思就是在调整页面宽度的时候把所有菜单变得透明一些，方便查看调整宽度后的效果。

我也需要。

**Comment by Vanessa219** [comment]
这样？好像效果不太明显呀
<img width="963" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/03fa6fc2-4463-4a73-aeb8-d560dc6956d8">

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/154863885/77c149d5-95e4-4887-84cf-9b45b65d54db)
是这个透明（30%左右？）

**Comment by TCOTC** [comment]
> 这样？好像效果不太明显呀，还有点干扰。

在鼠标点击滑动条的 0.3s 后，让菜单变得几乎完全透明，包括菜单的 背景色、阴影、字体、图标

**Comment by Vanessa219** [comment]
嗯，看来还是 https://github.com/siyuan-note/siyuan/issues/9521  这样更好。

**Comment by AvoidantPerDis** [comment]
> 嗯，看来还是 https://github.com/siyuan-note/siyuan/issues/9521  这样更好。

这个有计划吗

**Comment by Vanessa219** [comment]
有计划的，我先加入 backlog 里面提高优先级。
