### ISSUE TITLE
自定义图片的默认缩放

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1097]
建议添加自定义默认缩放

在我的计算机上，每次粘贴完图片几乎都需要按右键选中菜单，然后缩放到50%以下，这个重复操作太繁琐，如果在设置项中加入相关的设置，会极大的提高效率

**Comment by Andy-AO** [comment]
检查了设置面板没有发现相关的设置

**Comment by Andy-AO** [comment]
当然目前可以用脚本暂时的变相实现,思路就是hook `Ctrl+V`,发现剪切板当前的内容是图片,那么就会在粘贴后,追加html标签,但我还没有尝试过.这里全当记录了.

**Comment by 88250** [comment]
通过外部扩展吧，因为并不是每个时候都需要默认缩放设置，谢谢。
