### ISSUE TITLE
《添加到数据库》后出现的数据库列表位置不对

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

之前版本，该列表紧挨在该块的下面，现在跑到最上面去了

![image](https://github.com/siyuan-note/siyuan/assets/67137548/57b159f5-6a17-41b3-9bbd-c5df83ce75ac)

### Expected result

之前版本

![image](https://github.com/siyuan-note/siyuan/assets/67137548/31643722-66cd-43a5-803a-155d9ce2cf1b)

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
感觉这个是要看够不够地方放窗口的

**Comment by 88250** [comment]
嗯，这个是动态计算的，和版本应该没有关系。

**Comment by Jiangshuon** [comment]
之前版本一屏默认只展示7个，大小刚好合适。新版本一屏默认展示10个以上，太大了，就自动移动到了上面显示

**Comment by 88250** [comment]
我看了下代码，没有默认 7 个的，之前最大是 16 个，目前是改为 12 个。

**Comment by Jiangshuon** [comment]
比较老的版本，3.0.5版本，是7个

![image](https://github.com/siyuan-note/siyuan/assets/67137548/ea66058a-3481-4568-b7ef-189e2c96ee18)

**Comment by 88250** [comment]
我数了下截图里好像是 8 个 😂 

这个怕是前端计算固定一下高度？ @Vanessa219

**Comment by Vanessa219** [comment]
分页数应该是一个固定值，不会随着屏幕大小变化。否则感觉搜索结果数量会不正常。

**Comment by 88250** [comment]
@Vanessa219 是固定的 `12`，但是有的时候 12 会觉得太大，影响下拉框的位置，我意思是能不能根据屏幕高度计算一下下拉框高度，让其尽量出现在下方。

**Comment by Jiangshuon** [comment]
感觉改成8个就行，这个位置，刚好触底

<img width="719" alt="93592e8c8dd21e9a31a8ef7d81e951a" src="https://github.com/siyuan-note/siyuan/assets/67137548/38d175de-2d5b-4970-a186-d9377c248eb3">

**Comment by 88250** [comment]
屏幕大的话 8 个少了点。

**Comment by TCOTC** [comment]
> 是固定的 `12`，但是有的时候 12 会觉得太大，影响下拉框的位置，我意思是能不能根据屏幕高度计算一下下拉框高度，让其尽量出现在下方。

添加滚动条

**Comment by Jiangshuon** [comment]
@88250  大佬，要不就改成8个或7个吧，这可能是最简单的修改方式了，我看块引用搜索也是显示7个

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
这个和个数没有关系，上部空间大就会显示在上部，要充分利用空间。

**Comment by TCOTC** [comment]
> 这个和个数没有关系，上部空间大就会显示在上部，要充分利用空间。

输入框离得太远，体验很割裂

**Comment by Jiangshuon** [comment]
> 这个和个数没有关系，上部空间大就会显示在上部，要充分利用空间。

有关系吧，不是影响框的大小嘛，新版本的框明显大很多（见图）

![Screenshot_20240413152831](https://github.com/siyuan-note/siyuan/assets/67137548/3a2e2ef6-2613-4ffa-9da9-fdc3d856b480)

**Comment by Vanessa219** [comment]
可以把滚动条往下移动一点。

**Comment by Jiangshuon** [comment]
@Vanessa219 v大，再考虑下嘛，我好奇为啥没其他人提这个问题，难道是我电脑问题。。。

从第7行开始，数据库就出现在左上角了，对比块引却不会。。。

这样输入的时候，视线总是会被迫移到左上角，还是希望尽量出现在光标的位置，至少在同一垂直方向上，而不是跑到左上角

### 数据库列表

<img width="764" alt="806ace6fb255f0a4ce18795e2461ebc" src="https://github.com/siyuan-note/siyuan/assets/67137548/f6f1d01d-6447-4e73-be21-a1f8ee0ae524">

### 块引列表

<img width="1025" alt="8cb5ddb4e62f8afb682f716b771ff2f" src="https://github.com/siyuan-note/siyuan/assets/67137548/507aa5dc-7ac6-40ab-9155-ac4308e6f581">

**Comment by Vanessa219** [comment]
可以把 。。。8 往上滚动一点。这是选中面积大的进行显示。
