### ISSUE TITLE
Improve marketplace loading performance

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#10973]
降低延迟，减少转圈，减少重载

### In what scenarios do you need this feature?

https://ld246.com/article/1712593921358/comment/1712671108438

有的延迟，要降低的话技术上可能有难点。但有的我真想不明白。

1. 设置-集市，我新建一个工作空间，关闭安全模式，里面一个东西也没下载。为什么这个时候打开集市也要转圈？
而且吧，集市这个转圈有的时候就是加载不出来，一直转，很烦人。我这梯子质量挺好的，YouTube GitHub速度都很快，obsidian那边打开插件市场、主题市场都是加载很快，思源这边就不行。

2. 为什么文档块内搜索，打开的搜索窗也要转圈？这什么内容都不显示，转圈是为了啥。全局搜索，我觉得还有可能是因为要加载块太麻烦，所以不得不转圈，文档内搜索也这样，我不能理解。
<img width="864" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/eabe9834-3cb8-4a92-b404-ae7d49cea021">

关于重载。我觉得这个进度条界面的“侵入性”要比整一个大logo要轻得多，所以希望多用这种方式去加载，尽量少用下面那种方式，下面这种方式最好只在打开软件时出现，其它情况下都不这么干。
<img width="864" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/17e7b99d-4c78-460d-8cc6-f7ef9d225fcc">

<img width="1728" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/21563a23-46ba-4860-9b97-f250635c5aa4">

### Describe the optimal solution

.

**Comment by TCOTC** [comment]
> 设置-集市，我新建一个工作空间，关闭安全模式，里面一个东西也没下载。为什么这个时候打开集市也要转圈？

这个确实感觉有点慢

**Comment by UFDXD** [comment]
这个的确需要优化一波了，现在日常转圈

**Comment by UFDXD** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/97731736/cd6f6957-69d2-4281-ba04-baad414f75b7)

![image](https://github.com/siyuan-note/siyuan/assets/97731736/ad932981-38e6-439f-bede-341040e63fc0)

不知道要等多久

**Comment by TCOTC** [comment]
@UFDXD 更新 3.0.9 之后重建索引，然后再试试

**Comment by 5kyfkr** [comment]
集市的转圈感觉可以优化，能不能先显示已经安装的插件，检查更新时是在后台检查并记忆更新情况，这样就不用每次进去看着转圈了

**Comment by TCOTC** [comment]
> 集市的转圈感觉可以优化，能不能先显示已经安装的插件，检查更新时是在后台检查并记忆更新情况，这样就不用每次进去看着转圈了

我赞同这个，更新区域可以默认折叠

**Comment by UFDXD** [comment]
> @UFDXD 更新 3.0.9 之后重建索引，然后再试试

我会不知道？！（笑哭

**Comment by 88250** [comment]
> 集市的转圈感觉可以优化，能不能先显示已经安装的插件，检查更新时是在后台检查并记忆更新情况，这样就不用每次进去看着转圈了

后台倒是可以考虑缓存一波（反正现在也是 6 小时的包索引缓存，只是具体包没有缓存）。

---

@LoneFireBlossom 搜索转圈是正常现象，考虑到网络请求和后端处理都需要时间，所以加了转圈的动画。

---

@UFDXD SQLite 写入时会阻塞所有查询，估计是没有办法优化了。

**Comment by LoneFireBlossom** [comment]
> > 集市的转圈感觉可以优化，能不能先显示已经安装的插件，检查更新时是在后台检查并记忆更新情况，这样就不用每次进去看着转圈了
> 
> 后台倒是可以考虑缓存一波（反正现在也是 6 小时的包索引缓存，只是具体包没有缓存）。
> 
> @LoneFireBlossom 搜索转圈是正常现象，考虑到网络请求和后端处理都需要时间，所以加了转圈的动画。
> 
> @UFDXD SQLite 写入时会阻塞所有查询，估计是没有办法优化了。

网络请求是啥意思？我现在用的是客户端。
对一片空白的文档执行文档内搜索，后端处理啥需要时间呢？

**Comment by 88250** [comment]
@LoneFireBlossom 桌面端/移动端使用的话网络时间可以忽略，浏览器使用的话忽略不了，所以加了转圈的动画。不过特殊场景可能可以优化一下，比如 桌面端/移动端并且 Ctrl+F 搜索关键字为空 的情况我认为可以考虑去掉加载动画 @Vanessa219

**Comment by LoneFireBlossom** [comment]
另外关于我提到的重载方式的讨论，不知大家觉得怎么样。
我至今对我第一次重载时突然出现的那个黑红界面记忆犹新，当时我被吓了一大跳。所以我希望有一个侵入性比较小的方式。

**Comment by 5kyfkr** [comment]
> 另外关于我提到的重载方式的讨论，不知大家觉得怎么样。 我至今对我第一次重载时突然出现的那个黑红界面记忆犹新，当时我被吓了一大跳。所以我希望有一个侵入性比较小的方式。

我感觉是思源logo的配色和样式过于硬朗了，放大之后就会比较难蚌，所以我也觉得这个重载界面还是跑进度条会好点

**Comment by LoneFireBlossom** [comment]
> 载入界面暂时不动了吧。

我不明白，为什么暂时不动了就要关闭issue？这个问题前几天还讨论过：
https://github.com/siyuan-note/siyuan/issues/10584#issuecomment-2037669655

> 还有一个问题啊，对于这种未来肯定要解决，现在是因为遇到了困难，或者优先级别不是那么高，所以搁置的问题，真的关闭这个issue就好了吗？我觉得是不是用一个其他的方法更好。比如说虽然关掉了这个issue，但是打上一个future plan之类的标签。

> 如果只是关闭了这个帖子，而没有做一些备注或者统计的话，以后可能会忘掉其中的一部分提议。我开发者可能会忘掉，用户可能也会忘掉，或者流失了，不再提这个建议了。

> 我目的不是说仅仅把这一个issue打开，而是需要标注所有「值得后续优化的问题」issue。但如果这种issue都保持打开状态的话恐怕不符合开发者的习惯吧，我看思源的issue区，open状态的很少，和某些攒了上千个open issue的项目很不一样。
所以可以考虑加标签这种方式，等大工程都搞得差不多了再从关闭的带相关标签的issue里随机抽一些拿出来研究怎么改进

开发者既然说“暂时不动”，那应该是觉得有改动的必要，所以为什么要关闭？还是说开发者认为没有改的必要呢？

**Comment by 88250** [comment]
你认为有改动的必要的话麻烦单独提 issue 记录。

这个 issue 我们已经重命名为解决集市加载了，麻烦提 issue 的时候一个 issue 对应一个问题，不要一个 issue 对应不同的问题，谢谢。
