### ISSUE TITLE
表格像图片那样，支持填写标题

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#10977]
### In what scenarios do you need this feature?

想给表格添加一个说明，在块属性里添加能一定程度上实现，但标题是右对齐的，不如图片标题那样居中淡化美观。也不想使用文本块然后和表格拼成超级块那样的形式

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/e3f07324-ce2a-4d39-a7f4-86c99602d068)

### Describe the optimal solution

允许块属性居中？

**Comment by 88250** [comment]
@Vanessa219 帮忙看看自定义属性+CSS 代码片段能否实现。

**Comment by HowcanoeWang** [comment]
或许代码块、视频之类的也挺适合给加个标题啥的？

**Comment by 88250** [comment]
视频的有个提议： https://github.com/siyuan-note/siyuan/issues/9160

**Comment by wind-kisses** [comment]
支持给代码块增加可选填的标题~
放在下图红框中或者底部都很好。
最希望的是代码块折叠后标题能够显示😗省去要专门另起一行写“下面是xxxx代码：”的麻烦。
![image](https://github.com/siyuan-note/siyuan/assets/102211604/acdc0d8b-bb9e-4162-8fd6-a165833e7e45)

**Comment by TCOTC** [comment]
> 支持给代码块增加可选填的标题

感觉给代码块设置一个别名的效果也差不多？

**Comment by 88250** [comment]
还是通过扩展解决吧，原生不考虑了，感谢反馈。

**Comment by 88250** [comment]
表格标题请关注 https://github.com/siyuan-note/siyuan/issues/17002
