### ISSUE TITLE
希望输入“/”调出指令窗口可以直接输入模板名称来插入模板

### ISSUE THREAD

**Issue by muhanstudio** [siyuan-note/siyuan#10970]
### In what scenarios do you need this feature?

每次需要插入模板，要先“/”，然后再选择模板功能，然后再选择相应的模板，插入有一点不流畅

### Describe the optimal solution

希望输入“/”调出指令窗口可以直接输入模板名称来插入模板

**Comment by 88250** [comment]
/ 菜单是很多功能的入口，只用来做模板的话不合适，也许可以考虑插件实现类似功能，我关闭了，谢谢。

**Comment by muhanstudio** [comment]
不是只用来做模板，不用屏蔽其他功能，输入其他功能照样可以调用，而是说模板的名字也可以加入到功能的索引中，输入功能的名字就可以选择功能，输入模板的名字就可以插入模板

**Comment by muhanstudio** [comment]
例如功能里面有各种块功能，但是输入一个模板名字也可以被索引到

**Comment by 88250** [comment]
这个好像不太适合用 / 菜单来做，考虑用插件的命令命名好一些吧。
