### ISSUE TITLE
Add option to open pdf file with default system app

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#10972]
### In what scenarios do you need this feature?

I embed pdf's into notes a lot. Although current builtin pdf viewer is already pretty good. But I still feels adding this feature could provide another also very useful alternative choice. 

### Describe the optimal solution

Add an option in setting.

**Comment by TCOTC** [comment]
This one?

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e60a2f88-b403-4c0a-9035-a19f00317f97)

**Comment by jiewangjs** [comment]
Yes.

**Comment by jiewangjs** [comment]
Maybe I haven't expressed myself sufficiently clear. 
What I want is "single clicking the embedded pdf file make it open in default app", I am fully aware of current shift+click way.
For example, if the embeded file is a word .docx file, single click on the embedded file link would directly cause the file being opened by microsoft word application. I want this similar effect on .pdf file.

**Comment by jiewangjs** [comment]
I know. But I have used many other apps which have built-in pdf viewers can support setting for opening by system wide applications by default. 
I am just suggesting here, if this can be done, maybe your team can have some consideration on it. 
Plus, having this setting to allow all embedded files being opened by system application can give user a coherence feeling given the fact many other file types are indeeded opened by system apps already.

**Comment by 88250** [comment]
Please subscribe this issue https://github.com/siyuan-note/siyuan/issues/10641
