### ISSUE TITLE
Browser clipping extension hides token plain text

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10975]
剪藏扩展隐藏 token 明文

### In what scenarios do you need this feature?

[chrome 插件, 能不能在点击的时候把 token 隐藏掉? - 链滴](https://ld246.com/article/1712812342298)

明文显示有点风险：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e888dbc2-54b9-445d-8e88-806756b0cc24)

### Describe the optimal solution

剪藏扩展隐藏 token 明文

**Comment by 5kyfkr** [comment]
这个token有用吗，我随便打123都能正常剪藏。。。
![image](https://github.com/siyuan-note/siyuan/assets/63196026/ad766b81-421d-4cb7-870c-597ea17c3a90)

**Comment by 88250** [comment]
@5kyfkr 不开访问鉴权码的话是这样的。

**Comment by 5kyfkr** [comment]
> @5kyfkr 不开访问授权码的话是这样的。

了解，那这个问题对我没什么影响，应该用docker版或手机伺服的才会遇到
