### ISSUE TITLE
打开用户指南时丢失笔记本名称

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10989]
用户指南的两个异常情况

### Describe the problem

1. 有时候会出现这种情况（可能在打开多个工作空间的情况下出现）：

![ca83e1df1772eb3dcb8f59ff99937579](https://github.com/siyuan-note/siyuan/assets/78434827/81304374-390a-43c6-b2e5-d2bfc3cb02ed)

2. 在出现这种情况的时候（工作空间 A 打开了异常的用户指南），在工作空间 A 将一篇文档「移动到新窗口」，然后在工作空间 B 中打开用户指南，然后点击「请从这里开始」，该文档会从工作空间 A 的新窗口中打开

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a44c1c99-36be-4cf6-95a7-04d9b4dd737d)

### Version environment

```markdown
- Version: 3.0.9
- Operating System: Win10
- Browser (if used):
```

### Log file

[工作空间A-system-log.zip](https://github.com/siyuan-note/siyuan/files/14948267/A-system-log.zip)

[工作空间B-system-log.zip](https://github.com/siyuan-note/siyuan/files/14948268/B-system-log.zip)

**Comment by TCOTC** [comment]
> 2. 在出现这种情况的时候（工作空间 A 打开了异常的用户指南），在工作空间 A 将一篇文档「移动到新窗口」，然后在工作空间 B 中打开用户指南，然后点击「请从这里开始」，该文档会从工作空间 A 的新窗口中打开

我推测，有一种可能是：在工作空间 B 点击「请从这里开始」之后，在新窗口打开的不是工作空间 B 的用户指南，而是工作空间 A 自己的用户指南，但这个猜测未经证实。

**Comment by 88250** [comment]
我这里暂时无法重现该问题，如果后续能够找到重现步骤的话请随时跟帖，先关闭了，谢谢。

**Comment by TCOTC** [comment]
我这里切换工作空间和打开用户指南都比较频繁，一两天就能出现一次丢失笔记本名的情况

**Comment by 88250** [comment]
注意看下日志里面是否有 `corrupted` 字样

**Comment by TCOTC** [comment]
看了一下，隔几天就会出现一次：

```
W 2024/05/20 13:09:36 box.go:115: found a corrupted box [F:\SiYuan\data\20210808180117-czj9bvb]
W 2024/05/20 13:09:36 box.go:143: fixed a corrupted box [F:\SiYuan\data\20210808180117-czj9bvb]
```

**Comment by TCOTC** [comment]
另外，我平常会混用这3种方式来关闭用户指南：

1. 笔记本右键菜单 `关闭`
2. 笔记本右键菜单 `删除`
3. 关闭工作空间时自动关闭笔记本

不知道这个信息有没有帮助

**Comment by 88250** [comment]
我这里还是无法重现问题。

**Comment by TCOTC** [comment]
我最近一段时间也没遇到这个问题了，先关闭了
