### ISSUE TITLE
快速搜索文档并打开

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#10981]
### In what scenarios do you need this feature?

https://ld246.com/article/1712810364264

看到这个文章

### Describe the optimal solution

想到一个只要微小改动的功能增加办法。

在【【关键词出现下拉上下选择的时候，在这个入口增加shift+回车直接新页签打开文档。

**Comment by UFDXD** [comment]
目前是在这个阶段shift+回车就是回车
![image](https://github.com/siyuan-note/siyuan/assets/97731736/689e86d5-7c57-4c4c-873e-c684025683b5)

但是可以增加功能变成打开文档，命中任何块回车都打开包含这个块的文档

**Comment by 5kyfkr** [comment]
这提议不错，最好鼠标移上去的时候再加个打开按钮更直观

**Comment by UFDXD** [comment]
> 这提议不错，最好鼠标移上去的时候再加个打开按钮更直观

应该不需要按钮，因为全局面板已经可以代替这个功能了，增加这个功能只能算是增加一种更便捷的思源的进阶操作。

**Comment by 88250** [comment]
和全局搜索重复了，另外，块引搜索主要目的还是引用，不是打开，这里加入打开入口可能会造成使用上的歧义，所以还是不考虑加了，感谢反馈。
