### ISSUE TITLE
剪藏单独适配链滴

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#10987]
### In what scenarios do you need this feature?

比如剪藏链滴的帖子，

1. 链接需要重定向

2. 会在图片后面多加一行图片的长宽：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f6733fd4-24e0-42fd-964e-679d8ad44d3f)

### Describe the optimal solution

剪藏单独适配链滴

最好可以直接获取 Markdown ：

比如：

- https://ld246.com/article/1709827967877 → https://ld246.com/article/raw/1709827967877
- https://ld246.com/article/1709827967877/comment/1712845580086?r=JeffreyChen#comments → https://ld246.com/comment/raw/1712845580086

### Other information

https://ld246.com/article/1709827967877

**Comment by 88250** [comment]
不考虑了，直接用链滴的查看 Markdown 功能吧。

**Comment by TCOTC** [comment]
> 直接用链滴的查看 Markdown 功能

但是复制粘贴到思源里会变成一个代码块，有点麻烦

**Comment by 88250** [comment]
找个记事本复制纯文本



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月11日(周日) 中午11:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 剪藏单独适配链滴 (Issue #10987)




  
直接用链滴的查看 Markdown 功能
  
但是复制粘贴到思源里会变成一个代码块，有点麻烦

**Comment by 88250** [comment]
改进了下图片后面的数字问题。
