### ISSUE TITLE
自动加载文件的更改

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1099]
在多处对文件进行编辑的时候会用到这个功能

几乎所有的成熟的编辑器都要有这个功能

**Comment by Andy-AO** [comment]
关键是现在连刷新也没有，在外部更改之后，如果想继续使用思源笔记，需要进行繁琐的重复操作

**Comment by 88250** [comment]
你好，请使用文件树上的刷新按钮，谢谢。
