### ISSUE TITLE
希望点击大纲标题后光标出现在块的末尾

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#10993]
### In what scenarios do you need this feature?

目前是在块的开头，觉得有点奇怪。

在末尾的话，按一下enter就能在该标题下写东西。现在还要手动把光标移到末尾。

![image](https://github.com/siyuan-note/siyuan/assets/67137548/4529fd34-4c4f-46fb-8858-4b1463869cc6)

### Describe the optimal solution

无

**Comment by Jiangshuon** [comment]
才发现！不只是大纲，点击块引用后，光标也是出现在块的开头！这样有啥好处吗，感觉在末尾更自然吧

**Comment by leeyaunlong** [comment]
大纲下一个节点不就在上一个节点尾部吗?

**Comment by MisakaImouto8912** [comment]
我个人觉得在开头更好，因为如果一个块太长的话（如列表格、代码块），定位到尾部可能看不见开头，会更莫名其妙。
如果想要快速在下方添加块，可以使用快捷键 `Ctrl` + `Alt` + `A` ，更为方便。

**Comment by Jiangshuon** [comment]
> 我个人觉得在开头更好，因为如果一个块太长的话（如列表格、代码块），定位到尾部可能看不见开头，会更莫名其妙。 如果想要快速在下方添加块，可以使用快捷键 `Ctrl` + `Alt` + `A` ，更为方便。

大纲，标题块，为啥会很长。怎么会把代码块作为标题呢

快速在下方添加块用快捷键是不行的，我试过的，无法形成子列表

**Comment by MisakaImouto8912** [comment]
是我表达不太清晰，因为跳转到指定块的操作挺多的，列如：书签、双击搜索结果、当然还有大纲，他们目前用的应该是同一个接口，我怕改动这个会影响其他的。
我试了一下，如果只存在一个**列表块**的时候，通过快捷键会在下方创建段落块。如果已经存在**列表项块**再使用快捷键，就会创建**列表项块**。

https://github.com/siyuan-note/siyuan/assets/47753140/52cb92ee-0181-4b5e-b83b-6edd42836efa


可以考虑在**列表块**使用快捷键也创建**列表项块**，而不是在下方创建段落块，这样是否更为统一。

**Comment by Jiangshuon** [comment]
@Vanessa219  v大希望考虑下，我看了下vscode，好像思源的逻辑和IDE是差不多的，当点击块引用时，光标出现在前面（类似于vscode的alt+click），但是vscode中双击大纲时，光标是出现在末尾的，希望思源点击大纲时光标也能出现在末尾，这样非常方便输入。

**Comment by 88250** [comment]
这个不考虑改了，谢谢。
