### ISSUE TITLE
List item block cannot be copied with serial numbers when there is only one item

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#10999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

列表项块（有序列表、无序列表、任务列表）
当只有一项时，无法带序号复制
当有两项及以上时，是带有序号复制的

这里的序号是拿有序列表举例，如果是无序列表则是`*`，任务列表则是`* [ ]`

### Expected result

无论有多少项均统一均带序号复制

### Version environment

```markdown
- Version: v3.0.9
- Operating System: Windows 11
```

### Log file

null

**Comment by Temacc0531** [comment]
发现点击前面的子项图标是可以选中整个子项带序号复制的，但为什么直接划动复制又不能选中整个子项？

**Comment by TCOTC** [comment]
> 发现点击前面的子项图标是可以选中整个子项带序号复制的，但为什么直接划动复制又不能选中整个子项？

正常的，滑动鼠标只能选中多个块，选中单个块要用块标

**Comment by 88250** [comment]
楼上解释很到位，谢谢。

**Comment by TCOTC** [comment]
> 否则要选中行内元素的时候会很容易选中到整个块

之前用 FlowUs 最烦的就是这个，块内的文本要很小心才能选中
