### ISSUE TITLE
Prevent frontend request pending

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#10992]
![image](https://github.com/siyuan-note/siyuan/assets/873584/1a0ea8d3-f10c-4ed8-9a51-fafc00cf6fce)

**Comment by 88250** [comment]
确认了下，SQLite WAL 模式下写入时不会阻塞查询，所以重构内存表意义不大。

目前需要确认的问题是某些情况下请求会被 pending，导致用户编辑时看上去正常，实际上数据并未写入从而导致数据丢失。

**Comment by 88250** [comment]
已经确认并修复，是因为 sql queue 中的锁使用不当造成了死锁。

**Comment by TCOTC** [comment]
@88250 这个 issue 的 Milestones 应该要改一下

**Comment by 88250** [comment]
多谢提醒。
