### ISSUE TITLE
Caught up in an infinite loop of JavaScript snippet

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#10997]
### In what scenarios do you need this feature?

I accidentally tested an infinite JavaScript loop that keeps outputting alerts. Now, I can't do anything.

### Describe the optimal solution

How to boot the app with js snippet off? 
Or, is the snippets file stored in local drive? If so, where? So, I can modify the snippet file.

**Comment by TCOTC** [comment]
Workspace \data\snippets\conf.json
