### ISSUE TITLE
 Cancels text selection when the document is closed

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#10995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 打开文档
2. 选中一段文本
3. 保持选中状态，关闭文档
4. 重新打开这个文档
5. 文本依旧被选中

### Expected result

当文档关闭后，文本选中状态应该被取消

### Screenshot or screen recording presentation

![GIF 2024-4-12 15-55-36](https://github.com/siyuan-note/siyuan/assets/101307399/5b346bc7-36c5-4291-b8cc-82fde1c63b4d)

### Version environment

```markdown
- Version: v3.0.9
- Operating System: Windows 11
```

### Log file

null

**Comment by 88250** [comment]
@Vanessa219 这个是特性还是？

**Comment by 88250** [comment]
那我们关闭了，感谢楼主反馈。

**Comment by Temacc0531** [comment]
记住阅读位置可以理解，这个记住选中状态时什么考虑😂如果需要特别标注的话应该就是使用

**Comment by Vanessa219** [comment]
能记住更好一点吧。可以知道上次主要想修改的部分

**Comment by Temacc0531** [comment]
> 能记住更好一点吧。可以知道上次主要想修改的部分

好像没有太大必要，可能大部分用户也用不到这个特性。

目前我使用发现了一个问题，就是我经常对一份文档进行选中复制以后就直接把文档关闭了，下次进来就发现了还留有个选中状态，有点困惑

主要是目前类似的浏览器也没有这个特性😂

**Comment by 88250** [comment]
> 主要是目前类似的浏览器也没有这个特性😂

IDE 是有的。

**Comment by Temacc0531** [comment]
那先占个坑吧，后续再看看有没有其他用户反馈的
