### ISSUE TITLE
Javascript error (Mac 10.15.6)

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#11]
Version: 0.1.9

rm -rf ~/.siyuan.

I got the below error

<img width="408" alt="Screen Shot 2020-09-20 at 12 31 11 PM" src="https://user-images.githubusercontent.com/15811943/93693622-3771c080-fb3d-11ea-9062-6bf804cad8ea.png">

**Comment by 88250** [comment]
It Will be fixed in v0.2.0, thanks.

**Comment by 88250** [comment]
v0.2.0 released, please try it.
