### ISSUE TITLE
链接描文本，喜欢可以手动关闭

### ISSUE THREAD

**Issue by mieyeaa** [siyuan-note/siyuan#11002]
### In what scenarios do you need this feature?

复制网址链接粘贴时，自动转入描文本，这导致每次需要用到链接都很麻烦。

### Describe the optimal solution

提供关闭

### Describe the candidate solution

取消自动进入描文本

### Other information

![1](https://github.com/siyuan-note/siyuan/assets/59656688/ae83f642-50c6-457d-b303-7a774eee4fc8)

**Comment by shuojie819** [comment]
可能是你的浏览器携带的功能吧，比如edge ↓
![image](https://github.com/siyuan-note/siyuan/assets/72399630/d03135c4-c13e-4dad-8367-e97acc32bda9)

**Comment by mieyeaa** [comment]
> 可能是你的浏览器携带的功能吧，比如edge ↓ ![图像](https://private-user-images.githubusercontent.com/72399630/322002844-d03135c4-c13e-4dad-8367-e97acc32bda9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzA5MjYsIm5iZiI6MTcxMjkzMDYyNiwicGF0aCI6Ii83MjM5OTYzMC8zMjIwMDI4NDQtZDAzMTM1YzQtYzEzZS00ZGFkLTgzNjctZTk3YWNjMzJiZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDE0MDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NDNkNmRmOWFkYWJjOWE3ZjMxMDk3OGUxMWY4NjkxYThmZThhNmFjMWM5N2I2OWRhYTFjYzJkODk3MTg1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qJOTVvBIwMBwQf1_CA0VleoVynZjBYcA1gHLhfRWjUc)

 还真是，谢啦

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
