### ISSUE TITLE
集市更新异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11007]
### 集市更新版本号异常

v3.0.10-dev2

可能与 #10973 有关

1 下载这个挂件，始终会提示更新：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/85cc3c71-fd0d-454d-9cb1-b7663a6d5af3)

2 版本号和本地对不上：

![a91e6b6ffac8759e950914629c1d0e27](https://github.com/siyuan-note/siyuan/assets/78434827/6942e530-51cf-4c41-b36a-99a355994ad8)

3 还会出现最新版本的插件点了更新也没用（1.5.0是最新版）：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/96c97906-bbdb-417c-bcf0-76982eb61f5c)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e1cb7c1d-f9b5-4eba-8378-2227f3cfaf06)

**Comment by TCOTC** [comment]
> 挂件设置的问题，可能要去挂件仓库提

有啥问题？

**Comment by 88250** [comment]
1、2 问题：

![image](https://github.com/siyuan-note/siyuan/assets/873584/3ce3b898-b5bb-48b7-ac2e-a1386cdc0135)

![image](https://github.com/siyuan-note/siyuan/assets/873584/41289079-664d-4682-b3e9-5d2c7fa9f046)

这个挂件的 package 是后面提交的，release 的时候版本号没有变，还是 0.0.1 所以有问题 https://oss.b3logfile.com/package/hqweay/widget-inline-extractor@89cfc2578a27576a3da02fbbeee102ee71f1efd9/widget.json

3 问题：我这里无法重现，可以正常更新版本。

**Comment by TCOTC** [comment]
> 1、2 问题：这个挂件的 package 是后面提交的，release 的时候版本号没有变，还是 0.0.1 所以有问题

那是怎么出现 package 是对的，版本号却不变的情况？集市下载的时候是直接连 GitHub 下载的吗？

> 3 问题：我这里无法重现，可以正常更新版本。

我这里现在也重现不了，可能在插件更新之后的一段时间内能重现，我再观察一下

**Comment by 88250** [comment]
> 那是怎么出现 package 是对的，版本号却不变的情况？集市下载的时候是直接连 GitHub 下载的吗？

package 应该是作者后面手动上传更新的，不是 release 对应的 commit。

> 我这里现在也重现不了，可能在插件更新之后的一段时间内能重现，我再观察一下

好的。

**Comment by TCOTC** [comment]
1. 更新实际是成功了的，但那个刷新的图标一直在：
![集市](https://github.com/siyuan-note/siyuan/assets/78434827/bff07820-0a45-4894-9de0-0f2cdfa9c1bb)

2. 重载界面再打开集市也是一样的没有变化

3. 重启思源之后就不显示刷新图标了，但此时更新的插件已经变了
![image](https://github.com/siyuan-note/siyuan/assets/78434827/ff038558-c507-453f-b774-c2c8338d6122)

@88250 所以我觉得可能是缓存的问题

**Comment by TCOTC** [comment]
@88250 我连续复现 3 次了。 D 大想复现的话可以新建一个工作空间，下载一堆插件，等到下次出现有更新的插件时再试一下

**Comment by 88250** [comment]
确实能够重现问题，感谢指出，稍后排查。
