### ISSUE TITLE
建议导入时注意图片缩放的转换

### ISSUE THREAD

**Issue by Andy-AO** [siyuan-note/siyuan#1100]
除了直接用html方法之外，还有比较常见的语法是在图片路径尾部加入例如` 300x`的字符串.

但是这样的语法并不能被思源成功导入,导致其他地方的md文件中的图片不仅无法显示出此前的缩放情况,而且图片会直接无法显示.

建议在导入处理的时候，对这部分语法进行转换,或者直接兼容此语法.

**Comment by 88250** [comment]
导入方面的优化稍微放后，谢谢。

**Comment by 88250** [comment]
暂时不考虑了，后面如果需要再打开。
