### ISSUE TITLE
Improve database unbind block

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#11013]
数据库中不存在，显示已绑定

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在数据库主键添加了一个块，莫名其妙的消失了，然后再添加就显示已绑定……（重启了思源、重建了索引，都不太行）
![PixPin_2024-04-13_13-28-02](https://github.com/siyuan-note/siyuan/assets/72399630/c921e90a-c79a-4e1d-afb9-2cdb2e7ddc0a)
`https://github.com/siyuan-note/siyuan/assets/72399630/c921e90a-c79a-4e1d-afb9-2cdb2e7ddc0a`

### Expected result

当块不存在数据库中时不应该显示已绑定

### Version environment

```markdown
- Version: v3.0.10-dev1
- Operating System: windows 11 24H2
- Browser (if used):
```

### Log file

无

**Comment by shuojie819** [comment]
又试了一下，好像是中数据库中取消绑定块后不删除改行，在添加那个引用的话就会报已绑定……

**Comment by TCOTC** [comment]
确实是，即使删掉原来那个主键里的文本也不行

**Comment by 88250** [comment]
好像没有问题，只是不应该提示？

**Comment by TCOTC** [comment]
> 好像没有问题，只是不应该提示？稍后修改一下这种情况下不再提示已绑定。

不只是提示的问题。只要取消绑定块后不删除之前绑定该块的条目（或者让条目绑定别的块），就无法在数据库中再次绑定这个块

**Comment by 88250** [comment]
> > 好像没有问题，只是不应该提示？稍后修改一下这种情况下不再提示已绑定。
> 
> 不只是提示的问题。只要取消绑定块后不删除之前绑定该块的条目（或者让条目绑定别的块），就无法在数据库中再次绑定这个块

我这里测试可以绑定的，拖进去就行了。

**Comment by TCOTC** [comment]
我这里的行为完全不对啊，怎样都只能绑定原来的条目：

![数据库](https://github.com/siyuan-note/siyuan/assets/78434827/d9c31dff-fe4a-4f58-bc9e-dcf7e22edd8a)

**Comment by 88250** [comment]
目前取消绑定后 ID 不会改变，还是原来的 ID，所以再关联时还是继续关联到这一行数据上。

需要考虑下解绑时是否同时更换 ID。
