### ISSUE TITLE
Improve database checkbox field sorting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11016]
### 数据库新增条目没有参与勾选列排序

![勾选](https://github.com/siyuan-note/siyuan/assets/78434827/30555a73-6b42-4f4f-976f-8e58ea6d262c)

### Version environment

```markdown
- Version: v3.0.10-dev3
- Operating System: Win10
- Browser (if used):
```

**Comment by TCOTC** [comment]
想了一下应该是因为没有默认值，导致不参与排序

**Comment by 88250** [comment]
新增行后未编辑过的列都不参与排序的；json 里面只记录编辑过的值。

勾选有点特殊，得考虑一下是不是默认就算编辑过？

**Comment by 88250** [comment]
尝试了下，如果勾选框默认算作不为空参与排序的话会有其他问题，比如新增行以后会跳动，因为和新行不参与排序的规则冲突了。

所以目前还是保持现有设计，如果要参与排序的话得勾选再取消勾选。

**Comment by TCOTC** [comment]
> 尝试了下，如果勾选框默认算作不为空参与排序的话会有其他问题，比如新增行以后会跳动，因为和新行不参与排序的规则冲突了。

那刚刚新增的条目默认不参与排序，在这个条目被编辑过之后（比如添加了主键）就参与排序怎么样？

「勾选再取消勾选」还是很奇怪，因为勾选之后就参与排序了，还要找到排序后的位置再取消勾选，比较麻烦

**Comment by 88250** [comment]
有道理，稍后调整一下，勾选框优先按照主键是否编辑过来决定是否参与排序。
