### ISSUE TITLE
关联列排序导致数据库异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11015]
### 关联列排序导致数据库异常

[数据库视图.sy.zip](https://github.com/siyuan-note/siyuan/files/14965471/sy.zip)

v3.0.10-dev3

关联列排序之后有个视图打不开了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1cc3ecae-f658-4a7b-a50e-b1b549eb55bd)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9477d5f0-faaf-432c-bdb6-1da371956038)

重启思源后整个数据库都加载不出来了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1909c3bf-9a76-4be8-827c-53478c985a9c)

**Comment by 88250** [comment]
感谢反馈，稍后解决。

**Comment by 88250** [comment]
是 https://github.com/siyuan-note/siyuan/issues/11011 中引入的问题。
