### ISSUE TITLE
Adjusting the column width of the mirror database will affect other views

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11019]
### Describe the problem

GIF：

![影响](https://github.com/siyuan-note/siyuan/assets/78434827/66ea797b-5f8d-48e3-b11c-62916981391a)

### Version environment

```markdown
- Version: v3.0.10-dev3
- Operating System: Win10
- Browser (if used):
```

**Comment by 5kyfkr** [comment]
我觉得这个还挺好的，不然改了一列还要去其他视图一个个调

**Comment by TCOTC** [comment]
@5kyfkr 你认真看一下 GIF，这个是 BUG

**Comment by 5kyfkr** [comment]
> @5kyfkr 你可以仔细看一下 GIF，这个是显示上的 BUG ，实际上不会修改列宽

这样子，确实是bug

**Comment by TCOTC** [comment]
如果镜像数据库在不同的文档，即使其中一个文档已经关闭了，调整列宽后再打开文档，发现还是会影响到其他视图

**Comment by Vanessa219** [comment]
> ### 补充：
> 如果镜像数据库在不同的文档，即使其中一个文档已经关闭了，调整列宽后再打开文档，发现还是会影响到其他视图

这个好像重现不了

**Comment by TCOTC** [comment]
我现在也重现不了了，后面能重现了再说
