### ISSUE TITLE
Primary key value unexpectedly updated when database adds row

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11018]
主键升序排序时，空值应该置底

### In what scenarios do you need this feature?

主键为空时，升序未置底：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/92d81484-265d-44b1-b45b-055d7aabb0ec)

### Describe the optimal solution

跟其他类型的属性一样，升序和降序都置底：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ca268849-2fcf-45e0-b37b-f90113c40b49)

**Comment by 88250** [comment]
测试了下，应该是因为某种情况下（比如添加行时）虽然是新建，但是会意外修改主键值（还是空字符串）导致误识别为已经编辑过所以参与了排序。

后续会改进更新值的接口，如果新旧值对比一样则不更新值。
