### ISSUE TITLE
The block icon menu will no longer be displayed after selecting Delete through the block icon menu

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#11028]
删除一个块之后，不能立刻删除下一个块儿，具体可看视频。

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/62794181/6d6a7409-33b0-48f5-99f8-15da149abf93

有一个 bug，具体可以看视频。

简单说就是点到一个快标之后删除，再点下一个的时候就不可以删除了，需要把鼠标移到别的地方再移回来，才能够选中这个块儿。

### Expected result

期待早日修复

### Version environment

```markdown
- Version: 3.09
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
@Vanessa219 应该取消块标显示，让用户重新选择。
