### ISSUE TITLE
块引用与标签互转

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11026]
同意标签树完全被引用标签代替。代替方法是提供标签转引用功能，让使用标签用户转移出来，然后逐渐增强引用标签体系。

还有我需要一个类似标签的彻底删除这个引用标签的功能：删除逻辑是，是动态描文本引用中可以完全删除，是静态描文本就删除引用保留文本文字。

_Originally posted by @UFDXD in https://github.com/siyuan-note/siyuan/issues/10919#issuecomment-2041316100_
            
---

关联 #11238

**Comment by TCOTC** [comment]
- 将某个块(文档)的所有引用转换为标签
- 将某个标签转换为对某个块(文档)的引用

**Comment by TCOTC** [comment]
跟 #11025 实现其中一个

**Comment by UFDXD** [comment]
支持的理由是，既然思源不打算在标签上深入，那为什么不往反链上面深入呢？，标签有时候是刚需，那为什么不将刚需再利用增加思源的优势呢，反链+标签，刚需+刚需，不止1+1>2。

**Comment by 88250** [comment]
不考虑改变现有设计了，标签和引用保持独立，感谢反馈。

**Comment by TCOTC** [comment]
v3.1.28 支持将行级标签替换为块引用：https://github.com/siyuan-note/siyuan/issues/11238
