### ISSUE TITLE
数据库日期筛选bug（怎么越更新bug越多了？）

### ISSUE THREAD

**Issue by V7kb** [siyuan-note/siyuan#11027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1.数据库筛选“本周”，不显示周日的条目
2.4月14日既不在本周，也不在后一周，更不在前一周，在筛选中消失了

https://github.com/siyuan-note/siyuan/assets/166938054/d41b3277-c623-4fab-a4f3-f7cce0b7f82b

### Expected result

筛选本周应该显示4.14

### Version environment

```markdown
越更新问题越多
```

### Log file

越更新问题越多

**Comment by 88250** [comment]
你好，这个问题会在 https://github.com/siyuan-note/siyuan/issues/11004 中一并解决。

总体来说，bug 是在变少的，数量已经逐步收敛，感谢反馈。

**Comment by V7kb** [comment]
> 你好，这个问题会在 #10979 中一并解决。
> 
> 总体来说，bug 是在变少的，数量已经逐步收敛，感谢反馈。

ok
