### ISSUE TITLE
数据库新增列在其他视图隐藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11021]
### In what scenarios do you need this feature?

在数据库某个视图下新增的属性列，在其他视图默认隐藏

我平常使用首个视图作为「总表」，然后会在一个数据库里创建很多视图来做不同的筛选，之后时不时还会在每个视图中新增一些列作为这个视图特有的补充信息，但是**目前**每次新增 1 列都要手动去其他 (N-2) 个视图里面隐藏 (N-2) 次，来回操作非常麻烦。

### Describe the optimal solution

在数据库某个视图下新增的属性列，在其他视图默认隐藏。

如果实现了 #11020 ，即使默认隐藏了，在其他视图显示也很方便。

### Other information

[希望在数据库某个视图下新增的列，在其他视图自动隐藏 - 链滴](https://ld246.com/article/1708709423221) 投票几乎都支持：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b8ebf51b-e182-4aad-8fd3-a3a33d971409)

**Comment by 88250** [comment]
抱歉，这个不考虑了，其他视图默认要展示新增列的。
