### ISSUE TITLE
数据库列支持隐藏图标

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11023]
### In what scenarios do you need this feature?

有时候会觉得图标太占地方了，比如这里去掉图标的话列宽就可以缩短到两个字的长度了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/29e9a7bd-31fc-4157-9774-1b888772f8db)

而且图标只有标识的作用，没有功能，去掉了也没有影响

### Describe the optimal solution

数据库列支持隐藏图标：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/857043b4-4a8f-4081-b638-599aa7df61ba)

隐藏之后显示 #iconEmoji ：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fc5dbff8-9794-4c91-a1df-18c1978a0d03)

**Comment by 88250** [comment]
抱歉，这个需求有点过于小众了，参考 Notion-like 的一些产品似乎都没有支持，我们也不考虑了，如果实在需要可以考虑开发插件，谢谢。
