### ISSUE TITLE
Database UI color exception in embed blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11032]
嵌入块中的数据库颜色有点问题

### Describe the problem

嵌入块中的数据库颜色有点问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6fef54b2-b471-4051-8820-a1bda86035ec)

### Expected result

统一颜色

### Version environment

```markdown
- Version: 3.0.10-dev4
- Operating System: Win10
- Browser (if used):
```

**Comment by TCOTC** [comment]
### 点击嵌入块中的数据库时报错

[127.0.0.1-1713095262569.log](https://github.com/siyuan-note/siyuan/files/14970554/127.0.0.1-1713095262569.log)

乱点一通（GIF）：

![数据库](https://github.com/siyuan-note/siyuan/assets/78434827/48b0d428-fde9-4338-a593-406652362325)

**Comment by TCOTC** [comment]
还有固定的列也是白色的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ae97356c-b65c-4101-99ae-6380d32bd8b8)

**Comment by TCOTC** [comment]
还有鼠标移动到块标上时，不是整个块一下亮起（而是有先后的），也有点奇怪：

![块](https://github.com/siyuan-note/siyuan/assets/78434827/85e1daaf-bb9b-4507-84df-53580cfcca81)

**Comment by Vanessa219** [comment]
由于固定行列、滚动等问题，还存在一下 UI 问题

![072a82d961feda571ef63cd469add589](https://github.com/siyuan-note/siyuan/assets/970828/a0e9bbb8-c329-46e1-8deb-b8602949d713)

<img width="544" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/d948bdeb-336d-4a9f-9ed8-c8d929ddee02">

**Comment by TCOTC** [comment]
@Vanessa219 现在变得一闪一闪了：

![数据库](https://github.com/siyuan-note/siyuan/assets/78434827/c1a59064-4b3d-418e-82ed-72e47d13b1f7)
