### ISSUE TITLE
Improve dragging and selection of blocks containing iframe

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11033]
### Describe the problem

嵌入块中只要包含了挂件（不是只有挂件块），这个嵌入块就无法拖拽

### Expected result

包含挂件的嵌入块也能正常拖拽

### Version environment

```markdown
- Version: 3.0.10-dev4
- Operating System: Win10
- Browser (if used):
```

**Comment by TCOTC** [comment]
关联 #10900

**Comment by Vanessa219** [comment]
1. 从下往上划选遇到嵌入块时，不易划选中
2. 包含 iframe 块的划选
3. 包含 iframe 块的拖拽
