### ISSUE TITLE
Improve database reference anchor text

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11035]
改进数据库引用锚文本

### In what scenarios do you need this feature?

![数据库](https://github.com/siyuan-note/siyuan/assets/78434827/0bdde546-006b-453b-997e-b609cf09ed25)

### Describe the optimal solution

1. 复制为引用块的数据库如果未命名，则动态锚文本显示为「未命名数据库」
2. 被块引的数据库清空命名后，块引不应消失
3. 数据库重命名后，应及时刷新块引锚文本

**Comment by 88250** [comment]
第三点暂时没有办法改进，后续在 https://github.com/siyuan-note/siyuan/issues/8234 中考虑。

**Comment by TCOTC** [comment]
@88250 我觉得数据库也可以翻译一下，然后中文之间不需要空格，其他语种保留空格

![image](https://github.com/siyuan-note/siyuan/assets/78434827/467fef2d-9a61-4606-bb7f-21ee6752503c)

**Comment by 88250** [comment]
这个和 IFrame、Video 那些先保持一致吧：

![image](https://github.com/siyuan-note/siyuan/assets/873584/c09043b7-562e-4d25-b223-281da239a021)

你有空的话可以帮忙 PR 改进一下，谢谢。

**Comment by TCOTC** [comment]
这样的话好像「未命名」就多余了。想了想，既然引用的数据库未命名，那就说明用户很可能不打算填数据库名，这时候显示「未命名」就有点碍眼了

去掉「未命名」改成「Database...」吧，统一一下

**Comment by 88250** [comment]
ok
