### ISSUE TITLE
Disable edit of database table view in embedded block

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11034]
### 点击嵌入块中的数据库时报错

[127.0.0.1-1713095262569.log](https://github.com/siyuan-note/siyuan/files/14970554/127.0.0.1-1713095262569.log)

乱点一通（GIF）：

![数据库](https://github.com/siyuan-note/siyuan/assets/78434827/48b0d428-fde9-4338-a593-406652362325)

### Version environment

```markdown
- Version: 3.0.10-dev4
- Operating System: Win10
- Browser (if used):
```

**Comment by 88250** [comment]
感谢反馈，合并到 https://github.com/siyuan-note/siyuan/issues/11032 中跟进。
