### ISSUE TITLE
数据库资源列插入链接时，焦点移动到链接输入框

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11031]
### In what scenarios do you need this feature?

点击「链接」之后还要点击一次输入框，有点麻烦

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cf31458c-30a5-4ee1-a0eb-b2f005b80f94)

### Describe the optimal solution

数据库资源列插入链接时，焦点移动到链接输入框

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/11031
