### ISSUE TITLE
Improve heading drag conversion doc subheading level

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11037]
标题拖拽至文档树时提升等级减少一级

### In what scenarios do you need this feature?

如下图，文档内拖拽1级标题至文档树后转换成文档
![image](https://github.com/siyuan-note/siyuan/assets/63196026/69d887b6-f3ba-4ae1-b412-bf73f0a2d892)
1级标题(h1)提升成文档title，其他h2-h6也提升至h1-h5
![image](https://github.com/siyuan-note/siyuan/assets/63196026/1da8dfc9-8e8b-4cc5-83c3-a219cd126fb1)

### Describe the optimal solution

能否提供开关选项或者修改为不提升等级？因为在markdown里面h1应该就等于title，而在html语法里才有title这一说法，为了照顾md语法的习惯感觉应该给个选项能不提升等级。
至于其他如3级标题拖到文档树，我觉得也应该可以比现在少提升一级，变为3级标题转成title，4级标题转成h2，而且这样从文档树再拖回文档里也不会比原来高了一级，现在3级标题拖进文档树再拖回原来2级标题下就变成2级标题了，如下图是从文档树拖回来后3级标题变成2级了。
![image](https://github.com/siyuan-note/siyuan/assets/63196026/cfd5cc5c-1ba4-4151-8709-9370489a67e6)

综上，应该给个选项会好点，不用markdown的就维持现状，用markdown的减少一层等级提升。

**Comment by TCOTC** [comment]
我用思源的时候从来不创建一级标题，一直是从二级标题开始创建的，就是因为没法批量转换一级标题。

但现在我发现了一个问题，如果把二级标题拖拽到文档树上，二级标题下的三级标题全都变成一级标题了。

所以我倾向于这样的方案：

- 拖拽标题到文档树后，拖拽的标题变成文档名，子标题的最高级从一级标题变为二级标题（目前子标题都是一级标题，没法批量转换为低级的标题）
- 从文档树拖拽文档到编辑器后，拖拽的文档名转换为一级标题，子标题的最高级为二级标题（因为可以「带子标题转换」，所以维持目前的这个方案就好了）

**Comment by 5kyfkr** [comment]
> * 拖拽标题到文档树后，拖拽的标题变成文档名，子标题的最高级从一级标题变为二级标题（目前子标题都是一级标题，没法批量转换为低级的标题）

这个就是我希望的方案

> * 从文档树拖拽文档到编辑器后，拖拽的文档名转换为一级标题，子标题的最高级为二级标题（因为可以「带子标题转换」，所以维持目前的这个方案就好了）

这个可以不改维持现状，问题不大

**Comment by 88250** [comment]
很有道理，稍后改进。
