### ISSUE TITLE
bug1:json解析失败，造成正在写的重要资料丢失；bug2:重建索引超时退出会导致整个笔记丢失；recommend：提供关闭浏览器编辑功能，请勿让我的笔记在公司内网公开处刑。。。。。。。。。

### ISSUE THREAD

**Issue by github123-hzg** [siyuan-note/siyuan#11030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

正在写东西，突然索引异常，重启界面和重建了索引，丢失了10min+的日志，如果没有自动保存，我半天内容没了

硬件信息：MacBook Pro 16` 2019款
 型号名称：	MacBook Pro
  型号标识符：	MacBookPro16,1
  处理器名称：	六核Intel Core i7
  处理器速度：	2.6 GHz
  处理器数目：	1
  核总数：	6
  L2缓存（每个核）：	256 KB
  L3缓存：	12 MB
  超线程技术：	已启用
  内存：	32 GB

软件版本3.0.7 (3.0.7)

完整日志
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/04/14 15:40:35 runtime.go:74: kernel is booting:
    * ver [3.0.7]
    * arch [amd64]
    * os [darwin]
    * pid [4349]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/zhg/SiYuan]
I 2024/04/14 15:40:35 conf.go:468: user has disabled [Google Analytics]
I 2024/04/14 15:40:35 runtime.go:123: use network proxy [system]
I 2024/04/14 15:40:35 serve.go:115: kernel [pid=4349] http server [127.0.0.1:57895] is booting
I 2024/04/14 15:40:36 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=/Users/zhg/SiYuan/temp/pandoc/bin/pandoc]
I 2024/04/14 15:40:36 conf.go:1071: pandoc initialized, set pandoc bin to [/Users/zhg/SiYuan/temp/pandoc/bin/pandoc]
I 2024/04/14 15:40:36 blocktree.go:495: read block tree [11 MB] to [/Users/zhg/SiYuan/temp/blocktree], elapsed [0.04s]
I 2024/04/14 15:40:36 conf.go:827: database size [277 MB], tree/block count [250/36246]
I 2024/04/14 15:40:36 working.go:192: kernel booted
I 2024/04/14 15:40:36 box.go:76: auto stat [trees=250, blocks=36246, dataSize=1.6 GB, assetsSize=1.5 GB]
I 2024/04/14 15:40:36 disk.go:33: disk usage [total=500 GB, used=468 GB, free=16 GB]
I 2024/04/14 15:40:36 serve.go:128: reverse proxy server [127.0.0.1:6806] is booting
I 2024/04/14 15:40:38 session.go:116: auth success [ip=127.0.0.1:57897]
W 2024/04/14 15:40:42 tree.go:212: searching tree on filesystem [rootID=20240307214429-v4gbunb]
E 2024/04/14 15:40:42 tree.go:178: parse json [20240221223155-pj530q2/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] to tree failed: expected colon after object key
E 2024/04/14 15:40:42 tree.go:54: parse tree [/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] failed
E 2024/04/14 15:40:42 tree.go:250: load tree [/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] failed: parse tree failed
I 2024/04/14 15:42:39 cloud_service.go:383: get cloud user elapsed [3124ms]
E 2024/04/14 15:52:14 tree.go:143: parse json to tree [/Users/zhg/SiYuan/data/20240221223155-pj530q2/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] failed: expected colon after object key

### Expected result

修复索引问题！！！🚩🚩🚩
修复索引问题！！！🚩🚩🚩
修复索引问题！！！🚩🚩🚩

日志显示具体，但是又不够排查原因。。。。希望不要再这样了。

我的可疑操作
近期：写了一个特别长的md
往期：开放版3.0.6回退到社区版3.0.5，又升级为3.0.7

之前出现过的雷同bug：新手笔记📒丢失问题
场景描述：从已关闭的笔记本中重启新手笔记，建立索引过慢导致手动关闭思源笔记，重启再次建立索引就会失败。至今新手笔记本丢失未回。

### Version environment

```markdown
- Version: 版本3.0.7 (3.0.7)
- Operating System: mac os 11
- Browser (if used):haste no off of Browser
```

### Log file

I 2024/04/14 15:40:38 session.go:116: auth success [ip=127.0.0.1:57897]
W 2024/04/14 15:40:42 tree.go:212: searching tree on filesystem [rootID=20240307214429-v4gbunb]
E 2024/04/14 15:40:42 tree.go:178: parse json [20240221223155-pj530q2/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] to tree failed: expected colon after object key
E 2024/04/14 15:40:42 tree.go:54: parse tree [/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] failed
E 2024/04/14 15:40:42 tree.go:250: load tree [/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] failed: parse tree failed
I 2024/04/14 15:42:39 cloud_service.go:383: get cloud user elapsed [3124ms]
E 2024/04/14 15:52:14 tree.go:143: parse json to tree [/Users/zhg/SiYuan/data/20240221223155-pj530q2/20240220142136-xy9gt41/20240307214429-v4gbunb.sy] failed: expected colon after object key

**Comment by github123-hzg** [comment]
讨厌你的浏览器编辑功能没有关闭接口

**Comment by 88250** [comment]
* JSON 文件被写坏了这个第一次碰到，请继续帮忙留意观察，同时需要排除其他软件读写 .sy 文件
* 最近两个版本（v3.0.8 和 v3.0,9）数据索引有 bug，请等下个版本升级看看
* 不要打开网络伺服功能，这样就只能在 127.0.0.1 上使用，其他局域网设备无法访问，另外，如果要开启网络伺服功能，记得设置访问授权码

谢谢。

**Comment by github123-hzg** [comment]
好的。我尝试重新加载了失败的sy文件，没反应，都打算从sy文件恢复最后的笔记内容了，但是最后不止咋的就好了，不知道咋回事

**Comment by 88250** [comment]
请继续保持观察和反馈，谢谢。



---原始邮件---
发件人: "Oracle ***@***.***&gt;
发送时间: 2024年4月15日(周一) 晚上10:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] bug1:json解析失败，造成正在写的重要资料丢失；bug2:重建索引超时退出会导致整个笔记丢失；recommend：提供关闭浏览器编辑功能，请勿让我的笔记在公司内网公开处刑。。。。。。。。。 (Issue #11030)




 
好的。我尝试重新加载了失败的sy文件，没反应，都打算从sy文件恢复最后的笔记内容了，但是最后不止咋的就好了，不知道咋回事

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
