### ISSUE TITLE
Automatic refresh of document tree information

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11043]
文档树悬浮提示自动刷新

### In what scenarios do you need this feature?

只要不折叠再展开，无论什么时候把鼠标移上去，这个文档始终「更新于 4 秒以前」、没有「子文档」：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/231158e3-ed54-49e6-a0a9-c402ae585e90)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c7b717bd-622b-41bb-8e68-1b4dd2ac99b3)

修改文档名以后也没有刷新

### Describe the optimal solution

虽说不一定需要那么实时，但至少有必要隔一段时间刷新一下。当然，最好是鼠标移上去就刷新

**Comment by 88250** [comment]
@Vanessa219 增加 main 推送 `reloadDocInfo`：

![image](https://github.com/user-attachments/assets/39cecf85-ee70-414c-83ef-059986682c81)
