### ISSUE TITLE
Improve user guide formatting elements and shortcuts chapter

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11045]
### In what scenarios do you need this feature?

1. 「请从这里开始」应该是「块引用」

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6b63be2f-921c-47f9-954f-647dbc37810d)

2. Hyperlink 的中文应该叫 「超链接」

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c6c1ab07-2883-4787-b81f-956f8a8ae4d5)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f1acf0cb-e9ff-4aed-8722-c68c3eaba429)

3. 英文用户指南的 IFrame 演示应该改成一个 YouTube 视频（并且不会默认打开文档就播放）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6c315fe4-9b75-4225-9639-fff2cf291715)

### Describe the optimal solution

。

**Comment by 88250** [comment]
欢迎 PR 谢谢。

**Comment by 5kyfkr** [comment]
快捷键 介绍也可以备注下多选文档的操作
![image](https://github.com/siyuan-note/siyuan/assets/63196026/a0632fa2-972f-4664-afe4-8d6c0e4fc359)
还有 排版元素 的标题块下面也可以加一句介绍拖拽至文档树的介绍
![image](https://github.com/siyuan-note/siyuan/assets/63196026/a6e1d0f8-f3f3-4224-8c92-6807edfe9edc)

**Comment by TCOTC** [comment]
> 还有 排版元素 的标题块下面也可以加一句介绍拖拽至文档树的介绍

@5kyfkr 刚刚发现专门有个文档讲这个

![image](https://github.com/siyuan-note/siyuan/assets/78434827/247608ba-b442-4ed3-9091-18efdc17e216)

**Comment by 5kyfkr** [comment]
> @5kyfkr 刚刚发现专门有个文档讲这个

那就没事了，太久没细翻思源的说明了

**Comment by TCOTC** [comment]
#11049
