### ISSUE TITLE
Improve database table view row/col drag and drop sorting

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11048]
在数据库里拖动行时，「来回拖动」的话往往就没法把这一行拖动到最后指定的位置

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

操作是「来回拖动」，试一下就明白了
![CleanShot 2024-04-16 at 09 51 17](https://github.com/siyuan-note/siyuan/assets/50087596/b91a2a29-82a8-4a9d-a45e-723382ad5383)

### Expected result

.

### Version environment

```markdown
- Version: 3.0.9
- Operating System: macOS 
- Browser (if used): 13.6.6
```

### Log file

,

**Comment by TCOTC** [comment]
可以复现

**Comment by 88250** [comment]
我这里重现不了：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/78ac0a36-1964-4f4e-af8f-c58943449832)

**Comment by TCOTC** [comment]
@88250 「来回拖动」是要拖回原位
