### ISSUE TITLE
增加数据库最下一行 的自定义计算

### ISSUE THREAD

**Issue by Keeyuu** [siyuan-note/siyuan#11040]
### In what scenarios do you need this feature?

使用数据库替代excel的一些简单的计算,但是又没有内置的算法,
比如想算大于某个值的比例, 直接把所有需要的列出来不太现实,
不如直接给一个可以自定义算法的方法
![image](https://github.com/siyuan-note/siyuan/assets/38851875/31ca52b7-fe2c-4ead-8fdb-291264364244)

### Describe the optimal solution

.

### Describe the candidate solution

.

### Other information

.

**Comment by TCOTC** [comment]
赞同

**Comment by hdg8087** [comment]
数据库表格下方的数值计算，能指定小数点后几位吗？

**Comment by 88250** [comment]
抱歉不考虑原生支持了，也许可以通过插件实现。
