### ISSUE TITLE
去掉文件夹下对非思源 .md 的导入支持

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1104]
之前如果文件夹下存在 .md 且不是思源格式（没有 ID）时会进行识别转换，这个功能需要遍历文件，对性能消耗较大，并且使用起来有些“隐式”，更通用的导入使用方式还是通过界面打开笔记本文件夹进行。

所以我们决定去掉这个导入行为，后期可能会在界面上单独加入导入到已有笔记本文件夹功能。

**Comment by roverway** [comment]
其实导入单个非思源格式md文件对我来说很重要，因为思源笔记目前编辑替换功能不足，我经常把从pdf或从网页复制来的文件（内容比较乱，比如换行错误，有多个空格等等），用vscode通过正则替换等各种方式批量处理成干净的md文件（比如去除多余换行、去除多余空格，特定内容批量加粗或设置标题层级等等），之后再用思源打开，被思源处理成含id的格式。

上面处理过的文件对我来说不是一个单独的笔记本，而是目前笔记本下应当增加的若干文档。如果去除这个功能，上面的的需求我该怎么解决呢？把vscode处理好的文件单独放在一个临时文件夹中，用思源笔记打开这个文件夹，生成临时笔记本，等思源笔记处理完成后，再把处理过的文件从临时笔记本转移到现有笔记本中？

是不只能这样了？

或者是否可以增加像向现有笔记本导入一个或多个md文件的功能？

**Comment by 88250** [comment]
@roverway 去掉以后先用打开笔记本功能顶顶，如果需要频繁导入是有点麻烦。后面会支持单个或者批量导入 md 的，谢谢。

**Comment by roverway** [comment]
好的，我这个不是高频需求，可以隔一段时间会需要导入十个八个的，主要是VScode的的批量编辑替换功能很重要，这个没办法用思源笔记完成。

我曾经一次导入过100多个md文件，那还是早期，据说id处理功能不完善，能感觉到需要一段时间，而且有些文件确实没被添加id。再后来还一次导入过20多个文件，遍历文件几乎感觉不到性能影响，而且id也都完成添加了。

估计思源笔记的多文件同时编辑能力大概率是比不上vscode之类的编辑器的，所以批量导入md文件的功能一定有。

**Comment by 88250** [comment]
@roverway 计划在 v0.6.5 中去掉底层导入的同时加上界面导入。
