### ISSUE TITLE
Prompt when there is no normal exit

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11054]
移动端未通过「退出应用」按钮退出，下次启动时提示

### In what scenarios do you need this feature?

[数据不知道为啥失踪了，有个笔记本包括里边的文档找不到了，我天天加班加懵逼了还是？ - JeffreyChen 的回帖 - 链滴](https://ld246.com/article/1713141274118/comment/1713241507854#comments)

> 建议还是加个提醒，99% 的 app 都是直接划掉退出的，既然思源这点不符合用户习惯，那么还是需要提醒一下。比如：进入 app 后，发现上次退出不是通过“退出应用”功能，提示不要这样做。
> 
> 不然，恐怕 D 大你将要一次次不断提醒新用户这件事…

> 进入 app 后，发现上次退出不是通过“退出应用”功能，提示不要这样做。

感觉这个交互很合理，比如每次启动内核与点击「退出应用」都单独记录一下，下次启动根据记录来判断

毕竟大多数用户不会看完用户指南，还是需要软件主动提醒

### Describe the optimal solution

移动端未通过「退出应用」按钮退出，下次启动时提示。

提示的内容像是这样：“检测到应用意外关闭。请使用菜单栏「退出应用」按钮退出应用，以免造成数据丢失。”

**Comment by Soltus** [comment]
改进方向难道不应该是意外关闭的处理吗，即使你要求用户按规范使用菜单栏退出应用，意外关闭也是不可避免的

**Comment by TCOTC** [comment]
> 改进方向难道不应该是意外关闭的处理吗，即使你要求用户按规范使用菜单栏退出应用，意外关闭也是不可避免的

但问题是，意外关闭——都关闭了还能怎么处理？关闭的那一瞬间问题就发生了。所以只能尽量提醒用户。

**Comment by Soltus** [comment]
你用电脑断电类比是不恰当的，安卓应用是有对应的关闭事件的

**Comment by 88250** [comment]
> 你用电脑断电类比是不恰当的，安卓应用是有对应的关闭事件的

老铁给点提示，谢谢。

**Comment by Soltus** [comment]
> > 你用电脑断电类比是不恰当的，安卓应用是有对应的关闭事件的
> 
> 老铁给点提示，谢谢。

应该是在 App 的 [onActivityPreDestroyed ](https://github.com/Hi-Windom/Sillot-android/blob/main/app/src/main/java/org/b3log/siyuan/App.kt#L111-L114)里处理，能不能成我没试过

**Comment by Soltus** [comment]
> 应该是在 App 的 [onActivityPreDestroyed ](https://github.com/Hi-Windom/Sillot-android/blob/main/app/src/main/java/org/b3log/siyuan/App.kt#L111-L114)里处理，能不能成我没试过，稍等我去试试

试了一下onActivityPreDestroyed能处理的任务有限，[onSaveInstanceState](https://cloud.tencent.com/developer/article/1661080) 更适合 @88250

**Comment by 88250** [comment]
收到，等有空我试试，多谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月22日(周一) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 移动端未通过「退出应用」按钮退出，下次启动时提示 (Issue #11054)




  
应该是在 App 的 onActivityPreDestroyed 里处理，能不能成我没试过，稍等我去试试
  
试了一下onActivityPreDestroyed能处理的任务有限，onSaveInstanceState 更适合 @88250

**Comment by 88250** [comment]
考虑了下，还是用内核来记录吧，这样桌面端也能用。
