### ISSUE TITLE
导入 Markdown 到已有笔记本文件夹下

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1105]
https://github.com/siyuan-note/siyuan/issues/1104 后需要支持导入单个 Markdown 或者文件夹到已有笔记本下。

**Comment by xiosi** [comment]
无语了，docker网页的怎么导入啊，导入后的效果是怎么样的，用户指南的
* Parse and generate content blocks
* Convert `[[link|text]]` to content block reference
* Convert `#tag `to `#tag#`
完全没看懂

**Comment by JOE898** [comment]
请问现在可以导入其他MD文件吗

**Comment by 88250** [comment]
@JOE898 桌面端支持导入 Markdown 文件
