### ISSUE TITLE
数据库新建列菜单定位异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11051]
### 数据库新建列菜单定位异常

完全按照下面的操作，有概率复现：

![菜单](https://github.com/siyuan-note/siyuan/assets/78434827/c44b08a8-a506-40f5-bbc5-3e7c002e076c)

**Comment by 88250** [comment]
我试了 3 次，暂时没有重现。

**Comment by TCOTC** [comment]
我这里是编辑列名称后马上在右边添加一列就有概率出现

**Comment by 88250** [comment]
好的，我也可以重现了，多谢。
