### ISSUE TITLE
数据库 返回上一步菜单时返回了其他菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11052]
### 数据库 返回上一步菜单时返回了其他菜单

![菜单](https://github.com/siyuan-note/siyuan/assets/78434827/715fa2a7-0609-4090-98b1-034cde1e7a4c)

**Comment by Vanessa219** [comment]
右侧的菜单点击 `<` 图标都是返回到上一级的菜单，图中的两个菜单都属于平级。

**Comment by TCOTC** [comment]
但是很反直觉

**Comment by Vanessa219** [comment]
这两个菜单不属于同一个面板
