### ISSUE TITLE
Improve `Copy text *`

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#11057]
provide shortkey configuration for copy block reference as  *

### In what scenarios do you need this feature?

For now, there is configuration for copy block reference as "text *", but the copy "*" is also useful in some case.
Just a shortkey configuration, the UI element is not neccessary.

### Describe the optimal solution

-

**Comment by Vanessa219** [comment]
Do you mean "copy text*"?

<img width="1065" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/ad78ae2a-b724-4be1-b9c2-190cc244dad4">

**Comment by XinLi0111** [comment]
> Do you mean "copy text*"?
> 
> <img alt="image" width="1065" src="https://private-user-images.githubusercontent.com/970828/323898458-ad78ae2a-b724-4be1-b9c2-190cc244dad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDI5OTksIm5iZiI6MTcxMzU0MjY5OSwicGF0aCI6Ii85NzA4MjgvMzIzODk4NDU4LWFkNzhhZTJhLWI3MjQtNGJlMS1iOWMyLTE5MGNjMjQ0ZGFkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQxNjA0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTFiZGU1YjRhYjcwMGRkMWM4ZThmYjc1ODNhMDljNWI5MTFmNDgzZmZhODM3Njg5OWE2OGIyNjMyZGZlYWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pvg8pnBigEOpgeROK14dRt4CiJFQd_JxoxRdiuAR2wo">

No, just "Copy *", copy refence link as "*" without anchor text.

**Comment by Vanessa219** [comment]
没有复制 * 的这个功能

**Comment by XinLi0111** [comment]
是的，但是希望能提供功能并支持设定快捷键，避免菜单冗余。

另外，是否考虑优化复制为功能菜单，将这些复制功能统一为复制，在粘贴的时候再选择粘贴为。
一方面向word等软件都是类似操作，另一方面，需要的粘贴为什么样的格式在需要粘贴附近能更清晰的决断，而不是在复制的时候，这样也方便复制一次，在不同位置粘贴为不同样式。

**Comment by 88250** [comment]
考虑改进 `复制 文本 *` 功能：

* 在选中整个块时，则使用块级锚文本（和现在一样）
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/fa76f300-820f-47f3-9beb-3a70d1ed06cf)
* 在选中块中部分行级元素时，则使用选中的内容作为锚文本 
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/aa62492f-5f1c-4d91-940f-96fd1ce119be)
* 在不选中任何元素时（仅光标位于块内任意位置）时，则使用 `*` 作为锚文本
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/4b217849-3650-4c87-827b-165050a741c0)

这样能避免增加新的功能入口，同时没有副作用，我觉得应该没问题。

@Vanessa219

**Comment by 88250** [comment]
> 另外，是否考虑优化复制为功能菜单，将这些复制功能统一为复制，在粘贴的时候再选择粘贴为。
一方面向word等软件都是类似操作，另一方面，需要的粘贴为什么样的格式在需要粘贴附近能更清晰的决断，而不是在复制的时候，这样也方便复制一次，在不同位置粘贴为不同样式。

这个只能在复制时区分，因为粘贴时有的软件并不支持处理思源的富文本格式，所以只能在复制时区分是否是纯文本，类似 JetBrains IDE 的做法：

![image](https://github.com/siyuan-note/siyuan/assets/873584/50798906-f09b-4e6a-a23d-07bb4e66394a)
