### ISSUE TITLE
Improve database rollup filtering

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11059]
数据库新增条目没有参与筛选，与勾选框有关

## Describe the problem

[文档.sy.zip](https://github.com/siyuan-note/siyuan/files/14996207/sy.zip)

### 在这个文档，数据库汇总是正常的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/428aa068-332b-4bbd-ae23-a5ef7917b2e4)

### 但以汇总为筛选条件后就不对了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2d5c6d35-3fbe-4042-8a6a-af0c2aa4995f)

### 只有将任务 1、2 的勾选框「勾选再取消勾选」后才会显示：

![数据库](https://github.com/siyuan-note/siyuan/assets/78434827/7e9f51cf-49b4-449b-b604-1c0b0411cd73)

## Version environment

```markdown
- Version: v3.0.10
- Operating System: Win10
- Browser (if used):
```

## More information

也许与 #11016 有关

**Comment by 88250** [comment]
感谢反馈，和 11016 无关，是因为汇总的目标值没有初始化，这里需要填充默认值。
