### ISSUE TITLE
The database supports adding view/field/option description

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11053]
数据库支持添加视图描述、字段描述、选项描述，并显示在悬浮提示里

- [ ] 视图描述
- [ ] 字段描述
- [ ] 选项描述

### In what scenarios do you need this feature?

有时候需要给属性作补充说明，放在标题里太长了也不方便看，而且文本会被截断所以不美观

![image](https://github.com/siyuan-note/siyuan/assets/78434827/89b19752-e9e8-4951-a5d9-9d78e3554bfd)

### Describe the optimal solution

- ~~备注~~ 描述支持多行文本（Shift+Enter换行）
- 通过悬浮提示显示 ~~备注~~ 描述内容

**Comment by hdg8087** [comment]
支持。你说的这个也就是其它多维表格的 长文本 数据类型。
但你提出的 悬浮，的确是比较棒的想法。

**Comment by TCOTC** [comment]
我发现飞书多维表有类似的功能：

![image](https://github.com/user-attachments/assets/daeec91b-33d3-49ab-a315-1ea5b9ee48f9)

![image](https://github.com/user-attachments/assets/07cbac75-4005-4f00-ab63-3a149b7b5de5)

![image](https://github.com/user-attachments/assets/16adec03-5eaa-434e-b281-b03d430c4458)

**Comment by TCOTC** [comment]
Notion 也有：

![image](https://github.com/user-attachments/assets/70f9a050-d46e-439d-98a6-e7485333af63)

![image](https://github.com/user-attachments/assets/bae34b71-da31-4a55-a13c-fac07c57bc33)

![image](https://github.com/user-attachments/assets/b1839cfa-99aa-4c1b-8d15-b1242c075406)

![image](https://github.com/user-attachments/assets/7fedcd0f-4265-4037-98a2-ecfca5116ebd)

**Comment by TCOTC** [comment]
Notion 的选项描述只有打开菜单才能显示和编辑，思源可以更进一步显示悬浮提示：

p.s. 20251008：Notion 已经有悬浮提示了 https://github.com/siyuan-note/siyuan/issues/15598#issuecomment-3380312966

[视频.webm](https://github.com/user-attachments/assets/6851734d-c3c4-4983-89c2-3c6a56d393c9)

**Comment by cordinGH** [comment]
很赞的提议。好评！

**Comment by 88250** [comment]
@Vanessa219 setAttrViewColDesc setAttrViewColOptionDesc setAttrViewViewDesc
