### ISSUE TITLE
Supports replacing text elements with other elements

### ISSUE THREAD

**Issue by tagaga** [siyuan-note/siyuan#11058]
搜索替换的bug？？？

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

将“何”字换成标签何小二，替换为“#何小二#”，替换后变成了“###何小二#小二#小二#”，是替换参数设定错了 的原因，还是bug？

### Expected result

将“何”字换成标签何小二，替换为“#何小二#”，替换后变成了“###何小二#小二#小二#”，是替换参数设定错了 的原因，还是bug？

### Screenshot or screen recording presentation

替换为“#何小二#”

### Version environment

```markdown
- Version: 3.0.10
- Operating System: win11
- Browser (if used):
```

### Log file

I 2024/04/16 17:58:49 repository.go:1274: syncing data repo [device=138f83fd-1d5e-431f-9001-442a78bac5c4, kernel=epsol08, provider=3, mode=a/false]
I 2024/04/16 17:58:49 ref.go:50: got local latest [device=138f83fd-1d5e-431f-9001-442a78bac5c4/windows, id=ebf4f78459ee94f42f976991a453333a7ec9d5c0, files=534, size=35 MB, created=2024-04-16 17:42:39]
I 2024/04/16 17:58:49 repo.go:595: walk data [files=534] cost [46.5251ms]
I 2024/04/16 17:58:49 ref.go:50: got local latest [device=138f83fd-1d5e-431f-9001-442a78bac5c4/windows, id=ebf4f78459ee94f42f976991a453333a7ec9d5c0, files=534, size=35 MB, created=2024-04-16 17:42:39]
I 2024/04/16 17:58:49 webdav.go:92: uploaded object [main/siyuan/repo/lock-sync]
I 2024/04/16 17:58:49 ref.go:50: got local latest [device=138f83fd-1d5e-431f-9001-442a78bac5c4/windows, id=ebf4f78459ee94f42f976991a453333a7ec9d5c0, files=534, size=35 MB, created=2024-04-16 17:42:39]
I 2024/04/16 17:58:50 webdav.go:104: downloaded object [main/siyuan/repo/refs/latest]
I 2024/04/16 17:58:50 webdav.go:104: downloaded object [main/siyuan/repo/indexes/ebf4f78459ee94f42f976991a453333a7ec9d5c0]
I 2024/04/16 17:58:50 sync.go:1581: got cloud latest [device=138f83fd-1d5e-431f-9001-442a78bac5c4/windows, id=ebf4f78459ee94f42f976991a453333a7ec9d5c0, files=534, size=35 MB, created=2024-04-16 17:42:39]
I 2024/04/16 17:58:50 webdav.go:116: removed object [main/siyuan/repo/lock-sync]
I 2024/04/16 17:58:50 repository.go:1342: synced data repo [device=138f83fd-1d5e-431f-9001-442a78bac5c4, kernel=epsol08, provider=3, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=23 kB] in [0.82s], merge result [conflicts=0, upserts=0, removes=0]

**Comment by 88250** [comment]
目前仅支持替换元素的内容，不支持修改元素的类型。

**Comment by TCOTC** [comment]
### 支持将文本替换为标签

这种情况下替换，支持转换为标签：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3c5f857b-5fa1-45f3-963b-3c1c4984cfd5)

变成这样：（标签样式是主题的效果）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7180e605-c4ec-49c8-ae27-15ae1ee65489)

而不是这样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e6eaffa0-9253-474d-924b-e7db4dc0bee8)

**Comment by TCOTC** [comment]
@88250 修改之后支持将文本替换为什么类型？标签、块引之类的都行吗？

**Comment by 88250** [comment]
应该都行，我只简单测了下标签和加粗。
