### ISSUE TITLE
Improve HTML parsing code blocks

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#11068]
代码块复制问题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这个代码块复制的时候会被识别成表格 [文章地址](https://www.lixueduan.com/posts/go/swagger/)
<img width="859" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/d92a07f3-bb65-41c6-af2f-39fcca5f9302">
<img width="631" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/4963869f-5f22-422e-8b79-3d9b49f77891">

### Expected result

希望识别成代码块

### Version environment

```markdown
- Version: 3.0.10
- Operating System: MacOS
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个网页用的就是 table 哦：

![image](https://github.com/siyuan-note/siyuan/assets/873584/1350a023-a4b2-4777-b3e0-e8d5eed164a1)

**Comment by kylehz** [comment]
里面是code，复制到typora里是可以识别的：
<img width="885" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/93ccb2d4-d4ba-4d3f-a645-626c1cc62fe6">

**Comment by 88250** [comment]
找到一个办法可以改进，下个版本再试试，谢谢。
