### ISSUE TITLE
Official Docker Compose file with documentation

### ISSUE THREAD

**Issue by petruut** [siyuan-note/siyuan#11069]
### In what scenarios do you need this feature?

This would be super useful to several communities, and would enable quick/ transparent and scalable deployment of your app.

### Describe the optimal solution

Ideally, a docker compose example that's official to the repo, with ample documentation e.g. regarding environmental variables setup.

**Comment by terwer** [comment]
For your reference:

https://github.com/terwer/my-note-docker/blob/main/docker-compose.yml

**Comment by 88250** [comment]
PR contributions are welcome, thank you!

**Comment by caph1993** [comment]
In siyuan-community there's a docker-compose example: https://github.com/siyuan-community/siyuan?tab=readme-ov-file#docker-compose
