### ISSUE TITLE
标签的限制 最大 32 

### ISSUE THREAD

**Issue by Foundation-Maker** [siyuan-note/siyuan#11067]
### In what scenarios do you need this feature?

![CleanShot_2024-04-17 _ 11 34 45@2x](https://github.com/siyuan-note/siyuan/assets/46839690/443e6aca-e9eb-4f74-82f3-8a30a32e9cfb)

### Describe the optimal solution

可以自由设定吗？

**Comment by 88250** [comment]
+几号，这个设置太大的话较为影响性能，所以为了稳妥起见，上限是 32 个。
