### ISSUE TITLE
Database date filter excludes empty values

### ISSUE THREAD

**Issue by hqweay** [siyuan-note/siyuan#11061]
数据库筛选 日期字段 < 当前 天 时会筛选出日期字段为空的条目

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库筛选 日期字段 < 当前 时间段 时会筛选出日期字段为空的条目。

<img width="510" alt="image" src="https://github.com/siyuan-note/siyuan/assets/23608642/d9d28a18-5b2c-4d64-8ca5-4cbcc5eedb96">

这是 bug 还是 feature？

### Expected result

无

### Version environment

```markdown
- Version: 3.0.10
- Operating System: MacOS
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
时间为空时不应该被筛选出来
