### ISSUE TITLE
数据库模板不起作用

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11063]
### In what scenarios do you need this feature?

[文档.sy.zip](https://github.com/siyuan-note/siyuan/files/14998044/sy.zip)

![ad35313b549c6e73a9aae765a599ea68](https://github.com/siyuan-note/siyuan/assets/78434827/ec901081-3130-4518-8f57-b9306b17d0f9)

![849a2cf7383182ef031d10d9672fd6ba](https://github.com/siyuan-note/siyuan/assets/78434827/f368a9dd-0ede-4da9-b145-33fe6fcaf863)

### Describe the optimal solution

。

**Comment by 88250** [comment]
模板有报错：

```
W 2024/04/17 10:27:42 node.go:1011: parse template [.action{$a := index .汇总 0}
.action{if eq $a 50}
.action{$b := 999}
.action{end}
.action{$b}] failed: template: :5: undefined variable "$b"
```

$b 的作用域只在 if 块里面生效。

**Comment by TCOTC** [comment]
这样为什么也不行呢？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/21f1a0cd-c196-4e19-91de-3419fdeaf55d)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2bf4a80a-1705-4356-b5bb-fa92772a61ae)

```
.action{$a := index .汇总 0}
.action{if eq $a 50}
999
.action{end}
```

**Comment by 88250** [comment]
数字字段都是浮点数，`if eq $a 50.0`

**Comment by TCOTC** [comment]
还有这个我不懂，为什么一行可以一行不行：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/40e4b6d3-6f8c-4d2a-9481-49801a352fe6)

```
.action{ $date := substr 3 7 (index . "日期") }
.action{ $date } 
.action{ $nowdate := now | WeekdayCN }
.action{ $nowdate } 
.action{ if eq $date $nowdate }
666
.action{ end }
```

[日期.sy.zip](https://github.com/siyuan-note/siyuan/files/15005349/sy.zip)

**Comment by 88250** [comment]
```
.action{ $date := substr 3 6 (index . "日期") }
```

保险点的话最好再 trim 一下：

```
.action{ $date := trim (substr 3 6 (index . "日期")) }
```
