### ISSUE TITLE
Limit the maximum number of tags listed in the tag panel

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11071]
改进标签面板性能

https://ld246.com/article/1713144021491

生成了一个 Markdown 包用于测试： [test.zip](https://github.com/siyuan-note/siyuan/files/15037730/test.zip)

限制一下最大列出数量（通过 设置 - 文档树 - 最大列出数量）

**Comment by TCOTC** [comment]
那可能要把「最大列出数量」改成：

### 最大列出数量
如果标签/子文档非常多，可通过该项限制以提升性能

**Comment by 88250** [comment]
嗯，文案需要调整的。
