### ISSUE TITLE
关联列删除一个，汇总列不会减少

### ISSUE THREAD

**Issue by Foundation-Maker** [siyuan-note/siyuan#11076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

关联列的对应数据库删除了一行。但是汇总列仍然存在删除了行的数据

### Expected result

不应该存在

### Version environment

```markdown
- Version: 3.0.10
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你好，我这里测试没有重现问题，请看录屏：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/bf2e3def-28ad-4d3a-bf71-4be88817426c)

你那里如果还能重现的话请导出 .sy.zip 发给我们调试看看 845765@qq.com

**Comment by Foundation-Maker** [comment]
> 你好，我这里测试没有重现问题，请看录屏：
> 
>  issue.webm 
> 你那里如果还能重现的话请导出 .sy.zip 发给我们调试看看 [845765@qq.com](mailto:845765@qq.com)

![CleanShot_2024-04-18 _ 10 20 17@2x](https://github.com/siyuan-note/siyuan/assets/46839690/513aa6e7-acad-49a7-8f0d-e1eb6cbda84e)
试了几次，不能准确复现，但是现在数量对不上。

**Comment by 88250** [comment]
F5 刷新或者重新打开这个文档还是不对吗？

**Comment by Foundation-Maker** [comment]
> F5 刷新或者重新打开这个文档还是不对吗？

对的，包括重建索引，我都试过了。

**Comment by 88250** [comment]
方便导出数据我调试看看么？

**Comment by Foundation-Maker** [comment]
> 方便导出数据我调试看看么？

不是很方便，下次好复现，我再回复 issue吧。

**Comment by 88250** [comment]
好的，如果有能够重现问题的最小数据集是最好了，谢谢。

**Comment by 88250** [comment]
我暂时先关闭这个 issue，如果后续有问题麻烦直接回复即可，多谢。
