### ISSUE TITLE
复制时链接从本地链接变为在线链接

### ISSUE THREAD

**Issue by Mocuishle-Zuiren** [siyuan-note/siyuan#1107]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

环境限制，网络并不是时时都有的，所以我开启了拉取图片到本地。有一个问题是，我想把文章发布到其他平台，导出md，发现图片的链接还是本地链接，这对我造成了烦恼，其实我是有网络图床的

### 描述最优的解决方案 Describe the optimal solution
上传图床后，我会粘贴一个图片链接放笔记，图片链接编程本地链接，但还是在某个地方给我保存了网络链接，在我导出md时，网络链接会取代本地连接

**Comment by 88250** [comment]
你好，如果有发布需求的话尽量用图床，插入图片的时候直接用 `![foo](bar)` 插入，谢谢。因为思源不可能知道某个图片链接和网络位置的对应关系。
