### ISSUE TITLE
Add `editors` to the plugin's `Custom` class

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11072]
### In what scenarios do you need this feature?

https://github.com/frostime/sy-docs-flow/issues/57
原因见链接issue，目前已知在文档流插件、KNote、卡片式写作，这三个插件内的文档编辑界面内，无法调用以下功能快捷键：
快速制卡、添加到数据库、全屏切换
根据插件作者说是有部分快捷键不能在插件的自定义 Protyle （文档编辑器）当中使用的，请问是否能改进？

### Describe the optimal solution

在插件的编辑界面可正常使用这些功能的快捷键

**Comment by Vanessa219** [comment]
这个是有点问题，可能需要讨论一下

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/558cac2b-0689-4cda-80de-9432f0b6b73f)
Dev2好像没有安装包

**Comment by 5kyfkr** [comment]
@Vanessa219 https://github.com/frostime/sy-docs-flow/issues/57 V姐帮忙看看怎么给插件开发者说明下要修改的地方有哪些？
![image](https://github.com/siyuan-note/siyuan/assets/63196026/ca5f579b-ff4b-42ef-a363-32d435076cf3)
