### ISSUE TITLE
Prompt when database template field reports an error

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11070]
模板列代码报错时增加报错内容显示

### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/63196026/5c42b76b-c29a-4f2b-8b18-746e8a0d810f)

此问题的来源 https://github.com/siyuan-note/siyuan/issues/11064
在以上issue中，模板列报错仅在后台日志可见，当报错会影响加载性能的时候就会需要调试，所以需要提供报错提示，不然就要一直导出日志，非常繁琐。

### Describe the optimal solution

可以在报错时提供额外的报错提示，在右上角弹出提示框告知，毕竟bug不解决的代码一直在后台生成报错信息也不太好，可能哪天就会有加载隐患。

**Comment by TCOTC** [comment]
@88250 希望报错信息增加数据库名称和模板列的名称。

在一个文档里有多个数据库、数据库有多个模板的情况下，一打开文档就报错，找起来很麻烦

**Comment by 5kyfkr** [comment]
> @88250 希望报错信息增加对应的数据库名称和模板列名称。
> 
> 在一个文档里有多个数据库、数据库有多个模板的情况下，一打开文档就报错，找起来很麻烦

确实可以加下，我已经预感到下版本会很多人一打开弹出一堆报错冲进论坛的场景了。。。

**Comment by 88250** [comment]
好的，稍后加一下数据库名和模板字段名

**Comment by TCOTC** [comment]
@88250 还有就是能不能给报错之类的信息增加一个复制按钮？

**Comment by 5kyfkr** [comment]
@88250 还有重复的的报错项能不能隐藏掉也好，感觉有很多是同一段代码重复执行的报错，不然看着一堆红色弹窗血压升高

**Comment by 88250** [comment]
> @88250 还有就是能不能给报错之类的信息增加一个复制按钮？

@Vanessa219

**Comment by 88250** [comment]
> @88250 还有重复的的报错项能不能隐藏掉也好，感觉有很多是同一段代码重复执行的报错，不然看着一堆红色弹窗血压升高。就是执行一遍后，报错以后就不再执行模板计算，后面修复了报错再执行。应该是个执行次数的问题。

一个模板字段只会报错一次。

**Comment by 5kyfkr** [comment]
> > @88250 还有重复的的报错项能不能隐藏掉也好，感觉有很多是同一段代码重复执行的报错，不然看着一堆红色弹窗血压升高。就是执行一遍后，报错以后就不再执行模板计算，后面修复了报错再执行。应该是个执行次数的问题。
> 
> 一个模板字段只会报错一次。

那就好，没问题了
