### ISSUE TITLE
Improv `Ctrl+Click` select/deselect blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11075]
### `Ctrl+Click` 无法选中嵌入块

![块](https://github.com/siyuan-note/siyuan/assets/78434827/dee80081-b68e-4610-babd-b09c9371eaf6)

关联 [复制纯文本时嵌入块的查询语句被复制了 - 链滴](https://ld246.com/article/1713057285897) 的回帖

**Comment by TCOTC** [comment]
`Ctrl+Click` 点击数据库会变成编辑单元格

**Comment by TCOTC** [comment]
`Ctrl+Click` 点击标签

**Comment by Vanessa219** [comment]
都要改的，但是 ctrl+click 点击标签是添加该标签一同进行搜索的功能。这个可能改不了。
