### ISSUE TITLE
The local graph refresh fails after the reference in the doc changes

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11087]
在页面的数据库中建立链接后，关系图中的刷新按钮不起作用

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

见附件中的Untitled文件。
[1.sy.zip](https://github.com/siyuan-note/siyuan/files/15028792/1.sy.zip)

在文档中建立新的链接（以及建立新内容块，需要在关系图中打开相应选项）后，刷新按钮不能刷新关系图。
经测试发现是因为我在该页面的数据库里链接了其它文档块导致的，后续没有做进一步测试。
<img width="492" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/384e7bab-b0d5-46b6-a421-e2de25a3e9fc">

复现步骤：打开局部/全局关系图，在上面的Untitled文档里随便新建点儿链接，然后刷新关系图，会发现新建的链接关系没有出现在关系图上。

### Expected result

.

### Version environment

```markdown
- Version: 3.0.10
- Operating System: macOS
- Browser (if used): 13.6.6
```

### Log file

.

**Comment by 88250** [comment]
我无法重现问题，请在di点击刷新操作后导出上传系统日志。

![image](https://github.com/siyuan-note/siyuan/assets/873584/0ad9c270-c6db-4fe1-a13f-43219b246822)

**Comment by LoneFireBlossom** [comment]
试试全局关系图？
https://github.com/siyuan-note/siyuan/assets/50087596/3dab1da4-303e-4867-9d2a-52bc3db3d8f7
