### ISSUE TITLE
同步失败，提示"网络异常，请稍后重试”

### ISSUE THREAD

**Issue by lyur01** [siyuan-note/siyuan#11082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用阿里云oss进行同步，一直失败，提示“网络异常”，删除阿里云oss存储文件后，全量同步本地到远程是正常的，之后再次同步仍然报错“网络异常”

### Expected result

可正常同步

### Version environment

```markdown
- Version: v3.0.10
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15025135/siyuan.log)

**Comment by 88250** [comment]
从日志上看，你使用的是阿里云香港 S3 节点，网络可能不稳定。

中国大陆地区使用的话不要使用非大陆的 S3 服务，否则网络可能会被阻断。
