### ISSUE TITLE
Improve rollup column setting

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#11083]
<img width="352" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/89b83411-6628-44ed-a9c0-69b77e72b121">

1. 修改关联后清空汇总字段和汇总方式
2. 修改汇总字段后清空汇总方式

**Comment by TCOTC** [comment]
> 修改汇总字段后清空汇总方式

我觉得能保留的话应该尽量保留，没有对应的汇总方式保留不了才清空

**Comment by Vanessa219** [comment]
切换了就给用户重新选吧
