### ISSUE TITLE
方向键上键有时无法控制光标！

### ISSUE THREAD

**Issue by nightlye** [siyuan-note/siyuan#1108]
https://user-images.githubusercontent.com/53067795/104796640-fdff4800-57f2-11eb-9eec-149be6812792.mp4

如视频中所显示，像这种插入行内代码、latex的情况，在该行末可能会有无法用上键控制光标的情况

**Comment by Lemoners** [comment]
# Siyuan最新版本仍存在光标无法移动问题
- Siyuan版本: v1.1.6
- 问题描述:
    - 如下方视频所示: 键盘上键无法控制光标

https://user-images.githubusercontent.com/39124095/112852391-741b0780-90de-11eb-82e8-ba1fd8d5d165.mp4

**Comment by Lemoners** [comment]
重新试了一个Minimal的会出错的文本:
![image](https://user-images.githubusercontent.com/39124095/112858489-8009c800-90e4-11eb-9449-725b3354b546.png)
***
```
{: id="20210329230616-r1yngqh"}

- {: id="20210329230605-yu6qyvp"}((20200813163359-v04n73b "测试引用")): 是一个引用
  {: id="20210329230605-414w0ox" updated="20210329230644"}
- {: id="20210329230533-0jhnwhg"}`{{`: 这是一段测试文字
  {: id="20210329230533-5897knk" updated="20210329230628"}
{: id="20210329230527-wnmg6cl" updated="20210329230529"}


{: id="20210329230527-lmc2cd0" type="doc"}
```
视频如下:

https://user-images.githubusercontent.com/39124095/112858744-bd@88250 e5580-90e4-11eb-893e-bfd0f3646119.mp4

当快速多次敲击上键时光标会产生移动, 但正常的单次敲击并没有反应. 希望大大 @88250 能看看这个问题, 方向键不能使用在写文档的时候还挺影响思路的.
