### ISSUE TITLE
改进水平/垂直布局快捷键名称

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11089]
### In what scenarios do you need this feature?

搜「合并」「超级块」都搜不到，结果发现叫「XX布局」：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/12f05e5b-8816-450a-b78c-c56b7e4e66d6)

### Describe the optimal solution

建议把「XX布局」改成「合并为超级块XX布局」

**Comment by Vanessa219** [comment]
按照界面这样命名是合理的
<img width="323" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/0b17d4dd-f84e-4b76-b97e-7734a2adc14c">

**Comment by TCOTC** [comment]
前面的「合并为超级块」被吞掉了啊

![image](https://github.com/siyuan-note/siyuan/assets/78434827/19023fe2-0024-4ee8-bad3-315313aa44f9)

**Comment by Vanessa219** [comment]
要不就重复了，快捷键和前面的名称是完全匹配的。这样用户才好搜索。

**Comment by TCOTC** [comment]
但问题在于用户搜索的是「合并」「超级块」

**Comment by Vanessa219** [comment]
搜不到的话可以看帮助文档或换换成合并

**Comment by TCOTC** [comment]
直觉上只会搜“超级块”，不会去搜“XX布局”：

https://github.com/siyuan-note/siyuan/issues/16740#issuecomment-3703187861

![Image](https://github.com/user-attachments/assets/2737ffad-3a08-4718-b1b7-a0653a3e7cfe)

**Comment by caiweihan** [comment]
确实如这个 issue 所说，我尝试搜索过“合并超级块” > “垂直布局”快捷键，但搜索的是“超级块”

**Comment by Vanessa219** [comment]
带入超级块几个字的话菜单会就会重复超级块几个字。搜索不到换个关键字，毕竟不是经常修改，但菜单是经常看的。

**Comment by caiweihan** [comment]
> 带入超级块几个字的话菜单会就会重复超级块几个字。搜索不到换个关键字，毕竟不是经常修改，但菜单是经常看的。

那可以将编辑快捷键的 “垂直布局” 放在 “编辑器” > “通用” > “合并 超级块” 下面，和右键菜单保持一致。
问题不在于搜索不到就换个关键词搜索，一般用户搜索不到只会认为没有“超级块”相关的快捷键，就放弃搜索了。

**Comment by Vanessa219** [comment]
底层结构不是这样的 -_-||

**Comment by TCOTC** [comment]
> 带入超级块几个字的话菜单会就会重复超级块几个字

菜单文案和快捷键文案分开

**Comment by Vanessa219** [comment]
不进行修改了。搜索不到看一下菜单照着搜索即可。
