### ISSUE TITLE
数据库里的引用在关系图中均不显示

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如标题所示。
“数据库里的链接也是链接”，数据库就是动态表格，表格里的链接算链接线，所以数据库的链接线肯定也得算

### Expected result

实现应该有方面，首先数据库里的链接肯定算做文档的outgoing links。
其次数据库作为单独的一个选项也可以勾选使其单独显示。不过估计实现上是不是麻烦一些，因为数据库可以复制到多个地方。
<img width="186" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/039ed737-ee9a-4f4b-9074-32b1c7b19d2e">

### Version environment

```markdown
- Version: 3.0.10
- Operating System: macOS
- Browser (if used): 13.6.6
```

### Log file

.

**Comment by 88250** [comment]
这个不考虑了，关系图不再进行改进，感谢提议。

**Comment by LoneFireBlossom** [comment]
额，不改进是因为觉得关系图没什么卵用吧？以前我是这么想的，因为看过哈桑的文章。
但后来我发现关系图还是有一定用处。例如，要在工作空间里搜索关键词“曹操”，「在关系图中搜索」是查看自己记录了多少相关内容、这些内容之间的联系的**最直观的**方式。
其次是关系推导
![CleanShot 2024-04-19 at 11 34 19@2x](https://github.com/siyuan-note/siyuan/assets/50087596/88a8b33b-0557-4c52-b6cb-b8087e123f7a)

然后，本issue算是对关系图的基础功能的完善，关系图里连线都不全😂
而且，我觉得 [在页面的数据库中建立链接后，关系图中的刷新按钮不起作用 · Issue #11087 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/11087) 这两个issue是不是有什么关系，要解决就得一块儿解决🤔

**Comment by 88250** [comment]
是的，所以不考虑再动关系图了，后面那个 issue 等看看是不是有关联，有的话得解决，至少不能影响现有关系图使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月19日(周五) 中午11:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 数据库里的引用在关系图中均不显示 (Issue #11086)




 
额，不改进是因为觉得关系图没什么卵用吧？以前我是这么想的，因为看过哈桑的文章。
 但后来我发现关系图还是有一定用处。例如，要在工作空间里搜索关键词“曹操”，「在关系图中搜索」是查看自己记录了多少相关内容、这些内容之间的联系的最直观的方式。
 其次是关系推导
 ***@***.*** (view on web)
 
然后，本issue算是对关系图的基础功能的完善，关系图里连线都不全😂
 而且，我觉得 在页面的数据库中建立链接后，关系图中的刷新按钮不起作用 · Issue #11087 · siyuan-note/siyuan 这两个issue是不是有什么关系，要解决就得一块儿解决🤔
