### ISSUE TITLE
全局搜索功能给搞坏了,请修复

### ISSUE THREAD

**Issue by leeyaunlong** [siyuan-note/siyuan#11081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

3.0.10版后,全局搜索给改坏了
ctrl+p后 , 默认把最后一个保存的查询配置给读出来了.
全局不就是默认没有范围, 没有search word吗?

https://ld246.com/article/1713336942155

### Expected result

全局搜索应该 默认没有范围没有search word

### Version environment

```markdown
- Version: 3.0.10
- Operating System: win11
- Browser (if used):
```

### Log file

No

**Comment by 88250** [comment]
这块应该没有动过，默认就是使用上次的查询条件的。
