### ISSUE TITLE
Unable to input after deleting columns in the table under the list item

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11085]
列表嵌套表格块，对表格块进行删除操作后无法在此行进行输入，与理想情况不符

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

删除表格的操作：反复使用右键菜单的「删除列」。
![CleanShot 2024-04-19 at 01 15 15](https://github.com/siyuan-note/siyuan/assets/50087596/a2d358c7-6dc7-4f9b-9d0a-1d7e1fc2abd6)

### Expected result

理想情况是把表格全删掉后这一行立刻变回没有任何东西插入时的宽度，然后可以输入文字。
现实与理想情况不符。

建议是在列表上至少显示表格块块标，这样用块标来删除表格（如 [建议在多个块发生嵌套时将所有类型的块标都显示出来 - wxtgood 的回帖 - 链滴](https://ld246.com/article/1711588982750/comment/1712487384902#comments) ）
不对，这样还是会删掉整个列表

又或者是可以选中表格的一部分/全部后使用Delete键就可以删除，不需要通过右键菜单；全部删除后直接变成非嵌套块

### Version environment

```markdown
- Version: 3.0.10
- Operating System: macOS
- Browser (if used): 13.6.6
```

### Log file

.

**Comment by 88250** [comment]
* 使用 Esc 可以选中当前块，然后 Del/Backspace 就能删除了
* 在列表项下如果只有一个子块，则删除该子块后父块（列表项）也会被一并删除；如果有多个子块，则仅删除选中的子块

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/b3932d03-a567-49db-85e0-8afb1f37bb11)

[issue1.webm](https://github.com/siyuan-note/siyuan/assets/873584/6c25149b-80cb-4010-ab07-6cb690af363c)

**Comment by 88250** [comment]
对了，多次删除列不可输入的情况 @Vanessa219 看一下。

**Comment by LoneFireBlossom** [comment]
> * 使用 Esc 可以选中当前块，然后 Del/Backspace 就能删除了

我知道这个操作理论上可行，但是现实里这么删掉的话这一个列表项就没了，那么这个列表项块的ID就没了。如果这个列表项块有引用呢？我如果用这个方法删的话，我所有的引用就都失效了啊，所以得需要一个只删掉表格，但是这个列表项块还存在的方法

**Comment by 88250** [comment]
删除前可以通过引用计数判断是否有引用。

是否能保留父块列表项得 @Vanessa219 看看。

**Comment by LoneFireBlossom** [comment]
关联： [改进列表内“末尾插入块”的实现方式 · Issue #11107 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/11107)

**Comment by LoneFireBlossom** [comment]
> 是否能保留父块列表项得 @Vanessa219 看看。

我发现这个问题不止是对表格块，对其它情况也是如此：
对列表里的标题块、代码项块进行删除操作，这个列表也会随之消失。
![CleanShot 2024-04-21 at 19 57 23](https://github.com/siyuan-note/siyuan/assets/50087596/35356ebd-2807-4d6f-839b-72f7e5d9914f)

这符合用户直觉吗？我认为不符合。
不知道这是否符合开发者的设计意图？

**Comment by 88250** [comment]
得考虑一下，这个可能已经有用户习惯这样用了。

**Comment by LoneFireBlossom** [comment]
没看懂，用户要删列表块的话，点列表项的块标右键菜单啊，不会点这个菜单的，怎么会有用户习惯这么用呢

**Comment by 88250** [comment]
我指的是删除列表项下唯一子块的时候连同列表项一并删除。

**Comment by LoneFireBlossom** [comment]
要是这样的话，那我考虑提一个更复杂但是（在某种程度上）更合乎直觉的实现方案

对下面这个列表项块，光标在`段落块2`处
<img width="269" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/8ed37f9e-3549-408a-a625-c371eaaec8b8">

按ESC效果与以前一样，选中范围为：
<img width="460" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/8e123d1f-7c06-4504-a0fa-ec0c92bd4645">
此时按删除键就删除这个段落块。
**这更符合直觉，因为在视觉上只有段落块被选中了，前面的编号并没有被选中。**

再按一次ESC，选中范围为列表项块，也就是这个列表项块底色变了，变成强调色了：
<img width="670" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/46d22537-b429-4bd0-bf90-c4ff398aa5b1">
此时按删除键就删除这个列表项块。

再按一次ESC，选中范围为整个列表块，也就是这个列表块底色变了，变成强调色了：
<img width="677" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/879a6cd2-cfc8-4c3e-a7be-8729687b1020">
此时按删除键就删除这个列表块。


这个逻辑就像onenote里选中表格的逻辑，反复按ctrl+A，选中的区域回从当前文本-当前格子-当前行-整个表格逐渐扩展：

https://github.com/siyuan-note/siyuan/assets/50087596/df41f3d3-cb4b-410e-aa17-2b19c950efb8

**Comment by 88250** [comment]
现在有这个逻辑，不过用的不是多次 Esc，而是 Shift+↑，这个快捷键的作用就是往上级扩选，从子块逐层扩选父块。

**Comment by LoneFireBlossom** [comment]
哦哦，才知道。
那提案：

1. 让ESC键实现上述“从子块逐层扩选父块”的功能。
理由：目前ESC键的作用是“按一下选中光标所在的叶子（？）块，再按一下取消选中”。这个「再按一下取消选中」我觉得没有任何用处，因为有同样十分简易的方式来取消选中：随便打个字就行了。
2. 使用ESC选中一个块后，如果使用方向键也会取消选中。
理由：第一，将这也作为一个“取消选中”的方式。第二，「使用ESC键选中块时候再使用方向键」这种操作没什么实际使用场景吧？完全可以不要这个功能。

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
这个是参照 notion 的，实际用下来也觉得很方便的。

**Comment by LoneFireBlossom** [comment]
> 得考虑一下，这个可能已经有用户习惯这样用了。

只要ESC键有“从子块逐层扩选父块”的功能，那么有原有使用习惯的用户只需要从「按一次ESC键」变为「按两次ESC键」。我觉得这是非常好改的习惯——快速按两次ESC键非常容易，而且还有附带的体验优化：
第一，可以只删除子块了。
第二，按ESC键选中的区域更清晰、直观、容易理解了（按一下子块区域被高亮；按两下列表块区域被高亮），根据被高亮的区域范围，可以明确知道「自己按ESC键的话，哪一块区域会被删掉」。

**Comment by LoneFireBlossom** [comment]
> 这个是参照 notion 的，实际用下来也觉得很方便的。

notion的列表完全比不上思源的，思源能嵌套，notion的只能写纯文本、不能一个编号后面跟多个段落块。
因为更高级更强大，所以要完善的方面、要配套的措施也更多、更复杂😂

**Comment by 88250** [comment]
Esc 取消选块的逻辑也有人在用，这个不可能改了，改用 Shift+↑ 就用吧。

**Comment by LoneFireBlossom** [comment]
> Esc 取消选块的逻辑也有人在用，这个不可能改了，该用 Shift+↑ 就用吧。

ESC取消选块有什么使用场景吗……？我想象不出来

**Comment by 88250** [comment]
……我举个例子，选择了一个块时，如果没有 Esc 取消选中，假设用你说的方向键，那么如何在多个块之间切换？

**Comment by LoneFireBlossom** [comment]
"在多个块之间切换"是何意？

**Comment by 88250** [comment]
[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/15442436-e957-4a10-82ab-ed02a1604841)

**Comment by LoneFireBlossom** [comment]
> issue.webm

想了一下理解了，这是给别人演示用的吧？
