### ISSUE TITLE
支持将文本替换为标签

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11091]
### 支持将文本替换为标签

这种情况下替换，支持转换为标签：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3c5f857b-5fa1-45f3-963b-3c1c4984cfd5)

变成这样：（标签样式是主题的效果）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7180e605-c4ec-49c8-ae27-15ae1ee65489)

而不是这样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e6eaffa0-9253-474d-924b-e7db4dc0bee8)

---

关联：#11058

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/11058 中考虑。
