### ISSUE TITLE
Rows non-bound in the database support `Add to Database`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11093]
仅将主键文本复制到目标库的行主键中。

**Comment by TCOTC** [comment]
实现这个，应该需要顺便改一下目前的多选（目前是只有单选才有 `添加到数据库` ）：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/37cb9d38-01fc-4b47-a596-9849763f837f)

**Comment by 5kyfkr** [comment]
是滴，多选也应该能顺便弄了。以后有需求再整个带所有属性的“迁移到数据库”的功能
