### ISSUE TITLE
搜索结果重复

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#11099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

全局搜索, 结果有很多重复的, 如下
![Clip_2024-04-21_12-20-06](https://github.com/siyuan-note/siyuan/assets/48077521/3b3bde78-2a2c-4739-bb35-02c6536b19d7)

查看 http://127.0.0.1:65504/api/search/fullTextSearchBlock 返回结果
发现这些重复项的唯一差别是其 ial 的updated不同

```
                "ial": {
                    "custom-location": "20220814160448-0x1nq33",
                    "id": "20220814160419-2o9dp9j",
                    "title": "findstr",
                    "type": "doc",
                    "updated": "20240421110920"
                },
```

### Expected result

`

### Version environment

```markdown
- Version:  v3.0.10
- Operating System:  win10
- Browser (if used): no
```

### Log file

`

**Comment by 88250** [comment]
请重建索引以后再试试。

**Comment by iamqiz** [comment]
@88250  没作用

**Comment by 88250** [comment]
方便的话请导出数据发给我测试看看 845765@qq.com

**Comment by iamqiz** [comment]
噢, 我点的是数据历史里的重建索引,那个没用;  文档树菜单里的重建索引有用
我觉得重建索引麻烦, 这个问题可以通过二次过滤来解决; 或者SQL 去重? 
数据片段发你邮箱了

**Comment by 88250** [comment]
退出的时候不要强制结束进程，另外运行时第一次数据同步结束后会自动校验索引。

**Comment by iamqiz** [comment]
我印象中没怎么强制结束进程, 电脑重启更新时我也是等应用自动关闭后,剩余几个应用阻止关机我才强制关机的,这里面没有思源.
"运行时第一次数据同步"是什么时候? 之前我是手动同步,现在不用同步了,  
现在实现数据库部分重建索引了吗? 如果可以,那在我上面说的二次过滤基础上,自动对重复的文档进行重建索引?

**Comment by 88250** [comment]
那可能是上两个版本的 bug，升级 v3.0.10 以后需要手动重建索引；
就是启动以后执行完第一次数据同步后会自动校验索引，没有同步的话不会校验；
手动重建索引就是全量重建的。

**Comment by iamqiz** [comment]
手动是全量, 那自动时支持部分重建?
如果支持部分重建索引,那在我上面说的二次过滤基础上,自动对重复的文档进行重建索引,如何?

**Comment by iamqiz** [comment]
算了, 你说是上个版本的bug, 那先就这样吧, 以后再遇到再说

**Comment by 88250** [comment]
近期两个版本 v3.0.8/v3.0.9 数据索引有问题，所以我猜测应该是这个原因造成的。

**Comment by 88250** [comment]
同步后自动的索引校验不是全量重建，有几个检查步骤，其中一个就是去掉重复索引。

**Comment by heheda123123** [comment]
> 文档树菜单里的重建索引

 文档树菜单里没看到重建索引呀
![image](https://github.com/siyuan-note/siyuan/assets/97490782/07cfd5ea-dd02-4b4d-af4e-426f1244aea1)
