### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by sevntt** [siyuan-note/siyuan#11094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在一台服务器上面部署了两个docker服务(使用不同端口：192.168.2.199:6806  192.168.2.199:6807)，在一个浏览器同时登陆后，则先前一个登录的就会出现鉴权失败提醒。（可以在两个浏览器同时正常访问）感觉是全局密钥带来的问题？
![1713589690914](https://github.com/siyuan-note/siyuan/assets/87590779/ad77da2e-bf69-4d20-a838-3efbfb961c0b)

### Expected result

希望能够在一个浏览器同时访问多个网页服务，互不影响。

### Version environment

```markdown
- Version: 3.0.10
- Operating System: docker
- Browser (if used): edge_123
```

### Log file
[Uploading siyuan.log…]()

**Comment by 88250** [comment]
domain 一样端口不一样的情况下 cookie 是共享的，所以只有一个鉴权可以生效。这种情况建议使用不同 IP 或者域名。
