### ISSUE TITLE
拉伸编辑器大于最大宽度时显示最大宽度的右边界虚线

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1109]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

修改最大宽度时，拉伸编辑器，常常不知道有没有达到最大宽度，就需要一开始拉很宽，然后慢慢缩小，直到达到设置的最大宽度，有点麻烦。。
### 描述最优的解决方案 Describe the optimal solution
rt

### 其他信息 Other information
如果实现比较麻烦，可放到后期哈，，不急。。

**Comment by Vanessa219** [comment]
调整的时候是无法看见编辑器的，不行的话就用截图工具量一下适合的宽度后直接设置吧
