### ISSUE TITLE
Please enter the title of the feature request

### ISSUE THREAD

**Issue by zongqir** [siyuan-note/siyuan#11095]
### In what scenarios do you need this feature?

思源笔记缺乏flashcard的管理功能

### Describe the optimal solution

是否可以增强管理功能实现
1. 一个笔记本下的所有卡片视图
2. 一个文档下的所有卡片视图
3. 一个文档和子文档下的所有卡片视图
4. 卡片之间的关联关系 比如卡片a和卡片b之间的关联
目前基本没有地方统一管理闪卡 其实基本上也找不到卡和卡之间的联系

**Comment by 88250** [comment]
1、2、3 可以在文档树上右键 - 闪卡 - 管理

4 的话目前不考虑了，感谢反馈。
