### ISSUE TITLE
Database search keyboard is hidden on Android

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11098]
https://ld246.com/article/1713618202536

**Comment by wwxiaoqi** [comment]
这似乎是 Chromium 的问题，或许可以在 [bugs chromium issues](https://bugs.chromium.org/p/chromedriver/issues/list) 提一个

```logs
[ERROR:page_load_metrics_update_dispatcher.cc(119)] 
Invalid parse_blocked_on_script_execution_duration 0.909 s for parse duration 0.726 s
```

**Comment by wwxiaoqi** [comment]
当我使用 Firefox 的开源 WebView 代替产品：GeckoView，这个问题并没有发生。
![Snipaste_2024-04-26_11-37-23](https://github.com/siyuan-note/siyuan/assets/52415314/99ed7b75-5b3e-449c-baab-a9e6e724eae8)

GeckoView：
https://searchfox.org/mozilla-central/source/mobile/android/geckoview

**Comment by wwxiaoqi** [comment]
更新下：
调试完 WebView 发现原因是 JavaScript 脚本执行导致的阻塞导致的问题。

在初始化过程中：隐藏工具栏被执行了两次。

在点击数据库搜索过程中：那一块被当作了 Gone Status（猜测），导致了打开工具栏 JavaScript 代码还未执行完毕，又接着执行隐藏工具栏 JavaScript 代码....

所以才会有这个阻塞报错信息：
Invalid parse_blocked_on_script_execution_duration 0.909 s for parse duration 0.726 s

回头使用最新的 Android API 方法替换掉原有监听事件应该就可以解决这个问题了。


测试的话可以把隐藏工具栏 JavaScript 代码删掉，当 HTML 界面完全执行完毕后，点击正常...

**Comment by 88250** [comment]
> 回头使用最新的 Android API 方法替换掉原有监听事件应该就可以解决这个问题了。

有空的话请 PR 代码，谢谢。

**Comment by wwxiaoqi** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/52415314/2bddc424-7dbd-4b7b-876d-29a2e6a6dd4f)
试试将 input 变成 div 然后给个 contenteditable="true" 属性可否解决这个问题 😊

**Comment by Vanessa219** [comment]
有些地方的判断使用到 contenteditable="true" ，修改的话可能会引起其他输入的问题

**Comment by TCOTC** [comment]
https://ld246.com/article/1722588745977

**Comment by 88250** [comment]
暂时用一个折中方案解决：500ms 内键盘弹起又隐藏则强制再次显示键盘。缺点时显示后焦点会丢失，需要用户再次点击搜索框

先这样凑合顶顶。
