### ISSUE TITLE
数据库选中视图页居中显示

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11104]
### In what scenarios do you need this feature?

如下图，在视图较多的情况下想切换前方视图会需要进入视图列表里点选，现在默认点后面的视图会固定到最前方，导致前方视图标签页无法看到，如果来回切换视图会比较繁琐
![image](https://github.com/siyuan-note/siyuan/assets/63196026/61e08e5f-4821-4f5e-bc1d-6ea6300d6f10)

### Describe the optimal solution

建议如下图，判断在标签页数量超过切换栏宽度的时候，点击视图标签页后选中的标签页自动居中，这样就能显示前后的视图了，在手机端上也会更方便使用(屏幕窄)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/82489a80-c3ea-4714-9d3c-044ef41a797f)

**Comment by 5kyfkr** [comment]
好像可以用shift+滚轮，那电脑端似乎问题不大，看看实现困不困难，如果实现困难就算了

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/0585e29d-dfa8-4b35-806f-804a6b242401)
手机端直接就看不到，那就不整了

**Comment by TCOTC** [comment]
> 手机端直接就看不到

确实看不到了。

@Vanessa219 在移动端的数据库视图和旁边的按钮要不分开两行显示？按钮在上，视图在下
