### ISSUE TITLE
Change marketplace install package timeout to 2 minutes

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11106]
https://ld246.com/article/1713593712856

**Comment by TCOTC** [comment]
@88250 「全部更新」的超时时间是多久？

**Comment by 88250** [comment]
单个包安装 2m，全部的话都是按单个请求来的，全部更新没有单独的超时限制。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Mon, Apr 22, 2024 11:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Change marketplace install package timeoutto 2 minutes (Issue #11106)




 
@88250 「全部更新」的超时时间是多久？
