### ISSUE TITLE
支持复制资源文件

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11108]
“复制png“改为”复制为png”（copy as png）

### In what scenarios do you need this feature?

对gif、jpg/jpeg图片，右键菜单也显示“复制png”，看上去怪怪的。还是“复制为png”比较合适

另外，只实现了“复制为png”，而不能遵循图片的原格式复制（或者直接复制图片文件而不是图片，在剪贴板里的区别如下图所示），是electron的限制吗？
<img width="364" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/c42707e7-e791-4c55-b5a6-4ab4e9074ca7">

### Describe the optimal solution

.

**Comment by 88250** [comment]
感谢反馈，文案稍后调整。

> 另外，只实现了“复制为png”，而不能遵循图片的原格式复制（或者直接复制图片文件而不是图片，在剪贴板里的区别如下图所示），是electron的限制吗？

@Vanessa219

**Comment by Vanessa219** [comment]
@88250 应该可以直接用 go 写到剪切板里面吧

**Comment by 88250** [comment]
搜了下 golang 还真没有跨平台可写入任意文件的库（最多支持写入 PNG 文件到剪切板），自己开发又不会……

Electron 有 API https://www.electronjs.org/docs/latest/api/clipboard 但是好像仅支持文本和图片，不支持其他类型的文件。

如果只是 Windows 平台的话，用 PowerShell 的 Set-Clipboard 好像可以，但是用 ps 的话怕被杀软标记安全问题。

**Comment by Soltus** [comment]
> 搜了下 golang 还真没有跨平台可写入任意文件的库（最多支持写入 PNG 文件到剪切板），自己开发又不会……
> 
> Electron 有 API https://www.electronjs.org/docs/latest/api/clipboard 但是好像仅支持文本和图片，不支持其他类型的文件。
> 
> 如果只是 Windows 平台的话，用 PowerShell 的 Set-Clipboard 好像可以，但是用 ps 的话怕被杀软标记安全问题。

PS是肯定不行的，因为用户禁用脚本或者UAC等原因不同电脑上表现不一致无法预期

**Comment by LoneFireBlossom** [comment]
搜了一圈儿，怪不得复制图片只能复制成png。

[如何在 Windows 上自动将屏幕截图复制为 .jpg 而不是 .png？ - 超级用户 --- How can I automatically copy screenshots to .jpg instead of .png on Windows? - Super User](https://superuser.com/questions/1794331/how-can-i-automatically-copy-screenshots-to-jpg-instead-of-png-on-windows)
https://superuser.com/questions/1664216/why-does-google-chrome-and-safari-copy-image-as-png-representation

我觉得复制资源文件并不是非得实现的功能（其它本体笔记软件也没有这种功能吧？大概？），不知道别人是怎么想的

**Comment by 88250** [comment]
那就先不管了，打开本地文件夹以后再复制吧。
