### ISSUE TITLE
Database unbind block causes entry to be deleted

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11101]
v3.0.11-dev2

### 数据库取消绑定块导致条目删除

取消绑定块之后 刷新一下文档/新增一个条目 ，这个条目就消失了，导致「取消绑定块」基本等价于「删除」

![绑定](https://github.com/siyuan-note/siyuan/assets/78434827/137f6fe9-f8db-437e-b9eb-6c4e8cfe54d8)

**Comment by 88250** [comment]
测了下发现 v3.0.11 正式版也有该问题，感谢反馈。
