### ISSUE TITLE
改进列表内“末尾插入块”的实现方式

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11107]
### In what scenarios do you need this feature?

目前列表内使用“末尾插入块”的逻辑似乎是if-else的：

1. 如果一个列表有多项，那么使用此命令会插入一个同级、同父列表项。
2. 如果一个列表只有一项，那么使用此命令会插入一个段落块。

场景2在具体使用上会带来一些困扰：
在一个单项列表里写一个表格块/代码块后，如何顺着这个列表项继续写下去（也就是说，如何生成第二个列表项块）？
普通的回车没用，”末尾插入块“也没用。虽然有办法——就是新写一个列表块，拖进来成为其子项，然后再shift+tab，但这个显然对很多人不太友好。（我刚才就是想了一阵子才想出来）

<img width="1174" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/967b0d44-a8d8-4706-96ee-5b4b1a1c6e32">

### Describe the optimal solution

我觉得比较合适的方式是，无论列表是单项还是多项，“末尾插入块”命令都是执行插入一个同级、同父列表项。因为列表项的序号很好去掉，即使是新手也很好理解，这样的实现方式不会让人觉得困扰。

### Describe the candidate solution

上述讨论没有考虑这种情况，在这里“末尾插入块”就是插入一个同级段落块。
<img width="299" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/8ec109d9-9dbf-47d6-be3e-df0b8fc9f2d0">

或许在形式上更“统一”的操作是，如果列表里嵌套表格块/代码块/标题块/引用块……的话，“末尾插入块”是插入一个同级段落块？

**Comment by 88250** [comment]
你是选中列表项，然后用菜单 `末尾插入块`？

**Comment by LoneFireBlossom** [comment]
是

**Comment by LoneFireBlossom** [comment]
或者用快捷键

**Comment by 88250** [comment]
这个主要是要看选中的块，如果是菜单的话，选中的都是列表项，所以无论是否有多个子块都是插入同级列表项；如果是快捷键的话，光标虽然在子块中，但是插入的任然是同级列表项，如果是选中这个唯一子块再按快捷键，那么就是插入这个子块的同级，也就是再插入一个列表项子块。

**Comment by LoneFireBlossom** [comment]
我没看懂，所以没理解你想要表达的意思……

**Comment by 88250** [comment]
图文结合一下，使用菜单，使用快捷键：

* 使用菜单时，选中的都是列表项，所以这个列表项无论是否有多个子块都是插入同级列表项
* 使用快捷键时
  * 光标在列表项的唯一子块中，插入的是同级列表项
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/86125282-0f97-4691-b831-72a135777ac2)
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/155e8b84-97d7-40e6-a27f-6f39638ac38e)
  * 光标在列表项下多个子块中的任意一个子块中，插入的是同级子块
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/dafae987-b69f-4457-8845-c5e689c3ef76) 
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/e902947a-592c-49f2-90bf-03c3b5da7247)

**Comment by LoneFireBlossom** [comment]
我觉得开发者是不是理解错了我的意思？
这几张图都是多项列表，而我提的问题起因是单项列表

**Comment by 88250** [comment]
只有一个列表项的列表也是一样的，把这个逻辑推广一下，把列表项子块上移到列表项这一层是一致的。

**Comment by LoneFireBlossom** [comment]
示例GIF：
![CleanShot 2024-04-21 at 21 30 16](https://github.com/siyuan-note/siyuan/assets/50087596/3b765fc8-47ad-4f06-b80e-04fd47dfebaa)

**Comment by 88250** [comment]
是这个逻辑，你看我上面说的应该就理解了。

**Comment by LoneFireBlossom** [comment]
上面的GIF演示了使用菜单和使用快捷键两种方式

> 使用菜单时，选中的都是列表项，所以这个列表项无论是否有多个子块都是插入同级列表项

在GIF中，使用菜单的方式，插入的不是同级列表项，而是新的段落块啊？

> 使用快捷键时
> 光标在列表项的唯一子块中，插入的是同级列表项

在GIF中，使用快捷键的方式，插入的不是同级列表项，而是新的段落块啊？

**Comment by 5kyfkr** [comment]
> 是这个逻辑，你看我上面说的应该就理解了。

试了像下面的情况就没办法正常添加下一个列表项目了
![image](https://github.com/siyuan-note/siyuan/assets/63196026/eb996b02-48ce-40e6-ae30-d19765b99659)
而下面这个情况就可以正常添加
![image](https://github.com/siyuan-note/siyuan/assets/63196026/e00d82ff-e3d4-4cfa-ad8f-b097a68499ab)

**Comment by 88250** [comment]
@LoneFireBlossom 

> 在GIF中，使用菜单的方式，插入的不是同级列表项，而是新的段落块啊？

推广到列表这一层，插入和列表同级的块就是段落块。

> 在GIF中，使用快捷键的方式，插入的不是同级列表项，而是新的段落块啊？

同上。

---

@5kyfkr 这个是个引述块吧？选中引述块再 Ctrl+Shift+A 会插入引述块同级段落块，然后 Enter 就可以创建新的列表项了。

**Comment by 5kyfkr** [comment]
> @LoneFireBlossom
> 
> > 在GIF中，使用菜单的方式，插入的不是同级列表项，而是新的段落块啊？
> 
> 推广到列表这一层，插入和列表同级的块就是段落块。
> 
> > 在GIF中，使用快捷键的方式，插入的不是同级列表项，而是新的段落块啊？
> 
> 同上。
> 
> @5kyfkr 这个是个引述块吧？选中引述块再 Ctrl+Shift+A 会插入引述块同级段落块，然后 Enter 就可以创建新的列表项了。

这操作也太硬核了

**Comment by LoneFireBlossom** [comment]
> @5kyfkr 这个是个引述块吧？选中引述块再 Ctrl+Shift+A 会插入引述块同级段落块，然后 Enter 就可以创建新的列表项了。

现在又多了一种实现方式
不过本issue提出的目的就是“让这个操作变得更符合用户直觉”，这个实现方式也是“太深了”，不知开发者怎么看

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/a668944e-650f-4590-9602-dd421c0ec7e1)
看看这样行不行

**Comment by LoneFireBlossom** [comment]
别新添按钮了吧。只需要修改现有功能即可（所谓“奥卡姆剃刀”balabala……（

**Comment by 5kyfkr** [comment]
> 别新添按钮了吧。只需要修改现有功能即可（所谓“奥卡姆剃刀”balabala……（

这个功能直观点，鼠标不移过去也看不到，应该不会有很大影响吧

**Comment by LoneFireBlossom** [comment]
> > 别新添按钮了吧。只需要修改现有功能即可（所谓“奥卡姆剃刀”balabala……（
> 
> 这个功能直观点，鼠标不移过去也看不到，应该不会有很大影响吧

担心引入新bug

**Comment by 5kyfkr** [comment]
> 担心引入新bug

这个没辙，我看notion是列表只能放纯文本，思源过于自由其实这个功能已经算是在补bug

**Comment by 88250** [comment]
不考虑添加新按钮了，另外这个也不是设计缺陷。我认为目前这个交互设计还是挺直观的，核心逻辑就是按选中的块来，选中块以后再决定相关操作。

不选中任何块时，光标在容器块中的子块中，此时 Ctrl+Shift+A 则向上寻找子块，如果找到某一层存在多个子块，则就在这一层创建同级子块。

因为思源存在容器块，所以才会有这样的逻辑，这个逻辑其实并不复杂，但对于用户来说，比较难理解的其实是容器块本身，一旦理解容器块就比较好理解 “末尾插入块” 块了。

**Comment by LoneFireBlossom** [comment]
> @5kyfkr 这个是个引述块吧？选中引述块再 Ctrl+Shift+A 会插入引述块同级段落块，然后 Enter 就可以创建新的列表项了。

如何选中列表里嵌套的引述块/代码块/表格块？是按ESC吗？

> 不考虑添加新按钮了，另外这个也不是设计缺陷。我认为目前这个交互设计还是挺直观的，核心逻辑就是按选中的块来，选中块以后再决定相关操作。

如果「按ESC选中的是引述块/代码块/表格块」，“核心逻辑就是按选中的块来”，那为什么选中之后按ESC键删掉的是整个列表块呢？

**Comment by 88250** [comment]
> 如何选中列表里嵌套的引述块/代码块/表格块/...？是按ESC吗？

Esc 是选择当前光标所在的块，你举例里面有的是父块（比如引述块），这个需要 Shift+↑ 扩选。

> 如果「按ESC选中的是引述块/代码块/表格块/...」，“核心逻辑就是按选中的块来”，那为什么选中之后按delete键删掉的是整个列表块呢？这逻辑可不通啊。 https://github.com/siyuan-note/siyuan/issues/11085#issuecomment-2068010992

容器块里面如果没有子块了，会删除整个容器。

**Comment by 88250** [comment]
没有其他疑问的话我就关闭 issue 了，如果还有建议请继续跟帖。
