### ISSUE TITLE
查询语法and/or/not无效

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#11110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

版本3.0.10，windows

不管是用`关键字`还是`查询语法`搜索，都能搜到这个文档
![image](https://github.com/siyuan-note/siyuan/assets/97490782/33713f86-7955-493d-a9ac-20a60c4054e5)

但是如果加了`and`，两种方式都搜不到
![image](https://github.com/siyuan-note/siyuan/assets/97490782/58df8697-f3c5-4d2d-876a-d4ea26cdd735)

但是我看思源帮助文档里面写的默认就是`and`
![image](https://github.com/siyuan-note/siyuan/assets/97490782/b88b7288-1767-4ad6-b36b-1814f51d9fb9)

其他or/not语法也不生效

问题如下
1 and/or/not 不管是`关键字`模式，还是`查询语法`模式都不生效
2 and/or/not 属于最常用的语法，是只在`查询模式`下才生效吗？应该默认就生效吧
3 如果切换了查询模式，下一次打开搜索的时候不会保存上次使用的模式，是否应该保存上次使用的查询模式呢

### Expected result

正确处理and/or/not

### Version environment

```markdown
- Version: 3.0.10
- Operating System: windows
- Browser (if used):
```

### Log file

应该不用

**Comment by 88250** [comment]
> 1 and/or/not 不管是关键字模式，还是查询语法模式都不生效
> 2 and/or/not 属于最常用的语法，是只在查询模式下才生效吗？应该默认就生效吧

我这里测试是生效的，请检查是否是 搜索类型 中关闭了文档块。

![image](https://github.com/siyuan-note/siyuan/assets/873584/d6f89cbb-7700-4c6e-ad57-271050f2877c)

> 3 如果切换了查询模式，下一次打开搜索的时候不会保存上次使用的模式，是否应该保存上次使用的查询模式呢

使用 保存查询条件 即可：

![image](https://github.com/siyuan-note/siyuan/assets/873584/0e8e7fed-1a38-48c6-a523-98762e586ccc)

**Comment by Zuoqiu-Yingyi** [comment]
查询语法的关键字得用全大写的字母 `AND`, `OR` 与 `NOT`
