### ISSUE TITLE
导出时可供选择：是否导出包含的双链子文档

### ISSUE THREAD

**Issue by songshua295** [siyuan-note/siyuan#11111]
### In what scenarios do you need this feature?

场景：
1. 比如说一个笔记可能属于多个范畴，比如说《变量是什么？》可以属于《java》《python》子文档下，但是为了避免重名，只归属在了java子文档，我们将《变量是什么？》的双链作为解释放在其中一篇下面。

但是目前如果导出的话，则还需要将其移动到需要导出的目录下，非常不方便。

2. 在一个文档中，有多个双链引用，但是又需要打包发送给别人的时候，其中的双链文档又需要一个一个找，就比较麻烦。

### Describe the optimal solution

可以参考notion的是否包含子文档选项，可以放在设置里面默认，也可以在每次导出时提供弹窗选项。
![image](https://github.com/siyuan-note/siyuan/assets/65521386/0b77425e-3077-4084-bb81-3a7aedab3ea7)

**Comment by 88250** [comment]
有引用的文档会一并打包导出的。

**Comment by songshua295** [comment]
> 有引用的文档会一并打包导出的。

我自己尝试了一下，没有啊，还是说需要设置什么没？引用的文档与原文档不属于父子级的文档关系，导出只导出了包含的子文档以及自身文档。

**Comment by songshua295** [comment]
我的出发点是，作为**双链笔记，如果需要过度去组织文档关系，会强制将笔记思维转回线性的文档方式**，所以才会这么想。

**Comment by 88250** [comment]
抱歉没说清楚，是导出 .sy.zip 的时候会，导出 Markdown 不会，引用在导出 Markdown 时仅支持 设置 - 导出 - 引用 中列出的：

![image](https://github.com/siyuan-note/siyuan/assets/873584/175a8855-e175-4855-b1cd-7f8ec97b0b72)

如果是导出 PDF 或者 Word，可以 合并子文档 导出。

**Comment by 88250** [comment]
导出 Markdown 主要考虑数据迁移的场景，数据迁移时都是批量导出的，通过 设置 - 导出 - 引用 - 锚点哈希 已经能够得到完整的引用定位了。

如果是单篇导出的话就不考虑类似支持了，见谅。

**Comment by Achuan-2** [comment]
估计这个功能是希望整理的MOC列表，导出单篇文档，能导出为一个文件夹，块引的块如果为文档则会导出为markdown文件，原来的文档块引能变成markdown文件链接。
感觉这个功能还是值得做的，如果导出设置为脚注，块引的块为非文档块就依然是导出为脚注，块引的块为文档的话，则会导出markdown文件
