### ISSUE TITLE
复制出的笔记文件修改名称后不会按规则自动排序

### ISSUE THREAD

**Issue by qljiong** [siyuan-note/siyuan#11115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

笔记设置的是按名称自然降序
复制一份笔记后，修改笔记名称后，不会自动排序，
需要手动折叠展开一次父节点才能按规则排序
例如 
202404
  -- 20240405
  -- 20240406 // 复制出来的这一份，修改名称后不会按规则排序
  -- 20240403
  -- 20240402

### Expected result

复制修改名称后能自动根据排序规则排序

### Version environment

```markdown
- Version: v3.0.10
- Operating System: win10
```

**Comment by 88250** [comment]
是的，需要重新展开文档树。
