### ISSUE TITLE
remnote、anki、pdf  划词双链等

### ISSUE THREAD

**Issue by ben-1999** [siyuan-note/siyuan#1111]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
学习知识  记忆知识点 

### 描述最优的解决方案 Describe the optimal solution

我觉得anki很好用，但是缺乏组织和上下文，以及关联，知识过于碎片，复习的效率就很低，比如一个知识点很小，但是如果思源笔记就很好,可以使得有上下文的话会把一串的知识点，renmnote就是这样设置的

**Comment by 88250** [comment]
你好，请看下之前关于卡片复现相关的讨论 https://github.com/siyuan-note/siyuan/issues/676 

因为我们对这块不太了解，请描述一下你的具体设想，特别是功能细节，谢谢。

**Comment by 88250** [comment]
我们集中到卡片复习那个 issue 中讨论，谢谢。
