### ISSUE TITLE
The heading block convert doc block to preserve symbols as much as possible

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11126]
标题块转换为文档块后，标题块里的某些英文符号得不到保留

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如视频所示，可以看到很多英文符号在转换成文档块后得不到保留，只测试了一部分符号，没有全部测试

https://github.com/siyuan-note/siyuan/assets/50087596/a1b29eab-4083-4cd2-afa3-70f3ae3c215d

### Expected result

搜了一下没看到相应issue，是bug还是故意这么设置？
如果就是这么设置的话应该在帮助文档里写清楚吧，我看帮助文档里没写

### Version environment

```markdown
- Version: 3.0.11
- Operating System: macOS 13.6.6
- Browser (if used):
```

### Log file

.

**Comment by TCOTC** [comment]
这个应该是 BUG

**Comment by 88250** [comment]
这是早期（还是用文档名作为文件名的时期）实现的时候为了避免不合法的文件名而故意剔除了这些符号，现在已经可以支持（除了不能支持 `/`），稍后进行改进，感谢反馈。

**Comment by LoneFireBlossom** [comment]
> 这是早期（还是用文档名作为文件名的时期）实现的时候为了避免不合法的文件名而故意剔除了这些符号，现在已经可以支持（除了不能支持 `/`），稍后进行改进，感谢反馈。

为何不支持`/`呢

**Comment by TCOTC** [comment]
@88250 有曲线救国的方法实现支持斜杠作为标题吗？

**Comment by Temacc0531** [comment]
这个是不是需要在哪里告知一下用户，转换前提醒，或者帮助文档里面写一下，不然以为是bug了😂

**Comment by 88250** [comment]
@Temacc0531 ？

**Comment by Temacc0531** [comment]
> @Temacc0531 ？

没事了，转换的时候右上角有弹窗提示，妥
