### ISSUE TITLE
文档浮窗支持 `在当前窗口打开`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11127]
### In what scenarios do you need this feature?

目前要实现 `在当前窗口打开` ，有这两种方式：

1. Ctrl+ 鼠标左键 点击最前面的面包屑，在当前窗口打开
2. 在新窗口打开，再拖拽回当前窗口

**很不直观**

![image](https://github.com/siyuan-note/siyuan/assets/78434827/57ef06be-fcbe-4890-90d9-ba199b3ed37d)

---

[能不能在菜单里面加上 多种打开方式? - 链滴](https://ld246.com/article/1713955089471)

> 弹出窗口 无法通过拖拽到 页签或者分栏显示

### Describe the optimal solution

浮窗增加 `在当前窗口打开` 按钮

- 如果浮窗是聚焦状态，则 `在当前窗口打开` 也是聚焦状态

**Comment by TCOTC** [comment]
@Vanessa219 这个能做吗？

**Comment by Vanessa219** [comment]
加在这么？
<img width="412" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/6d49159f-f116-4027-b233-e8a17c5fbb0c">

**Comment by TCOTC** [comment]
我想做在这里：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c409b05b-60f0-477e-847b-a403584ec86a)

**Comment by Vanessa219** [comment]
浮窗中会有多个编辑器的。这样只能打开第一个。

**Comment by TCOTC** [comment]
多个编辑器的时候不是没有吗？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7876e337-46aa-445c-85a6-9b128e45aaa4)

**Comment by TCOTC** [comment]
那就同时添加在窗口顶部和菜单里吧？单个编辑器的时候很方便，多个编辑器的时候也能用

**Comment by TCOTC** [comment]
@Vanessa219 我觉得把 `使用新窗口打开` 改为 `在新窗口中打开` 会整齐一点：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/15ce4f51-e11f-4c19-9eb9-705b1636aeb8)

**Comment by wildshen** [comment]
@Vanessa219 新版本发布，浮窗增加了在新页签中打开，感觉挺好的。

不知道，是否可以把块右上角的引用数字的浮窗也这样更改。正如 @TCOTC 建议的：https://github.com/siyuan-note/siyuan/issues/11127?utm_source=ld246.com?utm_source=ld246.com#issuecomment-2131924055


当然已经有了alt+b的反链窗口，可是对于块的引用就不方便了，如果可以增加在新页签中打开就很好。
当然，问题就在于跟alt+b的反链窗口是否统一，统一的话，块引用就比较麻烦，同时显示文档全部反链还是显示块的反链。所以暂时就不统一。

总感觉这两个反链可以在优化下，然后统一起来，甚至可以数据库化。

**Comment by TCOTC** [comment]
如果能直接打开多编辑器里的每一个文档，查看反链就很方便

**Comment by Vanessa219** [comment]
有些时候会有会多个文档，打开过多也不好查看。具体看哪一个就开哪一个，有时候只是需要预览。
