### ISSUE TITLE
Entries with bookmark in the properties will taint the bookmark

### ISSUE THREAD

**Issue by TangQi001** [siyuan-note/siyuan#11128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/suka233/siyuan-knote/issues/9
The questions are as shown on the web page
![image](https://github.com/siyuan-note/siyuan/assets/67812425/a91700cf-bc76-41a4-baa3-a0bab7263803)

### Expected result

solved

### Version environment

```markdown
- Version: latest
- Operating System: windows11
- Browser (if used):
```

### Log file

no

**Comment by 88250** [comment]
请勿使用包含 bookmark 的属性名。
