### ISSUE TITLE
Feature Request | 为模板增加 `.action` 区块声明

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#11135]
### Problem statement

在模板行比较多的情况下，每一行都要写 `.action{}` 实在是太麻烦了……，像这种：

[https://ld246.com/article/1713177507282](https://ld246.com/article/1713177507282)

大几十行的模板，每行都要起手一句 `.action{}` 实在是难蚌。

以我个人的角度，最希望的是能做一个模板的宏展开。不过这个可能有点难为开发者，所以退一步：是否可以在模板解析中增加一个区块声明，使得在区块内部的所有行都会被视为被 `.action` 所包裹。

### Proposed approach

灵感来源是 vscode 中，可以通过这样的语法来自定义声明一个折叠区块：

```md
/* #region */
这部分区域可以被折叠
/* #endregion */
```

仿照这种思路，添加一个 `action` 区块声明

```md
.startaction
$x:= now
$year := now.Year
.endaction
```

golang 后端在读取到需要渲染的 sprig 之后，首先判断是否存在 `/^\.startaction$/gs` 所定义的区块

![image](https://github.com/siyuan-note/siyuan/assets/27268127/4eb46e62-388c-4323-8006-c77f88f11edf)

如果存在，就:

1. 从 `.startaction` 的下一行迭代到 `.endaction` 的上一行
2. 替换每行的字符串为 `.action(${line})`
3. 删除 `.startaction` 和 `.endaction`

然后将预处理之后的 sprig 模板继续进行解析即可。

### Exemplify

这里给一个简单的 python 实现的案例，通过这个案例可以发现实现起来也并不复杂

```py
import re


def process_sprig_text(input_text):
    # 正则表达式用于查找.startaction和.endaction之间的内容
    pattern = re.compile(r'\.startaction\n(.*?)\.endaction', re.DOTALL)

    # 查找所有符合的文本块
    matches = pattern.findall(input_text)

    # 处理每个匹配的文本块
    for match in matches:
        # 将块内的每行转换为 `.action(${line})`
        transformed_lines = [
            '.action{{ {} }}'.format(line.strip())
            for line in match.split('\n') if line.strip()
        ]
        transformed_text = '\n'.join(transformed_lines)

        # 替换原始文本中的整个块，包括.startaction和.endaction标记
        input_text = input_text.replace(
            '.startaction\n' + match + '.endaction', transformed_text
        )

    return input_text


# 示例文本
input_text = """
前面的部分，省略
下面就是区域的开始
.startaction
$week := add (mod (div ((toDate "2006-01-02" "2050-03-13").Sub now).Hours 24) 7) 1
$today := last (slice (list "星期六" "星期五" "星期四" "星期三" "星期二" "星期一" "星期天") 0 $week )
$datestr := now | date "2006-01-02"
$datestr_sy := now | date "20060102"
.endaction
到上面这行就是区域的结束

## 今日日记: .action{$datestr} .action{$today}
{: custom-dn-quickh2=".action{$datestr_sy}"}

.startaction
now | date "2006/01"
.endaction
"""

# 处理并打印结果
processed_text = process_sprig_text(input_text)
print(processed_text)
```

运行结果如下:

```py
前面的部分，省略
下面就是区域的开始
.action{ $week := add (mod (div ((toDate "2006-01-02" "2050-03-13").Sub now).Hours 24) 7) 1 }
.action{ $today := last (slice (list "星期六" "星期五" "星期四" "星期三" "星期二" "星期一" "星期天") 0 $week ) }
.action{ $datestr := now | date "2006-01-02" }
.action{ $datestr_sy := now | date "20060102" }
到上面这行就是区域的结束

## 今日日记: .action{$datestr} .action{$today}
{: custom-dn-quickh2=".action{$datestr_sy}"}

.action{ now | date "2006/01" }
```

模板也能正常渲染：

![image](https://github.com/siyuan-note/siyuan/assets/27268127/96c66fa4-45a0-4539-b474-8e1020f615a3)

**Comment by 88250** [comment]
感谢提议，但是这里还是不引入类似的变换/语法为好，改进方向应该是 https://github.com/siyuan-note/siyuan/issues/11080

**Comment by frostime** [comment]
> 感谢提议，但是这里还是不引入类似的变换/语法为好，改进方向应该是 #11080

你这 issue 半年都不一定能出来吧……

我这个实现上完全没有难度，唯一问题就是你说的污染语法问题。

但是本来我们这也不是纯 go 语法啊，早就引入了一堆方言了。加点语法糖，方便模板的编写和使用能有啥问题呢。

而且这个就是一个纯预处理阶段的特性，对语法本身侵入性也没有那么大啊。

我觉得这种技术洁癖实在没有必要，关键不应该是好用、方便用吗。

**Comment by TCOTC** [comment]
如果做了编辑器  #11080 ，好像能做个给每一行添加 .action{} 的插件跟编辑器配套用？

**Comment by TCOTC** [comment]
不过我也觉得每一行都要 .action{} 实在是超级麻烦

**Comment by frostime** [comment]
> > 感谢提议，但是这里还是不引入类似的变换/语法为好，改进方向应该是 #11080
> 
> 你这 issue 半年都不一定能出来吧……
> 
> 我这个实现上完全没有难度，唯一问题就是你说的污染语法问题。
> 
> 但是本来我们这也不是纯 go 语法啊，早就引入了一堆方言了。加点语法糖，方便模板的编写和使用能有啥问题呢。
> 
> 而且这个就是一个纯预处理阶段的特性，对语法本身侵入性也没有那么大啊。
> 
> 我觉得这种技术洁癖实在没有必要，关键不应该是好用、方便用吗。

类比一下就是，大家都可以正常用 js，但是用 ts 写起来更加顺手一点而已。

而且由于 ts 最后会被转译成 js，所以你不能说用了 ts 就是对 js 的语法污染了。

**Comment by mozhux** [comment]
我觉得也是。。既然每一行都要写.action，那跟没写有啥区别吗？默认就可以吧。

**Comment by 88250** [comment]
> 但是本来我们这也不是纯 go 语法啊，早就引入了一堆方言了。

没有方言，都是在 go 的标准模板语法支持的，如果引入自己的处理，后面恐怕会带来其他问题。

**Comment by 88250** [comment]
> 我觉得也是。。既然每一行都要写.action，那跟没写有啥区别吗？默认就可以吧。

不是每一行都需要 action 的。

**Comment by TCOTC** [comment]
> > 我觉得也是。。既然每一行都要写.action，那跟没写有啥区别吗？默认就可以吧。
> 
> 不是每一行都需要 action 的。

这样的吗？有例子吗？

**Comment by mozhux** [comment]
> 
> 没有方言，都是在 go 的标准模板语法支持的，如果引入自己的处理，后面恐怕会带来其他问题。

还是有方言的，本来人家的是{{aciton}}，比较正常， 比如{{加. 属性}} ，但为了避免思源内的语法冲突，改成了 .action{{action}}

**Comment by 88250** [comment]
> > > 我觉得也是。。既然每一行都要写.action，那跟没写有啥区别吗？默认就可以吧。
> > 
> > 
> > 不是每一行都需要 action 的。
> 
> 这样的吗？有例子吗？

.action{a}
这里不需要
.action{b}

**Comment by 88250** [comment]
> > 没有方言，都是在 go 的标准模板语法支持的，如果引入自己的处理，后面恐怕会带来其他问题。
> 
> 还是有方言的，本来人家的是{{aciton}}，比较正常， 比如{{加. 属性}} ，但为了避免思源内的语法冲突，改成了 .action{{action}}

这个不是方言，是 go 模板解析器支持的配置。

**Comment by 88250** [comment]
如果有办法在 go 模板框架下（比如通过自定义函数或者其他什么机制）实现 action 区块的话可以考虑。

**Comment by frostime** [comment]
> 如果有办法在 go 模板框架下（比如通过自定义函数或者其他什么机制）实现 action 区块的话可以考虑。

或者我再退一步，起码允许在 md 模板文件中应用这种语法如何？

md 模板肯定是有方言的——你们都加了 karmdown 属性声明的语法了，那额外加一个预处理器总可以吧。

**Comment by mozhux** [comment]
> > > 没有方言，都是在 go 的标准模板语法支持的，如果引入自己的处理，后面恐怕会带来其他问题。
> > 
> > 
> > 还是有方言的，本来人家的是{{aciton}}，比较正常， 比如{{加. 属性}} ，但为了避免思源内的语法冲突，改成了 .action{{action}}
> 
> 这个不是方言，是 go 模板解析器支持的配置。

我的意思是本来不需要额外录入的，但因为思源本身的冲突，导致用户要为这个冲突买单，每次都要写.action在前面。

**Comment by frostime** [comment]
> > 如果有办法在 go 模板框架下（比如通过自定义函数或者其他什么机制）实现 action 区块的话可以考虑。
> 
> 或者我再退一步，起码允许在 md 模板文件中应用这种语法如何？
> 
> md 模板肯定是有方言的——你们都加了 karmdown 属性声明的语法了，那额外加一个预处理器总可以吧。

而且这个预处理完全可以在前端就完成

**Comment by 88250** [comment]
如果能在前端完成的话，考虑用插件实现吧。

**Comment by 88250** [comment]
> md 模板肯定是有方言的——你们都加了 karmdown 属性声明的语法了

我没看明白，麻烦举个例子。

**Comment by 88250** [comment]
> 我的意思是本来不需要额外录入的，但因为思源本身的冲突，导致用户要为这个冲突买单，每次都要写.action在前面。

这个没有办法避免啊，不然语法有冲突。另外，这个也是通过 go 模板本身的机制实现，不是自己定义处理的，所以比较安全。引入自己的预处理我怕会引入无法解决的问题。

**Comment by frostime** [comment]
> > md 模板肯定是有方言的——你们都加了 karmdown 属性声明的语法了
> 
> 我没看明白，麻烦举个例子。

前端运行的插件没法解析 md 模板文件啊。

给你看一个目前集市里面 normal 模板的定义：

![image](https://github.com/siyuan-note/siyuan/assets/27268127/fc10fa70-257a-4e6a-9df5-ead0fe492114)

1. 一开头那些是 go 模板，由于 action 没法多行，不得不每行一个 .action
2. 后面 {{{col 还有 `{: style=""}` 的是 kmd 定义块的语法，肯定不属于 golang 吧？

那显然：
1. md 模板里 .action 写起来非常繁琐
2. md 模板里本来就不止有 go 模板语法

那我要求在 md 模板里面再加一个区块声明语法应该也不过分吧。

这个在前端就能预处理:

```ts
function processSprigText(inputText: string): string {
    // Regular expression to find text between .startaction and .endaction
    const pattern = /\.startaction(.*?)\.endaction/gs;

    // Replace the matched groups
    return inputText.replace(pattern, (match, group1) => {
        // Split the group into lines and transform each line
        const lines = group1.split('\n').filter(line => line.trim() !== '');
        const transformedLines = lines.map(line => `.action{ ${line.trim()} }`);
        return transformedLines.join('\n');
    });
}
```

**Comment by 88250** [comment]
上面说的和模板语法没有关系啊，那些是其他语法，不会在模板中处理的。你提的这个是需要改模板语法，除非有 golang 模板内置的机制，否则不建议处理。

**Comment by Zuoqiu-Yingyi** [comment]
@88250 @Vanessa219 
感觉可以参考一下嵌入块，支持一个纯前端渲染的模板模式，模板列中运行 js 代码，所需要的上下文塞入 js 的上下文中

**Comment by 88250** [comment]
这个单独开 Issue 讨论吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月25日(周四) 下午2:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] Feature Request | 为模板增加 `.action` 区块声明 (Issue #11135)




 
@88250 @Vanessa219
 感觉可以参考一下嵌入块，支持一个纯前端渲染的模板模式，模板列中运行 js 代码，所需要的上下文塞入 js 的上下文中
