### ISSUE TITLE
Refresh the doc tree after data sync generates conflicting documents

### ISSUE THREAD

**Issue by h9485910** [siyuan-note/siyuan#11137]
PC端冲突文档不能及时在文档树显示

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

本来是想测试下同步冲突了会怎么样，PC端开启了冲突后生成冲突文档，云端同步冲突后，文档树不能实时显示生成的冲突文档，重建索引后才在文档树显示

### Expected result

生成的冲突文档能够及时显示

### Screenshot or screen recording presentation

![20240425152430](https://github.com/siyuan-note/siyuan/assets/48907331/92b4e717-36ec-4e49-874f-c8c5fce64c54)

### Version environment

```markdown
- Version: 3.0.11
- Operating System: win 11
- Browser (if used):
```

### Log file

emmmm，很容易复现就不用贴日志了吧

**Comment by 88250** [comment]
这个不需要重建索引的，只需要重新展开文档树。

**Comment by h9485910** [comment]
> 这个不需要重建索引的，只需要重新展开文档树。这个不需要重建索引的，只需要重新展开文档树。这个不需要重建索引的，只需要重新展开文档树。

不能优化下直接展示吗？还需要手动操作一下感觉不够人性化，对于不了解的用户也是一个认知障碍

**Comment by 88250** [comment]
嗯，后续考虑自动刷新一下。
