### ISSUE TITLE
添加到数据库 支持通过块命名、别名搜索

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

添加到数据库，无法根据数据库别名搜索
之前版本是可以根据数据库别名搜索到数据库的

### Expected result

添加到数据库，能够根据数据库别名搜索目标数据库

### Version environment

```markdown
- Version: 3.0.11
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
“数据库别名”指的是数据库块的别名？

**Comment by Achuan-2** [comment]
是的

**Comment by 88250** [comment]
这个一直都不支持的，只能通过数据库名搜索，不支持通过块名、别名等搜索的。

**Comment by Achuan-2** [comment]
希望还是可以支持这个特性，https://github.com/siyuan-note/siyuan/issues/10875，之前有版本确实是可以的。

**Comment by 88250** [comment]
那有点奇怪了，我看代码实现没有支持过的。

**Comment by 88250** [comment]
找到代码提交历史了，以前确实是支持过，因为那时是通过数据库块搜索的，后来因为 https://github.com/siyuan-note/siyuan/issues/10934 中提议觉得搜索结果无关，所以不再通过数据库块搜索了，仅支持数据库名搜索。
