### ISSUE TITLE
在折叠块下方编辑时没有新建一个块

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#1113]
参见https://github.com/siyuan-note/siyuan/issues/1094 ，当时举的例子不是很好所以可能没表达清楚
### 描述问题 Describe the problem

现状：在折叠块后继续编辑把内容附加到被折叠的块上

### 期待的结果 Expected result
在折叠块后继续编辑应该新建一个块而不是把内容附加到被折叠的块上

### 截屏或录屏演示 Screenshot or screen recording presentation

![siyuan](https://user-images.githubusercontent.com/16791452/104797362-7288b580-57f8-11eb-8807-ee643287f6c9.gif)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by deerainw** [comment]
我看懂楼主的意思了，现在的这种包含是没问题的。标题块是一种特殊的容器块，它确实应该一直往下追溯到下一个标题块，并把这中间所有的内容块都视作属于自己的内容，所有带有标题折叠功能的编辑器都是这么处理的。

实际上上面的 gif 反映出来的真正问题是 test 标题下面的两句话反序了

**Comment by frankli998** [comment]
确实，主要是反了的问题。

**Comment by Tregyn-cc** [comment]
支持支持，这个问题比较难受

**Comment by 88250** [comment]
标题折叠在 v1.2.0 里面会有“退化”改动：不再将下方的块作为“子块”一同折叠。其实标题块在设计上也不是容器块，有的地方（比如悬浮窗）将标题下方块算作子块是做了单独处理的。需要折叠标题和下方块的话估计需要一个 Group 操作：用超级块包裹标题和下方块，然后对这个超级块进行折叠。

先关闭了，谢谢各位。
