### ISSUE TITLE
Unable to enter title immediately after creating database

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11143]
创建数据库后立刻向标题输入/粘贴文字，文字会消失

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

必须得等一会儿才能正式开始输入。
![CleanShot 2024-04-25 at 23 10 08](https://github.com/siyuan-note/siyuan/assets/50087596/1d46c4a5-52d1-4e7f-bf77-e2a45acea548)

### Expected result

.

### Version environment

```markdown
- Version: 3.0.11
- Operating System: macOS 13.6.6
- Browser (if used):
```

### Log file

.

**Comment by TCOTC** [comment]
可以复现
