### ISSUE TITLE
Improve database multi-select field sorting

### ISSUE THREAD

**Issue by zhenzou** [siyuan-note/siyuan#11146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

多字段排序不符合预期。如下截图

### Expected result

应该按照优先级排序

### Screenshot or screen recording presentation

<img width="987" alt="image" src="https://github.com/siyuan-note/siyuan/assets/7829073/03a8b790-35da-447a-88d7-01bb4df79fcc">

<img width="354" alt="image" src="https://github.com/siyuan-note/siyuan/assets/7829073/c6c016a0-10bc-4f83-9230-f227fe7e6361">
<img width="350" alt="image" src="https://github.com/siyuan-note/siyuan/assets/7829073/ba0bf211-173b-42cd-96ac-efc7de1b509c">

### Version environment

```markdown
- Version: 3.0.11
- Operating System: MacOS
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15124796/siyuan.log)

### More information

1. 3.0.10 还是好的
2. 两列都是单选
3. 看起来只按照了第一个排序列排序了

**Comment by TCOTC** [comment]
确实，我试了一下，只要排序里有单选或多选都会有问题

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dd6064a2-4b3e-4564-b1f5-f202173442f7)
