### ISSUE TITLE
Support minimize the main window after auto launch on Windows

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11145]
* https://ld246.com/article/1714094649872
* https://ld246.com/article/1710719957850
* https://ld246.com/article/1689612479723
* https://ld246.com/article/1682303242687

**Comment by wwxiaoqi** [comment]
如果将 kernel 和 siyuan 本体分阶段打开是否是更加好的选择？

kernel 开机自动后台启动，并且创建完成索引。
siyuan 本体负责连接，无需等待创建索引阶段。

**Comment by 88250** [comment]
桌面端 kernel 不能独立运行的，有个定时任务会扫描是否存在界面进程，不存在的话 kernel 会自动退出。
