### ISSUE TITLE
帮助文档快捷键页签部分的文案错误

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

帮助文档：

<img width="470" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/d48fbbf6-326e-4f5a-98b4-765e726fd036">

快捷键：

<img width="1009" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/0bb00fa3-02e2-4162-9444-3cb244eba1e7">

不是“选中第九个页签”而是“跳转到最后一个页签”。
另外两个地方文案应该统一一下，如果用跳转就都用跳转，一处用跳转另一处用选中不太好吧

文档其它部分未检查。

### Expected result

.

### Version environment

```markdown
- Version: 3.0.11
- Operating System: macOS 13.6.6
- Browser (if used):
```

### Log file

.

**Comment by LoneFireBlossom** [comment]
<img width="355" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/6cf42257-3acc-47ba-8d90-0fe9522c9969">

macOS上是`CMD+/`，这里没标明。

**Comment by 88250** [comment]
* 统一使用“跳转到”
* 修正 Ctrl+1, Ctrl+2, ..., Ctrl+9
* 增加 macOS 右键菜单

感谢反馈。

**Comment by LoneFireBlossom** [comment]
<img width="610" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/720959d2-b240-4494-9881-72e43ac6b09f">

是不是两个`ctrl+/`重复了？

**Comment by LoneFireBlossom** [comment]
右键菜单和菜单有什么不一样吗？我在macOS上用`CMD+/`，在文档树上唤起的都是右键菜单

**Comment by 88250** [comment]
有的地方估计是分左右键菜单的。

**Comment by LoneFireBlossom** [comment]
> 有的地方估计是分左右键菜单的。

没看懂……“有的地方”是指某些地区？软件的某个地方？左键菜单在哪？如果有左键菜单，那左键菜单和右键菜单的快捷键一样岂不是冲突了？

**Comment by LoneFireBlossom** [comment]
在文档树上选中多个文档，然后使用搜索/替换/间隔重复快捷键后，并不能在指定的这「多个」文档里进行搜索/替换/间隔重复。
在多选状态下没有预想效果的还有「重命名」。
建议把这些只能在选中单个文档下起作用的快捷键分离出来单独做一个表格。这样帮助文档表述更清楚。
<img width="557" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/77005e7c-7b6c-46a4-a607-5410a88404f0">

要么就是实现这种功能，即选中多个文档后可以对这些文档（及子文档）里的内容进行搜索/替换/间隔重复，新开一个issue。

**Comment by TCOTC** [comment]
> 要么就是实现这种功能，即选中多个文档后可以对这些文档（及子文档）里的内容进行搜索/替换/间隔重复，新开一个issue。

这个好，让搜索支持指定多个路径

**Comment by 88250** [comment]
> 没看懂……“有的地方”是指某些地区？软件的某个地方？左键菜单在哪（「估计」是何意？）？如果有左键菜单，那左键菜单和右键菜单的快捷键一样岂不是冲突了？

左键菜单和右键菜单是有区分的，我也记不太清楚……
