### ISSUE TITLE
打开的文档不在开启的笔记本中，「定位打开的文档」时需要提示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11149]
### In what scenarios do you need this feature?

打开一篇文档，发现点击「定位打开的文档」没有反应，想了一会才想到应该是在关闭的笔记本里

### Describe the optimal solution

如果打开的文档在关闭的笔记本中/不在开启的笔记本中，「定位打开的文档」时需要提示

**最好能提示这篇文档具体在哪个关闭的笔记本里**

### Describe the candidate solution

页签悬浮提示如果能显示笔记本就更好了（现在只能显示上级文档），

还有面包屑希望也能显示

**Comment by 88250** [comment]
正常情况下是无法打开关闭的笔记本中的文档的，需要看下如何重现，谢谢。

**Comment by TCOTC** [comment]
之前不是改进过吗？找不到 id 的话会直接在文件系统里找

**Comment by 88250** [comment]
懂了，看来是 #10772 的问题，关闭的笔记本不应该再被索引的，稍后解决。

**Comment by TCOTC** [comment]
> 懂了，看来是 #10772 的问题，关闭的笔记本不应该再被索引的，稍后解决。

那改了之后还能打开已关闭的笔记本中的文档吗？

**Comment by 88250** [comment]
不能的，否则会破坏已有的索引设计。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年4月27日(周六) 中午1:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 打开的文档不在开启的笔记本中，「定位打开的文档」时需要提示 (Issue #11149)




  
懂了，看来是 #10772 的问题，关闭的笔记本不应该再被索引的，稍后解决。
  
那改了之后还能打开已关闭的笔记本中的文档吗？

**Comment by TCOTC** [comment]
那我是不是还得单开一个 issue 「支持打开关闭的笔记本中的文档」？

有时候找不到块真的不知道是因为所在笔记本关闭了还是因为块已经删除了

**Comment by 88250** [comment]
不会支持的，这个需求违背了基础设计。


那个 issue 的目的是作为遗漏索引的兜底处理。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年4月27日(周六) 中午1:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 打开的文档不在开启的笔记本中，「定位打开的文档」时需要提示 (Issue #11149)




 
那我是不是还得单开一个 issue 「支持打开关闭的笔记本中的文档」？
 
有时候找不到块真的不知道是因为所在笔记本关闭了还是因为块已经删除了

**Comment by LoneFireBlossom** [comment]
> 不会支持的，这个需求违背了基础设计。 那个 issue 的目的是作为遗漏索引的兜底处理。
> […](#)
> ---原始邮件--- 发件人: "Jeffrey ***@***.***&gt; 发送时间: 2024年4月27日(周六) 中午1:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 打开的文档不在开启的笔记本中，「定位打开的文档」时需要提示 (Issue #11149) 那我是不是还得单开一个 issue 「支持打开关闭的笔记本中的文档」？ 有时候找不到块真的不知道是因为所在笔记本关闭了还是因为块已经删除了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

那么当提示block not found的时候有什么简便的办法确定是因为笔记在其它笔记本里，还是这个块丢失了？

**Comment by 88250** [comment]
> 那么当提示block not found的时候有什么简便的办法确定是因为笔记在其它笔记本里，还是这个块丢失了？

重建索引，完成以后再看，如果还是 block not found 那就是丢失了。

**Comment by TCOTC** [comment]
> > 那么当提示block not found的时候有什么简便的办法确定是因为笔记在其它笔记本里，还是这个块丢失了？
> 
> 重建索引，完成以后再看，如果还是 block not found 那就是丢失了。
 
意思是如果引用的块在关闭的笔记本里，不会 block not found ？

**Comment by 88250** [comment]
抱歉抱歉，最近老看错问题……

在关闭的笔记本里会 block not found 的，就算重建索引完了也会。

**Comment by LoneFireBlossom** [comment]
所以回到一开始的问题
那么当提示block not found的时候有什么简便的办法确定是因为笔记在其它笔记本里，还是这个块丢失了？

**Comment by TCOTC** [comment]
除了索引已关闭的笔记本，我估计没有别的办法。但如果索引已关闭的笔记本，这个「关闭」就好像脱裤子放屁

**Comment by TCOTC** [comment]
虚拟引用好像是缓存了？

> 关闭A笔记本，在B笔记本里思源笔记文字会显示虚拟引用，鼠标移上去会提示block not found。

@88250 试试？

**Comment by 88250** [comment]
> 关闭A笔记本，在B笔记本里思源笔记文字会显示虚拟引用，鼠标移上去会提示block not found。

这个问题稍后改进，谢谢。

**Comment by Hug-Zephyr** [comment]
A笔记本里面的块, 引用了B笔记本(被关闭了)里面的块, 点击引用 无法跳转, 提示 `未找到块id为xxx的内容块`
无法跳转可以理解, 因为被关闭了. 

但是: 是不是应该区分一下这种无法跳转的, 是真的没了, 还是笔记本关闭了
因为这两种场景的处理方式应该是完全不一样的, 
@88250

**Comment by 88250** [comment]
没有区别的办法，因为都是没有找到索引。

**Comment by Hug-Zephyr** [comment]
> 没有区别的办法，因为都是没有找到索引。

那是否应该提示一下, 可能是关闭笔记本导致的
比如: `未找到块id为xxx的内容块, 检查源块被删除/笔记本被关闭`

**Comment by 88250** [comment]
通过在文件系统上搜索可以区分是真的数据不存在还是索引不存在，等会我改一下试试。

关联 https://github.com/siyuan-note/siyuan/issues/16850
