### ISSUE TITLE
数据历史支持复制 ID / 文件名、支持打开本地目录

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11151]
### In what scenarios do you need this feature?

有时候会需要拿 ID 在文件系统里直接搜索

### Describe the optimal solution

数据历史支持复制文档或笔记本的 ID

**Comment by 88250** [comment]
这个怕是直接支持复制 history 路径更好一点？

![image](https://github.com/siyuan-note/siyuan/assets/873584/9cf5ebed-7f79-4d2e-8d41-00d50caf356c)

**Comment by TCOTC** [comment]
除了要找删除的文档这种情况，还有找更新的文档之类的文件不在 history 的情况。

干脆 ID 和路径都提供

**Comment by 88250** [comment]
感觉放在上面红框位置不大妥，有建议吗？

**Comment by TCOTC** [comment]
右键菜单吧，右键菜单啥都能塞

---

> 干脆复制 ID 和路径都分别提供

两个功能：

1. 复制文件 ID
2. 直接打开本地路径并选中对应的文件

**Comment by TCOTC** [comment]
补充一条：文件夹右键菜单支持 复制文件夹名称 & 打开文件夹

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2b65afc8-6e97-4256-bafe-f472b289220e)

**Comment by Vanessa219** [comment]
为什么没法一个个回滚？这个不是应该完善历史的回滚功能么？

**Comment by TCOTC** [comment]
当时那个情况是一个个回滚至少1小时起步，所以才“没法一个个回滚”

**Comment by 88250** [comment]
考虑了下，这个功能还是不加了，文件系统上的操作还是用户自己手动来吧。

**Comment by TCOTC** [comment]
就是没法手动来才要加的

**Comment by 88250** [comment]
按照日期就可以找到对应文件了

**Comment by TCOTC** [comment]
这三个已经是我考虑的最低的要求了：

> 1. 复制文档 ID
> 2. 复制资源文件的文件名（包括文件拓展名部分）
> 3. 直接打开本地路径并选中对应的文件

**Comment by 88250** [comment]
实在要加的话我认为只加这个吧

直接打开本地路径并选中对应的文件

**Comment by TCOTC** [comment]
三个场景：

1. 需要获取文档 id 后在思源内搜索 → 复制文档 ID
2. 需要获取资源文件名在整个文件系统中搜索 → 复制资源文件的文件名（包括文件拓展名部分）
3. 需要直接获取特定的某个历史文件 → 直接打开本地路径并选中对应的文件

**Comment by 88250** [comment]
只加最后一个就可以了，在文件系统上能找到前两个。

**Comment by TCOTC** [comment]
那伺服和Docker能这样操作吗？

**Comment by 88250** [comment]
不能，所以我建议是都不要加，和文件系统相关的操作尽量避免。

**Comment by 88250** [comment]
看看能不能通过插件解决吧，本体不考虑了。

**Comment by TCOTC** [comment]
那就改为：支持复制文档 id / 资源文件名（包含拓展名）

用户需要在文件系统里找的话就靠系统自带的搜索功能

**Comment by 88250** [comment]
等需求多了再看看。
