### ISSUE TITLE
Use `<sup>`/`<sub>` for Markdown exporting superscript/subscript

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11152]
上下标样式导出使用`<sup>`和`<sub>`语法

### In what scenarios do you need this feature?
相关isssue：https://github.com/siyuan-note/siyuan/issues/11141
希望思源笔记把上标和下标样式的输出改为 `<sup>`和 `<sub>`。
**原因**
- 虽然 Markdown 没有统一标准，各家都有各家方言，但是 Github 的 Markdown 语法在一定程度上是可以看作规范的，GFM 上标和下标语法就为  `<sup>`和 `<sub>`，而不是^和~，思源笔记的上标和下标样式直接粘贴到 GitHub 是失效的

- 导出 Markdown 的 上标和下标语法改为 `<sup>`和 `<sub>`，大部分主流 Markdown 编辑器都是支持 html 标签解析的，适用性更广

**对我接触到的支持Markdown语法的软件和网站进行上下标语法测试**

| 上下标语法支持✅❌ | 是否支持`<sub>`和`<sup>`语法       | 是否支持`^`和`~`语法                                   |
| -------------------- | ---------------------- | -------------------------------------------------- |
| Github             | 支持                 | 不支持，`~`包裹的文字会识别为下划线                 |
| Typora             | 支持                 | 可以配置是否支持                                 |
| VSCode Markdown    | 支持                 | 默认不支持，需要装Markdown Preview Enhance等插件 |
| Obsidian           | 支持                 | 默认不支持，不了解插件能否支持                   |
| Hexo               | 支持                 | 默认不支持，需要主题或插件支持                   |
| CSDN               | 支持                 | 支持                                             |
| 语雀               | 支持导入，不支持输入 | 支持导入、支持输入                               |
| 简书               | 支持                 | 支持                                             |
| 纯纯写作           | 支持                 | 不支持                                           |
| 简书               | 支持                 | 支持                                             |
| 博客园             | 支持                 | 支持                                             |
| 知乎               | 不支持               | 不支持                                           |
| notion             | 不支持               | 不支持                                           |
| flowus             | 不支持               | 不支持，`~`包裹的文字会识别为下划线                 |
| wolai              | 不支持               | 不支持，`~`包裹的文字会识别为下划线                 |

**测试结果**
- 在本次测试中，支持上下标语法的软件和网站一定支持`<sub>`和`<sup>`语法，但不一定支持`^`和`~`语法
- Github、flowus、wolai会把`~`语法识别为下划线语法
- 一些网站不支持上下标语法，知乎还会把`<sub>`和`<sup>`标签清除，不会把`^`和`~`清除。

### Describe the optimal solution

- 导出Markdown时，将上下标样式改为`<sup>`和`<sub>`语法
- 兼容`<sup>`和`<sub>`上下标语法的输入，便于Markdown格式的直接粘贴
- 复制Markdown时，上下标样式改为`<sup>`和`<sub>`语法，便于内容粘贴到Github等网站

### Describe the candidate solution

无

**Comment by 88250** [comment]
> 兼容<sup>和<sub>上下标语法的输入，便于Markdown格式的直接粘贴

这个暂时不考虑了，需要继续收集需求，谢谢。

**Comment by Achuan-2** [comment]
> 这个暂时不考虑了，需要继续收集需求，谢谢。
@88250 好的，暂时不着急，不过其实思源的键盘样式<kbd>、下划线样式<u>都是html标签，兼容<sup>和<sub>输入也应该是一件理应正常的事情。
