### ISSUE TITLE
The ability about DailyNote in embed block search panel.

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#11155]
### In what scenarios do you need this feature?

1. 在今日日记中创建未来的 DailyNote
2. 链接以往的 DailyNote

### Describe the optimal solution

在嵌入块搜索面板中，增加对 DailyNote 的支持。

1. 增加对 `custom-dailynote-[date]` 属性值的支持，并提高搜索结果的优先级。
2. 增加 【新增日记 yyyy-MM-DD】的选项。

### Other information

目前思源笔记没有办法快速链接到未来的 DailyNote。

在 Logseq 中，可以通过 [[2024-04-29]] 的方式，将内容链接到未来的日记中。目前的思源没办法这样做。

不过由于之前的调整，日记都增加了 `custom-dailynote-[date]` 的自定义属性。

那么是否可以考虑，在嵌入块搜索的列表中，增加对 DailyNote 的支持。

首先是，输入 `[[20240425(一个过去的日期)` ，能够在搜索列表中，展示出对应的 DailyNote。

目前思源的搜索结果中，DailyNote 的优先级并不高，具体表现是，下图中，没有直接展示出 0425 这篇 DN。

<img width="524" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/8056fc83-50c8-4b0d-bf8c-27b29318d4f2">

其次是，输入 `[[20240429(一个未来的日期)` ，能够在搜索列表中，直接创建未来的 DailyNote。

目前的思源，没办法直接创建未来的 DN，下图中的新建文档，依旧是创建文档的逻辑。

**希望在搜索结果中新增【新建日记 2024-04-29】这样的选项。**

<img width="687" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/446f3cf1-bd0a-4851-a56a-7342d7cab3db">

---

以上内容，作为引子。因为在交互上似乎还有可以优化的地方。

比如【新建日记】这里，如果是 `[[20240429` 这样满足未来 DailyNote 的 value，甚至可以考虑只留下 【新建日记】，而不用保留【新建文档】，这样交互上也更简洁。

**Comment by frostime** [comment]
关于创建未来的日记文档的一点简单提议：

1. 创建后，将 created 属性设置为未来那一天的 0 点，而非目前的真实时间
2. 默认设置文档隐藏属性，不在文档树中显示
3. 等当日调用 `createDailyNote` 的时候，将文档的隐藏属性去掉

**Comment by LoneFireBlossom** [comment]
logseq链接未来的dailynote，是用斜杠`/date`命令，而不是输入指定日期吧？这方面思源也可以自行实现，或者用插件实现。
<img width="1162" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/801e5c8e-a4e8-44a4-91fd-41082893a9d0">

**Comment by 88250** [comment]
* 搜索优先级就不调整了，否则会影响非 dn 用法的用户
* 创建未来日记应该可以通过插件实现，原生不考虑了

感谢提议。
