### ISSUE TITLE
文档树增加一个功能

### ISSUE THREAD

**Issue by honmashironeko** [siyuan-note/siyuan#11153]
### In what scenarios do you need this feature?

在文档树的地方增加建立一个笔记本下多个笔记本，比如主文件：项目，下一级：XXX公司，下下一级：系统.txt

### Describe the optimal solution

修改为一个大文件夹下包含多个笔记本，增加新建文件夹而不是子文档。

**Comment by 88250** [comment]
抱歉，笔记本无法支持嵌套。
