### ISSUE TITLE
When multiple files are selected in the file tree, "Open" is added to the right-click menu

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11150]
### In what scenarios do you need this feature?

目前在文档树上选中多个文档时的右键菜单如下：
<img width="561" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/f772d97a-6e04-4c68-a4db-9bb26e297dfe">

此时明明可以通过`Enter`快捷键执行「打开所有选中的文档」的命令，但是右键菜单里没有。
<img width="531" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/0ea18c74-6de0-41e8-b775-01a591b307d6">

### Describe the optimal solution

按照常理来讲，快捷键能执行的功能用菜单也应该能执行才对吧。
至少应该在菜单里加上「打开」这个功能。

### Describe the candidate solution

甚至可以考虑进一步加上完整的打开功能（即下图中某些功能也可以加上）。
<img width="414" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/bc931049-7fc8-484c-9e89-4d29abf69779">

**Comment by TCOTC** [comment]
支持

**Comment by Vanessa219** [comment]
选中单个文档的时候右键菜单是没有  enter 打开这一项的。因此多个也就没有加入。

如果加入的话可能选中单个也需要加入，这样就会显得重复了。

**Comment by LoneFireBlossom** [comment]
> 选中单个文档的时候右键菜单是没有 enter 打开这一项的。因此多个也就没有加入。

没理解，这不是有打开么（就是下图的「在右侧页签打开」）
<img width="414" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/bc931049-7fc8-484c-9e89-4d29abf69779">

**Comment by TCOTC** [comment]
@Vanessa219 跟 Enter 应该没有什么关系，需求是“多选右键菜单增加「打开」”

**Comment by Vanessa219** [comment]
这些都不是直接打开，没有点击打开这一项。

**Comment by Vanessa219** [comment]
@TCOTC 要一致

**Comment by Vanessa219** [comment]
直接点击这个不论在选中一个文档，还是选中多个文档弹出的菜单里面都没有这一项。看了下 IDE ，wolai 也没有这一项。感觉可以不用添加。

**Comment by TCOTC** [comment]
> 直接点击这个不论在选中一个文档，还是选中多个文档弹出的菜单里面都没有这一项。看了下 IDE ，wolai 也没有这一项。感觉可以不用添加。

选中一个文档的时候不是有吗？
