### ISSUE TITLE
Supports quickly inserting the end sub-item in a folded list item through `Alt+Enter`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11164]
https://liuyun.io/article/1714165103251

**Comment by TCOTC** [comment]
这个是新功能吗？用户指南是不是也要加一下

**Comment by 88250** [comment]
是新功能，稍后补充用户指南。

**Comment by Vanessa219** [comment]
> 这个是新功能吗？用户指南是不是也要加一下

可以帮忙补充一下么？ 🙏

**Comment by TCOTC** [comment]
这个功能我也没用过，@88250 来写吧

**Comment by 88250** [comment]
已经补充，用户指南 - 快捷键 - 点击/拖拽时使用辅助键 - 列表

**Comment by FranciscoBarros** [comment]
I'm not sure whether I should post the comment here or on the forum (https://liuyun.io/). Please let me know if I should have commented on the forum.

There are two observations/comments/suggestions

1) What do you think? Wouldn't it be interesting to have a configuration in which the user could indicate whether the block to be inserted will be the first or last among the existing children?

2) This new shortcut could be changed to also work if the block does not yet have any children. Yes? No? This would result in uniformity.

**Comment by 88250** [comment]
@FranciscoBarros 

Hello, we can also discuss it here.

1. To insert the first block, you can press Enter directly
2. This shortcut key can be used for folded or non-folded blocks, and there seems to be no consistency problem
