### ISSUE TITLE
导出功能添加「是否将链接导出为脚注」

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11169]
### In what scenarios do you need this feature?

目前微信公众号的规则是普通订阅号无法使用外链，超链接只能引用微信文章。
所以希望思源能对微信公众号的导出进行改进

另外这个也可以不仅仅针对微信公众号，也可以用于其他不支持超链接的平台，此外也可以用于导出图片（因为图片无法看超链接的具体链接），增强思源笔记导出多平台的能力

### Describe the optimal solution

不仅仅针对微信公众号，而是直接在「设置-导出」添加一个选项，是否将超链接导出为脚注，能作用到预览模式的复制和导出图片上。
这个方案不必检测链接是否来源于微信，对超链接进行统一处理。
注意事项
- 需要考虑和块引导出的脚注兼容。
- 如果超链接的链接和标题一样则不转化为脚注。

此外，如果链接能导出为脚注，就会多出一个用法，用链接来实现文献引用导出为脚注，链接的link不一定是超链接，而可以是引用的出处了。

### Describe the candidate solution

仅适配微信平台
1. 检测链接是否为 `https://mp.weixin.qq.com` 开头，如果不为则将超链接转换为脚注
2. 超链接转换为脚注需要考虑是否有链接多次出现，即需要对脚注进行去重

下面是一个可以将Markdown转微信公众号文章的网站的效果：https://doocs.github.io/md/
![Clip_2024-04-27_17-37-30](https://github.com/siyuan-note/siyuan/assets/60436214/176c4be3-16fd-4ee5-a0e2-bd6530267227)

![Clip_2024-04-27_17-18-39](https://github.com/siyuan-note/siyuan/assets/60436214/8f5e8193-331f-4ea1-a129-4807fd512e07)

**Comment by wwxiaoqi** [comment]
扩展：【备注】也已脚注的形式导出。

**Comment by Achuan-2** [comment]
> 扩展：【备注】也已脚注的形式导出。

老早就提过了，被否了：https://github.com/siyuan-note/siyuan/issues/6195

**Comment by 88250** [comment]
抱歉，不考虑添加了，如果需要的话，请在 Markdown 基础上自行再处理。

**Comment by Achuan-2** [comment]
思源笔记要发微信公众号，链接可以变为markdown源码样式
发了帖子进行处理了
https://ld246.com/article/1731553411638
