### ISSUE TITLE
新建文档时会高亮首行

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11160]
目前新建文档时会高亮一会首行，搞得我总感觉焦点是在首行而不是标题：

![文档](https://github.com/siyuan-note/siyuan/assets/78434827/d3189920-d19f-47d7-b060-6bb89927bc63)

---

新建文档时高亮首行是特意设计的吗？

**Comment by Achuan-2** [comment]
而且会有一个方框闪一下

**Comment by TCOTC** [comment]
> 而且会有一个方框闪现一下

@Vanessa219 这个问题还没解决

**Comment by 88250** [comment]
@TCOTC 是不是没有强制刷新？ dev 版需要强制刷新一下。

**Comment by TCOTC** [comment]
@Achuan-2 你用的是 dev 版吗？

**Comment by Achuan-2** [comment]
> @Achuan-2 你用的是 dev 版吗？

是的，用的是dev版本，依然有这个问题。
@88250 强制刷新指的是开发者工具按ctrl+f5吗，刷新过了依然有这个问题

**Comment by 88250** [comment]
打开开发者工具，禁用缓存然后 Ctrl+F5

**Comment by Achuan-2** [comment]
没有改进哦，说的是新建文档的一瞬间有一个方框
![Clip_2024-04-29_15-51-00](https://github.com/siyuan-note/siyuan/assets/60436214/50c7bea3-5139-4f6a-abd9-2dfe501fc9f7)

**Comment by 88250** [comment]
@Achuan-2 截图上看不出问题哦

**Comment by Achuan-2** [comment]
> @Achuan-2 截图上看不出问题哦

新建的一瞬间会有一个黑色方框闪现
![Clip_2024-04-29_15-54-06](https://github.com/siyuan-note/siyuan/assets/60436214/7ef03194-d79c-4d47-895f-27c2d0e09d45)
然后才出现标题
![Clip_2024-04-29_15-54-25](https://github.com/siyuan-note/siyuan/assets/60436214/18e195ff-e91a-48b0-8d22-104cf96d1ded)
是想要把这个黑色边框去掉

**Comment by 88250** [comment]
哦哦，懂了 @Vanessa219

**Comment by Vanessa219** [comment]
25ad5c0f4dd967ec8aa9754c1e7f12fe6a494d14

**Comment by andyer1511** [comment]
现在新建文档和打开文档都不会高亮第一个块，但是浮窗打开还是会高亮第一个块。
可否把浮窗打开高亮第一个块的功能也去掉。这样打开文档的视觉更统一。 @Vanessa219

**Comment by TCOTC** [comment]
> 现在新建文档和打开文档都不会高亮第一个块，但是浮窗打开还是会高亮第一个块。

确实是
