### ISSUE TITLE
Gutter tip prompt shortcut keys do not follow settings

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11161]
### In what scenarios do you need this feature?

比如我这样设置快捷键：
<img width="564" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/a55383c3-a62e-4c98-ad64-ad422539b00a">

这样设置后，在这里显示的依然是原来的快捷键：
<img width="356" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/113c764e-8895-48e9-b8e6-cd340ae257a6">

其它功能其它地方未做测试。

### Describe the optimal solution

.

**Comment by Vanessa219** [comment]
刷新后正常么？
<img width="1076" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/cd04a0b8-c5ad-48ae-a7f4-794aee032b65">

**Comment by LoneFireBlossom** [comment]
> 刷新后正常么？ <img alt="image" width="1076" src="https://private-user-images.githubusercontent.com/970828/326147474-cd04a0b8-c5ad-48ae-a7f4-794aee032b65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODg2MDgsIm5iZiI6MTcxNDE4ODMwOCwicGF0aCI6Ii85NzA4MjgvMzI2MTQ3NDc0LWNkMDRhMGI4LWM1YWQtNDhhZS1hN2Y0LTc5NGFlZTAzMmI2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMzI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWFjMjYwZWM5YTYxMzExNTMxNzQ0NjY3MTZlMmViYzIyZGVjZmY0NGU5OTNhNTUzM2M3ZDJiOTMzNDRjYzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gOWzdScB7nogW2PDrpVbkmbWkVQY415E_eI0mb_-xNU">

额，这快捷键我都改了好几周了，只是现在才注意到这个问题

**Comment by LoneFireBlossom** [comment]
这个没改全，我是macOS，结果显示的是windows的快捷键（如图中Ctrl+Click应该是CMD+Click）
<img width="257" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/de81d562-40ad-483e-84a4-6d9b40890434">
