### ISSUE TITLE
上传题头图按钮的鼠标光标样式应该是个抓手

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11176]
目前是箭头：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d1585016-7de9-4331-bd11-4230b851d4b1)

应该是抓手：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6e151797-8b68-45d3-a42a-9723f396a0e8)

**Comment by wwxiaoqi** [comment]
### **我认为这个游标满足 Windows 的设计范式。无需更改，理由如下：**

### 理由
在软件官方给出的[鼠标和指针一节](https://learn.microsoft.com/zh-cn/windows/win32/uxguide/inter-mouse)中，赋予了游标如下定义：
![152358186991482e469a037](https://github.com/siyuan-note/siyuan/assets/52415314/4471b01c-24c8-4999-b44b-b67cd235adcf)
| 形状序号 | 含义                                                         |
| -------- | ------------------------------------------------------------ |
| 1        | 标准选择形状                                                 |
| 7        | 单击帮助按钮后变成的形状                                     |
| 5        | 表示 Windows 系统正在后台操作                                 |
| 4        | 系统正处于忙碌状态，需要等待片刻                             |
| 9        | 在文档编辑区中显示此形状，表示可在此处输入文本内容           |
| 12/14    | 指针位于窗口的 4 条边上时显示的形状，拖动鼠标可改变窗口的高度或者宽度 |
| 11/15    | 指针位于窗口的 4 个角上时显示的形状，拖动鼠标可同时改变窗口的高度和宽度 |
| 8/10     | 表示鼠标指针指向的位置是一个超级链接                         |
| 6        | 在移动对象时指针的形状                                       |
| 16/17/18 | 表示鼠标指针所指的按钮或某些功能不能使用                     |
| 13       | 表示此时处于手写状态                                         |

按照目前的显示状态来说，是符合 Windows 的设计范式的。
考虑到此套方案已沿用多年，建议还是保留原有方案。

### 参考链接
[微软文档-Windows 7 鼠标和指针](https://learn.microsoft.com/zh-cn/windows/win32/uxguide/inter-mouse)
[微软文档-鼠标交互](https://learn.microsoft.com/zh-cn/windows/apps/design/input/mouse-interactions#cursors)
[百度经验-鼠标指针的15种状态的不同含义，鼠标方案的变更](https://jingyan.baidu.com/article/6b97984db8cc921ca2b0bf01.html)
[百度百家号-14 种不同类型的光标/鼠标指针及其名称](https://baijiahao.baidu.com/s?id=1777268624071137414)

**Comment by Vanessa219** [comment]
好专业，那就先不进行修改了。

**Comment by TCOTC** [comment]
> 好专业，那就先不进行修改了。

@Vanessa219 不对，还是要改。我改了一下 issue 的描述

**Comment by TCOTC** [comment]
好像还是不对，真要改的话整个界面的都要改了

**Comment by TCOTC** [comment]
改「上传」的话只用改一处，改其他地方的话至少要改几十处了

**Comment by TCOTC** [comment]
@wwxiaoqi 我粗略看了一下， Notion 、飞书和 GitHub 都没有遵守这个规范，所有按钮都是抓手的形状

**Comment by wwxiaoqi** [comment]
> @wwxiaoqi 我粗略看了一下， Notion 、飞书和 GitHub 都没有遵守这个规范，所有按钮都是抓手的形状

显示抓手应该是浏览器识别到这是个 URL 了。
如果此处其他位置全部都是抓手，只有上传是光标的话，那么统一了貌似是更加好的选择

**Comment by TCOTC** [comment]
> > @wwxiaoqi 我粗略看了一下， Notion 、飞书和 GitHub 都没有遵守这个规范，所有按钮都是抓手的形状
> 
> 显示抓手应该是浏览器识别到这是个 URL 了。 如果此处其他位置全部都是抓手，只有上传是光标的话，那么统一了貌似是更加好的选择

这个大概不是 URL：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2f656f91-0ce4-44ab-9571-156e75c365cf)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6fa717aa-0ab0-44ee-9e98-4d3c4c3d2c03)

**Comment by wwxiaoqi** [comment]
@TCOTC 我看了下 Blink（Chromium）、Webkit（Safari）、Gecko（Firefox） 这几个内核的代表浏览器，发现它们在 PC 上的操作逻辑均是将 HTML 的可点击元素识别为【抓手】。至于为什么这么做我没有在互联网上找到答案。

大家都这样操作，那么思源中，这个的显示就有点问题了：
1. 光标样式未统一
2. 如果距离【抓手】太近光标不会变成【标准选择形状】

![Animation](https://github.com/siyuan-note/siyuan/assets/52415314/3d88de58-5bbb-41ac-98f8-20b38353be49)

**Comment by TCOTC** [comment]
@wwxiaoqi 是这个的问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7db6651e-a17b-47a9-a658-a534c7439f5a)

**Comment by Vanessa219** [comment]
好的，下个版本改进

**Comment by wwxiaoqi** [comment]
> @wwxiaoqi 我提 issue 的时候就看过了，感觉应该是这个的问题：

@TCOTC  是的，是这里的问题。估计是 input 最开始设置的 cursor: pointer; （指定光标：手）被上层的 css 或者 js 覆盖了。
另外这里的 input 在第一个版本中就已经有了，所以无法知道这里设置的目的是什么了

**Comment by TCOTC** [comment]
@Vanessa219 在 dev4 里，「上传」的 tip 没了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b879648a-f790-4287-bc46-bd9afa7f023a)
