### ISSUE TITLE
Only the first embed block can be searched

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#11170]
当文档中有多个嵌入块时，只有第一个可以被搜索到

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

问题：当文档中有多个嵌入块时，只有第一个可以被搜索到（已通过创建新的工作空间测试）

### Expected result

都可以被搜索到

### Version environment

```markdown
- Version: v3.0.12-dev3
- Operating System: Windows 24H2
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请打包上传一下测试的工作空间。

**Comment by shuojie819** [comment]
设置里导出了一份
[测试库-20240427174934.zip](https://github.com/siyuan-note/siyuan/files/15137771/-20240427174934.zip)

**Comment by 88250** [comment]
感谢提供测试数据集，已经定位到问题，下个版本修复。
