### ISSUE TITLE
Improve inline formula input

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11175]
改进在 $$ 之间输入与粘贴（行级公式）

一、在 \$\$ 之间**输入**行级公式时，会吞掉首个字符：

![gongshi](https://github.com/siyuan-note/siyuan/assets/78434827/57cdd2a3-157c-466c-a8e3-b620f24af63e)

二、在 \$\$ 之间**粘贴**行级公式时，页面会滚到开头（焦点移动到了第一个块）：

![gongshi2](https://github.com/siyuan-note/siyuan/assets/78434827/98f3ad4a-c083-4e8f-bc64-ea50a148c615)

[在 $$ 之间输入公式会自动跳转到文章开头 - 链滴](https://ld246.com/article/1714295826470)

**Comment by Vanessa219** [comment]
第一个问题是由于弹出公式时输入框是全选状态，再输入就会被替换。

**Comment by Vanessa219** [comment]
这个代码上不好判断，特殊情况先缓缓。
