### ISSUE TITLE
Data History - File history - Assets search results and operation conditions do not match

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11171]
数据历史里的 clean 是空的

我刚刚发现我数据历史里的 clean 是空的（重建历史索引之后）：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e8349ff2-bed9-4185-856b-a25289bb56ff)

但本地是有的（里面都是清理的图片）：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c745826c-7833-4b14-8905-d4fe30144728)

我疑惑了

**Comment by 88250** [comment]
看了下，是因为只有资源存在清理操作，文档没有清理操作。

![image](https://github.com/siyuan-note/siyuan/assets/873584/d07a9acf-e31e-451a-aab1-72965332c9a1)

估计得把 清理 从操作列表中去掉。

**Comment by TCOTC** [comment]
加个「所有」就方便了（包含文档名、内容、资源）：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f88d33d1-d619-4493-a22d-a7e368042b1d)

**Comment by TCOTC** [comment]
还有个问题是选择「资源」之后右边是无法操作的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d947dcac-4903-442a-a509-3a71a72573b5)

**Comment by 88250** [comment]
资源和文档目前没法混在一起，所以才区分了的。资源只有一个 清理 操作，所以这里显示禁用。

**Comment by TCOTC** [comment]
> 资源只有一个 清理 操作

不止，你可以看一下

**Comment by TCOTC** [comment]
不对，好像还是 BUG

**Comment by 88250** [comment]
哦，对，不好意思，我忽略了资源也可以更新同步了，确实会有多种操作的。

**Comment by TCOTC** [comment]
1. 「文档名」「文档名和内容」：菜单中移除 清理
2. 「资源」：菜单中只保留 清理 更新 同步，并且菜单允许操作

**Comment by 88250** [comment]
对，我也是这样想的，等 @Vanessa219 改一下。

**Comment by TCOTC** [comment]
3. 在「文档名」「文档名和内容」与「资源」之间切换时，菜单选项重置为 所有操作 ，以避免出现「资源」- 排版 删除 替换 大纲

**Comment by 88250** [comment]
只要切换类型，就重置为 所有操作 吧。

**Comment by TCOTC** [comment]
> 只要切换类型，就重置为 所有操作 吧。

在「文档名」与「文档名和内容」之间切换时不需要重置

**Comment by 88250** [comment]
好的，等会我给 V 说一下。

**Comment by 88250** [comment]
资源文件目前没有实现更新记录，把 update 操作去掉吧。

关联 https://github.com/siyuan-note/siyuan/issues/11177

**Comment by TCOTC** [comment]
@88250 我有点好奇资源「同步」的是什么东西？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6cb340bb-ec0f-4d13-87b4-0a77418c6ec0)

**Comment by 88250** [comment]
应该是不同设备上 OCR 结果不同产生的。

**Comment by TCOTC** [comment]
但是我只用一个设备

**Comment by 88250** [comment]
感谢反馈，我看看，稍后处理。

**Comment by 88250** [comment]
感觉有点不对，没有启用 OCR 的话不会生成这个文件的，在内核启动后的日志中搜索 `tesseract-ocr` 看看。

**Comment by TCOTC** [comment]
> 在内核启动后的日志中搜索 `tesseract-ocr` 看看。

没有搜索到这个文本

**Comment by TCOTC** [comment]
> 感觉有点不对，没有启用 OCR 的话不会生成这个文件的

话说 OCR 功能是不是没有开关？

**Comment by 88250** [comment]
设置环境变量 `SIYUAN_TESSERACT_ENABLED=false` 可以关闭 OCR

**Comment by TCOTC** [comment]
那意思是 OCR 默认开启？

**Comment by TCOTC** [comment]
另外，用户指南这里还多了一个字：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6da132b3-7540-48af-937c-6dca43e54b07)

**Comment by 88250** [comment]
系统如果安装了 tesseract（在 $PATH 上，也就是可以直接在命令行中使用 `tesseract`），则默认开启，启动日志中会打印：

```
I 2024/04/29 11:30:43 tesseract.go:187: tesseract-ocr enabled [ver=v5.3.3.20231005, maxSize=2 MB, langs=chi_sim+chi_sim_vert+eng+osd]
```

如果 tesseract 命令不可用的话不会打印这句，OCR 也不应该会被启用。

帮助文档稍后改，多谢。

**Comment by TCOTC** [comment]
@88250 我看了一下，文件是逐渐变大的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ac5c15c6-985a-4387-9443-3f057f6c3fde)

我找了朋友的思源看看，也跟我一样会生成一个 `工作空间/data/assets/ocr-texts.json`

我感觉应该是只要添加了图片就会更新 ocr-texts.json 这个文件

**Comment by Temacc0531** [comment]
我自己没有安装也有`ocr-texts.json`这个文件

**Comment by 88250** [comment]
> 如果是这样的话，没开启 OCR 时不应该更新 ocr-texts.json

稍后调整，感谢反馈。
