### ISSUE TITLE
为不同类型的块单独提供折叠后的样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11178]
### In what scenarios do you need this feature?

所有的块都能折叠，但除了列表以外，其他的块折叠之后都巨丑

### Describe the optimal solution

为不同类型的块单独提供折叠后的样式

### Other information

目前只是记录一下需求，具体细节之后再说

[数据库折叠后內容显示过少 - JeffreyChen 的回帖 - 链滴](https://ld246.com/article/1714293407621/comment/1714293959303#comments)

**Comment by 88250** [comment]
考虑用自定义 CSS/插件支持吧。
