### ISSUE TITLE
Support graphviz responsiveness

### ISSUE THREAD

**Issue by bie-zheng** [siyuan-note/siyuan#11181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

graphviz生成图片无法等比例缩小

在宽度不够的情况下，导出的图片也是残缺的
![image](https://github.com/siyuan-note/siyuan/assets/99402968/c7f3afe2-c53d-4849-8981-670c05f76ece)

关联[滴链](https://ld246.com/article/1714067691178/comment/1714324520352#comments)

### Expected result

宽度自适应编辑器宽度。
如果图片过大，能够在思源内查看大图，拖动和局部放大。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/99402968/6346530f-d444-4f5f-9ddd-11a3e11124bd

### Version environment

```markdown
- Version: 3.0.11
- Operating System: win11
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15144817/siyuan.log)

**Comment by TCOTC** [comment]
@88250 建议先升级 graphviz 看看

**Comment by Vanessa219** [comment]
这个不是一个图片，可以支持自适应，但不能像普通图片一样支持点击预览。
