### ISSUE TITLE
脑图模式下列表项查询内容块失败

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#1118]
### 描述问题 Describe the problem

脑图模式下列表项的所属关系错误
![image](https://user-images.githubusercontent.com/16791452/104798307-b8497c00-5800-11eb-8858-fc2170412081.png)

```
- a
  - a1
  - a2
  - a3
- b
- c
```

### 期待的结果 Expected result
![image](https://user-images.githubusercontent.com/16791452/104798332-ee86fb80-5800-11eb-9749-32fb0d96f017.png)

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/16791452/104798314-cbf4e280-5800-11eb-968e-51888477d450.png)
![image](https://user-images.githubusercontent.com/16791452/104798335-f8a8fa00-5800-11eb-887d-98b98f8010a6.png)

### 版本环境 Version environment

* 版本 Version：0.6.1
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，层级逻辑应该没有问题，a 作为列表项和 a1 a2 a3 组成的列表是平级的。后面的查询失败应该是 bug，稍后修复。

**Comment by 88250** [comment]
排查了下，这个问题有点复杂，先靠编辑列表项上层的列表顶顶。
