### ISSUE TITLE
daily note创建不正确，在文档树删除后，思源无响应

### ISSUE THREAD

**Issue by ilo-l** [siyuan-note/siyuan#11182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/103417546/d7a89715-25fe-4335-80f1-8fef4186a6dc)
alt+5创建2024-04-29文档时，位置并不在daily note>2024>04路径下，而是新建了一个2024>untitled的路径。
在直接删除，untitled文档，或者在文档树打开2024-04-29思源就会进入未响应状态。
重新打开思源，点击untitled文档，也会进入未响应状态。
![image](https://github.com/siyuan-note/siyuan/assets/103417546/21984f4d-a132-47c8-bc45-22364e4f15f7)
在删除2024-04-29后，重新建立，路径并不在原有的daily note>2024>04，又新建daily note>2024>04的路径。

### Expected result

希望alt 5 的daily note 出现在原来文档树的位置

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):3.011
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/15146287/system-log.zip)

**Comment by 88250** [comment]
你好，从日志中看应该是强制结束过进程导致数据索引有问题，建议重建索引后再试试。
