### ISSUE TITLE
Add ability to embed Twitter/X tweets

### ISSUE THREAD

**Issue by anarion80** [siyuan-note/siyuan#11184]
### In what scenarios do you need this feature?

I want to save a tweet in SiYuan and want the 

### Describe the optimal solution

Optimal solution for me would be how Logseq does it:

`{{tweet https://twitter.com/logseq/status/1625486937938341890}}`

or 

`/tweet https://twitter.com/logseq/status/1625486937938341890`

would result in rendering the tweet:
![image](https://github.com/siyuan-note/siyuan/assets/2185791/5d560d3d-0829-4176-96dd-fec0557865f7)

or even have an option to automatically parse/regex twitter/x link and render then.

More info: https://discuss.logseq.com/t/link-preview-for-external-urls-aka-link-unfurl-cards-url-preview-url-expansion-link-expansion/16246

**Comment by 88250** [comment]
Hello, it is recommended to implement this requirement through plug-ins or widgets, thank you.
