### ISSUE TITLE
Catch SEND intents to import text on Android

### ISSUE THREAD

**Issue by corintho** [siyuan-note/siyuan#11187]
Add support for opening URLs and plain text on mobile

### In what scenarios do you need this feature?

When I want to add links to follow up later or copy some content to my notes.
I have to copy the text or URL, open the Siyuan app, paste the content, and go to what I was doing before.

### Describe the optimal solution

If the app is registered as an opener for URL and TEXT content (activity with intent-filter on Android) it would be a lot simpler to handle those cases more practically.
I understand there is a challenge in synchronizing this new information, it could be tackled in a few ways.

### Describe the candidate solution

I don't see an interim solution

### Other information

If the idea is accepted, I'm open to discussing possible solutions, and I can also create a PR to implement this feature for Android back-to-back. Unfortunately, I do not have enough knowledge to do it on iOS at this time.

**Comment by 88250** [comment]
I'm not sure if it's actually possible, but if you're already able to compile the SiYuan Android app, feel free to try to implement the sharing feature and PR to contribute the code, thanks.

**Comment by Soltus** [comment]
Yes, the problem is considering the IOS side.

**Comment by 88250** [comment]
v3.1.6 will add the ability to receive text data from other apps.

REF: https://developer.android.com/training/sharing/receive

After receiving the text data, it will be written to the clipboard (if the text is a URL, it will be converted to Markdown hyperlink syntax `[foo.com](foo.com)` and written).

We will further consider receiving files from other apps and inserting them into the end of the selected document as assets. Please follow https://github.com/siyuan-note/siyuan/issues/12426

Thanks.

**Comment by 88250** [comment]
As of v3.7.0, this has been switched to use shorthand: https://github.com/siyuan-note/siyuan/issues/17652
