### ISSUE TITLE
插件没有指定 `direction` 且 tagName 为 TEXTAREA 时，默认设置为 row 模式

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#11198]
### In what scenarios do you need this feature?

#11183 

@Vanessa219 

增加了 direction 参数后，之前插件的中的 textarea 变成了 column 模式了。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/76141f3f-558b-4f8f-9ea8-756a884f591d)

### Describe the optimal solution

为了避免大规模插件都要进行更改，建议在 Setting.ts 当中额外处理一下。

```ts
if (item.direction === undefined && actionElement.tagName === "TEXTAREA" {
    item.direction = 'row';
}
```

**Comment by Vanessa219** [comment]
为 undefined 的时候默认值是 column， 如果这样设置的话默认值就会更改了。只能麻烦插件作者修改一下了。

**Comment by frostime** [comment]
> 为 undefined 的时候默认值是 column， 如果这样设置的话默认值就会更改了。只能麻烦插件作者修改一下了。

1. 不太能理解您说的「默认值就会更改了」的顾虑和问题在哪里
2. 原本 textarea 的默认值就是 row，这里只是希望和之前的默认行为保持一致——毕竟以前就是对 textarea 做单独的特殊处理的
3. 「默认值」这种东西要合理、可用才有意义；而 textarea 如果设置为 column 模式，几乎是完全不可用的状态，所以把 textarea 的默认值设为 column 本来就是有问题的
4. 「麻烦插件作者修改一下」——但是很多插件作者现不一定能即时维护，甚至直接不维护了；改一下textarea的默认值，这些插件下周就可以重新正常使用；不改的话，可能有些插件要等到一两个月以后才能正常使用
