### ISSUE TITLE
脑图下，大纲块的子节点无法删除

### ISSUE THREAD

**Issue by nightlye** [siyuan-note/siyuan#1119]
https://user-images.githubusercontent.com/53067795/104798551-a8329c00-5802-11eb-81ed-37524dbc3537.mp4

如视频所示。
大纲块的子节点无法删除，但是大纲块节点可以被删除

**Comment by 88250** [comment]
你好，目前脑图有部分节点不支持移动和删除，暂时只能通过编辑 Markdown 进行操作。

后续我们会进行改进，但是短期内估计暂时没有时间细化，抱歉抱歉。
