### ISSUE TITLE
一个小问题：带有 NodeHeadingC8hMarker 类型的块，编辑后，经常会被重置

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#11190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

可能是以前从markdown导入的块，在编辑后，总是被重置。
比如下面这样的块，将标题 Sphere 修改为 Sphere1 后，刷新后，就被重置成 Sphere
``` json
{
	"ID": "20230425200694-9j3zox2",
	"Type": "NodeHeading",
	"HeadingLevel": 3,
	"Properties": {
		"id": "20230425200694-9j3zox2",
		"updated": "20240430103841"
	},
	"Children": [
		{
			"Type": "NodeHeadingC8hMarker",
			"Data": "### ",
			"Properties": {
				"id": ""
			}
		},
		{
			"Type": "NodeText",
			"Data": "Sphere",
			"Properties": {
				"id": ""
			}
		}
	]
},
```

而现在的标题块，没有 NodeHeadingC8hMarker 这个部分，没有这个问题

```json
{
	"ID": "20240430111210-zy3v0wi",
	"Type": "NodeHeading",
	"HeadingLevel": 3,
	"Properties": {
		"id": "20240430111210-zy3v0wi",
		"updated": "20240430111215"
	},
	"Children": [
		{
			"Type": "NodeText",
			"Data": "Spehre"
		}
	]
},
```

### Expected result

希望编辑后，不被重置。
或者提供能将全部笔记，重置为新的不带 NodeHeadingC8hMarker 的方法

### Version environment

```markdown
- Version: 3.0.11
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
我这里测试使用上述结构不会导致刷新后数据未记录问题，请上传一个能够重现问题的数据文件我再试试。

**Comment by zhoutaosheng** [comment]
@88250 我这边反复测试，已经无法重现了

一些可能的线索
- 这边怀疑是主题问题，把主题从 Dark+ 切到 默认主题，同样的操作，没有问题
- 然后，再切回到 Dark+ 主题，也没有重现这个问题

因此，也可能是主题问题，也可能是有其他因素同时作用。暂时没有找到稳定重现的方法。但确实是时而出现的问题。后续找到重现方法，再反馈给你

**Comment by 88250** [comment]
好的，那我先关闭了，后续如果还有问题请随时跟帖。
