### ISSUE TITLE
修改应用标题

### ISSUE THREAD

**Issue by ens100** [siyuan-note/siyuan#112]
Is it possible to change the title which appears on the Windows app to something like SiYuan? 

![image](https://user-images.githubusercontent.com/67863060/94365409-b9776180-00c8-11eb-9587-138e0687c418.png)

Apologies this is in English.

Many thanks

**Comment by 88250** [comment]
In the next release v0.2.4 it will be changed to `{title} - SiYuan`. The `{title}` may be current selected notebook or opened doc. In short, it should be something more meaningful than "When one drinks...". Thank you for letting us notice this.

English is welcome also, please let us know your feedback 😃
