### ISSUE TITLE
Adjust PDF export footer font size

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11203]
pdf导出的页脚支持设置字体大小

### In what scenarios do you need this feature?

看了下思源的源码，貌似pdf导出时，页脚只有8px字体大小，实在有点小了（我日常导出文字是17px）
![Clip_2024-04-30_23-30-01](https://github.com/siyuan-note/siyuan/assets/60436214/5c359287-fd12-4788-95d1-6e3f7b8953a6)
![Clip_2024-04-30_23-33-38](https://github.com/siyuan-note/siyuan/assets/60436214/58d168a8-6734-42e3-aef0-eea666fb497f)

### Describe the optimal solution

建议能加一个选框调节字体大小
![Clip_2024-04-30_23-32-42](https://github.com/siyuan-note/siyuan/assets/60436214/7e66bacc-c75c-4d20-b2ae-be79740dc88a)

### Describe the candidate solution

或者把8px先改成10-12px也行，8px确实太小了
或者模板语法支持设置字体大小

**Comment by 88250** [comment]
感谢反馈，配置项就不加了吧，考虑调整为 10-12px @Vanessa219

**Comment by Achuan-2** [comment]
如果不加选项的话，能否根据pdf字体大小来设置呢，比如设置为0.7em

**Comment by Vanessa219** [comment]
设置为 em, rem 页脚就无法显示了。先设置为 10px 试试吧。
