### ISSUE TITLE
使用ClipnoteFree的插入视频跳转链接功能无法转换为链接格式

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/zqszbd/clipnotefree/issues/2
此问题已在原插件作者那提过，但在群内交流开发者说也是用模拟按键来实现对应时间戳的插入，能在剪贴版获取到他也不知道怎么办了。
具体复现方式：
1.https://github.com/zqszbd/clipnotefree/releases/tag/Free  下载解压到任意文件夹，打开主程序
2.配置跳转链接功能快捷键(任意均可)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/95383eee-e924-4ce3-be28-60b6f3778096)
3.配置本地视频播放器potplayer主程序路径(也可以使用chrome或edge播放网页视频，根据https://www.yuque.com/zhangyewuxianxiaozhang/ghzwdl/qy049zf24bq7f05v  教程中的1.3安装浏览器插件，并配置2.2中的浏览器设置)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/165aa129-cfba-405b-8e59-dda415a85f5d)
4.打开本地mp4视频或网页b站视频后，光标定位到思源笔记中，使用快捷键插入视频跳转链接，然后就会如下图无法转换成链接格式，但是剪贴板历史记录里是正常的
![image](https://github.com/siyuan-note/siyuan/assets/63196026/13f30b95-5705-4963-a710-e80340a31e29)
5.排除了各种格式，只要不是[$time] ($url)这种链接格式都能正常复制进思源，剪贴板历史记录里也是正常的
![image](https://github.com/siyuan-note/siyuan/assets/63196026/d0a73f8c-14aa-4c8d-aaa5-2df286ef1ca8)
如下图只要不在编辑器内，都能正常粘贴
![image](https://github.com/siyuan-note/siyuan/assets/63196026/c22046c3-3dab-4a4c-b78c-c84b7e66190f)

### Expected result

能正常插入链接

### Version environment

```markdown
- Version: 3.0.12
- Operating System: win11
- Browser (if used):edge
```

### Log file

无报错

**Comment by 88250** [comment]
我这里测试正常，用的是浏览器插件 ClipNoteFreeExtension


[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/9a400bde-177c-48b6-9f14-57cfb424368e)

**Comment by 5kyfkr** [comment]
D大，再试试ctrl shift v，录屏软件里读到了是这个操作，我试了确实ctrl shift v不能复制进去
https://github.com/siyuan-note/siyuan/assets/63196026/72ad9533-460a-497d-87ee-666afadb98ae

**Comment by 88250** [comment]
Ctrl+Shift+V 是粘贴纯文本，这个粘贴进来不是超链接的。

**Comment by 5kyfkr** [comment]
> Ctrl+Shift+V 是粘贴纯文本，这个粘贴进来不是超链接的。

我知道了，我鬼屎的shift+R的快捷键把shift键带入进那个模版按键的ctrl v里了
