### ISSUE TITLE
鼠标划选选中多块，块右上方出现小竖线

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

鼠标划选选中多块，块右上方出现小竖线 

### Expected result

![Clip_2024-04-30_21-57-25](https://github.com/siyuan-note/siyuan/assets/60436214/ff837011-bc0a-4b26-a377-2bc8034b09da)

### Version environment

```markdown
- Version: 3.0.12
- Operating System: Win11
- Browser (if used):
```

### Log file

no need

**Comment by 88250** [comment]
我这里测试正常：

![image](https://github.com/siyuan-note/siyuan/assets/873584/8fdfe9c0-1068-49aa-8c3e-f85604e252ac)

**Comment by TCOTC** [comment]
可以稳定复现

![image](https://github.com/siyuan-note/siyuan/assets/78434827/92cf05e1-f5a6-480a-a05e-fe67f36eb244)

**Comment by TCOTC** [comment]
看上去是这个东西：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/308351ca-fe57-43bf-ba89-0ab199d383a9)

**Comment by 88250** [comment]
有使用什么代码片段么？

**Comment by TCOTC** [comment]
新建的工作空间

**Comment by 88250** [comment]
能录个屏看看如何拖动的吗？

**Comment by TCOTC** [comment]
就是很普通地拖动：

![拖动](https://github.com/siyuan-note/siyuan/assets/78434827/c9b1efdb-5858-4f6c-855d-dda6b95ebaf1)

**Comment by 88250** [comment]
我这里还是重现不了：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/ac98b72a-b811-4ca3-a981-218c6d618b93)

**Comment by TCOTC** [comment]
试试其他设备？

**Comment by 5kyfkr** [comment]
![image](assets/image-20240501000747-aco2fs0.png)
我这也可以重现

**Comment by Achuan-2** [comment]
这个issue在最新版已经没有了，关闭了

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/61d7ffd6-e41f-4d3b-b562-4eed3d053825)
我这dev2新工作空间一样还在

**Comment by TCOTC** [comment]
v3.0.15-dev2 还有：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b624d777-ae57-4891-a8c5-1596df0f2597)

**Comment by 88250** [comment]
是不是和设备显卡有关系？

**Comment by TCOTC** [comment]
@Achuan-2 换设备了？

**Comment by 5kyfkr** [comment]
我笔记本切独显直连和核显都一样

**Comment by 88250** [comment]
那就比较玄学了，这个问题我这里 win11 和 macos 都正常。

**Comment by TCOTC** [comment]
我是 WIN10

**Comment by 5kyfkr** [comment]
我公司win10和家里win11都有
