### ISSUE TITLE
中英文之间留空格问题

### ISSUE THREAD

**Issue by windoversnow** [siyuan-note/siyuan#1120]
https://github.com/siyuan-note/siyuan/issues/996#issuecomment-761499399

不是已经去掉中英文之间自动添加空格功能了吗（编辑时），我现在的笔记里还是会自动留空格，确切说是会有一定几率自动留出空格，没法控制

**Comment by 88250** [comment]
现在输入时已经不会自动添加空格了，请检查是不是其他辅助程序导致（比如输入法设置），谢谢。

**Comment by windoversnow** [comment]
> 现在输入时已经不会自动添加空格了，请检查是不是其他辅助程序导致（比如输入法设置），谢谢。

这个还真不是输入法原因 有些已经删完了空格的保存过的文章 改天打开修改局部内容 发现全文的空格又回来了

**Comment by 88250** [comment]
请检查一下版本，是不是启动了老的版本。
