### ISSUE TITLE
快捷键录入Ctrl+alt+上下左右箭头失败

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 在设置表格快捷键的过程中，快捷键录入Ctrl+alt+上下左右箭头失败，提示“ctrl+alt失效”
2. 在conf/conf.json直接修改快捷键Ctrl+alt+上下左右箭头，发现并没有work
3. 此外，快捷键搜索也不支持输入ctrl+alt+上下左右箭头
![Clip_2024-05-01_11-51-14](https://github.com/siyuan-note/siyuan/assets/60436214/48de9611-6618-44d6-82a4-69d263595467)

### Expected result

快捷键支持录入Ctrl+alt+上下左右箭头

### Version environment

```markdown
- Version: 3.0.12
- Operating System: Win11
- Browser (if used):
```

### Log file

no need

**Comment by Vanessa219** [comment]
是不是和系统快捷键冲突了，mac 和 windows 上都是可以的。

**Comment by TCOTC** [comment]
也许是其他程序占用了快捷键（比如输入法，可以换个输入法试试）

我这里同样正常：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8372e407-ab3c-4d0c-aa02-63339f8da31d)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1863f2cd-9d5b-4b0b-a8d0-461a7a4ed549)

**Comment by Achuan-2** [comment]
抱歉，网易云音乐的问题，默认开启全局热键了
