### ISSUE TITLE
集市-已下载页面过窄时，集市资源的名字和简介消失

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#11216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/38906705/a92051a7-aa86-45fb-8d15-0a45a848a4b5)

### Expected result

修复

### Version environment

```markdown
- Version: v3.0.12
- Operating System: win10
- Browser (if used):
```

### Log file

1

**Comment by TCOTC** [comment]
确实

![image](https://github.com/siyuan-note/siyuan/assets/78434827/509f5fee-3ea3-46d5-a8f2-734865d24c16)
