### ISSUE TITLE
option + e 偶尔快捷键失灵，会打出来 符号 `

### ISSUE THREAD

**Issue by Foundation-Maker** [siyuan-note/siyuan#11215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我这个option + e 设置为了垂直超级块
偶尔快捷键失灵，会打出来 符号 ` 
重启就会好。

### Expected result

正常使用

### Version environment

```markdown
- Version: 最新
- Operating System:  mac 
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/15175195/system-log.1.zip)

**Comment by 88250** [comment]
抱歉，我们无法重现该问题，先关闭了，如果还有其他补充请继续跟帖，谢谢 :pray:
