### ISSUE TITLE
搜索页面-小优化

### ISSUE THREAD

**Issue by Foundation-Maker** [siyuan-note/siyuan#11213]
### In what scenarios do you need this feature?

https://ld246.com/article/1712194645841

### Describe the optimal solution

1、可以显示更多的条数
2、保存的查询可以重命名
3、个别按钮，从二级菜单挪出来个更方便点击的地方。
4、文档层级间隔更清晰

![CleanShot_2024-05-01 _ 15 09 33@2x](https://github.com/siyuan-note/siyuan/assets/46839690/3e3e6c8b-c513-4f21-ad50-0ff882e3b680)

### Other information

https://ld246.com/article/1712194645841

**Comment by 88250** [comment]
暂时不考虑改变了，感谢反馈。
