### ISSUE TITLE
Support convert Base64 image when clipping HTML

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11210]
https://ld246.com/article/1714534561463

**Comment by TCOTC** [comment]
这里还是剪藏了一堆空格：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b2a22090-d607-4268-b10a-c30fd00c3ec0)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/535ac19f-394b-4161-a9ca-5490d9ec1812)

**Comment by 88250** [comment]
表格里确实还有问题，稍后改进，谢谢。
