### ISSUE TITLE
Double-clicking the database asset column causes the interface to freeze

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11220]
双击数据库资源列导致界面卡死

新建工作空间导入该文档：[双击文档测试.sy.zip](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/files/15175429/sy.zip)

双击数据库资源列：

![插件](https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/assets/78434827/d6570821-140f-44b4-a894-27a83f23a901)

关联：https://github.com/OpaqueGlass/syplugin-doubleClickFileTree/issues/18

**Comment by TCOTC** [comment]
@88250 帮忙看看这个能不能复现？

这个问题好像还不是之前那个卡死的问题

**Comment by 88250** [comment]
我这里可以重现 @Vanessa219
