### ISSUE TITLE
3.0.13 dev1 导出pdf 每页都有导出设置页面

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

3.0.13 dev1 导出pdf 每页都有导出设置页面
![Clip_2024-05-01_19-19-45](https://github.com/siyuan-note/siyuan/assets/60436214/bdc236fe-1122-4055-908a-be72b4f3326b)

### Expected result

正常导出

### Version environment

```markdown
- Version: 3.0.13 dev1
- Operating System: win11
- Browser (if used):
```

### Log file

no need

**Comment by 88250** [comment]
我这里无法重现，请确认一下是否有强制刷新 dev 版。

**Comment by 88250** [comment]
可以重现了。

**Comment by 88250** [comment]
请等新的 dev4 发布后再测试看看。
