### ISSUE TITLE
新建文档指定笔记本功能的全局设置对移动端无效

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

移动端似乎只看笔记本的设置

### Expected result

。。

### Version environment

```markdown
- Version: 最新
- Operating System: 安卓
- Browser (if used):
```

### Log file

。。

**Comment by TCOTC** [comment]
v3.0.12 应该已经修复了这个问题，除非你是这种情况：#11230

**Comment by 88250** [comment]
暂时用浏览器伺服顶顶吧，这一块要改的话估计得等后续重构移动端的时候才能考虑了，感谢反馈。

**Comment by Jiangshuon** [comment]
D大，闪卡、数据库、移动端、看板，这几个计划顺序是咋样的呢

**Comment by 88250** [comment]
闪卡重构目前正在由社区 @zxhd863943427 开发；其他优先级的话 数据库改进、看板、移动端。
