### ISSUE TITLE
回滚操作生成数据历史

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11229]
### In what scenarios do you need this feature?

目前：`回滚是不可逆的操作，一旦执行回滚后数据就无法回到当前状态`

所以我想，让回滚操作也生成数据历史的话，是不是就可逆了？

### Describe the optimal solution

回滚操作生成数据历史

**Comment by 88250** [comment]
这个怕是不考虑了，有提示应该就够用了，另外本身最后一次更新也会生成历史，还是可以用这个历史回滚的。

**Comment by TCOTC** [comment]
说实话，这个提示有够吓人

**Comment by 88250** [comment]
主要是提示用户回滚操作需要谨慎，文案可以考虑改改。

**Comment by TCOTC** [comment]
突然又想到那个「不要惊慌」反而会让人更慌，感觉文案是不是改一下更好？既然不想让人惊慌，就只应该用一些普通的平常的词汇

**Comment by TCOTC** [comment]
> 主要是提示用户回滚操作需要谨慎，文案可以考虑改改。

比如：文档回滚无法撤销，请确认后继续操作

**Comment by 88250** [comment]
帮忙 PR 改改，多谢。
