### ISSUE TITLE
移动文章出现 block not found v3.0.10

### ISSUE THREAD

**Issue by ccxuy** [siyuan-note/siyuan#11239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

移动文章出现 block not found v3.0.10

### Expected result

可正常移动

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/720603/98c561b9-5ce4-4e01-8c95-47d8b95afde7)

### Version environment

```markdown
- Version: 3.0.12
- Operating System: 
- Browser (if used):
```

### Log file

I 2024/05/03 15:54:14 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/05/03 15:54:14 runtime.go:74: kernel is booting:
    * ver [3.0.10]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/docker/siyuan]
I 2024/05/03 15:54:14 runtime.go:123: use network proxy [system]
I 2024/05/03 15:54:14 serve.go:115: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/05/03 15:54:15 blocktree.go:496: read block tree [16 MB] to [/docker/siyuan/temp/blocktree], elapsed [0.40s]
I 2024/05/03 15:54:15 conf.go:839: database size [146 MB], tree/block count [412/46526]
I 2024/05/03 15:54:15 working.go:192: kernel booted
I 2024/05/03 15:54:17 asset.go:97: loaded assets [2.48s]
I 2024/05/03 15:54:21 box.go:76: auto stat [trees=412, blocks=46526, dataSize=1.4 GB, assetsSize=1.1 GB]
I 2024/05/03 17:54:23 box.go:76: auto stat [trees=412, blocks=46526, dataSize=1.4 GB, assetsSize=1.1 GB]
I 2024/05/03 19:42:21 session.go:116: auth success [ip=192.168.3.1]
I 2024/05/03 19:42:21 serve.go:207: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
E 2024/05/03 19:45:58 tree.go:43: load tree [/20240427210149-3idyfnp.sy] failed: open /docker/siyuan/data/20230625022741-cf1jsyw/20240427210149-3idyfnp.sy: no such file or directory
E 2024/05/03 19:46:13 tree.go:43: load tree [/20240427210149-3idyfnp.sy] failed: open /docker/siyuan/data/20230625022741-cf1jsyw/20240427210149-3idyfnp.sy: no such file or directory
I 2024/05/03 19:46:32 database.go:110: reinitialized database [/docker/siyuan/temp/siyuan.db]
I 2024/05/03 19:46:32 index.go:206: rebuilt database for notebook [20230421014742-nyqqne7] in [0.10s], tree [count=20, size=3.4 MB]
I 2024/05/03 19:46:33 index.go:206: rebuilt database for notebook [20230820003901-zbhbo3d] in [0.39s], tree [count=97, size=7.5 MB]
I 2024/05/03 19:46:34 index.go:206: rebuilt database for notebook [20230625022741-cf1jsyw] in [1.15s], tree [count=297, size=24 MB]
I 2024/05/03 19:46:35 index.go:206: rebuilt database for notebook [20230502033208-lbol4db] in [0.00s], tree [count=2, size=19 kB]
I 2024/05/03 19:46:35 index.go:206: rebuilt database for notebook [20230625023703-bne9lgs] in [0.01s], tree [count=1, size=308 kB]
I 2024/05/03 19:46:36 index.go:278: resolved refs [0] in [212ms]
I 2024/05/03 19:50:05 serve.go:207: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
W 2024/05/03 19:50:49 blocktree.go:559: save block tree [size=16 MB] to [/docker/siyuan/temp/blocktree], elapsed [252.99s]
I 2024/05/03 19:52:03 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/05/03 19:52:03 runtime.go:74: kernel is booting:
    * ver [3.0.10]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/docker/siyuan]
I 2024/05/03 19:52:03 runtime.go:123: use network proxy [system]
I 2024/05/03 19:52:03 serve.go:115: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/05/03 19:52:03 blocktree.go:496: read block tree [16 MB] to [/docker/siyuan/temp/blocktree], elapsed [0.23s]
I 2024/05/03 19:52:03 conf.go:839: database size [6.7 MB], tree/block count [416/47321]
I 2024/05/03 19:52:03 working.go:192: kernel booted
I 2024/05/03 19:52:05 box.go:76: auto stat [trees=416, blocks=47321, dataSize=1.4 GB, assetsSize=1.2 GB]
I 2024/05/03 19:52:27 serve.go:207: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36]
E 2024/05/03 19:52:38 tree.go:43: load tree [/20240427210149-3idyfnp.sy] failed: open /docker/siyuan/data/20230625022741-cf1jsyw/20240427210149-3idyfnp.sy: no such file or directory
W 2024/05/03 19:52:48 file.go:1296: block tree not found by path [/20240427210149-3idyfnp.sy]
E 2024/05/03 19:52:55 tree.go:43: load tree [/20240427210149-3idyfnp.sy] failed: open /docker/siyuan/data/20230625022741-cf1jsyw/20240427210149-3idyfnp.sy: no such file or directory
E 2024/05/03 19:53:28 tree.go:43: load tree [/20240427210149-3idyfnp.sy] failed: open /docker/siyuan/data/20230625022741-cf1jsyw/20240427210149-3idyfnp.sy: no such file or directory
E 2024/05/03 19:54:19 tree.go:43: load tree [/20240427210149-3idyfnp.sy] failed: open /docker/siyuan/data/20230625022741-cf1jsyw/20240427210149-3idyfnp.sy: no such file or directory

**Comment by 88250** [comment]
请升级到最新版重建索引后再试试，这个问题应该是旧版本的问题。

如果升级最新版后重建索引后还能重现该问题，请继续跟帖，我们先关闭，感谢反馈。

**Comment by ccxuy** [comment]
更新到v3.0.12依然有，我发现在另外一个归档用的文件夹疑似有同样文章，我将这个出错的删除了，目前没发现别的问题

> 请升级到最新版重建索引后再试试，这个问题应该是旧版本的问题。
> 
> 如果升级最新版后重建索引后还能重现该问题，请继续跟帖，我们先关闭，感谢反馈。

**Comment by 88250** [comment]
收到。



---原始邮件---
发件人: "Misaka ***@***.***&gt;
发送时间: 2024年5月5日(周日) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 移动文章出现 block not found v3.0.10 (Issue #11239)




 
更新到v3.0.12依然有，我发现在另外一个归档用的文件夹疑似有同样文章，我将这个出错的删除了，目前没发现别的问题
  
请升级到最新版重建索引后再试试，这个问题应该是旧版本的问题。
 
如果升级最新版后重建索引后还能重现该问题，请继续跟帖，我们先关闭，感谢反馈。

**Comment by ccxuy** [comment]
> 收到。
> […](#)
> ---原始邮件--- 发件人: "Misaka ***@***.***&gt; 发送时间: 2024年5月5日(周日) 中午12:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 移动文章出现 block not found v3.0.10 (Issue #11239) 更新到v3.0.12依然有，我发现在另外一个归档用的文件夹疑似有同样文章，我将这个出错的删除了，目前没发现别的问题 请升级到最新版重建索引后再试试，这个问题应该是旧版本的问题。 如果升级最新版后重建索引后还能重现该问题，请继续跟帖，我们先关闭，感谢反馈。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

目前siyuan收藏的量已经比较大了，希望能增强这方面的功能（类似剪藏，omniverse，pinbox），如果能类似文件系统那样能检查一些错误自动修复就更好了，给软件付了个费，祝软件发展越来越好

**Comment by 88250** [comment]
目前启动后的第一次同步后会自动校验索引。
