### ISSUE TITLE
Allow referring to the current database in a "Relation" field

### ISSUE THREAD

**Issue by AnweshGangula** [siyuan-note/siyuan#11233]
### In what scenarios do you need this feature?

I want to create a databse of Tools and add a property called "Alternatives" which will show a list of tools which are alternatives to the current row. So to implement this, i need to be able to add a relation field which refers to the current database

### Describe the optimal solution

Allow a relation field to refer to its own database

### Describe the candidate solution

Check out an example screenshot from Notion which works for this scenario:

![image](https://github.com/siyuan-note/siyuan/assets/142878184/01c6e8ff-0085-414a-8ee3-968758e73f0c)

**Comment by TCOTC** [comment]
#9305 ?
