### ISSUE TITLE
数据库支持保存某列为模板，可以重复调用

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11236]
### In what scenarios do you need this feature?

目前数据库新建列的重复操作太多，
比如评级我用几个星星来表示，这不仅仅可以用来标注图书、电影、文献的打分，还可以用来标注任务优先级，但是每次都得手打星星特别麻烦，还需要配置颜色。以及用于任务管理的状态列，我使用todo、doing、abort、done，也是非常常用，每次都要手动添加。
比如一些模板公式列，每次使用需要去相关笔记、数据库找代码来复制使用
而想必官方也没有太多精力，创建更多的列类型覆盖更多的场景。所以建议支持保存列为模板，可以重复调用，方便用户也减少官方开发压力。

### Describe the optimal solution

能否出一个功能，支持保存某列为模板，可以便捷调用那些经常使用的列，这对于新建多选列和单选列特别有用，目前每次新建完都需要一个个填充选项，非常麻烦。

建议
1. 支持对单选列、多选列、模板列保存为模板
2. 列模板可以保存在目前的templates文件夹中，比如放在.database这个文件夹下（在编辑器调用普通文本模板排除这个文件夹不调用数据库列模板），保存形式建议以json格式，key包含name、type、 items。单选列的items就是每个选项的名称和配色，模板列的items就是模板内容。这样也方便用户可以把自己的列模板进行批量修改和分享。

此外，目前的模板列是不是只能用 Sprig 模板，通过代码逻辑显示特定文本？如果是的话，建议将其名称改为公式列

### Describe the candidate solution

无

**Comment by zxhd863943427** [comment]
与其说是列模板，不如上database按钮来执行自动化操作吧……

**Comment by 88250** [comment]
这个考虑插件实现吧，感谢提议。
