### ISSUE TITLE
Clicking a hyperlink on Android does not open the browser

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11240]
Android 端点击超链接未跳转浏览器打开

https://ld246.com/article/1714647331269

**Comment by Soltus** [comment]
思源现在的思路是超链接和双链都是点击就打开吧，我修改逻辑为[暂存](https://github.com/Hi-Windom/Sillot/blob/3300b873971ce0a6add0508e16b0e33f73888d66/app/src/protyle/util/compatibility.ts#L5-L64) 感觉挺舒服的，不过我的实现不是很优雅，希望思源可以考虑一下！这个关联安卓端 https://github.com/siyuan-note/siyuan-android/pull/19
暂存而不是立即打开主要是基于以下几点考虑：

1. 之前有用户反馈的安卓卡顿问题， 发现他的文档几乎布满了双链，这种情况暂存一定程度上可以避免UI阻塞卡顿
2. 编辑的情况下，单击预期的可能是需要修改锚文本，这时候直接打开会阻断这一流程

**Comment by Soltus** [comment]
点击双链还有一个缺陷是在手机浏览器端无法返回，如果官方可以提供 [sy-plugin-enhance](https://github.com/Wetoria/sy-plugin-enhance) 插件的底部导航栏那样就可以在手机浏览器里返回了（APP里不显示）

**Comment by 88250** [comment]
这个改动有点大，可能会影响其他交互，暂时还是不动了，移动端等后续考虑重构，谢谢。
