### ISSUE TITLE
行级代码与加粗两种排版属性不兼容

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [x] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图所示，我在一段已经加粗的文本上用\`\`来包裹一段文字，不能触发行级代码。
<img width="680" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/f89958ea-3963-4882-b3a9-b23491e82422">

如图所示，在行级代码中进行加粗操作会导致这一部分文字产生分离。
<img width="633" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/26c17884-be38-429a-b47e-5c755c5a0661">

### Expected result

.

### Version environment

```markdown
- Version: 3.0.12
- Operating System: macOS
- Browser (if used): 13.6.6
```

### Log file

.

**Comment by TCOTC** [comment]
> 如图所示，我在一段已经加粗的文本上用``来包裹一段文字，不能触发行级代码。

这个确实是，用快捷键可以，但直接输入 `` ` `` 不行

> 如图所示，在行级代码中进行加粗操作会导致这一部分文字产生分离。

话说 Markdown 的行级代码里能加粗吗？应该只能在加粗里放行级代码吧？所以这个应该是正常的表现？

**Comment by LoneFireBlossom** [comment]
> 话说 Markdown 的行级代码里能加粗吗？应该只能在加粗里放行级代码吧？所以这个应该是正常的表现？

我搜了一下没看到有人提过这个问题所以我就问了，至于开发者选择要不要遵循markdown的规范我无所谓

**Comment by 88250** [comment]
尽量遵循 Markdown 规范。

**Comment by LoneFireBlossom** [comment]
？这个issue有两项

**Comment by LoneFireBlossom** [comment]
???????????

**Comment by TCOTC** [comment]
@88250 这段话被忽略掉了：

> 如图所示，我在一段已经加粗的文本上用``来包裹一段文字，不能触发行级代码。
>
> ![image](https://github.com/siyuan-note/siyuan/assets/78434827/71eb208c-1ea8-43f6-8709-ae8a29a06f6d)

**Comment by 88250** [comment]
已经形成的行级元素就不能用标记符再次嵌套了。
