### ISSUE TITLE
关于思源笔记块引导出脚注的改进建议

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11247]
### In what scenarios do you need this feature?

目前块引导出脚注只适配了对选中一句话进行引用
![Clip_2024-05-04_10-51-44](https://github.com/siyuan-note/siyuan/assets/60436214/ea7f8042-23d4-4d16-beaf-58798eeda517)
在GitHub预览，效果是预期内的，很不错
![Clip_2024-05-04_10-52-12](https://github.com/siyuan-note/siyuan/assets/60436214/c495ee75-01d4-4ccb-87c6-69ea0a194775)
但是这种选中一句话的引用有一个问题，如果我想要一句话多个引用就做不到了，所以我会使用`*`作为锚文本来引用，比如下面这样子：
![Clip_2024-05-04_11-02-32](https://github.com/siyuan-note/siyuan/assets/60436214/90603ad0-fe84-4f5b-94ab-d55e70a8b379)
但是目前思源对这种引用的脚注导出没有很好适配,导出的脚注依然有`*`，建议锚文本为`*`的，如果设置块引导出为脚注，则将`*`删除，直接为脚注语法。
![Clip_2024-05-04_11-01-57](https://github.com/siyuan-note/siyuan/assets/60436214/b026cdfd-51db-4714-97c0-3333de338e3f)

此外，如果想用块引在思源笔记内实现脚注功能，要么块引新建文档要么基于段落块引用
块引选中文字新建文档的问题有两个
1. 新建那么多脚注块引文档不切实际，就算不在乎文档树有这些文档，考虑到文档在搜索的优先级，这些文档也会影响到日常搜索体验 
2. 块引选中文字新建文档会导致一句话只能引用一个引用，不好再引用另一个了。

而基于段落块引用现在的问题主要在于在文章最后放备注内容，引用完了之后，这些备注内容依然会导出，要解决只能把这些块放到子文档里去，不是那么方便。
所以我还想建议，一个垂直超级块如果命名为脚注或者Footnotes的块则不导出（这个命名可以官方自定义，或者在导出设置里添加一个选项，凡是块命名为xxx的就都不导出）
![Clip_2024-05-04_11-16-41](https://github.com/siyuan-note/siyuan/assets/60436214/81e8f020-69a7-498c-8f7f-5cc4f61b4e9a)

### Describe the optimal solution

1. 块引用导出，锚文本为*的，如果设置块引导出为脚注，则将`*`删除，直接为脚注语法。因为没人会对`*`进行备注，`*`只是一个占位符号，而且官方的块引转换就包含的转换锚文本为`*`，可以看作是一个规范
2. 为了方便使用笔记末尾的段落块来引用，实现脚注功能，建议一个块如果命名为脚注或者Footnotes的块则不导出（这个命名可以官方自定义，或者在导出设置里添加一个选项，凡是块命名为xxx的就都不导出）这个建议也不仅仅可以用于笔记末尾段落块引用这个场景，还可以用于屏蔽某个块，毕竟个人笔记要导出，有些块可能是个人的备注等等，不希望导出。

改进这两点之后，思源的块引就完全可以代替脚注功能了

### Describe the candidate solution

还有一个想法，块引转换添加一个转换为`[*]`，锚文本为`[*]`的，只要引用的块在本文章内，就不在正文导出，只导出为脚注，并且导出时块引的锚文本删除，替换为脚注语法
这个会比要用块命名来避免导出更方便，`[*]`这个文本也是参考脚注语法，改成`[^*]`也行
这样就意味着我要引用一篇文献，不一定要先把这篇文献放在文章末尾，而是直接可以在该段下面添加，然后块引进行引用。
写完之后再把所有文献列表汇总放在末尾也不迟。
![Clip_2024-05-04_11-33-16](https://github.com/siyuan-note/siyuan/assets/60436214/9447e599-d27b-4d22-8c14-db50327b0767)

### Other information

链滴帖子：https://ld246.com/article/1714794288514

**Comment by 88250** [comment]
抱歉，这部分不考虑再改动了，谢谢。

**Comment by Achuan-2** [comment]
> 抱歉，这部分不考虑再改动了，谢谢。

思源对文献引用、脚注的支持不足，还是很遗憾的
块引用支持转化为`[*]`, 将其作为脚注的替代功能，已经是我能想到最好的方案了
