### ISSUE TITLE
The file name encoding is abnormal after copying the image and pasting it

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#11246]
一个小bug：复制带空格命名的资源，带%20，从而导致出现在丢失的资源文件中

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

重现步骤：
比如一个图片， 命名为 How TCP Works.gif
- 拖进思源后为 How TCP Works-**********.gif
- 然后复制一下，文件名为 How%20TCP%20Works-**********.gif
最后出现在丢失的资源文件中
![image](https://github.com/siyuan-note/siyuan/assets/5683995/f33909fc-d940-40b0-9fb6-e7e0640e9832)

### Expected result

复制的时候，不要将空格改为 %20，已有的资源丢失，我自己改对。
另外希望顺便检查其他windows环境下，允许作为命名的特殊字符是否存在问题，感谢

### Version environment

```markdown
- Version: 3.0.12
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
> 然后复制一下，文件名为 How%20TCP%20Works-**********.gif

这里的 `复制` 是如何操作的？

> 另外希望顺便检查其他windows环境下，允许作为命名的特殊字符是否存在问题

这个在插入资源文件的时候检查过的。
