### ISSUE TITLE
Lost URL content after `:` when pasting as a link

### ISSUE THREAD

**Issue by joaosimuai** [siyuan-note/siyuan#11245]
URLs containing ":" are excluding content after ":" when pasted from clipboard directly to text as links (after last update)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Summed in the title. URLs are properly pasted only INSIDE the "link box" (link, anchor, title...) via right-click, requiring 2 actions instead of 1. It started after the last update, before that I had no problems. I haven't tried other syntax other than ":", sorry.

### Expected result

Paste the URL in its entirety from the clipboard to siyuan's on screen plain text, generating a link.

### Version environment

```markdown
- Version: v3.0.12
- Operating System: Windows 11 23H2
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15202617/siyuan.log)

**Comment by 88250** [comment]
Please provider the example URL for testing.

**Comment by joaosimuai** [comment]
> Please provider the example URL for testing.

Hi!
For example, copying "https://en.wikipedia.org/wiki/Category:Contents", will paste only "https://en.wikipedia.org/wiki/Category"

**Comment by TCOTC** [comment]
`Ctrl+K`

![image](https://github.com/siyuan-note/siyuan/assets/78434827/53b63083-eba3-4177-88ad-f7f283eef9a7)

**Comment by joaosimuai** [comment]
Hey, thank you very much! 🎉
