### ISSUE TITLE
打开了换行的数据库有点怪

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11243]
### 打开了换行的数据库有点怪（其实不开换行也会出现）

中间多了 3 行：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/69289c5a-5c5b-44ac-b8aa-3c34b6b8b915)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/0a78cea5-959a-4f91-a501-aa715e288ff2)

**Comment by Vanessa219** [comment]
这个没有关系，属性太多，为了方便开发人员阅读。
