### ISSUE TITLE
Optimize rendering performance of databases containing relation fields

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11249]
含有关联列的数据库选项加载速度优化

### In what scenarios do you need this feature?

如题，起因是发现我的主题大库和文档大库点开菜单会卡顿60ms左右，后台一直报[Violation] Forced reflow while executing JavaScript took 66ms，一直在强制重排如下图
![image](https://github.com/siyuan-note/siyuan/assets/63196026/dcce3432-06bc-490e-80ab-d5bcc5cee879)

尝试关了插件，但还是会和正常库有30ms左右的延迟区别，详见下视频
https://github.com/siyuan-note/siyuan/assets/63196026/6854917c-98e4-4c03-972b-e6d3a127518c
下面是视频里末端的演示笔记附件，可以复现，点击单选列明显上面的会慢，看性能数据却又是延迟相接近
[主题库.sy.zip](https://github.com/siyuan-note/siyuan/files/15209095/sy.zip)
只有把关联列都删了就正常了

### Describe the optimal solution

希望延迟恢复正常，不强制重排，强制重排的时候是在执行以下JS语句，但是每次好像都不一样，供参考
```javascript
window.siyuan.hideBreadcrumb && (window.siyuan.hideBreadcrumb = !1,
            Yb().forEach(o=>{
                o.protyle.breadcrumb?.element.classList.contains("protyle-breadcrumb__bar--hide") && (o.protyle.breadcrumb.element.classList.remove("protyle-breadcrumb__bar--hide"),
                o.protyle.breadcrumb.render(o.protyle, !0))
            }
            )),
            !e && t.buttons === 0 && window.siyuan.layout.bottomDock && !(0,
            T.FJ)() && (t.clientX < Math.max(document.getElementById("dockLeft").clientWidth + 1, 16) ? !window.siyuan.layout.leftDock.pin && window.siyuan.layout.leftDock.layout.element.clientWidth > 0 && (window.siyuan.layout.leftDock.element.clientWidth > 0 || window.siyuan.layout.leftDock.element.clientWidth === 0 && t.clientX < 8) && (t.clientY > document.getElementById("toolbar").clientHeight && t.clientY < window.innerHeight - document.getElementById("status").clientHeight - document.getElementById("dockBottom").clientHeight ? !v(t.target, "b3-menu") && !v(t.target, "protyle-toolbar") && !v(t.target, "layout--float") && window.siyuan.layout.leftDock.showDock() : window.siyuan.layout.leftDock.hideDock()) : t.clientX > window.innerWidth - Math.max(document.getElementById("dockRight").clientWidth - 2, 16) && !window.siyuan.layout.rightDock.pin && window.siyuan.layout.rightDock.layout.element.clientWidth > 0 && (window.siyuan.layout.rightDock.element.clientWidth > 0 || window.siyuan.layout.rightDock.element.clientWidth === 0 && t.clientX > window.innerWidth - 8) && (t.clientY > document.getElementById("toolbar").clientHeight && t.clientY < window.innerHeight - document.getElementById("status").clientHeight - document.getElementById("dockBottom").clientHeight ? !v(t.target, "layout--float") && !v(t.target, "protyle-toolbar") && window.siyuan.layout.rightDock.showDock() : window.siyuan.layout.rightDock.hideDock()),
            t.clientY > Math.min(window.innerHeight - 10, window.innerHeight - (window.siyuan.config.uiLayout.hideDock ? 0 : document.getElementById("dockBottom").clientHeight) - document.querySelector("#status").clientHeight) && window.siyuan.layout.bottomDock.showDock());
            const a = t.composedPath()[0];
```

**Comment by 5kyfkr** [comment]
最好能像notion一样支持动态加载关联数据库的项目

**Comment by TCOTC** [comment]
平时用数据库的时候确实会感觉弹出菜单有「延迟」的感觉

**Comment by 5kyfkr** [comment]
> 平时用数据库的时候确实会感觉弹出菜单有「延迟」
> 
> 不过新建数据库试了一下发现好像跟有没有关联列没啥关系

要数据量多了才会有感觉，我一百多篇文章分别关联过去主题库下面对应的文档，然后就已经延迟增加了，但是后续速度没有变得更慢，一开始应该是以前3.0.3和3.04遗留了许多修复bug的代码造成卡顿导致延迟60ms，但今天我重新弄了新库添加也是会慢

**Comment by 88250** [comment]
这个和界面重绘应该关系不大，看一下是不是某个网络请求比较慢？

**Comment by 5kyfkr** [comment]
> 这个和界面重绘应该关系不大，看一下是不是某个网络请求比较慢？

![image](https://github.com/siyuan-note/siyuan/assets/63196026/b2177d02-e199-416a-8396-8d6704197861)

数据库还会网络请求嘛，上图网络那里也没有相关请求吧，现在是比如加一段JS代码没排除数据库都会影响点击操作速度，有没可能弄出类似notion那种先出界面再转圈加载的方式？如下面视频

https://github.com/siyuan-note/siyuan/assets/63196026/9b2f60ac-a34b-4973-ae1c-6c6bf82ed1ec

**Comment by 88250** [comment]
找到一个优化点，下个 dev 版本麻烦帮忙测试看看。

**Comment by 5kyfkr** [comment]
dev2试了虽然还是有强制重排，但是速度和感觉比以前快了几十毫秒，基本能和没有双向关联的库比了，排查了插件是日历面板这个插件也会有影响，关了插件20ms，开了就会重排到60ms，总体还是比上版好很多了，把重排前的那段渲染延迟从30ms优化到1ms了
![image](https://github.com/siyuan-note/siyuan/assets/63196026/44815db8-a68d-473b-a9c3-bed5ab14168f)

**Comment by 5kyfkr** [comment]
日历面板这个插件，似乎只要开了就会在数据库内强制重排，各位大佬们有没有什么办法排查
![image](https://github.com/siyuan-note/siyuan/assets/63196026/c86c7103-a7c6-49d6-8be2-ae0098b3ce53)
