### ISSUE TITLE
导出 PDF 时第一页空白

### ISSUE THREAD

**Issue by entps** [siyuan-note/siyuan#11258]
macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常

### Expected result

macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常

**Comment by TCOTC** [comment]
可以补充一下使用的思源版本号

**Comment by entps** [comment]
当前版本 v3.0.12

**Comment by 88250** [comment]
请将能够重现问题的文档导出 .sy.zip 发给我们测试看看 845765@qq.com

**Comment by entps** [comment]
已发邮件

**Comment by 88250** [comment]
你好，已经收到测试数据集，我们在 macOS 上测试导出 PDF 正常，首页没有空白。

请在默认主题并且关闭代码片段等扩展后再测试看看。

**Comment by entps** [comment]
好的，我试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月05日 22:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [siyuan-note/siyuan] macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常 (Issue #11258) |

你好，已经收到测试数据集，我们在 macOS 上测试导出 PDF 正常，首页没有空白。

请在默认主题并且关闭代码片段等扩展后再测试看看。

**Comment by entps** [comment]
测试了，不行，还是一样的，使用默认主题，关闭所有代码片段，，仍然是首页空白


吴建忠
13928500723
***@***.***
佛山市恩特普斯管理咨询有限公司 资深实施顾问


在 2024年5月5日 ***@***.***> 写道：


你好，已经收到测试数据集，我们在 macOS 上测试导出 PDF 正常，首页没有空白。
请在默认主题并且关闭代码片段等扩展后再测试看看。

**Comment by 88250** [comment]
在新工作空间中导入测试看看？

**Comment by entps** [comment]
M2 MacbookAir，，，ARM版本




在 2024年5月5日 ***@***.***> 写道：


你好，已经收到测试数据集，我们在 macOS 上测试导出 PDF 正常，首页没有空白。
请在默认主题并且关闭代码片段等扩展后再测试看看。

**Comment by entps** [comment]
好的，我试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月05日 22:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [siyuan-note/siyuan] macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常 (Issue #11258) |

在新工作空间中导入测试看看？

**Comment by entps** [comment]
新建一个空间导入后，导出PDF正常了，，，不知道是哪里出了问题




在 2024年5月5日 ***@***.***> 写道：


在新工作空间中导入测试看看？

**Comment by 88250** [comment]
估计还是有什么插件或者扩展影响了，关闭所有扩展以后重启后再试试？

**Comment by entps** [comment]
找不到，所有的插件、挂件、主题都删除了，代码片断也删除了，已完全恢复到默认状态，还是不行。


但同一工作区同步到Windows之后是正常的，在Windows中从没出现过类似的问题。


在 2024年5月5日 ***@***.***> 写道：


估计还是有什么插件或者扩展影响了，关闭所有扩展以后重启后再试试？

**Comment by 88250** [comment]
试下删除 用户家目录/.config/siyuan/windowState.json 后再启动测试。

**Comment by entps** [comment]
试了，只删除 windowsState.json不行，要删除 conf.json 才行
在 2024年5月6日 ***@***.***> 写道：


试下删除 用户家目录/.config/siyuan/windowState.json 后再启动测试。

**Comment by 88250** [comment]
收到，那可能是某个配置引起的问题，现在是否能帮忙 diff 一下两个文件的差异？

**Comment by entps** [comment]
有没有什么工具可以对比两个文件的差异？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月06日 11:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [siyuan-note/siyuan] macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常 (Issue #11258) |

收到，那可能是某个配置引起的问题，现在是否能帮忙 diff 一下两个文件的差异？

**Comment by 88250** [comment]
git 就行，或者你发我邮箱吧 ***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月6日(周一) 中午12:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常 (Issue #11258)




 有没有什么工具可以对比两个文件的差异？
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2024年05月06日 11:37 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [siyuan-note/siyuan] macOS版本导出PDF时首页总是空白页，同一文档在Windows版本中导出PDF正常 (Issue #11258) |
 
 收到，那可能是某个配置引起的问题，现在是否能帮忙 diff 一下两个文件的差异？

**Comment by entps** [comment]
在 2024年5月6日 ***@***.***> 写道：


收到，那可能是某个配置引起的问题，现在是否能帮忙 diff 一下两个文件的差异？

**Comment by 88250** [comment]
我邮箱 845765@qq.com

**Comment by entps** [comment]
已发该邮箱
在 2024年5月6日 ***@***.***> 写道：


我邮箱 ***@***.***

**Comment by 88250** [comment]
收到，谢谢。

**Comment by zxhd863943427** [comment]
在3.14上可复现该问题，并且可在新工作空间复现。文档已上传：
[test.sy.zip](https://github.com/siyuan-note/siyuan/files/15329779/test.sy.zip)

并且同时存在两个问题，首页空白和最后一页存在滚动条：

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/ac6ad7e9-922c-4aa9-a184-d9f9b75236ea)

**Comment by 88250** [comment]
@Vanessa219 有空看看

**Comment by zxhd863943427** [comment]
那奇怪了，我这里的平台是windows10，之后我再看看吧。

**Comment by TCOTC** [comment]
两个问题都碰到了：https://ld246.com/article/1717488272178

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3516999a-15e5-477b-9b0b-197ee12d96a2)

**Comment by TCOTC** [comment]
关联 [导出为 pdf 的第一页为空白 - 链滴](https://ld246.com/article/1728051968985)

**Comment by Vanessa219** [comment]
这个可以重现么？

**Comment by TCOTC** [comment]
我这边重现不了
