### ISSUE TITLE
Improve interaction when deleting two-way relation field in a database

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11252]
删除数据库双向关联列时提供弹窗选择

### In what scenarios do you need this feature?

数据库删除关联列的时候应该要自动解除双向关联，否则会把另一个数据库的关联列也删除

最坑的是删除之后无法撤回，很容易就误删了

**Comment by 88250** [comment]
改进为让用户选择是否删除关联目标字段，类似 Notion：

![image](https://github.com/siyuan-note/siyuan/assets/873584/fb004e68-7b3a-406f-be99-f2be5c33dbd9)

**Comment by TCOTC** [comment]
我觉得文案可以完全抄 Notion 的（“属性”换成“字段”）：

![image](https://github.com/user-attachments/assets/8b030e2e-6282-47df-8ad5-d8bc2dd28204)

**Comment by 88250** [comment]
有点不一样的，因为如果不是双向关联是不弹确认框的。

**Comment by TCOTC** [comment]
刚刚试了一下，删除双向关联列不会弹窗

**Comment by 88250** [comment]
没有改完的，等 issue 关闭。

**Comment by TCOTC** [comment]
### 01 我觉得加一个“但”会更合适：

![image](https://github.com/user-attachments/assets/e3f288f2-c080-452a-a5b0-289f55780d21)

像 Notion 这样：

![image](https://github.com/user-attachments/assets/fbf3b668-95a1-4746-9bdc-c466d8a004f4)

### 02 关联字段还是双向关联的状态：

[视频.webm](https://github.com/user-attachments/assets/f0d45b22-63bb-4d24-ac51-1e012177e8ea)

**Comment by 88250** [comment]
稍后调整。
