### ISSUE TITLE
 使用 Docker 搭建，浏览器访问出现:fetch post error ReferenceError: ipcRenderer is not defined 

### ISSUE THREAD

**Issue by chenxuan520** [siyuan-note/siyuan#11256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

3.12 手机端作为私服,浏览器无法访问

### Expected result

参考 https://ld246.com/article/1714577616257

### Version environment

```markdown
- Version: 3.11
- Operating System: 安卓
- Browser (if used):chrome firefox
```

### Log file

参考 https://ld246.com/article/1714577616257

**Comment by chenxuan520** [comment]
除此以外还有一个问题,无法稳定复现,但是也是非常烦的,安卓端用久了(大约1个月)后下次手机打开都需要输入密码(正常应该是浏览器访问才要).重新安装可以解决这个问题(这也是为什么我下载了3.12的原因),非常奇怪,但是无法稳定复现就没有提issue,但是3.12又出现了这个问题,非常烦
这个问题已经涉及到了最基本的可用性问题了,希望快点解决

**Comment by TCOTC** [comment]
> 安卓端用久了(大约1个月)后下次手机打开都需要输入密码(正常应该是浏览器访问才要)

设计上是设置访问授权码之后每次打开思源笔记都要输入访问授权码的，但不知道为什么这个过程在移动端会被跳过，导致不需要输入访问授权码都可以打开思源笔记

**Comment by TCOTC** [comment]
> 浏览器无法访问

等下个版本再看

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/pull/11195

**Comment by hugoyue** [comment]
![iShot_2024-05-05_16 55 10](https://github.com/siyuan-note/siyuan/assets/36737373/0cdd2eee-fd3d-4325-8a47-21c10166222f)
升级最新版本后，浏览器打不开，PC端

**Comment by 88250** [comment]
@hugoyue 试试 dev 版。

**Comment by hugoyue** [comment]
> @hugoyue 试试 dev 版。

好的，我试试
