### ISSUE TITLE
使用的查询条件关键字为空时，保持原有关键字

### ISSUE THREAD

**Issue by V7kb** [siyuan-note/siyuan#11254]
### In what scenarios do you need this feature?

现状：在已搜索时，点击切换已保存的查询条件，搜索框中的文本会被清空，需要重新输入进行搜索。

需求：点击切换已保存的查询条件，文本框中的内容不会被清空，且自动执行搜索。例如：当前查询条件是标题，搜索“AAA”，显示出10条标题的搜索结果。点击切换保存查询条件为文本块+嵌入块，则自动显示“AAA”的文本块+嵌入块搜索结果。

按照现有的搜索形式，搜索流程应该是：打开搜索框——选择保存的查询条件——输入关键词搜索——找到需要的内容。
实际使用中，更合理的搜索流程是：打开搜索框——输入关键词搜索——未找到结果——切换查询条件——找到需要的内容

### Describe the optimal solution

1

### Describe the candidate solution

1

### Other information

1

**Comment by Vanessa219** [comment]
保存查询条件是会把搜索内容一起保存的，因为搜索内容也是查询条件的一部分。丢弃的话，还需要看一下其他用户的反馈。

**Comment by Vanessa219** [comment]
我先关闭了，有其他用户有同样的需求可继续添加评论。

**Comment by TCOTC** [comment]
如果查询条件的搜索内容为空，我觉得不需要清空已有的搜索内容，不然就太麻烦了

**Comment by Vanessa219** [comment]
为什么要保存为空，也许就是想空着。

**Comment by TCOTC** [comment]
就我而言，保存为空是不想将搜索文本替换为之前搜索的文本。

> 也许就是想空着

既然是搜索，那肯定不会需要空着，空着咋搜索

**Comment by V7kb** [comment]
> 就我而言，保存为空是不想将搜索文本替换为之前搜索的文本。
> 
> > 也许就是想空着
> 
> 既然是搜索，那肯定不会需要空着，空着咋搜索

是的。当保存为空时，对搜索来说，没有意义。我现在把保存为空作为更换搜索类型的方式。但问题在于需要重新输入关键词

**Comment by Vanessa219** [comment]
如果切换后发现当前输入框内容不符合，还是需要去清空的。这个需求再看看其他用户的反馈吧。

**Comment by niejianying** [comment]
> 如果切换后发现当前输入框内容不符合，还是需要去清空的。这个需求再看看其他用户的反馈吧。

希望切换查询条件时保留搜索框的文本!

**Comment by Temacc0531** [comment]
我也不是很需要把输入框文本作为查询条件保存
