### ISSUE TITLE
macOS版本安装Whiteboard 挂件后，光标焦点在文档中时，Option + Y 切换全屏功能失败，在Windows版本中切换全屏功能正常

### ISSUE THREAD

**Issue by entps** [siyuan-note/siyuan#11259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

macOS版本安装Whiteboard 挂件后，光标焦点在文档中时，Option + Y 切换全屏功能失败，在Windows版本中切换全屏功能正常

### Expected result

macOS版本安装Whiteboard 挂件后，光标焦点在文档中时，Option + Y 切换全屏功能失败，在Windows版本中切换全屏功能正常

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

macOS版本安装Whiteboard 挂件后，光标焦点在文档中时，Option + Y 切换全屏功能失败，在Windows版本中切换全屏功能正常

**Comment by TCOTC** [comment]
也可以向挂件仓库反馈：https://github.com/BryceAndJuly/Whiteboard

**Comment by entps** [comment]
已反馈，但这插件应该是正常的，我遇到的很多都是mac版有问题，但windows版就没问题。



---- 回复的原邮件 ----
| 发件人 | Jeffrey ***@***.***> |
| 日期 | 2024年05月05日 16:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [siyuan-note/siyuan] macOS版本安装Whiteboard 挂件后，光标焦点在文档中时，Option + Y 切换全屏功能失败，在Windows版本中切换全屏功能正常 (Issue #11259) |

也可以向挂件仓库反馈：https://github.com/BryceAndJuly/Whiteboard

**Comment by entps** [comment]
已反馈过，说是思源笔记方面有问题，Windows版正常


在 2024年5月5日 16:44，Jeffrey ***@***.***> 写道：


也可以向挂件仓库反馈：https://github.com/BryceAndJuly/Whiteboard

**Comment by 88250** [comment]
> 已反馈过，说是思源笔记方面有问题

具体是什么问题？

**Comment by Vanessa219** [comment]
是不是 Mac 不支持，我没有找到相关的快捷键。你试一下文档页签中的 alt+y 是否有作用。
<img width="724" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/d340bf7b-00f5-43b8-aabd-7a0a81427adf">

**Comment by TCOTC** [comment]
Windows 有全屏快捷键，Mac 不知道：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1e0632ca-35c2-4686-95e2-f2add6186f23)

**Comment by entps** [comment]
Windows Alt + Y，macos option + Y



---- 回复的原邮件 ----
| 发件人 | Jeffrey ***@***.***> |
| 日期 | 2024年05月06日 11:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [siyuan-note/siyuan] macOS版本安装Whiteboard 挂件后，光标焦点在文档中时，Option + Y 切换全屏功能失败，在Windows版本中切换全屏功能正常 (Issue #11259) |

Windows 有全屏快捷键，Mac 不知道：

image.png (view on web)

**Comment by Vanessa219** [comment]
这个只是编辑器下的，不是全局的。除文档外的页签都需要自己监听。如果是文档页签无法全屏才是思源本身的 bug。

**Comment by entps** [comment]
这是macOS的全屏切换


在 2024年5月6日 11:05，Jeffrey ***@***.***> 写道：


Windows 有全屏快捷键，Mac 不知道：
image.png (view on web)

**Comment by Vanessa219** [comment]
思源内部对 `⌥Y` 进行了实现，如果页签插件需要的话是要插件自己来实现的。
