### ISSUE TITLE
数据库形成异常的双向关联

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11251]
### 数据库形成异常的双向关联

测试用的文档：[关联测试文档.sy.zip](https://github.com/siyuan-note/siyuan/files/15210387/sy.zip)

正常情况：**双向关联会创建一个新的关联列**：

![正常2](https://github.com/siyuan-note/siyuan/assets/78434827/9ee51d75-5ee9-45e0-8432-423508822966)

异常情况 1 ：**双向关联关联了已有的关联列，而不是创建一个新的关联列**：

![关联3](https://github.com/siyuan-note/siyuan/assets/78434827/e3459e67-34df-46f5-927c-f7cea3ce649e)

异常情况 2 ：**形成了一对二的双向关联**：

![关联2](https://github.com/siyuan-note/siyuan/assets/78434827/c8369cdd-c82c-428f-8fc1-e78bd8d2502e)

异常情况 3 ：**关联同一个条目两次**：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/57977493-869d-4143-8a65-0ff1821ff9a1)

关联了两次同一个条目的文档：[BUG文档.sy.zip](https://github.com/siyuan-note/siyuan/files/15210402/BUG.sy.zip)

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/11250 中调整了一下，应该是同一个问题。

**Comment by TCOTC** [comment]
刚刚复现了关联同一个条目两次：

![重复条目](https://github.com/siyuan-note/siyuan/assets/78434827/83f529b1-98f8-4227-9dcd-d7e3c1b26a6e)

**Comment by TCOTC** [comment]
> 异常情况 1 ：**双向关联关联了已有的关联列，而不是创建一个新的关联列**

这个还是有：

文档：[关联测试文档2.sy.zip](https://github.com/siyuan-note/siyuan/files/15217753/2.sy.zip)

![关联](https://github.com/siyuan-note/siyuan/assets/78434827/18dc7699-6a52-4816-b8cc-3f88e388b54d)

**Comment by 88250** [comment]
异常情况 1  我这里重现不了，你是使用新库测试的吗？

**Comment by 88250** [comment]
异常情况 3 ：关联同一个条目两次

我这里也还是重现不了，使用新库测试看看。

**Comment by TCOTC** [comment]
> 异常情况 1 我这里重现不了，你是使用新库测试的吗？

是用新建的数据库测试的

**Comment by TCOTC** [comment]
这次是用新建的工作空间测试的：

https://github.com/siyuan-note/siyuan/assets/78434827/1a6ebda7-e0f3-48d8-8c6d-3bf598c678f3

**Comment by 88250** [comment]
多谢，稍后再改改。

**Comment by 88250** [comment]
我们关闭这个 issue 了，如果还有问题麻烦跟帖，多谢。

**Comment by TCOTC** [comment]
移除和添加都还有点异常：

![GUANL](https://github.com/siyuan-note/siyuan/assets/78434827/4f272c84-eedb-4fbd-806e-ae4f69aa0cc1)

**Comment by TCOTC** [comment]
上面的 GIF 中：

1. 移除时未能完全移除
2. 添加时会重复添加一个，然后被去重
3. 数据库 A 完全没变

文档：[测试文档.sy.zip](https://github.com/siyuan-note/siyuan/files/15237196/sy.zip)

**Comment by 88250** [comment]
@TCOTC 等 3.0.14-dev1 再试试，感谢测试。

**Comment by TCOTC** [comment]
@88250 我测试的时候应该已经包含了对这个 issue 的所有提交

https://github.com/TCOTC/siyuan/releases/tag/v3.0.14-dev001

**Comment by 88250** [comment]
@Vanessa219 再看看，还是有点问题
