### ISSUE TITLE
Improve backlink panel mention expansion configuration

### ISSUE THREAD

**Issue by enneaa** [siyuan-note/siyuan#11262]
反链面板增加反向提及默认最小化的选项

### In what scenarios do you need this feature?

反向链接比反向提及更重要，应该优先显示反向链接内容，现在反向链接部分只占了一半面积，完全不够显示。
建议反向提及默认最小化，需要的时候才点开。这也是logseq、obsidian 通行的做法，即默认隐藏反向提及，点击后展开。
![Screenshot_20240505-212713_SiYuan](https://github.com/siyuan-note/siyuan/assets/11749618/0320ac6f-9af2-4368-95b2-e110bbc49c0f)

### Describe the optimal solution

建议反向提及默认最小化，需要的时候才点击展开。

**Comment by TCOTC** [comment]
确实不怎么用提及，要是能配置就好了

**Comment by 88250** [comment]
这个逻辑才改过，短期内暂时不考虑再改变了，请参考 https://github.com/siyuan-note/siyuan/issues/11097

**Comment by TCOTC** [comment]
> 提及展开数设置为 0 时，不应关闭提及面板

要不增加一个「提及展开数设置为 -1 时，关闭提及面板」？

**Comment by 88250** [comment]
@TCOTC 似乎可行，等考虑看看。

**Comment by TCOTC** [comment]
可行的话两个都改改，然后多加半句文案：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/006bb138-6ade-4ac1-a6d9-e7bfd9dbe191)

**Comment by TCOTC** [comment]
@88250 还有我发现搜索「提及」的时候搜不到这个配置项：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9f3b1033-6fd2-4f16-8f4f-21a0e8c92227)

**Comment by 88250** [comment]
收到，这个下个版本加一下。

**Comment by 88250** [comment]
> 可行的话两个都改改，然后多加半句文案：
> 
> ![image](https://github.com/siyuan-note/siyuan/assets/78434827/006bb138-6ade-4ac1-a6d9-e7bfd9dbe191)

反链部分没有 收起 这个概念就不加了，只加 提及 -1 设置。
