### ISSUE TITLE
优化反链面板点击逻辑

### ISSUE THREAD

**Issue by enneaa** [siyuan-note/siyuan#11264]
### In what scenarios do you need this feature?

现在点击标题栏是展开，其实可以改为点击箭头展开和收拢，点击文档标题打开文档。就和在文档树里面的操作类似。这样操作更加精简，不需要 Ctrl➕ 点击了。
这样还是可以鼠标悬停打开悬浮小窗。

### Describe the optimal solution

- 点击反链面板中的文档标题栏直接打开该文档。
- 点击剪头展开和收拢。
- 鼠标悬停打开小窗。
- 去除Ctrl➕点击操作。
这样操作逻辑和文档树操作逻辑是一致的，点击文档标题打开文档，点击箭头展开子文档。

### Describe the candidate solution

其他和原来一样，点击反链面板反链文档标题栏还是展开和收拢，但是点击文档名称直接打开文档。

**Comment by TCOTC** [comment]
箭头超级难点的好吧

**Comment by enneaa** [comment]
> 箭头超级难点的好吧

一个按钮在那怎么会难点，很多操作不都是点击按钮。

**Comment by TCOTC** [comment]
文档树要点击箭头都很麻烦了，箭头不是更好的选择

**Comment by 88250** [comment]
这个之前就是箭头展开，后来改成整个标题展开的，不考虑改回去了，感谢反馈。
