### ISSUE TITLE
同步模式增加阿里云盘支持

### ISSUE THREAD

**Issue by dawnLyu** [siyuan-note/siyuan#11261]
### In what scenarios do you need this feature?

自己建立webdav还是麻烦，需要绑定域名，内网穿透等等。 可以支持阿里云盘支持，方便使用。

### Describe the optimal solution

应用‘纯纯写作’已经支持，说明是可以的。 阿里云盘也给了应用适配推荐，可以作为思源的app引流，双赢
https://writer.drakeet.com/backups   #纯纯写作方案引用

**Comment by TCOTC** [comment]
Duplicate of #10630
