### ISSUE TITLE
分隔线优化

### ISSUE THREAD

**Issue by mieyeaa** [siyuan-note/siyuan#11263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在标题下使用，会随着标题折叠，而折叠进去。

### Expected result

希望分隔线能有不被折叠进去选项。

### Screenshot or screen recording presentation

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
3.0.9
```

### Log file

...

### More information

.....

**Comment by TCOTC** [comment]
```
# 标题

内容

---（分隔线a）

内容

---（分隔线b）

# 标题
```

理想情况就是 分隔线b 不会被折叠起来

**Comment by 88250** [comment]
不考虑改变了，谢谢。
