### ISSUE TITLE
关于优化排版的文档

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11273]
### 关于优化排版的文档

「标签」是指行内标签吗？好像并不会被修改（也不应该修改）

「强调」是什么元素？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3a4c236e-f12d-450d-857f-980dbac5fe6e)

**Comment by TCOTC** [comment]
另外「高亮」应该是「标记」

**Comment by 88250** [comment]
感谢反馈，作如下调整：

![Uploading image.png…]()
