### ISSUE TITLE
给报错信息增加复制按钮 / 区分 `点击` 和 `选中文字` 的操作

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11275]
### In what scenarios do you need this feature?

点击后消失是正常的，但选中文字后不应该消失：

![提示](https://github.com/siyuan-note/siyuan/assets/78434827/7bb1920d-d4e2-4530-8ecb-e2e6eec6d692)

目前只能选中之后 `Ctrl+C` 然后再松开鼠标

### Describe the optimal solution

给报错信息增加复制按钮 / 区分 `点击` 和 `选中文字` 的操作

**Comment by Vanessa219** [comment]
划选后复制时候不消失，就不添加复制按钮了。

**Comment by TCOTC** [comment]
@Vanessa219 要是选择之后能按右键弹出菜单就好了（包含复制、全选）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fd7ff3bf-7ed8-433e-8d35-57f61b430945)

**Comment by TCOTC** [comment]
有点小问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2f352286-f5f7-44b8-b7bc-241f1a5c9618)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/22402ee2-293a-4221-90e7-a7930c0c3bd5)

**Comment by TCOTC** [comment]
@Vanessa219 希望在没有选中文本的情况下右键 `复制` 能自动全选后复制

![image](https://github.com/siyuan-note/siyuan/assets/78434827/63876552-4639-4675-8a8a-b011fc643927)
