### ISSUE TITLE
Improve responsiveness of code blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11274]
同时开启了 `代码块显示行号` 和 `代码块换行` 的代码块，在编辑器宽度改变后需要刷新

### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/78434827/81a12f84-7a30-41f4-9e5d-ef802afb4092)

要刷新一下行号才对：

![代码](https://github.com/siyuan-note/siyuan/assets/78434827/c90a0d1b-45ca-4d89-b9b0-1bff0bebfcc3)

### Describe the optimal solution

同时开启了「代码块显示行号」和「代码块换行」的代码块，在编辑器宽度改变后需要刷新

**Comment by TCOTC** [comment]
@Vanessa219 视频前半部分改变边距的时候代码块是不会变化的（只有里面的文本变化），但后半部分改变边距时会移动：

[代码.webm](https://github.com/siyuan-note/siyuan/assets/78434827/9c93b0e3-e33e-4a21-a4a8-fd6f712f685c)

**Comment by Vanessa219** [comment]
这个比较费性能，只能在确定不修改后进行统一计算。
