### ISSUE TITLE
请问假如 4G 空间用完了怎么办？ 

### ISSUE THREAD

**Issue by chrvip** [siyuan-note/siyuan#1127]
正式使用后图片比较多，估计一年不到就会用完的。
--------------
不是BUG，但是不知道归到哪一类，姑且归为BUG吧，也算一个潜在问题。

**Comment by 88250** [comment]
目前可以通过邀请用户订阅进行扩容，每邀请一个付费订阅用户后扩容 500M，后续应该会上线付费扩容。

我们鼓励离线使用，在线工作空间请不要作为主要使用场景，谢谢。

**Comment by chrvip** [comment]
我的主要场景是在办公室生产内容，然后在外面有使用内容的需求。目前的情况要用手机打开在线工作空间来使用了。

**Comment by 88250** [comment]
@chrvip 后续我们会提供移动端 APP，请关注 #1061
