### ISSUE TITLE
Two-way relation is invalid when related to the current database

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11278]
关联至当前数据库时，双向关联无效

#11233 ; 使用 v3.0.14-dev1

测试的文档：[测试.sy.zip](https://github.com/siyuan-note/siyuan/files/15222117/sy.zip)

使用双向关联的时候会隐藏，无法取消双向关联：

![shuagnxiang](https://github.com/siyuan-note/siyuan/assets/78434827/6524422c-059b-4806-9d04-02dd73f2a8a3)

并且实际上测试了发现是没有实现双向关联的：

[无效.webm](https://github.com/siyuan-note/siyuan/assets/78434827/446b9c5f-f466-449d-be89-ce7cdaa75920)

**Comment by Vanessa219** [comment]
当前数据库是可以进行双向关联的。如果双向关联过就不会再出现双向关联的选项了。

**Comment by TCOTC** [comment]
懂了

**Comment by TCOTC** [comment]
不对，如果已经双向关联了，那就应该显示，否则没办法取消双向关联：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e4df95e2-9a89-4510-b9a1-c5e07c0dca7e)

并且实际上测试了发现是没有实现双向关联的：

[无效.webm](https://github.com/siyuan-note/siyuan/assets/78434827/446b9c5f-f466-449d-be89-ce7cdaa75920)

**Comment by TCOTC** [comment]
@Vanessa219

**Comment by 88250** [comment]
在 Notion-like 中双向关联本库叫做“拆分”

Notion:

![image](https://github.com/siyuan-note/siyuan/assets/873584/26097869-8ac2-4e4e-8be2-950ef7e739bf)

我来 wolai：

![image](https://github.com/siyuan-note/siyuan/assets/873584/8c070c62-b8d4-4963-8f95-475a23cad9e1)

这种关联字段一旦建立就不允许取消关联了，并且删除字段的时候是一并删除之前自动创建的关联目标字段。

**Comment by TCOTC** [comment]
@88250 不一样啊，思源里的这个是完全无效：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/13336ab9-1ffb-4c9f-b7f7-0373f95047bd)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d90203ef-c2ce-4f7e-956a-b06058d07cfa)

**Comment by TCOTC** [comment]
> 这种关联字段一旦建立就不允许取消关联了

@88250 我试了一下 Wolai 是可以取消的（让其中一个关联列关联其他数据库，另一个关联列就取消关联了），但是取消之后会有 BUG ，估计是解决不了 BUG 才不允许取消的

**Comment by 88250** [comment]
抱歉抱歉，我刚刚忽略 无效 的问题了……

取消关联这个暂时还是不动了，逻辑有点复杂动了怕出问题。

**Comment by TCOTC** [comment]
@88250 刚刚又试了一下，Wolai 有一种安全的方法可以取消「拆分字段」，然后还可以重新「拆分字段」，说明不是实现不了：

[wolai.webm](https://github.com/siyuan-note/siyuan/assets/78434827/a7cb85fe-7415-4bed-9adc-a054588f63d0)

**Comment by 88250** [comment]
取消当前库双向关联 https://github.com/siyuan-note/siyuan/issues/11356
