### ISSUE TITLE
Tab键后内容自动变成代码块格式

### ISSUE THREAD

**Issue by Mannixhu** [siyuan-note/siyuan#1128]
### 描述问题 Describe the problem
输入Tab键后再输入的内容自动变成代码块格式

### 期待的结果 Expected result
输入Tab键后再输入的内容为默认格式

### 截屏或录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/16033328/104827895-0b254100-589e-11eb-8fbd-a604626d678a.mp4

### 版本环境 Version environment

* 版本 Version：0.6.1
* 操作系统 Operating system：macos11.1
* 浏览器（如果使用）Browser (if used)：mac客户端

### 日志文件 Log
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5825354/siyuan.log)

**Comment by 88250** [comment]
你好，这是 Markdown 语法的特性，谢谢反馈。
