### ISSUE TITLE
增加模板函数 `len`

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#11283]
### In what scenarios do you need this feature?

我翻了一下发现 Sprig 函数当中没有提供计算列表长度的功能。

### Describe the optimal solution

提供 len 函数，计算 `[]interface{}` 的长度。

https://pkg.go.dev/builtin#len

**Comment by TCOTC** [comment]
解决了？

**Comment by frostime** [comment]
> 解决了？

已经有了，我可能是哪里漏看了
![image](https://github.com/siyuan-note/siyuan/assets/27268127/7d8116d5-0d07-4d5d-8656-0e943ef7dc53)

**Comment by TCOTC** [comment]
https://www.topgoer.com/%E5%B8%B8%E7%94%A8%E6%A0%87%E5%87%86%E5%BA%93/template.html

我只看到这里有个 `len`：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3240babe-cf7d-4604-a627-b8e59be12ce1)

**Comment by frostime** [comment]
是的，这本身就是 Go 模板已经内置了的函数。
