### ISSUE TITLE
Improve sorting for `Add to Database`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11286]
改进将数据库条目批量添加到其他数据库时的顺序

### In what scenarios do you need this feature?

希望这样添加完之后的顺序是从 1 到 9 ，而不是从 9 到 1 ：

![顺序](https://github.com/siyuan-note/siyuan/assets/78434827/9f8b13a2-02f6-4945-a0a7-80265b6833d0)

### Describe the optimal solution

改为倒序添加 & 添加到末尾

**Comment by 88250** [comment]
添加是按正序添加的，添加到开头。

**Comment by TCOTC** [comment]
但是正序添加的话就跟原来展示的顺序不一样了

**Comment by 88250** [comment]
顺序是有点问题，稍后改进，谢谢。
