### ISSUE TITLE
快速打开数据库主键绑定文档的属性面板

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11284]
数据库添加 `属性` 字段类型

### In what scenarios do you need this feature?

数据库可以共享(自定义)属性；模板列只能读取，不能修改属性值。

所以需要一个 属性列 ，支持读取与修改(自定义)属性（纯文本）

p.s. 如果可行的话，希望也支持一下内置属性

### Describe the optimal solution

数据库添加 `属性` 字段类型。

更新主键时，属性也需要变更（比如更换绑定块时，属性要带过去）。

**Comment by Achuan-2** [comment]
查询块自定义属性就好了

**Comment by 88250** [comment]
自定义属性不考虑其他修改方式了，靠属性面板修改值，其他地方仅做读取，感谢提议。

**Comment by TCOTC** [comment]
现在还缺少一个 快速打开数据库主键绑定文档的属性面板 的办法

**Comment by TCOTC** [comment]
> 数据库可以共享(自定义)属性；模板列只能读取，不能修改属性值。

我觉得如果能有一个属性列的话，能提高数据库的上限。毕竟能让所有数据库共享属性，而关联列做不到

**Comment by 88250** [comment]
属性只能放在块上，但是数据库行可以不绑定块，有 `属性` 字段的话这里会有问题，很早以前的设计就是把所有字段都绑定到块属性的，后来发现逻辑上有问题就取消了。

**Comment by TCOTC** [comment]
我的想法是：没有绑定块时，属性列 等效于 文本列，绑定块之后再转换 & 取消绑定块时也转换

**Comment by 88250** [comment]
还有删除的情况的，并且要考虑双向的同步删除，仅仅为了实现修改，我觉得代价太大了，没有必要。

**Comment by TCOTC** [comment]
> 现在还缺少一个 快速打开数据库主键绑定文档的属性面板 的办法

那就看看这个。如果能解决这个问题的话我觉得也差不太多

**Comment by TCOTC** [comment]
比如 `Shift+Click` 条目前面的“块标”

![image](https://github.com/siyuan-note/siyuan/assets/78434827/70937ddc-95d1-4faf-aa90-aef7af3562f4)

**Comment by 88250** [comment]
@Vanessa219 考虑一下

**Comment by Vanessa219** [comment]
行上都有属性了，再打开属性面板会不会没有必要

**Comment by TCOTC** [comment]
> 行上都有属性了，再打开属性面板会不会没有必要

打开属性面板才能编辑自定义属性

**Comment by Vanessa219** [comment]
这个位置加一个打开属性面板？
<img width="685" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/a448e60e-78de-465a-b637-14c1b133638f">

**Comment by TCOTC** [comment]
可以是可以，但我感觉 `右键+两层菜单` 还是不够快，毕竟正常的块标只需要 `Shift+点击` 就可以打开属性面板了

**Comment by Vanessa219** [comment]
shift 冲突了。第一层的话可能会和属性冲突。

**Comment by TCOTC** [comment]
`Shift+点击` 在这里应该没有冲突吧：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ceec2915-fae4-412f-86b4-8d9336d0ffa3)

**Comment by Vanessa219** [comment]
都加吧。

**Comment by TCOTC** [comment]
从数据库打开的话，应该默认显示哪个呢？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/51ae4de0-3f03-4de2-ba49-f3a0c20023e6)

**Comment by 5kyfkr** [comment]
能不能把数据库属性页面弄成个面板在侧边栏展示？这样就不用纠结打开属性面板的操作了，直接选中那一行就显示对应的数据库属性

**Comment by 88250** [comment]
> 能不能把数据库属性页面弄成个面板在侧边栏展示？(现有的逻辑不动，多一个展示位置)这样就不用纠结打开属性面板的操作了，直接选中那一行就显示主键对应的数据库属性，我相信这个效果比一个个点击进去看好得多

和 https://github.com/siyuan-note/siyuan/issues/11371 是同一个需求吗？

**Comment by 5kyfkr** [comment]
> > 能不能把数据库属性页面弄成个面板在侧边栏展示？(现有的逻辑不动，多一个展示位置)这样就不用纠结打开属性面板的操作了，直接选中那一行就显示主键对应的数据库属性，我相信这个效果比一个个点击进去看好得多
> 
> 和 #11371 是同一个需求吗？

包括现在这个issue和以下这两个，感觉都是数据库属性展示便捷性的问题，我觉得最好的办法还是单独拉出来一个面板能在侧边栏显示
https://github.com/siyuan-note/siyuan/issues/11371
https://github.com/siyuan-note/siyuan/issues/11113

**Comment by TCOTC** [comment]
> > > 能不能把数据库属性页面弄成个面板在侧边栏展示？(现有的逻辑不动，多一个展示位置)这样就不用纠结打开属性面板的操作了，直接选中那一行就显示主键对应的数据库属性，我相信这个效果比一个个点击进去看好得多
> > 
> > 和 #11371 是同一个需求吗？
> 
> 包括现在这个issue和以下这两个，感觉都是数据库属性展示便捷性的问题，我觉得最好的办法还是单独拉出来一个面板能在侧边栏显示，现有的逻辑不变，多个展示的位置 #11371 #11113

大概就是让属性面板支持三种形态：可钉住的浮窗、页签、动态侧边面板

**Comment by 88250** [comment]
@5kyfkr @TCOTC 浮窗和页签似乎不是那么紧要，主要是有个侧栏面板应该就够用了。比如数据库行无论是否绑定了块，只要光标位于某一行，这个面板就竖向显示这一行的所有字段（某些字段除外，比如行号），和现在的 属性面板 - 数据库 效果一致？

**Comment by 5kyfkr** [comment]
> 大概就是让属性面板支持三种形态：可钉住的浮窗、页签、动态侧边面板

我的拉出指的是界面单独拿出来加到侧边栏就行，有现在的属性界面和侧边栏面板就行

**Comment by 5kyfkr** [comment]
> @5kyfkr @TCOTC 浮窗和页签似乎不是那么紧要，主要是有个侧栏面板应该就够用了。比如数据库行无论是否绑定了块，只要光标位于某一行，这个面板就竖向显示这一行的所有字段（某些字段除外，比如行号），和现在的 属性面板 - 数据库 效果一致？

没错，就是这个意思

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/11371 中继续讨论。
