### ISSUE TITLE
关联列支持关联多个数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11288]
### In what scenarios do you need this feature?

理想的情况是这样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7952de92-3ada-48d9-8f1d-78974d1e22dd)

但目前只能这样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/430afdc3-e100-4bfa-829d-a193aa4e58c0)

### Describe the optimal solution

关联列支持关联多个数据库

**Comment by 88250** [comment]
关联只能关联到一个库，无法关联多个库。
