### ISSUE TITLE
用户指南需要改进首页和目录结构

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11293]
### In what scenarios do you need this feature?

新用户不懂使用文档树，所以首页需要更直观。

说实话我最开始用思源的时候看到这个页面真的感觉不知道怎么下手：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/70d70491-2262-4308-a19e-f18ac4a458b9)

### Describe the optimal solution

把文档都平铺在首页：

比如 Notion https://www.notion.so/help/reference

![image](https://github.com/siyuan-note/siyuan/assets/78434827/28d01e26-fecc-4828-b687-3673b994666f)

比如 FlowUs https://flowus.cn/share/e68380be-23cf-42c4-9b95-23a52713213d

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bc2ec5d3-82f3-4815-8fd5-62f6cfab9cce)

比如 Wolai https://www.wolai.com/wolai/xhqeop8UHpVTMUSVmgz8nq

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7ff24eed-454c-4816-bbef-0d8ff6abf54f)

### Describe the candidate solution

最好能顺便改一下用户指南笔记本的目录结构，把重要的文档放到第一层，让用户不需要展开子文档就能看到与点击打开

**Comment by snoopydai** [comment]
那个块命名“社区”的位置一开始让我感到奇怪。我还以为这是 bug，怎么会跑到那个地方去。点开之后就只是弹出一个弹窗，不知道作用是什么。

直到我后来再次点开这个东西后，删掉“社区”文字，看到了提示的文字“为该快设置命名。。。”，我才知道原来这个是快命名。

这是一个需要优化的点。可能是快命名的样式要优化，或者点开这个东西后显示的使用指引要优化。

**Comment by 88250** [comment]
欢迎 PR 改进首页导航，目录结构的话暂时不调整了。
