### ISSUE TITLE
Improve editor preview

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11295]
### In what scenarios do you need this feature?

目前从编辑模式切换为预览模式，
文档显示默认是占满编辑器宽度的
![Clip_2024-05-07_17-35-14](https://github.com/siyuan-note/siyuan/assets/60436214/af20e8af-6b3c-4b1c-9de7-6bc60d7f498e)
要点击下desktop按钮，这个编辑器宽度才正常显示
![Clip_2024-05-07_17-35-30](https://github.com/siyuan-note/siyuan/assets/60436214/9cab04d3-b6e2-4769-bddb-18f8daf59629)

### Describe the optimal solution

建议电脑端打开预览模式，自动以desktop样式渲染

### Describe the candidate solution

无

**Comment by TCOTC** [comment]
@Vanessa219 `Improv editor preview` → `Improve`
