### ISSUE TITLE
Improve HTML code block clipping

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11296]
### 某网页无法剪藏代码

https://mr-houzi.com/2022/09/16/%E4%BB%A4%E4%BA%BA%E5%9B%B0%E6%83%91%E7%9A%84-Go-time-AddDate/

![image](https://github.com/siyuan-note/siyuan/assets/78434827/97db1aa2-54ae-4996-81df-10b290f67357)

里面的代码剪藏出来是：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8255cd16-5c0b-44ad-9e22-bb1c2df77316)

不知道能不能适配

**Comment by luo-chuan** [comment]
你可以装一个简悦插件，官方插件效果不好时，用简悦试试。
我刚刚试了，简悦的效果很不错。

**Comment by luo-chuan** [comment]
简悦要装这个子插件
![图片](https://github.com/siyuan-note/siyuan/assets/33930736/8434e943-ac4c-4c0a-8ad5-db589531b100)
动作里有这一项：
![图片](https://github.com/siyuan-note/siyuan/assets/33930736/dbdfe2ca-63ba-43e3-a57d-607beb764bed)
把这几项设置好后，点击导出即可。
![图片](https://github.com/siyuan-note/siyuan/assets/33930736/41ed7790-276d-4101-8e6a-89f004152632)

**Comment by 88250** [comment]
附加 https://ld246.com/article/1715239079172 一并改进。
