### ISSUE TITLE
Improve exit application on iOS

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11292]
改进移动端 `未正常退出` 提示

### 改进移动端提示文案

有的用户弹出这个是因为思源被杀后台了，建议补充一句“允许后台运行”“忽略电池优化”之类的话

![26bb005502df226e8a1ce1ee206f3e2d](https://github.com/siyuan-note/siyuan/assets/78434827/11780f35-3335-4d71-9930-7e8ff1108fad)

**Comment by 88250** [comment]
这个如果是 iOS 上弹出的话是个 bug，目前还在想怎么解决。

**Comment by 88250** [comment]
我这里目前在 iOS 上重现不了了，先关闭了。
