### ISSUE TITLE
内容快动态查询·可视化——不知道是否已经列入开发计划？

### ISSUE THREAD

**Issue by PayneSnow** [siyuan-note/siyuan#1129]
D大，您好！期待在正式版推出后，将 内容快动态查询·可视化。已有的动态查询需要输入语法，对于非程序员而言，还是比较麻烦，不好上手。
我可能描述不准确。下面以同类产品截图说明。这个功能对用户很有帮助。思源笔记有自己的设计理念，但是也期待能借鉴其他roam应用的优点，自动汇总[[主题]]内容至同一个页面。这样每次我只需要打开 daily note输入即可，隔一段时间我再将引用内容转移、汇总、整理至[[主题]]中。
logseq
![截屏2021-01-17 11 35 24](https://user-images.githubusercontent.com/51922806/104830262-19805680-58b8-11eb-9224-ad467775b3d2.png)
![截屏2021-01-17 11 32 49](https://user-images.githubusercontent.com/51922806/104830228-bd1d3700-58b7-11eb-9cb2-e0d4ced4d29c.png)

**Comment by PayneSnow** [comment]
目前虽然已经购买思源会员，但是使用很少。等待成熟后再操作。如果提的问题唐突，见谅

**Comment by 88250** [comment]
我们一直在想如何简单呈现，交互细节还需要考虑，谢谢。
