### ISSUE TITLE
Wrap text by characters rather than replace

### ISSUE THREAD

**Issue by ens100** [siyuan-note/siyuan#113]
Hi,

Is there any chance to have SiYaun do something similar like Obsidian does when adding for example `, ((, [[ ? This is so that the text is wrapped by these characters rather than replaced.

![test](https://user-images.githubusercontent.com/67863060/94365751-4d4a2d00-00cb-11eb-9031-cbf861406f77.gif)

Thank you so much and great work!

**Comment by 88250** [comment]
In SiYuan, the block reference is not located by the document/title, but needs to use `[[` to trigger the search, and finally use the definition block id. So I think wrapping with `[[` marker the selected text is not very useful.

**Comment by ens100** [comment]
Hi, thank you very much for looking into this. I will close this issue,
