### ISSUE TITLE
关于文档树的最大列出数优化建议

### ISSUE THREAD

**Issue by h9485910** [siyuan-note/siyuan#11305]
### In what scenarios do you need this feature?

今天研究了下文档树最大列出数，才发现只会加载设置的数量，超过了数量就完全不加载了，虽然是出于对性能的考虑，但是这会导致文档树加载不完全的问题，要么就一下子设置个特别大的数字，但是这样导致一下子加载太多也会卡顿，我试着把这里设置的数字清空，重建索引后就有个默认值512.

### Describe the optimal solution

当设置的最大列出数小于当前要展开的文档树时，按最大列出数展示，但是要在最下面的文档处提供个按钮来继续加载，或者是鼠标滑轮滑动触发继续加载，继续加载可以一次加载10条50条或者最大列出数的数量，这样一批批加载，既能稍微缓解一次加载过多导致的性能问题，也免得文档加载不全。

### Describe the candidate solution

我觉得要么提供-1或者0作为全部加载，要么提供分批懒加载，目前只加载指定数量剩下的不加载不是一个较好的方案

**Comment by TCOTC** [comment]
赞同

**Comment by 88250** [comment]
分页加载不考虑了，这个还是让用户自行决定设置数量吧，就像你说的，可以设置一个很大的数字，这样就能一次性加载了，谢谢。
