### ISSUE TITLE
按TAB键缩进段落后再编辑,该段落变为代码内容

### ISSUE THREAD

**Issue by yzg100** [siyuan-note/siyuan#1130]
问题：
对段落按TAB键缩进后，如编辑该段落内容,段落内容后变为代码内容
![按TAB键后再修改BUG.gif](https://i.loli.net/2021/01/17/1u89ncLEI3FiekS.gif)
录屏：https://sm.ms/image/1u89ncLEI3FiekS

**Comment by 88250** [comment]
你好，请参考 https://github.com/siyuan-note/siyuan/issues/1128
