### ISSUE TITLE
新建文档时临时解除该文档的只读

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11306]
### In what scenarios do you need this feature?

[只读模式下，新建文档不可编辑，要解锁 - JeffreyChen 的回帖 - 链滴](https://ld246.com/article/1714830013629/comment/1714887040576#comments)

目前在全局只读模式下，关闭文档再打开和重启思源就会把文档变回只读，这个不用变；

只需要在全局只读模式下增加一个逻辑：新建文档时临时解除该文档的只读

### Describe the optimal solution

新建文档时临时解除该文档的只读

**Comment by 88250** [comment]
和这个重复了吗？ https://github.com/siyuan-note/siyuan/issues/11302

**Comment by TCOTC** [comment]
Duplicate of #11302
