### ISSUE TITLE
代码内容过长、过宽不要出滚动条；文件树用户可自定义排序

### ISSUE THREAD

**Issue by yzg100** [siyuan-note/siyuan#1131]
1.代码内容过长、过宽时，在编辑器中出现滚动条。
**希望代码过长时，高度可自适应；过宽时自动换行。（可由用户自定配置也行）**

录屏图像中，可明显看到右侧同时出现了两条竖向滚动条。
![滚动条.gif](https://i.loli.net/2021/01/17/bKV1xEtWuyCh2zw.gif)
录屏：https://sm.ms/image/bKV1xEtWuyCh2zw
---------------------------------------------------------------------------------------------------------

2.文件树用户可自定义排序，
当前文件树中的文章是根据名称自动排序。有时并不希望使用文件名的排序方式，虽然可以加了1.2.3. 。。。。前缀来排序文章，但超过10以后，还是会导致1和10排到了一起。
**希望可拖放移动文章顺序，并保存该文章顺序。**

![QQ截图20210117134133.png](https://i.loli.net/2021/01/17/6Dn4KZoXqU3cAxE.png)
截图：https://sm.ms/image/6Dn4KZoXqU3cAxE

3.插入的图片可用户配置默认居左或居中放置。

**Comment by 88250** [comment]
你好

* 代码块折行和行数配置请关注 https://github.com/siyuan-note/siyuan/issues/708
* 文件自定义排序暂时实现不了，之前已经有过提议 https://github.com/siyuan-note/siyuan/issues/662
* 图片默认是局左的，如果单独占一行的话会自动居中
