### ISSUE TITLE
The line number field no longer appears in the database attribute panel

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11319]
### 属性面板数据库行号列无法显示

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2c434637-72c4-490c-9ceb-82396330d0b8)

**Comment by 88250** [comment]
属性面板中不应该显示行号，因为行号仅在表格视图中存在，其他视图可能没有行这个概念。所以后续会去掉属性面板中显示行号，感谢反馈。

**Comment by TCOTC** [comment]
> 去掉属性面板中显示行号

这样的话就不能在属性面板里调整行号列的位置了

**Comment by 88250** [comment]
呃，这倒是，但是也没啥更好的办法了。
