### ISSUE TITLE
图片重命名问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11313]
### 图片重命名问题

明明只有这个文档插入了这张图片，但重命名之后感觉像是修改了一大堆文件：

![图片](https://github.com/siyuan-note/siyuan/assets/78434827/c7842f8a-7127-4684-8e0d-4131576dc7e1)

**Comment by 88250** [comment]
没有重命名其他的图片，之所有有个进度条是因为需要遍历所有文档，看是否存在相同资源文件名需要重命名。

可以对比一下快照确认。

**Comment by Achuan-2** [comment]
图片重命名的操作能不能在后台进行，而不是进度条阻止用户编辑内容。

**Comment by 88250** [comment]
重命名图片可能需要修改文档内容的，不阻塞编辑的话可能会导致数据不一致。

**Comment by TCOTC** [comment]
> 没有重命名其他的图片，之所有有个进度条是因为需要遍历所有文档，看是否存在相同资源文件名需要重命名。

1. 遍历的文档包括已关闭的笔记本吗？
2. 我感觉这些文件名没必要显示，都是一闪而过的。不如搞个进度条

**Comment by 88250** [comment]
1. 包括
2. 稍后稍微调整一下推送显示的信息，加载过程就不推送了，只推送一开始的 "正在重命名..." 和真正命中的 "正在保存文档 [%s]..."

**Comment by Achuan-2** [comment]
> 重命名图片可能需要修改文档内容的，不阻塞编辑的话可能会导致数据不一致。

我觉得阻塞本篇文档的编辑就好了，其他文档的处理可以放在后台处理（为了保险，可以将查询到的文档先临时改为只读状态），否则只是重命名一张图片，却要等待很久时间，体验不好
