### ISSUE TITLE
光标位于标题(heading)前面时空格无效

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 光标在这里时，空格无效
<img width="483" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/3f27d1c0-033c-42c3-97f3-0dc2641f1a10">

2. 把`#     ddddd`粘贴到思源里，前面的空格都不见了

### Expected result

.

### Version environment

```markdown
- Version: 3.0.13
- Operating System: macOS 13.6.6
- Browser (if used): 
```

### Log file

.

**Comment by 88250** [comment]
这是正常的，`#` 后面只需要一个空格就能够形成标题，思源会自动处理。

**Comment by LoneFireBlossom** [comment]
？敲空格键没反应怎么能说是正常的呢？

**Comment by LoneFireBlossom** [comment]
把多个空格处理成一个空格又怎么能说是正常呢，这样处理的依据是什么

**Comment by 88250** [comment]
正常的，Markdown 语法如此。

**Comment by LoneFireBlossom** [comment]
> 正常的，Markdown 语法如此。

那这样的显示就是不合规的吗？
<img width="485" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/563625fb-6944-4238-98f0-d2bfbccb159f">

**Comment by 88250** [comment]
思源会自动格式化这种情况，把多余的空格去掉，或者说你如果想保留这些空格，思源实现不了。

**Comment by LoneFireBlossom** [comment]
> 思源会自动格式化这种情况，把多余的空格去掉，或者说你如果想保留这些空格，思源实现不了。

可是这就是思源里的截图啊，没格式化啊

**Comment by TCOTC** [comment]
> > 思源会自动格式化这种情况，把多余的空格去掉，或者说你如果想保留这些空格，思源实现不了。
> 
> 可是这就是思源里的截图啊，没格式化啊

你在 dddd 前面按一下空格试试

**Comment by 88250** [comment]
编辑过程中自动格式化了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月9日(周四) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 光标位于标题(heading)前面时空格无效 (Issue #11314)




  
思源会自动格式化这种情况，把多余的空格去掉，或者说你如果想保留这些空格，思源实现不了。
  
可是这就是思源里的截图啊，没格式化啊

**Comment by LoneFireBlossom** [comment]
归根结底我是觉得markdown这个规则根本就不值得遵守，非要说要遵守的话，那思源也没完全遵守啊，比如多行空行只渲染成一行就没遵守。所以为什么要遵守这种不符合常规思路的规则呢

**Comment by TCOTC** [comment]
> 多行空行只渲染成一行

GitHub 不是这样的

**Comment by 88250** [comment]
能遵循尽量遵循，标题开头空格好像场景不多。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月9日(周四) 中午12:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 光标位于标题(heading)前面时空格无效 (Issue #11314)




 
归根结底我是觉得markdown这个规则根本就不值得遵守，非要说要遵守的话，那思源也没完全遵守啊，比如多行空行只渲染成一行就没遵守。所以为什么要遵守这种不符合常规思路的规则呢

**Comment by LoneFireBlossom** [comment]
我找了两个在线markdown编辑器，段落里的多个空格也只能渲染成一个空格，思源也没遵守啊

<img width="1463" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/5ef04982-5789-4163-bf73-dd8310c09cf4">
<img width="1666" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/df14659a-dde6-4ac7-bb41-3b2ff08e4063">

**Comment by LoneFireBlossom** [comment]
我没有耐心看markdown原版规则的发展讨论。在我看来：

1. markdown将多个空行渲染成一个空行
2. markdown将多个空格渲染成一个空格
    1. markdown将标题开头的`#      dddd`中的空格全部消失

是遵循一套设计理念。不能只遵循其中一个，其它的不遵循，这样是割裂的

**Comment by TCOTC** [comment]
@88250 允许在标题开头输入空格会产生什么问题吗？

**Comment by 88250** [comment]
我也不太确定....



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年5月9日(周四) 中午12:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 光标位于标题(heading)前面时空格无效 (Issue #11314)




 
@88250 允许在标题开头输入空格会产生什么问题吗？
