### ISSUE TITLE
Improve doc tree modification time display

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11327]
更具体的更新时间提示

https://ld246.com/article/1715244260419

需要同时显示粗略的时间和精确的时间：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/184b374d-c4a0-4a17-ab73-703f4c307308)

**Comment by TCOTC** [comment]
感觉可以在中间这里再插入一行：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ee61c4c8-839c-4430-8dc1-0a8c8d534e14)

**Comment by 88250** [comment]
这样如何？

![image](https://github.com/siyuan-note/siyuan/assets/873584/45cfaca4-ccad-4b9b-a2d3-7ceccd2c5d35)

**Comment by TCOTC** [comment]
感觉还行，把括号换成逗号怎么样？

2024-05-09 15:51:14, 1 小时以前

**Comment by TCOTC** [comment]
括号跟数字挨着不太好看

![image](https://github.com/siyuan-note/siyuan/assets/78434827/15bd5a5b-9fa8-49b3-a57c-7c3d6706f40b)

**Comment by TCOTC** [comment]
感觉创建时间后面也可以加一下粗略时间，只有一行有粗略时间感觉有点怪

**Comment by TCOTC** [comment]
「以前」的「以」我觉得也可以去掉

> 在中文表达中，“1小时前”和“1小时以前”这两个表述在语义上是相同的，都表示当前时间点之前的1小时。在日常交流中，两者都可以使用，没有绝对的优劣之分。不过，从语言习惯和简洁性来看，“1小时前”可能更为常见和推荐，因为它更简洁明了，符合现代汉语的表达习惯。而“1小时以前”虽然也是正确的表达，但听起来略显正式或书面化，可能在口语交流中不如“1小时前”自然。
>
> 总的来说，两者都是正确的表达方式，选择哪一个更多取决于个人习惯和语境。在正式文书或书面语中，两者均可接受；在口语交流中，“1小时前”可能更为普遍。

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/c67f6473-8788-4b38-b49f-a9f0b741b6c7)

**Comment by snoopydai** [comment]
我觉得还要留意一下，当翻译成别的语言的时候，这么多内容所占的横向面积会不会很大。

**Comment by TCOTC** [comment]
> ##### 修改时间（Modification Time）
> 
> - **含义**：通常指的是某个数据或文件最后一次被修改的时间。这里的“修改”通常指的是内容上的变更，比如文本编辑、数据更改等。
> - **适用场景**：在文件系统中，这个时间戳用于指示文件内容的最后更改时间。在数据库或版本控制系统中，它可能用于记录某个记录或文档的最后编辑时间。
> 
> ##### 更新时间（Update Time）
> 
> - **含义**：通常指的是某个数据或文件最后一次被更新或重新计算的时间。这里的“更新”可能包括内容的修改，也可能包括状态的改变、属性的更新等。
> - **适用场景**：在数据库中，更新时间可能用于记录某个记录的任何类型的变更，包括状态更新、属性更新等。在软件更新或数据同步的上下文中，更新时间用于指示软件或数据的最新状态。

**Comment by TCOTC** [comment]
> 我觉得还要留意一下，当翻译成别的语言的时候，这么多内容所占的横向面积会不会很大。

应该不需要考虑，文档名长得多

**Comment by 88250** [comment]
@TCOTC https://github.com/siyuan-note/siyuan/issues/11327#issuecomment-2102277931 统一显示为 “更新时间”

@snoopydai 法语可能会折行

![image](https://github.com/siyuan-note/siyuan/assets/873584/3ca73325-a859-4f3d-b579-388845f4dcf6)

![image](https://github.com/siyuan-note/siyuan/assets/873584/2228ac73-95de-4d16-8c48-871d5dce8fb3)

**Comment by 88250** [comment]
暂时就这样吧。

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/commit/bb918f48797b41d7bcf4eed337167f4d91230bf5
