### ISSUE TITLE
移动端启动时同步增加自动重连

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11329]
### In what scenarios do you need this feature?

如下图，移动端有时网络没有电脑端那么稳定，我十次用流量启动感觉有三四次会遇到这个弹窗，但是再点一下立即同步又可以正常同步，我用的是七牛云的s3，不清楚判定逻辑，我wifi信号也会有几率出现，但桌面端只有完全断网才遇到过，希望能优化移动端启动时网络连接判定逻辑
![f734d399d782bd5f90bfeab9214fd21](https://github.com/siyuan-note/siyuan/assets/63196026/c6444d2d-e786-41ea-aca2-7811630aa1ff)

### Describe the optimal solution

建议多次尝试重连，不是第一次连接失败就报错。

**Comment by 88250** [comment]
* 对于网络连接是否正常的判断目前是重试 3 次，具体实现见 kernel/util/net.go 中的 isOnline 函数
* 对于下载/上传数据目前是重试 1 次，具体实现见 httpclient 库

**Comment by 5kyfkr** [comment]
> * 对于网络连接是否正常的判断目前是重试 3 次，具体实现见 kernel/util/net.go 中的 isOnline 函数
> * 对于下载/上传数据目前是重试 1 次，具体实现见 httpclient 库

网络连接判断如果不正常也会出现同步数据失败吧？那这个重试

> * 对于网络连接是否正常的判断目前是重试 3 次，具体实现见 kernel/util/net.go 中的 isOnline 函数
> * 对于下载/上传数据目前是重试 1 次，具体实现见 httpclient 库

看了下，里面那个checkURL是什么，s3服务商的地址吗？
