### ISSUE TITLE
改进侧栏按钮右键菜单布局

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11324]
### In what scenarios do you need this feature?

每次移动的时候都要认真看清楚，但偶尔还是会移错位置，我觉得可以改一下布局：

分成两列，左侧的放左边，右侧的放右边

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c8aeb2f0-edc4-4453-9674-df662541fc29)

### Describe the optimal solution

改进侧栏按钮右键菜单

**Comment by Vanessa219** [comment]
这个调整了还是需要细看，有个相关的拖拽的 issue，等后续支持了，也许好一点了。

**Comment by TCOTC** [comment]
如果这个布局能调整一下的话，我都能无脑点了。6个位置都是对应了方向的

**Comment by shuojie819** [comment]
能改成ob那样的随意拖拽就好了😁

**Comment by 88250** [comment]
> 能改成ob那样的随意拖拽就好了😁

https://github.com/siyuan-note/siyuan/issues/10247

**Comment by Vanessa219** [comment]
这个就关闭了，使用拖拽吧。
