### ISSUE TITLE
debian10 不支持了吗，3.x的linux在debian10拉不起来了

### ISSUE THREAD

**Issue by wenfer** [siyuan-note/siyuan#11326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

拉起直接报错
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed

![截图_siyuan_20240509154916](https://github.com/siyuan-note/siyuan/assets/16834499/bd246b8d-0c32-4eff-9e28-ab1775f69333)

![image](https://github.com/siyuan-note/siyuan/assets/16834499/5c0d5fbe-abc5-4899-975f-74fa6526cfe5)

### Expected result

正常拉起

### Version environment

```markdown
- Version: 3.0.13
- Operating System:  deepin 20.9 
- Browser (if used):  chrome
```

### Log file

![截图_选择区域_20240509154955](https://github.com/siyuan-note/siyuan/assets/16834499/797a2a29-3ee8-4284-b1e7-76afa4a86c30)

**Comment by wenfer** [comment]
ldd (Debian GLIBC 2.28.21-1+deepin-1) 2.28

**Comment by wenfer** [comment]
> 可能是 Electron 不支持了，请参考 https://askubuntu.com/questions/1395620/chrome-libva-error-usr-lib-x86-64-linux-gnu-dri-ihd-drv-video-so-init-failed

建议在环境要求中注明，并且关闭2.x  final版本的更新提示，不然体验太差了

**Comment by 88250** [comment]
可以在 设置 中关闭更新检查的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月10日(周五) 上午9:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] debian10 不支持了吗，3.x的linux在debian10拉不起来了 (Issue #11326)




  
可能是 Electron 不支持了，请参考 https://askubuntu.com/questions/1395620/chrome-libva-error-usr-lib-x86-64-linux-gnu-dri-ihd-drv-video-so-init-failed
  
建议在环境要求中注明，并且关闭2.x  final版本的更新提示，不然体验太差了
