### ISSUE TITLE
思源笔记上传图片优化

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11334]
### In what scenarios do you need this feature?

目前使用「上传资源文件到图床」
还是使用「分享到社区」功能，
都发现图片没有上传成功
可是在链滴查看笔记端的上传（「上传资源文件到图床」）和客户端上传（「分享到社区」）其实都是成功上传的，主要问题在于
我的文件名设置为`代码块限制最大高度、复制按钮不跟随滚动.gif`,但上传之后变为`代码块限制最大高度_复制按钮不跟随滚动.gif`，分享到平台的图片链接依然是`代码块限制最大高度、复制按钮不跟随滚动.gif`，导致图片无法被拉取

### Describe the optimal solution

建议笔记端的图片文件名处理和图床端一致

**Comment by 88250** [comment]
调整了一下，后续如果还遇到问题的话麻烦反馈，谢谢。

**Comment by Achuan-2** [comment]
ok，辛苦!
