### ISSUE TITLE
Feature：推荐在导入 Markdown 文档的时候解析一定的 YAML 元数据

### ISSUE THREAD

**Issue by yoghurtlee-thu** [siyuan-note/siyuan#11332]
### In what scenarios do you need this feature?

如题。

许多 Markdown 笔记软件（例如 Obsidian 和 Typora）都将元数据存储在文档顶部的 YAML 元数据区中，但是思源笔记并不能解析这样的元数据。 **我理解思源不是 Markdown 笔记软件，它不需要支持 YAML** ，但是如果能够解析某些通用的 YAML 元数据并将其转化为思源内部的属性和标签等，这对用户从其他软件迁移到思源无疑是很方便的。

As the title suggests.

Many Markdown note-taking software (such as Obsidian and Typora) store metadata in a YAML metadata block at the top of the document, but Siyuan cannot parse such metadata. **I totally understand that Siyuan is not a Markdown note-taking software and does not need to support YAML**, but if it could parse some common YAML metadata and transform it into Siyuan's internal attributes and tags, etc., it would undoubtedly be very convenient for users migrating from other software to Siyuan.

### Describe the optimal solution

解析文档顶部 YAML 数据块中的一些常见的元数据，例如 Date 和 tags。其余的元数据可以添加到自定义属性，或者依据用户的选择保留或者去除。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10878
