### ISSUE TITLE
the title of 不知道该叫什么的问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11342]
在文档完全加载的情况下，这个条会消失，就会没办法跳转到特定的块：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/142d230a-26fc-4488-9d10-2ec151bd01cf)

这个条除了用来跳转之外，还可以用来查看文档总块数，没了就看不了了

**Comment by 88250** [comment]
麻烦导出测试用 .sy.zip 以及给一下动态加载块数设置。

**Comment by TCOTC** [comment]
[写了七年文章，我把最重要的四项技能讲出来.sy.zip](https://github.com/siyuan-note/siyuan/files/15281183/sy.zip)

动态加载块数：256

**Comment by 88250** [comment]
抱歉，我记错了，这个是设计如此，不需要动态滚动条的时候（也就是不需要动态加载的时候）就不会显示了。

**Comment by TCOTC** [comment]
> 这个条除了用来跳转之外，还可以用来查看文档总块数，没了就看不了了

那这个需求怎么解决呢？

以及隐藏之后侧边就剩下两个箭头了也不好看

**Comment by 88250** [comment]
查看块数目前没有太多需求，暂时不考虑了。不动态加载的话就用正常的滚动条。
