### ISSUE TITLE
一个小问题：将标题块拖拽为页面后，其中的子标题，不能自动升级

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#11347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

比如将一个二级标题，拖拽为页面，其中的三级标题，仍为三级标题。
以前这个操作，三级标题，会升格为一级标题，包括其中的四级标题、五级标题，会提升为 二级标题、三级标题，这是很合理的

### Expected result

修复

### Version environment

```markdown
- Version: 3.0.13
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
> 一个二级标题，拖拽为页面，其中的三级标题，仍为三级标题

复现不了，我这里的三级标题会变成二级标题

**Comment by zhoutaosheng** [comment]
@TCOTC 看视频，视频中的标题 测试1
- 拖拽前，是二级标题
- 拖拽后，仍然是二级标题

https://github.com/siyuan-note/siyuan/assets/5683995/24636a9f-8acc-4ac0-a5f7-cb097354006b

**Comment by TCOTC** [comment]
> 看视频，视频中的标题 测试1
> 
> * 拖拽前，是二级标题
> * 拖拽后，仍然是二级标题
> 

这个没有问题，最高是二级标题

**Comment by TCOTC** [comment]
我没复现的是这句：

> 二级标题，拖拽为页面，其中的三级标题，仍为三级标题

**Comment by 5kyfkr** [comment]
> @TCOTC 看视频，视频中的标题 测试1
> 
> * 拖拽前，是二级标题
> * 拖拽后，仍然是二级标题
> 
>  1.mp4

现在的逻辑是，最高级别的标题拖拽变为文档标题，其他标题跟着提升，比如原来是3级和4级，拖拽后就3级变成文档名称，四级变2级标题。视频里是1级和2级，所以1级->文档标题，2级->2级标题，以前是1级变文档，2级变1级，现在比原来整体降了一级，因为像在obsidian中和其他markdown编辑器都是1级标题对应文档名称，从二级标题开始写

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/8f835211-10b7-4133-9b12-6e66cca1aa52)
这是ob里面的逻辑，markdown语法里是没有文档名这个语法的

**Comment by zhoutaosheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/63196026/329793838-8f835211-10b7-4133-9b12-6e66cca1aa52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDAyMjAsIm5iZiI6MTcxNTQzOTkyMCwicGF0aCI6Ii82MzE5NjAyNi8zMjk3OTM4MzgtOGY4MzUyMTEtMTBiNy00MTMzLTliMTItNmU2NmNjYTFhYTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE1MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmI1YmViMGUyYzdlOGEwN2E1MjI2ZDI5NmM2NjIyMWRiYjViZGZhYzQ5N2FkNjhjZmYzNjY1NzNlYmE2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.whClH7sAw2v2mk84p6DDxaiBHi2GKU-lh96H6wcN0nA) 这是ob里面的逻辑，markdown语法里是没有文档名这个语法的

但思源不是，在思源中，正常人都是从一级标题开始写的

**Comment by 5kyfkr** [comment]
> 但思源不是，在思源中，正常人都是从一级标题开始写的

所以我原来issue也建议提供切换开关，看D大能不能加回来吧

**Comment by TCOTC** [comment]
> > ![image](https://private-user-images.githubusercontent.com/63196026/329793838-8f835211-10b7-4133-9b12-6e66cca1aa52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDAyMjAsIm5iZiI6MTcxNTQzOTkyMCwicGF0aCI6Ii82MzE5NjAyNi8zMjk3OTM4MzgtOGY4MzUyMTEtMTBiNy00MTMzLTliMTItNmU2NmNjYTFhYTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE1MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NmI1YmViMGUyYzdlOGEwN2E1MjI2ZDI5NmM2NjIyMWRiYjViZGZhYzQ5N2FkNjhjZmYzNjY1NzNlYmE2MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.whClH7sAw2v2mk84p6DDxaiBHi2GKU-lh96H6wcN0nA) 这是ob里面的逻辑，markdown语法里是没有文档名这个语法的
> 
> 但思源不是，在思源中，正常人都是从一级标题开始写的

我是从二级标题开始写的，因为 Markdown 是这样

**Comment by zhoutaosheng** [comment]
明明markdown 告诉你 
- \# 是一级标题
- \#\# 是二级标题
- ....

现在非要不用一级标题，咱不用迁就ob吧

随便找一些git库中的readme文件，都存在一级标题的
https://github.com/dotnet/runtime
https://github.com/FFmpeg/FFmpeg
https://github.com/xmake-io/xmake

@88250 如果一定要迁就其他朋友的用法，建议做个开关吧

**Comment by 5kyfkr** [comment]
> 明明markdown 告诉你
> 
> * # 是一级标题
> * ## 是二级标题
> * ....
> 
> 现在非要不用一级标题，咱不用迁就ob吧
> 
> 随便找一些git库中的readme文件，都存在一级标题的 https://github.com/dotnet/runtime https://github.com/FFmpeg/FFmpeg https://github.com/xmake-io/xmake
> 
> @88250 如果一定要迁就其他朋友的用法，建议做个开关吧

这是纯属个人习惯问题，可以翻翻思源集市里插件和主题的readme，很多也有二级标题开始分类的，typora官网里面也是一级标题当主标题
![image](https://github.com/siyuan-note/siyuan/assets/63196026/fefb473f-00ca-4ef3-adc5-9ed10ee5286e)

**Comment by zhoutaosheng** [comment]
@88250 建议做个开关吧，有很多朋友，写markdown 时，会大量用 # 作为一级标题，因为
- 这比较直觉
- 可以让目录更简单一点，少想一点
- 输入时，每级目录，也要少输入一个 # 
思源之前拖拽后，最上级标题是一级标题，应该也是考虑到这部分用户的，希望增加一个开关

**Comment by 88250** [comment]
思源中还是建议从二级标题开始，比如 设置 - 导出 - 添加文档标题 这个就是添加的一级标题，如果不从二级标题开始的话也会有问题。

大部分情况下，正文中二级标题~六级标题已经足够用了，一级标题留下来做内置预设逻辑的顶层。

这个不考虑加开关了，感谢讨论。

**Comment by 5kyfkr** [comment]
> 思源中还是建议从二级标题开始，比如 设置 - 导出 - 添加文档标题 这个就是添加的一级标题，如果不从二级标题开始的话也会有问题。
> 
> 大部分情况下，正文中二级标题~六级标题已经足够用了，一级标题留下来做内置预设逻辑的顶层。
> 
> 这个不考虑加开关了，感谢讨论。

  添加文档标题 这个功能我觉得应该迁就标题设置，毕竟是前期遗留的习惯，能不能设置开关切换后这个设置就自动关闭或不允许打开了？

**Comment by TCOTC** [comment]
> 思源中还是建议从二级标题开始，比如 设置 - 导出 - 添加文档标题 这个就是添加的一级标题，如果不从二级标题开始的话也会有问题。
> 
> 大部分情况下，正文中二级标题~六级标题已经足够用了，一级标题留下来做内置预设逻辑的顶层。

要不在用户指南里加一句**标题的推荐用法**？

**Comment by 88250** [comment]
> 添加文档标题 这个功能我觉得应该迁就标题设置，毕竟是前期遗留的习惯，能不能设置开关切换后这个设置就自动关闭或不允许打开了？

不打开导出添加标题的话就只能手动添加了，这个用户更麻烦，并且手动添加的话逻辑上也是要添加一级标题的，会和正文其他部分的一级标题冲突。

**Comment by 88250** [comment]
> 要不在用户指南里加一句标题的推荐用法？

![image](https://github.com/siyuan-note/siyuan/assets/873584/cb2c7e19-dbb2-4dc7-b917-f339875bbdfd)

是否需要调整？

**Comment by 5kyfkr** [comment]
> > 添加文档标题 这个功能我觉得应该迁就标题设置，毕竟是前期遗留的习惯，能不能设置开关切换后这个设置就自动关闭或不允许打开了？
> 
> 不打开导出添加标题的话就只能手动添加了，这个用户更麻烦，并且手动添加的话逻辑上也是要添加一级标题的，会和正文其他部分的一级标题冲突。

不太理解，就不给打开添加标题也行吧，就相当于导出后外部文档名对应笔记名称就是主标题，直接一级标题进行分类，麻烦应该也不会太麻烦，直接从文件名复制一下放进去就行，毕竟导出功能用的不多，大部分时候还是为了方便在思源里用

**Comment by 88250** [comment]
不打开的话导出很麻烦的，得手动加，并且如果正文用了一级标题，手动加也会有冲突。

**Comment by 5kyfkr** [comment]
> 是否需要调整？

感觉还是得括号提一下(Markdown通常实践中一级标题为文章主标题，一篇笔记通常只有一个主标题)
>参考：https://learn.microsoft.com/en-us/powershell/scripting/community/contributing/general-markdown?view=powershell-7.4&viewFallbackFrom=powershell-7.3
>Only one H1 per document

**Comment by 88250** [comment]
还是不提 Markdown 了，我们说明这个逻辑就行了。

**Comment by zhoutaosheng** [comment]
> 思源中还是建议从二级标题开始，比如 设置 - 导出 - 添加文档标题 这个就是添加的一级标题，如果不从二级标题开始的话也会有问题。
> 
> 大部分情况下，正文中二级标题~六级标题已经足够用了，一级标题留下来做内置预设逻辑的顶层。
> 
> 这个不考虑加开关了，感谢讨论。

很多朋友，以前大量的文档，是从一级标题，开始写的，而且今后可能不小心就使用这个习惯。如果这样，导出是不是会有问题

而且这个问题，我看了，只是将文档标题作为一级标题了，你不说，我都没有发现
如果想解决，只需要将这种风格的文档，其他级别的标题降级就可以了

**Comment by TCOTC** [comment]
> 只需要将这种风格的文档，其他级别的标题降级就可以了

有点道理，不过六级标题就没法降了

**Comment by zhoutaosheng** [comment]
> > 只需要将这种风格的文档，其他级别的标题降级就可以了
> 
> 有点道理，不过六级标题就没法降了

1. 如果按照标题降级处理，到第6级，就不降了吧。我基本上没有用超过4级标题，超过4级，说明笔记目录本身已经不合理了
2. 也可以不降级，就现在的方式导出，真没有看出文档标题也作为一级标题后，和原有的一级标题在一起有什么违和，作者不说，真没有发现
