### ISSUE TITLE
数据库支持实时筛选和排序

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11349]
参考 Notion 的实时筛选和排序：

https://github.com/siyuan-note/siyuan/assets/78434827/11646dbc-842a-4339-8d85-c5110d93fc19

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/bb104f29-5280-491e-8203-b0c2c7fb5b2e)

---

下面是「创建时间排序后新建行跳动」的问题，移动到 #11100 解决：

```
使用右上角的加号添加条目的时候，输入框应该出现在开头才对

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/11100#issuecomment-2105908576_
            
这种情况，如果数据库很长，创建新条目的时候会跳转到数据库末尾，然后还要回到开头去编辑，很麻烦：

[123.webm](https://github.com/siyuan-note/siyuan/assets/78434827/fad6cf13-6daa-4c4c-b822-5f6610f27b21)
```

**Comment by Vanessa219** [comment]
这个属于排序问题 @88250

**Comment by 88250** [comment]
这个问题有点复杂，目前的逻辑是“编辑过的”行才参与排序，新建的行是不参与排序的，但是 创建时间 是自动填充的，所以默认就算作是编辑过的，一旦创建就会参与排序。

要改进的话有两个方案：

Notion 创建时就计算好插入位置，比如降序时创建就直接在第一行：



![image](https://github.com/siyuan-note/siyuan/assets/873584/4b1f26e5-4c32-4bbc-b641-a69f29efbd60)

wolai 创建时在最后一行：

![image](https://github.com/siyuan-note/siyuan/assets/873584/58954c79-13a1-4520-ad7d-87c807d62170)

创建结束后排序并定位到第一行：

![image](https://github.com/siyuan-note/siyuan/assets/873584/54f35a06-bb49-42b2-aae0-61b02ea287b6)

**Comment by TCOTC** [comment]
> 创建结束后排序并定位到第一行

赞同这个

- 使用右上角的添加按钮：在首行创建，创建结束后排序
- 使用左下角的添加按钮：在末行创建，创建结束后排序

**Comment by TCOTC** [comment]
> Notion 创建时就计算好插入位置，比如降序时创建就直接在第一行

如果思源能定位到数据库中间的某个位置，这个方案其实也没啥问题

**Comment by TCOTC** [comment]
> > 创建时就计算好插入位置，比如降序时创建就直接在第一行
> 
> 如果思源能定位到数据库中间的某个位置（定位到数据库具体条目），这个方案其实也没啥问题

如果能实现定位的话，应该就能做 #10916 了吧

**Comment by 88250** [comment]
可能是的，有一定关联。

**Comment by TCOTC** [comment]
[数据库排序功能, 对新增体验影响很大 - 链滴](https://ld246.com/article/1719195949253)

**Comment by 88250** [comment]
技术困难，并且工作量太大了，除非在前端再实现一套计算逻辑。
