### ISSUE TITLE
Triggering tag selection via `#` is no longer supported after disabling tag syntax

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11346]
禁用行级标签语法完善

### In what scenarios do you need this feature?

禁用行级标签语法之后，按#还是会弹出标签输入面板
我想禁用行级标签语法应该本来就不是那么需要标签的人，按#弹出标签输入面板就成了一个干扰
需要的用户可以用Ctrl+T或者斜杆命令添加标签

### Describe the optimal solution

禁用行级标签语法之后，按#就不弹出标签输入面板
需要的用户可以用Ctrl+T或者斜杆命令添加标签

**Comment by TCOTC** [comment]
别啊，我只是不想在 #foo# 包裹的时候自动转换为标签，输入 # 触发标签搜索还是挺好的（就像输入 / 触发菜单）

**Comment by 88250** [comment]
这情况还是用快捷键吧。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sat, May 11, 2024 19:11 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Triggering tag selection via `#` is nolonger supported after disabling tag syntax (Issue #11346)




 
别啊，我只是不想在 #foo# 包裹的时候自动转换为标签，输入 # 触发标签搜索还是挺好的（就像输入 / 触发菜单）

**Comment by Achuan-2** [comment]
@88250 @TCOTC 
补充下，目前用快捷键创建标签，没有输入#的标签搜索面板，支持这个issue的特性后，需要改进下快捷键创建标签的体验

**Comment by 88250** [comment]
@Achuan-2 这个暂时不动了吧，等后面看看需求是否强烈。

**Comment by TCOTC** [comment]
@88250 没法加标签了啊啊啊

**Comment by 88250** [comment]
@TCOTC 你指的是没法搜索？

**Comment by TCOTC** [comment]
> @TCOTC 你指的是没法搜索？

对

**Comment by 88250** [comment]
后面在 https://github.com/siyuan-note/siyuan/issues/11354 中考虑吧。

**Comment by hl262** [comment]
> 后面在 #11354 中考虑吧。

通过快捷键或者/的方式调取标签也没有搜索框的话，对于使用多级标签的用户会是一种困扰，这个改动之后多级的标签必须要去标签列表中复制才能保证新插入的标签的名称不会出错

**Comment by TCOTC** [comment]
@88250 移动端打不了标签了。

`设置 - 编辑器` 里没有 Markdown 语法的那 4 个开关

**Comment by 88250** [comment]
@Vanessa219 有空看看。

**Comment by TCOTC** [comment]
我还是觉得这个改动不好，移动端打标签很不方便了

**Comment by 88250** [comment]
从目前收到的反馈看，禁用 `#` 触发标签输入是有点问题，需要 `#` 触发输入的人还是挺多的，下个版本撤销这个修改吧。

撤销后 #11354 也不考虑了。
