### ISSUE TITLE
S3自动同步能否运行自行设定同步时间

### ISSUE THREAD

**Issue by yong900630** [siyuan-note/siyuan#11344]
### In what scenarios do you need this feature?

目前自动同步是数据不再变动后30秒进行同步一次，但是我感觉30秒属于比较节省流量的方法，但是感觉对于一下要求同步高的情况下，可以采用数据不再变动后1秒进行同步一次

### Describe the optimal solution

将同步时间变量变为允许认为输入即可，无需改动其他任何代码

**Comment by 88250** [comment]
思源笔记的同步方案不是为了能支持在线实时同步的，提高同步间隔虽然可以解决这个场景需求，但是存在较大副作用：文件较多时频繁同步会占用大量系统资源，特别是移动端上会增加设备耗电。所以 30s 的间隔是个较为稳妥的设置，不建议修改。

**Comment by yong900630** [comment]
那么能否允许用户自行设定同步时间呢？对于长期使用台式电脑的人来说，根本不需要关心耗电。
大部分的思源笔记修改的地方都在文字方面，而文字方面的同步本身并不怎么占用空间和流量。

**Comment by 88250** [comment]
这个不只是耗电，数据量大了以后频繁同步会占用很多系统资源的。

**Comment by 88250** [comment]
为了大部分用户能稳定运行，不考虑开放这个配置项，如果实在要改的话估计只能考虑修改源码自行编译了。

**Comment by yong900630** [comment]
也就是说siyuan同步的时候，S3云端是记录了每一次同步的数据，然后其他设备与S3云端同步时会同步上一次同步到最近同步每一次的同步数据。
比如2024年5月10日，早上10:00 A设备开始每1分钟同步一次，一直到12:00，会产生120次同步，S3端储存了120次的同步数据。
然后B设备最近一次同步时间在10:00，然后再12:05分打开设备，进行同步，然后该次同步会120次的同步数据（即使120次同步当中很多数据，已经不需要了）

**Comment by 88250** [comment]
不是，同步是对比差异后增量同步的。

**Comment by yong900630** [comment]
如果是对比差异后增量同步，那么严格讲很占用资源啊。S3端是对象存储，本身不具备计算能力，那么肯定是本地设备将数据与S3端的数据比对，消耗的资源是S3端。

您这里指的消耗资源是指本地设备需要读取全部S3端数据，每个块全部比对一遍在同步吗？如果真是这样的话，随着笔记的数据增多，那么以后每次同步都会越来越卡。但是思源笔记同步速度感觉还是非常快的，我用的是第三方七牛云S3端同步。

目前我的思源笔记基本只有几百M，以文字为主+少量图片，视频采用储存视频地址的方式来减少空间的占用。

**Comment by 88250** [comment]
> 您这里指的消耗资源是指本地设备需要读取全部S3端数据，每个块全部比对一遍在同步吗？

不需要全部读取，仅读取索引，通过索引就可以对比差异了，具体代码参见 https://github.com/siyuan-note/dejavu
