### ISSUE TITLE
批量添加的数据库条目无法按创建时间排序

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11348]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c09f35a8-3351-482c-9de8-e739143cc583)

升序和降序都是一样的：

[顺序.webm](https://github.com/siyuan-note/siyuan/assets/78434827/5dd9bb62-df87-4227-80a4-8a53885245e0)

### Describe the optimal solution

批量创建的条目，从上到下，创建时间应该是从早到晚的

**Comment by 88250** [comment]
批量创建的话创建时间都是一样的（目前时间不一样有点问题，稍后调整），所以升序降序不影响排序，参考飞书文档的逻辑。

**Comment by TCOTC** [comment]
@88250 飞书的批量创建时间也是不同的啊：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ef66e254-7386-42d0-ade7-33ad58c82237)

**Comment by 88250** [comment]
思源是毫秒的，但是我觉得批量创建的话创建时间就应该是一样的，因为他们都在“一批”里。

**Comment by TCOTC** [comment]
我觉得从逻辑上讲批量创建的作用原本就是代替一次次点击「添加」，点击「添加」是有次序的，所以批量创建也要有次序。

并且我想了想， `在上方插入 N 行` 和 `在下方插入 N 行` 还不一样：

- `在上方插入 N 行` ：**从下到上**，创建时间应该是从早到晚的
- `在下方插入 N 行` ：**从上到下**，创建时间应该是从早到晚的

**Comment by 88250** [comment]
这个暂时不做调整了，等后面继续收集反馈看看。
