### ISSUE TITLE
Improve slash menu

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11345]
### In what scenarios do you need this feature?

目前斜杆命令「新建文档」实际上是新建子文档
而且显示的快捷键是Ctrl+N新建文档，但实际表现与Ctrl+N的表现不同（Ctrl+N可以配置文档生成路径，目前这个命令完全是新建子文档，不受设置的Ctrl+N文档生成路径影响）
![Clip_2024-05-11_14-36-23](https://github.com/siyuan-note/siyuan/assets/60436214/6b566600-8722-41a9-a8f9-0e5b190114be)

### Describe the optimal solution

- 「新建文档」改为「新建子文档」，快捷键显示改为Ctrl+F3

### Describe the candidate solution

- 「新建文档」改为「新建子文档」，快捷键显示改为Ctrl+F3
- 同时新增「新建文档」功能，快捷键为Ctrl+N，根据笔记本/全局的Ctrl+N设置新建文档路径

**Comment by Vanessa219** [comment]
新建子文档 没有快捷键就空着， Ctrl+F3 是 `新建文档名为`， 是有区别的。

**Comment by Achuan-2** [comment]
哦哦，我看f3是`新建子文档`，就以为ctrl+f3就是`新建子文档名`为了

**Comment by TCOTC** [comment]
@Vanessa219 新建文档后不应该把 `/` 留在原位：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ff2cec23-5768-4171-a977-53b48ef05e00)
