### ISSUE TITLE
If a file with the same name exists during export PDF/Docx, it will be automatically renamed

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11357]
导出pdf、word如果文件被占用，弹窗提示用户

### In what scenarios do you need this feature?

目前导出pdf，如果之前已经导出过一次，这个pdf已经用Adobe Acrobat等pdf阅读软件占用，再导出同名pdf，不会提示文件被占用
只会一直显示`正在导出`

导出word也有这个问题

### Describe the optimal solution

导出pdf、word，如果同名文件被占用，弹窗提示用户

**Comment by TCOTC** [comment]
要是导出的目录下存在同名文件，也需要提示

**Comment by 88250** [comment]
> 要是导出的目录下存在同名文件，也需要提示

这个请单独开 issue。

**Comment by 88250** [comment]
要不咱直接改为发现同名文件就自动重命名，比如 xxx（1）.pdf 这样的？

**Comment by TCOTC** [comment]
合理

**Comment by TCOTC** [comment]
我建议是这样：

- xxx.pdf
- xxx(2).pdf
- xxx(3).pdf

**Comment by 88250** [comment]
那就不存在 #11358 的问题了，抱歉麻烦你了。

**Comment by TCOTC** [comment]
@88250 有个问题，现在批量导出 Markdown 时如果存在同名文件是怎么处理的？

**Comment by 88250** [comment]
我记得是文件名后面加随机数

**Comment by TCOTC** [comment]
> 我记得是文件名后面加随机数

![image](https://github.com/siyuan-note/siyuan/assets/78434827/eeff45fe-93f7-41ff-ac78-b04f7e4b1e2a)

**Comment by 88250** [comment]
哦哦，加的是文档 ID。

**Comment by 88250** [comment]
@Vanessa219 /api/file/getUniqueFilename

**Comment by TCOTC** [comment]
那除了 PDF/Docx 之外的是不需要吗？

**Comment by 88250** [comment]
其他的是通过浏览器下载，浏览器会自动处理。

**Comment by 88250** [comment]
导出 docx 不再删除已经存在的文件 https://github.com/siyuan-note/siyuan/issues/8822
