### ISSUE TITLE
Improve embed/ref block reindex

### ISSUE THREAD

**Issue by jim555666888** [siyuan-note/siyuan#11353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="374" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/6ce37bdc-6b53-4297-ad5c-a831ccc4b92e">

点击重建索引后，提示以下错误

<img width="1570" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/ba52e28e-2893-43e8-9025-45edabf15dbc">

<img width="892" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/cb6bcd08-3bfb-4866-b66a-7eccb5761400">

### Expected result

希望能解决bug

### Version environment

```markdown
- Version: 3.0.13
- Operating System: macos最新版
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
63839cba0cdb2cad198e7e56777e44200dd3eb53

**Comment by jim555666888** [comment]
该问题在3.0.15版本中仍未解决

**Comment by jim555666888** [comment]
> [63839cb](https://github.com/siyuan-note/siyuan/commit/63839cba0cdb2cad198e7e56777e44200dd3eb53)

3.0.15重建索引，仍然会出现：

![image](https://github.com/siyuan-note/siyuan/assets/105782402/0e088145-9a96-4aa0-8230-a3e122e1f39b)

**Comment by jim555666888** [comment]
3.0.15重建索引后仍然提示：”不存在符合条件的内容块“
