### ISSUE TITLE
导出 Markdown 再导入时遇到的双重标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11351]
### In what scenarios do you need this feature?

原文档：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b7b7f793-5907-4f23-b8e8-c48cf9d3be9b)

导出为 Markdown：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/98676d40-a828-4168-9b98-5290b08f595d)

再导入：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/950339da-dbc1-4cd4-81be-024001103294)

就会多出一个一级标题

### Describe the optimal solution

不知道能咋改进

**Comment by 88250** [comment]
关掉 设置 - 导出 - 添加文档标题

**Comment by TCOTC** [comment]
原来如此，没发现这个设置
