### ISSUE TITLE
Support cancel two-way relation when related to the current database

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11356]
https://github.com/siyuan-note/siyuan/issues/11278

**Comment by TCOTC** [comment]
@88250 为什么这两行会改来改去的：

https://github.com/siyuan-note/siyuan/commit/7debd72d376b9f9ffec47b243815efb08b8ecff4
![image](https://github.com/siyuan-note/siyuan/assets/78434827/74ee0359-5244-4798-b208-3fdb77c3befc)

https://github.com/siyuan-note/siyuan/commit/933a1936c0c4f206d48ea6ed933400341c08a809
![image](https://github.com/siyuan-note/siyuan/assets/78434827/b9ca6d9f-697b-4695-96ff-1da32efd302f)

**Comment by 88250** [comment]
IDE 自动格式化抽风了……

**Comment by TCOTC** [comment]
取消关联之后，再次关联会有一点问题：

理论上「关联」列和「321」列应该是一样的

[取消.webm](https://github.com/siyuan-note/siyuan/assets/78434827/b28bbae6-3c5f-4032-aa73-cd7500d6eaa1)

**Comment by 88250** [comment]
看了下是 https://github.com/siyuan-note/siyuan/issues/11250 没有解决好，稍后修复。
