### ISSUE TITLE
Message Dialog on Startup

### ISSUE THREAD

**Issue by UsmanTechJive** [siyuan-note/siyuan#11369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I've been receiving this message dialog since version 3.0.11 maybe, and it's still occurring whenever I start SiYuan.

![SiYuan_J79Yhgr2kx](https://github.com/siyuan-note/siyuan/assets/36538038/840e9266-54e3-43e6-af96-332eb4203a64)

### Expected result

The application starts without displaying the unintended message dialog, allowing for a seamless startup experience.

### Version environment

```markdown
- Version: 3.0.11
- Operating System: Windows 11 Pro
- Browser (if used): -
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15287687/siyuan.log)

**Comment by 88250** [comment]
If you exited the application normally last time, this pop-up message will not appear. Please close and exit the application normally and then start it again. This message should not appear.

**Comment by 88250** [comment]
We have closed this issue. If you still have any questions, please leave a comment. Thank you.
