### ISSUE TITLE
退格键后光标位置与常规方式不符

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#11366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

常规状态：
![CleanShot 2024-05-12 at 20 49 35](https://github.com/siyuan-note/siyuan/assets/50087596/12cee9f0-22b2-4e0d-b914-78f75a5f1624)

特殊状态，可以看到退格后光标跑到上面去了，这不对劲：
![CleanShot 2024-05-12 at 20 48 20](https://github.com/siyuan-note/siyuan/assets/50087596/97f7d735-9d16-436e-a55b-22e237dc1c89)

### Expected result

.

### Version environment

```markdown
- Version: 3.0.13
- Operating System: macOS  13.6.6
- Browser (if used):
```

### Log file

.

**Comment by TCOTC** [comment]
撤销后退格位置不正确

[列表.webm](https://github.com/siyuan-note/siyuan/assets/78434827/4da7ffc5-5225-4a5b-839c-9e7eb545298e)

还挺好复现
