### ISSUE TITLE
点击数据库导致页面微量移动

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11363]
### 点击数据库导致页面微量移动

在下面这种情况下（靠近文档顶部），可以观察到微量的移动：

[移动.webm](https://github.com/siyuan-note/siyuan/assets/78434827/fa3f1d66-3c5c-4c2f-b5dd-5dab3966c4ba)

**Comment by 88250** [comment]
我这里重现不了，麻烦导出这个文档我再测试看看。

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/0b5c2bc4-4e17-4add-ba6d-17c605831284)

**Comment by TCOTC** [comment]
你先往单选里多加一些：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8e20ac69-4bf4-48b6-8bbb-4fe2256fe9a5)

在弹出菜单的瞬间会移动

**Comment by 88250** [comment]
还是不行：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/17040def-ec65-4a01-809a-7223c123168e)

**Comment by TCOTC** [comment]
这东西还挺迷的，我一会能复现，一会不能复现，我再试试有什么简单的方法

**Comment by 88250** [comment]
好的，这个目前倒是影响不大。

**Comment by TCOTC** [comment]
换成「电」字，让面包屑吞掉上面一点：

[电.webm](https://github.com/siyuan-note/siyuan/assets/78434827/d64414d3-4bbe-4359-aef3-7e8355bbd3cc)

**Comment by 88250** [comment]
重现不了……

**Comment by TCOTC** [comment]
难道这个还会跟设备有关吗，算了，反正几乎没有影响，以后换设备还能复现的话再说好了
