### ISSUE TITLE
Improve `Display the VIP icon`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11368]
`顶栏显示VIP` 设置 VIP 图标

打开左边这个是有变化的，但打开右边这个没有变化：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dbec5f30-2366-41f2-9aad-0726b947d792)

**Comment by 5kyfkr** [comment]
买了订阅或功能特性就会有图标

**Comment by TCOTC** [comment]
> 买了订阅或功能特性就会有图标

主要是我这里也没见到有图标

**Comment by 5kyfkr** [comment]
> > 买了订阅或功能特性就会有图标
> 
> 主要是我这里也没见到有图标

是不是用移除图标插件给隐藏了，我是功能特性有图标，订阅我以前没开过不记得有没图标

**Comment by TCOTC** [comment]
> > > 买了订阅或功能特性就会有图标
> > 
> > 
> > 主要是我这里也没见到有图标
> 
> 是不是用移除图标插件给隐藏了，我是功能特性有钻石图标，订阅我以前开过忘记有没图标，这图标除了占用顶栏空间没啥用，没有最好

没开插件/代码片段

你的顶栏截个图让我看看是啥样？

**Comment by 5kyfkr** [comment]
> > > > 买了订阅或功能特性就会有图标
> > > 
> > > 
> > > 主要是我这里也没见到有图标
> > 
> > 
> > 是不是用移除图标插件给隐藏了，我是功能特性有钻石图标，订阅我以前开过忘记有没图标，这图标除了占用顶栏空间没啥用，没有最好
> 
> 没开插件/代码片段
> 
> 你的顶栏截个图让我看看是啥样？

都开了是这样
![image](https://github.com/siyuan-note/siyuan/assets/63196026/b0c0e593-6f13-4c75-9ec8-88152918156b)
![image](https://github.com/siyuan-note/siyuan/assets/63196026/d6f8a02b-df83-4240-b747-20cbdd30b9af)

**Comment by 88250** [comment]
订阅以后开启 顶栏显示头像和 VIP：

![image](https://github.com/siyuan-note/siyuan/assets/873584/98fa79c5-fdd9-483a-83b8-7de65fb75896)

全部关闭：

![image](https://github.com/siyuan-note/siyuan/assets/873584/57d2fdf7-5cf6-4087-a99f-117482039d34)

**Comment by TCOTC** [comment]
奇怪了，我这里没有那个钻石，皇冠也是一直显示的

**Comment by 5kyfkr** [comment]
> 奇怪了，我这里没有那个钻石，皇冠也是一直显示的

皇冠关不了嘛，钻石是买了功能特性才有，皇冠是订阅的

**Comment by TCOTC** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/fea1a10f-fd56-4009-a32d-459f1eadbaca)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d62a83fc-9e5e-49ec-b4c2-799cd7b28cbd)

就是没有那个钻石

**Comment by 5kyfkr** [comment]
> 就是没有那个钻石

辣么奇怪，没有订阅但是有皇冠。。感觉是图标元素对应错了

**Comment by TCOTC** [comment]
虽然我觉得可能是图标不同，但开启「顶栏显示VIP」确实是一点变化都没有

**Comment by TCOTC** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/a421b25a-c981-488b-a3a0-268872a5ff96)

这个一直显示的是试用订阅

**Comment by 5kyfkr** [comment]
> ![image](https://private-user-images.githubusercontent.com/78434827/329892682-a421b25a-c981-488b-a3a0-268872a5ff96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjIxODgsIm5iZiI6MTcxNTU2MTg4OCwicGF0aCI6Ii83ODQzNDgyNy8zMjk4OTI2ODItYTQyMWIyNWEtYzk4MS00ODhiLWEzYTAtMjY4ODcyYTVmZjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAwNTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MGFjMzU1YzdlMTI5MTM0NDE5YTk2ZGJkZjVmZWMzNTAzMzNhYWNjZTQ5ZmIxZWI1NTM1ZmM2ZGY1ZTc4M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.98owKpzp8A2eAMRPSvMQ5tHxArSU1pgmnVVAVpEB6z4)
> 
> 这个一直显示的是试用订阅

你现在是订阅和功能特性都没买？还是只买了功能特性？

**Comment by TCOTC** [comment]
@88250 我只买了功能特性，并且还没有试用过订阅

**Comment by 5kyfkr** [comment]
> @88250 我只买了功能特性，并且还没有试用过订阅

我用的是这个图标，所以功能特性是钻石，默认的也是皇冠
![image](https://github.com/siyuan-note/siyuan/assets/63196026/9747add9-a1af-4644-bc9a-0dfad3b58688)

**Comment by 88250** [comment]
哦，我知道了，这个是故意留着的，在没有登录或者登录后并且没有订阅（也没有试用订阅）时常驻显示：

![image](https://github.com/siyuan-note/siyuan/assets/873584/f393e485-6726-4314-a635-30f60cbfc306)

**Comment by 5kyfkr** [comment]
> 哦，我知道了，这个是故意留着的，在没有登录或者登录后并且没有订阅（也没有试用订阅）时常驻显示：

那我这怎么没常驻呢，我没开订阅

**Comment by TCOTC** [comment]
@88250 我感觉 有功能特性 & 没有试用订阅 的情况下就不需要显示了

**Comment by TCOTC** [comment]
> > 哦，我知道了，这个是故意留着的，在没有登录或者登录后并且没有订阅（也没有试用订阅）时常驻显示：
> 
> 那我这怎么没常驻呢，我没开订阅

你试用过了吧？

**Comment by 88250** [comment]
@5kyfkr 试用过就没有了

**Comment by 5kyfkr** [comment]
感觉有了功能特性应该不需要这个图标了，不然感觉怪怪的

**Comment by 88250** [comment]
再加个判断根据 顶栏显示 VIP 设置吧
