### ISSUE TITLE
希望增加一个选项：点击文档树的标题，是否展开子节点

### ISSUE THREAD

**Issue by jim555666888** [siyuan-note/siyuan#11384]
### In what scenarios do you need this feature?

<img width="695" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/97f3dde1-6815-4706-a71e-319a7cf2919f">

如题，当然这个可能也可以通过插件实现，但是市场中的插件都不好使，也有冲突，可能是因为和思源开放权限有关吧？

### Describe the optimal solution

我认为这是一个基础产品功能，不应该由插件实现。

可以在设置中加一个选项：点击文档是否展开子文档（如有）

感谢！

**Comment by jim555666888** [comment]
<img width="629" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/8c419d83-9f5c-4733-9069-8db9b92f7fb5">

**Comment by shuojie819** [comment]
支持😘
1. 自动展开、自动折叠
2. 点击大纲跳转时高亮标题块所在行
3. 实时显示当前文档所在大纲中的位置
演示：
![PixPin_2024-05-14_14-38-11](https://github.com/siyuan-note/siyuan/assets/72399630/9adff938-9b15-4f1e-8d31-e2612021521c)

**Comment by TCOTC** [comment]
这个效果看起来相当不错

**Comment by 88250** [comment]
抱歉，这个不考虑了，原生只考虑点击箭头展开/收起，点击文档打开。

**Comment by shuojie819** [comment]
> ~这个效果看起来相当不错~
> 
> 诶，我回复的那一条怎么删了

我发错地放了，原来这里说的是文档树🥲

**Comment by TCOTC** [comment]
> > ~这个效果看起来相当不错~
> > 诶，我回复的那一条怎么删了
> 
> 我发错地放了，原来这里说的是文档树🥲

那现在你发到哪个 issue 去了

**Comment by shuojie819** [comment]
> > > ~这个效果看起来相当不错~
> > > 诶，我回复的那一条怎么删了
> > 
> > 
> > 我发错地放了，原来这里说的是文档树🥲
> 
> 那现在你发到哪个 issue 去了

放到链滴了：[大纲需求 - 链滴](https://ld246.com/article/1715677596192)
