### ISSUE TITLE
When the `"` character exists in the hyperlink element address, the paste cannot be parsed normally

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11385]
粘贴链接时，把 URL 中的保留和不安全字符自动转换为 URL 编码

### In what scenarios do you need this feature?

1. 把 `[在必应搜索 "你好"](www.bing.com/search?q="你好")` 粘贴到思源内，会丢失链接部分 `"` 及后面的字符，变成 `[在必应搜索 "你好"](www.bing.com/search?q=)`
2. 把 `[在必应搜索 "你好"](www.bing.com/search?q=%22你好%22)` 粘贴到思源内则是正常的，点击超链接也能正常打开网页
3. 复制 `www.bing.com/search?q=%22你好%22` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会丢失链接部分 `你` 及后面的字符，变成 `http://www.bing.com/search?q=%22`

### Describe the optimal solution

建议在粘贴链接时，把 URL 中的保留和不安全字符（`"` 和非英文之类的）自动转换为 URL 编码

`[在必应搜索 "你好"](www.bing.com/search?q="你好")` 粘贴后变为 `[在必应搜索 "你好"](www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22)` （符号和中文都转换）

### Describe the candidate solution

> 复制 `www.bing.com/search?q=%22你好%22` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会丢失链接部分 `你` 及后面的字符，变成 `http://www.bing.com/search?q=%22`

另外，这个 `http://` 有必要自动加上吗？明明去掉之后点击也可以打开网页

**Comment by 88250** [comment]
> 这个 `http://` 有必要自动加上吗？

最好加，否则可能会被某些解析器识别为相对路径，比如 GitHub：


![image](https://github.com/siyuan-note/siyuan/assets/873584/b67385df-9b3b-4e27-81fa-9c4eeead236e)

**Comment by TCOTC** [comment]
> > 这个 `http://` 有必要自动加上吗？
> 
> 最好手动加，否则可能会被某些解析器识别为相对路径，比如 GitHub：
> 

这样的话加 `https://` 会不会更好？多数网站都是 https ，有的网站用 http 会打不开

**Comment by 88250** [comment]
嗯，主流已经是 https

**Comment by TCOTC** [comment]
刚刚打包试了一下：

1. 复制 `www.bing.com/search?q=%22你好%22` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会变成 `http://www.bing.com/search?q=%22` → 【问题】丢失了链接部分 `你` 及后面的字符
2. 复制 `www.bing.com/search?q="你好"` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会变成 `http://www.bing.com/search?q=` → 【问题】丢失了链接部分 `"` 及后面的字符
3. 以上自动添加的 `http://` 需要改为 `https://`
4. 复制 `[在必应搜索 "你好"](www.bing.com/search?q="你好")` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会添加链接 `www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22` → 【问题】前面少了 `https://`
5. 复制 `[在必应搜索 "你好"](www.bing.com/search?q=%22你好%22)` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会添加链接 `www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22` → 【问题】前面少了 `https://`

@88250 需要统一一下

**Comment by TCOTC** [comment]
另外除了 `"` ，其他符号会不会有同样的问题？我看 `URL 保留字符和不安全字符` 是有一堆的

**Comment by 88250** [comment]
* 3、4、5 不自动加 https，否则相对路径可能会有问题
* 不是 URL 编码问题，是 DOM 属性值的问题

**Comment by TCOTC** [comment]
> ![image](https://github.com/siyuan-note/siyuan/assets/78434827/04be860f-2483-4b81-827c-a33c5dfd7bcf)

这个相对路径的问题要怎么复现？

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/8ef005ef-72c4-4f48-930f-33dbba80df68)

**Comment by TCOTC** [comment]
这个懂了。那自动添加的 `http://` 不改为 `https://` 的理由是什么？

**Comment by 88250** [comment]
GFM 规范定义的 https://github.github.com/gfm/#autolinks-extension-

**Comment by TCOTC** [comment]
这两个呢：

> 1. 复制 `www.bing.com/search?q=%22你好%22` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会变成 `http://www.bing.com/search?q=%22` → 【问题】丢失了链接部分 `你` 及后面的字符
> 2. 复制 `www.bing.com/search?q="你好"` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会变成 `http://www.bing.com/search?q=` → 【问题】丢失了链接部分 `"` 及后面的字符

**Comment by 88250** [comment]
还在看



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Wed, May 15, 2024 13:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] When the `"` character exists in thehyperlink element address, the paste cannot be parsed normally (Issue #11385)




 
这两个呢：
   
复制 www.bing.com/search?q=%22你好%22 ，在思源内选中文本 Ctrl+K 或者直接粘贴，会变成 http://www.bing.com/search?q=%22 → 【问题】丢失了链接部分 你 及后面的字符
 
复制 www.bing.com/search?q="你好" ，在思源内选中文本 Ctrl+K 或者直接粘贴，会变成 http://www.bing.com/search?q= → 【问题】丢失了链接部分 " 及后面的字符

**Comment by TCOTC** [comment]
`www.bing.com/search?q=%22你好%22` 和 `www.bing.com/search?q="你好"` 

添加链接后应该变成 `http://www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22`

**Comment by 88250** [comment]
这个还不确定要不要强制编码，能不编码最好。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Wed, May 15, 2024 13:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] When the `"` character exists in thehyperlink element address, the paste cannot be parsed normally (Issue #11385)




 
www.bing.com/search?q=%22你好%22 和 www.bing.com/search?q="你好"
 
添加链接后应该变成 http://www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22

**Comment by TCOTC** [comment]
这两个已经是强制编码了的：

> 4. 复制 `[在必应搜索 "你好"](www.bing.com/search?q="你好")` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会添加链接 `www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22`
> 5. 复制 `[在必应搜索 "你好"](www.bing.com/search?q=%22你好%22)` ，在思源内选中文本 `Ctrl+K` 或者直接粘贴，会添加链接 `www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22`

**Comment by 88250** [comment]
嗯，等下午再看看



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Wed, May 15, 2024 13:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] When the `"` character exists in thehyperlink element address, the paste cannot be parsed normally (Issue #11385)




 
这两个已经是强制编码了的：
   
复制 [在必应搜索 "你好"](www.bing.com/search?q="你好") ，在思源内选中文本 Ctrl+K 或者直接粘贴，会添加链接 www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22
 
复制 [在必应搜索 "你好"](www.bing.com/search?q=%22你好%22) ，在思源内选中文本 Ctrl+K 或者直接粘贴，会添加链接 www.bing.com/search?q=%22%E4%BD%A0%E5%A5%BD%22
