### ISSUE TITLE
文本样式对内链、外链和虚拟引用的影响

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#11381]
### In what scenarios do you need this feature?

在对带有内链、外链或虚拟引用的文本设置文本样式时，会覆盖其本身的样式
- 内外链的高亮没了
- 虚拟引用的虚线没了

![image](https://github.com/siyuan-note/siyuan/assets/63145205/e85248c1-942d-4d45-9e5e-2ffba7746e3f)

### Describe the optimal solution

减弱影响或不影响这些内容

**Comment by 88250** [comment]
这是设计如此，虚拟引用仅作用于纯文本上。
