### ISSUE TITLE
近期未来是否会支持多用户？

### ISSUE THREAD

**Issue by nekomiya-kasane** [siyuan-note/siyuan#11382]
### In what scenarios do you need this feature?

Siyuan对数据表格支持比其他Notion类似的可本地部署的应用要好很多，我想部署在公司服务器上，但目前没有多用户支持和权限控制，这些是否在较近的未来会实现？

### Describe the optimal solution

添加多用户支持和文档权限控制，接入OIDC或LADP认证

**Comment by 88250** [comment]
你好，目前思源笔记是面向个人的知识管理工具，所以短期内是不考虑支持多用户的，谢谢。

**Comment by 88250** [comment]
欢迎参与 oidc 接入讨论 https://github.com/siyuan-note/siyuan/issues/16560
