### ISSUE TITLE
有些文本无法在  ``  之间直接粘贴

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11387]
### 有些东西无法在  `` ` ` `` 之间直接粘贴：

[粘贴.webm](https://github.com/siyuan-note/siyuan/assets/78434827/5ebc9efe-26ca-44e8-9b9c-bbf8388a5272)

```
&ZeroWidthSpace;标签

&ZeroWidthSpace;

<span data-type="tag">&ZeroWidthSpace;标签</span>

<span>&ZeroWidthSpace;标签</span>
```

**Comment by 88250** [comment]
这是因为第一次形成 code 元素时需要做一些标记符/HTML 标签的剔除，否则会导致其他问题 https://github.com/siyuan-note/siyuan/issues/9805 ，形成 code 元素以后再粘贴就可以按 code 的内部语义处理了，不会剔除标记符/HTML 标签。

所以这个问题无法再改进了，感谢反馈。

**Comment by TCOTC** [comment]
@88250 那文本 `&ZeroWidthSpace;` 和真正的零宽空格是没法区分的吗？我在段落块里粘贴 `&ZeroWidthSpace;` 的时候会转换为零宽空格，但手动输入 `&ZeroWidthSpace;` 就不会

**Comment by TCOTC** [comment]
> 第一次形成 code 元素时需要做一些标记符/HTML 标签的剔除
> 
> 形成 code 元素以后再粘贴就可以按 code 的内部语义处理了

那能不能做到在粘贴的时候先形成 code 元素了再粘贴文本进去？

**Comment by TCOTC** [comment]
粘贴转义文本也还有点问题：

[粘贴转义文本.webm](https://github.com/siyuan-note/siyuan/assets/78434827/655f608f-345a-4840-9e6d-824c7f71dbb9)

**Comment by 88250** [comment]
HTML 实体和字符有区别，但是主要是情况比较复制，以实际测试为准。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年5月26日(周日) 中午12:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 有些文本无法在  ``  之间直接粘贴 (Issue #11387)




 
@88250 那文本 &amp;ZeroWidthSpace; 和真正的零宽空格是没法区分的吗？我在段落块里粘贴 &amp;ZeroWidthSpace; 的时候会转换为零宽空格，但手动输入 &amp;ZeroWidthSpace; 就不会

**Comment by 88250** [comment]
做不到的



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年5月26日(周日) 中午12:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 有些文本无法在  ``  之间直接粘贴 (Issue #11387)




  
第一次形成 code 元素时需要做一些标记符/HTML 标签的剔除
 
形成 code 元素以后再粘贴就可以按 code 的内部语义处理了
  
那能不能做到在粘贴的时候先形成 code 元素了再粘贴文本进去？

**Comment by TCOTC** [comment]
> 第一次形成 code 元素时需要做一些标记符/HTML 标签的剔除

感觉好像有点不对劲，标记符/HTML 没法跟文本区分开吗？

**Comment by 88250** [comment]
粘贴的时候没有办法区分。
