### ISSUE TITLE
Improve database table view asset column

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#11389]
1. 移除
<img width="256" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/fe1cad3f-9fb3-4068-b861-894e4ca73bae">

2. 右键点击资源列中图片或链接弹出菜单
3. 菜单添加地址修改、复制、复制为 PNG 功能

**Comment by TCOTC** [comment]
关联 https://ld246.com/article/1715002885146/comment/1715218799795?r=JeffreyChen#comments
