### ISSUE TITLE
手动调整窗口分屏比例后无法保持分屏比例

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11386]
### In what scenarios do you need this feature?

如题，如以下视频，左右或者上下分屏后，只要手动调整了分屏大小，分屏的比例无法固定，右侧和下方的窗口大小会固定不动，希望能改进，保持比例缩放，不然在全屏和之间窗口化切换的时候就会出现窗口比例偏移，又要重新手动调整。

PS：公司电脑的录屏软件似乎不太兼容，颜色不用在意，上下分屏的情况没演示，问题相同

https://github.com/siyuan-note/siyuan/assets/63196026/320feffa-2906-4856-bbbc-154060f6a29d

### Describe the optimal solution

如上视频edge中的实现，左右分屏和上下分屏均能保持各窗口比例

**Comment by TCOTC** [comment]
如果能等比例调整就好了，现在这样确实奇怪

**Comment by 5kyfkr** [comment]
> 如果能等比例调整就好了，现在这样确实奇怪

是滴，以前可能一半一半分屏的时候没发现，一旦全屏和窗口化之间切换问题就很明显了

**Comment by Vanessa219** [comment]
保持比例的话左侧就不会固定，不方便查看。如果是固定的话，在缩放不大的情况下是不用再次拖拽进行调整。看了下 IDEA 也是选左侧进行固定。因此就不进行修改了。
https://github.com/siyuan-note/siyuan/assets/970828/af5ef1fc-8511-422e-a2f7-bc560ab9c175

**Comment by 5kyfkr** [comment]
> 保持比例的话左侧就不会固定，不方便查看。如果是固定的话，在缩放不大的情况下是不用再次拖拽进行调整。看了下 IDEA 也是选左侧进行固定。因此就不进行修改了。 

V姐，俺没看懂视频，左侧不会固定是指左侧文档树边栏的区域嘛？我指的是文档分屏的时候的情况，现在是分屏后右侧和下侧文档宽度调节后是固定的

**Comment by TCOTC** [comment]
> 保持比例的话左侧就不会固定，不方便查看。如果是固定的话，在缩放不大的情况下是不用再次拖拽进行调整。看了下 IDEA 也是选左侧进行固定。因此就不进行修改了。 https://github.com/siyuan-note/siyuan/assets/970828/af5ef1fc-8511-422e-a2f7-bc560ab9c175

这个视频里不变的是边栏，跟本 issue 的需求不一致

**Comment by 5kyfkr** [comment]
https://github.com/siyuan-note/siyuan/assets/63196026/fd340d10-9ded-4a73-83ce-9b6813bffda2

如视频，一开始分屏的时候比例55开没有问题，两边窗口都是依据对半开比例，手动调整后就变成右侧宽度固定了

**Comment by 5kyfkr** [comment]
> 保持比例的话左侧就不会固定，不方便查看。如果是固定的话，在缩放不大的情况下是不用再次拖拽进行调整。看了下 IDEA 也是选左侧进行固定。因此就不进行修改了。 

V姐，或者有没办法在不打开侧边栏的时候保持比例？因为一般我分屏的场景是肯定把边栏设置为浮动以获取最大显示面积的，所以只需要保证不打开边栏下能正常按比例缩放就行

**Comment by Vanessa219** [comment]
只要不拖拽过是会按比例分配的。拖拽过可能需要表示用户就是想着么固定的e 。

**Comment by 5kyfkr** [comment]
> 只要不拖拽过是会按比例分配的。拖拽过可能需要表示用户就是想着么固定的。

但是窗口缩小后或放大，两个分屏宽度就肯定会变，应该两者保持相同的比例，不能牺牲一边的宽度固定另一边

**Comment by TCOTC** [comment]
> 只要不拖拽过是会按比例分配的。拖拽过可能需要表示用户就是想着么固定的。

像 VSCode 拖拽后也是按比例的

> 不能牺牲一边的宽度固定另一边

赞同

**Comment by 5kyfkr** [comment]
还有就比如现在固定了右边宽度，整窗口放大的时候右边放大的比例反而会比左边小，然后在窗口缩小的时候，就是左边比例侵占过多，所以建议还是保持比例缩放

**Comment by Vanessa219** [comment]
但是 IDEA 不是这样的。

**Comment by 5kyfkr** [comment]
直接上AI的分析，实在不行可以做成选项切换。保持右侧宽度的缺点很明显，需要频繁调整，视觉不平衡也会影响美观。按比例的缺点我觉得AI说的比较勉强，不算大问题

在设计软件的分屏功能时，选择保持分屏比例还是固定右侧窗口的宽度，取决于用户的使用习惯和软件的设计目标。以下是两种方案的优缺点分析：

### 保持分屏比例
**优点：**
1. **视觉平衡**：保持分屏比例可以确保两个窗口在视觉上保持平衡，不会因为窗口大小的变化而导致内容显示不均。
2. **内容展示**：对于需要同时查看两个文档内容的用户来说，保持分屏比例可以确保两个文档的内容都能得到适当的展示。

**缺点：**
1. **灵活性较低**：用户可能需要频繁调整分屏比例以适应不同的使用场景，这可能会降低操作的便捷性。
2. **可能影响操作**：如果用户需要在一个窗口中进行详细操作，而另一个窗口仅用于参考，保持分屏比例可能会导致操作窗口的空间不足。

### 固定右侧窗口的宽度
**优点：**
1. **操作灵活**：用户可以根据需要自由调整左侧窗口的大小，而右侧窗口的宽度保持不变，这样可以为操作窗口提供更多的空间。
2. **适应性强**：对于需要在一个窗口中进行大量操作的用户来说，固定右侧窗口的宽度可以提供更好的操作体验。

**缺点：**
1. **视觉不平衡**：如果左侧窗口调整得过大，可能会导致右侧窗口显得过小，影响内容的展示和阅读。
2. **可能需要频繁调整**：用户可能需要根据不同的使用场景频繁调整窗口大小，以达到最佳的使用效果。

### 结论
选择哪种方案更好，需要根据软件的目标用户群体和使用场景来决定。如果软件的用户更倾向于同时查看和比较两个文档的内容，那么保持分屏比例可能是更好的选择。如果用户更注重在一个窗口中进行操作，那么固定右侧窗口的宽度可能更合适。

在实际设计中，可以考虑提供一个设置选项，让用户根据自己的偏好来选择分屏模式，这样可以更好地满足不同用户的需求。同时，提供一个简单直观的用户界面来调整分屏比例，可以提高用户体验。

**Comment by TCOTC** [comment]
怎么说呢，我平时主要操作的是左边的文档，但窗口大小一变化之后左边的文档宽度就变得很奇怪。

当然也会有主要操作右边文档的用户，所以最好的方式就是改为按比例缩放

**Comment by Vanessa219** [comment]
如果需要按照比例的话，打开后不要调整即可。

**Comment by TCOTC** [comment]
> 如果需要按照比例的话，打开后不要调整即可。

但就只能是 1:1 的比例了

**Comment by 5kyfkr** [comment]
> 如果需要按照比例的话，打开后不要调整即可。

所以逻辑不统一，1:1的时候又是按比例，切换比例了又是固定右侧窗口，体验比较割裂，很明显按比例保持更适合文档类型的对比，不会出现文档挤压到很窄的情况
如下图这是全屏的是时候：
![image](https://github.com/siyuan-note/siyuan/assets/63196026/1b202cfa-e213-49e6-a40c-d68fa959da3a)
这是窗口缩小一点的时候，f左侧一下就被挤压得很小，要再次调整
![image](https://github.com/siyuan-note/siyuan/assets/63196026/7062f9eb-0445-416d-8e65-60250ee4ed4f)

**Comment by TCOTC** [comment]
我一般会在全屏和半屏之间切换，结果就是每次左边的文档都几乎会被挤没

**Comment by Vanessa219** [comment]
拆分为多个窗口，然后用系统的桌面功能吧。

**Comment by 5kyfkr** [comment]
> 拆分为多个窗口，然后用系统的桌面功能吧。

https://[github.com/siyuan-note/siyuan/issues/10809](https://github.com/siyuan-note/siyuan/issues/10809)

多窗口做了这个才能保存布局

**Comment by Vanessa219** [comment]
好的，那提高一下优先级
