### ISSUE TITLE
表格选择单元格不灵活

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11388]
表格选择单元格不灵活

https://ld246.com/article/1715067367781

![表格-dSXbXcA](https://github.com/siyuan-note/siyuan/assets/78434827/931af453-0922-490f-bdfe-3d48050a6cda)

**Comment by TCOTC** [comment]
现在没法选中单元格内的部分文本了：

[视频.webm](https://github.com/user-attachments/assets/f98626a2-68de-44a0-9bf0-82c6e8219354)

**Comment by Vanessa219** [comment]
第二点一下找不到解决方案，合并到相关 issue 中处理吧。
