### ISSUE TITLE
数据库点击放大镜筛选后有的列会出现无法编辑的情况

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#11380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/5226690/445d49a6-1077-4fb1-9e95-637eb73533ab)
点击放大镜搜索后，搜索出的列不能编辑，有的列控制台报错，无法编辑
，有的列不报错，可以编辑。
控制台报错如下

VM657:1 Uncaught SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at main.6fee09a28b463b333968.js:1010:6409
    at Array.forEach (<anonymous>)
    at hg (main.6fee09a28b463b333968.js:1010:6160)
    at HTMLDivElement.<anonymous> (main.6fee09a28b463b333968.js:1123:18395)
(anonymous) @ main.6fee09a28b463b333968.js:1010
hg @ main.6fee09a28b463b333968.js:1010
(anonymous) @ main.6fee09a28b463b333968.js:1123

数据库不方便提供，看看这些信息能定位吗
已关闭所有插件、代码片段、使用daylight主题

### Expected result

可以编辑

### Version environment

```markdown
- Version: 当前版本 v3.0.13
- Operating System:  win11
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
你好，这个无法看出问题来，麻烦脱敏后导出 .sy.zip 发给我们调试看看 845765@qq.com

**Comment by 88250** [comment]
@TCOTC 你那里控制台有报错吗？

**Comment by TCOTC** [comment]
> @TCOTC 你那里控制台有报错吗？

当时没留意，后面就复现不了了

**Comment by 88250** [comment]
好的，等楼主再看看，记得用新版本帮忙测试。

**Comment by TCOTC** [comment]
关联 #11407

**Comment by 88250** [comment]
楼主这个库有多少行？

**Comment by jl0476** [comment]
> 楼主这个库有多少行？

332行，所以我觉得可能是一个问题 @88250

**Comment by 88250** [comment]
那估计是同一个问题了，等我们先修复那个后你再测测看。

**Comment by jl0476** [comment]
> 那估计是同一个问题了，等我们先修复那个后你再测测

应该是同一个问题，我把所有行都加载了就可以修改，
不全量加载，有分页的时候，就修改不了

**Comment by 88250** [comment]
好的，那就关闭这个 issue 了，那个 issue 中修复。
