### ISSUE TITLE
块引浮窗显示文档标题

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11392]
### In what scenarios do you need this feature?

其实一直以来都挺希望块引浮窗能显示文档标题的

目前在文档聚焦，文档标题会一直显示，而浮窗显示块，就算是文档块，文档标题也一直不显示，渲染表现并不统一
文档聚焦：
![Clip_2024-05-14_21-25-49](https://github.com/siyuan-note/siyuan/assets/60436214/6b97fe21-13f9-4b88-b99b-1672eb1e5879)
浮窗聚焦：
![Clip_2024-05-14_21-26-25](https://github.com/siyuan-note/siyuan/assets/60436214/6cb9a5d4-9ab6-429c-96e4-87ea253723a3)

使用MOC管理文档的块引的时候，希望复制或更改文档标题，现在只能打开文档进行，而如果悬浮窗显示标题，则可以更轻松做到

如果是段落块的块引通过浮窗查看，显示标题也能知道所属的文档标题，虽然面包屑也有文档标题信息，但是并不明显，而且还有路径信息干扰

### Describe the optimal solution

浮窗始终显示文档标题

### Describe the candidate solution

此外还希望搜索面板的聚焦也能显示文档标题

**Comment by 88250** [comment]
标题太占位置所以不考虑了，还是看面包屑吧，谢谢。
