### ISSUE TITLE
希望可以修改代码块样式word-break属性值

### ISSUE THREAD

**Issue by Kaida-Amethyst** [siyuan-note/siyuan#11408]
### In what scenarios do you need this feature?

代码块样式现在的属性现在有一个word-break: break-all，当代码块中的某一行代码比较长的时候，会直接从单词中间进行截断，会比较影响观感。

![1](https://github.com/siyuan-note/siyuan/assets/73624913/76ccbcee-da07-4608-894e-f0fdcc61a464)

![3](https://github.com/siyuan-note/siyuan/assets/73624913/9eacfa9c-25ce-40e3-a6b1-bb56b1d2017c)

### Describe the optimal solution

希望能把这个word-break: break-all修改一下，去掉，或者修改成word-break:normal可能会好一些，或者不直接写在style里面，而是写到其它class里面这样好改一些：

修改后的样子

![2](https://github.com/siyuan-note/siyuan/assets/73624913/d1dd5084-e3a7-4459-a009-04102509b9d9)

**Comment by 88250** [comment]
这个之前讨论过，请参考 https://github.com/siyuan-note/siyuan/issues/11248

**Comment by 88250** [comment]
抱歉，那个讨论是行级代码的，这个是代码块。

@Vanessa219 有空看看哦。

**Comment by Kaida-Amethyst** [comment]
额(⊙o⊙)…标题.....“bread-word”?应该是break-word吧^ ▽ ^
