### ISSUE TITLE
The selection options are inconsistent after pasting data into the database

### ISSUE THREAD

**Issue by qmdx00** [siyuan-note/siyuan#11409]
数据库导入已有单选值，高亮颜色和设置的不同

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/27898261/802cd8ae-ee9b-4e2e-8553-90340287fbd6

对于数据库已有的单选值，导入的数据有相同的值时，高亮的颜色与已设置的单选值的颜色不同，需要手动重新选择单选值

### Expected result

希望导入的数据单元格的值与设置的单选值相同时，自动设置对应的高亮

### Version environment

```markdown
- Version: v3.0.14
- Operating System: macOS Sonoma 14.0
- Browser (if used):
```

### Log file

.

**Comment by TCOTC** [comment]
确实，文档刷新之后颜色也不会统一

**Comment by TCOTC** [comment]
@88250 除了颜色的问题之外还有个问题，这些粘贴出来的选项不在候选列表里：

[表格.webm](https://github.com/siyuan-note/siyuan/assets/78434827/39f524c8-c8ad-4826-ab10-65831a2b7510)

筛选里也没有：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d2d6afe0-b59f-4e24-b7e6-92f619b0d5eb)

**Comment by 88250** [comment]
收到，会一并解决。

**Comment by TCOTC** [comment]
@88250 现在没法完全粘贴了，而且粘贴之后撤回不了：

[表格.webm](https://github.com/siyuan-note/siyuan/assets/78434827/562f3f2f-6913-44c2-8e12-4df81c185297)

**Comment by 88250** [comment]
@Vanessa219 确实有问题，再看看。

**Comment by Vanessa219** [comment]
f6a4ccfc7dfed0120f932c1d86c932d5f06be98f

**Comment by TCOTC** [comment]
> 现在没法完全粘贴了，而且粘贴之后撤回不了：

@Vanessa219 还是不行
