### ISSUE TITLE
Prompt for recovery method and retention days settings when deleting documents

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11400]
删除文档时提示恢复方式和保留天数设置

https://ld246.com/article/1715007543144

**Comment by TCOTC** [comment]
供参考

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ba9e3950-9c6f-424c-bab5-278085c0ed8b)

**Comment by TCOTC** [comment]
@88250 多个空格：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/13363b16-0b7a-496c-9e7e-7b840cc7cd68)

**Comment by 88250** [comment]
稍后调整

**Comment by TCOTC** [comment]
@88250 我感觉数字没必要用斜体，斜体感觉有点怪

![image](https://github.com/siyuan-note/siyuan/assets/78434827/35e85465-cb7d-43d5-a837-7076e2c0efa5)

普通文本就行了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e109b762-84cd-49a4-93cb-83bee279268a)

**Comment by 88250** [comment]
好的
