### ISSUE TITLE
每个文件最少要有一个文件历史

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#11404]
### In what scenarios do you need this feature?

有好多次修改了文件想看看都改了什么，就发现没有一个文件历史。可能是历史生成间隔时间太长……
感觉非常不安全，有好多文件都没有文件历史，想看的时候才发现……

### Describe the optimal solution

1. 每次打开后都应该有一个最新的文件历史。
2. 每个文件至少要有一个文件历史。

感觉第一个效果会好点，可以100%保证每次都有修改前历史文件。

**Comment by TCOTC** [comment]
有道理。如果有比较长的一段时间没有编辑过，就会没有任何历史

![image](https://github.com/siyuan-note/siyuan/assets/78434827/61971644-086e-4501-afe9-e7000cd0c2ed)

**Comment by snoopydai** [comment]
有这个功能好像确实会更好，比如手误修改了某个文档，但是一眼没看出来。过了挺长一段时间后，重新回看那篇笔记，才发现到有变动，但已经没办法回溯了。

**Comment by 88250** [comment]
这个不考虑了，建议使用数据快照。

**Comment by shuojie819** [comment]
> 这个不考虑了，建议使用数据快照。

今天突然发现一个失效的嵌入块，使用目录搜素查询整个工作空间发现除了呢查到这个失效的嵌入块，其他啥也没有，我怀疑源内容被修改之前没有生成文件历史……

感觉这个文件历史生成规则真的很重要，想知道为什么不考虑……
使用了一下obsidian，不知道他的生成规则是什么，但是每一次修改都会被记录。

**Comment by shuojie819** [comment]
试了一下obsidian的，新建了几个文件试了一下，每个文件至少会有一个文件历史。
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/57c9bc6a-e52d-4801-8208-6cee9ae9dfd6)

**Comment by TCOTC** [comment]
> 新建了几个文件试了一下，每个文件至少会有一个文件历史

建议再看一下这个历史能保留多久

**Comment by shuojie819** [comment]
> > 新建了几个文件试了一下，每个文件至少会有一个文件历史
> 
> 建议再看一下这个历史能保留多久

和思源一样，自己设置的
![图片](https://github.com/siyuan-note/siyuan/assets/72399630/155920ac-cd30-4b38-8094-504aee49e046)

**Comment by TCOTC** [comment]
> 和思源一样，自己设置的

> 每个文件至少会有一个文件历史

还得看看这个时间过了之后还会不会保留最近的一次历史

**Comment by shuojie819** [comment]
> > 和思源一样，自己设置的
> 
> > 每个文件至少会有一个文件历史
> 
> 还得看看这个时间过了之后还会不会保留最近的一次历史

……，最少设置1天，明天晚上再看……

**Comment by shuojie819** [comment]
> > 和思源一样，自己设置的
> 
> > 每个文件至少会有一个文件历史
> 
> 还得看看这个时间过了之后还会不会保留最近的一次历史

这是我今天第一次打开obsidian，昨天的文件历史已经消失了，但是他有一个最新的文件历史（可能在我打开文件的时候就产生了……也可能是其他）
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/e50b55f9-8d56-439a-b036-39327c316877)

**Comment by TCOTC** [comment]
看日期好像是今天的

**Comment by shuojie819** [comment]
> 看日期好像是今天的

是的呀，所以我说可能是在我打开文件的时候产生的……
