### ISSUE TITLE
中英文自动空格的问题

### ISSUE THREAD

**Issue by wrwe3888** [siyuan-note/siyuan#1140]
之前有中英文自动空格的功能，后来取消了。
我来 之类的，中英文之间有自动间距，但不是空格。
希望思源能开发出这个功能。

另外，之前用了思源的这个功能，现在这个功能没有了，
导致后面的中英文，有的有空格，有的没空格。
希望能有个功能，对所有文档的中英文空格，进行统一调整。

**Comment by 88250** [comment]
你好，这个只能通过手动加了，抱歉……

**Comment by wrwe3888** [comment]
可以手动添加空格，但是空格有问题，对吧？
不然思源了不会去掉这个功能。
那之前添加的空格，可以批量去掉吗？

**Comment by 88250** [comment]
空格逻辑和很多地方有冲突，所以去掉了。建议先不要批量去掉，如果确实有必要再手工处理。思源里面目前也没有方法可以批量去掉……

**Comment by roverway** [comment]
> 可以手动添加空格，但是空格有问题，对吧？
> 不然思源了不会去掉这个功能。
> 那之前添加的空格，可以批量去掉吗？

你可以试试vscode之类的编辑器，用正则表达式批量去掉空格。
