### ISSUE TITLE
嵌入块需求

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#11410]
https://ld246.com/article/1715675280672

**Comment by 88250** [comment]
1. https://github.com/siyuan-note/siyuan/issues/11055
2. 不考虑了
3. 通过引用计数可以判断
4. 这个无法判断的，因为嵌入块可以自定义 SQL 脚本

感谢反馈。

**Comment by shuojie819** [comment]
还是希望可以考虑一下：
2. 移除首个最顶级的标题很有必要（想引用那一个标题下面的内容，当前文档也要增加相似的标题就会有两个相同的标题，效果非常不理想……【表达的可能不是很清晰……】）
3. 通过引用是可以判断，但是……谁会一直看引用...，现状是每次都是有找不到的ID时，我才会去找是那个丢失了……
4. 3如果做好的话，4就是不需要的……（3和4都是为了不产生不明不白的找不到ID所存在的）

**Comment by shuojie819** [comment]
第4点其中一个感觉也是有必要的，【不存在符合条件的内容块】应该在【列出引用失效的块】中显示
![image](https://github.com/user-attachments/assets/6411ac06-756f-456c-91ee-11a80f759d10)
