### ISSUE TITLE
Preview mode tooltip and snackbar are not localized

### ISSUE THREAD

**Issue by mpcjazz** [siyuan-note/siyuan#11416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Tooltips and Snackbars displayed when hovering over icons in preview mode are in Chinese regardless of the set language.

### Expected result

They need to be displayed in the language currently set in the UI.

### Screenshot or screen recording presentation

![Image 001](https://github.com/siyuan-note/siyuan/assets/6954310/e47e2bcc-f060-4862-976a-7d704aea1ca1)

### Version environment

```markdown
- Version: 3.0.14
- Operating System: Windows
- Browser (if used):
```

### Log file

N/A

**Comment by TCOTC** [comment]
我试着 PR 一个
