### ISSUE TITLE
能否对公式于\(...\)内联数学和\[...\]显示的方程进行支持 

### ISSUE THREAD

**Issue by noenif** [siyuan-note/siyuan#11412]
### In what scenarios do you need this feature?

目前环境中是支持内联$ 和块模式$$的公式,当我开启 渲染的时候会显示渲染.

能否添加一个功能也支持显示\(...\)内联数学和\[...\]显示的方程.

因为有些地方的公式是显示\(...\)内联数学和\[...\]显示的方程.

这样我复制下来,我自己要写一个js脚本去替换.

能解决,但是我感觉很蠢,当然这是因为来源很广泛.
当然我看到一群说提示词的更蠢,我测试下带提示词和不带提示词 回答肯定是不带这种没意义的提示词的好.

### Describe the optimal solution

大佬我看您这边使用的是katex,能否来一个selector 动态配置 让用户选择那种显示呢.

**Comment by 88250** [comment]
抱歉，其他符号的语法不考虑支持了。
