### ISSUE TITLE
Font Size and Code Tab Spaces setting changed to select on the mobile

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11415]
我知道为什么偶尔会有用户的移动端字号变得超级大了，随手划几下就无意中调整了字号：

https://github.com/siyuan-note/siyuan/assets/78434827/f6b87928-7927-4132-8ae9-3adbc2cc2de2

~~https://github.com/siyuan-note/siyuan/assets/78434827/92e1a707-bb97-4be5-a42d-b5669136661e~~

**Comment by 5kyfkr** [comment]
看不到视频内容，是黑屏的

**Comment by TCOTC** [comment]
调整一下网页缩放，`Ctrl+R` 刷新一下网页再等待视频完全加载，看看行不行

**Comment by 5kyfkr** [comment]
> 调整一下网页缩放，`Ctrl+Shift+R` 刷新一下网页再等待视频完全加载，看看行不行
> 
> 不知道会不会和这个视频的编码有关

手机上可以，电脑上没有hevc解码器

**Comment by 5kyfkr** [comment]
确实调整字号容易被误操作滑动到了，可以改成滚动选择数值或者放到页面最前端

**Comment by TCOTC** [comment]
我换了编码重新传了视频，你再看看行不行

**Comment by 5kyfkr** [comment]
> 我换了编码重新传了视频，你再看看行不行

可以了

**Comment by Vanessa219** [comment]
这个是因为在滑动的过程中点击到了，还没想要要怎么避免。

**Comment by TCOTC** [comment]
@Vanessa219 比如只有点这里才能拖动，点其他地方无效：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/be16ce75-ac76-46b1-8156-e4df7fb7d34d)

**Comment by Vanessa219** [comment]
这个是操作系统定义的，没有接口修改。

**Comment by TCOTC** [comment]
那就把 slider 默认折叠起来，给个按钮展开？

**Comment by Achuan-2** [comment]
建议把字号调整的按钮改为数字spinner样式
![Clip_2024-05-19_22-58-38](https://github.com/siyuan-note/siyuan/assets/60436214/104c6502-03f8-4941-9fc5-37279fad4cd3)

原因：
1. 平板端、手机端调节字号由于没有鼠标，不好精确调整，很容易调过小或过大
2. slider样式适合大范围的变动，字号的调整一般比较小

**Comment by TCOTC** [comment]
> 不好精确调整，很容易把字号调过小或过大，比如只是想把14px改成17px，就很费劲

这个确实是，我也发现了

**Comment by Vanessa219** [comment]
移动端还要输入的话会不会比较麻烦？

**Comment by TCOTC** [comment]
移动端一般用不到那么大的字号，调字号都是小幅度调整的，输入应该比滑条好

**Comment by Vanessa219** [comment]
要不下拉选择？

**Comment by 5kyfkr** [comment]
> 要不下拉选择？

可以的，就给30px以下字号都完全够用了

**Comment by Vanessa219** [comment]
数字spinner 是？

Pad 端的优化可以单独放到相关 issue 中。

**Comment by Achuan-2** [comment]
> 数字spinner 是？
> 
> Pad 端的优化可以单独放到相关 issue 中。

就是这个样式
![Uploading image.png…]()
思源设置里，除了字号和tab空格用slider，其实设置的数字输入都是用这个样式

**Comment by Vanessa219** [comment]
滑动在桌面端可能会更好用一点吧。

**Comment by TCOTC** [comment]
感觉滑动在桌面也没什么用，我都是用 `Ctrl+滚轮` 调字号的

**Comment by 5kyfkr** [comment]
桌面端也挺难蚌，要鼠标移上去才能看到现在的字号，而且最大字号到72完全没必要，到30都绰绰有余了

**Comment by TCOTC** [comment]
这个 72 字号在我调试的时候还是能用到的

**Comment by 5kyfkr** [comment]
gpt写的代码，可以试试，直接记事本输进去保存为html打开
![image](https://github.com/siyuan-note/siyuan/assets/63196026/facd0409-5fa0-4e50-bf6e-70f7252ac81e)


```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>字号调节</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
    }
    input[type="number"] {
      width: 100px;
      padding: 5px;
      font-size: 16px;
    }
    button {
      padding: 5px 10px;
      font-size: 16px;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <h2>字号调节</h2>
  <input type="number" id="fontSizeInput" value="16">
  <button id="decreaseBtn">-</button>
  <button id="increaseBtn">+</button>

  <script>
    const fontSizeInput = document.getElementById('fontSizeInput');
    const decreaseBtn = document.getElementById('decreaseBtn');
    const increaseBtn = document.getElementById('increaseBtn');

    decreaseBtn.addEventListener('click', () => {
      fontSizeInput.stepDown();
      updateFontSize();
    });

    increaseBtn.addEventListener('click', () => {
      fontSizeInput.stepUp();
      updateFontSize();
    });

    function updateFontSize() {
      const newFontSize = fontSizeInput.value + 'px';
      document.body.style.fontSize = newFontSize;
    }
  </script>
</body>
</html>
```

**Comment by TCOTC** [comment]
我觉得没必要，这种上下箭头够用了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2279053c-771d-4854-9650-7fbd04af5d86)

**Comment by 5kyfkr** [comment]
> 我觉得没必要，这种上下箭头够用了：

桌面端有这个够了，移动端还没有这个

**Comment by TCOTC** [comment]
@Vanessa219 为啥移动端的 Tab 空格数不能为 0 呢？

**Comment by Vanessa219** [comment]
不输入就是 0 了。

**Comment by TCOTC** [comment]
我更新之后默认变成 4 了，没有 0 ：

![Screenshot_2024-05-28-17-30-52-03_ed1bdeca7a858bb430bfb9c256856672.jpg](https://github.com/siyuan-note/siyuan/assets/78434827/a8e2c1dc-521c-4a90-9883-d5e129aa21d4)

**Comment by 5kyfkr** [comment]
我也是，没有0了

**Comment by TCOTC** [comment]
> 不输入就是 0 了

话说这个是选项，没得输入啊

**Comment by Achuan-2** [comment]
> > 不输入就是 0 了
> 
> 话说这个是选项，没得输入啊

所以我才说尽量是输入框，而不是选项框，选项框并不适合数字输入。

**Comment by TCOTC** [comment]
> 所有数字可能不能完全列举

但实际上那两个地方已经是每个数字都列出来了（除了 `0`）

**Comment by TCOTC** [comment]
@Vanessa219 Tab 空格数不能设置为零，真的没问题吗？

![Screenshot_2024-06-04-08-13-56-25_ed1bdeca7a858bb430bfb9c256856672.jpg](https://github.com/siyuan-note/siyuan/assets/78434827/dd179494-fb26-467f-a374-e7daceec73fa)

**Comment by TCOTC** [comment]
@88250 看看？

**Comment by Vanessa219** [comment]
tab 设置为 0 的意义是？

**Comment by TCOTC** [comment]
意义是跟 PC 保持一致

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fcd4ddce-e1f0-4347-bfe6-57e5c31a5ab4)

**Comment by Vanessa219** [comment]
写忘记了，如果是0的话就表示为 tab，已添加。
