### ISSUE TITLE
Attribute Panel - Database attributes custom sorting

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#11428]
数据库属性面板拖拽排序异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下视频，数据库属性面板拖拽排序位置会跳变，无法固定，可重复复现

https://github.com/siyuan-note/siyuan/assets/63196026/f6f147e2-4507-4821-8ef7-bd584d30fe5b

测试文档：
[知识库.sy.zip](https://github.com/siyuan-note/siyuan/files/15330381/sy.zip)

### Expected result

能正常排序不跳动，日后这个面板如果集成到页面顶部也是很关键的。

### Version environment

```markdown
- Version: 3.0.14
- Operating System: win10
- Browser (if used):
```

### Log file

无报错

**Comment by 88250** [comment]
发现个设计问题：当存在多个视图时，展示的顺序无法确定使用哪一个，目前使用的是最近设置显示的视图 https://github.com/siyuan-note/siyuan/issues/9319

估计得改成独立的自定义排序，即属性面板中的字段顺序单独存取，不和视图中的顺序一致。

**Comment by TCOTC** [comment]
> 改成独立的自定义排序，即属性面板中的字段顺序单独存取，不和视图中的顺序一致

同一个数据库中有 A B 两个条目，更改 A 条目的数据库属性顺序后，B 条目的数据库属性顺序应该与 A 条目一致。

而不是每个条目都是单独的顺序

**Comment by 88250** [comment]
嗯，我指的独立是和视图独立。

**Comment by 88250** [comment]
@Vanessa219 新增 tx `sortAttrViewKey`
