### ISSUE TITLE
Improve HTML code block clipping

### ISSUE THREAD

**Issue by jim555666888** [siyuan-note/siyuan#11427]
3.0.14复制代码块的问题：丢失了代码缩进，导致代码挤在一起

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="1580" alt="image" src="https://github.com/siyuan-note/siyuan/assets/105782402/8e191c52-559a-4c87-82c3-8416c35fcdaf">

ru如图所示

### Expected result

希望能修正

### Version environment

```markdown
- Version: 3.0.14
- Operating System: macos
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请发一下网址

**Comment by TCOTC** [comment]
我这里复制 ChatGPT 的代码的缩进没问题

**Comment by jim555666888** [comment]
https://github.com/siyuan-note/siyuan/assets/105782402/38dfeb69-6a16-4974-9856-4e72b8c284c0


换不同的主题均这样，在更新3.0.14或者3.0.13时出现的问题

**Comment by jim555666888** [comment]
> 请发一下网址

我传了视频，就是通用的chatgpt网址
以前版本粘贴是没问题的

**Comment by 88250** [comment]
下个版本改进。
