### ISSUE TITLE
索引更新不及时

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#11429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/TinkMingKing/siyuan-plugins-index/issues/57

### Expected result

fix

### Version environment

```markdown
- Version: 3.0.14
- Operating System: windows
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
索引是异步更新的，有的场景如果需要同步获得索引提交结果，请使用 https://github.com/siyuan-note/siyuan/issues/10005 来判断。
