### ISSUE TITLE
数据库属性面板属性名前显示图标

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11438]
### In what scenarios do you need this feature?

不显示图标的话不太方便判断列类型：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/67a46401-15d8-4c18-952d-9f5ea1241948)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c42b49c7-db04-4126-b0b8-f654340fb5ec)

### Describe the optimal solution

数据库属性面板属性名前显示图标

### **这个也跟视图保持独立**

**Comment by 5kyfkr** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/63196026/24e03393-aca7-4bb5-8d57-9df3adb2f818)
我这默认主题和Asri都有图标

**Comment by TCOTC** [comment]
我检查一下插件和代码片段
