### ISSUE TITLE
After selecting the doc in the doc tree, `Ctrl+D` will not duplicate it

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11432]
文档树选中文档后 `Ctrl+D` 复制为副本无效

---

`Ctrl+点击` 选中文档后 `Ctrl+D` 复制为副本无效

确实是有这个快捷键的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6fd6aa3c-6c57-45d4-9e23-ee1277f30192)

**Comment by 88250** [comment]
文档树上选中后 Ctrl+D 确实无效 @Vanessa219

**Comment by 88250** [comment]
呃，我测试的是单选，Ctrl+点击 多选的话不支持 复制为副本

**Comment by TCOTC** [comment]
我测的也是单选

**Comment by 88250** [comment]
Ctrl+点击 是多选哦，单选的话直接选择就行了，那我们改一下标题。

**Comment by TCOTC** [comment]
`Ctrl+点击` 只点一次的话就是单选了

**Comment by 88250** [comment]
好的，反正就是选中然后 Ctrl+D 无效，应该是一个问题，等 @Vanessa219 看看
