### ISSUE TITLE
希望把《取消绑定块》下移

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11443]
### In what scenarios do you need this feature?

《取消绑定块》不是高频操作，和《添加到数据库》靠太近了，希望能下移到《删除》的上面

![image](https://github.com/siyuan-note/siyuan/assets/67137548/1a4733d4-ea0d-4d2f-a15f-0995265b2d3c)

### Describe the optimal solution

。。

**Comment by 88250** [comment]
有道理，稍后改进。
