### ISSUE TITLE
0.62 清理无效资源有 bug

### ISSUE THREAD

**Issue by hopebird** [siyuan-note/siyuan#1144]
### 描述问题 Describe the problem

1、清理无链接资源的时候，点击笔记本后面的清理图标无效，不能批量清理，只能一条一条单独点清理图标清理；
2、就算一条一条清理完毕，asset 文件夹里的文件仍然存在，没有被删除掉。
### 期待的结果 Expected result

自动清理、批量清理、扔到系统回收站即可。
### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by hopebird** [comment]
过了会儿又看了下，单独清理是能删除的，但要等一会儿。批量清理还是不行。

**Comment by 88250** [comment]
请贴一下日志文件，谢谢。

**Comment by 88250** [comment]
063 已经修复，感谢反馈。
