### ISSUE TITLE
拖动文字块/内嵌文件块到引用链接上，能够将拖动的内容移动到引用的页面中去

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#11449]
### In what scenarios do you need this feature?

有时我会在同一个page下创建很多引用链接来管理不同的内容，如果有了这个功能，就可以方便的将不同类别的块快速拖动到不同的引用中去，就像拖放到文件夹中去一样，大大提高效率。

### Describe the optimal solution

在引用类上添加eventlistener，当监控到有块被拖放在其上时，将它移动到引用指向的页面中，(可以默认设置添加在尾部)

**Comment by 88250** [comment]
感谢提议，这个用插件实现更适合一些。

**Comment by jiewangjs** [comment]
非常感谢您的见解，但在下对于相关开发技能不太精通，没有能力开发出来，您要是有空闲，可否开发一下作为官方插件供用户下载使用？

**Comment by 88250** [comment]
抱歉，这个估计只能靠社区开发者了。
