### ISSUE TITLE
Documents exported in the doc tree can no longer be imported

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11447]
在文档树导出的文档无法再导入

v3.0.15-dev1 ，使用新建的工作空间测试

[[测试].sy.zip](https://github.com/siyuan-note/siyuan/files/15350107/sy.zip)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cbfbece5-a7bc-41a5-b9de-92f0cd862778)

文档里只有这个标题和一串数字：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/985341dd-0674-402d-8421-c35a43d0ea8e)

在文档树导出该文档之后无法再导入

**Comment by 88250** [comment]
我这里可以正常导入这个 sy.zip

**Comment by 88250** [comment]
对了，看一下内核日志。

**Comment by TCOTC** [comment]
我刚刚发现我从 GitHub 再下载的是可以导入的，但我本地的这个就是导入不了

---

我怀疑是压缩包名的问题，压缩包名是 `[测试]` 就导入不了，改成其他的就可以导入

**Comment by 88250** [comment]
感谢，确实是文件名匹配的问题，下个版本修复。
