### ISSUE TITLE
Use real theme style value replace var in preview mode

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11458]
导出预览模式优化：css变量替换为实际值

### In what scenarios do you need this feature?

发现3.0.15 dev1的预览模式可以显示设置的blockquote背景色了
![Clip_2024-05-19_10-17-59](https://github.com/siyuan-note/siyuan/assets/60436214/b1d0d07c-b523-4dfd-bdf4-6308b7ae762e)

但是有一个问题，复制到微信公众号中的css如果要生效，就不能用变量var(--b3-card-warning-background)或者color: var(--b3-card-warning-color)，需要硬编码指出颜色是什么、背景色是什么，否则不仅仅不能显示，我后续自己用外部css设置blockquote的样式也会失效（可能是检测到变量不存在，导致针对这个块的自定义css也没用了 ）
![Clip_2024-05-19_10-19-25](https://github.com/siyuan-note/siyuan/assets/60436214/14d2830f-28f0-4b27-8566-2171aca8e1ae)

改成这样才可以把样式粘贴到微信公众号了
![Clip_2024-05-19_10-29-17](https://github.com/siyuan-note/siyuan/assets/60436214/501ec22a-f356-4d9b-90d2-b19a4b04218b)

![Clip_2024-05-19_10-29-00](https://github.com/siyuan-note/siyuan/assets/60436214/2f1ecdea-4b51-43fb-b825-6af199be65fb)

### Describe the optimal solution

导出预览模式优化，复制到微信公众号，css变量全部替换为实际值，包括外部css和DOM的style属性，都进行处理，这样思源笔记的样式基本可以完美复制到微信公众号

### Describe the candidate solution

设置的块背景色、字体颜色不在html元素显示，这样我可以用自定义css自行设置样式，而不像现在，官方并不支持复制样式到微信公众号，自定义css也无法成功显示样式

### Other information

无

**Comment by 88250** [comment]
似乎行级元素也是变量，这个没有影响吗？

**Comment by Achuan-2** [comment]
> 似乎行级元素也是变量，这个没有影响吗？

有影响的，用变量就都无法正常显示。

**Comment by 88250** [comment]
这个暂时没有太好的方案，等后续再考虑了。

**Comment by 88250** [comment]
尝试改进了一下，需要帮忙多测测，谢谢。

**Comment by Achuan-2** [comment]
好的谢谢！

**Comment by TCOTC** [comment]
@88250 这个改变会影响到 PDF 导出吗？还是只影响导出预览？

**Comment by 88250** [comment]
不影响 PDF 导出，只影响预览才对。

**Comment by Achuan-2** [comment]
![Clip_2024-05-21_13-37-38](https://github.com/siyuan-note/siyuan/assets/60436214/a2120ba7-bd02-4125-a970-f984e9932d13)
更新3.0.15了，感觉没有变化，无论是思源对样式的css（比如超链接样式）还是给块、文字添加背景色、字体颜色都依然用的是变量

**Comment by 88250** [comment]
@TCOTC @Achuan-2 抱歉，是我加错地方了，现在影响的是 PDF 不是导出预览，稍后改进。

**Comment by Achuan-2** [comment]
@88250 发现还有问题
比如如果theme.css设置的是    --b3-font-background2: var(--b3-card-warning-background);，背景色2在预览模式会变为var(--b3-card-warning-background)，而不是实际颜色值

**Comment by 88250** [comment]
稍后改进

**Comment by Achuan-2** [comment]
辛苦！

**Comment by Achuan-2** [comment]
现在应该只处理了DOM的css变量，想问问外部的css加的样式，有办法把变量替换为实际的值吗，比如blockquote的color和background还是变量
![PixPin_2024-11-17_12-35-29](https://github.com/user-attachments/assets/2189d201-6490-4f4d-a3d3-818fab11fda9)

**Comment by 88250** [comment]
外部的 css 没有解析，只解析 theme.css
