### ISSUE TITLE
Improve the direction of text, table columns, and horizontal overflow

### ISSUE THREAD

**Issue by CyRamos** [siyuan-note/siyuan#11455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Hey team, 
RTL user over here. 
When I grab some block of text (for example let's say it's a headline) and drag it next to another block on the left
It changes the order of the text in the wrong direction. 
## Wrong Example from SiYuan:
![image](https://github.com/siyuan-note/siyuan/assets/40651473/c4468c5c-e8e4-4c90-8f3a-33b285d31f03)

![image](https://github.com/siyuan-note/siyuan/assets/40651473/7541f73e-deab-452e-ba9a-02daea81f4ae)

## Expected result from Notion:
![image](https://github.com/siyuan-note/siyuan/assets/40651473/0c0df1f4-0e2b-44fc-9d92-f3f98cf8a5a5)

![image](https://github.com/siyuan-note/siyuan/assets/40651473/f4f2eda9-586b-4abf-b497-b97768ad1dda)

### Version environment

```markdown
- Version: v3.0.14
- Operating System: Windows 11 Pro
- Browser (if used): Brave, however, I'm using most with the desktop version. If it's necessary I'll use the web version.
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/15367111/siyuan.log)

**Comment by TCOTC** [comment]
I can reproduce this

[RTL.webm](https://github.com/siyuan-note/siyuan/assets/78434827/5010d04e-1d7d-4909-b692-c640b41a5184)

**Comment by CyRamos** [comment]
> I can reproduce this
> 
>  RTL.webm

Hey @TCOTC 
Thanks for the answer, I didn't mention however this feature is also enabled in my workspace. 
![image](https://github.com/siyuan-note/siyuan/assets/40651473/66b99615-c25d-4dae-85cb-4dea82c27be7)

in your video, it seems there is the same issue (when you drag the block left it appears in the right)

**Comment by CyRamos** [comment]
Hey team
Another mention: when writing in English (General RTL enabled in Editor but in document align to left).
The punctuation is also upside down:

![image](https://github.com/siyuan-note/siyuan/assets/40651473/e86c5858-796b-4139-8ddf-4b36b7c19715)

**Comment by Vanessa219** [comment]
This is quite correct for languages written right to left: the terminating punctuation mark appears at the end, i.e. on the left.

**Comment by CyRamos** [comment]
> This is quite correct for languages written right to left: the terminating punctuation mark appears at the end, i.e. on the left.

If it helps for references - in the Notion app where the blocks are auto-rotated (attach photo below) 
when it's RTL or LTR it's known to rotate the block automatically. 

![image](https://github.com/siyuan-note/siyuan/assets/40651473/77e15d80-51e3-4542-8e62-f5710e7ab90a)

**Comment by Vanessa219** [comment]
Rotation may not solve the problem, RTL is also language dependent.

**Comment by forabi** [comment]
Most apps which support auto-direction use some heuristics (if the paragraph starts with an RTL language character, this paragraph will be in RTL). Applying this setting to the whole editor is not very useful because most people will have to write some text in LTR languages along with RTL text in the same document.

**Comment by Vanessa219** [comment]
We can use the block menu to set each block individually.

<img width="669" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/78264577-1f3f-47c2-b20c-9a18695dd5aa">

**Comment by CyRamos** [comment]
> We can use the block menu to set each block individually.
> 
> <img alt="image" width="669" src="https://private-user-images.githubusercontent.com/970828/337863386-78264577-1f3f-47c2-b20c-9a18695dd5aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMDg1MzksIm5iZiI6MTcxOTAwODIzOSwicGF0aCI6Ii85NzA4MjgvMzM3ODYzMzg2LTc4MjY0NTc3LTFmM2YtNDdjMi1iMjBjLTlhMTg2OTVkZDVhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQyMjE3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjI1ZGM0NTIxYTBiYjRjZjkwZmI2ODc1ZDEyN2QwNTcxNDgxNzkyNGU4NGY4NTZhYTI0MDVmYzIxNjk3ZmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OZPIrPzoKEXdP4qXjfeTo6x_rOL22RDH9pi8Hfvb4sI">

Glad to hear that does it mean in the future the text will automatically be RTL / LTR based on the block?

**Comment by Vanessa219** [comment]
This requires manual setting, there is no automatic setting rule.

**Comment by CyRamos** [comment]
> This requires manual setting, there is no automatic setting rule.

I see, first of all, thanks for the answer
Second -  this is the current result for choosing in-block RTL / LTR (as mentioned above) + aligning the text right (ALT+R) 

![image](https://github.com/siyuan-note/siyuan/assets/40651473/d01f4db6-ddc2-42c3-b9a9-baf227073631)

**Comment by Vanessa219** [comment]
Because there is a block operation on `1.`, only the paragraph block has rtl.
It is normal when previewing.

<img width="995" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/2ede168b-3662-455f-967c-e48f10ac0158">
