### ISSUE TITLE
关于多级笔记导出为 PDF 时目录缺失、代码高亮缺失、分页符缺失的 BUG 

### ISSUE THREAD

**Issue by zznjobs** [siyuan-note/siyuan#11456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

关于多级笔记导出为 PDF 时目录缺失、代码高亮缺失、分页符缺失的 BUG - 链滴
https://ld246.com/article/1716049123999

### Expected result

我还观察到，有时候单篇大笔记导出 PDF 的时候，有时候也会有目录缺失的现象。
这个时候只需要手动点一下优化排版，就恢复正常了。

不知道导出多层笔记是不是会面临内存问题。
我觉得宁可导出速度慢一点，也要功能完整。
最好是能有个导出进度条，或者预估时间之类的东西，要不然不知道是导出失败了还是单纯的导出慢。

如果受打印 PDF 的 API 限制，能否在思源内部模拟手动导出单篇笔记的脚本，最后再合并到一起呢？
体验上类似手机上的长截图的感觉，即用户可以看到每篇笔记的操作流程，但阻塞除暂停和退出外的一切用户操作。

作者：didididididi
链接：https://ld246.com/article/1716049123999/comment/1716077958561#comments
来源：链滴
协议：CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/

### Version environment

```markdown
- Version: v3.0.11
- Operating System: Win10x64
```

### Log file

无

**Comment by 88250** [comment]
已在链滴原贴中回复，这里暂时关闭，谢谢。

**Comment by TCOTC** [comment]
代码高亮问题关联：#12378
