### ISSUE TITLE
动态块查询 默认显示边框

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1145]
### 描述问题 Describe the problem
现在默认是隐藏的，一是丑，二是隐藏了许多有用的信息。
建议默认开启，或者增加个开关。
这是之前的效果
![image](https://user-images.githubusercontent.com/37007969/104840119-5ff9a380-5900-11eb-92b4-b08b6b331282.png)

### 期待的结果 Expected result
![image](https://user-images.githubusercontent.com/37007969/104840074-245ed980-5900-11eb-88df-2a0ab85567cc.png)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
感谢建议，但是就是因为之前展示太累赘了才简化的哟……
