### ISSUE TITLE
Rendering exception in export preview mode when custom attribute value has line breaks

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11453]
3.0.15 dev1 预览模式在笔记前错误显示文档属性

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![Clip_2024-05-18_22-47-50](https://github.com/siyuan-note/siyuan/assets/60436214/96e4902a-2d3f-4fc8-a80e-b38dd5c68bdf)
预览模式在笔记前错误显示文档所有属性

如何复现：给文档添加一个自定义属性key为名，value为
```
- 1
- 2
```

### Expected result

正常预览

### Version environment

```markdown
- Version: 3.0.15 dev1 
- Operating System: Win 11
- Browser (if used):
```

### Log file

no need

**Comment by TCOTC** [comment]
最简复现：

```
-
- 
```

[复现.webm](https://github.com/siyuan-note/siyuan/assets/78434827/1f435219-3b04-4805-a03c-43fb6b21c9d5)

**Comment by 88250** [comment]
感谢反馈，测试了下，这个问题之前的版本也存在，稍后看看如何修复。
