### ISSUE TITLE
无法使用#创建标签

### ISSUE THREAD

**Issue by happy8abc** [siyuan-note/siyuan#11450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

无法使用#创建标签

### Expected result

无法使用#创建标签

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无法使用#创建标签

### More information

无法使用#创建标签

**Comment by happy8abc** [comment]
gethub我也不会用啊，英语也不认识几个哈，还有其他问题
1.不能使用#创建标签了
2.不能快捷键制卡了
3.不能鼠标拖动内容块移动了
v3.0.14好像问题有点多，这上面3个问题是我这个小白使用碰到的

**Comment by 88250** [comment]
1. 请参考 https://ld246.com/article/1715863425048
2. 和 3 建议检查是否是主题问题，我这里默认主题测试正常

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by happy8abc** [comment]
通过你的帮助，已经解决了，非常感谢

**Comment by 88250** [comment]
不用谢 🙏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月18日(周六) 上午10:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 无法使用#创建标签 (Issue #11450)




 
通过你的帮助，已经解决了，非常感谢
