### ISSUE TITLE
数据库换行文本编辑后会先变成一行再展开

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11452]
v3.0.15-dev1

数据库换行文本编辑（随便改一下文本）后会先变成一行再展开

理想情况应该是编辑之后直接变成最终的高度

[换行.webm](https://github.com/siyuan-note/siyuan/assets/78434827/d42b4b02-5c1b-413a-ba96-b419369f4855)

**Comment by TCOTC** [comment]
看起来好像是每次编辑之后都渲染了数据库两次

**Comment by 88250** [comment]
我这里未重现该问题：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/bca88cee-90a4-486a-a614-c74dfc3ca402)

**Comment by TCOTC** [comment]
@88250 用的是 v3.0.15-dev1 吗？

**Comment by 88250** [comment]
当前开发环境的最新代码，等后面打个 dev2 你再试试。

**Comment by TCOTC** [comment]
dev2 没问题了
