### ISSUE TITLE
数据库资源列支持直接粘贴链接

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11463]
### In what scenarios do you need this feature?

比如复制以下两种链接：

1. 带锚文本：`[VCB-Studio 公开教程](https://guides.vcb-s.com/)`
2. 不带锚文本：`https://guides.vcb-s.com/`

我希望在选中某个资源列单元格后能直接 `Ctrl+V` 将链接添加到资源列里。（是新增，不是覆盖）

效果分别为：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/594fccf1-dd55-4031-8dcd-55884e3c78d6)

### Describe the optimal solution

数据库资源列支持直接粘贴链接

**Comment by TCOTC** [comment]
> 2. 不带锚文本：`https://guides.vcb-s.com/`

这个就是 #11468 中标题为空的情况

**Comment by TCOTC** [comment]
@88250 这里出现了跟 #11385 一样的问题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e3a80f32-b260-474c-9c7d-cd412de175af)

**Comment by 88250** [comment]
@Vanessa219

**Comment by TCOTC** [comment]
@Vanessa219 没修好

`www.bing.com/search?q=%22你好%22` 和 `www.bing.com/search?q="你好"` 粘贴都变成了 `http://www.bing.com/search?q`

**Comment by Vanessa219** [comment]
@88250 BlockDOM2EscapeMarkerContent 解析有点问题。

`https://www.bing.com/search?q=%22你好%22`

`https://www.bing.com/search?q="你好"`

**Comment by 88250** [comment]
1
