### ISSUE TITLE
插件 API | Dock icon 允许使用 iconHTML

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#11464]
### In what scenarios do you need this feature?

目前 addDock API 中，`IPluginDockTab` 的 icon 似乎只能填写 symbol 名称；希望可以直接填写 iconHTML。

比如允许这样直接使用 emoji

![image](https://github.com/siyuan-note/siyuan/assets/27268127/4e04a7db-f8cc-4a60-9ec2-c8f1c0bb297c)

### Describe the optimal solution

增加 iconHTML。

**Comment by frostime** [comment]
> 这个主界面还是蛮重要的，用户一眼就可以看到，还是希望能够保持一致性。

那退一步不要求使用自定义 html，但是希望 icon 可以识别显示 emoji 字符如何？目前只能使用 symbol name。

而且这两者应该还是好区分的，emoji 可以被解析为数值，而symbol name 不行。

**Comment by Vanessa219** [comment]
不是解析的问题，是外光看上去会不协调。

**Comment by frostime** [comment]
> 不是解析的问题，是外光看上去会不协调。

我这看上去感觉还好。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/a422117b-f051-4248-bcf2-541673888fe5)

**Comment by Vanessa219** [comment]
每个操作系统上的 emoji 都还不太一致，大小也会有出入的。
