### ISSUE TITLE
希望增加一个隐私笔记的功能

### ISSUE THREAD

**Issue by C-a-r-r-y** [siyuan-note/siyuan#11462]
### In what scenarios do you need this feature?

笔记里一些不太方便的东西，即使藏好了，也会在双链启动或者其他功能被检索到，如果建立新的工作空间又太繁琐了

### Describe the optimal solution

为块加一个secret属性，记录隐私性，某个开关启动时就不可见或者标星

**Comment by 88250** [comment]
请参考用户指南：

![image](https://github.com/siyuan-note/siyuan/assets/873584/9c9481e9-bcf5-4a15-b518-cdd7f0f29561)
