### ISSUE TITLE
Browser clipping extension supports path selection

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11467]
剪藏扩展支持配置新建文档位置（支持路径模板）

### In what scenarios do you need this feature?

就像这个：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/0763e196-80e3-4f68-86cf-6a72435b3f90)

需求先挂着

**Comment by TCOTC** [comment]
相关需求：

- https://ld246.com/article/1727001388100

**Comment by 88250** [comment]
直接选择好还是配置路径好？

**Comment by TCOTC** [comment]
配置路径可以覆盖更多情况，比如像日记那样创建不存在的文档 `剪藏笔记本/{{now | date "2006/01"}}/`

**Comment by 88250** [comment]
这个应该用日记功能建立父文档，另外创建的场景比较少就不考虑了，主要考虑用户方便使用。

**Comment by TCOTC** [comment]
> 另外创建的场景比较少就不考虑了

我想的是每个月剪藏的自动放在一起，用户应该会需要的

**Comment by 88250** [comment]
路径选择是有较多需求，模板的目前只有你提过，所以优先考虑路径选择。

**Comment by TCOTC** [comment]
那直接选择的交互是怎么做？

平铺还是树结构？在拓展里选择还是在工作空间里选择？（我觉得在工作空间里配置可能更方便）

**Comment by 88250** [comment]
加个搜索框，搜索结果平铺，和移动块那个框差不多

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/665557c8-ad1a-4d3e-a717-9a5edc2eaf7f)

Notebook 这个下拉选择估计会去掉，已经没有必要了，直接用 Path 搜索+选择

**Comment by 88250** [comment]
需升级剪藏扩展 v1.4.0
