### ISSUE TITLE
数据库资源列链接类型标题为空时直接显示链接

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11468]
### In what scenarios do you need this feature?

有时候会觉得填标题很麻烦，所以希望标题为空时直接显示链接：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/78d1a1dc-dfc5-4eaa-be05-f47ec78dcbd3)

### Describe the optimal solution

数据库资源列链接标题为空时直接显示链接

**Comment by TCOTC** [comment]
@Vanessa219 对了，还希望显示的链接能省略掉前面的 `http(s)://`

**Comment by Vanessa219** [comment]
这是资源列，和 url 有一定的功能区别，就不进行省略了。

**Comment by TCOTC** [comment]
但这个是资源列里的 `链接` 类型，功能应该是一致的

**Comment by Vanessa219** [comment]
资源主要指的的文件，链接一般为网页。

**Comment by TCOTC** [comment]
我不太理解， 不填标题只填链接的 `资源列链接类型` 在功能上不是等价于 `链接列 URL` 吗？

**Comment by Vanessa219** [comment]
和标题没关系，是类型，一个是资源列，一个是链接列。
