### ISSUE TITLE
.sy.zip 导出同名文件时重命名有点怪

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11466]
v3.0.15-dev2

如果目录中已有 `文档.sy.zip` ，在导出时会重命名为 `文档.sy (1).zip` 。

这个 ` (1)` 的位置感觉应该放到 `.sy` 前面

**Comment by 88250** [comment]
感谢反馈，稍后调整。

**Comment by 88250** [comment]
尝试了下，这个地方改不了，是浏览器的默认行为。
