### ISSUE TITLE
Improve copying database block

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11460]
* 改进 `复制` 文案为 `复制镜像`/`Copy mirror`
* 改进 `复制为副本` 文案为 `复制为镜像副本`/`Duplicate mirror`
* 增加 `复制为完整副本`/`Duplicate completely` 菜单项
  
  副本数据库块中的数据库名称：`<数据库名称> (Duplicated xxxx-xx-xx xx:xx:xx)`（中间有个空格）

---

数据库块复制为副本时创建一个新数据库块

_Originally posted by @88250 in https://github.com/siyuan-note/siyuan/issues/9285#issuecomment-1784146180_

> 深克隆有点问题，Notion 中重复（Duplicate）数据库块时是把视图中的所有 page 都深克隆一次。我们没法这么做，因为块不只是文档块，还有其他块，其他块没有文档容器的话无法重复。
>
> 可能还是只能浅克隆 :joy: 再考虑看看，各位有什么建议欢迎讨论啊。

话说这个问题能有解决方案吗？我有深克隆数据库的需求

我试了一下把数据库的 json 复制一份，手动改文件名和里面的部分 id ，然后在文档里添加了这个数据库块。可以看到这不是镜像数据库，点击主键都会跳转到同一个文档：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/77cece85-5e4b-407f-934b-75e1cfb82938)

但我即使是重建索引之后，在这个文档的数据库属性里都只能看到原来的数据库：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1d63ab9c-6867-4023-9bc4-fcd811a90133)

**Comment by 88250** [comment]
完整的深克隆做不了，原因在之前的讨论中已经描述。

如果只是做数据库的克隆（不克隆块），那可以试试导出 .sy.zip 导入。

上面提到手动修改 id 的方式在块中不生效是因为块属性 avs 没有改，我刚刚发现导入 .sy.zip 也没有生效，这个问题稍后会解决。

**Comment by TCOTC** [comment]
> 我刚刚发现导入 .sy.zip 也没有生效，这个问题稍后会解决。

我这里导入没有问题

**Comment by TCOTC** [comment]
> 完整的深克隆做不了，原因在之前的讨论中已经描述。

我还是不太理解为什么做不了

> 手动修改 id 的方式在块中不生效是因为块属性 avs 没有改

意思是改了就行了吗？

**Comment by 88250** [comment]
> 我这里导入数据库感觉没有问题，绑定块的数据库属性是正常显示的。

同一个文档中的块正常，如果块在其他文档中就不正常了。

> 我还是不太理解为什么做不了

没有地方存放克隆块。

> 意思是改了就行了吗？

还是不能完整深克隆，只是修复上面说的 bug。

**Comment by TCOTC** [comment]
> > 我还是不太理解为什么做不了
> 
> 没有地方存放克隆块。
> 

我的想法是仍然绑定原来的块，不需要克隆块。

相当于把原来绑定的块批量添加进一个新的数据库（只不过这个数据库不是空的）

**Comment by 88250** [comment]
是的，现在只能做到这一步，所以不是完整的深克隆。

**Comment by TCOTC** [comment]
> 是的，现在只能做到这一步

那这个功能可以做吗？

**Comment by 88250** [comment]
这个应该没问题，我们先解决上面提到的导入后绑定已有块的属性不正确问题。

**Comment by TCOTC** [comment]
- 数据库块 `复制为副本` 时创建一个新数据库块，关联已绑定的块
- 数据库块 `复制` 后 `粘贴` 仍然是创建镜像数据库（保持不变）
- 仅改变数据库块 `复制为副本` 的行为，跟其他类型的块 `复制为副本` 的行为保持一致（创建新块，而不是**镜像**块）

**Comment by TCOTC** [comment]
> > 我这里导入数据库感觉没有问题，绑定块的数据库属性是正常显示的。
> 
> 同一个文档中的块正常，如果块在其他文档中就不正常了。
> 

确实是哦，不在子文档的话也需要跟随着被导出才行

**Comment by 5kyfkr** [comment]
> * 数据库块 `复制为副本` 时创建一个新数据库块，关联已绑定的块

副本的数据库标题应该要加上个(独立副本)的标识，不然会以为是镜像数据库

**Comment by TCOTC** [comment]
@5kyfkr 镜像数据库 本来就有单独的标识，不需要这个

**Comment by TCOTC** [comment]
@88250 数据库块 `复制为副本` 后，数据库名称增加一段 ` (Duplicated xxxx-xx-xx xx:xx:xx)`

**Comment by 88250** [comment]
好的

**Comment by 88250** [comment]
和 V 讨论了下，我们会多加一个块标菜单 `复制数据库块副本` 而不是修改 Ctrl+D（复制为副本），因为后者用户可能难以察觉其区别，并且改动以后这个行为和其他块会不一致，所以加一个块标菜单来突出这个功能比较好。

**Comment by 5kyfkr** [comment]
那数据库块就没有“修改 Ctrl+D（复制为副本）”这个了吧，相当于被 复制数据库块副本 这个取代

**Comment by 88250** [comment]
Ctrl+D 保持不变，依然是复制镜像块。

**Comment by 5kyfkr** [comment]
> Ctrl+D 保持不变，依然是复制镜像块。

两个选项都叫复制副本。。有点难理解
应该 Ctrl+D叫 复制镜像数据库副本，然后新加的叫 复制独立数据库副本，名字可能直观点，但是ctrl d估计为了保持其它块相同改不了名字，新加的可以突出一下是独立的新副本

**Comment by 88250** [comment]
对于数据库来说，默认的复制就是镜像，这个不用单独强调了吧，Ctrl+D 和 复制+粘贴 一样的。单独强调非镜像复制就可以了。

**Comment by 5kyfkr** [comment]
> 对于数据库来说，默认的复制就是镜像，这个不用单独强调了吧，Ctrl+D 和 复制+粘贴 一样的。单独强调非镜像复制就可以了。

可以，就单独强调非镜像的够了

**Comment by TCOTC** [comment]
@88250 

今天群里有一位刚刚发现他一直以来 `Ctrl+D` 创建的都是镜像数据库，导致编辑的时候把以前的条目都删除了。

新用户很难发现这个数据库「副本」是跟其他数据库同步的，默认的不应该是镜像。

比如在 Notion 里给 Database 创建副本就是创建一个不与原来的 Database 同步的新的 Database

我建议数据库 `复制为副本` 跟其他块保持一致，即创建一个编辑不会影响原块的新块，而不是创建一个与其他块同步的镜像块

而且不需要专门强调「非镜像」，因为带有 `(Duplicated xxxx-xx-xx xx:xx:xx)` 的就是「非镜像」，不带有的就是「镜像」

**Comment by 88250** [comment]
这个用法不考虑改变了，默认复制就是镜像块，非镜像块单独加入口。

**Comment by 5kyfkr** [comment]
> 而且不需要专门强调「非镜像」，因为带有 `(Duplicated xxxx-xx-xx xx:xx:xx)` 的就是「非镜像」，不带有的就是「镜像」

这个我觉得要强调，一般人根本不会关注到数据库右上角还有个镜像的角标，镜像的概念可能都不清楚，因为只有思源有这样的设计

**Comment by TCOTC** [comment]
> 默认复制就是镜像块，非镜像块单独加入口

@88250 那我建议把数据库块标里原来的「复制为副本」文案改为「创建镜像副本」，然后新增一个「创建独立副本」

**Comment by TCOTC** [comment]
「镜像」也是应该强调的，

对初次使用思源数据库的用户来说，只强调「非镜像」是无效的，因为他们对「镜像」没有概念。

更好的方式是都强调：「创建镜像副本」、「创建独立副本」

**Comment by TCOTC** [comment]
有「镜像」和「独立」的对比才行

**Comment by 88250** [comment]
我们再考虑下。

**Comment by 88250** [comment]
* 改进 `复制为副本` 文案为 `复制为镜像副本`/`Duplicate mirror`
* 增加 `复制为完整副本`/`Duplicate completely` 菜单项
  
  副本数据库块中的数据库名称：`<数据库名称> (Duplicated xxxx-xx-xx xx:xx:xx)`（中间有个空格）

**Comment by TCOTC** [comment]
`复制为完整副本` 最好是跟 `复制为镜像副本` 放在同一个二级菜单下挨着

**Comment by 88250** [comment]
是的，放在 复制 菜单下面

**Comment by TCOTC** [comment]
要不把 `复制纯文本` 放到 `复制` 的上面？让 `复制` 和 `复制为副本` 挨着

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6a833861-7bc6-4360-ab95-89daa7de2efa)

**Comment by 88250** [comment]
还有个复制文本*呢？

**Comment by TCOTC** [comment]
哦被我隐藏起来了，我就是觉得把复制放下面一点可能好一点

**Comment by 88250** [comment]
等做完功能以后看看，我感觉怕是没有必要，这两个已经离得很近了。

**Comment by TCOTC** [comment]
现在这个 `复制` 不上不下的感觉很奇怪

**Comment by 88250** [comment]
和其他块一样嘛

**Comment by TCOTC** [comment]
反正还是这个菜单感觉奇怪的问题，也不知道怎么改善

![image](https://github.com/siyuan-note/siyuan/assets/78434827/40702177-6a67-430c-91c6-90667f44b7aa)

**Comment by 88250** [comment]
上次讨论说是把图标都去掉？

**Comment by 5kyfkr** [comment]
龙生九子，各有不同，应该把最常用的几个加上图标放最前面，ctrl +c应该加个图标放前面点

**Comment by 88250** [comment]
这个菜单只要少一个图标就会不和谐，所以考虑全部去掉。

**Comment by TCOTC** [comment]
@88250 删图标 和 删「复制」

![Screenshot_2024-05-24-00-15-41-09_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/siyuan-note/siyuan/assets/78434827/aeb27d52-dfd8-4111-bbf2-93ac1332b7b1)

**Comment by 5kyfkr** [comment]
这是什么群，我也想加个
