### ISSUE TITLE
数据库资源列链接标题悬浮提示增加标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11465]
### In what scenarios do you need this feature?

两种情况：

1. 字数多所以被截断
2. 列宽不够所以被截断

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5ef6617a-0b0d-4bfd-b0a7-7488eafbd0f0)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3bc8a083-a20b-46ea-850e-f91837e20996)

### Describe the optimal solution

数据库资源列链接标题被截断时，需要在悬浮提示中显示标题（一行显示标题，一行显示链接）

**Comment by Vanessa219** [comment]
一下显示一行，一下显示两行会不会不太一致？

**Comment by TCOTC** [comment]
我觉得至少比不显示要好。

而且因为标题的长度一般没多长，而链接的长度可能非常长，所以在悬浮提示里，链接最好还是放在标题之下显示。

**Comment by Vanessa219** [comment]
标题在下方吧，和正文链接保持一致。

**Comment by TCOTC** [comment]
这个跟正文链接感觉还是不太一样，正文链接是有锚文本的，标题只是补充作用

**Comment by Vanessa219** [comment]
这样链接就会不稳定，一会在上一会在下。稳定出现的链接是需要固定在前面的，不一定出现的示为补充内容，不能占据主要位置。

**Comment by TCOTC** [comment]
目前有3种情况（假设文本被截断）：

1. 只填写了链接 → 悬浮提示只显示链接 ≈ 链接在前
2. 只填写了标题 → 悬浮提示只显示标题 ≈ 标题在前
3. 同时填写了链接和标题 → 悬浮提示同时显示链接和标题 → 谁在前？

阅读标题肯定是优先于阅读链接的，所以应该让标题在前

**Comment by Vanessa219** [comment]
标题已经有可见了，只是看不完整。如果只是截断了一个字的话，是会有重复的。

**Comment by TCOTC** [comment]
那就放下面吧

**Comment by Vanessa219** [comment]
上次好像讨论了是移动到空白和链接上显示不同的。现在为移动到链接上统一添加标题。

**Comment by TCOTC** [comment]
@Vanessa219 如果链接过长，悬浮提示里的标题会不会被挤没？
