### ISSUE TITLE
Please enter the title of the feature request

### ISSUE THREAD

**Issue by songshua295** [siyuan-note/siyuan#11471]
### In what scenarios do you need this feature?

1. 侧边栏中的书签、手机箱等功能能否关闭或者隐藏
2. 移动端搜索按钮的交互逻辑能否改变，或者按钮改一下位置，目前使用起来搜索一个东西从打开到搜索至少需要五步

### Describe the optimal solution

1. 侧边功能在设置中添加关闭或者隐藏按钮
2. 移动端的搜索按钮建议放在顶部的设置按钮旁边，或者放在侧栏的文档树顶部或者底部，点击搜索按钮后，光标自动放到输入框（移动端目前是需要自己点一下输入框的）

### Describe the candidate solution

暂无

### Other information

交互可以参考一下别的笔记的通用逻辑。

对于笔记来说，我觉得交互是一个笔记人对一个新的笔记软件的探索关键，如果交互做的不好，笔记使用起来就会很难受。
所以相比笔记的功能性，交互才是普通用户对于笔记的侧重点，功能是进阶笔记者对于笔记的看重点。

对于交互方面，我没有太多的建议，不过搜索的交互，我觉得可以参考notion、telegram。

**Comment by TCOTC** [comment]
> 侧边栏中的书签、手机箱等功能能否关闭或者隐藏

目前可以用代码片段或集市里的隐藏按钮插件

**Comment by 88250** [comment]
1. 集市中有个插件似乎可以
2. 这个要等后期考虑移动端重构了，焦点不放在输入框中是因为会弹出软键盘折叠

感谢反馈。
