### ISSUE TITLE
插件api请求：增加创建指定日期的日记到指定笔记本的api

### ISSUE THREAD

**Issue by suka233** [siyuan-note/siyuan#11472]
### In what scenarios do you need this feature?

目前思源日记可以自定义`存放路径`，并且有时会有新的日记相关特性加入（比如：[#9807](https://github.com/siyuan-note/siyuan/issues/9807)），插件作者自己来实现“创建指定日期的日记到指定笔记本”的功能会有很多阻力，并且可能也会有遗漏新属性适配的风险，所以提供一个官方api是必要的。

可预见的好处还有：采用此api的插件，即使后面该插件不再维护，功能也不会因为思源日记新特性的加入而缺失。

### Describe the optimal solution

入参：
1.指定日期YYYY-MM-DD
2.指定的notebook
3.模板路径（日记模板我没用过，这个参数我个人是不太需要的，但是为了可拓展性，能加就加吧）

接口行为：如果指定的日期已经存在日记，就返回该条日记的相关信息，否则新建日记。

**Comment by 88250** [comment]
创建日记要走统一的路径模板（如果需要指定笔记本可以考虑使用 `createDailyNote` 接口），所以不考虑单独提供路径参数了，谢谢。
