### ISSUE TITLE
Import markdown file，math formula can not display correctly.

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#11476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

现在“导入 markdown”、“简悦剪藏”，里面的公式都不能正常显示。

之前是没问题的，现在不行了。当前 siyuan 版本是 3.0.14，测试已排除插件和代码片段。

siyuan 回退到 3.0.7，用“简悦剪藏”、“导入 markdown”，公式都能正常显示。我猜这是因为简悦插件的原理实际上是先转为 markdown 再导入思源？但最新版本的 siyuan 导入 markdown 公式会不正常。

测试网页（以前是正常的）： [https://zhuanlan.zhihu.com/p/679689692](https://zhuanlan.zhihu.com/p/679689692)

3.0.7导入markdown：
![图片](https://github.com/siyuan-note/siyuan/assets/33930736/8ef877bf-bda4-4fa2-8cb3-ee7ae1272b3e)

3.0.14导入markdown：
![图片](https://github.com/siyuan-note/siyuan/assets/33930736/30c4c245-f610-4f41-b572-e05737b79a08)

### Expected result

none

### Version environment

```markdown
- Version: 3.0.14
- Operating System: win10 or android 14
- Browser (if used):
```

### Log file

none

### More information

关联： https://ld246.com/article/1716121840461/comment/1716188048829?r=openAI#comments

**Comment by TCOTC** [comment]
打开这个开关再导入 Markdown 试试看行不行：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ae2fc3d2-d61f-41e6-b92b-2b54ca1dcb9b)

**Comment by luo-chuan** [comment]
> 打开这个开关再导入 Markdown 试试看行不行：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/331977369-ae2fc3d2-d61f-41e6-b92b-2b54ca1dcb9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODk4MDcsIm5iZiI6MTcxNjE4OTUwNywicGF0aCI6Ii83ODQzNDgyNy8zMzE5NzczNjktYWUyZmMzZDItZDYxZi00MWU2LWI5MmItMmI1NGNhMWRjYjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNTgxMjI0OTU3M2E2NWU2NTM2MjBlNjdhMzIyMjMxMzk3OWMwNzhkNGVjMjdlY2IyMjNhYjgyODYyZmI3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sd8gcqUkzUYpr0-F2H2AHAephhs5DL87FXOfsE7jzyI)

谢谢，打开这个开关后，正常了。话说为什么要默认关闭这个开关呢？给用户造成困惑。建议这个开关默认打开。

**Comment by TCOTC** [comment]
> 话说为什么要默认关闭这个开关呢？给用户造成困惑。建议这个开关默认打开。

因为小白一般不用公式，但输入 `$` 的时候会变成行级公式，会造成困扰
