### ISSUE TITLE
Bucket 为空时不需要提示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11474]
Bucket 为空时不需要提示

[为空.webm](https://github.com/siyuan-note/siyuan/assets/78434827/66cff48a-8b0c-4086-8d75-df748950f2bb)

**Comment by 88250** [comment]
因为这里每点一下都进行了保存，所以即使为空也会判断并提示用户。

**Comment by TCOTC** [comment]
但这个提示不对啊，是为空而不是 `包含空格和特殊符号` ，所以为空的时候不应该有这个提示

**Comment by 88250** [comment]
稍后调整文案 `云端同步目录名（Bucket）不能为空、包含空格或特殊符号，最大长度 63 字符`
