### ISSUE TITLE
Improve block ref text copying

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#11473]
`\` Process optimization

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如果文档标题名为`\`,`\\\`,`\\\\\`，粘贴为引用块会产生问题

### Expected result

fix

### Version environment

```markdown
- Version: 3.0.14
- Operating System: win10
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
我这里测试似乎正常：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/cfee5dfe-1b9d-4d5c-82f8-06bb1f818c03)

**Comment by TinkMingKing** [comment]
@88250 标题只有反斜杠的时候

**Comment by 88250** [comment]
收到，稍后看下如何解决。
