### ISSUE TITLE
mp3文件插入渲染不稳定

### ISSUE THREAD

**Issue by hopebird** [siyuan-note/siyuan#1147]
### 描述问题 Describe the problem

在一个笔记里连续插入几个 mp3 文件的时候，有部分文件会不能播放（播放控件变灰色）。应该是其他代码影响了解析，所以出错了。
如果处理复杂，最好有个语法或者选项，强制可渲染的文件不渲染，而只留下链接，交给外部程序处理。
### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
感谢反馈，这个应该是因为 `<audio>` 标签解析渲染的问题导致，我们会在 https://github.com/siyuan-note/siyuan/issues/892 中进行改进。
