### ISSUE TITLE
Global Search That Will Search Also Inside PDF Files

### ISSUE THREAD

**Issue by CyRamos** [siyuan-note/siyuan#11470]
### In what scenarios do you need this feature?

Hey  
I've noticed that when I search for stings in my workspace it doesn't search inside PDFs attached (not embed) them as well. 

### Describe the optimal solution

I'd like an option to find data globally even if it's inside PDFs. I didn't find a plugin that could solve this problem. just to make clear - I don't mean the custom search inside the PDF, I mean a global search that could find me data in docs and also in PDF. 

### Describe the candidate solution

A global search (CTRL+F / CTRL+P) that could find me data inside PDF.

## Didn't find it globally
![image](https://github.com/siyuan-note/siyuan/assets/40651473/2fd8f44e-fc6c-4924-9ba0-7ad86a849543)

## Found it in a custom search inside the PDF itself
![image](https://github.com/siyuan-note/siyuan/assets/40651473/58ec6497-39bd-40c5-a1c1-c51611e8ce61)

**Comment by TCOTC** [comment]
Using this feature, you can search which PDF file a word appears in, but you cannot locate the exact position of the word in the PDF:
使用下面的这个功能，你可以搜索到一个词汇出现在哪个 PDF 文件中，但不能定位到这个词汇在 PDF 中的具体位置：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1341da33-eb09-4697-8332-778824bd9ed3)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bd1b8bfa-8e51-4dde-8327-54d03c69db6c)

**Comment by 88250** [comment]
As @TCOTC mentioned above, this is a PRO Feature that requires payment to use, but it can only locate files and cannot locate specific page numbers. After opening the PDF, you need to use the PDF's in-page search again.
