### ISSUE TITLE
Improve database text, email, url and phone field content escaping

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11489]
数据库文本字段 `"` 符号显示问题

https://ld246.com/article/1716275202158

[符号.webm](https://github.com/siyuan-note/siyuan/assets/78434827/fc1ec216-51ed-4387-8362-1b9c92b6ccf5)

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/11255
