### ISSUE TITLE
数据库单选多选支持合并选项

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11484]
### In what scenarios do you need this feature?

假设有 A B 两个选项，支持将 A 改为 B 

![image](https://github.com/siyuan-note/siyuan/assets/78434827/91eb6721-6580-419e-92b1-265709e560a2)

### Describe the optimal solution

在合并后：

- [ ] 原本单元格里的 A 的颜色也变为 B 的颜色
- [ ] `Ctrl+Z` 可以撤回合并操作，颜色也恢复

**Comment by 88250** [comment]
a 改 b 以后所有用了 a 的值都会更新为 b，这个时候撤销就会把所有 b 都还原为 a（包括以前用了 b 的）

**Comment by TCOTC** [comment]
那看来只能回滚历史或快照了

**Comment by 88250** [comment]
多选还有点问题

**Comment by TCOTC** [comment]
如果用户需要合并两个选项，我觉得应该直接删掉这个修改前的选项：

[video.webm](https://github.com/user-attachments/assets/d953b8a3-5a6b-407f-952a-e1b284dcd425)
