### ISSUE TITLE
Export the binding block docs when exporting the doc where the database is located

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11486]
导出数据库所在文档时一并导出绑定块所在文档

> > > 如果只是做数据库的克隆（不克隆块），那可以试试导出 .sy.zip 导入。
> > > 
> > > 上面提到手动修改 id 的方式在块中不生效是因为块属性 avs 没有改，我刚刚发现导入 .sy.zip 也没有生效，这个问题稍后会解决。
> > 
> > 我这里导入数据库感觉没有问题，绑定块的数据库属性是正常显示的。
> 
> 同一个文档中的块正常，如果块在其他文档中就不正常了。

_Originally posted by @88250 in https://github.com/siyuan-note/siyuan/issues/11460#issuecomment-2119259328_

在 v3.0.15 ，导出数据库所在文档是不会把绑定块所在的文档一并导出的（不是子文档的情况下），

1. 把 .sy.zip 导入原来的工作空间之后会关联已有的块（这个是有问题的，导入的 .sy.zip 应该是独立的，不应该与已有的数据关联）
2. 把 .sy.zip 导入其他工作空间之后这些条目就会丢失

**Comment by 88250** [comment]
是的，目前不会导出绑定块文档，麻烦单独建个 issue。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年5月21日(周二) 中午11:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [siyuan-note/siyuan] 导出数据库所在文档时一并导出绑定块所在文档 (Issue #11486)




    
如果只是做数据库的克隆（不克隆块），那可以试试导出 .sy.zip 导入。
 
上面提到手动修改 id 的方式在块中不生效是因为块属性 avs 没有改，我刚刚发现导入 .sy.zip 也没有生效，这个问题稍后会解决。
  
我这里导入数据库感觉没有问题，绑定块的数据库属性是正常显示的。
  
同一个文档中的块正常，如果块在其他文档中就不正常了。
  
Originally posted by @88250 in #11460 (comment)
 
在 v3.0.15 ，导出数据库所在文档是不会把绑定块所在的文档一并导出的（不是子文档的情况下），把 .sy.zip 导入其他工作空间之后这些条目就会丢失

**Comment by TCOTC** [comment]
所以这个已经是个单独的 issue 了

**Comment by 88250** [comment]
哦哦，不好意思，手机上看岔了……

**Comment by TCOTC** [comment]
@88250 `导出数据库所在文档时一并导出绑定块所在文档` 之后，如果在 `绑定块所在文档` 里也有数据库或者引用了其他文档，会怎么样？

**Comment by 88250** [comment]
递归导出。

**Comment by TCOTC** [comment]
如果不同的数据库绑定了同一个块，会被重复导出吗？还是只导出一个？

**Comment by 88250** [comment]
不会重复的，只导出一个文档。

**Comment by mozhux** [comment]
这个我建议是效仿其他的，在导出的时候弹窗可以选要不要导出里面的子文档。

**Comment by 88250** [comment]
暂时不加了吧，先实现尽量完整的导出，后面看需求再考虑是否加。
