### ISSUE TITLE
增加一些同步的信息让用户更清楚同步的情况

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#11482]
### In what scenarios do you need this feature?

我前段时间出现了一个同步bug，就是我同步之后导致我电脑上的一些文档的名字消失了变成了untitled，这些文档的特征如下：1.都是空白文档，即没有任何内容 2.都有子文档。当时很忙，没空弄明白什么原因，也不是很在乎同步，只是用来备份，然后就回滚了直接取消云同步，现在想起来用云同步发现还是有这个问题。

但是这个问题不是我这个issue的重点，因为它可能有各种各样的情况难以排查，我也决定待会把云端目录都清空，这样重新全量上传一下应该没问题。我想说的是这个问题我不是一下子发现的，因为这个问题没有任何报错，我是在几天后的全局搜索的时候发现有些被搜到的内容路径下有untitled，让我有点奇怪，这才发现这个问题。

这个bug的重点在于，我不知道啥时候云端同步有问题了。这个很要命。现在我都不知道我内容是不是缺失了，当然我看了下缺失的概率很小，目前没有发现任何资料的缺失，只是文档名消失。

以下是我个人的提议，也是本issue的重点：

我希望思源能够在每隔一段时间导出当前思源的所有文档目录，并且记录每个文档的大小或者字符数，文档最后一次的修改时间，我们用户最好能比较清楚的知道同步的结果。因为第一次出现文档名消失的清况后我用everything把思源的数据目录按修改时间进行排序，然后发现在同一个时刻有一大批文档被修改，这显然是不正常的。

我希望思源这个导出功能就是能够检测出有没有一大批文档突然在某一个时刻集体被修改，如果有再去查看那一时刻有没有使用全局替换功能，如果没有那显然是有问题的。这时候应该报错给用户，让用户能够最早发现问题并且回滚。

也可以记上对思源文档笔记数量的检测，这个可以不和导出文档在一块运行，这个功能可以更频繁一点毕竟不是很占用性能。如果检测到大规模的文档删除也最好提醒一下，就比如小米云相册在我每次删除大量云照片的时候都会告诉我最近您的账户有大量照片被删除，是否本人操作之类的，哪怕大多数时候都是我本人操作所以我根本不管这个消息，但是这个消息会让我比较安心，不会担心会不会有一天突然被bug删除了大量文档。或者可以记录下每次思源被打开或者关闭的时间，然后在每次打开的时候都显示上次打开思源的时候有多少文档被修改，正常来说这个数字不会很大。

### Describe the optimal solution

现在思源插件里面有一个名为“导出文档书结构”的插件，我刚才试了下，它会导出一个yaml文件，并且各种信息都很齐全。我第一次导出后，对笔记修改了点内容后再次导出，然后用notepad--对比这两个文件发现效果还不错，如下图所示。目前我个人想到的解决方法是以后每周或者每几周导出一个yaml，主要对比看总文档书以及总字符数，这两个一般是只增不减。
![Clip_2024-05-20_21-01-00](https://github.com/siyuan-note/siyuan/assets/98648589/88a82cc6-78ee-4af1-9f4d-a46df19304b6)
我其实觉得这个插件再优化一点，例如对导出的yaml文件和历史导出的yaml文件进行对比，然后给用户显示当前时间相较于上次导出yaml的时间增加或者减少了哪几个文档，字符数有什么变化，总共有几个文档被修改过。如果这个功能还能定时执行那就更好了。插件作者是@frostime  ,感谢大佬的插件，也希望大佬和d大能够看看这个需要是否有必要，如果可以加是思源来加还是通过插件实现。谢谢谢谢🙏

**Comment by 88250** [comment]
* 如果能重现问题麻烦提供多个设备的日志以便诊断问题
* 建议通过数据快照对比差异
* 对于大量变更的情况后续会考虑是否提醒用户，因为有些场景是可能大量变更的，比如整理笔记时，是否阻断和提示还需要考虑，建议定期备份数据快照或者原始数据以确保数据安全

感谢反馈，我关闭 issue 了，后续如果还存在 Untitled 问题请随时更贴反馈。
