### ISSUE TITLE
从资源列复制的图片无法再粘贴到资源列

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11487]
从资源列复制的图片无法再粘贴到资源列：

[图片.webm](https://github.com/siyuan-note/siyuan/assets/78434827/4d7c355d-7d82-46df-89a7-cdb117547453)

补充：

1. 可以粘贴到段落块中，但无法粘贴到资源列
2. 复制为 PNG 可以粘贴，但粘贴之后会生成文件名不同的重复的文件

**Comment by Vanessa219** [comment]
png 主要提供粘贴到 QQ 等通信工具上。由于系统安全限制，png 和原图不一致了，所以会重复。
