### ISSUE TITLE
Support triggering tag selection via `#`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11494]
Revert https://github.com/siyuan-note/siyuan/issues/11346

**Comment by andyer1511** [comment]
还是把`Markdown 行级标签语法`变成默认开启更好。
现在开启可以用#查询标签，不开启#无法查询，功能划分更清晰，想用标签和不想用都有的选。
但现在改成不开启也能查询标签，那开启不开启标语法就没区别了，不想用#查询标签的人就没得选了。

**Comment by TCOTC** [comment]
> 不想用 `#` 查询标签的人就没得选了

我建议给这个弹窗加个类名，这样就能通过 CSS 代码片段隐藏了

**Comment by TCOTC** [comment]
> 还是把`Markdown 行级标签语法`变成默认开启更好。
> 现在开启可以用#查询标签，不开启#无法查询，功能划分更清晰，想用标签和不想用都有的选。

实际上 `使用标签` 和 `使用 Markdown 行级标签语法` 是两个需求

**Comment by Achuan-2** [comment]
建议还是搞个选项，是否使用#触发标签输入，
我是既不想用Markdown行级标签语法，也不想输入#就弹出标签搜索面板干扰我输入的

**Comment by andyer1511** [comment]
![1716289546967](https://github.com/siyuan-note/siyuan/assets/18610532/4615b24c-9aa3-4121-b77b-af9e2fa2db53)
> 我建议给这个弹窗加个类名，这样就能通过 CSS 代码片段隐藏了
本来不想用标签在设置点一下按钮就好了，现在还得去找css代码。大部分人用软件只需要开关，不需要代码，这也是很多人说思源更像给程序员用的软件的原因。

> 实际上 查询标签 和 使用 Markdown 行级标签语法 是两个需求
`需要#查询，不需要行级标签语法`这是需要标签的细分需求，应该单独有一个开关设置。

**Comment by TCOTC** [comment]
我建议不要用 `用标签` 和 `不用标签` 来做分类，直接像我的表格那样用功能区分
