### ISSUE TITLE
部分外链图片无法正常显示

### ISSUE THREAD

**Issue by MasterJobSteam** [siyuan-note/siyuan#1149]
### 出现问题及截图

* 思源无法正常显示外链图片
![SiYuan](https://user-images.githubusercontent.com/60995722/104844496-896bfc80-590b-11eb-9a12-c59312b889ec.png)

* 浏览器能够正常显示
![Chrome](https://user-images.githubusercontent.com/60995722/104844610-2e86d500-590c-11eb-8031-39e7b4c641b2.png)

### 版本环境 Version environment

* 版本 Version：Kernel v0.6.2

**Comment by 88250** [comment]
你好，是不是图床有防盗链？浏览器上的可能是缓存，试试 F12 禁用缓存后刷新看下还能否访问，或者将此链接贴出来我这里试试访问，也方便调试，谢谢。

**Comment by MasterJobSteam** [comment]
https://isiyuan.obs.cn-north-4.myhuaweicloud.com/Clouds_Thicken.png

**Comment by 88250** [comment]
你好，这个是因为服务端报错，如果是自建图床，请看下图床服务端的日志，谢谢。

![image](https://user-images.githubusercontent.com/873584/104862285-0203a500-596e-11eb-8fa2-353ef204ea29.png)

**Comment by MasterJobSteam** [comment]
不知为何，我用浏览器访问能得到图床服务器日志，但用思源无法得到。
* 浏览器访问及图床服务器日志
![chrome](https://user-images.githubusercontent.com/60995722/104929624-19c74180-59df-11eb-92c0-137639181bce.png)
![serverlog](https://user-images.githubusercontent.com/60995722/104929775-49764980-59df-11eb-92e9-fb7c4a77621d.png)
* 思源访问，服务器无法找到对应 RequestId
![vditor](https://user-images.githubusercontent.com/60995722/104929970-8b9f8b00-59df-11eb-858d-27934c24231a.png)

**Comment by 88250** [comment]
我猜测可能是思源用的 User-Agent 标头服务端程序解析有缺陷，这个得找找服务端程序的源码或者发工单问下。
