### ISSUE TITLE
Opening the user guide is no longer supported on iOS

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11492]
iOS 端不再支持打开用户指南，请参考桌面端用户指南。

用户指南中包含了付费相关内容，无法通过商店上架审核。

**Comment by TCOTC** [comment]
我感觉这个 issue 更像是 `Abolishment`

**Comment by 88250** [comment]
嗯

**Comment by TCOTC** [comment]
能不能做到单独把 iPhone 上的付费相关内容删除？

**Comment by 88250** [comment]
不只是提到付费部分的内容，还有一些链接也审核不过。

**Comment by TCOTC** [comment]
干脆把审核不通过的内容都改了

**Comment by 88250** [comment]
我们还是得把精力放在其他任务上，很少人（可能没有人）会单独使用 iOS 端思源的，桌面端能够正常打开用户指南就够了。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/17851 中试试能不能恢复。
