### ISSUE TITLE
鼠标遮挡部分文字

### ISSUE THREAD

**Issue by Korov** [siyuan-note/siyuan#11496]
### In what scenarios do you need this feature?

![c69079a3b25c7ae20ead7d06610bbb7](https://github.com/siyuan-note/siyuan/assets/45894441/6e80527d-3b99-4a28-96d1-dc1c5f76ed12)

### Describe the optimal solution

不要遮挡文字

**Comment by TCOTC** [comment]
你鼠标太大了。

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bd12f428-c4e2-4035-aca6-9a078d895ce0)

文字遮挡鼠标更麻烦

**Comment by TCOTC** [comment]
我突然想起来元素只能被鼠标遮盖，你这个需求只能靠调大字号实现了：

```css
.tooltip {
    font-size: 15px;
}
```

**Comment by 88250** [comment]
正如楼上所言，我们关闭 issue 了。
