### ISSUE TITLE
以预览模式打开文档

### ISSUE THREAD

**Issue by cuijianzhe** [siyuan-note/siyuan#115]
场景：
笔记用于记录各个系统的账号，每次打开复制密码，希望处于阅读状态而不是编辑状态
类似于：
![image](https://user-images.githubusercontent.com/48144475/94387521-fb61df80-017c-11eb-87a3-b817b3a6c626.png)

**Comment by 88250** [comment]
用快捷键切换预览先顶顶。

**Comment by lss6378** [comment]
**期望的pdf预览效果：** 

![图片](https://user-images.githubusercontent.com/15924513/97454287-8b0fcf00-1971-11eb-83b9-1777eaea73d0.png)

参考：https://github.com/mozilla/pdf.js
