### ISSUE TITLE
List beginning code block and heading parsing problem

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1150]
### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/46141646/104845880-ac4ddf00-5912-11eb-97b5-2d606a68f0c9.png)
如图，```java没能触发代码块的编辑

### 期待的结果 Expected result

列表项 ``` 可以触发代码块的编辑

### 版本环境 Version environment

* 版本 Version：0.62

**Comment by wo4wangle** [comment]
这个问题不是无法触发，而是手动编辑也不能做到：即列表项的开头无法编辑代码块
最近我阅读源码，这样的需求很多：列表项以一段代码起头，然后其子项解释这份代码
我基本都是shift enter之后再贴代码
typora中 是可以 正常在 列表项开头就编辑代码块的

希望可以适当提升一下优先级
谢谢！

**Comment by 88250** [comment]
你好，这个问题应该在 v1.0.0 中修复了。
