### ISSUE TITLE
顶部导航栏标题是“未命名”

### ISSUE THREAD

**Issue by lixh00** [siyuan-note/siyuan#11504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

顶部title有些是未命名，实际上是有名字的。详情如图所示。使用默认主题也是如此。

![image](https://github.com/siyuan-note/siyuan/assets/72033265/ea0d23b0-d901-4dca-92ad-48bd3b5216a4)

### Expected result

正常显示title

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

nothing

**Comment by 88250** [comment]
建议在默认主题下测试，关闭插件或者代码片段。

**Comment by TCOTC** [comment]
试试看关掉这个文档再打开

**Comment by lixh00** [comment]
> 试试看关掉这个文档再打开

关掉再打开是正常的

**Comment by TCOTC** [comment]
确实偶尔会出现页签名跟文档名不同步的情况，关掉再打开会恢复正常

**Comment by lixh00** [comment]
> 确实偶尔会出现页签名跟文档名不同步的情况，关掉页签再打开会恢复正常

炫酷~

**Comment by 88250** [comment]
如果能够提供重现该问题的步骤请随时跟帖反馈，谢谢。

**Comment by lixh00** [comment]
> 如果能够提供重现该问题的步骤请随时跟帖反馈，谢谢。

啥都没干，直接打开就是这样，是偶发的，不能必现
