### ISSUE TITLE
数据库单选多选字段支持设置默认值

### ISSUE THREAD

**Issue by noenif** [siyuan-note/siyuan#11509]
主键 能否 自增 或者给定一个uuid ,并且隐藏主键

### In what scenarios do you need this feature?

主键 能否 自增 或者给定一个uuid ,并且添加一个隐藏主键.因为我想看的是总结的内容而不是主键
对于单选能否添加一个默认值.或者使用上一个值.或者可以是空的. 
对于多选也是遵循上述规律.
因为你是枚举,你一直让用户选这太痛苦了.

### Describe the optimal solution

感谢大佬添加的数据库,希望siyuan越做越好

**Comment by TCOTC** [comment]
1. 关联：[数据库主键支持隐藏](https://github.com/siyuan-note/siyuan/issues/10882)、[[css] 隐藏特定数据库块的主键列 - 链滴](https://ld246.com/article/1728354035172)
2. 单选/多选支持默认值：打开筛选的情况下好像会使用上一个值/筛选的值？但比较局限 → 关联 https://github.com/siyuan-note/siyuan/issues/11506

**Comment by TCOTC** [comment]
支持这个：「单选/多选支持默认值」

**Comment by 5kyfkr** [comment]
> 我支持这个：「单选/多选支持默认值」

我看了notion能AI自动识别主键内容选择单选甚至创建单选项，有点6，当然思源能给个设置基本就够了
![image](https://github.com/siyuan-note/siyuan/assets/63196026/3e3ba694-4545-43be-8c2e-59d2f8712622)

**Comment by noenif** [comment]
> 1. 关联：[数据库主键支持隐藏](https://github.com/siyuan-note/siyuan/issues/10882)
> 2. 单选/多选支持默认值：打开筛选的情况下好像会使用上一个值/筛选的值？但比较局限
会有三个基础配置选项, 使用上一个,默认配置一个,以及现在这种一直需要用户手动选择.因为没办法  siyuan的数据库不能用类似datagrip这种工具管理模式管理吧.他更类似于一个低代码工具.那至少应该为用户提供一些方便.

**Comment by noenif** [comment]
> > 我支持这个：「单选/多选支持默认值」
> 
> 我看了notion能AI自动识别主键内容选择单选甚至创建单选项，有点6，当然思源能给个设置基本就够了 ![image](https://private-user-images.githubusercontent.com/63196026/333004677-3e3ba694-4545-43be-8c2e-59d2f8712622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MjkzNDAsIm5iZiI6MTcxNjQyOTA0MCwicGF0aCI6Ii82MzE5NjAyNi8zMzMwMDQ2NzctM2UzYmE2OTQtNDU0NS00M2JlLThjMmUtNTlkMmY4NzEyNjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAxNTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYzZkODc0ODVlMTFkNzc1NjQ3ZDliNTFkOWFhZWY3ZTVhMzI3ZDhkMjUyYTkxMDgwNjEyZjhjNWRhZWRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Xt3-4t1JT_wnkd-RHP-PNLSY_OL24eiIHyTJ_EnkmE)

notion好是好,其实收费不收费我倒无所谓,关键英文我真不懂.也不是说我不懂这些单词,总之好别扭.

**Comment by 88250** [comment]
主键相关不考虑改变了；选项添加默认值等继续收集需求看看，谢谢。

**Comment by noenif** [comment]
> > 我支持这个：「单选/多选支持默认值」
> 
> 我看了notion能AI自动识别主键内容选择单选甚至创建单选项，有点6，当然思源能给个设置基本就够了 ![image](https://private-user-images.githubusercontent.com/63196026/333004677-3e3ba694-4545-43be-8c2e-59d2f8712622.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MjkzNDAsIm5iZiI6MTcxNjQyOTA0MCwicGF0aCI6Ii82MzE5NjAyNi8zMzMwMDQ2NzctM2UzYmE2OTQtNDU0NS00M2JlLThjMmUtNTlkMmY4NzEyNjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAxNTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYzZkODc0ODVlMTFkNzc1NjQ3ZDliNTFkOWFhZWY3ZTVhMzI3ZDhkMjUyYTkxMDgwNjEyZjhjNWRhZWRhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Xt3-4t1JT_wnkd-RHP-PNLSY_OL24eiIHyTJ_EnkmE)



> 主键相关不考虑改变了；选项添加默认值等继续收集需求看看，谢谢。

老大,可是主键手填真的有点累.

**Comment by noenif** [comment]
> 主键相关不考虑改变了；选项添加默认值等继续收集需求看看，谢谢。

老大,可是主键手填真的有点累.

**Comment by 88250** [comment]
可以把主键当做文本字段，或者不填也行。

**Comment by noenif** [comment]
> 可以把主键当做文本字段，或者不填也行。

确实可以这么理解,我看了一些issue,我感觉这东西更像是remark.或许可以把主要内容放这里.

**Comment by 88250** [comment]
选项默认值这个需求暂时不考虑了，请通过划选批量填充。
