### ISSUE TITLE
把一些伪元素提示更换成悬浮提示，并在有必要的时候添加类名

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11502]
> 需要先实现 #11440

### In what scenarios do you need this feature?

可以通过代码片段更改所有悬浮提示的样式，但伪元素和悬浮提示的样式不能统一就很难受。

还有一个问题是伪元素容易被遮挡，比如用 CSS 修改了行距后：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1bb63f22-85f7-4761-8202-dfb8f78ad9c1)

---

伪元素：

侧边栏按钮和侧边面板里的按钮：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b11732a7-faff-4596-af93-b4de4d274f9e)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5ea338c5-8a3a-4198-ae7f-6b7e41d97251)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bf3bcdf9-ef22-4c6e-9755-b4b83815bf22)

![image](https://github.com/user-attachments/assets/68353cc4-bedd-4f97-b717-624a6300575b)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/26e36bbd-3510-46f3-be97-bfbf3b1981c1)

某些元素的右上角按钮：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a7d424f3-6a07-4bbb-ac72-48129ae7dc9a)

某些浮窗上的按钮：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f54d75ba-fa20-47b9-a031-8022c9ba238a)

emoji 面板按钮：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/450ca687-0740-40a9-8838-60e3135aebfb)

集市：

![image](https://github.com/user-attachments/assets/208ffc01-3b02-4f68-b045-e434e371b040)

工具栏：

![image](https://github.com/user-attachments/assets/43086fb6-89e9-47a6-9878-8a100c2a3b37)

.layout__resize 元素的层级比工具栏高还会导致：
![c5c33cbaf8d407f271e383a8127c03ed](https://github.com/user-attachments/assets/9c78b124-ceac-4a3c-9a32-d0fdbf1ec6ef)

通知：

![image](https://github.com/user-attachments/assets/4fd7cf39-ea0d-4140-89fa-871a7a34dbbf)

……

### Describe the optimal solution

换成悬浮提示：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c2a6bcf3-0de1-4649-9a6e-2e0691255569)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c2973e33-7e7d-4ae6-8815-3b3aabef3676)

**Comment by Vanessa219** [comment]
太多了，要不先换一下样式？

**Comment by TCOTC** [comment]
> 其实伪元素更方便使用 css 来进行显示与否的修改。

伪元素的选择器不同是有点麻烦的，感觉不如 `改成悬浮提示之后加类名` 灵活，不过 `加类名` 怎么实现也是个问题，还是等我自己研究一下 #11440 再决定好了。

这个 issue 暂时先放着

**Comment by Lethe20** [comment]
1、无论选择哪一种方案，最好统一所有的悬浮提示，目前侧边栏使用的是伪元素，其他则使用showTip()动态生成。

2、伪元素的方案，对于系统资源的占用会不会少一点？因为提示仅限于css，不涉及javascript。

**Comment by Lethe20** [comment]
一些固定不变的提示，使用伪元素的方案，对于系统资源的占用会不会少一点？因为提示仅限于css，不涉及javascript。

**Comment by TCOTC** [comment]
> 使用伪元素的方案，对于系统资源的占用会不会少一点？

体感上应该没什么差别

**Comment by TCOTC** [comment]
刚刚发现伪元素也是可以统一改的，没必要换了。还是像 #12700 #12747 那样有需要再改成悬浮提示。这个 issue 先关了。
