### ISSUE TITLE
 内核因未知原因退出 The kernel exited for unknown reasons

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#11516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

演示↓（试了很多次都可以复现，两个工作空间都可以复现）
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/4f7eec8e-8ab2-49f2-a8f4-30d6d49458f7)

### Expected result

正常使用

### Version environment

```markdown
- Version: v3.0.15
- Operating System: 24H2 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
和这个应该是同一个问题 https://github.com/siyuan-note/siyuan/issues/11497 建议等发版以后再试试，这里先关闭。
