### ISSUE TITLE
数据库在只读模式应该不允许“复制为完整副本”

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#11518]
### In what scenarios do you need this feature?

数据库在只读模式下可以“复制为完整副本”
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/f0f30494-41a7-4102-a3a2-12c439f6d47b)

### Describe the optimal solution

数据库在只读模式应该不允许“复制为完整副本”

**Comment by TCOTC** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/7f957ca8-b0fd-48c8-848b-9c6c9cc648eb)
