### ISSUE TITLE
关系图功能请求：Graph Depth Support 添加对深度的支持

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#11513]
### In what scenarios do you need this feature?

在Obsidian的局部图谱中，有一个非常好用的功能叫做"深度"，允许用户在局部图谱（关系图）中延长节点的关系路径。
换句话说，我能看到当前节点的正反链标签等节点，还能看到与这些正反链标签节点相关的节点
一共可有五级深度，可以递进五次

该功能用于浏览或者导航都不错，希望思源也可以支持一下这个功能，非常有用，谢谢D大！

### Describe the optimal solution

该功能已在obsidian中实现：https://forum.obsidian.md/t/graph-view-consecutively-click-on-notes-and-tags-to-create-a-storyline-e-g-for-standup-comedy-routine/43965

**Comment by 88250** [comment]
你好，我们不会再为 关系图 添加特性，感谢理解。

**Comment by xRyul** [comment]
> 你好，我们不会再为 关系图 添加特性，感谢理解。

This is the only feature which is holding me back to fully transition into Siyuan. 

Seeing relationship between different notes at certain depth level via the graph is incredibly useful when doing research or simply consolidating all your notes. 

I am probably a complete noob, and maybe there is already something like that? 

If Siyuan is not planning on implementing this feature:

- what are other ways to see relationship between notes which are not directly connected? 
- what are other ways to find notes with only 1 link? (such notes usually indicate isolated information or forgotten ideas)
- what are other way to analyse flow of notes? (helpful in identifying bottlenecks e.g.: topic is not research in big enough depth thus more connections are needed to spread valuable information; helpful in identifying linear structure e.g.: more cross-links are needed to add bigger depth and variety of viewpoints)
- how can one find empty notes?

**Comment by KuiyueRO** [comment]
> 你好，我们不会再为 关系图 添加特性，感谢理解。

捞一手。局部关系图用来做非树状面包屑（导航）真的太合适了
