### ISSUE TITLE
每个笔记本创建独立配置选项

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#1151]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

- 目前有两个笔记本，笔记本A和笔记本B，两个笔记本的目录结构都不一样。
- 目前的"新建文档设置"和"新建日记设置"设置选项是全局的，不能实现每个笔记本独立配置。

![图片](https://user-images.githubusercontent.com/15924513/104847230-c212d280-5919-11eb-9f3c-f28ab6b25ed4.png)

### 描述最优的解决方案 Describe the optimal solution

- 对于"新建文档设置"和"新建日记设置"这些和笔记目录相关的配置，
- 每个笔记本的配置相互独立会更合理，配置选项分成两种："全局的"和"笔记本私有的"
- 如笔记本A新建日志，就只看到笔记本A的日志模板，而不会看到笔记本B的模板

### 描述候选解决方案 Describe the candidate solution

- 当前的解决方案是笔记本A和笔记本B在"新建文档设置"和"新建日记设置"相关的路径上保持一致
- 功能能够实现，但是并不优雅，但是笔记本A可以看到笔记本B的模板，笔记本B也能看到笔记本A的模板

### 其他信息 Other information

思源版本： V0.6.2
操作系统：Win10

**Comment by 88250** [comment]
后续考虑，谢谢建议。

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/1616 中处理，非常感谢。
