### ISSUE TITLE
关系图功能请求：Render Icon in graph view 在关系图中渲染图标

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#11514]
### In what scenarios do you need this feature?

希望可以在图谱中渲染文档图标，这样设置了图标的关键笔记辨识度会更高
![image](https://github.com/siyuan-note/siyuan/assets/63145205/0a792f04-bb87-409c-8e83-9961c4107d82)

### Describe the optimal solution

可以参考一下capacities和anytype的关系图谱，谢谢D大

**Comment by 88250** [comment]
你好，我们不会再为 关系图 添加特性，感谢理解。

**Comment by KuiyueRO** [comment]
> 你好，我们不会再为 关系图 添加特性，感谢理解。

这个也捞一手，和思源本体原生支持的图标进行配合真的很合适！！D大考虑一下吧，不急着更新，放backlog吧，用处确实没那么大，但它确实好看哇
