### ISSUE TITLE
数据库条目多选后右键支持复制块引用

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11520]
### In what scenarios do you need this feature?

![Clip_2024-05-24_10-20-35](https://github.com/siyuan-note/siyuan/assets/60436214/e000130d-e3db-4bc0-924c-ba2fd339f916)

希望数据库的条目多选之后，可以批量复制块引用

用途
1. 数据库做完筛选、排序后，批量复制多选条目的块引用，用于归档整理或临时整理需要
2. 数据库和列表型MOC相结合，数据库用于存放所有笔记，等到时机恰当，根据需要多选条目，粘贴到对应主题的列表MOC里

### Describe the optimal solution

数据库的条目多选之后，可以批量复制为块引用、纯文本、块超链接等格式，批量复制的样式建议是无序列表样式，有其他样式需求可以复制之后自行更改为有序列表、普通段落块等样式

### Describe the candidate solution

无

**Comment by 88250** [comment]
感谢提议，但有点疑问：对于绑定块可以做引用，那么对于非绑定块你是如何考虑的呢？

**Comment by Achuan-2** [comment]
> 感谢提议，但有点疑问：对于绑定块可以做引用，那么对于非绑定块你是如何考虑的呢？

1. 一种方法，只提供一个多选后的复制按钮，不区分复制纯文本、块引用、块超链接，同时选中绑定块和非绑定块，如果是绑定块，提供块引用，如果是非绑定块，提供纯文本，可以满足大部分需要，但一些人可能有额外需要（比如要复制块超链接到外部软件进行整理），需要多进行一步转换。
2. 第二种方法，依然提供具体的不同复制功能按钮（复制纯文本、块引用、块超链接），对于非绑定块，使用块引用、块超链接复制功能，则依然还是复制纯文本。可以满足所有需求，但是对于非绑定块，出现块引用、块超链接选项，复制的却是纯文本，可能用户会产生疑惑。

**Comment by 88250** [comment]
感觉第二种好一些，我们再考虑下，谢谢。

**Comment by TCOTC** [comment]
赞成第二种，并且我觉得「如果是非绑定块，提供纯文本」更好，否则明明多选选中了却没粘贴出来会很麻烦。

还有就是 `复制纯文本` 可能不需要列表，因为 `复制` 已经是带列表的纯文本了

另外还需要考虑一种场景：如果选中的条目都是纯文本条目，则菜单应该只显示 `复制` 和 `复制纯文本`

**Comment by Vanessa219** [comment]
复制多条的场景是？需要根据场景看多条数据之间用换行，逗号还是什么进行分割。

**Comment by TCOTC** [comment]
比如多选复制块引用，粘贴出来应该是这样的：

```
* ((20241025220855-1thlx7k '条目A绑定块'))
* ((20241025220902-0wkd4nm '条目B绑定块'))
* 条目C纯文本
* ((20241025220912-34sdbaj '条目D绑定块'))
```

**Comment by Vanessa219** [comment]
为什么是列表？场景是？

**Comment by TCOTC** [comment]
话说 1 楼不是写了吗

![image](https://github.com/user-attachments/assets/9e2fa9c5-7e4b-49b9-b82c-a4fb615370fb)

**Comment by Vanessa219** [comment]
用\n\n也很好转换，而且占到其他地方更方便吧。

**Comment by TCOTC** [comment]
列表块可以很方便转换为段落块，但段落块需要全部选中才能转换为列表块，条目越多就会越不方便。

**Comment by TCOTC** [comment]
@88250 菜单不只支持复制块引用，标题的 copy block refs 不准确，可以改改

**Comment by 88250** [comment]
> @88250 菜单不只支持复制块引用，标题的 copy block refs 不准确，可以改改

没看明白，麻烦截个图。

**Comment by TCOTC** [comment]
多选之后能复制的不只有块引用：

![image](https://github.com/user-attachments/assets/f91deaf9-314b-4a0b-b7cc-278433dc3bb7)
