### ISSUE TITLE
Improv outline drag and drop

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#11529]
https://ld246.com/article/1716123247390

**Comment by TCOTC** [comment]
[试了一下](https://github.com/TCOTC/siyuan/releases/tag/v3.0.16-dev001)，感觉 2px 的距离还是挺短的，可能 5px 会好点

**Comment by Vanessa219** [comment]
可能是由于我没用鼠标吧，这个没太多感觉。再等等看发帖者的感受吧。
