### ISSUE TITLE
希望将 Markdown 导入功能增加为直接导入为笔记本或保持原结构导入

### ISSUE THREAD

**Issue by ykla** [siyuan-note/siyuan#11528]
### In what scenarios do you need this feature?

目前要导入的文件夹A下有多个子文件夹，导入的时候会将该文件夹A作为笔记本的文档来处理，单独在笔记本下新建成一个文档叫做A（其他的子文件夹和根目录下的其他 ` .md` 都在A下面）。这个操作不符合预期。会造成相对地址识别错误也无法反映真实的结构路径。之前我似乎是直接复制的这些 md 到思源的目录下，会自动转换并处理，现在不会这样做了。起码在3月之前我还可以这样做，但是由于频繁更新已经不确定该功能是哪个版本变动的了。

### Describe the optimal solution

希望还原之前版本的行为。

### Describe the candidate solution

在导入 Markdown 文件夹时，直接导入文件夹内的子文件夹和 .md，不把该文件夹作为文档整体导入或者直接导入成一个笔记本。或者给与退回的选项。或者单独导入时允许 `ctrl a` 全选，目前只能单选 .md 且不能选择文件夹。

**Comment by 88250** [comment]
这个行为是设计如此，不考虑变更了，见谅。

> 之前我似乎是直接复制的这些 md 到思源的目录下，会自动转换并处理

一直不会处理的。

**Comment by ykla** [comment]
请考虑

>在导入 Markdown 文件夹时，直接导入文件夹内的子文件夹和 .md，不把该文件夹作为文档整体导入或者直接导入成一个笔记本。或者给与退回的选项。或者单独导入时允许 `ctrl a` 全选，目前只能单选 .md 且不能选择文件夹。” 

我认为该要求是合理的。
