### ISSUE TITLE
大纲添加右键菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11527]
### In what scenarios do you need this feature?

有时候需要在文档前做一个目录，得一个个标题复制块引用或者超链接，要在文档里来回跳转很麻烦（分屏能解决一部分问题，但不够方便），所以希望在大纲里右键点击标题时增加一个菜单方便复制

### Describe the optimal solution

红框里的是我觉得可以添加的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a3148868-c661-487e-a314-8cb8fb454b74)

**Comment by 88250** [comment]
悬浮大纲上的块标，浮窗中在使用该标题块的块标可以达到目的，所以就不考虑添加了。
