### ISSUE TITLE
从notion转过来，对数据库功能的一点小需求

### ISSUE THREAD

**Issue by Linnnkkk** [siyuan-note/siyuan#11523]
### In what scenarios do you need this feature?

首先本人表达对作者的感谢，开发这么棒的软件，而且开源，非常良心！！以下是我从notion转到思源的一点困扰
1. 目前在多个文档中引用同一个数据库，在其中任何一个文档操作数据库，其他页都会同步操作，包括数据库的视图，筛选等都同步。是否可以类似notion那样，只引用数据库，而不同步视图，筛选等。
2. 数据库新增的文档是否可以像notion那样有模板，且模板内可以对其他数据库进行变量筛选。
3. 数据库可以自动定时循环新增条目，类似notion。
以上三个点希望作者大大能够考虑，感谢

### Describe the optimal solution

na

**Comment by TCOTC** [comment]
请关注：

1. #10734
2. #11506
3. #10863

**Comment by 88250** [comment]
感谢反馈，请关注楼上帮忙整理的 issues。
