### ISSUE TITLE
列表项创建的编辑逻辑优化

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1153]
### 描述问题 Describe the problem
![image](https://user-images.githubusercontent.com/46141646/104847455-0e124700-591b-11eb-9648-a3a4aa7ddbe9.gif)

如图，折叠后1.1.1等对1.2是不可见的
直接回车后1.1.1等不应该是1.2的子项

### 期待的结果 Expected result

如图最后，回车后的1.2应该绕过1.1.1等
创建同级列表项应该绕过子项：因为子项已经有归属了
至少应该在折叠时候是如此的

创建同级列表项应该**只是创建同级列表项**
而不是**创建同级列表项，且把自己的子项全部迁移给同级列表项**

### 版本环境 Version environment

* 版本 Version：0.63

**Comment by wo4wangle** [comment]
D大这个isuue可以在 列表改进中 提前一些处理吗
因为这个是**列表里最影响体验的了**
比如，下图，我想给 java.nio.channels.FileChannel **向下 弄个同级项 且越过其子项** 很麻烦
**需要很多回车，也不知道回多少下是对的，还需要上下对照滚动着看…**
也可以直接enter再拖动块，但这样的场景在编辑列表时候基本几乎一直都在发生…

![image](https://user-images.githubusercontent.com/46141646/106400991-9edd3c80-645c-11eb-8b8b-329869c4a1a6.png)

**Comment by Vanessa219** [comment]
现在有个问题，折叠的是列表而非列表项，回车的时候会新生成一个列表。
只有当折叠的为列表项时才能满足以上需求，但是列表项又不太容易折叠到 🤦‍♀️

**Comment by blindYaksha** [comment]
实际测试发现：Workflowy 和 幕布，在中间的层级添加回车后，是增加最上面的子目录，原有的子目录会顺位到第二个。
![image](https://user-images.githubusercontent.com/5403899/107111062-d21e3200-6887-11eb-9dbe-114a0b2ac5de.png)

**Comment by blindYaksha** [comment]
在最后一行，连续敲击回车，则依次增加上一级的目录
![image](https://user-images.githubusercontent.com/5403899/107111076-fb3ec280-6887-11eb-8f30-a99360d8b3b7.png)

**Comment by blindYaksha** [comment]
为什么我上面粘贴的gif动图，显示不出来……
