### ISSUE TITLE
Add amd64 deb release package for Linux

### ISSUE THREAD

**Issue by KaiSiMai** [siyuan-note/siyuan#11532]
可以增加deb格式的包嘛？

### In what scenarios do you need this feature?

deb方便安装后管理

### Describe the optimal solution

无

### Describe the candidate solution

无

### Other information

尝试修改electron-builder-linux.yml 
打包成功
安装成功
正常运行
就是应用icon死活出不来
gnome环境
希望支持下deb

**Comment by 88250** [comment]
是按照 https://www.electron.build/configuration/linux#debian-package-options 这里修改的吗？请提供一下配置。

**Comment by 88250** [comment]
打 deb 似乎不支持 arm64 架构 https://github.com/electron-userland/electron-builder/issues/3901
