### ISSUE TITLE
让悬浮提示里的链接 `word-break: break-all;`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11539]
### In what scenarios do you need this feature?

如果提示是链接的话看起来会很奇怪：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c08d13e6-6b33-4cb7-9303-973c3a2dcfc8)

直接用 `.tooltip { word-break: break-all; }` 的话链接是正常了，但如果提示是普通文本的话就会在单词中间截断了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/56575817-e514-4c6d-95e3-314c8c682b7a)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/60588de2-38b7-4a8f-8f90-1ae6268d3b42)

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/78434827/92017384-d24a-4c68-b4d7-c1412158a5fb)

所以能不能给链接套一层 a 元素？ (或者是 data-type="a"？) 

然后单独给提示里的链接用 `word-break: break-all;`

**Comment by TCOTC** [comment]
这样直接加 style 的话会不会连标题一起 `word-break: break-all` 了？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7e5a94cb-3a6c-4cef-9edc-1315f11079d1)

**Comment by Vanessa219** [comment]
分开的，不会。
<img width="708" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/e70ddb7d-136d-43a4-8763-650f3394903d">
