### ISSUE TITLE
全局搜索中使用 ctrl+F 需继续进行搜索，而不是关闭搜索面板

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#11543]
https://ld246.com/article/1716632837934

**Comment by TCOTC** [comment]
我觉得不只是 全局搜索中使用 `Ctrl+F` 需继续进行搜索，下面两种情况也需要：

- [ ] 非全局搜索中使用 `Ctrl+F`
- [ ] 全局搜索中使用 `Ctrl+P`

**Comment by Vanessa219** [comment]
再次使用是关闭。

**Comment by TCOTC** [comment]
所以我就是想再次使用时不关闭

**Comment by TCOTC** [comment]
说到底 `Ctrl+F` 和 `Ctrl+P` 呼出的应该是同一个搜素窗口，只是 `Ctrl+F` 会多一个路径信息而已

**Comment by Vanessa219** [comment]
那为啥 ctrl+p 以后还要按 ctrl+p 呢？就比如很多菜单点击展开再点击就是关闭一样。

https://github.com/siyuan-note/siyuan/assets/970828/a9031fdf-0f1e-4e84-a68c-8606b01dc807

**Comment by TCOTC** [comment]
比如全局搜索时，选中某篇文档中的其他关键词，`Ctrl+P` 应该可以立即搜索。因为复制粘贴重新搜索太麻烦了。

就像浏览器的 `Ctrl+F` 搜索，可以反复按，而不是再按一次就关闭搜索了：

[浏览器.webm](https://github.com/siyuan-note/siyuan/assets/78434827/510ff85c-51fb-4b89-9f3c-475693b17122)
