### ISSUE TITLE
移动端文档无法显示所在的数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11549]
移动端没有像桌面端这样的标识：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/74d59c3b-b24c-4351-962a-0824229c410a)

关联 https://ld246.com/article/1716776365016

**Comment by Vanessa219** [comment]
是的，没有找到合适的位置放置。

**Comment by TCOTC** [comment]
为什么不像桌面端那样显示在右上角呢？

**Comment by Vanessa219** [comment]
移动端界面太小了。

**Comment by TCOTC** [comment]
界面虽然小，但位置应该是够的

**Comment by Vanessa219** [comment]
移动端标题是在顶部，放在那里会比较奇怪，并且位置是不够的。左右侧都有按钮。

**Comment by TCOTC** [comment]
我想的是这个地方：

![Screenshot_2024-05-28-10-26-44-39_ed1bdeca7a858bb430bfb9c256856672.jpg](https://github.com/siyuan-note/siyuan/assets/78434827/cde6e5c2-929a-4570-9cac-aca65434dfc9)

**Comment by 5kyfkr** [comment]
支持，题头图空出来这块位置完全够
