### ISSUE TITLE
Improve HTML code block clipping

### ISSUE THREAD

**Issue by mudebug77** [siyuan-note/siyuan#11540]
谷歌插件剪藏问题

### In what scenarios do you need this feature?

https://bbs.kanxue.com/thread-281901.htm
希望收藏这个网站的代码部分能修复一下。
收藏的代码区域会变成表格，需要手动修改。

代码部分收藏后会变成这样
![image](https://github.com/siyuan-note/siyuan/assets/34656102/5bc6bca1-0743-4751-9481-c7fac51107c6)

### Describe the optimal solution

最好能提供为一个UI接口
让用户对指定网站，实现转换规则自定义。

**Comment by 88250** [comment]
> 最好能提供为一个UI接口
让用户对指定网站，实现转换规则自定义。

这个不太明白，麻烦再描述一下。

**Comment by 88250** [comment]
下个版本会支持 syntaxhighlighter 表格类型的剪藏：

![image](https://github.com/siyuan-note/siyuan/assets/873584/8871a4ce-b52c-480b-b42f-d5d65bf176c9)
