### ISSUE TITLE
数据库 `复制为完整副本` 后，副本的关联列应该自动更改为对其他数据库的单向关联，不能影响原来的数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11548]
关联 #11460

目前把数据库 `复制为完整副本` 后，关联列的行为会变得很奇怪：（编辑副本的关联列不应该影响到其他数据库才对）

[副本.webm](https://github.com/siyuan-note/siyuan/assets/78434827/b6713440-3aec-4689-8c0d-878f94de83f3)

### Describe the optimal solution

数据库 `复制为完整副本` 后，副本的关联列应该自动更改为对其他数据库的单向关联，不能影响原来的数据库

**Comment by 88250** [comment]
感谢反馈，在 https://github.com/siyuan-note/siyuan/issues/11460 上提交改进。
