### ISSUE TITLE
手机伺服地址更新不及时的问题

### ISSUE THREAD

**Issue by h9485910** [siyuan-note/siyuan#11546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在局域网手机做伺服电脑使用的场景下，目前手机伺服地址有时候会变更，但是在设置关于里查看的地址还是上一个地址，公司有多个工作Wi-Fi，在连接的Wi-Fi变更的情况下伺服地址必然变更，但是目前只能关闭伺服功能再打开才能获取到变更后的伺服地址

### Expected result

伺服地址变更后能直接在设置关于里查看到最新的地址

### Version environment

```markdown
- Version: 3.0.15
- Operating System: win 11
- Browser (if used):
```

### Log file

No need

**Comment by luo-chuan** [comment]
可以这样回避你说的问题：
手机连接wifi时使用静态ip，然后通过python脚本一键打开思源伺服页面。
可以看这篇帖子 https://ld246.com/article/1711978885757

**Comment by Soltus** [comment]
https://github.com/Hi-Windom/Sillot-android/blob/main/app/src/main/res/layout/floating_window_layout.xml 使用的是悬浮窗显示IP

**Comment by 88250** [comment]
这个不考虑改变了，感谢理解。
