### ISSUE TITLE
Keep the width when duplicating database table view field

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11552]
数据库字段 `复制为副本` 支持复制列宽和值

### In what scenarios do you need this feature?

目前 `复制为副本` 只能复制字段类型和字段名称，**列宽**和**值**都没法 `复制` 过去

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a23d1f4b-39b0-4684-b0f2-4735eff412e2)

### Describe the optimal solution

数据库字段 `复制为副本` 支持复制列宽和值

列宽以当前视图的字段列宽为准

**Comment by 88250** [comment]
列宽可以考虑，值的话不考虑了，参考 Notion。
