### ISSUE TITLE
能不能ctrl+x剪切时，保留光标停留在一个空白的块中

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#11554]
### In what scenarios do you need this feature?

当前，选中几个块后剪切操作，光标会自动的移到下一个块的开始，能不能如标题那样，这样不至于使得剪切，复制逻辑和一般的软件太不一样，增加操作的一贯性。
还有就是空行的处理逻辑，当前如果从其他软件复制的文字块当中有空行，粘贴到siyuan里面时，空行全部消失。有时候空行是刻意留出来做视觉上的分隔的，这样的处理逻辑欠妥当。

### Describe the optimal solution

...

**Comment by TCOTC** [comment]
1. 都剪切了当然不会留下一个空白的块
2. 在 Markdown 里就是用空行来分隔段落的

这是一段话：

```
1111111111111
2222222222222
3333333333333
```

这是三段话：

```
1111111111111

2222222222222

3333333333333
```

**Comment by jiewangjs** [comment]
1）了解，但是我说的是一般操作逻辑。剪切一行文字，很多用户是不会期待光标移动到下面，然后这一行空间完全消失的。
2）markdown语法用空行分段这个我是了解的。但是现在的情况是，任意多的的空行，粘贴到siyuan里面，一个空行也不剩。为什么要保留，我的提问里原因已经写了很清楚了。

**Comment by TCOTC** [comment]
1. 思源是块编辑器，剪切了块，这个块就没有了，所以不会剩下什么
2. Markdown 语法里用来分隔段落的空行可以是任意多个（实际上标准的 Markdown 渲染里是没有空行这种东西的）

**Comment by 88250** [comment]
正如 @TCOTC 描述的那样，这两个是设计如此，不再考虑改变了，我关闭 issue 了，见谅。
