### ISSUE TITLE
文档 `复制为副本` 时，其中的数据库是否也需要 `复制为完整副本` ？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11551]
我倾向于把目前的 `镜像` 改为 `完整副本`

**Comment by 88250** [comment]
考虑了下，还是以镜像比较好，如果需要完整副本手动点击创建吧。

**Comment by TCOTC** [comment]
那用户在副本文档里操作之后影响到了原来的数据库怎么办呢？这个副本文档就不完全了

**Comment by TCOTC** [comment]
https://ld246.com/article/1773541586954
