### ISSUE TITLE
授权码能否记忆？

### ISSUE THREAD

**Issue by FEI352** [siyuan-note/siyuan#11550]
### In what scenarios do you need this feature?

输入过授权码就不用再输一遍了。

### Describe the optimal solution

目前的docker部署的授权码，浏览器后台删了就得重新输入一遍，能否想Memos一样可以记忆？
电脑上一直在后台没问题，在移动端留不住后台，每次都需要输入一遍密码很影响速记。

**Comment by TCOTC** [comment]
浏览器不是有保存密码的功能吗？

**Comment by FEI352** [comment]
> 浏览器不是有保存密码的功能吗？应该不会很麻烦



> 浏览器不是有保存密码的功能吗？应该不会很麻烦

可以，但是可以不用输入更好。

**Comment by 88250** [comment]
出于安全考虑，cookie 仅在 session 期间保存，所以请尝试使用浏览器客户端自动填充密码。
