### ISSUE TITLE
导出html引用的css/js脚本链接为本地地址问题

### ISSUE THREAD

**Issue by nn200433** [siyuan-note/siyuan#1155]
### 描述问题 Describe the problem

用户为何使用导出笔记为html？80%是发送给他人,或者分享粘贴到xxx网站呀。这时候127.0.0.1的地址就很蛋疼了鸭，建议将127.0.0.1转为`ld246`或`jsdeliver`地址

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/15652213/104860329-e4324200-5965-11eb-9480-cc689fb6e444.png)

**Comment by 88250** [comment]
通用格式的话建议用其他导出（比如 PDF），谢谢。
