### ISSUE TITLE
文档名支持使用富文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11563]
- 将文档名中的特殊字符转换为 HTML 字符实体保存
	- 直接复制标题时复制的也是 HTML 字符实体？
	- hPath 用 HTML 字符实体？
	- 需要考虑是否会引起其他问题
- 复制文本粘贴到文档名时不剔除特殊字符
- 文档树右键重命名弹出的窗口需要支持富文本输入
- 数据库主键支持富文本输入 #11553
- 导出为其他格式需要作为文件名时将文档名转换为纯文本
- 导出为 Markdown 时，如果启用了 `添加文档标题` ，那么将会在首行添加带 Markdown 标记符的一级标题

---

- 可以支持在文档名中使用 `/` 字符
- 文档名中可以使用块引用的话，双链的拓展性也许会更强？

---

https://ld246.com/article/1716884627072/comment/1716903011641#comments

**Comment by TCOTC** [comment]
还要考虑一下可读路径

**Comment by TCOTC** [comment]
用户需求：

- https://ld246.com/article/1731214659034

**Comment by 88250** [comment]
不考虑了，改动太大。
