### ISSUE TITLE
cnblog网页剪报代码块格式混乱

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#11568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

cnblog下的代码块似乎识别成了table
参考链接：
https://www.cnblogs.com/openharmony/p/17143897.html

### Expected result

代码块能被网页剪报保存笔记的时候还是代码块

### Screenshot or screen recording presentation

![cnblog_code_block_issues](https://github.com/siyuan-note/siyuan/assets/6134040/5eb7318f-f701-441e-8a8e-16dae49608fd)

### Version environment

```markdown
- Version: 3.0.14
- Operating System: Windows 10 14939
- Browser (if used): Chrome 123.0.6312.86 (正式版本) （64 位） (cohort: Stable)
```

### Log file

[siyuan.zip](https://github.com/siyuan-note/siyuan/files/15478240/siyuan.zip)

### More information

网页源码直接是
```
<pre data-index="0" class="set-code-show" name="code">
<code class="hljs language-cobol">
```
tag就是code，这里识别为表格我感觉可能是我哪里配置不对了或许

**Comment by 88250** [comment]
我这里使用最新版测试正常，建议更新下看看。

![image](https://github.com/siyuan-note/siyuan/assets/873584/fc4c6693-ae3a-40b7-ac45-fadb62710c5a)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by ruin1990** [comment]
问题解决感谢
