### ISSUE TITLE
文档树多选右键菜单增加 `复制`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11561]
就像 #11520 那样把多个条目放到无序列表里，可以把多个文档的 标题文本/块引用/超链接…… 放到一个无序列表里

关联需求：https://ld246.com/article/1716894086242

---

多选也需要支持使用快捷键 #13128

**Comment by frostime** [comment]
这里提供一些素材

![image](https://github.com/siyuan-note/siyuan/assets/27268127/f33024fa-0692-4447-ac9f-92b1bc0bdf70)
![image](https://github.com/siyuan-note/siyuan/assets/27268127/7faeca7d-ad68-4d62-b4cc-1414d7e21ddd)

**Comment by Jiangshuon** [comment]
以为和上周数据库多选一并实现了，原来没有，顶一顶

**Comment by TCOTC** [comment]
@Vanessa219 我这里没有复制：

![image](https://github.com/user-attachments/assets/27366414-a5a3-49ec-8e6c-d34fb66508c4)
