### ISSUE TITLE
Improve importing Markdown folder

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11567]
改进导入 Markdown 文件夹

导入 Markdown 文件夹时，如果其中的某一个文件夹下没有任何 .md 文件，那么就不需要在对应的目录位置创建同名的空白文档，只需要将其中的资源文件移动到 assets 文件夹里就行了。

并且要注意：不是忽略名为 `assets` 的文件夹（因为 assets 也可以是父文档名），而是在创建文档时忽略其中没有任何 .md 文件的文件夹。

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9a4c33f4-7600-41f9-a19b-09a72f95adc6)

https://ld246.com/article/1716885416114

**Comment by TCOTC** [comment]
@88250 看一下能不能兼容 FlowUs 导出的 Markdown 文件夹？

① 在 FlowUs 里的目录结构：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c9f9d7cc-ebb6-42b3-9cbe-1995c1119ecf)

② 导出的 Markdown 文件夹压缩包：

[测试+FlowUs+9b8a06e7-6e6e-48d6-b136-2a06b5636bd9.zip](https://github.com/siyuan-note/siyuan/files/15480021/%2BFlowUs%2B9b8a06e7-6e6e-48d6-b136-2a06b5636bd9.zip)

③ 导入思源后：（划线的是有重复创建的文档）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/0a413542-fe56-4658-b565-5e61ac474e36)

④ 文档内的链接不能指向导入的其他文档：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/49164454-0caf-4557-aa0b-d46259a90c80)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d1480112-6b62-4e1d-9542-283fc6a05cfc)

**Comment by 88250** [comment]
感谢提议，但是不考虑为特定导出格式进行适配了。

**Comment by TCOTC** [comment]
我又试了一下，原来思源导出的 Markdown 文件夹再导入也是不行的，不会链接到已导入的文档：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e01312ae-051f-43d1-ba06-629d27cbaa61)

**Comment by TCOTC** [comment]
导入 Markdown 文件夹，里面的文档有办法支持互相链接吗？

**Comment by 88250** [comment]
不支持相对路径处理的。

**Comment by TCOTC** [comment]
是技术上很复杂吗？

**Comment by 88250** [comment]
也不算太复杂，主要是没有时间处理。

**Comment by TCOTC** [comment]
我看到 ob 里用的也是超链接，有时候是路径（有同名文档时），有的时候是文件名（无同名文档时）

![image](https://github.com/user-attachments/assets/ab5ff023-83b3-45b7-ac72-4d312b7fb16b)

![image](https://github.com/user-attachments/assets/b6319ea0-123c-4317-aef9-9bb4ca862596)
