### ISSUE TITLE
Improve HTML h clipping

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11560]
剪藏：https://handbook.glyphsapp.com/drawing-paths/

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9aa99363-9839-4b7f-83a0-4f8f66f1ff2b)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/24ff037a-8bb5-4a01-8071-2073b5aaba17)

丢失了标题和图片

关联 https://ld246.com/article/1716890348320

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/713e7cc1-7c2b-4988-8096-e46b6036776c)

aside 这部分不会被剪藏，否则其他网站的侧边栏可能也会被剪藏下来。
