### ISSUE TITLE
Support Windows arm64

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11565]
https://ld246.com/article/1716822432347

**Comment by FEI352** [comment]
终于要做了吗？虽然可以用伺服和docker部署代替。不过做了我还是挺高兴的。

**Comment by 88250** [comment]
你那里有设备能帮我们测试下吗？下个 dev 版本会发布 win arm 安装包。



---Original---
From: ***@***.***&gt;
Date: Wed, May 29, 2024 01:34 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support Windows arm64 (Issue #11565)




 
终于要做了吗？虽然可以用伺服和docker部署代替。不过做了我还是挺高兴的。

**Comment by FEI352** [comment]
> 你那里有设备能帮我们测试下吗？下个 dev 版本会发布 win arm 安装包。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, May 29, 2024 01:34 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [siyuan-note/siyuan] Support Windows arm64 (Issue #11565) 终于要做了吗？虽然可以用伺服和docker部署代替。不过做了我还是挺高兴的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

我有一台Galaxybook2 骁龙850 8G。我该如何帮助你们测试？有了安装包之后我需要把x64的版本卸载吗？还是只装就行。

**Comment by 88250** [comment]
在 arm 设备上安装看看是否能用就行。



---Original---
From: ***@***.***&gt;
Date: Wed, May 29, 2024 07:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support Windows arm64 (Issue #11565)




  
你那里有设备能帮我们测试下吗？下个 dev 版本会发布 win arm 安装包。
 …
 ---Original--- From: @.&gt; Date: Wed, May 29, 2024 01:34 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [siyuan-note/siyuan] Support Windows arm64 (Issue #11565) 终于要做了吗？虽然可以用伺服和docker部署代替。不过做了我还是挺高兴的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: @.***&gt;
  
我有一台Galaxybook2 骁龙850 8G。我该如何帮助你们测试？有了安装包之后我需要把x64的版本卸载吗？还是只装就行。
