### ISSUE TITLE
快捷添加文本到 `虚拟引用关键字排除列表`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11573]
### In what scenarios do you need this feature?

https://ld246.com/article/1716886812137/comment/1716970697601#comments

- 或许可以在虚拟引用弹出的浮窗中增加一个按钮，用来排除该关键字
- 需要自动转义

**Comment by 88250** [comment]
这个之前考虑过，交给插件实现，已经提供 API： https://github.com/siyuan-note/siyuan/issues/9909
