### ISSUE TITLE
切換文檔後，無法顯示反向鏈接面板中的折疊/展開按鈕

### ISSUE THREAD

**Issue by Louie997** [siyuan-note/siyuan#11578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

切換文檔後，如果鼠標從左側靠近反向鏈接面板中的列表點，會無法顯示折疊/展開按鈕，
只能先從右側靠近，讓它顯示折疊/展開按鈕後，之後從左側靠近才能點擊折疊/展開按鈕。
以下示範：
![sybug2](https://github.com/siyuan-note/siyuan/assets/88768177/a0a32d50-e18b-4660-ba91-d62ef579f7dc)

### Expected result

切換文檔後，鼠標從左側靠近反向鏈接面板中的列表點，就能顯示折疊/展開按鈕。

### Screenshot or screen recording presentation

如上

### Version environment

```markdown
- Version: 3.0.16
- Operating System: win11
- Browser (if used):
```

### Log file

略

### More information

無

**Comment by Vanessa219** [comment]
和切换没有关系，是要求鼠标移动到块上造成的，已改进。
