### ISSUE TITLE
左侧大纲的默认字体太小

### ISSUE THREAD

**Issue by wrwe3888** [siyuan-note/siyuan#1157]
如下图，二级标题的字，就开始有点小了，三四级标题的字，就的确很小了。
如果想让大纲的级别更明显，可以像思源的列表项那样，每个层级一条竖线。
当然，如果有别的办法区分，那就更好了。
用缩小字体的方法，不是特别方便。

![QC}`1BGGD4}(UCB80O$SJKG](https://user-images.githubusercontent.com/62802939/104862062-28751080-596d-11eb-8cb9-9775271f8248.png)

**Comment by 88250** [comment]
063 调整大小，谢谢。

**Comment by wrwe3888** [comment]
那可否把相邻的层级之间错开的距离，稍稍稍稍调大一点？
估计一般人也就用到3级标题，距离调大一点，不会让左侧太宽。

另外，如下图，【学习笔记】这个标题下有子标题，但是我要把光标移到这个标题上，才知道它有子标题。
能不能在前面加一个标记，让人一看，就知道它有子标题？
![3ZKMD0_CD($M)OVD1C~~MWE](https://user-images.githubusercontent.com/62802939/104863033-dd103180-596f-11eb-9aaa-6a171ef90a7e.png)

**Comment by wrwe3888** [comment]
@88250 就类似那个红点一样。

**Comment by 88250** [comment]
@wrwe3888 063 会默认展开大纲层级的，稍后发布。
