### ISSUE TITLE
Improve rollback doc file history

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11575]
### 回滚文档后刷新文档名

回滚文档后文档名改变了，但：

- [ ] 该文档的**块引用的动态锚文本**没有刷新
- [ ] 该文档**页签显示的文档名**没有刷新
- [ ] **文档树**和**大纲**都忘记看了所以不清楚有没有刷新

![image](https://github.com/siyuan-note/siyuan/assets/78434827/1e63f797-9fc1-462d-855e-70b2e651f780)

**Comment by 88250** [comment]
重现步骤是？

**Comment by TCOTC** [comment]
1. `历史生成间隔` 设置为 1 分钟
2. 新建 2 个文档，分别命名为 "文档 A" 和 "文档 B"，在 `文档 A` 中引用 `文档 B`
3. 等待 1 分钟后生成历史
4. 删除 `文档 B` 的文档名，变为 "未命名"
5. 等待 1 分钟后生成历史
6. 在数据历史回滚 `文档 B` ，文档名恢复为 "文档 B"

大概就可以复现了

**Comment by 88250** [comment]
@Vanessa219 处理一下  该文档页签显示的文档名没有刷新
