### ISSUE TITLE
Software becomes laggy after a period of no operation

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#11571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

软件在一段时间没有操作后变得卡顿

情况1
今天开了软件没有操作等到操作的时候变得很卡，`Alt+5`创建今日笔记时也只新建文件没有加载模板，重启软件重建索引把新建的笔记删了，再重新`Alt+5`就恢复正常可以加载模板

情况2
每次刚刚重建索引完`【【关键字`创建双链都检索很快（1、2秒），软件开一段时间后，再次`【【关键字`创建双链就得加载转圈很久（7、8秒）

### Expected result

调查卡顿原因修复

### Version environment

```markdown
- Version: v3.0.16
- Operating System: Windows 11
```

### Log file

[app.log](https://github.com/siyuan-note/siyuan/files/15480776/app.log)
[siyuan.log](https://github.com/siyuan-note/siyuan/files/15480778/siyuan.log)

**Comment by 88250** [comment]
建议观察记录一下系统资源使用情况。

**Comment by 88250** [comment]
另外，如果开了插件和主题的话关闭后再测试。

我基本不关软件（只是系统睡眠），目前没有发现相关问题，先关闭 issue 了。

**Comment by Temacc0531** [comment]
默认主题无插件
情况1未能复现，我再继续观察
情况2还是会比刚索引完慢一些，但也没有7、8秒那么夸张
