### ISSUE TITLE
一个始终是 `未命名` 的动态锚文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11576]
在 #11575 回滚文档后发现了这个问题：（文档 B 是未命名，在回滚文档后文档名恢复为了"文档 B"）

[未命名.webm](https://github.com/siyuan-note/siyuan/assets/78434827/9bdca8d4-3730-4582-8ca9-8d89135ac31e)

这个问题的神奇之处在于：导出文档为 .sy.zip 之后再导入就正常了；直接复制文件到其他工作空间也是正常的，只在原来的工作空间有问题（重建索引也没用）。

所以可能要等 #11575 修复之后再看看这个问题。

**Comment by 88250** [comment]
还能重现么？

**Comment by TCOTC** [comment]
虽然原来已有的问题还在，但修好 #11575 之后应该就不会产生新的问题了。

所以我把这个 `未命名` 的文档修改标题后回滚了一下，所有 `未命名` 的块引就重新恢复正常了。

**Comment by 88250** [comment]
好的
