### ISSUE TITLE
块标没了

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11570]
刚刚用 Action 构建了一个：https://github.com/TCOTC/siyuan/releases/tag/v3.1.0-dev001

用的时候发现块标没了（另外试了一下 [v3.1.0-dev1](https://github.com/siyuan-note/siyuan/releases/tag/v3.1.0-dev1) 是有块标的）

@88250 看看你本地最新的版本有块标吗？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8c06c364-664c-4955-bf28-b18c5ff92302)

**Comment by 88250** [comment]
我这里正常，先关闭了。
