### ISSUE TITLE
使用快捷键 `复制为XX` 后选中与高亮该块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11574]
### In what scenarios do you need this feature?

我需要在使用快捷键后能够选中与高亮该块来辅助判断我复制的是否是正确的块。

目前直接按 `Ctrl+C` 复制块时会选中与高亮被复制的块，但用下面这几个快捷键就不会：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e22f54cc-c335-4132-b288-39ab7fd28189)

### Describe the optimal solution

使用快捷键 `复制为XX` 后选中与高亮该块

**Comment by Vanessa219** [comment]
这几个并不是内容，内容才需要选中。

**Comment by TCOTC** [comment]
手动选中块之后能按快捷键，那按快捷键之后为什么不能自动选中块呢？

**Comment by Vanessa219** [comment]
手动选择指的是？按哪一个快捷键？

**Comment by TCOTC** [comment]
点击块标、`Esc` 、`Shift+↑` 都能选中块，然后就能用这几个快捷键：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e473a212-700b-474a-9873-55f3422b2d3c)

因为我已经选中了块，所以我知道快捷键 `复制为` 的对象是哪个块。

但如果没有先选中块，而是直接使用快捷键，我就不清楚 `复制为` 的是当前段落块还是上层的容器块。（比如我试过之后发现绝大多数情况下复制的是段落块，但偶尔会复制成上层的容器块）

---

只有 `Ctrl+C` 时会高亮块：

[复制.webm](https://github.com/siyuan-note/siyuan/assets/78434827/c04362ab-62f1-4df2-b5fe-19321259bd19)

**Comment by Vanessa219** [comment]
复制的是当前光标所在的块，如果当前块没有相邻的块，则为父块。

**Comment by TCOTC** [comment]
我还是希望我用快捷键之后能高亮一下相应的块

**Comment by Vanessa219** [comment]
再看看其他用户的需求吧

**Comment by TCOTC** [comment]
类似的需求：https://ld246.com/article/1734338113594

@Vanessa219 我觉得可以为对应的块短暂添加 .protyle-wysiwyg--hl 类名（添加 1s 再移除）

**Comment by Vanessa219** [comment]
这个提示以前好像讨论过，复制不进行提示的。

**Comment by TCOTC** [comment]
我觉得更多是一种交互的反馈带来的安心感，按快捷键之后没有反应的话会怀疑是否有正确复制对应的块

**Comment by Vanessa219** [comment]
很多软件复制都没有反馈的，否则太干扰了。
