### ISSUE TITLE
OCR api 返回文字坐标信息

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#11584]
### In what scenarios do you need this feature?

扩展现有ocr能力

### Describe the optimal solution

可参考 [百度ocr api 文档](https://ai.baidu.com/ai-doc/OCR/vk3h7y58v) 的返回结构

**Comment by 2234839** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/49fc394f-792d-4ea5-bf48-6f6ff056af49)

@88250  如果可以返回定位信息的话，将这个功能内置到思源里，我感觉也可以作为一大卖点

**Comment by Achuan-2** [comment]
支持！

**Comment by Achuan-2** [comment]
以及建议更换OCR为paddle OCR，见：https://github.com/siyuan-note/siyuan/issues?q=is%3Aissue+is%3Aopen+paddle

**Comment by TCOTC** [comment]
- #10232

**Comment by 88250** [comment]
我搜了下 TesseractOCR，好像可以支持，有空的话请帮忙 PR，谢谢。

**Comment by 2234839** [comment]
换不换ocr引擎

**Comment by 88250** [comment]
不换的，换引擎目前还要考虑跨平台问题。

**Comment by Achuan-2** [comment]
建议直接换引擎，paddle OCR识别又快又准
我最近几个扫描的pdf，都是用https://github.com/hiroi-sora/Umi-OCR，进行OCR的，效果很满意
paddle OCR也是支持多端的，见这个项目：https://gitee.com/bingal/ai-ocr/tree/main

**Comment by 88250** [comment]
@Achuan-2 没有 Windows/Linux 编译包，恐怕换不了。

**Comment by Achuan-2** [comment]
有人在做了，不知道这个能不能用：https://github.com/Gavin1937/PaddleOCR-json/releases/tag/v1.4.0

**Comment by 2234839** [comment]
其实支持 PaddleOCR 我认为也可以，但是不能以嵌入的方式，只能说如果环境变量中能够使用就用
