### ISSUE TITLE
升级后新版本后代码编辑器有BUG

### ISSUE THREAD

**Issue by chennbnbnb** [siyuan-note/siyuan#11581]
### In what scenarios do you need this feature?

比如下面这个代码编辑框
<img width="973" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42932041/7b8d84fe-9e89-44da-8f5e-da8e937592e0">

1. 全选后安向上方向键, 光标会直接跳出代码编辑框, 理想情况是回到代码开头
2. 全选后安左方向键, 光标回到开头, 但是再按向下方向键, 会直接调到代码末尾, 理想情况是跳转到下一行代码

### Describe the optimal solution

希望操作逻辑能够像vscode一样, 至少也要和老版本一样, 新版本的代码编辑器有点反人类

**Comment by chennbnbnb** [comment]
问题复现: 
1. 从vscode复制代码粘贴到文档内
2. Command+A全选
3. 按左方向键回到代码开头
4. 按下方向键: 预期: 光标进入下一行; 实际操作: 跳转到代码末尾

**Comment by Vanessa219** [comment]
全选后按上和下跳转到上下块，按左右跳转到开头和末尾，这个是正常的操作。


`全选后安左方向键, 光标回到开头, 但是再按向下方向键, 会直接调到代码末尾, 理想情况是跳转到下一行代码`
这个无法重现，使用默认主题，关闭插件再试试。

**Comment by TCOTC** [comment]
我这里：

- 按 ↑ 会跳转到代码的倒数第二行
- 按 ↓ 会跳到代码块的下一个块
- 按 ← 和 → 是跳到代码的开头和末尾

**Comment by chennbnbnb** [comment]
> 全选后按上和下跳转到上下块，按左右跳转到开头和末尾，这个是正常的操作。
> 
> `全选后安左方向键, 光标回到开头, 但是再按向下方向键, 会直接调到代码末尾, 理想情况是跳转到下一行代码` 这个无法重现，使用默认主题，关闭插件再试试。

对于从vscode直接复制到文档内的代码才会复现出来

**Comment by chennbnbnb** [comment]
> 我这里在代码块内全选代码后：
> 
> * 按 ↑ 会跳转到代码的倒数第二行开头
> * 如果代码块末尾没有空行，按 ↓ 会跳到代码块的下一个块
> * 如果代码块末尾有空行，按 ↓ 会跳到代码的最后一行（即空行）
> * 按 ← 和 → 是跳到代码的开头和末尾
> 
> 感觉 ↑ 和 ↓ 有点不协调

是的, 代码框内部的全选, 上下方向键, 光标不应该跳出代码块

**Comment by TCOTC** [comment]
> 对于从vscode直接复制到文档内的代码才会复现出来

我这里也复现不了，给一下具体代码？

**Comment by TCOTC** [comment]
> 代码框内部的全选, 上下方向键, 光标不应该跳出代码块

其实我觉得这个没什么问题，跟在其他类型的块中全选内容再按方向键后的行为保持一致就好

**Comment by chennbnbnb** [comment]
复现的视频:


https://github.com/siyuan-note/siyuan/assets/42932041/075904d2-95a3-4507-90a3-3b9fbf0f5f23

**Comment by chennbnbnb** [comment]
未安装任何插件

**Comment by TCOTC** [comment]
@chennbnbnb 是啥系统？思源版本是多少？

**Comment by chennbnbnb** [comment]
> @chennbnbnb 是啥系统？思源版本是多少？

MacOS Monterey 12.4 (21F79)
Processor: Intel Core-i9
思源: v3.0.16

**Comment by TCOTC** [comment]
不知道是不是环境不同的原因，我 Windows10 的问题是上面提到的 2 点：

- 按 ↑ 会跳转到代码的倒数第二行开头
- 如果代码块末尾有空行，按 ↓ 会跳到代码的最后一行（即空行）

**Comment by chennbnbnb** [comment]
补充: 从vscode复制代码到文档内后, 在代码框的任意位置按 ↓ 都会直接跳转到最后一行, 无论最后一行是否有空行

**Comment by chennbnbnb** [comment]
这个问题对使用影响太大, 已经回退到3.0.11 release版本, 实测这个版本的代码编辑是没问题的

**Comment by chennbnbnb** [comment]
> 不知道是不是环境不同的原因，我 Windows10 的问题是上面提到的 2 点：
> 
> * 在代码块内全选代码后，按 ↑ 会跳转到代码的倒数第二行开头
> * 在代码块内全选代码后，如果代码块末尾有空行，按 ↓ 会跳到代码的最后一行（即空行）

和代码块最后一行有没有空格没关系, 老版本不支持云端,  新版本常用功能有BUG, 这也太难受了

**Comment by TCOTC** [comment]
我这里是跟空行有关系的

**Comment by chennbnbnb** [comment]
> 我这里是跟空行有关系的

我找到可以稳定复现的方法: 
如果代码块是本文档的最后一个块, 那么在代码块中就会出现这个跳转问题; 具体操作
1. 光标移动到文档末尾
2. 然后一直删除, 直到光标跳转到代码框内部
3. 然后ctrl+a全选代码, 后按"<-"移动到代码块开头
4. 再按 ↓就会跳到代码的最后一行
- 只要在文档的末尾随便放一些东西, 就可以避免这个问题

**Comment by TCOTC** [comment]
> 在代码块内全选代码后，按 ↑ 会跳转到代码的倒数第二行开头
> 在代码块内全选代码后，如果代码块末尾有空行，按 ↓ 会跳到代码的最后一行（即空行）

我补个录屏吧：

[代码.webm](https://github.com/siyuan-note/siyuan/assets/78434827/27ab8cb6-08c8-4486-a95c-a63608c53ee5)

**Comment by Vanessa219** [comment]
现在还有问题么？我好想都无法重现。

**Comment by TCOTC** [comment]
我这里依旧是这样。

1. 在代码块内全选代码后，按 ↑ 会跳转到代码的倒数第二行开头
2. 在代码块内全选代码后，如果代码块末尾有空行，按 ↓ 会跳到代码的最后一行（即空行）
3. 在代码块内全选代码后，如果代码块末尾无空行，按 ↓ 无效果

[视频.webm](https://github.com/user-attachments/assets/a8cbc247-9caf-4379-bbcb-21bafe2e3e56)


我的预期是光标跳转到选中部分的开头或结尾（VSCode 就是这样的）

**Comment by TCOTC** [comment]
我希望在这种情况按 `↓` 之后光标移动到选中的最底部的文本的下一行：

[视频.webm](https://github.com/user-attachments/assets/a9aa947c-f149-4690-b6c4-60b7ae3aedfc)

**Comment by Vanessa219** [comment]
mac 上这些都是正常的，我再看看吧。

**Comment by Vanessa219** [comment]
我在 windows 上试了也是好的，你把 .sy 文件发我看看

**Comment by TCOTC** [comment]
[代码块.sy.zip](https://github.com/user-attachments/files/17057260/sy.zip)

[视频.webm](https://github.com/user-attachments/assets/0110ca28-a0ef-4019-8c3a-98e483bb7b95)

**Comment by 88250** [comment]
@TCOTC Windows 上浏览器就这样了，没法改。
