### ISSUE TITLE
The User Guide is no longer opened repeatedly when multiple windows exist

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11588]
用户指南会在多个窗口同时打开

https://ld246.com/article/1714665469659

能直接解决 #10989 的第二点

**Comment by TCOTC** [comment]
粗略搜了一下没搜到 issue ，所以新建了这个 issue

**Comment by TCOTC** [comment]
@88250 消息会在每个窗口弹出：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9d103798-8e49-4db3-bd41-dfe5ed501e69)

**Comment by 88250** [comment]
这个是正常的，消息是广播通知。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sat, Jun 1, 2024 01:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] The User Guide is no longer openedrepeatedly when multiple windows exist (Issue #11588)




 
@88250 消息会在每个窗口弹出：
 
image.png (view on web)

**Comment by TCOTC** [comment]
> 消息会在每个窗口弹出
> 
> > 这个是正常的，消息是广播通知。

这个能不能限制在当前操作的窗口弹出？有时候弹个报错或提示，要在每个窗口都点一遍。

**Comment by 88250** [comment]
这个目前不作调整了。
