### ISSUE TITLE
拖拽文档时隐藏悬浮提示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11587]
拖拽文档时需要隐藏悬浮提示，否则就会被遮挡：

[拖拽文档时需要隐藏悬浮提示.webm](https://github.com/siyuan-note/siyuan/assets/78434827/0b93524f-e499-4294-86e4-a2bb1cd708ec)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by TCOTC** [comment]
@Vanessa219 把文档拖回原位之后要重新显示悬浮提示。

目前是要把鼠标移动到其他文档再移回来才重新显示悬浮提示：

[视频.webm](https://github.com/user-attachments/assets/8cf05d67-56a4-4931-97d2-ace65996604f)
