### ISSUE TITLE
The browser extension supports Wikipedia formula clipping

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11583]
剪藏插件支持剪藏维基百科的公式

### In what scenarios do you need this feature?

目前用思源的剪藏插件只能把维基百科的公式以图片的形式剪藏下来，希望适配维基百科的公式剪藏
示例网页：https://zh.wikipedia.org/wiki/%E7%91%9E%E5%88%A9%E8%B7%9D%E7%A6%BB
复制维基百科的公式，默认为图片，图片的alt带有latex公式, 内容如下
```
{\displaystyle z_{\mathrm {R} }={\frac {\pi w_{0}^{2}}{\lambda }},}
```

### Describe the optimal solution

适配维基百科的公式剪藏，希望是剪藏为markdown数学公式，而不是图片

**Comment by TCOTC** [comment]
我还一直以为 wiki 的公式就是图片的

**Comment by TCOTC** [comment]
@88250 上面这里剪藏看起来怪怪的：

网页：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2e36a58d-c0b3-4b3b-b931-87a87dff8634)

剪藏：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/98b8d98c-080d-4ad4-9745-13ad009880d4)

**Comment by TCOTC** [comment]
还有就是剪藏之后这里会多出一堆 svg：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/98ddb329-8cb6-4ec9-b27e-176325c537a3)

**Comment by 88250** [comment]
> @88250 上面这里剪藏怪怪的：
> 
> 网页：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/335687592-2e36a58d-c0b3-4b3b-b931-87a87dff8634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTAzMjQsIm5iZiI6MTcxNzIxMDAyNCwicGF0aCI6Ii83ODQzNDgyNy8zMzU2ODc1OTItMmUzNmE1OGQtYzBiMy00YjNiLWI5MzEtODdhODdkZmY4NjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDAyNDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MTBmMjVmZjhjODQ2OTFkZThkMTRiNzJmYjJiZDQ1MWQ3NzQ2ZGFmZGI3NmRiMDZjMTJiZWQwNTc4M2QxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.59oAcrPEH8ITrixkIYDpZD9-v0LG82AssqWVpxL5Qh4)
> 
> 剪藏：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/335687460-98b8d98c-080d-4ad4-9745-13ad009880d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTAzMjQsIm5iZiI6MTcxNzIxMDAyNCwicGF0aCI6Ii83ODQzNDgyNy8zMzU2ODc0NjAtOThiOGQ5OGMtMDgwZC00YWQ0LTk3NDUtMTNhZDAwOTg4MGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDAyNDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZmRlZjg5YjJhNjI5NjJhMTYzMDNmNTRiYzNhZWFjYzFjODcxNTVlZDQ3ZDJiMjZlNzA0MTAzOTk5ZmZiZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Up_XY1MYBPek4uS1ZRocIjgGeZWYp3nvcoy7Sw5YM3Y)

这个是符合剪藏的摘要获取规则的。

**Comment by 88250** [comment]
> 还有就是剪藏之后这里会多出一堆 svg：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/335772391-98ddb329-8cb6-4ec9-b27e-176325c537a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMTAzMjQsIm5iZiI6MTcxNzIxMDAyNCwicGF0aCI6Ii83ODQzNDgyNy8zMzU3NzIzOTEtOThkZGIzMjktOGNiNi00ZWM5LWIyN2UtMTc2MzI1YzUzN2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDAyNDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMjM2MjJhMjYxOWViNzliNmMxYjNlZGFkMjBmNTRmNzg0NzZjMDE4MDlkNGJlNGQyMzI1MGYyMDcyOTUxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R3KKfA-PWtAlUGksKWIc82oFw9IpGKTtOA0gW5oYuVk)

这个暂时没办法了，剪藏扩展会将能够下载的文件先下载插入，和思源中判断解析网页可能会有所出入。

**Comment by TCOTC** [comment]
> 这个是符合剪藏的摘要获取规则的。

但是为什么会在同一个块里没有换行呢？

**Comment by TCOTC** [comment]
@88250 旧版剪藏是正常的两个块的：

https://zh.wikipedia.org/wiki/%E7%91%9E%E5%88%A9%E8%B7%9D%E7%A6%BB

![image](https://github.com/siyuan-note/siyuan/assets/78434827/20373a20-9f9b-4556-b7f2-0b2de33a6bda)

新版变成一个块了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c0f6229d-9aa9-48cf-8a64-c6e22d43f1b1)

**Comment by 88250** [comment]
从内容上上看新版的更完整，这个图片被算作行级元素并到下面的 p 里了，应该算是zheng正常情况：

![image](https://github.com/siyuan-note/siyuan/assets/873584/7cef188f-c3bf-4b9a-95c4-2cdca5d5eec5)

**Comment by TCOTC** [comment]
为啥并到下面去是正常的？在 p 内的应该才算是 p 的行级元素吧？

**Comment by 88250** [comment]
> 为啥并到下面去是正常的？在 p 内的应该才算是 p 的行级元素吧？

https://github.com/siyuan-note/siyuan/issues/11640
