### ISSUE TITLE
Improve `Expand Down/Up` keymaps on Windows

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#11593]
`向下/上扩选` 在 Windows 中没有选中元素时无效

https://ld246.com/article/1716635371149

**Comment by TCOTC** [comment]
@88250 我有个问题，这两个快捷键和 `Shift+↑` `Shift+↓` 的区别是什么？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5556991d-f948-4a72-8693-bd16c0eed1f1)

**Comment by 88250** [comment]
一个是保留已经选择的，一个不保留。
