### ISSUE TITLE
微软应用商店版设置-关于页面由于移除了更新按钮JS报错，导致其它按钮也无法使用

### ISSUE THREAD

**Issue by XinRoom** [siyuan-note/siyuan#11590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

设置-关于页面部分按钮点击无法使用，比如访问授权码设置按钮，该界面有如下报错：
疑似由于移除了更新按钮，对应js代码报错，后续js代码也无法执行绑定按钮事件导致的。

![image](https://github.com/siyuan-note/siyuan/assets/32238570/5442cf5e-17fd-4ca2-ba8f-7b6e3289067b)

![image](https://github.com/siyuan-note/siyuan/assets/32238570/9b479e32-4903-4b5f-8ab3-55b351d6e444)

### Expected result

设置-关于页面 不报错，如访问授权码设置按钮可以使用。

### Version environment

```markdown
- Version: v3.0.16
- Operating System: Win11
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/15507282/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，已在 https://github.com/siyuan-note/siyuan/issues/11580 中修复。
