### ISSUE TITLE
网络图片转换为本地图片功能失效 http 401

### ISSUE THREAD

**Issue by jibwf** [siyuan-note/siyuan#11594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

从网页上复制粘贴资料到思源，里面包含图片链接。之前可以通过网络图片转换为本地，现在这个功能不好用了，会显示下载图片，最后会提示文档中不存在网络文件. 日志显示401，但是链接直接复制到浏览器打开没问题.

E 2024/05/31 10:11:59 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_032.png] failed: 401
E 2024/05/31 10:11:59 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_033.png] failed: 401
E 2024/05/31 10:11:59 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_034.png] failed: 401
E 2024/05/31 10:12:00 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_035.png] failed: 401
E 2024/05/31 10:12:00 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_036.png] failed: 401
E 2024/05/31 10:12:00 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_059.png] failed: 401
E 2024/05/31 10:12:00 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/Legacy/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_038.png] failed: 401
W 2024/05/31 10:12:00 blocktree.go:576: save block tree [size=10.2 MB] to [/Users/bowji/SiYuan/temp/blocktree], elapsed [3.45s]
E 2024/05/31 10:12:01 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_039.png] failed: 401
E 2024/05/31 10:12:01 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_040.png] failed: 401
E 2024/05/31 10:12:01 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_041.png] failed: 401
E 2024/05/31 10:12:01 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_052.png] failed: 401
E 2024/05/31 10:12:01 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_053.png] failed: 401
E 2024/05/31 10:12:02 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_042.png] failed: 401
E 2024/05/31 10:12:27 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_032.png] failed: 401
E 2024/05/31 10:12:28 assets.go:184: download net img [https://ondemandelearning.cisco.com/apollo-alpha/mc_scor10_22/assets/Security/Monolithic/SCOR/v1.0/GF/SCOR_1-0-0_Deploying_Cisco_ASA_Firewall_033.png] failed: 401

### Expected result

可以从网络上下载图片存到本地

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/65640470/036aae9c-759e-44b3-884c-e332419ecd87)

### Version environment

```markdown
- Version: 3.0.16
- Operating System: macOS 14.5 
- Browser (if used):safari
```

### Log file

[siyuan.log.zip](https://github.com/user-attachments/files/15507586/siyuan.log.zip)

**Comment by 88250** [comment]
401 说明目标站点有防盗链，可以试下用浏览器剪藏扩展。
