### ISSUE TITLE
 v3.0.16 改进网页剪藏，但是把网页划线高亮的加粗显示也取消了

### ISSUE THREAD

**Issue by wildshen** [siyuan-note/siyuan#11597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

浏览网页的时候使用荧光笔，划线高亮等扩展的时候，思源是会对高亮划线部分进行加粗，非常方便我画出重点。
但是最新版本思源已经无法对其加粗显示了

我是用的浏览器扩展一款是Readily，以前用于obsidian的，但是发现思源复制过来后，高亮部分还是可以加粗字体。
一款是:：ZetaMarker 萤光重点标注工具 - 网页和 PDF。高亮后可以直接显示。
很多高亮扩展都是不行的，比如五彩等，但是上面两款是可以的。

但是 v3.0.16版本都不行，不知道是不是改了什么地方。
顺便说下，其他剪藏工具，比如web clipper也是不行的，一直都不行，这也是一直用思源官方的原因。
不过，从现在这个版本开始，都一样了

### Expected result

浏览网页可以把自己高亮划线的重点，剪藏倒思源中。

### Version environment

```markdown
- Version: v3.0.16
- Operating System: Windows11
- Browser (if used):edge
```

### Log file

这个是版本问题

**Comment by 88250** [comment]
之前我们将 span 元素作为 加粗 转换，但是后来发现这样转换会导致其他问题，所以不再转换了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/690bb4a6-3125-47ab-a240-03750214a615)

**Comment by wildshen** [comment]
@88250 这个功能对于浏览网页划重点真的非常好，太方便了。有什么其他方法吗

**Comment by 88250** [comment]
@wildshen 目前没有办法了，抱歉。
