### ISSUE TITLE
need an API to get the current (last) active document block ID (or siyuan uri)

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#11596]
### In what scenarios do you need this feature?

I want to create a file shortcut for the current active document in my current working Explorer foler.
To create the url shortcut, I have to get the siyuan document url (sample format as siyuan://blocks/20230722081010-23riaqk).
Currently I have to use external automation script (e.g. AutoHotkey) to first activate the Siyuan Window, and then click the document, and then Send "Ctrl-Shift-H" event to Siyuan.
The problem is that Ctrl-Shift-H will return nothing if there editable client area is not focused (i.e. without an I-beam cursor flickering). So normally we have to click the document in order to get an I-Beam cursor. But it is trick for the automation script to find the correct place to click.

### Describe the optimal solution

In most case, I only use the default Siyuan-note window, and occasionally I open some siyuan docs in Chrome. 
It is preferrable the last active document ID is recorded based on the last active siyuan window (default or Chrome, or other browsers) and its active tab.

the name of the API could be /api/filetree/getLastActiveDocID and the parameter could be left empty.

### Describe the candidate solution

Alternatively allow the Ctrl-Shift-H to return siyuan uri event when there is no I-Beam cursor flickering. 

Many thanks!

**Comment by 88250** [comment]
Sorry, the kernel API cannot get the front-end active window.
