### ISSUE TITLE
分屏/不同窗口打开同一个文档编辑，文档内容块重复/顺序错误

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11607]
今天打开了两个窗口分别编辑同一个文档的前后部分（左侧编辑前面，右侧编辑后面），在某个时刻我在右侧窗口向上快速滚动文档，就出现了异常。

左侧主窗口的块顺序是正常的；在右侧窗口中则是异常的。

p.s. 虽然右侧窗口看起来像是开头的几个块跑到了文档中间，但我感觉更像是文档中间的块跑到了开头去：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/119e86b1-802b-41e5-b4d6-c861b568f575)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d5c1f2d3-25da-47b0-9c3c-f1299e9023cd)

尝试在右边窗口导出文档，在另一个工作空间导入后发现顺序是正常的，说明只是显示上的问题，没有影响到实际数据。

---

因为编辑文档的时候块的大小变化较大（嵌入块、代码块之类的），所以在编辑左侧文档的时候右侧文档的块是忽上忽下动来动去的，我怀疑就是这种情况导致动态加载出现了问题。

p.s. 当然也可能不是这个的问题

还可能是因为当时在左侧滚动之后立刻又在右侧滚动

**Comment by TCOTC** [comment]
右侧窗口文档在滚动到中间位置后按 F5 刷新才恢复正常

**Comment by TCOTC** [comment]
文档：[任务列表.sy.zip](https://github.com/user-attachments/files/15514214/sy.zip)

**Comment by TCOTC** [comment]
今天在同一个窗口内分屏时出现了可能类似的问题，向上滚动时卡顿了一会，然后就加载出了相同的块

![image](https://github.com/siyuan-note/siyuan/assets/78434827/25913dcb-0d91-4200-8d48-769992419836)

**Comment by TCOTC** [comment]
今天向右分屏的时候，右侧的文档只剩一个标题块和一个列表块了：（不是聚焦状态）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c467a6e8-813f-4020-af04-55766ea54dcf)

**Comment by Vanessa219** [comment]
导入了，具体是要怎么操作呢？我尝试了滚动和编辑好像没办法重现。

**Comment by TCOTC** [comment]
我也没有稳定的复现步骤，只是偶然遇到了才提一提

**Comment by Vanessa219** [comment]
我试了一下重现不了。

**Comment by Vanessa219** [comment]
我试了一下重现不了。
