### ISSUE TITLE
Markdown syntax switch no longer affects clip/paste HTML parsing

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11604]
### In what scenarios do you need this feature?

比如直接在GitHub复制右边的内容到思源笔记👉 f<sup>R</sup>​<sub>S</sub>
上标和下标，如果关闭「Markdown下标语法」和「Markdown上标语法」就无法渲染
![Clip_2024-05-31_17-07-04](https://github.com/siyuan-note/siyuan/assets/60436214/1ba408ca-109a-4206-9b38-6813c912275c)

### Describe the optimal solution

剪藏下标在关闭Markdown下标语法的时候，依然能正常渲染
剪藏下标应该默认是`<sup></sup>`，上标是`<sub></sub>`

**Comment by 88250** [comment]
这个是设计如此，要开启上下标语法才能解析。

**Comment by Achuan-2** [comment]
问题是，复制样式，剪贴板查看本身就是html样式，是思源给处理为了Markdown语法

**Comment by 88250** [comment]
没有办法处理，思源内部是用 Markdown 语法解析的，如果关闭了语法开关，则无法解析。

**Comment by Achuan-2** [comment]
不然剪藏默认把上下标改为`<sup></sup>`和`<sub></sub>`吗？
现在思源也是支持直接粘贴`<sup></sup>`和`<sub></sub>`，解析上下标的

**Comment by 88250** [comment]
那暂时没有办法了，先挂着吧。

**Comment by Achuan-2** [comment]
目前上下标的剪藏，我觉得可以把默认的解析语法改为`<sup></sup>`和`<sub></sub>`，毕竟现在的默认导出上下标已经是html语法了，输入却是Markdown的`^`和`~`就有问题。
但是考虑之后要添加斜体等样式的语法开关的话，
可能要对富文本的粘贴单独进行解析，而不考虑Markdown语法解析开关，这样可以在不影响粘贴富文本的情况下，关闭Markdown特定语法的输入，不知道这样能不能实现？

**Comment by 88250** [comment]
估计只能支持少量 HTML 输入，不然语法冲突太多。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月1日(周六) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 关闭 Markdown 上下标语法后剪藏上下标无法渲染 (Issue #11604)




 
目前上下标的剪藏，我觉得可以把默认的解析语法改为<sup&gt;</sup&gt;和<sub&gt;</sub&gt;，毕竟现在的默认导出上下标已经是html语法了，输入却是Markdown的^和~就有问题。
 但是考虑之后要添加斜体等样式的语法开关的话，
 可能要对富文本的粘贴单独进行解析，而不考虑Markdown语法解析开关，这样可以在不影响粘贴富文本的情况下，关闭Markdown特定语法的输入，不知道这样能不能实现？

**Comment by TCOTC** [comment]
> 在不影响粘贴富文本的情况下，关闭 Markdown 特定语法的输入

这个应该是关键

**Comment by TCOTC** [comment]
类似的问题：https://github.com/siyuan-note/siyuan/issues/10577#issuecomment-2198263009

> 复制和剪切的已经是标签了，粘贴出来的就应该是标签，而不是 `#` 包裹的文本：
>
> [视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/c2885327-0fea-4105-a7a0-1209b5fd4fa0)

**Comment by TCOTC** [comment]
我觉得得在发新版前搞定这个 issue ，或者实现对老用户也默认启用语法，否则对老用户影响太大了。

**Comment by 88250** [comment]
只能先建议老用户开启语法了，一下子搞不定。

**Comment by Achuan-2** [comment]
哇，现在有解决方案了吗

**Comment by 88250** [comment]
应该可以解决了，等后面实现完麻烦测试看看。

**Comment by Achuan-2** [comment]
> 应该可以解决了，等后面实现完麻烦测试看看。

好的，没问题，期待下

**Comment by 88250** [comment]
**foo** ** bar**

**Comment by TCOTC** [comment]
试了一下剪藏和粘贴，感觉 OK 了

**Comment by Achuan-2** [comment]
**foo**
__foo__
