### ISSUE TITLE
移动超级块中的子块会移动整个超级块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11609]
1. 从文档 B 拖拽一个块到文档 A右 ，然后再拖回来，会把其他的块也拖走，并且要重新打开页签才显示：

   [多窗口.webm](https://github.com/siyuan-note/siyuan/assets/78434827/dc7c6c2b-e7dc-4ee6-a353-ea1c4716bca3)

2. 从文档 B 拖拽一个块到文档 A右 ，文档 A左 没有更新：（不知道怎么复现，F5刷新后恢复正常）

   ![image](https://github.com/siyuan-note/siyuan/assets/78434827/97f7d491-f0d9-4f92-b68b-8b2b9d75c8bd)

**Comment by TCOTC** [comment]
其实也不是「移动整个超级块」，而是把超级块里的其他块移动了

**Comment by TCOTC** [comment]
还有问题：

1. 两个编辑器没有同步
2. 将子块移动出来之后还是有超级块

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/13e9efc1-3a5d-4562-8a2e-9146783ba9fc)

**Comment by TCOTC** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
跨窗口难度太大，想了好几天了都。。。

**Comment by TCOTC** [comment]
这个问题没完全解决之前先把 issue 打开吧，关着容易忘掉

**Comment by Vanessa219** [comment]
这个解决了同一个窗口的，跨窗口的我重新开一个记录下吧。
