### ISSUE TITLE
Add an internal kernel API `/api/av/appendAttributeViewDetachedBlocksWithValues`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11608]
创建行并插值。

https://ld246.com/article/1717014564274

示例如下：

![image](https://github.com/siyuan-note/siyuan/assets/873584/fda46c11-1495-4d08-8468-958cb3d796a8)

参数：

```json
{
  "avID": "20240118120204-kwyzf77",
  "blocksValues": [
    [
      {
        "keyID": "20240118120204-w6cggab",
        "block": {
          "content": "Test block"
        }
      },
      {
        "keyID": "20240118203822-io6ofxb",
        "text": {
          "content": "Test text"
        }
      },
      {
        "keyID": "20240531232156-ahsyx8l",
        "number": {
          "content": 1234
        }
      }
    ]
  ]
}
```

* blocksValues 是个二维数组，对应表格视图的行列
* 参数中的值可以参考源码 kernel/av/value.go 中的 Value 结构体

返回值：

```json
{
    "code": 0,
    "msg": "",
    "data": null
}
```

**Comment by lovelife88** [comment]
通过这个API可以在新建数据行批量设置属性值，能否提供API来批量修改某个数据行的属性？ @88250

**Comment by 88250** [comment]
请单独提 issue



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 4, 2024 12:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Add an internal kernel API`/api/av/appendAttributeViewDetachedBlocksWithValues` (Issue #11608)




 
通过这个API可以在新建数据行批量设置属性值，能否提供API来批量修改某个数据行的属性？ @88250
