### ISSUE TITLE
编辑条目后不重新渲染整个数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11612]
### In what scenarios do you need this feature?

目前编辑一个单元格就会导致整个数据库刷新，在编辑带有 模板/关联列 的数据库时非常卡。

p.s. 尤其是我这种在模板里查询 SQL ，每个条目要查 300ms 的情况，编辑一次要等好久

### Describe the optimal solution

只刷新编辑的那一行条目；

如果需要参与筛选或排序的话也不刷新整个数据库。

### Describe the candidate solution

~~如果编辑后条目高度没有改变，则只刷新编辑的那一个单元格~~ 好像高度是 CSS 控制的来着

如果能做到只刷新对应的单元格就更好了

### Other information

像这种在数据库里放视频的操作，就需要只刷新编辑的那一个单元格：（并且相关的模板可能需要重新计算）https://ld246.com/article/1717014564274/comment/1717212957736#comments

**Comment by 88250** [comment]
技术困难，并且工作量太大了，除非在前端再实现一套计算逻辑。
