### ISSUE TITLE
数据库导出模板后，支持在模板里指定数据库标题

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11616]
### In what scenarios do you need this feature?

做了一个月复盘的模板
![Clip_2024-06-01_17-10-31](https://github.com/siyuan-note/siyuan/assets/60436214/300ac538-0915-4a0c-98a0-595b18a0e58d)

用数据库归档每日日记，记录分数、状态、天气
导出为模板之后，希望在模板里可以指定数据库标题，然后就可以用模板语法自动生成
![Clip_2024-06-01_17-10-21](https://github.com/siyuan-note/siyuan/assets/60436214/c20daeaa-e0a6-4815-bb58-94428e1cb026)

### Describe the optimal solution

数据库导出模板后，支持在模板里指定数据库标题

**Comment by 88250** [comment]
这个做不到，数据库标题是保存在 av.json 里的，只能在 json 中调整。
