### ISSUE TITLE
多窗口编辑时，无法在新窗口正常打开文档分屏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11610]
向下分屏、向右分屏都不行；快捷键点击、文档树右键菜单都不行。

以 `Shift+Click` 向下分屏为例：

[Shift.webm](https://github.com/siyuan-note/siyuan/assets/78434827/1d27c201-b73a-4d52-aea0-0beb59ec7880)

**Comment by Vanessa219** [comment]
修改为在本窗口打开

**Comment by TCOTC** [comment]
> 修改为在本窗口打开

但是焦点在新窗口诶，不应该在新窗口打开吗？

要是在主窗口打开的话还要再拖过去新窗口，感觉很麻烦

**Comment by Vanessa219** [comment]
修改后不会在新窗口，这个是同一个文档才会有这样的问题。
