### ISSUE TITLE
支持选中搜索框中的部分文本后使用 `Ctrl+F` `Ctrl+P` ；如果此时光标在搜索框内没选中文本，则效果相当于全选搜索框文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11611]
`Ctrl+P` 变成使用查询条件了：

[搜索.webm](https://github.com/siyuan-note/siyuan/assets/78434827/9f810467-8f02-43a9-bab5-e40fc7ccacba)

**Comment by TCOTC** [comment]
再之后就是查询条件无法使用：

[搜索2.webm](https://github.com/siyuan-note/siyuan/assets/78434827/fd15103f-01f8-4e60-80ae-57f56e999948)

**Comment by TCOTC** [comment]
关联一下 #11254

**Comment by Vanessa219** [comment]
第一个是正常的，打开会使用上一次的查询条件，不需要的话可以清空。
第二个 ctrl+f 是按照路径搜索，查询条件不会覆盖选择的路径。

**Comment by TCOTC** [comment]
> 第二个 ctrl+f 是按照路径搜索，查询条件不会覆盖选择的路径。

但是路径清空之后不是就变成全局搜索了吗？

**Comment by Vanessa219** [comment]
第一点我这里重现不了

第二点需求有相关 issue 记录

**Comment by TCOTC** [comment]
第一点录屏：

清空之后再次 `Ctrl+P` 使用的还是查询条件

[搜.webm](https://github.com/siyuan-note/siyuan/assets/78434827/2394aa4e-91ca-4880-ab6b-b98ca2b9c4b9)

**Comment by Vanessa219** [comment]
用这个
<img width="128" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/bbc5f2e9-9a05-4a72-a22b-cc033f43ebfe">

**Comment by TCOTC** [comment]
所以意思是全局搜索默认会使用上次使用过的查询条件，只有用 `清空查询条件` 这个按钮才能恢复正常的全局搜索吗？

**Comment by TCOTC** [comment]
> > > 第二个 ctrl+f 是按照路径搜索，查询条件不会覆盖选择的路径。
> > 
> > 但是路径清空之后不是就变成全局搜索了吗？这个时候查询条件应该生效才对
> 
> 需求有相关 issue 记录

描述一下我的需求：`Ctrl+F` 搜索，将路径清空后，使用查询条件应该使用查询条件中的路径

这个相关的 issue 是哪一个？

**Comment by Vanessa219** [comment]
你这个场景可以使用 ctrl+p

<img width="650" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/f5939b14-91e4-4bb4-8489-336bf732f9e7">

**Comment by TCOTC** [comment]
懂了

**Comment by TCOTC** [comment]
话说能不能选中搜索框中的文本，然后按 `Ctrl+P` 切换为全局搜索？

**Comment by Vanessa219** [comment]
这个好像在另外一个 issue 里面建了 issue 了。

**Comment by 88250** [comment]
这个没有问题的话先关闭了。

**Comment by TCOTC** [comment]
@88250 我搜不到跟这个相同的打开的 issue ，而且以 `搜索` 作为关键词能搜出 1400 条已关闭的 issue 看不过来。要不还是开着这个 issue 吧

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/11637 应该是这个吧

**Comment by TCOTC** [comment]
@Vanessa219 不一样，那个 issue 是在文档内选中文本后搜索，这个 issue 的需求是：

> 支持选中搜索框中的部分文本后使用 `Ctrl+F` `Ctrl+P` ；如果此时光标在搜索框内没选中文本，则效果相当于全选搜索框文本

就是在这里选中部分文本后按快捷键能继续搜索选中的文本：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5f3e65d8-7b96-49c3-8d07-43579c684360)

按下快捷键后搜索 `34`

**Comment by Vanessa219** [comment]
看了下其他软件好像没有这样的

**Comment by TCOTC** [comment]
我也没见过。

现在认真想一想这个需求，有些情况不知道怎么处理，所以还是算了
