### ISSUE TITLE
反链提及重复问题

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1161]
### 描述问题 Describe the problem
现在的右侧提及不是实时渲染的，而且会将文档块、内容块都显示在右侧。

### 期待的结果 Expected result
建议右侧只显示光标所在块的提及，文档的提及通过单击标题页签展示

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/37007969/104882750-938b0b00-599e-11eb-87b0-125ab8604554.png)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by wrwe3888** [comment]
目前的提及部分太拥挤，能不能把提及内容的 文件路径 和 文字内容 分开啊？

**Comment by 88250** [comment]
> 目前的提及部分太拥挤，能不能把提及内容的 文件路径 和 文字内容 分开啊？

请关注 #295
