### ISSUE TITLE
回环地址不被识别并要求设置授权码

### ISSUE THREAD

**Issue by VSpade7** [siyuan-note/siyuan#11617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

不设置授权码，使用12.7.0.0.1无法访问思源

设置授权码后正常

### Expected result

能够正常识别127.0.0.1回环地址

### Screenshot or screen recording presentation

![Snipaste_2024-06-01_12-23-49](https://github.com/siyuan-note/siyuan/assets/46594083/eb9c84f0-632b-45db-abec-93a591374464)

### Version environment

```markdown
- Version: 3.0.16
- Operating System: win11 23H2
- Browser (if used):edge
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/06/01 17:06:52 runtime.go:74: kernel is booting:
    * ver [3.0.16]
    * arch [amd64]
    * os [Microsoft Windows 11 Home China]
    * pid [49720]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Spade7\Const\SiYuan]
I 2024/06/01 17:06:52 conf.go:124: loaded conf [C:\Spade7\Const\SiYuan\conf\conf.json]
I 2024/06/01 17:06:52 runtime.go:123: use network proxy [system]
I 2024/06/01 17:06:52 serve.go:116: kernel [pid=49720] http server [127.0.0.1:50916] is booting
I 2024/06/01 17:06:52 pandoc.go:132: built-in pandoc [ver=2.19.2, bin=C:\Spade7\Const\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/06/01 17:06:52 conf.go:1095: pandoc initialized, set pandoc bin to [C:\Spade7\Const\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/06/01 17:06:52 sync.go:147: sync before boot
I 2024/06/01 17:06:52 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:06:53 serve.go:129: reverse proxy server [127.0.0.1:6806] is booting
I 2024/06/01 17:06:53 repo.go:595: walk data [files=10004] cost [754.7376ms]
I 2024/06/01 17:06:53 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:07:02 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:07:03 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/refs/latest]
I 2024/06/01 17:07:03 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/indexes/e16fcc5d627d5b0a473dae82524f826815158af9]
I 2024/06/01 17:07:03 sync.go:1581: got cloud latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:07:03 repository.go:1217: boot get sync cloud files elapsed [10.51s]
I 2024/06/01 17:07:03 blocktree.go:513: read block tree [41.12 MB] to [C:\Spade7\Const\SiYuan\temp\blocktree], elapsed [0.44s]
I 2024/06/01 17:07:03 conf.go:850: database size [641.16 MB], tree/block count [640/168152]
I 2024/06/01 17:07:03 working.go:192: kernel booted
I 2024/06/01 17:07:04 box.go:77: auto stat [trees=640, blocks=168152, dataSize=553.54 MB, assetsSize=359.95 MB]
I 2024/06/01 17:07:04 disk.go:33: disk usage [total=999.13 GB, used=387.71 GB, free=611.43 GB]
I 2024/06/01 17:11:54 repository.go:1279: syncing data repo [device=fdea0e83-0071-4c3d-9cc7-66756f80579b, kernel=bl7ck7b, provider=0, mode=a/false]
I 2024/06/01 17:11:54 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:11:54 repo.go:595: walk data [files=10004] cost [365.3959ms]
I 2024/06/01 17:11:54 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:11:54 ref.go:64: updated local latest to [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:11:55 siyuan.go:112: uploaded object [siyuan/1625751521412/repo/Spade7/lock-sync]
I 2024/06/01 17:11:55 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:11:55 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/refs/latest]
I 2024/06/01 17:11:56 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/indexes/e16fcc5d627d5b0a473dae82524f826815158af9]
I 2024/06/01 17:11:56 sync.go:1581: got cloud latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:11:56 sync.go:1325: upsert file [39ee1190f95dd7e66ceb641d8dab34db52b327d9, /snippets/Savor.config.json, 2024-06-01 17:07:07] chunk [cdf58566376f11563f60e62cc4d85a646a05d02b]
I 2024/06/01 17:11:56 siyuan.go:112: uploaded object [siyuan/1625751521412/repo/Spade7/objects/39/ee1190f95dd7e66ceb641d8dab34db52b327d9]
I 2024/06/01 17:11:56 sync.go:1207: uploaded file [objects/39/ee1190f95dd7e66ceb641d8dab34db52b327d9, 1/1]
I 2024/06/01 17:11:56 sync.go:221: got local latest [c14b948a847c417d2fc408a24d717e78e15234cf] files [10004]
I 2024/06/01 17:11:56 sync.go:1454: got latest sync [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=e16fcc5d627d5b0a473dae82524f826815158af9, files=10004, size=544.5 MB, created=2024-06-01 16:23:05]
I 2024/06/01 17:11:56 sync.go:228: got latest sync [e16fcc5d627d5b0a473dae82524f826815158af9] files [10004]
I 2024/06/01 17:11:56 diff.go:49: upsert [lID=146454fbf12053e310c4f25110dcc6cbf1ce372b, lPath=/snippets/Savor.config.json, lUpdated=2024-06-01 12:23:21, rID=39ee1190f95dd7e66ceb641d8dab34db52b327d9, rPath=/snippets/Savor.config.json, rUpdated=2024-06-01 17:07:07]
I 2024/06/01 17:11:56 sync.go:239: cloud upsert [146454fbf12053e310c4f25110dcc6cbf1ce372b, /snippets/Savor.config.json, 2024-06-01 12:23:21]
I 2024/06/01 17:11:56 sync.go:245: local upsert [39ee1190f95dd7e66ceb641d8dab34db52b327d9, /snippets/Savor.config.json, 2024-06-01 17:07:07]
I 2024/06/01 17:11:56 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/refs/latest]
I 2024/06/01 17:11:56 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/indexes-v2.json]
I 2024/06/01 17:11:56 siyuan.go:112: uploaded object [siyuan/1625751521412/repo/Spade7/indexes/c14b948a847c417d2fc408a24d717e78e15234cf]
I 2024/06/01 17:11:56 sync.go:1172: uploaded index [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:11:56 siyuan.go:112: uploaded object [siyuan/1625751521412/repo/Spade7/check/indexes/221f21e0d369716df653af15a975300cc230b4dd]
I 2024/06/01 17:11:57 siyuan.go:112: uploaded object [siyuan/1625751521412/repo/Spade7/indexes-v2.json]
I 2024/06/01 17:11:57 siyuan.go:112: uploaded object [siyuan/1625751521412/repo/Spade7/refs/latest]
I 2024/06/01 17:11:57 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/refs/latest]
I 2024/06/01 17:11:57 sync.go:1382: updated latest sync [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:11:57 siyuan.go:173: removed object [siyuan/1625751521412/repo/Spade7/lock-sync]
I 2024/06/01 17:11:57 repository.go:1347: synced data repo [device=fdea0e83-0071-4c3d-9cc7-66756f80579b, kernel=bl7ck7b, provider=0, mode=a/false, ufc=4, dfc=3, ucc=0, dcc=0, ub=268.27 kB, db=476.59 kB] in [3.34s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/06/01 17:11:57 index_fix.go:50: start checking index...
I 2024/06/01 17:12:06 index_fix.go:71: finish checking index
I 2024/06/01 17:14:14 conf.go:587: exiting kernel [force=false, setCurrentWorkspace=true, execInstallPkg=0]
I 2024/06/01 17:14:14 sync.go:193: sync before exit
I 2024/06/01 17:14:14 repository.go:1279: syncing data repo [device=fdea0e83-0071-4c3d-9cc7-66756f80579b, kernel=bl7ck7b, provider=0, mode=a/false]
I 2024/06/01 17:14:14 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:15 repo.go:595: walk data [files=10004] cost [454.0307ms]
I 2024/06/01 17:14:15 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:15 siyuan.go:112: uploaded object [siyuan/1625751521412/repo/Spade7/lock-sync]
I 2024/06/01 17:14:15 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:15 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/refs/latest]
I 2024/06/01 17:14:16 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/indexes/c14b948a847c417d2fc408a24d717e78e15234cf]
I 2024/06/01 17:14:16 sync.go:1581: got cloud latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:16 siyuan.go:173: removed object [siyuan/1625751521412/repo/Spade7/lock-sync]
I 2024/06/01 17:14:16 repository.go:1347: synced data repo [device=fdea0e83-0071-4c3d-9cc7-66756f80579b, kernel=bl7ck7b, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=430.5 kB] in [1.51s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/06/01 17:14:16 database.go:1281: closed database
I 2024/06/01 17:14:16 conf.go:1014: cleared workspace temp
I 2024/06/01 17:14:16 sync.go:726: sync websocket closed
I 2024/06/01 17:14:31 working.go:146: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/06/01 17:14:31 runtime.go:74: kernel is booting:
    * ver [3.0.16]
    * arch [amd64]
    * os [Microsoft Windows 11 Home China]
    * pid [67000]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Spade7\Const\SiYuan]
I 2024/06/01 17:14:31 conf.go:124: loaded conf [C:\Spade7\Const\SiYuan\conf\conf.json]
I 2024/06/01 17:14:31 runtime.go:123: use network proxy [system]
I 2024/06/01 17:14:31 serve.go:116: kernel [pid=67000] http server [127.0.0.1:53769] is booting
I 2024/06/01 17:14:31 pandoc.go:132: built-in pandoc [ver=2.19.2, bin=C:\Spade7\Const\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/06/01 17:14:31 conf.go:1095: pandoc initialized, set pandoc bin to [C:\Spade7\Const\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/06/01 17:14:31 sync.go:147: sync before boot
I 2024/06/01 17:14:31 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:32 repo.go:595: walk data [files=10004] cost [436.4844ms]
I 2024/06/01 17:14:32 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:32 ref.go:50: got local latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:32 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/refs/latest]
I 2024/06/01 17:14:32 serve.go:129: reverse proxy server [127.0.0.1:6806] is booting
I 2024/06/01 17:14:33 siyuan.go:138: downloaded object [siyuan/1625751521412/repo/Spade7/indexes/c14b948a847c417d2fc408a24d717e78e15234cf]
I 2024/06/01 17:14:33 sync.go:1581: got cloud latest [device=fdea0e83-0071-4c3d-9cc7-66756f80579b/windows, id=c14b948a847c417d2fc408a24d717e78e15234cf, files=10004, size=544.5 MB, created=2024-06-01 17:11:54]
I 2024/06/01 17:14:33 repository.go:1217: boot get sync cloud files elapsed [1.51s]
I 2024/06/01 17:14:33 blocktree.go:513: read block tree [41.12 MB] to [C:\Spade7\Const\SiYuan\temp\blocktree], elapsed [0.06s]
I 2024/06/01 17:14:33 conf.go:850: database size [641.16 MB], tree/block count [640/168152]
I 2024/06/01 17:14:33 working.go:192: kernel booted
I 2024/06/01 17:14:33 box.go:77: auto stat [trees=640, blocks=168152, dataSize=553.54 MB, assetsSize=359.95 MB]
I 2024/06/01 17:14:33 disk.go:33: disk usage [total=999.13 GB, used=387.87 GB, free=611.27 GB]

**Comment by 88250** [comment]
我这里无法重现该问题，请检查是否是非思源内的网络配置导致（比如代理软件、路由设置等）。
