### ISSUE TITLE
数据库的单选和多选列支持设置指定选项默认颜色

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11615]
### In what scenarios do you need this feature?

目前单选和多选列，添加选项，是自动循环添加颜色
但是有的时候，其实是需要固定颜色的，尤其是添加emoji的选项，一些颜色并不和emoji适配，添加颜色反而看不清，我就会固定一个合适的颜色，但是目前默认自动循环添加颜色，我需要添加选项之后，还手动修改就有点麻烦了

### Describe the optimal solution

希望数据库的单选和多选列支持设置指定选项默认颜色
![Clip_2024-06-01_17-01-09](https://github.com/siyuan-note/siyuan/assets/60436214/e830b2dc-7732-4eb2-a48e-861333379c58)

**Comment by TCOTC** [comment]
确实有的时候不需要各种颜色

**Comment by 88250** [comment]
抱歉不考虑了，请手动调整。
