### ISSUE TITLE
Improve HTML tag input

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#11622]
`<u>`、`<sub>`…… 输入异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

> html 标签会被转换（不需要结束标签），输入后就会被转换，会影响到 输入、粘贴……，会变成乱码……
影响到的标签：`<b>、<sub>、<sup>……`
对了`<br />` 也会被转换

演示视频：
![PixPin_2024-06-02_11-54-43](https://github.com/siyuan-note/siyuan/assets/72399630/eca9cf9c-89e1-453a-9086-20f27afdeca7)
演示附加视频：
![PixPin_2024-06-02_11-56-29](https://github.com/siyuan-note/siyuan/assets/72399630/467b9992-498b-438a-82ab-e675fba563c3)

### Expected result

正常显示，感觉是个BUG，Typora那样才是正常的。

* 需要结束标签才会转换。（正常输入、粘贴）
* 在上条的基础上添加转换开关。

### Version environment

```markdown
- Version: v3.0.16、v3.0.17-dev2
- Operating System: Windows 24H2
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
#11156

**Comment by 88250** [comment]
> 需要结束标签才会转换。（正常输入、粘贴）

不需要的，只有起始标签就进行转换了，你可以试下其他的 Markdown 解析渲染器，比如 GitHub Issue 的。

```markdown
<sup>foo
```

渲染为：

<sup>foo

> 在上条的基础上添加转换开关

这个不考虑添加开关了，感谢反馈。

**Comment by shuojie819** [comment]
> > 需要结束标签才会转换。（正常输入、粘贴）
> 
> 不需要的，只有起始标签就进行转换了，你可以试下其他的 Markdown 解析渲染器，比如 GitHub Issue 的。
> 
> ```
> <sup>foo
> ```
> 
> 渲染为：
> 
> foo
> 
> > 在上条的基础上添加转换开关
> 
> 这个不考虑添加开关了，感谢反馈。

开关可以没有，但是不需要结束标签这个对我来说比较重要。（对我来说像是直接影响到了源码的编辑（源文本的编辑），这是不应该存在的，这是对源文本的入侵，我感觉……）
GitHub Issue是这样的，但是，他是源码呀……，本质有很大的区别。像是Typora这样的只有起始标签是不会被转义的。（obsidian那样的也是源码的）
又试了 Notion、Wolai，他们直接就不处理，这样也是好的（不会入侵我的输入）。

所以，我觉得最起码要有结束标签才会被转义才是正常的。

**Comment by shuojie819** [comment]
还有一个就是，我复制了一个HTML的实体字符表格：
* 在思源中 “实体名称和实体编号” 直接会被转换成对应的实体字符，但是思源是一个笔记软件呀，直接转换时HTML的特性，我记笔记的话这属于入侵吧（可能用词不当（入侵），但是这就是我的感觉）。
* 在Notion 直接就不会被转化。
* 在 Wolai 中也是不会被转换。
* 在语雀中也不会被转换，并且会提示是否转换。
* Typora、obsidian，在阅读模式、预览模式下也会被转义，但是……他能直接改源码。所以我认为这俩没有可比性（不在一个条件）

>**在实用场景中，有些需要转换，有些不需要被转化。（结构肯定是需要转换的，内容就不一定了）语雀在粘贴文本时会弹出提示，询问是否需要转换，我认为这是一个合理的解决方式。**

>**总之，直接转换在我看来对笔记软件来说是不应该存在的。**

粘贴效果
![图片](https://github.com/siyuan-note/siyuan/assets/72399630/e1702ea9-ed71-4ab1-b93e-ec4b32ce66e7)
![图片](https://github.com/siyuan-note/siyuan/assets/72399630/060e1306-21f2-4e69-849c-2c604923b3aa)
![图片](https://github.com/siyuan-note/siyuan/assets/72399630/7171ef06-056e-418c-bd13-c50560952bfe)
![图片](https://github.com/siyuan-note/siyuan/assets/72399630/2632567e-09a3-4625-8370-4d214df69f14)

**Comment by TCOTC** [comment]
- 这个问题请关注：#11557

**Comment by shuojie819** [comment]
再加一个解析问题：（乱码）
![recording](https://github.com/siyuan-note/siyuan/assets/72399630/d50b11af-8dbb-42b2-95df-7afe344bb1ee)

**Comment by TCOTC** [comment]
确实

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4b33530b-af42-4896-872d-5cf99aa3d1a6)

**Comment by shuojie819** [comment]
> 确实
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/335946201-4b33530b-af42-4896-872d-5cf99aa3d1a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTI3MzksIm5iZiI6MTcxNzM5MjQzOSwicGF0aCI6Ii83ODQzNDgyNy8zMzU5NDYyMDEtNGIzMzUzMGItYWY0Mi00ODk2LTg3MmQtNWNmOTlhYTNkMWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA1MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTFiY2ViZGMwMjk3MzZmODQxNDIyODc3Mzk5ZDQ4YTY4NjU1ZTFlMzkzMTRiN2U2MDM2YTE4MWY1MGI3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XZu71HUOZBjsRCUsknmYjl54OOLxJuyBP4RvKJA2t0s)

是的呀o(╥﹏╥)o，没有闭合标签，而且还会产生乱码。
我想问一下，我们在这个issues里发的信息 D 大会有邮件通知吗，能看到吗，需要@吗（不太懂，请教(^人^)）

**Comment by TCOTC** [comment]
能看到。过一两周没回复再 @

**Comment by shuojie819** [comment]
好的👌

**Comment by 88250** [comment]
复制包含 HTML 标签的代码异常 这个问题下个版本解决，感谢反馈。

**Comment by 88250** [comment]
输入闭合的问题也可以解决了。
