### ISSUE TITLE
提供文件树路径的搜索和定位

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1162]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

目录比较多
1. 有时候想不起具体的文档名，但是知道属于哪一个目录
2. 有时候就想看看一个目录下的文件树，但是目录太多翻很久

### 描述最优的解决方案 Describe the optimal solution

希望能通过搜索定位到目录

**Comment by 88250** [comment]
暂时不考虑了，感谢建议。
