### ISSUE TITLE
数据库的文本列会把引号展示为&quot;

### ISSUE THREAD

**Issue by BoastKnight** [siyuan-note/siyuan#11624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图：
![recording](https://github.com/siyuan-note/siyuan/assets/167420016/b4764dde-4961-491c-aca8-ba35352b9f3d)

### Expected result

no

### Version environment

```markdown
- Version:  v3.0.15
- Operating System: win11
- Browser (if used):
```

### Log file

no need

**Comment by TCOTC** [comment]
新版已经修复了，请更新
