### ISSUE TITLE
In some cases, the primary key sorting of the database panel fails

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11621]
属性面板中数据库列的顺序和本体不一致，在面板中调整后也不生效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="640" alt="20240602_043559_993_copy" src="https://github.com/siyuan-note/siyuan/assets/67137548/9422b47b-1904-4743-b959-a1ba8bd9c443">

<img width="701" alt="20240602_043555_084_copy" src="https://github.com/siyuan-note/siyuan/assets/67137548/37003daa-dffa-4ec9-bc27-63bb6a34bdcc">

### Expected result

。。

### Version environment

```markdown
- Version: 最新
- Operating System: win11
- Browser (if used):
```

### Log file

。。

**Comment by 5kyfkr** [comment]
这个就是这样的特性，假设你有三四个镜像数据库，每个镜像库都有不同的列顺序，那要怎么确定属性视图对应哪个的顺序？所以两个是分离的

**Comment by TCOTC** [comment]
这个是在 #11428 中修改的，属性界面的顺序与其他视图独立

**Comment by Jiangshuon** [comment]
主要问题是后半句，面板中调整顺序后无法生效

**Comment by TCOTC** [comment]
@88250 属性面板的数据库字段顺序无法调整：

[顺序.webm](https://github.com/siyuan-note/siyuan/assets/78434827/ffeed3e0-5bc6-4318-8082-4aa057988358)

**Comment by 5kyfkr** [comment]
https://github.com/siyuan-note/siyuan/assets/63196026/c7c95df9-80cb-41bc-89cd-b3395b7d11e5

我这边3.0.16试了能记住位置，记得以前修好过这个问题

**Comment by TCOTC** [comment]
@88250 这个文档可以复现问题：

[问题数据库2.sy.zip](https://github.com/user-attachments/files/15524685/2.sy.zip)

[属性.webm](https://github.com/siyuan-note/siyuan/assets/78434827/c39a636a-89ae-4a2b-94a7-6fa067b43df9)
