### ISSUE TITLE
Improve the pasting of selected text in PDF rectangular annotation

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11629]
改进 PDF 矩形标注选中文字粘贴

复制 PDF 标注后，支持在文档中选中文本直接 Ctrl+V 粘贴为引用（以选中的文本作为锚文本）（不需要粘贴图片）

https://ld246.com/article/1717308839787/comment/1717332364067#comments

**Comment by Vanessa219** [comment]
指的是这个么？还是其他的？

https://github.com/siyuan-note/siyuan/assets/970828/e468743c-6a64-4454-a02d-b4367c663af7

**Comment by TCOTC** [comment]
这样标注可以，但矩形标注是不行的

**Comment by TCOTC** [comment]
- 这个 issue 暂时先放着，等待 #11635

**Comment by Vanessa219** [comment]
这个和这个issue 没有关系吧

**Comment by TCOTC** [comment]
@zxhd863943427 说有关系

**Comment by Vanessa219** [comment]
@zxhd863943427 可别把剪切板中的数据结构格式改了呀，这个粘贴只是和复制时存在剪切板中的内容有关吧。

**Comment by zxhd863943427** [comment]
确实有关系了，支持多选标注进行复制……

能一次性复制多个标注并粘贴。

**Comment by Vanessa219** [comment]
多个只是批量问题，格式保持一致即可。

**Comment by TCOTC** [comment]
@Vanessa219 那个 PR 关闭了，这个需求可以做了

**Comment by Vanessa219** [comment]
现在好像没这个问题了

**Comment by TCOTC** [comment]
@Vanessa219 我这还是不行，会把选中的文字覆盖掉并且插入图片：

[视频.webm](https://github.com/user-attachments/assets/5d4641b4-8aae-445d-8e2e-adb8de6578c5)

**Comment by TCOTC** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
@88250 麻烦看一下是不是 WindowsWindows 下的问题？
https://github.com/user-attachments/assets/8a8bffc6-0a24-4e65-a90b-7e176a3c7c1a

**Comment by 88250** [comment]
@Vanessa219 Windows 上粘贴会带图片
