### ISSUE TITLE
数据库添加模板字段后内核退出

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11636]
**关联：https://ld246.com/article/1717415333925**

文档：[RSS-r6ETEVz.sy.zip](https://github.com/user-attachments/files/15533308/RSS-r6ETEVz.sy.zip)

在第二个数据库后增加一列模板，等一下内核就会退出。

重启后无法显示数据库：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dd859883-490e-455b-abea-13abbd1dc653)

**Comment by 88250** [comment]
已在链滴帖子中回复，是因为调用 API 插入数据的 ID 格式不正确。
