### ISSUE TITLE
新建子文档后及时刷新父文档图标

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11633]
### In what scenarios do you need this feature?

新建子文档：通过文档树添加、通过 `/` 菜单添加、通过 `F3` 添加

目前需要折叠上级文档再展开才会刷新父文档图标：

[图标.webm](https://github.com/siyuan-note/siyuan/assets/78434827/28897e16-31eb-4d9a-95d9-03e5f0398f5f)

### Describe the optimal solution

。

**Comment by 88250** [comment]
这个改进就不拉进版本了。
