### ISSUE TITLE
编辑文档名后支持撤销

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11632]
### 选中文本 `F2` 修改文档标题后无法 `Ctrl+Z` 撤销

[撤回.webm](https://github.com/siyuan-note/siyuan/assets/78434827/c98d14c3-8281-4992-b986-828faa3d9f82)

**Comment by 88250** [comment]
对话框不支持撤销。

**Comment by TCOTC** [comment]
没有对话框啊

**Comment by 88250** [comment]
不好意思，没仔细看描述……

**Comment by Vanessa219** [comment]
文档名重命名都不支持撤销

**Comment by TCOTC** [comment]
原来不用 `F2` ，直接编辑文档名也是不能撤销的

**Comment by TCOTC** [comment]
刚刚发现，如果光标一直在标题上的话是可以撤销的，但只要编辑一下正文就没法撤销了

**Comment by Vanessa219** [comment]
嗯，文档标题上的撤销用的是系统的。其余地方的没有写

**Comment by 88250** [comment]
这个不考虑改变了，就目前这样吧。

**Comment by TCOTC** [comment]
暂时解决不了的话还是先开着吧。我试了一下 Notion 和 FlowUs 都是支持撤销的，思源不支持的话确实有瑕疵

**Comment by 88250** [comment]
没有办法，实现不一样，撤销一直是个问题。
