### ISSUE TITLE
接入微信支付

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11639]
### In what scenarios do you need this feature?

要推广的话，接入微信支付后，获客应该会更容易转化。

学生应该是主力人群，但学生基本都是用微信支付的，很少用支付宝。比如我支付宝里一毛零钱都没有，用到的时候都是直接从银行卡里扣。

https://ld246.com/article/1706276949720

![0467fa2d4d0f2a5629bf79ad0277bc23](https://github.com/siyuan-note/siyuan/assets/78434827/d6875132-0daa-4bf6-885e-029e79c1e486)

### Describe the optimal solution

。

**Comment by 88250** [comment]
感谢提议，这个不考虑了。

**Comment by TCOTC** [comment]
原因是什么？
