### ISSUE TITLE
批量导出为 PDF 文件

### ISSUE THREAD

**Issue by BLACKT-T** [siyuan-note/siyuan#1164]
## 使用场景
经常需要分享pdf格式文件的场景，由于笔记文件较多，导出pdf需要一个一个文件导出，而现在批量导出只有md格式，局限性比较强。
所以需要能够批量导出PDF等其他格式文件。

**Comment by 88250** [comment]
感谢建议，稍微延后一点考虑，谢谢。

**Comment by 88250** [comment]
批量导出 PDF 不考虑了，主要原因是非常耗时，感谢提议。
