### ISSUE TITLE
Improve untitled database placeholder

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11641]
### In what scenarios do you need this feature?

像 #11582 一样把数据库的标题也改成 `color: var(--b3-theme-on-surface-light);`

![1717489597557](https://github.com/siyuan-note/siyuan/assets/78434827/f0cefb33-85ab-40c8-9777-0ee87664833c)

### Describe the optimal solution

。

**Comment by TCOTC** [comment]
@88250 这个不用拉进版本

**Comment by 88250** [comment]
ok
