### ISSUE TITLE
Improve cursor moving in the code block

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#11647]
代码块内移动光标出错

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

添加一个代码块，加入三行内容
```
aaa
bbb
ccc
```
光标放在aaa后面，按键盘上的向下，光标会到ccc后面
正确的操作应该是只向下一行

### Expected result

按向下的时候，应该只向下移动一行

### Version environment

```markdown
- Version: 3.0.17
- Operating System: windows 11
- Browser (if used):
```

### Log file

不涉及

**Comment by Vanessa219** [comment]
我这里无法重现，是有什么特殊操作或设置么？

https://github.com/siyuan-note/siyuan/assets/970828/f5d312d0-551f-4372-8a25-b9f222de6d8b

**Comment by heheda123123** [comment]
https://github.com/siyuan-note/siyuan/assets/97490782/37fd472d-8cdb-49b5-acc3-6e7b42546444

没有特殊设置，我siyuan一直用的默认配置，就只是开启了行号，加了插入代码块的快捷键
你上面也是在windows测试的嘛？

**Comment by pisceswb** [comment]
建议也取消在正常文本内容的最后一段中按向下箭头时，会直接定位到段落最后的设置，这个设置会对正常使用造成困扰。

**Comment by heheda123123** [comment]
> 建议也取消在正常文本内容的最后一段中按向下箭头时，会直接定位到段落最后的设置，这个设置会对正常使用造成困扰。

还真是有这个问题，不过我自己因为基本不用`shift-enter`，所以还没发现呢

**Comment by pisceswb** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
这个是有用户提的需求，但是我找不到出处了 😓

**Comment by 88250** [comment]
@Vanessa219 我们还需加强一下需求管理。

**Comment by pisceswb** [comment]
> @Vanessa219 我们还需加强一下需求管理。

希望思源笔记不要弄的太臃肿了，相信大部分人还是喜欢简洁美观高效的思源笔记。
个人觉得，大部分人的心理是，自己需要的功能要有，自己不用的别占位置和资源。简洁够用的刚刚好是最完美的状态。
所以，能用插件实现的功能，建议统统用插件实现，需要的用户自己启用。比如我就几乎从来没用到数据库、闪卡、导出、PDF等功能，如果把他们做成个插件的话，我就不会启用他们，这样我就会觉得我的思源笔记很简洁，不容易出错误（尽管知道这可能是心理作用，实际影响不大😂）。
可以弄几个官方插件以满足少量用户的特殊需求，甚至复杂的插件可以有偿使用（如果以官方名义争议较大的话，可以弄个小号😁）

还有，思源笔记的推广可以花钱做一做或给优惠政策让老用户拉一下新人，这么好的笔记，感觉应该推广开来让更多人受益。

**Comment by 88250** [comment]
嗯，功能设计上我们会尽量做权衡的，目前来看，商业推广目前也正在推进中，谢谢。



---Original---
From: ***@***.***&gt;
Date: Sun, Jun 9, 2024 17:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve cursor moving in the code block(Issue #11647)




  
@Vanessa219 我们还需加强一下需求管理。
  
希望思源笔记不要弄的太臃肿了，相信大部分人还是喜欢简洁美观高效的思源笔记。
 个人觉得，大部分人的心理是，自己需要的功能要有，自己不用的别占位置和资源。简洁够用的刚刚好是最完美的状态。
 所以，能用插件实现的功能，建议统统用插件实现，需要的用户自己启用。比如我就几乎从来没用到数据库、闪卡、导出、PDF等功能，如果把他们做成个插件的话，我就不会启用他们，这样我就会觉得我的思源笔记很简洁，不容易出错误（尽管知道这可能是心理作用，实际影响不大😂）。
 可以弄几个官方插件以满足少量用户的特殊需求，甚至复杂的插件可以有偿使用（如果以官方名义争议较大的话，可以弄个小号😁）
 
还有，思源笔记的推广可以花钱做一做或给优惠政策让老用户拉一下新人，这么好的笔记，感觉应该推广开来让更多人受益。
