### ISSUE TITLE
Improve Wikipedia clipping

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11640]
* https://ld246.com/article/1717475967558
* https://ld246.com/article/1717488465709

改进点：

* 正文换行
* 忽略引用中的注释
* dl.dd 定义的公式从行级公式改为块级公式
* class="texhtml" 的元素识别为公式
* 图片使用原图
* a.img 去掉 a

**Comment by TCOTC** [comment]
> a.img 去掉 a

这个是直接去掉了还是把链接放到图片的提示或标题里？

**Comment by 88250** [comment]
去掉跟在图片后面的超链接

**Comment by 88250** [comment]
还需要改进 https://ld246.com/article/1717687435797

**Comment by 88250** [comment]
继续改进 https://github.com/siyuan-note/siyuan/issues/11717

**Comment by TCOTC** [comment]
公式还是有点不一样：

https://en.wikipedia.org/wiki/Lebesgue_integration

![image](https://github.com/siyuan-note/siyuan/assets/78434827/17338f0c-de2c-4d85-aca5-54f685f91001)

思源：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/2c04d94b-0cc6-46c3-acaa-495bec8c4358)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7264d219-db30-401b-8db5-659f9e3a55e7)

**Comment by TCOTC** [comment]
@88250

**Comment by 88250** [comment]
感谢反馈，稍后改进。
