### ISSUE TITLE
Windoar arm64 and Linux arm64 no longer packing pandoc

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11649]
Windows arm64 上没有 pandoc 可执行文件发布，所以无法包含在安装包里；Linux arm64 虽然有，但是也不考虑包含了，需要的话请自行下载 pandoc 并在 设置 - 导出 中指定 pandoc 可执行文件路径。

**Comment by TCOTC** [comment]
@88250 标题里的 `Windoar` 是什么鬼，ws 是咋打错成 ar 的？

**Comment by 88250** [comment]
感谢指出。
