### ISSUE TITLE
Improve `Add to Database` search

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11644]
希望数据库搜索支持空格分隔的多关键词搜索

### In what scenarios do you need this feature?

后续数据库多了，光靠一个关键词定位有点难

![image](https://github.com/siyuan-note/siyuan/assets/67137548/194ccdad-8ae3-43bd-bd47-e903b8edfcae)

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
并且关键词之间应该是 AND 关系

**Comment by Jiangshuon** [comment]
是的，肯定是and

**Comment by TCOTC** [comment]
并且优先级应该是 命名 > 名称 > 别名

**Comment by 88250** [comment]
只能根据数据库名搜索，无法搜索数据库块属性。
