### ISSUE TITLE
数据库视图添加主键筛选条件后，添加行主键默认为筛选内容

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11657]
### In what scenarios do you need this feature?

目前视图如果对于单选列添加筛选条件`等于`后，添加新行，是会自动填充内容的的
但是添加了主键的筛选条件，并不会自动填充内容

![Clip_2024-06-07_09-21-15](https://github.com/siyuan-note/siyuan/assets/60436214/e1f33b6b-8cf7-4dba-8d79-223fa4037eee)

### Describe the optimal solution

数据库视图添加主键筛选条件（等于、包含、开头为、末尾为）后，添加行自动填充筛选内容

之前还提了一个设置主键模板的issue：https://github.com/siyuan-note/siyuan/issues/11506

所以对于筛选自动填充内容和主键模板还需要考虑优先级
优先级应该是主键模板 > 筛选自动填充内容，如果没有设置主键模板，则添加主键筛选条件后，添加新行，主键默认为筛选内容，如果设置了主键模板，则为模板生成内容。因为既然要对主键进行筛选，主键的生成模板也应该是符合筛选条件的。比如我现在用一个数据库管理全年的dailynote，对主键（内容为日期）进行筛选，依次建立月份视图，就希望直接在月份视图里，可以直接新建当月日记。

**Comment by 88250** [comment]
主键涉及到绑定块，规则无法统一，所以无法在筛选的时候自动填充。

**Comment by Achuan-2** [comment]
指的是在一个视图筛选主键后，要添加新行，由于默认为空，导致视图里这个新行不显示。
比如我筛选条件设置主键包含为`2024-06`, 我只需要添加新行的时候，内容填充为`2024-06`就可以了，之后再更改主键为当日日期`2024-06-16`

**Comment by 88250** [comment]
启用筛选的情况下也可以拖入块绑定的，这里如果自动填入值就会有冲突。

**Comment by Achuan-2** [comment]
我的想法是只对`新建条目`这个按钮自动填充值

**Comment by 88250** [comment]
使用下拉填充吧：

![image](https://github.com/siyuan-note/siyuan/assets/873584/cf818d5f-2141-4dc1-a82a-fe188a07b757)

**Comment by Achuan-2** [comment]
因为这里的问题在于筛选主键后新建行，不在视图显示。下拉填充并不会自动新建行。
不过如果之后支持设置新建行设置主键模板，这个提议的需求我也不是很需要了

**Comment by 88250** [comment]
好的，那就后面我们看下 https://github.com/siyuan-note/siyuan/issues/11506 能否做吧。
