### ISSUE TITLE
Missing features in the database and more

### ISSUE THREAD

**Issue by weidejunde** [siyuan-note/siyuan#11658]
### In what scenarios do you need this feature?

1. can embed (link) another page into a text field in a database table (like write in a page or conceptual).
2. show database properties for the page instead of hiding in a database node (like conceptual) and can export to pdf.
3. can arrange different custom positions of database fields instead of sorting in a list style (like access design function)
4. support multiple views like kanban, library...
5. can export everything on the working screen (like word, excel...)
6. support adding custom fonts for each paragraph of text instead of all pages (like word)
7. support vertical writing (from top to bottom, from right to left) for languages ​​like Chinese, Korean, Japanese and sometimes Vietnamese Nom characters)
---
those are all the features that I find this application is lacking.

### Describe the optimal solution

These features are available on word, notion...

**Comment by 88250** [comment]
Hello, we have our plan and it is not a complete copy of Notion, thank you.

**Comment by weidejunde** [comment]
i know it is hard to program an app like this, but i have seen this app has been developed very actively in the last few years (it has more functions than obsidian and only less than notion in the features i listed above) you guys can definitely make it better.
currently i only find the database function incomplete, the rest is acceptable.
thank you for creating this app.
