### ISSUE TITLE
移动端《添加到数据库》功能无法使用

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

块菜单中点击无反应，文档树菜单中操作没问题

### Expected result

。。

### Version environment

```markdown
- Version:最新 
- Operating System: 
- Browser (if used):
```

### Log file

。。

**Comment by 88250** [comment]
大概是的



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 19, 2024 04:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] `Add to Database` is not available on mobile(Issue #11651)




 
@88250 D大，下个月才会更新吗？这个bug很影响使用

**Comment by Jiangshuon** [comment]
移动端可以编译dev版吗？



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 19, 2024 07:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] `Add to Database` is not available on mobile(Issue #11651)




 大概是的 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Wed, Jun 19, 2024 04:18 AM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [siyuan-note/siyuan] `Add to Database` is not available on mobile(Issue #11651) 
 
 
 
 
   
 @88250 D大，下个月才会更新吗？这个bug很影响使用

**Comment by 88250** [comment]
只能手动编译。

**Comment by Jiangshuon** [comment]
D大这个得想办法解决下吧，没有dev版都无法测试，一旦出现非常影响使用的bug只能卸载重装。麻烦死了。
或者卸载后不删除文件



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 19, 2024 11:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] `Add to Database` is not available on mobile(Issue #11651)




 
只能手动编译。

**Comment by Jiangshuon** [comment]
手机可以同时安装dev版和正式版就好了

**Comment by 88250** [comment]
得自己编译，可以同时安装的。

**Comment by Jiangshuon** [comment]
> 得自己编译，可以同时安装的。

d大，不编译安卓dev版是因为安卓dev版编译无法自动化，因此非常麻烦、耗时，所以不编译吗？

安卓正式版也是手动编译的吗？

手动编译门槛高吗，有教程不

**Comment by 88250** [comment]
请参考项目 README



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 5, 2024 18:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] `Add to Database` is not available on mobile(Issue #11651)




  
得自己编译，可以同时安装的。
  
d大，不编译安卓dev版是因为安卓dev版编译无法自动化，因此非常麻烦、耗时，所以不编译吗？
 
安卓正式版也是手动编译的吗？
 
手动编译门槛高吗，有教程不
