### ISSUE TITLE
更新版本v3.0.17 底部栏变高了

### ISSUE THREAD

**Issue by jiaotashidiyangwangxingkong** [siyuan-note/siyuan#11655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

底部工具栏变高，上一个版本好像没有这么高的

### Expected result

底部栏不需要那么高

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/10350729/05900317-5aa5-492f-92fd-b334dcc42f40)

### Version environment

```markdown
- Version:  v3.0.17
- Operating System: windows 10 
- Browser (if used): no
```

### Log file

无

### More information

略

**Comment by 88250** [comment]
这个默认主题没有调整过，请使用默认主题测试。

**Comment by jiaotashidiyangwangxingkong** [comment]
> 88250
使用了默认主题还是一样高
![image](https://github.com/siyuan-note/siyuan/assets/10350729/1cbe191c-a387-4bd4-ae93-999c69745a92)
