### ISSUE TITLE
Supports block hyperlink jump in widgets on Android

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11652]
https://ld246.com/article/1717595781538

**Comment by lovelife88** [comment]
请问这个问题计划什么时候修复？开发的这个“最近更新的文档”挂件目前无法在手机上跳转，https://ld246.com/article/1717735136831

**Comment by 88250** [comment]
你好，我使用你的挂件 https://github.com/lovelife88/siyuan-widget-lastedupdated 最新版测试了一下，目前已经可以跳转，所以是不是没有问题了？

**Comment by 88250** [comment]
暂时先关闭，有进一步信息欢迎随时跟帖，谢谢。
