### ISSUE TITLE
Failed to get kernel serve port

### ISSUE THREAD

**Issue by sammy-hao** [siyuan-note/siyuan#11659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

本台机器首次安装，首次启动即失败

### Expected result

正常使用

### Screenshot or screen recording presentation

![无标题](https://github.com/siyuan-note/siyuan/assets/52777095/ad8399e6-4e60-4550-a734-de6717801b4f)

### Version environment

```markdown
- Version: 3.0.17
- Operating System: win10
- Browser (if used):
```

### Log file

[app.log](https://github.com/user-attachments/files/15718859/app.log)
[siyuan.log](https://github.com/user-attachments/files/15718945/siyuan.log)

**Comment by sammy-hao** [comment]
补充说明：防火墙和网络均设置为通过
![无标题](https://github.com/siyuan-note/siyuan/assets/52777095/eeb338f8-cd7b-4145-bfce-1373b07403f5)

**Comment by 88250** [comment]
从最后一次启动的日志上看 55634 端口的内核已经启动正常，但是界面程序连接时被拒绝了，建议还是排查一下防火墙相关设置，另外，如果有使用 VPN 或者代理，放行 127.0.0.1 

issue 我们先关闭了，如果还有其他补充欢迎随时反馈，谢谢。
