### ISSUE TITLE
细节改进：高亮文档树已打开文档

### ISSUE THREAD

**Issue by zillaos** [siyuan-note/siyuan#11663]
### In what scenarios do you need this feature?

希望在打开文档时，可以在文档树高亮文档名称
![image](https://github.com/siyuan-note/siyuan/assets/57604382/0db55317-8f2c-4c47-84e5-6e5783fafde0)
如上图，当英语六级文档打开时左侧文档树应高亮打开的文档

### Describe the optimal solution

obsdian 有类似的功能，如下图未命名文档打开时，左侧Vault高亮了未命名文档名称
![image](https://github.com/siyuan-note/siyuan/assets/57604382/30170ac4-032b-4a08-a3c3-87015df90ea9)

**Comment by 88250** [comment]
可以使用 定位打开的文档

![image](https://github.com/siyuan-note/siyuan/assets/873584/e1b0758f-f9fb-481b-a0b9-f18f65451159)

或者 设置 - 文档树 - 始终定位打开的文档
