### ISSUE TITLE
统一知识展示方式，隔离知识层与物理存储层的联系，真正做到“在思源笔记中，唯一重要的核心概念是内容块"

### ISSUE THREAD

**Issue by liubo-hebau** [siyuan-note/siyuan#1166]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
进行长期的学习与知识总结，知识整理，特别是需要知识拆分与合并时，不得不兼顾知识的内在关系结构与物理结构。 现有的目录文件结构本身就在对知识进行层次化归纳，但其功能过于单一。如： 一个主题A 含有 3个子主题 b, c, d。在思源里的方案主要有:
1. 建立文件夹（A），建立A中的文件（b, c, d），该方案的问题有
   a) 当合并 b c d 3个子主题时，不得不再新建一个文件A， 里面放入b,c,d3个主题，然后再删除b,c,d3个文件
   b) 此时已建的文件夹（A）就显得非常冗余，不知道它扮演个什么角色，最终也只能删除
   c)  知识组织不得不伴随大量物理文件的操作，这是没有必要的
   d) 在拆分知识点时，同样面临类似的问题

2. 在某一文件夹中，建立文件（A），再建立3个文件（b c d ）,该方案的问题有
   a)   A是b,c,d 的父主题，但只能被迫与b,c,d同级，与知识间的内在逻辑冲突
   b)   合并主题是会遇到与第一种方案类似的问题，知识组织不得不伴随文件操作，而已有的文件夹结构无法承担知识调整的重任。

思源已提供的，拖拽主题成文件，拖拽文件成主题并不能根本上解决以上的问题，该类操作仍然是文件的物理存储结构与知识组织绑定，二两者目前有无法兼容，而且还有存在冲突与矛盾。

### 描述最优的解决方案 Describe the optimal solution
1. 隔离物理存储文件层与知识层的关系，使得用户只关注知识组织，无需关注文件的物理结构。
2. 一个内容块就是一个主题，主题还有子主题，从而构建自然的层次结构。
3. 不同主题间可以自由合并、拆分、双向引用。

### 描述候选解决方案 Describe the candidate solution
1. 文件夹也作为内容块出现，可被编辑内容，可被双链
2. 文件夹自动完成对下级内容的双链

**Comment by 88250** [comment]
你好，我想这是使用方式决定的，产品层面并不约束使用习惯。总的来说有两种使用习惯：

1. 不分文件夹，所有文档块都放在一个物理文件夹下
2. 通过文件夹分类组织文档块

要完成第一种用法现在思源还欠缺一个重要操作，就是跨文档块拖拽移动内容块 #1025 这个我们后面会进行支持。只要完成这一点，逻辑上用户完全可以不关心物理文件存放路径，只用关系内容块的组织方式。这应该就是你提到的最优解决方案，后面肯定是可以支持的。

在实现跨文档移动内容块后，思源还存在一种情况没有实现，暂时称作“容器块无限层级缩放”，即逻辑上的容器块（比如标题块）或者真实的容器块（比如列表项块）可以“点击进入”，这操作类似大纲式笔记对于每个条目都可以进入那样，进入或者返回相当于将内容缩放到某个层级上。这个特性我们还需要时间考虑，交互设计和实现上都面临一些挑战。

感谢讨论！

**Comment by deerainw** [comment]
> 在实现跨文档移动内容块后，思源还存在一种情况没有实现（或者说是想做一些突破），我将它暂时称作“容器块无限层级缩放”，即逻辑上的容器块（比如标题块）或者真实的容器块（比如列表项块）可以“点击进入”，这操作类似大纲式笔记对于每个条目都可以进入那样，进入或者返回相当于将内容缩放到某个层级上。这个特性我们还需要时间考虑，交互设计和实现上都面临一些挑战。

我觉得这种敢想敢做的态度是真的牛🐮，对基于本地纯文本文件的软件来说，很多没人愿意去做的重要特性都是在思源上率先实现的，没道理不火起来

PS1：缩放的时候，顶部可能需要有个面包屑导航

PS2：写了篇思源安利文章，目前半成品草稿已经有七千多字了，打算等一个高度稳定可用版本发布的时候在知乎和语雀公开发一发

![image](https://user-images.githubusercontent.com/32661922/104912534-58e99880-59c7-11eb-96fe-4ae9ef05724a.png)

**Comment by liubo-hebau** [comment]
谢谢回复。自由、简单的组织知识；灵活、规范的展示知识大概是每个笔记爱好者的核心诉求吧。其他与知识组织无关的操作最好都屏蔽掉。不管是原生，还是插件，提供统一的“内容块视图“是极好的，关心文档的用户，提供“文档视图“”，至少可以方便导出，导入等操作。期待思源的逐渐进化。1.0 也只是开始！

**Comment by walklty** [comment]
> 一个内容块就是一个主题，主题还有子主题，从而构建自然的层次结构。
> 不同主题间可以自由合并、拆分、双向引用。

听起来像是大纲笔记的层级感觉

**Comment by MistRay** [comment]
>容器块无限层级缩放

比较期待,现在文件夹不被作为容器块看待,有时候我需要引用一个名词,比如`MySQL`,但`MySQL`是个文件夹,我没办法引用文件夹,所以我只能自己手动在文件夹下创建一个大纲文档,然后再引用这个大纲文档,有些麻烦.(也可能是我的用法有问题)

**Comment by deerainw** [comment]
@MistRay 
可以了解一下知识管理领域的 moc (map of contents) 这个概念，基本上能解决你的这种困惑。

**Comment by 88250** [comment]
感谢各位的帮助，我们后续会在 https://github.com/siyuan-note/siyuan/issues/1231 中支持容器块缩放编辑。
