### ISSUE TITLE
希望数据库浮窗也支持页签打开

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11665]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/67137548/d40bd60b-c839-4713-8730-f4fe52faea16)

<img width="286" alt="20240609_015323_817_copy" src="https://github.com/siyuan-note/siyuan/assets/67137548/40bd969b-724a-410e-a0e4-e077df0ca8a0">

### Describe the optimal solution

。。

**Comment by Jiangshuon** [comment]
哦哦，我知道了，其实是支持的，但必须保证只有一个镜像，如果有多个镜像在不同文档，就不会显示这个按钮了

**Comment by 88250** [comment]
是的，否则不知道具体打开哪个文档，我们关闭 issue 了，谢谢。

**Comment by Jiangshuon** [comment]
> @Jiangshuon 在这个菜单里也有「在新页签中打开」：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/338472017-d9b24d3f-593f-47dd-8c7c-9c62a92f968b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODk2NTEsIm5iZiI6MTcxODA4OTM1MSwicGF0aCI6Ii83ODQzNDgyNy8zMzg0NzIwMTctZDliMjRkM2YtNTkzZi00N2RkLThjN2MtOWM2MmE5MmY5NjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYTYyMzRmYTJhY2NlYmNmMWEyMzZhZjE5ZThjZDllMTMxMTRiZTIwZThiOWYxMjBhMDY1ODA1OTE3MTliZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P69LogTA1vywSUaZzfIx46u3eCwSfi5hAgi2CwyJ44c)
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/338472007-f62eaac5-c021-407d-a231-d98326158c34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODk2NTEsIm5iZiI6MTcxODA4OTM1MSwicGF0aCI6Ii83ODQzNDgyNy8zMzg0NzIwMDctZjYyZWFhYzUtYzAyMS00MDdkLWEyMzEtZDk4MzI2MTU4YzM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3MDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMzQ1MTE4MjFiZGYzMGYwYzFkOTUyYTVlYjdkNGJiNjljYmFhMDA4YTE0OWI0ZTZjOWFhMWI0ZjllYzlhODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vRQGONWx8vwA9Bm1h8Gx448S3BNDdgll91SkrDZzdr4)

666，thanks！！
