### ISSUE TITLE
SiYuan剪藏插件在Arc浏览器中失效

### ISSUE THREAD

**Issue by Linnnkkk** [siyuan-note/siyuan#11660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

SiYuan剪藏插件在chrome可以正常使用，但是在Arc浏览器中失效，无法使用

### Expected result

无法识别选择笔记本

### Version environment

```markdown
- Version: 1.2.6
- Operating System: windows 11
- Browser (if used):Arc browser
```

### Log file

N/A

**Comment by 88250** [comment]
请使用基于 [Chromium](https://www.chromium.org/) 内核的浏览器，另外 Chrome 版本不能低于 91，我先关闭了，如果还有补充信息欢迎提供，谢谢。

**Comment by Linnnkkk** [comment]
> 请使用基于 [Chromium](https://www.chromium.org/) 内核的浏览器，另外 Chrome 版本不能低于 91，我先关闭了，如果还有补充信息欢迎提供，谢谢。

Arc浏览器内核是Chromium，内核版本如下图
![image](https://github.com/siyuan-note/siyuan/assets/106414095/2bc5f0ee-6232-448e-9cff-3663afaf807c)

**Comment by 88250** [comment]
请看下 console 是否有相关报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月7日(周五) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] SiYuan剪藏插件在Arc浏览器中失效 (Issue #11660)




  
请使用基于 Chromium 内核的浏览器，另外 Chrome 版本不能低于 91，我先关闭了，如果还有补充信息欢迎提供，谢谢。
  
Arc浏览器内核是Chromium，内核版本如下图
 image.png (view on web)

**Comment by Linnnkkk** [comment]
> 请看下 console 是否有相关报错
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月7日(周五) 下午5:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] SiYuan剪藏插件在Arc浏览器中失效 (Issue #11660) 请使用基于 Chromium 内核的浏览器，另外 Chrome 版本不能低于 91，我先关闭了，如果还有补充信息欢迎提供，谢谢。 Arc浏览器内核是Chromium，内核版本如下图 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

![image](https://github.com/siyuan-note/siyuan/assets/106414095/c8291815-2aeb-42c2-b906-551f8da087c2)
这是报错
