### ISSUE TITLE
数据库添加‘批量选择’和‘delete按键’

### ISSUE THREAD

**Issue by tod-zhang** [siyuan-note/siyuan#11668]
### In what scenarios do you need this feature?

数据库添加‘批量选择’和‘delete按键’

### Describe the optimal solution

数据库添加‘批量选择’和‘delete按键’

**Comment by TCOTC** [comment]
批量选择要一个个点确实麻烦，不知道有没有更方便的交互

**Comment by 88250** [comment]
这个恐怕没有更好的交互方案了，选择以后可以通过菜单删除。

**Comment by TCOTC** [comment]
@88250 按住一个，然后鼠标往上往下拖动，这种交互能做到吗？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bed4a0ac-a2c0-4b90-b71c-ca717c05f8ec)

**Comment by Achuan-2** [comment]
> @88250 按住一个，然后鼠标往上往下拖动，这种交互能实现吗？
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/340006884-bed4a0ac-a2c0-4b90-b71c-ca717c05f8ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MDc3MjcsIm5iZiI6MTcxODUwNzQyNywicGF0aCI6Ii83ODQzNDgyNy8zNDAwMDY4ODQtYmVkNGEwYWMtYTJjMC00YjkwLWI3MWMtY2E3MTdjMDVmOGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDAzMTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YzViZTlkZWI4YTU1MjY2MDJlYjFiOTNhNzg5N2VlODIzNzA5YWYyNWQzMjQ1NGY2YzJjN2ZhMjc5ODg3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6npX-9aPVwH-aNfvWzZyubj6B-v1rBkyO2bsSb2pYE)

不如shift区域选择，按住shift点击第一个和最后一个，批量选择范围内的

**Comment by 88250** [comment]
先不加了，等后面参考下 Notion 等软件的实现（如果有的话）。
