### ISSUE TITLE
能否添加一键转换为本地图片的功能

### ISSUE THREAD

**Issue by noenif** [siyuan-note/siyuan#11662]
### In what scenarios do you need this feature?

因为很多cdn图片,可能会过期,我想转到自己的gitee库或者本地来.

### Describe the optimal solution

我现在找不到一个将网络图片转换为本地的按钮.我是通过导入按钮导入的.

**Comment by mozhux** [comment]
文档里菜单就有。一篇篇来。如果很多篇，应该直接替换链接去。

**Comment by 88250** [comment]
编辑器右边更多菜单

![image](https://github.com/siyuan-note/siyuan/assets/873584/2bb64ae6-7b62-4abc-a4b9-f0b4e2842508)

仅支持单篇转换。

**Comment by noenif** [comment]
> 编辑器右边更多菜单
> 
> ![image](https://private-user-images.githubusercontent.com/873584/337861375-2bb64ae6-7b62-4abc-a4b9-f0b4e2842508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NzgzNDEsIm5iZiI6MTcxNzk3ODA0MSwicGF0aCI6Ii84NzM1ODQvMzM3ODYxMzc1LTJiYjY0YWU2LTdiNjItNGFiYy1hNGI5LWYwYjRlMjg0MjUwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwMDA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2NlMzM5Zjg0NGYyNzNkZTljODA0MzY4ZTYwNjQ3ODliYzFmZjUwNjNlNWEzOGU4NzBhYThjYTQ0NTAzZDYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9nAE3L1unad0zekqaDCQUw5Dgw3BvB9EU_qfy0teUg8)
> 
> 仅支持单篇转换。

ok,没找到
