### ISSUE TITLE
Improve search group by doc

### ISSUE THREAD

**Issue by QMike0** [siyuan-note/siyuan#11667]
全局搜索设置`按文档分组`，同一文档会被分成多次显示

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在全局搜索设置`按文档分组`后，同一文档会被分成多次显示，每次显示所包含的内容块不同，这些内容块加在一起才是该文档中包含相应关键词的全部内容。该问题可能只出现在搜索结果较多的情况。我对全局搜索的筛选设置如下：
![image](https://github.com/siyuan-note/siyuan/assets/43239563/4c0b343c-d172-44d2-85dc-a318aaaac2ea)

以我笔记中的文档《GNSS&INS组合导航》为例，搜索关键词`导航`，该文档会出现多次，如下（多图警告）：
![image](https://github.com/siyuan-note/siyuan/assets/43239563/4f6a561f-9435-492d-8942-cf30e742e515)
![image](https://github.com/siyuan-note/siyuan/assets/43239563/334ac838-8bc9-477b-b0b7-3c96b1514c7e)
![image](https://github.com/siyuan-note/siyuan/assets/43239563/581f2962-199e-4481-ba6f-03480c5f1bfb)
![image](https://github.com/siyuan-note/siyuan/assets/43239563/393a3480-1e64-4ebf-8b58-3f432a67f61a)
![image](https://github.com/siyuan-note/siyuan/assets/43239563/b4781741-763f-4053-ad40-bd9145c2e070)
![image](https://github.com/siyuan-note/siyuan/assets/43239563/c17659e4-3af6-4167-b537-682342bdcb16)

### Expected result

全局搜索设置`按文档分组`后，同一文档的内容块应集中展示在同一文档下（顾名思义嘛），而不应该分开
仍然以《GNSS&INS组合导航》为例，里面共有16个内容块涉及到关键词`导航`，那么在搜索`导航`时，应按照如下进行集中展示：
![image](https://github.com/siyuan-note/siyuan/assets/43239563/0c61a7b6-90ab-4c27-bf98-538976e48786)

### Version environment

```markdown
- Version: v3.0.17
- Operating System: windows11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/user-attachments/files/15750652/system-log.zip)

**Comment by 88250** [comment]
完全不分页查询的话数据量大了会非常慢，改为按 设置 - 搜索 - 搜索结果显示数 限制吧。

**Comment by mozhux** [comment]
> 完全不分页查询的话数据量大了会非常慢，改为按 设置 - 搜索 - 搜索结果显示数 限制吧。

前天处理了一个咨询问题。。说是搜索少很多结果，很多人没看到上面的分页按钮，而且以为滚动和方向键下会动态加载新的。。
我建议还是滚动下来能动态加载分页吧。

**Comment by 88250** [comment]
还是用页码吧。

**Comment by QMike0** [comment]
> > 完全不分页查询的话数据量大了会非常慢，改为按 设置 - 搜索 - 搜索结果显示数 限制吧。
> 
> 前天处理了一个咨询问题。。说是搜索少很多结果，很多人没看到上面的分页按钮，而且以为滚动和方向键下会动态加载新的。。 我建议还是滚动下来能动态加载分页吧。

+1，我也是最近用搜索功能的时候总感觉少很多内容才提的这个issue。分页展示确实可以避免性能问题，但会导致误解是搜索结果不全，特别在`按文档分组`的情况下分散到不同页面更像是一种bug

**Comment by 88250** [comment]
这应该是个使用习惯问题，可能需要强调一下分页？

**Comment by QMike0** [comment]
> 这应该是个使用习惯问题，可能需要强调一下分页？
胖佬说的动态加载是一种思路；如果继续分页展示的话，也可以在当前页滚动到底部的时候，显示类似于下面的页面选择，取代现在的把分页按钮放在左上角，应该会更直观一些
![image](https://github.com/siyuan-note/siyuan/assets/43239563/1d59a8b3-ab86-4c39-a4e5-cf5ddf7c179d)

**Comment by QMike0** [comment]
另外，`按文档分组`最好还是能放一起，即使分页展示，下一页的内容和上一页的内容应该接上，这样比较符合正常查找逻辑。
比如上面图中的`GNSS&INS组合导航`文档，即使同一页无法完全展示它里面的内容块内容，下一页的开头也应该继续展示`GNSS&INS组合导航`文档对应的内容块

**Comment by 88250** [comment]
> > 这应该是个使用习惯问题，可能需要强调一下分页？
> 
> 胖佬说的动态加载是一种思路；如果继续分页展示的话，也可以在当前页滚动到底部的时候，显示类似于下面的页面选择，取代现在的把分页按钮放在左上角，应该会更直观一些 ![image](https://private-user-images.githubusercontent.com/43239563/338865058-1d59a8b3-ab86-4c39-a4e5-cf5ddf7c179d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzc3OTgsIm5iZiI6MTcxODE3NzQ5OCwicGF0aCI6Ii80MzIzOTU2My8zMzg4NjUwNTgtMWQ1OWE4YjMtYWI4Ni00YzM5LWE0ZTUtY2Y1ZGRmN2MxNzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA3MzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1Nzc4ZDdlN2RjMzU1NTE5NjQ5ZTJjNTBhOGM5YjZmNTRmMGQ2OGZkZTMxZmFiZDE3ZWJmODNhZmQ2OWY1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvY4lY3QNymEjxweQcJOgNusJuGi2WNmyVre_adFmRs)

新开个 issue 展示分页信息 https://github.com/siyuan-note/siyuan/issues/11699

**Comment by 88250** [comment]
> 另外，`按文档分组`最好还是能放一起，即使分页展示，下一页的内容和上一页的内容应该接上，这样比较符合正常查找逻辑。 比如上面图中的`GNSS&INS组合导航`文档，即使同一页无法完全展示它里面的内容块内容，下一页的开头也应该继续展示`GNSS&INS组合导航`文档对应的内容块

有道理，稍后看看能否优化。

**Comment by 88250** [comment]
尝试了下，文档分组分页后的排序没有办法保证切换分页时文档的顺序不变，因为是按照 blocks 搜索分页的，其结果在聚合分组，所以后面的页中可能会包含第一页结果之外的文档从而打乱第一页中看到的文档顺序。

**Comment by QMike0** [comment]
> 尝试了下，文档分组分页后的排序没有办法保证切换分页时文档的顺序不变，因为是按照 blocks 搜索分页的，其结果在聚合分组，所以后面的页中可能会包含第一页结果之外的文档从而打乱第一页中看到的文档顺序。

能否`按文档分组`的搜索结果不直接展示各个内容块，而是按照`搜索结果显示数`只展示限制数目下的文档（折叠状态），展开该文档查看时再动态加载它包含的内容块。这样应该能最大程度避免性能问题

**Comment by 88250** [comment]
这样的话还是可能碰到两个问题：

* 文档中命中的块太多，展开加载还是有性能问题
* 每次都需要展开，使用起来较为繁琐

**Comment by QMike0** [comment]
>  每次都需要展开，使用起来较为繁琐

个人来说，每次都需要展开虽然有点麻烦，但相较于同一文档的搜索结果分散在不同页中、导致的搜索结果不全的错觉，其实更能接受前者。「全但麻烦」比「简单但乱」要更有安全感，并且更能体现`按文档分组`这个概念一些

> 文档中命中的块太多，展开加载还是有性能问题

这个方案其实插件「[基于文档搜索](https://github.com/Misuzu2027/syplugin-document-search)」现在在用，实测性能影响不大，例如下面这些包含三百多搜索结果的文档，展开加载是很顺滑的。也有可能作者是做了优化
![image](https://github.com/siyuan-note/siyuan/assets/43239563/2d97ff64-ab17-4618-92ff-6913f109158f)

**Comment by 88250** [comment]
上面这个截图中右边的结果计数应该不是展开的时候才计算的吧？如果不是的话其实也做了一次不分页的全库搜索，你那里测试如果觉得不算慢的话那我们也可以试试不分页。

干脆这样吧，这个 issue 先按不分页（即将分页大小设置为整数最大值）实现，后续如果有人反馈性能问题，我们再考虑回退到按 搜索结果显示数 进行分页限制。

**Comment by QMike0** [comment]
> 上面这个截图中右边的结果计数应该不是展开的时候才计算的吧？如果不是的话其实也做了一次不分页的全库搜索，你那里测试如果觉得不算慢的话那我们也可以试试不分页。

对，是折叠状态下显示的。不过它限制了每页的文档数量，每页在切换时会有短暂的加载过程。很短，即使像我截图里面所示文档包含1000多搜索结果，每页加载时间也不到一秒。
![image](https://github.com/siyuan-note/siyuan/assets/43239563/07439b15-bb44-4eaf-aeb1-9a8afb08f196)
![image](https://github.com/siyuan-note/siyuan/assets/43239563/90858a86-31ad-4320-8995-9f37efacd278)

这样来看可能并非做的是完全不分页的全库搜索，只不过分页并不是思源这种基于内容块数量这种形式，而是每页展示的文档页。如果完全不分页的话，我估计肯定会有性能问题的反馈😂

**Comment by 88250** [comment]
你整个库有多少块，可以看下启动后的日志。

**Comment by QMike0** [comment]
> 你整个库有多少块，可以看下启动后的日志。

[system-log.zip](https://github.com/user-attachments/files/15802313/system-log.zip)
这个嘛？不知道怎么看😂

我用wordcount挂件的统计结果是这个：
![image](https://github.com/siyuan-note/siyuan/assets/43239563/d64c98b5-41be-46c3-a678-a13430456023)

**Comment by QMike0** [comment]
> > 你整个库有多少块，可以看下启动后的日志。
> 
> [system-log.zip](https://github.com/user-attachments/files/15802313/system-log.zip) 这个嘛？不知道怎么看😂
> 
> 我用wordcount挂件的统计结果是这个（不过好像不太准）： ![image](https://private-user-images.githubusercontent.com/43239563/338907215-d64c98b5-41be-46c3-a678-a13430456023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODQ2NzQsIm5iZiI6MTcxODE4NDM3NCwicGF0aCI6Ii80MzIzOTU2My8zMzg5MDcyMTUtZDY0Yzk4YjUtNDFiZS00NmMzLWE2NzgtYTEzNDMwNDU2MDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA5MjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNGQ4ZTkwMTQzOGVlYTk0ODVhYjBkOWQ2ZjAzYmFmYTM0Mjc4OWJlNjMyYWRlZjFlMzhmYTU1YjcxNTZlYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5BKEcm0QAztGN207TnVu0Dvfqp6cEzb1FROgeyohQ2k)

**Comment by 88250** [comment]
`tree/block count [534/53733]` 这个数量下性能问题不大，但是几十万的块可能就会比较慢了。

算了，这个 issue 暂时还是不做了，目前没有充分测试的条件，为了保险起见，还是撤销提交吧。等后面有机会我们再重新考虑。

**Comment by 88250** [comment]
这个没有更好的方案了，按文档分组的情况下只能分页查询，不然结果集太大性能上无法接受。

使用方式上可以切换到不分组或者限定搜索返回（Ctrl+F 在文档中搜索）来减少结果集，让结果更精确。

**Comment by QMike0** [comment]
> 这个没有更好的方案了，按文档分组的情况下只能分页查询，不然结果集太大性能上无法接受。
> 
> 使用方式上可以切换到不分组或者限定搜索返回（Ctrl+F 在文档中搜索）来减少结果集，让结果更精确。

可是如果不解决的话，搜索出来的结果不在同一页展示，“按文档分组”这一功能算是废了。“不分组”的搜索结果很凌乱，特别是搜索结果很多的情况下并不实用；基于文档 Ctrl f 的搜索则不太实际，虽然可以先搜索定位到文档后，再进入文档单独搜索，但这个过程本身就是很繁琐的，而且要是搜索结果存在于很多文档呢？一一去找就过于折腾了。

有个思路不知道技术层面上能否实现：基于文档搜索时仅先显示文档层面的结果，但都处于折叠状态，当点击某个文档的折叠按钮展开后，再去渲染加载该文档中内容块对应的搜索结果。从而避免同时渲染多个文档的内容块

D大再考虑一下这个功能的改进吧，个人觉得宁愿卡一点，也不要完全废了

**Comment by TCOTC** [comment]
> 都处于折叠状态

不要这个，凭空增加了阻碍

**Comment by QMike0** [comment]
> 不要这个，凭空增加了阻碍

说实话增加不了多少障碍，而且总比下面这个过程简单：
“基于文档 Ctrl f 的搜索则不太实际，虽然可以先搜索定位到文档后，再进入文档单独搜索，但这个过程本身就是很繁琐的，而且要是搜索结果存在于很多文档呢？一一去找就过于折腾了。”
