### ISSUE TITLE
侧栏按钮的鼠标光标变成箭头了

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11672]
侧栏按钮是：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/720cda19-0e9a-48c0-a400-fe33fb71a0de)

其他按钮是：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d28f66fa-e890-4dfe-ab6d-c29ca4e35471)

**Comment by 88250** [comment]
这个改动不拉进版本了。
