### ISSUE TITLE
改进选中文本替换的光标位置

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11679]
### In what scenarios do you need this feature?

**选中**文本后按 `Ctrl+R` ，目前弹出窗口后是全选被替换的文本（上方），我希望改为将光标移动到替换的文本框（下方），方便按下快捷键后直接键入替换的文本

（**不选中**文本直接按 `Ctrl+R` 的时候仍然要保持光标在上方文本框）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cc5f0647-dcba-4c80-a3de-bc3caa378c2c)

### Describe the optimal solution

。

**Comment by 88250** [comment]
感谢提议，但是这个不考虑了，参考了下 IDE 也是在搜索框里的。

**Comment by TCOTC** [comment]
@88250 我用 VSCode 光标是出现在替换文本框里的，平常都用习惯按下快捷键后直接输入了：

[替换.webm](https://github.com/siyuan-note/siyuan/assets/78434827/3bcfc740-3b49-41a1-9e57-4db2b0f5fabd)
