### ISSUE TITLE
新文档需在最近操作的页签中打开

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11676]
### In what scenarios do you need this feature?

焦点在右侧，打开文档也应该始终在右侧打开

[焦点.webm](https://github.com/siyuan-note/siyuan/assets/78434827/594ed918-ff80-43cb-8611-767674c51a15)

### Describe the optimal solution

。

**Comment by 88250** [comment]
这个好像不是丢失焦点，而是帖子正文中提到的“焦点在右侧，打开文档也应该始终在右侧打开”？

**Comment by TCOTC** [comment]
> 焦点在右侧，打开文档也应该始终在右侧打开

这个是我的需求，但某些操作导致焦点没了之后就会变成在左侧打开

某些操作：点击侧栏按钮（比如打开文档树）、展开/折叠文档

**Comment by Vanessa219** [comment]
点击 dock 面板后，焦点会在面板上，这样才能在面板上使用对应的快捷键。

**Comment by TCOTC** [comment]
所以就是 展开/折叠文档 的问题了？

**Comment by Vanessa219** [comment]
不是，是面板聚焦。这是正常的。

**Comment by TCOTC** [comment]
但是在分屏之后的操作上很不便利
