### ISSUE TITLE
The marketplacepackage supports author name search

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11673]
集市支持根据作者名称搜索

### In what scenarios do you need this feature?

https://ld246.com/article/1717643898610

p.s. 有时候我想快速找一下我的插件时也会需要

### Describe the optimal solution

集市支持根据作者名称搜索

**Comment by 88250** [comment]
这个不考虑了，可以到 GitHub 上搜索。

**Comment by TCOTC** [comment]
Obsidian 是可以按作者搜索的，感觉很方便：

![image](https://github.com/user-attachments/assets/4e5c486e-ddd3-46ce-baea-465808ef6cdd)

**Comment by 88250** [comment]
抱歉，我看错了，只是搜索的话可以支持。
