### ISSUE TITLE
Mermaid 渲染 Markdown 偏移问题

### ISSUE THREAD

**Issue by etchnight** [siyuan-note/siyuan#11670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在Mermaid中使用Markdown时，渲染出的Markdown文本会出现偏移，具体来说，是在Mermaid的流程图中，节点使用Markdown文本，如：
```
flowchart LR
    markdown["`This **is** _Markdown_`"]
    newLines["`Line1     Line 2     Line 3`"]
    markdown --> newLines
```

渲染结果为：
![捕获](https://github.com/siyuan-note/siyuan/assets/39119983/945d9ccb-a40e-4f40-9603-445bc51aea43)

### Expected result

上例中的渲染结果应该为：
![捕获2](https://github.com/siyuan-note/siyuan/assets/39119983/0d45b629-d1e9-4d05-a5f7-cbe6b4cc1f2b)

### Version environment

```markdown
- Version: v3.0.17
- Operating System: windows
- Browser (if used):
```

### Log file

不需要

### More information

经查，是由以下CSS规则导致，该规则位于`siyuan\app\src\assets\scss\component\_typography.scss`文件中（第25行）：
```
.b3-typography p, .b3-typography [data-node-id], .protyle-wysiwyg p, .protyle-wysiwyg [data-node-id] {
    line-height: 1.625;
    padding: 4px;
    margin: 2px 0;
    border-radius: var(--b3-border-radius);
}
```
原因是在Mermaid中使用Markdown文本时，渲染生成的元素为`<p>`而非`<span>`.
目前临时的修复方案是在代码片段中添加如下代码片段：
```
.protyle-wysiwyg foreignObject p {
  padding: 0;
  margin: 0;
}
```

**Comment by idealkindom** [comment]
确实有这个问题，请测试下我这个
```mermaid
sequenceDiagram
    autonumber
    participant 1 as $$\alpha$$
    participant 2 as $$\beta$$
    1->>2: Solve: $$\sqrt{2+2}$$
    2-->>1: Answer: $$2$$
    Note right of 2: $$\sqrt{2+2}=\sqrt{4}=2$$
```

**Comment by Vanessa219** [comment]
还有问题的话，导出 .sy 文件上传一下。

**Comment by idealkindom** [comment]
> 还有问题的话，导出 .sy 文件上传一下。

请查收附件和截图。这个mermaid图里α和β会显示不全。之前zettlr和Joplin也有这种问题，不过Joplin 3.1.1已经修复了。
[Mermaid渲染问题.sy.zip](https://github.com/user-attachments/files/16571225/Mermaid.sy.zip)
<img width="484" alt="思源mermaid渲染问题截图_2024-08-11_08-34-35" src="https://github.com/user-attachments/assets/5a9d3d92-6ec3-418b-b83b-5c863f4b32ac">

**Comment by idealkindom** [comment]
> 还有问题的话，导出 .sy 文件上传一下。

不过我觉得思源这个最大的硬伤还是导出图片超级慢，并且不支持svg，对于内容多一点的脑图、流程图，png那分辨率根本没法看

**Comment by Vanessa219** [comment]
这些可以使用导出 html

**Comment by idealkindom** [comment]
讲真的，思源的导入导出功能都隐藏的好深，找到一圈没找到，更加没有找到导出html

在 2024-08-12 10:37:42，V ***@***.***> 写道：


这些可以使用导出 html

**Comment by idealkindom** [comment]
.我找到导出html了，比png强多了

在 2024-08-12 10:37:42，V ***@***.***> 写道：


这些可以使用导出 html

**Comment by Vanessa219** [comment]
> > 还有问题的话，导出 .sy 文件上传一下。
> 
> 请查收附件和截图。这个mermaid图里α和β会显示不全。之前zettlr和Joplin也有这种问题，不过Joplin 3.1.1已经修复了。 [Mermaid渲染问题.sy.zip](https://github.com/user-attachments/files/16571225/Mermaid.sy.zip) <img alt="思源mermaid渲染问题截图_2024-08-11_08-34-35" width="484" src="https://private-user-images.githubusercontent.com/18344868/356843703-5a9d3d92-6ec3-418b-b83b-5c863f4b32ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0Mjg4NDAsIm5iZiI6MTcyMzQyODU0MCwicGF0aCI6Ii8xODM0NDg2OC8zNTY4NDM3MDMtNWE5ZDNkOTItNmVjMy00MThiLWI4M2ItNWM4NjNmNGIzMmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAyMDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MWUxODhiNDczZjM5NDBkZjIxYjE0NjI4NjRiOThlNzQzYTQ5YTljMDQ5ZDRlOTQ4NmFhOGY0NTkzNmQ4MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.05XQQoRU5fxyN-gCCuu993tqmmkdPX44JMkI8GcXI20">

下个版本再看看
