### ISSUE TITLE
Is it possible to select dev version in Siyuan?

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#11686]
### In what scenarios do you need this feature?

有没有可能在思源的 设置 - 关于 里，增加 dev 版本的选择？

懒癌发作，觉得每次要上Github下载dev版本，然后覆盖更新比较麻烦。想到了可以在设置里选择版本。

### Describe the optimal solution

-

**Comment by 88250** [comment]
不行的，dev 版本没有做 cdn，正式版本才有 cdn，所以就算显示了也不能保证能够正常下载，还是手动下载吧，感谢反馈。
