### ISSUE TITLE
search all database by "type=='db'" in sql

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#11687]
### In what scenarios do you need this feature?

At present, I can search all document or tasks blocks by setting the type in sql expression.
Could you offer the similar function for database?

### Describe the optimal solution

-

**Comment by TCOTC** [comment]
@88250 需要一个数据库块？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ceb09b3b-4bc9-4714-a68b-271400a9a955)

**Comment by 88250** [comment]
@TCOTC 帮忙加一下

**Comment by TCOTC** [comment]
@XinLi0111 You can use `type='av'`

**Comment by XinLi0111** [comment]
为了国际化？av可以了，赞

**Comment by TCOTC** [comment]
@XinLi0111 这个 issue 关闭吧，在 #11691 中补充类型字段说明

另外，可以把标题的 db 改成 av

**Comment by 88250** [comment]
标题可以不用改了，这个 issue 关闭，谢谢。
