### ISSUE TITLE
Remove invisible characters from file names when uploading assets

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11683]
将这个 PDF 文件拖到思源里：

[​​937.pdf](https://github.com/user-attachments/files/15781769/937.pdf)

点击后会报错：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/dfd5b6c6-ed29-4094-a36c-b6a5532341c0)

p.s. 不知道从 GitHub 下载的文件还能不能复现

**Comment by 88250** [comment]
我这里下载后测试正常。

试试打个 zip 包再上传。

**Comment by TCOTC** [comment]
群里那位打压缩包再解压之后也不行，但我这里解压之后就可以正常插入了。我在QQ把PDF转发给你再试试

**Comment by 88250** [comment]
那个压缩包解压不了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/dce8516d-95da-4c9b-9b29-c7db2005f384)

**Comment by TCOTC** [comment]
我用 Bandizip 能正常解压
