### ISSUE TITLE
右下角很多区域的按钮无法点击

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#11684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

不同的主题下，都无法点击，右下角的按钮和区域 

### Expected result

一切正常

### Version environment

```markdown
- Version: 商店 最新版
- Operating System: Win11
- Browser (if used):
```

### Log file

--

**Comment by TCOTC** [comment]
给个截图或者录屏说明一下？

**Comment by 88250** [comment]
你好，如果默认主题（daylight/midnight）没有问题的话说明是社区主题兼容问题，麻烦给对应主题提 issue 反馈，谢谢。

**Comment by TCOTC** [comment]
@heartacker 关闭所有插件和代码片段后重启思源，再录屏看看
