### ISSUE TITLE
改进面包屑更新

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11685]
- [ ] ~~点击标题时，清空面包屑（而不是仍然显示上一个面包屑）~~
- [ ] 在某种情况下面包屑未出现：

[面包屑.webm](https://github.com/siyuan-note/siyuan/assets/78434827/1ac47ba9-fc49-43ca-b563-b79ded098440)

**Comment by Vanessa219** [comment]
1. 在标题上不消失的话还可以高亮上一个光标的位置，是由于什么原因需要消失呢？
2. 使用过键盘的话就会消失了，为了让用户在文字输入时不被面包屑的更新所干扰。

**Comment by TCOTC** [comment]
1. 那就留着吧
2. 没用键盘，视频里只用了鼠标左键

**Comment by 88250** [comment]
我这里无法重现问题 2

**Comment by TCOTC** [comment]
@88250 点两个相邻列表块的中间，我这里很容易复现

**Comment by 88250** [comment]
哦，可以重现了.
