### ISSUE TITLE
Search assets cannot open and locate file name containing `'`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11693]
搜索资源文件无法打开定位包含 `'` 的资源文件

https://ld246.com/article/1718096363449/comment/1718099300608?r=88250#comments

**Comment by TCOTC** [comment]
但是有另一个问题，文档导出 PDF 和插入 PDF 时，为什么会去掉文件名中的 `'` 呢？

**Comment by 88250** [comment]
> 但是有另一个问题，文档导出 PDF 和插入 PDF 时，为什么会去掉文件名中的 `'` 呢？

特意去掉的。

**Comment by 88250** [comment]
> 我这里测试正常。搜索内容/文件内容/文件名 包含 `'` 都可以正常打开资源所在文件夹

我这里的测试有点问题，稍后具体再看看。
