### ISSUE TITLE
选中任意文字，复制为Markdown格式

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1169]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

有时候用MD在思源中编写的内容需要粘贴到其他平台：比如我现在敲的github issue
从思源直接选中复制粘贴的是不带markdown语法的内容

可以利用导出的方式，但是比较繁琐

### 描述最优的解决方案 Describe the optimal solution

右键点击选中内容，提供“复制为markdown”选项

**Comment by 88250** [comment]
目前在编辑器中复制应该是 Markdown 格式的， #1152 中会做一些标准 Markdown 和 kramdown 的复制区分。
