### ISSUE TITLE
Displays pagination info in search results

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11699]
https://github.com/siyuan-note/siyuan/issues/11667#issuecomment-2162304401

**Comment by TCOTC** [comment]
> issue 关键词：搜索 分页导航

参考 TDesign 的功能和样式：

![image](https://github.com/user-attachments/assets/d7d34fe8-e9eb-4496-b870-db5a0bf07451)

**Comment by 88250** [comment]
统一使用数据历史中的设计吧：

![image](https://github.com/user-attachments/assets/bbcd73e0-8eca-44c2-ac55-b6b3b79e674f)

**Comment by Vanessa219** [comment]
很多产品的搜索都没有分页跳转的设计，用户在搜索的时候是需要去顺着看结果的。https://github.com/siyuan-note/siyuan/issues/11667 这个使用分页来解决不是完美的办法，先关闭了。

**Comment by TCOTC** [comment]
> 参考 TDesign 的分页功能和样式：
> 
> ![image](https://github.com/user-attachments/assets/d7d34fe8-e9eb-4496-b870-db5a0bf07451)
> 

所以说用这种嘛
