### ISSUE TITLE
BUG: PDF阅读器使用ctrl+鼠标滚轮放大缩小页面不正常

### ISSUE THREAD

**Issue by 101010zyl** [siyuan-note/siyuan#11705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

PDF阅读器使用ctrl+鼠标滚轮放大缩小页面不正常：滚轮滚一格会导致过度的放大和缩小，比如从20%到150%到510%。
使用ctrl + =/- 放大缩小功能正常。

### Expected result

滚轮滚一格会导致正常的放大和缩小

### Version environment

```markdown
- Version: 3.0.17
- Operating System: windows11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/15808097/siyuan.log)

**Comment by hihaojie** [comment]
会不会是鼠标滚轮出问题了😂

**Comment by Vanessa219** [comment]
这个缩放是 pdf.js 内部自己处理的。
