### ISSUE TITLE
Does siyuan support spoiler tag?

### ISSUE THREAD

**Issue by thecoffeebin** [siyuan-note/siyuan#11700]
### In what scenarios do you need this feature?

Just like this one here https://meta.stackexchange.com/questions/1191/add-markdown-support-for-hidden-until-you-click-text-aka-spoilers

Spoiler is good for hiding some text from visible right away to readers until he/she decides to click on it.

### Describe the optimal solution

Suggestion: Add spoiler tag under slash functions.

**Comment by 88250** [comment]
It is not supported natively. You may try the callout plugin in the marketplace. Thanks.
