### ISSUE TITLE
在思源笔记中存放任意文件

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#11702]
### In what scenarios do you need this feature?

很多情况下，我想在笔记中插入一些文件，如 `xxx设计稿.psd`、或者 `xxx会议.pptx`，然后用链接把它们放到笔记正文中，然后点击即可用系统默认的打开方式打开这些文件预览，就像obsidian一样

想要在多台设备间同步这些文件时，我觉得把这些文件放在思源而非本地进行存储是很有必要的

### Describe the optimal solution

解决方案可以参考下obsidian，可以直接把文件拖入对应的目录进行存储，点击文件时触发系统默认的打开方式

### Describe the candidate solution

如果实现起来复杂的话，或许可以独立于笔记系统单独创建一个目录用来存放其它文件

**Comment by 88250** [comment]
现在就是这样设计的，请参考 用户指南 - 资源文件 章节。
