### ISSUE TITLE
功能请求：数据库主键中支持使用 F3 创建子文档并绑定块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11703]
### In what scenarios do you need this feature?

在数据库纯文本主键中选中文本后按 F3 ，目前是没反应的，我希望可以以选中的文本作为文档名创建子文档，然后该主键绑定该子文档。

### Describe the optimal solution

。

**Comment by 88250** [comment]
考虑到主键本身不适合记录太长的内容，所以选择部分后创建文档并绑定不会成为高频功能。这一点和内容块是有区别的，比如段落块内容较多，选择部分词语后创建文档引用或仅引用是可能经常使用的。

另外，可以考虑通过插件实现，原生就不考虑了，感谢提议。
