### ISSUE TITLE
使用快捷键进行移动时，移动对象与预期不一致

### ISSUE THREAD

**Issue by 7eopard** [siyuan-note/siyuan#11701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 打开文档A1，
2. 先把光标焦点放在某一个块a上，
3. 然后点击文档级的打开菜单（标题左边的，或右上角切换锁定状态旁边的，两者表现一致），
4. 使用自定义的快捷键触发移动功能，并选定目标文档A2，执行移动，
5. 光标所在的块a被移动为目标文档的块a'。

### Expected result

将文档A1移为文档A2的子文档

### Version environment

```markdown
- Version: latest msstore release (v3.0.17)
- Operating System: Win11
- Browser (if used): N/A
```

### Log file

uploaded failed

### More information

建议将移动块、移动文档设成两个快捷键

**Comment by TCOTC** [comment]
总结一下：打开文档块标菜单时，使用 `移动` 的快键键，应该移动的是文档，而不是光标所在的块。

**Comment by 7eopard** [comment]
> 总结一下：打开文档块标菜单时，使用 `移动` 的快键键，应该移动的是文档，而不是光标所在的块。

你总结的很好，但是我还是希望能分成两个快捷键( ´･･)ﾉ(._.`) 不然每次移动文档都要用抬手用鼠标点下

**Comment by Vanessa219** [comment]
快捷键就用一个了，还有文档树上也可以使用，这样记起来会比较方便。

**Comment by 88250** [comment]
这个改动不拉进版本了。
