### ISSUE TITLE
改进数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11715]
### In what scenarios do you need this feature?

如果宽度小到前面的文字看不见了，可以给一个悬浮提示：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/76969dc5-b64b-4e60-8df0-707d2b5e7b54)

### Describe the optimal solution

。

**Comment by Vanessa219** [comment]
应该是有的呀

<img width="117" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/fe5fa01a-c5f8-4e4c-8aa6-63fa6d100a48">

**Comment by 88250** [comment]
这个改动不拉进版本了。
