### ISSUE TITLE
维基百科剪藏还有点问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11717]
https://ld246.com/article/1718252952456

- [ ] 剪藏丢失列表内容
- [ ] 公式有点差别：

网页：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c4d9ca26-8b6a-4574-9a30-fc481d018f74)

剪藏：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/27ae84a9-b099-48c2-848b-5a3f06b5f672)

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/11640 中改进，谢谢。

**Comment by 88250** [comment]
PS：这个改进需要升级剪藏扩展才行。
