### ISSUE TITLE
当数据库在过滤/排序/搜索的时候，无法添加新数据

### ISSUE THREAD

**Issue by tod-zhang** [siyuan-note/siyuan#11711]
### In what scenarios do you need this feature?

后续添加同类型数据的时候，很不方便
![image](https://github.com/siyuan-note/siyuan/assets/74004482/d7834039-7031-46f0-bb4b-728b558253e4)

### Describe the optimal solution

希望像notion一样，可以在任何时候添加数据

**Comment by TCOTC** [comment]
@88250 如果在搜索时新增条目， Notion 是会直接清空搜索内容的

**Comment by TCOTC** [comment]
@tod-zhang 给一个实际操作的录屏演示看看具体情况？

**Comment by tod-zhang** [comment]
![recording](https://github.com/siyuan-note/siyuan/assets/74004482/fbbaaa97-b23d-4505-8a10-6b3eb4b9a5c4)

筛选的时候 可以新增条目

排序和搜索的时候不行

**Comment by tod-zhang** [comment]
还有就是 筛选功能会强制区分大小写，这个可以关闭么

**Comment by TCOTC** [comment]
- 跟排序有关的问题这里也有一个：#11349 ，不知道能不能一起解决
- 这个 issue 先解决搜索时新建条目的问题吧

**Comment by 88250** [comment]
这个不考虑再改变了，否则设计冲突的情况太多，感谢反馈。

**Comment by TCOTC** [comment]
> 如果在搜索时新增条目， Notion 是会直接清空搜索内容的

@88250 我觉得这个改成跟 Notion 一样也不是不行

**Comment by 88250** [comment]
暂时还是不动了。

**Comment by TCOTC** [comment]
感觉这个需求可以通过 #11965 解决
