### ISSUE TITLE
数据库多选列编辑和单元格修改保持滚动条位置

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11710]
### 数据库多选选项很多时，点击后会跳回开头

[数据库.webm](https://github.com/siyuan-note/siyuan/assets/78434827/da7019ed-b804-4f67-b74d-c11ec1d00ba6)

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by TCOTC** [comment]
@Vanessa219 希望在看不见上面换行的情况下，选项列表能保持住位置不动：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b6a6e79d-95e6-4c2a-8deb-e28fe55aef8c)

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/ca74b57d-3221-4757-8037-59bca5828d15)
