### ISSUE TITLE
分离伺服的访问授权码和本地打开的访问授权码

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11716]
### In what scenarios do you need this feature?

偶尔伺服，要设置访问授权码，但又不想本地打开每次都要输入访问授权码，所以伺服完之后要清空访问授权码，下次伺服又重新设置访问授权码……太麻烦了。

### Describe the optimal solution

就像发布服务是单独授权的一样，把伺服的访问授权码和本地打开的访问授权码分离。

在开启了伺服功能的情况下：

1. 如果 `伺服授权码` 和 `本地授权码` 都为空：伺服无法访问、本地打开不需要输入密码
2. 如果 `伺服授权码` 填写了 A 密码、`本地授权码` 为空：伺服需要输入 A 密码、本地打开不需要输入密码
3. 如果 `伺服授权码` 为空，`本地授权码` 填写了 A 密码：伺服需要输入 A 密码、本地打开也需要输入 A 密码
4. 如果 `伺服授权码` 填写了 A 密码、`本地授权码` 填写了 B 密码：伺服需要输入 A 密码、本地打开需要输入 B 密码

目前的用户属于第 3 种情况，不受影响；我需要的是第 2 种情况，只需要伺服输入密码

**Comment by 88250** [comment]
这个不考虑改变了，本地也是需要访问授权码的。

**Comment by TCOTC** [comment]
还是觉得伺服也像发布服务那样支持账户更好（跟授权码分离开），很容易收回一个人的编辑权限：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cf0e4850-535a-4a71-bddb-02802b35daa5)

**Comment by jijishenghuo** [comment]
伺服如果也设置了类似的用户名和密码，就能起到团队合作的目的了。一台云服务器，部署思源，打开伺服，记住端口号，设置用户名和密码，那不就是团队云文档啦。

可以考虑做成收费的功能特性，有需要的可以用，没需要的也不影响个人使用。主要是思源的文档，归个人或者小团队私有，本地备份，这个特点目前好像还没有笔记团队这样做的吧，可以作为创收的一个卖点。

关于冲突解决，最终管理者具有最高权限，个人拥有对个人块的所有权限，个人对其他人的块只有备注权限或者类似与pdf上的评论（评论也是一个块，所有人都可以看到评论）权限，被评论块的所有人决定是否采纳……这只是我个人的意见，觉得多一个创收的点也不错。

**Comment by jijishenghuo** [comment]
> 这个不考虑改变了，本地也是需要访问授权码的。

伺服如果也设置了类似的用户名和密码，就能起到团队合作的目的了。一台云服务器，部署思源，打开伺服，记住端口号，设置用户名和密码，那不就是团队云文档啦。

可以考虑做成收费的功能特性，有需要的可以用，没需要的也不影响个人使用。主要是思源的文档，归个人或者小团队私有，本地备份，这个特点目前好像还没有笔记团队这样做的吧，可以作为创收的一个卖点。

关于冲突解决，最终管理者具有最高权限，个人拥有对个人块的所有权限，个人对其他人的块只有备注权限或者类似与pdf上的评论（评论也是一个块，所有人都可以看到评论）权限，被评论块的所有人决定是否采纳……这只是我个人的意见，觉得多一个创收的点也不错。

**Comment by 88250** [comment]
协作还不是现阶段考虑的，这个还需要从长计议，感谢讨论。

**Comment by TCOTC** [comment]
用户反馈：

- https://ld246.com/article/1736396226227
- https://ld246.com/article/1750818407426
- https://ld246.com/article/1764235065865
- ![image](https://github.com/user-attachments/assets/3c0af904-0d4f-4354-bf92-0b47c9c2fa03)

**Comment by heartacker** [comment]
同需求

**Comment by shuojie819** [comment]
手机端打开 SiYuan APP每次都要输入密码……而且不能使用指纹等……真的太麻烦了，希望打开SiYuan APP不与私服密码绑定

**Comment by mozhuk** [comment]
支持一下，我也觉得设置伺服后本地打开也要授权码很麻烦。。

**Comment by wish5115** [comment]
支持+1
