### ISSUE TITLE
Supports creating different docs when the database primary key content is the same

### ISSUE THREAD

**Issue by tod-zhang** [siyuan-note/siyuan#11713]
数据库中的‘主键’，点击‘更多’并新建文档后，后续的相同名字的主键无法新建文档，而是会直接跳转为第一个文档. 也就是说同一个文档树列表下，名字无法重复

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/74004482/cfb61ae3-fdd2-4f6b-a78d-b0e293b47495)

### Expected result

请修复无法新建重名文档的bug

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by TCOTC** [comment]
总结一下：数据库主键无法创建与已有子文档同名的子文档

**Comment by 88250** [comment]
主键是唯一的，所以无法绑定到相同的块上。

**Comment by TCOTC** [comment]
@88250 issue 的问题是无法创建文档

**Comment by 88250** [comment]
哦，明白了，这个问题后面再看看。

**Comment by Vanessa219** [comment]
无法重现，是这样操作么？

https://github.com/siyuan-note/siyuan/assets/970828/edc7cdc8-9723-4569-9131-4400c063c485

**Comment by TCOTC** [comment]
我这里不行诶：

[重现.webm](https://github.com/siyuan-note/siyuan/assets/78434827/6b521256-4015-47a0-a652-82f1b85ba4de)

**Comment by 88250** [comment]
@TCOTC 主键那一列的重复值是使用下拉填充的还是手动填写的？

**Comment by TCOTC** [comment]
@88250 手动填的

**Comment by 88250** [comment]
嗯，我大概知道问题了，稍后调整。

**Comment by 88250** [comment]
这个改动不拉进版本了。
