### ISSUE TITLE
KaTeX parse error: Expected 'EOF', got '}' at position 19

### ISSUE THREAD

**Issue by kknd222** [siyuan-note/siyuan#11718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

KaTeX parse error: Expected 'EOF', got '}' at position 19:...esktopGroupName}}, @{ name="As...

源文本
Get-BrokerMachine -MaxRecordCount 1 | Select-Object MachineName,LastConnectionTime,IPAddress,@{ name = "交付组";expression = {$_.DesktopGroupName}},@{ name = "AssociatedUserFullNames";expression = {$_.AssociatedUserFullNames}},@{ name = "AssociatedUserNames";expression = {$_.AssociatedUserNames}}

### Expected result

KaTeX parse error: Expected 'EOF', got '}' at position 19:...esktopGroupName}}, @{ name="As...

### Version environment

```markdown
- Version: docker version v3.0.17
- Operating System: ubuntu 20.04
- Browser (if used): 360极速X 21.0.1200.0
```

### Log file

未发现明显报错

**Comment by 88250** [comment]
你好，这个公式文本好像不对吧，我在 KaTeX 官网上也无法渲染。

**Comment by kknd222** [comment]
> 你好，这个公式文本好像不对吧，我在 KaTeX 官网上也无法渲染。

这个不是公式，是powershell脚本
想问下如何不自动转换公式，只要文本记录就行了

**Comment by 88250** [comment]
哦哦，使用代码块记录即可，斜杆菜单里面找找，或者用 Markdown 语法。



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 14, 2024 08:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] KaTeX parse error: Expected 'EOF', got '}'at position 19 (Issue #11718)




  
你好，这个公式文本好像不对吧，我在 KaTeX 官网上也无法渲染。
  
这个不是公式，是powershell脚本
 想问下如何不自动转换公式，只要文本记录就行了

**Comment by TCOTC** [comment]
@kknd222 关闭公式语法的话应该不会自动转：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/794719e7-cf17-4fe8-ba74-e86f4a9b160f)

**Comment by kknd222** [comment]
> 哦哦，使用代码块记录即可，斜杆菜单里面找找，或者用 Markdown 语法。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Jun 14, 2024 08:53 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [siyuan-note/siyuan] KaTeX parse error: Expected 'EOF', got '}'at position 19 (Issue #11718) 你好，这个公式文本好像不对吧，我在 KaTeX 官网上也无法渲染。 这个不是公式，是powershell脚本 想问下如何不自动转换公式，只要文本记录就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;



> 哦哦，使用代码块记录即可，斜杆菜单里面找找，或者用 Markdown 语法。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Jun 14, 2024 08:53 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [siyuan-note/siyuan] KaTeX parse error: Expected 'EOF', got '}'at position 19 (Issue #11718) 你好，这个公式文本好像不对吧，我在 KaTeX 官网上也无法渲染。 这个不是公式，是powershell脚本 想问下如何不自动转换公式，只要文本记录就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的

**Comment by kknd222** [comment]
> @kknd222 关闭公式语法的话应该不会自动转：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/339599042-794719e7-cf17-4fe8-ba74-e86f4a9b160f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzE4MjQsIm5iZiI6MTcxODMzMTUyNCwicGF0aCI6Ii83ODQzNDgyNy8zMzk1OTkwNDItNzk0NzE5ZTctY2YxNy00ZmU4LWJhNzQtZTg2ZjRhOWIxNjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZmFkMjAyOTRiMGI4N2IyODRiNzhjOGU2ZDkyMjg5ZTViZTA2MjRlZjc2YjgyZDVkMzVlNDEyZTZhNzc1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQC52oQJkUlp_KdyyetwdAQ-dk9og0nQWYresr4V46w)



> @kknd222 关闭公式语法的话应该不会自动转：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/339599042-794719e7-cf17-4fe8-ba74-e86f4a9b160f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzE4MjQsIm5iZiI6MTcxODMzMTUyNCwicGF0aCI6Ii83ODQzNDgyNy8zMzk1OTkwNDItNzk0NzE5ZTctY2YxNy00ZmU4LWJhNzQtZTg2ZjRhOWIxNjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDAyMTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZmFkMjAyOTRiMGI4N2IyODRiNzhjOGU2ZDkyMjg5ZTViZTA2MjRlZjc2YjgyZDVkMzVlNDEyZTZhNzc1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQC52oQJkUlp_KdyyetwdAQ-dk9og0nQWYresr4V46w)

关闭后正常了，大佬
