### ISSUE TITLE
支持自定义 （代码字体）等宽字体

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#11723]
### In what scenarios do you need this feature?

for codeblock/inline code and so on

### Describe the optimal solution

null

**Comment by 88250** [comment]
这个请通过代码片段或者自定义主题实现，感谢反馈。

**Comment by heartacker** [comment]
类似 浏览器
![image](https://github.com/siyuan-note/siyuan/assets/1876302/ca572030-8c19-4407-8cf9-598838e32419)

个人认为，字体提供常规字体 和等宽字体 非常有用的。 毕竟对于我们的笔记而言，代码段，公式等都是使用等宽字体为主。

siyuan 现在只能设置字体， 建议添加一个等宽字体的设置。

对于你说的办法也是是一个方式，但是对于普通用户而言，真的非常难，都不知道如何弄。
