### ISSUE TITLE
改进页签右键菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11722]
### In what scenarios do you need this feature?

我经常用的是 `复制` 和 `分屏` ，这一堆 `关闭` 都不常用，希望互换一下位置，把 `关闭` 放到底下：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/656ff287-d168-4a5b-98b3-c61600e4ae8d)

### Describe the optimal solution

类似浏览器：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f52e32b4-fa46-4a53-ba07-05d9a6fbebaa)

**Comment by Vanessa219** [comment]
但 IDE 上是这样的
<img width="387" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/281b5c74-fe9e-4063-b946-ffe56aa4b1ef">

**Comment by TCOTC** [comment]
好吧，那就把 `关闭` 留在上面。但是 6 个 `关闭` 占地感觉太大了，不知道有没有办法优化一下

**Comment by 88250** [comment]
这个就不调整了，各种关闭的使用频率可能是要高一些的。

**Comment by TCOTC** [comment]
我在 Whisper 主题 v1.3.0 中自行实现了：

![Image](https://github.com/user-attachments/assets/398909d2-1f46-46b9-b976-20dd27c0db36)
