### ISSUE TITLE
对于符号链接的文件夹思源会当作不存在

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#11721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我开发插件是使用符号链接到思源的插件目录的，但思源没有同步改文件夹到其他终端

### Expected result

可以同步符号链接的目录

### Version environment

```markdown
- Version: v3.0.17
- Operating System: windows11
- Browser (if used):
```

### Log file

none

**Comment by TCOTC** [comment]
我印象中好像是特意改成不同步的？

**Comment by 2234839** [comment]
> 我印象中好像是特意改成不同步的？还是同步不了？

找到了 https://github.com/siyuan-note/siyuan/issues/3020

**Comment by 2234839** [comment]
我
