### ISSUE TITLE
快捷键设置中按辅助键时不进行提示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11720]
**忽略一楼**

~~在 Windows 上表现如下：~~

~~[无效.webm] (https://github.com/siyuan-note/siyuan/assets/78434827/7e614eb5-257a-4556-abb3-a3034bb7bee6)~~

---

~~用 [OpenArk](https://github.com/BlackINT3/OpenArk) 查了一下没有快捷键占用~~

**Comment by TCOTC** [comment]
在 Linux 上可以将快捷键录入，但也会弹出 `无效 [Ctrl]`

**Comment by Achuan-2** [comment]
Ctrl➕.是windows输入法切换中英文符号的快捷键

**Comment by TCOTC** [comment]
确实哦，用 [OpenArk](https://github.com/BlackINT3/OpenArk) 也没查出来。

不过我用搜狗输入法，关闭了这个快捷键也不行

**Comment by hihaojie** [comment]
> 确实哦，用 [OpenArk](https://github.com/BlackINT3/OpenArk) 也没查出来。
> 
> 不过我用搜狗输入法，关闭了这个快捷键也不行

搜狗输入法用该快捷键作为中英文标点切换的快捷键，单独关闭好像禁用不了，需要禁用全部快捷键

你可以切换成Windows自带输入法再进行测试，如果还不行，推荐用系统的英文输入法再测试（输入法显示为“Eng”，需要在Windows设置中额外安装）

另外如果你安装了 Powertoys，注意该软件有没有占用该快捷键

**Comment by TCOTC** [comment]
> 用系统的英文输入法再测试

确实用这个就没问题了。

所以在 Windows 上这个算是软件问题吧，不是思源的问题。

**Comment by TCOTC** [comment]
只剩下 Linux 上弹出 `无效 [Ctrl]` 的问题了

**Comment by TCOTC** [comment]
有个新发现，在 Windows 上如果按 `Ctrl` 的时间稍微长了一点，就会弹出 `无效 [Ctrl]`

`无效 [Ctrl]` 应该在只按下 `Ctrl` 并且送开按键之后才弹出来，而不是按下去久一点就会弹出
