### ISSUE TITLE
按下 `Home` 或 `End` 时应该隐藏 `/` 菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11726]
### In what scenarios do you need this feature?

在句子中间输入一个顿号 `、` ，然后按 `End` 跳到句子末尾按回车，此时不是新建下一个块，而是使用模板。

例如这个场景：

[场景.webm](https://github.com/siyuan-note/siyuan/assets/78434827/913691fc-6b2d-45d1-a898-fa6f45adafe8)

### Describe the optimal solution

按下 `Home` 或 `End` 时应该隐藏 `/` 菜单

**Comment by TCOTC** [comment]
最离谱的事情是按下 `Enter` 之后把光标前的 `D` 删除了。

**Comment by 88250** [comment]
这个改动不拉入版本了。
