### ISSUE TITLE
改进在标题中使用 `↓`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11729]
### In what scenarios do you need this feature?

https://ld246.com/article/1718440614240

按 `↑` 是正常的，按 `↓` 就会直接跳到首行：

[标题.webm](https://github.com/siyuan-note/siyuan/assets/78434827/7adad013-7984-4588-9903-d75452232bae)

### Describe the optimal solution

。

**Comment by TCOTC** [comment]
@Vanessa219 我觉得在正文首个块按 `↑` 之后，光标应该移动到标题里正对着的位置而不是开头（做不到的话就改成光标移动到末尾）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/afd1ec3f-73f8-4744-a814-688c8c25c9d4)

**Comment by Vanessa219** [comment]
正对的位置无法计算，一般标题都不太长，就定在开头吧。

**Comment by TCOTC** [comment]
我觉得一般应该是从末尾开始编辑的

**Comment by TCOTC** [comment]
用 Backspace 的频率应该高于 Delete
