### ISSUE TITLE
支持大纲拖动调整文件结构

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1173]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
调整文件内部结构时，目前拖动文本块的方案，对于内容较多的文本，需等待页面滚动到目标位置，调整较为不便

### 描述最优的解决方案 Describe the optimal solution
支持直接拖动大纲调整相应标题下全部内容到新位置

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/997
