### ISSUE TITLE
改进空内容块中使用 `Delete`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11732]
在列表项内，代码块之类的块上面的空段落块没法通过 `Backspace` 或 `Delete` 删除，`Backspace` 会直接反缩进：

`Backspace` 或 `Delete` 是不是应该能够删除首个段落块？

[交互.webm](https://github.com/siyuan-note/siyuan/assets/78434827/a053044d-11ca-4636-894b-b492feb0595b)

**Comment by Vanessa219** [comment]
应该是和其他块一样使用 `Delete` 进行移除

**Comment by 88250** [comment]
讨论结果是保持不变还是？

**Comment by TCOTC** [comment]
还没想到一个很合理的方案

**Comment by TCOTC** [comment]
@Vanessa219 要不分情况讨论吧？

Delete 时，下面是段落块的话就用目前这种：

> 不是把空块删除，而是把下一个块的内容复制到空块上，空块的 id 并没有变成下一个块的 id

Delete 时，下面是其他类型的块的话就把当前的块删除，下面的块移上来。而且一直都有人觉得这个 Delete 的交互很奇怪：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/834bca89-0e18-4676-85be-05667d699d21)

**Comment by Vanessa219** [comment]
这个是向后删除，等同于在下一个块前面删除。你指的删除是当块中没有内容才删除吗？那有内容就和现在保持一致？

**Comment by TCOTC** [comment]
嗯，我说的就是在空的块里按 Delete

**Comment by TCOTC** [comment]
空内容块：

- [ ] 空段落块
- [ ] 空标题块
- [ ] 空代码块
- [ ] 空表格块

**Comment by TCOTC** [comment]
在空内容块中使用 `Delete` 时，如果下面有内容块，就把当前内容块删除，下面的块移上来

**Comment by Vanessa219** [comment]
> Delete 时，下面是其他类型的块的话就把当前的块删除，下面的块移上来。毕竟一直都有人觉得这个 Delete 的交互很奇怪：

如果内容不为空时，就不会有变化，这样会不会也奇怪？

**Comment by TCOTC** [comment]
内容不为空时按 Delete 的行为就跟现在保持一致。

比如说，我用 WPS 的时候一般都是在某一行的内容为空的时候需要按 Delete 来删除这一个空行，所以不奇怪

**Comment by Vanessa219** [comment]
为了统一，以前在代码块第一个字符前 Backspace 只会移动光标，现在上一个是空块的话是会删除空块。

**Comment by TCOTC** [comment]
@Vanessa219 撤回还有问题：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/9c443074-439c-4107-884e-2ce4b2c540eb)

**Comment by TCOTC** [comment]
@Vanessa219 撤回还是有问题：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/a29e5ff3-77ce-48a9-ac50-3681c7a678a7)
