### ISSUE TITLE
Add a template function `getHPathByID`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11734]
### 增加模板函数：通过 ID 获取特定文档的路径

- 是 #11479 的衍生需求，但不止用于数据库中
- [通过 ID 获取特定文档的路径](https://github.com/siyuan-note/siyuan/issues/11479#issuecomment-2146774732)，比如 `{{ Id | DocPath }}`
- Id 为文档块 Id 时，获取到该文档的路径；Id 为其他内容块 Id 时，获取到该内容块所在文档的路径

**Comment by TCOTC** [comment]
感觉跟这个 issue 没什么关系？

**Comment by 88250** [comment]
@TCOTC 你看下是不是这个效果：

模板：

```
title: .action{ .title } 
id: .action{ .id }
hpath: .action{ getHPathByID .id}
```

输出：

![image](https://github.com/user-attachments/assets/93def9ee-4eca-443d-a12c-44a0d911318d)

**Comment by TCOTC** [comment]
能这样用就是对的：`.action{ getHPathByID 20240308161717-xkgiour }`/`.action{ 20240308161717-xkgiour | getHPathByID }`

**Comment by 88250** [comment]
```
.action{ getHPathByID "20240308161717-xkgiour" }/.action{ "20240308161717-xkgiour" | getHPathByID }
```

![image](https://github.com/user-attachments/assets/c1e95732-aa59-4c17-9b48-7917156e5886)

看上去没有问题，稍后提交代码。
