### ISSUE TITLE
删除文档后，及时将其关联的条目从所在的数据库中移除

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11731]
### In what scenarios do you need this feature?

- 删除文档后，及时将其关联的条目从所在的数据库中移除（需要实现的效果）
  - 目前要手动刷新文档才会移除条目
  - 换句话说就是需要刷新数据库块
- 回滚文档后，会重载界面，关联的条目就加回来了（目前的效果，不用改进）

### Describe the optimal solution

如果是批量删除文档，所有文档关联的数据库都要处理

**Comment by 88250** [comment]
稍后改进，不拉进版本了。
