### ISSUE TITLE
某网页复制的文本粘贴后会变成行级代码

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11737]
某网页复制的文本粘贴后会变成行级代码

https://www.kkdaxue.com/

`Ctrl+C` 复制：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/03f37df3-b990-48a4-a14b-96a9ac4ba845)

`Ctrl+V` 粘贴：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/265f4a33-a90d-44b5-94f0-ead6ec49b67f)

**Comment by 88250** [comment]
这个没有办法了，网页 dom 是 pre 标签包裹的，会被识别为代码。

![image](https://github.com/siyuan-note/siyuan/assets/873584/fe93a00b-5a84-4f93-9376-2fa117802ab5)
