### ISSUE TITLE
一点疑问

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11736]
输入 `、建模` 会匹配到 `UML` 是什么原理？

[疑问.webm](https://github.com/siyuan-note/siyuan/assets/78434827/0de0c1ec-a0b2-467e-b9a0-0c35d66d63d5)

**Comment by 2234839** [comment]
我这里也是

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/fb6d6934-6e72-4780-b7d8-c38b9ec04b0f)
