### ISSUE TITLE
chrome网页剪藏插件是否能做的更好

### ISSUE THREAD

**Issue by Hanochhu** [siyuan-note/siyuan#11739]
### In what scenarios do you need this feature?

在网页剪藏一些页面比如知乎，没有点进那个回答里的时候，用网页剪藏会从当前位置一点点滚动到顶，然后截取第一个（好像）回答，反正不是当前的。

还有一些文档页面，比如 
>https://platform.moonshot.cn/docs/api/chat#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF
会从底部往上滚，我开始以为会截取所有的，但是最终是随机截取了一部分，每次都不一样

### Describe the optimal solution

也许可以参考 onenote 的截取， 他的插件在截取的时候网页不会动，而且截取位置就是当前焦点的上下文，较为准确

**Comment by 88250** [comment]
* 知乎剪藏需要用回答的链接
* moonshot 这个网页后面看看是否能优化

**Comment by Hanochhu** [comment]
> * 知乎剪藏需要用回答的链接
> * moonshot 这个网页后面看看是否能优化

👌 牛的 第一次看见这么快的回复

**Comment by Hanochhu** [comment]
> * 知乎剪藏需要用回答的链接
> * moonshot 这个网页后面看看是否能优化

刚发现还有不对的地方，知乎用了回答的链接，但是把两个不同用户的回答剪在一起了，试了两次结果相同，好像是稳定触发的
https://www.zhihu.com/question/594837899/answer/3323645451

**Comment by Hanochhu** [comment]
好像逻辑是把所有展开的回答都裁剪，OneNote 能做的比较精确

**Comment by 88250** [comment]
你用的剪藏扩展版本是最新的吗？我这里最新的剪藏扩展测试正常，只会剪藏一个回答。

**Comment by 88250** [comment]
前面 moonshot 代码块、表格等剪藏优化合并到 https://github.com/siyuan-note/siyuan/issues/11642 中记录了。

**Comment by 88250** [comment]
新版 v1.2.8 浏览器扩展已经提交商店审核，请注意更新，并配套使用最新版（dev 版）思源。

这个问题我们先关闭了，如果后续还有反馈请直接跟帖，谢谢。
