### ISSUE TITLE
导出文件后支持用默认程序打开

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11748]
### In what scenarios do you need this feature?

现在能打开文件夹，但我还想再进一步能直接打开文件：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a97e7809-5df5-4e2a-8ddb-45363fc5080b)

### Describe the optimal solution

。

**Comment by 88250** [comment]
这个不考虑了，因为有的场景只是需要打开定位。

**Comment by TCOTC** [comment]
但是也有场景是直接打开

**Comment by 88250** [comment]
不考虑了，这个外部用户自己 Enter 或者双击就行了。

**Comment by TCOTC** [comment]
我想要这个功能主要是因为我电脑上打开文件夹要等个 10 秒钟，感觉超级慢

**Comment by 88250** [comment]
看看能不能搞个插件吧。
