### ISSUE TITLE
资产整理功能

### ISSUE THREAD

**Issue by lyyjyll** [siyuan-note/siyuan#11741]
### In what scenarios do you need this feature?

文件图片等资源放在一个文件夹下面就很多，可以分类存储吗，可以的话，再加上时间进行分组，以提升资源管理效率，笔记使用时间久了，索引会变慢吗？

### Describe the optimal solution

如果可以的话，请求实现不同类型文件的分类整理功能，例如html，PDF及其标注文件，png,video，docx等文件内容，如果可以加上日期的话，就更好啦。

**Comment by 88250** [comment]
可通过数据库功能整理。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月17日(周一) 中午12:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 资产整理功能 (Issue #11741)




 
In what scenarios do you need this feature?
 
文件图片等资源放在一个文件夹下面就很多，可以分类存储吗，可以的话，再加上时间进行分组，以提升资源管理效率，笔记使用时间久了，索引会变慢吗？
 
Describe the optimal solution
 
如果可以的话，请求实现不同类型文件的分类整理功能，例如html，PDF及其标注文件，png,video，docx等文件内容，如果可以加上日期的话，就更好啦。
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by TCOTC** [comment]
> 可通过数据库功能整理。

感觉跟数据库的场景不太一样，这个应该是要整理全部的资源文件

**Comment by lyyjyll** [comment]
感谢及时回复，如果可以实现自动管理和分类就好啦。 @88250 @TCOTC

**Comment by 88250** [comment]
抱歉，这个没有计划，可能可以期待插件，或者电脑使用第三方软件管理 data/assets 文件夹。
