### ISSUE TITLE
sort.json is saved as a single line

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#11746]
一个小建议：当选择不使用单行保存时，能否让所有的json文件，都以多行保存

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

选择不使用单行保存后
![image](https://github.com/siyuan-note/siyuan/assets/5683995/64355e5b-6ac2-4fdf-ac9f-b8e6b155bc7e)

现在的 sort.json 文件，没有保持一致性，仍然以单行保存

### Expected result

期待保持一致性

### Version environment

```markdown
- Version: 3.0.17
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
编辑一下需要多行保存的文档就行了。

直接全库转换的话不得卡死

**Comment by zhoutaosheng** [comment]
> 编辑一下需要多行保存的文档就行了。
> 
> 直接全库转换的话不得卡死
> 
> p.s. 如果你说的不是文档 json ，那就当我没说

1. 只是 sort.json 文件，没有统一而已
2. 没全库转换问题，更没有什么卡死问题，只是要跟设置以前保持一致而已

**Comment by 88250** [comment]
sort.json 似乎默认可以用单行，不支持调整，因为这个文件主要是提供给程序用的，不存在需要人为打开调整的场景。

**Comment by zhoutaosheng** [comment]
> sort.json 似乎默认可以用单行，不支持调整，因为这个文件主要是提供给程序用的，不存在需要人为打开调整的场景。
> 
> 但是其他 json 不能用单行保存，比如 conf.json，这个文件有的时候是需要人为可读写的。

确实sort.json这个文件，只支持单行，也不怎么影响。只是：
1. 看到设计不一致的地方，报告一下
2. 有的同学，用git管理笔记的时候，观察到它变动的时候，会想自己是不是做了什么修改。单行就没办法看了

**Comment by 88250** [comment]
嗯，谢谢，后面考虑把 sort.json 改为单行。

**Comment by TCOTC** [comment]
> 考虑把 sort.json 改为单行

多行吧？

**Comment by 88250** [comment]
呃，尴尬，我记反了，目前已经是单行保存了，所以就不考虑再作改动了。

**Comment by 88250** [comment]
sort.json 的话这个主要是程序用，其他场景就不考虑了。
