### ISSUE TITLE
Upgrade to Electron latest

### ISSUE THREAD

**Issue by abd-liac** [siyuan-note/siyuan#11747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

[Electron 28.x.y EOL](https://releases.electronjs.org/release/v28.3.3), thus unavailable in some distros.

### Expected result

Upgrade Electron.

### Version environment

```markdown
*
```

### Log file

*

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/11654
