### ISSUE TITLE
图片标题剪藏有点问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11745]
网页：https://zhuanlan.zhihu.com/p/654972022

剪藏：（从图片标题开始，后面少了内容）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d60775d8-6a22-4008-acb0-5d7c9b6e8361)

原网页：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/082d4076-d8c4-47c2-853b-1fd788dbd4f5)

**Comment by TCOTC** [comment]
这一堆呢？

https://www.zhihu.com/question/554620120/answer/3211660195

https://www.zhihu.com/question/384309878/answer/3207122203

https://www.zhihu.com/question/589304234/answer/3205616977

https://www.zhihu.com/question/615373351/answer/3204398153

https://www.zhihu.com/question/579920567/answer/3203177955

**Comment by 88250** [comment]
可以访问了

**Comment by 88250** [comment]
稍后改进，不拉进版本了。
