### ISSUE TITLE
独立记录标题展开状态，并且能正确处理展开和折叠

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11752]
### 独立记录标题展开状态，并且能正确处理展开和折叠

目前展开标题，标题下得所有折叠的子标题、列表都会全部展开，很影响用户体验。尤其是做个人管理的用户会经常排版，频繁折叠与展开标题，把所有折叠的子标题、列表全部展开的话会很麻烦，用起来感觉比较恼火。

相关问题：

- [大标题块折叠后展开导致内部有序列表块的折叠记录丢失 - 链滴](https://ld246.com/article/1716278488134)
- [展开标题，标题下得所有折叠都自动展开，这是特性？ - 链滴](https://ld246.com/article/1700797445928)
- [折叠的标题块打开后，其下折叠的列表块也全部默认展开 - 链滴](https://ld246.com/article/1709180379155)
- [展开上级标题会强制展开下级标题内容 - 链滴](https://ld246.com/article/1691392978540)

类 Notion 笔记软件对此的处理是增加「折叠标题」块类型：**标题**无法折叠，只有**折叠标题**可以折叠。

思源感觉不适合像 Notion 这样干，所以要考虑其他方法。

**Comment by 88250** [comment]
这个没有解决方案，相关 issue 也比较多，只能折中考虑了。

**Comment by TCOTC** [comment]
@88250 这个是哪里解决不了？

**Comment by 88250** [comment]
容器块和标题块的折叠会有逻辑冲突



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月24日(周二) 中午12:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 独立记录标题展开状态，并且能正确处理展开和折叠 (Issue #11752)




 
@88250 这个是哪里解决不了？

**Comment by TCOTC** [comment]
> 容器块和标题块的折叠会有逻辑冲突

有具体的场景例子吗？

p.s. 好像以前讨论过？但我没什么印象了，找不到相关 issue

**Comment by 88250** [comment]
必须整体折叠，不然移动块会有问题



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月24日(周二) 中午12:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 独立记录标题展开状态，并且能正确处理展开和折叠 (Issue #11752)




  
容器块和标题块的折叠会有逻辑冲突
  
有具体的场景例子吗？
 
p.s. 好像以前讨论过？但我没什么印象了，找不到相关 issue
