### ISSUE TITLE
改进文档树、大纲、列表拖动交互

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11751]
### In what scenarios do you need this feature?

像 Notion 这样可以明显地判断放下块后是变成同级还是子级：

[缩进.webm](https://github.com/siyuan-note/siyuan/assets/78434827/2ec7aabd-5ca1-41a6-9f05-18acb4a29b2f)

### Describe the optimal solution

文档树、大纲、列表的拖动都能这样就最好了

**Comment by 88250** [comment]
这个之前已经优化过了，可以从横线长短判断是同级还是子级：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/d824b976-57db-424b-9c38-4a6e47c39b6a)

**Comment by TCOTC** [comment]
@88250 我想要的是中间这个间隔，有间隔的话就不用上下左右挪来挪去比较长短了，只要有间隔就知道会变成子层级了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bb50e241-6ec2-4e15-84df-df3d9a163eac)

**Comment by 88250** [comment]
@Vanessa219 看看能否实现

**Comment by TCOTC** [comment]
参考：

![image](https://github.com/user-attachments/assets/b5fa1eb8-099e-4d85-ae11-7aa451dbc246)

**Comment by TCOTC** [comment]
@88250

**Comment by 88250** [comment]
得等 V 看

**Comment by TCOTC** [comment]
@88250 这个 issue 打开吧

**Comment by TCOTC** [comment]
@88250

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
这个线条是个样式，没办法分割。

**Comment by TCOTC** [comment]
如果这个效果没法实现的话，那能不能像目前的 Notion 这样高亮**父块(/父文档/父标题)**，便于判断拖拽到了哪里：

[视频.webm](https://github.com/user-attachments/assets/5be2e6be-357b-475d-a268-06a55ac17a04)

**Comment by TCOTC** [comment]
这个高亮的颜色没有消除：

[视频.webm](https://github.com/user-attachments/assets/2493cf45-4a84-4370-94a2-238efe543421)

还需要能临时覆盖原来的块颜色，否则有的块变成蓝色高亮，有的块又不变，视觉上很奇怪：

[视频.webm](https://github.com/user-attachments/assets/d0ff4d13-58fc-4a1a-a18b-d7ac3a35ff22)

**Comment by TCOTC** [comment]
@Vanessa219 还是会闪烁：

[视频.webm](https://github.com/user-attachments/assets/02d3bfc5-24c3-4a65-ae22-e04b81566f88)

**Comment by Vanessa219** [comment]
昨晚没有打版本

**Comment by TCOTC** [comment]
我自己用 GitHub Action 弄的，是最新的代码。

还有数据库也是：

[视频.webm](https://github.com/user-attachments/assets/c3fa19d0-1efc-4ef4-a35c-dfb72e36a983)

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/10730
