### ISSUE TITLE
分屏时，PDF 打开侧栏后无法拖拽页面宽度

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11759]
### In what scenarios do you need this feature?

关闭侧栏时是正常情况：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/82f35432-2d3a-451a-a857-9156ab54417b)

打开侧栏后，这里就无法拖动了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7c280f2f-9c1f-46f5-b102-2ccb890ee18a)

### Describe the optimal solution

。

**Comment by TCOTC** [comment]
@Vanessa219 我这里还是不行

**Comment by Vanessa219** [comment]
打开开发者工具强制刷新一下

<img width="119" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/1f3dd12b-9fff-493d-b15c-4584c8d8900e">

**Comment by TCOTC** [comment]
@Vanessa219 你把 PDF 分屏到右边再看看

**Comment by Vanessa219** [comment]
是这样操作么？

https://github.com/siyuan-note/siyuan/assets/970828/9495f347-b416-46cc-b0dc-7faf63173351

**Comment by TCOTC** [comment]
我这里可以了。不知道为啥今天又正常了

**Comment by Vanessa219** [comment]
那再观察观察
