### ISSUE TITLE
使用模板生成的日记内容格式混乱

### ISSUE THREAD

**Issue by BLACKT-T** [siyuan-note/siyuan#1175]
## 问题
模板设置好格式，一级标题和一个列表，但是点击日记按钮生成时，消除了一部分空格，导致列表第一项错位到了标题上。类似于加粗和高亮有时会自动删除空格导致不能渲染

模板：
![图片](https://user-images.githubusercontent.com/37499441/104975854-cc76be80-5a36-11eb-8f41-32bd6bb969ea.png)

日记生成效果：
![图片](https://user-images.githubusercontent.com/37499441/104975897-e57f6f80-5a36-11eb-89e2-f0ffb7427f72.png)

## 推测原因
推测是空格或者空行被清除的问题

## 期望
生成的日记格式符合模板中的格式

**Comment by 88250** [comment]
感谢反馈，064 修复。

**Comment by BLACKT-T** [comment]
加油 \^_^/
