### ISSUE TITLE
导出文档为 .sy.zip 后，进度条没有关闭

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11755]
### 导出文档为 .sy.zip 后，进度条没有关闭

文档已经正常导出完了（能正常导入另一个工作空间了），但进度条还一直显示：

![recording](https://github.com/siyuan-note/siyuan/assets/78434827/2df56bc1-ba5f-4434-8f32-c7db989a4571)

**Comment by 88250** [comment]
感谢反馈，稍后解决。
