### ISSUE TITLE
导出文档时禁用侧栏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11756]
### 导出文档时禁用侧栏

感觉导出文档时移动标题可能会产生什么问题：

p.s. 除了大纲之外，文档树、反链面板之类的也是

![image](https://github.com/siyuan-note/siyuan/assets/78434827/98c0648c-a940-41b5-87f0-b70f7186c22c)

**Comment by 88250** [comment]
这个改动不拉进版本了。
