### ISSUE TITLE
软件弃更了？？？两周没更新

### ISSUE THREAD

**Issue by zzz51522** [siyuan-note/siyuan#11753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

两周没更新，也无任何通知，是弃更了吗？

### Expected result

以前每周更新

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

no

**Comment by TCOTC** [comment]
可以看提交记录，仍然是高频更新：https://github.com/siyuan-note/siyuan/commits/dev

只是降低了发布正式版的频率

**Comment by Achuan-2** [comment]
其实我是想等思源的数据库主键模板和文档模板功能完善之后，b站发一个视频，分享使用思源笔记的经验的

但是这些功能提议被暂时搁置了🥲

**Comment by 88250** [comment]
没有放弃啊，只是降低发版频率了，谢谢。

@Achuan-2 可以先发点其他的 😂

**Comment by zzz51522** [comment]
> 可以自行查看代码提交记录，跟以往一样仍然是高频更新：https://github.com/siyuan-note/siyuan/commits/dev ；
> 
> 目前只是为了配合推广拉新而降低了正式版的发布频率，每周的 dev 版可以到 [Releases](https://github.com/siyuan-note/siyuan/releases) 里下载。

OK，为了稳定，还是等正式版吧

**Comment by zzz51522** [comment]
> 没有放弃啊，只是降低发版频率了，谢谢。
> 
> @Achuan-2 可以先发点其他的 😂

好的，以前都是每周二自动更新修补漏洞。发现端午后，到现在都没更新正式版了
