### ISSUE TITLE
标题块块标增加功能：折叠下方同级标题、展开下方同级标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11754]
### In what scenarios do you need this feature?

比如想要折叠 3、4、5 ，就可以先对 3 使用「折叠下方同级标题」、再对 6 使用「展开下方同级标题」：

p.s. 当然实际的应用场景应该有更多的标题和文本，这里只是一个例子

![image](https://github.com/siyuan-note/siyuan/assets/78434827/85e8a381-8f4b-49f8-9cbd-e0e46a1acbf7)

### Describe the optimal solution

标题块块标增加功能：折叠下方同级标题、展开下方同级标题

**不对在超级块、列表块等容器块里的同级标题生效**

### Other information

这个 issue 还能作为 #11752 需求的一种不够完全的替代方案

相关问题：[标题有没有批量折叠展开的方法 - 链滴](https://ld246.com/article/1712884735127)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/7929
