### ISSUE TITLE
PDF 页签右键菜单增加「复制」

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11758]
### In what scenarios do you need this feature?

方便引用 PDF

### Describe the optimal solution

PDF 页签增加：~~复制块 Markdown 链接~~ 还是不要那么长了，「复制」就够了

**Comment by 88250** [comment]
没看懂这个需求，麻烦补充。

**Comment by TCOTC** [comment]
加个复制：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bbe77c5c-ecea-4df6-bcd4-713f70b157ac)

**Comment by 88250** [comment]
复制的内容是？

**Comment by TCOTC** [comment]
`[果壳帮你选专业：2017版.pdf](assets/果壳帮你选专业：2017版-20240619094223-jgdvzef.pdf)`
