### ISSUE TITLE
有时候 Ctrl+悬浮 无效

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11769]
### 有时候 Ctrl+悬浮 无效

靠近边缘的时候更容易复现：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/341e8a19-4860-4859-805f-2553a4d56928)

**Comment by Vanessa219** [comment]
我和D都重现不了，是不是键盘焦点不在思源笔记上。

**Comment by TCOTC** [comment]
焦点一直都在思源里。

这个问题一直很折磨人，今天有点受不了了才想办法复现出来的。

**Comment by TCOTC** [comment]
把界面放到最大试试？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4e6fe593-fa46-42a7-b4be-0b1e329c068f)

**Comment by Vanessa219** [comment]
可以重现了，还麻烦再试试。
