### ISSUE TITLE
`Shift+Enter` does not work properly in inline elements

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11766]
### 块引用前使用 `Shift+Enter` 异常

正常情况按两下 `Shift+Enter` 应该是会新建块的，但在块引用前无效：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/031149ad-6a46-44a8-9368-cd3b194d3436)

**Comment by Vanessa219** [comment]
@88250 在块引用内连续 shift+enter 会出现标签

**Comment by 88250** [comment]
调整为行级元素内部最多只能加一个 `\n`。

**Comment by TCOTC** [comment]
@88250 改动之后还能按两下 `Shift+Enter` 新建段落块吗？

**Comment by 88250** [comment]
纯文本行级元素可以，其他行级元素不行，只能有一个换行。

**Comment by TCOTC** [comment]
是这个意思吗：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f2ddbba9-3877-42f9-b7eb-ea3d5d70da7e)

**Comment by 88250** [comment]
是的

**Comment by TCOTC** [comment]
@88250 我有个问题，为什么其他行级元素不行？

**Comment by Vanessa219** [comment]
需要的话直接回车就行，行级元素处理起来比较复杂。

**Comment by TCOTC** [comment]
差别在于：在列表中使用 Shift+Enter 和 Enter 的效果是不同的

**Comment by TCOTC** [comment]
还有这里我觉得可以优化一下：按两次 Shift+Enter 就可以新建一个块了，不应该需要继续输入文本

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/1066c467-681c-493a-aa6d-2713df441764)

**Comment by TCOTC** [comment]
@88250 看看上面这条

**Comment by 88250** [comment]
@Vanessa219 看一下

**Comment by Vanessa219** [comment]
行内元素要和段落元素保持一致的话，@88250 这边看看能不能实现？

如果`按两次 Shift+Enter 就可以新建一个块了`的话，用户就没有办法在一个块下面多次 `Shift+Enter` 空很多行了。

**Comment by TCOTC** [comment]
> 用户就没有办法在一个块下面多次 Shift+Enter 空很多行了

思源本来就不支持吧

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/c6349cec-bb6f-4cb3-a565-49076fa98d6f)

**Comment by Vanessa219** [comment]
`shift+enter` 不要输入字符

**Comment by Vanessa219** [comment]
这个 markdown 规范本来是不支持的，但是有用户需要使用同一个块进行留白，后面才添加的。

**Comment by TCOTC** [comment]
我怎么想都感觉怪怪的。现在还能找到那个用户反馈吗？我想看看是个什么需求

**Comment by Vanessa219** [comment]
就用来分割，没啥奇怪的。这个太早了，你看看能不能搜到。

**Comment by TCOTC** [comment]
@Vanessa219 这样有个问题是，用 Enter 或 Shift+Enter 都无法在列表中直接新建空行，必须先写点东西之后才能在两个块之间按 Enter 新建空行：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/4878428e-2778-4b21-a3f3-eab9ef4960fb)

我建议把这个无限软回车的特性改掉

**Comment by Vanessa219** [comment]
> 这个 markdown 规范本来是不支持的，但是有用户需要使用同一个块进行留白，后面才添加的。

使用这个就可以了，先在 `2` 后面 `shift+enter`，然后在 `ctrl+shift+a`

**Comment by TCOTC** [comment]
这个快捷键感觉不是很方便呐

**Comment by Vanessa219** [comment]
可以自定义嘛
