### ISSUE TITLE
支持 siyuan://assets 链接

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#11760]
### In what scenarios do you need this feature?

需要在思源已关闭的情况下，拉起思源并打开资源文件，同时能够解析参数。

### Describe the optimal solution

支持 siyuan://assets 链接

**Comment by zxhd863943427** [comment]
仔细想想，这样还能让插件生成统一的 `[标注](siyuan://assets)`链接，而不用考虑是要粘贴到思源还是外部了。

**Comment by 88250** [comment]
感谢提议，但是不考虑了，因为有的 assets 无法在思源内部打开。
