### ISSUE TITLE
代码块无法取消缩进

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#11761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

代码块中，形如：
```
block1
	block2
```
选中block2所在行按`shift + tab`可以取消block2的缩进

但形如：
```
block1
    block2
```
则无法做到

因为后者是使用空格缩进的

在从vscode粘贴代码时，由于配置了把tab置换为4个空格，所以复制到思源中的代码无法通过`shift + tab`进行缩进

### Expected result

对于前置`四个空格`而非`一个tab符`的代码行也能使用`shift + tab`进行缩进

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

不重要

**Comment by 88250** [comment]
抱歉实现不了，建议在 IDE 里排版好以后粘贴，关联 https://github.com/siyuan-note/siyuan/issues/9437
