### ISSUE TITLE
数据库视图中多选项的筛选条件增加“与”逻辑

### ISSUE THREAD

**Issue by QMike0** [siyuan-note/siyuan#11764]
### In what scenarios do you need this feature?

当前数据库对于多选项筛选条件中只包含“或”和“非”、以及“空”和“非空”，不包含“与”：
![image](https://github.com/siyuan-note/siyuan/assets/43239563/601c601d-d0bc-41e9-bb27-6527dc1a27bb)
筛选时若需要同时包含多个关键词，则无法实现。所以建议增加“与”

### Describe the optimal solution

在现有四个筛选类型基础上增加“与”

**Comment by TCOTC** [comment]
Duplicate of #10550
