### ISSUE TITLE
新建文件夹 文件夹所在位置自动折叠

### ISSUE THREAD

**Issue by reedtop** [siyuan-note/siyuan#1176]
### 描述问题 Describe the problem
新建文件夹后  新建的文件夹所在的父级文件夹自动折叠, 会把新建的文件夹收缩起来,无法看到  需要点开父级文件夹才可以看到新建的文件夹

影响使用体验和效果

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/668
