### ISSUE TITLE
（块引）创建文档异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11776]
### 数据库创建文档异常

使用新建的工作空间导入：[测试笔记本.sy.zip](https://github.com/user-attachments/files/15917784/sy.zip)

该数据库创建的文档很不正常：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/14443440-f9d1-4808-b231-b52bf804df02)

关联：#11773

**Comment by TCOTC** [comment]
在测试 #11731 的过程中形成了这样的数据库，但不清楚具体是我的什么操作造成的

**Comment by TCOTC** [comment]
在新建了一个数据库尝试复现的时候出现了一次（之后没有复现成功过）：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/850f50eb-8fde-4677-b102-7b0456562c58)

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/622f4340-fa9d-4eeb-99e8-94ae781183e9)

**Comment by TCOTC** [comment]
刚说完又复现了一次：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6597c6df-4ae4-4717-8c23-236641c643a8)

**Comment by 88250** [comment]
是在 v3.1.0-dev4 上测试的吗？

**Comment by TCOTC** [comment]
刚刚用 F3 选中文本创建子文档的时候也出现了这个问题，应该不只是数据库的问题

![image](https://github.com/siyuan-note/siyuan/assets/78434827/41d8d698-231b-4ccb-9b82-fe0605b9a4b6)

**Comment by 88250** [comment]
收到，可能是重构块树的细节有问题，稍后排查。
