### ISSUE TITLE
改进空文档显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11770]
### In what scenarios do you need this feature?

新建文档的时候，正文首行可以加一行浅灰色文本，比如 `输入文本，或按下 "/" 插入元素` ：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/abe1a739-ea59-4e84-83fb-08d06587bb6b)

### Describe the optimal solution

类似这样的效果：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ec6dea04-f27c-45bb-add3-6bd14f7b2f51)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c95293dc-038c-4700-a222-6de4744f3351)

**Comment by 88250** [comment]
这个之前加过，后来去掉了，后面考虑这个 https://github.com/siyuan-note/siyuan/issues/10528

**Comment by TCOTC** [comment]
这个 issue 就是从 #10528 衍生出来的嘛

**Comment by 88250** [comment]
不考虑只加提示了。
