### ISSUE TITLE
云端空间上限减小了

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#11779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/32903588/5cf383c9-bf7e-4db8-be3a-98ccfcb02fbb)

之前是16g，现在变15.5了

### Expected result

修复

### Version environment

```markdown
- Version: 3.0.17
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
账号问题请通过邮件联系 845765@qq.com 谢谢
