### ISSUE TITLE
数据库主键新建文档后及时刷新主键

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11771]
### 数据库主键新建文档后及时刷新主键

新建文档后想立刻打开文档，但点快了之后主键就保持为纯文本了：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/897afbb6-9921-44f5-95c3-3c33b96afd46)

**Comment by 88250** [comment]
这个改动不拉进版本了。
