### ISSUE TITLE
关系图全屏后隐藏最小化按钮

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11774]
### In what scenarios do you need this feature?

放在一起容易点错：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/f839cc2e-6705-40bc-bc78-1492ee2ea775)

### Describe the optimal solution

关系图全屏后，将两个最小化按钮分隔远一些、并在中间加一条分隔线

还可以改一下按钮文案，比如改为 `最小化关系图` ：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/24ed9991-447d-4b0f-8236-663f2c8733cd)

### Other information

https://ld246.com/article/1718895962507

**Comment by zxkmm** [comment]
thx! i still felling that it's probably better to remove that icon/function or use another icon tho.

**Comment by TCOTC** [comment]
在学英文？

**Comment by zxkmm** [comment]
不是只是这里外国人多点所以😛

**Comment by Vanessa219** [comment]
Mac 上没有这个问题，还是换一个图标吧。有适合的图标推荐么？

**Comment by zxkmm** [comment]
还是建议全屏时候不显示这个最小化按钮，因为不符合操作逻辑。
而且改了这个最小化按钮如果不改动其他侧栏功能的最小化按钮又感觉改动太大。如果只改这一个最小化按钮，又让学习成本更大。
全屏时候这个按钮表现和取消全屏类似。感觉没有任何必要，还会把这个全屏关系图的操作搞出两种状态，小白可能不好理解怎么切换查看关系图的全屏和不全屏的逻辑。

**Comment by zxkmm** [comment]
然后如果采用这个建议的话，那个“关系图全屏后又最小化”的配置还需要删掉，不然如果之前关系图是全屏的用户就退不出这个全屏设置了。

**Comment by Vanessa219** [comment]
> 然后如果采用这个建议的话，那个“关系图全屏后又最小化”的配置还需要删掉，不然如果之前关系图是全屏的用户就退不出这个全屏设置了。

这个好像没有影响，点击全屏切换退出就可以了。

**Comment by zxkmm** [comment]
> > 然后如果采用这个建议的话，那个“关系图全屏后又最小化”的配置还需要删掉，不然如果之前关系图是全屏的用户就退不出这个全屏设置了。
> 
> 这个好像没有影响，点击全屏切换退出就可以了。

我指的退不出这个状态指的是，如果用户以前用过这个最小化按钮，以后每次唤起关系图的界面，关系图就会以全屏显示。取消全屏以后可以退出，下次再唤起关系图依然是全屏显示。回退不到侧栏显示的状态
以上说的是针对如果真的采纳建议移除了最小化图标的情况

**Comment by zxkmm** [comment]
好像重启以后就可以了，等我仔细看看

**Comment by Vanessa219** [comment]
`取消全屏以后可以退出，下次再唤起关系图依然是全屏显示`  好像没有问题，等我提交以后用最新代码看看吧

**Comment by zxkmm** [comment]
好的，谢谢V大

**Comment by 88250** [comment]
这个改动不拉进版本了。
