### ISSUE TITLE
内容块动态查询嵌入 SQL 模式问题

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1177]
### 描述问题 Describe the problem

同样的查询代码，搜索能搜到；使用!{{test}} 也能搜到，但是
`!{{SELECT * FROM blocks WHERE content LIKE '%test%'}}`
就不行。

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/37007969/104978492-e3b8aa80-5a3c-11eb-9b08-a11a0fc57899.png)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by zhangjl-sjtu** [comment]
不只是markdown，content也一样的问题
![image](https://user-images.githubusercontent.com/37007969/104985051-081b8380-5a4b-11eb-9a5e-0286f3b57fab.png)

**Comment by zhangjl-sjtu** [comment]
测试了一下，中文环境下搜 %测试% 搜不到结果，其他的中文没问题；
%English% 搜英文好像都不行

**Comment by 88250** [comment]
你好，我这里在目前的最新版 v0.6.41 上重现不了，麻烦试下这个版本，谢谢。

![issue](https://user-images.githubusercontent.com/873584/105018806-657df780-5a80-11eb-87b7-87dae7eb449b.gif)
