### ISSUE TITLE
Refactor the blocktree storage

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11773]
重构块树存储

## 动机

之前的块树存储结构是自己实现的文件存储，通过散列分散在 256 个 msgpack 文件中，启动时从这些文件加载块树到内存中，并每隔 5s 将变更的块树写入文件。

目前遇到的问题：

* 数据量较大后，启动时读取块树结构较慢
* 定时落盘存在风险，某些情况下可能会造成块树丢失

## 方案

从散列存储 msgpack 文件（工作空间/temp/blocktree/00-ff.msgpack）改为使用 SQLite 存储（工作空间/temp/blocktree.db）。

这样能解决前面提到的问题：

* 启动时不再需要加载到内存
* 通过数据库事务提升安全性（SQLite WAL）

**Comment by TCOTC** [comment]
能提高启动速度吗？

**Comment by wy16W2pIilK1xgqN** [comment]
有兴趣由 SQLite 切换到DuckDB。
刚刚准备发这个的提议，写了一堆，卡网卡没了😿

**Comment by 88250** [comment]
> 能提高启动速度吗？

能，不过提升有限。

**Comment by Soltus** [comment]
应该也能降低内核退出概率

**Comment by Temacc0531** [comment]
尝鲜了一下，启动速度快挺多🤩

**Comment by AvoidantPerDis** [comment]
感觉启动是快了，日常编辑卡了不少，特别是刷闪卡的时候（1000张左右)

**Comment by Soltus** [comment]
安卓端好像反而更慢了

**Comment by 88250** [comment]
@AvoidantPerDis 打开开发者工具看看是哪个请求卡。

**Comment by AvoidantPerDis** [comment]
> @AvoidantPerDis 打开开发者工具看看是哪个请求卡，另外还需要提供一下内核日志。

![recording](https://github.com/siyuan-note/siyuan/assets/154863885/0aa8cee6-d42b-4449-8b9f-d8802e367baa)
[system-log.zip](https://github.com/user-attachments/files/15926929/system-log.zip)

**Comment by AvoidantPerDis** [comment]
卡了能有1分钟

**Comment by TCOTC** [comment]
@AvoidantPerDis 看一下是哪个请求卡住了

**Comment by AvoidantPerDis** [comment]
> @AvoidantPerDis 看一下是哪个请求卡住了

我刚刚关掉插件自查了一下，应该是番茄的闪卡优先级插件导致的，不过优先级我刚需

**Comment by TCOTC** [comment]
去仓库提个 issue 问问看

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c3537683-84e2-4175-b098-dc3da176553b)

**Comment by 88250** [comment]
@AvoidantPerDis 从块标打开属性面板看看 getBlockAttrs 的耗时

**Comment by AvoidantPerDis** [comment]
> @AvoidantPerDis 从块标打开属性面板看看 getBlockAttrs 的耗时。
> 
> 另外，你之前那个录屏看不到最新请求，请求一直是最上面的：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/341753910-9f739ab4-6b4c-4456-a9ab-562f85c047bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzQ0MDEsIm5iZiI6MTcxODk3NDEwMSwicGF0aCI6Ii84NzM1ODQvMzQxNzUzOTEwLTlmNzM5YWI0LTZiNGMtNDQ1Ni1hOWFiLTU2MmY4NWMwNDdiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMjQ4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjRiOTBmNDI5ODNlNzg0NzkwN2RhNmZiZGVmOWM4NWY5ZTk4NjJmMDlhOWViNGE5OTNmNjNlYzZmY2ZhYTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YMyItJHcVV0mTRgD9FNJ-TeVtcAKqHnqqUShfFEQ58A)

![image](https://github.com/siyuan-note/siyuan/assets/154863885/4c019d3a-1c23-467b-8fdd-611df36c6944)
属性面板秒开的

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/1c2f3e64-d3a8-48c5-a2d4-a2aff599fe9a)
[Uploading 127.0.0.1.zip…]()

**Comment by IAliceBobI** [comment]
之前出现过读写接口都串行，后来把只限制了写接口。现在看起来好像读接口也串行了。


来个批量属性查询的接口可以缓解。  #11786

**Comment by AvoidantPerDis** [comment]
![recording](https://github.com/siyuan-note/siyuan/assets/154863885/404f6003-6e94-45be-9e16-1cd6790bad00)
这是上一版的速度，虽然也慢但是至少快一半
[127.0.0.1 (2).zip](https://github.com/user-attachments/files/15928107/127.0.0.1.2.zip)

**Comment by AvoidantPerDis** [comment]
这个应该也可以用的以后闪卡的不同flag排序

> 之前出现过读写接口都串行，后来把只限制了写接口。现在看起来好像读接口也串行了。
> 
> 来个批量属性查询的接口可以缓解。 #11786

**Comment by 88250** [comment]
改进了一些性能，等新版本发布后各位帮忙测试看看。

**Comment by AvoidantPerDis** [comment]
关联列搜索好像变卡了

**Comment by 88250** [comment]
录屏看下请求耗时

**Comment by AvoidantPerDis** [comment]
> 录屏看下请求耗时

好像是最新dev的事，之前dev没有，而且整体都比较卡

**Comment by 88250** [comment]
那应该不是 dev7 改动导致的，dev7 没有做过相关改动。

不过刚刚找到一个细节优化点，等 dev8 再测测，谢谢。

**Comment by AvoidantPerDis** [comment]
> 那应该不是 dev7 改动导致的，dev7 没有做过相关改动。
> 
> 不过刚刚找到一个细节优化点，等 dev8 再测测，谢谢。

感觉多页签的情况还是可以优化的，最近期末周开好几个大文档，都不敢开侧边的大纲面板了

**Comment by zxhd863943427** [comment]
看了下blocktree.db的内容，似乎都是blocks里已有的内容？为啥要单独存一份？

**Comment by 88250** [comment]
帮忙测试下只用主库的性能。



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 12, 2024 18:49 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Refactor the blocktree storage (Issue#11773)




 
看了下blocktree.db的内容，似乎都是blocks里已有的内容？为啥要单独存一份？

**Comment by 88250** [comment]
@zxhd863943427 对了，有个重要原因就是 blocks 是异步写入的，存在较大延迟，而 blocktree 要求即时写入，所以不能直接用 blocks 库表。
