### ISSUE TITLE
改进公众号剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11781]
https://mp.weixin.qq.com/s/pIlATZG0nsbuGQZJGOXUzQ

这几部分不需要剪藏下来：

01

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6b890fc3-8a19-4809-bbbd-9f48c52b4466)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3477fdda-8d5c-4cff-a8b8-3f10490b825d)

02

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d2a58698-101a-4e33-be0d-1356822498e4)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/344f21be-f65d-43a4-a8ff-b8ec6d2b4a8d)

**Comment by 88250** [comment]
稍后改进，需要升级剪藏扩展。

**Comment by 88250** [comment]
稍后改进，需要升级剪藏扩展到 v1.2.17

**Comment by TCOTC** [comment]
@88250 这个剪藏丢了一些内容：

https://mp.weixin.qq.com/s/d74mmYONl63e31C4jVJWBA

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3ee0c311-5925-41de-aeb5-a1f39ff3c17b)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/652b931f-487c-4839-be91-f60ed81f3d4d)

**Comment by 88250** [comment]
稍后改进，需要升级剪藏扩展到 v1.2.18

**Comment by TCOTC** [comment]
后面部分的图片没剪藏到下来：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/973352b1-7060-4a59-b784-32838fa9ebb4)

**Comment by 88250** [comment]
稍后改进，需要升级剪藏扩展到 v1.2.19
