### ISSUE TITLE
Allow users to switch between tablet mode and mobile mode

### ISSUE THREAD

**Issue by ylsislove** [siyuan-note/siyuan#11789]
请求添加个设置项，允许用户自己切换平板模式/手机模式

### In what scenarios do you need this feature?

将XREAL Air2 AR眼镜接上Android设备，在AR空间下可以以横屏打开思源笔记app，但此时是界面显示的是手机模式。如果能切换成平板模式的话，AR眼镜+蓝牙键鼠+思源笔记，可以达到一个很爽的办公体验~

### Describe the optimal solution

添加个设置项，允许用户自己切换平板模式/手机模式

### Describe the candidate solution

在手机开发者选项里将“最小宽度”360dp改成600dp，重新打开思源笔记，界面居然会显示平板模式。但此时手机文字和图案会缩小，回到主界面的手势操作也会异常，所以只能重新把600dp改成360dp了。这个方案只能算是曲线救国的方案，还是希望D大能添加个设置项，允许用户自己切换平板模式/手机模式。

**Comment by Soltus** [comment]
LGTM

**Comment by KuiyueRO** [comment]
我也买了xreal!! 你真是个天才，我怎么没想到

**Comment by KuiyueRO** [comment]
我们暴力一点

`window.location.href = "http://127.0.0.1:6806/stage/build/desktop/";`

**Comment by KuiyueRO** [comment]
这样就可以了，打开移动端自动加载为desktop，但加载时间变长了，因为相当于加载两次

```javascript
"use strict";
const siyuan = require("siyuan");

const DESKTOP_LOCATION = "http://127.0.0.1:6806/stage/build/desktop/";

class RedirectToDesktopPlugin extends siyuan.Plugin {
    async onload() {
        console.log("插件已加载");
        this.checkAndRedirect();
    }

    async onunload() {
        console.log("插件已卸载");
    }

    checkAndRedirect() {
        console.log("当前 Location:", window.location.href);
        if (window.location.href.includes("/stage/build/mobile/")) {
            console.log("重定向到新的 Location:", DESKTOP_LOCATION);
            window.location.href = DESKTOP_LOCATION;
        } else {
            console.log("当前 Location 已为桌面模式，无需重定向。");
        }
    }
}

module.exports = RedirectToDesktopPlugin;

```

**Comment by 88250** [comment]
请考虑通过插件实现吧，感谢。
