### ISSUE TITLE
Improve page number for exporting PDF annotation hyperlinks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11780]
### 导出 docx 后，PDF 标注的链接打不开

pdf?p=n 的这种链接是打不开的：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7638b86e-ff96-4531-820a-1bcb9e6ab07a)

**Comment by 88250** [comment]
合并上 https://liuyun.io/article/1719212163338 一起处理，将 `?p=xxx` 改为 `#page=xxx`
