### ISSUE TITLE
修改块命名后立即刷新对应的动态锚文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11787]
### In what scenarios do you need this feature?

修改块命名后需要立即刷新对应的动态锚文本，还有刷新嵌套的锚文本（还有嵌套的嵌套的嵌套的……锚文本）

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/43585684-998a-478f-8a90-39c4f07e4ee8)

### Describe the optimal solution

修改块命名后刷新对应的动态锚文本

**Comment by 88250** [comment]
后面放在 https://github.com/siyuan-note/siyuan/issues/8234 中考虑吧。

**Comment by TCOTC** [comment]
对于 #8234 有很好的方案吗？

**Comment by 88250** [comment]
还没有的

**Comment by TCOTC** [comment]
那这个 issue 的问题有解决方案吗？

**Comment by 88250** [comment]
等后面统一考虑啊，这里不单独处理了。

**Comment by TCOTC** [comment]
今天遇到了动态锚文本跟块命名不同的情况，刷新文档也没用，很怪。之后看看怎么复现
