### ISSUE TITLE
blockquote 中多个代码块之间出现多余空行

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1178]
### 描述问题 Describe the problem

![s1](https://user-images.githubusercontent.com/69628966/104978894-e5cf3900-5a3d-11eb-9e87-98b4a7e2372d.gif)

### 版本环境 Version environment

* 版本 Version：0.6.3
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by yeshaopeng6688** [comment]
ps：d大有空尽快提供缩放界面的快捷键设置把，这个全局快捷键alt + m，和我自己的快捷键冲突很久了。

**Comment by Vanessa219** [comment]
空行是关闭再打开就有么？

**Comment by yeshaopeng6688** [comment]
> 空行是关闭再打开就有么？

对的。

**Comment by 88250** [comment]
@yeshaopeng6688 界面隐藏的快捷键请关注 https://github.com/siyuan-note/siyuan/issues/899 估计一时半会处理不了
