### ISSUE TITLE
Add plugin function `getModelByDockType`

### ISSUE THREAD

**Issue by dapaning** [siyuan-note/siyuan#11782]
### In what scenarios do you need this feature?

https://ld246.com/article/1718804848764

### Describe the optimal solution

https://ld246.com/article/1718804848764

**Comment by pisceswb** [comment]
希望有人能开发一个点击标签页自动展开文档树的插件（只展开活动标签页的文档树，关闭其它文档树）
https://ld246.com/article/1717306355600/comment/1717574856007#comments
https://ld246.com/article/1717770566008/comment/1717804982345#comments

**Comment by IAliceBobI** [comment]
补充一下：

根据内容块或者文档块 ID，展开文档树，并定位。

可以选择是否折叠其他已经展开的文档。

@dapaning 是这个吧。

**Comment by dapaning** [comment]
> 补充一下：
> 
> 根据内容块或者文档块 ID，展开文档树，并定位。
> 
> 可以选择是否折叠其他已经展开的文档。
> 
> @dapaning 是这个吧。

是的

**Comment by Vanessa219** [comment]
可参照 https://github.com/siyuan-note/plugin-sample/blob/a315fedef530f0ae76a74bcad5d72b6a92fcc3f0/src/index.ts#L373

**Comment by TCOTC** [comment]
@Vanessa219 能在展开特定文档的同时，折叠在该文档路径外的其他文档吗？

**Comment by Vanessa219** [comment]
可以先折叠父层，再展开特定文档。也可以遍历后折叠不需要的文档。
