### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by star2k** [siyuan-note/siyuan#11784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker version install plugin show incompatible

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/9582078/feab99c8-1b30-44f8-85b6-e8697a5e1050)

### Version environment

```markdown
- Version: 3.0.17
- Operating System: win10 22h2
- Browser (if used):chrome 120
```

### Log file

![image](https://github.com/siyuan-note/siyuan/assets/9582078/0945f8b2-7899-43fd-b809-c8aa7e40eecd)

**Comment by TCOTC** [comment]
是否兼容是由插件作者决定的。文档高亮搜索插件我会在下个版本取消限制，但实际上能否正常使用我就不知道了。

**Comment by 88250** [comment]
正如 @TCOTC 所说，我们关闭了。
