### ISSUE TITLE
括号自动补全

### ISSUE THREAD

**Issue by BitBute01** [siyuan-note/siyuan#11795]
### In what scenarios do you need this feature?

在自由输入下，当输入左半括号时，一般都需要补充右半括号，而且在代码和公式环境下非常实用

### Describe the optimal solution

可以参考obsidian和Vscode以及typora等编辑器和md笔记软件的功能实现

**Comment by TCOTC** [comment]
我搜狗输入法的这个功能在思源里不起效果，就很奇怪

![image](https://github.com/siyuan-note/siyuan/assets/78434827/efb20144-c9d2-45db-b864-b41bbb6e64cc)

**Comment by 88250** [comment]
符号补全主要看输入法的支持，不考虑在应用内实现了，感谢反馈。
