### ISSUE TITLE
HTML 块内脚本无法执行

### ISSUE THREAD

**Issue by ocean0117** [siyuan-note/siyuan#11796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/51983215/0fdfb2a4-8284-4b26-966a-f4701bf64733)
尽管我已经打开 HTML 块内脚本许可，但仍旧无法执行脚本中的代码。
我用了个简易的 JavaScript 检测脚本。
````html
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var jsSupported = document.getElementById('js-supported');
        jsSupported.innerHTML = 'JavaScript is supported!';
        jsSupported.style.color = 'green';
    });
</script>
</head>
<body>
    <div id="js-supported" style="font-size: 24px; text-align: center; margin-top: 50px;">
        Checking JavaScript support...
    </div>
    <noscript>
        <div style="font-size: 24px; text-align: center; margin-top: 50px; color: red;">
            JavaScript is not supported on your browser.
        </div>
    </noscript>
</body>
````
在 Siyuan 中展示结果如图所示：
![image](https://github.com/siyuan-note/siyuan/assets/51983215/78424734-166c-4e9e-907d-6ada30ec6166)
正常的j执行结果应该是：
![image](https://github.com/siyuan-note/siyuan/assets/51983215/67246251-6549-481d-963d-6454c966679e)

### Expected result

希望能执行 HTML 的 js 脚本

### Version environment

```markdown
- Version: 3.0.17
- Operating System: Windows 11 23H2
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/15937273/siyuan.log)

**Comment by Vanessa219** [comment]
DOMContentLoaded 已经结束才进行监听就会无效。可以换成 alert 就可以看到是否执行了。
```
<div>
<script>
alert(1)
    document.addEventListener('DOMContentLoaded', function() {
        var jsSupported = document.getElementById('js-supported');
        jsSupported.innerHTML = 'JavaScript is supported!';
        jsSupported.style.color = 'green';
    });
</script>
</head>
<body>
    <div id="js-supported" style="font-size: 24px; text-align: center; margin-top: 50px;">
        Checking JavaScript support...
    </div>
    <noscript>
        <div style="font-size: 24px; text-align: center; margin-top: 50px; color: red;">
            JavaScript is not supported on your browser.
        </div>
    </noscript>
</body>
</div>
```
