### ISSUE TITLE
数据库日期，可以选择仅显示日期吗？

### ISSUE THREAD

**Issue by V7kb** [siyuan-note/siyuan#11790]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/166938054/d9cb73c9-c65f-4e5b-88cb-b801c34ff78c)

### Describe the optimal solution

1

**Comment by TCOTC** [comment]
意思是想要默认填充不填充具体时间吗？→ 也就是 #10955 的需求

**Comment by 88250** [comment]
同上

**Comment by V7kb** [comment]
> 意思是想要默认填充不填充具体时间吗？→ 也就是 #10955 的需求

是的。目前只能一条条的设置不显示时间，很反人类。

**Comment by V7kb** [comment]
> 同上

同上
