### ISSUE TITLE
切换工作空间时关闭界面会关闭内核导致启动失败

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11794]
切换工作空间时关闭界面会关闭内核导致启动失败

这个情况时不时出现（偶尔点快了），希望能让第二个工作空间正常启动：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/2469c03f-4ec5-4605-9cf3-2b63dc68766c)

**Comment by 88250** [comment]
这个没有办法，要等内核进程完全启动以后才能退出之前的进程。
