### ISSUE TITLE
在文档末尾点击以新建块，会跳回到文档开头

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11798]
### 在文档末尾点击以新建块，会跳回到文档开头

1. 打开一个长文档，并且这个文档的末尾不是一个空的段落块
2. 在前面有内容的块里点一下
3. 关闭文档
4. 再次打开文档
5. 拉到文档最后，点击一下，就会跳回到文档开头

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/39f05a70-616d-4dc8-a88e-9502f554b33c)

**Comment by 88250** [comment]
这个改动不拉进版本了。
