### ISSUE TITLE
3.1.0 dev5 数据库编辑卡顿

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

3.1.0 dev5 数据库编辑卡顿
1. 悬浮块所属的数据库角标，要等很久才显示浮窗
2. 编辑单选、多选列，要等很久才弹出选项

退回dev1之后表现正常

### Expected result

正常编辑数据库

### Version environment

```markdown
- Version: 3.1.0 dev5
- Operating System: Win11
- Browser (if used):
```

### Log file

no need

**Comment by TCOTC** [comment]
我这里跟以前一样快，你重建索引试试有无改善？还有就是录屏看看

**Comment by 88250** [comment]
我这里也重现不了问题。请打开开发者工具，在 Network 中看看触发的请求，最好录屏演示，谢谢。

**Comment by 88250** [comment]
dev6 已经发布，请用该版本测试，如果还有问题请录屏反馈，issue 先关闭了，谢谢。
