### ISSUE TITLE
拖拽块到数据库中，如果有重复，应该将焦点移动到已有的条目上

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11804]
拖拽块到数据库中，如果有重复，应该将焦点移动到已有的条目上

直接在数据库里绑定的时候是有的，但拖拽块到数据库里就没有：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/1e511eda-8dc1-4820-a24c-dee9168d0a2a)

**Comment by JokeenZhang** [comment]
还要高亮

**Comment by Vanessa219** [comment]
单元格无法选中，那就选中行？

**Comment by 88250** [comment]
这个改动不拉进版本了。
