### ISSUE TITLE
开启全局只读后，可编辑文档在“大纲”中调整标题顺序，会触发文档从“可编辑”变为“只读”

### ISSUE THREAD

**Issue by hihaojie** [siyuan-note/siyuan#11808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

开启全局只读后，可编辑文档在“大纲”中调整标题顺序，会触发文档从“可编辑”变为“只读”。

### Expected result

只读模式下，拖动标题后，文档仍保持可编辑状态。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/25772523/792857b6-5b8e-4bb7-af4c-5ef23416134b

### Version environment

```markdown
- Version: 3.0.17
- Operating System: Windows10、Windows11
- Browser (if used):
```

### Log file

None

**Comment by 88250** [comment]
这个改动不拉进版本了。
