### ISSUE TITLE
链接与提及有相同内容

### ISSUE THREAD

**Issue by wfwuestc** [siyuan-note/siyuan#1180]
### 描述问题 Describe the problem

![1](https://user-images.githubusercontent.com/16739946/104981265-44e37c80-5a43-11eb-9dcb-55c5ffcb0dd5.png)
版本 0.6.3
如图 **Vue 3** 已经链接到了**2021 小组计划**文件中，但提及还会显示同一文件位置，且转换为内容块引用按钮可以重复点击。
之后**2021 小组计划**文件会出现如下结果
![result](https://user-images.githubusercontent.com/16739946/104981477-a6a3e680-5a43-11eb-9067-0679a3209fc0.png)

### 期待的结果 Expected result
以引用的链接不会在提及出现

**Comment by wfwuestc** [comment]
update：在使用` - [ ]`代办 时才会出现这样的问题

**Comment by 88250** [comment]
感谢反馈，我们合并到 https://github.com/siyuan-note/siyuan/issues/1161 中一起处理。
