### ISSUE TITLE
思源未来会适配鸿蒙next系统吗？

### ISSUE THREAD

**Issue by hypjyx** [siyuan-note/siyuan#11803]
### In what scenarios do you need this feature?

因为现在的设备都是华为的，马上就更新next系统了，会不会以后就无法使用思源笔记。

### Describe the optimal solution

希望作者能发布一个鸿蒙版，思源真的很好用~

**Comment by TCOTC** [comment]
不会专门适配

**Comment by 5kyfkr** [comment]
D大上次说的是看能不能正常编译，我也希望能适配下

**Comment by TCOTC** [comment]
编译不了就没办法了

**Comment by hypjyx** [comment]
希望能继续用吧，现在所有的笔记都转移到思源上了，买个会员真香啊。

**Comment by 88250** [comment]
感谢反馈，如果能适配的话会尽量去做的。

**Comment by hypjyx** [comment]
感谢D大
