### ISSUE TITLE
提供数据库模板列可用的获取原文顺序的方法

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#11806]
## 场景
我的听课笔记按多级标题整理在一个文档，平时和期末时会记录考点收集在一个数据库内，但创建和修改时间排序顺序对不上，几百条记录又不可能手打，sql的hpath只到文档名，面包屑无法查询，标题自动编号插件可行性最好，但是无法解决非标题块

## 结论
我试了各种办法，感觉目前破坏性较小的是提供块在原文的行号，or提供hpath到一级标题。

### Describe the candidate solution

比较难做但是效果更好的就是提供面包屑列表了

**Comment by AvoidantPerDis** [comment]
也要考虑到会有其他文档的块加入，行号其实不是很可行

**Comment by 88250** [comment]
这个应该是没有办法做到了，只能通过手动排序整理了。
