### ISSUE TITLE
已绑定块的条目不显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11805]
https://github.com/siyuan-note/siyuan/commit/65f24b376ee927d50608e93f2d693d144922f27e

https://ld246.com/article/1719117529369

[24年刑法复试题目.sy.zip](https://b3logfile.com/file/2024/06/24年刑法复试题目-YNCIQqM.sy.zip)

https://github.com/siyuan-note/siyuan/assets/78434827/e8ff34fa-7d33-4547-a1a8-0b80e94a5613

**Comment by 88250** [comment]
感谢反馈，稍后修复。
