### ISSUE TITLE
新建文档后，在行首无法按 Enter 换行

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11818]
https://ld246.com/article/1719278335958

可以复现，但不是在「文档开头」有这个问题，而是在新建文档后出现这个问题

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/de62155b-cee7-4b74-aae8-451c725858b9)

**Comment by pisceswb** [comment]
👍 @TCOTC

**Comment by pisceswb** [comment]
经测试，任意粘贴内容后，所在行的行首都无法使用回车换行

**Comment by pisceswb** [comment]
> 经测试，任意粘贴内容后，所在行的行首都无法使用回车换行

也是在新建文档中有问题。关闭标签页重新打开就好了。未生效的换行，在重新打开后也会生效。

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/11798
