### ISSUE TITLE
某网页剪藏不到文本、复制粘贴也不行

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11813]
反馈：https://ld246.com/article/1719240750976

网页：https://guangdong.chinatax.gov.cn/gdsw/zjfg/2024-06/05/content_7c599bba225741429407f88ff5b83ddf.shtml?_refluxos=a10

**Comment by 88250** [comment]
感谢反馈，下个版本改进。

这个改动不拉进版本了。

**Comment by TCOTC** [comment]
@88250 选中标题和第一行文本复制后粘贴不出标题：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/15a49a23-44f7-448b-b654-d6718d642bab)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/368bfc36-5f62-4358-ab99-f4bfd9274b8e)

**Comment by 88250** [comment]
收到，稍后改进。
