### ISSUE TITLE
启用拖动文字功能

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#11817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

再提**启用拖动文字功能**的可行性。
能否在拖动文字后，使用“**优化排版**”功能，自动优化变动的一个或两个块，消除拖动文字导致的格式问题。
或将选择权交给用户，移动后，可能导致格式不正确，只要不丢失数据就行。用户自己选择是否开启。

### Expected result

启用拖动文字功能

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
1
```

### Log file

1

**Comment by TCOTC** [comment]
> 消除拖动文字导致的格式问题

听起来做不到

**Comment by 88250** [comment]
这个实在做不到，以后如果有可能会考虑的，谢谢。
