### ISSUE TITLE
内核中断的一个可能的原因，和解决建议

### ISSUE THREAD

**Issue by windoversnow** [siyuan-note/siyuan#1181]
![image](https://user-images.githubusercontent.com/75920913/104991106-efb26580-5a58-11eb-9da7-7cbaa29fd8e9.png)
https://s3.ax1x.com/2021/01/19/sgYzw9.png

![image](https://user-images.githubusercontent.com/75920913/104991125-fb9e2780-5a58-11eb-84dd-bf9ab9f4aea6.png)
https://s3.ax1x.com/2021/01/19/sgtMfP.png

**Comment by 88250** [comment]
非常感谢你帮助我们排查该问题 https://github.com/siyuan-note/siyuan/issues/996 https://github.com/siyuan-note/siyuan/issues/1036

v0.6.5 中我们将对读写配置文件做一次优化，谢谢。

**Comment by windoversnow** [comment]
还有一个问题，我之前说，我有个文件特别容易引发崩溃，而且这个文件常常**修改了也不会自动保存**

今天巧合，因为一些别的原因用到这个文件，我把这个文件发到了手机，忘了导出普通md文件，所以在手机看时，夹杂着好多{: id="**********"}

我突然发现，有一个id是**null**
就是这样{: id="null"}
这是出现在一个列表段落的末尾，我发现列表中每一行都有自己的id，整段列表还有一个总id，就是这个总id，不知为何变成了null
![image](https://user-images.githubusercontent.com/75920913/104994536-9994f080-5a5f-11eb-87c7-425164cd224b.png)
https://s3.ax1x.com/2021/01/19/sgBKHO.png

我删掉了这个{: id="null"}以及列表各行的id，让思源重新读取这个文件，自动生成一遍新的id后，问题就解决了

**Comment by deerainw** [comment]
@windoversnow 

真的是这样，我之前也是有一个文件修改了但不会自动保存，虽然只发生过一次，但我记忆力比较强所以还是记下来了 😂

看到你说的就去搜了一下，这个文件里面果然有 id 为 null 的情况：

![image](https://user-images.githubusercontent.com/32661922/105000010-c26db380-5a68-11eb-98f5-b338810d6bd1.png)

**Comment by 88250** [comment]
@windoversnow @deerainw 这个问题可能是之前的版本的缺陷，请再帮忙留意一下新版中是否还会出现，谢谢。

**Comment by 88250** [comment]
我关闭这个 issue 了，减少 conf.json 写入在 v0.6.4 中发布改进，谢谢。

**Comment by FastStonewkx** [comment]
解决了吗，0.7
![image](https://user-images.githubusercontent.com/36177654/106348551-1480c580-6302-11eb-9868-8212d1d602a2.png)刚解压的最新版，白屏，一个月白屏两次。不能每次让我重启吧

**Comment by FastStonewkx** [comment]
方了，重启无效了。永久白屏了

**Comment by 88250** [comment]
@FastStonewkx 麻烦发一下 .siyuan 配置文件夹给我 845765@qq.com 然后删除该文件夹重启，谢谢。

**Comment by windoversnow** [comment]
> 方了，重启无效了。永久白屏了

可能得你自己排查下有什么冲突软件 我目前的非常稳定 这么多天来 就崩了一次 还自己想测试下软件极限 连续刷新文件树 给刷崩了 平时用再没出问题 可能我自己找到了自己的冲突软件了吧


顺便提个别的问题 专家模式不能搜索？不能复制插入图片？我还没更新最新版 不知是不是还是有这样的问题

**Comment by 88250** [comment]
@windoversnow 是的，专家模式暂时只能编辑文本。

**Comment by FastStonewkx** [comment]
[siyuan.log](https://github.com/siyuan-note/siyuan/files/6014435/siyuan.log)
谢谢，已经恢复了。但是应该不是软件冲突。重启好几次了，目前是删除了.siyuan文件夹。升级到最新版。

**Comment by FastStonewkx** [comment]
应该是我自己安装了go环境。但是删除那个文件夹，配置就都复位了，需要重新设置。当然我是白嫖用户，还是挺香的
![image](https://user-images.githubusercontent.com/36177654/108589825-40401a00-739b-11eb-8a53-d51c301efc7c.png)

**Comment by 88250** [comment]
@FastStonewkx 看上去可能是权限问题。
