### ISSUE TITLE
wav 音频无法播放

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#11810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

音频样本 [1719221043856-7d062gqvlny-20240624172403-1gzmpio.zip](https://github.com/user-attachments/files/15953258/1719221043856-7d062gqvlny-20240624172403-1gzmpio.zip)

![图片](https://github.com/siyuan-note/siyuan/assets/28727933/9d2af878-822c-4047-8fc0-97926c1d32fd)

### Expected result

可以正常播放

### Version environment

```markdown
- Version: v3.0.17dev4
- Operating System: windows
- Browser (if used):
```

### Log file

none

**Comment by TCOTC** [comment]
我这里正常播放

v3.1.0-dev6 Win10

**Comment by 88250** [comment]
500 报错的话可以看下内核日志是否有记录，先关闭了。

**Comment by 2234839** [comment]
报错日志会以  serve.go: 这样的形式吗，我没有找到相关日志

**Comment by 88250** [comment]
应该是的，或者看看 `E 2024` 开头的

**Comment by 2234839** [comment]
没有找到相关日志

**Comment by 2234839** [comment]
@88250  我这里又出现了，日志文件中没有记录
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/35a3da3d-d4b0-4068-a2b8-e769e57ed885)

**Comment by 88250** [comment]
有点难定位，方便的话请帮忙 debug 调试看看。
