### ISSUE TITLE
希望增加设置文档图标的api

### ISSUE THREAD

**Issue by dapaning** [siyuan-note/siyuan#11811]
### In what scenarios do you need this feature?

工作流中，会频繁新建若干固定类别的文档。
希望在新建的时候，就设置好图标。而不是手动设置。

### Describe the optimal solution

类似设置笔记本图标的api
![image](https://github.com/siyuan-note/siyuan/assets/66105129/be2e61c7-d42d-41dd-814b-3ed7a2d512a6)

**Comment by 88250** [comment]
文档图标请使用 `http://127.0.0.1:6806/api/attr/setBlockAttrs`

可以抓包看看：

![image](https://github.com/siyuan-note/siyuan/assets/873584/896d702f-b6e7-40b3-b81d-63dbb3e733f0)
