### ISSUE TITLE
知乎动图剪藏问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11812]
反馈：https://ld246.com/article/1719225893018

剪藏：https://zhuanlan.zhihu.com/p/82116922

有两个动图，剪藏不下来：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/93f9e5ad-b5f8-4fb0-88c2-6785f6292d0a)

**Comment by 88250** [comment]
感谢反馈，这个改进就不拉进版本了。

**Comment by TCOTC** [comment]
@88250 知乎的图片标题能单独处理一下吗？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/97265970-ee3d-48ca-ab3b-29d0dde35684)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/08c415eb-3ba1-46a7-8b21-8e736f299571)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f8e75b38-b6b9-4b89-83ed-4deac120c01b)
