### ISSUE TITLE
剪藏知乎图片模糊

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11826]
### In what scenarios do you need this feature?

https://zhuanlan.zhihu.com/p/82116922

直接剪藏下来是模糊的，但复制图片链接到思源里再下载网络图片就是清晰的

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ee472951-dfab-4120-bba1-52b38bb7cd54)

两者的本地文件对比：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/df887c2d-034f-4a04-8034-9d52fee3b578)

### Describe the optimal solution

。

### Other information

https://ld246.com/article/1719225893018

**Comment by 88250** [comment]
感谢反馈，稍后改进。

这个改动不拉进版本了。

**Comment by 88250** [comment]
PS 需要升级剪藏扩展。

**Comment by TCOTC** [comment]
@88250 GIF 剪藏成网络图片了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/98cddaf4-1d1f-4744-ab76-a9bf8a78191e)

**Comment by 88250** [comment]
等更新剪藏扩展。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年6月30日(周日) 中午1:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 剪藏知乎图片模糊 (Issue #11826)




 
@88250 GIF 剪藏成网络图片了：
 
image.png (view on web)

**Comment by TCOTC** [comment]
还有比这更高的版本吗？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9e06486b-98d1-41f0-bc2d-a1ddb70fab7c)

**Comment by 88250** [comment]
早上才发布了一个版本，我在外面有点记不清了，如果发布日期是今天的话晚点我回去再看看，谢谢。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年6月30日(周日) 中午1:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 剪藏知乎图片模糊 (Issue #11826)




 
还有比这更高的版本吗？
 
image.png (view on web)

**Comment by TCOTC** [comment]
看了代码提交，这个拓展是最新的

**Comment by 88250** [comment]
https://zhuanlan.zhihu.com/p/82116922 我这里用这个页面测试，剪藏扩展 v1.2.16 可以剪藏 gif 图片。

**Comment by TCOTC** [comment]
那就奇怪了，我这里是剪藏出两个网络图片：

`https://pic2.zhimg.com/v2-75dc0f59d2630e85a79090c1c7cd7dd5_r.jpg`

`https://pic1.zhimg.com/v2-d68b6f8e6d57a7bed9c8fd5e85cca56c_r.jpg`

**Comment by 88250** [comment]
我这里还是无法重现，应该是这两个图片：

![image](https://github.com/siyuan-note/siyuan/assets/873584/f2121044-c316-4d04-8f76-d10b5d11917f)

**Comment by 88250** [comment]
要不等下个 dev 发布以后再测试看看，谢谢。

**Comment by TCOTC** [comment]
那就之后再试试。

另外补充一张截图：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/18b52f8f-6b8b-46c1-8f5b-59066b1737ad)

**Comment by 88250** [comment]
收到

**Comment by TCOTC** [comment]
dev9 没问题了
