### ISSUE TITLE
使用过程中，发现跨笔记本移动文档未能实现

### ISSUE THREAD

**Issue by derek778** [siyuan-note/siyuan#1182]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
mac os big sur 11.1

请尽量清晰精准地描述你期待的功能和应用场景。

使用过程中，发现同一个笔记本内的文件夹互相拖拉md文件，是可以自动移动到其他文件夹的，很方便。

但是如果有几个笔记本，需要移动整理文档以后，无此功能。最后逼不得已得进源目录，手动剪切粘贴来实现相关的功能。

希望能够实现跨笔记本移动md文件的功能。会更方便整理分错类或者临时分类的文档

**Comment by 88250** [comment]
你好，我们之前有过考虑 https://github.com/siyuan-note/siyuan/issues/45 目前暂时没有改进计划，见谅。
