### ISSUE TITLE
选中内容，按回车键，再使用Ctrl Z撤销，会有bug

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#11825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下图，选中56，按回车键，再按Ctrl+Z撤销，会得到“undefined”
![image](https://github.com/siyuan-note/siyuan/assets/104658457/bd4fa9a5-55ad-43fa-a3cd-61606d7a0d11)

### Expected result

修复

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by pisceswb** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/104658457/f140dc0f-6b7c-44bd-8053-4e87ecc79756)

**Comment by pisceswb** [comment]
在新建文档，或新移动后文档中，会出现该bug。【】创建待办事项也不可用。
文档关闭重开后，会正常

可能与这个相关，https://github.com/siyuan-note/siyuan/issues/11818

**Comment by TCOTC** [comment]
我这里可以复现这两个问题

**Comment by 88250** [comment]
请等 v3.1.0-dev8 发布后在测试看看。

**Comment by TCOTC** [comment]
我这里没有这个问题了

**Comment by 88250** [comment]
那就先关闭了，谢谢。
