### ISSUE TITLE
提高块标折叠/展开响应速度

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11828]
### In what scenarios do you need this feature?

包括列表和标题，在点击块标的时候响应都不大快，使用快捷键就很快：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/b0313e41-19f7-4e95-a67d-d99ec1729d0e)

### Describe the optimal solution

。

### Other information

https://ld246.com/article/1719383530493

**Comment by Vanessa219** [comment]
这个需要等待请求返回，按照标题展开的优化方式进行。

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by TCOTC** [comment]
@Vanessa219 我发现点折叠展开的时候光标会变一下，我觉得需要和其他地方一样统一为不变的。

录屏里显示不出来变化后的光标，但意思是那么个意思：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/70803f3e-9f84-4570-94e0-15913d9f67fb)

**Comment by Vanessa219** [comment]
指的是点击后光标消失么？

**Comment by TCOTC** [comment]
是会变成另一个形状的光标：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/fa168c72-a301-406d-b78a-3ded2e54943e)

**Comment by Vanessa219** [comment]
我这里点击的时候不会，要拖拽的时候才会。目前拖拽已经修改，还麻烦再看看。
