### ISSUE TITLE
特殊文件名导致图片404

### ISSUE THREAD

**Issue by liun1221** [siyuan-note/siyuan#11823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

导入md文档发现某些图片不显示，确定图片存在，尝试手动复制图片进文档均不显示。调试发现404，后修改图片名可正确显示，猜测是文件名导致。尝试siyuan-v103.0.17-win和siyuan-v202406242313-win均能复现。
文件名：imagesurl=https%3A%2F%2Fwww.dbi-services.com%2Fblog%2Fwp-content%2Fuploads%2Fsites%2F2%2F2022%2F01%2FElasticsearch-index-shards-20240625150429-3rnv0vw.png
![image](https://github.com/siyuan-note/siyuan/assets/65383735/41d40cf9-613d-4be1-81d9-b4064b87d18e)

### Expected result

图片太多，手动修改太麻烦，希望修复bug

### Version environment

```markdown
- Version: 103.0.17
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
把图片粘贴/拖入笔记的时候是会移除文件名中的某些字符的

**Comment by liun1221** [comment]
> 把图片粘贴/拖入笔记的时候是会移除文件名中的某些字符的，你的这个图片是怎么带有这些字符的？剪藏吗？

是md文档导入的，自动导入引用的图片，我尝试手动将图片粘贴近文档，也是这个情况。

**Comment by 88250** [comment]
请上传原始导入 md 文件数据以便调试。

**Comment by liun1221** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/65383735/528c43d9-fb55-4c1e-aa02-65a1a8ffc25e)
[test.zip](https://github.com/user-attachments/files/16047281/test.zip)
原始文档过大，我弄了一个测试的md。可以复现。

**Comment by 88250** [comment]
收到，我们看下如何改进，谢谢。

**Comment by 88250** [comment]
已经定位到问题，稍后改进。

这个改动不拉进版本了。
