### ISSUE TITLE
在折叠状态下修改标题层级异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11829]
在折叠状态下修改标题层级异常

1. 在展开之后原来子层级的标题块就不显示了
2. 重新打开文档可以显示了，但原来子层级的标题要先折叠再展开才能显示后面的内容

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/a2f7952a-b559-4634-b9b1-d297d2a51ca4)

**Comment by Vanessa219** [comment]
修改后展开

**Comment by Vanessa219** [comment]
已改进，不拉进版本
