### ISSUE TITLE
希望数据库导出模版时，记住其属性面板中的字段顺序

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11820]
### In what scenarios do you need this feature?

不然导入数据库模版后，又要调一遍属性面板中的字段顺序

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
确实，使用模板之后再绑定块，块属性面板中的数据库字段顺序恢复默认了

**Comment by AvoidantPerDis** [comment]
用复制副本行不行啊？

**Comment by 88250** [comment]
感谢反馈，v3.1.0 加上。

这个改动不拉进版本了。
