### ISSUE TITLE
忽略虚拟引用

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11827]
https://ld246.com/article/1719328894581

> * data/.siyuan/indexignore：用于忽略索引
> * data/.siyuan/searchignore：用于忽略全局搜索
> * data/.siyuan/refsearchignore：用于忽略引用搜索

使用这三种忽略方式后，其中的关键词需要排除虚拟引用

**Comment by 88250** [comment]
仅加入 searchignore 吧，其他两个不需要：

* indexignore 如果有配置，那么默认就不会索引，所以不可能被搜索到
* refsearchignore 是针对 refs 的，不放到 blocks 上

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by TCOTC** [comment]
indexignore 是在同步时忽略，还是任何时候都忽略？

**Comment by 88250** [comment]
任何时候都忽略，不进入SQLite 索引。
