### ISSUE TITLE
标签面板增加搜索标签的功能

### ISSUE THREAD

**Issue by zhangjunquan** [siyuan-note/siyuan#11822]
### In what scenarios do you need this feature?

我想查看某个标签的使用次数，但是标签太多了

### Describe the optimal solution

可以在标签栏加一个搜索标签的功能么，对标签列表进行过滤。
![image](https://github.com/siyuan-note/siyuan/assets/9114193/2f733f20-f699-4823-aac5-b8c2b2fbde40)

**Comment by TCOTC** [comment]
Duplicate of #11039
