### ISSUE TITLE
代码块内双击文本的逻辑不符合常见用法

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#11833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下，新建一个代码块，里面写一些文本，当双击文本时，会选中文本和后面的空格 
![image](https://github.com/siyuan-note/siyuan/assets/97490782/03afe694-6b56-43ad-b10b-1da77ea88651)

### Expected result

一般的逻辑，都是只选中文本本身。多选中空格很干扰操作，只能手动选中这块文本，或者复制出来再删掉空格

### Version environment

```markdown
- Version: 3.0.17
- Operating System: windows 11
- Browser (if used):
```

### Log file

应该不需要

**Comment by 88250** [comment]
请参考 https://ld246.com/article/1616425150081

**Comment by heheda123123** [comment]
用了这么久还真不知道
