### ISSUE TITLE
v3.1.0-dev7  创建dailynote不加载模板

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

v3.1.0-dev7  创建dailynote不加载模板，创建的dailynote始终为空白文档

### Expected result

能加载模板

### Version environment

```markdown
- Version: 3.1.0 dev7
- Operating System: Win 11
- Browser (if used):
```

### Log file

no need

**Comment by 88250** [comment]
我这里测试正常，请录屏补充重现步骤。

**Comment by Achuan-2** [comment]
模板路径和文件没有问题，因为我改为dev1，创建dailynote就是正常的加载模板

**Comment by 88250** [comment]
需要描述一下重现步骤，谢谢。

**Comment by TCOTC** [comment]
关闭文档再打开有内容吗？

**Comment by TCOTC** [comment]
我也复现了

**Comment by 88250** [comment]
我这里还是重现不了……

**Comment by TCOTC** [comment]
[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/26ef317d-3977-45a2-89f1-c61ed4084e3e)

**Comment by 88250** [comment]
@TCOTC 模板路径那里不要加 `/data/templates/`

![image](https://github.com/siyuan-note/siyuan/assets/873584/b78d05a6-c806-407b-9a84-1734d67d03b3)

**Comment by TCOTC** [comment]
噢，好久没用过日记了，确实只用填文件名就行了。

那我没能复现

**Comment by Achuan-2** [comment]
那等新版本我再看看吧，之前数据库的问题也是https://github.com/siyuan-note/siyuan/issues/11834，等下个dev版本就好了

**Comment by 88250** [comment]
dev8 已经发布，请帮忙测试。

**Comment by Achuan-2** [comment]
依然不会不加载模板
路径改为默认的`/日记/{{now | date "2006/01"}}/{{now | date "2006-01-02"}}`，也是一样（我之前用`/Diary/{{now | date "2006/2006-01"}}/{{now | date "2006-01-02 Mon"}}`）,不会是日记模板的问题，因为同样的设置，我在之前版本是可以正常使用的
![Clip_2024-06-30_16-13-23](https://github.com/siyuan-note/siyuan/assets/60436214/3ac946f5-0194-4ea4-979e-25226421d043)

而且发现如果指定的dailynote路径不存在，不会自动生成

![Clip_2024-06-30_16-07-31](https://github.com/siyuan-note/siyuan/assets/60436214/c90491d1-4ca6-4308-9ea7-d148bb83ce5f)

**Comment by Achuan-2** [comment]
log文件
[siyuan.log](https://github.com/user-attachments/files/16043712/siyuan.log)

**Comment by 88250** [comment]
从日志上看，确实有相关报错，代码上面暂时看不出问题（是很早之前的代码）。

如果能在新的工作空间重现该问题，麻烦将工作空间打包上传，多谢。

**Comment by Achuan-2** [comment]
新建了一个工作空间就正常了，新建日记能加载模板，日记的父文档不存在也不会报错

**Comment by 88250** [comment]
不大好排查，还是需要工作空间打包数据才好定位。

**Comment by Achuan-2** [comment]
![Clip_2024-07-01_00-20-47](https://github.com/siyuan-note/siyuan/assets/60436214/9a5c3503-f057-4e02-b4d7-5abf726abc0f)
报错的工作空间，删除今日日记后，还会报文件不存在，无法创建日记
打包工作空间我需要看看怎么缩小文件数量。

**Comment by 88250** [comment]
好的，这个可能比较耗时，麻烦多帮忙试试。（和 assets 应该没有关系）

**Comment by Achuan-2** [comment]
我日常只用一个笔记本，这个笔记本有大概4000个文件，我把这个笔记本关闭，另一个新笔记本就能正常创建日记了

**Comment by 88250** [comment]
麻烦试试 dev9 是否还能重现问题。

**Comment by Achuan-2** [comment]
> 麻烦试试 dev9 是否还能重现问题。

还是有这个问题的

**Comment by 88250** [comment]
刚刚修复了一个相关问题，请等 dev10 再测试看看，谢谢。

**Comment by 88250** [comment]
dev10 已经发布，请帮忙测试。

**Comment by Achuan-2** [comment]
1. 创建日记能否正常加载模板：✅
2. 删除日记路径，能否创建路径，并生成日记：✅
目前测试感觉没有问题了

**Comment by 88250** [comment]
好的，可以关闭 Issue 了，谢谢。



---原始邮件---
发件人: "Jixiong ***@***.***&gt;
发送时间: 2024年7月5日(周五) 上午9:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] v3.1.0-dev7  创建dailynote不加载模板 (Issue #11834)




  
创建日记能否正常加载模板：✅
 
删除日记路径，能否创建路径，并生成日记：✅
  
目前测试感觉没有问题了

**Comment by jaccobian** [comment]
弱弱的问一下，我的思源笔记中都没有新建日记、存放路径，以及模板路径

<img width="2717" height="1637" alt="Image" src="https://github.com/user-attachments/assets/33639d5f-c49e-4220-b5e0-0d87d19f6c60" />

**Comment by TCOTC** [comment]
右键笔记本 - 设置

**Comment by jaccobian** [comment]
TCOTC真是及时雨，回复好快
