### ISSUE TITLE
在折叠状态下修改标题层级后撤销出现异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11837]
在折叠状态下修改标题层级后撤销出现异常

转换之后都很正常，但撤销之后就一直在转圈：（带子层级标题和不带子层级标题都是一样的）

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/e35223d3-ccb0-471a-9d88-03e4fbd628f8)

**Comment by Vanessa219** [comment]
已在 https://github.com/siyuan-note/siyuan/issues/11829 中进行修改
