### ISSUE TITLE
配置 `新建文档存放位置` 后调用 `createDocWithMd` 速度较慢

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11835]
### 新建文档速度慢

https://ld246.com/article/1719412186431

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ac1cdea3-067c-421e-bd4f-1d770664d7bc)

**Comment by 88250** [comment]
700ms+ 应该是正常范围，就不做再深入的排查了。

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/assets/78434827/9c9fb841-b686-4103-9e06-0fa4ad393e6a

**Comment by 88250** [comment]
配置了 `新建文档存放位置` 后调用 `createDocWithMd` 会比较慢，后面看看如何优化。
