### ISSUE TITLE
希望数据库的全选是全选所有行

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11839]
### In what scenarios do you need this feature?

目前只是全选加载出来的所有行，如果200条，最大行数50，岂不是要连续加载4次，然后才能全选

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
我的建议是给这里增加更多选项：（200、300、全部……）

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6d0ec495-3806-49ff-b9f8-e4faaf160a69)

**Comment by 88250** [comment]
增加 `全部` 吧 @Vanessa219

**Comment by 88250** [comment]
这个改动不拉进版本了。
