### ISSUE TITLE
使用 API 设置文档图标后，文档树上的文档图标需要及时更新

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11836]
https://ld246.com/article/1719458740178

**Comment by 88250** [comment]
需要重新展开文档树。

**Comment by TCOTC** [comment]
这个跟 #11633 有类似的地方吗？#11633 不需要重新展开文档树

**Comment by 88250** [comment]
不一样，#11633 是前端内置实现的逻辑。内核 API 没有刷新前端的能力。
