### ISSUE TITLE
在同步过程中关闭思源，会提示「退出时同步失败」

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11847]
在同步过程中关闭思源，会提示「退出时同步失败」

https://ld246.com/article/1719484005406

可以复现：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/224bf496-6c0b-47e6-b55e-df96cd3db422)

**Comment by 88250** [comment]
感谢反馈，稍后改进。

这个改动不拉进版本了。
