### ISSUE TITLE
替换文本后不重新加载界面

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11844]
替换文本后不重新加载界面

https://ld246.com/article/1719478251222 第一点

**Comment by yutianxhs25** [comment]
这个必须改进啊。刷新背后的逻辑是什么？为什么要刷新？难不成改了文件名要刷新？

**Comment by 88250** [comment]
因为思源支持多窗口，为了保证一致性所以目前必须刷新。后续如果能改进的我我们尽量想办法，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月30日(周日) 晚上9:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 替换文本后不重新加载界面 (Issue #11844)




 
这个必须改进啊。刷新背后的逻辑是什么？为什么要刷新？难不成改了文件名要刷新？

**Comment by yutianxhs25** [comment]
> 因为思源支持多窗口，为了保证一致性所以目前必须刷新。后续如果能改进的我我们尽量想办法，谢谢。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月30日(周日) 晚上9:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 替换文本后不重新加载界面 (Issue #11844) 这个必须改进啊。刷新背后的逻辑是什么？为什么要刷新？难不成改了文件名要刷新？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

然而，不应该、没有理由合上文档树啊。
最好是不刷新，就像word、typora那样。
如果不得不刷新的话，刷新之前，应当记录下文档树的展开状态，刷新完毕后再回复文档树的状态吧。

**Comment by 88250** [comment]
@yutianxhs25 你说的没错，之前已经有提议需要保留文档树展开状态 https://github.com/siyuan-note/siyuan/issues/10652 后面尽量考虑，谢谢。

**Comment by 88250** [comment]
这个 issue 我们先关闭了，感谢提议和讨论。

**Comment by TCOTC** [comment]
> 因为思源支持多窗口，为了保证一致性所以目前必须刷新。

这个没法判断吗？如果替换的文档只打开了一个页签，那就只刷新那一个页签就够了

**Comment by 88250** [comment]
不好判断，所以先统一刷新处理。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年6月30日(周日) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 替换文本后不重新加载界面 (Issue #11844)




  
因为思源支持多窗口，为了保证一致性所以目前必须刷新。
  
这个没法判断吗？如果替换的文档只打开了一个页签，那就只刷新那一个页签就够了

**Comment by TCOTC** [comment]
@88250 我发现单个文档打开多页签多窗口时，编辑内容块、拖动大纲、通过 API 插入块都是可以直接同步不用重载的，为什么替换文本就需要重载？

**Comment by TCOTC** [comment]
@88250

**Comment by 88250** [comment]
似乎有办法了，稍后改进看看。
