### ISSUE TITLE
折叠与聚焦功能体验改进

### ISSUE THREAD

**Issue by xxxxds** [siyuan-note/siyuan#11845]
### In what scenarios do you need this feature?

点击折叠按钮时容易碰到聚焦按钮，单点折叠按钮可能会触发聚焦事件，或者容易碰到菜单按钮，触发菜单
![image](https://github.com/siyuan-note/siyuan/assets/88675581/8dad622c-13c2-4b73-b681-439280f94713)
![image](https://github.com/siyuan-note/siyuan/assets/88675581/2e6b7851-b56d-49f7-b883-c98972a8ae3f)
如图所示，菜单、折叠、聚焦三个按钮靠得十分近，而且通常情况下是隐藏的，需要鼠标移动到上面才能看到按钮，盲点容易点到旁边的按钮。
这一点在移动端尤为严重，因为移动端上，手指比较粗，难以精确点到折叠按钮。
在使用频率上，折叠按钮远比聚焦和菜单按钮用得多，因此将按钮放在这个位置会造成许多不便

### Describe the optimal solution

幕布软件对此的处理要更好一些，折叠按钮和菜单按钮的间距拉得更大一点，聚焦按钮需要连点两下才能进入聚焦，而不是像思源笔记这样一点就进入聚焦
![幕布桌面端截图](https://github.com/siyuan-note/siyuan/assets/88675581/a848d673-32aa-4e8c-83cd-8aece004ed97)
在幕布的移动端上，折叠按钮被移动到了右边
![幕布移动端截图](https://github.com/siyuan-note/siyuan/assets/88675581/fb4aac10-be46-491c-8f27-05349c288daa)
这样点击的时候就不会碰到别的按钮。

### Describe the candidate solution

方案1：无论是桌面还是移动端，统一将折叠按钮移动到右边，设置双击聚焦按钮才能进入聚焦
方案2：桌面端拉大几个按钮的间距，移动端还是将折叠按钮移到右边，设置双击聚焦按钮才能进入聚焦
个性化方案：在设置里提供几个按钮的配置项，配置是否显示菜单、折叠按钮，是否启用聚焦功能，或者调控按钮是在文字的左边还是右边。

### Other information

个人感觉最容易提升体验的就是直接把聚焦按钮改为双击进入聚焦，实现起来也比较简单，桌面端把click事件改为dblclick事件，移动端用touchstart和touchend模拟一下就好

**Comment by TCOTC** [comment]
建议关闭这个开关：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f2372156-3573-4ad6-b365-b44c5a24c661)

**Comment by 88250** [comment]
感谢反馈，移动端暂时不会考虑做大的调整了；桌面端的话目前这方面的误触反馈不多，所以就也忽略吧。

我们关闭这个 issue 了，谢谢。
