### ISSUE TITLE
Improve boot index checking

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11842]
https://ld246.com/article/1719453366362

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by TCOTC** [comment]
相应的文案是不是也要改一改

**Comment by 88250** [comment]
嗯，稍后改进。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/17610 中改进，所以不再需要弹出 `上次使用后未完成数据索引，请执行一次 [设置 - 关于 - 重建索引]。` 消息提示了。
