### ISSUE TITLE
背景色遮挡了文字

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11841]
### 背景色遮挡了文字

https://ld246.com/article/1719475781063

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c9d2154e-2d26-4259-949f-3b76659ee864)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/53ffea62-be94-478d-8dd1-06c06a83896c)

**Comment by Vanessa219** [comment]
没太明白是什么意思？

<img width="238" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/5fa2476f-cf21-42ca-a748-560da4334802">

**Comment by Vanessa219** [comment]
是不是设置过什么？我这里是正常的

<img width="128" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/8de8b5cf-11f7-442c-b2ba-04fb03d1eac2">

**Comment by TCOTC** [comment]
我这里的字体是能叠在一起的，或许是字体不同？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c9f2e87a-f9d4-4aed-8c7a-354cb6961e8f)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cf026212-5cac-4a70-b9a3-6f73d43a5104)

**Comment by Vanessa219** [comment]
嗯，Windows 的字体问题。

**Comment by TCOTC** [comment]
@Vanessa219 日语的字体需不需要一起改？

#11322 把日语用的字体分离出来了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/4eb4c036-f4a3-45ed-805a-284eef903e93)
