### ISSUE TITLE
编辑标题块内容后不应该折叠大纲

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11843]
编辑标题块内容后不应该折叠大纲

https://ld246.com/article/1719478695166

**Comment by yutianxhs25** [comment]
能改进吗能改进吗？我追到这里来问了。

**Comment by 88250** [comment]
你好，我们会考虑的，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月30日(周日) 晚上9:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 编辑标题块内容后不应该折叠大纲 (Issue #11843)




 
能改进吗能改进吗？我追到这里来问了。

**Comment by 88250** [comment]
这个改动不拉进版本了。
