### ISSUE TITLE
Database template does not calculate Rollup values

### ISSUE THREAD

**Issue by KrzysztofChrisMaciejczuk** [siyuan-note/siyuan#11849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Using a database template with .action{ addf .val1 .col1 }, where val1 columns is a number and col1 is a Rollup column, which points to another table with a numeric column, does not sum the values. Adding more numeric columns within the local table works, but the Rollup column is always ommited.

It worked prior to 3.0.14

### Expected result

Numeric Rollup columns should be also summed when using within a template.

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/106653996/721f1025-3f3f-44ca-b5b8-6ca636df5d2e)

### Version environment

```markdown
- Version: 3.0.17
- Operating System: Ubuntu 24.04 
- Browser (if used): Firefox 127.0.2 64bit
Hosted via web app
- Host OS: Android (version unknown; latest on Samsung Fold 3)
```

### Log file

I will add log file later. Issue created on PC, while log file is on mobile.

### More information

I am using web app hosting and connect via LAN to my mobile. Though it does not work on host device as well.

**Comment by TCOTC** [comment]
maybe `.action{ addf .val1 (index .col1 0) }`

#11029

**Comment by KrzysztofChrisMaciejczuk** [comment]
Haha, it works :sweat_smile: . I reported because it used to work without the index. For a future reference: where could I find a more complete documentation on the database template language?

**Comment by TCOTC** [comment]
this one: [SiYuan Template Function Guide for Newcomers: Template Syntax + Functions + Markdown Block Syntax](https://liuyun.io/article/1718014557873)
