### ISSUE TITLE
Ordered list block number not refreshed

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#11840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

有序列表项序号未刷新

![GIF 2024-6-27 16-07-23](https://github.com/siyuan-note/siyuan/assets/101307399/500d37a5-e810-48ad-ac3c-198049444276)

### Expected result

刷新有序列表项序号，从1开始重排

### Version environment

```markdown
- Version: v3.0.17
- Operating System: Windows 11
```

### Log file

null

**Comment by TCOTC** [comment]
我感觉正常，复制的是什么粘贴的就是什么

**Comment by TCOTC** [comment]
不过我有一个问题，为什么需要这样子的列表：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/475cf923-1e10-491e-9ada-f7654e5ebea7)

**Comment by TCOTC** [comment]
提供一个我的思路：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/6de7a7bc-cdc0-480a-894f-3cbabb5d45ea)

**Comment by Temacc0531** [comment]
> 不过我有一个问题，为什么需要这样子的列表

最外层的12是我的模板里面带出来的，BCD是我实际填写的内容，因为复制一个列表项没法在末尾直接接入（会变成两个独立列表项），所以我直接粘贴到第一个项里面再`shfit+tab`

**Comment by TCOTC** [comment]
Shfit+Tab 之后应该会刷新编号的

**Comment by 88250** [comment]
或者转换列表为无序，再转换有序。

这个 issue 就关闭了，感谢反馈。

**Comment by Temacc0531** [comment]
所以这个是特性不是缺陷吗😂

**Comment by TCOTC** [comment]
不是缺陷。粘贴会刷新序号的话才是缺陷

**Comment by Temacc0531** [comment]
> 不是缺陷。粘贴会刷新序号的话才是缺陷，这样的话有些操作会实现不了

不关粘贴的事情，我是说shift+tab之后最外层的应该刷新才对，不是按照第二层的序号

**Comment by TCOTC** [comment]
你得像我这样粘贴：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d475a368-6a4c-4a0c-a7f2-cd06c11e7eaf)

> shift+tab之后最外层的应该按原本序号重新刷新才对，因为shift+tab前最外层的是从1开始的，而不是按照第二层的从2开始

你这个情况下就是删除了第一层的 1. ，然后将 2. 变为首个序号
