### ISSUE TITLE
改进按左右方向键时隐藏菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11846]
目前按左右方向键只会隐藏菜单，我希望在隐藏菜单之后能再移动一格：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/da175da8-01c6-4d41-8109-871f23502ad2)

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/a2fa91a1-e3b4-4cb6-8158-624680050aa9)

**Comment by Vanessa219** [comment]
需要先取消，光标在另字后面的话，也是是要搜索包含`另`的操作。

**Comment by TCOTC** [comment]
我的意思是，比如说输入 `、` 之后再按 `→` ，这个时候会隐藏菜单，我希望隐藏菜单之后光标能再往右移动一格移到 `另` 的右边

**Comment by 88250** [comment]
这个改动不拉进版本了。
