### ISSUE TITLE
闪卡功能最近有迭代计划吗？

### ISSUE THREAD

**Issue by V7kb** [siyuan-note/siyuan#11855]
### In what scenarios do you need this feature?

记得以前说过要重构闪卡，但近期好像没有动静了。看最近几个版本的更新说明，也没有关于闪卡的优化。
想了解下，闪卡重构的规划是往后排了还是被放弃了？如果是往后安排了，大概在什么时候可以启动重构？

### Describe the optimal solution

1

**Comment by 88250** [comment]
v3.1.0 发布以后需要稳定一段时间，可能需要 3 个月左右吧，具体请关注 https://github.com/siyuan-note/siyuan/issues/10471 谢谢！

**Comment by V7kb** [comment]
> v3.1.0 发布以后需要稳定一段时间，可能需要 3 个月左右吧，具体请关注 #10471 谢谢！

好的，辛苦
