### ISSUE TITLE
3.1.0-dev7 mjx-container节点latex剪报公式识别异常

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#11852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

示例
https://mp.weixin.qq.com/s/RX9gT6m5Qj2EU-zCN8TwgQ
与[#11743 ] 类似的问题，也是一个节点里包了个svg，然后这个节点的data-formula里是latex
```
<mjx-container jax="SVG" display="true" role="presentation" tabindex="0" ctxtmenu_counter="8" data-formula="f'(x,y_0)|_{x=x_0}=\lim_{h\to 0}\frac{f(x_0+h,y_0)-f(x_0,y_0)}{h}" style="overflow-x: auto;outline: 0px;display: block;text-align: center;margin: 15px 0px;">
```

### Expected result

公式可以正确复制到笔记里

### Version environment

```markdown
- Version: 3.1.0-dev7
- Operating System: Win10 x64
- Browser (if used): Chrome 120.0.6099.225 (正式版本) （64 位）
```

### Log file

日志我清理了一下重新导入网页剪报, 还是似乎只有一条
W 2024/06/28 18:40:33 blocktree.go:576: save block tree [size=2.36 MB] to [D:\SYNote\temp\blocktree], elapsed [4.38s]

### More information

辛苦开发者们看看

_No response_

**Comment by 88250** [comment]
感谢反馈，稍后改进。

**Comment by ruin1990** [comment]
@88250 D大，您好，我更新到3.1.0-dev8，刚才测试了一下，给的链接地址末尾latex的似乎有问题
后面的那段叉积的latex看起来有点问题，应该是begin和end这里识别的问题,具体看下图
![image](https://github.com/siyuan-note/siyuan/assets/6134040/9973a0e8-f669-4e73-997f-8d87c805981e)
跳转到那段的快速搜索文字： “根据叉积的定义，可得：”

**Comment by 88250** [comment]
感谢反馈，稍后改进。
