### ISSUE TITLE
根据标签或者属性自动汇总到数据库

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#11857]
### In what scenarios do you need this feature?

我在使用Obsidian的时候经常利用标签和名称来汇总笔记，但是Siyuan不能自动汇总只能手动添加文档。

### Describe the optimal solution

最佳的解决方案：可以根据标签汇总笔记，同时对关系图谱更新更多的过滤模式和颜色模式

这是期望的效果 
![image](https://github.com/siyuan-note/siyuan/assets/52444119/7c2e4bc0-988d-4c87-b9ce-35ed9f9eb798)
![image](https://github.com/siyuan-note/siyuan/assets/52444119/64af6576-3302-4b18-b109-50b78ca9ada3)

**Comment by TCOTC** [comment]
可以到 #10863 反馈

**Comment by 88250** [comment]
这个估计得期待相关插件实现了，原生应该不会提供自动汇总能力，感谢反馈。
