### ISSUE TITLE
在标题末尾可以通过`shift+enter`触发软换行编辑效果，实际无作用

### ISSUE THREAD

**Issue by hihaojie** [siyuan-note/siyuan#11851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在标题末尾通过 `shift+enter`键可以触发软换行的编辑效果，但实际键入内容时软换行并不生效。

### Expected result

通过`shift+enter`不再触发软换行编辑效果，或者标题支持软换行。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/25772523/cbc9d924-19b1-439f-9276-8368f84faf32)

https://github.com/siyuan-note/siyuan/assets/25772523/0c842eca-285e-4b08-bbb3-f2d84b9e5e6a

### Version environment

```markdown
- Version: 3.0.17
- Operating System: Windows10、Windows11
- Browser (if used):
```

### Log file

none

**Comment by TCOTC** [comment]
dev7 可以复现这个问题，标题块后使用软回车无效

**Comment by Vanessa219** [comment]
已改进，不拉进版本

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by TCOTC** [comment]
@Vanessa219 标题块内不能使用软回车了，按下 Shift+Enter 没有反应

**Comment by 88250** [comment]
嗯，标题元素不支持 Shift+Enter 呃。

**Comment by hihaojie** [comment]
@88250 D大，标题元素是以后都“不支持软换行”了，还是说“只是不支持`shift+enter`”？

如果是前者，现在仍能通过“转换为X级标题”实现“标题软换行”，如果是后者，标题支持软换行，却缺少有效的输入方法
![image](https://github.com/siyuan-note/siyuan/assets/25772523/a3cfbbfc-87e5-450b-b66b-e83d2756af5b)

**Comment by 88250** [comment]
不支持软换行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月1日(周一) 上午8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 在标题末尾可以通过`shift+enter`触发软换行编辑效果，实际无作用 (Issue #11851)




 
@88250 D大，标题元素是以后都“不支持软换行”了，还是说“只是不支持shift+enter”？
 
如果是前者，现在仍能通过“转换为X级标题”实现“标题软换行”，如果是后者，标题支持软换行，却缺少有效的输入方法
 image.png (view on web)

**Comment by hihaojie** [comment]
新版（dev8）仍能通过”转换为X级标题“实现标题软换行的效果，这个需要同步修改：
> ![image](https://github.com/siyuan-note/siyuan/assets/25772523/05a499b4-070d-45f7-92f5-ee74875ae54a)

**Comment by TCOTC** [comment]
> 通过”转换为X级标题“实现标题软换行的效果

@hihaojie 这个是怎么操作的？

**Comment by hihaojie** [comment]
> 这个是怎么操作的？

@TCOTC 添加一个包含软换行的段落块，点击”段落块图标“→”转换为“→”X级标题“

**Comment by TCOTC** [comment]
> 添加一个包含软换行的段落块，点击”段落块图标“→”转换为“→”X级标题“

@88250 确实是，转换之后还是显示软换行的，刷新文档之后才去掉软换行

**Comment by 88250** [comment]
@Vanessa219

**Comment by 88250** [comment]
已经调整，感谢反馈。

**Comment by TCOTC** [comment]
@88250 如果是输入 `# ` 后转换为标题，需要跟使用块标菜单转换为标题一样，不应该把软回车后的文本变成单独的段落块：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/abe75445-d96e-45ba-b7a1-94414c4c482e)

**Comment by TCOTC** [comment]
@88250

**Comment by 88250** [comment]
看了下最多只能做到反过来，即带软换行段落转换标题时分割为两个块，一个标题块一个段落块。

**Comment by 88250** [comment]
尝试改了下，会有其他问题，所以这里还是保持不变吧。
