### ISSUE TITLE
“标签”的光标在编辑模式和只读模式不同

### ISSUE THREAD

**Issue by hihaojie** [siyuan-note/siyuan#11854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

“标签”的光标在”只读模式“下仍可以**点击**弹出”搜索“，和编辑模式效果一致。但”只读模式“的光标为”文本指针“，和”编辑模式“的”手形光标“不同。

### Expected result

“只读模式”和“编辑模式”的光标效果一致，均为“手形光标”，表示该内容“可以点击”。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/25772523/77508cb3-0d93-4df8-af9a-c7f3cb4e3b33)
![image](https://github.com/siyuan-note/siyuan/assets/25772523/5d5134af-ca51-4a8a-ba5e-6ef71e9c132f)

### Version environment

```markdown
- Version: 3.0.17
- Operating System: Windows10、Windows11
- Browser (if used):
```

### Log file

none

**Comment by Vanessa219** [comment]
已修改，不拉进版本
