### ISSUE TITLE
Plugin to ship and running a executable binary like pandoc

### ISSUE THREAD

**Issue by jaar23** [siyuan-note/siyuan#11853]
### In what scenarios do you need this feature?

hi SiYuan dev, 
I'm currently building a plugin for SiYuan. I'm looking for extending the client to execute a executable binary within SiYuan. I know SiYuan ship with pandoc for document conversion. I would like to know the method on how can I ship a binary within the plugin and then able to execute it with from the client. 
Secondly, how can I store any data within SiYuan, normally which folder is recommended? I'm planning to store a sqlite kind of embeded db.

### Describe the optimal solution

The plugin might be heavier to run in the browser, so I would prefer to build a separate binary that is cross platform and can be invoke when required.

### Describe the candidate solution

The binary able to ship with the plugins, and place under `/data/plugins/plugin-A/binary`, while the file can save at the recommended location.

**Comment by 88250** [comment]
Hello, the binary can be packaged in the plugin folder. The data storage directory is recommended to be placed in data/storage/petal/{plugin}/, using the kernel interface `putFile`.
