### ISSUE TITLE
网络视频左上角需要一个小地球

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11856]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/873beabf-b25f-4ec6-9dd6-0ab391bed68e)

**Comment by 88250** [comment]
改成 `资源` 吧？

**Comment by TCOTC** [comment]
但是插入的 PDF 之类的资源文件是统计到「链接」里的，我觉得这个还是用「媒体」

**Comment by 88250** [comment]
我这里测试， IFrame/视频/音频 都没有被计入 图片 中：

![image](https://github.com/siyuan-note/siyuan/assets/873584/32d2fd94-494b-4630-8a07-8a8e9753195b)

**Comment by TCOTC** [comment]
试了一下，同样发现没有计入视频，我怀疑他看错了

**Comment by TCOTC** [comment]
不过我发现另外一个问题，网络图片左上角有个小地球，但网络视频没有：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f707bf2b-2d17-462a-846b-62c13f2cdd56)

**Comment by 88250** [comment]
嗯，只有图片有。这个暂时不动了，网络图片转换本地也是配套这个标识的。

**Comment by TCOTC** [comment]
网络资源文件转换本地也会转换网络视频，为什么不给网络视频也加个标识？

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/b430d60f-bca6-40fa-8699-a86d22e3f539)

资源文件和图片时分开的，资源文件包括了所有超链接的。

**Comment by TCOTC** [comment]
所以为什么不给网络视频也加个小地球标识？不是更方便判断吗？
