### ISSUE TITLE
知乎的图片标题能单独处理一下吗？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11859]
知乎的图片标题能单独处理一下吗？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/97265970-ee3d-48ca-ab3b-29d0dde35684)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/08c415eb-3ba1-46a7-8b21-8e736f299571)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f8e75b38-b6b9-4b89-83ed-4deac120c01b)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/11812#issuecomment-2186878424_

**Comment by 88250** [comment]
感谢反馈，稍后改进，需要升级剪藏扩展。
