### ISSUE TITLE
Reindex notebook and reload UI after data sync if notebook conf changed

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11850]
### 同步后需要关闭在已关闭的笔记本中的文档

https://ld246.com/article/1719500571449

![image](https://github.com/siyuan-note/siyuan/assets/78434827/a92bdc40-e9cc-4a16-bdc3-410f9db64115)

**Comment by woniuxia** [comment]
T佬，辛苦呀，造福大家
