### ISSUE TITLE
pdf页码跳转链接以及pdf内容摘录做笔记，类似于Margin note3

### ISSUE THREAD

**Issue by Asukaleo-aa** [siyuan-note/siyuan#1186]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在阅读pdf文档时，需要快速摘录pdf中的内容到笔记中，并实现笔记块和pdf内容的互相跳转，类似于marginote3和bookxnotepro的核心特征。
所摘录的内容作为块的标题，可根据选项设为默认子级或默认兄弟级。

### 描述最优的解决方案 Describe the optimal solution
具备基本的pdf阅读功能，即：
- 文本高亮
- 文本下划线
- 非文本内容多边形框选
- pdf滚动阅读
- 夜间阅读模式
- 标注后自动保存
md笔记与pdf链接功能：
- 高亮或下划线文本自动复制粘贴到当前md页面，作为子级或者兄弟级的标题（可以加个选项）
- 非文本内容多边形框选内容以图片的形式粘贴到当前md页面，自动生成一个占位的子级或者兄弟级的标题
- 点击上述两种情况生成的块可以跳转到pdf文档的对应标注位置
-  具体情境可参考 [Marginnote3](https://www.marginnote.com/)、[BookxnotePro](http://www.bookxnote.com/)

### 描述候选解决方案 Describe the candidate solution
- pdf滚动阅读
- md文件内嵌pdf页码跳转链接

### 其他信息 Other information
超级无敌非常感谢D大和V姐！！！

**Comment by yanyu2015** [comment]
> ### 你在什么场景下需要该功能？ In what scenarios do you need this function?
> 在阅读pdf文档时，需要快速摘录pdf中的内容到笔记中，并实现笔记块和pdf内容的互相跳转，类似于marginote3和bookxnotepro的核心特征。
> 所摘录的内容作为块的标题，可根据选项设为默认子级或默认兄弟级。
> 
> ### 描述最优的解决方案 Describe the optimal solution
> 具备基本的pdf阅读功能，即：
> 
> * 文本高亮
> * 文本下划线
> * 非文本内容多边形框选
> * pdf滚动阅读
> * 夜间阅读模式
> * 标注后自动保存
>   md笔记与pdf链接功能：
> * 高亮或下划线文本自动复制粘贴到当前md页面，作为子级或者兄弟级的标题（可以加个选项）
> * 非文本内容多边形框选内容以图片的形式粘贴到当前md页面，自动生成一个占位的子级或者兄弟级的标题
> * 点击上述两种情况生成的块可以跳转到pdf文档的对应标注位置
> * 具体情境可参考 [Marginnote3](https://www.marginnote.com/)、[BookxnotePro](http://www.bookxnote.com/)
> 
> ### 描述候选解决方案 Describe the candidate solution
> * pdf滚动阅读
> * md文件内嵌pdf页码跳转链接
> 
> ### 其他信息 Other information
> 超级无敌非常感谢D大和V姐！！！

其实你的想法很好，但是估计很难实现了，产品的路线不同吧估计，其实感觉跟bookxnote打通反而比较可行呢

**Comment by 88250** [comment]
你好，关于 PDF 的编辑操作估计支持不了，我们先简单支持一下 `[foo](assets/xxx.pdf?page=1)` 这样的调整吧，谢谢提议。

https://github.com/siyuan-note/siyuan/issues/1307

**Comment by Asukaleo-aa** [comment]
> 你好，关于 PDF 的编辑操作估计支持不了，我们先简单支持一下 `[foo](assets/xxx.pdf?page=1)` 这样的调整吧，谢谢提议。
> 
> #1307

足够了，非常感谢！

**Comment by GitHubChrischen** [comment]
能否这样操作，不要修改PDF这个源文件，而是把这个修改通过引用或者其他方式把PDF上的注释显示出来，再加上跳转功能，就像上面的页面跳转，显示的是一个连接，这个连接呈现的方式可以是图片（图片可以是注释的部分的截图（比如做了一段文字的高亮，但是不对PDF源文件进行修改，只是保存这个截图））， 点击这个图片可以对PDF的位置进行跳转，跳转的时候用思源笔记打开显示pdf相应位置。  或者是PDF上面相应的文字，点击文字连接到PDF相应位置， 我觉得核心一点就是不能对PDF源文件进行编辑和修改， 只需要保存注释以及注释的引用，并对这些在思源笔记上呈现出来
