### ISSUE TITLE
在图片或公式块上一行按delete键，没有使其上移一行，而是错误删除了下一行的图片或公式块

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#11868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

公式块在第二行，光标在到第一行，按delete键，并没有使公式块上移一行，而是直接将其删除了。
两张图片分别在第一行和第二行时，在第一行末尾按delete键，也有问题。

### Expected result

如果是bug的话，请修复。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/104658457/e725bba8-c58b-4c50-920c-db198e4b1c35

https://github.com/siyuan-note/siyuan/assets/104658457/23698e6d-370d-4b8f-8ca2-5c62fa9e90f2

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by TCOTC** [comment]
- 按 Delete 是删除后面的内容，这是正常的。
- 不过下个版本会改进在空内容块中使用 Delete 的情况：#11732

**Comment by pisceswb** [comment]
> * 按 Delete 是删除后面的内容，这是正常的（向后删除，等同于在下一个块前面删除）；Backspace 才是删除前面的内容。
> * 不过下个版本会改进在空内容块中使用 Delete 的情况：[改进空内容块中使用 `Delete` #11732](https://github.com/siyuan-note/siyuan/issues/11732)

公式块比较少用，没有太大关系。
关键是图片，上下两张图片时，在第一张图片后面按delete，能够把下面的图片移到上面才对。当前响应不合理

**Comment by TCOTC** [comment]
@Vanessa219 需要改进在图片后按 Delete，跟在下一个块前按 Backspace 统一：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/73956f65-4686-44b7-bb4a-94dfff9f884a)

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by pisceswb** [comment]
感觉还是有问题 @Vanessa219 

https://github.com/siyuan-note/siyuan/assets/104658457/4c385acb-f053-4924-b110-09ec07898218

**Comment by TCOTC** [comment]
@Vanessa219 在这里按 Delete 会删除后面的图片而不是文字：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/5b1f7ddd-b251-4c7e-bdef-cc682da87e3c)

**Comment by pisceswb** [comment]
向前删除也有点问题

https://github.com/siyuan-note/siyuan/assets/104658457/e6c164f6-1530-428d-9097-d1c7fd54842c

**Comment by pisceswb** [comment]
@Vanessa219

**Comment by pisceswb** [comment]
设置了图片宽度33%，从外部一次性选中几张图片，复制到思源笔记时，图片不能横向排列，而是一个图片一个块的纵向粘贴，请问是否能改进一下，一次性粘贴的图片放到一个块中就行

**Comment by Vanessa219** [comment]
以上都无法重现，目前还有这种情况么？

多个图片的排练问题参看 https://github.com/siyuan-note/siyuan/issues/7607

**Comment by pisceswb** [comment]
没有问题了，感谢V姐，赞！！ @Vanessa219
