### ISSUE TITLE
移动端下载云端数据快照失败 function not implemented

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#11864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

下载云端数据快照失败。

![aa97c17b62fe05b795be03088db059f](https://github.com/siyuan-note/siyuan/assets/16383685/7231a94a-65d4-4dbe-8b43-d1dfced21701)

![8fe4ce1c225cad6b26da68ca78cf0a4](https://github.com/siyuan-note/siyuan/assets/16383685/98c58091-34a7-416b-a4be-3bd2b7a475ff)

### Expected result

能正常下载。

### Version environment

```markdown
- Version: 3.0.17
- Operating System:  Android
- Browser (if used):
```

### Log file

移动端的日志怎么找呀？

**Comment by 88250** [comment]
请上传系统日志，位于 右侧栏面板 关于 中。

**Comment by 88250** [comment]
从日志上看，6 月 15 号就出现了这个问题，目前还不清楚原因，请等新版本发布后更新看下。

**Comment by woniuxia** [comment]
[system-log (1).zip](https://github.com/user-attachments/files/16158716/system-log.1.zip)
D大，试了两天还是不行，辛苦排查

**Comment by 88250** [comment]
等下个版本再试试。

**Comment by woniuxia** [comment]
[system-log (2).zip](https://github.com/user-attachments/files/16242661/system-log.2.zip)
辛苦D大继续排查

**Comment by 88250** [comment]
目前报错还是这个：

```
function not implemented
```

可能是系统底层缺失了某个函数导致的，一时半会儿没法定位具体问题了，抱歉。

**Comment by woniuxia** [comment]
之前能正常使用的。
那现在安卓端是完全没办法使用的状态。

**Comment by 88250** [comment]
可能是 6 月 15 号时升级系统了？

**Comment by woniuxia** [comment]
D大这个问题可以多打印些异常信息吗？
确认下是手机还是哪的问题，现在安卓端同步不了数据，很难受。

**Comment by 88250** [comment]
已经是打印全部报错信息了，但是定位不到问题。

**Comment by woniuxia** [comment]
😭 那咋办，只能等着我下次更新系统再看看吗？

**Comment by 88250** [comment]
试试看吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 上午7:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 移动端下载云端数据快照失败 function not implemented (Issue #11864)




 
😭 那咋办，只能等着我下次更新系统再看看吗？

**Comment by woniuxia** [comment]
D大，更新系统后可以了，我 close 了，辛苦。
