### ISSUE TITLE
删除数据库，绑定块不会清除右上角角标

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11860]
试了一下，文档块和非文档块都不会清除

https://ld246.com/article/1719702221462

**Comment by 88250** [comment]
感谢反馈，这个改动不拉进版本了。

**Comment by Jiangshuon** [comment]
@88250 d大，好奇不拉进版本是什么意思呢，是指下个版本此功能会改进，但是在更新说明中不会显示该issue，还是说该功能改进在后续版本才会生效？不拉进版本有啥好处吗？

**Comment by Jiangshuon** [comment]
@88250 还有D大，本周能更新吗？移动端无法使用“添加到数据库”这个太影响使用了！并且我还不会自己编译安卓…

**Comment by 88250** [comment]
下个版本更新就会有，这周还更新不了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月2日(周二) 中午1:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 删除数据库，绑定块不会清除右上角角标 (Issue #11860)




 
@88250 还有D大，本周能更新吗？移动端无法使用“添加到数据库”这个太影响使用了！并且我还不会自己编译安卓…
