### ISSUE TITLE
剪切嵌入块会导致嵌入块上的自定义属性丢失

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#11861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

为嵌入块添加自定义属性，剪切粘贴后会丢失，复制没问题

### Expected result

和复制一样的效果

### Version environment

```markdown
- Version: v3.0.17
- Operating System: windows
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
这个改动不拉进版本了。
