### ISSUE TITLE
改进列表 Shift+Tab

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11866]
https://ld246.com/article/1719817067018

“任务列表”里的“有序列表项”：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d3dbe0d8-efb6-4a80-9430-7fc9a5e6fa03)

只有这个组合有问题

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/66d9d02b-9814-4fbb-b4d8-72a2dfb06f75)

**Comment by 88250** [comment]
这个改动不拉进版本了。
