### ISSUE TITLE
在嵌入块中禁用图片宽度拖拽

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11879]
https://ld246.com/article/1719979143480/comment/1719983218387#comments

在嵌入块中拖拽图片宽度，会导致源块变为 HTML 块

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/dea397df-8ea7-41a9-a5cd-289ac1fa1edf)

**Comment by 88250** [comment]
这个改动不拉进版本了。
