### ISSUE TITLE
按 Backspace 时将列表项内的空标题块转换为段落块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11870]
### In what scenarios do you need this feature?

如果不在列表内，按 Backspace 时会将空标题块转换为段落块；

如果在列表内就不行：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/a2aefceb-6013-4045-9051-104b86aa7fed)

### Describe the optimal solution

`* # 345` 从右到左依次删除

**Comment by 88250** [comment]
这个改动不拉进版本了。
