### ISSUE TITLE
代码块跳转问题（在代码块中，无法跳转到上下块）

### ISSUE THREAD

**Issue by Think-man** [siyuan-note/siyuan#11877]
### In what scenarios do you need this feature?

1，代码块中，无法跳转到上下块
2，代码块中，shift + 上下键，跳不出代码块，无法到上级块
3，（可否加一个快捷键：让鼠标跳转到上下一个同级别块）

<img width="990" alt="image" src="https://github.com/siyuan-note/siyuan/assets/49435771/112c4236-9c9f-4a25-89bb-b04fe2ae26fe">

<img width="406" alt="image" src="https://github.com/siyuan-note/siyuan/assets/49435771/dcfea381-b790-4347-9466-b393ffb2af92">

### Describe the optimal solution

加一个快捷键是否可以解决？

**Comment by TCOTC** [comment]
[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/402567c2-817f-45d2-8653-394e1e086c28)

**Comment by 88250** [comment]
正如楼上录屏演示，直接使用 ↑/↓ 即可。
