### ISSUE TITLE
列表转换为段落没有显示快捷键

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11873]
![image](https://github.com/siyuan-note/siyuan/assets/78434827/65cf020a-aec4-4af6-a54b-12902f2caca9)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/9303ccec-c456-4abd-beb7-81b37f254f2b)

**Comment by 88250** [comment]
这个改动不拉进版本了。
