### ISSUE TITLE
在标题按下 Enter 后应该在文档开头新建一个段落块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11871]
### In what scenarios do you need this feature?

如果文档开头是一个列表的话就不行，只能在块标里用「起始插入块」：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/4053d747-2c5b-45ce-afd3-5c9ce4d5f079)

### Describe the optimal solution

。

**Comment by Vanessa219** [comment]
下面的这个块是空的，回车就会定位到空块，而不是新建，如果不是空块就会新建了。

**Comment by TCOTC** [comment]
能针对首个块为表格的场景单独优化一下吗

**Comment by 88250** [comment]
现在这个比较合理，因为空段落属于空块，标题回车后直接在列表下的空块中写更方便。

这个就不改动了，谢谢。

**Comment by TCOTC** [comment]
但既然是要在标题按回车了，那目的就是在开头新建一个空段落块，而不是跳转到下面输入。

就像下面这种情况，在标题按回车是为了在开头新建一个段落块，但按回车之后什么反应都没有：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/ac360004-cf3e-4906-973e-52df424093a4)

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
回车后光标已经在数据库上了，现在修改为新建块。

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by TCOTC** [comment]
> 在标题按下 Enter 后应该在文档开头新建一个段落块

已在 https://github.com/siyuan-note/siyuan/issues/15294 改进
