### ISSUE TITLE
表格块下多次正向链接，在关系图中只显示一个节点的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1187]
### Bug描述

表格内容块下对其它内容块多次正向链接，但是在关系图中只会显示一个节点（是一个随机的节点）

### 复现截屏

![image](https://user-images.githubusercontent.com/47321059/105045392-d3d3b180-5aa2-11eb-9691-2ad75cac21d3.png)

![image](https://user-images.githubusercontent.com/47321059/105045783-42187400-5aa3-11eb-8976-02c9e086550b.png)

![image](https://user-images.githubusercontent.com/47321059/105045869-56f50780-5aa3-11eb-9e1d-f8167066643c.png)

### 环境

版本 Version：v0.6.41
操作系统 Operating system：Windows 10

**Comment by 88250** [comment]
你好，我这里好像没问题：

![image](https://user-images.githubusercontent.com/873584/105056996-be18b900-5aaf-11eb-947c-c849164f9e57.png)

**Comment by dejavudwh** [comment]
1. 问题应该出现在bar的关系图当中
![image](https://user-images.githubusercontent.com/47321059/105061386-6a5c9e80-5ab4-11eb-8bc7-89ceb886efa4.png)

**Comment by 88250** [comment]
感谢，这里的确有问题，稍后改进。
