### ISSUE TITLE
在笔记中编辑文字，长按空格，长按退格都会导致软件卡顿

### ISSUE THREAD

**Issue by Josephyss** [siyuan-note/siyuan#11875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我用的是默认主题，无插件，长按空格和长按退格都会导致系统卡顿，请优化

### Expected result

长按空格，长按退格键

### Version environment

```markdown
win11，微软商店最新版
```

### Log file

[system-log.zip](https://github.com/user-attachments/files/16066955/system-log.zip)

**Comment by TCOTC** [comment]
GitHub 下载的没有遇到这种情况

**Comment by 88250** [comment]
抱歉，这个没有办法避免了，链滴上已经有反馈 https://ld246.com/article/1719915837925
