### ISSUE TITLE
导出文档的过程中支持取消

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11881]
### In what scenarios do you need this feature?

刚刚导出一个文档，因为没有留意文档内的连锁引用，把半个工作空间都导出了。过程中什么都无法操作只能干等

### Describe the optimal solution

导出文档的过程中支持取消

**Comment by 88250** [comment]
这个没有办法取消，如果加确认框的话又感觉有点多余。

先关闭了，如果以后反馈的人多再重开，谢谢。
