### ISSUE TITLE
希望支持快捷添加和更新序号的功能

### ISSUE THREAD

**Issue by zhuzongzhen** [siyuan-note/siyuan#11884]
### In what scenarios do you need this feature?

|编号|xxx|xxxx|
|--|--|--|
|1|xxx|xxx|
|2|xxx|xxx|
|3|xxx|xxx|

向上面这样的表格，最左边的序号，每次都需要手动一行行添加，并且删除或者新增一行表格时就会出现序号乱了，
然后就需要从头到尾再修改一遍，非常麻烦，能否使用自动一键生成序号

### Describe the optimal solution

是否可以使用占位符，比如 ${line}， 渲染时自动转换成表格对应的行号

**Comment by 88250** [comment]
你好，这个场景建议使用 数据库 - 表格视图 - 行号：

![image](https://github.com/siyuan-note/siyuan/assets/873584/dfa02496-8e04-4111-8460-346be49721ed)
