### ISSUE TITLE
（运行时错误、异常列表）选中列表项后拖动列表块标，应以选中的内容为准，只拖动选中的内容

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11882]
（运行时错误、异常列表）选中列表项后拖动列表块标，应以选中的内容为准，只拖动选中的内容

1. 产生系统运行时错误
   
   [视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/9cdef5d0-7cb6-47d5-a8b4-78e4deb448f4)

2. 产生异常的列表和列表项

   [视频2.webm](https://github.com/siyuan-note/siyuan/assets/78434827/b6f0996d-b229-499b-8990-9071ad659306)

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by TCOTC** [comment]
@Vanessa219 无论拖动的是哪个块标，都应该以选中的块为准。因为用户在拖动块的时候不会去分辨哪个块标对应哪个块，一般是随便找一个块标就拖动了。

比如这种情况，不试一下都不知道会拖动哪个块：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/ee43ddf6-b75a-4d0d-891b-6d68297e019f)

**Comment by Vanessa219** [comment]
块标和块是对应的。不能说这个块标的操作对应其他快的。试了下，notion 和我来都是这样的。

**Comment by TCOTC** [comment]
问题是别人多选之后的块标也只有一个，拖哪个都一样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e82a42d3-0963-4671-82e9-ed3f661778b9)

思源有一堆，效果还不同：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/58d2eae5-a48c-4176-9721-957e16a990b2)

**Comment by TCOTC** [comment]
要不在多选块的时候只显示一个块标？

**Comment by Vanessa219** [comment]
这个好像也不太好，再想想吧。
