### ISSUE TITLE
允许用户在思源运行时编辑 assets/ 目录下的文件

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#11883]
### In what scenarios do you need this feature?

* 此前为了防止第三方软件读写产生冲突，思源在检测到文件读写权限被侵占之后就会自动暴毙
* 然而，这带来了另一个影响：当我尝试使用外部软件编辑思源的资源文件的时候，会意外地触发思源的检测机制并导致思源暴毙
* 而使用外部软件编辑思源的资源文件非常正常、合理的需求，如：word 文件、ppt 文件等
* 需求：请为 asset 目录下的文件增加特殊处理，允许外部软件正常编辑 asset 文件

### Describe the optimal solution

* 我能想到的最简单粗暴的方案，就是检测到 asset 文件正在被编辑的时候，直接停止（推迟）同步
* 如果这个方案过于粗暴，也可以把条件收缩一些，只针对特定类型的文件执行这种推迟操作

  * 例如允许用户指定，在编辑后缀名为 docx、pptx 的文件时，才推迟通过
  * 而在检测到其他类型的文件被占用时，还是按照之前的逻辑自动暴毙

**Comment by TinkMingKing** [comment]
我觉得很是需要，之前编辑pdf，云端数据坏了好多次，因为思源不能手写标注，所以外部编辑pdf有时候非常需要，其他文件编辑可能也有类似需求

**Comment by zxhd863943427** [comment]
加一，assets下的目录是有外部编辑需求的，否则word、ppt之类的文档放进去就无法在思源打开时候编辑有点离谱。

**Comment by TCOTC** [comment]
现在不支持吗？我这里编辑 docx 文档好像没问题

**Comment by frostime** [comment]
> 现在不支持吗？我这里编辑 docx 文档好像没问题，表格也没问题

随缘暴毙，有时候不会出问题，但是有时候会

**Comment by 88250** [comment]
目前已经判断了一些同步时引起读写崩溃的情况（比如 Windows 下因为 Office 系列打开占用文件），但是可能有所遗漏，麻烦补充重现问题的环境，我这边尽量安装同样软件环境模拟看看，多谢。

**Comment by frostime** [comment]
> 目前已经判断了一些同步时引起读写崩溃的情况（比如 Windows 下因为 Office 系列打开占用文件），但是可能有所遗漏，麻烦补充重现问题的环境，我这边尽量安装同样软件环境模拟看看，多谢。

### Context

- 我上一次遇到暴毙情况可能已经有一两个月了，从那以后就没有在外部编辑过思源的资源文件；今天在群里聊天时提到了这个问题，于是我决定提交这个 issue。
- 正如之前提到的，我不太能确定你所说的「已经处理了一些同步时引起的读写崩溃」是何时加入的，以及是否还可能遇到之前的崩溃情况。
- 如果这是最近才加入的功能，那么我可能需要进行进一步测试以确认这个问题是否已经被解决（毕竟之前的更新公告中似乎没有提及此事）。

### 疑问：可扩展性

- 我比较好奇你说的处理策略具体是什么？是基于正在编辑的文件的扩展名来判断是否报错，还是依据外部编辑软件来源（比如office）来进行判断？
- 我特别关注的是功能的可扩展性：
  - 不同用户可能常用不同类型的文件；例如，我以前会将 drawio 文件放入思源并在外部编辑。
  - 是否可以让用户自定义这方面的设置？例如，允许用户指定某些文件后缀名，当思源检测到这些文件正在编辑时，采取特殊措施以避免崩溃。

**Comment by TCOTC** [comment]
@frostime 最近加的，直接下最新的 dev 版测

**Comment by 88250** [comment]
是这个 issue 改进的 https://github.com/siyuan-note/siyuan/issues/11253 最后一次提交是上个月（到目前还没有正式发版 v3.1.0，所以目前得用最新的 v3.1.0-dev9 测试）。

这个改动只是忽略隐藏文件（Office 系列软件编辑时会生成一个隐藏文件），所以其他情况还需要再测试看看（比如你提到的 drawio 编辑），如果有问题麻烦反馈，多谢。

**Comment by frostime** [comment]
> 是这个 issue 改进的 #11253 最后一次提交是上个月（到目前还没有正式发版 v3.1.0，所以目前得用最新的 v3.1.0-dev9 测试）。
> 
> 这个改动只是忽略隐藏文件（Office 系列软件编辑时会生成一个隐藏文件），所以其他情况还需要再测试看看（比如你提到的 drawio 编辑），如果有问题麻烦反馈，多谢。

你说的隐藏文件指的是编辑时候产生的临时文件是吗？相关代码似乎是 gulu 里这个？
https://github.com/88250/gulu/blob/c9cf5f7a4d02d3e984123354f1197637a58685fb/fileh_windows.go#L22

对这个代码我的疑问是，他似乎是通过前缀 `.` 来判断隐藏文件。但是我本机测试，使用 wps 打开word ppt文件的时候，生成的临时文件是以 `~` 为开头的，不知道这是否会构成影响。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/f088992a-bfde-4173-a265-5947546c1106)

**Comment by 88250** [comment]
对，就是这个临时文件，Windows 上使用 . 和文件属性判断：

![image](https://github.com/siyuan-note/siyuan/assets/873584/2824c896-d256-49ab-b6dd-b07d36b8f8aa)

**Comment by frostime** [comment]
> 对，就是这个临时文件，Windows 上使用 . 和文件属性判断：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/345691003-2824c896-d256-49ab-b6dd-b07d36b8f8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNjU2MTgsIm5iZiI6MTcyMDA2NTMxOCwicGF0aCI6Ii84NzM1ODQvMzQ1NjkxMDAzLTI4MjRjODk2LWQyNTYtNDlhYi1iNmRkLWIwN2QzNmI4ZjhhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwMzU1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2NjZmVjZGVkMDkwNzIzN2FiZmExM2NkNWY3YThlZjdlNmE4ZDJiYjYwNjJkMzgwZTI3ZWFhMzBjZTUwOGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R3siOhRnsDEc7Ij_saa0Nx1-_pq7A3JdYTeOBUyrp84)

ok，从代码来看逻辑应该没什么问题。我后面更新后测试测试。

不确定是否能解决。不过你可以先把这个 issue 关闭，如果还有问题我再重开。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
