### ISSUE TITLE
删除块后撤回，需要恢复数据库条目

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11887]
### In what scenarios do you need this feature?

撤回无法恢复条目：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/4e6ac6df-4eda-4a9e-bd40-19d930a1e4e5)

**Comment by 88250** [comment]
已经在 https://github.com/siyuan-note/siyuan/issues/10907 中记录过了。

**Comment by TCOTC** [comment]
@88250 #10907 里记录的是对数据库的操作，这个 issue 是对绑定块本身的操作

**Comment by 88250** [comment]
都记在一个里面吧。
