### ISSUE TITLE
转换网络图片为本地图片功能支持本地file:///文件

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#11885]
### In what scenarios do you need this feature?

当前的网络图片转本地似乎不支持导入 file:/// 协议的图片。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/a42bb543-bd22-46ae-86a5-c346ff92608c)

![image](https://github.com/siyuan-note/siyuan/assets/27268127/8f1e992e-88d2-4b22-8292-e9787fa6fd38)

### Describe the optimal solution

希望予以支持。

**Comment by 88250** [comment]
感谢反馈，稍后改进。

**Comment by 88250** [comment]
这个改动不拉进版本了。

**Comment by pisceswb** [comment]
可千万不要把“file://”的非图片链接加入到“转换为本地”的功能中了 @88250

**Comment by 88250** [comment]
@pisceswb 转图片的那个功能不会

**Comment by pisceswb** [comment]
修改后，“网络资源文件转换为本地”，这个功能会把本地的file://链接文件转换，将资源文件放到asset中吗？

**Comment by pisceswb** [comment]
@88250

**Comment by 88250** [comment]
没有改之前也会的，这个改动只是改进 `file:///` 的兼容。
