### ISSUE TITLE
导出 PDF 带上了菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11899]
### In what scenarios do you need this feature?

https://ld246.com/article/1720334603397/comment/1720341004766#comments

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f6c8535f-ff69-4901-a50c-b2225f172cba)

### Describe the optimal solution

。

**Comment by 88250** [comment]
我这里无法重现问题，你那里可以重现吗？

**Comment by TCOTC** [comment]
我这里也是这样的问题

**Comment by 88250** [comment]
随便一个文档都可以重现？

**Comment by TCOTC** [comment]
对：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e9f66f92-db14-4ea3-b2ee-d52ffff98bfe)

**Comment by 88250** [comment]
有点老火，我这里还是重现不了，帮忙试试新工作空间？

**Comment by TCOTC** [comment]
新建的也是这样：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3b8046c3-3196-4780-b3c2-c1c3a72a9416)

**Comment by 88250** [comment]
看下 Console 里面有没有报错

**Comment by TCOTC** [comment]
没有

**Comment by 88250** [comment]
暂时找不到问题原因了，等稍晚点再发一个 dev 看看。
