### ISSUE TITLE
改进选中子列表块的高亮

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11891]
### 改进选中子列表的高亮

如图：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/6ddfed71-b43f-40e4-837a-2503a182eb40)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/823259f3-0494-4276-b2fc-93437b32edd4)

需要对齐一下

**Comment by 88250** [comment]
这样选的时候选中的是列表块，所以会多出一截。

**Comment by TCOTC** [comment]
@88250 列表块也不应该多出一截，应该跟在列表外保持一致：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/ec2f8ef8-7bb5-4f0a-9792-a4c582834a27)

**Comment by 88250** [comment]
@Vanessa219

**Comment by TCOTC** [comment]
@88250 这个 issue 打开吧

**Comment by TCOTC** [comment]
应该是这两行样式的问题：

https://github.com/siyuan-note/siyuan/blob/0ea759953e998e0de3eb047d4c3df0ecba380a26/app/src/assets/scss/protyle/_wysiwyg.scss#L160-L161

**Comment by Vanessa219** [comment]
这个问题好像以前讨论过了

![QQ_1730194683436](https://github.com/user-attachments/assets/2b1d78e2-9a79-4944-9caa-1d9756450528)

**Comment by TCOTC** [comment]
讨论是讨论过，但确实还没解决

**Comment by Vanessa219** [comment]
这两个不是一个问题。找到解决方案再打开吧。
