### ISSUE TITLE
为什么不可以将conf一起同步

### ISSUE THREAD

**Issue by BabyMuu** [siyuan-note/siyuan#11892]
如题

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/10831

**Comment by BabyMuu** [comment]
> 有些主题在手机端上更好看，有些在pc端更好看，强制同步的话，手机端和pc端就只能用同一个主题了

快捷键也没有同步, 而且没有导入导出

**Comment by BabyMuu** [comment]
倒是没有考虑主题 主要是一些配置项 很想同步
