### ISSUE TITLE
3.1.0 dev11 存在文档打开闪退情况

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#11895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

打开文档，出现闪退情况
目前发现有两个文档出现这种情况
![思源笔记打开文档闪退](https://github.com/siyuan-note/siyuan/assets/60436214/03cd2382-a827-43f0-a9a1-3e463242629d)

测试文档：
[《星之卡比：探索发现》.sy.zip](https://github.com/user-attachments/files/16115710/sy.zip)
> 这个文档我导出再导入就没有问题，或者闪退的文档删除文字，之后也不会出现闪退现象

### Expected result

正常打开文档

### Version environment

```markdown
- Version: 3.1.0 dev11
- Operating System: win11 
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
> 导出再导入就没有问题

可能得打包一下工作空间

**Comment by 88250** [comment]
请上传一下日志文件。

**Comment by Achuan-2** [comment]
日志文件：[system-log.zip](https://github.com/user-attachments/files/16118388/system-log.zip)

**Comment by 88250** [comment]
日志里面有一条：

```
W 2024/07/06 18:48:20 transaction.go:1051: not found block [20240702213414-9v7iee9]
```

这个 ID 在提供的 .sy 数据中，所以应该是索引不完全导致的。但是具体导致这个问题的原因还没有排查到，重建索引应该能解决。

这个问题暂时先关闭了，我们会留意后续类似反馈，谢谢。
