### ISSUE TITLE
思源笔记网页插件无法保存github上issues页面的问题，只有标题

### ISSUE THREAD

**Issue by demonbana** [siyuan-note/siyuan#11893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源笔记网页插件无法保存github上issues页面的问题，保存后只有标题，没有内容也没有图片。
客户端使用，windows11，思源笔,3.0.17，浏览器edge版本 126.0.2592.87 (正式版本) (64 位)，思源笔记的插件

### Expected result

希望可以解决issues页面的某个问题的直接存档

### Version environment

```markdown
- Version: 3.0.17
- Operating System: windows11
- Browser (if used):edge版本 126.0.2592.87 (正式版本) (64 位)
浏览器的思源笔记插件
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/07/06 08:29:40 runtime.go:74: kernel is booting:
    * ver [3.0.17]
    * arch [amd64]
    * os [Microsoft Windows 10 Enterprise]
    * pid [18508]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\siyuan]
I 2024/07/06 08:29:40 conf.go:124: loaded conf [E:\siyuan\conf\conf.json]
I 2024/07/06 08:29:41 runtime.go:123: use network proxy [system]
I 2024/07/06 08:29:41 serve.go:116: kernel [pid=18508] http server [127.0.0.1:7588] is booting
I 2024/07/06 08:29:41 blocktree.go:513: read block tree [409.87 kB] to [E:\siyuan\temp\blocktree], elapsed [0.02s]
I 2024/07/06 08:29:41 conf.go:850: database size [7.88 MB], tree/block count [46/1598]
I 2024/07/06 08:29:41 working.go:192: kernel booted
I 2024/07/06 08:29:41 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=E:\siyuan\temp\pandoc\bin\pandoc.exe]
I 2024/07/06 08:29:41 conf.go:1095: pandoc initialized, set pandoc bin to [E:\siyuan\temp\pandoc\bin\pandoc.exe]
I 2024/07/06 08:29:41 box.go:77: auto stat [trees=46, blocks=1598, dataSize=180.18 MB, assetsSize=178.61 MB]
I 2024/07/06 08:29:41 disk.go:33: disk usage [total=475.78 GB, used=63.91 GB, free=411.88 GB]
I 2024/07/06 08:29:42 serve.go:129: reverse proxy server [127.0.0.1:6806] is booting
W 2024/07/06 08:32:50 blocktree.go:576: save block tree [size=142.19 kB] to [E:\siyuan\temp\blocktree], elapsed [2.83s]
I 2024/07/06 08:36:56 file.go:1631: removed doc [20240628231200-fm7lrwn/20240706083335-fkcaa9w.sy]
I 2024/07/06 08:37:03 file.go:1631: removed doc [20240628231200-fm7lrwn/20240706083231-ycskmnf.sy]
I 2024/07/06 08:37:07 file.go:1631: removed doc [20240628231200-fm7lrwn/20240706083243-ws84azs.sy]
W 2024/07/06 08:37:15 blocktree.go:576: save block tree [size=116.7 kB] to [E:\siyuan\temp\blocktree], elapsed [2.64s]
I 2024/07/06 08:38:36 file.go:1631: removed doc [20240628231200-fm7lrwn/20240706083815-cyzxxoy.sy]
I 2024/07/06 08:53:29 file.go:1631: removed doc [20240628231200-fm7lrwn/20240706085300-n7qqmgw.sy]

**Comment by demonbana** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/55745948/2804ea84-37d6-44ed-9624-90316bc65929)

**Comment by demonbana** [comment]
![Uploading 屏幕截图 2024-07-06 090326.jpg…]()

**Comment by demonbana** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/55745948/fd2ba64d-b85d-45f0-adc4-6e07fbb7a9ca)

**Comment by 88250** [comment]
GitHub Issue 的 DOM 元素大多包含 `commnet`，这个会被整体剪藏时默认移除。

可以考虑使用划选后的右键发送功能替代：

![image](https://github.com/siyuan-note/siyuan/assets/873584/a37d1cb3-d7ac-4cd2-96d9-6d48d46dd50a)

或者直接划选后复制再粘贴。

如果包含图片，使用 网络图片转换本地：

![image](https://github.com/siyuan-note/siyuan/assets/873584/40e66a7f-6139-43b2-8c86-fd934dbe04e6)
