### ISSUE TITLE
脑图改进建议：脑图与编辑视图紧密结合，起到1+1>2的作用，而不是现在的互不相关

### ISSUE THREAD

**Issue by Richardggm** [siyuan-note/siyuan#1189]
具体细节建议：
- 脑图只显示各级标题，而不显示正文。（正文太多根本显示不过来）。正文由编辑视图显示。
- 脑图和编辑页面结合，同时显示。点击脑图中的一项，编辑页面会跳转到对应位置。
- 脑图的各个节点的展开和闭合有记忆功能，下次打开仍然不变。（文件大了之后非常必要的功能，不然得翻来翻去很麻烦）

1.个人感觉，如果单独一个可编辑的脑图，那么这个功能就和别的思维导图软件没有太大区别。 
  但如果能够把脑图的功能和md编辑的功能结合起来，就会发挥更大的意义。

2.脑图起一个类似目录的作用（当笔记使用较久，目录层级较多时，脑图形式的目录比传统的线性目录要好用很多），点击脑图的某处，编辑页面就可以跳转到对应位置。 这样不仅方便编辑，也方便阅读。
  
3.目前的脑图模式，正文部分折叠，其实既不方便编辑，也不方便阅读，没怎么发挥出脑图的意义。 所以很希望开发大佬考虑下这个功能改进。

**Comment by 88250** [comment]
你好，目前的脑图模式是支持编辑的：

* 双击脑图节点可以编辑内容
* 使用 Insert 或者 Tab 键可以创建子节点（父节点必须是容器块）
* 部分节点支持拖动

脑图模式目前的状态只是基本可用，后续会逐步改进，感谢建议。
