### ISSUE TITLE
清理未引用的资源文件时不应该区分大小写

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11890]
https://ld246.com/article/1720165558482

更改路径大小写之后，未引用的资源文件中不应该出现这个资源文件

**Comment by winter60** [comment]
我的意思是不区分大小写哦，操作系统都不区分的

**Comment by TCOTC** [comment]
> 操作系统都不区分的

我还是第一次知道

**Comment by TCOTC** [comment]
我又想了想，还是「更改路径大小写之后不应该还能正常显示图片」更好，但不知道能否实现

**Comment by 88250** [comment]
> 我的意思是不区分大小写哦，操作系统都不区分的

只有 Windows 不区分，其他系统是区分大小写的，所以为了保证跨平台不出问题，还是要区分大小写。

所以保持不变了，感谢反馈。

**Comment by TCOTC** [comment]
@88250 那[帖子](https://ld246.com/article/1720165558482)里的问题怎么解决？

**Comment by winter60** [comment]
还有一个问题哈，资源路径名在块里写错后，为什么显示资源丢失，不应该只是未引用资源吗？@88250

**Comment by 88250** [comment]
未引用指的是出现了多余的资源文件；丢失指的是引用的路径不存在。

**Comment by winter60** [comment]
好的，终于搞明白了，感谢感谢
