### ISSUE TITLE
悬浮提示中的链接和标题之间添加一点间隔

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11896]
在悬浮提示中的链接和标题之间添加一点间隔，就能很方便区分开链接和标题（在链接和标题都是英文单词的情况下应该会不太方便查看标题）

- 链接
- 数据库资源列的链接

![image](https://github.com/siyuan-note/siyuan/assets/78434827/e43c300a-a83d-48ab-b265-74a30ecfafd0)

**Comment by TCOTC** [comment]
那个横线的意思是在那里加一点间隔，不是加一条横向的意思

**Comment by TCOTC** [comment]
@Vanessa219 有时候会出现链接和标题分不清的情况，所以需要一点间隔：

![image](https://github.com/user-attachments/assets/474832e4-bb5a-4fce-93fe-7714a78ed9a1)

**Comment by Vanessa219** [comment]
使用 `fn__hr` 进行分割
