### ISSUE TITLE
数据库增加重复值标记

### ISSUE THREAD

**Issue by lkwhile** [siyuan-note/siyuan#11907]
### In what scenarios do you need this feature?

数据库可判断是否存在重复值。

### Describe the optimal solution

增加可选按钮，当列中出现重复值时显示特定颜色。
![image](https://github.com/siyuan-note/siyuan/assets/122079546/bb1c8715-0aa5-4786-914d-0125bdd45af8)

### 备选方案一
![image](https://github.com/siyuan-note/siyuan/assets/122079546/9d47f796-499e-4fe0-acd3-cc09dca610cc)
### 备选方案二
![image](https://github.com/siyuan-note/siyuan/assets/122079546/bb19eccc-5716-4f52-89b8-cbf84fb6486f)

**Comment by TCOTC** [comment]
我觉得这里应该是增加「重复值计数」：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/ea625a15-1b5d-48fc-9d68-f2f717b34c36)
