### ISSUE TITLE
在行级元素前加两个反斜杠会变成 HTML

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11906]
https://ld246.com/article/1720407825316

可以复现

**Comment by 88250** [comment]
这个没有办法处理，`\` 会转义行级标签开头的 `<`。

**Comment by TCOTC** [comment]
我不太理解，`\\` 不是转义反斜杠本身吗？

**Comment by TCOTC** [comment]
@88250 为啥转义反斜杠本身的时候会再转义 `<` ？

**Comment by 88250** [comment]
标签的转义处理不太一样



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月28日(周六) 晚上8:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 在行级元素前加两个反斜杠会变成 HTML (Issue #11906)




 
@88250 为啥转义反斜杠本身的时候会再转义 < ？
