### ISSUE TITLE
改进优化排版

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11905]
### In what scenarios do you need this feature?

没加粗的时候优化排版是能在中英文间加空格的：`开启==Win+E键==`

![image](https://github.com/siyuan-note/siyuan/assets/78434827/cb36be59-e65c-4dfe-8655-2bc2a9589ff8)

加粗之后就不行了：`**开启**​**==Win+E键==**`

![image](https://github.com/siyuan-note/siyuan/assets/78434827/bca247e2-8955-43d8-927d-4b0cc39f9ba4)

### Describe the optimal solution

。

**Comment by 88250** [comment]
情况较复杂，暂时不考虑了，谢谢。
