### ISSUE TITLE
3.1.0 dev 11发布界面加载流程错误

### ISSUE THREAD

**Issue by leolee9086** [siyuan-note/siyuan#11902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

经过排查，应该是在issue中https://github.com/siyuan-note/siyuan/pull/11733

![image](https://github.com/siyuan-note/siyuan/assets/19915077/d53b6001-a5c6-4e11-824c-f4b46b8e6993)

这两个位置增加角色鉴权之后造成前端加载时收到403错误

这里可能需要对只读界面进行单独处理

### Expected result

在发布界面中跳过同步和获取云端用户,类似这样?
![image](https://github.com/siyuan-note/siyuan/assets/19915077/c96957e7-ac0e-4654-99d1-e76e620de4e6)

### Version environment

```markdown
- Version: 3.0.1 dev11
- Operating System: windows 11
- Browser (if used):edge
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16118929/siyuan.log)

**Comment by Zuoqiu-Yingyi** [comment]
@leolee9086 
该问题在 #11733 中已修复, 但在 https://github.com/siyuan-note/siyuan/commit/cd40ec50bbebe87ba6de7bf832805a73ffd5c476 里移除了回调函数中的状态校验导致又出现了

**Comment by leolee9086** [comment]
> @leolee9086 该问题在 #11733 中已修复, 但在 [cd40ec5](https://github.com/siyuan-note/siyuan/commit/cd40ec50bbebe87ba6de7bf832805a73ffd5c476) 里移除了回调函数中的状态校验导致又出现了

我也不知道该咋弄  我本地先加上用着得了

**Comment by 88250** [comment]
这两个路由拦截删掉了，还是在 controller 里面判断权限。

**Comment by Zuoqiu-Yingyi** [comment]
> 这两个路由拦截删掉了，还是在 controller 里面判断权限。

这是 API 调用的问题, 不是 API 实现的问题
通过移除权限中间件的方式会影响 API 行为的一致性!

**Comment by 88250** [comment]
似乎问题不大吧。

**Comment by Zuoqiu-Yingyi** [comment]
> 似乎问题不大吧。

会影响 API 的语义与行为的一致性，进而增加未来的维护成本

**Comment by 88250** [comment]
我觉得这个问题不大，`getWorkspaces` 也是类似处理的。

**Comment by Zuoqiu-Yingyi** [comment]
> 我觉得这个问题不大，`getWorkspaces` 也是类似处理的。

问题很大, `getWorkspaces` 也不应进行类似的处理
1. 引入错误的语义: `getCloudUser` 与 `getBootSync` API 调用不需要鉴权
2. 引入错误的行为: 无权限的请求调用了该 API 并获取了正常的响应
3. 未来的维护成本: 需要意识到以上问题才能正确理解这两个 API 的行为逻辑

**Comment by 88250** [comment]
麻烦单独开 Issue 记录下，这个版本暂时不动了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月7日(周日) 晚上11:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 3.1.0 dev 11发布界面加载流程错误 (Issue #11902)




  
我觉得这个问题不大，getWorkspaces 也是类似处理的。
  
问题很大, getWorkspaces 也不应进行类似的处理
  
引入错误的语义: getCloudUser 与 getBootSync API 调用不需要鉴权
 
引入错误的行为: 无权限的请求调用了该 API 并获取了正常的响应
 
未来的维护成本: 需要意识到以上问题才能正确理解这两个 API 的行为逻辑

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 
能接受 #11733 `App` 中 `constructor()` 中相关的优化嘛, 能接受的话我再开 issue 并提交相应的 PR

**Comment by 88250** [comment]
这个问题稍微推后吧，我和 @Vanessa219 先记一下，多谢。

**Comment by Vanessa219** [comment]
这个没问题就暂时不动了。

**Comment by Zuoqiu-Yingyi** [comment]
> 这个没问题就暂时不动了。

有性能+上述问题

**Comment by 88250** [comment]
先记录 issue 吧 https://github.com/siyuan-note/siyuan/issues/11918
