### ISSUE TITLE
自动隐藏侧边栏的触发区域改进

### ISSUE THREAD

**Issue by H-a-r-r-o-w** [siyuan-note/siyuan#11908]
### In what scenarios do you need this feature?

任何需要拖拽右侧滚动条的时候
![image](https://github.com/siyuan-note/siyuan/assets/77455480/a9b58a01-f501-46b9-b90c-0cd66c8995b0)

都会直接触发自动隐藏的右侧侧边栏
![image](https://github.com/siyuan-note/siyuan/assets/77455480/27e0a03f-fb57-4923-b4b9-eedf8fe61605)

目前导入无结构长文阅读，滚动条形同虚设，阅读体验相当糟糕。
补：同理左侧也希望能有类似改进，对于内容较多的侧边栏，一旦误触打开会很打扰思考。

### Describe the optimal solution

新增一个侧边栏“触发标识”，侧边主要区域不触发侧边栏，鼠标经过”触发标识“时才唤出侧边栏
![image](https://github.com/siyuan-note/siyuan/assets/77455480/8d868abf-5813-468d-9f27-b2e93c6bf111)
![image](https://github.com/siyuan-note/siyuan/assets/77455480/86d9f198-9adf-4667-8bd7-ba4ea422987e)
图示为Remnote的设计

**Comment by H-a-r-r-o-w** [comment]
补：同理左侧也希望能有类似改进，对于内容较多的侧边栏，一旦误触打开会很打扰思考。

**Comment by 88250** [comment]
这样的话对于想要方便触发展开的用户来说就不方便了，这地方暂时还是保持不变吧，感谢反馈。

**Comment by AvoidantPerDis** [comment]
感觉还是太灵敏了

**Comment by TCOTC** [comment]
如果能用 CSS 控制的话就能解决了 #12108

**Comment by Temacc0531** [comment]
现在不论是想打开还是想隐藏都基本盲操不了，强迫慢慢操作才可以

关联#9136
