### ISSUE TITLE
How to open the document programatically?

### ISSUE THREAD

**Issue by jaar23** [siyuan-note/siyuan#11904]
### In what scenarios do you need this feature?

I'm building a plugin that let user to search for their document, I want to let user open the document from search result.

### Describe the optimal solution

Open the document in editor panel by providing blockId.

**Comment by Wetoria** [comment]
In another app, you can set a link with a url scheme like `siyuan://blocks/${noteId}`

You can also open a document using <code>window.openFileByURL(`siyuan://blocks/${noteId}`)</code> in your plugin.

Alternatively, you can render a protyle with a nodeId.

There are many plugin author chatting on QQ, and it may be the main group of plugin authors

If you have any other questions about developing siyuan plugins, you can contact me.

**Comment by frostime** [comment]
> In another app, you can set a link with a url scheme like `siyuan://blocks/${noteId}`
> 
> You can also open a document using `` window.openFileByURL(`siyuan://blocks/${noteId}`) `` in your plugin.
> 
> Alternatively, you can render a protyle with a nodeId.
> 
> There are many plugin author chatting on QQ, and it may be the main group of plugin authors
> 
> If you have any other questions about developing siyuan plugins, you can contact me.

This takes effect even outside of SiYuan. However, if you specify a plugin scenario, you can use the openTab API or openMobileFileById (on mobile devices)

You can refer to this:
https://github.com/frostime/siyuan-dailynote-today/blob/c1016c8caa2f000f193afe76cbafae90732c6d5a/src/func/dailynote/open-dn.ts#L32

**Comment by Wetoria** [comment]
> > In another app, you can set a link with a url scheme like `siyuan://blocks/${noteId}`在另一个应用程序中，您可以使用 url 方案设置链接，例如 `siyuan://blocks/${noteId}` 
> > You can also open a document using `` window.openFileByURL(`siyuan://blocks/${noteId}`) `` in your plugin.您也可以使用 `` window.openFileByURL(`siyuan://blocks/${noteId}`) `` 插件打开文档。
> > Alternatively, you can render a protyle with a nodeId.或者，您可以使用 nodeId 渲染 protyle。
> > There are many plugin author chatting on QQ, and it may be the main group of plugin authorsQQ上有很多插件作者聊天，可能是插件作者的主要群体
> > If you have any other questions about developing siyuan plugins, you can contact me.如果您对开发思源插件还有其他疑问，可以联系我。
> 
> This takes effect even outside of SiYuan. However, if you specify a plugin scenario, you can use the openTab API or openMobileFileById (on mobile devices)这甚至在思源之外也生效。但是，如果指定插件方案，则可以使用 openTab API 或 openMobileFileById（在移动设备上）
> 
> You can refer to this:您可以参考以下内容： https://github.com/frostime/siyuan-dailynote-today/blob/c1016c8caa2f000f193afe76cbafae90732c6d5a/src/func/dailynote/open-dn.ts#L32

BTW, `openFileByURL` can be used in both platform, but it is not a recommended way.

**Comment by jaar23** [comment]
wow, both are working! thanks for the great help!
