### ISSUE TITLE
希望搜索界面可以直接新建文档，目前移动端可以，PC端不行

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11914]
### In what scenarios do you need this feature?

PC端只有没有任何搜索结果时才可以新建，但是更多时候是，如果没有该关键词的**文档**的话，就新建文档

<img width="926" alt="668bb179db4ebb000100267d" src="https://github.com/siyuan-note/siyuan/assets/67137548/a69e9f14-5c27-4c32-8d68-5516e661b36f">

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
赞同

**Comment by Jiangshuon** [comment]
@88250 ，d大，这周还不更新吗？等得花儿都谢了

**Comment by 88250** [comment]
今天会更新，正在打包了。

**Comment by Jiangshuon** [comment]
终于！！！！

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/16e327e9-6e34-43a3-b83d-15257b1db21a)
