### ISSUE TITLE
键盘控制选择 `/` 列表

### ISSUE THREAD

**Issue by M2uyo** [siyuan-note/siyuan#11912]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/92625353/3ce5f503-231f-4c40-9859-da9e1c8fc7fd)
可以通过TAB 和 上下左右键控制焦点选择里面的选项, 并通过回车确认选择

### Describe the optimal solution

语雀可以实现部分
![image](https://github.com/siyuan-note/siyuan/assets/92625353/823d45b5-a319-4b94-87de-c9e258d33d4d)

**Comment by TCOTC** [comment]
用 `↑` `↓` `Enter`

**Comment by Muu-yo** [comment]
> 用 `↑` `↓` `Enter`，`←` `→` `Tab` 没什么意义

上下太慢了 左右可以快速切到右侧的目录

**Comment by TCOTC** [comment]
思源只有单列的，多列是主题的效果

**Comment by Muu-yo** [comment]
> 思源只有单列的，多列是主题的效果

有没有可能支持个分组, 然后按左右切换分组

**Comment by 88250** [comment]
这里不考虑改变了，感谢提议。
