### ISSUE TITLE
数据库增加「重复值计数」

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11911]
_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/11907#issuecomment-2213227756_

**Comment by buco1997** [comment]
希望能增加重复值计数和重复值显示功能！

**Comment by 88250** [comment]
这个不考虑了，统计重复值有二义性，因为重复值可能存在多个。

如果要查看重复值，可以考虑排序后查看。

**Comment by TCOTC** [comment]
有几个重复值就计数几个嘛

**Comment by 88250** [comment]
还是不加了，通过唯一值已经可以判断了。

**Comment by TCOTC** [comment]
咋判断？

**Comment by 88250** [comment]
是的，或者切换统计，先看下总数在看下唯一值计数。

**Comment by TCOTC** [comment]
现在可以通过 `唯一值占比` 来判断是否有重复了
