### ISSUE TITLE
无序列表的闪卡，支持显示上下层级

### ISSUE THREAD

**Issue by H-a-r-r-o-w** [siyuan-note/siyuan#11910]
### In what scenarios do you need this feature?

现在的闪卡内容聚焦程度过高，在记忆时难以进行推断式记忆，需要显示上下文
![image](https://github.com/siyuan-note/siyuan/assets/77455480/820158f6-8885-4e5f-9926-cb0d65075ee5)
![image](https://github.com/siyuan-note/siyuan/assets/77455480/4ae24d2c-7b14-4d79-beaf-2c6af415b1a0)

### Describe the optimal solution

层级之间往往代表着细度的分化与逻辑，建议在默认设置中，至少显示完整的父层级内容
![image](https://github.com/siyuan-note/siyuan/assets/77455480/648da4e8-f4c6-497b-8b06-0a69eed17b06)
图为Remnote的设计。

**Comment by TCOTC** [comment]
点上面的面包屑：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/59a9d07a-d54e-4d97-9083-10e65f47cd57)

**Comment by H-a-r-r-o-w** [comment]
> 点上面的面包屑：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/346507665-59a9d07a-d54e-4d97-9083-10e65f47cd57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDIzMzksIm5iZiI6MTcyMDQ0MjAzOSwicGF0aCI6Ii83ODQzNDgyNy8zNDY1MDc2NjUtNTlhOWQwN2EtZDU0ZS00ZDk3LTkwODMtMTBlNjVmNDdjZDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEyMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YmE5MDY2ZGRkYWI4MzlmOWQ2MmEzYjc4Mjk3YzhkNmUwNjRkNjZlMTRjYWNmZDM3NDFlZDkzNDUxMDE2YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LsDQR61BQD4VEHJNJMPPgH8_gIicEzZnDCIVV-ddhBQ)

这个自然是知道的，但是每一个闪卡都默认不展开父级真的超级麻烦，所以说建议默认设置里和Remnote一样至少展开父节点

**Comment by Jiangshuon** [comment]
其实我觉得不用默认展开父节点，如果无法根据当前问题想起父节点是什么，说明对该知识点还不够熟悉

**Comment by H-a-r-r-o-w** [comment]
> 其实我觉得不用默认展开父节点，如果无法根据当前问题想起父节点是什么，说明对该知识点还不够熟悉

不能说不对，但很多内容是基于父节点的逻辑，存在不同含意的。
比如图示里的poised，在句子中解释为冷静沉着的，在其他句子里可能是动词过去式解释为悬停，我是基于句子去记忆的；
比如有时候我会有层级节点来解释变量含意，用于记忆和理解公式，每个公式里的变量用同一个符号意思是不同的。

**Comment by TCOTC** [comment]
干脆子块就不要闪卡，留父块的闪卡就够了

**Comment by 88250** [comment]
这个不考虑改变了，感谢讨论。
