### ISSUE TITLE
搜索历史显示双滚动条

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#11919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/32903588/c832e007-cacf-4f87-81b1-470c1dd30fdf)

![bfa1be79c702eb797069cec876c99662](https://github.com/siyuan-note/siyuan/assets/32903588/7a643281-3aa6-4249-a135-110e079e40a1)

### Expected result

fix it

### Version environment

```markdown
- Version: 3.0.17
- Operating System: win10
- Browser (if used):
```

### Log file

none

**Comment by TCOTC** [comment]
point 2 Duplicate of #10989

**Comment by Vanessa219** [comment]
第二点可以重现么？

**Comment by TinkMingKing** [comment]
无法，暂时找不到规律

**Comment by Vanessa219** [comment]
那先修改第一点，不拉进版本了。
