### ISSUE TITLE
文档过多时无法进入单页面菜单

### ISSUE THREAD

**Issue by zhangzz66** [siyuan-note/siyuan#11917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文档过多时，无法定位到当前文档，也就无法进行导入导出等相关的操作。

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/37007969/fd6c22ee-2726-4ce4-9499-8944043de3fe)
能否合并文档树上的菜单到文档页面上？

### Version environment

```markdown
- Version: 3.0.16
- Operating System: Win11
- Browser (if used):
```

### Log file

- 不需要

**Comment by TCOTC** [comment]
> 文档过多时，无法定位到当前文档，也就无法进行导入导出等相关的操作

你说的是这个菜单吧，不用在文档树右键就能打开：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/7fdfed12-f20d-4f4a-b4fa-554111aa8ce3)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/b911de4d-eb32-4f29-a5c5-9d0a60ab7397)

**Comment by zhangzz66** [comment]
> 你说的是这个菜单吧，不用在文档树右键就能打开：
对，就是这个，我竟然一直没有发现
> 文档树定位也很简单：
“定位打开的文档”以前一直用，但现在用不了，因为设置了超过256就不显示了（已经600+）。

已经解决，我先关闭这个issue了
