### ISSUE TITLE
Improve spaced repetition loading performance

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11927]
间隔重复打开和复习变得尤其缓慢，需要4、5秒才能响应

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

。。

### Expected result

。。

### Version environment

```markdown
- Version: 最新
- Operating System: 手机和pc
- Browser (if used):
```

### Log file

。。

**Comment by TCOTC** [comment]
我电脑也是

**Comment by IAliceBobI** [comment]
@abd-liac  插件在新版思源中，用的不是 getBlockAttrs ，而是batchGetBlockAttrs,

但瓶颈不是 batchGetBlockAttrs 这里，是getRiffDueCards ，读取到期卡特别慢。

**Comment by AvoidantPerDis** [comment]
问题出现在重构块树存储后，回到在此之前的dev无问题

**Comment by TCOTC** [comment]
我没用插件，同样是这个速度
