### ISSUE TITLE
拖动块时高亮相邻的块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11921]
## 超级块

拖动组合超级块的时候，只显示一条竖线不容易判断，高亮一下要组合成超级块的另一个块或相邻的子块会更好

- 拖动与某个块组合成超级块 → 高亮要组合成超级块的另一个块

   比如把 2 拖动到 1 的旁边，就高亮 1 ：

   ![image](https://github.com/siyuan-note/siyuan/assets/78434827/5ee15ae0-9243-4cb2-b08c-7cb48f50cac7)

   比如把 4 拖动到一个超级块的右边，就高亮这整个超级块：

   ![image](https://github.com/siyuan-note/siyuan/assets/78434827/ed2e0688-7a44-4463-af89-e5fc89a4ec9c)

- 拖动到某个块超级块内 → 高亮在这个超级块内与拖动位置相邻的子块

   比如把 4 拖动到 3 的右边，就高亮 3 这个块：

   ![image](https://github.com/siyuan-note/siyuan/assets/78434827/2d843285-e2d4-44db-81ee-8dce55b51dbc)

   比如把 4 拖动到 2 和 3 之间，就**高亮 2 和 3 这两个块**：

   → 关联：#12517

   ![image](https://github.com/siyuan-note/siyuan/assets/78434827/74f1ff44-bf3b-49f3-bc6a-347f002c6ec6)

## ~~列表~~ 其他块

- #11751

**Comment by shuojie819** [comment]
支持 +1
现在这个拖动确实还有很大的进步空间，显示……某些块的轮廓是个不错的解决方法。
>弄好了拖动效果 NO.1

**Comment by TCOTC** [comment]
基本在 #11751 实现了，还有部分问题移至 #12517 。
