### ISSUE TITLE
使得启动时自动打开项目变成可选的

### ISSUE THREAD

**Issue by Muu-yo** [siyuan-note/siyuan#11925]
### In what scenarios do you need this feature?

假设有两个笔记项目 1. 有授权码 2. 无授权码
假设项目1被关闭后想打开项目2
必须先输入项目1的授权码进入界面之后才能打开项目2

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/92625353/71823c79-460b-4179-b741-f3cd836935b5)
类似于Pycharm的框中的设置项

**Comment by 88250** [comment]
你好，可以通过制作快捷方式来指定工作空间入口，请参考 用户指南 - 工作空间 章节。

**Comment by Muu-yo** [comment]
> 你好，可以通过制作快捷方式来指定工作空间入口，请参考 用户指南 - 工作空间 章节。

如果有好多工作空间，这样的处理方式会很难受，如果有可能还是希望可以增加一个启动时询问打开哪个工作空间的界面
