### ISSUE TITLE
The drop-down menu in the macOS settings is invalid

### ISSUE THREAD

**Issue by syh19** [siyuan-note/siyuan#11929]
版本 v3.1.0 中集市面板排序下拉列表失效了

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="909" alt="image" src="https://github.com/siyuan-note/siyuan/assets/47665360/ab13acfe-8eb2-4f7f-8854-2b27f982fa1a">

### Expected result

可选择排序方式

### Version environment

```markdown
- Version: v3.1.0 
- Operating System: macos
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
我这里没问题。你可以试一下：

1. 更新主题
2. 关闭其他插件/代码片段后重启思源

**Comment by syh19** [comment]
我刚刚新创建的了一个新的工作空间也还是无法排序，还是点击没反应；新创建的工作空间是默认主题，无任何插件。

**Comment by TCOTC** [comment]
难道说的不是这个排序吗：


https://github.com/siyuan-note/siyuan/assets/78434827/eb12e694-4bc3-4a3e-935d-496bbf695fcb

**Comment by syh19** [comment]
Uploading 屏幕录制2024-07-09 22.22.17.mov…

**Comment by TCOTC** [comment]
@Vanessa219 可能是 Mac 上的问题

**Comment by Stellenb** [comment]
我也有同样的问题。

**Comment by Vanessa219** [comment]
无法重现，可以打开开发者工具看看有什么报错么？

**Comment by syh19** [comment]
> 无法重现，可以打开开发者工具看看有什么报错么？

控制台没有任何报错，只是单纯点击下拉菜单没有反应
我看社区也有好多人遇到类似的问题：[帖子链接](https://ld246.com/article/1720629089433)
应该是和MacOS特定版本有关系吧

**Comment by 88250** [comment]
请确认是否是在默认主题（daylight/midnight）下重现的。

**Comment by syh19** [comment]
> 请确认是否是在默认主题（daylight/midnight）下重现的。

确认是在默认主题（daylight/midnight）下复现的，不仅是默认主题，任何第三方主题都是失效的。重载以及重启软件都不起作用，下拉菜单还是无法展开。

**Comment by 88250** [comment]
刚刚发布了一个 dev 版本，请下载测试看看。安装 dev 版后需要打开开发者工具，在 Network 中禁用缓存，然后 Ctrl+R 刷新界面。

如果还是不行，建议关闭所有插件和代码片段以后再测试看看。

**Comment by syh19** [comment]
D大，正式版和 dev 版可以共存是吗？能共存的话我下载试一下

**Comment by TCOTC** [comment]
会覆盖吧

**Comment by syh19** [comment]
> 会覆盖吧？不知道 Mac 是怎样的

后续再从dev切回正式版的时候会影响数据吗？担心数据会丢失

**Comment by TCOTC** [comment]
不影响

**Comment by syh19** [comment]
> 应该不影响，数据都在工作空间里吧？

刚刚下载了dev版本，然后覆盖安装了，但是打开软件还是显示3.1.0版本，明明覆盖了但是版本没变化；
然后下拉菜单还是失效的

**Comment by TCOTC** [comment]
> 打开软件还是显示3.1.0版本

这个没问题

**Comment by syh19** [comment]
> 安装 dev 版后需要打开开发者工具，在 Network 中禁用缓存，然后 Ctrl+R 刷新界面。

按照 D大 说的安装 dev 版本并操作了，下拉菜单还是无效的

**Comment by 88250** [comment]
> 如果还是不行，建议关闭所有插件和代码片段以后再测试看看。

**Comment by syh19** [comment]
> 如果还是不行，建议关闭所有插件和代码片段以后再测试看看。

我把有问题的工作空间关闭所有插件和代码片段后原封不动复制了一份，然后新的工作空间可以正常展开下拉菜单，但是原来的工作空间还是不行。
按理说这两个是一模一样的数据，包括各种配置项，但是一个可以一个不行，很奇怪。

这么看来软件本身应该是没问题的，应该是和我的工作空间有关系。

**Comment by 88250** [comment]
打开开发者工具，再看看是不是 Console 里面有报错。

**Comment by syh19** [comment]
https://github.com/user-attachments/assets/de72bfcb-d795-4747-aea0-af589285f39f

我录了个屏，控制台里面没有报错。

**Comment by 88250** [comment]
暂时找不到原因了……先换个工作空间用了看看。

**Comment by syh19** [comment]
> 暂时找不到原因了……先换个工作空间用了看看。

嗯呐嗯呐，我看论坛和这个 issue 下面也还有其他人遇到了同样的问题，回头看看还有没有其他人再反馈了。

**Comment by Stellenb** [comment]
我找到的解决办法是，首先新建一个工作空间，然后不要登录自己的账号（因为登录之后，任何一个下拉菜单就无效了），再任意点击一个下拉菜单（我选的是云端同步）。以上操作完成后最后登录自己的账号即可。发自我的 iPhone在 2024年7月14日，11:57，D ***@***.***> 写道：﻿
暂时找不到原因了……先换个工作空间用了看看。

**Comment by 88250** [comment]
这个有点奇怪....



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 14, 2024 17:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] The drop-down menu in the macOS settings isinvalid (Issue #11929)




 我找到的解决办法是，首先新建一个工作空间，然后不要登录自己的账号（因为登录之后，任何一个下拉菜单就无效了），再任意点击一个下拉菜单（我选的是云端同步）。以上操作完成后最后登录自己的账号即可。发自我的 iPhone在 2024年7月14日，11:57，D ***@***.***&gt; 写道：﻿ 
 暂时找不到原因了……先换个工作空间用了看看。

**Comment by syh19** [comment]
今天我更新完 v3.1.1 版本后就可以正常使用啦。

**Comment by TCOTC** [comment]
v3.1.1 Mac https://ld246.com/article/1721271449594

**Comment by albertchendao** [comment]
> 我找到的解决办法是，首先新建一个工作空间，然后不要登录自己的账号（因为登录之后，任何一个下拉菜单就无效了），再任意点击一个下拉菜单（我选的是云端同步）。以上操作完成后最后登录自己的账号即可。发自我的 iPhone在 2024年7月14日，11:57，D ***@***.***> 写道：﻿ 暂时找不到原因了……先换个工作空间用了看看。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

创建新的工作空间后下拉菜单是正常的，然后什么都不操作，重启 siyuan 后又不行了

**Comment by Wetoria** [comment]
这个问题可能是Mac操作系统、electron的问题。Arc浏览器也出现了下拉框无效的情况。更进一步的情况我倒是没测试。

**Comment by TCOTC** [comment]
v3.1.2 Mac 还是不行

**Comment by 88250** [comment]
请各位帮忙试下 v3.1.3-dev 版本。

**Comment by albertchendao** [comment]
> 请各位帮忙试下 v3.1.3-dev 版本。

我的使用这个版本可以了，下拉选项正常

**Comment by 88250** [comment]
我们升级了 electron，麻烦大家帮忙测试开发版（[v3.1.9-dev5](https://github.com/siyuan-note/siyuan/releases/tag/v3.1.9-dev5)）看看是否正常。
