### ISSUE TITLE
拖动文档为子文档时，文档树自定义排序不稳定

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11922]
有时候会插入在顶部，有时候是底部，有时候是中间。

比如下面这个例子，为什么 4 会在 2 和 3 中间？

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/a4914537-7273-493f-a6ad-0cf17023ba8e)

**Comment by 88250** [comment]
因为 4 之前的排序值小于 3，所以拖成子文档以后会在 3 上面。

**Comment by TCOTC** [comment]
不是批量移动文档的时候就不需要这样了吧？我一个一个拖文档就是为了重新排序（让后拖进去的排在最底下），这样的话排序还是原样的乱

**Comment by 88250** [comment]
直接拖到目标下方。

**Comment by TCOTC** [comment]
子文档越长就越难拖，这时拖到父文档直接排到末尾是最方便的

**Comment by 88250** [comment]
这个就不动了



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月11日(周日) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 拖动文档为子文档时，文档树自定义排序不稳定 (Issue #11922)




 
子文档越长就越难拖，这时拖到父文档直接排到末尾是最方便的
