### ISSUE TITLE
无法安装，SiYuan无法关闭，请手动关闭它，然后单击重试以继续

### ISSUE THREAD

**Issue by zhy21345** [siyuan-note/siyuan#11933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![QQ截图20240709232054](https://github.com/siyuan-note/siyuan/assets/46223794/311922eb-6c2b-4702-8f32-b5885502bb78)
安装无法进行，指定的安装路径没有任何文件被解压

### Expected result

安装程序成功运行

### Version environment

```markdown
- Version: 3.1.0
- Operating System: Windows10
- Browser (if used):
```

### Log file

根本无法安装也无法获取log信息

**Comment by 88250** [comment]
建议重启系统后再安装看看，如果还是不行，可以试下先手动卸载后再安装。

**Comment by zhy21345** [comment]
> 建议重启系统后再安装看看，如果还是不行，可以试下先手动卸载后再安装。

已经重启，依然无法安装。因为这是初次安装，也无法卸载。

**Comment by zhy21345** [comment]
> 你选择的是为当前用户安装吗？

是的

**Comment by 88250** [comment]
安装路径和安装包程序不再同一个目录下吧？

**Comment by zhy21345** [comment]
> 安装路径和安装包程序不再同一个目录下吧？

当然，网页下载文件夹和应用安装路径是d:/download和d:/programfiles/SiYuan

**Comment by 88250** [comment]
换一个安装路径试试

**Comment by zhy21345** [comment]
> 换一个安装路径试试

虽然不知为何，但确实解决了。可能的原因是什么呢

**Comment by 88250** [comment]
是不是杀毒软件或者其他什么软件占用了目录或者文件吧。

**Comment by zhy21345** [comment]
> 是不是杀毒软件或者其他什么软件占用了目录或者文件吧。

我想并没有，安装路径和下载路径之前就设置过白名单，不过总算解决了就好

**Comment by HowcanoeWang** [comment]
3.1.8遇到了同样的问题，为单个用户安装，安装路径是C:/Apps/siyuan，一直提示siyuan无法关闭

使用管理员模式运行成功安装，看起来是卡在了移除桌面托盘图标
