### ISSUE TITLE
多窗口打开文档异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11939]
多窗口打开文档异常

- 文档移动到新窗口后，再次打开始终会在该窗口打开
- 在新窗口打开文档无法加载

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/f52f9b5f-e274-4ed8-8c38-7171ac634f02)

### Other information

https://ld246.com/article/1720582794114

**Comment by Vanessa219** [comment]
已修复，不拉进版本了。

**Comment by TCOTC** [comment]
我这里还是会始终在新窗口打开文档。

新窗口的文档被关闭了以后，说明其不再需要在新窗口显示，所以下一次应该在主窗口打开。
