### ISSUE TITLE
自定义模板函数

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11937]
### In what scenarios do you need this feature?

- 文档使用的模板函数
- 数据库模板列使用的模板函数

有些需求自己写个函数能很容易实现，但用内置的函数就极其复杂。

### Describe the optimal solution

。

**Comment by 88250** [comment]
这个恐怕只能通过 PR 补充了，没有办法运行时加载。

**Comment by TCOTC** [comment]
<img width="1222" height="523" alt="Image" src="https://github.com/user-attachments/assets/dde0cb49-d837-405a-87a5-62791ed54e69" />

<img width="2289" height="443" alt="Image" src="https://github.com/user-attachments/assets/dbfa48a4-03b7-4cb8-9edc-0180e261c50d" />

<img width="2449" height="563" alt="Image" src="https://github.com/user-attachments/assets/6aef9639-3ac1-4595-860a-72ec772b730b" />

**Comment by 88250** [comment]
具体实现思路是？

**Comment by TCOTC** [comment]
在所有使用到模板的地方开头插入用户的自定义模板。

但我现在很怀疑是否真的有人需要这个功能，模板写起来太麻烦，都没什么人用
