### ISSUE TITLE
Improve plugin dock position persistence

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11931]
插件 Dock 按钮无法保持在自定义位置

把按钮移动到其他位置，**关闭插件再打开** 或者 **重载界面** 之后按钮位置就恢复默认了

**Comment by Vanessa219** [comment]
重载界面这个才引入的，可以修复。但是关闭以后就没有数据了，只能按照配置来。

**Comment by TCOTC** [comment]
对我这种只在需要用时才启用插件的来说不太友好啊，有没有办法解决一下？

**Comment by TCOTC** [comment]
如果思源实在做不到，那有没有办法让插件获取到按钮的位置变动然后将这个位置保存为插件自身的配置信息？

**Comment by Vanessa219** [comment]
可能不太好记，如果启用之前，其他 dock 按钮移动过，这个位置可能就不对了。

**Comment by TCOTC** [comment]
那至少上下左右还是可以的，只要是在那个角落就行

**Comment by Misuzu2027** [comment]
@Vanessa219 有一个比较严重的 bug

v3.1.10-dev5 版本打开我的空间，发现界面一直在重载。

复现方式：打开 v3.1.10-dev5 ，下载一个插件，我这里是 基于文档搜索（syplugin-document-search） 插件，因为开启后会默认添加 Dock ，接着就会反复重载界面。

经调试原因是 onGetConfig.ts 文件中的 onGetConfig 方法中的 JSONToLayout(app, isStart); 代码调用下面代码发生异常，然后被异常处理捕获导致的

https://github.com/siyuan-note/siyuan/blob/e674cfec703b5e9f990b55d272aab88c0afc890c/app/src/plugin/loader.ts#L162  

建议修改判断为 ：

```ts
if (window.siyuan.storage[Constants.LOCAL_PLUGIN_DOCKS][plugin.name]  && window.siyuan.storage[Constants.LOCAL_PLUGIN_DOCKS][plugin.name][key]) {
```

**Comment by TCOTC** [comment]
我也遇到了，一直在重载，手动删掉工作空间的插件才恢复正常

**Comment by 88250** [comment]
@Misuzu2027 @TCOTC 我这里可以重现问题，稍后 @Vanessa219 确认一下。
