### ISSUE TITLE
添加數據庫API

### ISSUE THREAD

**Issue by ShirayukiRin** [siyuan-note/siyuan#11930]
### In what scenarios do you need this feature?

透過API對數據庫進行操作
例如:
1. 添加
2. 刪除
3. 修改屬性
4. 列出數據

### Describe the optimal solution

在[API文檔](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md)中沒發現數據庫相關的API
希望能添加

**Comment by 88250** [comment]
你好，请参考 router.go 中的 `/api/av/*` 开头的 API，用法只能通过看代码来使用。

Ref https://github.com/siyuan-note/siyuan/issues/11130
