### ISSUE TITLE
打开块标菜单时，点击另一个块标，需要在隐藏当前块标菜单后打开另一个块标菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11942]
### In what scenarios do you need this feature?

打开块标菜单时，点击另一个块标，需要在隐藏当前块标菜单后打开另一个块标菜单。

目前只是隐藏当前的菜单，没有打开新的菜单：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/78434827/426de4d6-9049-4c4a-8787-c49dfe9d8538)

**Comment by Vanessa219** [comment]
参考了一下 notion ，是不是要不显示块标会更好一点？

**Comment by TCOTC** [comment]
我看了一下 Notion ，菜单弹出之后整个界面其他地方都是不可操作的。

如果思源也改成这样的话我感觉不是很方便，比如在菜单弹出的时候就不能切换页签了，要先隐藏菜单，就会多一步点击。

**Comment by Vanessa219** [comment]
只是不显示块标，其他操作正常

**Comment by TCOTC** [comment]
显示块标的话，目前是点两下另一个块的块标就能打开另一个块的菜单了。

不显示块标的话，要先点击其他地方隐藏当前菜单，然后把鼠标移动到另一个块上，等块标出现后再点击。感觉不方便。

还是在隐藏当前块标菜单后直接打开另一个块标菜单会更方便。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
