### ISSUE TITLE
Improve database text field exporting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11945]
[数据库.sy.zip](https://github.com/user-attachments/files/16163913/sy.zip)

- 字段标题是纯文本，不要解析 Markdown
- 文本的软换行有问题

![image](https://github.com/siyuan-note/siyuan/assets/78434827/3fd79e41-c26c-474e-8a53-ccce42f7c1e6)

**Comment by TCOTC** [comment]
还有问题：

[未命名.sy.zip](https://github.com/user-attachments/files/16202777/sy.zip)

![image](https://github.com/user-attachments/assets/cba46b3f-0f43-4887-a487-d557f80cc4e2)

**Comment by TCOTC** [comment]
单元格内有多个换行的话还是会破坏表格：

![image](https://github.com/user-attachments/assets/dad6d9d6-dbd0-4cc3-a5c8-8cf52a1a9ac1)

**Comment by 88250** [comment]
感谢反馈，稍后解决。

**Comment by TCOTC** [comment]
模板里的换行还有问题：

![image](https://github.com/user-attachments/assets/9caada36-c842-4d5e-87f3-93dc20913b5e)

**Comment by TCOTC** [comment]
导出时应该根据模板列的设置来决定是否需要换行

**Comment by TCOTC** [comment]
这个 `<no value>` 我觉得没必要显示，像数据库那样为空就行了：

![image](https://github.com/user-attachments/assets/23321f50-0011-40e7-851b-2e29c84c227f)

**Comment by TCOTC** [comment]
希望这个样式也能显示出来，而不是纯文本：

![image](https://github.com/user-attachments/assets/7d4b00f7-9f77-4d23-8117-c1da6ae0102b)

**Comment by 88250** [comment]
麻烦上传一下测试用的 .sy.zip

**Comment by 88250** [comment]
模板字段的单独开 issue 后续再改进吧 https://github.com/siyuan-note/siyuan/issues/11988

.sy.zip 请上传到那里，谢谢。
