### ISSUE TITLE
希望添加添加批量重置闪卡功能和闪卡按顺序渐进显示

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#11947]
### In what scenarios do you need this feature?

在制卡刷题的时候我想突击刷题几遍但是不知道怎么快速一键重置，目前只有每一个单独的重置
![image](https://github.com/siyuan-note/siyuan/assets/52444119/d98ee5b2-42e4-45a6-bcfb-84a9e7597cd2)
第二个需求是有时候一些知识要求的前置内容比较多，需要提前复习很多前置知识作为前提

### Describe the optimal solution

对当前文档的卡片可以一键重置的按钮
可根据制卡循序来预览闪卡

**Comment by Jiangshuon** [comment]
批量重置现在有
![image](https://github.com/siyuan-note/siyuan/assets/67137548/22edda43-a1c1-4cde-b755-2b0588ce1e80)

**Comment by TCOTC** [comment]
> 批量重置现在有

确实单个文档的闪卡管理有批量重置

**Comment by SaXz2** [comment]
非常感谢已解决

**Comment by 88250** [comment]
第二个需求应该不会考虑了，请见谅。
