### ISSUE TITLE
快捷方式启动 相同路径不同路径名 没有去重且报错

### ISSUE THREAD

**Issue by Muu-yo** [siyuan-note/siyuan#11940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

cmd执行 
1. SiYuan.exe --workspace=d://note/siyuan
2. SiYuan.exe --workspace=D:\note\siyuan
相同的文件夹 产生了多个工作空间
且会报错
### Expected result

去个重?

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/92625353/6fb18603-f31d-4527-a410-e09f0ebc3353)
#### 启动时报错
![image](https://github.com/siyuan-note/siyuan/assets/92625353/01421172-4306-47d3-a24a-790f3708e61f)
![image](https://github.com/siyuan-note/siyuan/assets/92625353/f90f91a7-2b30-4f86-8e9a-f61d0bcf4003)
![image](https://github.com/siyuan-note/siyuan/assets/92625353/54af692d-fde7-48b6-9242-ba3f8cfe7055)
#### 关闭时报错
![image](https://github.com/siyuan-note/siyuan/assets/92625353/e8484406-953b-4a91-98e9-1da0aebd5f1c)
![image](https://github.com/siyuan-note/siyuan/assets/92625353/10ba7055-d709-4b7f-82e2-80c62b43ab85)

### Version environment

```markdown
- Version: 2.10
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16156682/siyuan.log)

**Comment by 88250** [comment]
你好，Windows 上因为不区分大小写，所以路径实际上是指向的同一个工作空间，但是其他系统上是区分大小写的，会指向不同的工作空间。考虑到这一点，我们暂时还是不进行去重了，感谢反馈。

**Comment by Muu-yo** [comment]
@88250 报错怎么个问题啊 ?

**Comment by 88250** [comment]
我这边最新版上测试没有报错。

**Comment by Muu-yo** [comment]
> 我这边最新版上测试没有报错。

@88250 能问下这个报错是什么意思么？

**Comment by 88250** [comment]
我看了下代码没有找到问题 😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月11日(周四) 中午12:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 快捷方式启动 相同路径不同路径名 没有去重且报错 (Issue #11940)




  
我这边最新版上测试没有报错。
  
@88250 能问下这个报错是什么意思么？
