### ISSUE TITLE
The database-bound block is automatically added to the database after being copied as a replica

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11959]
数据库绑定块复制为副本后，副本块需要添加到数据库中

1. 副本块需要添加到数据库中
2. 副本条目的字段值要跟原来的条目一致

内置属性和自定义属性都有，但数据库属性没有：

[视频.webm](https://github.com/user-attachments/assets/b2e38463-86e6-454b-aac3-5ecb7ac43a38)

关联 https://ld246.com/article/1720783311191

**Comment by 88250** [comment]
> 副本条目的字段值要跟原来的条目一致

这个暂时不做填充了，原有数据库字段值留空，或者按当前视图的过滤器设置填充。

**Comment by TCOTC** [comment]
文档块复制为副本之后没添加到数据库里

**Comment by 88250** [comment]
> 还有点问题：文档块复制为副本之后没添加到数据库里

感谢反馈，稍后改进。

**Comment by Jiangshuon** [comment]
@88250  d大，原文档中的块绑定了数据库，将文档复制为副本后，副本文档里面的块就没有绑定了，应该也要绑定吧

**Comment by TCOTC** [comment]
确实有这个问题，记录到 #12140
