### ISSUE TITLE
设置钉住的页签防止误关闭

### ISSUE THREAD

**Issue by Muu-yo** [siyuan-note/siyuan#11956]
### In what scenarios do you need this feature?

快捷键 ctrl+w 关闭当前页签 如果是多个的时候容易误关闭被钉住的页签

### Describe the optimal solution

希望添加个选项配置:  钉住的页签不可被关闭

**Comment by 88250** [comment]
你好，抱歉这个不考虑了，可以考虑使用：

![image](https://github.com/user-attachments/assets/942a600c-b819-4e7b-a8a6-a99790f49802)
