### ISSUE TITLE
DOCKER版本思源发布服务打开Basic Auth报错，会导致重复进行鉴权

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#11952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，Docker版本打开发布服务，并且开启Basic Auth后，进入发布的只读页面后后台报错，前端会要求重复进行鉴权

![image](https://github.com/siyuan-note/siyuan/assets/5226690/fa413baa-5933-4cbb-8a62-3f4f64485eb7)
![image](https://github.com/siyuan-note/siyuan/assets/5226690/36038509-975b-4f25-ba09-fd7495d14deb)

### Expected result

正常鉴权，不会报错

### Version environment

```markdown
- Version: 3.1.0
- Operating System: Docker 
- Browser (if used): chrome
```

### Log file

2024/07/11 17:49:37 http: panic serving 10.20.11.33:49874: runtime error: invalid memory address or nil pointer dereference
goroutine 2593 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1903 +0xbe
panic({0x1fc8100?, 0x3a24bb0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
net/http/httputil.(*ReverseProxy).copyBuffer(0x3a55e40, {0x2a09bc0, 0xc000a6df00}, {0x0, 0x0}, {0x0?, 0xc002860000?, 0xc002860000?})
        /usr/local/go/src/net/http/httputil/reverseproxy.go:634 +0xd3
net/http/httputil.(*ReverseProxy).copyResponse(0x3a55e40, {0x2a115b8, 0xc000b7a8c0}, {0x0, 0x0}, 0xffffffffffffffff)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:622 +0x1ee
net/http/httputil.(*ReverseProxy).ServeHTTP(0x3a55e40, {0x2a115b8, 0xc000b7a8c0}, 0xc002823b00)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:506 +0xff3
net/http.serverHandler.ServeHTTP({0x2a0b7d8?}, {0x2a115b8?, 0xc000b7a8c0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc00282cab0, {0x2a17b90, 0xc001d64240})
        /usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 88
        /usr/local/go/src/net/http/server.go:3290 +0x4b4

**Comment by jl0476** [comment]
@88250 这个能处理吗？

**Comment by 88250** [comment]
关闭所有插件后再看看？

**Comment by jl0476** [comment]
> 关闭所有插件后再看看？

关闭了所有插件，删除了所有插件，关闭了所有的代码，默认的主题，报错依旧。
![image](https://github.com/user-attachments/assets/378d3ae7-3fbe-4831-94d7-10126fce89e3)

**Comment by 88250** [comment]
暂时不太清楚原因，等有空看看。

**Comment by TCOTC** [comment]
跟 Docker 关系不大，桌面端也会这样

**Comment by 88250** [comment]
我这里桌面端开启发布服务后正常（启用 Basic 认证，并添加了一个测试账户）。

**Comment by TCOTC** [comment]
几天前的事了，我忘记是不是插件的问题了 https://ld246.com/article/1720587007796

**Comment by 88250** [comment]
楼主的问题是关闭了插件，默认主题也会有问题，所以我说我这里重现不了在桌面端上。

**Comment by TCOTC** [comment]
哦 不过会不会是相关的问题

**Comment by 88250** [comment]
这个就不太好确定了，得先在简单的环境下重现。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by TCOTC** [comment]
在 v3.3.1 解决 https://github.com/siyuan-note/siyuan/issues/15646
