### ISSUE TITLE
White screen when input text under an float window

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#11950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### [[ref]]
- [] click here, and move mouse to [[ref]], and a float window appears, then continue type something, will lead to a white screen

### Expected result

-

### Version environment

```markdown
- Version: 3.1.0
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by TCOTC** [comment]
给个录屏演示看看？

**Comment by XinLi0111** [comment]
> 给个录屏演示看看？

那天可以重复出现，但今天无法重现了😂，可能和那天刚更新有关吧

**Comment by XinLi0111** [comment]
> 给个录屏演示看看？

那天可以重复出现，但今天无法重现了😂，可能和那天刚更新有关吧
