### ISSUE TITLE
改进在新增的图片前 `Shift+Enter`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11968]
1. 输入文本
2. 软回车
3. 粘贴图片（我这里只有新增的图片能复现这个问题）
4. 在图片前软回车
5. 没有新建一个块，而是在中间插入了一个软回车
6. 在前面按一下退格键之后就恢复正常了

[视频.webm](https://github.com/user-attachments/assets/11992bf8-689b-4e59-8828-228da99395ee)

### Other information

可能与 #11766 相关

**Comment by pisceswb** [comment]
貌似与图片相关的操作有挺多问题的，这是基础内容，属于思源笔记的地基组成，希望能够优化修复

**Comment by TCOTC** [comment]
另一个与 `Shift+Enter` 相关的问题：#12200

**Comment by TCOTC** [comment]
可能是在 #13327 中修复了
