### ISSUE TITLE
提供回到上一个位置的快捷键

### ISSUE THREAD

**Issue by Young-Flash** [siyuan-note/siyuan#11963]
### In what scenarios do you need this feature?

跳转到某个应用块之后，可以通过某个快捷键回到跳转前的位置。类似于 vscode 中的 `Go Back`

<img width="1522" alt="image" src="https://github.com/user-attachments/assets/f935402b-58aa-46c8-96f7-45448f4f98d7">

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/caa88edc-6b04-49f6-8dba-57a74a61cb4d)

**Comment by 88250** [comment]
正如楼上所言。

**Comment by Young-Flash** [comment]
感谢！
