### ISSUE TITLE
Cache, OPFS, IndexedDB is deleted after SiYuan exit application

### ISSUE THREAD

**Issue by jaar23** [siyuan-note/siyuan#11969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

All persistent items is deleted after SiYuan exit application. For example, cache file from http request and indexeddb also got deleted. Tested on browser, it is not removed anything, only on application. Guess there is some setting in Electron.

### Expected result

Cache, OPFS, IndexedDB is persisted in SiYuan. Only delete it when explicitly call a function.

### Version environment

```markdown
- Version: 3.0.17 and 3.1.0
- Operating System: Linux
- Browser (if used): Browser is able to cache and persist those items, only SiYuan application deleted it.
```

### Log file

```
I 2024/07/13 23:59:22 database.go:1284: closed database
I 2024/07/13 23:59:22 conf.go:1018: cleared workspace temp
I 2024/07/13 23:59:22 sync.go:721: sync websocket closed
I 2024/07/13 23:59:23 conf.go:664: exited kernel
```

**Comment by 88250** [comment]
@Vanessa219 

![image](https://github.com/user-attachments/assets/1aacf4ee-1384-4739-b267-4b4e800df3f5)

![image](https://github.com/user-attachments/assets/6d655afa-8a62-4d67-b19e-ad43e51c861a)

**Comment by jaar23** [comment]
@Vanessa219 这个有办法做成设置吗， 让用户选择何时要清理？ 因为我在开发nb-assistant插件，每一次重启思源得加载transformer.js下载的模型，那样会很耗用户的时间与流量。

**Comment by jaar23** [comment]
找了一番发现，笔记并没有主动清除cache 而是因为每一次启动思源，后台的地址都不一样所导致。
![Screenshot_20240721_184102](https://github.com/user-attachments/assets/e1f4df30-16dd-4808-8479-d5def33afd82)

**Comment by jaar23** [comment]
让kernel启动在特定的port就可以了 `siyuan --port=16806` 可是那样就得让用户去改启动设置。
希望可以固定一个启动接口 比如`16806` , 只有在该接口不能使用的情况下才`getAvailablePort()`。
如果可以接受这个提议，我可以开一个pull request

**Comment by 88250** [comment]
启动时可以带参数，和指定工作空间类似。

**Comment by jaar23** [comment]
我发现有`getAvailblePort()` 的function，这个应该可以在第一次启动失败时候，从这个function拿到新的端口来实行第二次启动。不过这样就会有延迟或者出现其他问题。
因为是插件的关系，现在还没有找到更好的方法来读取本地文件。虽然`getFile` 可以使用，可是还是有局限。

**Comment by jaar23** [comment]
还有一个方法就是使用`env` 把端口设置在environmemt variable里。思源启动时候能够读取得到这个函数就用这个函数。并且确保只有真正需要修改端口的用户才去修改，不需要的都会照旧。启动失误也可以通过修改这个来解决。

**Comment by 88250** [comment]
对用户来说增加环境变量更麻烦一些吧，还是加启动参数方便。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
