### ISSUE TITLE
v3.1.0 缺失部分 emoji

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11961]
https://ld246.com/article/1720540716729

**Comment by qingtian805** [comment]
The alphabet emojis are called [Regional Indicator Symbol Letter](https://unicodeplus.com/U+1F1F9) which is used to indecate country flags in ISO 3166 Alpha-2 code. The emojis are not shown in [unicode full emoji list v16.0](https://www.unicode.org/emoji/charts-16.0/full-emoji-list.html). Searching 1f1f9 (letter T) only led me to the flag of Austria(AT), Bhutan(BT) and so on.

**Comment by qingtian805** [comment]
I am working on a list of emojis that disappeared in 3.1.0 and engaged a problem. Some unicode is not same with full list. For example, "1f3cb" is coded "1f3cb-fe0f":

https://github.com/siyuan-note/siyuan/blob/687421fe62beb6bddd46c69a263c485bb1fe6619/app/appearance/emojis/conf.json#L3354C1-L3360C9

Both code work fine though.

**Comment by TCOTC** [comment]
#11768 的如下更改造成了这个问题

> All Emojis description and keywords will comply with the [Unicode Common Locale Data Repository](https://github.com/unicode-org/cldr/tree/main/common/annotations).

原因是 cldr 缺失了部分 emoji ，例如这篇博客就提到了这个问题：[Unicode的CLDR有Emoji翻譯文字，但新版缺少了幾十個](https://jamesqi.com/zh-hant/%E5%8D%9A%E5%AE%A2/Unicode%E7%9A%84CLDR%E6%9C%89Emoji%E7%BF%BB%E8%AF%91%E6%96%87%E5%AD%97%EF%BC%8C%E4%BD%86%E6%96%B0%E7%89%88%E7%BC%BA%E5%B0%91%E4%BA%86%E5%87%A0%E5%8D%81%E4%B8%AA)

这导致部分 emoji 在 PR 中被移除：

![image](https://github.com/user-attachments/assets/5f6cfc42-7949-45a3-8b08-dfc541468c24)

**Comment by qingtian805** [comment]
Not only regional indicator symbols are missing. All family emojis are missing, too. Here is a complete list about missing emoji:
不止区域指示符缺失，所有的家庭 emoji 也缺失了。这是一份缺失 emoji 的完整列表：

``` text
//区域指示符 a-z 缺失 不在Full List中
1f1e6 a
1f1e7
1f1e8
1f1e9
1f1ea
1f1eb
1f1ec
1f1ed
1f1ee
1f1ef
1f1f0
1f1f1
1f1f2
1f1f3
1f1f4
1f1f5
1f1f6
1f1f7
1f1f8
1f1f9
1f1fa
1f1fb
1f1fc
1f1fd
1f1fe
1f1ff z

//各种家庭 缺失
1f468-200d-1f466
1f468-200d-1f466-200d-1f466
1f468-200d-1f467
1f468-200d-1f467-200d-1f466
1f468-200d-1f467-200d-1f467
1f468-200d-1f468-200d-1f466
1f468-200d-1f468-200d-1f466-200d-1f466
1f468-200d-1f468-200d-1f467
1f468-200d-1f468-200d-1f467-200d-1f466
1f468-200d-1f468-200d-1f467-200d-1f467
1f468-200d-1f469-200d-1f466
1f468-200d-1f469-200d-1f466-200d-1f466
1f468-200d-1f469-200d-1f467
1f468-200d-1f469-200d-1f467-200d-1f466
1f468-200d-1f469-200d-1f467-200d-1f467
1f469-200d-1f466
1f469-200d-1f466-200d-1f466
1f469-200d-1f467
1f469-200d-1f467-200d-1f466
1f469-200d-1f467-200d-1f467
1f469-200d-1f469-200d-1f466
1f469-200d-1f469-200d-1f466-200d-1f466
1f469-200d-1f469-200d-1f467
1f469-200d-1f469-200d-1f467-200d-1f466
1f469-200d-1f469-200d-1f467-200d-1f467

//西装革履的人
1f574-fe0f-200d-2640-fe0f 不在full list中，但在上版本中有
1f574-fe0f-200d-2642-fe0f 不在full list中，但在上版本中有

1f9b5 腿 缺失

e50a 涩谷区109大厦 Private Use Character 不在full list中，但在上版本中有
```

**Comment by 88250** [comment]
Fixed in https://github.com/siyuan-note/siyuan/pull/12051
