### ISSUE TITLE
无法剪藏的网页

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11962]
https://metahub.top/archives/29/

![image](https://github.com/user-attachments/assets/39b3bf76-5601-4681-b995-c54d58e0ea31)

**Comment by 88250** [comment]
这个全是自定义标签，处理不了啦：

![image](https://github.com/user-attachments/assets/78f90ed3-f92d-459c-b01b-01a655bf0674)

**Comment by 88250** [comment]
需要升级浏览器剪藏扩展，这个改动不拉进版本了。
