### ISSUE TITLE
编辑数据库单元格，即使过程中条目不显示也需要能应用编辑

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11965]
### In what scenarios do you need this feature?

比如这个主键就没法编辑，条目不显示之后就留下一个没用的输入框：

[视频.webm](https://github.com/user-attachments/assets/d97a5db8-03d5-4eb7-b98c-06cf8e3b423f)

再比如这个多选，条目不显示之后就不能响应了：

[视频.webm](https://github.com/user-attachments/assets/4e791a89-39f9-4233-96e5-9b4bb3cac8ac)

还有这个默认填充也失效了：

[视频.webm](https://github.com/user-attachments/assets/56e98bd6-4406-49b1-8cb1-8e55971a515c)

### Describe the optimal solution

像 Notion 这样，条目不显示出来也能编辑：

https://github.com/siyuan-note/siyuan/assets/78434827/11646dbc-842a-4339-8d85-c5110d93fc19

**Comment by TCOTC** [comment]
https://ld246.com/article/1721881842396

**Comment by 88250** [comment]
这部分逻辑比较复杂，不考虑再变动了，否则可能引入更多问题。

编辑框不消失的问题 @Vanessa219 抽空看看。

**Comment by TCOTC** [comment]
@88250 如果这个做不了，我觉得所有会把新增条目筛选掉的情况下都应该禁用添加按钮

**Comment by TCOTC** [comment]
具体操作上来说，要么是按钮不可点击，要么是点击之后不新增条目再弹出提示。反正就是不应该新增条目

**Comment by TCOTC** [comment]
我等会再提一个 issue

**Comment by 88250** [comment]
那就不方便了



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月17日(周六) 中午12:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 编辑数据库单元格，即使过程中条目不显示也需要能应用编辑 (Issue #11965)




 
@88250 如果这个做不了，我觉得所有会把新增条目筛选掉的情况都应该直接禁用添加按钮

**Comment by 88250** [comment]
现在的设计较为折中



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月17日(周六) 中午12:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 编辑数据库单元格，即使过程中条目不显示也需要能应用编辑 (Issue #11965)




 
具体操作上来说，要么是按钮不可点击，要么是点击之后不新增条目再弹出提示。反正就是不应该新增条目

**Comment by TCOTC** [comment]
这是另一种方案： #12270 ，这个方案就不用管编辑框了
