### ISSUE TITLE
:sparkles:嵌入块支持 `转换为`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11976]
### In what scenarios do you need this feature?

- [ ] 转换为块引用 https://ld246.com/article/1720958573868
- [ ] 转换为……

只有嵌入块 SQL 为 `select * from blocks where id='20240714202709-as0b4sr'` 这种格式，并且有符合条件的块时，右键菜单才出现 `转换为`

![image](https://github.com/user-attachments/assets/ae8fa76c-791b-4afa-b25a-d1231745b578)

**Comment by 88250** [comment]
不考虑了，可能通过插件实现更好一些。

**Comment by TCOTC** [comment]
用户需求：https://ld246.com/article/1740478509989
