### ISSUE TITLE
导入 `[[wikilink]]` 时锚文本使用模板变量 `{{.text}}`

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#1197]
还是直接替换成 `{{.text}}` 比较好，这些笔记里原来的链接全都是 `[[另一条笔记的名字]]`

![导入旧笔记包含了路径](https://user-images.githubusercontent.com/32661922/105179827-c252de00-5b64-11eb-93c7-735f5e5b1330.gif)

**Comment by deerainw** [comment]
https://user-images.githubusercontent.com/32661922/105181140-64bf9100-5b66-11eb-908b-71611ee68dd6.mp4

**Comment by 88250** [comment]
谢谢提议。

* 如果原文里是 `[[wikilink]]` 的话使用 `((id "{{.text}}"))`
* 如果原文里是 `[[wikilink|text]]` 的话使用 `((id "text"))`

**Comment by deerainw** [comment]
@88250 

反链里的显示变成了 `{{.text}}`

**Comment by deerainw** [comment]
啊不对，重启软件之后又没问题了。

**Comment by 88250** [comment]
如果用了自动升级的话，可能不太稳，手动安装顶顶。如果没用自动升级的话，麻烦帮忙留一下重现步骤，感谢。

**Comment by deerainw** [comment]
这个情况本身倒是可以稳定复现，第一次导入文件夹之后，有的反链会显示 `{{.text}}`，有的反链能正常显示，反正软件重启一下之后所有的显示就正常了。

有一个文件被链接了两次，其中一条反链正常显示，另外一条反链显示不正常，我拿别的编辑器打开这几个简短文件看了看，也没对比出有什么问题。包括软件重启前后，这些文件本身的内容也没变化。

**Comment by 88250** [comment]
好的，后面有时间会仔细看看的，这个目前先忽略一下，谢谢。
