### ISSUE TITLE
Improve database date field pasting

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#11973]
希望数据库日期列支持纯文本粘贴

### In what scenarios do you need this feature?

从别处复制类似2024-07-14 13:06的文本，粘贴到日期列

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
确实 `2024-07-14 13:18` 这样的格式不支持粘贴

**Comment by TCOTC** [comment]
用户需求：

![image](https://github.com/user-attachments/assets/350ba140-7d80-42e7-bd1a-48ed99802f4e)
