### ISSUE TITLE
lock permission failed

### ISSUE THREAD

**Issue by techdixie** [siyuan-note/siyuan#11970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

according to the log "lock workspace failed". With a little research it looks like its supposed to delete and recreate a .lock everytime it restarts and for some reason is unable to do so.  Any help would be great. I'm new at this. SiYuan is running through Dockge on a synology nas. I have no extensions running.

### Expected result

That the program would launch.

### Version environment

```markdown
- Version: 3.3?
- Operating System: Docker/Synology
- Browser (if used):
```

### Log file

E 2024/07/13 21:35:34 working.go:455: lock workspace [/siyuan/workspace/] failed: open /siyuan/workspace/.lock: permission denied

**Comment by 88250** [comment]
Please pay attention to whether the user has read and write permissions for the file system after mounting the data volume.
