### ISSUE TITLE
标题前方无法输入空格，通过“转换为”却可以保留空格

### ISSUE THREAD

**Issue by hihaojie** [siyuan-note/siyuan#11971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

标题前方不可输入空格，但通过“转换为”得到的标题，前方可以有空格。

此外，标题可以输入“`tab`”空白字符，且刷新后不会消失。

上述输入在刷新后（空格、Tab字符）不会消失，但是在标题后方进行任意输入，都会使空白字符消失。

### Expected result

标题最前端禁止输入任何空白字符，或标题最前端支持输入空白字符。

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/c0b7d9f0-b584-4531-990d-ad273f3a322e)

### Version environment

```markdown
- Version: 3.1.0
- Operating System: Windows10
- Browser (if used):
```

### Log file

None

**Comment by 88250** [comment]
感谢反馈，改进为转换时去掉开头的空白。

这个改动不拉进版本了。
