### ISSUE TITLE
请求新增开启/关闭文档的 API

### ISSUE THREAD

**Issue by M2uyo** [siyuan-note/siyuan#11979]
### In what scenarios do you need this feature?
想自己做个关闭指定窗口时重新打开并并钉住的插件
真的很需要 某个文档始终不被关闭

#### 新增API
1. 开启文档
2. 关闭文档
3. 钉住文档
#### 新增事件
1. 文档打开事件
2. 文档关闭事件

**Comment by leolee9086** [comment]
开启文档的api在这里可以找到:https://github.com/siyuan-note/plugin-sample/blob/main/src/index.ts
![image](https://github.com/user-attachments/assets/dfb11e21-39ea-4a61-a7bd-13aa8ff7d1b3)

这个方法的实现在:https://github.com/siyuan-note/siyuan/blob/master/app/src/plugin/API.ts
![image](https://github.com/user-attachments/assets/74ecf555-6104-4347-a989-2aaa74baf31c)

文档事件可以监听protyle的相关事件,也就是
```js
                    this.eventBus.on("loaded-protyle-static", this.eventBusLog);
                    this.eventBus.on("loaded-protyle-dynamic", this.eventBusLog);
                    this.eventBus.on("switch-protyle", this.eventBusLog);
                    this.eventBus.on("destroy-protyle", this.eventBusLog);
```                
相关示例代码同样在:https://github.com/siyuan-note/plugin-sample/blob/main/src/index.ts

**Comment by Muu-yo** [comment]
感谢，有时间我自己尝试一下

**Comment by Muu-yo** [comment]
@leolee9086  不知道我写的哪里有差错, 当我关闭 钉住的文档时就会报错(纯后端, 不是很能看明白前端的报错 (╯︵╰,))
```javascript
    async onload() {
        this.eventBus.on("destroy-protyle", this.OnDestroy_protyle);
    }

    private async OnDestroy_protyle({detail}: any) {
        if (detail.protyle.model.headElement.classList.contains("item--pin")) {
            console.log("inner", detail.protyle.block.id)
            await openTab({
                app: this.app,
                doc: {
                    id: detail.protyle.block.id
                },
                keepCursor: true
            })
        }
    }
````

![image](https://github.com/user-attachments/assets/42a90211-629b-47c5-8abd-1704e77c8839)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by code-lixm** [comment]
钉住文档的API现在有了么，求助

**Comment by TCOTC** [comment]
@code-lixm 这是我问 AI 的，你可以参考一下试试：

![Image](https://github.com/user-attachments/assets/b2912a64-df0e-4836-88c9-5e897dd07ad2)
