### ISSUE TITLE
Support find replace block ref anchor text

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11978]
无法替换锚文本

### In what scenarios do you need this feature?

https://ld246.com/article/1720960668888

我这里也不行

### Describe the optimal solution

1. 替换动态锚文本，自动变成静态锚文本
2. 替换静态锚文本

**Comment by 88250** [comment]
替换类型 中新增 引用锚文本：

![image](https://github.com/user-attachments/assets/53a2c3f2-ebe8-44f3-aa5f-c476e6ec0c4f)

**Comment by TCOTC** [comment]
我觉得最好放到这里的附近：

![image](https://github.com/user-attachments/assets/297b23a8-cd7e-4938-80eb-a8e273a671cb)

**Comment by 88250** [comment]
这个和备注类似，所以放在备注下面了。
