### ISSUE TITLE
Add plugin Event `opened-notebook` & `closed-notebook`

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#11974]
### In what scenarios do you need this feature?

插件需要根据笔记本打开、关闭来决定是否重新执行一些查询，已获得最新的状态。

### Describe the optimal solution

- on-box-opened
  - {detail}: box id
  - when: 笔记本打开、并执行完重新索引之后
- on-box-closed
  - {detail}: box id
  - when: 笔记本关闭之后

**Comment by 88250** [comment]
> when: 笔记本打开、并执行完重新索引之后

索引是否完成需要通过调用接口 `/api/sqlite/flushTransaction` 后才能确定。

**Comment by 88250** [comment]
另外，也可以参考这个 https://github.com/siyuan-note/siyuan/issues/8814#issuecomment-1653780601
