### ISSUE TITLE
Improve database template field exporting

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11988]
https://github.com/siyuan-note/siyuan/issues/11945#issuecomment-2227692627

**Comment by TCOTC** [comment]
[数据库.sy.zip](https://github.com/user-attachments/files/16233105/sy.zip)

- [ ] 换行
- [ ] 符号 `|`
- [ ] 导出时应该根据模板列的设置来决定是否需要换行：
   - 开启换行：正常换行
   - 关闭换行：连续的换行合并为一个空格
- [ ] `<no value>` 没必要显示，像数据库那样为空就行了
- [ ] 希望样式也能显示出来，而不是纯文本

![image](https://github.com/user-attachments/assets/3a8c5661-2c87-4d90-abe0-67b79760df93)

**Comment by 88250** [comment]
最后一个样式显示搞不了，只能以纯文本导出，前面几个可以改进，感谢反馈。
