### ISSUE TITLE
标题块更新时间不及时

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11983]
关联 https://ld246.com/article/1721020924069/comment/1721024411643#comments

要刷新一下才会更新：

[视频.webm](https://github.com/user-attachments/assets/59035333-f659-4c8a-92d3-a5d5be7e9af9)

**Comment by 88250** [comment]
这个没有办法改进了，只能在内核中计算更新时间，但是不做前端推送，先关闭了。
