### ISSUE TITLE
改进空内容块中使用 `Delete`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11984]
1. 上次 #11732 改进了列表内的情况，但撤回的问题还没修好 https://github.com/siyuan-note/siyuan/issues/11732#issuecomment-2206643369
2. 用户希望在任意的空段落块按 Delete 都是这个逻辑：删除当前块，后面的块上移 https://ld246.com/article/1721014259146/comment/1721024895264#comments

**Comment by Vanessa219** [comment]
1. 已修改
2. 可以使用 Backspace

**Comment by 88250** [comment]
这个改动就不拉进版本了。
