### ISSUE TITLE
全局搜索时，`输入为空时将显示最近更新的块` 在不同设备上的结果不一致

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11986]
关联 https://ld246.com/article/1721008956793

**Comment by 88250** [comment]
这是正常预期，这个不会被同步的，最近打开的文档 也是一样。

**Comment by TCOTC** [comment]
最近编辑时间不是写在文件里的吗？

**Comment by 88250** [comment]
最近更新是单独记录的



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年7月15日(周一) 下午5:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 全局搜索时，`输入为空时将显示最近更新的块` 在不同设备上的结果不一致 (Issue #11986)




 
最近编辑时间不是写在文件里的吗？
