### ISSUE TITLE
`Shift+Click` 点击资源文件无效

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11980]
https://ld246.com/article/1721017151634

如果焦点在编辑器内就不行，无法使用默认程序打开：

https://github.com/user-attachments/assets/76c63847-cfde-4d83-999b-6ad828546c0e

**Comment by 88250** [comment]
我这里目前已经无法重现问题，请再测试看看。

**Comment by TCOTC** [comment]
跨块的不能稳定复现，但在块内的是能复现的：

[视频.webm](https://github.com/user-attachments/assets/822fb15f-3bab-475f-be17-c3ecba962d4c)

**Comment by 88250** [comment]
@Vanessa219

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
