### ISSUE TITLE
`所见即所得` 与 `导出预览` 分屏时大纲有点问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11981]
### 01 大纲只能操作导出预览：

[视频.webm](https://github.com/user-attachments/assets/76e8173e-39ff-442f-8d67-4d8a0cf341a6)

### 02 另一种表现：

- #12464

### 03 点击大纲会把文档切换为导出预览：

[视频.webm](https://github.com/user-attachments/assets/20221833-3d36-49c2-aa9c-7dfc1747d085)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by TCOTC** [comment]
点击一下大纲，焦点就跑到右边的页签去了，没有恢复到原来的焦点：

[视频.webm](https://github.com/user-attachments/assets/e9255cfb-44c6-4754-ab3d-f434e4a293a0)

**Comment by Vanessa219** [comment]
点击大纲后，焦点就不在编辑器上了，再点击标题就会选取最后一个编辑器。

**Comment by TCOTC** [comment]
为什么不能把焦点恢复到最后操作的页签呢？

**Comment by TCOTC** [comment]
- `导出预览` 切换为 `所见即所得` 时没有去除一级标题
- `所见即所得` 切换为 `导出预览` 时没有增加一级标题

[视频.webm](https://github.com/user-attachments/assets/2bdd4df7-86e2-46a4-b3c4-df6d559e4d4c)

**Comment by TCOTC** [comment]
还是会把所见即所得的文档变成导出预览：

1. 打开 A B 两个文档
2. A 文档分屏到右侧，然后切换为导出预览模式
3. 点击左侧的 B 文档
4. 点击大纲（不是标题）
5. 点击一个标题

[视频.webm](https://github.com/user-attachments/assets/3d1fbd50-b0e0-47a3-811e-fe78612233b1)
