### ISSUE TITLE
在数据库中使用引用时，与被引用的块的双向链接出现在关系图中

### ISSUE THREAD

**Issue by ljh257110** [siyuan-note/siyuan#11989]
### In what scenarios do you need this feature?

当前在数据库中使用引用，比如使用引用作为主键，发现在关系图中并没有显示双向链接

### Describe the optimal solution

在数据库中使用引用，在关系图中也显示双向链接

**Comment by 88250** [comment]
你好，抱歉关系图不打算再做调整了，见谅。
