### ISSUE TITLE
Abnormal heading block update time

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11985]
标题块更新时间错误

修改标题块时，应该只更新上级标题块的更新时间，但目前是把文档中所有标题块的更新时间也更新了：

[视频.webm](https://github.com/user-attachments/assets/b50b2937-34a0-4756-8e6a-a10a66cfe988)

关联 https://ld246.com/article/1721020924069/comment/1721025165520#comments

**Comment by TCOTC** [comment]
没修好，还是同样的问题：

[视频.webm](https://github.com/user-attachments/assets/5a55587f-3fb9-4a3c-9866-eb556dd884cd)

**Comment by 88250** [comment]
感谢反馈，下个版本继续修复 https://github.com/siyuan-note/siyuan/issues/11996
