### ISSUE TITLE
新增汇总列时，如果该数据库只有一个关联列，则自动关联

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11982]
### In what scenarios do you need this feature?

很多时候只有一个关联列，增加汇总列时自动选择的话就可以省去手动选择这一步了：

![image](https://github.com/user-attachments/assets/e6211275-237a-4089-a04a-fdc070071d9a)

![image](https://github.com/user-attachments/assets/f4a93516-a8ee-4be6-b5ef-1cdfde6ff3b6)

### Describe the optimal solution

。

**Comment by 88250** [comment]
不考虑了，因为新建汇总时如果不想关联则还需要取消，所以用户手动关联更好。
