### ISSUE TITLE
把 `新建笔记本` 从文档树 `更多` 菜单中移出

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#11998]
### In what scenarios do you need this feature?

- 新用户不知道在 `更多` 里新建笔记本，上手的摩擦比较大，需要把按钮放到一个更显眼的地方
- 其他笔记软件新建文档（Notion）或者新建文件夹（Obsidian）的按钮都不是塞到菜单里的

### Describe the optimal solution

放中间：

![image](https://github.com/user-attachments/assets/604d3bf1-8054-4047-a708-c1e0a233315f)

**Comment by 88250** [comment]
这个不改变了。默认的空白页也有入口的：

![image](https://github.com/user-attachments/assets/8ab98e96-c373-4136-959a-4ce8507a9b52)

**Comment by TCOTC** [comment]
但新用户首先看到的是用户指南，不是空白页。所以新用户不知道在哪里新建笔记本
