### ISSUE TITLE
Abnormal heading block update time

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#11996]
https://github.com/siyuan-note/siyuan/issues/11985#issuecomment-2229896160

**Comment by TCOTC** [comment]
还是有问题，现在变成整个文档的块更新时间全部修改了：

[视频.webm](https://github.com/user-attachments/assets/7ddb8eae-449e-4fed-b54b-365b34d2d37e)

**Comment by 88250** [comment]
这个是之前的逻辑，修改上级标题块会更新下方所有块更新时间。

考虑了下，这个逻辑还是去掉吧。
