### ISSUE TITLE
文件树拖拽和排序

### ISSUE THREAD

**Issue by walklty** [siyuan-note/siyuan#12]
0.19
1. 目前还没有找到更改文件位置(文件夹)的方法,只能在资源管理器里更改后重启软件.
2. 目前文件树似乎是按创建时间排序的, 希望能增加选项按照A-Z方式排序.

**Comment by 88250** [comment]
后续版本会进行实现，感谢反馈。

**Comment by 88250** [comment]
文档移动在 https://github.com/siyuan-note/siyuan/issues/244 中试下，暂时不支持拖拽。

**Comment by 88250** [comment]
排序在 https://github.com/siyuan-note/siyuan/issues/335 中支持。

谢谢建议，我关闭了。
