### ISSUE TITLE
在搜索界面点击文档末尾，光标不会跳到最后一个块或者新建一个块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12009]
有时候通过搜索找到文档之后就直接开始编辑了，所以希望在搜索窗口编辑的体验和在页签编辑的体验更接近。

编辑文档的时候是可以的，搜索的时候不行：

[视频.webm](https://github.com/user-attachments/assets/0effce56-a68c-47aa-9200-5e9c1a456290)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
