### ISSUE TITLE
快速调整字号的时候可以提示字号大小

### ISSUE THREAD

**Issue by ThemanRonin** [siyuan-note/siyuan#12007]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/4a9204b2-1ea7-4fe8-8aca-c0164c7855df)
设置中的`快速调整字号`功能。可以按住ctrl+滚轮的时候快速调节字号，方便快捷的调节内容的字体大小，但是缺少一个**字号的提示**，如果想回到默认的状态无法准确调节，只能凭感觉，另外添加提示功能也可以快速知道当前字号的大小。

同时添加一个快捷键功能`重置字号`， 按下后可快速将字号调节到默认

### Describe the optimal solution

- 添加字号调节时的提示，例如`字号的大小`或`百分比`
- 添加一个`重置字号`快捷键， 按下后可快速将字号调节到默认

# 参考1
![recording](https://github.com/user-attachments/assets/704540a7-6121-43e0-afef-b93d8259e2d2)

# 参考2
![recording](https://github.com/user-attachments/assets/f5a34e0e-e9ba-4977-aef5-743552c39a41)

**Comment by TCOTC** [comment]
确实可以在整个界面的中下方整一个半透明的浮窗显示字号 2 秒

**Comment by AvoidantPerDis** [comment]
赞同

**Comment by Muu-yo** [comment]
> 确实可以在整个界面的中下方整一个半透明的浮窗显示字号 2 秒

![image](https://github.com/user-attachments/assets/155bbe34-ff29-4829-be06-949c3962f033)

IDEA这种就很好

**Comment by TCOTC** [comment]
应该在调整完字号之后再固定显示一段时间。目前感觉不太稳定：

[视频.webm](https://github.com/user-attachments/assets/94a33be5-e89e-42d4-bbcf-53e243c32537)
