### ISSUE TITLE
Improve HTML match clipping

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12005]
剪藏能否兼容Kimi Chat等平台的公式输出

### In what scenarios do you need this feature?

思源直接复制OpenAI的数学公式到软件里是可以转化为Markdown公式的
但是[Kimi](https://kimi.moonshot.cn/chat/)、[豆包](https://www.doubao.com/chat/)、[chatbox](https://web.chatboxai.app/)、[DeepSeek](https://chat.deepseek.com/)等AI软件/网站输出的数学公式，都无法正常通过直接复制之后粘贴在思源笔记里，渲染正确公式样式

我简单看了下，貌似他们公式复制到剪贴板都是一样的，除了和openai一样用的MathML，在span.katex-html还附带了一堆样式
![Clip_2024-07-17_16-40-18](https://github.com/user-attachments/assets/1c752293-68e4-4576-899d-d97ce1197e2b)

### Describe the optimal solution

希望思源笔记能粘贴渲染[Kimi](https://kimi.moonshot.cn/chat/)、[豆包](https://www.doubao.com/chat/)、[chatbox](https://web.chatboxai.app/)、[DeepSeek](https://chat.deepseek.com/)等AI软件/网站输出的数学公式

### Describe the candidate solution

无

### Other information

无

**Comment by 5kyfkr** [comment]
支持，我也经常在这些上面问公式

**Comment by 88250** [comment]
* 豆包的无法解析，里面没有 tex 公式内容，只有渲染好的 svg
* chatbox 暂时不考虑了

**Comment by 88250** [comment]
kimi 和 deepseek 在它们的网页上复制的时候自身做了处理，会去掉 annotation 节点（以 kimi 为例）：

原始 DOM：

![image](https://github.com/user-attachments/assets/396b3d52-bda2-4e6d-b455-2ea6b13d354e)

但是复制的 DOM 少了 annotation 节点：

![image](https://github.com/user-attachments/assets/3f6da626-e1cf-4a73-8f06-da88f43b869f)

少了 anno 节点的话就无法解析了，所以这个 issue 没有办法解决，抱歉。
