### ISSUE TITLE
云端的配置可否单独拆出来为一个文件

### ISSUE THREAD

**Issue by Muu-yo** [siyuan-note/siyuan#12002]
### In what scenarios do you need this feature?

同步到git: 下简称`同步`
### 痛点
S3的密钥在 conf/conf.json 里面 如果同步该文件则无法单独提交 conf/conf.json 里面的非云端配置内容
### 使用场景
使用git新建一个工作空间(带有旧版本的设置) 并希望可以同步两个工作空间的设置

git 同步配置文件 conf/ data/非笔记本文件夹 
### 导致问题
两个工作空间的云端配置应该是不同的
而同步会导致密钥也进行同步(其实并不想同步密钥)

### Describe the optimal solution

.

**Comment by 88250** [comment]
如果使用其他同步方式，最好不要同步 conf 文件夹，仅同步 data 文件夹。

PS：不建议使用任何第三方同步方式，如果需要自行扩展同步，请参考同步模块 https://github.com/siyuan-note/dejavu

**Comment by TCOTC** [comment]
> git 同步配置文件 conf/ data/非笔记本文件夹

楼主的需求应该是用 git 管理笔记数据以外的配置数据文件

**Comment by Muu-yo** [comment]
> 如果使用其他同步方式，最好不要同步 conf 文件夹，仅同步 data 文件夹。

@88250 主要是希望可以讲一个 conf.json 文件拆分成 conf.json 和 private_conf.json (密钥/账号等等不应该被共享的数据(

附上我现在的 gitignore 文件
```gitignore
# Ignore everything
*

# Except these directories and their contents
!/conf/
!/conf/**
!/data/
!/data/snippets/
!/data/snippets/**
!/data/emojis/
!/data/emojis/**
!/data/plugins/
!/data/plugins/**
!.gitignore

```

**Comment by 88250** [comment]
主线上目前没有这个需求，所以估计不会开发，见谅。
