### ISSUE TITLE
Improve database relation and rollup field exporting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12003]
改进数据库关联字段、汇总字段导出

[数据库 - 汇总 & 关联.sy.zip](https://github.com/user-attachments/files/16570748/-.sy.zip)

- [ ] 需要在单元格内正常换行
- [ ] 符号 `|` 需要转义

![image](https://github.com/user-attachments/assets/0c430c34-8308-4257-8300-5131d4d48a69)

**Comment by TCOTC** [comment]
- @88250 #11945 和 #11988 都改好了，这个也得改一下

**Comment by TCOTC** [comment]
关联和汇总的换行没有用：

[视频.webm](https://github.com/user-attachments/assets/61fa32f5-8c76-4bda-b886-90cb728a08cb)

**Comment by 88250** [comment]
感谢，稍后提交改进。
