### ISSUE TITLE
改进云端界面文案

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12011]
有用户不知道云端界面里的 `清理` 有什么用，我觉得应该可以在这里前面加一句：`删除所有未引用的云端快照和相关数据对象`：

![image](https://github.com/user-attachments/assets/3ccf835d-aa54-4a08-a17d-eb31b8b2e4d0)

**Comment by 88250** [comment]
感谢反馈，稍后改进。

**Comment by 88250** [comment]
这个改动不拉进版本了。
