### ISSUE TITLE
带样式导出pdf和html

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1201]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
导出pdf或html与别人分享，需要保持目前笔记本中设置好的字体、字号、颜色等各种标记样式。

### 描述最优的解决方案 Describe the optimal solution
严格按照当前思源笔记的主题样式导出

### 描述候选解决方案 Describe the candidate solution
导出pdf或html可以专门定制样式

**Comment by Vanessa219** [comment]
如果选了带背景的主题，pdf 导出的边距依旧是白色，比较难看。如果不使用背景的话，字如果白色的话，将看不清。

HTML 可以考虑

**Comment by roverway** [comment]
对于pdf，typora的处理方法比较合适：如果当前主题是浅色背景，按当前主题导出pdf；如果当前主题是深色背景，有如下提示：
![image](https://user-images.githubusercontent.com/657850/105260592-04ae0680-5bc9-11eb-9a8d-13fcc135ac64.png)。

这样就最大可能的保证导出样式和笔记内部阅读样式的一致了。

**Comment by Vanessa219** [comment]
收到
