### ISSUE TITLE
Some scenes will indicate abnormal status

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#12016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在二级标题下
1. 回车
2. 输入【-】

报错【状态异常】

注：尝试输入其他任意字符情况也是一样

### Expected result

修复

### Screenshot or screen recording presentation

![GIF 2024-7-18 16-19-32](https://github.com/user-attachments/assets/eaabd91d-6c65-4503-a1d1-101317849864)

### Version environment

```markdown
- Version: v3.1.1
- Operating System: Windows 11
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16280007/siyuan.log)

**Comment by TCOTC** [comment]
把这个文档上传一下

**Comment by Temacc0531** [comment]
> 我这里复现不了，你把这个文档上传一下看看

我把这文档在文档树导出导入到个新的工作空间也不能复现，主要是让D大看看日志，里面有很多报错

**Comment by TCOTC** [comment]
重建索引再试试？

**Comment by Temacc0531** [comment]
> 重建索引再试试？

试过了没啥用😂

**Comment by Temacc0531** [comment]
我整了一个可以复现的最小工作空间发 @88250 邮箱了

**Comment by 88250** [comment]
感谢反馈，已经定位到问题，在 https://github.com/siyuan-note/siyuan/issues/11959 中解决。

**Comment by Temacc0531** [comment]
> 感谢反馈，已经定位到问题，在 #11959 中解决。

这个我看是数据库块的原因吗，我还没怎么用到数据库块，这个是帮助文档里面的自带数据库块影响到了吗

另外，D大修完这个能先打个测试版吗，这个缺陷有点难受

**Comment by 88250** [comment]
晚上打



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 24, 2024 17:56 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Some scenes will indicate abnormal status(Issue #12016)




  
感谢反馈，已经定位到问题，在 #11959 中解决。
  
这个我看是数据库块的原因吗，我还没怎么用到数据库块，这个是帮助文档里面的自带数据库块影响到了吗
 
另外，D大修完这个能先打个测试版吗，这个缺陷有点难受
