### ISSUE TITLE
需求：剪藏网页将 URL 和原网页标题添加至页面自定义属性 (Features: Add url and title to page's custom attribute when clipping web pages)

### ISSUE THREAD

**Issue by Fradeet** [siyuan-note/siyuan#12017]
### In what scenarios do you need this feature?

目前， SiYuan 网页剪藏插件会使用一个 Markdown 无序列表存放网页 URL，标题等。这不够结构化，信息非常难被插件（或其他脚本）解析。

---
English Machine Translate:
At present, the SiYuan web-clipper plugin uses a Markdown list to store web urls, titles, etc. This is not structured enough, and the values are very difficult for plug-ins (or other scripts) to parse.

### Describe the optimal solution

SiYuan 有存放键值对的”自定义属性“功能，个人认为可以将它利用，存放 URL ，标题等重要的数据。

---
English Machine Translate:
SiYuan has the feature of "custom attribute" for storing key-value pairs. It can be used to store data such as urls and titles.

### Other information

个人写了一个提交：https://github.com/siyuan-note/siyuan-chrome/pull/9
关于数据结构化，本人也发过一个帖子：[导出数据库中文档的字段到 YAML-front-matter 有没有搞头？-链滴](https://ld246.com/article/1720965034227)

**Comment by 88250** [comment]
你好，这个还是不添加了，如果需要的话请自己打包浏览器扩展，感谢。
