### ISSUE TITLE
Improve HTML code block clipping

### ISSUE THREAD

**Issue by DearZack** [siyuan-note/siyuan#12014]
chrome插件保存的公众号文章代码显示异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

chrome插件版本：1.2.20
运行终端：windows11
客户端版本：V3.1.1

https://mp.weixin.qq.com/s/Crmm_AjCS3TBxmkPefg0oA
可以使用上面的文章保存一下
代码块显示异常

### Expected result

chrome插件版本：1.2.20
运行终端：windows11
客户端版本：V3.1.1

https://mp.weixin.qq.com/s/Crmm_AjCS3TBxmkPefg0oA
可以使用上面的文章保存一下
代码块显示异常

### Version environment

```markdown
chrome插件版本：1.2.20
运行终端：windows11
客户端版本：V3.1.1

https://mp.weixin.qq.com/s/Crmm_AjCS3TBxmkPefg0oA
可以使用上面的文章保存一下
代码块显示异常
```

### Log file

chrome插件版本：1.2.20
运行终端：windows11
客户端版本：V3.1.1

https://mp.weixin.qq.com/s/Crmm_AjCS3TBxmkPefg0oA
可以使用上面的文章保存一下
代码块显示异常

**Comment by 88250** [comment]
感谢反馈， 版本改进。
