### ISSUE TITLE
剪藏链滴文章代码块异常

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#12015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

待剪藏页面[https://ld246.com/article/1721269102151](url)

### Expected result

![微信图片_20240718133606](https://github.com/user-attachments/assets/f1dd779f-4cda-49a3-99c5-0176bb1a6b19)

### Version environment

```markdown
- Version: V3.1.1
- Operating System: Win10
- Browser (if used):
```

### Log file

前藏效果不佳，见上面示图

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/10987
