### ISSUE TITLE
改进中国地区集市包下载

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12026]
https://ld246.com/article/1721365124799

逻辑或许跟这个差不多：

如果 githubURL 无法访问或下载速度较慢，则尝试使用 ghproxyURL 来加速访问 GitHub 上的资源

https://github.com/siyuan-note/siyuan/blob/687421fe62beb6bddd46c69a263c485bb1fe6619/kernel/model/updater.go#L138-L151

相关的函数好像是这个：

https://github.com/siyuan-note/siyuan/blob/687421fe62beb6bddd46c69a263c485bb1fe6619/kernel/bazaar/package.go#L549-L585

**Comment by 88250** [comment]
链滴数据中心默认就是用的国内七牛云，并且加了 CDN。

**Comment by TCOTC** [comment]
> 用的国内七牛云，并且加了 CDN

1. 这部分代码是在哪个地方？
2. 是连不上链滴/七牛云就不能下载了吗？

**Comment by 88250** [comment]
bazaar 项目上
是的，网络要能连通七牛云



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年7月24日(周三) 中午12:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 改进中国地区集市包下载 (Issue #12026)




  
用的国内七牛云，并且加了 CDN
   
这部分代码是在哪个地方？
 
是连不上链滴/七牛云就不能下载了吗？
