### ISSUE TITLE
Importer which is similar to Obsidian importer

### ISSUE THREAD

**Issue by theisjendal** [siyuan-note/siyuan#12024]
### In what scenarios do you need this feature?

To increase the engagement of this application, having easy transfer from other PKM tools would be very beneficial.
Personally I already have a structure in a different PKM, but would like to use this tool; however, the transfer in markdown is not sufficient. Thus a more customised importer would be very useful, as I believe for many others. 

### Describe the optimal solution

It should be a easy import that sets up the program as close to the source tool. E.g., if the source is Obsidian, the structure would be different than if source is Notion.
Optimally it should be a process similar to:
Press import, select import program  (e.g. obsidian, notion), guide to import from that source, upload required files. 
SiYuan is now set up as close to the imported program structure.

### Describe the candidate solution

Example is in obsidian: https://help.obsidian.md/Plugins/Importer

### Other information
Feature is similar to the one described here but more detailed and motivated: https://github.com/siyuan-note/siyuan/issues/7048

**Comment by 88250** [comment]
Hello, SiYuan is an open-source project, this part is left to the community to contribute, thank you.
