### ISSUE TITLE
Improve HTML kbd clipping

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12027]
### In what scenarios do you need this feature?

关联 https://ld246.com/article/1721373461214

网页：https://handbook.glyphsapp.com/filtering/

1. 剪藏不了：

   ![image](https://github.com/user-attachments/assets/4282a8e9-eecf-48af-898a-3c3ef4ba2882)

2. 复制粘贴之后丢失符号：

   ![image](https://github.com/user-attachments/assets/94518e0a-11b6-4582-b7da-8f9f8f08cf18)

   ![image](https://github.com/user-attachments/assets/4d607b14-7a55-4ca5-a039-3ad872d5c719)

### Describe the optimal solution

。

**Comment by 88250** [comment]
1. 网页用的是 `aside` 标签，会被识别为侧栏被排除掉
2. 稍后改进

谢谢。
