### ISSUE TITLE
关闭 `保持全部展开` 时不应展开大纲

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12029]
https://ld246.com/article/1716649497110/comment/1721397583355#comments

**Comment by 88250** [comment]
这个不考虑调整了，因为修改标题时需要在大纲面板中看到修改结果。

**Comment by TCOTC** [comment]
但父级是始终可见的，不展开子级完全不影响「看到修改结果」：

[视频.webm](https://github.com/user-attachments/assets/8807b3db-6ff0-4ee9-ba34-4f80bf730749)

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
是不是点击了`保持全部展开`？

**Comment by TCOTC** [comment]
确实哦，原来这个按钮是这个用途，那关掉 `保持全部展开` 就没问题了。

不过我发现有另一个问题，**关闭** `保持全部展开` 时还会展开一次大纲：

[视频.webm](https://github.com/user-attachments/assets/23b4379d-3971-406f-8e30-23c16b0b1a06)

**Comment by TCOTC** [comment]
@88250 把 not planned 的 close 改一下
