### ISSUE TITLE
需求：重新加载

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#12021]
### In what scenarios do you need this feature?

换一个主题、开一个插件、更新主题插件……

### Describe the optimal solution

> 换一个主题、开一个插件、更新主题插件……

上面这些操作，很多时候会导致不能正常 显示/运行，需要 **重新加载** 才会正常 显示/运行，以前自定义表情哪里还有一个刷新，现在每次都需要关闭重新打开 SiYuan，很繁琐，所以希望提供 **重新加载按钮**。

**Comment by shuojie819** [comment]
@TCOTC  谢谢可以满足我的需求

> @88250  但是还是希望 SiYuan 可以提供一个专门的 **重载按钮或命令** ，上面的方法都不太……直接！
（个人观点：不要探索，要看就就会用，不要增加软件的使用难度）

**Comment by 88250** [comment]
加个刷新界面按钮对用户来说使用场景不明确，如果遇到上述问题，还是重启吧。

**Comment by shuojie819** [comment]
> 加个刷新界面按钮对用户来说使用场景不明确，如果遇到上述问题，还是重启吧。

想加 **重载按钮或命令** 主要是有集市（插件、主题……）、代码片段……这些都会有影响
Obsidian 中就有一个重新加载的命令
![图片](https://github.com/user-attachments/assets/f2df9a52-4475-41bf-afdf-20e4b0cb56eb)

> 当然，不加也没关系，有上述三种方法可以实现

**Comment by 88250** [comment]
欢迎提交相关插件。
