### ISSUE TITLE
改进 Windows 下块引用右键菜单快捷键显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12028]
- [ ] 在后台页签中打开 `Ctrl+Shift+./点击` → `Ctrl+Shift+. / Ctrl+点击`
- [ ] 在页签下侧打开 `Ctrl+Shift+Alt+./点击` → `Ctrl+Alt+. / Shift+点击`

p.s. 之前的描述有问题，修改了

**Comment by 88250** [comment]
我这里测试：

* Ctrl+点击 是后打开
* 我这里配置为 Ctrl+Shift+Alt+. 后可以正常下侧打开
  
  ![image](https://github.com/user-attachments/assets/a4d4a3a0-cc51-469b-abf4-bdae244347ce)
* 似乎不冲突

**Comment by TCOTC** [comment]
我没说清楚，第一点和第三点我指的是菜单上显示的快捷键有误：

![image](https://github.com/user-attachments/assets/b8c2b76e-b873-4260-a60a-3eb891f020e7)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
