### ISSUE TITLE
Improve indexing completeness when exiting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12039]
关闭应用时的索引问题

## 01

找个内容块多的文档，编辑标题，反复撤销和重做，然后关闭思源再打开，就会提示 `上次使用后未完成数据索引，请执行一次 [文档树 - 重建索引]。以后请完整退出程序后再关闭电脑` ：

[视频.webm](https://github.com/user-attachments/assets/3fe2c980-bee3-4f4c-92ea-a3703a2a2429)

[system-log.zip](https://github.com/user-attachments/files/16319872/system-log.zip)

## 02

关闭笔记本后立刻关闭思源：

[视频.webm](https://github.com/user-attachments/assets/eb97dbc1-c671-4fd4-ae9f-b78cb183a4c0)

**Comment by 88250** [comment]
这个是正常的，必须等数据库索引队列跑完。

**Comment by TCOTC** [comment]
为什么关闭的时候不等一等呢？

**Comment by TCOTC** [comment]
@88250

**Comment by 88250** [comment]
稍后改进看看。
