### ISSUE TITLE
支持引用数据库的单个条目

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12031]
在条目的右键菜单添加 `复制条目引用` （注意，不是复制块引用），在其他地方点击该引用可以直接打开数据库字段编辑面板 #12910（基本就像 Notion 那样）

引用的锚文本是动态的，跟随引用的条目主键变化（主键可能是纯文本，也可能是绑定块）

另外，需要像 #11520 一样支持多选条目后 `复制条目引用` 。

**Comment by TCOTC** [comment]
用户需求：

- https://ld246.com/article/1725596885614 第三点

**Comment by 88250** [comment]
单个条目不考虑引用了，引用只考虑收敛在块上。

**Comment by TCOTC** [comment]
那就不考虑动态锚文本了，更新后的需求是：

1. 支持复制条目链接
2. 点击链接后弹出条目的属性面板 / 数据库字段编辑面板

**Comment by TCOTC** [comment]
纯文本主键的条目是没有绑定块的，所以没法这样操作
