### ISSUE TITLE
Mac m1 下 siyuan 最新版本设置里下拉选项点击无反应

### ISSUE THREAD

**Issue by albertchendao** [siyuan-note/siyuan#12037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新到 siyuan 最新版本，点击设置-外观-代码块主题-明亮模式下代码块语法高亮主题-github 无反应，试了下其他下拉选项也无反应。

### Expected result

设置里下拉选项里的所有选项可以展示并选择

### Screenshot or screen recording presentation

<img width="1263" alt="image" src="https://github.com/user-attachments/assets/a54d3b86-2618-4ce9-a000-beb5c29963e2">

<img width="584" alt="image" src="https://github.com/user-attachments/assets/434a24d8-0453-48d9-b542-b8cbf504d80e">

<img width="1270" alt="image" src="https://github.com/user-attachments/assets/ae11de8d-9a6e-4a61-8942-56fba25f7e12">

### Version environment

```markdown
- Version: siyuan版本v3.1.1
- Operating System: MacOS Monterey 12.7.4
- Browser (if used):
```

### Log file

没找到 workspace 目录

**Comment by TCOTC** [comment]
Duplicate of #11929

**Comment by Hanochhu** [comment]
同样的问题，我的版本是 macos 13.6.4

**Comment by 88250** [comment]
Duplicate of #11929

**Comment by TCOTC** [comment]
楼主可以尝试一下刚刚发布的 v3.1.2 ，看看是否还有问题？

**Comment by Hanochhu** [comment]
> 可以尝试一下刚刚发布的 v3.1.2 ，看看是否还有问题？

还是有这个问题

**Comment by 88250** [comment]
请试下最新的 dev 版。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月4日(周日) 下午4:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] Mac m1 下 siyuan 最新版本设置里下拉选项点击无反应 (Issue #12037)




  
可以尝试一下刚刚发布的 v3.1.2 ，看看是否还有问题？
  
还是有这个问题

**Comment by TCOTC** [comment]
v3.1.3 版本应该就好了，请等待下次更新
