### ISSUE TITLE
像浏览器那样的文档内搜索

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12036]
搜索过程：
  1. 搜索文档中包含对应关键词的块，按块里的关键词数量来计数
  2. 把这些块按照在文档中的顺序排序（p.s. 按文档分组搜索的时候好像也是按顺序的？）

点击 `△` 就跳转到前一个块（如果一个块内有多个关键词，就跳转到前一个关键词），点击 `▽` 就跳转到后一个关键词（如果一个块内有多个关键词，就跳转到后一个关键词）（要有高亮）

一个文档对应一个搜索框：

![image](https://github.com/user-attachments/assets/69b44076-cfde-4f6f-84ca-0278afb2b85a)

因为在搜索的过程中也能编辑内容，所以还需要一个刷新按钮用来重新搜索

- 比如搜索关键词，当前的位置是 2/5 ，然后在前面的块增加了关键词，刷新之后位置就是 3/6

**Comment by Muu-yo** [comment]
![image](https://github.com/user-attachments/assets/6b8e6b42-24aa-42ac-a4c2-5b06e5a52b04)
这个插件好似实现了这个操作

**Comment by TCOTC** [comment]
这个插件有 1/3 是我做的，缺陷是只能在已动态加载的块中搜索

**Comment by 88250** [comment]
这个不考虑了，动态加载的情况下实现不了。
