### ISSUE TITLE
用户指南：参考「忽略索引」章节补充「忽略搜索」章节

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12032]
![image](https://github.com/user-attachments/assets/cb3e6e75-9acc-4fb0-98ae-564c6eb81e3c)

**Comment by TCOTC** [comment]
@88250 忽略搜索是跟忽略索引的方法一样吗？这个是不是可以复制过去改一改？

**Comment by 88250** [comment]
忽略搜索用的是 SQL 子句；忽略索引用的是 gitignore 语法（和 syncignore 一样）。

欢迎帮忙 PR 改进文档。
