### ISSUE TITLE
改进块引用 `转换为` 菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12034]
### In what scenarios do you need this feature?

去掉 `链接` 前的图标：

![image](https://github.com/user-attachments/assets/8b63c549-f04a-4320-819d-36ebcc74d0cc)

### Describe the optimal solution

。

**Comment by Vanessa219** [comment]
这个也一起移除了
![QQ_1721830917708](https://github.com/user-attachments/assets/0bc4471a-8cfd-490d-97c0-45332f581557)

**Comment by 88250** [comment]
这个改动不拉进版本了。
