### ISSUE TITLE
改进标签搜索

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12041]
### In what scenarios do you need this feature?

目前用 `#foo#` 作为关键字搜索有以下问题：

- 搜索父标签时无法搜索到子标签
- 搜索到的不一定是标签，还能搜索到被 # 包裹的相同文本

### Describe the optimal solution

- 搜索父标签时能同时搜索到子标签
- 搜索到的只能是标签，排除掉被 # 包裹的相同文本

需要一个更好的方案，比如在数据库里存块的标签

**Comment by 88250** [comment]
没有办法改了，算是设计上的缺陷。
