### ISSUE TITLE
已设置书签的文档需要在书签设置菜单中高亮

### ISSUE THREAD

**Issue by lhx-JIPS** [siyuan-note/siyuan#1204]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

1）当重新更新版本后，上一版本时已经设置的书签会消失，即当选中某个文档【右键】→【书签】后，往往看不到目前已经存在的书签条目，如果要设置该文档的书签，还得重新输入，而且很容易输错，导致产生两个相似的书签条目。如果能够选择就不存在这个问题了。
2）时间长了，就忘记该文档是否已经设置过相应书签，因为没有高亮显示该文档对应的书签条目。要么重新设置，要么到书签页面去查看，不方便。

### 描述最优的解决方案 Describe the optimal solution

建议【右键】→【书签】后增加书签条目内容，并高亮显示该文档已配置的书签。

**Comment by 88250** [comment]
你好，书签等属性丢失的问题应该在目前的版本中已经解决，请帮忙留意继续观察。

当前文档如果设置了书签，的确应该高亮以示区别，感谢建议。

**Comment by guidongyuan** [comment]
v0.6.6的版本，右键删除一直删除不了。
![image](https://user-images.githubusercontent.com/13446866/105453917-03113b00-5cbc-11eb-88a6-b7e0c778c5e9.png)

**Comment by Vanessa219** [comment]
该设置可更为方便的查看
![image](https://user-images.githubusercontent.com/970828/106092797-0304b580-616a-11eb-8b3d-7c5176a1a840.png)


@guidongyuan 请更新版本
