### ISSUE TITLE
file://Y:\11.pdf  之类的链接不应该把pdf文件复制到assets文件夹下

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#12049]
### In what scenarios do you need this feature?

问题描述：
打开一个Word文件，输入“文件”两个字，然后“插入”--“链接”--输入“file://Y:\11.pdf”--确定（如下图）

![](https://s3.bmp.ovh/imgs/2024/07/21/5bd6196f7cfb45cd.png)

然后复制带有链接的“文字”这个内容，在思源笔记中粘贴，此时思源笔记会把“Y:\11.pdf”这个PDF文件复制到assets文件夹下

### Describe the optimal solution

期待结果：
思源笔记可能是考虑到一些网页剪藏，需要把图片之类的资源下载到本地，但是对于“file://本地文件路径”这样的资源不应该被复制到assets文件夹下。思源笔记能否对网络资源和本地资源做个区分，本地资源的话，就**不要**复制到assets中。

**Comment by TCOTC** [comment]
按住 Alt 把文件从外面拖入思源

**Comment by Geo123abc** [comment]
> 按住 Alt 把文件从外面拖入思源

确实可以。

但是我是使用其他方法获得本地文件的一些链接到剪贴板，然后Ctrl+V粘贴到思源笔记。Alt这种方法可能不太适合我。

**Comment by TCOTC** [comment]
复制文件之后右键粘贴为纯文本即可

![image](https://github.com/user-attachments/assets/3f977cb4-e090-4f73-9f15-5a6eb2353b56)

**Comment by Geo123abc** [comment]
> 复制文件之后右键粘贴为纯文本即可
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/350772420-3f977cb4-e090-4f73-9f15-5a6eb2353b56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzA2OTUsIm5iZiI6MTcyMTU3MDM5NSwicGF0aCI6Ii83ODQzNDgyNy8zNTA3NzI0MjAtM2Y5NzdjYjQtZTA5MC00ZjczLTlmMTUtNWE2ZWIyMzUzYjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDEzNTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ODZmYTliYWUxN2RmZWM2NGZkNDMyNDFlNzRkYjEyZWExMGFkODdkZjRlM2Q1ZjBmMjg1ZjBlYmFlMzM5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.basuYhJrtEMAiryMjN1dmhymIpVXJFpfqrwg9VHulJo)

那就完全没有 file:// 链接了啊

**Comment by TCOTC** [comment]
你那里没有吗？我这里是有的

![image](https://github.com/user-attachments/assets/57dea0e5-43f4-46dd-a4ed-59aa28cddcc0)

**Comment by Geo123abc** [comment]
> 你那里没有吗？我这里是有的
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/350774191-57dea0e5-43f4-46dd-a4ed-59aa28cddcc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NzE2NzEsIm5iZiI6MTcyMTU3MTM3MSwicGF0aCI6Ii83ODQzNDgyNy8zNTA3NzQxOTEtNTdkZWEwZTUtNDNmNC00NmRkLWE0ZWQtNTlhYTI4Y2RkY2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDE0MTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNWUxZWIxOTAwYjk2NmRjYThiOGE1OGFhOGVhYmNlMmI3ZGRkY2Q0YTdkMGRiOTkzOGZkZmNhN2U5ZTFiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qYe-ZX9HBxmnq3_Xyx8F7SRdT5p5jD_XJISSA7OtxSE)

好奇怪，我这里就真的成了纯文本，没有链接的，你这咋有链接呦？

**Comment by TCOTC** [comment]
你录屏看看？

https://github.com/user-attachments/assets/f40aba9f-ea63-42b8-8011-96688a016092

**Comment by Geo123abc** [comment]
> 你录屏看看？
> 
>  default.mp4

噢噢噢，你这个是从资源管理器Ctrl+C复制的啊

我是通过其他途径获得的html片段，但是为了叙述方便，我等价成了    类似从Word中  复制带有file:// 链接的文字，然后再在思源笔记中粘贴

你可以尝试一下从Word中复制，然后再在思源笔记中粘贴

**Comment by TCOTC** [comment]
我不太会用 Word ，你能不能提供一个示例文档？

**Comment by Geo123abc** [comment]
我的电脑文件和你的不一样，你试试按照这个截图能自己搞一个文档

![](https://s3.bmp.ovh/imgs/2024/07/21/7aa788f841e929f1.png)

**Comment by TCOTC** [comment]
我可以重现这个问题了，从 Word 里复制这种形式的链接粘贴到思源里就会自动添加为附件。@88250

**Comment by Geo123abc** [comment]
> 我可以重现这个问题了，从 Word 里复制这种形式的链接粘贴到思源里就会自动添加为附件。@88250

辛苦了

**Comment by 88250** [comment]
这个是个特性，复制时会自动拉取本地附件作为资源文件插入。

**Comment by Geo123abc** [comment]
> 这个是个特性，复制时会自动拉取本地附件作为资源文件插入。

D大，
但是如下所示的markdown不会拉取本地附件，markdown和html片段的差异，是否有一种规范不统一的感觉？

```md
[FILE](file://Y:\1.pdf)
```

**Comment by 88250** [comment]
复制粘贴 html 是单独处理的，复制粘贴 md 不处理。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月24日(周三) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] file://Y:\11.pdf  之类的链接不应该把pdf文件复制到assets文件夹下 (Issue #12049)




  
这个是个特性，复制时会自动拉取本地附件作为资源文件插入。
  
D大，
 但是如下所示的markdown不会拉取本地附件，markdown和html片段的差异，是否有一种规范不统一的感觉？
 [FILE](file://Y:\1.pdf)

**Comment by Geo123abc** [comment]
> 复制粘贴 html 是单独处理的，复制粘贴 md 不处理。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月24日(周三) 晚上8:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] file://Y:\11.pdf 之类的链接不应该把pdf文件复制到assets文件夹下 (Issue #12049) 这个是个特性，复制时会自动拉取本地附件作为资源文件插入。 D大， 但是如下所示的markdown不会拉取本地附件，markdown和html片段的差异，是否有一种规范不统一的感觉？ [FILE](file://Y:\1.pdf) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好吧，感觉怪怪的，有点规范不统一，暂时先这样吧

**Comment by 88250** [comment]
md 导入时会处理



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月24日(周三) 晚上8:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] file://Y:\11.pdf  之类的链接不应该把pdf文件复制到assets文件夹下 (Issue #12049)




  
复制粘贴 html 是单独处理的，复制粘贴 md 不处理。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月24日(周三) 晚上8:20 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [siyuan-note/siyuan] file://Y:\11.pdf 之类的链接不应该把pdf文件复制到assets文件夹下 (Issue #12049) 这个是个特性，复制时会自动拉取本地附件作为资源文件插入。 D大， 但是如下所示的markdown不会拉取本地附件，markdown和html片段的差异，是否有一种规范不统一的感觉？ FILE — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
好吧，感觉怪怪的，有点规范不统一，暂时先这样吧
