### ISSUE TITLE
文档自动命名

### ISSUE THREAD

**Issue by Hanochhu** [siyuan-note/siyuan#12048]
### In what scenarios do you need this feature?

当文档没有写标题的时候，有时候暂时没想好名字，显示‘未命名’的话下次就想不起来了

### Describe the optimal solution

可以选文档的前n 个字作为名字

**Comment by TCOTC** [comment]
我提议：如果文档没填写标题，则在文档树上显示首个非空段落块中的文本内容（如果没有非空段落块则显示「未命名」）。并且仅仅是显示，不作为文档标题参与索引。

**Comment by Hanochhu** [comment]
> 我提议：如果文档没填写标题，则在文档树上显示首个非空段落块中的文本内容（如果没有非空段落块则显示「未命名」）。并且仅仅是显示，不作为文档标题参与索引。

合理，不过显示前十几个字也差不多吧，毕竟侧边栏就那么大。 都行，只要有类似的功能就行

**Comment by 88250** [comment]
抱歉这个不考虑了，使用 `未命名` 占位好一些。
