### ISSUE TITLE
improvement on default focus position when opening notes.

### ISSUE THREAD

**Issue by 7eopard** [siyuan-note/siyuan#12047]
### In what scenarios do you need this feature?

To perform operation on notes that is just opened. Often, this operation is to be performed only after the note's content is checked.

### Describe the optimal solution

It is notes that more operations are performed on, instead of their first block, esp. when these notes have just been clicked, selected, and opened. Default focus or cursor position, in this case, is supposed to be set at the object note if there's no character input detected; the default object of any shortcut operation should be that note as well. That would be more intuitive.

### Describe the candidate solution

introduction of different shortcut modifier for block and note respectively.

making note's icon checkbox, click to check, righ-click to edit icon.

**Comment by TCOTC** [comment]
你的意思是打开文档的时候焦点不在文档内吗？

**Comment by 7eopard** [comment]
> 你的意思是打开文档的时候焦点不在文档内吗？

我希望在没有输入时或点击任何一个块时，焦点是文档，而不是文档内的块。

**Comment by TCOTC** [comment]
这个焦点是会记录的，上次关闭文档的时候焦点在哪里，下次打开的时候就在哪里。

**Comment by 7eopard** [comment]
> 这个焦点是会记录的，上次关闭文档的时候焦点在哪里，下次打开的时候就在哪里。

没有办法让焦点在文档树上吗

**Comment by TCOTC** [comment]
> 让焦点在文档树上

按住 Ctrl，鼠标左键点击文档

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
