### ISSUE TITLE
The sorting of fields in the database attribute panel is unstable

### ISSUE THREAD

**Issue by QMike0** [siyuan-note/siyuan#12043]
数据库属性面板存在的一些问题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 重复退出/进入数据库属性面板，会发现各数据库属性条目会随机排序，无法按照数据库中的排序固定好
![recording](https://github.com/user-attachments/assets/7b61c988-e828-461d-ae55-a661e5102b91)
2. 数据库属性面板的资源列中，既无法点击已添加好的“链接”，也无法添加更多资源
![recording](https://github.com/user-attachments/assets/ea3630d7-ca5a-47a6-96a5-da5e33eada74)
3. 数据库属性面板的链接列中，修改链接后无法立刻切换，点击链接后仍会跳转到修改前的旧链接。必须要关闭属性面板重新打开后才能跳转新链接。
![recording](https://github.com/user-attachments/assets/e022eb0c-c9c2-41b0-8f70-3947e3546b5b)

### Expected result

对上述各条的Expected result如下：
1. 数据库属性面板的各条目固定好排序不要乱动；另外应按照数据库表格视图手动调整的条目顺序自动改变排序，例如手动拖动db中各列顺序从左向右为A, C, E, B, D，那么在链接该数据库的文档/内容块的数据库属性面板中，属性条目从上向下的顺序也应变为A, C, E, B, D，并且是只要db表格各列顺序有变化，相应文档/内容块的数据库属性面板的各条目排序也应随之变化，而非根据初始创建db时各列的顺序就不变了
2. 数据库属性面板的资源列也应像其他类型列一样，支持添加，也支持资源（例如链接）的点击和跳转
3. 数据库属性面板的链接列中修改链接后，点击应能跳转到新链接，而非修改前的旧链接。这一点其实在数据库表格视图中可以实现。

总之，应保持数据库属性面板与数据库表格视图交互逻辑的统一，为后续[这个issue](https://github.com/siyuan-note/siyuan/issues/11371)的实现做准备
PS：催一波编辑器顶部添加数据库属性面板的进程

### Version environment

```markdown
- Version: 3.1.1
- Operating System: Windows
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16323334/siyuan.log)

**Comment by TCOTC** [comment]
> 只要db表格各列顺序有变化，相应文档/内容块的数据库属性面板的各条目排序也应随之变化，而非根据初始创建db时各列的顺序就不变了

这个是有问题的，所以 #11428 将视图和属性面板的排序分离了

> 重复退出/进入数据库属性面板，会发现各数据库属性条目会随机排序，无法按照数据库中的排序固定好

新建的数据库可以复现这个问题。@88250

> 数据库属性面板的链接列中，修改链接后无法立刻切换，点击链接后仍会跳转到修改前的旧链接。必须要关闭属性面板重新打开后才能跳转新链接。

确实有这个问题。@88250

> 修改链接后，点击应能跳转到新链接，而非修改前的旧链接。这一点其实在数据库表格视图中可以实现。

@QMike0 这是指什么？表格视图修改链接是及时生效的

> 数据库属性面板的资源列也应像其他类型列一样，支持添加，也支持资源（例如链接）的点击和跳转

拆分到 #12044

**Comment by QMike0** [comment]
> @QMike0 这是指什么？表格视图修改链接是及时生效的
就是指“数据库属性面板的链接列中，修改链接后无法立刻切换，点击链接后仍会跳转到修改前的旧链接。必须要关闭属性面板重新打开后才能跳转新链接”，表格视图不存在问题

> 这个是有问题的，所以 https://github.com/siyuan-note/siyuan/issues/11428 将视图和属性面板的排序分离了
这一点我的想法是，排序应该支持表格视图-->属性面板单向的变化。也就是表格视图的各列顺序变化要能导致属性面板各条目的排序跟着改变，但属性面板中不应支持手动改变排序，这样就能避免那个issue的问题。
手动改变表格视图各列顺序的目的就是为了更好地查看属性信息，排序的改变应该是统一的，否则需要在属性面板中一个一个单独调各条目顺序太难受了

**Comment by TCOTC** [comment]
数据库是有多个视图的，所以属性面板单独排序

**Comment by TCOTC** [comment]
不过如果要让属性视图跟某个表格视图的排序同步，我觉得也不是不能做。给个下拉菜单切换就行了

**Comment by QMike0** [comment]
> 不过如果要让属性视图跟某个表格视图的排序同步，我觉得也不是不能做。给个下拉菜单切换就行了 #12045

1，好主意

> 新建的数据库可以复现这个问题。@88250

我又测试了一下，不用新建数据库，只要向已有的数据库中添加新文档，然后打开这个新文档进入它的属性面板，就能复现这个问题。如果只是打开该数据库之前添加的文档，属性面板中的各条目排序是固定住的，必须要先打开这个新添加的文档才行

**Comment by 88250** [comment]
* 第一点本贴跟进
* 第二点 https://github.com/siyuan-note/siyuan/issues/12289
* 第三点 https://github.com/siyuan-note/siyuan/issues/12386
