### ISSUE TITLE
改进属性面板的数据库资源字段

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12044]
#12043 第二点

- [x] 属性面板中的链接和资源文件无法左键点击打开（链接→网页 图片→查看 文件→打开）。
- [x] 属性面板中的链接和资源文件无法右键点击编辑。参考：#11060
- [x] 无法在属性面板中添加链接和资源文件。参考：#11463 #11469 #12308 #12422
- [x] 链接显示与表格视图不一致。参考：#11468 #11465
- [x] https://github.com/siyuan-note/siyuan/issues/12289

   ![image](https://github.com/user-attachments/assets/37665b25-356c-4125-9255-1cae6a78f1b1)

**Comment by Vanessa219** [comment]
1. 链接需点击后面的图标，否则和输入框事件重叠
3. 上传文件我这里是可以的

 https://github.com/siyuan-note/siyuan/issues/12308 也合并到这个 issue 下吧
