### ISSUE TITLE
数据库增加属性关联

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12040]
### In what scenarios do you need this feature?

希望在打开笔记的时候可以同步数据到对应页面
![image](https://github.com/user-attachments/assets/261312a2-7e69-42ca-97da-b0368affe47e)

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/248dda4e-d4d2-463a-8504-d1999a044a36)
希望是这种类似Notion一样可以根据属性相互编辑和查看

**Comment by TCOTC** [comment]
请关注 #11371

目前可以使用文档(块)的属性面板：

![image](https://github.com/user-attachments/assets/93614e0c-08b7-49d4-965d-d713b5bf704a)

![image](https://github.com/user-attachments/assets/aced0f1b-9829-4728-afe0-dd84f1efbb12)
