### ISSUE TITLE
属性面板数据库支持切换为某个视图的排序

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12045]
### In what scenarios do you need this feature?

增加一个下拉菜单：

- 默认排序（不支持隐藏字段）
- 其他的某个**表格视图**的排序（在视图中隐藏的字段就不显示）
  - 在属性面板的更改同步到视图
  - 视图被删除后，恢复为显示默认排序

![image](https://github.com/user-attachments/assets/d6111d65-38a9-41a4-a572-5810c80d36d7)

**Comment by 88250** [comment]
这个不考虑了，属性面板和视图拥有独立的字段排序和字段隐藏 https://github.com/siyuan-note/siyuan/issues/12341

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/9e5162a1-acf1-4be4-989a-740131ca8252)

**Comment by TCOTC** [comment]
有的用户就是想让属性面板里的排序跟表格视图里的排序保持同步

**Comment by 88250** [comment]
不考虑了，需求较为小众并且和现有设计不符。
