### ISSUE TITLE
保存搜索条件时回车操作与预期不符

### ISSUE THREAD

**Issue by 7eopard** [siyuan-note/siyuan#12046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

保存查询条件时如果名字与旧条件有重复，会提示是否覆盖。此时回车仍然触发“保存查询条件”，而不是“确认”。

### Expected result

回车时触发“确认”。

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

N/A

**Comment by TCOTC** [comment]
确实有这个问题

[视频.webm](https://github.com/user-attachments/assets/e83bf3f0-a3e1-493a-9ba6-2906b1c7fec4)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
