### ISSUE TITLE
超级块中的嵌入块无法显示面包屑

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12059]
https://ld246.com/article/1721213038102

[视频.webm](https://github.com/user-attachments/assets/63843090-520a-4bf9-b59c-4d4e02310915)

**Comment by 88250** [comment]
这个是设计如此：

![image](https://github.com/user-attachments/assets/36c9ad59-0ecf-46e3-8747-2f7578b1f4ad)

**Comment by TCOTC** [comment]
这个是为啥会这样设计？

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/6258

**Comment by TCOTC** [comment]
我看起来感觉像是因为解决不了超级块中的面包屑带来的问题才隐藏了面包屑，而不是设计成这样

**Comment by 88250** [comment]
对，应该是的，这个设计保持不变了。

**Comment by TCOTC** [comment]
话说我直接改 HTML 试了一下，感觉好像没啥问题？

[视频.webm](https://github.com/user-attachments/assets/24cf48f9-21e4-4eb9-9c8f-3ba62e9e236e)

**Comment by TCOTC** [comment]
要不试试改回来有没有问题？
