### ISSUE TITLE
每次打开思源都会出现更新提示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12056]
![image](https://github.com/user-attachments/assets/d01f7ce0-7d0e-4ffa-bd55-b245a5f02c91)

是更新 APP 之后不正常退出就会这样吗？

最好还是只弹一次

**Comment by 88250** [comment]
是的，需要点 x 关闭，然后右侧栏正常退出应用。

**Comment by TCOTC** [comment]
改进重建索引提示之后基本可以直接在后台划掉思源了，这个能不能再改进一下，比如主动关闭弹窗后这个版本就不再弹出

**Comment by 88250** [comment]
配置文件和索引不一样



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年7月24日(周三) 中午12:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 每次打开思源都会出现更新提示 (Issue #12056)




 
改进重建索引提示之后基本可以直接在后台划掉思源了，这个能不能再改进一下，比如主动关闭弹窗后这个版本就不再弹出
