### ISSUE TITLE
从网页复制的下划线字符会带不可见的转义符

### ISSUE THREAD

**Issue by d13-proto** [siyuan-note/siyuan#12052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 复制网页中的下划线字符，例如这里的“__”
2. 粘贴到笔记里，显示为：`__`
3. 复制笔记里的 `__`
4. 粘贴到其他地方，显示为：`\_\_`

### Expected result

期望从网页复制的下划线字符，复制到其他地方时不带转义符

### Version environment

```markdown
- Version: v3.1.1
- Operating System: Windows
- Browser (if used): Firefox
```

### Log file

[siyuan-2024-07-22.log](https://github.com/user-attachments/files/16325800/siyuan-2024-07-22.log)

### More information

从其他地方复制的下划线字符，不会出现此问题

**Comment by TCOTC** [comment]
#11206

**Comment by 88250** [comment]
这是正常的，因为 `_` 是 Markdown 标记符，如果要显示的话需要加转义 `\_`。
