### ISSUE TITLE
在Ubuntu2020.04上通过docker运行siyuan，启动失败。

### ISSUE THREAD

**Issue by marshalby2** [siyuan-note/siyuan#1205]
在Ubuntu2020.04上通过docker运行siyuan，启动失败。

1. 启动指令**docker run -v /siyuan/conf:/siyuan/conf -v /siyuan/data:/siyuan/data -p 6806:6806 b3log/siyuan --resident=true --conf=/siyuan/conf**
2. conf.json文件放在/siyuan/conf路径下，conf.json内容如下：
```
{
  "url": "http://127.0.0.1:6806/siyuan/my-note",
  "name": "mu-note",
  "auth": "",
  "user": "",
  "password": "",
  "path": "/siyuan/data/my-note"
}
```
/siyuan/data/my-note这个文件夹是存在的

**Comment by 88250** [comment]
你好，有报错日志出现么？

**Comment by marshalby2** [comment]
我用docker logs指令没有看到输出

**Comment by marshalby2** [comment]
我又重新试了几次，在执行`docker run -v /siyuan/conf:/siyuan/conf -v /siyuan/data:/siyuan/data -p 6806:6806 b3log/siyuan --resident=true --conf=/siyuan/conf`这条指令的时候，就报错了，容器根本没有启动起来

**Comment by 88250** [comment]
请贴一下报错信息，谢谢。
