### ISSUE TITLE
MacOS 思源本体没有窗口置顶功能

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#12053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Mac上，本体没有窗口置顶功能。
<img width="659" alt="image" src="https://github.com/user-attachments/assets/b86f8c3f-1a34-48db-b8ec-9583f1282492">

<img width="469" alt="image" src="https://github.com/user-attachments/assets/06ab9cea-9fb5-452e-a50c-0f9c50e2fb4d">

### Expected result

在图中位置增加窗口置顶的选项，以及切换窗口置顶的快捷键

### Version environment

```markdown
- Version: 3.1.1
- Operating System: MacOS
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
用其他工具软件顶顶（虽然我不清楚用哪款 :joy:

**Comment by Wetoria** [comment]
这个功能 Electron 是提供的，windows 的思源里，已经有这个置顶的选项，只是 Mac 下没有。

技术方面，就是将思源本体窗口，或者无脑一点，将所有electron窗口都 setAlwaysOnTop(true) 基本就行。

不过交互上要搞的好的话，还是有点细节要处理。

有一个可以参考的，Arc 浏览器是在每一个窗口的 Window 菜单里，增加了 Stay On Top 的选项：

<img width="630" alt="Image" src="https://github.com/user-attachments/assets/762b8731-dc8e-4e2b-a381-34eba4feab8c" />

仅作技术细节分享，如果以后其他人有同样的需求了，可以作为参考。
