### ISSUE TITLE
希望添加 创建数据库表字段索引 接口

### ISSUE THREAD

**Issue by Misuzu2027** [siyuan-note/siyuan#12054]
### In what scenarios do you need this feature?

我的 blocks 表行数有24万条。我在用下面 sql 的时候，非常简单的条件，执行速度却是 200 多毫秒。
![image](https://github.com/user-attachments/assets/941bf689-84fe-462d-a0a1-2d6a9d8cc4e8)
排查后发现是没有为 parent_id 字段创建索引，我创建索引后再查询，速度降到了 2 毫秒 
![image](https://github.com/user-attachments/assets/a01321bf-f1c3-4965-ab20-f81e68dd661a)
，这足有100被的差距。

我现在正在开发 反链面板插件，其中需要使用 parent_id 字段进行递归确定块的层级关系，如果没办法为安装此插件的用户进行创建索引优化速度，体验会很差。并且我认为后续的插件开发作者也可能遇到此类问题，所以我希望能够提供一个创建索引的接口，供插件作者调用。

### Describe the optimal solution

接口方面，如果为了减少可能存在的麻烦和风险，可以限制该接口只允许传入两个参数 表名 和 字段名，由后端生成索引名称后创建索引，避免不同插件用不同的索引名称对同一个字段重复创建。

### Describe the candidate solution

如果不想开这个接口，那我希望可以把 parent_id 这个字段默认创建索引，只是id，不会影响太多空间。

**Comment by 88250** [comment]
我们默认加入索引吧，感谢反馈。

**Comment by 88250** [comment]
这个改动就不拉进版本了。
