### ISSUE TITLE
`Convert to blockquote` supports config keymaps

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#12069]
能否为“转化为引述”功能添加快捷键

### In what scenarios do you need this feature?

请问能否为“转化为引述”功能添加快捷键；
或选中几个块后，使用 “ Shift + > ” 键，能够将选中的几个块都变成引述

### Describe the optimal solution

1

**Comment by TCOTC** [comment]
为 `引述` 添加快捷键

**Comment by Vanessa219** [comment]
`Shift + > ` 为输入键，做为快捷键的话，用户会无法输入 `》`。添加一个为空的快捷键，让用户自己定义。
