### ISSUE TITLE
部分pdf矩形标注丢失图片

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#12064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在不同的工作空间对该pdf进行矩形标注（其他pdf没有该问题），都会丢失图片。
![image](https://github.com/user-attachments/assets/b9c0080c-92b5-4c4f-8bf9-f5324e3ead32)

pdf下载地址：https://f.ws28.cn/f/enuskwr1sa5 复制链接到浏览器打开

### Expected result

希望可以修复

### Version environment

```markdown
- Version: 最新版
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by TCOTC** [comment]
请你上传一下图片不能正常显示的文档

我这看起来很正常：

![image](https://github.com/user-attachments/assets/8c54df7e-e54a-4a6a-8c7f-fc16fcc72612)

**Comment by chenshinshi** [comment]
> 请你上传一下图片不能正常显示的文档
> 
> 我这看起来很正常：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/351183522-8c54df7e-e54a-4a6a-8c7f-fc16fcc72612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDg3MTIsIm5iZiI6MTcyMTcwODQxMiwicGF0aCI6Ii83ODQzNDgyNy8zNTExODM1MjItOGM1NGRmN2UtZTU0YS00YTZhLThjN2YtZmMxNmZjYzcyNjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA0MjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMDFlN2I4NjcxOGJkYzQ3MDY5Nzg0ZmQ5ZGI5YzgwMmE1N2M4ZTVhOTQ0MmE1ZTY0ODhhYTM4OTBhMTQ0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O8LWRl1DdiLm4HknC72MdwLf7o5Yj3IL3NtsMKnUO_I)

amazing，好像是我浏览器的问题
