### ISSUE TITLE
<div>元素无法被正常粘贴

### ISSUE THREAD

**Issue by ThemanRonin** [siyuan-note/siyuan#12067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

# div元素如果想要粘贴的话，只能使用**代码块**进行粘贴，直接粘贴和纯文本粘贴都无法正常显示

例如该代码文本：
```HTML
<div id="barMode" class="toolbar__item ariaLabel" aria-label="外观模式">
    <svg><use xlink:href="#iconLight"></use></svg>
</div>
```
## 当复制后以**纯文本**的方式粘贴会自动转换成HTML代码块，动图演示：

![recording](https://github.com/user-attachments/assets/7b68a0ae-7db7-4604-a520-1022f030effa)

## 其他的元素简单测试了一下，是可以正常粘贴成**纯文本**的，动图演示：

![recording](https://github.com/user-attachments/assets/4a817645-253b-49d8-966e-5a21b57ae311)

### Expected result

修复该问题

### Version environment

```markdown
- Version: 3.1.1.
- Operating System: Windows 10 Pro
- Browser (if used):
```

### Log file

I believe this incident does not require reporting in the log file.

**Comment by 88250** [comment]
HTML 块是使用 `<div>` 包裹的，所以粘贴文本会解析为 HTML 块。

建议用代码块包裹。
