### ISSUE TITLE
微软拼音输入法在某种情况下 `Delete` 失效，并且造成异常的块（需要通过刷新文档解决）

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12065]
按 aaa ，然后退格删除，再按 Delete：（前面是搜狗，后面是微软）

[视频.webm](https://github.com/user-attachments/assets/9aa4d047-7113-4446-8de1-0ec2fcffe3a3)

### Other information

貌似 QQ 拼音输入法也有这个问题

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/4826

**Comment by 88250** [comment]
我这里使用微软拼音已经无法重现该问题，麻烦再测试看看。

**Comment by 88250** [comment]
好的。
