### ISSUE TITLE
快速复制标题及标题下内容

### ISSUE THREAD

**Issue by Jamie-Wan** [siyuan-note/siyuan#1206]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
拆书、拆大文档的时候，可以通过收缩某一级标题，将该标题复制或剪切后粘贴时会将该级标题及标题下的内容一起粘贴

### 描述最优的解决方案 Describe the optimal solution
Obsidian
![image](https://user-images.githubusercontent.com/65280479/105275108-860d9500-5bd9-11eb-9682-7d4203156ad1.png)
当连省略号一起选中时即将标题将该级标题下内容一起选中，否则只是选中标题

**Comment by Vanessa219** [comment]
拆分可以拖拽菜单到文件树上

![image](https://user-images.githubusercontent.com/970828/106119304-feeb8e80-618f-11eb-9270-cdcf3dfadf73.png)

聚合可以通过拖拽文件到编辑器中

![image](https://user-images.githubusercontent.com/970828/106119424-29d5e280-6190-11eb-9eb9-a97cc82c2eff.png)
