### ISSUE TITLE
希望图片插入到数据库时可以显示的稍微大一点，

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12062]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/8a839e1d-f90a-4861-b742-34e846181ad1)
如图所示
另外一个比较重要的需求是数据库中的备注信息不支持双链和文字混用，文字就支持文字有时候需要双链到对应的页面当做补充

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/bf08a9d0-a23c-473c-84b8-34257b76523e)
就像这样的感觉

**Comment by TCOTC** [comment]
> 希望图片插入到数据库时可以显示的稍微大一点

用 CSS 片段应该能实现

> 另外一个比较重要的需求是数据库中的备注信息不支持双链和文字混用，文字就支持文字有时候需要双链到对应的页面当做补充

听起来像是这个需求：#11553

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
