### ISSUE TITLE
Improve list item editing

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#12066]
在无序列表中插入公式删除后可能引发错误

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下列表，
操作如下，在公式块前一个块的最后按delete（光标移到and后面），然后就会出现问题，百分之百复现

* $RR$

  * is known as the rejection ratio, used to dampen or delay the element removal process,<br />被称为拒绝比例，用于减弱或延迟元素移除过程。<br />$0\leq RR\leq1$ ,
    and
  * $$
    \begin{equation} RR=r_{1}+r_{2}\times SS+r_{ON}\times ON\end{equation}
    $$
* $r_1,r_2$

  * are coefficients determined from experience with ESO method.

### Expected result

更加顺滑的操作

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

[log.log](https://github.com/user-attachments/files/16346800/log.log)

**Comment by TCOTC** [comment]
我不太理解你所指的问题是什么？


https://github.com/user-attachments/assets/ec14e1ed-4d83-4aad-9f7b-0fb01ac2c419

**Comment by TCOTC** [comment]
麻烦导出这个文档为 .sy.zip 上传一下

**Comment by lisontowind** [comment]
[1.zip](https://github.com/user-attachments/files/16351370/1.zip)

**Comment by lisontowind** [comment]
[1.sy.zip](https://github.com/user-attachments/files/16351391/1.sy.zip)

**Comment by TCOTC** [comment]
@88250 看看，这个文档能复现问题：[#12066.sy.zip](https://github.com/user-attachments/files/16351610/12066.sy.zip)

**Comment by 88250** [comment]
@Vanessa219 我测试了下，似乎是因为这些 `br` 影响的：

![image](https://github.com/user-attachments/assets/e2b4dfe7-0ce6-47be-8bc5-a25d39c2a277)
