### ISSUE TITLE
改进文件历史中的数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12079]
两个问题：

1. 无法使用搜索
2. 无法切换视图

[视频.webm](https://github.com/user-attachments/assets/dc044f33-9531-4b4a-a895-0bfbfca4c00e)

**Comment by 88250** [comment]
这个界面只能看个大概，功能不可能带全的。

**Comment by TCOTC** [comment]
有多个视图的情况下就只能看到一个视图了，感觉不太好
