### ISSUE TITLE
3.1.1版本的设置中，偶尔会出现“关于”消失的情况

### ISSUE THREAD

**Issue by edward-kyle** [siyuan-note/siyuan#12071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![Clip_2024-07-24_15-50-08](https://github.com/user-attachments/assets/8c2a9318-c754-4e2f-9faf-0d65a198084b)
偶尔会出现“关于”选项按钮消失的情况

### Expected result

不再出现这种情况

### Version environment

```markdown
- Version: 3.1.1
- Operating System: win11
- Browser (if used):
```

### Log file

暂无

**Comment by TCOTC** [comment]
你的是不是这个问题：#12013

**Comment by edward-kyle** [comment]
> 你的是不是这个问题：#12013

既然会在下个版本中修复，那我就把这个issue关闭了。
