### ISSUE TITLE
编辑数据库后没有生成文件历史

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12078]
- 编辑文档中的数据库后生成文件历史
- 包含数据库镜像的其他文档不需要同时生成文件历史

---

- 有文件历史就能回滚一些无法撤回的操作 https://github.com/siyuan-note/siyuan/issues/10907#issuecomment-2133003782

**Comment by 88250** [comment]
> 包含数据库镜像的其他文档也需要同时生成文件历史？

不用吧。

**Comment by 88250** [comment]
我这里测试，编辑单元格内容可以生成文档对应的文件历史的。

**Comment by TCOTC** [comment]
我这里现在试也是会生成文件历史。估计是跟 #12081 相关的问题了
