### ISSUE TITLE
在标题块前输入 `>` 或 `》` 之后应该给标题块套一层引述块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12074]
### In what scenarios do you need this feature?

输入 `>` 不能转换，输入 `》` 会变成 `>` ：

[视频.webm](https://github.com/user-attachments/assets/fea22c9d-920e-4bf9-819a-33e5181570cd)

### Describe the optimal solution

应该是这样：

![image](https://github.com/user-attachments/assets/982031bd-e705-4629-94d1-034c5001034c)

**Comment by 88250** [comment]
标题块内是行级元素，使用 md 表示如下：

```
# > foo
```

所以不会转换为引述块+标题块。

**Comment by TCOTC** [comment]
这样的话输入不了 `》` 是个问题

**Comment by 88250** [comment]
@Vanessa219
