### ISSUE TITLE
自动更新功能不起作用

### ISSUE THREAD

**Issue by nightlye** [siyuan-note/siyuan#1207]
尝试用0.6.1自动更新到最新版本，点击检查更新后提示有更新的版本并且安装包已经下好，但重启并没有更新。

**Comment by 88250** [comment]
请上传一下 siyuan.log 以及 update.log ，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果有进一步反馈请随时跟帖，非常感谢。

**Comment by nightlye** [comment]
抱歉，不是经常上GitHub没能及时看到回复。
现在已升级到0.6.5版本，但仍然无法自动更新。
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5853610/siyuan.log)
[siyuan-update.log](https://github.com/siyuan-note/siyuan/files/5853611/siyuan-update.log)

**Comment by 88250** [comment]
@nightlye 你好，从日志上看是因为文件权限问题，估计只能通过手动安装了，感谢帮忙反馈。
