### ISSUE TITLE
单个嵌入块复制为嵌入块后无法显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12076]
正常的嵌入块里是可以嵌套嵌入块的，但单个嵌入块复制为嵌入块后无法显示：

[视频.webm](https://github.com/user-attachments/assets/767e42f2-d3c1-4971-bed8-087818d42638)

导出预览是正常显示的：

![image](https://github.com/user-attachments/assets/b496042c-5811-40c8-bbce-465dbc001fb4)

**Comment by 88250** [comment]
嵌入块不支持再次嵌入自身，目前导出/预览模式下也不会在计入了。
