### ISSUE TITLE
有鉴权码时，siyuan未锁屏状态下，把电脑锁屏，之后解锁电脑，siyuan显示“访问鉴权失败”

### ISSUE THREAD

**Issue by edward-kyle** [siyuan-note/siyuan#12070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

siyuan未锁屏状态下，把电脑锁屏，之后解锁电脑，siyuan显示“访问鉴权失败”。
之后无法刷新，无法退出。只能通过任务管理器强制关闭siyuan。

### Expected result

希望可以解决这个问题。

### Screenshot or screen recording presentation

![newnew](https://github.com/user-attachments/assets/c8b97ad2-63f2-4fc5-b278-1fa879f03aee)

### Version environment

```markdown
- Version: 3.1.1
- Operating System: Win 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16358784/siyuan.log)

**Comment by edward-kyle** [comment]
补充一下，有在关于中开启这个功能：
![Clip_2024-07-24_15-46-11](https://github.com/user-attachments/assets/5d685379-4f00-4b14-96e0-6cdb110bbc65)

**Comment by edward-kyle** [comment]
> 补充一下，有在关于中开启这个功能：
> ![Clip_2024-07-24_15-46-11](https://private-user-images.githubusercontent.com/78415230/351623828-5d685379-4f00-4b14-96e0-6cdb110bbc65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDg0NDIsIm5iZiI6MTcyMTgwODE0MiwicGF0aCI6Ii83ODQxNTIzMC8zNTE2MjM4MjgtNWQ2ODUzNzktNGYwMC00YjE0LTk2ZTAtNmNkYjExMGJiYzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA4MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNTE3Y2I4NjE4NjQ4YTQ1OTYxOWVhZWUyYTEwM2ZhMmFlMDQ1Zjk0NTg1NDc0MzVhYWJlOGEzOTdiOTg3YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JEtoq4gVj-wxPwv-nNE8Rz-xPw6n-yWNWuWOuOTAwsg)

开启这个功能后，直接电脑锁屏，解锁电脑，打开siyuan应该看到的是：
![Clip_2024-07-24_16-03-13](https://github.com/user-attachments/assets/65d17ae0-303f-4ee5-acc1-da5d3130ad42)

但是我直接进入到了siyuan里，但是右上角会显示“访问鉴权失败” 。并且无法编辑，无法打开任何按钮，无法点击右上角的x退出，无法通过右下角状态栏右键退出。

**Comment by edward-kyle** [comment]
关联：https://ld246.com/article/1721870965530

**Comment by edward-kyle** [comment]
最新情况：使用集市里的离开即锁插件也会导致这种情况的出现。推测是锁屏功能的api问题。
![Clip_2024-07-30_22-41-39](https://github.com/user-attachments/assets/88285449-7263-4cf8-87b4-476e55b7f0fb)

**Comment by TCOTC** [comment]
关联：https://ld246.com/article/1722160599284

**Comment by 88250** [comment]
我这里在 v3.1.3 上无法重现该问题，请测试一下看看。

**Comment by edward-kyle** [comment]
您好，我在v3.1.3版本上也无法复现该问题了。应该是已经被修复了吧。

**Comment by 88250** [comment]
好的，那就先关闭了。

**Comment by edward-kyle** [comment]
很抱歉，今天下午又能复现了，我也不知道这是为什么？
![Clip_2024-08-09_15-55-51](https://github.com/user-attachments/assets/4909499d-09e3-41c5-8d8e-de437908e98f)

**Comment by 88250** [comment]
排除插件影响了吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月9日(周五) 下午3:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 有鉴权码时，siyuan未锁屏状态下，把电脑锁屏，之后解锁电脑，siyuan显示“访问鉴权失败” (Issue #12070)




 
很抱歉，今天下午又能复现了，我也不知道这是为什么？
 Clip_2024-08-09_15-55-51.png (view on web)

**Comment by edward-kyle** [comment]
尝试了一下关闭所有插件，无法复现。
大概率是被某个插件影响到了

**Comment by 88250** [comment]
嗯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月9日(周五) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 有鉴权码时，siyuan未锁屏状态下，把电脑锁屏，之后解锁电脑，siyuan显示“访问鉴权失败” (Issue #12070)




 
尝试了一下关闭所有插件，无法复现。
 大概率是被某个插件影响到了

**Comment by edward-kyle** [comment]
试了很久，也不知道是哪个插件导致这个bug。最后只能关闭“跟随系统锁屏”功能。

**Comment by myg321** [comment]
> 试了很久，也不知道是哪个插件导致这个bug。最后只能关闭“跟随系统锁屏”功能。

我把所有插件关闭，每次锁屏再打开后也还是有这个提示.... 
![image](https://github.com/user-attachments/assets/bd05d781-aa4f-43d2-94f3-2bccc2867561)

**Comment by myg321** [comment]
> 排除插件影响了吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月9日(周五) 下午3:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 有鉴权码时，siyuan未锁屏状态下，把电脑锁屏，之后解锁电脑，siyuan显示“访问鉴权失败” (Issue #12070) 很抱歉，今天下午又能复现了，我也不知道这是为什么？ Clip_2024-08-09_15-55-51.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

把所有插件关闭，锁屏再打开后依然有这个提示，我是最近这几天出现的这个问题：
![image](https://github.com/user-attachments/assets/3e9927a5-2591-4127-8f1c-f748c20abe81)

**Comment by myg321** [comment]
> 排除插件影响了吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月9日(周五) 下午3:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 有鉴权码时，siyuan未锁屏状态下，把电脑锁屏，之后解锁电脑，siyuan显示“访问鉴权失败” (Issue #12070) 很抱歉，今天下午又能复现了，我也不知道这是为什么？ Clip_2024-08-09_15-55-51.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

已知问题：
1. 关闭“访问授权码跟随系统锁屏”时：
电脑锁屏后再打开无提示，笔记裸露在屏幕上。思源笔记界面开着的时候，点击左上角设置→锁屏（或者Alt+N）就会出现“访问鉴权失败，请刷新或者重新打开”提示且只能从资源管理器中关闭。
2. 开启“访问授权码跟随系统锁屏”时：
电脑锁屏后再打开就会出现“访问鉴权失败，请刷新或者重新打开”提示且只能从资源管理器中关闭。思源笔记界面开着的时候，击左上角设置→锁屏（或者Alt+N）弹出输入密码界面：
![image](https://github.com/user-attachments/assets/ee62b811-a6c0-4478-8112-1d0d4a870bf3)

**Comment by TCOTC** [comment]
用户反馈：

- https://ld246.com/article/1726708106757

   ![image](https://github.com/user-attachments/assets/ac393371-9b48-424c-81e9-b5b8936fb5bf)
