### ISSUE TITLE
改进数据库视图右键菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12082]
> #10889 的另一种方案

我还是觉得两个功能相同的选项很奇怪：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/c46f0db7-fb2f-4f96-822a-61c7f190edb5)

如果改成像 FlowUs 这种点击就能编辑视图名称的方式就会更方便：

![image](https://github.com/user-attachments/assets/e55df686-8dc2-4ae3-bb71-8f1db67f78b8)

**Comment by 88250** [comment]
暂时不考虑改变了。

**Comment by TCOTC** [comment]
刚刚发现 Wolai 也是，还是这样方便：

![image](https://github.com/user-attachments/assets/b4336430-d9c2-4ce6-b44b-3c076d11c618)
