### ISSUE TITLE
s3同步：我猜测这可能是个BUG

### ISSUE THREAD

**Issue by go1em** [siyuan-note/siyuan#12085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

查看日志，发现有如下报错
```
2024/07/24 22:11:27 net.go:122: check url [https://***********:8443/] is online failed: Get "https://***********:8443/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
为了清楚影响，看了一下相关的源码（不是很精通），发现：
if !exit && !isProviderOnline(byHand) { // 这个操作比较耗时，所以要先推送 syncing 事件后再判断网络，这样才能给用户更即时的反馈

我想这里*可能*是有问题的：
新版本的minio把API和console分开了，不带token的访问会被redirect到console去，而私有部署的时候，一般都在配置完成后把console封掉。
这就会导致，正常通过API访问数据是没问题的，但是直接访问endpoint是404
我猜测，如果这个前置探测无法成功，就不会自动同步？？

### Expected result

请确定一下是否为BUG

### Version environment

```markdown
- Version: 3.0.15
- Operating System: windows10
- Browser (if used):none
```

### Log file

W 2024/07/24 22:11:27 net.go:122: check url [https://**********:8443/] is online failed: Get "https://**********:8443/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I 2024/07/24 22:11:29 repository.go:1279: syncing data repo [device=9e2f7421-6161-423d-ab8f-86d4d8ed46b3, kernel=scx83nm, provider=2, mode=a/false]
I 2024/07/24 22:11:29 ref.go:50: got local latest [device=9e2f7421-6161-423d-ab8f-86d4d8ed46b3/windows, id=b7e73df9fa1ec53b28bccce002e7b18a1e98c769, files=452, size=36.33 MB, created=2024-07-24 20:57:59]
I 2024/07/24 22:11:29 repo.go:595: walk data [files=452] cost [23.7814ms]
I 2024/07/24 22:11:29 ref.go:50: got local latest [device=9e2f7421-6161-423d-ab8f-86d4d8ed46b3/windows, id=b7e73df9fa1ec53b28bccce002e7b18a1e98c769, files=452, size=36.33 MB, created=2024-07-24 20:57:59]
I 2024/07/24 22:11:32 s3.go:94: uploaded object [repo/lock-sync]
I 2024/07/24 22:11:32 ref.go:50: got local latest [device=9e2f7421-6161-423d-ab8f-86d4d8ed46b3/windows, id=b7e73df9fa1ec53b28bccce002e7b18a1e98c769, files=452, size=36.33 MB, created=2024-07-24 20:57:59]
I 2024/07/24 22:11:34 s3.go:121: downloaded object [repo/refs/latest]
I 2024/07/24 22:11:35 s3.go:121: downloaded object [repo/indexes/b7e73df9fa1ec53b28bccce002e7b18a1e98c769]
I 2024/07/24 22:11:35 sync.go:1581: got cloud latest [device=9e2f7421-6161-423d-ab8f-86d4d8ed46b3/windows, id=b7e73df9fa1ec53b28bccce002e7b18a1e98c769, files=452, size=36.33 MB, created=2024-07-24 20:57:59]
I 2024/07/24 22:11:35 s3.go:138: removed object [repo/lock-sync]
I 2024/07/24 22:11:36 repository.go:1347: synced data repo [device=9e2f7421-6161-423d-ab8f-86d4d8ed46b3, kernel=scx83nm, provider=2, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=19.75 kB] in [6.64s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/07/24 22:52:09 box.go:77: auto stat [trees=185, blocks=9298, dataSize=36.64 MB, assetsSize=1.67 MB]

**Comment by 88250** [comment]
不是 bug，同步前需要检查网络连通性。

**Comment by go1em** [comment]
nice，要饭不能嫌馊，我懂我懂
