### ISSUE TITLE
右键数据库视图时不应该打开该视图

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12083]
两个问题：

1. 右键视图时会打开该视图
2. 在已经弹出一个菜单的情况下，再右键其他视图，菜单隐藏后不会立即重新弹出

[视频.webm](https://github.com/user-attachments/assets/39ee1f14-0160-407c-bef6-1e99b7537708)

### Describe the optimal solution

Notion 右键视图是直接弹出菜单的，不会切换视图

**Comment by 88250** [comment]
我感觉目前这个设计比较好，右键菜单都是一些写入功能，切换以后能更直观地让用户知道当前操作的视图，所以这个设计就不考虑改动了，感谢反馈。
