### ISSUE TITLE
Automatically refresh database views after deleting/rolling back documents

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12081]
奇怪的数据库

工作空间：[测试空间.zip](https://github.com/user-attachments/files/16364944/default.zip)

- 遇到编辑数据库后没有生成文件历史的情况 #12078
- 数据库绑定的三个文档在删除和回滚时的表现都不同：

   [视频.webm](https://github.com/user-attachments/assets/e4de1e5d-baaa-4752-81ed-a0bebab7cfbf)

p.s. 我在测试 #11959 和研究 #11887 的时候反复编辑、删除和回滚文档，不知道怎么这个数据库就成这样了

**Comment by 88250** [comment]
删除文档的实现做了一些改进，后面自动刷新数据库应该就正常了。

回滚文档也做了一些改进，会刷新关联的数据库了（要等大概 3s 左右）。
