### ISSUE TITLE
消息只弹出一个勾

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12080]
在历史数据比较多的时候清理，比较容易复现：

[视频.webm](https://github.com/user-attachments/assets/6aad1cf0-9f0a-41bc-a8b2-525ab1325e14)

**Comment by 88250** [comment]
我这里重现不了。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by TCOTC** [comment]
很怪啊，刚才又试了一下「在历史数据比较多的时候清理」，还是会出现只有一个勾的情况：

![image](https://github.com/user-attachments/assets/c3a257de-be84-4ba6-8ce6-8be53e74d583)

**Comment by 88250** [comment]
可以关注看下开发者工具网络 websocket 的推送内容，另外内核日志是否有报错？

**Comment by TCOTC** [comment]
网络里就这两个，感觉没啥特别的：

[127.0.0.1.zip](https://github.com/user-attachments/files/16487972/127.0.0.1.zip)

![image](https://github.com/user-attachments/assets/40abf82f-f1e0-4bf1-9acd-d46e6f7bed98)

日志：

[system-log.zip](https://github.com/user-attachments/files/16487973/system-log.zip)

**Comment by 88250** [comment]
内核日志未发现问题。

要看 websocket messages：

![image](https://github.com/user-attachments/assets/69f45298-47ba-4c6c-bc1b-196ed0d66748)

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/dda300a2-5e04-4f78-88f4-21fe2189965a)

**Comment by 88250** [comment]
内核已经推送消息了，那可能是界面显示的问题，不好重现没法定位了。

**Comment by 88250** [comment]
稍微进行了一些调整，请后面再试试。
