### ISSUE TITLE
此md文档打不开

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#1208]
### 描述问题 Describe the problem

此`.md`文档用思源打不开。
### 期待的结果 Expected result

能像typora那样正常打开。

### 版本环境 Version environment

* 版本 Version： v0.6.5 / Kernel v0.6.5
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

### 该文档
[test.zip](https://github.com/siyuan-note/siyuan/files/5847236/test.zip)

**Comment by 88250** [comment]
你好，我这里试了一下，可以打开。不过这篇文档有点大，编辑起来会比较卡，这个后面优化看看。

![image](https://user-images.githubusercontent.com/873584/105319767-4908c900-5c00-11eb-8825-1ac4964e4364.png)

PS：请在文件树上使用导入功能。

**Comment by nanmao** [comment]
> 你好，我这里试了一下，可以打开。不过这篇文档有点大，编辑起来会比较卡，这个后面优化看看。
> 
> ![image](https://user-images.githubusercontent.com/873584/105319767-4908c900-5c00-11eb-8825-1ac4964e4364.png)
> 
> PS：请在文件树上使用导入功能。

刚开始用右键打不开，然后用文件树导入也没有文档出现，从网页复制在思源粘贴也粘贴不了。
晚上重启了思源用文件树导入就成功了。
我希望：
●能直接用右键选择思源打开这个文档。
●从文件树导入能百分百成功导入。
●从网页复制这篇[文章](http://super-memory.com/help/il.htm)，能在思源直接粘贴。

**Comment by 88250** [comment]
@nanmao 收到，导入后续会做拖拽支持，这样方便操作一些。
