### ISSUE TITLE
能否将外观最近使用的外观列出来,而不要放在里面.

### ISSUE THREAD

**Issue by noenif** [siyuan-note/siyuan#12084]
### In what scenarios do you need this feature?

当我学习英语书籍的时候,我喜欢将前置定语和后置定语,前置状语和后置状语列出来.然后标出整个主谓宾.还有生词.

当我学习一个知识点的时候,我喜欢,画出句子的论据论点主题.

因此我会经常使用这些外观.

### Describe the optimal solution

现在我一直需要两次点击,确实延缓了使用时间.

**Comment by 88250** [comment]
这个设计应该不会变了，如果只是最近一个使用的外观，建议用快捷键，感谢反馈。
