### ISSUE TITLE
Can't open folded icons menu in top bar when title icon and/or VIP icon are disabled

### ISSUE THREAD

**Issue by mustakshif** [siyuan-note/siyuan#12087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The folded icons menu fails to open when the `barMore` element in the top bar is clicked if the title icon and/or VIP icon are disabled. 

This occurs because the `barMore` element's `data-hideids` property retains the value `toolbarVIP`, regardless of whether these icons are disabled in the account settings.

<img width="605" alt="screenshot" src="https://github.com/user-attachments/assets/3244daef-0efd-4137-ad7b-e2ebc71e4bca">

### Expected result

The folded icons menu should open when the `barMore` element is clicked, regardless of whether the title icon or VIP icon are enabled or disabled. 

### Version environment

```markdown
- Version: 3.1.1
- Operating System: macOS 15.0
- Browser (if used): none
```

### Log file

none

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
