### ISSUE TITLE
Supports converting network assets in the database to local

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12096]
数据库里的网络资源无法转换到本地

![image](https://github.com/user-attachments/assets/aabe217e-8866-42e7-9b65-64703b356207)

都不行：

![image](https://github.com/user-attachments/assets/cd81132d-b713-45f4-ab43-2556058322cd)

**Comment by 88250** [comment]
发一下日志，可能是因为网络无法连通的问题导致的。

**Comment by TCOTC** [comment]
[system-log.zip](https://github.com/user-attachments/files/16386600/system-log.zip)

应该跟网络没啥关系：

[视频.webm](https://github.com/user-attachments/assets/a6c62da5-1b87-4be7-b723-79c9197c67b9)

**Comment by 88250** [comment]
不好意思，的确有点问题，稍后改进。
