### ISSUE TITLE
An "exit" button needed on the front-end

### ISSUE THREAD

**Issue by Leo-Zhan** [siyuan-note/siyuan#12093]
### In what scenarios do you need this feature?

this app need to sync and exit manully now, but these two buttons are hidden in the setting.  

### Describe the optimal solution

So it is convenient while "exit" button showed on the top always, and sync automatically.

![PixPin_2024-07-25_17-27-53](https://github.com/user-attachments/assets/da854100-9c27-457c-9c12-ec303e365998)

**Comment by 88250** [comment]
Exit is not a frequently used function, so it is placed in the sidebar panel.
