### ISSUE TITLE
SSL seems to not be working?

### ISSUE THREAD

**Issue by HarD-BR** [siyuan-note/siyuan#12097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I'm trying to run a container with `'--ssl=true'` on command property, but it doesn't seem to be effective.

### Expected result

To run SiYuan on 443 behind a reverse proxy with SSL

### Screenshot or screen recording presentation

Property:
![image](https://github.com/user-attachments/assets/8f137dd9-bace-4a97-b8ae-ac157e9dcf5c)

### Version environment

```markdown
- Version: latest
- Operating System: Client - W11 Pro // Docker host - Debian 11
- Browser (if used): Google Chrome
```

### Log file

I 2024/07/25 22:43:30 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/07/25 22:43:30 runtime.go:74: kernel is booting:
    * ver [3.1.1]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/07/25 22:43:30 conf.go:125: loaded conf [/siyuan/workspace/conf/conf.json]
I 2024/07/25 22:43:30 runtime.go:123: use network proxy [system]
I 2024/07/25 22:43:30 serve.go:127: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/07/25 22:43:30 conf.go:835: database size [14 MB], tree/block count [64/5276]
I 2024/07/25 22:43:30 working.go:193: kernel booted
I 2024/07/25 22:43:30 box.go:77: auto stat [trees=64, blocks=5276, dataSize=3.31 MB, assetsSize=1.92 MB]
I 2024/07/25 22:53:11 serve.go:230: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36]

**Comment by 88250** [comment]
Hello, you need to configure an SSL certificate on the reverse proxy server.
