### ISSUE TITLE
改进关联当前数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12095]
https://ld246.com/article/1721915754732

Notion 会在同一列中相互关联，但思源没有：

[视频.webm](https://github.com/user-attachments/assets/5ad7b38a-b9b6-4e7b-a57d-65886d20510b)

**Comment by Wetoria** [comment]
主要还是目前双向关联的逻辑是新增一列，而不是复用当前列。

如果是当前数据库的话，双向关联应该是同一个列，而不是新增一列。只有当关联的数据库不是当前数据库的时候，才需要给目标数据库添加一个新的列。

数据库A--关联-->数据库A，只有一个列
数据库A--关联-->数据库B，在B中新增一个列

**Comment by TCOTC** [comment]
> 如果是当前数据库的话，双向关联应该是同一个列，而不是新增一列。

这个不能改，跟 Notion 保持一致

**Comment by 88250** [comment]
这个不考虑加了，感谢提议。

**Comment by TCOTC** [comment]
为啥不加了哇，我还挺需要的
