### ISSUE TITLE
关于集成GitHub进行云同步的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1210]
## 描述

当前思源的设定是一个新笔记本会新建一个 Git 仓库，但是这样在 GitHub 上就要对应建相应个数的仓库，不仅会浪费空间并且操作更加麻烦。

## 改进建议

所以个人觉得可以所有笔记对应一个仓库

**Comment by 88250** [comment]
你好，这部分设计不会进行变更了，见谅。
