### ISSUE TITLE
Improve HTML details-summary clipping

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12106]
改进剪藏 HTML details 元素

- `<details>` → 放进无序列表，折叠
- `<details open="">` → 放进无序列表，展开
- `<summary>foo</summary>` 内的文本就是列表块的首个子块

## 01

https://simoncozens.github.io/feature-tags/

![image](https://github.com/user-attachments/assets/7ff1e75d-27c0-4e72-a9de-68a16d9a5a62)

可以把圈起来的部分放到两个展开的无序列表块里：

![image](https://github.com/user-attachments/assets/795c15f1-c79f-4111-b6eb-feee3156097c)

## 02

https://ld246.com/article/1692089679062

![image](https://github.com/user-attachments/assets/d50ecdd3-126b-444d-93e1-887cbd4f65c5)

可以把圈起来的部分放到一个折叠的无序列表块里：

![image](https://github.com/user-attachments/assets/a5079723-88d7-4886-a492-689a14fd5458)

---

关联 https://ld246.com/article/1722058786914

**Comment by 88250** [comment]
折叠状态搞不了，这里只能按标准 Markdown 转换。
