### ISSUE TITLE
tree not found 的日志能否提供更多信息？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12104]
经常有人遇到 tree not found ，但没有稳定的重现步骤、看日志也定位不了问题

![image](https://github.com/user-attachments/assets/2160a4a4-549e-40db-acd1-475ce64b2c78)

https://ld246.com/article/1722041397080

**Comment by 88250** [comment]
下个版本改进，加入更详细的日志打印。

这个改动就不拉进版本了。

**Comment by HowcanoeWang** [comment]
我这边鼠标在导航条上移动或滚动可以稳定弹出报错UI

**Comment by TCOTC** [comment]
录屏看看

**Comment by TCOTC** [comment]
@HowcanoeWang 你看看那个叫 2024.04.03 的文档存不存在？

**Comment by HowcanoeWang** [comment]
> @HowcanoeWang 你看看那个叫 2024.04.03 的文档存不存在？

2024.04.03那个文档是在的

**Comment by TCOTC** [comment]
打开那个页签然后试试折叠文档树再定位

**Comment by HowcanoeWang** [comment]
电脑更新重启后，这个UI错误又无法触发了，把标签页打开成上面录屏的，也无法触发这个报错
