### ISSUE TITLE
只有在启用 Tesseract 的情况下才能进行 ocr 搜索

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#12107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这个帖子有人反馈无法搜索图片 https://ld246.com/article/1718783978167/comment/1721268978239#comments

我阅读代码
https://github.com/siyuan-note/siyuan/blob/1f46d16055d7143eb77eeb63e32d99b9aa32cf14/kernel/treenode/node.go#L135
发现这里似乎是只有 Tesseract 启用了才能进行 ocr 搜索，这导致插件提供的 ocr 搜索功能也还需要用户启用 Tesseract ，或者用户之前使用 Tesseract  建立了 ocr-text.json 但后面关闭的话还是不能进行搜索

### Expected result

ocr 搜索只与 ocr-text.json 相关，不和 Tesseract 强绑定

### Version environment

```markdown
- Version: v3.1.1
- Operating System: windows11
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
欢迎 PR 改进。

**Comment by 88250** [comment]
经过分析，不启用 OCR 时也可以搜索到的，只是要等重建索引执行完才能搜索到。
