### ISSUE TITLE
[汇总] 数据库条目编辑的相关提案

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12103]
![条目编辑](https://github.com/user-attachments/assets/b1a0fc44-ce48-4c1a-bbce-23acd161c064)

- [ ] #11965
- [ ] #12022
- [ ] #11100
- [x] #12102
- [x] #11612
- [x] #11349

**Comment by 88250** [comment]
这个 issue 我关闭了，谢谢。
