### ISSUE TITLE
编辑数据库单元格，支持实时应用更改

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12102]
参考 Notion 的实时筛选，对单元格内容的修改是实时的：

https://github.com/siyuan-note/siyuan/assets/78434827/11646dbc-842a-4339-8d85-c5110d93fc19

实现这个功能之后继续实现实时筛选和排序：#11349

**Comment by 88250** [comment]
这个搞不了：技术困难，并且工作量太大了，除非在前端再实现一套计算逻辑。
