### ISSUE TITLE
多选块的蓝色无法覆盖子块的自定义外观颜色

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12105]
[颜色.sy.zip](https://github.com/user-attachments/files/16398314/sy.zip)

像上面的引述块被选中后颜色可以被覆盖，但下面的列表块就不行：

![image](https://github.com/user-attachments/assets/017d5e51-0006-4e13-90e4-fd0891d39cef)

只选中这两个块的时候才能被正常覆盖：

![image](https://github.com/user-attachments/assets/831b388d-f3d6-4f9d-98de-d1b7435882b4)

**Comment by Vanessa219** [comment]
选中的是哪一个块只会修改那一个块的背景，子块不进行修改。

**Comment by TCOTC** [comment]
我的意思就是这是个问题

**Comment by TCOTC** [comment]
多选块时，子块不应该应用颜色

**Comment by Vanessa219** [comment]
操作的时候并不会操作子块，改变的话可能会让用户误解。

**Comment by TCOTC** [comment]
子块颜色不变的话才会有误解。应该统一为被选中的块就变成蓝色

**Comment by Vanessa219** [comment]
看了下 notion 也是维持不变的，它可能也是怕用户误解才这么做的。这个就不进行修改了。

**Comment by TCOTC** [comment]
其实有点不同，如果用 Notion 的方案，子块的颜色是会与蓝色叠加的，思源的子块颜色则是完全没有变化（比较突兀）：

[视频.webm](https://github.com/user-attachments/assets/7c2d552e-a54f-43f3-a29e-12025c85ec9e)

**Comment by Vanessa219** [comment]
比较微弱，我们也弱弱的改一下吧。

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by TCOTC** [comment]
@Vanessa219 有办法只让原本的背景色变透明而不是整个元素变透明吗？

**Comment by Vanessa219** [comment]
选中的背景色为 var(--b3-theme-primary-lightest) ，如果这个设置的是透明的话就是透明的，用户可以自己修改。

**Comment by TCOTC** [comment]
我的意思是这个样式把整个子元素都变透明了：

https://github.com/siyuan-note/siyuan/blob/11386294056d511ee0127b92daed9418254be255/app/src/assets/scss/protyle/_wysiwyg.scss#L452-L454

比如改成 `opacity: .26;` ，文本就很淡了：

![image](https://github.com/user-attachments/assets/3d620789-9f08-4cdd-af49-173a6d6d5770)

怎样保持内部文本的颜色不变？

**Comment by Vanessa219** [comment]
不用改那么淡

**Comment by TCOTC** [comment]
我想只把子块的背景色改透明，但我不知道怎么改

**Comment by Vanessa219** [comment]
只改背景色的话要使用 background-color: rgba
