### ISSUE TITLE
如何通过 CSS 控制未钉住的侧栏弹出与收回？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12108]
> 跟 #11908 遇到的是同一个问题，侧栏太容易触发

想通过 CSS 控制未钉住的侧栏弹出与收回：

- 用 `animation-delay: 200ms;` 控制悬停等待的时间
- 用 `animation-duration: 200ms;` 控制侧栏弹出与收回的时间

但是我感觉这个侧栏弹出与收回好像不是通过 CSS 实现的？

https://github.com/siyuan-note/siyuan/blob/73cb847d1d01c0291c878506f07439664137657c/app/src/util/globalShortcut.ts#L119-L131

https://github.com/siyuan-note/siyuan/blob/687421fe62beb6bddd46c69a263c485bb1fe6619/app/src/layout/dock/index.ts#L415-L491

关联 https://ld246.com/article/1720580075525

另一个与未钉住侧栏相关的 issue ：#11938

**Comment by 88250** [comment]
@Vanessa219 有空看看

**Comment by Vanessa219** [comment]
延时显示最终还是会显示出来，这个体验可能更不好。

**Comment by 88250** [comment]
这个作为讨论话题先关闭了。

**Comment by TCOTC** [comment]
@Vanessa219 我自己体验好就行了嘛，我自己控制延迟的时间。思源默认立即弹出就好了

**Comment by Vanessa219** [comment]
那应该可以的

**Comment by TCOTC** [comment]
总结一下，目前的问题就是侧栏弹出与收回不是通过 CSS 实现的，所以用户也就没法通过 CSS 来控制弹出速度快慢

**Comment by Vanessa219** [comment]
可以用延时的 css

**Comment by TCOTC** [comment]
是用哪个？

**Comment by Vanessa219** [comment]
`transition-delay`

**Comment by TCOTC** [comment]
原来是这个。不过跟我预期有点不同，之前没搞清楚。


有没有办法能实现鼠标保持悬停 500ms 才弹出侧栏呢？（不是鼠标碰到侧栏后再等待 500ms）

**Comment by Vanessa219** [comment]
这个需要改 js 了。如果不快的话，用户可能会觉得卡顿。
