### ISSUE TITLE
在非聚焦状态下，块标菜单应该隐藏 `聚焦到上层` 选项

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12115]
在非聚焦状态下，`聚焦到上层` 是无效的。需要先 `聚焦` 了才能 `聚焦到上层`

![image](https://github.com/user-attachments/assets/ac505b3f-f25b-4cdd-a59f-0baded1f0936)

**Comment by 88250** [comment]
情况比较复杂，还是固定出现吧，这个也没有副作用。

**Comment by TCOTC** [comment]
1. `聚焦到上层` 在聚焦状态以外有作用吗？
2. 在[本就过长的菜单](https://github.com/siyuan-note/siyuan/issues/12116#issuecomment-2267562324)里增加一个没用的选项是不合适的

**Comment by 88250** [comment]
目前只能这样了。

**Comment by TCOTC** [comment]
> 情况比较复杂，还是固定出现吧，这个也没有副作用。

@88250 我感觉逻辑上只要点击 `聚焦到上层` 之后编辑器没有聚焦，就说明没有上层。然后就能反推出什么情况下才显示 `聚焦到上层` 选项
