### ISSUE TITLE
改进宽度菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12117]
竖着有点占地方，建议把这几个百分比由现在的纵向排列改成横向排列：

![image](https://github.com/user-attachments/assets/868c73a2-009b-4d89-b05a-94a0c0085548)

![image](https://github.com/user-attachments/assets/ef4fdbbc-7141-460f-b4e0-021daa66bab9)

**Comment by Vanessa219** [comment]
这样不好点击，不进行修改了。
