### ISSUE TITLE
文章图标能否支持base64编码以及外链图片？

### ISSUE THREAD

**Issue by songshua295** [siyuan-note/siyuan#12119]
### In what scenarios do you need this feature?

经常使用，因为自带的图标很多都是用不到的，如果需要自定义的话，操作起来的步骤流程太多了（打开emoji文件夹⮕添加图标，可能还需要转换格式⮕重命名为合适的文件名称⮕刷新资源⮕添加图标），希望支持外链以及base64的方式。

### Describe the optimal solution

参考notion等产品：

1. 支持外链：格式一般支持ico、svg、png、jpeg，webp、gif等格式，通过本地网络进行加载；
2. 支持base64编码：这个我觉得如果会用的话，很好用，原理是html中的图片url可以指定base64编码，而不用输入图片路径，该base64就是图片的数据，我这里分享一个notion页面作为演示
    notion页面：[https://songshua.notion.site/RaiDrive-9a2e086a598344fc91daf9df2e8b0b22?pvs=4](https://songshua.notion.site/RaiDrive-9a2e086a598344fc91daf9df2e8b0b22?pvs=4)
    ![image](https://github.com/user-attachments/assets/ca2c2101-1e40-4deb-963c-88135f3e6e35)
    图标base64数据：data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAAEZSURBVFhH7de9TgJBEMDxKRUVqbBU34zjI4EQxGAkUe5OMDwFH0cgmvgCmhhrLrndcFxhI4Gz0fKukX683fACoxZqpvhnqp38drsFUxSWtl+KWsIgZcmcntnJNILeKoLhC61xGIGzWEHLMz6un8t4NS+R6gRFPQ/uJMLoDWH8Suv2HRPIGtQt1CJT5EnZ0tAze+Mi9EO1jJZCOIuYAQxgAAMY8E8AgwTgJEspTf76C1gbwGH3EbfOZrjX9Ghd+Ljb9L4PODLvcafiYaY2pXUq1PwBgP2AqarA/bpLqyExXXcZwAAGMIABvwHwxc9pOyjoedx5wtTJXC8kdR4owBouRS5s+8XYlHlS1mYmLxBvV2WsbkOqoc644SfcEASUN+hnWQAAAABJRU5ErkJggg==
    原理的话，D应该知道，但我还是附上：[https://cloud.baidu.com/article/2823386](https://cloud.baidu.com/article/2823386)

### Describe the candidate solution

这里阐述的还是交互的问题，因为打开文件夹了添加资源是非常“粗暴”和“糟糕”。

这给我的感觉就是--不像一个现代的笔记软件。在功能上，虽然思源已经做得十分不错了，但是在交互上，还是与其他大厂有一些差异。

**Comment by TCOTC** [comment]
我觉得可以学 Notion 在这里添加一个自定义图片的页面

Notion 这里可以粘贴 base64 提交：

![image](https://github.com/user-attachments/assets/a323f8f9-a450-4bb4-812b-0d25fd1bab66)

**Comment by 88250** [comment]
这个不考虑了，感谢反馈。

**Comment by TCOTC** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/12926#issuecomment-3418417583
