### ISSUE TITLE
希望点击文档树空白区域时能取消选中已选中的文档

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12118]
每次要选择文档的时候都要先 Ctrl+Click 取消选中其他已经被选中的文档，想要一个更方便的方式来取消选中。

比如点击下方空白处可以取消选择笔记本 111 ：

![image](https://github.com/user-attachments/assets/9f181dbf-4cc8-4d9f-8b79-26ab88a0c173)

还有上方：

![image](https://github.com/user-attachments/assets/ae4970de-7b1d-45fc-8a26-483789a7939e)

**Comment by 88250** [comment]
我不太理解为何要取消选中，要选择文档的话直接选择就可以了。

**Comment by TCOTC** [comment]
因为我担心同时选中笔记本和文档操作可能会有问题（比如之前忘记取消选中笔记本导致内核退出 #12090 ），所以每次都要 Ctrl+Click 一下笔记本取消选中，如果点击空白处可以取消选中已选中的笔记本或文档就会很方便。

**Comment by 88250** [comment]
目前暂时没有发现其他问题，遇到的话反馈吧。加一个取消不解决问题哦，另外，如果空白取消选中的话焦点可能会有问题，交互改动较大，所以不考虑了，谢谢。

**Comment by TCOTC** [comment]
我用 JS 片段实现了

```js
// 点击文档树空白处，取消选中文档或笔记本 JS片段
document.addEventListener('click', async function(event) {
    // 检查点击的元素及其上层元素是否包含 .block__icon 或 .b3-list
    if (!event.target.closest('.block__icon, .b3-list')) {
        // 查找 .sy__file 下所有包含 .b3-list-item--focus 类名的元素
        const focusedItems = document.querySelectorAll('.sy__file .b3-list-item--focus');
        // 去掉 .b3-list-item--focus 类名
        focusedItems.forEach(item => {
            item.classList.remove('b3-list-item--focus');
        });
    }
}, true); // 使用捕获阶段
```
