### ISSUE TITLE
移动端支持发布服务

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12113]
### In what scenarios do you need this feature?

桌面端有：

![image](https://github.com/user-attachments/assets/1eff4608-6913-4fd9-9930-95019c97a062)

移动端没有：

![33567a85f9c619dbe0a7a333a3f4f15](https://github.com/user-attachments/assets/04389f81-2294-47a4-9f4f-58fb65cfdc74)

**Comment by 88250** [comment]
移动端最多用于伺服使用，作为发布服务场景不多，所以不考虑了，谢谢。

**Comment by TCOTC** [comment]
感觉问题也不算大，可以在伺服里打开发布服务
