### ISSUE TITLE
改进块标菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12116]
![image](https://github.com/user-attachments/assets/ed9403d1-1d83-497a-ae84-d5c1b9a57852)

1. 改变排序：

   `跳转到父块`
   `跳转到父块的上一个块`
   `跳转到父块的下一个块`

2. 仅在 列表块/列表项块的块标菜单 和 列表项的子块的 `Ctrl+/` 菜单 中显示 `跳转到父块的上一个块` 和 `跳转到父块的下一个块` ，在其他类型的块的菜单中隐藏

   p.s. 我追溯了这三个功能的来源 #9527 #11193 ，发现 `跳转到父块的上一个块` 和 `跳转到父块的下一个块` 只有在列表里才会使用，没有其他使用场景（在其他类型的块里用是很奇怪的逻辑）

**Comment by 88250** [comment]
这个不考虑改变了，原因见 https://github.com/siyuan-note/siyuan/issues/12115#issuecomment-2267559798

**Comment by TCOTC** [comment]
1. `跳转到父块` 的三个选项顺序有点怪，我觉得还是改一改 https://github.com/siyuan-note/siyuan/issues/15833
2. 目前的块标菜单选项多得不行，我认为必须要照顾到大多数用户的使用体验，适当精简

   ![image](https://github.com/user-attachments/assets/356b27d4-0aa5-4e43-8002-6160cfb77662)

**Comment by 88250** [comment]
目前只能这样了。

**Comment by TCOTC** [comment]
块标菜单真的有点太宽了，我觉得还是移除掉更好：

![image](https://github.com/user-attachments/assets/fc38af47-0268-458d-8566-9be1830bf51c)

**Comment by 88250** [comment]
不考虑改动了，希望移除的话用插件移除吧。
