### ISSUE TITLE
希望思源笔记的笔记本展示效果能够做成和语雀app的知识库一样

### ISSUE THREAD

**Issue by lytanz** [siyuan-note/siyuan#12124]
### In what scenarios do you need this feature?

我觉得目前的思源笔记的笔记本展示不够完美，笔记本和笔记都在同一列展示，很混乱。

### Describe the optimal solution

希望思源笔记的笔记本和笔记分开，希望能做到和语雀的展示效果一样就好了。最左边是知识库，然后点击知识库，在中间打开笔记列表，最后边是笔记编辑区。
![0dcf0671dbd17e5cd7304d3abf60d898](https://github.com/user-attachments/assets/cec7dc75-b247-45c1-8c62-ee82809d53b2)

**Comment by 88250** [comment]
你好，这个不考虑改变了，感谢反馈。
