### ISSUE TITLE
设置 - 快捷键 的搜索有点问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12121]
没有搜索结果，但会显示 `编辑器` ：

![image](https://github.com/user-attachments/assets/e7c88487-a1f6-43b3-931b-1d1f5bd73201)

**Comment by 88250** [comment]
我这里测试正常：

![image](https://github.com/user-attachments/assets/41341bbb-2042-4851-a4ec-6bbc5095100d)

**Comment by TCOTC** [comment]
1. 安装一个会注册快捷键的插件，比如目录插件

   ![image](https://github.com/user-attachments/assets/3ee0d080-b6c2-49be-af2c-44aae2546fc1)

2. 重载界面
3. 搜索

   ![image](https://github.com/user-attachments/assets/16ec384f-30a2-4b24-bee4-aa975dd6d00f)

   ![image](https://github.com/user-attachments/assets/ce2fbac3-412e-48a2-ada5-95afd503f182)
