### ISSUE TITLE
Search with `search engine` in pdf reader

### ISSUE THREAD

**Issue by shvmsaini** [siyuan-note/siyuan#12122]
### In what scenarios do you need this feature?

When opening pdfs inside the built in pdf reader in siyuan, the right click should a context menu to search selected text with a search engine. 

### Describe the optimal solution

What siyuan is doing : Right click doesn't work, only a highlighting popup is shown.
![image](https://github.com/user-attachments/assets/2d717a36-82ca-4810-aa61-da57141e4812)

What logseq is doing: Shows a highlighting popup but on right click shows a context menu to search text with google.
![image](https://github.com/user-attachments/assets/ec2a33d4-2914-45c9-ade9-cbce086e3041)

**Comment by 88250** [comment]
Considering that there are so many search engines, we do not plan to add this function natively. Please look forward to community plugins. Thank you.
