### ISSUE TITLE
相同文档分屏时，点击大纲标题会使左侧的文档跳转到开头

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12125]
点这两个区域：

![image](https://github.com/user-attachments/assets/1e4a3520-ebb3-4eb9-8302-e4f766144792)

演示：

[视频.webm](https://github.com/user-attachments/assets/2263a239-ccaa-41bf-ab4d-46d226717214)

---

焦点在哪个文档，就应该是哪个文档跳转到开头

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
