### ISSUE TITLE
标签搜索条件能否支持保存设置

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#12126]
### In what scenarios do you need this feature?

点击标签后，展开的搜索面板在修改搜索条件后不会保存设置

### Describe the optimal solution

希望能够单独保存设置或继承全局的搜索条件设置，个人认为前者好点

**Comment by TCOTC** [comment]
> 在修改搜索条件后不会保存设置

无法 `保存查询条件` 吗？

**Comment by TinkMingKing** [comment]
> > 在修改搜索条件后不会保存设置
> 
> 无法 `保存查询条件` 吗？

总不能每个标签都保存一个查询条件吧，支持保存`搜索条件`才更和理

**Comment by TCOTC** [comment]
这个不够用吗：

![image](https://github.com/user-attachments/assets/3e61f3d7-f615-434b-9001-d5bcef7facb4)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by TinkMingKing** [comment]
可能是因为搜索条件的保存逻辑有问题

https://github.com/user-attachments/assets/997d7281-bf8d-4287-badc-943d5d24aa65

按道理直接点保存就行了，但是好像必须点保存查询条件才行，这样的逻辑似乎是有问题的

**Comment by TCOTC** [comment]
对哦，点这个保存压根没保存

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
这个和搜索关键字一样，需要清空查询条件后保存下次才会生效。

**Comment by TinkMingKing** [comment]
> 这个和搜索关键字一样，需要清空查询条件后保存下次才会生效。

原来如此，有点难以发现，为什么不设置成点击直接保存呢？
而且似乎发现了bug，全局搜索时，点击`清空查询条件`，红框里的搜索内容不会被清除

![image](https://github.com/user-attachments/assets/1a888dac-793e-4e55-943b-b5f9d95ada69)

**Comment by TCOTC** [comment]
我这里没有复现这个问题

**Comment by TinkMingKing** [comment]
https://github.com/user-attachments/assets/6b4a7405-7208-4e9b-a628-3d1c1179a72d

**Comment by TCOTC** [comment]
没搞明白是怎么复现的

[视频.webm](https://github.com/user-attachments/assets/c16433f7-62bf-4266-861d-0d6cb4136d07)

**Comment by TinkMingKing** [comment]
ok，破案了，它的问题
![image](https://github.com/user-attachments/assets/8f45df99-c4ae-491b-a3cc-12c9983355ba)
