### ISSUE TITLE
列表块的嵌入块不能及时更新

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12123]
[视频.webm](https://github.com/user-attachments/assets/ecde6bdd-dd66-4704-93f9-d8d676a26433)

**Comment by 88250** [comment]
从录屏上看好像没发现问题，有一点延迟是正常的。另外，因为查询嵌入块脚本可以自定义，所以无法计算影响范围，所以一些场景是需要手动刷新嵌入块的，这里就不做调整了，感谢反馈。

**Comment by TCOTC** [comment]
我的意思就是这个时候的嵌入块不对：

![Screenshot_2024-09-08-20-30-19-69_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/bed2ee02-497a-47bb-9e6d-d00dca013f24)

**Comment by 88250** [comment]
手动刷新一下吧。

**Comment by TCOTC** [comment]
所以为啥这种情况下不会更新嵌入块呢？

**Comment by 88250** [comment]
之前说了嘛：

> 另外，因为查询嵌入块脚本可以自定义，所以无法计算影响范围，所以一些场景是需要手动刷新嵌入块的，这里就不做调整了

**Comment by TCOTC** [comment]
我就是不太理解同样是编辑块的操作，咋有的场景就不行 🤔

不管了

**Comment by TCOTC** [comment]
> 因为查询嵌入块脚本可以自定义，所以无法计算影响范围

话说不能针对思源本身的 SQL 优化一下吗？

`{{select * from blocks where id='20240928163748-ongydf6'}}` 我看起来也不像是确定不了影响范围的

**Comment by 88250** [comment]
嵌入块不只有 id 形式的，所以不考虑了



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月28日(周六) 晚上7:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 列表块的嵌入块不能及时更新 (Issue #12123)




  
因为查询嵌入块脚本可以自定义，所以无法计算影响范围
  
@88250 话说不能针对思源本身的 SQL 优化一下吗？
 
{{select * from blocks where id='20240928163748-ongydf6'}} 我看起来也不像是确定不了影响范围的

**Comment by TCOTC** [comment]
已在 https://github.com/siyuan-note/siyuan/issues/14370 中改进
