### ISSUE TITLE
公众号剪藏缺少换行

### ISSUE THREAD

**Issue by DearZack** [siyuan-note/siyuan#12133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复现地址：https://mp.weixin.qq.com/s/wY8kYYHdRI8v0m5L8IIYSw

### Expected result

复现地址：https://mp.weixin.qq.com/s/wY8kYYHdRI8v0m5L8IIYSw

### Version environment

```markdown
- Version: v3.1.1
- Operating System: win11
- Browser (if used):chrome
```

### Log file

- Version: v3.1.1
- Operating System: win11
- Browser (if used):chrome

**Comment by DearZack** [comment]
是代码块缺少换行

**Comment by 88250** [comment]
感谢反馈，合并到 https://github.com/siyuan-note/siyuan/issues/12014 一并处理。
