### ISSUE TITLE
无法同步

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#1213]
### 描述问题 Describe the problem

新建的文件夹, 把原来内容移动到改文件夹. 点击同步一直处于同步状态, 实际上未同步. 云端也没有同步的仓库

### 期待的结果 Expected result

能够正常同步

### 截屏或录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/18739609/105352334-baf50880-5c28-11eb-9277-3a2054d30dd1.mp4

### 版本环境 Version environment

* 版本 Version：0.6.6
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5849309/siyuan.log)

### 更多信息 More information

无

**Comment by 88250** [comment]
请关闭“思源笔记用户指南”笔记本后再试试同步，谢谢。

**Comment by banjuer** [comment]
原来如此!🤤
