### ISSUE TITLE
为小屏设备添加以desktop模式打开的选项

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12135]
### In what scenarios do you need this feature?

由于mobile模式不支持多标签页等功能，因此希望D大可以添加一个选项，支持在手机上以desktop模式访问客户端。

有兴趣通过主题自己提升编辑体验。

谢谢D大

### Describe the optimal solution

添加一个运行模式：desktop/mobile

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/11789
