### ISSUE TITLE
文档属性面板的独立快捷键，以及将文档属性面板嵌入文档的选项

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12138]
### In what scenarios do you need this feature?

D大这个功能很有用的，一个是方便编辑，二个是有这个功能，就能有更多的文档布局花样了！！！

### Describe the optimal solution

![图片主题：集合、关系、类型和模板 - 任意案例 - 任意类型社区 --- Picture thread Sets, Relatio](https://github.com/user-attachments/assets/3f47dd57-8445-431c-9b3e-0038117d1cb1)
![Fifth](https://github.com/user-attachments/assets/a3e4dce2-f4e1-422d-a152-b1fc5484b846)
![图片主题：集合、关系、类型和模板 - 任意案例 - 任意类型社区 --- Picture thread Sets, Relatio](https://github.com/user-attachments/assets/9f83030e-fa46-4e05-a122-ce0a8c57c40e)

**Comment by TCOTC** [comment]
#11371 ？

**Comment by 88250** [comment]
Duplicate of #11371
