### ISSUE TITLE
退出聚焦时，如果聚焦的块不存在，文档会被关闭

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12130]
[视频.webm](https://github.com/user-attachments/assets/561e4ba3-12de-483c-a656-aa375492fb7d)

**Comment by TCOTC** [comment]
如果聚焦的块不存在，回到文档开头应该比较合适

**Comment by 88250** [comment]
为了避免进一步发生不一致的情况，所以得关闭编辑器。

**Comment by TCOTC** [comment]
我认为可以重新加载文档而不必完全关闭编辑器
