### ISSUE TITLE
设置>外观 中，刷新按钮不见了

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#12136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

外观中的刷新按钮不见了
![image](https://github.com/user-attachments/assets/20a4daa9-62bb-46a3-8923-448217011e6a)
它还是很有用的，当修改一个插件、增加一个新的emoji图片，都需要通过刷新按钮更新，而不用重新打开

### Expected result

有刷新按钮，或者有其他机制，能刷新

### Version environment

```markdown
- Version: 3.1.1
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
打开开发者工具，然后 Ctrl|+R

**Comment by TCOTC** [comment]
设置 - 快捷键 - 刷新

![image](https://github.com/user-attachments/assets/7dadbd90-b580-403f-ab59-6496e4874d8a)
