### ISSUE TITLE
The database-bound block is automatically added to the database after being copied as a replica

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12140]
文档复制为副本/生成冲突文档，其中数据库绑定的块的副本也要添加到数据库中

https://github.com/siyuan-note/siyuan/issues/11959#issuecomment-2257580142

[视频.webm](https://github.com/user-attachments/assets/3fb24507-a2f0-4715-8bb1-1aae8213d281)

**Comment by Jiangshuon** [comment]
T兄，你是大学生吗，每天空闲时间这么多！

**Comment by Jiangshuon** [comment]
@88250 ，d大希望这个考虑下

比如一种重要应用场景：

目前文档冲突后会复制一份文档，解决冲突时，要是删了原文档就麻烦了。

文档中块绑定的数据库会全部丢失，因为复制文档中的块是没有绑定的。

这给解决冲突带来不便，删除要非常注意——只能删复制文档，不能删原文档

**Comment by 88250** [comment]
收到，稍后看看。

**Comment by 88250** [comment]
已在 #12294 移除该功能
