### ISSUE TITLE
author 改变的插件不在 集市 - 已下载 的待更新列表中

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12142]
1. 在 data\plugins 创建 siyuan-plugin-task-list 文件夹
2. 下载 [siyuan-plugin-task-list 插件 v0.3.4](https://github.com/syh19/siyuan-plugin-task-list/releases/tag/v0.3.4) 的 [package.zip](https://github.com/syh19/siyuan-plugin-task-list/releases/download/v0.3.4/package.zip) 解压到文件夹
3. 打开 集市 - 已下载，无法显示更新：

   ![image](https://github.com/user-attachments/assets/785d063b-44a9-48c7-ad85-1209229b91b1)

4. 打开插件的 plugin.json 文件，将 `"author": "syh19",` 修改为 `"author": "sylwair",`
5. 之后再打开 集市 - 已下载，就能显示更新了：

   ![image](https://github.com/user-attachments/assets/e2aad977-4d62-42eb-a587-7d6cf8e1aae0)

---

[system-log.zip](https://github.com/user-attachments/files/16424504/system-log.zip)

**Comment by 88250** [comment]
库地址变化的话会认为不是一个库了。

**Comment by TCOTC** [comment]
但 GitHub 仓库没变

**Comment by 88250** [comment]
判断集市包是否有更新也会对比作者字段：

![image](https://github.com/user-attachments/assets/a88263ff-3836-42e9-b73d-8510fd49afd7)

**Comment by TCOTC** [comment]
但 GitHub 仓库没变的话，为什么作者变了要认为不是一个库？

**Comment by 88250** [comment]
url，author 和 name 构成的唯一标识，这个最好不要变。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月4日(周日) 晚上10:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] author 改变的插件不在 集市 - 已下载 的待更新列表中 (Issue #12142)




 
但 GitHub 仓库没变的话，为什么作者变了要认为不是一个库？
