### ISSUE TITLE
希望超链接以更编辑的方式被创建

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#1214]
在目前超链接的创建方式还是要借助语法的
由于网址通常较长，所以不太方便的，尤其是目前思源采用的还是所见即所得的方式。
菜单栏上的超链接按钮也不太实用
建议当点击那个按钮的时候，直接跳出对话框，上一行填标题，下一行填网址。点击确定后自动生成、
然后希望以卡片的形式显示超链接，这样感觉比较正式一点，也更能激发人们点击超链接查看的欲望

**Comment by 88250** [comment]
你好，如果是复制超链接的话，请复制后试试快捷键 <kbd>Ctrl K</kbd>，会自动做链接插入格式的。

卡片形式需要网络支持，并且目标网站需要实现某些规范这样才能有较好的展现体验，这方面目前暂时没有计划做改进，感谢提议。
