### ISSUE TITLE
在分隔线后的只含零宽空格的段落块无法通过 Backspace 删除

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12149]
[你有哪些特别牛的自学经历？ - 知乎.sy.zip](https://github.com/user-attachments/files/16428994/-.sy.zip)

[视频.webm](https://github.com/user-attachments/assets/c98af0f6-301c-4289-94d6-e861c97b939f)

**Comment by 88250** [comment]
@Vanessa219 这里是个零宽空格：

![image](https://github.com/user-attachments/assets/308acbaa-d2f9-4903-ab4d-ac35845b776e)

**Comment by TCOTC** [comment]
@88250 可能剪藏也有问题，这个段落块是剪藏 https://www.zhihu.com/question/55049980/answer/3576791962 产生的

**Comment by Vanessa219** [comment]
@88250 已处理，你再看一下剪藏为什么会有零宽空格

**Comment by 88250** [comment]
找到了，是左边目录导致的，这个最好还是不动了：

![image](https://github.com/user-attachments/assets/06b64827-5339-41f0-b35c-eb35afbd1e44)
