### ISSUE TITLE
改进移动端插件功能提示文案

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12145]
https://ld246.com/article/1722442902755

这个提示很奇怪，完全看不出这个功能是什么、要怎么用。

这是在插件添加了侧栏按钮之后才有用的，并且是在桌面端配置好之后重启移动端才能生效的：

![3f681bdc90532ffb0b570764d439ff53](https://github.com/user-attachments/assets/d7c0d91f-9d77-4faf-89b6-0f91837f0677)

**Comment by TCOTC** [comment]
始终会显示一行「未找到相关内容」：

**Comment by wish5115** [comment]
我觉得，这不仅仅是提示问题，这是设计问题，应该把这个插件按钮改成“更多”按钮，用户很容易理解，显示更多侧边栏工具，而点开后显示，没有了或者不展开提示尚没有更多侧边栏工具

**Comment by TCOTC** [comment]
合理

**Comment by Vanessa219** [comment]
> 提示尚没有更多侧边栏工具

@TCOTC  这个是怎么操作出现的？

**Comment by Vanessa219** [comment]
如果提示 `尚没有更多侧边栏工具` 的话，用户不知道要怎么获取更多侧边栏工具。

**Comment by TCOTC** [comment]
@Vanessa219 如果安装的插件没有添加任何侧边栏功能，点击移动端左侧栏的插件图标就会提示：“该功能需在思源桌面端进行配置。如果你已经配置，请在顶部账号设置中进行刷新”

**Comment by Vanessa219** [comment]
是会有提示的，我的意思是下图这个怎么重现的？
![QQ_1723300312944](https://github.com/user-attachments/assets/c45a3792-4abf-44e9-9af0-29d0c79c51dc)

**Comment by TCOTC** [comment]
用了这个插件，会添加一个侧栏功能：

![image](https://github.com/user-attachments/assets/cbc063b3-97f6-42ce-85e9-40a5df6781a7)

视频上传中

**Comment by wish5115** [comment]
> 如果提示 `尚没有更多侧边栏工具` 的话，用户不知道要怎么获取更多侧边栏工具。

提示后面可以加个帮助链接，用户点进去查看详细说明

**Comment by TCOTC** [comment]
> 加个帮助链接

我倾向于直接完整说明怎么获取更多侧边栏工具，反正屏幕位置是够的

**Comment by Vanessa219** [comment]
移动端无法挂载帮助文档，否则无法审核通过。

**Comment by TCOTC** [comment]
话说是某一个文档有问题还是整个用户指南都不能有？

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/11492

**Comment by Vanessa219** [comment]
> 用了这个插件，会添加一个侧栏功能：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/356818296-cbc063b3-97f6-42ce-85e9-40a5df6781a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MzA1NTIsIm5iZiI6MTcyMzQzMDI1MiwicGF0aCI6Ii83ODQzNDgyNy8zNTY4MTgyOTYtY2JjMDYzYjMtOTdmNi00MmNlLTg1ZTktNDBhNWRmNjc4MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDAyMzczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNmJkYWU5NjA3OThkYWRiNDQyNzQ4N2I2OGI0NmQ1ZDY1YzQ1MjM0YWEzODY2YWNjZGZmN2U2ODE5NDg0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AAj5_WMLPPgvKXJ7sMpZV1iD9oh4Tc2-EgBwlRFMTYo)
> 
>  Record_2024-08-10-22-39-43_ed1bdeca7a858bb430bfb9c256856672.mp4

插件的问题就先不处理了，demo 上的是好的就行。

**Comment by TCOTC** [comment]
确实哦，好像是插件的问题。关联 https://github.com/frostime/sy-bookmark-plus/issues/13#issuecomment-2283031563

**Comment by TCOTC** [comment]
那就只改提示的文案就可以了

**Comment by Vanessa219** [comment]
iPhone 上没有帮助文档，文案就不用修改了

**Comment by TCOTC** [comment]
这个文案跟帮助文档没关系的吧？

![3f681bdc90532ffb0b570764d439ff53](https://github.com/user-attachments/assets/d7c0d91f-9d77-4faf-89b6-0f91837f0677)

**Comment by Vanessa219** [comment]
不是说要改成再后面加个帮助文档的链接么？还是说要改成什么？

**Comment by TCOTC** [comment]
帮助链接是 @wish5115 说的，我的疑问就在开头：

![image](https://github.com/user-attachments/assets/d14b8fb7-766f-4408-9ca7-ff41fcb77e69)

**Comment by TCOTC** [comment]
群里的大家都说不知道这个提示是什么意思，不知道这个怎么用

**Comment by 88250** [comment]
@TCOTC 请帮忙考虑一下，群里也讨论一下吧。

**Comment by TCOTC** [comment]
@88250 改成这个怎么样：

> 插件带有的侧栏功能需要在桌面端配置，配置完成后请重启思源（移动端首次使用插件需要先伺服到桌面端信任集市）

**Comment by 88250** [comment]
我觉得可行，麻烦 PR。

**Comment by TCOTC** [comment]
> > > 用了这个插件，会添加一个侧栏功能：
> > 
> > 插件的问题就先不处理了，demo 上的是好的就行。
> 
> 确实哦，好像是插件的问题。关联 https://github.com/frostime/sy-bookmark-plus/issues/13#issuecomment-2283031563

现在发现不算是插件的问题，应该由思源来处理：https://github.com/siyuan-note/siyuan/pull/16271
