### ISSUE TITLE
列表块的块引用转换为定义块时异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12148]
[视频.webm](https://github.com/user-attachments/assets/822b8520-1607-4696-b108-ada828fb7616)

**Comment by TCOTC** [comment]
这个时候是有问题的，段落块和列表块互换，段落块的前面不应该还有列表：

![image](https://github.com/user-attachments/assets/18adf44d-cbd9-4022-973b-c3331383bb61)

**Comment by 88250** [comment]
这个逻辑是这样的，如果段落的父块是列表项块，则使用列表项块作为当前引用块进行交换：

![image](https://github.com/user-attachments/assets/c03b4b3d-f9c9-4083-96b6-b1a6f9641de4)

交换后如果是列表项块，则为其添加一个列表块作为父块：

![image](https://github.com/user-attachments/assets/c29672f6-9c25-43b6-a4c9-5a4e29d39e21)

这个逻辑保持不变了，否则可能会有其他问题，感谢反馈。
