### ISSUE TITLE
:sparkles: 集市 - 已下载 中的待更新列表支持折叠与展开，并且默认折叠

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12144]
默认折叠后，先加载本地插件，再联网查询插件更新，也许能解决 #12050 的一部分问题（虽然无论折叠不折叠都连不上网查询不了）。并且默认折叠就不会在加载出更新插件的时候导致整个已下载列表跳动

**Comment by LEDZB** [comment]
意思是配置成“默认折叠”既可？貌似没有看到这个配置项

**Comment by TCOTC** [comment]
因为这只是一个提案，没有这个功能

**Comment by LEDZB** [comment]
> 因为这只是一个提案，实际没有这个功能

那请问目前这个问题有何解决的方法吗？貌似需要等10min分钟左右才可以加载出来

**Comment by TCOTC** [comment]
@88250

**Comment by 88250** [comment]
这个暂时不动了，改进 https://github.com/siyuan-note/siyuan/issues/12050
