### ISSUE TITLE
请求支持设置块标的显示逻逻

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#12141]
### In what scenarios do you need this feature?

鼠标离开还有个块标总觉得用起来没那么顺手

### Describe the optimal solution

siyuan能不能设置鼠标不在块上就隐藏块标呀，类似notion的那种，设置里加个设置项支持调整

**Comment by TCOTC** [comment]
干脆鼠标离开编辑器就隐藏块标

**Comment by TinkMingKing** [comment]
> 干脆鼠标离开编辑器就隐藏块标

比较合理的是离开块就隐藏块标，大多都是这么个逻辑

**Comment by TCOTC** [comment]
> 比较合理的是离开块就隐藏块标，大多都是这么个逻辑

目前块标是在编辑器里到处飘的，离开某个块之后块标就飘到其他块前面了

**Comment by Vanessa219** [comment]
在左侧或右侧空白已经离开块了，但还是需要显示块标的。

为什么要隐藏块标呢，只是显示着，应该不会干扰操作。

**Comment by TinkMingKing** [comment]
> 在左侧或右侧空白已经离开块了，但还是需要显示块标的。
> 
> 为什么要隐藏块标呢，只是显示着，应该不会干扰操作。

1. notion是这样做的，绝大多数软件都是这样做的
2. 块标用于操作块，离开了就没有显示以及操作的必要了，避免由于显示而分散注意力
3. 有时候想截个图，块标影响截图效果
4. 我没有任何办法让它不见，只要它出现
5. 至少要有办法让它隐藏，例如离开编辑区（WPS是这样做的），最好是离开块（notion）

**Comment by TCOTC** [comment]
我也有隐藏块标的需求，偶尔截图的时候文档里总是有几个多余的块标，很难看

**Comment by Vanessa219** [comment]
离开块的话估计不行，左右空白位置是专门有需求需要显示块标的。

**Comment by TCOTC** [comment]
我觉得离开编辑器之后能隐藏就最好了

**Comment by 88250** [comment]
这个改动就不拉进版本了。

**Comment by Temacc0531** [comment]
有点疑问
1. 我升级了 v3.1.4-dev4 但是默认工作空间没有生效，创建一个新工作空间是可以生效的，是需要怎么刷新吗
2. 鼠标在编辑器内的非块区域，块标是会继续保持显示的。但是如果是从编辑器外移入到非块区域，块标又不会显示了。逻辑应该保持一致，既然编辑器内非块区域也会显示，那就应该都显示，要不就都不显示
![GIF 2024-8-19 12-20-33](https://github.com/user-attachments/assets/581f1b37-16c6-4bd9-a61c-70bfa55f6626)

**Comment by TCOTC** [comment]
这个是没问题的，光标移动到块上会显示块标，在移动到编辑区域外隐藏块标

**Comment by Temacc0531** [comment]
> 试试打开开发者工具，在网络里勾选停用缓存，然后按 Ctrl+Shift+R 刷新

试了，没有效果

> 光标移动到块上就会一直显示块标，只有移动到文档外才隐藏块标。因为你的光标没有碰到块，所以不会有块标

我说的就是这隐藏和显示的逻辑应该统一。要不就是光标在编辑器内就显示，移出编辑器隐藏；要不就是只有和楼主说的一样光标只有在块上才显示，不在块上就隐藏。现在隐藏是按照编辑器区域，显示又是按照块区域

**Comment by TCOTC** [comment]
我需要在文档末尾仍然显示块标，用来判断文档最后一个块是否是空段落块

**Comment by Temacc0531** [comment]
找到不隐藏的原因了，如果边栏悬浮，再隐藏停靠栏，鼠标移出编辑器就不会隐藏了

> 离开块的话估计不行，左右空白位置是专门有需求需要显示块标的。

话说如果是左右空白隐藏不行，那上下空白位置隐藏是不是可以？

**Comment by TCOTC** [comment]
@Vanessa219 可以在光标移动到 protyle-top 的时候隐藏块标

**Comment by Temacc0531** [comment]
@Vanessa219 V姐看看这个

**Comment by Vanessa219** [comment]
@TCOTC 都属于编辑区域，就不改动了。

@Temacc0531 空白区域是没有块的，所以不会显示块标。

**Comment by Temacc0531** [comment]
V姐有两个问题哦

1. 如果边栏悬浮，再隐藏停靠栏，鼠标从停靠栏方向移出编辑器不会隐藏块标
2. 【空白区域是没有块的，所以不会显示块标】
编辑器内的块标的就算鼠标已经移到空白区域了块标还是会一直显示

**Comment by Vanessa219** [comment]
1. 移除的话是不是就移动到编辑器上了，所以就又显示了？
2. 空白区域还是属于编辑区域，只是没有块

**Comment by Temacc0531** [comment]
1. 我补充个图
![GIF 2024-9-4 16-08-02](https://github.com/user-attachments/assets/a54b310e-22c8-4536-abf8-2a071735b779)

**Comment by Vanessa219** [comment]
从上的话，经过了页签，页签不算编辑区域

**Comment by Temacc0531** [comment]
> 从上的话，经过了页签，页签不算编辑区域

所以我从左边移到桌面上了，这不也应该隐藏吗，桌面不是编辑区域吧

**Comment by TCOTC** [comment]
我也觉得应该隐藏

**Comment by Vanessa219** [comment]
好的，已修改。
