### ISSUE TITLE
选择框优化

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#12143]
### In what scenarios do you need this feature?

![QQ_1722328148078](https://github.com/user-attachments/assets/d474a627-693c-4cc8-9ba2-13921d368bde)

在拖动选择时，内容块内的内容也会被高亮

### Describe the optimal solution

选择块后不应该再高亮块中的内容，否则会感觉十分奇怪，不符合直觉

**Comment by TCOTC** [comment]
Duplicate of #12120

**Comment by TinkMingKing** [comment]
@88250 请问这个是不计划进行调整是吗？

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/12120

**Comment by TCOTC** [comment]
@TinkMingKing 意思是我已经在 https://github.com/siyuan-note/siyuan/issues/12120 报告过了这个问题，然后你创建了重复主题的 issue ，所以把你的关掉了
