### ISSUE TITLE
De-duplication of backlinks after referencing multiple blocks in the same block

### ISSUE THREAD

**Issue by QMike0** [siyuan-note/siyuan#12147]
段落块的反链去重问题

### In what scenarios do you need this feature?

列表项的反链可以去重，但是段落块当中的不会去重，参考[这里](https://github.com/Misuzu2027/syplugin-backlink-panel/issues/5#issuecomment-2255451401)

### Describe the optimal solution

段落块应与列表块一样，反链都应避免重复计数

**Comment by TCOTC** [comment]
确实列表项块去重了而段落块没有去重：

![image](https://github.com/user-attachments/assets/3a17b611-7cc4-47cf-baac-0e119069df46)

**Comment by Misuzu2027** [comment]
表格块也会出现重复。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3317 处理同一个块中引用相同块时去重，先改为同一个块中引用不同块也进行去重。
