### ISSUE TITLE
文档树新增按文档被引用数排序

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#1215]
今天又把以前积累的大批 markdown 文件全部导入思源试了试效果，看着文档树里显示的每个文档被引用数，突然有了这么个灵感 🤔

![image](https://user-images.githubusercontent.com/32661922/105353651-7bc7b700-5c2a-11eb-8668-27a6f5835b75.png)

**Comment by 88250** [comment]
这个应该是可以实现的，我们放在后面一点考虑，感谢提议。

**Comment by 88250** [comment]
v1.2.2 实现，文件夹还是在最前面，按照文件名自然排序，下面的文档按引用数排序：

![image](https://user-images.githubusercontent.com/873584/126089549-3babfae3-40b7-4dc9-a56f-600a6ef9fb98.png)
