### ISSUE TITLE
Improve processing when a database-bound block changes its type

### ISSUE THREAD

**Issue by alexjp** [siyuan-note/siyuan#12152]
Block binding to a database, loses its binding when changing its type (paragraph to list)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Hi,

When a block has a binding to a database, changing its type will make it lose its binding.
Say a Paragraph has a binding to a database. If I change that Paragraph into a List, and then to a Paragraph again, the binding gets lost. (it seems that it happens when turning a List into a Paragraph).

Rebinding it again to the same database, makes it reappear, and with the data previously entered.

Hope this is not a duplicate, thanks!

### Expected result

Changing a block with a database bind from a List to a Paragraph, to not lose its binding.

### Version environment

```markdown
- Version: v3.1.2
- Operating System: Linux
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16434709/siyuan.log)

### More information

EDIT: Forgot to mention. When the block loses it's binding, it will still display the name of the database that it was supposed to be bind to. But clicking on the name of the database (to the right just above the block), shows an empty dialog window, and closing that window, the binding name of the database on the block disappears.

**Comment by TCOTC** [comment]
我觉得可以这样：段落块转换为列表块时，保持段落块的 ID 不变，新增列表块和列表项块的 ID

**Comment by 88250** [comment]
@alexjp Thanks for the feedback, we'll see if we can improve it later.

@TCOTC 目前就是这样的。

**Comment by TCOTC** [comment]
> > 我觉得可以这样：段落块转换为列表块时，保持段落块的 ID 不变，新增列表块和列表项块的 ID
>
> 目前就是这样的。

我观察到不是这样的，段落块的 ID 会改变：

[视频.webm](https://github.com/user-attachments/assets/d548947e-d16b-46a9-8df2-664941a0d2e4)

**Comment by 88250** [comment]
用转换功能才不会变

**Comment by TCOTC** [comment]
> 用转换功能才不会变

那我觉得这个就是问题了

**Comment by 88250** [comment]
这个没法搞，楼主说的是另一个问题。

**Comment by alexjp** [comment]
Just quick tested, seems fixed! :) Thank you very much!
