### ISSUE TITLE
Improve sub/sup pasting as plain text

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12155]
改进 sub sup 粘贴

```
<sub>foo</sub>
<sup>foo</sup>
```

粘贴纯文本和粘贴转义文本的时候都有点问题：

[视频.webm](https://github.com/user-attachments/assets/855dd3a9-babe-492e-8dc5-aa290b47b342)

**Comment by 88250** [comment]
只能解决粘贴为纯文本的问题，粘贴转义文本的问题解决不了。
