### ISSUE TITLE
改进用户指南内容块类型章节

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12151]
1. 给 `如果需要在列表项中~~进行~~换行，请使用 <kbd>Shift+Enter</kbd> 。` （去掉 `进行` ）换个位置

   ![image](https://github.com/user-attachments/assets/594019a8-4872-4404-ac88-cfe80215a538)

2. ```
   如果需要在表格中使用 `|` ，请使用 `\` 转义，即需要输入 `\|`。

   如果需要在表格中换行，请使用 <kbd>Shift+Enter</kbd> 。
   ```

   用户不知道怎么换行：https://ld246.com/article/1722350885642

   ![image](https://github.com/user-attachments/assets/8e88314b-8cf3-4c19-811f-71fb110228c1)

3. 数据库单元格也要补充说明用 `<kbd>Shift+Enter</kbd>` 换行
4. 各语种的用户指南都要改

**Comment by 88250** [comment]
有空帮忙 PR 一发吗？

**Comment by TCOTC** [comment]
再等等
