### ISSUE TITLE
导出块引用支持 `移除`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12154]
使用场景：写作文章，块引用附在段落后，只用来关联参考的资料，希望导出时自动移除

![image](https://github.com/user-attachments/assets/d94b833d-5eb7-4e15-9d1e-ad506e240c48)

**Comment by 88250** [comment]
感谢提议，但是不考虑了，建议复制副本后手动处理或者通过某个插件移除引用（如果有这样的插件）。

**Comment by Achuan-2** [comment]
之前我提过一个类似建议：https://github.com/siyuan-note/siyuan/issues/11247

**Comment by Achuan-2** [comment]
另外想问问思源现在能通过给块添加属性，设置某个块在导出markdown、pdf时不导出吗
如果可以，就可以通过改动集市上的备注增强插件，实现在思源实现脚注功能的平替了
