### ISSUE TITLE
点击超链接没有反应

### ISSUE THREAD

**Issue by 522247020** [siyuan-note/siyuan#12153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在点击超链接，浏览器无响应

### Expected result

在点击右下角帮助，GitHub 后，弹出截图，如下
![QQ截图20240731090614](https://github.com/user-attachments/assets/6d02c6f1-a65a-4d85-b749-dc786b5d49c6)

我感觉可能是系统认为有两个浏览器导致。
据当事人反馈，说是曾经安装过夸克网盘，之后卸载，就产生这个问题。
---
我下载夸克浏览器重新安装后卸载，然后一切正常

### Version environment

```markdown
- Version: v3.1.2
- Operating System: win11
- Browser (if used): Edge
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16434964/siyuan.log)

**Comment by 522247020** [comment]
思源是用的 win 的商店版本。

**Comment by TCOTC** [comment]
一般来说只要选择了默认浏览器就行：

![image](https://github.com/user-attachments/assets/136dd3f9-91f9-4e55-a970-9c17651c136d)

**Comment by 88250** [comment]
你好，这个应该是系统浏览器设置的问题，我们关闭了。

**Comment by 522247020** [comment]
> 一般来说只要选择了默认浏览器就行：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/353665440-136dd3f9-91f9-4e55-a970-9c17651c136d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDc2NzMsIm5iZiI6MTcyMjY0NzM3MywicGF0aCI6Ii83ODQzNDgyNy8zNTM2NjU0NDAtMTM2ZGQzZjktOTFmOS00ZTU1LWE5NzAtOWMxNzY1MWMxMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAxMDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YTZiY2FiNjE0OWVmZTdmNmI1YTY2Yjk5MGU0NzU0Y2NiYmY0YTM1OTQ5ZDY1MWFkMDE4OGYwZWUxN2FmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hU0bu1FliJUK59fWXaumcdkeDjA2F5uvtMDWsRQr-SE)

不行的，点了好多次。

**Comment by TCOTC** [comment]
> 不行的，点了好多次。

那就在系统设置的默认应用里把相关的打开方式都设置为 Edge

**Comment by 522247020** [comment]
> > 不行的，点了好多次。
> 
> 那就在系统设置的默认应用里把相关的打开方式都设置为 Edge

。下次把。问题都搞定了，我是重装搞好了。

**Comment by TCOTC** [comment]
Windows 确实是有很多莫名其妙的问题
