### ISSUE TITLE
如果列表内只有一个块，该块的块标不会显示（标题块除外）

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

代码块、段落块、引述块均如此。只有标题块才会显示块标

![image](https://github.com/user-attachments/assets/f7f7c6fa-99f7-405c-b4fb-dacd32a5e663)

### Expected result

希望都显示

### Version environment

```markdown
- Version: 最新
- Operating System: win11
- Browser (if used):
```

### Log file

。。

**Comment by TCOTC** [comment]
这个是刻意隐藏的，你可以使用 `Ctrl+/` 呼出菜单

**Comment by Jiangshuon** [comment]
这样想直接拖动就没办法了哟

**Comment by 88250** [comment]
这个是设计如此，确实没有办法拖动，只能用菜单中的移动。
