### ISSUE TITLE
在达到最大列出数量的最后一个文档下方增加按钮，加载剩下的文档

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12164]
### In what scenarios do you need this feature?

因为子文档太多导致文档树太长，所以设置了 `最大列出数量` ，但设置了之后就没法看到剩下的文档了。

![image](https://github.com/user-attachments/assets/bca60764-ed0d-4053-8ff5-c721d7310c3f)

### Describe the optimal solution

想要在最后一个文档下方增加一个按钮，点击之后加载剩下的文档

**Comment by 88250** [comment]
不考虑了，文档树太长的话界面可能会卡死。

**Comment by TCOTC** [comment]
但加个按钮或者菜单的话就是可控的了

**Comment by 88250** [comment]
加载了以后可能会卡死，所以不加了。如果需要的话，直接改参数。

**Comment by TCOTC** [comment]
那每次加载后 10 条行不行？

**Comment by 88250** [comment]
不改了，意义不大。

**Comment by TCOTC** [comment]
想让文档树短一点，又不想直接忽略掉没加载出来的文档，两难啊
