### ISSUE TITLE
Publish service prohibit find-replace

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12168]
发布服务没有阻止文本替换

**Comment by Csrayz** [comment]
还真是，使用全局搜索的替换功能即可替换掉文中内容。


<img width="1020" alt="image" src="https://github.com/user-attachments/assets/42873169-eec6-47af-bcc3-08d8fe6bc2f8">

**Comment by TCOTC** [comment]
除了阻止文本替换以外，这个替换的按钮也不应该出现

**Comment by 88250** [comment]
界面暂时不动了，内核接口上阻断。
