### ISSUE TITLE
编辑多选列单元格时偶尔会闪烁一下

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12163]
比如第 6 秒：单元格移除了 `1` ，然后又闪回了一下；第 12 秒：单元格移除了 `4` ，然后又闪回了一下

[视频.webm](https://github.com/user-attachments/assets/babe47f6-52cc-4461-aebb-ff4cd9512196)

**Comment by 88250** [comment]
按目前的机制是无法避免了。

**Comment by Temacc0531** [comment]
要不再想想🤨
