### ISSUE TITLE
列表块的第一个段落块块标点击没反应

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

第一个不行， 第二个可以

![image](assets/image-20240801204545-4nlal53.png)

### Expected result

。。

### Version environment

```markdown
- Version: 最新
- Operating System: win11
- Browser (if used):
```

### Log file

。。

**Comment by TCOTC** [comment]
你是不是用了 Savor 主题？

**Comment by Jiangshuon** [comment]
是的，主题的问题吗。。。我偷懒了，没验证

**Comment by TCOTC** [comment]
https://github.com/royc01/notion-theme/issues/288

**Comment by TCOTC** [comment]
切换回默认主题之后有没有重启思源？

**Comment by Jiangshuon** [comment]
不是同一个问题，我说的是列表中的**段落块**块标

![image](https://github.com/user-attachments/assets/6dc2625e-f25d-4e43-a8ea-84696f6a5f14)

**Comment by TCOTC** [comment]
怪了，我的能点开。你上传一下这个文档？

**Comment by Jiangshuon** [comment]
好的

**Comment by TCOTC** [comment]
不清楚这个问题与 https://github.com/royc01/notion-theme/issues/288 的问题是否相关，先附在这里：

![image](https://github.com/user-attachments/assets/42d98e45-f7ca-493a-b8cd-3f229f7d50ac)

https://github.com/siyuan-note/siyuan/blob/c6d2d629e8b3e86789f97836e80cbfd087d55846/app/src/protyle/gutter/index.ts#L435-L442

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
