### ISSUE TITLE
公众号剪藏代码块缺少语言信息

### ISSUE THREAD

**Issue by DearZack** [siyuan-note/siyuan#12160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复现地址：https://mp.weixin.qq.com/s/QmikshYOUdmSovU_GwvCZg

一般代码块会在```后面加语言信息，例如java，这样语法就会高亮
```java
//代码
```

我不知道是本来公众号就获取不到这个信息还是bug，麻烦确认一下。

- Version: v3.1.2
- Operating System: win11
- Browser (if used):chrome

### Expected result

- Version: v3.1.2
- Operating System: win11
- Browser (if used):chrome

### Screenshot or screen recording presentation

- Version: v3.1.2
- Operating System: win11
- Browser (if used):chrome

### Version environment

```markdown
- Version: v3.1.2
- Operating System: win11
- Browser (if used):chrome
```

### Log file

- Version: v3.1.2
- Operating System: win11
- Browser (if used):chrome

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/227409fe-4dc0-416d-b240-6223a5b217a8)

**Comment by 88250** [comment]
代码块里面没有语言信息，无法获取到的。
