### ISSUE TITLE
The asset creation time and update time are displayed in reverse order

### ISSUE THREAD

**Issue by jim555666888** [siyuan-note/siyuan#12170]
几个小bug反馈：本地文件属性错误；pdf文件用默认程序打开就得靠运气

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="460" alt="iShot_2024-08-02_09 20 14" src="https://github.com/user-attachments/assets/bc5e9c72-0a15-4aa9-968b-c9dcbbbf7ce8">
上面创建和更新的时间明明相反了吧，希望更正一下

<img width="826" alt="image" src="https://github.com/user-attachments/assets/45fc536a-8d1c-48b7-aa6f-db51155f2ced">
上图pdf文件为什么打开策略和其他文件不同？其他文件打开都是使用默认程序打开，唯独pdf是在思源中打开，这样体验不一致感是一种…嗯，比较低级的错误。如果pdf文件对思源有特别意义的话，也建议把pdf打开的方式单独做成一个选项，至少让用户可选吧。

现在用用默认程序打开pdf，在macos系统下，先按住shift再点击，不知道你们测试过没，这个100次中有1次能点开就不错了，我稍后拍个视频，希望你们能改进，最好是保持软件体验的一致性，不应该对个别文件类型做特殊处理，即便要特殊处理，也请留一个配置项。谢谢~~~

### Expected result

希望改进

### Version environment

```markdown
- Version: 3.1.2
- Operating System:macos 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
> 在macos系统下，先按住shift再点击，不知道你们测试过没

我们这里测试正常。

**Comment by jim555666888** [comment]
https://github.com/user-attachments/assets/700a8d96-0c08-4137-b11f-20f449887c96



这是关于pdf文件的打开方式，按住shift再点击，非常困难，基本这个功能不可用。我希望不管是pdf还是其他文件，它的打开策略的配置应该是一直的

**Comment by jim555666888** [comment]
关于pdf文件打开的配置选项的建议，以及不能使用shift+点击打开，我要不再提个问题单？

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/12171
