### ISSUE TITLE
pdf附件使用shift+点击无法用默认程序打开，建议pdf附件打开策略和其他文件类型保持一致

### ISSUE THREAD

**Issue by jim555666888** [siyuan-note/siyuan#12171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如视频操作所示，在macos系统下，只有极少数概率可以使用shift+点击使用默认程序打开，有时候是最开始的时候，有时候是中间的某次点击操作。更换不同主题以及默认主题均有此问题

### Expected result

希望pdf文件的默认打开方式有专门的配置选项，或者应该和其他文件保持一致。
此举应能保持软件体验的一致性。

同时，也希望能修正上述视频中演示的无法打开的情况，此情况在历史的所有版本中均存在问题

### Version environment

```markdown
- Version: 3.1.2以及历史所有版本均存在此问题
- Operating System: macos
- Browser (if used):
```

### Log file

无

**Comment by jim555666888** [comment]
https://github.com/user-attachments/assets/92bdee9c-2f9c-4922-9a24-304a307e294d

**Comment by jim555666888** [comment]
我大概知道bug原因了，是因为鼠标点击到块，这再shift+点击，应该和系统的选中操作有冲突（是系统性冲突），所以打不开，我尝试shift+点击其他文件类型，也有此问题。如果先把鼠标在块外点击，再做shift+点击的操作，大概率是正常的。但是一般用户可能很难弄懂和规避这个bug吧。。。。


所以最好的办法，应该是对pdf文件可配置默认打开方式，或者保留和其他类型的文件一样，直接点击就用默认程序打开。

**Comment by jim555666888** [comment]
在electron的渲染进程中，用的还是浏览器。其实在浏览器上，按 shift再点击，本身就会被识别为选中，比如你在这个页面上，随便在文字上按shift+点击，浏览器会识别为选中。最好能避免shift的组合操作，这个在技术上容易产生系统级的冲突，影响用户体验。

总之还是希望把pdf的打开策略和其他文件类型保持一样的配置，直接点击就能用默认程序打开

**Comment by 88250** [comment]
资源文件打开方式配置请关注 https://github.com/siyuan-note/siyuan/issues/10641

**Comment by jim555666888** [comment]
> 资源文件打开方式配置请关注 #10641

对，改成click+点击，应该可以规避浏览器shift+点击的系统级冲突。

但是我这个问题单主要是希望pdf文件也能配置为使用点击就能默认程序打开

**Comment by 88250** [comment]
10641 就是配置打开方式的，但是目前还没有明确计划。
