### ISSUE TITLE
wps和飞书表格内字符有下划线的情况下复制粘贴后有转义字符

### ISSUE THREAD

**Issue by maxiaogood** [siyuan-note/siyuan#12177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在wps表格或者飞书云文档上表格添加一个带下划线的单元格数据,负责到其他地方都是正常的,但复制到思源笔记的表格中后再复制到其他地方就会多一个\,详情见视频

### Expected result

希望从表格中复制的不带\

### Screenshot or screen recording presentation

[20240802_170416.zip](https://github.com/user-attachments/files/16468391/20240802_170416.zip)

### Version environment

```markdown
- Version: V3.1.2
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16468409/siyuan.log)

**Comment by TCOTC** [comment]
> 希望从表格中复制的不带\

可以为 `复制纯文本` 设置一个快捷键，然后选中文本使用快捷键

**Comment by 88250** [comment]
默认复制的是 Markdown 文本，所以 `_` 需要进行转义。

**Comment by maxiaogood** [comment]
> 默认复制的是 Markdown 文本，所以 需要进行转义。`_`

不是这个问题,是我从其他地方复制的带下划线的纯文本,比如txt,复制到思源笔记, 然后再从思源笔记负责就不会带\,但从wps表格或者飞书云文档负责的纯文本,复制到思源笔记,然后再从思源笔记复制就会带\

https://github.com/user-attachments/assets/46b7a90f-c947-4b92-9489-135d0ab423e7

**Comment by maxiaogood** [comment]
> > 希望从表格中复制的不带\
> 
> 可以为 设置一个快捷键，然后选中文本使用快捷键`复制纯文本`

麻烦看下我最新的回复

**Comment by TCOTC** [comment]
> 但从wps表格或者飞书云文档复制的带下划线的纯文本

我试了一下飞书，飞书应该是不能复制纯文本的（我没找到哪里可以复制纯文本），只会复制 HTML，所以粘贴到思源里会被转义

**Comment by maxiaogood** [comment]
> > 从wps表格或者飞书云文档复制的带下划线的纯文本
> 
> 我试了一下飞书，飞书应该是不能复制纯文本的（我没找到哪里可以复制纯文本），只会复制 HTML，所以粘贴到思源里会被转义

的确是html,但我试了下Obsidian和typora都没这个问题,还有wps表格单元格复制不知道是不是这个问题,这个可以优化一下吗

**Comment by maxiaogood** [comment]
@TCOTC

**Comment by TCOTC** [comment]
只能等 #11206 实现了
