### ISSUE TITLE
Markdown公式块识别异常

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#12178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Markdown导入及文本直接复制进笔记时，公式块识别异常
比如下面这句话
```
可通过某直线来近似某曲线在 $x_0$点及其附近的图像，该直线称为该曲线在 $x_0$点的 微分 ，或称为该曲线在 $x_0$点的 切线 ，如下图所示。
```

完整的markdown我打包成zip上传一下
[如何理解偏导数与全微分.md.zip](https://github.com/user-attachments/files/16469002/md.zip)

### Expected result

 $x_0$能正确识别为公式块

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/88459847-fd7b-4350-8f60-b6aee8618966)

### Version environment

```markdown
- Version: 3.1.2
- Operating System: Win10
- Browser (if used):Chrome 120
```

### Log file

[如何理解偏导数与全微分.md.zip](https://github.com/user-attachments/files/16469002/md.zip)

### More information

遇到好几次了，今天更新最新版发现还是有这个问题

**Comment by TCOTC** [comment]
你有没有打开公式语法？

![image](https://github.com/user-attachments/assets/4695843f-c835-46fa-b32e-d2d2acc4e5ea)

**Comment by ruin1990** [comment]
原来如此，谢谢，问题已解决了
