### ISSUE TITLE
支持将 PDF 默认打开方式修改为在当前编辑器打开

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12173]
https://ld246.com/article/1722562810035

**Comment by 88250** [comment]
这个不考虑了，PDF 页签和编辑器页签没有替代关系。

**Comment by TCOTC** [comment]
什么叫「替代关系」？

**Comment by 88250** [comment]
这是两种不同的页签，使用场景不同，所以 PDF 侧边打开更合理。

**Comment by TCOTC** [comment]
1. 文档页签和 PDF 页签都是页签，既然能放在一起，我觉得本质上没有不同。就像用浏览器打开 PDF 文件，页签也是放在一起的（虽然浏览器不能分屏）
2. 我觉得还是要满足用户需求，如果侧边打开了还要手动移回来，那显然还是直接在当前编辑器打开更合适。

**Comment by XeroChina** [comment]
分屏查看在大屏幕上确实方便，但办公中便携式笔记本屏幕小，左边显示目录，右边显示大纲，中间再一分屏查看，大多数情况下字就很小了。希望能够加一个整体选项，让用户可以禁用分屏。这样各取所需。我现在只能是打开pdf后，立刻取消分屏来查看。希望后面能给用户一个选择的权利，多谢多谢
![image](https://github.com/user-attachments/assets/4b33ef8d-acd0-46e7-90e4-30153a7704c3)
