### ISSUE TITLE
[文档] 快捷键章节补充

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12179]
1. 少了 `Ctrl+V` 粘贴
2. 还有一个操作：`Ctrl+C` 复制文件之后 `粘贴为纯文本`
3. 删除 `反向链接图标` 部分

![image](https://github.com/user-attachments/assets/04f24ef7-f7ea-4d5a-81ba-da77c2fdec38)

**Comment by TCOTC** [comment]
@88250 我有个疑问，这个 `反向链接图标` 的操作是在哪个地方？

![image](https://github.com/user-attachments/assets/f80d6dab-ea0a-4b09-8fc0-aa323ad39dba)

**Comment by 88250** [comment]
指的是反向面板上的操作

**Comment by TCOTC** [comment]
是指哪个图标？块标吗？

![image](https://github.com/user-attachments/assets/febac617-5681-473a-ba1d-f7cee7dac7bb)

**Comment by 88250** [comment]
是的，你按 Alt/Shift 然后往编辑器中拖一下看看。

**Comment by TCOTC** [comment]
试了一下，前面的 `块标` 部分说的才是对的，这个 `反向链接图标` 部分可以删掉了

![image](https://github.com/user-attachments/assets/3da8e32f-d2a9-4c74-b23b-b8e7de96d16c)

**Comment by 88250** [comment]
有道理，反链图标这部分文档是[编辑器式反链面板改造](https://github.com/siyuan-note/siyuan/issues/3565)之前就写的了，目前已经不需要，稍后移除。

**Comment by 88250** [comment]
这个改动就不拉进版本了。
