### ISSUE TITLE
在反链中点击，会导致列表项被断开

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12175]
这种情况下应该要新建一个列表项才对：

[视频.webm](https://github.com/user-attachments/assets/f625bcdd-eef0-46bc-ab88-1fd344d262b0)

**Comment by Vanessa219** [comment]
在底部点击会根据情况新建块，正文中也是如此。

**Comment by TCOTC** [comment]
但是这样的话列表的结构就出问题了

**Comment by Vanessa219** [comment]
那就点击了没反应？

**Comment by TCOTC** [comment]
能不能在这个列表项的最后一个直接子块下方再创建子块？

**Comment by Vanessa219** [comment]
除了返链，缩放也有类似的情况。好像点击了没反应也不好。

**Comment by TCOTC** [comment]
再创建一个列表项怎么样？

**Comment by Vanessa219** [comment]
好像也不太妥

**Comment by TCOTC** [comment]
@Vanessa219 这样呢

反链里的这个列表项：

- 如果是最后一个列表项，就创建段落块；
- 如果不是最后一个列表项，就创建新的列表项；

**Comment by Vanessa219** [comment]
缩放进去就不知道是不是最后一个了，需要发请求，这样太过于复杂了。

**Comment by TCOTC** [comment]
> 那就点击了没反应？

想了想还是这个比较合适，聚焦列表项的时候点击下方就是没反应的

**Comment by Vanessa219** [comment]
好像现在就是这样的。
