### ISSUE TITLE
Improve block update time filling

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12182]
很多块没有更新时间

## 在用 SQL 查询的时候发现了这个问题，有很多 列表(项)块、列表项中的段落块、列表项中的超级块、空段落块 没有更新时间，其中绝大部分是列表(项)块

![image](https://github.com/user-attachments/assets/7bedb8e2-d2a2-49e2-9e52-54de315dad15)

## 创建列表，刷新之后有的块有更新时间，有的块没有：

[视频.webm](https://github.com/user-attachments/assets/ace7fa96-fee9-4e6f-a730-46984444beca)

## 点击文档末尾新建空段落块：

[视频.webm](https://github.com/user-attachments/assets/ddf5c9cf-c9be-4f75-b3cb-d6cc506a32a5)

## 我觉得在索引的时候，如果一个块没有更新时间，就应该把创建时间填到更新时间里去

---

关联一下 https://ld246.com/article/1722587502176/comment/1722601401871#comments

**Comment by 88250** [comment]
看下 id 是不是很早以前的，如果是的话应该是以前的 bug 导致。

**Comment by TCOTC** [comment]
从很早以前到最近的都有

**Comment by 88250** [comment]
好的，我看到你上面补充的录屏了，等有空看看具体问题。

**Comment by TCOTC** [comment]
@88250 这一个判断好像用不上，updated = created 之后就不会 < created 了吧？

![image](https://github.com/user-attachments/assets/61a740e8-9b73-41e1-a4ae-af56f91b35fc)

**Comment by 88250** [comment]
言之有理，稍后改进。

**Comment by TCOTC** [comment]
@88250 现有的一大堆没有更新时间的块咋办？

![image](https://github.com/user-attachments/assets/a0c365b7-217f-4cf0-9bcc-c76f926c54b8)

**Comment by 88250** [comment]
后面打开文档后会自动更新。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Thu, Aug 8, 2024 21:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve block update time filling (Issue#12182)




 
@88250 现有的一大堆没有更新时间的块咋办？
 
image.png (view on web)

**Comment by TCOTC** [comment]
> 打开文档后会自动更新

@88250 我发现打开文档和刷新文档都不行，要修改一次没更新时间的块才有更新时间

**Comment by 88250** [comment]
哦哦，确实是的，需要修改一下内容。
