### ISSUE TITLE
custom.css 注释丢失

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1218]
### 描述问题 Describe the problem
资源笔记重启后，custom.css中的注释内容丢失。怀疑是程序自动重写该文件的时候，忽略了/* */之间的内容

### 期待的结果 Expected result
保留注释

### 版本环境 Version environment
0.6.6及以前版本都有这个问题

**Comment by 88250** [comment]
你好，注释部分目前没有做解析保留，稍后我们看下是否能改进，谢谢。

**Comment by 88250** [comment]
这部分有难度，暂时实现不了，我关闭了。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3597
