### ISSUE TITLE
Contributing issue

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#12184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

按照 https://github.com/siyuan-note/siyuan/blob/master/.github/CONTRIBUTING_zh_CN.md 使用 `git clone --depth=1 git@github.com:siyuan-note/siyuan.git` 拉取仓库，会看不到 `dev` 分支。

使用 `git fetch --unshallow` 解决不了这个问题。最后使用 `git clone git@github.com:siyuan-note/siyuan.git` 才能看到远端的 dev 分支。

### Expected result

-

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
主干要稳定些，需要 dev 分支的话可以单独拉取。

**Comment by Wetoria** [comment]
怪我没说清楚。

> - git clone --depth=1 git@github.com:siyuan-note/siyuan.git
> - 切换到 dev 分支 git checkout dev

如果仅仅按照贡献文档里这两个命令，是没办法切换到 dev 分支的。
这个 issue 主要是想描述贡献文档里的步骤不够具体。

**Comment by 88250** [comment]
懂了，稍后我把 `--depth=1` 去掉吧，感谢反馈。
