### ISSUE TITLE
导入密钥的输入框有问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12189]
#12183

[视频.webm](https://github.com/user-attachments/assets/c69919ca-dade-4bd3-9dd4-71e6a58ff7b3)

**Comment by 88250** [comment]
请不要重复提，一个问题的话下面跟帖即可，谢谢。

**Comment by TCOTC** [comment]
不同的问题开不同的 issue 嘛，既然 #12183 用来改进密钥导入了，这个 UI 问题就要新建 issue 了。

**Comment by 88250** [comment]
一并处理了
