### ISSUE TITLE
在唯一一个列表项块 `末尾插入块` 时，需要创建第二个列表项

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12180]
在有超过 1 个列表项块的时候，按快捷键在末尾插入块可以继续创建列表项：【正常】

![image](https://github.com/user-attachments/assets/c77d6aad-a2fb-4afc-9f7b-51bffa2ee74e)

在只有 1 个列表项块的时候，按快捷键在末尾插入块会在列表块后插入一个段落块：【异常】

![image](https://github.com/user-attachments/assets/fbce5068-95be-4156-96cd-73a208d516cb)

**Comment by 88250** [comment]
这个是设计如此，只有一个列表项的列表会直接按列表这一级创建下方块。

**Comment by TCOTC** [comment]
这个设计有什么使用场景？

**Comment by 88250** [comment]
方便在容器块单一路径嵌套时跳出创建顶层同级下方块，比如：

![image](https://github.com/user-attachments/assets/0f97073d-f2bf-4b41-a285-35f3771fdd79)

**Comment by TCOTC** [comment]
我觉得在列表里用 `末尾插入块` 要换个逻辑，现在的感觉有点怪：

[视频.webm](https://github.com/user-attachments/assets/00567acb-3620-453b-a4bb-9f2cd5111c5b)
