### ISSUE TITLE
Improve data repo key importing

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12183]
导入密钥的输入框有点问题

超出去了：

![image](https://github.com/user-attachments/assets/7f4cb248-1b4b-4635-8184-b9910d640b03)

**Comment by TCOTC** [comment]
另外我有个问题，这里支持输入什么？

![image](https://github.com/user-attachments/assets/0dd9d683-d510-4f1e-8e45-3a19d971655a)

**Comment by 88250** [comment]
首尾空白会被剔除

**Comment by TCOTC** [comment]
看起来没剔成功啊：

[视频.webm](https://github.com/user-attachments/assets/81c11ced-9430-49d2-958e-4fb2121a23f6)

**Comment by 88250** [comment]
输入框超出去的问题我这里无法重现，先改后面这个问题。

**Comment by TCOTC** [comment]
#12189

**Comment by 88250** [comment]
@Vanessa219 看一下界面的问题 
[视频.webm](https://github.com/user-attachments/assets/c69919ca-dade-4bd3-9dd4-71e6a58ff7b3)

**Comment by TCOTC** [comment]
@88250 还有这里不需要拼写检查：

![image](https://github.com/user-attachments/assets/2d376951-ea24-46d4-a282-ac196252a2bb)

**Comment by 88250** [comment]
收到，稍后改进。

**Comment by TCOTC** [comment]
@88250 这里还是有点问题，拖动浮窗边框的话输入框就不能同时变化高度了：

[视频.webm](https://github.com/user-attachments/assets/e6ee7e41-635c-4459-a0c7-a8bb6ec00e16)

---

AI Chat 也有同样的问题：

https://github.com/siyuan-note/siyuan/blob/0ea759953e998e0de3eb047d4c3df0ecba380a26/app/src/ai/chat.ts#L7-L15

[视频.webm](https://github.com/user-attachments/assets/967e199b-2b51-4418-a4a5-9e1b72e2eca8)

**Comment by 88250** [comment]
@Vanessa219 有空看看。
