### ISSUE TITLE
无法替换被转义的符号

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12195]
比如 `信源订阅 \=\> 略读 \=\> 稍后阅读 \=\> 原文阅读`

搜索 `=>` 可以搜索到文本，但无法替换文本；搜索 `\=\>` 无法搜索到文本

**Comment by 88250** [comment]
只能单独一个字符一个字符替换了：

搜索 `=` 替换 xxx，再搜索 `>` 替换 xxx

**Comment by shuojie819** [comment]
这个真是个巨大的缺陷，`=>` 是一个整体，但是分开后就不唯一了…………

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/15256 中解决。
