### ISSUE TITLE
按 `Shift+Enter` 时，行内元素和段落元素保持一致

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12199]
https://github.com/siyuan-note/siyuan/issues/11766#issuecomment-2181077781 ~ https://github.com/siyuan-note/siyuan/issues/11766#issuecomment-2186049766

目前的情况：

- 在 `1111111111\n1111111111` 中间可以按 `Shift+Enter` 换行新建段落块
- 在 `2222222**222\n222**2222222` 中间按 `Shift+Enter` 无法换行新建段落块

![image](https://github.com/siyuan-note/siyuan/assets/78434827/f2ddbba9-3877-42f9-b7eb-ea3d5d70da7e)

需求：

- 在 `2222222**222\n222**2222222` 中间按 `Shift+Enter` 能够换行新建段落块

**Comment by 88250** [comment]
这个不考虑了，行级元素中再分块会引入其他解析问题。
