### ISSUE TITLE
复制列表的 Markdown 缺少空行

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12192]
222222 和 33333 之间需要一个空行：

![image](https://github.com/user-attachments/assets/e8554396-0dda-41c6-b4ab-8259f1a25941)

**Comment by 88250** [comment]
不需要的，Markdown 松散列表模式只需要一个空行 https://spec.commonmark.org/0.31.2/#loose

**Comment by TCOTC** [comment]
规范是最少要一个空行，但两个空行也不影响。

主要问题是 222222 是 11111 的子列表，但却离 33333 更近，用起来很难受

**Comment by 88250** [comment]
适应下吧。

**Comment by TCOTC** [comment]
@88250 静态站点生成器 [MkDocs](https://github.com/mkdocs/mkdocs) 不兼容思源的列表

关联 https://ld246.com/article/1722761264931

![image](https://github.com/user-attachments/assets/f6a85e13-d7bf-49df-a788-2c0491e8fe78)

**Comment by 88250** [comment]
这个不是思源的问题哦



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月4日(周日) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 复制与导出列表的 Markdown ，需要在子块末尾补充一个空行 (Issue #12192)




 
@88250 静态站点生成器 MkDocs 不兼容思源的列表
 
关联 https://ld246.com/article/1722761264931
 
image.png (view on web)

**Comment by TCOTC** [comment]
我有个疑问，为什么会采用在父列表后面加一行的方式作为松散列表，而不是前后各加一行？

```
* 11111

  * 22222
  * 33333
  * 44444
* 55555
```

```
* 11111

  * 22222
  * 33333
  * 44444

* 55555
```

**Comment by 88250** [comment]
实现太复杂。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月4日(周日) 下午5:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 复制与导出列表的 Markdown ，需要在最后一个子块末尾补充一个空行 (Issue #12192)




 
我有个疑问，为什么会采用在父列表后面加一行的方式作为松散列表，而不是前后各加一行？
 * 11111   * 22222   * 33333   * 44444 * 55555  * 11111   * 22222   * 33333   * 44444 * 55555

**Comment by TCOTC** [comment]
- https://ld246.com/article/1760518296368
- ![Image](https://github.com/user-attachments/assets/00c29695-f6d2-4472-8b60-863b41484013)
