### ISSUE TITLE
Hyperlink elements support copying in multiple formats

### ISSUE THREAD

**Issue by yyangdid** [siyuan-note/siyuan#12198]
请求在超链接上右键增加复制链接菜单

### In what scenarios do you need this feature?

现在在超链接上使用右键复制得到的是 markdown 格式的链接，希望能增加一个复制纯链接的菜单。

![Snipaste_2024-08-04_23-26-06](https://github.com/user-attachments/assets/7f7fe31f-0920-4928-b28f-3e97d442c2d7)

### Describe the optimal solution

希望能考虑添加这个小功能，对于使用几十个不同独立浏览器的人真的很重要🙏🙏🙏

**Comment by TCOTC** [comment]
确实在我需要复制链接的时候也会觉得有点麻烦。

我提议在输入框的后面各增加一个复制按钮：

![image](https://github.com/user-attachments/assets/de634f96-a51c-4de5-9527-16429226f9df)

p.s. 不只是链接的菜单，各个右键菜单都可以改一改

**Comment by Hzz-0802** [comment]
网络图片有可能也加个复制纯链接吗

**Comment by 88250** [comment]
@Hzz-0802 嗯，图片元素都会加上的。
