### ISSUE TITLE
Alt Tab 切换窗口后会触发折叠

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1219]
### 描述问题 Describe the problem
点击代码块有时会折叠代码块，无法进入编辑状态

### 期待的结果 Expected result
单击进入编辑状态

### 截屏或录屏演示 Screenshot or screen recording presentation
![20210122_100328](https://user-images.githubusercontent.com/657850/105438207-7eafbf80-5c9d-11eb-919c-61eb31a9de1e.gif)

### 版本环境 Version environment
066

**Comment by 88250** [comment]
你好，这个问题可能不只是发生在特定类型块上，我们这边也注意到了，可能是因为 Alt Tab 切换窗口的时候按键粘滞判断有问题，后面会继续跟进，谢谢。

**Comment by deerainw** [comment]
> 可能是因为 Alt Tab 切换窗口的时候按键粘滞判断有问题

专门试了一下，跟 alt+tab 无关，我纯用鼠标切换程序也出现了这个现象

**Comment by deerainw** [comment]
上面是我弄错了，就是 alt+tab 的锅，但主要是切出思源的那一下 alt+tab 导致，切回思源的时候无论是 alt+tab 还是鼠标都不影响
