### ISSUE TITLE
移动端设置访问授权码后，启动应用时能直接进入，不需要输入访问授权码

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12193]
- https://ld246.com/article/1710832234231 （在这个时候我也遇到了该问题，但现在复现不了）
- https://ld246.com/article/1720442820058
- https://ld246.com/article/1722743938347 （在升级思源之后才要求输入访问授权码）

**Comment by 88250** [comment]
授权码的意义就是需要授权才能进入。

**Comment by TCOTC** [comment]
问题在于现在启动应用时能直接进入，不需要输入访问授权码

**Comment by 88250** [comment]
我这里测试设置授权码后需要输入授权码才能进入的。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月4日(周日) 下午3:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 移动端设置访问授权码后，启动应用时能直接进入，不需要输入访问授权码 (Issue #12193)




 
问题在于现在启动应用时能直接进入，不需要输入访问授权码

**Comment by TCOTC** [comment]
我这里也是，但有的用户就是没有那个页面

**Comment by shuojie819** [comment]
+ 1
最近我也遇到一次，第二次就没有了（不知道怎么触发的……

**Comment by TCOTC** [comment]
@88250 我建议把 issue 先开着
