### ISSUE TITLE
异常的 DOM

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12196]
如果保存布局时 DOM 有问题，使用这个布局的时候也会恢复这个问题：（关闭所有页签再打开文档就能恢复正常）

工作空间：[布局问题.zip](https://github.com/user-attachments/files/16487310/BUG.zip)

[视频.webm](https://github.com/user-attachments/assets/7aa8db43-0027-49d4-931b-a29d25fed80f)

### Other information

用得太久了，也不知道是什么时候把 DOM 搞成这样的

**Comment by Vanessa219** [comment]
保存为什么，最终就会还原为什么。尝试了一下，

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
