### ISSUE TITLE
删除绑定块导致数据库异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12191]
1. 正常情况是删除块的同时会从数据库中移除，但像下面视频这样操作之后会留下几个条目，刷新文档才移除
2. 最开始的绑定块的右上角的数据库标识没了（此时如果导出该文档再导入，会发现数据库没有绑定块了）
3. 再次复制为副本，副本块不会再绑定到数据库中

[视频.webm](https://github.com/user-attachments/assets/7bb187c8-9339-4b5c-a3e6-e6dfd92ae9a1)

**Comment by 88250** [comment]
感谢反馈，合并到 https://github.com/siyuan-note/siyuan/issues/12140 中处理。
