### ISSUE TITLE
多选列表项，按 `(Shift+)Tab` 之后不应该取消选中

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12209]
多选列表项，列表的缩进不能连续调整，需要不断地选中：

[视频.webm](https://github.com/user-attachments/assets/318fbb58-2fc4-4ba6-afec-0178fefa802d)

如果只选中了一个列表项的所有子块，就是正常的：

[视频.webm](https://github.com/user-attachments/assets/71f7096d-9aa4-46a1-8468-3d8ed6153bb9)

**Comment by 88250** [comment]
图二现在不支持了，要扩选到列表项这一级，操作以后都是取消选中，但是实际上是可以继续 Tab/Shift+Tab 的。

**Comment by TCOTC** [comment]
比如我想把 3 4 5 都移到第一层，目前只能按一次选一次再继续按：

[video.webm](https://github.com/user-attachments/assets/22d67297-4667-4c65-8023-aa85afe2e922)

**Comment by 88250** [comment]
@Vanessa219

**Comment by Wetoria** [comment]
选择列表项的所有子元素时，可以考虑缩进列表项。

下面这种选择的情况，不能通过 `Tab` 进行缩进。
<img width="373" alt="image" src="https://github.com/user-attachments/assets/9a99a975-1984-4b60-8d66-c19aedbc3e51" />

目前只能这种的可以缩进。
<img width="326" alt="image" src="https://github.com/user-attachments/assets/53c240b2-9a6b-4e24-9f85-b6291a537222" />

应该是代码里只判断了选中的块是不是都是列表项吧？是不是可以向上找一次共同父级是不是列表项？
