### ISSUE TITLE
后端API的QPS有上限么

### ISSUE THREAD

**Issue by M2uyo** [siyuan-note/siyuan#12201]
### In what scenarios do you need this feature?

我尝试批量请求 api/block/getBlockKramdown 
同时请求大概在80-90个的时候 会卡死  
当我停止程序之后 会恢复正常
请问这个是 思源后端程序的限制么?

#### 统计方法
1. 设定一个计数器, 请求前+1, 请求后 -1
2. 查看卡死前的 计数器的最大值
3. 大概在 80-90  真实可能在100左右?

**Comment by 88250** [comment]
有的，请参考 https://github.com/siyuan-note/siyuan/issues/9939

**Comment by M2uyo** [comment]
> 有的，请参考 #9939

看起来不一样哦, 他的那个是执行失败, 我这个是执行阻塞. 当请求取消后 阻塞就会被撤销掉

**Comment by M2uyo** [comment]
> get* 好像没有限制并发数，如果请求没有响应的话可能就是到达设备的处理极限了。

感觉性能上并没有限制, CPU/内存的占用很低

**Comment by 88250** [comment]
估计需要设置 go pprof 调试看看
