### ISSUE TITLE
pc端锁定之后能不能自动最小化

### ISSUE THREAD

**Issue by iowong** [siyuan-note/siyuan#12202]
### In what scenarios do you need this feature?

锁定时候

### Describe the optimal solution

锁定时候自动最小化或者按esc最小化  当要用到锁定基本就是人要离开了  
每次锁定还留个锁定的界面在屏幕上 再去右下角掉一下图标

**Comment by 88250** [comment]
可以考虑使用 Alt+N 锁定然后 Alt+M 最小化。
