### ISSUE TITLE
Wrong parsing virtual reference with `\` before it

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12206]
如果虚拟引用前有转义符号，标签会被写入

https://ld246.com/article/1722933360950

[视频.webm](https://github.com/user-attachments/assets/15a116da-78a8-4cf3-96f1-dd27e0784939)

**Comment by 88250** [comment]
这个是正常情况，因为转义符把 HTML 标签转义了。

**Comment by TCOTC** [comment]
但对使用虚拟引用的用户来说不是正常情况

**Comment by TCOTC** [comment]
我感觉还是有点不一样，转义 HTML 标签应该是上面这种，但现在是下面这种：

![image](https://github.com/user-attachments/assets/cef500f4-defc-411f-afd4-830fb35691e8)

**Comment by 88250** [comment]
\\ 转义了 \ 本身，后面一个 \ 转义 <

**Comment by TCOTC** [comment]
那这三个 `\` 是从哪里来的？

**Comment by 88250** [comment]
看上去可能是 Windows 的盘符路径

**Comment by TCOTC** [comment]
但我只打了一个 `\` ，按理说不应该会变成三个

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/7821 中加入了转义，后面 https://github.com/siyuan-note/siyuan/issues/9790 又重复转义了一次导致的问题，删掉 7821 修复。
