### ISSUE TITLE
聚焦时，有序列表的序号需要支持刷新

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12218]
https://ld246.com/article/1723175540448

[视频.webm](https://github.com/user-attachments/assets/080ebe5e-43f0-4661-abad-e677034256ba)

**Comment by Vanessa219** [comment]
如下聚焦 2 后反向缩紧 22 前端无法处理。因为界面上没有3 ，无法把 3 更新为 4。因此此类情况就没有进行处理。

![QQ_1723772013101](https://github.com/user-attachments/assets/3fee22aa-30ff-47e3-9be6-a71a87e07555)

**Comment by TCOTC** [comment]
能否实现让内核处理序号刷新？

**Comment by 88250** [comment]
应该是能的，后面考虑。

**Comment by 88250** [comment]
统一内核处理的话估计太慢了，后面暂时靠刷新编号顶顶吧 https://github.com/siyuan-note/siyuan/issues/11990

**Comment by TCOTC** [comment]
这样行不行：只在聚焦状态时才由内核处理 聚焦时顶层的列表项 所在的列表块
