### ISSUE TITLE
改进在代码块中使用 `Ctrl+Shift+Home/End`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12216]
在代码块中,

- [x] ~无法使用 `Ctrl+Home` 跳转到代码开头~ 用 `Ctrl+A` + `←` 代替
- [x] ~无法使用 `Ctrl+End` 跳转到代码末尾~ 用 `Ctrl+A` + `→` 代替
- [ ] 无法使用 `Ctrl+Shift+Home` 选中到代码开头
- [ ] 无法使用 `Ctrl+Shift+End` 选中到代码末尾

**Comment by 88250** [comment]
我试了下 Ctrl+Shift+Home/End 目前是针对编辑器整体的，代码块这部分暂时就不考虑了。
