### ISSUE TITLE
为啥老是升级降级 Electron版本。有这精力好好弄note本身不好吗？

### ISSUE THREAD

**Issue by clfsoft** [siyuan-note/siyuan#12214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

为啥老是升级降级 Electron版本。有这精力好好弄note本身不好吗？

### Expected result

固定一个版本，等Electron稳定后再升级啊。

### Version environment

```markdown
- Version: all
- Operating System: windows1022h2 
- Browser (if used):
```

### Log file

no

**Comment by 88250** [comment]
没有办法，我们更新的已经是 Electron 稳定版（并且一般是大版本之前的一个版本），但是还是会遇到一些未知问题。

**Comment by 88250** [comment]
另外，主程序本身也在不断完善，谢谢。

**Comment by clfsoft** [comment]
好吧。
