### ISSUE TITLE
`Copy Headings and Bottom Blocks` does not work properly on Android

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12211]
`复制标题及下方块` 得到的是 HTML 而不是 Markdown，并且在移动端无法正常粘贴

- [ ] 无法通过 `复制标题及下方块` 得到 Markdown
- [ ] 在移动端 `复制标题及下方块` 后无法正常粘贴

https://ld246.com/article/1723024006808

![Screenshot_2024-08-07-18-03-04-51_ed1bdeca7a858bb430bfb9c256856672.jpg](https://github.com/user-attachments/assets/6603f88b-0f9d-4bad-9178-8a7002965351)

**Comment by Vanessa219** [comment]
浏览器端无法设置剪切板中的多种 data，@88250 看一下 go 是否能设置剪切板中的 `text/plain` 和 `text/html` 数据

**Comment by 88250** [comment]
Android 端新增一个接口用于设置 HTML 剪切板。

**Comment by 88250** [comment]
> 无法通过 复制标题及下方块 得到 Markdown

这个目前实现不了，剪切板中只能统一写入 HTML。后面看需求吧，如果需要 带下方块复制 Markdown 的需求较多再考虑，另外，这个也能通过插件实现，把 `/api/block/getHeadingChildrenDOM` 返回的 HTML 转换 Markdown 即可。

**Comment by 88250** [comment]
上面回复的方案有点问题，已经改为复制为标准 Markdown 了。

**Comment by TCOTC** [comment]
@88250 我这里复制之后粘贴出来的还是 HTML

**Comment by 88250** [comment]
你编译移动端测试的吗？

**Comment by TCOTC** [comment]
我用的是桌面端

**Comment by TCOTC** [comment]
关联 #12227
