### ISSUE TITLE
Add "Remember Me" checkbox to sign in page

### ISSUE THREAD

**Issue by K33k0** [siyuan-note/siyuan#12219]
### In what scenarios do you need this feature?

Logging into the self hosted version using the browser or PWA. PWA is worse as I have to enter the auth code every time i open it

### Describe the optimal solution

Add a remember me checkbox to the auth code entry screen. This means you could stay logged in for x amount of time.

**Comment by 88250** [comment]
The access authorization code needs to be entered every time you log in, which is similar to the password when logging into the operating system, so we do not consider adding a remember function, thank you.

**Comment by tomershvueli** [comment]
@88250 I've also come across this limitation - would you accept a PR that would add a 'Remember me for 30 days' checkbox on the login page?

**Comment by 88250** [comment]
@tomershvueli PRs welcome

**Comment by tomershvueli** [comment]
@88250 just opened up [a PR here](https://github.com/siyuan-note/siyuan/pull/14964)! Open to notes - thanks!

**Comment by 88250** [comment]
@tomershvueli We will follow up in PR, thanks.
