### ISSUE TITLE
SQL 搜索时指定路径无效

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12215]
指定了路径之后搜索结果没变

**Comment by 88250** [comment]
我这里测试正常

![image](https://github.com/user-attachments/assets/74f2eb84-70cc-46e4-ba60-4c0041ce011e)


指定 hpath：

![image](https://github.com/user-attachments/assets/634328b8-cff1-41f7-a811-1606a2d58343)

**Comment by TCOTC** [comment]
我说的是上面这个指定路径功能：

![image](https://github.com/user-attachments/assets/be1fac55-7912-4510-aac4-95604c15b225)

**Comment by 88250** [comment]
这个是这样的，不会拼接其他条件的，条件要写在 SQL 里。
