### ISSUE TITLE
剪藏功能推荐

### ISSUE THREAD

**Issue by nightlye** [siyuan-note/siyuan#1221]
可以联动简悦或者Web Clipper增加剪藏功能。首推web clipper，实践之后感觉这个比简悦好一些。并且可以绑定的账户还更多。
[web clipper插件](https://chrome.google.com/webstore/detail/web-clipper/mhfbofiokmppgdliakminbgdgcmbhbac?hl=zh-CN)

**Comment by 88250** [comment]
谢谢，但这个功能估计是需要插件来支持思源，而不是思源去支持插件……

**Comment by deerainw** [comment]
web-clipper 扩展的作者来了 #1266
