### ISSUE TITLE
After the image is set to center, the width cannot be adjusted through the menu

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12217]
图片设置为居中后无法通过菜单调整宽度

https://ld246.com/article/1722926260242
https://ld246.com/article/1724383269807
https://ld246.com/article/1725331872422

[视频.webm](https://github.com/user-attachments/assets/54edb119-37e0-4448-b330-4bb587b07fa9)

**Comment by TCOTC** [comment]
两个问题：

1. 菜单按钮没有及时移动
2. 光标没有直接靠在图片后面

[视频.webm](https://github.com/user-attachments/assets/d1a4fb57-ec3d-47d0-b4c9-73c47b9971b2)

**Comment by 88250** [comment]
@Vanessa219 抽空看看

**Comment by Vanessa219** [comment]
1. 已处理。由于限制，把 % 改为 vw
2. 居中的话需要把外层撑满，然后设置图片居中，因此光标只能在外层。如果想要在图片旁白的话可以选择图片所在的块居中。
