### ISSUE TITLE
[request] 大佬help，希望能增强表格单元格的填充

### ISSUE THREAD

**Issue by code-lixm** [siyuan-note/siyuan#12225]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/b03ced87-771b-4d9c-9d6a-872001bf2be3)

### Describe the optimal solution

confluence中的表格填充

### Describe the candidate solution

希望可以添加一个填充按钮

**Comment by TCOTC** [comment]
可以提到 #4785

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/4785
