### ISSUE TITLE
请问 数据库-视图 能增加分组功能吗

### ISSUE THREAD

**Issue by holduan** [siyuan-note/siyuan#12222]
### In what scenarios do you need this feature?

数据库视图比较多时，都在同一级的，用展开按钮翻找也不够便捷

### Describe the optimal solution

增加视图分组功能

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10964

**Comment by TCOTC** [comment]
@88250 这个需求是视图分组，不是条目分组

**Comment by 88250** [comment]
哦，视图分组的话没有计划，可以关注 https://github.com/siyuan-note/siyuan/issues/11020
