### ISSUE TITLE
导入markdown时支持思源原有表格语法

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#12223]
### In what scenarios do you need this feature?

https://ld246.com/article/1722755614345/comment/1722755839104#comments
我自己写了脚本将HTML表格转成思源表格，但是导入md后仍然是标准表格
粘贴又没问题，但是一旦字数在10w以上时，思源往往要20min+才能保存，期间无法操作，非常影响体验，我看所有样式都处理完了，但是.sy文件一直是1kb，是否可以改进？

### Describe the optimal solution

1.导入markdown时支持思源原有表格语法
2.或者改进粘贴保存速度

### Describe the candidate solution

[test.md](https://github.com/user-attachments/files/16568375/test.md)
这是50w字的md，可以测试一下

**Comment by AvoidantPerDis** [comment]
表格转换效果如下
<table><tr><td colspan="4">概念: 两个以上合伙人为了共同的事业目的, 订立的共享利益、共担风险的合同</td></tr><tr><td rowspan="11">合伙合同</td><td></td><td>目的的共同性</td><td></td></tr><tr><td></td><td>订立的特殊性</td><td></td></tr><tr><td>特点</td><td>内容的特殊性</td><td></td></tr><tr><td></td><td>继续性合同</td><td></td></tr><tr><td></td><td>以不要式为原则</td><td></td></tr><tr><td></td><td></td><td>典型合同</td></tr><tr><td></td><td>性质和功能</td><td>共同行为</td></tr><tr><td></td><td></td><td>具有规范合伙组织体的功能</td></tr><tr><td>类型</td><td></td><td>民事合伙和商事合伙 持续合伙和偶然合伙 定期合伙和不定期合伙</td></tr><tr><td rowspan="2">效力</td><td>内部关系</td><td>出资的方式符合法律规定 合伙人负有出资义务 出资数额符合法律规定与协议约定 出资时间符合法律规定和协议约定 依照法律规定和合伙合同的约定确定合伙财产的归属 合伙人不得擅自向合伙人以外的第三人转让合伙份额 依照法律规定和合伙合同的约定承担合伙债务 依照法律规定和合伙合同的约定分配损益 合伙人共同执行合伙事务 依照法律规定和合伙合同的约定执行合伙事务 合伙事务执行人的确定 合伙事务执行人的报酬</td></tr><tr><td>外部关系</td><td>合伙人与第三人发生法律关系的效果归属 合伙人原则上对外承担无限连带责任 合伙人的债权人不得代位行使合伙人的合伙权利</td></tr><tr><td rowspan="7"></td><td rowspan="7">终止</td><td></td><td>合伙期限届满，合伙人决定不再经营</td></tr><tr><td></td><td>不定期合伙任意解除</td></tr><tr><td></td><td>合伙人约定解散事由的出现</td></tr><tr><td></td><td>合伙人的目的已经实现或无法实现</td></tr><tr><td></td><td>全体合伙人决定解散</td></tr><tr><td></td><td>合伙人死亡、丧失民事行为能力或终止</td></tr><tr><td></td><td>法律、行政法规规定的解散合伙的其他原因</td></tr></table>


| {: colspan='4' rowspan='1'}概念: 两个以上合伙人为了共同的事业目的, 订立的共享利益、共担风险的合同 | {: class='fn__none'} | {: class='fn__none'} | {: class='fn__none'} |
| {: colspan='1' rowspan='11'}合伙合同 |  | 目的的共同性 |  |
| {: class='fn__none'} |  | 订立的特殊性 |  |
| {: class='fn__none'} | 特点 | 内容的特殊性 |  |
| {: class='fn__none'} |  | 继续性合同 |  |
| {: class='fn__none'} |  | 以不要式为原则 |  |
| {: class='fn__none'} |  |  | 典型合同 |
| {: class='fn__none'} |  | 性质和功能 | 共同行为 |
| {: class='fn__none'} |  |  | 具有规范合伙组织体的功能 |
| {: class='fn__none'} | 类型 |  | 民事合伙和商事合伙持续合伙和偶然合伙定期合伙和不定期合伙 |
| {: class='fn__none'} | {: colspan='1' rowspan='2'}效力 | 内部关系 | 出资的方式符合法律规定合伙人负有出资义务出资数额符合法律规定与协议约定出资时间符合法律规定和协议约定依照法律规定和合伙合同的约定确定合伙财产的归属合伙人不得擅自向合伙人以外的第三人转让合伙份额依照法律规定和合伙合同的约定承担合伙债务依照法律规定和合伙合同的约定分配损益合伙人共同执行合伙事务依照法律规定和合伙合同的约定执行合伙事务合伙事务执行人的确定合伙事务执行人的报酬 |
| {: class='fn__none'} | {: class='fn__none'} | 外部关系 | 合伙人与第三人发生法律关系的效果归属合伙人原则上对外承担无限连带责任合伙人的债权人不得代位行使合伙人的合伙权利 |
| {: colspan='1' rowspan='7'} | {: colspan='1' rowspan='7'}终止 |  | 合伙期限届满，合伙人决定不再经营 |
| {: class='fn__none'} | {: class='fn__none'} |  | 不定期合伙任意解除 |
| {: class='fn__none'} | {: class='fn__none'} |  | 合伙人约定解散事由的出现 |
| {: class='fn__none'} | {: class='fn__none'} |  | 合伙人的目的已经实现或无法实现 |
| {: class='fn__none'} | {: class='fn__none'} |  | 全体合伙人决定解散 |
| {: class='fn__none'} | {: class='fn__none'} |  | 合伙人死亡、丧失民事行为能力或终止 |
| {: class='fn__none'} | {: class='fn__none'} |  | 法律、行政法规规定的解散合伙的其他原因 |

我测试是没问题的，思源能识别

**Comment by 88250** [comment]
抱歉，导入仅支持标准 Markdown；复制粘贴的话大量数据没有办法改进了，只能用导入。
