### ISSUE TITLE
改进剪藏、粘贴

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12237]
### 01 剪藏：https://ld246.com/article/1723388814745

- [ ] 有些内容是应该在列表内的：

   ![image](https://github.com/user-attachments/assets/6c999138-bd39-4542-ab42-ec08a1ac28a7)

- [ ] kbd 元素没有正确剪藏：

   ![image](https://github.com/user-attachments/assets/16777fb1-d1ed-4390-bd1a-bd05d0c45614)

- [ ] 代码块末尾都有多余的换行和零宽空格：

   ![image](https://github.com/user-attachments/assets/65a71c4f-ad5e-4eee-8d81-8d7e87847547)

---

### 02 复制 Markdown 粘贴：https://ld246.com/article/raw/1723388814745

- [ ] 这部分粘贴出来感觉很怪：

   ![image](https://github.com/user-attachments/assets/4ae0fe8f-3875-40ec-b0e6-0e82b0b1c303)

**Comment by 88250** [comment]
* 链滴的剪藏不适配了 https://github.com/siyuan-note/siyuan/issues/10987
* 不支持脚注部分解析

**Comment by TCOTC** [comment]
没道理不能适配啊

01 这个子元素剪藏之后应该在列表里的：

![image](https://github.com/user-attachments/assets/d56d0da2-235e-4c52-ad3a-271958eb8166)

02 kbd 元素的剪藏也应该是能改进的：

![image](https://github.com/user-attachments/assets/cbc24c4e-8f6a-46c9-9a00-5bb119f594a9)

03 这个 code 元素里面明明没有零宽空格是怎么剪藏出来的：

![image](https://github.com/user-attachments/assets/0e134e1c-87b3-4982-9085-a4527b8d53f4)

04 还有这个代码块粘贴之后会变成行级代码：

```
# 标题

    ```shell
    这里是个代码块
    ```
```

**Comment by 88250** [comment]
> 没道理不能适配啊

没有必要，因为链滴已经提供了 Markdown 文本了。

**Comment by TCOTC** [comment]
如果链滴遇到这些问题，那其他网页也是一样的，问题不只是链滴有，还是要改进才行

https://cs50.harvard.edu/x/2024/notes/1/

![image](https://github.com/user-attachments/assets/4a8e505e-3e4d-4744-961f-0b6800400892)

![image](https://github.com/user-attachments/assets/78cce883-6574-4e9b-b09d-9fb7b62195f0)

**Comment by 88250** [comment]
* 列表的问题可以重现
* 复制 Markdown 纯文本后粘贴

**Comment by TCOTC** [comment]
那 kbd 元素的剪藏呢？

**Comment by TCOTC** [comment]
还有这种代码块粘贴之后会变成行级代码也没法解决：

```
# 标题

    ```shell
    这里是个代码块
    ```
```

**Comment by 88250** [comment]
kbd 的问题单独提 issue 吧

**Comment by TCOTC** [comment]
代码块 Markdown 的问题能解决吗？

**Comment by 88250** [comment]
思源不支持缩进风格的代码块，所以会将缩进风格的代码块转换为行级代码。
