### ISSUE TITLE
某种情况下光标不能移动到图片前，无法删除软换行

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12238]
正常情况下光标可以在图片前：

[视频.webm](https://github.com/user-attachments/assets/9ade6127-8e53-456d-8266-bc090eab51a9)

但像这样操作之后就会产生问题，无论怎样块里面都有一个软换行：

[视频.webm](https://github.com/user-attachments/assets/b824dcb9-78b3-45f1-af75-74ea61f63592)

p.s. 或许与 #11968 有点关联

**Comment by Misuzu2027** [comment]
补充一个图片编辑问题，粘贴图片后，在段落中其他位置按 `Delete`  键，会删除刚刚插入的图片。

https://github.com/user-attachments/assets/65b3fd48-50a2-4f26-83b7-069683618507

**Comment by TCOTC** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/11868#issuecomment-2207697375

**Comment by Vanessa219** [comment]
这两个目前都无法重现，我现关闭了，可以重现的话再进行修复。

**Comment by TCOTC** [comment]
软换行的问题确认已经被解决了
