### ISSUE TITLE
客户端无法加载需要挂代理的外链图片，而网页端可以

### ISSUE THREAD

**Issue by YotsubaAina** [siyuan-note/siyuan#1223]
### 描述问题 Describe the problem

在已挂代理的情况下，思源客户端无法加载来自需要挂代理的图床（例如imgur）的图片，而网页端可以加载。
测试图片地址：https://i.imgur.com/lPPc9Jp.png
#### 图为在客户端下无法加载来自imgur的图片
![](https://i.loli.net/2021/01/22/FzrUxmA4WQnsZLM.png)

#### 图为在网页端和typora下，可以加载图片
![](https://i.loli.net/2021/01/22/UJpMG3tmuEw9Rdk.png)

![](https://i.loli.net/2021/01/22/2ebvgrzJ63C1xVD.png)

同时我也用着 sm.ms 图床，测试图片地址：https://i.loli.net/2021/01/22/oQTLj39xcIZuKVO.png
但是在思源客户端里的加载速度跟没挂代理时一样，比较慢
### 期待的结果 Expected result

可能是客户端没有通过系统代理
希望客户端可以像网页端一样能通过系统代理来加载外链图片

### 版本环境 Version environment

* 版本 Version：SiYuan 0.6.6
* 操作系统 Operating system：Win10 LTSC 
* 浏览器（如果使用）Browser (if used)：Chrome 88.0.4324.96

**Comment by 88250** [comment]
谢谢反馈，请关注 #1009
