### ISSUE TITLE
颜色选择, 清除样式图标替代文字

### ISSUE THREAD

**Issue by M2uyo** [siyuan-note/siyuan#12248]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/658296ea-edc6-4270-addb-3c8cc07cdbf2)
文字占的空间相当于两个图标了
如果用图标可以多看到一个最近的使用操作

### Describe the optimal solution

清除样式图标替代文字

**Comment by TCOTC** [comment]
其实最近使用的外观固定是 8 个，这个文字多长都不会影响

**Comment by M2uyo** [comment]
> 其实最近使用的外观固定是 8 个，这个文字多长都不会影响。也就是说没法“多看到一个”

试了下确实是这样,  那就是单纯一个问题了 在多个图标之中插入了一条文字 感觉很违和

**Comment by TCOTC** [comment]
问题不大，因为“镂空”和“投影”也是文字

**Comment by M2uyo** [comment]
> 问题不大，因为“镂空”和“投影”也是文字

感觉好的解决方式是也加icon 整体上协调一点

**Comment by 88250** [comment]
暂时不考虑改动了，感谢反馈。
