### ISSUE TITLE
Improve editor emojis loading

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12241]
自定义表情(emoji)无法插入文档

- [ ] 新增的自定义表情需要在重建索引之后才能插入文档

   [视频.webm](https://github.com/user-attachments/assets/71d2da18-0a70-469c-ac1c-8f9133e18414)

- [ ] 自定义表情的文件名或路径中含有特殊符号时无法插入文档（空格、Markdown标记符……），需要转义

   ![image](https://github.com/user-attachments/assets/a402be46-7926-400e-b763-8e0f61c6be27)

**Comment by 88250** [comment]
> 自定义表情的文件名或路径中含有特殊符号时无法插入文档（空格、Markdown标记符……），需要转义

这个目前没有办法处理了，只能在插入文件前自行处理好。
