### ISSUE TITLE
Recurring tasks and Database view features

### ISSUE THREAD

**Issue by rishacha** [siyuan-note/siyuan#12244]
### In what scenarios do you need this feature?

@88250, 

Is it possible to add the following features to the database?

Please let me know your thoughts/optimal solution for this. 

My objective - 

1. I want recurring tasks to be supported natively by SiYuan
2. I want to create a finance tracker and wanted to add -
    1. Payment reminders/EMI payment reminders (using the above recurring tasks feature)
    2. Pivot table like chart visualizations for tables like - Total income, expenses etc. ( I know this is a bit ambitious and difficult to implement)
    3. Calendar view for the above payment reminders/schedule etc (This may be the scope of a plugin), but please take a look at [this issue thread](https://github.com/syh19/siyuan-plugin-task-list/issues/31#issuecomment-2258816908)

My recommendations - 

1. Add a unique, auto-generated id as a primary key of the database, similar to this - [Notion - Unique ID](https://www.notion.so/help/unique-id)
2. I want to setup recurring tasks and visualizations for databases (like excel pivots). Hence I want to try out something like -
    1. [Calendar view](https://www.notion.so/help/guides/calendar-view-databases)
    2. Chart view

### Describe the optimal solution

Proposed solution - 

1. Unique ID - Notion implements this
2. Calendar view - Notion also has this implemented
3. Chart view - This is the tricky one !

### Describe the candidate solution

I will add a candidate solution after I know your thoughts on this. 

### Other information

Please let me know your thoughts/optimal solution for this. I am ready to help with implementations if you're okay, but need to know if this makes sense. 

Thank you for all the effort !

**Comment by fwonce** [comment]
Same requirement here but I don't believe it's easy to implement in a note-taking application. I use Microsoft Todo for these tasks partially.

**Comment by rishacha** [comment]
@fwonce - All I need is some metadata in the tasks block. I can then build a plugin on top or extend existing plugins.

What about unique id in databases?

**Comment by rishacha** [comment]
Tagging again to bump @88250 @Vanessa219 - a penny for your thoughts

**Comment by rishacha** [comment]
@88250 @Vanessa219 - Some response/solution/roadmap?

**Comment by 88250** [comment]
Hello, this feature will not be considered in the short term for the following reasons:

* The database currently needs to solve other basic issues
* The next plan for database view is the dashboard https://github.com/siyuan-note/siyuan/issues/8873 and the gallery view https://github.com/siyuan-note/siyuan/issues/10414

So the native support for this feature request cannot be achieved in the short term, maybe it can be achieved through a plug-in (operating data through the database API), thank you.
