### ISSUE TITLE
Please enter the title of the feature request

### ISSUE THREAD

**Issue by Esdyee** [siyuan-note/siyuan#12245]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/8c475dbb-32cf-4572-bec3-9289a6b932c8)

### Describe the optimal solution

I installed your product on my fileserver.
And I use it a lot through web pages.
So it would be nice to have a url link to it as well.
I would like to be able to use the browser history API of the link I am currently viewing to copy the location of the page I am currently viewing.

**Comment by mozhux** [comment]
![image](https://github.com/user-attachments/assets/75dcd8d4-4752-447f-9966-829b351bd143)

**Comment by fwonce** [comment]
You forgot to enter the title buddy

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:

**Comment by TCOTC** [comment]
#12253
