### ISSUE TITLE
希望接口 `/api/ref/getBacklinkDoc` 添加参数 `containChildren`

### ISSUE THREAD

**Issue by Misuzu2027** [siyuan-note/siyuan#12254]
### In what scenarios do you need this feature?

我正在开发反链面板插件，有个功能只会获取指定定义块的反链信息，但是遇到一些情况下接口效率很低，分析后发现是因为这个定义块下方有太多子块，会递归查询该定义块下的所有定义块。

### Describe the optimal solution

我看了下源码，发现 `QueryRefsByDefID` 方法可以传参数进行控制是否包含子级，所以改动不是很大。

只需要给接口 `/api/ref/getBacklinkDoc` 添加一个 `containChildren` 参数即可。

**考虑到兼容性**，如果 `containChildren` 没有传进来，还是默认为true，如果接口传了参数 `containChildren` ，就以接口入参为准。

**Comment by 88250** [comment]
欢迎 pr



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月15日(周四) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 希望接口 `/api/ref/getBacklinkDoc` 添加参数 `containChildren` (Issue #12254)




 
In what scenarios do you need this feature?
 
我正在开发反链面板插件，有个功能只会获取指定定义块的反链信息，但是遇到一些情况下接口效率很低，分析后发现是因为这个定义块下方有太多子块，会递归查询该定义块下的所有定义块。
 
Describe the optimal solution
 
我看了下源码，发现 QueryRefsByDefID 方法可以传参数进行控制是否包含子级，所以改动不是很大。
 
只需要给接口 /api/ref/getBacklinkDoc 添加一个 containChildren 参数即可。
 
考虑到兼容性，如果 containChildren 没有传进来，还是默认为true，如果接口传了参数 containChildren ，就以接口入参为准。
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by 88250** [comment]
已经合并 PR，感谢贡献。
