### ISSUE TITLE
重启后保持页签查看顺序

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12259]
一般会打开上一个标签页（这是符合预期的），但在不知道“上一个”是哪一个的情况下，应该打开左边的标签页而不是打开最右侧的标签页（左侧没有标签页的情况下打开右侧标签页）。

跳到最右边再滚动回左边很麻烦：

[视频.webm](https://github.com/user-attachments/assets/b628e0ce-6d0b-4528-9fc0-91742f2cf660)

**Comment by Vanessa219** [comment]
程序是知道上一个是那一个标签的。

**Comment by TCOTC** [comment]
看起来界面刷新之后就不知道了

**Comment by Vanessa219** [comment]
从左到右

**Comment by TCOTC** [comment]
不一定是从左到右，新页签也可以在中间打开。

不过问题不是这个，聚焦页签的顺序是相对随机的。我改了一下 issue 标题。

**Comment by Vanessa219** [comment]
重载后是从左到右的，聚焦是按照用户点击的。

**Comment by TCOTC** [comment]
研究了一下，应该需要持久化 tab-header 的 data-activetime 才行，否则重载之后 data-activetime 就是从左到右按顺序递增的了

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
