### ISSUE TITLE
Support making a new flashcard from a one-liner block

### ISSUE THREAD

**Issue by fwonce** [siyuan-note/siyuan#12251]
### In what scenarios do you need this feature?

I have some language learning notes like this.
```
# New words in this article
真ん中: まんなか、middle
アーティスト: artist
今夜: こんや、tonight
前: まえ、ago, front
今日: きょう、today
お皿: おさら、plate
電気: でんき、electronics
象: ぞう、elephant
千葉: ちば、Chiba
昨日: きのう、yesterday
始めで: はじめで
```

And I want to make new flashcards from each line of them as I wish. I don't want to conform the way SiYuan requires to recognize the flashcard's front and back content, i.e. sublist style, etc. Because that will make my notes pretty clustered and extensively long.

### Describe the optimal solution

It's nice to have a one-liner flashcard recognition style, asides the existing ones. The syntax can be discussed, not necessarily to use a colon to delimit the front and back content as I use in the example above. I'm okay to follow the rule everyone likes. Even a table row is okay for me but I don't believe it's easy to be implemented.

### Describe the candidate solution

A more sophisticated way is to have a delimiter text setting rather than a hardcoding one.

### Other information

I'm happy to help contributing on implementation, as long as you guys like this idea.

**Comment by 88250** [comment]
Sorry, SiYuan can only make cards based on blocks, there is no other way to make cards.

**Comment by fwonce** [comment]
> Sorry, SiYuan can only make cards based on blocks, there is no other way to make cards.

@88250 Thank you for noticing but I believe there are some misunderstanding. Let me explain my idea more elaborately.

Every line of text is a BLOCK in SiYuan, right? Let's say I select the whole line `アーティスト: artist` in the example and press `Cmd + Option + F`, or I click the block handle `⠿` before this line and select `Quick make card`. Either way, I will get a new entry in my flashcard database, whose front (question) content is `アーティスト: artist`, and back (answer) content is also the same, although not what I desire. My expectation for the front (question) content is `アーティスト` and for the back (answer) content is `artist`.
```
# New words in this article
真ん中: まんなか、middle
**アーティスト: artist**  <--- THIS LINE
今夜: こんや、tonight
......
```
Therefore I'm talking about making cards based on blocks indeed, which is completely compatible with SiYuan's principle. The only difference is that it's a one-liner block. If I want to achieve my expectation, I must to put the same one-liner this way and do the `Cmd + Option + F` thing.
```
- アーティスト <--- the front (question) part
    - artist  <--- the back (answer) part
```
I hope I've conveyed the idea clearly this time.

Best regards.

**Comment by fwonce** [comment]
@88250 Hey sorry to bother, but could you please take a look at my last reply?

**Comment by 88250** [comment]
> Every line of text is a BLOCK in SiYuan, right? 

This is not the case. SiYuan divides blocks based on Markdown syntax. For example:

```
* foo
```

Although there is only one line, it actually contains three blocks:

1. List block
2. List item block
3. Paragraph block

For soft line break structures, such as:

```
foo
bar
```

These two lines will only form a paragraph block.

---

For the card making structure you need, you can try this:

![image](https://github.com/user-attachments/assets/7c84e58a-8c6c-4364-8fc1-d192e2b43487)
