### ISSUE TITLE
删除当前查询条件后 `清空查询条件` 

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12258]
删除了查询条件，下一次搜索的时候就不应该继续使用已经删除的查询条件：

[视频.webm](https://github.com/user-attachments/assets/0c75ea37-48ed-45ff-892a-b32951d14de4)

**Comment by Vanessa219** [comment]
如果删除其他查询条件的话，当前查询还是要保存的。为统一，删除后就都保留了。

**Comment by TCOTC** [comment]
这个逻辑就是感觉怪怪的，还得再想想

**Comment by Vanessa219** [comment]
如果删除的是当前的，就是有蓝边的再清空？
![QQ_1723867341364](https://github.com/user-attachments/assets/b61c06ea-5206-4f14-9c7b-ba2972e29c29)

**Comment by TCOTC** [comment]
也行

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
