### ISSUE TITLE
底部出现滚动条

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12264]
关联 https://ld246.com/article/1723540577279

新工作空间，字号是默认的，在改变界面整体大小的时候会出现底部的滚动条：

[视频.webm](https://github.com/user-attachments/assets/379e8fea-ba16-48d5-a76d-304721727745)

**Comment by 88250** [comment]
我这里重现不了。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:

**Comment by TCOTC** [comment]
@Vanessa219 我这里依旧能复现，我发现好像跟这个 `min-width` 有关：

[video.webm](https://github.com/user-attachments/assets/7b4a3587-8a6b-4fc1-a855-081079842498)

**Comment by TCOTC** [comment]
找到问题了，是因为侧栏面板有个 `min-width: 0.1px`，需要默认 `display: none;`，我等会看看怎么修改

关联 https://github.com/siyuan-note/siyuan/issues/13516 02

https://github.com/user-attachments/assets/25f1cc36-762b-4faf-8dc9-e55fcbbd7e50

**Comment by TCOTC** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/14856
