### ISSUE TITLE
改进块拖入数据库

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12263]
### Notion 的范围是这么大：

![image](https://github.com/user-attachments/assets/28444474-e0ef-4f89-8d2f-49f08250e3de)

### 目前思源要把块准确拖动到这条线上才能添加进数据库，不太方便：

![image](https://github.com/user-attachments/assets/2fdb7854-5276-4670-86fc-c8bac3728d54)

### 我希望块拖动到至少这个范围内就能添加进数据库：

![image](https://github.com/user-attachments/assets/e1b3c820-699e-406c-931c-f95b6111786e)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by TCOTC** [comment]
@Vanessa219 新版又不行了

**Comment by Vanessa219** [comment]
看上去是好的呀。

https://github.com/user-attachments/assets/112ebe9c-934a-40db-bd64-6d6be218372c

**Comment by TCOTC** [comment]
今天又好了，不知道为啥，能稳定复现我再说
