### ISSUE TITLE
代码块语言位置和行号开关有问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12268]
> 也许是 #10769 的延伸

1. 新建代码块的时候，代码块语言位置不对，要先关闭行号再开启行号才正常
2. 关闭行号没有反应

[视频.webm](https://github.com/user-attachments/assets/4c07b1b7-e159-4c9f-b154-43520172059d)

**Comment by Vanessa219** [comment]
不拉进版本了

**Comment by Misuzu2027** [comment]
行号好像还有个小问题，点击行号会在行号内出现输入光标，不过输入后会把内容移到代码块中。


https://github.com/user-attachments/assets/06e555f8-7912-4489-8fe4-c9c80604eb32

**Comment by TCOTC** [comment]
确实。 @Vanessa219 光标可以出现在行号后面
