### ISSUE TITLE
代码块的宽度设置有问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12265]
### 在垂直布局超级块中设置 100% 的宽度，会超出范围：

![image](https://github.com/user-attachments/assets/34f48e8f-562f-48e0-85fc-48dce63948d8)

[视频.webm](https://github.com/user-attachments/assets/2376c5e5-6a14-43d3-9466-e58d6150adec)

### 然后取消超级块，再合并为水平布局超级块时也不正常，跟没设置过宽度的代码块表现不一样：

[视频.webm](https://github.com/user-attachments/assets/bc95b99c-e01c-4816-aba2-142457864dd3)

**Comment by Vanessa219** [comment]
第一个已修复，第二点是正常的，因为设置了宽度为 100%，取消就可以了。
