### ISSUE TITLE
api sql调用思源如何保持内容结构和高效

### ISSUE THREAD

**Issue by sunk926** [siyuan-note/siyuan#12260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

目前需要将思源中的特定标签内容通过api导入到知识库系统,但是只能 先获取到标题,然后再通过标题递归出所有的子块,包括多层级的块,再用 getChildBlocks 获取到顺序id,最后再根据获取到的id进行对sql获取的内容排序.

### Expected result

这样的效率太低了,每次取一条信息,要递归sql查询很多次,而且容易出错..有没有高效一点的方法,就指定某个id就可以直接取出这个id下面所有层级的内容. 同时内容顺序结构保持不变.其实就是类似 getChildBlocks ,不光是取出id,还有content,markdown.

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
可以试试这个接口 /api/block/getBlockTreeInfos https://github.com/siyuan-note/siyuan/issues/11311

**Comment by sunk926** [comment]
> 可以试试这个接口 /api/block/getBlockTreeInfos #11311

感谢, api文档里面没这个接口.

**Comment by 88250** [comment]
我大概明白了，我们改进一下 getChildBlocks https://github.com/siyuan-note/siyuan/issues/8249 吧，加入返回 content 和 markdown 字段。

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by sunk926** [comment]
> 稍后会发布一个 dev 版，请帮忙测试。
测试了下,没什么问题,顺序都是对得上的

**Comment by 88250** [comment]
Ok



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月17日(周六) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] api sql调用思源如何保持内容结构和高效 (Issue #12260)




  
稍后会发布一个 dev 版，请帮忙测试。
 测试了下,没什么问题,顺序都是对得上的
