### ISSUE TITLE
数据库在搜索时新增条目，需要先清空搜索内容再新增条目

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12269]
目前条目会被直接过滤掉，变成一个多余的空白条目，根本没有意义。

所以在新增条目时应该自动清空搜索内容。

---

改的时候顺便改一下提示的文案：

> 新增行已被过滤，可取消过滤/搜索/排序进行查看

改成：

> 新增行已被过滤，可取消过滤/排序进行查看

**Comment by 88250** [comment]
不考虑动了，目前的提示已经能够让用户知道结果，是否删除搜索关键字用户自己决定更好。
