### ISSUE TITLE
使用内容动态查询，内存占用高，电脑直接卡顿

### ISSUE THREAD

**Issue by o-ut-man** [siyuan-note/siyuan#1226]
只打开了1个内容动态查询的页签，查询结果不超过20条，内存占用就上去了不少。只要打开2个有内容动态查询的页签，电脑就直接卡顿。 虽然电脑配置不是很高，但希望还是优化一下

**Comment by 88250** [comment]
你好，麻烦截图看下 kernel 进程内存占用情况，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果有反馈请继续跟帖，谢谢。
