### ISSUE TITLE
“#”符号包裹的标签可以在指定范围或域显示，不在范围内的不显示，减少干扰

### ISSUE THREAD

**Issue by wxknxxzj** [siyuan-note/siyuan#1227]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
一个文件夹下给某个文件的某个块打标签，比如文本块摘抄梳理，文献条目分类等
只在该文件下的标签显示，不只是全局标签。

### 描述最优的解决方案 Describe the optimal solution

在标签选项卡增加一个可以调整显示范围的入口，这个文件本身，该文件夹内等

### 描述候选解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
你好，标签页签的设计目的就是为了全局显示的，这是为了能从另一个角度看到块的组织（跨笔记本的）。

你提到的场景建议用层级标签解决，这样能将某个子标签的“作用域”限制在某个父标签下面，在标签页签的顶层上就会只占一条了。

我关闭了，还有建议或者讨论的话请随时跟帖，谢谢。
