### ISSUE TITLE
当新建一个空的笔记时，启动时右上角总是提示”未找到相关内容“

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

所谓空笔记，就是我新建了一个笔记，这个笔记下没建任何文档，即一个空列表的笔记。

然后，重启思源时，右上角总是提示”未找到相关内容“

### Expected result

期望这种情况不要加这种提示，感觉没必要。

刚开始没注意，后来发现老是提示这个问题，莫名其妙，找了好久都没找到原因，后来，通过搜索源码排查，设置断点，才发现是笔记空列表导致的。感觉没必要提示，会给用户带来困扰，如果不懂源码的朋友可能很难发现是哪里出的问题。

### Screenshot or screen recording presentation

<img width="182" alt="image" src="https://github.com/user-attachments/assets/fb862080-ebdf-4610-8f16-b8e38b5e0b89">

### Version environment

```markdown
- Version: 3.1.3
- Operating System: macos14.5
- Browser (if used):
```

### Log file

no no no

**Comment by 88250** [comment]
麻烦录屏演示一下重现步骤。

**Comment by wish5115** [comment]
> 麻烦录屏演示一下重现步骤。

仔细观察了下，目前，没找到重现的步骤，仅仅我这个文件夹，删除文档后，偶尔会出现，我新建笔记再删除没用出现这个问题，把这个笔记导入到别的空间也没出现问题。

![r27](https://github.com/user-attachments/assets/139beb59-6813-4613-8d75-7c6acce7e715)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:
