### ISSUE TITLE
请问可以在数据库的文本模式下，增加字体颜色和格式输入的选项吗？

### ISSUE THREAD

**Issue by wk-coder** [siyuan-note/siyuan#12272]
### In what scenarios do you need this feature?

比如以前是分开的每一页“每日总结”，现在有了数据库，想把其中的几项单独列几个竖栏，方便直接浏览

### Describe the optimal solution

像我这样的话，可能就当作notion表格来使用了，和以前的双链互相引用模式确实不太一样，不过这样记录方便。就是格式上，现在数据库的文本模式下无法用列表和颜色等等，看上去不能一眼区分。不知道是否可以实现？

**Comment by TCOTC** [comment]
Duplicate of #11553
