### ISSUE TITLE
希望佬可以加入思源内部块嵌入的标题功能以实现嵌入文档内部块或文档的时候实现大纲也被嵌入

### ISSUE THREAD

**Issue by fairyli7** [siyuan-note/siyuan#12277]
### In what scenarios do you need this feature?

> - 引用的粒度是否可以再大一些(文档级别)，现有的超级块(无论是文档级别还是，块级别)嵌入到另一个文档内容之后都是没有(被引用内容的)的大纲，感觉嵌入块和文档内容的割裂感很重
> - 或者文档树，可以多一个软连接选项(可以软连接到另一个文档)
> - 如果以上两个都不能实现的话，那么是否可以考虑实现IFrame可以嵌入思源内部块(这样是不是可以渲染出标题大纲了)

#### 在尝试嵌入块和文档的过程中
- 嵌入块的尝试中无法显示大纲
<img width="1849" alt="1" src="https://github.com/user-attachments/assets/fd37d0d3-2caf-4726-b756-c83f744906e6">

- 嵌入一个整个文档的引用也是无法显示大纲
   - 复制子文档D为嵌入块
   - 粘贴到子文档C
<img width="1854" alt="2" src="https://github.com/user-attachments/assets/cd05a412-3667-43af-9b8c-c6413738941c">

#### 在尝试`IFrame`的过程中
> 我发现似乎可以嵌入，但是不是一个实体，不会显示，我按F5刷新之后，会跳转到子文档D
> 如果这样我的问题也解决了，但是当我点击子文档C的时候它不会自动F5刷新跳转(这个使我很苦恼)
<img width="1852" alt="3" src="https://github.com/user-attachments/assets/7e88e368-70ed-4d58-a500-d56370907282">

 - 未刷新，不会进行显示或者跳转
<img width="1825" alt="4" src="https://github.com/user-attachments/assets/cae2b935-0834-448d-99d3-2b3a324bb9f2">

 - 当我刷新之后会进行显示和跳转
<img width="1842" alt="5" src="https://github.com/user-attachments/assets/5536af11-52a4-4659-aba7-60f68cf5cd8b">

###
 - 嵌入块有标题和大纲显示
 - 或者IFrame可以嵌入内容块(实现内容的跳转或者嵌入带有大纲的渲染)
 - 或者文档树可以配置软链接，可以使一个文档的内容直链接到另一个文档上面(就可以实现同步修改了) 
      - 类似这样
<img width="736" alt="6" src="https://github.com/user-attachments/assets/937a0dc7-7cd7-427e-b469-c630a4a000d1">

**Comment by 88250** [comment]
抱歉，没有计划支持在嵌入块中显示大纲。
