### ISSUE TITLE
改进任务列表项拖拽到文档树

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12283]
只有拖任务列表项到文档树之后会多出一个段落块：（应该去掉这个多余的段落块）

![image](https://github.com/user-attachments/assets/66c820b2-eafd-416e-8800-bb823c90152b)

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/12411 中统一改为保留段落。
