### ISSUE TITLE
Support to connect AI to OpenWebAI

### ISSUE THREAD

**Issue by NightHawkATL** [siyuan-note/siyuan#12285]
### In what scenarios do you need this feature?

To keep things local and not have to pay for AI interaction.

### Describe the optimal solution

Add a drop-down in settings to choose from OpenAI or OpenWebAI (Ollama). Once Ollama is selected, there will be options to link to the self-hosted service for URL or IP:Port and API key or login information.

### Describe the candidate solution

not sure what this means.

**Comment by ricardosilva86** [comment]
That's a very interesting feature, which could make this whole solution possible to run entirely on a local machine/network without the need of plugin anything to the outside world.

**Comment by 88250** [comment]
Please refer to here https://liuyun.io/article/1704494054801
