### ISSUE TITLE
云端配置二维码

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#12288]
### In what scenarios do you need this feature?

云端同步数据时，能否加一个二维码导入/导出配置的选项，如下图：
<img width="725" alt="image" src="https://github.com/user-attachments/assets/d1e595e3-4f1d-4584-b930-5348ed802f8d">

### Describe the optimal solution

看了下配置文件（似乎是加密的）大概900个字符，二维码最大容量2.9kb，应该是可以存下的

**Comment by EaMarWi** [comment]
+1

**Comment by 88250** [comment]
感谢提议，但是不考虑添加这个特性了，请使用导出/导入功能。
