### ISSUE TITLE
数据库属性面板资源列添加链接后出现无法关闭窗口等bug

### ISSUE THREAD

**Issue by QMike0** [siyuan-note/siyuan#12289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这个issue是对[issue12034](https://github.com/siyuan-note/siyuan/issues/12043)第二条的补充

数据库属性面板的资源列在已存在资源时，存在之前issue所说的“无法点击已添加好的“链接”，也无法添加更多资源”问题。最近又发现若没有添加资源（例如链接），是可以在属性面板界面添加资源的，但添加后便无法关闭窗口，并且无论左键还是右键点击，都会默认一直向资源列中重复添加。由于无法退出，这时只能强制关闭思源。
![PixPin_2024-08-19_14-53-51](https://github.com/user-attachments/assets/c6ca909d-9626-4943-a81b-efae92f4191a)

### Expected result

数据库属性面板的资源列无论是否已添加资源，都应支持继续添加，并且完成添加后能够像在数据库中那样点击空白区域退出，而不是重复添加

### Version environment

```markdown
- Version: v3.1.3
- Operating System: windows 11和linux都存在该问题
- Browser (if used):
```

### Log file

[Uploading siyuan.log…]()

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/12044
