### ISSUE TITLE
Why don't you add a permission control feature

### ISSUE THREAD

**Issue by xzclinux** [siyuan-note/siyuan#12286]
### In what scenarios do you need this feature?

Document Management for Enterprises

### Describe the optimal solution

Create your own user space for each user

**Comment by ytm157** [comment]
> 协作还不是现阶段考虑的，这个还需要从长计议，感谢讨论。

https://github.com/siyuan-note/siyuan/issues/11716#issuecomment-2223274227

> 你好，目前思源笔记是面向个人的知识管理工具，所以短期内是不考虑支持多用户的，谢谢。

https://github.com/siyuan-note/siyuan/issues/11382#issuecomment-2109065540
