### ISSUE TITLE
关于用户指南数据库的疑问

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12282]
### 切换界面语言之后从菜单打开的用户指南能看到对应语言的数据库：

![image](https://github.com/user-attachments/assets/b1256687-0506-4dc7-8cac-31acfea4d801)

### 但把所有用户指南**直接复制**进工作空间之后重建索引，却只能看到中文的数据库：

![image](https://github.com/user-attachments/assets/b9be110e-a30c-4e8b-a61e-de709844c814)

![image](https://github.com/user-attachments/assets/b585fb4c-27be-437c-bbbd-84558a729024)

**Comment by 88250** [comment]
字段名称没有多语言的，一开始设置的是什么语言后面就是那个语言了。

**Comment by TCOTC** [comment]
但为什么其他数据库加载不出来呢？

**Comment by 88250** [comment]
我这里好像没有问题：

![image](https://github.com/user-attachments/assets/1b0cc7be-ef5d-47ec-9f0d-bd8b46843447)

**Comment by TCOTC** [comment]
怪怪的，不管了
