### ISSUE TITLE
打开 PDF 之后向下分屏，会使 PDF 跳转到第一页

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12287]
[视频.webm](https://github.com/user-attachments/assets/363f6a2e-b0d3-4bab-a673-31c74b9f7bf8)

**Comment by Amarantos475** [comment]
[

Uploading QQ2024819-141721.mp4…

](url)

**Comment by Amarantos475** [comment]
https://github.com/user-attachments/assets/46a7209c-03ff-4a9b-84fc-e7d1c36df0cb
