### ISSUE TITLE
不小心删除了有多个子文档的文档后回滚恢复超麻烦

### ISSUE THREAD

**Issue by holduan** [siyuan-note/siyuan#12295]
### In what scenarios do you need this feature?

如题，手速快，没注意自己选错了文档并删除了，没有建立快照或者备份，目前只能通过逐个恢复已删除的文档，但不能批量恢复，并且每恢复一个文档都会重新索引，重新索引后才能进行恢复操作，索引时间又很长（1500个块元素左右，还是存SSD里面），20个文档，恢复花了我30分钟... 希望可以完善一下这方面的体验，谢谢。

### Describe the optimal solution

-

**Comment by TCOTC** [comment]
确实是很麻烦，希望能改进 #11872

目前有个方法就是在本地 history 文件夹里找到该文档的文件夹手动复制到 data 文件夹下对应的位置

**Comment by holduan** [comment]
> 确实是很麻烦，希望能改进 #11872
> 
> 目前有个方法就是在本地 history 文件夹里找到该文档的文件夹手动复制到 data 文件夹下对应的位置

原来还有这方法，谢谢提醒，可惜我已经手动逐个恢复了，要是早知道你这方法我就不用这么折腾了 😢

**Comment by 88250** [comment]
抱歉，目前暂时没有更好的方案了。

**Comment by TCOTC** [comment]
回滚文档后仅重新索引当前文档：#12320 ，下个版本回滚的索引应该超级快了
