### ISSUE TITLE
公式块语法对于overparen这种圆弧表示不支持

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#12293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

```
\overparen{AB} 
\overset{\LARGE{\frown}}{AB}
\widehat{AB}
```
其中```\overparen{AB} ```不支持，会报错
![image](https://github.com/user-attachments/assets/8a9d9891-b3e2-4b0f-9976-916fb30f7fca)
```
KaTeX parse error: Undefined control sequence: \overparen at position 1: \overparen{AB}
```

### Expected result

三种圆弧语法都能支持
![image](https://github.com/user-attachments/assets/12a6baee-0ca6-4a11-92f4-39dae02d263b)

[在线Latex测试](https://www.latexlive.com/##)

### Version environment

```markdown
- Version: 3.1.3
- Operating System: Windows 10 14939
- Browser (if used): Chrome 120
```

### Log file

![image](https://github.com/user-attachments/assets/8a9d9891-b3e2-4b0f-9976-916fb30f7fca)
```
KaTeX parse error: Undefined control sequence: \overparen at position 1: \overparen{AB}
```

### More information

![image](https://github.com/user-attachments/assets/87013bea-60ca-4a90-b526-8909ca105567)
行级公式也是一样的错误。
目前我找到的替代解决方案如下：
```
\overset{\LARGE{\frown}}{AB}
\widehat{AB}
```

**Comment by 88250** [comment]
如果 KaTex 不支持的话就没有办法了，建议搜一下 KaTex 文档看是否有替代方案。

https://katex.org/

**Comment by ruin1990** [comment]
参考了下https://katex.org/docs/support_table.html#o
可以使用\overgroup{AB} 代替
