### ISSUE TITLE
资源文件的锚文本有点问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12290]
- [ ] 第一次拖入文档后锚文本多出了 `-20240819153903-8m6vvfo` ，应该只有原来的文件名才对（第二次拖入的时候就是正常的）
- [ ] 相同文件的第二个链接重命名，却是第一个链接的锚文本改变了

[视频.webm](https://github.com/user-attachments/assets/d474f80a-c83e-4987-84f7-67180082661e)

**Comment by TCOTC** [comment]
用户反馈：

- https://ld246.com/article/1724941941636

**Comment by 88250** [comment]
已在 https://github.com/siyuan-note/siyuan/pull/12361 中修正，感谢反馈。

**Comment by TCOTC** [comment]
@88250 #12361 能修复本 issue 的第二个问题吗？

**Comment by 88250** [comment]
应该能，本质上是同一个问题



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月30日(周五) 中午12:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 资源文件的锚文本有点问题 (Issue #12290)




 
@88250 #12361 能修复本 issue 的第二个问题吗？
