### ISSUE TITLE
加粗渲染问题

### ISSUE THREAD

**Issue by wfan14513** [siyuan-note/siyuan#123]
过程：
1.加粗一句话中的一段，比如“假设，**如果**，所以。”，正常渲染。
2.再加粗整一句：“**假设，**如果**，所以。**”，思源也渲染，但是到处文件用ty打开，中间的“如果”是没加粗的，这个ty比较符合逻辑。
3.然后思源里手动删除中间的四个*号：“**假设，如果，所以。**”，就不渲染了。

其他语法是不是也有同样情况，没有试。

**Comment by 88250** [comment]
发明发一下 Markdown 文本，使用 ` ``` ` 包裹作为代码块贴一下，类似这样：

````markdown
```markdown
这里是原 Markdown 文本
```
````

**Comment by wfan14513** [comment]
过程：
1.加粗一句话中的一段，比如：
```markdown
假设，**如果**，所以。
```
正常渲染：假设，**如果**，所以。
2.再加粗整一句：(用惯了word导致的行为)
```markdown
**假设，**如果**，所以。**
```
思源也渲染：**假设，如果，所以。**
但是用ty打开导出文件，中间的“如果”是没加粗的：**假设，**如果**，所以。**
3.然后思源里手动删除中间的四个*号：
```markdown
**假设，如果，所以。**
```
思源就不渲染了，显示结果为：
```markdown
**假设，如果，所以。**
```

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/94522869-e95a6c80-0262-11eb-9268-07103f80ee3a.png)

这个按 CommonMark/GFM 规范标准来说是应该要渲染的，以 GitHub 和[这里](https://spec.commonmark.org/dingus)的渲染结果为准。

![image](https://user-images.githubusercontent.com/873584/94523109-4e15c700-0263-11eb-93ba-5730fc6bb54f.png)

这个我这里重现不了，如果方便请录屏演示。

**Comment by wfan14513** [comment]
好滴，发群里了。

**Comment by 88250** [comment]
有标点符号的情况应该是不渲染的，v0.2.4 修复。
