### ISSUE TITLE
数据库资源列支持直接粘贴标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12308]
在 #11463 中已经支持了粘贴以下两种链接：

1. 带锚文本：`[VCB-Studio 公开教程](https://guides.vcb-s.com/)`
2. 不带锚文本：`https://guides.vcb-s.com/`

我发现在粘贴时能判断出文本是否是链接，如果不是链接的话就不会粘贴到资源列里。

所以就有了这个需求：粘贴时如果判断不是链接，则粘贴为标题（链接留空）

p.s. 本 issue 是 #11469 需求的延伸

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/12044
