### ISSUE TITLE
无法正常粘贴GIF图片

### ISSUE THREAD

**Issue by EndlessErrors** [siyuan-note/siyuan#1230]
### 描述问题 Describe the problem

粘贴GIF格式图片时，要么没有反应，要么会转为PNG格式。但是拖拽添加GIF能正常添加。

### 版本环境 Version environment

* 版本 Version：v0.6.6 
* 操作系统 Operating system：Win10

**Comment by 88250** [comment]
这个应该是粘贴的时候系统程序决定的，用拖拽吧，谢谢。
