### ISSUE TITLE
Improve mouse hover tips for database asset fields

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12309]
数据库资源列链接留空时，没有显示标题的悬浮提示

> 关联 #11465

填了链接 & 填了标题：有悬浮提示，正常

![image](https://github.com/user-attachments/assets/baef25ff-9824-4961-8031-a270ca2785f0)

**没填链接** & 填了标题：无悬浮提示，异常

![image](https://github.com/user-attachments/assets/9beef2ee-12ba-401e-b20d-756ba5f745cd)

**Comment by Vanessa219** [comment]
由于 https://github.com/siyuan-note/siyuan/issues/12308 产生的，就不拉进版本。
