### ISSUE TITLE
更新文档可读路径会不会有点慢？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12312]
移动文档之后。这个速度是正常的吗？

每个文档的块数都不同，但我怎么感觉耗时这么均匀。

[视频.webm](https://github.com/user-attachments/assets/df2171bb-f938-4814-abca-fc9431d7b3bc)

[system-log.zip](https://github.com/user-attachments/files/16724153/system-log.zip)

**Comment by TCOTC** [comment]
另外这里一直显示的是 `已经更新 [1] 个文档的可读路径` ，什么情况下会更新多个文档？

**Comment by 88250** [comment]
看上去是正常的，可读路径要更新每个块的路径。

 已经更新 [1] 个文档的可读路径 文案是因为一个文档包含多个块。
