### ISSUE TITLE
Improve CSDN clipping

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12313]
改进 CSDN 剪藏

1. 这部分不需要剪藏下来：

   ![image](https://github.com/user-attachments/assets/e87e891a-d464-4881-b603-9729086c1902)

2. 剪藏的代码块里有很多空行：

   ![image](https://github.com/user-attachments/assets/4dafd722-4cf1-4515-8387-fb2c985934a6)

**Comment by 88250** [comment]
请提供一个网页以便调试，谢谢。

**Comment by TCOTC** [comment]
https://blog.csdn.net/mini_1251861209/article/details/125000023

[滚动条出现挤压页面宽度，影响布局_监听宽度时忽略出现滚动条的影响-CSDN博客.zip](https://github.com/user-attachments/files/16825149/_.-CSDN.zip)

**Comment by 88250** [comment]
需要升级剪藏扩展。

**Comment by 834116404** [comment]
这是什么剪辑插件?

**Comment by 88250** [comment]
> 这是什么剪辑插件?

https://github.com/siyuan-note/siyuan-chrome
