### ISSUE TITLE
改进剪藏标题元素

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12319]
剪藏：https://ld246.com/article/1702570646974

图片后的标题的剪藏有点问题：

![image](https://github.com/user-attachments/assets/e1809e71-b262-478f-bff1-1aba620048ee)

![image](https://github.com/user-attachments/assets/92b00c84-c4bf-4599-8776-901effeff21b)

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/12368 中改进了。
