### ISSUE TITLE
Improve web clipping adaptation

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12310]
网页无法剪藏

https://blog.goalonez.site/blog/Tailscale%E8%87%AA%E5%BB%BA(Headscale%E5%8F%8ADerp).html

![image](https://github.com/user-attachments/assets/97b50f55-4150-4a4e-afbc-8401829b8b41)

关联　https://ld246.com/article/1724376356090

**Comment by 88250** [comment]
需要升级剪藏扩展。
