### ISSUE TITLE
Reindex only the current document after rolling back the document

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12320]
支持在回滚文档时打断重建索引

每回滚一篇文档都要等半天才能继续回滚下一篇，需要回滚的文档多了就得等很久。

像这个搜索索引就没有必要一直等，直接打断了回滚下一篇文档就好：

![image](https://github.com/user-attachments/assets/bf261da9-04a1-4996-bb9a-253c92c0240c)

**Comment by 88250** [comment]
这个没有办法打断，并且如果打断的话会导致索引不完整出现其他问题。

**Comment by TCOTC** [comment]
那能不能跳过部分不会产生问题的索引？比如这个搜索索引非常耗时，每回滚一个文档都要完整等一遍

**Comment by 88250** [comment]
不行的



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年8月28日(周三) 下午2:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 支持在回滚文档时打断重建索引 (Issue #12320)




 
那能不能跳过部分不会产生问题的索引？比如这个搜索索引非常耗时，每回滚一个文档都要完整等一遍

**Comment by 88250** [comment]
考虑了下，改进为仅重建当前文档索引，不再全量重建索引。

**Comment by TCOTC** [comment]
我还以为不全量重建索引会产生什么问题，原来是可以仅重建当前文档索引的 😄

**Comment by aptexd** [comment]
Oh God, the question has finally changed
