### ISSUE TITLE
复制导致 ID 重复的问题

### ISSUE THREAD

**Issue by alphaleek** [siyuan-note/siyuan#1232]
### 描述问题 Describe the problem
段落块拖动后，新位置的块，里面文字会自动改变。原位置的块不会消失

这些块有个特点，是已存的块复制粘贴的
### 期待的结果 Expected result
修复bug

### 版本环境 Version environment

* 版本 Version：0.6.6
* 操作系统 Operating system：win10

* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5857194/siyuan.log)

**Comment by alphaleek** [comment]
视频在这里，刚才没上传成功
https://user-images.githubusercontent.com/76611744/105518320-1d2a3800-5d13-11eb-85a8-1ba79f059f92.mp4

**Comment by alphaleek** [comment]
又试了一下，把原来复制粘贴过来的块删除，重新打字输入，然后再拖动就正常了

https://user-images.githubusercontent.com/76611744/105519192-17812200-5d14-11eb-8520-6617e86982b1.mp4

**Comment by Vanessa219** [comment]
我这里无法重现，复制粘贴是通过快捷键还是右键还是其他什么方式？

**Comment by alphaleek** [comment]
https://user-images.githubusercontent.com/76611744/106355817-63941e00-6335-11eb-85b3-c1954643380f.mp4

这样可以复现。简单讲就是原内容**test1**，我复制粘贴之后，修改内容为**test2**。再次复制粘贴后，拖动段落块，文字就会自己变化

**Comment by alphaleek** [comment]
> 我这里无法重现，复制粘贴是通过快捷键还是右键还是其他什么方式？

上面发了新的视频，为复现步骤。复制粘贴是快捷键复制粘贴，而且必须是标题块和段落块一同复制
