### ISSUE TITLE
聚焦列表项删除列表块会产生运行时错误

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12326]
聚焦**列表项**删除列表块之后产生运行时错误：

[视频.webm](https://github.com/user-attachments/assets/657fccdd-4524-4e8f-b4ec-a98f505b2799)

聚焦**列表块**删除列表块之后创建了多余的块：

[视频.webm](https://github.com/user-attachments/assets/e7c75693-5be5-41d1-9794-d62eb58e012a)

**Comment by 88250** [comment]
1. 没有办法避免这样的操作
2. @Vanessa219

**Comment by TCOTC** [comment]
1. 能不能在聚焦的块不存在后直接关闭浮窗，不产生运行时错误？

**Comment by Vanessa219** [comment]
第一点和第二点已修复。

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
