### ISSUE TITLE
希望安卓手机端能支持一下文档大纲

### ISSUE THREAD

**Issue by holduan** [siyuan-note/siyuan#12323]
### In what scenarios do you need this feature?

目前12寸的安卓平板是有大纲的，但手机端上没有，不知道8寸的有没有。文档比较长的时候不方便翻找，例如一个整篇的书籍文档，希望可以支持一下

### Describe the optimal solution

-

**Comment by TCOTC** [comment]
你的左侧栏没有大纲吗？

![a7b07710f7defda60f876935d10eeb5](https://github.com/user-attachments/assets/12ee9104-4118-4829-8be2-18909a2023f3)

**Comment by holduan** [comment]
> 你的左侧栏没有大纲吗？
> 
> ![a7b07710f7defda60f876935d10eeb5](https://private-user-images.githubusercontent.com/78434827/361140459-12ee9104-4118-4829-8be2-18909a2023f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTMxOTIsIm5iZiI6MTcyNDUxMjg5MiwicGF0aCI6Ii83ODQzNDgyNy8zNjExNDA0NTktMTJlZTkxMDQtNDExOC00ODI5LThiZTItMTg5MDlhMjAyM2YzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE1MjEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMGYxMmQ3NTE4NDNjYzRiZTk3NDY4M2Q1NWMzMjVlNDEzOTk2YTY4YTdmYjkwOWUyNzcwODE0ZDRmMGU2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s5Llyyhs4D59XILaXgzqKpnXACbC6h8LUMwVeUNvfhE)

感谢提醒，我睁眼瞎啊，哈哈哈

**Comment by 88250** [comment]
没有问题的话关闭了，谢谢。

**Comment by holduan** [comment]
> 没有问题的话关闭了，谢谢。

没啥大问题了。不过希望能优化一下移动端的文档树、大纲等界面的切换交互：
在打开文档树等界面的情况下（全屏右滑），屏幕上半部分左右滑动切换文档树、大纲等界面，屏幕下半部分左滑收缩文档树界面。
谢谢 ❤
