### ISSUE TITLE
「页签切换」支持排序

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12329]
平常会打开一堆页签，经常需要排序，但拖动页签时如果需要跨很多个页签就会感觉不太容易操作（尤其是需要横向滚动的时候），所以希望能在「页签切换」这里支持排序：

![image](https://github.com/user-attachments/assets/bbeab101-367e-47e9-94ee-85189f30703f)

像数据库视图排序这种效果：

![image](https://github.com/user-attachments/assets/7b1054cf-533b-4277-b31d-accae5cb4b1b)

p.s. 未钉住的文档不能拖动到钉住的文档中间；钉住的文档不能拖动到未钉住的文档中间

**Comment by 88250** [comment]
不考虑了，这个还是按打开顺序，感谢反馈。

PS：钉住/未钉住不能混在一起。
