### ISSUE TITLE
希望能够增加一个记忆布局的功能

### ISSUE THREAD

**Issue by Amarantos475** [siyuan-note/siyuan#12333]
### In what scenarios do you need this feature?

因为每次需要打开好几个框，每次都要调整到一定的位置

### Describe the optimal solution

能否增加一个记忆布局情况的选项，能够保存几个布局，进入哪个布局就打开相应的东西

**Comment by TCOTC** [comment]
你说的是这个吗：

![image](https://github.com/user-attachments/assets/f17c4c7e-4c20-4f04-9bdc-d54da34239c2)

**Comment by Amarantos475** [comment]
真不好意思呢
