### ISSUE TITLE
如果视频文件名中有空格，分享到社区无法播放

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12338]
> p.s. 如果文件名里有其他特殊符号，不知道会怎么样

文档：

![image](https://github.com/user-attachments/assets/31ca25bb-489b-4516-a80b-8d9147b2e98d)

分享之后：https://ld246.com/article/1724675033538

![image](https://github.com/user-attachments/assets/67c27ef8-8212-41cb-b38d-40c750c58b48)

这里的文件名原样保留了，实际上要把空格替换为 `_` 才能正常播放视频：

![image](https://github.com/user-attachments/assets/ec921a69-5f42-43e5-896f-d12ba02120f0)

**Comment by 88250** [comment]
需要分享社区才能看到改进。

这个改动就不拉进版本了。
This change will not be included in the version.
