### ISSUE TITLE
The move doc window retains the keyword of the last search

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12335]
希望移动文档界面保留上次搜索的关键词

### In what scenarios do you need this feature?

和文档搜索一样，避免重复搜索

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
另外还有一点是，这个看起来是个按钮，但点了没用：

![62dbeadc6157ac0fee6d55ef9741865](https://github.com/user-attachments/assets/29bdfa55-6fe7-457f-b37c-a8b8a3644841)

**Comment by TCOTC** [comment]
这个机翻有点问题，移动端 mobile 翻译成 move 了

**Comment by 88250** [comment]
> 这个机翻有点问题，移动端 mobile 翻译成 move 了

楼主没说是移动端嘛，说的是移动文档窗口。

**Comment by TCOTC** [comment]
完了理解错了，我另提一个 #13415

**Comment by 88250** [comment]
ok

**Comment by TCOTC** [comment]
这里错开了感觉有点怪：

![image](https://github.com/user-attachments/assets/259191c0-02ed-4942-8fe6-0e0ef41318ab)
