### ISSUE TITLE
cloud index changed 是怎么回事？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12334]
![image](https://github.com/user-attachments/assets/e99ff1e9-c925-4023-b6c1-0f61c10b01a4)

迁移数据，一台电脑可以同步，一台不行

[Asystem-log.zip](https://github.com/user-attachments/files/16741610/system-log.zip)

[Bsystem-log.zip](https://github.com/user-attachments/files/16741619/system-log.zip)

**Comment by 88250** [comment]
另外，迁移数据建议用导出/导入 Data
