### ISSUE TITLE
Please enter the title of the feature request

### ISSUE THREAD

**Issue by Amarantos475** [siyuan-note/siyuan#12332]
### In what scenarios do you need this feature?

pdf标记页面

### Describe the optimal solution

希望能增加一个功能，能够调整框选图片，有时候框选范围比较大，框选过去才发现没有框选完全，只能删除掉框选框然后重新框选，希望能够增加一个选项能够框选后仍旧能调整框选框大小，还有一个问题就是框选的时候我选择的是按CTRL打开框选聚焦，每次框选标记的时候容易误打开离得近的聚焦

**Comment by 88250** [comment]
你好，这个不考虑了，请重新框选标记。后面 Ctrl 的问题也只能尽量避免误操作，感谢反馈。

**Comment by Solost475** [comment]
您好，好像可以通过按下快捷键直接进入类似于一个截图界面，截图界面屏蔽了所有的快捷键，等到截图摘录完成后恢复快捷键，容易框选失误的问题好像可以通过这个方法解决：把他比作一个截图界面，在没有确定框选内容时先不进行将图片直接截取出来，而是先进行调整，等到调整完摘录大小后再进行真正的截取图片
![image](https://github.com/user-attachments/assets/75abab26-ffbc-4470-a734-5a447699d7ff)类似于这样没确定前还是可以调整啥的
