### ISSUE TITLE
希望 快速制卡 支持指定更多的内容快和快捷键

### ISSUE THREAD

**Issue by holduan** [siyuan-note/siyuan#12330]
### In what scenarios do you need this feature?

需要 列表项块 支持快速制卡，因为合并列表后，列表项块制作的闪卡不会失效。整个列表 `快速制卡` 也需要。

### Describe the optimal solution

-

**Comment by TCOTC** [comment]
制卡是有快捷键的

![image](https://github.com/user-attachments/assets/1a718e83-bd7a-47a8-bde3-85483f11bd53)

只需要 Shift+↑ 选中对应的块再使用快捷键即可

**Comment by holduan** [comment]
> 制卡是有快捷键的
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/361186422-1a718e83-bd7a-47a8-bde3-85483f11bd53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NjQwOTMsIm5iZiI6MTcyNDU2Mzc5MywicGF0aCI6Ii83ODQzNDgyNy8zNjExODY0MjItMWE3MThlODMtYmQ3YS00N2E4LWJkZTMtODU0ODNmMTFiZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA1Mjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MzU0NjRjMWFmMjVjNGM5NmZkMzY2NTVmM2IxZDExMWQ2ODljNzQ2MDYwZjE2ZGNkMGRkMDgzYzdjNGI0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.acfQEq9r7SMJgV-nz96M_SA9E_JSfStJuhtJeLxII5Y)
> 
> 只需要 Shift+↑ 选中对应的块再使用快捷键即可

大佬6啊，这些快捷键平时都没关注。不过用这个操作至少要两次 `Shift+↑` 然后 `Ctrl+Shift+F`，要换右手，不如鼠标点击 `列表项块` 然后 `Ctrl+Shift+F` 便捷。

**Comment by 88250** [comment]
没有问题的话我们关闭了，谢谢。

**Comment by holduan** [comment]
> 没有问题的话我们关闭了，谢谢。

有问题，只读的文档做闪卡就不能用上面的提到的方法了，移动端上更麻烦，希望 `快速制卡` 支持指定更多的内容块以及支持快捷键，谢谢

**Comment by TCOTC** [comment]
只读的文档不能编辑，不能制作闪卡

**Comment by holduan** [comment]
只读也可以，快速制卡 快捷键可以制作闪开的

Jeffrey Chen ***@***.***> 于 2024年8月31日周六 00:24写道：

**Comment by holduan** [comment]
> 只读的文档不能编辑，不能制作闪卡

只读也可以用 快速制卡

**Comment by TCOTC** [comment]
确实哦，可以用快捷键。

@88250 这个是符合预期的吗？

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
感觉可以治卡会更方便一些。
