### ISSUE TITLE
支持内容块删除、剪切

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1233]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/105526726-beb68700-5d1d-11eb-8626-aef4cd9cf1aa.png)
如图，我右键一个代码块的符标后显示的选项：没有删除块和剪切块的功能

当块的选中相对麻烦时候 希望 能右键后 对块做 删除或剪切的功能
**比如块内容比较多，拖动鼠标选中就比较低效**

**剪切块的 频率 比 现有的复制块功能的频率要更高**
因为 在双链中，重复的内容 通常是用双链进行引用，而不是复制到多个位置
多数情况复制都是为了进行剪切

### 描述最优的解决方案 Describe the optimal solution

块符标 右键 提供 删除块，剪切块 功能

**Comment by Vanessa219** [comment]
移除可使用
![image](https://user-images.githubusercontent.com/970828/106110375-95ff1900-6185-11eb-805e-1c0495bd09f7.png)
剪切可右键
![image](https://user-images.githubusercontent.com/970828/106110419-a616f880-6185-11eb-966c-90af645f434e.png)
