### ISSUE TITLE
查找与替换无法替换行级公式以及公式块的内容

### ISSUE THREAD

**Issue by phoenixsfly** [siyuan-note/siyuan#12331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在[#3392](https://github.com/siyuan-note/siyuan/issues/3992)中提到搜索替换功能支持元素包括行级公式、公式块，但是目前我的编辑器版本v3.1.3使用中发现存在可以搜索但是无法替换的现象，例如如下文本：

>这是一个测试文本$\alpha$，无法替换latex公式$\beta$
>\alpha_2+\beta_3+\alpha4=1

按CTRL +  R 搜索“\alpha”，替换为“\gamma”，选择全部替换后，编辑器刷新，但是本文并未发生替换
开始考虑是否是转义符的问题，于是去掉转义符，搜索“alpha”替换为“gamma”，选择全部替换，编辑器刷新，但是文本仍未发生替换
![image](https://github.com/user-attachments/assets/86e18d77-7b10-457d-8432-a9121205228b)

### Expected result

公式能够正确被替换

### Version environment

```markdown
- Version: v3.1.3
- Operating System: windows 11
- Browser (if used):
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/08/25 15:51:16 runtime.go:74: kernel is booting:
    * ver [3.1.2]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [5656]
    * runtime mode [prod]
    * working directory [C:\Users\z\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\z\Documents\SiYuan]
I 2024/08/25 15:51:16 conf.go:125: loaded conf [C:\Users\z\Documents\SiYuan\conf\conf.json]
I 2024/08/25 15:51:16 runtime.go:123: use network proxy [system]
I 2024/08/25 15:51:16 serve.go:127: kernel [pid=5656] http server [127.0.0.1:2732] is booting
I 2024/08/25 15:51:16 conf.go:835: database size [118.79 kB], tree/block count [1/4]
I 2024/08/25 15:51:16 working.go:193: kernel booted
I 2024/08/25 15:51:16 pandoc.go:146: built-in pandoc [ver=3.1.1, bin=C:\Users\z\Documents\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/08/25 15:51:16 conf.go:1099: pandoc initialized, set pandoc bin to [C:\Users\z\Documents\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/08/25 15:51:16 box.go:77: auto stat [trees=1, blocks=4, dataSize=3.21 MB, assetsSize=2.05 MB]
I 2024/08/25 15:51:16 disk.go:33: disk usage [total=450.24 GB, used=311.71 GB, free=138.53 GB]
I 2024/08/25 15:51:17 fixedport.go:35: fixed port service [127.0.0.1:6806] is running

**Comment by TCOTC** [comment]
选择对应的替换类型了吗？

![image](https://github.com/user-attachments/assets/9b5fc5ec-3530-4b0c-b1e6-049f92232655)

**Comment by phoenixsfly** [comment]
> 选择对应的替换类型了吗？
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/361199033-9b5fc5ec-3530-4b0c-b1e6-049f92232655.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDA4MDksIm5iZiI6MTcyNDYwMDUwOSwicGF0aCI6Ii83ODQzNDgyNy8zNjExOTkwMzMtOWI1ZmM1ZWMtMzUzMC00YjBjLWIxZTYtMDQ5ZjkyMjMyNjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE1NDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MDI4MzczZTczODNkMzliZmFkMzJhYjdmMDRmOWM0MTdmMTk5MTUyODY0NzQyOGNhMzVjZjljNjY5OTNhNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_KdEmTpZYJYg-fMM3uhG8Q8eq6uzMLxAb8hlajiUsY)

原来如此，问题已解决
搜索类型和替换类型默认居然不一致🤐

**Comment by 88250** [comment]
没有问题的话我们关闭了，谢谢。
