### ISSUE TITLE
弹出window默认对话框时窗口失去焦点，之后所有输入框都获取不到焦点

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12349]
在控制台执行：

```js
setTimeout(function(){alert("111");},5000);
```

然后关闭开发者工具……：

https://github.com/user-attachments/assets/73939eda-78bf-4bd0-92bf-812d47325ce3

查到一点相关的：

[关于使用electron使用alert失去文本框焦点无法选中的问题_electron alert-CSDN博客](https://blog.csdn.net/HQqHQhqqhq/article/details/128315452)
[electron app弹出默认对话框后页面失去焦点问题 - 潜水的阳光 - 博客园](https://www.cnblogs.com/yinliang/p/12175076.html)

**Comment by Vanessa219** [comment]
用户使用 showMessage 替代 alert 就可以了。

**Comment by TCOTC** [comment]
@zxkmm

**Comment by zxkmm** [comment]
因为火狐不兼容那个新的css高亮api，我要用alert 和confirm，这两个可以在思源没有进主界面之前工作，避免暴露用户的隐私。不过但是如果不行就算了，反正我的插件也没人用。

**Comment by Vanessa219** [comment]
兼容 Chrome 就可以了，火狐用的人少。

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/pull/16073
