### ISSUE TITLE
不需要提示 `新增行不参与排序`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12342]
实际上在条目添加了之后马上就会排序：

[视频.webm](https://github.com/user-attachments/assets/73042054-88ae-405d-9480-e85643fbf6c7)

[视频.webm](https://github.com/user-attachments/assets/20faba1f-5a5b-431c-94b5-0e54345446d0)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
