### ISSUE TITLE
数据历史 - 文件历史 支持调整标题宽度

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12347]
https://ld246.com/article/1724738234541

如果文件名长的话不方便查看（尤其是有前缀的情况）：

![image](https://github.com/user-attachments/assets/032663be-baf6-4009-8a65-49df22106ff3)

![image](https://github.com/user-attachments/assets/93c7c210-c599-47c2-8077-ce1c8234aa13)

**Comment by 88250** [comment]
这个不持久化了吧。

改动不拉入版本了。

**Comment by Vanessa219** [comment]
宽度已经持久化了，改动点包括文档历史、数据历史、历史对比及UI，因此还是拉入版本。
