### ISSUE TITLE
批量修改块的样式功能

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#1234]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
当我们在对文档内容进行梳理的时候，会对文档的块进行样式调整，比如打标题等，目前的工具栏很鸡肋，例如对于标题只能一个一个的修改起作用，这样比如直接敲键盘。
### 描述最优的解决方案 Describe the optimal solution
当选择中多个块时，选择某个样式，所有块应用该样式，这样可以大大提高效率。
-->

**Comment by 88250** [comment]
你好，你指的样式主要是颜色这个么？

**Comment by GlowBlur** [comment]
@88250 主要是标题设置和批量的设置项目列表等

**Comment by 88250** [comment]
现在只能转换第一个是个 bug，请关注 #132 

我应该没理解错你提的需求吧……

**Comment by GlowBlur** [comment]
@88250 有点类似那个bug，就是比如我选中多段文字，我要把它们全设成标题，那么只有第一个起作用，这样还不不如直接代码操作快

**Comment by 88250** [comment]
好的，那就没问题了，我关闭这个了，后面在那边处理，谢谢。
