### ISSUE TITLE
改进数据库条目更新时间和创建时间字段值 Improve database updated and created column values

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12345]
### 条目更新时间

目前在数据库中绑定块条目的 `更新时间` 是与绑定块本身的更新时间同步的，而非绑定块条目使用的是行时间：

> 有绑定块的时候使用块的时间，没有的时候使用行时间。(来源:  [#9391](https://github.com/siyuan-note/siyuan/issues/9391) 、[链滴](https://ld246.com/article/1696932771024/comment/1696943559858#comments) )

也就是说，修改非绑定块条目的字段之后会刷新 `更新时间` ，而修改绑定块条目的字段之后 `更新时间` 会保持不变。

同样是修改条目字段，但结果不同，就会导致在排序和筛选条目时产生不一致的逻辑，以排序为例：

* 如果数据库中只有非绑定块条目，那么在数据库使用更新时间降序时一切都正常：**最后修改字段的条目始终会排在最上方**。
* 如果非绑定块条目 A 和绑定块条目 B 混用，排序的逻辑就会混乱，比如：先修改 A 条目的字段（A 条目的 `更新时间` 刷新），再修改 B 条目的字段（B 条目的 `更新时间` 保持不变），此时数据库使用更新时间降序，**就会把最后修改字段的 B 条目排在最先修改字段的 A 条目下方**，不能真实地反应条目修改的时间先后。

从直觉上讲，如果在数据库中排序和筛选条目，是管理整个条目而不是只管理其主键绑定块， `更新时间` 应该是整个条目的更新时间（也就是最后一次编辑条目字段的时间）。

再考虑到条目可以绑定块，修改块内容基本等同于修改条目主键(content)，所以一共有两种情况应该刷新条目的 `更新时间` （**Notion 的数据库也是这个逻辑**）：

1. 编辑条目的某个字段值之后（对于绑定块条目和非绑定块条目），刷新该条目的 `更新时间`
2. 编辑条目的绑定块本身之后（对于绑定块条目），刷新该条目的 `更新时间`

### 修改绑定块

修改绑定块会修改条目的更新时间和创建时间，这个逻辑也有问题。

修改绑定块时（包括：创建新文档、绑定已经存在的块、取消绑定块），条目本身的 `创建时间` 应该保持不变；修改主键相当于修改字段值，所以条目的 `更新时间` 应该刷新为修改主键那一刻的时间。

**保证条目的 `创建时间` 固定、`更新时间` 单向增长**，排序和筛选就不会混乱，也就不会出现「更换绑定块之后，`更新时间` 大幅变化」「取消绑定块之后 `更新时间` 倒退」之类的不合理情况了：

[视频.webm](https://github.com/user-attachments/assets/beb08575-5635-4291-af53-f196bb4aa228)

**Comment by Hzz-0802** [comment]
支持

**Comment by 88250** [comment]
这是个特性，不考虑改变了。

绑定块和非绑定块建议不要混用，因为这两者存在不同的使用场景。

**Comment by TCOTC** [comment]
绑定块和非绑定块必然是混用的，很多情况下是先记录纯文本，等到需要的时候再创建新文档

**Comment by 88250** [comment]
所以只是建议

**Comment by TCOTC** [comment]
用户不是这样用的，那就应该改思源本身的逻辑

**Comment by 88250** [comment]
块更新时间是有较多需求才改成目前这样的，所以不考虑再改变了。

**Comment by TCOTC** [comment]
那就再增加一个 `条目更新时间` 字段？否则没办法满足需求。

在 Notion 的 Database 和飞书的多维表里，都有一个字段是条目的更新时间

**Comment by 88250** [comment]
维持现有设计不变了。

**Comment by Temacc0531** [comment]
> 绑定块和非绑定块必然是混用的，很多情况下是先记录纯文本，等到需要的时候再创建新文档。

搞成两个表单独管理绑定和非绑定的？😂
