### ISSUE TITLE
Add a new api '/api/filetree/getPathByID'

### ISSUE THREAD

**Issue by ytm157** [siyuan-note/siyuan#12352]
### In what scenarios do you need this feature?

没有合适的接口可以直接根据 ID 删除 doc，看了下 siyuan 的源代码，发现前端是通过 listDocsByPath 接口取到 path，把 path 存入到 `<li>` 节点中的 data-path 属性中。在删除的时候直接取 `<li>` 里的 data-path 然后通过 removeDoc 接口删除。

而 removeDoc 这个接口只支持传入 path 不支持传入 id，在需要直接使用接口删除某个 doc 时较为麻烦。

### Describe the optimal solution

建议新增一个接口 /api/filetree/getPathByID，可以根据 id 获取到 doc 的实际存储路径，然后可以将该路径传入 removeDoc 接口中。

代码已提交 https://github.com/ytm157/siyuan/commit/33a927e5d5d58124ba17b8f57188862d9f8ddc99 ，如果 OK 的话将发起一个PR。

**Comment by 88250** [comment]
已经合并，感谢贡献。
