### ISSUE TITLE
虚拟引用的功能优化

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12358]
### In what scenarios do you need this feature?

# 开这个issue的原因

最近在写推荐思源的文章，其中介绍思源强大的虚拟引用特性、支持块引用的图谱特性、高性能的搜索以及最核心的块特性，开这个issue提一下发现的问题，希望帅气的D大和美丽的V姐考虑一下

# 遇到的问题

## 问题1 块样式与虚拟引用的冲突

- 块样式作为思源最核心的块特性的一部分，也是文档编辑中需求量很大且必不可少的。
- 虚拟引用作为思源的特色功能，也是很好用很重要的。

但是目前虚拟引用只支持纯文本导致了一个问题，核心特性和特色功能之间存在一定的冲突，也就是说用户在编辑文档时只能二选一。

不论我如何推荐思源的块和虚拟引用，最后用户尝试时一定会发现这个问题。

## 问题2 虚拟引用的手动刷新

思源虚拟引用的强大是毋庸置疑的，但为了性能禁用自动刷新并改为手动刷新的打断感是非常强的，与思源其他方面的高性能（比如搜索）形成了强烈的落差感，另外f5后的页面闪烁很难受。

### Describe the optimal solution

对于问题1，希望d大能考虑 虚拟引用 对块样式的兼容，即使是以纯文本检索块内容后，在 `::after` 中额外绘制一个虚拟引用虚线

对于问题2，希望d大能考虑 添加一个设置项用于启用定时刷新，拥有性能比较好的设备的用户可以自行开启。

**Comment by 88250** [comment]
1. 这是设计如此，虚拟引用只作用于纯文本元素上，因为非纯文本元素已经赋予语义了（比如加粗、斜体等），所以不再叠加虚拟引用
2. 这个没有办法了，只能手动刷新渲染

感谢反馈。

**Comment by TCOTC** [comment]
可以用番茄工具箱插件，能在顶栏添加一个刷新虚拟引用的按钮：

![image](https://github.com/user-attachments/assets/22b5f037-fd60-499e-936e-f7ec168dee5c)

**Comment by KuiyueRO** [comment]
谢谢！这就去下

**Comment by KuiyueRO** [comment]
还是希望d大考虑下虚拟引用的优化

![Screenshot_20240924_134048_org.b3log.siyuan.jpg](https://github.com/user-attachments/assets/8f59dd42-a194-496e-a806-5917ba9c4788)

我的意思并非是实现跨元素/子元素的虚拟引用，只是希望在已有语义的元素内部再进行一次虚拟引用的判定。

不然想搞点花里胡哨的页面，在思源中制作某个小说的wiki之类的，虚拟引用这么好用的功能就失效了。

**Comment by TCOTC** [comment]
> 在已有语义的元素内部再进行一次虚拟引用的判定

我也认为这个是比较合理的

**Comment by Wetoria** [comment]
为行内元素设置样式的语义，不足以与虚拟引用的语义进行区分对待。

至少对于加粗、斜体、下划线、删除线、字体大小、颜色、背景色这一批内容来说，它们所附带的语义，是不足以“覆盖”掉虚拟引用的语义的。

而标记，由于介入了闪卡，因此不参与虚拟引用的识别，这个可以理解。

上标、下标也有自己的适用场景，比如尾链、化学符号等，也可以不参与。

行内代码、公式、备注、标签、键盘这些也可以、并且也不应该参与虚拟引用。

对于加粗、斜体、字体大小、颜色、背景色这五项增加虚拟引用的判定，我认为算是合理的。

下划线、删除线这两项可能还需要再商议。

**Comment by Tisamn** [comment]
> 1. 这是设计如此，虚拟引用只作用于纯文本元素上，因为非纯文本元素已经赋予语义了（比如加粗、斜体等），所以不再叠加虚拟引用
> 2. 这个没有办法了，只能手动刷新渲染
> 
> 感谢反馈。

D大，那能否实现：虚拟引用的样式直接覆盖类似加粗这样的非纯文本元素呢？以前加粗或者更改样式以突出标记的文字，某天建立了一个相关的主题文档后，无法实现在不建立引用的前提下，通过这些“被标记的文字”直接查看该主题文档。
如果虚拟引用的样式可以对以前“被标记的文字”进行覆盖，那么对该文字可以同时起到突出标记和直接查看相关的主题文档的作用，个人认为一举两得，是对虚拟引用这一功能的增强，此外可以将其作为一个选择性的功能，由使用者自主决定是否在设置中选择开启或关闭。

**Comment by TCOTC** [comment]
> 在已有语义的元素内部再进行一次虚拟引用的判定

@88250
