### ISSUE TITLE
Keep the outline expanded and collapsed

### ISSUE THREAD

**Issue by Richardggm** [siyuan-note/siyuan#1235]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

当文件较大时，大纲的层次较多，展开折叠大纲会比较费力。所以如果有记忆功能，在下次打开同一个文件的时候，还是之前的展开折叠状态，就会方便很多。

**Comment by 88250** [comment]
这是一个很好的建议，我们后面会尽量实现的，非常感谢。

**Comment by 88250** [comment]
v1.2.0 已经支持折叠/展开全部，记忆功能暂时不支持，看后续需求，谢谢。
