### ISSUE TITLE
移动端删除工作空间没有经过确认

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12351]
https://github.com/user-attachments/assets/f1072261-04a0-49c3-ad8d-43e6fac75a60

p.s. 再次新建同名工作空间可以恢复

**Comment by 88250** [comment]
这是设计如此，只有物理删除时弹确认框。

**Comment by TCOTC** [comment]
用户反馈：[手机端删除空间无法取消 - 链滴](https://ld246.com/article/1728738877901)

说明这个还是有歧义，我建议改改文案。比如：

> ⚠️彻底删除操作确认
>
> 工作空间已在列表中移除，是否需要再彻底删除工作空间 /storage/emulated/0/Android/data/org.b3log.siyuan/files/123 的数据？（物理删除数据，无法恢复）
>
> 　　　　　　　　　　　　　　　　　取消　　　　 确定

**Comment by 88250** [comment]
欢迎 PR
