### ISSUE TITLE
数据库提供更丰富的筛选规则

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#12365]
### In what scenarios do you need this feature?

数据库筛选默认规则是or（满足一项规则即生效），不能设置成and（所有规则都满足），用起来很不方便，希望数据库提供更丰富的筛选规则。
比如我有三列勾选框，我想筛选没有全部完成三项的条目，呈现结果确实只要有一项完成就不会显示该条目，导致期望显示的条目遗漏。

### Describe the optimal solution

如果能提供筛选规则选项（图1），或者直接上条件组就更好了（图2）。

![2`R`@{SC8M3RV EO`6`AY$8](https://github.com/user-attachments/assets/1194fff1-9aad-4c59-b5ef-56fd354030f3)

![L4ACW$S$Q JI92P4P(O@8}5](https://github.com/user-attachments/assets/0403539d-ec1e-44e3-9193-a9f9e73d8ce3)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10550
