### ISSUE TITLE
只读模式下按 Ctrl+C 无法复制代码块内的文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12369]
https://ld246.com/article/1725097764864

p.s. 0:03 的时候按了一下 `Ctrl+C`

[视频.webm](https://github.com/user-attachments/assets/38e36497-cb12-4a95-9d1f-3c9cf42eee51)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
