### ISSUE TITLE
新建超链接自动拉取网页标题

### ISSUE THREAD

**Issue by EndlessErrors** [siyuan-note/siyuan#1236]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

当剪切板有超链接时，在空白处按`Ctrl+K`添加超链接，链接文本为空白，希望在这种情况下能够自动拉取网页标题，并将编辑光标设置为全选中抓取到的网页标题，方便自定义。
![图片](https://i.loli.net/2021/01/23/xBoXsN6flDZyAUR.png)

**Comment by 88250** [comment]
你好，抓取估计会比较耗时（类似图片拉取功能）而且不太稳定，先不考虑引入，感谢提议。

https://github.com/siyuan-note/siyuan/issues/1020#issuecomment-761526071
