### ISSUE TITLE
导出PDF，第一页空白，第二页才是内容

### ISSUE THREAD

**Issue by AZmake** [siyuan-note/siyuan#12366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

新建任意文档，写入任意带标题的内容，导出PDF，第一页空白，第二页才是内容

### Expected result

第一页非空白

### Version environment

```markdown
- Version: v3.1.4
- Operating System: mac os sonoma 14.1.1
- Browser (if used):
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/08/30 16:40:43 runtime.go:74: kernel is booting:
    * ver [3.1.4]
    * arch [arm64]
    * os [darwin]
    * pid [12350]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/abc/Desktop/notepad/siyuan]
I 2024/08/30 16:40:43 conf.go:125: loaded conf [/Users/abc/Desktop/notepad/siyuan/conf/conf.json]
I 2024/08/30 16:40:43 runtime.go:123: use network proxy [system]
I 2024/08/30 16:40:43 serve.go:127: kernel [pid=12350] http server [127.0.0.1:54825] is booting
I 2024/08/30 16:40:43 conf.go:838: database size [200.37 MB], tree/block count [382/33353]
I 2024/08/30 16:40:43 working.go:193: kernel booted
I 2024/08/30 16:40:43 pandoc.go:146: built-in pandoc [ver=3.1.1, bin=/Users/abc/Desktop/notepad/siyuan/temp/pandoc/bin/pandoc]
I 2024/08/30 16:40:43 conf.go:1100: pandoc initialized, set pandoc bin to [/Users/abc/Desktop/notepad/siyuan/temp/pandoc/bin/pandoc]
I 2024/08/30 16:40:43 box.go:77: auto stat [trees=382, blocks=33353, dataSize=233.89 MB, assetsSize=217.31 MB]
I 2024/08/30 16:40:43 disk.go:33: disk usage [total=245.11 GB, used=197.23 GB, free=47.88 GB]
I 2024/08/30 16:40:44 fixedport.go:35: fixed port service [127.0.0.1:6806] is running

**Comment by TCOTC** [comment]
是与 #11258 类似的问题

**Comment by 88250** [comment]
使用的是默认主题并且没有开启插件和代码片段吗？

**Comment by 88250** [comment]
缺少进一步信息，我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:
