### ISSUE TITLE
复制粘贴和剪藏兼容五彩插件划线

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12362]
01 划线部分粘贴不出来：

https://ld246.com/article/1724987198549

![image](https://github.com/user-attachments/assets/de8e9929-c8a0-4c23-b8d8-04dfe284e17f)

![image](https://github.com/user-attachments/assets/bae6cdef-b6aa-48c1-a484-c1a69c24b8c5)

HTML：

```html
<article class="vditor-reset article-content" data-link="https://ld246.com/article/1724987198549" data-author="wzsh">
<p>
    <markerow8 data-id="snLt" data-pkid="5254818" class="wucaiclrx1" style="color: rgb(0, 0, 0); background-color: rgba(244, 220, 97, 0.698);">五彩高亮划线部分无法复制粘贴，没有高亮的都是可以正常复制粘贴。见视频。</markerow8>
</p>
<p>其他笔记的编辑器都是正常的，无论 wolai，word，wps 等等。</p>
</article>
```

02 剪藏的时候如果里面有 strong 之类的元素，只能剪藏出没有行级样式的纯文本

**Comment by 88250** [comment]
1. 不考虑支持自定义标签了
2. 需要给一个示例页面才好分析

我先关闭 issue，欢迎随时补充信息。

**Comment by 88250** [comment]
收到，稍后改进。

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
