### ISSUE TITLE
在插件市场里加一个‘反馈’按钮，跳转到 issue

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#12364]
### In what scenarios do you need this feature?

总是有人在群里或者集市里面咨询插件使用的问题，我感觉可能很多用户是不知道有 issue 这个东西的。

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/5b275b18-153c-4f00-bacc-8e2d5b792221)

或许可以增加一个明确的「反馈」按钮或者链接，直接跳转到 issue。

**Comment by 88250** [comment]
加了个 反馈 按钮：

![image](https://github.com/user-attachments/assets/26f2a38a-a98c-4755-8f9b-d70a5b24e233)

这个改动不拉入版本了，感谢提议。
