### ISSUE TITLE
自3.07版本之后加入了网络认证以及升级了GLIBC,CentOS7.9已经无法正常打开Appimage

### ISSUE THREAD

**Issue by chantsing** [siyuan-note/siyuan#12377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

自3.07版本之后加入了网络认证以及升级了GLIBC版本,CentOS7.9已经无法正常打开Appimage
请问能否继续支持CentOS7.9,并且电脑不允许联网，新版本的思源笔记没法打开使用。

### Expected result

请问如何关闭思源笔记的网络验证，更老版本的CentOS也能正常打开使用

### Version environment

```markdown
- Version: 
3.08 or later
- Operating System: 
CentOS 7.9 without root
- Browser (if used):
```

### Log file

没法打开软件，日志文件好像是没有记录的，不上传了
![IMG_20240802_093843](https://github.com/user-attachments/assets/633ee16b-e91e-497d-8735-ba44af8eb558)
![IMG_20240802_093933](https://github.com/user-attachments/assets/f9004112-37bb-4d95-9d4c-b6ee0d03af2d)
[Uploading siyuan.log…]()

### More information

![IMG_20240802_093933](https://github.com/user-attachments/assets/7e83ddd1-3032-465b-b830-0ddcb4d47655)

![IMG_20240802_093843](https://github.com/user-attachments/assets/2c8180ca-3240-4977-a5fb-c04bd6ad5773)
![IMG_20240802_093933](https://github.com/user-attachments/assets/7e83ddd1-3032-465b-b830-0ddcb4d47655)

**Comment by 88250** [comment]
你好，不太清楚你提到的 网络认证 是啥，麻烦描述一下；目前最低需要 glibc 2.31，如果还不满足的话只能自己尝试编译了。

我先关闭 issue 了，谢谢。
