### ISSUE TITLE
docker部署的思源服务,在更新版本后,之前的笔记找不到了

### ISSUE THREAD

**Issue by Trihs** [siyuan-note/siyuan#12375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我把思源通过docker部署在自己的一个小云服务器上,今天更新了最新的版本,更新是成功了,但是之前记录的笔记以及工作空间找不到了,是被覆盖掉了么?还是说可以通过配置路径来找回

### Expected result

希望找回之前记录的笔记以及工作空间

### Version environment

```markdown
- Version: v3.1.4
- Operating System: Ubuntu22.04
- Browser (if used):
```

### Log file

/merged/home/siyuan/SiYuan/temp/siyuan.log

I 2024/09/02 09:31:32 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/09/02 09:31:32 runtime.go:74: kernel is booting:
    * ver [3.1.4]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/home/siyuan/SiYuan]
D 2024/09/02 09:31:32 conf.go:166: check device locale failed [detect: not detected], using default language [en_US]
I 2024/09/02 09:31:32 runtime.go:123: use network proxy [system]
I 2024/09/02 09:31:32 serve.go:127: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/09/02 09:31:32 blocktree.go:75: reinitialized database [/home/siyuan/SiYuan/temp/blocktree.db]
I 2024/09/02 09:31:32 database.go:92: the database structure is changed, rebuilding database...
I 2024/09/02 09:31:32 database.go:109: reinitialized database [/home/siyuan/SiYuan/temp/siyuan.db]
I 2024/09/02 09:31:32 conf.go:838: database size [4.1 kB], tree/block count [0/0]
I 2024/09/02 09:31:32 working.go:193: kernel booted
I 2024/09/02 09:31:32 box.go:77: auto stat [trees=0, blocks=0, dataSize=36.87 kB, assetsSize=0 B]
I 2024/09/02 09:32:47 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
I 2024/09/02 09:32:50 index.go:220: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.07s], tree [count=67, size=1.25 MB]
I 2024/09/02 09:32:50 index.go:290: resolved refs [36] in [49ms]
I 2024/09/02 09:41:12 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
W 2024/09/02 09:41:32 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist
W 2024/09/02 09:51:32 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist
I 2024/09/02 10:08:55 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
W 2024/09/02 10:08:55 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist
I 2024/09/02 10:08:58 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
W 2024/09/02 10:11:32 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist

---
/diff/home/siyuan/SiYuan/temp/siyuan.log

I 2024/09/02 09:31:32 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/09/02 09:31:32 runtime.go:74: kernel is booting:
    * ver [3.1.4]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/home/siyuan/SiYuan]
D 2024/09/02 09:31:32 conf.go:166: check device locale failed [detect: not detected], using default language [en_US]
I 2024/09/02 09:31:32 runtime.go:123: use network proxy [system]
I 2024/09/02 09:31:32 serve.go:127: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/09/02 09:31:32 blocktree.go:75: reinitialized database [/home/siyuan/SiYuan/temp/blocktree.db]
I 2024/09/02 09:31:32 database.go:92: the database structure is changed, rebuilding database...
I 2024/09/02 09:31:32 database.go:109: reinitialized database [/home/siyuan/SiYuan/temp/siyuan.db]
I 2024/09/02 09:31:32 conf.go:838: database size [4.1 kB], tree/block count [0/0]
I 2024/09/02 09:31:32 working.go:193: kernel booted
I 2024/09/02 09:31:32 box.go:77: auto stat [trees=0, blocks=0, dataSize=36.87 kB, assetsSize=0 B]
I 2024/09/02 09:32:47 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
I 2024/09/02 09:32:50 index.go:220: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.07s], tree [count=67, size=1.25 MB]
I 2024/09/02 09:32:50 index.go:290: resolved refs [36] in [49ms]
I 2024/09/02 09:41:12 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
W 2024/09/02 09:41:32 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist
W 2024/09/02 09:51:32 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist
I 2024/09/02 10:08:55 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
W 2024/09/02 10:08:55 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist
I 2024/09/02 10:08:58 serve.go:232: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0]
W 2024/09/02 10:11:32 history.go:590: history dir [/home/siyuan/SiYuan/history] not exist

**Comment by 88250** [comment]
需要挂载数据卷。
