### ISSUE TITLE
Code blocks are not syntax highlighted when exporting to PDF/image/HTML

### ISSUE THREAD

**Issue by M2uyo** [siyuan-note/siyuan#12378]
导出支持代码高亮

### In what scenarios do you need this feature?

经尝试 导出 PDF 图片 HTML 均无代码高亮
代码高亮对于代码来说还是蛮重要的, 在阅读体验上也不在一个层次上, 
所以希望D大支持下 导出后的文件支持代码高亮

### Describe the optimal solution

语雀的PDF导出支持代码高亮 如下图(语雀导出的PDF文件)
![image](https://github.com/user-attachments/assets/16990d34-bd22-4d72-829d-e7d4b555ed73)

**Comment by TCOTC** [comment]
我可以复现，导出预览是没有代码高亮的：

![image](https://github.com/user-attachments/assets/08723ef7-9b4b-41f3-9c9e-62828320ad8f)

另外关联：#11456

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/commit/1989ade24dbb2e4d24068604b39064b305f513a4
