### ISSUE TITLE
There is an additional whitespace after this character: ’

### ISSUE THREAD

**Issue by kendofriendo** [siyuan-note/siyuan#12370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When pasting text that contains an "inverted comma" (’) into Siyuan's editor, it is rendered together with an additional blank space character.
```
’ 
```

### Expected result

it should be rendered as a single charcter:

```
’
```

or converted to apostrophe

```
'
```

### Screenshot or screen recording presentation

How Siyuan renders the text:
![image](https://github.com/user-attachments/assets/ded8a549-e67b-42b5-bdf9-dcba69abf3bb)

How the text should be rendered:
![image](https://github.com/user-attachments/assets/08fa5a89-e92c-4f43-887a-bd58d2a490f8)

### Version environment

```markdown
- Version: 3.1.4
- Operating System: Windows 11
- Browser (if used): Chrome
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16825168/siyuan.log)

**Comment by 88250** [comment]
Hello, I have tested it with the default theme and default font and it works fine. Please check the relevant configuration.

![image](https://github.com/user-attachments/assets/2c8e985c-833d-477b-89bf-f9fa14fabc3c)
