### ISSUE TITLE
Implement insensitive case via Sqlite fts5 tokenizer.

### ISSUE THREAD

**Issue by yb6b** [siyuan-note/siyuan#12371]
### In what scenarios do you need this feature?

思源笔记处理英文字母大小写的办法目前是用两个fts5索引表，一个原版，一个全小写的。导致双倍磁盘占用。

### Describe the optimal solution

我读到微信团队的[文章](https://cloud.tencent.com/developer/article/2220615)，提到可以用[自定义tokenizer](https://www.sqlite.org/fts5.html#custom_tokenizers)的办法处理大小写。这需要写个C/C++的动态链接库。github上有个[类似的仓库](https://github.com/wangfenjin/simple)，它能区分大小写，能输入拼音反查等。C++代码的核心是 [tokenize](https://github.com/wangfenjin/simple/blob/a9234eb7169d98522ff07f42e0e9f9aa603bbebd/src/simple_tokenizer.cc#L104) 方法。

微信有个开源的[WCDB](https://github.com/Tencent/wcdb/wiki)项目，针对大型sqlite数据库的全文搜索优化，还能数据加密压缩。

不过思源的kernel改起来颇为困难。同时涉及C++，跨平台也是个挑战。不知D大意见如何？

**Comment by 88250** [comment]
> 我读到微信团队的[文章](https://cloud.tencent.com/developer/article/2220615)，提到可以用[自定义tokenizer](https://www.sqlite.org/fts5.html#custom_tokenizers)的办法处理大小写。

文章中好像没有提到可以只用一个库就支持大小写敏感吧？我只看到提到这个：

> 第五，支持将字母全部转成小写。这样用户可以用小写搜到大写，反之亦然。

这样的话只能实现大小写不敏感，不能实现大小写敏感。

**Comment by yb6b** [comment]
谢谢D大的提醒，确实不容易在查询时动态的区分大小写。思源已经用了tokenizer的技术了。

能不能只建一个fts5虚拟表，这个表含有 区分大小写和全小写的blocks列。查询时，在业务代码里切换列并且转成小写字母去除字母的帽子？

**Comment by 88250** [comment]
之前考虑过这个方案的，但是测试下来存储占用不会少太多，因为主要就是 content 占用，其他字段占用很小的。

**Comment by yb6b** [comment]
是的，content占用大。

这样只能深入地魔改sqlite了。

或者考虑二次过滤的办法，先得到不区分大小写的块，然后在业务代码里判断大小写。二次过滤还可以间接地实现 正则表达式搜索。

有个不情的问题：是否真的需要全文搜索索引？单机应用不需要毫秒之间出结果。譬如vscode的项目搜索，底层用ripgrep，它是遍历所有文件的，速度可以接受了。obsidian的搜索也是遍历。

**Comment by 88250** [comment]
在没有更好的方案前就不考虑改变了，vscode/obsidian 是基于文本文件（比如可以按行列定位），但是 SiYuan 无法基于文件，所以必须进行数据索引才能更好地为用户提供搜索功能。

这个 issue 我关闭了，如果后面还有方案，欢迎随时跟帖讨论，谢谢。
