### ISSUE TITLE
从思源笔记引出的链滴论坛链接，允许不登陆阅读。

### ISSUE THREAD

**Issue by yb6b** [siyuan-note/siyuan#12376]
### In what scenarios do you need this feature?

在《思源笔记用户指南》里，有下面几个链接是需要登录才能阅读的：
1. [缘起](https://ld246.com/article/1619868273581)
2. 社区资源
    * [思源笔记快乐手册](https://ld246.com/article/1668217980464)
    * [我的 dailynote 流程](https://ld246.com/article/1658109483457)
    * [使用虚拟引用功能阅读超长篇小说《冰与火之歌》](https://ld246.com/article/1679134353655)
    * [实践中对双链和写作的一些思考](https://ld246.com/article/1633719399031)
    * [一次漫游：学习中的快乐与束缚](https://ld246.com/article/1681801981651)
3. [思源 Chrome 扩展](https://ld246.com/article/1629423901669)
4. [思源笔记技术架构](https://ld246.com/article/1619868273581#%E6%8A%80%E6%9C%AF%E6%9E%B6%E6%9E%84)

此外，旧版本的更新日志也会使用链滴论坛的链接。

### Describe the optimal solution

针对这些帖子，可否给个特权，允许不登录阅读？

**Comment by 88250** [comment]
这个暂时不考虑改变了，感谢反馈。
