### ISSUE TITLE
Database views support from other pages?

### ISSUE THREAD

**Issue by dvsekhvalnov** [siyuan-note/siyuan#12373]
### In what scenarios do you need this feature?

Hi guys, sorry if it has been asked before, hard to search issues in Chinese.

Is it possible to reference database from another page? E.g. let's say you have `action items` database and want to have a view on `Dashboard` page (action items for today for instance) and second view on `Meeting notes` (action items related to specific meeting).  Views are backed by database data, but independent in terms of visible columns, filters and sorting.

If it's not yet possible, are considering such feature request?

### Describe the optimal solution

Possible database views like Notion has?

**Comment by TCOTC** [comment]
It is close to #10734

**Comment by dvsekhvalnov** [comment]
Hi @TCOTC , thank. 

Still hard to understand in Chinese :) Is mirroring a way to go or do you guys planning to work on better 'view support' ?

**Comment by TCOTC** [comment]
In fact, my English skills are very poor and I rely almost entirely on translation software, so I have no way to properly explain to you the content of #10734.

In short, I think #10734 and this issue want to solve similar needs, but in a different form.

**Comment by dvsekhvalnov** [comment]
Understood, feeling same :) Do you have plans to complete https://github.com/siyuan-note/siyuan/issues/10734 ?

**Comment by 88250** [comment]
Hello, #10734 There is no clear development plan yet, please be patient, thank you.
