### ISSUE TITLE
Custom User login

### ISSUE THREAD

**Issue by jesperrichert** [siyuan-note/siyuan#12381]
### In what scenarios do you need this feature?

Make user accounts and manage users

### Describe the optimal solution

Member and Admins can create accounts to login with accounts

**Comment by 88250** [comment]
Hello, we have no plans for this feature. If you really need it, please modify the relevant code yourself and open source it under AGPL. Thank you.

**Comment by kalon33** [comment]
That's unfortunate not being able to setup multiuser/multiaccounts instances for teams.
