### ISSUE TITLE
打开一张图片，好像会先加载完文档中的所有图片才能打开

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12389]
文档里的图片如果比较多、比较大，首次打开某一张图片的速度很慢

**Comment by 88250** [comment]
这个应该没有办法优化了，浏览器本身加载图片的方式就是这样的，另外，如果是伺服浏览器上用的话，下行带宽也会影响加载速度。

**Comment by TCOTC** [comment]
应该是 Viewer.js 的问题：https://github.com/fengyuanchen/viewerjs/issues/426
