### ISSUE TITLE
文件命名排序 功能以及方案

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1238]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/105567420-bdf91180-5d6c-11eb-9c65-e9980f576028.png)
如图，这是思源官方帮助笔记的文件树
为了让多个文件的显示有一定的顺序
利用**手工**数值前缀的方式，让文件的显示顺序达到理想的顺序

这样的场景非常常见
随着笔记的发展，文件的增多，文件的顺序调整也是很自然的
**但是手工命名维护文件顺序 非常低效**：
用户可能想放弃合理的顺序，或干脆放弃顺序，这是一种无奈的妥协

### 描述最优的解决方案 Describe the optimal solution

过去设想让软件维护一个用户自定义的顺序记录
这是一个方案，但是这样破坏了文件顺序的携带

望着这些数字前缀，我想到了一个**兼容的方案**：
不如让思源去维护这些数字，这样就保证了顺序携带到了文件本身

可以做成一个 命名排序 功能的开关
如果开启，表明文件名的 ”数字+空格“ 部分属于思源 命名排序功能 的默认前缀
**用户拖放文档可以调整文档的顺序，思源帮助用户去做 数字前缀 排序命名的工作**
没有 ”数字+空格“ 的 思源会主动添加，开启时候按系统默认的排序去维护，后面按用户的调整去维护

### 其他信息 Other information

这其实是一个 **痛点** 特性
也许发布会可以对比手工的效率

本issue是看到这个排序issue 想起的：https://github.com/siyuan-note/siyuan/issues/1215#issue-791184704

顺序是一个**有价值**的信息：
可以是引用排序，可以是时间排序，也可以是我提的用户定义排序
或者是字数排序，优先级顺序等等

**Comment by 88250** [comment]
如果能实现自定义排序 #662 那其实不用维护这个编号了，现在就是因为实现不了才这样的。

感谢帮忙思考，但是目前确实是没有实现方案，我关闭了。

**Comment by wo4wangle** [comment]
> 如果能实现自定义排序 #662 那其实不用维护这个编号了，现在就是因为实现不了才这样的。
> 
> 感谢帮忙思考，但是目前确实是没有实现方案，我关闭了。

”现在就是因为实现不了才这样的“：我不明白是哪种实现不了
我提的方案**就是维护编号，不过维护工作交给思源了**
文件的重命名 思源 做不到吗？
