### ISSUE TITLE
Database support Group by Fields and can save as new view

### ISSUE THREAD

**Issue by thienphuoc86** [siyuan-note/siyuan#12383]
### In what scenarios do you need this feature?

Database support Group by Fields and can save as new view

### Describe the optimal solution

Refer to database view of Lark
![image](https://github.com/user-attachments/assets/1fa25dca-e86a-4237-80c7-59825dae2bce)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/10964
