### ISSUE TITLE
剪藏链滴和流云还有必要滚动页面吗？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12398]
#12368 的延续

不滚动的话还能剪藏图片吗？

如果可以的话，跳过滚动页面直接剪藏会更方便

![image](https://github.com/user-attachments/assets/72d0b3aa-30f0-4fe6-bf15-695a0d60961c)

**Comment by 88250** [comment]
这部分就保持不变了，谢谢。
