### ISSUE TITLE
shift + enter 快捷键问题

### ISSUE THREAD

**Issue by M2uyo** [siyuan-note/siyuan#12390]
### In what scenarios do you need this feature?

1. 当将 shift + enter 指定为一个快捷键功能后, 是否会屏蔽原本的软换行功能 (如果没有屏蔽 那么执行顺序是?)
2. 如何识别软换行 (当我指定了一个功能后, 我应该如何判断是否执行了软换行)

### Describe the optimal solution

1

**Comment by 88250** [comment]
1. 不能配置
2. 没看明白

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:

**Comment by M2uyo** [comment]
> 1. 不能配置
> 2. 没看明白

1. 
![image](https://github.com/user-attachments/assets/beb67d24-924d-41ec-b90e-a8ebd0e0e2ff)
我直接更改 conf.json 是可以应用的, 且看起来使用正常 ( 千万别限制!!!! 挺好的 非常想用这个 shift + enter 作为Jetbrain的资深用户)
2. 因为我是直接修改了conf文件应用的, 所以很好奇 这样做是否会屏蔽原先软换行功能(希望是屏蔽的, 因为软换行对我也没有太大作用) 
- 如果没有屏蔽, 那么最终效果是什么样子的, 我这边操作起来看起来就是屏蔽了的样子

![20240904_164424](https://github.com/user-attachments/assets/bf1d55fd-fa3f-4988-8f5f-93cb8a305cec)

**Comment by 88250** [comment]
可能会有其他问题，不建议直接修改配置文件，我也不确定会出现什么表现，如果你用下来没啥问题那就先凑合用。
