### ISSUE TITLE
文件树折叠异常

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#1239]
### 截屏或录屏演示 Screenshot or screen recording presentation

![文件折叠异常](https://user-images.githubusercontent.com/28727933/105572337-7c2e9200-5d91-11eb-88a9-25862c91b516.gif)

### 版本环境 Version environment

* 版本 Version：v0.6.6 / Kernel v0.6.6
* 操作系统 Operating system：windows
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5859859/siyuan.log)

**Comment by 88250** [comment]
你好，我这里重现不了。

日志上有个报错：

```
E 2021/01/23 15:33:00 box.go:474: init repo failed: mkdir C:\Program Files\SiYuan\resources\guide\思源笔记用户指南\.git: Access is denied.
```

不太确定是否和这个有关，请等 v0.6.7 发布以后帮忙回测，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果还有反馈请随时跟帖，谢谢。
