### ISSUE TITLE
集市无法正常显示软链接插件

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#12399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

近两个版本的思源，集市当中无法显示软链接开发的插件。

![image](https://github.com/user-attachments/assets/345b2bbb-66cc-4b75-b272-083aa9e3a4ac)

简单跟踪了一下发现：loadPetals 当中查找到了；同时也正常执行了 load；但是就是在集市当中没有显示。

![image](https://github.com/user-attachments/assets/b01e961e-1de5-4cc0-950c-1c800e83db8a)

![image](https://github.com/user-attachments/assets/f7838169-75b3-41cf-a1fa-ccbc0366ac66)

右上角的「设置」中，有点击按钮，但是显示异常

![image](https://github.com/user-attachments/assets/25333137-0764-4c3a-be6e-543343999e7c)

### Expected result

略

### Version environment

```markdown
- Version: 3.1.15
- Operating System: Windows 10
- Browser (if used): 无，Desktop 模式
```

### Log file

log 文件中没有什么特别的记录。
[app.log](https://github.com/user-attachments/files/16886729/app.log)

[siyuan.log](https://github.com/user-attachments/files/16886730/siyuan.log)

**Comment by KuiyueRO** [comment]
相同问题，3.1.4版本开始就无法使用软链接了，回退3.1.3后正常

**Comment by suka233333** [comment]
me too

**Comment by zxhd863943427** [comment]
已定位到问题根源，应该是在提交hash675d60f-7d179f之间引入的，对应的信息为：
```
commit 7d179f328234aad7a2407db49a4375345840e276
Author: Daniel <845765@qq.com>
Date:   Wed Aug 28 16:48:49 2024 +0800

    :arrow_up: Upgrade kernel deps

commit 675d60fbb5a143dd14a23fb7a1b754cb686fc91b
Author: Daniel <845765@qq.com>
Date:   Wed Aug 28 16:45:40 2024 +0800

    :arrow_up: Upgrade kernel deps
```
应该是更新依赖导致的问题，回退到 675d60f 后本地打包内核，问题消失。

**Comment by 88250** [comment]
我切换到 go1.22.6 调试了下，应该是因为 go1.23.0 下这个判断有问题：

```go
func IsSymlink(dir fs.DirEntry) bool {
	return dir.Type() == fs.ModeSymlink
}
```

在 1.23.0 下虽然是符号链接，但是也会返回 `ModeIrregular`，这就比较头大了。

目前似乎没有其他判断方案了，估计只能等 go 发新版看看。

**Comment by 88250** [comment]
继续测试了下，在 Windows 11 上：

* 使用 `mklink /D` 创建的符号链接，go1.23.0 是可以识别为 `ModeSymlink` 的
* 使用 `mklink /J` 创建的联接，go1.23.0 会识别为 `ModeIrregular`
* go1.22 上这两者均识别为 `ModeSymlink`

各位看下是不是 `/J` 创建的，如果是的话改成 `/D` 应该就可以了。
