### ISSUE TITLE
数据库显示失败，一直在加载。

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#12395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库不显示，
ok手机电脑上都这样。

### Expected result

ok

### Screenshot or screen recording presentation

![Screenshot_20240904-233434](https://github.com/user-attachments/assets/a19b26e9-a336-486f-bf27-502e7d344f09)

### Version environment

```markdown
- Version: 3.1.5
- Operating System: all
- Browser (if used):
```

### Log file

……

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:
