### ISSUE TITLE
改进代码块导出预览

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12394]
问题：

1. 没有显示行号
2. 没有换行
3. 文本居右显示了

![image](https://github.com/user-attachments/assets/f52a613d-d2e9-4b28-877d-f16f32818285)

p.s. 关联 https://ld246.com/article/1725446461859

**Comment by Vanessa219** [comment]
居右无法重现
![QQ_1725527237487](https://github.com/user-attachments/assets/96af0035-1e01-4dcd-8647-92147d05fdb2)

无法换行需要添加换行标识 @88250 

行号为了保证正常复制到其他平台就不添加了。

**Comment by TCOTC** [comment]
发个 dev 版我再试试

**Comment by 88250** [comment]
@TCOTC 得再等等

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by TCOTC** [comment]
dev 版不会居右了

**Comment by 88250** [comment]
ok
