### ISSUE TITLE
能不能在工具栏加一个按钮，点击一下随机打开一篇文章

### ISSUE THREAD

**Issue by DearZack** [siyuan-note/siyuan#12400]
### In what scenarios do you need this feature?

做了一些笔记，长时间不看可能会忘记，想着每天可以随机看一下，会加强记忆

### Describe the optimal solution

做了一些笔记，长时间不看可能会忘记，想着每天可以随机看一下，会加强记忆

**Comment by 88250** [comment]
集市中应该有类似插件，请自行寻找，谢谢。
