### ISSUE TITLE
Improve list editing

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#12405]
建议列表项首使用退格键时，把内容合并在上一个列表项里

### In what scenarios do you need this feature?

https://ld246.com/article/1725417615370 
源于此个帖子的讨论，在列表里的段落块缩进逻辑较为混乱

### Describe the optimal solution

建议改为logseq这种
![2](https://github.com/user-attachments/assets/19d41b8d-826b-43be-9d2f-5fda60bda71e)

**Comment by 88250** [comment]
@Vanessa219 考虑一下

**Comment by TCOTC** [comment]
确实，应该统一为 Backspace 删除列表项。

[视频.webm](https://github.com/user-attachments/assets/86ed825b-2531-4543-bfc2-15a68e263593)

**Comment by Vanessa219** [comment]
这样好像也有问题，比如这种情况，在22前面删除，得到的结果都一样。

![QQ_1725769293949](https://github.com/user-attachments/assets/31ab8c04-3990-4027-aea3-01a0ccdf8b73)

**Comment by TCOTC** [comment]
> 比如这种情况，在22前面删除，得到的结果都一样。

我感觉挺合理的。上面是删除列表项块的同时删除列表块，下面是删除列表项块，最后的效果应该都是一样的

**Comment by royc01** [comment]
> 这样好像也有问题，比如这种情况，在22前面删除，得到的结果都一样。
是合理的，logseq也采取这种方案

**Comment by 88250** [comment]
不应该一样的，下面 22 的情况应该再往前缩出，参考 Notion：

![image](https://github.com/user-attachments/assets/682b3c69-0fdd-4cac-a4ad-fcf3b4e2a989)

再按退格缩出为：

![image](https://github.com/user-attachments/assets/a8689bce-62d8-4514-9299-84de49fa7c6c)

**Comment by royc01** [comment]
> 不应该一样的，下面 22 的情况应该再往前缩出，参考 Notion：

notion的结构不一样，段落块支持反缩进，所以逻辑比较一致，而思源在列表里面的段落块反缩进会导致整个列表项反缩进了

**Comment by 88250** [comment]
这里如果不缩出的话就没法方便的得到下图结果了。

**Comment by 88250** [comment]
另外，还有两种场景：

场景一：

![image](https://github.com/user-attachments/assets/36dea09f-4e60-475e-a899-e0bb83e1a334)

在 333 前面退格，得到：

![image](https://github.com/user-attachments/assets/6c76b617-45bc-4946-bb72-e17ba8547a01)

场景二：

![image](https://github.com/user-attachments/assets/d491f938-a0d4-4d80-8d43-00e129222047)

同样在 333 前面退格，得到：

![image](https://github.com/user-attachments/assets/d42da587-6755-4df6-96ec-1d6ee6126618)

就像 @royc01 说的，思源不支持在列表下单独段落缩进，所以如果要统一逻辑，一些排版效果用户就很难操作实现了。

这部分考虑了下，还是不考虑修改了，因为列表+多叶子块的结构在本质上就无法保证操作逻辑的统一。
