### ISSUE TITLE
Improve database paste binding blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12408]
复制 A 数据库主键（已绑定块）粘贴到 B 数据库主键时，需要绑定块

https://ld246.com/article/1725596885614 第二点

![image](https://github.com/user-attachments/assets/7f8214f6-4ae6-4f80-99a4-d6e560320ac2)

---

如果粘贴的目标数据库中已包含粘贴的绑定块 → 只保留纯文本主键。这样就不会丢失条目里除了主键外的其他字段信息（否则用户可能注意不到复制粘贴的条目有的没有粘贴进去就把原来的数据库删了）

**Comment by Vanessa219** [comment]
无法区分是当前数据库，还是其他数据库。如果是当前数据库的话，就永远无法粘贴了。

**Comment by TCOTC** [comment]
为啥不能粘贴？

**Comment by Vanessa219** [comment]
一个 id 只能有一条。不论怎么粘贴都只有一条。

**Comment by TCOTC** [comment]
> 如果粘贴的目标数据库中已包含粘贴的绑定块 → 只保留纯文本主键

这个实现不了吗？

**Comment by Vanessa219** [comment]
判断不了当前库是否有存在已绑定的 id，如果发请求的话，会让用户有延迟感。
