### ISSUE TITLE
点击大纲标题时，如果标题没有被折叠，需要退出聚焦

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12419]
目前是点击被折叠的标题以后，就一直是聚焦状态了：

[视频.webm](https://github.com/user-attachments/assets/2f2d6acc-5135-4ba7-85b6-aeb04a343756)

关联 https://ld246.com/article/1725769274424

**Comment by 88250** [comment]
这个是正常的，上级标题折叠以后下方所有块都会被折叠，所以点击跳转是聚焦状态。

**Comment by TCOTC** [comment]
@88250 顶层的两个二级标题都不是被折叠的

**Comment by 88250** [comment]
我看你录屏上是折叠状态：

![image](https://github.com/user-attachments/assets/ac1a7dac-c8c8-4f62-88f9-ee0a2d8a499f)

**Comment by TCOTC** [comment]
我重新描述一下吧。

正常情况下，点击**能显示出来的标题**是会取消当前的聚焦状态直接跳转到块的，只有点击**被折叠起来不显示的标题**才会聚焦。

但是点击了 `33333` 之后再点击 `222222` 时，没有取消聚焦，这是不正常的：

[视频.webm](https://github.com/user-attachments/assets/278284a2-a2a8-4b14-b786-be9b8cd4e6c3)

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
没有聚焦时，222 已经显示在界面上，就可以直接定位。
当聚焦到 333，点击 222 时会发起一个 /api/block/checkBlockFold 请求，此时返回为折叠块，就会聚焦处理。

**Comment by Vanessa219** [comment]
返回折叠状态的都会进行聚焦。 @88250 是否需要判断一下是否为顶层折叠？

**Comment by 88250** [comment]
层级多了的话在某一层聚焦切换上面某一层还是会聚焦，这个我觉得还是保持聚焦跳转吧。
