### ISSUE TITLE
Creating a dailynote template supports the doc icon

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12416]
dailynote 模板支持设置dailynote文档图标

### In what scenarios do you need this feature?

目前思源笔记导出模板属性是支持导出文档属性的，包括文档别名、命名以及文档图标等等属性
![Clip_2024-09-08_11-56-42](https://github.com/user-attachments/assets/734f5f49-e481-4240-8148-f9a6c40e46d1)

我目前的dailynote会给每日添加上星期的自定义图标
![Clip_2024-09-08_11-56-59](https://github.com/user-attachments/assets/980cd139-936d-4972-8227-d04d8f5787f3)
现在都是纯手动的添加，无法自动添加，如果dailynote调用模板支持根据文档属性设置文档图标，就可以自动化设置每周几设置对应的文档图标了

### Describe the optimal solution

dailynote调用模板支持根据文档属性设置文档图标，就可以自动化设置每周几设置对应的文档图标

### Describe the candidate solution

无

### Other information

无

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/10698
