### ISSUE TITLE
希望能保存多个AI配置

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#12414]
### In what scenarios do you need this feature?

不同情况下想用不同的模型，但是每次都要重新填很麻烦

### Describe the optimal solution

希望可以保存多个AI配置，这样可以方便切换

**Comment by TCOTC** [comment]
确实

**Comment by 88250** [comment]
这个请考虑通过插件实现，大致思路：

* 提供界面支持保存多套 AI 配置
* 提供切换配置功能并通过 setAI 接口设置生效

**Comment by lisontowind** [comment]
解决了，集市上有SACKey插件😊

**Comment by 88250** [comment]
ok
