### ISSUE TITLE
Improve list item convert to doc

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12411]
拖动列表项到文档树后，如果列表项块的首个子块被引用或被数据库绑定，则在新增的文档中保留这个块

因为首个子块不保留，就会丢失引用和数据库绑定：

[视频.webm](https://github.com/user-attachments/assets/547db0f0-ac3a-40a3-ae6a-667e844d91ee)

---

另一种方案是将引用和数据库绑定转移到文档块上，但如果列表项块本身也被相同的数据库绑定了，一转移就会出现同一个数据库绑定了两次同一个文档的情况

**Comment by TCOTC** [comment]
@88250 改了之后是什么效果？

**Comment by 88250** [comment]
保留第一个块



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sun, Sep 8, 2024 12:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve list item convert to doc (Issue#12411)




 
@88250 改了之后是什么效果？
