### ISSUE TITLE
无法拖动块的情况

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12410]
在列表块内只有一个列表项块，列表项块内有多个子块的情况下，通过列表项块标的左半边可以正常拖动块，但右半边不能拖动：

```
* 2222222222

  3333333333
```

[视频.webm](https://github.com/user-attachments/assets/fdd3eb7b-8dbb-43b2-9e1e-f611b9c11002)

**Comment by 88250** [comment]
我这里目前无法重现该问题，先关闭了。

**Comment by TCOTC** [comment]
我这里还会有这种情况：

[视频.webm](https://github.com/user-attachments/assets/513323d3-420a-41a6-9245-444c6979e92e)

**Comment by 88250** [comment]
我这里即使在很右边也可以拖的，搞不好是驱动和 electron 相关的问题。
