### ISSUE TITLE
双链悬浮窗上下文显示

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1241]
### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/46141646/105573735-9e78dd80-5d9a-11eb-8fce-0edff1060f06.png)
如图，显示了双链的原文窗口
但是这种时候**往往希望能看到这个原文 所在的上下文**
目前是通过直接再打开显示整个文件来浏览，相对低效

### 期待的结果 Expected result

悬浮窗能显示 原文所在的整个文件内容
悬浮窗定位到 引用块的 内容 窗口大小也刚好包裹（如现在）
**但是可以通过滚动鼠标来浏览原文的上下文，免得再打开，只是瞥一眼**

**Comment by lss6378** [comment]
或者提供一个在预览窗口内直接跳转的选项，上下文查看可以在一个窗口内完成，而不需要新建窗口，也许是不错的选择

**Comment by 88250** [comment]
在 #1399 中改进看看，谢谢。
