### ISSUE TITLE
文档树展开子文档时容易误触打开文档

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12413]
展开/折叠按钮的 上/左/下方 不应该有边距：

![image](https://github.com/user-attachments/assets/ba02b76e-b028-4aa9-b278-185ffa26bba8)

**Comment by 88250** [comment]
这里的边距我们已经优化过了，之前和 Notion 差不多比较大：

![image](https://github.com/user-attachments/assets/4c062c14-e503-44ae-8841-18b6fcc49958)

后面优化后调整小了：

![image](https://github.com/user-attachments/assets/908c933f-6af8-497f-8dac-954b22386e92)

如果不要边距的话界面会比较丑，所以就不考虑再调整了。

**Comment by TCOTC** [comment]
@88250 按钮可以显示那么大，但实际点击范围能不能再扩大？

**Comment by 88250** [comment]
不能的
