### ISSUE TITLE
前端使用组件技术

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#12415]
### In what scenarios do you need this feature?

利于更多开发者参与前端代码贡献
在现有的代码中，充斥者魔法字符串以及html模板代码，这让我感觉非常难以下手进行改动。
组件化成功后，在 ts 的加持下改动难度会小许多。

### Describe the optimal solution

鉴于目前的代码情况，我认为使用 tsx + solid 渐进化改造可能是最好选择

**Comment by 88250** [comment]
抱歉，这个不考虑了：

1. 没有开发资源投入
2. 不希望使用其他 UI 框架

对于社区开发者而言，任何组件框架都需要学习成本，所以绑定到某个框架上不是最优选。如果要组件化，较为可行的方案应该是在现有基础上小步重构，形成思源自己的 UI 框架。目前一部分实现已经是这样考虑的，只是业务需求较多，所以实现细节比较糙，后续如果有必要的话再看看如何改进吧，我们也希望社区开发者往这个方向上帮助思源，谢谢。
