### ISSUE TITLE
导入 Markdown 支持导入 `<img src="" />` 图片

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12418]
https://ld246.com/article/1725723850413

**Comment by 88250** [comment]
这个是支持的，需要打包上传 .md 文件和相关资源文件才能定位问题。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:
