### ISSUE TITLE
搜素页签默认展开第一个搜索结果

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#1242]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

全局搜索很方便，希望能自动展开第一个搜索结果

![图片](https://user-images.githubusercontent.com/15924513/105578804-bf065f00-5dbd-11eb-83f9-b1276697de4f.png)

### 其他信息 Other information

思源版本： 0.6.6  
操作系统： win10

**Comment by 88250** [comment]
这部分我们计划在 #1159 中一起做，谢谢反馈。
