### ISSUE TITLE
数据库资源列的链接如果只有标题，鼠标左键单击后直接弹出编辑浮窗

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12422]
让鼠标左键单击后直接弹出编辑浮窗：

![image](https://github.com/user-attachments/assets/9a3d8f20-0bb9-410b-8f2c-e2ea01d39590)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
