### ISSUE TITLE
移动端打开文档显示文档题头图、标签和表情操作

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12425]
目前新建文档后是不显示顶上的三个按钮的（我觉得应该会有用户不知道）：

![Screenshot_2024-09-09-12-18-30-17_ed1bdeca7a858bb430bfb9c256856672](https://github.com/user-attachments/assets/8aea17fd-40c9-46a0-81e3-5cc4db3c53ef)

我觉得在新建文档后可以先默认聚焦在 .protyle-background__action ：

![Screenshot_2024-09-09-12-18-40-55_ed1bdeca7a858bb430bfb9c256856672](https://github.com/user-attachments/assets/bcc57a94-6cb7-49fb-ae9a-e92b84fee871)

**Comment by TCOTC** [comment]
更新之后好像没有变化？

**Comment by Vanessa219** [comment]
只有第一次生效，我再改改
