### ISSUE TITLE
文档转移与图标的 bug

### ISSUE THREAD

**Issue by xwxw098** [siyuan-note/siyuan#12427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文档在文件编辑器内转移，其面包屑还是停留在原位置，左侧文档树并不会迁移，相当于变成了引用，而不是转移，只能在文档树内转移，才是真的转移
data/emojis内上传的 svg图标，名字不变，但图片内容变了，但怎么刷新数据库，图片还是原来的图片
<img width="563" alt="image" src="https://github.com/user-attachments/assets/09ddb26e-40a6-45ca-895a-d4f523d906e0">

### Expected result

请尽快修复，谢谢

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
1. 你指的是转移引用功能吗？
2. 修改自定义图标文件的话可能需要刷新，打开开发者工具，在网络中禁用缓存然后 Ctrl+R 刷新试试

**Comment by 88250** [comment]
我先关闭了，欢迎随时跟帖补充，谢谢。
