### ISSUE TITLE
图片标题支持行内公式

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#12421]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/92f88f97-af85-4550-8cb6-635b2039e9bf)
需要要给图片标公式的时候发现无法识别公式

### Describe the optimal solution

图片标题要是可以渲染行内公式就好了。。。。

### Describe the candidate solution

当然也可以把标题写在外面，不使用图片的标题功能解决。。。。。。

**Comment by 88250** [comment]
这个不考虑了，仅支持文本，感谢提议。
