### ISSUE TITLE
增加图片高度的设置

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12423]
### 背景

有时候会需要在一个段落块里插入多张图片，或者[把多个包含图片的段落块组合成超级块](https://ld246.com/article/1722836542235)，想要把图片对齐。

但只靠调整图片的宽度很难让每张图片的高度一致，因此会参差不齐。

### 方案

- 支持为图片设置高度
- 支持恢复默认高度
- 支持拖拽调整图片高度

另外：同时设置图片的高度和宽度会有冲突，所以设置高度之后要清除设置的宽度、设置宽度之后要清除设置的高度

---

> <details>
> <summary>还能顺带实现一些其他的用户需求</summary>
> 
> ![fe828a0aff0e8b55a43b94efc73c83d](https://github.com/user-attachments/assets/3b1834ce-96cf-498b-9f2f-0b651a6733bd)
> 
> [笔记支持嵌入网页，图片拖拽调整高度和宽度 - 链滴](https://ld246.com/article/1720407074590)
> 
> [希望可以设置图片的默认大小 - 链滴](https://ld246.com/article/1715071100240)
> 
> [图片可以自动设置宽度吗？ - 链滴](https://ld246.com/article/1710390248947)
> 
> [请问复制的图片的默认大小可以设置吗 - 链滴](https://ld246.com/article/1698284294338)
> 
> 备注：目前默认宽度可以用 CSS 实现，如果之后支持设置图片高度，那么默认高度也应该可以用 CSS 实现
> 
> </details>

**Comment by 88250** [comment]
之前讨论过，会有其他问题，所以不再考虑了 https://github.com/siyuan-note/siyuan/issues/4878#issuecomment-1125820781

**Comment by TCOTC** [comment]
没看明白 https://github.com/siyuan-note/siyuan/issues/4878#issuecomment-1125820781 跟我这个 issue 有什么关系

**Comment by 88250** [comment]
默认图片大小会有影响

**Comment by TCOTC** [comment]
用户通过 CSS 来设置默认图片大小，遇到的问题用户自己解决就好了，不是思源该管的事情了。

目前的需求就是支持为单张图片设置高度。

**Comment by 88250** [comment]
@Vanessa219 评估一下可行性

**Comment by Vanessa219** [comment]
为保持图片比例，应该是设置宽度就可以了，宽度变了，高度也会变。如果宽度和高度都设置的话，比例就不对了。

**Comment by TCOTC** [comment]
@Vanessa219 我补充了这一点：

![image](https://github.com/user-attachments/assets/5c00fe75-728a-4395-9e21-6eade4a3e150)

**Comment by TCOTC** [comment]
对了，高度是用 px 和 vh 这种感觉更好，因为是用来保存高度一致的，所以不能调比例

**Comment by TCOTC** [comment]
总之就是有的时候需求是让多图的高度完全一致，这靠调整宽度是很难做到的

![image](https://github.com/user-attachments/assets/6dcb8277-ecf1-41f1-b627-a10470917a55)

**Comment by KuiyueRO** [comment]
完了我也是。差不多意思就是超级块中有几张图，这几张图在统一高度的情况下去计算几张图片的宽度px。

另外如果可以，根据宽度的px去计算占比百分之多少，自动设置块宽度。其实不仅是图片，有的时候文字等也需要统一高度，这个很有用，大幅减少排版的时间

**Comment by Vanessa219** [comment]
自动的设置这个可能每个人对每种块想要的宽度不一样，还是用户自己设置吧。
高度的话就添加一个菜单吧，毕竟 notion 都不支持。

**Comment by TCOTC** [comment]
我想了想，应该会有用户想同时设置高度和宽度来拉伸图片，建议还是支持同时设置高度和宽度，不用清除其一了。

> 如果宽度和高度都设置的话，比例就不对了

比例的问题就交给用户自己决定，反正可以将高度或宽度恢复默认。

不过目前点击高度或宽度的 `默认` 都会使高度和宽度同时恢复默认，我认为分开来处理会更合理。

---

另外还有点问题：

### 01 选中文本时鼠标移到输入框外可能会关闭菜单、点击输入框再点击外部会关闭菜单

[视频.webm](https://github.com/user-attachments/assets/b7931fd4-d0ff-4245-b4f8-88956793d492)

### 02 需要支持通过删除已填写的具体数值来恢复默认

[视频.webm](https://github.com/user-attachments/assets/e6884471-be1b-4f9d-ba0f-8fef16c18da6)

**Comment by Vanessa219** [comment]
1， 2 已改进。高宽同时设置先不支持了，毕竟大部分用户是不希望图片变形的。

**Comment by TCOTC** [comment]
> 高宽同时设置先不支持了，毕竟大部分用户是不希望图片变形的。

那么基于这一点，还有一个问题是拖拽图片宽度（有个小竖条）时，不会清除高度，导致图片比例不正确：

[视频.webm](https://github.com/user-attachments/assets/7fa47438-e42e-4204-9c95-8247e02aac00)

**Comment by TCOTC** [comment]
还有，这个输入框没有跟下面的文本对齐，看起来有点别扭：

![image](https://github.com/user-attachments/assets/ee70f048-7184-4f28-9796-609056be736e)

**Comment by Vanessa219** [comment]
这个是为了和 focus 后的外层高亮对齐
