### ISSUE TITLE
After find-replacing block refresh other associated blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12439]
查找替换块内容后刷新关联的其他块内容

- [ ] 块引用锚文本
- [ ] 嵌入块
- [ ] 或许还有别的块类型？

[视频.webm](https://github.com/user-attachments/assets/863d3104-06e3-43c3-8a72-1e1de8e2ac55)

**Comment by TCOTC** [comment]
关联的块更新了，但块自身没有更新：

[视频.webm](https://github.com/user-attachments/assets/4d2f0f51-c3d9-4951-aa58-1d681bae947c)

**Comment by 88250** [comment]
和 https://github.com/siyuan-note/siyuan/issues/12437#issuecomment-2348022851 应该是一个问题，一并处理了。

**Comment by Jiangshuon** [comment]
@88250 @TCOTC 最新版查找替换慢好多了，替换一个块也要5秒以上，好像还替换不了，感觉没必要立刻刷新关联块吧

**Comment by TCOTC** [comment]
我也觉得这个交互还能再优化一下。

> 好像还替换不了

替换类型选没选？

**Comment by Jiangshuon** [comment]
我重启思源后行了，不知为啥。速度还是慢了好多

**Comment by TCOTC** [comment]
关联 #12618
