### ISSUE TITLE
`粘贴为纯文本` 快捷键在文档标题中无效

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12435]
[视频.webm](https://github.com/user-attachments/assets/387311a7-7534-4694-b701-8d26457e26bc)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by 88250** [comment]
我这里测试无法重现该问题。

**Comment by Vanessa219** [comment]
我这里也重现不了。


https://github.com/user-attachments/assets/c9eff631-5a4e-46d2-9044-92fbb4d676c1

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/0beac68e-4910-4505-9686-b501690e65fc)

录屏上最后又按了个 Ctrl+V

**Comment by TCOTC** [comment]
确实哦，刚刚试了一下在其他地方按 `Ctrl+Shift+V` 也会这样，我研究看看是不是我电脑的问题
