### ISSUE TITLE
启用了发布服务和密码验证，但是访问不但不是密码验证，而是授权码，而且还可以编辑

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#12436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题

### Expected result

- 访问应该提示密码授权而不是授权码
- 反正应该是只读服务

### Version environment

```markdown
- Version: 3.1.6
- Operating System: all
- Browser (if used): edge
```

### Log file

%

**Comment by heartacker** [comment]
![Screenshot_2024-09-11-09-33-51-736_Edge Canary.png](https://github.com/user-attachments/assets/32d3b9b1-9aa5-4b03-90c0-1ea6fa872fcf)

**Comment by TCOTC** [comment]
请截图确认一下网址中的端口号是不是 6808 ？

**Comment by heartacker** [comment]
![Screenshot_2024-09-11-09-33-51-736_Edge Canary.png](https://github.com/user-attachments/assets/32d3b9b1-9aa5-4b03-90c0-1ea6fa872fcf)

确认是6806

**Comment by heartacker** [comment]
不好意思，我访问的是6806，不是6808
不过6806是啥呢

**Comment by 88250** [comment]
6806 是默认的伺服端口。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:

**Comment by heartacker** [comment]
好的，谢谢
终于明白了，
原来这里是两个东西
- 发布服务
- 关于里面的伺服

|发布服务| 伺服|
| - | - |
|![image](https://github.com/user-attachments/assets/65d7c502-50f7-4d6f-905e-3fe867c613de)|![image](https://github.com/user-attachments/assets/19f0fb77-c221-41c9-82d6-1ca733308589) |

@88250 不过这个设置的地方实在是让人难以理解，你看是否可以整合一下这两个功能设置的地方。让用户好理解一点。尤其是伺服，在关于里面，想都想不到。

**Comment by TCOTC** [comment]
其实我也觉得伺服功能的位置很怪。我推荐把伺服和发布服务靠在一起，菜单叫 `伺服与发布`

**Comment by heartacker** [comment]
对，
或者发布独立一个，伺服独立一个

**Comment by 88250** [comment]
暂时不动了，伺服是很早之前提供的功能，并且适用面较广，而发布服务需求并不多，放在一起不太合适。

**Comment by TCOTC** [comment]
但在设置里，发布服务比伺服功能显眼多了
