### ISSUE TITLE
Refresh result list after find-replace

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12437]
`全部替换` 后没有刷新搜索结果列表

单个块替换是正常的，全部替换就没有刷新：

[视频.webm](https://github.com/user-attachments/assets/19f9b969-b094-4d47-a043-e0d27a45692f)

**Comment by TCOTC** [comment]
@88250 块引用还略有问题：

[视频.webm](https://github.com/user-attachments/assets/82c15f62-26da-412c-a8ba-130250804a01)

**Comment by 88250** [comment]
稍后改进，谢谢。

**Comment by TCOTC** [comment]
体感上替换的过程有点慢，还有办法再快一些吗？

[视频.webm](https://github.com/user-attachments/assets/f0958361-2cf9-4144-9153-692b2eba82f5)

**Comment by 88250** [comment]
没有办法了，要保证一致性的话必须等数据索引执行完毕。
