### ISSUE TITLE
优化同步事件，使插件得以获悉 petal 的更新

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#12433]
### In what scenarios do you need this feature?

✨ 需求：希望插件能知道「远端更新了插件的设置」，这样才方便插件自行处理多设备的设置冲突。

📚 解释：以一个具体案例进行说明。

* 假设有一个相同的插件 X，同时运行在两台设备 A 和 B 上。在 T - 1 时刻，两个插件 xa 和 xb 内存中维护的变量状态和当地 petal 存储的内容都一致，记为状态 v@t-1
* 在 T 时刻，xa 更新了设置，写入了新的 petal 文件，记为状态 v@t
* 在 T + 1时刻，思源进行了同步，将最新的 petal 写入到 B 设备中
* 现在问题出现了：在设备 B 上，插件 xb 在内存中维护的状态为v@t-1，而其本地 petal 中记录的状态为 v@t，**出现了冲突**
* 如果此时设备 B 再进行了更新状态，那么设备 B 以及同步后的 A 设备的 petal 中的数据状态就变成了 v@t+1，和设备 A 中 xa 在内存中的状态**再次出现了冲突**
* 任由以上进行循环，那么很容易出现数据的冲突甚至是丢失（我们姑且称为**插件冲突**）

重要性：以上的问题，在本地保存大量状态的插件中尤为重要，例如书签插件，很可能出现用户不当操作造成加入的书签直接丢失的情况。

🤔 分析：

1. 这个问题和「不要在多端同时编辑一个块」造成的文档冲突还不一样:

    1. 多端同时编辑文档，强调的是「同时」，只要保证不在同一个时刻编辑同一个块，那么也不会造成文档冲突
    2. 插件冲突触发的条件更加简单：只要两个设备都进行了需要写入 petal 的操作，就非常容易触发插件冲突
2. 插件冲突问题的核心在于：思源没有多端 petal 合并的机制

    1. 对思源内置的块、文档而言，思源可以自行拉取到更新之后进行合并处理操作
    2. 但是对于插件而言，他天然就是单机的，即便思源更新了远端的数据，插件也不得而知，更不知道自己当前的状态实际上已经“落后”了
    3. 🛠️ 思路：让插件自行解决合并问题
3. 思源内置的 sync event bus 不足以解决问题

    1. sync-start, sync-end 里面没有关于同步内容本身的信息，无法获知插件文件是否更新了
    2. 🛠️ 思路：需要一个机制去通知插件，告诉它们「应该做状态合并了」

### Describe the optimal solution

1. 方案一：建议添加一个 EventBus `on-petal-updated`

    1. 在 sync 结束之后，分析本次同步中涉及更改的消息
    2. 对那些 petal 被更改的插件，广播这个事件（包括更新的文件等）
2. 方案二：优化 sync-end 事件，在参数中添加更新的文件的路径
3. 插件接受到事件之后，自行决定如何处理，自行完成状态合并

🤔 如果感觉这个对性能有影响，也可以做成一个可选的开关？

**Comment by 88250** [comment]
我看了下内核目前的处理步骤：

1. 内核在处理同步数据合并后会在 main 上推送 reloadPlugin 事件，界面收到 reloadPlugin 后如果是 upserts（新增或更新文件）则重新载入插件
2. 同步结束后在 main 上推送 syncing 事件

在 1 中似乎不可能出现 xb 内存状态不一致的情况，因为重载时应该会根据同步后的文件重新载入吧？

**Comment by frostime** [comment]
> 我看了下内核目前的处理步骤：
> 
>     1. 内核在处理同步数据合并后会在 main 上推送 reloadPlugin 事件，界面收到 reloadPlugin 后如果是 upserts（新增或更新文件）则重新载入插件
> 
>     2. 同步结束后在 main 上推送 syncing 事件
> 
> 
> 在 1 中似乎不可能出现 xb 内存状态不一致的情况，因为重载时应该会根据同步后的文件重新载入吧？

你说的情况 1 是指启动时候的同步吗？那个确实会 reload。

但是在开启了同步感知之后的运行过程中，应该是不会 reload 插件的吧（我没有遇到过在运行中插件自动重载的情况）？

我说的情况是，比如我在办公室和家里两个思源都开了同步感知、思源都长时间运行。在这种情况下似乎就会出现上面提到的插件冲突问题。

当然我没有细扒代码，插件冲突问题也只是我个人经验性的感受，可能有些技术性细节会有疏漏或不准确的地方。

**Comment by TCOTC** [comment]
> 如果是 upserts（新增或更新文件）则重新载入插件

这个指的是插件文件夹还是配置文件夹？

**Comment by 88250** [comment]
/storage/petal/ 下的变更

**Comment by frostime** [comment]
> /storage/petal/ 下的变更

也就是说现在思源内部实际上是做了插件状态合并的吗？
这个确实让我有些困惑：

1. 我确实没有注意到过插件会自动 unload/reload 的情况（也可能是因为处于远端的问题）
2. 我确实遇到过两端插件状态冲突的情况

如果按照你的说法的话，思源已经做的这种插件合并的机制的话，那可能是别的什么因素导致的了。

我可能需要做一些实验来研究一下。

**Comment by 88250** [comment]
实验时请观察一下 main ws 通道上的 reloadPlugin 事件是否如期推送以及是否执行重载



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月11日(周三) 中午11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 优化同步事件，使插件得以获悉 petal 的更新 (Issue #12433)




  
/storage/petal/ 下的变更
  
也就是说现在思源内部实际上是做了插件状态合并的吗？
 这个确实让我有些困惑：
  
我确实没有注意到过插件会自动 unload/reload 的情况（也可能是因为处于远端的问题）
 
我确实遇到过两端插件状态冲突的情况
  
如果按照你的说法的话，思源已经做的这种插件合并的机制的话，那可能是别的什么因素导致的了。
 
我可能需要做一些实验来研究一下。

**Comment by frostime** [comment]
> 实验时请观察一下 main ws 通道上的 reloadPlugin 事件是否如期推送以及是否执行重载
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月11日(周三) 中午11:51 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 优化同步事件，使插件得以获悉 petal 的更新 (Issue #12433) /storage/petal/ 下的变更 也就是说现在思源内部实际上是做了插件状态合并的吗？ 这个确实让我有些困惑： 我确实没有注意到过插件会自动 unload/reload 的情况（也可能是因为处于远端的问题） 我确实遇到过两端插件状态冲突的情况 如果按照你的说法的话，思源已经做的这种插件合并的机制的话，那可能是别的什么因素导致的了。 我可能需要做一些实验来研究一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

好的，这个 issue 先进入 pending 状态吧。你可以先 close 了，要是还有问题我再来讨论。

**Comment by 88250** [comment]
好的，不过没有 pending 状态，有问题随时跟帖即可。

**Comment by frostime** [comment]
> 实验时请观察一下 main ws 通道上的 reloadPlugin 事件是否如期推送以及是否执行重载
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月11日(周三) 中午11:51 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 优化同步事件，使插件得以获悉 petal 的更新 (Issue #12433) /storage/petal/ 下的变更 也就是说现在思源内部实际上是做了插件状态合并的吗？ 这个确实让我有些困惑： 我确实没有注意到过插件会自动 unload/reload 的情况（也可能是因为处于远端的问题） 我确实遇到过两端插件状态冲突的情况 如果按照你的说法的话，思源已经做的这种插件合并的机制的话，那可能是别的什么因素导致的了。 我可能需要做一些实验来研究一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

您好，我抽空测试了一下 reloadPlugin

🧪 实验方案如下：

* 工具：

  * 源代码：[[frostime/test-reload/blob/v0.2.1/src/index.ts](https://github.com/frostime/test-reload/blob/v0.2.1/src/index.ts)](https://github.com/frostime/test-reload/blob/v0.2.1/src/index.ts)
  * Release：[https://github.com/frostime/test-reload/releases/tag/v0.2.1](https://github.com/frostime/test-reload/releases/tag/v0.2.1)
* 方案：

  * 在插件中，记录同步实验（实际包括：`['reloadPlugin', 'syncing', 'syncMergeResult']`.）
  * 将事件记录写入到 temp 下的一个日志文件中
  * 插件日志中是否会正常计量记录 `reloadPlugin`
* 操作：

  * 在设备 A 和 B 上安装 test-reload
  * 在设备 B 上操作插件的设置界面，更新插件的设置

    
    ![image](https://github.com/user-attachments/assets/83fdf831-8525-4f84-ae9c-d33e85bb8a96)

  * 触发 B 上的 petal 文件更新了，先让 B 设备进行更新，然后检查设备 A 的数据更新
* 观察：

  * 查看设备 A 是否会收到 reloadPlugin 事件
  * 查看设备 A 上的插件是否会自动 reload（onload 和 onunload 事件都会记录到日志中）


👀 观察情况：

在设备 B 上更新了插件的设置，更新效果如下。

![image](https://github.com/user-attachments/assets/37c5d80d-a8e4-49fd-a980-50bfa7e3d860)

> [!WARNING]
> 在设备 A 中观察到了 reloadPlugin，**但是 upsertPlugin 列表为空，也没有将设备 A上的 test-reload 插件自动重载**。

![image](https://github.com/user-attachments/assets/8f60cf05-9fbf-4d92-b04a-95f2f6b4970f)

**Comment by 88250** [comment]
感谢反馈，我定位到了一个问题，请等下一个版本发布后再测试看看。

**Comment by frostime** [comment]
> 感谢反馈，我定位到了一个问题，请等下一个版本发布后再测试看看。

好的，辛苦

**Comment by frostime** [comment]
刚刚测试了一下，目前应该是成功了。

![image](https://github.com/user-attachments/assets/876fd3dc-0f49-4259-a2fb-befd5d3e1cf3)

**Comment by 88250** [comment]
👌🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月29日(周日) 下午5:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 优化同步事件，使插件得以获悉 petal 的更新 (Issue #12433)




 
刚刚测试了一下，目前应该是成功了。
 
image.png (view on web)
