### ISSUE TITLE
Emoji中，自定义表情支持插入到文档

### ISSUE THREAD

**Issue by JHPZ** [siyuan-note/siyuan#12430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用自定义表情插入文档时，文件夹可能携带空格，则插入到文档不能正常展示：
![image](https://github.com/user-attachments/assets/6ac5024e-8d5e-4e9e-917c-a484ae474f4c)

展示情况：
![image](https://github.com/user-attachments/assets/a441c2e7-2924-40fd-9948-aaea58c8c76f)

### Expected result

我认为应当支持展示空格文件夹内的表情，虽然改文件夹名字也能做到。但文档图标可以展示
![image](https://github.com/user-attachments/assets/3d6428c7-5632-4dbe-a2f8-13efbfb58f56)

### Version environment

```markdown
- Version: v3.1.5
- Operating System: Linux
- Browser (if used): Edge
```

### Log file

这个应该不需要日志

**Comment by 88250** [comment]
这个没有办法，只能用户自己去掉命名中的空格了。
