### ISSUE TITLE
自动刷新文档树上的引用计数

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12432]
> 延伸 #8234

目前只能通过手动折叠与展开上级文档才能刷新

![image](https://github.com/user-attachments/assets/60b2cde0-53d2-41bb-9599-081cd1966c5a)

**Comment by 88250** [comment]
已经在 #8234 中实现了，但是引用计数刷新较慢，估计要等 3-5s 后才刷新。

**Comment by TCOTC** [comment]
奇怪了，我这好像是不会变的。晚上再试试

**Comment by TCOTC** [comment]
@88250 确实不会刷新：

[视频.webm](https://github.com/user-attachments/assets/b243fda0-c9a4-4f87-83f4-ee80fe05f327)
