### ISSUE TITLE
一个无法导入的 .sy.zip

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12444]
从这个回帖里下载的：https://ld246.com/article/1725440349684/comment/1726111004722#comments

[20240912110012-6j43ku9-4TnDIJC.sy.zip](https://github.com/user-attachments/files/16973019/20240912110012-6j43ku9-4TnDIJC.sy.zip)

[视频.webm](https://github.com/user-attachments/assets/00f5757a-1886-442f-a205-d94cd72010ef)

**Comment by 88250** [comment]
这个压缩包不是通过思源导出的，手动压缩的话结构不符合会导致这个问题。

**Comment by TCOTC** [comment]
确实哦，如果直接压缩 .sy 的话就会变成 .sy.zip
