### ISSUE TITLE
水平布局超级块内的表格样式问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12445]
https://ld246.com/article/1725440349684

[v3.1.3](https://github.com/siyuan-note/siyuan/releases/tag/v3.1.3)：

![image](https://github.com/user-attachments/assets/38d63b29-2219-4718-9bb3-c5a6ac020806)

[v3.1.6](https://github.com/siyuan-note/siyuan/releases/tag/v3.1.6)：

![image](https://github.com/user-attachments/assets/3a2a0ee2-dd3e-496a-9db3-4d388711ac09)

**Comment by Vanessa219** [comment]
由于 https://github.com/siyuan-note/siyuan/issues/12231 只能自行设置一下宽度
![QQ_1726127989734](https://github.com/user-attachments/assets/89b12daa-a380-4462-8255-540e2acac646)

**Comment by IQEQSQ** [comment]
我改这个宽度也只能解决一个表格，我有几百个表格，而且即使改完一个后，也没办法换行

**Comment by IQEQSQ** [comment]
这个问题能重新打开吗 @TCOTC

**Comment by Vanessa219** [comment]
这个是由于其他问题导致的，不行的话可以自定义 CSS

```
.protyle-wysiwyg [data-node-id].sb[data-sb-layout=col] > div {
        min-width: auto;
}
```

**Comment by IQEQSQ** [comment]
@Vanessa219 感谢，这个解决了我的问题
