### ISSUE TITLE
标签组合过滤

### ISSUE THREAD

**Issue by lbgws2** [siyuan-note/siyuan#12449]
### In what scenarios do you need this feature?

快速查找,筛选

### Describe the optimal solution

数据检索是个人知识管理中相当重要的一环,当个人知识库膨胀到上万条以上时,如何快速查找到自己需要的内容是个很大的挑战,如果不能在知识库中顺利检索到这条知识,那么这条知识就不存在

现有的利用关键词检索,很容易出现信息过载的情况,不能对内容进行很好的定位

而利用树形目录进行信息组织的方法也显得非常繁琐,更严重的问题是很多时候面临分类难题,比如说,我有一个git cheatsheet,我应该将它放在git相关目录,还是应该另建一个cheatsheet目录,存放所有的cheatsheet

我的设想是完全抛弃树形分类,完全使用标签进行分类,对任意一个文章,或者一个文字块,均可以打标签,
打标签时,后台自动检索所有标签组,并给出输入建议,
检索时,可以从已有的标签组给出输入建议,通过标签组合过滤的形式,来快速定位内容

我找到了一个有关标签组合过滤的实例
﻿
[IMDB 关键词](https://www.imdb.com/search/title/?keywords=mafia,murder&explore=keywords)
﻿
IMDB为每部电影标注了上百个关键词,通过对关键词的组合过滤(即同时包含多个关键词),可以快速找到自己感兴趣的相关电影
﻿
IMDB中存储了几百万部影视内容,在这样的数据量下,想要快速找到自己感兴趣的内容是非常困难的,标签组合过滤无疑是个非常有趣的数据筛选方法

**Comment by 88250** [comment]
这个估计不会改动了，请期待社区插件提供更好的搜索，感谢提议。
