### ISSUE TITLE
导出 PDF 时支持分页预览

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12441]
https://ld246.com/article/1726047969435

**Comment by Achuan-2** [comment]
浏览器打开后调用浏览器的打印思源笔记内容功能，这个思路可行嘛？

**Comment by TCOTC** [comment]
感觉不是很合理

**Comment by 88250** [comment]
Electron 没有打印预览功能，浏览器打印预览的话得先导出 SiYuan HTML 然后再在浏览器打开，比较绕路。
