### ISSUE TITLE
同步失败：网络超时，请稍后再试 (Provider: S3) v3.1.6

### ISSUE THREAD

**Issue by feng-yifan** [siyuan-note/siyuan#12443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

点击备份按钮，提示 “同步失败：网络超时，请稍后再试 (Provider: S3) v3.1.6”

### Expected result

能够正常同步

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/119933e4-ca6a-4153-8908-5d5a64ce91b8)

### Version environment

```markdown
- Version: v3.1.6
- Operating System: Windows11
- Browser (if used): N/A
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/16972852/siyuan.log)

### More information

该问题发生于今天早上，在问题发生之前没有对设置进行过变动，但是思源笔记被手动更新到了最新版本。

在问题发生后我切换了到了另一个 S3 服务，尝试全量同步已有笔记，参见日志，仅有部分文件能够上传。

日志中只提到了 `request context canceled caused by: context deadline exceeded`，这个信息太模糊了。有办法在日志中记录 S3 的返回信息么？

我查看了 S3 网关日志，对于一个空白的 bucket，日志显示：
- 接口创建了文件 `lock-sync`
- 正常上传了一些文件
- 开始出现客户端关闭连接
- 删除了 `lock-sync` 文件

对于被使用的 S3 服务，它工作正常。

**Comment by 88250** [comment]
```
E 2024/09/12 11:11:01 sync.go:1409: upload chunks failed: RequestCanceled: request context canceled
caused by: context deadline exceeded
```

这个指的是请求超时了，建议看下 S3 服务端日志。
