### ISSUE TITLE
列表 shift tab BUG

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1244]
### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/46141646/105612050-29d28d00-5df4-11eb-8b38-086032f89a6b.gif)
如图，在4处 shift tab 
结果出现了两个6，多了一个

### 期待的结果 Expected result

最后一行6不该出现

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/1240 中处理，感谢反馈。
