### ISSUE TITLE
导出预览和导出 PDF 时支持临时调整表格宽度

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12459]
“临时” 的意思是不会应用到文档中，只会影响导出

![image](https://github.com/user-attachments/assets/52804f07-e8ef-4279-8406-92c802d28a3d)

**Comment by 88250** [comment]
这个还是在文档中调整吧。

**Comment by TCOTC** [comment]
数据库导出的表格是无法调整的：

![image](https://github.com/user-attachments/assets/c22ffa1c-d0d4-4a02-9ac9-cfa8cec88300)

**Comment by 88250** [comment]
就这样吧



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月15日(周日) 上午8:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 导出预览和导出 PDF 时支持临时调整表格宽度 (Issue #12459)




 
数据库导出的表格是无法调整的：
 
image.png (view on web)
