### ISSUE TITLE
导出插件导出语雀文档失败

### ISSUE THREAD

**Issue by 879611427** [siyuan-note/siyuan#12456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

语雀文档导出失败
访问地址https://www.yuque.com/aceld/lfhu8y/hv3rqf

### Expected result

导入到思源笔记中，只导出了标题及一点点内容

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/83f70672-77a4-4d91-a866-52630230e338)

### Version environment

```markdown
3.1.6
```

### Log file

W 2024/09/13 09:16:09 sync.go:553: confirm [0] uploaded cloud [refs/latest] failed [local=6589576db1fcae71dd57061e5e7bf7fa7a6e3a1a, downloaded=4cabe9e000603bd4321ae1d8bfc105fb45d97f7f]
I 2024/09/13 09:16:09 s3.go:121: downloaded object [repo/indexes/4cabe9e000603bd4321ae1d8bfc105fb45d97f7f]
I 2024/09/13 09:16:09 s3.go:94: uploaded object [repo/refs/latest]
W 2024/09/13 09:16:09 sync.go:574: fix [0] uploaded cloud [refs/latest, 6589576db1fcae71dd57061e5e7bf7fa7a6e3a1a]
I 2024/09/13 09:16:10 s3.go:121: downloaded object [repo/refs/latest]
I 2024/09/13 09:16:10 sync.go:580: confirmed [1] uploaded cloud [refs/latest]
I 2024/09/13 09:16:10 sync.go:1382: updated latest sync [device=44a78fd8-ee93-4a03-9317-97ea04ffb796/windows, id=6589576db1fcae71dd57061e5e7bf7fa7a6e3a1a, files=281, size=23.25 MB, created=2024-09-13 09:16:07]
I 2024/09/13 09:16:10 s3.go:138: removed object [repo/lock-sync]
I 2024/09/13 09:16:10 repository.go:1343: synced data repo [device=44a78fd8-ee93-4a03-9317-97ea04ffb796, kernel=nyv00f3, provider=2, mode=a/false, ufc=5, dfc=3, ucc=1, dcc=0, ub=18.17 kB, db=22.04 kB] in [3.68s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/09/13 09:16:10 index_fix.go:50: start checking index...
I 2024/09/13 09:16:23 index_fix.go:71: finish checking index
W 2024/09/13 09:16:23 index_fix.go:91: exist more than one ref duplicated [20240905174406-bvv67dr], reindex it

**Comment by 88250** [comment]
你好，请到对应的插件仓库反馈。
