### ISSUE TITLE
支持禁用列表语法

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12458]
- [ ] `- ` `* `
- [ ] `1. `
- [ ] `[]` `[ ]` `- [ ]` `* [ ]`

![image](https://github.com/user-attachments/assets/effd3e80-31d7-4b28-9c4d-97cae1182d8d)

![image](https://github.com/user-attachments/assets/8c52adfe-c16e-41ec-bba7-fb1b2f713ad4)

**Comment by 88250** [comment]
块级语法不考虑取消了，不然可能会有 ID 索引问题。
