### ISSUE TITLE
改进包含图片的段落块编辑

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12452]
https://github.com/siyuan-note/siyuan/issues/11868#issuecomment-2207697375 以及往后的几条回复

**Comment by Vanessa219** [comment]
以上都无法重现， @88250 确认一下是否是 windows 的问题？

**Comment by 88250** [comment]
Del 向右删除了图片不是文字这个可以重现；Backspace 向左删除的重现不了。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by TCOTC** [comment]
确认 Backspace 的问题已经被解决了
