### ISSUE TITLE
Improve database block/text/asset/template/relation/rollup field sorting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12454]
数据库主键字段/文本字段支持更多排序方式

- [ ] 字母升序
- [ ] 字母降序
- [ ] 自然升序
- [ ] 自然降序

---

同时解决 https://ld246.com/article/1726154732885 遇到的问题

**Comment by 88250** [comment]
不添加额外的排序方式了，仅将默认的排序实现改为 字母排序 实现

**Comment by TCOTC** [comment]
那就没法实现自然排序的吧？

**Comment by 88250** [comment]
是的
