### ISSUE TITLE
列表 tab BUG 2

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1245]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/105612506-9d29ce00-5df7-11eb-82d7-64c5a040a5a7.mp4

如视频，拖拽调整后在5处按tab，没有反应

### 期待的结果 Expected result

拖拽调整后在5处按tab，出现应有的tab反应

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/1240 中处理，感谢反馈。
