### ISSUE TITLE
When creating new entry on filtered database view allow pre-populating properties with filter values

### ISSUE THREAD

**Issue by dvsekhvalnov** [siyuan-note/siyuan#12455]
### In what scenarios do you need this feature?

Hello, here is use case:

1. Database
2. View with filters on one or more properties, exact values match (e.g. `status=In progress`, `Is_internal=True`, e.t.c.)
3. Adding new row from the view insert all-empty values and showing banner: `The newly inserted rows has been filtered ` (see screenshot)
4. Have to navigate to other view to fill-in new row properties, which is annoying. 

Would it be possible to have an option in Database settings to pre-populate property values for new rows from the filter settings? 

<img width="451" alt="image" src="https://github.com/user-attachments/assets/a969e37c-70c2-4298-9575-2857c0be8df5">

### Describe the optimal solution

Option in Database settings to switch between current behavior and pre-populating properties from filter. 
Can be really handy to be able to add rows from filtered view and stay in a same view for further editing.

**Comment by 88250** [comment]
Sorry, there is no other way except to switch to the full view without sorting/filtering. It is recommended to add data in the full view.
