### ISSUE TITLE
鼠标历史点击位置 前进和后退 的跳转 功能

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1246]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
![image](https://user-images.githubusercontent.com/46141646/105613179-13303400-5dfc-11eb-8155-e2fd56bbc5e0.png)

如图，这是idea的代码跳转功能

在思源中：
记笔记时候想看看一个文档：ctrl p 找到后，希望快捷返回刚刚编辑的位置
看笔记的时候，想看看双链的内容：ctrl 左键后，希望快捷返回ctrl 左键的位置
看笔记时候：希望跳回上一个鼠标点击的位子
…

### 描述最优的解决方案 Describe the optimal solution

希望提供 鼠标历史点击位置 前进和后退 的跳转 功能

**Comment by 88250** [comment]
请关注 #239
