### ISSUE TITLE
数据库支持粘贴带结束时间的日期

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12463]
目前无法粘贴这种文本为日期：

[视频.webm](https://github.com/user-attachments/assets/73c55537-289d-4782-8cc5-757db3f743c9)

> #11973 的延伸

**Comment by Jiangshuon** [comment]
希望空格或者其他符号分隔都能匹配

**Comment by TCOTC** [comment]
确实，比如 `2024/9/14 ~ 2024/9/15`

**Comment by Vanessa219** [comment]
目前就先用 `→`, `-`, `~` 这几个进行判断吧。
空格的话时间和年份之间也会存在，就不加入了。

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/11973
