### ISSUE TITLE
导出预览时无法使用大纲

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12464]
[视频.webm](https://github.com/user-attachments/assets/63ccfc46-4749-49c0-a196-72427eb42b02)

**Comment by TCOTC** [comment]
应该与 #11981 是同一个问题，只不过这次是导出预览的大纲用不了

**Comment by 88250** [comment]
现在没有问题了？

**Comment by TCOTC** [comment]
Duplicate of #11981

**Comment by TCOTC** [comment]
更诡异的问题出现了：点击大纲会把文档切换为导出预览

[视频.webm](https://github.com/user-attachments/assets/b7dc6a6b-35fe-4a14-af8c-cf873258f188)
