### ISSUE TITLE
导出预览需要显示嵌入块内的标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12465]
或许与 #12233 有关联

![image](https://github.com/user-attachments/assets/0b8a6a77-05ec-45f0-b50c-0b82990b0b6f)

**Comment by TCOTC** [comment]
@88250 这个 issue 是不是应该跟 #12469 一样关掉？

**Comment by 88250** [comment]
呃， 是的，引述块中的标题不计入大纲啊。
