### ISSUE TITLE
单选多选列添加选项时支持通过按钮添加

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12460]
目前只能按 Enter 来添加，可能会有用户不知道应该按 Enter ，我提议把这里做成一个按钮，点击之后添加选项：

![image](https://github.com/user-attachments/assets/1b704ec6-e72d-4f60-b8de-d31c28458142)

**Comment by 88250** [comment]
这个应该不是问题，类 Notion 的交互都是这样的，用户知道的。

**Comment by TCOTC** [comment]
但不用 Notion 的用户不能被忽略啊

**Comment by 88250** [comment]
先不管了，提示已经做到位了。
