### ISSUE TITLE
可以用post请求发送卡片吗？文档里没有找到请求体body

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#12466]
### In what scenarios do you need this feature?

fetch('http://127.0.0.1:6806/api/setting/setFlashcard', {
  method: 'POST',
  headers: {
    'Authorization': 'Token dxnssnq2vo6n1rbt',
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    id: "20240913111507-ajk53r7",
   decks: "20230218211946-2kw8jgx"
})
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));

### Describe the optimal solution

1

**Comment by 88250** [comment]
可以在开发者工具网络中抓包作为参考。
