### ISSUE TITLE
导出的 PDF 没有嵌入块中的标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12469]
或许与 #12233 有关联

![image](https://github.com/user-attachments/assets/e70fd899-ab80-4abf-91a7-ba9317de7e80)

**Comment by 88250** [comment]
我没看明白你提的问题，请打包 .sy.zip 我这边测试看看。

**Comment by TCOTC** [comment]
[导出 PDF.sy.zip](https://github.com/user-attachments/files/16995140/PDF.sy.zip)
[导出 PDF.pdf](https://github.com/user-attachments/files/16995143/PDF.pdf)

我的意思就是打开 PDF 之后，嵌入块里的标题没有算在标题里，不能用于跳转：

![image](https://github.com/user-attachments/assets/e7cb65d6-ba37-489b-a032-de69b1f06060)

**Comment by 88250** [comment]
引述块里的标题都不计入大纲的。

**Comment by 88250** [comment]
那个是导出设置中以原文导出时才起作用。
