### ISSUE TITLE
使用 /api/av/appendAttributeViewDetachedBlocksWithValues 给数据库添加行时应同时给select和mSelect列添加options

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#12475]
### In what scenarios do you need this feature?

目前使用/api/av/appendAttributeViewDetachedBlocksWithValues给数据库添加行时只是简单点往values数组里增加了一个对象，key没有变化。

### Describe the optimal solution

单选和多选列添加values的同时应更新key的options，如果value有定义了新option的color，则使用定义颜色，否则自动为新选项设置颜色。

**Comment by 88250** [comment]
感谢反馈，示例：

```json
{
    "avID": "20240914171218-ao9tg2z",
    "blocksValues": [
    [
      {
        "keyID": "20240914171218-o763bsk",
        "block": {
          "content": "Test block"
        }
      },
      {
        "keyID": "20240914171218-x5xqz9m",
        "mSelect": [{
            "content": "opt 2",
            "color": "4"
        }]
      }
    ]
  ]
}
```

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
