### ISSUE TITLE
文件历史操作增加 `回滚` 类型

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12471]
跟 #12470 配合，便于用户撤销错误的回滚操作

![image](https://github.com/user-attachments/assets/c5621d06-2bff-4b1d-ba00-2c253a4c6fea)

然后再把回滚文件历史和回滚数据快照的提示 “回滚操作无法撤销，确定要将 xxx 回滚吗？” 分别改为：

- “确定要将 xxx 回滚吗？之后能在文件历史中再次回滚 ”回滚“ 操作以撤销”
- “确定要将 xxx 回滚吗？之后能在数据快照中再次回滚最新的快照以撤销”

**Comment by 88250** [comment]
回滚本质上不是数据变更，所以不考虑在这里加入了。
