### ISSUE TITLE
Loading screen popup messages no longer block UI loading

### ISSUE THREAD

**Issue by Nyeilim** [siyuan-note/siyuan#12476]
疑似插件加载会阻塞思源打开

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在思源加载界面时候，会弹出插件加载的对话框，需要点击确定，才能进入编辑界面。和插件作者讨论过，更多讨论详情，[参见](https://github.com/WingDr/siyuan-plugin-citation/issues/89)。

### Expected result

思源在进入界面时，不应该受到插件加载的阻塞。

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/f380c83f-61a5-4d87-bd71-70a48bc24182)

### Version environment

```markdown
- Version: v3.1.6
- Operating System: Windows 11
-  (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17001585/siyuan.log)

**Comment by 88250** [comment]
应该是 alert 阻塞界面了，看看是不是能换成自己实现的弹框？

 @Vanessa219

**Comment by TCOTC** [comment]
> 换成自己实现的弹框

能解决 #12349 吗？
