### ISSUE TITLE
When rolling back a snapshot, a snapshot is created for the current data by default

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12470]
回滚快照时，如果近期没有创建过快照，弹窗提示用户创建一个快照

比如“回滚后无法恢复，是否要先创建一个当前的快照？”之类的，点“是”就创建快照

用于预防这种情况：https://ld246.com/article/1726235369321

**Comment by 88250** [comment]
为了数据安全，回滚快照之前默认创建一个快照吧。
