### ISSUE TITLE
v3.1.6 导出data 失败

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

工作空间大小5GB，导出data，会一直显示正在导出，无法真正导出（等了一晚上也是这样）
但试了下新建一个工作空间是可以快速导出的

### Expected result

正常导出data

### Screenshot or screen recording presentation

![Clip_2024-09-14_11-02-19](https://github.com/user-attachments/assets/0d4208b5-fdf8-4605-8d29-850b1e8fa334)

### Version environment

```markdown
- Version: v3.1.6
- Operating System: Win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/user-attachments/files/17000695/system-log.zip)

**Comment by 88250** [comment]
导出 data 的时候会有进度遮罩，上面会实时输出导出文件，观察一下是否有变化。

另外，稍后会添加点日志，请等 v3.1.7-dev3 导出测试并上传日志。

**Comment by 88250** [comment]
dev3 已经发布，麻烦测试看看，谢谢。

**Comment by Achuan-2** [comment]
导出data进度遮罩没有实时显示导出文件，一段时间遮罩就自动关闭了
![Clip_2024-09-16_11-14-21](https://github.com/user-attachments/assets/9bfd4c30-7405-401a-9fb5-5ef99fe98759)
日志：
[system-log (1).zip](https://github.com/user-attachments/files/17008348/system-log.1.zip)

**Comment by TCOTC** [comment]
话说我硬盘满了的时候也会这样，研究半天才发现是因为硬盘已经满了。我觉得需要处理一下我这种情况

**Comment by Achuan-2** [comment]
![Clip_2024-09-16_11-32-38](https://github.com/user-attachments/assets/2c59f94a-9a72-4c01-a4fa-f2c49be39db0)
各个盘都没满，我也是导出到C盘的

**Comment by 88250** [comment]
应该是在复制数据，导出 data 需要把 data 先复制到一个临时目录，估计是文件太多，复制太慢了。

如果不是固态硬盘的话试试换固态硬盘，其他应该没啥办法了，系统不休眠的话在等等看。

**Comment by Achuan-2** [comment]
就是固态硬盘，之前试过导出一晚上，完全没有动静，感觉还是有bug的，遮罩也就十几秒就消失了

**Comment by 88250** [comment]
导出的时候观察一下导出路径上是否有文件生成



---原始邮件---
发件人: "Jixiong ***@***.***&gt;
发送时间: 2024年9月16日(周一) 中午12:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] v3.1.6 导出data 失败 (Issue #12473)




 
就是固态硬盘，之前试过导出一晚上，完全没有动静，感觉还是有bug的，遮罩也就十几秒就消失了，后面就完全没有动静了

**Comment by Achuan-2** [comment]
没有文件生成
我的data文件夹
![Clip_2024-09-16_12-57-13](https://github.com/user-attachments/assets/44408d5f-cbb0-4ef3-b9bd-1b44407a3995)
导出时生成的temp文件夹：少了一些文件夹
![Clip_2024-09-16_12-57-48](https://github.com/user-attachments/assets/c0a095be-3987-4b39-a912-071c24a339c2)

**Comment by Achuan-2** [comment]
我知道原因了，我之前有自己开发插件，插件文件夹node_modules，文件太多就导出失败了
建议导出data，排除node_modules文件夹

**Comment by TCOTC** [comment]
我觉得导出文件时应该先预估大小，如果磁盘空间不足的话就弹窗制止导出

**Comment by 88250** [comment]
@Achuan-2 跳过文件有点风险，还是全部打包比较可靠。

@TCOTC 稍后在桌面端添加

**Comment by Achuan-2** [comment]
@88250 node_modules文件夹会被同步吗

**Comment by 88250** [comment]
会的



---原始邮件---
发件人: "Jixiong ***@***.***&gt;
发送时间: 2024年10月11日(周五) 晚上6:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] v3.1.6 导出data 失败 (Issue #12473)




 
@88250 node_modules文件夹会被同步吗

**Comment by Achuan-2** [comment]
那还是希望导出全部data时不导出插件下的node_modules，以及不同步node_modules
不然每次开发完还得手动删，或者用软链接
