### ISSUE TITLE
在 思源 - 设置 - 代码片段 中添加一个 社区分享 超链接按钮

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12477]
https://ld246.com/article/1726222956996/comment/1726307348366#comments

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by TCOTC** [comment]
这个按钮要不也显示给繁体中文用户？

**Comment by 88250** [comment]
非大陆手机号注册不了链滴



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月15日(周日) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 在 思源 - 设置 - 代码片段 中添加一个 社区分享 超链接按钮 (Issue #12477)




 
这个按钮要不也显示给繁体中文用户？

**Comment by TCOTC** [comment]
话说现在链滴不用登录就能看了，是不是可以加按钮了？

**Comment by 88250** [comment]
不加了，保不齐哪天又要登录才能浏览。
