### ISSUE TITLE
打开的链接块在文档树中高亮显示所在位置

### ISSUE THREAD

**Issue by changxf123** [siyuan-note/siyuan#12479]
### In what scenarios do you need this feature?

打开的链接块，在文档树中高亮显示名称，或者高亮显示其所在的主干名称，已表明其在文档树中所处的位置。

### Describe the optimal solution

希望得到改进

**Comment by TCOTC** [comment]
建议使用这个功能：

![image](https://github.com/user-attachments/assets/127a5b14-03a5-4191-9854-fb7be1a29c5a)
