### ISSUE TITLE
保存布局时需要保存文档树状态并在使用布局时对其进行还原

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#12485]
那就先不考虑保留了。

再解决一下这个需求：

> 保存布局时也保存文档树状态

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/10652#issuecomment-2351344488_

**Comment by 5kyfkr** [comment]
这个确实得整，不然一换布局又白给了

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.

**Comment by 5kyfkr** [comment]
> 这个改动就不拉进版本了。 This change will not be included in the version.

啥时拉进去？

**Comment by TCOTC** [comment]
意思是不添加进版本日志

**Comment by 5kyfkr** [comment]
> 意思是不添加进版本日志。代码是合进去了的。

了解，还以为要等下版本了

**Comment by TCOTC** [comment]
@88250 这个说法我每次看都觉得很怪，改成下面这个吧：

这个改动不添加进[里程碑](https://github.com/siyuan-note/siyuan/milestones)。

This change will not be added to the [milestone](https://github.com/siyuan-note/siyuan/milestones).

**Comment by 88250** [comment]
差别不大....



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月16日(周一) 中午12:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 保存布局时需要保存文档树状态并在使用布局时对其进行还原 (Issue #12485)




 
@88250 这个说法我每次看都觉得很怪，改成下面这个吧：
 
这个改动不添加进里程碑。
 
This change will not be added to the milestone.

**Comment by TCOTC** [comment]
> 差别不大....

至少有一个链接能让别人明白是不添加进了什么

**Comment by 88250** [comment]
这个就是不想和版本关联哦



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月16日(周一) 中午1:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 保存布局时需要保存文档树状态并在使用布局时对其进行还原 (Issue #12485)




  
差别不大....
  
至少有一个链接能让别人明白是不添加进了什么

**Comment by TCOTC** [comment]
没看懂你的意思

**Comment by 88250** [comment]
> 这个改动就不拉进版本了。
> This change will not be included in the version.

不和任何版本关联。
