### ISSUE TITLE
New Notebook button should NOT be hidden behind the submenu

### ISSUE THREAD

**Issue by lynrayy** [siyuan-note/siyuan#12481]
### In what scenarios do you need this feature?

I'm new in this software and want to complain about the UI. Why MOST important button is hidden behind sub-menu? It should be on the most visible place!
![image](https://github.com/user-attachments/assets/eb5c4e5f-a472-4ce3-b917-6d141780d63d)

### Describe the optimal solution

Place Plus button in the main page (Plus button = New Notebook option)

**Comment by lynrayy** [comment]
Also i don't want to see colored icons near the document title. Why can't i disable this? Is it so hard to copy Notion style?
![image](https://github.com/user-attachments/assets/c5868b66-fc9a-4364-8914-4b0364cddaf2)
![image](https://github.com/user-attachments/assets/9e38a19e-02b9-4d35-81a2-61b8c67ec0ec)

**Comment by lynrayy** [comment]
Also drag and dropping document inside document should create link to it instead of merging documents!

JUST COPY NOTION WHY YOU CANT DO THOSE SIMPLE THINGS WTF???
![image](https://github.com/user-attachments/assets/74017c53-a56d-4ed1-81b1-2024ef89e8e8)

**Comment by lynrayy** [comment]
![image](https://github.com/user-attachments/assets/4524998d-bc28-4de1-a712-13611d29618a)

**Comment by 88250** [comment]
* Creating a notebook is not a high-frequency operation, so it is placed in the secondary menu
* SiYuan is not a copy of Notion

Thanks.

**Comment by lynrayy** [comment]
SiYuan is not a copy of Notion

Unfortunately
