### ISSUE TITLE
改进手动创建快照的流程

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12488]
- 点击 `创建快照` 按钮时检查文件变化

	- 如果无变化，则提示 "已存在最新的快照。检查数据快照耗时 XXs" ，不弹窗请求用户输入快照备注（可以避免这种情况：[手动创建快照后，备注不显示 - 链滴](https://ld246.com/article/1673179724740)）

	- 如果有变化，则弹窗请求用户输入快照备注，并且支持无备注的快照（或者默认备注为 "Create manually" 之类的），便于快速手动创建快照

**Comment by 88250** [comment]
这个需要扫描以后才能知道是否有变化，所以技术上不可能做到，保持目前的设计不变了，谢谢。

**Comment by TCOTC** [comment]
我的意思就是先扫描

**Comment by 88250** [comment]
等后面看反馈吧，这个提升并不是太关键，因为如果能创建快照的话就直接创建了，没有副作用。

**Comment by TCOTC** [comment]
主要是两个地方有点难受：

1. 如果快照创建不了的话刚写的快照备注也消失了
2. 创建快照必须要备注

**Comment by 88250** [comment]
也许可以加点默认变动，比如某个文件的写入？

**Comment by TCOTC** [comment]
> 加点默认变动

这样能顺便解决回滚之后同步会被云端覆盖的问题吗：

![image](https://github.com/user-attachments/assets/5d26862b-5f25-4125-8637-29e463830aec)

**Comment by 88250** [comment]
不能，同步是双向合并的，如果要覆盖，只能手动上传快照。
