### ISSUE TITLE
支持 `Alt+拖拽` 文档树上的文档到编辑器里插入块引用

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12482]
比如拖拽到这里：

![image](https://github.com/user-attachments/assets/964d56e8-d5ca-4fbf-8dd2-7b7dc9eb19a4)

关联 https://github.com/siyuan-note/siyuan/issues/12481#issuecomment-2351105644

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
