### ISSUE TITLE
悬浮窗无法上下滑动

### ISSUE THREAD

**Issue by YotsubaAina** [siyuan-note/siyuan#1248]
### 描述问题 Describe the problem

测试图片: 
https://i.loli.net/2021/01/23/dFj1eJh7gTKO6tM.jpg
https://i.loli.net/2021/01/23/Qrz2ENjUmDsHAkM.jpg

初次加载引用的内容块或文档, 因需要一定的加载时间会导致悬浮窗无法上下滑动
而且点击标题栏后, 悬浮窗窗口会占满应用全屏, 只能左右移动, 依旧无法上下滑动.
加载完后再悬浮就没问题了.

### 期待的结果 Expected result

希望初次加载时悬浮窗可以根据内容加载的情况自动调整, 每次要等到加载完有点影响体验

### 截屏或录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/74671505/105619438-bd747f80-5e2d-11eb-83c7-93d854bcf8a2.mp4

### 版本环境 Version environment

* 版本 Version：v0.6.6 / Kernel v0.6.6
* 操作系统 Operating system：win10 LTSC

**Comment by 88250** [comment]
请试下默认主题是否有问题，谢谢。

**Comment by YotsubaAina** [comment]
> 请试下默认主题是否有问题，谢谢。

使用默认主题依然有相同的问题，而且很难按到标题栏的按钮。

https://user-images.githubusercontent.com/74671505/105622837-b199b500-5e4f-11eb-9262-51074893698e.mp4

**Comment by Vanessa219** [comment]
弹层的高度是自适应的，只有超出范围才会去设置高度，因此第二次加载，图片有缓存，可以及时计算高度。这个受限于图片的加载速度，目前暂不解决了。

上下拖动下个版本解决
