### ISSUE TITLE
把 粘贴/剪藏 和 输入 分离，关闭 Markdown 语法输入不应影响粘贴和剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12489]
应该要把 粘贴/剪藏 和 输入 分离一下，否则关闭之后就复制的 HTML 就粘贴不成加粗和斜体了/剪藏网页没有加粗和斜体

p.s. 我印象中当时 #11141 也有这个问题，后面解决了？

![image](https://github.com/user-attachments/assets/b7853bd7-82c0-4f03-a05a-4b46c1e3f088)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/11206#issuecomment-2351578801_

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/11604 中考虑，谢谢。
