### ISSUE TITLE
数据库链接字段里如果不是链接，点击后的效果应该是编辑单元格

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12483]
目前不是链接也能点击“打开”：

![image](https://github.com/user-attachments/assets/f207d49f-4238-4976-86b3-bbb936b5af5f)

在 Notion 中如果不是链接，点击之后是编辑单元格：

![image](https://github.com/user-attachments/assets/4576cbcc-f665-4feb-86f0-7baf7ba425b2)

**Comment by Vanessa219** [comment]
notion 上没有协议开头或者写为 siyuan:// 都是无法打开的。这样虽然是优化，但也是限制。
