### ISSUE TITLE
数据库数字字段的菜单增加 `默认填充 0` 选项

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12494]
我觉得在菜单里增加一个 `默认填充 0` 的选项会更方便：

![image](https://github.com/user-attachments/assets/65ebf021-7377-474f-83cb-5c6925ccce79)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/12491#issuecomment-2351867218_

**Comment by 88250** [comment]
感谢提议，但是不考虑了，可以使用划选填充。
