### ISSUE TITLE
某网页无法剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12495]
网址：https://zhongce.sina.com.cn/article/view/72751

剪藏后：

![image](https://github.com/user-attachments/assets/c98d9440-4270-4e4c-939e-7b3a9b88f682)

关联 https://ld246.com/article/1726423900988

**Comment by 88250** [comment]
需要升级剪藏扩展。

这个改动就不拉进版本了。
This change will not be included in the version.
