### ISSUE TITLE
Document tree supports "Open with same New Window"

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12490]
在文档树上多选文档，选择在新窗口打开，应该在同一个新窗口打开这些文档

目前是每个文档都打开了一个新窗口，逻辑很怪。

比如在页签右侧或下侧打开都是一起的，打开新窗口时页签也应该是在一起的。

**Comment by 88250** [comment]
这个设计保持不变了，感谢反馈。

**Comment by TCOTC** [comment]
那加一个“在同一新窗口打开”的菜单项行不行？现在没有办法批量在新窗口打开文档

**Comment by 88250** [comment]
这个应该可以有。

**Comment by TCOTC** [comment]
补充，在多选文档时添加选项到这里：

![image](https://github.com/user-attachments/assets/5cf57ff2-1480-48eb-835b-e3c5f8690abe)

**Comment by Vanessa219** [comment]
菜单保持不变，支持多个打开的时候是在一个 window 上。
