### ISSUE TITLE
Subdocument path not updated after moving parent document

### ISSUE THREAD

**Issue by Misuzu2027** [siyuan-note/siyuan#12493]
当移动的文档存在子文档，移动后，子文档在sqlite数据库中的box、path、hpath 没有更新。

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当移动的文档存在子文档，移动后，子文档在sqlite数据库中的box、path、hpath 没有更新。

### Expected result

更新子文档的数据库数据

### Version environment

```markdown
- Version: v3.1.6
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
感谢反馈，我这里测试 hpath 会更新，box 和 path 没有更新，下个版本修复。
