### ISSUE TITLE
移动端_输入法bug

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#12496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/user-attachments/assets/b229ce48-b792-494b-9490-8d8ae54f40a0

### Expected result

看视频

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by TCOTC** [comment]
录屏没有录制到手指的操作，请在录屏设置中开启。或者用文字描述一下你的操作

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/4826

**Comment by 88250** [comment]
我这里在 iOS 17.6 搜狗输入法 11.55 上无法重现该问题，请看下你的版本。

**Comment by leommjj** [comment]
发自我的 iPhone在 2024年10月14日，22:51，D ***@***.***> 写道：﻿
我这里在 iOS 17.6 搜狗输入法 11.55 上无法重现该问题，请看下你的版本。

**Comment by leommjj** [comment]
> 我这里在 iOS 17.6 搜狗输入法 11.55 上无法重现该问题，请看下你的版本。

ios18.1

**Comment by 88250** [comment]
iOS 18 目前还在 Beta 测试吧，建议等正式版发布以后再试试，谢谢。

**Comment by leommjj** [comment]
> iOS 18 目前还在 Beta 测试吧，建议等正式版发布以后再试试，谢谢。

![image](https://github.com/user-attachments/assets/99dc510c-75ba-438b-99a7-d78588e0dfcb)
zhengsban正式版很早就推了

**Comment by 88250** [comment]
我们后续会再收集反馈看看。
