### ISSUE TITLE
Mermaid中的KaTeX数学公式渲染问题

### ISSUE THREAD

**Issue by idealkindom** [siyuan-note/siyuan#12501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

同样的语法，在文本中以KaTex输入和渲染没问题，到了Mermaid中就出现了问题（已确认是双$包围）
```mermaid
graph TD
A[12]-->B[$$R=R\lparen f_c,f_y,a_k,...\rparen/\alpha_{Rd}$$];
A-->C[$$R=R\lparen f_c,f_y,a_k,...\rparen/\gamma_{Rd}$$]
```
同时附上截图：
<img width="603" alt="mermaid KaTeX" src="https://github.com/user-attachments/assets/9ea681d2-66c9-488e-bebd-c0956998e062">

### Expected result

Mermaid应该能正常渲染节点的KaTeX公式才合理

### Version environment

```markdown
- Version: 3.1.6
- Operating System: Win 10 X64
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17016880/siyuan.log)

**Comment by idealkindom** [comment]
问题好像出在最后一个带下标的希腊字母，但是KaTeX本身OK，Mermaid却不行，可能是Mermaid的bug？？

**Comment by 88250** [comment]
应该是 mermaid 的问题，我在官网上测试也报错 https://mermaid.live/edit

**Comment by 88250** [comment]
可以看看 mermaid issues 上是否已经有记录，没有的话提一个，谢谢。

**Comment by idealkindom** [comment]
已提

在 2024-09-18 11:50:56，D ***@***.***> 写道：


可以看看 mermaid issues 上是否已经有记录，没有的话提一个，谢谢。
