### ISSUE TITLE
个别主题明暗切换theme.js问题

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [siyuan-note/siyuan#12508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

主题在切换浅色和深色模式时有可能会重启思源，又有可能不会重启思源。具体表现在两个模式使用同一个主题，切换颜色模式后有些主题效果不生效，同时theme.js移除了主题元素又不添加回来。需要重新加载思源页面或者重启思源。
使用主题VSCode Lite Edit复现，使用其他主题未见复现。可能是触发了主题卸载事件又没有触发加载事件。

### Expected result

在执行theme.js移除主题之后再执行theme.js的加载来加载主题，切换主题后主题显示效果正常。或者同样主题切换颜色模式触发刷新来重新加载主题。

### Screenshot or screen recording presentation

https://github.com/user-attachments/assets/005b1d93-075a-4b81-90aa-86af38941f64

### Version environment

```markdown
- Version: 3.1.6
- Operating System: Windows 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17031988/siyuan.log)

### More information

这种情况可以在theme.js中添加什么来避免呢？写了window.destroyTheme()和（function(){})()，但是似乎在切换主题颜色模式的时候会出问题。可能是主题卸载事件意外触发导致的？

**Comment by TCOTC** [comment]
你的视频我播放不了，你自己能看到吗？

**Comment by lingfengyu-dreaming** [comment]
> 你的视频我播放不了，你自己能看到吗？

可以播放，浏览器和APP都可以
手机没法预览，这个可以渲染成视频吗
![Video](https://github.com/user-attachments/assets/005b1d93-075a-4b81-90aa-86af38941f64)

**Comment by lingfengyu-dreaming** [comment]
太脑残了，我把问题排除出来了，我的错

**Comment by TCOTC** [comment]
发现是啥问题？

**Comment by lingfengyu-dreaming** [comment]
> 发现是啥问题？

我的js里面用`const`声明了一个全局变量，这个变量本来是初始化配置文件用的，理论上只用到一次且全局不变。前几个版本都没有问题，切颜色主题也不报错，现在出问题了，切主题没有重新加载会重复声明，js就会报错，改成`var`就可以了。
真不懂什么原因，之前没问题我就没管
