### ISSUE TITLE
列表 tab BUG3

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1250]
### 描述问题 Describe the problem
![image](https://user-images.githubusercontent.com/46141646/105621994-52847200-5e48-11eb-867e-3e3241dfd771.png)
如图，如果光标在7、8、9前面，按tab：会直接跳转到页面头部，这样不是预期的动作

### 期待的结果 Expected result

目前在7、8、9前面，按shift tab会执行 列表项反向缩进
故此，**希望 在7、8、9前面，按tab 会执行 列表项正向缩进**

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/1240 中处理，感谢反馈。
