### ISSUE TITLE
改进数据库模板字段筛选（需要剔除注释内容）

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12504]
### 用户反馈：

![image](https://github.com/user-attachments/assets/25ded578-008f-4e0e-b2cc-2c2db049bd1b)

### 复现方法：

使用模板：

```
2<!--7-->
```

筛选条件：`包含 7`

![image](https://github.com/user-attachments/assets/838a0663-4f4a-47c9-98c3-bfa4a78b949f)

**Comment by 88250** [comment]
使用 `.action{/* 7 */}` 插入注释。
