### ISSUE TITLE
Bigger OCR text area field + 

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12503]
### In what scenarios do you need this feature?

When need to view image OCR text field... It is too small if the image text is paragraph.
![image](https://github.com/user-attachments/assets/3732d91f-2491-4d23-a731-f67c8d055c18)

### Describe the optimal solution

1. Increase and save the text area field size depend on user's resizing.

2. Maybe add "OCR" icon at right-top side:
 to create/edit/delete OCR text **manually** like document-preview... 
Because for some image, I dont need OCR, some hand-written image OCR it get wrong characters

5. Can you implement an warn notification if the OCR process **go wrongs** (greater than limit_size, I/O error...) ... If it success, it go  silent.

Thank you for your app...I really impressed with the work of you...

**Comment by 88250** [comment]
Hello, the OCR text box size cannot be memorized, so you can only drag it each time you use it. Maybe you can try to specify the size through a custom code snippet CSS/JS.

If OCR reports an error, there should be a record in the kernel log, please refer to the log file.
