### ISSUE TITLE
百度百科的剪藏，能否优化一下？

### ISSUE THREAD

**Issue by asasn** [siyuan-note/siyuan#12502]
### In what scenarios do you need this feature?

好比说，“难念的经”这个词条。
https://baike.baidu.com/item/%E9%9A%BE%E5%BF%B5%E7%9A%84%E7%BB%8F/4163438
一、缺乏“相关星图”栏目底下的基本信息
![image](https://github.com/user-attachments/assets/ca2389fc-f9ce-4a84-8b92-b4fa6fe99c8f)

二、把“播报”、“编辑”这些多余的文字也添加进去了，能否去除？
![image](https://github.com/user-attachments/assets/f4d6094f-4bbe-4c9c-bafe-6c93fc108b47)

### Describe the optimal solution

百科之类，是个人比较喜欢的资料收集渠道，盼望能够针对各种百科进行优化。

**Comment by 88250** [comment]
稍后改进，但是这里没有办法分隔，只能做到如下效果：

![image](https://github.com/user-attachments/assets/6508c08d-ca9b-4e36-85c9-f61611178ff2)

需要升级剪藏扩展；这个改动不拉进版本了。
