### ISSUE TITLE
I have a question about export notebook as markdown...

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12505]
### In what scenarios do you need this feature?

As I have tested the export function... I find that the **ref to heading/file_path of another md file** isn't supported... 

Is this technically can't be done or it is not yet implemented? ... Because in the worst case of far future if I have to drop this app, at least I can export "notebook" as "md folder and can ref to each other at least by file_path/heading" ....

### Describe the optimal solution

...

**Comment by 88250** [comment]
Try this:

![image](https://github.com/user-attachments/assets/54874703-177a-40f2-bdb8-c65b98371293)
