### ISSUE TITLE
Turn inline tag into text is empty

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [x] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Given inline tag... If you "RClick -> Turn into Text" ... 
1. It is deleted completly
2. If I trigger "redo" action, it can't function properly... It seems like "redo" don't work

### Expected result

.....bbbb

### Version environment

```markdown
- Version: v3.1.6 desktop-app
- Operating System: Window
- Browser (if used):
```

### Log file

.....

**Comment by 88250** [comment]
Thanks for the feedback, this issue should have been fixed in the latest dev version.
