### ISSUE TITLE
Option to choose 'Show As' for numbers in database views (bar, ring, e.t.c.)

### ISSUE THREAD

**Issue by dvsekhvalnov** [siyuan-note/siyuan#12515]
### In what scenarios do you need this feature?

Database view, want to display numbers (templated properties as well) as visual indicators (ring, bar, e.t.c.).

Here is a screenshot from other note taking app how to choose 'show as' option:
![image](https://github.com/user-attachments/assets/74c8a96c-e1e5-4b19-8a8d-78139619c0fb)

And here is how it looks like in database view:
![image](https://github.com/user-attachments/assets/ec73f422-5d5b-4505-836c-054c8a42d97d)

P.S> Sorry if it is duplicate again, hard to search in Chinese. May be you guys can outline some roadmap in English too?

### Describe the optimal solution

Add 'Show As' option for columns of type number (including rollups and templated). With some predefined set of 'visualizations'. 

Allow color selection for 'visualizations' will be superb.

**Comment by TCOTC** [comment]
好想法！我提供一个中文的 Notion 截图作为参考：

![image](https://github.com/user-attachments/assets/97534d02-274b-4c15-902c-a1adb6f154de)

**Comment by TCOTC** [comment]
@dvsekhvalnov Hi! I've updated my previous reply, maybe it will be informative for you.

**Comment by dvsekhvalnov** [comment]
@TCOTC thanks for the tip, can try that.

Still think built-in option can be easier though :)

**Comment by 88250** [comment]
Thanks for the suggestion, but template fields should expand this part.
