### ISSUE TITLE
Improve image width setting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12516]
图片宽度问题

> 关联 #12423

### 01 比例问题

之前是按编辑器的宽度，所以四张 25% 宽度的图片刚好可以排放在一个块内。

现在是按窗口的宽度，之前的图片排版就都乱了。

### 02 图片标题宽度问题

https://ld246.com/article/1727180114061
![image](https://github.com/user-attachments/assets/60f15d27-7a5a-4538-85b5-d028f0c7b17f)

会导致标题宽度超过图片宽度，然后菜单按钮和光标都会偏移：

![image](https://github.com/user-attachments/assets/9a3ba955-9e0a-4f30-99d7-5907fe280e9c)

**Comment by TCOTC** [comment]
@Vanessa219 我觉得图片宽度的这个问题影响比较大

**Comment by TCOTC** [comment]
用户反馈：

- https://ld246.com/article/1729040540186

**Comment by Misuzu2027** [comment]
我试了下 v3.1.14-dev5 版本，发现给图片设置高度还是给 img 标签修改样式，F5 刷新后会发现修改图片高度没有生效。

**Comment by TCOTC** [comment]
宽度也有问题

[video.webm](https://github.com/user-attachments/assets/6002e7a9-2385-46eb-b859-556d74aa590b)

**Comment by 88250** [comment]
稍后调整

**Comment by pisceswb** [comment]
https://ld246.com/article/1733232175688
3 张宽度为 33% 的图片，不能在同一排中

**Comment by wish5115** [comment]
> https://ld246.com/article/1733232175688 3 张宽度为 33% 的图片，不能在同一排中

我这边32%就好了，图片之间可能有些间距啥的吧，如果你那边有问题可以再小点试试。
