### ISSUE TITLE
及时刷新被引用块的 refcount 属性

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12512]
需要跟引用计数同步刷新，计数为 0 时及时移除 refcount 属性

**Comment by 88250** [comment]
麻烦截图看下是哪部分的 DOM

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/17cf5a1c-9df6-4958-9d7c-1a018ccc09a9)

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
