### ISSUE TITLE
增加标题编号

### ISSUE THREAD

**Issue by lhx-JIPS** [siyuan-note/siyuan#1251]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

目前不同级别的标题前面没有编号，比如1、1.1、1.1.1、2、2.1、2.1.1等，依靠提示符H2、H3以及字体大小等不够直观。希望增加编号功能。

### 描述最优的解决方案 Describe the optimal solution

可以默认显示标题编号，如果某个特殊标题不想设置编号，可以在标题后面加上`{-}`结尾。下一个标题编号接上一个编号，比如：

`1 标题1`
`标题2`
`2 标题3`

**Comment by 88250** [comment]
感谢建议，但暂时不考虑引入。
