### ISSUE TITLE
允许调用思源内置icon作为文档和行内icon

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12510]
### In what scenarios do you need this feature?

希望可以在文档和行内直接使用思源内置的icon，甚至是多个图标包，emoji有时候不是特别合适。内置图标包相比emoji会更加统一并且整洁

### Describe the optimal solution

下面是notion的图标包，可以选择并染色。

![image](https://github.com/user-attachments/assets/715a08db-f450-4b8c-bb6e-7277dad4a6bd)

capacities也支持，但很可惜我现在不是会员了

![image](https://github.com/user-attachments/assets/a77c7ae2-256e-4b60-a989-fc001d6620ad)

**Comment by 88250** [comment]
感谢提议，不考虑了，也许可以等社区制作图标集市包。

**Comment by KuiyueRO** [comment]
d大的意思是将内置图标做成单独的svg文件放到emoji路径下么

**Comment by 88250** [comment]
嗯，做成集市包可以上架。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月19日(周四) 晚上7:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 允许调用思源内置icon作为文档和行内icon (Issue #12510)




 
d大的意思是将内置图标做成单独的svg文件放到emoji路径下么

**Comment by KuiyueRO** [comment]
好的

**Comment by TCOTC** [comment]
> > 做成集市包可以上架
> 
> 话说这个怎么实现？通过插件将图标文件复制到 emoji 文件夹里？

还真有这个思路的插件 https://github.com/L1cardo/siyuan-plugin-material-icon

![Image](https://github.com/user-attachments/assets/77a8cf21-4621-485c-b051-abf5e99d5079)

**Comment by KuiyueRO** [comment]
> 还真有这个思路的插件 https://github.com/L1cardo/siyuan-plugin-material-icon
> 
> ![Image](https://github.com/user-attachments/assets/77a8cf21-4621-485c-b051-abf5e99d5079)

是的，本来这个PR是支持多图标包的和多种icon颜色的，但考虑到思源的图标包不会同步，另外担忧有颜色可能引发别的问题，所以现在的方案就是使用思源设置中选用的图标包。切换到其他图标包时因为图标名称是一样的，所以图标也会自动切换，保证视觉的一致性
