### ISSUE TITLE
改进拖动块到两个块之间的情况

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12517]
比如把 3 拖动到 1 和 2 之间，就同时高亮 1 和 2 这两个块，而不是只能高亮其一：

![image](https://github.com/user-attachments/assets/0c31ad4e-7d23-447d-b89d-98799ff4c9bd)

比如把 4 拖动到 2 和 3 之间，就同时高亮 2 和 3 这两个块：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/74f1ff44-bf3b-49f3-bc6a-347f002c6ec6)

**Comment by 88250** [comment]
@Vanessa219 是不是不用区分某个块的上或者另一个块的下？因为这两种情况对于用户来说是一样的：

![image](https://github.com/user-attachments/assets/a1d57343-1259-48fe-bdc4-67370b4c4ee3)

![image](https://github.com/user-attachments/assets/a7878b7a-9dbc-4771-82cd-df59e197fbe8)

**Comment by Vanessa219** [comment]
要不就只高亮列表内部吧。段落块这样的话太晃眼了，有点花了。notion 也就有列表

**Comment by TCOTC** [comment]
> 太晃眼了，有点花了

我觉得可以像 Notion 那样淡入淡出

**Comment by Vanessa219** [comment]
要不就超级块和列表弄一下？淡入淡出会有残影，有的用户说卡才移除的。

**Comment by TCOTC** [comment]
> 就超级块和列表弄一下

也行。

> 淡入淡出会有残影，有的用户说卡才移除的。

其实我觉得拖动时的频繁闪烁更影响用户体验，所以我觉得有一点点淡出的话能缓解一下

**Comment by Vanessa219** [comment]
效果先不加了，就弄简化一下块吧。

**Comment by TCOTC** [comment]
> 不用区分某个块的上或者另一个块的下

还有这个情况也是，会导致那条线反复闪烁：

- #10730
