### ISSUE TITLE
Is the OCR image option hidden intentionally on browser by default?

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

On local:
![image](https://github.com/user-attachments/assets/17f8024b-6182-4bbf-bd95-ee6870744234)

On browser:
![image](https://github.com/user-attachments/assets/a6420110-9410-45f5-aaa0-0b463098b7a0)

### Expected result

Show OCR option in the browser... because if I paste image on  the browser... It is still be OCR-ed as expected.

### Version environment

```markdown
- Version: 
- Operating System: Window
- Browser (if used): Edge browser
```

### Log file

....

**Comment by 88250** [comment]
The next version will display the settings menu on the browser side, thank you.

**Comment by 88250** [comment]
这个改动就不拉进版本了。
This change will not be included in the version.
