### ISSUE TITLE
图片文件名过长/路径过长时，导出的 HTML 无法显示图片

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12521]
https://ld246.com/article/1725848538170 ：在自己的设备上正常显示图片，在别人的设备上文件路径变长了于是显示不了图片

导出为 HTML(SiYuan) 后，在我自己的设备上也显示不了图片：

[EXCEL操作.sy.zip](https://github.com/user-attachments/files/17052002/EXCEL.sy.zip)
[EXCEL操作de54112284f17e05287c2c8fa4d90c7d37a700d1e5de28b3cc5bdc5f7ab15ca6ad1ec177c308ebd5304cab29adb.zip](https://github.com/user-attachments/files/17052003/EXCEL.de54112284f17e05287c2c8fa4d90c7d37a700d1e5de28b3cc5bdc5f7ab15ca6ad1ec177c308ebd5304cab29adb.zip)

![image](https://github.com/user-attachments/assets/9c04f431-5668-4c50-b687-eca2e169b0d8)

**Comment by 88250** [comment]
尝试了下，这个还是不动了，因为如果缩短文件名的话可能会丢失信息（插入文件的时候已经缩短过文件名了）。

另外，这个问题最主要的是和存放解压缩文件的路径有关系，可以手动将解压路径放在某个分区根目录上，并将文件夹名称改短应该就能打开了，比如 D:\\1\index.html
