### ISSUE TITLE
手机伺服链接问题

### ISSUE THREAD

**Issue by lbgws2** [siyuan-note/siyuan#12529]
## 基础情况

我使用手机思源作为伺服器,电脑端通过网页访问,这样好处是数据不需要进行同步,电脑端也可以随时访问编辑,这个是我从OB转到思源的一个重要特性

## 问题

手机端开启伺服后,会有一个IP访问地址,能否为block节点增加一个直链地址 形式如 http://192.168.x.x/block/{blockID}

这样我可以将这个链接收藏,从外部直接访问到对应的block

PS:如果能为pdf批注也增加对应的链接就更好了,
我可以将pdf文件直接存入思源,从外部直接访问到pdf指定页码,相当于一个移动书库了

**Comment by 88250** [comment]
`http://127.0.0.1:6806/?id={blockID}`
