### ISSUE TITLE
移动安卓端在**手动同步**模式下切换到多任务管理时不需要同步数据

### ISSUE THREAD

**Issue by Tlonglan** [siyuan-note/siyuan#12523]
### In what scenarios do you need this feature?

在手动同步的模式下，切换到 **后台多任务管理** 就会触发数据同步
在实际使用中，只是暂时切换一下，马上就回来（特别是将应用固定在后台的情景），并没有要退出应用，不需要这样频繁地同步数据

https://github.com/user-attachments/assets/402c9fb2-a7cd-4862-9af1-3505bfd063ee

__

### Describe the optimal solution

取消从任务后台回来就触发数据同步的行为

**Comment by TCOTC** [comment]
> 切换到 后台多任务管理 就会触发数据同步

听起来挺合理的，能保证数据同步。不过如果用户一切到后台就划掉了思源会咋样？

**Comment by 88250** [comment]
这个是设计如此，Android 端切换前后台算作手动点击同步（即使在 手动同步 模式下），这是为了尽量保证数据同步，除非在 完全手动 同步模式下，切换前后台才不会触发同步。
