### ISSUE TITLE
RF: hide horirontal scroll-bar for better visual ux 

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12520]
### In what scenarios do you need this feature?

If I copy long text to code element... 

In github
```
Have you tried anytype? It stores everything device-locally, and only syncs the diff - if you use that for a a few minutes, especially the iOS app you'll understand what I mean, it's lightning-fast.

Notion on the other hand runs everything to the cloud and their 'apps' are just glorified react interfaces to the web version. Slow and clunky.

I probably have over 10,000 notes over a period of about 10-15 years (a large chunk imported from evernote previously) with various metadata like tags, due dates etc. This means 2-8 second load times when searching and opening notes - doesn't sound like alot, but when you're using it several hundred times a day, or trying to jot down a quick thought it gets frustrating.
```

In Siyuan
![image](https://github.com/user-attachments/assets/2d3a26b7-38e3-4114-abd8-f4ccd8ef176d)

In Notion
![image](https://github.com/user-attachments/assets/0ff653e7-36ff-4121-a854-dc16d133b0d6)

### Describe the optimal solution

Just hide it for clean visual UI... Especially if multi code element in the same page

**Comment by TCOTC** [comment]
My Notion: A giant scroll bar

![image](https://github.com/user-attachments/assets/13bad607-ed94-4ecd-a01f-3e20cf5a6a08)

**Comment by 88250** [comment]
Hi, we don't plan to change this, thanks for your feedback.
