### ISSUE TITLE
Some PDF assets are not content searchable

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12536]
在资源文件搜索中搜索不到内容的 pdf

https://ld246.com/article/1726822234843

pdf: [测试pdf.zip](https://github.com/user-attachments/files/17075116/pdf.zip)

我将 pdf 插入文档，也是搜索不到

**Comment by 88250** [comment]
可能是上游库的问题，已经提交 issue https://github.com/tetratelabs/wazero/issues/2317

这里先关闭，如果那边有动静再跟进。

**Comment by 88250** [comment]
已经确认是思源这边依赖库版本不匹配引起的问题，下个版本会解决，谢谢。
