### ISSUE TITLE
如果引用的块在当前文档，无法 `在新页签中打开`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12537]
有时候会需要 `在新页签中打开` 之后拖动页签分屏查看，所以需要支持。

[视频.webm](https://github.com/user-attachments/assets/dd1cdc37-0806-4adb-842d-64f9206a7005)

**Comment by Vanessa219** [comment]
和 https://github.com/siyuan-note/siyuan/issues/11980 是同一个问题。

**Comment by Vanessa219** [comment]
修改一下文案吧，`使用页签打开`。
如果页签已经打开的话就定位一下，这样即使不在同一个页面，如果页签过多的话，可以直接定位，不需要再次打开。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
