### ISSUE TITLE
Repeated shutting down of Siyuan

### ISSUE THREAD

**Issue by indespicableme** [siyuan-note/siyuan#12545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I use the Siyuan app almost daily in my iMac, almost daily. For the last month, the app is repeatedly and unexpectedly closing with a 'data corruption' warning. 

I am using the latest version of Siyuan and running macOS Sequoia. My Siyuan folder is located in an external HDD. And I am not aware of anything process scanning the drive. I have even stopped spotlight from scanning the drive.

it has happened before, but now the app is closing almost at 5 minutes interval.

below is the screenshot of the warning -

![image](https://github.com/user-attachments/assets/fdb2770e-be66-4e9f-9cc6-6b394f7513ce)

It will be of great help, if other members please help me regarding this issue, as I have a huge collection of medical notes in Siyuan. And, at this moment I can not access any of them.

Thanks.

### Expected result

It will be of great help, if other members please help me regarding the above issue, as I have a huge collection of medical notes in Siyuan. And, at this moment I can not access any of them.

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/242cc3bb-8c0a-4ad0-aa08-1d5f7731a583)

### Version environment

```markdown
- Version: 3.16
- Operating System: macOS Sequoia.
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17085751/siyuan.log)

**Comment by 88250** [comment]
Hello, from the kernel log, please delete these files manually and restart to see:

```
E 2024/09/22 02:41:30 tree.go:163: parse json to tree [/Volumes/Expansion/siyuan volume/data/20231102232332-mcbu0hm/._20240506200906-8ktgdpq.sy] failed: invalid character '
```

There may be some similar places, please search for `parse json to tree` in the log and manually delete these damaged files.

In addition, if the folder `/Volumes/Expansion/siyuan volume/data/.siyuan/filesys_status_check/` exists, delete it.

After deleting it, restart Siyuan and see.

The generation of these `._xxx` files is not normal. It is recommended to use other tools to check whether there is a problem with the file system of this disk.

**Comment by indespicableme** [comment]
Thanks for your help.

As suggested, I did delete all the files, and the file_status_check folder. 

The Siyuan app, started normally and was working normally for a bit longer time, than before, but then again it unexpectedly shuts down.

The file_status_check folder is again being regenerated.

Below is the log -

I 2024/09/22 08:39:19 runtime.go:79: kernel is booting:
    * ver [3.1.6]
    * arch [arm64]
    * os [darwin]
    * pid [25796]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Volumes/Expansion/siyuan-repository]
I 2024/09/22 08:39:19 conf.go:126: loaded conf [/Volumes/Expansion/siyuan-repository/conf/conf.json]
I 2024/09/22 08:39:19 runtime.go:128: use network proxy [system]
I 2024/09/22 08:39:19 serve.go:139: kernel [pid=25796] http server [127.0.0.1:56856] is booting
I 2024/09/22 08:39:20 fixedport.go:35: fixed port service [127.0.0.1:6806] is running
I 2024/09/22 08:39:21 pandoc.go:146: built-in pandoc [ver=3.1.1, bin=/Volumes/Expansion/siyuan-repository/temp/pandoc/bin/pandoc]
I 2024/09/22 08:39:21 conf.go:1097: pandoc initialized, set pandoc bin to [/Volumes/Expansion/siyuan-repository/temp/pandoc/bin/pandoc]
I 2024/09/22 08:39:21 conf.go:835: database size [218.76 MB], tree/block count [354/30837]
I 2024/09/22 08:39:21 working.go:193: kernel booted
I 2024/09/22 08:39:22 box.go:77: auto stat [trees=354, blocks=30837, dataSize=8.06 GB, assetsSize=8.04 GB]
I 2024/09/22 08:39:22 disk.go:33: disk usage [total=4.01 TB, used=242.35 GB, free=3.76 TB]
E 2024/09/22 08:49:25 runtime.go:161: check file system status failed: dir [/Volumes/Expansion/siyuan-repository/data/.siyuan/filesys_status_check] has more than 1 file:
  ._check_consistency
  check_consistency
, github.com/siyuan-note/siyuan/kernel/util.checkFileSysStatus()
	/Users/Vanessa/Work/Code/siyuan/kernel/util/runtime.go:267 +0x788
github.com/siyuan-note/siyuan/kernel/util.CheckFileSysStatus()
	/Users/Vanessa/Work/Code/siyuan/kernel/util/runtime.go:174 +0x70
created by main.main in goroutine 1
	/Users/Vanessa/Work/Code/siyuan/kernel/main.go:53 +0xb4


Thanks.

**Comment by 88250** [comment]
There is likely a problem with the disk partition. It is recommended to test another partition.

**Comment by indespicableme** [comment]
okay Sir, thanks a lot

**Comment by cnwang0525** [comment]
> There is likely a problem with the disk partition. It is recommended to test another partition.

您好，我遇到了和作者一样的问题，mac os，最新版软件，工作空间在 exfat 的外置 ssd 移动硬盘上，报错内容也一直，请教是否移动硬盘都会有类似的问题？

**Comment by 88250** [comment]
@cnwang0525 可能只有 macOS 上的移动硬盘有这个问题，其他系统上我们没有收到过类似反馈

**Comment by cnwang0525** [comment]
> [@cnwang0525](https://github.com/cnwang0525) 可能只有 macOS 上的移动硬盘有这个问题，其他系统上我们没有收到过类似反馈

感谢，目前是否原因未知 & 没有解决办法？

**Comment by 88250** [comment]
不知道原因，只能换下分区/硬盘试试

**Comment by cnwang0525** [comment]
> 不知道原因，只能换下分区/硬盘试试

好的，感谢回复

**Comment by cnwang0525** [comment]
> 不知道原因，只能换下分区/硬盘试试

UPDATE：移动硬盘分区从 exFat 重新改为 APFS 格式后目前运行稳定，但具体原因不明，mac 和 win 系统移动硬盘互通使用应该是小众需求，可能也很难在后续版本中得到彻底解决了
