### ISSUE TITLE
Improve cloud data synchronization stability

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#12543]
https://ld246.com/article/1726705701342

将并行迁出文件改为串行，虽然会慢一点，但是可以控制迁出顺序；改进迁出顺序：

1. 配置文件
2. assets
3. emojis
4. storage
5. widgets
7. templates
8. public
9. 笔记本数据，笔记本数据按路径长短排序，短路径排前面

**Comment by frostime** [comment]
这个对同步的性能影响会比较大吧？

**Comment by zxhd863943427** [comment]
似乎现在已经是串行的？只是没有排序？

**Comment by 88250** [comment]
等机制稳定以后再优化，应该可以在细节上进行并行迁出，比如除了笔记本数据的其他路径应该都可以。

**Comment by 5kyfkr** [comment]
> 等机制稳定以后再优化，应该可以在细节上进行并行迁出，比如除了笔记本数据的其他路径应该都可以。

我现在同步唯一会遇到没同步过来的就是CSS片段，有两台电脑和一台手机，经常公司那台电脑CSS片段没同步过去，要不就是家里的没同步过来，仅出现在css片段新增或改动较多的时候，其他文档那些没遇到同步遗漏，建议配置文件不并行。

**Comment by 88250** [comment]
CSS 代码片段不是配置文件，可以再观察看看



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 22, 2024 20:26 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve cloud data synchronization stability(Issue #12543)




  
等机制稳定以后再优化，应该可以在细节上进行并行迁出，比如除了笔记本数据的其他路径应该都可以。
  
我现在同步唯一会遇到没同步过来的就是CSS片段，有两台电脑和一台手机，经常公司那台电脑CSS片段没同步过去，要不就是家里的没同步过来，仅出现在css片段新增或改动较多的时候，其他文档那些没遇到同步遗漏，建议配置文件不并行。
