### ISSUE TITLE
数据库日期筛选的问题

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

筛选当前周和前一周没有问题，前2周就有问题了

![image](https://github.com/user-attachments/assets/9ca7cad0-2c0a-4059-b75e-3c8025248456)

![image](https://github.com/user-attachments/assets/0146f154-dd3b-44ee-aff6-630870b8c380)

![image](https://github.com/user-attachments/assets/9d50b977-8d5b-4681-95a9-030e8f028c9a)

### Expected result

。。

### Version environment

```markdown
- Version: 最新
- Operating System: win11
- Browser (if used):
```

### Log file

。。

**Comment by 88250** [comment]
你好，我没有看出问题，请具体描述一下。

**Comment by Jiangshuon** [comment]
9月2号不是前两周的吧

**Comment by 88250** [comment]
9月2号是前两周的周一：

![image](https://github.com/user-attachments/assets/40869100-aaf3-45e6-ac1e-33aaa9b027c3)

**Comment by Jiangshuon** [comment]
哦哦，前两周是这个意思。

那我想筛选出上上周（7天）的数据，怎么填呢

我用"介于”好像不行

![image](https://github.com/user-attachments/assets/f2e04af9-cba3-4379-bc24-9e11d0d59eec)

**Comment by 88250** [comment]
创建时间、更新时间 字段的 介于 计算确实有问题，稍后修复。

请等发布下一个 dev 版时帮忙测试看看，谢谢。

**Comment by 88250** [comment]
感谢反馈，又调整了一下。

![image](https://github.com/user-attachments/assets/3c56c82c-e86f-4210-9e6a-49eb96fc19d9)

![image](https://github.com/user-attachments/assets/35fa1315-7771-4297-80f3-ca10e48eb493)
