### ISSUE TITLE
对属性面板备注占位符样式的疑问

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12544]
为什么下面这个占位符会看起来更黑：

![image](https://github.com/user-attachments/assets/86a22684-763e-4b1b-b4b0-9401e9be9f46)

换个主题看更明显：

![image](https://github.com/user-attachments/assets/ef2e9031-aaa3-4a73-af02-404c0ebfadde)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
