### ISSUE TITLE
块引右键菜单添加「删除块引及定义块」

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12558]
### In what scenarios do you need this feature?

主要场景

- 使用块引构建文档moc，某篇笔记已经无用，删除块引前还需要删除文档
- 使用块引充当脚注功能，之后想要删除块引脚注，删除块引前，还需要删除删除块引指向的块
因此希望块引右键菜单能添加「删除块引及定义块」，一键删除块引和及其定义块

### Describe the optimal solution

块引右键菜单能添加「删除块引及定义块」，一键删除块引和及其定义块，考虑到存在误删的可能性，点击按钮后，应该添加一个确认按钮，或者撤回支持恢复块引及其定义块
原来的「删除」功能文案改为「删除块引」
![PixPin_2024-09-23_11-33-48](https://github.com/user-attachments/assets/f407fe1d-d78d-45e9-a0ab-8b6c46a9be71)

**Comment by TCOTC** [comment]
所有文档中的相同块引都一并删除吗？

**Comment by Achuan-2** [comment]
> 所有文档中的相同块引都一并删除吗？

不需要，只需要删除当前选中的块引及其定义块

**Comment by TCOTC** [comment]
如果做这个功能的话，要考虑删除的块是叶子块的情况。比如删除列表项块内的段落块，要同时删除列表项块。

**Comment by Achuan-2** [comment]
> 如果做这个功能的话，要考虑删除的块是叶子块的情况。比如删除列表项块内的段落块，要同时删除列表项块。

只需要考虑删除块引指向的定义块即可，列表项块可以有多个段落块的

**Comment by TCOTC** [comment]
> 能用就行

不考虑边界情况的话，到时候直接给你运行时错误

**Comment by Achuan-2** [comment]
> > 能用就行
> 
> 不考虑边界情况的话，到时候直接给你运行时错误

只需要判断块id类型，然后调用删除文档/api/filetree/removeDoc和删除块/api/block/deleteBlock的API即可
边界情况是API考虑的事情

**Comment by TCOTC** [comment]
我的意思就是要考虑这个（p.s.我没看删除块的API是怎么实现的）

**Comment by 88250** [comment]
这个最好还是人为处理。
