### ISSUE TITLE
Iframe内容缓存

### ISSUE THREAD

**Issue by ONIONLYONE** [siyuan-note/siyuan#12550]
### In what scenarios do you need this feature?

iframe块中的内容似乎每次打开都需要重新加载，但有时候这些内容是不变的，因此能否将内容缓存下来，内容变化时手动更新

### Describe the optimal solution

用户选择重新加载或缓存内容

**Comment by 88250** [comment]
这个做不到哦。

**Comment by webceoboy** [comment]
+1 需要这个功能，里面的js设置了cache header，但无法缓存
