### ISSUE TITLE
Clicking the document tag in the graph reports an error

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12556]
头图上面的标签，在关系图中点击，报错未找到id为[xxx]的内容块

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

关于关系图有2个bug

1. 头图上面的标签，在关系图中(包括全局关系图和局部关系图)点击，报错未找到id为[xxx]的内容块，但在文档中用#xxx#添加的标签没问题
    ![image](https://github.com/user-attachments/assets/b1fbdae1-452c-487a-ae54-01e7142b4208)
3. 在局部关系图中，#xxx#添加的标签是无连线的，而在全局关系图中是有连线的，二者显示不一致
    全局关系图
    <img width="583" alt="image" src="https://github.com/user-attachments/assets/7d4ac3f9-0397-4a95-a6ef-0ee4dcb77788">
    局部关系图
    ![image](https://github.com/user-attachments/assets/11e5c9b4-2abf-40a4-9424-d6d53826ed05)

### Expected result

1. 头图上面添加的标签在关系图中能正常点击。
2. 局部关系图中#xxx#添加的标签也有连线，和全局关系图保持一致。

### Version environment

```markdown
- Version: 3.1.6
- Operating System: MacOS 14.6.1
- Browser (if used): 无
```

### Log file

无

**Comment by wish5115** [comment]
> 你看下是不是把 段落 关掉了？

确实没开启段落，段落开启后是这样的

<img width="674" alt="image" src="https://github.com/user-attachments/assets/77bc77c8-1c72-4676-9818-dbbdfb9dc429">

但全局关系图也没开启段落，却有连线。二者还是不一致。不知道这个段落起到了什么作用，是否是bug？

**Comment by 88250** [comment]
这个不是 bug，局部关系图是连接到子块上，所以不开段落块的话就不会有连接，而全局关系图设计上就是连接到文档上的 https://github.com/siyuan-note/siyuan/issues/5218

**Comment by wish5115** [comment]
> 这个不是 bug，局部关系图是连接到子块上，所以不开段落块的话就不会有连接，而全局关系图设计上就是连接到文档上的 #5218

OK，感谢！
