### ISSUE TITLE
设置 - 导出 - 导出 Data 功能导致程序退出

### ISSUE THREAD

**Issue by zhimiaoli** [siyuan-note/siyuan#12568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

因为我经常备份Data作为额外一份备份，但是最近版本当运行导出时候，程序显示，🚒 已成功避免潜在的数据损坏 错误，强制退出。

实际上并没有运行任何这类同步工具，已经购买同步功能，使用Cloudfare R2进行同步，能不能不要如此激进直接退出，给个提示不行吗。

### Expected result

正常导出

### Screenshot or screen recording presentation

![PixPin_2024-09-24_08-34-08](https://github.com/user-attachments/assets/cba09713-00b4-4087-b65a-e6a50c9fc69f)

### Version environment

```markdown
- Version: 3.1.6
- Operating System: Windows 10
- Browser (if used):
```

### Log file

老问题了。

**Comment by 88250** [comment]
是否使用了其他会扫描文件路径的第三方程序？或者插件等？

**Comment by zhimiaoli** [comment]
> 是否使用了其他会扫描文件路径的第三方程序？或者插件等？

没有使用同步工具，系统有杀毒软件，但是多次尝试导出都报错，应该不是杀毒软件的问题。

**Comment by 88250** [comment]
上传一下日志文件吧

**Comment by zhimiaoli** [comment]
> 上传一下日志文件吧

看日志找到原因了，因为其中一个附件Excel正在被Excel打开了，Excel文件被Excel锁定了。

```
F 2024/09/24 08:30:29 filelock.go:87: copy [src=D:\Users\lizm275\SiYuan\data, dest=D:\Users\lizm275\SiYuan\temp\export\SiYuan-20240924083028] failed: open D:\SiYuan\data\assets\~$整理代码-20240722150738-d96d42y.xlsx: The process cannot access the file because it is being used by another process.
    github.com/siyuan-note/siyuan/kernel/model.exportData({0xc001784300, 0x39})
    	D:/88250/siyuan/kernel/model/export.go:464 +0x167
    github.com/siyuan-note/siyuan/kernel/model.ExportData()
    	D:/88250/siyuan/kernel/model/export.go:446 +0x265
    github.com/siyuan-note/siyuan/kernel/model.ExportDataInFolder({0xc00192a440, 0x1a})
    	D:/88250/siyuan/kernel/model/export.go:416 +0x1aa
    github.com/siyuan-note/siyuan/kernel/api.exportDataInFolder(0xc001abe000)
    	D:/88250/siyuan/kernel/api/export.go:241 +0xcf
I 2024/09/24 08:30:43 working.go:147:
```

**Comment by 88250** [comment]
那就是这个原因了哦。

**Comment by TCOTC** [comment]
@88250 导出是不是应该忽略 `~$` 临时文件？

**Comment by 88250** [comment]
导出 Data 不能忽略隐藏文件，否则数据可能丢失



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月24日(周二) 上午10:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 设置 - 导出 - 导出 Data 功能导致程序退出 (Issue #12568)




 
@88250 导出是不是应该忽略 ~$ 临时文件？

**Comment by zhimiaoli** [comment]
但是这个提示和直接退出的主程序的操作真的不是很友好；能否直接提示用户，让用户决定是否继续。

**Comment by TCOTC** [comment]
我觉得可以弹窗提示让用户关闭其他程序，然后让用户再次尝试导出

**Comment by 88250** [comment]
不好判断的，你有方案不？



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月24日(周二) 中午11:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 设置 - 导出 - 导出 Data 功能导致程序退出 (Issue #12568)




 
我觉得可以弹窗提示让用户关闭其他程序，然后让用户再次尝试导出

**Comment by TCOTC** [comment]
> 弹窗提示让用户关闭其他程序

比如在导出过程中，文件名以 `~$` 开头的文件无法访问时？

**Comment by 88250** [comment]
不能保证这样的文件就无法复制啊



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月24日(周二) 中午12:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 设置 - 导出 - 导出 Data 功能导致程序退出 (Issue #12568)




  
弹窗提示让用户关闭其他程序
  
比如在导出过程中，文件名以 ~$ 开头的文件无法访问时？

**Comment by TCOTC** [comment]
我看都报错了，至少可以处理一下这种情况：`F 2024/09/24 08:30:29 filelock.go:87: copy [src=D:\SiYuan\data, dest=D:\\SiYuan\temp\export\SiYuan-20240924083028] failed: open D:\SiYuan\data\assets\~$整理代码-20240722150738-d96d42y.xlsx: The process cannot access the file because it is being used by another process.`

**Comment by 88250** [comment]
要导出的时候才能知道是否正常，无法提前判断的



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月24日(周二) 中午1:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 设置 - 导出 - 导出 Data 功能导致程序退出 (Issue #12568)




 
我看都报错了，至少可以处理一下这种情况：F 2024/09/24 08:30:29 filelock.go:87: copy [src=D:\SiYuan\data, dest=D:\\SiYuan\temp\export\SiYuan-20240924083028] failed: open D:\SiYuan\data\assets\~$整理代码-20240722150738-d96d42y.xlsx: The process cannot access the file because it is being used by another process.
