### ISSUE TITLE
没有后缀名的网络图片使用“网络图片转换为本地图片”功能后图片链接没有替换为本地连接

### ISSUE THREAD

**Issue by AZmake** [siyuan-note/siyuan#12561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

没有后缀名的网络图片使用“网络图片转换为本地图片”功能后图片链接没有替换为本地连接

### Expected result

没有后缀名的网络图片使用“网络图片转换为本地图片”功能后图片链接替换为本地连接

### Screenshot or screen recording presentation

1、新建文档
2、浏览器打开链接 https://www.jianshu.com/p/b169d1897129 复制黏贴到新建文档
3、选择"网络图片转换为本地图片"
4、显示文件下载完毕，asset里面能找到图片
5、文档里面的图片链接没有替换为本地连接

### Version environment

```markdown
- Version: 3.1.6
- Operating System: mac
- Browser (if used):
```

### Log file

I 2024/09/23 17:19:00 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/09/23 17:19:00 runtime.go:79: kernel is booting:
    * ver [3.1.6]
    * arch [arm64]
    * os [darwin]
    * pid [18874]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/lyc/Desktop/notepad/siyuan]
I 2024/09/23 17:19:00 conf.go:144: initialized the specified language [zh_CN]
I 2024/09/23 17:19:00 runtime.go:128: use network proxy [system]
I 2024/09/23 17:19:00 serve.go:139: kernel [pid=18874] http server [127.0.0.1:53314] is booting
I 2024/09/23 17:19:00 blocktree.go:75: reinitialized database [/Users/lyc/Desktop/notepad/siyuan/temp/blocktree.db]
I 2024/09/23 17:19:00 database.go:92: the database structure is changed, rebuilding database...
I 2024/09/23 17:19:00 database.go:109: reinitialized database [/Users/lyc/Desktop/notepad/siyuan/temp/siyuan.db]
I 2024/09/23 17:19:00 conf.go:835: database size [4.1 kB], tree/block count [0/0]
I 2024/09/23 17:19:00 working.go:193: kernel booted
I 2024/09/23 17:19:01 box.go:77: auto stat [trees=0, blocks=0, dataSize=36.87 kB, assetsSize=0 B]
I 2024/09/23 17:19:01 disk.go:33: disk usage [total=245.11 GB, used=200.31 GB, free=44.8 GB]
I 2024/09/23 17:19:01 index.go:220: rebuilt database for notebook [20210808180117-czj9bvb] in [0.03s], tree [count=70, size=1.39 MB]
I 2024/09/23 17:19:01 index.go:290: resolved refs [36] in [19ms]
I 2024/09/23 17:19:01 fixedport.go:35: fixed port service [127.0.0.1:6806] is running
I 2024/09/23 17:19:06 pandoc.go:176: initialized built-in pandoc [ver=3.1.1, bin=/Users/lyc/Desktop/notepad/siyuan/temp/pandoc/bin/pandoc]
I 2024/09/23 17:19:06 conf.go:1097: pandoc initialized, set pandoc bin to [/Users/lyc/Desktop/notepad/siyuan/temp/pandoc/bin/pandoc]
I 2024/09/23 17:19:29 blocktree.go:75: reinitialized database [/Users/lyc/Desktop/notepad/siyuan/temp/blocktree.db]
I 2024/09/23 17:19:29 database.go:109: reinitialized database [/Users/lyc/Desktop/notepad/siyuan/temp/siyuan.db]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240503141125-cebef36] in [0.02s], tree [count=1, size=1.46 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240829171652-ucamsqx] in [0.01s], tree [count=1, size=917 B]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240819100807-bx36rmt] in [0.02s], tree [count=4, size=290.1 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240726151546-knpkfzq] in [0.01s], tree [count=4, size=173.29 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240513165804-jr2jd74] in [0.00s], tree [count=1, size=67.01 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240513111331-bwrovo0] in [0.01s], tree [count=4, size=55.18 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240419112210-m18cg60] in [0.01s], tree [count=6, size=344.3 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20210808180117-czj9bvb] in [0.03s], tree [count=70, size=1.39 MB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240227101755-8yawoy2] in [0.02s], tree [count=39, size=1.1 MB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240105132935-clyemh8] in [0.17s], tree [count=273, size=10.32 MB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240105140433-xds6oiq] in [0.01s], tree [count=12, size=284.92 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240117093118-ey7fxnm] in [0.01s], tree [count=11, size=375.35 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240105143419-omjktul] in [0.01s], tree [count=16, size=224.1 kB]
I 2024/09/23 17:19:29 index.go:220: rebuilt database for notebook [20240223102100-683eid7] in [0.01s], tree [count=11, size=39.88 kB]
I 2024/09/23 17:19:29 index.go:290: resolved refs [36] in [67ms]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.00s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.01s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.01s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.01s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.02s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.02s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.03s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.03s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.03s]
I 2024/09/23 17:19:32 asset.go:100: loaded assets [2.04s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.04s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.04s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.05s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.05s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.05s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.06s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.06s]
I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.07s]

后面都是 I 2024/09/23 17:19:33 asset.go:100: loaded assets [2.07s]

**Comment by 88250** [comment]
@TCOTC 原网页上用的是 `//` 

![image](https://github.com/user-attachments/assets/59b15a68-6908-4986-8712-fa14176ac9c2)

我们兼容一下。

这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by TCOTC** [comment]
那怪怪的，为啥我复制粘贴到思源里就没这个问题

**Comment by 88250** [comment]
不清楚了，我这里和楼主描述的问题一样。
