### ISSUE TITLE
Mac 上的编码问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12565]
https://ld246.com/article/1727089403865

**Comment by 88250** [comment]
麻烦关闭 issue，已经在链滴上回复。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月23日(周一) 晚上7:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] Mac 上的编码问题 (Issue #12565)




 
https://ld246.com/article/1727089403865

**Comment by TCOTC** [comment]
可能是主题字体的问题
