### ISSUE TITLE
支持临时调整浮窗内的字号

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12564]
就像调整新窗口的字号不会影响主窗口

关联 https://ld246.com/article/1727088881126

**Comment by 88250** [comment]
我看贴子已经解决了



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月23日(周一) 晚上8:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 支持临时调整浮窗内的字号 (Issue #12564)




 
靠 CSS 应该实现不了吧？Ctrl+滚轮 是思源控制的

**Comment by TCOTC** [comment]
那个代码片段只能固定浮窗中的字体字号，某些元素的大小不会改变，样式奇怪。

但主要原因是我的需求是像调整新窗口的字号不会影响主窗口那样，调整单个浮窗的字号不会影响其他编辑器，用 CSS 不能满足这个需求。

**Comment by 88250** [comment]
这个不考虑了，谢谢。
