### ISSUE TITLE
Ignore assets associated with the `custom-data-assets` block attribute when cleaning unreferenced assets

### ISSUE THREAD

**Issue by suka233** [siyuan-note/siyuan#12574]
清理未引用资源时，文档块也支持忽略custom-data-assets和data-assets属性定义的资源文件

### In what scenarios do you need this feature?

开发插件的时候，有一些数据是文档相关的，和文档强绑定的，所以有这个需求，目前看源码，只有widget类型的块支持上述俩属性：
![图片](https://github.com/user-attachments/assets/01c7af32-0bb5-4ef8-a6dc-6d864ef87c09)

### Describe the optimal solution

更改应该很简单 ，全局搜索只有这俩处适配custom-data-assets和data-assets属性。可惜我不会go。
![图片](https://github.com/user-attachments/assets/546293a5-d7cb-4876-8b62-5ec8770fb364)

有一点需要注意，custom-data-assets和data-assets的设计可能要优化一下：因为过往这俩忽略属性只在widget块生效，所以一般不会有其它的插件或者挂件占用。

但是一旦文档块要加上这俩忽略属性的话，可能会有不同的插件都需要使用这个属性，这个时候，设计成忽略所有以custom-data-assets和data-assets开头的属性的资源内容更合理。
比如custom-data-assets-xxx1，custom-data-assets-xxx2都应该被正确处理。

**Comment by 88250** [comment]
`data-assets` 是个过时的属性，这里不再支持了，仅考虑 `custom-data-assets`

**Comment by 88250** [comment]
等 v3.1.8-dev1 发布后麻烦帮忙测试看看。

**Comment by TCOTC** [comment]
@88250 这个应不应该算 Development ？感觉只有插件开发者需要关心

**Comment by 88250** [comment]
稍后改一下标签，谢谢



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Wed, Sep 25, 2024 07:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Ignore assets associated with the`custom-data-assets` block attribute when cleaning unreferenced assets (Issue#12574)




 
@88250 这个应不应该算 Development ？感觉只有插件开发者需要关心

**Comment by 2234839** [comment]
非常棒的想法呀
