### ISSUE TITLE
大纲标题的悬浮提示应该显示在远离侧栏的那一边

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12575]
### 标题较短时，悬浮提示会显示在靠近侧栏的一边。需要保持一致：

[视频.webm](https://github.com/user-attachments/assets/8ca5234a-48a6-4317-92aa-f0b4e836b256)

### 如果是这种大纲页签，保持现在这样就好了：

![image](https://github.com/user-attachments/assets/80c19125-04e0-4f30-9f18-45ffb5247ab2)

**Comment by Vanessa219** [comment]
大纲的位置不固定，距离不好计算。如果右侧有个很窄的面板之类的情况。因此就不进行改进了。
