### ISSUE TITLE
为js片段增加快捷键支持

### ISSUE THREAD

**Issue by lbgws2** [siyuan-note/siyuan#12576]
思源运行JS片段是个非常强大的功能

与OB的Templater插件相比,感觉缺少快捷键功能,为自定义的脚本增设快捷键,可以方便脚本运行

也可以在浮动菜单中增加自定义脚本,并可以自定义图标

**Comment by TCOTC** [comment]
你可以写 JS 实现快捷键

**Comment by 88250** [comment]
自己应该可以注册快捷键的。
