### ISSUE TITLE
Moving doc search supports multiple keywords separated by spaces

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12577]
希望移动文档的搜索支持多关键字搜索（空格分隔）

### In what scenarios do you need this feature?

目前是完全匹配，文档多了，有点困难

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
确实

**Comment by TCOTC** [comment]
为啥用起来感觉是 OR 关系，输入多个关键词之后还更难筛选了

![image](https://github.com/user-attachments/assets/1e7121d8-7abf-4f6c-8f99-c599866871d6)

**Comment by Jiangshuon** [comment]
嗯，应该是and关系

**Comment by 88250** [comment]
稍后调整一下
