### ISSUE TITLE
功能建议：拖动文件进笔记可形成本地文件链接，而不是只能每次把文件复制成附件

### ISSUE THREAD

**Issue by Richardggm** [siyuan-note/siyuan#1258]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

我有许多文件需要管理，而一个很好的管理方式就是在md笔记里文件建链接引用到对应的文件，如下图所示，是我以链接的形式整理的一些文件（很清楚，很方便，点击即可打开。唯一的问题是制作时有点繁琐）。

![image](https://user-images.githubusercontent.com/35445448/105632892-8f745700-5e90-11eb-944e-7720d2defa8c.png)

思源笔记目前拖动文件进md，会全都以附件的形式形成链接。但是我文件比较多，而且有固定的目录，所以希望能够不生成附件，而是以电脑本地文件的形式形成链接，例如这种格式：
![image](https://user-images.githubusercontent.com/35445448/105632947-deba8780-5e90-11eb-92a4-d2941bb47ecb.png)

所以，希望能够有一个自定义设置，可以选择每次拖动文件进md，是形成本地文件链接，还是形成附件链接。

**Comment by 88250** [comment]
你好，这个地方我们之前有过考虑，请参考 https://github.com/siyuan-note/siyuan/issues/127 

还需要些时间，感谢建议。
