### ISSUE TITLE
Pinned Breadcrumb While Editing (Bulletpoint Lists)

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#12582]
### In what scenarios do you need this feature?

**Context**

I'm writing large lists of bullet points indented at different levels, e.g. if I find something new for a parent bullet I would add it blow the parent bullet point intended one level.

**Problem**

If I click on the bullet point the document breadcrumb is displayed and I know if editing a lager list what the parent bullet point was and if I'm at the correct level.

However as soon as you start writing text without using your mouse to move around the breadcrumb will be faded out. This isn't useful if you move only your cursor around leaving the mouse alone (so I'll not get the breadcrumb back if I do not click).

![Recording 2024-09-24 at 15 48 02](https://github.com/user-attachments/assets/3bc38f74-da0d-4bcd-8f6f-db7c76915627)

### Describe the optimal solution

The breadcrumb list should be pinned if you need the info for navigation even if you start typing. Maybe the pinned breadcrumb should be an preference setting.

### Describe the candidate solution

Make the pinned breadcrumb an option to stay visible even if you start typing.

**Comment by 88250** [comment]
There are two reasons for this design:

1. Unable to calculate breadcrumbs in real-time (real-time calculation of breadcrumbs is expensive)
2. Design aesthetics to make the interface more concise (refer to Notion)

The main reason is the first point, so it cannot be changed to a fixed display here. Thanks for the feedback.
