### ISSUE TITLE
新建文档和块引新建文档支持自动添加到指定数据库

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12588]
### In what scenarios do you need this feature?

![PixPin_2024-09-25_14-12-48](https://github.com/user-attachments/assets/a07c5789-5c60-4c06-873c-1950aae03719)
场景：如果用户要查询自己的所有笔记、所有块引新建的笔记，过去只能通过SQL来查询，或者在文档树里找，目前有了数据库，要是新建文档和块引新建文档都能将文档自动添加到指定的数据库，就可以利用数据库的管理功能
好处
1. 用户可以很方便回顾自己创建的所有笔记，对于dailynote笔记用户的我而言，主要通过页签和块引用新建概念笔记（卡片笔记），文档树主要建立knowledge笔记（用来管理概念笔记）
2. 新建创建日期和更新日期列，用户可以按时间倒序，查看创建笔记历史，可以直接在数据库中通过筛选条件，找到指定日期的笔记，比SQL筛选更适合小白用户
3. 新建单选和多选列，可以对所有文档进行简易的快捷分类，对一些轻文档树管理的用户而言，可以只用数据库来管理文档，以满足管理的需求

![PixPin_2024-09-25_14-22-47](https://github.com/user-attachments/assets/415c76ea-0f7b-4ece-b343-b979a66cc7e3)

### Describe the optimal solution

在笔记本设置和全局设置的新建文档和块引新建文档设置里新增「添加到指定数据库」功能
![PixPin_2024-09-25_14-20-02](https://github.com/user-attachments/assets/a41ba7b6-705c-4dcf-b44c-3fd6e97dff1f)
![PixPin_2024-09-25_14-20-12](https://github.com/user-attachments/assets/c82670a1-2c7c-4750-99b9-679f6f778e8e)

### Describe the candidate solution

文档树新建文档、页签新建文档（Ctrl+N）和块引新建文档的笔记都可以自动添加到一个指定数据库中，直接在设置里做一个单独选项
三种方式统一用一个数据库也可以，个人感觉并不是很有必要用不同的数据库做区分

**Comment by TCOTC** [comment]
我觉得可以在 Database Automations #10863 支持添加一个 `新建文档` 的触发器和一个 `块引新建文档` 的触发器、添加一个 `添加文档到数据库` 的执行操作。

**Comment by 88250** [comment]
这个考虑通过插件实现吧，如果需要新增参数请告诉我们，谢谢。
