### ISSUE TITLE
Browser clipping extension supports configuring whether to download assets

### ISSUE THREAD

**Issue by lbgws2** [siyuan-note/siyuan#12583]
思源剪藏插件图片链接功能建议

思源浏览器剪藏插件,能否增加一个转换选项,由用户选择图片链接是否存到assets,或者使用引用链接

我现有的剪藏文章5000+,担心以后剪藏更多文章时,如果都是存在本地,assets规模太大了,同时我对图片链接失效不是那么敏感

**Comment by 88250** [comment]
增加一个开关：

![image](https://github.com/user-attachments/assets/bfaffaf6-4071-4c33-8a6f-eb57bbea5c51)

需升级剪藏扩展 v1.5.0
