### ISSUE TITLE
希望增加标签页右键删除功能

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12580]
### In what scenarios do you need this feature?

有时候利用数据库创建了文件，但是删除的时候需要在文档树去翻找再右键有些麻烦

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/551c4cae-39d6-4c59-851f-ee3a89dc2095)

### Other information

![image](https://github.com/user-attachments/assets/495b9717-582e-4293-b2d9-e493414aa464) 
添加一个这样的按钮

**Comment by TCOTC** [comment]
请尝试使用文档菜单：

![image](https://github.com/user-attachments/assets/a2b79298-08a8-43c8-98dd-e3ff17ebb655)
