### ISSUE TITLE
嵌入块、引用块 Cmd + click 静默打开 失效

### ISSUE THREAD

**Issue by HoollyFox** [siyuan-note/siyuan#12585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

对嵌入块Cmd + click 不会执行静默打开，毫无反应。 

对引用块 Cmd + click 在关闭 “按住 cmd 显示浮窗” 后会 静默打开，在打开 “按住 cmd 显示浮窗”后，亦失效。 

### Expected result

修复。 

### Version environment

```markdown
- Version: 版本3.1.7 (3.1.7) 
- Operating System:  macOS 15.0 (24A335)
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17123964/siyuan.log)

**Comment by TCOTC** [comment]
> 对嵌入块Cmd + click 不会执行静默打开，毫无反应。

没有这个快捷键吧？

不过我猜 Cmd + Click 点击面包屑这里应该是可以的：

![image](https://github.com/user-attachments/assets/b73069c1-56d5-45df-a147-1cda6ac15dec)

**Comment by 88250** [comment]
> 在打开 “按住 cmd 显示浮窗”后，亦失效

我这里 Windows 上测试没有问题，可以后台打开。

**Comment by Vanessa219** [comment]
无法重现。我先关闭了。

**Comment by TCOTC** [comment]
@HoollyFox 第二点问题你可以录屏演示一下看看

**Comment by HoollyFox** [comment]
@TCOTC 我测试了一下第二点不再出现了，抱歉，可能是昨天电脑有啥问题。 

@88250 
> 嵌入块不支持该快捷键。

目前在用户手册里面这个用法还存在，可能需要删掉。

**Comment by 88250** [comment]
> 目前在用户手册里面这个用法还存在，可能需要删掉。

麻烦截图我看看位置

**Comment by HoollyFox** [comment]
<img width="816" alt="image" src="https://github.com/user-attachments/assets/2d85a1c9-1c96-4d3d-9ea8-fddea1e14a42">

如图。 Thanks a lot.

**Comment by 88250** [comment]
收到，谢谢。

我们再确认一下 @Vanessa219

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
