### ISSUE TITLE
请求修改快捷键生成逻辑（无序列表 有序列表 任务块列表）

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12589]
### In what scenarios do you need this feature?

很多时候需要修改和转换块的类型而不是再嵌套一个，在操作上有些别扭

https://github.com/user-attachments/assets/6db86b60-3c95-4c58-8bc4-86ddab88509e

### Describe the optimal solution

https://github.com/user-attachments/assets/ffc85479-7bfd-4e27-8cbb-81cbc772747d

**Comment by 88250** [comment]
需要选中 列表块 以后再操作：

[issue.webm](https://github.com/user-attachments/assets/125bd70e-8bb5-4964-a019-e313748a945f)

**Comment by TCOTC** [comment]
1. 可以用鼠标点击列表块的块标，然后使用快捷键，会方便一点；
2. 如果未来改进 #11994 ，就可以先按 Backspace 删除列表块、再按快捷键将段落转换为其他列表。

**Comment by SaXz2** [comment]
> 需要选中 列表块 以后再操作：
> 
>  issue.webm

这种方式容易出现bug,而且操作上也不是那么方便，如下图所示
![image](https://github.com/user-attachments/assets/39cc9408-183f-463d-b62f-62e2fc37f975)

**Comment by SaXz2** [comment]
> 需要选中 列表块 以后再操作：
> 
>  issue.webm

又触发了一个bug
![image](https://github.com/user-attachments/assets/ccabdcf7-9f1d-4cb4-bbd6-af2e5ce15f6c)
多个无序列表转换的时候有概率发生这种情况

**Comment by TCOTC** [comment]
请录屏复现一下操作

**Comment by SaXz2** [comment]
> 请录屏复现一下操作

就是来回切换状态的时候，发生了重叠，然后撤回的有概率会发生索引崩溃

https://github.com/user-attachments/assets/2f5bac39-4585-4184-ac4f-75a248e51dad

**Comment by TCOTC** [comment]
确实有问题 @88250 

[视频.webm](https://github.com/user-attachments/assets/2a952b33-407f-4faa-aab0-9ebfcd7131e8)

**Comment by TCOTC** [comment]
记录到 #12591
