### ISSUE TITLE
拖拽文档到数据库之后的样式问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12594]
文档树：

[视频.webm](https://github.com/user-attachments/assets/8f5131bb-913d-4dcd-96ca-fddeb6e49ada)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by TCOTC** [comment]
这个修了吗？我这里好像没这个问题了

**Comment by 88250** [comment]
估计是在 https://github.com/siyuan-note/siyuan/issues/12607 中修复了，先关闭吧。
