### ISSUE TITLE
选中文字后粘贴，被选中的文字不会替换

### ISSUE THREAD

**Issue by billypon** [siyuan-note/siyuan#12597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在别处复制一段文字，到思源中选中一段我想替换的文字，按Ctrl-v进行粘贴，此时被选中的文字还在，粘贴的文字出现在光标处

### Expected result

被选中的文字删除，替换成粘贴的文字

### Version environment

```markdown
- Version: 3.1.7
- Operating System: Windows 10
- Browser (if used):
```

### Log file

这个问题与log没有关系，就不贴了

**Comment by TCOTC** [comment]
> 在别处复制一段文字

在哪？录屏重现一下

**Comment by 88250** [comment]
选中块后粘贴是不替换的。

**Comment by TCOTC** [comment]
> 粘贴的文字出现在光标处

确实，这个症状是选中了块粘贴
