### ISSUE TITLE
搜索时 `新建文档` 选项不需要高亮文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12598]
新建文档后面这部分文本不需要高亮：

![image](https://github.com/user-attachments/assets/bef33f45-ec8b-41a6-854e-27aa21da82a0)

![image](https://github.com/user-attachments/assets/a1f00444-be58-4d57-b126-ea386a7244ab)

Notion 这样没高亮的看起来会舒服一点（但筛选结果也没有高亮的话可能不够实用）：

![image](https://github.com/user-attachments/assets/02b6baec-1483-41b8-a8ae-e95aa09bdbe7)

关联 https://ld246.com/article/1727277872375

**Comment by 88250** [comment]
这个就不改动了吧，谢谢。

**Comment by TCOTC** [comment]
这个高亮太多余了

**Comment by 88250** [comment]
还行啊，新建文档可以起到强调作用。

**Comment by TCOTC** [comment]
我觉得没有必要强调这个，用户能看见 `新建文档` 的。

看着反而是干扰：

![image](https://github.com/user-attachments/assets/6f3e2303-0e23-40d7-95d0-96c9fe956691)

**Comment by 88250** [comment]
我觉得挺好的，暂时不动了。
