### ISSUE TITLE
在列表内创建分隔线后，应该在分隔线后创建一个块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12593]
如果列表的后面有空的块，光标就会直接跑到列表后面了；列表后没有块的时候才正常：

[视频.webm](https://github.com/user-attachments/assets/473c3f15-b03c-4d63-9106-ec7b48dcb980)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
