### ISSUE TITLE
转移引用之后控制台有报错

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12606]
[视频.webm](https://github.com/user-attachments/assets/b665ee80-a423-43fa-83d5-736f5f997629)

录屏里录到了一帧：

![](https://github.com/user-attachments/assets/4aaf20ce-d895-4b42-9731-3605976c1e69)

**Comment by 88250** [comment]
我这里细化日志看了下：

![image](https://github.com/user-attachments/assets/d78b02f8-fabf-4eaa-a9fe-4082fc7d57c7)

@Vanessa219 评估一下是否紧要。

**Comment by 88250** [comment]
刷新界面的时候可能刚好有其他请求被打断了。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
