### ISSUE TITLE
文档树鼠标操作优化

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12603]
### In what scenarios do you need this feature?

通过shift+左键点击起点和终点笔记，按照当前排序模式直接批量选择途径的所有笔记。

### Describe the optimal solution

目前edge等多个应用是通过shift+鼠标左键进行快速批量选择的，而思源只能通过键盘快速选择（并且相关内容在用户指南中藏的很隐蔽），或是ctrl+鼠标左键多次加选

**Comment by Achuan-2** [comment]
+1

**Comment by TCOTC** [comment]
这样的话就需要支持为下列功能指定快捷键（限定为在 `Ctrl+点击` `Alt+点击` `​Shift+点击​` `​Ctrl+Alt+点击/鼠标中键` ​中选择其一）：

名称 | 操作 | 备注
-- | -- | --
多选 | ​Ctrl+点击​ / ⌘点击​ |  
在右侧打开 | ​Alt+点击​ / ⌥点击​ |  
在下侧打开 | ​Shift+点击​ / ⇧点击​ |  
在新页签中打开 | ​Ctrl+Alt+点击​ / ⌥⌘点击​ / 鼠标中键 | 需设置为在当前页签中打开

并且新增一个 `快速扩选` 的功能

**Comment by KuiyueRO** [comment]
如果可以，我比较希望是shift+点击，这个快捷键目前看来比较通用，没那么反直觉

**Comment by KuiyueRO** [comment]
另外还有一个关联需求，右键菜单新增一个合并到xx文档的选项，支持单选和多选

**Comment by TCOTC** [comment]
> 另外还有一个关联需求，右键菜单新增一个合并到xx文档的选项，支持单选和多选

如果你的意思是合并多个文档，可以多选文档之后拖拽到目标文档内

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/12185

**Comment by KuiyueRO** [comment]
> > 另外还有一个关联需求，右键菜单新增一个合并到xx文档的选项，支持单选和多选
> 
> 如果你的意思是合并多个文档，可以多选文档之后拖拽到目标文档内（不过刚刚发现了 BUG #12607

恩恩这个我是知道的，但是拖拽合并对于大的工作空间不是特别的理想。

- 快速多选需要通过键盘的shift+方向键，然后右手切换到鼠标去拖拽
- 拖拽功能在平板端不能用
- 若想快速整理到不同路径，不停地开关对应文档树负担也有点重

**Comment by KuiyueRO** [comment]
https://liuyun.io/article/1731050550530

**Comment by TCOTC** [comment]
> > 可以多选文档之后拖拽到目标文档内
> 
> 很遗憾这个操作也不行了 #12607

现在又可以了 https://github.com/siyuan-note/siyuan/issues/13225
