### ISSUE TITLE
建议新增图片裁剪、旋转、翻转功能

### ISSUE THREAD

**Issue by tt545571022** [siyuan-note/siyuan#12604]
### In what scenarios do you need this feature?

经常出现这样的场景：在思源笔记中贴入图片后，图片中有部分内容不需要，希望将其裁剪掉。目前似乎不支持类似的功能。由此做一个小的延申，增加图片的裁剪、旋转、翻转这样的图片基础功能。

### Describe the optimal solution

经常出现这样的场景：在思源笔记中贴入图片后，图片中有部分内容不需要，希望将其裁剪掉。目前似乎不支持类似的功能。由此做一个小的延申，增加图片的裁剪、旋转、翻转这样的图片基础功能。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5573
