### ISSUE TITLE
伺服使用问题

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#12600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用电脑开启伺服，会出现图片显示的情况，
![5226ae9990d980fbdd66785f0f46ee6](https://github.com/user-attachments/assets/18baab04-75e2-4f11-88f8-4db2bc540130)；
个人排查：首先关闭js片段和所有插件，情况没有改变；ios18设备更换浏览器访问，会出现错误提示的频率不同；更换安卓设备访问正常；开启一个新的的工作空间访问也正常。

### Expected result

情况比较复杂，一时间难以排查

### Version environment

```markdown
- Version: 3.1.7
- Operating System: ios18
- Browser (if used): safar或者edge
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17140825/siyuan.log)

**Comment by leommjj** [comment]
更换新的工作空间偶尔也会提示！！！

**Comment by 88250** [comment]
这是正常的，使用 iOS 伺服的话不能切换应用并且要保持亮屏才行，因为 iOS 上应用一旦进入后台就会被休眠。

**Comment by leommjj** [comment]
> 这是正常的，使用 iOS 伺服的话不能切换应用并且要保持亮屏才行，因为 iOS 上应用一旦进入后台就会被休眠。

不是用ios设备开伺服，是用pc开伺服，然后用域名代理。我是用苹果ios18在手机端访问。

**Comment by leommjj** [comment]
pc和安卓设备通过“域名地址”访问都不会提示，所以我想是不是和ios18系统有关？

**Comment by 88250** [comment]
iOS 一直都这样的

**Comment by leommjj** [comment]
> iOS 一直都这样的

也没有切换后台和黑屏，就是会偶尔出现提示

**Comment by 88250** [comment]
那可能是网络问题，建议桌面端浏览器打开 F12 看看 WebSocket 等网络连接

**Comment by leommjj** [comment]
> 那可能是网络问题，建议桌面端浏览器打开 F12 看看 WebSocket 等网络连接

桌面访问没问题，就是苹果手机浏览器访问这样；不知道怎么解决

**Comment by 88250** [comment]
苹果手机访问自己手机伺服的？

**Comment by leommjj** [comment]
> 苹果手机访问自己手机伺服的？

苹果访问pc的伺服，

**Comment by leommjj** [comment]
用tcp开隧道就没有问题

**Comment by 88250** [comment]
那说明还是网络有点问题
