### ISSUE TITLE
Display tags in search results list

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12601]
### In what scenarios do you need this feature?

在搜索界面能否展示文档的标签
![image](https://github.com/user-attachments/assets/8ed57c57-c9be-4a41-8e82-72044eda6433)

### Describe the optimal solution

如上所说，希望在这个位置添加文档的标签
![image](https://github.com/user-attachments/assets/f0c754b4-1fc5-4f00-bc47-d6e0763dd95f)

**Comment by 88250** [comment]
这个要加就所有块都加吧，大致效果：

![image](https://github.com/user-attachments/assets/e285d4b7-944c-4761-a798-4725911436dd)

搜索结果高亮：

![image](https://github.com/user-attachments/assets/432fd225-0f54-4b4c-975f-2d000192bd87)

**Comment by SaXz2** [comment]
感谢D大，这样就好了
