### ISSUE TITLE
改进新用户的上手体验

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12602]
### In what scenarios do you need this feature?

在给其他人推荐思源的过程中，有不少新用户会遇到报错，比如下面这两张图，都是不同的人给的反馈。

这其实关系到新用户是否信任思源的稳定性，和有无解决方案关系不大。可能新用户一上手就遇到了这个问题，那估摸着不会再考虑使用思源笔记了，即使它的功能非常强大。

这其实贼尴尬，推荐别人用思源，结果进不去思源，这时候要不就是推荐的人帮忙一起排错，要不就是直接不考虑思源了。

![Screenshot_20240926_124848_com tencent mm](https://github.com/user-attachments/assets/ad2dde88-a53b-4cdf-bbc4-bd2ae2d05c53)

![Screenshot_20240926_124922_com microsoft office outlook](https://github.com/user-attachments/assets/18f6d75e-955a-496c-8439-332d72185236)

### Describe the optimal solution

能不能自动排查问题并给出建议或是直接把问题解决了😆😆😆

**Comment by 88250** [comment]
内核连接不通的话没啥办法处理，报错弹框中已经给了解决方案。
