### ISSUE TITLE
文档里面是否可以对 【长代码块】 添加折叠功能

### ISSUE THREAD

**Issue by LEDZB** [siyuan-note/siyuan#12611]
### In what scenarios do you need this feature?

当我需要往笔记中添加代码块的时候，如果代码块很长，整个笔记也会很长，是否可以添加一个功能，可以控制代码块的高度呢？

### Describe the optimal solution

建议增加代码块的高度控制

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/11055

**Comment by LEDZB** [comment]
意思是需要更新到 v3.1.4 版本？

**Comment by 88250** [comment]
这个改进目前还在计划中。
