### ISSUE TITLE
Can modify bookmark via search window

### ISSUE THREAD

**Issue by LJpLJ** [siyuan-note/siyuan#12613]
### In what scenarios do you need this feature?

文档块可以直接在搜索的浏览界面修改书签，不用单独在页签打开修改

### Describe the optimal solution

与原文档体验一致，在文档块內容顶部显示书签区域

### Describe the candidate solution

有路径打开文档浮窗

**Comment by TCOTC** [comment]
这么一说，我发现在搜索和浮窗都没法修改文档的标签，因为标题是隐藏的：

![image](https://github.com/user-attachments/assets/3a98b7a8-03f7-4e73-a378-e725ab4e411e)

**Comment by TCOTC** [comment]
与 #10693 是类似的需求

**Comment by 88250** [comment]
这个之前讨论过，不做调整了，只能在文档页签中修改，谢谢。
