### ISSUE TITLE
代码块，希望支持更多的编程语言

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#12616]
### In what scenarios do you need this feature?

如题，希望支持更多的编程语言，比如常见的 cuda-cpp、web assembly 等等

有些语言，对于不是这个领域的开发者，可能比较小众，是否可以考虑提供高亮模板

### Describe the optimal solution

支持

**Comment by TCOTC** [comment]
请向上游 hljs 反馈
