### ISSUE TITLE
Ctrl + Click on a block to open the block in a new tab instead of current tab.

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#12619]
### In what scenarios do you need this feature?

Working with multiple blocks at the same time is really fast and amazing

### Describe the optimal solution

When Ctrl+Click (or other shortcut) on a block it should open to the side on a new tab (Reference Logseq Shift+Click on block as reference)

### Describe the candidate solution

Same as above

### Other information

Current workaround is splitting the page and then scrolling to the respective block.

**Comment by TCOTC** [comment]
You could try setting a shortcut for `Split Right`, that would be handy:

![image](https://github.com/user-attachments/assets/38d9d899-eaaa-4939-a690-55c8c2a62ee9)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:
