### ISSUE TITLE
零高行号

### ISSUE THREAD

**Issue by M2uyo** [siyuan-note/siyuan#12617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

行号会出现零高的问题

### Expected result

正常计算行高

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/4340d158-e901-4b44-baf7-f822ffbfa9f8)

### Version environment

```markdown
- Version: 
- Windows 11
- Siyuan:3.17
```

### Log file

看起来没有啥特别的日志
![image](https://github.com/user-attachments/assets/36f69d96-00fb-4d1d-b8ca-06b648c20d29)
就是有几个在搜索过程中报错 (但是感觉这东东为啥也要报错?)

**Comment by TCOTC** [comment]
使用默认主题、关闭所有插件和代码片段之后重启思源，再看看有没有这个问题

**Comment by M2uyo** [comment]
> 使用默认主题、关闭所有插件和代码片段之后重启思源，再看看有没有这个问题

他这个主要出现的就很随机  有的时候有 有的时候就没有 另外重新进一下就好了

**Comment by TCOTC** [comment]
先排除第三方的影响，才能确认问题

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:
