### ISSUE TITLE
Mouse hover notebook to display some information

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12615]
希望笔记本也能显示文档数

### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/4f0f739e-fb94-4e50-87e7-4fa5fbc3acaf)

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
1. 下面那个是笔记本的数量
2. 我觉得笔记本也可以有像文档那样的悬浮提示

**Comment by 88250** [comment]
鼠标悬浮显示吧
