### ISSUE TITLE
界面异常、闪烁

### ISSUE THREAD

**Issue by SxLuol** [siyuan-note/siyuan#12610]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

问题：
24.09.25 正常使用，24.09.26出现此状态，软件启动起至其后，
如动图所示，发生闪烁、UI错乱。

25~26 期间：
1. 未变更系统、软件设置
2. 对 SiYuan 工作空间启用了 win11 "受保护的文件夹"，软件相关的访问进程已通过。

检查：
卸载了 24.09.25 系统质量更新（KB5043178），无效

### Expected result

触发此错误的原因。

### Screenshot or screen recording presentation

![screenshots](https://github.com/user-attachments/assets/6e3113f0-c596-4c16-8e5d-9569b5a48a90)

### Version environment

```markdown
- Version: v3.1.7
- Operating System: Win11专业工作站版_24H2_26100.1876
- Browser (if used):Edge
```

### Log file

[system-log.zip](https://github.com/user-attachments/files/17153041/system-log.zip)

**Comment by 88250** [comment]
> 对 SiYuan 工作空间启用了 win11 "受保护的文件夹"，软件相关的访问进程已通过。

建议换个工作空间路径测试看看。

多半是系统环境原因，先关闭了，感谢反馈。
