### ISSUE TITLE
复制到其他软件粘贴，如何去掉块之间的空行？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12612]
即使是在导出预览下复制，粘贴也是有空行的：

![image](https://github.com/user-attachments/assets/aa4c1e06-9997-4fd8-bd9a-90ace749fc85)

![image](https://github.com/user-attachments/assets/76b2f0d2-c7b3-424c-927a-e6254b388008)

**Comment by 88250** [comment]
这个去不掉吧，主要看目标软件如何解析 div 和 p
