### ISSUE TITLE
改进查找替换交互

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12618]
目前替换之后会一直阻止用户操作（并且时间过长），但用户不一定需要再次查找替换，一些场景下用户替换完就可以直接关闭搜索窗口了，因此也不需要等索引完成。

建议改为在搜索窗口内显示 loading-pure.svg ，以便用户关闭搜索窗口进行其他操作。

**Comment by 88250** [comment]
这个没有办法，因为 #12439 内需要等刷新结束。

**Comment by TCOTC** [comment]
内容替换明显是比搜索索引建立要快的，完全不需要继续等待：

[视频.webm](https://github.com/user-attachments/assets/f91869de-5c94-45e1-81a7-cda4448d934a)

**Comment by 88250** [comment]
要等索引完才能确定关联块刷新

**Comment by 88250** [comment]
不阻止的话替换期间数据可能会变动，影响一致性。

**Comment by TCOTC** [comment]
只阻止替换期间不行吗？

**Comment by 88250** [comment]
索引大致需要 5s 左右（看数据量），暂时没有办法更快了，前面说了，不索引的话无法计算关联的，所以只能等索引完了才能计算出来。

**Comment by TCOTC** [comment]
那以前的替换为啥会更快？

**Comment by 88250** [comment]
以前不用刷新关联块啊

**Comment by TCOTC** [comment]
哦，所以说 #12439 是 #8234 的衍生问题，是一直都有的问题

**Comment by 88250** [comment]
这两个没啥关联，主要是查找替换刷新关联块这个需求要实现就只能等索引完成



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年9月27日(周五) 晚上6:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 改进查找替换交互 (Issue #12618)




 
哦，所以说 #12439 是 #8234 的衍生问题，是一直都有的问题

**Comment by 88250** [comment]
性能优化可关注 https://github.com/siyuan-note/siyuan/issues/12777
