### ISSUE TITLE
功能请求:根据全局字段创建动态数据库

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12626]
### In what scenarios do you need this feature?

这个功能来源是Tiddly Wiki 的灵感， TiddlyWiki把所有条目的标签当做一个整体的数据库，每一个标签都相当于是一个文件夹或者是文件，如下图所示
![image](https://github.com/user-attachments/assets/649aab11-2a24-4ab3-b220-75cd98ee6aeb)

### Describe the optimal solution

期望改进的方式：
根据全局字段或是标签创建动态数据库

**Comment by TCOTC** [comment]
希望能靠 #10863 实现：自动将带有特定标签的文档或块添加到数据库中

**Comment by 88250** [comment]
请参考 @TCOTC 的回复，谢谢。
