### ISSUE TITLE
功能请求：自定义数据库行高

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12628]
### In what scenarios do you need this feature?

具体如下图

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/b7895124-32c0-4a89-ab2e-8ade2aead2ff)

**Comment by TCOTC** [comment]
自定义行高，我觉得在字段开启换行且文本过长时是挺有用的

**Comment by 88250** [comment]
不考虑了，因为可能会和其他显示设置产生冲突，比如换行显示。
