### ISSUE TITLE
功能请求:数据库上关联全局字段

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12625]
### In what scenarios do you need this feature?

目前的标签系统和局部数据库的标签的分开的，有时候需要两者保持一致，这样在录入标签的时候就也会方便很多

### Describe the optimal solution

需求：把全局字段关联到数据库
![image](https://github.com/user-attachments/assets/576661b2-10c7-4497-ae94-a61cbde86520)

**Comment by KuiyueRO** [comment]
这个我也支持一票，但不仅仅是标签系统，下面说下我的想法

目前从全局和局部的角度来看，双链笔记的数据库大致分为两个流派。

1. 以notion为例，每个数据库的属性都是相互独立的（关联除外）。
5. 以tiddlywiki、anytype、tana、未来的logseq、以及目前的obsidian属性为例，整个工作空间可以视为一个巨大的数据库，所有条目共用这些属性。

### 全局

全局有以下几个优点：

1. 通过某一属性快速找到所有关联条目，
2. 省心省力、高度复用（属性键值都可以复用）

但缺点也比较明显：

1. 为特定内容创建的属性也会在全局属性中出现
2. 值可能会造成污染

### 局部

局部的优点：

1. 干净整洁
2. 互不干扰（这两点是很重要的

缺点：

过于干净整洁，在长期使用中，每个数据库的属性填写设置算是个兔子洞，极易出现属性键或值近义的情况，这种情况在查询中比较麻烦，填写和修改成本也是未知的（在别的数据库有个一模一样的属性，但我不能直接使用）

### 总结下

这两派都有利有弊，一个是特定用途的属性污染结果（以下图为例），另一个是一次次重新填写。因此我认为允许用户在对用属性中自行设置是否为全局属性是个比较好的方式，并且若为全局属性，在添加列时属性的键和值可以直接候选。

目前看来模板、单选、多选、日期、创建日期、更新日期算是最适合自行开启全局属性的。别的属性类型也许也有需求。其中标签系统算是一种特殊的多选属性。

另外可以添加一个属性总览面板，在其中管理所有全局和局部属性（这两者可以分开），
1. 如手动合并相近属性和它们的值，这些值可以手动合并，或是全部保留。
2. 将全局属性分离为多个相同的局部属性等

哦哦对了还有一个衍生需求，自定义属性允许设置为全局属性，以方便重复使用，例如css、查询等。

![image](https://github.com/user-attachments/assets/9e29fb88-7ac5-48b0-b727-a5b6de397e10)

**Comment by TCOTC** [comment]
行内标签和文档标签不一样，实现不了双向同步修改

**Comment by 88250** [comment]
请参考 @TCOTC 的回复，谢谢。
