### ISSUE TITLE
功能优化：数据库筛选优化（为空和不为空）

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12629]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/063bd5b4-c198-47c5-a107-004564cae2d2)

### Describe the optimal solution

如上图一样，希望对于单选或者多选等字段中的为空和不为空修改为可勾选选项

**Comment by TCOTC** [comment]
Duplicate of #10550
