### ISSUE TITLE
关系图节点信息优先显示块名或备注

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1262]
https://ld246.com/article/1611146149173

**Comment by Achuan-2** [comment]
我觉得关系图节点不应该优显示块备注，块备注一般内容比较多，关系图都无法分辨这个点在哪里了，如果一个块是文档，那么显示的优先级应该是文档命名>文档名。
![PixPin_2024-11-13_15-07-32](https://github.com/user-attachments/assets/be5cc92f-7081-4129-9109-b94b5e11cedc)

**Comment by TCOTC** [comment]
备注这种东西应该悬浮显示才对
