### ISSUE TITLE
功能请求:自定义数据库块引新建文档位置

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12627]
### In what scenarios do you need this feature?

现在的块引新建文档，用的都是设置中统一变量，但是很多时候不同的数据库生成块引的位置也有所区别，希望可以自定义数据库块引存放位置

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/250d5528-66ac-4494-836e-6fb12b684e21)

另一种解决方案是对块引新建可以设置多种规则设置

**Comment by TCOTC** [comment]
Duplicate of #11479
