### ISSUE TITLE
切换语言后标题占位符会变成标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12622]
[视频.webm](https://github.com/user-attachments/assets/06adf2d0-2305-4242-9b6f-b2b74a77f8eb)

**Comment by 88250** [comment]
这个只能这样，因为内核层是不允许文档名为空字符串的，所以默认会填充当前语言“未命名文档”。

稍微改进一下，中文切换英文时由 “未命名” 改为 “未命名文档”，这样一致性更好一些。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
