### ISSUE TITLE
官方能否给个insertAttrViewBlock，这个api的请求体实例？

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#12634]
### In what scenarios do you need this feature?

文档看起来吃力，自己测试过后失败。请求帮助，例如https://github.com/siyuan-note/siyuan/issues/12475。

### Describe the optimal solution

1

**Comment by TCOTC** [comment]
Duplicate of #11130

**Comment by leommjj** [comment]
![image](https://github.com/user-attachments/assets/f82b8de4-fc3a-4d2f-af42-3389f15e53be)
api我知道，就是body是什么形式 不太懂

**Comment by 88250** [comment]
请参考开发者工具中的网络请求。

**Comment by Achuan-2** [comment]
这个调用很奇怪，blockID是数据库块的id，而不是文档块id
* avID：数据库id，非数据库块id，可在DOM中找
* blockID：数据库块id，非添加的块id
* srcs

  * id
  * isDetached

    * false：绑定块
    * true：非绑定块

```js
const docids = ['20240928004914-pwh0yxz']
const srcs = docids.map(docId => ({
    "id": docId,
    "isDetached": false,
}));
avid = '20240928104630-r293qm7' // 数据库
avblockID = '20240928111535-ts1vz4e' // 数据库块id


const input = {
  "avID": avid,
  "blockID": avblockID,
  'srcs': srcs
  
}
const result =await fetchSyncPost('/api/av/addAttributeViewBlocks', input)
```

**Comment by leommjj** [comment]
> 这个调用很奇怪，blockID是数据库块的id，而不是文档块id
> 
> * avID：数据库id，非数据库块id，可在DOM中找
> * blockID：数据库块id，非添加的块id
> * srcs
>   
>   * id
>   * isDetached
>     
>     * false：绑定块
>     * true：非绑定块
> 
> ```js
> const docids = ['20240928004914-pwh0yxz']
> const srcs = docids.map(docId => ({
>     "id": docId,
>     "isDetached": false,
> }));
> avid = '20240928104630-r293qm7' // 数据库
> avblockID = '20240928111535-ts1vz4e' // 数据库块id
> 
> 
> const input = {
>   "avID": avid,
>   "blockID": avblockID,
>   'srcs': srcs
>   
> }
> const result =await fetchSyncPost('/api/av/addAttributeViewBlocks', input)
> ```

数据库块id 怎么获取，我用查看数据库的api，只能看到键值的id

**Comment by Achuan-2** [comment]
@leommjj  编辑器右键复制块id即可
