### ISSUE TITLE
能否对任务列表添加todolist查询

### ISSUE THREAD

**Issue by noenif** [siyuan-note/siyuan#12636]
### In what scenarios do you need this feature?

在我的认知中
需要todolist的支持,很显然有些困惑的内容不一定在这一个章节能解决,而如果你跨章节大概率也是迷惑

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/045cd205-799d-4b07-a838-fe0006ef3ef0)
比如这种情况,我看了别人的解释,但是我有疑问,主要因为这块的内容他是后面的章节的,我可能现需要一个todolist.等到我学到哪一块的时候,我再来解决这个问题
但是因为东西比较分散.我实际上可能也已经忘了是否要解决.需要添加一下搜索功能,类似idea 中的一个todolist搜索框.

专门对一个目录下的todolist进行查询.看看还有多少知识点没有补全.我感觉这是一个帮助对笔记而言.

**Comment by TCOTC** [comment]
请使用 [siyuan-plugin-task-list](https://github.com/syh19/siyuan-plugin-task-list) 插件：

![image](https://github.com/user-attachments/assets/92a35b53-b010-4e05-b852-7faa74525352)

**Comment by noenif** [comment]
> 估计不会内置该功能，建议使用 [siyuan-plugin-task-list](https://github.com/syh19/siyuan-plugin-task-list) 插件：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/371719383-92a35b53-b010-4e05-b852-7faa74525352.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0OTA0NjYsIm5iZiI6MTcyNzQ5MDE2NiwicGF0aCI6Ii83ODQzNDgyNy8zNzE3MTkzODMtOTJhMzViNTMtYjAxMC00ZTA1LWI4NTItN2ZhYTc0NTI1MzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDAyMjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1M2RiNWEyODJjYzY5OTllNThhNmU3NjVkZmZjODE4Zjc3NTFkZjZlOWM4OTk5NmRlMWExZWY1YWI1MTkxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rp9aGZGUelyl4ZPi0Z_f3Ybh2GMEqRNBDT-uu_aTy94)

非常感谢,已经搞懂了
