### ISSUE TITLE
`新建子文档` 应能够在子级末尾新建丨`Add sub doc` should be configurable to add doc at the end of child

### ISSUE THREAD

**Issue by mamaruo** [siyuan-note/siyuan#12638]
### In what scenarios do you need this feature?

显而易见地，新建子文档时，在末尾添加是常见的——知识学习一般是顺序的。
It is obvious that when creating a new subdocument, appending it to the end of child is common—knowledge acquisition is generally sequential.

### Describe the optimal solution

添加一项设置，使得“新建子文档”能够在子级末尾新建。
Make `Add sub doc` configurable to add doc at the end of child.

### Describe the candidate solution

将`新建子文档`默认设为末尾添加。
Set `add sub doc` at the end as default.

**Comment by 88250** [comment]
抱歉，这个不考虑了，请参考 https://github.com/siyuan-note/siyuan/issues/3181

**Comment by TCOTC** [comment]
@mamaruo 请考虑使用 `在下方新建文档` ：

![image](https://github.com/user-attachments/assets/33000ed0-8e43-4f04-a695-76931bb07cbf)
