### ISSUE TITLE
在公式后面粘贴图片，然后在公式后面按回车会导致公式被复制一份

### ISSUE THREAD

**Issue by dream-tentacle** [siyuan-note/siyuan#12637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，下有录屏

### Expected result

修复bug

### Screenshot or screen recording presentation

https://github.com/user-attachments/assets/53342209-fa9f-4252-8257-150f14ee794b

### Version environment

```markdown
- Version: 3.1.7
- Operating System: windows
- Browser (if used): NO
```

### Log file

应该能复现，不行的话我再传

**Comment by Vanessa219** [comment]
不能重现，还麻烦上传一下 .sy。

**Comment by dream-tentacle** [comment]
[siyuan.log](https://github.com/user-attachments/files/17172265/siyuan.log)

**Comment by dream-tentacle** [comment]
[作业一.sy.zip](https://github.com/user-attachments/files/17172270/sy.zip)

**Comment by dream-tentacle** [comment]
@Vanessa219 测试感觉比较宽的图片（导致换到下一行）都会这样，我这边新开一个文档也能复现

**Comment by dream-tentacle** [comment]
当出现这种情况的时候，后一个公式具备如下性质：鼠标在该行后面点击，看不到闪烁的光标，按回车后又会复制，此时最后一行公式仍然具备该性质

**Comment by 88250** [comment]
我这里也不能重现。

请检查是否是插件或者代码片段影响。

**Comment by TCOTC** [comment]
> 按回车后又会复制，此时最后一行公式仍然具备该性质

我可以复现：

[sy.zip](https://github.com/user-attachments/files/17173869/sy.zip)

**Comment by Vanessa219** [comment]
@TCOTC 这个是坏的数据，按照他第一个录屏进行操作也能复现么？

**Comment by TCOTC** [comment]
那个操作我没复现出来

**Comment by TCOTC** [comment]
严格来说我不需要插入图片就能复现公式重复的问题：

[视频.webm](https://github.com/user-attachments/assets/7e82874e-567b-4069-8e69-1c072fe59fac)

**Comment by TCOTC** [comment]
不过说到跟图片相关的光标问题，我就想到 #12238

**Comment by dream-tentacle** [comment]
> 我这里也不能重现。
> 
> 请检查是否是插件或者代码片段影响。

我没用插件，文件里也没有代码

**Comment by Vanessa219** [comment]
麻烦下个版本再看看

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by TCOTC** [comment]
我这里还是选中公式的后半部分再按 Enter 就会创建一个重复的公式，这是预期内的行为吗？

**Comment by Vanessa219** [comment]
好像选不中公式的后半部分，一选就全选了。

**Comment by TCOTC** [comment]
就是上面那个录屏的情况，可以选中公式的后半部分

**Comment by TCOTC** [comment]
我希望向前选中之后回车也跟向后选中保持一致，都是回车取消选中：

[视频.webm](https://github.com/user-attachments/assets/f5df3963-c90c-4c50-8907-e31adb27cfc5)
