### ISSUE TITLE
功能优化：数据库链接行设置名称

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12631]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/c7dbfcea-f86d-4a32-a99d-b308a580320f)

### Describe the optimal solution

如上图所示，目前的数据库链接网址是不会添加设置名称
![image](https://github.com/user-attachments/assets/d5bbb18b-2695-40f1-addc-c72254b15ffa)

**Comment by TCOTC** [comment]
请使用数据库资源字段，可以填写链接标题

**Comment by SaXz2** [comment]
> 请使用数据库资源字段，可以填写链接标题

这里希望的是跟下方复制粘贴一样，能自动识别到链接名称，不然多一步的操作

**Comment by TCOTC** [comment]
选中资源字段的单元格即可粘贴

**Comment by 88250** [comment]
请参考 @TCOTC 的回复，谢谢。
