### ISSUE TITLE
侧边留白过大

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#1263]
![image](https://user-images.githubusercontent.com/11142054/105651298-7223a500-5ef1-11eb-9a11-0e67f35eec70.png)

如上图，建议把侧边的空白缩小点，这个实在有点宽呢。主要是不知道这么宽留着的作用是啥，加上思源其实支持多窗口，所以建议节约点空间
uy顺便再提一些改进的建议
1 建议还有空间的时候不隐藏按钮
2 支持自定义显示的按钮黑排序
 [shun]
![image](https://user-images.githubusercontent.com/11142054/105651225-3b4d8f00-5ef1-11eb-8f5e-4771316d818c.png)

**Comment by 88250** [comment]
你好，编辑器设置中有宽度调整；工具栏按钮配置请关注 #143 ，感谢反馈。

**Comment by regzhuce** [comment]
> 你好，编辑器设置中有宽度调整；工具栏按钮配置请关注 #143 ，感谢反馈。

编辑器中调整宽度到100%还是留白太多，感觉不是宽度设置的问题
