### ISSUE TITLE
【bug report】 使用滚轮、page up/down翻页与Ctrl+Z撤回出现光标乱跳问题反馈

### ISSUE THREAD

**Issue by Ghost-Girls** [siyuan-note/siyuan#1264]
### 描述问题 Describe the problem

1、滚轮以及键盘翻页导致的光标定位比较迷，有时先使用滑块移动了，使用滚轮、按键的时候会出现回滚现象
撤销后，光标移动跳转的位置过大，容易迷失操作。

2、撤销后页面滚动幅度大，且光标定位变化大，容易产生迷失感。

**Comment by 88250** [comment]
请问你使用的版本是？

**Comment by zhaojiansong** [comment]
V_0.6.6



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 上午10:10
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;; 
抄送: "猎游"<1028617702@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [siyuan-note/siyuan] 【bug report】 使用滚轮、page up/down翻页与Ctrl+Z撤回出现光标乱跳问题反馈 (#1264)





 
请问你使用的版本是？

**Comment by Vanessa219** [comment]
撤销请使用最新版看一下是否能重现。

滚轮滚动应该不会调整光标位置，问题一是否能详细描述或录屏？

**Comment by zhaojiansong** [comment]
这张GIF中有两个BUG，另一为ISSUE#1331



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月28日(星期四) 中午1:36
收件人:&nbsp;"siyuan-note/siyuan"<siyuan@noreply.github.com&gt;;
抄送:&nbsp;"猎游"<1028617702@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 【bug report】 使用滚轮、page up/down翻页与Ctrl+Z撤回出现光标乱跳问题反馈 (#1264)





 
撤销请使用最新版看一下是否能重现。
 
滚轮滚动应该不会调整光标位置，问题一是否能详细描述或录屏？

**Comment by 88250** [comment]
我先关闭了，信息有点不够方便定位。
