### ISSUE TITLE
从网页拷贝强调文字abc，思源直接变成文字 **abc** 而不是强调状态的abc（v3.16没有这个问题）

### ISSUE THREAD

**Issue by clfsoft** [siyuan-note/siyuan#12640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/76a76ffd-070a-4c4b-bd75-aa3467e61273)
变成
![image](https://github.com/user-attachments/assets/08d10c80-7027-4814-9cf7-ad0fd476ab74)

另外使用code编辑器插件(monaco-editor)对强调的处理也很奇怪
使用shiyuan强调文字那么code编辑插件正常显示。
![image](https://github.com/user-attachments/assets/652f91ef-84f7-4a03-90bc-e057c468fdeb)

但是反过来 在code 编辑器里头 添加强调那么siyuan就是显示成**
![image](https://github.com/user-attachments/assets/55ca44f0-8952-4c0d-aadf-81f1ec18b8f5)

### Expected result

![image](https://github.com/user-attachments/assets/c9192bbc-db8a-415a-9c4a-003afd3edc68)

### Version environment

```markdown
- Version: 3.17
- Operating System: widnows10 22h2 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17174122/siyuan.log)

**Comment by clfsoft** [comment]
另外推荐有一些最最基本的功能（那些是需要讨论），能否在release前面smoke test一下。
个人推荐是 和收集笔记+编辑笔记的部分（拷贝粘贴更是重中之重）。
其他就算出问题可以慢慢等下一个release。

**Comment by TCOTC** [comment]
1. 开启 设置 - 编辑器 - Markdown 行级星号语法
2. 请看通告：[如果你更新 v3.1.7 后发现粗体或斜体变成了星号 * - 链滴](https://ld246.com/article/1727172565679)

**Comment by TCOTC** [comment]
@88250 以后这种会大范围影响用户的改变确实应该在 changelog 提一下才行（这次我只想到了在链滴说一下

**Comment by 88250** [comment]
嗯，好的。

另外，楼主可以关注 dev 版。

我关闭了，如果还有问题请继续跟帖，谢谢。
