### ISSUE TITLE
Improve HTML code block clipping

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12642]
改进代码块剪藏

剪藏网页：https://blog.zhangyirui.cn/2023/12/04/transparency-blending-algorithm/

网页中代码块里有注释：

![image](https://github.com/user-attachments/assets/c3e9dd0f-1e77-4cf4-8c16-d289e8a22079)

剪藏后注释消失：

![image](https://github.com/user-attachments/assets/88556fff-1002-43af-808e-45a994925498)

**Comment by 88250** [comment]
稍后改进，需要升级剪藏扩展 v1.5.2

顺便把语言识别加强一下。
