### ISSUE TITLE
添加设置导入图片`单独识别OCR`功能

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12654]
### In what scenarios do you need this feature?

目前的 OCR 是挺好用的，但是它会对所有的图片都进行 OCR 识别，导致有些没有必要识别的图片也会被识别到，显示一堆乱码出来
![image](https://github.com/user-attachments/assets/137fa567-0fde-41a3-a06c-6b237a602e42)

### Describe the optimal solution

希望可以增加一个设置选项单独对图片进行 OCR 识别，并且设置可以关闭自动OCR

**Comment by 88250** [comment]
可以对图片 重新 OCR，但是无法对部分图片关闭，如果关闭的话只能全部关闭。

这个没有太好的方案可以两全其美，所以开关就统一管理了，感谢反馈。

**Comment by SaXz2** [comment]
> 可以对图片 重新 OCR，但是无法对部分图片关闭，如果关闭的话只能全部关闭。
> 
> 这个没有太好的方案可以两全其美，所以开关就统一管理了，感谢反馈。

那可以设置为关闭全部，用户手动OCR一张一张识别吗，我觉得这样更加实用一点，相比全部都OCR

**Comment by 88250** [comment]
这样的话不如用外部程序识别让后设置文本了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月30日(周一) 中午12:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 添加设置导入图片`单独识别OCR`功能 (Issue #12654)




  
可以对图片 重新 OCR，但是无法对部分图片关闭，如果关闭的话只能全部关闭。
 
这个没有太好的方案可以两全其美，所以开关就统一管理了，感谢反馈。
  
那可以设置为关闭全部，用户手动OCR一张一张识别吗，我觉得这样更加实用一点，相比全部都OCR

**Comment by zzsimplezz** [comment]
> 这样的话不如用外部程序识别让后设置文本了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月30日(周一) 中午12:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 添加设置导入图片`单独识别OCR`功能 (Issue #12654) 可以对图片 重新 OCR，但是无法对部分图片关闭，如果关闭的话只能全部关闭。 这个没有太好的方案可以两全其美，所以开关就统一管理了，感谢反馈。 那可以设置为关闭全部，用户手动OCR一张一张识别吗，我觉得这样更加实用一点，相比全部都OCR — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

Hello. I know the "manually set OCR text by external program" work but it take too much time for a simple task... I have a better idea...
**How about we add a toggle option to enable/disable OCR globally... so then we have 2 cases.**
1. Always enable work as default.
2. Toggle disable intentionally:
    - User can choose which image to get OCR
    - User can reenable for bulk lessons/slide images to get OCR and then turn if off.
