### ISSUE TITLE
[v.3.1.8] Creating group "siyuan" (<GID>) error

### ISSUE THREAD

**Issue by ilgigante77** [siyuan-note/siyuan#12655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Updating to v.3.1.8 without changing anything on workspace or in docker-compose file, the application cannot start and is struck with :
Creating group "siyuan" (<GID>)
(Are you sure you are root?)

Downgrading to 3.1.7 all is ok

### Expected result

Nothing is broken with the new image for Docker

### Version environment

```markdown
- Version: b3log/siyuan:v3.1.8 - b3log/siyuan:latest (Docker)
- Operating System: Ubuntu 24.04 (Docker host)
- Browser (if used): none
```

### Log file

No logs are produced

**Comment by 88250** [comment]
@Macavity Hi, could you help me look into this issue?

**Comment by redjumper** [comment]
provide your docker-compose file

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/pull/12658

**Comment by glaucon1984** [comment]
I see it's closed, but, has this been fixed on v3.1.8? If I update my docker container to :latest will it work or I should wait for the release of v3.1.9? will there be problems if I sync my docker container running on v3.1.7 with the Andoird/Windows clients running on v3.1.8?

**Comment by Macavity** [comment]
No, 3.1.8 introduced this issue and the fix is not yet in a released version.

**Comment by EJianZQ** [comment]
我在拉取了最新的docker镜像并启动时遇到了同样的问题

**Comment by redjumper** [comment]
去掉user: 'xxx:xxx'这一行，改用env PUID和PGID来指定

**Comment by ilgigante77** [comment]
Can you please reply in English?

Il mer 2 ott 2024, 15:48 redjumper ***@***.***> ha scritto:

**Comment by redjumper** [comment]
if you're using compose, remove the line user: 'xxx:xxx' and instead use
enviroment variables PUID and PGID.
You can check the readme for more infomation, docker deploy has changed
since 3.1.8

Il Gigante ***@***.***> 于 2024年10月2日周三 22:09写道：

**Comment by ilgigante77** [comment]
Thanks, I'll try

Il mer 2 ott 2024, 16:17 redjumper ***@***.***> ha scritto:
