### ISSUE TITLE
Improve performance of exporting .sy.zip for notebook

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12653]
压缩包发邮箱了

导出好久都是这样：

![image](https://github.com/user-attachments/assets/83ff3093-e728-46f4-8546-338b75735113)

![image](https://github.com/user-attachments/assets/ce6f31ae-59ff-44a5-ba5a-899772ad1d84)

**Comment by TCOTC** [comment]
这里也显示进度吧？

**Comment by 88250** [comment]
下个版本麻烦再测试看看。

**Comment by TCOTC** [comment]
好像没有成功显示进度，会停在下面这个状态几十秒：

![image](https://github.com/user-attachments/assets/9466c7cf-0da3-48e7-88c9-072488d4af0f)

**Comment by 88250** [comment]
可能是在复制某个大的资源文件，稍后把复制资源文件的进度推送调整到前面一点看看。

**Comment by TCOTC** [comment]
我这里还是这样，会有一段时间进度停在 `已创建数据文件[1938/1938/01基础领域/07水利/01水坝]` 没变化

**Comment by 88250** [comment]
暂时找不到原因了



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sat, Oct 12, 2024 23:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve performance of exporting .sy.zip fornotebook (Issue #12653)




 
我这里还是这样，会有一段时间进度停在 已创建数据文件[1938/1938/01基础领域/07水利/01水坝] 没变化

**Comment by 88250** [comment]
@TCOTC 找到一个 bug，稍后修复。
