### ISSUE TITLE
笔记本 `打开文件夹位置` 之后需要激活窗口

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12652]
否则文件夹窗口就会在所有窗口的最下面，看不见窗口：

[视频.webm](https://github.com/user-attachments/assets/de3037f0-964d-4cb9-9a8e-9a79cfe4932b)

**Comment by 88250** [comment]
我这里测试正常，你看下是不是设置了窗口置顶。

**Comment by TCOTC** [comment]
没有。打开的文件夹会在所有窗口（包括其他软件的窗口）的后面

**Comment by 88250** [comment]
我这里无法重现问题，建议检查一下是不是其他软件的设置导致的。

**Comment by TCOTC** [comment]
不清楚，我 Win10 和 Win11 都是这样

**Comment by 88250** [comment]
[issue.webm](https://github.com/user-attachments/assets/5edc80e9-7782-41fe-b3ac-ee686a1fc33c)

**Comment by TCOTC** [comment]
不止我是这样：

![Screenshot_2024-09-30-13-52-54-60_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/user-attachments/assets/292f2b2a-748b-4eb9-a666-7f03415d24bf)

**Comment by TCOTC** [comment]
貌似是 electron 的问题，思源里用 shell.showItemInFolder 打开文件夹是正常的，但用 shell.openPath 打开的文件夹就会显示在所有窗口的底部(open in the background)，包括打开笔记本文件夹、打开外观文件夹、打开图标文件夹……

参考：https://github.com/electron/electron/issues/36765

@88250 看看思源能改进吗？

**Comment by 88250** [comment]
暂时不能确定问题，我们这里正常的。

**Comment by Vanessa219** [comment]
感觉不是方法不同造成的，是不是设置过了窗口固定显示在最前？
