### ISSUE TITLE
改进隐藏/显示窗口和 Mac 上点击 Dock 图标

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#12656]
### In what scenarios do you need this feature?

目前 显示\隐藏窗口 的全局快捷键alt+m只对第一个打开的工作空间生效，对后打开的工作空间无效。希望能够对所有的工作空间都生效。

### Describe the optimal solution

可以在electron的渲染进程中焦点的获取事件，获取焦点后向主进程发送消息，在主进程中记录最后获取焦点的渲染进程。
按下alt+m全局快捷键时，主进程对最后获取焦点的渲染进程窗口进行显示\隐藏

**Comment by wish5115** [comment]
我测试了下，应该是热键冲突的原因，我给两个窗口分别设置不同的热键就可以了。

**Comment by wish5115** [comment]
Mac上点击dock图标也有这个问题，只第一个打开的工作空间显示，obsidian就没这个问题，总是显示最后一个使用的窗口。

**Comment by MisakaImouto8912** [comment]
出现一个问题，我之前是两个空间设置了不同的快捷键进行 显示/隐藏，一个是 ALT+M，一个是 ALT+N；这两个互不干扰，可是更新后两个快捷键都只对最后打开的窗口有效，无法用不同快捷键区分想要显示的空间了。 @Vanessa219

**Comment by Vanessa219** [comment]
下个版本改进
