### ISSUE TITLE
改进全局搜索结果数提示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12662]
在 data/.siyuan/searchignore 文件里添加一行 `box != '20240921172429-w3h7c0h'`（笔记本id）忽略搜索索引之后，重建索引，再搜索，发现还是能看到有多少个块。

忽略搜索索引之后不应该计入匹配块数：

![image](https://github.com/user-attachments/assets/c105d7c0-5fc2-44c8-bb48-bd36d194dba0)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
