### ISSUE TITLE
Highlight the path to the current block (in lists)

### ISSUE THREAD

**Issue by Tamriel** [siyuan-note/siyuan#12669]
### In what scenarios do you need this feature?

I want to see where my cursor is quickly.

### Describe the optimal solution

Like this blue line:
![grafik](https://github.com/user-attachments/assets/2704e712-dbfd-4589-8a39-1492923427a5)

**Comment by 88250** [comment]
Thanks for the suggestion, but we don't consider native implementation. Please try community themes or plug-ins to implement this function. Thank you.
