### ISSUE TITLE
Add reminders / dates

### ISSUE THREAD

**Issue by Tamriel** [siyuan-note/siyuan#12667]
### In what scenarios do you need this feature?

I want to be reminded of specific tasks when their date is due.
When I get reminded, I want to delete or edit each task (e.g. change the date).

### Describe the optimal solution

In a block I write a date in the form `<YYYY-MM-DD>`, e.g. `Water the garden <2024-10-30>`
That part is parsed as the date attribute of the block, so the content-block-embed search `{{ SELECT * FROM blocks WHERE date <= today }}` contains the block, when its date is reached.

To delete or edit the found blocks, currently I need to click on blocks. Then a popup opens. Inside the popup, I can edit the blocks.
I want to be able to edit the blocks in the results of the content-block-embed directly, without needing to click on the blocks.

**Comment by 88250** [comment]
Thanks for the suggestion, but we don't consider native implementation. Please try community themes or plug-ins to implement this function. Thank you.
