### ISSUE TITLE
Improve database primary key content update for bound container blocks

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12664]
数据库条目绑定列表(项)块时，修改首个块的内容之后不会更新数据库主键

- [ ] 即使重建索引也不会更新主键文本

关联 https://ld246.com/article/1727709402416

[视频.webm](https://github.com/user-attachments/assets/8a8b181c-2baf-453f-a3a2-6b09e67c0954)

**Comment by TCOTC** [comment]
这种情况下不会更新主键：

[视频.webm](https://github.com/user-attachments/assets/1047f4e0-4df5-4d0b-8243-526652a0b4aa)

**Comment by 88250** [comment]
稍后继续改进，谢谢。
