### ISSUE TITLE
Export with link to other files

### ISSUE THREAD

**Issue by Tamriel** [siyuan-note/siyuan#12668]
### In what scenarios do you need this feature?

1) I want to (regularly) publish the Notebook as a website.
2) Someday I may want to leave Siyuan completely and move my data to a different tool.

### Describe the optimal solution

In the following thread, the user adham shares a script which produces the optimal result:
https://liuyun.io/article/1700915419894/comment/1701416569711#comments
1) The logic of that script should be integrated into Siyuans export settings as a new export option.
2) The script should be improved in a way, that also links to headings in other files are included. In that thread it is discussed, how that could be done.

**Comment by 88250** [comment]
Thanks for the suggestion, but we don't consider native implementation. Please try community themes or plug-ins to implement this function. Thank you.
