### ISSUE TITLE
对接 Web Clipper

### ISSUE THREAD

**Issue by DiamondYuan** [siyuan-note/siyuan#1266]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

support web clipper.

### 描述最优的解决方案 Describe the optimal solution

提供一个本地的 http 服务，只需要 3 个接口
1. 获取目录树
2. 上传图片
3. 新建文档

就可以适配 web clipper https://github.com/webclipper/web-clipper

**Comment by 88250** [comment]
你好，我想象中整体流程大概是这样的，请看是否适合：

1. Web Clipper HTML 转换 Markdown
2. 列出笔记本，让用户选择存放到某个笔记本下
3. 上传资源文件，思源会生成 ID 附加到文件名后面
4. 创建文档，这一步需要修改之前的 Markdown 中的资源文件链接为上一步返回的路径

## 接口端点、参数和返回值

* 端点：`http://127.0.0.1:6806`
* 均是 POST 方法
* 需要带参的接口，参数为 JSON 字符串，放置到 body 里，标头 Content-Type 为 `application/json`
* 返回值

  ```json
  {
    "code": 0,
    "msg": "",
    "data": {}
  }
  ```

  * `code`：非 0 为异常情况
  * `msg`：正常情况下是空字符串，异常情况下会返回错误文案
  * `data`：可能为 `{}`、`[]` 或者 `NULL`，根据不同接口而不同

## 列出笔记本

* `/api/notebook/ls`
* 不带参
* 返回值

  ```json
  {
    "code": 0,
    "msg": "",
    "data": {
      "files": [
        "F:\\SiYuan\\data\\思源笔记用户指南",
        "F:\\SiYuan\\data\\测试笔记本"
      ]
    }
  }
  ```

  * `files`：笔记本绝对路径，所以得使用 `basename` 之类的函数截取笔记本名

## 上传资源文件

* `/api/asset/upload`
* 参数为 HTTP Multipart 表单

  * `assetsPath`：资源文件存放路径，实参有以下三种情况

    1. `"/assets/"`：工作空间 assets 文件夹
    2. `"/测试笔记本/assets/"`：为测试笔记本下的 assets 文件夹
    3. `"/测试笔记本/foo/assets/"`：测试笔记本下 foo 文件夹下的 assets 文件夹

    建议用第三种，其中文件夹 foo 就是上面创建文档时的文件夹，如果没有文件夹的话就是第二种情况。
  * `file[]`：上传的文件列表
* 返回值

  ```json
  {
    "code": 0,
    "msg": "",
    "data": {
      "errFiles": [""],
      "succMap": {
        "foo.png": "assets/foo-20210719092549.png"
      }
    }
  }
  ```

  * `errFiles`：处理时遇到错误的文件名
  * `succMap`：处理成功的文件，key 为上传时的文件名，value 为 assets/foo-id.png，用于将已有 Markdown 内容中的资源文件链接地址替换为上传后的地址

## 创建文档

* `/api/filetree/createDoc`
* 参数

  ```json
  {
    "notebook": "测试笔记本",
    "path": "/foo/bar.sy",
    "markdown": ""
  }
  ```

  * `notebook`：笔记本名称
  * `path`：文档路径，需要以 / 开头并以 .sy 结尾，中间使用 / 分隔层级
  * `markdown`：GFM Markdown 内容
* 返回值

  ```json
  {
    "id": "文档 ID"
  }
  ```

  * `id`：应该用不到，可忽略

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/126682626-e0b42cb1-db73-4a68-8a87-6607fd811672.png)

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/126682694-14e4798a-2d7b-4fca-bcbc-368a76eb64f7.png)

**Comment by DiamondYuan** [comment]
我参数传错了？

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/126725483-9d7964b0-ce01-459d-b1ab-9ef82d562cc3.png)
表单中文件字段的 name 是 `file[]`。

**Comment by 88250** [comment]
@DiamondYuan v1.2.2-alpha4 加入了 API 鉴权，需要麻烦你再改一下：

POST /api/system/loginAuth，body `{"auth": "用户配置的授权码"}`，response 标头里有 Cookie 值，后面的 API 请求需要带 Cookie 验证。

**Comment by 88250** [comment]
@DiamondYuan API 鉴权 https://github.com/siyuan-note/siyuan/issues/2537
