### ISSUE TITLE
Make URLs clickable

### ISSUE THREAD

**Issue by Tamriel** [siyuan-note/siyuan#12665]
### In what scenarios do you need this feature?

When I paste an URL into Siyuan (e.g. `https://github.com/siyuan-note/siyuan`), it is treated as plain text. I want to be able to click on it so it is opened in my webbrowser. To have it clickable, currently you have to press ctrl+k and then Enter to create a hyperlink. That is cumbersome.

### Describe the optimal solution

When pasting URLs, Siyuan should create a hyperlink automatically. Because nobody wants to have URLs as plain text (I guess).

**Comment by TCOTC** [comment]
> you have to press ctrl+k and then Enter to create a hyperlink.

I personally think this is fast enough.

> When pasting URLs, Siyuan should create a hyperlink automatically. Because nobody wants to have URLs as plain text (I guess).

In fact, this will bother users who need to paste plain text, such as a link after `[title]( `.

**Comment by Tamriel** [comment]
> I personally think this is fast enough.

Yes, it is fast, but it is a new key combination to learn. Moreover, ctrl+k is more difficult to press than ctrl+v. In LibreOffice the behavior is the same (URLs become hyperlinks automatically after pasting).

> In fact, this will bother users who need to paste plain text, such as a link after `[title]( `.

That case could be handled as an exception.

**Comment by 88250** [comment]
Sorry, this is by design and is not considered to be changed.
