### ISSUE TITLE
清除行级元素后工具栏的按钮颜色没有变

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12661]
1. 右边的按钮颜色不会变
2. ~~标签不会转换为文本，这是预期行为吗？~~ 确实是预期行为 #6501

https://ld246.com/article/1727674144530

[视频.webm](https://github.com/user-attachments/assets/c3c7d6f2-8bef-4b28-8707-5d7fa7638d32)

**Comment by Vanessa219** [comment]
已修复，不拉进版本
