### ISSUE TITLE
改进带链接的标题剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12676]
剪藏网页：https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow

### 不需要剪藏标题的超链接

如果标题元素上带有的链接是“当前网址+#…”的形式就不用剪藏了，例如：

- 当前网址：`https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow#构成的属性`
- 标题元素上的超链接：`https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow#尝试一下`

![image](https://github.com/user-attachments/assets/55ce778e-db01-4e1c-926a-8967f593a2ee)

<details>
<summary>行内代码剪藏</summary>

### 02 行内代码剪藏区分标签和实体

这里不应该剪藏成这样：

![image](https://github.com/user-attachments/assets/6a63d5d0-dd37-47ec-9b12-5c0035f38ef5)

应该是这样：

![image](https://github.com/user-attachments/assets/a70e97ab-bafd-441c-ad09-24883a84dec1)

也就是说行级代码的剪藏应该区分 HTML 标签和 HTML 字符实体：

```
<code><a href="/zh-CN/docs/Web/CSS/overflow-x"><code>overflow-x</code></a>: hidden</code>
剪藏↓
[`overflow-x`](https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow-x)`: hidden`

<code>&lt;a href=&quot;https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow-x&quot;&gt;&lt;code&gt;overflow-x&lt;&sol;code&gt;&lt;&sol;a&gt;: hidden</code>
剪藏↓
`<a href="https://developer.mozilla.org/zh-CN/docs/Web/CSS/overflow-x"><code>overflow-x</code></a>: hidden`
```

p.s. 代码块的话没法插入其他行级元素，所以剪藏时就不需要区分标签和实体了

</details>

**Comment by 88250** [comment]
标题超链接剪藏没有问题的，带锚文本可以跳转，如果网页跳转不了，应该是这个网页本身的锚文本不对导致的。

**Comment by TCOTC** [comment]
点击之后会跳转到剪藏的网页，感觉没有剪藏的必要，转换为文本又很麻烦

**Comment by 88250** [comment]
有必要的，可以跳转到锚点
