### ISSUE TITLE
新版本的使用习惯。

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1267]
* 之前图片换行就居中了，啥也没设置，现在所有图片默认居左，要一张一张更改，太麻烦，希望图片默认居中。
* 之前说图片缩放的自定义比例问题，是想直接在“即时渲染”的模式下，就可以更改，而不是需要调换到“专家模式”，再去更改，两步操作变成三步操作 = =。
![image](https://user-images.githubusercontent.com/69628966/105671774-3b17b880-5f1e-11eb-8ff0-0efd6e241432.png)
* 文件树和大纲，之前可以调位置的，习惯一个放上一个放下，现在全部整到上面去，又要更改使用习惯 = =。

**Comment by yeshaopeng6688** [comment]
萝卜青菜，各有所爱 ，新版本界面很简洁，但我喜欢老版本界面🤣
![image](https://user-images.githubusercontent.com/69628966/105672134-e294eb00-5f1e-11eb-9bb9-0a341273c417.png)

**Comment by roverway** [comment]
第一个不清楚。
第二个：渲染模式右键菜单改缩放比例
第三个：左上和坐下布局，可以一上一下，右侧也一样。

**Comment by 88250** [comment]
你好，请适应一下，谢谢。

**Comment by yeshaopeng6688** [comment]
> 第一个不清楚。
> 第二个：渲染模式右键菜单改缩放比例
> 第三个：左上和坐下布局，可以一上一下，右侧也一样。

* 之前版本，默认图片全部居中，现在0.67图片全部居左，意思就是要所有图片都要再手动改一个居中么。。
* 右键的确可以修改比例，但是不如直接显式修改来得方便，左右滑动很慢，不灵敏。如果难搞，这个无所谓，只是建议做成typora那样更好操作。
* 大纲和文件树，不能一上一下，之前我是大纲左上，文件树左下，现在大纲和文件树全部在左上，我需要看全局还得按快捷键转换，这个很麻烦，如果不能做成idea那样，自由调换位置（这也符合现在界面的简洁需求），那我就自己适应得了。
