### ISSUE TITLE
改进移动折叠标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12672]
1. 限定范围是“已折叠的标题”
2. 移动折叠标题时应该把子层级的所有块一起移动过去
   p.s. 我发现把标题块拖拽到文档树的时候是能实现的

问题录屏：

1. 拖拽移动块，会遗漏子块
2. 块标移动块，需要刷新文档

[视频.webm](https://github.com/user-attachments/assets/bf391fd7-aff9-4db1-9d51-a3bf3bc11ed1)

[视频.webm](https://github.com/user-attachments/assets/7fea9033-a438-4f89-aee5-d90d6bda309a)

另外如果这个 issue 解决了是不是能再解决 #11752 ？只要移动块没问题的话就能单独折叠了吧

**Comment by 88250** [comment]
这是个特性 https://github.com/siyuan-note/siyuan/issues/8321

**Comment by TCOTC** [comment]
@88250 我发现 https://github.com/siyuan-note/siyuan/issues/8321 跟本 issue 没啥关系啊，这个明显是编辑器 BUG
