### ISSUE TITLE
改进链滴代码剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12678]
剪藏网页：https://ld246.com/article/1464879728790

代码块：

![image](https://github.com/user-attachments/assets/6f59ae84-58d1-49f7-a735-0adf284bbd06)

![image](https://github.com/user-attachments/assets/fb99c2cc-bca6-4a5d-9169-ffd7c7944273)

没有剪藏成代码块：

![image](https://github.com/user-attachments/assets/e9803a52-fecf-4dc0-9187-0d79c50c024b)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
