### ISSUE TITLE
Inline insert ai chat block,

### ISSUE THREAD

**Issue by red-co** [siyuan-note/siyuan#12670]
### In what scenarios do you need this feature?

Currently, ai chat is very rudimentary.
1. A pop-up window is displayed instead of the inline buffer of the page. This will block the editor experience.
2. It is still a pop-up window problem. It makes it impossible to copy and paste other contexts and prompts from the editor.
3. Set a ai chat panel to set the context and requirements at here. Instead, the corresponding context is passed directly in the editor page.

### Describe the optimal solution

null

**Comment by 88250** [comment]
Sorry, the native interaction will not be considered for change for the time being. Please try the relevant community plug-in. Thank you.
