### ISSUE TITLE
Cannot open assets on iOS

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12675]
#12584 没有解决问题

1. https://ld246.com/article/1727262858752
2. ![image](https://github.com/user-attachments/assets/9000a1a3-b627-4480-b560-dd8d9bf763c6)

**Comment by 88250** [comment]
我们这里无法重现问题，得看看其他人的反馈。

**Comment by TCOTC** [comment]
用户反馈：

- [iPad 打开 pptx 弹出这个打不开，但安卓手机就能打开 - 链滴](https://ld246.com/article/1728393877119)

**Comment by pakeh2866** [comment]
依旧未解决：https://ld246.com/article/1728436915565

**Comment by 88250** [comment]
@pakeh2866 我们这里依旧无法重现问题，麻烦建立一个新工作空间帮忙测试看看。

**Comment by Vanessa219** [comment]
我这里是可以的，是不是设置了不允许浏览器打开？

https://github.com/user-attachments/assets/38b883ad-e3ef-40e4-b29e-54fcd4e54524
