### ISSUE TITLE
v3.1.8 1panel docker-compose

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12674]
不清楚是什么问题，先记录。

https://ld246.com/article/1727661361090/comment/1727787950435#comments

https://github.com/1Panel-dev/appstore/blob/dev/apps/siyuan/3.1.8/docker-compose.yml

**Comment by TCOTC** [comment]
是要有人给 1Panel PR 还是下个版本就自动好了？

**Comment by redjumper** [comment]
要pr，现在的处理逻辑要么不指定user,要么指定user 0:0，不然都会有问题

Jeffrey Chen ***@***.***> 于 2024年10月2日周三 22:30写道：

**Comment by TCOTC** [comment]
1Panel 已修复：https://github.com/1Panel-dev/appstore/commit/d1d905a3d948f36c5949e759ea5c9fb9fe425ccb
