### ISSUE TITLE
改进撤回后使用行级元素快捷键

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12679]
先按 Ctrl+G 再按 Ctrl+B 是正常的，但撤回一下再按 Ctrl+B 就会再创建一个行级代码：

p.s. 不只是 Ctrl+B ，按其他行级元素的快捷键也一样

[视频.webm](https://github.com/user-attachments/assets/11979a5b-f52c-496f-a8ce-2effbe371b5d)

预期应该是不会再创建一个行级代码

**Comment by Vanessa219** [comment]
已修复，不拉进版本了。
