### ISSUE TITLE
改进窗口关闭按钮的悬浮提示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12680]
偶尔会出现换行的情况：

![image](https://github.com/user-attachments/assets/c6d99683-6389-4ebe-a254-bccbbd5f532b)

**Comment by 88250** [comment]
无法重现，先关闭了，等有确定的重现步骤再看，谢谢。

**Comment by TCOTC** [comment]
我感觉可能跟这个现象相关，悬浮提示的宽度是不固定的：

[视频.webm](https://github.com/user-attachments/assets/b2e68951-777c-4501-96ef-9445b8a33525)

**Comment by TCOTC** [comment]
@Vanessa219

**Comment by TCOTC** [comment]
@Vanessa219 看看

**Comment by Vanessa219** [comment]
这个不处理了，显示不下换行是正常的。

**Comment by TCOTC** [comment]
为什么不再宽一点

**Comment by Vanessa219** [comment]
默认主题下面没有问题，先不处理了。
