### ISSUE TITLE
建议块内部用户自定义dom提交时可忽略，目前会被转换为HTML实体被提交

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12684]
### In what scenarios do you need this feature?

如题，
比如有一个代码块，
<img width="916" alt="image" src="https://github.com/user-attachments/assets/7a109f2c-ea20-4792-9776-ca7f0d0fd4d5">
修改代码块内容，内容被提交后，按f5，变成了代码的一部分
<img width="891" alt="image" src="https://github.com/user-attachments/assets/69916ffe-b210-4e64-af15-c0bdf12bc25a">
网络抓包数据
![r69](https://github.com/user-attachments/assets/9e66d4c9-df64-4d10-9918-434ead7282c4)

普通块也一样，比如，下面的段落块
<img width="559" alt="image" src="https://github.com/user-attachments/assets/b64d637f-885c-421d-b8fb-47260c1bb367">

修改块内容，内容被提交后，变为了
<img width="549" alt="image" src="https://github.com/user-attachments/assets/30971b5f-daa5-45ee-8cac-7cec249c7a24">
网络抓包数据
![r68](https://github.com/user-attachments/assets/5df2772d-6983-40c5-a237-56c5a74703b5)

### Describe the optimal solution

建议可以给用户自定义dom添加属性，然后可根据这个属性，在提交块内容时忽略该dom

比如：

```html
<div data-custom-ignore="true">......</div> 
```
然后在块提交时，可忽略此dom。

关联帖子：https://ld246.com/article/1727621671852/comment/1727911436752?r=wilsons#comments

**Comment by TCOTC** [comment]
protyle-custom 行不行？

https://github.com/88250/lute/pull/207

**Comment by 88250** [comment]
用 protyle-custom 应该可以忽略的，我先关闭了，感谢反馈。

**Comment by wish5115** [comment]
> 用 protyle-custom 应该可以忽略的，我先关闭了，感谢反馈。

好的，感谢！学习了。

**Comment by wish5115** [comment]
> protyle-custom 行不行？
> 
> [88250/lute#207](https://github.com/88250/lute/pull/207)

好的，感谢！学习了。
