### ISSUE TITLE
文档路径显示 功能

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1268]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/105671892-6bf7ed80-5f1e-11eb-9c97-f7bde27e6943.png)
如图，思源UI 上方目前是空白，可以如idea显示文件路径一样，显示**笔记路径**
笔记路径其实也是笔记的上级信息，可以了解笔记的定位
如果可以还可以和文件树联动（点击路径定位到文件树展开）

### 描述最优的解决方案 Describe the optimal solution

多数大纲类都有这样的功能，比如RemNote：
![image](https://user-images.githubusercontent.com/46141646/105672034-aeb9c580-5f1e-11eb-9b82-6352af891e8a.png)

**Comment by 88250** [comment]
感谢建议，我们合并到 #1231 中一起实现。
