### ISSUE TITLE
使用 jdecked/twemoji 作为可选的内置 emoji 字体

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12689]
> #11375 的后续

[jdecked/twemoji](https://github.com/jdecked/twemoji) 是 [twitter/twemoji](https://github.com/twitter/twemoji) 的分支，emoji 更完整（看上去即将支持 [Unicode 16.0](https://github.com/jdecked/twemoji/issues/88) ），Discord 也在用这个 emoji 字体，算是经过了市场检验的。

Code licensed under the MIT License: <http://opensource.org/licenses/MIT>

Graphics licensed under CC-BY 4.0: <https://creativecommons.org/licenses/by/4.0/>

考虑到可能有的人更喜欢自己系统的 emoji 字体（以及某些系统的 emoji 字体是没问题的），所以建议添加一个开关切换，并且默认对用户关闭。

![image](https://github.com/user-attachments/assets/78c83e56-f9e9-47b5-b202-4deb4fc483df)

p.s. 我的 Win10 和 Win11 都缺很多 emoji ，Windows 上的体验真的很差

**Comment by 88250** [comment]
不考虑更换图片类型的，尽量使用系统原生字体。

**Comment by TCOTC** [comment]
原来以前用过 twitter-emoji.js https://github.com/siyuan-note/siyuan/issues/8206
