### ISSUE TITLE
改进即刻网页剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12681]
剪藏网页：https://web.okjike.com/repost/66fd6b757e4026e015db6b43

内容没有剪藏下来：

![image](https://github.com/user-attachments/assets/0782b58d-26f8-4b87-ae14-6ace7dc0f545)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by 88250** [comment]
需要升级剪藏扩展 1.5.3
