### ISSUE TITLE
导出预览和实际导出的结果不吻合

### ISSUE THREAD

**Issue by dahuzi-gege** [siyuan-note/siyuan#12685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这是在文章中导出预览中桌面看到的视图：
![image](https://github.com/user-attachments/assets/2c0c54b9-cad7-4bf0-b65e-51acf1a1b4c2)
这是在导出图片或者导出PDF的视图：
![image](https://github.com/user-attachments/assets/91e5de77-a063-4cb9-9ea6-2767a3fe0c3f)

### Expected result

应该导出预览中桌面视图和导出图片和PDF的视图一模一样才对

### Version environment

```markdown
- Version: 3.1.8
- Operating System: windows  和 docker
- Browser (if used):浏览器使用
```

### Log file

这个不知道

**Comment by TCOTC** [comment]
点击导出图片或者 PDF 的时候弹出的就是对应的预览窗口了。

而导出预览模式是跟 HTML Markdown 一样的：

![image](https://github.com/user-attachments/assets/2befc408-4230-4bd4-a184-f480e9e377d8)

**Comment by 88250** [comment]
楼上正解。
