### ISSUE TITLE
`保存查询条件` 时支持选择保存的条件

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12686]
### 背景

发现有的用户只想保存某几类条件，不保存其他查询条件，希望在使用查询条件时能：

- 能覆盖路径
- 不覆盖搜索的文本
- 排序方式不变
- ……

### 方案

`保存查询条件` 时支持选择保存哪些条件，而不是默认都保存了（路径是默认不保存的）

**Comment by dahuzi-gege** [comment]
支持，不能保存路径真的让人很烦恼。场景1：假如查询单词：我在其他笔记本里想查询这个单词，我每次想查询这个单词都得必须先去选择这个文档。非常花时间。

**Comment by 88250** [comment]
这里不考虑复杂化设计了，查询条件是所有当前设置的总和，不支持仅设置部分条件。

@dahuzi-gege 我这里测试路径可以正常工作，你看下是不是保存查询条件时没有路径条件。
