### ISSUE TITLE
在 Ctrl+F 搜索中使用查询条件，文档路径不应该带到 Ctrl+P 全局搜索中

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12687]
录屏前半部分是在 Ctrl+P 搜索中使用查询条件，可以看到之后 Ctrl+F 和 Ctrl+P 搜索的路径是独立的，前者是当前文档路径，后者是查询条件路径。

录屏后半部分是在 Ctrl+F 搜索中使用查询条件，可以看到之后 Ctrl+F 和 Ctrl+P 搜索的路径是相同的，前者是当前文档路径，后者仍然是之前的文档路径，而不是查询条件中的路径。

如果使用了查询条件，那么在 Ctrl+P 搜索中应当使用查询条件中的路径。

[视频.webm](https://github.com/user-attachments/assets/5fb39231-10b4-4a59-b129-6b3444f26070)

**Comment by dahuzi-gege** [comment]
https://github.com/siyuan-note/siyuan/issues/12686
我使用了Ctrl+P达到了我提的要求。。。哈哈！！！但是我觉得Ctrl+P替换成 Ctrl+F才是正确的

**Comment by Vanessa219** [comment]
是不是没用清空查询条件，我这里是正常的。

https://github.com/user-attachments/assets/928ba7b5-bf5c-475a-9288-5be6159f637e

**Comment by TCOTC** [comment]
按 Ctrl+F 之后要点一下查询条件，再按 Ctrl+P 全局搜索

**Comment by Vanessa219** [comment]
这个操作过了嘛。

**Comment by TCOTC** [comment]
问题是这个当前文档路径不是查询条件，Ctrl+P 的时候不应该出现

**Comment by Vanessa219** [comment]
操作的就会记录，路径也属于查询条件的。
