### ISSUE TITLE
数据库链接字段支持忽略非链接文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12690]
Notion 这个感觉好灵活，链接前后的文本都会被忽略（填写多个链接的情况下只会打开第一条链接）：

[视频.webm](https://github.com/user-attachments/assets/c09e70a9-64ff-4c62-98cc-2454b9309ab6)

我觉得思源也可以这样，感觉方便多了，还能顺便实现给链接添加锚文本的用户需求：

- #9635
- https://ld246.com/article/1727900601471

以及重新考虑一下实现 #12483

**Comment by 88250** [comment]
超链接没有可靠的识别方式，实际上很容易有 bug，比如少个空格就不行了，还是不做了。
