### ISSUE TITLE
FR: 页签元素新增属性

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12695]
### 01 添加一个属性，值是文档 id

想通过 JS 实现禁止关闭特定页签的功能，需要按文档 id 找到页签

### 02 添加一个属性，值是笔记本 id

在写一个[代码片段](https://ld246.com/article/1727980528164)，要判断最后聚焦的文档页签所在的笔记本。

需要思源在页签元素上添加一个属性，值是笔记本 id（如果页签不是文档的话就不需要添加这个属性了）：

p.s. 属性名可以叫 `data-box` 之类的
p.s.s. 其实值是 path 也行，毕竟 path 的开头就是笔记本 id

![image](https://github.com/user-attachments/assets/eec38355-1a4b-417b-8f94-ccf7af247595)

---

当然，如果有其他方便的办法能获取最后聚焦的文档页签所在的笔记本，这个属性可能就没必要加了

**Comment by Vanessa219** [comment]
使用 `getAllModels` 获取编辑器页签对象，需要的值都在里面了。
