### ISSUE TITLE
`折叠` 文档树后需要保存文档树状态

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12692]
折叠文档树之后关闭思源，下次打开思源时又会重新展开文档树，感觉不合理。

---

目前一刷新就会恢复：

[视频.webm](https://github.com/user-attachments/assets/81aee794-4a47-4f4c-8e7b-451a1638a9e2)

**Comment by FancyBEAST** [comment]
How to refresh like that? 🤔

**Comment by TCOTC** [comment]
use Developer Tools, Ctrl+R

![image](https://github.com/user-attachments/assets/ddb9796e-97db-4953-aa83-8e01be0f9642)
