### ISSUE TITLE
本地文件插入链接优化

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#127]
![image](https://user-images.githubusercontent.com/873584/94543079-2da63680-027c-11eb-8666-3d68b0f2655a.png)

![XQFLWW 0NQ7QFGPY2Z)Q3W0](https://user-images.githubusercontent.com/873584/94941102-03b47480-0507-11eb-8345-7ec155609e62.png)
![image](https://user-images.githubusercontent.com/873584/94941173-1c248f00-0507-11eb-8980-e68348f4a447.png)

目前是拖拽文件到编辑器时会自动复制文件到文档同级 assets 目录下，但有的时候用户需要的仅是插入 `[filename](filepath)` 链接。所以可能需要加个开关来配置拖拽文件进入编辑器时的操作，或者拖入后让用户选择下一步应该怎么办（是复制文件到 assets 呢还是仅插入链接文本）。

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/839 中考虑。

**Comment by Richardggm** [comment]
> “可能需要加个开关来配置拖拽文件进入编辑器时的操作，或者拖入后让用户选择下一步应该怎么办（是复制文件到 assets 呢还是仅插入链接文本）”

希望能够是第一种方案，即可以在设置中默认设置好，而不是每次都需要选择下一步怎么办。因为对于习惯用这个功能的用户来说，拖动文件进笔记的操作很频繁，"每次都要选择下一步怎么办"就显得比较繁琐。
