### ISSUE TITLE
Bug: global/local search double cliick to open doc in BROWSER

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When in global/local search view in browser:
- Double click to go to doc don't work .But triple click to go to doc work (I means "Go to" , not "preview")

### Expected result

Double click to go to doc

### Version environment

```markdown
- Version: 3.1.8
- Operating System: 
- Browser (if used): Edge
```

### Log file

.

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
