### ISSUE TITLE
改进数据库单元格编辑的输入框大小

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12708]
[视频.webm](https://github.com/user-attachments/assets/62dbfbc4-7657-4fca-a4eb-111902d40791)

Notion 会先顶到界面左边，然后再往右边伸长，并且在单元格很长的情况下，点击的单元格不会跳动：

![image](https://github.com/user-attachments/assets/252051d2-d1b8-464e-84a7-6ec67deafddf)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
