### ISSUE TITLE
数据库点击 `计算` 行时应该根据鼠标位置定位

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12707]
鼠标点哪里就在哪里的下方弹出才是最方便的，否则字段越长就越麻烦。

[视频.webm](https://github.com/user-attachments/assets/3ee3eee0-db83-45a2-aedf-24b078b44178)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Vanessa219** [comment]
不拉进版本了
