### ISSUE TITLE
Ctrl+M会最小化窗口

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#12702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

ctrl+M默认创建行级公式,把它删掉之后, ctrl+M会最小化窗口
![PixPin_2024-10-04_19-58-24](https://github.com/user-attachments/assets/420d3690-3f58-4a69-b431-911d5d8729ef)

### Expected result

ctrl+M啥也不干

### Version environment

```markdown
- Version: 3.1.8
- Operating System: win10
- Browser (if used):
```

### Log file

`

**Comment by iamqiz** [comment]
好像是Electron 的问题, 新版qq按ctrl+M也会最小化😂

**Comment by TCOTC** [comment]
确实

**Comment by 88250** [comment]
Fixed in https://github.com/siyuan-note/siyuan/issues/12735

**Comment by TCOTC** [comment]
更新 Electron 应该没有解决问题。只要光标不在编辑器里，按 Ctrl+M 就会最小化窗口。

**Comment by 88250** [comment]
确实还是有问题。

**Comment by 88250** [comment]
globalShortcut.unregister("CommandOrControl+M"); 

也没有办法取消，估计只能等 Electron 修复了。

**Comment by iamqiz** [comment]
查了下,ctrl+m最小化是electron有意实现的快捷键:
https://github.com/electron/electron/issues/16338

~建议改思源,增加一个无功能的按键项,用来阻止ctrl+m等键~
我之前提这个issue是因为我autohotkey脚本写的一个热键有问题,导致在思源里ctrl+shift+m按键会误触发ctrl+m,所以想把ctrl+m禁用了; 现在我把那个热键禁用了, ctrl+m就不怎么需要禁用了
