### ISSUE TITLE
改进新浪财经剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12705]
关联帖子：https://ld246.com/article/1728096510058

剪藏网页：https://finance.sina.com.cn/stock/relnews/2024-10-03/doc-incrfmwc2722671.shtml

没有剪藏出东西：

![image](https://github.com/user-attachments/assets/daf9cd41-ca3b-47d2-ae6f-70ed73be4b27)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

需要升级剪藏扩展 v1.5.4
