### ISSUE TITLE
FR: Support remove db record at the block level

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12709]
### In what scenarios do you need this feature?

One block can have multile database... but it is hard to remove its record at the block in the editor.

![image](https://github.com/user-attachments/assets/66d128a0-0a70-4cfc-8543-5a84ec91174d)
 

### Describe the optimal solution

Add a delete button along the record.

**Comment by TCOTC** [comment]
Do not consider adding deletions to this location, the panel mainly does data updates, not additions and deletions. #10581

You can refer to this operation method: https://github.com/siyuan-note/siyuan/issues/10581#issuecomment-2016821418

**Comment by zzsimplezz** [comment]
> Do not consider adding deletions to this location, the panel mainly does data updates, not additions and deletions. #10581
> 
> You can refer to this operation method: [#10581 (comment)](https://github.com/siyuan-note/siyuan/issues/10581#issuecomment-2016821418)

Nah... I know I can delete the record manually like the video... But as normal user, this delete action too complicated.

And I think the "delete" button really fit with the panel... Put it at the right-top to distinguish... Don't you think so?

**Comment by TCOTC** [comment]
Hmm... I also think this will be convenient in some usage scenarios. If possible, I hope to add Unbind block and Delete buttons. After clicking, a pop-up window will pop up for secondary confirmation to avoid misoperation:

![image](https://github.com/user-attachments/assets/78cc155d-23e0-4c67-a755-15f62d4059fd)

That's for @88250 to consider.

**Comment by TCOTC** [comment]
Improve in https://github.com/siyuan-note/siyuan/issues/13375
