### ISSUE TITLE
支持 `word-break: break-all;` 情况下的代码块行号计算

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12715]
## 背景

相关帖子：https://ld246.com/article/1727688144141

先使用这个代码片段：

```css
.protyle-wysiwyg .hljs > div[contenteditable] {
    word-break: break-all !important;
}
```

然后把下面这段代码复制粘贴到代码块里，开启代码块换行和行号：

```php
if ($_SESSION['is_snapshotuser'] == 1) {
	$_SESSION['is_snapshotuser'] = 0;
	return ['nickname' => '微信用户', 'avatar' => 'https://thirdwx.qlogo.cn/mmopen/vi_32/Q3auHgzwzM5EPsm1NEriaoj9ONhxhcWKz9RbNRnYhaooks1zicFGllRezc7Ya7v5WNqAMtfIxTpF7FVdNpXZnuNA/132'];
}
```

行号高度的计算就会有问题：

![image](https://github.com/user-attachments/assets/af686bb9-f8f2-4f35-accd-aa779b50ab07)

## 方案

不知道能不能实现，但我想到一个思路：

1. 用 [Window.getComputedStyle()](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/getComputedStyle) 获取代码元素的样式
2. 如果 `.wordBreak === "break-all"` ，则按 break-all 来计算代码块的行号

相关的需要修改的应该是这段代码：

https://github.com/siyuan-note/siyuan/blob/6278d97486cb29370446276f49495701f076da14/app/src/protyle/render/highlightRender.ts#L117-L165

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Vanessa219** [comment]
https://ld246.com/article/1727688144141/comment/1732412801927?r=Vanessa#comments

**Comment by TCOTC** [comment]
我说的是回帖里发现的这个问题呐：

![image](https://github.com/user-attachments/assets/ab2883e0-d3a8-4883-abcb-df3d322d88e1)

**Comment by Vanessa219** [comment]
这个问题参见回帖。
