### ISSUE TITLE
添加内核接口 `/api/block/getDocsInfo`  ，用于批量获取文档信息

### ISSUE THREAD

**Issue by Misuzu2027** [siyuan-note/siyuan#12718]
### In what scenarios do you need this feature?

为了提高响应速度，可以通过参数控制是否返回 文档引用数量、关联的属性数据库。

### Describe the optimal solution

无

**Comment by 88250** [comment]
感谢提议，我们在 https://github.com/siyuan-note/siyuan/pull/12719 中跟进。
