### ISSUE TITLE
一些块的背景色需要带透明度

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12713]
需要跟 #12706 #12712 一起改，有必要的话我一起 PR

- 块的默认颜色（带透明度）
- 父块带颜色的情况 → 跟块的默认颜色叠加
- .protyle-wysiwyg--select 或 .protyle-wysiwyg--hl 的情况 → 叠加混合
- .protyle-wysiwyg--select 和 .protyle-wysiwyg--hl 一起的情况 → 两次叠加混合

### 01 嵌入块需要用带透明度的颜色

这个颜色跟 --b3-theme-background 混合之后等于 --b3-theme-surface ：

![image](https://github.com/user-attachments/assets/03707bff-7ddb-4554-abd8-c660bfbd2bec)

### 02 代码块也改成统一用嵌入块那个带透明度的颜色：

- 关联 https://github.com/siyuan-note/siyuan/issues/12712

![image](https://github.com/user-attachments/assets/acecc5dc-dcb9-480b-ac8f-422e6d193650)

### 03 表格的颜色：

白色格子改成透明，灰色格子改成前面嵌入块那个带透明度的颜色

![image](https://github.com/user-attachments/assets/2e5ff8d0-7d86-4cdd-a9a5-ad5b45bd5c8b)

### 04 引述块需要用带透明度的颜色

左侧的颜色需要跟父块叠加；主体的颜色跟 --b3-theme-background 混合之后等于 --b3-list-hover

![image](https://github.com/user-attachments/assets/2ed01bac-c409-49dd-8ceb-69111302431a)

p.s. 闪卡的颜色保持不变，不需要叠加

**Comment by Vanessa219** [comment]
修改了引述块、潜入块和表格的。代码块深色主题背景色是不一致的。
