### ISSUE TITLE
After pressing Down key the cursor will move to the the begin of the next line

### ISSUE THREAD

**Issue by RigHakiko** [siyuan-note/siyuan#12710]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

While editing the note. If press Down key, the cursor will move to the the **begin** of the next line 

### Expected result

the cursor will move to the position where it should be

### Version environment

```markdown
- Version: 3.1.8
- Operating System: Mac OS 15.0.1
- Browser (if used):
```

### Log file

-

**Comment by TCOTC** [comment]
[视频.webm](https://github.com/user-attachments/assets/1c68bef4-ca85-4cea-8d2b-a21b713fc56a)

**Comment by 88250** [comment]
关联
* 代码块或以软换行结尾的块移动光标 ↑ 会跳过 https://github.com/siyuan-note/siyuan/issues/5498
* 代码块全选后 ↑ 光标不会上移 https://github.com/siyuan-note/siyuan/issues/11581
