### ISSUE TITLE
增强搜索功能：跨块搜索

### ISSUE THREAD

**Issue by realysy** [siyuan-note/siyuan#12716]
### In what scenarios do you need this feature?

情景：

* 记得写过某篇笔记，但不记得文档名，只记得包含两个关键词，想根据这两个关键词把这篇文档搜索出来
* 这两个关键词都不是非常特殊的词，可能包含在很多文档中，所以用单一的关键词可能会搜索出很多篇文档，所以需要两者共用搜索
* **问题在于**，当这两个关键词不在同一个块中时（比如不在同一个段落中），使用**空格分隔**的多个关键词搜索，无法搜索到结果
  * 块1：关键词A
  * 块2：关键词B
* **期望结果**：能搜索到包含多个关键词的文档，即使这些关键词不在同一个块中

下面是我的测试文档和测试搜索
* 测试笔记文档（文档内容即上面的情景描述）
  [想要搜索到的测试文档.sy.zip](https://github.com/user-attachments/files/17269891/sy.zip)

* 使用`关键词A 关键词B`测试搜索，由于文档中`关键词A`和`关键词B`不在同一个块中，无法搜索到这篇文档
  ![图片](https://github.com/user-attachments/assets/8b9d254a-bb79-45b8-8f2c-5898c5d684c7)

一个真实的例子是，
* 我写了很多篇关于virtualbox的笔记，都给他们打了virtualbox的tag或者在文件名中添加了virtualbox单词；
* 然后我记得有一片关于virtualbox设置ip的笔记，搜索`virtualbox ip`却没有搜索到任何内容。
* 而事实上我确实有一篇标题为virtualbox的笔记，其正文中包含`ip`这个单词，由于ip所在的段落中没有同时出现virtualbox，导致搜索不到

### Describe the optimal solution

最佳的方法可能是，对于搜索框中的空格划分的多个关键词，分别在文档中搜索，返回文档中匹配到所有关键词的文档

### Describe the candidate solution

一种备选方法是，提供`在结果中搜索`功能按钮，让用户先搜索一个关键词，然后再输入一个关键词点击`在结果中搜索`，此时只在之前搜索到的文档中进一步搜索

### Other information

思源笔记版本：v3.1.8

**Comment by TCOTC** [comment]
Duplicate of #10584

目前你可以使用 基于文档搜索 插件：

![image](https://github.com/user-attachments/assets/127277f2-494b-4b74-bbde-fa51b2a6a6d9)

**Comment by realysy** [comment]
谢谢，这个插件 基于文档搜索 确实可以

**Comment by TCOTC** [comment]
已于 3.1.11 支持 https://github.com/siyuan-note/siyuan/issues/10584
