### ISSUE TITLE
复制豆包的代码块内容粘贴到思源里，无法形成行级公式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12725]
复制豆包的代码块内容粘贴到思源里，无法形成行级公式

关联帖子：https://ld246.com/article/1728298039535

[视频.webm](https://github.com/user-attachments/assets/389aa042-fa38-4a5a-8409-21cd4a4d3c74)

对话的提示词：

```
利用数学归纳法 +Ramsey 数递推关系即可，注意到$ R(k,l)\leq R(k-1,l)+R(k,l-1)\leq C_{k+l-3}^{k-2}+ C_{k+l-3}^{k-1} $，利用组合数的 Pascal 公式，得到 $C_{k+l-3}^{k-2}+ C_{k+l-3}^{k-1}=C_{k+l-2}^{k-1}$，得证。 把上面这段文本放在 markdown 代码块输出，不要修改
```

豆包复制的内容：

![image](https://github.com/user-attachments/assets/367e16cc-229b-4530-b515-73bc7bb4b6be)

**Comment by 88250** [comment]
第一个 `$` 后面不能有空格。

**Comment by TCOTC** [comment]
@88250 但从代码块里复制粘贴出来的时候有空格也没影响它转换为行级公式

**Comment by 88250** [comment]
看来不是空格的问题，后面仔细看看。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
