### ISSUE TITLE
增加按钮，打开 petal 目录

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#12729]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/c3192547-702c-40b8-9643-0927b76bab50)

### Describe the optimal solution

添加一个按钮，打开插件对应的 petal 目录（如果存在的话）

**Comment by TCOTC** [comment]
合理，并且图标得用除了文件夹以外的图标

**Comment by 88250** [comment]
这个不考虑了吧，对于用户来说打开这个意义不大哦。

我关闭了，感谢提议。

**Comment by TCOTC** [comment]
能直接打开插件安装目录，但是不能直接打开配置目录，就感觉怪怪的。
