### ISSUE TITLE
使用 updateBlock with markdown 时，mermaid 代码块未正确展示

### ISSUE THREAD

**Issue by akkuman** [siyuan-note/siyuan#12736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我使用 updateBlock 来对文档进行内容更新，如果内容中含有 mermaid 代码块，则内容更新后没有正确展示

![image](https://github.com/user-attachments/assets/8e0712a0-7e73-41d0-b5dd-682afa3203ae)

### Expected result

预期应该是 mermaid 代码块展示为图

### Version environment

```markdown
- Version: 3.1.8
- Operating System: windows11
- Browser (if used):
```

### Log file

暂无

**Comment by 88250** [comment]
我这里测试正常，请发一下 request body payload

**Comment by TCOTC** [comment]
@akkuman 用小写 m 试试：

![image](https://github.com/user-attachments/assets/c53a5a1d-41af-4c92-a5ad-55a7b21da76f)

**Comment by akkuman** [comment]
> @akkuman 开头用小写 m 试试：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/374600323-c53a5a1d-41af-4c92-a5ad-55a7b21da76f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MzYxNTEsIm5iZiI6MTcyODQzNTg1MSwicGF0aCI6Ii83ODQzNDgyNy8zNzQ2MDAzMjMtYzUzYTVhMWQtNDFhZi00YzkyLWE1YWQtNTVhN2IyMWRhNzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAxMDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjkxZjMxMzNjZGFmYzdlYzU2YTkwNDJmY2RkYzQ3MTUwMjA1OWQyZTg5ZTgyMDczOWIwZTlmNmQyZjRlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gLmWoayXJ4e62W66udtge5PYA4DMhdw0D2TtaShoZYQ)

是这个原因，感谢
