### ISSUE TITLE
数据库支持固定条目数分页与分页导航

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12730]
数据库很复杂的情况下，固定显示一定数量的条目，然后分页加载，前端性能会好很多

加上左右箭头和当前页数：

![image](https://github.com/user-attachments/assets/0ae961be-b8a9-45f9-8ffc-626cfb0c1e4d)

---

用户反馈：

![image](https://github.com/user-attachments/assets/95de24d2-64fc-42d4-8741-fd38d1e14341)

**Comment by 88250** [comment]
这个就不动了，之前就是显式分页加载的，不考虑改回去了。
