### ISSUE TITLE
引用搜索列表候选项顺序优化

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#12733]
### In what scenarios do you need this feature?

目前 [[ 引用搜索列表键入关键词后，候选项的顺序是固定的
![image](https://github.com/user-attachments/assets/6641424e-fa01-4e7a-9764-1858667285e5)

### Describe the optimal solution

建议做如下优化：
- 最后引用的放在第一位
- 最近有引用过的放在前几位
这样可以更加快速地选到想要的内容

**Comment by 88250** [comment]
没有搜索关键字的话是最近的放前面的。

**Comment by AdachiQ** [comment]
> 没有搜索关键字的话是最近的放前面的。

有搜索关键字的时候也需要这么处理呀~

**Comment by 88250** [comment]
有关键字的话就按照关键字搜索的排序逻辑处理了

**Comment by TCOTC** [comment]
> 最后引用的放在第一位
>
> 最近有引用过的放在前几位

@AdachiQ 我这里试的就是这样，你那里是什么排序？
