### ISSUE TITLE
引用计数元素位置错误

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12738]
### 01

引用计数插入在 DOM 里的位置有问题，导致以下现象：

1. 列表块的引用计数高亮的是首个列表项
2. 在列表项存在引用计数的情况下，引用列表块不会显示引用计数，需要刷新恢复正常

[视频.webm](https://github.com/user-attachments/assets/05433cad-7608-43f0-9cf2-29ee5d63d722)

### 02

[引用计数1.sy.zip](https://github.com/user-attachments/files/17296917/1.sy.zip)

嵌入块中没有显示引用计数：

![image](https://github.com/user-attachments/assets/0b54dc28-a4ca-4547-b290-b38ca9f4e831)

**Comment by Vanessa219** [comment]
对不齐是由于列表项在列表中有空隙，方便拖拽可以拖拽到列表项之后。
 
![QQ_1728442512742](https://github.com/user-attachments/assets/12caf7a4-a2d8-4f9a-8371-5a86191cdd69)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by TCOTC** [comment]
啥对不齐？

**Comment by Vanessa219** [comment]
上面2点已修改
