### ISSUE TITLE
The `Allow execution of scripts within HTML blocks` option cannot be enabled on mobile

### ISSUE THREAD

**Issue by poetmilk** [siyuan-note/siyuan#12744]
安卓允许执行HTML块内脚本选项打不开

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

安卓版本：设置-编辑器-允许执行HTML块内脚本，这个选项打不开。

### Expected result

安卓版本：设置-编辑器-允许执行HTML块内脚本，这个选项打不开。

### Screenshot or screen recording presentation

安卓版本：设置-编辑器-允许执行HTML块内脚本，这个选项打不开。

### Version environment

```markdown
安卓版本：设置-编辑器-允许执行HTML块内脚本，这个选项打不开。
```

### Log file

安卓版本：设置-编辑器-允许执行HTML块内脚本，这个选项打不开。

### More information

安卓版本：设置-编辑器-允许执行HTML块内脚本，这个选项打不开。

**Comment by TCOTC** [comment]
打不开是指什么意思？

![Screenshot_2024-10-10-10-46-59-93_ed1bdeca7a858bb430bfb9c256856672.jpg](https://github.com/user-attachments/assets/d1dda4c8-f5bb-4b2b-ba63-46ac2bcd1095)
