### ISSUE TITLE
  v3.1.9-dev5 添加到数据库不显示已有数据库

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

  v3.1.9-dev5 添加到数据库不显示已有数据库
![PixPin_2024-10-09_15-03-17](https://github.com/user-attachments/assets/ea002af0-d6c6-49ff-adff-0bbe873f6c60)
![PixPin_2024-10-09_15-03-23](https://github.com/user-attachments/assets/7d40cc2e-114b-4c92-9ecd-017987c6b941)

### Expected result

添加到数据库显示已有数据库

### Version environment

```markdown
- Version:   v3.1.9-dev5
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/pull/12723 引入的问题，稍后修复。
