### ISSUE TITLE
For the latest version 3.1.8,  pasting text copied from ChatGPT will lose the format (leaving plain text not rendered)

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#12749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

```
* **Early Wittgenstein**: His "Tractatus" is a work on logic and the philosophy of language, asserting that the structure of language mirrors the logical structure of the world. This work influenced logical positivism and analytical philosophy.
* **Later Wittgenstein**: In his later work, Wittgenstein rejected many of his earlier ideas and focused on how language is used in everyday practices. His "language-games" theory has had a wide-ranging impact on philosophy, linguistics, and cognitive science.
```
When pasted, the first star will be rendered as item dot as normal, but words wrapped in ** ** will be left plain text. This issue only happens after updated to the 3.1.8 version (or latest versions within a few days)

### Expected result

Render pasted Markdown correctly.

### Screenshot or screen recording presentation

<img width="531" alt="无标题" src="https://github.com/user-attachments/assets/d28dde4e-c18b-41e8-bfbf-d02ea1762044">

### Version environment

```markdown
- Version: 3.1.8
- Operating System: Win 10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17336899/siyuan.log)

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/6406173c-c097-4384-9d47-0974c08887d4)
