### ISSUE TITLE
更新时间和创建时间字段的类型问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12748]
![image](https://github.com/user-attachments/assets/fe32b404-510f-44a8-8873-216e60f7b9ee)

更新时间和创建时间字段：

![image](https://github.com/user-attachments/assets/4a519e5e-2c2c-40d4-a7e1-45dc10edc12f)

日期字段：

![image](https://github.com/user-attachments/assets/67959d00-0188-4412-ba9f-37daf33d5c4d)

```
.action{ $date := index . "日期" }
.action{ div (now.Sub $date).Hours 24 }
```

**Comment by 88250** [comment]
使用 index ."更新时间" 的话取到的是列值，所以就是字符串了，模板里面可以使用内置变量取 .created .updated 取值，这个是 date 类型的。

https://github.com/siyuan-note/siyuan/issues/9364
