### ISSUE TITLE
无法进行批量替换

### ISSUE THREAD

**Issue by woodchen-ink** [siyuan-note/siyuan#12745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/66e631f4-bbc2-4344-af49-bb502ad72983)
![20241010114920_rec_](https://github.com/user-attachments/assets/59436b8f-e6c0-40f2-b634-0abc8dff36db)

### Expected result

正常替换掉内容

### Version environment

```markdown
- Version: 最新
- Operating System: windows 11 
- Browser (if used):
```

### Log file

none 很容易复现, 就不用贴日志了吧

**Comment by TCOTC** [comment]
替换类型有没有选择图片链接？

![image](https://github.com/user-attachments/assets/88a19140-b003-4330-ad2c-932103d64ab5)

**Comment by woodchen-ink** [comment]
> 替换类型有没有选择图片链接？
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/375208513-88a19140-b003-4330-ad2c-932103d64ab5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzI5MzIsIm5iZiI6MTcyODUzMjYzMiwicGF0aCI6Ii83ODQzNDgyNy8zNzUyMDg1MTMtODhhMTkxNDAtYjAwMy00MzMwLWFkMmMtOTMyMTAzZDY0YWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzNTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZDc2ZDg5YjU4ZjcxM2NhYWJkMzFhOGRiOGI3N2RhNzhmMjc1OTVkNjc1ZTlmMDUzZDA3MzU4M2NlOWRhZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-JyqIPVtray2OyHl0OY2PBSWUjAS3zXMHEmzqeQHDFA)

刚发现这里还有按钮, 点进去启用后可以替换了, 谢谢.

这里设计..为什么不是默认全选呢, 而且我这次勾中了, 第二次点击替换又重置为"未选中"状态

**Comment by TCOTC** [comment]
你可以 保存查询条件 或者清空查询条件再选择

**Comment by woodchen-ink** [comment]
> 你可以 保存查询条件 或者清空查询条件再选择

明白, 谢谢
