### ISSUE TITLE
命名、别名、备注和书签合并到属性设置中

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#1275]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
- 块命名/块别名/块备注, 现在是三个入口，对于内容块来说，我认为三者都是块的属性。
- 既然是属性，入口做成一个，可以同时查看/编辑，提高交互体验，也便于理解
![图片](https://user-images.githubusercontent.com/15924513/105707005-40d8c280-5f4d-11eb-87ee-563c49d61cfd.png)

### 描述最优的解决方案 Describe the optimal solution
入口合并成一个：  
![图片](https://user-images.githubusercontent.com/15924513/105707425-e12ee700-5f4d-11eb-9ce3-7f736a8dbddd.png)
编辑以卡片/块的方式展现，可以同时编辑/查看“块命名/块别名/块备注”：  
![图片](https://user-images.githubusercontent.com/15924513/105706835-07a05280-5f4d-11eb-8fb2-2cf9462ff917.png)

### 其他信息 Other information

思源版本: 0.6.7
操作系统：win10

**Comment by 88250** [comment]
感谢老铁的提议，暂时不考虑了。

**Comment by 88250** [comment]
v1.2.0 beta4 实现。

**Comment by 88250** [comment]
延迟一波…… 😓
