### ISSUE TITLE
华为开发者文档识别异常

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#12757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

问题是发现在HarmonyOS的文档上的，下面2个链接都文章都能复现内容无法正确：
1. [网页页脚被识别成了正文，而正文内容没识别到](https://developer.huawei.com/consumer/cn/doc/harmonyos-references-V5/natural-language-word-tag-api-V5)
2. [正文内容没有识别到，且代码块复制粘贴异常](https://developer.huawei.com/consumer/cn/doc/harmonyos-guides-V5/image-pixelmap-operation-native-V5)
这里主要对二号链接给出截图
![image](https://github.com/user-attachments/assets/a99406cb-919e-4911-aeee-3dc3c06440a9)
其次对于二号链接内的代码块，识别上似乎变成了列表的html
![image](https://github.com/user-attachments/assets/90a4e352-2ff4-4053-b465-d7d8bac066d9)

### Expected result

正确识别文章并摘录

### Version environment

```markdown
- Version: 3.1.8
- Operating System: Windows 10
- Browser (if used): Chrome 120
```

### Log file

同样的文章，OpenHarmony官网上的能正常摘录识别https://docs.openharmony.cn/pages/v5.0/zh-cn/application-dev/media/image/image-pixelmap-operation-native.md

### More information

问题理论上能稳定复现

**Comment by 88250** [comment]
感谢反馈，请关注思源和剪藏扩展的新版本发布，下个版本都升级一下应该就好了。
