### ISSUE TITLE
全选代码块缩进，希望鼠标光标能保持全选，以便连续多次缩进

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12753]
### In what scenarios do you need this feature?

现在全选代码块缩进，缩进后，选中区域就变成了下面的几行，不方便连续多次缩进
![PixPin_2024-10-12_11-31-34](https://github.com/user-attachments/assets/1b732d7e-5a2b-455d-a77d-11168213df82)

### Describe the optimal solution

全选代码块缩进，希望鼠标光标能保持全选，以便连续多次缩进

### Describe the candidate solution

无

**Comment by TCOTC** [comment]
提供一下代码

**Comment by Achuan-2** [comment]
我感觉我都是稳定出现的
```js
plugins.push(new CopyPlugin({
    // 用途：把文件放在dist，用来打包
    patterns: [
        { from: "preview.png", to: "./dist/" },
        { from: "icon.png", to: "./dist/" },
        { from: "README*.md", to: "./dist/" },
        { from: "plugin.json", to: "./dist/" },
        { from: "src/i18n/", to: "./dist/i18n/" },
        { from: "src/index.css", to: "./dist/" }, // Add this line
        { from: "src/assets/", to: "./dist/assets/" } // Add this line
    ],
}));
plugins.push(new ZipPlugin({
    filename: "package.zip",
    algorithm: "gzip",
    include: [/dist/],
    pathMapper: (assetPath) => {
        return assetPath.replace("dist/", "");
    },
}));
} else {
plugins.push(new CopyPlugin({
    // 用途：run dev的时候放在当前目录，可以直接运行
    patterns: [
        { from: "src/i18n/", to: "./i18n/" },
        { from: "src/index.css", to: "./" }, // Add this line
        { from: "src/assets/", to: "./assets/" } // Add this line
    ],
}));
}
```

**Comment by 88250** [comment]
我这里 Ctrl+A 后 Tab 有问题，用鼠标全选后 Tab 没有问题

**Comment by Achuan-2** [comment]
> 我这里 Ctrl+A 后 Tab 有问题，用鼠标全选后 Tab 没有问题

哦哦，确实是 Ctrl+A 后 Tab 有问题，用鼠标全选后 Tab 没有问题

**Comment by TCOTC** [comment]
我这里只要上面选择了任意一个语言就会有问题：

![image](https://github.com/user-attachments/assets/6998436f-08fc-4759-b952-2e0324843c59)

![image](https://github.com/user-attachments/assets/ac390861-5b78-4dd8-a04e-31f8b7ae6b4a)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
