### ISSUE TITLE
insert 'dom' block 之后无法为 block 设置属性

### ISSUE THREAD

**Issue by grunmin** [siyuan-note/siyuan#12756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

```js
async function insertHTML(){
	const html_content = `<div>
	<p>gogog</p>
	<p>2222</p>
	</div>`
	response = await api.insertBlock('dom', html_content, '', thisBlock.id)
	console.log('response', response)
	block_id = response[0].doOperations[0].id
	await api.setBlockAttrs(block_id, {
            	'custom-page-id': String(33333),
	        })
	attr = await api.getBlockAttrs(block_id)
}
insertHTML()
```
以如上代码为例，该代码可以使用 sy-run-js 插件运行。当 insert 的是 markdown 时，可以正常 setBlockAttrs。当 insert 为 dom 时，出现 3 个问题
1. 展示异常，需要关掉文档重新打开才正常
2. 无法设置 attr，报错 tree not found
3. 有概率出现 状态异常提示，需要重建索引

这些函数都是思源原生的 API，应该跟插件逻辑无关，因此反馈到思源仓库

### Expected result

插入 dom 能像插入 markdown 一样正常工作

### Version environment

```markdown
- Version: v3.1.8
- Operating System: Mac
- Browser (if used):
```

### Log file

```
W 2024/10/12 15:09:58 tree.go:220: block tree not found [id=20241012150958-80kl86s], stack: [    github.com/siyuan-note/siyuan/kernel/model.LoadTreeByBlockID({0xc012f94060, 0x16})
        /Users/Vanessa/Work/Code/siyuan/kernel/model/tree.go:218 +0x5b
    github.com/siyuan-note/siyuan/kernel/model.SetBlockAttrs({0xc012f94060, 0x16}, 0xc004f14ff0)
        /Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:164 +0x4c
    github.com/siyuan-note/siyuan/kernel/api.setBlockAttrs(0xc01144e200)
        /Users/Vanessa/Work/Code/siyuan/kernel/api/attr.go:101 +0x50b
]
W 2024/10/12 15:09:58 tree.go:220: block tree not found [id=20241012150958-80kl86s], stack: [    github.com/siyuan-note/siyuan/kernel/model.LoadTreeByBlockID({0xc012f941e0, 0x16})
        /Users/Vanessa/Work/Code/siyuan/kernel/model/tree.go:218 +0x5b
    github.com/siyuan-note/siyuan/kernel/model.getBlockAttrs({0xc012f941e0, 0x16})
        /Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:337 +0x31
    github.com/siyuan-note/siyuan/kernel/model.GetBlockAttrs({0xc012f941e0, 0x16})
        /Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:317 +0x74
    github.com/siyuan-note/siyuan/kernel/api.getBlockAttrs(0xc000238500)
        /Users/Vanessa/Work/Code/siyuan/kernel/api/attr.go:68 +0x12d
]
```

**Comment by 88250** [comment]
你好，请使用 API 文档中的内核接口通过 HTTP 客户端工具（比如 Postman）进行测试，包装过的 API 不利于定位问题，谢谢。

**Comment by 88250** [comment]
另外需要注意插入的 DOM 必须是思源的 DOM 格式，比如：

```html
<div data-node-id=\"20241013110455-uoct968\" data-node-index=\"1\" data-type=\"NodeParagraph\" class=\"p\" custom-test=\"bar\" updated=\"20241013110455\"><div contenteditable=\"true\" spellcheck=\"false\">foo</div><div class=\"protyle-attr\" contenteditable=\"false\">​</div></div>
```

这个例子里面一并插入了自定义属性，不需要再次 setBlockAttrs。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by grunmin** [comment]
OK，

> 另外需要注意插入的 DOM 必须是思源的 DOM 格式，比如：
> 
> ```
> <div data-node-id=\"20241013110455-uoct968\" data-node-index=\"1\" data-type=\"NodeParagraph\" class=\"p\" custom-test=\"bar\" updated=\"20241013110455\"><div contenteditable=\"true\" spellcheck=\"false\">foo</div><div class=\"protyle-attr\" contenteditable=\"false\">​</div></div>
> ```
> 
> 这个例子里面一并插入了自定义属性，不需要再次 setBlockAttrs。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

好的，思源的DOM格式有文档或代码可以参考吗？
事实上我在做一个类似剪藏的功能：提供url，运行js代码后在当前block下插入网页内容，将网页内容直接同步到需要的地方，并且支持覆盖式更新。
之所以不先转为markdown，是因为复杂表格只能用pandoc grid_tables扩展来解析，转换后的markdown用kramdown无法解析（事实上我将kramdown文档里的复杂表格markdown代码拷贝到siyuan发现siyuan渲染有问题）。所以目前看只能使用插入dom的方式。

**Comment by TCOTC** [comment]
> 思源的DOM格式有文档或代码可以参考吗？

用开发者工具自己看就行了

**Comment by 88250** [comment]
@grunmin 转换 Markdown 可以考虑用 Lute

**Comment by grunmin** [comment]
> @grunmin 转换 Markdown 可以考虑用 Lute

starred, 感谢  
siyuan的网页剪藏插件也是用lute吗

**Comment by 88250** [comment]
网页剪藏不涉及转换，转换是在思源内核上完成的，用的是 Lute

**Comment by grunmin** [comment]
> 网页剪藏不涉及转换，转换是在思源内核上完成的，用的是 Lute

再请教下，有计划将lute转换的能力通过API暴露出来吗？看API文档目前只暴露了pandoc的接口

**Comment by 88250** [comment]
/api/lute/html2BlockDOM
