### ISSUE TITLE
在块标上滚动鼠标滚轮，文档页面不会滚动

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12751]
有时候鼠标会碰到块标，这个时候无法滚动文档页面

![image](https://github.com/user-attachments/assets/eeeb4844-e232-4c3b-a236-132b8ec358c4)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
