### ISSUE TITLE
优化对文献有超链接的图片的剪藏

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12759]
### In what scenarios do you need this feature?

网址：https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9974100/
PMC是生物医学专业主要用的文献数据库之一，
打开文献，每个Figure都是可以点击放大图片的，图片被超链接嵌套
![PixPin_2024-10-12_16-58-38](https://github.com/user-attachments/assets/d0758f71-005c-42c0-8dee-6426c697306a)

经过思源笔记的剪藏插件剪藏之后是这样
![PixPin_2024-10-12_16-56-19](https://github.com/user-attachments/assets/f5a61628-2fde-4a94-80d1-adf02f30af30)

希望剪藏效果是这样
![PixPin_2024-10-12_16-59-14](https://github.com/user-attachments/assets/902da0b3-f5c7-45ba-8f51-6feb3c4c2eef)

### Describe the optimal solution

优化对文献有超链接的图片的剪藏

**Comment by Achuan-2** [comment]
Nature 文献剪藏全文：https://www.nature.com/articles/s41586-024-07915-x
![PixPin_2024-10-12_17-31-44](https://github.com/user-attachments/assets/c474a2e6-7301-4f97-acaf-be401eb0b05b)

**Comment by 88250** [comment]
这个没有办法，思源无法支持图片和超链接嵌套，所以只能把超链接放到图片后面。

**Comment by Achuan-2** [comment]
这个能优化下吗
![PixPin_2024-10-12_17-34-20](https://github.com/user-attachments/assets/b8f67f83-d9b5-406c-940f-3a48db9d45b8)

**Comment by Achuan-2** [comment]
> Nature 文献剪藏全文：https://www.nature.com/articles/s41586-024-07915-x ![PixPin_2024-10-12_17-31-44](https://private-user-images.githubusercontent.com/60436214/375947416-c474a2e6-7301-4f97-acaf-be401eb0b05b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjU4NTAsIm5iZiI6MTcyODcyNTU1MCwicGF0aCI6Ii82MDQzNjIxNC8zNzU5NDc0MTYtYzQ3NGEyZTYtNzMwMS00Zjk3LWFjYWYtYmU0MDFlYjBiMDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA5MzIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMDVlMjA2ZDhkODUzZGM0ZTY5ZTViNjMzZTBmYWQxZTNmNTZlYWI3ODI4MjU0Y2ZiZTQ1NjlhZjQzY2ZkZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IKwZSeStXBbranxZkwz504vI1dHZ_oSVa3sDYl05tzg)

另外被超链接嵌套的图片剪藏，能否将超链接放在下一行，而不是和图片放在同一行

**Comment by Achuan-2** [comment]
另外思源其实也可以模仿在线图片的样式，对于有超链接的图片添加一个伪元素，可以点开打开链接，而隐藏图片后面的超链接
![PixPin_2024-10-12_17-37-41](https://github.com/user-attachments/assets/9b847f41-5af8-4285-bdec-0d4e218adc6b)

个人觉得图片支持超链接还是有意义的，毕竟文献、微信公众号对图片添加超链接是很常见的操作

**Comment by 88250** [comment]
语法树结构不支持，目前不考虑改动了。

**Comment by Achuan-2** [comment]
写了一个js代码片段
```js
    const imgSpans = document.querySelectorAll('span.img');

    imgSpans.forEach(imgSpan => {
        // 找到 imgSpan 后面的兄弟节点
        const nextSibling = imgSpan.nextElementSibling;

        // 检查是否是 span.a 节点
        if (nextSibling && nextSibling.dataset.type === 'a') {
            // 隐藏 span.a 节点
            nextSibling.style.display = 'none';

            // 创建新的 span.img__net 节点
            const imgNetSpan = document.createElement('span');
            imgNetSpan.className = 'img__net';

            // 使用 innerHTML 添加 SVG
            imgNetSpan.innerHTML = `
                <svg>
                    <use xlink:href="#iconRight"></use>
                </svg>
            `;

            // 设置 imgNetSpan 的点击事件，跳转到 span.a 的链接
            imgNetSpan.addEventListener('click', function() {
                window.open(nextSibling.dataset.href, '_blank');
            });

            // 找到 span.img 的第二个 span
            const innerSpans = imgSpan.querySelectorAll('span');
            if (innerSpans.length > 1) {
                innerSpans[1].appendChild(imgNetSpan);
            }
        }
    });
```
![PixPin_2024-10-12_17-53-23](https://github.com/user-attachments/assets/4cf173a4-a94a-4ffc-9693-7f591933012b)

**Comment by Achuan-2** [comment]
写了一个插件https://github.com/Achuan-2/siyuan-plugin-imgAddLink
自己先用着
