### ISSUE TITLE
清理云端存储 S3 获取列表失败

### ISSUE THREAD

**Issue by wwxiaoqi** [siyuan-note/siyuan#12752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

配置如图：
![5f879b2d58daccf81bd5e28e06b345ca](https://github.com/user-attachments/assets/c569e1d0-200c-41b6-85c5-87d95b55873d)

当我使用【清理云端存储】功能时候会出现提示：
![93fb708bc232d20cda35b50cb464c8f5](https://github.com/user-attachments/assets/d8d4d20e-859f-4ee9-b91c-340ca9302d2d)

```
list objects failed: NoSuchKey: The specified key does not exist.
列表对象失败: NoSuchKey: 指定的键不存在
```

### Expected result

正常清理.

### Version environment

```markdown
- Version: v3.1.8
- Operating System: Windows 11 23h2
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/user-attachments/files/17340521/system-log.1.zip)

**Comment by FancyBEAST** [comment]
@wwxiaoqi did you figure out the problem?

**Comment by wwxiaoqi** [comment]
@FancyBEAST 
I believe the issue is due to the difference between Path Style URL and Virtual-Hosted Style URL.

<details><summary>Path Style</summary>

In a Path Style URL, the bucket name follows the domain and becomes part of the URL path.

```
http://s3endpoint/BUCKET
```

For example, if there is a photo.jpg stored in a bucket named images in the us-west-2 region, you can access it like this:

```
http://s3-us-west-2.amazonaws.com/images/photo.jpg
```

Here, both the bucket and key are part of the URL path: / {bucket} / {key}
</details>

<details><summary>Virtual-Hosted Style</summary>
In a Virtual-Hosted Style URL, the bucket name becomes a subdomain:

```
http://BUCKET.s3endpoint
```
For instance, if there is a photo.jpg stored in a bucket named images in the us-west-2 region, you can access it in this manner:

```
http://images.s3-us-west-2.amazonaws.com/photo.jpg
```

In this case, the bucket is inferred from the host part of the URL.

</details>

------------------

If you have set up the Path-style mode and encounter an issue with the ‘Clear Cloud Storage’ function where the request path is missing the bucket, this could be the root cause of the problem.

Without extensive testing, I have emptied my S3 OSS contents and switched to the Path Style URL mode, and everything is functioning well now

It’s worth noting that Siyuan seems to default to appending the bucket string for Path Style URLs. If you encounter this problem:

![image](https://github.com/user-attachments/assets/2c3eadcf-837d-4be4-99c2-7d9d589183d0)

You need to remove the bucket from the Endpoint settings to make it work properly.

```diff
- http://images.s3-us-west-2.amazonaws.com/
+ http://s3-us-west-2.amazonaws.com/
```
