### ISSUE TITLE
思源笔记本地离线部署中的音频录制问题

### ISSUE THREAD

**Issue by QIN2DIM** [siyuan-note/siyuan#12758]
## 环境说明

- 使用 Docker Compose 在本地离线部署思源笔记
- 容器服务来源：[b3log/siyuan](https://ld246.com/forward?goto=https%3A%2F%2Fhub.docker.com%2Fr%2Fb3log%2Fsiyuan)
- 通过浏览器访问思源笔记

## 问题描述

在使用思源笔记的音频录制功能时，遇到了以下两个问题：

### 问题 1：音频录制的网络传输流程

在任一笔记页面开启录音功能，录制音频并点击 结束录制 后，直到 AudioBlock 出现在笔记页面并能正常播放，这个过程中具体存在怎样的网络传输流程？

### 问题 2：大文件录音保存失败

在一个特殊场景下，录制了一段较长时间的音频（预估文件大小可能超过 2 GiB）。在结束录制后，将音频保存到容器的 workspace 时出现了网络传输异常，思源笔记随即弹出了相应的错误提示。

#### 关于这个问题，我有以下疑问：

1. 思源笔记调用浏览器的录音 API 后，点击 结束录制 时，音频文件是否会先写入本地磁盘，还是直接从内存通过网络传输到目标容器？
2. 由于网络传输中断，目标容器的思源笔记 workspace 中未发现该音频文件。那么，在运行浏览器的 PC 上，是否存在一份完整未损坏的音频文件缓存？（注意：期间未刷新页面或关闭笔记标签，且已手动点击结束录制）

## 期望得到的帮助

1. 思源笔记在录音结束后的数据处理流程。
2. 提供可能的数据恢复方法或建议，以尝试找回中断传输的音频文件。
3. 针对大文件音频录制，有无优化建议以提高传输成功率

感谢协助！╰(*°▽°*)╯

**Comment by TCOTC** [comment]
> 针对大文件音频录制，有无优化建议以提高传输成功率

换成 mp3 大概好点 #11727

**Comment by 88250** [comment]
问题 1

请参考开发者工具中的网络页签

问题 2

1. 直接网络传输，本地不会有文件
2. 不会，对于长时间录音，建议还是用设备自带的录音软件，录完后再以资源文件的形式插入到笔记中

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
