### ISSUE TITLE
改进标签、改进剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12764]
导入这个文档：[LaTeX公式手册(全网最全) - 樱花赞 - 博客园.sy.zip](https://github.com/user-attachments/files/17354765/LaTeX.-.-.sy.zip)，会出现很多标签：

p.s. 用户是剪藏之后出现这个问题的，但我剪藏复现不了，导入文档才能复现。
p.s.s. 我觉得需要排除代码、公式、嵌入块之类东西里的 `#foo#`。

![image](https://github.com/user-attachments/assets/ba6e6871-734d-4908-99b5-2e078b728e48)

剪藏 https://www.cnblogs.com/1024th/p/11623258.html ：

![image](https://github.com/user-attachments/assets/b96daf61-5358-44dd-bddc-739c63e8d1d8)

![image](https://github.com/user-attachments/assets/b20a2713-b2a1-46f0-a152-2354d114b410)

![image](https://github.com/user-attachments/assets/29f5424b-3e9f-4009-81ad-91691094880c)

![image](https://github.com/user-attachments/assets/ab9d70b1-d7a5-4c59-aaf2-8bb184643677)

![image](https://github.com/user-attachments/assets/62b678a4-97fc-480b-9f70-3a85c3a6aca6)

![image](https://github.com/user-attachments/assets/f1787e38-008f-429e-abfc-057d61327158)

**Comment by 88250** [comment]
标签搜索改进不了，剪藏稍后改进。

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/12677

**Comment by TCOTC** [comment]
那为啥我自己剪藏的没有标签，导入那个文档又有标签？

**Comment by 88250** [comment]
我用的是剪藏后测试的

**Comment by TCOTC** [comment]
想明白了，应该是开启了 `Markdown 行级标签语法` 之后剪藏，然后有些公式剪藏成了段落块所以里面就形成了标签。

所以只要解决公式剪藏的问题就能解决出现多余标签的问题了。
