### ISSUE TITLE
dock图标和窗口 布局方式 建议

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1276]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/105706950-2b639880-5f4d-11eb-8dc3-3ba8b217e602.png)

如图，这是旧版的思源UI，可以在侧边放置3个及以上，目前只能放置两个工具窗口
0.6.7后更加接近于idea和vscode的UI了，更加的简洁和优雅
但是希望能保留过去的**灵活和自由**，比如vscode侧边可以放置多个栏目，如下
![image](https://user-images.githubusercontent.com/46141646/105707302-af1d8500-5f4d-11eb-83b3-ff5237dafc58.png)

### 描述最优的解决方案 Describe the optimal solution

dock窗口希望保留过去拖放的自由和灵活，比如
* 拖放dock图标 到窗口 可以像过去一样预览和放置布局
* 拖放dock图标 在四周 可以移动dock图标位置

### 其他信息 Other information

使用新UI的时候，视觉印象的确是更好的，
比如：dock窗口去除了dock窗口名，节省了空间

但是使用体验感觉可能不太如过去。
比如：自由布局的便捷和自由不如之前

还有一点讨论：
观察idea和vscode可以发现，dock图标都在侧边
**这是因为顶层全是菜单，而dock工具窗口和菜单不是一类**，菜单放置顶部，dock工具放非顶部，作为区分
**而思源仅有 文件 这一个dock有菜单的感觉，也许把各个dock强行从顶部分散理由不足，且占用侧边空间**

保持现有默认布局的设计
再提供上述 拖放布局方案 的功能，一方面可以让用户直接体验 优秀编辑器建议的布局，同时也给用户 高度自定义布局的自由

**Comment by lss6378** [comment]
+1， VSC上的布局挺好的：
![窗口堆叠和布局拖动](https://user-images.githubusercontent.com/15924513/105710986-db87d000-5f52-11eb-8ba6-e0db5d93f29b.gif)

**Comment by kiritocode** [comment]
赞同！

大纲能拖来拖去太重要了。

而且最好能够开多个大纲页面，比如我在编辑 file2, 但是想参考 file1 的大纲，这个目前做不到，目前的大纲绑死在当前活动的tab上了。

**Comment by 88250** [comment]
@kiritocode 编辑器页签上右键打开文档大纲

**Comment by 88250** [comment]
@wo4wangle @lss6378 我们后面尽量参考，谢谢。
