### ISSUE TITLE
希望能给数据库新增一个富文本字段

### ISSUE THREAD

**Issue by iamlinkent** [siyuan-note/siyuan#12765]
### In what scenarios do you need this feature?

有时候需要给记录做些备注，纯文本字段无法满足

### Describe the optimal solution

希望能给数据库新增一个富文本字段

**Comment by TCOTC** [comment]
Duplicate of #11553

**Comment by iamlinkent** [comment]
> Duplicate of #11553

用你介绍的资源字段只能插入链接，这样一来链接字段反而变得多余了！我觉得要么在现有的文本字段新增格式化功能，要么新增一个富文本字段，备注记录时没有文本格式化实在是不方便

**Comment by TCOTC** [comment]
@iamlinkent 如果你想让链接字段可以同时放链接和文本，可以支持一下这个提案：#12690

**Comment by iamlinkent** [comment]
> @iamlinkent 如果你想让链接字段可以同时放链接和文本，可以支持一下这个提案：#12690

我看了你的提案，综合我说的场景，文本字段格式化功能或者富文本字段一本都会有插入锚链接，完美解决，而且很多场景都能用到。查了下论坛也有几个人很早前提过这个需求，作者说会考虑！不知道是因为作者否决这个需求，还是开发起来工作量太大
