### ISSUE TITLE
浮窗和反链面板的块标问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12760]
[视频.webm](https://github.com/user-attachments/assets/1a0eda88-2736-4ba4-a4e4-b39907994c71)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by TCOTC** [comment]
相关问题：https://ld246.com/article/1731154927823

**Comment by Vanessa219** [comment]
反链的好像重现不了。

**Comment by TCOTC** [comment]
能不能在鼠标离开对应的编辑器的时候才隐藏，感觉一滚动就隐藏的话很奇怪。

用浮窗打开文档的时候，滚动翻页之后鼠标要动一下才能看到块标，用起来跟打开页签的编辑器体验不一致。

**Comment by Vanessa219** [comment]
鼠标不离开编辑器也可以滚动的，这样解决不了问题。

**Comment by TCOTC** [comment]
哦对，我再想想
