### ISSUE TITLE
Shift + PageUp / PageDown 无法多选块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12769]
变成多选文本了：

[视频.webm](https://github.com/user-attachments/assets/3a171469-8b70-4b00-b898-fc6a64077be5)

**Comment by Vanessa219** [comment]
没有这两个快捷键，看上去是系统默认行为。

**Comment by TCOTC** [comment]
不是思源快捷键。以前一直是通过这样来快速扩选块的，现在不行了。

**Comment by TCOTC** [comment]
我感觉大概跟 Electron 有关，说不定变不回来了。

所以能不能增加“直接扩选到首个/末尾块”的功能，支持配置快捷键

**Comment by Vanessa219** [comment]
这个么？

![QQ_1728965086651](https://github.com/user-attachments/assets/322b8bde-0f11-43f6-b434-b104f68c9c78)

**Comment by TCOTC** [comment]
还真是，原来是我记错了
