### ISSUE TITLE
一直显示正在退出无法关闭页面

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#12761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

windows在点击关闭按钮同步完成后一直显示正在退出，可以进行设置页面等操作，只有重新加载页面才会关闭页面，不然会一直显示正在退出
之前手机上也出现过卡正在退出的情况，伺服后重置窗口布局就好了，后来在桌面端试过重置窗口好了一段时间后又不行了，关闭所有插件也还是会出现卡正在退出

### Expected result

可以正常退出软件关闭页面

### Version environment

```markdown
- Version: v3.1.9-dev7
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan2.log](https://github.com/user-attachments/files/17350092/siyuan2.log)

**Comment by 88250** [comment]
从日志上看是因为退出时需要同步数据，而此时又扫描到数据有变更，所以同步时间较长，建议点击退出后就不要再编辑数据了。
