### ISSUE TITLE
会开发自己的同步服务器吗？

### ISSUE THREAD

**Issue by libra1010** [siyuan-note/siyuan#12773]
### In what scenarios do you need this feature?

构建中心服务，同步直接同步至私有化部署的服务器。 而非重新搭建s3,或者购买S3

### Describe the optimal solution

构建中心服务，同步直接同步至私有化部署的服务器。 而非重新搭建s3,或者购买S3

**Comment by 88250** [comment]
购买 功能特性 以后也可以使用 S3/WebDAV 将数据存储到指定的存储服务中的。
