### ISSUE TITLE
搜索时删除块之后需要移除对应的搜索结果、撤回时需要再添加回来

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12770]
[视频.webm](https://github.com/user-attachments/assets/118a9e12-07c8-470f-b68b-39ef5edcae28)

**Comment by 88250** [comment]
这个不考虑了，搜索操作需要等索引建立，比较耗时。

**Comment by 88250** [comment]
没有办法处理，你有啥方案不？
