### ISSUE TITLE
Improve the experience of opening pages in the dock bar with Ctrl+R.

### ISSUE THREAD

**Issue by TangQi001** [siyuan-note/siyuan#12778]
### In what scenarios do you need this feature?

------------------------------------------Chinese-----------------------------------------------------------
### 问题来源
为了界面的美观性，我将dock栏全部隐藏了
![image](https://github.com/user-attachments/assets/a241a7d9-cffb-4923-afc1-f2aceb01f642)
但是，这也就出现一个问题，我如何打开我需要的在dock栏上的页面呢，比如书签，knote页面，插件页面？
### 问题描述
我使用了ctrl+R解决这一问题，需要插件页面时我就可以ctrl+R选择打开页面
![image](https://github.com/user-attachments/assets/05ba0ea1-bc02-4830-9f3b-096df537069b)
但是，当我打开页面比如AI-豆包之后，我如何关闭它呢？
我尝试重新ctrl+R，点击AI-豆包，发现页面并没有缩回去。
所以，我希望能增加一个在页面存在的情况下，ctrl+R的点击能够将页面收回

----------------------------------------------English----------------------------------------------
### Source of the problem
For the aesthetics of the interface, I have hidden the entire dock bar.
![image](https://github.com/user-attachments/assets/a241a7d9-cffb-4923-afc1-f2aceb01f642)
However, this also poses a problem. How can I open the pages on the dock bar that I need, such as bookmarks, knote pages, and plugin pages?
### Problem description
I have used ctrl+R to solve this problem. When I need the plugin page, I can select and open the page by pressing ctrl+R.
![image](https://github.com/user-attachments/assets/05ba0ea1-bc02-4830-9f3b-096df537069b)
But after I open a page such as AI-Doubao, how can I close it?
I tried pressing ctrl+R again and clicking on AI-Doubao, but found that the page did not retract.
Therefore, I hope to add a function that when the page exists, clicking ctrl+R can retract the page.

### Describe the optimal solution

增加一个二次点击收回页面的功能，或者在页面存在的情况下，点击能够收回页面

**Comment by 88250** [comment]
试试 Ctrl+W 关闭面板

**Comment by KuiyueRO** [comment]
侧栏的取消钉住也是一个不错的选择

![image](https://github.com/user-attachments/assets/0e278ffb-cca6-4a04-8e9e-8e9ea52aa4f1)

**Comment by TCOTC** [comment]
1. Ctrl+R 不是替换功能吗，你改成什么的快捷键了？
2. 你这图太糊了

**Comment by KuiyueRO** [comment]
看起来应该是 `最近的文档` 面板

**Comment by TCOTC** [comment]
等等，我好像懂了，你是想关闭侧栏弹出的面板是吗？

**Comment by 88250** [comment]
那关闭了啊。

**Comment by TCOTC** [comment]
我试了一下，在显示侧栏的情况下才关得了，先点击按钮再按 Ctrl+W

**Comment by TCOTC** [comment]
好像有个技巧，点一下插件自带的这个设置图标再按 Ctrl+W 就行了：

![image](https://github.com/user-attachments/assets/e66ce27f-8241-4576-9269-796f093e987e)
