### ISSUE TITLE
文件重命名提示非法字符，删除掉`.md`就能重命名，且引用内容丢失

### ISSUE THREAD

**Issue by BLACKT-T** [siyuan-note/siyuan#1277]
## 问题
新建文件的时候不需要填写`.md`后缀，只需要写上文件名即可，但是重命名时却有`.md`后缀，观感不一致
再就是我遇到的问题是重命名时我没有书写非法字符，，却提示我非法字符，例如文件名`NodeJS总结.md`不变化字符，点击修改文件却显示存在非法字符，只能直接叉掉。但是删除掉`.md`后缀即可修改成功，但是文件却不是md文件了，并且内容丢失了。

这是我遇到的问题
![图片](https://user-images.githubusercontent.com/37499441/105713941-ae3d2100-5f56-11eb-923f-b60340bc0fd1.png)

**Comment by 88250** [comment]
收到，v0.6.8 修复 https://github.com/siyuan-note/siyuan/issues/1271

**Comment by BLACKT-T** [comment]
\^_^/
