### ISSUE TITLE
工具栏应该始终显示在编辑器内

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12775]
向上飘的时候应该在页签下停住，而不是直接飞出去：

[视频.webm](https://github.com/user-attachments/assets/ab6490c9-df5a-4d71-b149-ca1e165368b9)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Vanessa219** [comment]
不拉进版本了。

**Comment by TCOTC** [comment]
我这里还是会飞出去：

[video.webm](https://github.com/user-attachments/assets/3c56a884-b708-4b59-912e-74d4811b5f57)
