### ISSUE TITLE
mac M2芯片14.2.1 系统   思源3.1.8导出pdf失败

### ISSUE THREAD

**Issue by fsy0718** [siyuan-note/siyuan#12772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

导出pdf失败
1. 如果包含本地图片时，导出失败，一直处理【正在导出，请稍等...】

### Expected result

导出成功

### Screenshot or screen recording presentation

<img width="850" alt="企业微信截图_7e609b4a-dfb8-49e6-b5cf-e44d2c1c5fd4" src="https://github.com/user-attachments/assets/4741a3b4-1f6f-4c6b-bd31-8e12cc42c464">

### Version environment

```markdown
- Version: 3.1.8
- Operating System: mac M2  14.2.1
- Browser (if used):
```

### Log file

W 2024/10/14 16:07:58 tree.go:220: block tree not found [id=20241014160756-zt9dn1v], stack: [    github.com/siyuan-note/siyuan/kernel/model.LoadTreeByBlockID({0x140015d4978, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/tree.go:218 +0x44
    github.com/siyuan-note/siyuan/kernel/model.getBlockAttrs({0x140015d4978, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:337 +0x34
    github.com/siyuan-note/siyuan/kernel/model.GetBlockAttrs({0x140015d4978, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:317 +0x68
    github.com/siyuan-note/siyuan/kernel/api.getBlockAttrs(0x14008ea8000)
    	/Users/Vanessa/Work/Code/siyuan/kernel/api/attr.go:68 +0x124
]
W 2024/10/14 16:07:58 tree.go:220: block tree not found [id=20241014160756-7ovq1ua], stack: [    github.com/siyuan-note/siyuan/kernel/model.LoadTreeByBlockID({0x140015d4a08, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/tree.go:218 +0x44
    github.com/siyuan-note/siyuan/kernel/model.getBlockAttrs({0x140015d4a08, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:337 +0x34
    github.com/siyuan-note/siyuan/kernel/model.GetBlockAttrs({0x140015d4a08, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:317 +0x68
    github.com/siyuan-note/siyuan/kernel/api.getBlockAttrs(0x14001eda300)
    	/Users/Vanessa/Work/Code/siyuan/kernel/api/attr.go:68 +0x124
]
W 2024/10/14 16:07:58 tree.go:220: block tree not found [id=20241014160756-svrdwxr], stack: [    github.com/siyuan-note/siyuan/kernel/model.LoadTreeByBlockID({0x140015d4a98, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/tree.go:218 +0x44
    github.com/siyuan-note/siyuan/kernel/model.getBlockAttrs({0x140015d4a98, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:337 +0x34
    github.com/siyuan-note/siyuan/kernel/model.GetBlockAttrs({0x140015d4a98, 0x16})
    	/Users/Vanessa/Work/Code/siyuan/kernel/model/blockial.go:317 +0x68
    github.com/siyuan-note/siyuan/kernel/api.getBlockAttrs(0x14004148000)
    	/Users/Vanessa/Work/Code/siyuan/kernel/api/attr.go:68 +0x124
]

**Comment by 88250** [comment]
请安装最新 dev 版后测试看看。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:

**Comment by fsy0718** [comment]
已正常，但体感比之前版本卡顿
