### ISSUE TITLE
支持设置某个块不导出

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12788]
### In what scenarios do you need this feature?

想自己写一个脚注插件，用文档内块引实现脚注，具体见https://github.com/siyuan-note/siyuan/issues/11247
导出文章的时候，需要把文档里被块引的脚注给屏蔽，用思源自己生成的脚注
因此希望思源能提供一个功能，可以设置某个块不导出
这在其他输出场景也能用到，比如我写一篇博客，我可以在段落后面批注自己的想法和待办，但是分享出去的时候不导出

### Describe the optimal solution

通过自定义属性设置某个块不导出
比如custom-export=false

### Describe the candidate solution

无

**Comment by TCOTC** [comment]
如果思源提供导出各种文件的接口的话，通过插件调用时应该就能自行处理一些特殊的块

**Comment by 88250** [comment]
这个不考虑了，感谢反馈。

**Comment by Achuan-2** [comment]
![PixPin_2024-10-15_15-57-08](https://github.com/user-attachments/assets/d5315184-07d5-4a08-a36d-214d7057dd5d)
好吧，那我就把脚注统一都放在一个文档里
