### ISSUE TITLE
Unable to open PDF

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12794]
PDF 无法打开

- 无法在新窗口打开：https://ld246.com/article/1728978737254
- 无法打开：https://ld246.com/article/1729005355179

**Comment by Vanessa219** [comment]
第二个你可以重现么？

**Comment by TCOTC** [comment]
我这重现不了

**Comment by 88250** [comment]
我已经在 https://ld246.com/article/1729005355179 中反馈需要 PDF 文件了，等有人发送 PDF 的话我们测试看看，这个 issue 先关闭。

**Comment by InfinityMachine** [comment]
遇到了同样的问题，更新之后 pdf 就打不开了，微软商店 v3.1.9 版本。

**Comment by 88250** [comment]
@InfinityMachine 麻烦发一下无法打开的 PDF 以便我们测试。

**Comment by InfinityMachine** [comment]
[https://res.public.onecdn.static.microsoft/assets/mail/file-icon/png/pdf_16x16.png]数据库系统概论(第五版).pdf<https://1drv.ms/b/s!Aq87o8Ok7BvJg5cQcQfqv15sbcnJHw>

这是我无法正常打开的 pdf 之一。
________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 16:09
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


@InfinityMachine<https://github.com/InfinityMachine> 麻烦发一下无法打开的 PDF 以便我们测试。

―

**Comment by 88250** [comment]
@InfinityMachine 我这里测试可以打开的，请排查一下是不是插件或者代码片段影响。

**Comment by InfinityMachine** [comment]
禁用全部插件后依然无法打开，在新文档中插入 pdf 之后依然无法打开。

________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 16:16
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


@InfinityMachine<https://github.com/InfinityMachine> 我这里测试可以打开的，请排查一下是不是插件或者代码片段影响。

―

**Comment by 88250** [comment]
试试在新工作空间中测试

**Comment by 88250** [comment]
打开开发者工具 Network 看下点击以后的请求，我录了个屏参考：

[issue.webm](https://github.com/user-attachments/assets/82c26f04-c763-4aa0-8456-8174f74828c4)

**Comment by InfinityMachine** [comment]
[cid:c06e768f-9241-4c30-adc0-ba7a9cf0fc25]
________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 16:26
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


打开开发者工具 Network 看下点击以后的请求，我录了个屏参考：

issue.webm<https://github.com/user-attachments/assets/82c26f04-c763-4aa0-8456-8174f74828c4>

―

**Comment by 88250** [comment]
@InfinityMachine 我这里看不到你发的内容：

![image](https://github.com/user-attachments/assets/40ac0fed-47d6-48e8-a708-2ca81de00b86)

**Comment by InfinityMachine** [comment]
现在能看到了吗？
________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 16:33
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


@InfinityMachine<https://github.com/InfinityMachine> 我这里看不到你发的内容：

image.png (view on web)<https://github.com/user-attachments/assets/40ac0fed-47d6-48e8-a708-2ca81de00b86>

―

**Comment by 88250** [comment]
@InfinityMachine 

![image](https://github.com/user-attachments/assets/99fe8480-008a-4368-90e9-94813784750b)

**Comment by InfinityMachine** [comment]
<https://1drv.ms/i/s!Aq87o8Ok7BvJg5cXonYx7J_GDnmo1A>
[https://sjc04pap002files.storage.live.com/y4mDsbEQh5yWvjdBm01WQtciM375nnZ_j7b93tu2jFU_wFXbaaJEZQjqlKOHJM_vk-F1kCjCeHhgCjoBR-mSChIZy7qNwjZ9pdKpr08GFtWaL2sO_KtpfOP96lIkw8bxGSUsTVyisvjcDSJ9wkwBjyld0sLf0Rf9O5m7qpuMz7-_99v5g2nCkkwKWZEv_-YXT2c?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]image.png

这一次呢？
________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 16:37
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


@InfinityMachine<https://github.com/InfinityMachine>

image.png (view on web)<https://github.com/user-attachments/assets/99fe8480-008a-4368-90e9-94813784750b>

―

**Comment by InfinityMachine** [comment]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/d7e32d6d-6cf0-40b9-8ca6-66abefaa054a">

**Comment by 88250** [comment]
最后这一条可以看到图片了，这个问题我们排查下看看，感谢。

**Comment by InfinityMachine** [comment]
> 最后这一条可以看到图片了，这个问题我们排查下看看，感谢。

好的麻烦你们了。

**Comment by InfinityMachine** [comment]
> 最后这一条可以看到图片了，这个问题我们排查下看看，感谢。

发现如果通过电子邮件回复是没有办法成功传送文件或者图片的，需要在 github 这边来传送图片。

**Comment by 88250** [comment]
嗯，估计是的。

**Comment by 88250** [comment]
@InfinityMachine PDF 超链接链接指定了页码吗？

**Comment by InfinityMachine** [comment]
> @InfinityMachine PDF 超链接指定了页码吗？

无论是否通过指定页码的超链接去打开 pdf，都无法成功打开。

**Comment by 88250** [comment]
能否录个屏看下操作，从插入 PDF 文件开始，需要在新工作空间中录屏。

**Comment by InfinityMachine** [comment]
> 能否录个屏看下操作，从插入 PDF 文件开始，需要在新工作空间中录屏。
以下是录屏。
https://1drv.ms/v/s!Aq87o8Ok7BvJg5cj6dqWKDMp4MdaLA?e=eUGdbu

**Comment by 88250** [comment]
开发者工具里面禁用缓存，然后 Ctrl+R 刷新后再试试

**Comment by InfinityMachine** [comment]
> 开发者工具里面禁用缓存，然后 Ctrl+R 刷新后再试试

![image](https://github.com/user-attachments/assets/c949bf13-398d-4112-a7fc-c612e363c9ba)

**Comment by 88250** [comment]
打开定位到问题了，是 .mjs 没有被识别为 js，稍后我们改进下会发布一个 dev 版，麻烦发布以后帮助测试并反馈一下测试结果，谢谢。

**Comment by InfinityMachine** [comment]
> 打开定位到问题了，是 .mjs 没有被识别为 js，稍后我们改进下会发布一个 dev 版，麻烦发布以后帮助测试并反馈一下测试结果，谢谢。

好的，辛苦了。感谢。

**Comment by 88250** [comment]
@InfinityMachine 开发版已经发布，麻烦抽空测试。

**Comment by InfinityMachine** [comment]
微软商店并没有显示更新。。

________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 18:02
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


@InfinityMachine<https://github.com/InfinityMachine> 开发版已经发布，麻烦抽空测试。

―

**Comment by 88250** [comment]
@InfinityMachine 得手动下载安装版

**Comment by InfinityMachine** [comment]
好的，已经下载了

________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 18:14
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


@InfinityMachine<https://github.com/InfinityMachine> 得手动下载安装版

―

**Comment by InfinityMachine** [comment]
好的，经过测试问题已经被修复啦，非常感谢。
________________________________
发件人: D ***@***.***>
发送时间: 2024年10月17日 18:14
收件人: siyuan-note/siyuan ***@***.***>
抄送: CaoBoyu ***@***.***>; Mention ***@***.***>
主题: Re: [siyuan-note/siyuan] Unable to open PDF (Issue #12794)


@InfinityMachine<https://github.com/InfinityMachine> 得手动下载安装版

―

**Comment by 88250** [comment]
@InfinityMachine 多谢帮助
