### ISSUE TITLE
Drag and drop to insert asset fails

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#12791]
拖动文件到思源中功能失效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

看起来是 3.1.9 中，新出现的问题。将一个文件，拖到思源中，没有反应

### Expected result

希望修复

### Version environment

```markdown
- Version: 3.1.9
- Operating System: Win11
- Browser (if used): None
```

### Log file

无

**Comment by 88250** [comment]
使用菜单顶顶，稍后我们排查。

**Comment by TCOTC** [comment]
确实。会报错

![image](https://github.com/user-attachments/assets/9f827c87-158d-4c06-a5f0-c0ba584d60a3)
