### ISSUE TITLE
改进反向链接，支持「仅显示文档块的反链」

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#12796]
## 反向链接的可读性不高

【问题】
- 文档块的 **反向链接** 视图（例如 alt + b 打开），会将文档块中的内容块反链，也显示进去。

【影响】
- 降低了反链视图的可读性

【想法】
- 文档块反链就应该只显示文档块自身的反链。
- 显示内容块就有点奇怪，例如当使用静态锚文本时，就没办法看出这是该文档中哪一个内容块的引用了。

### Describe the optimal solution

**【目标】**
考虑到或许有人用到了这个设计，例如可以在设置里，提供一个可选项。
开启之后，文档块反向链接只显示对该文档块的反链，不再显示文档块中的那些内容块的反链。

**【可能有用的参考】**
目前想满足这种需求，依赖于思源插件集市内的「[反链过滤面板](https://github.com/Misuzu2027/syplugin-backlink-panel) 」插件，这是该插件的默认效果。
**我觉得这个功能官方应该具备，而不是依靠插件** 。
（ 该插件的作者： @Misuzu2027 ）

---

下图是上述插件的具体效果：
- 2024-10-16 页面，有3个反链结果，分别是 **文档块** 以及内部的 **2个内容块**
- 插件默认过滤掉了内容块，只显示 文档块 反链。但是结果数量无法同步显示（依旧是3个）

![image](https://github.com/user-attachments/assets/e58d88ed-9a58-42bc-9207-5345bd98467a)

该插件还提供了其他功能，都是挺实用的那种，一些同类笔记软件也具备这些功能。
有没有可能把该插件的一些功能，纳入官方正统？
- 例如实时过滤（输入过滤词实时显示结果，不用回车）
- 例如从反链列表里，过滤掉一些页面
- 例如其中的折叠按钮，不会影响原始位置的折叠状态。

**Comment by 88250** [comment]
这个设计不考虑改变了，如果有其他需求还是用插件吧，感谢反馈。

**Comment by cordinGH** [comment]
> 这个设计不考虑改变了，如果有其他需求还是用插件吧，感谢反馈。

是技术上存在困难吗？
我感觉文档块反链只显示文档块才是正解吧
