### ISSUE TITLE
通过 “剪切” 来移动 Block 时，Block id 会丢失

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#12795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

- 如下图的结构
![image](https://github.com/user-attachments/assets/a6af433a-9c27-403b-bfbf-c1623abd387a)

- 问题场景 —— 通过 剪切 来移动 Block
  - 当我点击 Block 001 的块标 - 打开菜单 - 剪切，然后去往目标页面中的目标位置，粘贴。
  会使得图中嵌入块直接丢失
![image](https://github.com/user-attachments/assets/0abb29de-c972-4e21-93b1-14889996a06c)

### Expected result

**期望结果：** 剪切粘贴 Block，应当维持 block id 不变。以解决图中的情况。

### Version environment

```markdown
- Version: 3.1.8
- Operating System: win11
- Browser (if used):
```

### Log file

[应该不需要日志文件.log](https://github.com/user-attachments/files/17385109/default.log)

**Comment by TCOTC** [comment]
剪切是会改变块ID的，想保留块ID得靠移动块

**Comment by 88250** [comment]
楼上正解，我关闭了，感谢反馈。

**Comment by 88250** [comment]
参考 https://github.com/siyuan-note/siyuan/issues/6807
