### ISSUE TITLE
Can't turn by the link to the note 

### ISSUE THREAD

**Issue by oswid** [siyuan-note/siyuan#1279]
### 描述问题 Describe the problem
With Russian language can't turn by link to the note by press Ctrl + Lmouse 
![error](https://user-images.githubusercontent.com/76834058/105723679-1cbeb680-5f38-11eb-9a06-b250067e0633.gif)

Current version v0.6.6 / Kernel v0.6.6

**Comment by lss6378** [comment]
遇到同样的问题，打开思源后，托盘无显示，且关闭不了
思源版本V0.7.0，

截图：
![无法关闭](https://user-images.githubusercontent.com/15924513/106272785-90303300-626c-11eb-9fef-004fd67b2553.gif)

关闭"点击关闭按钮后缩小到托盘中"配置，再关闭窗口，还有后台进程占用：
![图片](https://user-images.githubusercontent.com/15924513/106273221-3f6d0a00-626d-11eb-8412-6d8650e68e9f.png)


日志：
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5893686/siyuan.log)

**Comment by 88250** [comment]
@oswid Please update to v0.7.0 and try it again, thank you.

@lss6378 控制台报错的问题是因为没有登录帐号么？程序退出的问题一直定位不到，有点棘手。

**Comment by 88250** [comment]
@oswid Please update to v0.7.0 and try it again, thank you.

@lss6378 控制台报错的问题是因为没有登录帐号么？程序退出的问题一直定位不到，有点棘手。

**Comment by 88250** [comment]
@oswid Please update to v0.7.0 and try it again, thank you.

@lss6378 控制台报错的问题是因为没有登录帐号么？程序退出的问题一直定位不到，有点棘手。

**Comment by lss6378** [comment]
> 
> 
> @oswid Please update to v0.7.0 and try it again, thank you.
> 
> @lss6378 控制台报错的问题是因为没有登录帐号么？程序退出的问题一直定位不到，有点棘手。

尝试了下，账号登出后，控制台马上就出现报错
![图片](https://user-images.githubusercontent.com/15924513/106275253-7c86cb80-6270-11eb-869b-8c40acf8d6d4.png)

**Comment by 88250** [comment]
@lss6378 谢谢帮忙测试，稍后修复。

**Comment by oswid** [comment]
has no change 
![ZI8OQpzaI6](https://user-images.githubusercontent.com/76834058/106353742-d681a280-62fd-11eb-8cc0-78322196db7a.gif)

**Comment by oswid** [comment]
nothing has changed
![ZI8OQpzaI6](https://user-images.githubusercontent.com/76834058/106353914-fa91b380-62fe-11eb-80fd-2ed86ccc401d.gif)

![image](https://user-images.githubusercontent.com/76834058/106353935-20b75380-62ff-11eb-9943-8ab1d82559f0.png)

also have some problem with update to new version from 0.66, just uninstall v.066 and install 0.7 to find out bug has fix or not

**Comment by 88250** [comment]
After v1.0.0 the link jump has been changed to click directly, thank you.
