### ISSUE TITLE
华为安装app没有AI功能

### ISSUE THREAD

**Issue by danpianji** [siyuan-note/siyuan#12790]
### In what scenarios do you need this feature?

接入人工智能api
app是github这里下载的
模拟器中安装是有ai的
华为关闭了增强安全模式后手动安装的
这个和华为审查github链接没有关系吧,怎么通过特定方法把这个功能调出来呢,我需要接入deepseek

### Describe the optimal solution

怎么通过特定方法把这个功能调出来,因为模拟器中都可以,所有不知道为什么华为手机上屏蔽了

**Comment by 88250** [comment]
这个是受限于合规，所以无法添加，感谢反馈。

**Comment by danpianji** [comment]
可以通过自行编译的方式实现吗

**Comment by 88250** [comment]
试试搜索 集市

**Comment by 88250** [comment]
试试搜索 AI

**Comment by danpianji** [comment]
![001](https://github.com/user-attachments/assets/330d2a60-a278-453f-98ad-1778757e62d3)

如图操作只有内容,没有看到AI功能

**Comment by TCOTC** [comment]
华为手机上思源的工具栏有没有AI功能？

**Comment by danpianji** [comment]
> 华为手机上思源的工具栏有没有AI功能？

![18703efe18de7dada1354d8f72aad4e](https://github.com/user-attachments/assets/a98ba271-9fe5-4a0f-9ecb-d5d2a8594a49)
你是说这个工具栏吗,也没有

**Comment by TCOTC** [comment]
我指的是行内的和块菜单的：

![Screenshot_2024-10-15-18-51-27-74_ed1bdeca7a858bb430bfb9c256856672.jpg](https://github.com/user-attachments/assets/23580530-fcef-4083-aa87-981072922af7)

![Screenshot_2024-10-15-18-51-44-50_ed1bdeca7a858bb430bfb9c256856672.jpg](https://github.com/user-attachments/assets/b640b705-7204-4cda-83ff-0e497a50eb29)

**Comment by danpianji** [comment]
> 我指的是行内的和块菜单的：

这个会提示参考用户指南进行ai配置

**Comment by TCOTC** [comment]
那你伺服到桌面端看看能不能配置

**Comment by danpianji** [comment]
> 那你伺服到桌面端看看能不能配置

桌面端,web,模拟器 都有这个功能

**Comment by danpianji** [comment]
思源服务在群晖docker上

**Comment by TCOTC** [comment]
你问的不是华为的APP吗？手机伺服到桌面端行不行？

> 华为安装app没有AI功能

**Comment by TCOTC** [comment]
按理说伺服到桌面端配置完之后再手机上就能用了

**Comment by danpianji** [comment]
> 按理说伺服到桌面端配置完之后在手机上就能用了

手机开伺服,出现ai后我再改成群晖伺服,这样是吗,我试试

**Comment by TCOTC** [comment]
我没听明白跟群辉有啥关系？

**Comment by danpianji** [comment]
> 我没听明白跟群辉有啥关系？
> 
> 你在手机上是用网页打开思源的还是用APP？

app

**Comment by TCOTC** [comment]
我再重新描述一下，就是：

1. 在手机打开伺服功能
2. 在电脑或者手机浏览器的桌面模式打开伺服的链接
3. 在桌面版界面中打开设置里的 AI 去配置（不过不知道有没有这个选项，如果没有的话就输入AI搜索一下）
   ![image](https://github.com/user-attachments/assets/2984683a-2a02-413a-bfce-9ef98c2a30f5)

**Comment by danpianji** [comment]
这个ai配置是桌面端归桌面端,浏览器归浏览器,app上归app,不同的终端要重新配的

**Comment by TCOTC** [comment]
对的，配置手机的就要手机伺服打开桌面版网页去修改

**Comment by danpianji** [comment]
> 对的，配置手机的就要手机伺服打开桌面版网页去修改

太感谢你了,  可以了.   因为模拟器里面是可以直接在app上修改的,不知道可以伺服后改
