### ISSUE TITLE
The word count of the selected block is inaccurate

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12793]
选中块的字数统计不准确

[人工智能.sy.zip](https://github.com/user-attachments/files/17379694/sy.zip)

[视频.webm](https://github.com/user-attachments/assets/111ba043-75ad-43d9-96ce-5408491371ae)

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/pull/12723 引入的问题，稍后修复。
