### ISSUE TITLE
打开文档后直接关闭对应文档的未钉住浮窗

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12806]
![image](https://github.com/user-attachments/assets/4ba79c2b-db47-41dc-9245-c774c412ab89)

Ctrl+Click 反链文档图标之后不应该显示浮窗，弹出浮窗在这个场景下是多余的：

[视频.webm](https://github.com/user-attachments/assets/2b53e274-6af2-418c-8554-a63afa8752a0)

**Comment by Vanessa219** [comment]
为什么多余？

**Comment by TCOTC** [comment]
Ctrl+Click 的目的是打开文档，所以没必要再同时打开该文档的浮窗，一方面是干扰查看文档，另一方面是要手动关掉浮窗有点麻烦

**Comment by Vanessa219** [comment]
鼠标离开就会关闭了。如果移动上次可能表示需要继续查看其内容。

**Comment by TCOTC** [comment]
但浮窗就靠着鼠标打开，用户在实际使用的时候鼠标点击完就是会移上去的

**Comment by Vanessa219** [comment]
一般点完不动一下就消失了。这个就不改进了。

**Comment by TCOTC** [comment]
其他用户也觉得应该关闭浮窗：https://github.com/siyuan-note/siyuan/issues/12978#issuecomment-2449694314

> However, the floating window should close instantly as soon as the user clicks to open it in full-size mode.
