### ISSUE TITLE
多选块拖拽或拖拽折叠标题形成水平布局超级块时，这些块需要自动组成垂直布局超级块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12809]
跟 #10696 类似，目的是优化排版体验。

### 背景

看到视频 https://www.bilibili.com/video/BV19pmPY8Ezy?t=1794.0 里新手横排标题的操作之后我发现目前的逻辑还存在一点问题：

[视频.webm](https://github.com/user-attachments/assets/455708a9-9d76-4d61-beac-55b963ea6dda)

多选块拖拽或拖拽折叠标题形成水平布局超级块时，这些块应该需要自动组成垂直布局超级块

**Comment by Vanessa219** [comment]
增加了一点：多选或折叠标题拖拽到横向排列的超级块中。

**Comment by Vanessa219** [comment]
这个也支持的，上面说的是增加

**Comment by TCOTC** [comment]
跟折叠的标题块横排之后，另一个标题块及其子块也同样需要组成垂直布局：

[视频.webm](https://github.com/user-attachments/assets/ceff355a-10d8-4e8b-8d0d-b79d545a5bba)

**Comment by Achuan-2** [comment]
这个改的好👍
