### ISSUE TITLE
Can't assign key to keymap

### ISSUE THREAD

**Issue by oswid** [siyuan-note/siyuan#1280]
### 描述问题 Describe the problem
Can't assign to keymap Ctrl-Alt-Shift-F15
![2error](https://user-images.githubusercontent.com/76834058/105730408-5e9f2b00-5f3f-11eb-8e65-5273046b4544.gif)

version 0.66

**Comment by Vanessa219** [comment]
`ctrl+alt+shift+f1` is too complicated, you can use `ctrl+shift+f1` instead.
