### ISSUE TITLE
大纲锁定拖动建议

### ISSUE THREAD

**Issue by Jackie239** [siyuan-note/siyuan#12803]
### In what scenarios do you need this feature?

在看大纲的内容时，需要查看某个标题下的内容，这个时候左键点击标题跳转到指定位置会和拖动大纲标题调整文档结构产生歧义，经常勿触导致文档结构变化。

### Describe the optimal solution

在大纲里可以把拖动标题的功能锁定。

**Comment by TCOTC** [comment]
感觉支持禁用的话还是有点用的。

可以给大纲面板加一个更多菜单，#11533 也放进去。

**Comment by 88250** [comment]
这个不容易误触吧，不考虑加开关了，感谢反馈。
