### ISSUE TITLE
改进用户指南

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12811]
解决 #11998 的另一种方案。

```
在文档树面板的 <kbd>更多</kbd> 菜单中新建笔记本，在笔记本下新建文档
```

![image](https://github.com/user-attachments/assets/09a4f7ae-5ff6-4eb3-90b3-2273bc1adaf2)

**Comment by 88250** [comment]
欢迎 PR

**Comment by 5kyfkr** [comment]
用户指南我感觉能不能整个网页版本，这样修改更新也会更方便吧

**Comment by 88250** [comment]
@5kyfkr 不整了，没有资源维护。

**Comment by 88250** [comment]
我先关闭了，有空的话帮忙 PR 谢谢。

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/pull/12822
