### ISSUE TITLE
Improve database template field loading performance

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#12818]
特别是对于包含了绑定块的库有较大提升。

**Comment by TCOTC** [comment]
大概能提升多少？

**Comment by 88250** [comment]
好几倍吧，等 dev3 发布你试试看。

**Comment by 5kyfkr** [comment]
赶脚确实快了非常多，得劲

**Comment by TCOTC** [comment]
话说我的没有多少绑定块而且没用模板字段的数据库虽然只有60行15列，但开了Savor主题之后编辑一个单元格都得卡两秒。

感觉整个数据库块元素更新真的很影响性能。
