### ISSUE TITLE
Switch between notes by the finder 

### ISSUE THREAD

**Issue by oswid** [siyuan-note/siyuan#1281]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
Fast switcher between notes that search only by the name of files 
like this : 
![adds1](https://user-images.githubusercontent.com/76834058/105732852-f4d45080-5f41-11eb-847b-f0e78e38565b.gif)

does app have any community/socials  outside the China? Cant register here https://ld246.com

**Comment by deerainw** [comment]
Siyuan note considers 'doc'(or 'file') as a special form of 'block', you can search all 'blocks' in your notebooks above an updating-list after pressing the search shortcut `ctrl+p`. Files, as well as other kind of blocks, will be listed here.

You can also specify a specific type with a key, for example, `h:cat` returns all `heading blocks` that contains 'cat' in all notebooks, others are excluded. But, noteworthy in this context is that ‘doc’ has higher priority than any other kind of blocks in result list, so you can simply press `ctrl+p` and type file names to switch, there's no need to filter other types out. 😃

**Comment by oswid** [comment]
![image](https://user-images.githubusercontent.com/76834058/105742041-10dcef80-5f4c-11eb-88a3-fe7c22886ec7.png)
think you are right 😃
