### ISSUE TITLE
所有第三方插件在命令面板中注册的命令，回车都无法使用，只能鼠标点击

### ISSUE THREAD

**Issue by akkuman** [siyuan-note/siyuan#12816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

所有第三方插件在命令面板中注册的命令，回车都无法使用，只能鼠标点击
目前测试了
- 增强思源笔记
- 插入目录
- 文档上下文

### Expected result

按照命令面板的说明，应该回车/点击是相同的效果

### Screenshot or screen recording presentation

https://github.com/user-attachments/assets/ca212301-94ec-4752-8ec1-7e4f66e54ff8

### Version environment

```markdown
- Version: v3.1.8
- Operating System: Windows
- Browser (if used):
```

### Log file

应该不需要

**Comment by akkuman** [comment]
https://github.com/frostime/sy-doc-context/issues/1

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
