### ISSUE TITLE
选中并粘贴图片，无法替换掉选中的部分 BUG

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1282]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/105734859-0a5f6f80-5f6e-11eb-858a-b3ddd1322768.mp4

如视频，选中文字后粘贴图片，选中的文字依然存在
选中并粘贴文字是可以替换的

### 期待的结果 Expected result

选中的文字被替换

**Comment by 88250** [comment]
你好，目前设计就是这样的，感谢反馈。
