### ISSUE TITLE
CSDN 复制粘贴不出图片

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12828]
关联帖子：https://ld246.com/article/1729153912089

网页：https://blog.csdn.net/Together_CZ/article/details/115494176

演示：

[视频.webm](https://github.com/user-attachments/assets/3152d30e-8abb-4b9b-85a3-e63f414b660b)

**Comment by 88250** [comment]
我这里测试登录后可以正常复制粘贴（不使用思源剪藏扩展或者其他扩展的情况下）。
