### ISSUE TITLE
Outline and bookmark supports displaying images

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12820]
大纲无法显示自定义表情

![image](https://github.com/user-attachments/assets/28fb404f-b5dd-474a-b640-214465d808d1)

https://ld246.com/article/1729213426374/comment/1729214160264#comments

**Comment by 88250** [comment]
目前只要是图片都不支持显示，稍后调整为支持显示图片（包括了自定义表情）。

**Comment by TCOTC** [comment]
### 01 如果标题块包含图片，大纲无法显示

我试了一下，如果标题块有自定义表情的话可以在大纲显示，如果标题块里插入了图片的话这个文档的大纲就一个标题都不显示了

### 02 在标题块内无法通过 `:foo` 搜索表情

不会弹出表情选择浮窗

**Comment by 88250** [comment]
@Vanessa219 抽空看看

**Comment by 88250** [comment]
@TCOTC 02 我和 V 正常：

![image](https://github.com/user-attachments/assets/a85b40e2-4de7-4e92-b430-a3d8c7d05291)

**Comment by TCOTC** [comment]
1. 如果前面有字符，按 `foo` 无法搜索表情
2. 在只有自定义表情的标题前按两次 Backspace 会删除该自定义表情，而不是把自定义表情移到上一行末尾
3. 会伴随出现异常的块

录屏：

[视频.webm](https://github.com/user-attachments/assets/e17fc28d-fd4f-45d6-b37e-17c121fb9351)
