### ISSUE TITLE
表格中有公式时出现垂直滚动条

### ISSUE THREAD

**Issue by w-jin** [siyuan-note/siyuan#12829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当表格中有公式时，表格右端出现滚动条，且可以上下滚动一小段距离

markdown如下

```markdown
|  | 阻抗 | 导纳 |
| - | - | - |
| 电阻 | $Z_R=R \quad (\varphi_{Z}=0)$ | $Y_{G}=G=\dfrac{1}{R} \quad ( \varphi_{Y}=0 )$ |
| 电感 | $Z_{L}=j \omega L \quad ( \varphi_{z}=90^{\circ} )$ | $Y_{L}=-j \dfrac{1}{\omega L}  \quad ( \varphi_{z}=-90^{\circ} )$ |
| 电容 | $Z_{C}= -j \dfrac{1}{\omega C} \quad ( \varphi_{z}=-90^{\circ} )$ | $Y_{c}=j\omega C \quad (\varphi_{Y}=90^{\circ})$ |
```

效果如下

![image](https://github.com/user-attachments/assets/3e57b8ba-8f1d-4f40-8e0b-b012c4f2c156)

### Expected result

垂直方向上显示完整的表格，不显示滚动条，就像github显示的这样

|  | 阻抗 | 导纳 |
| - | - | - |
| 电阻 | $Z_R=R \quad (\varphi_{Z}=0)$ | $Y_{G}=G=\dfrac{1}{R} \quad ( \varphi_{Y}=0 )$ |
| 电感 | $Z_{L}=j \omega L \quad ( \varphi_{z}=90^{\circ} )$ | $Y_{L}=-j \dfrac{1}{\omega L}  \quad ( \varphi_{z}=-90^{\circ} )$ |
| 电容 | $Z_{C}= -j \dfrac{1}{\omega C} \quad ( \varphi_{z}=-90^{\circ} )$ | $Y_{c}=j\omega C \quad (\varphi_{Y}=90^{\circ})$ |

### Version environment

```markdown
- Version: 3.1.9
- Operating System: win11
- Browser (if used):
```

### Log file

无，应当可以直接复现

**Comment by TCOTC** [comment]
确实

**Comment by Vanessa219** [comment]
被数学公式撑高了，需要把字体设置小。目前还没找到其他方案。

**Comment by TCOTC** [comment]
用这个呢：

```css
.protyle-wysiwyg [data-node-id].table table {
    overflow: visible;
}
```

**Comment by Vanessa219** [comment]
表头固定有点问题，但不知道其他地方还有没有问题

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by 88250** [comment]
能用代码片段的话先用代码片段顶顶吧。
