### ISSUE TITLE
Paste code block without the ` symbol 复制代码粘贴到外部的时候不带 ` 符号 

### ISSUE THREAD

**Issue by mysteriousHerb** [siyuan-note/siyuan#12834]
### In what scenarios do you need this feature?

复制粘贴到终端的时候会带 `` 导致没法直接复制粘贴运行
我特指是inline code 哈

### Describe the optimal solution

如果检测为code block， 并且全选 那直接粘贴的时候不带`
或者加一个复制键在右上角

**Comment by TCOTC** [comment]
选中文本，右键，使用“复制纯文本”
