### ISSUE TITLE
WEBCLIPPER: Please insert save path for clipping...Bug

### ISSUE THREAD

**Issue by zzsimplezz** [siyuan-note/siyuan#12830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I tried siuyan webclipper before, it worked... Now I try it again , it seems not working anymore... Can somebody check if it is just me or new bugx

### Expected result

...

### Version environment

```markdown
- Version: 3.1.8
- Operating System: 
- Browser (if used):
```

### Log file

.

**Comment by TCOTC** [comment]
Please update SiYuan to v3.1.9 and try again, it may solve the problem.

**Comment by TCOTC** [comment]
You need to choose a save path:

![image](https://github.com/user-attachments/assets/535ae30c-fe2c-4d3d-836a-e2974e4e61ef)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
I'll close it now. If you have any questions, please continue to post. Thank you :pray:
