### ISSUE TITLE
导出笔记本为 .sy.zip 再导入之后文档结构不一致

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12831]
测试工作空间的导出Data：[测试空间-20241019003636.zip](https://github.com/user-attachments/files/17438360/-20241019003636.zip)

中间导出和导入的过程太长所以截掉了：

[视频.webm](https://github.com/user-attachments/assets/fc40eb67-b87a-4f76-868a-f5af18583f50)

关联 #12653 #12825

**Comment by 88250** [comment]
感谢反馈，稍后修复。

**Comment by TCOTC** [comment]
导出的时候后面的文档一直再变，但前面一直都是 [1/2082] ：

![image](https://github.com/user-attachments/assets/cb49cf82-539b-486b-9a29-28020ea2be82)

**Comment by 88250** [comment]
这个问题稍后修复，感谢反馈。
