### ISSUE TITLE
Community help

### ISSUE THREAD

**Issue by snowe2010** [siyuan-note/siyuan#12839]
### In what scenarios do you need this feature?

Sorry, I'm not sure where to post this. I've created an account on the LiuYun site, but I'm unable to post anything there as I don't have enough "Answer points". I don't think Twitter is an appropriate help forum, so I hoped there would be a GitHub Discussions page, but couldn't find one of those either. 

Adding some way to request help without having answered questions (how can I answer questions if hardly anyone is asking questions?) would be great. 

Anyway, I guess I'll just ask my question here, though this is not how I usually like to do things. 

I cannot find it documented anywhere how you save data within a widget or plugin? For example I have a very simple widget I've written:

```javascript
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Golarion Date Picker Widget</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.13/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f0f0f0;
            display: flex;
            justify-content: start;
            align-items: start;
            height: 100vh;
            margin: 0;
            font-family: 'Arial', sans-serif;
        }
        .custom-date-picker {
            background-color: white;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            width: 300px;
        }
        h2 {
            color: #333;
            margin-bottom: 20px;
            text-align: center;
        }
        #golarion-date {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 16px;
        }
        .flatpickr-calendar {
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1) !important;
        }
    </style>
</head>
<body>
    <div class="custom-date-picker">
        <input type="text" id="golarion-date" placeholder="Select a date" readonly>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.13/flatpickr.min.js"></script>
    <script>
        const golarionMonths = [
            { name: "Abadius", days: 31, season: "Winter" },
            { name: "Calistril", days: 28, season: "Winter" },
            { name: "Pharast", days: 31, season: "Spring" },
            { name: "Gozran", days: 30, season: "Spring" },
            { name: "Desnus", days: 31, season: "Spring" },
            { name: "Sarenith", days: 30, season: "Summer" },
            { name: "Erastus", days: 31, season: "Summer" },
            { name: "Arodus", days: 31, season: "Summer" },
            { name: "Rova", days: 30, season: "Fall" },
            { name: "Lamashan", days: 31, season: "Fall" },
            { name: "Neth", days: 30, season: "Fall" },
            { name: "Kuthona", days: 31, season: "Winter" }
        ];

        flatpickr("#golarion-date", {
            dateFormat: "d F Y",
            defaultDate: new Date(4707, 0, 1),
            monthSelectorType: "static",
            locale: {
                months: {
                    shorthand: golarionMonths.map(m => m.name),
                    longhand: golarionMonths.map(m => m.name)
                }
            }
        });
    </script>
</body>
</html>
```

but I do not know how to get this widget to actually save the selected date into the user's json/.sy files. 

I have looked through the documentation and didn't really find anything, but found this Issue where someone discusses grabbing IDs using some DOM methods, but it doesn't indicate how that translates to actually saving the data off. https://github.com/siyuan-note/siyuan/issues/5066

### Describe the optimal solution

A simple tutorial showing how to create a plugin and a widget, not just sample repos, but repos explaining what is happening. Also the sample widget just retrieves data using the query api, it doesn't use anything that would be 'writing', so it's hard to see how to use. 

### Describe the candidate solution

Ideally a single tutorial showing writing a value from a widget to a Document and then reading that value from the document to reinstantiate the widget when the document is opened.

**Comment by 88250** [comment]
Hello, we recommend using the kernel API to operate file access data https://github.com/siyuan-note/siyuan/blob/master/API.md#file

The file path can be placed in the /data/storage/{your-widget}/ folder.

I'll close it now. If you have any questions, please continue to post. Thank you :pray:

**Comment by snowe2010** [comment]
@88250 my issue here is that I do not understand _how to use_ the API. I can see all the methods, but through what mechanism do I actually get the parameters that go into those api calls? `getFile` takes a `path`. How do I get that `path`? How do I get the block that I need to update? Is the widget expected to update the entire file every time it's edited? or does it simply edit a block? How do I find what the id of the blocks are before and after my widget so that I can call the `prepend` or `append` blocks apis?

**Comment by 88250** [comment]
You can hard-code a path parameter, or specify it yourself according to the functional logic you need to complete. Other questions are similar, mainly depending on the function you need to complete.

**Comment by snowe2010** [comment]
I'm sorry, I think I'm not being clear here. The first step of any widget is knowing what data to use to make the calls to the API. I'm asking how to get that data. How do I retrieve the data I need? Let's say my widget is _just_ going to make a Block with the ID of the file. That's all it needs to do. 

Where do I get the ID of the file, and where do I get the ID of the blocks in order to insert a new one? I can't hardcode these as it makes the widget useless for any other files.

**Comment by 88250** [comment]
If you mean getting the current widget block ID, you can refer to this (in Chinese) https://github.com/siyuan-note/siyuan/issues/1488#issuecomment-883498078

But I'm not sure if this solution is still valid (if the DOM structure is inconsistent with this solution, the code needs to be slightly adjusted).

**Comment by snowe2010** [comment]
I think I just might not understand how the widgets are supposed to work. Where is a widget supposed to store data for a block? Like if I have a widget that is just a text box (for pretend), how do I save that data into the block data?

**Comment by 88250** [comment]
If the data is small, you can consider using the block attribute API to write it into the custom attributes of custom-xxx, but it is recommended to use the file API to store it separately.

**Comment by snowe2010** [comment]
I see. So you're saying I shouldn't even store it with the original file data, but in a completely separate file. The data is at most 20 characters, so not sure a whole file for that is worth it.

**Comment by gbcatrinoiu** [comment]
@snowe2010 I'm trying to create a small widget what will list all the files that contain a specific tag. Not sure if that is even possible, but as far as I understand right now it looks like a widget is what I need, but I don't understand how to consume the API. 

Did you manage to create a widget? Can you help me understand how to get started?

**Comment by snowe2010** [comment]
@gbcatrinoiu no, I decided to not write any plugin as how to do so wasn't documented. I've mostly switched to AnyType, even though I would have loved to keep using SiYuan. SiYuan is clearly very powerful, but I'm not really going to go digging into the internals, I just wanted to write a widget.
