### ISSUE TITLE
编辑链接时，增加一个粘贴选项

### ISSUE THREAD

**Issue by yxy823** [siyuan-note/siyuan#12832]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/d94ff2df-89f9-4964-bbb6-a44d04ef1aec)
现在编辑链接时可以直接复制链接，希望增加上一个粘贴选项
![image](https://github.com/user-attachments/assets/62bbae79-099c-47ea-8fd9-07ac64525f27)

### Describe the optimal solution

增加上一个粘贴选项

**Comment by TCOTC** [comment]
粘贴是低频操作，还是手动全选文本粘贴吧

**Comment by 88250** [comment]
我和 @Vanessa219 也认为这个是个低频操作，没有必要加按钮了，感谢反馈。
