### ISSUE TITLE
标签窗口 的数量显示

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1283]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/105740733-71802280-5f74-11eb-8f0b-cadedee85219.png)

如图，文件树的目录有文件数量的显示
比如这里我希望知道 TODO标签 的数量情况，根据数量我会选择是否处理TODO

### 描述最优的解决方案 Describe the optimal solution

标签窗口的标签也有数量显示，类似文件树的文件数量显示效果

**Comment by 88250** [comment]
v0.6.8 中进行实现，谢谢。

**Comment by SeyeeL** [comment]
@88250 请问标签窗口的数量显示实现了吗，我目前是 v1.4.2 好像没看到啊

**Comment by 88250** [comment]
@SeyeeL v1.2.0 以后我们重写了思源，目前的版本里面没有限制，页签过多下拉显示还在计划中，请看 https://github.com/siyuan-note/siyuan/issues/2098
