### ISSUE TITLE
出现了新问题，软件打开一直闪屏，用不了。本来可以用的不知道为什么突然这样子

### ISSUE THREAD

**Issue by whitea133** [siyuan-note/siyuan#12841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

软件一直闪屏

### Expected result

修复bug

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/bab91593-ba86-480d-b4a8-df2435700705)
![image](https://github.com/user-attachments/assets/259f436d-30ac-45c7-88a5-ac9fd7a6bb9f)

### Version environment

```markdown
- Version: 3.1.9（最新的测试版）
- Operating System: win11
- Browser (if used):无
```

### Log file

修复bug

### More information

闪屏频率太快了，截图完全看不清楚情况，反正就是上面的两张图片来回切换

**Comment by 88250** [comment]
我们这里目前无法重现该问题，请通过 Ctrl+Shift+I 打开开发者工具，切换到 Console 上录屏或者截图看下报错信息。

**Comment by whitea133** [comment]
软件上面按钮都点不了，就是那个click刷新的按钮都点不了，软件一直闪。根本用不了

**Comment by 88250** [comment]
用快捷键打开开发者工具

**Comment by 88250** [comment]
如果还是不行，试试删除 `C:\Users\用户名\.config\siyuan\workspace.json` 后再启动，这个情况下会让重新选择工作空间，选择一个新的空的工作空间测试看看。

我先关闭了，如果还有问题请随时跟帖，谢谢。

**Comment by whitea133** [comment]
Uploading VID_20241020_114012.mp4…

**Comment by whitea133** [comment]
https://github.com/user-attachments/assets/acf697b7-2d54-4177-93e2-34e84ae23d89

**Comment by 88250** [comment]
从录屏上看，这种情况多半是显卡驱动的问题，建议更新下显卡驱动后再试试。

**Comment by whitea133** [comment]
啊？但是这只是软件在闪屏啊？而且昨天是可以正常使用的，到了晚上7，8点我都还在做笔记，9点的时候不知道怎么就出问题了。今天重下了也没有用

**Comment by whitea133** [comment]
请问一下我如果下载回3.1.8版本的话，环境和文件那些的会不会有变动，如果没有的话，我先用回之前的版本了。

**Comment by 88250** [comment]
不会有问题的。

**Comment by whitea133** [comment]
那好，那我先用回之前的版本了，你们先修bug

**Comment by 88250** [comment]
这个问题我们这里重现不了，不是程序问题，可能是环境问题。

**Comment by whitea133** [comment]
刚才换了3.1.8版本，问题没了
![image](https://github.com/user-attachments/assets/b7477506-0d30-4d76-81a9-3f503c38a7e6)

**Comment by TCOTC** [comment]
遇到了相同的问题：https://github.com/siyuan-note/siyuan/issues/11931#issuecomment-2424205104

**Comment by 88250** [comment]
稍后我们确认下。
