### ISSUE TITLE
希望点击顶栏能隐藏打开的菜单或窗口

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12847]
目前需要点击顶栏下方的部分才能隐藏：

[视频.webm](https://github.com/user-attachments/assets/f970c9fb-cf34-491a-90d5-7839126f6867)

关联 https://ld246.com/article/1729336408893

**Comment by Vanessa219** [comment]
这里是用来拖拽整个窗口的，监听不到，可能是 Electron 的设置吧。
