### ISSUE TITLE
使用思源自己的下拉框样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12845]
这个下拉框在 Win11 是带圆角的感觉挺正常，但在 Win10 就是扁方形的感觉跟其他部件格格不入。

![image](https://github.com/user-attachments/assets/70e87b6f-b7df-4727-b11e-1a8a866125e7)

关联 https://ld246.com/article/1729336408893

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Vanessa219** [comment]
这个只改 css 好像不行，改动比较多，还是使用原生的吧。
