### ISSUE TITLE
改进一些弹窗的关闭按钮设计

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12843]
全部改成浮窗右上角的这种关闭按钮：

![image](https://github.com/user-attachments/assets/681782dd-f803-49d9-a2cc-bb81e494fdd7)

需要改进的例子：

![image](https://github.com/user-attachments/assets/263dcfc3-64a3-499a-b7bf-ef21d78b7af8)

![image](https://github.com/user-attachments/assets/bc98ec20-9a38-4217-a692-a5a03ce40409)

![image](https://github.com/user-attachments/assets/a3da8060-20e7-4b27-a628-aab57e090276)

参考这种样式：

![image](https://github.com/user-attachments/assets/997a1982-97e3-42db-a10c-3d0934d2b93c)

关联 https://ld246.com/article/1729336408893

**Comment by Achuan-2** [comment]
这个改动我觉得没必要吧，我挺喜欢这种关闭按钮设计的

**Comment by Vanessa219** [comment]
有取消按钮的应该可以不需要添加关闭按钮了，但设置这个弹窗加在右上角确实有点不太合适。

**Comment by Vanessa219** [comment]
这个还需要再讨论下，先不进行修改，设计主要参考 https://m3.material.io/components/dialogs/overview

**Comment by TCOTC** [comment]
> 在桌面端用 Material 3 感觉好丑

### [TDesign 对话框](https://tdesign.tencent.com/vue/components/dialog)：

![image](https://github.com/user-attachments/assets/c108f6d5-2607-4779-aa56-fcfe096c603a)

![image](https://github.com/user-attachments/assets/5889e530-d1e0-4d6b-b439-567d279e56d9)

**Comment by Vanessa219** [comment]
组件大部分都是参考的 Material，为了统一设计，目前会逐步更新到 3。

**Comment by TCOTC** [comment]
不要哇，Material 好丑

**Comment by Vanessa219** [comment]
你建议的 https://github.com/siyuan-note/siyuan/issues/12844 这个就是 M3 的设计。

**Comment by TCOTC** [comment]
开关按钮各家都是长那样的

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by wish5115** [comment]
我建议，退出按钮，删除按钮等危险操作用红色文字提醒下，包括手机端。

<img width="179" alt="image" src="https://github.com/user-attachments/assets/75529bc4-d38c-4f7e-9cc3-b29918e79714">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img width="168" valign="top" alt="image" src="https://github.com/user-attachments/assets/08d4284f-dedc-4e85-be33-7be0622388b8">

**Comment by TCOTC** [comment]
我觉得退出也可以变红，因为现在关闭窗口就是变红的：

![image](https://github.com/user-attachments/assets/6d2a3f3a-9b86-4751-8a68-c6b80d350fd8)

**Comment by wish5115** [comment]
楼上说的有道理，其实退出并非一点危险性没有的，比如，某些插件并非实时保存的，如果正在某些插件中操作，操作一半不小心点错了，或者我用开发者工具进行页面调试，调试到一半等场景，这些我都遇到过。

而且，手机端不是需要点退出才会同步吗？每次关闭时，都要找一下按钮有点累，我用css改成红色按钮后，每次快捷多了。

关于删除，我觉得提醒和确认是2个角度的问题，就像有些危险的地方，虽然有保安看惯，但也会给出非工作人员禁止入内等提示一样。再者，删除确认框并不是特别明显，有点像普通的确认框，按理说应该多加些危险的样式，让人一眼就能区分危险操作才对，否则，如果用户的操作本身就经常弹窗是可能看错而误删除。

**Comment by TCOTC** [comment]
转移到 https://github.com/siyuan-note/siyuan/issues/12919 继续讨论

**Comment by TCOTC** [comment]
我发现 ob 就是我想的这种设计：

![image](https://github.com/user-attachments/assets/4a45cd2c-bca1-4203-a957-8d71dab99893)

**Comment by Vanessa219** [comment]
什么设计?

**Comment by TCOTC** [comment]
就是前面提到的把关闭按钮都移到弹窗内，还有以前不知道在哪里提过的在设置里用小标题给功能分区

**Comment by Vanessa219** [comment]
这个好像有另外一个 issue， 这个 issue 说的不是这个。搜索页面咋整呢？

**Comment by TCOTC** [comment]
搜索界面直接把关闭按钮移到右上角就行。

不过我觉得应该[整体重新调整](https://github.com/siyuan-note/siyuan/issues/10794)，现在这个搜索界面一股子 IDE 的味道

**Comment by Vanessa219** [comment]
比 IDE 还 IDE ，为啥会需要这么多按钮和功能呀。
