### ISSUE TITLE
改进开关按钮样式设计

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12844]
![image](https://github.com/user-attachments/assets/ddbde794-23c8-45a0-9139-675c99a4e62a)

关联 https://ld246.com/article/1729336408893

**Comment by TCOTC** [comment]
关闭状态的颜色可以再深一点：

![image](https://github.com/user-attachments/assets/8059232b-c597-4126-a30d-d913e8cad37f)

参考 Chrome：

![image](https://github.com/user-attachments/assets/a11e3ab9-e7a6-457c-981b-5a1f9fd44688)

**Comment by 88250** [comment]
这个参考过的，但是蓝色不一样，深了不好看。

**Comment by TCOTC** [comment]
我说的是那个灰色的圆点

**Comment by Vanessa219** [comment]
这个试过了，和整体不搭配

**Comment by TCOTC** [comment]
@Vanessa219 用了一阵子我感觉还是再深一点点好看：

![image](https://github.com/user-attachments/assets/19675427-204b-46c9-abcd-658c5cab9225)
