### ISSUE TITLE
添加图片备注或批注样式有问题，操作非常不便利

### ISSUE THREAD

**Issue by liuxingar** [siyuan-note/siyuan#12840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

发现图片支持添加备注（不是块），但是操作方式还是和普通文本那样需要触发浮动工具条，而工具条的触发很困难。

https://github.com/user-attachments/assets/1ea04ddf-d316-4c16-8990-1312598d2ab1

### Expected result

期望效果类似下面视频，思源可以考虑添加到图片右键菜单中
https://github.com/user-attachments/assets/c44e85e3-ff8d-4fdb-b698-8a0e608166d9

### Version environment

```markdown
- Version: 3.1.9
- Operating System: Windows 10
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
你好，图片是不支持备注的，刷新以后备注就丢失了。稍后我们会改一下交互，彻底屏蔽掉浮动工具栏，感谢反馈。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
