### ISSUE TITLE
数据库的 .b3-chip 太圆了

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12858]
建议 .b3-chip 的 border-radius 属性用 var(--b3-border-radius)

border-radius:20px 太圆了感觉不好看：

![image](https://github.com/user-attachments/assets/ff935b3d-b2c6-4ccd-bb36-08746e35bb3b)

参考 Notion FlowUs Wolai：

![image](https://github.com/user-attachments/assets/bb383a30-0b71-42e5-96f5-eb8ffb58a38c)

![image](https://github.com/user-attachments/assets/7aad79a6-96c9-4242-9c61-1ae822e2d09b)

![image](https://github.com/user-attachments/assets/05f11ef1-fcdd-4d10-b989-55eaa0a91970)

**Comment by Vanessa219** [comment]
这个样式都进行统一的调整吧，就不单独针对数据库了。

**Comment by Temacc0531** [comment]
v3.1.10-dev6 看起来还是没有改到的样子，已经禁用缓存刷新
![1729492759768](https://github.com/user-attachments/assets/8dcecd87-8e82-43d3-8e56-5aa3f87c4179)

**Comment by TCOTC** [comment]
@Temacc0531 dev6还没改这个，等 dev7

**Comment by TCOTC** [comment]
@Vanessa219 我觉得用 var(--b3-border-radius) 更好一点，让这两个地方弧度一致：

![image](https://github.com/user-attachments/assets/9d5c6aff-bd84-4ce2-9009-68b0c13f2d98)
