### ISSUE TITLE
改进全局提示样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12859]
## 01

蓝色不好看，我觉得可以用白色或者灰色：

![image](https://github.com/user-attachments/assets/c31a4c80-9d93-49dd-a463-3fa61565ae35)

[TDesign](https://tdesign.tencent.com/vue/components/message)：

![image](https://github.com/user-attachments/assets/754111c3-42aa-4625-aa4e-1b603aa7c488)

## 02

移除最后的那个 √ ，然后在每条消息后添加一个 × ：

![image](https://github.com/user-attachments/assets/e3c4f17d-c49e-4944-ac19-bb8424df6373)

然后给每种全局提示添加一个 messageId 属性（直接用消息的序号），这样就可以通过 CSS 来隐藏特定的全局提示了 #11109

**Comment by Vanessa219** [comment]
自动消失的不会有关闭图标，全部已读不能移除，每条信息都有 id，这种消息显示不应该使用 css 来控制。

**Comment by TCOTC** [comment]
自动消失的目前也能点击关闭，所以加个关闭按钮也没问题。

用 CSS 应该更灵活。

**Comment by Vanessa219** [comment]
提示分为自动关闭的和手动关闭的，手动关闭的会加。
都知道加 CSS 的地方了，理论上直接不发送提示就可以了。

**Comment by KuiyueRO** [comment]
可以考虑把下面那个✓隐藏掉，那个✓不太明显，直接点击气泡就可以关闭。

**Comment by TCOTC** [comment]
感觉有点丑

![image](https://github.com/user-attachments/assets/1bd3a3ba-d479-492f-bf5f-99322117eaff)

**Comment by Temacc0531** [comment]
新版确实不大好看

**Comment by TCOTC** [comment]
@Vanessa219 在明亮模式下应该用白色的背景色

**Comment by Vanessa219** [comment]
先移除已读吧。tooltip 也是黑色的，就统一了。

**Comment by TCOTC** [comment]
> 自动消失的不会有关闭图标，全部已读不能移除，每条信息都有 id，这种消息显示不应该使用 css 来控制。

那个 data-id 是个随机的值，我指的 messageId 是这个：

![image](https://github.com/user-attachments/assets/30a76de7-7ebb-4145-81d4-04a8faca0ee6)

**Comment by Vanessa219** [comment]
哦，但这些用 css 确实不太适合。
