### ISSUE TITLE
拖入文件时指示插入位置

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12857]
比如拖入一个资源文件（链接），插入的位置可以显示一个光标；
比如拖入一个资源文件（块），插入的位置可以显示一条线。

目前是插入之后才知道会插入哪里：

[视频.webm](https://github.com/user-attachments/assets/894d8654-7247-404d-ace8-ade88be04fa4)

Notion 就会指示插入位置：

[视频.webm](https://github.com/user-attachments/assets/cd6daa67-78cc-44d5-86f2-4151ea908827)

**Comment by Vanessa219** [comment]
上传文件统一为显示光标插入点，横线就不考虑了。

**Comment by TCOTC** [comment]
> 横线就不考虑了

但是看起来会有点不对，光标的位置和文件插入的位置不同：

[视频.webm](https://github.com/user-attachments/assets/5cd983b3-0534-4d9c-83ac-e20af421b404)

**Comment by Vanessa219** [comment]
光标在文字中粘贴也是如此的，先保持一致。后面看看是否需要隔断为三个块之类的。

文档树和块标弄不出光标来 😭
