### ISSUE TITLE
图片标题支持换行

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12855]
### In what scenarios do you need this feature?

希望图片标题支持换行，目前不支持换行

### Describe the optimal solution

类似行内备注，存储的时候，换行存储为\n，再渲染为换行效果

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Achuan-2** [comment]
![PixPin_2024-10-27_14-51-26](https://github.com/user-attachments/assets/94cc91a8-df54-4bff-82c5-45606619b62f)
感觉有点问题，
输入换行标题后，有时候再打开图片标题的输入框就没有换行了
![PixPin_2024-10-27_14-52-02](https://github.com/user-attachments/assets/68a13942-efb2-45e7-8c41-dae14066784f)
