### ISSUE TITLE
改进搜索历史浮窗位置

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12856]
浮窗应该始终与输入框的下边界对齐，不遮挡输入框：（如果浮窗高度不够就减小浮窗的高度）

![image](https://github.com/user-attachments/assets/2a1f12db-9c39-45b8-9d51-aab12e259bd4)

目前某些情况下会高于输入框：

[视频.webm](https://github.com/user-attachments/assets/9bf000f2-7087-4139-a244-d3cd650ce6d1)

#12848

**Comment by Vanessa219** [comment]
只能调整一下高度，否则该情况就比较难以使用了。
![QQ_1729481138785](https://github.com/user-attachments/assets/437da2f4-b2d9-4bd6-9d67-c2125b126b06)
