### ISSUE TITLE
右键资源文件链接/图片，弹出菜单后默认全选锚文本/标题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12851]
链接不需要经常改，所以最好是默认全选锚文本/标题。

[视频.webm](https://github.com/user-attachments/assets/47da5d63-9df8-41ec-a21c-a7716fc9593c)

关联 https://ld246.com/article/1729429376698

> 目前右键链接时，如果链接合法就会全选锚文本，如果链接不合法就会全选链接，我感觉这个逻辑确实不错

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
