### ISSUE TITLE
滚动条拖到顶/底之后不再受控

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12853]
触发动态加载之后鼠标就控制不了滚动条了，需要重新拖动滚动条：

[视频.webm](https://github.com/user-attachments/assets/1408f63d-fb47-4c46-b009-5e968374165b)

希望能像这样保持滚动条始终可以操控：

[视频.webm](https://github.com/user-attachments/assets/bb3c7b34-6349-4bc3-8329-76f37888d2d2)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Vanessa219** [comment]
我们在加载的时候还会动态移除以前加载过的块。这样保持滚动条不变的话，文档位置就会不对了。目前看上去没有解决方案。
