### ISSUE TITLE
复制 assets 链接，选中文本粘贴/Ctrl+K之后自动填入链接

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12867]
目前还要再手动粘贴一下：

[视频.webm](https://github.com/user-attachments/assets/4349bb7c-d61a-47e3-9ae4-d697ff717561)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
