### ISSUE TITLE
Improv custom emojis at the beginning of the block

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#12868]
1. 如果前面有字符，按 `:foo` 无法搜索表情
2. 在只有自定义表情的标题前按两次 Backspace 会删除该自定义表情，而不是把自定义表情移到上一行末尾
3. 会伴随出现异常的块

录屏：

[视频.webm](https://github.com/user-attachments/assets/e17fc28d-fd4f-45d6-b37e-17c121fb9351)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/12820#issuecomment-2426174524_

**Comment by 88250** [comment]
@TCOTC 数字后面 : 不触发表情是个优化 https://github.com/siyuan-note/siyuan/issues/7052

**Comment by TCOTC** [comment]
Improv → Improve
