### ISSUE TITLE
希望改进字体外观设置逻辑

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12863]
### In what scenarios do you need this feature?

https://github.com/user-attachments/assets/e342150d-6a32-429d-b7ad-423454573de1

如视频所示，这个判断的逻辑有些奇怪，悬浮上去按字体外观的快捷键的时候，经常会改错

### Describe the optimal solution

![Clip_2024-10-21_12-02-54](https://github.com/user-attachments/assets/74121ba5-131e-4ee9-919f-28a23042000c)

希望改成在悬浮的时候按快捷键就能修改对应的块，有点表述不清楚了，大致就是这么个意思

**Comment by 88250** [comment]
选择的块会高亮的，如果没有高亮的话就是当前块。

**Comment by SaXz2** [comment]
问题是要点一下那个横杠才能变成高亮选定块，多了一步的操作，想改进成鼠标移动到那个块按快捷键就修改那个块的样式，感觉会更加高效

**Comment by 88250** [comment]
使用 Shift+↑ 扩选，然后 Ctrl+/

**Comment by SaXz2** [comment]
这个我知道，但我经常是用鼠标来操作块的，为了改字体样式我还得点一下就有些许的麻烦，如下方视频所示

https://github.com/user-attachments/assets/892c819a-0602-406f-9ab8-912eaa5d92bf

**Comment by TCOTC** [comment]
> 想改进成鼠标移动到那个块按快捷键就修改那个块的样式

选中块之后也能把鼠标移到其他块的块标上，会有冲突的。
