### ISSUE TITLE
浅色模式下光标为白色导致无法定位鼠标位置

### ISSUE THREAD

**Issue by Chen017** [siyuan-note/siyuan#12864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在文本界面,浅色模式时,光标会经常显示为白色导致与背景混淆无法定位光标, 只有当停留几秒不动后才会变成黑色

### Expected result

始终为黑色在浅色模式的时候

### Version environment

```markdown
- Version: 3.9.1(10.19 preview)
- Operating System: windows
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17454900/siyuan.log)

**Comment by TCOTC** [comment]
是不是 Win11+AMD？

**Comment by TCOTC** [comment]
是不是 Win11+AMD？

**Comment by Chen017** [comment]
yes

**Comment by TCOTC** [comment]
AMD 的问题，已经很久了

**Comment by Chen017** [comment]
崩  好吧

**Comment by TCOTC** [comment]
下一台电脑我再也不买 AMD 了 orz
