### ISSUE TITLE
这种块级交互有可能添加吗？翘望已久

### ISSUE THREAD

**Issue by muhanstudio** [siyuan-note/siyuan#12869]
### In what scenarios do you need this feature?

https://github.com/user-attachments/assets/2334a58c-5ca8-44a5-b59b-585c6db89ea9

这种块级交互有可能添加吗？翘望已久，是一个对应iPad和移动端很友好的交互

### Describe the optimal solution

capacities在他们的web移动端也有设计，目前有两种方案，长按和左右滑来进入选中状态

**Comment by muhanstudio** [comment]
另外再问一句，移动端和iPad端的优化会在什么时候开始，还远吗

**Comment by 88250** [comment]
> 另外再问一句，移动端和iPad端的优化会在什么时候开始，还远吗

今年可能希望不大了。
