### ISSUE TITLE
The backlink panel no longer displays child-block references

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#12861]
https://ld246.com/article/1729448933555

**Comment by 88250** [comment]
这个改变会影响到部分用户的使用习惯，所以还是只能加个开关：

设置 - 编辑器 - 反向链接包含子块
启用后子块将被纳入到反向链接计算中

**Comment by cordinGH** [comment]
有个小问题，当选择「不包含子块」后，文档树上的引用计数，没有生效
![image](https://github.com/user-attachments/assets/b0658a33-ce1e-4006-a7d7-78a6609ae5de)

**Comment by 88250** [comment]
@cordinGH 感谢反馈，后续改进。

**Comment by TCOTC** [comment]
能不能分开来做开关？如果引用计数不包含子块的话，一些情况就很难判断文档内容是否被引用了，容易误删。

**Comment by 88250** [comment]
你说的有一定道理，文档树这个还是默认包含子块吧，不做调整了，谢谢。
