### ISSUE TITLE
The backlink panel no longer displays breadcrumbs of the first-level blocks

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#12862]

**Comment by TCOTC** [comment]
我觉得还需要有什么东西分隔一下（分隔线、阴影之类的），否则看起来像是靠在一起的块：

![image](https://github.com/user-attachments/assets/45efb5dd-195b-4e6e-ba8c-08f8c8e41726)

**Comment by pureTrue** [comment]
![图片](https://github.com/user-attachments/assets/dbcff759-2b13-42ab-b712-d8ad692f215c)
如果可以的话，红框框选的，末尾的面包屑文字也给去掉呗

---
![图片](https://github.com/user-attachments/assets/36a263fb-199d-4223-85ff-56e56e3cbfce)
另外，浮窗的第一级面包屑，能否去掉目录层级结构，只保留页面名称？

原图：P.A.R.A./日记/2024/10/2024-10-21/水果
希望改成：水果

**Comment by 88250** [comment]
* 反链面包屑最后一层文字应该可以去掉
* 浮窗面包屑目录层级不能去掉，这个信息有用

**Comment by SaXz2** [comment]
这个我觉得可以交给css来处理，真要把最后一层去掉就没有这种特性了

https://github.com/user-attachments/assets/e8112936-0ec1-4fbd-8863-32c10bed4371

**Comment by 88250** [comment]
那要不还是改回去？ 这个还是用户自己用扩展（比如 CSS）方式去掉吧？

@pureTrue

**Comment by TCOTC** [comment]
我觉得能 CSS 隐藏就够了

**Comment by 88250** [comment]
不对，我们只是去掉了文字，并没有去掉块标，还是可以预览/跳转到目标块的，你再试试看？ @tcmtom

**Comment by SaXz2** [comment]
他说的应该是这种，只能跳转到文档块了
![Clip_2024-10-29_17-58-19](https://github.com/user-attachments/assets/28e624f4-6a4b-44c8-80fa-55861b150319)

**Comment by 88250** [comment]
我和 @Vanessa219 讨论一下

**Comment by 88250** [comment]
只有一层面包屑时还是要显示，只是去掉当前块文字，也就是这样：

![image](https://github.com/user-attachments/assets/95ebd4fc-caf5-4ea1-95ec-3da54717c49f)

**Comment by SaXz2** [comment]
建议改一下默认css样式吧，改成渐隐就行了，去掉字选区范围也小了，就剩块标那样了。

logseq只有一层的时候是去掉的，但是思源里面内容偏向长，最后一层字虽然没啥用，但是只留块标也很奇怪，改来改去感觉还是保留比较好，只需要把样式稍微改动一下隐藏最后一层

**Comment by TCOTC** [comment]
放一个面包屑图标在这真是丑不拉几的，作用也只有按住 Ctrl 点击打开文档，感觉不是常用的操作。

我建议把 Ctrl+Click 块标的作用改成打开文档，毕竟 Ctrl+Click 在反链面板里也不能聚焦。

![image](https://github.com/user-attachments/assets/7c408b59-1c6b-40d2-b374-c0826a0a9ec8)

**Comment by SaXz2** [comment]
这么改更好了，就剩个块标显示也丑不显示空一行也丑爆了

**Comment by 88250** [comment]
这样改的话改动有点大，先不考虑了，暂时先这样吧，等后面看看反馈。

**Comment by SaXz2** [comment]
要不发个投票帖吧，目前这样实在是丑爆了，强迫症看了表示非常难受

**Comment by 88250** [comment]
不考虑再加开关了……就和 反链包含子块 开关一致？

**Comment by TCOTC** [comment]
@88250 你是不是搞混 issue 了

**Comment by 88250** [comment]
呃呃，是搞混了。

面包屑的问题不动了啊。

**Comment by SaXz2** [comment]
> 不考虑再加开关了……就和 反链包含子块 开关一致？

目前需求：保留很丑，不保留最后一层面包屑反链面板不能跳转到对应位置，改动的话有点过于大刀阔斧

要不这样，做个判定只有一层面包屑，还是给删掉，但 Ctrl+左键 文档名跳转到对应位置，这样都能满足

**Comment by 88250** [comment]
> 但 Ctrl+左键 文档名跳转到对应位置，这样都能满足

多个的时候怎么处理？

**Comment by TCOTC** [comment]
@SaXz2 不是文档左边的图标，我提的是块标

**Comment by SaXz2** [comment]
> 多个的时候怎么处理？

是我欠考虑，有点头疼

**Comment by 88250** [comment]
这个改动大不考虑了。

**Comment by SaXz2** [comment]
> @SaXz2 不是文档名左边的图标，我提的是块标

那看来还是这种改动是最优解，改动有点大，等更新看反馈吧

**Comment by TCOTC** [comment]
Ctrl+点击 块标这个应该能改一下

**Comment by SaXz2** [comment]
主要无论 Logseq 还是 Roam 只有一层的情况下都是直接删掉跳转文档的，我觉得改块标是个好的改进，跳转和美观两不误，用起来还更方便了。

**Comment by 88250** [comment]
@Vanessa219 评估一下

**Comment by Vanessa219** [comment]
可以

**Comment by 88250** [comment]
好的，那就还是只有一层的时候不显示，块标可以点击跳转。

**Comment by TCOTC** [comment]
首个块上方不需要显示分隔线：

![image](https://github.com/user-attachments/assets/ceca1ff2-e285-440f-905e-d665e7414b77)

**Comment by SaXz2** [comment]
![Clip_2024-11-02_20-08-10](https://github.com/user-attachments/assets/e6dbb53f-3944-4996-9639-e7d992a0d991)
目前反链面板的面包屑还发现个问题，Logseq和Roam都是基于无序列表的面包屑比较统一，思源里面有标题有无序感觉添加标题的面包屑看着更直观一点，不然容易搞混，就如上图一样不够直观

**Comment by TCOTC** [comment]
有道理，其他类型的块也需要标题面包屑

**Comment by 88250** [comment]
> 首个块上方不需要显示分隔线：

我这里正常。

--- 

其他问题暂时不动了啊。

**Comment by SaXz2** [comment]
建议还是把标题面包屑整上，不然很多反链都成一种了，没法区分了
分割线那个问题我也存在，可以复现

发自我的iPhone


------------------ Original ------------------
From: D ***@***.***&gt;
Date: Sat,Nov 2,2024 11:41 PM
To: siyuan-note/siyuan ***@***.***&gt;
Cc: SaXz2 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [siyuan-note/siyuan] The backlink panel no longer displaysbreadcrumbs of the first-level blocks (Issue #12862)





  
首个块上方不需要显示分隔线：
  
我这里正常。
 
 
其他问题暂时不动了啊。

**Comment by TCOTC** [comment]
我这里很容易复现这条线

![image](https://github.com/user-attachments/assets/36db0d8a-eb8c-41f6-9e33-b68bbf35e060)

**Comment by 88250** [comment]
嗯，多条的时候我可以重现了 @Vanessa219

**Comment by cordinGH** [comment]
> ![Clip_2024-11-02_20-08-10](https://private-user-images.githubusercontent.com/52444119/382469802-e6dbb53f-3944-4996-9639-e7d992a0d991.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTA2NTcsIm5iZiI6MTczMDU5MDM1NywicGF0aCI6Ii81MjQ0NDExOS8zODI0Njk4MDItZTZkYmI1M2YtMzk0NC00OTk2LTk2MzktZTdkOTkyYTBkOTkxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDIzMzIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NDhiMjdhYjc5ZmJhMjNhMGUyYWE4Yzc5YzY2NDQ4MGU1NzY3N2I3YzZiYjI3ZTA0OWMxODc4NGE1OGIyYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9CcJZ5WWkBhjJ9rHfUC-HMJ3BT1V2e-c7tath-OtdiM) 目前反链面板的面包屑还发现个问题，Logseq和Roam都是基于无序列表的面包屑比较统一，思源里面有标题有无序感觉添加标题的面包屑看着更直观一点，不然容易搞混，就如上图一样不够直观，a和c都成一种了。
> 
> d的面包屑可以刷新出来这里补一张图是这样的 ![Clip_2024-11-02_20-13-41](https://private-user-images.githubusercontent.com/52444119/382470530-593c1334-777f-43c1-b1ed-fc6c18070dc1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTA2NTcsIm5iZiI6MTczMDU5MDM1NywicGF0aCI6Ii81MjQ0NDExOS8zODI0NzA1MzAtNTkzYzEzMzQtNzc3Zi00M2MxLWIxZWQtZmM2YzE4MDcwZGMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDIzMzIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNTU1ZWFhMjZiZGJhNTgwYmJiNWMzYmEzMzc0YWIwZjcxMWEyNDBlMjljNDBjMDdkMDNhMTA1NzY2MjQ4YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J3EceD_OTsNlMZmr6o1s5Acy4h9azMscD_R-ojBngQ4) 但是只有标题就没有面包屑了 ![Clip_2024-11-02_20-18-31](https://private-user-images.githubusercontent.com/52444119/382470842-25e13212-2ef9-4af0-9c60-b7f5de8b6f00.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTA2NTcsIm5iZiI6MTczMDU5MDM1NywicGF0aCI6Ii81MjQ0NDExOS8zODI0NzA4NDItMjVlMTMyMTItMmVmOS00YWYwLTljNjAtYjdmNWRlOGI2ZjAwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDIzMzIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYzJjZDRhZTNjZjE5ZmNhNTQ2MWNiNzY3MDgyMTRiNjNiYmQ2N2QxMzU4ZjZkNzRmODU1ODcyMTY4MWNkYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8Rlen-xZWNGmvoqYFKV3jwywFII6XEFajmYSQZWd7mM)
> 
> 链接在一级无序列表列表也是不显示的 ![Clip_2024-11-02_20-35-53](https://private-user-images.githubusercontent.com/52444119/382471912-ce79e700-9108-4bd7-96c8-5a3455139a82.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTA2NTcsIm5iZiI6MTczMDU5MDM1NywicGF0aCI6Ii81MjQ0NDExOS8zODI0NzE5MTItY2U3OWU3MDAtOTEwOC00YmQ3LTk2YzgtNWEzNDU1MTM5YTgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDIzMzIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NjU4MjQ0NTcwNzA1N2Y0NmVlMjdhYmRiMDkyNGZjNWI5YTllMTAxMTg1OWQxOGIwZTdjYmE1YmVkNThkZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dRLD64Ul59vecJ9L0CK_qW52LoGB3_3FSj1sddSRXFc)
> 
> 具体使用场景：不显示标题面包屑很难过滤具体内容 ![Clip_2024-11-02_20-26-15](https://private-user-images.githubusercontent.com/52444119/382471343-87953731-5573-4c52-b701-8c7e14ac64ae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1OTA2NTcsIm5iZiI6MTczMDU5MDM1NywicGF0aCI6Ii81MjQ0NDExOS8zODI0NzEzNDMtODc5NTM3MzEtNTU3My00YzUyLWI3MDEtOGM3ZTE0YWM2NGFlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDIzMzIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNGM2ZjJjYTUzOGQ2NmE1ZDc5YTA2MTI4YmNmYmIyYzQxN2ViMmNmNGFkYmM5YmQ1NjAxNTQzNmJmYmViOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jev6FeN_aXqSY07olP6uwg129TUpJaw_iLRAcrml7jI)

我也是从logseq迁过来的，我现在的想法是完全使用无序列表。标题也放在无序列表里，这样就有面包屑了。

但这种方式也存在一个问题，就是面包屑出现重复项。如下图 heading1。
![Screenshot_2024-11-03-07-37-10-103_org b3log siyuan](https://github.com/user-attachments/assets/4e75aa73-5d3a-4c03-aa39-4853920c42c7)

**Comment by SaXz2** [comment]
这个逻辑不好搞，标题是一个块，列表项也是一个块，讨论的优点远了，一会我单开一个issue讨论吧，把具体需求都明确列出来。

**Comment by cordinGH** [comment]
> 这个逻辑不好搞，标题是一个块，列表项也是一个块，讨论的有点远了，一会我单开一个issue讨论吧，把具体需求都明确列出来。

确实都是块，但是段落块也是块，列表项容器中的段落块是具备这种去重处理的。

**Comment by SaXz2** [comment]
https://github.com/siyuan-note/siyuan/issues/13008

**Comment by AvoidantPerDis** [comment]
作为从来是以思源为主软件的重度用户
![image](https://github.com/user-attachments/assets/f39cbe98-eb89-4a05-9884-d73a9a9445ca)
 新版的这次反链面包屑改动让我非常不习惯 
 我不清楚其他软件迁移过来的用户习惯如何 但是他们对思源的理解应该是没有那些已经付费和订阅老用户高的吧 
 社区也有人提出意见https://ld246.com/article/1730366536715/comment/1730385375808#comments
 如果要改动 要么让社区提前知情 要么让提供共存选项 
 思源为了拉新可以改变 但不能丢了根基 不然老用户流失只会更快

**Comment by TCOTC** [comment]
请等下一个版本再试试

**Comment by AvoidantPerDis** [comment]
> 请等下一个版本再试试

功能如何可以回退或者等到下一个版本 我只是感觉心有不忿 不吐不快

**Comment by SaXz2** [comment]
这个版本改动把之前的面包屑的跳转问题解决了，属于优化，应该能解决你的问题。并且在这个基础上优化了反链面板的内的排序逻辑和优化了面包屑，说实话算是加强了，社区吐槽的也是跳转的问题，这个新版也解决了。体验上要比旧版好的多，可以等待一下3.1.11的发布

**Comment by AvoidantPerDis** [comment]
那我的需求就是想时刻显示除最小子块的完整面包屑呢

**Comment by TCOTC** [comment]
一直都有人说面包屑太多

**Comment by SaXz2** [comment]
问题是最后一层面包屑是内容本身，跟反链内容是重叠的，这个块标去掉文字后除了跳转并没有其他存在的意义，外观上空一行跟其他内容格格不入，保留文字显示重复的问题论坛也有很多人提出，现在通过 Ctrl+左键是非常优雅的解决方案了。

**Comment by AvoidantPerDis** [comment]
> 问题是最后一层面包屑是内容本身，跟反链内容是重叠的，这个块标去掉文字后除了跳转并没有其他存在的意义，外观上空一行跟其他内容格格不入，保留文字显示重复的问题论坛也有很多人提出，现在通过 Ctrl+左键是非常优雅的解决方案了。

我也说了是除了本身啊

**Comment by SaXz2** [comment]
> 我也说了是除了本身啊

那现在改进的逻辑不跟你说的一样吗，无论标题还是无序列表都有面包屑了，排序也按照内容顺序排序，面包屑重复项也去掉了保持了一致性。参考 https://github.com/siyuan-note/siyuan/issues/13008 的最新改进

**Comment by TCOTC** [comment]
其实等下个版本再试就好了，现在不用讨论这个

**Comment by AvoidantPerDis** [comment]
等下个版本用到了再看看吧 。我也不只是为了这一个功能，只是说点想说的

**Comment by AvoidantPerDis** [comment]
新版本很好用 感谢D大和各位的努力 我想我也应该再耐心一点 相信思源能越来越好
