### ISSUE TITLE
表情失效

### ISSUE THREAD

**Issue by defaultw** [siyuan-note/siyuan#12872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/a2185ff0-6d18-436d-8cb9-846ffd82dc80)
使用docker部署，一段时间后部分表情陆续失效

### Expected result

使表情显示正常

### Version environment

```markdown
- Version: 3.1.9
- Operating System:  Ubuntu 24.04 LTS (GNU/Linux 6.8.0-45-generic x86_64)
- Browser (if used):Chrome
```

### Log file

![image](https://github.com/user-attachments/assets/ebdd783f-c2a8-480f-9954-f0fb9317f18c)
![image](https://github.com/user-attachments/assets/de1cd04f-e209-42e2-b957-ddb5923c6d47)

**Comment by 88250** [comment]
需要安装较新的 Emoji 字体，或者试试集市中的 Emoji 插件。

Console 截图报错和这个没有关系，看上去是某个浏览器插件的报错。
