### ISSUE TITLE
The document tree creation time and update time are reversed

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12874]
文档树创建时间和更新时间颠倒了

https://ld246.com/article/1729572166387

![image](https://github.com/user-attachments/assets/894da5a3-3167-49bd-8459-2b3b98a295a6)

**Comment by TCOTC** [comment]
重建索引之后恢复正常，但编辑一下文档之后又变成颠倒的了

**Comment by 88250** [comment]
我这里无法重现问题，需要上传一下 .sy.zip

**Comment by TCOTC** [comment]
录屏：

[视频.webm](https://github.com/user-attachments/assets/5a03bf8c-94af-4722-bf1c-e9d2f23ba704)
