### ISSUE TITLE
我们可以加一个pdf自动转markdown格式数据的功能吗

### ISSUE THREAD

**Issue by CoderYiFei** [siyuan-note/siyuan#12875]
我们可以加一个pdf自动转markdown格式数据的功能吗

有一些github上参考的pdf转md的仓库，我希望它们被集成到siyuan里面去

**Comment by TCOTC** [comment]
建议单独找这类工具使用

**Comment by 88250** [comment]
这个不考虑内置了，请在软件外单独处理，感谢提议。
