### ISSUE TITLE
在代码块内按 Delete 不应该影响其他块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12870]
关联 https://ld246.com/article/1729516965382

[视频.webm](https://github.com/user-attachments/assets/ad79e581-0899-4d92-9542-ccef2d310941)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by Vanessa219** [comment]
notion 也是这样做的，Delete 是末尾反向删除，不需要的话不要乱按就行。

**Comment by TCOTC** [comment]
Notion 是会把下一个块的内容移动到代码块内的，跟思源不一样。而且 Notion 的更反人类。

在代码块内按 Backspace 和 Delete 都是高频操作，应该避免影响到其他的块。

**Comment by Vanessa219** [comment]
正常人在末尾不会无缘无故 Delete，这个就不进行修改了。

**Comment by TCOTC** [comment]
会有需要长按 Delete 删除代码的场景
