### ISSUE TITLE
导出标准markdown时，支持将 双向链接 转换成 文档超链接 

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1287]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
![image](https://user-images.githubusercontent.com/37007969/105751019-6df29880-5f80-11eb-97f8-c16546d356df.png)
在做一些安装教程发布到github或者gogs上时，经常会让读着参考[另一篇文档](/test.md)，在思源中习惯采用 `((` 语法，但是导出时并不能转成相对笔记本的路径

### 描述最优的解决方案 Describe the optimal solution
我看到block表里面已经存储了内容块所在的文档相对路径，希望能在导出时增加 锚文本+文档超链接 选项

![image](https://user-images.githubusercontent.com/37007969/105752016-bf4f5780-5f81-11eb-8666-ed2233a8e1d6.png)

**Comment by 88250** [comment]
你好，导出主要是单篇导出，批量也是按单篇处理的。

块引遇到文档块，使用非嵌入内容式导出这个暂时没有计划，我们的期望是社区中有人能基于 Lute 来做，谢谢提议。
