### ISSUE TITLE
反链面板中的无序列表不会展开

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12873]
### In what scenarios do you need this feature?

![Clip_2024-10-22_10-29-38](https://github.com/user-attachments/assets/02805435-3861-4eb7-a029-a0c7a8faf546)
这里我把展开数已经开到了1000但是在反链面板里面依旧是折叠的状态
![Clip_2024-10-22_10-31-34](https://github.com/user-attachments/assets/afa33299-052d-45aa-913c-a8cc7da496ea)

### Describe the optimal solution

希望无序列表可以在反链面板展开

**Comment by 88250** [comment]
这个配置项指的是展开的文档这一级，不是内部折叠块。

**Comment by SaXz2** [comment]
> 这个配置项指的是展开的文档这一级，不是内部折叠块。

好的谢谢，理解错了，那无序列表的展开在哪里设置，一个一个点开有点繁琐

**Comment by 88250** [comment]
目前只能手动点
