### ISSUE TITLE
希望数据库条目支持shift多选

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12879]
### In what scenarios do you need this feature?

目前只能一个个点，好麻烦

### Describe the optimal solution

。。

**Comment by TCOTC** [comment]
重复 https://github.com/siyuan-note/siyuan/issues/11975

**Comment by Jerry-0202** [comment]
> 重复 #11975

不算重复，算一个补充。可以考虑再开启一下。因为对键盘的支持不是那么友好。
另外我发现一个问题，对于选中的单元格有很多个的话，右键菜单只能恢复在一个条目，具有焦点，而不是多行条目。

多个条目应该有他自己的上下文菜单。

**Comment by TCOTC** [comment]
> 条目支持shift多选

就这一点而言是重复的
