### ISSUE TITLE
Document block sort value changed from `0` to `100`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#12886]
https://github.com/siyuan-note/siyuan/issues/10584 实现了关键字跨块出现后命中文档块，所以按 `类型` 排序时搜索结果中会出现大量文档块，需要降低其权重，使其排到最后面。

重建索引后生效。

**Comment by TCOTC** [comment]
能不能支持自定义搜索结果优先级？这样改的话文档就跑到后面了吧

**Comment by 88250** [comment]
前面如果有单个块命中关键字，那就单个块排前面；不能自定义。

**Comment by 88250** [comment]
比如这种很常见的情况：

![image](https://github.com/user-attachments/assets/3b060d91-d063-458e-ab5c-10fd5b126f50)

但可能不方便的就是这种情况文档会排在后面：

![image](https://github.com/user-attachments/assets/30cb4fff-c5bd-43e7-a46e-abb7823ed7df)

这个暂时没有办法处理了。

**Comment by Achuan-2** [comment]
不建议降低文档搜索权重，我使用搜索功能，绝大部分都是搜索文档，文档往往代表已经整理或者正在整理的笔记，只有找不到文档才会去找块，因此文档理应在块前面，而不是干扰项, 对我而言，搜索块往往是干扰项。把文档放在搜索结果后面，对很多人来说，应该是本末倒置。

此外，比如我之前打开MOC文档，都是搜前缀@+领域，这样moc文档都在最前面，现在改完权重之后，这个用法就不好用了，反而是之前引用MOC文档的一个块在前面了……

因此建议不更改文档搜索权重，等之后有人反馈再看看，那些用dailynote记录笔记的人，不想搜索文档，可以在需要的时候关闭搜索文档，来过滤。现在这样一改，那我只能把所有子块都禁用了，只搜索文档了。

**Comment by 88250** [comment]
不更改权重的话搜索无法精确定位到块了，这个问题更大哦。

**Comment by Achuan-2** [comment]
> 不更改权重的话搜索无法精确定位到块了，这个问题更大哦。

1. 对我而言，90%场景用搜索都是找文档，10%才找没整理过的块。用一个关键词找到各个文档，对我而言，更符合预期，找到的文档很多，我可以添加更多关键词来精确查找
2. 用户要精确定位块可以关闭搜索文档块实现，改完权重，要让文档块在前面，得关闭所有其他块，只会更麻烦

**Comment by 88250** [comment]
> 用户要精确定位块可以关闭搜索文档块实现

不能关闭的，否则搜索不到文档名。

**Comment by 88250** [comment]
这样吧，先不改动，还是用 0，等发布个 dev 版你感受下看看。

**Comment by Achuan-2** [comment]
好，还想到一个解决方法，类型排序一定是文档块放在前面的，这就是类型排序的预期
但是可以让相关排序，被多个关键词完全命中的块放在前面

**Comment by 88250** [comment]
后续在 https://github.com/siyuan-note/siyuan/issues/10584 中看看能否改进吧。
