### ISSUE TITLE
Enhancement: Smaller Slash Command Menu

### ISSUE THREAD

**Issue by UsmanTechJive** [siyuan-note/siyuan#12887]
### In what scenarios do you need this feature?

Hey there!

I just have a small request, I love the slash command feature in SiYuan, but it feels a bit too big and overwhelming right now, covering the entire space.

![image](https://github.com/user-attachments/assets/91d578dd-6fb4-4f46-8bd1-df9ca7001090)

### Describe the optimal solution

In apps like Notion, AnyType, and this new Lazy Note Taking app, the menu is much smaller and more compact. I really love the modern look of the Lazy app, and I think something similar would make SiYuan even better.

![image](https://github.com/user-attachments/assets/597d06c5-118e-4578-a78b-6a3b404bb26f)

I would appreciate it if we could have both full-size and compact menu options in the settings.

Please consider this request, as I believe it would significantly enhance the user experience. Thank you!

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/815284dc-ea43-47dc-8388-39a846e18808)

The default theme looks like this, but it seems a bit too wide. We’ll see if we can adjust it later. Thanks for your feedback.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
