### ISSUE TITLE
Feature Request 「plz support InternLM2.5」

### ISSUE THREAD

**Issue by boshallen** [siyuan-note/siyuan#12882]
### In what scenarios do you need this feature?

Hi,

I noticed that the repository currently lacks support for the InternLM2.5-7B (1.8B, 20B) model, which may cause compatibility issues or missing steps for users trying to implement it. It would be beneficial to update the repository with detailed instructions or tools for integrating and using the InternLM2.5-7B model, ensuring the content remains relevant.

I believe that adding this support would significantly enhance the usability of the project. While some manual adjustments are possible, official guidance or toolchain support would be much more efficient and advantageous, especially for new users.

If possible, including example scripts or demonstrating integration with InternLM2.5-7B would also be a valuable addition.

For further support, please add the InternLM Assistant (WeChat search: InternLM) or join the InternLM Discord(https://discord.com/invite/xa29JuW87d).

### Describe the optimal solution

Feature Request 「plz support InternLM2.5」

**Comment by 88250** [comment]
用户如果需要的话会自己配置然后填入 model 参数的，请不要滥用 issue 推广，好的产品自己会说话。

Users will configure and fill in model parameters if necessary. Please do not abuse issue promotion. Good products will speak for themselves.

![image](https://github.com/user-attachments/assets/aba95686-79d7-402b-9b12-de54d93db47c)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
