### ISSUE TITLE
“未引用资源文件”面板存在以 `.sya` 格式结尾的文件

### ISSUE THREAD

**Issue by xeahsoon** [siyuan-note/siyuan#12880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在数据库的链接或资源类型字段中引用本地 PDF 文件，设置中的“未引用资源文件”面板存在以 `sya` 格式结尾的文件，如果误删除该文件，不知道是否对数据会产生影响

### Expected result

在数据库中引用文件，“未引用资源文件”中不应存在与该文件有关的内容

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/6e5a5040-bc8b-48bd-ab51-f7d639359456)

![image](https://github.com/user-attachments/assets/49ad604b-be45-4347-a777-6ac3b442fe8b)

### Version environment

```markdown
- Version: v3.1.10
- Operating System: Docker
- Browser (if used): Chrome
```

### Log file

无

**Comment by TCOTC** [comment]
@88250 这个不是能清理吗：

![image](https://github.com/user-attachments/assets/1032ea04-8889-4d25-832d-33d3991e09a1)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by 88250** [comment]
.sya 是 PDF 标注数据文件，如果没有 PDF 资源文件的话 .sya 会纳入清理。

楼主你目前的情况应该是把 PDF 资源文件的引用删了，然后在数据库链接字段中手动加入了 assets/xxx.pdf 地址，这种情况目前没有把数据库 链接/资源 字段加入到清理计算中，下个版本会改进，感谢反馈。

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by TCOTC** [comment]
> 这种情况目前没有把数据库 链接/资源 字段加入到清理计算中，下个版本会改进

是怎么改进？

**Comment by 88250** [comment]
就是把 链接/资源 字段中的 assets/xxxx 纳入到清理计算中。

**Comment by 88250** [comment]
对，就是数据库中的链接和资源字段和普通 assets 超链接都算做引用

**Comment by TCOTC** [comment]
刚刚试了一下，确实哦，删除条目之后该条目之前引用的资源文件不会出现在“未引用的资源文件”里

**Comment by TCOTC** [comment]
> 这个PDF标注不是能清理吗：
>
> ![image](https://github.com/user-attachments/assets/1032ea04-8889-4d25-832d-33d3991e09a1)

@88250 那用户指南这里是不是有问题？

**Comment by 88250** [comment]
代码已经变更 https://github.com/siyuan-note/siyuan/issues/7964 稍后改进文档。
