### ISSUE TITLE
Docker 容器启动慢问题（使用NFS挂载的存储执行chown性能问题）

### ISSUE THREAD

**Issue by DreamBlurred** [siyuan-note/siyuan#12881]
### In what scenarios do you need this feature?

我的Docker容器工作目录存储在通过NFS挂载的目录下（局域网内），其挂载参数为`rw,soft,intr,noatime,nodiratime,nosuid,rsize=65535,wsize=65535,retrans=1,timeo=600`
为了避免性能差已经屏蔽了大多数不实用的参数了，容器启动脚本中的这段代码是无条件执行
`echo "Adjusting ownership of /opt/siyuan, /home/siyuan/, and ${WORKSPACE_DIR}"`
`chown -R "${PUID}:${PGID}" /opt/siyuan`
`chown -R "${PUID}:${PGID}" /home/siyuan/`
`chown -R "${PUID}:${PGID}" "${WORKSPACE_DIR}"`
笔记数据文件较多后执行性能很差(目前仅4-5个小笔记，文件总大小200M+，以及需要3-5分钟的加载时间了，看日志就是执行这一步的代码)，且NFS服务端已经映射了目录权限为固定值，因此这个指令并无作用，反而带来很大的性能开销

### Describe the optimal solution

为Docker启动变量或者入参接口处添加一个变量位用来限制是否跳过这些指令（需要使用者去判断权限问题）

### Describe the candidate solution

添加一个目录权限判断，在目录权限满足时跳过这些指令（当然这样并不一定安全，且如果遍历的话性能无法保证）

**Comment by 88250** [comment]
这个估计不会动了，不然可能有其他问题。另外，不建议在网络存储上使用思源，思源比较依赖磁盘性能。

**Comment by DreamBlurred** [comment]
> 这个估计不会动了，不然可能有其他问题。另外，不建议在网络存储上使用思源，思源比较依赖磁盘性能。

好吧，还是感谢回复，目前局域网Nas使用还未发现卡顿或延迟的情况，后面看情况吧
