### ISSUE TITLE
请问如何删除题头图

### ISSUE THREAD

**Issue by ohyessir** [siyuan-note/siyuan#12888]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/e1e0126f-ddcd-4de7-9686-1c36bc0a05f6)
如何删除如下的红色题头图
![image](https://github.com/user-attachments/assets/f577ed1a-e729-4095-9dd8-610404a4d02f)
这个题头图看的有点不舒服，像恐怖片里面血液的感觉，请问我怎么在程序中永久删除这个图

### Describe the optimal solution

我应该如何删除这个

### Describe the candidate solution

1

### Other information

1

**Comment by 88250** [comment]
抱歉，内置的题头图不支持删除。
