### ISSUE TITLE
JavaScript Snippet Not Executing on Startup After Reopening SiYuan Without Manual Re-enabling

### ISSUE THREAD

**Issue by UsmanTechJive** [siyuan-note/siyuan#12893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I have modified the breadcrumbs using a CSS snippet, as shown in the image below:

![image](https://github.com/user-attachments/assets/d2661905-323c-4035-9494-890b5034312e)

I implemented additional CSS and JavaScript to hide the breadcrumbs, making them visible only when hovering over the .protyle-top area. This setup works as expected sometimes, but at other times it doesn’t work at all.

CSS Snippet:
`
/* Initially hide the breadcrumb */
.protyle-breadcrumb {
    opacity: 0;
    transition: opacity 0.3s ease, visibility 0.3s ease;
    visibility: hidden; 
}

/* Show the breadcrumb on hover */
.layout-wnd--active:hover .protyle-breadcrumb {
    opacity: 1;
    visibility: visible;
}

.protyle-breadcrumb__bar--nowrap {
    display: none;
}

/* Flashcard Fix */
.card__block .protyle-breadcrumb {
    position: relative !important;
    left: 0px;
    top: 0px;
}

/* Embedded Block Fix */
.block__edit.fn__flex-1.protyle {
    position: static !important;
}

/* WebView Fix */
.protyle-breadcrumb .svelte-8mo1c {
    position: static !important;
}

/* Light Mode */
:root[data-theme-mode="light"] .protyle-breadcrumb {
    color: var(--b3-theme-on-surface);
    position: absolute;
    left: 18px !important;
    top: 8px;
    backdrop-filter: blur(9px);
    border-radius: 100px !important;
    background: radial-gradient(rgba(240,240,240,0.8), rgba(240,240,240,0.8));
    background-color: var(--b3-theme-on-surface);
    height: 30px !important;
    mix-blend-mode: luminosity !important;
    outline: 1px solid var(--b3-border-color-trans);
}

/* Dark Mode */
:root[data-theme-mode="dark"] .protyle-breadcrumb {
    color: var(--b3-theme-on-surface);
    position: absolute;
    left: 18px !important;
    top: 8px;
    backdrop-filter: blur(9px);
    border-radius: 100px !important;
    background: radial-gradient(rgba(10,10,10,0.65), rgba(10,10,10,0.65));
    background-color: var(--b3-theme-on-surface);
    height: 30px !important;
    mix-blend-mode: luminosity !important;
    outline: 1px solid var(--b3-border-color-trans);
}
`

JS Script:
`
const breadcrumb = document.querySelector('.protyle-breadcrumb');
const topElement = document.querySelector('.protyle-top');

// Function to show the breadcrumb
function showBreadcrumb() {
    breadcrumb.style.opacity = '1';
    breadcrumb.style.visibility = 'visible';
}

// Function to hide the breadcrumb
function hideBreadcrumb() {
    breadcrumb.style.opacity = '0';
    breadcrumb.style.visibility = 'hidden';
}

// Show breadcrumb when mouse enters .protyle-top or .protyle-breadcrumb
topElement.addEventListener('mouseenter', showBreadcrumb);
breadcrumb.addEventListener('mouseenter', showBreadcrumb);

// Hide breadcrumb when mouse leaves .protyle-top or .protyle-breadcrumb
topElement.addEventListener('mouseleave', function() {
    // Delay to give user time to move from topElement to breadcrumb
    setTimeout(() => {
        if (!breadcrumb.matches(':hover') && !topElement.matches(':hover')) {
            hideBreadcrumb();
        }
    }, 100);
});

breadcrumb.addEventListener('mouseleave', function() {
    // Delay to allow user to move back to topElement if needed
    setTimeout(() => {
        if (!breadcrumb.matches(':hover') && !topElement.matches(':hover')) {
            hideBreadcrumb();
        }
    }, 100);
});
`

Whenever I close and reopen SiYuan, the JavaScript does not function as intended until I manually disable and re-enable it. However, sometimes even after re-enabling, it still doesn’t work, only functioning correctly the first time. This behavior is not limited to this particular script but seems to affect other scripts as well. I suspect there might be a bug causing the JavaScript not to execute correctly upon launching SiYuan. Could there be something I’m overlooking, or is this an issue with how scripts are being handled during startup?

### Expected result

The JavaScript should execute correctly every time SiYuan is opened, without requiring manual re-enabling of the script.

### Version environment

```markdown
- Version: 3.1.10
- Operating System: 
- Browser (if used):
```

### Log file

-

**Comment by TCOTC** [comment]
I think that the .protyle-breadcrumb and .protyle-top elements do not exist at the time JS is executed.

**Comment by UsmanTechJive** [comment]
Maybe, but when I created and ran this script the first time, it worked as expected. However, when I tried re-opening SiYuan, it launched and loaded, but now when I'm re-enabling the script, it's not working, even though both .protyle-breadcrumb and .protyle-top elements do exist because I can see in the dev tools. I'm confused about what is going wrong here...

**Comment by 88250** [comment]
Hi, this problem may only be solved by you.

**Comment by TCOTC** [comment]
SiYuan will run the JS before adding the interface elements, which may be the cause of the problem.
