### ISSUE TITLE
The marketplace language does not change after switching the appearance language

### ISSUE THREAD

**Issue by syh19** [siyuan-note/siyuan#12892]
切换软件语言后有概率出现集市弹窗语言未正确切换的问题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

切换软件语言后有概率出现集市弹窗语言未正确切换的问题。

### Expected result

语言正确切换

### Screenshot or screen recording presentation

<img width="1291" alt="image" src="https://github.com/user-attachments/assets/a30e844f-545c-4ef9-adb2-7b424449bb0d">

### Version environment

```markdown
- Version: v3.1.10
- Operating System: MacOS
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
麻烦录屏演示重现步骤。

**Comment by syh19** [comment]
主要看视频的后半部分，软件语言为英文，集市语言却是中文。

https://github.com/user-attachments/assets/e5c180a2-a29d-4765-bf41-c4f306fbebe8

**Comment by syh19** [comment]
才发现`issue`上的图片上传错了，主要看一下视频吧，视频复现了问题。

**Comment by 88250** [comment]
感谢反馈，稍后修复。

**Comment by TCOTC** [comment]
@88250 marketplace → bazaar ？

**Comment by 88250** [comment]
Issues 标题里用 marketplace

**Comment by TCOTC** [comment]
👌#8020
