### ISSUE TITLE
选中自定义表情之后不应该弹出表情选择器

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12898]
只应该在点击的时候弹出，选中的时候不应该弹出：

[视频.webm](https://github.com/user-attachments/assets/4c9c59ef-69e5-4fd1-8a80-2a73ff93917e)

**Comment by Vanessa219** [comment]
那如果选中以后再点击呢？目前没有找到可以区分选中时点击还是选中后再点击的标识。

**Comment by TCOTC** [comment]
> 目前没有找到可以区分选中时点击还是选中后再点击的标识

区分不了就不管它，只要单纯选中的时候不弹出就行了。

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vanessa219** [comment]
这个和链接不一样，选中链接文字后再点击，选中会消失，但是图片不会。这个就涉及到浏览器的特性了。
选中表情后光标一般不会在光标上，就不进行修改了。
