### ISSUE TITLE
Docker外网连接启动速度异常

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#12894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/0c0a919b-c5d6-4dd8-9690-93742916e1b3)
docker思源在外网访问的时候启动速度很慢，要卡启动界面两三分钟，卡在loadpetals这一项，用内网ip访问无问题，可能是什么问题？日志也没发现有什么异常

### Expected result

和内网速度一致

### Version environment

```markdown
- Version: 3.1.10
- Operating System: 
- Browser (if used):edge
```

### Log file

I 2024/10/24 22:13:41 session.go:116: auth success [ip=2409:8a55:636:bf20:3661:4a24:bbfc:e7dc]
I 2024/10/24 22:13:41 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36 EdgA/130.0.0.0]
I 2024/10/24 22:15:38 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0]
I 2024/10/24 22:16:01 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0]
I 2024/10/24 22:16:28 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0]
E 2024/10/24 22:16:32 serve.go:466: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
I 2024/10/24 22:17:20 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0]
I 2024/10/24 22:17:40 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0]
I 2024/10/24 22:24:01 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36 EdgA/130.0.0.0]
I 2024/10/24 22:28:40 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0]
I 2024/10/24 22:43:23 store.go:61: purging data repo [/siyuan/Cloud/repo/]
I 2024/10/24 22:43:23 store.go:229: purged data repo [/siyuan/Cloud/repo/], [314] indexes, [3380] objects, [29468765] bytes
I 2024/10/24 22:51:59 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0]

**Comment by 5kyfkr** [comment]
![image](https://github.com/user-attachments/assets/98c2a356-dbc7-4073-84d3-36a3b8c2175e)
似乎是nginx反代的ws不行

**Comment by 5kyfkr** [comment]
![image](https://github.com/user-attachments/assets/83fe6bff-0b75-41b8-b1f7-8bb47ed261f8)
是不是loadpedals有6.9m大小所以加载慢？

**Comment by 88250** [comment]
网络太慢了或者是服务器下行带宽不够，加载 6.5 K 需要 1.7 秒……

![image](https://github.com/user-attachments/assets/4d5f37ee-85db-4df7-aa4c-4c6367f56071)

**Comment by xeahsoon** [comment]
> 网络太慢了或者是服务器下行带宽不够，加载 6.5 K 需要 1.7 秒……
> 
> ![image](https://private-user-images.githubusercontent.com/873584/380001322-4d5f37ee-85db-4df7-aa4c-4c6367f56071.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzcyMzIsIm5iZiI6MTcyOTgzNjkzMiwicGF0aCI6Ii84NzM1ODQvMzgwMDAxMzIyLTRkNWYzN2VlLTg1ZGItNGRmNy1hYTRjLTRjNjM2N2Y1NjA3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwNjE1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmZiNzFhMDBiMzY3NDQxM2Q5MDczNjBjNzI0YTcyNzNiYjU1ZGU2YWNiMjRkNDg1MzdiNWZlOGQ1YjY2MzRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xQo3GG-GUnHB7votTmKeLo0kDwOy2pmFrnmsuECVntg)

@88250 @5kyfkr 我这也有一样的问题，并不是外网带宽不行，主要时间都花在 `loadPetals` 这个请求上，如果配置的 http 这个接口请求几秒钟就能完成，但是一旦配置成 https，这个接口就要几十秒，并且返回包的大小也不一致。
![image](https://github.com/user-attachments/assets/eea3a688-da0a-455a-bcfa-e2f72e5917fb)
![image](https://github.com/user-attachments/assets/e3566645-fb98-42bd-8295-c79c837fafdc)

**Comment by 5kyfkr** [comment]
> @88250 @5kyfkr 我这也有一样的问题，并不是外网带宽不行，主要时间都花在 `loadPetals` 这个请求上，如果配置的 http 这个接口请求几秒钟就能完成，但是一旦配置成 https，这个接口就要几十秒，并且返回包的大小也不一致。 ![image]

你也用了cloudflare的cdn吗？我是搭在NAS上用DDNS到cloudlare上，然后挂上cdn，这样就能用ipv4网络环境访问，测试了只有在国外服务器翻墙的连接就很快，只要一用国内网络环境就会慢，应该是cloudflare服务器的原因

**Comment by shuojie819** [comment]
+1，我只里也是，loadPetals 超级慢

![Image](https://github.com/user-attachments/assets/8185e8af-655b-4ca3-b984-96277a3f14fb)

**Comment by shuojie819** [comment]
loadPetals 怎么优化变小呀， 这个网站好快呀： https://publish.ccsjhn.com/

![Image](https://github.com/user-attachments/assets/5e273570-02e9-4689-81f2-038770c89be6)
