### ISSUE TITLE
在视觉上左右对齐菜单选项

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12908]
关联字段菜单这里有点没对齐：

![image](https://github.com/user-attachments/assets/1971b266-4212-430f-af3e-012f9495e9bd)

宽度和高度菜单也是：

![image](https://github.com/user-attachments/assets/b702655e-7570-4d60-b5e2-b77bb875733b)

**Comment by Vanessa219** [comment]
第一点已修复，第二点是保证 focus 和 hover 时对齐，就不修改了。

不加入版本了。

**Comment by TCOTC** [comment]
> 第二点是保证 focus 和 hover 时对齐

难道就不能 focus 、 hover 和直接看上去都对齐吗？

**Comment by Vanessa219** [comment]
要有效果的嘛
