### ISSUE TITLE
在链接内选中文本，无法弹出工具栏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12900]
[视频.webm](https://github.com/user-attachments/assets/778bf582-ad71-467d-abd3-a7eaa84e1cf3)

**Comment by 88250** [comment]
我这里测试正常，可以弹出。

![image](https://github.com/user-attachments/assets/e97e090f-f82b-4200-a638-a19b51b96d23)

暂时先关闭了。

**Comment by TCOTC** [comment]
录屏看看你的操作

**Comment by 88250** [comment]
[issue.webm](https://github.com/user-attachments/assets/1c4b1825-2b2e-46e6-8deb-b8a5913b489a)

**Comment by TCOTC** [comment]
你把链接换成 `siyuan://blocks/20241025115234-m7m9w2y` 试试

**Comment by 88250** [comment]
换成这个确实有问题 @Vanessa219
