### ISSUE TITLE
数据库单元格支持垂直拖动填充值

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12907]
像 Notion 这样可以向上拖动：

![image](https://github.com/user-attachments/assets/cf0f7ba9-1ab7-42ce-aaf1-15ac4eb71557)

**Comment by TCOTC** [comment]
我看 Notion 在填充完之后是不会再出现这个圆点的，思源这个有点问题：

[视频.webm](https://github.com/user-attachments/assets/035e592d-cccb-4072-85ef-d7af36283da0)

**Comment by Vanessa219** [comment]
没啥问题，可以继续操作更方便。

**Comment by TCOTC** [comment]
那圆点不应该是在最后选中的那个单元格上吗？现在始终是在最底下的单元格

**Comment by Vanessa219** [comment]
统一在填充区域的最后一个单元格

**Comment by TCOTC** [comment]
> 可以继续操作更方便

那这样就不方便继续操作了啊，这个圆点出现在带有填充值的多个条目中间，逻辑上还要手动点击一下最上方的条目再继续向上填充

**Comment by Vanessa219** [comment]
应该是出现在填充单元格的最后一个吧。

**Comment by TCOTC** [comment]
也合理，刚刚看了 FlowUs Wolai 是这样的。

只有思源的这个圆点会在倒数第二个条目：

[视频.webm](https://github.com/user-attachments/assets/8c68f5c8-4003-4d87-95fa-58a99e1db649)
