### ISSUE TITLE
调整字数显示位置为右下角悬浮显示

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1290]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

隐藏编辑器工具栏后，看不到文章总字数了

### 描述最优的解决方案 Describe the optimal solution

类似typora的方式，右下角悬浮显示，如下图：
![image](https://user-images.githubusercontent.com/657850/105791399-fb55dd00-5fc0-11eb-91df-efb587176c8d.png)

typora貌似用了底部状态栏（非最大化时候可见，窗口最大化的时候就看不到状态栏，正文可以延伸到屏幕最低端显示，不懂这是个啥）

**Comment by 88250** [comment]
v1.2.0 调整到文档导航条 - 更多中了，谢谢。
