### ISSUE TITLE
搜索样式改进

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12901]
### In what scenarios do you need this feature?

在搜素的过程中，只有一行以及在按文档分组时路径过长不够清晰的问题
以下是对比图，可以看出路径长的眼花缭乱
![image](https://github.com/user-attachments/assets/7465df10-0c0d-4451-b5d8-9c79e9aaf16c)

### Describe the optimal solution

按文档分组应该只显示文档名称
路径信息应该跟不分组统一，都保持在右下角
![Clip_2024-10-25_18-01-04](https://github.com/user-attachments/assets/0c52c93d-f691-4d98-85c3-0d0e54edbb79)

搜索结果应该默认支持多行显示，虽然可以用css改，但默认的主题的样式还是建议改进一下。

**Comment by 88250** [comment]
感谢反馈，这个目前不考虑改动了。
