### ISSUE TITLE
希望数据库支持共享字段（来源于块的自定义属性）

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#12905]
### In what scenarios do you need this feature?

有些属性希望能在块绑定的每个数据库都显示，但又不想重复添加

### Describe the optimal solution

列名就是自定义属性名，如果匹配上，就显示出字段内容，并且能直接在数据库中编辑

**Comment by 88250** [comment]
这个还是建议用模板列。

**Comment by TCOTC** [comment]
可以用模板列获取绑定块的属性，不过编辑属性就有点麻烦了，关联 #11284 #11371

**Comment by Jiangshuon** [comment]
@88250 D大求助！我在updateAttributeViewCell函数中调用SetBlockAttrs(val.BlockID, nameValues)为什么会卡住呢？数据库编辑就没反应了。我想试着在编辑单元格后将值更新到自定义属性当中

![Image](https://github.com/user-attachments/assets/bd758fd0-1eb7-467e-bc81-8315ff6952ce)

**Comment by TCOTC** [comment]
- 关联 https://github.com/siyuan-note/siyuan/issues/13121
