### ISSUE TITLE
支持拖拽资源文件到数据库资源字段

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12904]
- [x] 编辑器的数据库中
- [x] 属性面板 - 数据库 中

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/9543
