### ISSUE TITLE
数据库更新时间字段和创建时间字段增加逻辑选项：绑定块优先与条目优先

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12909]
现有的更新时间字段和创建时间字段都是绑定块的属性，在一些情况下使条目管理极其不便（比如在混合绑定块条目与纯文本条目的数据库中筛选和排序），作为 #12345 的替代方案，在不破坏现有逻辑的情况下，我建议：

- 更新时间字段增加选项 `绑定块更新时间优先`(默认)、`条目更新时间优先`
- 创建时间字段增加选项 `绑定块创建时间优先`(默认)、`条目创建时间优先`

添加一个二级菜单到这个位置：

![image](https://github.com/user-attachments/assets/2a2be32d-29ce-4efe-baba-7524da7687fa)

**Comment by 88250** [comment]
维持现有设计不变了。如果一定需要显示条目更新时间，用模板列替代一下吧。

**Comment by TCOTC** [comment]
替代不了哇，只有时间字段才有这些筛选方式：

![image](https://github.com/user-attachments/assets/a93a832d-1f71-45ef-992b-64cad5ee4584)

**Comment by 88250** [comment]
那只能先凑合用了，新增特性现阶段不考虑了。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年10月27日(周日) 下午5:48
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 数据库更新时间字段和创建时间字段增加逻辑选项：绑定块优先与条目优先 (Issue #12909)




 
替代不了哇，只有时间字段才有这些筛选方式：
 
image.png (view on web)

**Comment by 88250** [comment]
补充模板变量：

```
.action{.entryCreated}
.action{.entryUpdated}
```

https://github.com/siyuan-note/siyuan/issues/12968

**Comment by TCOTC** [comment]
用户反馈：https://github.com/siyuan-note/siyuan/issues/14106

**Comment by TCOTC** [comment]
[数据库更新时间不会随内容变化自动更新时间，有办法解决吗 - 链滴](https://ld246.com/article/1759979719935)
