### ISSUE TITLE
改进点击 `已关闭的笔记本` 的动画

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12914]
[视频.webm](https://github.com/user-attachments/assets/44f29d73-3a63-4853-8702-271d590dd609)

1. 在点击收起的一瞬间不应该上升，在视觉上会有不必要的闪烁：

   [视频.webm](https://github.com/user-attachments/assets/09243289-30a7-4c80-920b-7e73e7709737)

2. 在点击展开的一瞬间不应该消失，在视觉上会有不必要的闪烁（另外那个删除图标也会闪一下，不过好像没法禁用这个 hover 样式，所以没那么有所谓）：

   [视频.webm](https://github.com/user-attachments/assets/9bfc8997-9b77-4c58-a9bf-c9ae91988e4e)

**Comment by SaXz2** [comment]
可以顺带改进一下文档树的拖拽显示吗，文档数量多了以后会更加的闪烁
示例1
![PixPin_2024-10-28_12-59-20](https://github.com/user-attachments/assets/1e33cd01-07eb-419f-8228-ba95eeb48e7e)
示例2
![recording](https://github.com/user-attachments/assets/d073b8e6-b81a-4895-baec-fb91c0b8deba)

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vanessa219** [comment]
@SaXz2 第一点可以优化。但第二点由于排序规则的不确定，需要刷新父列表。

**Comment by SaXz2** [comment]
> @SaXz2 第一点可以优化。但第二点由于排序规则的不确定，需要刷新父列表。

希望未来可以得到改善，文档数量多了以后，拖拽不停的刷新体验实在是不太好

**Comment by TCOTC** [comment]
我新建工作空间之后遇到了缩不下去的情况：

[视频.webm](https://github.com/user-attachments/assets/5e45a8c2-4498-43d4-88e8-7fca8aba6250)

**Comment by Vanessa219** [comment]
@SaXz2 好的，再改进一下

**Comment by SaXz2** [comment]
先感谢V姐，经过dev8测试不涉及以下两点效果已经非常完美了。

- 拖动大纲以后会导致文档树刷新
- 拖动大纲以后折叠的大纲会全部展开

**Comment by TCOTC** [comment]
@SaXz2 我想起来了，你是不是始终展开大纲了：

![image](https://github.com/user-attachments/assets/06528bd6-4a2b-4e4a-92d6-2fff821df24e)

**Comment by SaXz2** [comment]
才发现这个，昨天讨论半天原来问题出在这，难怪你复现不了

**Comment by TCOTC** [comment]
> 拖动大纲以后会导致文档树刷新

@Vanessa219 这个确实是，目前文档树会刷新了再展开，这个场景实际不应该刷新的

**Comment by Vanessa219** [comment]
已修复
