### ISSUE TITLE
浮窗右上角按钮没对齐

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12911]
现在是斜着对齐的，不好看：

![image](https://github.com/user-attachments/assets/3cc2752e-57fd-4ad7-87b3-5c6f5d432dff)

**Comment by Vanessa219** [comment]
不拉进版本了。

**Comment by TCOTC** [comment]
我觉得浮窗只有一个文档的情况下不应该有外侧这个滚动条：

[视频.webm](https://github.com/user-attachments/assets/bc27fe75-9a75-4e9f-b7cc-c568bc0b1d05)

**Comment by TCOTC** [comment]
特定情况下还会出现滚动条：

[video.webm](https://github.com/user-attachments/assets/f5617e30-0dc8-4626-b4f5-7b01893ee5e0)
