### ISSUE TITLE
Support exporting Markdown after selecting multiple documents

### ISSUE THREAD

**Issue by Chen017** [siyuan-note/siyuan#12912]
希望支持批量导出PDF等多种格式 Mark down也行 

### In what scenarios do you need this feature?

有很多文档需要导出 分享的时候只能一个一个手点非常慢 我看到有人说可以批量导出到 但是我没发现路径 当我多选几个文档之后 出来的按钮并没有导出 只有导出预览 

### Describe the optimal solution

支持批量导出

**Comment by TCOTC** [comment]
我觉得可以有多选文档导出

![image](https://github.com/user-attachments/assets/e55af00b-b601-467e-bbc1-09e09408c016)

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Chen017** [comment]
@88250 请问这个是完成了吗, 我在3.1.19还是只能批量导出markdown
