### ISSUE TITLE
全面修改与统一各种元素对应的光标类型 (cursor 属性) 与 hover 样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12915]
- 可点击的元素使用默认的箭头指针，hover 时元素背景色变灰
- 可拖拽的元素(和链接元素)使用 pointer ，如果该元素也可点击，则 hover 时元素背景色变灰

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vanessa219** [comment]
点击应该是小手手呀，背景变灰这个根据不同的元素来会更合理一些。

这个 issue 太笼统了，我先关闭了，还麻烦针对不同的使用场景和元素进行。

**Comment by TCOTC** [comment]
稍微修改了一下 issue 描述。

---

就是所有的按钮都改用箭头光标，用手的话不太规范，应该是可拖拽的元素或链接才用手 `cursor: pointer`（可拖拽的元素本来应该用抓手 `cursor: grab`，但考虑到这些元素一般都能点击，所以统一用 `cursor: pointer` 好看点）

比如 Chrome：

![image](https://github.com/user-attachments/assets/ad6c36c8-a9f1-4ae0-90d5-43884a0ac6dd)

QQ：

![image](https://github.com/user-attachments/assets/782c7904-517c-4f99-bcf4-256b0c773c96)

![image](https://github.com/user-attachments/assets/666f7baa-8aa1-4785-a109-716eaa7bb8bb)

**Comment by Vanessa219** [comment]
这个规范是哪里的？

**Comment by TCOTC** [comment]
比如 Apple：https://support.apple.com/en-hk/guide/mac-help/mh35695/mac

![image](https://github.com/user-attachments/assets/ce1104e0-eba0-4fce-8037-b64a649331d3)
![image](https://github.com/user-attachments/assets/5acdab73-dc5b-42ab-ac54-21ac19711e15)

比如 Microsoft：https://learn.microsoft.com/en-us/windows/win32/menurc/about-cursors

![image](https://github.com/user-attachments/assets/b004b1e3-3baa-4e0a-8d77-35b82da68c9b)
![image](https://github.com/user-attachments/assets/40129090-991d-4dc3-b8b9-bb11d55c1937)

比如 Mdn：https://developer.mozilla.org/zh-CN/docs/Web/CSS/cursor

![image](https://github.com/user-attachments/assets/2418259e-6f45-4e2e-bb7c-4d76a3916e29)
![image](https://github.com/user-attachments/assets/a5bb0797-57c9-417f-875c-9d19ba7677a6)
![image](https://github.com/user-attachments/assets/08c038e1-191a-49cb-a628-1ec8ea203a9a)

---

我看 Obsidian 也是这样：

![image](https://github.com/user-attachments/assets/7c0cc9c0-e6fc-4b6c-871b-4d9748713f78)

Anytype：

![image](https://github.com/user-attachments/assets/6055b31d-4146-4ced-926a-bd1d4660082b)

**Comment by Vanessa219** [comment]
IDE 也是这样的。但是网页端的 GitHub、notion 等都是 pointer。这是要区分网页和 app 么？

**Comment by TCOTC** [comment]
我觉得还是规范一点区分 default 和 pointer 的用法，让 UI 更美观。

网页和客户端我感觉应该不用区分，思源的按钮点击之后网页 URL 是不会变的。

**Comment by Vanessa219** [comment]
目前很多网站用的都是 pointer，这是为什么呢？

**Comment by TCOTC** [comment]
感觉可能是懒得做元素的 hover 样式，直接用 cursor: pointer 来表示元素可点击？或者是 UI 框架的问题？

我看了我电脑安装的软件，都是箭头：

![image](https://github.com/user-attachments/assets/e5871c74-6a37-4bee-80c2-57824f1e151f)

![image](https://github.com/user-attachments/assets/990f8b62-0d0f-4060-9d8f-7c2bbbbbde34)

![image](https://github.com/user-attachments/assets/bd76668a-2930-4467-a8d9-646c8027c7db)

![image](https://github.com/user-attachments/assets/ac49cfc7-df63-4d0a-a39b-7c79146af619)

![image](https://github.com/user-attachments/assets/ba0ceb33-5551-4d3f-8e82-7421c286265a)

**Comment by Vanessa219** [comment]
app 基本都是这样的，关键我们有网页版本的。

**Comment by Vanessa219** [comment]
目前还分不开

**Comment by TCOTC** [comment]
CSS 配合 #12549 好像可以分开？

**Comment by Vanessa219** [comment]
除了设备，还需要区分伺服的。这样做是重置，还有一种做法是 css 文件不同。
