### ISSUE TITLE
不知道怎么样让插件能够在某些地方屏蔽编辑器快捷键

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#12918]
### In what scenarios do you need this feature?

现在在把 [latex 公式提示](https://ld246.com/article/1729057425529) 整理成可以发布的插件，为了功能尽善尽美希望一些快捷键在codemirror中也能够保持和思源本体的一致性（其实最关键的就是`ctrl+z`、`ctrl+y`、`ctrl+enter`、`ctrl+f`这些）

目前遇到一个问题就是codemirror本质上就是把原本的textarea设置成display;none，然后在上面再自己绘制编辑器实现代码提示，这样的话在其上按下的快捷键都会触发编辑器快捷键（比如说`ctrl+z`会直接把整个公式块撤销），就算加上preventDefault也没用

感觉应该是思源前端注册触发方式的问题？还是说我的操作不太对，因为用codemirror的话只能用他自己的快捷键注册方法，用的也是那边提供的preventDefault。

### Describe the optimal solution

在想能不能通过某些注册，使得某些快捷键在具有某些标记的块上不会触发，最好是每个插件可以单独有自己的标记，比如说某个特定的class（就算是空的），前端快捷键触发的时候就检查一下如果满足条件就跳过

**Comment by TCOTC** [comment]
监听快捷键然后阻止默认行为？

**Comment by WingDr** [comment]
> 监听快捷键然后阻止默认行为？

就是已经preventDefault了，但是还是会触发，我把现在的插件和演示视频都发出来
[package.zip](https://github.com/user-attachments/files/17529606/package.zip)

https://github.com/user-attachments/assets/93df49e0-80c8-462e-b071-783ae7424805
就像这样，按下`ctrl+z`之后整个公式块被撤回了，但是事实上代码中是有preventDefault的
![image](https://github.com/user-attachments/assets/599aa5c6-fc5c-4915-909b-0ba625e7c31b)

**Comment by WingDr** [comment]
另外好像open-noneditableblock时间的event并不会附带这个块本身的信息？我觉得起码得有一个信息表明打开的是 公式块/行内公式/HTML块/引用块 吧，还是说是我没找到？如果有必要，我可以单开一个issue

**Comment by 88250** [comment]
@Vanessa219 抽空帮忙看看

**Comment by Vanessa219** [comment]
理论上焦点在公式的编辑器上就不会被编辑器的 keydown 事件劫持，加一个 `event.stopPropagation();`  就不会冒泡到 window 上。你先试试看，不行的话把重现步骤发一下。

**Comment by WingDr** [comment]
主要是它不在公式的编辑器，因为是用codemirror，就是把原本textarea的地方屏蔽掉了，然后添加了一个新的编辑器和原本的textarea同步，结构是这样的

![image](https://github.com/user-attachments/assets/6a7b07a7-1580-457d-a1df-a0c26a97a3a5)

里面editorEnhanceContainer就是新编辑器，然后mathEnhanceDyBlock是数学增强插件添加的部分

**Comment by WingDr** [comment]
其实最关键的是我没办法通过触发原本textarea的keydown事件来撤销，感觉是因为新编辑器和原本textarea同步的操作并不会被记录

**Comment by WingDr** [comment]
好好好，没事了，加了个stopPropagation就可以了，我还以为codemirror没提供这个选项，那这个issue就先关闭了

另外这个要不要考虑一下？现在好像还是没有什么办法在触发`open-noneditableblock`的时候判断是什么块
> 另外好像open-noneditableblock时间的event并不会附带这个块本身的信息？我觉得起码得有一个信息表明打开的是 公式块/行内公式/HTML块/引用块 吧，还是说是我没找到？如果有必要，我可以单开一个issue
