### ISSUE TITLE
增加两种打开数据库条目属性面板的方式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12910]
> 来自 #11284 的需求，经过讨论与 #11371 没有设计上的冲突

1. `Shift+点击` 条目块标，打开属性面板：

   ![image](https://github.com/siyuan-note/siyuan/assets/78434827/ceec2915-fae4-412f-86b4-8d9336d0ffa3)

2. 条目右键菜单增加 `打开属性面板`：

   ![image](https://github.com/user-attachments/assets/e5057143-c176-4cc7-9ea9-3ad8e971fc7c)

---

1. 有绑定块的条目打开这个块的属性面板（其中当前的数据库置顶显示）
2. 纯文本条目打开的“属性面板”，只包含该数据库的字段：#12941

**Comment by 88250** [comment]
> 2. 纯文本条目打开的属性面板，只有当前的数据库

这一点不考虑了，和初始设计相违背，因为只有块才有属性面板。

**Comment by 88250** [comment]
新增打开入口 @Vanessa219 抽空看看

**Comment by TCOTC** [comment]
> > 2. 纯文本条目打开的属性面板，只有当前的数据库
> 
> 这一点不考虑了，和初始设计相违背，因为只有块才有属性面板。

这是为了保证条目交互的一致性，本质是为了方便编辑条目字段，跟是否绑定块无关

**Comment by 88250** [comment]
现阶段不加入新特性了



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年10月27日(周日) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 增加两种打开数据库条目属性面板的方式 (Issue #12910)




    
纯文本条目打开的属性面板，只有当前的数据库
   
这一点不考虑了，和初始设计相违背，因为只有块才有属性面板。
  
这是为了保证条目交互的一致性，本质是为了方便编辑条目字段，跟是否绑定块无关

**Comment by TCOTC** [comment]
这个可以放到 milestone 里

**Comment by 88250** [comment]
不加了，改动不大。

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
