### ISSUE TITLE
api的paste事件,不能被 files 的粘贴事件正确触发,api for paste ,didn't works on files

### ISSUE THREAD

**Issue by AirParty** [siyuan-note/siyuan#12917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

粘贴文件的时候,第一次稳定不触发,之后稳定触发，但是事件内没有信息。

按照以下操作可以稳定触发bug.
1. 在plugin-sample中打开 "On paste“监听。在外部使用ctrl+c 复制一个文件。
2. 在siyuan内部使用ctrl+v粘贴。此时不会触发api的paste事件，文件会直接插入文档。
3. 继续点击ctrl+v。此时On paste事件会被触发。从控制台可以看到此时虽然触发事件，但是没有任何数据，文件也不会再次重复插入。
4. ![sc_2024-10-26_15-24-12](https://github.com/user-attachments/assets/abfe17c7-1a64-4ab8-bc4d-2fd82c2ee938)

### Expected result

希望能先触发API的paste事件再触发siyuan内部的粘贴事件。

### Version environment

```markdown
- Version: 3.1.10
- Operating System: windows
- Browser (if used):
```

### Log file

![sc_2024-10-26_15-24-12](https://github.com/user-attachments/assets/abfe17c7-1a64-4ab8-bc4d-2fd82c2ee938)

**Comment by 88250** [comment]
@Vanessa219 抽空帮忙看看。

**Comment by Vanessa219** [comment]
已修复，但需注意第一次走的是读本地路径，因此返回的是 string[] , 需要自己判断一下

![QQ_1729999582382](https://github.com/user-attachments/assets/76a9b261-27b7-406d-9447-ce2d3bf94eac)
