### ISSUE TITLE
改进一些危险操作的确认按钮

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12919]
> 延续 https://github.com/siyuan-note/siyuan/issues/12843#issuecomment-2436813988 的讨论

用红色警示用户

比如：

![image](https://github.com/user-attachments/assets/cd0e9ec0-7023-44ea-9ec4-20d624be09b1)

大概改成这样：（并且“确定”改为“删除”，更明确地提醒用户）

[视频.webm](https://github.com/user-attachments/assets/26874f16-7573-4096-8d79-a7fab4c5b0bf)

比如 `删除` 选项：

[视频.webm](https://github.com/user-attachments/assets/882435b4-bcf4-4443-b4e2-52bccbe52bfb)

参考 Notion 的， icon 和文本都会变红：

![image](https://github.com/user-attachments/assets/e1d08366-e6dd-4828-a5fe-171881cd2ee9)

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by TCOTC** [comment]
还有这个布局的删除按钮：

![image](https://github.com/user-attachments/assets/a966a02e-24fd-473a-bdd2-9c763d4ab220)
