### ISSUE TITLE
after drag/resize, keep then cursor in the editor

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1291]
### 描述问题 Describe the problem
调整编辑区域宽度（或打开和关闭侧栏时），光标所在位置被从当前屏幕可见区域挤出

### 期待的结果 Expected result
编辑区宽度变化前后，光标所在位置始终在屏幕中心

**Comment by Vanessa219** [comment]
由于后期打开文件树时需将光标移动到文件树上，以方便的使用上下键进行选择。
因此打开和关闭侧栏时请使用快捷键。

**Comment by roverway** [comment]
> 由于后期打开文件树时需将光标移动到文件树上，以方便的使用上下键进行选择。
> 因此打开和关闭侧栏时请使用快捷键。

这个问题和是否使用快捷键打开文件树无关，问题在于文件树挤占编辑区域后，编辑区域内容宽度变化导致当前光标位置被挤出屏幕外。除非侧边栏能够浮动在编辑区上层显示，不挤占屏幕空间，否则这个问题始终都有。

**Comment by Vanessa219** [comment]
修改以后是再拖拽后光标依旧保持在编辑器中。使用鼠标点击关闭和打开文件树不行，但是可以先用 `alt+1` 顶顶

**Comment by roverway** [comment]
> 修改以后是再拖拽后光标依旧保持在编辑器中。使用鼠标点击关闭和打开文件树不行，但是可以先用 `alt+1` 顶顶

没问题，本来我也是用快捷键打开和关闭侧栏的。多谢啦！
