### ISSUE TITLE
改进拖拽已开启排序的笔记本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12916]
避免有的用户不知道为什么不能排序

- 开启了文档树排序之后不允许拖拽**笔记本**（文档则始终允许拖拽），此时在笔记本上应使用默认的箭头指针 #12915
- 用户尝试拖拽笔记本时提示“已开启排序，无法拖拽”

**Comment by Vanessa219** [comment]
这样的话，每次开始拖拽都会提示，太干扰了。

**Comment by TCOTC** [comment]
那就干脆不提示了，直接禁止拖拽吧

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by TCOTC** [comment]
笔记本不是不能嵌套吗？

**Comment by Vanessa219** [comment]
文件可以

**Comment by TCOTC** [comment]
但文档可以嵌套跟这个 issue 无关

**Comment by Vanessa219** [comment]
> 那就干脆不提示了，直接禁止拖拽吧

由于可以拖拽文档，因此不能禁止。

**Comment by TCOTC** [comment]
我说的是禁止拖拽笔记本
