### ISSUE TITLE
属性面板支持拖动与多开

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12913]
> 来自 #11113 的需求，经过讨论与 #11371 没有设计上的冲突

可以添加一个「钉住」按钮，在点击「钉住」之前就和现在相同，在点击「钉住」之后就从模态转换为非模态，支持拖动与同时打开多个

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by 88250** [comment]
不考虑了，场景不多。
