### ISSUE TITLE
建议改进快捷键触发方式，缩小触发条件，减少意外触发

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12925]
### In what scenarios do you need this feature?

比如，ctrl+单击，仅限制ctrl+点击，而排除ctrl+alt+单击，ctrl+alt+shift+单击等被触发。

原因是，一旦 ctrl/shift/alt+某项操作被占用，则所有涉及到ctrl/shift/alt的组合键都有被触发的可能，这样，除了可能会导致按键冲突外，也大大缩小了快捷键的可用范围。关联问题：https://github.com/loonghfut/siyuan-alist/issues/2#issuecomment-2439623843

关联帖子：https://ld246.com/article/1726311206127/comment/1726566424823?r=wilsons#comments

### Describe the optimal solution

建议可参考
https://ld246.com/article/1726311206127/comment/1726566424823?r=wilsons#comments 这种方案
或者 https://ld246.com/article/1726311206127/comment/1726569945733?r=wilsons#comments 这种简单方案

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vanessa219** [comment]
目前修改了编辑器区域的点击，如果有遗漏的话可以进行回复。

**Comment by TCOTC** [comment]
为什么这里需要交换？

![image](https://github.com/user-attachments/assets/38a5da82-d863-44c7-94fb-d14d59a0334f)

**Comment by wish5115** [comment]
请教下大佬 @Vanessa219 @TCOTC 这里的 #if #else #endif是构建工具支持的吗？是怎么生效的的？
