### ISSUE TITLE
建议粘贴超链接后，可以选择性的支持多种形式，如：预览页面、仅网页标题、原始URL等

### ISSUE THREAD

**Issue by blackflash997997** [siyuan-note/siyuan#12929]
### In what scenarios do you need this feature?

现在默认粘贴超链接就是文本格式：
![image](https://github.com/user-attachments/assets/8ca5c76e-cee0-456c-a858-8e69c7a2c2df)
建议，粘贴后，弹出一个选择框通过方向键控制选择粘贴类型，
如：
![image](https://github.com/user-attachments/assets/5baf6a0f-75bc-4722-b70c-04bea310c2c1)

不知道后续能否支持？

### Describe the optimal solution

这个功能对于做笔记还是很有帮助的

**Comment by 88250** [comment]
使用 Ctrl+K 粘贴；不考虑其他样式了，感谢提议。
