### ISSUE TITLE
Add block ref exception for inline tags

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12922]
为行级标签添加块引用异常

只有为标签内的文本添加块引用才正常，除此之外则会吞掉选中的文本：

[视频.webm](https://github.com/user-attachments/assets/ff533e76-732f-4475-a636-9c334aaca83c)

使用场景是这个：https://ld246.com/article/1729262322134/comment/1729942961017#comments

![image](https://github.com/user-attachments/assets/7fd083a4-e6db-46ca-bb6e-d02186212e77)

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vanessa219** [comment]
先显示出来吧，引用和标签重叠，点击就点击不到标签了。
https://github.com/siyuan-note/siyuan/issues/7477
https://github.com/siyuan-note/siyuan/issues/8825
