### ISSUE TITLE
对接简悦

### ISSUE THREAD

**Issue by PayneSnow** [siyuan-note/siyuan#1292]
对接【简悦】，打通 阅读+笔记 工作流，实现网页阅读、剪藏和摘录

后期软件成熟后，建议增加网页剪藏功能；
1.网页剪藏也可以不用自己做，对接第三方服务。推荐使用【简悦】.强烈期待 思源笔记能和简悦对接，结合简悦的 阅读模式 + 标注系统 + 稍后读，以及思源笔记的知识网络建构功能，将会形成趋于完美的知识管理解决方案。使用简悦进行批注, 随后将批注内容直接导出至思源笔记. 随后用户再使用思源笔记进一步进行整理.
3.简悦：官网介绍——GitHub - Kenshin/simpread: [简悦 ( SimpRead ) - 让你瞬间进入沉浸式阅读的扩展](https://github.com/Kenshin/simpread)
链接内有简悦作者联系方式。期待您和简悦开发者沟通联系。
4.简悦介绍：
简悦 - SimpRead 进化到 1.0.1，虽是一小步，却带来了大家期盼的功能 https://sspai.com/post/39831
阅读模式 + 标注系统 + 稍后读，简悦 2.0 想成为你的知识管理解决方案 阅读模式 + 标注系统 + 稍后读，简悦 2.0 想成为你的知识管理解决方案 - 少数派 2---https://sspai.com/post/61996
5.个人评价：
我已经使用简悦3年，也使用过其他多种网页剪藏工具。简悦是我目前发现 功能最为强大、使用最为优雅的知识管理工具。
简悦优化了中文世界的几百个常用站点，使得用户能够体验优质优雅的网页阅读体验；
简悦对接了包括evenote、notion、语雀、ulysses、bear等中文世界常用等十几款应用的api,可以很方便地将网页全文以及批注内容直接发送至笔记或写作软件之中。

![image](https://user-images.githubusercontent.com/51922806/105801044-2fd29480-5fd3-11eb-9f45-dff2beb47ea5.png)
![image](https://user-images.githubusercontent.com/51922806/105801055-36610c00-5fd3-11eb-8ab4-6aac08db3cea.png)
![image](https://user-images.githubusercontent.com/51922806/105801057-3b25c000-5fd3-11eb-8b87-821a1a041d69.png)
![image](https://user-images.githubusercontent.com/51922806/105801063-411ba100-5fd3-11eb-897f-5a7750d94f18.png)
![image](https://user-images.githubusercontent.com/51922806/105801070-45e05500-5fd3-11eb-82e0-44c29b2a9e3c.png)

**Comment by PayneSnow** [comment]
这是obsidian的. 使用简悦+简悦·同步助手+ Obsidian打造一站式知识管理方案——http://kenshin.wang/blog/#/posts/25

**Comment by ttimasdf** [comment]
正好这两天简悦会员促销，闭着眼睛买了

**Comment by 88250** [comment]
简悦这边不太确定需要提供什么接口，后面我们先对接 Web Clipper https://github.com/siyuan-note/siyuan/issues/1266

我关闭了，谢谢提议。
