### ISSUE TITLE
html代码块中scipt标签解析错误，已允许代码块内脚本

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

已开启HTML代码块内脚本选项。

当在html代码块中输入`<script>xxxx</script>`等内容时，script标签解析错误，如图
![image](https://github.com/user-attachments/assets/5a904ed1-c9e7-4f68-aa88-9173318172ca)

生成的代码中，不仅两处，还多出了`</script></div>`内容，导致script内的脚本报错无法执行。
![image](https://github.com/user-attachments/assets/c2ea3fe0-ea46-48ea-a5b1-46402150c537)

关联帖子：https://ld246.com/article/1729935510467/comment/1729948008065?r=wilsons#comments

### Expected result

期望能正常生成script脚本内容

### Version environment

```markdown
- Version: 3.1.10
- Operating System: macos
- Browser (if used): not use
```

### Log file

no

**Comment by 88250** [comment]
我这里测试正常：

![image](https://github.com/user-attachments/assets/dd6e8b28-9fe0-4d1c-b66d-bc981ec1a726)

我是一次性外面写好然后粘贴进去的。

**Comment by TCOTC** [comment]
我这里逐个字符输入也正常，而且在 `alert(1)` 之后每输入一个字符都会弹一次窗口

**Comment by 88250** [comment]
弹窗是正常的……

**Comment by wish5115** [comment]
> 我这里测试正常：
> 
> 我是一次性外面写好然后粘贴进去的。

我知道了，这个html代码块是实时解析的，在解析过程中出现的问题，导致我后面怎么改都有问题，我是先粘贴网上的代码，再修改的，刚才的测试代码删了，无法重现刚才的问题了。

现在测试外面编辑好是没问题的。

**Comment by 88250** [comment]
好的，那就这样吧，我关闭了。

**Comment by TCOTC** [comment]
> 在解析过程中出现的问题，导致我后面怎么改都有问题

我这里也是控制台报错之后就会一直报错

**Comment by wish5115** [comment]
> Quote reply

嗯，再有问题再说。

**Comment by TCOTC** [comment]
咋还会引用 Quote reply 的，是 GitHub 的问题吗

![image](https://github.com/user-attachments/assets/f43da7ad-766f-4bfa-a48d-5eda300a3133)

**Comment by wish5115** [comment]
> 咋还会引用 Quote reply 的，是 GitHub 的问题吗
> 

不清楚耶，刚才点引用回复，就这样了
