### ISSUE TITLE
改进文档树操作逻辑（Alt+拖入和拖入的逻辑调换）

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12924]
### In what scenarios do you need this feature?

目前拖入是直接把文本合并到对应文档中比较反逻辑，应该改成按住ALT插入，直接拖拽是双链链接。  双链链接是一个高频动作，建议修改

### Describe the optimal solution

如上

**Comment by TCOTC** [comment]
确实是个常见的问题，有时候用户把文档拖入编辑器之后就回不去了。

真要改的话我觉得现在改是最好的，因为还没有用户习惯使用 Alt 拖拽。

**Comment by 88250** [comment]
块拖拽都是直接移动的，只有加 Alt 才是引用，编辑器里也是这个逻辑，不考虑改变了，感谢反馈。

**Comment by SaXz2** [comment]
> 块拖拽都是直接移动的，只有加 Alt 才是引用，编辑器里也是这个逻辑，不考虑改变了，感谢反馈。

那建议加一个按住ALT引用的指示器

**Comment by TCOTC** [comment]
主要是没地方加提示，只能当做一个隐藏用法了

**Comment by SaXz2** [comment]
> 主要是没地方加提示，只能当做一个隐藏用法了

我说的是拖入的时候在编辑器显示要拖入到哪里的指示器就跟直接插入一样有个光标指示的，跟最近改进的拖入文档插入一样

**Comment by TCOTC** [comment]
目前弄不出来：https://github.com/siyuan-note/siyuan/issues/12857#issuecomment-2437743709

**Comment by TCOTC** [comment]
这个 issue 实际上已经实现了 https://github.com/siyuan-note/siyuan/issues/13181
