### ISSUE TITLE
The Publishing service no longer support export

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#12928]
建议发布服务可以设置指定的笔记和目录及隐藏指定的插件等

### In what scenarios do you need this feature?

一般发布服务，不可能100%发布自己的笔记目录，毕竟笔记里通常有私人的东西。所以建议发布服务可以设置指定笔记和目录。

大多数插件并没有判断发布模式下不进行写操作，所以有些插件开放出去是比较危险的，建议发布时同样可设置屏蔽哪些插件。

其他功能屏蔽，比如导出功能等。

### Describe the optimal solution

虽然，通过js或css可以屏蔽或隐藏，但js和css太容易破解了，非常不安全。

建议能从内核层面直接不返回这些隐私数据较好。

**Comment by 88250** [comment]
* 发布内容粒度支持设置不考虑支持
* 插件调用的内核 API 在发布模式下有写入权限控制的，访客无法写入
* 稍后会去掉导出菜单

**Comment by wish5115** [comment]
> 稍后会去掉导出菜单

建议最好给个选项给用户选择是否显示。

> * 插件调用的内核 API 在发布模式下有写入权限控制的，访客无法写入

如果插件没走api呢？比如alist插件，发布服务下可以上传文件。

**Comment by 88250** [comment]
不加开关了，这个之前有一些反馈需要去掉，以多数需求为主。

最好改成用 API 操作文件，不然会有数据损坏风险。

**Comment by wish5115** [comment]
> 最好改成用 API 操作文件，不然会有数据损坏风险。

嗯，alist是因为直接上传到网盘，所以不走api。

**Comment by 88250** [comment]
哦哦，我以为是读写工作空间数据的，如果是单独读写其他地方的存储倒是没有问题，只存在你说的安全风险。

**Comment by luo-chuan** [comment]
> 不加开关了，这个之前有一些反馈需要去掉，以多数需求为主。

我觉得欠妥。没收到反馈可能是这部分用户还没注意到该功能被取消。
建议提供开关，允许用户设置是否允许导出。因为有的发布者就是希望读者能够下载已发布的内容。从另一方面讲，读者下载了内容，自然就会为了读取下载的文件而去安装思源软件，这无形中就增加了思源的用户数量。
