### ISSUE TITLE
资源文件搜索是否需要剔除文件名后的 id ？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12931]
不剔除 id 的话搜索原文件名带日期的文件根本搜不出来，但如果剔除 id 再搜索的话就没法按文件的插入时间搜索了。

![image](https://github.com/user-attachments/assets/ce850a58-619c-464d-8370-4ed350551949)

**Comment by 88250** [comment]
那就暂时不要动了吧，等后面看看是否有更多反馈。
