### ISSUE TITLE
数据库属性面板支持点击打开主键绑定块与悬浮显示浮窗

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12938]
需要先实现 #12910 和 #12031 或者实现 #12913 才有这个使用场景。

支持点击打开主键绑定块与悬浮显示浮窗：

![image](https://github.com/user-attachments/assets/9d2b95fc-4c58-4bc5-8436-6128a61cac39)

**Comment by 88250** [comment]
这个面板的入口都是块，所以没有必要再在这里打开块了。
