### ISSUE TITLE
图片地址用中文输入法输入需要按enter才能更改

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12936]
### In what scenarios do you need this feature?

发现图片地址用中文输入法输入文字需要按enter才能更改，不按enter，输入就是无效的
而直接用英文输入法，就立马修改了

### Describe the optimal solution

图片地址用中文输入法输入也能立即更改

**Comment by TCOTC** [comment]
这个是输入法特性，应该与思源无关

**Comment by Achuan-2** [comment]
> 这个是输入法特性，应该与思源无关

就是有点bug
明明输入了，但是没有生效

**Comment by TCOTC** [comment]
录屏看看

**Comment by Achuan-2** [comment]
![PixPin_2024-10-27_15-13-54](https://github.com/user-attachments/assets/a33e844e-8ee2-44b6-8107-7eed312d6047)

**Comment by TCOTC** [comment]
如果网络图片在本地没有缓存的话，目前好像是要关闭菜单才会请求？

**Comment by Achuan-2** [comment]
> 如果网络图片在本地没有缓存的话，目前好像是要关闭菜单才会请求？
> 
> 又好像不是。

本地图片也是一样的，随便在本地图片地址添加一个中文，就知道了

**Comment by TCOTC** [comment]
我这里没感觉有什么问题：


https://github.com/user-attachments/assets/4deee172-2a25-4ea9-b38c-e21be22fc2c3

**Comment by Achuan-2** [comment]
> 我这里没感觉有什么问题：
> 
>  default.mp4

可以用微软输入法试试，我微软输入法也是一样的

**Comment by TCOTC** [comment]
还真是微软输入法的问题。关联 #4826

**Comment by Achuan-2** [comment]
微信输入法也是同样问题

**Comment by Vanessa219** [comment]
已修改，不拉进版本了。
