### ISSUE TITLE
/资源 搜索与插入资源文件的异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12932]
1. 无法搜索到超过一层文件夹的资源文件（好像需要重启思源）
2. 插入的资源文件链接锚文本错误，比如锚文本应该是 `一层文件夹.txt` ，但实际是 `assets/.txt`

[视频.webm](https://github.com/user-attachments/assets/abc25c87-510d-48ff-8d04-c5268889ca9f)

关联 https://ld246.com/article/1728814976221/comment/1730003959220#comments

**Comment by 88250** [comment]
那个 一层文件夹.txt 是不是之前插入过，不然不应该出现在搜索里的，笔记本级资源文件不支持 /搜索

![image](https://github.com/user-attachments/assets/89b2fb91-8588-4346-9d4e-539e4f51a4ff)


我先关闭了，你确认后给我说声，多谢。

**Comment by TCOTC** [comment]
是 assets 文件夹哇，不是笔记本

![image](https://github.com/user-attachments/assets/81d77ba0-5180-44ed-90ed-567481ee356d)

**Comment by 88250** [comment]
哦哦，不好意思没注意，等会我测试看看。

**Comment by 88250** [comment]
1. 这个问题是因为用的 github.com/fsnotify/fsnotify 文件系统监听的库不是递归监听，新建文件夹以后需要再次 watch，思源中这种场景不多所以不考虑实现了
2. @Vanessa219 帮忙看看

**Comment by Vanessa219** [comment]
第二点已修复，不拉进版本了。

**Comment by TCOTC** [comment]
应该去掉路径，只保留文件名：

![image](https://github.com/user-attachments/assets/8847ab7c-382d-49cf-95af-40b6e12d107a)

**Comment by 88250** [comment]
这个考虑过的，但是觉得有路径信息更好。

**Comment by TCOTC** [comment]
对于插入文件的锚文本来说，路径是多余的，完整的路径可以在悬浮提示里看，或者在链接输入框复制。

默认的资源文件锚文本应该始终是文件名本身。

[视频.webm](https://github.com/user-attachments/assets/d1e08695-365a-4c45-a3bf-745d951e8735)

**Comment by 88250** [comment]
行嘛，稍后改改



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年10月30日(周三) 中午12:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] /资源 搜索与插入资源文件的异常 (Issue #12932)




 
对于插入文件的锚文本来说，路径是多余的，完整的路径可以在悬浮提示里看，或者在链接输入框复制。
 
默认的资源文件锚文本应该始终是文件名本身。
 
视频.webm
