### ISSUE TITLE
数据库视图与字段自定义图标更改光标类型、添加 hover 样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12934]
- [ ] 鼠标光标显示为默认箭头样式
- [ ] 添加 hover 样式，这个图标的背景色变灰（不包含输入框）

关联 #12915

![image](https://github.com/user-attachments/assets/de99fba7-9813-46d0-a258-8dd86e5263a2)

![image](https://github.com/user-attachments/assets/3579d6fb-28ee-4717-8f4b-655f3305c79f)

另外这里看上去没对齐：

![image](https://github.com/user-attachments/assets/b5566696-0761-46c7-a911-99dbf828f13d)

**Comment by Vanessa219** [comment]
有输入框的都没有背景
箭头， switch hover 是有边距的

![QQ_1730017285771](https://github.com/user-attachments/assets/e511ca32-70ca-4426-9a54-3f9907c12022)
