### ISSUE TITLE
新建文件名中不能包含部分特殊字符

### ISSUE THREAD

**Issue by ihyw** [siyuan-note/siyuan#1293]
### 描述问题 Describe the problem
今天群友提到了，新建文件名中不能包含部分特殊字符的情况

### 期待的结果 Expected result
可能大家更期待文件名可以无拘无束来取，或者这本身是设计上必须对部分字符进行限制的情况，可以稍作说明。

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/74618439/105802863-0ca9e400-5fd7-11eb-9e91-ea6317a6c7e4.png)

### 版本环境 Version environment

* 版本 Version：v0.6.7
* 操作系统 Operating system：Windows10

**Comment by 88250** [comment]
收到，v0.6.8 修复 https://github.com/siyuan-note/siyuan/issues/1271
