### ISSUE TITLE
修改和统一数据库术语

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12935]
- [x] `字段` `属性` `列` → 统一为 `字段`
- [x] `条目` `行` → 统一为 `条目`
- [x] “计算”行（中文）、顺序调整

先放着，有空再改。

---

- [x] 01
![8d854929f7a9536e51b439a892b90627](https://github.com/user-attachments/assets/dad95f21-6793-4ecc-b19b-e8ce64e26a32)

- [x] 02
![4fe6be147bc2bc49afe79f4cb8b83e80](https://github.com/user-attachments/assets/a18b5029-de6a-4063-ae53-e9350d516f44)

- [x] 03 数据库字段菜单
![image](https://github.com/user-attachments/assets/ea064868-ecaa-4aa3-93bb-b4f0e334fb5b)

- [x] 04 数据库条目右键菜单
![image](https://github.com/user-attachments/assets/3ca8c48f-7c3b-49b4-a656-a4308808d841)

- [x] 05 数据库视图菜单
![image](https://github.com/user-attachments/assets/04c61fbf-722c-4272-a669-ff0ccd8ac04c)

……

---

“计算”行（中文）：

备注：需要单独提一个新增“唯一值占比”的 issue

![63f16b727384cc38b23ab733cfc109f8](https://github.com/user-attachments/assets/82dde928-4ded-46ed-90e3-51b15cf86c1d)

```
无
条目数 ← 行计数
未填写 ← 空值计数
已填写 ← 非空值计数
值数量 ← 值计数
唯一值 ← 唯一值计数
未填写占比 ← 空值占比
已填写占比 ← 非空值占比
唯一值占比 (新增)
```

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
