### ISSUE TITLE
希望可以给无序列表中的文字块设置属性

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12933]
### In what scenarios do you need this feature?

搜索的时候我会关闭列表这些块的搜索，但是这样就会导致我设置了别名但是搜索的时候怎么都搜索不出来， [[ 也不能通过别名检索 ，如果开启就会有很多的重复内容。

### Describe the optimal solution

如上所述，希望增加鼠标设置列表项中的文字块属性的方式， 目前虽然可以通过快捷键的方式设置，但是用鼠标只能设置列表和列表项的别名，一定程度上有些繁琐

**Comment by TCOTC** [comment]
鼠标点一下其他的块，然后右键点击目标块：


https://github.com/user-attachments/assets/a6725cd7-aa61-405f-94f6-ca22af838001

**Comment by SaXz2** [comment]
学到了，我一直是看左侧标志点
