### ISSUE TITLE
.dragover 需要一点 border-radius

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12940]
直角感觉太硬了，需要一点圆角：

![image](https://github.com/user-attachments/assets/8403527e-0ec4-4790-a16b-6c4275316a29)

关联 #11751

**Comment by Vanessa219** [comment]
圆角+border 不好看，就不修改了。

**Comment by TCOTC** [comment]
直角很突兀啊

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Vanessa219** [comment]
圆角看上去很奇怪的，你可以改了看看。

**Comment by TCOTC** [comment]
我试了有一点圆角的样式，感觉比直角好

**Comment by Vanessa219** [comment]
直角比较直观。
