### ISSUE TITLE
Templates for docs/database rows.

### ISSUE THREAD

**Issue by zetashift** [siyuan-note/siyuan#12945]
### In what scenarios do you need this feature?

When creating a new doc for a database that has certain rows pre-filled.
E.g. I'm making a new `TV Show` doc, and I want to have the doc icon/cover pre-filled and the `total episodes watched` fields quickly defined.

### Describe the optimal solution

I'm not entirely sure, maybe a YAML frontmatter with the database name?

### Describe the candidate solution

This one I'm not sure about!

### Other information

This would be a great replacement as well for people that like PKMs like `Anytype` or `Capacities`.

**Comment by TCOTC** [comment]
Related to #11479 #11506

**Comment by 88250** [comment]
Currently, you can consider batch filling by dropping down cells.

![image](https://github.com/user-attachments/assets/aad33421-6c1b-4ed5-8a8e-1d8ffba93631)

**Comment by zetashift** [comment]
> Related to #11479 #11506

Ah sorry! My searching didn't bring up those isses.

> Currently, you can consider batch filling by dropping down cells.

Thank you, for my use case this isn't practical, because I tend to add just a single row at a time, with a (big) gap of time until the next one. But this is handy indeed.
