### ISSUE TITLE
支持转换列表项块类型

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12942]
> 从 https://www.bilibili.com/video/BV1i51YYrEFb?t=986.3 观察到的需求

01 比如选中无序列表中间的几个列表项，然后转换为任务列表，同时将 一个**无序**列表块 **断开**成相邻的 一个**无序**列表块+一个**任务**列表块+一个**无序**列表块

![image](https://github.com/user-attachments/assets/0750e4f8-7701-4bc2-abba-39b2cb2a0343)

↓

![image](https://github.com/user-attachments/assets/ea308c2f-e89b-4e78-b033-c37edcb68b11)

比如分别选中，就分别断开：

![image](https://github.com/user-attachments/assets/296d3d9f-bfdb-4dc1-9fd1-1feb9671dc12)

↓

![image](https://github.com/user-attachments/assets/5c529378-e468-4916-b9f5-2b1048ce1102)

---

02 还有就是选中整个列表块中的所有列表项时也可以提供转换（等效于选中列表块转换）

**Comment by 88250** [comment]
1. 手动断开吧
2. 选中所有列表项块不等价于选中父列表块
