### ISSUE TITLE
在本地浏览器打开失败

### ISSUE THREAD

**Issue by ihyw** [siyuan-note/siyuan#1294]
### 描述问题 Describe the problem
在本地浏览器打开思源失败，图标一直转动，浏览器控制台错误如下

### 期待的结果 Expected result
可以实现正常登录

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/74618439/105804423-be96df80-5fda-11eb-92eb-9ce5d18b01e7.png)

### 版本环境 Version environment

* 版本 Version：v0..6.7
* 操作系统 Operating system：Windows10
* 浏览器（如果使用）Browser (if used)：New Microsoft Edge

**Comment by 88250** [comment]
068 修复，谢谢。
