### ISSUE TITLE
代码注释使用中英双语

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12947]
我记得之前好像有外国人抱怨注释很多中文？

- 关联 #7814

**Comment by 88250** [comment]
这个没法考虑这么多了，毕竟关联到的 issues 也基本都是中文的。

**Comment by TCOTC** [comment]
有的注释能顺手改的话还是加一下英文吧

![image](https://github.com/user-attachments/assets/c57474ee-8e93-4955-8dc4-023d584bf6c4)

**Comment by 88250** [comment]
你有空的话顺手帮忙 PR 翻译一下吧……

**Comment by TCOTC** [comment]
那先把这个 issue 开着吧，assign 我，我有空再改

**Comment by 88250** [comment]
你直接开 PR 就行了。

**Comment by 88250** [comment]
自己记录一下吧，请用思源笔记 😂
