### ISSUE TITLE
Display document title in data history preview area

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12948]
文件历史显示标题

选中文本不小心按 F2 修改了文档标题 #11632 的情况下，想通过文件历史查看原来的文档标题，但发现文件历史里没有显示标题。

只有窗口左上角会显示最新的标题，无法查看旧标题是什么：

[视频.webm](https://github.com/user-attachments/assets/32d242bb-52cc-4920-9ab6-92fdfa5fb2a6)

希望在这里显示标题：

![image](https://github.com/user-attachments/assets/693ff05a-6067-4342-a4b0-8a9651e997b5)

两个入口：

- 数据历史 - 文件历史
- 文档树 - 文档右键菜单 - 文件历史

**Comment by 88250** [comment]
数据历史 - 文件历史 这个全局入口没有问题，左侧栏里面已经有标题了。

**Comment by TCOTC** [comment]
左侧栏是个按钮，复制不了标题

**Comment by 88250** [comment]
发现快照对比也没有显示标题，一起加一下吧。
