### ISSUE TITLE
为非绑定块条目增加一个数据库字段编辑面板

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12941]
目的是为非绑定块条目提供一个与块属性面板一样方便显示与编辑字段的方式。

目前的块属性面板是这样的：

<img src="https://github.com/user-attachments/assets/d2c29f7d-7ef0-41db-823c-11e424055980" style="width: 40%;">

需要增加的“数据库字段编辑面板”是这样的，只保留查看与编辑条目字段的功能：

<img src="https://github.com/user-attachments/assets/ae728a23-c1b5-4492-b22f-a707415c2ccc" style="width: 40%;">

---

需求：

- #12031 中的非绑定块条目需要该面板
- #12101 中的非绑定块条目需要该面板
- #12910 中的非绑定块条目需要该面板

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by 88250** [comment]
不考虑了，非块数据仅支持在视图中编辑。

**Comment by TCOTC** [comment]
隐藏字段的话就没法编辑了

**Comment by 88250** [comment]
可以开一个没有隐藏的视图编辑

**Comment by TCOTC** [comment]
操作路径太长了，新建视图→找到条目→编辑字段，远不如直接 Shift+点击 打开面板编辑方便

**Comment by 88250** [comment]
整个插件吧

**Comment by TCOTC** [comment]
我觉得应该原生实现。

思源的数据库缺的就是这个，不能像其他产品那样可以直接打开一个页面编辑所有字段。

**Comment by heeeeeeee-8** [comment]
不要这个不考虑那个考虑用插件，你可以慢，但不能都落下，也不能一味的轻装上阵，既然其他笔记软件高频存在的功能，就该也去开发，试问主键打开悬浮窗竖排展示其内容不是增加对工作的便利和视觉浏览的直观体现吗，这是用户高频的、基本的需求，希望尽快开发搬上日程

**Comment by TCOTC** [comment]
@88250 实现一下这个吧

Notion 在新建条目无法默认填充的情况下（比如文本“不为空”），会在右侧弹出文档界面让用户编辑字段。我觉得思源也可以参考这样实现，弹出一个字段编辑面板，而不是直接过滤掉再弹出消息提示。

<img width="1557" height="936" alt="Image" src="https://github.com/user-attachments/assets/13ec2bdc-4627-44e2-a247-4aeff5673d38" />

**Comment by 88250** [comment]
暂时是没有开发资源搞这个了，欢迎各位 PR 贡献

**Comment by 88250** [comment]
已经在 https://github.com/siyuan-note/siyuan/issues/11371 中实现。
