### ISSUE TITLE
Document icons support the use of dynamic icons

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12943]
文档图标支持使用动态图标

关联 #12939

交互参考 Wolai：

![image](https://github.com/user-attachments/assets/eb14caf3-81b5-41d0-b34a-f8565b486fd3)

**Comment by TCOTC** [comment]
另外还有个需求：type 8 支持使用模板来显示文本

**Comment by 88250** [comment]
这个目前只考虑在文档图标上实现，否则导出会有问题。

**Comment by Achuan-2** [comment]
> 另外还有个需求：type 8 支持使用模板来显示文本

目前type 8不适合输入太多文字的，5个字感觉就是极限了，再多也看不清

**Comment by TCOTC** [comment]
不用输入太多文本，几个字就行，比如 “第 X 天”

**Comment by Achuan-2** [comment]
> 不用输入太多文本，几个字就行，比如 “第 X 天”，比如查询某个任务列表块的完成进度 “XX%” 。

另外我发现像%、#之类的符号，输入会截断URL，需要处理下
* 空格: `%20`
* %: `%25`
* +: `%2B`
* /: `%2F`
* ?: `%3F`
* #: `%23`
* &: `%26`
* \=: `%3D`

**Comment by TCOTC** [comment]
> 另外我发现像%、#之类的符号，输入会截断URL，需要处理下

符号在渲染的时候用 HTML 字符实体

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/pull/12939

**Comment by Achuan-2** [comment]
动态图标使用的时候，可以直接用`api/icon/getDynamicIcon`，例如`api/icon/getDynamicIcon?color=red&type=7&lang=zh_CN`，这样用伺服的时候也能用

**Comment by Achuan-2** [comment]
我觉得3.1.11可以先支持dailynote模板设置动态图标（目前dailynote模板还不支持用网络图标），文档添加动态图标的界面下个版本再出

**Comment by TCOTC** [comment]
👉 #12926

**Comment by Achuan-2** [comment]
需要改进下：
如果文档图标本来就是动态图标，希望点击动态图标设置界面，会自动加载之前的选项，方便修改，而不是所有选项都要重新设置
![PixPin_2024-11-09_17-50-37](https://github.com/user-attachments/assets/c4f919f1-f521-4d7c-b648-0df60ed2b0a3)

**Comment by TCOTC** [comment]
还有格式化这里，需要根据选择的语种显示不同的语言（而不是 `简体/English`）：

![image](https://github.com/user-attachments/assets/2edf5b48-2620-4c18-85b3-d3025f5b4236)

**Comment by SaXz2** [comment]
BUG反馈： 使用模版后文档树与页面图标颜色不一致
![Clip_2024-11-10_09-44-41](https://github.com/user-attachments/assets/644e188b-c78e-4128-abad-1b58c5040d36)

**Comment by 88250** [comment]
@SaXz2 我这里无法重现，麻烦录屏看下

**Comment by TCOTC** [comment]
还有页签图标的圆角看起来怪怪的，我建议去掉圆角：

![image](https://github.com/user-attachments/assets/e9ccf8db-dcc7-482d-9457-8237235f7211)

**Comment by SaXz2** [comment]
> @SaXz2 我这里无法重现，麻烦录屏看下

https://github.com/user-attachments/assets/c9a715d8-1af5-4346-b212-d6504cb42864

[Todo2.md](https://github.com/user-attachments/files/17691337/Todo2.md)
模版文件

**Comment by Achuan-2** [comment]
> > @SaXz2 我这里无法重现，麻烦录屏看下
> 
>  2024-11-10.20-08-39_batch.mp4 
> [Todo2.md](https://github.com/user-attachments/files/17691337/Todo2.md) 模版文件

直接用`&` 试试，不要用HTML实体编码

**Comment by SaXz2** [comment]
> > > @SaXz2 我这里无法重现，麻烦录屏看下
> > 
> > 
> > 2024-11-10.20-08-39_batch.mp4
> > [Todo2.md](https://github.com/user-attachments/files/17691337/Todo2.md) 模版文件
> 
> 直接用`&` 试试，不要用HTML实体编码

直接用&的话就生成不了图标了

**Comment by Achuan-2** [comment]
> > > > @SaXz2 我这里无法重现，麻烦录屏看下
> > > 
> > > 
> > > 2024-11-10.20-08-39_batch.mp4
> > > [Todo2.md](https://github.com/user-attachments/files/17691337/Todo2.md) 模版文件
> > 
> > 
> > 直接用`&` 试试，不要用HTML实体编码
> 
> 直接用&的话就生成不了图标了

我这边用&是正常的
![PixPin_2024-11-10_22-25-54](https://github.com/user-attachments/assets/618b269a-a868-412e-9f6c-60ade0836c85)
URL直接用`&amp;`会被截断，因为这个不是URL编码，之所以文档图标可以显示，可能是额外做了编码转换，而文档树没有额外处理

**Comment by AvoidantPerDis** [comment]
![image](https://github.com/user-attachments/assets/58b84774-7995-4642-b151-4abdf907b47c)
这里的颜色能自定义吗 我想改成自己常用的

**Comment by Achuan-2** [comment]
@

> ![image](https://private-user-images.githubusercontent.com/154863885/384767402-58b84774-7995-4642-b151-4abdf907b47c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyOTUyNjUsIm5iZiI6MTczMTI5NDk2NSwicGF0aCI6Ii8xNTQ4NjM4ODUvMzg0NzY3NDAyLTU4Yjg0Nzc0LTc5OTUtNDY0Mi1iMTUxLTRhYmRmOTA3YjQ3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMzE2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDljZTZlMDU0ZWE1NTJjNWVlZTNlODAzMjA2Njk1OGMyODRkN2YxZjk4ZTQ1ODk5MmFlNGNlMzJlNzA3MTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UcZoQRSnFTQAwzCPZyW1Mok0ZUssmVCvLF6UZF1kdtc) 这里的颜色能自定义吗 我想改成自己常用的

@Vanessa219 ，我觉得可以像自定义文档图标一样，颜色变量暴露出来，通过js代码片段来修改颜色变量

**Comment by AvoidantPerDis** [comment]
能不能记忆自定义的内容啊 包括日期 文字颜色啥的 每次都要重新填

**Comment by TCOTC** [comment]
输入框还有一点布局问题：

[video.webm](https://github.com/user-attachments/assets/62d8c009-5b3d-46d9-ac2b-3b8b3e349815)

**Comment by Vanessa219** [comment]
颜色在输入框中输入 #色值即可，已修改下列问题
* [X] 回填
* [X] 格式化
* [X] tab 圆角
* [X] 位置偏移

**Comment by Achuan-2** [comment]
@Vanessa219 回填会自动往颜色里添加`#`，如果填入的是自带的变量比如`blue`就会有问题
![PixPin_2024-11-13_10-23-57](https://github.com/user-attachments/assets/dbfca58b-1e6b-47ee-8644-fd036ae3d906)

![PixPin_2024-11-13_10-23-30](https://github.com/user-attachments/assets/394beaf0-1e5f-4981-9ca8-782ee4de15be)

**Comment by Vanessa219** [comment]
统一使用 # 号开头的色值代码，不然不好处理。

**Comment by Achuan-2** [comment]
> 统一使用 # 号开头的色值代码，不然不好处理。

好吧，相当于文档图标直接砍掉了直接输入color=red这种用法吗？（虽然我的意思是支持用这种用法）

那我直接写个代码片段，把文档图标的动态图标给替换成自己需要的吧

**Comment by Achuan-2** [comment]
js代码片段写好了，发现用js直接更改background值，会自动变为rgb值，末尾还会加上"；"
```js
(async () => {

    // 定义观察DOM变化的函数
    function observeDomChange(targetNode, callback) {
        const config = { childList: true, subtree: true };
        const observer = new MutationObserver((mutationsList) => {
            for (const mutation of mutationsList) {
                if (mutation.type === 'childList') {
                    callback(mutation);
                }
            }
        });
        observer.observe(targetNode, config);
        return observer;
    }

    // 定义颜色替换的逻辑
    function updateColors() {
        // 定义新的颜色数组
        const newColors = [
            "#d13d51", // red
            "#3eb0ea", // blue
            "#eec468", // yellow
            "#52E0B8", // green
            "#a36cda", // purple
            "#f183aa", // pink
            "#f3865e", // orange
            "#576574" // grey
        ];

        const colorSquares = document.querySelectorAll('.fn__flex.emoji__dynamic-color .color__square');
        colorSquares.forEach((square, index) => {
                square.style.backgroundColor = newColors[index];
        });
        console.log("颜色替换")

    }

    // 选择要观察的节点（通常是整个文档或特定的容器）
    const targetNode = document.body;

    // 开始观察DOM变化，并在检测到.color__square元素时运行updateColors
    observeDomChange(targetNode, (mutation) => {
        // 监听代码列表的弹窗事件
        if (mutation.target.classList.contains("fn__flex")) {
            const dialog_emoji_open = document.querySelector('.b3-dialog--open[data-key="dialog-emojis"]');
            console.log(dialog_emoji_open)
            if (dialog_emoji_open) {
                updateColors();
            }
        }

    });


})();


```
![PixPin_2024-11-13_13-01-09](https://github.com/user-attachments/assets/2057dd8c-0500-4499-8883-750802c45d73)

**Comment by TCOTC** [comment]
@Vanessa219 需要给 .emojis__tabbody 元素增加 `scrollbar-gutter: stable;` 才能避免偏移，不过左右两边的宽度看起来会不一样：

![image](https://github.com/user-attachments/assets/7df53276-ed86-4b59-bf58-51e7557e6a15)

目前输入框还是有偏移：

[video.webm](https://github.com/user-attachments/assets/28baf2fb-8596-4b22-a3af-4fc406d158a5)

**Comment by Vanessa219** [comment]
侧边有点不好看，先不改了。
