### ISSUE TITLE
改进数据库调整列宽功能

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12952]
Wolai 这个调整列宽的功能和交互真的太完美了，对[强迫症](https://github.com/siyuan-note/siyuan/issues/11022)极其友好：

- [ ] 调整列宽时会悬浮显示实际的列宽值，列宽等于左侧列的列宽时有线条指示、会自动吸附：

   [视频.webm](https://github.com/user-attachments/assets/0fbe2392-07bb-4b41-a859-e5b03432c4e6)

- [ ] 双击自动调整列宽至合适的值：

   [视频.webm](https://github.com/user-attachments/assets/7d0c2ae0-a438-44e4-8b08-fc75543f3016)

- [ ] 右键之后有更多功能：

   [视频.webm](https://github.com/user-attachments/assets/ce84ee42-357b-4333-badc-276cc5db73f0)

- [ ] 可以将列宽单次同步至其他相同类型的视图（表格视图）：

   [视频.webm](https://github.com/user-attachments/assets/2d049604-b8f9-49c3-844e-42829f310a22)

**Comment by cordinGH** [comment]
这个双击有点赞啊，喜欢

**Comment by 5kyfkr** [comment]
同步列宽和双击设置太好了，支持

**Comment by 88250** [comment]
目前不考虑了，如果后续反馈多再考虑。

**Comment by Jerry-0202** [comment]
> 目前不考虑了，如果后续反馈多再考虑。

醒醒，起来考虑啦

**Comment by TCOTC** [comment]
> 可以将列宽单次同步至其他相同类型的视图

关联需求：

<img width="396" height="378" alt="Image" src="https://github.com/user-attachments/assets/52d8cc96-e222-4cd3-9aea-8a668e524740" />

**Comment by HaoCeans** [comment]
这个太喜欢了，强烈支持！！！！

**Comment by HaoCeans** [comment]
为什么关闭了，快打开！！！

**Comment by 5kyfkr** [comment]
只求新增列不要重新在其他视图调整列宽，太离谱了这个体验

**Comment by 88250** [comment]
@TCOTC @5kyfkr 也就是说目前最迫切的需求是同步列宽到其他视图？

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/11022 中实现同步列宽

**Comment by Achuan-2** [comment]
支持改进

**Comment by Achuan-2** [comment]
> 只求新增列不要重新在其他视图调整列宽，太离谱了这个体验


希望新建表格视图，默认用第一个视图的列宽，否则每次新建视图都得调整
或者也可以是新建视图时，使用当前显示的表格视图的列宽

我个人倾向于后者

目前只能通过复制为副本来复制视图列宽，还是太麻烦了，因为复制为副本之后还需要清除各种条件

**Comment by TCOTC** [comment]
> 默认用第一个视图的列宽

我反对，应该是完全独立的视图，使用默认列宽

**Comment by Achuan-2** [comment]
> 我反对，应该是完全独立的视图，使用默认列宽

那这样的话，建议新建视图，列顺序也不要使用第一个视图的列顺序，每次新建视图，都去调整列顺序吧

---


以我的博客数据库为例，新建不同视图只是为了分类，一个列宽度确定下来，几乎就不会再调整

<img width="1736" height="834" alt="Image" src="https://github.com/user-attachments/assets/4567aaa9-7f1c-4ca0-92e8-6e816e66f507" />

新建视图使用默认列宽的场景在哪呢？符合大多数人的使用场景吗？

**Comment by TCOTC** [comment]
Notion 也是使用首个同类视图的列宽，那我不反对了，有用户问的时候就说 Notion 也是这样的

但我要求加一个“恢复默认列宽”的选项

**Comment by 88250** [comment]
> 希望新建表格视图，默认用第一个视图的列宽

ok

**Comment by 88250** [comment]
@TCOTC 恢复默认列宽的场景是啥？

**Comment by TCOTC** [comment]
场景不好说，但就是想要有能够**恢复默认**的选项，有点像表格这个，但又不完全像。

如果拖拽的时候能像 wolai 那样实时显示列宽的话，不用添加选项也行，手动拖拽到 200px 就够了

<img width="930" height="640" alt="Image" src="https://github.com/user-attachments/assets/77bed2ab-8f94-4255-80b6-30eb90b89320" />

**Comment by 88250** [comment]
没有使用场景的话暂时不考虑了



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2025年7月12日(周六) 中午12:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 改进数据库调整列宽功能 (Issue #12952)


TCOTC left a comment (siyuan-note/siyuan#12952)
 
场景不好说，但就是想要有能够恢复默认的选项，有点像表格这个，但又不完全像。
 
如果拖拽的时候能像 wolai 那样实时显示列宽的话，不用添加选项也行，手动拖拽到 200px 就够了
 image.png (view on web)

**Comment by Jerry-0202** [comment]
> 没有使用场景的话暂时不考虑了
> […](#)

好理性的D

**Comment by TCOTC** [comment]
支持设置精确列宽

![Image](https://github.com/user-attachments/assets/80917882-8f13-435b-934e-e754b0a8773c)

**Comment by TCOTC** [comment]
### 01

希望鼠标左键按下 av__widthdrag 之后就用 tooltip 显示宽度值，目前得微微移动一下鼠标才显示

https://github.com/user-attachments/assets/c326f173-1ef8-40f5-8656-e37ac9df793e

**Comment by TCOTC** [comment]
### 02

把字段菜单里的选项移除，仅保留 av__widthdrag 的右键菜单里的选项

<img width="632" height="677" alt="Image" src="https://github.com/user-attachments/assets/376bd37c-8db0-43d8-99b5-c3cca75cb519" />

<img width="385" height="401" alt="Image" src="https://github.com/user-attachments/assets/f66c79fd-373f-473d-b0f7-36fda22b4738" />

移动端我测试过了右键菜单可以触发（点击一次之后长按一下比较容易触发），列宽也能拖拽。所以字段菜单里的选项没有保留的必要

<img width="1239" height="950" alt="Image" src="https://github.com/user-attachments/assets/1deefa4b-35dd-41ea-bf62-f56f5038e76f" />

**Comment by 88250** [comment]
01-02 done
