### ISSUE TITLE
改进数据库底部 `加载更多` 和 `添加` 的样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12950]
思源目前是两个不同宽度的按钮并列、按钮里面套按钮，样式感觉相当丑：

![image](https://github.com/user-attachments/assets/c5f96905-aca0-4991-87b1-b61a6a7aa180)

像 Notion 这样分别放一行，配置显示条目数的按钮放在右边，我觉得更好看，点击区域更大也更方便：

![image](https://github.com/user-attachments/assets/2b6e999e-26e7-43be-aa26-fc63d72947a2)

另外我建议跟这里统一，把 `添加` 改为 `添加条目`：

![image](https://github.com/user-attachments/assets/8c47bd0a-7976-433d-aef0-f54c50733006)

**Comment by Vanessa219** [comment]
正常情况下不会2个同时高亮

![QQ_1730079262121](https://github.com/user-attachments/assets/25a217d5-3455-4b1b-a823-166bdd9f41f8)

使用 notion 的设计会比较占位置，且页数调整按钮离得太远了。文案可以修改一下。

**Comment by TCOTC** [comment]
但是 加载更多 按钮里面再套一个按钮看起来真的很奇怪

**Comment by Vanessa219** [comment]
除了 notion 这个设计再看看有没有其他更合适的吧。
