### ISSUE TITLE
自定义表情加载时快时慢

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12954]
关联 https://ld246.com/article/1730085736366

[视频.webm](https://github.com/user-attachments/assets/a6e40221-6c79-4707-beb0-6c85d41ae5d4)

**Comment by zuoez02** [comment]
图标多了，DOM渲染的压力就会很大，最好是能够做个虚拟滚动的效果

**Comment by SaXz2** [comment]
感觉是小事，我的图标有3000多个，加载起来相比Obsidian的icons插件已经是质的飞跃了，目前体验上非常不错，如果改进的话，只需要改进一下自定义表情滚动卡顿的问题就足够了，但是像我这样塞几千个的用法也很少见了。一般也是搜索使用并没有明显的问题
![Clip_2024-11-02_13-15-36](https://github.com/user-attachments/assets/d3afa978-ebad-4ff1-bae3-4d7a5c6bc66c)

**Comment by 88250** [comment]
就这样吧，不考虑改动了。
