### ISSUE TITLE
Add `renderElement` and `blockElement` for `open-noneditableblock`

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#12955]
### In what scenarios do you need this feature?

这个EventBus是在 #8374 中添加的，然后在 #12918 里面我提到想要添加打开块的信息。因为触发事件后获取到的的protyle并不是打开的块的，而是整个文档的，就像这样
![image](https://github.com/user-attachments/assets/ec825bef-46d8-4891-a43b-c946a69accfb)
可以看到block的id是和rootID是一样的，也就是说目前没有任何方式能够判断打开的是哪个块，以及块的类型是什么

### Describe the optimal solution

我不知道protyle这个是不是bug，如果是的话直接改一下就行，但是这样的话行内公式之类的好像也没办法很好地处理。

最好还是能够添加另一组信息来指示一下打开的是哪个块，或者块的基础信息（其实直接附上data-type就行，NodeMathBlock/inline-math/NodeHTMLBlock/NodeBlockQueryEmbed，就能知道打开的是哪种块），然后最好是除了inline-math以外就能给出块id，这一点可能就是要修一下protyle

**Comment by WingDr** [comment]
补充一下，目前 [siyuan-plugin-math-enhance插件](https://github.com/zxhd863943427/siyuan-plugin-math-enhance) 是通过弹出窗口的标题判断的，感觉有点抽象了xs

**Comment by Vanessa219** [comment]
不是 bug，可以获取到点击的行内元素和块元素。你看看需要哪一个？

**Comment by WingDr** [comment]
> 不是 bug，可以获取到点击的行内元素和块元素。你看看需要哪一个？

我不知道以后有什么需求，现在的话可以看怎么样给一下点击的元素的data-type（就像上面说的那样），然后给一下所在块的id（如果本身是块级的就给它自己的id，如果是行级的就给所在块的），感觉这样比较好

**Comment by Vanessa219** [comment]
直接给点击的元素和块的 Element 吧，这些都可以从 DOM 上面取到。

**Comment by WingDr** [comment]
> 直接给点击的元素和块的 Element 吧，这些都可以从 DOM 上面取到。

okk，也行
