### ISSUE TITLE
支持中英文符号自动补全

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12957]
### In what scenarios do you need this feature?

请支持对对各类型的括号和单双引号、书名号 `（),{}, [], "", ''`，并且光标调到括号的中间或者自动换行

### Describe the optimal solution

这一优化可以极大的提升写作编辑的体验，请D大考虑一下，谢谢D大

![image](https://github.com/user-attachments/assets/d5dd157b-278d-4b45-ac9a-c9223bbe8bc7)

**Comment by TCOTC** [comment]
我觉得应该解决的问题是有些输入法的符号补全在思源里不起作用

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/4826

**Comment by TCOTC** [comment]
对。大部分输入法是有符号补全功能的，但在思源里会不起作用。
