### ISSUE TITLE
数据库搜索时不需要隐藏 .av__views 上的按钮

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12966]
目前在输入了文本之后是不隐藏的，那么应该从点击了搜索按钮开始就不隐藏，直到关闭搜索：

[视频.webm](https://github.com/user-attachments/assets/7c46bc92-3739-4c88-91fb-ef4aa5ad9f7e)

**Comment by Vanessa219** [comment]
已改进，不拉进版本了

**Comment by TCOTC** [comment]
搜索文本清空之后会闪一下：

[视频.webm](https://github.com/user-attachments/assets/7cbcb5f6-056a-4a90-8496-04787318ada9)

**Comment by Vanessa219** [comment]
看上去是正常的，是最新代码么？

https://github.com/user-attachments/assets/7aa67d9f-8fbe-4075-b5f2-2e495d37a3e9

**Comment by TCOTC** [comment]
我用的是最新的 dev 版

**Comment by 88250** [comment]
鼠标在这个数据库区域内的话不会闪，在外面的话会闪。
