### ISSUE TITLE
希望代码块增加CodeQL语法高亮支持

### ISSUE THREAD

**Issue by xzajyjs** [siyuan-note/siyuan#12964]
### In what scenarios do you need this feature?

写CodeQL代码相关笔记

### Describe the optimal solution

增加语法高亮支持

**Comment by TCOTC** [comment]
新增高亮语法需要上游 hljs 支持，思源增加不了

**Comment by 88250** [comment]
请到 https://github.com/highlightjs/highlight.js/issues 这里提出特性请求，谢谢。
