### ISSUE TITLE
右键粘贴菜单添加去除空格、去除换行按钮

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#12969]
### In what scenarios do you need this feature?

![PixPin_2024-10-29_22-23-09](https://github.com/user-attachments/assets/efeaf261-3a13-4c9a-b78d-6c46439319b9)

从pdf复制跨行文字，会存在多余空格和换行

如果思源本身能提供去除空格、去除换行功能的话，可以减少繁琐的粘贴后调整步骤

### Describe the optimal solution

右键粘贴菜单添加去除空格、去除换行按钮

**Comment by TCOTC** [comment]
感觉多余了，适合插件实现

**Comment by 88250** [comment]
考虑插件实现吧。
