### ISSUE TITLE
数据库设置排序后，新增条目会被自动筛选掉

### ISSUE THREAD

**Issue by V7kb** [siyuan-note/siyuan#12965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题

https://github.com/user-attachments/assets/1fb155ce-287a-4d1f-a6a1-62a8d29057f9

### Expected result

增加排序后，新增行也不会被筛选掉，因为“排序”改变的是此表条目的顺序，而非过滤此表  或者  让用户有足够时间编辑。现在来不及编辑就自动过滤掉了

### Screenshot or screen recording presentation

1

### Version environment

```markdown
- Version: v3.1.10
- Operating System: win11
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
这是设计如此：如果同一字段上同时存在过滤和排序，则不会自动填充默认值，所以会被过滤掉。

**Comment by TCOTC** [comment]
这个设计有缺陷，视图排序只应该影响如何判断“上一个条目”，参考 https://github.com/siyuan-note/siyuan/issues/11966

**Comment by 88250** [comment]
等后面看看能不能改吧。

**Comment by ZSCN2024** [comment]
请问这个问题还没有修改吗？新增条目，闪一下就消失了，根本来不及填充内容

**Comment by TCOTC** [comment]
请关注  https://github.com/siyuan-note/siyuan/issues/11966 和https://github.com/siyuan-note/siyuan/issues/12270

**Comment by ZSCN2024** [comment]
> 请关注 #11966 和 #12270

刚发现是另外的问题，已发issues https://github.com/siyuan-note/siyuan/issues/13823
