### ISSUE TITLE
Improve parsing of YAML Front Matter when importing Markdown

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#12962]
导入markdown文档时yaml区里的属性导入不正确

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

把思源的一个文档导出为markdown文件，文档的标签输出到了markdown文件的yaml区，导入该md文件，tags变成了自定义属性
思源笔记原文档：
![image](https://github.com/user-attachments/assets/7bb36213-e9f8-4118-893b-0e2e881af05a)
导出后的md文件：
![image](https://github.com/user-attachments/assets/b111036e-d4e3-4869-b639-7864e49311be)
导入md后生成的文档：
![image](https://github.com/user-attachments/assets/9cc64344-250a-44d8-b289-fb7e40992e14)

### Expected result

- tags应导入为文档标签，而不是文档自定义属性。
- date应作为文档的创建时间，而不是文档自定义属性。
- lastmod应作为文档的更新时间，而不是文档自定义属性。
- 有title属性时，应将title作为文档名，忽略文件名。
别名、命名、书签、备注等内置属性也应进行特殊处理。

### Version environment

```markdown
- Version: 3.1.10
- Operating System: win10
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
> 别名、命名、书签、备注等内置属性也应进行特殊处理。

这个不考虑了，导入 Markdown 主要用于其他应用数据导入，思源自身的数据导出导入最好使用 .sy 而不是 .md。

**Comment by TCOTC** [comment]
这是为了方便将其他软件导出的 Markdown 迁移到思源，而不是为了从思源导出 Markdown 再导入。

在导入思源前用脚本处理一下 Markdown 就可以方便地为文档添加内置属性：别名、命名、书签、备注。

**Comment by UltramarineSky** [comment]
> 在导入思源前用脚本处理一下 Markdown 就可以方便地为文档添加内置属性：别名、命名、书签、备注。
请问这个是要怎么样处理

**Comment by TCOTC** [comment]
你可以导出看看 别名、命名、书签、备注 的格式，怎么处理问 AI 就行了
