### ISSUE TITLE
The flashcard will be seem as using space when i use ctrl+e to open dock app！当我使用闪卡时，点击ctrl+e，会被看作在闪卡中使用空格！！I find a bug finally！！！！！

### ISSUE THREAD

**Issue by TangQi001** [siyuan-note/siyuan#12967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/a9454141-0896-40f4-b57e-ddfc43c35d8c)
首先把闪卡放到文档栏中
然后按ctrl+e
![image](https://github.com/user-attachments/assets/474b69db-6caf-4238-9c8b-245b8d474aee)
无论点击哪个按键，都会被看作是在后面的闪卡页面中按空格的效果

![image](https://github.com/user-attachments/assets/a9454141-0896-40f4-b57e-ddfc43c35d8c)
First, put the flashcard into the document column.
Then press ctrl+e.
![image](https://github.com/user-attachments/assets/474b69db-6caf-4238-9c8b-245b8d474aee)
No matter which key is clicked, it will be regarded as the effect of pressing the space key on the subsequent flashcard page.

### Expected result

嘀嘀嘀

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/13bfa056-cc5c-44d6-be4d-74a081a4e214)
没an按之前
![image](https://github.com/user-attachments/assets/6a153429-d45d-474b-a48c-e48e33f05054)
按了之后，到了下一个闪卡了，同时还没有跳到我点击的页面

### Version environment

```markdown
- Version: latest
- Operating System: windows
- Browser (if used):
```

### Log file

eeeeee
[system-log (5).zip](https://github.com/user-attachments/files/17557889/system-log.5.zip)

**Comment by TCOTC** [comment]
新建一个工作空间然后录屏操作一下看看吧

**Comment by TCOTC** [comment]
我这里可以复现了，在刷卡时点击最近的文档里的选项，思源会自己刷卡

**Comment by Vanessa219** [comment]
感谢反馈，不加入版本了。
