### ISSUE TITLE
坚果云webdav无法正常使用

### ISSUE THREAD

**Issue by twtccw** [siyuan-note/siyuan#1296]
正确输入坚果云的webdav链接以及账号，应用密码后，点击确定无反应。
多次尝试及长时间等待均无反应。思源版本为0.6.7

**Comment by 88250** [comment]
链接地址需要带文件夹路径，不然可能会被 API 调用受限。

**Comment by twtccw** [comment]
感谢回复。https://dav.jianguoyun.com/dav/Siynote/，这是我设置的链接，
且已经在坚果云根目录下创建同名文件夹，添加应用生成应用密码。

**Comment by 88250** [comment]
请上传一下日志，我们看下是否有报错，谢谢。

**Comment by twtccw** [comment]
`I 2021/01/26 18:16:47 working.go:85: kernel [v0.6.7] is booting, runtime mode is [prod], working directory is [/home/xujun/Downloads/siyuan-0.6.7-linux/siyuan-0.6.7-linux/resources], temp directory is [/tmp/siyuan], read only [false]
I 2021/01/26 18:16:47 lang.go:67: initialized languages
D 2021/01/26 18:16:47 conf.go:96: initialized language [zh_CN] based on device locale
I 2021/01/26 18:16:47 conf.go:179: local serve path [http://192.168.1.104:6806]
I 2021/01/26 18:16:47 conf.go:183: initialized conf
I 2021/01/26 18:16:47 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/26 18:16:48 webdav.go:36: initialized WebDAV server
I 2021/01/26 18:16:48 conf.go:329: initialized box
I 2021/01/26 18:16:48 repo.go:40: initialized git repo
I 2021/01/26 23:48:13 box.go:318: indexing [39] trees, cpus [12]`

**Comment by twtccw** [comment]
I 2021/01/26 18:16:47 working.go:85: kernel [v0.6.7] is booting, runtime mode is [prod], working directory is [/home/***/Downloads/siyuan-0.6.7-linux/siyuan-0.6.7-linux/resources], temp directory is [/tmp/siyuan], read only [false]
I 2021/01/26 18:16:47 lang.go:67: initialized languages
D 2021/01/26 18:16:47 conf.go:96: initialized language [zh_CN] based on device locale
I 2021/01/26 18:16:47 conf.go:179: local serve path [http://192.168.1.104:6806]
I 2021/01/26 18:16:47 conf.go:183: initialized conf
I 2021/01/26 18:16:47 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/26 18:16:48 webdav.go:36: initialized WebDAV server
I 2021/01/26 18:16:48 conf.go:329: initialized box
I 2021/01/26 18:16:48 repo.go:40: initialized git repo
I 2021/01/26 23:48:13 box.go:318: indexing [39] trees, cpus [12]

**Comment by 88250** [comment]
连接坚果云以后没有出现报错日志么？另外，请打开界面上的开发者工具，在 Console 中看下是否有前端报错。

**Comment by twtccw** [comment]
日志部分：
I 2021/01/26 15:28:58 lang.go:67: initialized languages
D 2021/01/26 15:28:58 conf.go:96: initialized language [zh_CN] based on device locale
I 2021/01/26 15:28:58 conf.go:179: local serve path [http://192.168.87.7:6806]
I 2021/01/26 15:28:58 conf.go:183: initialized conf
I 2021/01/26 15:28:58 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/26 15:28:59 webdav.go:36: initialized WebDAV server
I 2021/01/26 15:28:59 conf.go:329: initialized box
I 2021/01/26 15:28:59 repo.go:40: initialized git repo
I 2021/01/26 15:37:58 setuilayout.go:43: set ui layout done
I 2021/01/26 15:38:00 setuilayout.go:43: set ui layout done
E 2021/01/26 15:44:35 log.go:49: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	/usr/lib/go-1.13/src/runtime/panic.go:679 (0x43dad1)
/usr/lib/go-1.13/src/runtime/panic.go:199 (0x4539db)
/usr/lib/go-1.13/src/runtime/signal_unix.go:394 (0x453818)
/home/daniel/88250/siyuan-src/kernel/model/box.go:381 (0x10e2345)
/home/daniel/88250/siyuan-src/kernel/model/box.go:375 (0x10e22fa)
/home/daniel/88250/siyuan-src/kernel/model/box.go:924 (0x10e7a3b)
/home/daniel/88250/siyuan-src/kernel/cmd/refreshtree.go:21 (0x11582ad)
/home/daniel/88250/siyuan-src/kernel/cmd/cmd.go:255 (0x115f5f6)
/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 (0x46e0e0)
console部分：
main.6f1046b988ba3e0ae64d.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
t.addScriptSync @ main.6f1046b988ba3e0ae64d.js:1
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'userSiYuanProExpireTime' of null
    at Object.onSetaccount (main.6f1046b988ba3e0ae64d.js:1)
    at t.Model.msgCallback (main.6f1046b988ba3e0ae64d.js:1)
    at WebSocket.t.onmessage (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:4 Uncaught TypeError: Cannot read property 'length' of null
    at Object.t.initFile (main.6f1046b988ba3e0ae64d.js:4)
    at HTMLDivElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'url' of null
    at w.getLeaf (main.6f1046b988ba3e0ae64d.js:1)
    at w.openItem (main.6f1046b988ba3e0ae64d.js:1)
    at main.6f1046b988ba3e0ae64d.js:1
main.6f1046b988ba3e0ae64d.js:4 Uncaught TypeError: Cannot read property 'length' of null
    at Object.t.initFile (main.6f1046b988ba3e0ae64d.js:4)
    at HTMLDivElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
highlight.pack.js?v=0.6.7:169 WARN: Could not find the language 'P', did you forget to load/include a language module?
highlight.pack.js?v=0.6.7:169 WARN: Falling back to no-highlight mode for this block. <code class=​"language-P vditor-linenumber">​…​</code>​
highlight.pack.js?v=0.6.7:169 WARN: Could not find the language 'Pyt', did you forget to load/include a language module?
highlight.pack.js?v=0.6.7:169 WARN: Falling back to no-highlight mode for this block. <code class=​"language-Pyt vditor-linenumber">​…​</code>​
highlight.pack.js?v=0.6.7:169 WARN: Could not find the language 'Pyth', did you forget to load/include a language module?
highlight.pack.js?v=0.6.7:169 WARN: Falling back to no-highlight mode for this block. <code class=​"language-Pyth vditor-linenumber">​…​</code>​
highlight.pack.js?v=0.6.7:169 WARN: Could not find the language 'Pytho', did you forget to load/include a language module?
highlight.pack.js?v=0.6.7:169 WARN: Falling back to no-highlight mode for this block. <code class=​"language-Pytho vditor-linenumber">​…​</code>​
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'parentElement' of null
    at c.hlText (main.6f1046b988ba3e0ae64d.js:1)
    at HTMLInputElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'userSiYuanProExpireTime' of null
    at Object.onSetaccount (main.6f1046b988ba3e0ae64d.js:1)
    at t.Model.msgCallback (main.6f1046b988ba3e0ae64d.js:1)
    at WebSocket.t.onmessage (main.6f1046b988ba3e0ae64d.js:1)
onSetaccount @ main.6f1046b988ba3e0ae64d.js:1
msgCallback @ main.6f1046b988ba3e0ae64d.js:1
t.onmessage @ main.6f1046b988ba3e0ae64d.js:1
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)
main.6f1046b988ba3e0ae64d.js:1 Uncaught TypeError: Cannot read property 'dispatchEvent' of null
    at HTMLButtonElement.<anonymous> (main.6f1046b988ba3e0ae64d.js:1)

**Comment by 88250** [comment]
请在设置 - 外观中重置一下界面然后再试试，谢谢。

**Comment by twtccw** [comment]
已重置
[siyuan_console.log](https://github.com/siyuan-note/siyuan/files/5877358/siyuan_console.log)

**Comment by 88250** [comment]
请问你是登录了帐号使用吗？如果是的话请在设置 - 帐号中点击刷新按钮。

**Comment by twtccw** [comment]
您好，开始的时候我是想直接用webdav的，因为网盘里面有不少md文件。
后面发现webdav正确输入点击确定无反应后，才登录了。刚才反馈前登录已经退出。
对了，我的系统是deepin Linux V20.1。使用的客户端是官方发布的tar.gz里面的可执行程序。

**Comment by 88250** [comment]
如果 md 文件太多的话 WebDAV 可能调用会受限，因为思源目前的机制是需要全量读取所有 md 进行索引，调用过于密集可能就超过 API 配额了。

登录后帐号的问题稍后我们进行排查，这个 issue 我先关闭了，如果还有需要反馈或者帮助的请直接跟帖，非常感谢。

**Comment by MontaEllis** [comment]
我也遇到了一样的问题，但我指定的目录中是没有md文件的

**Comment by 88250** [comment]
@MontaEllis 感谢反馈，v0.8.5 中做了修复 https://github.com/siyuan-note/siyuan/issues/1432 请等发布以后再试。

**Comment by MontaEllis** [comment]
谢谢，siyuan牛逼
