### ISSUE TITLE
Request for Automatic Web Link Integration in SiYuan Database

### ISSUE THREAD

**Issue by itszarnish** [siyuan-note/siyuan#12979]
### In what scenarios do you need this feature?

I found this feature in Capacities that makes it incredibly convenient to add web links to the database automatically. All I have to do is copy and paste the link when I click the "New" button, and it automatically fetches all the website content and stores it in the database. I humbly request if we could get this feature in SiYuan in the future.

https://github.com/user-attachments/assets/f52ee400-0a8f-414e-9a96-0ea939c6270c

This is how we can search:

https://github.com/user-attachments/assets/7c56fe22-c91f-44d1-897a-cdfb7480c5be

These are the views available in Capacities, and I noticed that SiYuan has plans for a Gallery View. Could you let me know when we can expect this feature? I would really benefit from having these database views as shown in the video.

https://github.com/user-attachments/assets/95a08415-fc9e-4065-97e5-c04514d8b788

Once we paste a link, this is how our database looks like. I believe this could be achievable in SiYuan.

![image](https://github.com/user-attachments/assets/5f190747-c31c-4f08-aff6-f2a9e672b7bb)

As a data scientist, I often save articles and links, so this feature would be incredibly helpful, not just for me, but for many others too. I know I could use Capacities for this, but I truly love SiYuan for its customizations, flexibility, and all its other great features. Adding automatic web-link integration would make SiYuan even better for my workflow.

I sincerely hope you'll consider this request. Thank you for your time and for all the amazing work you’re doing with SiYuan. ❤️

### Describe the optimal solution

-

**Comment by InayaWhoCodes** [comment]
I fully support this feature request, it would be incredible to have! I've been looking for something similar, and if the developers bring this feature to SiYuan, I would be beyond grateful. 

+1 from my side

**Comment by 88250** [comment]
Hello, there is no plan to save web pages to the database. We hope to use a plugin to achieve this. We have discussed this before: https://github.com/siyuan-note/siyuan/issues/10824

**Comment by itszarnish** [comment]
Currently, there is no plugin for that, based on what I've explored, and I prefer native features provided by the software. I would still request that you consider this for future development, but please do not close this issue prematurely.

**Comment by itszarnish** [comment]
Also, you didn't mention the views. I mean, every PKM tool has gallery view, kanban view, list view, and table view. Why is SiYuan lacking these essential features? I've done my research, and you mentioned that this year you are focusing on improving SiYuan overall, which is great, and I really appreciate it. However, can we at least get these features next year? It would mean a lot.

**Comment by 88250** [comment]
1. We can only look forward to community plugins
2. There is no clear time to launch other views

Thank you for your time.

**Comment by itszarnish** [comment]
Alright, no problem. Take your time, but please try to make these views native because plugins don’t offer the same quality as native features. I really hope that by mid-2025, we will have views or at least a gallery view.
