### ISSUE TITLE
查看块引用时，高亮显示引用处的文本（强化提醒的目的）

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#12972]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/777695a4-a810-4e62-9327-bfd198702a3a)
查看块引用时，希望可以提高查找引用的效率，希望可以高亮显示锚文本。

### Describe the optimal solution

rt

**Comment by 88250** [comment]
我这里测试正常：

![image](https://github.com/user-attachments/assets/ac64856a-b2ba-4c7c-ad0e-c83489db2441)

方便的话请制作能够重现问题的最小数据集以便调试，我先关闭了，欢迎随时补充，感谢反馈。
