### ISSUE TITLE
图片重命名后 ocr-texts.json 需要更新

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12974]
需要把原来的 OCR 文本带过去：

[视频.webm](https://github.com/user-attachments/assets/23cec5ef-c844-4445-b546-4cf2c2ad0350)

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.

**Comment by TCOTC** [comment]
图片重命名或许不需要 RemoveAssetText ，因为图片重命名之后还能按 Ctrl+Z 撤销回前一张图片。

或者说撤销之后再把 Text 加回来？

**Comment by TCOTC** [comment]
那重命名的场景就不 Remove 了吧，清理未引用的图片时再 Remove

**Comment by 88250** [comment]
ok

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/commit/ba9f41aa35489e4a4a527d435b27b2c759fa5b81
https://github.com/siyuan-note/siyuan/commit/37647191c68fc6e878df04aaff7d58cec8b63701
