### ISSUE TITLE
Improve HTML clipping

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#12973]
### In what scenarios do you need this feature?

以下内容不能正确剪藏，例如：

https://book.leveldesignbook.com/process/overview 的动图,

https://book.leveldesignbook.com/process/preproduction 的youtube iframe视频,

https://book.leveldesignbook.com/process/combat/enemy 的表格

### Describe the optimal solution

希望可以正确剪藏，这个网站使用的是gitbook，

![image](https://github.com/user-attachments/assets/ea90ff4f-b909-4b93-96c6-66da4cb7c6e7)

**Comment by 88250** [comment]
感谢反馈，代码已经改进，需要升级思源和剪藏扩展。

**Comment by KuiyueRO** [comment]
谢谢D大
