### ISSUE TITLE
Centered Document View & Web Sharing

### ISSUE THREAD

**Issue by itszarnish** [siyuan-note/siyuan#12978]
### In what scenarios do you need this feature?

This is a screen recording of Capacities, and it’s not just about Capacities in Notion either. When we click on a document in the database, it opens in a centered, floating style, and we can expand it to full document size as well. I would love to have this feature in SiYuan, as it’s incredibly convenient and easy to use it.

Additionally, I’d like to request an enhancement for sharing documents on the web. In Capacities or Notion, when we share a document, it retains all styles, colors, and other details in the shared version. This feature is something I truly need in SiYuan.

Thank you for considering these requests! I would greatly appreciate it. Please don't ignore it.

https://github.com/user-attachments/assets/0933630a-960b-494a-b41b-255735019889

This is how we can expand the document to full size; I really want this feature.

https://github.com/user-attachments/assets/b345f189-236e-496f-bed6-ca26047aa49c

### Describe the optimal solution

-

**Comment by 88250** [comment]
In the SiYuan database, if it is a bound block, you can open it by floating:

![image](https://github.com/user-attachments/assets/20a661db-a1d2-465b-b5a6-2677b6d6676d)

If you want to share, please consider using the publishing function:

![image](https://github.com/user-attachments/assets/8528ab4e-fcaf-43f7-bca4-968abcc3a868)

**Comment by itszarnish** [comment]
> In the SiYuan database, if it is a bound block, you can open it by floating:
> 
> ![image](https://private-user-images.githubusercontent.com/873584/381796244-20a661db-a1d2-465b-b5a6-2677b6d6676d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzU3NDIsIm5iZiI6MTczMDM3NTQ0MiwicGF0aCI6Ii84NzM1ODQvMzgxNzk2MjQ0LTIwYTY2MWRiLWExZDItNDY1Yi1iNWE2LTI2NzdiNmQ2Njc2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMTUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTA2MjlhMjZhZjdlZTM3MGQzZGI3NmExMzQ4NDJlNjZmMWNjNzJlOTdkZDVhYjZiZTE1N2U2NDQ0ZDVjYmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.trPu40PEbsJ2n62YSAb-ZeldH-WcQzoNlWNS0YATyKg)
> 

I've tried this, but it is not as user-friendly or efficient as what we have in Notion, Capacities, or even AnyType.

Here are some user experience issues:

1. It should not display a floating window when hovering over it.
2. Please watch the video below. This is how it should display: in the exact center of the SiYuan window, only when the user clicks on the bound block document in the database.

https://github.com/user-attachments/assets/4a50b1db-c51f-4df2-8454-a65fd9954072

3. Once I click on the 'Open' arrow button, it should open in another tab, which is already working well. However, the floating window should close instantly as soon as the user clicks to open it in full-size mode.

![image](https://github.com/user-attachments/assets/91637b7f-e004-4317-ad67-04045f37b618)


https://github.com/user-attachments/assets/280a6acd-4bd5-4b99-aeeb-155f34013509


I've already heard that you often ignore these kinds of user experience improvements, but they are important for daily use. All I can do is request that you please consider them.

**Comment by itszarnish** [comment]
> If you want to share, please consider using the publishing function:
> 
> ![image](https://private-user-images.githubusercontent.com/873584/381796386-8528ab4e-fcaf-43f7-bca4-968abcc3a868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzU3NDIsIm5iZiI6MTczMDM3NTQ0MiwicGF0aCI6Ii84NzM1ODQvMzgxNzk2Mzg2LTg1MjhhYjRlLWZjYWYtNDNmNy1iY2E0LTk2OGFiY2MzYTg2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMTUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmY4NjcwNmZkY2ViNzg3MjE1ODM1NzBlNWZkMWQ4MzNiN2JhZTQ2OGFiODZmODU2YzFhOGU5ZTgyOWY5NWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9K5-okcMoxt2-FvW-BhgsJhbG8pNKVGocDmiYs-v_9A)

Isn't the publish function meant for sharing on a local network? What I mean by the share feature is the ability to publish content on the web so that everyone can access it via a link and read it without any login or barriers, just like in Notion and Capacities.

Here is a video of how convenient it is in Capacities: the user has a share button in the menu, and they can just click on it and get a shareable link. It’s that simple. Why isn't SiYuan considering this? It would be super helpful for users who want to share their content. Why don't we have a default feature like this, as simple as it is?

https://github.com/user-attachments/assets/e7b8543b-2351-4465-a976-a0a98bbe2f2c

Once the content has been shared, the user can see a beautiful shared indicator in the breadcrumb area.

![image](https://github.com/user-attachments/assets/540f4ce2-b192-459b-8335-afdaa4035a64)

And then, any user can access the shared content like this, with all the styles remaining unchanged.

https://github.com/user-attachments/assets/ebefca6f-245c-4db2-bb1f-7ef042ac1ff1

**Comment by itszarnish** [comment]
Okay, I found the option to control the hover behavior, but what I still want is for the bound document in the database to open in a compact, centered window when I click on it, instead of opening in a new tab.

![image](https://github.com/user-attachments/assets/ca3efd50-8e06-4caf-9f06-969161021865)

**Comment by TCOTC** [comment]
> However, the floating window should close instantly as soon as the user clicks to open it in full-size mode.

I think so. #12806

**Comment by itszarnish** [comment]
> > If you want to share, please consider using the publishing function:
> > ![image](https://private-user-images.githubusercontent.com/873584/381796386-8528ab4e-fcaf-43f7-bca4-968abcc3a868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzU3NDIsIm5iZiI6MTczMDM3NTQ0MiwicGF0aCI6Ii84NzM1ODQvMzgxNzk2Mzg2LTg1MjhhYjRlLWZjYWYtNDNmNy1iY2E0LTk2OGFiY2MzYTg2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxMTUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmY4NjcwNmZkY2ViNzg3MjE1ODM1NzBlNWZkMWQ4MzNiN2JhZTQ2OGFiODZmODU2YzFhOGU5ZTgyOWY5NWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9K5-okcMoxt2-FvW-BhgsJhbG8pNKVGocDmiYs-v_9A)
> 
> Isn't the publish function meant for sharing on a local network? What I mean by the share feature is the ability to publish content on the web so that everyone can access it via a link and read it without any login or barriers, just like in Notion and Capacities.
> 
> Here is a video of how convenient it is in Capacities: the user has a share button in the menu, and they can just click on it and get a shareable link. It’s that simple. Why isn't SiYuan considering this? It would be super helpful for users who want to share their content. Why don't we have a default feature like this, as simple as it is?
> 
>  Recording.2024-10-31.171059.mp4 
> Once the content has been shared, the user can see a beautiful shared indicator in the breadcrumb area.
> 
> ![image](https://private-user-images.githubusercontent.com/119295635/381942236-540f4ce2-b192-459b-8335-afdaa4035a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjIyMDMsIm5iZiI6MTczMDQ2MTkwMywicGF0aCI6Ii8xMTkyOTU2MzUvMzgxOTQyMjM2LTU0MGY0Y2UyLWIxOTItNDU5Yi04MzM1LWFmZGFhNDAzNWE2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMTUxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWNiOTdhZDg5ZDc4YTA1NzUxZmY3YzQ3NGY4ZmUxZDA3YTllNGZkNWNmOWY2MmYzMjllM2M3ODM2MzUzOWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GMyL-02EdFMfIh1KmnCUXPhc7yHDhuJcNT1-teOBXXc)
> 
> And then, any user can access the shared content like this, with all the styles remaining unchanged.
> 
>  Recording.2024-10-31.171355.mp4

Can someone please help me with this? I really need to publish to the web while keeping all the syntax intact.

**Comment by InayaWhoCodes** [comment]
I'm also looking for an easy way to share but haven't been able to figure it out. It would be nice if Siyuan also had a share button in the menu.

**Comment by HamXaY09** [comment]
I'm also looking for a "share to web" feature as mentioned. Does Siyuan have a similar feature? if yes then how we can do it? 

I'm not good with complex methods, so I'm looking for a simple way to share with people I want to.

**Comment by HamXaY09** [comment]
I found this plugin but I'm not aware of this docker thing as I'm not very technical person this plugin what I was looking for but its can't share it on the web like Notion does

![image](https://github.com/user-attachments/assets/b00be883-c39d-4c88-876d-78fb11f9ce93)
