### ISSUE TITLE
All plain text formats are supported when comparing data snapshots

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#12975]
在快照对比界面中显示纯文本内容

### In what scenarios do you need this feature?

目前在两个快照进行对比的时候，只有思源文档、JSON 文件能直接展示内容并进行对比。其他的 txt 、md 文档等纯文本文档都只能显示一个路径。非常不方便对比。

![image](https://github.com/user-attachments/assets/12875a4f-b825-4dd2-8b8f-0baedaf0e6bd)

### Describe the optimal solution

允许直接显示对比 txt、md 等纯文本文件。

**Comment by TCOTC** [comment]
我觉得要不还是在客户端支持一下这些操作吧：https://github.com/siyuan-note/siyuan/issues/11151

**Comment by 88250** [comment]
@TCOTC 那个不考虑了，先解决楼主提的显示纯文本格式。

**Comment by TCOTC** [comment]
我这里还是只有路径：

![image](https://github.com/user-attachments/assets/358ddb25-6cef-461d-84bf-c6022b27798b)

**Comment by 88250** [comment]
稍后改进。

**Comment by TCOTC** [comment]
除了比较数据快照，文件历史也需要支持显示纯文本：（路径保留，用于找到对应的文件）

![image](https://github.com/user-attachments/assets/6b1cdef3-11b8-4e96-b680-26b67831f2f8)

**Comment by 88250** [comment]
文件历史这边暂时不动了。
