### ISSUE TITLE
Callout Block Feature in SiYuan with Customizable Icons

### ISSUE THREAD

**Issue by itszarnish** [siyuan-note/siyuan#12987]
### In what scenarios do you need this feature?

I found this feature to be very useful. In AnyType, we have callouts, and the good thing is that we can achieve this in SiYuan as well. Once we add a callout block, we can then change the icon, which is super handy. I would like to request the addition of a callout block in SiYuan too.

Video for the ref:

https://github.com/user-attachments/assets/54d13782-9c4c-451f-9caa-034e64c139a9

Edit: Notion also have this feature.

![image](https://github.com/user-attachments/assets/032cd28e-6db7-426a-9b07-17a4a04b8de1)

### Describe the optimal solution

-

**Comment by itszarnish** [comment]
I know that in SiYuan we have plugins that perform similar functions, but they come with limitations, such as not being able to pick any emoji or icon we want—it's fixed. Therefore, I would appreciate it if we could have this feature natively.

![image](https://github.com/user-attachments/assets/a97931fb-4b6b-41d7-9b7a-f67793ee0194)

**Comment by 88250** [comment]
Hello, judging from the current development resources, if there is a plugin implementation, we will not consider native implementation. Perhaps you can provide custom icons to the plugin repository for feedback. Thank you.

**Comment by TCOTC** [comment]
sy-bq-callout plugin support:


https://github.com/user-attachments/assets/1ec378ec-1426-445b-a62b-c05fd164859f

**Comment by itszarnish** [comment]
> The sy-bq-callout plugin supports using the same emoji for a type (but not for a block):
> 
>  video.mp4

This is what I mentioned earlier: I need to be able to change the emoji/icon on the fly for each callout, as you demonstrated. I've already explored the options, but they remain limited. I can’t instantly change the icon when using a callout, similar to the examples I shared from Anytype.

For instance, if I have multiple documents in SiYuan that each require different emojis, the current plugin doesn’t allow for that level of customization. If I update a custom emoji through the plugin, it will replace the icon everywhere it’s used, which isn’t ideal.

**Comment by shuojie819** [comment]
希望可以重新考虑一下，SiYuan内置Callout块（有折叠按钮），现在几乎没有不支持Callout的笔记软件了：Notion、Wolai、Flowus、飞书、语雀、Obsidian、Anytype、AppFlowy……

**Comment by Achuan-2** [comment]
> [@88250](https://github.com/88250) 希望可以重新考虑一下，SiYuan内置Callout块（有折叠按钮），现在几乎没有不支持Callout的笔记软件了：Notion、Wolai、Flowus、飞书、语雀、Obsidian、Anytype、AppFlowy…… 笔记内容相关的基础功能块希望可以内置。

+1, github also supports it
it would be great if siyuan can add a fold button in callouts, which can fold a callout conveniently
```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
