### ISSUE TITLE
鼠标错误触发折叠

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#1298]
### 复现时机

从思源切换到别的程序，过一会再从别的程序切换回思源，此时用鼠标左键单击容器块文字就会直接触发折叠（并没有按住 alt 键）。

停留在思源界面，再敲击一下 alt 键，此现象消失。

在我这里是必现操作。

### 报错信息

有时出现这样的提示：
```
读取笔记本 [http://127.0.0.1:6806/siyuan/1605629299270/思源笔记测试demo/] 下的文件 [/拖动测试.md] 失败：open C:\Users\deera\Dropbox\myNote\思源笔记测试demo\拖动测试.md: The requested operation cannot be performed on a file with a user-mapped section open.
```

**Comment by 88250** [comment]
谢谢反馈，这个问题后面会在 https://github.com/siyuan-note/siyuan/issues/1219 中修复。
