### ISSUE TITLE
The backlink panel supports filtering by the document name

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#12985]
反链面板过滤文档名

### In what scenarios do you need this feature?

示例： 
- 文档名： 张强
- 内容：[[生日]]  XXXX...

但是反链过滤，不能按照文档名去过滤，过滤张强就是空的了。

### Describe the optimal solution

直接在原有基础上添加文档名的检索，不会影响别的内容。

**Comment by SaXz2** [comment]
测试体验：可以再次增强搜索命中 命名、别名、备注、标签 等其他属性 使用体验会更加好

参考：https://github.com/Misuzu2027/syplugin-backlink-panel/issues/20

对比图：
![Clip_2024-11-11_11-22-33](https://github.com/user-attachments/assets/8fa96dfa-2bc1-4f4d-97fe-3bb28e001b96)

**Comment by 88250** [comment]
收到，稍后加上。

**Comment by SaXz2** [comment]
1.测试了新版没有生效
检索属性检索不出来
![Clip_2024-11-13_23-00-52](https://github.com/user-attachments/assets/3219f066-df64-4e4f-a42c-0b56113bfd09)

2.应该去掉大小写检测
![Clip_2024-11-13_22-57-49](https://github.com/user-attachments/assets/e19f924d-fbaf-42de-b85b-995486a2e3d1)

3.不能过滤出属性中的缺字(虽然是插件但是原版应该也测试一下)
![Clip_2024-11-13_23-02-21](https://github.com/user-attachments/assets/c8c83fb4-82f6-4194-a0b4-712c7f28838d)

4.支持过滤出代码块中的这里，建议直接改成匹配到的都列出来不管是嵌入块还是代码块只要肉眼能看到都匹配过滤出来
![Clip_2024-11-13_22-57-23](https://github.com/user-attachments/assets/e9920451-e857-4351-a8c1-1cdb2fcc21c7)

**Comment by SaXz2** [comment]
破案了属性加在段落上就不显示了

**Comment by 88250** [comment]
没太看懂……

**Comment by 88250** [comment]
1. 只有给定义块上添加的属性才过滤，不计算定义块子块的
2. 改进空格分隔关键字高亮
3. 代码块语言搜索搞不了，代码块内容高亮目前也搞不了
4. ok
5. 和 2 一样，空格分隔

**Comment by SaXz2** [comment]
1. 建议再优化一下，我都统一把属性添加到段落块中，不计算的话什么都搜索不出来
3. 可以参考 反链面板插件

**Comment by 88250** [comment]
麻烦制作一个 1 问题的测试数据集我这边调试看看。

2 的话短期内不考虑了改动高亮机制了。

**Comment by SaXz2** [comment]
[搜索测试.sy (1).zip](https://github.com/user-attachments/files/17747134/sy.1.zip)

![Clip_2024-11-14_18-26-42](https://github.com/user-attachments/assets/d562af7d-7c45-4cb9-9139-f08d8c819d4d)

这个属性添加的方式应该限制一下，现在有点太过于自由了以至于能最多套个10层
![Clip_2024-11-14_18-31-53](https://github.com/user-attachments/assets/0fe0871d-77ad-4b85-8a40-609262c129c2)

**Comment by TCOTC** [comment]
每个块都是能添加属性的

**Comment by SaXz2** [comment]
有一些显示BUG，目前会变成这样
![Clip_2024-11-18_12-32-14](https://github.com/user-attachments/assets/34447bd2-4c05-4ae3-ae63-0f68dbaf4d7e)

用了主题以后会这样
![Clip_2024-11-18_12-31-52](https://github.com/user-attachments/assets/8466ebe2-9334-461c-b0be-1d4f83900dc1)

**Comment by TCOTC** [comment]
关联 #13178

**Comment by SaXz2** [comment]
@88250  D大再搞一搞吧，经过测试这个版本目前用起来很麻烦21个反链中只能过滤出6个连最基本的静态锚文本都无法被过滤出来
![Clip_2024-11-19_20-26-09](https://github.com/user-attachments/assets/d92608f4-346a-4ed3-8e0b-644fcbb01868)

**Comment by 88250** [comment]
这个图片我没看懂，麻烦做个最小化测试数据集。

**Comment by SaXz2** [comment]
召唤一下米大@Misuzu2027  来探讨一下，刚才看了一眼米大的说明，过滤逻辑上有些复杂，我已经有点搞不清楚了，稍后我再做一份新的测试数据集
![Clip_2024-11-19_21-05-56](https://github.com/user-attachments/assets/a592d27e-932c-4846-9322-aedc6ba98b2d)
米大的说明

**Comment by 88250** [comment]
@Misuzu2027 感谢指出问题，下个版本修复 https://github.com/siyuan-note/siyuan/issues/13210

**Comment by SaXz2** [comment]
新的测试数据
[合并测试.sy.zip](https://github.com/user-attachments/files/17824814/sy.zip)

**Comment by 88250** [comment]
@SaXz2 搜索的问题是因为没有在当前块上，这个不会考虑改动了。

**Comment by SaXz2** [comment]
不对啊D大，3.1.13版本过滤不了段落块，以前的版本是可以的，这个过滤效果肯定是不应该的
![Clip_2024-11-20_16-06-10](https://github.com/user-attachments/assets/56202bf6-08b5-45e9-8b6e-59058eb4c45b)

**Comment by 88250** [comment]
哦哦，不好意思，我只看了列表那个例子，段落的例子确实有问题，稍后调整。

**Comment by Temacc0531** [comment]
dev3现在过滤不了列表子块的，这个是正常的吗

**Comment by 88250** [comment]
@Temacc0531 https://github.com/siyuan-note/siyuan/issues/12985#issuecomment-2478315130

**Comment by Temacc0531** [comment]
> @Temacc0531 [#12985 (comment)](https://github.com/siyuan-note/siyuan/issues/12985#issuecomment-2478315130)

嘶，我这个不是还挺常见的用法吗，有什么替代方案吗😯

**Comment by 88250** [comment]
恐怕是没有，看下社区插件？

**Comment by Temacc0531** [comment]
> 恐怕是没有，看下社区插件？

传递规则冲突是啥意思来的，按我的理解都显示出来了就应该支持过滤吧，属性那些隐藏字段都可以，显示出来的反倒过滤不了

**Comment by 88250** [comment]
新开一个 issue 吧
