### ISSUE TITLE
已关闭的笔记本中的闪卡会显示“不存在符合条件的内容块”

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#12983]
容易被误判为已删除的块。

重构闪卡的话最好能记录一下所在的笔记本 id ，知道是在已关闭的笔记本里。

**Comment by 88250** [comment]
这个机制没法改了，没有索引的情况下无法判断。

**Comment by TCOTC** [comment]
用户反馈：

https://ld246.com/article/1745931170094

**Comment by TCOTC** [comment]
@88250 那就加个索引？

**Comment by TCOTC** [comment]
@88250 这个改成 no plan
