### ISSUE TITLE
勾选框列完成状态同步至主键任务列表的勾选框

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#12988]
### In what scenarios do you need this feature?

如下图，数据库的勾选框完成后可以自动把任务列表的勾选框也同步勾选，可以方便数据库管理任务
![image](https://github.com/user-attachments/assets/4856d1e5-4094-4cf2-9616-d1ee803a6052)
![image](https://github.com/user-attachments/assets/ee3d75e2-ea38-4a3c-8a5c-0a46648d883f)

### Describe the optimal solution

在勾选框列的设置里增加开关，选择是否能同步状态至任务列表的勾选框

**Comment by 88250** [comment]
这个恐怕不太合理，因为可能存在多个勾选框，无法确定哪个勾选框对应任务列表状态，如果还要加配置的话就太复杂了，原生不考虑了，谢谢。

**Comment by 5kyfkr** [comment]
> 这个恐怕不太合理，因为可能存在多个勾选框，无法确定哪个勾选框对应任务列表状态，如果还要加配置的话就太复杂了，原生不考虑了，谢谢。

这个插件也做不出来吧，如果要管理任务那要点两次勾选框，对于任务管理这种高频操作过于繁琐了。
加个选项就是：同步完成状态至主键任务列表，只要加一个这个开关，其他勾选框列默认不开启这个开关就行，也不影响现有的用法。

**Comment by 88250** [comment]
现阶段不考虑加特性了。
