### ISSUE TITLE
Performance Improvement Needed for Toggle Block: Loading Indicator Causes Delays

### ISSUE THREAD

**Issue by itszarnish** [siyuan-note/siyuan#12986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I've noticed that the performance of the toggle block is not smooth and doesn't feel robust to me. It shows a loading indicator whenever I toggle to display the content, which I have never seen in any other PKMs.

**Here are the video recordings demonstrating the toggle feature:**

### 1. SiYuan Toggle Feature:
https://github.com/user-attachments/assets/434fa91a-7d5f-4c31-a1ea-cb268fe26728

![image](https://github.com/user-attachments/assets/d37277e3-24dc-4957-8b41-434b0f27cc33)

### 2. Toggle Feature in Capacities (feels smooth and fast without a loading indicator):

![image](https://github.com/user-attachments/assets/297c3ab5-19f4-47c3-973f-3480080d3e2e)

https://github.com/user-attachments/assets/bdbf29a6-b3aa-4213-9812-5d294cc1f554

### 3. Toggle Feature in AnyType (also fast):

![image](https://github.com/user-attachments/assets/26792285-524f-4d6d-a824-79e084b3552c)

https://github.com/user-attachments/assets/c06b5f3a-91c5-4562-9385-adfa2892f4e0

**Additionally, it would be better to have a dedicated toggle block. As you can see in both Capacities and AnyType, the arrow icon is displayed properly, whereas in SiYuan, the arrow icon only appears when the user hovers over it. This can be improved.**

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
This cannot be improved, because the heading block needs to be dynamically calculated and loaded.

**Comment by itszarnish** [comment]
Okay, what I mean is: is it impossible to improve, or is it just that you don’t have the time for it? If that's the case, I would request that you please don’t close this issue, as it’s really important. Take your time, and maybe consider improving it in the coming weeks or months, but please do something about it. The current implementation of the toggle feels slow and at least do something about that loading indicator doesn't look good at all. Thank you.

**Comment by HamXaY09** [comment]
+1 I've also noticed this issue.

**Comment by itszarnish** [comment]
If possible, consider adding a separate toggle block feature, similar to what most PKMs offer. This would provide a more robust and smooth user experience if current implementation of heading block can't be improved.
