### ISSUE TITLE
闪卡编辑器内长按 esc 后光标聚焦到复习按钮上

### ISSUE THREAD

**Issue by TangQi001** [siyuan-note/siyuan#12989]
### In what scenarios do you need this feature?

当我复习闪卡的时候，总是需要去修改闪卡内容
但是，当我修改内容后，我不能使用1 2 3 4或者asdf来复习闪卡
而是需要鼠标重新点击闪卡界面
这就会造成复习闪卡的不流畅
When I review flashcards, I always need to modify the flashcard content. However, after I modify the content, I cannot use 1, 2, 3, 4, or asdf to review flashcards. Instead, I need to click on the flashcard interface again with the mouse. This will cause an unsmooth review of flashcards.

### Describe the optimal solution

在闪卡界面中增加新的全局快捷键，使得编辑闪卡之后，还能快速选择复习难度
Add new global shortcuts in the flashcard interface so that after editing a flashcard, you can quickly select the review difficulty.

**Comment by 88250** [comment]
这个不考虑了，复习快捷键还是仅作用于复习界面，感谢反馈。

**Comment by TCOTC** [comment]
楼主的意思应该是这里缺少自定义快捷键：

![image](https://github.com/user-attachments/assets/cb24c613-f1b4-4529-840d-0be49b37acc0)

![image](https://github.com/user-attachments/assets/24c5f179-0c35-447a-a893-a1fb5d4b4cbd)

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
@TangQi001 用 Esc 后可以继续使用 1234 ，这样是否能解决你的问题？

**Comment by TCOTC** [comment]
话说按 Esc 不能选中块也是个问题

**Comment by 88250** [comment]
https://ld246.com/article/1730688209179 和这个一起考虑下 @Vanessa219

**Comment by TCOTC** [comment]
Esc 跟选中当前块冲突了，建议不要这样改

**Comment by TCOTC** [comment]
所以我还是觉得添加自定义快捷键更通用和统一

**Comment by TCOTC** [comment]
想了想我觉得还是不要改了，用鼠标点吧。毕竟编辑闪卡也是用鼠标点的。

**Comment by gaoluji** [comment]
可以用用remnote

**Comment by Vanessa219** [comment]
改成长按吧，https://ld246.com/article/1730688209179 这个问题需要的话重新开一个 issue 吧。

**Comment by 88250** [comment]
这个改进就不归入特定里程碑版本了，谢谢。
This improvement will not be included in a specific milestone version, thank you.

**Comment by TCOTC** [comment]
我这里长按 Esc 之后：

- 窗口：会关闭
- 页签：焦点还是在块内
