### ISSUE TITLE
插件api或者内核api请求，返回只具备css和html标签的伪protyle

### ISSUE THREAD

**Issue by suka233333** [siyuan-note/siyuan#12995]
### In what scenarios do you need this feature?

现在的插件api: new Protyle很好用了，可以很方便的在思源中渲染一个可以实时编辑的编辑区。
但是想要在思源以外的地方渲染一个编辑区就比较困难了，即使是只有ui界面的伪编辑区都不行，主要是css的样式比较难以搞定。所以能不能插件提供一个方法，入参为blockId，返回这个blockId渲染出来的那堆html，包含相关的css样式。

### Describe the optimal solution

提供一个插件方法或者内核api？（不确定内核api能不能干这件事），入参为blockId，返回这个blockId渲染出来的那堆html，包含相关的css样式。

**Comment by 88250** [comment]
试试这个 /api/block/getBlockDOM
