### ISSUE TITLE
对外发布只读模式服务支持简单内容权限控制

### ISSUE THREAD

**Issue by ouchuji** [siyuan-note/siyuan#12990]
### In what scenarios do you need this feature?

场景如下：
使用Docker部署Web版本思源笔记，发布服务模式将笔记以只读模式提供给他人查阅，这是个很方便的功能，但是希望可以做的更好些

例如可以设置某些笔记本可以开放给别人查阅，例如公司里面一些尚未发布的规章制度问题，还在完善中的文档，这些都不便于提早发布给别人看

所以建议该处可以加一些简单权限控制，满足小型创业团队的需求

### Describe the optimal solution

发布服务设置处

可以支持开关某些笔记本的对外可读权限

![image](https://github.com/user-attachments/assets/956ecf6e-533e-4b17-90cf-ac075202be74)

**Comment by 88250** [comment]
你好，目前不考虑支持设置发布粒度和权限管理，谢谢。
