### ISSUE TITLE
Docker Web 模式支持通过域名定向某个具体文档并最好可以支持锚点

### ISSUE THREAD

**Issue by ouchuji** [siyuan-note/siyuan#12992]
### In what scenarios do you need this feature?

场景如下：
通过Docker部署Web版本的思源笔记，通过服务发布的方式对外发布只读的笔记内容
但是假如说想告诉同事，想看哪个具体文档，只能让他打开网址后，手动搜索才能找到相应文档
建议可以通过链接的方式，可以指定定位打开某个指定的文档，并且最好可以支持锚点，直接跳转文档某个位置
这样对于小团队协作会比较便捷

### Describe the optimal solution

Docker部署的思源，每个文档可以有一个分享的Web地址，打开该Web地址，即可直接跳转打开该文档

**Comment by TCOTC** [comment]
...url...?id=xxx

...url...?id=xxx&focus=true

**Comment by ouchuji** [comment]
@TCOTC  请教一下，是否有功能或者插件，可以直接复制出自定义域名 + 文档ID的 链接， 每次都是手动拼比较麻烦

**Comment by TCOTC** [comment]
印象中没有，你可以自己做个插件或者写 CSS 实现

**Comment by ouchuji** [comment]
> 印象中没有，你可以自己做个插件或者写 CSS 实现

有示例吗？或者文档地址我看下，感谢

**Comment by TCOTC** [comment]
参考 [插件开发 Quick Start - 链滴](https://ld246.com/article/1723732790981)

**Comment by TCOTC** [comment]
> 直接复制出自定义域名 + 文档ID的链接

现在有了：

![Image](https://github.com/user-attachments/assets/fec47654-e764-40c8-8042-f26112e490e2)

**Comment by ouchuji** [comment]
谢谢, 给力
