### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by zZ-10** [siyuan-note/siyuan#13]
我在搜索时， 搜索列表内有内容，搜索输入框无内容或者 有内容， 我输入法键盘未关闭，点击enter都会自动打开选中的第一条结果 
![微信截图_20200921180721](https://user-images.githubusercontent.com/58500946/93755141-610e1300-fc35-11ea-8ae7-ea982019b6d3.png)

**Comment by 88250** [comment]
从截图上看是因为选中了第一条搜索结果。

**Comment by 88250** [comment]
v0.2.0 已经发布，请试用一下，如果还有问题请继续反馈，issue 我先关闭了。

**Comment by zZ-10** [comment]
额，我输入法的键盘没关闭之前， 我按enter，应该是把输入法键盘内的输入字母原文输入到搜索框的， 而不是自动打开选中的第一条展示的搜索结果记录

**Comment by 88250** [comment]
收到，下个版本修复 @Vanessa219

**Comment by zZ-10** [comment]
Issue都没消息提醒，我都不知道恢复了， 昨天下班的时候我说的就是这个:bug:
