### ISSUE TITLE
Heading Option Needed in Menu

### ISSUE THREAD

**Issue by HamXaY09** [siyuan-note/siyuan#13007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Hello, developers. I would like to request that you add a heading option to this floating menu. It would make my life easier, as currently, I am unable to convert text to a heading, and there is no option available in the menu.

https://github.com/user-attachments/assets/1d25c8ef-f1c2-437f-8e69-611a7693fda6

### Expected result

Please, if possible, add a heading option directly here so that everyone, including people like me who aren't very technical, can easily change it. This would make life much easier for me.

![image](https://github.com/user-attachments/assets/4312c2f9-98d7-4b7a-bec2-b6fa7954c0eb)

Thank you!

### Version environment

```markdown
- Version: 3.1.10
- Operating System: 
- Browser (if used):
```

### Log file

no

**Comment by TCOTC** [comment]
Two ways:

1. Click on another block, then right-click on the block that you want to convert to title
2. Press Ctrl+/

**Comment by 88250** [comment]
As @TCOTC said, please use Ctrl+/ to trigger the block icon menu, which contains block type conversion; or directly use the heading shortcut Ctrl+Alt+1~6.

[issue.webm](https://github.com/user-attachments/assets/b9022656-1d0d-4856-9d87-15a9da26054f)

**Comment by HamXaY09** [comment]
> Two ways:
> 
> 1. Click on another block, then right-click on the block that you want to convert to heading
> 2. Press Ctrl+/

Thank you! I'll use this approach, but just out of curiosity, do you plan to add a heading option in the menu for quick access in the future, or will you never consider adding this feature? I mean, it's a simple option and not that complicated.

**Comment by 88250** [comment]
Hello, that toolbar is used to edit inline-level elements, so block-level operations will not be considered to be added to the toolbar.
