### ISSUE TITLE
云端备份的数据大小和同步一直一样？

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![PixPin_2024-11-03_00-55-33](https://github.com/user-attachments/assets/1e237789-356b-4d58-950d-360c73854018)
最近发现云端备份和云端同步的数据大小一直一样，可是我目前并没有云端备份
请问是云端备份计算错误吗？
![PixPin_2024-11-03_01-00-34](https://github.com/user-attachments/assets/27c0a78e-0a60-45d1-96b8-8db488081283)

### Expected result

云端备份的数据大小显示正常

### Version environment

```markdown
- Version:  v3.1.11-dev9
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
应该是跟最近一个快照一致的

**Comment by 88250** [comment]
最近的一个改动影响了统计，目前已经修复，感谢反馈。
