### ISSUE TITLE
更换音频播放器组件

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13001]
原生样式有点丑了，我觉得可以参考飞书这种：

左边播放暂停，中上显示文件名和时长，中下显示进度条，右边调整音量（以及调整播放速度）。以及组件的宽度是块的宽度。

![image](https://github.com/user-attachments/assets/0c69396c-2a15-4a02-8ce0-6b50d7349676)

关联 #6490

---

p.s. AnyType 这个也挺好看，但不够实用：

![image](https://github.com/user-attachments/assets/45e1b905-434b-468f-9041-5061f528c3a2)

**Comment by wish5115** [comment]
不如让用户选择以哪种样式显示

甚至隐藏，可以通过链接等关联音频文件，点击触发播放等。

**Comment by TCOTC** [comment]
> 可以通过链接等关联音频文件

现在就行

**Comment by wish5115** [comment]
> 现在就行

但现在不能隐藏播放

**Comment by TCOTC** [comment]
隐藏播放不合理，要有组件才行

**Comment by wish5115** [comment]
> 隐藏播放不合理，要有组件才行

合理呀，参考这个需求 https://ld246.com/article/1730450028517/comment/1730547266995#comments

**Comment by TCOTC** [comment]
没看懂，有录屏演示吗？

**Comment by wish5115** [comment]
> 没看懂，有录屏演示吗？

大概就是想要这种效果，不需要显示播放器

https://github.com/user-attachments/assets/3fbe8903-fbca-47d4-90c6-46fd9efef8f0

**Comment by 88250** [comment]
考虑用插件扩展吧。
