### ISSUE TITLE
改进 .layout__resize 的样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13003]
目前的样式不够明显：

[video.webm](https://github.com/user-attachments/assets/abbe2e8c-dfca-448b-8947-52d2dda7e789)

可以参考：

[video.webm](https://github.com/user-attachments/assets/3f9a5031-f3ca-4e8d-b805-150b8584df27)

[video.webm](https://github.com/user-attachments/assets/e0b272b0-c852-40af-b7ea-5d573f66d88b)

[video.webm](https://github.com/user-attachments/assets/eefba792-4051-412e-8804-e4815798fc88)

**Comment by Vanessa219** [comment]
看了一下历史记录，移动上去的颜色是修改过三次了，目前就不在修改了。宽度改变的话会有点粗糙的感觉，综合下来就不进行修改了。

https://github.com/user-attachments/assets/1cd34ee9-bf9f-4a41-8a43-0ac6ff403844

**Comment by TCOTC** [comment]
Win11 + AMD 看不见光标啊

**Comment by TCOTC** [comment]
这个问题 N 年都没修，我还是自己用 CSS 改样式吧
