### ISSUE TITLE
输入 `:` 加软回车的问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13004]
https://ld246.com/article/1730544136834

[video.webm](https://github.com/user-attachments/assets/7ea3bcaf-9a04-4835-8a8e-7d58492a9f6c)

**Comment by 88250** [comment]
这个符合 Markdown 表格语法的。

**Comment by TCOTC** [comment]
这是啥语法？

```
:
1
```

**Comment by 88250** [comment]
不好意思，前面我记错了，准确地说是：

```
0
-:
1
```

符合 Markdown 语法，但是思源转换的时候做了一些其他兼容调整，所以这个会被识别为表格。这个没法改动了。

**Comment by TCOTC** [comment]
但那是一个异常的块了，不是表格

**Comment by 88250** [comment]
好的，我们明天看看。
