### ISSUE TITLE
粘贴不了 MS Office Excel 内容的问题

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#1300]
### 描述问题 Describe the problem

excel 中复制简单表格, 无法粘贴

### 期待的结果 Expected result

可以粘贴

### 截屏或录屏演示 Screenshot or screen recording presentation

NA

### 版本环境 Version environment

* 版本 Version：0.6.6, 0.6.7
* 操作系统 Operating system：win10 x64
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

日志无相关信息

### 更多信息 More information

粘贴不了 Excel 内容的问题 #655

**Comment by 88250** [comment]
你好，我用一个很简单的示例测试了一下没有问题。

![issue](https://user-images.githubusercontent.com/873584/105935575-2a398500-608d-11eb-9a9a-3b13df7e8b1c.gif)

**Comment by yuuuxt** [comment]
我用类似的简单表格, 昨天在两台win10电脑上, 测试了一次0.6.6, 两次0.6.7, 均粘贴失败..

**Comment by 88250** [comment]
我这里重现不了，先关闭了……如果有进一步细节排查，请跟帖，谢谢。

**Comment by yuuuxt** [comment]
看截图并非是Microsoft Office, 问下有在MS Office上尝试重现吗? 我这里试过了2016, 2019及365的版本.

**Comment by 88250** [comment]
用的是 WPS，系统上暂时没装 MS Office，等有空的时候试试。
