### ISSUE TITLE
导出预览无法使用 Ctrl+A 全选文档内容

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13002]
https://ld246.com/article/1730533587227/comment/1730535415783#comments

**Comment by Vanessa219** [comment]
不需要全选，直接点击复制到公众号等按钮就可以复制了。

**Comment by TCOTC** [comment]
那个不是专门针对公众号、知乎修改过的吗？

话说手机上我怎么没见到语雀

**Comment by Vanessa219** [comment]
忘记为什么没有了，我加一下吧。语雀的是标准 md。
