### ISSUE TITLE
Improve data synchronization perception

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13000]
A 设备同步触发 B 设备感知，B 接收到同步消息后之前是做一次自动同步，这时可能出现 B 上面因为某些原因会出现数据变动，导致又重复触发 A 同步，导致死循环。

改为收到同步消息后仅做下载方向同步，完全覆盖本地数据避免死循环和一致性问题。

**Comment by TCOTC** [comment]
如果 A B 各有一些新数据的话（比如各有10篇新文档），B 的新数据是会被覆盖没掉吗？

**Comment by 88250** [comment]
会的
