### ISSUE TITLE
导入的文档右上角会有一个数据库角标，点击即消失

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13011]
不应该出现数据库角标。

[测试的文档.sy.zip](https://github.com/user-attachments/files/17610800/sy.zip)

**Comment by 88250** [comment]
因为块有这个属性：`custom-avs`

![image](https://github.com/user-attachments/assets/af968fcc-78f5-4c63-81a8-5eb151780e4d)

**Comment by TCOTC** [comment]
但是没有绑定数据库，就不应该有数据库角标啊

**Comment by 88250** [comment]
你发的这个文档应该是绑定过的。

**Comment by TCOTC** [comment]
对，但导入之后就没有绑定了，应该去掉关联

**Comment by 88250** [comment]
这个包是你手动压缩的还是？

**Comment by TCOTC** [comment]
文档树导出的

**Comment by 88250** [comment]
导出的时候数据库已经不存在了？

**Comment by TCOTC** [comment]
数据库在另一个文档，没有一起导出

**Comment by 88250** [comment]
懂了，改进了一下导入，没有对应数据库的话就去掉这个属性。

**Comment by TCOTC** [comment]
我这里还是会有数据库角标，没有去掉

**Comment by 88250** [comment]
我这用 issue 提供的测试文档重现不了哦。

**Comment by TCOTC** [comment]
> 我这用 issue 提供的测试文档重现不了

我也是。但你可以试试创建一个新文档，绑定了数据库之后导出再导入

**Comment by 88250** [comment]
这个没有问题，导出的时候会将该文档相关的数据库一并导出，所以再次导入就会还原。

**Comment by TCOTC** [comment]
但是点一下角标就消失了，不如导入的时候就去掉

**Comment by 88250** [comment]
我这边正常的，导入以后绑定关系还在，你导出一个我试试。

**Comment by TCOTC** [comment]
我等下一个 dev 再新建工作空间测试看看

**Comment by TCOTC** [comment]
见录屏：

[video.webm](https://github.com/user-attachments/assets/80613623-4f2a-4d08-8ba5-27067b96e69d)

[222.sy.zip](https://github.com/user-attachments/files/17730967/222.sy.zip)

**Comment by TCOTC** [comment]
> 导入 222 角标的问题我这里还是不能重现，导入后就没有角标。

我估计是因为工作空间存在那个数据库所以才没有去掉角标，你试试按我录屏的流程操作一遍

**Comment by 88250** [comment]
确实是这个问题，稍后改进。
