### ISSUE TITLE
Dynamically loading graph nodes and edges

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13014]

**Comment by TCOTC** [comment]
这个是想实现 Obsidian 那种效果吗？

**Comment by 88250** [comment]
不太一样的动画效果。

**Comment by TCOTC** [comment]
要不动态加载出来的时候再分散一点？一个大叉叉看起来怪怪的

![image](https://github.com/user-attachments/assets/e367988e-7523-44eb-b23a-828bbfc88b46)

**Comment by TCOTC** [comment]
确实，目前需要等很久才能缩放

**Comment by KuiyueRO** [comment]
还有一个小建议，文档块节点的颜色建议降低一些对比度，让它更接近背景色一些（偏灰白），白色背景下的黑色节点有点像蜘蛛眼睛

**Comment by 88250** [comment]
稍后稍微再看看能不能调整，这个估计暂时只能这样了。

**Comment by SaXz2** [comment]
![recording](https://github.com/user-attachments/assets/e6500327-e903-4786-ad34-605d19778ce2)
我有个一直存在的问题，时不时他就要转风车，建议修一修太怪了跟吃了炫迈一样

**Comment by TCOTC** [comment]
对，这个关系图一直在转圈以至于没法操作

**Comment by 88250** [comment]
等下个 dev 版看看。

**Comment by mustakshif** [comment]
有个新问题，节点大小设置得大一点这些节点运动就停不下来，只能往小了调


https://github.com/user-attachments/assets/cdb8971b-f47f-449b-82d4-a2f4565e05a2

**Comment by SaXz2** [comment]
![Clip_2024-11-05_23-34-29](https://github.com/user-attachments/assets/14bc684f-6d19-4af9-b91c-1dd2f9ef6fd5)
要不改这样？加个弧线也挺好看的

**Comment by TCOTC** [comment]
弧线没必要，就是要直线箭头才方便
