### ISSUE TITLE
行级样式复制粘贴为纯文本的问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13015]
https://ld246.com/article/1730648824893

没有正确粘贴为纯文本：

[video.webm](https://github.com/user-attachments/assets/08986b74-98b0-45f1-a7cf-dc01fe719e69)

**Comment by TCOTC** [comment]
@88250 其他元素也有问题：

[video.webm](https://github.com/user-attachments/assets/2c778af7-22a1-43fb-9d8f-4eeb69674317)

**Comment by 88250** [comment]
看上去只有一个加颜色的有问题？

**Comment by TCOTC** [comment]
Markdown 标记符全出来了

**Comment by 88250** [comment]
又改了一下，明天发版后看看。
