### ISSUE TITLE
指定路径查找 功能

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1301]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/105873461-786f6980-6036-11eb-82cb-602be15e974c.png)

如图，这是idea的路径查找：右键一个目录可以只搜索这个目录下的内容
关键词在大量目录存在，只想找到某个目录下的

### 描述最优的解决方案 Describe the optimal solution

类似idea的实现，搜索效果和全局搜索的一样

**Comment by 88250** [comment]
在搜索框中使用表达式 `path:xxx`，便捷入口暂时不考虑实现，感谢建议。
