### ISSUE TITLE
反链面包屑样式优化

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13018]
反链里的面包屑样式，或许可以适当淡化+缩小，以使得用户在视觉上 可以更好地聚焦内容本身。
![image](https://github.com/user-attachments/assets/cbc2c595-3db8-40ce-ae6e-bc5898bacf4a)

引用结构如下：
![image](https://github.com/user-attachments/assets/4ce5f102-e465-42ce-85d1-9f5beb0172a2)

**Comment by 88250** [comment]
样式就暂时不动了，和编辑器保持一致。
