### ISSUE TITLE
改进选中块或表格单元格后 `Backspace` `Delete` `Tab` `Shift+Tab` 的操作

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13027]
### 新方案：

选中块或选中单元格后，保留光标仅用于键入文本，但不应影响 `Backspace` `Delete` `Tab` `Shift+Tab`

- 选中块的情况下 `Backspace` `Delete` `Tab` `Shift+Tab` 应该是对这个块的操作
- 选中单元格的情况下 `Backspace` `Delete` 应该是对这个单元格的操作

### 旧方案：

1. 多选块后不再保留光标
2. 多选表格单元格后不再保留光标，然后实现按 Backspace 和 Delete 清空单元格

用户投票：https://ld246.com/article/1730715344779

![image](https://github.com/user-attachments/assets/838f2084-6767-4393-a95e-bceac09e1ba9)

---

关联 #10488

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/cac077ab-f64e-428b-93b2-7d1a8766d7cc)

**Comment by 88250** [comment]
不考虑了，单元格操作用菜单吧。

保留光标可以方便修改。

**Comment by TCOTC** [comment]
问题在于，多选的情况下，逻辑上是不应该直接编辑文本的

**Comment by TCOTC** [comment]
选中块之后仍保留光标会导致：[选中表格所在的列表项后按tab无法缩进](https://github.com/siyuan-note/siyuan/issues/13188)

**Comment by TCOTC** [comment]
以光标位置优先的话操作会非常反直觉：

[video.webm](https://github.com/user-attachments/assets/c3c19a03-cc2c-44b4-b7ed-effbbdf74bf9)

关联 #13188

**Comment by Vanessa219** [comment]
缩进和反向缩进选中的块需要为列表项，否则操作无效。

**Comment by TCOTC** [comment]
@Vanessa219 撤回之后光标能不能也回到原位（而不是开头）：

[video.webm](https://github.com/user-attachments/assets/62ef48ed-a5b3-4908-8b9a-a35bc7f3acd1)

**Comment by Jasonsey** [comment]
所以选中段落也是不能tab缩进吗？

**Comment by TCOTC** [comment]
看具体情况，有截图看看最好
