### ISSUE TITLE
使用快捷键将块添加至数据库应该对应块类型

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#13023]
### In what scenarios do you need this feature?

现在思源用快捷键添加到数据库的时候，会把对应光标所在的块的纯文本添加进数据库，而不是把光标所在位置对应的块添加进数据库。
举个例子，我光标在任务列表项里，然后用键盘快捷键添加至数据库内，但是数据库实际添加的不是这个任务列表项的块，而是任务列表项内容的纯文本，而块标菜单里的添加至数据库又是将任务列表块给添加进数据库里。
我认为快捷键的添加至数据库应该和块标里的保持一致，不然我模板列获取任务完成状态的时候就对应不上是任务列表了，只知道是个纯文本无法识别对应属性。

### Describe the optimal solution

键盘快捷键的添加至数据库功能应该与块标的添加至数据库功能实现保持一致。

**Comment by TCOTC** [comment]
正常，直接按快捷键添加的是列表项里的段落块。

点击列表项的快标再按快捷键就行了。

**Comment by 5kyfkr** [comment]
> 正常，直接按快捷键添加的是列表项里的段落块。
> 
> 点击列表项的快标（或者按两次 Shift+↑）再按快捷键就行了。

感觉没什么必要分成两种，制作闪卡的快捷键我印象里也有这个问题，同一个功能两种实现还是有点怪

**Comment by 88250** [comment]
不是同一个功能，Shift+↑ 是扩选。

思源是容器块嵌套，所以操作前需要选择需要的块，不是快捷键的问题，而是只能人去选择。
