### ISSUE TITLE
改进剪藏代码块解析

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#13026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

该文章发现代码块识别异常：https://mp.weixin.qq.com/s/xg10jQFf7AsiPQIBS1dRMg

### Expected result

文章正确摘录

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/b525dba3-6c2c-4294-9cba-d900c9a9e771)

### Version environment

```markdown
- Version: 3.1.10
- Operating System: Win 10 14939
- Browser (if used): Chrome 126
```

### Log file

https://mp.weixin.qq.com/s/xg10jQFf7AsiPQIBS1dRMg

### More information

文章中多处代码块应该都没识别到，当成html块处理了。这种代码块我F12看了下是code节点

**Comment by 88250** [comment]
感谢反馈，下个版本改进。
