### ISSUE TITLE
正则表达式搜索 `*` 的问题、支持打断搜索

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13021]
https://ld246.com/article/1730678393331

1. 搜索 `*` 之后就停不下来了，退出搜索窗口再重新搜索也还是停不下来。

2. 我觉得可以给一个按钮停止搜索：

![image](https://github.com/user-attachments/assets/664722fb-8a2a-42cc-a7cc-295961d997a8)

**Comment by 88250** [comment]
这个是正则报错了，已经添加提示，试试最新 dev 版。



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年11月4日(周一) 中午12:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 正则表达式搜索 `*` 的问题、支持打断搜索 (Issue #13021)




 
https://ld246.com/article/1730678393331
  
 
搜索 * 之后就停不下来了，退出搜索窗口再重新搜索也还是停不下来。
 
 
 
我觉得可以给一个按钮停止搜索：
 
  
image.png (view on web)

**Comment by TCOTC** [comment]
有提示了
