### ISSUE TITLE
关于在入口界面卡死问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1302]
### 描述问题 Describe the problem

在误启旧版本报错之后，启动了新版本，在入口界面卡死。（转圈动画有反应）

重启之后仍然没有解决。

![Snipaste_2021-01-27_10-43-32](https://user-images.githubusercontent.com/47321059/105935638-489f8080-608d-11eb-8326-45b01df41312.jpg)

### 版本环境 Version environment

* 版本 Version：0.6.7
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

日志记录截止在昨天晚上

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5877445/siyuan.log)

**Comment by dejavudwh** [comment]
重装 覆盖目录，解决了

**Comment by 88250** [comment]
好的，请再帮忙留意观察，谢谢。
