### ISSUE TITLE
复制数据库单元格支持粘贴为表格

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13025]
Wolai 是直接粘贴为表格的：https://github.com/siyuan-note/siyuan/issues/10488#issuecomment-2453284415

但考虑到思源的用户需求不同，我想到一个方案：

复制数据库单元格之后，在右键菜单增加一个“粘贴为表格”：

![image](https://github.com/user-attachments/assets/1091d01e-442d-4ea1-8be3-b53c088821fd)

关联 #10488

**Comment by 88250** [comment]
这个不考虑了，因为数据库字段后续会支持富文本 #11553 会导致普通表格解析出问题。

**Comment by TCOTC** [comment]
想了一下，如果选中的单元格内没有除段落块以外的行级元素，还是能粘贴为表格的
