### ISSUE TITLE
Search Bar Lag with Large Database Views

### ISSUE THREAD

**Issue by HamXaY09** [siyuan-note/siyuan#13029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I'm experiencing noticeable lag when I click on the search icon in the database. As shown in the video, the search bar lags when it opens. I'm using the default theme with no custom CSS or modifications.

The lag only occurs in the database view that contains a large number of entries. In the "All Products" view, I have over 100 entries, and when I filter it down to a specific view with only three entries, the search bar opens without any lag.

Please take a look at the video. I hope you can improve the animation and reduce the lag.

https://github.com/user-attachments/assets/a8985209-3966-471e-a60a-7735eb04a4bc

### Expected result

.

### Version environment

```markdown
- Version: 3.1.10
- Operating System: 
- Browser (if used):
```

### Log file

.

**Comment by HamXaY09** [comment]
And when I apply a theme, the lag is significantly noticeable in the 'All Products' tab, but in the 'Active Orders' tab, it is still reasonably usable.

https://github.com/user-attachments/assets/f6876ae4-d322-466d-8b7f-d778201d06a8

**Comment by Vanessa219** [comment]
Transition animation effects are performance-intensive, and you can use CSS snippets to remove the effects.

```css
.av__views .b3-text-field {
    transition: none;
}
```
