### ISSUE TITLE
能不能增加打印功能？

### ISSUE THREAD

**Issue by jidenanian** [siyuan-note/siyuan#13039]
### In what scenarios do you need this feature?

喜欢思源中主题搭配排版好的样式，但现在思源不支持打印功能，需要导出打印，但导出后有些样式会变化，如导出后题头图部分会单独成一个图片在笔记的上方，影响观感。

### Describe the optimal solution

思源能不能直接支持打印，打印成思源里的所见即所得。

**Comment by 88250** [comment]
你好，这个不支持，只能支持导出 PDF 后打印。

**Comment by jidenanian** [comment]
这个不好实现么？

**Comment by 88250** [comment]
应该不好实现，目前也没有开发资源能够投入到研究中。
