### ISSUE TITLE
Copy highlight text without html code

### ISSUE THREAD

**Issue by thienphuoc86** [siyuan-note/siyuan#13033]
### In what scenarios do you need this feature?

Example I highlight the text green with green color
![image](https://github.com/user-attachments/assets/8d27a5f4-3bef-4afc-b6c3-fbe0fdfbe029)
After that I copy the green text and paste to notepad. The result is "green" text not `<span data-type="text" style="color: var(--b3-font-color7);">green</span>`

### Describe the optimal solution

not yet

### Describe the candidate solution

not yet

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/07c9e705-ff75-4c8e-89de-d50c4aad192d)
