### ISSUE TITLE
Important Feature Requests for SiYuan to Boost Workflow and User Adoption

### ISSUE THREAD

**Issue by InayaWhoCodes** [siyuan-note/siyuan#13034]
### In what scenarios do you need this feature?

I've been following SiYuan's progress, and it’s amazing to see it reach over 20k stars! Even though I don’t use SiYuan daily because a few features are missing, I’m really excited and promise that once these features are added, I’ll fully support the project by buying a lifetime license. If I can, I’ll even donate more to show my appreciation. I’m hoping these features will be available in 2025 so I can switch everything from Obsidian and Notion to SiYuan, as I prefer having one system for all my needs.

**Here is my wish list of features that are crucial for my workflow:**

**Reminders:** The ability to set reminders on a database entry, text, or block, where I can select a date and time on a calendar, and get a notification when the time comes. This would be super helpful for staying on top of important tasks.

**Different Database Views:** Options like gallery view, kanban view, and list view. This is extremely important for me, and the main reason I’m not using SiYuan yet.

**Canvas:** A feature similar to what Obsidian has, where I can freely organize and connect my notes visually. This is essential for my work style.

**Database Automations:** Similar to Notion, where I can automate actions based on certain triggers in the database.

**AI Semantic Search in Database:** It would be amazing to search the database using natural language and have local AI understand my queries. This would make finding information much easier and more intuitive.

**SiYuan's Native AI Chat Window (Not Plugin Please):** Similar to Notion, but with support for local AI models. Since SiYuan is open-source, I hope it can support this better, making my workflow faster and more efficient.

**Web Clipper:** A tool similar to Notion's, allowing me to clip content from the web and save it directly to a database in SiYuan. Currently chrome extension is lacking so many features.

These features are incredibly important for my workflow. I sincerely hope the SiYuan developers consider adding them soon. These updates would make a huge difference and encourage more people like me to fully embrace and support SiYuan.

Thank you for considering this!

### Describe the optimal solution

.

**Comment by 88250** [comment]
Hello, we will start developing the Kanban view next year. Other features may have to wait. We also hope that community developers can participate to accelerate development. Thank you.

**Comment by Achuan-2** [comment]
I think gallery view is more important than kanban view. Gallery view can be used for card note management. It can also be used to manage recipes, books, and movies with covers. This is the habit of many Notion users.

**Comment by UsmanTechJive** [comment]
I also prefer Gallery View first.

**Comment by HamXaY09** [comment]
Gallery please 🙏

**Comment by itszarnish** [comment]
Once all of these features are added, I don't think anyone would consider other PKMs.

Gallery View +1

**Comment by Eli-808** [comment]
All features +1

**Comment by tiritibambix** [comment]
Reminders is a killer feature

**Comment by YusufDemir90** [comment]
+1

**Comment by Priya-V0** [comment]
Please! +1

**Comment by jackiallied** [comment]
+1

**Comment by itsOliviaTaylor** [comment]
+1
