### ISSUE TITLE
Add refresh button to message #156

### ISSUE THREAD

**Issue by unuunn** [siyuan-note/siyuan#13037]
### In what scenarios do you need this feature?

I'm using PWA with `start_url` commented out, this gives me the ability to open `/stage/build/desktop/` on a tablet and `/stage/build/mobile/` on a phone and install them as mobile apps normally. (The `/` path is blocked on nginx for security reasons)
I found a small bug though, not all devices can redirect normally to the `/check-auth?to=%2Fstage%2Fbuild%2Fdesktop%2F` page
Since PWA is running in `fullscreen` mode, it becomes impossible to get to the authorization page.

### Describe the optimal solution
For myself I fixed this problem by making the word `refresh` in the top message as `<button>` with `onclick=“window.location.reload()”`, I suggest to do so for all localizations, or add a forced refresh button under the message.

![2024-11-05_015525_min](https://github.com/user-attachments/assets/e5837db4-0bad-4cf6-804b-75e10facf350)

```patch
--- ru_RU.json     2024-10-22 05:25:00.000000000 +0300
+++ ru_RU.json  2024-11-05 01:34:57.000000000 +0300
@@ -1469,7 +1469,7 @@
     "153": "Скачанные файлы %d, части %d, полученные байты %s",
     "154": "Облако может поддерживать резервное копирование только до 12 снимков",
     "155": "Директория облачной синхронизации была сброшена до [главной]",
-    "156": "Аутентификация доступа не удалась, пожалуйста, обновите или переоткройте её",
+    "156": "Аутентификация доступа не удалась, пожалуйста, <button onclick=\"window.location.reload()\">обновите</button> или переоткройте её",
     "157": "Ключ не распознается, пожалуйста, подтвердите, что скопированная строка ключа правильная",
     "158": "Индексирование репозитория данных, прогулка по данным %s",
     "159": "Индексирование репозитория данных, получение последнего файла %v/%v",
```

**Comment by 88250** [comment]
Thanks for your feedback, we will improve it later.
