### ISSUE TITLE
导入markdown文件时块的创建时间晚于更新时间

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#13038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

关联 issue：https://github.com/siyuan-note/siyuan/issues/12962
在上面的issue中将yaml中的date和lastmod时间赋给了文档。经测试，文档内的块的更新时间也获得了正确处理，但是块的创建时间未被处理，导致创建时间晚于更新时间。
导入后文档的创建时间、更新时间正确：
![剪贴板图片](https://github.com/user-attachments/assets/2bedfea9-1621-4f1d-b61a-190823fd4ac3)

文档内的块的创建时间错误、更新时间正确：
![剪贴板图片 (1)](https://github.com/user-attachments/assets/b3c231c3-cbf0-4276-86fb-fa78849238e4)

### Expected result

块的创建时间应该和文档的创建时间一致。

### Version environment

```markdown
- Version: 3.1.11 dev11
- Operating System: win10
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
> 块的创建时间应该和文档的创建时间一致。

应该和块的更新时间一致吧？

**Comment by 88250** [comment]
呃，块的更新时间即文档更新时间，是一样的，稍后改进。
