### ISSUE TITLE
改进外观菜单

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13036]
目前外观菜单存在的问题：

- 颜色选项太小，看不清，建议放大显示成两行，并且在开头添加默认色选项（用于单独清除字体颜色或背景色）
- 字体颜色选项的 `A` 太小太细，看不清颜色
- 灰色外框（hover之后变成黑色）影响颜色判断

参考 Wolai：

![image](https://github.com/user-attachments/assets/4354a36e-ec60-4492-8b12-3ab3a8f7f270)

关联 https://ld246.com/article/1730735837514

**Comment by KuiyueRO** [comment]
![image](https://github.com/user-attachments/assets/5d9112e4-39f2-449a-85d9-35b19188b5fc)

> 左侧我自己做了些符合自己口味的修改，如圆角、下拉栏边框颜色等，这个不在建议范围内。

我的建议是：

1. 字体调粗一些：方便看到字体颜色
2. 每个选项略微增大：利于辨识
3. 移除每个选项外轮廓的 border/阴影：这个其实会干扰颜色的判断，
4. 还有个没做的，将样式弹窗的背景色与编辑器的背景色统一，方便一眼判断

总的来说就是减少不必要的干扰，然后一眼就能看清选择样式后的颜色。

**Comment by TCOTC** [comment]
@Vanessa219 两个问题：

### 01 暗黑模式下默认字体的颜色应该是白色：

![image](https://github.com/user-attachments/assets/78cffcec-8d4a-40d3-94dc-5cea143220f9)

### 02 可以把这个 `清除样式` 简化成一个垃圾桶图标，占 4 个格子感觉太宽了：

![image](https://github.com/user-attachments/assets/a6565615-66a1-446a-b4de-2981ae589693)

然后在悬浮提示里显示 `清除样式`：

[video.webm](https://github.com/user-attachments/assets/9824b739-d19e-45ee-8342-2196644d0733)

**Comment by TCOTC** [comment]
@Vanessa219 还有一个可以改进的地方：

目前的格子外框用的是 `box-shadow: 0 0 0 1px var(--b3-theme-surface-lighter) inset;`，可以改成 Wolai 这种透明色 `border: 1px solid rgba(0, 0, 0, 0.08);` ，能跟格子的背景色融合得更好

![image](https://github.com/user-attachments/assets/55d8a0e8-220c-43c3-b85d-99af4f3752f8)

**Comment by TCOTC** [comment]
@Vanessa219 图标需要再小一点

![image](https://github.com/user-attachments/assets/e8529c02-1950-4c74-bfcd-4a1f37766fe9)

**Comment by TCOTC** [comment]
@Vanessa219 字号和清除样式按钮的宽度还有一点问题：

![image](https://github.com/user-attachments/assets/65d33aff-cd21-4f88-8fef-9a9c1dfd78c7)

[video.webm](https://github.com/user-attachments/assets/30b8cf47-bb50-40c4-a7fb-d88f890d7544)
