### ISSUE TITLE
导出PDF出现样式错误

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#13030]
![Clip_2024-11-04_22-17-21](https://github.com/user-attachments/assets/174fd713-ec8c-4468-93dd-43e46c79f4cc)

![Clip_2024-11-04_22-18-41](https://github.com/user-attachments/assets/a1bdf9a1-55d0-4cff-84a7-7d920ef05703)

复现方式：出在这个 [ 上在这后面粘贴样式就坏了

**Comment by TCOTC** [comment]
看不懂，录屏看看

**Comment by SaXz2** [comment]
https://github.com/user-attachments/assets/e247332e-5313-4946-9704-41c556da51fd

@TCOTC

**Comment by TCOTC** [comment]
我能复现
