### ISSUE TITLE
复制网页上的图片，粘贴到笔记中会被自动转成base64码

### ISSUE THREAD

**Issue by o-ut-man** [siyuan-note/siyuan#1303]
复制网页上的图片，粘贴到笔记中会被自动转成base64码
复制本地的图片文件，粘贴到笔记中无反应
截图复制到剪切板的图片，可以正常粘贴
通过拖动本地的图片文件，可以正常拖到笔记中

**Comment by 88250** [comment]
复制转 Base64 是网页那端处理的；目前的确是需要剪切板中有才能粘贴，感谢反馈。
