### ISSUE TITLE
midnight主题的默认字体颜色应该是白色

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#13044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/01d3febe-fab3-4a5d-922e-7340c07b8c0e)

### Expected result

改白色

### Version environment

```markdown
- Version: v3.1.11
- Operating System: win10
- Browser (if used):
```

### Log file

1

**Comment by TCOTC** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/13036#issuecomment-2456959604

**Comment by royc01** [comment]
okok
