### ISSUE TITLE
Improve plain text comparison in data snapshot

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#13046]
### In what scenarios do you need this feature?

https://github.com/siyuan-note/siyuan/issues/12975

v3.1.11 之后，体验上升不少。不过还有两个小问题：

1. md 文档还是只显示路径
  
![image](https://github.com/user-attachments/assets/3e8a495a-77e8-4409-b9ea-748fd799ffac)

2. 顶部的标题我觉得还是直接显示完整路径比较方便对比；毕竟还是存在多个同名文件的情况的。

![image](https://github.com/user-attachments/assets/3189ea14-3261-4ed4-bee8-2439565fc39a)

### Describe the optimal solution

略

**Comment by TCOTC** [comment]
我提议：

1. 文件历史支持显示文件纯文本
2. 在首行添加文件路径

**Comment by 88250** [comment]
@TCOTC 文件历史暂时不改了
