### ISSUE TITLE
粗体、斜体、下划线和删除线继承块元素颜色

### ISSUE THREAD

**Issue by Mctalos** [siyuan-note/siyuan#13043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如果块设定了颜色样式appearance，对其中一些文字选择加粗，字体颜色变为黑色。
之前的版本不是这样的，会保留字体颜色的。

https://github.com/user-attachments/assets/bdaa32b1-9ec8-4730-828b-2d150cea2506

### Expected result

以前，对块设定样式appearance，里面输入的文字都会继承块的设定，对其中的某些文本字段进行加粗，是可以保留块所设定的颜色的。
现在不行了，加粗的文本字体颜色变回黑色。需要手动再设置颜色。比之前操作量增加了。

### Version environment

```markdown
- Version: v3.1.10
- Operating System: win10最新
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17629998/siyuan.log)

**Comment by Vanessa219** [comment]
应该一直都是这样的，22 年的代码就是这样的了，被以下样式重置了。

![QQ_1730810229396](https://github.com/user-attachments/assets/baf7302a-de65-4f51-a480-cae228ad7ffc)

**Comment by TCOTC** [comment]
一直都有用户反馈这个加粗之后字体变黑的问题来着。我建议统一去掉行级元素自带的黑色

![image](https://github.com/user-attachments/assets/255fb568-8ea3-4eb0-bd88-bb2c1a38ef5d)

**Comment by Mctalos** [comment]
> 应该一直都是这样的，22 年的代码就是这样的了，被以下样式重置了。
> 
> ![QQ_1730810229396](https://private-user-images.githubusercontent.com/970828/383147735-baf7302a-de65-4f51-a480-cae228ad7ffc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjkxNTMsIm5iZiI6MTczMDgyODg1MywicGF0aCI6Ii85NzA4MjgvMzgzMTQ3NzM1LWJhZjczMDJhLWRlNjUtNGY1MS1hNDgwLWNhZTIyOGFkN2ZmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNzQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDIyNDg4NTQ5YWM4N2FlMmE3NzAzMDU5ZmU1MDI4ZDRmYzQyNjA3MDIyYjljNWIwZTkxNzUwMjI4ZTQ5YzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LLkcCATjG_vyjCnbRNl-wnlr213Y2tZFuiT8J9yBDgs)


额，我把我的笔记又翻了看了下，确实是我记错了，我之前的用法是：设置了块的样式appearance，然后设置标题等级heading，是heading自带了加粗的效果，这个情况下，可以同时继承块appearance & heading的设置。


但是，我在想，块和文本 appearance设置、显示的优先级，可否优化下，我认为以下这种逻辑可能更好一点？
1. 文本同时继承 块appearance设置和 文本的设置（仅限加粗、下划线、斜体）。
2. 如果 对文本设置了appearance，和文本所属块的appearance设置冲突，则优先文本设置的appearance。

这样的话，和目前appearance 中 delete style 的操作逻辑保持一致，好一点，编辑的自由度、统一性也能更好一点。
