### ISSUE TITLE
关系图 getGraph 耗时太长

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13040]
![6abd95ccc421b94c345e6d7351a727bc](https://github.com/user-attachments/assets/561942d6-e6aa-4421-9938-337e1649b28b)

![8d2e9a4c50f9bd2750693896b0614c02](https://github.com/user-attachments/assets/9b885f97-6009-4504-b01d-656249540f7b)

**Comment by TCOTC** [comment]
那这个是能改进的吗

**Comment by 88250** [comment]
看下那个 getGraph 返回的 nodes 和 links 数量

**Comment by TCOTC** [comment]
当时的截图：

![632efd473605942d1b9a520fb0242730](https://github.com/user-attachments/assets/6dd52c3d-c1b7-4c99-a925-065aab79e464)

**Comment by 88250** [comment]
下个版本加个 LIMIT 看看。

**Comment by TCOTC** [comment]
加 LIMIT 之后会有什么影响呢？

**Comment by 88250** [comment]
做多只显示 10240 个节点

**Comment by TCOTC** [comment]
现在能秒出了
