### ISSUE TITLE
PDF文件链接支持网络url以及file协议，标注支持自动高亮

### ISSUE THREAD

**Issue by songshua295** [siyuan-note/siyuan#13042]
### In what scenarios do you need this feature?

1. 有的PDF书籍文件可能非常大，可能是必要的少数时候会使用，如果使用插入到资源中，同步时会占用过多的云空间以及流量，对同步速度也会有较大影响，希望能够支持网络url的pdf，通过网络请求pdf文件，而不是assets；
2. 目前的标注功能，每次**勾选文字之后都需要手动点击颜色才能进行标注**成功，在高效阅读的时候，这一点击操作不利于思维连贯，希望能够多一个自动标注的选项，能够在鼠标划过的时候自动有一种颜色标注，无须再次点击颜色，保证思维连贯性。

### Describe the optimal solution

1. notion、remnote、ob中的插件均有相关功能，此处不做演示。
2. 如remnote中，添加一个自动高亮的选项，勾选时，鼠标划过会自动高亮，思源中需要注意ctrl+v的标注不要失效。
![recording](https://github.com/user-attachments/assets/33aa1ba9-3bf3-4b35-81c0-1a111e4db901)

**Comment by 88250** [comment]
这个大概是实现不了了，本地的话可以考虑使用符号链接，符号链接不会被纳入同步。
