### ISSUE TITLE
网页端 PDF 查看引入按需载入或缓存

### ISSUE THREAD

**Issue by XcantloadX** [siyuan-note/siyuan#13041]
### In what scenarios do you need this feature?

通过网页查看 PDF 时，整个 PDF 文件会完整载入，而且没有缓存机制，每次查看都需要重新载入。

### Describe the optimal solution

按需载入，只载入当前查看的部分，其他部分翻到了再载入。

### Describe the candidate solution

首次载入 PDF 文件后缓存到浏览器中，避免每次都要加载。

**Comment by 88250** [comment]
这个主要看 PDF.js 的能力，目前已经是分片加载，但是 PDF 格式比较复杂，很多重要的元数据都是在末尾，参考：

* https://stackoverflow.com/questions/44747737/pdf-js-lazy-load
* https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#range
