### ISSUE TITLE
关于图片块设置居中之后，换行失效的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1304]
### 描述问题 Describe the problem

在插入图片块之后不进行操作，在图片块之间换行插入正常。

在图片块设置为居中之后，换行效果失效。（并且缩放的图片会变回原来大小）

### 截屏或录屏演示 Screenshot or screen recording presentation

![ew](https://user-images.githubusercontent.com/47321059/105949372-8f01d900-60a7-11eb-848d-f4bc8f948e9c.gif)

### 版本环境 Version environment

* 版本 Version：0.6.7
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
这个问题在 090 中应该已经修复，感谢反馈。
