### ISSUE TITLE
请教个技术栈的问题，关于跨平台构建应用的

### ISSUE THREAD

**Issue by ouchuji** [siyuan-note/siyuan#13045]
### In what scenarios do you need this feature?

我看Window Mac Linux 是通过electron 实现跨平台的， 那么Android 和 IOS的跨平台是通过哪个技术栈实现的呢？它们和Electron端用的同一套代码吗？ 还是说它们的代码是单独开发的

### Describe the optimal solution

同上，帮忙答疑下

**Comment by TCOTC** [comment]
关联：

- https://github.com/siyuan-note/siyuan-android
- https://github.com/siyuan-note/siyuan-ios

**Comment by ouchuji** [comment]
> 关联：
> 
> * https://github.com/siyuan-note/siyuan-android
> * https://github.com/siyuan-note/siyuan-ios

不好意思，没有安卓和IOS的开发经验，我看了那两个Repo，没有看太出来， 可以提示一下相关技术栈的名称吗？

**Comment by TCOTC** [comment]
我也不懂，只是知道仓库是分开的

**Comment by ouchuji** [comment]
> 我也不懂，只是知道仓库是分开的

@TCOTC  好的，还是谢谢啦

**Comment by 88250** [comment]
内核是跨平台编译的，请参考上述提到的仓库构建。

**Comment by ouchuji** [comment]
> 内核是跨平台编译的，请参考上述提到的仓库构建。

所有前端代码，后端代码逻辑，都是封装在内核中的吗？ @88250

**Comment by 88250** [comment]
前端不是，前后端是分开编译的，前端 TypeScript。

**Comment by ouchuji** [comment]
> 前端不是，前后端是分开编译的，前端 TypeScript。
好的，多谢，我再研究研究
