### ISSUE TITLE
云端笔记克隆失败

### ISSUE THREAD

**Issue by Precola** [siyuan-note/siyuan#1305]
### 描述问题：两台设备同步失败。有的文件备份成功，有的出现了这个问题：

![image](https://user-images.githubusercontent.com/46554831/105955352-1b64c980-60b1-11eb-98e0-7e18fb32b4ee.png)

**Comment by 88250** [comment]
你好，请上传一下日志文件，谢谢。

**Comment by Precola** [comment]
在哪里找到日志文件呢

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/105964973-db581380-60bd-11eb-8de0-971ff1fad603.png)

**Comment by 88250** [comment]
从日志上看可能是因为克隆时没有权限写入磁盘导致，换个克隆到本地存放的路径试试。

**Comment by Precola** [comment]
我试了 E、D盘下的一些路径还是不行。我今天在这个路径下克隆其他文件夹就成功了。但是有两个没有成功。

**Comment by 88250** [comment]
是不是有其他程序限制了磁盘读写，比如杀毒软件之类的。

**Comment by Precola** [comment]
我这个电脑没按杀毒软件 全靠windows的安全中心。把那个实时保护关了，也没有用。

**Comment by 88250** [comment]
感觉这个问题不好排查了……有空的话麻烦多帮忙试试，我先关闭了。如果能找到稳定重现的步骤或者有其他线索请随时跟帖，谢谢。
