### ISSUE TITLE
公式块工具栏按钮提示被遮挡

### ISSUE THREAD

**Issue by ShawElA** [siyuan-note/siyuan#13050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

鼠标悬浮在公式块工具栏按钮时，黑色气泡提示显示不完整。

### Expected result

出现完整提示

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/9a543507-dc59-4e9e-bb6b-a4b0ef9f8983)

### Version environment

```markdown
- Version: 3.1.11
```

### Log file

.

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/12747
