### ISSUE TITLE
改进上标链接复制粘贴和剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13056]
关联帖子 https://ld246.com/article/1730868913658

剪藏网址 https://www.zhihu.com/question/2127166482

![image](https://github.com/user-attachments/assets/c73810a4-4dc3-4aa7-b57f-121a75ce8826)

应该剪藏成链接：

![image](https://github.com/user-attachments/assets/f8b0ce1e-b1fb-4cce-a85d-2aa05f5aee6d)

**Comment by Achuan-2** [comment]
确实有问题，维基百科也这样
![PixPin_2024-11-07_11-36-00](https://github.com/user-attachments/assets/878bffa6-6455-4ae1-a95c-680bf5e2a55b)


![PixPin_2024-11-07_11-36-00](https://github.com/user-attachments/assets/a7ab39c3-3790-42e4-ad94-531f752e903a)
