### ISSUE TITLE
Apps in Chinese mainland app stores no longer provide AI access settings

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13051]
因为无法通过商店审核：

![image](https://github.com/user-attachments/assets/d78884dd-3f3d-4b59-b4b5-483d48680c62)

**Comment by pisceswb** [comment]
可以把ChatGPT的AI设置改名为Kimi API。他们好像是完全相同的请求模式。如果用户自己要使用ChatGPT的话，简单改一下模型和请求网址即可。

**Comment by 88250** [comment]
提供不了资质信息

**Comment by wish5115** [comment]
意思是以后ai用不了了？
建议提供一个插件版，这样也不影响用户使用体验。
可以暂时在ai设置中加上说明提醒用户，不然短时间内用户发现突然没了会感觉很奇怪。

**Comment by TCOTC** [comment]
像华为，集市都没有，感觉没什么必要
