### ISSUE TITLE
多选字段转换为单选字段后，仅显示单元格的第一个选项

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13054]
跟 https://github.com/siyuan-note/siyuan/commit/cf4e9f22ac7358da6cc4365a3cb4801c7d042c24 一起改了。

参考了 Wolai 和 Notion 的逻辑：

1. 转换之后原本单元格里的多个选项没有被删除，只是不显示，再切换回多选字段之后可以恢复显示
2. 修改单选时再删除原本的多个选项

**Comment by Vanessa219** [comment]
wolai 多选不可以粘贴到单选上。目前粘贴后仅使用第一个选项。粘贴时就不考虑列类型的转换了。

**Comment by TCOTC** [comment]
没看懂，我说的是转换字段类型之后单选字段单元格里有多个选项，应该只显示其中第一个选项

**Comment by Vanessa219** [comment]
这个应该已经修改了，如果还能重现的话，麻烦录屏一下。

**Comment by TCOTC** [comment]
就是说转换类型之后只应该显示首个选项：

[video.webm](https://github.com/user-attachments/assets/56a2c1a2-bbba-4a21-8509-a76f996b3200)

**Comment by Vanessa219** [comment]
@88250
