### ISSUE TITLE
Improve marketplace multi-language internationalization

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13053]
解决集市已下载中不显示插件的问题

1. 外观语言为中文，插件没有指定默认 README 与中文 README 的情况下，需要优先使用英文，其次使用其他语言

   比如不指定 default 的情况下 [siyuan-oembed](https://github.com/anarion80/siyuan-oembed) 插件就不能显示。

   ![image](https://github.com/user-attachments/assets/910656ed-8df2-4741-b88e-c4f9c253cda5)

2. 外观语言为指定语言，插件获取不到该语言 README 时，使用其他能获取到的 README

   比如之前五彩插件没有打包 README_zh_CN.md ，但 plugin.json 里又有 "zh_CN": "README_zh_CN.md" ，就导致在已下载中不能显示插件

3. 其他字段也一样

   ![image](https://github.com/user-attachments/assets/89baba75-c9b7-455b-9a92-396bb5adb8ab)

**Comment by TCOTC** [comment]
还有个语言显示不正确的问题：

![image](https://github.com/user-attachments/assets/aef5878c-a6ec-42da-a48e-5aeab3b954bd)

**Comment by 88250** [comment]
都使用 `README.md` 兜底吧。

**Comment by TCOTC** [comment]
如果没有打包 README.md(或者README) 的话也不行

**Comment by 88250** [comment]
这个是打包时要求打包的
