### ISSUE TITLE
一本日记导入思源笔记

### ISSUE THREAD

**Issue by tanziow** [siyuan-note/siyuan#13064]
### In what scenarios do you need this feature?

在思源笔记记录日记，但既往记录在一本日记上

### Describe the optimal solution

一本日记上零零散散记了1500条日记怎么快速导入思源笔记

**Comment by TCOTC** [comment]
思源仅支持导入 Markdown 文件夹，你可以尝试将一本日记导出的 .txt 文件处理为 .md 文件，或者向一本日记的开发者请求开发导出 Markdown 的功能。

**Comment by pisceswb** [comment]
一本日记有网页端，配合Web工具集成插件，应该可以将就着用。
