### ISSUE TITLE
Improve data synchronization to reduce the probability of conflicts

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#13065]
没有同时编辑的情况下发生同步冲突

### In what scenarios do you need this feature?

均是在用电脑，手机是挂在后台没有编辑操作的

第一次：Conflicted 2024-11-05 21:09:24

连续改了几个数据库的标题，每个数据库都有很多块

第二次：Conflicted 2024-11-06 21:22:52

普通编辑

### Describe the optimal solution

电脑日志：

[system-log (5).zip](https://github.com/user-attachments/files/17648162/system-log.5.zip)

移动端日志：
[system-log-3.zip](https://github.com/user-attachments/files/17648223/system-log-3.zip)

**Comment by 88250** [comment]
第一次冲突是因为 Android 端同步后计算出了新增文档，所以需要创建一个合并快照，然后继续推送 PC 端，而 PC 端也正在编辑这个文档，所以产生冲突：

```
/20230119231527-harn4t7/20230120000714-soczjxh/20241105210042-11cof2n.sy
```

请帮忙确认一下是不是这个文档冲突的。

第二次冲突是因为有个插件配置文件在 Android 端发生了变动：

```
I 2024/11/06 21:22:41 sync.go:240: cloud upsert [660f632063a2a097261ed14b3c41bc8294360355, /storage/petal/syplugin-document-search/search-setting.json, 2024-11-06 20:59:11]
I 2024/11/06 21:22:41 sync.go:246: local upsert [da6182dfd9bca03f877e67b58e299065e339cc67, /storage/petal/syplugin-document-search/search-setting.json, 2024-11-06 21:22:38]
```

以 Android 端 local 为准以后推送 PC 端，PC 端走的是下载快照，所以就和当前编辑冲突了。


麻烦帮忙确认一下第一点是不是这个文档冲突的。

**Comment by Jiangshuon** [comment]
应该不是的，这个文档没有冲突，冲突的是数据库中引用块所在的多个文档，不是数据库所在的文档，**我一次性冲突了几十个文档**

好像修改数据库标题后，会马上更新引用块右上角的数据库标题名，这相当于在编辑该文档

是不是这个原因容易引起冲突呢，如果数据库中块很多很多，这个过程中就相当于在不停地修改不同的文档，就容易引起冲突了

是不是块的数据库标题在修改后打开这个文档后才更新比较好呢，而不是立马就更新

我记得之前有个issue就是改成立马更新的，最开始是懒更新的
