### ISSUE TITLE
多选数据库条目的右键菜单支持 `复制主键文本`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13062]
目前只有单选纯文本条目的情况下才有 `主键`（建议改为`复制主键文本`），绑定块条目和多选条目的情况下也需要：

![image](https://github.com/user-attachments/assets/489afc4b-457f-4691-890e-313de53b1095)

关联 #11520

**Comment by TCOTC** [comment]
啥意思？

**Comment by Vanessa219** [comment]
多选以后都是这个菜单，复制的内容会根据主键是否绑定进行判断的。

![image](https://github.com/user-attachments/assets/0728bb6f-b2f2-4bc5-842f-c976dd2be160)

**Comment by TCOTC** [comment]
我的意思是在这个子菜单里再加一个 `复制主键文本`

**Comment by Vanessa219** [comment]
选中的都是没有绑定的显示，还是只要有一个是没有绑定的就显示，还是都显示？

**Comment by TCOTC** [comment]
都显示，需求是复制主键的纯文本。

选中一个主键的情况：

```
111
```

选中多个主键的情况：

```
* 111
* 222
* 333
```
