### ISSUE TITLE
改进数据库粘贴时包含逗号和换行的文本处理

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13068]
目前允许在选项中使用英文逗号，导致无法从外部复制多个选项粘贴到单元格中，出现了不一致的行为：

> 对比 Notion Wolai SiYuan

[video.webm](https://github.com/user-attachments/assets/b32f4f8c-44f3-460e-ae4d-f5363f06339d)

剔除英文逗号：

![image](https://github.com/user-attachments/assets/b0967cc4-21c4-44d7-b89d-31d40f6cdbdc)

关联 https://ld246.com/article/1730797541762

**Comment by 88250** [comment]
这个改进就不归入特定里程碑版本了，谢谢。
This improvement will not be included in a specific milestone version, thank you.

**Comment by TCOTC** [comment]
换行不应该去掉，换行之后的就是下一个条目的数据了

[video.webm](https://github.com/user-attachments/assets/68d00aca-0480-4e30-9f61-1fd65306ad02)

**Comment by Vanessa219** [comment]
是最新代码么？怎么看上去不太一样？

https://github.com/user-attachments/assets/0acfe08e-5dda-4886-81ff-e713810a5a28

**Comment by TCOTC** [comment]
我这里只选中了一个单元格：

![image](https://github.com/user-attachments/assets/106d358d-c4c2-44d8-915b-e14455ab8ab3)

**Comment by Vanessa219** [comment]
只选中一个单元格的话是全部内容都放在一个单元格里面

**Comment by TCOTC** [comment]
我录屏 0:15 的时候粘贴也有点问题，我建议用制表符来分隔单元格（Notion的方案），否则没法粘贴多行

**Comment by Vanessa219** [comment]
没看懂他们的方案，感觉很奇怪。只选中一个单元格的话他们也是全部拷贝的。你想改进的点是？

https://github.com/user-attachments/assets/6121bb6e-fae8-43c2-b7ed-a68be0884434

**Comment by TCOTC** [comment]
Notion 的处理应该是有 BUG，不过我的意思是用制表符来分隔单元格，这样粘贴的时候就能兼容单元格里出现空格的情况，不会把所有文本都粘贴到一个条目里

![image](https://github.com/user-attachments/assets/f1ea3888-578c-4075-9fd0-2093e84cb8c4)

**Comment by Vanessa219** [comment]
问题是从其他地方复制过来的不是制表符，如果是思源内部复制粘贴的话是没有问题的。

**Comment by TCOTC** [comment]
思源内部能实现复制粘贴应该就够了
