### ISSUE TITLE
内核连接中断

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1306]
### 描述问题 Describe the problem

一个朋友遇到的v0.6.7的内核连接中断

### 截屏或录屏演示 Screenshot or screen recording presentation

![2b89c69bca63c3054740a0ab33d57af](https://user-images.githubusercontent.com/47321059/105956053-2bc97400-60b2-11eb-89ec-8618caf4a9d2.png)

### 版本环境 Version environment

* 版本 Version：0.6.7
* 操作系统 Operating system：Win19
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5878320/siyuan.log)

**Comment by 88250** [comment]
日志上看应该没有问题，有可能是因为启用了网络代理导致的。如果没有启用网络代理，有可能是防火墙或者杀毒软件阻止了端口，请问一下你的朋友具体情况，谢谢。

**Comment by 88250** [comment]
另外，不要直接打开 .git 文件夹。
![image](https://user-images.githubusercontent.com/873584/105956435-c2963080-60b2-11eb-9815-4e27a0b1a93c.png)

**Comment by dejavudwh** [comment]
关闭代理后还是相同的问题，杀毒软件只有火绒和win10自带的。但是这两个杀毒我也在使用，都是正常的。

**Comment by 88250** [comment]
试下删除 ~/.siyuan/ 配置文件夹重启，如果还有问题，就看下 kernel 进程是否已经启动，如果 kernel 进程正常，但是界面还是报连接中断，那大概率还是网络访问不了导致。

**Comment by dejavudwh** [comment]
删除.siyuan解决了
