### ISSUE TITLE
文档标签页右键菜单增加更多内容

### ISSUE THREAD

**Issue by Cheng7966** [siyuan-note/siyuan#13066]
### In what scenarios do you need this feature?

文档树内容较多，想删除当前打开的文档需要鼠标寻找的文档树中的位置；希望能在文档标签页右键菜单增加更多内容，类似与文档树的右键菜单。
![Snipaste_2024-11-06_23-16-31](https://github.com/user-attachments/assets/9691ee65-9eee-4356-824c-6f9615467418)
![Snipaste_2024-11-06_23-16-49](https://github.com/user-attachments/assets/93d1f53a-d913-43ba-8a84-4ef8ac01584b)

### Describe the optimal solution

None

**Comment by TCOTC** [comment]
在这：

![image](https://github.com/user-attachments/assets/61d0e6ec-7de4-45c9-b7a2-10342eec072d)
