### ISSUE TITLE
Cisco Secure Client kills the app

### ISSUE THREAD

**Issue by m1nka** [siyuan-note/siyuan#13063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Using Cisco VPN ([Cisco AnyConnect VPN](https://www.cisco.com/site/uk/en/products/security/secure-client/index.html) kills the app when the VPN is connected. Once the VPN connection is established Siyuan crashes. If the Cisco Client is open but VPN is not connected everything is fine.

### Expected result

Ideally I would like Siyuan not to crash. Even something like an "Airplane mode" would be great, because really the app should not crash. It works offline as well. This makes Siyuan unusable for me :-/

### Screenshot or screen recording presentation

<img width="761" alt="Screenshot 2024-11-06 at 13 42 32" src="https://github.com/user-attachments/assets/7491e9f4-086a-4b50-b71a-861312ff7847">

### Version environment

```markdown
- Version: 3.1.11
- Operating System: MacOS 17.4.1
- Browser (if used): -
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17647377/siyuan.log)

**Comment by TCOTC** [comment]
Maybe you need to configure the proxy:

![image](https://github.com/user-attachments/assets/de116939-fc78-421b-aa92-fca33a174214)

**Comment by 88250** [comment]
Please resolve the network connectivity issue on your own, thank you.
