### ISSUE TITLE
文档树中图标支持悬浮后打开浮窗

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13061]
### In what scenarios do you need this feature?

需要有办法能直接打开一个文档的浮窗

### Describe the optimal solution

1. 文档树文档的右键菜单 `打开` 增加一个 `使用浮窗打开`
2. 页签菜单增加一个 `使用浮窗打开` ，如果页签是聚焦的，则打开的浮窗也聚焦

**Comment by Vanessa219** [comment]
页签的类型较多，浮窗不确定是否支持。先添加文档数文件名菜单。

**Comment by TCOTC** [comment]
除了文档、资源文件、搜索、间隔重复、插件的页签之外还要哪些类型？

能不能只限于在文档和资源文件页签上添加？

**Comment by Vanessa219** [comment]
目前页签上的设计是统一的，不确定多有页签都可以使用的情况下，不会进行添加。

**Comment by TCOTC** [comment]
那就先忽略页签。

另外在文档菜单也加一下 `使用浮窗打开`：

![image](https://github.com/user-attachments/assets/72262062-8999-44aa-a636-642121d7c9fc)

![image](https://github.com/user-attachments/assets/437818bc-4baf-403f-a210-148bd6d3be52)

![image](https://github.com/user-attachments/assets/e337f370-c124-4719-bf9a-b27bc183ecbe)

**Comment by Vanessa219** [comment]
这些地方 ctrl+hover 可以打开浮窗，文档树的话悬浮在文档块标上打开就可以了，没有必要再加一个菜单

![QQ_1731031635707](https://github.com/user-attachments/assets/341f70bf-f42c-4bf9-a19b-b2bb7db39546)

**Comment by TCOTC** [comment]
> 文档树的话悬浮在文档块标上打开就可以了

这个是不是有点容易误触了？

**Comment by Vanessa219** [comment]
但是这个和配置项会有点冲突，再想想看。
