### ISSUE TITLE
List only 256 unreferenced assets

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13075]
https://ld246.com/article/1730941950880

未引用资源太多可能会导致前端异常，下个版本会调整返回上限，最多仅列出 256 条未引用资源，但是点删除的话还是会全部一次性清理

**Comment by TCOTC** [comment]
256 会不会少了一点？我刚刚清理 450 个都没遇到问题

**Comment by 88250** [comment]
那加到 512 吧，太多了也没法看，基本都是批量删了。

**Comment by TCOTC** [comment]
如果结果数超过 512 的话，我觉得需要在最底下增加一行提示

![image](https://github.com/user-attachments/assets/f825e560-655e-4323-9275-4132d4cbdbfa)
