### ISSUE TITLE
选中包含备注与行级代码的文本后右键菜单的问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13078]
[video.webm](https://github.com/user-attachments/assets/6ff479af-36c4-446c-8c02-bd3abf1c1bcd)

关联 https://ld246.com/article/1730973381703

类似的问题：#12673

**Comment by Vanessa219** [comment]
颜色在输入框中输入 #色值即可，已修改下列问题
* [X] 回填
* [X] 格式化
* [X] tab 圆角
* [X] 位置偏移

**Comment by Vanessa219** [comment]
这是正常的，右键点击什么元素就弹出该元素的菜单

**Comment by TCOTC** [comment]
但是这里根本没有 HTML 块

**Comment by Vanessa219** [comment]
这个问题修复 https://github.com/siyuan-note/siyuan/issues/12673 的时候就不会出现了。
