### ISSUE TITLE
啥时候支持分享，web端

### ISSUE THREAD

**Issue by gsh456** [siyuan-note/siyuan#13076]
### In what scenarios do you need this feature?

自建docker ，分享功能，希望加入分享功能再入。

### Describe the optimal solution

自建docker ，分享功能，希望加入分享功能再入。

**Comment by 88250** [comment]
你好，请考虑使用发布服务，另外没有计划加入内容粒度相关权限控制，感谢反馈。

**Comment by gsh456** [comment]
好吧，不入了，继续 trilium

**Comment by Jiangshuon** [comment]
自我意识过剩

**Comment by luo-chuan** [comment]
> 没有计划加入内容粒度相关权限控制

可以折中一下，给一个笔记本级别的权限控制就行。

**Comment by Huppert96** [comment]
> 自我意识过剩

讲道理这个东西真的还挺有必要，老是自己想各种办法搞插件，搞分享，但是还是不如官方来一个，自部署版本反正是有服务器的，能访问服务器，就能访问服务器分享出来的页面，顶多加个密码校验之类的呗，类似百度网盘，再加个过期时间，其实基本上就完活了。
