### ISSUE TITLE
列表复制纯文本缺少序号

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13072]
比如这种场景，需要粘贴纯文本的同时保留序号，直接复制粘贴有序号但也有块引用、复制纯文本再粘贴没有块引用但也没有序号：

![0d12872b9965d156595d0865adbf31bd](https://github.com/user-attachments/assets/b1d0524d-439f-4d91-b6fb-2fedc8edac60)

**Comment by 88250** [comment]
这个不考虑改变了，网页上复制列表也是只有文本，没有序号的。
