### ISSUE TITLE
导入的 MarkDown 文档中如果图片是 HTML 格式的, 则图片导入不进去

### ISSUE THREAD

**Issue by jssda** [siyuan-note/siyuan#13087]
### In what scenarios do you need this feature?

导入的markdown文档中, 图片书写格式为
```html
<div>
<img src="test.png" style="zoom:50%;">
</div>
```
图片导入不进来

### Describe the optimal solution

希望能够支持此项功能

### Other information

思源版本:  v3.1.10

**Comment by jssda** [comment]
https://github.com/siyuan-note/siyuan/issues/13080#issue-2641063640

**Comment by TCOTC** [comment]
> 思源版本: v3.1.10

v3.1.11 已经改进过了，v3.1.12 会继续改进细节
