### ISSUE TITLE
启用：启动时关闭所有页签 功能，打开后如何让左侧文档树也回到全部折叠的状态？

### ISSUE THREAD

**Issue by lu161513** [siyuan-note/siyuan#13084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在文档树设置中启用了：启动时关闭所有页签 功能
打开后如何让左侧文档树依然会展开到我上次展开的那层，希望打开时也折叠所有文档树，每次开启程序恢复到所有树未展开，文档未打开的状态
![1](https://github.com/user-attachments/assets/8417a757-d5e3-4189-91d7-8b5c6e7b3366)
![2](https://github.com/user-attachments/assets/3e9b97ec-2432-47a5-bc08-bc7b678568aa)

### Expected result

希望打开软件后，如果开启了启动时关闭所有页签 功能，希望左侧文档树可以折叠

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

NONE

**Comment by 88250** [comment]
请参考 https://ld246.com/article/1728469520911
