### ISSUE TITLE
双链浮窗 Esc 键关闭

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1308]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/105998449-9e087b80-60e7-11eb-8e07-e2d4a28de18b.png)

如图，这是一个双链浮窗的使用case
一般双链的查看，都是看一看迅速了解之后，然后希望速度关闭，回到原文
为了快速关闭，需要移动鼠标点击x
这个过程还是不够快，而且 x 不大 有时候后点不准，影响阅读和笔记节奏

### 描述最优的解决方案 Describe the optimal solution

提供 esc关闭 比较准确和快速

**Comment by roverway** [comment]
弹窗出来后，点击谈窗外区域，弹窗就会消失了，也很快。

**Comment by wo4wangle** [comment]
> 弹窗出来后，点击谈窗外区域，弹窗就会消失了，也很快。

嗯，这样是又快了一些：毕竟可以点的区域更大
不过还是得想点哪里：浮窗形式不固定
语法密度比较高的时候，乱点还会出现编辑语法：比如加粗、代码块，影响连贯性

按键是固定的，也没有副作用
