### ISSUE TITLE
希望可以依次浏览数据库中的图片，目前只能单张单张地看

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#13082]
### In what scenarios do you need this feature?

只要图片不在数据库中，就可以，在数据库中就不行

![image](https://github.com/user-attachments/assets/055585ff-87fa-4915-9228-7c85c930d770)

![image](https://github.com/user-attachments/assets/35d75763-ed07-41c8-bcce-c57844e63b64)

### Describe the optimal solution

。。

**Comment by SaXz2** [comment]
支持这个功能，我也会跟一样这么用，加个切换确实方便很多
