### ISSUE TITLE
导出预览模式优化排版后卡住

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13081]
![image](https://github.com/user-attachments/assets/53665ccf-5e5c-4744-a987-cd9a4c540dae)

**Comment by 88250** [comment]
我这里无法重现问题，需要上传能够重现问题的 .sy.zip

**Comment by TCOTC** [comment]
我这里随便一个文档都这样

[video.webm](https://github.com/user-attachments/assets/5698c916-921d-4ce8-8f11-ed766e4e1364)

**Comment by 88250** [comment]
哦，这样能重现了。

@Vanessa219
