### ISSUE TITLE
Resume Showing Breadcrumb in Embed Blocks

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#13099]
### In what scenarios do you need this feature?

Relate： https://ld246.com/article/1731152697050 
As figure show：
![Screenshot_20241109_210452_org_b3log_siyuan_MainActivity](https://github.com/user-attachments/assets/8f157373-95e5-404f-82ab-ed13403fcab4)

I have turn on this option, but it did not work:
![Screenshot_20241109_211439_org_b3log_siyuan_MainActivity](https://github.com/user-attachments/assets/046880fa-621b-4c1d-bf5e-89f91156b90c)

### Other information

The version of SiYuan: 3.1.11 Android

**Comment by TCOTC** [comment]
1. 你这个是新建的工作空间吗？
2. 下载最新的 dev 版试试看还有没有这个情况
3. 导出 Data 上传一下看看

我这里是能正常显示面包屑的：

![image](https://github.com/user-attachments/assets/54c18b34-1a35-4570-a9f3-651bff7931fc)

**Comment by luo-chuan** [comment]
> 1. 你这个是新建的工作空间吗？
> 2. 下载最新的 dev 版试试看还有没有这个情况
> 3. 导出 Data 上传一下看看

1. 不是新建的工作空间，只是把其它笔记本关闭了。
2. 我用的安卓版，没有dev版本。
3. 如下
[Test.sy.zip](https://github.com/user-attachments/files/17687947/Test.sy.zip)

**Comment by luo-chuan** [comment]
刚刚试了下，关闭所有插件和代码片段，此bug依然存在。因此排除插件和代码片段的影响。

**Comment by TCOTC** [comment]
如果方便的话请试试看同版本的桌面端（伺服）显不显示面包屑

**Comment by luo-chuan** [comment]
> 如果方便的话请试试看同版本的桌面端（伺服）显不显示面包屑

3.1.11版本的桌面端和伺服端也有同样的问题。
