### ISSUE TITLE
右键菜单复制或剪切行级标签时使用 HTML

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13092]
https://github.com/siyuan-note/siyuan/issues/11604#issuecomment-2198423839

关闭行级标签语法之后，复制标签再粘贴会粘贴为 `#foo#` 而不是标签

这两个：

![image](https://github.com/user-attachments/assets/4d8be39d-1847-4ae6-97df-f6cc9dca589a)

**Comment by Achuan-2** [comment]
直接选中按Ctrl+C是没问题的，只有在菜单里点击复制才会有问题

**Comment by 88250** [comment]
这个改进就不归入特定里程碑版本了，谢谢。
This improvement will not be included in a specific milestone version, thank you.
