### ISSUE TITLE
动态图标自定义文本支持换行和模板

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13095]

**Comment by 88250** [comment]
不考虑支持换行了，模板应该是可以的，直接改文档 icon 属性。

**Comment by TCOTC** [comment]
我是说在这里填 `.action{　}` ：

![image](https://github.com/user-attachments/assets/d2dc80d2-9cb2-4e96-9c64-b07a74d10bf3)

**Comment by 88250** [comment]
需要哪些变量呢？

**Comment by TCOTC** [comment]
能支持的变量都支持吧

![image](https://github.com/user-attachments/assets/5b83bbd4-accb-460b-9f08-3a1a8cdbea91)

**Comment by 88250** [comment]
目前似乎没有传入 id 参数 @Vanessa219 评估一下看看是否能实现传入 id

**Comment by TCOTC** [comment]
我看不懂了……是我理解的这个模板和变量吗？

![image](https://github.com/user-attachments/assets/e3602b95-3c45-4822-87ea-a1329c668505)

填在这里：

![image](https://github.com/user-attachments/assets/695845f6-c5e6-4df8-93b1-81ed50798a27)

**Comment by TCOTC** [comment]
话说换行为什么不支持一下，这个图标的高度刚刚好能放下两行文本

**Comment by 88250** [comment]
是这个用法

**Comment by 88250** [comment]
因为是存在属性里，换行支持比较复杂，所以目前不考虑改动了。
