### ISSUE TITLE
数据库资源字段支持 PDF 标注

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13093]
用户反馈：

![6f8a58aa2183dda0b55adfe7d472e46a](https://github.com/user-attachments/assets/f7d9724c-d5b5-4a6c-99de-7119c917280e)

**Comment by 13953889506** [comment]
希望早点实现

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/11553 中考虑，感谢反馈。
