### ISSUE TITLE
Automatic purge for local data repo

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13091]
在一定的时间间隔内保存指定数量的**未标记的快照**，如：

- 1 天内：无限制
- 2\~3 天内：20 个快照（比如 2\~3 天内有 100 个快照，就每删 4 个快照保留 1 个快照）
- 4\~7 天内：40 个快照
- 8\~30 天内：115 个快照
- 31\~100 天内：175 个快照
- ……

按快照具体时间与当前具体时间的差计算，而不是按日期。

分开配置：

- 云端快照自动清理策略
- 本地快照自动清理策略

---

关联需求:

#10787 https://github.com/siyuan-note/dejavu/issues/8

![image](https://github.com/user-attachments/assets/b8a040c0-8cc3-4e32-baca-16451d10842e)

**Comment by 88250** [comment]
云端的不考虑改变策略了，本地的后续考虑看看。

**Comment by 88250** [comment]
考虑了下，清理策略如下：

* 每天最多保留 x 个快照，默认 2 个
* 保留最近 y 天的快照，默认 180 天

**Comment by TCOTC** [comment]
配置界面长啥样？

**Comment by 88250** [comment]
设置 - 关于 

![image](https://github.com/user-attachments/assets/25c4928a-7b1f-4f0f-8197-0d9c6db8aa25)


等会打个 dev 版

**Comment by TCOTC** [comment]
用户更新之后自动清理掉大量快照的话感觉不是很妙，因为用户可能希望保留这些快照

**Comment by TCOTC** [comment]
还有就是这个配置应该在重启思源之后生效。不然手残输入一个很小的数就麻烦了

**Comment by 88250** [comment]
就这样吧，清理掉是这个 issue 的目的。

**Comment by TCOTC** [comment]
> 每天最多保留 x 个快照，默认 2 个（保留每天最后一个，其他随机保留）

这个随机有点怪，为什么不平均分布呢？

**Comment by 88250** [comment]
按时间平均不一定是最优



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Sun, Nov 17, 2024 01:56 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Automatic purge for local data repo (Issue#13091)




  
每天最多保留 x 个快照，默认 2 个（保留每天最后一个，其他随机保留）
  
这个随机有点怪，为什么不平均分布呢？

**Comment by TCOTC** [comment]
但是完全随机不是更差吗

**Comment by 88250** [comment]
随机更好，因为快照本身就无法判断重要性，所以随机反而更平均。

**Comment by TCOTC** [comment]
有个开关的话也需要默认开启，否则用户不会主动开启。

但新增的开关不能默认开启，所以还是不加开关更好。

**Comment by zxhd863943427** [comment]
但是，在用户设置前，就已经自动执行了

**Comment by zxhd863943427** [comment]
而且，默认设置的频率也不一定是用户需要的。

**Comment by 88250** [comment]
> 这导致默认的180天以前的快照会完全丢失

正在紧急修复，争取等会发版 https://github.com/siyuan-note/siyuan/issues/13203

**Comment by 88250** [comment]
新版本已经发布。
