### ISSUE TITLE
代码片段有概率出现无法同步现象

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#13101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

参考以下视频，win端把(0,0,0)改成(20,0,0)后同步，docker端同步后还是(0,0,0)，然后win端再次同步后，又把docker端的(0,0,0)数据同步过来，把(20,0,0)给还原成(0,0,0)了。然后再次尝试后docker端又能正常同步过去了。

https://github.com/user-attachments/assets/f97b3936-1ea8-4055-a7b0-de0e32ce8fc1

### Expected result

能每次准确同步，不丢同步。这个是个老问题，一年前就发现有，这版本说是有优化同步最新快照但是还是会出现。

### Version environment

```markdown
- Version: 3.1.11
- Operating System: win11
- Browser (if used):3.1.11
```

### Log file

[system-log (win端日志).zip](https://github.com/user-attachments/files/17688601/system-log.win.zip)
[system-log (docker端日志).zip](https://github.com/user-attachments/files/17688602/system-log.docker.zip)

**Comment by 88250** [comment]
麻烦发一下快照 id 或者出现问题的时间点。

**Comment by 5kyfkr** [comment]
![image](https://github.com/user-attachments/assets/324ddf59-b699-4c24-9a7e-5fc939dce86e)
对应视频里是这几笔同步快照

**Comment by KuiyueRO** [comment]
同样遇到过

**Comment by 88250** [comment]
被 docker 端覆盖是因为 docker 端在 00:08:44 做了一次编辑

![image](https://github.com/user-attachments/assets/5dc29412-1716-4767-83c2-15d78f578d69)

**Comment by 88250** [comment]
我先关闭了，后面如果在没有多端编辑的情况下还能重现问题麻烦跟帖补充，感谢反馈。

**Comment by 5kyfkr** [comment]
> 被 docker 端覆盖是因为 docker 端在 00:08:44 做了一次编辑

这不能解释我00:09:14在pc端编辑了然后点了同步了，那云端最新的应该是pc的吧，然后docker版00:09:21后续也再次同步了，应该就是从云端取了最新的

**Comment by 88250** [comment]
pc 端 09:14 同步后 5afde0ba86687a3b3cfc09d02e10b82dd85cd26d 快照到云端已经是最新的了，但是 docker 端 00:09:21 下载到最新的以后发现本地文件有变动，这个时候会做一个文件级冲突判断：如果本地修改早于云端 7 分钟则使用云端覆盖本地，但这个文件的修改时间是 00:08:44，所以就用本地覆盖云端了，所以再次在 pc 端同步以后就覆盖了 pc 端本地 00:09:05 的文件。

本质上就是因为这个文件在 docker 端改动过，所以得看看为啥会有改动。

**Comment by 5kyfkr** [comment]
我当时是反复测试想复现这个问题，所以来回在docker和pc端修改同步，应该是08:44我修改了但是没同步，然后先去pc端改了再同步，然后就复现了。这个本地修改早于云端7分钟的逻辑是怎么定的，感觉好像有点不符合同步的直觉

**Comment by 88250** [comment]
因为多端本地都可能会有修改，在无法使用统一时间服务的情况下只能使用本地设备时间，但是本地时间也存在误差，所以必须有一个时间段来界定覆盖方向。

**Comment by 5kyfkr** [comment]
了解，我再观察测试下超过7分钟的情况

**Comment by 88250** [comment]
麻烦发下日志



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月11日(周一) 晚上9:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 代码片段有概率出现无法同步现象 (Issue #13101)




 
image.png (view on web)
 又复现了次，回家路上在手机端增加了个“测试测试”空白片段，然后刚才在PC端把这个空白片段删了
 image.png (view on web)
 image.png (view on web)

**Comment by 5kyfkr** [comment]
[system-log (docker日志).zip](https://github.com/user-attachments/files/17703292/system-log.docker.zip)
[system-log (win日志).zip](https://github.com/user-attachments/files/17703294/system-log.win.zip)

**Comment by 88250** [comment]
还需要手机端的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月11日(周一) 晚上9:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 代码片段有概率出现无法同步现象 (Issue #13101)




 
system-log (docker日志).zip
 system-log (win日志).zip

**Comment by 5kyfkr** [comment]
我是手机上用网页docker版

**Comment by 88250** [comment]
哦哦，稍后分析



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月11日(周一) 晚上9:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 代码片段有概率出现无法同步现象 (Issue #13101)




 
我是手机上用网页docker版

**Comment by 88250** [comment]
还是之前的问题，代码片段在 docker 端上同步前有修改：

```
I 2024/11/11 21:34:24 sync.go:240: cloud upsert [ed045abed3a0122504bb78d79b60c15a3537369a, /snippets/conf.json, 2024-11-11 21:26:05]
...
I 2024/11/11 21:34:24 sync.go:246: local upsert [cb1aa39af084d81a62255de93e207a92a5f3ad57, /snippets/conf.json, 2024-11-11 21:27:10]
```

21:27:10 这个时间在 docker 上改动过。

**Comment by 5kyfkr** [comment]
> 还是之前的问题，代码片段在 docker 端上同步前有修改：
> 
> ```
> I 2024/11/11 21:34:24 sync.go:240: cloud upsert [ed045abed3a0122504bb78d79b60c15a3537369a, /snippets/conf.json, 2024-11-11 21:26:05]
> ...
> I 2024/11/11 21:34:24 sync.go:246: local upsert [cb1aa39af084d81a62255de93e207a92a5f3ad57, /snippets/conf.json, 2024-11-11 21:27:10]
> ```
> 
> 21:27:10 这个时间在 docker 上改动过。

奇了怪了，21点27分我没有打开docker客户端，我在21点30分pc端同步后才打开的
![image](https://github.com/user-attachments/assets/2345191b-4768-4fef-ab70-2c7023b870a4)

**Comment by 88250** [comment]
> 会不会是docker自己后台同步了做了修改

思源自己应该不可能会去修改文件，但是不排除外部修改。

**Comment by 88250** [comment]
你那边只有代码片段出现这样的问题？

**Comment by 5kyfkr** [comment]
> 思源自己应该不可能会去修改文件，但是不排除外部修改。

我又回想了一下，那四次pc端同步速度比较慢，可能是在那中间我打开了docker端然后先看了下代码片段有没同步过来，也就是21时27分左右，然后在21时34分再点了同步，但是同步完没效果。我可以确认的是我21点27分仅打开了docker端没做任何编辑操作

**Comment by 5kyfkr** [comment]
> 你那边只有代码片段出现这样的问题？

我这边还遇到过memos同步插件，一端把memos数据同步到笔记本过后同步，另一端点同步没有更新

**Comment by 88250** [comment]
后续请注意关注是否有发 setSnippet 这个请求

**Comment by 5kyfkr** [comment]
> 后续请注意关注是否有发 setSnippet 这个请求，这个请求会改变文件

在开发工具看似乎一打开docker端就会有，我下次确保其他客户端没打开的情况下会不会复现吧

**Comment by 88250** [comment]
不是 getSnippet 是 setSnippet

**Comment by 5kyfkr** [comment]
![image](https://github.com/user-attachments/assets/2b5f9ed5-b8fe-4098-9cb0-20d9dae45cfa)
我这似乎是有

**Comment by 88250** [comment]
收到

 @Vanessa219 看一下

**Comment by 88250** [comment]
@5kyfkr 我们这里无法重现打开就发送 setSnippet，麻烦录屏演示一下。

**Comment by 5kyfkr** [comment]
https://github.com/user-attachments/assets/494ae935-3c90-4508-a772-f2b28e7a3cb4

这是我公司的电脑客户端上也有

**Comment by 88250** [comment]
看上去是这个插件调用的：

![image](https://github.com/user-attachments/assets/c8445c21-75d3-4c53-87e6-30269ad5a795)

**Comment by 88250** [comment]
麻烦给插件仓库反馈一下。稍后我们也会改进 setSnippet 接口，如果数据没有变动，则不写入文件（不会改变文件时间），这样就不会被再次同步了。
