### ISSUE TITLE
Docker 网页只读模式下，前进后退不可以用

### ISSUE THREAD

**Issue by ouchuji** [siyuan-note/siyuan#13104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图，在文档中点击跳转到另外一个文档，之前按后退可以退回原文档的，现在前进后退都是灰色的，无法正常前进后退，跳转后返回原文档很不方柏霓
![image](https://github.com/user-attachments/assets/2200ef8c-5495-4f24-812f-54e7dd80e2e2)

### Expected result

前进后退可以生效，和编辑模式那样

### Version environment

```markdown
- Version:  v3.1.11
- Operating System: Docker
- Browser (if used): Chrome 130.0.6723.117
```

### Log file

无报错

**Comment by ouchuji** [comment]
@88250  这个可以帮忙看下吗？

**Comment by 88250** [comment]
@Vanessa219 抽空看看

**Comment by Vanessa219** [comment]
前进后退记录的是光标的位置，只读的时候没有光标，可以使用 ctrl+E 进行切换。

**Comment by ouchuji** [comment]
@Vanessa219  试了Ctrl+E， 显示出来的是个搜索弹窗， 只读模式确实没有光标的，那么意思是只读模式前进后退就是不可以用的是吗？

**Comment by TCOTC** [comment]
@Vanessa219 能不能再记录一下页签切换？目前客户端的页签切换也是没有光标的

**Comment by Vanessa219** [comment]
@ouchuji 是的

@TCOTC 页签切换时，编辑器内以前有光标的就有，没有的话不会随便生产一个光标的。

**Comment by ouchuji** [comment]
那这块可以优化一下，确实只读模式下，如果没有返回前进功能确实比较麻烦 @Vanessa219

**Comment by Vanessa219** [comment]
可以用 ctrl+e
