### ISSUE TITLE
echart显示空白，没有显示报错

### ISSUE THREAD

**Issue by Littleweisheit** [siyuan-note/siyuan#13103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

把echart实例https://echarts.apache.org/examples/zh/editor.html?c=sunburst-borderRadius
用chatgpt转json后导入思源
```
{
  "data": [
    {
      "name": "Grandpa",
      "children": [
        {
          "name": "Uncle Leo",
          "value": 15,
          "children": [
            {
              "name": "Cousin Jack",
              "value": 2
            },
            {
              "name": "Cousin Mary",
              "value": 5,
              "children": [
                {
                  "name": "Jackson",
                  "value": 2
                }
              ]
            },
            {
              "name": "Cousin Ben",
              "value": 4
            }
          ]
        },
        {
          "name": "Father",
          "value": 10,
          "children": [
            {
              "name": "Me",
              "value": 5
            },
            {
              "name": "Brother Peter",
              "value": 1
            }
          ]
        }
      ]
    },
    {
      "name": "Nancy",
      "children": [
        {
          "name": "Uncle Nike",
          "children": [
            {
              "name": "Cousin Betty",
              "value": 1
            },
            {
              "name": "Cousin Jenny",
              "value": 2
            }
          ]
        }
      ]
    }
  ],
  "option": {
    "series": {
      "type": "sunburst",
      "data": "data",
      "radius": [60, "90%"],
      "itemStyle": {
        "borderRadius": 7,
        "borderWidth": 2
      },
      "label": {
        "show": false
      }
    }
  }
}
```

### Expected result

显示这个图表
![图片](https://github.com/user-attachments/assets/70dfea0e-a3f4-421f-b02d-35e5bd7a7e87)

### Screenshot or screen recording presentation

下面空白处
![图片](https://github.com/user-attachments/assets/09e6720c-9b0d-45cf-905f-68309b53fe0e)

### Version environment

```markdown
- Version: 3.1.10
- Operating System: Win11
- Browser (if used):
```

### Log file

I 2024/11/10 12:13:19 conf.go:598: exiting kernel [force=false, setCurrentWorkspace=true, execInstallPkg=0]
I 2024/11/10 12:13:19 sync.go:193: sync before exit
I 2024/11/10 12:13:19 repository.go:1285: syncing data repo [device=3635fde5-930d-4691-8cb5-6be86775988c, kernel=w2ahe72, provider=3, mode=a/false]
I 2024/11/10 12:13:19 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=fccecf49a3d1bef13816562a53d69f7dd32a2815, files=557, size=83.49 MB, created=2024-11-10 12:03:44]
I 2024/11/10 12:13:19 repo.go:591: walk data [files=557] cost [33.1004ms]
I 2024/11/10 12:13:19 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=fccecf49a3d1bef13816562a53d69f7dd32a2815, files=557, size=83.49 MB, created=2024-11-10 12:03:44]
I 2024/11/10 12:13:19 ref.go:64: updated local latest to [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:25 webdav.go:92: uploaded object [Notes/siyuan/repo/lock-sync]
I 2024/11/10 12:13:25 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:26 webdav.go:104: downloaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:13:26 webdav.go:104: downloaded object [Notes/siyuan/repo/indexes/fccecf49a3d1bef13816562a53d69f7dd32a2815]
I 2024/11/10 12:13:26 sync.go:1581: got cloud latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=fccecf49a3d1bef13816562a53d69f7dd32a2815, files=557, size=83.49 MB, created=2024-11-10 12:03:44]
I 2024/11/10 12:13:26 sync.go:1325: upsert file [76868cb7aea02e995ff003c126583df0c7197c57, /20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, 2024-11-10 12:12:58] chunk [c838cdbdc083575b539468a2dd33e6c2ccc44309]
I 2024/11/10 12:13:26 sync.go:1341: upsert chunk [c838cdbdc083575b539468a2dd33e6c2ccc44309]
I 2024/11/10 12:13:27 webdav.go:92: uploaded object [Notes/siyuan/repo/objects/c8/38cdbdc083575b539468a2dd33e6c2ccc44309]
I 2024/11/10 12:13:27 sync.go:1261: uploaded chunk [objects/c8/38cdbdc083575b539468a2dd33e6c2ccc44309, 1/1]
I 2024/11/10 12:13:28 webdav.go:92: uploaded object [Notes/siyuan/repo/objects/76/868cb7aea02e995ff003c126583df0c7197c57]
I 2024/11/10 12:13:28 sync.go:1207: uploaded file [objects/76/868cb7aea02e995ff003c126583df0c7197c57, 1/1]
I 2024/11/10 12:13:28 sync.go:221: got local latest [3ae0b591fd50bbbc38d667f67aa32a9da4e720bc] files [557]
I 2024/11/10 12:13:28 sync.go:1454: got latest sync [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=fccecf49a3d1bef13816562a53d69f7dd32a2815, files=557, size=83.49 MB, created=2024-11-10 12:03:44]
I 2024/11/10 12:13:28 sync.go:228: got latest sync [fccecf49a3d1bef13816562a53d69f7dd32a2815] files [557]
I 2024/11/10 12:13:28 diff.go:49: upsert [lID=b6d81901a3deaaaf454722b58e57165a116e1054, lPath=/20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, lUpdated=2024-11-10 12:03:11, rID=76868cb7aea02e995ff003c126583df0c7197c57, rPath=/20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, rUpdated=2024-11-10 12:12:58]
I 2024/11/10 12:13:28 sync.go:239: cloud upsert [b6d81901a3deaaaf454722b58e57165a116e1054, /20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, 2024-11-10 12:03:11]
I 2024/11/10 12:13:28 sync.go:245: local upsert [76868cb7aea02e995ff003c126583df0c7197c57, /20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, 2024-11-10 12:12:58]
I 2024/11/10 12:13:28 webdav.go:104: downloaded object [Notes/siyuan/repo/indexes-v2.json]
I 2024/11/10 12:13:28 webdav.go:104: downloaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:13:29 webdav.go:92: uploaded object [Notes/siyuan/repo/indexes-v2.json]
I 2024/11/10 12:13:29 webdav.go:92: uploaded object [Notes/siyuan/repo/indexes/3ae0b591fd50bbbc38d667f67aa32a9da4e720bc]
I 2024/11/10 12:13:29 sync.go:1172: uploaded index [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:31 webdav.go:92: uploaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:13:31 webdav.go:104: downloaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:13:31 sync.go:1382: updated latest sync [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:32 webdav.go:116: removed object [Notes/siyuan/repo/lock-sync]
I 2024/11/10 12:13:32 repository.go:1353: synced data repo [device=3635fde5-930d-4691-8cb5-6be86775988c, kernel=w2ahe72, provider=3, mode=a/false, ufc=4, dfc=3, ucc=1, dcc=0, ub=33.05 kB, db=28.54 kB] in [12.55s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/11/10 12:13:32 database.go:1310: closed database
I 2024/11/10 12:13:32 conf.go:1021: cleared workspace temp
I 2024/11/10 12:13:32 sync.go:727: sync websocket closed
I 2024/11/10 12:13:40 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/11/10 12:13:40 runtime.go:79: kernel is booting:
    * ver [103.1.10]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [11044]
    * runtime mode [prod]
    * working directory [C:\Users\MYUSERNAME\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\MYUSERNAME\SiYuan]
I 2024/11/10 12:13:40 conf.go:130: loaded conf [C:\Users\MYUSERNAME\SiYuan\conf\conf.json]
I 2024/11/10 12:13:40 conf.go:501: user has disabled [Google Analytics]
I 2024/11/10 12:13:40 runtime.go:128: use network proxy [system]
I 2024/11/10 12:13:40 serve.go:139: kernel [pid=11044] http server [127.0.0.1:63767] is booting
I 2024/11/10 12:13:41 pandoc.go:146: built-in pandoc [ver=3.5, bin=C:\Users\MYUSERNAME\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/11/10 12:13:41 conf.go:1100: pandoc initialized, set pandoc bin to [C:\Users\MYUSERNAME\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2024/11/10 12:13:41 sync.go:147: sync before boot
I 2024/11/10 12:13:41 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:41 repo.go:591: walk data [files=557] cost [30.407ms]
I 2024/11/10 12:13:41 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:41 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:41 fixedport.go:35: fixed port service [127.0.0.1:6806] is running
I 2024/11/10 12:13:42 webdav.go:104: downloaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:13:42 webdav.go:104: downloaded object [Notes/siyuan/repo/indexes/3ae0b591fd50bbbc38d667f67aa32a9da4e720bc]
I 2024/11/10 12:13:42 sync.go:1581: got cloud latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:13:42 repository.go:1223: boot get sync cloud files elapsed [0.89s]
I 2024/11/10 12:13:42 conf.go:841: database size [26.69 MB], tree/block count [38/5217]
I 2024/11/10 12:13:42 working.go:193: kernel booted
I 2024/11/10 12:13:42 box.go:76: auto stat [trees=38, blocks=5217, dataSize=83.77 MB, assetsSize=62.82 MB]
I 2024/11/10 12:13:42 disk.go:33: disk usage [total=135.32 GB, used=89.94 GB, free=45.38 GB]
I 2024/11/10 12:13:51 session.go:116: auth success [ip=127.0.0.1:63769]
I 2024/11/10 12:14:38 repository.go:1285: syncing data repo [device=3635fde5-930d-4691-8cb5-6be86775988c, kernel=ie8f4mx, provider=3, mode=a/false]
I 2024/11/10 12:14:38 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:14:38 repo.go:591: walk data [files=557] cost [32.6058ms]
I 2024/11/10 12:14:38 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:14:38 ref.go:64: updated local latest to [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3136649379ad1c0089835d8847c12027d64d9e3b, files=557, size=83.49 MB, created=2024-11-10 12:14:38]
I 2024/11/10 12:14:43 webdav.go:92: uploaded object [Notes/siyuan/repo/lock-sync]
I 2024/11/10 12:14:43 ref.go:50: got local latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3136649379ad1c0089835d8847c12027d64d9e3b, files=557, size=83.49 MB, created=2024-11-10 12:14:38]
I 2024/11/10 12:14:43 webdav.go:104: downloaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:14:43 webdav.go:104: downloaded object [Notes/siyuan/repo/indexes/3ae0b591fd50bbbc38d667f67aa32a9da4e720bc]
I 2024/11/10 12:14:43 sync.go:1581: got cloud latest [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:14:43 sync.go:1325: upsert file [5b3b98479ed373ff8559b1f0a2c2c151e7fca797, /20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, 2024-11-10 12:14:06] chunk [9b4756ecb81ac4b831cee5ba4fd5a0820e24469f]
I 2024/11/10 12:14:43 sync.go:1341: upsert chunk [9b4756ecb81ac4b831cee5ba4fd5a0820e24469f]
I 2024/11/10 12:14:44 webdav.go:92: uploaded object [Notes/siyuan/repo/objects/9b/4756ecb81ac4b831cee5ba4fd5a0820e24469f]
I 2024/11/10 12:14:44 sync.go:1261: uploaded chunk [objects/9b/4756ecb81ac4b831cee5ba4fd5a0820e24469f, 1/1]
I 2024/11/10 12:14:45 webdav.go:92: uploaded object [Notes/siyuan/repo/objects/5b/3b98479ed373ff8559b1f0a2c2c151e7fca797]
I 2024/11/10 12:14:45 sync.go:1207: uploaded file [objects/5b/3b98479ed373ff8559b1f0a2c2c151e7fca797, 1/1]
I 2024/11/10 12:14:45 sync.go:221: got local latest [3136649379ad1c0089835d8847c12027d64d9e3b] files [557]
I 2024/11/10 12:14:45 sync.go:1454: got latest sync [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3ae0b591fd50bbbc38d667f67aa32a9da4e720bc, files=557, size=83.49 MB, created=2024-11-10 12:13:19]
I 2024/11/10 12:14:45 sync.go:228: got latest sync [3ae0b591fd50bbbc38d667f67aa32a9da4e720bc] files [557]
I 2024/11/10 12:14:45 diff.go:49: upsert [lID=76868cb7aea02e995ff003c126583df0c7197c57, lPath=/20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, lUpdated=2024-11-10 12:12:58, rID=5b3b98479ed373ff8559b1f0a2c2c151e7fca797, rPath=/20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, rUpdated=2024-11-10 12:14:06]
I 2024/11/10 12:14:45 sync.go:239: cloud upsert [76868cb7aea02e995ff003c126583df0c7197c57, /20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, 2024-11-10 12:12:58]
I 2024/11/10 12:14:45 sync.go:245: local upsert [5b3b98479ed373ff8559b1f0a2c2c151e7fca797, /20241108170119-b6b4fre/20241108170322-zfpujks/20241108170322-qy7gfih/20241108170322-h4bm9jg/20241110112902-7y096rj.sy, 2024-11-10 12:14:06]
I 2024/11/10 12:14:46 webdav.go:104: downloaded object [Notes/siyuan/repo/indexes-v2.json]
I 2024/11/10 12:14:46 webdav.go:104: downloaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:14:47 webdav.go:92: uploaded object [Notes/siyuan/repo/indexes-v2.json]
I 2024/11/10 12:14:47 webdav.go:92: uploaded object [Notes/siyuan/repo/indexes/3136649379ad1c0089835d8847c12027d64d9e3b]
I 2024/11/10 12:14:47 sync.go:1172: uploaded index [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3136649379ad1c0089835d8847c12027d64d9e3b, files=557, size=83.49 MB, created=2024-11-10 12:14:38]
I 2024/11/10 12:14:49 webdav.go:92: uploaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:14:49 webdav.go:104: downloaded object [Notes/siyuan/repo/refs/latest]
I 2024/11/10 12:14:49 sync.go:1382: updated latest sync [device=3635fde5-930d-4691-8cb5-6be86775988c/windows, id=3136649379ad1c0089835d8847c12027d64d9e3b, files=557, size=83.49 MB, created=2024-11-10 12:14:38]
I 2024/11/10 12:14:49 webdav.go:116: removed object [Notes/siyuan/repo/lock-sync]
I 2024/11/10 12:14:49 repository.go:1353: synced data repo [device=3635fde5-930d-4691-8cb5-6be86775988c, kernel=ie8f4mx, provider=3, mode=a/false, ufc=4, dfc=3, ucc=1, dcc=0, ub=33.07 kB, db=28.57 kB] in [11.37s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/11/10 12:14:49 index_fix.go:50: start checking index...
I 2024/11/10 12:14:49 index_fix.go:71: finish checking index

### More information

目前不支持这种图形吗？

**Comment by wish5115** [comment]
这不是bug，选项写法有问题，data应该放到option的data里，请不要太相信ai

正确写法如下：

```json
{
    "series": {
        "type": "sunburst",
        "data": [
            {
                "name": "Grandpa",
                "children": [
                    {
                        "name": "Uncle Leo",
                        "value": 15,
                        "children": [
                            {
                                "name": "Cousin Jack",
                                "value": 2
                            },
                            {
                                "name": "Cousin Mary",
                                "value": 5,
                                "children": [
                                    {
                                        "name": "Jackson",
                                        "value": 2
                                    }
                                ]
                            },
                            {
                                "name": "Cousin Ben",
                                "value": 4
                            }
                        ]
                    },
                    {
                        "name": "Father",
                        "value": 10,
                        "children": [
                            {
                                "name": "Me",
                                "value": 5
                            },
                            {
                                "name": "Brother Peter",
                                "value": 1
                            }
                        ]
                    }
                ]
            },
            {
                "name": "Nancy",
                "children": [
                    {
                        "name": "Uncle Nike",
                        "children": [
                            {
                                "name": "Cousin Betty",
                                "value": 1
                            },
                            {
                                "name": "Cousin Jenny",
                                "value": 2
                            }
                        ]
                    }
                ]
            }
        ],
        "radius": [
            60,
            "90%"
        ],
        "itemStyle": {
            "borderRadius": 7,
            "borderWidth": 2
        },
        "label": {
            "show": false
        }
    }
}
```

如果不会用，建议参考帖子：https://ld246.com/article/1721906460386
