### ISSUE TITLE
能否加入网页嵌入视图？

### ISSUE THREAD

**Issue by WuHaoyang000** [siyuan-note/siyuan#13109]
### In what scenarios do you need this feature?

现有的很多内容可以通过共享文档等方式和别的软件互联，实现共同办公。

### Describe the optimal solution

现有插件已经能实现在新的标签页打开一个网页，说明在思源内嵌web浏览器是可行的。然而这个只能在新标签也打开，是否能内嵌在文档内？通过iFrame框架很多地方无法嵌入（比如WPS云文档）

**Comment by 88250** [comment]
可以试下 IFrame 块， /iframe
