### ISSUE TITLE
Add a kernel API `/api/filetree/renameDocByID`

### ISSUE THREAD

**Issue by kuangdongksk** [siyuan-note/siyuan#13105]
可以将重命名文档改成只需要文档的ID吗？

### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/d655c80a-af94-455e-a67a-cba2f45266af)
目前是这样的，如果插件开发者只保留的文档的ID是无法直接更新文档的名称的，还需要再次请求借口获取文档路径，如果同时保存的话，新建文档后并不返回路径，依旧要请求一次接口

### Describe the optimal solution

希望可以只传递文档的ID就可以对文档进行重命名，是不是因为文档的名称是保存在json里边而json没有保存ID的缘故？

**Comment by kuangdongksk** [comment]
D大，可以把移动文档的from和to也改成id形式的吗

**Comment by 88250** [comment]
单独提个 issue 吧，谢谢。
