### ISSUE TITLE
数据库导出 .csv 样式问题

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#13102]
![2c2a4f6a8e46f7f8cb4e5970c6738ffc](https://github.com/user-attachments/assets/376a9656-1d7c-40ee-9297-477a25b1d6c2)

数据库导出模板列应该只有未完成和已完成
资源列应该导出图片

**Comment by 88250** [comment]
* 导出时是按照模板渲染的，不会去掉 HTML 标签
* CSV 是文本格式，所以只能导出路径
