### ISSUE TITLE
The architecture of pandoc bundled in macOS arm64 version is still x86_64 (which is not fixed in #12750)

### ISSUE THREAD

**Issue by ZeroAurora** [siyuan-note/siyuan#13110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

#12750 does the upgrade to pandoc 3.5, and states that it supports macOS on Apple Silicon. However when using the latest version of SiYuan, the bundled binary is still incompatible.
I also looked into the content inside of the .app folder, found pandoc.zip and tried to run the binary inside of it, and the result is still the same. It might be a build problem.

### Expected result

The bundled pandoc executable should be in correct architecture.

### Screenshot or screen recording presentation

<img width="2560" alt="图片" src="https://github.com/user-attachments/assets/87adb617-a472-43c4-b2cb-7b932188c444">

### Version environment

```markdown
- Version: v3.1.11
- Operating System: macOS 15.1
- Browser (if used): N/A
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17691117/siyuan.log)

**Comment by 88250** [comment]
Please try deleting the workspace/temp/pandoc/ folder and then starting SiYuan.

**Comment by ZeroAurora** [comment]
> Please try deleting the workspace/temp/pandoc/ folder and then starting SiYuan.

Tried and not working. I also specified in the issue that:

> I also looked into the content inside of the .app folder, found pandoc.zip and tried to run the binary inside of it, and the result is still the same. It might be a build problem.

**Comment by ZeroAurora** [comment]
https://github.com/siyuan-note/siyuan/blob/487c48427ae8e3b840d209047cc316273c7a3931/app/electron-builder-darwin-arm64.yml#L61

**Comment by 88250** [comment]
Thanks for the feedback, it will be fixed in the next version.

**Comment by 88250** [comment]
这个改进就不归入特定版本了，谢谢。
This improvement will not be included in a specific version, thank you.
