### ISSUE TITLE
无法关闭没有任何内容显示的标签页，同时也无法通过点击文件打开

### ISSUE THREAD

**Issue by zqhjl** [siyuan-note/siyuan#1311]
### 描述问题 Describe the problem
重命名文档时，输入框中会自动出现.md后缀，然后点击确定后会弹出字符不合法的警告框。删除.md后点击确定，重命名会成功，但会使得该文件没有后缀名而无法打开。在windows自带的文件管理器中，加上了.md后缀，还是无法打开。同时，重命名前的标签页无法关闭，并且没有内容显示。重新安装后依然如此。

### 期待的结果 Expected result
解决这一问题。

### 截屏或录屏演示 Screenshot or screen recording presentation
![无法关闭和无法打开](https://user-images.githubusercontent.com/61345763/106011512-7fa97c80-60f5-11eb-8441-067a23d3b6df.gif)

### 版本环境 Version environment

* 版本 Version：0.6.7
* 操作系统 Operating system：windows10
* 浏览器（如果使用）Browser (if used)：chrome

### 日志文件 Log
D 2021/01/27 22:50:20 box.go:382: unindexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:50:20 box.go:318: indexing [4] trees, cpus [4]
D 2021/01/27 22:50:20 box.go:353: indexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:51:18 setuilayout.go:43: set ui layout done
I 2021/01/27 22:51:23 process.go:65: ui process exited, exit kernel process now
I 2021/01/27 22:51:23 conf.go:231: exited kernel
I 2021/01/27 22:51:34 working.go:84: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/27 22:51:34 working.go:85: kernel [v0.6.7] is booting, runtime mode is [prod], working directory is [D:\Program Files\SiYuan\resources], temp directory is [C:\Users\mmc\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/27 22:51:35 lang.go:67: initialized languages
D 2021/01/27 22:51:35 conf.go:79: loaded conf [C:\Users\mmc\.siyuan\conf.json]
I 2021/01/27 22:51:35 conf.go:179: local serve path [http://192.168.0.5:6806]
I 2021/01/27 22:51:35 conf.go:183: initialized conf
I 2021/01/27 22:51:35 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/27 22:51:36 webdav.go:36: initialized WebDAV server
I 2021/01/27 22:51:36 box.go:318: indexing [4] trees, cpus [4]
D 2021/01/27 22:51:36 box.go:353: indexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:51:36 conf.go:329: initialized box
I 2021/01/27 22:51:37 repo.go:40: initialized git repo
I 2021/01/27 22:52:11 process.go:65: ui process exited, exit kernel process now
I 2021/01/27 22:52:11 conf.go:231: exited kernel
I 2021/01/27 22:52:42 working.go:84: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/27 22:52:42 working.go:85: kernel [v0.6.7] is booting, runtime mode is [prod], working directory is [D:\Program Files\SiYuan\resources], temp directory is [C:\Users\mmc\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/27 22:52:43 lang.go:67: initialized languages
D 2021/01/27 22:52:43 conf.go:79: loaded conf [C:\Users\mmc\.siyuan\conf.json]
I 2021/01/27 22:52:43 conf.go:179: local serve path [http://192.168.0.5:6806]
I 2021/01/27 22:52:43 conf.go:183: initialized conf
I 2021/01/27 22:52:43 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/27 22:52:43 webdav.go:36: initialized WebDAV server
I 2021/01/27 22:52:43 box.go:318: indexing [5] trees, cpus [4]
D 2021/01/27 22:52:43 box.go:353: indexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:52:43 conf.go:329: initialized box
I 2021/01/27 22:52:45 repo.go:40: initialized git repo
I 2021/01/27 22:54:30 process.go:65: ui process exited, exit kernel process now
I 2021/01/27 22:54:30 conf.go:231: exited kernel
I 2021/01/27 22:54:38 working.go:84: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/27 22:54:38 working.go:85: kernel [v0.6.7] is booting, runtime mode is [prod], working directory is [D:\Program Files\SiYuan\resources], temp directory is [C:\Users\mmc\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/27 22:54:39 lang.go:67: initialized languages
D 2021/01/27 22:54:39 conf.go:79: loaded conf [C:\Users\mmc\.siyuan\conf.json]
I 2021/01/27 22:54:39 conf.go:179: local serve path [http://192.168.0.5:6806]
I 2021/01/27 22:54:39 conf.go:183: initialized conf
I 2021/01/27 22:54:39 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/27 22:54:39 webdav.go:36: initialized WebDAV server
I 2021/01/27 22:54:39 box.go:318: indexing [5] trees, cpus [4]
D 2021/01/27 22:54:39 box.go:353: indexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:54:39 conf.go:329: initialized box
I 2021/01/27 22:54:40 repo.go:40: initialized git repo
I 2021/01/27 22:55:39 process.go:65: ui process exited, exit kernel process now
I 2021/01/27 22:55:39 conf.go:231: exited kernel
I 2021/01/27 22:56:02 working.go:84: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/27 22:56:02 working.go:85: kernel [v0.6.7] is booting, runtime mode is [prod], working directory is [D:\Program Files\SiYuan\resources], temp directory is [C:\Users\mmc\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/27 22:56:03 lang.go:67: initialized languages
D 2021/01/27 22:56:03 conf.go:79: loaded conf [C:\Users\mmc\.siyuan\conf.json]
I 2021/01/27 22:56:03 conf.go:179: local serve path [http://192.168.0.5:6806]
I 2021/01/27 22:56:03 conf.go:183: initialized conf
I 2021/01/27 22:56:03 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/27 22:56:03 webdav.go:36: initialized WebDAV server
I 2021/01/27 22:56:03 box.go:318: indexing [5] trees, cpus [4]
D 2021/01/27 22:56:03 box.go:353: indexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:56:03 conf.go:329: initialized box
I 2021/01/27 22:56:04 repo.go:40: initialized git repo
D 2021/01/27 22:56:14 box.go:382: unindexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
D 2021/01/27 22:56:14 webdav.go:65: closed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:56:32 box.go:318: indexing [5] trees, cpus [4]
D 2021/01/27 22:56:32 box.go:353: indexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
D 2021/01/27 22:56:32 webdav.go:155: opened local box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 22:56:45 process.go:65: ui process exited, exit kernel process now
I 2021/01/27 22:56:45 conf.go:231: exited kernel
I 2021/01/27 23:01:55 working.go:84: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/27 23:01:55 working.go:85: kernel [v0.6.7] is booting, runtime mode is [prod], working directory is [D:\Program Files\SiYuan\resources], temp directory is [C:\Users\mmc\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/27 23:01:56 lang.go:67: initialized languages
D 2021/01/27 23:01:56 conf.go:79: loaded conf [C:\Users\mmc\.siyuan\conf.json]
I 2021/01/27 23:01:56 conf.go:179: local serve path [http://192.168.0.5:6806]
I 2021/01/27 23:01:56 conf.go:183: initialized conf
I 2021/01/27 23:01:56 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/27 23:01:56 webdav.go:36: initialized WebDAV server
I 2021/01/27 23:01:56 box.go:318: indexing [5] trees, cpus [4]
D 2021/01/27 23:01:56 box.go:353: indexed box [http://127.0.0.1:6806/siyuan/siyuan/学习/]
I 2021/01/27 23:01:56 conf.go:329: initialized box
I 2021/01/27 23:01:58 repo.go:40: initialized git repo

**Comment by zqhjl** [comment]
重置外观后可以正常使用了…不过重命名文档那个问题应该还是需要改进一下的

**Comment by 88250** [comment]
感谢反馈，v0.6.8 已做修复。
