### ISSUE TITLE
文案改进建议

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#13112]
### In what scenarios do you need this feature?

1. 在向他人推荐SiYuan时，经常会遇到用户对定价策略的不理解，中国用户和国际用户都有过这种困惑。
2. 第三方同步这一描述存在歧义，我建议改为：“同步到自定义s3/webdav（由开发团队维护）”或是“同步到第三方s3/webdav（由开发团队维护）”。因为第三方同步会和第三方插件同步、第三方同步软件发生混淆。

## 建议如下

下面写个例子

### 免费计划

- 本地存储
- 可靠的本地数据快照系统
- 从浏览器访问已打开的本地思源知识库
- 官方剪藏插件与API
- 只读发布功能
- Docker部署
- 社区集市：插件、主题、模板、挂件、图标、代码片段
- 所有基础功能
    - 由思源团队开发的所见即所得编辑器
    - 强大且与文档特性一致的块特性
    - 基于块的数据库
    - 文档笔记与禅模式
    - 大纲笔记支持
    - 独特的多daily note支持
    - 双链、嵌入块、引用计数、关系图谱
    - 性能优秀的可编辑反链与搜索
    - BalaBala...

### 功能特性

- [X] 免费计划 所有功能
- 同步到自定义s3/webdav（由开发团队维护）
- 云端数据快照系统
- 端到端加密
- 搜索PDF、docx、图片等资产中的文字

### 订阅计划

- [X] 免费计划 所有功能
- [X] 功能特性 所有功能 （订阅有效期内）
- 同步到官方服务器
    - 云端数据快照系统
    - 单个文件没有大小限制
    - 7个工作空间
    - 总大小8GB
- 端到端加密
- 收集箱

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/ff601c15-13f8-49e2-8cbd-ac70f1440f65)

![image](https://github.com/user-attachments/assets/ea9f7f62-4a28-4a39-b31f-520451a19781)

![image](https://github.com/user-attachments/assets/bae89944-1125-4a47-98da-508bc3429b0c)

![image](https://github.com/user-attachments/assets/89042f0f-c6b4-4243-a61c-54c57b2dc7ab)

**Comment by 88250** [comment]
> 同步到自定义s3/webdav（由开发团队维护）

这个可能歧义更大哦，开发团队并不维护第三方存储。

另外，关于定价页面布局考虑过其他方案的，但是其他方案感觉没有对比，按行对比功能会更直观。

所以暂时不考虑改动了，感谢反馈。

**Comment by zxhd863943427** [comment]
我还是支持换个表达的……我已经很多次给外国友人解释当前的功能特性到底是啥东西了……

**Comment by TCOTC** [comment]
其实我觉得这样分更合适：`免费` `拓展` `订阅`

**Comment by 88250** [comment]
名称的话影响不大，现在大家觉得主要是什么地方有问题？

**Comment by TCOTC** [comment]
用户首先会对比这两个付费方案，结果什么也看不出来：

![image](https://github.com/user-attachments/assets/3299dd77-2dbc-4097-bc1e-cf64958164a1)

下面没区别的项目应该全部去掉。

![image](https://github.com/user-attachments/assets/2c100138-2d4a-46e1-89eb-dec4f950b5ff)

**Comment by 88250** [comment]
去掉的话就没有特性介绍了，或许可以把最下面的排序提前？

**Comment by TCOTC** [comment]
把“会员特权”提到最上面也行

**Comment by KuiyueRO** [comment]
1. 订阅包含的功能特性只在订阅期间生效，购买订阅不等于购买功能特性。这个没有明确提示，很多人会对此有疑问，订阅后是不是就永久可用功能特性了。

2. 第三方同步和同步到第三方/自定义s3之间有明显的不同。主要歧义在于思源所说的第三方是第三方存储桶（存储），而很多人默认会认为是由第三方（社区）提供的同步插件（同步服务）。

我发现当使用第三方同步作为介绍时，很多不够了解的人会认为思源故意限制了社区制作同步插件的权限，只能走官方的同步。这一点在ob社区推荐思源时感知明显。

总之就是很多人理解不了这个第三方s3是什么意思，上次国外友人关于这个问题问了我很多层楼。

另外我那个括号内的内容也不是重点，可以不要，也可以改为（官方同步方案）之类的内容

**Comment by KuiyueRO** [comment]
另外，我觉得最顶部只需要指出特点就好，D大你看notion这个页面，顶部就如同我提供的图一图二一样，plus版第一行就是“免费版的全部功能"，只有划到底部才会显示对比详细的对比表格。突然粘贴不了图片了🤣

https://www.notion.so/zh-cn/pricing

**Comment by frostime** [comment]
我也支持更换一下描述，现在的描述还是有点模糊。

**Comment by TCOTC** [comment]
> 购买订阅不等于购买功能特性。这个没有明确提示

有的。

@88250 把付费须知直接放到页面上吧，因为可能还是会有用户不看：

![image](https://github.com/user-attachments/assets/e7ad8252-f5ca-4669-a0a6-e6e450044bca)

**Comment by TCOTC** [comment]
> 很多人理解不了这个第三方s3是什么意思

@88250 把这些描述也加到定价页吧

![image](https://github.com/user-attachments/assets/8427b823-0084-42ee-904f-e6e8bf357d8e)

![image](https://github.com/user-attachments/assets/8e519b16-971e-4cf3-a0b6-8e8ebfedb774)

**Comment by KuiyueRO** [comment]
对于刚了解得用户来说信息量可能有点多了😊😊，得从一堆信息中提炼区别点。例如虽然写了块引用和块嵌入，但不止一次有刚上手的用户问有没有块引用、块嵌入。

**Comment by frostime** [comment]
我没啥想法，就让 GPT 给出了一些建议。

```md
[https://b3log.org/siyuan/pricing.html](https://b3log.org/siyuan/pricing.html)

这是思源笔记的定价页面目前这个订阅界面饱受争议，经常会遇到用户对定价策略的不理解，中国用户和国际用户都有过这种困惑。以下是我整理出来的一些争论。

1. **功能特性标题描述**：「功能特性」这个词词义暧昧，没有什么信息量却又容易引起误解；特别是下面还有一个「一次付费，终身使用」就更容易让人误解了
2. **没有解释清楚生效期限**：订阅包含的功能特性只在订阅期间生效，购买订阅不等于购买功能特性。这个没有明确提示，很多人会对此有疑问，订阅后是不是就永久可用功能特性了。
3. **对「第三方同步」的描述不清**：思源中「功能特性」方案里面的「第三方同步」指的含义是：「思源提供一个云同步的功能结构，但是需要用户自己搭建 S3，Web Dav 服务来对接」；但是经常有人理解为「官方会提供 S3/Webdav 服务给用户进行同步」。
4. **使用了技术术语**：「S3」「Webdav」这些都是技术性名词，用户不一定理解实际的含义，从而造成理解的困难

请你：

* 仔细阅读、研究思源目前定价页面的内容
* 结合我提出的几个问题，自行分析当前定价页面存在哪些问题
* 给出你的改进意见

  * 改进意见尽可能多、丰富、完善，且具有可执行性
  * 首先指出问题，然后给出具体的优化方案
  * 要切实回应我上面提出的问题
 ```

![image](https://github.com/user-attachments/assets/ca314c3c-b59d-4e20-84a4-8eac776a0268)

**Comment by frostime** [comment]
我是觉得没有必要在中间堆叠这么一大堆东西的。

![image](https://github.com/user-attachments/assets/0d399b77-3213-4072-9a98-5645a8ca23b0)


这个页面里面最重要的信息最底下，上面这些东西看上去非常庞杂，实际上从阅读的角度看全是干扰的噪声，没有什么有价值的信息量。

![image](https://github.com/user-attachments/assets/253160f7-7919-4ad9-86fb-b75b53327e20)


如果不想去掉，也可以默认折叠起来，只留一个标题的位置，节省空间，也能让用户一下子翻到最下面看有价值的信息。 

![image](https://github.com/user-attachments/assets/71b632e4-56cd-4205-b87f-2f9f05558f78)

**Comment by TCOTC** [comment]
GPT看起来在胡言乱语

**Comment by 88250** [comment]
去掉那些特性列出了，突出重点：

![image](https://github.com/user-attachments/assets/dde67074-cfc4-4f72-946b-bf51d6b3d295)

**Comment by TCOTC** [comment]
要不做成卡片式的，不要勾和叉

![image](https://github.com/user-attachments/assets/0a1ed2d9-6e74-430d-8e5f-3ce5f78e3a0b)

**Comment by 88250** [comment]
不大改了

**Comment by TCOTC** [comment]
一个方一个圆看起来不太协调

![image](https://github.com/user-attachments/assets/3caa2ad0-9307-4591-ae81-c7a9c5fce1ba)

**Comment by 88250** [comment]
嗯，等会调整一下

**Comment by SaXz2** [comment]
定价的视觉中心太高了，应该再往下一点

**Comment by TCOTC** [comment]
确实，上面再加一个 .feature__hr 会好一点：

![image](https://github.com/user-attachments/assets/230d402e-22f6-4dc0-8039-02bbfbdff476)

**Comment by 88250** [comment]
好的

**Comment by TCOTC** [comment]
- [ ] 为资源文件图床功能增加描述

![image](https://github.com/user-attachments/assets/4a7615cb-7c0f-42f5-9e27-620cb86da583)

**Comment by 88250** [comment]
已经调整，感谢反馈。
