### ISSUE TITLE
希望可以快捷打开多个工作空间

### ISSUE THREAD

**Issue by gudaoxuri** [siyuan-note/siyuan#13114]
### In what scenarios do you need this feature?

我有多个工作空间，每次都要先打开主（默认）工作空间，然后再打开另外的工作空间。

### Describe the optimal solution

如下图，类似vscode，可以pinned 一些常用工作空间，实现快速打开指定工作空间的功能。

![image](https://github.com/user-attachments/assets/aa6d2a1c-1342-41f9-b086-45d75f66f3f4)

**Comment by SaXz2** [comment]
可以用指令  `--workspace=path`
添加到快捷方式后面即可

**Comment by 88250** [comment]
楼上的方式是正解，具体操作步骤请参考 用户指南 - 工作空间 章节，谢谢。
