### ISSUE TITLE
表情选择器中的表情宽度问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13115]
### 01 需要最小宽度

出现豆腐块时会影响相邻的其他表情的位置：

![image](https://github.com/user-attachments/assets/8e276240-2834-40e1-bd44-dcce4d3b7ad1)

![image](https://github.com/user-attachments/assets/75809b72-67f4-46d9-9803-b00e0ebfbc95)

### 02 内置表情和自定义表情的宽度需要一致

https://ld246.com/article/1680525879267

自定义表情是方的，内置表情是扁的：

![image](https://github.com/user-attachments/assets/51d20412-e2fa-47d5-af95-1e45b7b9929d)

**Comment by Vanessa219** [comment]
mac 下是正常的，我先设置一个最小宽度吧，大小不同的操作系统是？

![image](https://github.com/user-attachments/assets/1dc730de-2257-43b6-a13a-cb7d69d08b6d)

**Comment by TCOTC** [comment]
我是 Win11

**Comment by Vanessa219** [comment]
自定义表情和 emoji 无法统一宽度。

![8f3e4bffea57621190acc2a00edf7ced](https://github.com/user-attachments/assets/54d34241-c914-4d57-8447-8273a2bb2961)

**Comment by Vanessa219** [comment]
不行

**Comment by TCOTC** [comment]
那最小宽度能搞吗？

**Comment by Vanessa219** [comment]
已经根据 mac 系统设置了，太宽 mac 下无法看‘
