### ISSUE TITLE
闪卡未作答时不显示书签、命名、别名、备注丨Hide bookmark, name, alias, memo in flashcard when not showing answer 

### ISSUE THREAD

**Issue by mamaruo** [siyuan-note/siyuan#13116]
### In what scenarios do you need this feature?

闪卡未作答时，书签、命名、别名、备注可能会透露答案信息。
Bookmark, name, alias, memo may reveal answer information when flashcards are not answered.

### Describe the optimal solution

闪卡未作答时不显示书签、命名、别名、备注。
Hide bookmark, name, alias, memo in flashcard when not showing answer.

**Comment by 88250** [comment]
这个不考虑改动了，感谢提议。
