### ISSUE TITLE
改进标题剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13124]
关联帖子：https://ld246.com/article/1731386387139

剪藏网址：https://www.vulture.com/article/diddy-parties-details.html

![image](https://github.com/user-attachments/assets/10dfb901-e270-4013-9244-b57b21b4521c)

标题没有剪藏下来：

![image](https://github.com/user-attachments/assets/ec34c147-2c61-4bf0-8bc0-da50b83d69cf)

**Comment by 88250** [comment]
标题已改进；链滴帖子中提到的超链接问题我这里重现不了。
