### ISSUE TITLE
section 标签剪藏问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13125]
关联帖子 https://ld246.com/article/1731377195203

剪藏网址 https://mp.weixin.qq.com/s/0S7job6WcgTy8WXt4cCv5Q

文本和图片应该分成两个块：

![image](https://github.com/user-attachments/assets/3d55bbe7-8aeb-40bb-af5b-f607c718fa40)

**Comment by TCOTC** [comment]
@88250 会剪藏到这些：

![image](https://github.com/user-attachments/assets/b2380538-f2dd-4870-81c7-475aa65ee376)

![image](https://github.com/user-attachments/assets/25ca08ec-215b-49df-8c79-de79d9aa1486)

**Comment by 88250** [comment]
稍后改进
