### ISSUE TITLE
文档树“复制”支持使用快捷键

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13128]
![image](https://github.com/user-attachments/assets/81ca7a2e-38f8-4f7b-895e-85d8aa60ae94)

需求：

![image](https://github.com/user-attachments/assets/2ff4fac6-dd06-4a4c-acc0-6465f6912e1a)

**Comment by HibernalGlow** [comment]
不知道为啥普通的复制引用 快捷键失灵了 复制为嵌入是好的 文档树也能用
![PixPin_2024-12-03_23-08-24](https://github.com/user-attachments/assets/a172a4a9-9444-4f35-bb7f-7984f9ad3a3f)

**Comment by TCOTC** [comment]
确实，先记录 #13361

**Comment by TCOTC** [comment]
应该没人发现
