### ISSUE TITLE
在文档树上选中一个文档后支持按 Ctrl+A 选中所有同级文档（同一个父文档下）

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13123]
让多选文档更方便一点

**Comment by 88250** [comment]
考虑到文档树列出有限制，这个操作可能会引入和编辑动态加载类似无法全选的问题，所以不考虑了。

**Comment by TCOTC** [comment]
> 文档树列出有限制

在没有动态加载的情况下，Ctrl+A 全选和一个个文档选中都不能在实际上全选，但支持 Ctrl+A 能让选择文档更方便

**Comment by 88250** [comment]
看看能不能用插件支持吧

**Comment by 88250** [comment]
我个人是偏向于 Shift 多选的，但是目前交互有冲突，无法推进。
