### ISSUE TITLE
文件导出插件显示的建议

### ISSUE THREAD

**Issue by gudaoxuri** [siyuan-note/siyuan#13122]
### In what scenarios do you need this feature?

目前导入pdf、图片等类型时很多插件都不能正常显示（只显示成一条文字链接）。比如drawio、univer等。希望可以能正常显示。

### Describe the optimal solution

建议导出对不能显示的插件使用截图方式转成图片显示。

**Comment by 88250** [comment]
你好，插件的导出无法支持，如果有所顾虑建议不使用插件。
