### ISSUE TITLE
关于文件（标签页）关闭不了显示空白的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1312]
### 描述问题 Describe the problem

文件关闭不了并且显示空白。暂时不知道进行了什么操作，只记得长时间没有切换到这个标签页。

### 截屏或录屏演示 Screenshot or screen recording presentation

![ew1](https://user-images.githubusercontent.com/47321059/106020470-c5b70e00-60fe-11eb-94fa-7776fd0cbbdc.gif)

### 版本环境 Version environment

* 版本 Version：0.6.7
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
感谢反馈，v0.6.8 修复。
