### ISSUE TITLE
3.1.10反链面板改版后严重影响使用

### ISSUE THREAD

**Issue by sw6633** [siyuan-note/siyuan#13129]
### In what scenarios do you need this feature?

诉求：
反链面板要像以前一样能显示块的反链情况，而不是只能显示页面反链

### Describe the optimal solution

原来反链面板能显示页面+块的反链情况
我打开一个笔记，能清楚在反链面板看到块的引用情况，从而进行相关回顾，好用得很，是笔记寻回的所有方式里最高效的一种
而现在只能显示页面级的反链，块的反链要到页面所在的具体位置才能看到引用次数（还只是次数），反链面板几乎等于没用了

**Comment by TCOTC** [comment]
请到设置中打开开关：

![image](https://github.com/user-attachments/assets/37a721e2-7d70-43d3-a52c-c11e3bee5533)
