### ISSUE TITLE
3.1.11版本webdav无法同步

### ISSUE THREAD

**Issue by zbigbird** [siyuan-note/siyuan#13139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在Unraid上，按照应用商店默认模板安装了思源笔记，配置了webdav服务，webdav服务用joplin等访问正常，但是思源在配置同步时提示“同步失败：锁定云端同步目录失败，请稍后再试 (Provider: WebDAV) v3.1.11”

### Expected result

同步失败：锁定云端同步目录失败，请稍后再试 (Provider: WebDAV) v3.1.11

### Version environment

```markdown
- Version: 3.1.11
- Operating System: unraid
- Browser (if used):chrome
```

### Log file

Creating group siyuan (1000)
Creating user siyuan (PUID: 1000, PGID: 1000)
Adjusting ownership of /opt/siyuan, /home/siyuan/, and /siyuan/workspace/
Starting Siyuan with UID:1000 and GID:1000 in workspace /siyuan/workspace/
I 2024/11/13 14:36:59 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/11/13 14:36:59 runtime.go:79: kernel is booting:
    * ver [3.1.11]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/11/13 14:36:59 conf.go:130: loaded conf [/siyuan/workspace/conf/conf.json]
I 2024/11/13 14:36:59 runtime.go:128: use network proxy [system]
I 2024/11/13 14:36:59 serve.go:139: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/11/13 14:37:00 sync.go:147: sync before boot
I 2024/11/13 14:37:00 ref.go:50: got local latest [device=y1gkspxzv1y2/linux, id=03fdd3d2ae689236946a9c8352272415afed30c6, files=6, size=7.69 kB, created=2024-11-13 14:24:06]
I 2024/11/13 14:37:00 repo.go:591: walk data [files=6] cost [5.212072ms]
I 2024/11/13 14:37:00 ref.go:50: got local latest [device=y1gkspxzv1y2/linux, id=03fdd3d2ae689236946a9c8352272415afed30c6, files=6, size=7.69 kB, created=2024-11-13 14:24:06]
I 2024/11/13 14:37:00 ref.go:50: got local latest [device=y1gkspxzv1y2/linux, id=03fdd3d2ae689236946a9c8352272415afed30c6, files=6, size=7.69 kB, created=2024-11-13 14:24:06]
W 2024/11/13 14:37:01 sync.go:1581: not found cloud latest
I 2024/11/13 14:37:01 repository.go:1228: boot get sync cloud files elapsed [0.54s]
I 2024/11/13 14:37:01 conf.go:841: database size [7.64 MB], tree/block count [0/0]
I 2024/11/13 14:37:01 working.go:193: kernel booted
I 2024/11/13 14:37:01 box.go:77: auto stat [trees=0, blocks=0, dataSize=53.12 kB, assetsSize=0 B]
I 2024/11/13 14:37:14 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.125 Safari/537.36 UOS Professional]
I 2024/11/13 14:37:21 serve.go:244: serving [/] for user-agent [Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.125 Safari/537.36 UOS Professional]
I 2024/11/13 14:37:36 repository.go:1290: syncing data repo [device=y1gkspxzv1y2, kernel=jijo1l4, provider=3, mode=a/true]
I 2024/11/13 14:37:36 ref.go:50: got local latest [device=y1gkspxzv1y2/linux, id=03fdd3d2ae689236946a9c8352272415afed30c6, files=6, size=7.69 kB, created=2024-11-13 14:24:06]
I 2024/11/13 14:37:36 repo.go:591: walk data [files=6] cost [5.541014ms]
I 2024/11/13 14:37:36 ref.go:50: got local latest [device=y1gkspxzv1y2/linux, id=03fdd3d2ae689236946a9c8352272415afed30c6, files=6, size=7.69 kB, created=2024-11-13 14:24:06]
E 2024/11/13 14:37:37 webdav.go:469: mkdir [siyuan/siyuan/repo] failed: MkdirAll /siyuan/siyuan/repo/: 415
E 2024/11/13 14:37:37 sync_lock.go:161: upload lock sync failed: MkdirAll /siyuan/siyuan/repo/: 415
E 2024/11/13 14:37:37 repository.go:1318: sync data repo failed: lock cloud repo failed
I 2024/11/13 14:37:40 repository.go:1290: syncing data repo [device=y1gkspxzv1y2, kernel=jijo1l4, provider=3, mode=a/true]
I 2024/11/13 14:37:40 ref.go:50: got local latest [device=y1gkspxzv1y2/linux, id=03fdd3d2ae689236946a9c8352272415afed30c6, files=6, size=7.69 kB, created=2024-11-13 14:24:06]
I 2024/11/13 14:37:40 repo.go:591: walk data [files=6] cost [5.067875ms]
I 2024/11/13 14:37:40 ref.go:50: got local latest [device=y1gkspxzv1y2/linux, id=03fdd3d2ae689236946a9c8352272415afed30c6, files=6, size=7.69 kB, created=2024-11-13 14:24:06]

**Comment by 88250** [comment]
建议确认一下权限：

E 2024/11/13 14:37:37 webdav.go:469: mkdir [siyuan/siyuan/repo] failed: MkdirAll /siyuan/siyuan/repo/: 415

**Comment by zbigbird** [comment]
在unraid下，查看权限是正确的：
root@officenas:/mnt/user/appdata/siyuan# ls -l
total 4
drwxr-xr-x 1 1000 1000   53 Nov 14 16:13 conf/
drwxr-xr-x 1 1000 1000  161 Nov 13 15:45 data/
drwxr-xr-x 1 1000 1000   10 Nov 13 15:17 note/
drwxr-xr-x 1 1000 1000   85 Nov 14 16:13 repo/
drwxr-xr-x 1 1000 1000 4096 Nov 14 16:04 temp/
root@officenas:/mnt/user/appdata/siyuan# cd /mnt/user/appdata/
root@officenas:/mnt/user/appdata# ls -l
total 12
drwxr-xr-x 1 root   root    10 Nov 11 09:15 Nginx-Proxy-Manager-Official/
drwxr-xr-x 1 root   root    47 May 20 14:47 calibre/
drwxr-xr-x 1 nobody users   10 Nov 14 15:17 cloudflared/
drwxr-xr-x 1 root   root    28 May 23 15:44 filebrowser/
drwxrwxrwx 1 nobody users   92 Nov 12 17:42 filestash/
drwxr-xr-x 1 root   root    62 Aug 29 16:47 homarr/
drwxr-xr-x 1 nobody users 4096 Nov  7 15:52 lucky/
drwxr-xr-x 1 nobody users   68 May 20 08:52 mariadb/
drwx------ 1    999 users 4096 Nov  8 11:25 maxkb/
drwxr-xr-x 1 nobody users   29 Nov 13 00:04 nocodb/
drwxr-xr-x 1 root   root  4096 Nov 14 16:11 resilio-sync/
drwxr-xr-x 1 root   root    92 Jun 11 16:58 s-pdf/
drwxr-xr-x 1 root   root    10 Nov 11 09:15 sftpgo/
drwxrwxrwx 1   1000  1000  107 Nov 13 15:31 siyuan/
drwxr-xr-x 1   1000  1000  138 Sep  3 16:11 trilium/
drwxr-xr-x 1 nobody users  157 Nov  1 21:39 vocechat/
drwxr-xr-x 1 nobody users   45 Nov 11 14:20 webdav/
drwxr-xr-x 1 nobody users   33 Nov 14 05:37 wewe-rss/
root@officenas:/mnt/user/appdata#
