### ISSUE TITLE
软换行可以显示回车符

### ISSUE THREAD

**Issue by HibernalGlow** [siyuan-note/siyuan#13138]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/bf7ba9cb-6271-4e8e-ab3c-5c0218e58dab)
目前区分换行2段是通过末尾空格 如果页签间距窄或者文本长度刚好相当 就难以区分

### Describe the optimal solution

类似word的回车符 可以css控制显示 默认不显示 有需求自己设置

**Comment by TCOTC** [comment]
这个应该实现不了

**Comment by 88250** [comment]
实现不了

**Comment by HibernalGlow** [comment]
有啥替代解决方案不 软回车能被搜索替换也行

**Comment by 88250** [comment]
可以试试正则搜索

**Comment by HibernalGlow** [comment]
\n好像搜不到
