### ISSUE TITLE
WebDAV同步问题

### ISSUE THREAD

**Issue by hopana** [siyuan-note/siyuan#13136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem
WebDAV同步报错：同步失败：Remove SiYuan/siyuan/repo/lock-sync: 400 (Provider: WebDAV) v3.1.11

1、试用订阅
2、设置-云端-配置WebDAV
3、同步（同步成功）
4、删除服务器同步目录
5、无法同步、无法更换目录、无法再次配置

删除服务器同步目录的动机：由于创建的目录为SiYuan，而思源笔记又默认在后面加了一个siyuan，导致路径为 /SiYuan/siyuan/xxxx，所以想更换目录

### Expected result

1、支持更换WebDAV同步目录
2、支持目录不存在时重新配置WebDAV同步目录
3、支持迁移等

### Version environment

```markdown
- Version: v3.1.11
- Operating System: Win10 23H2
- Browser (if used):No
```

### Log file

I 2024/11/13 09:57:42 sync.go:147: sync before boot
I 2024/11/13 09:57:42 ref.go:50: got local latest [device=4b4331cb-762e-46c8-a396-8f9b683a6aaf/windows, id=d5cc7d118f4ad3d0b7e1b6a2be0490eca9482445, files=40, size=2.92 MB, created=2024-11-13 09:56:50]
I 2024/11/13 09:57:42 repo.go:591: walk data [files=40] cost [1.6395ms]
I 2024/11/13 09:57:42 ref.go:50: got local latest [device=4b4331cb-762e-46c8-a396-8f9b683a6aaf/windows, id=d5cc7d118f4ad3d0b7e1b6a2be0490eca9482445, files=40, size=2.92 MB, created=2024-11-13 09:56:50]
I 2024/11/13 09:57:42 ref.go:50: got local latest [device=4b4331cb-762e-46c8-a396-8f9b683a6aaf/windows, id=d5cc7d118f4ad3d0b7e1b6a2be0490eca9482445, files=40, size=2.92 MB, created=2024-11-13 09:56:50]
E 2024/11/13 09:57:42 sync.go:1586: download cloud latest failed: ReadStream SiYuan/siyuan/repo/refs/latest: Authorize SiYuan/siyuan/repo/refs/latest: 401
E 2024/11/13 09:57:42 sync.go:738: download cloud latest failed: ReadStream SiYuan/siyuan/repo/refs/latest: Authorize SiYuan/siyuan/repo/refs/latest: 401
I 2024/11/13 09:57:42 repository.go:1228: boot get sync cloud files elapsed [0.06s]
E 2024/11/13 09:57:42 repository.go:1233: sync data repo failed: ReadStream SiYuan/siyuan/repo/refs/latest: Authorize SiYuan/siyuan/repo/refs/latest: 401
E 2024/11/13 09:57:42 sync.go:592: sync failed caused by network: ReadStream SiYuan/siyuan/repo/refs/latest: Authorize SiYuan/siyuan/repo/refs/latest: 401
E 2024/11/13 09:58:08 sync.go:592: sync failed caused by network: Authorize /: 401
I 2024/11/13 09:58:11 repository.go:1290: syncing data repo [device=4b4331cb-762e-46c8-a396-8f9b683a6aaf, kernel=e9d4ol9, provider=3, mode=a/true]
I 2024/11/13 09:58:11 ref.go:50: got local latest [device=4b4331cb-762e-46c8-a396-8f9b683a6aaf/windows, id=d5cc7d118f4ad3d0b7e1b6a2be0490eca9482445, files=40, size=2.92 MB, created=2024-11-13 09:56:50]
I 2024/11/13 09:58:11 repo.go:591: walk data [files=40] cost [1.6692ms]
I 2024/11/13 09:58:11 ref.go:50: got local latest [device=4b4331cb-762e-46c8-a396-8f9b683a6aaf/windows, id=d5cc7d118f4ad3d0b7e1b6a2be0490eca9482445, files=40, size=2.92 MB, created=2024-11-13 09:56:50]
E 2024/11/13 09:58:11 sync_lock.go:106: unmarshal lock sync failed: unexpected end of JSON input
E 2024/11/13 09:58:11 sync_lock.go:109: remove unmarshalled lock sync failed: Remove SiYuan/siyuan/repo/lock-sync: 400
E 2024/11/13 09:58:11 repository.go:1318: sync data repo failed: Remove SiYuan/siyuan/repo/lock-sync: 400
E 2024/11/13 09:58:11 sync.go:592: sync failed caused by network: Remove SiYuan/siyuan/repo/lock-sync: 400

**Comment by amenekowo** [comment]
请问一下是如何解决的？我现在使用WebDAV同步也出现了相同的问题
