### ISSUE TITLE
WebDAV账号密码本机硬盘明文存储

### ISSUE THREAD

**Issue by hopana** [siyuan-note/siyuan#13137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/329d3a2a-055b-44ce-bbce-0161d69463bb)

WebDAV配置居然是明文存在本地！！！

### Expected result

至少加个密存储吧，对称加密或者混淆一下也行啊

### Version environment

```markdown
- Version: v3.1.11
- Operating System: Win11 23H2
- Browser (if used):
```

### Log file

无

**Comment by lisontowind** [comment]
讲个恐怖故事，Chromium系浏览器的密码管理。。。。。

**Comment by hopana** [comment]
> 讲个恐怖故事，Chromium系浏览器的密码管理。。。。。

虽然众所周知，Chrome是这么干的，但是不代表人家就是对的，本人是做技术的，哪怕简单的转换一下编码也能起到不错的作用，而且实现起来不难，所以，我觉得还是尽量不要存明文比较好😑

**Comment by royc01** [comment]
加密也没意义啊，这个配置是可以直接导出的

**Comment by TCOTC** [comment]
应该说只要打开了思源就能看到密码

**Comment by 88250** [comment]
在没有办法做到安全的情况下还是不考虑了，不然依然有泄漏风险。

建议 WebDAV 服务端单独建立思源文件夹进行管理，不要和其他文件夹混用，从服务端管理来规避安全风险。
