### ISSUE TITLE
反链面板中拖拽发生崩溃

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#13131]
操作流程：
![Clip_2024-11-12_23-42-24](https://github.com/user-attachments/assets/cffae3de-f6d8-42b7-9f77-4f7248afea2e)

![recording](https://github.com/user-attachments/assets/696172de-79e4-4021-8a3a-a5aa85abbab9)

**Comment by SaXz2** [comment]
> ### In what scenarios do you need this feature?
> 操作流程： ![Clip_2024-11-12_23-42-24](https://private-user-images.githubusercontent.com/52444119/385353229-cffae3de-f6d8-42b7-9f77-4f7248afea2e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjY0OTUsIm5iZiI6MTczMTQyNjE5NSwicGF0aCI6Ii81MjQ0NDExOS8zODUzNTMyMjktY2ZmYWUzZGUtZjZkOC00MmI3LTlmNzctNGY3MjQ4YWZlYTJlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1NDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MTM5ODVhZWEwZDA2NjI5ZTNjNmZhNWUyOTBlYjkzOWYxMTI3OTk0ODg5NDMwZmQ1YjdiMTg5MzBhZmZhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dHcSdt2vP8fdx_UbTyzAnXU2lABRu85Y3jHjR-UAbAA)
> 
> ![recording](https://private-user-images.githubusercontent.com/52444119/385353481-696172de-79e4-4021-8a3a-a5aa85abbab9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjY0OTUsIm5iZiI6MTczMTQyNjE5NSwicGF0aCI6Ii81MjQ0NDExOS8zODUzNTM0ODEtNjk2MTcyZGUtNzllNC00MDIxLThhM2EtYTVhYTg1YWJiYWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1NDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MjVhMzM0MTVlNDc1YTQxZDZmNzZkMzRhZDEzNmU5NzEyMzBiZTBmMmVmMjk5ZTYwMWVkMTRhYTMwMWExNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w9VF2LgD_PDuyx3y2knek8N8QfVjrFlkgnANpzOTUAE) [ ![recording](https://private-user-images.githubusercontent.com/52444119/385353481-696172de-79e4-4021-8a3a-a5aa85abbab9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjY0OTUsIm5iZiI6MTczMTQyNjE5NSwicGF0aCI6Ii81MjQ0NDExOS8zODUzNTM0ODEtNjk2MTcyZGUtNzllNC00MDIxLThhM2EtYTVhYTg1YWJiYWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1NDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MjVhMzM0MTVlNDc1YTQxZDZmNzZkMzRhZDEzNmU5NzEyMzBiZTBmMmVmMjk5ZTYwMWVkMTRhYTMwMWExNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w9VF2LgD_PDuyx3y2knek8N8QfVjrFlkgnANpzOTUAE) ](https://private-user-images.githubusercontent.com/52444119/385353481-696172de-79e4-4021-8a3a-a5aa85abbab9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjY0OTUsIm5iZiI6MTczMTQyNjE5NSwicGF0aCI6Ii81MjQ0NDExOS8zODUzNTM0ODEtNjk2MTcyZGUtNzllNC00MDIxLThhM2EtYTVhYTg1YWJiYWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1NDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MjVhMzM0MTVlNDc1YTQxZDZmNzZkMzRhZDEzNmU5NzEyMzBiZTBmMmVmMjk5ZTYwMWVkMTRhYTMwMWExNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w9VF2LgD_PDuyx3y2knek8N8QfVjrFlkgnANpzOTUAE) [ ](https://private-user-images.githubusercontent.com/52444119/385353481-696172de-79e4-4021-8a3a-a5aa85abbab9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjY0OTUsIm5iZiI6MTczMTQyNjE5NSwicGF0aCI6Ii81MjQ0NDExOS8zODUzNTM0ODEtNjk2MTcyZGUtNzllNC00MDIxLThhM2EtYTVhYTg1YWJiYWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1NDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MjVhMzM0MTVlNDc1YTQxZDZmNzZkMzRhZDEzNmU5NzEyMzBiZTBmMmVmMjk5ZTYwMWVkMTRhYTMwMWExNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w9VF2LgD_PDuyx3y2knek8N8QfVjrFlkgnANpzOTUAE)

**Comment by 88250** [comment]
这个改进就不归入特定里程碑版本了，谢谢。
This improvement will not be included in a specific milestone version, thank you.
