### ISSUE TITLE
pdf 标注失效

### ISSUE THREAD

**Issue by city945** [siyuan-note/siyuan#13130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当标注 assets 子目录下的 pdf 时，复制的 pdf 标注只有纯文本
<<assets/books/《Python3 网络爬虫开发实战》.pdf/20241112213458-w2qn82x "books/《Python3 网络爬虫开发实战》.pdf-P11-20241112213458-w2qn82x">>

### Expected result

期望为正常可跳转的 pdf 标注链接

### Version environment

```markdown
- Version: 3.0.17
- Operating System: MacOS 15.0 Sequpia
```

### Log file

None

### More information

当从外部拖入 pdf 文件 a.pdf 时，会在 assets 下生成副本 a-xxxx-xxxx.pdf，此时 pdf 标注正常
比较希望能将 pdf 集中放在 assets 的子目录如 assets/books 下并保持原始的 pdf 文件名，当我直接创建这个子目录并复制 pdf 进去，可以从思源笔记中导入该 pdf 资源并打开，但是此时复制标注出现异常，变成了如上格式的纯文本字符串，而不是链接

**Comment by 88250** [comment]
你好，PDF 标注仅支持在 assets 文件夹下使用，不支持子文件夹。

**Comment by city945** [comment]
> 你好，PDF 标注仅支持在 assets 文件夹下使用，不支持子文件夹。

非常感谢，方便再问一下，我看 REAME 中说"思源笔记是完全开源的"，是否意味着如果 clone 这份开源代码，就能编译出 Release 中发布的 xxx-mac.dmg？
此外，dockerhub 上的 b3log/siyuan:v3.1.11 镜像中是否包含开发环境，代码 clone 到容器中就能编译吗？
比较感兴趣个人定制一些功能或者参与到社区的 bug 解决中来 Thanks♪(･ω･)ﾉ

**Comment by 88250** [comment]
可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月15日(周五) 下午3:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] pdf 标注失效 (Issue #13130)




  
你好，PDF 标注仅支持在 assets 文件夹下使用，不支持子文件夹。
  
非常感谢，方便再问一下，我看 REAME 中说"思源笔记是完全开源的"，是否意味着如果 clone 这份开源代码，就能编译出 Release 中发布的 xxx-mac.dmg？
 此外，dockerhub 上的 b3log/siyuan:v3.1.11 镜像中是否包含开发环境，代码 clone 到容器中就能编译吗？
 比较感兴趣个人定制一些功能或者参与到社区的 bug 解决中来 Thanks♪(･ω･)ﾉ
