### ISSUE TITLE
折叠展开上级标题后嵌入块的问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13134]
1. 折叠上级标题后嵌入块不显示，刷新能恢复
2. 展开之后嵌入块没有同步展开
3. 面包屑没有及时更新

[video.webm](https://github.com/user-attachments/assets/163845c9-6eb9-4f38-88ac-c5c706a1359b)

**Comment by 88250** [comment]
面包屑不会实时刷新的。

前面两个问题 @Vanessa219 看一下

**Comment by Vanessa219** [comment]
先把折叠后有问题的修改了，展开的话先不处理了。
