### ISSUE TITLE
块折叠后的编辑改进

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#1313]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在输入过程中需要对部分块进行折叠,折叠块后输入新的内容时无法输入
且目前在折叠块后输入的内容出现的位置也有问题

https://user-images.githubusercontent.com/11732858/106022882-40812880-6101-11eb-85f9-6b3b036b3b2a.mp4

### 描述最优的解决方案 Describe the optimal solution
类似这样,块折叠后,在下面可以继续键入文字

https://user-images.githubusercontent.com/11732858/106022848-37905700-6101-11eb-91a2-4f5ca6762d8d.mp4

**Comment by Vanessa219** [comment]
现在点击空白处可以新建空块，应该是上次修复相关 issue 的时候修复了，如果还有问题再打开就可以了。
