### ISSUE TITLE
Access authorization code captcha vulnerability

### ISSUE THREAD

**Issue by xzajyjs** [siyuan-note/siyuan#13147]
There is a logic vulnerability in the verification code of the login interface

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

After the front-end enters the correct verification code, the packet is captured and held, and then the current verification code can be used for unlimited replay attacks (the password can be cracked)
---
# Step 1. Capture the packet
![image-20241114170406421](https://serverless-page-bucket-lv779z7b-1307395653.cos.ap-shanghai.myqcloud.com/picgo/202411141704437.png)

# Step 2. Use the same verification code to blast password
![image-20241114170356960](https://serverless-page-bucket-lv779z7b-1307395653.cos.ap-shanghai.myqcloud.com/picgo/202411141703978.png)

# Step 3. Find the correct password no need verifying the verification code
![image-20241114170346964](https://serverless-page-bucket-lv779z7b-1307395653.cos.ap-shanghai.myqcloud.com/picgo/202411141703116.png)

### Expected result

The current verification code lifecycle ends after each login attempt

### Version environment

```markdown
- Version: All Versions
- Operating System: All Systems
- Browser (if used): All Browsers
```

### Log file

No need.

**Comment by 88250** [comment]
Hi, do you mean the `captch` will not be reset?

**Comment by 88250** [comment]
Thanks for the feedback, I have been able to reproduce the issue and will fix it in the next version.
