### ISSUE TITLE
调整 `块引动态锚文本最大长度` 之后需要刷新块引用动态锚文本、数据库主键锚文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13140]
比如引用一个文档，要重命名这个文档才能刷新块引用：

![image](https://github.com/user-attachments/assets/7cd14dcc-3b41-4065-8f66-21671ecc26dc)

![image](https://github.com/user-attachments/assets/5816784d-2d61-4098-acb9-acd288ea8950)

**Comment by 88250** [comment]
这个选项只能对后面的操作生效，之前的锚文本数据不会刷新。

**Comment by TCOTC** [comment]
所以为什么不能刷新一下呢？

**Comment by 88250** [comment]
动以前的锚文本不一定是预期

**Comment by TCOTC** [comment]
我认为这里就是要实时调整才合逻辑：

![image](https://github.com/user-attachments/assets/679b8d20-46d2-498d-bbd7-c4ce8a58a0f5)

不行的话我去搞个投票看看

**Comment by 88250** [comment]
过去几年里面没有这个需求，我觉得最好不要动了。

**Comment by TCOTC** [comment]
另外这里的搜索文本应该是完整的主键纯文本：

[video.webm](https://github.com/user-attachments/assets/8dd7372e-c1ed-4e65-9aae-a3629d0ebebc)

**Comment by 88250** [comment]
主键这里改为不受那个锚文本设置项限制，直接使用一个较大值 `10240` 如何？

**Comment by TCOTC** [comment]
赞同

**Comment by 88250** [comment]
改成 1024 吧，10240 太大了。
