### ISSUE TITLE
嵌入块的面包屑始终需要最后一层块标

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13141]
如果没有最后一层块标，聚焦整篇文档之后就不能直接聚焦回原来显示的块

**Comment by 88250** [comment]
没看懂你说的是哪种情况，截图看下。

**Comment by TCOTC** [comment]
刚刚发现只有嵌入列表块才出现这个问题：

[video.webm](https://github.com/user-attachments/assets/6b2ef9bc-d5bc-4131-a593-f35fd48f3f91)

另外我觉得最后一层面包屑好像没必要显示文本

**Comment by 88250** [comment]
这个是正常的，因为列表块本身也不会显示面包屑。

嵌入块这里最后一层暂时还是保留文本显示，只有反链面板中不显示。

**Comment by TCOTC** [comment]
那要不还是加一下列表块的面包屑吧，现在只能通过刷新嵌入块才能聚焦回去，逻辑不太一致

**Comment by 88250** [comment]
列表这一层是故意去掉的

**Comment by TCOTC** [comment]
面包屑中间不需要加，但如果最后一层是列表块的话就加上吧

**Comment by 88250** [comment]
这个主意不错，稍后改进。

**Comment by 88250** [comment]
收到，稍后改进。
