### ISSUE TITLE
添加获取当前活动文档id和当前块id的内核API

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#13148]
### In what scenarios do you need this feature?

主要用于quicker等外部工具。
有时候需要获取当前活动文档信息，但是quicker等外部工具又无法在思源内部执行js代码来获取信息。

### Describe the optimal solution

如果没有打开文档，返回空。
如果打开了文档，返回当前文档id和块id。
焦点不在编辑器内能返回块id吗？无法实现的话可忽略块id

**Comment by TCOTC** [comment]
用这个插件：

![image](https://github.com/user-attachments/assets/c6b0433f-1f24-4430-ae80-6a2d67c309a9)

**Comment by AdachiQ** [comment]
> 用这个插件：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/386155467-c6b0433f-1f24-4430-ae80-6a2d67c309a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODEyNjYsIm5iZiI6MTczMTU4MDk2NiwicGF0aCI6Ii83ODQzNDgyNy8zODYxNTU0NjctYzZiMDQzM2YtMWYyNC00NDMwLWFlODAtNmEyZDY3YzMwOWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwNDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNDQyODU0YjVhNDU4MTMwYWRlMzM5ZmVkZDQ5MWJhYzE4MjE4MzUwYzRkODFlMjI4YWNjOGJiMTNjODNhNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KWby8k26msadwN0mEPQX4_CgguigLaDFtBRlVwV77T8)
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/386155829-cf202c75-0f60-42d4-81b8-dfd357e77025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODEyNjYsIm5iZiI6MTczMTU4MDk2NiwicGF0aCI6Ii83ODQzNDgyNy8zODYxNTU4MjktY2YyMDJjNzUtMGY2MC00MmQ0LTgxYjgtZGZkMzU3ZTc3MDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwNDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MWZlYjlkODY3M2Y0Njg5YmUzOTM2NTNjZDY0MmE3MjM3ZTU3NjhhZDNkNmRjZjY3MjVjM2ZlMTY0ZGI2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N9Ou4BiQBncVGWOvTgvCHE9jMkqYbW_xrrEBpVgTjmo)

就是不想让用户安装额外的插件才提的

**Comment by TCOTC** [comment]
那实际的用户需求场景是什么？获取 id 用来做什么？

**Comment by AdachiQ** [comment]
> 那实际的用户需求场景是什么？获取 id 用来做什么？

https://getquicker.net/Sharedaction?code=cdac9f0b-1bd9-4e96-b873-08dad0f8d7c2
比如获取当前文档id来汇总当前页面反链和待办

**Comment by TCOTC** [comment]
> [getquicker.net/Sharedaction?code=cdac9f0b-1bd9-4e96-b873-08dad0f8d7c2](https://getquicker.net/Sharedaction?code=cdac9f0b-1bd9-4e96-b873-08dad0f8d7c2) 比如获取当前文档id来汇总当前页面反链和待办

用这个就行了

**Comment by TCOTC** [comment]
我看了一下，用到的子程序是这个：https://getquicker.net/subprogram?id=b1fafc14-befb-4cfb-4656-08db159e6a6f

**Comment by AdachiQ** [comment]
> 我看了一下，用到的子程序是这个：https://getquicker.net/subprogram?id=b1fafc14-befb-4cfb-4656-08db159e6a6f

这个子程序我写的，有局限性，比如用户改了快捷键就不能用了，比如焦点不在编辑器内了失效了

**Comment by AdachiQ** [comment]
> * 改了快捷键就不能用了
> * 焦点不在编辑器内了失效了
> 
> 这两个怎么复现？

把赋值块超链接的快捷键改掉
把焦点放在反链面板内

**Comment by TCOTC** [comment]
没复现出来，麻烦录屏看看

**Comment by AdachiQ** [comment]
> 没复现出来，麻烦录屏看看

记错了，上面的问题是这个子程序的：https://getquicker.net/SubProgram?id=28576c99-9754-4487-62c8-08da9360f478
你发的那个子程序存在的问题是当前文档id可能错误，因为是读取conf.json文件来获取信息的，但是conf.json文件的写入并不实时，切换文档后马上运行子程序会获取到前一个文档的id

**Comment by TCOTC** [comment]
> 切换文档后马上运行子程序会获取到前一个文档的id

这个倒不算什么问题，我看到 conf.json 基本能在 500ms 内更新

**Comment by wish5115** [comment]
> > 没复现出来，麻烦录屏看看
> 
> 记错了，上面的问题是这个子程序的：https://getquicker.net/SubProgram?id=28576c99-9754-4487-62c8-08da9360f478 你发的那个子程序存在的问题是当前文档id可能错误，因为是读取conf.json文件来获取信息的，但是conf.json文件的写入并不实时，切换文档后马上运行子程序会获取到前一个文档的id

可以二者结合相互印证以增加可靠性，比如，现通过快捷键获取当前块id，然后通过块id查询文档id，然后再通过conf.json查询当前文档id，然后必须两者完全一致才认为是有效，否则，等待500ms重试，这样，即使有一个方法出错也能避免误取。

**Comment by KuiyueRO** [comment]
获取当前块的最顶层块ID的api。这个也有些需求

例如查看最顶层的块是不是某个类型的块，现在虽然有其他办法实现，但提供一个api应该会顺手不少。

**Comment by TCOTC** [comment]
如果能直接运行 JS 的话就最好了

**Comment by wish5115** [comment]
有一个办法可以较准的获取文档id,
之前用ctrl+shift+h获取块id，不是用户可能会改按键吗
现在可以用/api/system/getConf获取配置，然后找到keymap字段，可解析里面的custom字段的按键值，然后再和quicker的按键做个映射就可以较准确的按键了。

思源按键列表：
 https://github.com/siyuan-note/siyuan/blob/487c48427ae8e3b840d209047cc316273c7a3931/app/src/constants.ts#L207
quicker按键列表：
https://getquicker.net/KC/Help/Doc/sendkeys

**Comment by TCOTC** [comment]
实际上用户可能会删除快捷键

**Comment by 88250** [comment]
内核是无状态的，无法得到当前界面活动的文档，如果需要界面配合，建议通过界面插件进行交互。

**Comment by wish5115** [comment]
> 如果能直接运行 JS 的话就最好了

@TCOTC 我实现了quicker向思源发送js代码并返回结果功能

子程序
https://getquicker.net/SubProgram?id=cb322876-e4a3-462a-e322-08dd0733f195

使用示例
https://getquicker.net/Sharedaction?code=0557062c-aecb-4942-e321-08dd0733f195
