### ISSUE TITLE
如果文档首个块是嵌入块，在文档标题按 Enter 无法在文档开头新建一个段落块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13142]

**Comment by TCOTC** [comment]
有点怪，我只在这个工作空间才能复现：[测试空间.zip](https://github.com/user-attachments/files/17777829/default.zip)

[video.webm](https://github.com/user-attachments/assets/4165a467-b0a7-42ba-bd98-ac79da8cd97c)

**Comment by 88250** [comment]
我这里可以重现了，稍后排查。

**Comment by Vanessa219** [comment]
已修复，不拉进版本了
