### ISSUE TITLE
unraid 部署思源笔记 3.1.11 版无法 webdav 同步

### ISSUE THREAD

**Issue by zbigbird** [siyuan-note/siyuan#13145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在unraid部署思源笔记后，webdav无法同步

### Expected result

希望能得到指导，多次尝试webdav配置，同步仍然不成功

### Version environment

```markdown
- Version: 3.1.11
- Operating System: unraid
- Browser (if used):
```

### Log file

Using existing group: siyuan (1000)
Using existing user siyuan (PUID: 1000, PGID: 1000)
Adjusting ownership of /opt/siyuan, /home/siyuan/, and /siyuan/workspace
Starting Siyuan with UID:1000 and GID:1000 in workspace /siyuan/workspace
I 2024/11/14 16:04:03 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/11/14 16:04:03 runtime.go:79: kernel is booting:
    * ver [3.1.11]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace]
I 2024/11/14 16:04:03 conf.go:130: loaded conf [/siyuan/workspace/conf/conf.json]
I 2024/11/14 16:04:03 runtime.go:128: use network proxy [system]
I 2024/11/14 16:04:03 serve.go:139: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/11/14 16:04:05 sync.go:147: sync before boot
I 2024/11/14 16:04:05 ref.go:50: got local latest [device=ia51hzv4yd85/linux, id=a99868306d62337ebffc57117a7df848ebb80310, files=7, size=7.69 kB, created=2024-11-13 16:47:52]
I 2024/11/14 16:04:05 repo.go:591: walk data [files=7] cost [5.758202ms]
I 2024/11/14 16:04:05 ref.go:50: got local latest [device=ia51hzv4yd85/linux, id=a99868306d62337ebffc57117a7df848ebb80310, files=7, size=7.69 kB, created=2024-11-13 16:47:52]
I 2024/11/14 16:04:05 ref.go:50: got local latest [device=ia51hzv4yd85/linux, id=a99868306d62337ebffc57117a7df848ebb80310, files=7, size=7.69 kB, created=2024-11-13 16:47:52]
W 2024/11/14 16:04:05 sync.go:1581: not found cloud latest
I 2024/11/14 16:04:05 repository.go:1228: boot get sync cloud files elapsed [0.55s]
I 2024/11/14 16:04:06 conf.go:841: database size [7.9 MB], tree/block count [0/0]
I 2024/11/14 16:04:06 working.go:193: kernel booted
I 2024/11/14 16:04:06 box.go:77: auto stat [trees=0, blocks=0, dataSize=57.3 kB, assetsSize=0 B]
I 2024/11/14 16:08:10 repository.go:1290: syncing data repo [device=ia51hzv4yd85, kernel=b970gi9, provider=3, mode=a/true]
I 2024/11/14 16:08:10 ref.go:50: got local latest [device=ia51hzv4yd85/linux, id=a99868306d62337ebffc57117a7df848ebb80310, files=7, size=7.69 kB, created=2024-11-13 16:47:52]
I 2024/11/14 16:08:10 repo.go:591: walk data [files=7] cost [4.571552ms]
I 2024/11/14 16:08:10 ref.go:50: got local latest [device=ia51hzv4yd85/linux, id=a99868306d62337ebffc57117a7df848ebb80310, files=7, size=7.69 kB, created=2024-11-13 16:47:52]
E 2024/11/14 16:08:11 webdav.go:469: mkdir [main/siyuan/repo] failed: MkdirAll /main/siyuan/repo/: 415
E 2024/11/14 16:08:11 sync_lock.go:161: upload lock sync failed: MkdirAll /main/siyuan/repo/: 415
E 2024/11/14 16:08:11 repository.go:1318: sync data repo failed: lock cloud repo failed

### More information

同一问题已经在链滴提交，现在不知道是我配置的原因还是什么问题，请尽快帮我解决，谢谢

**Comment by zbigbird** [comment]
在unraid下，查看权限是正确的：
root@officenas:/mnt/user/appdata/siyuan# ls -l
root@officenas：/mnt/user/appdata/siyuan# ls -l
total 4 共 4 页
drwxr-xr-x 1 1000 1000 53 Nov 14 16:13 conf/
drwxr-xr-x 1 1000 1000 53 11月 14 16：13 conf/
drwxr-xr-x 1 1000 1000 161 Nov 13 15:45 data/
drwxr-xr-x 1 1000 1000 161 11月 13 日 15：45 数据/
drwxr-xr-x 1 1000 1000 10 Nov 13 15:17 note/
drwxr-xr-x 1 1000 1000 10 11月 13 15：17 注/
drwxr-xr-x 1 1000 1000 85 Nov 14 16:13 repo/
drwxr-xr-x 1 1000 1000 85 11月 14 16：13 repo/
drwxr-xr-x 1 1000 1000 4096 Nov 14 16:04 temp/
drwxr-xr-x 1 1000 1000 4096 11 月 14 日 16：04 temp/
root@officenas:/mnt/user/appdata/siyuan# cd /mnt/user/appdata/
root@officenas：/mnt/user/appdata/siyuan# cd /mnt/user/appdata/
root@officenas:/mnt/user/appdata# ls -l
root@officenas：/mnt/user/appdata# ls -l
total 12 共 12 页
drwxr-xr-x 1 root root 10 Nov 11 09:15 Nginx-Proxy-Manager-Official/
drwxr-xr-x 1 根根 10 年 11 月 11 日 09：15 nginx-proxy-manager-official/
drwxr-xr-x 1 root root 47 May 20 14:47 calibre/
drwxr-xr-x 1 根 根 47 年 5 月 20 日 14：47 口径/
drwxr-xr-x 1 nobody users 10 Nov 14 15:17 cloudflared/
drwxr-xr-x 1 nobody users 10 11月 14 15：17 cloudflared/
drwxr-xr-x 1 root root 28 May 23 15:44 filebrowser/
drwxr-xr-x 1 根根 28 年 5 月 23 日 15：44 文件浏览器/
drwxrwxrwx 1 nobody users 92 Nov 12 17:42 filestash/
drwxrwxrwx 1 nobody users 92 11月 12 17：42 filestash/
drwxr-xr-x 1 root root 62 Aug 29 16:47 homarr/
drwxr-xr-x 1 根 根 62 8 月 29 日 16：47 homarr/
drwxr-xr-x 1 nobody users 4096 Nov 7 15:52 lucky/
drwxr-xr-x 1 nobody users 4096 11月 7 15：52 lucky/
drwxr-xr-x 1 nobody users 68 May 20 08:52 mariadb/
drwxr-xr-x 1 nobody users 68 5月 20 08：52 mariadb/
drwx------ 1 999 users 4096 Nov 8 11:25 maxkb/
drwx------ 1 999 个用户 4096 11 月 8 日 11：25 maxkb/
drwxr-xr-x 1 nobody users 29 Nov 13 00:04 nocodb/
drwxr-xr-x 1 nobody users 29 11月 13 00：04 nocodb/
drwxr-xr-x 1 root root 4096 Nov 14 16:11 resilio-sync/
drwxr-xr-x 1 根根 4096 11 月 14 日 16：11 resilio-sync/
drwxr-xr-x 1 root root 92 Jun 11 16:58 s-pdf/
drwxr-xr-x 1 根根 92 Jun 11 16：58 s-pdf/
drwxr-xr-x 1 root root 10 Nov 11 09:15 sftpgo/
drwxr-xr-x 1 根 根 10 11月 11 日 09：15 sftpgo/
drwxrwxrwx 1 1000 1000 107 Nov 13 15:31 siyuan/
drwxrwxrwx 1 1000 1000 107 11月 13 15：31 思源/
drwxr-xr-x 1 1000 1000 138 Sep 3 16:11 trilium/
drwxr-xr-x 1 1000 1000 138 9 月 3 日 16：11 trilium/
drwxr-xr-x 1 nobody users 157 Nov 1 21:39 vocechat/
drwxr-xr-x 1 nobody users 157 11月 1 21：39 vocechat/
drwxr-xr-x 1 nobody users 45 Nov 11 14:20 webdav/
drwxr-xr-x 1 nobody users 45 11月 11 14：20 webdav/
drwxr-xr-x 1 nobody users 33 Nov 14 05:37 wewe-rss/
drwxr-xr-x 1 没有人用户 33 11月 14 05：37 wewe-rss/
root@officenas:/mnt/user/appdata#
root@officenas：/mnt/user/appdata#

**Comment by 88250** [comment]
```
E 2024/11/14 16:08:11 webdav.go:469: mkdir [main/siyuan/repo] failed: MkdirAll /main/siyuan/repo/: 415
E 2024/11/14 16:08:11 sync_lock.go:161: upload lock sync failed: MkdirAll /main/siyuan/repo/: 415
```
试下手动创建这个文件夹后再同步。

**Comment by zbigbird** [comment]
尝试过了，还是不行，不肯能每个文件夹和文件都手动创建吧？
