### ISSUE TITLE
PDF 的“大纲”和“显示缩略图”无法调整边栏宽度

### ISSUE THREAD

**Issue by hihaojie** [siyuan-note/siyuan#13144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

浏览 PDF 时，鼠标光标拖动“大纲”、“显示缩略图”边栏宽度无效
![image](https://github.com/user-attachments/assets/a83d351d-177b-4689-b595-bf85705e6a74)
 

### Expected result

可以正常拖动边栏，调整宽度

### Version environment

```markdown
- Version: 3.1.11
- Operating System: Windows10、Windows11、Android14（HyperOS 1.0.20.0）
- Browser (if used):Edge（手机伺服模式）
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17742222/siyuan.log)

**Comment by xian54966** [comment]
也发现同样问题

**Comment by TCOTC** [comment]
调整宽度之后里面的页面宽度没有变，是固定的：

![image](https://github.com/user-attachments/assets/0c264921-30ae-4103-a36d-0e1ee8e27ef5)

**Comment by Vanessa219** [comment]
这个是正常的，可参考 pdf.js

**Comment by TCOTC** [comment]
奇怪，我怎么感觉之前是会变的

**Comment by Vanessa219** [comment]
后面更新了
