### ISSUE TITLE
`Ctrl+Alt+M` 快捷键无法使用

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13158]
选中文本后按快捷键 `Ctrl+Alt+M` 什么也没发生

v3.1.12-dev3

[video.webm](https://github.com/user-attachments/assets/ba4fd889-eeae-4abd-984a-00c6b294e6c5)

**Comment by TCOTC** [comment]
@88250 你看看在 Windows 能不能复现

**Comment by 88250** [comment]
我这里也有问题

**Comment by TCOTC** [comment]
在 NVIDIA GeForce Experience 中关掉这个即可解决：

![2f40bf257082ab40a07daa2060b6dbb3](https://github.com/user-attachments/assets/e153ab40-1ef1-4b41-ba0c-413bec77b8d0)

或者更改快捷键：

![image](https://github.com/user-attachments/assets/9b529710-7bfa-4c6b-b42a-d5db6f9635be)

![image](https://github.com/user-attachments/assets/a02b9635-6389-42b4-9e94-9a7ad2cc2bbe)

![image](https://github.com/user-attachments/assets/4d828943-95a4-4b16-9ea0-00bcf7d2d2ab)

![image](https://github.com/user-attachments/assets/a706dfde-c1c6-4dbb-b4ae-d7e1a982cbb4)
