### ISSUE TITLE
思源的命令面板浪费了，建议充分利用起来

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#13159]
### In what scenarios do you need this feature?

<img width="441" alt="image" src="https://github.com/user-attachments/assets/9997c1e3-50cb-4573-93b2-b6d28ef20d66">

思源的命令面板功能太少了，大部分功能都不能用命令执行，感觉新手可能都不知道有这个功能。

如果使用obsidian久了，在思源里总觉得缺少了什么，不够顺手，原因就是没有命令。

在obsidian中，可以说命令就是一等公民，ob中几乎所有的操作都可以通过命令执行，而且，可以通过插件或js调用执行命令。

插件中也有命令，也可以调用插件里的命令，插件之间互调等，可以说，ob里，如果开发一个插件，那首先要做的就是注册命令，把几乎所有的开放功能都会注册为命令。

命令用起来真的比鼠标，菜单啥的快捷方便多了，而且ob里可以进行命令管理，可以给常用命令设置别名，重命名，排序等，不要太方便了。

我觉得，如果思源里命令能开发的像ob一样完善，应该是一个巨大的飞跃，不仅对用户更加方便，对开发也更加方便。

建议D大认真考虑下！

@88250 @Vanessa219 V @TCOTC T

### Describe the optimal solution

建议认真考虑！

**Comment by 88250** [comment]
命令面板目前主要是放置插件功能 https://github.com/siyuan-note/siyuan/issues/8526#issuecomment-1605302645

**Comment by wish5115** [comment]
谢谢！我觉得应该作为核心功能，一等公民，越早规划越好。

**Comment by hxchtiewei** [comment]
我觉得往命令方向发展纯纯的程序员思维，只会让软件受众越来越少。良好的ui交互才是获得更多用户以及活下去的真理。
