### ISSUE TITLE
内置拆分合并块的功能

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#13156]
### In what scenarios do you need this feature?

思源目前在拆分合并方面还不太顺手，可以提升一下这方面的功能和体验。

### Describe the optimal solution

1. 按标题拆分为新文档块
2. 按标题拆分为子文档，并转化为层级，如果层级超过7层，弹出提示：继续拆分超过7层；拆分到最后一层按同层级拆分；拆分到最后一层，heading不再拆分。
3. 将文档树中的子文档按照层级合并到父文档
4. 将选中块拆分为未命名/内置属性命名的新文档
5. 将文档移动到另一块中合并为超级块

以上需求希望可以保留块id、块属性。如果是合并为超级块，则将文档命名添加到内置属性的命名中。

**Comment by TCOTC** [comment]
建议手动处理，或者用这个插件：

![image](https://github.com/user-attachments/assets/fb58b300-2bc0-4534-a3c3-bd0219060bfb)

**Comment by KuiyueRO** [comment]
真心感觉还是内置比较好，之前就是用的这个插件，但这个插件看起来已经失效了

**Comment by TCOTC** [comment]
我这里插件是能正常工作的，你可以录屏看看有什么问题

**Comment by KuiyueRO** [comment]
没事了，知道是啥问题了。插件工作正常
