### ISSUE TITLE
打开思源后，如果页签很多，应该定位到最后打开的那个页签

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13164]
目前还要再滚动去找到页签：

[video.webm](https://github.com/user-attachments/assets/a2caec79-d1df-457b-84e0-6aacbed1c1f8)

**Comment by Vanessa219** [comment]
我这里是好的

https://github.com/user-attachments/assets/c2687046-b331-4bb3-973f-e2e6832394cc

**Comment by TCOTC** [comment]
这个打开的页签是在一堆页签的左边吗？

**Comment by Vanessa219** [comment]
左右都有好像还是正常的

https://github.com/user-attachments/assets/ffbd21ed-bf88-42b8-a2d2-d859edb29c7f

**Comment by TCOTC** [comment]
@88250 那边怎么样？

**Comment by 88250** [comment]
我这里可以重现

**Comment by Vanessa219** [comment]
可以重现了，不拉进版本了。
