### ISSUE TITLE
标签面板内的结果排除模板

### ISSUE THREAD

**Issue by Jamie-Wan** [siyuan-note/siyuan#1316]
### 描述问题 Describe the problem
模板内的标签会显示

### 期待的结果 Expected result
在标签面板内不会显示模板里的标签结果

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，能详细描述一下么，没看懂哦……

**Comment by Jamie-Wan** [comment]
![image](https://user-images.githubusercontent.com/65280479/106084258-f7f55980-6158-11eb-9d9d-cce752ebbefb.png)
不会显示模板文件夹里的

**Comment by 88250** [comment]
谢谢，我明白了，下个版本改进。
