### ISSUE TITLE
For flashcard blocks without fill-in-the-blank cards created, cancel "Show Answer".对于没有制作填空卡的闪卡块，取消“显示答案”

### ISSUE THREAD

**Issue by TangQi001** [siyuan-note/siyuan#13163]
### In what scenarios do you need this feature?

对于闪卡，只有填空卡，依据闪卡是否有填空，现在可以分为：
没有标记（填空卡）的单独段落闪卡
有标记（填空卡）的填空闪卡

对于没有填空卡的单独段落闪卡，我对此只有两个目的：
1.用这张卡制作填空
2.单独复习这个段落块

然而，无论是哪一种，都没有“显示答案”的步骤需求，所以我认为可以取消

而且，“显示答案”会导致使用段落闪卡制作填空闪卡时，必须要先点击一次显示答案，然后再制作闪卡，否则就会导致制作闪卡后文本被填空覆盖了，只能显示答案然后看到新制作的填空内容

For flashcards, there are only fill-in-the-blank cards. According to whether there is a fill-in-the-blank on the flashcard, it can now be divided into:
Separate paragraph flashcards without a mark (fill-in-the-blank card).
Fill-in-the-blank flashcards with a mark (fill-in-the-blank card).

For separate paragraph flashcards without a fill-in-the-blank card, I only have two purposes for this:
1. Use this card to create fill-in-the-blanks.
2. Review this paragraph block alone.

However, for either type, there is no need for the step of "showing the answer", so I think it can be cancelled.

Moreover, "showing the answer" will cause when using paragraph flashcards to create fill-in-the-blank flashcards, you must click to show the answer once first, and then create the flashcard. Otherwise, after creating the flashcard, the text will be covered by the fill-in-the-blank, and you can only show the answer and then see the newly created fill-in-the-blank content.

Author: TangQi
Link: https://ld246.com/article/1730688209179
Source: Linkdrop
License: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/

### Describe the optimal solution

对于没有填空卡的段落闪卡，取消“显示答案这一步骤”

但是，这就会导致新的问题，由于思源没有摘录卡和填空卡概念，就会导致复习过程中的操作不流畅，比如一张卡点一下就复习，另一张卡点两下才复习

对于这种情况，个人建议对于段落闪卡，将“显示答案”换为“复习程度”，并且在还没有选择“复习程度”的情况下，制作标记不会将闪卡变为填空

For paragraph flashcards without fill-in-the-blank cards, cancel the "show answer" step.

However, this will lead to new problems. Since Siyuan does not have the concepts of excerpt cards and fill-in-the-blank cards, it will lead to an unsmooth operation during the review process. For example, one flashcard can be reviewed with one click, while another requires two clicks.

For this situation, I personally suggest that for paragraph flashcards, replace "show answer" with "review degree". And in the case where "review degree" has not been selected, making marks will not turn the flashcard into a fill-in-the-blank card.

Author: TangQi
Link: https://ld246.com/article/1730688209179
Source: Linkdrop
License: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/

**Comment by SaXz2** [comment]
这个改进确实会方便很多，我同样有很多的摘录卡每次都要点两次确实是有点麻烦，支持一下

**Comment by TCOTC** [comment]
@Vanessa219 “显示答案”会闪现一下：

[video.webm](https://github.com/user-attachments/assets/fc6f6c71-8cf1-4434-b014-54ec1f99d99d)
