### ISSUE TITLE
无法同步笔记数据

### ISSUE THREAD

**Issue by marshalby2** [siyuan-note/siyuan#13167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

安装思源最新版本 3.1.11,连接 WIFI 无法同步数据，切换手机 WIFI  后可以同步数据。

### Expected result

联网后既可以同步数据

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/c98faabc-409d-42c4-883b-e182fed9e523)

### Version environment

```markdown
- Version: 3.1.11
- Operating System: Kali-Linux
- Browser (if used):
```

### Log file

I 2024/11/16 22:04:59 ref.go:50: got local latest [device=98714213d8314675a9f45a42edd52117/linux, id=05ccb854bfd65c95703be4f078fd52f305735464, files=1157, size=190.03 MB, created=2024-11-16 19:48:53]
E 2024/11/16 22:05:02 sync.go:1586: download cloud latest failed: download object [siyuan/1524822749398/repo/main/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1524822749398/repo/main/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com on 192.168.1.1:53: no such host
E 2024/11/16 22:05:02 sync.go:132: download cloud latest failed: download object [siyuan/1524822749398/repo/main/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1524822749398/repo/main/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com on 192.168.1.1:53: no such host
I 2024/11/16 22:05:02 siyuan.go:231: removed object [siyuan/1524822749398/repo/main/lock-sync]
E 2024/11/16 22:05:02 repository.go:1318: sync data repo failed: download object [siyuan/1524822749398/repo/main/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1524822749398/repo/main/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com on 192.168.1.1:53: no such host
E 2024/11/16 22:05:02 sync.go:592: sync failed caused by network: download object [siyuan/1524822749398/repo/main/refs/latest] failed: Get &#34;https://siyuan-data.b3logfile.com/siyuan/1524822749398/repo/main/refs/latest&#34;: dial tcp: lookup siyuan-data.b3logfile.com on 192.168.1.1:53: no such host

**Comment by 88250** [comment]
```
E 2024/11/16 22:05:02 sync.go:132: download cloud latest failed: download object [siyuan/1524822749398/repo/main/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1524822749398/repo/main/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com on 192.168.1.1:53: no such host
```

从日志上看是网络问题，建议看下是不是 DNS 设置有问题。

**Comment by marshalby2** [comment]
补充一下，我使用的 Debian 和 Kali Linux 都遇到过这个问题，最后解决方式就是增加 dns 服务器，在 `/etc/resolv.conf` 文件中，加入
```shell
nameserver 114.114.114.114 
nameserver 1.1.1.1
nameserver 8.8.8.8
```
