### ISSUE TITLE
Feature: Whole Blog Processing

### ISSUE THREAD

**Issue by TomLucidor** [siyuan-note/siyuan#13160]
### In what scenarios do you need this feature?

There are blogs out there with a fun and long history that can be turned into a knowledge base.

### Describe the optimal solution

1. Crawl the whole blog and index  URLs of the article entries 
2. Get the contents of article entries and cache them locally
3. Run it through AI to summarize each entry (e.g. Chain-of-Density)
4. If necessary, summarize sections or paragraphs of the article
5. Custer articles from the same blog based on topic
6. Extending blog indexing power to blogosphere level (sites with similar topics)

**Comment by 88250** [comment]
It is recommended to consider using a plug-in to extend this function, thank you.

**Comment by TomLucidor** [comment]
@88250 where is the plugin repo then? Not plugin building, but whole repo for the collection of tools made by the community?

**Comment by 88250** [comment]
https://github.com/siyuan-note/bazaar

**Comment by TomLucidor** [comment]
@88250 thanks but that is a software index, not a human-readable one like an "Awesome" README. Are there anything more legible for community idea-sharing?
