### ISSUE TITLE
二维码导出云同步配置

### ISSUE THREAD

**Issue by Littleweisheit** [siyuan-note/siyuan#13166]
### In what scenarios do you need this feature?

把桌面端的配置迁移到移动端，现在火狐浏览器或者thunderbird都可以通过二维码来传递设置到移动端。
这将极大便利用户，提高使用体验。

### Describe the optimal solution

二维码

**Comment by 88250** [comment]
感谢提议，但是不考虑添加这个特性了，请使用导出/导入功能。
