### ISSUE TITLE
PDF content extraction and  summarization

### ISSUE THREAD

**Issue by TomLucidor** [siyuan-note/siyuan#13162]
### In what scenarios do you need this feature?

There are enough websites out there that breaks down the complexity of papers, but there should be FOSS alternatives for the same thing https://www.aimodels.fyi/

### Describe the optimal solution

1. (optional) automatically grab PDF links or Open Access research links and cache paper
2. Summarize singular paper in isolation (with or without techniques like Chain of Density for capturing details)
3. Address relevance between papers and other articles in the knowledge base

**Comment by 88250** [comment]
It is recommended to consider using a plug-in to extend this function, thank you.

https://github.com/siyuan-note/bazaar
