### ISSUE TITLE
Improve search highlighting

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13178]
更换搜索高亮的实现方式

- https://developer.mozilla.org/zh-CN/docs/Web/API/CSS_Custom_Highlight_API
- https://developer.mozilla.org/zh-CN/docs/Web/CSS/::highlight

目前用 data-type="search-mark" 会影响很多行级元素的自定义样式，比如 https://github.com/siyuan-note/siyuan/issues/12985#issuecomment-2481930758 ：

![image](https://github.com/user-attachments/assets/9dd444de-bc5c-446a-a686-578bfef5e99c)

![image](https://github.com/user-attachments/assets/c6c93142-acfd-4eff-acdb-bf2269181269)

以及目前的方式没法高亮代码块内的代码

**Comment by TCOTC** [comment]
话说这个高亮好像没什么区别，还是会把行级元素切碎：

![image](https://github.com/user-attachments/assets/8656fef8-f000-4cb9-8f2a-91e1d86cf3e4)

**Comment by 88250** [comment]
等会我再改进一下看看

**Comment by 88250** [comment]
后续在 https://github.com/siyuan-note/siyuan/issues/13343 中继续改进。
