### ISSUE TITLE
Search flashcards (Improvements for Manage flashcard)

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#13174]
### In what scenarios do you need this feature?

Currently Manage flashcard window shows all flashcards that you created all at once. So if you make a lot of flashcards it will become very hard to navigate through it.

### Describe the optimal solution

I suggest the following improvements for Manage flashcard window
- Basic searching like searching flashcards based on keywords 
- Advanced searching option (for example search cards based on docs (including sub-docks))
- Custom filters that can be used to filter cards based on flags/tags in future https://github.com/siyuan-note/siyuan/issues/10233 https://github.com/siyuan-note/siyuan/issues/10453
- Sort by custom options like due date, placed on which sub doc, etc.
- Batch operations like deleting cards, modifying tags/flags, etc.

### Describe the candidate solution

I think Anki browse window does the job best for exploring flashcards. https://docs.ankiweb.net/browsing.html

**Comment by 88250** [comment]
Please watch this https://github.com/siyuan-note/siyuan/issues/10471
