### ISSUE TITLE
请问如何使笔记题目下自动显示出创建时间和更新时间？

### ISSUE THREAD

**Issue by freezingbz** [siyuan-note/siyuan#13179]
### In what scenarios do you need this feature?

现在点右上角那个文件图标，最下面两行是有创建时间和更新时间的。
![图片](https://github.com/user-attachments/assets/b09eff71-fcc0-4727-8b36-017c6f749448)

但因为每个文件都点开来看很麻烦，所以希望能像下图这样，在标题之下自动显示出来：
![图片](https://github.com/user-attachments/assets/1bda446d-00b5-4c46-b96c-ace3d4086032)

图片来源于旧版的Tsundoku Lite主题，它有自动加上创建时间的功能，不过没有更新时间，且本身浮窗颜色有点异常，因此不得不换。但新版的Tsundoku就没有了这个功能，希望自己能将它加上。

### Describe the optimal solution

本身是编程小白。麻烦大佬传授下如何通过微调（猜测可能是通过代码片段那里？）加上这样的功能。谢谢！

**Comment by TCOTC** [comment]
番茄工具箱好像有这个功能。你可以在群里或者链滴上问问

**Comment by 88250** [comment]
https://ld246.com/article/1731923283560
