### ISSUE TITLE
希望添加直接拍照导入图片的功能

### ISSUE THREAD

**Issue by 7zq12lvm-b** [siyuan-note/siyuan#13176]
### In what scenarios do you need this feature?

思源android版，添加图片不太方便，需要先拍照，再从本地导入图片

### Describe the optimal solution

是否能直接添加一个调用相机的按钮，导入图片时直接拍照，也不必在相册还留有一个文件。

**Comment by luo-chuan** [comment]
安卓平板端还没有拍照功能。
win平板（比如surface）也还没有拍照功能。
