### ISSUE TITLE
Cannot reset UI, Unable to `Zoom IN` 

### ISSUE THREAD

**Issue by Saugatkafley** [siyuan-note/siyuan#13173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When zoom out `Ctrl -`. The layour shrinks. But I am unable to restore it by simply zooming in `Ctrl +`. As a result UI is really small and I simply cannot `undo` this . 

### Expected result

Should be able to zoom in/out of the layout. Or reset the layout.

### Screenshot or screen recording presentation

The UI is just small cant read properly and cannot find a reset option.
![siyuan_bug](https://github.com/user-attachments/assets/240ada0e-2ef7-4fc7-948e-564575a57dae)

### Version environment

```markdown
- Version:  v3.1.11
- Operating System: Ubuntu 22.04
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/user-attachments/files/17789127/system-log.zip)

**Comment by 88250** [comment]
* Ctrl+= to Zoom out
* Ctrl+0 to Reset

**Comment by Saugatkafley** [comment]
Thanks worked ! :+1:
