### ISSUE TITLE
思维导图功能无法删除节点，建议增加右键菜单

### ISSUE THREAD

**Issue by libertysnt** [siyuan-note/siyuan#13177]
### In what scenarios do you need this feature?

思维导图中按delete无法删除节点，希望可以在思维导图中增加右键菜单

### Describe the optimal solution

思维导图模块通过键盘删除、展开、收缩思维导图的节点，增加自动排序功能

**Comment by TCOTC** [comment]
这个吗，直接选中文本编辑就行了：

![image](https://github.com/user-attachments/assets/d111b4c6-4efd-4a2f-8406-183df6e0f8cc)

**Comment by libertysnt** [comment]
![iShot_2024-11-19_13 48 24](https://github.com/user-attachments/assets/d5ae4666-1950-4756-8d9e-9fd7a4e087ec)
最新版本的思维导图不是这样的嘛？

**Comment by TCOTC** [comment]
你应该去对应的插件仓库反馈问题，这里是思源的仓库
