### ISSUE TITLE
粘贴代码时代入最近语言

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1317]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

粘贴大量代码时，需要每次手动写lang，往往粘贴的代码，在一段时间内，都是一样的lang。
### 描述最优的解决方案 Describe the optimal solution
![image](https://user-images.githubusercontent.com/69628966/106078440-5ff27280-614e-11eb-9cd3-0a54811f1769.png)

![image](https://user-images.githubusercontent.com/69628966/106078315-2a4d8980-614e-11eb-99c3-a4952001f5ff.png)
ps：左键打开，不是右键，写错了。。

**Comment by 88250** [comment]
你好，使用 ` ``` ` 触发时会自动默认最近一次使用的语言。

**Comment by yeshaopeng6688** [comment]
> 你好，使用 `` ``` `` 触发时会自动默认最近一次使用的语言。

。。我是直接复制idea的代码到思源中，因为会自动加`````，所以才提的这个改进。
那么，能否**将代码复制到思源的时候，也会自动触发 最近一次使用的语言**呢？

**Comment by 88250** [comment]
@yeshaopeng6688 收到，我们考虑下，谢谢。
