### ISSUE TITLE
Improve kernel API `/api/block/getBlockKramdown`

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13183]
/api/block/getBlockKramdown 支持导出 span 元素样式

### In what scenarios do you need this feature?

通过块引实现脚注，想通过导出kramdown，将块引锚文本变为脚注编号

![PixPin_2024-11-18_19-43-35](https://github.com/user-attachments/assets/95abd7b0-5c6f-4406-aa86-ce9cce7d56b6)

发现，目前/api/block/getBlockKramdown获得的data和导出模板得到的data并不一致
/api/block/getBlockKramdown 
![PixPin_2024-11-18_19-39-06](https://github.com/user-attachments/assets/4525dffc-133f-4133-aa9f-4db2e84aa5ed)
```
'事<sup>((20241118190659-8v4a45p "注"))</sup>{: style="--memo: 1"}实上<sup>((20241118190702-rywdn7p "注"))</sup>{: style="--memo: 1"}\n{: id="20241118180021-1hva1qs" updated="20241118190702"}'
```
导出模板
![PixPin_2024-11-18_19-39-28](https://github.com/user-attachments/assets/bc6d74ea-9772-41e1-a3e0-b1b7bebb2b66)
```
事<span data-type="block-ref sup" data-subtype="s" data-id="20241118190659-8v4a45p">注</span>{: style="--memo: 1"}实上<span data-type="block-ref sup" data-subtype="s" data-id="20241118190702-rywdn7p">注</span>{: style="--memo: 1"}
{: id="20241118180021-1hva1qs"}
```

如果/api/block/getBlockKramdown得到的内容，使用/api/block/updateBlock来更新块，块引样式就会消失
![PixPin_2024-11-18_19-41-26](https://github.com/user-attachments/assets/f3d89cf8-58bb-488e-b148-799b91e455b5)
```markdown
let data = {
  "dataType": "markdown",
  "data": res.data.kramdown,
  "id": "20241118180021-1hva1qs"
}

await fetchSyncPost('/api/block/updateBlock', data);

```
而使用模板导出的kramdown则不会

### Describe the optimal solution

/api/block/getBlockKramdown 支持导出span元素样式

### Describe the candidate solution

可以直接获取文档的DOM

**Comment by Achuan-2** [comment]
发现如果是静态锚文本的块引粘贴就有问题，动态锚文本的块引就没问题
```markdown
静态锚文本<sup>((20241119112943-2u0qmkw "20241119 11:29:43"))</sup>
动态锚文本<sup>((20241119112943-2u0qmkw '20241119 11:29:43'))</sup>

```
![PixPin_2024-11-19_11-56-00](https://github.com/user-attachments/assets/0385804b-94a1-4e6e-b000-eb25f90c980b)

**Comment by 88250** [comment]
增加一个参数 `mode`：

* `md`：Markdown 标记符模式，使用标记符导出（默认）
* `textmark`：文本标记模式，使用 span 标签导出
