### ISSUE TITLE
同步完成后，更新一下已打开页签的标题

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#13189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

有A、B两台电脑，都打开了同一个文档。
1. A电脑修改了该文档的标题。
2. 打开B电脑上的思源笔记，同步后，B电脑上的该文档的内部标题修改了，但页签标题没有修改。

### Expected result

望修复

### Version environment

```markdown
- Version: v3.1.11
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
我这里无法重现该问题，重命名文档后同步另一端会自动重现加载新名称页签。

建议看下是不是同步时改文档有改动。

**Comment by pisceswb** [comment]
我这边会出现这种情况，webdav同步 @88250 
![image](https://github.com/user-attachments/assets/b5a6c861-f9bd-42bd-a94e-44afbae1e200)

**Comment by TCOTC** [comment]
我没开同步也偶尔出这个问题，不知道怎么复现
