### ISSUE TITLE
Support HarmonyOS NEXT system

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13184]
支持鸿蒙系统 https://github.com/siyuan-note/siyuan-harmony

golang 不支持直接编译鸿蒙支持的共享库：

* https://github.com/golang/go/issues/54805
* https://github.com/golang/go/issues/13492

解决方案：

https://github.com/harmony-contrib/log-adaptor

---

旧方案：

但可以通过修改 go 源码来绕过该问题，参考 @richerfu 大佬的文章 https://juejin.cn/post/7400961014051897379 

![image](https://github.com/user-attachments/assets/56298c28-fa35-4757-bdaa-96196a2726d7)

**Comment by hyperiris** [comment]
这个方案看起来是因为没有引入cgo，所以没有牵扯到musl，所以不会有问题。但是在复杂的业务场景里，出现了cgo、gomobile可能会不太行

**Comment by richerfu** [comment]
> 这个方案看起来是因为没有引入cgo，所以没有牵扯到musl，所以不会有问题。但是在复杂的业务场景里，出现了cgo、gomobile可能会不太行

完全正确，事实上更加完善的适配可以参考：https://gitee.com/wefuture/golang_go/tree/feature%2Ftlsgd_mode_support/ 

由社区大佬提供，本人对于 GO 研究不多仅限于浅薄的适配～

**Comment by 88250** [comment]
@hyperiris @richerfu 目前已经可以拉起内核，模拟器和云调试都可以跑了 🙏

**Comment by aspirantioner** [comment]
@88250 老哥可以交流下解决方案吗，我目前也在尝试鸿蒙中引入go

**Comment by 88250** [comment]
@aspirantioner 请参考 issue 正文中的文章

**Comment by ruin1990** [comment]
log这部分可以参考HarmonyOS的例程：
需要配置下环境变量，保证有配置到OpenHarmony的SDK

我给一份我自己Windows上交叉编译用的脚本
```bat
@echo off
rem 一般来说只需要修改OHSDK的路径就行了，也就是OHOS SDK的路径
set OHSDK=F:\OpenHarmony\Sdk\12
set HDC=hdc
set OH_BUILD_TOOL=%OHSDK%\native\build-tools
set OH_BUILD=%OHSDK%\native\build
set CMAKE=%OH_BUILD_TOOL%\cmake
set CMAKE_BIN=%CMAKE%\bin\cmake.exe
set CMAKEGUI_BIN=%CMAKE%\bin\cmake-gui.exe
set NINJA_BIN=%CMAKE%\bin\ninja.exe 
set TOOLCHAIN_CFG=%OH_BUILD%\cmake\ohos.toolchain.cmake 
set PATH=%CMAKE%\bin;%PATH%

:menu
rem cls
echo ==============================
echo        请选择一个任务
echo ==============================
echo 1. 执行预构建
echo 2. 执行编译
echo 3. 退出
echo ==============================
set /p choice=请输入选项(1-5):

if "%choice%"=="1" goto task1
if "%choice%"=="2" goto task2
if "%choice%"=="3" goto exit

echo 请输入有效的选项(1-5)!
pause
goto menu

:task1
echo 正在执行预构建...
rem rmdir /s out
echo deleting out
rmdir /s /q out
rem arm64
rem %CMAKE_BIN% -G Ninja -B out -DCMAKE_TOOLCHAIN_FILE=%TOOLCHAIN_CFG% -DCMAKE_MAKE_PROGRAM=%NINJA_BIN% -DCMAKE_BUILD_WITH_INSTALL_RPATH=true -DCMAKE_BUILD_TARGET=Shared
rem arm32
%CMAKE_BIN% -G Ninja -B out -DCMAKE_TOOLCHAIN_FILE=%TOOLCHAIN_CFG% -DCMAKE_MAKE_PROGRAM=%NINJA_BIN% -DCMAKE_BUILD_WITH_INSTALL_RPATH=true -DCMAKE_BUILD_TARGET=Shared -DOHOS_ARCH=armeabi-v7a
pause
goto menu

:task2
echo 正在执行编译...
%CMAKE_BIN% --build out
pause
goto menu

:exit
echo 退出程序.
pause

```
CMakeList.txt增加
```
find_library(
    # Sets the name of the path variable.
    hilog-lib
    # Specifies the name of the NDK library that
    # you want CMake to locate.
    hilog_ndk.z
)
target_link_libraries(${target_name} PUBLIC ${hilog-lib})
```

下面我给一段codelab里参考的头文件，实际调用和printf一样，应该能改成cgo的写法
```cpp
#ifndef LOG_COMMON_H
#define LOG_COMMON_H
#include <hilog/log.h>
#define LOG_PRINT_DOMAIN 0xFF00
#define APP_LOG_DOMAIN 0x0001

#define APP_LOG_TAG "drawing"

#define DRAWING_LOGI(...) ((void)OH_LOG_Print(LOG_APP, LOG_INFO, LOG_DOMAIN, APP_LOG_TAG, __VA_ARGS__))
#define DRAWING_LOGD(...) ((void)OH_LOG_Print(LOG_APP, LOG_DEBUG, LOG_DOMAIN, APP_LOG_TAG, __VA_ARGS__))
#define DRAWING_LOGW(...) ((void)OH_LOG_Print(LOG_APP, LOG_WARN, LOG_DOMAIN, APP_LOG_TAG, __VA_ARGS__))
#define DRAWING_LOGE(...) ((void)OH_LOG_Print(LOG_APP, LOG_ERROR, LOG_DOMAIN, APP_LOG_TAG, __VA_ARGS__))

#endif // LOG_COMMON_H
```
另外这个仓库 https://github.com/siyuan-note/siyuan-harmony，我好像无法访问

**Comment by hyperiris** [comment]
> > 这个方案看起来是因为没有引入cgo，所以没有牵扯到musl，所以不会有问题。但是在复杂的业务场景里，出现了cgo、gomobile可能会不太行
> 
> 完全正确，事实上更加完善的适配可以参考：https://gitee.com/wefuture/golang_go/tree/feature%2Ftlsgd_mode_support/
> 
> 由社区大佬提供，本人对于 GO 研究不多仅限于浅薄的适配～

我这几天使用这个大佬修改过的go编译器编译了我们产品中的go模块，中间历经坎坷不一一言表，现在的结果是：
鸿蒙 NEXT 手机端可以dlopen，没有进一步功能测试
鸿蒙 NEXT PC端dlopen失败，详细可以看 https://gitee.com/wefuture/golang_go/issues/IB6W4R

**Comment by afocus** [comment]
https://github.com/golang/go/issues/71953 貌似在解决该问题

**Comment by LucisXu** [comment]
@88250 @hyperiris @richerfu 大佬，小弟有一处不理解，求指导一下🙏：
当前项目里用到的go-sqlite是有用到cgo才对，也就是依然会涉及到musl。那么为什么使用了[log-adaptor](https://github.com/harmony-contrib/log-adaptor) 进行了替代就可正常编译并拉起内核了，而没有把go-sqlite替换掉呢？

**Comment by LucisXu** [comment]
> > [@88250](https://github.com/88250) [@hyperiris](https://github.com/hyperiris) [@richerfu](https://github.com/richerfu) 大佬，小弟有一处不理解，求指导一下🙏： 当前项目里用到的go-sqlite是有用到cgo才对，也就是依然会涉及到musl。那么为什么使用了[log-adaptor](https://github.com/harmony-contrib/log-adaptor) 进行了替代就可正常编译并拉起内核了，而没有把go-sqlite替换掉呢？
> 
> 该解决方案本质上是使用的安卓编译模式，而非musl。所以不会有这个问题，log-adaptor 只是修改了代码中会使用安卓NDK 的log能力替换成鸿蒙的实现。所以并不需要改go-sqlite.

感谢大佬，我还有一处疑惑🙏：

我看了下当前的[harmony](https://github.com/siyuan-note/siyuan/tree/master/kernel/harmony)
/build.sh，确实是使用的安卓编译模式，但是当在鸿蒙系统运行时，系统提供给cgo的c标准库是否还是musl呢，或者可能鸿蒙做了Bionic c的兼容？

**Comment by 88250** [comment]
这个我不太懂...



---Original---
From: ***@***.***&gt;
Date: Tue, May 20, 2025 17:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support HarmonyOS NEXT system (Issue #13184)


 LucisXu left a comment (siyuan-note/siyuan#13184)
   
@88250 @hyperiris @richerfu 大佬，小弟有一处不理解，求指导一下🙏： 当前项目里用到的go-sqlite是有用到cgo才对，也就是依然会涉及到musl。那么为什么使用了log-adaptor 进行了替代就可正常编译并拉起内核了，而没有把go-sqlite替换掉呢？
  
该解决方案本质上是使用的安卓编译模式，而非musl。所以不会有这个问题，log-adaptor 只是修改了代码中会使用安卓NDK 的log能力替换成鸿蒙的实现。所以并不需要改go-sqlite.
  
感谢大佬，我还有一处疑惑🙏：
 
我看了下当前的harmony
 /build.sh，确实是使用的安卓编译模式，但是当在鸿蒙系统运行时，系统提供给cgo的c标准库是否还是musl呢，或者可能鸿蒙做了Bionic c的兼容？

**Comment by richerfu** [comment]
> > > [@88250](https://github.com/88250) [@hyperiris](https://github.com/hyperiris) [@richerfu](https://github.com/richerfu) 大佬，小弟有一处不理解，求指导一下🙏： 当前项目里用到的go-sqlite是有用到cgo才对，也就是依然会涉及到musl。那么为什么使用了[log-adaptor](https://github.com/harmony-contrib/log-adaptor) 进行了替代就可正常编译并拉起内核了，而没有把go-sqlite替换掉呢？
> > 
> > 
> > 该解决方案本质上是使用的安卓编译模式，而非musl。所以不会有这个问题，log-adaptor 只是修改了代码中会使用安卓NDK 的log能力替换成鸿蒙的实现。所以并不需要改go-sqlite.
> 
> 感谢大佬，我还有一处疑惑🙏：
> 
> 我看了下当前的[harmony](https://github.com/siyuan-note/siyuan/tree/master/kernel/harmony) /build.sh，确实是使用的安卓编译模式，但是当在鸿蒙系统运行时，系统提供给cgo的c标准库是否还是musl呢，或者可能鸿蒙做了Bionic c的兼容？

musl的标准库，鸿蒙不会兼容Bionic c。因此这里能跑通不意味着没问题，你要想完全没问题。请参考 https://gitcode.com/openharmony-sig/ohos_golang_go/pull/15 这个也是官方向go提PR的内容。

**Comment by mhlywxl** [comment]
请问下这个最终用的是哪种方案,用的https://github.com/harmony-contrib/log-adaptor的吗 @88250

**Comment by 88250** [comment]
嗯，目前是该方案。



---Original---
From: "wu ***@***.***&gt;
Date: Mon, Jun 16, 2025 11:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support HarmonyOS NEXT system (Issue #13184)


mhlywxl left a comment (siyuan-note/siyuan#13184)
 
请问下这个最终用的是哪种方案,用的https://github.com/harmony-contrib/log-adaptor的吗 @88250

**Comment by mhlywxl** [comment]
大佬，我在ubuntu20.04下安装了go 1.24版本后，执行build.sh，报：
```
runtime/cgo
net
# github.com/mattn/go-sqlite3
sqlite3-binding.c:237010:16: warning: initializing 'unsigned char *' with an expression of type 'char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
github.com/mattn/go-sqlite3
# net
/usr/local/go/src/net/cgo_resold.go:20:76: cannot use _Ctype_size_t(len(b)) (value of uint64 type _Ctype_size_t) as _Ctype_socklen_t value in argument to (_C2func_getnameinfo)
```

在macos m芯片下也会报：
`xxxxxxx/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.darwin-arm64/src/net/cgo_resold.go:20:76: cannot use _Ctype_size_t(len(b)) (value of uint64 type _Ctype_size_t) as _Ctype_socklen_t value in argument to (_C2func_getnameinfo)`


有遇到过吗 @88250

**Comment by 88250** [comment]
sqlite3 那个不用管，只是个警告；后面这个 cgo_resold 要改 golang 源码，可参考同目录下的 cgo_resnew.go 改一下。

**Comment by ljy22338** [comment]
大佬好，我能启动siyuan-harmony，但是初始化的时候会cppcrash闪退。
除了添加必要的 so文件 资源文件 没有做更多修改
能否指点一下小弟如何排查问题。

```
Process name:org.b3log.siyuan.ho
Process life time:7s
Reason:Signal:SIGSEGV(SEGV_MAPERR)@0xff825a065faa0009 
Fault thread info:
Tid:31600, Name:OS_TaskWorker
#00 pc 000000000003ee50 /system/lib64/platformsdk/libace_napi.z.so(panda::JSValueRef ArkNativeFunctionCallBack<true>(panda::JsiRuntimeCallInfo*)+432)(6c1a8d774d3ae619f3694983d88e25d3)
#01 pc 0000000000446d6c /system/lib64/module/arkcompiler/stub.an(RTStub_PushCallRangeAndDispatchNative+140)
#02 at kernelInitWorker (entry/src/main/ets/pages/Main.ets:23:8)
#03 pc 00000000003a6d90 /system/lib64/platformsdk/libark_jsruntime.so(panda::ecmascript::InterpreterAssembly::Execute(panda::ecmascript::EcmaRuntimeCallInfo*)+216)(3aad567d00fac9535fda40922d18ea9e)
#04 pc 00000000005ae2bc /system/lib64/platformsdk/libark_jsruntime.so(panda::FunctionRef::CallForNapi(panda::ecmascript::EcmaVM const*, panda::JSValueRef*, panda::JSValueRef* const*, int)+324)(3aad567d00fac9535fda40922d18ea9e)
``` 
@richerfu @88250 @hyperiris

**Comment by 88250** [comment]
@ljy22338 抱歉，我没有遇到过这个问题，你可以确认下是不是编译环境的问题，比如 sdk 版本（我这里 HarmonyOS 6.0.0 Release SDK, inclusion of OpenHarmony SDK Ohos_sdk_public 6.0.0.47 (API Version 20 Release) as is.）。
