### ISSUE TITLE
选中表格所在的列表项后按tab无法缩进

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#13188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

选中表格所在的列表项后按tab无法缩进
![PixPin_2024-11-19_07-46-07](https://github.com/user-attachments/assets/040c1d35-394c-445f-9305-5bf03a73b837)

实际行为是跳到下一个表格单元

### Expected result

缩进为子级列表项

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

`

**Comment by TCOTC** [comment]
光标在表格内 && 选中了表格父级列表项 时 无法缩进：

[video.webm](https://github.com/user-attachments/assets/f87b33a0-42c9-44c4-91cc-fda57659fa63)

**Comment by Vanessa219** [comment]
在表格内按 esc 选中表格就可以了

**Comment by TCOTC** [comment]
还是这个光标的问题，真的没必要留着光标：#13027

**Comment by iamqiz** [comment]
@Vanessa219 我选中整个表格所在的列表项,就是为了缩进该列表项,这是没有任何歧义的,如果我想编辑表格,那我可以选择整个表格而不是选择表格所在整个列表项,
如果按现在的逻辑(选中表格,按tab能缩进表格所在的列表项),那么就会出现不一致的问题,比如下面的例子
如果我选中11所在的段落块,能缩进其所在的列表项(记作a,也即表格和22/33所在的容器)
那么如果我选中22和33所在的整个列表(下图可见光标位于33行),按理说应该也能缩进上述列表项a, 但是呢实际行为是缩进了33所在的列表项,
而如果我光标位于22行,然后选中22和33所在的整个列表,按下tab却没有任何缩进,这又不符合前面的逻辑(选中表格按tab缩进表格所在列表项)

所以我觉得esc选中块然后按tab的整个逻辑很混乱,我感觉选中不选中有时没啥差别;


![PixPin_2024-11-19_19-47-55](https://github.com/user-attachments/assets/30bd7f07-bbdf-40f3-844f-0b93ffd81d2a)

**Comment by iamqiz** [comment]
我简化一下, 1选中块之后不要去考虑光标了(不要考虑光标的位置了)
2 选中啥就缩进啥,不要去缩进选中项的父块

**Comment by iamqiz** [comment]
@Vanessa219 当然了,我希望V姐搞个投票,听听大家的意见,

**Comment by Vanessa219** [comment]
用 Esc 选中 shift 更快捷方便。

**Comment by iamqiz** [comment]
> 用 Esc 选中后， shift 更快捷方便。

????? shift不也是用来选中的嘛? 现在讨论的是选中后tab的操作

**Comment by Vanessa219** [comment]
打漏了
用 Esc 选中后， shift+tab/tab 更快捷方便。

**Comment by iamqiz** [comment]
@Vanessa219 选中后按tab,在哪些情况下会缩进父项,在哪些情况下会缩进光标下的块? 在哪些情况下啥也不做? 能详细说一下吗? 现在的逻辑很混乱

**Comment by Vanessa219** [comment]
是逻辑上哪里有冲突导致了混乱么，可以具体说说。

**Comment by iamqiz** [comment]
@Vanessa219 我说了啊,你怎么就不看看我上面写的?

**Comment by TCOTC** [comment]
这个逻辑确实很抽象

[video.webm](https://github.com/user-attachments/assets/be287ceb-a628-49c3-be0f-90fab4b21824)

**Comment by iamqiz** [comment]
选中代码块时按tab,是缩进代码块中光标所在行, 而不是缩进整个代码块
所以,到底什么情况下选中块会缩进被选中的块? 什么情况下缩进光标所在行的内容? 
能不能统一 一下逻辑?
@Vanessa219

**Comment by Vanessa219** [comment]
你具体举例出来就很清晰了，这样把代码块的逻辑统一为表格的就行了。还有其它的有冲突么？

**Comment by iamqiz** [comment]
@Vanessa219 我早就说了,为什么你就不看呢? https://github.com/siyuan-note/siyuan/issues/13188#issuecomment-2485536874

**Comment by iamqiz** [comment]
@Vanessa219 你作为思源前端开发者,难道不比我更懂选中块之后按tab的逻辑? 既然这个issue不被你认为是bug,那么就是有意设计的,既然是有意设计的,那么肯定你比我更了解各种块在选中之后按tab的处理逻辑, 有没有冲突,不应该是你比我们更了解吗?
所以我才问你 在什么情况下,选中块之后按tab会缩进选中的块, 什么情况下会缩进光标所在的内容, 什么情况下什么也不做,
但是你既不回答,也不看我之前的详细举例, 所以你在干什么?

**Comment by TCOTC** [comment]
不急，没回复的话就是还没空看。

我想了一个新的方案：#13027

**Comment by Vanessa219** [comment]
非常抱歉我的回答没有让你满意，如果没有其他问题的话，接下来将按照 https://github.com/siyuan-note/siyuan/issues/13027 进行改进。
