### ISSUE TITLE
docker compose health check

### ISSUE THREAD

**Issue by tbfpartner** [siyuan-note/siyuan#13182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

couldnt really search, as most issues are chinese :(

### Expected result

i would like to add a health check to the compose file. 

trying the command directly in the container reveals following:

`wget -nv -t1 --spider localhost:6806
Connecting to localhost:6806 (127.0.0.1:6806)
wget: server returned error: HTTP/1.1 401 Unauthorized`

### Version environment

```markdown
b3log/siyuan:3.1.7
```

### Log file

no log file possible

**Comment by 88250** [comment]
Please use POST /api/system/currentTime
