### ISSUE TITLE
希望思源官方或者可以插件支持一些主流的书籍格式的阅读

### ISSUE THREAD

**Issue by uuuuuuuuuup** [siyuan-note/siyuan#13180]
### In what scenarios do you need this feature?

目前主流的一些阅读软件是支持记录想法或者笔记的，如：微信读书、蜗牛读书...，但这些数据只能在 app 里面进行浏览，对于笔记重度使用者来说，相当于数据存在了两个位置，有很大的阅读复习难度。

### Describe the optimal solution

目前主流的一些阅读软件是支持记录想法或者笔记的，如：微信读书、蜗牛读书...，但这些数据只能在 app 里面进行浏览，对于笔记重度使用者来说，相当于数据存在了两个位置，有很大的阅读复习难度。

### Describe the candidate solution

目前主流的一些阅读软件是支持记录想法或者笔记的，如：微信读书、蜗牛读书...，但这些数据只能在 app 里面进行浏览，对于笔记重度使用者来说，相当于数据存在了两个位置，有很大的阅读复习难度。

**Comment by 88250** [comment]
得等社区看看是否有人做相关插件了，感谢提议。

**Comment by uuuuuuuuuup** [comment]
> 得等社区看看是否有人做相关插件了，感谢提议。得等社区看看是否有人做相关插件了，感谢提议。得等社区看看是否有人做相关插件了，感谢提议。

好滴
