### ISSUE TITLE
拖拽标题/列表项到文档树、拖拽文档到编辑器中，需要显著提示用户接下来的操作

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13181]
我认为比较合适的方法是在鼠标右下角显示一个跟随鼠标的提示框：

![image](https://github.com/user-attachments/assets/4e81bf04-038f-4c89-bc26-6919410bc7e4)

比如：

- 拖拽标题或列表项到文档树：“转换为文档”
- 拖拽文档到编辑器中：“移动到此处”

还有别的操作同理：

- 按住 Alt 拖拽文档到编辑器：“生成块引用”

**Comment by Vanessa219** [comment]
用户的操作和行为都比较明显且唯一，就不进行添加了。

**Comment by TCOTC** [comment]
这个真的不明显，除了思源，哪个笔记软件把文档拖到编辑器里是直接把内容移动过来的

**Comment by Vanessa219** [comment]
那和 alt 拖拽交换一下？alt拖拽才为拖拽文档内容

**Comment by TCOTC** [comment]
交换的话我是支持的，但用户还是不知道接下来的操作会是什么，这个问题没有解决

**Comment by Vanessa219** [comment]
其他家没有这种提示，用户也知道的。还是说有哪家有这种提示？

**Comment by TCOTC** [comment]
其他家应该是没有将内容拖到编辑器里（而且还不能直接撤销）的这种操作的，思源需要一个单独的交互方式。

我的想法就是在鼠标旁边显示一个悬浮提示，感觉很符合直觉。

**Comment by Vanessa219** [comment]
这样修改后就不是内容了。

> 那和 alt 拖拽交换一下？alt拖拽才为拖拽文档内容

**Comment by TCOTC** [comment]
感觉还是不对。比如这个：

> 拖拽标题或列表项到文档树：“转换为文档”

如果没有提示的话，用户只有试过一次才知道会怎么样

**Comment by Vanessa219** [comment]
其他软件也是这样的，有帮助文档嘛。

**Comment by TCOTC** [comment]
> 那和 alt 拖拽交换一下？alt拖拽才为拖拽文档内容

那还是先改一下这个吧，感觉用户的直觉就是拖入文档块引用

![Screenshot_2024-11-28-09-49-23-93_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/user-attachments/assets/4f404bdc-77a6-432e-8544-e3751224565f)

**Comment by TCOTC** [comment]
@Vanessa219 有点问题，现在要按住 Alt 才能把文档拖到数据库里了

**Comment by TCOTC** [comment]
@Vanessa219 还是拖不进去：

[video.webm](https://github.com/user-attachments/assets/5d95ac68-3f44-4016-ae57-cf71d51832f0)
