### ISSUE TITLE
在英语界面下关系图的字不会跟随字体设置 The font within the graphs does not use the appropriate font when the display language is set to English

### ISSUE THREAD

**Issue by quiniapiezoelectricity** [siyuan-note/siyuan#13187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

把显示语言设置为英语（或其他非汉字语言）后，关系图的字体直接变了新细明体/times new roman： 如下图
在显示语言为中文（不论繁简）的时候则没有这个问题 （日语也是正常的）

### Expected result

关系图的字体应不分显示语言跟随思源里的字体

### Screenshot or screen recording presentation

英文为显示语言时（bug)：
<img width="325" alt="image" src="https://github.com/user-attachments/assets/2a93f817-1e80-400d-b589-6f31cc062b1b">

中文为显示语言时（正常）：
<img width="316" alt="image" src="https://github.com/user-attachments/assets/4e55cb0a-16d0-4af7-8b0e-3a284b4b5a96">

### Version environment

```markdown
- Version: v3.1.11
- Operating System: MacOS
- Browser (if used):
```

### Log file

n/a

**Comment by 88250** [comment]
我这里正常，建议检查一下是不是插件、代码片段等设置问题。

**Comment by quiniapiezoelectricity** [comment]
@88250 我再试了一试 应该是在OS语言也是英文的情况下才会产生这个bug 你可以试试能不能复现这个问题吗
我测试的结果如下：
MacOS(英文) -> 思源(英文) -> bug
MacOS(英文) -> 思源(简体中文) -> 正常
MacOS(简体中文) -> 思源(英文) -> 正常
MacOS(简体中文) -> 思源(简体中文) -> 正常
我在ios跟docker环境里测试的结果也相同

**Comment by 88250** [comment]
那估计是系统语言优先了，思源本身不带雅黑字体的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月19日(周二) 晚上10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 在英语界面下关系图的字不会跟随字体设置 The font within the graphs does not use the appropriate font when the display language is set to English (Issue #13187)




 
@88250 我再试了一试 应该是在OS语言也是英文的情况下才会产生这个bug 你可以试试能不能复现这个问题吗
 我测试的结果如下：
 MacOS(英文) -&gt; 思源(英文) -&gt; bug
 MacOS(英文) -&gt; 思源(简体中文) -&gt; 正常
 MacOS(简体中文) -&gt; 思源(英文) -&gt; 正常
 MacOS(简体中文) -&gt; 思源(简体中文) -&gt; 正常
 我在ios跟docker环境里测试的结果也相同

**Comment by quiniapiezoelectricity** [comment]
@88250 我不是很理解 所以意思就是说关系图里的字体是跟随系统字体而不是思源里设定的字体的意思吗？ 还有这个issue应该可以重开一下吧 感谢🙏

**Comment by TCOTC** [comment]
> 思源里设定的字体

你用的是哪个字体？

**Comment by quiniapiezoelectricity** [comment]
我选的是预设的字体 但是其实我无论选哪个都是在关系图里被无视 而关系图里甚至不是用思源本身UI的字体

**Comment by TCOTC** [comment]
你的意思是无论这里选择什么字体，关系图里的字体都不会变吗？

![image](https://github.com/user-attachments/assets/fec38945-6748-49f0-ac6d-bd7ea1e963ea)

**Comment by quiniapiezoelectricity** [comment]
这个是没错 关系图里的字体不跟随那个选项（毕竟那里写的是编辑器里的字体 所以我也不确定这个是feature 还是 bug）
但是我这个issue的重点是当OS和思源的语言都设为英文的时候 关系图里的字体就会变了一个既不是UI字体也不是设定里的字体的字体

**Comment by TCOTC** [comment]
哦对，那个是编辑器字体，不影响关系图

**Comment by TCOTC** [comment]
> 当OS和思源的语言都设为英文的时候 关系图里的字体就会变了一个既不是UI字体也不是设定里的字体的字体

@Vanessa219 看看

**Comment by TCOTC** [comment]
我知道问题在哪了，这个字体是单独设置的：

![image](https://github.com/user-attachments/assets/08fceaf8-f297-4cfc-aee7-b75a5e3d1af7)

@Vanessa219 为什么默认主题限制用 mononoki ？

**Comment by quiniapiezoelectricity** [comment]
我下载了momonoki 然后那个字体就显示正常了
其实我觉得单独设置momonoki没啥问题 但是就可能应该要附上字体的otf会比较好一点（毕竟总不能假设所有人都有下那个字体）
然后我试了试发现 数据库(Database) -> 表格(Table) -> 设置(Settings) -> 字段(Fields) 也有同样的问题 但是这个就安装了momonoki也解决不了
<img width="226" alt="image" src="https://github.com/user-attachments/assets/3faba3a8-6d8a-4163-b2df-adaab2c2f587">

**Comment by Vanessa219** [comment]
可能是以前要计算宽度，选了个等宽字体吧。我把它改成默认的 arial 吧。
