### ISSUE TITLE
形如“<a>x<b></b></a>”的文本无法正常输入

### ISSUE THREAD

**Issue by hihaojie** [siyuan-note/siyuan#13191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

输入形如“`<a>x<b></b></a>`”的文本时会自动转为“`<a>x</a>`”。在 3.0.17 版没有此问题
![image](https://github.com/user-attachments/assets/f77d6a57-339d-42c2-867f-5b6206ffa2e0)

### Expected result

可以正常键入形如“`<a>x<b></b></a>`”的文本

### Version environment

```markdown
- Version: 3.1.11
- Operating System: Windows10、Windows11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17808476/siyuan.log)

**Comment by 88250** [comment]
`<b>` 标签会被自动转换为加粗。

**Comment by TCOTC** [comment]
建议在行级代码中输入

**Comment by hihaojie** [comment]
> 建议在行级代码中输入

我需要对字符进行高亮等操作，行级代码不是很合适。
这个显示问题我用转义的斜杠解决了

**Comment by TCOTC** [comment]
如果不需要再复制的话确实可以用转义符
