### ISSUE TITLE
功能请求，折叠快捷键，对组合在一起的引述和超级块有效

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#13194]
### In what scenarios do you need this feature?

当前，Ctrl+↑快捷键可以折叠光标所在的单个块。
功能请求:
在多个块合并成的引述或超级块中，使用Ctrl+↑快捷键，能够折叠整个引述或超级块，而不是单个块。

也就是对于组合块，ALT+点击与 Ctrl+↑快捷键，呈现的是不同的效果。一个折叠整个组和块，一个仅折叠一个段落
![image](https://github.com/user-attachments/assets/74b10219-5f66-4992-ae2a-f100f5bf9ede)

### Describe the optimal solution

目的是为了实现，选中多个块后，便捷的将其全部折叠在一起。

**Comment by TCOTC** [comment]
> 能够折叠整个引述或超级块

[video.webm](https://github.com/user-attachments/assets/2fb2188c-3346-412e-afdf-ccbe81036563)

**Comment by pisceswb** [comment]
> > 能够折叠整个引述或超级块
> 
>  video.webm

希望使用Ctrl+↑快捷键也能够实现折叠整个引述或超级块。
这样就能够组一个quicker动作: 
1. 转换成引述或超级块
2. 折叠

**Comment by TCOTC** [comment]
转换完成之后再按 Shift+↑

**Comment by pisceswb** [comment]
> 转换完成之后再按 Shift+↑

转换成引述或超级块后，Ctrl+↑只能折叠一个段落，而不是整个引述或整个超级块

**Comment by TCOTC** [comment]
所以我让你按 Shift+↑

**Comment by pisceswb** [comment]
> 所以我让你按 Shift+↑ ，得选中了对应的引述块或者超级块才能折叠

我这边不行呢
![思源笔记](https://github.com/user-attachments/assets/5bc300c2-c963-4e3e-8ca9-f495cd7bfe2b)

**Comment by TCOTC** [comment]
要多按几次直到选中，我的录屏那样
