### ISSUE TITLE
搜索功能ui重新设计

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1319]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

目前有ctrl+p，以及Alt+f两种方式唤起搜索，功能一致但展现方式不同，体验上也都不够舒适。
前者的缺点是：1. 搜索结果和笔记正文不能同时展现；2. 由于界面设计原因，无法充分利用屏幕；
后者的缺点是：1. 界面左边栏设计有些突兀，尤其是当打开文件树等左侧功能区的时候；2. 必须先选择关键词后唤起搜索，没办法灵活调整搜索关键词；alt+f的优点是可以标签方式展示多个搜索关键词的结果。

### 描述最优的解决方案 Describe the optimal solution
1. 整合现有两种搜索界面成一种，占用一个快捷键，若有选中词语，则直接搜索，否则，展示搜索界面，等待用户输入关键词。
2. 重新设计搜索界面，参考vscode，搜索图标在左侧dock栏，搜索结果类似文件树，以文档块为节点折叠，文件树顶端输入搜索关键词，若点击搜索结果，则打开该文档块。

**Comment by EndlessErrors** [comment]
我是用户，谈谈自己的看法。

其实没必要把所有搜索界面整合成一种，笔记软件的搜索功能是根本性的需求，而且存在不同的搜索情境（下文详述），**与其寻找全能的UI（大概率不存在），不如强化不同界面的优势用以应对不同的搜索情境**，毕竟VSCode也是有两种搜索UI的（侧边栏和Ctrl+P）。

结合我个人使用体验，个人建议**改造Ctrl+P的搜索功能，加入dock搜索栏，取消用Alt+F直接打开搜索页签，多个搜索UI共存**，分别用于不同搜索情境：

* Ctrl+P 的搜索：
  * 主要用来临时性查询某个知识点（如某个数学公式），或者用来一次性地跳转到其它页面，而非用来进行主题性浏览，使用后不会改变软件不同栏目（包括dock栏、页签）的布局，无副作用。
  * 甚至可以把Ctrl+P改造成和VSCode一样的多功能栏，不仅仅可以搜索、跳转，还可以用于输入命令，为一些不算常用的功能、设置以及之后插件的功能调用及设置提供入口（不然这些都只能抢占快捷键或者让右键菜单臃肿）
  * 改进1：适当缩小Ctrl+P搜索栏的大小（可参照VSCode），去除固定的正文预览区域，改为鼠标放到图标上悬浮窗显示正文，可以解决无法充分利用屏幕的问题
  * 改进2：改造成多功能栏
* Dock 搜索栏：
  * 由于是常驻的，可以用于主题性浏览
  * 支持放到左右侧和上下侧，放到左右侧就是如楼主说的类似VSCode的侧边搜索栏，放到上下侧就是现有的Alt+F的功能（搜索栏的左侧是搜索结果，右侧显示正文）
  * 加入一个按钮：由当前的Dock搜索栏创建一个搜索页签，方便灵活布局或者同时进行多个搜索
* 搜索悬浮窗（非必需）
  * 界面设计类似VSCode用`Shift+F12`唤出的引用悬浮窗（见最后的图1），同上下侧Dock搜索栏
  * 它的好处在于它是悬浮窗，不会改变各种栏目（包括dock栏、页签）的布局，并且相比常驻的横向Dock搜索栏可以有更大的纵向显示空间
  * 加入一个按钮：由当前的悬浮窗创建一个搜索页签
* 现在的 Alt+F 的搜索页签：
  * 由于Dock搜索栏和搜索悬浮窗已经取代了它的功能，即使需要把搜索作为页签灵活布局或者同时进行多个搜索，也能用按钮创建，因此可以取消直接用右键菜单或者`Alt+F`快捷键打开搜索页签
    *（从个人经验出发胆大包天地推己及人，可能用户使用中对这两方面的需求不常见，因此搜索页签作为附属功能应该是合理的。而且VSCode也是设计为从按钮创建搜索页签）*
  * 左侧搜索结果能改变宽度、能折叠以给正文让出空间；右侧正文区和正常的文档一致（既非现在的预览，也非子块，而是能正常编辑）

**快捷键**：`Alt+F`、`Shift+Alt+F`、`Shift+Ctrl+F`、`F12`可以分配给除搜索页签外的搜索功能。

还有**需不需要支持划词搜索**，可以参考VSCode（毕竟有长期经验积累），让Ctrl+F和悬浮窗都支持划词搜索，而其它搜索功能即使有选中的关键词也不将其作为搜索关键词。

**更多的思考：**
后续还可以引入另一种搜索页签，能够保存和处理搜索结果，参考有用户为此制作的[Quicker动作：生成原文平铺列表](https://getquicker.net/Sharedaction?code=6520e8f3-3853-451c-94e1-08d89f14c282)。

图1：VSCode用`Shift+F12`唤出的引用悬浮窗![图片](https://user-images.githubusercontent.com/57283205/106195788-9d590d80-61eb-11eb-82d5-8c0fd27fcd6d.png)

**Comment by 88250** [comment]
感谢讨论，后面我们再考虑。
