### ISSUE TITLE
集市包支持指定反馈渠道

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13197]
plugin.json 增加一个字段（支持多个键值对，可以放多个反馈渠道）。

场景：有的仓库是不开放 issue 的，需要单独指定反馈渠道：

![image](https://github.com/user-attachments/assets/bee54768-0c85-446f-b124-66fae49635db)

---

另外这个 `下载` 和 `反馈` 按钮的浮动效果也要改掉。

**Comment by 88250** [comment]
这个不考虑了，反馈渠道统一设置为 issues，如果需要其他反馈方式可以在 README 中说明。
