### ISSUE TITLE
Improve file history UI

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13193]
改进文件历史窗口布局、文件历史支持分页导航

1. 目前切换分页是在右上角，但列表在左边，感觉隔得有点远：

   ![image](https://github.com/user-attachments/assets/161e45a4-5387-4d74-a0c6-0810a38884a6)

2. 不需要 `清理` 和 `删除` ：

   ![image](https://github.com/user-attachments/assets/c2049f65-9a98-4cdf-b36b-a2ae0d70b9d5)

3. 文件历史最好也支持分页导航

**Comment by Temacc0531** [comment]
现在的还会有按钮被遮挡的问题
![1732010136487](https://github.com/user-attachments/assets/66ebc299-f635-4a22-adfa-93ee0d07e95e)

**Comment by TCOTC** [comment]
> 按钮被遮挡

这个看起来好像没有很合适的办法

**Comment by Temacc0531** [comment]
> 按钮被遮挡
> 这个看起来好像没有很合适的办法

如果空间不够，那几个输入/选择框看起来可以缩小一点的样子

**Comment by TCOTC** [comment]
缩小的话就显示不完整了
