### ISSUE TITLE
嵌入块中的数据库无法 `加载更多`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13205]
按钮点了之后会打开浮窗而不是加载更多条目

**Comment by 88250** [comment]
嵌入块不能直接交互的。

**Comment by TCOTC** [comment]
我看这个设计就像是允许 `加载更多` 的：

![image](https://github.com/user-attachments/assets/10f237cc-f022-4361-a4cc-d79f39fe83fd)

不然就直接用 `.av__row--util{display: none;}` 了
