### ISSUE TITLE
导出data的时候会显示已经删除的文章的文件名

### ISSUE THREAD

**Issue by DearZack** [siyuan-note/siyuan#13202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我每过一段时间会备份一下数据，比如我曾经有一个“a.md”，后来我把它删了，且点个“设置-编辑器-历史保留天数-情况所有历史”，但是我在导出的时候，会有一个进度条，会显示正在导出的文件名，我还是可以看到“a.md”，正常吗？

### Expected result

我每过一段时间会备份一下数据，比如我曾经有一个“a.md”，后来我把它删了，且点个“设置-编辑器-历史保留天数-情况所有历史”，但是我在导出的时候，会有一个进度条，会显示正在导出的文件名，我还是可以看到“a.md”，正常吗？

### Version environment

```markdown
- Version: 3.1.11
- Operating System: win11
- Browser (if used):
```

### Log file

毕现

**Comment by 88250** [comment]
可能是和其他文件重名了吧，你看下实际如果没有导出的话就是正常的。
