### ISSUE TITLE
列表项之间缺少间距

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13201]
![image](https://github.com/user-attachments/assets/ce4c7d44-a5f8-4a33-ae1e-788fa41a890d)

**Comment by 88250** [comment]
这个间距还行吧，太大的话就不好看了。

**Comment by TCOTC** [comment]
这个没有间距了啊

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/eb0f74cd-9c69-4326-bf7b-b91a34e7baaa)

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
已修复，不拉进版本了。
