### ISSUE TITLE
Lazy loading of images and IFrames

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#13204]
为 img 和 iframe 添加 `loading="lazy"`

**Comment by TCOTC** [comment]
这个有什么效果呢？

**Comment by 88250** [comment]
在可视区域内再加载，提升性能



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Wed, Nov 27, 2024 23:57 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Lazy loading of images and IFrames (Issue#13204)




 
这个有什么效果呢？
