### ISSUE TITLE
能否通过增加标签来将块或者文档添加到特定的数据库呢？

### ISSUE THREAD

**Issue by Kikkwa** [siyuan-note/siyuan#13215]
### In what scenarios do you need this feature?

我自己使用到这种功能情况下不多，只是刚刚我在给我的题库添加标签的时候意识到了这个功能。

### Describe the optimal solution

同一个块里面的多个不同的标签可以把一个块添加到多个数据库。这样使用起来一定很方便。

**Comment by TCOTC** [comment]
得看谁能参考 [[Quicker] 思源笔记 SuperTag - 链滴](https://ld246.com/article/1731945645865) 做一个插件了
