### ISSUE TITLE
单击文件树中的文档引用计数仅显示浮窗，不打开文档。

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1321]
### 描述问题 Describe the problem
单击文件树中的文档引用计数显示浮窗 同时打开文档。

### 期待的结果 Expected result
单击文件树中的文档引用计数仅显示浮窗，不打开文档。

**Comment by 88250** [comment]
下个版本修复 #1259

**Comment by roverway** [comment]
070的表现：单击文件树中的文档引用计数后，先打开文档，稍后显示浮窗。
这个好像还是不对。

**Comment by 88250** [comment]
@roverway 收到，稍后调整。

**Comment by Vanessa219** [comment]
0.7.1 已修复
