### ISSUE TITLE
关于-数据仓库密钥-话术语病

### ISSUE THREAD

**Issue by hqweay** [siyuan-note/siyuan#13227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![CleanShot 2024-11-22 at 18 54 21@2x](https://github.com/user-attachments/assets/9518c165-342f-4f04-911d-5eb1df8bd897)

### Expected result

/

### Screenshot or screen recording presentation

/

### Version environment

```markdown
/
```

### Log file

/

### More information

/

**Comment by TCOTC** [comment]
我改改

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/80c7068b-5770-4c93-bc70-d5dc8d921302)

**Comment by TCOTC** [comment]
#13229
