### ISSUE TITLE
Pandoc single instance instead of binary in each workspace

### ISSUE THREAD

**Issue by asim215** [siyuan-note/siyuan#13221]
### In what scenarios do you need this feature?

Currently each workspace instance takes about 150 Mb with almost empty user data. I figured out that it supplied each workspace with itself pandoc binary. It is inefficient. I wanted to store my notes in backup, but storing many same pandoc instances useless for space. Where Obsidian takes ~1.2 Mb of data with notes. Each workspace siyuan takes more than 151 Mb of space. I have 5 projects with almost no notes in them and total amount it is 808 Mb of storage!

### Describe the optimal solution

One binary pandoc which supplies with siyuan package not for each existing workspace. Or if possible use system pandoc if it is installed on that system. Or install it if you will use it, because you not always use export.

**Comment by 88250** [comment]
Settings - Export - Path to Pandoc executable

If you manually specify a non-default Pandoc path, the built-in Pandoc will not be initialized.

**Comment by asim215** [comment]
> Settings - Export - Path to Pandoc executable
> 
> If you manually specify a non-default Pandoc path, the built-in Pandoc will not be initialized.

 It doesn't change anything... Even if I specify local pandoc. Create new workspace. It still creates binary inside.
![20241123_19h22m45s_grim](https://github.com/user-attachments/assets/e766964f-276e-45f6-b180-9e8c8ec9fac1)
![20241123_19h23m06s_grim](https://github.com/user-attachments/assets/6b214880-d27b-433f-a2d3-64031f452387)
![20241123_19h23m21s_grim](https://github.com/user-attachments/assets/add97049-7d70-4cf0-9e3a-e356e4897709)

**Comment by 88250** [comment]
After specifying the settings, manually delete the temp/pandoc folder, and pandoc should not be initialized again when you restart SiYuan.

**Comment by asim215** [comment]
> After specifying the settings, manually delete the temp/pandoc folder, and pandoc should not be initialized again when you restart SiYuan.

Yes, it worked. Thanks. Only when I manually change path to pandoc in settings in every workspace instance. It looks like there is no global settings.

**Comment by asim215** [comment]
Can I remove pandoc as essential option? I don't export in docx files. Only in markdown.

**Comment by 88250** [comment]
No plan, thanks.



---Original---
From: "Anton ***@***.***&gt;
Date: Sun, Nov 24, 2024 00:39 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Pandoc single instance instead of binary ineach workspace (Issue #13221)




 
Can I remove pandoc as essential option? I don't export in docx files. Only in markdown.
