### ISSUE TITLE
更换第三方主题后主页面两边边距不一样

### ISSUE THREAD

**Issue by ayue2019** [siyuan-note/siyuan#1322]
### 描述问题 Describe the problem
更换第三方主题后，如果调节了左侧文件树面板的宽度，那么主页面两边的宽度就会不一样

### 期待的结果 Expected result
更换第三方主题，调节文件树面板的宽度后，主页面两侧的留白宽度依然保持一致

### 截屏或录屏演示 Screenshot or screen recording presentation
![image-8b391ca0](https://user-images.githubusercontent.com/58946586/106087419-eadb6900-615e-11eb-9f2b-f5868683d037.png)

### 版本环境 Version environment

* 版本 Version：0.6.8
* 操作系统 Operating system：Windows 10

**Comment by 88250** [comment]
请给该主题仓库提 issue，谢谢。
