### ISSUE TITLE
把表情选择器拉宽之后，表情的行间距会变大

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13236]
![image](https://github.com/user-attachments/assets/9947f902-68b3-4d54-a3f1-9a54ea2f004c)

**Comment by 88250** [comment]
我这里测试正常，你看下是不是其他代码片段影响的。

**Comment by TCOTC** [comment]
拉宽之后截图看看你的“食物和饮料”这一节？

**Comment by 88250** [comment]
下面的确实有点问题：

![image](https://github.com/user-attachments/assets/91337b74-bdfa-401e-9d9f-c91109372d57)

**Comment by Vanessa219** [comment]
不拉进版本了
