### ISSUE TITLE
移除粘贴时折叠标题的折叠状态

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13232]
选中标题的文本复制，预期是复制了 `### 标题`，粘贴时生成一个新的标题块，而新的标题块不应该是折叠的状态。

[video.webm](https://github.com/user-attachments/assets/8d76deda-0735-4f14-8e8f-9152bbf69c9b)

**Comment by TCOTC** [comment]
@Vanessa219 复制的子块粘贴出来是折叠状态：

[video.webm](https://github.com/user-attachments/assets/0f7006cf-93d5-42f6-84bf-d768c199f29b)

**Comment by 88250** [comment]
复制下方块 这个功能就还是保持折叠吧。
