### ISSUE TITLE
`<foo:>` 粘贴到思源中会变成链接

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13231]
```
<foo:>
```

Obsidian 不会：

![image](https://github.com/user-attachments/assets/247731f5-9720-4349-a0f4-32c9f3c46c5f)

**Comment by 88250** [comment]
按照 Markdown 标准这个是应该转换为超链接的：

![image](https://github.com/user-attachments/assets/548fca04-5fef-4b2e-9d78-74af419ee52a)

测试地址：

https://spec.commonmark.org/dingus/

**Comment by TCOTC** [comment]
@88250 我发现在思源里粘贴 `<fo:>` 的话不是链接

![image](https://github.com/user-attachments/assets/97408662-1423-4aa2-b241-805e643f6614)

**Comment by 88250** [comment]
思源 lute 好像改过对 protocol 的判断
