### ISSUE TITLE
自动上传图片到指定图床.

### ISSUE THREAD

**Issue by leolee9086** [siyuan-note/siyuan#1323]
### 你在什么场景下需要该功能？ 

由于我们是一家以网络社区作为宣传途径的室内设计工作室,我们经常会有将图片上传到指定图床(目前我们使用的是腾讯云对象存储)的需求.

目前我们主要是通过用typora重新打开编辑过的文档来达到这个目的,但是终究有一些不太方便.

### 描述最优的解决方案 Describe the optimal solution

目前我们使用的markdown编辑器中,typora通过调用picgo,比较好的实现了这一功能.

也许思源笔记也可以通过调用电脑上安装的picgo 来实现这样的自动上传.

### 描述候选解决方案 Describe the candidate solution

既然思源笔记可以支持通过GITHUB同步笔记内容,应该也可以通过同样的途径实现图片的自动上传.
不过直接调用picgo可能会更容易实现,也能够有更多的选择空间.

**Comment by 88250** [comment]
你好，暂时没有集成图床工具的计划 #641
