### ISSUE TITLE
某种情况下无法多选块

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13237]
```
* 00000000000

  11111111111

  * 22222222222222
  * 33333333333333
  * 44444444444444
```

正常情况下可以多选子块，但如果鼠标一开始点到了块和块之间的那条缝，就不能选中子块了（表现为只能高亮一下子块的文本、只能选中父块）：

[video.webm](https://github.com/user-attachments/assets/9077d262-103a-4d5f-accb-5a5e923d6f3b)

**Comment by Vanessa219** [comment]
已修改，不拉进版本了。
