### ISSUE TITLE
未引用的资源文件支持搜索

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13249]
https://ld246.com/article/1732429960638

- 数量太多而没有列出的也应该能搜索到
- 支持使用多个关键字搜索

**Comment by z2023711** [comment]
> https://ld246.com/article/1732429960638
> 
> 数量太多而没有列出的也应该能搜索到
我想搜索是没有问题的，但是思源“资源”界面的搜索好像并不支持“多关键词”。
想找到并插入合适的图片，但图片的格式并不是只有一种，如果是想通过名字搜索，文件太多的情况下，很难做到记住每个图片的“名称”和图像内容吧，

**Comment by TCOTC** [comment]
@88250 /资源 搜索不能用多个关键字吗

**Comment by TCOTC** [comment]
@88250 是不是把 issue 漏掉了？需要在这里或者别的什么地方加一个搜索框：

![image](https://github.com/user-attachments/assets/4e24c256-15ed-4374-9937-ba0c322df249)

**Comment by 88250** [comment]
只做了 /资源 支持多关键字搜索
