### ISSUE TITLE
Failed to purge data repo: cloud object not found v3.1.13

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#13243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I was trying to purge cloud rata repo of my main vault and found this error showing today. I created a fresh vault and a fresh R2 bucket to test and it is showing the same error.

### Expected result

It should not show an error and purge the cloud snapshots, etc.

### Version environment

```markdown
- Version: v3.1.13
- Operating System: Windows 11
- Browser (if used):
```

### Log file

I 2024/11/23 20:19:19 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/11/23 20:19:19 runtime.go:86: kernel is booting:
    * ver [3.1.13]
    * arch [amd64]
    * os [Microsoft Windows 11 Home Single Language]
    * pid [7804]
    * runtime mode [prod]
    * working directory [C:\Users\<redacted>\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\<redacted>\Vaults\Testing]
I 2024/11/23 20:19:19 conf.go:169: initialized language [en_US] based on device locale
I 2024/11/23 20:19:19 runtime.go:138: use network proxy [system]
I 2024/11/23 20:19:19 serve.go:189: kernel [pid=7804] http server [127.0.0.1:56824] is booting
I 2024/11/23 20:19:19 blocktree.go:75: reinitialized database [C:\Users\<redacted>\Vaults\Testing\temp\blocktree.db]
I 2024/11/23 20:19:19 database.go:92: the database structure is changed, rebuilding database...
I 2024/11/23 20:19:19 database.go:109: reinitialized database [C:\Users\<redacted>\Vaults\Testing\temp\siyuan.db]
I 2024/11/23 20:19:19 conf.go:851: database size [4.1 kB], tree/block count [0/0]
I 2024/11/23 20:19:19 working.go:193: kernel booted
I 2024/11/23 20:19:19 box.go:77: auto stat [trees=0, blocks=0, dataSize=36.87 kB, assetsSize=0 B]
I 2024/11/23 20:19:19 disk.go:33: disk usage [total=511.3 GB, used=73.08 GB, free=438.23 GB]
I 2024/11/23 20:19:22 index.go:220: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.07s], tree [count=67, size=1.31 MB]
I 2024/11/23 20:19:22 index.go:290: resolved refs [36] in [62ms]
I 2024/11/23 20:19:32 pandoc.go:186: initialized built-in pandoc [ver=3.5, bin=C:\Users\<redacted>\Vaults\Testing\temp\pandoc\bin\pandoc.exe]
I 2024/11/23 20:19:32 conf.go:1113: pandoc initialized, set pandoc bin to [C:\Users\<redacted>\Vaults\Testing\temp\pandoc\bin\pandoc.exe]
I 2024/11/23 20:20:19 mount.go:65: created box [20241123202019-3j8yz5d]
I 2024/11/23 20:20:19 index.go:220: rebuilt database for notebook [20241123202019-3j8yz5d] in [0.01s], tree [count=0, size=0 B]
I 2024/11/23 20:20:19 index.go:290: resolved refs [36] in [58ms]
I 2024/11/23 20:21:05 repo.go:649: walk data [files=8] cost [11.4251ms]
I 2024/11/23 20:21:05 ref.go:64: updated local latest to [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=eb3930e21b9f7c74c5ef4fe9d0a35f84fa4fccd4, files=8, size=8.5 kB, created=2024-11-23 20:21:05]
I 2024/11/23 20:22:44 repository.go:1396: syncing data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/true]
I 2024/11/23 20:22:44 repo.go:649: walk data [files=8] cost [9.8134ms]
I 2024/11/23 20:22:44 ref.go:64: updated local latest to [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c, files=8, size=8.7 kB, created=2024-11-23 20:22:44]
W 2024/11/23 20:22:47 sync.go:1546: not found cloud latest
I 2024/11/23 20:22:56 sync.go:239: got local latest [9ebd133b56a351fee841ba34d624abd8e9b1bc0c] files [8]
I 2024/11/23 20:22:56 sync.go:1435: latest sync index not found, return an empty index
I 2024/11/23 20:22:56 sync.go:262: local upsert [0e29461c711a65ad48a0520cd020eca16627204a, /storage/av/20240208172742-57vwxqw.json, 2024-11-19 21:25:48]
I 2024/11/23 20:22:56 sync.go:262: local upsert [4a717bee254be57549924ad78480684c69053bed, /storage/av/20240208173528-oq4elsj.json, 2024-11-19 21:25:48]
I 2024/11/23 20:22:56 sync.go:262: local upsert [0da9f440297eeec099a902cf0442582cd40bc042, /storage/av/blocks.msgpack, 2024-11-23 20:20:19]
I 2024/11/23 20:22:56 sync.go:262: local upsert [19a2dbb864c770c181bdf878ff51c0f83b5702ed, /.siyuan/indexignore, 2024-11-23 20:19:22]
I 2024/11/23 20:22:56 sync.go:262: local upsert [82d199e768fdd8fcfa7dc7c1805ad581227c83cb, /.siyuan/syncignore, 2024-11-23 20:21:05]
I 2024/11/23 20:22:56 sync.go:262: local upsert [d3c297d5d151a5376cc8537afabe7a61e872e2b5, /20241123202019-3j8yz5d/.siyuan/conf.json, 2024-11-23 20:20:19]
I 2024/11/23 20:22:56 sync.go:262: local upsert [213d738ca884a6600af4a03b87887a5f5c75ea43, /20241123202019-3j8yz5d/20241123202021-fh2db9x.sy, 2024-11-23 20:22:32]
I 2024/11/23 20:22:56 sync.go:262: local upsert [5e9b96d29fbaa495f61cd40c918f477f73a8fb75, /storage/av/20240208172719-6qv16cr.json, 2024-11-19 21:25:48]
I 2024/11/23 20:22:57 sync.go:1174: uploaded index [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c, files=8, size=8.7 kB, created=2024-11-23 20:22:44]
I 2024/11/23 20:22:58 sync.go:907: uploaded cloud ref [refs/latest, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c]
I 2024/11/23 20:22:58 ref.go:64: updated local latest to [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c, files=8, size=8.7 kB, created=2024-11-23 20:22:44]
I 2024/11/23 20:22:58 sync.go:1384: updated latest sync [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c, files=8, size=8.7 kB, created=2024-11-23 20:22:44]
I 2024/11/23 20:22:59 repository.go:1468: synced data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/true, ufc=11, dfc=2, ucc=7, dcc=0, ub=5.52 kB, db=0 B] in [14.52s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/11/23 20:22:59 index_fix.go:50: start checking index...
I 2024/11/23 20:22:59 index_fix.go:70: finish checking index
I 2024/11/23 20:22:59 repository.go:161: no index to purge [ellapsed=0.00s]
I 2024/11/23 20:23:04 repository.go:1396: syncing data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/true]
I 2024/11/23 20:23:04 repo.go:649: walk data [files=8] cost [8.2009ms]
I 2024/11/23 20:23:07 sync.go:1585: got cloud latest [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c, files=8, size=8.7 kB, created=2024-11-23 20:22:44]
I 2024/11/23 20:23:07 repository.go:1468: synced data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/true, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=646 B] in [3.58s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/11/23 20:23:08 repository.go:1396: syncing data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/false]
I 2024/11/23 20:23:08 repo.go:649: walk data [files=8] cost [12.7925ms]
I 2024/11/23 20:23:10 sync.go:1585: got cloud latest [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c, files=8, size=8.7 kB, created=2024-11-23 20:22:44]
I 2024/11/23 20:23:11 repository.go:1468: synced data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=646 B] in [3.08s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/11/23 20:23:32 repo.go:157: purging cloud...
E 2024/11/23 20:23:34 repo.go:221: get index [9ebd133b56a351fee841ba34d624abd8e9b1bc0c] failed: cloud object not found
I 2024/11/23 20:31:11 repository.go:1396: syncing data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/false]
I 2024/11/23 20:31:11 repo.go:649: walk data [files=8] cost [9.8444ms]
I 2024/11/23 20:31:14 sync.go:1585: got cloud latest [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f/windows, id=9ebd133b56a351fee841ba34d624abd8e9b1bc0c, files=8, size=8.7 kB, created=2024-11-23 20:22:44]
I 2024/11/23 20:31:14 repository.go:1468: synced data repo [device=5d2d1f97-ddc5-422c-86f4-03c744141d9f, kernel=glnisp7, provider=2, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=646 B] in [3.16s], merge result [conflicts=0, upserts=0, removes=0]

### More information

There is no issue with syncing files

**Comment by 88250** [comment]
This issue has been fixed in the latest dev version, welcome to test.

**Comment by 88250** [comment]
Sorry, we just retested it and there are still some issues with the current dev version. We will continue to resolve it later. Please wait for the next dev version to test again. Thank you.
