### ISSUE TITLE
代码块剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13242]
代码块剪藏

关联 https://ld246.com/article/1732370147901

网页：https://fermi.ink/posts/2023/05/31/01/

![image](https://github.com/user-attachments/assets/ebfe16a1-dd98-4af6-8639-bfdf42218189)

剪藏：

![image](https://github.com/user-attachments/assets/0e338c01-c022-4ece-97ac-7a90acdabfee)

**Comment by TCOTC** [comment]
@88250 我剪藏会卡在这里：

![image](https://github.com/user-attachments/assets/2f7afeb5-9168-4775-833f-09dca0494585)

你那边怎么样？

**Comment by 88250** [comment]
我这边正常，这个多半是网络问题，你看下 Network 请求。

**Comment by TCOTC** [comment]
卡在了这个地方：

我访问不了这个 https://twemoji.maxcdn.com/v/14.0.2/72x72/2753.png

![image](https://github.com/user-attachments/assets/0ec6661a-09ac-4fda-aa68-3f8c269c146b)

**Comment by 88250** [comment]
我这里正常哦：

![image](https://github.com/user-attachments/assets/126e260d-3551-458c-9185-4aed399d84e4)

没有请求 maxcdn 这个域名的请求。

**Comment by TCOTC** [comment]
是个 emoji ，等了一阵子才加载出来：

![image](https://github.com/user-attachments/assets/a5c7b36f-25c2-436a-9a20-7192405abbaa)

![image](https://github.com/user-attachments/assets/3e5390c2-98c7-4c80-a3f2-973370d3df12)

**Comment by 88250** [comment]
ok
