### ISSUE TITLE
数学网站网页行级公式识别有问题

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#13258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

网页行级公式识别有问题：
https://www.matongxue.com/madocs/723/
公式块识别是正确的

### Expected result

行级公式正确识别

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/21e270ae-db82-4925-aa98-740258f187a7)
截图里可以看到似乎公式原图也拿到了，调试分析latex在alt段

### Version environment

```markdown
- Version: 3.1.13
- Operating System: Win10
- Browser (if used): Chrome 131
```

### Log file
[如何理解拉普拉斯变换？.zip](https://github.com/user-attachments/files/17899236/default.zip)
抓了一份静态网页，因为原网站现在需要微信登录后才能看文章

### More information

如果需要我测试 ，at我下

**Comment by 88250** [comment]
感谢反馈，下个 dev 版本发布后请帮忙测试看看。

**Comment by ruin1990** [comment]
v3.1.14-dev4 测试问题已解决，感谢修复
