### ISSUE TITLE
用户指南中添加打开用户指南的方法

### ISSUE THREAD

**Issue by emptylight370** [siyuan-note/siyuan#13255]
### In what scenarios do you need this feature?

用户指南在之前更新之后会自动关闭，社区里有很多问题就是怎么打开用户指南。我认为现在是时候在用户指南添加怎么打开用户指南的内容了。

### Describe the optimal solution

在“从这里开始”的显眼处添加怎么打开用户指南的方法，根据现有排版，个人倾向于添加在分割线上方，即

> 我们希望在接下来的时间里，思源能够成为你生活和学习的效率工具，帮助你实现更多的目标和计划🙏

内容之后

### Other information

希望告知：将仓库里的user guide文件夹导入思源可以直接编辑吗？

**Comment by TCOTC** [comment]
@88250 考虑一下

![image](https://github.com/user-attachments/assets/1c8d09a8-e88b-4e34-a351-86e0dbba7ccb)

**Comment by TCOTC** [comment]
> 将仓库里的user guide文件夹导入思源可以直接编辑吗？

可以，不过没必要

**Comment by emptylight370** [comment]
感谢T佬，不过不导入思源怎么编辑呢？

**Comment by TCOTC** [comment]
不推荐编辑，但具体还是看你是什么用途

**Comment by emptylight370** [comment]
> 不推荐编辑，但具体还是看你是什么用途

主要是看之前T佬提交的pr有修改guide的sy文件，所以想知道修改用户指南是不是需要修改仓库里的文件

**Comment by TCOTC** [comment]
一般是从仓库里复制笔记本到工作空间，编辑完之后再复制回仓库提交。如果改的地方少的话就直接找到对应的词修改了。

改用户指南会有一点坑要踩，所以不太推荐其他人改。

**Comment by emptylight370** [comment]
感谢T佬解答

**Comment by wish5115** [comment]
用户指南为何不搞在线版？这样更新和查找都方便吧

**Comment by 88250** [comment]
> @88250 考虑一下
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/389269446-1c8d09a8-e88b-4e34-a351-86e0dbba7ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDA1MDMsIm5iZiI6MTczMjUwMDIwMywicGF0aCI6Ii83ODQzNDgyNy8zODkyNjk0NDYtMWM4ZDA5YTgtZTg4Yi00ZTM0LWEzNTEtODZlMGRiYmE3Y2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAyMDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZjJiZTU0NjI2MmJjNDViYjRiNmY4YzZiZGFkY2Q4MGY5NzFlNzcwODQ1NzAxODAyZTExNDRiYzA0YzRiMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5UX380Iy5L-0HuH6H-GjD8KazFEe_KCuCgVHKBwlkXk)
> 
> ```
> > 关闭思源笔记时会自动关闭用户指南，可以点击 <kbd>主菜单</kbd> - <kbd>用户指南</kbd> 再次查看
> ```

请帮忙 PR 一下。
