### ISSUE TITLE
非编辑块删除后撤销异常

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#13254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

删除html可以重复撤回，并且得到的结果为实际的html内容，具体见视频。

### Expected result

不应该可以进行第二次撤回

### Screenshot or screen recording presentation

https://github.com/user-attachments/assets/6afca156-0cfd-4f85-a5b6-328d2d3e66c7

### Version environment

```markdown
- Version: 3.1.11
- Operating System: 
- Browser (if used):
```

### Log file

-

**Comment by TCOTC** [comment]
撤销再重做会变成字符实体

![image](https://github.com/user-attachments/assets/b3b89fa6-405b-49e3-bfe4-f421fb751ee9)

**Comment by TCOTC** [comment]
@Vanessa219 撤销再重做还是会变成实体：

![image](https://github.com/user-attachments/assets/4451d6d9-4dfb-4b9c-ada7-a425b8223cdb)
