### ISSUE TITLE
豆包复制粘贴问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13265]
网址：https://www.doubao.com/thread/wd13986daaf6afb10

点下面的复制然后粘贴到思源里：

![image](https://github.com/user-attachments/assets/ad8607a6-e5ed-4ec8-bd3d-7b2b15248b30)

所有文本都在一个块中：

![image](https://github.com/user-attachments/assets/8ea8079f-5c95-45b6-a097-1a320d8d200b)

不知道能不能针对性处理一下这种 `white-space: pre;` 的 span 元素：

```html
<span style="white-space: pre;">以下是对这个句子意味的辨析：
### 整体意境营造
这句话描绘出一种极为静谧、柔和且充满诗意的氛围。仿佛时间的话语被轻柔地诉说着，带着一种细腻的情感，引领着人的思绪进入到一个宁静且美好的情境之中。
### 具体词汇解读
- “Whisper the words of time gently”（轻柔地低语时间的话语）：这里将时间拟人化，赋予了时间能够“说出话语”的能力，并且是被“轻柔地低语”，给人一种时间的流淌并非是那种急促、喧嚣的感觉，而是如耳边的轻声细语般，缓缓而来，暗示着人们要以一种平和、细腻的心境去感受时间的推移，去聆听时间所蕴含的种种故事与启示。
- “let the soul encounter the splendid dream of blooming flowers in tranquility”（让灵魂在宁静中邂逅繁花绽放的绚烂梦想）：此部分强调了灵魂层面的体验。“让灵魂……邂逅”表示一种引导灵魂去经历、去遇见的意味，而所遇见的是“繁花绽放的绚烂梦想”，“繁花绽放”象征着美好、繁荣、充满生机的景象，代表着那些绚丽多彩、令人向往的梦想或美好愿景。“在宁静中”再次突出了整个情境的安静祥和，意味着这种灵魂与美好梦想的相遇不是在纷扰、嘈杂的环境下，而是在一片宁静之中，更能凸显出这种邂逅的纯粹与珍贵，也暗示着只有当内心平静时，灵魂才更容易感知到那些美好的梦想。
### 情感与主题传达
整体传达出一种对宁静、美好的向往之情。鼓励人们在喧嚣的生活中，静下心来，去倾听时间的声音，去感受内心深处的宁静，从而能够让灵魂与那些如繁花般绚烂的梦想相遇，或许是在提醒人们不要在忙碌中迷失了对美好事物的感知与追求，要保持一颗宁静且充满期待的心去拥抱生活中的梦想与希望。</span>
```

**Comment by ruin1990** [comment]
这个问题，有点像：https://github.com/siyuan-note/siyuan/issues/13195
当时修改点：https://github.com/siyuan-note/siyuan-chrome/pull/11/files
难道我还漏了个white-space: pre ?
之前的主逻辑：
```
if (
            (style.whiteSpace.trim().toLowerCase() === 'normal' || style.whiteSpace.trim().toLowerCase() === 'pre-wrap') &&
            (style.wordWrap.trim().toLowerCase() === 'break-word' || style.overflowWrap.trim().toLowerCase() === 'break-word' || style.wordBreak.trim().toLowerCase() === 'break-word')
        )
```

**Comment by 88250** [comment]
应该不用动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月26日(周二) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 豆包复制粘贴问题 (Issue #13265)




 
这个问题，有点像：#13195
 当时修改点：https://github.com/siyuan-note/siyuan-chrome/pull/11/files
 难道我还漏了个white-space: pre ?
 之前的主逻辑：
 if (             (style.whiteSpace.trim().toLowerCase() === 'normal' || style.whiteSpace.trim().toLowerCase() === 'pre-wrap') &amp;&amp;             (style.wordWrap.trim().toLowerCase() === 'break-word' || style.overflowWrap.trim().toLowerCase() === 'break-word' || style.wordBreak.trim().toLowerCase() === 'break-word')         )

**Comment by ruin1990** [comment]
嗯，我也觉得应该不用动，很少遇到white-space: pre;，大部分都是white-space: pre-wrap;，
查了一下区别在于后者pre-wrap对于超出元素范围的文字能自动换行，正常网页应该还是要考虑到这个的。
以后如果真遇到了再改。
