### ISSUE TITLE
在思源笔记中删除的文件或附件不要彻底删除，而是放入系统回收站

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1326]

**Comment by 88250** [comment]
你好，考虑到跨平台需要保持一致，所以没有提供。

为防止意外，建议挂个同步盘或者通过 Git 管理版本。

**Comment by SeyeeL** [comment]
希望内置一个回收站，这样删除的时候就可以直接删，目前v1.4.2每次删除都有弹窗好麻烦，因为很多时候是点新文档点错了就删掉。

**Comment by 88250** [comment]
@SeyeeL 笔记本历史上可以恢复删除的文件。
