### ISSUE TITLE
Improve database select field color and layout

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13263]
改进单选字段颜色和布局

颜色竖着排列太浪费空间了：

![image](https://github.com/user-attachments/assets/9845c97b-0d49-4f0f-93ab-1214f81812e6)

比较方便的是参考外观菜单和 FlowUs，把颜色改成横排，然后给正在使用的背景色按钮添加灰色背景：

![image](https://github.com/user-attachments/assets/29f6503d-6e4c-4d2b-9ad6-7055e0e14a34)

![image](https://github.com/user-attachments/assets/4a0304cc-feac-4e52-9b07-05ea17453e55)

**Comment by Vanessa219** [comment]
相似的颜色有点多，同时更新一下

![image](https://github.com/user-attachments/assets/63fe8f32-5efd-4b12-a565-da3175946627)

![image](https://github.com/user-attachments/assets/0c923ba1-b169-419f-9d47-50116a8d8130)

**Comment by TCOTC** [comment]
这个颜色的排序有什么讲究吗？

**Comment by TCOTC** [comment]
感觉还是挺像的：

![IMG_20241210_135144.png](https://github.com/user-attachments/assets/11e84fe0-c2c7-4562-8b7c-f5998573f3da)

**Comment by TCOTC** [comment]
@Vanessa219 选项的颜色有点问题，没有在 1~13 循环，会出现不存在的颜色：

![image](https://github.com/user-attachments/assets/12b95fc8-6626-44f6-8d36-cc2cfff4101d)

**Comment by TCOTC** [comment]
@Vanessa219 会有一个不存在的 14：

![image](https://github.com/user-attachments/assets/33bf2b14-0063-41e6-9dd0-16e5b2f48f49)

**Comment by Vanessa219** [comment]
这个是跟随系统的样式，就没有填充了

**Comment by TCOTC** [comment]
这里应该是 1 的

**Comment by Vanessa219** [comment]
![image](https://github.com/user-attachments/assets/de1dcb13-c9ae-4d49-bd88-a0ca9453fce1)

**Comment by TCOTC** [comment]
这个 14 就留给手动选吧，选项自动循环到 14 就没背景色了用起来会很奇怪

**Comment by Vanessa219** [comment]
先这样吧，不选到的话就没有必要存在了。选项循环的情况少，而且到了循环的时候一般都会再手动设置一下吧。
