### ISSUE TITLE
多选文档的右键菜单支持 `复制文档名`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13266]
> #11561 的后续

类似于 #13062 ，在多选文档的右键菜单添加一个 `复制文档名`

---

另外数据库这个看起来有点怪，我希望改一下：

![image](https://github.com/user-attachments/assets/4c394700-e1c0-42c1-a71d-61f60ad15930)

**Comment by Vanessa219** [comment]
看了一下很多产品都没有复制文件名这个功能，目前菜单太多，我自己选起来都比较困难。
可以使用复制可读路径勉强解决一下。 

文案的话直接 PR 就可以了。
