### ISSUE TITLE
ChatGPT剪藏

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13260]
https://chatgpt.com/share/67445929-6bb4-8004-80cb-972997e99860

![image](https://github.com/user-attachments/assets/c98c8c24-be4c-4ea3-8a23-f09b7e4267f6)

**Comment by TCOTC** [comment]
复制粘贴的话里面的块级公式会变成行级公式

**Comment by 88250** [comment]
剪藏不好适配，复制粘贴稍后改进。
