### ISSUE TITLE
水平布局时对齐不合理

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13279]
**其他内容基本对齐，代码块偏移很大**
![image](https://github.com/user-attachments/assets/4b3d0aef-90c7-4e17-b1ca-5a6b3ef71b35)

**部分块会导致右边也不对齐**
![image](https://github.com/user-attachments/assets/79d529a2-016f-45be-8aea-fdfd0b51c361)

**Comment by cordinGH** [comment]
好像其他内容也有点不齐
![image](https://github.com/user-attachments/assets/1722e2a1-f135-488f-aa19-69bf1b1c3c98)

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/12318

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/12318 中解决

**Comment by cordinGH** [comment]
> https://github.com/siyuan-note/siyuan/issues/12318 中解决

已更新，效果很好👍
