### ISSUE TITLE
通过 `<iframe>` 引用的资源文件纳入引用计算

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1327]
### 描述问题 Describe the problem
放入assets，通过iframe嵌入的pdf会被识别为未引用资源

### 期待的结果 Expected result
assets内被iframe嵌入的文件不要识别为未引用

**Comment by 88250** [comment]
你好，我这里试了一下，没能重现。

**Comment by roverway** [comment]
![image](https://user-images.githubusercontent.com/657850/106343870-8517ea00-62e2-11eb-82ac-f6e47aa0a1ec.png)

![image](https://user-images.githubusercontent.com/657850/106343873-89440780-62e2-11eb-9b94-1e1f31d4de88.png)

D大，你看我的上面截图就是我说的这种情况

**Comment by 88250** [comment]
哦，用绝对路径的话不会纳入计算的。

**Comment by roverway** [comment]
明白了，我改成相对路径了。那这个我感觉不算bug，帮助文件里提一句就行了。

**Comment by 88250** [comment]
稍后改进文档，我关闭了。
