### ISSUE TITLE
浏览器端打开 plugin link

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#13289]
### In what scenarios do you need this feature?

目前思源的桌面端可以识别形如 `siyuan://plugin/xxx` 的链接，从而允许插件自定义一些自己的超链接。

但是这个功能在浏览器端支持的并不好。当在浏览器中点击一个 plugin link 的时候，会将请求发送给桌面端处理，而非在浏览器内处理。

同样的问题不仅出现在「本地桌面端的浏览器伺服」界面也出现在「docker端」中。我在 docker 中尝试点击一个连接，结果却在我本地的桌面端中打开。

![image](https://github.com/user-attachments/assets/03257418-ff80-4dbc-90ef-0ddff7a272a5)

相关 issue：https://github.com/frostime/sy-docs-flow/issues/73

### Describe the optimal solution

当在浏览器（docker）中打开插件链接的时候，能正确地在浏览器内部处理链接事件。

**Comment by TCOTC** [comment]
- 确实 #12297

**Comment by 88250** [comment]
这个不考虑了，让用户自行决定是否需要用 http 协议。

**Comment by frostime** [comment]
> 这个不考虑了，让用户自行决定是否需要用 http 协议。

那为啥浏览器端的 siyuan blockid 链接能正常生效呢？插件链接和 block 链接本质上没啥区别吧？

**Comment by TCOTC** [comment]
本地的思源在浏览器打开是正常的，只有 Docker 才有这个问题

**Comment by frostime** [comment]
> 应该不能生效吧，会拉起应用。

我这个访问的是远端的 docker 哦

![PixPin_2024-11-27_21-50-52](https://github.com/user-attachments/assets/dedb08dc-7dfc-4f0e-b80f-fa493d20b3ae)

**Comment by TCOTC** [comment]
神奇

**Comment by 88250** [comment]
呃，那不清楚了，谁有空去看看代码吧，欢迎 PR。

**Comment by frostime** [comment]
> 呃，那不清楚了，谁有空去看看代码吧，欢迎 PR。

那要不还是把这个 open 吧；既然我那里显示的可以点击 siyuan 链接实现跳转，那说明总归是有办法的。就算是 backlog 掉也行。
