### ISSUE TITLE
改进 PDF 跨页标注

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13282]
https://ld246.com/article/1732610937549

我还没测试

**Comment by Vanessa219** [comment]
目前不知道能不能处理，我先关闭了，可以处理再打开。

**Comment by Vanessa219** [comment]
已修复，不拉进 3.1.15 了

**Comment by TCOTC** [comment]
我发现不是颜色的问题，跨页都标注不了：

[video.webm](https://github.com/user-attachments/assets/d833b9f6-c8d3-41fa-a198-ee1ea0ecbc18)

**Comment by TCOTC** [comment]
跨页的标注还有点怪：

[video.webm](https://github.com/user-attachments/assets/e055dc69-7a7c-44be-ac9b-05021d178223)

**Comment by TCOTC** [comment]
还有点问题：

1. 点击标注跳转到 PDF 时只有前一页的标注会闪烁一下
2. 改变标注颜色时跨页的标注颜色不统一

**Comment by jhs1965net** [comment]
great thanks, any possibility to fix in ipad
