### ISSUE TITLE
历史版本增强

### ISSUE THREAD

**Issue by Jial08** [siyuan-note/siyuan#13280]
### In what scenarios do you need this feature?

目前的历史是按照保留天数的，是否能参考群辉的版本控制新增按版本数量上限控制？

### Describe the optimal solution

<img width="690" alt="image" src="https://github.com/user-attachments/assets/fc0a68f4-5b2d-4481-9c17-2b249cb0f013">

这个是群辉 Synology Drive 的版本控制，是否能提供相同的版本逻辑功能？目前的天数不是很符号我的功能需求，感谢

**Comment by 88250** [comment]
你指的是快照清理策略吗？

**Comment by Jial08** [comment]
不是，就是历史保留天数
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/9434293d-d96d-4038-8c45-796607248159">

群辉可以查看某个文件的最近多少次修改
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/139b95dc-393a-47af-8e56-a5fc0559d05a">

我们的历史保留天数过期了就没有历史版本了吧

**Comment by 88250** [comment]
文件历史和数据快照都是按最长天数保留的，超过天数就会被自动清理掉。

因为笔记数据是较为易变的数据，如果按版本数量的话可能不符合大部分用户的预期，所以这里我们就不考虑以数量为主的清理策略了，谢谢。
