### ISSUE TITLE
（（引用大纲块出现内容错误，并且鼠标放在上面不会显示块内容

### ISSUE THREAD

**Issue by nightlye** [siyuan-note/siyuan#1328]
https://user-images.githubusercontent.com/53067795/106108376-1f611c00-6183-11eb-8720-cade13e5cc83.mp4

如视频所示。
右键选择复制块引用和搜索引用是两个id。

**Comment by 88250** [comment]
你好，请在 v0.7.0 上进行回测，如果还有问题请继续跟帖，谢谢。
