### ISSUE TITLE
Graph nodes no longer display memos

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13287]
### In what scenarios do you need this feature?

关系图节点不应该优先显示块备注，块备注一般内容比较多，我有些文档只有备注，没有命名，会导致在关系图里都无法分辨这些文本对应的点在哪里了

![image](https://github.com/user-attachments/assets/de59b56c-4144-480b-83e1-30991a371107)

### Describe the optimal solution

关系图不显示备注。只显示块内容和块命名

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/1262
