### ISSUE TITLE
Improve exporting block ref

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13283]
导出pdf支持块引转锚点哈希跳转

### In what scenarios do you need this feature?

https://ld246.com/article/1729305846229

目前导出pdf只支持导出块引为脚注，无法跳转到被引用的本文档内的块，脚注在此场景下体验不佳，会重复生成块，也没有回到原文某段文字的作用，无法制作出pdf文档标题目录，图表引用等功能，导出后的效果和在思源笔记使用的体验差别很大。

另外，目前我写的脚注插件，可以把脚注放在当前文档或者父块后，以往如果导出pdf，块引会转为脚注，这些脚注块就无法放在当前文档不然就会重复，如果能对导出pdf进行改进，脚注块放在当前文档，则能点击就跳转到对应的脚注块，会更加的自由方便

### Describe the optimal solution

鉴于需要考虑引用的块是不是当前文档（及其子文档）

可参考帖子https://ld246.com/article/1729305846229

中讨论的建议
引用的是非当前文档（及其子文档）中的内容，在导出 PDF 之后转换为脚注；
引用的是当前文档（及其子文档）中的内容，在导出 PDF 之后可以直接点击跳转。

对于递归引用，只考虑第一层级引用的块是不是当前文档（及其子文档）的块

### Describe the candidate solution

无

**Comment by Achuan-2** [comment]
dev5 pdf导出，块引好像没有变化

**Comment by Achuan-2** [comment]
另外块超链接也应该跟随块引导出的原则，进行转换

**Comment by 88250** [comment]
> 建议对于pdf，导出块引为脚注or锚点哈希效果是一样的

OK

> 另外块超链接也应该跟随块引导出的原则，进行转换

这个不动了，超链接不是块引

**Comment by Achuan-2** [comment]
还是希望块超链接也能导出锚点哈希和脚注
1. 很多用户有时候不希望块引给反链面板添加太多信息，就会用块超链接，在思源笔记里，块超链接除了只是单向链接以及外部软件打开思源外，和块引没有区别。块超链接其实和导出锚点哈希的效果才是最一致的，也应该支持导出锚点哈希。
2. 一方面，如果用户需要导出块超链接，导出pdf的时候块引可以选择导出为块超链接，这样pdf中无论块引和块超链接全是块超链接。另一方面，应该没有几个用户希望，块引和块超链接导出pdf，只有块引转化了，而块超链接没有变化，块超链接只是给自己用，既然想要导出锚点哈希，要么是为了方便导出方便直接在pdf里看，要么就是给别人看，块超链接没有变化，是不符合预期的

**Comment by 88250** [comment]
有道理，稍后加一下，麻烦帮忙测试看看。

**Comment by Achuan-2** [comment]
> 有道理，稍后加一下，麻烦帮忙测试看看。

ok，激动，这下导出功能大进步了😄

**Comment by congSjwbsz** [comment]
这个功能终于改进了，这个导出优化再配合【目录插件】以后分享笔记不用自建服务器也可以分享了
关联：https://ld246.com/article/1723470408894

**Comment by Achuan-2** [comment]
> 这个功能终于改进了，这个导出优化再配合【目录插件】以后分享笔记不用自建服务器也可以分享了 关联：https://ld246.com/article/1723470408894

不知道锚点哈希的md导出为word能不能支持跳转

**Comment by 88250** [comment]
好的，稍后再改改。

**Comment by Achuan-2** [comment]
> 好的，稍后再改改。

辛苦辛苦，直接起飞🛫🚀
下周末的视频就讲思源导出做手册、电子书😄

**Comment by 88250** [comment]
@Achuan-2 麻烦发一下你那边 pandoc 导出的命令

**Comment by Achuan-2** [comment]
> @Achuan-2 麻烦发一下你那边 pandoc 导出的命令

直接用的`pandoc input.md   -o output.docx`

**Comment by TCOTC** [comment]
@Achuan-2 发一下你导出的 .docx 看看。这个链接看起来像是只能在你的设备上点击跳转的

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/4a11a048-f627-430a-9dcd-402f54808313)

[foo.docx](https://github.com/user-attachments/files/17969036/foo.docx)

**Comment by TCOTC** [comment]
这个确实是本地路径的链接

```
<p class="MsoBodyText"><span><a href="file:///D:/Admin/Desktop/foo.docx#X3a613a81036ac0ce6dcd36a42b8063473d145ce"><span class="15" style="mso-spacerun:'yes';font-family:Aptos;mso-bidi-font-family:'Times New Roman';
color:rgb(21,96,130);">111</span></a></span><span style="mso-spacerun:'yes';font-family:Aptos;mso-bidi-font-family:'Times New Roman';
font-size:12.0000pt;"><o:p></o:p></span></p>
```

能跳转的链接应该是这种：

```
<p class="MsoNormal"><span><a href="file://xn--1-471bx41aba436x/#_33333333333333333333"><u><span class="15" style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:Calibri;
mso-hansi-font-family:Calibri;mso-bidi-font-family:'Times New Roman';color:rgb(0,0,255);
text-decoration:underline;text-underline:single;"><font face="Calibri">111111111111111</font></span></u></a></span></p>
```

**Comment by Achuan-2** [comment]
> ![image](https://private-user-images.githubusercontent.com/873584/391334687-4a11a048-f627-430a-9dcd-402f54808313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTk5NjUsIm5iZiI6MTczMzA1OTY2NSwicGF0aCI6Ii84NzM1ODQvMzkxMzM0Njg3LTRhMTFhMDQ4LWY2MjctNDMwYS05ZGNkLTQwMmY1NDgwODMxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMzI3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGE1YjE0ZTA2YWYyNGI4NzUwYTEyMjY1MDhlZjhiYzExYTk5YWUwNWJmYjk5MDZlOTJjZWQ2ZTBjNGRjN2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4wq9OlBX7mBnaOV1H2-EsDeC3wkdxJTzEUiVqtvqfok)
> 
> [foo.docx](https://github.com/user-attachments/files/17969036/foo.docx)

可以跳转的，这个路径只是word自己加上的，你移动word之后，自动会改
![PixPin_2024-12-01_21-28-11](https://github.com/user-attachments/assets/e0e2c68f-975a-42bc-8c91-1d2e84a37c8b)

**Comment by Achuan-2** [comment]
> [output2.docx](https://github.com/user-attachments/files/17969050/output2.docx)
我的导出文件，也可以试试能不能跳转

**Comment by TCOTC** [comment]
我这里跳不了

**Comment by Achuan-2** [comment]
> D 发的那个我这里跳不了

你试试我的

**Comment by TCOTC** [comment]
我知道了，是不兼容 WPS ，这两个文件用 Word 打开就是能跳转的

**Comment by Achuan-2** [comment]
> 我知道了，是不兼容 WPS ，这两个文件用 Word 打开就是能跳转的

哦哦，那就没问题了，wps本身就有点问题，pandoc导出markdown为word的模板也不一定能用于wps

**Comment by 88250** [comment]
那就改下：块引导出模式为哈希锚点时，导出 .docx 默认切换为脚注模式。

**Comment by TCOTC** [comment]
话说我用 Word 添加的链接，在 WPS 里是能跳转的，是不是 Pandoc 的问题

**Comment by 88250** [comment]
不清楚，但是感觉 pandoc 导出 Word 的没问题应该就不是 pandoc 的问题。

**Comment by Achuan-2** [comment]
> 那就改下：块引导出模式为哈希锚点时，导出 .docx 默认切换为脚注模式。

脚注模式是也像pdf一样区分文档内用锚点哈希和文档外用脚注吗

**Comment by TCOTC** [comment]
WPS 添加的链接在 Word 里也能跳转

**Comment by 88250** [comment]
> 脚注模式是也像pdf一样区分文档内用锚点哈希和文档外用脚注吗

是

**Comment by Achuan-2** [comment]
导出word的锚点哈希貌似有点问题，点击所有链接都是跳转到最前面

**Comment by 88250** [comment]
帮忙试下这两个文件的跳转：

[导出 PDF 和 Word 锚点.docx](https://github.com/user-attachments/files/17971003/PDF.Word.docx)
[导出 PDF 和 Word 锚点.pdf](https://github.com/user-attachments/files/17971004/PDF.Word.pdf)

**Comment by Achuan-2** [comment]
> 帮忙试下这两个文件的跳转：
> 
> [导出 PDF 和 Word 锚点.docx](https://github.com/user-attachments/files/17971003/PDF.Word.docx) [导出 PDF 和 Word 锚点.pdf](https://github.com/user-attachments/files/17971004/PDF.Word.pdf)

pdf没问题，word全都是跳转到最前面

**Comment by Achuan-2** [comment]
另外，导出预览模式有问题

1. 导出锚点哈希模式不起作用，应该效果和脚注一样（突然想到锚点哈希模式还有存在必要吗，要不干脆把导出为脚注，改为导出为「脚注和锚点哈希」？
2. 选择导出为脚注后，锚点哈希会自动添加域名

![PixPin_2024-12-02_09-54-14](https://github.com/user-attachments/assets/70921622-2b2b-449b-aa0a-f4afd5d17718)

**Comment by Achuan-2** [comment]
导出md的问题：

块超链接，只是转化为块引，但是没有变为锚点哈希

![PixPin_2024-12-02_10-25-21](https://github.com/user-attachments/assets/6780bf23-b481-435a-8894-3702d641cbf4)
![PixPin_2024-12-02_10-25-31](https://github.com/user-attachments/assets/ad201f08-14ea-4555-aae1-fff85197c0f6)

**Comment by 88250** [comment]
> 导出锚点哈希模式不起作用，应该效果和当前选择导出为脚注的效果一样

稍后改进

> 选择导出为脚注后，锚点哈希会自动添加域名

我这里重现不了，麻烦导出 .sy.zip 给我试试

> 导出md，选择导出锚点哈希的问题

稍后改进

----

我在想是不是把脚注和哈希锚点合并吧，因为两个模式加起来才是完全体。

**Comment by Achuan-2** [comment]
我在想是不是把脚注和哈希锚点合并吧，因为两个模式加起来才是完全体

是的，我觉得可以合并，文档内是锚点哈希，文档外是脚注，选项改为脚注和锚点哈希

**Comment by Achuan-2** [comment]
>> 选择导出为脚注后，锚点哈希会自动添加域名
>
>我这里重现不了，麻烦导出 .sy.zip 给我试试

我指的是选择块引导出为【脚注】，导出预览模式选择复制到语雀

[20241202 09_47_36.sy.zip](https://github.com/user-attachments/files/17972040/20241202.09_47_36.sy.zip)

**Comment by Achuan-2** [comment]
导出pdf问题：

当导出pdf时，如果文档有附件，会导致所有的锚点哈希失效

[导出pdf时文档有附件，会导致所有的锚点哈希失效.sy.zip](https://github.com/user-attachments/files/17972087/pdf.sy.zip)

**Comment by 88250** [comment]
> 当导出pdf时，如果文档有附件，会导致所有的锚点哈希失效

对，这个问题我也发现了。

**Comment by Achuan-2** [comment]
> > 当导出pdf时，如果文档有附件，会导致所有的锚点哈希失效
> 
> 对，这个问题我也发现了，但是解决不了，是 PDF 处理库的 bug。

那能不能选择导出为锚点哈希，干脆把pdf所有的附件asset链接变为普通文本，等这个bug解决了再改回去

**Comment by 88250** [comment]
这个是已有的问题，就不改了，不然嵌入不了附件。

**Comment by Achuan-2** [comment]
> 这个是已有的问题，就不改了，不然嵌入不了附件。

ok，知道有这个bug也行，我有一个文档之前一直导出pdf锚点哈希无效，一个个删，才找出这个原因所在

**Comment by 88250** [comment]
另外复制语雀那个问题可以解决错误添加图床地址的问题，但是解决不了锚点，因为复制到语雀用的是标准 markdown 渲染，不插入锚点的。

**Comment by 88250** [comment]
这个版本暂时先改进这么多，后面考虑一下要不要合并 脚注+哈希锚点，稍后我们发测试版，麻烦关注。

**Comment by Achuan-2** [comment]
> 另外复制语雀那个问题可以解决错误添加图床地址的问题，但是解决不了锚点，因为复制到语雀用的是标准 markdown 渲染，不插入锚点的。

嗯嗯，理解的，用这个主要是不需要再导出md，可以直接复制md，粘贴到其他地方，比如GitHub

**Comment by Achuan-2** [comment]
> 这个版本暂时先改进这么多，后面考虑一下要不要合并 脚注+哈希锚点，稍后我们发测试版，麻烦关注。

辛苦辛苦

**Comment by Achuan-2** [comment]
@88250 发现一个bug，如果导出文档为pdf时，不设置导出文档标题，子文档引用父文档的链接会失效

**Comment by 88250** [comment]
感谢反馈，后续在 https://github.com/siyuan-note/siyuan/issues/13331 中跟进。
