### ISSUE TITLE
自定义排序下，给笔记本和父文档右键菜单添加排序功能

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13297]
### In what scenarios do you need this feature?

自定义排序之前导入的文档都是乱序
![PixPin_2024-11-28_10-09-22](https://github.com/user-attachments/assets/a1a33b92-b546-4cdd-9228-b3410e8695c5)

我希望能在自定义排序下，添加排序功能，这样减少自己手动拖动的麻烦。
注意：我这里的排序功能，指的是代替手动排序，依然保留排序结果的排序，只不过把手动排序的步骤，自动化了，不是嵌套排序

### Describe the optimal solution

自定义排序下，给笔记本和父文档添加排序功能，这个排序是把手动排序的步骤进行自动化，不是嵌套排序

这样会把自定义排序变得更加灵活，有基本的排序功能，可以先随意无序创建文档，沉静于创作，之后再根据文档名进行排序，得到有序的笔记层级，不用受制于自动排序的制约，非常自由，大大增强自定义排序的实用程度

### Describe the candidate solution

无

**Comment by TCOTC** [comment]
一次性自动排序

**Comment by 88250** [comment]
自定义排序是需要手动排序的，如果有自动化需求建议考虑插件实现。

**Comment by Achuan-2** [comment]
> 自定义排序是需要手动排序的，如果有自动化需求建议考虑插件实现。

好的，那请问存储自定义排序的文件存放在哪

**Comment by Achuan-2** [comment]
如果能用插件修改sort.json，应该就可以实现自定义排序功能了

* `/api/file/getFile`
* `/api/file/putFile`

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/66e5e9bb-3b4b-4860-be8e-39ac9a5bcdd5)
