### ISSUE TITLE
非必要的md语法渲染

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#1329]
今天发现贴入一个Excel函数
原文内容`SUMPRODUCT( $B$20:$ C$20,B2:C2)`

在思源中
![image](https://user-images.githubusercontent.com/11142054/106110999-6ef51700-6186-11eb-8a0a-f04b46259f78.png)

这种情况其实已经出现过蛮多次了
建议退出一个原样显示内容的功能
对设置了原样显示的内容，不再使用md语法进行渲染

**Comment by 88250** [comment]
请使用 `\` 转义。

**Comment by 88250** [comment]
请使用 `\` 转义。
