### ISSUE TITLE
导出时，数据库中的绑定块，变为块引，能导出为锚点哈希

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13298]
### In what scenarios do you need this feature?

我用思源笔记导入开源的电子书《自学是门手艺》
我用数据库来管理各章节
![PixPin_2024-11-28_10-37-01](https://github.com/user-attachments/assets/e0a67658-7d7e-46a6-bd61-2675f7d1d717)
这样的好处是，阅读一章节的时候，我悬浮数据库角标，就能跳转到其他章节（相比用文档树，可以更自由的排序，添加已读/未读标签、总结备注等信息）
![PixPin_2024-11-28_10-37-51](https://github.com/user-attachments/assets/116ecc59-9ac7-4300-b5ca-faf014dd9235)

但是目前导出含有绑定块的数据库，导出markdown 数据库里的绑定块都为纯文本，不是块引，也不跟随我导出块引的设置变为锚点哈希

### Describe the optimal solution

导出时，数据库中的绑定块，变为块引，能导出为锚点哈希

### Describe the candidate solution

无

**Comment by 88250** [comment]
数据库中的主键目前不考虑和引用做相同的逻辑。
