### ISSUE TITLE
Remove Unicode PUA characters

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13291]
PUA 字符无法查找替换

关联帖子：https://ld246.com/article/1732700068088

这个网页中包含了 [PUA 字符](https://en.wikipedia.org/wiki/Private_Use_Areas) U+E004 ：https://www.gov.cn/zhengce/2016-05/24/content_5076294.htm

![image](https://github.com/user-attachments/assets/39297210-7ebf-4bc8-badc-23ae3dbf1eaf)

在思源中无法查找和替换：

![image](https://github.com/user-attachments/assets/9f318955-53cc-4062-941b-0e940b62f292)

点新建文档的话也没有文档名：

![image](https://github.com/user-attachments/assets/716b7c24-d495-4f31-9f99-84e9ebddfd67)

**Comment by TCOTC** [comment]
PUA 字符的字形好像是可以通过制作字体来自定义的，直接删除合适吗？还是说根本没办法实现搜索和替换？

**Comment by 88250** [comment]
实现不了，先移除吧。

**Comment by TCOTC** [comment]
编辑已经包含 PUA 字符的块会删除 PUA 字符吗？

**Comment by 88250** [comment]
不会
