### ISSUE TITLE
在笔记中不能正常使用小小输入法

### ISSUE THREAD

**Issue by tswwe** [siyuan-note/siyuan#13290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用小小输入法 yong.exe（以 TSF 模式运行），在其他软件中，按下中英文切换键（默认是 LCTRL）切换到英文状态，即可进行英文输入；但在思源笔记中，切换到英文状态后，再按任意键，小小输入法会立刻变回中文状态，并且，在打字过程中，输入法状态条会频繁闪烁。

### Expected result

在思源笔记中使用 TSF 模式的小小输入法，应像在其他软件中一样，打字时状态条不闪烁，并且切换到英文状态后，可进行正常的英文输入。

### Screenshot or screen recording presentation

https://github.com/user-attachments/assets/ab4c3bad-2dec-4037-b5ca-cff83756c077

### Version environment

```markdown
- Version: 3.1.13
- Operating System: Win10
```

### Log file

not neccessary
[siyuan.log](https://github.com/user-attachments/files/17928544/siyuan.log)

### More information

小小输入法最新版本：[yong-20241126.zip](https://github.com/user-attachments/files/17928469/yong-20241126.zip)

如何安装小小输入法并以 TSF 模式运行：解压至 `C:\Program Files (x86)`，运行里面的 `tsf\install.bat` 以安装 TSF 模块（安装成功后会在系统中添加一个 Yong 输入法键盘），随后像视频中那样操作（切换至 Yong 输入法键盘，注意不能是微软拼音或其他键盘，并运行主程序 `w64\yong.exe`）即可。
> 小小输入法有两种输入模式，一种是外挂模式，一种是 TSF 模式（能够获得系统原生输入法级别的体验），后者需要安装 TSF 模块。

**Comment by 88250** [comment]
我们最近调整了下输入法兼容，请帮忙试下目前最新的 dev 版（v3.1.14-dev4）。

**Comment by tswwe** [comment]
> 我们最近调整了下输入法兼容，请帮忙试下目前最新的 dev 版（v3.1.14-dev4）。

感谢你们的辛勤工作，遗憾的是经测试，问题依然存在。

如果需要的话请告诉我，我可以将测试用虚拟机导出并分享到网盘（或通过其他方式发送），以便你们快速追踪问题。

**Comment by 88250** [comment]
收到，但小众输入法一时半会我们兼容不了，先整理到 https://github.com/siyuan-note/siyuan/issues/4826 中。

**Comment by tswwe** [comment]
更新：反馈给小小输入法开发者后，其作了专门适配，问题已消除。

[反馈的过程](https://yong.dgod.net/read.php?tid=4932)表明，此问题似乎是因为思源笔记频繁发送焦点消息导致的，建议开发者 @88250 核实并考虑此行为是否规范，评估是否会导致性能空耗或者更严重的问题？

**Comment by 88250** [comment]
目前思源估计只能这样，感谢感谢。
