### ISSUE TITLE
反向链接面板在数据库切换视图时闪烁，快速折叠并展开，在新建视图后自动全部折叠

### ISSUE THREAD

**Issue by Cosss7** [siyuan-note/siyuan#13299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

反向链接面板在数据库切换视图时闪烁，快速折叠并展开，在新建视图后自动全部折叠

### Expected result

反链面包保持全部展开的样子

### Version environment

```markdown
- Version: 3.1.13
- Operating System: windows 11
- Browser (if used):
```

### Log file

我检查了，这个不会产生日志

**Comment by Cosss7** [comment]
顺便问下，反链面板折叠/展开的逻辑是怎样的？期望是默认全部展开吗？

**Comment by Cosss7** [comment]
看起来是有几个反链展开，就会重复几次折叠/展开

**Comment by Cosss7** [comment]
补充，不只是切换数据库视图，修改笔记后，执行数据库提交的时候也会重复折叠/展开

**Comment by 88250** [comment]
请下载最新 dev 版测试看看。

**Comment by Cosss7** [comment]
> 请下载最新 dev 版测试看看。

测试没问题了，请问是哪个提交修复的？我学习一下

**Comment by 88250** [comment]
@Vanessa219 找一下提交记录

**Comment by Vanessa219** [comment]
8a6ba2b2d0840e725a625efb5d59132aefae6118
