### ISSUE TITLE
【shift+回车】的问题

### ISSUE THREAD

**Issue by wfan14513** [siyuan-note/siyuan#133]
1.一段如下的文字：
**我想同时引用多段文字。**
所以我用了shift+回车把它们放到同一个块中。然后第一句话加粗了。

2.但是最后显示的是：
**我想同时引用多段文字。** 所以我用了shift+回车把它们放到同一个块中。然后第一句话加粗了。

也就是没有换行。但是把光标放在被加粗的那句话上，是能分段的（如1），移开又变回没换行的了（如2）。

**Comment by 88250** [comment]
v0.3.5 里做了一次修复，应该已经修复，谢谢反馈。
