### ISSUE TITLE
是否可以支持搜索支持繁体简体互通

### ISSUE THREAD

**Issue by gascarrier** [siyuan-note/siyuan#13304]
### In what scenarios do you need this feature?

目前情况是如果文章是繁体的，用中文搜索是搜索不到内容的。大神能否延伸支持一下简体繁体互通啊？就是搜索的时候输入的是简体的文字，同样可以搜索出繁体中文的结果。如果反过来搜索的是繁体的文字，同样也可以搜索出简体的结果呢？

### Describe the optimal solution

最好的结果是如描述中提到的，搜索的时候输入的是简体的文字，同样可以搜索出繁体中文的结果。如果反过来搜索的是繁体的文字，同样也可以搜索出简体的结果。

**Comment by 88250** [comment]
抱歉，这个支持不了。

**Comment by fujingzhai** [comment]
> 抱歉，这个支持不了。

D大，这个对我的场景来说也是刚需，我之前做了繁简体通用检索的插件，但还是希望能够原生支持。
就我所接触的常用软件来说，Notion、WPS、微信都是支持的。 MacOS的spotlight不支持，是被吐槽的一点。

实现起来应该非常简单，然后跟区分大小写一样加个选项按钮就行了。大多数中文用户都是简体字场景，无论是否区分，对他们的使用都毫无影响。

这两天我的Fable 5 和GPT 5.5额度都用不完，如果能做得还算可以的话，是否可以 PR 呢？

**Comment by 88250** [comment]
> 实现起来应该非常简单

说说你的思路

**Comment by TCOTC** [comment]
我想到的是单独加两个 FTS 表存纯简体和纯繁体，跟大小写敏感一样要打开开关才写入和查询。但问题是简繁体是一对多的关系，不同的地区用的繁体还不同，我想不到怎么索引。

**Comment by fujingzhai** [comment]
> > 实现起来应该非常简单
> 
> 说说你的思路


<img width="991" height="438" alt="Image" src="https://github.com/user-attachments/assets/af720eb0-1d9d-42a3-86e5-a42465469592" />

Fable 5 的回答。我自己还不太懂呀，不过我可以贡献算力，哈哈

**Comment by 88250** [comment]
看上去并不简单啊，要改分词器，不知道对性能的影响有多大，可以继续问问 ai。

**Comment by fujingzhai** [comment]
> 我想到的是单独加两个 FTS 表存纯简体和纯繁体，跟大小写敏感一样要打开开关才写入和查询。但问题是简繁体是一对多的关系，不同的地区用的繁体还不同，我想不到怎么索引。

J佬好，正好这方面是我的专业。

繁简体一对多，正常情况下是繁体多——简体一，对检索来说，完全不是什么问题。
繁体字转简体字基本上错误率很小，所以我平时的工作文字默认就是繁体字。

至于不同地区用的繁体字不同，这个问题也没有那么复杂。台湾只是用的词汇不同，正体字跟大陆繁体字本身是没有本质区分的，只是官方规范会有部分出入，可以忽略。至于那些复杂的异体字、俗体字，我们就不考虑了，毕竟输入法都未必能打出来。

对检索来说，就是无论我输入繁体字还是简体字还是繁简体字夹杂在一起，都能索引到结果。能达到这个效果就够了。

**Comment by fujingzhai** [comment]
> 看上去并不简单啊，要改分词器，不知道对性能的影响有多大，可以继续问问 ai。

<img width="985" height="742" alt="Image" src="https://github.com/user-attachments/assets/86b9c919-b66b-4e62-b3bb-01f20038c30f" />

**Comment by 88250** [comment]
思路应该是可行的，但要实际测试下性能影响。

**Comment by fujingzhai** [comment]
> 思路应该是可行的，但要实际测试下性能影响。

那我先开干试试 👀 纯 vibe coding 虽然自己玩一玩挺爽，但最多做做小插件，要到能给大家用的水平，还是要辛苦 D大 把关。

眼瞅着这两天Codex和Claude额度都快要重置了，不舍得这么浪费了。。。。。。

<img width="2032" height="1161" alt="Image" src="https://github.com/user-attachments/assets/f16ebe2a-b39e-4b2e-940e-a15e9be5504f" />

**Comment by 88250** [comment]
好的，你先试试，加油！

**Comment by fujingzhai** [comment]
<img width="2032" height="1161" alt="Image" src="https://github.com/user-attachments/assets/2d8dbf56-f6e2-41c7-8e2e-a761fd46fa2d" />
<img width="2032" height="1161" alt="Image" src="https://github.com/user-attachments/assets/ce496d22-c14d-4b39-aee4-8aac76e702d8" />

D大，效果是可以的，但性能影响不知道怎么判断。

**Comment by fujingzhai** [comment]
忘了让它改一下，改成“区分繁简体”，默认不打开。跟“区分大小写”保持一致。

**Comment by 88250** [comment]
性能我建议用重建索引测试，用大点的库（比如文字有 1kw 以上）的，让 ai 在重建索引里面加耗时日志。多跑几次看看耗时。

另外也可以问问 ai 有什么关于性能对比测试的建议。

**Comment by fujingzhai** [comment]
Fable 5 太猛了，它直接自己弄好都去浏览器测试完了，不过库比较小，现在只是功能实现了。

我接下来再让它干一下

**Comment by 88250** [comment]
对了，配置界面先不要动，因为我们正在重写配置界面 #17601 可以先改配置数据结构，加那个开关字段。

**Comment by fujingzhai** [comment]
> 对了，配置界面先不要动，因为我们正在重写配置界面 [#17601](https://github.com/siyuan-note/siyuan/issues/17601) 可以先改配置数据结构，加那个开关字段。

好

**Comment by TCOTC** [comment]
> 忘了让它改一下，改成“区分繁简体”，默认不打开。跟“区分大小写”保持一致。

“区分”是指什么行为？

**Comment by fujingzhai** [comment]
> > 忘了让它改一下，改成“区分繁简体”，默认不打开。跟“区分大小写”保持一致。
> 
> “区分”是指什么行为？

区分就是简体只能搜到简体，繁体只能搜到繁体。
不区分繁简体的情况下，搜“诗经”可以命中“诗经”“詩經”“诗經”“詩经”。
区分的情况下，“诗经”只能命中“诗经”。

**Comment by zxkmm** [comment]
> > 忘了让它改一下，改成“区分繁简体”，默认不打开。跟“区分大小写”保持一致。
> 
> “区分”是指什么行为？

打开：简繁体互相搜不到；关闭：简繁体可以互相搜到。类似大小写

**Comment by fujingzhai** [comment]
<img width="1020" height="536" alt="Image" src="https://github.com/user-attachments/assets/03dadedf-9c5d-499b-8734-b5eaf7adf261" />

D大，测试效果似乎还行。不过现在它的逻辑应该是反过来的，我觉得还是要跟“区分大小写”保持一致，用“区分繁简体”，而非“不区分”。

**Comment by 88250** [comment]
单独写个针对 sqlite3 的 go benchmark 再测一测。

**Comment by fujingzhai** [comment]
<img width="994" height="399" alt="Image" src="https://github.com/user-attachments/assets/d592939f-e913-4a4a-be4a-6c9f188aa8d8" />

似乎还行

**Comment by 88250** [comment]
插入和查询都要麻烦再测一下，用 benchmark，应该可以出个对比，改之前和改之后的对比。

**Comment by fujingzhai** [comment]
似乎结果也还不错，Claude 五小时额度到了，临时换上了GPT 5.5

<img width="780" height="494" alt="Image" src="https://github.com/user-attachments/assets/df0f7ae8-babb-4d60-9624-0f8f30131fd3" />

[REPORT.md](https://github.com/user-attachments/files/28844684/REPORT.md)

**Comment by fujingzhai** [comment]
<img width="1920" height="1050" alt="Image" src="https://github.com/user-attachments/assets/b9c3cffa-29b0-4b00-b333-03a3cc0358c4" />

我自己试了试，体验也是正常的。

**Comment by tcmtom** [comment]
哇，太好了

**Comment by 88250** [comment]
@fujingzhai 麻烦抽空 PR，谢谢！
