### ISSUE TITLE
在复制figure包裹的img 元素 粘贴转化后有问题

### ISSUE THREAD

**Issue by noenif** [siyuan-note/siyuan#13307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [ ] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [ ] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/0b01b10a-550a-4bfa-b66a-3156326c4828)
![image](https://github.com/user-attachments/assets/3aa37a9b-da4b-474a-937d-5840e0e0a08a)
如果没有figure就是正常的.

### Expected result

变成这样后就成功了
`![c04f001.eps](http://localhost:928/epub_book/About%20Face/OPS/image_fi/766576c04/c04f001.png "图 4-1: 需求定义流程概览")`

就是图 4-1: 需求定义流程概览这里多了一个换行符.可能是网页带的样式.但是在typroa中可以成功转换.

### Screenshot or screen recording presentation

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

### More information

无

**Comment by 88250** [comment]
请给一下网页地址

**Comment by noenif** [comment]
> 请给一下网页地址



直接在 这个`https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_figcaption`网站运行即可



问题代码:`  <figure>
    <img alt='c03f001.eps' class='center' src='https://www.w3schools.com/tags/pic_trulli.jpg' />
    <figcaption><p><a id='figure3-1' href='#figureanchor3-1'><b>Figure 3-1:</b></a> If you try to design an automobile
      that pleases every possible driver, you end up with a car with every possible feature that pleases nobody.
      Software today is too often designed to please too many users, resulting in low user satisfaction. <a
        id='figureanchor3-2' href='#figure3-2'>Figure 3-2</a> provides an alternative approach.</p></figcaption>
  </figure>
`
正常代码:`<figure>
  <img src="pic_trulli.jpg" alt="Trulli" style="width:100%">
  <figcaption>Fig.1 - Trulli, Puglia, Italy.</figcaption>
</figure>

`

**Comment by noenif** [comment]
> m

在typroa中
![image](https://github.com/user-attachments/assets/b580a063-d303-4158-828f-a2e412cd1806)
![image](https://github.com/user-attachments/assets/dd798199-1736-437b-89c6-092a9916a866)

**Comment by 88250** [comment]
请等下个 dev 版本发布后再测试看看，我先关闭了，如果还有问题，请跟帖。

**Comment by noenif** [comment]
> 我这里测试复制粘贴正常：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/390953647-43c18aec-9649-4889-b65d-f5d16df98880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NTMxODAsIm5iZiI6MTczMjg1Mjg4MCwicGF0aCI6Ii84NzM1ODQvMzkwOTUzNjQ3LTQzYzE4YWVjLTk2NDktNDg4OS1iNjVkLWY1ZDE2ZGY5ODg4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwNDAxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTQ5MzAwYjEyYjdhNjllNGM4ODE1MzIxMDJlZTRkMDI2NDRlNTQ3ZTQyZmViYWY1ODZlMDM3MGY5MDI5MjkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gD1nSMqLRQNmQ201rHItfEuz4ixYcrvunvd-LmPVT-E)

是一个问题代码,不是第二个正常代码.

**Comment by 88250** [comment]
我懂了，稍后确认并改进，感谢感谢。
