### ISSUE TITLE
需求：搜索可以检索父标题

### ISSUE THREAD

**Issue by 1696774082** [siyuan-note/siyuan#13302]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/eebe56eb-5d28-44c2-9e88-b43cbf3d16a0)

### Describe the optimal solution

none

**Comment by TCOTC** [comment]
关联 https://ld246.com/article/1732781725317

**Comment by 88250** [comment]
搜索结果只能定位到一个具体的块（如果是跨块关键字可以定位文档），无法定位父级或其他位置。

可以试试 SQL 搜索，加 type
