### ISSUE TITLE
数据库主键绑定块会显示出备注文本

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13308]
我觉得主键应该只显示绑定块的纯文本

![image](https://github.com/user-attachments/assets/66968861-e1f2-4e6e-a5c5-8f4477de4409)

**Comment by 88250** [comment]
这个只能这样了，和块引动态锚文本一样，等后面看看能不能实现静态锚文本吧 https://github.com/siyuan-note/siyuan/issues/10049
