### ISSUE TITLE
Linux桌面KDE下中键关闭标签页会粘贴剪贴板

### ISSUE THREAD

**Issue by Littleweisheit** [siyuan-note/siyuan#13309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

KDE有个特性选中即复制，然后中键粘贴。和ctrl c+v是不同的剪贴板。两者独立。
关闭标签页的同时，会粘贴剪贴板内容。我就奇怪，怎么会有多余内容。

### Expected result

关闭标签页

### Version environment

```markdown
- Version: 最新
- Operating System: KDE桌面环境
- Browser (if used):
```

### Log file

不需要

**Comment by Littleweisheit** [comment]
中键关闭标签页的时候不粘贴就好

**Comment by TCOTC** [comment]
这个是 Linux 的问题

**Comment by Littleweisheit** [comment]
> 这个是 Linux 的问题，不是思源的问题。
> 
> 不过监听中键不知道能不能阻止在 Linux 下的默认行为。

这是KDE的特性

**Comment by Menghuan1918** [comment]
> > 这个是 Linux 的问题，不是思源的问题。
> > 不过监听中键不知道能不能阻止在 Linux 下的默认行为。
> 
> 这是KDE的特性，其他软件关闭标签页并不会这样比如Kate

这实际上是X11的[PRIMARY剪贴板特性](https://wiki.archlinuxcn.org/wiki/%E5%89%AA%E8%B4%B4%E6%9D%BF)，思源关闭标签页会粘贴实际上是触发了这个剪贴板。

![图片](https://github.com/user-attachments/assets/07a4aa62-b951-45d8-8776-95c5721f337e)

不过VSCode的标签页不会触发，不知道是不是有额外设置什么，待各位大神探究了：

![图片](https://github.com/user-attachments/assets/a810e9a7-a93c-4df1-b0ed-2c8f6ca8e2a7)

**Comment by 88250** [comment]
研究了下不知道咋搞，暂时先关闭，如果有人知道的话麻烦 PR，多谢。

**Comment by TCOTC** [comment]
关联 https://github.com/siyuan-note/siyuan/pull/13395
