### ISSUE TITLE
命令面板搜索失败

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![PixPin_2024-11-30_00-59-58](https://github.com/user-attachments/assets/d8e611fb-ceab-4afe-bc06-2efd34205ab8)
始终只显示所有插件添加的命令

![PixPin_2024-11-30_01-01-38](https://github.com/user-attachments/assets/93dbf618-f87d-4308-b159-79783cc5ea54)

### Expected result

正常搜索

### Version environment

```markdown
- Version: v3.1.14 dev4
- Operating System:  win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
已修复，不拉进版本了。
