### ISSUE TITLE
Pls Provide Option to Allow Exporting in Publishing Service

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#13315]
### In what scenarios do you need this feature?

才注意到这条 issue： https://github.com/siyuan-note/siyuan/issues/12928

我试了下，还真的不让导出了。建议提供开关，允许用户设置是否允许导出。因为有的发布者就是希望读者能够下载已发布的内容，这样一刀切禁止下载欠妥。从另一方面讲，读者下载了内容，自然就会为了读取下载的文件而去安装思源软件，这无形中就增加了思源的用户数量。

### Describe the optimal solution

.

**Comment by 88250** [comment]
暂时不考虑了，谢谢。
