### ISSUE TITLE
按钮样式问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13317]
这个按钮看起来有点怪，鼠标没放上去会变灰，鼠标放上去再移开又不变灰了。我建议统一为鼠标在按钮上方才变灰：

[video.webm](https://github.com/user-attachments/assets/fdd85929-0864-4630-9587-21c91d9111b7)

**Comment by Vanessa219** [comment]
基于 https://github.com/siyuan-note/siyuan/issues/9857 ，还是保持移上去都变深。
