### ISSUE TITLE
【BUG】自动折叠BUG，小几率频点白屏

### ISSUE THREAD

**Issue by Ghost-Girls** [siyuan-note/siyuan#1331]
版本V0.6.7
且演示的GIF中也出现了上次所说的Ctrl+Z的大幅度的滚动。
希望定位一下BUG，早日在下一个版本中修复。

图片通过邮件回复

**Comment by zhaojiansong** [comment]
自动折叠的问题已经定位，实际是即时渲染模式由自动切换为预览模式。

**Comment by 88250** [comment]
你好，撤销的问题请关注 #1398 感谢反馈。
