### ISSUE TITLE
请求添加获取虚拟引用的API

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#13316]
### In what scenarios do you need this feature?

在某些情况下，想把虚拟用转化为引用。以及提取文本中的虚拟引用。

### Describe the optimal solution

目前的办法是从编辑器中获得虚拟引用，但需要先在编辑器刷新虚拟引用。
希望获得api：

1，批量把块的虚拟引用转化为引用。
2，批量把块的虚拟引用转化为链接。
3，通过批量的块 id 获得虚拟引用, 包括id以及content。
4,   通过文本获得虚拟引用。

**Comment by 88250** [comment]
一个关键词可能会对应多个引用定义块，所以需要用户手动搜索引用然后选择，所以 1、2 如果要做的话就得指定定义块 ID。

这个需求场景应该可以通过 https://github.com/siyuan-note/siyuan/issues/11238 解决，所以就不单独提供支持了，感谢反馈。
