### ISSUE TITLE
改进设置界面

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13320]
清理历史的按钮看起来像是个外链：

![image](https://github.com/user-attachments/assets/d2ce911d-c920-4046-a550-0ba750ed2cca)

像数据仓库清理就是把按钮和天数配置分开的：

![image](https://github.com/user-attachments/assets/9531efe7-4bb7-46fe-aa98-410d228a6498)

**Comment by Vanessa219** [comment]
不拉进版本了

**Comment by TCOTC** [comment]
文案我觉得可以再改一下：

![image](https://github.com/user-attachments/assets/5c762537-91f5-41e0-905d-01bba1c382fe)
