### ISSUE TITLE
表情选择器样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13322]
我这里点开之后默认会有一部分空白看起来不太好看：

![image](https://github.com/user-attachments/assets/1dd0f260-ceb1-4dd0-b964-c4b6abca1e6b)

**Comment by Vanessa219** [comment]
那以用户数较多的 Windows 用户为主吧，这个还得麻烦你看一下多少合适，代码位于

https://github.com/siyuan-note/siyuan/blob/ff7480a0fb1885edac1887b1fe1d925f2c18c684/app/src/emoji/index.ts#L253

**Comment by Vanessa219** [comment]
窄吧，动态图表也需要对于调整。

**Comment by TCOTC** [comment]
你和 D 那里是调到多少 px 合适？

**Comment by Vanessa219** [comment]
待会用 D 的电脑调整吧，我这里目前是合适的

![image](https://github.com/user-attachments/assets/9732a73d-ec8e-467d-871e-9005fa6cb510)

**Comment by TCOTC** [comment]
要不 Mac 和 Windows 用不同的宽度吧，Mac 的宽度不变

**Comment by Vanessa219** [comment]
宽度不一样，动态图标的大小也是需要调整的。还是保持一致吧。

**Comment by Vanessa219** [comment]
麻烦看看，不拉进 3.1.15 版本了

**Comment by TCOTC** [comment]
还行吧
