### ISSUE TITLE
反向链接提及页面

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#13324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在反向链接提及中
1. 列表会显示为 null
2. 每折叠一次会多显示一行
![image](https://github.com/user-attachments/assets/b01d6af8-b387-4cf1-b54e-7bcdbc4a7dd2)

https://github.com/user-attachments/assets/c6e8c7b5-bcb8-449f-a1be-ceed9ae83044

### Expected result

正常显示

### Version environment

```markdown
- Version: v3.1.14-dev5
- Operating System: Windows 24H2
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
@88250 这里还有个提及的问题你看看：https://ld246.com/article/1732166234911

**Comment by TCOTC** [comment]
好像是同一个问题。另外，我刚刚试了一下这个颜色看起来有点与众不同：

![image](https://github.com/user-attachments/assets/1194417f-e514-4e5f-ac96-ffc6670700a6)

**Comment by TCOTC** [comment]
还有全局搜索之后提及就没有高亮了：

[video.webm](https://github.com/user-attachments/assets/b6314ded-6e1e-49fd-a270-ebeabe7918f2)

**Comment by 88250** [comment]
> 这里还有个提及的问题你看看是不是同一个问题：https://ld246.com/article/1732166234911

是。

> 我刚刚试了一下这个颜色看起来有点与众不同：

第一个命中的颜色就是这样的了。

> 还有全局搜索之后提及就没有高亮了

是有点问题 @Vanessa219

**Comment by TCOTC** [comment]
> 第一个命中的颜色就是这样的了

能不能不命中

**Comment by 88250** [comment]
等 V 看下
