### ISSUE TITLE
拖动文档到数据库，文档添加到数据库失败

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

数据库为空，无法拖动文档添加到数据库
![PixPin_2024-12-02_14-50-05](https://github.com/user-attachments/assets/b4ad90d9-44a4-4831-82f2-b85a72282c71)
数据库有一个空白行，拖动文档，变成纯文本
![PixPin_2024-12-02_14-51-13](https://github.com/user-attachments/assets/f5ebdc7a-5641-4c3f-8ba1-adf45a64bd6e)

### Expected result

拖动文档到数据库，能将文档添加到数据库

### Screenshot or screen recording presentation

见上

### Version environment

```markdown
- Version: v3.1.4 dev6
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Achuan-2** [comment]
https://github.com/siyuan-note/siyuan/issues/13181
哦哦，现在是需要按住alt+drag才能拖动到数据库了

**Comment by Achuan-2** [comment]
另外现在拖动文档到某个文档，都没有高亮显示了，只有拖到数据库才有高亮显示，需要修复下

**Comment by 88250** [comment]
文档树上的拖拽做了点交互改变，这个就不再改回去了。

**Comment by Achuan-2** [comment]
> 文档树上的拖拽做了点交互改变，这个就不再改回去了。

单纯drag拖动文档到某个文档，没有高亮显示，能否加一个光标显示，
就像拖动文件到文档的效果一样

**Comment by 88250** [comment]
@Vanessa219

**Comment by TCOTC** [comment]
上个月说弄不出光标 https://github.com/siyuan-note/siyuan/issues/12857#issuecomment-2437743709

**Comment by TCOTC** [comment]
> https://github.com/siyuan-note/siyuan/issues/13181
> 哦哦，现在是需要按住alt+drag才能拖动到数据库了
> 希望用drag就能直接拖动到数据库，因为拖进数据库也是添加引用的一种形式
> 
> 

你那里拖不进去吗？应该改了的 https://github.com/siyuan-note/siyuan/issues/13181#issuecomment-2506579692
