### ISSUE TITLE
嵌套块的第一个块和最外层块的右侧命名，别名，数据库等属性重叠了

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#13333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/user-attachments/assets/c0bd82e5-c294-40d2-8c7f-c1d3d0bf0a97)

如图所示，嵌套块的第一个块和最外层块的右侧命名，别名，数据库等属性重叠了。

### Expected result

上下留点距离，不要重回在一块

### Version environment

```markdown
- Version: 3.1.11
- Operating System: mac windows都一样
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个目前是设计如此，在同一行的块只能这样属性角标了，无法错开显示，感谢反馈。

**Comment by TCOTC** [comment]
没什么好办法，只能尽量少用
