### ISSUE TITLE
移动端设置的手动同步为啥自动同步了

### ISSUE THREAD

**Issue by flowprog** [siyuan-note/siyuan#13337]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

云端设置那里是全手动的方式，只有打开退出才同步的，但是经常修改完后，就自动给我同步了。

### Expected result

没有手动点击的时候永远不要同步

### Version environment

```markdown
- Version: 最新
- Operating System: 安卓
- Browser (if used):
```

### Log file

no

**Comment by TCOTC** [comment]
复现不了。你能复现的话麻烦完整录屏演示。

**Comment by 88250** [comment]
这个理论上不会自己变的，如果能重现的话麻烦录屏，我先关闭了，欢迎随时补充重现步骤，感谢反馈。

**Comment by flowprog** [comment]
哦，我知道了，切换到其他APP，再切回来就会同步，放到后台这种情况也会当退出了对吧

**Comment by 88250** [comment]
对，Android 端切换应用会除非一次同步



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月4日(周三) 中午12:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 移动端设置的手动同步为啥自动同步了 (Issue #13337)




 
哦，我知道了，切换到其他APP，再切回来就会同步，放到后台这种情况也会当退出了对吧
