### ISSUE TITLE
Improve exporting block ref

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13331]
继续改进 https://github.com/siyuan-note/siyuan/issues/13283

* 改进导出范围计算（多选文档、块引用、块超链接涉及到的文档）
* 合并块引导出模式 脚注+锚点哈希

> @88250 发现一个bug，如果导出文档为pdf时，不设置导出文档标题，子文档引用父文档的链接会失效

**Comment by Achuan-2** [comment]
导出md的bug，两个块之前相互引用，导出块引为锚点哈希失败
导出pdf没有这个bug
测试文件
[20241203 19_12_44.sy.zip](https://github.com/user-attachments/files/17992192/20241203.19_12_44.sy.zip)

**Comment by Achuan-2** [comment]
markdown导出有问题

1. 只有锚点哈希的跳转链接，没有锚点了
2. 选择锚点哈希模式，导出块引是没有转换的

**Comment by Achuan-2** [comment]
如果块引添加了上标，希望变为锚点哈希也能保持上标样式

**Comment by 88250** [comment]
> markdown导出有问题
> 
> 1. 选择脚注模式导出md.zip文件，只有锚点哈希的跳转链接，没有锚点了
> 
> ![PixPin_2024-12-04_18-45-54](https://private-user-images.githubusercontent.com/60436214/392340656-d35053ec-9203-4fda-a031-aabb1c8b36e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NDgxNDQsIm5iZiI6MTczMzY0Nzg0NCwicGF0aCI6Ii82MDQzNjIxNC8zOTIzNDA2NTYtZDM1MDUzZWMtOTIwMy00ZmRhLWEwMzEtYWFiYjFjOGIzNmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDA4NTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDQwNDdhY2ViMmNhZjY0MzE3ZGY0MGI5ZDQzMzYwMWQ1OTgyZWMzZGJhZTY3Y2UzMjRmMDIyNjQwN2I3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w4tBXAY7fMK_Ahe3jXQ-IgKZ6He0pco9kYq9GbVCaEQ)
> 
> 2. 预览模式，选择锚点哈希模式，导出块引是没有转换的，脚注模式才转换，但是如1所说，只有锚点哈希的跳转链接，没有锚点了

锚点哈希模式已经和脚注模式合并为 脚注+锚点哈希 ，所以这个问题应该是不存在了，等发布新版麻烦测试。

**Comment by 88250** [comment]
> 导出md的bug，两个块之间相互引用，导出块引为锚点哈希失败

已经修复。

**Comment by 88250** [comment]
> 如果块引添加了上标，希望变为锚点哈希也能保持上标样式

已经改进。

**Comment by Achuan-2** [comment]
预览模式还有一点点问题
![PixPin_2024-12-09_11-47-04](https://github.com/user-attachments/assets/092b8800-475d-4e81-b194-6f42fc8796d1)

直接复制到语雀依然只有跳转链接，没有放锚点，导出md.zip是没有问题的

```markdown
# 20241209 11:43:56

‍

* [1](#20241209114356-ydng8dj)
* [2](#20241209114400-5ms4v6s)

## 1

## 2

```

**Comment by 88250** [comment]
我测试了下，语雀的 Markdown 不支持 `<span>` 标签，所以就算这里加了也没有用哦。

**Comment by Achuan-2** [comment]
> 我测试了下，语雀的 Markdown 不支持 `<span>` 标签，所以就算这里加了也没有用哦。

嗯，主要是复制到其他地方去，比如github或者其他markdown编辑器，不是为了复制到语雀，就不需要再单独导出了

用户如果不需要，再把块引锚文本切换为纯文本就行了

**Comment by 88250** [comment]
好的，我们先支持了看。

**Comment by Achuan-2** [comment]
ok，辛苦🙇‍♂️
