### ISSUE TITLE
Telegram reminder (or other messaging app reminder)

### ISSUE THREAD

**Issue by mindey** [siyuan-note/siyuan#13340]
### In what scenarios do you need this feature?

In SiYuan, there's "WeChat reminder" in the drop-down.
I happen to use Telegram, so I would need one.

### Describe the optimal solution

Make the "WeChat reminder" into generic "IM reminder" (i.e., instant messaging reminder), and allow user to define their favorite reminding option.

**Comment by 88250** [comment]
Hi, not considering support, thanks for the feedback.
