### ISSUE TITLE
Improve search highlighting

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13343]
继续完善 https://github.com/siyuan-note/siyuan/issues/13178

**Comment by Vanessa219** [comment]
* 历史
* 反链
* 搜索

**Comment by Achuan-2** [comment]
高亮颜色不一致
![PixPin_2024-12-09_09-46-48](https://github.com/user-attachments/assets/47d2becf-13fc-429b-a26a-e47713c6e38b)

**Comment by Achuan-2** [comment]
现在在搜索中点击块，可以看下个高亮项，但是这个交互有问题，太隐藏了，而且还不能点快，一旦点快，就打开块了

**Comment by Achuan-2** [comment]
搜索定位有问题，如果搜索的内容已经是命中了文档块，搜索面板里点击文档块里的子块，是不会跳转或者跳转不正确的

![PixPin_2024-12-09_10-05-08](https://github.com/user-attachments/assets/cc6585f1-b008-4b91-bc09-1784192b3510)

![PixPin_2024-12-09_10-05-41](https://github.com/user-attachments/assets/89e45c31-f6db-4531-90cb-246254a92708)

**Comment by Vanessa219** [comment]
搜索面板放不下按钮了，放在编辑器上的话有点不恰当。目前先这样
![image](https://github.com/user-attachments/assets/b856944a-72c6-4328-9404-fde4fde8b050)

其余两点已修改。

**Comment by Achuan-2** [comment]
可以在右上角放的，参考高亮搜索插件，其实占据不了多大空间的

**Comment by Vanessa219** [comment]
这个是全局搜索，放在编辑器内不有一点突兀。

**Comment by Achuan-2** [comment]
> 这个是全局搜索，放在编辑器内不有一点突兀。

不觉得突兀，全局搜索是搜索全部块，这个是在块里看每个命中，对于看文档块中的多个命中是很好用的，如果全局搜索有这个，就可以更方便看多个文档的命中情况。虽然思源搜索结果虽然会罗列所有命中的块，但是左侧的展现并不能展示多少文字，也不能展示所有命中，还是得到右侧的编辑区看具体的命中情况。其实这点就很像vscode的搜索体验，全局搜索可以搜索到相关的文件，打开文件里又可以进一步搜索

这个提案只是把跳转到下一个命中的功能凸显出来，更易用而已，不然当初为什么要做跳转到下一个命中的功能呢

**Comment by Vanessa219** [comment]
没太理解，是要在编辑器内部再加一个搜索按钮么？看了下 IDE 中并没有
![image](https://github.com/user-attachments/assets/e2046c1f-faad-4ad4-90ce-fd7fbf0b9779)

**Comment by Achuan-2** [comment]
> 没太理解，是要在编辑器内部再加一个搜索按钮么？看了下 IDE 中并没有 ![image](https://private-user-images.githubusercontent.com/970828/393864678-e2046c1f-faad-4ad4-90ce-fd7fbf0b9779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTUxNjQsIm5iZiI6MTczMzc1NDg2NCwicGF0aCI6Ii85NzA4MjgvMzkzODY0Njc4LWUyMDQ2YzFmLWZhYWQtNGFkNC05MGNlLWZkN2ZiZjBiOTc3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQxNDM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTJjM2JlMzE1MzZhZDM3M2QxMThiNDc0ZjU4ZmZlZmE4MTg3MzJhNDc5OWU5MjM3MWIyMTdjMjM5NDE2YThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.c8RS3W5oJtVSUNUCdLrbGcjxA3e1_7mQ3jqAmdz8guM)

VScode的界面是这样的
![PixPin_2024-12-09_22-34-06](https://github.com/user-attachments/assets/0d3e52f9-d53b-45a5-9fa3-7804195dfa8c)

我只是解释全局搜索和单页面搜索并不冲突，是可以一起互补的

思源可以在现在的基础上，先做前一个按钮和后一个按钮

**Comment by Vanessa219** [comment]
编辑器内搜索目前好像有插件了。全局搜索中的下一个放置位置还需要在考虑一下。如果放到编辑器内，不仅突兀，操作也不方便，间隔的太远了。
![image](https://github.com/user-attachments/assets/922e5d85-8c10-49af-aada-5cb52156deb9)

**Comment by Vanessa219** [comment]
太远了，没有先走点击行方便。鼠标需要滑动来滑动去的。

**Comment by Achuan-2** [comment]
> 太远了，没有直接点击行方便。鼠标需要滑动来滑动去的。

问题是直接点击的交互是有问题的，误触了就跳转，也容易变为双击打开

左侧本来连内容都放不下，也塞不下按钮

也只能放在编辑器区了

我觉得一般用跳转的场景是，现在全局搜索找到可能的几个块，然后再右侧看有几个高亮跳转，只有几个高亮的用不到高亮跳转功能，有很多高亮的，目前一个个点击块来跳转太累，速度还不能快，不如右侧添加按钮来得实际

鼠标需要滑动来滑动去的问题对我而言并没有什么，反而能引导我专注在当前块里

**Comment by TCOTC** [comment]
同一个块内的关键词应该不会太多，点几下就够了

**Comment by Achuan-2** [comment]
> 同一个块内的关键词应该不会太多，点几下就够了

一个块的就不需要高亮跳转了，只有文档块才需要

**Comment by Vanessa219** [comment]
要不按住 ctrl 点击，就可以阻止打开了？

**Comment by TCOTC** [comment]
太怪了
