### ISSUE TITLE
希望页签栏支持更快速复制粘贴块链接的方式

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#13344]
### In what scenarios do you need this feature?

我的应用场景是：
假设页签 A-Z 都是打开的，即同时在整理这多个文档。
由于有时候两个页签在文档树上跨距很大，为了将页签 A 的链接插入到页签 B 对应的文档，目前的操作显得有的笨拙，先在页签 A 上右键，弹出菜单，移动1秒钟，找到复制，然后再进去点击复制链接，然后再去 B 中粘贴。大约需要4-5秒钟满城。

文档树上虽然支持 Alt-拖放，但是查看文档 B 时，由于跨距大，文档树上看不到文档 A 的节点，所以无法使用。

在设置>快捷键>通用大类下面，有关闭页签等快捷键可设置，但是没有复制（及其子项）。
虽然右键点击页签可以找到复制，但是位置靠下，需要移动很长距离，非常不方便。

### Describe the optimal solution

方法1：Alt+Shift-拖动直接实现粘贴块链接 (因为 Alt-拖动已经用于拖动页签进行布局)，或者 Ctrl-Alt-拖动，Ctrl-Shift-拖动，等等都可以。

### Describe the candidate solution

方法2：页签的右键菜单允许排序，可将复制项移动到上面（例如长按拖动调节顺序）。或者支持用户自定义菜单，如默认展开复制的几个子项。说实话，关闭页签的菜单我反而不常用。

方法3：为鼠标停靠的页签提供热键快速复制块链接。这个可以由用户自定义。

**Comment by TCOTC** [comment]
我觉得可以在这里支持用右键菜单：

![image](https://github.com/user-attachments/assets/042db749-ee76-4edd-ae03-8d2c6dcbb4af)

以及支持拖拽排序：#12329

**Comment by jabobian** [comment]
我觉得你的理解和我提的问题完全不是同一件事情，惭愧。

**Comment by TCOTC** [comment]
你提的操作方法有点小众了，我觉得可以基于目前的交互进行改进

**Comment by jabobian** [comment]
复制在右键菜单的第8项，距离确实太远了。或者提供一个设置选项，允许将关闭的菜单折叠。前两个方案要改主程序不好实现，但第3个方案可以用插件做，各位高手，可否为鼠标停靠的页签提供热键快速复制块链接。

**Comment by TCOTC** [comment]
可以用 CSS 把不需要用的按钮隐藏

**Comment by 88250** [comment]
这个不考虑了，插件也许可以定制。
