### ISSUE TITLE
移除编辑器输入日志

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#13346]
![image](https://github.com/user-attachments/assets/40983393-2229-4f13-98c1-2cb631b497e1)
v3.1.14  每次打开开发者工具，都会打印一些内容块。  希望能有选项关掉。

**Comment by TCOTC** [comment]
这个确实

**Comment by wish5115** [comment]
其实没用的，即使官方不输出，插件里也会输出一堆

**Comment by IAliceBobI** [comment]
主要是我开发插件要看。
我的插件不输出这些。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 晚上6:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 每次打开开发者工具，都会打印一些内容块。  希望能有选项关掉。 (Issue #13346)




 
其实没用的，即使官方不输出，插件里也会输出一堆

**Comment by wish5115** [comment]
> 主要是我开发插件要看。 我的插件不输出这些。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月3日(周二) 晚上6:27 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 每次打开开发者工具，都会打印一些内容块。 希望能有选项关掉。 (Issue #13346) 其实没用的，即使官方不输出，插件里也会输出一堆 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

<img width="685" alt="image" src="https://github.com/user-attachments/assets/0ee09786-d6c7-43a4-addc-da180a60aab5">

过滤下就好了，官方输出的是就牛一毛而已，仅仅官方去掉输出解决不了你的问题。

**Comment by TCOTC** [comment]
不影响，还是去掉更好

**Comment by TCOTC** [comment]
@Vanessa219 拖动开发者工具输出的这个能不能也去掉：

![image](https://github.com/user-attachments/assets/7b504415-53a5-4a80-ac82-f2dbcd51f278)

**Comment by Vanessa219** [comment]
这个我的不会输出

**Comment by TCOTC** [comment]
这个：

https://github.com/siyuan-note/siyuan/blob/914c7659388e645395e70224f0d831950275eb05/app/src/protyle/util/resize.ts#L26

**Comment by wish5115** [comment]
建议搞个全局函数，然后判断仅开发环境输出

**Comment by TCOTC** [comment]
我希望开发环境也去掉，因为我一直用的都是开发环境🫠

**Comment by IAliceBobI** [comment]
一些打包工具可以去掉js中的输出的。

**Comment by wish5115** [comment]
> 我希望开发环境也去掉，因为我一直用的都是开发环境🫠

哦哦，不要小看console.log，如果在循环里，且数据量大的话，这个输出直接让性能断崖式下降，毕竟是io操作。
