### ISSUE TITLE
Improve template search

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13348]
### In what scenarios do you need this feature?

![PixPin_2024-12-03_12-07-40](https://github.com/user-attachments/assets/59409264-4780-41bc-81d4-665bcbd3b3f1)
目前模板搜索并不支持搜索文件夹
![PixPin_2024-12-03_12-08-04](https://github.com/user-attachments/assets/0a26f6e5-1c66-4689-a91a-445af9deab6a)

### Describe the optimal solution

模板搜索支持搜索文件夹

### Describe the candidate solution

无

**Comment by 88250** [comment]
顺便支持空格分隔 AND 搜索
