### ISSUE TITLE
关联字段弹窗需要限制最大宽度

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13359]
https://ld246.com/article/1733232337232

![image](https://github.com/user-attachments/assets/9694ae56-4c52-42a9-8922-371714f8d55e)

**Comment by Vanessa219** [comment]
不拉进版本了

**Comment by TCOTC** [comment]
过长的条目需要加上悬浮提示

**Comment by Vanessa219** [comment]
这个用的是 css ，js 不太好判断是否过长

**Comment by TCOTC** [comment]
[`88a3ffc` (#13476)](https://github.com/siyuan-note/siyuan/pull/13476/commits/88a3ffc488f5d238f3d02baefb0332cd1b15c92f)
