### ISSUE TITLE
有序列表缩进样式不美观

### ISSUE THREAD

**Issue by MACDfree** [siyuan-note/siyuan#1335]
### 描述问题 Describe the problem
目前笔记有序列表缩进样式为2em，我看了一下github上其实也是这样的。但是，由于github上有序列表的序号是不算在这2em之内的，所以整体效果还行。而笔记中的序号则是也算在2em之内的，导致看上去缩进太多。

### 期待的结果 Expected result
参照主流编辑器的样式风格改进

### 截屏或录屏演示 Screenshot or screen recording presentation
本笔记中

![image](https://user-images.githubusercontent.com/3363410/106165822-74725180-61c6-11eb-82c8-755e7f632edc.png)

Typora

![image](https://user-images.githubusercontent.com/3363410/106165925-953aa700-61c6-11eb-87ae-7688d9be6323.png)

github

![image](https://user-images.githubusercontent.com/3363410/106165999-ad122b00-61c6-11eb-899e-59db6109ae89.png)

### 版本环境 Version environment

* 版本 Version：0.6.8
* 操作系统 Operating system：windows 10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，这应该是社区主题吧，请给主题仓库提 issue 谢谢。
