### ISSUE TITLE
Improve system font loading

### ISSUE THREAD

**Issue by Mctalos** [siyuan-note/siyuan#13356]
关于字体设置、导出PDF的问题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

问题一：思源笔记如果 外观设置为 英文，在字体设置中，就找不到汉字字体，比如思源宋体、思源黑体等。
需要将外观设置改为中文→编辑器字体设置为思源宋体→外观设置为英文。当然不是啥大问题，但是我习惯系统、软件都是英文，工作文档当然得用中文了。其他很多软件比如office，界面显示语言不影响字体设置，可以显示中文字体的。
<img width="1057" alt="20241203_21-41-32" src="https://github.com/user-attachments/assets/4263546c-356a-4d30-9fb1-b854b2dfaeb8">

问题二：如果编辑器字体设置为思源宋体，那么在导出PDF的时候，就不显示文字了，如下图所示。疑似没有在PDF中嵌入字体文件所致？

<img width="408" alt="20241203_20-18-04" src="https://github.com/user-attachments/assets/4cef5154-71ad-45c0-bcb9-4ec0f5d4644b">
<img width="586" alt="20241203_20-25-40" src="https://github.com/user-attachments/assets/7e00ff6a-fe41-42d9-a89c-1b0ce9981b61">

### Expected result

如果在导出PDF中嵌入编辑器设置的字体

### Version environment

```markdown
- Version: v3.1.14
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/17992825/siyuan.log)

**Comment by Mctalos** [comment]
> 思源宋体和思源黑体是你自己安装的吗？
> 
> 我这里复现不了

是的呀，字体已经确认安装到系统了。
思源编辑器里能看到，其他软件也是能识别的。导出PDF不显示文字。

<img width="673" alt="20241203_21-37-39" src="https://github.com/user-attachments/assets/ffa04d22-0ac0-4791-9511-b2b18d163abc">
<img width="815" alt="20241203_21-37-02" src="https://github.com/user-attachments/assets/aa21a942-65dd-4176-a846-d857d47f5775">

**Comment by 88250** [comment]
* 问题 1 稍后改进
* 问题 2 我这里也重现不了
