### ISSUE TITLE
Generating block reference with a block that has ' character is causing weird behaviour

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#13358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

If the block has the character `'` then it is causing weird behaviour while creating block reference. Please check the video below

### Expected result

Creating block reference should be normal

### Screenshot or screen recording presentation

https://github.com/user-attachments/assets/384caa78-c593-4cf1-b340-fe632c4c3941

### Version environment

```markdown
- Version: 3.1.14
- Operating System: Windows 11
- Browser (if used):
```

### Log file

I 2024/12/03 18:02:04 working.go:147: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/12/03 18:02:04 runtime.go:87: kernel is booting:
    * ver [3.1.14]
    * arch [amd64]
    * os [Microsoft Windows 11 Home Single Language]
    * pid [9620]
    * runtime mode [prod]
    * working directory [C:\Users\<redacted>\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\<redacted>\Vaults\SiYuan Test]
I 2024/12/03 18:02:04 conf.go:169: initialized language [en_US] based on device locale
I 2024/12/03 18:02:04 runtime.go:139: use network proxy [system]
I 2024/12/03 18:02:04 serve.go:209: kernel [pid=9620] http server [127.0.0.1:53641] is booting
I 2024/12/03 18:02:04 blocktree.go:75: reinitialized database [C:\Users\<redacted>\Vaults\SiYuan Test\temp\blocktree.db]
I 2024/12/03 18:02:04 database.go:92: the database structure is changed, rebuilding database...
I 2024/12/03 18:02:04 database.go:109: reinitialized database [C:\Users\<redacted>\Vaults\SiYuan Test\temp\siyuan.db]
I 2024/12/03 18:02:04 conf.go:851: database size [4.1 kB], tree/block count [0/0]
I 2024/12/03 18:02:04 working.go:193: kernel booted
I 2024/12/03 18:02:04 box.go:77: auto stat [trees=0, blocks=0, dataSize=36.87 kB, assetsSize=0 B]
I 2024/12/03 18:02:04 disk.go:33: disk usage [total=511.3 GB, used=79.31 GB, free=432 GB]
I 2024/12/03 18:02:07 index.go:220: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.07s], tree [count=67, size=1.32 MB]
I 2024/12/03 18:02:07 index.go:290: resolved refs [36] in [103ms]
I 2024/12/03 18:02:15 mount.go:65: created box [20241203180215-udcu0aw]
I 2024/12/03 18:02:15 index.go:220: rebuilt database for notebook [20241203180215-udcu0aw] in [0.00s], tree [count=0, size=0 B]
I 2024/12/03 18:02:16 index.go:290: resolved refs [36] in [49ms]
I 2024/12/03 18:02:18 pandoc.go:186: initialized built-in pandoc [ver=3.5, bin=C:\Users\<redacted>\Vaults\SiYuan Test\temp\pandoc\bin\pandoc.exe]
I 2024/12/03 18:02:18 conf.go:1113: pandoc initialized, set pandoc bin to [C:\Users\<redacted>\Vaults\SiYuan Test\temp\pandoc\bin\pandoc.exe]
I 2024/12/03 18:03:08 file.go:1728: removed doc [20241203180215-udcu0aw/20241203180218-ugeswhy.sy]

**Comment by TCOTC** [comment]
There is also a problem here:

[video.webm](https://github.com/user-attachments/assets/a373461e-6740-4461-8916-6f7350064c13)
