### ISSUE TITLE
No results found after clicking on the inline tag

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#13351]
点击行内标签后搜索结果为空

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![2](https://github.com/user-attachments/assets/a81d1c45-0ec9-45a9-8a31-5d6a6bae3495)

### Expected result

修复

### Version environment

```markdown
- Version: v3.1.14
- Operating System: win10
- Browser (if used):
```

### Log file

1

**Comment by Hzz-0802** [comment]
点刷新按钮也没用，只有在标签面板点击才有搜索结果。

**Comment by TCOTC** [comment]
1. 标签没有高亮
2. 搜索定位不到标签所在的块

**Comment by 88250** [comment]
> 1. 标签没有高亮
> 2. 搜索定位不到标签所在的块

在 https://github.com/siyuan-note/siyuan/issues/13343 中改进。

**Comment by TCOTC** [comment]
@88250 我这里还是搜不到标签

[video.webm](https://github.com/user-attachments/assets/dfe18340-8ac8-4ceb-b5b1-e573486ab020)

**Comment by 88250** [comment]
等下个 dev 版再试试。

**Comment by TCOTC** [comment]
现在可以了
