### ISSUE TITLE
html标签的批量替换存在问题

### ISSUE THREAD

**Issue by davincilll** [siyuan-note/siyuan#13354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/34b5308d-5947-402c-87c5-f547c8d70792">
所有的选择项都打开了，这个不能匹配的问题令人无法理解
https://ld246.com/article/1715778551878
该帖不能解决我的问题

### Expected result

正确匹配高亮

### Version environment

```markdown
- Version: 最新
- Operating System: mac
- Browser (if used): no
```

### Log file

without

**Comment by TCOTC** [comment]
文档导出上传看看

**Comment by davincilll** [comment]
> 文档导出上传看看

[1. 概览.md](https://github.com/user-attachments/files/17992748/1.md)

**Comment by TCOTC** [comment]
确实，我这里再多一个 `"` 就不行了

![image](https://github.com/user-attachments/assets/4a19081b-00cc-4ab6-903d-11e282b1c265)

![image](https://github.com/user-attachments/assets/099eae16-a682-477b-ae57-e1e4cde266ac)

**Comment by TCOTC** [comment]
@88250 是不是支持不了单引号？

![image](https://github.com/user-attachments/assets/6c25c48a-a0eb-40cf-9eda-89ea5edcf46e)

**Comment by 88250** [comment]
可以支持，稍后改进。

**Comment by davincilll** [comment]
> 可以支持，稍后改进。

我这里更新到新版本后，一定程度上解决了我的问题，但是现在好像依然还是存在一些新的问题，比如在某些块中的虽然可以被查询到，但是无法替换，即时我打开了所有的选项。

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/9d9b58e4-6dec-42ea-a8df-89efd5ac3a01" />

我进行了替换但是没有实际的替换效果

**Comment by TCOTC** [comment]
@davincilll 替换类型开了吗？

![image](https://github.com/user-attachments/assets/064cc76f-545c-4881-a0dc-c3d8144ec305)

**Comment by 88250** [comment]
行级代码的替换还有点问题，下个版本继续解决，感谢反馈。
