### ISSUE TITLE
PDF 浏览界面优化

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1336]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

1. 当前翻页功能太弱并且直接输入页面跳转存在问题。
2. 当前PDF部分的UI不符合思源的整体UI风格，过于突兀并且不美观。

![image](https://user-images.githubusercontent.com/47321059/106169213-17789a80-61ca-11eb-88b4-e4986a8a0f93.png)

**Comment by 88250** [comment]
页面跳转在 v0.6.8 #1307 中完成了；UI 后续改进，谢谢提议。
