### ISSUE TITLE
【docker】💔 思源笔记遇到了一点问题... v3.1.14 你的数据应该是安全的

### ISSUE THREAD

**Issue by tofch** [siyuan-note/siyuan#13369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

💔 思源笔记遇到了一点问题... v3.1.14
你的数据应该是安全的，请检查网络连接和内核进程是否正常，然后重新启动思源笔记
如果仍然出现该问题，请在[这里]寻求帮助或者报告缺陷

问题在3.1.13上也出现，触发情况随机，可能在输入时，也可能在浏览笔记时。
docker日志里没有异常

### Expected result

smoothly run...

### Version environment

```markdown
- Version: 4.1.13, 4.1.14
- Operating System: ubuntu 20.4 / debian12.8
- Browser (if used): chromium, firefox
```

### Log file

2024/12/04 22:12:50 runtime.go:87: kernel is booting:
    * ver [3.1.14]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/12/04 22:12:50 conf.go:130: loaded conf [/siyuan/workspace/conf/conf.json]
I 2024/12/04 22:12:50 conf.go:288: upgraded from version [3.1.13] to [3.1.14]
I 2024/12/04 22:12:50 conf.go:511: user has disabled [Google Analytics]
I 2024/12/04 22:12:50 runtime.go:139: use network proxy [system]
I 2024/12/04 22:12:50 serve.go:209: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/12/04 22:12:50 conf.go:851: database size [9.56 MB], tree/block count [11/670]
I 2024/12/04 22:12:50 working.go:193: kernel booted
I 2024/12/04 22:12:50 box.go:77: auto stat [trees=11, blocks=670, dataSize=4.99 MB, assetsSize=4.7 MB]
I 2024/12/04 22:15:30 session.go:121: auth success [ip=192.168.6.6:52264]
I 2024/12/04 22:15:30 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36]
I 2024/12/04 22:20:46 session.go:121: auth success [ip=192.168.6.6:48288]
I 2024/12/04 22:21:48 session.go:121: auth success [ip=192.168.6.6:57280]
I 2024/12/04 22:21:48 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36]

**Comment by 88250** [comment]
建议排查网络，可以使用时在浏览器端打开开发者工具观察 Network 请求，如果 WebSocket 断开的话会报这个错。

**Comment by tofch** [comment]
我在局域网内使用docker；可能影响的程序是v2rayN，但已经设置了直连lan的路由。

典型的错误是这样的：
`WebSocket connection to 'ws://192.168.6.22:6806/ws?app=wr0wn&id=3b748102-5401-43c4-b891-0c7d67f6c01d&type=filetree' failed: `

`main.d92a2ab….js:16 WebSocket is closed. Reconnect will be attempted in 3 second. 
CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}
isTrusted
: 
true
bubbles
: 
false
cancelBubble
: 
false
cancelable
: 
false
code
: 
1006
composed
: 
false
currentTarget
: 
WebSocket {url: 'ws://192.168.6.22:6806/ws?app=wr0wn&id=3b748102-5401-43c4-b891-0c7d67f6c01d&type=filetree', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
defaultPrevented
: 
false
eventPhase
: 
0
reason
: 
""
returnValue
: 
true
srcElement
: 
WebSocket {url: 'ws://192.168.6.22:6806/ws?app=wr0wn&id=3b748102-5401-43c4-b891-0c7d67f6c01d&type=filetree', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
target
: 
WebSocket {url: 'ws://192.168.6.22:6806/ws?app=wr0wn&id=3b748102-5401-43c4-b891-0c7d67f6c01d&type=filetree', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}
timeStamp
: 
326955.59999996424
type
: 
"close"
wasClean
: 
false
[[Prototype]]
: 
CloseEvent`

ISSUES：
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

AFFECTED RESOURCES:
main.d92a2ab….js:16

**Comment by 88250** [comment]
非 Chrome 内核浏览器目前无法兼容，我们后面看下是否能搞定，不好意思。

**Comment by tofch** [comment]
啊 我以为是firefox才有问题。现在上面打不开笔记。
我测试了不同os的代理设置。认为是debian12的手动代理会发生此错误； macos上设置代理后一切正常。

**Comment by zagger-crypto** [comment]
我也出现这种问题，我是在编辑器中粘贴代码时会出现，粘贴的文本多一点就会出现这个弹窗
![image](https://github.com/user-attachments/assets/4b015446-ecab-450e-b2dd-5b66811310ba)

**Comment by 88250** [comment]
@zagger-crypto 看下内核日志是不是报错了，如果是的话再测试下桌面端应用程序是否能重现该问题。
