### ISSUE TITLE
auto indentation and autocomplete punctuation in code blocks, text, and formulas

### ISSUE THREAD

**Issue by sophlzy3** [siyuan-note/siyuan#13363]
### In what scenarios do you need this feature?

daily notetaking and writing as this is a crucial feature for productivity

### Describe the optimal solution

Code Blocks
- applies to for/while loops, functions, if/elif/else
- automatically create an indent when hit ENTER if needed 
- put in "end" if an end is required by the loop

> for example: MATLAB
> `def function():` should be automatically completed by 
> ```matlab
> end
> ```
> the function should look like this:
> ```
> def function():
>
> end
> ```
> the cursor should be put in the second line, between `def` and `end`

Text
- place the cursor in the middle of the brackets, such as
    - English punctuations: `"`,` <`, `(`, `[`, `{`, `, etc.
    - Code fence: ``` or ` 
    - Foreign languages (eg Chinese): `（`, `”`, `《`, `「`, `【` , etc.

Formulas
- complete `$` for inline formulas and `$$` for formula blocks
- complete `\begin{}` with `\end{}`

**Comment by 88250** [comment]
We are not considering improvements for the time being. Please consider using the auto-completion that comes with the input method (but it is not compatible with some input methods).

The formula part can currently use plug-ins, thank you.
