### ISSUE TITLE
数据库视图增加 emoji 图标显示选项的建议如何？

### ISSUE THREAD

**Issue by songshua295** [siyuan-note/siyuan#13379]
### In what scenarios do you need this feature?

数据库视图在数据比较多的情况下，图标比文字**更具有识别性**。 

 **如果你也需要此特性，请点击这个[投票](https://ld246.com/article/1733404760820)**

请看jpeg：
![image](https://github.com/user-attachments/assets/c8f87d33-1c79-4744-98dd-46d4697a5cb3)
加图标之后
![image](https://github.com/user-attachments/assets/e8c692f7-e803-4c0e-a8a4-3fe2ba6fe69a)

### Describe the optimal solution

摆手不是不要，而是无需多言。
![05313836](https://github.com/user-attachments/assets/cc96b064-7e8e-4113-b087-62bb9c849295)

### Other information

建议是增加开关选项，增加用户可选项。

因为不是每一种数据库都需要此图标，有的数据库过多图标，会增加用户添加图标的成本，同时还可能减少信息量。

**Comment by TCOTC** [comment]
Duplicate of #13378
