### ISSUE TITLE
Formatting a word selected by double-click should not format the space after

### ISSUE THREAD

**Issue by Djobydjoba** [siyuan-note/siyuan#13372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Select a word in a middle of a sentence by double-clicking on it. The space after the word is selected with the word too, that seems OK (Microsoft Word does the same. But that depends on the program though). But what is not OK is that if you apply a formatting to the selection with the formatting pop-up bar (bold, italic, underline, strike, keyboard or whatever) , the formatting is applied to the space after the word too. This is not OK to have the space underlined, strikethrough, in bold or whatever. Again, compare here with with Microsoft Word, it has the good behavior.

### Expected result

After a string has been selected **by double-clicking on it**, the formatting applied should be be applied to the space after when it has been automatically included in the selection.
When the selection is done manually without double-clicking on a string, it is OK though to apply the formatting to the entire selection, even to the spaces.

### Version environment

```markdown
- Version: 3.1.14
- Operating System: Windows 10 Pro x64
- Browser (if used): not used.
```

### Log file

[system-log.zip](https://github.com/user-attachments/files/18013644/system-log.zip)

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/12944
