### ISSUE TITLE
The database primary key field displays the icon of the bound doc

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13378]
数据库主键字段显示绑定文档的图标

https://ld246.com/article/1733404760820

Notion FlowUs Wolai 是默认显示图标的，确实有使用场景

**Comment by HibernalGlow** [comment]
用了动态图标功能 需求更强了

**Comment by 88250** [comment]
加开关好像没有必要吧？要支持的话就直接支持了。

**Comment by TCOTC** [comment]
因为我不太需要显示图标，一部分条目有图标一部分条目没图标会让强迫症很不爽

**Comment by 88250** [comment]
不加开关了，可以用 CSS 片段取消。

**Comment by TCOTC** [comment]
需要支持点击修改文档图标：

![image](https://github.com/user-attachments/assets/b3bec850-ed42-4399-882f-06b65b37f8f4)
