### ISSUE TITLE
关于标签页不能打开的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1337]
### 描述问题 Describe the problem

文件的标签页不能打开，控制台报错和标签页无法关闭报错相同。

此前的操作是删除了无法关闭的标签页的`<li></li>`

在重启思源和重置窗口后恢复正常

### 截屏或录屏演示 Screenshot or screen recording presentation

![ew1](https://user-images.githubusercontent.com/47321059/106169847-cae18f00-61ca-11eb-88e6-60d58673d44d.gif)

### 版本环境 Version environment

* 版本 Version：0.6.7
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，请升级到 v0.6.8，谢谢。

**Comment by dejavudwh** [comment]
好的 ，刚刚没有检查更新，不好意思D大。

**Comment by dejavudwh** [comment]
晚安
