### ISSUE TITLE
浮窗的「上下文」效果不一致

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

一个小问题，鼠标悬浮在文档树旁边的引用计数器，所得到的浮窗，其中「上下文」功能似乎有点异常。
![image](https://github.com/user-attachments/assets/992c6e26-74a1-4339-8b5c-24515a20372b)

[20241204232836.webm](https://github.com/user-attachments/assets/94cdffe3-7eb0-4722-8a24-2675b617d57c)

- 视频里第一个浮窗，是在反链面板中  hover面包屑块标 得到的浮窗，点击「上下文」可以正确的切回聚焦。
  第二个是hover文档树引用计数器得到的浮窗，点击「上下文」直接切到段落上去了。

### Expected result

「上下文」的功能效果，应当和反链中打开的浮窗一致。

### Version environment

```markdown
- Version: 3.1.14
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
引用计数使用的是 `api/block/getRefIDs` 获取的块 id，引用使用的是被引用的 id，两个块的 id 是不一致的。

视频中的浮窗一个是块，一个是列表项。所以是不一致的。

**Comment by cordinGH** [comment]
就是感觉怪怪的，按理说双击了“上下文”，不是应该恢复为原样吗

**Comment by 88250** [comment]
拍查了下是因为 https://github.com/siyuan-note/siyuan/issues/6853 上实现的问题，稍后调整，感谢反馈。
