### ISSUE TITLE
Attribute panel - Database supports removing the current block

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#13375]
在属性面板数据库界面增加“移出数据库”按钮

### In what scenarios do you need this feature?

将块添加到数据库后，如果要将其从数据库中移出，需要如下步骤：

1. 点击块右上角的数据库图标
2. 在数据库界面点击数据库名称
3. 在镜像数据库浮窗中选择其中一个镜像数据库
4. 在镜像数据库中找到当前块所在行
5. 删除该行

太麻烦了！

### Describe the optimal solution

在数据库界面中增加一个“移出数据库”的按钮就会方便很多，如下图：
![image](https://github.com/user-attachments/assets/9ae3f8d9-9662-476f-b899-24ff79e32d54)

操作步骤将简化为：
1. 点击块右上角的数据库图标
2. 在数据库界面点击“移出数据库”按钮

完工！

**Comment by Jiangshuon** [comment]
顶！！

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/10581

**Comment by TCOTC** [comment]
有了 SuperTag 的用法之后，确实还需要一个不打开数据库就能删除条目的办法

**Comment by Achuan-2** [comment]
➕1

**Comment by 5kyfkr** [comment]
支持，现在要删除还要进去数据库翻找，比较难受

**Comment by HibernalGlow** [comment]
好评

**Comment by TCOTC** [comment]
@Vanessa219 浮窗的触发区域应该与文本宽度一致，否则感觉太怪了

![image](https://github.com/user-attachments/assets/842b5d16-3a39-4fd0-a91f-d17372e5fce3)
