### ISSUE TITLE
can ollma be used in siyuan？

### ISSUE THREAD

**Issue by 1caiji23** [siyuan-note/siyuan#13377]
### In what scenarios do you need this feature?

i want to use local ollama，rather than openai，because openai is unable to china 

### Describe the optimal solution

i have no idea

**Comment by kingbluetooth** [comment]
You can achieve this very easily:

1. Run Ollama

Now in Siyuan Notes under AI settings:

2. Set AI provider to **OpenAI**
3. Set model name to the name of the Ollama model i.e: **llama3.2:1b**
4. Set API Key to **abc**
5. Set API base URL as **http://localhost:11434/v1**
6. Now use AI in your notes

**Comment by 1caiji23** [comment]
> 您可以非常轻松地实现这一点：
> 
> 1. Run Ollama
> 
> 现在在 AI 设置下的思源笔记中：
> 
> 2. 将 AI provider 设置为 **OpenAI**
> 3. 将 model name 设置为 Ollama 模型的名称，即：**llama3.2：1b**
> 4. 将 API Key 设置为 **abc**
> 5. 将 API 基 URL 设置为 **http://localhost:11434/v1**
> 6. 现在在您的笔记中使用 AI

thank you
