### ISSUE TITLE
issue #13381 续

### ISSUE THREAD

**Issue by LSkittles** [siyuan-note/siyuan#13384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

#13381 https://github.com/siyuan-note/siyuan/issues/13381。

我直接从 OSS 的控制台拉取了云端文件，与思源本地的 repo 对比了一下，发现思源本地的 repo 缺少很多文件。
![repo-objects-00](https://github.com/user-attachments/assets/b38acdbe-d6be-49e0-96f5-53109fcedaaa)

因此**云端数据损坏**的真实原因是否有可能是，思源**并未完整下载云端文件**，能否核查一下。

另外我从控制台拉取文件时，概率（3/3）会出错暂停一次，需要**手动继续**才能完整下载，目前不清楚触发原因（阿里的OSS）。

最后，有没有什么应急用的法子，可以从本地的 OSS 恢复一下笔记，直接替换工作空间下 repo 的路子走不通。

### Expected result

云端同步能够正常使用。

### Version environment

```markdown
- Version: v3.1.14 from MS Store.
- Operating System: Windwos 11 24H2.
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18033094/siyuan.log)

**Comment by LSkittles** [comment]
> 不是的，是因为云端缺失，你那里可以从日志上找一下数据对象 id，通过路径在云端 repo 中确认是否缺失，比如这个 9304d2fd083fc3899ef3353d9b9308f7f277e9f4，对应路径应该是 objects/93/04d2fd083fc3899ef3353d9b9308f7f277e9f4

至少一部分在云端 repo 中是存在的，不过手动把云端 repo 的文件复制到本地之后，还是会缺一些。最后七七八八折腾，勉强恢复了一部分笔记。

**Comment by LSkittles** [comment]
另外闲唠两句。
  
云端目录损坏这个问题，是否与思源的增量快照机制有一定相关？基于本地优先的理念，至少我在使用思源的云功能时，是当做第二道备份来用的。但是，一来思源当前云端目录损坏的概率好像还是有些大（我自己己经遇到过不下两次了，刚开始笔记少，丢了也没在意）；二来云端 repo 一旦坏一点点，直接就把全部数据都给扬了，这对指望云备份救命的用户来说实在有些不能接受。
  
个人理解增量快照的机制方便云同步，但云备份这个业务，还是全量快照稳定一点。是否可以提供一个全量、增量切换的选项，或者干脆将云同步功能与云备份功能区分开。这样当笔记比较多的时候，就算云端 repo 损坏，也至少能恢复出一部分笔记。

**Comment by 88250** [comment]
云端损坏这个问题我们一直在找重现方式，但是直到目前为止还是定位不到问题，如果你那里能够稳定重现，请务必告诉我们重现步骤。

有单独的云端备份功能的，使用方式可在用户指南中搜索 数据备份。
