### ISSUE TITLE
有序列表项存在代码块时的缩进问题

### ISSUE THREAD

**Issue by MACDfree** [siyuan-note/siyuan#1338]
### 描述问题 Describe the problem
当有序列表中某一项下有代码块时，正常代码块应该是缩进显示。实际编辑时发现当调整到缩进格式后保存，再打开页面时缩进样式有被还原回来了。并且原先有序列表是一个块，再打开时变成了多个块

### 期待的结果 Expected result
保持编辑后的格式

### 截屏或录屏演示 Screenshot or screen recording presentation

![123213](https://user-images.githubusercontent.com/3363410/106172331-adfa8b00-61cd-11eb-939e-d625497de495.gif)

### 版本环境 Version environment

* 版本 Version：0.6.8
* 操作系统 Operating system：windows 10
* 浏览器（如果使用）Browser (if used)：

**Comment by MACDfree** [comment]
0.7.1中好像是修复了？

**Comment by 88250** [comment]
麻烦帮忙测试一下 071 中的表现，谢谢。

**Comment by MACDfree** [comment]
经测试，0.7.1中此问题已修复，并且列表的操作逻辑也变得更加直观易用。👍👍👍

**Comment by 88250** [comment]
感谢帮忙测试，我关闭了。列表相关改动比较多，如果发现 bug 请新开 issue 反馈，谢谢。
