### ISSUE TITLE
可以增加顺滑光标么，能极大的提升使用体验

### ISSUE THREAD

**Issue by Kikkwa** [siyuan-note/siyuan#13380]
### In what scenarios do you need this feature?

https://ld246.com/article/1730052819264 这是我在论坛上面发的帖子
我一直觉得顺滑的体验非常有助于写作，我现在也一直有使用论坛上别人分享的 块平滑移动 代码片段，我觉得体验很好，甚至觉得这种体验应该本身就自带在软件本体，而不需要另外使用代码片段增加学习成本。

顺滑光标功能不影响软件的整体架构，也不应该会产生太大的BUG，大概也不会浪费开发者太多的时间。
换取的书写体验是完全值得的
特别是一些功能单一的 Markdown 编辑器，我特别不理解为什么没有顺滑光标的功能，我指的是 Typora。

如果可以的话，请参考一下Ob的插件和代码片段，原生内置到思源笔记

### Describe the optimal solution

Obsidian 上的解决方法
1.  安装 ninja插件 https://github.com/vrtmrz/ninja-cursor
2. 使用这个代码片段 https://forum.obsidian.md/t/cursor-smooth-caret-animation/31068/25

**Comment by 88250** [comment]
期待插件。
