### ISSUE TITLE
Math.js plugin

### ISSUE THREAD

**Issue by Ordyl** [siyuan-note/siyuan#13389]
### In what scenarios do you need this feature?

Dear colleagues I have request to add math.js as plugin. Allow it to calculate inside the note.

### Describe the optimal solution

The plugin should integrate math.js functionality seamlessly into SiYuan Note, allowing users to perform calculations and evaluate mathematical expressions directly within their notes. Below is an outline of the desired features and behavior:

Inline Calculation:

Users can write expressions in a specific syntax (e.g., {{2 + 3}} or $math{2 + 3}), and the plugin evaluates the expression and displays the result inline, replacing the placeholder with 5.
Block-Level Calculation:

Users can create a dedicated block (e.g., a "Math Block") for performing more complex calculations or series of expressions. The results are displayed beneath the block or within the same block dynamically.
Support for Advanced Math Functions:

The plugin should support advanced math operations, including:
Trigonometry (sin, cos, tan).
Algebraic operations (e.g., solving equations).
Statistical calculations (mean, median).
Unit conversions (e.g., 5 km to m → 5000 m).
Real-Time Evaluation:

As users type the expression, the plugin dynamically evaluates it in real-time and updates the result.
Error Handling:

If an invalid expression is entered, the plugin should display a helpful error message (e.g., "Invalid syntax" or "Division by zero error").
Customizable Syntax and Behavior:

Provide a settings menu where users can:
Choose the syntax for math expressions.
Enable or disable real-time evaluation.
Set preferences for displaying results (e.g., inline, block, or tooltip).
Lightweight Integration:

Ensure the plugin is lightweight and doesn’t introduce significant latency or performance issues, even with large notes containing multiple calculations.
Compatibility:

Ensure compatibility with existing SiYuan features, such as Markdown rendering, and allow for exporting notes with evaluated results.

**Comment by 88250** [comment]
Thanks for the suggestion, I look forward to the emergence of such a plugin.
