### ISSUE TITLE
希望添加根据多级标题自动生成目录的功能

### ISSUE THREAD

**Issue by dreamcatcher-zgr** [siyuan-note/siyuan#13385]
### In what scenarios do you need this feature?

当文档太长时，可以通过点击目录来跳转到对应位置

### Describe the optimal solution

根据1、2、3、4级标题关系在文档左侧自动生成目录，跟飞书文档效果类似

**Comment by TCOTC** [comment]
![image](https://github.com/user-attachments/assets/aa069bdb-daab-44ca-be5e-fba694b33d2c)

**Comment by 88250** [comment]
使用大纲面板（Alt+2）
