### ISSUE TITLE
新建工作空间，从云端拉取数据快照失败（S3）

### ISSUE THREAD

**Issue by LSkittles** [siyuan-note/siyuan#13381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

新建工作空间，配置 S3 后，从云端拉取数据快照失败，报错：“同步失败：open D:\bhe_data\SiYuan\bhe_note\repo\objects\92\396d28698957bdc49b2e4242c6a54a4f8efd8e: The system cannot find the file specified. (Provider: S3) v3.1.14”。
![屏幕截图 2024-12-06 004928](https://github.com/user-attachments/assets/69602d00-73d8-429c-b3ef-5a119570cb6c)
此时关闭软件并重启启动后，文档树可以看到部分笔记本，但**无法打开**，报错“未找到相关内容”。
![image](https://github.com/user-attachments/assets/4461ef8c-7e74-4fab-ba43-a9de5117e82f)

### Expected result

可以正常使用云端同步功能。

### Version environment

```markdown
- Version: v3.1.14 from MS Store。
- Operating System: Windows 11 24H2。
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18027111/siyuan.log)

**Comment by TCOTC** [comment]
先试试在 文档树 - 更多 - 重建索引

**Comment by 88250** [comment]
> E 2024/12/06 00:48:57 sync.go:1460: download cloud chunk [9304d2fd083fc3899ef3353d9b9308f7f277e9f4] failed: cloud object not found

说明云端数据损坏了，出现这个问题的话只能从其他备份数据导入了。

我这里目前无法重现这个问题，如果你能够重现的话请告诉我，谢谢。

**Comment by banjuer** [comment]
同样，出问题了
