### ISSUE TITLE
Support flac audio asset playback

### ISSUE THREAD

**Issue by Gwyn-S** [siyuan-note/siyuan#13386]
不支持flac音频格式

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

从本地文件夹拖入flac音频文件到文章中，播放器不能正确播放而是以文件链接形式，但是改成MP3,WAV均可，其他格式未测试
![image](https://github.com/user-attachments/assets/c9fdb1ec-3caa-46eb-a68d-97eec9423a3a)

### Expected result

可以在文章中播放

### Version environment

```markdown
- Version: 3.1.14
- Operating System: win10
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
给一个文件试试

**Comment by 88250** [comment]
http://samples.mplayerhq.hu/
