### ISSUE TITLE
插件开发求助： 在只读模式下，使用new Protyle，有没有办法自动解锁，允许编辑

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13391]
### In what scenarios do you need this feature?

思源如果开启全局只读模式，尽管当前文档已经解锁了，插件使用new Protyle，根据当前文档的块创建一个编辑弹窗，默认也是只读模式。
但我插件的使用场景是，调用插件的时候，用户是需要将当前文档解锁，但目前文档解锁了，插件的弹窗，却还要再解锁一次，有点不方便，目前我只能通过Protyle的面包屑解锁编辑，请问该如何自动解锁呢？看了Protyle的参数，并没有找到对应参数，调用protyle.protyle.disable =false. 也不起作用

### Describe the optimal solution

无

### Describe the candidate solution

无

**Comment by Vanessa219** [comment]
初始化的时候使用这个参数试试

![image](https://github.com/user-attachments/assets/b7af733c-07ef-455f-bc39-3bfa04e83755)

**Comment by Achuan-2** [comment]
![PixPin_2024-12-07_10-51-13](https://github.com/user-attachments/assets/1e4a521b-9d74-488f-8cca-b94c09cf723d)
没有用

**Comment by Vanessa219** [comment]
做为参数进行设置，不要赋值

**Comment by Achuan-2** [comment]
> 做为参数进行设置，不要赋值

不知道怎么传参，v姐能不能指导下

**Comment by Vanessa219** [comment]
不好意思，看错了，我加两个方法吧。

**Comment by Achuan-2** [comment]
好的，感谢V姐🙏
