### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by whoishuai** [siyuan-note/siyuan#13394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

折叠标题后，标题下的图片无法显示

### Expected result

![1733553410816](https://github.com/user-attachments/assets/4a06fd2c-2b2b-4271-9e28-86fc29506b00)
图片无法完全显示
在老的版本标题折叠后图片也可完全显示
但在新版本中无法做到
![1733553448308](https://github.com/user-attachments/assets/b1144e89-de54-419d-8448-61f95faba014)

注：图中以是目前的老版本，但是我依然找不到最开始的那个老版本

### Version environment

```markdown
- Version: 3.1.7
- Operating System: windows
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18046521/siyuan.log)

**Comment by whoishuai** [comment]
![1733554062865](https://github.com/user-attachments/assets/3936ace0-fbc5-45c7-89f6-081250549fc9)
这是旧版本的：3.0.16
发现是可以显示的

**Comment by 88250** [comment]
看了下代码变更历史，这个是在 v3.1.6 中改动的，折叠标题块以后会折叠其下方所有块，如果不这样做会有其他问题，所以只能这样做。
