### ISSUE TITLE
顶栏中拖拽区域，是否需要给一个cursor属性

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13393]
今天才发现原来「设置」「搜索」，这类浮窗，也可以顶栏拖拽。是否需要给一个cursor属性提醒一下用户
![image](https://github.com/user-attachments/assets/bfa94403-f607-4139-a46e-356a280e5b6f)

**Comment by cordinGH** [comment]
![image](https://github.com/user-attachments/assets/e298b99a-4a6e-4792-9ea6-2c07647efac6)
甚至左边这一块也支持拖拽，以前从来没想到过

**Comment by TCOTC** [comment]
感觉没啥必要，用户用不到这个拖拽

**Comment by Vanessa219** [comment]
这种好像一般没有手势，加了的话文字上是 move 就很奇怪

![image](https://github.com/user-attachments/assets/d16d01c9-5ca6-4c21-9d90-fd170fbf3df8)
