### ISSUE TITLE
打开工作空间，有的页签显示不了文档

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13390]
工作空间压缩包

![image](https://github.com/user-attachments/assets/419c907d-9ea9-4f0b-b37a-8f7af917e24c)

**Comment by Vanessa219** [comment]
conf.json 里面的 children 是空的，这个数据是操作了什么导致的？

![image](https://github.com/user-attachments/assets/4a89a184-2d69-4184-9a68-97fe2cfa15d4)

**Comment by TCOTC** [comment]
不知道，我更新了之后就这样了

**Comment by Vanessa219** [comment]
是关闭工作空间，然后安装包，然后打开就这样了么？还是其他的操作？

**Comment by TCOTC** [comment]
> 关闭工作空间，然后安装包，然后打开就这样了

感觉应该是这样

**Comment by Vanessa219** [comment]
重现不了，要不发现没有 children 的，就把页签关了吧。

**Comment by TCOTC** [comment]
也行

**Comment by Vanessa219** [comment]
不拉进 3.1.15 了
