### ISSUE TITLE
Code block in List block

### ISSUE THREAD

**Issue by thienphuoc86** [siyuan-note/siyuan#13392]
### In what scenarios do you need this feature?

The code block should stay in List block
![image](https://github.com/user-attachments/assets/f0d91937-bbce-4663-a171-5887cae149f0)

![image](https://github.com/user-attachments/assets/8b06f705-6fd1-48f1-863b-01b5a989af06)

### Describe the optimal solution

With the old version (I don't remember which version) the code block was completely in the list block

**Comment by KuiyueRO** [comment]
Have you tried the default theme?

Below is my screenshot

![image](https://github.com/user-attachments/assets/ab5aedd9-98b8-4eba-8995-77f3e0819932)

**Comment by royc01** [comment]
My bad, I'll fix it in the next version.

**Comment by thienphuoc86** [comment]
Thanks royc01,
It's ok now :)
