### ISSUE TITLE
在 Protyle 的事件处理中，无视一切来自 protyle-custom 的事件

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#13397]
### In what scenarios do you need this feature?

此前，我们尝试在 Lute 中加入了 .protyle-custom 标签，让 DOM 中允许存在一些被官方解析器“无视”的部分，以便于我们插入一些自己的元素节点。

https://github.com/88250/lute/issues/206

这个 issue 希望更进一步，在所有 protyle 的事件处理当中，将它当作思源设计范围之外的东西，直接忽视掉。

### Describe the optimal solution

在各个事件处理函数中，如果检测到是 .protyle-custom 的元素，就直接退出无视。

```js
if (el.closest('.protyle-custom') {
    return;
}
```

当然，我们的直接目的是能在编辑器内安全地插入自定义的代码——而上面提出的做法仅仅是我直观想到的一个解决方式。

就最后的目的而言，最直接的效果肯定是如果用户在 protye-custom 里面点击、输入一些元素后，不会影响到本体的内容，同时本地也不会误删掉自定义的元素。

**Comment by Vanessa219** [comment]
点击的话，内部不要带 siyuan 的 data-type 和 class 应该就不会命中。输入的话要保持一些快捷键的操作，因此也没有办法彻底屏蔽。

或者有什么特定的场景我看看是否能处理。

**Comment by frostime** [comment]
> 点击的话，内部不要带 siyuan 的 data-type 和 class 应该就不会命中。输入的话要保持一些快捷键的操作，因此也没有办法彻底屏蔽。
> 
> 或者有什么特定的场景我看看是否能处理。

介绍一下我遇到的具体情况。

#### 背景

背景是这样：尝试魔改嵌入块，在 embed 元素里面嵌入了自定义的元素。

![image](https://github.com/user-attachments/assets/d088df58-d7f5-4ce9-8281-620c102b5e33)


如果什么都不管的话，在 textarea 里面按下键盘的时候整个嵌入块就会被直接吞没掉。

![image](https://github.com/user-attachments/assets/b1b94400-c75b-4a36-9be1-eb1b23abb0b5)


#### 尝试截断

猜测可能是上层的事件起了什么冲突。所以在截断容器元素的冒泡传播。

![image](https://github.com/user-attachments/assets/ce04dfa0-dfc9-4c54-8861-b7569ae0ae1d)


#### 新的问题

然而新的问题出现了，现在对话框里面无法正常输入中文符号，一旦强行输入就会出现奇怪的反应。

![image](https://github.com/user-attachments/assets/1e8ffe14-6b6c-4854-b547-5b71316dd0b3)

**猜测**，可能是由于强制截断，导致输入法无法正常处理正常的输入事件。

针对这个问题，**假设**的一个可行的思路是：不强制截断事件，而在思源内部无视掉对他的处理。

#### 其他问题：关于 ESC 选中块

为了能复用一些思源内的样式，所以在内部插入 markdown 文档等的时候复用了块的类名等。

![image](https://github.com/user-attachments/assets/84bb5d4d-2e5b-4e1a-b34d-fc13240a6f4f)

同时为了避免麻烦，需要让思源的 ESC 选中所在的块的功能不可以在 protyle-custom 内部生效。

不过奇怪的事，直接禁用 key event 的 propagation 似乎无法达成这一目的。我参考之前 ZX 在一个插件中的做法，是给 protyle.element 在**捕获阶段**添加一个监听器，直接截断来自自定义元素的传播。

![image](https://github.com/user-attachments/assets/4f9a7ff0-d3be-4265-b156-4044ff9f8d69)

但是我在翻阅思源的代码的时候，似乎没有看到有用捕获时期的监听器，不知道为什么会这样。

想要再请问一下，这个 ESC 选中块是如何实现的，为什么冒泡阶段的 stoppropagation 无法阻止这个功能。

**Comment by Vanessa219** [comment]
是在 keydown 中阻止冒泡么？

样式没有干扰的话可以用，不行的话可以自己写。

**Comment by frostime** [comment]
> 是在 keydown 中阻止冒泡么？
> 
> 样式没有干扰的话可以用，不行的话可以自己写。

我又调试了一下代码，现在大部分都正常了。
https://github.com/frostime/sy-query-view/blob/8b5b6a7006967f10ed67b994dbcec83b00b8d3a7/src/core/data-view.ts#L1187

几个截断的时间都是在冒泡期间阻止的。这几个目前看没啥问题。

唯一需要特别处理的是 ESC 事件，这个很奇怪不知道为啥必须要在捕获阶段绑定到 protyle.element 上去截断 keydown 的传播才有效果。

https://github.com/frostime/sy-query-view/blob/8b5b6a7006967f10ed67b994dbcec83b00b8d3a7/src/core/data-view.ts#L1231

个人对于在自定义代码（而且这是放到嵌入块里面执行的，会经常刷新）中操作 protyle.element 还是有点顾虑，不知道可不可以至少在 `ESC` 按键这个事件中跳过 `protyle-custom`？

**Comment by frostime** [comment]
> > 是在 keydown 中阻止冒泡么？
> > 样式没有干扰的话可以用，不行的话可以自己写。
> 
> 我又调试了一下代码，现在大部分都正常了。 https://github.com/frostime/sy-query-view/blob/8b5b6a7006967f10ed67b994dbcec83b00b8d3a7/src/core/data-view.ts#L1187
> 
> 几个截断的时间都是在冒泡期间阻止的。这几个目前看没啥问题。
> 
> 唯一需要特别处理的是 ESC 选中块的事件，这个很奇怪不知道为啥必须要在捕获阶段绑定到 protyle.element 上去截断 keydown 的传播才有效果。
> 
> https://github.com/frostime/sy-query-view/blob/8b5b6a7006967f10ed67b994dbcec83b00b8d3a7/src/core/data-view.ts#L1231
> 
> 个人对于在自定义代码（而且这是放到嵌入块里面执行的，会经常刷新）中操作 protyle.element 还是有点顾虑，不知道可不可以至少在 `ESC` 按键这个事件中跳过 `protyle-custom`？

那几个在 protyle-custom 内部就可以截断处理的事件可以先放放，但是那个必须要绑定到 protyle 元素上，用来阻止 ESC 选择元素功能的操作，不知道 V 姐可否研究一下，直接内置到思源里（如果元素 closest 到一个 .protyle-custom，就禁止使用 ESC 选中）？

操作 prtotyle-element 的事件我还是有点担忧的。

**Comment by Vanessa219** [comment]
内置的话，其他自定义想用的就没有办法去使用了。只能自己特殊处理。

keydown 的话 protyle.wysiwyg.element 和 window 上都绑定过。

**Comment by frostime** [comment]
感觉现在有点乱。我先 close 了，等能提出更明确的需求之后再提一下吧。🤔
