### ISSUE TITLE
Integrating Excalidraw

### ISSUE THREAD

**Issue by iWaoc** [siyuan-note/siyuan#13399]
### In what scenarios do you need this feature?

In all SiYuan instances (Desktop, Docker, Self-hosting)

### Describe the optimal solution

Hello!

Although SiYuan is powerful for creating multiple types of graphs and diagrams, I think it would be better if you would integrate the complete Excalidraw canvas (also OpenSource) and its available functions into SiYuan, which I have been able to test in other applications that have it integrated, such as Trilium Notes.

Could you integrate this functionality that Excalidraw (https://github.com/excalidraw/excalidraw) provides to increase SiYuan's capabilities for creating graphs and diagrams?

I hope you will be encouraged to do so. 🫶🏼

**Comment by 88250** [comment]
Hello, we are not considering native integration of Excalidraw at present. Please implement it through plugin. Thanks for your suggestion.
