### ISSUE TITLE
斜体字语法还是需要在*后面加一个空格才能实现渲染

### ISSUE THREAD

**Issue by wfan14513** [siyuan-note/siyuan#134]
希望能跟加粗语法一样不需要自己加空格。

**Comment by 88250** [comment]
请在 https://spec.commonmark.org/dingus/ 这里试一下语法，看下思源渲染是否和标准一致。

**Comment by wfan14513** [comment]
是一致的。
我记得还是链滴的时候，不是加了个零宽空格解决了这个问题吗？

**Comment by wfan14513** [comment]
哦，好像现在加粗也要空一格。

**Comment by 88250** [comment]
是一致的那就没问题了，需要遵循规范，关闭了哈。

**Comment by wfan14513** [comment]
OK
