### ISSUE TITLE
希望可以支持列表折叠和展开的部分制作闪卡

### ISSUE THREAD

**Issue by zyc649** [siyuan-note/siyuan#13401]
### In what scenarios do you need this feature?

本人的最后一级列表通常是在列表下加入大量图片和文字，也通常是主要需要记忆的部分，如下图所示。在制卡时希望将下图 1 号位置作为闪卡标题，而 2 号位置作为答案（**其实也就是列表的折叠和展开的状态！个人感觉这样制卡也是非常符合直觉的**）
![image](https://github.com/user-attachments/assets/950245f7-4077-4e95-a9ae-9711739242b4)

### Describe the optimal solution

将列表作为题目，折叠的部分作为答案。从而实现闪卡和列表折叠展开在形式上的统一。

**Comment by 88250** [comment]
仅支持这个：

![image](https://github.com/user-attachments/assets/d554dfef-e056-4a5d-9a62-970ed787d3cc)

不考虑引入其他模式了，感谢提议。
