### ISSUE TITLE
剪藏页面时，不同电脑上HTTP 请求标头 Authorization: token不统一

### ISSUE THREAD

**Issue by dorauemon** [siyuan-note/siyuan#13400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

剪藏页面时，剪藏插件在不同电脑上HTTP 请求标头 Authorization: token不统一，导致每次我从mac换到台式机上使用时都要重新设置API TOKEN才能剪藏，然后chrome扩展一同步，换回mac时又要来一次，有没有办法解决？

### Expected result

Authorization: token统一

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
手动指定 思源 - 设置 - 关于 - API token
