### ISSUE TITLE
Outline panel update overwrite content issue

### ISSUE THREAD

**Issue by hzxgi** [siyuan-note/siyuan#13409]
大纲更新时会覆盖其他文档

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

分屏时切换标签页可能导致大纲对应不上

### Expected result

对应上

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/7dc526ee-b48d-407e-a022-4b5b8631f428)

### Version environment

```markdown
- Version: 3.1.14
- Operating System: Windows11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18062472/siyuan.log)

**Comment by Vanessa219** [comment]
快速拉近关系和女生问去哪里玩 这两个标题都是《加上一段时间》里面的么？我这里无法重现，具体要怎么操作呢？

**Comment by hzxgi** [comment]
对，都是《加上一段时间》里面的

**Comment by hzxgi** [comment]
具体复现步骤我也不是很清楚。我是在**聊天实战**里ctrl+x复制一个标题后粘贴到**加上一段时间**后马上点击**聊天实战**

**Comment by hzxgi** [comment]
今晚上出现了两次这个bug

**Comment by 88250** [comment]
数据未写入完成之前切换大纲可能不会更新，写入大致需要 500 毫秒左右。

我先关闭了，如果超过 1 秒还能重现该问题麻烦录屏演示，感谢反馈。
