### ISSUE TITLE
支持输入 `1。 ` （数字&句号&空格）转换为有序列表

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13403]
关联 https://ld246.com/article/1733664825290

**Comment by 88250** [comment]
之前曾经试过，后来移除了，因为有副作用 https://github.com/siyuan-note/siyuan/issues/921

**Comment by TCOTC** [comment]
你得再判断一个空格才行，`1、 ` 对应 `1. `，末尾都有一个空格

**Comment by 88250** [comment]
不改了，输入法设置应该可以



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2024年12月8日(周日) 晚上11:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 支持输入 `1。 ` （数字&amp;句号&amp;空格）转换为有序列表 (Issue #13403)




 
你得再判断一个空格才行，1、  对应 1. ，末尾都有一个空格

**Comment by TCOTC** [comment]
@88250 Notion FlowUs Wolai 飞书 全都支持这个操作

**Comment by 88250** [comment]
我们暂时不考虑了



---原始邮件---
发件人: "Jeffrey ***@***.***&gt;
发送时间: 2025年1月17日(周五) 中午1:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 支持输入 `1。 ` （数字&amp;句号&amp;空格）转换为有序列表 (Issue #13403)




 
@88250 Notion FlowUs Wolai 飞书 全都支持这个操作
