### ISSUE TITLE
搜索结果的高亮范围不正确

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13408]
关联 https://ld246.com/article/1733720211170 ，#13343 的后续

目前会高亮并且定位到同文档中的其他块上（文档块的逻辑），而预期是只高亮与定位对应的块内的文本：

[video.webm](https://github.com/user-attachments/assets/20e0cbbf-4cd6-48cc-8473-ddec7d480e25)

**Comment by Vanessa219** [comment]
[c546e0f](https://github.com/siyuan-note/siyuan/commit/c546e0fd945502c27b169cedf2be13a3917c9f0e)

**Comment by TCOTC** [comment]
@Vanessa219 还是高亮了其他的块：

[video.webm](https://github.com/user-attachments/assets/08d7a3ee-4e37-4018-b02d-6726f9121dbe)

**Comment by Vanessa219** [comment]
这个都会高亮的，只是当前块会使用橙色

**Comment by TCOTC** [comment]
还是感觉很奇怪，搜索块 A ，但是能跳到块 B
