### ISSUE TITLE
docker 部署，并使用frpc穿透后，一直提示错误

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#13406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker 部署
并使用frpc 穿透

### Expected result

直接在内网访问 6806 端口还没有问题的。

### Screenshot or screen recording presentation

一开始加载成功并显示
然后立马提示这个错误

![image](https://github.com/user-attachments/assets/8edc18bf-c932-49fb-8332-995ad1dc2772)

### Version environment

```markdown
- Version: 3.1.14
- Operating System: all
- Browser (if used): all
```

### Log file

E 2024/12/09 11:45:05 serve.go:536: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2024/12/09 11:45:10 serve.go:536: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2024/12/09

**Comment by 88250** [comment]
需要保证 WebSocket 也能够连通，可以打开浏览器开发者工具看下请求状态，参考 frp 相关资料配置 WebSocket。
