### ISSUE TITLE
Display tag and bookmark in flat

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1340]
上下文层级：

* https://github.com/siyuan-note/siyuan/issues/1158
* https://github.com/siyuan-note/siyuan/issues/1031

还需要加入直接平铺内容块的展现方式。

**Comment by wo4wangle** [comment]
打个预防针

因为标签上文引入了 非文件系统的上文层级
这样层级会爆炸式的增长，引入“层级地狱”的问题
如下，我现在的展开：都找不着边了
![image](https://user-images.githubusercontent.com/46141646/106368496-ceb91100-6384-11eb-8117-aa6cea80ffae.png)

按过去层级全部换行显示的方案，即使平铺实现也会有 **上文信息沾满标签窗口** 的问题
而事实上，**标签标注的不是上文，而是内容，上下文信息不应该喧宾夺主**

方案：
这个问题我想了一下：没想啥好办法…
至少目前觉得过去的平铺方式就很ok：直接放弃 非文件系统的层级，强调标签块的内容
因为上文靠文件系统路径已经能确定大范围了
我倒是觉得标签直接修饰的块内容可以 多行全展示，因为块内容才是标签最直接的关联

**Comment by Jamie-Wan** [comment]
还有反向链接的层级也是一样的问题🙀🙀
