### ISSUE TITLE
增加“重载界面”内核API或快捷键

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#13402]
### In what scenarios do you need this feature?

做了个从网页抓取代码片段并发送到思源的quicker动作，使用了 /api/snippet/setSnippet 和 /api/setting/setSnippet 两个API，但是添加后并没有生效，只是修改了conf.json文件，需要重启思源代码片段才会生效

### Describe the optimal solution

增加“重载界面”内核API或快捷键，以便使代码片段立即生效

**Comment by 88250** [comment]
POST `/api/system/reloadUI`

**Comment by 88250** [comment]
下个 dev 版加入

**Comment by 88250** [comment]
v3.1.27 该 API 端点有变更：`/api/ui/reloadUI`
