### ISSUE TITLE
导出PDF时mermaid显示位置有问题

### ISSUE THREAD

**Issue by emptylight370** [siyuan-note/siyuan#13417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在导出pdf时，如果笔记中含有mermaid，导出之后在对应位置会有很长的留白，但是mermaid图表会有显示偏差，不会显示在空白处

### Expected result

mermaid图表显示在空白处

### Screenshot or screen recording presentation

![PixPin_2024-12-10_18-15-42](https://github.com/user-attachments/assets/6d6280dc-e1f2-4b42-8d22-7950aacab49d)

### Version environment

```markdown
- Version: 3.1.15
- Operating System: Windows 11 23h2
- Browser (if used):
```

### Log file

1

### More information

https://ld246.com/article/1733805172257

**Comment by Vanessa219** [comment]
看上去是正常的，麻烦上传一下有问题的 .sy 文件。

https://github.com/user-attachments/assets/df7b602b-7f04-4286-b2e0-0839bbc02f68

**Comment by emptylight370** [comment]
[存储区管理.sy.zip](https://github.com/user-attachments/files/18088925/sy.zip)
[存储区管理.pdf](https://github.com/user-attachments/files/18088926/default.pdf)

**Comment by Vanessa219** [comment]
已修复，不拉进 3.1.16 版本了
