### ISSUE TITLE
数据库模板列支持markdown格式渲染

### ISSUE THREAD

**Issue by RainBoat** [siyuan-note/siyuan#13414]
### In what scenarios do you need this feature?

数据库模板列能够提取很多自定义字段，但似乎并不支持直接参照markdown内容渲染，也不支持交互点击。这为实现点击跳转等功能带来了障碍。
例如，通过以下代码输出markdown格式的超链接
```
.action{$ParentNode := index . "custom-ParentNode"}
.action{$blocks := (queryBlocks "SELECT * FROM blocks WHERE id = '?' "  $ParentNode)}
.action{range $b:=$blocks} 
[.action{$b.Content}](siyuan://blocks/.action{$b.ID})
 .action{end}
```
数据库模板列显示为以下图片
![image](https://github.com/user-attachments/assets/63fcf3e1-4ae9-4173-9a3d-50bdaac1e424)

### Describe the optimal solution

支持模板列的markdown渲染

**Comment by TCOTC** [comment]
不支持 Markdown 渲染，请拼接 HTML

**Comment by RainBoat** [comment]
#12012 可能需要进一步解决此问题
