### ISSUE TITLE
数据库粘贴导致崩溃

### ISSUE THREAD

**Issue by ShawElA** [siyuan-note/siyuan#13410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

两列文本列之间夹一个多选列，粘贴时出错并崩溃

https://github.com/user-attachments/assets/fe3f88b6-00c5-4549-a236-ace56aa29975

### Expected result

正常粘贴

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

略

**Comment by TCOTC** [comment]
相关 https://github.com/siyuan-note/siyuan/issues/13259
