### ISSUE TITLE
思源 docker 部署后正常运行 4 天，使用过程中，粘贴从别处复制的文档标题没反应，发现报错 502

### ISSUE THREAD

**Issue by lzmsomuch** [siyuan-note/siyuan#13412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源 docker 部署后正常运行 4 天，使用过程中，粘贴从别处复制的文档标题没反应，发现报错 502

### Expected result

无法正常使用，编辑文档等

## 问题现象
使用过程中，突然无法粘贴，
然后发现 浏览器报错 502 Bad Gateway
![image](https://github.com/user-attachments/assets/82b9a302-9576-4bc5-9d4f-68c65215da7e)

## 排查 docker 进程和日志
![image](https://github.com/user-attachments/assets/13f0ee03-3cc4-4995-9e59-180f3b6b8bf9)

### Version environment

```markdown
- Version: 3.1.14
- Operating System: Windows Chrome 访问 docker 部署的 siyuan server 端
- Browser (if used): Chrome 最新版
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18071125/siyuan.log)

**Comment by 88250** [comment]
从内核日志上看没有问题（报错不影响），建议排查是不是反代服务器的问题。

**Comment by lzmsomuch** [comment]
> 从内核日志上看没有问题（报错不影响），建议排查是不是反代服务器的问题。
确实是这个问题，谢谢大佬，已解决
