### ISSUE TITLE
Paste code block missing line break

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13416]
https://ld246.com/article/1733818265802

[video.webm](https://github.com/user-attachments/assets/dbb40c8f-54d0-451f-891d-b5b86aa83173)

![image](https://github.com/user-attachments/assets/9d5c9f08-2e1a-410a-a4f8-b8dcefa8d84d)

**Comment by 88250** [comment]
DOM 结构太复杂了，不考虑兼容了：

![image](https://github.com/user-attachments/assets/8ca46098-704c-45c0-bd04-b4948b332fef)

建议导出 Markdown 再导入。

**Comment by 88250** [comment]
排查了下，代码块换行丢失是个 bug，稍后修复。
