### ISSUE TITLE
添加一个设置，在用户使用全屏(alt+y)的时候，比例放大页面。

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#13413]
### In what scenarios do you need this feature?

当我将页面全屏的时候，希望可以自动放大显示所有内容，主要是阅读为主。希望能够添加一个设置
可以在用户全屏的时候，自动按照设置缩放显示内容

### Describe the optimal solution

添加一个设置。
默认为 100%，并提供其他可选选项
如80%  110% 120%  125% 133%  150% 200%
当用户使用全屏的时候，可以自动按照这个比例缩放查看。

**Comment by TCOTC** [comment]
适合用插件实现这种功能

**Comment by 88250** [comment]
放到 Idea 插件需求中，感谢提议。

**Comment by heartacker** [comment]
谢谢

另外问问  idea 插件在哪里下载，。不是很懂你说的idea 是啥

**Comment by TCOTC** [comment]
idea 是这个 issue 的标签，不是插件

**Comment by 88250** [comment]
应该还没有类似插件的，只是添加到 [Idea](https://github.com/siyuan-note/siyuan/labels/Idea) 需求池中，以便社区开发者参考。
