### ISSUE TITLE
Improve inline elements parsing

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13420]
方法来源于 https://ld246.com/article/1717657383372

```
<span data-type="text" style="text-emphasis-style: dot; text-emphasis-position: under;">着重符号<span> ((20241210194444-oqwwntf "*"))
```

我不理解这个是怎么解析的，为什么会有两种结果：

[video.webm](https://github.com/user-attachments/assets/2e43354d-5aaf-4de8-8b2b-2f141af9ff0a)

**Comment by 88250** [comment]
严格来说是有 bug，但是目前没有太好的方案解决。

这个问题源自 `着重符号<span>` 这里的结束标记没有匹配，使用 `</span>` 才能匹配，解析过程中最后匹配到的是后面的引用 `<span data-type="block-ref" data-subtype="s" data-id="20241210194444-oqwwntf">*</span>` 的 `</span>`，然后 HTML 解析器在这种情况下可以正确解析出两个 span 节点，所以结果刚好正确。

![image](https://github.com/user-attachments/assets/37d2c007-07c2-4646-a2c9-ff8309abe416)

![image](https://github.com/user-attachments/assets/d75c41e9-2cc0-4355-8e5a-3ff2a972022a)

而如果没有 `</span>` 结束标记的话无法正确解析 `<span data-type>` 为 lute ast 行级节点，所以返回了行级 HTML 节点（最终渲染为文本节点）：

![image](https://github.com/user-attachments/assets/1e7fa238-360a-4d9d-a979-84bfed3b904b)

这个问题稍后会改进解析，判断 span 是否正确匹配。
