### ISSUE TITLE
Unable to use `Query Syntax` to search

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13422]
无法正常使用 `查询语法` 搜索类型

v3.1.10：

![image](https://github.com/user-attachments/assets/e804021e-4507-4644-9a80-6289aeb0ab6a)

v3.1.15：

![image](https://github.com/user-attachments/assets/83afea22-1530-4398-8f53-7ba59aff871e)

---

- [ ] 跨块搜索 #10584
- [ ] 搜索结果高亮

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/a18ed370-6e95-4bde-a08d-6b367ac8042d)

这里指的是？

**Comment by TCOTC** [comment]
1. 查询语法搜索支持跨块搜索（像关键字搜索那样）
2. 搜索结果的文本要有高亮

**Comment by 88250** [comment]
查询语法支持不了跨块搜索，只有关键字模式能支持。
