### ISSUE TITLE
Some security vulnerabilities

### ISSUE THREAD

**Issue by Elleuch-x1** [siyuan-note/siyuan#13426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

As requested from the maintainer, here's the titles of the vulnerabilities:

- Arbitrary file read via /api/template/render
- Arbitrary file read via path traversal in /api/export/exportResources
- Stored XSS via /upload
- Stored XSS and arbitrary file write in the host via /api/asset/upload
- Limited SSTI via /api/template/renderSprig

### Expected result

n/a

### Version environment

```markdown
Latest version
```

### Log file

n/a

### More information

The details has been sent to the maintainer

**Comment by 88250** [comment]
Confirmed:

* Arbitrary file read via /api/template/render
* Arbitrary file read via path traversal in /api/export/exportResources
* Stored XSS and arbitrary file write in the host via /api/asset/upload

Not considered a vulnerability:

* Stored XSS via /upload 
  The upload interface can upload any file without checking the file content. If the uploaded file can be opened in SiYuan and causes XSS, please provide more details.
* /api/template/renderSprig
  This is a functional feature.
