### ISSUE TITLE
内容块备注展现

### ISSUE THREAD

**Issue by YotsubaAina** [siyuan-note/siyuan#1342]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

浏览全文的时候想要知道哪些地方被我做了备注，但是做了备注的内容块没有像引用那样的提示效果，不太好找
![image](https://user-images.githubusercontent.com/74671505/106233376-5b52ba80-6231-11eb-9df7-964d8fe766d8.png)

### 描述最优的解决方案 Describe the optimal solution

参考 Notion，建议加一个按钮用于提示当前内容块是否含有备注，并且点击这个按钮可以查看和修改备注

![image](https://user-images.githubusercontent.com/74671505/106233218-f7c88d00-6230-11eb-880e-1f3071dbf3c6.png)
点击按钮后
![image](https://user-images.githubusercontent.com/74671505/106233222-fbf4aa80-6230-11eb-83fd-68007b337b15.png)

**Comment by Vanessa219** [comment]
目前先使用颜色和提示
![image](https://user-images.githubusercontent.com/970828/106700051-0347f980-661f-11eb-83a2-3721f5ac69e3.png)
![image](https://user-images.githubusercontent.com/970828/106700064-080cad80-661f-11eb-975e-9bbe4f76cf3e.png)
