### ISSUE TITLE
在平板上点击块引用打开文档之后还会打开浮窗

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13429]
https://github.com/user-attachments/assets/d7d69b99-9e5d-4fd4-8b0f-c4cffbdc4ba9

**Comment by TCOTC** [comment]
用户反馈：https://ld246.com/article/1734093932851

**Comment by 88250** [comment]
Fixed in https://github.com/siyuan-note/siyuan/commit/e9bddf922477a47390e47f8b1a2342385c468332

**Comment by TCOTC** [comment]
我这里还是会打开浮窗

**Comment by Vanessa219** [comment]
没有设备，麻烦再看看。

前一个提交是修复无法关闭弹窗的问题。

**Comment by TCOTC** [comment]
@Vanessa219 不会打开浮窗了，不过点击块引用切换文档之后会弹出键盘，不像手机那样会自动隐藏
