### ISSUE TITLE
网页剪藏pre节点包裹的code节点换行无法正确识别

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#13433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

发现一种有pre包裹的code节点，里面的代码换行无法正确识别，导致代码全黏到一行了
[问题网址](https://findfunction.com/blogs/%E9%B8%BF%E8%92%99%E8%B0%83%E8%AF%95%E6%97%A5%E5%BF%97/openharmony-%E5%BA%94%E7%94%A8%E8%8E%B7%E5%8F%96%E7%B3%BB%E7%BB%9F%E7%AD%BE%E5%90%8D%E5%92%8C%E6%9D%83%E9%99%90/)

### Expected result

代码段能正确识别换行

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/52d37bdd-14b8-4a21-9e52-ff45f0d641eb)

### Version environment

```markdown
- Version: 3.1.15
- Operating System: Win10
- Browser (if used): Chrome 126
```

### Log file

这个按理说遇到pre节点需要额外处理换行

**Comment by 88250** [comment]
这个问题请等下个 dev 版后看看，应该已经修复。

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/13416

**Comment by ruin1990** [comment]
测试v3.1.16-dev2问题已解决
