### ISSUE TITLE
建议笔记本自定义排序的情况下,创建笔记时可以选择笔记创建在最上方还是最下方

### ISSUE THREAD

**Issue by oufu99** [siyuan-note/siyuan#13431]
### In what scenarios do you need this feature?

因为是根据自己的情况进行排序,我把重要的笔记放到了最上方,但是现在我创建的笔记会直接生成在他们的上面,就需要再手动操作一次。
因为用户的众口难调,有些人喜欢创建在最上面,所以希望添加一个功能让用户自己选择是创建在最上方还是最下方

### Describe the optimal solution

创建新笔记时,根据选项判断一下他的排序方式

**Comment by TCOTC** [comment]
这个不考虑了 #3181

请使用 `在下方新建文档` ：

![image](https://github.com/user-attachments/assets/33000ed0-8e43-4f04-a695-76931bb07cbf)

**Comment by oufu99** [comment]
那可否给在上方/下方新建文档,添加两个快捷键? 如果有快捷键效果也一样

**Comment by TCOTC** [comment]
其实我觉得有快捷键也没啥用，还是要先用鼠标点

**Comment by 88250** [comment]
> 这个不考虑了 https://github.com/siyuan-note/siyuan/issues/3181

感谢提议。
