### ISSUE TITLE
动态图标的大小与 emoji 不一致

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13437]
https://ld246.com/article/1733914459035

![image](https://github.com/user-attachments/assets/66ebbe00-d804-4577-a2c5-afbf079362a3)

还有页签和数据库主键上的大小也看看

**Comment by SaXz2** [comment]
![PixPin_2024-12-24_16-50-49](https://github.com/user-attachments/assets/c232a2d4-f359-47d0-ba6e-52bef628444c)
![PixPin_2024-12-24_16-53-17](https://github.com/user-attachments/assets/e2b2bb2a-2fc5-4cf2-a10b-05a3a3eccc38)

图标会出现对不齐的情况，出现在：自定义图标和动态图标

**Comment by Vanessa219** [comment]
每个系统上不太一样，只能进行基本对齐。

**Comment by SaXz2** [comment]
> 每个系统上不太一样，只能进行基本对齐。如果还不太齐的话，发一下系统。

目前还是如上图一样数据库对不齐

日志文件
[system-log (1).zip](https://github.com/user-attachments/files/18268665/system-log.1.zip)

版本	Windows 11 专业版 Insider Preview
版本号	Dev
安装日期	‎2024-‎10-‎04
评估到期日期	‎2025-‎09-‎16 5:16
操作系统版本	27695.1000
功能包	Windows Feature Experience Pack 1000.26100.19.0

**Comment by Vanessa219** [comment]
没对齐的这2个是 emoji 还是图片？麻烦发我一下。

**Comment by SaXz2** [comment]
红色那个是动态图标
另一个是这个文件
![nuke](https://github.com/user-attachments/assets/57a1cd33-df89-4f20-9fb6-366d415899ce)

**Comment by Vanessa219** [comment]
@88250

**Comment by 88250** [comment]
我这里看上去能对齐：

![image](https://github.com/user-attachments/assets/dcbac18d-50e0-47fa-ad50-192087be0f3c)

**Comment by SaXz2** [comment]
> @SaXz2 你再看下是不是其他扩展影响？

找到原因了，是JS代码导致的，里面动了图片的样式，忘记关了
