### ISSUE TITLE
Failed to get kernel serve port after restarting (Ubuntu, Flatpak)

### ISSUE THREAD

**Issue by laguill** [siyuan-note/siyuan#13432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

After restarting my laptop running Ubuntu, I encounter the following issues with the Siyuan app (installed via Flatpak):

1. Upon launching, the app displays the error message: "Workspace is locked."
2. Then, I receive another error: "Failed to get kernel serve port."

To resolve this, I have to manually kill the Siyuan process via the application manager and then restart the app, after which it works normally.

### Expected result

The app should start without errors after a system restart.

### Version environment

```markdown
- Version: 3.1.14
- Operating System: Ubuntu
```

### Log file

Nothing in `~/.var/app/org.b3log.siyuan/cache/tmp/`

**Comment by 88250** [comment]
It is recommended to check whether the kernel process (SiYuan-Kernel) is started automatically. If so, you need to turn off the automatic startup.

**Comment by 88250** [comment]
I will close the issue first. If you have any questions, please feel free to post them.

**Comment by laguill** [comment]
Ok so turned off the automatic startup of siyuan on boot
But I am still getting the same issue
