### ISSUE TITLE
Add block content statistics template function `statBlock`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13438]
增加字符数和字数的模板函数

返回 ID 对应的文档或块的字数

关联需求 https://ld246.com/article/1733921523331

- [ ] 补充用户指南

**Comment by TCOTC** [comment]
@88250 话说能不能再加个模板用来统计字符串里的字数（主键没有绑定块的情况）

**Comment by 88250** [comment]
加了个 `runeLen`

**Comment by 88250** [comment]
就这样吧，用户指南里有就行了。

**Comment by TCOTC** [comment]
@88250 我怎么感觉 runeLen 是字符数而不是字数

**Comment by 88250** [comment]
下个版本改进 https://github.com/siyuan-note/siyuan/issues/13625
