### ISSUE TITLE
/api/av/setAttributeViewBlockAttr 不会自动设置颜色

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

用api批量设置数据库绑定块的多选字段，发现不会自动添加颜色
![PixPin_2024-12-11_22-52-14](https://github.com/user-attachments/assets/59cc27ef-b4fc-46da-bf25-a20bc952daf0)

### Expected result

希望能自动设置多选项的颜色，而不需要指定

### Screenshot or screen recording presentation

无

### Version environment

```markdown
- Version: 3.1.15
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
需要给一下实参

**Comment by TCOTC** [comment]
缺了颜色后面的数字

**Comment by Achuan-2** [comment]
代码
```
// ------------设置属性 ------------ // 
await fetchSyncPost("/api/av/setAttributeViewBlockAttr", {
    avID: avID,
    keyID: keyID,
    rowID: docId,
    value: {
            "mSelect": [{"content":"Fiction7"}]
        },
});
```

**Comment by 88250** [comment]
如果添加不存在的选项的话需要指定 color，如果是已经存在的会自动沿用。

![image](https://github.com/user-attachments/assets/c15f065d-f833-40fe-b669-d476112b80e6)

稍后改进为没有指定 color 的话随机一个颜色：

![image](https://github.com/user-attachments/assets/fa272f41-cd2e-4373-82e7-f2c8524cf4d1)

**Comment by TCOTC** [comment]
我觉得应该用 1+rand.Intn(13)

**Comment by 88250** [comment]
到 14 应该没问题，14 是默认值。
