### ISSUE TITLE
Support setting automatic sync interval

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13448]
https://github.com/siyuan-note/siyuan/issues/13172#issuecomment-2506139842

![image](https://github.com/user-attachments/assets/5c392050-5cc4-41c9-9944-1e9e2449c62f)

**Comment by 88250** [comment]
组合选项有什么建议？

**Comment by TCOTC** [comment]
现在的间隔是什么来着？

**Comment by 88250** [comment]
没有数据改变后 30s 进行同步，如果数据一直没有改动（云端或者本地），则根据当前相同次数逐步延长 2^n 分钟，最短 8 分钟，最长 2^9 分钟

**Comment by TCOTC** [comment]
最长 8.5 小时吗？

**Comment by 88250** [comment]
对的

**Comment by 88250** [comment]
等我考虑下，很早之前是有间隔设置的，后面移除了。

**Comment by 88250** [comment]
以秒为单位吧，范围 30-43200

**Comment by 88250** [comment]
以秒为单位，支持范围 30-43200，即 30 秒 - 12 小时

**Comment by TCOTC** [comment]
为啥 docker 和第三方同步不能用？

**Comment by 88250** [comment]
感谢指出，需要支持的，稍后解决。

**Comment by TCOTC** [comment]
@Vanessa219 这里不是按钮，光标不对，应该点数字输入框才能编辑：

![image](https://github.com/user-attachments/assets/a405d415-bfcc-48b5-a8de-5ffef89b3f6a)
