### ISSUE TITLE
你好，有计划支持yaml格式的文件显示吗？

### ISSUE THREAD

**Issue by DearZack** [siyuan-note/siyuan#13447]
### In what scenarios do you need this feature?

我复制了一个yaml格式的文件在笔记中，目前的显示是一个未知文件，希望可以支持显示

### Describe the optimal solution

我复制了一个yaml格式的文件在笔记中，目前的显示是一个未知文件，希望可以支持显示

**Comment by TCOTC** [comment]
截图看看怎么显示的？

**Comment by DearZack** [comment]
![image](https://github.com/user-attachments/assets/b0ebd4b7-0702-4216-b789-6a8fd542e9ae)

**Comment by TCOTC** [comment]
请给插件或主题仓库反馈

**Comment by royc01** [comment]
或者直接贴到代码块里面

**Comment by 88250** [comment]
文本文件类型目前不考虑支持，还是外部打开吧，感谢提议。
