### ISSUE TITLE
优化文档标签交互

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#13440]
@Vanessa219 如果搜索出来的标签已经被添加了，我觉得可以在后面显示一个 `√`

[video.webm](https://github.com/user-attachments/assets/621e151d-4c79-4a2c-aa50-0e279179c2b9)

---

然后这个空标签还是有问题：

[video.webm](https://github.com/user-attachments/assets/d9efae7c-5699-4525-9c03-34bad3276b8f)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/13311#issuecomment-2533746235_

**Comment by TCOTC** [comment]
标签前后的空格也要剔除：

[video.webm](https://github.com/user-attachments/assets/7a45512d-991a-40a0-b716-c0828bfc7bae)
