### ISSUE TITLE
改进启用`在当前页签中打开`时的前进后退

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13444]
### In what scenarios do you need this feature?

两种场景：
1. 简单浏览一些相关文档
2. 根据moc结构，一层层跳转到目标文档，或是在文档之间切换。

这两种场景里，很多文档只是临时打开一下，并不需要打开为新的标签页，不然关闭标签页的操作会变得非常频繁，会影响一些使用体验。

因此如果能支持 **在当前标签页覆盖打开** 就好了。
如果还能支持 `前进` 和 `后退` ，那就更完美了，就像浏览器标签页那样。

### Describe the optimal solution

因为目前的3种 "修饰键+左键单击" 的功能，都已被官方分配，所以或许可以给一个中键单击，中键单击为覆盖打开。

但个人感觉 最佳方案或许是 **支持对鼠标按键功能的修改** ，这样就可以让用户自行分配 "修饰键+左键单击" 的功能了。
就类似于自行分配快捷键那样。

也期待更优秀的方案。

**Comment by TCOTC** [comment]
感觉可以增加一种像 VSCode 那样的逻辑，单击是临时打开页签，双击是固定打开页签

**Comment by 88250** [comment]
用这个设置项吧：

![image](https://github.com/user-attachments/assets/224ebcd6-ff2e-4154-97b0-621b9cdc91b7)

**Comment by TCOTC** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/13446

**Comment by cordinGH** [comment]
> 用这个设置项吧：
> 
> ![image](https://github.com/user-attachments/assets/224ebcd6-ff2e-4154-97b0-621b9cdc91b7)
> 

@88250 d大有没有计划支持一下前进和后退？目前覆盖，无法做到这两点。

**Comment by Vanessa219** [comment]
前进后退指的是这个么？

![image](https://github.com/user-attachments/assets/4736b48e-7fff-4789-a533-3ef3c64c1e63)

**Comment by cordinGH** [comment]
> 前进后退指的是这个么？
> 
> ![image](https://private-user-images.githubusercontent.com/970828/395374654-4736b48e-7fff-4789-a533-3ef3c64c1e63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTI2NjgsIm5iZiI6MTczNDA1MjM2OCwicGF0aCI6Ii85NzA4MjgvMzk1Mzc0NjU0LTQ3MzZiNDhlLTdmZmYtNDc4OS1hNTMzLTNlZjNjNjRjMWU2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QwMTEyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjNkZDdhN2U1YTgzZjlmMmI4YzNmZTgxY2IyZTUyMzU3YzRiOGU1NmRiM2IyNzU0MDRlOTdiZTFiOTM2NDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rIX9DpiOmscF9uvatqbaOSjFHckawwO5Rcs6Z-oD5-I)

对的，但前进和后退时不时会无效，不太清楚什么原因
（下面视频中前半段有效，后半段就无效了）
https://github.com/user-attachments/assets/58663fb7-408e-46c2-b46b-d64a8391bd6b
