### ISSUE TITLE
改进页签样式

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13442]
现在这个页签用起来像 IDE，风格有点怪。我觉得 Obsidian 那种样式会舒服很多：

[video.webm](https://github.com/user-attachments/assets/c6d2ebb1-fb04-455a-a9f3-b9dde2d4efc7)

另外我觉得 .layout-tab-bar 不应该被高亮：

[video.webm](https://github.com/user-attachments/assets/69a71d5a-0089-4f2a-b4df-1288e085ac23)

**Comment by 88250** [comment]
后续放到 https://github.com/siyuan-note/siyuan/issues/10749 中考虑吧。

**Comment by TCOTC** [comment]
@88250 这个要重开

**Comment by 88250** [comment]
不用了吧，参考：

<img width="756" height="117" alt="Image" src="https://github.com/user-attachments/assets/23a5ba9d-3ab7-4436-bda8-b25ec4025da2" />

**Comment by TCOTC** [comment]
这个已经是旧版的 IDE 样式了，新主题到处都是圆角

**Comment by 88250** [comment]
暂时先不变了，你说的圆角的应该是 IsLands Dark 主题吧：

<img width="1324" height="338" alt="Image" src="https://github.com/user-attachments/assets/36166423-4a39-4e34-9a08-ead2e5636ab9" />

**Comment by TCOTC** [comment]
对，已经是默认主题了 [Meet the Islands Theme – The New Default Look for JetBrains IDEs | The JetBrains Platform Blog](https://blog.jetbrains.com/platform/2025/12/meet-the-islands-theme-the-new-default-look-for-jetbrains-ides/)

**Comment by 88250** [comment]
暂时不跟进了，等以后有空再看吧 😂

**Comment by 88250** [comment]
后续请关注 https://github.com/siyuan-note/siyuan/issues/17384
