### ISSUE TITLE
关于复制文章到知乎图片上传失败的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1344]
### 描述问题 Describe the problem

复制文章到知乎，图片上传失败

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/47321059/106242846-4e3ec700-6243-11eb-8861-330d193bf448.png)

### 版本环境 Version environment

* 版本 Version：0.6.7
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，目前确实有这个问题：

* https://github.com/siyuan-note/siyuan/issues/448
* https://ld246.com/article/1606827532185

暂时还没有找到解决方案，如果找到的话会在 #448 中解决，感谢反馈。
