### ISSUE TITLE
关于代码块之后的换行失效问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1345]
### 描述问题 Describe the problem

在代码块之后进行换行，功能失效。
类似于图片块之后的换行体验。

### 截屏或录屏演示 Screenshot or screen recording presentation

![ew12](https://user-images.githubusercontent.com/47321059/106246320-e25f5d00-6248-11eb-8eec-336e11080b17.gif)

### 版本环境 Version environment

* 版本 Version：0.6.8
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
跳出代码块编辑请用这个 
![image](https://user-images.githubusercontent.com/873584/106253526-90233980-6252-11eb-9da0-4e3cdee8cfd3.png)
