### ISSUE TITLE
就一个软件更新整不明白，还有脸让人付费。webdav都不给用，辣鸡。

### ISSUE THREAD

**Issue by houhed** [siyuan-note/siyuan#13453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

win版本，关闭软件提示升级，点升级提示有data文件要求移除，移除完data文件夹更新进度条走动，数秒后，卒，提示程序在运行，强行关闭，更新终止，重新运行程序更新，又生个data文件夹出来，然后继续提示要移动data文件夹，再移动再更新再提示程序在运行。你说辣鸡不辣鸡。webdav都收费，臭不要脸。分享不起别分享啊。

### Expected result

辣鸡，有脸收费？

### Version environment

```markdown
win10
```

### Log file

已卸载

### More information

已卸载

**Comment by royc01** [comment]
如果遇到bug可以录屏提交的，issue也不是用来撒泼的。至于webdav收不收费，谁该你的？笔记软件喜欢用哪个就用哪个，没必要在网络上把自己的素质展现得那么“淋漓尽致”。

**Comment by houhed** [comment]
辣鸡，问题都不敢回应。

**Comment by houhed** [comment]
> 如果遇到bug可以录屏提交的，issue也不是用来撒泼的。至于webdav收不收费，谁该你的？笔记软件喜欢用哪个就用哪个，没必要在网络上把自己的素质展现得那么“淋漓尽致”。

辣鸡不让说？

**Comment by houhed** [comment]
> 如果遇到bug可以录屏提交的，issue也不是用来撒泼的。至于webdav收不收费，谁该你的？笔记软件喜欢用哪个就用哪个，没必要在网络上把自己的素质展现得那么“淋漓尽致”。

收费啊。让你收。我就不付，气死你。我用GoodSync做多端同步，怎么样，气死你，气死你。不过呢，更新都做不清楚，这么辣鸡我也不想用，已经删了这辣鸡了。

**Comment by royc01** [comment]
你付不付关我啥事？我只是来观赏一下生物的多样性。🤣

**Comment by houhed** [comment]
> 你付不付关我啥事？我只是来观赏一下生物的多样性。🤣

嗯。你不是多样性之一？

**Comment by yuanjieyu** [comment]
笑死，一个人连软件更新用都用不明白，跑来这撒泼打滚，也不知道两个耳朵中间夹的是个什么东西hhh

**Comment by houhed** [comment]
> 笑死，一个人连软件更新用都用不明白，跑来这撒泼打滚，也不知道两个耳朵中间夹的是个什么东西hhh

是你爹

**Comment by royc01** [comment]
对啊，互相展现嘛，大伙不要跟他吵架，静静观察完事。🤣

**Comment by woniuxia** [comment]
厌蠢症犯了。
看这个人的资料，就是单纯过来找事的，大伙散了吧。

**Comment by yuanjieyu** [comment]
> > 笑死，一个人连软件更新用都用不明白，跑来这撒泼打滚，也不知道两个耳朵中间夹的是个什么东西hhh
> 
> 是你爹

哟，怎么？不会用就是不会用，没脑子就是没脑子，你bb的再多也排不出脑子里晃荡的水

**Comment by yuanjieyu** [comment]
> > 笑死，一个人连软件更新用都用不明白，跑来这撒泼打滚，也不知道两个耳朵中间夹的是个什么东西hhh
> 
> 是你爹

抱歉，我说错了，你压根就没脑子，怎么进水啊

**Comment by KuiyueRO** [comment]
盲猜你没注意提示将工作空间设置在程序路径下了，并且你是通过启动关闭应用程序进行更新的（或是系统有权限问题导致思源没有完全关闭）？

然后打开思源就要打开那个工作空间，打开那个工作空间就要生成data文件夹，这就进入了死循环🥲

**Comment by TCOTC** [comment]
把这个用户 block 吧

**Comment by DostGit** [comment]
> > 如果遇到 bug 可以录屏提交的，issue 也不是用来撒泼的。至于 webdav 收不收费，谁该你的？笔记软件喜欢用哪个就用哪个，没必要在网络上把自己的素质展现得那么 “淋漓尽致”。
> 
> 收费啊。让你收。我就不付，气死你。我用 GoodSync 做多端同步，怎么样，气死你，气死你。不过呢，更新都做不清楚，这么辣鸡我也不想用，已经删了这辣鸡了。

你连每年100的东西都买不起，你叫个j8
