### ISSUE TITLE
/api/block/updateBlock 更新问题

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/siyuan#13459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用 `/api/block/updateBlock` 更新 dom 时，更新成功，但是页面对应块会消失，重新加载页面才会显示出来：
### 请求头
~~~ http
POST  /api/block/updateBlock
{
  "id": "20241213225048-pdd5n9o",
  "dataType": "dom",
  "data": "<div data-node-id=\"20241213225048-pdd5n9o\" data-node-index=\"2\" data-type=\"NodeParagraph\" class=\"p\" updated=\"20241213225320\"><div contenteditable=\"true\" spellcheck=\"false\"><span data-type=\"code\">ss</span>s<span data-type=\"code\">​ss</span>​</div><div class=\"protyle-attr\" contenteditable=\"false\">​</div></div>"
}
~~~

### 响应
~~~ json
{
  "code": 0,
  "msg": "",
  "data": [
    {
      "timestamp": 0,
      "doOperations": [
        {
          "action": "update",
          "data": "<div data-node-id=\"20241213225048-pdd5n9o\" data-node-index=\"1\" data-type=\"NodeParagraph\" class=\"p\" updated=\"20241213225320\"><div contenteditable=\"true\" spellcheck=\"false\">​<span data-type=\"code\">​ss</span>​s<span data-type=\"code\">​ss</span>​</div><div class=\"protyle-attr\" contenteditable=\"false\">​</div></div>",
          "id": "20241213225048-pdd5n9o",
          "parentID": "",
          "previousID": "",
          "nextID": "",
          "retData": null,
          "blockIDs": null,
          "blockID": "",
          "deckID": "",
          "avID": "",
          "srcIDs": null,
          "srcs": null,
          "isDetached": false,
          "ignoreFillFilter": false,
          "name": "",
          "type": "",
          "format": "",
          "keyID": "",
          "rowID": "",
          "isTwoWay": false,
          "backRelationKeyID": "",
          "removeDest": false
        }
      ],
      "undoOperations": null
    }
  ]
}
~~~

### Expected result

`/api/block/updateBlock` 通过 dom 更新块后，对应块直接显示更新后的结果，不用重载整个页面。

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/d9396152-29c8-4b6f-b23b-0f520100c415)
![image](https://github.com/user-attachments/assets/b460d141-6031-497a-95c7-d0c5d989252e)

### Version environment

```markdown
- Version: 3.1.15
- Operating System: windows10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18127964/siyuan.log)

**Comment by 88250** [comment]
我这里测试正常，更新以后编辑器会自动刷新的，建议在默认主题下关闭所有代码片段、扩展等后测试。

**Comment by Achuan-2** [comment]
/api/block/updateBlock更新块貌似无法ctrl➕z撤回

**Comment by 88250** [comment]
是的，内核 API 均不支持撤销。



---原始邮件---
发件人: "Jixiong ***@***.***&gt;
发送时间: 2024年12月15日(周日) 晚上7:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] /api/block/updateBlock 更新问题 (Issue #13459)




 
/api/block/updateBlock更新块貌似无法ctrl➕z撤回
