### ISSUE TITLE
firefox 浮窗 无法关闭

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#13454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 网络伺服，在 firefox 中打开
2. 点击引用块弹出浮窗
3. 点击浮窗关闭

报错如下
Uncaught TypeError: t.highlight.markHL is undefined
    i_ http://127.0.0.1:6806/stage/build/desktop/main.0e0a0b0fc1fd82607234.js:1037

### Expected result

正常关闭

### Version environment

```markdown
- Version: v3.1.15
- Operating System: 
- Browser (if used):firefox
```

### Log file

none

**Comment by TCOTC** [comment]
相关反馈 https://ld246.com/article/1733997764177

**Comment by Vanessa219** [comment]
e9bddf922477a47390e47f8b1a2342385c468332

**Comment by Vanessa219** [comment]
不拉进 3.1.16 了
