### ISSUE TITLE
Add SQL query template function `querySQL`

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13455]
增加 `querySQL` 模板函数

需要查 refs 表

![image](https://github.com/user-attachments/assets/02656530-82bb-41e6-8600-2944d16d4fab)

**Comment by 88250** [comment]
要不直接加个 querySQL 吧，更通用点。

**Comment by TCOTC** [comment]
所有表都能查吗？

**Comment by 88250** [comment]
对，和那个内核 sql 接口差不多

**Comment by TCOTC** [comment]
那就加这个吧

**Comment by TCOTC** [comment]
这个会报错：模板解析失败：template: :1:8: executing "" at <querySQL>: wrong number of args for querySQL: want 1 got 2 v3.1.17

```
 .action{querySQL "SELECT * FROM spans LIMIT ?" "3"}
```

**Comment by 88250** [comment]
这个不支持预编译 SQL，只能把参数拼进去。
