### ISSUE TITLE
数据库应用反链后 文档无法看到数据库的反链

### ISSUE THREAD

**Issue by zongqir** [siyuan-note/siyuan#13456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当我将文档添加到数据库中 无法看到这个文档被数据库引用

### Expected result

看不到反链

### Version environment

```markdown
似乎是个历史BUG
```

### Log file

这个不需要 稳定浮现

**Comment by 88250** [comment]
数据库绑定块不纳入引用反链面板。
