### ISSUE TITLE
代码块的优化

### ISSUE THREAD

**Issue by impasse** [siyuan-note/siyuan#1346]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/8296340/106265628-47737c80-6262-11eb-8724-03aade16dbc0.png)

代码块的语言下拉框应该有个空的配置，针对不支持的语言或者不需要配置语言的场景。

语言下拉框最好支持 pageup/pagedown 翻页。

语言下拉框按包含字符过滤的结果有点冗余，按前缀过滤更符合习惯，

### 描述最优的解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/8296340/106268291-d8982280-6265-11eb-8e28-9d1dc8748842.png)

typora 的设计感觉更舒服一点

### 其他信息 Other information

另外这个框不自动关掉，应该算bug

![image](https://user-images.githubusercontent.com/8296340/106268459-1c8b2780-6266-11eb-87c1-439298f9af25.png)

**Comment by 88250** [comment]
你好，候选列表关闭需要手动 Esc 一下，这部分设计目前感觉还行，就暂时不改了，感谢反馈。
