### ISSUE TITLE
Search preview area supports inline memo positioning

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13465]
搜索预览区支持备注定位

### In what scenarios do you need this feature?

![PixPin_2024-12-14_22-54-34](https://github.com/user-attachments/assets/c93b84fb-6377-43c7-9e07-4bd3c66edf85)
搜索命中备注内容时不会跳转，搜索结果一旦多了，查看起来有些困难。

### Describe the optimal solution

效果可以参考插件 [基于文档搜索](https://github.com/Misuzu2027/syplugin-document-search)
![PixPin_2024-12-14_22-59-10](https://github.com/user-attachments/assets/674a0d45-11bd-4e75-978c-e2f94b3066d6)

### Other information

当跳转搜索条目时，或许可以给这个块短暂高亮一下，这样用户就可以一眼看到是哪个块了。
效果如下图。
![PixPin_2024-12-14_23-07-06](https://github.com/user-attachments/assets/3b19fae9-eaa9-4dc8-9679-5b1e904b085f)

**Comment by TCOTC** [comment]
等下个版本再试试
