### ISSUE TITLE
突发奇想，可否增加一个用户自定义块？

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#13474]
### In what scenarios do you need this feature?

有时，需要对某个块魔改，但受限于思源对块属性和块内元素的限制，改起来总是束手束脚的。

如果能有一种块类型，比如叫用户自定义块，这个块内的元素用户可以完全自定义，思源只需要无脑渲染块内的HTML元素即可。

这样，以后实现某种自定义功能就非常方便了。

不清楚思源内部实现逻辑，不知是否好实现。

如果能实现就最好了。

### Describe the optimal solution

用户可插入自定义块，块内元素可自由发挥。

**Comment by 88250** [comment]
* 可以考虑用挂件块、HTML 块
* 另外就是 https://github.com/siyuan-note/siyuan/issues/8418

**Comment by wish5115** [comment]
> * 可以考虑用挂件块、HTML 块
> * 另外就是 [Support for inserting custom blocks #8418](https://github.com/siyuan-note/siyuan/issues/8418)

好的，学习了，感谢D大，原来官方已经有计划了。
