### ISSUE TITLE
Mac端支持url-schemes

### ISSUE THREAD

**Issue by LeokuJessica** [siyuan-note/siyuan#1347]
采用本地跳转(不用网页端),可在设置里选择网页端跳转url/本地跳转(考虑到windows不知道有没有,也许这个功能要在打造差异化的时候引入)   siyuan://open-notes
参考:craft for Mac,https://mp.weixin.qq.com/s/_41NT6_XFrJfNa_1owAffw 
需求场景: mac自动化工作流中软件的联动

**Comment by 88250** [comment]
你好，之前我们考虑过，但是我们觉得通过 URL 更符合设计目标，在浏览器上直接使用。

感谢反馈。

**Comment by LeokuJessica** [comment]
其实之后可以留下一个设置选项,之后可以让用户自己去设计他们的需求,本人不太了解url schemes要实现的技术手段的复杂程度,如果不是太费时间的话,希望之后考虑打造客户端差异化的时候可以再次回顾一下需求,现阶段由于人员精力问题肯定版本都是高度一致的,每个系统特性不一样,希望之后有更多mac的差异化特性.(虽然现在说的太早了,不过真的希望思源在做好功能的同时,尝试结合每个系统的特性提高用户的体验感,另外的比如说menubar引入速记/和mac的软件联动)😊
