### ISSUE TITLE
改进文档树展开图标误触问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13471]
参考 Notion 的设计，将展开和图标进行合并，避免误触的同时也可以减小宽度占用。不过这个方案也有个缺点：无法直接看出是否存在子文档。

**Comment by TCOTC** [comment]
这个缺点我接受不了

**Comment by TCOTC** [comment]
这个缺点我接受不了

**Comment by congSjwbsz** [comment]
还是不要合并吧？无法直接看出是否存在子文档，在体验上就不好，还不如占用下空间

**Comment by MisakaImouto8912** [comment]
我支持点击图标可以展开子文档，更换图标对我来说是低频操作，但是千万别隐藏展开按钮啊，看不出有没有子文档太糟糕了！

**Comment by SaXz2** [comment]
希望不要合并在一起，误处可以用css处理

**Comment by Achuan-2** [comment]
图标误触用css解决吧
原来的js逻辑不用删
就用css取消点击事件
喜欢折腾图标的用户，自己加css代码片段
因为我觉得喜欢折腾图标，应该也是愿意折腾下css
但是不喜欢折腾图标的人，估计是不愿意折腾css代码片段的，或许连主题都懒得折腾

**Comment by 88250** [comment]
那就还是 CSS 代码片段解决吧，感谢各位讨论。

**Comment by Achuan-2** [comment]
> 图标误触用css解决吧 原来的js逻辑不用删 就用css取消点击事件 喜欢折腾图标的用户，自己加css代码片段，启用点击修改图标 因为我觉得喜欢折腾图标，应该也是愿意折腾下css的，折腾美化就是他们的乐趣之一 但是不喜欢折腾图标的人，估计是不愿意折腾css代码片段的，或许连主题都懒得折腾 看思源想要讨好哪类人群

我觉得还是默认禁用文档树直接修改图标，需要的用户自己用css片段开启比较合适

**Comment by Achuan-2** [comment]
问题是文档树图标直接修改，没有这个功能，不会被骂，但是有这个功能，反而会被吐槽，吐槽帖子也不少了

**Comment by TCOTC** [comment]
> 没有这个功能，不会被骂

去链滴发个投票吧，看看实际的用户需求
