### ISSUE TITLE
列表回车导致图片缩放失效的问题

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1348]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106278197-45ff7f80-6275-11eb-82d6-5fb8e9e0bc07.mp4

如视频，9处粘贴图片，缩小图片，图片末尾处enter：图片的缩放失效
这不合理

### 期待的结果 Expected result

图片的缩放不失效

* 版本 Version：0.7.0

**Comment by wo4wangle** [comment]
@88250 我在0.7.5上测试，这个问题依旧，bug case和这个issue的保持完全一致

**Comment by 88250** [comment]
@wo4wangle 078 继续修复，发布后请帮忙回测，谢谢。
