### ISSUE TITLE
新建代码片段不显示

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13499]
新建工作空间，导入 Data：[代码片段-20241216163744.zip](https://github.com/user-attachments/files/18147115/-20241216163744.zip)

[video.webm](https://github.com/user-attachments/assets/068160c2-f1f9-485c-9ea5-7b6c13a289a1)

**Comment by 88250** [comment]
可能是里面有什么代码片段影响了，我这里全部禁用后再添加没有问题。

**Comment by TCOTC** [comment]
确实
