### ISSUE TITLE
关于无法识别用户自建的md文件的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1349]
### 描述问题 Describe the problem

自建Markdown文件，但思源内部文件树无法识别

### 截屏或录屏演示 Screenshot or screen recording presentation

![ew123](https://user-images.githubusercontent.com/47321059/106280818-5f0a2f80-6279-11eb-9f6f-668944ed5d3d.gif)

### 版本环境 Version environment

* 版本 Version：0.6.8
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，目前是设计如此，不会监听文件变化，并且已有的 Markdown 文件需要通过界面导入，感谢反馈。

**Comment by dejavudwh** [comment]
好的 感谢
