### ISSUE TITLE
有使用的资源文件会被认为未引用

### ISSUE THREAD

**Issue by 397334469** [siyuan-note/siyuan#13497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图，图片是有实际使用的
![image](https://github.com/user-attachments/assets/f0d8f258-27ce-42c2-b8bd-174602b773e3)
但是这儿显示为未引用
![image](https://github.com/user-attachments/assets/e5ce987c-7113-4169-aa16-ccea5b27df65)
为什么会发现这个BUG？因为有误删掉过，所以现在都不敢再删这些图片了~

### Expected result

正确统计

### Version environment

```markdown
- Version: v3.1.15
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18143778/siyuan.log)

**Comment by 88250** [comment]
这个是个网络图片，并不是本地资源文件：

![image](https://github.com/user-attachments/assets/da5b83c5-92cf-4d3c-9b16-8833e5682f60)

**Comment by 397334469** [comment]
![image](https://github.com/user-attachments/assets/b431249e-a3b1-4c3d-b999-ba52c4b59ed7)
D大，看看这图的右上角。这图片是本地图片啊，不知道为什么会有左上角的图标。这应该又是另外一个BUG。

**Comment by 88250** [comment]
那个只是图片的文本信息，不是实际路径，你可以右键图片看下实际的图片地址。

**Comment by 88250** [comment]
这里多了个空格：

![image](https://github.com/user-attachments/assets/975e6e9f-ffbc-49ec-b1ce-dc17a6fa34c9)

**Comment by 397334469** [comment]
嗯，确实是有这个空格。这个空格不知道是什么功能引入的。后面再有发现这种，到时再反馈。

**Comment by TCOTC** [comment]
感觉是不是应该自动去除链接首尾的空字符？

**Comment by TCOTC** [comment]
关闭菜单的时候就应该去掉空白字符了：

[video.webm](https://github.com/user-attachments/assets/814109bb-b7be-4640-806f-ea92ba6545e7)

**Comment by 88250** [comment]
@Vanessa219
