### ISSUE TITLE
窗口未激活时顶部单像素宽的白边

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#1350]
### 描述问题 Describe the problem

窗口未激活时, 顶部有1像素的白边(以daylight为例, 与底色有关)

### 期待的结果 Expected result

无该条白边

### 截屏或录屏演示 Screenshot or screen recording presentation

参见 #1333

### 版本环境 Version environment

* 版本 Version：0.7.0
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：NA

### 日志文件 Log

NA

### 更多信息 More information

#1333

**Comment by Vanessa219** [comment]
设计如此，以表示当前窗口没有激活。

**Comment by yuuuxt** [comment]
审美上看 hmm...
