### ISSUE TITLE
改进块引导出 Markdown 锚点哈希

### ISSUE THREAD

**Issue by JayceVane** [siyuan-note/siyuan#13505]
### In what scenarios do you need this feature?

导出markdown后超链接失效了，markdown 导出默认带题头图

### Describe the optimal solution

希望后续能够支持保留超链接的markdown导出。同时能够给予用户选择是否导出题头图的选项

**Comment by TCOTC** [comment]
什么超链接？把文档发一下看看？

**Comment by JayceVane** [comment]
就是针对子文档的链接会消失

**Comment by JayceVane** [comment]
就是我在主文档下生成子文档的链接，然后再导出markdown是勾选包括子文档，之后主文档下对子文档的链接就会消失，变成文本了。

**Comment by 88250** [comment]
* 试试 设置 - 导出 - 引用 - 脚注+锚点哈希
* 题头图暂时不考虑取消

**Comment by JayceVane** [comment]
不行，直接变成代码块了，而不是引用子文档的相对路径
[矩阵论.md.zip](https://github.com/user-attachments/files/18163415/md.zip)
锚文本链接的的话直接指向思源笔记里的子文档去了，而不是导出的markdown子文档

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/13500 中处理。
