### ISSUE TITLE
请更新Ai功能，支持Gemini、Claude。

### ISSUE THREAD

**Issue by HaiSeaman** [siyuan-note/siyuan#13508]
### In what scenarios do you need this feature?

现在写文案越来越依赖Ai了。特别是想用Gemini和Claude.

### Describe the optimal solution

有没有更新Ai功能支持Gemini、Claude的计划呢？

**Comment by TCOTC** [comment]
暂无计划 https://github.com/siyuan-note/siyuan/issues/9262

**Comment by 88250** [comment]
请考虑通过插件支持。
