### ISSUE TITLE
搜索结果用固定窗格显示

### ISSUE THREAD

**Issue by hyjwonder** [siyuan-note/siyuan#1351]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

用关键词进行全局搜索时

### 描述最优的解决方案 Describe the optimal solution

目前搜索结果用弹出窗口显示，选中一个结果后，可以跳转到原文，但结果列表就消失了。需要用一个固定窗格显示结果列表。
RoamEdit搜索结果在右侧固定窗格显示。

### 描述候选解决方案 Describe the candidate solution

无

### 其他信息 Other information

无
<img width="1439" alt="CleanShot 2021-01-29 at 23 16 39@2x" src="https://user-images.githubusercontent.com/77609410/106292733-22920000-6288-11eb-8ef5-29cb8695de16.png">
<img width="1426" alt="CleanShot 2021-01-29 at 23 16 14@2x" src="https://user-images.githubusercontent.com/77609410/106292792-350c3980-6288-11eb-9e4d-ec6b47a57258.png">

**Comment by 88250** [comment]
请使用搜索页签：

![image](https://user-images.githubusercontent.com/873584/106293108-9207ef80-6288-11eb-8fde-63ea4710fb7b.png)

**Comment by hyjwonder** [comment]
谢谢D大！基本解决了。
