### ISSUE TITLE
疑问：代码片段输入框默认显示两行是如何实现的？

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13518]
比如图片是默认一行：

![image](https://github.com/user-attachments/assets/c1bc6754-ddb4-4acf-b1cc-1b467592b6a2)

代码片段是默认两行：

![image](https://github.com/user-attachments/assets/0ca0f7e0-4913-4c35-a983-9a547479b365)

我看代码没看出来是怎么控制的

**Comment by 88250** [comment]
textarea 默认就是两行。

**Comment by TCOTC** [comment]
那一行又是怎么实现的？

**Comment by TCOTC** [comment]
噢我看到了 `rows="1"`
