### ISSUE TITLE
优化数据库视图切换逻辑，当前视图不重复加载

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13512]
为什么一点这个按钮，视图就要更新：

[video.webm](https://github.com/user-attachments/assets/600a733b-d8a3-4006-b0be-39cab2988b80)

还有 data-render 属性是做什么用的？

**Comment by Vanessa219** [comment]
需要切换到当前视图，可以改进一下。

用于判断是否渲染

**Comment by TCOTC** [comment]
还有点问题，这个 .b3-menu__item--current 完全不动：

[video.webm](https://github.com/user-attachments/assets/adb98d9c-2f40-4b85-a309-8a7147286eb4)
