### ISSUE TITLE
控制台警告

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13511]
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

![image](https://github.com/user-attachments/assets/575a4aa1-ab40-41e7-a447-42181a535195)

![image](https://github.com/user-attachments/assets/c737420c-6e6f-4648-a1ff-84b993c89f68)

**Comment by Vanessa219** [comment]
不拉进 3.1.18 版本了
