### ISSUE TITLE
数据库选项颜色不一致

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13529]
这个样式有问题：

![image](https://github.com/user-attachments/assets/bb60abdb-c9d9-45b2-b26b-48e22859869b)

用这个颜色之后选项的颜色会有相对明显的差异：

```css
:root{--b3-font-background1: rgb(255, 255, 204);}
```

![image](https://github.com/user-attachments/assets/6696efad-b559-4699-8657-bb5cc8013ca1)

**Comment by Vanessa219** [comment]
不拉进 3.1.18 版本 了
