### ISSUE TITLE
思源 chrome extension 剪辑页面漏英文空格

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#13521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源网页剪藏去掉了部分英文单词间的空格。

页面：https://cr.openjdk.org/~briangoetz/lambda/lambda-translation.html

页面文字：
![Xnip2024-12-18_10-25-18](https://github.com/user-attachments/assets/6bb5971c-3b3d-4e84-935e-cef8d452f4a6)

剪辑到思源笔记：
![Xnip2024-12-18_10-23-46](https://github.com/user-attachments/assets/e93b2e97-bf5a-4672-a8bf-e60eb239bcca)

### Expected result

英文空格间的空格保留

### Version environment

```markdown
chrome extension: 1.7.1
Siyuan: 3.1.15
OS: macOS 15.1.1
```

### Log file

无

**Comment by 88250** [comment]
我这里测试正常，建议排查是否是其他浏览器扩展影响的。

![image](https://github.com/user-attachments/assets/c9beee3c-f6d6-418a-9bff-e378cd83c627)

**Comment by TCOTC** [comment]
我这里也没少空格

**Comment by aGolduck** [comment]
![Xnip2024-12-18_12-44-05](https://github.com/user-attachments/assets/b945a66e-2760-4e2a-a612-57e5d7cb9004)
只有这个扩展

环境：
chrome:  131.0.6778.140（正式版本） (arm64)
macOS: 15.1.1
Siyuan: 3.1.15

有没有其他信息我可以提供

**Comment by 88250** [comment]
暂时不确定啥问题了，等会 @Vanessa219 用 macOS 测试看看

**Comment by Vanessa219** [comment]
这里无法重现

![image](https://github.com/user-attachments/assets/307d3149-1ee4-4239-88ef-fd078d6d98ca)

SiYuan Chrome 1.7.1
Chrome 131.0.6778.140（正式版本） (arm64)
macOS: 15.1.1
Siyuan: 3.1.16
