### ISSUE TITLE
Firefox下存在兼容性问题

### ISSUE THREAD

**Issue by cn-taoye** [siyuan-note/siyuan#13525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

打开左下角标签窗口中的任一标签，右侧会弹出“搜索”窗口。搜索窗口出现后，点击“搜索”窗口上的关闭图标无反应，不能关闭该窗口。同样情况下，Chrome不存在问题。

### Expected result

与chrome上的表现一致，点击关闭图标正常关闭该窗口。

### Version environment

```markdown
- Version: 3.1.15
- Operating System: Ubuntu 24.04.1 LTS

- Browser (if used): Firefox 133.0.3 (64-bit)
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2024/12/18 10:55:27 runtime.go:87: kernel is booting:
    * ver [3.1.15]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2024/12/18 10:55:27 conf.go:131: loaded conf [/siyuan/workspace/conf/conf.json]
I 2024/12/18 10:55:27 conf.go:290: upgraded from version [3.1.8] to [3.1.15]
I 2024/12/18 10:55:27 runtime.go:139: use network proxy [system]
I 2024/12/18 10:55:27 serve.go:209: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2024/12/18 10:55:27 conf.go:856: database size [6.76 MB], tree/block count [83/1429]
I 2024/12/18 10:55:27 working.go:193: kernel booted
I 2024/12/18 10:55:27 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 10:55:27 box.go:77: auto stat [trees=83, blocks=1429, dataSize=41.74 MB, assetsSize=4.54 MB]
E 2024/12/18 10:55:37 serve.go:552: get cookie failed: securecookie: error - caused by: securecookie: error - caused by: gob: decoding into local type *string, received remote type 
W 2024/12/18 10:55:37 serve.go:589: closed an unauthenticated session [125.71.203.130:59292]
E 2024/12/18 10:55:37 serve.go:552: get cookie failed: securecookie: error - caused by: securecookie: error - caused by: gob: decoding into local type *string, received remote type 
W 2024/12/18 10:55:37 serve.go:589: closed an unauthenticated session [125.71.203.130:59300]
E 2024/12/18 10:55:38 serve.go:552: get cookie failed: securecookie: error - caused by: securecookie: error - caused by: gob: decoding into local type *string, received remote type 
W 2024/12/18 10:55:38 serve.go:589: closed an unauthenticated session [125.71.203.130:59314]
E 2024/12/18 10:55:38 serve.go:552: get cookie failed: securecookie: error - caused by: securecookie: error - caused by: gob: decoding into local type *string, received remote type 
W 2024/12/18 10:55:38 serve.go:589: closed an unauthenticated session [125.71.203.130:59322]
E 2024/12/18 10:55:38 serve.go:552: get cookie failed: securecookie: error - caused by: securecookie: error - caused by: gob: decoding into local type *string, received remote type 
W 2024/12/18 10:55:38 serve.go:589: closed an unauthenticated session [125.71.203.130:59334]
E 2024/12/18 10:55:49 serve.go:552: get cookie failed: securecookie: error - caused by: securecookie: error - caused by: gob: decoding into local type *string, received remote type 
I 2024/12/18 10:55:52 session.go:121: auth success [ip=125.71.203.130:59348]
I 2024/12/18 10:56:01 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 10:57:44 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 10:58:08 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 10:58:49 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 11:02:41 session.go:121: auth success [ip=125.71.203.130:59198]
I 2024/12/18 11:02:41 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36]
I 2024/12/18 11:02:56 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 12:55:27 box.go:77: auto stat [trees=83, blocks=1429, dataSize=81.54 MB, assetsSize=4.54 MB]
I 2024/12/18 14:55:27 box.go:77: auto stat [trees=83, blocks=1429, dataSize=81.54 MB, assetsSize=4.54 MB]
I 2024/12/18 15:13:56 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0]
I 2024/12/18 15:48:56 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0]
I 2024/12/18 15:49:31 file.go:1730: removed doc [20240522162250-21owkmb/20240522162513-vxuh89x/20240522162513-gue96gb/20241202090719-v1qytiy/20241218103523-21zv0f7/20241218154925-mjvs4oo.sy]
I 2024/12/18 15:52:58 file.go:1730: removed doc [20240522162250-21owkmb/20240522162513-vxuh89x/20240522162513-gue96gb/20241202090719-v1qytiy/20241218103523-21zv0f7/20241218155130-4flp254.sy]
I 2024/12/18 15:54:18 session.go:121: auth success [ip=125.71.203.130:53648]
I 2024/12/18 15:54:18 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36]
I 2024/12/18 15:55:28 file.go:1730: removed doc [20240522162250-21owkmb/20240527155225-qvv5deu.sy]
I 2024/12/18 15:55:53 index.go:220: rebuilt database for notebook [20210808180117-czj9bvb] in [0.18s], tree [count=70, size=1.4 MB]
I 2024/12/18 15:55:53 index.go:290: resolved refs [37] in [69ms]
E 2024/12/18 15:56:07 bookmark.go:182: parse block [20210428212840-859h45j] failed: indexing
I 2024/12/18 15:56:10 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 16:25:17 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0]
I 2024/12/18 16:30:01 font.go:58: loaded system fonts [0] in [0ms]
I 2024/12/18 16:31:40 serve.go:314: serving [/] for user-agent [Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0]

**Comment by Vanessa219** [comment]
和 https://github.com/siyuan-note/siyuan/issues/13454 是同一个问题，下个版本修复
