### ISSUE TITLE
关于新版关系图的修改建议

### ISSUE THREAD

**Issue by alphaleek** [siyuan-note/siyuan#1352]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

建议1：全局关系图中，点击一个节点，显示完整的逻辑连线，而不是只显示该节点的相邻逻辑节点。
原因：全局关系图在整体上显示完整的逻辑连线，符合网状的思维模式。能更好的从整体把握知识体系。只显示相邻逻辑节点，虽然看起来简洁，但是更像是线性的思维。
解决方案：
方案1：:给用户自己选择的权力。关系图是选择更简洁，还是更网状。
方案2：或把相邻节点的连线做淡化处理，而不是用箭头来表现，箭头只能起到简洁的作用，但是看上去真的很不直观
![image](https://user-images.githubusercontent.com/76611744/106290690-b4e4d480-6285-11eb-89ec-605966465b7c.png)
![image](https://user-images.githubusercontent.com/76611744/106292351-b0212000-6287-11eb-9dcf-c82048c13ae9.png)
建议2：全局关系图中，对于被引用次数多的中心节点，希望可以用醒目的颜色标识出来。现在是中心节点的大小稍大一点，但是还是不直观。
![image](https://user-images.githubusercontent.com/76611744/106293017-78ff3e80-6288-11eb-8599-4e885b9c097b.png)
说的有点乱，希望D大能看懂啥意思。。

**Comment by 88250** [comment]
你好，只有箭头没有线可能是因为开启了自定义主题，关掉试试。

**Comment by alphaleek** [comment]
我太难了，打了半天字，发现是主题的问题。。。感谢D大

**Comment by 88250** [comment]
不好意思，幸苦了 😂
