### ISSUE TITLE
Compatible with Sogou input method to intelligently adjust punctuation after numbers

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#13528]
搜狗输入法智能调整标点功能在思源中不生效

### In what scenarios do you need this feature?

在输入时间时（例如12:00）时，很好用的功能 。不用频繁切换输入法了

![image](https://github.com/user-attachments/assets/793fe665-349d-4415-843a-425e63dffbc2)

### Describe the optimal solution

之前是生效的，最近几个版本不生效了

**Comment by ZSCN2024** [comment]
我也遇到这个问题了。以前数字后面按句号，会自动变成英文的点，现在要手动切换。

![image](https://github.com/user-attachments/assets/098ef7a5-525d-432a-911e-eb1b2a3a68e0)

**Comment by IAliceBobI** [comment]
我设置了自动补全标点，为什思源桌面版v3.1.16没有补全,  系统windows11




https://github.com/user-attachments/assets/9675f16c-1487-4daa-b05f-fa42f792a191

**Comment by ZSCN2024** [comment]
今天会发新版本修正这个BUG吗？
智能标点功能使用频率很高，思源里失效了，很影响使用。
目前唯一的解决方案是换输入法，但这样词库又没了

**Comment by 88250** [comment]
今天的版本不包含此项改进，计划在 v3.1.18 中解决。
