### ISSUE TITLE
Remove Sentry reporting diagnostic data

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13522]
https://github.com/siyuan-note/siyuan/issues/4338

它已经完成使命了，感谢开启这个开关帮忙反馈问题的用户 ❤️

**Comment by TCOTC** [comment]
这个原本是用来上传哪些报错信息的？

**Comment by 88250** [comment]
堆栈中的报错信息，就是日志打印 error 那些。

**Comment by woniuxia** [comment]
以后有新的反馈组件吗？还是直接不要了？
