### ISSUE TITLE
希望状态栏可以设置只保留字数之类的统计

### ISSUE THREAD

**Issue by ningchenyu** [siyuan-note/siyuan#13537]
### In what scenarios do you need this feature?

写东西的时候想只看到字数的统计，但又不想看到索引创建之类的动态，因为它总是很频繁是在创建索引，觉得有点烦人。但又想看到实时的字数统计。希望可以单独设置只看到字数之类的统计，不用看到那些创建索引的提示。

### Describe the optimal solution

建议在隐藏底部状态栏下增加子选项，1.字数统计类，2.创建索引类，3.同步类，4.下载安装包进度 等等...

**Comment by TCOTC** [comment]
虽然能用 CSS 隐藏，但我也觉得应该内置一下，比如叫“隐藏底部状态栏信息”

**Comment by ningchenyu** [comment]
> 虽然能用 CSS 隐藏，但我也觉得应该内置一下，比如叫“隐藏底部状态栏信息”
我学会了，谢谢
.status__msg, .status__backgroundtask
{
	display: none !important;
}
