### ISSUE TITLE
新增百度云、蓝奏云下载渠道

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1353]
### 描述问题 Describe the problem

思源当前的两个下载渠道：github和思源官网都存在下载速度问题。

github即使在使用VPN或者下载加速工具也不能达到理想速度，并且对一般的用户不友好。
思源官网的速度则有时只能达到几kb

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/47321059/106308987-73135880-629c-11eb-9ab0-0f063e22b265.png)

![image](https://user-images.githubusercontent.com/47321059/106309052-8de5cd00-629c-11eb-815d-3380f293f366.png)

### 可能的解决方案

考虑到发展初期，不负担额外的服务器费用，可以尝试使用第三方提供的网盘

**Comment by 88250** [comment]
谢谢建议，能推荐下你认为比较好的网盘服务吗？

**Comment by dejavudwh** [comment]
作为资源下载方，体验比较好的有：诚通网盘，蓝奏云。因为有会员，所以百度网盘的体验也不错。但是诚通和蓝奏云没有试过做资源分享方，蓝奏云对大文件分享应该是有限制的。
