### ISSUE TITLE
Sticky search when scrolling in database

### ISSUE THREAD

**Issue by FancyBEAST** [siyuan-note/siyuan#13533]
### In what scenarios do you need this feature?

When you scroll in a long database the search bar is not available for quick searches.
![image](https://github.com/user-attachments/assets/3152c3d5-95b0-4857-aea9-a58c780c668b)
- Before scrolling
![image](https://github.com/user-attachments/assets/b10184c7-a881-417c-9ce9-14c3e28aebd3)
- During scrolling

### Describe the optimal solution

The search bar and filter should be available during scrolling.

### Describe the candidate solution

same as above.

**Comment by TCOTC** [comment]
FlowUs 的移动端是这样的，搜索单独放一行，宽度够大，SiYuan 可以参考：

FlowUs mobile is like this, the search is in a separate line, the width is big enough, SiYuan can refer to:

![51a9dd9d95a7b0e7b73a8513892f93a](https://github.com/user-attachments/assets/130e9251-3173-4c41-9e9e-5bb105524509)

**Comment by FancyBEAST** [comment]
@TCOTC won't it be possible to have the entire top bar except the title be sticky? It will be really helpful to switch between views, filtering, searching without scrolling all the way to the top. What do you think?

**Comment by 88250** [comment]
Referring to the design of Notion, the top toolbar will not be pinned when scrolling, only the table header will be pinned. This design is not considered to be changed for the time being. Thanks for the suggestion.

**Comment by FancyBEAST** [comment]
I don’t think it’s necessary for the top toolbar to be pinned since most of its functions, like filter and sort, are already accessible through the 3 dot menu. However, search isn’t available there, and scrolling all the way to the top to use it can be a hassle in large databases.

Would it be possible to add a hotkey to trigger the search function from anywhere on the database instead? Alternatively, how about integrating it with SiYuan’s default search window? Currently, the default search refers to the entire database, which isn’t very useful in this context. Perhaps it could be adapted to focus on specific fields instead. What do you think?
