### ISSUE TITLE
zip: not a valid zip file v3.1.16

### ISSUE THREAD

**Issue by gaoliuzhu** [siyuan-note/siyuan#13539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

导出的s3配置文件，重新导入移动端和pc端都会报错：zip：不是有效的zip文件v3.1.16

<img width="881" alt="image" src="https://github.com/user-attachments/assets/9b2e1939-dbda-49aa-a41c-65d0fa9e9c62" />
没有对导出的s3配置文件做任何的修改：
<img width="785" alt="image" src="https://github.com/user-attachments/assets/132a8fb7-b6d3-4655-934d-2c27b2a4bb9e" />

### Expected result

应该能正确的导入s3的配置

### Version environment

```markdown
-版本：v3.1.16
-操作系统：iOS18.2 or Mac OS 15.2
-浏览器（如果使用）：
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18192148/siyuan.log)

**Comment by gaoliuzhu** [comment]
safari浏览器自己把zip解压了的原因，忽略

**Comment by TCOTC** [comment]
@88250 感觉是不是也能兼容一下直接导入 json 文件？
