### ISSUE TITLE
属性面板移除数据库加入数据历史和交互改进

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13536]
关联 #13375

**Comment by Vanessa219** [comment]
这个好像没必要呀。

**Comment by TCOTC** [comment]
hover 时图标变红，再用红色的悬浮提示 https://github.com/siyuan-note/siyuan/pull/13476

![image](https://github.com/user-attachments/assets/79a625e6-0e79-4a4f-8d26-b3b2d18e4842)

**Comment by TCOTC** [comment]
我刚刚发现移除条目没有数据历史

**Comment by 88250** [comment]
> 我刚刚发现移除条目没有数据历史。数据库所在文档应该要生成历史的（即使这个文档没有打开）。

稍后改进
