### ISSUE TITLE
导出 PDF 显示的字体需要跟编辑器字体设置一致

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13534]
关联 #13241

![image](https://github.com/user-attachments/assets/a959b962-0918-4797-91fa-d54d46f2be9e)

![image](https://github.com/user-attachments/assets/a12259a3-774c-4dc3-8146-63560c488323)

**Comment by Vanessa219** [comment]
和 https://github.com/siyuan-note/siyuan/issues/13550 是一个同一个问题导致的。
