### ISSUE TITLE
数据库没有显示文档图标

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13530]
[测试文档.sy.zip](https://github.com/user-attachments/files/18184899/sy.zip)

没有显示图标：

![image](https://github.com/user-attachments/assets/6ecb1d21-a12a-4733-8666-6221280dabd7)

**Comment by 88250** [comment]
稍后

**Comment by TCOTC** [comment]
重新导入的正常了，但之前没显示的还是没显示
