### ISSUE TITLE
标签异常的产生以及无法正常的删除

### ISSUE THREAD

**Issue by davincilll** [siyuan-note/siyuan#13546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="669" alt="image" src="https://github.com/user-attachments/assets/28458479-a9ea-496c-b09a-eedd934f0cf2" />
在使用思源插件或者简悦剪藏插件时会出现一些奇怪的标签，并且部分标签无法被删除
<img width="763" alt="image" src="https://github.com/user-attachments/assets/12a648c8-500f-4de8-8ffd-d59c1785066f" />

### Expected result

没有异常的标签随着剪藏而增加

异常的标签可以被成功的删除

### Version environment

```markdown
- Version: latest
- Operating System: mac
- Browser (if used): no
```

### Log file

I 2024/12/19 18:57:15 repository.go:1429: syncing data repo [device=E61A108C-A936-561D-87F7-FB6B171CB1A0, kernel=155hlur, provider=2, mode=a/false]
I 2024/12/19 18:57:15 repo.go:661: walk data [files=12861] cost [182.198625ms]
I 2024/12/19 18:57:15 repo.go:770: get latest files [files=12861] cost [45.314333ms]
I 2024/12/19 18:57:16 ref.go:64: updated local latest to [device=E61A108C-A936-561D-87F7-FB6B171CB1A0/darwin, id=deb5724205941c1aa3277184760fba12e548eadb, files=12861, size=1.55 GB, created=2024-12-19 18:57:16]
I 2024/12/19 18:57:16 sync.go:1580: got cloud latest [device=E61A108C-A936-561D-87F7-FB6B171CB1A0/darwin, id=bb57fdaaecb317586e99b92e3e10018288083921, files=12861, size=1.55 GB, created=2024-12-19 18:10:25], cost [273.988292ms]
I 2024/12/19 18:57:16 sync.go:247: got local latest [deb5724205941c1aa3277184760fba12e548eadb] files [12861]
I 2024/12/19 18:57:16 sync.go:1450: got latest sync [device=E61A108C-A936-561D-87F7-FB6B171CB1A0/darwin, id=bb57fdaaecb317586e99b92e3e10018288083921, files=12861, size=1.55 GB, created=2024-12-19 18:10:25]
I 2024/12/19 18:57:16 diff.go:49: upsert [lID=56b2b57d8184cfc413df9ee26ec165f0228bbf37, lPath=/storage/petal/kmind/config/license.kmindconf, lUpdated=2024-12-19 18:10:01, rID=93b266193b1bb216632f8ea69e9e62c8d086e4ec, rPath=/storage/petal/kmind/config/license.kmindconf, rUpdated=2024-12-19 18:52:32]
I 2024/12/19 18:57:16 diff.go:49: upsert [lID=0af996455a8bdd7e67ea18a90e93e8d3b9f5a2c1, lPath=/20240225215122-vodfrm5/20240315181307-vieunhw.sy, lUpdated=2024-12-19 18:10:00, rID=a2e275bcf21fbd79421963294d45cee49cf40759, rPath=/20240225215122-vodfrm5/20240315181307-vieunhw.sy, rUpdated=2024-12-19 18:52:31]
I 2024/12/19 18:57:16 diff.go:49: upsert [lID=d18cd53b3a88dc3431fb93d401a7223737f383ee, lPath=/20240904214053-6pvvsr9/20240522124541-dxyfpda/20240522124001-3kpqt9g/20240328200911-8jvdtka/20240328212231-326o2df/20240410222622-720ta3u/20240312144746-04icr8v.sy, lUpdated=2024-12-19 18:10:00, rID=969d3152ba96e209a97bff03225d597604be5c37, rPath=/20240904214053-6pvvsr9/20240522124541-dxyfpda/20240522124001-3kpqt9g/20240328200911-8jvdtka/20240328212231-326o2df/20240410222622-720ta3u/20240312144746-04icr8v.sy, rUpdated=2024-12-19 18:52:31]
I 2024/12/19 18:57:16 diff.go:49: upsert [lID=c785b20e4c666ad4b0e83e5c4bbca6add5f8f0b9, lPath=/20240225215122-vodfrm5/20240329233111-uw5m4ad.sy, lUpdated=2024-12-19 18:10:00, rID=c6a419ea6a78d17aac556163c5603a809a618925, rPath=/20240225215122-vodfrm5/20240329233111-uw5m4ad.sy, rUpdated=2024-12-19 18:52:31]
I 2024/12/19 18:57:16 diff.go:49: upsert [lID=f3911271ec7262dfd787f5cf370a5b89b1dfdef3, lPath=/storage/petal/kmind/config/user.kmindconf, lUpdated=2024-12-19 18:10:01, rID=c547e793871e7a0b27fb3ef47bd2dbf136a458d8, rPath=/storage/petal/kmind/config/user.kmindconf, rUpdated=2024-12-19 18:53:11]
I 2024/12/19 18:57:16 sync.go:264: cloud upsert [56b2b57d8184cfc413df9ee26ec165f0228bbf37, /storage/petal/kmind/config/license.kmindconf, 2024-12-19 18:10:01]
I 2024/12/19 18:57:16 sync.go:264: cloud upsert [0af996455a8bdd7e67ea18a90e93e8d3b9f5a2c1, /20240225215122-vodfrm5/20240315181307-vieunhw.sy, 2024-12-19 18:10:00]
I 2024/12/19 18:57:16 sync.go:264: cloud upsert [d18cd53b3a88dc3431fb93d401a7223737f383ee, /20240904214053-6pvvsr9/20240522124541-dxyfpda/20240522124001-3kpqt9g/20240328200911-8jvdtka/20240328212231-326o2df/20240410222622-720ta3u/20240312144746-04icr8v.sy, 2024-12-19 18:10:00]
I 2024/12/19 18:57:16 sync.go:264: cloud upsert [c785b20e4c666ad4b0e83e5c4bbca6add5f8f0b9, /20240225215122-vodfrm5/20240329233111-uw5m4ad.sy, 2024-12-19 18:10:00]
I 2024/12/19 18:57:16 sync.go:264: cloud upsert [f3911271ec7262dfd787f5cf370a5b89b1dfdef3, /storage/petal/kmind/config/user.kmindconf, 2024-12-19 18:10:01]
I 2024/12/19 18:57:16 sync.go:270: local upsert [c547e793871e7a0b27fb3ef47bd2dbf136a458d8, /storage/petal/kmind/config/user.kmindconf, 2024-12-19 18:53:11]
I 2024/12/19 18:57:16 sync.go:270: local upsert [93b266193b1bb216632f8ea69e9e62c8d086e4ec, /storage/petal/kmind/config/license.kmindconf, 2024-12-19 18:52:32]
I 2024/12/19 18:57:16 sync.go:270: local upsert [a2e275bcf21fbd79421963294d45cee49cf40759, /20240225215122-vodfrm5/20240315181307-vieunhw.sy, 2024-12-19 18:52:31]
I 2024/12/19 18:57:16 sync.go:270: local upsert [969d3152ba96e209a97bff03225d597604be5c37, /20240904214053-6pvvsr9/20240522124541-dxyfpda/20240522124001-3kpqt9g/20240328200911-8jvdtka/20240328212231-326o2df/20240410222622-720ta3u/20240312144746-04icr8v.sy, 2024-12-19 18:52:31]
I 2024/12/19 18:57:16 sync.go:270: local upsert [c6a419ea6a78d17aac556163c5603a809a618925, /20240225215122-vodfrm5/20240329233111-uw5m4ad.sy, 2024-12-19 18:52:31]
I 2024/12/19 18:57:17 sync.go:1168: uploaded index [device=E61A108C-A936-561D-87F7-FB6B171CB1A0/darwin, id=deb5724205941c1aa3277184760fba12e548eadb, files=12861, size=1.55 GB, created=2024-12-19 18:57:16]
I 2024/12/19 18:57:17 sync.go:901: uploaded cloud ref [refs/latest, id=deb5724205941c1aa3277184760fba12e548eadb]
I 2024/12/19 18:57:17 ref.go:64: updated local latest to [device=E61A108C-A936-561D-87F7-FB6B171CB1A0/darwin, id=deb5724205941c1aa3277184760fba12e548eadb, files=12861, size=1.55 GB, created=2024-12-19 18:57:16]
I 2024/12/19 18:57:17 sync.go:1378: updated latest sync [device=E61A108C-A936-561D-87F7-FB6B171CB1A0/darwin, id=deb5724205941c1aa3277184760fba12e548eadb, files=12861, size=1.55 GB, created=2024-12-19 18:57:16]
I 2024/12/19 18:57:17 repository.go:1501: synced data repo [device=E61A108C-A936-561D-87F7-FB6B171CB1A0, kernel=155hlur, provider=2, mode=a/false, ufc=8, dfc=2, ucc=0, dcc=0, ub=383.45 kB, db=650.38 kB] in [1.49s], merge result [conflicts=0, upserts=0, removes=0]

I 2024/12/19 18:57:17 index_fix.go:51: start checking index...
I 2024/12/19 18:57:22 index_fix.go:71: finish checking index
I 2024/12/19 18:57:22 store.go:61: purging data repo [/Users/dfcold/SiYuan/repo/], retention indexes [41]
I 2024/12/19 18:57:23 store.go:242: purged data repo [/Users/dfcold/SiYuan/repo/], [0] indexes, [0] objects, [0] bytes

这是我进行相关操作时前后时间的日志，我不确定是否有相关信息

**Comment by TCOTC** [comment]
给个网页试试

**Comment by davincilll** [comment]
> 给个网页试试

http://www.52im.net/thread-4081-1-1.html

使用简悦进行的导入，可能是因为这篇文章的排版导入后的结果比较怪

**Comment by TCOTC** [comment]
关掉这个再导入看看有没有改善：

![image](https://github.com/user-attachments/assets/44e53413-7545-413f-bb8a-5e2d006a806f)

**Comment by davincilll** [comment]
> 我这里用官方的剪藏拓展是正常的。你在设置里关掉这个选项再剪藏看看有没有改善：
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/397369282-44e53413-7545-413f-bb8a-5e2d006a806f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTE4NzQsIm5iZiI6MTczNDYxMTU3NCwicGF0aCI6Ii83ODQzNDgyNy8zOTczNjkyODItNDRlNTM0MTMtNzU0NS00MTNmLWJiOGEtNWUyZDAwNmE4MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyMzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmVhMTEwMzFkYWM1ZDNhMGJjMzhjOTZkNzY0MWFkM2NmOGFiNWE5MDlkZDlkZTdlOWYwNGE0NzZlZTk5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xcaYKNXLGu5IR6bf5vdSKPekl48sKVKvFYpkq2wLY0Q)

你这里解决了我剪藏时产生的未预期的标签的问题，既有的大部分标签是可以被删除的。但是仍然存在部分标签是无法被删除的问题。

这个标签点击时，无法搜索到任何结果
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/989cce2f-5857-400e-b14b-026cd864d75c" />

但是我进行删除（删除后仍然存在）时，会定位到这个笔记
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/9b1bb427-8681-40cc-b556-b33cc15fc74e" />


这个是我很久之前使用简阅剪藏的结果，目测是这些导致了那个嵌套特别深的标签
<img width="796" alt="image" src="https://github.com/user-attachments/assets/2040090c-465b-4353-8c2b-cfe5823eac4c" />
<img width="737" alt="image" src="https://github.com/user-attachments/assets/ed344fda-5de7-4dc9-b41f-ecbb726fa33f" />

这里是原地址[https://help.aliyun.com/zh/ecs/user-guide/cron-expressions](https://help.aliyun.com/zh/ecs/user-guide/cron-expressions)

这里我使用官方的剪藏时不会识别出标签。我这里想表达不是剪藏方面的问题。而是想说一下关于这个标签随之产生的一些异常行为，比如说为什么无法删除，为什么点击这个标签时搜索不到，但是删除时会找到对应的文件（我不太确定是数据库中出现了不一致性，还是说执行逻辑上出了些问题）

**Comment by ZSCN2024** [comment]
> > 我这里用官方的剪藏拓展是正常的。你在设置里关掉这个选项再剪藏看看有没有改善：
> > ![image](https://private-user-images.githubusercontent.com/78434827/397369282-44e53413-7545-413f-bb8a-5e2d006a806f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTE4NzQsIm5iZiI6MTczNDYxMTU3NCwicGF0aCI6Ii83ODQzNDgyNy8zOTczNjkyODItNDRlNTM0MTMtNzU0NS00MTNmLWJiOGEtNWUyZDAwNmE4MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDEyMzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmVhMTEwMzFkYWM1ZDNhMGJjMzhjOTZkNzY0MWFkM2NmOGFiNWE5MDlkZDlkZTdlOWYwNGE0NzZlZTk5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xcaYKNXLGu5IR6bf5vdSKPekl48sKVKvFYpkq2wLY0Q)
> 
> 你这里解决了我剪藏时产生的未预期的标签的问题，既有的大部分标签是可以被删除的。但是仍然存在部分标签是无法被删除的问题。
> 
> 这个标签点击时，无法搜索到任何结果 <img alt="image" width="1152" src="https://private-user-images.githubusercontent.com/123285105/397382970-989cce2f-5857-400e-b14b-026cd864d75c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzc3ODEsIm5iZiI6MTczNDY3NzQ4MSwicGF0aCI6Ii8xMjMyODUxMDUvMzk3MzgyOTcwLTk4OWNjZTJmLTU4NTctNDAwZS1iMTRiLTAyNmNkODY0ZDc1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwNjUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGE0MjFmNTYwMmU2M2VkOGQ2N2ZhNDg3ZDU1ZTU3YWVlOWZmOTkxYTY2YmVlZGNhNjNjN2U4OWVhM2M4MWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BYBSivqI8AwenTjjKCMU6_HOflchfgfn8XltlGi7WOE">
> 
> 但是我进行删除（删除后仍然存在）时，会定位到这个笔记 <img alt="image" width="1152" src="https://private-user-images.githubusercontent.com/123285105/397383281-9b1bb427-8681-40cc-b556-b33cc15fc74e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzc3ODEsIm5iZiI6MTczNDY3NzQ4MSwicGF0aCI6Ii8xMjMyODUxMDUvMzk3MzgzMjgxLTliMWJiNDI3LTg2ODEtNDBjYy1iNTU2LWIzM2NjMTVmYzc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwNjUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTU5ZDA5ZDc3OWI2MGQ2NjY2OTc2YTY3NzI1ZjY0ZjBlY2ExZWY1YzdmYzZmNzk3NzI1MWZhNTU4ODIyYWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.emC9ArJVsYEydOoPyHy9na3FN-oDrjQz3WM34C4MGGQ">
> 
> 这个是我很久之前使用简阅剪藏的结果，目测是这些导致了那个嵌套特别深的标签 <img alt="image" width="796" src="https://private-user-images.githubusercontent.com/123285105/397384032-2040090c-465b-4353-8c2b-cfe5823eac4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzc3ODEsIm5iZiI6MTczNDY3NzQ4MSwicGF0aCI6Ii8xMjMyODUxMDUvMzk3Mzg0MDMyLTIwNDAwOTBjLTQ2NWItNDM1My04YzJiLWNmZTU4MjNlYWM0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwNjUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjY3ZDQzZjRmYTcyMjlkOTc5YjdmODg2OWU1YjYyMGM5ZjNhN2YxMmE3N2I0YWZjYjg3MmZiMGJjM2ZlODBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ybrckP8mlk5efFX6zWhl6E4s40PUA5R_BIuHv-E9mo8"> <img alt="image" width="737" src="https://private-user-images.githubusercontent.com/123285105/397384097-ed344fda-5de7-4dc9-b41f-ecbb726fa33f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2Nzc3ODEsIm5iZiI6MTczNDY3NzQ4MSwicGF0aCI6Ii8xMjMyODUxMDUvMzk3Mzg0MDk3LWVkMzQ0ZmRhLTVkZTctNGRjOS1iNDFmLWVjYmI3MjZmYTMzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwNjUxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWViYTRhY2RjZGU1YzEyMGUwYzg0YWRlYmNhNzhlMTQxNDlkMmFkOTVmMmUxYmQ5YTUzZjExMDNlZWZjNjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S_JRdJol-83kLKqsvLiO75vClWKwGCNKGUAkPEbFFCc">
> 
> 这里是原地址https://help.aliyun.com/zh/ecs/user-guide/cron-expressions
> 
> 这里我使用官方的剪藏时不会识别出标签。我这里想表达不是剪藏方面的问题。而是想说一下关于这个标签随之产生的一些异常行为，比如说为什么无法删除，为什么点击这个标签时搜索不到，但是删除时会找到对应的文件（我不太确定是数据库中出现了不一致性，还是说执行逻辑上出了些问题）

标签无法删除这个问题很早就有了，开发者以前好像处理过一次，现在又出现了吗？

**Comment by 88250** [comment]
暂时先关闭了，欢迎随时补充信息，谢谢。

**Comment by Sandman126** [comment]
导入notion出现类似问题
解决办法：
导入后，备份到webdav上，再把本地工作空间文件都删掉，下载备份，标签恢复
