### ISSUE TITLE
建议访问授权码，增加仅应用于远程访问选项

### ISSUE THREAD

**Issue by wish5115** [siyuan-note/siyuan#13544]
### In what scenarios do you need this feature?

<img width="625" alt="image" src="https://github.com/user-attachments/assets/cd5ca417-60a0-43a9-ac9e-e125273ca39c" />

如图，我开启授权码的目的是为了远程访问时需要输入密码，但我本地的app每次打开时也需要输入密码，电脑端还好，手机端界面又小，每次输入很麻烦，建议增加仅应用于远程访问选项，这样，用户多一种选择的可能。

### Describe the optimal solution

访问授权码增加仅应用于远程访问选项

**Comment by wish5115** [comment]
我曾尝试用js自动输入，但停留在登录界面时，js片段并未加载，因此无用。

**Comment by 88250** [comment]
不考虑改变设计了，这个也有本地使用场景的。

**Comment by wish5115** [comment]
> 不考虑改变设计了，这个也有本地使用场景的。

是的，所以才说加选项嘛

**Comment by wish5115** [comment]
> 暂时不加了，后续需求多再考虑。

👌
