### ISSUE TITLE
宽度百分比建议增加手工输入途径

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#13558]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/fe9aed31-a5de-4e5b-bcaa-deb92077e0fd)
如图所示超级块包含了4个代码块，想设置成代码块所占比例分别为30%  30% 30% 10%时无法实现，现在都预置了几种固定的百分比

### Describe the optimal solution

宽度百分比增加手工输入

**Comment by TCOTC** [comment]
100% 下面那里可以拖拽调整
