### ISSUE TITLE
图片能默认居中么。

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1355]
图片默认居中 应该是大部分的使用场景吧 = =，新版本把这个去掉了，让用户自己设置位置，
这样在**新版本之前 写的所有笔记**，里面的图片 都得一个一个手动设置居中 = =。
建议改进：
* **写死了，图片默认居中（一般使用场景），特殊场景，再手动设置居左、居右**。
* **灵活点，在设置中，用户可以根据自己习惯，设置图片默认居中、居左、居右**，特殊场景，再手动设置。

**Comment by 88250** [comment]
你好，之前试过默认居中，很多用户反馈这不大合理……所以我们还是按照默认居左处理吧，配置项现阶段暂时不考虑，等如果需要的人多了再看看，感谢反馈。

**Comment by yeshaopeng6688** [comment]
= =。行吧，他们图片都很小，放中间确实不好看。

**Comment by yeshaopeng6688** [comment]
对了，既然表格有居中居左居右的快捷键，图片能否也有呢，这样也方便点是😁

**Comment by 88250** [comment]
@yeshaopeng6688 单独开个 issue 谢谢
