### ISSUE TITLE
Markdown 代码块解析问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13552]
导入这个文档：[代码注释规范.sy.zip](https://github.com/user-attachments/files/18198334/sy.zip)

按如下操作：

[video.webm](https://github.com/user-attachments/assets/46d493b2-39e1-4045-937c-8a499c44281e)

**Comment by 88250** [comment]
这里可以稍微调整一下，以确保从代码块中复制后和刷新再点复制得到同样的结果，比如复制最后这两个块：

![image](https://github.com/user-attachments/assets/6f239508-7c29-40e1-8aee-ad0bf99c51d1)

贴到代码块中再点复制：

![image](https://github.com/user-attachments/assets/3d811a28-130d-4718-a2a0-c667ba199773)

再粘贴后得到结果：

![image](https://github.com/user-attachments/assets/753f384a-0223-44aa-b746-e2703a39a988)

---

因为思源支持代码块中包含 ``` 标记符（实现方案是将 ` ``` ` 替换为 ` ZWJ``` `），而这个依然可以被解析为行级代码。

实践上应该尽量避免代码块中包含 ` ``` `，否则可能会有其他解析问题，这算是 Markdown 本身的问题吧。

**Comment by TCOTC** [comment]
因为我是从网页复制 Markdown 的，所以粘贴到思源里会有一个代码块做中转

https://gist.githubusercontent.com/skyjia/cf59c483e98580e288f96e1e4bdd4104/raw/e46b31e50fceec373fafefde4583b2fc21cd5832/comments_style.md

**Comment by 88250** [comment]
嗯，稍后改进了一下，得多测测看，谢谢。
