### ISSUE TITLE
改进数据库合并选项

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13554]
如果用户需要合并两个选项，我觉得应该直接删掉这个修改前的选项：

[video.webm](https://github.com/user-attachments/assets/d953b8a3-5a6b-407f-952a-e1b284dcd425)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/11484#issuecomment-2520291491_

**Comment by 88250** [comment]
删掉会有改变已有值的问题，目前应该是前端没有判断重复，界面上应该判断一下？ @Vanessa219

**Comment by Vanessa219** [comment]
不拉进 3.1.17
