### ISSUE TITLE
Browser Clipping Extension supports multiple languages

### ISSUE THREAD

**Issue by ruin1990** [siyuan-note/siyuan#13559]
chrome插件添加多国语言支持框架

### In what scenarios do you need this feature?

想着是不是可以对提示信息、设置及剪报界面做国际化处理，现在应该是全英文的

### Describe the optimal solution

我目前是想着一个国家语言一个json，对于静态网页，默认还是英语，然后在load完成后加载对应的json用js给替换掉文字
对于动态弹出的一些提示信息，动态获取对应字符串代替静态的字符串。
所有json文件丢在locales底下以[langCode].json命名
设置里追加一个当前语言的设置，遇到不支持的语言就直接换英语

### Describe the candidate solution

一样的做法，但是优先先把主界面静态内容给翻译了，一些popup的代码内字符串就延后处理

**Comment by 88250** [comment]
嗯，可以考虑使用浏览器语言来选择默认语言（比如从 User Agent 读取，或者从某个前端 API 获取默认语言）。

欢迎 PR。

**Comment by TCOTC** [comment]
https://developer.chrome.com/docs/extensions/reference/api/i18n?hl=zh-cn

**Comment by ruin1990** [comment]
> 嗯，可以考虑使用浏览器语言来选择默认语言（比如从 User Agent 读取，或者从某个前端 API 获取默认语言）。
> 
> 欢迎 PR。

嗯，那我这周改一个看看，确实是需要判断下浏览器的默认语言

**Comment by ruin1990** [comment]
> https://developer.chrome.com/docs/extensions/reference/api/i18n?hl=zh-cn

这个方法我研究了一下有个缺点，用户无法配置和浏览器语言不同的语言配置，准备整体结构参考这个，但是加载字符串的函数要重新封装一下

**Comment by 88250** [comment]
我这里暂时没有时间看细节……感觉应该可以不用 HTTP 请求吧，直接加载插件中的文件？

**Comment by ruin1990** [comment]
> 我这里暂时没有时间看细节……感觉应该可以不用 HTTP 请求吧，直接加载插件中的文件？
嗯，我再研究一下。
准备先做成这样：选择语言目前只能先把option.html给翻译了，tip弹出框里的内容暂时先跟着浏览器走的。

**Comment by 88250** [comment]
感谢贡献 https://github.com/siyuan-note/siyuan-chrome/pull/14
