### ISSUE TITLE
希望隐藏停靠栏后，左右两边能有悬浮边栏的识别区域

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#13553]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/11d2da5d-c42c-41d1-a0c7-330f198b48ea)
就如chrome的书签侧边栏插件(https://github.com/Kiuryy/Bookmark_Sidebar)
左侧能有个识别区域，在没有停靠栏的时候鼠标移过去能触发悬浮边栏，现在隐藏停靠栏后无法每次稳定触发悬浮边栏。
目前因为隐藏停靠栏后无法稳定触发悬浮边栏，基本从来都不敢隐藏停靠栏

### Describe the optimal solution

能有1-5px宽度的鼠标识别区域
另外，我觉得隐藏停靠栏后，如果鼠标滑过显示边栏，应该把停靠栏一起显示出来，这样需要切换的时候也可以切换功能页面

**Comment by TCOTC** [comment]
> 现在隐藏停靠栏后无法每次稳定触发悬浮边栏

窗口最大化的时候也这样吗？

**Comment by 5kyfkr** [comment]
> > 现在隐藏停靠栏后无法每次稳定触发悬浮边栏
> 
> 窗口最大化的时候也这样吗？

窗口最大化不会，但是我一般都是窗口化的时候用

**Comment by 5kyfkr** [comment]
另外，我觉得隐藏停靠栏后，如果显示边栏因该把停靠栏一起显示出来

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/9136
