### ISSUE TITLE
给自适应宽度添加设置快捷键并添加到命令面板中

### ISSUE THREAD

**Issue by SaXz2** [siyuan-note/siyuan#13567]
### In what scenarios do you need this feature?

很多时候我需要来回切换自适应宽度，但是目前很难快速切换，希望可以对这个功能添加一个快捷方式

### Describe the optimal solution

1.添加快捷键
2.添加到命令面板中 用一个按钮来完成启动或禁用的状态

**Comment by TCOTC** [comment]
让以下操作支持自定义快捷键：

- 全局自适应宽度切换
- 当前文档自适应宽度切换
	- 默认
	- 启用
	- 禁用

**Comment by SaXz2** [comment]
默认感觉不需要，建议跟其他软件一样，一个按钮切换启用和禁用就行了，方便一点

**Comment by TCOTC** [comment]
如果要添加到命令面板的话那肯定是一起加上

**Comment by SaXz2** [comment]
> 如果要添加到命令面板的话那肯定是一起加上

那这样按钮肯定不止一个了，切换的时候还得多打几个关键字 本来是一个的按钮就得分开做成3个了

**Comment by TCOTC** [comment]
按钮至少有 4 个

**Comment by SaXz2** [comment]
> 按钮至少有 4 个
这样设计就太多了，自适应宽度默认就是默认状态，我更偏向加一个按钮切换宽屏窄屏，去掉多余不常用的选项，如果都分开用命令行的时候就需要输入 自适应 → 再选择到 启用 ，多了选择的步骤，使用上不够流畅快捷了

**Comment by TCOTC** [comment]
现在就有4个

**Comment by Vanessa219** [comment]
是需要哪里的快捷键？
![image](https://github.com/user-attachments/assets/13851b33-6aff-45af-abf0-4290abcdc686)
![image](https://github.com/user-attachments/assets/3e840851-0b31-4ec1-98f1-49f4ac37cc69)

**Comment by SaXz2** [comment]
> 是需要哪里的快捷键？
单个文档的快捷切换第一张图里

**Comment by Vanessa219** [comment]
只需要启用和禁用么？

**Comment by SaXz2** [comment]
> 只需要启用和禁用么？

对，相当于一个可以快速切换单个文档宽窄的快捷方式
