### ISSUE TITLE
表格内容，部分单元格复制的时候会为_加上转义符

### ISSUE THREAD

**Issue by cosmos-wonder** [siyuan-note/siyuan#13560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复制圈出来的单元各时，粘贴板值为 search\_index\_user\_summary\_sync\_inc-global-live
<img width="1016" alt="image" src="https://github.com/user-attachments/assets/9b087965-d694-4485-8bbf-3f222fbde364" />

### Expected result

search_index_user_summary_sync_inc-global-live

### Version environment

```markdown
- Version: 3.1.16
- Operating System: MacBook Pro
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18209222/siyuan.log)

**Comment by TCOTC** [comment]
表格内容是哪来的？手动输入的还是从哪里复制粘贴的？

**Comment by cosmos-wonder** [comment]
> 表格内容是哪来的？手动输入的还是从哪里复制粘贴的？

复制粘帖的

**Comment by TCOTC** [comment]
网页吗？发网址看看

**Comment by cosmos-wonder** [comment]
公司内网，外网访问不了

**Comment by TCOTC** [comment]
@88250 复制下面这个表格到思源里，再从思源复制粘贴，确实会有转义符

|search_index_user_summary_sync_inc-global-live||
|---|---|
|123|123|

![image](https://github.com/user-attachments/assets/d7e853d3-ed0f-4bfb-8a83-bb5f5b5e44b2)

**Comment by 88250** [comment]
下划线是 Markdown 标记符，所以会自动加上 `\` 转义符。

**Comment by TCOTC** [comment]
但是只复制单元格文本而不是整个表格的话是正常的，表格有办法处理吗？

![image](https://github.com/user-attachments/assets/9c789817-cb23-4e62-a0b2-e339296f1a11)

**Comment by 88250** [comment]
看了下没有办法处理啦，不然 https://github.com/siyuan-note/siyuan/issues/12725 这个会炸。

**Comment by TCOTC** [comment]
@cosmos-wonder 选中文本之后右键点击，复制为纯文本
