### ISSUE TITLE
预览模式：复制到语雀，图片没有用图床前缀

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复制到语雀，图片没有用图床前缀

导致上传图片到图床，依然无法把图片粘贴到外部软件

### Expected result

复制到语雀，图片使用图床前缀

### Screenshot or screen recording presentation

![PixPin_2024-12-21_17-45-32](https://github.com/user-attachments/assets/92235c7a-a4ba-4b13-973a-a9a15c3d3a5a)

### Version environment

```markdown
- Version: 3.1.17 dev1
- Operating System: Win 11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
和这个冲突了…… https://github.com/siyuan-note/siyuan/issues/13283#issuecomment-2510537284

**Comment by Achuan-2** [comment]
是说之前锚点错误添加图床地址吗，所以统一不添加图床地址吗？
锚点是#开头的，
能否给assets开头的图片地址添加图床地址
而不给锚点链接添加图床地址呢？
否则以后就不能直接复制带图床的md了

**Comment by 88250** [comment]
可以的，稍后改进。
