### ISSUE TITLE
Query language for database filters

### ISSUE THREAD

**Issue by Xe1Dery** [siyuan-note/siyuan#13570]
### In what scenarios do you need this feature?

I just recently started using Siyuan and can only use machine translation for Chinese. Sorry if this is a duplicate or if I don't fully understand all the functions and plugins.

When using the database filter, I got an unexpected result.

Example database:
![image](https://github.com/user-attachments/assets/b8709474-c5fb-4fdb-a3ea-9bcd1fca0cbe)

When using the filter on Multi Select I get entries matching `A OR B`:
![image](https://github.com/user-attachments/assets/f1bab7f0-92ed-4dc1-b493-f1ffe113f6b1)

I expected to get occurrences corresponding to `A AND B` like this:
![image](https://github.com/user-attachments/assets/39683ece-eb13-42f3-9aef-d647719e77bb)

### Describe the optimal solution

I'm still not completely sure of my knowledge, maybe the desired feature is implemented differently or there is already a plugin for it, but my search led me here.

As a solution I see adding a query language in the filters tab, which will allow to create filters like `A AND (B OR C) AND !D`  

### Describe the candidate solution

-

### Other information

-

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/10550

**Comment by Xe1Dery** [comment]
Thank you!

> #10550
