### ISSUE TITLE
添加命令直接切换隐藏左栏/右栏/底栏，现在的不好切换

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#13578]
### In what scenarios do you need this feature?

如图所示：

![image](https://github.com/user-attachments/assets/ec3519a0-34f5-462d-b957-e7011c136f69)

我我需要隐藏左栏。但是因为左栏分上下不分，
搞得每次都隐藏了文档树，结果下面的大纲直接占满了，我只好在次点击一下 大纲让他隐藏。

这种操作非常反直觉，尤其是笔记本电脑或者平板等屏幕不宽的设备。为了增加显示面积不得不时常的隐藏

底部，右边，同理

### Describe the optimal solution

![image](https://github.com/user-attachments/assets/ec3519a0-34f5-462d-b957-e7011c136f69)

- 方案1， 在左边中间的空白处，双击直接隐藏文档数和大纲，
- 方案2， 类似 VSCODE ，添加界面管理的快捷功能

![image](https://github.com/user-attachments/assets/4ce9e4ff-86cd-4196-9452-d85d3b66bb9e)

### Describe the candidate solution

无论何种方式， 都应该添加一个命令，用户可以直接用快捷键 切换显示。

**Comment by 88250** [comment]
这个不考虑改了，面板设计如此，感谢反馈。
