### ISSUE TITLE
Use `position: absolute` to set element position instead of `position: fixed`.

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#13573]
### In what scenarios do you need this feature?

在 transform 元素内部，渲染 protyle 时，由于 gutter、hint、toolbar 等元素使用的是 `position: fixed`，导致这些元素的定位出现偏差。

### Describe the optimal solution

使用 `position: absolute` 代替 `fixed`。

在计算时，使用目标元素（比如段落块）的 `top` 和 `left`，减去 `.protyle` 对应的 `top` 和 `left` 是可以正确定位目标的。

当然，由于对思源整理代码不熟悉，我不确定该方案是不是会有潜在影响。

### Other information

https://github.com/user-attachments/assets/0bd9a101-9436-4e45-9d0b-33fad571a5e0

该视频是我在实现白板功能时插入的自定义元素。

通过在 `protyle-content` 下插入了一个同样大小的元素 `enProtyleActualArea`，在其内部使用 `absolute` 对下图中的元素 `enProtyleActualAreaContainer` 进行定位。

`enProtyleActualArea` 区域，用于定位。等同于 `protyle` 或 `protyle-content`
<img width="1459" alt="image" src="https://github.com/user-attachments/assets/1003c7f6-de10-4f2e-aab8-e55484ea6333" />

`enProtyleActualAreaContainer` 元素，实际需要定位的元素。等同于 `gutters`、`hint` 等。
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/11b68e0d-eb49-4c71-a862-ba3290fd40ac" />

滚动 `protyle`、调整 `protyle` 区域的宽度，都是能良好地匹配上。

计算的逻辑如下：

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/713a1afb-d3b9-4844-a4f2-5637d473974b" />

@Vanessa219 V姐你看看能调整成使用 `absolute` 的方式吗？

**Comment by Vanessa219** [comment]
是有什么偏差？用 absolute 后这些元素就无法浮到编辑器外部了

**Comment by Wetoria** [comment]
> 是有什么偏差？

简单来说就是gutter等都不在预期的位置上。实际操作的时候，gutter、hint都是看不到了。

比如截图里 hint 向右偏移了很大一截。

<img width="1420" alt="image" src="https://github.com/user-attachments/assets/3cce75c0-684e-492f-b133-3620313e5336" />

> 用 absolute 后这些元素就无法浮到编辑器外部了

这个问题我后来想到了。所以好像也不能简单的改成 `absolute`。

本来想提一个备选方案的：

在 gutter/hint/toolbar 上记录一下上一次绑定的目标元素？这样在插件里也能根据目标元素重新调整这些 `fixed` 的元素。

但是就不给你们增加工作量了。

我目前用了另外的方式解决了这个问题，先观察一段时间好了。

**Comment by Vanessa219** [comment]
编辑器编辑部分可以使用 protyle.wysiwyg
