### ISSUE TITLE
支持快速选中容器块

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13580]
### In what scenarios do you need this feature?

**遇到的问题**
现在选中容器块很麻烦，我一般是shift+方向键 通过扩选的方式来选中容器块。
但部分容器块是叠在一起的（例如列表项和列表），扩选时得识别和记忆当前的扩选层级，很是费劲。

### Describe the optimal solution

**可以考虑修改一下块标的左键逻辑**
目前左键和右键都是打开块菜单并选中块，我觉得可以给左键逻辑变更为**只选中块，而不打开菜单**。
这样就可以快速且准确的选中指定容器块了。
> **这种操作习惯和windows一致，左键单击是选中，右键是打开菜单**

**Comment by TCOTC** [comment]
> 目前左键和右键都是打开块菜单并选中块

已经能满足你的需求了

**Comment by cordinGH** [comment]
不行的，块菜单被打开会影响快捷键
![PixPin_2024-12-23_00-54-29](https://github.com/user-attachments/assets/c5494e7b-35d0-4bc6-ab5e-1633f6b1d274)

**Comment by TCOTC** [comment]
你用左键点试试

@Vanessa219 右键点击块标之后无法使用快捷键

**Comment by cordinGH** [comment]
左键好像没问题。那就是右键打开会影响快捷键。
受操作系统的使用习惯，一直在右键打开菜单 😭

**Comment by cordinGH** [comment]
修改了一下正文。
可以考虑左键单击块标是仅选中，右键为打开菜单。
这样的话 在使用习惯上就和操作系统一致了，操作系统也是左键选中，右键打开菜单。

**Comment by TCOTC** [comment]
左键点击按钮打开菜单是惯用做法，用右键的反而是少数

**Comment by cordinGH** [comment]
这样吗？我还以为多数人都是继承了操作系统右键菜单的习惯

**Comment by 88250** [comment]
这个就保持不变了，谢谢。

**Comment by TCOTC** [comment]
> 右键点击块标之后无法使用快捷键

@88250 还有这个问题
