### ISSUE TITLE
显示id

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#13587]
能否在图中位置显示id，大部分时候我只是想看一眼，是否是这个块。现在只能复制，粘贴后看。

![image](https://github.com/user-attachments/assets/354b1fc2-9d1c-4326-b7de-1a5890e45a05)

![image](https://github.com/user-attachments/assets/9f00e88f-e7c2-4399-84ae-49d3a8990588)

**Comment by Vanessa219** [comment]
ID 有点长，你看这样行不？

![image](https://github.com/user-attachments/assets/04a6cd85-52a3-4738-b157-f2a151cc7b72)

**Comment by KuiyueRO** [comment]
> ID 有点长，你看这样行不？

和创建时间、更新时间放在一起是不是更合适

**Comment by Vanessa219** [comment]
太长了好像不是太好看，而且前半部分会和更新日期重复。

![image](https://github.com/user-attachments/assets/e85724db-50f4-444a-b00f-7cef2f91cefc)

**Comment by 88250** [comment]
ID 这个大部分时候属于程序使用，还是不放在界面上好一些，所以不考虑改变了，感谢反馈。
