### ISSUE TITLE
列表内调整缩进时始终显示面包屑

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13594]
便于查看层级

https://ld246.com/article/1734315530572/comment/1734397105428#comments

**Comment by 88250** [comment]
不考虑改变设计了，面包屑无法动态计算（动态计算的话性能消耗代价太大）。

**Comment by leeyaunlong** [comment]
> 不考虑改变设计了，面包屑无法动态计算（动态计算的话性能消耗代价太大）。

如何自己通过脚本触发更新? 快捷键触发也可以.

**Comment by 88250** [comment]
代码实现入口应该是：

![image](https://github.com/user-attachments/assets/4c9ce8dd-d500-4a68-8138-91daf3fea55e)

![image](https://github.com/user-attachments/assets/8bd7b919-edd5-435b-a07c-aab4ebf11bd7)

只要鼠标移动就会重新渲染面包屑。
