### ISSUE TITLE
段首插入 ￥￥ 不能转换公式块

### ISSUE THREAD

**Issue by ShawElA** [siyuan-note/siyuan#13590]
段首插入 `$$` 会将这一段转换成公式块，而插入 `￥￥` 无任何效果。

**Comment by 88250** [comment]
我这里测试正常

**Comment by ShawElA** [comment]
> 我这里测试正常

噢不好意思，我没描述清楚。我是指**这一段已经有内容**的前提下，段首插入 `$$` 会将这一段整个转换成公式块，而插入 `￥￥` 无任何效果。

**Comment by 88250** [comment]
收到，后面看看能否改进 @Vanessa219

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/pull/13596
