### ISSUE TITLE
块类型切换逻辑不一致

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

**对 段落块 使用右键菜单（或快捷键）转换为容器块时：**
它的转换逻辑是：创建目标容器块来包裹住原先的段落块。
这种逻辑是合理的，保证了块id的稳定性，因为段落块id没有变化，所以来回切换类型不会丢失块引。

https://github.com/user-attachments/assets/5c7691ee-3975-4e25-9a47-3051b8fd2a0a

**但是如果使用markdown语法来得到容器块，则会出问题：**
语法会直接改变元素类型，然后内部生成一个新段落块来继承原段落内容。这就导致无法切回原类型，无论是菜单切换，还是删除开头语法，都会丢失块引。

https://github.com/user-attachments/assets/eb26444b-3591-465d-a721-7e196461d08c

![image](https://github.com/user-attachments/assets/9ee94f4a-d61a-4b15-b650-08cc929834f2)

### Expected result

markdown语法的效果，应该与右键菜单一致，而不是直接改变元素类型。以防止用户因此产生一些困惑或者是丢失块引。

### Version environment

```markdown
- Version: 3.1.15(微软商店版）
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
使用转移引用功能

**Comment by cordinGH** [comment]
> 使用转移引用功能

容器块这里面无法生效。我对视频2 转移步骤：
- 复制段落块id
- 单击列表块块标打开转移引用，粘贴段落块id
- 无变化。

**Comment by cordinGH** [comment]
最重要的是，真的有必要保留这两种不同的逻辑吗？

右键菜单的逻辑应该才是合理的，保障了段落id的稳定。

markdown语法转换出来的列表，直接导致类型转换变得不可逆了（id会变），`转移引用功能`也转不回段落上。

**Comment by TCOTC** [comment]
我这里转移引用正常：

[video.webm](https://github.com/user-attachments/assets/cc84caa9-c15e-49c3-81cd-d8af19754536)

**Comment by cordinGH** [comment]
嵌入引用不会替换。

https://github.com/user-attachments/assets/1804c258-5061-4c3d-9695-c962d017f37a

**Comment by cordinGH** [comment]
又测了一下，和容器块无关，纯段落也是一样的，只要是嵌入块都无法转移。

**Comment by 88250** [comment]
转移引用仅作用于引用元素上，不支持嵌入块的。

**Comment by cordinGH** [comment]
#4071 早期也有人提过引用丢失的问题。我觉得和菜单转换对齐后，也能一定程度上减少这种情况

**Comment by 88250** [comment]
不好搞，现在这部分逻辑暂时动不了

**Comment by cordinGH** [comment]
好吧，那没办法了。
不过我自身倒是不受影响，因为我能接受不使用markdown语法。
主要是想着降低其他用户（尤其新用户）遇到引用丢失的概率，特别是那些习惯性使用markdown语法的人。

**Comment by 88250** [comment]
几乎实现不了的，因为输入 Markdown 标记符和一次性执行某种转换是不一样的，这两种逻辑的实现细节上无法保证一致性。

较为安全的做法就是能用菜单尽量用菜单，或者避开已知的某种输入下 ID 会改变的情况。

**Comment by cordinGH** [comment]
了解了，以后我多注意注意。

**Comment by TCOTC** [comment]
所以就当特性来用吧，需要把 ID 移动到容器块的时候就输入 Markdown 标记符

**Comment by cordinGH** [comment]
也对，确实能当一个特性
