### ISSUE TITLE
文档树排序异常

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13598]
https://ld246.com/article/1735015037279

我这里测试只有名称的升降序是正常的，其他都有问题

备注：是笔记本的排序不是文档的排序

**Comment by 88250** [comment]
笔记本按创建时间排序有点问题；其他几个排序模式笔记本不支持。

**Comment by TCOTC** [comment]
> 其他几个排序模式笔记本不支持

那就支持一下？

**Comment by 88250** [comment]
暂时不考虑了
