### ISSUE TITLE
改进禁用自适应宽度时的编辑器宽度调整

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13595]
目前的机制是动态调整元素的 padding 或 margin，用起来一弹一弹的感觉像果冻。我感觉可以改成动态调整元素的 width ，一般情况下不需要调整，只有宽度不够的时候才缩小 width 。

[video.webm](https://github.com/user-attachments/assets/cae7b966-5e9e-4e39-978a-879e088d3041)

关联 https://ld246.com/article/1734184672100

---

如果实在实现不了的话，需要补上这个：

![image](https://github.com/user-attachments/assets/d6af48da-064a-47ab-97e2-dbe94243fdb4)

**Comment by Vanessa219** [comment]
宽度都会变化，还是无法避免这个问题。
