### ISSUE TITLE
求助：/api/transactions更新块

### ISSUE THREAD

**Issue by emptylight370** [siyuan-note/siyuan#13593]
### In what scenarios do you need this feature?

现状：在插件环境里面调用了`/api/transactions`来更新块内容。
调用代码如下：
https://github.com/emptylight370/sy-format-helper/blob/b8c1bf66c54703f0e0907fa632296c2c885d2970/src/api.ts#L28-L49
此处的`nodeId`为修改块的id，`appId`为插件获取的appid，`updated`和`original`分别是更新后和更新前的dom结构。
这里用`doOperations`和`undoOperations`封装了修改前后的dom，并且我记得早几天测试的时候是应该是可以通过`CTRL+Z`撤回的（我印象里观察到了撤回操作生效，就认为是可以写入撤回栈的，可能记忆出错了）。现在通过插件的`fetchSyncPost`调用之后可以返回完整的`doOperations`和`undoOperations`，并且`timestamp`也是调用时的时间戳。在调用完成之后也可以正常更新前端显示。
不过现在面临的问题是无法通过`CTRL+Z`撤回这个修改，检查发现被修改的块里面的`protyle`的`transactionTime`没有被更改，`undo`的`undoStack`为空，判断为前面的`undoOpreations`未写入撤回栈。
请问`/api/transactions`这一方法能不能通过`undoOperations`撤回操作？或者说这一方法能不能撤回操作？如果不能，可以通过什么方法向撤回栈中写入撤回操作？

### Describe the optimal solution

none

### Other information

本地测试在`/api/transactions`结束之后使用`/api/sqlite/flushTransaction`刷新事务无效。

**Comment by Vanessa219** [comment]
api 只是后台操作，需要前端的撤销可根据需求调用 Protyle 中以下方法
![image](https://github.com/user-attachments/assets/678bf793-1e48-4934-a549-a9bf264a7058)

**Comment by emptylight370** [comment]
感谢V大解答

**Comment by emptylight370** [comment]
抱歉V大，再次打扰一下，具体使用Protyle方法更新块的使用需要注意哪些方面呢？

我测试下来如果只用Protyle方法可以替换块的内容，但是只有部分时候可以通过撤回来取消上一步内容，
插件中调用的是`Protyle.prototype.updateTransaction`方法，没理解错的话这一步应该是`transactions("update")`，但是`undoStack`为空，`redoStack`写入的内容是修改后内容的"delete"和"update"，也就是在修改后dom的后面插入一个新块并且删除新块，
使用撤回操作不能撤回这次更新，但是使用重做操作可以重做新建块并删除块操作。

如果调用后端api`/api/transactions`并且将返回值的`doOperations`和`undoOperations`传入`Protyle.prototype.transactions`方法，就会变为[object Object]并且在后面插入一个新的块，刷新后可见内容无误，但是原本块的位置写入一个空块，替换后的内容写入新块。显然不应该这样用。

如果直接使用`Protyle.prototype.transaction`方法，自己构建do和undo并传入`{action:"update",id,data}`也会面临与`updateTransaction`差不多的情况。

希望V大能指出使用方法中的错误，或者指路一下前端代码中用户输入更新块的代码。

**Comment by emptylight370** [comment]
抱歉打扰，应该是不需要指导了。我研究官方示例找到了操作块的代码，现在可以写入撤回栈了。谢谢V大之前的回复。
