### ISSUE TITLE
数据库 主键列，建议增加重复计数

### ISSUE THREAD

**Issue by Mctalos** [siyuan-note/siyuan#13592]
### In what scenarios do you need this feature?

数据库 主键列，建议增加重复计数
自己数据库行数比较多，希望增加一个主键重复数量计数。用于辅助判断是否重复输入了。
目前有非重复项统计，希望在增加一个重复项统计。

<img width="673" alt="20241223_14-23-03" src="https://github.com/user-attachments/assets/f7ffb9c7-9363-4966-8ac3-20b171a7db15" />

### Describe the optimal solution

暂无

**Comment by TCOTC** [comment]
用 唯一值占比 来判断吧

**Comment by Mctalos** [comment]
> 用 唯一值占比 来判断吧
> 
> Duplicate of #11911

好的，谢谢，用唯一性占比统计也可以。
看了您关联的那个问题，觉得好奇怪呀，我不懂编程，不太理解为啥统计唯一性占比、唯一性数量都可以实现，统计重复数值不能实现。( ﹁ ﹁ )
