### ISSUE TITLE
图片宽度问题

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13609]
四张 25% 宽度的图片放在一起还是会挤下去一个：

![image](https://github.com/user-attachments/assets/33bcfb2c-8d3f-40cc-95b2-7d68ab604d49)

_Originally posted by @TCOTC in https://github.com/siyuan-note/siyuan/issues/12516#issuecomment-2511504608_

**Comment by pisceswb** [comment]
3张33%的都会挤下去一个，已设置默认为32%。是边框占据位置了？如果不是bug的话，这样也可以，自己修改一个稍小点的值。别因为修复这个再引起其它bug。

**Comment by Vanessa219** [comment]
图片之间是有边距的，100% + 边距 就会导致换行。

**Comment by TCOTC** [comment]
但是这个宽度不对啊，比 3.1.6 的 25% 宽一些，有没有办法能改进一下？

![image](https://github.com/user-attachments/assets/29912d1a-58bb-4e1d-8880-92a8656e5424)

**Comment by Vanessa219** [comment]
也有道理，那还是把边距算进去
