### ISSUE TITLE
导出mermaid，不显示文字

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#13601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

导出memaid，不显示文字

```
graph TD
    A[选择最佳旅游目的地]
    A --> B1[旅游成本]
    A --> B2[旅游景点吸引力]
    A --> B3[住宿条件]
    A --> B4[餐饮质量]
  
    B1 --> C1[城市甲]
    B1 --> C2[城市乙]
    B1 --> C3[城市丙]
  
    B2 --> C1[城市甲]
    B2 --> C2[城市乙]
    B2 --> C3[城市丙]
  
    B3 --> C1[城市甲]
    B3 --> C2[城市乙]
    B3 --> C3[城市丙]
  
    B4 --> C1[城市甲]
    B4 --> C2[城市乙]
    B4 --> C3[城市丙]
```
![PixPin_2024-12-24_16-39-50](https://github.com/user-attachments/assets/addf78c0-d207-48be-b0b7-63c9b996468d)

![PixPin_2024-12-24_16-39-42](https://github.com/user-attachments/assets/a79fd71d-c636-43f3-973f-8984d75b70eb)

### Expected result

导出memaid，正常显示文字

### Version environment

```markdown
- Version: v3.1.17 dev2
- Operating System: Win11
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
我这里导出预览和导出 PDF 都能正常显示：

![image](https://github.com/user-attachments/assets/c13571fc-c332-4f03-b06b-143ed9397b19)

**Comment by 88250** [comment]
我这里导出 PDF 也正常：

![image](https://github.com/user-attachments/assets/076ac976-c65b-40d6-a1b2-2c4ef255b676)

楼主排除一下是不是插件、代码片段等影响了，我先关闭 issue。

**Comment by Achuan-2** [comment]
因为字体设置的是sans-serif 
Acrobat没安装字体包，就不显示中文，用edge打开是正常的
