### ISSUE TITLE
Improve checking for updates on exit

### ISSUE THREAD

**Issue by flowprog** [siyuan-note/siyuan#13608]
从托盘退出时如果有新安装包请弹出来而不是卡死在里面也不退出

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，托盘退出时，如果有更新，会卡住，那系统强制关机的时候甚至是否容易造成出错

### Expected result

提示更新或直接退出

### Version environment

```markdown
- Version: 
- Operating System: win11
- Browser (if used):
```

### Log file

no

**Comment by TCOTC** [comment]
关联 https://ld246.com/article/1735026550764

**Comment by ZSCN2024** [comment]
目前思源的稳定性不太好，小问题也比较多。感觉摊子铺的太大，开发资源跟不上。
用户只能先自适应。比如自动升级的问题，我把自动升级关闭了，每次手动下载安装包升级，这样就不会遇到你说的问题了。

**Comment by 88250** [comment]
两个改进：

1. 有更新可用并且窗口最小化或者隐藏到托盘时弹出主窗口
2. 退出时不通过网络检查更新，避免网络卡顿

**Comment by TCOTC** [comment]
> 有更新可用并且窗口最小化或者隐藏到托盘时弹出主窗口

感觉不太好，能不能实现重新聚焦窗口的时候才弹出提示？

**Comment by 88250** [comment]
目的就是要这种情况下弹出哦，否则就会有楼主提到的问题。

**Comment by TCOTC** [comment]
我觉得应该在重新聚焦窗口的时候才弹出提示，用户没打开窗口看到提示都话退出就不更新。

窗口突然打开我觉得不好，用户会反感

**Comment by 88250** [comment]
只有有更新的时候才弹出，这样也能让用户选择是否更新，直接退出的话就看不到更新提示了。

**Comment by TCOTC** [comment]
下次打开窗口再提示就够了

**Comment by 88250** [comment]
我觉得目前这样挺好，等看看后面反馈再考虑要不要调整吧
