### ISSUE TITLE
支持导出 .sy.zip 和 .md 时不带引用的文档（块引转换为超链接）

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13602]
网状结构的卡片笔记，只想导出一篇文档的时候，会连带导出一大堆文档

**Comment by 88250** [comment]
.sy.zip 和 .md 主要是为了数据完整性，所以不考虑其他模式了，.md 的话应该可以用预览模式复制。

**Comment by TCOTC** [comment]
不冲突嘛，导出加个选项

**Comment by 88250** [comment]
这个不适合加，如果是 .md 的话可以考虑用导出预览模式
