### ISSUE TITLE
编辑器中错误拼写的提示修正

### ISSUE THREAD

**Issue by yangyi0318** [siyuan-note/siyuan#13603]
### In what scenarios do you need this feature?

编辑器中开启拼写检查后，目前可以检查出错误的拼写，但无法提示可供修改的选项。
<img width="532" alt="spelling1" src="https://github.com/user-attachments/assets/353b7774-b473-4c96-8c86-c66f49f1dc25" />

### Describe the optimal solution

类似于Word或者浏览器中的功能，若检查出拼写错误的单词，右键点击，可出现可供修改的单词列表。

**Comment by 88250** [comment]
抱歉，这个支持不了。
