### ISSUE TITLE
Use ID when block ref anchor text is empty

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13606]
引用块内容为空时，块引用锚文本应该是块 ID

文档：[1111111111.sy.zip](https://github.com/user-attachments/files/18240666/1111111111.sy.zip)

打开文档，复制标题，粘贴到第一个块，撤销

[video.webm](https://github.com/user-attachments/assets/9c2bab15-fd12-4876-bd4b-40e7661a8883)

**Comment by 88250** [comment]
![image](https://github.com/user-attachments/assets/6715aea9-76cc-4903-834e-d14673a4fc0e)

因为下面有个引用元素（这个引用元素不知道什么原因锚文本是空的所以看不到），引用了第一个段落，所以这个段落一改动就会导致引用锚文本变动。

**Comment by TCOTC** [comment]
就是说这个锚文本有问题，引用块内容为空的情况应该显示 ID

**Comment by TCOTC** [comment]
我还以为只有那个块有问题来着，原来都有问题：

[video.webm](https://github.com/user-attachments/assets/8b070f28-e19f-49ad-b20c-8614ff54baf2)

**Comment by 88250** [comment]
暂时不改动锚文本空的情况了

**Comment by TCOTC** [comment]
但是之前是显示 ID 的

**Comment by 88250** [comment]
哦，确实是，稍后改改，谢谢。
