### ISSUE TITLE
070内核磁盘和cpu占用异常

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1360]
[###](url) 描述问题 Describe the problem
如下图，根据尝试，应该是输入tag或者尝试显示引用浮窗的时候会触发较高大的cpu和磁盘占用。
同时能感觉到明显的浮窗弹出延迟（两三秒）以及tag候选词弹出延迟（估计超过5秒）

![image](https://user-images.githubusercontent.com/657850/106350329-ba86fc80-630f-11eb-9361-41cea6f346c9.png)

系统是win10专业版，磁盘是固态硬盘。
i日志如下：

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5897543/siyuan.log)

**Comment by 88250** [comment]
你好，如果方便的话请打包发我一下完整的笔记本数据 845765@qq.com

**Comment by 88250** [comment]
已在邮件沟通，后续看，先关闭了，谢谢。
