### ISSUE TITLE
Reduce exit time when sync is enabled

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13604]
继续完善 https://github.com/siyuan-note/siyuan/issues/13589

**Comment by 5kyfkr** [comment]
支持下，现在我觉得手机客户端速度提升很多了，我又从docker端改回用手机客户端了，唯一比不上docker端的就是退出老是要去菜单里按退出，退出按钮感觉搞个悬浮按钮之类的没准也不错

**Comment by 88250** [comment]
直接放在主界面上容易误触
