### ISSUE TITLE
切换聚焦层级的交互建议

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#13610]
### In what scenarios do you need this feature?

通过alt + 方向键切换聚焦层级时，由于会显示或隐藏其他段落，会导致光标所在段落频繁位移，这种感觉就像是使用md编辑器时在编辑模式和阅读模式切换，定位比较困难。

### Describe the optimal solution

有两种建议：

1. 保持光标所在段落在垂直方向上的位置不变，并高亮一次新显示的块
2. 高亮一次新显示的块，同时为左右、上下依次添加缓动动画

**Comment by 88250** [comment]
麻烦录屏看下

**Comment by 88250** [comment]
暂时先关闭了，欢迎随时补充信息，谢谢！
It is closed for the time being, please feel free to add more information, thank you!

**Comment by TCOTC** [comment]
这个说的应该是聚焦没有合适的动画，看起来是直接硬切的
