### ISSUE TITLE
动态查询Emoji表情语法似乎失效

### ISSUE THREAD

**Issue by ihyw** [siyuan-note/siyuan#1361]
### 描述问题 Describe the problem
动态查询Emoji表情时，语法好像失效了

### 期待的结果 Expected result
不知道Emoji表情是否支持类似的搜索

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/74618439/106351223-ec9b5d00-6315-11eb-95f9-b8971336a564.png)

### 版本环境 Version environment

* 版本 Version：v0.7.0
* 操作系统 Operating system：Windows10

**Comment by 88250** [comment]
你好，试了下好像没问题。

![issue](https://user-images.githubusercontent.com/873584/106377841-d1deec00-63da-11eb-8c3e-d814d32abcf3.gif)

我先关闭了，如果有进一步细节反馈请随时跟帖，谢谢。
