### ISSUE TITLE
移动端支持`分享进思源`

### ISSUE THREAD

**Issue by cordinGH** [siyuan-note/siyuan#13620]
### In what scenarios do you need this feature?

有时候拍了些照片，或者是截屏截图，想要快速插进日记做图片笔记，但是移动端目前并不支持这个功能，期待可以实现。

### Describe the optimal solution

其他笔记软件的效果参考（启动快是因为事先就把软件打开放在了后台）

https://github.com/user-attachments/assets/883152b3-7893-4820-902f-d903c651ab86

https://github.com/user-attachments/assets/3265295e-33f3-4f74-ada2-1e712bff27e4

**Comment by TCOTC** [comment]
Duplicate of #12426

**Comment by 88250** [comment]
后续请关注 https://github.com/siyuan-note/siyuan/issues/14414
