### ISSUE TITLE
增加用户注册及多用户管理功能

### ISSUE THREAD

**Issue by tt545571022** [siyuan-note/siyuan#13634]
### In what scenarios do you need this feature?

当小组内共同使用思源笔记时，有时需要管理各自的文档权限，此时需要多用户注册及用户管理。

### Describe the optimal solution

null

### Describe the candidate solution

null

### Other information

null

**Comment by 88250** [comment]
思源笔记主要面向个人使用，不面向协同，所以短期内不会考虑引入协同相关特性，感谢提议。

**Comment by TCOTC** [comment]
相关

- https://github.com/siyuan-note/siyuan/issues/11382
- https://github.com/siyuan-note/siyuan/issues/3838
- https://github.com/siyuan-note/siyuan/issues/6568
