### ISSUE TITLE
拓展模板功能

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13632]
支持导出(包含资源文件或数据库的)模板为这样的结构(模板解析也需要支持)，这种情况算单个模板，不算是在文件夹中：

![image](https://github.com/user-attachments/assets/b7391242-907a-4ae1-99c4-11ff0fc9281d)

便于分享模板、使用模板

![image](https://github.com/user-attachments/assets/768fa6ca-031e-4cf9-8b76-39267bdb8042)

![image](https://github.com/user-attachments/assets/49b8a2c1-0bd0-4c3e-9861-f42fb92c323d)

![image](https://github.com/user-attachments/assets/bc6c16fb-2e98-42d2-9bc2-d05fd6af16a8)

**Comment by 88250** [comment]
不考虑了，模板仅支持排版，带数据的话用导出 .sy.zip
