### ISSUE TITLE
能否使用 Gitee AI 模型 API ？

### ISSUE THREAD

**Issue by pittosporum1** [siyuan-note/siyuan#13630]
### In what scenarios do you need this feature?

这里是 Gitee AI 平台，隶属于开源中国项目，是国内最大的开源社区。我们目前正在积极拓展合作伙伴。据我们了解，思源笔记 可以集成到我们的 Serverless API 应用中，并为您提供详细的集成配置指南。我们认为，通过合作，我们可以提升高端并共同提升用户的AI使用体验。

### Describe the optimal solution

这是对应的活动文档：https:
[//ai.gitee.com/docs/openapi/serverless](https://ai.gitee.com/docs/openapi/serverless)
也可以用openai兼容的方式接入： https:
[//ai.gitee.com/docs/openapi/v1](https://ai.gitee.com/docs/openapi/v1)

[我们希望与贵公司产品确认合作意向。如果您对合作感兴趣，可以添加我的微信。]
![产品合作伙伴-马建仓小助手](https://github.com/user-attachments/assets/722b59c5-c2de-4471-bc78-613bd647d762)

合作权益包括：

产业合作伙伴展示墙：[https://ai.gitee.com/partnerFuture](https://ai.gitee.com/partner)
1v1 技术支持

期待您的回复！

**Comment by 88250** [comment]
思源笔记支持 OpenAI 兼容的 API，所以理论上用户只需配置就可以了，谢谢。

**Comment by pittosporum1** [comment]
> 思源笔记支持OpenAI兼容的API，所以理论上用户只需配置就可以了，谢谢。

好的，您这边方便接入下吗，我们可以把贵公司产品加入产品合作伙伴里联合做一次宣发

**Comment by pittosporum1** [comment]
接入后，可以提供下logo和官网链接，我们加上自己的官网

**Comment by 88250** [comment]
思源已经提供 OpenAI 设置了，不需要单独提供 Gitee AI 设置哦。
