### ISSUE TITLE
只有标题没有内容的文档无法导出 Markdown

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13631]
哪些文档需要导出 Markdown：

1. 有内容的文档
2. 没有子文档的文档
3. 开启了 `导出 Markdown 添加 YAML front-matter`，有自定义属性的空文档

---

![image](https://github.com/user-attachments/assets/1a68ffda-d698-4b24-b6e2-f5f888fdab32)

![image](https://github.com/user-attachments/assets/9af7c0ce-4023-44f8-8c01-a86821434838)

**Comment by songshua295** [comment]
建议对比15版本，16开始导出有问题的

**Comment by 88250** [comment]
* 我这里测试空文档和没有子文档的文档都可以导出
* 导出 Markdown 仅支持单个文档，不会包含子文档的

**Comment by songshua295** [comment]
> * 我这里测试空文档和没有子文档的文档都可以导出
> * 导出 Markdown 仅支持单个文档，不会包含子文档的，除非是多选导出或者导出笔记本

啊？是导出逻辑的想法有改变吗？之前能导出文档以及其所包含的子文档的。请看VCR：以下为`3.1.15`版本


![PixPin_2024-12-26_19-47-24](https://github.com/user-attachments/assets/dd3ee1f3-3744-4532-855a-1094dc9e42c8)

**Comment by 88250** [comment]
3.1.15 有个 bug 导致变为批量导出了，之前一直都是单文件导出的。

**Comment by TCOTC** [comment]
那怎么导出一个文档及其子文档为 Markdown ？

**Comment by 88250** [comment]
可以试试新建一个笔记本然后移动过去导出笔记本

**Comment by TCOTC** [comment]
不对啊，3.1.10 是包含子文档的

![image](https://github.com/user-attachments/assets/e1e5ac9e-8ec9-46c2-b382-cfc2f98f7edf)

**Comment by 88250** [comment]
那有可能是后面改动过，和其他几种格式统一了。

**Comment by TCOTC** [comment]
我从 3.1.10 试到 3.1.15 ，都是能导出子文档的，3.1.16 导出坏了，3.1.17 无法导出空文档为 Markdown。

应该是没修好 #13545

**Comment by 88250** [comment]
试试开发版分支编译，我这里导出是正常的。

**Comment by TCOTC** [comment]
我现在用的是 dev 最新的代码

**Comment by 88250** [comment]
看看前端和后端日志有没有报错

**Comment by TCOTC** [comment]
没有报错

**Comment by 88250** [comment]
打断点帮忙调试下吧

**Comment by TCOTC** [comment]
不行，代码看不懂一点。我一个个 commit 试过去了，在这个 commit 修改之后导出 Markdown 就没有子文档了：

https://github.com/siyuan-note/siyuan/commit/382f7dd2357668398702ab75a3a4bbdbf1701560

**Comment by 88250** [comment]
没有子文档是和其他格式做了统一，这个正常的，我指的是空文档无法导出的问题能重现？

**Comment by TCOTC** [comment]
单独导出空文档的话没问题，提到空文档是因为我用主库测试导出 Markdown 的时候能导出子文档，但会缺少内容为空的子文档。

用测试库导出的时候无论子文档有没有内容都无法导出。

**Comment by 88250** [comment]
子文档不导出的，除非用导出笔记本才会都导出。

**Comment by TCOTC** [comment]
> 没有子文档是和其他格式做了统一

我觉得不合理，用户用了这么久的逻辑不应该改

**Comment by songshua295** [comment]
> > 没有子文档是和其他格式做了统一
> 
> 我觉得不合理，用户用了这么久的逻辑不应该改

我赞同你的说法，jc

**Comment by songshua295** [comment]
> > 没有子文档是和其他格式做了统一
> 
> 我觉得不合理，用户用了这么久的逻辑不应该改

我赞同你的说法，jc

**Comment by 88250** [comment]
不改的话会有其他问题……比如包含引用的话会有逻辑冲突

**Comment by TCOTC** [comment]
所以我提了这个：https://github.com/siyuan-note/siyuan/issues/13602

**Comment by TCOTC** [comment]
排列组合：

- 导出带子文档，导出不带子文档
- 导出带块引文档，导出不带块引文档

**Comment by 88250** [comment]
我也回你了嘛，导出 .md 和 .sy 不适合加开关。

导出 .md 的需求主要用于数据迁移，至少是笔记本粒度才能保证数据完整性。当然，我也明白存在导出父子文档的需求场景，但是实现上可能有难度，不是加开关可以解决的，谁有时间的话可以研究一下。

**Comment by TCOTC** [comment]
> 导出 .md 的需求主要用于数据迁移

有用户用来分享 Markdown 版笔记的

**Comment by 88250** [comment]
放到一个笔记本里面导出笔记本顶顶吧

**Comment by 88250** [comment]
可以帮忙测试一下这里：

![image](https://github.com/user-attachments/assets/47a86cf4-90de-44fc-9742-f25cb59fec5f)

把这句注释掉，应该就可以包含子文档导出了，主要测试一下其他格式是否会有问题。

**Comment by 88250** [comment]
最新 dev 上已经提交包含子文档的改进了，需要多测测。

**Comment by TCOTC** [comment]
> 主要测试一下其他格式是否会有问题

其他格式的预期是包不包含子文档？

**Comment by TCOTC** [comment]
圈起来的是导出会带子文档的：

![image](https://github.com/user-attachments/assets/5684bc78-ff32-416d-baa3-5c135addf1dc)

**Comment by 88250** [comment]
嗯，那就统一为都带子文档。

**Comment by 88250** [comment]
统一吧先
