### ISSUE TITLE
数据库 - 行选择

### ISSUE THREAD

**Issue by Jerry-0202** [siyuan-note/siyuan#13646]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/615a41c4-7756-4794-908a-e4efd456c5c4)
一次性创建了很多个空行，但发现不需要这么多想要删除，却发现没有一个很好的多选手段。

### Describe the optimal solution

我的希望是能够添加shift区间选，或者说ctrl点选。如果可以的话，还可以鼠标框选区域。

另外我发现当单元格具有焦点，按下 shift + ↑/←/→/↓ 键，它是不能够像Excel一样的。这也阻止了我想实现我的目的。

**Comment by TCOTC** [comment]
Duplicate of #11975

**Comment by Jerry-0202** [comment]
> 重复的 #11975

没重复，补充：

![image](https://github.com/user-attachments/assets/511b76bb-9983-4de2-b95e-60b78ca557b0)


在这样的选择的场景下，希望能够将对应的条目打勾。更符合用户意图。

**Comment by TCOTC** [comment]
> 在这样的选择的场景下，希望能够将对应的条目打勾。

这里我们参考 Notion FlowUs Wolai 飞书 等的通行做法，只选中单元格而不勾选条目

**Comment by Jerry-0202** [comment]
> > 在这样的选择的场景下，希望能够将对应的条目打勾。
> 
> 这里我们参考 Notion FlowUs Wolai 飞书 等的通行做法，只选中单元格而不勾选条目

确实，可以配合delete删除字段内容，那么还是要增强键鼠选择功能
