### ISSUE TITLE
updateBlock api, krmarkdown IAL parsing error

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#13649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

调用 /api/block/updateBlock 时，使用以下参数会报错

```json
## 请求体
{
    "dataType": "markdown",
    "data": "11\n{: custom-expr=\"block.box + &quot;崮生幸运新&quot;\"  id=\"20241228100856-2d66z0j\" title=\"expr test\" type=\"doc\" updated=\"20241228095733\"}",
    "id": "20241228100856-2d66z0j"
}
## 响应
{
    "code": -1,
    "msg": "data block DOM failed: found invalid ID [block.box + &quot;崮生幸运新&quot;]",
    "data": null
}
```

如果将ial 中的 id 移动到最前面则不会出错
```json
## 请求体
{
    "dataType": "markdown",
    "data": "11\n{: id=\"20241228100856-2d66z0j\" custom-expr=\"block.box + &quot;崮生幸运新&quot;\"   title=\"expr test\" type=\"doc\" updated=\"20241228095733\"}",
    "id": "20241228100856-2d66z0j"
}
## 正常响应
```

光看表象，对于 ial 中的 id 的解析似乎永远是第一个属性

### Expected result

解析正确的id

### Version environment

```markdown
- Version: v3.1.17
- Operating System: windows
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
是的，解析时考虑到一个性能优化，id 必须放在第一个属性。
