### ISSUE TITLE
数据库 - 新功能特性：关联字段选择页滚动条

### ISSUE THREAD

**Issue by Jerry-0202** [siyuan-note/siyuan#13644]
### In what scenarios do you need this feature?

![image](https://github.com/user-attachments/assets/8efd2b52-b081-4ef5-8b97-95976deb1593)

如图所示。当关联的表格的条目足够的多，然后进行关联选择对方表格组件的时候，没有滚动条，无法滚动，很明显没有加载完，只有通过搜索，但这很考验用户记忆力。

### Describe the optimal solution

添加滚动条即可。

### Describe the candidate solution

考虑到条目足够多，可以考虑引入虚拟列表技术。

**Comment by TCOTC** [comment]
关联字段只有 16 个条目，只有窗口高度很小的情况下才会显示出滚动条

**Comment by Jerry-0202** [comment]
> 关联字段只有 16 个条目，只有窗口高度很小的情况下才会显示出滚动条

不是很理解，实际上我原来被关联的表格，它的条目不止16个，所以我不知道这里的16具体指的是什么。

现在我的两个数据库进行关联，数据库分别是a和b。
当我在数据库b中的关联字段选择数据库a的组件，实际上数据库a的条目是远超过弹出的图片所示。

所以，这个需求应该还算是一个真实的需求。

**Comment by TCOTC** [comment]
目前关联字段弹窗限制显示 16 个条目，有需要的话只能搜索。

不过我看 Notion 是这样设计的：

![image](https://github.com/user-attachments/assets/b05ff94f-491d-43e7-9d67-e9000e338526)

可以只显示一页条目，也可以显示所有条目（加上动态加载）

**Comment by 88250** [comment]
这个不考虑改变了，最多显示 16 条。
