### ISSUE TITLE
统一列表渲染为松散模式

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1364]
通过样式进行紧凑化。

**Comment by wo4wangle** [comment]
D大，松散模式 是指 列表项间距比较大吗？
如果是指这个，我倒希望 **列表越紧凑越好**
因为诸如列表和导图都是牺牲了空间换取层级可视化效果
就**希望这种牺牲更少一点**，能分得清就行

**Comment by 88250** [comment]
@wo4wangle 是的，松散模式就是这个意思。目前已经统一使用松散模式，视觉上以做调整，不会看上去太松散。

**Comment by wo4wangle** [comment]
> @wo4wangle 是的，松散模式就是这个意思。目前已经统一使用松散模式，视觉上以做调整，不会看上去太松散。

嗯，那看效果吧，紧凑是希望信息密度更高一些
不知道 间距 能否通过 主题 进行调解

**Comment by 88250** [comment]
能通过主题调整的。
