### ISSUE TITLE
Support one-click addition of Microsoft Defender exclusions

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#13650]
支持一键加入 Microsoft Defender 排除项

因 Microsoft Defender 引起的问题：

* 误报误杀导致内核程序丢失
* 抢占文件读写导致数据写入失败内核报错退出
* 影响性能

解决方案：

如果用户正在使用 Defender 并且未将思源安装路径和工作空间路径加入到排除项中的话，提示用户将这两个路径加入到排除项中，并提供一键加入排除项功能。

设计：

* 定时检查是否正在使用 Defender
  * 如果是的话再检查这两个路径是否已经加入排除项
  * 如果未加入则弹出提示消息告诉用户不加入排除项可能会引起的问题，并提供“一键加入排除项”按钮

实现：

* 通过开源项目 [elevator](https://github.com/siyuan-note/elevator) 请求用户提权执行程序
* 通过 `conf.system.microsoftDefenderExcluded` 记录是否已经添加过排除项
* PowerShell `Add-MpPreference -ExclusionPath` 添加排除项

**Comment by ZSCN2024** [comment]
想问了解一下为什么思源受到MD的影响这么大，其他笔记软件这样的问题好像不多
另外一个问题是，如果把思源笔记添加到排除项，是否MD也不查杀思源笔记的附件了？

**Comment by 88250** [comment]
思源的内核程序使用 golang 开发，编译为可执行文件，所以可能系统检查比较严格；
需要同时添加安装路径和工作空间路径

**Comment by ZSCN2024** [comment]
> 思源的内核程序使用 golang 开发，编译为可执行文件，所以可能系统检查比较严格； 需要同时添加安装路径和工作空间路径

感谢回答

**Comment by 88250** [comment]
应该不会，得测试看看

**Comment by TCOTC** [comment]
> 如果用户正在使用 Defender 并且未将思源安装路径和工作空间路径加入到排除项中的话

测试的时候我是不是得关掉无的火绒？

> 定时检查是否正在使用 Defender

这个时间间隔有多久？

**Comment by 88250** [comment]
要关掉其他杀毒软件才会用系统自带的；间隔 30 分钟

**Comment by TCOTC** [comment]
我这里关掉火绒打开思源也没提示，是因为我火绒没法完全关掉还是这个提示要等 30 分钟才弹出？

![image](https://github.com/user-attachments/assets/aff0b0c4-39c0-4928-962e-30dae9d0fa3a)

**Comment by 88250** [comment]
看上去是没有关闭火绒，看看这个？

![image](https://github.com/user-attachments/assets/828d1e05-0375-4504-bcc7-84b9698dae73)

**Comment by TCOTC** [comment]
可能是火绒阻止了打开 Microsoft Defender，也可能是我以前弄了什么东西禁用了，总之我这里打不开是测不了了

![image](https://github.com/user-attachments/assets/7cdb30ec-1efd-4f90-b451-3c0a63a75388)

**Comment by 88250** [comment]
没事，这个应该不影响其他功能，我自己多测试下。

**Comment by 5kyfkr** [comment]
这个提示能不能只提示三次，我公司电脑没有管理员权限添加不了，每次启动都出现有点难蚌。
另外我家里24H2 win11的电脑点了添加没任何反应，用管理员权限启动思源也一样，所以也希望不一直提示。

**Comment by 88250** [comment]
先手动改一下 conf.json 吧，正文末尾有方法。
