### ISSUE TITLE
数据库 - 标题：不支持粘贴文本

### ISSUE THREAD

**Issue by Jerry-0202** [siyuan-note/siyuan#13654]
### In what scenarios do you need this feature?

![PixPin_2024-12-28_23-56-20](https://github.com/user-attachments/assets/420d16a1-f756-4010-a86a-4adf5d909b89)

从视频可以看出，标题部分根本不支持键盘粘贴。

### Describe the optimal solution

改进即可

**Comment by TCOTC** [comment]
Duplicate of#13607
