### ISSUE TITLE
复制正文内容粘贴到标题时，应去除 Markdown 标记符

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13652]
一般带 Markdown 标记符是不符合用户预期的，除非用户粘贴的就是带 Markdown 标记符的纯文本。

---

如果要保留标记符粘贴，应当先粘贴到代码块里再复制带 Markdown 标记符的纯文本粘贴到标题。

然后就有一个问题，将“带 Markdown 标记符的纯文本” `粘贴为纯文本` 之后会去除 Markdown 标记符而不是保留原状。

**Comment by 88250** [comment]
> (但不等于粘贴纯文本)

这里没看懂

> 然后就有一个问题，将“带 Markdown 标记符的纯文本” 粘贴为纯文本 之后会去除 Markdown 标记符而不是保留原状。

用粘贴转义文本

**Comment by TCOTC** [comment]
严格来说带标记符的才是纯文本，粘贴到标题时默认粘贴**纯文本**的话不太对，所以只能说是**去除 Markdown 标记符的文本**

![image](https://github.com/user-attachments/assets/b9668a7c-8bd8-4d42-9eba-d569051e76ae)

**Comment by 88250** [comment]
那定义不太一样，思源里面定义的纯文本是去掉标记符的。

**Comment by Vanessa219** [comment]
粘贴处理的话都是使用的纯文本，因为没有 api 可以读取到 text/html

**Comment by TCOTC** [comment]
这样的话那就改成粘贴时纯文本去除 Markdown 标记符吧

**Comment by TCOTC** [comment]
现在直接粘贴是去除标记符，那粘贴纯文本就改成原样保留标记符吧

**Comment by 88250** [comment]
不改了不改了，作为标题需要标记符的场景太少了
