### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by mhlywxl** [siyuan-note/siyuan#13657]
### In what scenarios do you need this feature?

1. 网页版：支持离线查看，断网的时候弹窗的断网提示框是否可以关了，不要影响笔记的查看，否则断网情况下之前打开的笔记没法继续查看
2. 移动版：移动版增加配置链接到私有部署的服务端

### Describe the optimal solution

1. 网页版：支持离线查看，断网的时候弹窗的断网提示框是否可以关了，不要影响笔记的查看，否则断网情况下之前打开的笔记没法继续查看
2. 移动版：移动版增加配置链接到私有部署的服务端

**Comment by TCOTC** [comment]
> 断网的时候弹窗的断网提示框是否可以关了

可以打开网页开发者工具临时删掉这个元素

> 链接到私有部署的服务端

目前不会考虑 #5990

**Comment by mhlywxl** [comment]
> 可以打开网页开发者工具临时删掉这个元素。当然根本的解决办法是恢复网络连接，毕竟没有网络就是看不了的

这个在手机上的时候没法操作，是否可以增加个关闭的按钮

**Comment by TCOTC** [comment]
原则上不应增加关闭按钮，以免用户认为还能操作

**Comment by mhlywxl** [comment]
那是否可以在关闭后禁止编辑呢，这样至少能查看，等网络恢复后再允许编辑操作

**Comment by 88250** [comment]
不行的，没有网络的话连接不了内核，任何操作都无法进行。
