### ISSUE TITLE
Upgrade crashes or white screen on HarmonyOS

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13651]
鸿蒙 NEXT 版本升级会导致启动时闪退

https://ld246.com/article/1735383661249

**Comment by 88250** [comment]
我们这里测试从 v3.1.16 升级到 v3.1.17 正常，目前商店里面暂时也没有人反馈这个版本升级有问题的，需要继续收集反馈，谢谢。

**Comment by 88250** [comment]
稍微调整一下，总是解压缩前端资源。
