### ISSUE TITLE
思源笔记下载速度太慢，希望革新软件分发方式

### ISSUE THREAD

**Issue by snjjnlk** [siyuan-note/siyuan#1365]
### 描述问题 Describe the problem
思源笔记无论在任何地方，用任何方式下载，都无法脱离100KB每秒的速度，而且还很容易断掉连接。

### 期待的结果 Expected result
希望能增加百度网盘等下载方式。

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
谢谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/1353
