### ISSUE TITLE
Error screen on SiYuan application launch.

### ISSUE THREAD

**Issue by iproid** [siyuan-note/siyuan#13659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The problem started approximately on 20th of December. When launching SiYuan application I get an error screen and the main UI is not accessible. Prior to the problem I've updated SiYuan and updated Windows, I am not sure what was the reason. After the problem started I have updated SiYuan to last 3-4 patches from github with no effect. I tried disabling antivirus and firewall, uninstalling SiYuan and deleting folders C:\Users\***\SiYuan and C:\Users\***\.config\siyuan, installing SiYuan with firewall/antivirus disabled, moving the workspace folder, creating a new workspace.

### Expected result

SiYuan should start without the error screen.

### Screenshot or screen recording presentation

![image](https://github.com/user-attachments/assets/ac42f4b2-dd3c-4b67-b576-569dcc041b75)

### Version environment

```markdown
- Version: Pre-release v3.1.18-dev2 - v202412291301
- Operating System: Windows 10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/user-attachments/files/18269038/siyuan.log)

**Comment by 88250** [comment]
Hello, from the log, it seems that the dev version kernel started successfully, but then the kernel was terminated due to location reasons. From the existing log information, it is probably that the antivirus software killed the kernel process. Please make sure that the installation path and workspace path are added to the antivirus software trust list.

**Comment by iproid** [comment]
None of manipulations to the antivirus/firewall made any difference.
I have downgraded to version Pre-release v3.1.14-dev5 - v202411302059 and it works again.
