### ISSUE TITLE
可以搜索到超链接内容，但文本替换失效

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#13660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，可以搜索到超链接内容，但不能替换其中的文本。其它地方文本的替换正常

### Expected result

修复

### Version environment

```markdown
- Version: v3.1.15
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by TCOTC** [comment]
替换类型选了链接吗？

![image](https://github.com/user-attachments/assets/0c3ef745-3139-410a-ab0e-b2ff18a47710)

**Comment by pisceswb** [comment]
感谢指导，选了类型就可以了，谢谢！ @TCOTC
