### ISSUE TITLE
关于markdown格式过于单一的问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1366]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

当前以markdown解释器为基础的文本格式过于单一，不能支持多栏显示、背景颜色等功能。在一些情况下，多栏显示可以让界面更加紧凑，背景色也有强调功能，可以美化整体UI。

### 描述最优的解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/47321059/106363742-63137b80-6365-11eb-9d06-ce42cc484a6f.png)

**Comment by wo4wangle** [comment]
你说的这种大概要提供画布模式
像notion，onenote，wolai等
提供块的 自由布局

我希望的是**不要因此抛弃了 开源格式 如MD**
因为抛弃了开源格式就抛弃了 内容使用的自由
比如onenote的内容 只有onenote可用 
但是MD的内容 所有支持MD的都可以用

**Comment by 88250** [comment]
横向布局能力请关注 #790 感谢提议。

**Comment by dejavudwh** [comment]
> 你说的这种大概要提供画布模式
> 像notion，onenote，wolai等
> 提供块的 自由布局
> 
> 我希望的是**不要因此抛弃了 开源格式 如MD**
> 因为抛弃了开源格式就抛弃了 内容使用的自由
> 比如onenote的内容 只有onenote可用
> 但是MD的内容 所有支持MD的都可以用

我也同意，但是这个应该可以通过导出功能支持吧。
