### ISSUE TITLE
导出 PDF 的图片和文本重叠、出现滚动条

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13669]
[anki自动考研.sy.zip](https://github.com/user-attachments/files/18274413/anki.sy.zip)
[anki自动考研.pdf](https://github.com/user-attachments/files/18274416/anki.pdf)

**Comment by Vanessa219** [comment]
我这里是正常的，是不是受到什么样式的影响？
[anki自动考研.pdf](https://github.com/user-attachments/files/18275353/anki.pdf)

**Comment by TCOTC** [comment]
至少图片和这个标题重叠的问题是有的：

![image](https://github.com/user-attachments/assets/abd4c3ea-c2fb-4ea3-b2dc-2e84dccd502e)

**Comment by Vanessa219** [comment]
3.1.19
