### ISSUE TITLE
后台一直生成警告

### ISSUE THREAD

**Issue by 5kyfkr** [siyuan-note/siyuan#13672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图，后台每隔几十秒一直生成这个警告，看报错是某个字体没加载成功
The resource http://127.0.0.1:49732/appearance/fonts/JetBrainsMono-2.304/JetBrainsMono-Regular.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

![image](https://github.com/user-attachments/assets/2921cdd8-4ee2-49ac-bdfd-6c81c2ece8fd)
![image](https://github.com/user-attachments/assets/977379f2-c1b2-4308-8df0-15fceab3859a)

### Expected result

不报错

### Version environment

```markdown
- Version: 3.1.17
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by TCOTC** [comment]
有点奇怪，我这里没有警告

**Comment by 5kyfkr** [comment]
> 有点奇怪，我这里没有警告

我测试了没插件、代码片段、默认主题的工作空间可以复现

**Comment by 88250** [comment]
浏览器端使用的话试试清理存储：

![image](https://github.com/user-attachments/assets/72af4693-a46f-482d-947d-ffe72ddec5d0)

桌面端我这里也无法重现问题，先关闭了。

**Comment by 5kyfkr** [comment]
奇了怪了，我在公司电脑win10系统新建个工作空间也能复现
![image](https://github.com/user-attachments/assets/3715d9ee-476e-45aa-b875-f709c826e4a2)

**Comment by 88250** [comment]
直接访问一下这个路径看看能否加载，或者等新版本升级后再看看。

**Comment by 5kyfkr** [comment]
> 浏览器端使用的话试试清理存储：
> 
试了不行，反正我这稳定复现

https://github.com/user-attachments/assets/86b6c22a-9785-4184-83fe-af789b391d80

**Comment by 5kyfkr** [comment]
> 直接访问一下这个路径看看能否加载，或者等新版本升级后再看看。

都是正常加载的，只是没有被用上，dev2试了也一样

**Comment by 5kyfkr** [comment]
试了3.1.16没问题
![image](https://github.com/user-attachments/assets/92190a38-61c9-402a-9e33-b07909e647f2)

**Comment by 88250** [comment]
稍微改了一点不知道有没有效果，等新版本发布后再试试，谢谢。

**Comment by 5kyfkr** [comment]
![image](https://github.com/user-attachments/assets/5f60dc3b-6fd4-451f-9001-a45297e29e8c)
3.1.18新版还是报错，应该是这行代码的问题，我现在完全没用上这个字体，都是用自定义字体插件弄的代码块字体
 <link rel="preload" href="../../../appearance/fonts/JetBrainsMono-2.304/JetBrainsMono-Regular.woff2" as="font" type="font/woff2" crossorigin>

**Comment by 88250** [comment]
不影响的话先忽略吧，我也不清楚为啥……

**Comment by 5kyfkr** [comment]
好吧，一小时就能整几百条预警，强迫症犯了，祈祷某天突然好了

**Comment by TCOTC** [comment]
我这里也有警告了，然后我发现问题在哪了，这个字体被加载了但是没有地方会使用

![Image](https://github.com/user-attachments/assets/b91329af-8516-4b3a-adb2-4dfdef1c9eb9)

这两行直接删掉应该就没问题了：https://github.com/siyuan-note/siyuan/pull/13937

```html
<link rel="preload" href="../../../appearance/fonts/Noto-COLRv1-2.047/Noto-COLRv1.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="../../../appearance/fonts/JetBrainsMono-2.304/JetBrainsMono-Regular.woff2" as="font" type="font/woff2" crossorigin>
```
