### ISSUE TITLE
APT repository/PPA

### ISSUE THREAD

**Issue by KaKi87** [siyuan-note/siyuan#13673]
### In what scenarios do you need this feature?

Automatically updating SiYuan on Debian-based Linux distros

### Describe the optimal solution

An APT repository would host SiYuan's DEB build.

### Describe the candidate solution

A PPA (an APT repository hosted by launchpad.net) would build and host SiYuan.

### Other information

Automated updates is already possible from Flathub but that build type has limited filesystem access.

---
Thanks

**Comment by 88250** [comment]
Thanks for the suggestion, PR contributions are welcome.

**Comment by KaKi87** [comment]
This is actually not an in-app feature but an external service, and one that only you can set up because digitally signed by with a GPG key pair stored on your device and protected by your password.

Thanks

**Comment by 88250** [comment]
Can we use GitHub Actions to automate releases? If so, we can configure the relevant keys through settings.

**Comment by KaKi87** [comment]
Maybe in combination with GitHub Pages :thinking:
