### ISSUE TITLE
关于关系图优化的几点想法

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1367]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

因为D大在关系图优化的计划里没有详细说，所以想提一下几点自己的想法。

1. 关系图之间的层级关系不明显
2. 关系图的节点的粒度太细
3. 关系图选中节点中心化不够明显

### 描述最优的解决方案 Describe the optimal solution

1. 节点的大小可以有区分，比如一级标题和二级标题的区分、颜色和颜色的区分。
2. 可以去掉对引用、图片的节点，或者设置节点过滤。
3. 在选中当前节点之后，能够调整关系图来凸显以当前节点为中心的节点关系

**Comment by 88250** [comment]
你好，v0.7.0 后关系图目前已经支持颜色区分块类型，也提供了按类型的筛选。

关系图在接下来的一段时间里暂时只会进行微调，不准备引入大的改版了，这一块目前还没有很好的想法，感谢讨论。
