### ISSUE TITLE
Support for ignoring the prompt to add Microsoft Defender exclusions

### ISSUE THREAD

**Issue by ZSCN2024** [siyuan-note/siyuan#13687]
思源笔记必须加入MD排除列表吗？

### In what scenarios do you need this feature?

我不想把思源笔记加入MD排除项，但是这个弹窗已经连续弹出来三四次了。
设置项中也没有找到关闭这个弹窗的选项。

![image](https://github.com/user-attachments/assets/94396e4c-3382-4a5b-b675-6d7ffa85a18d)

### Describe the optimal solution

希望可以不要连续弹窗提醒

**Comment by TCOTC** [comment]
确实把开关漏掉了

**Comment by ZSCN2024** [comment]
> 确实把开关漏掉了

或者在弹窗上添加个  **不再提醒**  选项也行。

**Comment by 88250** [comment]
目前没有做“不再提示”的设置，如果不想提示，可以手动把 工作空间/conf/conf.json 中的 `microsoftDefenderExcluded` 设置为 `true`。

v3.1.19 中加入“忽略”按钮。

**Comment by TCOTC** [comment]
我觉得还是同时在设置里加个开关更好，忽略了之后也能重新添加

**Comment by 88250** [comment]
配置项太多，用户不一定看得到，起到提醒作用就可以了。

**Comment by TCOTC** [comment]
> 工作空间/conf/conf.json 中的 `microsoftDefenderExcluded` 设置为 `true`

话说这个会被 `导出设置` 吗？

**Comment by 88250** [comment]
会的，应该重置一下？

**Comment by TCOTC** [comment]
应该吧

**Comment by 88250** [comment]
ok

**Comment by Hzz-0802** [comment]
我的系统是网上大神精简版的，Microsoft Defender封闭时就“优化”掉了，没有排除列表可以添加。

**Comment by ZSCN2024** [comment]
> 目前没有做“不再提示”的设置，如果不想提示，可以手动把 工作空间/conf/conf.json 中的 `microsoftDefenderExcluded` 设置为 `true`。
> 
> v3.1.19 中加入“忽略”按钮。

软件重启后， `microsoftDefenderExcluded` 自动变为 `false`。

**Comment by 88250** [comment]
退出以后再改



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 1, 2025 02:12 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support for ignoring the prompt to addMicrosoft Defender exclusions (Issue #13687)




  
目前没有做“不再提示”的设置，如果不想提示，可以手动把 工作空间/conf/conf.json 中的 microsoftDefenderExcluded 设置为 true。
 
v3.1.19 中加入“忽略”按钮。
  
软件重启后， microsoftDefenderExcluded 自动变为 false。
