### ISSUE TITLE
支持把 .sy.zip 作为模板使用

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#13680]
> #13632 的另一个方案

便于分享模板、使用模板

**Comment by 88250** [comment]
不考虑了，模板是模板，数据导入是数据导入。

**Comment by TCOTC** [comment]
这个限制太大了，为什么不实现 Notion 类的模板呢？

**Comment by 88250** [comment]
设计不一样嘛

**Comment by TCOTC** [comment]
那就改改嘛，模板集市还是很有潜力的

**Comment by 88250** [comment]
用数据导入一样的吧，模板仅提供排版

**Comment by TCOTC** [comment]
但用户会希望把带数据库、图片之类的也导出到模板里。

还能上传到集市分享。

**Comment by 88250** [comment]
内容块分享目前还不确定是否要做，等以后再考虑。

**Comment by TCOTC** [comment]
用户的直觉就是导出单独的模板，不受原来的数据库影响：https://ld246.com/article/1736323309354
