### ISSUE TITLE
大批量笔记导出为markdown格式时无反馈，希望加入进度统计或错误提示

### ISSUE THREAD

**Issue by uowk** [siyuan-note/siyuan#13685]
### In what scenarios do you need this feature?

尝试导入10万的md文件笔记后，再做导出，选择markdown格式后时软件提示了"exporting, please wait... " , 但长时间等待后没有其他反馈提示， 等待超过10分钟后尝试关闭软件时出现长卡顿，可能是有进程在处理
<img width="317" alt="7d24d9c383a8c9a35fca460487a994b5" src="https://github.com/user-attachments/assets/0a699048-7040-4f8b-95d4-3b9bbf6c7359" />

### Describe the optimal solution

希望加入导出markdown或其他格式时的进度统计或错误反馈提示

**Comment by 88250** [comment]
导入以后要等索引建完，否则可能很多操作都会卡住。

这个问题暂时没法优化了，如果有大量数据，建议分工作空间，感谢反馈。

**Comment by uowk** [comment]
非常能理解这部分的优化不易，但还是想提一点， 如果能加个友好提示的话体验会好很多，例如现在的导出为sy格式的体验就很好
<img width="712" alt="1e54b1891516cb0f5b344aa6c540a0f9" src="https://github.com/user-attachments/assets/604a031e-2ffe-4229-9551-0a3201d0059e" />

**Comment by 88250** [comment]
明白了，稍后改进，感谢反馈。

**Comment by 88250** [comment]
v3.1.19

**Comment by uowk** [comment]
想到一个替代的方案， 首先导出sy格式的目前体验是没问题的， 如果可以提供一个三方工具在外部将导出后sy格式批量转markdown或其他格式也是很好的

**Comment by 88250** [comment]
这个要靠社区开发者贡献了，谢谢。
