### ISSUE TITLE
文件树 文件 拖放时候 鼠标滚轮的支持

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1369]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/106370597-72f78380-6396-11eb-9abe-c6d7af5beebb.png)

如图，我左键按住 “触发器”文件 拖放过程中发现 **要放置的目录比较远**
我通过 拖放到顶部边缘触发 文件树向上滚动 **不灵敏，也不好控制速度**
我自发的，**按住左键的同时 滚动鼠标滚轮，希望能通过滚轮快速到达我想放置的目录**
但是 这个时候 滑动滚轮是无效的

### 描述最优的解决方案 Describe the optimal solution

滑动滚轮有效

### 描述候选解决方案 Describe the candidate solution

可以的话，实现一下 文件树的 文件/目录 **右键 移动到** 功能
方案：弹出新的文件树，只有目录层级，然后可以选中要移动到的目录，确定移动

因为即使提供了滚轮滚动，有些要移动到的目录可能是关闭状态
这时候还需要提前找到目录并打开，再回到文件 拖动同时滚动 到目录，比较繁琐

**Comment by Vanessa219** [comment]
拖拽的时候是可以滚动滚轮的，至于移动到文件夹已经有人提过了 https://github.com/siyuan-note/siyuan/issues/449。感谢建议
