### ISSUE TITLE
块备注改进，采取更明显的显示方式

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1372]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
一篇文档中多个块有备注信息，事后需要查看备注的时候，目前需要准确找到相应块之后右击查看，事实上备注较多的话，很难记住哪个块有备注，逐个块右键点击检查显然是不合适的，希望改进备注的展示方式。

### 描述最优的解决方案 Describe the optimal solution
类似word的批注，文档右侧固定区域显示完整备注

### 描述候选解决方案 Describe the candidate solution
有备注的块在文档右侧显示备注图标，鼠标指向后浮动显示备注内容。

### 其他信息 Other information
飞书文档的处理，供参考：
1. 备注信息右侧展示图标
![image](https://user-images.githubusercontent.com/657850/106374412-5d964f80-63be-11eb-8e49-e4deb35026d9.png)

2. 点击相应图标后展开内容
![image](https://user-images.githubusercontent.com/657850/106374418-638c3080-63be-11eb-9006-4f1f0100eea4.png)

**Comment by 88250** [comment]
感谢建议，会在 https://github.com/siyuan-note/siyuan/issues/1342 中进行改进。
