### ISSUE TITLE
When Image or attachment reference removed, they should be deleted (or ask for deletion)

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1373]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

If there is a note with `images` or `attachments`, they are not deleted when their reference are cleared from the doc, the same behavior happens when removing the whole note

### 描述最优的解决方案 Describe the optimal solution

When the Reference of an image or attachments are removed from the document -> ask for confirmation to delete the corresponding assets (image or attachment)

OR --> Also would be nice if they are moved to a trash folder so that we give some space for the user to undo (Restore The assets)

**Comment by 88250** [comment]
Hello, please try Settings - Assets - Cleanup unreferenced assets. 

Data change use Git for versioning, thank you.

**Comment by eslam-gomaa** [comment]
Very Nice, Thank you
