### ISSUE TITLE
The cursor is lost when the super block is continuously entered

### ISSUE THREAD

**Issue by coff11** [siyuan-note/siyuan#1375]
### 描述问题 Describe the problem
使用`超级块`时，连续输入`{{{}}}`后，然后在中间敲击回车换行，光标会自动跳动到文档顶部，且刚才输入的{{{}}}不可见（仍然存在，可以删除，但单击时不会显示）。

### 期待的结果 Expected result
光标应停留在正确位置。

### 版本环境 Version environment

* 版本 Version：当前版本 v0.7.0 / Kernel v0.7.0
* 操作系统 Operating system：MacOS 11.1
* 浏览器（如果使用）Browser (if used)：客户端

**Comment by 88250** [comment]
稍后排查，感谢反馈。
