### ISSUE TITLE
列表中，换行后删除项目符号、使用Tab缩进后，输入文字时会自动打开代码块

### ISSUE THREAD

**Issue by coff11** [siyuan-note/siyuan#1379]
### 描述问题 Describe the problem
列表中，换行后删除项目符号、使用Tab缩进后，输入文字时会自动打开代码块

### 期待的结果 Expected result
正常输入

### 截屏或录屏演示 Screenshot or screen recording presentation
![Feb-01-2021 00-22-46](https://user-images.githubusercontent.com/20441641/106390602-15aa1380-6424-11eb-819c-63c7b51e37d8.gif)

### 版本环境 Version environment

* 版本 Version：v0.7.1
* 操作系统 Operating system：MacOS 11.1
* 浏览器（如果使用）Browser (if used)：客户端

**Comment by 88250** [comment]
你好，删除项目符号以后就是段落，如果此时缩进的话就是代码块了，这个是 Markdown 语法，感谢反馈。
