### ISSUE TITLE
排除功能，将指定子目录内的文档以普通 md 格式处理，不在排除的子目录使用 sy.md 格式

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#138]
做个排除功能，就像 `.gitignore` 那样起作用，有些笔记不需要链接，不想用 sy.md 格式，只希望保持 md 格式进行使用（比如我的一个 Diary 文件夹，要在手机上编辑，写日记），就需要通过通配符进行排除，在思源笔记上查看、编辑时，将这些文档以普通 md 文档对待，对指定子目录不使用 sy.md。

**Comment by 88250** [comment]
现在已经提供导入向导，已有 md 和 sy md 是完全分开的文件夹了。sy 文件夹内暂时不考虑支持 md 情况，谢谢反馈。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/231
