### ISSUE TITLE
列表缩进关联子项的问题

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1381]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106395042-f9fe3780-643a-11eb-8441-bce4a84544d7.mp4

如图，2处tab，没有携带子项：我还以为tab的逻辑变了，但是脱离子项也不合理
然后在6处tab，发现又携带了子项：所以这应该是2处的tab有BUG

### 期待的结果 Expected result

和过去一样 tab会携带子项一起调整

### 版本环境 Version environment

* 版本 Version：0.7.1

**Comment by 88250** [comment]
感谢反馈，应该不关联子项缩进的。

**Comment by wo4wangle** [comment]
> 感谢反馈，应该不关联子项缩进的。

说反了吧…
应该是**关联子项缩进**吧？

**Comment by 88250** [comment]
不关联的，参考 Word。

**Comment by wo4wangle** [comment]
> 不关联的，参考 Word。

嗯，明白了
我到word和typora上操作了一下：的确是不关联的
但是 我这种需求还是在的，而且很高频：子项跟随缩进
word和typora也都提供 其他的方式去做：多选批量缩进，能否支持一下呢
因为关联缩进的调整是很自然的需求

一点讨论：
word也许不是合适的参考对象吧：word和思源应该不太是一类，而且word的列表也不是主打
在列表方面更强的，比如logseq, RoamEdit, RemNote等全部都用的是思源过去的方式：tab直接 关联子项缩进
为什么弃用了 tab关联子项 呢

**Comment by 88250** [comment]
通过拖拽进行块的结构调整更好，尽量统一逻辑。
