### ISSUE TITLE
大纲中无法显示 HTML 标签包裹文字

### ISSUE THREAD

**Issue by chenyingxiu** [siyuan-note/siyuan#1384]
问题如图所示
![image](https://user-images.githubusercontent.com/40259489/106409235-11f5ab80-647b-11eb-8903-77a08b607fcd.png)

**Comment by 88250** [comment]
感谢反馈，后续修复。

**Comment by chenyingxiu** [comment]
### 0.7.5版本修改后，出现后续问题
如图所示
![image](https://user-images.githubusercontent.com/40259489/106568781-b1479b00-656e-11eb-9006-cd5f41be2f21.png)
![image](https://user-images.githubusercontent.com/40259489/106568910-e2c06680-656e-11eb-84f1-1e6ac7ccf49a.png)
* 创建HTML包裹<*>，上图为下划线<u>，可以在大纲中刷新并显示
* 利用HTML结尾</*>包裹时，上图为下划线</u>，大纲中无法刷新显示

**Comment by 88250** [comment]
@chenyingxiu 收到，稍后修复。
