### ISSUE TITLE
可以不可以取消跨域限制

### ISSUE THREAD

**Issue by xzclove** [siyuan-note/siyuan#1386]
http://127.0.0.1:6806/stage/build/desktop/
这种可以访问，但是我用域名指定到服务器的  6806端口访问，
比如 http://note.baidu.com -> http://127.0.0.1:6806

看到提示有跨域限制，访问不了，怎么处理？

需求是 一个思源笔记作为服务器，然后公网进行编辑操作

**Comment by 88250** [comment]
你好，请试试这个参数：

![image](https://user-images.githubusercontent.com/873584/106472402-9aa53380-64dd-11eb-99af-47682b25dd0b.png)
