### ISSUE TITLE
思源笔记社区在海外无法访问

### ISSUE THREAD

**Issue by YukoOshima** [siyuan-note/siyuan#1387]
### 描述问题 Describe the problem

在海外的时候， 思源笔记自带的同步功能无法使用。 提示无法连接。 社区也无法进入。

### 期待的结果 Expected result

希望能开放海外用户访问。 

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

### 更多信息 More information

我的ip地址是 143.92.127.224

**Comment by 88250** [comment]
你好，服务端没有做地域限制，如果网络不通，很有可能是 GFW 的关系，这个估计没法解决，抱歉抱歉。
