### ISSUE TITLE
内容块聚焦关系图

### ISSUE THREAD

**Issue by coff11** [siyuan-note/siyuan#1388]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
目前思源中的关系图分为两种：第一个是单个文件内所有「块」及连接的关系图，第二个是全局以文件名为组织的的关系图。

但这背后似乎有一个潜在的共识：单个文件内的所有「块」都是相关的。

思源是以「块」作为连接粒度的，那么就应该考虑到有一种情况：单个文件内的块可能并不相关。可能用户只是按照日期去命名文件而已（如Roamresearch中的每日笔记功能，当然思源中也有）。

在这种情况下，现有的两种关系图并不具有很好的效果（因为现有的两种关系图其实背后的本质都是以文件作为基准的，而不是「块」，如果想查看某个块的关系图，调出的结果仍然包括了当前文件其他不相关块的联系）。

### 描述最优的解决方案 Describe the optimal solution
在某个「块」上右击调出菜单 ⇒ 关系图应该是以当前「块」为核心的关系图（展示与当前块有连接关系的块），而不是该「块」所在文件的关系图。
![image](https://user-images.githubusercontent.com/20441641/106420180-0e6f1e00-6495-11eb-8473-a219a8f8bd99.png)

**Comment by 88250** [comment]
你好，文档块和文档内的块天然就是关联的（是文档块的子块），所以目前会出现不相关的块。这个后面一点考虑，应该可以只显示当前块的引用关系的，感谢建议。

**Comment by 88250** [comment]
v1.2.0 实现了内容块聚焦，以这个为基础就能够实现聚焦块的关系图了，近期会上线，谢谢。
