### ISSUE TITLE
日志文件中报错

### ISSUE THREAD

**Issue by MACDfree** [siyuan-note/siyuan#1390]
### 描述问题 Describe the problem
查看日志发现有报错

### 期待的结果 Expected result
消除报错

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/3363410/106433847-b0016a00-64ab-11eb-847f-c2412bb8132b.png)

### 版本环境 Version environment

* 版本 Version：0.7.1
* 操作系统 Operating system：windows 10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5902741/siyuan.log)

**Comment by 88250** [comment]
你好，我这里重现不了问题，麻烦看下报错的笔记本中动态查询嵌入的语句，谢谢。

**Comment by MACDfree** [comment]
测试发现，当我输入动态查询嵌入语句时，当输入到select * from时会出现此报错。

**Comment by 88250** [comment]
感谢反馈，稍后改进。
