### ISSUE TITLE
内容块动态查询支持深度参数

### ISSUE THREAD

**Issue by ghost** [siyuan-note/siyuan#1391]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
群里有老哥提到，使用诸如!{{h:内容}}的时候，会搜出包括其子块在内的全部内容，我想可能因为他的数据量较大，所以只想查询标题本身进行宏观的预览

### 描述最优的解决方案 Describe the optimal solution
如果可能的话，大概需要加一个对搜索结果范围的控制

### 其他信息 Other information
![image](https://user-images.githubusercontent.com/74618439/106441410-f9a28280-64b4-11eb-992b-e4a79bee984f.png)
比如此处，只需要显示是标题的内容即可，子内容不用列出，可以方便快速预览

**Comment by 88250** [comment]
感谢反馈，这个可能需要加一个 `depth`  来控制子块深度，暂时还没想好，需要考虑一段时间。

**Comment by 88250** [comment]
似乎没有更多用户需要，先不考虑了。

**Comment by 88250** [comment]
标题块后续解决提案 https://github.com/siyuan-note/siyuan/issues/4404
