### ISSUE TITLE
列表项多选缩进及反向缩进

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1392]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

批量进行缩进

### 描述最优的解决方案 Describe the optimal solution

参考word实现：可以多选，然后tab/shift tab，而且可以间隔多选
见图，按住ctrl,可以间隔多选：
![image](https://user-images.githubusercontent.com/46141646/106451589-c0244400-64c1-11eb-921d-52b61d913cb0.png)

### 描述候选解决方案 Describe the candidate solution

列表多选缩进几乎带有列表的软件都有，比如：obsidian, logseq, roamedit, typora…

**Comment by 88250** [comment]
感谢提议，后期考虑。
