### ISSUE TITLE
列表块折叠后黑点消失

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1395]
### 描述问题 Describe the problem
列表块折叠异常

![zhedie](https://user-images.githubusercontent.com/37007969/106468156-87439980-64d8-11eb-9fae-dc787e7250f7.gif)

### 版本环境 Version environment

* 版本 Version：0.075
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，列表块完全折叠以后是会消失的，我关闭了，感谢反馈。
