### ISSUE TITLE
列表 Tab 带子项层级缩进

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1397]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106477000-a34c3880-64e2-11eb-9a68-42fcb5ca4c31.mp4

如视频， 在2处tab：不携带子项进行整体层级调整
但是在3处shift tab：就携带子项进行整体层级调整
这种不一致会给人造成困惑：**为什么反向缩进就携带子项，而正向缩进就不携带子项呢**
这样的性质在word里也没有

### 期待的结果 Expected result

我的看法是：**正向也携带子项**
**几乎所有以 列表见长 的软件都是 携带子项缩进的：如同样基于markdown的logseq也是携带了子项调整**

因为子项在编辑过程种就有“属于父项”的含义
缩进不单单是格式上的缩进，也是层级调整，而层级是关联的，不是孤立的
就如移动一个文件夹的层级，**自然就会携带其子文件夹和文件 一起移动** 一般

doc中的列表缩进更多是配合页面尺标在做，而不是层级：相邻列表项的缩进差**甚至可以横跨一个页宽**
思源是基于markdown，而非doc，思源应该选更适合markdown的列表层次，而不是doc的列表缩进

且 拖放调解 主要方便在列表项上下顺序的调整，而不是列表项左右层级的调整
因为 拖放 预览的是横线，而不是竖线，横线分隔上下清晰，但是分隔左右不清晰
拖放也需要经过 多次悬停等待，按键更高效和准确

### 版本环境 Version environment

* 版本 Version：0.7.5

**Comment by 88250** [comment]
感谢建议，后期考虑。
