### ISSUE TITLE
撤销操作光标定位到撤销前而不是上一个操作后

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#1398]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
文章修改跨度比较大时，比如先在第1行操作，再在第999行操作，此时撤销第999行的操作，光标就定位到第1行了。就需要再跳到999行进行操作，很不人性化。
所以，希望撤销第999行的操作时，光标可以定位到 对第999行操作前的位置。

**Comment by Vanessa219** [comment]
撤销的话都应该都需要跳转到上一次光标的位置，这样才知道大概是撤销了一些什么。

**Comment by yeshaopeng6688** [comment]
> 撤销的话都应该都需要跳转到上一次光标的位置，这样才知道大概是撤销了一些什么。

问题是，跳转的不是撤销的位置，而是**上一个操作后**的位置！
![s](https://user-images.githubusercontent.com/69628966/108966221-df755200-76b8-11eb-90fd-8a2b28c30e24.gif)
先输入aaa、bbb、ccc、ddd
此时，当前最后一个操作时输入ddd
现在，删除bbb，
撤销，
        需要的是跳转到 bbb
        而不是跳转到ddd，
跳转到ddd，我只知道**撤销前操作了啥**，而不知道我撤销了啥。

**Comment by yeshaopeng6688** [comment]
另外，提一个粘贴引用的bug。
![s](https://user-images.githubusercontent.com/69628966/108967015-ea7cb200-76b9-11eb-94cb-f234f830e293.gif)

**Comment by yeshaopeng6688** [comment]
使用的都是最新版本 v1.04
