### ISSUE TITLE
Block floating window support navigating and zoom-in

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1399]
类似面包屑导航，将现有的文档路径扩充为块路径，并且浮窗内容支持原地[缩放](https://github.com/siyuan-note/siyuan/issues/1231) 。

![image](https://user-images.githubusercontent.com/873584/106493248-da771580-64f3-11eb-9fbc-93dbef4a9d9e.png)

**Comment by lss6378** [comment]
建议参考下文档管理器的层级路径解决方案：
![路径导航](https://user-images.githubusercontent.com/15924513/106750806-4926b100-6663-11eb-979d-96baf8c1e3ee.gif)

**Comment by 88250** [comment]
This feature will be included in v1.2.0.
