### ISSUE TITLE
MBP 安装后第一次打开可以，关掉后打不开了 ，而且每个markdown文件下会多生成一份永久文件

### ISSUE THREAD

**Issue by goldpumpkin** [siyuan-note/siyuan#14]
如图是再选择笔记本之后，生成的文件
![image](https://user-images.githubusercontent.com/22197388/93758073-5b66fc00-fc3a-11ea-8057-3de727ad606c.png)

**Comment by 88250** [comment]
* 关闭后不能打开的问题 v0.2.0 修复
* xxx.sy.md 是思源笔记的格式，具体细节请看软件自带的帮助文档中关于导入部分的描述

感谢反馈。
