### ISSUE TITLE
提议：将目前的列表块，升级成大纲块

### ISSUE THREAD

**Issue by hdg8087** [siyuan-note/siyuan#1400]
大篇多段的内容，可以用多级标题来结构化。

但内容复杂的单段落，用标题来结构化，就不太方便了。因为：
【1】这时候，标题下的内容往往不多，使用标题会显得煞有介事。
【2】本来一个段落的内容，分成了标题和正文两部分，这时标题和内容间距太远，内容割裂感太强。
【3】不知道选哪级标题。按一般思路，一级标题后再次分级，是二级标题，但仅一段话，就分出1个二级标题，显得轻重不匹。

单段内容太复杂了，拆成多段内容不就可以了？
有时候可以，有时候却不太方便。
毕竟，一个段落就是一个语义块，拆分后，语义块就割裂了。

列表块升级成大纲块，我觉得可能有以下几点：
【1】允许无序列表和有序列表互相嵌套。
【2】大纲可点击黑点折叠。
【3】列表项之间的行间距，可选择松散模式 or 紧凑模式。
【4】自定义大纲黑点与左侧边界的距离。
【5】搜索时，可自定义以列表项 or 整个列表为单位，进行结果展示。
【6】如果能够，可选择第大纲第1行是否显示黑点。比如我这段第1行就没有序号。

大纲块的作用：
【1】解决痛点：大纲块解决的，是单段复杂内容层级化、结构化的痛点。
【2】现实状态：这个痛点比较隐形，很多从大纲转到md，开始挺好、后续使用时，发现没有大纲，极为痛苦和不适。毕竟，大纲的层级性、结构化，太清晰、太容易了。
【3】整合两端：在md里内置大纲块，可以充分利用好md和大纲的优势。很多人不习惯大纲满屏的黑点，没有黑点或黑点不方便，却也很不习惯。

以上未考虑技术难度，请D大斟酌考虑。

**Comment by 88250** [comment]
感谢建议，目前暂时不考虑引入新的块类型，因为列表块应该已经够用了：

1. 无序有序相互嵌套是可以的
2. 折叠用块标识
3. 依赖主题
4. 依赖主题
5. 使用类型过滤
6. 依赖主题

块标识是对块的操作入口，通过快捷键可以较为高效操作。
