### ISSUE TITLE
列表 快捷键 折叠 BUG

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1401]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106540142-4da37a80-653a-11eb-8cd7-ff558df2208c.mp4

如视频，2处，通过点击的方式折叠：正常
但是通过快捷键的方式来折叠：无法折叠子项

### 期待的结果 Expected result

快捷键的方式正常折叠，case中无论是纯按键还是alt+左键都不正常

### 版本环境 Version environment

* 版本 Version：0.7.5

**Comment by 88250** [comment]
你好，视频演示中折叠的是列表项下的段落块，如果要折叠列表项的话需要选中列表项：

![image](https://user-images.githubusercontent.com/873584/106540930-e981b600-653b-11eb-8aac-4c8e1ec07932.png)
