### ISSUE TITLE
列表空白行

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#1402]
### 描述问题 Describe the problem

每次打开会多出很多空白行

### 期待的结果 Expected result

正常显示

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/18739609/106543152-2485e880-6540-11eb-8c7b-e5620965463f.png)

### 版本环境 Version environment

* 版本 Version：0.7.5
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

### 更多信息 More information

无

**Comment by banjuer** [comment]
补充: 换成daylight主题也一样,还是有很多空白行
![image](https://user-images.githubusercontent.com/18739609/106545830-0a9ad480-6545-11eb-8857-47a7db191cf6.png)

**Comment by 88250** [comment]
你好，麻烦发一下 .md 给我 845765@qq.com

**Comment by banjuer** [comment]
> 你好，麻烦发一下 .md 给我 [845765@qq.com](mailto:845765@qq.com)

日志与文件已发送

**Comment by 88250** [comment]
你好，我在 v0.7.8 开发版上看没有报错，空段落的地方手动删除即可。

今晚应该会发布 v0.7.8 请更新后再试，谢谢。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/1414 中继续修复。

**Comment by banjuer** [comment]
了解!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: D<mailto:notifications@github.com>
发送时间: 2021年2月3日 10:15
收件人: siyuan-note/siyuan<mailto:siyuan@noreply.github.com>
抄送: banjuer<mailto:banjuer@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [siyuan-note/siyuan] 列表空白行 (#1402)


在 #1414<https://github.com/siyuan-note/siyuan/issues/1414> 中继续修复。

―
