### ISSUE TITLE
同步页面改进

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1403]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
两台电脑交替使用思源笔记时，希望随时看到目前笔记本的同步状态（最近一次成功同步的时间、IP地址、客户端类型如浏览器或者app等）

### 描述最优的解决方案 Describe the optimal solution
同步页面显示上述信息

**Comment by 88250** [comment]
建议用网盘进行同步，感谢。
