### ISSUE TITLE
当块引用被标签包裹，且存在于标题块中时，标签页锚文本会变成{{.text}}

### ISSUE THREAD

**Issue by ihyw** [siyuan-note/siyuan#1405]
### 描述问题 Describe the problem
当块引用被标签包裹，且存在于标题块中时，标签页锚文本会变成{{.text}}，如下图

### 期待的结果 Expected result
应该显示内容本身

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/74618439/106590688-5753cf00-6588-11eb-9fbd-a206caa679c7.png)

### 版本环境 Version environment

* 版本 Version：v0.7.5
* 操作系统 Operating system：Windows10

**Comment by 88250** [comment]
不支持动态标签（通过锚文本模板渲染）的，感谢反馈。
