### ISSUE TITLE
LaTeX 公式颜色命令\color支持

### ISSUE THREAD

**Issue by wangfh5** [siyuan-note/siyuan#1406]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

给公式块中的部分公式增加颜色。

### 描述最优的解决方案 Describe the optimal solution

使用`\color`语法，可以直接以颜色名为参数，也可输入rgb数据：
```
{\color{red} abc}
```

```
{\color[rgb]{0,1,0} abc}
```

目前思源和Typora的渲染结果对比：
![image](https://user-images.githubusercontent.com/51868839/106616962-19b36e00-65a9-11eb-83a7-1a5524489cf6.png)

![image](https://user-images.githubusercontent.com/51868839/106616969-1b7d3180-65a9-11eb-9ba7-fb7dbd25cb14.png)

**Comment by yanyu2015** [comment]
> ### 你在什么场景下需要该功能？ In what scenarios do you need this function?
> 给公式块中的部分公式增加颜色。
> 
> ### 描述最优的解决方案 Describe the optimal solution
> 使用`\color`语法，可以直接以颜色名为参数，也可输入rgb数据：
> 
> ```
> {\color{red} abc}
> ```
> 
> ```
> {\color[rgb]{0,1,0} abc}
> ```
> 
> 目前思源和Typora的渲染结果对比：
> ![image](https://user-images.githubusercontent.com/51868839/106616962-19b36e00-65a9-11eb-83a7-1a5524489cf6.png)
> 
> ![image](https://user-images.githubusercontent.com/51868839/106616969-1b7d3180-65a9-11eb-9ba7-fb7dbd25cb14.png)

我想要用类似于wl那种可以直接选中部分的底纹或字体颜色的公式高亮....
哈哈，感觉要求有点高了，
目前只能自己再截图对公式的部分做标注说明

**Comment by MACDfree** [comment]
> ### 你在什么场景下需要该功能？ In what scenarios do you need this function?
> 给公式块中的部分公式增加颜色。
> 
> ### 描述最优的解决方案 Describe the optimal solution
> 使用`\color`语法，可以直接以颜色名为参数，也可输入rgb数据：
> 
> ```
> {\color{red} abc}
> ```
> 
> ```
> {\color[rgb]{0,1,0} abc}
> ```
> 
> 目前思源和Typora的渲染结果对比：
> ![image](https://user-images.githubusercontent.com/51868839/106616962-19b36e00-65a9-11eb-83a7-1a5524489cf6.png)
> 
> ![image](https://user-images.githubusercontent.com/51868839/106616969-1b7d3180-65a9-11eb-9ba7-fb7dbd25cb14.png)

我测试了一下，发现换个公示引擎就好了

![image](https://user-images.githubusercontent.com/3363410/106924057-a72dc400-6749-11eb-9abc-c34d1020554a.png)

![image](https://user-images.githubusercontent.com/3363410/106924131-bb71c100-6749-11eb-966b-e268b1cf23c0.png)

**Comment by zhangjl-sjtu** [comment]
katex已经支持颜色语法，设置里面更换一下就好

**Comment by 88250** [comment]
先关闭了，感谢反馈。
