### ISSUE TITLE
列表 Tab 空的子项消失问题

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1409]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106641804-96067b00-65c2-11eb-9ef1-e106d8f1b969.mp4

如视频，5处tab : 子项消失
不合理

### 期待的结果 Expected result

子项不消失

### 版本环境 Version environment

* 版本 Version：0.7.8

**Comment by 88250** [comment]
目前暂时是这么设计的，如果子列表为空（没有任何文本）的话会删掉。
