### ISSUE TITLE
列表 复制粘贴 列表属性消失问题

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1410]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106674726-c106c400-65ee-11eb-9e31-451fe339fee9.mp4

如视频，选中3、4列表项复制，然后在空白处或列表处进行粘贴：3列表项失去了列表属性

### 期待的结果 Expected result

3列表项保留列表属性

### 版本环境 Version environment

* 版本 Version：0.7.8

### 更多信息 More information

其实剪切3、4也有问题，测试便知：保留了无意义的列表点
想要迁移列表内容时候发现的问题

**Comment by Vanessa219** [comment]
这个需要把光标再往前移动一点，大概到篮框位置，否则选中的只是里面的段落，没有选中列表
![image](https://user-images.githubusercontent.com/970828/107012732-5fa04a00-67d4-11eb-945e-374f9d0a7a49.png)
