### ISSUE TITLE
希望能方便的选中当前“块”，并进行删除

### ISSUE THREAD

**Issue by yangxiche** [siyuan-note/siyuan#1411]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
需要删除当前块的时候，目前的操作是要 占击光标，然后从最后的文字向最开始的文字进行拖动光标选中全部内容，然后再删除。
实际上我需要直接选中当前块就可以删除整个块。

ESC选中当前块后，可以使用backspace删除整个块。

**Comment by 88250** [comment]
谢谢建议，后期考虑。

**Comment by 88250** [comment]
合并到 #889 中处理，谢谢。
