### ISSUE TITLE
列表折叠无法展开问题

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1412]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106682137-d387fa00-65fc-11eb-8b1b-899a1f1f2ae8.mp4

如视频，折叠2及其子项后，在2处尝试用alt + 左键：2及其子项无法展开
或者说折叠之后，无法通过快捷键展开折叠

### 期待的结果 Expected result

可以通过快捷键展开折叠

### 版本环境 Version environment

* 版本 Version：0.7.8

**Comment by liubo-hebau** [comment]
当按住ALT ，滑动鼠标到列表中某一项后，假设A，单击后的直觉逻辑是：折叠A的所有子表项，保留A的内容，并加强显示A是被折叠过的。而思源的处理方式是，只把A单做一个段单独折叠，导致A变灰色，其字表项未受影响，这个操作感觉比较反直觉。大概折叠的关键问题就在这里。

**Comment by liubo-hebau** [comment]
假设有父表项A ，其字表项B，思源要想折叠A，一种方式是用鼠标找到A和B的狭小中间地带点击折叠，折叠后又只能通过左侧图标，在菜单项里展开A，操作有点怪。通过父子表项间的“中间地带”折叠感觉没有必要。

**Comment by 88250** [comment]
@liubo-hebau 嗯，正在想办法改进。

**Comment by wo4wangle** [comment]
> 假设有父表项A ，其字表项B，思源要想折叠A，一种方式是用鼠标找到A和B的狭小中间地带点击折叠，折叠后又只能通过左侧图标，在菜单项里展开A，操作有点怪。通过父子表项间的“中间地带”折叠感觉没有必要。

我认为这么做是为了 把单独折叠表项A 和 折叠A和其子项 分开
因为A单独一个列表项还可以携带shift enter的换行  
这时候单独折叠A相当于折叠了A的shift enter内容
这种是有折叠意义的

其实可以加一个逻辑：如果A没有shift enter内容，alt 左键A就是折叠A及其子项
因为折叠没有shift enter内容的A，只是颜色变灰了而已，没有多少实际折叠意义

不知道现在的实现逻辑 @Vanessa219

**Comment by wo4wangle** [comment]
> 假设有父表项A ，其字表项B，思源要想折叠A，一种方式是用鼠标找到A和B的狭小中间地带点击折叠，折叠后又只能通过左侧图标，在菜单项里展开A，操作有点怪。通过父子表项间的“中间地带”折叠感觉没有必要。

我认为这么做是为了 把单独折叠表项A 和 折叠A和其子项 分开
因为A单独一个列表项还可以携带shift enter的换行  
这时候单独折叠A相当于折叠了A的shift enter内容
这种是有折叠意义的

其实可以加一个逻辑：如果A没有shift enter内容，alt 左键A就是折叠A及其子项
因为折叠没有shift enter内容的A，只是颜色变灰了而已，没有多少实际折叠意义

不知道现在的实现逻辑 @Vanessa219
