### ISSUE TITLE
列表 ctrl+enter 越过子项建立同级列表项 功能

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1413]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/46141646/106682706-067ebd80-65fe-11eb-9a03-61242a2d9a97.png)

如图，写完列表项1的丰富内容2-6后，想要创建下一个主题x，接着进行x的丰富
x越过了2-6，因为2-6是属于主题1的，而不是x
目前有 折叠、拖动、不断回车 三种方式去做
但是都效率都不高

### 描述最优的解决方案 Describe the optimal solution

在1的末尾 ctrl enter 越过1的子表项创建同级列表项x

### 其他信息 Other information

最好能在 快捷方式的设定 中提供 创建同级列表项（不越过子项） 和  创建同级列表项（且越过子项） 的设定自由

因为 一般有子项的时候，往往都希望 一键 直接越过子项 创建同级表项
我的话大概率会直接把enter做为 创建同级列表项（且越过子项），ctrl enter作为 创建同级列表项（不越过子项）
这在实践中具备合理性，但是考虑到用户已有习惯和其他软件方案，可以防御性的默认现在的enter行为

**Comment by 88250** [comment]
感谢建议，后期考虑。

**Comment by Vanessa219** [comment]
可以使用 shift+arrowup，shift+arrowup ，ctrl+shift+a
