### ISSUE TITLE
关系图节点浮窗干扰改进

### ISSUE THREAD

**Issue by ChengzuHuang** [siyuan-note/siyuan#1417]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在使用关系图进行漫游的时候

每次把鼠标放到节点上就会弹出预览，非常不方便漫游的使用。希望能够设置为默认不开启预览，使用快捷键才开启。

**Comment by 88250** [comment]
@Vanessa219 按住 <kbd>Alt</kbd> 时悬浮节点才展现浮窗不知道是否可行。
