### ISSUE TITLE
增加设置能够使关系图默认不开启预览

### ISSUE THREAD

**Issue by ChengzuHuang** [siyuan-note/siyuan#1418]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在使用关系图进行漫游的时候，每次把鼠标放到节点上就会弹出预览，非常不方便漫游的使用。希望能够使其默认不开启预览，配合快捷键才能够预览。

**Comment by 88250** [comment]
和 https://github.com/siyuan-note/siyuan/issues/1417 重复了。
