### ISSUE TITLE
导出功能bug(pdf,markdown)

### ISSUE THREAD

**Issue by qylixin** [siyuan-note/siyuan#1419]
### 描述问题 Describe the problem
1. 导出PDF时，当图片比较大会被截断
2. 导出PDF样式与原笔记不一致(尤其是表格和代码)
3. 导出Markdown时会丢失图片

### 期待的结果 Expected result

1. 导出PDF图片不会被截断
2. 导出PDF样式与笔记样式保持一致
3. 导出Markdown时可以附带图片一起导出（可以类似typora一样建立一个xxx.assets图片目录）

### 截屏或录屏演示 Screenshot or screen recording presentation

编辑器样式
<img width="897" alt="image" src="https://user-images.githubusercontent.com/18651098/106716468-6f375b80-6639-11eb-9fbb-75b38b905301.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/18651098/106716512-7e1e0e00-6639-11eb-88e7-b78fc6cba453.png">

PDF样式
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/18651098/106716697-b6255100-6639-11eb-809f-f12d9c87512b.png">

导出Markdown
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/18651098/106716799-d5bc7980-6639-11eb-961b-cc1e229dd19d.png">

### 版本环境 Version environment

* 版本 Version：v0.7.8 / Kernel v0.7.8
* 操作系统 Operating system：MacOS 10.15.7

**Comment by 88250** [comment]
你好，导出 Markdown 如果需要带资源附件的话请导出 TextBundle。其他问题后续会改进，感谢反馈。
