### ISSUE TITLE
添加待办清单 (ToDo List)的大纲视图

### ISSUE THREAD

**Issue by hkunzhe** [siyuan-note/siyuan#1421]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
查看文档中的待办清单 (ToDo List)，显示进度完成情况

### 描述最优的解决方案 Describe the optimal solution
[Boostnote](https://github.com/BoostIO/Boostnote)可以动态追踪文档中待办清单的完成情况
![image](https://user-images.githubusercontent.com/30763967/106753789-1aaad500-6667-11eb-9338-5bed28e48d02.png)
但是没法对具体的待办清单有一个完整的概览（大纲视图），当文档内容很多，并且其中含有较多的待办清单，这个功能就显得非常重要。可以添加一个类似现在软件中使用的书签按钮，通过点击待办清单按钮，可以看到文档中待办清单的大纲视图。

**Comment by rumengsiji** [comment]
![Uploading image.png…]()
可以通过内容快动态查询实现，不过还是觉得有个待办清单 (ToDo List)的大纲视图会更好些，如果能查看历史已完成的待办就更好了，虽然这个也能通过动态查询实现，但总归不方便。

**Comment by 88250** [comment]
感谢提议和讨论，先通过动态查询嵌入顶顶，后期考虑通过插件支持，谢谢。
