### ISSUE TITLE
关于英文文章的字数统计

### ISSUE THREAD

**Issue by yiweiwong** [siyuan-note/siyuan#1422]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
群友提出，希望有针对英文单词的字数统计，而非对字母的统计

### 其他信息 Other information
![image](https://user-images.githubusercontent.com/74618439/106759012-3022fd80-666d-11eb-9126-1d328c6a1bc7.png)

**Comment by 88250** [comment]
v1.2.0 中加入对“词”的计数，谢谢。
