### ISSUE TITLE
升级 Electron 框架

### ISSUE THREAD

**Issue by ChengzuHuang** [siyuan-note/siyuan#1423]
### 描述问题 Describe the problem
之前也提过，问题一直没得到解决，稳定性非常差，经常多点几下或者用着用着就卡死，闪退。

### 截屏或录屏演示 Screenshot or screen recording presentation
![bug2](https://user-images.githubusercontent.com/10935766/106770812-4b940580-6679-11eb-924d-e58c35bc14ff.gif)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5919622/siyuan.log)

**Comment by 88250** [comment]
请打开开发者工具，看下 Console 下是否有报错，谢谢。

**Comment by ChengzuHuang** [comment]
程序初始化后：
![image](https://user-images.githubusercontent.com/10935766/106826084-26c38080-66c1-11eb-9ab9-239af5b2d7fb.png)
崩溃时没任何信息，直接退出了

**Comment by 88250** [comment]
请问网络是否允许了端口 6806 访问？

**Comment by ChengzuHuang** [comment]
应该是开启了
![bug3](https://user-images.githubusercontent.com/10935766/106832235-3dbba000-66cc-11eb-8335-df89dd7e1c4c.gif)
![image](https://user-images.githubusercontent.com/10935766/106832272-4ca25280-66cc-11eb-8af3-13732a3cfd33.png)

**Comment by 88250** [comment]
帮忙留意闪退卡死的时候进程是否还在以及内存、CPU 使用情况。

**Comment by ChengzuHuang** [comment]
![bug4](https://user-images.githubusercontent.com/10935766/106834261-0e0e9700-66d0-11eb-98bd-3d5a713ae3d8.gif)

**Comment by 88250** [comment]
好像是点到 
![image](https://user-images.githubusercontent.com/873584/106834587-b3c20600-66d0-11eb-8018-148f76c6a5a7.png) 这一篇的时候奔溃的，请帮忙试下是否是这样？

**Comment by ChengzuHuang** [comment]
看起来主要是在文档切换时，也和我的印象相符。
![Uploading bug5.gif…]()

**Comment by 88250** [comment]
我在本地目前重现不了，不太确定是否和数据相关。方便打包发一下这个库到我邮箱么？ 845765@qq.com

**Comment by 88250** [comment]
你好，我测试了多次，但是重现不了。对了， 麻烦你在 Chrome 浏览器上直接使用，看看能否重现，谢谢。

![issue](https://user-images.githubusercontent.com/873584/106840377-043e6100-66db-11eb-814b-cf07224af2a3.gif)

**Comment by ChengzuHuang** [comment]
使用浏览器就一点问题没有。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 中午11:22
收件人:&nbsp;"siyuan-note/siyuan"<siyuan@noreply.github.com&gt;;
抄送:&nbsp;"Zu"<floyd777@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 频繁闪退，卡死，求提升稳定性 (#1423)





 
你好，我测试了多次，但是重现不了。对了， 麻烦你在 Chrome 浏览器上直接使用，看看能否重现，谢谢。

**Comment by 88250** [comment]
这个问题估计有点难以定位，预计会在 v0.9.0 升级一下 Electron 框架，等 v0.9.0 发布以后请帮忙回测，谢谢。

**Comment by ChengzuHuang** [comment]
没问题😉

**Comment by ChengzuHuang** [comment]
升级框架后到现在还没出现过崩溃

**Comment by 88250** [comment]
@ChengzuHuang 感谢反馈 :)
