### ISSUE TITLE
文件树和页签 提供 复制文件路径到剪贴板 功能

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1424]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

只要操作对象是一个文件系统的文件，往往都会提供此功能，比如vscode, 福昕pdf, everything等
![image](https://user-images.githubusercontent.com/46141646/106815921-8ca70c80-66af-11eb-90d8-8b95b358120f.png)

![image](https://user-images.githubusercontent.com/46141646/106815932-903a9380-66af-11eb-9f30-217febcaeffd.png)

![image](https://user-images.githubusercontent.com/46141646/106815940-93ce1a80-66af-11eb-8af3-3ce5c947d582.png)

我个人几乎每形成一个文档都考虑复制绝对路径 放到anki里面回溯使用

### 描述最优的解决方案 Describe the optimal solution

文件树和页签 提供 复制路径到剪贴板 功能

**Comment by 88250** [comment]
使用 URL 是更好的选择，本地路径如果一定要复制的话请通过打开文件位置手动复制。
