### ISSUE TITLE
标签 提示残留 问题

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1426]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106823331-b6fec700-66bb-11eb-8ddb-4e46fa036bcc.mp4

如视频，我快速 **敲完了** “疑问” 标签，然后标签的候选提示 依旧出现了
这个时候我敲了回车，又出现了一个 “疑问” 标签
这不是我想要的效果 ： 我不需要候选，因为我手动敲完了

我手动敲完标签的原因是：提示跟不上手速 我手敲不用等待提示 效率更高
我回车的原因是：我敲完了 标签 需要去换行写其他内容，这个时候往往出现 重复标签

### 期待的结果 Expected result

优化 标签提示速度 （如果可以的话）
对 标签的 完成做判断，如果标签完成了 提示快速自动消失：#疑问# 右边的#都敲完了，就表示不需要提示了
也许显示提示前 再做一次是否进行显示的检查更好 （也许弄个递归提示检查，因为可能又敲了个新的 需要提示的 标签）
手速够快的，等提示加载完成并出现的时候，可能都编辑到另一个次元了（形容编辑上下文的迥然不同，我是真偶有碰到）

**Comment by Vanessa219** [comment]
重现不了，是不是因为你先 # 关闭了标签
![image](https://user-images.githubusercontent.com/970828/107009712-5e6d1e00-67d0-11eb-9cde-a11e18457d77.png)
然后又输入了一个 #
![image](https://user-images.githubusercontent.com/970828/107009813-7f357380-67d0-11eb-871f-5140456123d5.png)
所以产生了提示，然后再回车就把提示带过去了？

**Comment by wo4wangle** [comment]
> 重现不了，是不是因为你先 # 关闭了标签
> ![image](https://user-images.githubusercontent.com/970828/107009712-5e6d1e00-67d0-11eb-9cde-a11e18457d77.png)
> 然后又输入了一个 #
> ![image](https://user-images.githubusercontent.com/970828/107009813-7f357380-67d0-11eb-871f-5140456123d5.png)
> 所以产生了提示，然后再回车就把提示带过去了？

空格 是我 为了上屏 输入法的候选
shift 3 就是 #
键盘的录制 我是设定了较长时间保留 以免消失得太快 
所以 看起来我好像 又输入了一个 “空格 shift 3#
其实并不是又输了一个，而是延长显示，还没消失

我没有利用 标签的候选提示
结尾的# 也是手敲的，原因是候选提示太慢
这个问题 在我这边是比较明显的，基本必出，0.8.5也一样：

https://user-images.githubusercontent.com/46141646/107044843-cdae3680-67ff-11eb-94eb-83cce7edf20e.mp4

**Comment by Vanessa219** [comment]
可能是你标签太多了，已经模拟出来，下个版本修复。
