### ISSUE TITLE
列表 粘贴图片后 空项消失 问题

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#1429]
### 描述问题 Describe the problem

https://user-images.githubusercontent.com/46141646/106835523-6e9ed380-66d2-11eb-84b7-230f0cc724d5.mp4

如视频， 在3处shift enter 后 粘贴一个图片：3下的空列表项消失了

场景是这样的：
我编辑3，然后enter、tab打算写3的子项内容时候，发现需要shift enter贴图对3进行说明，然后再去编辑3的子项
然而，3的子项消失了，我需要重新建立

### 期待的结果 Expected result

3的空列表项不消失

### 版本环境 Version environment

* 版本 Version：0.8.0

**Comment by 88250** [comment]
感谢反馈，设计如此 https://github.com/siyuan-note/siyuan/issues/1409#issuecomment-772154521
