### ISSUE TITLE
LaTeX cannot be rendered when exporting to PDF

### ISSUE THREAD

**Issue by jonecns** [siyuan-note/siyuan#1430]
1. 版本信息：
当前版本 v0.8.0 / Kernel v0.8.0
Windows10

2. 文件内容

```
绪论

梯度

哈密尔顿算子 $\nabla$ 

 $\displaystyle f(x)=\int_{0}^{x}g(t)dt$ 变上限函数
```

KaTeX和MathJax都测试过，导出后为下图
![image.png](https://b3logfile.com/file/2021/02/image-2ad46f2c.png)

**Comment by yanyu2015** [comment]
> 1. 版本信息：
>    当前版本 v0.8.0 / Kernel v0.8.0
>    Windows10
> 2. 文件内容
> 
> ```
> 绪论
> 
> 梯度
> 
> 哈密尔顿算子 $\nabla$ 
> 
>  $\displaystyle f(x)=\int_{0}^{x}g(t)dt$ 变上限函数
> ```
> 
> KaTeX和MathJax都测试过，导出后为下图
> ![image.png](https://camo.githubusercontent.com/1bc50e135ebdf0d27be067f1decb936916e07743981ed09b95a89b3e498d36c7/68747470733a2f2f62336c6f6766696c652e636f6d2f66696c652f323032312f30322f696d6167652d32616434366632632e706e67)

我目前遇到是，导出PDF的时候，一直开在这个页面
![image](https://user-images.githubusercontent.com/11142054/106887240-d7f90380-671f-11eb-96c9-09aaada695b3.png)
打算导出的时候先用typora顶顶
另外今天我发现mathjax在换行的时候有问题，用KaTeX可以

**Comment by Vanessa219** [comment]
@yanyu2015 文章多的话需要多等一下

**Comment by Vanessa219** [comment]
@jonecns 我这里是正常的，你看一下导出 html 可以正常显示么？
![image](https://user-images.githubusercontent.com/970828/107007787-f9b0c400-67cd-11eb-8d48-abeba3450b29.png)

**Comment by jonecns** [comment]
@88250 导出html后打开提示一个鉴权，登陆以后显示如下


![image](https://user-images.githubusercontent.com/49853153/107457574-465d1c00-6b8d-11eb-9d29-71e96cb4eb3c.png)

**Comment by 88250** [comment]
@jonecns 版本是 v0.9.2 么？这个问题应该修复过。

**Comment by jonecns** [comment]
@88250 更新0.9.6后问题已解决
