### ISSUE TITLE
块引用部分复制粘贴到新文档，引用次数在文档右侧不显示

### ISSUE THREAD

**Issue by alphaleek** [siyuan-note/siyuan#1433]
### 描述问题 Describe the problem
![image](https://user-images.githubusercontent.com/76611744/106873085-0c17f880-670f-11eb-90fb-7b6ef37b5cca.png)
我把一个文档中的块引用，使用快捷键复制粘贴到新的文档。这个新的文档名称右侧的引用次数不显示

### 期待的结果 Expected result
修复bug

### 版本环境 Version environment

* 版本 Version：0.8
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5924626/siyuan.log)

**Comment by 88250** [comment]
文件数上的计数需要重新展开才会刷新，暂时不作调整了，感谢反馈。

**Comment by alphaleek** [comment]
> 文件数上的计数需要重新展开才会刷新，暂时不作调整了，感谢反馈。

不明白重新展开是如何操作，我重启软件、刷新文件树、关闭文件夹重新导入均无效
