### ISSUE TITLE
支持选中文本一键格式化

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1436]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

在完成文本的编写之后，但是之后可能需要进行文本格式的改变。

类似代码编辑器的功能

也就是如果当前选中文本进行的是类似格式化的操作，就不对文本进行删除，而是进行格式化

![s12](https://user-images.githubusercontent.com/47321059/106889020-5eaee000-6722-11eb-8025-da5aee386c18.gif)

**Comment by 88250** [comment]
感谢建议，后期考虑。

**Comment by Vanessa219** [comment]
格式化可以使用工具栏上的按钮或快捷键
