### ISSUE TITLE
引入列表的松散模式后，ALT+鼠标的折叠方式错乱，ALT+V的折叠方式也失效

### ISSUE THREAD

**Issue by liubo-hebau** [siyuan-note/siyuan#1437]
### 描述问题 Describe the problem
在最新版更新（080）中，引入了列表的松散模式，但在以前版本中已经较成熟的ALT+鼠标选中表项折叠的方式均失效或错乱。ALT+V的快捷键折叠方式也失效，特别是在退回以往版本后，由于笔记文件发生了变化，退回后问题仍存在。

### 期待的结果 Expected result
修复新版中ALT+鼠标的点选表项折叠

### 截屏或录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/50349859/106899541-71c8ac80-6730-11eb-900e-caf882cc14a3.mp4

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，在段落上选中的是段落块，不是列表项块或者列表块。目前在子列表块上折叠以后只能通过块标菜单进行展开，这个问题会在 #https://github.com/siyuan-note/siyuan/issues/1412 中考虑如何处理，感谢反馈。

![issue](https://user-images.githubusercontent.com/873584/106901737-13e99400-6733-11eb-8b00-01d7be222c29.gif)
