### ISSUE TITLE
设置-外观-模式设置无效

### ISSUE THREAD

**Issue by MACDfree** [siyuan-note/siyuan#1439]
### 描述问题 Describe the problem

设置-外观-模式设置无效

### 期待的结果 Expected result

设置-外观-模式设置有效

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/3363410/106925412-093af900-674b-11eb-9213-24dcad4e0b6e.png)

![image](https://user-images.githubusercontent.com/3363410/106925592-31c2f300-674b-11eb-9117-18c2c88e625a.png)

### 版本环境 Version environment

* 版本 Version：0.8.5
* 操作系统 Operating system：windows 10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，我这里无法重现，请试下重置外观。

**Comment by MACDfree** [comment]
重置外观后问题解决
