### ISSUE TITLE
问题反馈渠道即将进行语言分区 Issue feedback channel will soon be language partition

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1440]
大家好，我们决定在 v1.0.0 发布以后对问题反馈渠道进行分区：

* 中文反馈请到 [思源笔记 - 领域 - 链滴](https://ld246.com/domain/siyuan)
* 英文反馈请到 [Issues · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues)
* 发错分区的内容会被直接关闭或者删除
* v1.0.0 发布以后我们将上线英文版官网

感谢你的支持 ❤️ 

---

Hello everyone, we decided to partition the issue feedback channels after v1.0.0 is released:

* For Chinese feedback, please go to [SiYuan - Domain - LianDi](https://ld246.com/tag/siyuan)
* For English feedback, please go to [Issues · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues)
* The contents of the wrong partition will be directly closed or deleted
* We will launch the English version of the official website after v1.0.0 is released

Thank you for your support ❤️

**Comment by deerainw** [comment]
I've decided to create issues on GitHub in English from now on. <img src="https://user-images.githubusercontent.com/32661922/106988864-c2c9b680-67ab-11eb-8a9b-69e2cf93ea43.png" width="20" />
