### ISSUE TITLE
Android端无法使用

### ISSUE THREAD

**Issue by walklty** [siyuan-note/siyuan#1441]
### 描述问题 Describe the problem

小米9, 开发版21.1.28
启动时首先显示该apk为旧版Android打造, 可能无法正常使用.
之后进入"黑屏", 无任何相应.
尝试开启所有权限, 仍然是这个问题

**Comment by 88250** [comment]
你好，应用启动以后需要在手机浏览器访问 `http://127.0.0.1:6806` 或者在同一局域网内设备上使用 `http://手机 IP:6806` 访问。后续我们会完善应用使用引导，感谢反馈。
