### ISSUE TITLE
查找局域网思源伺服

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#1443]
### In what scenarios do you need this function?

使用思源安卓伺服时, 每次局域网IP变化后(断网重连等), 使用伺服比较麻烦

### Describe the optimal solution
局域网内, 手机使用无线, 大部分并没有做mac绑定, 那么每次进入局域网环境内, 获取到的IP都有可能是不同的,
每次使用时都需要查看当前手机IP地址然后再到浏览器输入, 这个过程比较麻烦且不友善. 探讨以下解决方案

1. 提供一个公共查找服务, 可以查找局域网内思源伺服, 可以是`find.siyuan.com`等等. 类似群晖查找功能.
群晖查找:
登录`http://find.synology.com/`, 会自动查找出局域网内的群晖nas, 提示用户进行连接

### Describe the candidate solution

2. 思源定时输出当前伺服地址`IP:PORT`到UI界面, 并提供复制功能. 用户复制发送到电脑上后, 使用最新地址访问

### Other information

无

**Comment by 88250** [comment]
问题反馈渠道即将进行语言分区 https://github.com/siyuan-note/siyuan/issues/1440 请到中文社区反馈，谢谢。
