### ISSUE TITLE
having the Toggle list would be very nice ! 

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1444]
### In what scenarios do you need this function?

It would be nice to have this kind of block that's used in Notion called "Toggle List" as it helps keeping the notes very organized

### Describe the optimal solution

![image](https://user-images.githubusercontent.com/33789516/107010766-75474c80-679f-11eb-80b1-2fa644a99d63.png)

![image](https://user-images.githubusercontent.com/33789516/107010817-88f2b300-679f-11eb-8f15-a38eedeab24b.png)

---

```html
<details>
    <summary>I have keys but no locks. I have space but no room. You can enter but can't leave. What am I?</summary>
    words here
</details>
```

![image](https://user-images.githubusercontent.com/33789516/107011306-23eb8d00-67a0-11eb-9e93-c1aad2eccd28.png)

**Comment by Vanessa219** [comment]
Sorry, I don't know "toggle list", but you can `alt click` to expand/contract list item.

https://user-images.githubusercontent.com/970828/107013792-c83bf680-67d5-11eb-83a8-70a68e1f222b.mp4

**Comment by eslam-gomaa** [comment]
Thank you for replying,

The  "block hide" option is very good,  but the one in "Notion" is different,   please find this shared page as an example

https://www.notion.so/darkenman/Test-Page-63cdd365700f45c4a531b5bc6320a596

> Please check these parts
![image](https://user-images.githubusercontent.com/33789516/107038439-2e6c4d80-67c5-11eb-976e-6b693d44b487.png)

**Comment by Vanessa219** [comment]
Sorry, I can’t see the difference between example and example2

**Comment by eslam-gomaa** [comment]
yes, and that makes them comfortable to use.

#### as an example here is how I use them to organize my notes

![image](https://user-images.githubusercontent.com/33789516/107040010-52309300-67c7-11eb-9217-da16c0470d10.png)

**Comment by Vanessa219** [comment]
siyuan note has a more flexible architecture, you can toggle "headings, list item, and super block"

![动画 (71)](https://user-images.githubusercontent.com/970828/107043580-2bda1a00-67fe-11eb-95c9-9c56db134d8a.gif)

**Comment by eslam-gomaa** [comment]
good, but when the `super block` is flooded is disappears !

**Comment by fengqiii** [comment]
Because of siyuan's  traditional folder structure, it might not have such free Toggle List as Notion, which is the real web-based notes. Siyuan now couldn't embed pages in pages and toggle them, but just cite the blocks that you want. It is the disadvantage; it is also the advantage for its versatility and security of the notes.

**Comment by Vanessa219** [comment]
@eslam-gomaa Oh, this is a bug of including the title in the super block. You can use `! ((` embed doc or any block

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/1449

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/1449
