### ISSUE TITLE
Anki类复习功能

### ISSUE THREAD

**Issue by YukoOshima** [siyuan-note/siyuan#1446]
### In what scenarios do you need this function?
学习新的知识, 利用艾宾浩斯记忆曲线防止遗忘

### Describe the optimal solution
通过添加tag, 或者类似remnote一样的标记符号, 把知识点加入到复习队列里面.

### Other information
作为学生党非常喜欢思源笔记, 同时也喜欢remnote的复习功能, 如果二者能够结合就好了.

**Comment by 88250** [comment]
后期考虑，感谢建议。

**Comment by Jack20152019** [comment]
赞👍非常需要这样的功能，参考obsidian to anki这个插件，就挺好，做到思源和anki同步就行
