### ISSUE TITLE
MAC系统下克隆在线空间的笔记本至本地出现未导入的提示

### ISSUE THREAD

**Issue by ihyw** [siyuan-note/siyuan#1450]
### Describe the problem
一位群友，在其MAC系统下克隆在线空间中的笔记本至本地出现文件夹未导入的提示

### Expected result
正常情况应该是克隆好后直接打开

### Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/74618439/107063257-20461d80-6815-11eb-81c6-efba3707db25.png)
![image](https://user-images.githubusercontent.com/74618439/107063241-1ae8d300-6815-11eb-9bf4-52ef15ab51af.png)

### Version environment

* Version: v0.8.5

### Log File
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5934005/siyuan.log)

**Comment by 88250** [comment]
中文反馈请到链滴，我关闭了。
