### ISSUE TITLE
a bug when  launch

### ISSUE THREAD

**Issue by jacob11112** [siyuan-note/siyuan#1451]
### Describe the problem

when launch siyaun.exe , then interface is blank
### Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/74459689/107109096-3e913500-6878-11eb-98d7-e388cacb0347.png)

### Version environment

* Version: 0.8.5
* Operating system: windows 10
* Browser (if used): 

### Log File

I 2021/02/06 12:40:49 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 12:40:49 working.go:89: 

I 2021/02/06 12:40:49 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 12:40:50 lang.go:67: initialized languages
D 2021/02/06 12:40:50 conf.go:79: loaded conf [C:\Users\Jacob\.siyuan\conf.json]
I 2021/02/06 12:40:50 lang.go:67: initialized languages
D 2021/02/06 12:40:50 conf.go:79: loaded conf [C:\Users\Jacob\.siyuan\conf.json]
I 2021/02/06 12:40:50 conf.go:186: local serve path [http://192.168.1.110:6806]
I 2021/02/06 12:40:50 conf.go:190: initialized conf
I 2021/02/06 12:40:50 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/06 12:40:50 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2021/02/06 12:40:50 conf.go:186: local serve path [http://192.168.1.110:6806]
I 2021/02/06 12:40:50 conf.go:190: initialized conf
I 2021/02/06 12:40:50 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/06 12:40:50 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2021/02/06 12:40:51 working.go:89: 

I 2021/02/06 12:40:51 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 12:40:51 working.go:89: 

I 2021/02/06 12:40:51 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 12:40:52 lang.go:67: initialized languages
D 2021/02/06 12:40:52 conf.go:79: loaded conf [C:\Users\Jacob\.siyuan\conf.json]
I 2021/02/06 12:40:52 lang.go:67: initialized languages
D 2021/02/06 12:40:52 conf.go:79: loaded conf [C:\Users\Jacob\.siyuan\conf.json]
I 2021/02/06 12:40:52 conf.go:186: local serve path [http://192.168.1.110:6806]
I 2021/02/06 12:40:52 conf.go:190: initialized conf
I 2021/02/06 12:40:52 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/06 12:40:52 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2021/02/06 12:40:52 conf.go:186: local serve path [http://192.168.1.110:6806]
I 2021/02/06 12:40:52 conf.go:190: initialized conf
I 2021/02/06 12:40:52 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/06 12:40:52 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2021/02/06 12:40:53 working.go:89: 

I 2021/02/06 12:40:53 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 12:40:53 working.go:89: 

I 2021/02/06 12:40:53 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 12:40:54 lang.go:67: initialized languages
D 2021/02/06 12:40:54 conf.go:79: loaded conf [C:\Users\Jacob\.siyuan\conf.json]
I 2021/02/06 12:40:54 conf.go:186: local serve path [http://192.168.1.110:6806]
I 2021/02/06 12:40:54 conf.go:190: initialized conf
I 2021/02/06 12:40:54 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/06 12:40:54 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2021/02/06 12:40:54 lang.go:67: initialized languages
D 2021/02/06 12:40:54 conf.go:79: loaded conf [C:\Users\Jacob\.siyuan\conf.json]
I 2021/02/06 12:40:55 conf.go:186: local serve path [http://192.168.1.110:6806]
I 2021/02/06 12:40:55 conf.go:190: initialized conf
I 2021/02/06 12:40:55 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/06 12:40:55 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2021/02/06 12:40:55 working.go:89: 

I 2021/02/06 12:40:55 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 12:40:55 working.go:89: 

I 2021/02/06 12:40:55 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\Jacob\AppData\Local\Temp\siyuan], read only [false], container [standard]

**Comment by 88250** [comment]
> serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

SiYuan requires permission to listening to port 6806.

**Comment by jacob11112** [comment]
it isn't  reason.i tried to run it as administor and stop softwares like windows defender ,but it seems not change too.

**Comment by 88250** [comment]
Sorry, I can't reproduce it...

**Comment by jacob11112** [comment]
thanks ,it's OK now.probably  the problem is  the defender as you said,but i'm confused why it did't change when i run it as administered and stop softwares like windows defender.
