### ISSUE TITLE
一般文档窗口可固定在侧边栏

### ISSUE THREAD

**Issue by liubo-hebau** [siyuan-note/siyuan#1452]
### In what scenarios do you need this function?
一些如清单等高频访问信息可以在写入一般文档窗口后使之固定在侧边栏，类似快捷访问，提升工作效率。

### Describe the optimal solution
一般文档窗口可固定在侧边栏，并做窗体大小适配

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/1440
