### ISSUE TITLE
连接的bug

### ISSUE THREAD

**Issue by MontaEllis** [siyuan-note/siyuan#1453]
### Describe the problem

老是出现这样的问题

### Expected result

https://ellis.oss-cn-beijing.aliyuncs.com/img/20210206162908.png

### Log File

I 2021/02/04 16:48:16 working.go:84: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/02/04 16:48:16 working.go:85: kernel [v0.8.0] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\ellis\AppData\Local\Temp\siyuan], read only [false]
I 2021/02/04 16:48:17 lang.go:67: initialized languages
D 2021/02/04 16:48:17 conf.go:96: initialized language [zh_CN] based on device locale
I 2021/02/04 16:48:18 conf.go:185: local serve path [http://192.168.3.47:6806]
I 2021/02/04 16:48:18 conf.go:189: initialized conf
I 2021/02/04 16:48:18 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/02/04 16:48:18 webdav.go:36: initialized WebDAV server
I 2021/02/04 16:48:18 conf.go:335: initialized box
I 2021/02/04 16:48:18 repo.go:40: initialized git repo
I 2021/02/04 16:48:18 working.go:84: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/02/04 16:48:18 working.go:85: kernel [v0.8.0] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\ellis\AppData\Local\Temp\siyuan], read only [false]
I 2021/02/04 16:48:18 working.go:135: port [6806] is opened, try to check version of running kernel
I 2021/02/04 16:48:18 lang.go:67: initialized languages
D 2021/02/04 16:48:18 conf.go:79: loaded conf [C:\Users\ellis\.siyuan\conf.json]
I 2021/02/04 16:48:18 conf.go:185: local serve path [http://192.168.3.47:6806]
I 2021/02/04 16:48:18 conf.go:189: initialized conf
I 2021/02/04 16:48:18 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/04 16:48:18 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
I 2021/02/04 20:15:12 box.go:274: indexing [45] trees, cpus [8]
D 2021/02/04 20:15:12 box.go:309: indexed box [http://127.0.0.1:6806/siyuan/siyuan/思源笔记用户指南/]
D 2021/02/04 20:15:12 webdav.go:155: opened local box [http://127.0.0.1:6806/siyuan/siyuan/思源笔记用户指南/]
I 2021/02/04 20:31:10 setuilayout.go:43: set ui layout done
I 2021/02/05 14:26:56 working.go:89: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/02/05 14:26:56 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\ellis\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/05 14:26:57 lang.go:67: initialized languages
D 2021/02/05 14:26:57 conf.go:79: loaded conf [C:\Users\ellis\.siyuan\conf.json]
I 2021/02/05 14:26:57 conf.go:186: local serve path [http://192.168.3.47:6806]
I 2021/02/05 14:26:57 conf.go:190: initialized conf
I 2021/02/05 14:26:57 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/02/05 14:26:57 webdav.go:36: initialized WebDAV server
I 2021/02/05 14:26:57 box.go:282: indexing [45] trees, cpus [8]
D 2021/02/05 14:26:58 box.go:277: indexed box [http://127.0.0.1:6806/siyuan/siyuan/思源笔记用户指南/]
I 2021/02/05 14:26:58 conf.go:336: initialized box
I 2021/02/05 14:27:04 repo.go:40: initialized git repo
E 2021/02/05 14:56:04 crypt.go:48: decrypt failed: encoding/hex: invalid byte: U+0075 'u'
I 2021/02/05 14:56:05 box.go:282: indexing [0] trees, cpus [8]
D 2021/02/05 14:56:05 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
D 2021/02/05 14:56:05 webdav.go:103: opened remote box [https://dav.jianguoyun.com/dav/siyuan_notes/]
D 2021/02/05 20:00:09 box.go:363: unindexed box [http://127.0.0.1:6806/siyuan/siyuan/思源笔记用户指南/]
D 2021/02/05 20:00:09 webdav.go:65: closed box [http://127.0.0.1:6806/siyuan/siyuan/思源笔记用户指南/]
D 2021/02/05 20:18:10 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/05 20:18:12 box.go:282: indexing [7] trees, cpus [8]
D 2021/02/05 20:18:12 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
D 2021/02/05 20:18:39 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/05 20:18:42 box.go:282: indexing [7] trees, cpus [8]
D 2021/02/05 20:18:42 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
D 2021/02/05 20:19:24 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
D 2021/02/05 20:19:25 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/05 20:19:25 box.go:282: indexing [2] trees, cpus [8]
D 2021/02/05 20:19:25 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/05 20:19:26 box.go:282: indexing [2] trees, cpus [8]
D 2021/02/05 20:19:26 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
D 2021/02/05 20:19:56 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/05 20:19:56 box.go:282: indexing [2] trees, cpus [8]
D 2021/02/05 20:19:57 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/05 22:10:05 setuilayout.go:43: set ui layout done
D 2021/02/06 15:03:17 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
D 2021/02/06 15:03:20 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
F 2021/02/06 15:03:20 box.go:261: read box [https://dav.jianguoyun.com/dav/siyuan_notes/] doc [/Fleeting Notes/西瓜书/第五章 神经网络.md] failed: 读取笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下的文件 [/Fleeting Notes/西瓜书/第五章 神经网络.md] 失败：ReadStream /Fleeting Notes/西瓜书/第五章 神经网络.md: 503
I 2021/02/06 15:04:40 working.go:89: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/02/06 15:04:40 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\ellis\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 15:04:41 lang.go:67: initialized languages
D 2021/02/06 15:04:41 conf.go:79: loaded conf [C:\Users\ellis\.siyuan\conf.json]
I 2021/02/06 15:04:42 conf.go:186: local serve path [http://192.168.3.47:6806]
I 2021/02/06 15:04:42 conf.go:190: initialized conf
I 2021/02/06 15:04:42 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/02/06 15:04:42 webdav.go:36: initialized WebDAV server
I 2021/02/06 15:04:42 working.go:89: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/02/06 15:04:42 working.go:90: kernel [v0.8.5] is booting, runtime mode is [prod], working directory is [D:\siyuan\resources], temp directory is [C:\Users\ellis\AppData\Local\Temp\siyuan], read only [false], container [standard]
I 2021/02/06 15:04:42 working.go:145: port [6806] is opened, try to check version of running kernel
I 2021/02/06 15:04:42 lang.go:67: initialized languages
D 2021/02/06 15:04:42 conf.go:79: loaded conf [C:\Users\ellis\.siyuan\conf.json]
E 2021/02/06 15:04:42 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 15:04:42 box.go:282: indexing [0] trees, cpus [8]
D 2021/02/06 15:04:42 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/06 15:04:42 conf.go:336: initialized box
I 2021/02/06 15:04:42 repo.go:40: initialized git repo
I 2021/02/06 15:04:42 conf.go:186: local serve path [http://192.168.3.47:6806]
I 2021/02/06 15:04:42 conf.go:190: initialized conf
I 2021/02/06 15:04:42 serve.go:57: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/02/06 15:04:42 serve.go:59: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
E 2021/02/06 15:04:45 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
E 2021/02/06 15:04:51 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 15:07:08 setuilayout.go:43: set ui layout done
D 2021/02/06 15:31:06 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/06 15:31:11 box.go:282: indexing [20] trees, cpus [8]
D 2021/02/06 15:31:11 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
I 2021/02/06 15:37:56 setuilayout.go:43: set ui layout done
E 2021/02/06 16:26:45 box.go:173: 读取笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下的文件 [/Permanent Notes/政治评论/2020-硕-中特.md] 失败：Write /Permanent Notes/政治评论/2020-硕-中特.md: 503
E 2021/02/06 16:26:46 box.go:173: 读取笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下的文件 [/Permanent Notes/政治评论/2020-硕-中特.md] 失败：Write /Permanent Notes/政治评论/2020-硕-中特.md: 503
E 2021/02/06 16:26:48 box.go:173: 读取笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下的文件 [/Permanent Notes/政治评论/2020-硕-中特.md] 失败：Write /Permanent Notes/政治评论/2020-硕-中特.md: 503
D 2021/02/06 16:27:00 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
E 2021/02/06 16:27:00 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 16:27:00 box.go:282: indexing [0] trees, cpus [8]
D 2021/02/06 16:27:00 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
E 2021/02/06 16:27:00 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
D 2021/02/06 16:27:08 box.go:363: unindexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
E 2021/02/06 16:27:08 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 16:27:08 box.go:282: indexing [0] trees, cpus [8]
D 2021/02/06 16:27:08 box.go:277: indexed box [https://dav.jianguoyun.com/dav/siyuan_notes/]
E 2021/02/06 16:27:08 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 16:27:11 setuilayout.go:43: set ui layout done
E 2021/02/06 16:27:16 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 16:27:59 setuilayout.go:43: set ui layout done
E 2021/02/06 16:28:04 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 16:33:11 setuilayout.go:43: set ui layout done
E 2021/02/06 16:33:16 box.go:104: 列出笔记本 [https://dav.jianguoyun.com/dav/siyuan_notes/] 下路径为 [/] 的文件列表失败：ReadDir /: 503 Service Unavailable - PROPFIND /
I 2021/02/06 16:33:21 setuilayout.go:43: set ui layout done

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/1440

**Comment by 88250** [comment]
https://ld246.com/article/1612594530082/comment/1612602834519?r=88250#comments
