### ISSUE TITLE
can't deploy siyuan server with the docker images b3log/siyuan

### ISSUE THREAD

**Issue by jacob11112** [siyuan-note/siyuan#1454]
### Describe the problem
> docker run -v /siyuan/conf:/siyuan/conf -v /siyuan/data:/siyuan/data -p 6806:6806 b3log/siyuan --resident=true --conf=/siyuan/conf

I use this command to run a container,the container will stop immediately.I start it again,but it stop imediately too.
and  then i doubt the problem may be caused by option **-v /siyuan/data:/siyuan/data** 
so then i use **docker run  -d -p 6806:6806 b3log/siyuan --resident=true** ,the containner run normally and i can get in web.but i use **docker exec -it <container_name>  /bin/bash** to modify the config.but it failed.
> OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown

### Expected result
the best is a good image.but it's OK if you give me a brief guide how to build the image

### Version environment

* Version: the latest docker images 
* Operating system: Cent OS8
* Browser (if used):

**Comment by 88250** [comment]
Hello, try `/bin/sh`.

**Comment by jacob11112** [comment]
thanks
