### ISSUE TITLE
支持对其它外部文件的链接

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1456]
### In what scenarios do you need this function?

支持对其它外部文件的链接，可以扩大对知识整理的范围，比如链接代码文件，pdf文件和word文件

### Describe the optimal solution

可以新增思源内部对其它文件格式的支持，或者简单的对其它软件的唤起。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/1440
