### ISSUE TITLE
can't create extra new lines in super blocks

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1467]
### In what scenarios do you need this function?

would be better if we are able to create extra new lines in super blocks

![image](https://user-images.githubusercontent.com/33789516/107213357-f0fc0000-6a10-11eb-9257-322e78287945.png)

**Comment by 88250** [comment]
Hello, I can't reproduce it, could you make a gif/mp4 to show it?

**Comment by eslam-gomaa** [comment]
Hello,

Here you go

![test](https://user-images.githubusercontent.com/33789516/107355998-e6a53900-6ad8-11eb-9242-d7adc011a093.gif)

**Comment by 88250** [comment]
Yes, in the super block we just can create one blank when pressing Enter, thanks for the feedback.
