### ISSUE TITLE
Would be nice to hide the ** & # when rendering

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1473]
### In what scenarios do you need this function?

Would be nice to hide the ** & # when rendering

![image](https://user-images.githubusercontent.com/33789516/107356357-603d2700-6ad9-11eb-89d3-c9d4da66dac0.png)
![image](https://user-images.githubusercontent.com/33789516/107356392-6df2ac80-6ad9-11eb-803d-1d09e7d18cc3.png)

> Typora doesn't show the # of the headlines

![image](https://user-images.githubusercontent.com/33789516/107356486-88c52100-6ad9-11eb-9f38-cd47e56f8544.png)

**Comment by 88250** [comment]
Hi, I think it's a feature of SiYuan, thank you.
