### ISSUE TITLE
Support links to external files in other formats 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1478]
### In what scenarios do you need this function?

Supporting links to external files in other formats can make the knowledge system more complete. 

### Describe the optimal solution

Siyuan can simply call up other applications to open linked files

**Comment by wo4wangle** [comment]
I drag a pdf file to siyuan
and then I ctrl+Left click on the file link in siyuan
the file is finely opened with the default application (福昕pdf)
OS : win10
