### ISSUE TITLE
About newbie-friendliness and mass appeal 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1479]
### In what scenarios do you need this function?

1. The current siyuan is not friendly to novices. Even though some functions are mentioned in the guide, they are still not straightforward enough.

2. Although siyuan's functions are great, the overall experience and UI are more biased towards programmers. The interface and UI are not attractive enough for the public. (But this is just my personal guess, because I like this style very much. )

### Describe the optimal solution

1. Siyuan can use the method of novice guidance similar to the game. When it is used for the first time, users can keep clicking on the next step to understand the use process.

2. Add more icons or graphical operations.

**Comment by 88250** [comment]
Thanks for your advice, but I think User Guide documents are the best way to introduce SiYuan itself. If we can't describe SiYuan in this way, it means the basic functions of SiYuan is not good, it can't bootstrap itself, we need to keep improving.
