### ISSUE TITLE
cannot use shift+right-click on taskbar

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#1490]
### Describe the problem

cannot use shift+right-click on taskbar. It should trigger what alt+space does:
![图片](https://user-images.githubusercontent.com/3153534/107595976-47f01800-6c51-11eb-9c1c-036b06f35852.png)

### Expected result

show the menu when pressed.

### Screenshot or screen recording presentation

as above

### Version environment

* Version: 0.9.5
* Operating system: win 10 x64
* Browser (if used): NA

### Log File

NA

### More information

NA

**Comment by 88250** [comment]
Sorry, maybe we can't do it on Electron frameless window.
