### ISSUE TITLE
Ability to modify highlighting colors

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1498]
### In what scenarios do you need this function?

Need the ability to modify these colors

![image](https://user-images.githubusercontent.com/33789516/107734474-2b61e780-6d06-11eb-82c9-ea2e863f8695.png)

**Comment by 88250** [comment]
Now, we can custom theme in theme.css:

* `--b3-font-colorN`
* `--b3-font-backgroundN`
