### ISSUE TITLE
webdav

### ISSUE THREAD

**Issue by zZ-10** [siyuan-note/siyuan#15]
![image](https://user-images.githubusercontent.com/58500946/93859908-d25ecc00-fcf0-11ea-8bde-525c9107e57c.png)
这个webdav 中的笔记关闭后能不能提供保存啊， 
现在 我点击关闭后，它就没了；
预期效果 :
类似于x-shell gui面板一样，我再次点击这个文件夹会自动链接到webdav，如果我没点记住密码则需要 正确输入密码后才能打开链滴笔记；

**Comment by zZ-10** [comment]
![image](https://user-images.githubusercontent.com/58500946/93860064-105bf000-fcf1-11ea-98de-89eb00342d73.png)
1、链接webdav弹窗面板 打开后， 我点击界面内 弹窗面板外任意地方，都会导致这个弹窗关闭；

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/15#issuecomment-696585915 在 0.2.1 中改进

**Comment by 88250** [comment]
WebDAV 记住密码暂时不实现了，感谢反馈。
