### ISSUE TITLE
内容块引用自动完成列表不消失问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#150]
![issue](https://user-images.githubusercontent.com/873584/94939616-f7c7b300-0504-11eb-892e-1489162bd73e.gif)

中文输入时可以重现。

**Comment by Vanessa219** [comment]
如果此处消失的话， `测试))` 就无法进行搜索。此处交互还需要进一步考虑

**Comment by Vanessa219** [comment]
该格式不符合内容块引用规则，视为搜索内容。不进行修改。
