### ISSUE TITLE
Change siyuan to private folder on Android

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#1516]
### In what scenarios do you need this function?

Note books should be created in Documents folder on Android, the present parent location is `/storage/emulated/0/siyuan/data`, which disobey some principle of Android. 

### Describe the optimal solution

Put app private data in `/storage/emulated/0/Android/data/org.b3log.siyuan` and put the Notebooks in `/storage/emulated/0/Documents/siyuan/`

**Comment by 88250** [comment]
Hi, if we put data in the private-scoped folder, the third-party app can't read it, how to sync via the third-party app?

**Comment by HaujetZhao** [comment]
Then put the sync-needed file with the Notebooks in the `/storage/emulated/0/Documents/siyuan/` folder, just like pictures of Instagram put in the `/storage/emulated/0/Pictures/Instagram/`

**Comment by 88250** [comment]
`Documents` dir is also deprecated from Android 10, so I think we should keep all data to app private dir.

**Comment by HaujetZhao** [comment]
As long as put it in `/storage/emulated/0/Android/data/org.b3log.siyuan` but not `/data/data/org.b3log.siyuan`, file manager apps can still have access to these files and do sync things. 

Probably add a location custom setting, for users who use their own other sync tools.

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/1522

**Comment by saad909** [comment]
there should be option to select custom folder where to store notebooks similar to obsidian app. Only this thing is keeping me from shifting to siyuan from obsidian
