### ISSUE TITLE
Multi-user access in web 

### ISSUE THREAD

**Issue by jacob11112** [siyuan-note/siyuan#1524]
### In what scenarios do you need this function?
**remote connection with  siyuan in VPS**   

### Describe the optimal solution
I hope I can set it in config.json like  jupyter

**Comment by 88250** [comment]
Thanks for your advice, but SiYuan is mainly for personal use, not for collaboration for multiple users.

**Comment by jacob11112** [comment]
Maybe I didn't convey myself clearly.I did't mean collaboration for multiple users. I just mean i hope it can support  different users.
but now i find anothor idea to solve my problem

**Comment by 18651619390** [comment]
> Maybe I didn't convey myself clearly.I did't mean collaboration for multiple users. I just mean i hope it can support different users. but now i find anothor idea to solve my problem

May I ask how you solved it?

**Comment by oromis995** [comment]
> > Maybe I didn't convey myself clearly.I did't mean collaboration for multiple users. I just mean i hope it can support different users. but now i find anothor idea to solve my problem
> 
> May I ask how you solved it?

You can start more than one docker container and assign a different port.
