### ISSUE TITLE
assets文件夹内图片无法拖动

### ISSUE THREAD

**Issue by ishield** [siyuan-note/siyuan#1525]
assets资源文件夹内的图片无法直接拖动到文档中，不同的assets文件夹内的文件也无法拖动移动到其他assets文件夹。

应用场景：大量导入图片到assets文件夹中，然后分别拖动放置到不同的文档的不同位置

**Comment by 88250** [comment]
Thanks for your report.

https://github.com/siyuan-note/siyuan/issues/1440
