### ISSUE TITLE
click is different with double-click 

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#1535]
### In what scenarios do you need this function?
sometimes I open a docment temporarily, just for a glance, or quickly browser the file tree, but I have to close the all the tabs one by one.

### Describe the optimal solution
use click on file tree for "open in current tab", or "open in a temporary tab",  no matter how many times I have clicked on the tree, there is  only one tab be updated and showed on the window.

use double-click on file tree for "open in a new tab", or "open in a long-term tab", every time I couble-click on the tree, a new tab will be generated.

**Comment by Vanessa219** [comment]
You can setting these config:
![image](https://user-images.githubusercontent.com/970828/108305665-79cf2480-71e5-11eb-912f-d5e60be7b583.png)

**Comment by roverway** [comment]
> You can setting these config:
> ![image](https://user-images.githubusercontent.com/970828/108305665-79cf2480-71e5-11eb-912f-d5e60be7b583.png)

That's different, wether a tab is temporary or not is independent of wether it has been modified, some times I want the unmodified tab stay on the window for reference, so I think a new feature will be better: double-click on the tree and open in new tab, click open in current window. 

Users themself will determine which tab will be replace.
