### ISSUE TITLE
快速搜索内容块预览关键词高亮

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#155]
### 当前环境：
- 操作系统： win10
- 思源版本：V0.2.5

### 问题描述：
- 快速搜索仅有搜索条目关键词高亮，没有内容块预览关键词高亮

### 期望的改进：
- 希望加入搜索预览内容块关键词高亮，可以更加快速直观地定位搜索信息

![图片](https://user-images.githubusercontent.com/15924513/94988812-97874e80-05a2-11eb-9a62-9914dbb20522.png)

**Comment by 88250** [comment]
附带再优化一下单击选择，双击打开 @Vanessa219
