### ISSUE TITLE
git sync does not respond 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1552]
### Describe the problem

There is no response to git synchronization, and it always shows that it is synchronizing. Version management was closed before this. 

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/47321059/108252436-9b072500-7193-11eb-9e5c-49bd2d2b177b.png)

### Version environment

* Version: 0.9.9
* Operating system: win10
* Browser (if used): 

### Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5997921/siyuan.log)

**Comment by 88250** [comment]
Hello, the problem caused by the git commit has been disabled: 

> repo.go:34: git repo has been disabled

Please set git commit interval more than 0 if you want to use SiYuan sync, thanks.

**Comment by dejavudwh** [comment]
Yes, but I have turned on version management before synchronization. I just reset version management. The log shows:
` I 2021/02/18 10:37:02 repo.go:41: initialized git repo`
but It was not displayed when I set it up yesterday, there may be a problem here.

**Comment by 88250** [comment]
Please try:

1. Remove .git
2. Kill kernel process
3. Restart SiYuan
