### ISSUE TITLE
Save the browsing location before exiting

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1554]
### In what scenarios do you need this function?

Save the browsing position before exiting. When I reopen siyuan, I can return to the original browsing position instead of the file header

**Comment by 88250** [comment]
It's nice advice, but we can't implement it at present, remains it in the open status.

**Comment by 88250** [comment]
We will not consider supporting it in the short term. We will consider it later when there are more needs. Thank you.
