### ISSUE TITLE
[feature suggestion] separate todo feature

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#1557]
### In what scenarios do you need this function?

strengthen todo feature (could be a separate feature)

### Describe the optimal solution

separate todo feature that is on par with plain tasks, and then implement siyuan-specific features

### Describe the candidate solution

1. implement something like https://github.com/aziz/PlainTasks or https://github.com/fabiospampinato/vscode-todo-plus
2. think of connections between current siyuan and the todo feature

**Comment by 88250** [comment]
Hello, please describe some details of the task list you want, thank you.
