### ISSUE TITLE
（待定）提供 1 个月时长的订阅试用

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1558]
订阅试用的主要是云端服务，考虑两个选择：

* 提供试用期或者
* 永久免费 16M

**Comment by luckept** [comment]
支持试用，试用的方案看着更大气😎

**Comment by 88250** [comment]
暂时不考虑了，先结束推荐码机制吧。

**Comment by 88250** [comment]
后续请关注 https://github.com/siyuan-note/siyuan/issues/4186
