### ISSUE TITLE
Emoji and bold format together will cause input problems

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1559]
### Describe the problem

Emoji and bold format together will cause input problems，and emoji may have other problems. #1555 

### Screenshot or screen recording presentation

![s](https://user-images.githubusercontent.com/47321059/108341018-30e29480-7214-11eb-986c-3ddcf799f942.gif)

### Version environment

* Version: 0.9.9
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
Thanks for your feedback, merge this issue into https://github.com/siyuan-note/siyuan/issues/1555
