### ISSUE TITLE
Clear git history

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1560]
### In what scenarios do you need this function?

When using third-party synchronization tools, current popular synchronization tools cannot ignore the specified file, so the .git file may sometimes be too large (for example, some pdf are added), so the optional function of deleting git history should be added, such as automatically delete the synchronized history.

**Comment by 88250** [comment]
I think we can delete .git folder manually.

**Comment by dejavudwh** [comment]
Okay, I agree, it is very simple.

**Comment by 88250** [comment]
Thank you.
