### ISSUE TITLE
sidebar covers the emoji floating bar

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1568]
### Describe the problem

The sidebar covers the emoji floating bar, but the other floating bars display normally. 

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/47321059/108400091-cc482980-7255-11eb-95e0-8f10d1461528.png)
![image](https://user-images.githubusercontent.com/47321059/108400242-f4378d00-7255-11eb-975f-d29c611eb583.png)

### Version environment

* Version: 1.0.0
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
This is fixed in recent versions, thanks.
