### ISSUE TITLE
add code::before notation

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#1575]
### In what scenarios do you need this function?

the community theme blue topaz has a feature of language notation for code blocks, check [here](https://github.com/whyt-byte/Blue_Topaz_for_Siyuan_Light/blob/main/theme.css), start from line 514.

the implementation is a little cumbersome: each of the languages needs to be covered.

### Describe the optimal solution

Is it possible to have it integrated, so in CSS we only need to adjust the style?

### Describe the candidate solution

keep as it is.

### Other information

NA

**Comment by 88250** [comment]
I'm not sure about it, please check it after v1.2.0 released, thanks.
