### ISSUE TITLE
多个脚注显示异常

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#158]
### 当前环境：
- 操作系统： win10
- 思源版本：V0.2.5

### 问题描述
使用多个脚注时无法正常显示，如图：
![多个脚注显示异常](https://user-images.githubusercontent.com/15924513/94991818-133fc600-05b8-11eb-8329-549adede7954.gif)

源文件： 

[LYT(Linking Your Thinking).zip](https://github.com/siyuan-note/siyuan/files/5321640/LYT.Linking.Your.Thinking.zip)

**Comment by 88250** [comment]
感谢反馈，目前有三种元素的细节处理有问题：

* 链接引用
* 脚注
* ToC

具体改进请关注 https://github.com/siyuan-note/siyuan/issues/49。
