### ISSUE TITLE
Support dock panel dragging

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1580]
### In what scenarios do you need this function?

More freedom in layout 

### Describe the optimal solution

Support dragging the sidebar to change the position 

![image](https://user-images.githubusercontent.com/47321059/108510552-a2e0d980-72f9-11eb-9a8d-d76383348b1a.png)

**Comment by Vanessa219** [comment]
Now I’m going to do an exciting widget block, this is going to be later.

**Comment by dejavudwh** [comment]
Well, I just happened to think of it, so I opened an Issue first. 感谢！加油！

**Comment by Vanessa219** [comment]
跨度太大，拖拽也麻烦，现在加了提示 🤦‍♀️
![image](https://user-images.githubusercontent.com/970828/124058829-b268ef80-da5c-11eb-8021-883f99851ef7.png)
