### ISSUE TITLE
Which one is correct?

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#1586]
I think #1 have to be bold.

1. **test test(test test)**test test
2. **test test(test test)** test test

![Kapture 2021-02-19 at 16 41 47](https://user-images.githubusercontent.com/15811943/108569970-78c7f100-72d2-11eb-879d-cbc71178356d.gif)

**Comment by 88250** [comment]
In fact, it is not, and so is GitHub:

![image](https://user-images.githubusercontent.com/873584/108579001-f84fd180-735f-11eb-8789-c356bea8fdd0.png)
