### ISSUE TITLE
标签页签与书签页签内容块预览

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#159]
### 当前环境：
- 操作系统： win10
- 思源版本：V0.2.5

### 场景描述
文档里添加了很多标签和书签，如果需要查看详情，则需要打开文档。在查看过程中，会打开很多中间文档，但是这些文档查看过后又要一一关闭。

### 期望的改进
标签列表和书签列表能够内容预览，减小直接打开文档查看的频率

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/94993371-27d58b80-05c3-11eb-9b1d-a35aa99dcd29.png)

打算和反链页签一样，移到块标识上进行预览。

**Comment by lss6378** [comment]
- 预览建议使用统一的形式，和内容块预览类似，触发预览后，可以查看上下文
- 统一的预览形式在操作上会比较轻松，没有负担
![图片](https://user-images.githubusercontent.com/15924513/94994858-ec3fbf00-05cc-11eb-9cce-ca981768f720.png)

**Comment by 88250** [comment]
嗯，我也是这样想的，可以实现反链页签上面的预览功能。
