### ISSUE TITLE
Showing the forward/back-links on the graph view

### ISSUE THREAD

**Issue by ezzaouia** [siyuan-note/siyuan#1595]
![forward:back-links](https://user-images.githubusercontent.com/6187174/108589634-87101e80-735f-11eb-96a6-df178efeff0d.png)

**Comment by 88250** [comment]
The global graph is document-level for summary central, thanks.

**Comment by 88250** [comment]
The local graph is block-level:

![image](https://user-images.githubusercontent.com/873584/108598778-a1331680-73ca-11eb-8839-c8e02af3d51a.png)
