### ISSUE TITLE
Allow creating  a new doc (in the current folder) from a forward link if it does not exist yet, e.g., using cmd+click on link 

### ISSUE THREAD

**Issue by ezzaouia** [siyuan-note/siyuan#1599]
![whitesspaces2](https://user-images.githubusercontent.com/6187174/108593129-4241b300-7372-11eb-894a-4734b8e50782.png)

**Comment by 88250** [comment]
The doc creation menu is in `((` auto-completion list, or you can select text and create in the right-click menu, thanks.
