### ISSUE TITLE
内嵌内容块预览问题

### ISSUE THREAD

**Issue by heshang233** [siyuan-note/siyuan#16]
以用户指南为例：
修改`快速上手`的标题级别，让其在`内容块`的大标题下面
编辑模式下能看到完整信息
![image](https://user-images.githubusercontent.com/13328402/94106078-3a3a2180-fe6d-11ea-8310-5d6327f275a6.png)

而预览模式下内容块信息被截取，展示如下
![image](https://user-images.githubusercontent.com/13328402/94106095-445c2000-fe6d-11ea-8d3d-56bac30ad780.png)

怀疑与`有序列表块`有关系，测试发现预览时从第一个`有序列表块`或`块引用快`开始展示

**Comment by heshang233** [comment]
导出和预览一样也有同样问题。

**Comment by 88250** [comment]
感谢反馈，v0.2.2 修复。
