### ISSUE TITLE
增加底部状态栏，快捷添加标签，自定义笔记/文件夹排序，附件查看及管理，显示 MD 源码，加密笔记

### ISSUE THREAD

**Issue by SylleoYr** [siyuan-note/siyuan#160]
似乎发现了新大陆（思源笔记 :tada:）？一直在找这么一个笔记，能够以纯文本存储，但又能很好的支持笔记甚至个人知识库管理的软件，试过 QOWn、Cherrytree、为知等，都不是很满意，目前在用 VNote，但发现思源时让我一眼相中，尤其是块级引用和双向链接，完整的 MD 支持和扩展 MD 语法支持，基于 Git 的版本管理。

在试用 v0.25 的过程中，还有几个个人感觉不够方便的地方，希望能够在后期增加：

- 表格只有三行三列，不知道怎么增减行列；
- 增加底部状态栏显示，用来统计当前笔记字词数，显示/编辑标签等；
- 标签管理功能有点弱，并且添加只能通过 `##` 的形式，希望能够增加快捷输入标签的功能（对于笔记等的标签，相当于给笔记文件打 Tag），文中可通过 `##` 引用标签；
- 笔记和文件夹的自定义排序功能；
- 附件查看和管理能力较弱，目前是通过 `[]()` 的形式作为链接插入文中的，希望能够有一个单独的附件管理窗格，支持调用默认程序打开附件；
- 能够在编辑界面一键切换 MD 源码和即时渲染的编辑界面（可能有但我没发现:joy:）；
- 支持加密笔记（加密笔记本，单独加密某个笔记）

（感觉有点像把 VNote 的一些功能拿过来了，仅作建议，仅供参考，谢谢！:wink:）

**Comment by 88250** [comment]
感谢反馈 🙏 

* 表格编辑优化请关注 https://github.com/siyuan-note/siyuan/issues/39
* 状态栏目前暂时没有计划，等再收集一些需求
* 标签的自动完请关注 https://github.com/siyuan-note/siyuan/issues/161
* 文件树排序、移动等请关注 https://github.com/siyuan-note/siyuan/issues/12
* 资源文件在 assets 文件夹下，相关优化请关注 https://github.com/siyuan-note/siyuan/issues/120 https://github.com/siyuan-note/siyuan/issues/110
* 编辑器“源码模式”暂时没有计划提供，可以先用其他文本编辑器顶顶 😂 
* 初始化的时候已经自动生成密钥对（用于[数据同步](https://github.com/siyuan-note/siyuan/milestone/5)），加密功能应该会基于这个来做，不过暂时没有计划，等再收集一些需求

我们目前正在做 [v0.2.6](https://github.com/siyuan-note/siyuan/milestone/4)，主要特性是支持浏览器上直接使用，这个版本里会发布 Docker 镜像，如果是程序员用户的话可以自己折腾一下部署在服务器上用，支持移动端浏览器使用。后续等我们这边的官方数据同步功能上线以后，懒得折腾的用户就可以直接多端使用了。

再次感谢老铁的反馈建议，我们会继续努力的！

**Comment by SylleoYr** [comment]
哇，之前没注意到邮件，:joy:

希望 docker 能支持反代在非根目录下，也就是 `xxx.com/siyuan/` 这种（资源引用，e.g. CSS等，采用相对路径，而非根路径）

**Comment by 88250** [comment]
NGINX 的话配置一下 location 应该就能解决 😄

**Comment by SylleoYr** [comment]
> 
> 
> NGINX 的话配置一下 location 应该就能解决 😄

但如果页面资源采用 `/a.css` 这种方式引用的话，浏览器就会向 `xxx.com/a.css` 发起请求。

**Comment by 88250** [comment]
加上这个 kernel 启动参数试试 `--servePath=xxx.com/siyuan`

**Comment by SylleoYr** [comment]
嗯嗯，谢谢，不过目前我用的是 Caddy，我回去再研究研究 😂
