### ISSUE TITLE
mentions show unrelated content 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1602]
### Describe the problem

1. mentions show unrelated content 
2. When I cut the content in the displayed document and then pasted it, the mention disappeared. 
3. Only this document has this problem, the others are normal. 
4. I cannot reproduce it for now. 

### Version environment

* Version: 1.0.0
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
Thanks, I close it.
