### ISSUE TITLE
Clicking on the appearance settings will jump back to the default theme

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1603]
### Describe the problem

1. When I click the appearance setting (the current theme is customized), it will jump back to the default theme.
2. It appears two or three times, but it can't be reproduced. Sometimes it can work. 

![image](https://user-images.githubusercontent.com/47321059/108596284-f832ee80-73be-11eb-8b3c-122a428336f5.png)

### Version environment

* Version: 1.0.0
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
I am not sure it is a bug, please help us to find steps to reproduce. Close this at present.

**Comment by dejavudwh** [comment]
Okay, I will try to reproduce it.
