### ISSUE TITLE
Open two notebook, bookmark can not work

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1618]
### Describe the problem

The bookmark feature still has an unknown bug!

1. Sometimes it takes twice to delete, and the content block bookmark also has a very strange bug! (For example, the bookmark cannot be deleted and the current one will become other content blocks after deleting the current one) (first gif)

2. The first bookmark added will not be displayed, and it will only be displayed after adding the second bookmark. (Second gif)

The bug in the content block cannot be reproduced now, and the bookmark feature may have a serious bug! 

### Screenshot or screen recording presentation

![s1](https://user-images.githubusercontent.com/47321059/108621108-a09e8c80-746b-11eb-939d-f734afeab06b.gif)
![s2](https://user-images.githubusercontent.com/47321059/108621109-a1cfb980-746b-11eb-9ebb-f288c8ea4dae.gif)

### Version environment

* Version: 1.0.2
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
Please check v1.0.3 whether can reproduce it, thank you.

**Comment by dejavudwh** [comment]
There are still big problems, as shown in my new screenshot below. 

![s2](https://user-images.githubusercontent.com/47321059/108796705-541a9480-75c4-11eb-875d-de81778773af.gif)

**Comment by Vanessa219** [comment]
Please check v1.0.9 whether can reproduce it, thank you.

**Comment by 88250** [comment]
If you find any issue with it, please let us know, thanks.
