### ISSUE TITLE
Delete bookmarks directly in the bookmarks panel

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1619]
### Describe the optimal solution

Delete the bookmark directly in the bookmark bar, without finding the file or content block to delete it. 

![image](https://user-images.githubusercontent.com/47321059/108621307-de4fe500-746c-11eb-9215-56ef7c8efdb0.png)

**Comment by 88250** [comment]
Please check v1.0.3 whether can reproduce it, thank you.

**Comment by dejavudwh** [comment]
Sorry, there may be a problem with my statements. This issue is for a feature, which means that you don't need to find each bookmarked document to delete it. Instead, you can delete it directly in the bookmark bar.

**Comment by 88250** [comment]
We have added this delete entry in a previous version, please confirm whether it is the same as you need, thank you.

![image](https://user-images.githubusercontent.com/873584/111914790-7a8dfb80-8aae-11eb-9054-c32907d7b75f.png)
