### ISSUE TITLE
Backspace at front of Heading will cause the heading to convert as a normal text

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1620]
### Describe the problem

Format bug when deleting to the previous line

### Screenshot or screen recording presentation

![s1](https://user-images.githubusercontent.com/47321059/108621653-ed379700-746e-11eb-86fc-43be5462c68c.gif)

### Version environment

* Version: 1.0.2
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
Improved in v1.2.0, thanks.
