### ISSUE TITLE
输入账号密码后，点击“登录”没有反应

### ISSUE THREAD

**Issue by JingchengLi** [siyuan-note/siyuan#1621]
### Describe the problem
![image](https://user-images.githubusercontent.com/5918144/108622013-2cff7e00-7471-11eb-8836-c20afaa8c0d3.png)
已经购买了早鸟的高级版，
输入账号密码后，点击“登录”没有反应，无法登录。
用的MAC pro，
0.98
0.99
1.00
1.02
在这些版本均存在这个问题。

### Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
你好，这个应该是网络问题，请关闭 VPN 等代理软件（如果有开启的话）。另外，可以试下用手机网络看看。

我先关闭，如果还有问题请跟帖反馈，谢谢。
