### ISSUE TITLE
Cancel the code block language list by clicking elsewhere

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1627]
### In what scenarios do you need this function?

When selecting the code block language, you must select to cancel the floating box. But sometimes the code block does not support certain languages, so you need not select any options. 

### Describe the optimal solution

![image](https://user-images.githubusercontent.com/47321059/108625496-334c2500-7486-11eb-8b50-afe4bab1767a.png)

**Comment by Vanessa219** [comment]
Pls press `esc`
