### ISSUE TITLE
cpu 100% on MacBookPro M1

### ISSUE THREAD

**Issue by MistRay** [siyuan-note/siyuan#1630]
### Describe the problem
After a period of use, than program display shows disconnection from the kernel and the cpu is 100%
![image](https://user-images.githubusercontent.com/34370155/108629959-5930f400-749d-11eb-869d-6630244c6d47.png)

### Version environment

* Version: 1.0.2
* Operating system: macOS BigSur 11.0.1
* Browser (if used):

**Comment by 88250** [comment]
Could you help us to test whether reproduce it with the same dataset on Windows?

**Comment by MistRay** [comment]
Yes,It cannot be reproduced on windows.(V1.0.5)
This problem may be caused by Apple Silicon.

**Comment by 88250** [comment]
Thanks, we will release Apple universal package in #713

**Comment by 88250** [comment]
Please try the latest arm64 dmg for macOS, thanks.
