### ISSUE TITLE
Type filtering when adding references 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1631]
### In what scenarios do you need this function?

When adding a reference, if you query all content that contains keywords, it is not easy to select quickly and may reduce performance. 

### Describe the optimal solution

such as:
`((p` only display all pages that can be referenced.
`((b` only displays all blocks that can be referenced.

**Comment by 88250** [comment]
Please refer to type filtering already existing, like `((d` for doc block.

**Comment by toyluck** [comment]
试验了下好像不可以， 最新版本 1.2 

https://user-images.githubusercontent.com/13290492/111299944-80897400-868b-11eb-83c3-b6aed373c9ba.mov

**Comment by 88250** [comment]
@toyluck `((d:文档名`
