### ISSUE TITLE
Reference .text cannot be modified after clicking to move the cursor to the desired position 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1634]
### Describe the problem

Reference .text cannot be modified after clicking to move the cursor to the desired position, because they will jump directly after clicking them. 

### Screenshot or screen recording presentation

![s4](https://user-images.githubusercontent.com/47321059/108738220-5b16b800-756e-11eb-95fb-be06e90eb794.gif)

### Version environment

* Version: 1.0.2
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
Maybe this had been fixed in recent versions, please check it, thanks.
