### ISSUE TITLE
Reference link preview block does not disappear 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1635]
### Describe the problem

The reference link preview block will not disappear after I perform other operations. 

### Screenshot or screen recording presentation

![s5](https://user-images.githubusercontent.com/47321059/108739311-7d5d0580-756f-11eb-81c4-dcbf99875fce.gif)

### Version environment

* Version: 1.0.2
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
Please try the latest version, thanks.
