### ISSUE TITLE
Optimization of the operation of custom themes in the settings 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1637]
### In what scenarios do you need this function?

The operation of the custom theme in the setting has a serious delay and needs to be pulled down in a large range, which affects other operations. 

![image](https://user-images.githubusercontent.com/47321059/108747263-34f61580-7578-11eb-8218-05a275ffa55b.png)

### Describe the optimal solution

Use a separate drop-down box or panel.

**Comment by 88250** [comment]
There is no improvement plan, thanks for the suggestion.
