### ISSUE TITLE
新版本下载覆盖老版本发现无法打开思源笔记软件了

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#164]
![image](https://user-images.githubusercontent.com/29135984/95035336-63717200-06f7-11eb-8db5-25a1a394ca45.png)

**Comment by 88250** [comment]
请尝试杀掉进程后重新启动。

**Comment by 88250** [comment]
你好，请下载最新版重新安装试试，谢谢。

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/95280117-de1cc780-0886-11eb-9e5f-df1de7a5a8b9.png)
windows不信任它哦

**Comment by 88250** [comment]
加入到信任里吧。
