### ISSUE TITLE
File Tree cannot be refreshed automatically

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#1640]
### Describe the problem

when i change the file's name or create a new file the **File Tree** cannot be refreshed automatically

### Expected result

File Tree refreshing automatically

### Screenshot or screen recording presentation

![autorefresh](https://user-images.githubusercontent.com/18739609/108796391-a1e2cd00-75c3-11eb-972f-ebc46e4184b3.gif)

### Version environment

* Version: Current version v1.0.3 / Kernel v1.0.3
* Operating system: Win10
* Browser (if used): no

### Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/6026472/siyuan.log)

### More information

reinstall or install older(1.0,1.01) version cannot solve the problem

**Comment by 88250** [comment]
Hello, can you send the whole nootebook.zip to 845765@qq.com?

**Comment by banjuer** [comment]
> Hello, can you send the whole nootebook.zip to [845765@qq.com](mailto:845765@qq.com)?

The whole notebook is too big to be sent by email, and I have prepared a download link that has been sent to you

**Comment by q292338634** [comment]
新建或删除都会有这个问题
