### ISSUE TITLE
Error parsing template variable '{{.id}}'

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1647]
### Describe the problem
Error parsing template variable  '{{.id}}'

### Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/37007969/108850001-c9ff1a00-761d-11eb-9e91-779694831bf4.png)

### Version environment

* Version: 1.0.4
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
Fixed in https://github.com/siyuan-note/siyuan/issues/1648, thanks.
