### ISSUE TITLE
Assets name retain scores and underscores

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1661]
### Describe the problem

When uploading an attachment --> spaces, scores and underscores get removed from the name

![image](https://user-images.githubusercontent.com/33789516/108983221-4da91d00-7697-11eb-910c-4e59209dd8eb.png)

After Upload
![image](https://user-images.githubusercontent.com/33789516/108983270-5863b200-7697-11eb-9c6f-213ccf4e7a72.png)

### Expected result

Preserving the name displayed as the original

![image](https://user-images.githubusercontent.com/33789516/108983320-69acbe80-7697-11eb-8052-8f6873b36c9f.png)

**Comment by 88250** [comment]
Spaces will be removed, `_` and `-` should be retained.

**Comment by eslam-gomaa** [comment]
would the spaces  be replaced with "_" for example ?

**Comment by eslam-gomaa** [comment]
> Spaces will be removed, `_` and `-` should be retained.

would the spaces be replaced with "_" for example ?

**Comment by 88250** [comment]
@eslam-gomaa Ok, we will try.
