### ISSUE TITLE
Add css class for special folders (e.g. templates)

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#1664]
### In what scenarios do you need this function?

For theme customization. Currently, the templates folder's icon has specified style of `color=var(--b3-theme-primary)`.

### Describe the optimal solution

add css class for special folders (e.g. templates)

### Describe the candidate solution

NA

**Comment by Vanessa219** [comment]
这样试试
```
.file-tree li[data-name="assets"] {
    color: red;
}
```
