### ISSUE TITLE
query content block failed

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1666]
### Describe the problem

When adding a note to the task list item, it shows that the query content block failed. The other blocks are normal. 

Same problem in naming and aliasing.

![image](https://user-images.githubusercontent.com/47321059/109037056-3dc82200-7705-11eb-9544-ae828c180e7b.png)

![image](https://user-images.githubusercontent.com/47321059/109037175-65b78580-7705-11eb-8655-180cb59c338b.png)

### Version environment

* Version: 1.0.5
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
It may be fixed in recent versions, please help us check it, thanks.
