### ISSUE TITLE
Support batch setting block properties

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1667]
### In what scenarios do you need this function?

When performing SQL queries, you need to use naming or remarks, but now can only operate on a single content block. 

### Describe the optimal solution

Support batch setting of naming, alias and remarks. (There should be a lot of room for optimization in the operation of the content block.)

**Comment by 88250** [comment]
The idea of bulk operation on blocks is cool, but there are some challenges in interaction design, do you have any advice?

**Comment by dejavudwh** [comment]
I think we can learn from the operation of Windows batch selection of files: hold down the `shift` key, and then click multiple blocks with the mouse.
Or, you can place an option box in front of each block, and the user can click the option boxes of multiple blocks. When setting block properties, Siyuan can traverse all the selected boxes to set the properties.

**Comment by dejavudwh** [comment]
![32](https://user-images.githubusercontent.com/47321059/109996024-c9ffc800-7d49-11eb-8a96-5f30d10a2a4c.gif)

**Comment by 88250** [comment]
Merged into https://github.com/siyuan-note/siyuan/issues/1719
