### ISSUE TITLE
Code block that copied from elsewhere format bug 

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1672]
### Describe the problem

in vscode:
![image](https://user-images.githubusercontent.com/47321059/109117255-b7e7bd80-777c-11eb-9b22-a16c64e52bb7.png)

in siyuan:
![image](https://user-images.githubusercontent.com/47321059/109117297-c33ae900-777c-11eb-98dc-5ccad03a25d4.png)

### Version environment

* Version: 1.0.5
* Operating system: win10 
* Browser (if used):

**Comment by 88250** [comment]
Please use <kbd>Ctrl+Shift+v</kbd> to copy code, thanks.
