### ISSUE TITLE
支持查看和删除云端图床资源文件

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1674]
该功能仅在云端提供 [链滴 - 设置 - 文件 - 笔记端](https://ld246.com/settings/file?type=3)。

**Comment by LIETIAN183** [comment]
这个云端图床是怎么使用的？

**Comment by 88250** [comment]
@LIETIAN183 文档 `...` 菜单中有个上传资源文件到云端

**Comment by LIETIAN183** [comment]
> @LIETIAN183 文档 `...` 菜单中有个上传资源文件到云端

找到了，谢谢了，但是上传了之后怎么获得图床的URL，我尝试导出也不会自动转换图片链接
我看你写支持查看和删除云端图床资源文件，怎么操作

**Comment by 88250** [comment]
@LIETIAN183 这个是待开发的特性，目前还不支持直接查看和删除，目前上传到云端图床主要是提供给复制到知乎、语雀等平台时使用。

**Comment by LIETIAN183** [comment]
@88250 OK，获得图床中图片的 URL 也是需要后续开发是吗，我明白了

**Comment by jiangbaiyan** [comment]
> @LIETIAN183 这个是待开发的特性，目前还不支持直接查看和删除，目前上传到云端图床主要是提供给复制到知乎、语雀等平台时使用。

复制到其他平台后，图片URL仍然是本地路径，无法使用云端图床

**Comment by 88250** [comment]
@jiangbaiyan 要从预览模式复制。
