### ISSUE TITLE
Add template var `{{.alias}}` for doc

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1675]
### In what scenarios do you need this function?
When querying the content block that contains the current document alias

**Comment by 88250** [comment]
By the way, also add the other two variables  `{{.name}}` and `{{.memo}}`.

**Comment by zhangjl-sjtu** [comment]
dynamic content block queries do not seem to support determining whether a variable is empty?

**Comment by 88250** [comment]
Try `xxx != ''` in SQL.
