### ISSUE TITLE
Insert a node in mindmap should begin with level 2 title

### ISSUE THREAD

**Issue by zhangjl-sjtu** [siyuan-note/siyuan#1683]
### Describe the problem
Press 'Enter' or 'TAB' to insert a node in mindmap should begin with level 2 title rather than plain text.
And then the L3 title, L4 title

### Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/37007969/109187553-f7d69100-77cc-11eb-8ab2-af93621d3803.png)
![image](https://user-images.githubusercontent.com/37007969/109187617-07ee7080-77cd-11eb-81e7-fbddeb35d1de.png)

### Version environment

* Version: 1.0.5
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
I think keeping the plain text type is correct. If the user wants to insert sub nodes, should use a container block.
