### ISSUE TITLE
Apple Silicon version fails to open

### ISSUE THREAD

**Issue by wizyoung** [siyuan-note/siyuan#1691]
### Describe the problem

The latest V1.0.7 build for apple silicon fails to open.

When I first clicked to open it, it said "The file is damaged and cannot be opened". So I typed "sudo xattr -d com.apple.quarantine /Applications/SiYuan.app" and reopened it. But this time the M like logo on the startup page just spinned and failed to open.

### Expected result

Open normally.

### Screenshot or screen recording presentation

<img width="1156" alt="iShot2021-02-27 00 32 03" src="https://user-images.githubusercontent.com/13296106/109327415-464e6300-7893-11eb-9198-2ea3d4f98b69.png">

### Version environment

* Version: V1.0.7
* Operating system: macOS 11.2.2 on M1 chip
* Browser (if used): Not used

### Log File
[siyuan.log](https://github.com/siyuan-note/siyuan/files/6051036/siyuan.log)

### More information

The error message on the system console app about SiYuan Helper (GPU) is:
`Failed to get cache main folder: failed to lookup DARWIN_USER_CACHE_DIR err:5`

**Comment by MistRay** [comment]
I had the same problem

**Comment by 88250** [comment]
Sorry, we don't have a real machine for testing, please help us to test this installation package again, thank you.

https://github.com/siyuan-note/siyuan/releases/download/v1.0.7/siyuan-1.0.7-mac-arm64.dmg

**Comment by wizyoung** [comment]
Yes, this version works like a charm now! The startup time is way much faster than intel version and the kernal-darwin process has a very low CPU usage (around 0.3% in the Monitor.app). Thanks very much!

But it still shows "File is damaged and cannot be opened" and I need to type "sudo xattr -d com.apple.quarantine /Applications/SiYuan.app" to solve this. Maybe a certificate or something is needed for the macOS system to trust SiYuan.app?

**Comment by 88250** [comment]
@wizyoung We did not buy the Apple certificate, maybe we will buy it in the future, thank you.
