### ISSUE TITLE
Improve asset file name link text

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1692]
### In what scenarios do you need this function?

Hello, 

Many thanks for responding to my request to keep the file name, but I meant the displayed file name not the file itself, so would be great to keep the displayed name as the file name (in assets)

![image](https://user-images.githubusercontent.com/33789516/109332150-66b3f880-7866-11eb-8ee3-e8b5c05fbbd1.png)

Thank you in advance

**Comment by 88250** [comment]
Thanks, we will improve it in v1.0.8.
