### ISSUE TITLE
page white spaces are removed when changing the theme from light to dark and vise versa

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1693]
### Describe the problem

page white spaces are removed when changing the theme from light to dark and vise versa

> before
![image](https://user-images.githubusercontent.com/33789516/109332356-a8dd3a00-7866-11eb-95f2-7bebabc63f0d.png)

> After changing the appearance from light to dark

![image](https://user-images.githubusercontent.com/33789516/109332441-c7433580-7866-11eb-9289-e1aa582fee46.png)

**Comment by 88250** [comment]
Fix in v1.2.0.
