### ISSUE TITLE
Spell check feature for notes

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1694]
### In what scenarios do you need this function?

I noticed that there is a spell check feature for notes names, but it would  be very good to have this feature for notes

![image](https://user-images.githubusercontent.com/33789516/109332617-04a7c300-7867-11eb-9758-c354cb256e26.png)

**Comment by 88250** [comment]
Merge into https://github.com/siyuan-note/siyuan/issues/597, thanks.
