### ISSUE TITLE
内容块嵌入编辑

### ISSUE THREAD

**Issue by steveyang331** [siyuan-note/siyuan#17]
什么时候可以支持 block embed ？也就是可以编辑嵌入的block，同步到原block，而不仅仅是预览block ref的内容。
直接可以编辑嵌入的block，更方便，不然要跳转打开多窗口页面，还要鼠标放在上面去预览。有点麻烦。

**Comment by 88250** [comment]
在计划中，只是目前还需要考虑交互，因为编辑嵌入的块可能会生成新块，新块如何处理是个问题。

**Comment by steveyang331** [comment]
好的！ 
另外，如果实现了block embed，接下来可实现 block ref 转换成 block embed，或者其他格式，text格式等。

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/94260804-62a44780-ff63-11ea-81f6-e4136e93cd31.png)
block embed 视频置入方式还有更好的方式嘛？（视频上方的代码不鞥自动隐藏）似乎帮助里的只能显示链接
![image](https://user-images.githubusercontent.com/29135984/94261042-caf32900-ff63-11ea-9961-d91e6b2f90fb.png)

**Comment by 88250** [comment]
感谢老铁的提议，v0.4.6 将引入悬浮预览编辑，欢迎来体验。
