### ISSUE TITLE
Support note box

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1701]
### In what scenarios do you need this function?

There are different implementations for note boxes out there, and it's going to be a nice feature to have in siyuan

## Examples

---

![image](https://user-images.githubusercontent.com/33789516/109381294-3dd14900-78e2-11eb-8ff2-c6419ee57815.png)

---

![image](https://user-images.githubusercontent.com/33789516/109381362-b20bec80-78e2-11eb-9c05-5109ef53f510.png)

![image](https://user-images.githubusercontent.com/33789516/109381367-b932fa80-78e2-11eb-905d-372193756aec.png)

![image](https://user-images.githubusercontent.com/33789516/109381374-c64fe980-78e2-11eb-9b07-eab5d9df06e8.png)

![image](https://user-images.githubusercontent.com/33789516/109381413-0c0cb200-78e3-11eb-93c7-2a93ba8ec265.png)

**Comment by 88250** [comment]
How about setting block background-color?

**Comment by eslam-gomaa** [comment]
If you mean this looks nice to me 

![image](https://user-images.githubusercontent.com/33789516/109385218-ea1f2980-78fa-11eb-89e0-49028fad36a1.png)

**Comment by 88250** [comment]
I close this, thanks.
