### ISSUE TITLE
Add breadcrumbs Bar

### ISSUE THREAD

**Issue by scvoet** [siyuan-note/siyuan#1704]
### In what scenarios do you need this function?

Quickly see the subordination of the text I am editing.

### Describe the optimal solution

add a bar like VsCode

![图片](https://user-images.githubusercontent.com/45708948/109389720-80c60780-7948-11eb-9add-e595bfd5e588.png)

**Comment by 88250** [comment]
Merge into https://github.com/siyuan-note/siyuan/issues/1231 thanks.
