### ISSUE TITLE
Support custom block attributes

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1719]
### In what scenarios do you need this function?

For example, I am writing a TODO. I will note `finished` for all finished TODOs, and I will note `unfinished` for all unfinished TODOs, and then use SQL to query and display them by category. 

### Describe the optimal solution

Add the default memo(or naming and aliases), such as the example above.

I think this feature and #1667  are both able to enhance the user experience very well.

**Comment by 88250** [comment]
Do you mean we should open customing block properties for users?

**Comment by dejavudwh** [comment]
I mean to add the default block properties (memo, name, and alias), it would be best if users could customize it.

**Comment by 88250** [comment]
Thanks, just as a long-term plan, we will keep thinking about it.
