### ISSUE TITLE
Complex sql parsing problems

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#1727]
### Describe the problem

i want to use complex sql to implement dynamic query, but didn't get the expected results.

* **my purpose:** dynamically query tasks that were completed last month

* **query sql:**
```sql
select  *
from blocks
where type='i' and path = '/work.md' and markdown like '%[x]%'
and (
    created between(SELECT strftime('%Y%m%d',date('now','start of month','-1 month'))) and (SELECT strftime('%Y%m%d',date('now','start of month','-1 day')))
        or updated between(SELECT strftime('%Y%m%d',date('now','start of month','-1 month'))) and (SELECT strftime('%Y%m%d',date('now','start of month','-1 day')))
)
```

**the result:**
![image](https://user-images.githubusercontent.com/18739609/109471289-8a1bb500-7aab-11eb-85ff-6a6c6ad2c883.png)

### Expected result

I don't know how sql parsing is implemented in SiYuan, and just explore whether this complex sql can be used

### Screenshot or screen recording presentation

see figure above

### Version environment

* Version:  v1.0.8 / Kernel v1.0.8
* Operating system: 
* Browser (if used): 

### Log File

null

### More information

null

**Comment by 88250** [comment]
`created` and `updated` is not `DATATIME`/`DATE` type, it is `TEXT` type, so try using '<' or '>' comparison operator for it.

**Comment by banjuer** [comment]
> `created` and `updated` is not `DATATIME`/`DATE` type, it is `TEXT` type, so try using `<` or `>` comparison operator for it.

I tried it but it didn't work.

**query sql**
```sql
select  * from blocks where type='i' and path = '/work.md' and markdown like '%[x]%' and created >=(SELECT strftime('%Y%m%d',date('now','start of month','-1 month'))) and created<=(SELECT strftime('%Y%m%d',date('now','start of month','-1 day')))
```

by the way, the `strftime()` function's result type was `TEXT`

![image](https://user-images.githubusercontent.com/18739609/109474602-a6b9ec00-7aaf-11eb-9bcf-57cf11e225f9.png)
