### ISSUE TITLE
Sync that does not require to turn on auto-commit

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1734]
### In what scenarios do you need this function?

I connected to my own remote repo, and I don't want to have meaningless automatic commitin the remote repo. 

![image](https://user-images.githubusercontent.com/47321059/109525868-ebb04380-7aec-11eb-83ab-04c523bc383b.png)
![image](https://user-images.githubusercontent.com/47321059/109525909-f66ad880-7aec-11eb-8b80-46a4bca77051.png)

**Comment by 88250** [comment]
If you want to use a third-party repository service, please use `git` command externally, thanks.

**Comment by dejavudwh** [comment]
> If you want to use a third-party repository service, please use `git` command externally, thanks.

Yeah, I know. I just think that the automatic commit can be turned off independently without affecting the synchronization feature.

**Comment by 88250** [comment]
@dejavudwh Sync depends on Git at present, maybe re-implement it in the future.

**Comment by dejavudwh** [comment]
thanks!
