### ISSUE TITLE
repo metadata error

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1735]
### Describe the problem

During sync, the panel show repo metadata error. 

siyuan.log:
![image](https://user-images.githubusercontent.com/47321059/109527350-81000780-7aee-11eb-851f-4e3794461489.png)

After killing the kernel, return to normal.

### Version environment

* Version: 1.0.8
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
* If you want to use a third-party repository service, please use `git` command externally
* This error log above please ignore, we will improve it later

Thanks.
