### ISSUE TITLE
支持行级备注

### ISSUE THREAD

**Issue by lvzhp** [siyuan-note/siyuan#174]
选中 一部分文字，进行悬浮注释。
类似于脚注，但是不是标注在底部，而是在注释的文字旁有个图标，鼠标移上去，即可显示注释的内容。

**Comment by 88250** [comment]
行级内容的备注（或者叫批注）暂时没有，但块级内容（针对内容块）的备注已有计划，请看 https://github.com/siyuan-note/siyuan/issues/64

**Comment by 88250** [comment]
行级的暂时不考虑了，谢谢。

**Comment by aptexd** [comment]
好奇一下，行级注释通过什么方案进行锚定文本的，是字符串吗，还是特殊标记

**Comment by 88250** [comment]
@aptexd 将选择的文本加上 `<span>`，类似这样：

```html
foo<span data-type="comment" data-comment-content="这里是对 bar 的注释">bar</span>baz
```

**Comment by 88250** [comment]
为了和块级备注对应，命名定为 `行级备注`，DOM 结构大致是：

```html
foo<span data-type="inline-memo" data-inline-memo-content="这里是对 bar 的备注">bar</span>baz
```
