### ISSUE TITLE
Siyuan not opening on mac

### ISSUE THREAD

**Issue by raphaelhuleux** [siyuan-note/siyuan#1741]
Hi, 

The app doesn't open on my mac, it stays stuck at the loading phase.

**Comment by langzhou** [comment]
try to close it and reopen it.

**Comment by raphaelhuleux** [comment]
I tried that and reinstalling it, but still stuck.

**Comment by 88250** [comment]
Hello, are you using SiYuan v1.0.9 on Apple silicon?

**Comment by raphaelhuleux** [comment]
Hello, I'm using the last version of SiYuan on a 2020 Macbook Pro with an Intel Core i5. I finally managed to open it, but don't really know what changed.
