### ISSUE TITLE
Embed PDF file of absolute path link

### ISSUE THREAD

**Issue by hyjwonder** [siyuan-note/siyuan#1743]
### In what scenarios do you need this function?

Display an embedded view of a PDF file. Currently it only supports PDF files in "Assets" folder, whereas PDF files in other folders, such as Downloads folder, are not supported.
OS: MacOS Big Sur 11.2

### Describe the optimal solution
The following code works:
<iframe src="assets/filename.pdf" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" height=500> </iframe>

-------

The following code does not work:
<iframe src="/Users/username/Downloads/filename.pdf" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" height=500> </iframe>

**Comment by 88250** [comment]
Hello, this is the design expectation, thanks.
