### ISSUE TITLE
Copy the local images when calling templates

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1747]
### In what scenarios do you need this function?

If I have a template with local images 

> The template
![image](https://user-images.githubusercontent.com/33789516/109754275-63b16300-7bec-11eb-9586-08d259aab988.png)

When using `{{` to import a template to a note copy the images as well with the text

> After importing the template
![image](https://user-images.githubusercontent.com/33789516/109753457-f8b35c80-7bea-11eb-90fc-80bcb821727b.png)

**Comment by 88250** [comment]
The next release (v1.2.0) will use the universal assets folder to save asset files, so I think this issue can be closed, thanks.
