### ISSUE TITLE
Windows 版发布包增加 Zip 绿色解压版

### ISSUE THREAD

**Issue by hallnorthncov** [siyuan-note/siyuan#175]
喜欢解压即用的绿色便携版笔记软件，可以用u盘或云盘一起带走。
希望能同时发布exe安装包和zip安装包。

**Comment by 88250** [comment]
感谢建议，但需要等[自动更新](https://github.com/siyuan-note/siyuan/issues/170)方案确定后再考虑。

**Comment by hallnorthncov** [comment]
好的，我使用的便携版fdm(free download manager)能自动更新，可以参考一下

**Comment by fxxf1111** [comment]
2年了，还是没用绿色版
