### ISSUE TITLE
My way for note boxes

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1755]
### In what scenarios do you need this function?

Hello @88250

Just letting you know, That I've used this way to accomplish note boxes through templates:

![image](https://user-images.githubusercontent.com/33789516/109817770-f547c180-7c3a-11eb-9486-3202fa70c6d0.png)

![image](https://user-images.githubusercontent.com/33789516/109817278-69ce3080-7c3a-11eb-8cae-cdb15611baaa.png)

each box in a separate file

---

And here is how it looks in different themes

![image](https://user-images.githubusercontent.com/33789516/109816525-84ec7080-7c39-11eb-8a3b-2f78f71769e2.png)

---

![image](https://user-images.githubusercontent.com/33789516/109817079-296eb280-7c3a-11eb-95af-c0b1d73cff13.png)

--

![image](https://user-images.githubusercontent.com/33789516/109817151-3f7c7300-7c3a-11eb-805d-68057ba2302d.png)

---

Just letting you know in case you want to extend this further some how, or consider it while developing the themes

Thank you

**Comment by 88250** [comment]
It's cool! If could, welcome to share it on the [community bazaar](https://github.com/siyuan-note/bazaar), please refer to the user guide for more details, thanks.
