### ISSUE TITLE
嵌入块下面的块行首的backspace删除问题。

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#178]
![QQ图片20201007102813](https://user-images.githubusercontent.com/66795040/95280694-356f6780-0888-11eb-9874-7031719a5838.png)
嵌入快后面如果有一个空行，在空行头这里，按backspace，删除不了这个空行块，只能在下面的块头上按backspace删除。

**Comment by 88250** [comment]
现在似乎已经没问题了，谢谢。
