### ISSUE TITLE
AI Suggestions

### ISSUE THREAD

**Issue by darkfire5900** [siyuan-note/siyuan#1781]
### In what scenarios do you need this function?

Your note title “animals” may imply that other relevant notes contain animals, such as cats, elephants, etc.

### Describe the optimal solution

Since this is artificial intelligence, it must be trained first, etc. However, on the front end it can simply display related connections.

### Describe the candidate solution

In order to identify relationships between words, it is helpful to compare word embeddings. Perhaps the words are considered sufficiently associated, if they fulfill a certain threshold.

### Other information

Thank you for considering this feature, as I believe it would be extremely valuable for many people.

**Comment by 88250** [comment]
SiYuan is still in the basic development stage. We need to stabilize the basic functions first, and then consider the advanced features in the future. Thank you very much.
