### ISSUE TITLE
Document formatting

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1787]
### Describe the optimal solution

Support document formatting and support users to configure the formatting method by themselves. For example, delete line breaks, convert Chinese and English characters, and automatically add lists, etc.

**Comment by 88250** [comment]
Can you give me an example?

**Comment by dejavudwh** [comment]
I think formatting in a document is difficult compared to code formatting. Or Siyuan can refer to word and add richer format brushes after the selected paragraph, such as deleting spaces, highlighting text, etc., because Siyuan's formatting capabilities are not very strong now, of course, this may also violate the original intention of Markdown. So this is just my immature idea. 

![image](https://user-images.githubusercontent.com/47321059/110611212-f98b5600-81c9-11eb-860d-b04c82a67dd5.png)

![image](https://user-images.githubusercontent.com/47321059/110610974-b92bd800-81c9-11eb-9d7c-22d9ef9d6bcb.png)

**Comment by 88250** [comment]
I think we should keep the original text as can as possible, it is a personal style in some cases. 

Thank you for sharing.
