### ISSUE TITLE
About Click Hyperlinks

### ISSUE THREAD

**Issue by Lilac-Dream** [siyuan-note/siyuan#1795]
### In what scenarios do you need this function?
Click Hyperlinks

### Describe the optimal solution
I don't want to open web when i click hyperlinks.

### Describe the candidate solution
1. Click hyperlinks can't open web. (only edit it)
2. Open web when i use ctrl add click hyperlinks.

### Other information
I want have a setting to set it.

**Comment by 88250** [comment]
Use option is a good idea, but we still need time to continue to think about it, thanks.

**Comment by Lilac-Dream** [comment]
好的，先谢谢作者大大~~

**Comment by 88250** [comment]
在 v1.2.0 中超链接还是使用单击打开，编辑使用右键弹框，大概是这个样子的：

![link](https://user-images.githubusercontent.com/873584/116051366-182aab00-a6ab-11eb-88e7-91c5b2cf5bf3.gif)

谢谢，我关闭了。
