### ISSUE TITLE
Ctrl+F support search ref anchor text

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1800]
### Describe the problem

ctl + f  can't search Reference names

![image](https://user-images.githubusercontent.com/33789516/110328190-b0010680-8023-11eb-8332-1d87953dfd38.png)

**Comment by 88250** [comment]
It’s a bit complicated here, try to improve it later, thank you.

**Comment by 88250** [comment]
Merged into https://github.com/siyuan-note/siyuan/issues/1995
