### ISSUE TITLE
Input cursor misplaced

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#1818]
### Describe the problem

Input cursor misplaced 

### Screenshot or screen recording presentation

![11](https://user-images.githubusercontent.com/47321059/110613530-5a1b9280-81cc-11eb-929d-f513aedca498.gif)

### Version environment

* Version: 1.1.2
* Operating system: win10 
* Browser (if used):

**Comment by Vanessa219** [comment]
Unable to reproduce, but related issues have been modified, please try again in the 1.1.3 preview version.

**Comment by dejavudwh** [comment]
Update: This problem may occur when the notes are not saved, and there is no problem after saving.
