### ISSUE TITLE
页签预览模式

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#183]
### 当前环境：
- 操作系统： win10
- 思源版本：V0.2.6

### 场景描述
目前思源打开**新页签**有两种方式:
1. 通过左侧目录打开**新页签**
2. 通过搜索打开**新页签**
但是这种方式，会产生大量新页签，不利于页面浏览

### 期望的改进
参考Visual Studio Code 的设置，那就是当你打开一个文件的时候，如果你只是看看，并不做任何修改，那么这个查看文件的 Tab 只是临时的，它会在你打开下个文件的时候被替换，也就是说，始终只会有一个「预览」功能的 Tab，直到你在这个 Tab 做了修改（编辑操作或双击页签），那么下个预览就会在新的 Tab 打开。

![页签预览模式](https://user-images.githubusercontent.com/15924513/95324495-64aac680-08d2-11eb-973a-bcf386c45836.gif)

vscode tab设置相关参考：[使 Visual Studio Code 的打开文件始终在新 Tab](https://imtx.me/blog/make-visual-studio-code-open-files-always-in-new-tab/)

**Comment by lss6378** [comment]
可以参照下Obsidian, 默认情况下是预览模式，锁定后打开是新建窗口  

![窗口锁定与预览](https://user-images.githubusercontent.com/15924513/96363884-82e1b380-1169-11eb-87dc-9689e37f161f.gif)

**Comment by 88250** [comment]
现在已有在右侧或下侧打开，所以似乎可以关闭该 issue 了？

![image](https://user-images.githubusercontent.com/873584/97123793-5e3c9b80-1768-11eb-9eb9-77a91229fcee.png)

**Comment by lss6378** [comment]
> 
> 
> 现在已有在右侧或下侧打开，所以似乎可以关闭该 issue 了？
> 
> ![image](https://user-images.githubusercontent.com/873584/97123793-5e3c9b80-1768-11eb-9eb9-77a91229fcee.png)

目前遇到的主要问题是，在浏览的过程中，会产生大量中间页签，希望有预览模式可以减少 **临时页签** 的产生

**Comment by lss6378** [comment]
举个例子：
我在浏览 LYT 库的时候，才半个小时，就产生能好多页签，需要边看边关  
预览模式则不会产生新的页签，只有在需要的时候生成页签，整个浏览过程就会显得比较流畅
![图片](https://user-images.githubusercontent.com/15924513/97141558-ea1aeb80-1799-11eb-9d23-af020de069bf.png)

**Comment by Vanessa219** [comment]
本来想找一下 IDEA 是怎么实现的，结果没找到。。。VS 那个感觉和我们单双击的配置冲突了，OB 的又有点不方便。

**Comment by lss6378** [comment]
> 
> 
> 本来想找一下 IDEA 是怎么实现的，结果没找到。。。VS 那个感觉和我们单双击的配置冲突了，OB 的又有点不方便。

单双击的配置是从**文件树打开页签**，从并不冲突，VSC也是有配置可以开启/关闭**页签模式**
- 开启页签预览模式，默认开启的页签是 **预览页签**，**双击页签** 或者 **编辑内容** ，**预览页签** 变为 **普通页签**
- 关闭页签预览模式，开启的都是 **普通页签**，和原来一样
- 从文件树双击文件名切换**预览页签** -->**普通页签**，这个功能比较鸡肋，可以割掉

**Comment by lss6378** [comment]
标签也管理也可以参考浏览器的解决方案: [标签式浏览](https://support.mozilla.org/zh-CN/kb/%E6%A0%87%E7%AD%BE%E5%BC%8F%E6%B5%8F%E8%A7%88)


> ## 在新标签页里打开链接
> 
> 通常，你点击一个链接时，链接会在当前的标签页里打开。如果你想要在一个新标签页里打开链接，你只需 右击链接，然后在弹出菜单里选择 在新标签页里打开链接。

**Comment by Vanessa219** [comment]
想象着改了一下，不好用再改
