### ISSUE TITLE
Folder tree not updating

### ISSUE THREAD

**Issue by hyjwonder** [siyuan-note/siyuan#1835]
### Describe the problem

Environment: Siyuan on MacOS

1. If you drop an .md file into Siyuan folder (I mean through mac Finder, not through the Siyuan app)
2. Then you click "refresh“ in Siyuan
3. The .md file is not shown in Folder tree, but if you search, the new .md file is shown in the results, and you can open the .md file by clicking the result.

### Expected result

1. The .md file should show in the folder tree.
2. Screenshot shows the file count is "2", but only one file in the tree, while the new .md is missing.

### Screenshot or screen recording presentation

![CleanShot 2021-03-14 at 09 36 25@2x](https://user-images.githubusercontent.com/77609410/111054809-a0ae0d00-84aa-11eb-8547-9214dc35576e.png)

### Version environment

* Version: Siyuan 1.1.2
* Operating system: MacOS 11.2.3
* Browser (if used): n/a

### Log File

n/a

### More information

n/a

**Comment by ttimasdf** [comment]
+1, and for a similar issue, maybe a file watcher will solve them both.

Markdown files modified by external program (e.g. Typora) is not updated automatically. A manual close-reopen may update the content.

**Comment by 88250** [comment]
@hyjwonder Please use the import function to import the standard markdown file.
@ttimasdf Yes, SiYuan does not watch file/folder change at present, we need time to think about it.

Thank you.

**Comment by ttimasdf** [comment]
Seems #1977 has been closed that we could expect the feature in next release 😉  @hyjwonder
