### ISSUE TITLE
An error occurred during synchronization

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#1847]
### Describe the problem

An error occurred during synchronization

### Expected result

Sync correctly

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/18739609/111127339-b0af1500-85ae-11eb-8865-3fdd38e7450d.png)

### Version environment

* Version: v1.1.2 / Kernel v1.1.2
* Operating system: win10
* Browser (if used): 

### Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/6139972/siyuan.log)

### More information

nil

**Comment by 88250** [comment]
Hello, maybe .git is corrupted, please clean it follow the user guide. 

We are re-implementing sync, it will be released in v1.1.3, thanks.
