### ISSUE TITLE
Windows10下，1.1.3版本同步失败

### ISSUE THREAD

**Issue by luwanglin** [siyuan-note/siyuan#1864]
### Describe the problem

Windows10下，1.1.3版本同步失败

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/34809270/111744712-9e8ee880-88c6-11eb-8041-80fec7a83559.png)

### Version environment

* Version: 当前版本 v1.1.3 / Kernel v1.1.3
* Operating system:   Windows 10 专业版 20H2
* Browser (if used): 

### Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/6169300/siyuan.log)

**Comment by 88250** [comment]
你好，麻烦有空的时候再帮忙试一下，我先关闭 issue 了，有任何问题请跟帖反馈，谢谢。
