### ISSUE TITLE
列表项和注释使用显示异常，注释也变成列表项

### ISSUE THREAD

**Issue by guidongyuan** [siyuan-note/siyuan#1897]
在列表下方使用注释，切换到下一个列表项，注释也变成了列表项
![image](https://user-images.githubusercontent.com/13446866/112236023-c1c8e780-8c7a-11eb-879d-c27b724d44c8.png)
按下 Enter后，发现注释也变成列表项
![image](https://user-images.githubusercontent.com/13446866/112236123-c8eff580-8c7a-11eb-9f1a-214ef749a1ff.png)

![image](https://user-images.githubusercontent.com/13446866/112236176-e02ee300-8c7a-11eb-9b72-04353a0f5761.png)

**Comment by 88250** [comment]
谢谢，后续排查。

PS 中文反馈请到社区发帖 https://ld246.com/domain/siyuan #1440

**Comment by 88250** [comment]
这个逻辑应该是正常的，如果需要再 Blockquote `>` 中换行请使用 Shift Enter。

**Comment by guidongyuan** [comment]
> 这个逻辑应该是正常的，如果需要在 Blockquote `>` 中换行请使用 Shift Enter。

不正常吧。
现在异常问题是，一开始我的引用块是缩进的，退出引用块后，发现引用块前面也加了一个点变成列表项了。

![image](https://user-images.githubusercontent.com/13446866/112245867-b2529a00-8c8c-11eb-9111-29aebe1c238d.png)

**Comment by 88250** [comment]
@guidongyuan 哦，抱歉没看清楚，后续改进。
