### ISSUE TITLE
Embedded block queries do not work properly in some cases

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#1912]
### Describe the problem

This query statement is working fine, but the results are not available in siyuan

![图片](https://user-images.githubusercontent.com/28727933/112711523-06b37f00-8f04-11eb-9842-287981aaeba8.png)

### Version environment

* Version:  v1.1.5 / Kernel v1.1.5
* Operating system:  Windows_NT x64 10.0.19042
* Browser (if used):

**Comment by 88250** [comment]
Sorry, I can't reproduce it.

![image](https://user-images.githubusercontent.com/873584/112725772-d516d400-8f54-11eb-82f7-1f6f411587ea.png)

Close first, please give me more details, thanks.
