### ISSUE TITLE
Can't not sync on macOS

### ISSUE THREAD

**Issue by Jiaohang** [siyuan-note/siyuan#1923]
### Describe the problem
从云端下载笔记本失败

上传到云端的设备
Win10

从云端下载的设备
MacOS 10.15.7 , Intel CPU
SiYuan  v1.1.5
rsync  version 3.2.3  protocol version 31 installed
/etc/hosts 已经添加下列配置
8.136.157.37   siyuan.b3logfile.com

### Expected result
同步笔记本 [Career Notes] 失败：pull output [Warning: Permanently added 'siyuan.b3logfile.com,8.136.157.37' (ECDSA) to the list of known hosts. auth failed rsync: connection unexpectedly closed (0 bytes received so far) [Receiver] rsync error: error in rsync protocol data stream (code 12) at io.c(228) [Receiver=3.2.3] ], err [exit status 12]

### Screenshot or screen recording presentation

<img width="1920" alt="截屏2021-03-29 下午1 55 26" src="https://user-images.githubusercontent.com/49380344/112792693-8a04da00-9096-11eb-8c10-e180f17d0e24.png">

### Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/6219563/siyuan.log)

**Comment by 88250** [comment]
你好，请升级到 v1.1.6 再帮忙测试一下，谢谢。

**Comment by Jiaohang** [comment]
Good！v1.1.6 版本可以正常同步了
