### ISSUE TITLE
When pasting code in code block it creates new lines

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1938]
### Describe the problem

When pasting code in code block it creates new lines  (These new lines did not exist in the original code) and  confirmed that the issue happens only when pasting to siyuan note

![image](https://user-images.githubusercontent.com/33789516/113244540-7d120180-92b5-11eb-9299-a514bad2d746.png)

**Comment by 88250** [comment]
Hi, We invite you to join the Insider team, please accept the invitation, and download the `v1.1.61 Insider Preview` in repo https://github.com/siyuan-note/insider to help us test. If this issue still exists, please let us know, thanks.

**Comment by eslam-gomaa** [comment]
Thank you, Accepted

**Comment by eslam-gomaa** [comment]
Tested and still exists

**Comment by 88250** [comment]
Can you give me the raw content from the clipboard? It's maybe HTML content, thanks.

**Comment by eslam-gomaa** [comment]
try to copy and past this 

```
#Application Setup 
frontend ContentSwitching

  bind 10.10.10.100:443
  mode  http
  option httplog
  acl host_sub2 hdr(host) -i sub2.mydomain.com
  acl host_sub3 hdr(host) -i sub3.mydomain.com
  use_backend sub2_nodes if host_sub2
  use_backend sub3_nodes if host_sub3

frontend PassThrough1
  bind 10.10.10.101:443
  mode  tcp
  option tcplog
  use_backend sub1_nodes     

frontend PassThrough2
  bind 10.10.10.102:443
  mode  tcp
  option tcplog
  use_backend sub4_nodes

backend sub1_nodes
  mode tcp
  balance roundrobin
  stick-table type ip size 200k expire 30m
  stick on src
  server node1 10.10.10.101:8081 check
  server node2 10.10.10.102:8081 check 

backend sub2_nodes
  mode http
  balance roundrobin
  stick-table type ip size 200k expire 30m
  stick on src
  server node1 10.10.10.101:8082 check
  server node2 10.10.10.102:8082 check 

backend sub3_nodes
  mode http
  balance roundrobin
  stick-table type ip size 200k expire 30m
  stick on src
  server node1 10.10.10.101:8083 check
  server node2 10.10.10.102:8083 check

backend sub4_nodes
  mode tcp
  balance roundrobin
  stick-table type ip size 200k expire 30m
  stick on src
  server node1 10.10.10.101:8084 check
  server node2 10.10.10.102:8084 check
```

**Comment by 88250** [comment]
Copy the above content from the GitHub page can't reproduce this issue, and I try to paste it into IDEA and copy-paste it again to SiYuan can't reproduce it also.

**Comment by eslam-gomaa** [comment]
The same happens when copying from github or other app

![empty-lines](https://user-images.githubusercontent.com/33789516/113287183-7f904d80-92ed-11eb-97b9-e06e7d0f8a3d.gif)

**Comment by 88250** [comment]
Thanks, I can reproduce it, here is a workaround:

![issue](https://user-images.githubusercontent.com/873584/113287813-aa47c980-9320-11eb-843c-ca6023789380.gif)

I will try to fix it later.

**Comment by eslam-gomaa** [comment]
Nice, Thanks
