### ISSUE TITLE
查询笔记本失败

### ISSUE THREAD

**Issue by zZ-10** [siyuan-note/siyuan#194]
![image](https://user-images.githubusercontent.com/58500946/95530740-38e22a80-0a11-11eb-9db7-a231f6c097a3.png)
版本更新后，旧版本内的笔记无法打开、无法关闭， 0.2.4升级到0.2.7版本

**Comment by 88250** [comment]
请在设置外观中重置一下应该就好了。

**Comment by zZ-10** [comment]
好的， 已解决
