### ISSUE TITLE
Tray icon missing on Linux KDE

### ISSUE THREAD

**Issue by Clouder0** [siyuan-note/siyuan#1952]
### Describe the problem

No tray icon is displayed on Linux(KDE desktop). 

I've enabled `Close button settings: shrink to tray after clicking the close button` and now every time I click the close button, the form just gets minimized rather than shrink to tray.

It is notable that I am using applications generated by [nativefier](https://github.com/nativefier/nativefier) and the tray icon appeared as expected.

### Expected result

Show a system tray icon.

### Log

Nothing special.

[siyuan.log](https://github.com/siyuan-note/siyuan/files/6250370/siyuan.log)

### Version environment

* Version: 1.1.7
* Operating system: Manjaro Linux, KDE desktop

**Comment by 88250** [comment]
There is no time to troubleshoot this issue, so sorry.

**Comment by Clouder0** [comment]
A temporary solution:  run SiYuan Kernel in the background and build `http://127.0.0.1:6806/stage/build/desktop/` by Nativefier.

For more information, see [Linux 下使用 Nativefier 打包思源笔记](https://ld246.com/article/1622898305015)

**Comment by 88250** [comment]
I close this issue, thank you for sharing it.
