### ISSUE TITLE
forsted glass主题显示异常

### ISSUE THREAD

**Issue by JingchengLi** [siyuan-note/siyuan#1953]
### Describe the problem
![image](https://user-images.githubusercontent.com/5918144/113434809-338bf880-9414-11eb-803d-5e14122dada3.png)

如图，MAC上应用forsted glass主题后，显示异常。

### Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
你好，如果是主题样式问题，麻烦给该主题的作者反馈，非常感谢。
