### ISSUE TITLE
思源笔记大纲前增加竖线，优化视觉观察

### ISSUE THREAD

**Issue by wolovejing** [siyuan-note/siyuan#1963]
### 思源笔记大纲的进一步优化
我看到思源笔记近期以及2.0计划中并没有实现真正大纲的想法，说实话现在思源的大纲不是真正的大纲，但是也够我用了。但是我经常把不同级别的标题看到一起。所以希望在前面加个竖线，类似这样的。

![image](https://user-images.githubusercontent.com/30975494/113510168-1417db80-958c-11eb-88be-7c4cd868969b.png)

### 自己尝试的解决方法

我自己自定义主题，但是有很多限制（因为我是个半吊子）
1. 造成了文件数前面也有竖线
![image](https://user-images.githubusercontent.com/30975494/113510305-cbaced80-958c-11eb-9cd3-6307ce2e4957.png)

2. 只能按照标题级别从一级标题逐步到增加 不能跳级别，要不然机会布局错乱

### 希望能在大纲前面增加竖线

**Comment by 88250** [comment]
你好，这部分暂时不会进行调整了，抱歉。
