### ISSUE TITLE
Template folder should NOT be included while rendering global graph

### ISSUE THREAD

**Issue by Lemoners** [siyuan-note/siyuan#1978]
### In what scenarios do you need this function?

When open `global graph`, notes from `template` folder should not be included.

Current graph: (As you might see, the notes from `template` is really distracting.)
![image](https://user-images.githubusercontent.com/39124095/113819795-63d4ed80-97ac-11eb-9c72-5e880499d075.png)

### Describe the optimal solution

Leave out all notes from `template` folder while rendering global graph.

### Describe the candidate solution

Maybe the user can filter notes that are displayed on the graph.

`Filters` in [Obsidian](https://obsidian.md/)
![image](https://user-images.githubusercontent.com/39124095/113819963-a72f5c00-97ac-11eb-87a3-bcce1d908373.png)

As you might see from the picture above, Obsidian provides multiple filters for the user to specify which notes to be displayed.

**Comment by 88250** [comment]
Thanks, we will exclude the template path in the next release.

By the way, you can find the graph filer here:
![image](https://user-images.githubusercontent.com/873584/113890395-b2a77500-97f6-11eb-8efc-63dce3f300a3.png)

**Comment by Lemoners** [comment]
Thanks for reply~

> 
> By the way, you can find the graph filer here:
>

Yeah I know the filter can exclude/include some types of notes, but I was actually hoping for some more advanced filters. Sorry I didn't explain Obsidian's filter function clearer before.

![image](https://user-images.githubusercontent.com/39124095/113957080-2d9d7980-9851-11eb-864e-fcbf4f96e800.png)

They have multiple filter choices, and they can be applied at the same time. 
For example: If I just want to see notes **in the directory: Siyuan**, but without tag **#TODO#**
I can use filters like: `path:"Siyuan"; !tag:"#TODO#"`

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/113957624-2460dc80-9852-11eb-85ec-142281c24581.png)

![image](https://user-images.githubusercontent.com/873584/113957706-4b1f1300-9852-11eb-99a7-9d34984c8150.png)

**Comment by Lemoners** [comment]
Right, sorry I forgot this can be applied to graph, too! Thanks for your immediate reply~

### Btw, just find that \<space\> seems can not be properly recognized during search.

> For example, I have a folder caller `0. Inbox`:
> 
> When I type `path:"0. Inbox"`, things show up perfectly.
> But `path:0. Inbox` shows nothing,  I guess that the \<space\> is interpreted as a delimiter rather than \<space\>.
> I also try `path:0.\ Inbox`, nothing shows up, either.
> One substitute is to use `path:0.?Inbox`, it works, too.

Do u think this is the right behavior, or maybe `path:0.\ Inbox` should work, too?
(But either way, this doesn't bother me, I love the regex-like search feature. 😄 )

**Comment by 88250** [comment]
* Space ` `  is a normal character, no escape need
* Space will be interpreted as `AND`
