### ISSUE TITLE
Use Protyle instead of Vditor for the editor

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1981]
*Protyle* is a brand new editor for SiYuan.

* [WYSIWYG](https://github.com/siyuan-note/siyuan/issues/1985)
* [List outline](https://github.com/siyuan-note/siyuan/issues/1983)
* [Zoom in](https://github.com/siyuan-note/siyuan/issues/1231)
* [Dynamic loading](https://github.com/siyuan-note/siyuan/issues/1977)
* [Horizontal layout](https://github.com/siyuan-note/siyuan/issues/790)
* [Block drag](https://github.com/siyuan-note/siyuan/issues/1980)

**Comment by zhongluqiang** [comment]
前进和后退这点感觉很重要，写东西的时候局部效应很明显，需要频繁在一处进入链接和返回，加上这点配合快捷捷可以很大程序上解放双手，比如vscode的Alt+ ← / →

**Comment by JokeenZhang** [comment]
@zhongluqiang 我则是喜欢用鼠标的侧边按键，在 #239 就有人提出这个点了
