### ISSUE TITLE
I don't know how to new a document on the site deployed by docker

### ISSUE THREAD

**Issue by Co1lin** [siyuan-note/siyuan#1984]
I deployed a docker version on my server, but I didn't know how to create a new document. I pressed the button in the center of the screen trying to do new a doc, however it said "Please open a notebook first". But the problem is I couldn't find a button to create a new notebook or open a default notebook. 

Anyway, it runs on my server, but I can't start my editing.

**Comment by 88250** [comment]
After close all notebooks, can you see this?

![image](https://user-images.githubusercontent.com/873584/114110250-ac55ed80-9909-11eb-97f6-41e052cda155.png)

**Comment by Co1lin** [comment]
<img width="1199" alt="Screen Shot 2021-04-09 at 8 50 08 AM" src="https://user-images.githubusercontent.com/17642707/114113159-9992e700-9910-11eb-88c4-feaa8c422893.png">
I can only see this after running the docker.

**Comment by 88250** [comment]
Please pull the lastest Docker image and follow the user guide to setup, thanks.

**Comment by Co1lin** [comment]
Now I realized my problem... The Aliyun server pull dockers from its mirror by default, so I used an old version of your docker. After I pull the latest version, it works well now. Thanks for your help!
