### ISSUE TITLE
The html tag can not be triggered properly.

### ISSUE THREAD

**Issue by Lemoners** [siyuan-note/siyuan#1986]
### Describe the problem

For example, when I type `<font>First line</font>`, I hope it to be displayed as follows:
- When the cursor is at somewhere else:  `First line`.
- When the cursor is at the tag: `<font>|First line` or `First line|</font>`.

Now, `First line|</font>` can be displayed properly, but I can not get `<font>|First line` unless I add a character and then delete it.

https://user-images.githubusercontent.com/39124095/114119673-b386f680-991d-11eb-9ae8-6fb23aa52033.mp4

### Version environment

* Version: 1.83
* Operating system: Windows

**Comment by 88250** [comment]
Hello, we are completely rewriting the editor, so the previous editing problem will not be solved, thank you.
