### ISSUE TITLE
bug: 复制链接，链接的字符串会被转换成符号

### ISSUE THREAD

**Issue by mohuishou** [siyuan-note/siyuan#1987]
### Describe the problem

![image](https://user-images.githubusercontent.com/15172509/114134075-b0016880-9939-11eb-94fe-f83e866dda71.png)

复现步骤

1. 复制这个链接 `http://baidu.com?xx=xxx&region=xxxx`
2. 在思源中使用 `ctrl+k` 就会出现上图的情况，`&reg` 被转换成了 `®`
3. 及时手动修改了这个，过段时间也会被再次转换为 `®`

### Expected result

链接中的字符串不要被转换 http://baidu.com?xx=xxx&region=xxxx

### Version environment

* Version: 当前版本 v1.1.82 / Kernel v1.1.82
* Operating system: mac os
* Browser (if used):

**Comment by 88250** [comment]
你好，我们正在重写编辑器，这个等重写完以后我们会进行测试，谢谢反馈。
