### ISSUE TITLE
Editor redo/undo

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#1988]

**Comment by tqyao** [comment]
如何撤销重做呢，一旦 control+z 撤销后，内容永久消失了。想立即恢复怎么办

**Comment by adocampo** [comment]
I don't know either which is the hotkey for "redo". Ctrl+Z undo the changes, but the usual hotkey for redo changes, Ctrl+Shift+Z does nothing. 
How can we manage to redo actions?

**Comment by Temacc0531** [comment]
> I don't know either which is the hotkey for "redo". Ctrl+Z undo the changes, but the usual hotkey for redo changes, Ctrl+Shift+Z does nothing. How can we manage to redo actions?

Ctrl+Y
