### ISSUE TITLE
Maybe I have three bugs about search bar, list and custom sorting

### ISSUE THREAD

**Issue by lognow** [siyuan-note/siyuan#1989]
### 1. `search bar` in `settings` fails to work

After I type in keyword to search like "language" or "语言" into the search bar in `settings`, and click "enter" or the magnifying glass in front the bar, nothing change.

### 2. buttons and shortcuts of `list`, `order list` and `task list` do not work

In editor, if a line, whether with words or just an empty line, is not marked as list by markdown syntax, then shortcuts of `list (ctrl+L)`, `order list (ctrl+O)` and `task list (ctrl+J)` and buttons on top of the editor do not work. 

However, if current line is marked as list using `* `, both shortcuts and buttons work as expected.

### 3. `Refresh` and `fold/unfold` opeartions will shuffle the `custom sorting` in `File Tree`

I select `custom sorting` in `File Tree` and drag the notes to change their sorting, this works well; but `refresh` or `fold/unfold` will shuffle the `custom sorting`. Is this a bug or designed feature?

### Version environment

* Version: 1.1.83
* Operating system: Win10

**Comment by 88250** [comment]
We will check it before the next release, thanks.
