### ISSUE TITLE
on Linux -- unable to create ordered list, numbered list or to do

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#1991]
### Describe the problem

App version:  v1.1.83   (Linux appimage)

none of those work on Linux (even when using the hot keys) but they do work if I do them manually. i.e `- [  ] to create a  to-do`

![image](https://user-images.githubusercontent.com/33789516/114273186-76a02a00-9a19-11eb-9fe6-fa638fc8f9e0.png)

**Comment by 88250** [comment]
Hello, we are completely rewriting the editor, so the previous editing problem will not be solved, thank you.

**Comment by eslam-gomaa** [comment]
Thank you
