### ISSUE TITLE
The webpage stuck at the loading stage when using another port

### ISSUE THREAD

**Issue by Co1lin** [siyuan-note/siyuan#1992]
Thanks for your reply.

Actually I have tried to use NGINX and docker port mapping, but I met some problems. I ran 
```shell
docker run --name syr -v ~/siyuan/conf:/siyuan/conf -v ~/siyuan/data:/siyuan/data -p 16806:6806 b3log/siyuan --resident=true --conf=/siyuan/conf/ --data=/siyuan/data/ --authCode=123 --readonly=true
```
to run the docker, and visit http://mydomain:16806 . However, the webpage stuck at the loading stage. I used Developer Tools to check what happened, and I saw 
```
Failed to load 'http://mydomain:6806/stage/vditor/dist/js/lute/lute.min.js?v=1.1.83'.
```
in the console, which means some resources were still provided with the fixed port 6806, so I think it was hard to solve.

By the way, the authentication requires both username and password. I can only find how to specify the password, but I don't know how to alter the username. The default username is "siyuan", which is figured out by my trying, and I suggest declare it in the user guide.

_Originally posted by @Co1lin in https://github.com/siyuan-note/siyuan/issues/1990#issuecomment-817174748_

**Comment by 88250** [comment]
Hello, try to specify the boot parameter like this `--servePath=http://mydomain:16806`.
