### ISSUE TITLE
Enable MathJax automatic equation numbering feature

### ISSUE THREAD

**Issue by mythmyp** [siyuan-note/siyuan#1993]
### In what scenarios do you need this function?
做大量公式推导，查看了mathjax的文档，是有自动编号的功能的。

### Describe the optimal solution
根据官方的文档，通过添加以下设置就能开启自动编号功能：
```
window.MathJax = {
  tex: {
    tags: 'ams'
  }
};
```
from http://docs.mathjax.org/en/latest/input/tex/eqnumbers.html

**Comment by 88250** [comment]
Sorry for my late reply, we will add it in v1.2.0, thank you.

**Comment by 88250** [comment]
The MathJax engine has some issues, we are considering to remove it, use KaTex instead of it.
