### ISSUE TITLE
Docker部署的网页版bug

### ISSUE THREAD

**Issue by Jackiexiao** [siyuan-note/siyuan#1999]
网页:
http://jackiexiao.com:6806/

bug:
1. Ctrl + alt + C 无法复制纯文本（貌似是快捷键冲突?）且期望更改 ctrl + C 为复制纯文本（更符合直观的操作习惯）
2. 图片无法正常显示（刷新后会丢失）

部署指令:
```
docker pull b3log/siyuan && \
docker run -v /siyuan/conf:/siyuan/conf \
-v /siyuan/data:/siyuan/data \
-p 6806:6806 b3log/siyuan \
--resident=true \
--conf=/siyuan/conf/ \
--data=/siyuan/data/ \
--authCode="BEYOND" \
--name siyuan_server
```

**Comment by 88250** [comment]
你好，图片问题可能需要加启动参数 `--servePath`，复制问题后期排查，谢谢。

**Comment by Jackiexiao** [comment]
thx

**Comment by Jackiexiao** [comment]
请问我设置了自己的 authCode，访问时输入 用户名 siyuan 以及自己的 authCode，但是遇到报错 unauthenticated 如何解决?
抱歉啊，对网页交互这块不太熟悉 @88250

**Comment by 88250** [comment]
这个可能是个 bug，多刷下几次试试，后面我们再排查，目前在做编辑器重写，现有缺陷暂时不进行修复了，谢谢。

**Comment by Jackiexiao** [comment]
好
