### ISSUE TITLE
分享文档到链滴

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2004]
[B3log 构思 - 分布式社区网络](https://ld246.com/article/1546941897596)

* 需要注册并登录链滴账号
* 导出 Markdown 后对接链滴[发布帖子接口](https://ld246.com/article/1488603534762#%E5%8F%91%E5%B8%83%E5%B8%96%E5%AD%90)
  * 文档标题作为帖子标题
  * 文档标签作为帖子标签
  * 文档导出的 Markdown 作为帖子内容，其中引用转换为脚注
* 上传资源文件到社区图床
  * 免费用户单个文件小于 3MB
  * 订阅用户单个文件小于 10MB
* 分享完毕后对文档写入属性 `custom-liandi-articleId` 用于关联链滴帖子 ID

该特性从 v2.6.1 发布后进入订阅用户内测阶段，v2.7.0 对所有用户可用。

**Comment by Zuoqiu-Yingyi** [comment]
期待 思源-博客-社区 三端互通🎉

**Comment by qifengle1998** [comment]
![47D171DD65B8B4B19D957AE8CBE7A3C9](https://user-images.githubusercontent.com/37429029/175203997-8a2faafa-7140-4915-8cb6-8f5903591b59.png)
好馋Icity这个日记分享功能。

**Comment by iamqiz** [comment]
+10086

**Comment by aptexd** [comment]
争取早日实现，这样就能愉快得提 Bug 了🤣

**Comment by 88250** [comment]
该特性从 v2.6.1 发布后进入订阅用户内测阶段，v2.7.0 对所有用户可用。

**Comment by woniuxia** [comment]
D 大，审核怎么搞？

**Comment by 88250** [comment]
和现在的链滴审核一样。

**Comment by eulores** [comment]
Hello,

It is impossible for international users to register at ld246.com, as a requirement is to have a Chinese mainland mobile telephone number.
Is there any alternative means of creating an account on ld246.com?
I would like to participate actively in the discussions surrounding SiYuan. Right now I am only reading (with the help of Google Translate).

Kind regards,
eulores

**Comment by iamqiz** [comment]
@eulores  ld246 is mainly a chinese community,in addition,sharing to ld246 need  BBS points ,so it maybe not suitable for foreign users,  😂 
you can try this widget to share doc to other website, 
terwer/sy-post-publisher: Publish siyuan article to supported open platforms 发布思源笔记到支持的平台
https://github.com/terwer/sy-post-publisher
