### ISSUE TITLE
YAML Front Matter 导入问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#202]

**Comment by Vanessa219** [comment]
补充：不应该带 `{: id="20201010223936-stfo3qh"}`
![image](https://user-images.githubusercontent.com/970828/95657894-97122900-0b49-11eb-825c-d9563ae56217.png)

**Comment by 88250** [comment]
@Vanessa219 这个问题在 https://github.com/siyuan-note/siyuan/issues/109 中处理。
