### ISSUE TITLE
Remove auto fetch remote image to local

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2033]
It should use the external browser extension instead:

* [JianYue](https://github.com/siyuan-note/siyuan/issues/1292)
* [Web Clipper](https://github.com/siyuan-note/siyuan/issues/1266)

**Comment by alanelminster** [comment]
I really like this feature…… 
In most time I just need to copy a single picture to a specific location. 
All those external extensions can't easily solve this situation.

**Comment by 88250** [comment]
@alanelminster Sorry,  some websites need auth (via cookie) in some cases, so it not very 'stable' to use. We will think about it later, maybe a browser extension is a final resolution.

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2035
