### ISSUE TITLE
running bug.

### ISSUE THREAD

**Issue by eyeswinds** [siyuan-note/siyuan#2036]
![image](https://user-images.githubusercontent.com/44407703/117392952-a877b400-af25-11eb-8ce3-2e33ecc43d98.png)

version: macos 1.1.83 /1.1.82  

the app can not opening ,   stucks in this interface .  its not useful though i reinstalling again and again.

**Comment by 88250** [comment]
Hello, try to delete the global conf dir `~/.siyuan` and restart, thanks.
