### ISSUE TITLE
What is the default username and password for the docker container?

### ISSUE THREAD

**Issue by fengwang** [siyuan-note/siyuan#2039]
### Describe the problem

After running the docker with a command line of 
```
docker run -v /data/Configuration/siyuan/conf:/siyuan/conf -v /data/Configuration/siyuan/data:/siyuan/data -p 7801:6806 b3log/siyuan --resident=true --conf=/siyuan/conf/ --data=/siyuan/data/
```

I am stuck at the login page, where the username and password are required.

### Expected result

Update the user manual with this information.

### Version environment

latest version as of 5/8/21.

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
Username is `siyuan`, password can be specified by boot parameter `--authCode`, please check the user guide for more details, thanks.
