### ISSUE TITLE
标签预览显示上下文

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#205]
### 当前环境：
- 操作系统： win10
- 思源版本：V0.2.7

### 场景描述
目前在思源中使用标签作为文档归类/查找的一种辅助方式，当前版本已实现标签所在内容块的预览。
通常标签所在行是独立的内容块。当前标签预览，不能查看上下问题，比较鸡肋。
![标签预览只能查看当前内容块](https://user-images.githubusercontent.com/15924513/95658252-9084b100-0b4b-11eb-9cca-f0aa10aa28a8.gif)

### 期望的改进
使用标签预览，类似搜索，能够查看上下文并高亮显示当前**标签**
![高亮显示当前标签，并能显示上下文](https://user-images.githubusercontent.com/15924513/95658367-6bdd0900-0b4c-11eb-8ab7-1db619843c36.gif)

**Comment by Vanessa219** [comment]
搜索和这个用途不太一样。标签上只是一个预览作用，点击就可以方便快速的打开全文进行查看了。

**Comment by lss6378** [comment]
> 
> 
> 搜索和这个用途不太一样。标签上只是一个预览作用，点击就可以方便快速的打开全文进行查看了。

我目前的用法，标签是用来**分类**及**快速搜索**。
如果使用**点击标签**操作查看全文，就会产生很多**临时页签**，出现 #183 这种情况。
如果标签预览可直接查看上下文，或者通过其他方式减少**临时页签**的产生，使用过程中体验会更好

如下图：点击标签查看过程中产生**临时页签**
![点击查看标签，产生过多页签](https://user-images.githubusercontent.com/15924513/95668219-77a7ea00-0ba3-11eb-882c-f9305e6f1473.gif)

**Comment by Vanessa219** [comment]
那我就关闭这个 issue，主攻 #183 了。

目前打开过多可以使用 ctrl+w 进行关闭
