### ISSUE TITLE
inline break omit 

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#2057]
![image](https://user-images.githubusercontent.com/11204422/119244511-0eaa3b00-bba4-11eb-8ad8-c8cec67847b3.png)
typora has this neat feature to omit inline break.
Wondering does siyuan has this setting too ? (this is critical for collaborating with somebody who uses a markdown editor like typora support this feature. I dont want to working on irregular length lines on siyuan)

**Comment by 88250** [comment]
Hello, SiYuan is not a Markdown editor, it operates blocks after v1.2.0, so it will not support this feature, thank you.
