### ISSUE TITLE
Existing docs' image problem

### ISSUE THREAD

**Issue by lowwor** [siyuan-note/siyuan#2060]
版本号：v1.2.0 Beta1
Version：v1.2.0 Beta1
v1.2.0 Beta1中去除了自动拉取图片，改用剪藏插件实现，但是对于现在已有的文档，很多图片都可能还是网络图片，但网络图片容易失效，所以希望将他们变成本地的，但现在很难知道文档中还有哪些图片是是网络的，哪些是本地的。同时，也缺少一个快捷的方法将已有文档的网络图片转换为本地图片。可否给本地图片和网络图片加个标识（如图片右上角加个小标之类的），或者类似未引用资源那样增加个网络图片列表，同时，可否增加一个手动按钮将本文章（或者所有文章的）网络图片拉取到本地的功能？
Siyuan remove auto fetch image in v1.2.0 Beta1, instead, it now use a web clipper. But for existing docs, there still remains some image referenece from web, and may expired easily. I would like to convert them to local assets, but it's hard to identify between web image and local image. At the same time, we need an more convenient way to convert existing web image asset to local image asset. Can we add a mark(like a badge on the top right corner of the image) to identify web image asset to local image asset, or something like the unreferenced asset list, a web image asset list. And we need a funtion to manual trigger auto fetch image in current doc(or all the doc).

**Comment by 88250** [comment]
本地拉取容易失败，可用性不好，这也是为什么后面要做 SiYuan Chrome Extension 的原因；已有的数据就不做处理了，如果需要查询的话可看下 `C:/Users/用户名/AppData/Local/Temp/siyuan/siyuan.db`，这是个 SQLite 数据库，里面有个表 assets，记录了所有资源文件，查询后手动处理吧，谢谢。

**Comment by lowwor** [comment]
了解，那mac上这个数据库的地址是哪个？

**Comment by 88250** [comment]
看下日志文件，里面有打印这个信息。

**Comment by lowwor** [comment]
assets表里没有，blocks表里也要过滤markdown才能出来，但是查了下，有一千多张还是网络图片的，显示是正常的，但是确实以前拉取失败没提示没注意这么多还是网络图片的，手动替换的话要裂开了，是否有其他更好的方案建议？

**Comment by 88250** [comment]
哦，抱歉我记错了，assets 表里只有本地 assets 文件夹下面的，绝对路径或者网络路径不会插入到这个表里。

用 blocks 表里的 md 的话需要自己解析，然后找个 md 处理器把 img link 提取出来，然后再写个爬虫工具抓下来，然后和数据 .sy json 里原来的 img link 对应上，同一重命名替换，大概就是这个流程。

**Comment by lowwor** [comment]
现在手动替换的做法是点图片右上的三个点，点复制图片，然后黏贴，然后删除原来的图片，我感觉在三个点里面的复制图片下暂时多加上一个拉取到本地的按钮，实现这个过程，应该比较容易实现，比我从头来一套更快一点。个人感觉现在应该有挺多用户都不知道图片还是网络图片的，可以在beta这种过度版本中暂时加个功能，方便用户在向插件迁移前做下转换。

**Comment by 88250** [comment]
拉取图片不会做的，不然以后还是有问题，见谅了。

**Comment by lowwor** [comment]
了解。
