### ISSUE TITLE
copy a sentence from word to siyuan.  the space between two words disappeared. It happened randomly.

### ISSUE THREAD

**Issue by legend053** [siyuan-note/siyuan#2062]
## Siyuan, v1.2 beta 2.

**If I copied a sentence from word to siyuan.  The space between two words disappeared. It happened randomly. Most of the time it happened at the first two words of the copied sentence. See gif below.**
![bug_report](https://user-images.githubusercontent.com/7464388/120907215-64132d00-c625-11eb-8e69-db868213c1a2.gif)

**Comment by legend053** [comment]
Here is the Word file for your reference.
[Example.docx](https://github.com/siyuan-note/siyuan/files/6603358/Example.docx)

**Comment by 88250** [comment]
Fixed in v1.2.0 beta3, thanks.
