### ISSUE TITLE
长列表加载性能优化

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2067]
当一个文档只有一个列表块，里面有超多内容时，性能需要优化（好像没法触发动态加载？）

测试用例：[长列表：《SQL语法速成手册》.zip](https://github.com/siyuan-note/insider/files/6605659/SQL.zip)

**Comment by 88250** [comment]
现在只有根这一级的块会进行动态加载，子块还不会，后面改进吧。

**Comment by 88250** [comment]
估计不会优化了，目前看没有太多需求。

**Comment by jhan3657** [comment]
蹲一波优化，目前已经遇到长列表性能问题了，加载很慢影响正常使用，希望能够考虑重开，谢谢
