### ISSUE TITLE
某一文档，滑动到最下方，会自动关闭该文档

### ISSUE THREAD

**Issue by mummer98** [siyuan-note/siyuan#2071]
### Describe the problem
有一个文档，滑动到文档最下面时，文档会自动关闭，其他文档没有出现这个问题，这个文档最后面是插入了一个word文档、一个excel表格和一个音频文件，但是这三个文档都因为assets beta 3的bug都被删掉了
> 由于不知道怎么上传附件，相关文件（操作录屏、日志、该文档）就通过邮箱发送给D大了

**Comment by 88250** [comment]
我这重现不了，等 beta4 发布以后麻烦回测，谢谢。

**Comment by mummer98** [comment]
> 我这重现不了，等 beta4 发布以后麻烦回测，谢谢。

可能测试不了了，我把那个文档删掉了

**Comment by 88250** [comment]
邮箱里应该还有，等会我发你。

**Comment by mummer98** [comment]
> 邮箱里应该还有，等会我发你。

好的，重新放到`date`下面相应文件夹内再打开，还是存在前面那个问题，等更新beta4后 再回测反馈

**Comment by 88250** [comment]
好的，那先关闭了。
