### ISSUE TITLE
Blockquote data loss

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2075]
### Describe the problem

Hello,
this is related to this [issue](https://github.com/siyuan-note/insider/issues/764)
I found this in log, and just confirming if it's gonna be fixed in beta4 ?

![image](https://user-images.githubusercontent.com/33789516/121049263-d4ea4e80-c7b7-11eb-8b5a-12ed68f97e55.png)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/121050301-09c3c900-c7eb-11eb-9fe5-e71fd8646b86.png)

I think the data is corrupted, but I am not sure how it happens.

**Comment by eslam-gomaa** [comment]
* First of all, [this issue was fixed](https://github.com/siyuan-note/siyuan/issues/2075#issuecomment-856056212) after I killed the process (I rebooted in my case)

I think I faced this before, when I  types some paragraphs that include `&` symbol, for example
![image](https://user-images.githubusercontent.com/33789516/121051636-e3396a00-c7b9-11eb-9de1-db06d8c1764d.png)

And worked normally After I removed the `&`

---

I'm not sure of this .. but I found an `&` symbol in the doc that got data loss and removed it
now will watch if it will happen again

**Comment by eslam-gomaa** [comment]
I checked the logs after I removed the `&` symbol and continued to edit the note

And did't get the error
![image](https://user-images.githubusercontent.com/33789516/121055811-e2a2d280-c7bd-11eb-8802-e288ed7bd04e.png)

**Comment by 88250** [comment]
v1.2.0-beta4 just released, please use it for testing.

**Comment by eslam-gomaa** [comment]
@88250, In beta4 i'm still getting block not found

![image](https://user-images.githubusercontent.com/33789516/121066483-3d422b80-c7ca-11eb-9cb7-a77cc0e9b5e6.png)

**Comment by eslam-gomaa** [comment]
I got many of them like before

![image](https://user-images.githubusercontent.com/33789516/121082569-92883800-c7de-11eb-8432-41b33b21c801.png)

**Comment by 88250** [comment]
> I'm not sure of this .. but I found an `&` symbol in the doc that got data loss and removed it
> now will watch if it will happen again

Sorry, I couldn't reproduce it.

Please check whether enabled the experimental feature "use existing database" in settings - about.

**Comment by eslam-gomaa** [comment]
Yes, was used

**Comment by eslam-gomaa** [comment]
Thanks will try

**Comment by eslam-gomaa** [comment]
I killed all the processes running before starting the app again, still seeing these

* Encountered page closing automatically
  * But didn't encounter data loses


```
    * resident [true]
    * arch [amd64]
I 2021/06/08 06:49:09 conf.go:209: local serve path [http://192.168.1.15:6806]
I 2021/06/08 06:49:10 database.go:97: reinitialized database [/tmp/siyuan/siyuan.db]
I 2021/06/08 06:49:10 serve.go:50: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/06/08 06:49:13 box.go:522: rebuilding database of box [siyuan-Eslam]
I 2021/06/08 06:49:19 working.go:125: kernel booted
E 2021/06/08 06:50:29 transaction.go:160: not found block [id=20210608065029-0e0yhsn]
I 2021/06/08 06:52:15 working.go:364: port [6806] is opened, try to check version of running kernel
I 2021/06/08 06:52:15 working.go:374: version of the running kernel is [1.2.0-beta4]



E 2021/06/08 07:07:34 transaction.go:160: not found block [id=20210608070733-tesiwwt]
E 2021/06/08 07:07:34 transaction.go:100: not found previous block [id=20210608070733-tesiwwt]
E 2021/06/08 07:08:03 transaction.go:160: not found block [id=20210608070802-j03xrtb]
E 2021/06/08 07:08:03 transaction.go:100: not found previous block [id=20210608070802-j03xrtb]
E 2021/06/08 07:08:05 transaction.go:160: not found block [id=20210608070803-swhvrbe]
E 2021/06/08 07:08:13 transaction.go:160: not found block [id=20210608070803-swhvrbe]
E 2021/06/08 07:08:15 transaction.go:160: not found block [id=20210608070747-z51l6w7]
E 2021/06/08 07:08:15 transaction.go:100: not found previous block [id=20210608070747-z51l6w7]
E 2021/06/08 07:08:17 transaction.go:160: not found block [id=20210608070815-p4bbb0v]
E 2021/06/08 07:08:19 transaction.go:62: not found block [id=20210608070815-p4bbb0v]
E 2021/06/08 07:08:19 transaction.go:160: not found block [id=20210608070747-z51l6w7]
E 2021/06/08 07:08:21 transaction.go:160: not found block [id=20210608070747-z51l6w7]
E 2021/06/08 07:08:22 transaction.go:160: not found block [id=20210608070747-z51l6w7]
E 2021/06/08 07:08:30 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:31 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:33 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:36 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:46 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:47 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:48 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:51 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:52 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:08:59 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:04 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:09 transaction.go:160: not found block [id=20210608070747-z51l6w7]
E 2021/06/08 07:09:09 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:09 transaction.go:160: not found block [id=20210608070747-z51l6w7]
E 2021/06/08 07:09:11 transaction.go:160: not found block [id=20210608070909-0hxuft1]
E 2021/06/08 07:09:16 transaction.go:160: not found block [id=20210608070909-0hxuft1]
E 2021/06/08 07:09:21 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:24 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:28 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:42 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:44 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:47 transaction.go:160: not found block [id=20210608070909-0hxuft1]
E 2021/06/08 07:09:47 transaction.go:62: not found block [id=20210608070909-0hxuft1]
E 2021/06/08 07:09:47 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:48 transaction.go:62: not found block [id=20210608070748-erngxod]
E 2021/06/08 07:09:48 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:53 transaction.go:160: not found block [id=20210608070951-5x4fndn]
E 2021/06/08 07:09:54 transaction.go:160: not found block [id=20210608070951-5x4fndn]
E 2021/06/08 07:09:56 transaction.go:160: not found block [id=20210608070951-5x4fndn]
E 2021/06/08 07:09:58 transaction.go:160: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:09:59 transaction.go:160: not found block [id=20210608070951-5x4fndn]
E 2021/06/08 07:10:01 transaction.go:62: not found block [id=20210608070747-z51l6w7]
E 2021/06/08 07:10:01 transaction.go:62: not found block [id=20210608070821-twezhfr]
E 2021/06/08 07:10:01 transaction.go:160: not found block [id=20210608070951-5x4fndn]
E 2021/06/08 07:10:02 transaction.go:160: not found block [id=20210608070951-5x4fndn]
E 2021/06/08 07:10:02 transaction.go:100: not found previous block [id=20210608070951-5x4fndn]

```

**Comment by eslam-gomaa** [comment]
Got to more issues

1 -- See this error when rebooting the app on linux
![image](https://user-images.githubusercontent.com/33789516/121128612-f5ec8700-c82b-11eb-81e8-cae68e74ac20.png)

I must kill the process in order to work well
```
pkill siyuan
```

---

2 -- After rebooting the app, I found data missing from the note I was working on with nothing in logs ! :cry:

**Comment by eslam-gomaa** [comment]
Still getting data losses, will rollback to beta2 temporarily

**Comment by 88250** [comment]
> I 2021/06/08 06:52:15 working.go:364: port [6806] is opened, try to check version of running kernel
> I 2021/06/08 06:52:15 working.go:374: version of the running kernel is [1.2.0-beta4]

Kill process `SiYuan Kernel`.

**Comment by eslam-gomaa** [comment]
ok

**Comment by eslam-gomaa** [comment]
Hello @88250 

I think the issue is in the save mechanism, (as I understand) it tries to save in real time. and maybe the issue happens when I add new content it saving happens at the same time

#### 2 issues happen
* page closes automatically
* data loses (maybe didn't show up in the recording but happens)

![new](https://user-images.githubusercontent.com/33789516/121305563-040ad800-c8fe-11eb-8b70-2c349a0f572a.gif)

**Comment by 88250** [comment]
Thank you for helping to find this problem, I can reproduce the data loss on the Blockquote block.

**Comment by eslam-gomaa** [comment]
I'm happy to hear that, Thanks
