### ISSUE TITLE
自定义加密备份存放路径

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2077]
现在的正在使用的文件和备份文件好像都是存储在同一个siyuan文件夹下,能否允许自定义备份位置.以节省特定位置空间的占用(我的siyuan文件夹是放在icloud的同步文件夹里的,所以空间会紧张)

**Comment by 88250** [comment]
思源有两种备份：

* 编辑历史，在笔记本文件夹/.siyuan/backup/
* 加密备份，在工作空间文件夹/backup/

老铁觉得两个都需要配置吗？

**Comment by GuoYimingac** [comment]
编辑历史肯定要保持在笔记本文件夹里面,主要是加密备份最好能够自定义,这样会方便一点

**Comment by 88250** [comment]
好的，那我们先支持加密备份的路径配置。
