### ISSUE TITLE
Blank Block Jitter

### ISSUE THREAD

**Issue by Clouder0** [siyuan-note/siyuan#2079]
### Describe the problem

Once a blank block exists, all the blocks under it would jitter when the cursor moves.

![visual2](https://user-images.githubusercontent.com/41664195/121120497-3e1da080-c850-11eb-9654-4e028fd3131b.gif)

![visual3](https://user-images.githubusercontent.com/41664195/121120641-8dfc6780-c850-11eb-9727-d76edb4c5fcd.gif)

### Version environment

* Version: v1.2.0-beta4
* Operating system: Manjaro KDE

**Comment by 88250** [comment]
I could'nt reproduce it, please try reset appearance and keymap, thanks.

**Comment by Clouder0** [comment]
It's my problem. Electron v11.3.0 was used by me to package SiYuan Web thus leading to this issue. After upgrading to v13.1.0, the jitter just disappeared.
