### ISSUE TITLE
行内公式在一行之首时无法缩到上一行

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2083]
如题,体验很不好,选取不了,剪切公式代码,另外在上一行创建一个行内公式,下面那个行内公式会把后面的文字全部吞进去

https://user-images.githubusercontent.com/77337499/121145079-2c002a00-c871-11eb-8d10-23f2ee8f67e9.mov

**Comment by GuoYimingac** [comment]
之前反应过,但是几个版本后这个问题还是存在,挺烦的

**Comment by 88250** [comment]
调整了一下，但是不确定是否已经能够达到期待，请等 beta5 发布以后帮忙回测反馈，谢谢。
