### ISSUE TITLE
select all and delete bug

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2084]
### Describe the problem

select all and delete bug, (Also happens when selecting all and type text)

* In the test, not all the text is deleted, ans although it's shown as deleted, when I re open the page I still can see parts of the text

![select all](https://user-images.githubusercontent.com/33789516/121145320-1e31b100-c83f-11eb-9ad9-c3a513c8aa90.gif)

---
And there is nothing in logs

![image](https://user-images.githubusercontent.com/33789516/121145930-bcbe1200-c83f-11eb-8191-ca6f27f39c18.png)

**Comment by 88250** [comment]
It's a bug as the same as #2075 , thank you very much.

**Comment by eslam-gomaa** [comment]
Hello @88250 ,  I think it's not the same issue as [2075](https://github.com/siyuan-note/siyuan/issues/2075)

**Comment by 88250** [comment]
After v1.2.0-beta5 released, please test it, thanks.
