### ISSUE TITLE
问题:加粗的时候如果选中已经加粗的文件,会将原有加粗内容取消,感觉不大好

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2085]
https://user-images.githubusercontent.com/77337499/121146681-c14fee00-c872-11eb-8da0-60e3ce163939.mov

**Comment by 88250** [comment]
行级排版的交叉、包含后面再做，谢谢反馈。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2911
