### ISSUE TITLE
按住ctrl点击文档块链接，如果是空文档，就不会打开。

### ISSUE THREAD

**Issue by wfan14513** [siyuan-note/siyuan#209]
有内容的文档没有问题，会另开一个页签打开。

**Comment by Vanessa219** [comment]
是这样操作么？好像不行
![QQ20201011-120245-HD](https://user-images.githubusercontent.com/970828/95670060-cceef600-0bb9-11eb-8b56-c98cde1bb93e.gif)

**Comment by wfan14513** [comment]
嗯，我又试了下，发现是那些可能“损坏”的链接不行，但是我忘了怎么搞的了，这两天用得比较多。
“损坏”的意思就是，鼠标悬停上去没有反应，不像你这个图里还能浮现个框。
没法复现了，先把这个issue关了吧，影响不大，找到规律再说。

**Comment by Vanessa219** [comment]
好的，多谢。
