### ISSUE TITLE
标题块带下方块折叠和移动

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2097]
https://github.com/siyuan-note/insider/issues/68

**Comment by deerainw** [comment]
记得测试折叠后的块移动快捷键😂

**Comment by 88250** [comment]
> 记得测试折叠后的块移动快捷键😂

我突然忘记这个快捷键指的是啥了，能提示一下么？  😂

**Comment by Achuan-2** [comment]
> > 记得测试折叠后的块移动快捷键😂
> 
> 我突然忘记这个快捷键指的是啥了，能提示一下么？ 😂

Ctrl+shift+up/down
