### ISSUE TITLE
支持设置页签打开最大数量

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2098]
https://github.com/siyuan-note/insider/issues/626

默认值为 `12`

**Comment by SeyeeL** [comment]
好的，希望增加标签窗口的数量显示，谢谢

**Comment by snipersteve** [comment]
页签是我理解的tab吗？我设置为1之后，还是有多tab显示，不知何故。
<img width="1091" alt="_20220627135816" src="https://user-images.githubusercontent.com/834498/175869732-5cc32a64-685f-4453-a8ed-72c00c3c6853.png">
