### ISSUE TITLE
建议:独立字体设置

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2099]
现在的字体设置算是写在CSS里的,每次升级CSS文件必须重新把这一块的颜色改掉,能不能独立出来,允许在软件配置字体的颜色,背景色,不随主题而改变,这样对于对CSS陌生的用户比较友好,也能保持笔记在不同主题下的统一性(不然会出现几个主题中颜色比一样)
![截屏2021-06-10 上午9 39 14](https://user-images.githubusercontent.com/77337499/121451287-e60da800-c9cf-11eb-8a16-9f9fc1b5a05b.png)

**Comment by 88250** [comment]
这样设计是为了和主题搭配，不然可能会影响整体效果。所以就不改了，谢谢。
