### ISSUE TITLE
滚动条鼠标悬停图标更改

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#21]
滚动条较窄，希望鼠标悬停时图标有更改。
![M}6AD$)3)77DH(%37}OATEC](https://user-images.githubusercontent.com/66795040/94168716-7fd40a00-fec0-11ea-86d0-3f6843f3ebf0.jpg)

**Comment by wbooooooo** [comment]
刚看到qq，我觉得qq也很巧妙，他用了改变滚动条颜色的办法，也不失为一个思路，毕竟滚动条离边框太近，移动距离很短，图标变三回。。。但是有可能对theme有影响，开发者定夺。。。

**Comment by 88250** [comment]
v0.2.2 修复。
