### ISSUE TITLE
⚠️ Data losses

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2101]
### Describe the problem

continuing on this [issue](https://github.com/siyuan-note/siyuan/issues/2075),

I've avoided blockquotes since it was obvious that the issue is in blockquotes, **But I've encounted a data loss just now !**

![image](https://user-images.githubusercontent.com/33789516/121466390-a9ce4d80-c9b7-11eb-86c7-311f93ff158d.png)

---

some paragraphs and images are missed from the page

**Comment by 88250** [comment]
Please keep watching after v1.2.0-beta5 released, thank you.

**Comment by eslam-gomaa** [comment]
@88250

for Quoteblocks issue, it seems to be solved.

I've encountered very few data losses (Maybe 1 or 2 since the last release) but couldn't reproduce them.

**Comment by 88250** [comment]
@eslam-gomaa 

We have fixed a potential defect that may cause data loss in beta6. The issue remains open. Please help to observe for a while, thank you very much!

**Comment by eslam-gomaa** [comment]
Ok, sure

**Comment by eslam-gomaa** [comment]
#### A strange case

When I resize the picture and close the page, and I open it again the image back to the original size

![image](https://user-images.githubusercontent.com/33789516/121838163-88cb6c80-ccd7-11eb-9aca-b802b39930e7.gif)

**Note**: Tried to test the image out of quoteblock but got the same result

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2101#issuecomment-860349630 Fix in beta7, thanks.

**Comment by eslam-gomaa** [comment]
@88250 

FYI, I'm getting small data losses, but can't track the reason

**Comment by 88250** [comment]
Did you encounter it while copying and pasting?

**Comment by eslam-gomaa** [comment]
most of them yes, but can't be 100% sure

**Comment by 88250** [comment]
v1.2.0-beta7 fixed a bug about pasting, please test it, thank you.

**Comment by eslam-gomaa** [comment]
Hello @88250 

FYI, I didn't see any `not found block` since beta7

**Comment by 88250** [comment]
Hello，@eslam-gomaa 

In other words, has no data loss been found yet?

**Comment by eslam-gomaa** [comment]
yes, didn't encounter data losses

**Comment by 88250** [comment]
Ok, thank you, we close this issue.
