### ISSUE TITLE
多窗口分栏区别的页签减淡样式，单窗口也会应用

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#2111]
![image](https://user-images.githubusercontent.com/60436214/121607659-00ed2480-ca83-11eb-8ef4-243eeeee2330.png)
自从添加了多窗口区分的效果后，一直有一个问题，点击旁边的大纲或者其他非编辑器区域，编辑器页签就会整个变暗（也就是单窗口也会应用上未激活页签的样式）带来额外的干扰，希望能优化一下

**Comment by Vanessa219** [comment]
这是一个特性，后续需要在确定用户专注在哪一个面板上，以便使用快捷键进行快捷操作。
