### ISSUE TITLE
结合 shift↑ 为块添加展开/折叠快捷键 ⌘↑

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2114]

**Comment by Creling** [comment]
从beta6的菜单来看，快捷键是`ctrl + ↑`，不是`shift + ↑`。

![image](https://user-images.githubusercontent.com/43109504/122001861-89512980-cde3-11eb-8b2a-239d99166800.png)

**Comment by Vanessa219** [comment]
标题说的是结合shift + ↑，快捷键还是  ⌘↑
