### ISSUE TITLE
图片居中以后，同一段落输入文本，图片的居中会被取消

### ISSUE THREAD

**Issue by EndlessErrors** [siyuan-note/siyuan#2117]
图片居中以后，同一段落（图片前或后）输入文本，图片的居中会被取消

期望：文本的输入不影响图片是否居中。

beta5

**Comment by 88250** [comment]
一个图片只有独占一行（独占一个段落块）时才能居中， 这个问题是设计缺陷，暂时不考虑改进了，谢谢。

**Comment by 88250** [comment]
v1.2.0-beta6 改进，谢谢。
