### ISSUE TITLE
能否支持类似html的图片大小和位置定义

### ISSUE THREAD

**Issue by xmu714** [siyuan-note/siyuan#2118]
### In what scenarios do you need this function?

需要可以像html一样排版图片，定义图片宽度和高度，以及左右和居中的位置

### Describe the optimal solution

可以直接支持html的图片语法

### Describe the candidate solution

或者在插入图片的工具上提供填入数值和位置的功能

### Other information

先前在md文件里用html写好了大小和位置的图片，转换之后全乱了，还得手动拖拽，但是这样的话就和word一样，排版上就要浪费太多时间，偏离了内容本身

**Comment by 88250** [comment]
你好，图片目前已经支持居中和缩放，细节后续会逐步完善。HTML 短期内不会支持了，非常抱歉。

**Comment by xmu714** [comment]
> 你好，图片目前已经支持居中和缩放，细节后续会逐步完善。HTML 短期内不会支持了，非常抱歉。

我在右键菜单里面只看到了居中没有看到缩放，或许是指的那个拖拽？但是现在那个很难用，轻轻一点就变成了图片预览，没法修改，然后两张图我拖到一块，结果只有第一章可以缩放，第二张没有缩放箭头出来。

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/121709756-743a7900-cb0b-11eb-8c10-a9e1cc481c5e.gif)
