### ISSUE TITLE
行内公式,问题复现

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2121]
https://user-images.githubusercontent.com/77337499/121760543-eb98f880-cb5d-11eb-913a-9fb04d8adaf0.mov

很神奇又出现了

**Comment by Vanessa219** [comment]
没太看明白，麻烦再细说一下

**Comment by GuoYimingac** [comment]
当行内公式在第一个位置时,光标无法到达这一行的最前面

**Comment by GuoYimingac** [comment]
https://github.com/siyuan-note/siyuan/issues/2083

**Comment by Vanessa219** [comment]
收到
