### ISSUE TITLE
横排分栏宽度调整

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2125]
什么时候能够支持这个功能

https://user-images.githubusercontent.com/77337499/121804294-3313a780-cc78-11eb-958f-25071a5c25cd.mov

**Comment by Vanessa219** [comment]
先简单支持下
![image](https://user-images.githubusercontent.com/970828/121807148-8d673500-cc85-11eb-862e-457cc44221cd.png)
