### ISSUE TITLE
设置中点击资源后无法进行其他操作

### ISSUE THREAD

**Issue by yunfei97** [siyuan-note/siyuan#2127]
### Describe the problem

![image](https://user-images.githubusercontent.com/32860548/121811744-dfb15180-cc97-11eb-9b7d-9dbc7944b194.png)
无法点击其他设置选项

### Version environment

* Version: beta6
* Operating system: Windows10

**Comment by 88250** [comment]
谢谢反馈，https://github.com/siyuan-note/siyuan/issues/2126 处理。
