### ISSUE TITLE
文档数据文件名使用 ID

### ISSUE THREAD

**Issue by Rubbi5hThird** [siyuan-note/siyuan#2131]
文件名的问题, windows 下面默认不区分大小写的, Linux 是区分的, 这里会不会有 bug  ?
目前思源的状态是标题当文件名, 我觉得会有问题, 是不是改成不在以标题保存, 而是是 id 保存, id 对应文件名

**Comment by 88250** [comment]
你好，我觉得应该没有问题吧 👀

**Comment by Rubbi5hThird** [comment]
linux 和 win 文件名的识别会有匹别，标题即文件名的设定会在一些场景上会有问题，还是希望会支持这个 feature.
TKS
