### ISSUE TITLE
Add refresh button on the bookmark toolbar

### ISSUE THREAD

**Issue by Creling** [siyuan-note/siyuan#2149]
### Describe the problem

Bookmark window will not refresh automatically when I add/remove/edit bookmarks of some article until I reboot Siyuan fully.

### Expected result

Bookmark window ought to refresh automatically when I add/remove/edit bookmarks of some article. 

### Screenshot or screen recording presentation

![PmGzf2BgBz](https://user-images.githubusercontent.com/43109504/122154274-320c9100-ce97-11eb-8ac4-a476df2d96fd.gif)

### Version environment

* Version: v1.2.0-beta6
* Operating system:  windows

**Comment by 88250** [comment]
We will add a refresh button on the bookmark toolbar, thanks.
