### ISSUE TITLE
支持导入 CSL-JSON 进行文献引用

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2152]
BibJSON 或者 CSL-JSON 应该只用支持一种即可？

**Comment by Creling** [comment]
+10 for bibtex

**Comment by wazili** [comment]
工作流
可以参考一下[如何用markdown写学术论文？（VScode+zotero+pandoc）_哔哩哔哩_bilibili](  https://www.bilibili.com/video/BV1pq4y1u7ap?spm_id_from=333.999.0.0  )    

zotero的经典插件
[Cite as you Write :: Better BibTeX for Zotero](  https://retorque.re/zotero-better-bibtex/citing/cayw/  )

**Comment by Gold-ingot** [comment]
请问该功能该如何使用？能否简单介绍？

**Comment by yanyu2015** [comment]
提供一个其他的项目供参考:
`https://github.com/melat0nin/zotero-roam-export`

**Comment by Geo123abc** [comment]
这个是ob 那边的一个插件，可以参考一下  [stefanopagliari/bibnotes](  https://github.com/stefanopagliari/bibnotes  )

**Comment by 88250** [comment]
抱歉各位，这个特性目前不再考虑了，等[前端 API](https://github.com/siyuan-note/siyuan/issues/5066) 开放以后再看情况，感谢理解。

**Comment by Geo123abc** [comment]
[WingDr/siyuan-plugin-citation: A citation plugin for the SiYuan Note.](  https://github.com/WingDr/siyuan-plugin-citation  )    

[思源笔记文献引用插件 siyuan-plugin-citation - 链滴](  https://ld246.com/article/1688908419920  )    

[思源笔记文献引用插件siyuan plugin citation：思源笔记也可以快捷插入参考文献啦，还能方便导出为Word（ing），在Word中还能增、改、删_哔哩哔哩_bilibili](  https://www.bilibili.com/video/BV17u411j79z/  )

**Comment by Geo123abc** [comment]
[[【乱侃】使用 markdown 软件 +zotero 进行学术写作的一些经验 - 链滴](https://ld246.com/article/1687500970083)](https://ld246.com/article/1687500970083  )

[Siyuan 文献管理插件，实现与 Zotero 无缝对接 - 链滴](  https://ld246.com/article/1689296953335  )
