### ISSUE TITLE
命名及备注标识被遮挡

### ISSUE THREAD

**Issue by DonSudo** [siyuan-note/siyuan#2153]
版本：V1.2 beta7

Bug：命名及备注标识被遮挡——经测试，所有块的命名及备注标识都会被遮挡一半，即便上一行是空行也会如此，如下图所示：

![image](https://user-images.githubusercontent.com/53081419/122217545-17aad580-cee0-11eb-92e3-e7f1b8861bb3.png)

**Comment by Vanessa219** [comment]
同 https://github.com/siyuan-note/siyuan/issues/2155
