### ISSUE TITLE
公式块复制图片按钮指向上一个公式块(还错位了....)

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2167]
https://user-images.githubusercontent.com/77337499/122570635-7efe8c00-d07e-11eb-8f98-60c2e21651ad.mov

**Comment by GuoYimingac** [comment]
我的意见是改成一键生成svg图像并替换,同时在文件里面保留代码,允许之后修改只用,这样可以同时保留编辑能力,同时减轻电脑渲染latex的压力

**Comment by Vanessa219** [comment]
这个只是为了粘贴到其他不支持数学公式的网站。如果替换成图片，使用数学公式多的人就要存放大量图片了。最后图片的管理删除都会很麻烦。

**Comment by Vanessa219** [comment]
没有办法重现，还麻烦发一下 .sy 文件

**Comment by 88250** [comment]
暂时没有进一步反馈，先关闭了。
