### ISSUE TITLE
高亮排版时删除内部多余的空格

### ISSUE THREAD

**Issue by youth54** [siyuan-note/siyuan#2169]
### Version environment

* Version: 1.2.0 beat8
* Operating system: Windows 10
* Browser (if used): 

导出的结果如下图
![image](https://user-images.githubusercontent.com/72968849/122574658-76a85000-d082-11eb-9720-fc466141c81d.png)

**Comment by 88250** [comment]
你好，导出的格式是？

**Comment by youth54** [comment]
> 你好，导出的格式是？

试了PDF和html，都有这个问题

**Comment by 88250** [comment]
我这里重现不了问题，方便的话请发一下 .sy 文件，谢谢。

**Comment by youth54** [comment]
好的
[高亮-beat8.zip](https://github.com/siyuan-note/siyuan/files/6687141/-beat8.zip)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/123131625-704e1580-d480-11eb-9590-5d69323fa069.png)

这个地方多了一个空格，beta10 里会进行改进，自动删除多余空格，谢谢。
