### ISSUE TITLE
整段文字加颜色着重,行内公式上移

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2170]
![截屏2021-06-19 上午11 08 45](https://user-images.githubusercontent.com/77337499/122629331-c58bcf00-d0ee-11eb-88e2-0b42ec7b9c1c.png)

**Comment by Vanessa219** [comment]
无法重现，可以的话，发一下原文。
![image](https://user-images.githubusercontent.com/970828/122672711-a29d1000-d1ff-11eb-9a9f-bae198324ca7.png)

**Comment by Vanessa219** [comment]
可以重现了，下个版本修复。
