### ISSUE TITLE
copy individual image locally

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2171]
### In what scenarios do you need this function?

Hello,

When I copy individual image from the browser it's not downloaded locally, is it possible to allow to fetch individual images with `ctl` + `shift` + `v` ? (not talking about full posts)

![image](https://user-images.githubusercontent.com/33789516/122630713-2ce15900-d0c6-11eb-9608-49a9da506503.png)

**Comment by Vanessa219** [comment]
If only copy img, ctrl+v should paste it locally.
