### ISSUE TITLE
开启浏览器访问鉴权后登录提示“unauthenticated”，需多次刷新页面才能进入主界面

### ISSUE THREAD

**Issue by risoyo** [siyuan-note/siyuan#2176]
### Describe the problem

docker部署，版本为1.2.0-beta8，在开启了浏览器访问鉴权后，登录时在确定密码正确的情况下多次提示“unauthenticated”,再点击确定后无反应，在web的init界面转圈圈，需要F5刷新，可能会继续弹出“unauthenticated”，继续点击确定并刷新3-5次才能进入主界面

### Expected result

输入密码后正常登录

### Screenshot or screen recording presentation
已开启浏览器访问鉴权

![image](https://user-images.githubusercontent.com/11912562/122660035-51b1fb00-d1b0-11eb-9966-29af2c293774.png)

输入正确的用户名密码并点击确定后提示“unauthenticated”

![image](https://user-images.githubusercontent.com/11912562/122659987-e1a37500-d1af-11eb-9659-3ecdb6986180.png)

多次刷新并点击“unauthenticated”的确定后进入主界面

![image](https://user-images.githubusercontent.com/11912562/122660137-735fb200-d1b1-11eb-9991-04b346732496.png)

### Version environment

* Version: 1.2.0-beta8
* Operating system: 服务器为CentOS 7.6 64bit，客户端浏览器系统为Windows10-2020H1、macos 11.4 big sur
* Browser (if used): chrome89、edge91、Safari

### Log File

日志文件无异常

![image](https://user-images.githubusercontent.com/11912562/122660078-c71dcb80-d1b0-11eb-918b-a1096c5b9a3f.png)

### More information

此问题在1.1.X版本已存在，经过对docker image的回溯，已保存的1.1.8.1~1.1.8.3均存在此问题，1.1.6无此问题，由于未保存1.1.7和1.1.8的docker镜像，故无法验证是在1.1.7中出现的还是在1.1.8中出现的bug

**Comment by 88250** [comment]
你好，浏览器端是 macOS 么？

**Comment by risoyo** [comment]
> 你好，浏览器端是 macOS 么？

d大您好，提交issue时是使用的MacOS，平时主力机是使用的Windows，均存在此问题，复现此问题最方便的是使用ios的Safari，电脑端（Windows和MacOS）点击刷新几次之后还可以进入主界面，但是iOS的Safari端不管怎么刷新都进不去，一直提示“unauthenticated”

昨天在分析是哪个版本的image出现这个问题时，是采用每次都删除所有的conf、data文件的方式来排除conf中的设置的影响，在1.1.6中无此问题，到1.1.8.1就有了，今天将数据迁移到1.2.0-beta8，依然存在此问题

文件夹的权限方面，各个文件夹权限用户如下：
siyuan为部署docker时的映射目录
``` 
nohup docker run -v /home/dockerData/siyuan:/siyuan/workspace -p 6806:6806 b3log/siyuan --resident=true --workspace=/siyuan/workspace/ &
``` 

![image](https://user-images.githubusercontent.com/11912562/122660371-9723f780-d1b3-11eb-9489-f0b778ca2d1b.png)

![image](https://user-images.githubusercontent.com/11912562/122660389-d2262b00-d1b3-11eb-991f-08dff6ce3120.png)
![image](https://user-images.githubusercontent.com/11912562/122660396-db16fc80-d1b3-11eb-9872-0971494066b0.png)
![image](https://user-images.githubusercontent.com/11912562/122660404-e1a57400-d1b3-11eb-8272-dc2c3c44dc3b.png)

**Comment by 88250** [comment]
Safari 上的确有这个问题，目前仅支持 Chrome。

后面会在做锁屏密码 #1139 时一并解决，这个我先关闭了，感谢帮忙确认问题。
