### ISSUE TITLE
网页（chrome）上多行的代码块拷贝到思源的时候会变成一行。

### ISSUE THREAD

**Issue by yeahmat3** [siyuan-note/siyuan#2177]
### Describe the problem

网页上多行的代码块拷贝到思源的时候会变成一行。目前只测试了chrome浏览器，从stackoverflow上拷贝会出现此问题，请排查兼容性。

### Version environment

* Version: beta1.8
* Operating system: win10
* Browser (if used): chrome

**Comment by 88250** [comment]
麻烦给一个测试网址，谢谢。

**Comment by sundancing** [comment]
> 麻烦给一个测试网址，谢谢。

应该是通用的问题，但是复现的一个细节条件是，需要有其他块一起复制，不要单单复制代码块。

**Comment by 88250** [comment]
剪藏可优先考虑使用 https://github.com/siyuan-note/siyuan-chrome 谢谢。
