### ISSUE TITLE
代码块在缩小字体字号时，左边有部分内容被隐藏，整体往左偏移了一些像素。

### ISSUE THREAD

**Issue by yeahmat3** [siyuan-note/siyuan#2178]
### Describe the problem

代码块在缩小字体字号时，左边有部分内容被隐藏，整体往左偏移了一些像素。

### Version environment

* Version: v1.2.0-beta8
* Operating system: win10
* Browser (if used): chrome 91

**Comment by Vanessa219** [comment]
没有截图，但应该说的是这个问题吧 https://ld246.com/article/1624600352400 ？
