### ISSUE TITLE
建议新增一个关闭所有不活跃标签的快捷键，可以借用TC的ctrl+shift+w

### ISSUE THREAD

**Issue by yeahmat3** [siyuan-note/siyuan#2179]
### In what scenarios do you need this function?

建议新增一个关闭所有不活跃标签的快捷键，可以借用TC的ctrl+shift+w

**Comment by 88250** [comment]
你好，“不活跃标签”指的是？

**Comment by yeahmat3** [comment]
> 你好，“不活跃标签”指的是？

不是当前编辑器的页面，是指其余的页面。
目前可用的快捷键是ctrl+w关闭当前页面，相对应的，ctrl+shift+w是关闭除了当前编辑页面外其余的页面。

**Comment by 88250** [comment]
这个暂时不加快捷键了，主要是参考 Chrome 的，谢谢。
