### ISSUE TITLE
when creating new lines in the middle of `todo list` it should convert the second new line to a paragraph

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2180]
### Describe the problem

when creating new lines in the middle of `todo list` it should convert the second new line to a paragraph (Like **test 2** (At the end of the `todo list`) ) 

![19](https://user-images.githubusercontent.com/33789516/122663051-ff64e000-d197-11eb-9e70-34b8fb48b2e6.gif)

**Comment by Vanessa219** [comment]
This feature refers to https://workflowy.com/
