### ISSUE TITLE
代码块实时渲染问题

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#219]
当代码块预览开关打开时，虽然支持了代码的实时预览，但是编辑代码块的时候，分割成了两部分，编辑体验并不是很好。
当开关关闭时，虽然编辑时变成了一块，但是不编辑的时候，也不支持实时渲染了。
总体来说体验并不是很友好。typora 的代码块体验就挺好的，不知道后续会不会进行借鉴和优化。

**Comment by HaujetZhao** [comment]
我也希望能实现 Typora 那样的渲染方式 😆

**Comment by 88250** [comment]
暂时忽略，这个要等很久以后可能才能改进了。
