### ISSUE TITLE
引用标题时连带引用标题下的内容而非仅引用标题

### ISSUE THREAD

**Issue by DonSudo** [siyuan-note/siyuan#2190]

**Comment by 88250** [comment]
你好，目前应该就是这样的，具体是有什么疑问么？

**Comment by DonSudo** [comment]
> 你好，目前应该就是这样的，具体是有什么疑问么？

后续回考虑连带引用标题下的内容吗，类似Obsidian

**Comment by 88250** [comment]
我不太明白你的意思，方便的话麻烦截图或者录屏说明，谢谢。

**Comment by DonSudo** [comment]
![image](https://user-images.githubusercontent.com/53081419/122859006-df771d00-d34d-11eb-869b-70db8ca5b71d.png)

![image](https://user-images.githubusercontent.com/53081419/122859051-f3228380-d34d-11eb-8162-54491253305a.png)

**Comment by 88250** [comment]
标题引用的话选择 `H` 的块标的就是标题了，鼠标悬浮这个块引链接会连带标题下的块一起展示的。

**Comment by DonSudo** [comment]
> 标题引用的话选择 `H` 的块标的就是标题了，鼠标悬浮这个块引链接会连带标题下的块一起展示的。

🆗确实是这样
