### ISSUE TITLE
全局快捷键无法取消

### ISSUE THREAD

**Issue by Borluse** [siyuan-note/siyuan#2194]
### Describe the problem

全局快捷键无法取消，因为和我的ide快捷键冲突，非常影响工作。

### Expected result

全局快捷键应该能取消。事实上，我认为思源很多的快捷键并不需要是全局的，应用内就足够了。而全局的，应该能人为的去掉。例如alt+m，会自动打开思源，但是我的ide里alt+m是函数搜索，只要思源开着，我就完全无法工作。
以前版本是可以取消掉，更到1.2-beta8后，完全无法去掉了。

### Screenshot or screen recording presentation

无

### Version environment

* Version: 1.2.0-beta8
* Operating system: win10
* Browser (if used):

**Comment by Vanessa219** [comment]
重置一下快捷键就可以了。

**Comment by Borluse** [comment]
@Vanessa219 试了一下确实可以。不过你们是不是考虑下那个按钮改为 “应用” 或者 ”保存“ ？我以为是重置所有的快捷键。
