### ISSUE TITLE
建议实现闭环的文件管理功能

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#22]
文件管理目前还缺乏几个方面：
1、文件/文件夹的移动。参考第二条。。。
2、文件的复制、粘贴。因为复制粘贴不可重复，不可换根文件夹，建议不要用普通的复制粘贴功能，直接用移动至...，复制至...。直接限制移动操作只能在根目录内的文件夹、子文件夹进行。并在说明文档种详细列明，移动、复制对引用产生的潜在影响。如："移动文件并不会对引用产生影响。复制后，若删除原文档，则会使原引用失效。"并在删除一个文档的时候，自动扫描文档是否存在引用关系，给出提示”此文档存在被引用关系，若删除所有引用将会失效，是否确认删除？“
3、软删除建议增加回收站。但是因为不同根目录删除文件文件夹不同，回收站要么就一个根目录一个，要么就要提示一下目录。
4、文件夹管理存在bug，如果我删除一个A文件夹，产生A.deleted，此时我新建A文件夹，再删除，会报错。无法删除，建议有一个功能，比如把A.deleted直接改名？文件没测试，不知道是否会有类似问题。
通过实现闭环的文件、文件夹管理，减少从资源管理器进入的问题。

**Comment by wbooooooo** [comment]
我想了一下，那个关于文件夹关系的说明应该说明这几点:1，文件与文件夹不可跨根目录移动，文件或文件夹的移动不影响文件的链接关系。2，复制文件或文件夹等同于导出，可以跨根目录复制。复制可以通过预览/导出设置进行设置。复制操作产生的所有新文件没有任何已存在的链接与被链接的关系。3，对于已有链接关系的文件或文件夹，删除后所有相关的链接关系将无效，强烈建议谨慎删除。4，对于已删除进入回收站的文档，从回收站恢复，链接关系也会同时恢复。
第四步需要保证.deleted 文件恢复后也不会有重名。

**Comment by 88250** [comment]
我们先把软删除重命名重复这个问题解决，感谢提议。

**Comment by 88250** [comment]
v0.3.5 实现了移动文档，至此基本已经实现了文件管理的基础功能了，感谢反馈，我关闭了。
