### ISSUE TITLE
todo内容块 内容和方块标记不对齐

### ISSUE THREAD

**Issue by harukaze33** [siyuan-note/siyuan#2207]
### Describe the problem

todo内容块 内容和方块标记不对齐

### Expected result

对齐todo的方块和对应的内容

### Screenshot or screen recording presentation

https://user-images.githubusercontent.com/82687346/123204730-3e25cd80-d4eb-11eb-9bb0-810448bbf7e1.mov

### Version environment

* Version: 当前版本 v1.2.0-beta9 / Kernel v1.2.0-beta9
* Operating system: MacOS 11.1
* Browser (if used):

**Comment by 88250** [comment]
你好，我这里重现不了问题，请试下重置外观，设置 - 外观 - 恢复默认窗口。

**Comment by Vanessa219** [comment]
收到了字体大小的影响，下个版本改进
