### ISSUE TITLE
打开笔记本时新增导入流程

### ISSUE THREAD

**Issue by jxjxjhjh** [siyuan-note/siyuan#221]
T15.MD
会多出 T15_20201012212413-ee7zrj6.sy.md
这种

**Comment by 88250** [comment]
你好，这是思源处理导入已有 .md 的逻辑，是正常现象，具体细节请看用户指南导入相关章节，谢谢。

**Comment by Vanessa219** [comment]
还是应该解决下，比如导入到什么位置。

**Comment by LiWenGu** [comment]
放.siyuan目录下就挺好

**Comment by 88250** [comment]
新增导入流程，打开本地文件夹时判断是否存在 .sy.md：

* 如果存在（出现一个该文件名）则继续走目前的处理流程，即扫描 .md 并完成自动导入
* 如果不存在则认为是完全从已有 Markdown 文件夹进行导入，需要让用户指定目标文件夹路径，即指定导入完成后 .sy.md 存放的文件夹路径

**Comment by jxjxjhjh** [comment]
> 新增导入流程，打开本地文件夹时判断是否存在 .sy.md：
> 
> * 如果存在（出现一个该文件名）则继续走目前的处理流程，即扫描 .md 并完成自动导入
> * 如果不存在则认为是从标准 Markdown 文件夹进行导入，需要让用户指定目标文件夹路径，即指定导入完成后 .sy.md 存放的文件夹路径

没看明白，意思就是没办法解决吗？.sy.md文件必须和我已有的.md文件在同一个目录？

**Comment by 88250** [comment]
@jxjxjhjh 现在如果已经是这样的话只能手动过滤一下文件，手动移动位置了，抱歉。

**Comment by jxjxjhjh** [comment]
这个设置逻辑是有问题的，用户使用本地编辑器的前提是本身使用的文件式管理方式，他要通过文件目录和一个个文件来识别管理自己的数据。
一打开软件没有任何提示直接给用户打开文件的目录来一个全盘扫描然后生成副本文件，我还好不到100个文件，手动删也还行，要是我有数百上千文件就很麻烦了。
就像其他人提的建议，软件生成的文件直接放到自有目录下在代码实现上并不难，可能就几行代码，也不需要改软件功能，希望能尽快实现。

**Comment by HaujetZhao** [comment]
我也觉得需要改进一下，虽然从软件处理的逻辑上是好的，但是从用户使用的角度，在文件管理器中看到那么多带有日期、哈希值的 .sy.md 文件名，还是会别扭。克隆目录结构放到 .siyuan 文件夹就挺好的

**Comment by 88250** [comment]
@jxjxjhjh @HaujetZhao v0.2.9 实现 https://github.com/siyuan-note/siyuan/issues/221#issuecomment-707532632
