### ISSUE TITLE
在思源内复制超链接问题

### ISSUE THREAD

**Issue by LecoLu** [siyuan-note/siyuan#2215]
### Describe the problem
![image](https://user-images.githubusercontent.com/24625475/123351677-39672500-d590-11eb-8f37-15e02c0e974c.png)

复制出来后粘贴，这样显示很不友好：
![image](https://user-images.githubusercontent.com/24625475/123352102-33257880-d591-11eb-98e1-45864daf6597.png)

期望结果：（复制粘贴出来的应该是显示文本，就不要带上链接本身）
https://v.qq.com/
腾讯视频 - 中国领先的在线视频媒体平台,海量高清视频在线观看 (qq.com)

### Version environment
* Version: v1.2.0-beta9
* Operating system: Windows

**Comment by 88250** [comment]
你好，这个可以切换到导出预览进行复制，谢谢。
