### ISSUE TITLE
有序、无序列表向前缩进的建议

### ISSUE THREAD

**Issue by youth54** [siyuan-note/siyuan#2216]
### 当列表中包含子项时，列表向前缩进后，会向下移动
如下图
![无序列表缩进](https://user-images.githubusercontent.com/72968849/123370776-fff3e100-d5b2-11eb-8cfd-cac928d92299.gif)

### 建议
如下图所示，在同一行前后移动。这样感觉更符合编写习惯，以及内容的从属关系。
![列表缩进-建议](https://user-images.githubusercontent.com/72968849/123371257-fcad2500-d5b3-11eb-9b4d-0bf5d404f18c.gif)

**Comment by youth54** [comment]
写完子列表后，相要在前面插入同级内容，比较困难。
![image](https://user-images.githubusercontent.com/72968849/123372397-0e8fc780-d5b6-11eb-9fa5-d746522836dc.png)

**Comment by Vanessa219** [comment]
在实际的写作中，当有多个子列表，需要把第一个子列表提升，那么应该是和他的父亲并列，剩余的子列表依旧保持不变，而不是成为其兄弟列表的父亲，否则的话，还需要去手动移动该子列表同级的其余列表。
https://workflowy.com/ 的交互也是如此。
