### ISSUE TITLE
图片居中后图片的段后距显著增大

### ISSUE THREAD

**Issue by Creling** [siyuan-note/siyuan#2217]
居中前

![image](https://user-images.githubusercontent.com/43109504/123378298-24ee5100-d5bf-11eb-8b1e-8ef96682f8d0.png)

居中后

![image](https://user-images.githubusercontent.com/43109504/123378339-3172a980-d5bf-11eb-8deb-f70863a19300.png)

版本： v1.2.0-beta9 / Kernel v1.2.0-beta9

**Comment by 88250** [comment]
你好，我这里没有重现问题。

![issue](https://user-images.githubusercontent.com/873584/123391875-098b4200-d5cf-11eb-9738-96438b706a64.gif)

**Comment by 88250** [comment]
可能是这个地方多了一个空行？

![image](https://user-images.githubusercontent.com/873584/123518199-696d1000-d6d7-11eb-9b1f-c8c0631193fb.png)
