### ISSUE TITLE
本地备份 按钮加载不出来

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2219]
![截屏2021-06-25 下午4 05 14](https://user-images.githubusercontent.com/77337499/123391969-23c52000-d5cf-11eb-8a6c-66a7083803dd.png)

本地备份加载半天按钮还是不出来

**Comment by 88250** [comment]
我这里重现不了 😂

**Comment by GuoYimingac** [comment]
我是备份在外接硬盘
是不是会影响速度?

**Comment by GuoYimingac** [comment]
刚刚加载出来了

**Comment by 88250** [comment]
> 我是备份在外接硬盘
> 是不是会影响速度?

有可能，这个需要遍历查看文件大小。

**Comment by GuoYimingac** [comment]
好吧,我放在系统盘里

**Comment by 88250** [comment]
嗯，再观察看看是否变快了。

**Comment by 88250** [comment]
我先关闭了，如果有进一步反馈请跟帖。

**Comment by GuoYimingac** [comment]
快了的确,但是有个问题,为什么不能先把按钮加载出来,数据慢慢来,不然感觉很奇怪

**Comment by 88250** [comment]
好的，后面有空就改进。
