### ISSUE TITLE
内置数学公式引擎

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#222]
现在笔记本断了 wifi，思源、Typora 就都加载不了数学公式了，看到数学公式引擎都可以通过 npm 安装，就想或许思源可以内置 katex、mathjax 离线引擎

**Comment by 88250** [comment]
你好，思源已经离线打包数学公式引擎，我这里试了下简单的公式完全可以离线渲染的。请详述重现步骤，谢谢。

**Comment by HaujetZhao** [comment]
> 你好，思源已经离线打包数学公式引擎，我这里试了下简单的公式完全可以离线渲染的。请详述重现步骤，谢谢。

明白了。我是在离线时输入 `$\Delta$` 发现无法渲染成功，才认为没有内置引擎。今天在设置里将引擎从 MathJax 换成 KeTax 后可以了。

**Comment by 88250** [comment]
好的，那我关闭了。
