### ISSUE TITLE
全局搜索支持类型过滤

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2229]
### In what scenarios do you need this function?

Thanks for the nice feature, I think it's gonna be more efficient if we're able to choose the block type while searching in the same page.

**Comment by Kitsuta-le** [comment]
这个大概会是什么时候安排呀？等了好久。。。

**Comment by 88250** [comment]
@Kitsuta-le 还需要再等等。

**Comment by Kitsuta-le** [comment]
排除容器快都出选项了 这个应该不远了吧hhhh

**Comment by 88250** [comment]
@Kitsuta-le 再等等，1.8 以后再排期。
