### ISSUE TITLE
剪切链接后粘贴问题

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#2231]
### Describe the problem

- 剪切链接后粘贴, 只能粘贴一次, 第二次及之后按ctrl+v无法粘贴, 剪贴板为空;
- 剪切链接后粘贴, 链接丢失, 仅粘贴纯文本. 偶发, 未成功复现

### Expected result

(修复)

### Screenshot or screen recording presentation

NA

### Version environment

* Version: 1.2, beta 9
* Operating system: win10 x64
* Browser (if used): 

### Log File

NA

### More information

NA

**Comment by 88250** [comment]
剪切好像就是这样的吧，只能粘贴一次。

**Comment by yuuuxt** [comment]
不是的, 剪切后就到剪切板了, 可以多次粘贴, 可以在任意 text editor 或 word 中尝试.

**Comment by Vanessa219** [comment]
感谢反馈，偶发的我这里重现不了，还需要你再协助协助。
