### ISSUE TITLE
链接后粘贴链接问题

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#2232]
### Describe the problem

在链接后粘贴链接(无其他字符间隔), 排版错误.

### Expected result

(修复)

### Screenshot or screen recording presentation

NA

### Version environment

* Version: 1.2 beta 9
* Operating system: win10 x64
* Browser (if used): 

### Log File
NA

### More information

NA

**Comment by 88250** [comment]
我这里重现不了问题，麻烦录屏演示，谢谢。

![issue](https://user-images.githubusercontent.com/873584/123498582-6e907780-d663-11eb-9709-0639438f0f6a.gif)

**Comment by yuuuxt** [comment]
![temp](https://user-images.githubusercontent.com/3153534/123504852-48cc9800-d68e-11eb-9a52-db71d66d8ea4.gif)
