### ISSUE TITLE
拖放列表项以重新排序

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#2234]
### In what scenarios do you need this function?

方便地重新排序列表项(包括checkbox list)

### Describe the optimal solution

NA

### Describe the candidate solution

NA

### Other information

NA

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/123498445-90d5c580-d662-11eb-87b2-15c1c87c3f8b.gif)

应该还算方便。

**Comment by yuuuxt** [comment]
学会了, 谢谢
