### ISSUE TITLE
版本管理开关

### ISSUE THREAD

**Issue by wfan14513** [siyuan-note/siyuan#224]
对于没有版本管理需求的，不知道可不可以关掉。
用FolderSync同步坚果云的内容到手机，好像是因为有.git，所以总出错。

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/98698061-966eeb80-23b0-11eb-9cd7-7f0ad4d303d8.png)

目前这里只能大于 0，将改为可以设置成 0，表示关闭版本管理。
