### ISSUE TITLE
滚屏选择笔记时存在选区丢失的问题

### ISSUE THREAD

**Issue by Creling** [siyuan-note/siyuan#2241]
当一边长按鼠标左键，一边滚动鼠标滚轮以大面积选择笔记内容时，先前选中的选区会在滚动屏幕的过程中丢失，即使没有放开鼠标左键。

版本：beta10

**Comment by 88250** [comment]
目前还不支持，请关注 https://github.com/siyuan-note/siyuan/issues/2066
