### ISSUE TITLE
文档树名称显示异常

### ISSUE THREAD

**Issue by abtxu** [siyuan-note/siyuan#2244]
![image](https://user-images.githubusercontent.com/48761002/123549494-e3ff6380-d79b-11eb-8864-0ad77328a412.png)

**Comment by 88250** [comment]
请看下默认主题是否有问题，如果没有的话麻烦向该主题仓库反馈，谢谢。

**Comment by abtxu** [comment]
![image](https://user-images.githubusercontent.com/48761002/123563560-04550f80-d7e8-11eb-8e65-1306d22990d7.png)
使用默认daylight主题，仍旧出现这个问题

**Comment by 88250** [comment]
请在设置 - 外观中重置一下看看。

**Comment by 88250** [comment]
我先关闭了，如果还有遇到请随时跟帖反馈，谢谢。
