### ISSUE TITLE
备注功能的优化

### ISSUE THREAD

**Issue by abtxu** [siyuan-note/siyuan#2247]
1. 希望能实现类似word中的批注功能。现有的备注功能只能针对整个内容块做备注，而实际上用户往往关注的是这个内容块中的某一个字词或者一句话。

能否让备注的粒度细化一些？

2. 另外，试图为多个内容块做备注也无法实现。选中多个内容块然后设置备注，只能为最后一个内容块加备注。

**Comment by 88250** [comment]
1. 备注目前不会做到行级和支持备注内容排版，这个场景建议用块引用
2. 合并为超级块，对超级块备注

谢谢。
