### ISSUE TITLE
虚拟引用 Virtual ref

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2249]
虚拟引用是一种根据已有块链的锚文本来自动探测的“块链”，但它并不会真实链接到块上，而是仅在编辑器内标记，并支持浮窗预览。

**实在没有时间查阅它的标准/惯用名称，如果你知道请斧正，谢谢。**

**Comment by roverway** [comment]
其实我感觉可以对整个笔记进行分词，允许用户自定义配置忽略某些关键词，之后对剩余词汇做个词云图，或者类似tag列表的东西，点击对应项目就提示相应的笔记或块。

似乎比这个探测更好用。

**Comment by 88250** [comment]
@roverway 这个看社区是否有人用挂件块实现

**Comment by roverway** [comment]
> @roverway 这个看社区是否有人用挂件块实现

现在开发挂件块的用户还很少。挂件块推出早期，D大是否考虑搞几个官方挂件？一方面向用户充分展示挂件的潜力，吸引流量，另一方面，也顺便解决一些问题或者提供一些新特性？

**Comment by 88250** [comment]
@roverway 是有这样的计划，但目前挂件块尚处于早期阶段，预计会在今年第四季度开始着手。

**Comment by deerainw** [comment]
感觉这个功能上的坑还是很多的，比如：
- 两个子文件夹下都有名叫「简介」的笔记，有这样的重名笔记时如何处理
- 「简介」属于一个比较高频的词汇，如果这些高频词汇不排除就会导致满篇都是提示，还需要有根据用户字典来排除的功能
- 支持别名也是很自然的需求......
- 分词问题、性能问题......
😢

**Comment by 88250** [comment]
@deerainw 多谢帮忙考虑，我们补充一下你再看看是否可行：

* 使用命名、别名来搜索（已有块链的锚文本是否要加入还在考虑），文档名不包含在内
* 如果有重复命名，通过类似引用数上那样进行多个引用展示
* 支持别名搜索，不知道你说的是不是这个？
* 应该没有分词问题，忽略大小写全匹配；性能应该问题不大，一开始的渲染只需要查询一次命名别名，鼠标悬浮的时候才真正搜索加载

其他还有什么地方感觉有问题麻烦再看看，谢谢。

**Comment by deerainw** [comment]
> @deerainw 多谢帮忙考虑，我们补充一下你再看看是否可行：
> 
> * 使用命名、别名来搜索（已有块链的锚文本是否要加入还在考虑），文档名不包含在内
> * 如果有重复命名，通过类似引用数上那样进行多个引用展示
> * 支持别名搜索，不知道你说的是不是这个？
> * 应该没有分词问题，忽略大小写全匹配；性能应该问题不大，一开始的渲染只需要查询一次命名别名，鼠标悬浮的时候才真正搜索加载
> 
> 其他还有什么地方感觉有问题麻烦再看看，谢谢。

既然命名也避免不了会有重复，那还是包含文档名吧...... 在 roam edit 里，鼠标放到一个检测到的链接上会出现一个预览浮窗，它不存在重复的问题，主要的麻烦还是重复内容该怎么呈现

**Comment by 88250** [comment]
考虑了下，不包含命名和别名了，仅在已有块链的锚文本中进行搜索。

**Comment by BettyJJ** [comment]
RoamEdit 把这个叫做“链接探测”，个人觉得比虚拟引用好，主要是虚拟引用有点看不懂是什么意思

**Comment by loveshizuka** [comment]
其实，叫作 “潜在引用” 又直接又达意。

**Comment by Elliootalderson** [comment]
虚拟引用,怎么使用啊,完全不会
