### ISSUE TITLE
将属性界面等做成类似公式的浮窗

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2250]
![截屏2021-06-28 下午4 20 44](https://user-images.githubusercontent.com/77337499/123603784-cb8b5980-d82c-11eb-907b-8eb9d44d31f9.png)
如题,这样挡住所选内容感觉对与命名之类的操作很不友好,能不能改成类似公式中所用的浮窗的那种形式

**Comment by 88250** [comment]
属性多了肯定还是会挡住内容的，不然属性窗口太小不方便。我关闭了，谢谢。
