### ISSUE TITLE
data losses again

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2253]
### Describe the problem

I've faced data losses in beta10  (Happened when adding & removing paragraphs) -- these paragraphs were pasted from a web page, so maybe the bug is related to pasting text.

![image](https://user-images.githubusercontent.com/33789516/123629226-54e26200-d814-11eb-84c9-d5e3d5857e1a.png)

![image](https://user-images.githubusercontent.com/33789516/123629260-5e6bca00-d814-11eb-9132-f0a1e170010b.png)

**Comment by 88250** [comment]
Please try after 'kernel booted' printed in the log.

**Comment by 88250** [comment]
We have improved the implementation. Before the kernel is booted, data is not allowed to be written. If there is a write operation, there will be an error message on the interface.

Please help to observe after beta11 is released, thank you.

**Comment by eslam-gomaa** [comment]
Thank you
