### ISSUE TITLE
支持内容块拖动排版

### ISSUE THREAD

**Issue by wfan14513** [siyuan-note/siyuan#226]
同样是因为即时渲染，有时候不方便文本选中，如果能拖动，就方便编辑和排版。

**Comment by wfan14513** [comment]
类似大纲笔记按住前面的点上下拖动

**Comment by lss6378** [comment]
> 
> 
> 同样是因为即时渲染，有时候不方便文本选中，如果能拖动，就方便编辑和排版。

这样子？  
![块拖动](https://user-images.githubusercontent.com/15924513/95850004-bc3dac00-0d82-11eb-98dd-b4326764f61e.gif)

**Comment by wfan14513** [comment]
对滴，赞！

**Comment by EndlessErrors** [comment]
许多有块的软件都支持拖动排版，强烈希望加入该功能

**Comment by 88250** [comment]
Word 中的快捷键是 `Shift Alt 上下箭头` @Vanessa219

**Comment by SuhaifengEric** [comment]
棒啊~已经支持永久版，D大加油，奥利给
