### ISSUE TITLE
期待增加块引用的跨文本移动功能

### ISSUE THREAD

**Issue by PayneSnow** [siyuan-note/siyuan#2265]
D大，您好！ 官方中文论坛发文好像需要积分，所以就在这儿提建议了。
思源笔记重构后，体验已经很流畅了，颜值提升了不少，使用也更方便了。
现在思源笔记可以像大纲笔记那样进行块折叠、展开、拖拽、聚焦。使用体验基本上与Roam Research、Logseq等相差无几。唯一的缺憾是缺乏块引用的跨文本拖拽。
双链笔记的一大优点便是通过引用实现数据的自动汇总。希望思源笔记未来可以允许直接将关于某个笔记文档的反向链接内容，像其他大纲笔记那样直接拖拽至该笔记文档中。
感谢！

**Comment by 88250** [comment]
你好，你说的拖拽指的是？

**Comment by PayneSnow** [comment]
移动。

**Comment by 88250** [comment]
呃，我理解不了，有空的话麻烦录个屏说明，谢谢。

**Comment by PayneSnow** [comment]
好，我虽然很早下载并购买思源，但是使用较少。可能我描述不准确。我录屏示范一下。感谢您！

**Comment by PayneSnow** [comment]
https://user-images.githubusercontent.com/51922806/123813214-4afd5380-d927-11eb-841f-9ef662155e62.mov

**Comment by 88250** [comment]
谢谢，我明白了，但这个短期内估计不会去考虑，现在还有大量优先级较高的任务需要完成。

**Comment by PayneSnow** [comment]
理解，明白。期待将录屏中的功能加入长期 roadmap。感谢！

**Comment by Vanessa219** [comment]
看了录屏，我还是不太明白你的需求，是需要这样的功能么？
https://user-images.githubusercontent.com/970828/123896753-b8939900-d994-11eb-9aea-55c5a64e205d.mp4

**Comment by PayneSnow** [comment]
> 看了录屏，我还是不太明白你的需求，是需要这样的功能么？
> 
>  QQ20210630-111659-HD.mp4
哈哈，对的。就是需要这个功能。原来已经实现了。前两天使用时，没有操作成功。使用有些生疏。给你们带来困扰了。
- 我刚测试了一下，貌似是仅支持 大纲列表内容块的移动，其他的内容块的移动不支持。还是我又没有正确操作？谢谢

**Comment by Vanessa219** [comment]
需要拖拽块所对应的图标。
![image](https://user-images.githubusercontent.com/970828/124052174-7fb8fa00-da50-11eb-937a-175a487a3e34.png)

**Comment by PayneSnow** [comment]
> 需要拖拽块所对应的图标。
> ![image](https://user-images.githubusercontent.com/970828/124052174-7fb8fa00-da50-11eb-937a-175a487a3e34.png)
感谢您的详细指点。如您所言，各种内容块——拖拽块所对应的图标——可以实现位置移动。但是在悬浮面板中，只有大纲列表可以拖动，其他的内容块在悬浮面板中没有显示对应的图标。

https://user-images.githubusercontent.com/51922806/124095478-4b632f00-da8c-11eb-8dd1-35f36d9b2e1e.mov

我提的跨文本移动内容块的需求在思源笔记里可能有点奇怪，能支持大纲列表的移动已经非常棒了。希望越做越好！
当然，除了跨文档的拖拽移动，通过打开多个窗口直接复制和粘贴，也可以实现将反向链接全部汇总到某个页面。
