### ISSUE TITLE
希望能提供标签树功能

### ISSUE THREAD

**Issue by alanjustalan** [siyuan-note/siyuan#2267]
因为自己标签用得比较频繁，标签的数量也比较多。但是有不少标签之间是有从属关系的，所以我想有一个标签树功能，可以对标签进一步进行分类。可以参考印象笔记的标签树功能。
![image](https://user-images.githubusercontent.com/42884681/123884378-ace8a800-d97d-11eb-84c9-429b51df1d3c.png)

**Comment by 88250** [comment]
目前应该已经支持，试试 `#a/b/c#`。

![image](https://user-images.githubusercontent.com/873584/123884569-1a94d400-d97e-11eb-9151-c7fceec43a9f.png)
