### ISSUE TITLE
Backup function error

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#2270]
### Describe the problem

The following error was reported during the backup

### Expected result

Normal operation

### Screenshot or screen recording presentation

![图片](https://user-images.githubusercontent.com/28727933/123896132-8afa2000-d993-11eb-85b0-ee74c81950d8.png)

### Version environment

* Version:  v1.2.0-beta9 / Kernel v1.2.0-beta9
* Operating system: windows10
* Browser (if used): 

### Log File

```log
E 2021/06/30 11:01:46 backup.go:272: read file [C:\Users\llej\Documents\SiYuan\data\widgets\svelte-app\node_modules\.pnpm\@babel+code-frame@7.14.5\node_modules\@babel\highlight] failed: read C:\Users\llej\Documents\SiYuan\data\widgets\svelte-app\node_modules\.pnpm\@babel+code-frame@7.14.5\node_modules\@babel\highlight: The handle is invalid.
E 2021/06/30 11:01:46 backup.go:172: encrypt data dir failed: read C:\Users\llej\Documents\SiYuan\data\widgets\svelte-app\node_modules\.pnpm\@babel+code-frame@7.14.5\node_modules\@babel\highlight: The handle is invalid.
```

### More information

This may be due to a problem with pnpm soft links

**Comment by 88250** [comment]
Hello, thanks for the feedback. Symbolic links should not be supported at the moment. Let’s see if it is necessary to support this later, just close this now.
