### ISSUE TITLE
希望能提供一个提醒功能

### ISSUE THREAD

**Issue by alanjustalan** [siyuan-note/siyuan#2272]
希望能提供一个提醒的功能。功能和样式可以参考印象笔记。比如在某篇文档上设置一个哪天哪时的提醒，到了时间就在软件内提醒，比如在软件内弹出窗口，或者其他通知方式。这样子可以让自己设定某篇文档什么时候再次阅读，某则任务笔记什么时候开始准备等等。
![image](https://user-images.githubusercontent.com/42884681/123925236-4b482e00-d9bd-11eb-8a94-b75c8efceadf.png)

**Comment by 88250** [comment]
现阶段暂时不考虑添加新特性了，估计要等 v3 阶段考虑，谢谢。
