### ISSUE TITLE
空列表项下面直接插入列表的情况

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2286]
![image](https://user-images.githubusercontent.com/873584/124214525-ec9dc400-db24-11eb-9e90-b8cac57d92f3.png)

这种情况理论上是可以存在的，但是实际上没有存在的价值，而且会造成困扰，所以应该不进行解析支持。

**Comment by XinLi0111** [comment]
还会出bug 【beta13】， 在空列表直接新建一个新的列表，然后在直接删除新建的列表，原先的空列表会卡住，再输入文字也会移位

**Comment by 88250** [comment]
@XinLi0111 的确有这个问题，我们还在考虑如何解决。

**Comment by choyy** [comment]
最近就被这种情况困扰

**Comment by 88250** [comment]
不考虑了，因为有的场景（真实用户案例）需要这样的结构：

* * [x] foo
* * [ ] bar
