### ISSUE TITLE
增加行宽度75

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2294]
![截屏2021-07-02 下午5 55 30](https://user-images.githubusercontent.com/77337499/124257637-2390cb80-db5f-11eb-8e2c-093a7d00e19e.png)
为啥没有75QAQ.命名有25

**Comment by GuoYimingac** [comment]
对了,啥时候做一个类似图像调节的手柄

**Comment by Achuan-2** [comment]
之前那个宽度调节的滑块在一级菜单底下这个设计蛮好的，现在宽度、块背景色、居中都藏在二级反而不方便了

**Comment by GuoYimingac** [comment]
同意，完全没必要做在二级里面

**Comment by Vanessa219** [comment]
全部展开一级放不下呀

**Comment by GuoYimingac** [comment]
如果使用并排的按钮还发得下吗?
还有就是感觉其实,这个手柄很难用

**Comment by Vanessa219** [comment]
感谢建议，后期改进，先添加 75
