### ISSUE TITLE
图片功能的改进建议

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#23]
1、提供选项：粘贴图片，拉取本地图片，拉取互联网图片，全部存入笔记本。
2、图片大小可以修改。

**Comment by wbooooooo** [comment]
图片还需要优化一下，比如我从剪贴板里粘过来的图片，本地拖过来的图片，我都希望本地自动保存，希望提供这个选项。比如qq聊天记录里的图片，粘过来，第二天就失效了。

**Comment by 88250** [comment]
本地图片的问题 Q 群里沟通过已解决；图片大小修改后续支持。
