### ISSUE TITLE
输入 (( 后继续输入文字,默认新建文档

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#230]
●输入`((`后继续输入文字,能以此文字为文件名默认新建文档.
●希望增加选项:单击块引用链接能直接跳转(而不是需要按住`Ctrl`单击跳转).
Thanks♪(･ω･)ﾉ

**Comment by 88250** [comment]
谢谢反馈，请参考 https://github.com/siyuan-note/siyuan/issues/70

跳转的话需要 Ctrl 否则编辑的交互会有冲突。
