### ISSUE TITLE
希望本地也能支持多份备份

### ISSUE THREAD

**Issue by alanjustalan** [siyuan-note/siyuan#2303]
因为我个人的资料比较大，云端备份多份的话，很快8g空间就填满了。所以希望本地备份也能支持多份备份，这样云端的多份备份就可以上传少几次

**Comment by 88250** [comment]
你好，本地可以在文件系统上直接复制的。

**Comment by alanjustalan** [comment]
> 你好，本地可以在文件系统上直接复制的。
没有啊，我打开backup文件夹，本地只有一份备份

**Comment by 88250** [comment]
将这个文件夹整体复制到其他就行了。

**Comment by alanjustalan** [comment]
> 将这个文件夹整体复制到其他地方就行了。

纯手动是吧？就是没那么方便，要打开这个文件夹，再复制到另一个地方。不像直接在备份界面点“备份到本地”就行了

**Comment by 88250** [comment]
效率上可能没有太大区别……思源里如果要支持多个备份，肯定也是需要设置备份路径的，所以其实和备份好了直接文件系统上拷贝没有多大区别了。
