### ISSUE TITLE
从文件夹结构迁移到子文档结构

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2304]
https://ld246.com/article/1625288787015

## 设计

* 笔记本文件夹使用 id
* 文档文件夹和文档使用相同的 id
* 同 id 文件夹下的文档视作子文档

## 迁移

* 笔记本文件夹重命名为新生成的 id，名称保存到 .siayun/conf.json 中
* 已有文件夹旁边如果不存在同名文档则创建同名的空文档
* 将文件夹名称改为同名文档 id
* [文档名迁移到 id](https://github.com/siyuan-note/siyuan/issues/2131)

**Comment by roverway** [comment]
这样迁移之后，还可以在本地文件系统随意调整文档所属目录吗？

**Comment by 88250** [comment]
@roverway 可以调整的，但需要先定位到文档 id
