### ISSUE TITLE
beta11添加三级标题后，大纲不显示

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#2310]
![image](https://user-images.githubusercontent.com/33319484/124361967-c67f3d80-dc64-11eb-8e80-95495e7e5e04.png)

如图所示，添加三级标题后，鼠标移动过去，会出现箭头，点击后才会显示（展开）

**Comment by 88250** [comment]
这个应该没问题，三级标题是二级标题的子节点。我先关闭了，如果还有疑问或者反馈请继续跟帖，谢谢。

**Comment by JokeenZhang** [comment]
之前不都是默认展开的吗，怎么现在需要手动去展开呢

**Comment by Vanessa219** [comment]
默认只展开第一层
