### ISSUE TITLE
历史记录写入报错

### ISSUE THREAD

**Issue by alanjustalan** [siyuan-note/siyuan#2313]
更新 12后，有些笔记的历史间隔记录丢失了，我是设置每分钟记录一次的，现在有的文件的历史间隔记录只有最近的一次
![ABH`6KGF56SXC ~~H84_J@4](https://user-images.githubusercontent.com/42884681/124370960-6661b900-dcaf-11eb-81bb-74dedc559e27.jpg)

**Comment by 88250** [comment]
请上传一下日志文件。

**Comment by 88250** [comment]
群里沟通后发现和 https://github.com/siyuan-note/siyuan/issues/2309 是一个问题，这个 issue 先关闭了。

**Comment by 88250** [comment]
抱歉，不是同一个问题，这个是写历史文件的时候有 bug，感谢反馈，下个版本修复。
