### ISSUE TITLE
beta12，有的笔记的历史间隔记录没有丢失，但右边的部分又没了

### ISSUE THREAD

**Issue by alanjustalan** [siyuan-note/siyuan#2314]
有的笔记的历史间隔记录没有丢失，但右边的部分又没了
![@6 Y8EQ56`Q)KH4(7PQ W K](https://user-images.githubusercontent.com/42884681/124370970-927d3a00-dcaf-11eb-96dc-1f539349bb37.jpg)

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2313
