### ISSUE TITLE
嵌入块错误渲染

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#2315]
### Describe the problem

嵌入块错误的渲染了多个

### Screenshot or screen recording presentation

![图片](https://user-images.githubusercontent.com/28727933/124378086-24059f80-dce2-11eb-9168-b6e8e76d51c0.png)

### Version environment

* Version: v1.2.0-beta12 / Kernel v1.2.0-beta12
* Operating system: windows10
* Browser (if used): 

### More information

<details >
    <summary>源文件</summary>
    <pre>{
	"ID": "20210703115750-avc54g9",
	"Type": "NodeDocument",
	"Properties": {
		"id": "20210703115750-avc54g9",
		"updated": "20210704160824"
	},
	"Children": [
		{
			"ID": "20210703115750-8dwrwot",
			"Type": "NodeParagraph",
			"Properties": {
				"id": "20210703115750-8dwrwot",
				"updated": "20210703115819"
			},
			"Children": [
				{
					"Type": "NodeText",
					"Data": "adfadfa"
				}
			]
		},
		{
			"ID": "20210703115811-8dbulrz",
			"Type": "NodeParagraph",
			"Properties": {
				"id": "20210703115811-8dbulrz",
				"updated": "20210703115834"
			},
			"Children": [
				{
					"Type": "NodeBlockRef",
					"Data": "span",
					"Children": [
						{
							"Type": "NodeOpenParen"
						},
						{
							"Type": "NodeOpenParen"
						},
						{
							"Type": "NodeBlockRefID",
							"Data": "20210703115750-8dwrwot"
						},
						{
							"Type": "NodeBlockRefSpace"
						},
						{
							"Type": "NodeBlockRefText",
							"Data": "adfadfa"
						},
						{
							"Type": "NodeCloseParen"
						},
						{
							"Type": "NodeCloseParen"
						}
					]
				},
				{
					"Type": "NodeText",
					"Data": "的"
				}
			]
		},
		{
			"ID": "20210704160541-ddnay35",
			"Type": "NodeList",
			"ListData": {},
			"Properties": {
				"id": "20210704160541-ddnay35",
				"updated": "20210704160819"
			},
			"Children": [
				{
					"ID": "20210704160544-zsyg3bu",
					"Type": "NodeListItem",
					"ListData": {
						"BulletChar": 42,
						"Marker": "Kg=="
					},
					"Properties": {
						"id": "20210704160544-zsyg3bu",
						"updated": "20210704160819"
					},
					"Children": [
						{
							"ID": "20210704160544-vwqe051",
							"Type": "NodeParagraph",
							"Properties": {
								"id": "20210704160544-vwqe051",
								"updated": "20210704160546"
							},
							"Children": [
								{
									"Type": "NodeText",
									"Data": "dd"
								}
							]
						},
						{
							"ID": "20210704160816-7alljp4",
							"Type": "NodeList",
							"ListData": {},
							"Properties": {
								"id": "20210704160816-7alljp4",
								"updated": "20210704160819"
							},
							"Children": [
								{
									"ID": "20210704160816-zc8pvre",
									"Type": "NodeListItem",
									"ListData": {
										"BulletChar": 42,
										"Marker": "Kg=="
									},
									"Properties": {
										"id": "20210704160816-zc8pvre",
										"updated": "20210704160819"
									},
									"Children": [
										{
											"ID": "20210704160816-ng5b6j0",
											"Type": "NodeParagraph",
											"Properties": {
												"id": "20210704160816-ng5b6j0",
												"updated": "20210704160817"
											},
											"Children": [
												{
													"Type": "NodeText",
													"Data": "11"
												}
											]
										},
										{
											"ID": "20210704160818-6tf9gtd",
											"Type": "NodeList",
											"ListData": {},
											"Properties": {
												"id": "20210704160818-6tf9gtd",
												"updated": "20210704160819"
											},
											"Children": [
												{
													"ID": "20210704160818-t3ylk36",
													"Type": "NodeListItem",
													"ListData": {
														"BulletChar": 42,
														"Marker": "Kg=="
													},
													"Properties": {
														"id": "20210704160818-t3ylk36",
														"updated": "20210704160819"
													},
													"Children": [
														{
															"ID": "20210704160818-n4dp2so",
															"Type": "NodeParagraph",
															"Properties": {
																"id": "20210704160818-n4dp2so",
																"updated": "20210704160819"
															},
															"Children": [
																{
																	"Type": "NodeText",
																	"Data": "333"
																}
															]
														}
													]
												}
											]
										}
									]
								}
							]
						}
					]
				}
			]
		},
		{
			"ID": "20210704160824-3jexnkk",
			"Type": "NodeBlockQueryEmbed",
			"Properties": {
				"id": "20210704160824-3jexnkk",
				"updated": "20210704160824"
			},
			"Children": [
				{
					"Type": "NodeOpenBrace"
				},
				{
					"Type": "NodeOpenBrace"
				},
				{
					"Type": "NodeBlockQueryEmbedScript",
					"Data": "select * from blocks where id='20210704160816-zc8pvre'"
				},
				{
					"Type": "NodeCloseBrace"
				},
				{
					"Type": "NodeCloseBrace"
				}
			]
		}
	]
}</pre>

</details>

**Comment by Vanessa219** [comment]
单个导入源文件是 ok 的，看上去应该是 id 重复了。点击跳转看一下，应该是可以打开2个块。还麻烦把 id 重复的步骤发我一下。谢谢。

**Comment by 2234839** [comment]
应该不会是 id 重复，这是新创建的

![嵌入块重复渲染](https://user-images.githubusercontent.com/28727933/124380630-42729780-dcf0-11eb-8c02-9bd3d232edc5.gif)
