### ISSUE TITLE
beta11 块引用问题，复制为引用块后，在无序列表中黏贴，出现问题

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#2320]
![image](https://user-images.githubusercontent.com/33319484/124389666-bb86e480-dd1a-11eb-9b41-e17fdb48c39b.png)

如图，在黏贴后，在其后面输入“，”，会出现在下一行，并且光标不能移动到块引用最后面，也就是在“扣6分”继续往前移动鼠标后，会直接出现在块引用后面

**Comment by 88250** [comment]
方便打包上传一下 .sy 文件吗？

**Comment by Vanessa219** [comment]
beta12 中修复过。

**Comment by JokeenZhang** [comment]
久等了，文件并没有引用其他文件的块，引用的是同文件的块。

无法直接上传`.sy`，所以打包成zip了，请查收。

[1 扣分与罚款.zip](https://github.com/siyuan-note/siyuan/files/6765118/1.zip)
