### ISSUE TITLE
微软输入法中文状态下输入数字的问题

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#2321]
### Describe the problem

在微软输入法下复现.

### Expected result

NA

### Screenshot or screen recording presentation
![temp](https://user-images.githubusercontent.com/3153534/124389697-dc4f3a00-dd1a-11eb-9d4a-676561739ea6.gif)

### Version environment

* Version: 1.2 beta12
* Operating system: win10 x64
* Browser (if used): 

### Log File

NA

### More information

NA

**Comment by 88250** [comment]
这个问题我这里重现不了，得继续等其他使用者反馈看看。

**Comment by Vanessa219** [comment]
无法重现，但摸索着修复了一下，还麻烦下个版本再帮忙反馈一下。
