### ISSUE TITLE
slow when past copied text from a browser

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2325]
### Describe the problem

Some times it's slow to past copied text from a browser :thinking: , I couldn't record it as it doesn't always happen (Just from time to time)

**Comment by 88250** [comment]
Hello, how many contents copy one time?

**Comment by eslam-gomaa** [comment]
few lines (nearly 5 lines) sometimes less

**Comment by 88250** [comment]
Please help to continue to observe, thank you.

**Comment by eslam-gomaa** [comment]
Will report if I face it again, thank you
