### ISSUE TITLE
List block data loss

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2329]
### Describe the problem

I get that message a lot !  (seems to happen only with `lists` blocks)

![image](https://user-images.githubusercontent.com/33789516/124508712-bc7a4d80-ddd0-11eb-9b78-82b108426ffb.png)

**Comment by 88250** [comment]
Please upgrade to beta13 (please remeber to ensure the old kernel process is closed before boot).

**Comment by eslam-gomaa** [comment]
I rebooted, and still getting it
