### ISSUE TITLE
块引用悬浮预览窗口加入跳转按钮

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#233]
### 当前环境：
- 操作系统： win10
- 思源版本：V0.2.8

### 场景描述
当前块引用和块嵌入，跳转到原文需要使用 **(Ctrl + 鼠标点击)** ，  
对于习惯使用鼠标浏览页面的同学来说体验上不是非常 **顺滑** 

### 期望的改进
希望直接鼠标点击**块引用或块嵌入**名称，就能直接跳转到原文。
操作就像浏览器鼠标点击跳转到相应链接一样，会比较直观，没有学习负担。

![鼠标页面跳转](https://user-images.githubusercontent.com/15924513/95945420-06736b80-0e1d-11eb-8d05-b7d006b697be.gif)

**Comment by 88250** [comment]
但这会和点击编辑的交互有冲突哦。

**Comment by lss6378** [comment]
> 
> 
> 但这会和点击编辑的交互有冲突哦。

是否可考虑鼠标悬，弹出跳转链接，
 - 点击链接跳转，
 - 点击原文编辑

**Comment by lss6378** [comment]
类似这样子： 
![图片](https://user-images.githubusercontent.com/15924513/95947298-dfb73400-0e20-11eb-82da-edee32e8b7a7.png)

**Comment by nanmao** [comment]
感谢你的建议.非常赞同你的想法😘块引用是思源的基础,我觉得越方便越舒服,少按一个按键感觉都不一样.
