### ISSUE TITLE
突然弹出查询失败窗口

### ISSUE THREAD

**Issue by DonSudo** [siyuan-note/siyuan#2335]
上下都有文字（中英文都包含）时，输入无序列表，弹出查询失败窗口，无法稳定复现，但时不时就出现
![查询](https://user-images.githubusercontent.com/53081419/124571625-898c9400-de7a-11eb-8d09-2d07f492994f.gif)

**Comment by 88250** [comment]
谢谢，已经能够重现问题，合并到 https://github.com/siyuan-note/siyuan/issues/2329 中解决。
