### ISSUE TITLE
Data loss when creating a new document

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2336]
### Describe the problem

Got the same error when creating a new document

The error got away when restarted the app

![image](https://user-images.githubusercontent.com/33789516/124671152-5d423900-deb5-11eb-8f31-c6a0466b4ed6.png)

**Comment by 88250** [comment]
Please help to continue to observe, thank you.

**Comment by 88250** [comment]
v1.2.0-beta15 has been released, please use it to test.

**Comment by eslam-gomaa** [comment]
seems to be fixed, Thank you
