### ISSUE TITLE
作为 md 编辑器使用

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#234]
当在一个未添加到笔记本的目录中双击打开 md 文件，打开方式选择思源笔记时，思源笔记以正常编辑 md 文件的方式编辑这个文件，对其进行 sy.md 的格式转化。

对于一些不希望添加到笔记本的 md 文件（例如仓库的 readme.md 文件）编辑很有用。

**Comment by 88250** [comment]
单个文档的编辑不是思源的目标场景，就不支持了，谢谢反馈。
