### ISSUE TITLE
未知原因闪退

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2342]
### Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
请帮忙找找重现步骤，谢谢。

**Comment by GuoYimingac** [comment]
[2.31.1 PHY103 Lecture Note的副本.zip](https://github.com/siyuan-note/siyuan/files/6774142/2.31.1.PHY103.Lecture.Note.zip)

**Comment by GuoYimingac** [comment]
首先是显示说什么要刷新,否则会丢失,然后再打开,一直往下滑动
就会直接闪退出去

**Comment by GuoYimingac** [comment]
文件是那个09.2的那个

**Comment by 88250** [comment]
是否删除过标题？

**Comment by GuoYimingac** [comment]
没有

**Comment by 88250** [comment]
版本是？

**Comment by GuoYimingac** [comment]
当前版本 v1.2.0-beta11 / Kernel v1.2.0-beta12

**Comment by 88250** [comment]
请安装目前的最新版 beta14 看看。

**Comment by GuoYimingac** [comment]
好的我试试看

**Comment by 88250** [comment]
请升级到 beta15 试试，谢谢。

**Comment by GuoYimingac** [comment]
这个文档在beta14通过刷新不再出现问题了

**Comment by 88250** [comment]
好的，请继续观察。

**Comment by 88250** [comment]
我关闭了，请用最新版测试，如果还有问题请跟帖反馈，谢谢。
