### ISSUE TITLE
关于带图的文档移动的问题

### ISSUE THREAD

**Issue by wfan14513** [siyuan-note/siyuan#235]
最好能在打开思源后把对应的图片自动拉到相应的assets文件夹内。

**Comment by 88250** [comment]
你好，我没有看明白，麻烦详述，谢谢。

**Comment by wfan14513** [comment]
不好意思，嫌麻烦就没上图。我上了两张图你看看能表达清楚不：
[](https://github.com/wfan14513/PublicPic01/blob/master/%E7%A7%BB%E5%8A%A8%E5%B8%A6%E5%9B%BE%E6%96%87%E6%A1%A31.png?raw=true)
[](https://github.com/wfan14513/PublicPic01/blob/master/%E7%A7%BB%E5%8A%A8%E5%B8%A6%E5%9B%BE%E6%96%87%E6%A1%A32.png?raw=true)

**Comment by wfan14513** [comment]
![图](https://github.com/wfan14513/PublicPic01/blob/master/%E7%A7%BB%E5%8A%A8%E5%B8%A6%E5%9B%BE%E6%96%87%E6%A1%A31.png?raw=true)

![图](https://github.com/wfan14513/PublicPic01/blob/master/%E7%A7%BB%E5%8A%A8%E5%B8%A6%E5%9B%BE%E6%96%87%E6%A1%A32.png?raw=true)

**Comment by 88250** [comment]
思源内移动文档会实现自动复制关联资源，请关注 #244 。
