### ISSUE TITLE
cannot paste image into Siyuan. Image broken

### ISSUE THREAD

**Issue by legend053** [siyuan-note/siyuan#2357]
Siyuan version: 1.2 Beta 14.

Images cannot be shown after paste images into Siyuan. The gif shows failure of pasting screenshot into siyuan. Actually, I cannot paste all images into Siyuan. But, if I click the broken image, the image can be shown in the pop up window.

![copy screenshot to siyuan fail](https://user-images.githubusercontent.com/7464388/124867107-191d6a00-df83-11eb-9105-f373c38f7afb.gif)

**Comment by 88250** [comment]
资源文件是存放在全局还是笔记本文件夹下？

**Comment by legend053** [comment]
是在：assets/aa-20210709155704-3416nij.png
我发现在这个笔记本里，粘贴图片都是无法显示。但是，我在另一个笔记本里，粘贴图片都一切正常。我看图片也是在assets下面的。

**Comment by 88250** [comment]
方便把数据打包给我一下么？ 845765@qq.com

**Comment by legend053** [comment]
是那个有问题的笔记本吗？

**Comment by 88250** [comment]
只要是能重现问题的最小数据集即可，谢谢。

**Comment by 88250** [comment]
已经收到测试数据，但是我这里重现不了，麻烦再观察看看。

**Comment by 88250** [comment]
我先关闭了，如果还遇到问题请继续跟帖反馈。
