### ISSUE TITLE
iframe嵌入youtube会404,浏览器正常访问

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2359]
![Uploading 截屏2021-07-08 下午8.59.53.png…]()
如题

**Comment by GuoYimingac** [comment]
![截屏2021-07-08 下午9 00 13](https://user-images.githubusercontent.com/77337499/124925877-7ff85d00-e02f-11eb-8e67-fb4db95c5ef1.png)
我不确定是不是我的网络设置问题,还是软件有什么地方有事

**Comment by 88250** [comment]
应该是网络问题吧，现在不支持代理，除非走系统的全局代理。

**Comment by 88250** [comment]
先关闭了，后面看反馈情况后再考虑重启 https://github.com/siyuan-note/siyuan/issues/1009
