### ISSUE TITLE
这个 table-layout: fixed;  在beta2中可以更改表格等宽，升级了新的版本后就实现不了了

### ISSUE THREAD

**Issue by wk-coder** [siyuan-note/siyuan#2370]
### Describe the problem

theme.css中更改表格的css，在beta2中，加入如下语句：

table,th
{
	table-layout: fixed; 
	border:1px solid black;
	width:100%;
}
td
{
	text-align:left;
}

可以实现表格中列表等宽。

现在升级了 beta15，14，13都试过了，更改后没有作用，单句测试的时候，width属性可以改有效果，但是“ table-layout:fixed” 这句话失效了。
想问一下是什么原因，能解决吗？或者思源后来的新版本有了另一种实现方式吗？

### Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by Vanessa219** [comment]
需要设置一下     display: table;
