### ISSUE TITLE
Images take unneeded space

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2372]
### Describe the problem

Images take unneeded space

![image](https://user-images.githubusercontent.com/33789516/125026138-41d95880-e084-11eb-87ff-854d3c402683.png)

This affects folding pictures (folding used show some of the picture while it's folded)

![image](https://user-images.githubusercontent.com/33789516/125026184-574e8280-e084-11eb-85af-913282624a14.png)

**Comment by 88250** [comment]
This bug will be fixed in https://github.com/siyuan-note/siyuan/issues/2365, thanks.
