### ISSUE TITLE
导出设置块引为锚文本模式时报错

### ISSUE THREAD

**Issue by jh-yi** [siyuan-note/siyuan#2376]
### Describe the problem

版本：v1.2.0-beta15和16

当文档内有引用块和块链接时正常迅速导出，但有嵌入块时选择导出-markdown显示“正在导出，请稍后”。

**Comment by 88250** [comment]
内核日志有报错吗？

**Comment by jh-yi** [comment]
> 内核日志有报错吗？

E 2021/07/09 16:00:44 log.go:89: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	/usr/local/go/src/runtime/panic.go:965 (0x4039c38)
/usr/local/go/src/runtime/panic.go:212 (0x403803a)
/usr/local/go/src/runtime/signal_unix.go:734 (0x4051c58)
/Users/Vanessa/Work/GoGoGo/pkg/mod/github.com/88250/lute@v1.7.4-0.20210709072903-7049481e1e93/ast/node.go:392 (0x43fd124)
/Users/Vanessa/Work/GoGoGo/pkg/mod/github.com/88250/lute@v1.7.4-0.20210709072903-7049481e1e93/ast/node.go:429 (0x43fd11f)
/Users/Vanessa/Work/Code/siyuan-src/kernel/model/export.go:311 (0x4b61244)
/Users/Vanessa/Work/GoGoGo/pkg/mod/github.com/88250/lute@v1.7.4-0.20210709072903-7049481e1e93/ast/walk.go:36 (0x43fe078)
/Users/Vanessa/Work/GoGoGo/pkg/mod/github.com/88250/lute@v1.7.4-0.20210709072903-7049481e1e93/ast/walk.go:44 (0x43fe0c4)
/Users/Vanessa/Work/GoGoGo/pkg/mod/github.com/88250/lute@v1.7.4-0.20210709072903-7049481e1e93/ast/walk.go:31 (0x4b26288)
/Users/Vanessa/Work/Code/siyuan-src/kernel/model/export.go:220 (0x4b26245)
/Users/Vanessa/Work/Code/siyuan-src/kernel/model/export.go:208 (0x4b26099)
/Users/Vanessa/Work/Code/siyuan-src/kernel/model/export.go:146 (0x4b25704)
/Users/Vanessa/Work/Code/siyuan-src/kernel/model/export.go:108 (0x4b24d58)
/Users/Vanessa/Work/Code/siyuan-src/kernel/cmd/exportmd.go:21 (0x4bb7cbd)
/Users/Vanessa/Work/Code/siyuan-src/kernel/cmd/cmd.go:203 (0x4bc34b2)
/usr/local/go/src/runtime/asm_amd64.s:1371 (0x4074840)

**Comment by 88250** [comment]
方便发一下测试用的数据集给我吗？ 845765@qq.com

**Comment by 88250** [comment]
你好，用这个测试集我导出 test_inbox 没有发现问题哦。

**Comment by 88250** [comment]
抱歉，结合日志分析发现是设置了导出为锚文本时可以重现问题了，这个 bug 稍后修复，谢谢。

**Comment by jh-yi** [comment]
好的辛苦了～

D ***@***.***> 于 2021年7月9日周五 17:52写道：
