### ISSUE TITLE
插入图片之后的bug

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2378]
https://user-images.githubusercontent.com/77337499/125092492-fbc3d980-e103-11eb-8b8a-9936854b63d0.mov

**Comment by Vanessa219** [comment]
啊啊啊，我没看出啥问题呀。

**Comment by 88250** [comment]
设置了居中？

**Comment by GuoYimingac** [comment]
就是图片删掉以后会出现居中的提示文字,同时光标在左边,除非把这个快删掉,必然不会改变

**Comment by GuoYimingac** [comment]
还有就是,原来的居中照片下面都会多出一行,但是无法删除那一行,能不能看看是不是有什么解决方法

**Comment by Vanessa219** [comment]
> 就是图片删掉以后会出现居中的提示文字,同时光标在左边,除非把这个快删掉,不然不会改变

重新设置一下外观
![image](https://user-images.githubusercontent.com/970828/125159146-367f4d80-e1a8-11eb-9a39-e3a7cf8d2133.png)

**Comment by Vanessa219** [comment]
> 还有就是,原来的居中照片下面都会多出一行,但是无法删除那一行,能不能看看是不是有什么解决方法

这个是图片标题的位置，后期优化。
