### ISSUE TITLE
网页端退出

### ISSUE THREAD

**Issue by WuTao18** [siyuan-note/siyuan#2384]
### In what scenarios do you need this function?

用Docker部署思源笔记，希望加入退出功能。

### Describe the optimal solution

1. 网页端加入退出的按钮，点击后退出，需要再次登录才能使用。
2. 如果一段时间不操作，可以自动退出。

**Comment by 88250** [comment]
你好，后面支持，谢谢。

https://ld246.com/article/1625728661599

**Comment by 88250** [comment]
授权码机制已经重写，网页关闭以后会自动清空授权状态。
