### ISSUE TITLE
Back and forward for editor

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#239]
# 希望增加标签回跳快捷键（或者有个回跳按钮）
* 打开新标签的时候（或者自顶向下新建文档的时候），能按快捷键回跳上一标签页.
* 如果标签页打开很多，打开标签页再回跳回去在标签窗口很难找准；如果通过反向链接回跳，需要打开反向链接，然后双击第一行，这在编辑笔记的时候这么多步骤有点割裂.

# 使用场景

我在集中学某一章节的时候，有标签回跳快捷键可以很方便的纵向拆解，等新建文档块自顶向下用法实现了，我在拆解文章里各种名词概念解释的时候，编辑完后需要回跳回来，能用快捷键（或者有个回跳按钮）的话，整体就很流畅顺滑.

**Comment by 88250** [comment]
感谢反馈，这两点提议都非常有用，我们会逐步实现。

**Comment by lss6378** [comment]
+1,希望有个浏览器类似的按钮，可以前进后退
![图片](https://user-images.githubusercontent.com/15924513/96328837-a0375480-1079-11eb-8e85-13d276452173.png)

**Comment by lss6378** [comment]
主流浏览器(谷歌，火狐)都支持鼠标侧键前进后退，浏览页面非常便捷  
![图片](https://user-images.githubusercontent.com/15924513/96330571-c0224480-1088-11eb-8c63-b6be2cf43971.png)

**Comment by 88250** [comment]
拆分为两个 issue，复制内容块快捷操作请参考 https://github.com/siyuan-note/siyuan/issues/313

**Comment by Vanessa219** [comment]
> 当光标停留在整个文档外边框和内边框之间的空白处
这里光标指的是鼠标的小手手？

**Comment by nanmao** [comment]
> 这里光标指的是鼠标的小手手？
> 
> > 当光标停留在整个文档外边框和内边框之间的空白处

是的. 当鼠标停留在整个文档外边框和内边框之间的空白处

**Comment by Tokubara** [comment]
这个issue包括了cursor的navigate么? 也就是移动了光标以后, 能够通过快捷键之类的返回到原来的光标的位置么?
比如通过内容块链接, 我跳到了另一个内容块, 这个issue能让我迅速回到原来的位置, 是这样么?

**Comment by 88250** [comment]
@Tokubara 理论上是的

**Comment by banjuer** [comment]
提议增加返回上一步操作快捷键. 找了半天没找到在这里看到了, 原来是个feature😊

**Comment by JokeenZhang** [comment]
这样的话鼠标的后退前进按键就很有用了，支持
