### ISSUE TITLE
新建文档名对话框输入自适应宽度

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2391]
![截屏2021-07-10 下午11 15 57](https://user-images.githubusercontent.com/77337499/125167789-dce14800-e1d4-11eb-99c7-530d5757c02e.png)

**Comment by 88250** [comment]
有啥建议么？

**Comment by 88250** [comment]
群里讨论后，考虑把输入框和文字一起拉长。
