### ISSUE TITLE
图片放到最大时会跳一下

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2402]
https://user-images.githubusercontent.com/77337499/125251429-e03a1800-e329-11eb-9971-1f8ca2217136.mov

是不是出bbug了

**Comment by GuoYimingac** [comment]
[Polarisation.sy.zip](https://github.com/siyuan-note/siyuan/files/6799584/Polarisation.sy.zip)

**Comment by 88250** [comment]
我这里重现不了问题哦。

![issue](https://user-images.githubusercontent.com/873584/125252727-45dad400-e32b-11eb-8c0c-8be27be48ab3.gif)

**Comment by Vanessa219** [comment]
版本是？

**Comment by 88250** [comment]
先关闭了，如果有进一步反馈请跟帖。
