### ISSUE TITLE
I think  entering `focus` by clicking `ctrl` + `the block (In the editing area)` is not comfortable

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#2409]
### In what scenarios do you need this function?

I think  entering `focus` by clicking `ctrl` + `the block (In the editing area)` is not comfortable, because it's easy to click `ctrl` for another reason and enter the focus mode unintentionally

Thank you

**Comment by 88250** [comment]
Yes, rc2 we will remove it.

https://github.com/siyuan-note/siyuan/issues/2403
