### ISSUE TITLE
清理无用的图片功能

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#241]
“删除”文档的图片后，assets文件夹里的图片还在。
●希望在编辑笔记的时候，删除笔记里的图片，assets文件夹里的图片也被删掉。
●或者出一个功能，能找出assets文件夹里没有被引用的图片，删掉。

**Comment by 88250** [comment]
感谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/110
