### ISSUE TITLE
预览图片时支持缩放和拖动视觉焦点位置

### ISSUE THREAD

**Issue by Mrxiang-Plus** [siyuan-note/siyuan#2415]
### In what scenarios do you need this function?
当预览一张超大的图片是，只能看到图片的一部分

### Describe the optimal solution
希望可以在预览图片的时候实现鼠标滚轮缩放，和点击拖动图片位置

### Describe the candidate solution
预览时实现一个图片查看器的功能，滚轮缩放和点击拖动焦点位置

### Other information
这样在看图片的体验更友好

**Comment by Mrxiang-Plus** [comment]
图像的缩放功能还不能支持吗，我看pdf都支持缩放了

**Comment by Vanessa219** [comment]
是的，还没有安排到，pdf 的是使用的库里面就带了的。

**Comment by qifengle1998** [comment]
> 

PDF缩放太灵敏的问题希望后面可以优化一下。

**Comment by Mrxiang-Plus** [comment]
希望能尽快支持图片的缩放。图片浏览器也有较多的开源版本
现在写笔记，看大图真的很折磨

**Comment by Fast-Ray1** [comment]
怎么改图片默认的缩放大小 能修改配置文件吗

**Comment by Achuan-2** [comment]
同时希望能够有浏览笔记内所有图片的功能，支持上一张和下一张按钮

**Comment by 88250** [comment]
@Achuan-2 这个麻烦单独提议，谢谢。
