### ISSUE TITLE
旧版本迁移到新版本备份导致文件丢失问题

### ISSUE THREAD

**Issue by squirtlecc** [siyuan-note/siyuan#2423]
### Describe the problem

旧版本迁移到新版本(1.1.83->1.2.0)无法正常识别到笔记,且将目录调整到原文档依旧无法识别笔记;

当备份和笔记本文件夹相同时,会清空文件夹内的所有文件.

### Expected result

1.旧文档迁移到新文档有具体指导;
2.点击本地备份文件->备份时有提示会清空文件或不清空文件;
3. 可以查看以往云端备份的内容.

### Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/79736081/125573888-b0b8f8e6-315e-4ff0-807a-0899528fcbf7.png)
上图显示文件目录与笔记在同一目录下(旧版本指定目录即可检测到笔记)

![image](https://user-images.githubusercontent.com/79736081/125574194-cd78620d-bc63-482b-bb81-6ed50af633d8.png)
备份描述问题,描述并不清晰,因为常理来说备份文件的这个过程并不会清空备份文件夹中旧的文件,但是在该版本会清空备份文件夹中的所有文件之后再生成备份文件

### Version environment

* Version: 1.2.0-rc3
* Operating system: ubuntu-20.04
* Browser (if used): Chrome

### Log File

I 2021/07/14 13:02:13 working.go:118: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/07/14 13:02:13 working.go:119: kernel is booting: 
    * ver [1.1.83]
    * runtime mode [prod]
    * working directory [/home/vase/software/SiYuan/resources]
    * temp directory [/tmp/siyuan]
    * system temp directory [/tmp/siyuan] 
    * rsync directory [/home/vase/software/SiYuan/resources/rsync]
    * read only [false]
    * container [electron]
    * resident [true]
    * arch [amd64]
I 2021/07/14 13:02:13 conf.go:203: local serve path [http://192.168.50.193:6806]
I 2021/07/14 13:02:13 serve.go:60: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/07/14 13:02:20 working.go:143: kernel booted
I 2021/07/14 13:06:52 conf.go:242: exited kernel
I 2021/07/14 14:03:15 working.go:96: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/07/14 14:03:15 working.go:97: kernel [v1.1.0] is booting, runtime mode is [prod], working directory is [/home/vase/software/SiYuan/resources], temp directory is [/tmp/siyuan], read only [false], container [standard], resident [true], arch [amd64]
I 2021/07/14 14:03:15 working.go:184: port [6806] is opened, try to check version of running kernel
I 2021/07/14 14:03:15 conf.go:196: local serve path [http://192.168.50.193:6806]
I 2021/07/14 14:03:15 serve.go:58: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2021/07/14 14:03:15 serve.go:60: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: address already in use
I 2021/07/14 14:03:43 working.go:96: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/07/14 14:03:43 working.go:97: kernel [v1.1.0] is booting, runtime mode is [prod], working directory is [/home/vase/software/SiYuan/resources], temp directory is [/tmp/siyuan], read only [false], container [standard], resident [true], arch [amd64]
I 2021/07/14 14:03:43 conf.go:196: local serve path [http://192.168.50.193:6806]
I 2021/07/14 14:03:43 serve.go:58: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/07/14 14:03:43 repo.go:36: git repo has been disabled
E 2021/07/14 14:03:43 box.go:246: get data [path=/Server/Docker使用.md] from box [url=http://127.0.0.1:6806/siyuan/1610258813056/SiYuanNote/] failed: open /home/vase/文档/SiYuanNote/Server/Docker使用.md: no such file or directory
E 2021/07/14 14:03:43 box.go:246: get data [path=/Linux/Ubuntu 深度学习基础环境安装.md] from box [url=http://127.0.0.1:6806/siyuan/1610258813056/SiYuanNote/] failed: open /home/vase/文档/SiYuanNote/Linux/Ubuntu 深度学习基础环境安装.md: no such file or directory
E 2021/07/14 14:03:43 box.go:246: get data [path=/DeepLearning/d2l notebook.md] from box [url=http://127.0.0.1:6806/siyuan/1610258813056/SiYuanNote/] failed: open /home/vase/文档/SiYuanNote/DeepLearning/d2l notebook.md: no such file or directory
E 2021/07/14 14:03:57 liandi.go:128: get repos from cloud repo server failed: [invalid character '<' looking for beginning of value]
I 2021/07/14 14:05:28 working.go:350: port [6806] is opened, try to check version of running kernel
I 2021/07/14 14:05:28 working.go:364: found old kernel [ver=1.1.0] is running, try to close it
I 2021/07/14 14:05:28 conf.go:235: exited kernel
F 2021/07/14 14:05:28 working.go:368: close old kernel failed: [Post "http://127.0.0.1:6806/api/exit": EOF]
I 2021/07/14 14:05:31 working.go:118: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/07/14 14:05:31 working.go:119: kernel is booting: 
    * ver [1.1.83]
    * runtime mode [prod]
    * working directory [/home/vase/software/SiYuan/resources]
    * temp directory [/tmp/siyuan]
    * system temp directory [/tmp/siyuan] 
    * rsync directory [/home/vase/software/SiYuan/resources/rsync]
    * read only [false]
    * container [electron]
    * resident [true]
    * arch [amd64]
I 2021/07/14 14:05:31 conf.go:203: local serve path [http://192.168.50.193:6806]
I 2021/07/14 14:05:31 serve.go:60: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/07/14 14:05:39 working.go:143: kernel booted
E 2021/07/14 14:05:53 repo.go:135: read dir [/home/vase/文档/SiYuanNote/.siyuan/backup] failed: open /home/vase/文档/SiYuanNote/.siyuan/backup: no such file or directory
E 2021/07/14 14:06:08 liandi.go:172: get repos from cloud repo server failed: [invalid character '<' looking for beginning of value]
I 2021/07/14 14:21:49 conf.go:242: exited kernel
### More information

1.旧文档迁移到新文档没有具体指导,目前为止并没有迁移过去;
2.点击本地北方文件的备份时并没有提示会清空备份文件夹中的全部内容导致笔记文件全部丢失,这在笔记文档里还是很危险的操作;
3. 无法查看以往云端备份的内容,以前时有按钮点击直接跳转的现在跳转时404:(https://ld246.com/udanax/1610258813056).

**Comment by 88250** [comment]
* 迁移指南请看这里 https://ld246.com/article/1622710344891
* 云端在线工作空间已经移除了，其他移除的特性列表请看 https://ld246.com/article/1623053132677
