### ISSUE TITLE
支持Markdown的双链导出

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#2427]
### In what scenarios do you need this function?

支持Markdown的双链导出

### Describe the optimal solution

嵌入块可以直接把块放入到当前文档里导出，引用块可以作为另一个完整的文档导出，在当前文档里使用超链接链接。

### Describe the candidate solution

单个文件导出保持原样，支持整个笔记本导出为PDF，引用块使用PDF内的跳转。

**Comment by 88250** [comment]
目前的导出如果选择了锚文本导出模式，会自动加上 `siyuan://` 超链接，如果选择其他两个模式，会将引用处原文嵌入到当前文档中。

这部分暂时不做调整了，谢谢。
