### ISSUE TITLE
一段文字内含格式（粗体，超链接等），使用删除线后格式消失

### ISSUE THREAD

**Issue by jh-yi** [siyuan-note/siyuan#2428]
### Describe the problem

如题，一段文字内含格式（粗体，超链接等），使用删除线后格式消失。

### Expected result

有时候只是想提示自己已完成该部分内容，但仍希望原格式如超链接能保留。

**Comment by 88250** [comment]
目前通过工具栏操作不支持行级元素的交叉或者包含，如果需要的话可以试下通过 Markdown 语法进行排版。

这部分后面再改进，谢谢。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2911
