### ISSUE TITLE
关于引用内容块、反链、大纲的一些改进

### ISSUE THREAD

**Issue by jh-yi** [siyuan-note/siyuan#2429]
### Describe the problem

**引用内容块：**假设存在一个术语term定义，在其他文档中想要引用这个词的时候，总是想指向最原始的那段。但目前输入[[或((触发内容块引用搜索的时候会把作为引用块的关键字也作为候选。
e.g. 如果在文档1定义了一个python函数def abc()，在文档2、3、4....N文档都插入了这个引用块。在新文档想再次出发内容块引用搜索的时候，有N个选项！虽然有时可以根据路径区分，但如果前面的引用块位于同一个文档则无法区分了吧？加上候选列表中也是无序的。

**反链：**当新增引用内用快的时候，被引用块右侧的数字要关闭文档再打开才能更新显示。如果能即时更新就好了。

**大纲：**大纲中的标题前面都有H1, H2, H3...然而其实看不清数字，而且这么多H显得有点乱。如果可以只根据缩进区分层级就更干净了，并且可以自定义区分层级所用的缩进空格数。

个人意见，仅供参考

**Comment by 88250** [comment]
* 块引候选列表目前是按照类型排序的，优先文档块、标题块、段落块，同时也通过关键字的命中次数、是否有命名别名等因素进行了排序
* 反链、关系图等没有实时刷新，需要点击对应面板上的刷新按钮
* 大纲等地方的块标可以悬浮预览编辑的

感谢反馈，我关闭了，如果有其他建议欢迎跟帖。
