### ISSUE TITLE
引用内容块编辑BUG

### ISSUE THREAD

**Issue by jh-yi** [siyuan-note/siyuan#2430]
### Describe the problem

在B处插入引用内容块（原文A）后，修改原文A，B处自动更新。

但是不小心在B处编辑后，原文A处不更新，且再修改原文A时，B已不再自动更新。应该算一个BUG吧...

**Comment by 88250** [comment]
你好，引用链接渲染的文本在思源里叫做“锚文本”，这个锚文本默认是留空的，留空时会自动根据定义块的文本进行渲染。

如果手动改过锚文本（在引用处将光标移到链接中修改或者在右键弹框中修改），则会优先使用锚文本渲染，此时就会发现锚文本和定义块的文本不一样，这是个特性。

我关闭了 :)
