### ISSUE TITLE
打开帮助文档后引起的未找到内容块

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#2432]
### Describe the problem

打开两本笔记本的时候，点击另一本笔记本的文档会出现未找到内容块问题

### Screenshot or screen recording presentation

![I`FO_X7N)JS8LSY58YI4NOW](https://user-images.githubusercontent.com/47321059/125723834-28bdb20d-3662-4744-84ed-a83292348f7d.jpg)

### Version environment

* Version: 1.2
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
> 如果关掉用户指南，再打开用户指南，最后打开其他的笔记本，就会报查询笔记本失败，我这里复现是这样的

下个版本修复，谢谢。
