### ISSUE TITLE
复制块级元素到表格中时转换为行级元素

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#2436]
### Describe the problem

![1](https://user-images.githubusercontent.com/47321059/125763026-756eb141-d637-4eb2-b16f-0ab31643a779.gif)

### Version environment

* Version: 1.2
* Operating system:win10 
* Browser (if used):

**Comment by 88250** [comment]
复制的内容是个标题么？

**Comment by dejavudwh** [comment]
> 复制的内容是个标题么？

是的
