### ISSUE TITLE
shift + 方向键和全选快捷键的操作建议

### ISSUE THREAD

**Issue by dive2Pro** [siyuan-note/siyuan#2442]
### In what scenarios do you need this function?
键盘快捷操作

### Describe the optimal solution
* shift + 方向键

  * 现在
    *  shift + 上下 都是默认选中整个 block 了. 多行文字选择很不方便
  * 期望

    * 从选定的位置开始, shift + 上 应该选中 当前已选中的 + 到上一行和光标同一列的位置. 当到达 block 的顶行之后,  再 shift + 上, 才选中整个 block. 再 shift + 上  范围外扩.
* 全选快捷键

  * 现在

    * 选中全文.  而要选中一整个 block , 当前最快的方式则是通过鼠标三击, 影响输入的节奏
  * 期望

    * 如果当前页有光标, 第一次全选, 选中当前光标所在的 block. 第二次全选, 选中全文
    * 如果页面上没有光标, 第一次全选, 选中全文.

**Comment by Vanessa219** [comment]
会存在多页签多窗口的情况，因此无法确定当前的编辑器，这个就不实现了。

> 如果页面上没有光标, 第一次全选, 选中全文
