### ISSUE TITLE
新上传的附件被识别为未引用资源

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#2443]
### Describe the problem
新上传的附件被识别为未引用资源。清除会把真实的附件删掉,点击附件会提示"查询资源文件失败"，因为此问题已经丢失很多关联的附件。。。
### Expected result
附件引用被正确识别

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/18739609/125888703-a6ddf22a-cba1-4d94-9794-736cf20d8d64.png)

### Version environment

* Version: v1.2.0 / Kernel v1.2.0
* Operating system: Linux xxx-manjaro 5.10.49-1-MANJARO #1 SMP PREEMPT Sun Jul 11 12:59:43 UTC 2021 x86_64 GNU/Linux
* Browser (if used): 

### Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/6827664/siyuan.log)

**Comment by 88250** [comment]
可能是因为这个 https://github.com/siyuan-note/siyuan/issues/2435 麻烦确认下

**Comment by 88250** [comment]
清理未引用资源不会物理删除，而是移到了 history 下面，文件系统上找找手动恢复。

**Comment by banjuer** [comment]
> 可能是因为这个 #2435 麻烦确认下

我的附件尾部没有空格。删除几次再次上传还会出现提示未引用

**Comment by banjuer** [comment]
建议先以稳定性为主吧。一下子丢失很多附件的引用，哎，好痛苦

**Comment by 88250** [comment]
方便发一下数据集给我吗？ 845765@qq.com

**Comment by 88250** [comment]
你好，我们这段时间一直在改进稳定性，毫无疑问稳定性是最优先需要保证的。

这个问题我们在 QQ 用户群里请其他用户帮忙测试，他们都没有能重现问题。所以还是得麻烦你帮忙一下，谢谢。

**Comment by 88250** [comment]
已通过邮件沟通，目前暂时不确定问题原因。

> banjuer: 把原所有配置：数据里面的conf，.siyuan完全删除后好了。

> D: 这个应该不影响才对，就先这样吧。
>
> 下次使用的时候请继续留意观察，我关闭那个 issue 了。
