### ISSUE TITLE
Parse tree failed报错

### ISSUE THREAD

**Issue by Borluse** [siyuan-note/siyuan#2444]
### Describe the problem

更新到最新版后，编辑文件会报错
![JXIMQS%AP)61{JENK56M@~J](https://user-images.githubusercontent.com/317421/125909743-f7351dfd-0ae1-42ac-9b5f-15de578271cf.png)

之后这个文件就再也无法打开。查看.sy文件，发现文件没有写完

![W@ONDHAG(581TDP2N @9ESU](https://user-images.githubusercontent.com/317421/125909951-1bb1a6af-22c5-4011-bd86-1359e57fa5c1.png)

我目前使用了synology的drive对该目录进行同步

### Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by Borluse** [comment]
补充一下，使用管理员模式打开，似乎正常

**Comment by Borluse** [comment]
> 补充一下，使用管理员模式打开，似乎正常

时间长点还是会有问题，和管理员没有关系

**Comment by 88250** [comment]
请问是否使用了同步盘？

**Comment by 88250** [comment]
> 我目前使用了synology的drive对该目录进行同步

抱歉刚才看漏了……麻烦关闭同步盘以后再进行一下长时间测试，谢谢。

**Comment by 88250** [comment]
思源写文件的时候是锁定写入的，并且要文件完整写入以后才会关闭文件。

请看一下这个 .sy 旁边是否生成了带数字结尾的临时文件，如果有的话有两种可能：

1. 思源写入过程中被打断（比如掉电，进程崩溃等），这种情况下文件打开应该是乱码或者被大量空字节填充
2. 思源正准备写入，但是文件被其他进程占用导致无法写入（这个进程很可能是同步盘）

**Comment by Borluse** [comment]
关闭drive之后，确实没有再出现parse tree failed的报错。
因为我是用的nas，还是期望能解决一下这个问题。

**Comment by 88250** [comment]
这个问题应该无法解决……所有实时写入数据的本地软件应该都存在这个问题，思源目前是通过暂时锁定文件（一分钟内锁定）来尽量降低问题出现概率了，如果要完全避免的话只能一直锁定文件才行，但是这样的话第三方同步盘就没法同步文件了。

目前如果要完全避免问题，可以考虑在思源内核退出以后再打开第三方同步，或者用官方同步（预计本月底开始内测）。

我关闭问题了，如果还有建议请跟帖回复，谢谢。

**Comment by Borluse** [comment]
> 这个问题应该无法解决……所有实时写入数据的本地软件应该都存在这个问题，思源目前是通过暂时锁定文件（一分钟内锁定）来尽量降低问题出现概率了，如果要完全避免的话只能一直锁定文件才行，但是这样的话第三方同步盘就没法同步文件了。
> 
> 目前如果要完全避免问题，可以考虑在思源内核退出以后再打开第三方同步，或者用官方同步（预计本月底开始内测）。
> 
> 我关闭问题了，如果还有建议请跟帖回复，谢谢。

我比较疑惑的是，在之前的版本， 甚至是1.2.0的beta版本，都没有遇到过这个问题，只有在这个正式版本才出现问题。

**Comment by 88250** [comment]
@Borluse 锁定文件是在 beta12 以后引入的，之前也有陆续数据损坏的反馈，后来经过排查发现有一部分是因为网盘同步造成的。所以 beta12 改为锁定文件。

有一个可能性是网络质量和数据量影响，这一点还有待更多用户反馈情况。我个人觉得，如果要用同步盘，比较可靠的方法是启动思源之前同步一次，使用过程中不要同步，等思源内核进程退出以后再同步。

**Comment by Borluse** [comment]
> @Borluse 锁定文件是在 beta12 以后引入的，之前也有陆续数据损坏的反馈，后来经过排查发现有一部分是因为网盘同步造成的。所以 beta12 改为锁定文件。
> 
> 有一个可能性是网络质量和数据量影响，这一点还有待更多用户反馈情况。我个人觉得，如果要用同步盘，比较可靠的方法是启动思源之前同步一次，使用过程中不要同步，等思源内核进程退出以后再同步。

很难做这个操作，对使用者的要求偏高。

我觉得如果可以的话：
1. 提供一个选项，允许关掉文件锁。文件写坏的情况自己负责。
2. 或者能提供一个私有部署的同步服务器，类似joplin自己的server

使用同步盘的原因是我希望我的资料拿在我手里，不是说信不过思源，只是我想完全控制自己的数据。

**Comment by 88250** [comment]
思源支持通过 Docker 部署的，请看帮助中有介绍。
