### ISSUE TITLE
输入数字后的第一个句号，默认为英文句号

### ISSUE THREAD

**Issue by Mrxiang-Plus** [siyuan-note/siyuan#2451]
### In what scenarios do you need this function?
使用数字来标记章节号的时候，现在需要先切换到英文输入 " . " ，然后切换回来继续编辑

### Describe the optimal solution

对于typora这些编辑器而言，默认在数字后的句号为小数点。

### Other information

让记笔记的过程更舒适，跟符合中文输入习惯

**Comment by Vanessa219** [comment]
这个已经修改过了。你使用的版本是？或者看一下输入法的设置。

**Comment by 88250** [comment]
我这里试用微软/搜狗/百度输入法测试好像没发现问题，麻烦楼主再试下，能录屏演示最好，谢谢。

**Comment by Mrxiang-Plus** [comment]
我发现了，是输入法的问题，抱歉。
我把这个关了
