### ISSUE TITLE
HTTP服务器监听地址设置

### ISSUE THREAD

**Issue by hanson-l** [siyuan-note/siyuan#2453]
### In what scenarios do you need this function?

你好，请问桌面端是否能提供后端http服务器监听地址和端口的设置呢？
比如我想设置为127.0.0.1，只让本机访问

### Other information

谢谢大佬开发的软件，非常好用

**Comment by 88250** [comment]
目前是监听了全网卡（0.0.0.0），因为普通用户可能并不清楚如何固定 IP，这一点目前暂时不会改了，抱歉啊。
