### ISSUE TITLE
未使用的题头图不会自动删除

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#2454]
### Describe the problem

如果插入本地新的题头图并且随机切换为其它题头图，新的题头图不会自动删除并且不会出现在随机题头图库之中

![image](https://user-images.githubusercontent.com/47321059/126038767-118e299d-2cb5-4f99-a8a3-14f7eb73bccc.png)

### Version environment

* Version: 1.2
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
题头图是作为资源文件插入的，可通过清理未引用资源文件来删除。

随机图库目前不支持，这个后面再考虑，谢谢。
