### ISSUE TITLE
SQL查询实现单个字段的渲染

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#2455]
### In what scenarios do you need this function?

通过SQL查询内容块，但是渲染时只需要部分字段

比如下面这个SQL会渲染出所有文档块

```sql
select * from blocks where type = "d" and id in (select root_id from blocks where content like "%#贪心算法#%")
```

### Describe the optimal solution

渲染所有文档块的标题

```sql
select title from blocks where type = "d" and id in (select root_id from blocks where content like "%#贪心算法#%")
```

**Comment by 88250** [comment]
编辑器内的查询嵌入块不支持这样使用，原因是这样无法保证块的完整性，修改块数据会有问题，所以必须是 block 字段的全部投影。

这个后面会通过挂件块支持，示例 https://github.com/88250/Stairway-To-Heaven
