### ISSUE TITLE
设置 - 外观中增加“点击关闭按钮时的行为”

### ISSUE THREAD

**Issue by C3-DLearning** [siyuan-note/siyuan#246]
思源的界面最大化，其他窗口没有最大化，鼠标甩到屏幕右上角去关闭窗口时容易将思源直接关闭。
建议在设置中添加“点击关闭按钮时的动作”，内附两种思源的退出方式：1、退出思源笔记；2、最小化到系统托盘区，这样方便用户根据自己的习惯选择笔记退出方式

**Comment by 88250** [comment]
目前仅在 Windows 上有托盘，所以该特性仅在 win32 上实现 @Vanessa219
