### ISSUE TITLE
导入 Markdown 文档前进行重名检查

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#2464]
121，刚好碰到了类似的情形，文件太多，自己不知道有重名，导入无提示，之后发现有链接坏了，才排查发现原因。
希望能够改进导入流程，增加重名提示并要求用户选择，要么用户自己重命名，要么自动重命名（比如加数字后缀）

**Comment by 88250** [comment]
可能创建一个时间戳命名的文件夹来保存导入的文档比较好。
