### ISSUE TITLE
所有本地功能完全免费

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2471]
如果你为了某些本地特性而订阅了，请发邮件至 845765@qq.com  退款剩余时长，抱歉抱歉。

退款时间截至该 issue 发布上线之日。

**Comment by alanjustalan** [comment]
？？？这也太慈善了吧？

**Comment by alanjustalan** [comment]
会员看得有些五味杂陈哈哈

**Comment by 88250** [comment]
@alanjustalan 这不是慈善……这样做是为了思源更好地发展。

**Comment by chiao666** [comment]
导出word之类的功能免费了吗，看到定价对比说明中免费了，但实际无法使用

**Comment by 88250** [comment]
@chiao666 v1.2.2 发布以后就免费了。

**Comment by chiao666** [comment]
> @chiao666 v1.2.2 发布以后就免费了。

好嘞，牛牛牛！
