### ISSUE TITLE
任务列表前有的有 id，有的没有

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2489]
1	* {: id="20210722190444-ioycsgk"}[X] 1
  {: id="20210722190444-wlouj5m" updated="20210722190445"}

**Comment by xiaoyoucheng** [comment]
![image](https://user-images.githubusercontent.com/33143581/126728257-8134ef8f-2b9a-47da-936d-2ac81c2148a4.png)
![动画16](https://user-images.githubusercontent.com/33143581/126728266-9a5e8d06-75aa-4df4-9141-1b21c3b88801.gif)

嵌入块的查询语句时 `select * from blocks where( markdown like '- [ ]%' or markdown like '* [ ]%') and subtype = 't' and type = 'i' and box = 'Note'` 由于markdown 字段 不明的增加了id属性 所以导致SQL查询不出来
