### ISSUE TITLE
版本检测错误导致无法重启

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2497]
https://ld246.com/article/1626958041721

I 2021/07/22 18:13:18 working.go:310: port [6806] is opened, try to check version of running kernel
I 2021/07/22 18:13:18 working.go:320: version of the running kernel is the same as this boot [1.2.2-alpha1], exit this boot

**Comment by 88250** [comment]
社区帖子里反馈的问题主要是移动块性能不好，这个会在 v1.2.2 解决。
