### ISSUE TITLE
大纲能不能自动根据更新而全部展开

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#2499]
![anJdsZij3E](https://user-images.githubusercontent.com/11204422/126862247-3d9cd1e4-14e5-467e-99ea-14605e9c3dd9.gif)
老版本是一直展开的. 现在的这个不能了.

**Comment by 88250** [comment]
已在 https://github.com/siyuan-note/siyuan/issues/2476 中改进，请等 v1.2.2 发布以后看下，谢谢。
