### ISSUE TITLE
能不能提供一个选项, 不隐藏文件夹前的指示箭头

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#2503]
![AXCkCbLVgR](https://user-images.githubusercontent.com/11204422/126870038-f7e85814-0b9d-4302-ba3d-0b682403783e.gif)
创建文件的时候, 清楚的指导那边是文件夹, 哪边是文件还是方便很多的. 
现有的设置, 设计上有它的好处.
但给一个可以设置的选项应该也是合理的吧

**Comment by 88250** [comment]
你好，这个可以考虑自定义主题，目前暂时不考虑加开关了，谢谢。
