### ISSUE TITLE
在同一层级建文件夹, 希望可以不折叠同侧次其他已打开的文件夹

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#2504]
![LLGCebZ7yV](https://user-images.githubusercontent.com/11204422/126870180-1296e861-0133-48b3-aa78-12c1e4eff98d.gif)

如果需要建立一些复杂点的嵌套文件, 文件夹目录. 图中显示的问题就非常不方便. 
希望原来打开的文件夹状态不要发生变化

**Comment by 88250** [comment]
后面考虑，感谢建议。

**Comment by 88250** [comment]
我先关闭了，如果后面还有更多人反馈再重新考虑打开。
