### ISSUE TITLE
网页书签

### ISSUE THREAD

**Issue by ymguo-phy** [siyuan-note/siyuan#2508]
可以不可以做类似这样的网页书签块
![截屏2021-07-26 上午10 31 39](https://user-images.githubusercontent.com/77337499/126925153-ef140dfb-9c74-4b06-8525-eaf4b2ac6dd1.png)

**Comment by 88250** [comment]
之前有过提议 https://github.com/siyuan-note/siyuan/issues/1020 但是因为依赖网络，怕不稳定所以先搁置。
