### ISSUE TITLE
时序图元素添加添加「引用内容块支持」

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#2515]
环境：win10 v1.2.2

以下是在帮助文档/编辑器/排版元素中截图的。
![image](https://user-images.githubusercontent.com/33319484/127251363-630f4b3b-9ad4-4454-a597-d74f9a8bbc2c.png)

能否在图中，被红框标注的位置添加引用内容块支持，即能通过输入`((`就能触发内容块引用搜索。并且能够点击时序图里的元素，跳转到对应的块中。

**Comment by JokeenZhang** [comment]
这样就可以当成一个简单的概念图

**Comment by Vanessa219** [comment]
可参见 mermaid ，如果他不支持的话，我们也无法支持。目前他的 graph 是可以支持的 https://ld246.com/article/1620574303200
