### ISSUE TITLE
文档另存为模板

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2517]
https://ld246.com/article/1627437453385

**Comment by YJTZTMS** [comment]
不用Typora siyuan两边跑了😀

**Comment by 88250** [comment]
@YJTZTMS 这个预计至少要等几个月……

**Comment by YJTZTMS** [comment]
@88250 不着急，等得起

**Comment by oufu99** [comment]
看到这个功能了~希望那时候能一起上个模板按钮的功能 嗷嗷
