### ISSUE TITLE
打开文档位置后不会自动激活窗口

### ISSUE THREAD

**Issue by 18160701310** [siyuan-note/siyuan#2524]
![动画2](https://user-images.githubusercontent.com/84733506/127283461-9d9b63e2-de16-4a3c-b932-a74f5ad8fad3.gif)

**Comment by 88250** [comment]
我这里重现不了问题，估计得再收集一下其他用户的反馈，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果后续有收到更多人反馈会重开，谢谢。
