### ISSUE TITLE
alt+f4不是关闭窗口，变成结束进程了。。即使开了关闭到托盘也是结束进程

### ISSUE THREAD

**Issue by 18160701310** [siyuan-note/siyuan#2528]
alt+f4和窗口关闭按钮的事件应该是一样的

**Comment by 88250** [comment]
我这里测了下，Alt F4 不会退出内核，麻烦再试试看，谢谢。

**Comment by 18160701310** [comment]
> 船队，奥特F4奥克特·弗尔克·克斯坦，阿弗尔特·奥德·德福·奥德·德福
> 
> ![image](https://user-images.githubusercontent.com/873584/127295938-ac53cf5c-b168-49f6-899a-87594f27bc45.png)

不不，不是这个意思，我的意思是一般情况atl+f4是关闭窗口，并不是结束进程，而大多数软件也是这样的，这个并不需要做处理， 默认系统就是这样的
然后我开了关闭按钮后缩小到托盘中，alt+f4应该是和关闭按钮一样的事件
和关不关内核并没有关系，因为点关闭按钮也不会退出啊，因为只是关闭窗口
<img width="561" alt="Snipaste_2021-07-28_17-11-58" src="https://user-images.githubusercontent.com/84733506/127296583-79f93fdb-8dda-4eef-b88f-6f5a3b6f6c25.png">

**Comment by 18160701310** [comment]
然后我需要右键点托盘图标时那个quit退出，还能让我关闭内核，这两个是应该不冲突 的

**Comment by 88250** [comment]
现在并没有特殊处理过 Alt F4，都是系统默认行为。

**Comment by 18160701310** [comment]
> 现在并没有特殊处理过 Alt F4，都是系统默认行为。
如图，现在就是这样了，前面说的有点乱，总结一下就是：ALT+F4应该和点击关闭按钮是一个效果，而不是现在这样和托盘的quit一个效果，和 ”退出时关闭内核” 这个功能没有关系
![1](https://user-images.githubusercontent.com/84733506/127297632-db0940d3-d45d-4b10-b979-67e27ac89cde.gif)

**Comment by 18160701310** [comment]
> 现在并没有特殊处理过 Alt F4，都是系统默认行为。

抱歉前面说的有点乱，如图所示，总结一下就是：ALT+F4应该和点击关闭按钮是一个效果，而不是现在这样和托盘的quit一个效果，和 ”退出时关闭内核” 这个功能没有关系

https://user-images.githubusercontent.com/84733506/127298593-317940cd-469f-4a52-a1d1-2ee4d7843add.mp4

**Comment by 88250** [comment]
明白了，选项只做了点击关闭按钮时的处理，Alt F4 暂时不处理了。如果需要最小化的话可以用 Alt M
