### ISSUE TITLE
请问能不能弄像编辑器一样的代码提示？

### ISSUE THREAD

**Issue by BlackWhite2000** [siyuan-note/siyuan#253]

**Comment by 88250** [comment]
你指的是代码块编辑时么？如果是的话可能……短时间内支持不了。

**Comment by BlackWhite2000** [comment]
对 代码块编辑时  我刚才写代码时候突然反应过来没有提示不习惯哈哈 
没关系 不过如果未来支持那绝对舒服

**Comment by 88250** [comment]
未来也不一定能支持，这个事情比较复杂，建议还是在 IDE 里写好再贴过来。

我关闭 issue 了，谢谢支持老铁。
