### ISSUE TITLE
工作空间列表切换

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2535]
https://ld246.com/article/1627475047073

**Comment by Imatvoid** [comment]
这个是排期表里的工作空间快捷切换吗？
可以不点进设置，直接切的

**Comment by Imatvoid** [comment]
感觉把工作空间去掉，在文档树加一个专门的工作空间目录，这样更好

**Comment by 88250** [comment]
@lmatvoid 同时使用的话不行，只能切换。这个 issue 是在设置 - 关于那里把现在的文件夹选择改为记录已经选择过的工作空间路径，以列表的方式展现方便切换。

**Comment by Imatvoid** [comment]
@88250 在内测群里问了很多企业用户，大家现在都是手动改设置重启切换的，确实很不方便。
因为企业的数据肯定是不能同步的，但是往往工作中有一些个人的灵感需要记下来，这是私人的数据，不能区分的话对企业用户确实不太友好，除非用别的笔记软件，这里D大是否能再考虑下。
像eclipse / idea一样，支持在启动的时候选择工作空间，这样支持打开多个。

**Comment by 88250** [comment]
@Imatvoid 多开工作空间短时间内支持不了，等以后再看吧，我们还是先做切换。

**Comment by 2234839** [comment]
> @88250 在内测群里问了很多企业用户，大家现在都是手动改设置重启切换的，确实很不方便。
> 因为企业的数据肯定是不能同步的，但是往往工作中有一些个人的灵感需要记下来，这是私人的数据，不能区分的话对企业用户确实不太友好，除非用别的笔记软件，这里D大是否能再考虑下。
> 像eclipse / idea一样，支持在启动的时候选择工作空间，这样支持打开多个。

或许可以尝试使用 docker

**Comment by Imatvoid** [comment]
@88250 理解，希望长期计划内能支持

**Comment by Imatvoid** [comment]
@2234839 用docker再开一个？

**Comment by 2234839** [comment]
> @2234839 用docker再开一个？

是的，用 docker 就没有限制了

**Comment by Imatvoid** [comment]
@2234839 好的我去试试，thanks
