### ISSUE TITLE
Mermaid 可视化作图

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#254]
多数 MD 编辑器、笔记软件说的支持 Mermaid 也只是渲染支持，最终还是需要用户手打出一张图，远没有像 XMind 那样的思维导图软件直观，要是能实现 Mermaid 的可视化编辑，估计会是很难超越的 Feature。

毕竟没有参考，应该比 Typora 模式更难实现。或许可以加到长远计划中。

**Comment by 88250** [comment]
这要从长计议，现阶段不太可能去达成。无论如何，非常感谢提议。
