### ISSUE TITLE
docker部署1.2.3版拒绝访问

### ISSUE THREAD

**Issue by risoyo** [siyuan-note/siyuan#2542]
### Describe the problem

使用docker部署1.2.3版，拒绝访问一切连接

### Version environment

* Version: 1.2.3
* Operating system: centos
* Browser (if used): 

### Log File

思源笔记正常启动，但是连接被拒绝，尝试使用nginx反向代理，也被拒绝

不使用nginx：
docker启动命令：
`nohup docker run -v /home/dockerData/siyuan:/siyuan/workspace -p 6806:6806 b3log/siyuan --resident=true --workspace=/siyuan/workspace/ &`

浏览器访问被拒绝，本地curl被拒绝，netstat查看6806端口正常服务

![image](https://user-images.githubusercontent.com/11912562/127446494-95d68567-d32b-43f4-bb6b-5a5d0d374f23.png)

使用nginx：
nginx代理6806端口，
```
    server {
        listen       6806;
        server_name  localhost;
        location / {
            proxy_pass  http://127.0.0.1:6807;
        }
    }
```
docker启动命令：
`nohup docker run -v /home/dockerData/siyuan:/siyuan/workspace -p 6807:6806 b3log/siyuan --resident=true --workspace=/siyuan/workspace/ &`

访问时报错：
```
2021/07/29 14:43:15 [error] 18694#0: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 119.4.253.108, server: localhost, request: "GET /stage/build/desktop/ HTTP/1.1", upstream: "http://127.0.0.1:6807/stage/build/desktop/"
2021/07/29 14:43:15 [error] 18694#0: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 119.4.253.108, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:6807/favicon.ico"", referrer: "http://服务器IP:6806/stage/build/desktop/"
```

此时尝试在服务器curl访问，连接被拒绝
![image](https://user-images.githubusercontent.com/11912562/127446341-e7ee5027-5125-4c2e-87be-169d5844c43f.png)

**Comment by 88250** [comment]
`proxy_pass  http://127.0.0.1:6807;`

端口是 6806

**Comment by risoyo** [comment]
> `proxy_pass http://127.0.0.1:6807;`
> 
> 端口是 6806

d大您好，这里是因为之前服务器的防火墙策略放开了6806端口，所以在nginx端监听了6806，在docker部署时将本地端口的6807映射到容器中的6806

刚才也试了下docker部署使用6806，nginx监听6807来访问，nginx还是会报502 bad gateway
![image](https://user-images.githubusercontent.com/11912562/127490458-e51d98aa-7f6a-4bbf-a503-8c98c09620eb.png)

这是docker的启动命令
```
nohup docker run -v /home/dockerData/siyuan:/siyuan/workspace -p 6806:6806 b3log/siyuan --resident=true --workspace=/siyuan/workspace/ &
```

这是nginx的配置
```
    server {
        listen       6807;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            proxy_pass  http://127.0.0.1:6806;
        }
    }

```

这是nginx的报错
```
2021/07/29 20:16:36 [error] 27015#0: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 117.173.227.160, server: localhost, request: "GET /stage/build/desktop/ HTTP/1.1", upstream: "http://127.0.0.1:6806/stage/build/desktop/", host: "服务器IP:6807"
2021/07/29 20:16:36 [error] 27015#0: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 117.173.227.160, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:6806/favicon.ico", host: "服务器IP:6807", referrer: "http://服务器IP:6807/stage/build/desktop/"
```

此时尝试在服务器curl本地的url，报`Connection reset by peer`
![image](https://user-images.githubusercontent.com/11912562/127491200-d6343c85-77a3-431b-91e7-1b72f56b536e.png)

**Comment by 88250** [comment]
我暂时没有时间去排查细节，麻烦参考 https://ld246.com/article/1627480121372 试下，谢谢。

**Comment by Clouder0** [comment]
很多拒绝访问是这个配置项的影响：
  
![image](https://user-images.githubusercontent.com/41664195/127601219-931647ce-78dc-4550-8ed6-6dc6f58c532e.png)

在 `conf.json` 中启用，就能与之前版本一样直接访问了。可以参考 [这里](https://ld246.com/article/1627197890848#%E6%89%93%E5%BC%80-networkServe-%E9%85%8D%E7%BD%AE)。

**Comment by risoyo** [comment]
> 很多拒绝访问是这个配置项的影响：
> 
> ![image](https://user-images.githubusercontent.com/41664195/127601219-931647ce-78dc-4550-8ed6-6dc6f58c532e.png)
> 
> 在 `conf.json` 中启用，就能与之前版本一样直接访问了。可以参考 [这里](https://ld246.com/article/1627197890848#%E6%89%93%E5%BC%80-networkServe-%E9%85%8D%E7%BD%AE)。

感谢，在`conf.json`里面改了配置之后可以了
这里还有一点需要注意下，就是在改配置前要先docker stop，如果改了配置后再docker stop的话，修改的配置会被覆盖

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2549
