### ISSUE TITLE
面包屑导航列表使用第一个子块文本

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#2553]
### Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/31495943/127734712-e4c91711-7793-4022-b1f1-80cf17ecff08.png)

### Version environment

* Version: 1.2.3
* Operating system:  win10
* Browser (if used):

**Comment by 88250** [comment]
你好，目前容器块包含时面包屑导航的文本显示是这样的，你的建议是只显示第一个子块的文本吗？

**Comment by XinLi0111** [comment]
我的想法是只显示第一个最高级别的子块文本。理由有 3 点：
1. 子块内容太长，或子块层级比较多，则面包屑的导航能力就被大量内容污染了。我看到面包屑好像是做了文本长度限制。
2. 如果“第一级第二级别第三级”这个内容块已经包含了前面的内容，那么最后一级的“第三级”的作用是什么，列表的层级关系也不清楚了。
    如果“第一级第二级别第三级”这个内容块的文本是被限制显示后的，那么直接显示第一个块是不是相同的结果，都是限制了不完全显示整个内容块。

**其实都是做了限制，我觉得，直接显示第一个子块的前面多少字符，这样更好**，不知道 D 大有别的想法没？开发辛苦了！

3. 再比如像我这样的，重复嵌套容器块的（下图），面包屑导航感觉会有一定的误导性。
![image](https://user-images.githubusercontent.com/31495943/127735562-4fd454be-fa22-4b84-99c6-ad5daa03e22c.png)

**Comment by 88250** [comment]
列表块就按照你的建议改进一下试试，使用第一个子块文本，上线看其他用户反馈情况，谢谢。

**Comment by XinLi0111** [comment]
按我的理解，面包屑导航是一种层级关系的展现，那么列表项块的上一级不应该是列表块。

# 举例1：
面包屑导航：文档 > H标题1 > ·-列表项2 > ·-列表项2.2
```
# 标题1
- 列表项1
- 列表项2
  - 列表项2.1
  - 列表项2.2     _鼠标所在_
```
# 实际：
![image](https://user-images.githubusercontent.com/31495943/127737041-030f2727-4090-4efa-a141-a4155834e51b.png)


# 举例2：
面包屑导航：文档 > H标题1 > ·- **<empt>** ·-列表项2.2
```
# 标题1
- 列表项1
-  - 列表项2.1   _鼠标所在_   
```
# 实际
![image](https://user-images.githubusercontent.com/31495943/127737135-b723b08c-a0c0-403a-89e8-1cb41145447c.png)




# 举例3：

![image](https://user-images.githubusercontent.com/31495943/127736920-9bbe97e6-9c87-4b67-b77f-23b54934d496.png)




还有一个老问题，末端节点的面包屑导航总是落在文本块上，标题块和列表项块都是这样。不知道是不是相关的代码，可以一起处理下。

![image](https://user-images.githubusercontent.com/31495943/127736553-842efce9-779e-4ef5-a0c0-2fb48a5d1bd4.png)
![image](https://user-images.githubusercontent.com/31495943/127736558-9b6d68e7-7212-4a3a-8715-7774cb1e6bd6.png)

**Comment by XinLi0111** [comment]
第一个例子的图错了

**Comment by 88250** [comment]
举例一的情况会调整为如下：

![image](https://user-images.githubusercontent.com/873584/127739337-4c7302cf-09bd-4d56-a544-90daa48949f6.png)

举例二空列表项下的列表块还需要考虑 https://github.com/siyuan-note/siyuan/issues/2286

举例三的情况应该没问题，优先按容器块（而非标题块）处理层级。

最后一个老问题目前是已经处理过的结果了，即如果容器块下面包含多个叶子块的时候不进行简化，因为多叶子块是并列的，它们之间有上下文。目前的面包屑导航上没有体现出上下文关系，这个会在以后进行实现，将鼠标移到容器块上，可以竖向展现它的子块列表。

**Comment by 88250** [comment]
我先关闭了，如果需要讨论请随时跟帖，谢谢。
