### ISSUE TITLE
不允许创建以 `.` 开头的文档

### ISSUE THREAD

**Issue by mrjesen** [siyuan-note/siyuan#2556]
### Describe the problem

例如新建文档.aaa,未关闭笔记可以正常编辑，重启后无法打开且会自动消失，可能和隐藏文件文件机制有关？

### Expected result

重启后不会消失，且能正常编辑

### Screenshot or screen recording presentation

感觉描述的很清楚。

### Version environment

* Version: 1.2.3
* Operating system:  win10x64
* Browser (if used):  no

### Log File

nothing

### More information

nothing

**Comment by 88250** [comment]
是的，稍后会改进判断，不允许新建 `.` 开头的文件，避免后续问题，谢谢。

**Comment by mrjesen** [comment]
好家伙 ，直接ban了。

**Comment by 88250** [comment]
@mrjesen 是的……因为 ls 的时候也会跳过 . 开头的文件，为了保持一致性，就直接禁止在程序内创建了。
