### ISSUE TITLE
修改授权码后关闭会一直卡在数据写入

### ISSUE THREAD

**Issue by mrjesen** [siyuan-note/siyuan#2557]
### Describe the problem

修改授权码后关闭会一直卡在数据写入

### Expected result

不卡

### Screenshot or screen recording presentation

nothing

### Version environment

* Version: 1.2.3
* Operating system: win10x64
* Browser (if used): 

### Log File

nothing

### More information

nothing

**Comment by 88250** [comment]
是在退出的时候吗？

**Comment by mrjesen** [comment]
> 是在退出的时候吗？

是的，右上角❌

**Comment by mrjesen** [comment]
> 是在退出的时候吗？

是的，右上角❌

**Comment by 88250** [comment]
这个问题应该在 v1.2.3 上修复过 https://github.com/siyuan-note/siyuan/issues/2531

请再帮忙看下重现步骤，谢谢。

**Comment by mrjesen** [comment]
对的，是一样的步骤。 不好意思，我用的就是1.2.2版本
