### ISSUE TITLE
conf.json修改端口后前端无法访问

### ISSUE THREAD

**Issue by mrjesen** [siyuan-note/siyuan#2558]
### Describe the problem

conf.json修改端口后前端无法访问
也就是说，我想用其他端口来提供笔记服务。我通过命令`docker run -itd -p 1234:6806 xxxx`来启动docker服务
但是f12调试前端网页发现，依然在请求6806端口，而不是请求1234端口
建议把前端网页对应的6806端口改为变量，转为提取url中的端口。

### Expected result

提取url中的端口，而不是6806

### Screenshot or screen recording presentation

nothing

### Version environment

* Version:  ubuntu 20.04
* Operating system:  docker - 最新镜像
* Browser (if used): 

### Log File

nothing

### More information

nothing

**Comment by 88250** [comment]
端口是写死的，不支持更换。需要配置 NGINX 反代来更换端口，通过 `--servePath=ip:port` 来做访问端口。
