### ISSUE TITLE
资源管理器中修改文件名后的错误

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2576]
第一个是点了刷新，并不会改变文件树。
第二个是，点击编辑栏的标题，文件树会改名，但是点了刷新或者重启，名字又会变成旧的

**Comment by 88250** [comment]
用的是属性 `title` 来显示文档名，这里确实有不一致的地方，需要将文件名直接迁移到 id.sy 格式上 https://github.com/siyuan-note/siyuan/issues/2131
