### ISSUE TITLE
希望主题样式优先级是最优先

### ISSUE THREAD

**Issue by BlackWhite2000** [siyuan-note/siyuan#258]
比如我想改代码块的样式，因为不是最优先我就需要添加 !important。
这个添加多了的话我怕出问题

**Comment by Vanessa219** [comment]
主题样式使用了 Vditor 的模式，在思源中需要进行修改，请在该 issue 关闭后再进行自定义修改

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/504 中已修改
