### ISSUE TITLE
docker image 支持 arm 架构

### ISSUE THREAD

**Issue by guvmao** [siyuan-note/siyuan#2580]
期望 docker 镜像 增加 aarch64&Arm64 版本镜像

**Comment by 88250** [comment]
你好，这个暂时没有时间处理，等后面再考虑，谢谢。

**Comment by guvmao** [comment]
使用 docker buildx 可以非常方便快捷的构建 Arm 架构镜像，希望可以考虑~

**Comment by bitxel** [comment]
+1

**Comment by 2116259** [comment]
+1

**Comment by whuwangyong** [comment]
> +1

这个已经有了哦，8个月之前就有了。
https://hub.docker.com/r/b3log/siyuan/tags

**Comment by whuwangyong** [comment]
@2116259 

这个已经有了哦，8个月之前就有了。
https://hub.docker.com/r/b3log/siyuan/tags

**Comment by 2116259** [comment]
> @2116259
> 
> 这个已经有了哦，8个月之前就有了。 https://hub.docker.com/r/b3log/siyuan/tags

感谢！已经用上了。
