### ISSUE TITLE
文档导出为PDF时将文档树转换为PDF书签

### ISSUE THREAD

**Issue by wiketool** [siyuan-note/siyuan#2583]
### 文档导出为PDF时将文档树转换为PDF书签

如Typora中所做的一样，它将H1~H6的标题在导出时自动转换为了PDF的书签，方便快速导览

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/779

**Comment by wiketool** [comment]
好的，谢谢您
