### ISSUE TITLE
反链提及显示不全

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2589]

**Comment by Kitsuta-le** [comment]
可能因为内容是复制的
qq：Kitsuta

**Comment by 88250** [comment]
@Kitsuta-le 搜索 - 设置里面有个最大条数限制，配置大一点看看。

我先关闭了，这个问题等 v1.2.5 发布以后请帮忙进行回归测试，谢谢。

**Comment by Kitsuta-le** [comment]
感谢！问题已解决！后续会继续看看
