### ISSUE TITLE
1.2.31 内核中断，无法进入查看笔记，重启和重装都是这样

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#2597]
已提供日志：
[siyuan.log](https://github.com/siyuan-note/siyuan/files/6942541/siyuan.log)

还有就是当我退出坚果云之后，也还不能解决问题。

**Comment by JokeenZhang** [comment]
备份后，我把工作空间除了data以外的文件都删了才能进去

**Comment by 88250** [comment]
从日志上看是因为 `D:\UserDocuments\new_clound\INKPW\conf\conf.json` 这个配置文件被其他程序锁定或者修改过权限导致读取不了，所以内核启动失败。

这个问题在程序内解决不了，后面如果频繁出现请继续跟帖，我们进一步排查原因，谢谢。
