### ISSUE TITLE
可以增加缩放整个页面的功能吗？

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#26]
现在的字对我的小屏幕来说有些小，有没有简单的缩放功能提供呢？

**Comment by Vanessa219** [comment]
0.2.3 中实现

**Comment by zhl111** [comment]
我咋没找到呢？而且ctrl++木有反应，ctrl+-可以缩小，ctrl+0可以复原

**Comment by 88250** [comment]
@zhl111 Windows 上是 <kbd>Ctrl +</kbd>，请留意这个加号需要按 Shift，也就是 <kbd>Ctrl Shift =</kbd> 😅

**Comment by zhl111** [comment]
是有快捷键冲突？ob不需要按shift也可以放大哦

**Comment by Vanessa219** [comment]
0.2.4 已修复
