### ISSUE TITLE
Can NOT select multi-lines properly.

### ISSUE THREAD

**Issue by Lemoners** [siyuan-note/siyuan#2601]
### Describe the problem

When I try to select multi-lines for copy, I scroll down or move the cursor to the bottom, which should increase the selected area. However, in current version, I can't select lines with my cursor properly.

### Screenshot or screen recording presentation
> For example, when I try to select line `C-Z` using my cursor. In the end, only `U-Z` were selected.

https://user-images.githubusercontent.com/39124095/128516422-43012a9b-03e9-4b7c-9eb0-46444308d081.mp4

### Version environment

* Version: v1.2.31
* Operating system: Windows
* Browser (if used): None

**Comment by 88250** [comment]
Please refer to https://github.com/siyuan-note/siyuan/issues/2066, thanks.
