### ISSUE TITLE
列表项块转换为文档块

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2610]

**Comment by fanglypro** [comment]
列表块转换文档个人认为价值有限，更加重要的应该是列表项转换文档。
列表项父结点对应文档标题，子列表块对应文档内容。
这可以和标题转换文档对应，列表项父结点对应标题，子列表块对应标题下面的内容。

**Comment by 88250** [comment]
@fanglypro 嗯，子列表转文档的时候可以用这个逻辑。

**Comment by fanglypro** [comment]
> @fanglypro 嗯，子列表转文档的时候可以用这个逻辑。

这时候涉及到一个我觉得很关键的逻辑问题，就是转换后的文档id选用原先的哪个id

如果用户是把一个列表项拖拽到文档树中，此时我认为，新文档的id应该是列表项的id

如果用户是把一个列表块拖拽到文档树中，此时新文档的id应该是该列表块的id，然后如果有父结点，就选用父结点作为文档标题

我看您回复的意思好像是觉得列表项转换文档可以用子列表块转换文档替代，这我觉得是一个非常危险的思路，因为有用户会引用列表项，只是使用子列表块转换文档的话，这些对原列表项的引用就全部失效了。

事实上，与标题转换文档对应，我们是把标题拖拽到文档树中，在列表中与标题对应的应该是列表项而不是列表块，所以更自然的想法是拖拽列表项而不是子列表块，直接按住列表中的圆点拖到文档树中这应该是是比较自然的动作

简单来说，我的诉求就是：列表项转换文档后文档id为原列表项的id，列表块转换文档后文档id为原列表块的id

**Comment by fanglypro** [comment]
再举个例子，在标题转文档中：
# 要点一

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

# 要点二

Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. nesciunt.

# 要点三

At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.

比如我要把要点二转文档，我应当拖拽要点二旁边的标题块标识到文档树中

在列表转文档中：

- 要点一
  - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
- 要点二
  - Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. nesciunt.
- 要点三
  - At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.

此时，和前面标题转文档对应，如果我想要把要点二转文档，应当是拖拽要点二旁边的圆点到文档树中，而不是拖拽要点二下面的内容

**Comment by deerainw** [comment]
补充一个小例子，在下面这张图里，如果想转换出一个名字叫 A，正文是 BC 的新文档，这里没有对应的列表块，只有一个列表项块能对应 ABC 这个区域

![image](https://user-images.githubusercontent.com/32661922/131465954-35710d5d-6112-4b76-a51f-98f7ac92e9e7.png)

**Comment by fanglypro** [comment]
刚刚看到个视频案例，在这里补充下：[How to convert block references to page references in Roam Research
](https://www.youtube.com/watch?v=Vc2ZhH9g0j8)

可以看到在roam research里面想要把块引用转化为页面引用需要通过复杂的奇淫技巧才能实现，而如果思源能实现列表项（不是列表块）转化文档的话，只需要将列表项的圆点拖拽到文档树中就结束了，完爆视频里的操作

**Comment by 88250** [comment]
@fanglypro @deerainw 感谢两位帮忙梳理思路，列表块转换确实有点问题，列表项转换比较自然。如果有一种情况是列表项里面包含了行级排版元素（特别是包含块引）时，转换为文档标题后这个信息会丢失，因为文档标题不支持行级元素。这个点两位有空帮忙看看吗？
