### ISSUE TITLE
Breadcrumb sibling navigation

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2613]
https://ld246.com/article/1628497639952
- [ ] 支持快捷键操作

**Comment by TCOTC** [comment]
参考「(伪)文档面包屑」插件的功能，仓库：https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb

**Comment by AvoidantPerDis** [comment]
对于超长文档（100w+，我把实体书导入为一个文档的，这样不用开很多页签）还是用这个功能好，大纲太卡了

**Comment by 88250** [comment]
已经有插件支持，暂时不考虑了。

**Comment by TCOTC** [comment]
### 01

- 按钮没有间距
- 空块不必显示文本，留空才能直观知道这是个空块

<img width="687" height="566" alt="Image" src="https://github.com/user-attachments/assets/f68e4d43-922c-4b0e-8948-d86817438a31" />

<img width="234" height="185" alt="Image" src="https://github.com/user-attachments/assets/c90a3dd8-330f-4354-ae34-a17e2e26b6f2" />

**Comment by 88250** [comment]
01 done
