### ISSUE TITLE
支持内容块折叠

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#262]
* 支持非文档块的内容块（包括容器块和叶子块）折叠
* 折叠后支持拖拽移动
* 标题块折叠需要包含其下方内容块

## 持久化状态

* 折叠状态通过块属性持久化
* 引用计数显示

**Comment by deerainw** [comment]
块的上下拖动好像已经安排上了 #226 ，如果折叠之后依然能拖动就非常舒服了

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/101845832-9a965080-3b8a-11eb-8319-6e08a71881f9.png)

**Comment by 88250** [comment]
> 块的上下拖动好像已经安排上了 #226 ，如果折叠之后依然能拖动就非常舒服了

标题块的包含拖动后续改进 https://github.com/siyuan-note/siyuan/issues/963
