### ISSUE TITLE
无法上传备份upload failed

### ISSUE THREAD

**Issue by abtxu** [siyuan-note/siyuan#2622]
windows 7 系统，
当前版本 v1.2.31 / Kernel v1.2.31
upload failed: auth failed rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3], exit status 12

**Comment by 88250** [comment]
抱歉，刚刚云端服务出了点问题，现在已经恢复。
