### ISSUE TITLE
重启思源导致列表背景色丢失

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#2629]
### Describe the problem

重启思源导致列表背景色丢失。

复现：
`- 测试***（测试）***`

![de7eae91933bb8a273caf7c8623d51f](https://user-images.githubusercontent.com/47321059/129440424-2413de29-5b33-4ee0-bbe8-67c6e167c34b.png)

![image](https://user-images.githubusercontent.com/47321059/129440434-dfb52acf-e52f-4023-b12a-2ebf18d4c2ed.png)

### Version environment

* Version: 1.2.31
* Operating system: win10
* Browser (if used):

**Comment by Vanessa219** [comment]
重现不了，用默认皮肤试试？

**Comment by dejavudwh** [comment]
> 重现不了，用默认皮肤试试？

![1](https://user-images.githubusercontent.com/47321059/129442324-355a5841-64cc-46a6-91b0-1f6daf6a523d.gif)

**Comment by Vanessa219** [comment]
可以重现了，下个版本修复，谢谢反馈
