### ISSUE TITLE
Figure size can’t be saved

### ISSUE THREAD

**Issue by feima1992** [siyuan-note/siyuan#2632]
### Describe the problem

Figure size can’t be saved. After resizing a figure and reopen that file, the figure size will be reset to 100%.

### Version environment

* Version: v1.2.31 / Kernel v1.2.31
* Operating system: windows 10
* Browser (if used):

**Comment by 88250** [comment]
Hello, I can't reproduce it now. If it is convenient, can you provide a screen recording demonstration? Thanks.

**Comment by feima1992** [comment]
![XUyty3394Z_new](https://user-images.githubusercontent.com/68376720/129575548-b79e6a65-30ec-46db-8153-04bb61152d0b.gif)

**Comment by 88250** [comment]
Please wait for the release of v1.2.5 and then help to see if it is normal, thank you.
