### ISSUE TITLE
过多的”请从这里开始“

### ISSUE THREAD

**Issue by risoyo** [siyuan-note/siyuan#2633]
### Describe the problem
不清楚算不算bug，但是确实有点影响使用了。。
docker部署，每次打开网页后都会跳到”请从这里开始“，如果不手动关闭的话就会越累积越多，一天下来就会变成这样

![image](https://user-images.githubusercontent.com/11912562/129467875-f78de18a-83f7-4ac4-a1c2-d005e8883cb9.png)

### Expected result

能否为启动默认打开帮助页面加一个开关，或者检查到已经打开了”请从这里开始“页面后跳到这里都可以
现在这样的话自己打开的笔记没多久就淹没在一片”请从这里开始“里面了

### Version environment

* Version: 1.2.3.1，docker部署
* Operating system: centos
* Browser (if used): chrome、edge

**Comment by risoyo** [comment]
这是设置-文档树的配置内容
![image](https://user-images.githubusercontent.com/11912562/129470728-06458b97-c344-4d24-846f-2bfa2e6ec340.png)

**Comment by 88250** [comment]
请升级到最新版应该就没有了。
