### ISSUE TITLE
docker部署后移动端报错

### ISSUE THREAD

**Issue by w-shadow** [siyuan-note/siyuan#2638]
### Describe the problem
docker部署后移动端报错

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/60930949/129550660-cceaabfb-859c-47b1-9c11-c9c329ed06d4.png)

### Version environment

* Version: 1.2.31
* Operating system: centos docker
* Browser (if used): chrome

**Comment by 88250** [comment]
请打开 F12 看下 Network 中加载 lute.js 的请求是否完成。

![image](https://user-images.githubusercontent.com/873584/129551446-4e5d3cf7-39d6-4e81-baff-ae7e7c94ce8f.png)

**Comment by w-shadow** [comment]
![image](https://user-images.githubusercontent.com/60930949/129555752-04f9d2ef-71f8-47f4-bb57-3a0960aa3698.png)

我解析了域名并配置了ssl和反向代理，在桌面端访问无异常，但是无法在移动端的浏览器中打开。

**Comment by 88250** [comment]
浏览器仅支持 Chrome 新版内核的，可能是这个原因。

**Comment by w-shadow** [comment]
我用的就是最新的chrome，/lute.min.js.map报错404，在访问stage/build/desktop/时没有uncaught typeerror的报错，但是在stage/build/mobile/的时候报错就出现了，无论是实际在手机上操作还是在浏览器的toggle device toolbar中换成手机都会有问题。
附上链接：https://note.back2me.cn

**Comment by 88250** [comment]
* lute.min.js.map 报错不要紧
* 有访问授权码进不去

这个问题暂时先搁置一下，等 v1.2.5 发布以后再看，谢谢。

**Comment by 88250** [comment]
你好，思源新版已经发布，如果有空的话请测试一下，我先关闭该 issue 了，如果有问题请随时跟帖，谢谢。

**Comment by w-shadow** [comment]
问题解决了！
