### ISSUE TITLE
提议将局部关系图中Heading按照层级显示成树状结构

### ISSUE THREAD

**Issue by shshsunny** [siyuan-note/siyuan#264]
即，所有的H2节点连接到上级H1节点而不是直接连到文件节点，H3节点连接到上级H2节点而不是直接连接到文件节点……以此类推,形成多层树状结构。
这样节点的层级关系在关系图上显示更清晰一些。
下面是一个Heading层级很多（有H1~H3）的MD文件，已经明显看出显示节点数量太多，杂乱无章。
![image](https://user-images.githubusercontent.com/35917471/96359588-1c4b9e00-1147-11eb-988a-6bb241bcbcc8.png)

**Comment by 88250** [comment]
感谢反馈，之前已有提议，请关注 https://github.com/siyuan-note/siyuan/issues/62
