### ISSUE TITLE
目录可同时作为笔记

### ISSUE THREAD

**Issue by xianjie-li** [siyuan-note/siyuan#2642]
### In what scenarios do you need this function?

通常一篇文章下会关联很多个块或者子页面, 将这些内容作为笔记的子级管理会比拆分开更容易管理和理解。

![image](https://user-images.githubusercontent.com/34636376/129682149-bc4935fc-b48f-4575-ae09-6dc060b9d3e4.png)

<br/>

### Describe the optimal solution

✨ 将目录和文章都归为节点，每个节点既可以是文章，也可以包含子节点, 文章内通过块链新建的块都自动作为该页面的子节点。

💥 值得注意的一点是展开节点的逻辑 之前用的一款软件是点击节点开启节点页面，左侧icon控制节点展开

![image](https://user-images.githubusercontent.com/34636376/129682809-94f58af8-abf4-406e-b731-9083106e2062.png)

**Comment by 88250** [comment]
你好，这个将在 v1.2.5 https://github.com/siyuan-note/siyuan/issues/2304 中完成，预计本周内会发布，谢谢。
