### ISSUE TITLE
启动异常，一直卡住不动

### ISSUE THREAD

**Issue by nldgaole** [siyuan-note/siyuan#2643]
启动思源的时候一直卡住不动，删除用户下的.siyuan等文件都不行。

**详情：**

1. 版本siyuan-1.2.5-alpha5-win
2. 系统win11
3. 目前状态![image.png](https://b3logfile.com/file/2021/08/image-75ad92e1.png)
4. 删除用户下的siyuan文件夹也不能解决![image.png](https://b3logfile.com/file/2021/08/image-e666662d.png)
5. 工作空间已经整体备份，且原位置文件已经删除。
6. 以上均无法解决问题，特此向论坛大佬求助，谢谢！

**Comment by 88250** [comment]
麻烦上传一下工作空间/conf/siyuan.log

**Comment by nldgaole** [comment]
> 麻烦上传一下工作空间/conf/siyuan.log
[siyuan.log](https://github.com/siyuan-note/siyuan/files/7010978/siyuan.log)
最后的日志文件可能是这个，D大辛苦

**Comment by 88250** [comment]
从日志上看应该是因为 6806 端口没有权限，请看下防火墙配置，另外，也有可能是因为这个 https://ld246.com/article/1627667145070 导致。

我先关闭了，如果还有问题请随时跟帖，谢谢。
