### ISSUE TITLE
支持设置编辑器只读模式

### ISSUE THREAD

**Issue by Mrxiang-Plus** [siyuan-note/siyuan#2648]
### In what scenarios do you need this function?

阅读模式/文件锁

在阅读模式/文件锁下，文件只能读，不能修改
因为有时候读笔记没有修改的意愿，不小心的拖动就导致某些改动

### Describe the optimal solution

方案一：阅读模式，所有文件只能读
方案二：文件锁，可以对指定文件进行加锁/解锁

### Other information

个人觉得，使用场景还是蛮多的

**Comment by 88250** [comment]
感谢反馈，后期考虑。

**Comment by Zuoqiu-Yingyi** [comment]
目前可以使用 *导出预览模式* 先顶顶

**Comment by TankNee** [comment]
移动端很需要这样的只读功能。

**Comment by 88250** [comment]
@TankNee 移动端默认就是只读的。

**Comment by TankNee** [comment]
@88250 我在iPad上使用思源笔记的时候会直接进入编辑模式。

**Comment by Zuoqiu-Yingyi** [comment]
> @TankNee 移动端默认就是只读的。

貌似还能通过块标拖动

**Comment by 88250** [comment]
@TankNee 哦，Pad 端和桌面一样，没有算作移动端。

**Comment by Mrxiang-Plus** [comment]
我觉得单独的文件锁，是个比较好的方案。
我去研究一下代码实现。

**Comment by joyhu** [comment]
> ### In what scenarios do you need this function?
> 阅读模式/文件锁
> 
> 在阅读模式/文件锁下，文件只能读，不能修改 因为有时候读笔记没有修改的意愿，不小心的拖动就导致某些改动
> 
> ### Describe the optimal solution
> 方案一：阅读模式，所有文件只能读 方案二：文件锁，可以对指定文件进行加锁/解锁
> 
> ### Other information
> 个人觉得，使用场景还是蛮多的

非常需要此功能，一直以来都想找一个笔记软件，即可以离线使用(经常在机房处理故障，需要截图或记录信息)，这些问题思源现在都已经可以完善的解决，但还需要将自己本地整理好的一些笔记同步到互联网上的思源笔记作为知识库共享，但是现在是只要能打开就能编辑，这就非常麻烦。

**Comment by 88250** [comment]
@joyhu Docker 部署的话看下内核 `readonly` 参数。

**Comment by ballghost** [comment]
这个功能啥时候支持啊，都一年多了，经常无意间编辑了都不知道

**Comment by 88250** [comment]
@ballghost 近期版本会开展。

**Comment by terwer** [comment]
终于开始了，太需要这个功能了，D大加油💪🏻。
