### ISSUE TITLE
日志（dailynote）文件夹无法移动

### ISSUE THREAD

**Issue by abtxu** [siyuan-note/siyuan#2650]
右键选择移动，然后在搜索框中无法移动到当前文件夹之外的文件夹
即便移动了，按alt+5也是在原来的文件夹创建

**Comment by 88250** [comment]
* 试试在文档树上直接拖拽移动
* 日记的保存路径需要在设置中配置

**Comment by abtxu** [comment]
日记的保存路径需要在设置中配置
已经找过了，找不到才来问的

**Comment by 88250** [comment]
@abtxu 

右键笔记本 - 设置 - 新建日记 - 存放路径

**Comment by abtxu** [comment]
感谢回答。
另外问一下，文档树基层笔记本如何排序，目前的排序都是针对笔记本之下的笔记的排序

**Comment by 88250** [comment]
笔记本还不支持排序，以后考虑。

**Comment by abtxu** [comment]
> * 试试在文档树上直接拖拽移动
文档树中的拖拽不能实现跨文件夹的移动

**Comment by 88250** [comment]
等 v1.2.5 发布，谢谢。

**Comment by abtxu** [comment]
感谢答复！
