### ISSUE TITLE
思源笔记的剪藏功能如何使用？

### ISSUE THREAD

**Issue by abtxu** [siyuan-note/siyuan#2652]
安装思源笔记的Chrome拓展，选中复制到思源，提示我在思源笔记中粘贴，但如果还要自己粘贴的话，不用这个拓展直接复制和粘贴不是完全一样吗？

至于用WebClipper，在登录账号这一关就过不了，因为添加账户那里也没有思源笔记的选项。

**Comment by 88250** [comment]
* 用剪藏扩展的话可以将图片拉取到本地，不过现在还不稳定，v1.2.5 以后会稳定一些
* Web Clipper 目前应该是只有测试版支持
