### ISSUE TITLE
cannot exit in ubunut20.04

### ISSUE THREAD

**Issue by Jowisdom** [siyuan-note/siyuan#2653]
# problem of description
when launch siyuan at fisrt, I cannot exit. So I choose to quit at dock by right key. HOWEVER, when I relaunch siyuan, the error happens.
> A Javascript error occurred in the main proccess

# solution
 I enter the .config and delte the Siyuan dir. Then I relaunch the app without error.

**Comment by 88250** [comment]
Thank you for sharing the feedback. Close it first. If you still have any questions, please continue to post.
