### ISSUE TITLE
卡booting

### ISSUE THREAD

**Issue by nldgaole** [siyuan-note/siyuan#2655]
6806还是没法正常调用，关闭端口也不行，求助

**Comment by 88250** [comment]
麻烦发一下内核日志，工作空间/conf/siyuan.log

**Comment by baozilala** [comment]
卡boot界面的话，我是卸载关机重启然后再安装就好了。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请跟帖反馈，谢谢。
