### ISSUE TITLE
笔记录音问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#266]
使用 `<audio>` 标签 src 会有路径问题。

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/97251381-b778fd80-1842-11eb-9f56-9a2a5ac54207.png)

**Comment by 88250** [comment]
src 请求路径问题已在 v0.4.6 中修复。目前的问题是上传 wav 以后插入 DOM 没有更新 md。
