### ISSUE TITLE
块引新建文档存放位置 删除后没有更改

### ISSUE THREAD

**Issue by baozilala** [siyuan-note/siyuan#2667]
### Describe the problem

旧版本设置了：块引新建文档存放位置
将目录设置到了： /articles
新版本删除了此设置。但是实际却没有修改成功。还是会自动默认创建到之前设置的文件夹内。

### Expected result

问题修复

### Version environment

* Version: 1.2.5
* Operating system: win 10
* Browser (if used): no

**Comment by 88250** [comment]
你好，这个配置有两个地方：

* 全局配置（设置 - 文档树）
* 笔记本配置

是不是有个地方没有修改？

**Comment by baozilala** [comment]
是的，谢谢D大。问题解决了。

**Comment by baozilala** [comment]
是的，谢谢D大。问题解决了。
