### ISSUE TITLE
多级hover浮动的内容块层级错误

### ISSUE THREAD

**Issue by kaiaiz** [siyuan-note/siyuan#2670]
### Describe the problem

操作复现：以‘思源笔记用户指南’为例，打开‘0 什么是内容块’，hover层级依次是 嵌入内容块-这里-这里。

### Expected result

后浮动的内容块应在最上层，但是在最底层
### Version environment

* Version: 1.2.5
* Operating system: win7
* Browser (if used): 

### More information

[Video_20210821143314.zip](https://github.com/siyuan-note/siyuan/files/7025039/Video_20210821143314.zip)

**Comment by Vanessa219** [comment]
如果有点击过的话，点击的那一层将会在最上层
