### ISSUE TITLE
头图上传插入去重

### ISSUE THREAD

**Issue by liuyike98** [siyuan-note/siyuan#2681]
### In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/87092276/130340379-304856b8-6a95-43e3-8c46-5f8ed6154781.png)
多个文档都是用的一个头图，需要多次选择文件并且占用多倍空间，可否优化一下。

还有能否加入自定义外部链接设置为头图？

### Describe the optimal solution

允许设置外部链接为title-img的background

**Comment by 88250** [comment]
外部链接暂时不考虑，先改去重，谢谢。
