### ISSUE TITLE
选中文字背景颜色与加粗冲突

### ISSUE THREAD

**Issue by liuyike98** [siyuan-note/siyuan#2688]
### Describe the problem
在选中文字后，选择文字背景色，会将范围内文字标记为strong，同时，取消加粗，或者将已经标记背景颜色的区域置为斜体，会自动把背景颜色去除，此处是否应为设置为span？
![image](https://user-images.githubusercontent.com/87092276/130364477-052535eb-2f22-4b70-8cc2-cd67a028277c.png)

**Comment by 88250** [comment]
工具栏暂时不支持交叉和包含，这个等后面再做，我先关闭了，谢谢。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2911
