### ISSUE TITLE
assets 资源文件展现

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#27]
可否让其显示存在的图片呢？像obsidian那样。
或者干脆不显示，我倾向第一种。

**Comment by 88250** [comment]
计划是要显示里面资源文件的，只是还没来得及实现，稍后会尽快，感谢。

**Comment by 88250** [comment]
v0.2.4 中只做了文件树上的 assets 文件列出，打开具体资源文件后续在 https://github.com/siyuan-note/siyuan/issues/120 中完成。
