### ISSUE TITLE
选中文本按'Ctrl alt A'快速设置命名

### ISSUE THREAD

**Issue by zhangzz66** [siyuan-note/siyuan#2702]
类似选中文本按'ctrl k'快速设置超链接

**Comment by GuangDai** [comment]
不建议，因为这个快捷键习惯用QQ截图了

**Comment by zhangzz66** [comment]
> 不建议，因为这个快捷键习惯用QQ截图了

重点不是快捷键，快捷键是可以换的

**Comment by GuangDai** [comment]
emmm，那确实，是可以考虑

**Comment by 88250** [comment]
https://ld246.com/article/1630485682505
