### ISSUE TITLE
虚拟引用对英语使用空格分词

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2703]
![截屏2021-08-24 上午11 55 20](https://user-images.githubusercontent.com/77337499/130553381-8417a683-a360-4630-a1d1-0c1eff1b5f92.png)
我有点说不清楚,大概意思就是对于英语和数字的话,最好是作为一个整体去检索,这里出现了 anywhere这个单词,结果被索引的部分是单词中here.

第二个问题是这里的数字1也出现了隐痛,但是1都是出现在10或者0.1 这样的东西中的

还有就是,我有个疑问,就是比如说一个单词 plank constant(普朗克常数),而我有一个页面叫做plank constant,一个页面叫做 constant.结果虚拟引用的结果是指向constant.我想让他不显示constant这个关键词,而是显示plank constant.能否通过关键词进行屏蔽.屏蔽所有 单个的constant,但是保留类似 plank constant,boltzman constant之类的关键词

**Comment by 88250** [comment]
目前还没有做分词处理，后面改进。
