### ISSUE TITLE
子文档导航

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2711]
https://ld246.com/article/1629824751470

考虑结合挂件来做，通过选项默认在文档开头或者结尾插入挂件。

**Comment by leolee9086** [comment]
如果操作习惯是在父文档下建立大量子文档的话，父文档显示子文档导航会不会带来性能下降的问题？？

**Comment by 88250** [comment]
这个可以用现有的配置 `列出最大数量` 来限制。

目前这个特性还有待考虑，不急着做。

**Comment by yangzj1992** [comment]
挂件的机制思路目前是这个么：https://github.com/siyuan-note/siyuan/issues/1488？
目前看集市也还没有挂件项，还在 Draft 状态是么？

**Comment by 88250** [comment]
@yangzj1992 是这个机制，目前挂件集市已经对订阅用户开放测试，等 v1.8.0 后会正式上线。

**Comment by hwlts** [comment]
这个功能进入开发计划了吗？

**Comment by 88250** [comment]
@hwlts 已经移到 Idea 中，靠社区扩展实现。

**Comment by hwlts** [comment]
> @hwlts 已经移到 Idea 中，靠社区扩展实现。

是用这个插件吧？
https://github.com/OpaqueGlass/listChildDocs

**Comment by hwlts** [comment]
> @hwlts 已经移到 Idea 中，靠社区扩展实现。

https://github.com/OpaqueGlass/listChildDocs 是指这个挂件吧？

**Comment by 88250** [comment]
也许还有其他的，我没有太多了解，见谅。
