### ISSUE TITLE
文档图标支持自定义

### ISSUE THREAD

**Issue by mohuishou** [siyuan-note/siyuan#2724]
参考 notion，可以直接填一个链接地址，包括 base64 的图片链接

![image](https://user-images.githubusercontent.com/15172509/130814403-cc82a2ff-ce47-4fc5-a7c5-163df92d719f.png)

**Comment by 88250** [comment]
自定图标正在做 https://github.com/siyuan-note/siyuan/issues/2654

暂时不支持直接外链，感谢提议。
