### ISSUE TITLE
BUG,Del没有删除文档树笔记而是删除笔记内容

### ISSUE THREAD

**Issue by xBLACKICEx** [siyuan-note/siyuan#2727]
有bug,我用虚拟键盘模拟了下，没有删除笔记删除的笔记内容，真。键盘一个问题
#2698 
![Animation](https://user-images.githubusercontent.com/51036094/130823655-0093bad2-7e74-4778-8d58-ab97548b0258.gif)
![image](https://user-images.githubusercontent.com/51036094/130823864-782b347d-6a15-4a99-b1d2-ebdd51e0059a.png)

**Comment by 88250** [comment]
感谢反馈，在 https://github.com/siyuan-note/siyuan/issues/2719 中修复。
