### ISSUE TITLE
桌面端启动检查端口改进

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2734]
* 6806 是否被占用，已占用的话还需判断是否是已有内核
* 6806 是否能够监听，排除 #2565 中的情况

如果端口不能使用，则弹框提示。

**Comment by clasy0947** [comment]
能否支持修改默认的6806端口

**Comment by 88250** [comment]
@clasy0947 目前支持不了。

**Comment by jaamyang** [comment]
貌似这个问题还是没有解决
