### ISSUE TITLE
面包屑导航添加切换快捷键

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#2760]
![J5FY`G2DZW8MXZQF~EJJ_BK](https://user-images.githubusercontent.com/88605687/131206445-3559269b-ce6e-41f0-bc99-89dc8c4fb2ae.png)
如此可以配合搜索中展开的功能！

**Comment by 88250** [comment]
准确说应该是面包屑导航提供快捷键？

**Comment by Kitsuta-le** [comment]
> 准确说应该是面包屑导航提供快捷键？

我不太知道面包鞋是什么。。。就是箭头标的那一行。要在搜索中展开容器就必须点前面的那一栏（现在只有段落），所以有个快捷键能左右切换就很好

**Comment by Kitsuta-le** [comment]
> 准确说应该是面包屑导航提供快捷键？

我不太知道面包屑是什么。。。就是箭头标的那一行。要在搜索中展开容器、查看容器就必须点那一行（现在只有段落），所以有个快捷键能左右切换就很好

**Comment by 88250** [comment]
嗯，那一行就是面包屑导航了，我们考虑下，后面应该会支持快捷键选择。

**Comment by Kitsuta-le** [comment]
> 嗯，那一行就是面包屑导航了，我们考虑下，后面应该会支持快捷键选择。

嘻嘻 D大加油

**Comment by 88250** [comment]
暂时不考虑了，等以后如果有类似需求再考虑，感谢理解。
