### ISSUE TITLE
反链面板层级、上下文和移动改进

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2762]
* https://ld246.com/article/1630135656996
* https://ld246.com/article/1630268678551
* https://ld246.com/article/1632023007590

**Comment by deerainw** [comment]
在其它大纲双链笔记里，反链的层级选择在技术上不是难关，但是具体选择哪几个层级来展示还是很有讲究的，主要有下面这几个现成作业。

首先，按照 conor 工作流，在 daily notes 页面写下：

```markdown
- [[bar]]
    - sth about bar
        - sub bullet
```

然后在名叫 `foo` 的页面里写下这样的内容：

```markdown
- 1
	- 2
		- 3 - [[bar]]
			- 4
				- 5
					- 6
```

对于上面的内容，几个做得比较好的大纲双链笔记是这么展示层级的：

## roam research

![image](https://user-images.githubusercontent.com/32661922/131220502-c0030b49-cd2f-4294-b61d-3410b6082654.png)

## 葫芦笔记

![image](https://user-images.githubusercontent.com/32661922/131220569-3af20680-f570-4309-8c26-9701d887642c.png)

## logseq

![image](https://user-images.githubusercontent.com/32661922/131220579-e0ef1cae-19b5-48e8-acfd-31031b5f4b63.png)

## roam edit

![image](https://user-images.githubusercontent.com/32661922/131220595-d98b5ab4-3634-4b05-9311-71f9107b9783.png)

## 层级选择规律

总的来说，反链层级选择这件事情，还是 roam research 和 logseq 做得最好。

在 daily notes 工作流里，`[[bar]]` 这个链接的用途就是把自己的下级节点传递给 `bar` 这个页面，姑且叫它**传递型双链**，daily notes 里的这种链接不会有更上级的节点，所以 roam research 的反链里展示的是 `[[foo]]` 这一行和它的第一子级。第一子级下方的内容被折叠起来了，于是 daily notes 的这段内容在 `bar` 的反链里只展示了两行，避免过多占用反链的展示空间。logseq 也是这么做的，其它另外两个软件的理解就稍微欠缺一点。

而在 `foo` 这个页面里，列表一共有六个层级，`[[bar]]` 这个链接出现在第三层 `3 - [[bar]]` 里，既然这个节点既有上级节点又有下级节点，说明它并不是那种用在 daily notes 流程里的传递型双链，这个链接的作用是表现关联性，姑且叫它**关联型双链**。对于这种情形，roam research 的做法是完全不展示 `3- [[bar]]` 的下级节点、只展示 `3- [[bar]]` 这一个层级，上级节点用面包屑稍微显示一下。logseq 对这种情形有一点不同的理解，它在反链里展示了 `3 - [[bar]]` 的第一个下级节点 `4`，但无论怎么说，`4` 下面的节点肯定是不适合进一步展示出来了，不然会过多地占用反链的展示空间，特别是对思源这种在侧面的反链面板来说，空间弥足珍贵。

如果缺少了上面说的这种反链层级处理，一旦一个列表项块里有锚文本、下级节点又很多，光这一条反链就会把整个反链面板铺满了。而完全折叠起来同样不合适，这个小细节带来的使用差距是决定性的，大纲型笔记如果处理不好这一点，反链的实用性就会大打折扣，完全不展示下级的话根本不利于对 daily notes 生成的那些主题做后期整理。

所以思源列表块的反链层级在改进的时候，具体怎么选择展示的层级，我觉得直接照抄 roam research 或者直接照抄 logseq 都是很好的。但假如思源的列表块实在做不了 roam research 和 logseq 那样的反链层级处理，恐怕还是不要默认展开锚文本列表项的下级比较好，不过展开下级的按钮可以加上。

**Comment by fanglypro** [comment]
虽然closed了，我还是强烈希望能够按照 https://ld246.com/article/1628672942107 里面的最新讨论，复刻roam research的反链展示逻辑

**Comment by deerainw** [comment]
同意楼上，一次性改进到位比较好。复刻 roam research 的设计本身就有很强的舆论背书效果，而且它确实更能同时满足大多数人各自不同的使用习惯。之后我出一个教程背背书，各位理解了 conor 流程的朋友再在论坛和用户群之类的地方口头支持支持，这个设计从各个方面来说就站住脚了。直接发布试水的话可能引来比较混乱的讨论。

**Comment by 88250** [comment]
> 然后，反链面板上有两个按钮，一个是全部展开，点了这个按钮相当于变成 logseq 那种，所有内容都展开子列表。另一个按钮是全部折叠，点了这个按钮相当于变成 remnote、roamedit 这种，所有内容都折叠子列表。

@fanglypro 这里我不大理解为啥需要两个按钮，似乎只是个状态切换吧？

**Comment by fanglypro** [comment]
> > 然后，反链面板上有两个按钮，一个是全部展开，点了这个按钮相当于变成 logseq 那种，所有内容都展开子列表。另一个按钮是全部折叠，点了这个按钮相当于变成 remnote、roamedit 这种，所有内容都折叠子列表。
> 
> @fanglypro 这里我不大理解为啥需要两个按钮，似乎只是个状态切换吧？

因为现在相当于有3种状态，第一种状态即默认状态是roam research的形态，第二种状态是类似logseq的形态，第三种状态是类似remnote、roamedit的形态。

如果只有一个按钮的话，默认是roam research的形态，点击这个按钮后是变成哪个形态呢？

**Comment by fanglypro** [comment]
模拟一个具体例子，因为现在版本的反链中的列表块还不能展开，这里我用标题块进行模拟展示（事实上标题的展示逻辑也应当要和列表一样，D大看看要不要顺带把标题的反链逻辑也改一改，和列表的原则是一样的）

引用《测试》这个文档：

![image](https://user-images.githubusercontent.com/57083732/134781377-ee6bb5dd-17ef-4fe5-afae-6dff4374d2f2.png)

在《测试》文档的反链，默认形态即roam research形态，根据上下文是否充足选择折叠或展开，节点中如果只有反链锚文本，则展开，节点中如果不止反链锚文本，则折叠，应当是下面的样式，第一个引用处折叠，第二个引用处展开：

![image](https://user-images.githubusercontent.com/57083732/134781422-6e22d2d9-b4a2-4096-a227-38002627a7ae.png)

点击全部展开后，要转换为logseq形态，应当是下面的样式：

![image](https://user-images.githubusercontent.com/57083732/134781445-d8b06c41-fd3e-4610-a55c-eab36eb8efa2.png)

点击全部折叠后，要转换为remnote、roamedit形态，应当是下面的样式：

![image](https://user-images.githubusercontent.com/57083732/134781529-79df343f-d412-4dfa-b564-902c1374e9d5.png)

**Comment by 88250** [comment]
@fanglypro 感谢说明，我们再考虑下。

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/134789520-4079ccd5-b220-4d3c-bfba-4718cf5b6276.png)

@fanglypro @deerainw 请帮忙看下这样如何？两种形态的切换暂时不考虑了。

**Comment by fanglypro** [comment]
这个`1a1`的地方，我认为最好还是只显示`1`比较好，按照roam research和logseq中的设计，是显示子列表的第一层级的内容，图片中把子列表的内容直接附在父结点上有点奇怪，大部分情况下这样连起来并不能成为完整的句子，只会造成信息冗余，在实际场景中文本内容比较多，感受就会比较明显，我建议这部分还是修改下。

现在的上下文按钮和全部折叠、全部展开按钮是和1.3.5之前的功能一样吗，也就是上下文按钮的功能是在不自动换行和自动换行之间切换，全部折叠展开是根据文档进行折叠展开吗？在我的体验上，对这几个按钮，我只会在每天第一次打开反链面板的时候点击上下文按钮，因为上下文按钮可以保持状态，之后我就不会动这几个按钮了。当然这样的设计我也能接受，默认是roam research形态+自动换行已经能满足我的需求了，这部分就看D大的考虑了。

**Comment by 88250** [comment]
> 感受就会比较明显，我建议这部分还是修改下

好的。

> 是和1.3.5之前的功能一样吗

一样。

@fanglypro

**Comment by deerainw** [comment]
<img width="82" alt="1632628001(1)" src="https://user-images.githubusercontent.com/32661922/134792814-f3f9c334-53a5-42ba-9ee7-abc8657252de.png">

**Comment by whuwangyong** [comment]
这个现在（1.8.5）还是只展示了两级啊。

**Comment by aptexd** [comment]
在实现[编辑器式反链面板 · Issue #3565 ](https://github.com/siyuan-note/siyuan/issues/3565) 功能后
已经失去了在此 issue 讨论和实现的功能
功能重构失去原本特性这无可厚非
而反链展示又是核心体验之一
因此我提议重开此 issue

**Comment by 88250** [comment]
@aptexd 现在反链的层级规则没有变化，还是按照这个逻辑实现的。

**Comment by aptexd** [comment]
> @aptexd 现在反链的层级规则没有变化，还是按照这个逻辑实现的。

终于找到原因了，我想应该就是“共享折叠状态”造成的
我推测应该是在 .sy 文档中 fold 字段影响到了其他窗口正常状态了

**Comment by mohuishou** [comment]
+1 遇到了同样的问题
