### ISSUE TITLE
笔记本排序

### ISSUE THREAD

**Issue by LecoLu** [siyuan-note/siyuan#2786]
在1.2.x版本，我可以通过关闭文件夹后重新打开，达到自己想要的文件夹自定义顺序，重启后仍然保持。

现在新版1.3.1，用一样的办法重启后会恢复到默认排序。能不能像之前那样重启后仍然保持文件夹排序，或者增加个文件夹排序的功能。

**Comment by 88250** [comment]
嗯，我们已经陆续收集到一些用户反馈，但是这个目前暂时不是高优先级，所以还需要再等等，谢谢。

**Comment by TylerWang1998** [comment]
你好，我从1.1.x升级到1.2.x，按照教程复制了原data内的文件夹至新的文件夹，文件夹内已有数据，但打开思源笔记后，在“已关闭的笔记本”中未显示笔记本，请问如何解决？
可以付费解决，数据丢失，很急，谢谢！

**Comment by TylerWang1998** [comment]
> 你好，我从1.1.x升级到1.2.x，按照教程复制了原数据内的文件夹至新的文件夹，文件夹内已有数据，但打开思源笔记后，在“已关闭的笔记本”中未
> 提示笔记，请问如何解决？可以付费解决，数据丢失，很急，谢谢！

联系方式：18019022279（微信同号）

**Comment by 88250** [comment]
@TylerWang1998 请先下载 v1.2.31 进行迁移，完成以后再下载 v1.2.7 进行第二次迁移，最后再安装最新版。

* [思源笔记 v1.1.x 数据迁移至 v1.2.x 的说明](https://ld246.com/article/1622710344891)
* [思源笔记 v1.2.5 发布，迁移到 id 子文档](https://ld246.com/article/1629458118781)
