### ISSUE TITLE
1.3.1列表项搜索既没有列表也没有段落

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#2789]
![image](https://user-images.githubusercontent.com/88605687/131308058-3b0e8625-4f6c-45b6-936d-97e13eb296c9.png)

**Comment by 88250** [comment]
搜索选项里打开了段落吗？

**Comment by Kitsuta-le** [comment]
> 搜索选项里打开了段落吗？

开了段落引用就出现段落了呀。。。可是我们需要的是上版本那样对列表项 搜索显示段落 引用正常
![9F3HY@ C6092W){{4OGADV6](https://user-images.githubusercontent.com/88605687/131325071-15ef4f0f-dcb1-442c-9a46-b6fb7a5e1fb6.png)

**Comment by 88250** [comment]
全局搜索默认已经不支持搜索容器块了 v1.3.0 https://github.com/siyuan-note/siyuan/issues/2612 

如果需要的话可以用 SQL 搜，我关闭了。

**Comment by Kitsuta-le** [comment]
> 全局搜索默认已经不支持搜索容器块了 v1.3.0 #2612
> 
> 如果需要的话可以用 SQL 搜，我关闭了。

可是你在1.3.0做的就是仅勾选列表项就能搜索到段落啊，为什么要改动呢？

**Comment by 88250** [comment]
这个逻辑没有变过，打开段落的话就支持段落，没有开的话就搜不到东西了，因为默认排除了容器块。

有改动的话会开 issue 的。

**Comment by Kitsuta-le** [comment]
> 这个逻辑没有变过，打开段落的话就支持段落，没有开的话就搜不到东西了，因为默认排除了容器块。
> 
> 有改动的话会开 issue 的。

我明白你的意思，但在使用逻辑上列表项是不同于其他容器的，列表项可以说是大纲用户的基本单位完全可以替代段落，之前希望改进搜索列表项的排序也是基于这一点。上图我搜出的段落比较少，但要是有七个八个就非常不便了。希望d大考虑下。
![image](https://user-images.githubusercontent.com/88605687/131333657-1f405b9e-e6d2-478a-b328-faed91cea053.png)

**Comment by Kitsuta-le** [comment]
> 这个逻辑没有变过，打开段落的话就支持段落，没有开的话就搜不到东西了，因为默认排除了容器块。
> 
> 有改动的话会开 issue 的。

我明白你的意思，但在使用逻辑上列表项是不同于其他容器的，列表项可以说是大纲用户的基本单位完全可以替代段落，之前希望改进搜索列表项的排序也是基于这一点。上图我搜出的段落比较少，但要是有七个八个就非常不便了。希望d大考虑下。
![image](https://user-images.githubusercontent.com/88605687/131333844-d4f59860-fa4d-41f9-ba41-661a91dba97e.png)

**Comment by 88250** [comment]
要灵活的话估计只能等这个 https://github.com/siyuan-note/siyuan/issues/2229 了，在全局搜索上单独支持类型过滤。

**Comment by Kitsuta-le** [comment]
> 这个逻辑没有变过，打开段落的话就支持段落，没有开的话就搜不到东西了，因为默认排除了容器块。
> 
> 有改动的话会开 issue 的。

我明白你的意思，但列表项和其他容器是不一样的，大纲用户对列表项的使用需求绝对是远大于段落的。希望d大考虑下。


> 要灵活的话估计只能等这个 #2229 了，在全局搜索上单独支持类型过滤。

赞👍🏻 办法总比问题多
