### ISSUE TITLE
添加颜色后英文单词之间无法添加空格

### ISSUE THREAD

**Issue by xBLACKICEx** [siyuan-note/siyuan#2797]
BUG, 英文下给字体添加颜色会自动添加粗体，且英文单词在多个字体颜色直接无法添加空格
版本：1.31
![bug with font colors3](https://user-images.githubusercontent.com/51036094/131408320-6657095c-fb12-4d7a-a2c6-f3a6bf59890b.gif)

**Comment by 88250** [comment]
加颜色目前只能加粗。
