### ISSUE TITLE
思源软件关闭后，文件树也回到初始状态

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#28]
能否保持最后编辑的文件位置呢，不然文件多了每次打开都耗费时间。

**Comment by 88250** [comment]
窗口布局持久化以及文件树等页签组件状态持久化已经在计划中，后续会尽快实现，感谢反馈。

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/46
