### ISSUE TITLE
支持题头图上下拖动调整位置

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2805]
https://ld246.com/article/1630419038900

**Comment by pusuanzi1** [comment]
建议题头图支持Internet link

**Comment by LaneDu** [comment]
类似notion那样可以从unsplish之类的网站random 获取

**Comment by 88250** [comment]
@LaneDu 以后再考虑……

**Comment by LaneDu** [comment]
优化建议，可以放到主要功能完善之后

**Comment by netdog2019** [comment]
> 希望类似notion那样可以从unsplish之类的网站random 获取

这个功能好，最好可是这只默认增加题图头，插入随机照片。
