### ISSUE TITLE
休眠后内核连接中断

### ISSUE THREAD

**Issue by Cloud33** [siyuan-note/siyuan#2806]
### Describe the problem
1.3.1 内核连接中断

### Expected result

机器睡眠后，第二天启动，总会报这个错误

### Screenshot or screen recording presentation

![1630458895](https://user-images.githubusercontent.com/8787198/131595941-74e10d5c-3a02-4bb4-91bd-fdc3aa63679b.jpg)

### Version environment

* Version: 1.3.1
* Operating system:  windows 10
* Browser (if used): 

### Log File

没有生成日志文件

**Comment by 88250** [comment]
日志文件在工作空间/conf/siyuan.log 麻烦打包上传一下，谢谢。

**Comment by Cloud33** [comment]
Log File:
[siyuan.log](https://github.com/siyuan-note/siyuan/files/7087593/siyuan.log)

**Comment by 88250** [comment]
v1.3.2 中修复，麻烦发布以后再帮忙回测，谢谢。

**Comment by Cloud33** [comment]
谢谢，等待新版发布

**Comment by Zuoqiu-Yingyi** [comment]
@88250 `v2.4.6` 该问题再次出现
系统: Windows 11 22H2 22621.675

**Comment by 88250** [comment]
> @88250 `v2.4.6` 该问题再次出现 系统: Windows 11 22H2 22621.675

估计还得继续观察，暂时找不到原因。
