### ISSUE TITLE
配置文件conf.json的商店发布功能

### ISSUE THREAD

**Issue by Angus-169** [siyuan-note/siyuan#282]
配置项很多，为了方便新用户快速上手使用，可以做一些推荐性配置文件，方便新用户从其他竞品迁移，降低学习成本

**Comment by 88250** [comment]
脑洞是好……但是现有的 conf.json 里有一些隐私配置，比如 WebDAV 密码、密钥对私钥等，所以目前是不能公开的。

以后如果要做的话会考虑拆分一下配置，就眼目前来看，支持自定义主题和配色调整应该就差不多了，各项参数的配置还是留待用户自行摸索吧。
