### ISSUE TITLE
提供快捷获取块链接的方式或快捷键

### ISSUE THREAD

**Issue by VSpade7** [siyuan-note/siyuan#2822]
![2955BA348E0A8E10DA7988C7BA2D0B13](https://user-images.githubusercontent.com/46594083/131796497-9f50a724-3b29-4bf9-872e-7aa63fe21f8a.jpg)
想配合quicker链接别的软件，希望获取块链接能提供快捷键或其他能快捷获取块链接的功能

**Comment by VSpade7** [comment]
希望能提供两种获取块链接的方式，一种是获取选中块的链接，一种是当前所在文档的链接

**Comment by 88250** [comment]
复制块超链接已经有快捷键了：

![image](https://user-images.githubusercontent.com/873584/132079959-cc82b402-2b17-4287-8266-87d112032ba3.png)

当前文档的暂时不添加了，我关闭了，谢谢。
