### ISSUE TITLE
PDF 标注双链

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2828]
* [x] PDF 阅读器 https://github.com/siyuan-note/siyuan/issues/2857
* [x] 标注 JSON 结构和存取
* [x] 数据库表 `file_annotation_refs`
* [x] Lute Spin https://github.com/88250/lute/issues/155
* [x] Transaction
* [x] PDF 阅读器内预览块
  * [x] `/api/block/getRefIDsByFileAnnotationID`
  * [x] 鼠标悬浮标注加载浮窗编辑器（预览多个块`）
* [x] 编辑器内跳转 PDF 并高亮标注（跳转到注解）

**Comment by Crowds21** [comment]
既然都支持PDF了,能不能一块把equb也支持了,好多电子书专门下的equb格式. 0-0

**Comment by 88250** [comment]
@Crowds21 还需要时间研究，先投票 PDF 的，谢谢。

**Comment by yanyu2015** [comment]
所以投票以后多久能开工并实现呢？

**Comment by 88250** [comment]
@yanyu2015 年底以前应该没问题。

**Comment by ippreacher** [comment]
其实投票没啥悬念，国外的rn有了，国内的logseq、互链文档也已经有了，听说re也在做，这已经成为双链笔记的基本功能了罢，也算不上什么卖点。

**个人认为真正的差异化或者卖点是对关系图或者脑图的改进，可以手动处理知识结构之间的关系，而不仅仅呈现双链之间的引用关系。这方面thebrain有体现，但其对中文支持不佳。有一个roam mind是将脑图与双链相结合，并且有脑图的自由节点和关联线的功能，这一点就使得脑图不再被局限为大纲的另一种展示方式而已，而是可以按照主题来组织各知识节点之间的逻辑关系，从而有可能摆脱文档关系图的鸡肋现状。可惜roam mind已经停止开发了。**

**Comment by clark874** [comment]
> 其实投票没啥悬念，国外的rn有了，国内的logseq、互链文档也已经有了，听说re也在做，这已经成为双链笔记的基本功能了罢，也算不上什么卖点。
> 
> **个人认为真正的差异化或者卖点是对关系图或者脑图的改进，可以手动处理知识结构之间的关系，而不仅仅呈现双链之间的引用关系。这方面thebrain有体现，但其对中文支持不佳。有一个roam mind是将脑图与双链相结合，并且有脑图的自由节点和关联线的功能，这一点就使得脑图不再被局限为大纲的另一种展示方式而已，而是可以按照主题来组织各知识节点之间的逻辑关系，从而有可能摆脱文档关系图的鸡肋现状。可惜roam mind已经停止开发了。**
> 
> 如果D大感兴趣，可以抽点时间看看roam mind的功能演示视频。当然，虽然它近期已经停止开发，但也已经支持pdf标注了。
> https://www.zhihu.com/zvideo/1375536317065949184

支持一个，这个理念非常先进，从知识链接升级到了知识重组和学习，可以说真正让软件突破了只是记录知识，链接知识的场呢面，真正让笔记重组有了“学习”功能的意义。倘若能够实现会非常有意义，可以突破小圈子的局限，向广大学生和研究者推广，从而实现盈利和发展。

**Comment by 88250** [comment]
@ippreacher @clark874 感谢两位的建议，脑图方面的重构估计还早，请关注 https://github.com/siyuan-note/siyuan/issues/2024

**Comment by zhang-hao-me** [comment]
支持，最好可以像Marginnote那样，然后再利用双链的特点。

**Comment by zhang-hao-me** [comment]
> > 其实投票没啥悬念，国外的rn有了，国内的logseq、互链文档也已经有了，听说re也在做，这已经成为双链笔记的基本功能了罢，也算不上什么卖点。
> > **个人认为真正的差异化或者卖点是对关系图或者脑图的改进，可以手动处理知识结构之间的关系，而不仅仅呈现双链之间的引用关系。这方面thebrain有体现，但其对中文支持不佳。有一个roam mind是将脑图与双链相结合，并且有脑图的自由节点和关联线的功能，这一点就使得脑图不再被局限为大纲的另一种展示方式而已，而是可以按照主题来组织各知识节点之间的逻辑关系，从而有可能摆脱文档关系图的鸡肋现状。可惜roam mind已经停止开发了。**
> > 如果D大感兴趣，可以抽点时间看看roam mind的功能演示视频。当然，虽然它近期已经停止开发，但也已经支持pdf标注了。
> > https://www.zhihu.com/zvideo/1375536317065949184
> 
> 支持一个，这个理念非常先进，从知识链接升级到了知识重组和学习，可以说真正让软件突破了只是记录知识，链接知识的场呢面，真正让笔记重组有了“学习”功能的意义。倘若能够实现会非常有意义，可以突破小圈子的局限，向广大学生和研究者推广，从而实现盈利和发展。

我也赞同这种想法，批注能够成为思维导图的一部分

**Comment by ippreacher** [comment]
> @ippreacher @clark874 感谢两位的建议，脑图方面的重构估计还早，请关注 #2024

辛苦D大！如果D大认可这个重要方向，脑图重构的优先级也可提前一点，毕竟pdf注释原本也是long-term呀😜

**Comment by 88250** [comment]
@ippreacher 这个争取明年有进度吧……

**Comment by innerbeast** [comment]
> 其实投票没啥悬念，国外的rn有了，国内的logseq、互链文档也已经有了，听说re也在做，这已经成为双链笔记的基本功能了罢，也算不上什么卖点。
> 
> **个人认为真正的差异化或者卖点是对关系图或者脑图的改进，可以手动处理知识结构之间的关系，而不仅仅呈现双链之间的引用关系。这方面thebrain有体现，但其对中文支持不佳。有一个roam mind是将脑图与双链相结合，并且有脑图的自由节点和关联线的功能，这一点就使得脑图不再被局限为大纲的另一种展示方式而已，而是可以按照主题来组织各知识节点之间的逻辑关系，从而有可能摆脱文档关系图的鸡肋现状。可惜roam mind已经停止开发了。**
> 
> 如果D大感兴趣，可以抽点时间看看roam mind的功能演示视频。当然，虽然它近期已经停止开发，但也已经支持pdf标注了。
> https://www.zhihu.com/zvideo/1375536317065949184

看了下这个roam mind，发现这个理念超强啊，作为资深思维导图爱好者，正是我一直寻找的的，可惜停止开发了，希望思源也能有如此强大的脑图功能

**Comment by ttimasdf** [comment]
> > 其实投票没啥悬念，国外的rn有了，国内的logseq、互链文档也已经有了，听说re也在做，这已经成为双链笔记的基本功能了罢，也算不上什么卖点。
> > **个人认为真正的差异化或者卖点是对关系图或者脑图的改进，可以手动处理知识结构之间的关系，而不仅仅呈现双链之间的引用关系。这方面thebrain有体现，但其对中文支持不佳。有一个roam mind是将脑图与双链相结合，并且有脑图的自由节点和关联线的功能，这一点就使得脑图不再被局限为大纲的另一种展示方式而已，而是可以按照主题来组织各知识节点之间的逻辑关系，从而有可能摆脱文档关系图的鸡肋现状。可惜roam mind已经停止开发了。**
> > 如果D大感兴趣，可以抽点时间看看roam mind的功能演示视频。当然，虽然它近期已经停止开发，但也已经支持pdf标注了。
> > https://www.zhihu.com/zvideo/1375536317065949184
> 
> 看了下这个roam mind，发现这个理念超强啊，作为资深思维导图爱好者，正是我一直寻找的的，可惜停止开发了，希望思源也能有如此强大的脑图功能

看起来就很难做……印象笔记几年前的大版本就有了类似的功能，但实在是难用，相当于要把知识用mindmap和文字的方式整理两遍。用户体验称不上友好。

**Comment by sun-duo** [comment]
希望思源能把 PDF 双链功能一直做下去，我个人是把它当成核心功能来使用思源笔记的，在 win 上思源的 PDF 标注链接是我用的最舒服的，非常灵活，不必拘泥于大纲脑图，可以设置各种格式，还能结合思源笔记的其他功能，比如全局搜索快速定位锚文本，进而快速定位书籍中我想翻阅的内容等等。PDF 双链这个功能，我真的觉得做好了可以成为思源笔记的一大特色，是其他 PDF 阅读软件和笔记软件不具备的，它和“思源”的含义也不谋而合，书籍文献等等 PDF 也是我们知识的重要来源。我的书籍阅读笔记体系已经建立在思源笔记上很久了，感谢 D 大和 V 姐，永远尽我所能支持你们，加油！
