### ISSUE TITLE
Database table view

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2829]
Divided into the following tasks:

* [x] https://github.com/siyuan-note/siyuan/issues/7552
* [x] https://github.com/siyuan-note/siyuan/issues/7536
* [x] https://github.com/siyuan-note/siyuan/issues/8663
* [x] https://github.com/siyuan-note/siyuan/issues/8693
* [x] https://github.com/siyuan-note/siyuan/issues/8690
* [x] https://github.com/siyuan-note/siyuan/issues/8696
* [x] https://github.com/siyuan-note/siyuan/issues/8691
* [x] https://github.com/siyuan-note/siyuan/issues/8694
* [x] https://github.com/siyuan-note/siyuan/issues/8695
* [x] https://github.com/siyuan-note/siyuan/issues/8664
* [x] https://github.com/siyuan-note/siyuan/issues/8699
* [x] https://github.com/siyuan-note/siyuan/issues/8769
* [x] https://github.com/siyuan-note/siyuan/issues/8667
* [x] https://github.com/siyuan-note/siyuan/issues/8692
* [x] https://github.com/siyuan-note/siyuan/issues/8757
* [x] https://github.com/siyuan-note/siyuan/issues/8665
* [x] https://github.com/siyuan-note/siyuan/issues/8765
* [x] https://github.com/siyuan-note/siyuan/issues/8854
* [x] https://github.com/siyuan-note/siyuan/issues/8891
* [x] https://github.com/siyuan-note/siyuan/issues/8892
* [x] https://github.com/siyuan-note/siyuan/issues/8764
* [x] https://github.com/siyuan-note/siyuan/issues/9091
* [x] https://github.com/siyuan-note/siyuan/issues/8710
* [x] https://github.com/siyuan-note/siyuan/issues/8895
* [x] https://github.com/siyuan-note/siyuan/issues/9242
* [x] https://github.com/siyuan-note/siyuan/issues/8766
* [x] https://github.com/siyuan-note/siyuan/issues/9304
* [x] https://github.com/siyuan-note/siyuan/issues/9371
* [x] https://github.com/siyuan-note/siyuan/issues/8894
* [x] https://github.com/siyuan-note/siyuan/issues/9419
* [x] https://github.com/siyuan-note/siyuan/issues/9424
* [x] https://github.com/siyuan-note/siyuan/issues/9888
* [x] https://github.com/siyuan-note/siyuan/issues/9958
* [x] https://github.com/siyuan-note/siyuan/issues/10072

**Comment by 88250** [comment]
基于现有属性，接口请参考 API 文档。

**Comment by Crowds21** [comment]
今天看了一下其他几家属性视图的状态.
提一个小想法. 对于文档这个级别的块的属性,通过Front-matter的形式展现出来是否会更好. 美观,易于浏览且方便编辑.

**Comment by 88250** [comment]
@Crowds21 这个好像和 YFM 没有什么关系吧。

**Comment by Crowds21** [comment]
> @Crowds21 这个好像和 YFM 没有什么关系吧。

我试了试在wolai, 对一个视图添加新数据, 比如新添加一个列的时候,会自动地在文档的这个部分添加对应的属性. 感觉特别方便.
而且这样子浏览也很直接.
虽然和ob用的front-matter有些区别, 但毕竟作用其实是一样的. 而且我个人感觉观感更好. 而且我自己体验上感觉给文档设置属性操作上感觉不够流畅.不知道是不是我个人习惯上的问题.
```
---
key: Ob front-matter
key2: value2
multiple: [one, two, three]
multiple:
- one
- two
- three
---
``` 

等D大后续研究研究. 😀

**Comment by 88250** [comment]
@Crowds21 这可能是文本模式和所见即所得模式的区别，后者需要更好的交互设计，欢迎讨论。

**Comment by hexawing** [comment]
以我用ob（front-matter形式，浅度使用）和tw（属性形式，中度使用）的感受来说，直接写文本里面可能爽一点。因为写文本里面可以被反链找到

**Comment by Crowds21** [comment]
> 以我用ob（front-matter形式，浅度使用）和tw（属性形式，中度使用）的感受来说，直接写文本里面可能爽一点。因为写文本里面可以被反链找到

ob我很长时间没有用过了, 只是看过一些别人的截图.

我一直觉得,属性面板最好是能够嵌入到正文里,当作成"块"的一部分.而不是单独的一个面板. 这样子能够它能够配合上下文.输入一些比较长的内容,不同用户也能根据自己的需求发挥不同的作用.如果用户不想看,那也可以直接将这个部分折叠.
而不只是一个用来标注 TODO 的简单的项目/任务管理工具.

比如这样子. Key部分标注属性的名字,而块的通过软换行来显示不同的 Value. 现在的Logseq 是类似的模式.
![image](https://user-images.githubusercontent.com/48215334/142856115-590c5f76-dc9c-4197-b110-7f3fe661fb41.png)

**Comment by 88250** [comment]
@Crowds21 希望社区有人能贡献一下这样的属性挂件。

**Comment by Crowds21** [comment]
> @Crowds21 希望社区有人能贡献一下这样的属性挂件。
靠大佬们了, 前端没啥时间搞 😂.
@hexawing 
其实用#TAG#,或其他自己习惯用的一些特殊关键词也可以达到类似的效果的. 比如
![image](https://user-images.githubusercontent.com/48215334/142858773-5adb3564-7efb-4dca-8060-bd7efb429ca2.png)
但是编辑器来我感觉不够流畅,我也想不到其他啥更好的方法了.

**Comment by SineMark2020** [comment]
> @Crowds21 希望社区有人能贡献一下这样的属性挂件。




> @Crowds21 希望社区有人能贡献一下这样的属性挂件。

开发与维护挂件是要花时间付出，如果没有激励奖励，那就只能等不知道什麽时候出现的热心人

**Comment by netdog2019** [comment]
属性视图确实很方便。

**Comment by gclm** [comment]
建议属性视图可以加个是否必填的选项，这样在同时维护文档规范上会更方便点。

**Comment by Zuoqiu-Yingyi** [comment]
> > @Crowds21 希望社区有人能贡献一下这样的属性挂件。
> 
> 靠大佬们了, 前端没啥时间搞 😂. @hexawing 其实用#TAG#,或其他自己习惯用的一些特殊关键词也可以达到类似的效果的. 比如 ![image](https://user-images.githubusercontent.com/48215334/142858773-5adb3564-7efb-4dca-8060-bd7efb429ca2.png) 但是编辑器来我感觉不够流畅,我也想不到其他啥更好的方法了.

我有一个比较容易实现的想法, 就是将文档块属性窗口调整一下样式直接放在文档的首部, 这样还能顺手解决浮窗预览无法查看文档属性的问题 [块引文档块的浮窗内容改进 · Issue #3314 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/3314?utm_source=ld246.com)

**Comment by leolee9086** [comment]
https://github.com/leolee9086/cc-doctype-form/blob/main/README.md
这种的不知道能不能顶顶
现在的效果大致像这样
![)J9I{8 0L9_4QF@KJ6EPQ0A](https://user-images.githubusercontent.com/19915077/147845834-f262253c-8890-498a-a4bc-f3bdb247366b.png)

**Comment by Belf-hu** [comment]
D大，属性以后会不会做属性类型，比如做一个属性复选框，属性date什么的，就像notion那种属性类型？

**Comment by 88250** [comment]
@Belf-hu 暂时没有考虑好，之前设计属性的时候感觉不需要内建类型支持。

**Comment by Belf-hu** [comment]
> @Belf-hu 暂时没有考虑好，之前设计属性的时候感觉不需要内建类型支持。

哈哈哈，希望后续可以考虑。感谢。

**Comment by Zuoqiu-Yingyi** [comment]
哈哈, 搞了一个 <kbd>伪</kbd>·属性视图 [[思源笔记经验分享] 使用 Query 挂件实现属性视图 - 链滴](https://ld246.com/article/1649526670055)

**Comment by Elliootalderson** [comment]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/93273663/167842739-ec20fc41-b1b6-4cdf-8763-c35770c3d605.png">
使用notion这种属性视图 有助于美化排版,可以吸引用户,文档结构也更加清晰.也可以丰富集市的模板数量
.如果这中属性视图能用在每一个列表块中,可以实现某种模板的功能, 减少用户输入量

**Comment by SineMark2020** [comment]
居然提前了，感动 😀😀😀

**Comment by woniuxia** [comment]
@88250 D大，我看标题加了个 Database，是要搞多维表了吗?

**Comment by 88250** [comment]
> @88250 D大，我看标题加了个 Database，是要搞多维表了吗?

类似 Notion 的 Database，但是暂时不会支持太多视图，先支持表格视图。

**Comment by woniuxia** [comment]
> > @88250 D大，我看标题加了个 Database，是要搞多维表了吗?
> 
> 类似 Notion 的 Database，但是暂时不会支持太多视图，先支持表格视图。

@88250 D大，留好接口，其他视图可以考虑通过集市贡献的方式来完成，群里的大佬有一万个想法，哈哈哈哈

**Comment by UFDXD** [comment]
先搞白板好吧，这个真不急

**Comment by 88250** [comment]
> 先搞白板好吧，这个真不急

从目前用户社区反馈来看，属性视图的需求优先级更高一些。

**Comment by Soltus** [comment]
> 先搞白板好吧，这个真不急

白板要搞好久，不急

**Comment by Yuminis98** [comment]
确实，白板是个大工程，不急

**Comment by GoseRank** [comment]
2.7.1 属性视图还是没有，加油呀，刚需刚需

**Comment by SineMark2020** [comment]
这种不会是小版本有的功能，应该是2.8，看二月有没有机会上线

**Comment by Cyber-Syntax** [comment]
After trying Notion, I can say that the reason why notion is used so much is that it has plugins such as table and board, which really saves people from using two applications. I hope you are adding these features first. (I couldn't understand much with Translate.)

**Comment by Beforerr** [comment]
和属性关联很强的是“类” (class) 这个概念, 希望在实现属性的时候可以考虑与“类”结合。
比如说 “SiYuan” 是一个软件类的实例。而软件类带有一些固定的属性 比如 “开发者”, “最新版本”, “链接”之类的。那么当我标记 “SiYuan” 为软件时, 自动创建相关的属性。这个可以参考 Tana , 在 Tana 中被叫做 “supertag”。

进一步地话, 和类相关的一个概念是 method, 比如对 "daily note" 这个类 定义打开前一天日记和后一天日记的方法 （具体的 method 可以交给用户/社区来写, 主要期待能有 UI 接口）。当然感觉这个实现的话比较困难, 只是个想法。

**Comment by Zuoqiu-Yingyi** [comment]
希望内置的属性视图可以以 Web 应用的方式进行访问

**Comment by 88250** [comment]
@Cyber-Syntax Basically available release probably won't be until around July.

**Comment by Yuminis98** [comment]
我看这个issue，好像是一个大工程，这个属性视图是做什么？ 是类似于notion的知识库吗？
我可以通过属性视图，做出这种表格吗？
![image](https://user-images.githubusercontent.com/117956441/227861905-a8343fd5-0c95-467c-ac89-4d04a0d8f752.png)

**Comment by GoseRank** [comment]
属性视图好久都没有动静了😭😭

**Comment by SineMark2020** [comment]
> 属性视图好久都没有动静了😭😭

.....一直被插队，很多人在等，要等插件后了吧.

**Comment by royc01** [comment]
上面D大有回复过了

**Comment by wrwe3888** [comment]
notion类的database有个很大局限性，是表格的列（属性名），仅适用于该表格的行页面。比如表1中的属性“作者”和表2中的属性“作者”是不相干的。

logseq的query功能，可以把整个库里凡是属性是“作者”的页面聚合到一个表中。但它的缺点是由此得到的表格无法编辑，基本没有列数据类型、无法计算，没有表格下方的汇总（也许高级query有这样的功能，但是比较麻烦，一般人学不会），没有关联等notion表格的功能。

不知道思源的database是什么形态，不知道D大有无打通两种表格的方案。

**Comment by pureTrue** [comment]
> notion类的database有个很大局限性，是表格的列（属性名），仅适用于该表格的行页面。比如表1中的属性“作者”和表2中的属性“作者”是不相干的。
> 
> logseq的query功能，可以把整个库里凡是属性是“作者”的页面聚合到一个表中。但它的缺点是由此得到的表格无法编辑，基本没有列数据类型、无法计算，没有表格下方的汇总（也许高级query有这样的功能，但是比较麻烦，一般人学不会），没有关联等notion表格的功能。
> 
> 不知道思源的database是什么形态，不知道D大有无打通两种表格的方案。

感觉比较好的方案是像tana类似的Supertags，给标签加上父子关系，表格某个属性列就可以复用其子标签。

**Comment by 88250** [comment]
> notion类的database有个很大局限性，是表格的列（属性名），仅适用于该表格的行页面。比如表1中的属性“作者”和表2中的属性“作者”是不相干的。

@wrwe3888 这个可以用关联解决。

**Comment by wrwe3888** [comment]
@88250 

如果有100个表格中都有 “作者” 这一列呢？
如果不知道哪些表格中还有 “作者” 这一列呢？

我上面的意思是，notion表格的属性，不能全局通用。
logseq query的属性，可以全局通用，但得到的表格又不能修改编辑、没有数据类型、没有页下汇总。

这个矛盾目前还没有哪个软件能解决。

**Comment by 88250** [comment]
@wrwe3888 我上面说的是 Notion 中 Database 的 关联 列可以解决你提出的问题，不存在你所描述的：

> notion类的database有个很大局限性，是表格的列（属性名），仅适用于该表格的行页面。比如表1中的属性“作者”和表2中的属性“作者”是不相干的。

**Comment by AugustTuan** [comment]
除开airtable，国内的体验下来做的最好的database应该是飞书做的，要是功能和那个一样丰富就厉害了。

**Comment by SineMark2020** [comment]
Attribute View 这种说法很少见，一看之下不知道这是什么，為何不直接写Database View就很好理解

**Comment by 88250** [comment]
> Attribute View 这种说法很少见，一看之下不知道这是什么，為何不直接写Database View就很好理解

嗯，我们修改一下：

* 对用户叫做“数据库”
* 对开发者叫做“属性视图”

**Comment by 88250** [comment]
没事，用户侧应该不会有歧义，和 Notion 保持统一 :trollface:

**Comment by Zuoqiu-Yingyi** [comment]
> 没事，用户侧应该不会有歧义，和 Notion 保持统一 :trollface: 

database 这个词的歧义就是 notion 搞出来的。。。

**Comment by SineMark2020** [comment]
不管对跟错，notion是行业老大又是先驱所以有命名权，这样才能让使用思源新用户对接，减少学习成本.

**Comment by Soltus** [comment]
逆天

**Comment by wslrj123** [comment]
啥时候出看板视图

**Comment by 88250** [comment]
@wslrj123 还没有具体计划，毕竟目前连 table view 都还没有 😅

**Comment by j1406493495** [comment]
预览版赶紧出啊

**Comment by AsafMah** [comment]
WIll this feature include an easier way to input attributes for documents?

For example, in Obsidian I have a template for the daily note that has a attributes (like `mood:: `) and then I use it to query them elsewhere.

**Comment by 88250** [comment]
> WIll this feature include an easier way to input attributes for documents?
> 
> For example, in Obsidian I have a template for the daily note that has a attributes (like `mood:: `) and then I use it to query them elsewhere.

It supports editing attributes through the attribute panel. If you want to query attributes, you need to use other methods, because attribute views need to be created manually, and it cannot automatically query and summarize.

Perhaps the community developers can build automated attribute views in some way to achieve this, but it's still early days, we're still building the infrastructure, thanks.

**Comment by AsafMah** [comment]
Thank you, I will clarify my questions:

1.Is there today a way to query anything other than blocks? Or for now the SQL is only to display blocks with `{{`?
2.Is there or will be there a way to create or edit attributes not in the attribute panel, but inside of the document itself? Like there is a syntax for tags #tag#, a syntax for setting attributes? (like `attribute:: value` in obsidian)
3. Is there/will there be a way to include attributes in a template?

**Comment by Zuoqiu-Yingyi** [comment]
@AsafMah

> 2.Is there or will be there a way to create or edit attributes not in the attribute panel, but inside of the document itself? Like there is a syntax for tags #tag#, a syntax for setting attributes? (like `attribute:: value` in obsidian)

the community widget `metadata` provides a method for editing document block attributes inside the document

**Comment by daniel10saida** [comment]
I don't see metadata in the list of the widget to download from the application. Where do I download the metadata widget?

**Comment by wslrj123** [comment]
给个建议，千万别做像wolai这种不能改类型不能隐藏的主字段，巨多余难用


![Image](https://github.com/siyuan-note/siyuan/assets/106938316/6a4dd946-7a4c-4701-be88-cd7616099b29)

**Comment by 88250** [comment]
@wslrj123 呃，已经是这样了，主字段不能隐藏也不能修改类型。

**Comment by wslrj123** [comment]
从大体设计可以看出来思源走的还是类notion路线，但感觉有点走偏了。。。
notion的view其实也有“双链”，只不过是作为引用字段使用，但D大可能没有考虑到notion的主字段为什么不直接用引用字段而用子页面的形式。
notion view主字段和子页面构建成一对一的关系，这样做比较显眼的作用就是子页面标题下的属性视图，但思源貌似做成了多组属性...emm，这样的话为什么不直接用引用字段?还是说D大将来打算做一个显示多组属性的面板？但就目前思源主字段的设计并没有看到功能向的意义，反而显得多余且增添了限制。
如果继续当前的设计路线的话，从某种意义上来说思源已经有了一些独创性的东西走在了前沿，我还是很期待思源是怎么利用多组属性的。但除此之外还有一个重要的问题就是主字段的必填，目前的主字段是强绑定块的，这点属实没必要，属性视图的定位应该是分析与管理的思维工具

**Comment by 88250** [comment]
@wslrj123 主键的值实际上是块引锚文本，可以支持隐藏的，不用纠结这一点。

**Comment by wslrj123** [comment]
隐藏问题是次要的，自己写css都行，主要问题是必须绑定块，参考wolai和notion的主字段都不是必填

**Comment by 88250** [comment]
肯定是要绑定块的，表格视图中每一行对应一个块。

**Comment by wslrj123** [comment]
没搞懂“必须绑定块“的设计理念。。。在我看来万物皆可block和万物皆可row是并不冲突的两个设计，block中是笔记视角下产物，row是分析与管理视角下的产物，它们应该是交叉关系，row可选关联block我可以理解，但不理解为什么一定要强行绑定，为了遵从写好的开发逻辑吗？

**Comment by 88250** [comment]
块是基础，行只是视图中的一种。

**Comment by 5kyfkr** [comment]
现在的完成度我感觉适合做文档目录树，可以更方便的给文档增加属性标签并筛选出来，这一点应该就是notion的精髓，加上不同视图的切换玩法就会更多，但是还是建议文档标题附近能增加个属性按钮，点开直达文档的属性，然后可以方便的反向编辑已链接文档的属性，并且能从被链接database的文档跳转回database主文档，这两点完成应该用起来会很方便。
另外希望自带的表格功能也能达到类似的外观操作，感觉可以顺带也优化下。

**Comment by 88250** [comment]
属性面板的直达入口后续考虑添加，已有的表格暂时没有时间优化了，等后面看，有个单独的 issue。



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 2, 2023 14:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database (Attribute View) (#2829)




 
现在的完成度我感觉适合做文档目录树，可以更方便的给文档增加属性标签并筛选出来，这一点应该就是notion的精髓，加上不同视图的切换玩法就会更多，但是还是建议文档标题附近能增加个属性按钮，点开直达文档的属性，然后可以方便的反向编辑已链接文档的属性，并且能从被链接database的文档跳转回database主文档，这两点完成应该用起来会很方便。
 另外希望自带的表格功能也能达到类似的外观操作，感觉可以顺带也优化下。

**Comment by wrwe3888** [comment]
> 没事，用户侧应该不会有歧义，和 Notion 保持统一 :trollface:

我是各种笔记的热心用户，但第一次见到notion的数据库时，感觉肯定很难，所以没怎么使用notion。

“数据库”这个名字，对于程序员来说，可能是比较一般的词，但对于非程序员的普通用户来说，会有很强的疏离感。

所以强调建议叫 数据表格，而不是数据库。当然，英语翻译叫database无所谓。

**Comment by 88250** [comment]
不一定是表格，还有其他视图。



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 2, 2023 16:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database (Attribute View) (#2829)




  
没事，用户侧应该不会有歧义，和 Notion 保持统一 
  
我是各种笔记的热心用户，但第一次见到notion的数据库时，感觉肯定很难，所以没怎么使用notion。
 
“数据库”这个名字，对于程序员来说，可能是比较一般的词，但对于非程序员的普通用户来说，会有很强的疏离感。
 
所以强调建议叫 数据表格，而不是数据库。当然，英语翻译叫database无所谓。

**Comment by ognsya** [comment]
> Not necessarily tables, there are other views too.
> […](#)
> ---Original--- From: ***@***.***> Date: Wed, Aug 2, 2023 16:10 PM To: ***@***.***>; Cc: ***@***.******@***.***>; Subject: Re: [siyuan-note/siyuan] Database (Attribute View) ( #2829 ) It's okay, user There should be no ambiguity on the side, and it should be unified with Notion. I am an enthusiastic user of various notes, but when I saw the notion database for the first time, it must have been difficult, so I didn't use notion much. The name "database" may be a relatively common word for programmers, but for ordinary users who are not programmers, it will have a strong sense of alienation. Therefore, it is emphasized that it is recommended to call it a data table, not a database. Of course, it doesn't matter if the English translation is called database. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: ***@***.***>

"Table view" makes sense to me (as an English speaker).

Then other potential views can be List view, Kanban view, Grid view, Graph view etc...

**Comment by 88250** [comment]
Yes, so the base is called "Database" and then there are different views, very similar to Notion.

**Comment by wrwe3888** [comment]
【1】希望属性视图能有行号。
【2】希望表属性视图的列宽度能调小一点。
【3】希望属性视图能有notion那样的子项目行（就是在首列以树形结构来显示，方便识别不同行之间的层级关系）。这个功能我给wolai flowus提过两年建议，一直没弄。没想到notion弄出来的。希望思源能有。

notion没有行号。
notion表格列的最小宽度也挺宽，当列数据比较少时，这些宽度都浪费了。

**Comment by 88250** [comment]
1. 暂时不加了，后面再看需求
2. 暂时不改了
3. 这个加不了

**Comment by 5kyfkr** [comment]
我又想到个办法，解决不能方便管理多层知识的问题，能不能一个位置多个视图，做成标签页，毕竟上面这空白看着就适合放多标签，这样就多了一个视图的层级了

![Image](https://github.com/siyuan-note/siyuan/assets/63196026/b34508a4-eab3-4490-850a-99e8bb65043d)

**Comment by 88250** [comment]
@5kyfkr 后面会有其他视图页签的。

**Comment by 5kyfkr** [comment]
那就没辙了，不能分层级就还替代不了用无序列表做目录的作用，感觉有一点点可惜，只能希望白板能解决更清晰的可视化层级管理了

**Comment by wrwe3888** [comment]
> 

Notion就是可视化层级啊，tower, clickup做的也很不错。

**Comment by wrwe3888** [comment]
D大，数据表格大约什么时候能上线？

**Comment by 88250** [comment]
争取今年年底以前吧。

**Comment by ognsya** [comment]
> Try to do it before the end of this year.

I'm curious, why is the release date moving so many months forward from original predictions?

Any issues in development? Or can we expect extra features?

Again, just curious! No rush 🙂

**Comment by 88250** [comment]
@ognsya There are some details that need to be considered, so the official version needs to wait, thank you.

**Comment by AugustTuan** [comment]
这个做出来，是不是就可以抛弃飞书的多维表格了，必须联网，而且每次打开表格都要转圈圈，忍它很久了(*/ω＼*)

**Comment by yylicon** [comment]
请问下画廊视图在计划内吗，就是用图片作为卡片封面的那个视图，挺好看的，希望加这个

**Comment by 88250** [comment]
@yylicon 目前还没有，表格视图做完以后是看板视图。

**Comment by wrwe3888** [comment]
表格涉及到的细节功能多，从现在开始，从初次发布到功能一个个完善，最后达到飞书多维表现在的情况，感觉总得一两年时间吧。

> 这个做出来，是不是就可以抛弃飞书的多维表格了，必须联网，而且每次打开表格都要转圈圈，忍它很久了(_/ω＼_)

**Comment by AugustTuan** [comment]
估计把这个issue关闭，思源才会发布3.0版本

**Comment by 88250** [comment]
嗯，这个特性就是计划在 3.0.0 发布。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 15:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database (Attribute View) (#2829)




 
估计把这个issue关闭，思源才会发布3.0版本

**Comment by aobatu** [comment]
@88250  3.0.0计划啥时候发布呢？目前表格开发是还在继续不，看最近好像没有相关进展了。

**Comment by 88250** [comment]
年底前吧，最近也有进展的。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 22:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database (Attribute View) (#2829)




 
@88250  3.0.0计划啥时候发布呢？目前表格开发是还在继续不，看最近好像没有相关进展了。

**Comment by SineMark2020** [comment]
不考虑2.x.x时先公测吗？ 例如database(Beta) , 让很多人一起测试，否则内测后直上3.0容易问题一堆.

**Comment by 88250** [comment]
@SineMark2020 会在正式版发布之前公测一段时间的，付费（功能特性或订阅）用户可参与公测。

**Comment by heartacker** [comment]
有点不是很理解，为什么 第一个一定是 block

**Comment by 88250** [comment]
@heartacker 和 Notion Database 类似，需要一个“主键”，更多讨论参见 https://github.com/siyuan-note/siyuan/issues/9272

**Comment by SineMark2020** [comment]
> @SineMark2020 会在正式版发布之前公测一段时间的，付费（功能特性或订阅）用户可参与公测。

其实可以考虑让database 公测成为一个长期计画，等tables view, Kanban view, 等等其它视图完整后再上到3.0

**Comment by 88250** [comment]
其他视图看情况吧，年内还是得先上线表格视图。



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 3, 2023 09:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database (Attribute View) (#2829)




  
@SineMark2020 会在正式版发布之前公测一段时间的，付费（功能特性或订阅）用户可参与公测。
  
其实可以考虑让database 公测成为一个长期计画，等tables view, Kanban view, 等等其它视图完整后再上到3.0

**Comment by hdg8087** [comment]
希望能让用户选择是否在页面上显示 自定义属性 表格属性。
希望自定义属性的属性名能够使用中文。

**Comment by 88250** [comment]
@hdg8087 第一个暂时不考虑了，因为块级属性都可以作为数据库数据，所以统一使用属性面板更合理一些。第二个是技术原因无法使用中文  #8440 #7581 #9312

**Comment by fwonce** [comment]
> 这个做出来，是不是就可以抛弃飞书的多维表格了，必须联网，而且每次打开表格都要转圈圈，忍它很久了(_/ω＼_)

试用了，这个跟多维表还不一样，核心还是属性视图，就是必须关联一个block。
难受，至少跟我的use case不一样。

**Comment by 88250** [comment]
@fwonce 最新版已经不用必须关联到块了，可以直接在表格中添加行数据。

**Comment by jl0476** [comment]
@88250 现在搜索无法检索到属性视图内的内容，这个后续考虑支持吗？

**Comment by 88250** [comment]
@jl0476 后续会支持的。

**Comment by wrwe3888** [comment]
筛选成不同的视图，这种功能有没有计划？

**Comment by 88250** [comment]
@wrwe3888 目前还没有。

**Comment by wrwe3888** [comment]
哦，理解，要做的事太多，这个优先级不够。
希望以后能开发出来，毕竟筛选是数据库的基本功能之一嘛。

**Comment by Yinian12** [comment]
请问能支持在数据库中插入在线图片吗？

**Comment by 88250** [comment]
@Yinian12 支持的，使用资源列：

![image](https://github.com/siyuan-note/siyuan/assets/873584/f1116496-ee73-45ad-8853-50c3bc6ddadb)

**Comment by Yinian12** [comment]
> @Yinian12 支持的，使用资源列：
> 
> ![image](https://user-images.githubusercontent.com/873584/280525513-f1116496-ee73-45ad-8853-50c3bc6ddadb.png)

😮但是这样好像只有链接，不会像插入本地图片一样显示出来

**Comment by 88250** [comment]
好像是有点问题，我们稍后看看。 @Vanessa219

**Comment by xiaofeng010766** [comment]
D大，这个database后期是只有会员能用？

**Comment by 88250** [comment]
> D大，这个database后期是只有会员能用？

内测结束后会对多有用户开放。

**Comment by jl0476** [comment]
@88250 database删除行后ctrl+z撤回，删除的行加回来了，但是行里面数据是空的。设计就是这样的吗？

**Comment by 88250** [comment]
暂时只能这样了，数据撤回不了。



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 12, 2023 14:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database (Attribute View) (#2829)




 
@88250 database删除行后ctrl+z撤回，删除的行加回来了，但是行里面数据是空的。设计就是这样的吗？

**Comment by arminta7** [comment]
Is this still planned for release before the end of the year? 😎

**Comment by 88250** [comment]
@arminta7 We plan to release this feature in mid-February 2024, thank you.

**Comment by lisontowind** [comment]
D大，计划中有calendar view吗？

**Comment by 88250** [comment]
@lisontowind 目前还没有，表格视图完成以后是看板视图 #8873 ，然后可能是画廊视图。

**Comment by SunshineWang** [comment]
> calendar view

希望能优先 calendar view 和 甘特图/timeline view，这样通过一个任务数据库就可以把日程/项目管理功能融合进来，就不需要其它日程软件了。

**Comment by 88250** [comment]
下个视图的计划是看板视图，谢谢。



---Original---
From: ***@***.***&gt;
Date: Tue, Feb 13, 2024 17:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database table view (#2829)




  
calendar view
  
希望能优先 calendar view 和 甘特图/timeline view，这样通过一个任务数据库就可以把日程/项目管理功能融合进来，就不需要其它日程软件了。

**Comment by H-a-r-r-o-w** [comment]
属性视图完成，然后是看板试图
请问这个“属性视图完成”包括公式功能吗？

白板功能是准备放在看板之后？还是另有计划？

**Comment by 88250** [comment]
白板暂时还没有明确计划。



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 14, 2024 17:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Database table view (#2829)




 
属性视图完成，然后是看板试图
 请问这个“属性视图完成”包括公式功能吗？
 
白板功能是准备放在看板之后？还是另有计划？
