### ISSUE TITLE
选择文本右键选项“创建以此为标题的新笔记”

### ISSUE THREAD

**Issue by Angus-169** [siyuan-note/siyuan#283]

**Comment by 88250** [comment]
需要建立内容块链接么？

**Comment by Angus-169** [comment]
需要直接和被选中项建立链接，但是应当是从被选中文本指向新建的文件

**Comment by 88250** [comment]
好的，等自顶向下的基础用法在 https://github.com/siyuan-note/siyuan/issues/70 中完成之后会加入，谢谢提议。
