### ISSUE TITLE
带子级升降标题层级

### ISSUE THREAD

**Issue by yangguang760** [siyuan-note/siyuan#2860]
从orgmode转过来的，有个功能特别方便，希望可以在思源实现。
具体来说，添加两个菜单操作并可绑定快捷键：
第一个操作：升/降当前标题级别
第二个操作：升/降当前标题及子标题级别

**Comment by 88250** [comment]
后面一点再考虑，谢谢。

**Comment by Vanessa219** [comment]
/api/block/getHeadingLevelTransaction {id:string, level:int}

**Comment by Chenm4** [comment]
目前有一个问题是，我网页剪藏为md格式，可能最高级的标题才是2级标题，并且有挺多个2级标题并列，我想将它们都转为一级标题貌似没有快速转换的方法，新建一个一级标题最多把子标题转为二级标题，能够增加上将子标题转换为一级标题的选项？

**Comment by TCOTC** [comment]
@Chenm4 请关注 https://github.com/siyuan-note/siyuan/issues/11838
