### ISSUE TITLE
导入typora的md文件时，图片丢失

### ISSUE THREAD

**Issue by allceo** [siyuan-note/siyuan#2865]
typora编写md的文件夹目录下存放图片的目录为：.images

md文件中插入图片：

![image](https://user-images.githubusercontent.com/1932516/132218797-4f9f5ffe-ab37-41d7-988c-7b6ed4e80416.png)

导入文件夹之后，思源下查看导入文件为：

![image](https://user-images.githubusercontent.com/1932516/132218716-14061ca0-e7e1-46e5-a74d-45352cbda421.png)

![image](https://user-images.githubusercontent.com/1932516/132218377-50c5b1f3-b405-4b94-992b-3db7ee2df856.png)

* Version:  v1.3.4
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
你好，`.` 开头的文件或文件夹会被忽略，这个估计只能通过批量替换原始文件来解决了。

**Comment by xiosi** [comment]
![图片](https://user-images.githubusercontent.com/65847420/161001741-8f851909-538e-49f0-9bf3-f8a200096063.png)
这种的通过复制粘贴也导入不了！
![图片](https://user-images.githubusercontent.com/65847420/161002075-47401988-c6c9-4efb-8a23-4ad534127ad1.png)

版本：docker image1.9.2
