### ISSUE TITLE
Android 11 以下无法正常进入

### ISSUE THREAD

**Issue by TonyW825** [siyuan-note/siyuan#2868]
### Describe the problem

下载最新版本后直接安装，启动界面后，一直处于 LOGO 页，无法进入，但伺服正常可用。

不清楚是否为手机版本问题，自用的坚果 Andriod 7 和 10 都无法进入。

### Screenshot or screen recording presentation

https://user-images.githubusercontent.com/46043068/132232132-936ce190-20fe-4817-80e5-7f2ee2a4e9d9.mp4

### Version environment

* Version: 1.3.4
* Operating system: Android 7.1.1 & Android 10
* Browser (if used): 

### Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/7116582/siyuan.log)

**Comment by 88250** [comment]
日志上看好像一切正常，能帮忙试下 v1.3.3 是否有此问题吗？

**Comment by 88250** [comment]
麻烦用 V1.3.4 伺服，桌面端访问，F12 切换到移动端浏览器看下是否有报错。

**Comment by TonyW825** [comment]
![2021-09-06_23-20-11](https://user-images.githubusercontent.com/46043068/132238564-77b37bf2-76b1-4787-b28b-d8ec4e235bdf.png)
是这个吗？

**Comment by 88250** [comment]
得重新访问一下 IP:6806 这样才会切换到移动端

**Comment by TonyW825** [comment]
![2021-09-06_23-35-23](https://user-images.githubusercontent.com/46043068/132239885-53bc6084-28ff-4a56-b5bf-723041bf4928.png)

**Comment by 88250** [comment]
感谢帮忙，好像是 Android 11 以下都有问题，我们再排查看看。

**Comment by 88250** [comment]
Android 端 v1.3.41 已经发布，麻烦下载后安装看看。

**Comment by TonyW825** [comment]
> Android 端 v1.3.41 已经发布，麻烦下载后安装看看。

v1.3.41 可正常进入。辛苦。

**Comment by TonyW825** [comment]
@88250  D大，该问题在更新完 v1.3.5-alpha1 后又出现了，烦请抽空排查。谢谢。

---

I 2021/09/15 15:27:06 working_mobile.go:39: 

I 2021/09/15 15:27:06 runtime.go:37: kernel is booting:
    * ver [1.3.5-alpha1]
    * arch [arm64]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20210913]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan, data 5.9 MB]
    * rsync [/data/app/org.b3log.siyuan-uPyN_GJN1GwKva2ot0ZmLg==/lib/arm64/librsync.so]
I 2021/09/15 15:27:06 conf.go:232: local serve path [http://10.139.116.210:6806]
I 2021/09/15 15:27:06 database.go:130: initialized database tables
I 2021/09/15 15:27:06 database.go:84: reinitialized database [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2021/09/15 15:27:06 conf.go:407: pre-init database size [33 kB]
E 2021/09/15 15:27:06 box.go:78: not found box conf [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/data/20210808180117-czj9bvb/.siyuan/conf.json]
I 2021/09/15 15:27:06 conf.go:419: post-init database size [33 kB]
I 2021/09/15 15:27:06 working.go:108: kernel booted
I 2021/09/15 15:27:06 serve.go:68: kernel is booting [http://127.0.0.1:6806]

**Comment by 88250** [comment]
收到，a2 修复。
