### ISSUE TITLE
重名检测

### ISSUE THREAD

**Issue by yhhwanwu** [siyuan-note/siyuan#2869]
新版本允许文档重名了吗？有时候会忘了以前已经建立过同名的文档，能否添加一个重名检测，或者将新建同名文件合并到同名的旧文档中是否可行？

Version environment
Version: 1.3.2
Operating system: win10

**Comment by 88250** [comment]
已经允许文档标题重复了，这是个特性，暂时就不加重名检测了，谢谢。
