### ISSUE TITLE
希望能把 选中的内容块 移动到 对应的文档上 实现插入到这个文档后方

### ISSUE THREAD

**Issue by VSpade7** [siyuan-note/siyuan#2871]
我个人习惯是在dailynote或是在某个笔记本建个inbox来记录灵感，累积一段时间后，开始把其中相关的内容挪出来生成一篇新的文章，经常会从多个文档的挪动内容到一个文档里去，目前只能不断得剪切粘贴，有点难受

**Comment by 88250** [comment]
拖拽移动应该也行，但是剪切粘贴应该是最快的方式了。

如果是标题的话可以试试标题转换文档（将标题直接拖拽到文档树上），如果是其他类型的块，后面再逐步支持，比如 #2610
