### ISSUE TITLE
搜索结果上下键切换问题

### ISSUE THREAD

**Issue by Sanly** [siyuan-note/siyuan#2872]
[这篇帖子](https://ld246.com/article/1630732678425)中提及的bug可以重现了：

无论在 CTRL+P 模式还是 CTRL+F 模式，在进行关键词搜索后，用鼠标任意点选一栏结果，然后用上下键就无法切换搜索结果了，只能滚动结果列表。

D大看看是不是有这个问题。

**Comment by 88250** [comment]
感谢，已经可以重现。

PS 论坛上艾特或者回复我也能有通知的。

**Comment by Sanly** [comment]
谢D大提示！
