### ISSUE TITLE
支持 Windows 单词补全系统

### ISSUE THREAD

**Issue by xBLACKICEx** [siyuan-note/siyuan#2874]
请支持window单词补全系统
![gqdgfdfq](https://user-images.githubusercontent.com/51036094/132395178-94a7e365-28c5-4eaf-a315-667de341c2c2.gif)

**Comment by 88250** [comment]
这个不大清楚要怎么实现，我觉得好像应该靠输入法？

**Comment by xBLACKICEx** [comment]
> 这个不大清楚要怎么实现，我觉得好像应该靠输入法？

思源网页版是支持的，看看是不是electron的问题,毕竟notion也是election实现的。

**Comment by xBLACKICEx** [comment]
@88250 
标题是有补全的！其他的都不行
![hsgqerg](https://user-images.githubusercontent.com/51036094/132832472-7ca9e7bf-e671-45f0-97e9-83b298ae62e4.gif)

**Comment by 88250** [comment]
这个问题暂时无法解决了，我关闭了，感谢反馈。
