### ISSUE TITLE
块嵌入，表格显示重复

### ISSUE THREAD

**Issue by huanongkou** [siyuan-note/siyuan#2883]
### 块嵌入，表格显示重复

![image](https://user-images.githubusercontent.com/5572885/132638904-a793b6b5-280e-4a4a-a5f6-a5cf99714ed8.png)
如图操作显示，将文件《IT 专区》复制为 嵌入款，黏贴到《阿里云盘资源》，《阿里云盘资源》在导出模式下，table 重复显示了，但是在所见所得的模式下 正常显示

**Comment by 88250** [comment]
https://ld246.com/article/1631172970951

**Comment by huanongkou** [comment]
这个啥时候修复呀？

**Comment by 88250** [comment]
还没确认问题……需要再等等。

**Comment by 88250** [comment]
@huanongkou 我这里目前在 v1.3.5 开发版上重现不了，等正式版发布以后麻烦你再看下，谢谢。

**Comment by huanongkou** [comment]
好的  那我等 V1.3.5

**Comment by 88250** [comment]
我关闭了，如果还有问题请跟帖。
