### ISSUE TITLE
笔记打不开

### ISSUE THREAD

**Issue by lepecoder** [siyuan-note/siyuan#2884]
昨天刚装的1.3.4今天笔记就打不开了，重装1.3.3也不行，这里面有我找工作的所有所有东西，面试笔记，真实无语了！！！！！！！！！！！！！！！！！！
![](https://i.bmp.ovh/imgs/2021/09/3cab06b820ee8f55.png)

**Comment by 88250** [comment]
https://ld246.com/article/1631173591364
