### ISSUE TITLE
能否支持更多远程同步方案？

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#2886]
### In what scenarios do you need this function?

多设备之间同步笔记

### Describe the optimal solution

可以参考Joplin那种同步方案，支持很多种服务端，比如能同步到自己搭建的nextcloud应用里

**Comment by 88250** [comment]
你好，这个暂时不是重点，我们在蹲 [Rclone](https://github.com/rclone/rclone) 的双向同步，等它正式上线后再考虑，谢谢。
