### ISSUE TITLE
docker `--workspace` not work with non-exist directory

### ISSUE THREAD

**Issue by grsky360** [siyuan-note/siyuan#2891]
### Describe the problem

When I'm using docker to deploy siyuan with `--workspace`, it is not working when the target directory not is not exist.

![image](https://user-images.githubusercontent.com/13222125/132804840-668c5782-2da3-40f9-bbce-d71141701844.png)
![image](https://user-images.githubusercontent.com/13222125/132804863-40a9de58-e188-4878-b558-e240931705b5.png)

**Comment by 88250** [comment]
Please try it specify args with `--workspace=/xxx`.

**Comment by grsky360** [comment]
Not working without exist directory
![image](https://user-images.githubusercontent.com/13222125/132972645-ec3e3659-ffca-4cd5-bed0-eed330f28538.png)

Here is the correct way by mkdir manually
![image](https://user-images.githubusercontent.com/13222125/132972670-d66e257b-1e9c-4e93-9489-491bbaaa1b17.png)

**Comment by 88250** [comment]
The `--workspace` does not support `$HOME` env var.

**Comment by grsky360** [comment]
@88250 I don't think it is about $env. In Linux/Mac, when we enter a $env, it is auto replaced by the real value. So the real value was pass.
And even if I write the absolute path, it doesn't work

**Comment by 88250** [comment]
@grsky360 Sorry for that, you are right. SiYuan will not create workspace dir if it does not exist, except the path is default (~/Document/SiYuan).

**Comment by grsky360** [comment]
Will this behavior be fixed or it should be as-is?
I think auto creating behavior will be better in some environment like docker

**Comment by 88250** [comment]
@grsky360 I have added a log output on to it, no auto mkdir.
