### ISSUE TITLE
建议书签和大纲的快捷键调换一下

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#29]
1，按快捷键alt+1出现文件树
2，按alt+2出现书签
3，再按alt+2书签关闭，顶端出现文件树字样，但实际显示的是大纲内容。此处可以反复复现。
4，若没有第一步，书签只显示打开关闭状态
5，是否可以按alt+1出现文件树，再按出现大纲？或者alt+2改成大纲，alt+3为书签，文件树和大纲似乎逻辑上更贴近一些，这样是否更好呢？

**Comment by Vanessa219** [comment]
到第三步为止都没有打开大纲，应该不会显示大纲内容。我这里无法重现。

快捷键后期可以进行自定义，这里就不进行修改了。

**Comment by zhl111** [comment]
文件树和大纲之间的问题还是有一个问题。
alt+1开文件树 →→OK
alt+1关文件树 →→ OK
alt+2开大纲 →→ OK
alt+2关大纲 →→ OK
alt+1开文件树 →→ 空白一次
应该可以复现

**Comment by Vanessa219** [comment]
0.2.4 修复
