### ISSUE TITLE
输入行内代码时的bug

### ISSUE THREAD

**Issue by SylleoYr** [siyuan-note/siyuan#2904]
### Describe the problem

输入行内代码时, 先输入 `\`\``, 然后再输入文字, 仅会将第一个字母作为行内代码 (见 gif). 使用快捷键 Ctrl+G 时没有这个问题.

### Expected result

输入 `\`\`` 后再输入文字时保持行内代码样式, 待光标移出行内代码范围时恢复.

### Screenshot or screen recording presentation

![inline_code](https://user-images.githubusercontent.com/23133978/132971320-5e601457-f482-4558-b8a7-7c122a25a0c5.gif)

### Version environment

* Version: v1.3.4
* Operating system: Windows 10 21H1 19043.1165
* Browser (if used): 

### More information

一个小建议, 希望可以在输入的时候显示输入位置处的 markdown 源代码, 类似 Typora 那样.

![2021-09-12_11-47-02](https://user-images.githubusercontent.com/23133978/132971345-58fd46a8-5ded-44d9-9406-39721ab715db.png)

**Comment by 88250** [comment]
这个暂时不做调整了，所见即所得模式没有办法二者兼顾……

**Comment by SylleoYr** [comment]
后期可以改进吗? 感觉可以做成就像 Typora 的所见即所得那样 🤣 

![2021-09-12_15-44-57](https://user-images.githubusercontent.com/23133978/132978197-eef6a1b7-ecce-4b57-9fdf-f6c424a23212.png)

**Comment by SylleoYr** [comment]
- 这个 bug 在修改一个已存在的行内代码的开头或末尾时也会出现, 只能在一个行内代码的中间部分进行修改

![inline_code_2](https://user-images.githubusercontent.com/23133978/132978985-ce8fca11-c7f1-4081-be90-9143793b873d.gif)


- 使用 Ctrl + G插入行内代码时, 输入完成后按下方向键, 光标并未跳出行内代码区域, 但此时输入文字已经不再行内代码区域中

![inline_code_3](https://user-images.githubusercontent.com/23133978/132979420-0ecdeb82-08b3-40b0-966d-a98d1c48d01d.gif)

**Comment by 88250** [comment]
@SylleoYr 这部分的设计暂时不会动了，参考的是 Notion，所见即所得的编辑器大概只能这样设计了。
