### ISSUE TITLE
增加折叠列表（ToggleList）

### ISSUE THREAD

**Issue by haiyusun** [siyuan-note/siyuan#2907]
希望输入`/`时有ToggleList的选项，默认折叠，点击展开。

![image](https://user-images.githubusercontent.com/21038884/132988632-eb26964f-c94e-4246-9e13-80bc45ff00e9.png)

![image](https://user-images.githubusercontent.com/21038884/132988637-a72e22e4-d953-4d90-8c5c-07f645bbb22f.png)

**Comment by 88250** [comment]
你好，已有列表已经支持折叠，谢谢。
