### ISSUE TITLE
支持设置块引时新建文档默认存储路径

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#291]
自上而下建立的新文档位置可以调整

**Comment by 88250** [comment]
在设置中加一个默认保存位置吗？

**Comment by Asasahn** [comment]
是的 就可以在设置中更改默认保存位置




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 中午11:59
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;; 
抄送: "单志玮"<1026411669@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [siyuan-note/siyuan] 自上而下建立的新文档默认位置可以调整为其他文件夹 (#291)





 
在设置中加一个默认保存位置吗？
