### ISSUE TITLE
行级元素支持多重样式类型

### ISSUE THREAD

**Issue by SylleoYr** [siyuan-note/siyuan#2911]
该方案相关变更：

* https://github.com/siyuan-note/siyuan/issues/5869
* https://github.com/siyuan-note/siyuan/issues/5787

**旧版本不兼容新版本数据格式，所以一旦升级到新版本以后，所有端都必须使用新版本，否则行级元素会丢失。** 建议升级前手动备份一次数据，所有端都安装好新版本以后再启动。

---

以下是原提议：

### Describe the problem

编辑文字无法选择叠加多个样式, 如 加粗+斜体, 斜体+颜色, 只能选择单一样式. 

一种解决办法是手动输入标记, 如 加粗+斜体, 并且只能按照如下顺序输入:

1. `***`
2. `***test`
3. `***test***`

加粗+链接:

1. `**[test](link`
2. `**[test](link)**`

因为一旦提前输入了完整的样式标记符号, 如 `****`, 再将光标移至中间就会使得只有第一个字母被添加上样式 (中文可能是因为输入法原因好像没这个问题)

### Expected result

可以为一段文字叠加多个样式, 如 加粗+链接, 加粗+斜体/删除线/下划线 等等.

手动输入多有不便, 还是希望可以选择多个样式叠加.

### Screenshot or screen recording presentation

![stack_style](https://user-images.githubusercontent.com/23133978/133010376-0e17410d-7595-4aad-a518-a2b928e8e514.gif)

### Version environment

* Version: v1.3.4
* Operating system: Windows 10 21H1
* Browser (if used):

**Comment by 88250** [comment]
这个比较复杂，暂时不做改进，后面要做的话会重开，谢谢。

**Comment by SylleoYr** [comment]
👌

**Comment by 88250** [comment]
加粗使转义符暴露 https://github.com/siyuan-note/siyuan/issues/2849

**Comment by bestv5** [comment]
目前思源作者还没计划增加多重效果。看来只能先手动输入效果了。附图
![image](https://user-images.githubusercontent.com/15650275/141040974-8a4aa28b-d6ff-428c-ac16-3b040d3d8d4e.png)

**Comment by jabobian** [comment]
我觉得如果能提供 Alt-Shift-X，弹出
字体样式 这个窗口就基本可以用了，可以自己设计一组鼠标动作点击对应位置来切换字体。

用Autohotkey能检测到这个窗口，字体样式 - 思源 v1.8.2 ahk_class Chrome_WidgetWin_1 ahk_exe SiYuan.exe 。
Alt-X默认是应用当前字体样式。

**Comment by woniuxia** [comment]
喜大普奔~

**Comment by tcmtom** [comment]
终于来了

**Comment by 88250** [comment]
该方案相关变更：

* https://github.com/siyuan-note/siyuan/issues/5869
* https://github.com/siyuan-note/siyuan/issues/5787
