### ISSUE TITLE
文档树剪切文档

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2913]
https://ld246.com/article/1631511656276

[文档树复制文档](https://github.com/siyuan-note/siyuan/issues/2790)

**Comment by yanyu2015** [comment]
不知道这个功能啥时候能安排上

**Comment by 88250** [comment]
@yanyu2015 暂时还没有时间处理，抱歉了。

**Comment by 88250** [comment]
考虑之后我们觉得移动已经覆盖剪切了，所以就不支持剪切了。

**Comment by yanyu2015** [comment]
使用了下现在的移动，好像跟之前的没啥区别
当文件目录较多的时候，定位依然很麻烦，我觉得如果实在不支持剪切(或者复制粘贴)的话，倒不如把现在的移动跳出的面板改成树形的
