### ISSUE TITLE
导出为长图

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#2919]
* https://github.com/bubkoo/html-to-image
* https://github.com/niklasvh/html2canvas
* https://ld246.com/article/1655728431623

**Comment by Zuoqiu-Yingyi** [comment]
这里有个临时解决方案:
1. 复制需要导出的内容为嵌入块
2. 单击嵌入块 SQL 输入框右上角的 <kbd>复制 PNG</kbd> 按钮
3. 嵌入块渲染的截图将写入剪贴板
![image](https://user-images.githubusercontent.com/49649786/161391423-d838574b-fd92-458a-ab2f-82203b74268b.png)

**Comment by aobatu** [comment]
这个功能有计划什么时候开发不？

**Comment by 88250** [comment]
@aobatu 暂时没有排期，还在做其他任务。

**Comment by aobatu** [comment]
发现最新的2.0.4版本不能使用浏览器的截图插件了，用的是chrome浏览器，试了Nimbus Capture、Fireshot、Awesome Screenshot都不可以，原先1.9版本的时候还用过Awesome Screenshot是ok的，但是现在就卡死了。
这样就无法把笔记内容截图导进行分享了。。。

**Comment by 88250** [comment]
可考虑导出 HTML 然后再截图。

**Comment by aobatu** [comment]
> 可考虑导出 HTML 然后再截图。

这种操作太复杂了，操作流程太长，如果要分享多个内容（若超过屏幕）就非常麻烦；
还有一个问题是，导出HTML好像是整个文档都要导出，而不能只导出其中某部分内容。这样如果一个文档本身很长，只想截取其中一部分，要把整个文档全部导出HTML，然后全截图，再从中选择一部分，非常不现实。
原先可以还支持浏览器截图的时候，只需要聚焦内容，然后滚屏就好。

这样看下来，由于现在版本不支持浏览器滚动截图了，所以导出长图这个功能变得比较迫切了！

**Comment by 88250** [comment]
这部分暂时还没有精力解决，只能再等等了，感谢理解。

**Comment by aobatu** [comment]
好的，那我就先静静等待，辛苦了~

**Comment by aobatu** [comment]
@88250  想问下这个功能最近有计划了不？:)

**Comment by 88250** [comment]
@aobatu 短期内没有哦。

**Comment by aobatu** [comment]
感谢@D支持！
现在的导出长图是导出整个文档，未来是否可以支持内容块的导出图片呢？
我的诉求场景是，想要导出某个标题下面的整个文字为长图，不知道这样是否可以实现？

**Comment by Vanessa219** [comment]
是否可以拆成不同的文档呢？这样的话感觉不太好操作。

**Comment by Achuan-2** [comment]
> 是否可以拆成不同的文档呢？这样的话感觉不太好操作。

我觉得可以导出当前聚焦的块

**Comment by aobatu** [comment]
我新创建个个issue吧

**Comment by wingofsky** [comment]
这个功能太赞了

**Comment by choora** [comment]
长到了一定的程度应该自动切割图片吧……一个 10+w 字的文档尝试导出长图，到现在就只能等待，其他操作都操作不了……

**Comment by terwer** [comment]
我觉得应该是自己去控制文档文字字数，不应该切割。不然长图还能叫长图吗
一个文档能到10万字，那说明没有遵循最佳实践，我一般文章超过2000-3000字就会新建文档。
之前用typora的时候文章超过3000就会感觉明显卡顿。

**Comment by Zuoqiu-Yingyi** [comment]
是不是可以另起一个页面/进程负责导出图片的渲染?

**Comment by gqfgh** [comment]
好像文档的标题没有导出，能加上吗？

**Comment by Vanessa219** [comment]
> 好像文档的标题没有导出，能加上吗？

设置里面配一下

**Comment by Vanessa219** [comment]
> 是不是可以另起一个页面/线程/进程负责导出图片的渲染?

理论上可以起一个 Worker，但计算还是比较耗费的，这个也不经常操作，等后面再优化优化。
