### ISSUE TITLE
上标与加粗功能不能同时实现

### ISSUE THREAD

**Issue by mingyuezhaowo** [siyuan-note/siyuan#2923]
### Describe the problem

一行文字使用 ctrl + B 加粗后，再选中某个文字使用上标功能，发现整行文字都变成上标格式了；
如果先选中某个文字上标，再选中整行加粗，则上标效果消失。

### Expected result

上标与加粗效果可以同时存在。

### Screenshot or screen recording presentation

![上标加粗问题](https://user-images.githubusercontent.com/17918944/133387704-2ac207c3-cd3d-4d14-80c1-71b1211734ff.gif)

### Version environment

* Version:  v1.3.4
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
请参考 https://github.com/siyuan-note/siyuan/issues/2911
