### ISSUE TITLE
PDF 批注建议增加1. pdf内部批注 2.导出功能 3.导入识别原有批注并转化为格式

### ISSUE THREAD

**Issue by GuoYimingac** [siyuan-note/siyuan#2926]
1. 有时候可能会需要进行批注并保存到pdf文件里面,用于之后的导出至其他软件或交流,可以在荧光笔那里增加一个类似对话框的东西,在里面输入的内容将被保存在pdf文件中,这之后在笔记中cmd V可以带着引用的内容和在对话框中的批注一起复制.
2. 导出pdf时可以把需要的批注导出,和荧光笔画的地方一起导出.
3. 可以识别原来存在pdf中的批注,点击荧光笔区域,并cmd V 可提取并复制到笔记中,包含批注.(也可以考虑允许在导入时自动提取并复制到新文档中)
这三点式之前在zotero beta 版本的pdf浏览器中特别实用的功能2333希望能够考虑

**Comment by 88250** [comment]
写入 PDF 的操作目前做不到，以后如果有可能做的话再打开，谢谢。

**Comment by GuoYimingac** [comment]
提取批注现在能做吗?

**Comment by 88250** [comment]
放在后面的版本考虑，有可能会用挂件实现。
