### ISSUE TITLE
支持 SOCKS5 网络代理

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2928]
仅桌面端支持，移动端和 Docker 暂时不考虑。

* [ ] 代理设置
* [x] 内核 HTTP 请求代理
* [x] 内核 SSH 连接代理
* [ ] Electron HTTP 请求代理

**Comment by walklty** [comment]
太好了.
真的是单位有限制得用代理.

**Comment by JokeenZhang** [comment]
> 太好了. 真的是单位有限制得用代理.

有什么用吗？不太了解做什么的

**Comment by JokeenZhang** [comment]
> 太好了. 真的是单位有限制得用代理.

有什么用吗？不太了解做什么的

**Comment by walklty** [comment]
> > 太好了. 真的是单位有限制得用代理.
> 
> 有什么用吗？不太了解做什么的

单位网络必须要走公司的代理否则无法访问外网.

**Comment by lhy1024** [comment]
移动端未来会支持么

**Comment by 88250** [comment]
> 移动端未来会支持么

请关注 https://github.com/siyuan-note/siyuan/issues/13784
