### ISSUE TITLE
反向链接中的所在位置信息直接以标题的形式呈现

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#293]

**Comment by 88250** [comment]
没有标题的块呢？

**Comment by Asasahn** [comment]
我的意思是 一个块所在的文档名&nbsp;

就现在是以这种方式呈现的嘛 可以直接以标题的形式呈现
Daily note
2020-10-14


反向链接内容






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 中午12:02
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;; 
抄送: "单志玮"<1026411669@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [siyuan-note/siyuan] 反向链接中的所在位置信息直接以标题的形式呈现 (#293)





 
没有标题的块呢？

**Comment by 88250** [comment]
那可能太宽泛了……可能加个文档-标题层级汇总会好一些，这个后面再考虑改进，谢谢。

**Comment by Asasahn** [comment]
我觉得反链的核心作用不是提供一个可以反向跳转的链接
而是把与某一链接相关的内容自动整合呈现出来
就类似于一个通过反向链接整理出来的新的文章 把原本零碎的分散的内容组织起来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 中午12:02
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;; 
抄送: "单志玮"<1026411669@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [siyuan-note/siyuan] 反向链接中的所在位置信息直接以标题的形式呈现 (#293)





 
没有标题的块呢？

**Comment by Asasahn** [comment]
> 那可能太宽泛了……可能加个文档-标题层级汇总会好一些，这个后面再考虑改进，谢谢。

好的

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/97832013-ac274580-1d0c-11eb-894d-2974edfa8ab1.png)

反链列表已经加入路径信息，上下文信息在 https://github.com/siyuan-note/siyuan/issues/295 中完成，谢谢。
