### ISSUE TITLE
反链页签上下文展现

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#295]
![Obsidian_ESdftzdmea](https://user-images.githubusercontent.com/67853721/96674473-7ba1ec00-139b-11eb-9fa9-900abfcb12fe.png)
![Obsidian_HIbpV2Fdg1](https://user-images.githubusercontent.com/67853721/96674474-7d6baf80-139b-11eb-9906-5e83a2798abf.png)
![Obsidian_8uLppp9rnR](https://user-images.githubusercontent.com/67853721/96674476-7d6baf80-139b-11eb-9652-ebf8baf3c5af.png)
![Obsidian_HT21apzDku](https://user-images.githubusercontent.com/67853721/96674477-7e044600-139b-11eb-82f3-f6ba73ba3bd2.png)
![Obsidian_v7pS9phazs](https://user-images.githubusercontent.com/67853721/96674478-7e9cdc80-139b-11eb-9e71-3b3b14e632e7.png)
![Obsidian_PP3WYhR7im](https://user-images.githubusercontent.com/67853721/96674481-7e9cdc80-139b-11eb-8aa0-00403c0f0543.png)

**Comment by xulei-shl** [comment]
希望不仅仅是obsidian那种简单的上下文显示，而是大纲的上级节点或者标题，以显示出链接块在整个文档中的层级位置。

个人的使用场景是：Daily Notes记录有多篇文章的笔记。然后用根节点或标题记录题名、章节名等信息，被链接的一般都是下级节点或正文部分。

不知道是否有普遍性此种需求是否有普遍性
