### ISSUE TITLE
PDF 画框复制注解带截图

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2952]
https://ld246.com/article/1632378417154

**Comment by hyjwonder** [comment]
+1

**Comment by QiuMP** [comment]
+1

**Comment by hyjwonder** [comment]
Any date planned to close this issue?

**Comment by 88250** [comment]
@hyjwonder No plans in the near future.

**Comment by youth54** [comment]
在使用过程中，对于图片公式较多的文档确实需要显示图片，个人感觉对于PDF阅读标注挺重要的。D大最近有实现这个功能的计划吗？期待早日实现～

**Comment by heimi98** [comment]
顶一下，期待早日开发。

**Comment by Danielypzhang** [comment]
@88250 请问这个需要什么设置吗？我升级后，手机做伺服器，电脑浏览器打开，没有截图显示。

**Comment by 88250** [comment]
@Danielypzhang 只有在桌面端支持，浏览器端不支持。
