### ISSUE TITLE
移动页签到新窗口

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#2955]
https://ld246.com/article/1632383202463

**Comment by Zuoqiu-Yingyi** [comment]
可以先用这个方法顶一顶: [\[思源笔记经验分享\] 多窗口功能](https://ld246.com/article/1649992440500)

**Comment by Elliootalderson** [comment]
> 可以先用这个方法顶一顶: [[思源笔记经验分享] 多窗口功能](https://ld246.com/article/1649992440500)

只有用dark那个主题,才可以. 关键我用不惯那主题. 看的我眼花

**Comment by isyngo** [comment]
> > 可以先用这个方法顶一顶: [[思源笔记经验分享] 多窗口功能](https://ld246.com/article/1649992440500)
> 
> 只有用dark那个主题,才可以. 关键我用不惯那主题. 看的我眼花

可以再仔细看下帖子内容，里面写了不使用Dark+主题的操作方式。

**Comment by Elliootalderson** [comment]
> > > 可以先用这个方法顶一顶: [[思源笔记经验分享] 多窗口功能](https://ld246.com/article/1649992440500)
> > 
> > 
> > 只有用dark那个主题,才可以. 关键我用不惯那主题. 看的我眼花
> 
> 可以再仔细看下帖子内容，里面写了不使用Dark+主题的操作方式。

早试过了, 我用的那个tokyo dark主题 反正没反应

**Comment by Zuoqiu-Yingyi** [comment]
> 早试过了, 我用的那个tokyo dark主题 反正没反应

我记得 Tsundoku Dark 主题自带 theme.js, 是覆盖文件后没反应吗

**Comment by woaihuangxueying** [comment]
> > 早试过了, 我用的那个tokyo dark主题 反正没反应
> 
> 我记得 Tsundoku Dark 主题自带 theme.js, 是覆盖文件后没反应吗

您是dark+主题地开发者，主题功能确实很丰富，但是外观实在是太花了

**Comment by Zuoqiu-Yingyi** [comment]
> 您是dark+主题地开发者，主题功能确实很丰富，但是外观实在是太花了

可以使用其他主题的样式, 使用 Dark+ 的功能, 都是模块化的

**Comment by Elliootalderson** [comment]
> > 您是dark+主题地开发者，主题功能确实很丰富，但是外观实在是太花了
> 
> 可以使用其他主题的样式, 使用 Dark+ 的功能, 都是模块化的

大佬, 希望可以给里面功能添加一起快捷键, 特别是导图, 我经常用

**Comment by Zuoqiu-Yingyi** [comment]
> 大佬, 希望可以给里面功能添加一起快捷键, 特别是导图, 我经常用
我认为使用模板更好, 模板支持设置块属性, 你将只有一个导图视图列表块的文档导出为模板即可

**Comment by Elliootalderson** [comment]
有道理👌

**Comment by 88250** [comment]
@Chenm4 抱歉，我没看懂你的疑问，麻烦再补充描述一下。

**Comment by Chenm4** [comment]
> @Chenm4 抱歉，我没看懂你的疑问，麻烦再补充描述一下。
抱歉是我回复错issue了，我是想在https://github.com/siyuan-note/siyuan/issues/3664这个issue下面问的。就是现在块引用的悬浮窗口还是不能拖动出siyuan，这个还是解决不了是吗

**Comment by 88250** [comment]
可以使用新窗口打开：

![image](https://github.com/siyuan-note/siyuan/assets/873584/0bdf17c5-3cbe-4eec-ae32-657c837cb081)
