### ISSUE TITLE
选中内容右键“作为内容新建文档”

### ISSUE THREAD

**Issue by Angus-169** [siyuan-note/siyuan#296]
方便将长文拆解为卡片笔记

**Comment by 88250** [comment]
文档标题用什么好呢？

**Comment by Angus-169** [comment]
可以以“当前文档名_编号/yyyymmddhhmmss”作新的文件名

**Comment by 88250** [comment]
还要继续收集需求进行讨论，感觉不是很广泛的需求……

**Comment by 88250** [comment]
目前已经支持 
![image](https://user-images.githubusercontent.com/873584/99618051-9b403900-2a5b-11eb-89ce-2100dc149840.png)

**Comment by 88250** [comment]
呃，弄错了，这个是文件名……提议需要的是作为内容……
