### ISSUE TITLE
汇编语法高亮

### ISSUE THREAD

**Issue by NU-LL** [siyuan-note/siyuan#2964]
如题 请问下可以加入汇编的语法高亮支持吗
如常用的x86汇编与arm汇编
x86中可能还会涉及AT&T汇编与inter汇编

**Comment by 88250** [comment]
可以支持这几种：

* ARM Assembly
* AVR Assembly
* Intel x86 Assembly
* MIPS Assembly
* WebAssembly

**Comment by NU-LL** [comment]
这些足够了 非常感谢
