### ISSUE TITLE
为什么没有源码了？要闭源了吗？

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#2966]

**Comment by 88250** [comment]
思源笔记目前不是开源项目，只有底层解析器是开源的 https://github.com/88250/lute

**Comment by Allenxuxu** [comment]
@88250 记得很早之前还看了一点源码的，忘记哪个仓库了，是把仓库删了吗？

**Comment by 88250** [comment]
@Allenxuxu https://github.com/88250/liandi/tree/v1.1.8

**Comment by wooyang2018** [comment]
我很生气，过不久就会有更多的收费功能出来了，我就又要换软件了

**Comment by wooyang2018** [comment]
本来想自己做一个扩展的，你这闭源了，真是无奈了

**Comment by 88250** [comment]
> 我很生气，过不久就会有更多的收费功能出来了，我就又要换软件了

可以试下这两个开源项目：

* https://github.com/logseq/logseq
* https://github.com/AppFlowy-IO/appflowy

**Comment by Allenxuxu** [comment]
> 我很生气，过不久就会有更多的收费功能出来了，我就又要换软件了

增加收费功能也无可厚非啊，毕竟都要生存，要想活着总得赚钱啊。

**Comment by jearton** [comment]
思源收费我觉得没啥问题，反正笔记内容是本地化的，云端存储只是一个中转站而已，又没存储你的明文内容，存的就是一堆加密后的乱码数据，你的笔记内容除了你自己能在本地解密，对其他人没有任何价值，无需介意。这和那些纯粹的云笔记是有本质区别的。而且就算开源了自己搭云服务器私有化部署不要成本的啊，核算下来还没思源的同步便宜呢。@wooyang2018

**Comment by jearton** [comment]
> > 我很生气，过不久就会有更多的收费功能出来了，我就又要换软件了
> 
> 可以试下这两个开源项目：
> 
> * https://github.com/logseq/logseq
> * https://github.com/AppFlowy-IO/appflowy

logseq到底还是国外开发的，对中文环境和国人思维习惯来说，试用过，一点都不友好，很难用。
appflowy没用过，不知道深浅

**Comment by 88250** [comment]
偶尔搜索这个 issue，补充一下，思源笔记现在已经完整开源 https://github.com/siyuan-note/siyuan/issues/5013
