### ISSUE TITLE
PDF 阅读时，出现大块阴影

### ISSUE THREAD

**Issue by PayneSnow** [siyuan-note/siyuan#2968]
Mac big sur 11.5.2
思源笔记最新版
每一页规定位置都有阴影
![截屏2021-09-25 21 40 59](https://user-images.githubusercontent.com/51922806/134773581-a90eef7e-c771-425e-9799-e693088f6663.png)
![截屏2021-09-25 21 41 11](https://user-images.githubusercontent.com/51922806/134773587-78e587e5-3d9e-4867-93ab-c546d2180006.png)

**Comment by 88250** [comment]
默认主题有这个问题吗？如果有的话，是否能分享一下 PDF 我们方便调试，谢谢。

**Comment by PayneSnow** [comment]
好快，真的好佩服您！稍等，我先测试一下其他主题。

**Comment by PayneSnow** [comment]
![截屏2021-09-25 21 48 10](https://user-images.githubusercontent.com/51922806/134773810-3de49143-c694-45bf-8741-b653d177af15.png)
重新打开后，阴影面积变大了

**Comment by PayneSnow** [comment]
> 默认主题有这个问题吗？如果有的话，是否能分享一下 PDF 我们方便调试，谢谢。
D 大，我测试了包括默认主题在内的其他四五个主题，都没有问题。出现问题的就是我使用的截图中的那个黑暗主题 Room

**Comment by 88250** [comment]
感谢反馈，麻烦给该主题仓库提 issue，我关闭了。
