### ISSUE TITLE
代码块无法对齐

### ISSUE THREAD

**Issue by xibaibai9527** [siyuan-note/siyuan#2971]
看过别人的解释，说是第三方写的主题的问题，但我发现这是内置的代码块风格问题。
选择最上面的ant-design会复现bug，换成vs就好了（虽然还是感觉行号有一点点高）

另外再请教一下，是不是没办法实现像vs那样的复杂的代码高亮？
c# 代码诸如Console.Write都不会自动高亮

**Comment by 88250** [comment]
* 能否帮忙截图一下对齐问题？
* 目前代码高亮使用的是 https://highlightjs.org/，看官方 demo https://highlightjs.org/static/demo/  也是没有高亮
  ![image](https://user-images.githubusercontent.com/873584/134808692-ea6e9b41-4c3a-4af6-b671-6bfd40599cee.png)

**Comment by xibaibai9527** [comment]
抱歉，忘记发过这贴了，不太习惯使用github

代码块这边感觉bug挺多的，我主贴说的行错位，经过排查后发现是外观-代码块主题这边的问题，选择ant-design会超出。
80行代码就出界了4行
![截图23](https://user-images.githubusercontent.com/19858971/137599507-9ca364ad-25df-4903-a1f4-cf0a8f2c69ad.jpg)
这个问题在我换成vs主题就好了

问题2是效率问题，上面的80多行代码，已经非常卡了，输入延迟肉眼可见

问题3是高亮问题，习惯了vs和sublime的花花绿绿，思源这边实在太“素”了，我现在看代码是从思源暂时复制到vs里看
![截图24](https://user-images.githubusercontent.com/19858971/137599582-0f9a9375-4f2e-4055-bd31-1daa4d20908a.jpg)

**Comment by 88250** [comment]
@xibaibai9527 代码估计还是先在 IDE 里面写好一次性粘贴吧，性能问题请关注 #3138
