### ISSUE TITLE
请问Dockerfile在哪里可以看到？

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#2977]
### In what scenarios do you need this function?

我在容器的启动日志里看到无法识别语言为中文

![image](https://user-images.githubusercontent.com/10370433/134801896-ff5075e3-0d80-4cc7-b418-1e03b1e99c1e.png)

### Describe the optimal solution

能否暴露一些环境变量设置？能否把Dockerfile开源出来？关注你们很久了

**Comment by 88250** [comment]
暂时还不方便开源，语言探测失败的话可以在设置 - 外观中手动切换。
