### ISSUE TITLE
建议内置一个收集上报错误日志的程序

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#2979]
### Describe the candidate solution

在日常使用中，有时候会莫名其妙内核崩溃退出，或者网页端的一些JS问题，建议你们把这些错误日志收集并上报，这样你们可以主动发现问题并改进它。希望这款笔记越来越强大，非常喜欢 本地离线+云同步模式 的笔记软件。

**Comment by 88250** [comment]
这个之前考虑过，但是我们觉得还是用户自己上传比较好。

https://b3log.org/siyuan/privacy.html
