### ISSUE TITLE
查询嵌入块添加面包屑

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#2985]
### In what scenarios do you need this function?

1.1.83版本之前，思源的嵌入块都是能显示面包屑的，1.2.0之后嵌入块的面包屑被砍，
个人认为面包屑还是有存在的必要的，例如
- 查询多个块时，可以一眼区别不同块的路径
- 嵌入单个块，如页面或标题时，可以了解这个块的标题或路径
![image](https://user-images.githubusercontent.com/60436214/134843120-5a5b44f7-3d44-4609-9ee8-b780d4dee5f9.png)

综上，希望嵌入块面包屑可以回归

### Describe the optimal solution

一种方案是默认一直显示嵌入块的面包屑
另一种方案是当鼠标悬浮到嵌入块时，显示各结果的面包屑

**Comment by 88250** [comment]
就目前这段时间收集的反馈看，似乎很少有用户需要这个，我们先关闭，以后再考虑。

**Comment by fanglypro** [comment]
嵌入块属于正向链接范畴，需不需要面包屑可能有争议，roam research和logseq的嵌入块中都没有面包屑，但思源里面并没有真正的嵌入块概念。

而sql查询结果属于反向链接范畴，我认为是需要有面包屑的，面包屑包含了重要的上下文信息，在汇总与回忆过程中发挥了重要作用，像 roam research、logseq 的反链、query都是有面包屑的。

以及思源后续的编辑器式反链面板中我认为也需要有面包屑。

**Comment by winter60** [comment]
这个功能是指在嵌入块上直接显示面包屑吗？
我非常需要这个功能，通过嵌入块可以直接查看面包屑，这就知道当前内容属于哪个文档，而不是打开浮窗再查看。
嵌入块本身就能够显示全部内容，那么只有在需要修改的时候才需要点击嵌入块进入浮窗，这非常适合浏览多个文档内容而不分心。

如果怕有的用户觉得一直显示不太友好，那么可以做成一个开关，就像现在嵌入块已有的功能“隐藏标题下方的块”。

**Comment by 88250** [comment]
收到，我们再考虑看看。

**Comment by why8023** [comment]
这个功能还是有一定需求的,比如利用SQL汇总某一段时间创建的daily note, 没有面包屑, 需要用鼠标一个一个去查看属于哪一天, 不像面包屑那样一目了然.

**Comment by SuJun-Hub** [comment]
不错不错，这下嵌入块实现页面随机就可以看到标题了

**Comment by hscui** [comment]
这个功能对于集聚了很多项的人来说太过花哨了，每个项目都要有两行，而且把并列排布的嵌入块的格式搞坏了。
