### ISSUE TITLE
Mac客户端关闭的问题

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#2986]
### In what scenarios do you need this function?

我在 设置-外观 里，打开了关闭按钮设置，关闭了退出界面时关闭内核。

![image](https://user-images.githubusercontent.com/10370433/134842165-eec31867-a0a9-48fa-9106-c0043690454c.png)

然后我点关闭时，会有一个最小化的动效，然后才把界面关闭。这个效果不对呀，我预期的应该是点关闭时，直接就关了，没有一个最小化的过程，而且进程不退出。你看微信、QQ、钉钉这类APP，关闭的时候，就是这种效果。

**Comment by 88250** [comment]
感谢反馈，这个问题会在 https://github.com/siyuan-note/siyuan/issues/2575 中一并改进。
