### ISSUE TITLE
思源笔记打开时，默认展开笔记本

### ISSUE THREAD

**Issue by ranbest** [siyuan-note/siyuan#2987]
能不能增加思源笔记打开时，默认展开笔记本功能。

**Comment by 88250** [comment]
可以试下 `设置 - 文档树 - 始终定位打开的文件`。

**Comment by ranbest** [comment]
> 可以试下 `设置 - 文档树 - 始终定位打开的文件`。

这个我知道。当我关闭了所有打开文件，再打开应用时，左侧笔记本是关闭的。是否可以考虑，打开时默认展开或者展开第一级目录

**Comment by 88250** [comment]
哦，这个暂时做不到，之前考虑过，抱歉了。
