### ISSUE TITLE
关闭windows客户端一段时间后，仍然有驻留内存的进程

### ISSUE THREAD

**Issue by kaiaiz** [siyuan-note/siyuan#2988]
### Describe the problem

关闭windows客户端一段时间后，仍然有驻留内存的进程SiYuan Kernel，并且占用不低的cpu。也无法直接结束进程。
### Screenshot or screen recording presentation
![333](https://user-images.githubusercontent.com/18533952/134854959-3f0a8b84-0860-4580-9b09-c60389493adf.png)

### Version environment

* Version: 1.3.5
* Operating system: win7
* Browser (if used):

**Comment by 88250** [comment]
请升级到最新版以后再看看，我先关闭了。
