### ISSUE TITLE
自顶向下法新建文档后光标定位问题

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#299]
![2020 10 21](https://user-images.githubusercontent.com/26304888/96677781-e0ad1000-13a2-11eb-97d4-b6c3141f163f.gif)
新建文档后文字后面的光标丢失了, 无法继续打字输入

**Comment by 88250** [comment]
似乎和 https://github.com/siyuan-note/siyuan/issues/228 有关 @Vanessa219

**Comment by nanmao** [comment]
> 似乎和 #228 有关 @Vanessa219

这次是用英文输入法, 没有符号自动补全的测试, 依然会光标丢失, 没法继续输入.
![2020 10 212](https://user-images.githubusercontent.com/26304888/96679271-eb1cd900-13a5-11eb-9a5d-bbe9e76155d5.gif)
