### ISSUE TITLE
请问有没有计划集成rclone？

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#2990]

**Comment by 88250** [comment]
rclone 的双向同步还没有正式发布，等发布稳定以后会考虑。

**Comment by jearton** [comment]
@88250 大佬，我请教一下，rclone我去看了，不是有copy和sync命令嘛，copy可以下载，sync可以上传。双向同步是啥概念？

**Comment by 88250** [comment]
需要一个机制自动判断是上传还是下载。
