### ISSUE TITLE
请问能否支持以下这些语法？

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#2992]
### Describe the optimal solution

我觉得这些语法非常实用，能否考虑支持一下：

1. Admonitions：https://squidfunk.github.io/mkdocs-material/reference/admonitions/
2. Content tabs：https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
3. Sortable tables：https://squidfunk.github.io/mkdocs-material/reference/data-tables/#sortable-tables
4. Footnotes：https://squidfunk.github.io/mkdocs-material/reference/footnotes/
5. icons：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
6. Collapsible blocks：https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks

**Comment by 88250** [comment]
Markdown 扩展语法不考虑引入了。

**Comment by jearton** [comment]
@88250 那能否以插件扩展的方式，允许社区同学自己开发集成进去？

**Comment by 88250** [comment]
可以考虑用挂件进行扩展。
