### ISSUE TITLE
希望嵌入的本地视频可以像 PDF 那样增加参数来实现指定片段播放

### ISSUE THREAD

**Issue by VSpade7** [siyuan-note/siyuan#2996]
在本地视频引用链接后跟上开始时间与结束时间，来实现类似视频划重点的功能

**Comment by VSpade7** [comment]
视频划重点可以做成类似 PDF 的框选，自己在进度条上为开始结束时间上打两个点，然后导出为一个跳转播放链接

**Comment by 88250** [comment]
这个可能需要定制播放器，暂时没有精力开发。

**Comment by 88250** [comment]
我先关闭了，以后如果要做会重开。
