### ISSUE TITLE
block embed 视频置入方式还有更好的方式吗？

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#30]
![image](https://user-images.githubusercontent.com/29135984/94260804-62a44780-ff63-11ea-81f6-e4136e93cd31.png)
block embed 视频置入方式还有更好的方式吗？（视频上方的代码不能自动隐藏）似乎帮助里提供的只能显示链接而不能显示视频。。
![image](https://user-images.githubusercontent.com/29135984/94261042-caf32900-ff63-11ea-9961-d91e6b2f90fb.png)

**Comment by 88250** [comment]
HTML 块上个版本做过调整，固定显示了，因为担心有的情况下会隐藏 HTML 代码不易被发现，类似的还有内联 HTML。

**Comment by zhl111** [comment]
我把代码删除了，视频还在，有意思。embed这块我不太懂，不知道其他诸如pdf\Excel之类的是否可以内置

**Comment by 88250** [comment]
其他格式暂时不行，不过理论上只要浏览器内能做展现的应该都能做。

**Comment by zhl111** [comment]
期待。我在谷歌和百度上各自搜了一下思源笔记，几乎没有人写教程和推荐笔记，也很少人知道，我也是在ob群里了解到的。这状态和其他有所不同，而且交流在qq群，似乎偏向小众😄。discord.com里交流不也挺好？

**Comment by 88250** [comment]
我们其实是有一个专门的社区的 https://ld246.com/tag/siyuan 只是可能更小众一些……
