### ISSUE TITLE
[[ 自动补全

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#300]
这是在roam research的演示, 我在"test"文档下,输入`[[]]`或者`[[`后继续输入文字, 默认新建了"特殊"文档.然后按→右箭头两次,能继续输入文字.
![2020 10 211](https://user-images.githubusercontent.com/26304888/96678105-9710f500-13a3-11eb-80b6-56db92fc9bd4.gif)
这是思源的演示. 我输入`[[`后继续输入文字, 一是输入法符号自动补全多出`]]`，二是光标丢失没法继续输入。
![2020 10 21](https://user-images.githubusercontent.com/26304888/96678395-2d451b00-13a4-11eb-8f76-a28a3a5b6629.gif)
我想要的是，按`[[`后思源自动帮我补全符号，这样就不会触发输入法的自动补全功能。按`[[`后继续输入文字，再按enter键新建文档。新建文档后光标不丢失，能继续打字。

**Comment by 88250** [comment]
类似`[[占位]]`的用法还有待考虑，是按目前的思路直接新建文档好还是以后用 Ctrl 点击创建还没想好，我偏向沿用现有思路，然后按照你说的来优化平衡体验，即创建文档以后光标能够回到正常位置继续输入 #299 。

**Comment by nanmao** [comment]
> 类似`[[占位]]`的用法还有待考虑，是按目前的思路直接新建文档好还是以后用 Ctrl 点击创建还没想好，我偏向沿用现有思路，然后按照你说的来优化平衡体验，即创建文档以后光标能够回到正常位置继续输入 #299 。

能不能像rr这样, 按`[[`就自动帮你补全, 这样输入法自动补全就不会触发了.  然后我可以按→右箭头两次, 能继续输入文字. 而被`[[`和`]]`包裹的文字, 能默认新建文档.

**Comment by 88250** [comment]
这个思路不错 @Vanessa219

**Comment by 88250** [comment]
* 光标丢失和补全的问题我们在 https://github.com/siyuan-note/siyuan/issues/320 中继续跟进
* 占位用法提议 https://github.com/siyuan-note/siyuan/issues/310

当前 issue 我就关闭了，谢谢。
