### ISSUE TITLE
云端同步能否增加修改文件（笔记）列表和状态？

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3004]
现在同步只能看到统计的一些信息，对于一些具体的文件，优先级或者重要性很高，那么就会关注这些文件（笔记）是否有同步上去：

![image](https://user-images.githubusercontent.com/33319484/135189874-4f533048-05c2-42f1-ae08-cf9a5e4a2d57.png)

**Comment by 88250** [comment]
这个统计信息是很准确的，如果同步没有报错且时间正确的话应该就不会有问题了。
