### ISSUE TITLE
Global breadcrumbs

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3007]
https://ld246.com/article/1632885400987

- [ ] 支持鼠标操作

先完成块级 #2613

**Comment by TCOTC** [comment]
用 (伪)文档面包屑 syplugin-fakeDocBreadcrumb 插件可以基本实现了，只是还有点兼容问题，所以希望思源本体支持。感觉能直接抄代码了：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/392332c3-f1a7-415b-a4f9-5ef87a4931c5)

![image](https://github.com/siyuan-note/siyuan/assets/78434827/83040685-06de-4371-b446-64cda6c5eac5)

**Comment by 88250** [comment]
已经有插件支持，暂时不考虑了。

**Comment by mozhuk** [comment]
插件维护期了，比如这次3.7更新，插件不维护，样式对不齐，希望官方支持。

<img width="634" height="81" alt="Image" src="https://github.com/user-attachments/assets/a025303b-9495-4472-b742-920890c67486" />
