### ISSUE TITLE
Code is inline by mistake when copy-paste

### ISSUE THREAD

**Issue by Ovilia** [siyuan-note/siyuan#3008]
### Describe the problem

Copy and paste multiple paragraphs which contains a code block will make the code inline. 

Example: [link](https://v3.vuejs.org/api/refs-api.html#customref).

1. Copy this part

![image](https://user-images.githubusercontent.com/779050/135198322-17da09cc-6630-490d-a337-887ca55ac0a9.png)

2. Paste in SiYuan

![image](https://user-images.githubusercontent.com/779050/135200367-5ff41520-5505-4ae2-8c23-769c8eac42de.png)

### Expected result

Code should be in multiple lines (which is the same as the current behavior of copying the code part only).

![image](https://user-images.githubusercontent.com/779050/135200508-7eafc7c1-b9ed-4846-a309-f19e0223e910.png)

### Version environment

* Version: 1.3.5
* Operating system: Mac 
* Browser (if used): Chrome 93

**Comment by 88250** [comment]
感谢反馈，在 v1.3.8 修复。
