### ISSUE TITLE
TOOD 列表拖动，子 todo 没有跟随移动

### ISSUE THREAD

**Issue by crazyhl** [siyuan-note/siyuan#3009]
### Describe the problem

我的一个 TODO 包含了几个子TODO，当我拖动父TODO 的时候里面的子项并没有跟随移动，而且拖动的TODO变成了普通文本
我的创建子 TODO 方式是，按下回车 tab 创建的 子 TODO

### Expected result
希望拖动父 todo 的时候里面的子项可以跟随移动

### Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/5474833/135200361-9b6d9d54-5294-464b-98b8-1005c0260b0f.png)

![image](https://user-images.githubusercontent.com/5474833/135200714-098118fa-fad8-463f-91fe-929fd0a4e196.png)

### Version environment

* Version:  1.3.7
* Operating system:  macos 11.6

**Comment by 88250** [comment]
你好，拖拽时块标用的是哪一个？

![image](https://user-images.githubusercontent.com/873584/135201107-48335706-711b-49d5-80df-163eca3fb22d.png)

**Comment by crazyhl** [comment]
我知道了，我是移动到文本上，标快变成了这个
![image](https://user-images.githubusercontent.com/5474833/135202330-7182cbcb-8f3a-4c24-913a-35bed6086aca.png)
我应该用前面那个标快
![image](https://user-images.githubusercontent.com/5474833/135202393-d006e61a-d58d-4c88-b596-10239a8f0228.png)
不过你最前面的那个标识我这边没有

**Comment by crazyhl** [comment]
> 鼠标悬浮过去应该就有了，如果没有的话试试默认主题。

好的，thx
