### ISSUE TITLE
bug - letters covering letters

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#3015]
When I'm writing long texts, the letters are on top of the ones below.
Letters in "Heading 4" and outliner notes.

![image](https://user-images.githubusercontent.com/90691302/135259179-00b7a599-a03d-4eae-a44a-36fc7a32d52b.png)

### Version environment

* Version: 1.3.7
* Operating system:  Windows
* Browser (if used):

**Comment by 88250** [comment]
Thank you for your feedback and fix it in https://github.com/siyuan-note/siyuan/issues/3003.
