### ISSUE TITLE
选中文字后能按快捷键新建关联文档

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#302]
# 需求
思源的块引用可以帮我梳理关系和结构化学习材料，学习过程在其他软件进行，梳理在思源，所以块引用越是方便越好。
需求是：选中文字后能按快捷键新建关联文档，或者凡是被`[[`和`]]`包裹的文字都能默认新建与本文档双链的新文档。
# 使用场景
![2020 10 21](https://user-images.githubusercontent.com/26304888/96714520-d9065f00-13d4-11eb-9e05-b53f3853b5a4.gif)
实例：我先学计算机网络分类，这是大框架。然后对计算机网络分类下的＂交换技术分类＂进行学习，这时我**选中文字后按快捷键快速新建关联文档**就可以了；我如果对＂交换技术分类＂下的＂报文交换＂进行学习，这时我**选中文字后按快捷键快速新建关联文档**就可以了，同理可以快速的一直往下拆，并且文档名清晰无需额外命名，后期学物理层的时候又可以快速拉出来双链对三种交换技术进行研究。
# 不知道取啥标题
这个需求和 #296 与 #298 不同，我想要的是一键新建文档后默认与本文档进行双链， #296 的长文拆解 和 #298 的粘贴新建文档默认不进行双链更合适。
另外这个功能能提供快捷键好很多很多，配合quicker的话可玩性高，用右键然后跳选项选择慢很多而且麻烦（但是对新用户更友好）。
我希望能提供选中文字后按快捷键新建关联文档的功能( •̀ ω •́ )✧。

**Comment by 88250** [comment]
老铁咋关了呢？

**Comment by nanmao** [comment]
> 老铁咋关了呢？

在思源的块引用过程中可以帮助我梳理关系，边引用边理清思路。而思源另一个作用是帮助我结构化材料，我这样做拆得太细了，不利于整体视图。我的学习材料逻辑链很清晰，我把它们放一起，不拆解的，更好。有需要的时候直接引用块。

或许这个需求对学习材料无序的，需要二次整理的有用，如果你们觉得可以做的话，继续打开就好了。

**Comment by 88250** [comment]
哦哦，那暂时还是关闭着吧……等以后我们想起来再重头审视，或者有需要的时候 reopen，谢谢谢谢。
