### ISSUE TITLE
不同步符号链接

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#3020]
### Describe the problem

使用mklink或ln，对同步屏蔽列表中的文件夹建立软连接后，软件无法进行同步

### Expected result

判断文件夹是否为软连接，如果是则视作正常文件夹进行处理

### Screenshot or screen recording presentation

syncignore文件：
```
assets/**/*
```

Win端使用`mklink /J`的效果
![image](https://user-images.githubusercontent.com/19968935/135390009-20613f26-93a5-4346-ad60-710eef3150b8.png)
同步的报错：
![image](https://user-images.githubusercontent.com/19968935/135389672-333aab22-ddb2-41d9-b826-ffd1a14a897e.png)

Mac端使用ln -s建立的效果
![image](https://user-images.githubusercontent.com/19968935/135390060-06a124cc-d103-4231-ae81-89597776558f.png)
同步时的报错：
![image](https://user-images.githubusercontent.com/19968935/135389853-65dfd4b4-104a-4fa0-b42b-823c185ee513.png)

### Version environment

* Version: 1.3.8
* Operating system: Win10 + Mac

### Log File

E 2021/09/30 13:56:10 sync.go:506: read file [D:\AppData\SiYuanNote\data\assets] failed: read D:\AppData\SiYuanNote\data\assets: The handle is invalid.
E 2021/09/30 13:56:10 sync.go:338: encrypt data dir failed: read D:\AppData\SiYuanNote\data\assets: The handle is invalid.

### PS

1.3.7版本中，只要屏蔽列表设置为
```
assets
```
表现正常，图片附件显示与添加没有任何问题，除了有一次遇到会删除该软连接
https://github.com/siyuan-note/siyuan/issues/2998

**Comment by 88250** [comment]
目前的同步是 follow symlink 的，也就是说同步后云端是保存了符号链接实际指向的真实文件。

估计只能做成同步时不跟随符号链接，而是同步符号链接本身这个文件。因为如果一旦跟随，云端存了真实文件，那么另一个设备上就只能下载到真实文件了，会出现删除已有链接的情况。

**Comment by HowcanoeWang** [comment]
> 目前的同步是 follow symlink 的，也就是说同步后云端是保存了符号链接实际指向的真实文件。
> 
> 估计只能做成同步时不跟随符号链接，而是同步符号链接本身这个文件。因为如果一旦跟随，云端存了真实文件，那么另一个设备上就只能下载到真实文件了，会出现删除已有符号链接的情况。

可能要分成两种情况，一种是文件符号链接，一种是文件夹符号链接；
而且win系统的符号链接和mac系统的符号链接，似乎也是不同的两种文件类型；

我的应用场景是，只要涉及到符号链接，那这个路径一定会存在于syncignore中；或许可以用这个思路，一旦检测到符号链接，自动添加到syncignore文件，忽略同步？

**Comment by 88250** [comment]
我也倾向于直接忽略符号链接。
