### ISSUE TITLE
自动转换箭头等特殊符号

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#3021]
### In what scenarios do you need this function?

设置中提供一个选项开关，当输入 -》 -> >= +- 等符号后自动转换为 → ≥ ± 一体符号，避免输入过程中去输入法特殊字符里面寻找相应的符号中断思路

**Comment by 88250** [comment]
输入侧的处理我们暂时不会考虑，这个主要靠输入法设置来完成，我关闭了，谢谢。
