### ISSUE TITLE
代码块 下方可触发范围过大， 导致代码块之后无法继续写字，鼠标无法选择到下方输入

### ISSUE THREAD

**Issue by mtianyan** [siyuan-note/siyuan#303]
![image](https://user-images.githubusercontent.com/15145231/96719756-6ac59a80-13dc-11eb-93a8-1a7c6cdf4ba9.png)

红色位置点击仍能触发上方代码块展开

**Comment by lss6378** [comment]
+1，也遇到这个问题
建议参考Typora这种方式：


## 思源代码块
![思源代码块渲染](https://user-images.githubusercontent.com/15924513/96723306-fccfa200-13e0-11eb-8503-ee1748733a52.gif)

## Typora代码块
![Typora代码块渲染](https://user-images.githubusercontent.com/15924513/96723384-14a72600-13e1-11eb-90c4-2c5c67260bd7.gif)

**Comment by 88250** [comment]
用这个先顶顶

![image](https://user-images.githubusercontent.com/873584/96731049-6bb0f900-13e9-11eb-88b7-c2926fe797a4.png)

或者在设置 - 编辑器中关闭代码块预览。

以后编辑器可能会做原地渲染代码块，但是目前暂时没有精力，见谅。

**Comment by Vanessa219** [comment]
@mtianyan 点击红色空白区域会新建块的，如果不能请描述一下详细步骤

光标在代码块末尾按下/右键可以在下方新建块。
