### ISSUE TITLE
多选块外观设置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3037]
* https://ld246.com/article/1632969520294
* https://ld246.com/article/1636631038304

**Comment by Solomon-king1** [comment]
咋关闭了啊，我用1.6.2还是没法实现多选块文字的加粗、下划线等操作啊，只有个改变颜色啊

**Comment by 88250** [comment]
@Solomon-king1 这个 issue 支持的就是外观设置……
