### ISSUE TITLE
win10下安装后无法打开

### ISSUE THREAD

**Issue by KongMingxi** [siyuan-note/siyuan#304]
![图片](https://user-images.githubusercontent.com/31657475/96818135-b759a780-13d5-11eb-9e58-cf178b13d09e.png)

**Comment by 88250** [comment]
是最新版吗？

**Comment by 88250** [comment]
如果之前安装过 v0.3.0 前的版本，请手动删除用户家目录下 `./siyuan` 文件夹后再重启。我先关闭了，如果还有问题请继续跟帖，谢谢。

**Comment by KongMingxi** [comment]
已解决，谢谢
