### ISSUE TITLE
增加类似 Typora 的专注模式

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#306]
专注模式的应用场景就是准备进行一个长时间的连续记录时，这个时候我其实不太需要其他东西去分散注意力，就可以向隐藏其他的按钮，等到记录完成以后再退出专注模式进行笔记的漫游或者其他操作，这样来保证整个记录过程的流畅性。
 我现在就是先在typora中进行连续的记录，然后再拷贝进思源当中然后建立链接什么的，但是还是感觉这种操作有些割裂，希望能够引进这种专注模式。

**Comment by 88250** [comment]
v1.2.0 中支持块级缩放聚焦，结合全屏应该能提升专注编辑体验，我关闭了，谢谢反馈。
