### ISSUE TITLE
显式效果更好的 PDF 标注

### ISSUE THREAD

**Issue by Wonderdch** [siyuan-note/siyuan#3062]
### In what scenarios do you need this function?

PDF 标注

### Describe the candidate solution

1. 希望划词标注时，要么每行下面都能看到 白色，要么直接就没有白色
![image](https://user-images.githubusercontent.com/12708888/135966608-25245904-7c0e-40c8-b303-d94a8148b1cd.png)

2. 希望深色模式时，被标注的字还能显式白色（或其他颜色），感觉紫色过于耀眼了
![image](https://user-images.githubusercontent.com/12708888/135966748-f946b382-ed6f-4b55-b837-7ba5bc22776d.png)

### Other information

PDF 已附上：
[PointsofInterestrecommendationsMethods,evaluation,andfuture directions.pdf](https://github.com/siyuan-note/siyuan/files/7283046/PointsofInterestrecommendationsMethods.evaluation.andfuture.directions.pdf)

**Comment by 88250** [comment]
你好，目前的开发版效果如下：

![image](https://user-images.githubusercontent.com/873584/136036302-1d97563e-e792-4e3b-932d-c9a01c929e04.png)


![image](https://user-images.githubusercontent.com/873584/136036248-b8bc4d90-c1e5-4aa5-86fe-846b91b47514.png)


请等 v1.4.0 发布以后再试试，如果还有问题，请跟帖回复，我先关闭了，谢谢。
