### ISSUE TITLE
窗口拖动大小以后再重启有概率出现布局出错的问题

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#308]

**Comment by Vanessa219** [comment]
0.3.6 以后版本还会重现么？可以具体给一下重现步骤么？

**Comment by Asasahn** [comment]
还是会重现&nbsp;具体操作是win10有个插件powertoys其中一个功能是给电脑划定好选区然后把软件拖到预定选区就会显示预定大小的窗口
就是类似于win+左右键的分屏&nbsp;
然后在这个分屏的状态下关闭思源再打开就有概率出现




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "V"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 中午12:05
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;; 
抄送: "单志玮"<1026411669@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [siyuan-note/siyuan] 窗口拖动大小以后再重启有概率出现布局出错的问题 (#308)





 
0.3.6 以后版本还会重现么？可以具体给一下重现步骤么？

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/263 是和第一条里面的图一样的现象么？

**Comment by Asasahn** [comment]
是的发自我的华为手机-------- 原始邮件 --------发件人： V <notifications@github.com>日期： 2020年10月27日周二 12:32收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asasahn <1026411669@qq.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 窗口拖动大小以后再重启有概率出现布局出错的问题 (#308)

#263 是和第一条里面的图一样的现象么？

**Comment by Vanessa219** [comment]
还是希望能详细介绍一下具体的必现步骤，如果最新版还出现的话，请再次打开该 issue

**Comment by Vanessa219** [comment]
淳帅二代找到了重现步骤，放入 https://github.com/siyuan-note/siyuan/issues/633 进行解决
