### ISSUE TITLE
列表编辑解析问题

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#309]

**Comment by 88250** [comment]
麻烦录屏，谢谢。

**Comment by Asasahn** [comment]
我看看怎么录屏啊 研究一下






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2020年10月22日(星期四) 晚上10:08
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;; 
抄送: "单志玮"<1026411669@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [siyuan-note/siyuan] 思源无序列表第四行和第五行中间会自动出现一行空格 (#309)





 
麻烦录屏，谢谢。

**Comment by Asasahn** [comment]
拿手机拍的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月22日(星期四) 晚上10:08
收件人:&nbsp;"siyuan-note/siyuan"<siyuan@noreply.github.com&gt;;
抄送:&nbsp;"单志玮"<1026411669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 思源无序列表第四行和第五行中间会自动出现一行空格 (#309)





 
麻烦录屏，谢谢。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

VID_20201022_221141.mp4 (68.20M, 2020年11月21日 22:14 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=78666665ebf88e9ea1aa4b581535004a0657035404510250195f04550618065257574b5d0450004800525f555604565006045356332232337d223957030702540454543a010703540057480843013258&code=4ffe352e

**Comment by 88250** [comment]
这问题后面修复，谢谢反馈。

**Comment by Asasahn** [comment]
好的

**Comment by 88250** [comment]
这个问题会在 v0.3.4 中修复，请在该版本发布后帮忙进行测试验证，谢谢。
