### ISSUE TITLE
1.4.0版本，网络代理的说明文字是不是写错了？

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#3098]
### Describe the problem

![image](https://user-images.githubusercontent.com/10370433/136641566-88a026a5-6969-43c3-a8a0-845c8eda021d.png)

怎么和网络伺服的描述一样的？

### Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
嗯，写错了，在 https://github.com/siyuan-note/siyuan/issues/3092 中修复。
