### ISSUE TITLE
1.4.0版本，MAC客户端无法强制退出

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#3099]
### Describe the problem

![image](https://user-images.githubusercontent.com/10370433/136641665-fff29f73-c56d-4064-88dc-86f21797e4fd.png)

如图，点退出没反应，点这个退出就是强制退出的意思。我的配置是这样的：

![image](https://user-images.githubusercontent.com/10370433/136641719-4dea66be-89c1-42b6-9a2d-6dc9d708e37a.png)

### Expected result

我想要的效果是：点关闭按钮，是不退出的状态，但是右击点退出，应该要能真正退出才对。你可以试试其他APP，比如钉钉、微信之类的，都是这种效果。

为什么要真正退出？因为我在升级的时候，必须得先完全退出才能升级。

### Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3086
