### ISSUE TITLE
关于块引用符号问题

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#31]
内容块嵌入符号(( 似乎和其他的笔记皆不同，不知道是有特殊的原因还是什么，这在其他笔记迁移到思源笔记的过程中，所有的原先的引用链接全部不能启用，造成很大的迁移成本。不知有何种方式解决？

而且((输入会麻烦很多，一是要按住shift再加9键。二是很多符号输入设置是自动补全的，这就增加了更多的步骤，又不能连按否则就变成了(9).

如果和其他笔记通用[[]]，会有什么影响吗？谢谢

**Comment by 88250** [comment]
* 打开已有的文件夹会进行自动导入，将 `[[wikilink]]` 语法自动转换为 `((id))`
* 使用 `((id))` 语法主要是因为思源是块级引用，需要和文档/标题级引用作区分，也参考了 Roam Research 的块引语法
* 已经做了一些输入触发方面的优化，比如 `[[` 同样是可以触发块引自动完成，包括中文语境优化，比如使用 `【【` 和 `（（` 也能触发块引
* 如果底层使用 `[[id]]` 存储的话，其实和其他系统也是不兼容的，因为 id 不是 wikilink
