### ISSUE TITLE
PageUP/PageDown 禁止光标移动

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#3100]

**Comment by 88250** [comment]
我这里没试出来，麻烦录屏演示一下，谢谢。

**Comment by Kitsuta-le** [comment]
Uploading QQ录屏20211009111629.mp4…

**Comment by Kitsuta-le** [comment]
https://user-images.githubusercontent.com/88605687/136642362-2b660bfb-b1b5-4a0f-9a47-d4b2d9d4a6c8.mp4

**Comment by Vanessa219** [comment]
在第一次输入 asdfasdf 后看上去是正常的，后面进行了什么操作导致滚动了一下？

**Comment by Kitsuta-le** [comment]
https://user-images.githubusercontent.com/88605687/136643512-ddc4cd64-51ab-474b-ac9d-6d1966029ba4.mp4

**Comment by 88250** [comment]
@Kitsuta-le 这个暂时就先这样吧，参考 Word 应该没错。
