### ISSUE TITLE
建议assets目录放到每个笔记本里

### ISSUE THREAD

**Issue by jearton** [siyuan-note/siyuan#3101]
### In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/10370433/136643217-80cd838b-c197-4d3a-8014-f9dc44dfa6dd.png)

比如我有3个笔记本，然后我要对其中一个笔记本不同步到云端，那么这个笔记本里引用的所有assets也不应该同步到云端。这个要怎么做到呢？syncignore咋写？

如果每个笔记本的assets能够隔离，各存各的，就没有这个问题了。

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/136643349-274937be-766d-4bac-bf24-8a4b52dcc145.png)

**Comment by jearton** [comment]
明白了，我的问题，我应该仔细看一遍使用教程 😄

**Comment by jearton** [comment]
@88250 是否可以考虑把这个能力集成到笔记本的设置弹窗里？可视化操作

![image](https://user-images.githubusercontent.com/10370433/136643485-1d4062fb-b554-40f8-9acf-3d920e274813.png)

**Comment by 88250** [comment]
@jearton 这个功能暂时作为手动选项，我们建议还是集中存放。
