### ISSUE TITLE
设置搜索失效

### ISSUE THREAD

**Issue by yalinlei** [siyuan-note/siyuan#3102]
设置里面的搜索框无法搜索

Windows10 思源笔记1.4.0

![设置里面的搜索框无法搜索](https://user-images.githubusercontent.com/75535154/136645501-30c09449-3274-4ca9-9094-2cba61f122f1.gif)

**Comment by Zuoqiu-Yingyi** [comment]
设置搜索又坏了😂
  * ver [1.5.3]
  * arch [amd64]
  * runtime mode [prod]
  * read only [false]
  * container [std]
  * database [ver=20211022]
  * rsync [version 3.2.4dev  protocol version 31]
  * pandoc [pandoc.exe 2.13]

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 感谢反馈，下个版本修复。
