### ISSUE TITLE
字体加颜色并添加块引用后无法插入字符

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3103]
## 环境

版本1.4.0，win10

## GIF
![test](https://user-images.githubusercontent.com/33319484/136652323-a77a76fd-b8cf-4775-9e45-2e7f05ae6cbd.gif)

## 出问题文件拷贝

（压缩包内部仅包含GIF演示所用到的sy文件）

[20211009170818-2n4ab0w.zip](https://github.com/siyuan-note/siyuan/files/7315305/20211009170818-2n4ab0w.zip)

**Comment by JokeenZhang** [comment]
1.7.5已经不能在为文字设置外观后，又通过`((`重新编辑部分文字的引用，这种bug已经不会出现了

**Comment by 88250** [comment]
@JokeenZhang 那就先这样，等后面支持排版元素嵌套再看看。
