### ISSUE TITLE
mac版客户端卡顿

### ISSUE THREAD

**Issue by zero-hugo** [siyuan-note/siyuan#3105]
### Describe the problem
mac客户端操作体验一般，感觉有卡顿，像是文档的上下滚动，或者文档之间的切换，还有设置里各个选项直接的切换，都有一种微妙的卡顿感，不流畅。希望改进。

### Version environment

* Version: 1.4
* Operating system: macos11.5.2
* Browser (if used): firefox93

**Comment by 88250** [comment]
你好，目前我们暂时没有收到类似反馈，如果可以的话，请帮忙继续留意观察，比如系统资源使用情况。

Issue 我先关闭了，谢谢。
