### ISSUE TITLE
内容块 URL

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#312]
通过点击该URL访问**思源笔记桌面端**的对应内容块，现在迫切需要该功能，以此为锚点实现和其他软件的对接。
e.g. 对PDF里的某句话添加该URL，可以一键跳转思源对应内容块笔记（目前是用时间戳配合quicker顶着，不过时间戳不美观）。
PS. 在思源笔记桌面端或者浏览器端使用都没关系，只要保证有完整的快速响应的编辑体验。

**Comment by 88250** [comment]
我们计划直接在浏览器上使用，但前提是必须启动内核。这部分架构已经在逐步调整，以后可能会彻底放弃 Electron 版本。

在浏览器上使用，内容块 URL 大致会是这样子的：`http://127.0.0.1:6806/blocks/{id}`。

**Comment by 88250** [comment]
v0.4.3 中实现了文档块 URL，其他块因为会清理 ID 的原因，URL 并不稳定，还有待考虑如何解决。
