### ISSUE TITLE
列表和标题折叠小三角

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#3125]
![image](https://user-images.githubusercontent.com/90691302/136782930-25036b75-69fd-4cdd-9fe9-da64e92f1d1d.png)

I use the program to set up a study structure. This makes it too easy for me to understand the content! For me to open a topic, I need to press "ALT" on the keyboard and click with the mouse, or press "Ctrl + down arrow".
My suggestion: Create a new button next to the central topic to just click and already open or close all the content within it. This would help too much in navigation. Below I put a very interesting image to help you understand.

Open:
![image](https://user-images.githubusercontent.com/90691302/136783060-f2c90b6b-b52c-40e1-864b-9637f6af5bab.png)

Close:
![image](https://user-images.githubusercontent.com/90691302/136783630-012c39fe-991c-4b71-ba8b-9070911700b9.png)

**Comment by 88250** [comment]
It's a good idea. We have had this idea before, but there is no time for improvement at the moment. Please keep this issue open and we will consider it later, thank you.

**Comment by taozina** [comment]
First, I'd like to thank you for the program's support! The frequency of updates, the speed of response on the forum is amazing. SiYuan has everything to win the global market in this field. But I would just like to reinforce the idea of bringing a new icon to expand and collapse the content of a note. It would make my student life so much easier! Pressing "alt" all the time to expand or collapse bothers me!

**Comment by Elliootalderson** [comment]
终于....

**Comment by taozina** [comment]
Great news! Thanks

**Comment by cesaryuan** [comment]
@Vanessa219 就不开新issue了，希望折叠的小三角更圆润一点🤣
