### ISSUE TITLE
减少列表竖线间距

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#3137]
![506111337d7957be5f8f75bf4422d56](https://user-images.githubusercontent.com/88605687/136954283-844ff13d-4a59-4d3b-8320-28cbc6a91e5a.jpg)
![4b5c3169aa85531ab8f7fd57bbcedaa](https://user-images.githubusercontent.com/88605687/136954323-755f58fd-8b20-48b7-9170-845375af806e.jpg)
)

**Comment by Kitsuta-le** [comment]
本来是写的安卓的。。。可是对比了一下电脑的其他大纲竖线好像也是比较宽的。。。尤其在分屏的时候会很挤
![image](https://user-images.githubusercontent.com/88605687/136956217-d81640b9-41c7-4cba-b49f-2e34e7fa486c.png)

**Comment by fanglypro** [comment]
> ![image](https://user-images.githubusercontent.com/88605687/136966252-c833a903-e262-4187-9400-5e2c85a79935.png) 我倒觉得现在的行间距更清晰，如果调整的话希望能给个选项

对了，你截图里的这个并不是默认间距，你这是Tsundoku-green主题吧，这个主题里面改过列表间距的，它的参数是：

```css
.protyle .li {
    margin: 0px 0px 0px 0px;
}
```

这个参数下是刚刚好使得多选块的阴影没有重合，刚好贴在一起。

你可以试试改成默认主题，感受下默认的列表行间距。

**Comment by AiteYx** [comment]
今天刚下载思源使用。现在仅仅“.protyle .li”不能修改间距了，默认主题下。
在 theme.css 最后添加这些可以仅仅改变列表之间的间距。
```
.li .p {
    padding: 0px 0px 0px 0px;
}
.protyle-wysiwyg .li {
    min-height: 26px !important;
}
.protyle-wysiwyg [data-node-id].li>[data-node-id] {
    margin-left: 26px !important;
}
.protyle-wysiwyg [data-node-id].li>.protyle-action {
    width: 26px !important;
}
.li > .protyle-action {
    height: 26px !important;
    line-height: 26px !important;
}
```
