### ISSUE TITLE
更换代码块编辑器

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#3141]
由于以下问题，需更换代码块编辑器。

代码块输入乱窜：

- [x]  https://ld246.com/article/1633937592296 已经在 https://github.com/siyuan-note/siyuan/issues/4190 中解决
- [x] https://ld246.com/article/1636702505887 已经在 https://github.com/siyuan-note/siyuan/issues/4190 中解决
- [x] https://ld246.com/article/1636823039131 已经在 https://github.com/siyuan-note/siyuan/issues/4190 中解决
- [ ] https://ld246.com/article/1650623107430 https://github.com/siyuan-note/siyuan/issues/4710

移动端：

- [x]  https://ld246.com/article/1637833297226 已经在 https://github.com/siyuan-note/siyuan/issues/4190 中解决

代码块性能问题：

- [ ]  https://ld246.com/article/1634032037894
- [ ]  https://ld246.com/article/1635236761283

渲染

- [x]  https://ld246.com/article/1640710884506 已经在 https://github.com/siyuan-note/siyuan/issues/4190 中解决

**Comment by Zuoqiu-Yingyi** [comment]
建议使用 Monaco Editor, 目前没有遇到单编辑器性能瓶颈, 如果支持焦点在编辑器中时编辑器快捷键覆盖笔记快捷键, 估计能争取到一批 vscode 粉丝😄
Monaco Editor 可能遇到的坑: `移动端支持`, `单文章多编辑器渲染性能`

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 估计会用 Code Mirror

**Comment by jearton** [comment]
更换之后会需要对历史数据进行迁移吗？

**Comment by Vanessa219** [comment]
部分在 https://github.com/siyuan-note/siyuan/issues/4190 中进行修复

**Comment by 88250** [comment]
先关闭了，目前基本已经可用。

**Comment by CnsMaple** [comment]
所以还打算更换到Code Mirror吗

**Comment by 88250** [comment]
@CnsMaple 不换了。

**Comment by 88250** [comment]
@CnsMaple 实现不了，建议在 IDE 里面排版完一次性粘贴到思源。

**Comment by Chenm4** [comment]
> @CnsMaple 实现不了，建议在 IDE 里面排版完一次性粘贴到思源。
我记得notion有一个功能是代码块可以自己调节颜色，例如一个代码块中某几行是最为关键的可以单独为这几行设置为全红色更加显眼，不知道notion是不是跟思源同一个机制，思源不知道能不能实现
