### ISSUE TITLE
预览窗口可否在软件窗口中居中显示？

### ISSUE THREAD

**Issue by pusuanzi1** [siyuan-note/siyuan#3145]
### Other information

预览窗口可否在软件窗口中居中显示？

![image](https://user-images.githubusercontent.com/90290182/137026718-a5b2fb2e-bbfe-4a36-8fa8-1e407429516a.png)

**Comment by 88250** [comment]
块引浮窗是尽量贴合块引元素的，所以无法居中显示，感谢反馈。
