### ISSUE TITLE
支持插入图片大小设置

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#315]
如行列宽，放大缩小等。

**Comment by Infinemen** [comment]
既然是笔记了，那知识密度（每页知识点数量）应该是远高于书本的。我也觉得markdown的默认排版方式是很不紧凑的，不单单是一整张图片占半页这一个最大痛点。所以就借楼，提下排版问题。我觉得笔记应该是紧凑而不简单的。

**Comment by yuhuai258852** [comment]
既然图片大小可以自定义，那么图片应该也支持点击放大浏览，类似知乎里，鼠标箭头放到图片上，会显示一个放大图标，点击后可放大图片进行查看

**Comment by 88250** [comment]
@yuhuai258852 图片点击查看大图在 https://github.com/siyuan-note/siyuan/issues/609 中进行实现，谢谢。

**Comment by derek778** [comment]
这个功能十分有必要，可以自定义图片的大小

**Comment by zinuo-H** [comment]
希望能像语雀或者Onenote一样，可以通过拖动图片的边框来调整图片大小

**Comment by zinuo-H** [comment]
> @zinuo-H 这个早已经支持了。

不行的，我是指直接拖动图片的边框来调整大小。我知道右键后选择宽度可以调整图片大小，但是这样没有直接拖拽方便，特别是截图很多的时候一个个这样调整比较麻烦。

ps: 希望作者再加上裁剪图片的功能就更好了！

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/200307276-6783600b-2c9c-48cd-ba14-872a4127d435.png)

**Comment by wclly264** [comment]
上面说的方法的确能调整图片大小，就是没有看到介绍时候不容易想到，这个标志像是上下滚动条，一般调整大小用图片底部角来调整。

**Comment by wclly264** [comment]
我也是查了挺久的调整图片大小的方法，才知道如何做了。
