### ISSUE TITLE
自定义排序时新建文档默认放置到底部

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3181]
https://ld246.com/article/1634549741869

**Comment by 88250** [comment]
v1.5.5 以后自定义排序模式下较新的文档会统一放置在顶部按时间排序，顶部和底部两个选择上我们还是决定放顶部了。

**Comment by DevYiTing** [comment]
1.“在上方新建文档”和“在下方新建文档”这两个选项能否增加快捷键操作？
2.“新建子文档”这个选项能否设计成按顺序向下创建？现在连续点击新建子文档的时候，都是新的子文档在旧的子文档上方，能否设计成在下方？或者增加一个用户选项，让用户选择在顶部还是底部。毕竟还是有一小部分用户是希望新建的子文档是按照从上到下的顺序排列。

**Comment by 88250** [comment]
1. 暂时不考虑了
2. 这个之前考虑过，主要问题是新建放在顶部容易看，当文档树太长时底部不一定能看到，并且思源对于这种情况有加载限制，超出限制以后就无法看到了（设置 - 文档树 - 最大列出数量），所以综合考虑放在顶部是最稳妥的

**Comment by 88250** [comment]
v3.4.0 支持 https://github.com/siyuan-note/siyuan/issues/16327
