### ISSUE TITLE
块引浮窗交互改进

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#3183]
https://ld246.com/article/1634564665780

- [x] ~~移除正文鼠标悬停展示悬浮窗~~
- [x] 统一书签、反链、关系图、正文中引用点击操作
  * click：新标签页打开内容，并跳转
  * ctrl+click：新标签页打开内容，但不跳转(注：关系图中为打开悬浮窗)
  * shift+click：右侧分屏打开内容
  * alt+click: 向下分屏打开文档
- [x] https://github.com/siyuan-note/siyuan/issues/3325
- [x] https://github.com/siyuan-note/siyuan/issues/3321

**Comment by Zuoqiu-Yingyi** [comment]
我也来许个愿
希望鼠标中键单机与 `ctrl+clink` 等效, 毕竟这也是浏览器在新标签页打开的语义❀
