### ISSUE TITLE
文件导入后似乎[[wikilink]] 语法没有自动转换为 ((id))

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#32]
![image](https://user-images.githubusercontent.com/29135984/94327975-80b08d00-ffe1-11ea-82c3-7fffe451506b.png)
谢谢您的耐心回复

**Comment by 88250** [comment]
可能是原文档的路径不是全路径导致。因为如果不是相对于当前文档的全路径的话文件系统上是定位不到目标文档的。可以帖一下文件夹树结构给我看下么？

**Comment by zhl111** [comment]
我是把ob里的部分文件夹导入思源的
![image](https://user-images.githubusercontent.com/29135984/94328102-7216a580-ffe2-11ea-83b4-87e63661418f.png)

**Comment by zhl111** [comment]
另外，内容引用的段落引用是需要手动删除多余内容吗？
![image](https://user-images.githubusercontent.com/29135984/94328206-1862ab00-ffe3-11ea-80e6-92f62530692a.png)
您的段落引用只有关系图三个字是手动删除的？
![image](https://user-images.githubusercontent.com/29135984/94328253-77282480-ffe3-11ea-8d42-80bdc767c66f.png)

**Comment by zhl111** [comment]
不同目录下的关键词不能自动关联？
![image](https://user-images.githubusercontent.com/29135984/94328324-21a04780-ffe4-11ea-8348-3766c82e6a4e.png)
在帮助文档里就可以
![image](https://user-images.githubusercontent.com/29135984/94328338-47c5e780-ffe4-11ea-8736-d5eae06f940e.png)

**Comment by 88250** [comment]
> 我是把ob里的部分文件夹导入思源的
> ![image](https://user-images.githubusercontent.com/29135984/94328102-7216a580-ffe2-11ea-83b4-87e63661418f.png)

ob 有个路径设置，如果用了短路径的话就导入不了了。

**Comment by 88250** [comment]
> 另外，内容引用的段落引用是需要手动删除多余内容吗？
> ![image](https://user-images.githubusercontent.com/29135984/94328206-1862ab00-ffe3-11ea-80e6-92f62530692a.png)
> 您的段落引用只有关系图三个字是手动删除的？
> ![image](https://user-images.githubusercontent.com/29135984/94328253-77282480-ffe3-11ea-8d42-80bdc767c66f.png)

内容块引用语法 `((id "text"))`，其中 `text` 这部分是自定义的锚文本，可以手动调整的，细节请看帮助文档里“链接内容块”一章。

**Comment by zhl111** [comment]
我是将ob目录拷贝入思源的，短路径只在图片或文件引用时使用的吧，这和[[xxx]]转化成（(id)）有影响？

**Comment by 88250** [comment]
> 不同目录下的关键词不能自动关联？不过这似乎不是什么问题
> ![image](https://user-images.githubusercontent.com/29135984/94328324-21a04780-ffe4-11ea-8348-3766c82e6a4e.png)
> 在帮助文档里就可以
> ![image](https://user-images.githubusercontent.com/29135984/94328338-47c5e780-ffe4-11ea-8736-d5eae06f940e.png)

复制粘贴的内容现在（v0.2.2）有个 bug 会导致块引失效，下个版本修复。

**Comment by 88250** [comment]
> 我是将ob目录拷贝入思源的，短路径只在图片或文件引用时使用的吧，这和[[xxx]]转化成（(id)）有影响？

有的，短路径格式是无法定位到文件系统的路径的，是 ob 私有的元数据。

**Comment by zhl111** [comment]
ob改成这种方式可以了
![image](https://user-images.githubusercontent.com/29135984/94329829-fe2fc980-fff0-11ea-9c43-156e54c7061f.png)
每段关系图的位置看起来是随机分布的，id自动生成的原因？如果按某种规律比如顺时针排列您觉得有必要么？

另外，如果把帮助文档排除在全局关系图之外的选项是否更好？

**Comment by 88250** [comment]
有过考虑，请看 https://github.com/siyuan-note/siyuan/issues/60

**Comment by 88250** [comment]
我关闭了，如还有问题请继续跟帖，谢谢。
