### ISSUE TITLE
QQ 拼音输入法自动补全时块引符号时末尾多出 `]]`

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#320]
<img width="118" alt="11" src="https://user-images.githubusercontent.com/26304888/97039383-eec78000-159e-11eb-9396-a45b11efa161.png">

英文输入法,没有符号自动补全,新建引用文档光标丢失.
中文输入法,符号自动补全,新建引用文档光标丢失且末尾多出`]]`
![2020 10 24](https://user-images.githubusercontent.com/26304888/97039886-be341600-159f-11eb-8997-449c96d2f07b.gif)

**Comment by 88250** [comment]
我这里重现不了……怎么办 😂

**Comment by nanmao** [comment]
> 我这里重现不了……怎么办 😂

![image](https://user-images.githubusercontent.com/26304888/97135586-a325f980-178b-11eb-91f3-50455d7da49c.png)
![image](https://user-images.githubusercontent.com/26304888/97135591-a5885380-178b-11eb-9a04-d9c35b651beb.png)
![image](https://user-images.githubusercontent.com/26304888/97135595-a7eaad80-178b-11eb-9665-aa289d373ce3.png)
![image](https://user-images.githubusercontent.com/26304888/97135597-aa4d0780-178b-11eb-83e6-b09915bb81c6.png)

**Comment by 88250** [comment]
@Vanessa219 我这里光标没丢失，但是有报错。

![issue](https://user-images.githubusercontent.com/873584/97156879-4d187c80-17b2-11eb-8b1b-bd5597c4bd5d.gif)

```
expandMarker.ts:45 Uncaught TypeError: Cannot read property 'element' of undefined
    at Object../src/vditor/ir/expandMarker.ts.exports.expandMarker (expandMarker.ts:45)
    at Editor.msgCallback (index.ts:109)
    at WebSocket.ws.onmessage (Model.ts:20)
```

**Comment by 88250** [comment]
@nanmao 你好，我们这里修复了一波，但是不确定是否能解决这个 issue，请在 v0.3.6 发布以后帮忙再测试看看，谢谢。

**Comment by nanmao** [comment]
> @nanmao 你好，我们这里修复了一波，但是不确定是否能解决这个 issue，请在 v0.3.6 发布以后帮忙再测试看看，谢谢。

0.3.6新建引用文档光标丢失 已修复.
中文输入法符号自动补全, 新建引用文档后末尾还是会多出`]]`.

**Comment by 88250** [comment]
你好，不知道现在这个问题是否还能重新，我先关闭了，如果还有反馈请继续跟帖，谢谢。

**Comment by nanmao** [comment]
> 你好，不知道现在这个问题是否还能重新，我先关闭了，如果还有反馈请继续跟帖，谢谢。

中文输入法符号自动补全, 新建引用文档后末尾还是会多出`]]`.
当前版本 v0.5.44
![2020 12 28](https://user-images.githubusercontent.com/26304888/103185293-b1f96b80-48f6-11eb-87fe-c2c894db15b5.gif)

**Comment by 88250** [comment]
请问你使用的输入法是？我去下载安装一个试试看。

**Comment by nanmao** [comment]
http://qq.pinyin.cn/
![image](https://user-images.githubusercontent.com/26304888/103185998-cee36e00-48f9-11eb-8ed6-1e9ef8a40464.png)

**Comment by 88250** [comment]
哇，QQ 拼音居然还在更新，之前我看到他们官网说放弃了就转用搜狗了，刚刚安装 QQ 拼音，很干净舒适。

这个问题已经能重现了，稍后修复 🙏
