### ISSUE TITLE
选中文本后进行内容块粘贴时锚文本的优化

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#321]
1、复制引用，复制嵌入和复制块内容，应该整合为复制块id和复制块内容，并提供相应的快捷键。在粘贴的时候，提供选项粘贴为块引用，粘贴为块嵌入和粘贴内容，并提供快捷键。比如ctrl+v就是粘贴为引用或者粘贴内容。ctrl+XXX+v为粘贴为块嵌入。甚至如果剪贴板是完整块id的话，ctrl+shift+v是块嵌入都可以考虑。
2、建议增加一个功能，类似于选中文本新建文档。选中文本后，在引用或嵌入块时候，直接把选中文本作为锚文本嵌入进去。比如，我选中了“红烧肉”三个字，用快捷键（或右键也可提供选项）粘贴引用块的时候，锚文本直接就是“红烧肉”。

**Comment by Vanessa219** [comment]
第一点已经修改，第二点没太明白

**Comment by wbooooooo** [comment]
就是现在每次粘贴块，锚文本都是块的前几个字。很多时候，我粘贴的时候，是我已经打好了一句话，比如: 今天见了张三。然后我的锚文本，其实就是张三。引用的是张三的名片。我希望我打了这句话，选中张三这两个字，粘贴块的时候锚文本就自动是张三了，而不是名片的前几个字。

**Comment by wbooooooo** [comment]
就是引用块，嵌入块时锚文本的逻辑问题。现在是先粘贴，再修改锚文本，我希望能做到，先写好锚文本，然后选中它，再粘贴。这样更符合写笔记思考的逻辑。

**Comment by 88250** [comment]
收到，我们明白了，非常感谢！
