### ISSUE TITLE
标签功能优化建议

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3214]
目前笔记内添加标签，需要把标签内容写在笔记内容里。有时候我只想按标签分类，不想把标签内容体现在笔记里面。作者看看能不能实现这个功能呢。就是标签作为笔记的虚拟属性隐藏存在。不直接显示在笔记内。但是在标签栏里还显示出来。

**Comment by 88250** [comment]
可以在属性面板中设置自定义属性。

**Comment by 88250** [comment]
需要搭配挂件，但是现在没人开发 😂

**Comment by bestv5** [comment]
挂件是啥 ，有说明或者开发文档的链接吗

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/1488
