### ISSUE TITLE
打开文档并定位文档所在位置，然后打开日记，文档树会全部折叠

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3217]
### Version environment

* Version: v1.4.4
* Operating system: win10

**Comment by Vanessa219** [comment]
感谢反馈，但目前无法重现。请更新到 1.4.5 再试，如果还能重现请录屏。

**Comment by JokeenZhang** [comment]
在1.7.3还是会出现。

> 你好，这个问题在最新版上还能重现吗？

在1.7.3还是会出现。

**Comment by Vanessa219** [comment]
还是无法重现，麻烦详细说一下操作步骤

**Comment by JokeenZhang** [comment]
https://user-images.githubusercontent.com/33319484/150105883-88c9491e-992f-434f-8c2d-c9e6148c33b7.mp4

和以前一样的使用操作步骤。

**Comment by Vanessa219** [comment]
你新建一个空的库可以重现么？

**Comment by JokeenZhang** [comment]
从1.7.3升级到1.7.5后，新建笔记本还是会出现这个问题

![QQ20220120-154531-HD](https://user-images.githubusercontent.com/33319484/150295653-c2a4c70a-14c7-4eb4-9728-62ec4fe055e2.gif)

gif经过压缩，有些看不清

![image](https://user-images.githubusercontent.com/33319484/150295715-a07b1b86-c5d9-41d9-8e4d-05e5fb6cca1b.png)

大概就是Two有three的子文档，打开日记本的日记后，Two会折叠

系统的版本信息：MacOS 11.6

**Comment by Vanessa219** [comment]
理解错了，一直以为是开启了设置里面的“始终定位打开的文档”后，新建日记进行定位。
下个版本修复。
