### ISSUE TITLE
优化冒号后自动弹出 emoji 选择框的场景

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#3223]
### In what scenarios do you need this function?
冒号是常用的标点符号, 在绝大多数情况下输入冒号是作为标点符号使用而不是想输入emoji, 每次输入冒号都弹出emoji选择框很干扰体验, 并且在冒号后直接按回车键会输入第一个emoji而不是换行.

### Describe the optimal solution
提供选项关闭冒号呼出emoji的功能, 使冒号能仅仅作为普通标点符号使用

**Comment by 88250** [comment]
感谢反馈，还需要考虑一下替代方式，比如类似 wolai 使用双 `::` 或者仅支持通过斜杆菜单 #3224。

**Comment by 88250** [comment]
感觉 Notion 的逻辑也很好：输入 `:` 后不展现菜单，紧跟输入的话出现筛选。

因为在英文排版中，标点符号后面需要跟一个空格，这个空格刚好可以避免出现不必要的 Emoji 筛选菜单。

@Vanessa219

**Comment by Vanessa219** [comment]
输入冒号后，以下情况冒号后不再弹出 emoji 选择框
1. 按 esc 和方向键后
2. 冒号前为数字
3. 鼠标点击过编辑器后
