### ISSUE TITLE
下侧左方分割在左侧边栏右侧(很难文字描述，看图)

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#3226]
### In what scenarios do you need this function?

目前的下册左方是左图的模式，希望增加一个右图的分布选项

![image](https://user-images.githubusercontent.com/19968935/138393824-a19b2352-7b64-47e2-86f1-b1ef70625e50.png)

**Comment by Vanessa219** [comment]
如果左右两侧都展开的话，下部位置将会比较小。目前就不添加了。

**Comment by HowcanoeWang** [comment]
> 感谢建议，考虑到左右两侧都展开的话，下部位置将会比较小。目前就不添加了。

啊，想要的就是这样的效果，两侧都展开后，使得反链变成嵌入当前页面下方，现在下面太宽了反而难受😂
