### ISSUE TITLE
粘贴文本中包含 `((` 时不应该出现块引提示

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3227]
一段文字中包含（（文字xxx））,黏贴到笔记中的时候，会弹出引用块的提示，这个能优化一下吗。希望在黏贴这种文字的时候，不提示出来。
效果见下图：
![image](https://user-images.githubusercontent.com/15650275/138417055-436e8891-ee3a-47ab-82ff-870ce6a2dc82.png)

**Comment by Vanessa219** [comment]
改进一下 这个问题 https://ld246.com/article/1636012394127?r=88250
