### ISSUE TITLE
Ctrl B 加粗文字后光标位置问题

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#323]
现在ctrl+b加粗后，光标在末尾\*\*的前方，建议光标跳到末尾\*\*的后方，便于加空格或者继续编辑。

**Comment by 88250** [comment]
@Vanessa219 

* 如果 Ctrl B 时内容为空则将插入符置于内测 `**‸**`
* 如果不为空则置于右侧 `**foo**‸`

其他几个行级排版操作类似。
