### ISSUE TITLE
iOS 移动端显示上下有黑边

### ISSUE THREAD

**Issue by SeyeeL** [siyuan-note/siyuan#3254]
![c2a9fc62e6f70f2abe50fcd488a48de](https://user-images.githubusercontent.com/71479570/138623614-b8360ef5-9995-4359-ba42-3cdf96da0c3b.jpg)
ios 15.0.2 ,13promax

**Comment by 88250** [comment]
你好，请试下最新的公测版看该问题是否还存在，谢谢。

**Comment by SeyeeL** [comment]
![image](https://user-images.githubusercontent.com/71479570/140680087-8dc4d612-03b1-4e94-8bf4-9aa9d5e2fdde.png)
依然有
