### ISSUE TITLE
剪藏识别代码块语言改进

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3266]
* https://ld246.com/article/1635220636064 已经得到部分改进
* https://ld246.com/article/1637725241835 微信公众号的代码块无法解决
* https://ld246.com/article/1640492387130 提供的示例站点无法打开
* https://github.com/siyuan-note/siyuan/issues/3573 Readability.js 会剔除类包含 `comment` 的节点，估计无法解决
* https://ld246.com/article/1641374157234 会剪藏为 HTML 块
* https://github.com/siyuan-note/siyuan/issues/4002 v2.1.5 改进
* https://ld246.com/article/1645173909897 已经解决
* https://github.com/siyuan-note/siyuan/issues/4361 v2.1.5 改进
* https://github.com/siyuan-note/siyuan/issues/4368 提供的示例站点无法打开
* https://ld246.com/article/1657001891385 无法支持

**Comment by YorickGu** [comment]
https://blog.csdn.net/weixin_37778801/article/details/86286817
这个网址的剪藏的时候，代码块中的代码最下面会有数字

**Comment by huang5556019** [comment]
类似https://juejin.cn/post/7075156399839248420 
里面的答案类似待办类型：
 A、正确
 B、错误
 剪藏后变成无序列表的样式

直接复制 然后粘贴 样式正常

**Comment by isAsher** [comment]
https://www.daimajiaoliu.com/daima/485ad133a100408
网页代码块是 Java，剪藏后变成 HTML

**Comment by 88250** [comment]
能够支持的已经支持了，请看更新后的 issue 正文，谢谢。
