### ISSUE TITLE
增加鼠标中键点击标签关闭页面

### ISSUE THREAD

**Issue by lowwor** [siyuan-note/siyuan#327]

**Comment by nanmao** [comment]
去鼠标官网看看有没有驱动，可以自定义设置。
![image](https://user-images.githubusercontent.com/26304888/97098250-b797c280-16b5-11eb-9821-f6268e08391a.png)

![image](https://user-images.githubusercontent.com/26304888/97098254-bbc3e000-16b5-11eb-83c3-33e90ce56017.png)

**Comment by 88250** [comment]
能通过定制外设（输入法类似）解决的我们就暂时忽略了，感谢反馈。
