### ISSUE TITLE
增加区分默认图标和自定义图标属性标识的建议

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3270]
由于css中不能过滤svg元素下use元素 的xlink:href 字符，“xlink:href ” 不是use的属性。
希望在svg的元素上增加一个属性标识该svg是默认的图标，
例如：class=‘def-icon’ 或者 data-type=“iconfile”。
这样在主题thems.css文件中配置笔记文件图标和层级图标。

**Comment by Vanessa219** [comment]
自定义图标是 img， 默认图标是 svg。可以通过 tagName 进行区分

**Comment by bestv5** [comment]
> 自定义图标是 img， 默认图标是 svg。可以通过 tagName 进行区分

我使用的版本是1.5.2，没有发现自定义图标是img，还是svg。
![图像 1](https://user-images.githubusercontent.com/15650275/141872103-cfb3749d-943d-4241-af1b-8de653328488.png)

**Comment by Vanessa219** [comment]
这样的就是系统的，其他的就是自定义的

**Comment by bestv5** [comment]
> > 自定义图标是 img， 默认图标是 svg。可以通过 tagName 进行区分

可能我没表述清楚，我说的默认图标就是“ iconfile” 这个图标，其他用户选择的系统图标和用户导入的图标是自定义图标。我想筛选的是用户有没有自己选择图标，比如，筛选用户更换过图标的元素 ，css样式却筛选不出来。

**Comment by Vanessa219** [comment]
<svg class="custom-icon">

**Comment by bestv5** [comment]
@Vanessa219  @88250  非常感谢两位支持这个功能，千里膜拜 <g-emoji alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png" class="emoji">🚀</g-emoji> <g-emoji alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png" class="emoji">🚀</g-emoji> <g-emoji alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png" class="emoji">🚀</g-emoji>
