### ISSUE TITLE
优化编辑器光标移动

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3274]
https://ld246.com/article/1635339227687

**Comment by Morganwan90** [comment]
因为这个这个光标移动的优化..貌似现在css中无法被focus...
主要我觉得..好像没有解决帖子中的问题...

**Comment by Vanessa219** [comment]
修改后只有 `protyle-wysiwyg`  才能被 focus，
你按照帖子中的进行操作，如果移动到其他地方，浏览器会进行记忆。
