### ISSUE TITLE
下划线覆盖公式问题

### ISSUE THREAD

**Issue by SupritYoung** [siyuan-note/siyuan#3277]
# 如图

![image](https://user-images.githubusercontent.com/30597946/139174506-5e944f4e-ebd0-4f2f-af2f-8afbdfc48105.png)

还有就是行内公式过于靠下，有点不美观，再靠上一点就更好看

![image](https://user-images.githubusercontent.com/30597946/139174609-51cd516b-d507-47eb-8870-151881b86824.png)

**Comment by Vanessa219** [comment]
这个需要 https://github.com/siyuan-note/siyuan/issues/2911 的支持
