### ISSUE TITLE
双击悬浮层顶部栏进行 pin/unpin 操作

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#3281]
https://ld246.com/article/1635347537273

**Comment by netdog2019** [comment]
如果有几个悬浮窗都pin在顶层后，需要点击一个悬浮窗然后松开按键才能到最顶层，应该设计成点中按键后就自动到切换到最上面，因为如果移动一个悬浮窗，应该是点击了以后自动到最上面，然后移动到合适的位置，松开结束。现在是点击后，还是在底层，移动的时候也是在底层，直到最后松开按键，才到最上层。能否优化一下？

**Comment by Vanessa219** [comment]
@netdog2019 感谢建议，a5 改进。
