### ISSUE TITLE
剪切板中为链接且无选中内容，ctrl+k 无效

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#3288]

**Comment by deerainw** [comment]
![image](https://user-images.githubusercontent.com/32661922/140544651-656265f7-6da8-45ca-91f4-d7f28012eb18.png)

剪贴板里复制了一个链接，在编辑器里按 ctrl+k，聚焦的是第一行，这里直接聚焦第二行比较好

**Comment by Vanessa219** [comment]
@deerainw 收到，稍后改进

**Comment by zijihezijivan** [comment]
还有个小问题，在新块的空行（没内容时）该快捷键还是无效，得输入点内容才有效，输入一个空格也行，反正得输入内容。

**Comment by zijihezijivan** [comment]
离谱的是，当你把输入的所有内容都删了后，cmd+k 是会生效的，也就是说新行初次使用时候如果为空，cmd+k无效

**Comment by Vanessa219** [comment]
感谢反馈，下个版本修复
