### ISSUE TITLE
当第三方文件同步客户端同步笔记工作目录时，思源报错状态异常

### ISSUE THREAD

**Issue by roeseth** [siyuan-note/siyuan#3290]
### 描述问题 Describe the problem
在Synology Drive Client中启用NAS与本地思源工作目录的双向同步时，任意打开笔记会在编辑过程中随机时间点弹出状态异常，重建索引或强制退出后该笔记均会**丢失**。停用Synology Drive Client后问题消失。怀疑思源不能正确处理被占用文件/被修改的文件（？）。

### 期待的结果 Expected result
第三方程序在操作思源工作目录时，思源能缓存编辑数据直到文件解锁，并有相应提示（类似”无法自动保存，[错误信息]“）。可以手动/自动触发重试（可强制覆写被第三方改动的文件？）。

### 版本环境 Version environment

* Version: v1.4.6 & v1.4.5
* Operating system: Windows 10 21H1 19043.1288
* Browser (if used): N/A

### 日志文件 Log File
[siyuan.log](https://github.com/siyuan-note/siyuan/files/7439174/siyuan.log)

### 更多信息 More information
Update: 单向同步没有问题，怀疑Synology Drive Client的双向同步有些额外的奇怪动作
<!--
请提供任何附加信息，以帮助我们更好地定位问题。
Please provide other additional information to help us diagnose the problem.
-
->

**Comment by 88250** [comment]
运行期间无法支持使用第三方同步盘实时同步，细节请看 https://ld246.com/article/1626537583158
