### ISSUE TITLE
路径不能包含中文标点和空格

### ISSUE THREAD

**Issue by zhaozhiliao** [siyuan-note/siyuan#3292]
### 描述问题 Describe the problem

如图，希望能路径能够支持。

路径：C:\Users\Files\Documents\[3]个人知识库\SiYuan。因为使用文件夹名“[1]知识库“，导致不能关联此文件。如果修改文件名，影响其他软件使用。
目前也是尝试切换思源笔记阶段，明白此问题优先级低，但还是希望未来能解决。目前用obsidian 和 logseq，软件，都能支持这种路径。

### 截屏或者录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/51565169/139416457-b98f50bb-0cac-422f-b32f-437972f5aef1.png)

### 版本环境 Version environment

版本：v1.4.6

**Comment by 88250** [comment]
你好，抱歉了，这个没有办法支持 https://github.com/siyuan-note/siyuan/issues/3205
