### ISSUE TITLE
支持列出和切换最近打开的文档

### ISSUE THREAD

**Issue by zijihezijivan** [siyuan-note/siyuan#3293]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在查看文档或编辑文档时候我们**经常需要去子文档中添加or编辑内容，完了就需要回到父级文档，此时迫切需要一个能快速返回父级稳定的快捷。**
因为tab多，打开的子文档可能跟父文档隔的很远，每次好难找，切换回去好麻烦

此前也有人提到这个问题：[连接](https://github.com/siyuan-note/siyuan/issues/239?utm_source=ld246.com)
目前给的解决方案是：「编辑点的前后跳转」
但**这并没有实际解决上面提到的需求**，因为**比如我跳到子文档编辑了很多内容，想跳到父级文档，此时如果用「编辑点的前后跳转」要操作好多步骤才能回到父目录，非常麻烦。**这样还不如直接用鼠标去点开父级文档，或者通过反链去打开父级文档

真正的需求是：一步跳转到父文档，类似电脑上的资源管理器「`cmd+上下箭头`」即可跳到上级目录和下级目录

### 描述可能的最优解决方案 Describe the optimal solution

最优的解决方案其实就是：**支持快速切换最近打开的文件**
类似IDE编辑器那样，`cmd/ctrl + e` 列出最近「打开」的「文件」（注意**不是**最近编辑的**块**），选中回车即可切换过去

目前是搜索栏为空会显示的是最近「编辑」的「块」列表，**这并不是解决『快速切换最近打开的文件』的方法**，这样会有个问题：同一条笔记**重复**显示好几条，仍然不便于文件切换

![image202110291724366k0w77r.png](https://raw.githubusercontent.com/zijihezijivan/push/master/image-20211029172436-6k0w77r.png)
这里要是列出最近「打开」的「文档」就可以了，主要想通过这种方式来切换最近打开的文件

### 其他信息 Other information

目前支持打开多个文件（多tab）是个优点，但与之配套的功能「文件切换」目前还非常鸡肋，是个痛点。文件切换很不方便，希望后面能够支持

**Comment by 88250** [comment]
感谢提议，后续会支持。

**Comment by woaihuangxueying** [comment]
希望可以达到 alt+TAB的效果
对于我这种经常要在多个文档中切换的人来说，这个功能敲重要

**Comment by Foundation-Maker** [comment]
我搜索了一下最近使用的这个功能；还是有不少人迫切希望这个功能的出现；在Java 开发工具中类似于 ctrl + e 就可以显示；方便

**Comment by 88250** [comment]
v2.0.25 支持 Ctrl+Tab 切换页签，但是仅能在当前打开的页签中切换，不支持选择已经关闭的页签 https://github.com/siyuan-note/siyuan/issues/5290

**Comment by JokeenZhang** [comment]
> 我搜索了一下最近使用的这个功能；还是有不少人迫切希望这个功能的出现；在Java 开发工具中类似于 ctrl + e 就可以显示；方便

那个是最近编辑文件列表吧，这个功能也挺实用的啊

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/6841

**Comment by Achuan-2** [comment]
为什么不是alt+e是列出文档呢

**Comment by 88250** [comment]
@Achuan-2 尽量按照 JetBrains 的默认快捷键

**Comment by aptexd** [comment]
> @Achuan-2 尽量按照 JetBrains 的默认快捷键

实锤了“知识编程”软件[狗头]，当然我也是赞成这样的的🤣

**Comment by 88250** [comment]
从之前的讨论记录可以看出，大家都认为 Ctrl+E 更好一些 😃

**Comment by aptexd** [comment]
能改就行，反正快捷键的修改十分方便

**Comment by Zuoqiu-Yingyi** [comment]
要不要在菜单栏左上角/右上角添加一个该功能的按钮, 感觉不太方便找到入口

**Comment by Vanessa219** [comment]
这个功能感觉不太合适占用顶部呀

**Comment by Vanessa219** [comment]
这个位置如何？
<img width="303" alt="image" src="https://user-images.githubusercontent.com/970828/208045920-587c285a-127f-4b65-a47d-5b6a55f2ab3f.png">

**Comment by leolee9086** [comment]
要不放到边栏？

**Comment by Vanessa219** [comment]
边栏是放面板的。
