### ISSUE TITLE
块移动支持复制为引用或嵌入

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3294]
目前的块拖拽移动是剪切，考虑增加复制为引用或嵌入。

https://ld246.com/article/1635562072606/comment/1635563001129#comments

**Comment by qifengle1998** [comment]
可不可以这样子
直接拖动就是剪切，
alt+拖动 就是复制

**Comment by yawn0305** [comment]
支持这个改进功能，希望能尽早实现

**Comment by AndssY** [comment]
支持这个改进功能

**Comment by Vanessa219** [comment]
按住 alt 为插入引用，按住 shift 为插入嵌入块

**Comment by why8023** [comment]
可否再加一个互换功能, 将原始块移动到新页面, 同时在旧页面生成引用块或者嵌入快, 这个对于整理和溯源很有帮助

**Comment by 88250** [comment]
@why8023 请关注 #5805

**Comment by deerainw** [comment]
> 按住 alt 为插入引用，按住 shift 为插入嵌入块

先按住 shift 键无法拖动，现在要先拖动再按住 shift 再放开鼠标才行

**Comment by Vanessa219** [comment]
这可能是系统的设定吧。从外部拖拽资源到编辑器也是只能监听松开时候所按住的键，我改一下文案吧。

**Comment by deerainw** [comment]
> 这可能是系统的设定吧。从外部拖拽资源到编辑器也是只能监听松开时候所按住的键，我改一下文案吧。

但是按 alt 的时候是可以先按 alt 再拖动的

**Comment by Vanessa219** [comment]
都统一拖之后再按吧，要不用户可能会混乱 🤪

**Comment by fanglypro** [comment]
为啥改成只针对反链面板块移动了？现在反链面板要查看完整上下文需要浮窗，这个issue的实用价值还是比较有限的，而且后面改成编辑器式反链面板后，这个功能还要重做吧？

alt+drag的一个核心应用场景是面向正文的，例如 https://www.youtube.com/watch?v=RvWic15iXjk 这个视频中能明显感受到alt+drag的便利。以及“反链即正文”，这个在roam/logseq中能很明显感受到，反链中的操作和正文中的操作是一模一样的，没有割裂感。

**Comment by Vanessa219** [comment]
先用反链做了看看用户的操作手感。没太大问题就可以推广到文档树、块标等上面。
