### ISSUE TITLE
Docker 容器以 1000:1000 用户组执行

### ISSUE THREAD

**Issue by joshuazm** [siyuan-note/siyuan#3296]
目前测试在群晖里创建docker侍服，群晖里的用户无法正常同步在web页面下创建的笔记，目前暂时解决办法是使用定时任务定期刷新data目录下用户及用户组为群晖用户及用户组，希望能够支持如下的运行方式：

`docker run --name "siyuan_note" -e LANG=zh_CN.UTF-8 -e LC_ALL=zh_CN.UTF-8 -u 1000:1000 -d -v /volume1/docker/siyuan_note:/siyuanworkspace -p 6806:6806 b3log/siyuan --resident="true" --workspace /siyuanworkspace   --servePath="xx.com" --ssl=true --accessAuthCode="xxxx"`
 希望能够实现如上命令所示允许指定-u参数以普通用户的权限来执行，具体的用户id与组id由使用人自己设置

**Comment by netdog2019** [comment]
我的也是一样的问题，经常同步出错，我把群晖docker的同步方式更换成https，电脑端照样用ssh就没问题，但是docker经常会崩溃，自动重启。但是同步数据没什么问题。

**Comment by 88250** [comment]
@joshuazm 我们在镜像里先写死 1000:1000 用户组执行
@netdog2019 同步时连续拉取到两次下载数据后会自动退出

**Comment by fangxinzhi** [comment]
不是很懂这个情况是怎么回事，我在群辉docker上的思源笔记从来没有崩溃过或者同步不了，用的是群辉自带的DDNS服务加公网IP加端口映射，就是有时候在不同的电脑上访问日记页面顺序会乱

**Comment by gtgc2005** [comment]
有一个很不理解的事情就是如此重大的更新，应该给一定的缓冲时间提醒下用户的。因为很多用云服务器的用户并不存在这个问题，，而写死后对他们来说，意味着要重新修改dokcer，而这需要一定时间

事实上，我正准备从笔记中提取一段文字，可是打开后看着502报错一脸蒙蔽，甚至有一定的恐慌。这很不友好。所有有没有一种可能，下次类似的变动，可以提前在笔记内推送下通知告知下。以便提前有所准备。

**Comment by fangxinzhi** [comment]
> 有一个很不理解的事情就是如此重大的更新，应该给一定的缓冲时间提醒下用户的。
> 
> 事实上，我正准备从笔记中提取一段文字，可是打开后看着502报错一脸蒙蔽，甚至有一定的恐慌。这很不友好。所有有没有一种可能，下次类似的变动，可以提前在笔记内推送下通知告知下。以便提前有所准备。

我只能说我对思源的使用方式还很简单，绝大多数更新我好像都用不上，毕竟我是把笔记部署在群辉上白嫖

**Comment by gtgc2005** [comment]
> > 有一个很不理解的事情就是如此重大的更新，应该给一定的缓冲时间提醒下用户的。
> > 事实上，我正准备从笔记中提取一段文字，可是打开后看着502报错一脸蒙蔽，甚至有一定的恐慌。这很不友好。所有有没有一种可能，下次类似的变动，可以提前在笔记内推送下通知告知下。以便提前有所准备。
> 
> 我只能说我对思源的使用方式还很简单，绝大多数更新我好像都用不上，毕竟我是把笔记部署在群辉上白嫖

思源的进步肯定要通过不断的迭代去实现更多的功能以及满足更多的用户需求，这是必然的。所以类似修改是必不可少的。只不过我建议在修改前通过一些手段通知用户提早做准备。因为以我为例，我现在不得不停下本来的计划，去查阅资料修改的我的docker-compose代码，这是一个计划外的意外。而我并没有为此做好准备。

**Comment by fangxinzhi** [comment]
docker现在不是可以选择版本吗，最新版不好用可以退回上一个版本啊

**Comment by adoom2017** [comment]
我还以为我的笔记都丢了么，估计因为这个权限变更了，所以原来的路径读不了了

**Comment by gtgc2005** [comment]
提醒下，代码需做如下修改
Docker在原命令上加上`-u 1000:1000`
docker-compose在原命令上加上`user: "siyuan"`

同时，ssh内给宿主机上的映射文件夹赋权
`chown -R 1000:1000 "本地映射文件夹“`

以上，应该能解决更新后的权限报错问题

**Comment by StephenLiz** [comment]
从v1.5.1开始，在群晖内能使用 -v 参数运行镜像无报错，但宿主机内的目录一直为空白

docker run --name siyuannotes -dit --restart=always -v /volume1/Notes/SiYuanNotesData:/root/Documents/SiYuan -p 6806:6806 -u 1000:1000 b3log/siyuan:v1.5.2 -resident -accessAuthCode mypassword

**Comment by gtgc2005** [comment]
> 从v1.5.1开始，在群晖内能使用 -v 参数运行镜像无报错，但宿主机内的目录一直为空白
> 
> docker run --name siyuannotes -dit --restart=always -v /volume1/Notes/SiYuanNotesData:/root/Documents/SiYuan -p 6806:6806 -u 1000:1000 b3log/siyuan:v1.5.2 -resident -accessAuthCode mypassword

试试看加上如下命令
--workspace /root/Documents/SiYuan

**Comment by adoom2017** [comment]
> 从v1.5.1开始，在群晖内能使用 -v 参数运行镜像无报错，但宿主机内的目录一直为空白
> 
> docker run --name siyuannotes -dit --restart=always -v /volume1/Notes/SiYuanNotesData:/root/Documents/SiYuan -p 6806:6806 -u 1000:1000 b3log/siyuan:v1.5.2 -resident -accessAuthCode mypassword

内部路径变了，/home/siyuan/Documents/SiYuan，不再是root用户了

**Comment by zhangzz66** [comment]
权限变了之后很不方便了, 比如管理员从其他地方复制过去的文件, 思源docker内会报错permission deny
