### ISSUE TITLE
markdown 标记中文的斜体或粗体之后必须输入空格才能生效

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#3301]
### 描述问题 Describe the problem
使用 `*` `**` 来标记中文的斜体和粗体, 必须在其后输入一个空格才能正确显示. 对于英文则没有这个问题.

### 截屏或者录屏演示 Screenshot or screen recording presentation
![markdown](https://user-images.githubusercontent.com/58763608/139586293-2fb7f068-e735-4d78-9c17-696d326a95c6.gif)

### 版本环境 Version environment

* Version: 1.4.6
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
感谢反馈，这个问题会在 v1.4.7 中修复。
