### ISSUE TITLE
在 list 内使用代码块，样式有问题

### ISSUE THREAD

**Issue by crazyhl** [siyuan-note/siyuan#3309]
### 描述问题 Describe the problem

在 list 内使用代码块，样式有问题，在段落外使用则没问题。
更换主题后，没发生奇怪现象，判断是主题问题，使用的主题是Tsundoku Dark
但是，使用 Tsundoku Light 则没法生问题，切换 Tsundoku Dark 后问题依旧

### 期待的结果 Expected result

第一个图是出现问题的图，第二个图是切换主题后的正常状态。希望能调整一下

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/5474833/139792028-f15b738f-30d2-40d1-947e-c86a03e515a2.png)
![image](https://user-images.githubusercontent.com/5474833/139792589-a9548a89-2931-4c87-bc03-6b8fbca60c25.png)

### 版本环境 Version environment

* Version: 1.4.6
* Operating system:  macOS 12.0.1 
* Browser (if used):

**Comment by 88250** [comment]
更新下主题试试，如果还有问题，请到该主题仓库上反馈，谢谢。
