### ISSUE TITLE
SQL 不支持字符串拼接操作

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3312]
https://ld246.com/article/1635827860414

**Comment by winter60** [comment]
【BUG】嵌入块的sql使用 || 拼接时会查询错误



使用嵌入块进行查询的好处，就是能够显示全文，根据时间进行查询就一个频繁的操作。
比如查询昨天写的内容：
```sql
select 
*
from blocks
where type = 'd'  
and updated  like  '%' ||  strftime( '%Y%m%d', date('now','-1 day')) ||'%' 
and ial not like '%漫游%'
order by updated desc

```
这里我不得不用到拼接字符串的语法来查询时间，可查询的结果不是我想要的，还增多许多内容，更甚至造成了套娃导致程序卡死。
希望能够改进一下嵌入块，能够支持`||`语法
