### ISSUE TITLE
有序号的段落无法将中间的一个块转换为平级的普通段落

### ISSUE THREAD

**Issue by hbuexinxin** [siyuan-note/siyuan#3313]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

期望：比如已经有5行的有序列表，现在想将最后的2行和前面的3行分开为2个部分，在第3行后新增一行普通段落，之前的最后2行可以重新开始序号

问题：现在无法在中间插入一个普通的段落，使用backspace删除后，段落并不能与前面的列表平级，再次使用backspace后，回到了上一行列表，而不是减少一级缩进
![image](https://user-images.githubusercontent.com/2741609/139846089-d1b132ca-7458-47e0-a8c1-6f73bdc20251.png)

期望是下面的效果
![image](https://user-images.githubusercontent.com/2741609/139846576-fdcc7354-838f-4165-95dc-6e75af18d186.png)

**Comment by 88250** [comment]
你好，这个操作我们估计不会支持。如果一定需要的话，只能考虑插入段落以后下面这个列表手打 `4. ` 重新调整，抱歉抱歉。
