### ISSUE TITLE
PDF 按住 Ctrl+D 进行矩形标注，按住 Alt+D 进行矩形标注并显示背景

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#3318]
https://ld246.com/article/1643809195430

**Comment by Wonderdch** [comment]
希望未来 PDF 划词标注也能通过快捷键（或默认设置）来实现是否显示背景。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/7159 @Vanessa219
