### ISSUE TITLE
Win10平台无法正常访问集市

### ISSUE THREAD

**Issue by Qi-XM** [siyuan-note/siyuan#3319]
### 描述问题 Describe the problem

在win10终端访问集市, 软件会变为全白屏无法操作, 只能退出重启. 

### 截屏或者录屏演示 Screenshot or screen recording presentation
- 此为软件全窗口截图, 为全白色.
![image](https://user-images.githubusercontent.com/76560575/139989771-1942a5f7-2a4c-4616-8b30-db488a61f99f.png)
- endline

### 版本环境 Version environment

* Version: v1.3.4
* Operating system: Windows 10
* Browser (if used): 

### 日志文件 Log File

* 日志无异常
I 2021/11/03 09:23:49 serve.go:68: kernel HTTP server is booting [http://127.0.0.1:6806]
I 2021/11/03 09:23:49 box.go:422: rebuilt database of box [20211103090916-ev2avwd] in [0.00s]
I 2021/11/03 09:23:49 box.go:422: rebuilt database of box [20210808180117-czj9bvb] in [0.11s]
I 2021/11/03 09:23:49 conf.go:415: post-init database size [1.1 MB]
I 2021/11/03 09:23:50 working.go:108: kernel booted
I 2021/11/03 09:25:37 conf.go:281: exited kernel

**Comment by 88250** [comment]
你好，请升级到最新版以后再试，谢谢。
