### ISSUE TITLE
有关assets 目录下创建软链接引用资源的一些问题

### ISSUE THREAD

**Issue by VSpade7** [siyuan-note/siyuan#3322]
# mac
## 当我在 assets 目录下创建一个 PDF 文件的软连接时，在 设置-资源 可以检测到这个文件
![image](https://user-images.githubusercontent.com/46594083/140005229-0e5b2818-0577-4e80-b2af-cb774d4fea6d.png)
---
![image](https://user-images.githubusercontent.com/46594083/140005300-060cdffd-f260-4291-9130-c57c230700eb.png)
## 当我在文档里想引用的时候，搜不到这个资源
![image](https://user-images.githubusercontent.com/46594083/140005405-c5356223-3eab-4ba2-9af1-1d7eb252b360.png)
---
![image](https://user-images.githubusercontent.com/46594083/140005345-67613144-92df-46ff-a4a4-3da6e733f61f.png)
## 如果我先随便引用一个资源，再把资源路径改成那个软连接，是可以识别出这个资源并加载 PDF 的
![image](https://user-images.githubusercontent.com/46594083/140005548-16afd815-8bcd-4924-96a1-d712aa3bb178.png)
有些 PDF 体积太大了，一股脑全塞到 assets 着实有点蛋疼，看看能不能优化一下，在文档插入的时候能检测到软链接。
之前群里还提到不是通过思源上传的资源没有时间戳，目前感觉只能自己拿个小 pdf 上传完后生成时间戳文件名后再把文件名改到真正要用的软链接上。
# win
win 下似乎不支持直接对单个文件设置软链接，只能链接文件夹，不过 assets/软链接文件夹/资源 这样也是可以用的
# Linux
Linux 没有测试

**Comment by 88250** [comment]
你好，估计只能先正常插入资源文件，然后手动将资源文件移走，并用一样的文件名创建软连接。因为如果不在编辑器里上传的话，资源文件没有插入数据库，所以会搜索不到。

未引用资源目前的实现为了保险起见，走的是全量文件扫描，而不是查库，所以不存在这个问题。
