### ISSUE TITLE
Linux版修改字体以后代码段里的字体没有改

### ISSUE THREAD

**Issue by Homurua** [siyuan-note/siyuan#3326]
### 描述问题 Describe the problem
如题，我改了字体以后，代码段里的字体还是系统默认字体

### 期待的结果 Expected result
可以正常修改

### 截屏或者录屏演示 Screenshot or screen recording presentation
![Screenshot from 2021-11-04 12-30-23](https://user-images.githubusercontent.com/8419862/140258310-d6870a4c-e48e-4872-ae5c-41bf45607657.png)

### 版本环境 Version environment

* Version: v1.4.6
* Operating system: Ubuntu 21.10, Gnome 40.4.0
* Browser (if used):

**Comment by 88250** [comment]
代码块用的是其他字体。
