### ISSUE TITLE
数学公式显示问题

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#333]
- MathJax引擎显示符号不全; 
- 希望公式显示能调大一些, 太小了.
![image](https://user-images.githubusercontent.com/26304888/97112574-feba9d80-171f-11eb-9f35-732ccacbfd3a.png)
![image](https://user-images.githubusercontent.com/26304888/97112577-04b07e80-1720-11eb-92be-43dcae67a9d5.png)
![image](https://user-images.githubusercontent.com/26304888/97112637-653fbb80-1720-11eb-9fd6-eecac270b1c5.png)

$\sin (\alpha \pm \beta)=\sin \alpha \cos \beta \pm \cos \alpha \sin \beta, \quad \cos (\alpha \pm \beta)=\cos \alpha \cos \beta \mp \sin \alpha \sin \beta$ $\tan (\alpha \pm \beta)=\frac{\tan \alpha \pm \tan \beta}{1 \mp \tan \alpha \tan \beta}, \quad \cot (\alpha \pm \beta)=\frac{\cot \alpha \cot \beta \mp 1}{\cot \beta \pm \cot \alpha}$

**Comment by Vanessa219** [comment]
* 显示还是全的，只是超过了背景
![image](https://user-images.githubusercontent.com/970828/97797676-e683da80-1c59-11eb-8557-b33f13598327.png)
* 好像用块级的 $$ 就会显示的大一点

**Comment by Vanessa219** [comment]
还是优化了一下，麻烦 0.4.0 再看看

**Comment by nanmao** [comment]
> * 显示还是全的，只是超过了背景
>   ![image](https://user-images.githubusercontent.com/970828/97797676-e683da80-1c59-11eb-8557-b33f13598327.png)
> * 好像用块级的 $$ 就会显示的大一点



- 直接把$改为$$不能显示公式
- mathpix里识别出来的LaTeX语法，带$$的LaTeX也不能直接显示出公式
![image](https://user-images.githubusercontent.com/26304888/97802853-42158e80-1c81-11eb-855b-2eb4830948bc.png)
- 图里红色字标注的LaTeX：$\sin (\alpha \pm \beta)=\sin \alpha \cos \beta \pm \cos \alpha \sin \beta, \quad \cos (\alpha \pm \beta)=\cos \alpha \cos \beta \mp \sin \alpha \sin \beta$
$\tan (\alpha \pm \beta)=\frac{\tan \alpha \pm \tan \beta}{1 \mp \tan \alpha \tan \beta}, \quad \cot (\alpha \pm \beta)=\frac{\cot \alpha \cot \beta \mp 1}{\cot \beta \pm \cot \alpha}$

- 图里绿色字标注的LaTeX：$$
\begin{array}{l}
\sin (\alpha \pm \beta)=\sin \alpha \cos \beta \pm \cos \alpha \sin \beta, \quad \cos (\alpha \pm \beta)=\cos \alpha \cos \beta \mp \sin \alpha \sin \beta \\
\tan (\alpha \pm \beta)=\frac{\tan \alpha \pm \tan \beta}{1 \mp \tan \alpha \tan \beta}, \quad \cot (\alpha \pm \beta)=\frac{\cot \alpha \cot \beta \mp 1}{\cot \beta \pm \cot \alpha}
\end{array}
$$

**Comment by Vanessa219** [comment]
图里绿色字标注的需要使用 MathJax 进行渲染

在数学块公式内修改 $ 不会变成新块，需要在下方重新建一个。

**Comment by nanmao** [comment]
> 图里绿色字标注的需要使用 MathJax 进行渲染
> 
> 在数学块公式内修改 $ 不会变成新块，需要在下方重新建一个。

- 绿色字标注的LaTeX在下方重新建一个，也显示不出公式（两个渲染引擎都试了）
- 我想要的是，直接粘贴下方的LaTeX，能显示出公式
![image](https://user-images.githubusercontent.com/26304888/97819392-3f4b8580-1ce3-11eb-87c3-df631235085a.png)
![image](https://user-images.githubusercontent.com/26304888/97819401-48d4ed80-1ce3-11eb-8541-8615cc4ed4ed.png)

$$
\begin{array}{l}
\sin (\alpha \pm \beta)=\sin \alpha \cos \beta \pm \cos \alpha \sin \beta, \quad \cos (\alpha \pm \beta)=\cos \alpha \cos \beta \mp \sin \alpha \sin \beta \\
\tan (\alpha \pm \beta)=\frac{\tan \alpha \pm \tan \beta}{1 \mp \tan \alpha \tan \beta}, \quad \cot (\alpha \pm \beta)=\frac{\cot \alpha \cot \beta \mp 1}{\cot \beta \pm \cot \alpha}
\end{array}
$$
