### ISSUE TITLE
提供插入块、更新块和删除块的 API

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3334]
希望在API中增加一个接口，通过data-id或者其他唯一主键，更新块内容。
例如：
参数：data-id：123456   必填 
           data-content：块内容（可选，空就从笔记内获取）
通过这个api接口，可以更新笔记块内的内容。

**Comment by Crowds21** [comment]
对于编辑操作我感觉一般大家应该不会涉及到太复杂的操作,我觉得我可能用到的如下:

1. 通过指定的ID修改块内容,如果担心不同类型的块转换容易出问题,可以先只支持同类型块的内容修改. 
2. 在指定的文档末尾添加内容
3. 删除块
D大可能一直在担心第一个.但我觉得绝大多数人,可能也只是用这个来給 `- [ ]` 更改一下状态,或者是删除一下`#TODO#`标签. 再多就是批量删除或更改块的内容.
是不是可以先不考虑块类型之间的互相变化. 后续再提供专门的块类型转换的接口?

- id:  如果为block则修改block内容, 如果为doc 则直接在doc末添加内容
- action: update / delete
- content:  只支持一个块的content修改,而不支持makrdown修改

一点粗浅的想法.

**Comment by WeiCJ2020** [comment]
现在这个有计划了吗？感觉api完善之后， 有很多的辅助应用可以开发

**Comment by 88250** [comment]
需要考虑数据格式，目前有三种备选：JSON、kramdown 和 DOM，无论使用那种格式，都需要通过 Lute 进行解析，还需要时间进一步考虑。

**Comment by 88250** [comment]
文档[见此](https://github.com/siyuan-note/siyuan/blob/master/API.md#%E5%9D%97%E6%93%8D%E4%BD%9C)。
