### ISSUE TITLE
bug反馈：批量选择内容块时，如果同时滑动鼠标滚轮，将会导致上面选中的块丢失

### ISSUE THREAD

**Issue by SupritYoung** [siyuan-note/siyuan#3338]
批量选择内容块时，如果同时滑动鼠标滚轮，将会导致上面选中的块丢失。
理想情况：

https://user-images.githubusercontent.com/30597946/140493386-cc2ab6a9-085c-4acb-9786-519694ec5612.MOV

当前问题：

https://user-images.githubusercontent.com/30597946/140493339-e9bce77a-619a-4995-b85f-5e872922d6dd.MOV

**Comment by 88250** [comment]
你好，请关注 https://github.com/siyuan-note/siyuan/issues/2066
