### ISSUE TITLE
任务列表块编辑渲染问题

### ISSUE THREAD

**Issue by TonyW825** [siyuan-note/siyuan#334]
> SiYuan-v0.3.4
> win10 
#### 添加新待办项时以下两种情况概率交替出现：

1. 按待办列表项数形成多个待办列表块；
2. 原有待办列表形成1个无序列表块，新添加待办项形成一个新无序列表块

#### 关闭程序，待`kernel.exe`进程自动结束，重启程序后可显示正常结构；如在未恢复正常显示的情况下进行了第1种待办列表块`id`引用，则块结构不会在程序重启后恢复（录屏时未录到该种情况），但如果新生成的是第2种无序列表块，即便是引用了块`id`也会恢复显示为原来结构

另，文档编辑过程中预览<kbd>Ctrl E</kbd>正常，但导出`.md`时会按当时编辑状态下的文档内容结构导出

![待办列表编辑渲染问题](https://user-images.githubusercontent.com/46043068/97112467-6b816800-171f-11eb-8232-ebf1ede2dec7.gif)

**Comment by 88250** [comment]
感谢反馈，这问题很严重，我们会尽快修复。
