### ISSUE TITLE
当容器块的顶层块引用了文档块时，顶层块如果没有其它内容，引用这个容器块后渲染为空

### ISSUE THREAD

**Issue by Dammyxy** [siyuan-note/siyuan#3340]
### 描述问题 Describe the problem

https://github.com/siyuan-note/siyuan/issues/3126
在这个issue被采纳之后，当容器块的顶层块引用了文档块时，如果后面没有其它内容，复制这个容器块为块引用，再粘贴会导致渲染为空。只有在块菜单里复制该块为引用块时会出现这种情况。

### 期待的结果 Expected result
期望可以将顶层块的锚文本加入渲染
### 截屏或者录屏演示 Screenshot or screen recording presentation
![列表块第一行只有块引是渲染不出来](https://user-images.githubusercontent.com/48867926/140569024-eb2d5c31-a147-4114-8d79-780537d9cd99.gif)

### 版本环境 Version environment

* Version: 1.4.7
* Operating system: WIN11
* Browser (if used):

**Comment by 88250** [comment]
我这里重现不了，麻烦打包上传一下这个笔记本，谢谢。

![issue](https://user-images.githubusercontent.com/873584/140592456-847acacd-556b-4720-884c-aaecbc2efc7a.gif)

**Comment by Dammyxy** [comment]
> 我这里重现不了，麻烦打包上传一下这个笔记本，谢谢。
> 
> ![issue](https://user-images.githubusercontent.com/873584/140592456-847acacd-556b-4720-884c-aaecbc2efc7a.gif)
使用的是新建测试笔记本
补充：顶层块引用的是文档块，这样复制块引粘贴后渲染为空，目前1.4.8也能复现。
![引用渲染消失](https://user-images.githubusercontent.com/48867926/140599709-7c083b06-9108-4d7d-bc67-6d7809d80d39.gif)

**Comment by Dammyxy** [comment]
https://github.com/siyuan-note/siyuan/issues/3350 已经定位到问题
