### ISSUE TITLE
挂起无响应问题

### ISSUE THREAD

**Issue by Dammyxy** [siyuan-note/siyuan#3342]
### 描述问题 Describe the problem
有两种情况：
在第一张GIF图里按住退格键删除块后出现状态异常，这时的重建索引和强制退出都是有用的。
第二张GIF图里进行了一系列操作后出现异常，按住退格键删除块会导致重建索引和强制退出都没有用。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![按住退格键不动出现错误](https://user-images.githubusercontent.com/48867926/140569483-53d0f9f8-353a-40dc-9da7-ba20af6de0f1.gif)

![列表块第一行只有块引是渲染不出来](https://user-images.githubusercontent.com/48867926/140569494-f9c70adc-e9a3-4ac5-beaa-1a57d1a81b16.gif)

### 版本环境 Vers

ion environment

* Version: 1.4.7
* Operating system: win11
* Browser (if used): 

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/7488550/siyuan.log)

**Comment by 88250** [comment]
第一个问题还是重现不了；先修复第二个重建时卡死的问题。
