### ISSUE TITLE
希望可以在购买授权码后，图床可以传到自己用docker部署的版本上

### ISSUE THREAD

**Issue by mmdjiji** [siyuan-note/siyuan#3345]
希望可以在购买授权码后，图床可以传到自己用docker部署的版本上

出于安全性考虑，有内网部署笔记系统的需求，而图床功能很方便，但图床希望仅内网可见，能不能在购买授权码之后，提供一个设置入口，可以将图床部署在docker搭建的服务器之上。

**Comment by 88250** [comment]
所有数据都是在本地的，上传社区图床的功能只是为了方便复制到知乎、语雀等平台。

**Comment by mmdjiji** [comment]
就是，图片也可以上传到本地的服务器。

**Comment by 88250** [comment]
外链图片吗？如果是的话目前不会考虑 https://github.com/siyuan-note/siyuan/issues/641

**Comment by 88250** [comment]
我关闭了，如果还有问题欢迎跟帖，谢谢。
