### ISSUE TITLE
幻灯片模式中不会渲染数学公式

### ISSUE THREAD

**Issue by WangHaiYang874** [siyuan-note/siyuan#3347]
幻灯片模式中不会渲染数学公式. 望改进.

**Comment by whzecomjm** [comment]
+1 同样发现此问题。
![image](https://user-images.githubusercontent.com/7845827/140610285-1be8f383-26e7-462a-9a53-0b27d0db2c0f.png)

不过导出的pdf可以渲染出公式

**Comment by whzecomjm** [comment]
导出的pdf希望能支持slides模式~

**Comment by 88250** [comment]
你好，幻灯片演示功能会在 v1.7.2 移除，我关闭了，谢谢。

https://github.com/siyuan-note/siyuan/issues/3817
