### ISSUE TITLE
某些输入法中英文自动空格问题

### ISSUE THREAD

**Issue by TracyIverson** [siyuan-note/siyuan#3363]
### 中英文自动加空格功能在1.4.4版本后会出错

使用win10自带输入法中英文混输的时候，中英文之间的空格不会自动插入，需要在输入完成后删除一个字符或者输入一个空格，才会将之前输入内容中缺失的空格补全，使用百度\搜狗等输入法并不会出现这个问题，我看了更新公告，可能是这个修改[自动空格导致输入法吞字](https://github.com/siyuan-note/siyuan/issues/3222?utm_source=ld246.com)导致的问题

### 优化win10输入法兼容问题，或者考虑将自动加空格改为渲染时自动加间距

**Comment by 88250** [comment]
感谢反馈，近期版本修复。视觉空格方案暂时不考虑了，感谢提议。

**Comment by 88250** [comment]
@Vanessa219 目前测试这几款输入法下会有问题：

* 微软拼音
* QQ 拼音
* 小鹤音形

**Comment by TracyIverson** [comment]
那可能是我微软拼音版本的问题，我是在公司电脑上遇到这个问题的，用的是win10企业版1809

**Comment by 88250** [comment]
@TracyIverson 我这里微软拼音也有问题，这个问题我们还在看如何解决。

**Comment by TracyIverson** [comment]
> @Vanessa219 目前测试这几款输入法下会有问题：
> 
> * 微软拼音
> * QQ 拼音
> * 小鹤音形

**Comment by 88250** [comment]
别 close 啊……

**Comment by Jed-Z** [comment]
macOS原生输入法，通过Chrome远程访问Win上的SiYuan Kernel，同样会有这个问题

**Comment by 88250** [comment]
@Vanessa219 这个问题可能还影响标记符合并 https://ld246.com/article/1640672085298

**Comment by glatavento** [comment]
fcitx5 输入行内公式后切换为拼音输入法并输入时会卡死，必须点击其他位置取消输入才能从卡死中恢复

![Peek 2021-12-30 17-48](https://user-images.githubusercontent.com/76601050/147740546-60f80012-b7df-44ac-8317-1becdbc1d750.gif)

**Comment by 88250** [comment]
自动空格功能还是有些无法解决的问题，我们会在 v1.7.2 中移除中西文自动空格功能 https://github.com/siyuan-note/siyuan/issues/3826

以后如果找到好的方案我们会继续尝试，感谢各位反馈。

**Comment by ProgramFan** [comment]
有没有可能提供一个菜单项和快捷键，用户自己来触发一次「修正当前文档中英文间空格」？这个功能确实还是很有用的。

**Comment by raymond8825** [comment]
这个功能还是非常实用的啊，希望早日加回来

**Comment by ttimasdf** [comment]
吓得我不敢更新了……

是否可以做成选项？我也用微软拼音，虽然自动空格需要手动触发，但也比手动移动回去手动加入空格要方便的多呀

**Comment by ProgramFan** [comment]
@88250 D大怎么看？
