### ISSUE TITLE
win11环境下思源笔记秒退

### ISSUE THREAD

**Issue by Nixiabing** [siyuan-note/siyuan#3365]
### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
请提供一下日志文件，工作空间/temp/siyuan.log

**Comment by Nixiabing** [comment]
是不是这条：
I 2021/11/09 09:10:03 box.go:450: rebuilt database for notebook [20210907194453-2ufy57k] in [0.03s]

**Comment by ttimasdf** [comment]
。。你这跟你沟通成本就很高，完整文件一丢就得了呗

**Comment by 88250** [comment]
楼主，请更新到最新版后再试试。如果还有问题，请上传一下内核日志文件，我先关闭了。
