### ISSUE TITLE
顶栏优化UI

### ISSUE THREAD

**Issue by Batapha** [siyuan-note/siyuan#3367]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
虽然现在主要做的是稳定已有的功能，但是UI这件事也是一个软件必不可少的门面，期待能够适配macOS新的界面或者是有notion那样较好的UI（没有说现在的UI不好看的意思，只是还可以优化，也没有期待短期内能够改变，只是提出这个选项，希望能够作为优化的一个项目）

### 描述可能的最优解决方案 Describe the optimal solution
一个是finder的界面，一个是notion的界面，可以看到notion的界面语言非常统一，好看

![截屏2021-11-08 18 46 08](https://user-images.githubusercontent.com/50532539/140728660-8646d7bc-1358-4b1c-b89d-0e791ec9f6a4.png)

![截屏2021-11-08 18 46 39](https://user-images.githubusercontent.com/50532539/140728734-7a67584e-88c3-424f-b7e4-358153e5f94a.png)

**Comment by 88250** [comment]
顶栏上后续计划会先加入全局面包屑 https://github.com/siyuan-note/siyuan/issues/3007

功能入口可能会支持插件，这个还有待考虑，感谢提议。
