### ISSUE TITLE
Stylizing Buttons Drop Text's Links

### ISSUE THREAD

**Issue by tswwe** [siyuan-note/siyuan#3380]
### 描述问题 Describe the problem

Any stylizing button (e.g., <kbd>**B**</kbd>, <kbd>*I*</kbd>, <kbd>~~T~~</kbd>) on the editor toolbar drops target text's link if it has one.

### 期待的结果 Expected result

Stylizing buttons should not affect the link of text.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![rec](https://user-images.githubusercontent.com/36465489/141048736-cb05a385-0b14-4c4f-8d66-1d46df985949.gif)

### 版本环境 Version environment

* Version: 1.5.0
* Operating system: Win10 21H1

**Comment by 88250** [comment]
Duplicated with https://github.com/siyuan-note/siyuan/issues/2911
