### ISSUE TITLE
双链内容浮窗可以同一内容无限嵌套

### ISSUE THREAD

**Issue by bearxz** [siyuan-note/siyuan#3382]
### 问题
当通过双链查看浮窗内容时，能够对同一内容无限嵌套，显示多层相同浮窗。
### 预期结果
相同内容的浮窗过滤一下，不会产生同一内容嵌套的问题
### 截图
![图片](https://user-images.githubusercontent.com/37499441/141056135-aef2d472-48b5-4125-ac6f-ba0f84479fdd.png)

**Comment by 88250** [comment]
这个是特性……
