### ISSUE TITLE
无序列表后直接插入表格的bug

### ISSUE THREAD

**Issue by xfdj** [siyuan-note/siyuan#3385]
### 描述问题 Describe the problem

如果在无序列表后直接插入表格，左边是无法显示表格的图标的。只能使用`Ctrl+/`来打开表格的菜单。

![image](https://user-images.githubusercontent.com/38575841/141138947-47ae36f1-99d8-4b49-8158-eeb9e613e42b.png)

### 期待的结果 Expected result

应该类似超级块的图标显示那样，在同一行既显示表格图标，又显示无序列表图标。

### 版本环境 Version environment

* Version: v1.5.0
* Operating system: Windows 10
* Browser (if used): 

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/7513779/siyuan.log)

**Comment by 88250** [comment]
请用 <kbd>Ctrl+/</kbd> 来唤出该子块菜单。

这个是个优化，当列表项下面只有一个子块时，就不出现子块的块标菜单了。

**Comment by xfdj** [comment]
不清楚这个优化的意义，因为表格的块表菜单中没有表格的菜单设置选项，如果不出现子块的块标菜单，不知道能不能考虑一下让表格的菜单出现在无序列表的菜单里？这样才是不损失功能的情况下优化了吧。而且个人感觉这个优化并没有方便使用，而是会带来不便和使用上的疑惑，希望开发者能考虑一下加回来，谢谢~

**Comment by Vanessa219** [comment]
思源的块是允许嵌套的，如果嵌套的块太多，每一个块都显示的话，左侧会放不下的。所以只有一层嵌套的情况仅显示顶层。

**Comment by Vanessa219** [comment]
思源的块是允许嵌套的，如果嵌套的块太多，每一个块都显示的话，左侧会放不下的。所以只有一层嵌套的情况仅显示顶层。

**Comment by xfdj** [comment]
竖着显示图标的效果其实挺不错的，不知道可不可以作为左侧图标放不下的一个解决方案呢？

**Comment by xfdj** [comment]
另外其实在搜索里面当列表项下面只有一个子块时，还是会出现子块的块标菜单，如下所示。
![image](https://user-images.githubusercontent.com/38575841/141289864-14d1588d-cf75-41bc-bdd1-61d9ed399c88.png)
从设计语言来说这其实也存在不统一的情况。

**Comment by 88250** [comment]
> 竖着显示图标的效果其实挺不错的，不知道可不可以作为左侧图标放不下的一个解决方案呢？

竖着放的话下面有子块就放不下了。


> 另外其实在搜索里面当列表项下面只有一个子块时，还是会出现子块的块标菜单，如下所示。 ![image](https://user-images.githubusercontent.com/38575841/141289864-14d1588d-cf75-41bc-bdd1-61d9ed399c88.png) 从设计语言来说这其实也存在不统一的情况。

这个列表项下面应该有多个子块吧。

**Comment by xfdj** [comment]
emmm我觉得完全不会放不下啊

![image](https://user-images.githubusercontent.com/38575841/141688538-195e1296-c258-4999-a820-9b4d3ef47f41.png)
这种效果不是挺好的吗？其实每次焦点都只会在一个块上，其它块的图标不会显示出来的吧。

> > 竖着显示图标的效果其实挺不错的，不知道可不可以作为左侧图标放不下的一个解决方案呢？
> 
> 竖着放的话下面有子块就放不下了。
> 
> > 另外其实在搜索里面当列表项下面只有一个子块时，还是会出现子块的块标菜单，如下所示。 ![image](https://user-images.githubusercontent.com/38575841/141289864-14d1588d-cf75-41bc-bdd1-61d9ed399c88.png) 从设计语言来说这其实也存在不统一的情况。
> 
> 这个列表项下面应该有多个子块吧。

这个举的例子确实有点问题，不过还是希望能够在只有一层嵌套的情况下全部显示图标。毕竟只是多一个图标的事，左侧该放不下还是放不下，该放得下多一个图标应该也问题不大。

另外在使用的过程中还发现，如果省略了里层的图标，列表项里是段落块的时候是没办法继续聚焦到段落块的（无论是用Ctrl+Click还是Alt+→都不行），所以里层的图标还是放出来好一点点~D大再考虑一下？

**Comment by 88250** [comment]
用快捷键选块，选中以后可以扩大或者减小选区。界面上的改动目前不考虑了，感谢反馈。
