### ISSUE TITLE
上传本地备份失败

### ISSUE THREAD

**Issue by xiaotoucai** [siyuan-note/siyuan#3389]
### 描述问题 Describe the problem

上传本地备份失败

### 期待的结果 Expected result

可以上传备份，安心使用

### 截屏或者录屏演示 Screenshot or screen recording presentation

错误信息：
upload failed: rsync: [sender] Failed to exec /cygdrive/C/Users/\#346\#242\#201\#346\#231\#250/Documents/SiYuan/temp/rsync/bin/ssh.exe/ -i 'C:\Windows\Temp\siyuan\key\hfjcopf' -4 -c aes256-gcm@openssh.com -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o BatchMode=yes -o PreferredAuthentications=publickey -o KexAlgorithms=diffie-hellman-group-exchange-sha256 -o Compression=no -o ConnectTimeout=7 : No such file or directory (2) rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.2.4dev] rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12

### 版本环境 Version environment

* Version: 1.4.6
* Operating system: win10 64
* Browser (if used):

**Comment by 88250** [comment]
请更新到最新版，并将工作空间路径设置在没有中文和空格的路径下。
