### ISSUE TITLE
支持文档块书签

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#339]
0.3.5

希望文档块也能添加到书签

**Comment by 88250** [comment]
目前遇到的问题是没有地方存储文档块书签，其他内容块是存储在 IAL 属性上的 `{ id:='xxx' bookmark='xxx'}`。文档块的 id 是在物理文件名上，这地方似乎不能放书签，因为书签标识可能会比较长。

这个属于整体方案设计的缺陷，暂时支持不了，以后如果单独存储元数据了倒是能够支持，所以先关闭了，感谢反馈。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/723 中进行文档块 id 重构，完成以后就可以支持文档块加书签了。
