### ISSUE TITLE
支持 HTML 块 - `<table>` 表格

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3394]
* 合并单元格
* 调整列宽
* 表格顶部标题、底部注释 https://ld246.com/article/1639190711965

**Comment by netdog2019** [comment]
表格对于很多人而言，几乎是每天都需要用的，如果能把表格加强，应该能吸引一大波新用户。

**Comment by wuqi** [comment]
好顶赞,table比markdown那个简易表格要好的多

**Comment by zilianghm** [comment]
让表格拖动宽度吧

**Comment by gslnzfq** [comment]
我目前遇到的问题：
1. 合并单元格目前不支持
2. 在单元格内部换行不支持

以上都是markdown表格不支持的，要是有html表格就更完美了

**Comment by Morganwan90** [comment]
来了来了终于来了~我笔记里全是表格

**Comment by remoon1991** [comment]
要是能和notion那样就太棒了，飞书新出的那个能加子任务，感觉很nice！
如果开发者有时间可以搞一搞

**Comment by 88250** [comment]
经过考虑，暂时不会加入 HTML 表格，而是对现有的表格进行增强改进：

* https://github.com/siyuan-note/siyuan/issues/4018
* https://github.com/siyuan-note/siyuan/issues/4022

后续考虑在 v1.9.0 尝试支持 HTML 标签 https://github.com/siyuan-note/siyuan/issues/4023
