### ISSUE TITLE
中西文中间自动插入空格BUG

### ISSUE THREAD

**Issue by fledgling-rjk** [siyuan-note/siyuan#3397]
### 描述问题 Describe the problem

开启中西文中间自动插入空格后，有时书写中西文混合的文本时不会自动插入空格

测试发现，当输入中西文时切换输入法会自动插入空格，但如果只使用汉语输入法，当需要输入英文时使用 enter 键的话不会自动插入空格

### 截屏或者录屏演示 Screenshot or screen recording presentation

![屏幕采集_20211113_160552](https://user-images.githubusercontent.com/58317245/141611211-e99646b1-a36a-41de-a012-a96243a69c01.gif)

### 版本环境 Version environment

* Version: 1.5.1
* Operating system: Windows 10
* Browser (if used): 

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/7531622/siyuan.log)

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/3363
