### ISSUE TITLE
生成静态站点

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#34]
单独启一个开源项目来做，让有在线发布静态站点需求的用户就可以通过这个工具来导出静态站点，自己部署 GitHub Pages 或者 Gitee Pages 之类的平台伺服。

**Comment by nn200433** [comment]
> 单独启一个开源项目来做，让有在线发布静态站点需求的用户就可以通过这个工具来导出静态站点，自己部署 GitHub Pages 或者 Gitee Pages 之类的平台伺服。
---
这功能 对于docker部署，并有域名的用户有点垃胯啊。docker部署的用户应该整个其它方案，比如选择某篇笔记直接公开为站点，没必要再导出了

**Comment by 88250** [comment]
@2234839 老铁，考虑把 https://github.com/2234839/md2website 迁移到社区组织下么？如果迁移的话，项目重命名为 `OceanPress` 如何？

**Comment by 2234839** [comment]
> 
> 
> @2234839 老铁，考虑把 https://github.com/2234839/md2website 迁移到社区组织下么？如果迁移的话，项目重命名为 `OceanPress` 如何？

我好像应该先重命名再迁移的，现在迁移了后我没有进设置页的权限了，要不你改一下名？

**Comment by 88250** [comment]
@2234839 感谢，已经设置完毕 🎉
