### ISSUE TITLE
MathJax 支持用 `\\` 换行

### ISSUE THREAD

**Issue by Infinemen** [siyuan-note/siyuan#340]
理科生，往往需要推导下公式，所以希望用一个块完成公式推导，这个时候就需要换行。谢谢，程序员辛勤工作。

**Comment by 88250** [comment]
麻烦补充一下 `\\` 的公式文本，我们对这块不熟悉，谢谢。

**Comment by Infinemen** [comment]
```
f=a+b+c+a=2a+b+c
```
显示为
![formula](https://user-images.githubusercontent.com/19859842/97243506-6f9daa80-1831-11eb-8af4-b639eb5cf597.jpg)
```
f=a+b+c+a \\ =2a+b+c
```
希望能显示为
![formula2](https://user-images.githubusercontent.com/19859842/97243621-b1c6ec00-1831-11eb-9261-dc615a69034b.jpg)

**Comment by 88250** [comment]
收到，谢谢。

**Comment by Vanessa219** [comment]
数学公式我们使用了 katex 和 mathjax，目前 katex 是支持 `\\` ，但 mathjax 就有问题，需要等待他们修复 https://github.com/mathjax/MathJax/issues/2312

**Comment by Infinemen** [comment]
谢谢

**Comment by Infinemen** [comment]
\\ 完整语法是  \\[行距] 来决定换行后两行之间的距离。默认比较窄，如果有比较高的符号 比如分数 积分号这种，默认行距两行会挨在一起。
等开发大大有时间来精雕细琢的时候，希望能把这个细节改一改。个人觉得 默认4-5px比较合适。 \\[4px] 或者 \\[5px]

**Comment by 88250** [comment]
v1.2.0 以后已经移除支持 MathJax 引擎，我关闭了。
