### ISSUE TITLE
中英文自动插入空格问题

### ISSUE THREAD

**Issue by fledgling-rjk** [siyuan-note/siyuan#3407]
### 描述问题 Describe the problem

1.5.2 版本后修复了 #3397 和 #3363 的问题，但现在先输入英文后再输入汉语不会自动插入空格

### 截屏或者录屏演示 Screenshot or screen recording presentation

![屏幕采集_20211115_094319](https://user-images.githubusercontent.com/58317245/141709462-5f29d3eb-3b02-439b-9e9d-4bf9d2a81abd.gif)

### 版本环境 Version environment

* Version: 1.5.2
* Operating system: Windows 10
* Browser (if used):

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/3363 中处理，感谢反馈。
