### ISSUE TITLE
增加设置插入代码块的快捷键

### ISSUE THREAD

**Issue by junmoxiao** [siyuan-note/siyuan#3409]
插入代码块是很常用的操作。希望能增加相关的快捷键设置，能一键插入，现在的方式得按好几下。 
 
要么是
```
```enter
```
要么是
```
/code回车
```
很不方便，现在只有设置插入行内代码块的快捷键

**Comment by halavah** [comment]
Typora用户认为，保持 Ctrl + Shift + K  快捷键，很有用😁

**Comment by junmoxiao** [comment]
> Typora用户认为，保持 Ctrl + Shift + K 快捷键，很有用😁

也行， Ctrl + Shift + K 挺好的，关键是现在没插入代码块的快捷键给我用呀
