### ISSUE TITLE
丰富表格功能

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#341]
希望在建立表格时可以自定义行列数，而不是总为默认的3*3；此外希望能增加合并单元格等功能。

**Comment by 88250** [comment]
你好，表格功能目前可以通过快捷键进行编辑；合并单元格估计支持不了，因为 Markdown 没有这语法……

表格的可视化操作请关注 https://github.com/siyuan-note/siyuan/issues/39

感谢反馈！

**Comment by 2016201256** [comment]
![微信图片_20201027100910](https://user-images.githubusercontent.com/58763608/97248346-8eee0500-183c-11eb-9dca-fdc9658167e2.jpg)
感谢您的回复！或许合并单元格可以参考一下vscode插件Markdown Preview Enhanced的方法（如图所示），不知道是否容易实现

**Comment by 88250** [comment]
感谢感谢，稍后研究 👍
