### ISSUE TITLE
列表项的线 无法对齐，且若颜色不一致会显示两种颜色

### ISSUE THREAD

**Issue by lvzhp** [siyuan-note/siyuan#3414]
![image](https://user-images.githubusercontent.com/71172482/141742351-907244fc-a5ae-4252-969c-a8283f5d2d97.png)

![image](https://user-images.githubusercontent.com/71172482/141742450-d350712b-8810-467d-b70d-1277e90df30f.png)
如上图

**Comment by lvzhp** [comment]
![image](https://user-images.githubusercontent.com/71172482/141743555-fc7f24e4-7216-46d1-a841-14ab48625056.png)

**Comment by Vanessa219** [comment]
无法重现，请使用默认主题，如还有问题请发一下 .sy 文件。
![image](https://user-images.githubusercontent.com/970828/142006128-6e59e092-527d-4628-afa1-2840c9c63360.png)

**Comment by lvzhp** [comment]
[20211115152207-dm4ab73.zip](https://github.com/siyuan-note/siyuan/files/7552353/20211115152207-dm4ab73.zip)
@Vanessa219

**Comment by lvzhp** [comment]
默认主题也会如此，只是不明显罢了。

**Comment by lvzhp** [comment]
已经排查出来原因了~
是标题样式的锅~

**Comment by lvzhp** [comment]
border-bottem   
border-left
均不可使用，否则会造成上面的情况。
而且我试验了多个主题，均是这几个元素导致的对不齐，或者 颜色不一致效果

**Comment by lvzhp** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
用 box-shadow 试试？默认主题没有问题的话，我先关闭该 issue 了，还有问题可以继续留言。
