### ISSUE TITLE
粘贴时代码块缩进和设置的不一样

### ISSUE THREAD

**Issue by ACGLife** [siyuan-note/siyuan#3415]
### 描述问题 Describe the problem

输入时可以实现设置的空格数缩进效果而粘贴时是以8个空格为缩进

### 期待的结果 Expected result

粘贴时可以按设置的空格数缩进

**Comment by 88250** [comment]
目前代码块编辑器方面的问题我们暂时不做修复和改进了，后期计划会做一次全面重制，请关注 https://github.com/siyuan-note/siyuan/issues/3141
