### ISSUE TITLE
check-auth 界面提供关闭按钮

### ISSUE THREAD

**Issue by Jed-Z** [siyuan-note/siyuan#3417]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

希望从局域网其他机器远程访问思源时，在本机只是需要打开思源内核，这时希望可以在启动思源后直接关闭（最小化到托盘）。

### 描述可能的最优解决方案 Describe the optimal solution

在 check-auth 界面增加最小化、最大化、关闭按钮。

**Comment by 88250** [comment]
直接启动内核即可，需要加上一些启动参数，具体请参考帮助文档启动参数章节，谢谢。
