### ISSUE TITLE
支持配置文本对齐方式

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#3419]
In the program, we already have the layout "**left**", "**center**" and "**right**".
I would love the "**justify**" layout incrementing, where the letters end on the same position

Left Layout:
![image](https://user-images.githubusercontent.com/90691302/141776610-eb0ccba4-9293-43e3-b9ab-d799383e7f34.png)

Justify Layout:
![image](https://user-images.githubusercontent.com/90691302/141776374-ef5be3d3-e0f0-42d6-8553-9c44d67a7d08.png)

The text ends at the same position for all lines. This gives a more formal and beautiful look to other languages. In addition to helping to make reading more enjoyable.

Icon for layout justify:
![image](https://user-images.githubusercontent.com/90691302/141776776-757f4725-54b5-42dc-9865-3d2f3ee8571e.png)

**Comment by Crowds21** [comment]
a great enhancement to the current left/right layout

**Comment by Vanessa219** [comment]
This layout setting may need to be changed to be global, which would be cumbersome to do for every block.

**Comment by choyy** [comment]
这个可以默认开启吗

**Comment by 88250** [comment]
@choyy 目前不行，如果需要的话请重新开 issue，谢谢。
