### ISSUE TITLE
块引搜索类型过滤

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#342]
通过搜索关键字前缀进行过滤：

* `((d` 文档块
* `((#` 标题块
* `((*` 列表块（包含有序列表块、无序列表块和任务列表块）
* `` ((` `` 代码块
* `((>` 块引用块
* `(($` 数学公式块
* `((p` 段落块

**Comment by lss6378** [comment]
## 建议支持文档块过滤
- 比如 `((d` 搜索过滤搜索文档块名称(包括文件名和关键字前缀)
- 文件名搜索和引用是非常常见的哦

**Comment by lss6378** [comment]
## 搜索过滤列表菜单
- `((/`弹出类型过滤列表，鼠标/按键选择后切换到对应类型
##  *我来*  
![图片](https://user-images.githubusercontent.com/15924513/97296022-0f3b5700-188b-11eb-8258-0b132d02e724.png)

## RE
![图片](https://user-images.githubusercontent.com/15924513/97296206-4e69a800-188b-11eb-9481-dce3a948b497.png)

**Comment by 88250** [comment]
@lss6378 

* `((d` 已经加入
* 交互界面暂时不做了

感谢建议！
