### ISSUE TITLE
mac同步后出现无文字横幅

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3421]
在公司操作后，回家重新打开思源，发现在公司写的笔记没有同步下来，就点菜单那里的同步，然后就出现这个了

![image](https://user-images.githubusercontent.com/33319484/141793018-22c2c2b8-baf0-4c13-9db4-3c35e2b52300.png)

version：1.5.1

**Comment by 88250** [comment]
应该是有字的：工作空间目录路径请勿包含和空格。

这个可能和自定义主题配色有点冲突，导致看不清楚。

**Comment by JokeenZhang** [comment]
公司用的版本是1.5.2，每次打开电脑都会先看看有没有更新，所以是会出现这种软件版本不一致的现象。不知道这个问题会不会跟这样的使用习惯有关

**Comment by 88250** [comment]
目前思源还处于快速迭代开发阶段，请尽量保持最新版。

**Comment by JokeenZhang** [comment]
切换至自带主题后，横幅的信息是这样的

![image](https://user-images.githubusercontent.com/33319484/141794859-86c1c835-d654-4a32-b4ee-61f8f34f3608.png)

一直以来都是用中文路径的，怎么现在就突然不行了呢

**Comment by 88250** [comment]
v1.4.5 以后不再支持中文路径 https://github.com/siyuan-note/siyuan/issues/3205

**Comment by JokeenZhang** [comment]
好的，了解
