### ISSUE TITLE
支持字体字重设置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3423]
https://ld246.com/article/1637024799454

**Comment by 88250** [comment]
需求不强烈，暂时不考虑了，先做其他任务。

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/10313

**Comment by QQQOrange** [comment]
> 关联 #10313

啊 所以直接毙了 不做吗？非常影响体验啊

**Comment by 88250** [comment]
@QQQOrange 这个 issue 是很早以前就提的了，我关联一下。

**Comment by QQQOrange** [comment]
> @QQQOrange 这个 issue 是很早以前就提的了，我关联一下。

嗷嗷嗷
