### ISSUE TITLE
支持对图片和链接的标题进行搜索

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#3427]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在可预见的未来应该不会加入图片OCR与图片内容搜索, 因此我打算合理利用图片的标题与提示文本对图片内容进行标注, 以方便对图片进行搜索, 但经过测试, 目前仅支持对提示文本进行搜索

### 描述可能的最优解决方案 Describe the optimal solution

同时支持对图片标题与提示文本的搜索

**Comment by 88250** [comment]
超链接也有标题部分，一加就只能都加了 :joy:
