### ISSUE TITLE
Change colors background text

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#3428]
The colors of the markings are very dark and barely noticeable. I always use the "eye protection" available in Windows to reduce screen glare. Therefore, colors are very difficult to see in Siyuan's "night theme". In the "light theme" the colors are easy to see.

![image](https://user-images.githubusercontent.com/90691302/142003436-7162b0f4-bc5d-482e-b71f-5b61c2ddd419.png)

In the image I put the colors red, orange, blue and green. I don't know for the other users, but for me they are very faded. Very much!
I would like to suggest changes to the brightness of the colors for those who are more visible.

**Comment by Vanessa219** [comment]
As shown in the figure below, you need to use it with the foreground color
![image](https://user-images.githubusercontent.com/970828/142343929-fcb66d9c-3549-40b2-a16f-fabed5bc1a86.png)
