### ISSUE TITLE
块引用搜索排序算法优化

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#343]
可以考虑加个自定义搜索优先级的概念.
- 例如我搜索`A`,出现结果有`A0`, `A1`, `A2`, `A4`...等十几条结果, 但大多数情况下我希望`A2`的结果出现在最前面, 通过右键对该块调整搜索优先级, "0%"为最高优先级, "100%"为最低优先级.
- 或者对于锚文本相同的块, 它们搜索关键字(锚文本)是一样的, 用自定义搜索优先级能提供更高效的搜索结果排序(对不擅长使用正则的小白用户来说).

**Comment by 88250** [comment]
搜索排序目前是按引用数来评分的，后续会加入更多权重项，应该包括：

* 书签
* 备注

手动赋予权重应该也行，但是使用起来可能稍有麻烦，还需要考虑一下。

**Comment by 88250** [comment]
目前已经按类型进行了排序，后面会逐步微调。
