### ISSUE TITLE
无法显示pdf中的批注

### ISSUE THREAD

**Issue by sunshineharry** [siyuan-note/siyuan#3432]
# 版本信息
思源笔记： 1.5.2（目前最新版）
windows： win11
# 问题描述
**无法显示PDF中的手写批注**
正常pdf阅读器显示：
![image](https://user-images.githubusercontent.com/52942042/142097162-80427a4f-9c51-46b4-9022-2138657ce360.png)
思源笔记显示：
![image](https://user-images.githubusercontent.com/52942042/142097223-1fb0a27d-8667-4ad9-aaf0-6c2f64d4b8cf.png)
源文件：
[特征值与特征向量.pdf](https://github.com/siyuan-note/siyuan/files/7551190/default.pdf)

**求修复**

**Comment by 88250** [comment]
你好，已有 PDF 的注解不支持显示的。
