### ISSUE TITLE
代码块增加none无样式的选项

### ISSUE THREAD

**Issue by halavah** [siyuan-note/siyuan#3435]
![样式问题](https://user-images.githubusercontent.com/55541070/142166202-38abfb65-477a-4d6c-9827-8818650ee882.png)
我喜欢直接在代码块中，以自己的“格式”来记录笔记，但是默认dos格式，希望能更typora一样可以设置none

**Comment by 88250** [comment]
请使用 `plaintext` 作为高亮语言。

![image](https://user-images.githubusercontent.com/873584/142167505-32b9628e-2938-41d6-a6f9-47fb5978b955.png)

**Comment by 88250** [comment]
选择高亮语言以后，这个值就会作为下一次使用时代码块的默认值。
