### ISSUE TITLE
将TAB缩进转换为连续空格

### ISSUE THREAD

**Issue by halavah** [siyuan-note/siyuan#3436]
虽然TAB可以快速分割文字，但TAB在某些程序中打开会出现问题
--
建议【类似VScode、Sublime】保存后，默认将 TAB 全部转换为 空格

**Comment by Vanessa219** [comment]
设置中可对 tab 进行配置。后续输入 tab 的时候就会为空格了

**Comment by 88250** [comment]
我先关闭了，如果还有问题请跟帖，谢谢。
