### ISSUE TITLE
文件夹路径过长

### ISSUE THREAD

**Issue by aptexd** [siyuan-note/siyuan#3448]
### 描述问题 Describe the problem
Windows11移动整个工作空间.siyuan文件夹中有文件夹显示路径太长无法移动，删除也无法放入回收站，只能永久删除

### 期待的结果 Expected result
正常移动工作空间

### 版本环境 Version environment

* Version: 
* Operating system: Windows 11
* Browser (if used):

**Comment by 88250** [comment]
能找到太长的路径是什么样的吗？

**Comment by aptexd** [comment]
因为已经删除，所以找不到了，在OneDrive的回收站也无法显示全部路经，不过i查Windows官方文档，应该是文件夹命名长度和文件夹层数同时触发的这个问题，这是在微软官方找到的文档，也不排除是Windows11的问题
[最大路径长度限制](https://docs.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)

> 能找到太长的路径是什么样的吗？

**Comment by aptexd** [comment]
如果按照这个文档中路经260个字符问题，那我感觉当时应该已经超过了

**Comment by 88250** [comment]
明白了，这个我们后面加个文档树层级限制，感谢反馈。

**Comment by 88250** [comment]
好像不大对劲，那个文档中提到的是 Windows API 的最大长度限制，而系统本身好像支持很大，所以实际上我们好像可以不限制。

不过不限制的话就可能遇到你之前的问题，在文件系统上复制或者移动文件时会报错。这个我觉得我们暂时先不改吧，因为按照 260 个字符来看的话，层级可能不够用。

我关闭了，后面如果有其他人也遇到这个问题，会关联到这里重新考虑，谢谢。
