### ISSUE TITLE
浏览器中使用思源外链图片无法显示， 客户端正常显示

### ISSUE THREAD

**Issue by feima1992** [siyuan-note/siyuan#3449]
### 描述问题 Describe the problem
浏览器中使用思源外链图片无法显示， 客户端正常显示

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
有的图片网站做了反盗链（比如微信公众号），所以在标准浏览器环境下是无法加载的。思源桌面端做了单独的处理，所以可以显示。

我关闭了，感谢反馈。
