### ISSUE TITLE
代码块如果是markdown, 空格会变成换行

### ISSUE THREAD

**Issue by lvzhp** [siyuan-note/siyuan#3450]
![1](https://user-images.githubusercontent.com/71172482/142583194-9534d47e-6bf7-4388-9809-4820e34e54d9.gif)
如图

**Comment by 88250** [comment]
麻烦帖一下该代码块源码，谢谢。

**Comment by lvzhp** [comment]
[20211119143755-f7eutjl.zip](https://github.com/siyuan-note/siyuan/files/7581520/20211119143755-f7eutjl.zip)
@88250 
最后一个代码块

**Comment by 88250** [comment]
感谢提供测试数据，已经可以重现问题。

**Comment by 88250** [comment]
这个问题我们以后在 https://github.com/siyuan-note/siyuan/issues/3141 中处理吧，感谢反馈。
