### ISSUE TITLE
微信提醒推送

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3457]
https://ld246.com/article/1637335249851

推送方式：微信服务号 `B3log开源`

![image](https://user-images.githubusercontent.com/873584/145057194-e9bb80a4-c22c-4707-aae1-c3cd37bf3f69.png)

工作原理：

1. 将需要设置提醒的内容块文本内容明文发送到云端
2. 云端定时轮询，发现需要推送的文本以后推送到绑定的微信

**Comment by SineMark2020** [comment]
会用到云，这项或许可以当订阅功能了

**Comment by 88250** [comment]
@SineMark2020 嗯，这个功能将会是订阅功能。

**Comment by qifengle1998** [comment]
好家伙，这是准备要把清单类app的饭碗抢了

**Comment by remoon1991** [comment]
如果可能，后续可以出类似“我的印象笔记”那种，将公众号链接复制进去，就可以剪藏的功能。

**Comment by Crowds21** [comment]
会开放专门接口,用于获取设置了提醒的文本吗?

**Comment by bigonestep** [comment]
非常期待这个功能，甚至可以说，加入这个功能，思源笔记就真正完整了。

**Comment by nijun1993** [comment]
此功能一出，思源的格局就有了，订阅也有了，一举两得。

**Comment by legend053** [comment]
很好。微信能否发消息给思源？

**Comment by 88250** [comment]
@legend053 微信等输入后面会实现的，大致的考虑是一个纯云端功能，在思源里面直接套壳打开云端页面，这个页面类似邮箱的收件箱（Inbox），其中的数据只能查看、删除和发送到笔记本。

以微信举例使用流程：微信公众号输入、打开思源云端 Inbox，浏览需要的信息并发送到笔记本进行整理，删除信息。
