### ISSUE TITLE
Docker 部署出现websocket问题

### ISSUE THREAD

**Issue by hoorayui** [siyuan-note/siyuan#3459]
### 描述问题 Describe the problem
阿里云机器部署docker遇到错误

按照帮助文档步骤操作 执行 docker run -v /siyuan/workspace:/siyuan/workspace -p 6806:6806 -u 1000:1000 b3log/siyuan --workspace=/siyuan/workspace/

docker有ws相关报错，

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/13306725/142738624-76f1489b-311d-4932-baaa-4b1d386c05db.png)

docker logs 提示 在get version meta info之前就报了

![image](https://user-images.githubusercontent.com/13306725/142738637-eb3100b0-4187-4e06-9547-14f4c59d393d.png)
### 版本环境 Version environment

* Version: 1.5.3
* Operating system: OpenSUSE Leap 15.3
* Browser (if used): Edge 95.0.1020.53

### 日志文件 Log File

![image](https://user-images.githubusercontent.com/13306725/142738936-07921ea2-9634-4f41-84bb-12d11685e87d.png)

**Comment by 88250** [comment]
使用了 NGINX 的话需要用 WebSocket 反代 `/ws`。

**Comment by hoorayui** [comment]
> 使用了 NGINX 的话需要用 WebSocket 反代 `/ws`。

哇，太棒了！！！成功运行了，是我大意了，没注意到文档的这句
(第一次提Issue，感谢作者回复，^_^)

**Comment by wyfang** [comment]
@88250 @hoorayui 同样问题，新手求问最后的 /ws 是啥意思？

我是这样的：
docker run --restart=always -v /home/siyuan/workspace:/siyuan/workspace -p 127.0.0.1:6806:6806 -u 1000:1000 b3log/siyuan --workspace=/siyuan/workspace/

**Comment by rabbitlhf** [comment]
> 

如果使用 apache 怎么配置呢？
