### ISSUE TITLE
任务列表项中嵌入内容块问题

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#346]

**Comment by 88250** [comment]
上面这个位置不行，下面的可以。你说的是上面的情况吗？

![image](https://user-images.githubusercontent.com/873584/97404102-824ad900-1930-11eb-9575-dca1fd500f91.png)

**Comment by Asasahn** [comment]
是的 不过我发现把上面的嵌入删掉部分 下面的嵌入也会消失发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2020年10月28日周三 15:16收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asasahn <1026411669@qq.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 在todo列表中 无法正常嵌入内容块 (#346)

上面这个位置不行，下面的可以。你说的是上面的情况吗？

**Comment by 88250** [comment]
这个问题有点复杂，我们先解决普通列表项中嵌入块的问题 https://github.com/siyuan-note/siyuan/issues/364
