### ISSUE TITLE
快捷键修改

### ISSUE THREAD

**Issue by corwin1949** [siyuan-note/siyuan#3468]
macos 11.6，客户端版本 V1.5.3

快捷键 home 可以移动到行首，而 快捷键 end 无法移动到行末，变成了移动到页面底部。

另：行首行末的快捷键可以改成 com + 左右方向键 吗，因为这个快捷键是浏览器以及许多编辑器通用的快捷键，我常常不自觉使用它，但它是无效的。
改成 com + 左右方向键，或许更符合用户的使用直觉。

---
最后，感谢开发了这么好用的思源笔记。

**Comment by Vanessa219** [comment]
- [ ] <kbd>⌘→</kbd> => <kbd>⌘]</kbd>
- [ ] <kbd>⌘←</kbd> => <kbd>⌘[</kbd>
- [ ] <kbd>⌘[</kbd> => <kbd>⌥[</kbd>

**Comment by Vanessa219** [comment]
@corwin1949 目前可以在快捷键中重新这是前进后退按钮来解决

**Comment by corwin1949** [comment]
> @corwin1949 目前可以在快捷键中重新这是前进后退按钮来解决

太好了，删除了前进后退的快捷键，成功了。感谢!
