### ISSUE TITLE
多选选中区域问题

### ISSUE THREAD

**Issue by gqzcl** [siyuan-note/siyuan#3474]
#### 开始选中区域

![image](https://user-images.githubusercontent.com/43192463/142986181-62000764-e236-487a-89c4-ee36e48169d2.png)

#### 鼠标滚轮向下滚动后选中区域停留在原处

![image](https://user-images.githubusercontent.com/43192463/142986240-cc44ca96-4958-4788-b77e-32f6bf8f7fd9.png)

### 期待的结果 Expected result

**选中区域应该是跟随鼠标滚轮的**

#### 初始选中区域
![image](https://user-images.githubusercontent.com/43192463/142986559-a2e46bfd-3671-469f-8b3c-14f817ec81e9.png)

#### 滚轮向下滚动后
![image](https://user-images.githubusercontent.com/43192463/142986596-4d642cfa-a893-4f80-bf75-5864cc77ceb7.png)

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/2066
