### ISSUE TITLE
双列块导出PDF、html后变成两行

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3478]
两个块合并成水平排列的块，变成两列。导出pdf 或者html后变成了单列两行了。

笔记：
![image](https://user-images.githubusercontent.com/15650275/143151972-679d6070-8d88-4aa6-9e58-8f61c782b48e.png)

导出后
![image](https://user-images.githubusercontent.com/15650275/143152012-ec790c58-5022-4b58-b7ec-7ba0c0851237.png)

**Comment by 88250** [comment]
感谢反馈，合并到 https://github.com/siyuan-note/siyuan/issues/3104 中处理。
