### ISSUE TITLE
自定义表情支持网络图片URL导入

### ISSUE THREAD

**Issue by nicollcheng** [siyuan-note/siyuan#3480]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在使用自定义的图标时，需要将网络图片下载，并放在指定目录下后，还需要刷新，若在编写文章时，不实需要使用自定义图标，这样的步骤下来就非常令人烦恼

### 描述可能的最优解决方案 Describe the optimal solution

网络导入URL时，将图片下载到指定目录，在用户无感知的情况下，自动后台刷新

**Comment by 88250** [comment]
感谢提议，但是暂时不考虑了，图标文件夹需要有特定的目录 ，网络下载的话无法保证结构是否正确。

**Comment by nicollcheng** [comment]
那么是否可以支持网络路径图片展示以及集成Unsplash，类似Notion中如下功能
![image](https://user-images.githubusercontent.com/64319004/143389158-3d54bc57-c4e2-41a9-9c7c-56c065a28db0.png)

**Comment by 88250** [comment]
@nicollcheng 请关注 https://github.com/siyuan-note/siyuan/issues/2951
