### ISSUE TITLE
反向链接面板计入文档自身引用

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3486]

**Comment by whuwangyong** [comment]
反链面板现在不展示自身引用了吗？
![image](https://user-images.githubusercontent.com/5968678/169961513-97271922-fbbe-4d69-9683-ce1d2c4fdac5.png)

Windows + v2.0.6 

我是倾向于不展示自身引用的，所以这样挺好，我只是确认一下。
btw，正文里面的引用计数是不是也不展示自己呢？

**Comment by 88250** [comment]
* 反链面板已经排除自身引用
* 文档标题这里要包含，和文档树一致
