### ISSUE TITLE
点击笔记本导出后出现导出中就没有下文了

### ISSUE THREAD

**Issue by SeyeeL** [siyuan-note/siyuan#3491]
尝试了win和mac英特尔的1.4.8，mac M1的1.5.3都是一样，请问导出的文件在哪

**Comment by 88250** [comment]
麻烦提供一下日志文件：工作空间/temp/siyuan.log

**Comment by 88250** [comment]
应该和 https://github.com/siyuan-note/siyuan/issues/3493 是一个问题，先关闭了。

**Comment by SeyeeL** [comment]
这是M1的

**Comment by SeyeeL** [comment]
[siyuan.log.zip](https://github.com/siyuan-note/siyuan/files/7603880/siyuan.log.zip)

**Comment by 88250** [comment]
@SeyeeL 从日志上看，这个问题应该在内测版上修复了。
