### ISSUE TITLE
M1,v1.5.3,笔记本会偶尔打不开，软件也无法退出

### ISSUE THREAD

**Issue by SeyeeL** [siyuan-note/siyuan#3493]
https://user-images.githubusercontent.com/71479570/143463664-46727f5b-e6bf-4a70-bae3-f49d28f13284.mov

**Comment by 88250** [comment]
这个问题我们会在下个版本修复，感谢反馈。

**Comment by 88250** [comment]
对了，我能邀请你加入内测吗？帮忙测试一下目前你碰到的问题是否已经在内测版上修复。

**Comment by SeyeeL** [comment]
好，可以

**Comment by 88250** [comment]
好了，已经邀请了，内测仓库是 https://github.com/siyuan-note/insider

**Comment by SeyeeL** [comment]
![image](https://user-images.githubusercontent.com/71479570/143519021-cc96a42d-ed96-43e5-b29f-5002e8f225e1.png)
好像看不到

**Comment by 88250** [comment]
你还没有接受邀请哦：

![image](https://user-images.githubusercontent.com/873584/143519846-a958a682-3ee1-4c97-8624-d93d1c1765e1.png)

在 https://github.com/siyuan-note 这里看下，界面上应该会有提示接受邀请。

**Comment by SeyeeL** [comment]
@88250 内测版已经解决这个问题和导出无响应的问题。macM1和win10都可以了。

**Comment by 88250** [comment]
@SeyeeL 感谢帮忙测试，这两天内就会发布 v1.5.4 正式版。
