### ISSUE TITLE
类似 MediaWiki 的「键值对」信息框

### ISSUE THREAD

**Issue by whitepecan** [siyuan-note/siyuan#3494]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

你好！

对于笔记本内的一些文档，需要重复键入同样一组信息。

例如，建立一个笔记本记录学生信息，其中每个文档记录一个学生。每个文档当中都需要同样一组信息，如姓名、性别、出生日期等。

模板可以解决一次性的问题，但是未来也许需要给所有学生添加一种新类型的信息，这种信息在最初记录的时候没有考虑到，因此模板内原先没有，而更新模板并不能相应地自动更新所有使用了该模板的场合。

### 描述可能的最优解决方案 Describe the optimal solution

如果有类似 MediaWiki 的「键值对」信息框，每次需要新增信息时只需在模板中新增一个键（key），同时所有使用了模板信息框的地方都会自动添加该键，而用户只需自行输入该键所对应的值（value）就可以了。

### 描述候选的解决方案 Describe the candidate solution

使用模板，并在每次需要时手动更新所有页面。

### 其他信息 Other information

MediaWiki 的信息框基本原理类似于由键值对组成的 n 行 2 列的表格，并且第 2 列的信息可以包含图片等多媒体。除此之外，信息框顶端包含当前页面的名称，而且可以将多个行分为一组，组名独占一行。如下图所示。

![图片](https://user-images.githubusercontent.com/95060019/143514887-7fc14797-704e-46c1-ad93-73544f449b48.png)

谢谢！

**Comment by 88250** [comment]
你好，我对 MediaWiki 不太熟悉。从思源来说，这个需求应该可以通过块属性来实现，但是目前 https://github.com/siyuan-note/siyuan/issues/2829 还没有具体的开发时间，可能会在 v2.0 以后才考虑。

另外，也可以考虑等社区开发者提供挂件来支持，但是都要再等等看……

我关闭了，如果需要继续讨论的话欢迎随时跟帖，谢谢。

**Comment by whitepecan** [comment]
> 你好，我对 MediaWiki 不太熟悉。从思源来说，这个需求应该可以通过块属性来实现，但是目前 #2829 还没有具体的开发时间，可能会在 v2.0 以后才考虑。
> 
> 另外，也可以考虑等社区开发者提供挂件来支持，但是都要再等等看……
> 
> 我关闭了，如果需要继续讨论的话欢迎随时跟帖，谢谢。

多谢你的回复！

如果用块属性来记录信息的话，有什么方式可以将块属性的键和值直接显示到笔记本的正文当中吗？

**Comment by 88250** [comment]
上面已经说了：

* 等 #2829 
* 等社区挂件

**Comment by whitepecan** [comment]
> 上面已经说了：
> 
>     * 等 [属性视图 #2829](https://github.com/siyuan-note/siyuan/issues/2829)
> 
>     * 等社区挂件

谢谢！我理解了。
