### ISSUE TITLE
当前输入法是中文时，自定义快捷键不生效

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3496]
我把锁屏快捷键设置为 `shift + q`，但是当我在中文状态下使用该快捷键时，会直接在思源编辑器中输出“Q”，而不是达到我预想中的锁屏效果。

![image](https://user-images.githubusercontent.com/33319484/143523926-b43656c7-f077-492b-8949-b20e2822fe29.png)

需要先切换为英文输入法，才会生效

以下是设置快捷键页面
![image](https://user-images.githubusercontent.com/33319484/143523966-453fae85-f46c-41cd-9c32-df57de1d3444.png)

思源版本是1.5.3，在win10下运行

**Comment by Vanessa219** [comment]
这个是操作系统输入法的设定，优先为大写转换。你换个快捷键吧。
