### ISSUE TITLE
停靠栏面板支持鼠标悬停展开

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#3499]
https://ld246.com/article/1637906203921

**Comment by Elliootalderson** [comment]
终于来了,等到白头了

**Comment by roverway** [comment]
期待已久的特性啊，1.2之前就希望有了。

**Comment by Soltus** [comment]
@Vanessa219 
左右dock激活项应当互不影响，不然用户操作步骤会增加
`getAll.ts`中forEach前需要判断，不然首次进入会报错
```ts
...data?.forEach...
```
```ts
export const getAllDocks = () => {
    const docks: IDockTab[] = [];
    window.siyuan.config.uiLayout.left.data?.forEach((item: IDockTab[]) => {
        item.forEach((dock: IDockTab) => {
            docks.push(dock);
        });
    });
    window.siyuan.config.uiLayout.right.data?.forEach((item: IDockTab[]) => {
        item.forEach((dock: IDockTab) => {
            docks.push(dock);
        });
    });
    window.siyuan.config.uiLayout.top.data?.forEach((item: IDockTab[]) => {
        item.forEach((dock: IDockTab) => {
            docks.push(dock);
        });
    });
    window.siyuan.config.uiLayout.bottom.data?.forEach((item: IDockTab[]) => {
        item.forEach((dock: IDockTab) => {
            docks.push(dock);
        });
    });
    return docks;
};
```

**Comment by Vanessa219** [comment]
@Soltus 稍等，还没写完，欢迎 close 后再来测试。谢谢 😊

**Comment by Soltus** [comment]
@Vanessa219  还有一个小建议，我使用模态弹窗时，停靠栏仍响应鼠标悬停展开，虽然目前看不出来有什么负面影响

**Comment by mozhux** [comment]
这个钉住的按钮建议再优化一下，比如语雀那样的，和savor主题那样的，在边栏上增加缩进按钮即可
![image](https://user-images.githubusercontent.com/46953371/218325141-78e1c7ab-6798-4c27-aac1-441de5f92440.png)

**Comment by royc01** [comment]
![image](https://user-images.githubusercontent.com/38906705/218348331-2d9c1d38-a1cd-4abe-b052-e1746227e18f.png)
建议悬浮后侧栏不遮挡页签和面包屑，隐藏dock栏时触发区域跟页签和面包屑重叠

**Comment by Vanessa219** [comment]
> @Vanessa219 还有一个小建议，我使用模态弹窗时，停靠栏仍响应鼠标悬停展开，虽然目前看不出来有什么负面影响

模态弹窗指的是？

**Comment by Vanessa219** [comment]
> 这个钉住的按钮建议再优化一下，比如语雀那样的，和savor主题那样的，在边栏上增加缩进按钮即可 ![image](https://user-images.githubusercontent.com/46953371/218325141-78e1c7ab-6798-4c27-aac1-441de5f92440.png)

如果面板都是关闭状态放在 dock 栏上可能会有点奇怪

**Comment by Soltus** [comment]
> > @Vanessa219 还有一个小建议，我使用模态弹窗时，停靠栏仍响应鼠标悬停展开，虽然目前看不出来有什么负面影响
> 
> 模态弹窗指的是？

我自己写的，类似于思源的全局搜索界面

**Comment by Vanessa219** [comment]
> ![image](https://user-images.githubusercontent.com/38906705/218348331-2d9c1d38-a1cd-4abe-b052-e1746227e18f.png) 建议悬浮后侧栏不遮挡页签和面包屑，隐藏dock栏时触发区域跟页签和面包屑重叠

上下分屏后页签和面包屑位置不固定，没有办法进行躲避。

**Comment by royc01** [comment]
> > 这个钉住的按钮建议再优化一下，比如语雀那样的，和savor主题那样的，在边栏上增加缩进按钮即可 ![image](https://user-images.githubusercontent.com/46953371/218325141-78e1c7ab-6798-4c27-aac1-441de5f92440.png)
> 
> 如果面板都是关闭状态放在 dock 栏上可能会有点奇怪

但是关闭dock 栏，面板就不能使用钉住了

**Comment by Vanessa219** [comment]
> > > @Vanessa219 还有一个小建议，我使用模态弹窗时，停靠栏仍响应鼠标悬停展开，虽然目前看不出来有什么负面影响
> > 
> > 
> > 模态弹窗指的是？
> 
> 我自己写的，类似于思源的全局搜索界面

用的是 dialog 标签？

**Comment by Vanessa219** [comment]
> > > 这个钉住的按钮建议再优化一下，比如语雀那样的，和savor主题那样的，在边栏上增加缩进按钮即可 ![image](https://user-images.githubusercontent.com/46953371/218325141-78e1c7ab-6798-4c27-aac1-441de5f92440.png)
> > 
> > 
> > 如果面板都是关闭状态放在 dock 栏上可能会有点奇怪
> 
> 但是关闭dock 栏，面板就不能使用钉住了

这样的话在有面板的 dock 栏处都需要一直显示的浮动图标，会不会太干扰界面？

**Comment by royc01** [comment]
> > > > 这个钉住的按钮建议再优化一下，比如语雀那样的，和savor主题那样的，在边栏上增加缩进按钮即可 ![image](https://user-images.githubusercontent.com/46953371/218325141-78e1c7ab-6798-4c27-aac1-441de5f92440.png)
> > > 
> > > 
> > > 如果面板都是关闭状态放在 dock 栏上可能会有点奇怪
> > 
> > 
> > 但是关闭dock 栏，面板就不能使用钉住了
> 
> 这样的话在有面板的 dock 栏处都需要一直显示的浮动图标，会不会太干扰界面？

我之前主题做的方案是面板hover状态才出现这个图标

**Comment by mozhux** [comment]
> > > > 这个钉住的按钮建议再优化一下，比如语雀那样的，和savor主题那样的，在边栏上增加缩进按钮即可 ![image](https://user-images.githubusercontent.com/46953371/218325141-78e1c7ab-6798-4c27-aac1-441de5f92440.png)
> > > 
> > > 
> > > 如果面板都是关闭状态放在 dock 栏上可能会有点奇怪
> > 
> > 
> > 但是关闭dock 栏，面板就不能使用钉住了
> 
> 这样的话在有面板的 dock 栏处都需要一直显示的浮动图标，会不会太干扰界面？

不需要一直显示的浮动图标的。鼠标放上去才有，可以使用一下savor主题体验一下。
默认是这样
![image](https://user-images.githubusercontent.com/46953371/218361818-a63c9011-fcb1-43fd-b08d-74ba4fc8fd45.png)
悬浮是这样
![image](https://user-images.githubusercontent.com/46953371/218361895-8b5ecce1-aa06-4bd6-9c80-4485f36df538.png)
悬浮后是这样，鼠标放在最左或最后会显示出来悬浮，和目前的官方的一一致。
![image](https://user-images.githubusercontent.com/46953371/218361955-19f8c580-4fd3-4e18-8c17-366440ec74d8.png)

**Comment by royc01** [comment]
> > ![image](https://user-images.githubusercontent.com/38906705/218348331-2d9c1d38-a1cd-4abe-b052-e1746227e18f.png) 建议悬浮后侧栏不遮挡页签和面包屑，隐藏dock栏时触发区域跟页签和面包屑重叠
> 
> 上下分屏后页签和面包屑位置不固定，没有办法进行躲避。

可以先考虑单屏的情况，上下分屏的频率低一点

**Comment by Soltus** [comment]
> 用的是 dialog 标签？

差不多吧，使用的是UI库的Modal组件。虽然目前看没有副作用，但由于遮罩是半透明的，停靠栏响应鼠标事件但实际上需要先关闭遮罩层才能操作，存在不一致性

**Comment by Vanessa219** [comment]
@Soltus 你可以在顶层的元素上加类 `b3-dialog` 来解决
@royc01 稍后修改
@mozhux 待我稍后看看

**Comment by Soltus** [comment]
> @Soltus 你可以在顶层的元素上加类 `b3-dialog` 来解决 @royc01 稍后修改 @mozhux 待我稍后看看

好的

**Comment by Vanessa219** [comment]
@mozhux 目前浮动状态下移鼠标移除面板，面板就会消失。点击那个箭头可能会有点压力，后面再看看怎么改进。

**Comment by mozhux** [comment]
> @mozhux 目前浮动状态下鼠标移除面板，面板就会消失。点击那个箭头可能会有点压力，后面再看看怎么改进。

把按钮放到下方我觉得都比在顶部好。。不然就是挪到面板内。
![image](https://user-images.githubusercontent.com/46953371/218401465-bf8bbd5c-25ed-4d6b-bab5-c7a849a67816.png)
![image](https://user-images.githubusercontent.com/46953371/218401576-73e98d66-ff93-4c86-ab47-eca3ee5158cd.png)

**Comment by Temacc0531** [comment]
开启悬停后浮窗高度会比顶栏高出几个像素，没有对齐

![image](https://user-images.githubusercontent.com/101307399/218417314-66d212c9-3035-47d0-852d-1bc67cda5030.png)

**Comment by Soltus** [comment]
@Vanessa219 左右浮窗的高度不一致，是有什么考量吗

**Comment by yixna** [comment]
动画卡顿不流畅

**Comment by Temacc0531** [comment]
开启悬停再隐藏边栏后，想点击文档右上角的`···`按钮会变成触发边栏，引起冲突，点不到`···`按钮

**Comment by littlecoby** [comment]
支持一个按钮放在停靠栏上方，还要想想停靠栏隐藏时按钮怎么放。
像语雀或edge那样放在面板边缘的一个不方便的地方是，当面板处于悬浮状态，想要钉住时，鼠标稍微移偏一些面板就自动缩回去了，有时得操作两三次才能钉上。
面板中的内容（文档树、大纲）集中在上方，钉住按钮放在上方能减少鼠标移动的距离。

**Comment by Vanessa219** [comment]
> @Vanessa219 左右浮窗的高度不一致，是有什么考量吗

楼上有提到避免遮挡

**Comment by Vanessa219** [comment]
> 动画卡顿不流畅

使用默认主题么？

**Comment by royc01** [comment]
> > @Vanessa219 左右浮窗的高度不一致，是有什么考量吗
> 
> 楼上有提到避免遮挡

左右可以做一致  右侧也遮挡

**Comment by Vanessa219** [comment]
> 开启悬停再隐藏边栏后，想点击文档右上角的`···`按钮会变成触发边栏，引起冲突，点不到`···`按钮

如果隐藏了停靠栏就缩小触发点？

**Comment by Vanessa219** [comment]
> > > @Vanessa219 左右浮窗的高度不一致，是有什么考量吗
> > 
> > 
> > 楼上有提到避免遮挡
> 
> 左右可以做一致 右侧也遮挡

考虑到右侧面板内容比较充实且右侧被遮挡内容比较少。

**Comment by royc01** [comment]
> > > > @Vanessa219 左右浮窗的高度不一致，是有什么考量吗
> > > 
> > > 
> > > 楼上有提到避免遮挡
> > 
> > 
> > 左右可以做一致 右侧也遮挡
> 
> 考虑到右侧面板内容比较充实且右侧被遮挡内容比较少。

牺牲几十个像素我觉得可以接受的，左右面板对称，逻辑上就比较一致，或者左侧高度也不减，但是触发区域降到面包屑以下

**Comment by Vanessa219** [comment]
> > > > > @Vanessa219 左右浮窗的高度不一致，是有什么考量吗
> > > > 
> > > > 
> > > > 楼上有提到避免遮挡
> > > 
> > > 
> > > 左右可以做一致 右侧也遮挡
> > 
> > 
> > 考虑到右侧面板内容比较充实且右侧被遮挡内容比较少。
> 
> 牺牲几十个像素我觉得可以接受的，左右面板对称，逻辑上就比较一致，或者左侧高度也不减，但是触发区域降到面包屑以下

194px，等后续用户反馈再看看，毕竟反链还蛮占用位置的。

**Comment by royc01** [comment]
> 194px，等后续用户反馈再看看，毕竟反链还蛮占用位置的。
👌👌

**Comment by aptexd** [comment]
“钉住”按钮的位置和“文档树”“大纲”等按钮平级了，有可能造成困惑，或许可以调整下

**Comment by Soltus** [comment]
> @Soltus 你可以在顶层的元素上加类 `b3-dialog` 来解决 @royc01 稍后修改 @mozhux 待我稍后看看

我试了一下，加上`b3-dialog`自带了很多样式，不是一个可用的方案。

**Comment by Vanessa219** [comment]
> “钉住”按钮的位置和“文档树”“大纲”等按钮平级了，有可能造成困惑，或许可以调整下

https://github.com/siyuan-note/siyuan/issues/7375

**Comment by Vanessa219** [comment]
> > 194px，等后续用户反馈再看看，毕竟反链还蛮占用位置的。
> > 👌👌

https://github.com/siyuan-note/siyuan/issues/7363 第二点

**Comment by Vanessa219** [comment]
> > @Soltus 你可以在顶层的元素上加类 `b3-dialog` 来解决 @royc01 稍后修改 @mozhux 待我稍后看看
> 
> 我试了一下，加上`b3-dialog`自带了很多样式，不是一个可用的方案。

我记录一下，后期放到 https://github.com/siyuan-note/siyuan/issues/5066 进行考虑
