### ISSUE TITLE
公式与代码块自动补全

### ISSUE THREAD

**Issue by H-tr** [siyuan-note/siyuan#3501]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
写Katex的时候如果有一个\begin{assigned}，还需要自己手动在后面补上\end{assigned}，就不是很方便，然后编辑代码的时候打完{后总是需要找对齐位置，也不是很方便（好吧事实上代码可以在vscode之类的编辑器上写完直接复制，但是tex很麻烦）

### 描述可能的最优解决方案 Describe the optimal solution
有没有可能直接使用一部分开源编辑器的源代码？（比如vscode）

### 描述候选的解决方案 Describe the candidate solution
自己写所有部分

### 其他信息 Other information
并没有了。个人感觉对我来说笔记软件相比于latex的主要优势是代码块。所以希望能够在这里改进一下

**Comment by 88250** [comment]
抱歉了，这个目前做不了……

以后如果有能力可以做会重开，感谢提议。
