### ISSUE TITLE
List outline dots/numbers support click to focus

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3502]
列表大纲圆点/数字支持点击聚焦

https://ld246.com/article/1637919826896

**Comment by Zuoqiu-Yingyi** [comment]
建议点击聚焦使用`双击`事件触发, 将`单击`事件留给展开折叠这种更高频的操作 ✨

**Comment by Achuan-2** [comment]
建议单击折叠，双击聚焦。单击聚焦太容易误触（之前就是因为太容易误触才改为ctrl+点击进入的），而且对大多数人说，聚焦是低频操作，而折叠是高频需求，折叠应该比聚焦功能更容易点击，而且聚焦很容易让没接触大纲笔记软件的人懵圈，以为软件出问题只显示部分笔记。

单击列表项折叠，或者有折叠三角形，更符合大多数软件的使用逻辑，照顾多数用户的使用习惯

**Comment by netdog2019** [comment]
支持单击折叠，双击聚焦。而且前面最好不要用原点，不太好分别，用三角形好分辨。折叠后是三角形尖端指向右边，展开时三角形旋转，尖端指向下面，更加直观一些。

**Comment by Crowds21** [comment]
是还像原来一样,点击一下就聚焦吗?太容易误触了吧.
`Ctrl + Click` 难道还不够方便吗. 觉得这个应该属于个人习惯问题,而非快捷键设置的问题吧. 
你既然用笔记软件了,那必然有一个手是在键盘上的吧, 最左下角的Ctrl ,小拇指底部手掌往下一压就成了,都不用专门移动手指头.
我甚至觉得这个比双击都方便.

**Comment by Elliootalderson** [comment]
类似于我来,单击展开,再次单击折叠,同一快捷键支持展开/关闭所有折叠

**Comment by Elliootalderson** [comment]
还有,现在的折叠的列表圆点和序列数字,和没有折叠的圆点和列表数字差异不好,很难分辨.加入三角形折叠列表很有必要,

**Comment by Elliootalderson** [comment]
另外,多层双击聚焦的返回键的设置很重要.现在是快捷键(这个很不方便)+鼠标返回(但好像不管多少层,都是一步返回到最外层)这个逻辑上应该逐层返回

**Comment by yuanwei-jay** [comment]
希望做成幕布那样——通过小三角形进行折叠/展开；单击小圆点直接进入聚焦状态。这样一步到位，也符合大多数人的使用习惯。

**Comment by 88250** [comment]
感谢各位讨论，我们先加列表块折叠小三角吧 https://github.com/siyuan-note/siyuan/issues/3125

**Comment by 88250** [comment]
确定加入折叠小三角了，这个我们关闭了，感谢各位讨论。

**Comment by ippreacher** [comment]
能否像workflowy一样，点击圆点聚焦，并且聚焦的内容是自动展开的？

**Comment by 88250** [comment]
展开状态目前没有办法分离记录，所以还是保持现状吧。



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 11, 2023 13:16 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] List outline dots/numbers support click tozoom in (Issue #3502)




 
能否像workflowy一样，点击圆点聚焦，并且聚焦的内容是自动展开的？

**Comment by ippreacher** [comment]
明白了， 现在只读模式下（PC端和手机端）也能够修改展开状态，也是这个原因导致吧？希望单独记录展开状态，成为大纲的完全体。

**Comment by 88250** [comment]
嗯，后面看情况，谢谢。



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 11, 2023 13:46 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] List outline dots/numbers support click tozoom in (Issue #3502)




 
明白了， 现在只读模式下（PC端和手机端）也能够修改展开状态，也是这个原因导致吧？希望单独记录展开状态，成为大纲的完全体。

**Comment by ippreacher** [comment]
现在思源的编辑器很强大，可以说是笔记软件中独一份的，希望大纲也能进一步增强完备！辛苦D大！

**Comment by Aiviokoo** [comment]
> 能否像workflowy一样，点击圆点聚焦，并且聚焦的内容是自动展开的？

补充一下以供未来参考：
在workflowy中，若点击已经折叠的内容，则聚焦后自动展开被折叠的第 1 层，退出聚焦仍复原折叠。
（第 2、3、4 层若本就未折叠，则也会显示为未折叠状态，从而聚焦后1、2、3、4均展开；若本就为折叠的，则只有1自动展开，2、3、4不会在这时自动展开）
也就是说它的聚焦自动展开是只对当前能看到的折叠点击后自动展开当前层，其他层不受影响。
目前使用Savor主题可以实现相同效果（要不官方直接招安一下这个效果）@88250
