### ISSUE TITLE
视频时间戳

### ISSUE THREAD

**Issue by GreenHatHG** [siyuan-note/siyuan#3504]
如下链接
https://cn.logseq.com/t/topic/838

**Comment by 88250** [comment]
你好，这个功能不考虑直接内置，我们期待社区开发者通过挂件引入，感谢提议。

**Comment by Zuoqiu-Yingyi** [comment]
@GreenHatHG 
* [\[思源笔记经验分享\] 为笔记内 BiliBili/YouTube 视频创建时间戳 & 跳转到指定时间点](https://ld246.com/article/1648639553690)
* [\[思源笔记经验分享\] 为笔记内视频块 / 音频块快速创建时间戳](https://ld246.com/article/1645210285263)
* [\[思源笔记经验分享\] 为笔记内视频块 / 音频块设置多个时间戳](https://ld246.com/article/1644814136903)
* [\[思源笔记经验分享\] 为笔记内视频块 / 音频块设置时间戳](https://ld246.com/article/1644759207850)

**Comment by GreenHatHG** [comment]
你的邮件已收到！

**Comment by woaihuangxueying** [comment]
现在在上网课，太需要这个功能了！！！！
