### ISSUE TITLE
appimage方式启动缺少字体

### ISSUE THREAD

**Issue by Carlos920** [siyuan-note/siyuan#3505]
### 描述问题 Describe the problem
appimage方式启动缺少字体

ubuntu上以appimage格式启动很多字体无法显示

### 期待的结果 Expected result
能否将部分字体也打包至appimage中或者给出一个字体列表

### 截屏或者录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/32257015/143727655-e300c24b-2805-446d-8e37-5f085e17e74b.png)

### 版本环境 Version environment

* Version: siyuan-1.5.3-linux.AppImage
* Operating system:  Linux Ubuntu

**Comment by 88250** [comment]
你好，字体可以在主题的 theme.css 文件中找到。daylight 主题默认的字体应该是：`--b3-font-family: "quote", "Helvetica Neue", "Luxi Sans", "DejaVu Sans", "Hiragino Sans GB", "Microsoft Yahei", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Segoe UI Symbol", "Android Emoji", "EmojiSymbols";`
