### ISSUE TITLE
macOS 上 CPU 占用非常高

### ISSUE THREAD

**Issue by iswbm** [siyuan-note/siyuan#3507]
### 描述问题 Describe the problem

这两天才下载使用的 siyuan 笔记，发现思源笔记只要一打开就非常占用 cpu，如下图所示，这还是在我笔记只有一两篇的情况下

![](http://image.iswbm.com/20211128205626.png)

### 期待的结果 Expected result

希望查一下问题，优化一下，cpu 占用这么多，风扇转得很响

### 版本环境 Version environment

* Version: 1.5.3
* Operating system: macOS 10.13.6
* Browser (if used): 客户端

**Comment by 88250** [comment]
你好，请问是否使用过查询嵌入块？如果使用过的话，v1.5.3 会出现空查询脚本导致挂起无响应问题。

如果没有使用过的话，麻烦提供一下日志文件，谢谢。

**Comment by iswbm** [comment]
> 你好，请问是否使用过查询嵌入块？如果使用过的话，v1.5.3 会出现空查询脚本导致挂起无响应问题。
> 
> 如果没有使用过的话，麻烦提供一下日志文件，谢谢。

抱歉我初次使用，不知道你所说的『查询嵌入块』是什么意思，我只是简单的 markdown 格式的文章（有图片）

对应的日志如下，好像没有看出异常

```
I 2021/11/21 20:01:14 conf.go:359: exited kernel
 35 I 2021/11/21 20:01:18 working.go:94:
 36       ___                                   ___           ___           ___
 37      /  /\        ___           ___        /__/\         /  /\         /__/\
 38     /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
 39    /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
 40   /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 41  /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 42  \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
 43   \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
 44    \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
 45      /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
 46      \__\/                                 \__\/         \__\/         \__\/
 47 I 2021/11/21 20:01:18 runtime.go:57: kernel is booting:
 48     * ver [1.5.3]
 49     * arch [amd64]
 50     * runtime mode [prod]
 51     * working directory [/Applications/SiYuan.app/Contents/Resources]
 52     * read only [false]
 53     * container [std]
 54     * database [ver=20211022]
 55     * workspace directory [/Users/MING/Documents/SiYuan, data 2.2 MB]
 56     * rsync [version 2.6.9  protocol version 29]
 57     * pandoc [pandoc 2.13]
 58 I 2021/11/21 20:01:18 conf.go:257: local serve path [http://192.168.1.4:6806]
 59 I 2021/11/21 20:01:18 conf.go:507: pre-init database size [958 kB]
 60 I 2021/11/21 20:01:18 serve.go:68: kernel is booting [http://127.0.0.1:6806]
 61 I 2021/11/21 20:01:18 box.go:495: use existing database for box [20210808180117-czj9bvb]
 62 I 2021/11/21 20:01:18 box.go:495: use existing database for box [20211121160407-5he187p]
 63 I 2021/11/21 20:01:18 conf.go:523: post-init database size [958 kB], tree stat [count=49, size=906 kB]
 64 I 2021/11/21 20:01:19 working.go:112: kernel booted
 65 I 2021/11/21 20:09:34 conf.go:359: exited kernel
```

**Comment by 88250** [comment]
思源在启动的时候会进行数据索引，这个阶段比较占用 CPU，启动完毕以后应该会恢复正常，麻烦观察一下是否是这个情况，谢谢。

**Comment by iswbm** [comment]
> 思源在启动的时候会进行数据索引，这个阶段比较占用 CPU，启动完毕以后应该会恢复正常，麻烦观察一下是否是这个情况，谢谢。

经过测试，在我新增一篇文章后，CPU 就开始狂飙，从刚刚到现在 20 分钟了，CPU 还是居高不下（70%-80%），风扇一直狂转。

而当我关闭软件后，再重新打开，就正常了（占用在 20-30%），一旦新增文章，就又开始狂飙了。

**Comment by 88250** [comment]
能截图看下所有 `SiYuan` 开头的进程 CPU 占用情况吗？在 Windows 上面，一共有这几个进程：

![image](https://user-images.githubusercontent.com/873584/143771257-bdbed84e-2659-4760-bb09-78769245a7b3.png)

**Comment by iswbm** [comment]
> 能截图看下所有 `SiYuan` 开头的进程 CPU 占用情况吗？在 Windows 上面，一共有这几个进程：
> 
> ![image](https://user-images.githubusercontent.com/873584/143771257-bdbed84e-2659-4760-bb09-78769245a7b3.png)

请看

![](http://image.iswbm.com/20211128221417.png)

**Comment by 88250** [comment]
这个问题可能是因为思源使用的 Electron 框架导致 https://github.com/electron/electron/issues/31916 

我们会继续收集用户的反馈，并跟进该问题，感谢反馈。

**Comment by 88250** [comment]
我关闭了，这个问题在 v1.7.0 [降级 Electron](https://github.com/siyuan-note/siyuan/issues/3783) 后应该就好了，有空的话请帮忙确认一下，谢谢。
