### ISSUE TITLE
自定义排序后新建的文档排序不一致

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3511]
### 描述问题 Describe the problem

在很久以前就已经设置排序方式为自定义排序，今天在不同电脑上同步后发现显示的文件位置不对（因为昨天新增文件比较多，然后在日记中按文件顺序建立索引，今天在日记中发现文档树文档顺序与日记表现的不一样）

在Mac上新建文件，默认都是处于其所在文件夹顶部，同步后，关闭思源。然后在Win10上打开，同步，发现新建的文件排序反而在其所在文件夹中间位置，有些是在第一个，更多的是散乱的。

比如在Inbox文件下建立子文档M、N、K、Q，原来已经有文档A、B、C、D、E，在Mac电脑显示是 M、N、K、Q、A、B、C、D、E。但是同步到其他电脑显示的顺序可能是：M、A、B、C、N、K、D、E、Q.。虽然这个顺序不一定是实际表现的，但是却有可能这么排列

### 期待的结果 Expected result

同样的版本，同样的排序方式，希望同步后，其他电脑上的思源显示文件位置会是一样的

### 版本环境 Version environment

* Version: Mac新增、修改时是1.5.4-beta4，后面升级到1.5.4。今天开机win10后直接升级1.5.4，然后同步
* Operating system: Mac11.6，win10 21H2
* Browser (if used):

**Comment by 88250** [comment]
同步完成以后试下重新展开文档树。

**Comment by JokeenZhang** [comment]
还是不行，而且只有那几个包含子文档的父文档的顺序是错的

**Comment by JokeenZhang** [comment]
是否类似于操作系统文件管理系统排列那样，文件夹默认在顶部？

**Comment by HowcanoeWang** [comment]
> 是否类似于操作系统文件管理系统排列那样，文件夹默认在顶部？

我也刚想提一个自动排序的issue，windows和mac混用，今日速记里面的日期乱的一塌糊涂

**Comment by 88250** [comment]
没有文件夹之后，任何文档都有可能出现子文档，所以不能按照是否有子文档来进行分类，因为这样分的话，顺序会更混乱。自定义排序可能更适合一些。

楼主提的 bug 我们现在还不能定位到。

**Comment by HowcanoeWang** [comment]
> 没有文件夹之后，任何文档都有可能出现子文档，所以不能按照是否有子文档来进行分类，因为这样分的话，顺序会更混乱。自定义排序可能更适合一些。
> 
> 楼主提的 bug 我们现在还不能定位到。

我这边也遇到同样的情况，特别是daliynote非常明显，似乎mac的逻辑是在顶部插入整体降序(11.30 -> 11.29 -> 11.28)，而windows的逻辑是在底部插入整体升序(11.01 -> 11.02 -> 11.03)
有一个简单的解决方法，在右键里面，增加一个重新排序功能 排序当前子文件夹> 降序/升序
![image](https://user-images.githubusercontent.com/19968935/144346503-c3d43397-45d6-4abd-b88a-1d0361ed60ed.png)
