### ISSUE TITLE
Mac中西文自动插入空格机制在无序列表中不有效执行

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3512]
### 描述问题 Describe the problem

Mac下，使用系统输入法，打开自动插入空格开关后，需要在文字后面添加标点字符后才会插入空格隔开（添加空格），这与Win10系统表现的不一样，win10（这里使用搜狗输入法）没有出现过该问题。

![image](https://user-images.githubusercontent.com/33319484/143797134-ed56d0e6-1705-48eb-b29c-4adb74f0d9d7.png)

在上图中，如果添加标点符号，`1` 与 `位置` 会自动插入空格隔开；但是如果不添加标点符号，而是直接通过回车键添加无需列表项，不会插入空格隔开。

这是mac上的表现。这方面win10上的表现远远好于mac，win10中添加数字或中文，都会导致 `位置` 前自动插入空格。

### 期待的结果 Expected result

mac在中西文自动插入空格的表现能跟win10一样

### 版本环境 Version environment

* Version: 在两个系统上都是1.5.4
* Operating system: mac11.6，win10 21h2
* Browser (if used):

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/3363
