### ISSUE TITLE
集市包版本更新但不出现更新按钮问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3513]
* 主题
* 图标

**Comment by Zuoqiu-Yingyi** [comment]
目前(`v2.0.9`)貌似用的是 `本地版本号字符串 < 集市版本号字符串` 的方案判断是否显示更新按钮
经过测试,  如果一个内容现在云端版本号为 `0.9.10`, 那么
- 本地版本号为 `0.9.0`, `0.9.00`, `0.9.1` 时都能正常显示更新按钮
- 本地版本号为 `0.9.10`, `0.9.2`, `0.9.20` 时都不能正常显示更新按钮

这会导致一个必然会出现的问题, 如果该内容更新到 `9.9.9`, 那么之后的版本 `1x.x.x` 都不会正常显示更新按钮

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 确实是 `<`，下个版本改为 `!=`
