### ISSUE TITLE
行内代码选中后点击加粗，会取消行内代码格式

### ISSUE THREAD

**Issue by zxlzy** [siyuan-note/siyuan#3518]
### 描述问题 Describe the problem

选中行内代码后，点击加粗，或者 ctrl B， 会取消行内代码。但是 **```a = 1```** 是支持的。
### 期待的结果 Expected result
不会自动取消行内代码。

### 版本环境 Version environment

* Version:  1.5.4
* Operating system: macos
* Browser (if used):  chrome

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/2911
