### ISSUE TITLE
操作体验建议

### ISSUE THREAD

**Issue by errorcode7** [siyuan-note/siyuan#3519]
图标偏小，容易误操作
![image](https://user-images.githubusercontent.com/1251316/143845464-2702f438-140a-4986-868e-7dfe0afd9bd6.png)

展开收缩操作过于繁琐，建议鼠标放在上面的时候，下方自动出现出现一个往下的类似这种》箭头，直接展开和收缩。
![image](https://user-images.githubusercontent.com/1251316/143845706-69bacb96-9274-49be-a6a5-6fd2737610fe.png)

**Comment by 88250** [comment]
1. 图标过小暂时没有改进计划，可以试下集市中的一些主题
2. 请关注 https://github.com/siyuan-note/siyuan/issues/3125
