### ISSUE TITLE
支持自定义表情刷新快捷键

### ISSUE THREAD

**Issue by nicollcheng** [siyuan-note/siyuan#3520]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在刷新Emoji文件夹添加了新图片后，支持快捷键刷新

### 描述可能的最优解决方案 Describe the optimal solution

在刷新Emoji文件夹添加了新图片后，添加新的快捷键，以方便刷新Emoji文件夹实时图片信息

**Comment by 88250** [comment]
你好，考虑到这个功能并不是高频使用 ，所以不会添加快捷键支持。可以在设置 - 外观中进行刷新：

![image](https://user-images.githubusercontent.com/873584/143866856-5188ff0d-b665-4dd7-b5ae-ebc411441427.png)
