### ISSUE TITLE
支持超链接自动识别

### ISSUE THREAD

**Issue by WuTao18** [siyuan-note/siyuan#3522]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

复制超链接，粘贴到思源笔记的时候。

### 描述可能的最优解决方案 Describe the optimal solution

粘贴一个超链接的时候，自动识别为链接，提示文本补全为网页标题。
例如往[幕布](https://mubu.com/)里粘贴`https://b3log.org/siyuan/`，会自动识别为超链接并补全提示文本，如下图。
<img width="526" alt="image" src="https://user-images.githubusercontent.com/32795326/143903644-1e6e6057-73da-4e01-aef8-25e16d0335e4.png">

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
1. 复制超链接以后使用 Ctrk+K 会按照超链接格式插入，不默认解析是因为有的地方还是需要纯文本
2. 链接卡片（或者仅文本）需要抓取解析网页，暂不考虑 https://github.com/siyuan-note/siyuan/issues/1020 这个估计以后浏览器会自带（比如 Edge 就有这个功能）

感谢反馈。
