### ISSUE TITLE
对自定义 emoji 搜索结果进行匹配优先排序

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#3525]
https://ld246.com/article/1638202866363

**Comment by Elliootalderson** [comment]
试用了改版后的emoji功能,怎么比之前感觉更不友好了.

首先,排序的优先级很奇怪

![image.png](https://b3logfile.com/file/2021/12/image-f87974d5.png)

第一个图标叫phr.png ,竟然排在我想要的图标(红圈内)名为 right_arrow.png前面.而right_arrow左边的图标叫做mindmaster.png.

第二,用户想要的是这样的结果,直接列出最近常用.便于快速输入

![image.png](https://b3logfile.com/file/2021/12/image-e96bef6c.png)

但是/emoji操作比":+首字母"繁琐.

所以真正的需求是通过":+图标首字母"直接列出/emoji的结果

**Comment by Vanessa219** [comment]
是不是 emoji 的文件夹中包含了 r 字母？

搜索的时候把常用表情不进行过滤，固定加在前面如何？

**Comment by Elliootalderson** [comment]
图一中的第一排的图标名称中都含有r字母, 但r字母不在首位的图片名和r在首位的图片没有先后顺序.导致尽可能输入全名"right_arrow"才能确认到图标顺位第一.
实际上,可以把搜索的表情,分类为常用表情和所有表情(过滤常用表情),两者按字母A~Z优先级排序,并且常用表情中在符合字母优先级的基础上,按最近使用进行排序,对于我经常使用"right_arrow"这个表情而言,我只需" :r "就能匹配到搜索结果的第一顺位"right_arrow"

**Comment by Elliootalderson** [comment]
换句话说,直接把"/emoji+表情"的搜索结果移到" :+表情"就大致可以满足了.
"/emoji+表情"操作过程按键多
" :+表情"操作过程按键少.

**Comment by Vanessa219** [comment]
稍后把文件名排除，再加入常用表情，感谢反馈

**Comment by Elliootalderson** [comment]
https://user-images.githubusercontent.com/93273663/144859896-822b4138-8440-4108-a18e-a268c0111646.mp4

输入emoji后,当前块前面的文字被清空

**Comment by Vanessa219** [comment]
感谢反馈，下个版本修复
