### ISSUE TITLE
下载资源文件到本地

### ISSUE THREAD

**Issue by cxcn** [siyuan-note/siyuan#3526]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

从网页复制带图片的内容，会引用原网页的图片，一旦网页挂掉图片就丢了

### 描述可能的最优解决方案 Describe the optimal solution

在笔记右上脚添加一个按钮选项
![](https://i.loli.net/2021/11/30/t4No1TUlrImYSh6.png)

遍历该笔记所有图片外链，下载到本地（就像粘贴图片一样）

**Comment by 88250** [comment]
请使用浏览器剪藏扩展，比如思源的剪藏或者 Web Clipper。
