### ISSUE TITLE
动态渲染的长文档后退问题

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#3528]
动态渲染的长文档，在尾部聚焦后，再后退会回退到最顶层，而不是之前的块
另外希望后退后，之前的块定位到窗口上方，目前是下方，与大纲定位一致
版本：1.5.4 
系统：win10

**Comment by 88250** [comment]
麻烦试下最新版上是否还能重现，谢谢。

**Comment by Achuan-2** [comment]
依然有这个问题，动态加载的长文档聚焦无法回到原处

**Comment by 88250** [comment]
收到，后面再跟进。
