### ISSUE TITLE
Docker自建版本加载大文件JS缓慢的问题

### ISSUE THREAD

**Issue by qq77522980** [siyuan-note/siyuan#3529]
目前docker自建版本，输入授权码登陆后，会加载一个10+M的twitter的js文件（当然还有很多其他JS），对于带宽有限的服务器不太友好（我的是腾讯1M VPS）。可能每次加载需要2-3分钟吧。
能否加入相关配置功能，可以把JS文件放入对象存储，这样可以提升加载速度。

**Comment by 88250** [comment]
暂时不会考虑，感谢反馈。
