### ISSUE TITLE
文档标题和标题块纳入虚拟引用

### ISSUE THREAD

**Issue by yangguang760** [siyuan-note/siyuan#3532]
如图
<img width="656" alt="Snipaste_2021-11-30_21-53-56" src="https://user-images.githubusercontent.com/748502/144059988-5566e68d-4762-45c1-bb5c-dbc2f22243ea.png">

**Comment by 88250** [comment]
`六大纪律` 没有被引用过的话不会纳入虚拟引用搜索的，可能是这个问题。

**Comment by yangguang760** [comment]
@88250 Thx，试了试，确实是。不过我觉得还是应该从块标题里搜索，毕竟虚拟引用本来就是用来标识该引没引的东西。

**Comment by 88250** [comment]
下个版本会将文档标题和标题块纳入搜索，但是标题块会出现自己引用自己的情况 https://ld246.com/article/1633243424177

![image](https://user-images.githubusercontent.com/873584/144067883-3f4a5a6c-d4b6-4143-aafa-8eb052a1ee79.png)

这个暂时不处理了，具体讨论看上面的帖子，谢谢。

**Comment by 88250** [comment]
内测版上反馈后决定还是不要加入标题和文档名，否则过于混乱。
