### ISSUE TITLE
虚拟引用转为引用块

### ISSUE THREAD

**Issue by yangguang760** [siyuan-note/siyuan#3533]
我个人认为，逻辑还是要统一，以下三种方案我觉得都ok
1、如果提及可以使用文本搜索，则在提及处可看到所有虚拟引用，并可转换为块引用，逻辑自洽
2、目前提及仅仅使用名称和别名搜索，则应该在虚拟引用处提供转换为块引用的功能，这样，在反链处可以看见所有引用，逻辑自洽
3、设置中提供开关，是否用文本作为提及搜索，以便集中将提及转为块引用

**Comment by 88250** [comment]
这个在解决自身引用之前先不考虑了 https://ld246.com/article/1633243424177
