### ISSUE TITLE
导出 Word 时支持通过属性设置 Pandoc 参数

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3535]
https://ld246.com/article/1638283280873

使用方式：在文档上设置属性 `pandoc-docx`，值为附加参数列表，比如 `--reference-doc twocolumns.docx --lua-filter=zotero.lua`。

**Comment by legend053** [comment]
那现在属性里设置的pandoc参数可以用吗？我看论坛里之前的帖子说设置的参数并不起作用。

**Comment by 88250** [comment]
论坛里反馈的是这个 https://github.com/siyuan-note/siyuan/issues/3592

**Comment by legend053** [comment]
没看懂。那现在设置的参数对导出word有影响吗？

**Comment by 88250** [comment]
有的，这个 issue 做的就是导出 Word 时支持设置 Pandoc 参数。

**Comment by legend053** [comment]
好。我记得之前的内测版里的设置不起作用。我这就安装最新版再试试. :)

**Comment by Achuan-2** [comment]
现在还支持这个特性吗

**Comment by 88250** [comment]
不支持了，有其他问题，建议还是导出 Markdown 后自行调用 Pandoc。
