### ISSUE TITLE
搜索页签改为上下布局

### ISSUE THREAD

**Issue by tobealive** [siyuan-note/siyuan#3538]
# Feature suggestion Quicksearch Docklet
There are at least two use cases that come to my mind for this. 
- Having a search function and its results available while keeping the main Document in attention. 
- The docklet could also display the search results when clicking on a Tag.
It would also solve problems with displaying the tag-search results in a split pane. 
(Without wanting to generalize too much) Handling it in a split pane comes with workflow distractions. General Overview is compromised and it's probably an overkill. In many cases, there will be lots of empty space on the left search results side and the preview side will be too narrow on most screens to make good use of it. 
Displaying the results in the docklet with a small contextual preview one above the other instead of a horizontal split would solve this problem. 

I also think this feature would just add to the project without taking something. The advanced search feature is still good and usable as a launcher and for searching with full attention.
Reading the "Origin" article I could imagine that it could fit in the spirit and principles of the project.

_I'm adding a screenshot from a fellow PKM Application as inspiration for how it can be handled._

![PKM-2](https://user-images.githubusercontent.com/34311583/144120673-e1f9ef6d-7c5d-4484-86e4-e5786be7a86b.jpg)

**Comment by 88250** [comment]
Hello, the search tab is not only used for tag search but it can also be used for common text keyword search (Ctrl+Shift+F after selecting text), so we design it to be separated by left and right, such as this case:

![image](https://user-images.githubusercontent.com/873584/144158231-34c28bc2-dd28-44dc-a841-15da08e6336b.png)

**Comment by tobealive** [comment]
Hello, thanks for your reply! Yes, I can see a use case here and know about that functionality. For me, it is very rarely I have to admit. The long list of search results tells barely a thing about the single items it is pointing at and it's hard to find something from that list. When we put a more specific search the list is getting a lot shorter and on the left side is of the split pane is a lot of unused space. Another thing is that for using it like this, the right sidebar has to be closed else the preview gets too narrow to be usable. At least on most used screens and resolutions that are used today.

Maybe I get used to it and learn to love it. 

Also, I really want to put some honoring words next to my critiques.
I found SiYuan on the way fighting through the currently available PKM Software Junge and I'm really glad I did. 
It's a beautiful piece of work. I'm a Designer myself and this Software is like a piece of art with a productive use to it. It is somehow like I'm able to feel that it is made with love and passion.
The WYSIWYG Editor is outstanding and on top it is content-block based.  Also the handling of embedded content like videos and pdfs. Even though small of the Features have small errors here and there they are already first class! So kudos. Thank you very much is what I want to say!
​

**Comment by tobealive** [comment]
**Also, I really want to put some honoring words next to my critiques.**
I found SiYuan on the way fighting through the currently available PKM and Note Taking Software-Junge and I'm really glad I found it. 
It's just a beautiful piece of work! I'm a Designer myself and this Software is like a piece of art with a productive use to it. It is somehow like I'm able to feel that it is made with love and passion.
The WYSIWYG Editor is outstanding and on top it is content-block based.  Also the handling of embedded content like videos and pdfs. Even though small of the Features have small errors here and there they are already first class! So kudos. Thank you very much is what I want to say!

**Comment by 88250** [comment]
Thanks for the discussion. In fact, regarding the search interface, there is also discussion on the SiYuan Chinese forum https://ld246.com/article/1637045994739, some users think that the left-right layout is reasonable.

At the moment, what you said also makes sense because the tab panel can already be displayed in a tree form, and it may be more reasonable to press the top-bottom layout of the search tab. We will adjust the layout of the search tab in the near future, thank you.

**Comment by tobealive** [comment]
Thanks for the rapid work! Insane speed. 

Seeing the Ambition for the left/right approach it in the Chinese forums and feeling like my initial issue wasn't communicated that well I want to leave a quick annotation to this request.

I actually didn't wanted to push changing the search to a top bottom approach. It was more about splitting the results list and the preview and keeping it in left/right. Then like on the screenshot the results list can be displayed in a widget in the toolbar / dock. That's why i called it docket.

**Comment by tobealive** [comment]
Sorry for the errors with spelling and semantic. I needed to edit the recent comment after posting it. 

In case you're checking the comments just via mail: to read it in a way that makes more sense I recommend checking it directly on GitHub to see the most up-to-date version. Haha sorry for this again.

**Comment by tobealive** [comment]
**Visualization preview of the request.**
![SiYuan - 0 Please Start Here_001 (1)](https://user-images.githubusercontent.com/34311583/144592811-be633e82-f75f-45fc-9b3b-2931b82ab667.png)

**Comment by 88250** [comment]
Oh, I understand, we need a search panel, not just a tab.

We may need to spend time to consider and implement this. In the recent releases, we will keep the design of the search tab, for the time being. The new change we can continue discussing in https://github.com/siyuan-note/siyuan/issues/3564, thank you.
