### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by xiaotoucai** [siyuan-note/siyuan#3539]
### 描述问题 Describe the problem

同步失败：
同步失败：upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
### 期待的结果 Expected result

希望同步成功

### 版本环境 Version environment

* Version: 1.5.3
* Operating system: win10
* Browser (if used): 

### 日志文件 Log File

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2021/12/01 08:22:03 runtime.go:57: kernel is booting:
    * ver [1.5.3]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\app\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211022]
    * workspace directory [D:\siyuan, data 280 MB]
    * rsync [version 3.2.4dev  protocol version 31]
    * pandoc [pandoc.exe 2.13]
I 2021/12/01 08:22:03 conf.go:257: local serve path [http://127.0.0.1:6806]
I 2021/12/01 08:22:03 database.go:134: initialized database tables
I 2021/12/01 08:22:03 database.go:88: reinitialized database [D:\siyuan\temp\siyuan.db]
I 2021/12/01 08:22:03 sync.go:85: sync before boot
I 2021/12/01 08:22:03 serve.go:68: kernel is booting [http://127.0.0.1:6806]
I 2021/12/01 08:22:05 sync.go:161: set sync interval to [2m]
I 2021/12/01 08:22:05 conf.go:507: pre-init database size [66 kB]
I 2021/12/01 08:22:05 box.go:524: rebuilt database for notebook [20210808180117-czj9bvb] in [0.12s], tree stat [count=46, size=876 kB]
I 2021/12/01 08:22:06 box.go:524: rebuilt database for notebook [20211004102208-ko8o0bx] in [1.01s], tree stat [count=86, size=1.0 MB]
I 2021/12/01 08:22:06 conf.go:523: post-init database size [2.9 MB], tree stat [count=132, size=1.9 MB]
I 2021/12/01 08:22:07 working.go:112: kernel booted
E 2021/12/01 08:28:56 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 08:33:11 liandi.go:301: get cloud sync info failed: [Post "https://siyuan2.b3logfile.com/apis/siyuan/sync/getSiYuanWorkspaceSync": dial tcp: lookup siyuan2.b3logfile.com: no such host]
E 2021/12/01 08:34:14 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 08:46:00 liandi.go:301: get cloud sync info failed: [Post "https://siyuan2.b3logfile.com/apis/siyuan/sync/getSiYuanWorkspaceSync": dial tcp: lookup siyuan2.b3logfile.com: no such host]
E 2021/12/01 08:47:01 liandi.go:301: get cloud sync info failed: [Post "https://siyuan2.b3logfile.com/apis/siyuan/sync/getSiYuanWorkspaceSync": dial tcp: lookup siyuan2.b3logfile.com: no such host]
I 2021/12/01 08:48:07 sync.go:227: sync [cloud=13883, local=13891] uploaded in [3.91s] via [ssh]
I 2021/12/01 08:48:07 sync.go:232: set sync interval to [1m]
I 2021/12/01 08:49:08 sync.go:161: set sync interval to [2m]
I 2021/12/01 08:51:09 sync.go:161: set sync interval to [4m]
E 2021/12/01 08:56:10 liandi.go:301: get cloud sync info failed: [Post "https://siyuan2.b3logfile.com/apis/siyuan/sync/getSiYuanWorkspaceSync": dial tcp: lookup siyuan2.b3logfile.com: no such host]
E 2021/12/01 08:57:15 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 08:58:18 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 08:59:23 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:00:27 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:01:31 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:02:34 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:03:39 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:04:42 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:05:46 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:06:49 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:07:53 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:08:57 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:10:00 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:12:04 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:13:07 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:14:11 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:15:14 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
E 2021/12/01 09:16:19 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
I 2021/12/01 09:16:29 sync.go:88: sync before exit
E 2021/12/01 09:16:33 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
I 2021/12/01 09:16:38 conf.go:359: exited kernel
I 2021/12/01 09:30:48 working.go:94: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2021/12/01 09:30:50 runtime.go:57: kernel is booting:
    * ver [1.5.3]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\app\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211022]
    * workspace directory [D:\siyuan, data 280 MB]
    * rsync [version 3.2.4dev  protocol version 31]
    * pandoc [pandoc.exe 2.13]
I 2021/12/01 09:30:50 conf.go:257: local serve path [http://127.0.0.1:6806]
I 2021/12/01 09:30:50 database.go:134: initialized database tables
I 2021/12/01 09:30:50 database.go:88: reinitialized database [D:\siyuan\temp\siyuan.db]
I 2021/12/01 09:30:50 sync.go:85: sync before boot
I 2021/12/01 09:30:50 serve.go:68: kernel is booting [http://127.0.0.1:6806]
E 2021/12/01 09:30:54 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
I 2021/12/01 09:30:54 conf.go:507: pre-init database size [66 kB]
I 2021/12/01 09:30:54 box.go:524: rebuilt database for notebook [20210808180117-czj9bvb] in [0.07s], tree stat [count=46, size=876 kB]
I 2021/12/01 09:30:55 box.go:524: rebuilt database for notebook [20211004102208-ko8o0bx] in [0.71s], tree stat [count=88, size=1.1 MB]
I 2021/12/01 09:30:55 conf.go:523: post-init database size [2.9 MB], tree stat [count=134, size=1.9 MB]
I 2021/12/01 09:30:56 working.go:112: kernel booted
I 2021/12/01 09:31:03 sync.go:92: sync by hand
E 2021/12/01 09:31:07 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12
I 2021/12/01 09:31:15 sync.go:92: sync by hand
E 2021/12/01 09:31:18 rsync.go:122: upload failed: ssh: connect to host siyuan.b3logfile.com port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev], exit status 12

**Comment by 88250** [comment]
这个问题我们已在 v1.5.5 https://github.com/siyuan-note/siyuan/issues/3503 中进行改进，请等该版本发布以后升级，谢谢。
