### ISSUE TITLE
长文档不能自动保存

### ISSUE THREAD

**Issue by wbooooooo** [siyuan-note/siyuan#354]
长篇小说（125万字左右），复制进思源，可以浏览，但是正常无法保存。

**Comment by 88250** [comment]
书签丢失问题分离到 https://github.com/siyuan-note/siyuan/issues/355

**Comment by wbooooooo** [comment]
还有个问题，部分长文档（30万字左右）在关闭思源再打开后，上次未关闭的页签是没有的。

**Comment by 88250** [comment]
似乎是因为 WebSocket 通讯时 payload buf 设置问题。

[气体动力学.zip](https://github.com/siyuan-note/siyuan/files/5540803/default.zip)

**Comment by 88250** [comment]
v0.4.6 做了设置调整，待发布后请帮忙看下是否工作正常。另外，长文档保存可能会比较卡，也请帮忙反馈一下体验感受。
