### ISSUE TITLE
Android 端顶部适配打孔屏

### ISSUE THREAD

**Issue by reov** [siyuan-note/siyuan#3548]
顶部按键和前置摄像头的孔位重合，无法使用

### 期待的结果 Expected result

将顶部状态栏空出，显示系统状态栏

### 版本环境 Version environment

* Version: 1.5.4
* Operating system: Android 11
* Browser (if used):

**Comment by 88250** [comment]
在下个版本会试着进行调整，发布以后麻烦帮忙看看，感谢反馈。
