### ISSUE TITLE
支持Docker arm64 / aarch64版本

### ISSUE THREAD

**Issue by bitxel** [siyuan-note/siyuan#3556]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

您好，目前Docker Hub上只有amd64版本镜像, 希望可以同时编译一份aarch64版本镜像，应用场景：部署docker容器到树莓派，感谢！

**Comment by 88250** [comment]
暂时没有时间处理，请关注 https://github.com/siyuan-note/siyuan/issues/2580
