### ISSUE TITLE
PDF 中按下 `h` 为手型工具 `s` 为文本工具

### ISSUE THREAD

**Issue by Gd-Gordon** [siyuan-note/siyuan#3559]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
放大PDF页面以后
按下鼠标中键或空格临时从文本选择工具切换到手形工具，实现类似Adobe家软件那种万向拖动页面，而不是现在的双向滚动页面难以精确控制。

### 描述可能的最优解决方案 Describe the optimal solution
按下鼠标中键或空格临时从文本选择工具切换到手形工具，松开鼠标中键或空格自动切换回文本选择工具
Adobe Acrobat, Photoshop, Office 365 Word, OneNote (微软家的切换到Panning Tool后不会自动切换回原编辑状态，略不方便)

### 描述候选的解决方案 Describe the candidate solution
无

无

### 其他信息 Other information
无
无

**Comment by Vanessa219** [comment]
使用的工具没有对应的接口，你看使用快捷键来进行切换如何？
