### ISSUE TITLE
文档同步滚动

### ISSUE THREAD

**Issue by Gd-Gordon** [siyuan-note/siyuan#3560]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
对照浏览英文+中文翻译文献时
一个标签页打开英文PDF，另一个标签页打开中文PDF，在任何一个标签页滚动PDF时同步滚动另一个标签页的PDF到相同位置

### 描述可能的最优解决方案 Describe the optimal solution
在文档查看工具栏上加一个开关同步滚动的按钮，在需要被同步滚动的标签页开启后，滚动PDF时可同步滚动另一个标签页的PDF到相同位置
VS Code+Sync scroll插件，Office365 Word的同步滚动

### 描述候选的解决方案 Describe the candidate solution
在文档查看工具栏上加一个的同步位置按钮，在任何一个标签页点击一次后，同步另一个标签页的PDF到相同位置
类似Adobe acrobat/reader的sync scroll插件（非实时同步滚动，是手动点击按钮同步另一打开的PDF到相同位置）https://www.try67.com/tool/acrobat-reader-synchronized-scrolling-two-or-more-pdf-documents

### 其他信息 Other information
如需要Adobe acrobat/reader的sync scroll插件javascript文件研究可联系我，我已购买
无

**Comment by 88250** [comment]
你好，这个功能现阶段暂时不考虑，感谢提议。
