### ISSUE TITLE
[Feature Request] Change Workspace Dir to directory with special charakters 

### ISSUE THREAD

**Issue by tobealive** [siyuan-note/siyuan#3562]
Changing the workspace directory to one with special characters (in my case an emoji)  and spaces results in an error.

Would be nice to get that further flexibility in choosing the dir location.

![siyuanchangedir](https://user-images.githubusercontent.com/34311583/144586917-5b29fc6a-cec5-48ea-aa6f-1f83fcdb44a6.jpg)

**Comment by 88250** [comment]
Due to some technical limitations, this cannot be achieved, sorry.

**Comment by tobealive** [comment]
Oh, okay.
Hoped it would be as simple as with terminal commands. Putting a dir path in quotation marks "" solve issues with spaces and special characters.
