### ISSUE TITLE
使用引用块新建文档提示 Block not found

### ISSUE THREAD

**Issue by Elliootalderson** [siyuan-note/siyuan#3563]
* https://ld246.com/article/1632902916081
* https://ld246.com/article/1638533060244

我和他的情况一下,但是通过重新索引无法解决
而且只有个别文档有这种情况,有些文档则正常

**Comment by Elliootalderson** [comment]
我现在已经无法正常使用了,即便是引用已经存在的块,都会显示block not found

**Comment by 88250** [comment]
麻烦上传一下日志文件，谢谢。

**Comment by Elliootalderson** [comment]
自动好了,I have done nothing. I cant type Chinese characters here. da bu liao zi, gai si de wei ruan shu ru fa.
