### ISSUE TITLE
搜索面板

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3564]
**Visualization preview of the request.**
![SiYuan - 0 Please Start Here_001 (1)](https://user-images.githubusercontent.com/34311583/144592811-be633e82-f75f-45fc-9b3b-2931b82ab667.png)

_Originally posted by @tobealive in https://github.com/siyuan-note/siyuan/issues/3538#issuecomment-985431126_

**Comment by tobealive** [comment]
Oh, nice that you opened this and considering an implementation. So thankful for your time and efforts!

The screenshot just comes with additional errors from my side. Man, my spelling is getting bad these days 🙊. But I'm glad it serves a purpose. 

Sending love and blessings 🤍🙌

**Comment by roverway** [comment]
这个没做完吧？期待这个搜索面板。现有的ctrl+p还是不够高效，当内容比较多的时候。

**Comment by 88250** [comment]
还没有做的，现在可以用搜索页签顶顶。

**Comment by 88250** [comment]
After consideration, we decided not to consider introducing new features for the time being. The function of grouping by document tree will be added to the existing search interface, thank you.
