### ISSUE TITLE
编辑器式反链面板

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3565]
https://ld246.com/article/1638586556421

**Comment by fanglypro** [comment]
我提一个可能会成为难点的问题：思源中的展开折叠需要写入文件，这导致一个块的展开折叠只有一个状态

而 RR 当中，原文的折叠展开状态和反链中的折叠展开状态是各管各的

下面是一个 RR 中的案例，可供参考，思源之后的编辑器式反链面板应当也能完成下面的逻辑：

![temp141](https://user-images.githubusercontent.com/57083732/158955922-43755571-7345-4241-938d-c053a7205064.gif)

**Comment by jhan3657** [comment]
希望能够有更直观的上下文提示。
由于现在的反链面板缺少面包屑展示，并且如果是关联型反链，想要查看上下文只能鼠标移动到块标浮窗预览（还要手动点击右上角的上下文图标）。
建议这里的块标浮窗预览直接展现上下文并高亮显示

**Comment by 88250** [comment]
@fanglypro 分离的折叠状态先不考虑了。

**Comment by fanglypro** [comment]
> @fanglypro 分离的折叠状态先不考虑了。

那还能保持现有的类 roam research 的逻辑吗，也就是当锚文本独占时，仅显示下级列表块的第一级列表，更深级别的列表要折叠，当不是锚文本独占时，仅显示该列表项，下级列表都折叠。是否可以简单阐述下您现在考虑的设计逻辑呢？

如果不能满足现有这个逻辑的话，很有可能编辑器式反链面板还不如现有的反链面板

**Comment by 88250** [comment]
这个逻辑会保持不变的。

**Comment by fanglypro** [comment]
> 这个逻辑会保持不变的。

那就好👍🏻

但是如果满足这个逻辑的话，不就是会有分离的折叠状态码？比如对于非锚文本独占的列表项，在正文里是展开的，在反链面板里应该要折叠。

难道说展示形式还是和现在一样，只是把现在不能编辑的纯文本内容改成可编辑的富文本？这样的话浮窗还存在吗？因为反链展示的内容只是给出最小可用文本，方便定位有价值的信息，最终还是要查看反链中这个块的完整上下文，而且这个查看上下文过程应该不需要切换文档，也就是说不应该通过点击跳转对应文档来查看相关上下文（obsidian、wolai之类的反链就败在于此）。roam research 中通过分离的折叠展开逻辑以及反链面板中的面包屑达到在反链面板中直接查看上下文的功能，思源目前可以通过浮窗查看上下文，没有roam用起来顺畅，但也能用，所以我觉得，在反链中查看上下文时，一种方式是使用分离的折叠展开逻辑+反链面板面包屑，另一种方式是仍保留浮窗，两者至少应该有一个。

**Comment by fanglypro** [comment]
> 目前的实现思路是通过之前反链的逻辑（所谓的传递或关联）将需要的块捞出组装给反链编辑器，反链编辑器和文档编辑器不会是一样的块结构，反链编辑器是根据反链逻辑动态组合的块。面包屑还没有考虑是不是必须的，块标浮窗应该会保留。

那和之前相比有哪些区别呢，之前是纯文本，改了之后可以是富文本，貌似只有这么一个区别？

**Comment by 88250** [comment]
应该是这样的吧…… 允许编辑的话可能会有冲突，还在考虑。

**Comment by mozhux** [comment]
> 应该是这样的吧…… 允许编辑的话可能会有冲突，还在考虑。

不能编辑的话功能性缺失好多，希望可以搞一下，多验证一下嘛

**Comment by 88250** [comment]
@mozhux 嗯，得再考虑一下。

**Comment by fanglypro** [comment]
> > 应该是这样的吧…… 允许编辑的话可能会有冲突，还在考虑。
> 
> 不能编辑的话功能性缺失好多，希望可以搞一下，多验证一下嘛

能编辑的话确实很方便，但是D大目前考虑的设计形式下，编辑功能意义不大，因为需要浮窗才能查看完整上下文，在浮窗中编辑更合适

像roam那样能够直接在反链面板中通过折叠展开与点击面包屑查看上下文，这时候反链面板直接编辑的作用会比较大，不然不如用浮窗编辑方便

**Comment by woaihuangxueying** [comment]
新人试用了现在的反链面板，
每次查看上下文都要等待几秒打开浮窗，非常非常非常地打断思路
希望可以直接在反链面板展开、折叠上下文。
还有就是希望反链面板搜索可以支持模糊搜索，多关键词搜索。
期待这个功能的改进。

**Comment by haogeek** [comment]
用了几个月思源笔记下来感觉最大的问题就是在于反链面板，也就是反链整理成文的操作体验，这也是我觉得思源笔记相比RR、Logseq之流的主要缺陷，而这其中主要的原因就在于“浮窗”。

通过反链面板打开块浮窗，在浮窗里早就可以实现编辑了，也早就可以显示富文本、面包屑，看样子浮窗完全可以解决上面聊到的种种问题，那为什么还需要改反链面板？很显然，答案只有一个——浮窗不好用。

浮窗对于正向链接来说是很好用的，百科类网站那种浮窗体验已经存在了这么多年了，感觉也很好，但浮窗对于反向链接和汇总和整理来说体验却很糟糕，主要体现在以下几点：
1. 每次都需要鼠标定位停留，等待一秒左右浮窗才显示，这个效率就比较低。
2. 鼠标一挪走，浮窗就没了，想要持续显示或同时显示多个块浮窗就只能pin住。
3. 虽然浮窗有pin功能，但由于浮窗在整个界面里占的面积较大，这样整个屏幕最多能放下3个浮窗，而这时候文档编辑区域已经被遮挡得所剩无几了，想要在pin住的浮窗和当前编辑的文档之间自由切换、转移内容（daily notes的常用操作）就很难做到。

Logseq之类的大纲笔记是怎么做的呢？它的右侧边栏是用来pin的，每个pin住的块依次排列，不存在遮挡，并且占用的屏幕空间并没有那么大，这样就可以很方便地把右侧边栏作为“素材库”，而在左边的文档编辑器里对其进行整理。甚至Logseq的右侧边栏还可以作为临时暂存区，这样可以把某些内容块暂时扔到这里，而切换当前编辑的文档时并不会影响到这部分暂存，在合适的时机再把它们从暂存区拿出来放到合适的文档中（想想iPhone移动桌面图标有多麻烦就知道这个意思了）。

各种大纲类笔记软件没有选择把反链放在右侧，而是放在文档底部，想必很大程度上就是为了把右侧边栏留出来，另一方面把反链放在文档底部也更方便展开反链内容，这样反链本身就组成了文档内容，一目了然，这一点之前也有很多人已经提到过。这是思源笔记跟其他大纲双链笔记相比的一个决定性差异，即思源笔记并没有把右侧边栏用作可以pin内容的“素材库”，而是把它作为了反链索引本身，并且默认情况下切换当前文档，反链面板就会变，除非通过快捷键以分屏方式打开反链面板，这跟“素材库”和“暂存区“式的操作体验相比就差的很多了。

总的来说，浮窗机制当然可以保留，但**如何让多个素材内容块能够并列且持久显示，不受文档切换的影响，可以自由地在多个块之间转移和整理内容，才是思源笔记解决反链操作体验的根本**。思源笔记本身UI可以自由分屏，这是很大的优势，但这个优势却没有很好地跟反链操作结合起来，是个遗憾，而且即便不考虑反链，目前的分屏也太拥挤了，体验并不好。其实如果pin住的浮窗能拖到第二台显示器上，倒也算是个权宜之计。

**Comment by 88250** [comment]
@haogeek 

感谢建议，目前可以试试这个操作：不用联动反链面板（Alt+7），用文档反链页签，然后在反链条目中 Alt+Click 打开，这样就可以不受文档切换影响并且并列显示了。

**Comment by haogeek** [comment]
@88250 是说Alt+B打开的反链页签吧？我上面提到的“除非通过快捷键以分屏方式打开反链面板”说的就是这个，但使用Alt+Click打开反链条目的时候还是前台打开的，这样每次还是需要在切回到反链页签再点击其他的条目。而且对于这个右分屏（包含反链页签和这批打开的反链条目）来说，还是只能一次查看一个页签的内容，没达到平铺的效果。而且如果当前激活的页签是反链页签，那么按Alt+Click会再次向右分屏，而不是直接排在反链页签右侧。

![image](https://user-images.githubusercontent.com/4096257/166941865-88d384e6-9a36-447d-bc4c-e97f135696ef.png)

其实如果是用Shift+Click在反链页签中打开反链条目，使其依次往下排列，这样是比较接近右侧边栏平铺效果的，但这样会导致反链页签（反链面板）被压缩，所以我才说反链面板最好不要跟显示素材的区域放在一起。而且点开的条目的越多，每个条目也会被压缩得越短，虽然每个条目内部有滚动条，但更好的方式是让所有这些条目有一个整体的滚动条

![image](https://user-images.githubusercontent.com/4096257/166940813-f450ac4d-40b3-494f-b2b4-02ad45891e57.png)

**Comment by 88250** [comment]
大概明白你的意思了，编辑器式反链面板的改进估计不会包含这个，我们先解决反链编辑的问题。

“素材临时区”这个后面考虑，感谢提议。

**Comment by haogeek** [comment]
好的，这个改动要实现起来确实是个大工程，持续期待。

P.S.近期的一些优化和修复已经解决了我之前记录下的不少问题，赞！

**Comment by woaihuangxueying** [comment]
这个也是个大工程，除了关系图，感觉就是这个更新最重要了

**Comment by whuwangyong** [comment]
在整理反链时，将反链面板的内容拖动到正文后，好像无法撤销回去？

**Comment by 88250** [comment]
@whuwangyong 仅支持在同一个编辑器中撤销。

**Comment by whuwangyong** [comment]
Alt + B 学到了！ 但是只有光标在正文时才有效，光标在文档标题上时无效。

**Comment by whuwangyong** [comment]
> 仅支持在同一个编辑器中撤销。

@88250 这个还是稍微有点危险。如果不小心拖错了，你不知道这个块之前在哪里。万一是从一个完整的文档里面拖走了，那篇文档就不完整了。

所以一定注意看清标题，只从2022-05-05这种daily notes里面拖。

**Comment by 88250** [comment]
后面再想办法支持全局撤销。

**Comment by Elliootalderson** [comment]
反链面板和提示面板, 也支持悬浮小窗口吗

**Comment by haogeek** [comment]
今天才发现原来把反链内容作为引用块复制到正文时，并不是像roam research那样展示完整的块内容，而只展示有限的锚文本，对于列表块会仅以当前层级转换为段落块，而非带上子层级。https://github.com/siyuan-note/siyuan/issues/4830

这样就无法实现 https://ld246.com/article/1634538470534 里提到的流程。

而且就算锚文本能显示很长，但整段文字看上去都是锚文本的样式，也很难看（思源并不支持样式嵌套，也就是说原本文本里的粗体、链接、颜色等等在转换为锚文本之后都只剩下了锚文本样式）。
![image](https://user-images.githubusercontent.com/4096257/170635053-126189e1-0638-4576-88b3-0f56dd08b0aa.png)

这个一定要改进啊，不然我实在不知道除了用嵌入块之外还有什么办法既能在正文里完整呈现反链内容，又能保持两者同步。其实从概念上讲，嵌入块似乎是更符合上述需求的，样式和内容都得到了完整的保留和同步，但嵌入块有以下几个问题：

1. 每一个嵌入块都被封在了一个框里，视觉上干扰很大，并且不能在正文里直接编辑，而需要点开浮窗才能编辑。其实这个框可以淡化，或换成一个小图标，仍然保留通过快捷键开启浮窗的能力，同时也支持直接在正文里编辑。
2. 与复制引用块不同，嵌入块所有出现的地方都是完全一致的，这样就做不到多版本化。而引用块可以通过不同的锚文本来实现多版整理草稿，以及在不同的文档中以不同的词句呈现。
3. 不能重新排版，如下图，第二个框里的段落要放到第一个框下级是做不到的。但思源本身每个块都有独立ID，改变排版层级应该不会影响到链接关系，所以理论上是可以支持重新排版的。
![image](https://user-images.githubusercontent.com/4096257/170636806-f1ff63b5-8325-484e-a75c-f00fca7cce04.png)

综上，还是需要做一个当前引用块和嵌入块形式之间的“中间态”，既能像嵌入块那样完整呈现内容和样式，又能在正文里直接编辑和重排版，且不影响链接关系。

P.S. 反链面板目前直接拖动到正文是“剪切移动”，要复制引用块还需先等待打开浮窗，再在浮窗里复制，然后回到正文粘贴，这个效率太低了，希望能实现其他朋友提过的通过快捷键直接拖动为引用块的操作。

**Comment by primejava** [comment]
反向链接就像是5G一样，没有几个人需要反向链接

**Comment by leolee9086** [comment]
我想还是有很多人需要的  比如说我..........

**Comment by jhan3657** [comment]
> 反向链接就像是5G一样，没有几个人需要反向链接

你不用不代表别人不用，很期待思源的反链能够进一步优化。

**Comment by qifengle1998** [comment]
> 反链是伪需求，建议停止
记笔记是伪需求，建议别记笔记

**Comment by Elliootalderson** [comment]
打字是伪需求, 建议我们见面讨论

**Comment by mlzxy** [comment]
> 今天才发现原来把反链内容作为引用块复制到正文时，并不是像roam research那样展示完整的块内容，而只展示有限的锚文本，对于列表块会仅以当前层级转换为段落块，而非带上子层级。#4830

非常同意 *“引用链接” 应该支持内容嵌入*，不应该只局限于“锚文本”。

---

用 Roam 的语法 https://twitter.com/roamresearch/status/1226707275823206401  举例：

假设我引用了一篇文章里的语句，`[text](((annotation_id)))`，我会用自己的语言重述一下文章内容，而不仅仅是粘贴原文。 <ins>正因为会用自己的语言总结，就会有更丰富的编辑需求</ins>，如高亮/粗体/公式 等。

- 希望：`[summary in ==my language==, $E=mc^2$](((annotation_id)))`

- 如果只能用锚文本: `[summary in my language in plain texts without any kind of formats](((annotation_id)))`

**Comment by fanglypro** [comment]
> > [#3565 (comment)](https://github.com/siyuan-note/siyuan/issues/3565#issuecomment-1158448176)
> 
> 回复一下自己，分享一下自己的 workaround。
> 
> 由于Siyuan目前的 “引用链接” 只是锚文本，不支持内容嵌入，我的做法是这样的：
> 
> 1. 把 “引用链接” 最小化，如 🔗 一个 icon 来作为锚文本
> 2. 在锚文本的旁边，写自己的 summary
> 
> 这样既可以编辑丰富的内容，也可以链向以前的材料。

可以试一下思源里面的这个按钮，和你所说的类似

![image](https://user-images.githubusercontent.com/57083732/181405663-2882439b-d80e-4217-954e-fba93abf3cc4.png)

这个功能是模仿 roam research 的：

![image](https://user-images.githubusercontent.com/57083732/181405844-e83e50aa-f20c-44cf-acff-0ba4950e1d75.png)

**Comment by fanglypro** [comment]
现有的数字浮窗反链其实就是一种编辑器式反链面板，当然两者的反链计算范围不同，数字浮窗反链不计算子块，反链面板计算子块，但在很多时候两者计算范围差不多，可以互相替代，那为什么平常很少有人提到这个数字浮窗反链呢，大家提建议也集中在反链面板，很大原因在于数字浮窗反链太难用了，作为一个编辑器式反链还不如非编辑器式反链。后续设计编辑器式反链面板的时候也应该综合考虑数字浮窗反链一起设计。

**Comment by haogeek** [comment]
> 很大原因在于现有的引用计数浮窗反链太难用了

赞同你所说的，这本质上跟我上面的评论说的一样，“**浮窗**”这种形式根本就不适合于反链编辑，操作起来非常闹心。目前的引用计数浮窗就很像我上面说的关于“反链面板和素材条目被压缩”的情况。

一直在期待这些诉求能够早日得到改进。

**Comment by yuyuyu-github** [comment]
> > 很大原因在于现有的引用计数浮窗反链太难用了
> 
> 赞同你所说的，这本质上跟我上面的评论说的一样，“**浮窗**”这种形式根本就不适合于反链编辑，操作起来非常闹心。目前的引用计数浮窗就很符合我上面说的关于“浮窗遮挡编辑区“以及“反链面板和素材条目被压缩”的情况。
> 
> 其实归根结底，反链操作改进的核心应该在于提升主题文档的编辑体验，而不是反链素材本身的编辑体验，所以如果只是实现了编辑器式反链面板，恐怕还是无法改善反链操作体验。 所谓主题文档本身的编辑体验，就包括多素材平铺展示、保持维持主文档上下文且不必反复切换页签、拖拽素材到主题内支持选择剪切或复制、支持选择引用或嵌入、支持保留原始排版、支持包含子块等。
> 
> 一直在期待这些诉求能够早日得到改进。

字词，在使用反链面板的时候，浮窗一直在拖慢我的节奏，打断我的思路

**Comment by wrwe3888** [comment]
Logseq的反链面板非常不错，D大在logseq上改进就好了！
