### ISSUE TITLE
https转圈圈界面, 不能进入系统,  发现pdf.js仍然使用了http的地址,其他资源正常

### ISSUE THREAD

**Issue by xibaoning** [siyuan-note/siyuan#3566]
https转圈圈界面, 不能进入系统,  发现pdf.js仍然使用了http的地址,其他资源正常, 寻找main.js代码发现: n._SSL=!1,  导致SSL永远不生效, 
n._SSL='https:' == document.location.protocol 后成功进入了https系统

**Comment by 88250** [comment]
请参考帮助文档内核参数章节，`--ssl`  启动参数。

**Comment by xibaoning** [comment]
已经设置了,ws也设置了,  main.js修改后正常了, 说明是静态文件main.js里面的bug, 与--ssl等后台参数无关 ?

**Comment by 88250** [comment]
正常情况下，前端静态资源文件里面的代码在启动时内核会根据参数去替换的。

**Comment by xibaoning** [comment]
嗯, 这种纯判断客户端的协议而已, 好像不用后台去替换, 客户端判断就行了, 然后发现main.js同样写死了 :"6806" 改成 
":"+location.port ,  测试发现端口也可以任意改了,
可能我想的简单了,你们可能有其他原因不这么设置,  见谅

**Comment by 88250** [comment]
建议不要直接改代码，不然可能有其他问题。

**Comment by xibaoning** [comment]
嗯,知道了, 只是好奇为什么出现这些看起简单的问题, 所以试了试

**Comment by 88250** [comment]
如果加参数确定不生效的话麻烦告诉我们，可能是 bug。

**Comment by yanickxia** [comment]
最新版本同样的问题 + 1 @88250
