### ISSUE TITLE
Where to restore note history ?

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#3569]
### 描述问题 Describe the problem

I can't find where to restore note history ?!

![image](https://user-images.githubusercontent.com/33789516/144736036-a9435443-7f83-4c10-a016-85e5f7944d4b.png)

![image](https://user-images.githubusercontent.com/33789516/144736092-58985fd6-ef9a-49fa-b6e3-96348c43ddf7.png)

**Comment by 88250** [comment]
Right-click on a notebook in doc tree panel:

![image](https://user-images.githubusercontent.com/873584/144740311-cc082ac4-e789-43c0-a7f6-e6eabb702b6c.png)
