### ISSUE TITLE
希望添加Front-matter语法

### ISSUE THREAD

**Issue by ACGLife** [siyuan-note/siyuan#3574]
## 希望在文件最上方以 `---` 分隔的区域添加Front-matter语法而不是直接转成分隔线

例如：
```
---
title: Hello World
date: 2013/7/13 20:46:25
---
```

**Comment by roverway** [comment]
现在就可以的，看起来是两条分割线中间夹着一堆内容。注意中间内容的换行用shift+enter，不要直接回车。
我用这个配合hexo博客来用。

**Comment by ACGLife** [comment]
> 现在就可以的，虽然看起来是两条分割线中间夹着一堆内容，但不影响其他软件识别。 注意中间内容的换行用shift+enter，不要直接回车。 我用这个配合hexo博客来用。

想要有一个预览效果，而且导出markdown首尾多了一个空行，希望优化一下

**Comment by 88250** [comment]
这个语法增加以后，可能会和现在的属性功能有冲突，能够合二为一应该会更好。

在没有考虑清楚之前，暂时不会引入特性了，后续如果还有其他用户反馈这个需求，我们会关联到这个 issue 上，等考虑清楚以后再重开，感谢提议。
