### ISSUE TITLE
搜索界面改进

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#3575]
不管匹配项目和预览窗格左右还是上下分布，目前匹配项目窗格都存在问题：由于一行同时显示匹配内容和所属笔记路径，当宽度不够的时候，匹配项目就会被压缩到几乎不可用的程度，具体见下图（截图最下面两行干脆完全看不到匹配项目了）。
搜索是高频使用特性，希望对搜索界面的优化能够提前。
关于这里提及的问题，我能想到的解决方案就是实现匹配项目和所属笔记的树状排列（类似vscode），或者有其他的方案也行。
感谢两位开发者。
![image](https://user-images.githubusercontent.com/657850/144980505-37f494ed-54ea-4ed8-a41b-c472bc59ebe0.png)

**Comment by 88250** [comment]
搜索结果树形目录应该不会考虑，先做 https://github.com/siyuan-note/siyuan/issues/3564 完这个再看反馈，谢谢。
