### ISSUE TITLE
Preview & Pinning of .pdf Files

### ISSUE THREAD

**Issue by tobealive** [siyuan-note/siyuan#3576]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
Working with ´.pdf´ files is in many cases the same workflow for me as working with other internal notes. Having the **possibility of previewing and pinning** such files when hovering over **a link** to that file or when hovering over **an annotation** that was made inside the pdf and reflinked in a block. This would make the user experience with SiYuan even better.

### 描述可能的最优解决方案 Describe the optimal solution
This functionality already exists for hovering over internal links. This action shows a preview window which can be also pinned.
If it's technically possible, implementing the same functionality for ´.pdf´ files.

### 描述候选的解决方案 Describe the candidate solution
\---

### 其他信息 Other information

I've seen you are working on a feature for pinning a Tab. This could already be a partial workaround for the issue and make it possible to pin ´.pdf´ files.

**Comment by 88250** [comment]
Hello, to preview PDF window has a lot of technical details that need to handle,  although it is possible I think.

We need time to think about it, please remain this issue open.

**Comment by 88250** [comment]
After a long period of observation, this requirement is not considered for the time being, thank you.
