### ISSUE TITLE
行内公式使用键盘输入``只能输入一个字符

### ISSUE THREAD

**Issue by NAIXIL** [siyuan-note/siyuan#3579]
如果我使用快捷键输入的时候，是正常的；如果我直接采用Markdown语法，则无法输入行内公式。
![image](https://user-images.githubusercontent.com/49865574/145052712-3e309d96-0724-4fe7-9cc9-b3ab119f2bdd.png)

这个是录屏：
https://user-images.githubusercontent.com/49865574/145053033-4e605d27-4509-495b-a4f5-4e50acee320b.mp4

**Comment by 88250** [comment]
你好，这个是所见即所得编辑时的设计选择：即使用 md 语法元素排版完以后再编辑就跳出。

如果不这样的话，就无法跳出公式（或者其他元素排版了），这个设计选择是二选一的，我们选了前者。

感谢反馈。

**Comment by NAIXIL** [comment]
好的，原来如此， 谢谢

**Comment by 88250** [comment]
跳出的细节应该还有改进空间，等后面我们再试试看。
