### ISSUE TITLE
快速打字时，光标乱跳位置，导致输入错位

### ISSUE THREAD

**Issue by isPoto** [siyuan-note/siyuan#3582]
### 描述问题 Describe the problem

快速打字时，光标会跳位。末位光标跳到文字中间。

录制视频中所示，正常或较慢速度打字正常，但快速打字时光标就会从末位跳到中间，导致输入错位。

### 期待的结果 Expected result

打字时，光标始终在末位。正常接收并显示用户敲打的字符

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/59009389/145154302-65460cca-8890-408a-9c69-7d9a978b526d.mp4

### 版本环境 Version environment

* Version: v1.5.4
* Operating system: Win10 21H1
* Browser (if used): Vivaldi 5.0.2497.24 (Stable channel) (64-bit)

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/7673643/siyuan.log)

**Comment by netdog2019** [comment]
1.5.5 a7同样出现这个问题，输入数字会乱跳，但是输入字母好像不会，微软输入法和手心输入法都有这个问题。

**Comment by YawN0305** [comment]
我用的1.5.4也有这个问题，win10平台，搜狗拼音输入法

**Comment by 88250** [comment]
如果还能重现的话请跟帖，谢谢。
