### ISSUE TITLE
PDF在黑暗模式下的适配问题导致图片反色

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#3583]
### 描述问题 Describe the problem

PDF在黑暗模式下的适配问题导致图片反色。不论主题，只要在黑暗模式下

### 期待的结果 Expected result

图片不再反色

### 截屏或者录屏演示 Screenshot or screen recording presentation

示例：

![image-20211208194211-fapty84](https://user-images.githubusercontent.com/63145205/145204773-7fe22a30-7366-4c5b-9f9f-e86f1433aca9.png)

![image-20211208194240-4tm28ti](https://user-images.githubusercontent.com/63145205/145204867-ec5d80a2-faa0-4354-9bff-ec74ce2c6d0b.png)

![image-20211208195019-lt7wg5g](https://user-images.githubusercontent.com/63145205/145204882-2ecc41ec-ea82-445d-b8d6-0c3e748fce66.png)

![image-20211208195030-92shlcu](https://user-images.githubusercontent.com/63145205/145204894-0953c546-8c08-412f-9b26-91adf9219b6a.png)

### 版本环境 Version environment

* Version: 1.5.4
* Operating system: Windows11 22000.348.0

**Comment by 88250** [comment]
你好，这个问题暂时没有办法解决，只能反色处理了，抱歉抱歉。
