### ISSUE TITLE
为超链接输入框中加入标题输入框

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#3586]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在 Web 页面中超链接的标题可以在鼠标停留时显示, 在思源中鼠标停留显示的是链接 URL, 有朋友依据该特性实现了备注[【Tsundoku】 v1.0.1 添加行内备注样式 - 链滴](https://ld246.com/article/1638180227027)

但是由于链接 URL 中的内容不支持搜索, 而链接标题支持搜索 [Issue #3427](https://github.com/siyuan-note/siyuan/issues/3427?utm_source=ld246.com) 但无法插入, 希望为超链接的插入面板添加一个标题输入框(见下图), 并在鼠标停留时可同时显示超链接标题与链接 URL.

![image](https://user-images.githubusercontent.com/49649786/145339570-620b8e24-4688-46af-858a-00a3b91cb544.png)

### 描述可能的最优解决方案 Describe the optimal solution

超链接的插入面板添加一个标题输入框
在鼠标停留时同时显示超链接标题与链接 URL

**Comment by aptexd** [comment]
我觉得这个很有用

**Comment by Zuoqiu-Yingyi** [comment]
目前使用起来貌似 `鼠标停留时同时显示链接标题与链接 URL` 功能并未实现, 导致超链接的标题仅能在搜索时使用, 感觉有些鸡肋😂

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 收到，近期试下如何改进。
