### ISSUE TITLE
[建议] 右上角角标弹出的被引用位置弹窗能默认显示上下文

### ISSUE THREAD

**Issue by oufu99** [siyuan-note/siyuan#3588]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
查看被引用的地方,需要有上下文帮助回忆或者帮助理解

1.给一篇文章做了笔记,想查看这些不同时间点做的笔记
2.看此笔记和别的笔记样子什么关联

### 描述可能的最优解决方案 Describe the optimal solution
弹窗直接显示上下文,每个上下文的框有个宽度(现在已经有了)就不会因为被引用太多导致看不过来

### 描述候选的解决方案 Describe the candidate solution
在设置中有个的选项,可以选择是否默认显示上下文

### 其他信息 Other information
记忆最重要的就是联想,回忆最重要的是线索,如果没有上下文,无法知道这篇笔记被用在了哪里,因为外面被引用的地方和弹窗显示出来的是一模一样的,不显示上下文完全没有作用,就像这个,我知道了在这篇笔记里引用了这一句话,但是完全没有作用。。。
![image](https://user-images.githubusercontent.com/18545756/145390494-effbd9ba-8945-44c1-9d31-b0fc0736119b.png)
后面笔记越来越多,连接和引用也越来越多的时候,没有上下文的提示,完全是想不起来这单单的一句话是什么时候因为什么目的被引用的的了

**Comment by 88250** [comment]
* 这个之前的版本我记得有尝试过，后来才调整为默认不加载上下文的
* 面包屑导航已经起到了一些上下文的作用
* 暂时不考虑加选项了，近期交互方面也不会做太大调整了

我们会继续收集类似反馈，如果觉得有必要的时候会重开，感谢。
