### ISSUE TITLE
建议标签、块等筛选功能中，支持声母模糊匹配，非常方便

### ISSUE THREAD

**Issue by jazzson** [siyuan-note/siyuan#359]
建议标签、块等筛选功能中，支持声母模糊匹配，非常方便。比如
输入 bq ,就可以自动显示标签、表情、本钱 等所有包含bq声母的标签

**Comment by 88250** [comment]
你好，经过考虑我们觉得这个可能是个没有太大意义的需求，因为输入法在输入 `bq` 以后也能打出 `标签` 来。

如果考虑不周之处请跟帖讨论，感谢提议。
