### ISSUE TITLE
文档树 Emoji 和标题 Emoji 不匹配

### ISSUE THREAD

**Issue by YIMINGMA** [siyuan-note/siyuan#3595]
### 描述问题 Describe the problem

已打开使用系统原生 emoji 选项，文档树显示的是原生的，但是文档标题显示的并不是原生的，可能是微软的？

### 期待的结果 Expected result

文档标题显示系统原生 emoji。

### 截屏或者录屏演示 Screenshot or screen recording presentation

下图为《思源笔记用户指南》的致谢部分截图。

<img width="486" alt="截屏2021-12-10 10 27 20" src="https://user-images.githubusercontent.com/45311510/145560122-fdc8e0e7-c9a4-4499-a931-104ff6cc2de8.png">

下图来自[unicode.org](https://unicode.org/emoji/charts/full-emoji-list.html)的 emoji 渲染结果显示。

<img width="1106" alt="截屏2021-12-10 10 36 01" src="https://user-images.githubusercontent.com/45311510/145560491-90f770b2-63c6-4b87-bd85-50e36243995b.png">

### 版本环境 Version environment

* Version: 1.5.4-mac-arm64
* Operating system: macOS Monterey 12.0.1
* Browser (if used): None

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/7692064/siyuan.log)

### 更多信息 More information

None

**Comment by Vanessa219** [comment]
好像无法重现，使用默认主题试试。
![image](https://user-images.githubusercontent.com/970828/145592427-f274cdf2-f6d9-42df-aab4-ae91a1b950e6.png)

**Comment by YIMINGMA** [comment]
我的默认主题下还是这样，删除`.config`目录下配置文件&卸载重装后也是这样😂
<img width="837" alt="截屏2021-12-10 14 51 20" src="https://user-images.githubusercontent.com/45311510/145593594-f3502df8-e017-4cb0-bf9a-73869b5c9a7b.png">
<img width="1363" alt="截屏2021-12-10 14 51 37" src="https://user-images.githubusercontent.com/45311510/145593609-4665f56a-c77b-4bd7-95c8-7f65101af995.png">
<img width="1398" alt="截屏2021-12-10 14 51 53" src="https://user-images.githubusercontent.com/45311510/145593623-b57828fd-9914-4dcf-96e7-246962c64f99.png">

**Comment by 88250** [comment]
你是否有安装过 Emoji 字体？这个 Emoji 看上去像是 Windows 版的字体文件。

**Comment by YIMINGMA** [comment]
在配置终端时安装了一些诸如Meslo for Powerline之类的字体

**Comment by 88250** [comment]
这个问题现在的版本还存在吗？我们这里无法重现，先关闭了，如果有补充信息欢迎继续提供，非常感谢。
