### ISSUE TITLE
异步模板外界交互

### ISSUE THREAD

**Issue by xibaoning** [siyuan-note/siyuan#3603]
异步模板选择后, 远程请求一个地址(可能耗时,操作时有等待提示), 然后将返回结果渲染到笔记页面中,  这样就提高了外部数据的获取, 外部可以后台生成思源的笔记语法,返回模板内容

或者
本地模板直接支持script标签:
<script>
//这里就可以进行远程获取数并渲染到当前页面
</script>

虽然可以用iframe,但iframe不是直接生成模板内容

**Comment by 88250** [comment]
没太明白应用场景，麻烦举例描述一下，谢谢。

**Comment by xibaoning** [comment]
@88250 
![image](https://user-images.githubusercontent.com/48142659/145738377-67d31147-795a-4e40-8909-794ef59efea2.png)

**Comment by xibaoning** [comment]
不一定是通过模板, 如果能通过什么方式渲染外部数据来生成笔记数据, 可拓展笔记的使用范围

**Comment by 88250** [comment]
数据写入可通过 [API](https://github.com/siyuan-note/siyuan/blob/master/API.md) 实现，如果是需要剪藏的话可以用浏览器扩展。

**Comment by xibaoning** [comment]
API有给他一个字符串内容, 然后返回渲染的结果么,目前好像只能渲染磁盘上的MD文件

**Comment by 88250** [comment]
数据格式解析的话要用 [Lute](https://github.com/88250/lute)，比如支持将 Markdown 渲染为思源 DOM 格式。
