### ISSUE TITLE
给反向链接加个标识

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3612]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在看文档的时候，虽然可以通过`反向链接`看到文档的被引用情况。
但是，这不是很方便，很多时候我们可能并不想看到整个文档的反向链接，因为有时我们只是看一个文档的一部分而不是整个文档，这种时候最好是正文中的反向链接有一个标识，这样我们浏览文档时可以清楚的看到这个地方是否有反链。

### 描述可能的最优解决方案 Describe the optimal solution

给被引用的块加上标识，以便让我们看文档的时候知道它有反链。

**Comment by 88250** [comment]
通过块引用计数可以查看。

**Comment by choyy** [comment]
才注意到
