### ISSUE TITLE
题头图使用网络图片

### ISSUE THREAD

**Issue by everleap** [siyuan-note/siyuan#3613]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
文档题头图使用

在题头图使用时可以选择使用网络链接而非只能选择本地图片
### 描述可能的最优解决方案 Describe the optimal solution

例如notion、wolai等

**Comment by netdog2019** [comment]
而且最好能在模版中设置题头图，现在好像没法设置。

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/2951

**Comment by 88250** [comment]
> 而且最好能在模版中设置题头图，现在好像没法设置。

模板还不行，可考虑单独开个 issue 记录，谢谢。
