### ISSUE TITLE
使用快速滚动条时题头图显示错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#3614]
### 描述问题 Describe the problem

使用快速滚动条跳转时题头图会跟随跳转, 而且在向上翻页时题头图有时会闪出

### 期待的结果 Expected result

题头图只在题头显示, 不随快速滚动条跳转, 且在向上翻页时不会闪出

### 截屏或者录屏演示 Screenshot or screen recording presentation

![思源笔记-bug反馈-05](https://user-images.githubusercontent.com/49649786/146205727-d9cc2801-f24d-4fe2-9467-d4eb23eaecae.gif)

### 版本环境 Version environment

* Version: 1.5.4

**Comment by 88250** [comment]
v2.0.24 依然能重现。
