### ISSUE TITLE
Firefox编辑笔记有卡顿

### ISSUE THREAD

**Issue by allblue** [siyuan-note/siyuan#3620]
### 描述问题 Describe the problem

通过6086端口在firefox、waterfox等火狐系浏览器编辑笔记时，会频繁出现卡顿现像，具体有
1. 退格键无效或滞后太久，但用鼠标手动选取后再按退格键通常能立即生效
2. 方向键无法移动光标
换用chrome、edge、brave等chromium系浏览器均无此问题。

### 期待的结果 Expected result

改善firefox浏览器支持，可与chrome浏览器一样流畅编辑文档

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

* Version:  1.5.4
* Operating system:  windows10、Manjaro
* Browser (if used):  Firefox 95、Waterfox G4.0.3、Brave 1.33.106、Edge 95

### 日志文件 Log File

无

### 更多信息 More information

无

**Comment by 88250** [comment]
你好，目前几乎没有做浏览器兼容，请使用最新的 Chrome。近期无法做出改进，先关闭了，抱歉抱歉。
