### ISSUE TITLE
支持笔记本设置独立的排序规则

### ISSUE THREAD

**Issue by mingyong-g** [siyuan-note/siyuan#3623]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
当有多个笔记本，每个笔记本定位场景不同时，希望能够单独设置笔记本的排序规则，而不是采取全局的排序规则。

我有三个笔记本A，B, C ，
- A用于记录生活日记，我希望A能够按照创建日期排序；
- B用于记录学习笔记，我希望B能够按照修改文件名排序，这样我可以通告设置前缀，将重要的内容排在笔记本前面；
- C用于记录工作只能，我希望C能够按照修改日期进行排序，这样我可以第一时间获取最近的工作内容，快速进入之前的工作内容。

### 描述可能的最优解决方案 Describe the optimal solution

- 全局排序规则作为默认的规则，此外各个笔记本可以单独设置排序规则，若没有则采取全局排序规则

**Comment by 88250** [comment]
目前无法支持，如果以后有实现思路了会考虑，感谢提议。

**Comment by TWQM** [comment]
就这个需求请问有进一步的更新计划吗？

**Comment by 88250** [comment]
抱歉没有。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月25日(周日) 晚上9:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 支持笔记本设置独立的排序规则 (Issue #3623)




 
就这个需求请问有进一步的更新计划吗？

**Comment by 88250** [comment]
只是笔记本级排序已经支持，右键笔记本可以看到。
