### ISSUE TITLE
PDF 预览效果添加使用浏览器和本地 PDF 工具打开

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#363]
**期望的pdf预览效果：** 

![图片](https://user-images.githubusercontent.com/15924513/97454287-8b0fcf00-1971-11eb-83b9-1777eaea73d0.png)

参考：
- https://github.com/mozilla/pdf.js
- https://github.com/tomoki1207/vscode-pdfviewer

_Originally posted by @lss6378 in https://github.com/siyuan-note/siyuan/issues/115#issuecomment-717993793_

**Comment by 88250** [comment]
直接用浏览器打开吧……
