### ISSUE TITLE
安卓客户端屏幕尺寸自动适配问题

### ISSUE THREAD

**Issue by Morganwan90** [siyuan-note/siyuan#3630]
主要系折叠屏或拥有多个屏幕尺寸的设备。

目前的情况系：
小屏或者打开折叠屏状态下，都分别可以打开思源客户端。
但是小屏切换至折叠屏打开状态，或者折叠屏打开状态切换至小屏会闪退。

期望状态：
当尺寸发生变动时自动适配新的屏幕尺寸。

**Comment by 88250** [comment]
这个没有设备可以调试，先关闭了，感谢反馈。
