### ISSUE TITLE
引入块在复制时复制文字本身

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3631]
引入块在复制时，怎么复制文字本身，而不是链接？
如果目前思源不支持，能不能添加这个功能？

**Comment by 88250** [comment]
“引入块”指的是引述块吗？

**Comment by Morganwan90** [comment]
> 引入块在复制时，怎么复制文字本身，而不是链接？ 如果目前思源不支持，能不能添加这个功能？

是指只复制锚文本？试了一下，就是一个新的引述块，框选文字，第一次会复制这个引述快。重复一次操作，会变成复制纯文本。

![截图_20213520063544](https://user-images.githubusercontent.com/61633409/146753965-029dc29e-b341-4e3b-80ba-7c10ae160262.gif)

**Comment by bestv5** [comment]
> “引入块”指的是引述块吗？

是的，复制到别的文本编辑器后，只是复制的引用块的id

**Comment by bestv5** [comment]
> > 引入块在复制时，怎么复制文字本身，而不是链接？ 如果目前思源不支持，能不能添加这个功能？
> 
> 是指只复制锚文本？试了一下，就是一个新的引述块，框选文字，第一次会复制这个引述快。重复一次操作，会变成复制纯文本。
> 
> ![截图_20213520063544](https://user-images.githubusercontent.com/61633409/146753965-029dc29e-b341-4e3b-80ba-7c10ae160262.gif)

是我没说清楚，是复制到别的文本工具比如word 记事本等。

**Comment by 88250** [comment]
> > “引入块”指的是引述块吗？
> 
> 是的，复制到别的文本编辑器后，只是复制的引用块的id

块 ID 可以在这里复制：

![image](https://user-images.githubusercontent.com/873584/146772332-96de5b28-1524-43ad-8844-311d6395d332.png)

**Comment by 88250** [comment]
@Morganwan90 这个操作应该是符合预期的。

**Comment by bestv5** [comment]
> > > “引入块”指的是引述块吗？
> > 
> > 
> > 是的，复制到别的文本编辑器后，只是复制的引用块的id
> 
> 块 ID 可以在这里复制：
> 
> ![image](https://user-images.githubusercontent.com/873584/146772332-96de5b28-1524-43ad-8844-311d6395d332.png)

可是，我不想复制id，我想复制的是文字。
比如，下面的内容
[[引述块id]]后面继续添加的文字。
引述块内容是：刑法

我复制黏贴到word后，希望是刑法后面继续添加的文字。而实际是[[引述块id]]后面继续添加的文字。

**Comment by 88250** [comment]
@bestv5 在编辑器内暂时不行，因为需要编辑器粘贴，如果没有原始格式的话粘贴不了。复制到外部的话建议在导出预览中复制，感谢反馈。

PS 这个较引用，不是引述。

**Comment by bestv5** [comment]
> @bestv5 在编辑器内暂时不行，因为需要编辑器粘贴，如果没有原始格式的话粘贴不了。复制到外部的话建议在导出预览中复制，感谢反馈。
> 
> PS 这个较引用，不是引述。

那能不能增加一个快捷键，支持这种复制？导出再复制，不光麻烦，也有可能格式变了……

**Comment by Vanessa219** [comment]
复制的时候会将 md 拷贝到 text/plain 中，sy 格式拷贝到 text/html 中。需要使用 md 的话直接粘贴到记事本或者任意支持 text/plain 的应用中即可。
