### ISSUE TITLE
iOS 内核连接中断

### ISSUE THREAD

**Issue by MrLucy** [siyuan-note/siyuan#3634]
ios  上滑动使App后台运行后，再返回，内核中断错误，点击界面无任何反应

![BUG](https://user-images.githubusercontent.com/12154906/146862313-fc5d72fd-0b2c-4b3d-945e-5c9bf6a86a55.jpg)

**Comment by Vanessa219** [comment]
这个问题应该已经修复了，你用的版本是？

**Comment by MrLucy** [comment]
1.5版本&nbsp; 今天刚从B3log哪里通过testFlight下载下来用的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 中午12:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] ios 内核中断 (Issue #3634)





 
这个问题应该已经修复了，你用的版本是？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vanessa219** [comment]
今天试了一天，就重现了一次。找不到规律。 😭

**Comment by Vanessa219** [comment]
加了个监听，麻烦在一起观察观察

**Comment by linglongyoudoufu** [comment]
> 今天试了一天，就重现了一次。找不到规律。 😭

会不会是iOS或iPados的内存机制引起的?我经常碰到这种情况....如果新增后台自刷新的能力会不会好一些?
