### ISSUE TITLE
特定情况下无法syncing，伴随出现内存占用超高的情况

### ISSUE THREAD

**Issue by blackplume233** [siyuan-note/siyuan#3637]
![NA~EXWAH(M (U8B@5FSOCWO](https://user-images.githubusercontent.com/32346887/146881947-77b13237-4dc7-4979-90e4-bee87c4141d0.png)
首先是遇到启动时同步卡主，一段时间后显示失败，该问题可能是由于我本地网络导致，目前正在排查，但是伴随出现的有内存占用量超高，持续20G左右，峰值40G，同时有大量的硬盘读写操作。
日志如
[siyuan.log](https://github.com/siyuan-note/siyuan/files/7750048/siyuan.log)
下

**Comment by 88250** [comment]
你好，麻烦发一下账号名，我们核对一下云端日志。

**Comment by blackplume233** [comment]
blackplume233

**Comment by 88250** [comment]
云端日志暂时没有发现相关问题。目前猜测可能是本地环境引起的问题，试下 `设置 - 编辑器 - 历史保留天数 清空所有历史`，然后重启思源（包括内核），重启以后再同步看看。

**Comment by blackplume233** [comment]
之前已经重启过，重启后可以正常使用。如果判断该问题不需要处理可以直接Close Issue，如果需要其他信息我可以配合提供

**Comment by 88250** [comment]
情况所有历史重启后麻烦同步一次，再发一下日志文件，谢谢。

**Comment by blackplume233** [comment]
[siyuan.log](https://github.com/siyuan-note/siyuan/files/7750845/siyuan.log)
以上是相关LOG，不客气，感谢你提供优秀的笔记软件

**Comment by 88250** [comment]
目前我们大概收到过和这个问题类似的 2-3 个反馈，暂时还定位不到产生原因，还得继续收集一下其他用户的反馈，感谢理解，我关闭了。
