### ISSUE TITLE
1.5.4 点击“+”新建文档，新文档的位置不定

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3638]
![image](https://user-images.githubusercontent.com/33319484/146891478-414bb30a-ce7f-42c6-8fd6-43d07d3aad3c.png)

文档树的排列顺序是自定义排序。新建文档的位置一般都会在当前文件夹下的顶部（置顶效果），现在的话则是固定在 “Google Material Design” 文档的下面，不知道是怎么变化的。已经确定排序方式依然是自定义排序，且都是同一台电脑，同一个思源版本。

![image](https://user-images.githubusercontent.com/33319484/146891625-1fc80f9e-bfc3-4e62-a311-277091fdc0bd.png)

当新建文件夹时，还可能会使现在已有的新文档所在文件夹里的文件顺序错乱，又得需要手动拖动排序。

这样的问题出现在子文档数量较多的情况下，子文档比较少的情况下，默认新建文档是出现在底部的。。。

系统版本是win10 21H2

**Comment by 88250** [comment]
和这个描述的是同一个问题吗？

https://github.com/siyuan-note/siyuan/issues/3511

**Comment by Achuan-2** [comment]
我也有这个问题，使用自定义排序，比如某个月最初几天的日记新建是在最下的，后面就跑到最上了。
Inbox笔记本新建则是会出现在中间

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/3511 中处理，应该是同一个问题。
