### ISSUE TITLE
记住文档树的展开情况

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3640]
每次打开思源都要展开一下文档树，希望能记住上一次关闭前的文档树
要是能记住文档上次阅读的位置就更好了(ง •̀_•́)ง

**Comment by 88250** [comment]
文档树状态和文档位置目前因为技术原因实现不了，抱歉了。以后如果能实现的话会考虑，感谢理解。

**Comment by code4wt** [comment]
这个确实比较难受，尤其是打开了很多文档情况下

**Comment by 88250** [comment]
@code4wt 手动点击一下文档树上的定位按钮，或者开启 <kbd>设置 - 文档树 - 始终定位打开的文档</kbd> 后试试。
