### ISSUE TITLE
1.5.5-beta1，macOS 12.0.1，鼠须管输入法在$x+y$后面无法输入内容，必须空一格打字后再把空格删除。内置输入法没问题。

### ISSUE THREAD

**Issue by grandband** [siyuan-note/siyuan#3651]
### 版本环境 Version environment

* Version: 1.5.5-beta1
* Operating system: macOS 12.0.1
* Browser (if used):

**Comment by 88250** [comment]
你好，你用的输入法是？

**Comment by grandband** [comment]
https://github.com/rime/home
rime 鼠须管 0.15.2
