### ISSUE TITLE
希望能增加类似于RoamEdit的词语的注释功能

### ISSUE THREAD

**Issue by AdventureBoy** [siyuan-note/siyuan#3654]
![image](https://user-images.githubusercontent.com/18328365/147219111-4d749088-a1eb-4110-84cb-1a77dc72a2dd.png)
![image](https://user-images.githubusercontent.com/18328365/147219129-8077c754-3569-4dc8-afb4-76767cb2fb97.png)
语法是加粗或有文字格式的文字后用{:注释内容}实现注释

**Comment by 88250** [comment]
行级批注暂时不考虑，如果以后要支持的话会重新打开 https://github.com/siyuan-note/siyuan/issues/174 感谢提议。
