### ISSUE TITLE
为浮窗四周添加大小拖拽功能

### ISSUE THREAD

**Issue by tobealive** [siyuan-note/siyuan#3659]
### 描述问题 Describe the problem
I'm experiencing a small problem with pinned windows. If it's not a quick fix, it's probably not that big of a priority.
For I don't know if this issue is to classify as a bug, a feature request, or a problem that is not possible to solve due to technical difficulties I'll just keep it at the description of what I experience and hope you can tell me more. 
Pinned windows can't be resized from the left side. It's also from the top side but top side not working is probably even less important. These are persistent through the themes used. Bellow I'll link to a 20-second video of the issue.
  

### 期待的结果 Expected result
Ability to resize the window from the left side / bottom left corner.

### 截屏或者录屏演示 Screenshot or screen recording presentation
YT (high res): https://youtu.be/pASc0Af46Wc
GIF: 
![ezgif-5-04db27eb0a](https://user-images.githubusercontent.com/34311583/147255206-6bbe8c0f-dde1-4407-bd5f-43ce424c9458.gif)

### 版本环境 Version environment

* Versions: 1.5.3, 1.5.4, 1.5.5beta 
* Operating system: Linux various
* Browser (if used):

**Comment by Vanessa219** [comment]
We did not implement this feature. I think dragging the top and then dragging to the right can also achieve the effect of dragging to the left.

**Comment by tobealive** [comment]
Thanks for your quick reply. Yes, that's certainly a way to get to it and the one I'm using currently. 
Having this one noted down for a while now as a potential small improvement, I felt free to share it and get it off the list. I'll still be happily using your software when it stays in your described way 😊👍.
