### ISSUE TITLE
Markdown 粘贴列表分割处理问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3661]
https://ld246.com/article/1640268449654

**Comment by 88250** [comment]
markdown这样的 Markdown 文本解析以后实际上只有一个列表（松散列表），思源里面不存在松散列表，所以复制以后会转换为：

```markdown
* foo
* bar

**Comment by Clouder0** [comment]
![image](https://user-images.githubusercontent.com/41664195/149605055-9d8b66bd-3b22-4dc2-b317-7755b825e7e7.png)

在思源中两个独立的列表，复制后会变成 markdown 中的一个 loose list，并且在导入时损失原有的格式。

```markdown
* List1
* List1
* List1

* List2
* List2
* List2

  * sub
```

![image](https://user-images.githubusercontent.com/41664195/149605097-4fad2751-1476-41a7-96a3-eff073d4b43a.png)

用思源中的空段落分割的列表也会丢失，因为空段落无法导出为 markdown.

![image](https://user-images.githubusercontent.com/41664195/149605876-0b0b0fe2-fb8e-4786-a06f-51f9db7f9099.png)

这样一来，从思源导出的连续列表损失了原有的格式，而且也不能往回导入。（复制粘贴）  
同样的，在思源的预览模式中，这些格式都会丢失。

在 CommonMark Spec 中，分割连续列表的[一个例子](https://spec.commonmark.org/0.30/#example-308)使用了 html 注释，但在思源中应该是无效的。

理想的情况是，思源的导出 markdown 文本能保留分隔的连续列表格式，导入时还能识别这种格式生成两个独立列表。

**Comment by 88250** [comment]
@Clouder0 嗯，这个暂时没法搞，只能这样了。
