### ISSUE TITLE
预览模式块背景色消失

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#3663]
编辑模式
![image](https://user-images.githubusercontent.com/60436214/147310234-6f215e9d-5e53-4565-99b8-808962b049f0.png)
预览模式
![image](https://user-images.githubusercontent.com/60436214/147310248-d478836e-ed04-4b83-82ee-4fb1c0e139ac.png)

### 版本环境 Version environment

* Version: 1.5.5 beta2
* Operating system:  Win10
* Browser (if used):

**Comment by 88250** [comment]
导出预览模式使用的是标准 Markdown 渲染的，所以没有 Protyle Block 特性。

这个估计不会变了，后面考虑的改进方向是导出 PDF/HTML 时使用 Protyle Block DOM。
