### ISSUE TITLE
浮窗支持拖出思源界面

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#3664]
当块引预览、数学公式编辑时，有时候希望把浮窗往下拖动，目前的情况是浮窗必须在思源界面内，不能超出。这样就会造成可拖动的范围比较小，想把浮窗往偏下面拖动就必须把浮窗缩小。
还有一点，如果能支持拖出界面，这样当预览块引时位置偏下时，浮窗页面也能调整的稍微大些，而不是根据只出现剩余高度的大小
![image](https://user-images.githubusercontent.com/60436214/147312282-72b2ca4e-f5a4-485d-ba0e-31593011f3f1.png)

**Comment by 88250** [comment]
目前由于技术限制实现不了。后期会先考虑页签转换浮动窗口 https://github.com/siyuan-note/siyuan/issues/2955

**Comment by Achuan-2** [comment]
也不能实现浮窗超出页面的部分隐藏吗

**Comment by Vanessa219** [comment]
超出思源部分已经是另外一个应用了。所以要参见 #2955
