### ISSUE TITLE
反向链接tab鼠标悬停支持预览

### ISSUE THREAD

**Issue by AdventureBoy** [siyuan-note/siyuan#3665]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
引用很长时查看不方便

![image](https://user-images.githubusercontent.com/18328365/147320817-5f5a147c-0a76-4dd7-8b4f-17c514ad6e8c.png)

### 描述可能的最优解决方案 Describe the optimal solution
鼠标悬停能有悬浮框展示完整引用

**Comment by kungjulianis** [comment]
把鼠标悬停在段落图标上，不就可以显示完整的引用内容（整个块）了吗？

**Comment by AdventureBoy** [comment]
sorry才看到，确实可以😁
