### ISSUE TITLE
表格内存在换行的文本，复制后粘贴到Windows记事本带<br\>

### ISSUE THREAD

**Issue by tianzry** [siyuan-note/siyuan#3677]
### 描述问题 Describe the problem
表格内存在换行的文本，复制后粘贴到记事本带<br\>，需手动删除多余的换行控制字符

![image](https://user-images.githubusercontent.com/19747979/147425700-ca15b3dc-3e14-4f35-a06c-a866f1583fdc.png)
如下图，复制第二列带换行的文本，粘贴到Windows记事本（以及其他plain text编辑器）或者微信、qq聊天输入框，预期应该是：
line2with#$
line2 newline
但是实际上是`line2with#$ <br/>line2 newline`

### 期待的结果 Expected result
表格带换行的文本复制后粘贴，预期应该是：
line2with#$
line2 newline
但是实际上是`line2with#$ <br/>line2 newline`

### 版本环境 Version environment

* Version: 1.5.5（12.26发布版本）
* Operating system: Windows 10 2004
* Browser (if used): 软件内使用，未使用浏览器

**Comment by Vanessa219** [comment]
抱歉，这个无法进行改进，粘贴到记事本中是用的 md 语法，在 md 中 table 的换行只能用 <br>。
