### ISSUE TITLE
Multicolor - Style Bug

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#3678]
First of all, thank you so much for sharing this amazing program.

I found a bug that has annoyed me in some situations. I can't film my screen so I'll describe how to find the bug.

1 - Select a word;
2 - Click on the button to select the style.
3 - We apply the “multicolor” style.
4 - Now you can't see the mouse cursor on the word.

In some situations this interferes too much. I went to test and only in this style that has this bug.

Finally, I already asked for this once and I come here to reinforce my request. Please put a button to expand and collapse information in outline mode. Clicking "alt + x" all the time is really bad. If you had a button at the beginning of the paragraph, it would be excellent.

**Comment by 88250** [comment]
1. The multicolor style can't display cursor (caret) may be a defect on browser, maybe we will find a workaround in the future
2. List fold/unfold feature is still on https://github.com/siyuan-note/siyuan/issues/3125 

Thanks.
