### ISSUE TITLE
托盘菜单添加显示主界面

### ISSUE THREAD

**Issue by sukanka** [siyuan-note/siyuan#3687]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
据反馈（见 [AUR评论](https://aur.archlinux.org/packages/siyuan-note-bin/))，在 mate 桌面、kde 中都无系统托盘图标，希望官方能够支持。

### 描述可能的最优解决方案 Describe the optimal solution
已有第三方解决方案，参考 [思源笔记 Linux 使用优化](https://ld246.com/article/1634908196973),
目前我采用了前两个 patch, 添加了托盘，配置了 url scheme

**Comment by 88250** [comment]
感谢反馈，下个版本会在 Windows 和 Linux 桌面端都添加一个菜单项：

![image](https://user-images.githubusercontent.com/873584/147661091-7984b447-4bcc-4ecf-b21e-665ed9678fe9.png)
