### ISSUE TITLE
[iPadOS] Latex行内公式在list中不生效

### ISSUE THREAD

**Issue by Creling** [siyuan-note/siyuan#3697]
在Siyuan for Windows中，使用`$...$`可以在list中插入行内公式，效果如下：
![image](https://user-images.githubusercontent.com/43109504/147659954-93eab42a-9f83-48bf-bcac-9855c440fd81.png)

在Siyuan for iOS中进行相同的操作，会生成块级公式而不是行内公式，效果如下：
![e5a2442bb474e90238a8724c1d5276a](https://user-images.githubusercontent.com/43109504/147660126-686d4769-8306-4842-a39a-ca14621b669b.jpg)

操作系统：iPadOS 15.1

**Comment by 88250** [comment]
你好，这个问题在最新版上还能重现吗？

**Comment by 88250** [comment]
我们先关闭了，后面做平板优化的时候留意，感谢反馈。
