### ISSUE TITLE
导出功能 不会在指定的文件夹生成导出文件

### ISSUE THREAD

**Issue by Allenxuxu** [siyuan-note/siyuan#3704]
### 描述问题 Describe the problem

导出功能不会在指定的文件夹生成导出文件，只会在 siyuan 的 temp/export 目录生成

### 版本环境 Version environment

* Version: 1.5.6
* Operating system: mac
* Browser (if used):

**Comment by 88250** [comment]
设计上是这样的，用户指定的路径是用于下载导出的包的。

**Comment by Allenxuxu** [comment]
> 设计上是这样的，用户指定的路径是用于下载导出的包的。

没有太明白这里的意思，指定目录下载导出的包呢

**Comment by 88250** [comment]
导出的时候选择的路径是下载路径，正常情况下应该是打开浏览器下载，如果没有打开浏览器的话可能是因为系统默认浏览器设置影响的。
