### ISSUE TITLE
快捷键新建文档时 支持选择笔记本

### ISSUE THREAD

**Issue by Allenxuxu** [siyuan-note/siyuan#3706]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

使用快捷键新建文档时，总是新建在第一个笔记本下面，需要再人工挪动一次，可以在新建文档时支持选择笔记本（不通过鼠标操作，提高效率）

**Comment by 88250** [comment]
如果要选择笔记本的话快捷键的作用就大打折扣了，即使通过键盘选择笔记本也要至少多两次键盘操作（上下选择+确认）。

**Comment by Allenxuxu** [comment]
> 如果要选择笔记本的话快捷键的作用就大打折扣了，即使通过键盘选择笔记本也要至少多两次键盘操作（上下选择+确认）。

但是如果每次都是默认第一个，那我就要通过鼠标，去拖了。
感觉可以提供一个配置项？ 如果不配置，就每次要求选择，配置了就默认创建在指定笔记本

**Comment by 88250** [comment]
这个配置还需要再考虑下，也许还有其他解决方案。

**Comment by 88250** [comment]
我先关闭了，后面如果有更好的方案再补充，也欢迎继续讨论。
