### ISSUE TITLE
想要插入图片链接时很难点击到插入链接的按钮

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#3707]
![动画](https://user-images.githubusercontent.com/56879067/147750839-1dcd77b8-8e73-418c-8b1e-b82f9de252fa.gif)

**Comment by 88250** [comment]
应该是因为前置的 bug 导致 https://github.com/siyuan-note/siyuan/issues/3710 我先关闭了，等那个 bug 修复以后再试试，如果还有问题请继续跟帖，谢谢。
