### ISSUE TITLE
Mac os Magnet半屏拖拽

### ISSUE THREAD

**Issue by mtianyan** [siyuan-note/siyuan#371]
其他软件在Magnet 下都可以拖到屏幕右边，自动半屏。思源拖拽无反应

![image](https://user-images.githubusercontent.com/15145231/97715094-ede1a180-1afc-11eb-853e-00fa9cdf4995.png)

**Comment by 88250** [comment]
感谢反馈，暂时不做深入了，v0.4.0 支持在浏览器上使用，可以试试浏览器用法，谢谢反馈。
