### ISSUE TITLE
API 细节改进

### ISSUE THREAD

**Issue by Crowds21** [siyuan-note/siyuan#3712]
API文档里面有好几处的 `path` 含义冲突.
`/api/filetree/removeDoc` 里面的path是  `"path": "/20210902210113-0avi12f.sy"`
`/api/filetree/createDocWithMd` 里面的  path是 `"path": "/foo/bar"`

和模板一样,用`hpath` ,`path`区分会不会稍微好一些.

**Comment by 88250** [comment]
这个不改了，按照文档示例来吧。

**Comment by Crowds21** [comment]
> 这个不改了，按照文档示例来吧。

好的D大,还有, SQL查询好像是打错了?`/api//query/sql`

**Comment by 88250** [comment]
感谢指正，已经修复。
