### ISSUE TITLE
希望把思源的菜单整一下

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3717]
菜单我都替你想好了，不会说不整吧(ㅍ_ㅍ)
![图片](https://user-images.githubusercontent.com/68107073/147843285-d59eda34-fde2-4625-a293-80db1c557cd5.png)

**Comment by roverway** [comment]
看起来确实整齐美观很多。
其中编辑菜单可能使用率要低于目前的块图标点击显示，因为移动到上边框没那么方便，其他几个里面，前进后退、放大缩小，似乎现在这种单独放个图标更方便，因为这几个操作很可能是会连续点击的（比如逐渐放大等）。
剩下的菜单项目这么整理感觉都不错。

**Comment by choyy** [comment]
确实，不过编辑菜单也没有找到什么好加的
前进后退是本来就有图标的，放大缩小这种我觉得应该不会经常用，所以就不在乎连不连续点击啦

**Comment by 88250** [comment]
你好，我没看明白你指的菜单是哪里的菜单……

**Comment by choyy** [comment]
@88250 就是顶栏的菜单，linux和mac应该都有吧
![图片](https://user-images.githubusercontent.com/68107073/147865247-7e20f6a1-28d9-4534-897d-54dd50714d43.png)

**Comment by allblue** [comment]
这个好像是mac默认的吧，windows/linux版没有这块
![image](https://user-images.githubusercontent.com/844763/147880682-80913c63-31be-4f70-b3f1-b7c514a003af.png)

**Comment by choyy** [comment]
> 这个好像是mac默认的吧，windows/linux版没有这个，直接就是那排图标 ![image](https://user-images.githubusercontent.com/844763/147880682-80913c63-31be-4f70-b3f1-b7c514a003af.png)

KDE和GNOME都是有全局菜单的，其他桌面的话应该也有不少是有的

**Comment by allblue** [comment]
> > 这个好像是mac默认的吧，windows/linux版没有这个，直接就是那排图标 ![image](https://user-images.githubusercontent.com/844763/147880682-80913c63-31be-4f70-b3f1-b7c514a003af.png)
> 
> KDE和GNOME都是有全局菜单的，其他桌面的话应该也有不少是有的

gnome mate都没有，kde不确定

**Comment by 88250** [comment]
系统的原生菜单我们暂时不考虑了，感谢提议和讨论。

**Comment by choyy** [comment]
@88250 不是系统原生菜单，是在现在的菜单中加些常用的功能

**Comment by 88250** [comment]
顶栏的菜单不同操作系统上面表现不同哦。

**Comment by choyy** [comment]
那...还是有空再说吧
