### ISSUE TITLE
云端收集箱

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3718]
云端收集箱是一个纯云端功能，数据从云端获取，使用分页列表展示，类似邮箱的收件箱（Inbox），其中的数据只能查看、删除和发送到笔记本。

以微信举例使用流程：微信公众号输入、打开思源云端 Inbox，浏览需要的信息并发送到笔记本进行整理，删除信息。

_Originally posted by @88250 in https://github.com/siyuan-note/siyuan/issues/3457#issuecomment-1003500774_

---

### 服务端

* [x] 微信接入
* [x] 网页爬虫
* [x] DOM 转换 Markdown
* [x] 数据入库
* [x] 数据查询、删除 API
* [x] 数据插入云端公开 API

### 客户端

* [x] 界面渲染和交互
* [x] 查询、删除 API 接入
* [x] 移动到笔记本

**Comment by hanson-reas** [comment]
D大 借个楼 好像链滴社区崩了，云同步功能 思源笔记也用不了了

**Comment by 88250** [comment]
> D大 借个楼 好像链滴社区崩了，云同步功能 思源笔记也用不了了

https://ld246.com/article/1641121217690

**Comment by fantasyzyc** [comment]
支持！如果能有云端功能就不考虑用cubox了！

**Comment by woniuxia** [comment]
这个功能就离谱，有了这个功能又能少用一个应用了。

**Comment by JokeenZhang** [comment]
如果能做到直接包括微信在内，其他app，如知乎、掘金等社区也能分享到思源就更好了。android的话应该就是Intent。

**Comment by woniuxia** [comment]
哇哇哇，D大要开动了呀。十分期待~
感觉爬虫和 ODM 转 markdown 可以放在二期吧。
一期可以支持简单的链接和文本的收藏。

**Comment by Zuoqiu-Yingyi** [comment]
等不及的朋友可以瞅瞅 [Zuoqiu-Yingyi/zhenxun-bot-plugin-siyuan: 绪山真寻 bot 的思源笔记收集箱插件](https://github.com/Zuoqiu-Yingyi/zhenxun-bot-plugin-siyuan), 可以将 QQ 群设置为收集箱, 就是从零开始配置比较麻烦

**Comment by hiforrest** [comment]
无论是转瞬即逝的灵感还是开会时做记录，最重要是打开速度要快。目前安卓 APP 打开速度很慢，现在只能寄希望于「云端收集箱」补上这个短板。

我注意到，「云端收集箱」要先打开公众号才能使用。记一条新内容，要先打开微信，然后找到公众号，接着，打开输入内容界面才能开始真正的输入。这一番操作下来，效率和使用 APP 相比没有明显的优势。

我想，微信中通过发送一条消息到对话框是较为快捷的方式，希望能考虑🙋

**Comment by 88250** [comment]
@hiforrest 不太明白“发送一条消息到对话框”是指的什么，麻烦再补充一下，谢谢。

**Comment by Zuoqiu-Yingyi** [comment]
> @hiforrest 不太明白“发送一条消息到对话框”是指的什么，麻烦再补充一下，谢谢。

应该是指可以分享/转发消息至公众号, 可能包括微信内消息的转发与微信外消息的分享

**Comment by hiforrest** [comment]
> @hiforrest 不太明白“发送一条消息到对话框”是指的什么，麻烦再补充一下，谢谢。

像 Flomo 的微信输入那样，在微信中创建一个机器人好友，叫做「Flomo」；给它发消息，内容就会保存到笔记本。微信是常驻APP，打开很快，只要把这个好友置顶就可以方便的发送内容到笔记本了 🚀

参考：https://baijiahao.baidu.com/s?id=1686971704175852903

**Comment by deerainw** [comment]
所有微信公众号都不能接受转发消息，思源手机 app 好像也不能接受来自其它 app 的分享消息，所以在手机快速记录这一部分，目前最快的方式可能就是在微信里找到公众号然后发送消息了。

我觉得真正比较难设计的是后期整理时「发送到笔记本」这一步。

- 云端快速收集箱的每一条内容应该是只有正文没有标题，而且从字数上说也会比较短，所以一条笔记发送到笔记本时如果直接生成一个新文档就不太适合，汇总整理起来也不方便
- 如果一条笔记发送到笔记本的时候是发送到某个文档里生成一个块，对于大量零散内容肯定会比第一种方式更好整理一些，但是因为每条云端笔记的归属不同，对每条笔记都要手动选择具体发送到哪个文档又是一件很麻烦的事
- 目前我感觉点击某条云端笔记时直接默认发送到当天的 daily note 文件末尾比较好，这样既免去了发送目标的选择，又可以利用编辑器本身的编辑能力进行整理，配合锚文本就可以直接传递到各个主题文档的反链里

就上面几种方式来说，偏好每一种方式的人使用习惯可能有极大的差异，比如偏好第一种方式的人可能是想在手机端粘贴点长篇文章发到公众号而不是手动记录自己的灵感，偏好第二种方式的人可能是只想找个 flomo 替代品，偏好第三种方式的人是非主流。不管选择哪种策略，如果没有官方亲自下场背书，可能社区里又会多一大批关于云端收集箱的 issue 

![image](https://user-images.githubusercontent.com/32661922/158073155-095d82bf-580a-4c43-9ffb-9e5203a3f3ff.png)

**Comment by 88250** [comment]
@deerainw 

> > @hiforrest 不太明白“发送一条消息到对话框”是指的什么，麻烦再补充一下，谢谢。
> 
> 像 Flomo 的微信输入那样，在微信中创建一个机器人好友，叫做「Flomo」；给它发消息，内容就会保存到笔记本。微信是常驻APP，打开很快，只要把这个好友置顶就可以方便的发送内容到笔记本了 🚀
> 
> 参考：https://baijiahao.baidu.com/s?id=1686971704175852903

微信好像没有提供 bot 相关 API，这样做似乎不太稳妥……

**Comment by 88250** [comment]
@deerainw 感谢梳理，我们再想想。

**Comment by hiforrest** [comment]
我刚接触思源笔记，初步试用，桌面端很优秀，但移动端的「速记」功能是思源笔记所缺失的。看到前面的回复，有些失望。下面我想完整阐述一下我想法，可能对于这个主题来说有些跑题，但这是我在「路线图」中看到的，最接近能解决问题的工作计划了，就写在这里吧。希望对思源笔记有一点帮助。

笔记软件的移动端和桌面端的使用逻辑不一样，不是把桌面端复制到移动端就解决问题了。手机端侧重于「记」和「看」，能够快速记录，方便地浏览已有内容即可。内容管理，复杂的操作可以放到桌面端来完成。

一款好的手机端笔记APP，首要标准永远是「快」。想法稍纵即逝，产生灵感的瞬间必须马上记下；开会时出现重要信息，必须马上记录。从产生想法到开始记录，时间越短越好，步骤越少越好。能用 0.1 秒不用 0.5 秒，能用一步，不用两步。

而思源笔记手机 APP 的现状是，且不说打开速度慢，进入 APP 之后，还要点一下「编辑」按钮才能开始输入文字；甚至进入 Daily Note 还需先点开侧栏菜单，选择「日记」，如此之繁琐！这一番操作下来，我真的会忘记一开始要记什么。由此细节可见，开发者尚未重视到手机端「速记」的重要性。

下面是几个笔记类 APP 的解决方案：

- 印象笔记现在被很多用户所诟病，口碑在一路下滑。但是，它身上依然有一些值得学习的优点。印象笔记采用的是长按启动图标，选择「速记」，瞬间就会弹出输入框，让用户可以立即开始输入。

- 老罗的锤子手机被很多人骂，很大成都上是硬件拖了后腿。实际上它的软件非常优秀。其中，「闪念胶囊」就体现了老罗对「快」的重视，甚至为它做了一个专属的物理按键。突发灵感，按住开始说话即可。这个交互体验令人拍案叫绝。

- Flomo 是一款简陋的工具，它抓住了用户随时记录这个需求，提供了一系列的内容输入渠道。其中就有从微信的「Flomo 机器人」输入文字。其实 Flomo APP 的打开速度还算过得去，但它依然在不遗余力的提供各种输入内容的渠道，因为他知道，让用户方便、快速的输入的重要性。这也许是它取得市场上成功的因素之一吧。

如果「云端收集箱」依靠公众号来做，明显「快不起来」：首先公众号本身入口就深（公众号还难找），从公众号进入功能页面还有一层，太复杂了，且不说里面做的功能多强大，酒香就怕巷子深！我为何不长按印象笔记，直接开始记录？

建议重新评估一下「云端收集箱」的制作方案。所有的特性当中：「快」首当其冲，不然的话，为什么要做「云端收集箱」，直接用 APP 不就行了。

**Comment by 88250** [comment]
@hiforrest 非常有用的建议，我们目前的打算是先上线云端收集箱，这个基础版本先采用公众号打通，提供云端 API 之后在继续考虑速记的接入方式。也许可以通过你说的长按图标触发输入框来接入，也许也还有其他方案，这个等云端收集箱上线以后再陆续完善，感谢帮助。

**Comment by hiforrest** [comment]
@88250 嗯，路要一步一步走，有解决的计划我就不担心了 🥳

**Comment by woniuxia** [comment]
微信提供了消息推送服务端处理接口，D大，后面可以看下。
https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html#%E5%BC%80%E5%8F%91%E8%80%85%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8E%A5%E6%94%B6%E6%B6%88%E6%81%AF%E6%8E%A8%E9%80%81

**Comment by s544838371** [comment]
> 支持！ 如果能有云端功能就不考虑用cubox了！

能替代Cubox吗

**Comment by taozina** [comment]
@88250  对不起。 我不知道这是否是正确的提问方式。 但是思源2.0版本会有很大的变化还是只是另一个正常的更新（就像从1.9.1到1.9.9的那些）？

**Comment by 88250** [comment]
@taozina 正常更新，会引入一些特性，但总体上不会有太大变化，具体计划变更可参考 https://github.com/siyuan-note/siyuan/milestone/177

**Comment by JCJC01** [comment]
你好，印象笔记可以通过把微信文章，或者聊天记录以及图片转发给公众号（公众号绑定了自己印象账号），公众号收到后就会自动转发存储到印象笔记中，希望思源也能实现，感谢
滴答清单也有类似功能，在微信的公众号里面发送todo list 内容（时间地点事件内容），然后自动后台在滴答清单服务器生成 to do list

**Comment by 88250** [comment]
@JCJC01 这个 issue 就是提供类似的功能。

**Comment by woniuxia** [comment]
撒花~
静待四月十六号~

**Comment by 88250** [comment]
明天会发布 v2.0.0 的第一个内测版。

**Comment by JCJC01** [comment]
能测麻烦算我一个哈，谢谢D大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 云端收集箱 (Issue #3718)




 
@JCJC01 这个 issue 就是提供类似的功能。

**Comment by JCJC01** [comment]
内测麻烦也发我一个哈，谢谢

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 云端收集箱 (Issue #3718)




 
@JCJC01 这个 issue 就是提供类似的功能。

**Comment by 88250** [comment]
@JCJC01 已经邀请。

**Comment by fanglypro** [comment]
现在只能移动到笔记本级生成一个文档吗，能否移动到单个文档内部呢？

**Comment by mozhux** [comment]
收集箱的思源端展示要再优化一下，现在点击后也是在当前页面打开，不是在右边的打的打开，这样不方便浏览。

**Comment by mozhux** [comment]
对于图片等消息，由于安全限制，在思源上不会直接显示图片，只是一个链接，只能转成文档再下载本地才行，看能不能优化一下直接显示或者有个直接转本地的呢。
![image](https://user-images.githubusercontent.com/46953371/163123163-10c1350c-c5db-482b-9217-7b8c3b478a0d.png)

**Comment by JCJC01** [comment]
1.请问手机版本暂时没有收集箱吗？
2.不能向公众号发信息保存，让微信保存功能的意义大减，因为能打开微信保存，效率不比直接打开思源保存高。可惜了微信不支持。本来可以通过先把聊天记录和图片保存在收藏，然后在公众号里通过添加收藏发出保存的，但有个问题，这样不能激发收集箱处理中，请稍后查看的状态，是没有这个设定吗？

**Comment by fanglypro** [comment]
个人感觉现在的云端收集箱有点问题，不是收集箱，而是一个剪藏中转站

对于非链接剪藏类的其他信息，甚至不如发消息到文件传输助手，然后在电脑上打开文件传输助手一个一个复制到笔记里，用文件传输助手比云端收集箱效率更高

**Comment by 88250** [comment]
@fanglypro 微信只是一个对接方式，后面会提供 API，这个应该是云端收集箱的最大意义。

**Comment by JCJC01** [comment]
你好，目前微信里面公众号云收集箱的功能只支持文字和图片吗？
聊天记录，还有微信收藏的内容发给公众号无法激活收集的功能，即没有提示云端收集箱处理中
希望可以支持微信收藏中添加的聊天记录
操作是把聊天记录多选后收藏，然后来到公众号，通过收藏添加聊天记录发送到公众号保存
![IMG_20220414_090153](https://user-images.githubusercontent.com/103412730/163293669-d50eadac-5a88-4f65-917f-1c03461e4fca.jpg)

**Comment by 88250** [comment]
我试了一下，好像无法支持，微信不会发送此类消息到我们的服务端。

**Comment by JCJC01** [comment]
> 我试了一下，好像无法支持，微信不会发送此类消息到我们的服务端。

意思是如果我们从公众号添加收藏里面的内容发到公众号，微信自动屏蔽了，无法发送到服务端，导致无法激活云端收集箱的收集功能，对吗？

**Comment by 88250** [comment]
应该是的，至少目前我没有找到聊天记录转发公众号后会服务端能够收到消息的技术方式。

**Comment by JCJC01** [comment]
你好，刚试了一下，你看是否是折衷的思路
在和朋友聊天的界面，多选聊天记录，安卓微信右下角有个邮箱标记，选了后出现手机安装了的软件（与微信有连接端口的），直接发送过去。我测试了滴答和飞书都是可以直接把聊天记录转过去的。虽然不是云端服务，但也能实现微信入口转发保存到思源的目的
![IMG_20220414_113227](https://user-images.githubusercontent.com/103412730/163309281-981ba2c2-c0b4-4ef4-b8e7-dc903aac82d7.jpg)
![IMG_20220414_113217](https://user-images.githubusercontent.com/103412730/163309297-6638ecf9-3a4a-4c50-8f6d-322bfb812e7e.jpg)
![IMG_20220414_113314](https://user-images.githubusercontent.com/103412730/163309312-91350545-e149-407e-9e2a-6a6aace17967.jpg)

**Comment by 88250** [comment]
这个不是云端收集箱的功能，后面再单独考虑，感谢提议。

**Comment by mozhux** [comment]
> 我试了一下，好像无法支持，微信不会发送此类消息到我们的服务端。

所以一些APP已经开始用企业微信做一个转发了，可以尝试一下的

> 

公众号是不行了，所以都用了企业微信。比如滴答这种
![微信图片_20220414114654](https://user-images.githubusercontent.com/46953371/163309975-1bb37a9d-a88f-4c31-9db2-2784015dad44.png)

**Comment by 88250** [comment]
@mozhux 后面考虑，感谢提议。

**Comment by winter60** [comment]
D大，建议收集箱具备像反链面板那样拖动到正文的操作，这样便于整理~
另外开放云端api是指不用在终端安装思源就能发送到收集箱了吗？如果是的话就太牛逼啦

**Comment by 88250** [comment]
@winter60 整理功能靠发送到笔记本后进行；云端 API 就是对接云端接口，和本地思源没有关系，可以走 API 数据先入库，然后思源打开联网就能看到。

**Comment by winter60** [comment]
> 

了解啦，谢谢~

**Comment by JCJC01** [comment]
请问云收集箱目前出现在侧栏中，不能直接复制文本，需要移动到文档中才能复制。能否改成直接在侧栏中就可以直接复制，这样可以省区一个步骤，后面大量使用的时候方便很多

**Comment by woniuxia** [comment]
D 大，这个功能有可能脱离于思源吗？
直接在链滴论坛上面加个 tab “云端收集箱”。
有时候收集些信息，只是做临时的存储，在网上就能处理完，不想再打开思源客户端去操作。

**Comment by 88250** [comment]
@woniuxia 麻烦例举一个具体的使用场景和步骤我们分析看看是否有必要。

**Comment by Zuoqiu-Yingyi** [comment]
> > @woniuxia 麻烦例举一个具体的使用场景和步骤我们分析看看是否有必要。
> 
> 比如说，朋友分享了个b站/网站/文章，当前没时间看，存到收集箱中，等有时间再看。 不过这些内容可能知识含量不高，不用做笔记，那么打开思源客户端就有些重了，直接网页上有个地方查看就可以了。 可能有些脱离了知识收集和整理的范围，D大可以再考虑下。

收集箱不仅是爬取发送的超链接呀, 手动发送 markdown 文本也可以, 用于一些灵感出现是快速打开记录

**Comment by 88250** [comment]
@woniuxia 这个例子中随便用一个其他工具（比如 QQ/微信）可能更快。

**Comment by woniuxia** [comment]
@88250 当前就是通过微信来实现的。
不过思源有了云端收集箱功能，希望使用场景更多一些，替换掉当前世面上大部分稍后读工具。

**Comment by JCJC01** [comment]
你好，使用云收集箱一段时间，有一些反馈想分享，可能各人对收集箱的定位或者自己使用场景不同，有不同感想。
目前不太便捷，1.图片需要移动到笔记，然后再下载才能使用，如果传了几张相片，快速找回来，可能就要逐个重复上述操作才能找到目标相片才能使用
2.不支持语音，有时候灵感想法或者，连打字都觉得时间不够，想记录一些想法，语音是最快捷的方法。
3.不支持文件收集
4.不支持聊天记录的，直接转发
5.需要进入公众账号才能转发。理论上跟上面一条是一样的，但是特意把聊天记录单独提出来，是因为有时候跟业务有关的聊天记录比较重要，所以单独拿得出来。
6.不知道是否是公众账号的设置问题，每次都要点一下键盘才能输入，如果不点的话是各种服务选项。
目前使用了几款软件，觉得最优方案是葫芦笔记的机器人，可以转发很多格式的文件图片聊天记录，甚至可以把机器人拉进群聊的群，方便记录重要的聊天信息。
虽然以上说的几点都有可折衷代替方案，但是代替方案往往意味着要多几个步骤，或者借助其他软件，对于灵感记录，快速记录都有阻碍。
目前这种方案可能更偏重于稍后阅读。
每个人都有自己的使用方法，纯粹想表达一下自己的反馈，不喜勿杠。爱思源，每天都离不开思源

**Comment by JCJC01** [comment]
云收集箱作为2.0重大功能更新，希望越来越完善，如果因为成本或者其他开发原因，是否可以出个对接目前主流信息收集类软件api的教程，曲线救国先，谢谢。更好的使用值得消费者付费更多，可以针对这些成本更大的功能增加附加费用。notion还有wolai等都有增值付费的功能。

**Comment by JCJC01** [comment]
云收集箱作为2.0重大功能更新，希望越来越完善，如果因为成本或者其他开发原因，是否可以出个对接目前主流信息收集类软件api的教程，曲线救国先，谢谢。更好的使用值得消费者付费更多，可以针对这些成本更大的功能增加附加费用。notion还有wolai等都有增值付费的功能

**Comment by 88250** [comment]
@JCJC01 API 请参考帮助文档收集箱章节。

**Comment by JCJC01** [comment]
你好，知道post和body，咋用？虽然很爱数码，无奈编程小白一个，大大，有没有操作的教程

**Comment by JCJC01** [comment]
【【Notion × 滴答清单】自动同步To-do清单！别再让安排任务也成为你的任务之一-哔哩哔哩】 https://b23.tv/8QKLBos，类似这种教程
