### ISSUE TITLE
插入链接时的一个小问题

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3719]
当复制一个链接把它插入到思源中，操作是这样的：
快捷键ctrl+K插入链接（链接会自动插入）--->输入提示文本--->回车完成插入

完成插入之后有一个问题，就是它会自动选中提示文本，这样如果要继续输入文字就会修改提示文本了，希望能改进
![Peek 2022-01-01 14-53](https://user-images.githubusercontent.com/68107073/147845677-bfb94446-23c8-4c37-a989-f55d6346a745.gif)

**Comment by choyy** [comment]
双链的面板也是这样，是否也有必要改一下？

**Comment by Vanessa219** [comment]
光标放在最后是否会好一点？

**Comment by choyy** [comment]
> 光标放在最后是否会好一点？

我觉得光标放最后再输入不会再修改提示文本就可以了
