### ISSUE TITLE
在浏览器不能添加iframe 不显示网址输入框

### ISSUE THREAD

**Issue by Rioad233** [siyuan-note/siyuan#3726]
### 描述问题 Describe the problem
在浏览器不能通过/菜单添加iframe，没有弹出输入网址的输入框，在客户端是可以的。
![image](https://user-images.githubusercontent.com/52393675/147853882-bba14a50-7aa8-498f-9eaa-20a5b706729a.png)

**Comment by 88250** [comment]
是由于 https://github.com/siyuan-note/siyuan/issues/3722 引起的 bug，下个版本修复，感谢反馈。
