### ISSUE TITLE
在设置>类型过滤中添加锚文本选项

### ISSUE THREAD

**Issue by kungjulianis** [siyuan-note/siyuan#3728]
作为思源笔记的忠实粉丝，我一直在努力摸索一种更有效并且展示结果更可控的笔记体系。思源笔记通过Sql来实现块嵌入无疑是一种特色，因为这样不但可以利用语法实现更多惊喜的内容够，也在块嵌入的时候，我可以区分哪些是纯引用性的，对于帮助理解被引段落没有帮助，不需要进入反链面板、虚拟引用及搜索结果的，那么我便采用块嵌入。而另一些是诠释性的引用，这些段落被引用之后，上下文中会对该段落做出一定程度上的解释而有助于我理解，那么让这些进入反链面板、虚拟引用及搜索结果才更有价值。

而区别于块级引用，在行级引用中都是采用块引这一种形式，那么便无法使其对应的采用同一种笔记方式。虽然在1.6.0的版本中，已经可以通过设置>搜索中的选项，使其因为锚文本被排除在反链面板及虚拟引用之外（因为我的笔记中原文有段落缩进，而在行级引用中会取消，或者只是引用一段话中的部分句子，所以几乎自带锚文本）。但缺少了被排除在搜索结果之外的方法。

因此如果**在设置>类型过滤中也添加锚文本这一选项**，那么在行级引用中，是否呈现在搜索结果中也变得可控，可以通过简单的设置来实现。因为在同一个笔记体系中，块级引用（块嵌入）被排除在搜索结果中，而行级引用却在，尤其是行级引用数量上都远远大于块级引用，这无疑会对搜索结果的呈现形成重复性的干扰。如何在笔记体系中兼容块级引用与行级引用不同的特性而建立一套自己的方法，或者干脆完全不使用块嵌入吗？这会变成一个复杂的问题。

**Comment by 88250** [comment]
设置 - 搜索 - 类型过滤 针对的是块类型，而锚文本是行级引用元素，所以没有办法通过类型过滤排除的。

**Comment by 88250** [comment]
我关闭了，如果需要继续讨论的话请随时跟帖。
