### ISSUE TITLE
【体验优化】空行``delete``时会删除后面行的Markdown标记

### ISSUE THREAD

**Issue by orangee-wi** [siyuan-note/siyuan#373]
## 现状
当在空行按键``delete``（删除后面内容）时，会删除掉后面行的Markdown标记
## 希望优化
空行``delete``时**不会**删除后面行的Markdown标记，**仅删除空行**
## Demo
![siyuan-note_issue5](https://user-images.githubusercontent.com/37354425/97724966-90535200-1b08-11eb-9713-a276ab479dc3.gif)

**Comment by 88250** [comment]
在 v1.1.8 中修复，谢谢。
