### ISSUE TITLE
同步服务器宕机了吗?

### ISSUE THREAD

**Issue by allblue** [siyuan-note/siyuan#3731]
社区也无法访问，官网倒是正常。
其他小伙伴能正常用吗？

**Comment by 88250** [comment]
麻烦 `ping ld246.com` 看下结果。

**Comment by allblue** [comment]
域名无法解析
```
C:\Windows\System32>ping ld246.com
Ping 请求找不到主机 ld246.com。请检查该名称，然后重试。
```

**Comment by 88250** [comment]
`ipconfig /flushdns` 后再 ping 了看下，如果还是无法解析，估计还要再等等 DNS 生效。

**Comment by 88250** [comment]
今天从早上开始，云端服务就被攻击了一波，下午我们切换了 DNS，如果没有生效的话只能再等等看了，抱歉抱歉。

**Comment by allblue** [comment]
找了二个在线网站测了下，大多解析不成功，还有10.88.88.88这种dns污染
![image](https://user-images.githubusercontent.com/844763/147879569-762f84de-a988-4389-99e2-b6adc13801de.png)

![image](https://user-images.githubusercontent.com/844763/147879578-a88f3f82-d7cf-457a-b0ef-e3d50ce612d9.png)

**Comment by allblue** [comment]
hosts里手动指定了ip，暂时可以用了

**Comment by 88250** [comment]
先凑合顶顶，我们再观察看看，后面如果还是不行，会考虑用其他域名做同步服务。

**Comment by allblue** [comment]
同步服务器是不是还有子域名?

**Comment by allblue** [comment]
> 先凑合顶顶，我们再观察看看，后面如果还是不行，会考虑用其他域名做同步服务。

同步服务器是不是用的子域名?

**Comment by 88250** [comment]
是子域名，不过不是 ld246.com 的。

解析到 `10.88.88.88` 的问题稍后应该能解决，再观察看看，谢谢。

**Comment by allblue** [comment]
> 

方便的话，可以透露下同步的域名吗，我再做个host指定
不方便就算了，我再等等:)

**Comment by allblue** [comment]
同步了30分钟，终于同步成功一次

**Comment by 88250** [comment]
再等等吧 🙏

**Comment by allblue** [comment]
收到:smile:

**Comment by guidongyuan** [comment]
从昨晚到现在，又同步不了了

**Comment by 88250** [comment]
@guidongyuan `ping ld246.com` 看看结果。

**Comment by guidongyuan** [comment]
ping不到

ping ld246.com
ping: cannot resolve ld246.com: Unknown host



At 2022-01-03 08:42:05, "D" ***@***.***> wrote:

@guidongyuanping ld246.com 看看结果。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 88250** [comment]
@guidongyuan Windows 系统上面执行 `ipconfig /flushdns` 后再 ping 了看，如果还是不行，麻烦再等等。

**Comment by guidongyuan** [comment]
我是mac，搜了一下，用sudo killall -HUP mDNSResponder
不过执行了还是不行，没事，我先等等。



At 2022-01-03 09:17:05, "D" ***@***.***> wrote:

@guidongyuan Windows 系统上面执行 ipconfig /flushdns 后再 ping 了看，如果还是不行，麻烦再等等。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by allblue** [comment]
> 

估计还在攻击中，12点，03点各同步成功一次，其他时候都是失败。早上又测了下，比昨天好点
![image](https://user-images.githubusercontent.com/844763/147898470-db51d300-bbe2-4a1f-a882-776dd25447ef.png)

**Comment by 88250** [comment]
@allblue 目前倒是没有攻击了，可能还是 DNS 没有生效。

**Comment by guidongyuan** [comment]
> @allblue 目前倒是没有攻击了，可能还是 DNS 没有生效。

D大，今天还是没有回复，Mac笔记本，能怎样操作吗？

**Comment by 88250** [comment]
@guidongyuan 重启一下系统看看。

**Comment by guidongyuan** [comment]
> @guidongyuan 重启一下系统看看。

感谢，刚刚重启就恢复了
