### ISSUE TITLE
建议加上英语单词的自动填充（autocomplete or auto-completion）功能

### ISSUE THREAD

**Issue by Rao-Jupiter** [siyuan-note/siyuan#3734]
# 应用场景
我经常使用思源笔记做笔记，也会使用其他的编辑器如vscode，kate，emacs等来随手写一点文档。我发现这些编辑器有auto-completion功能，就是在写英文单词的时候，只需要打前几个字母，编辑器就能从之前输入的文本中提取单词，就像写代码中的自动预测功能一样，这种功能可以极大提高写作的效率，特别是写草稿的时候。

### 描述可能的最优解决方案 

这种自动补全单词的功能在不同的软件里面有不同的称呼。在Kate，Notepad++里面的中文名称是“自动完成”

在其他的编辑器或者软件中可能被叫做“自动补全”

在emacs里面则主要是 company-mode 起作用

vscode 中有多种插件可以实现该功能，自带也有这种功能（但是对md格式要进行设置）

Obsidian里面的 various completion插件也有相同的功能

维基百科里面的描述如下：https://en.wikipedia.org/wiki/Autocomplete

# 其他信息

思源笔记在自动补全双链功能非常强大，如果加上这个单词自动补全功能会更高效

**Comment by 88250** [comment]
你好，这个要靠输入法解决了，我目前使用的是搜狗拼音，试了下基本还是能够工作的。

我关闭了，感谢提议。
