### ISSUE TITLE
代码块加入shift+tab左缩进功能

### ISSUE THREAD

**Issue by xibaoning** [siyuan-note/siyuan#3735]
很多文字编辑软件中,shift+tab可以左缩进, 建议加入此功能方便代码块的代码快速对齐,  现在是复制到其他软件中调整好再复制过来, 麻烦

**Comment by 88250** [comment]
目前代码块编辑器问题比较多，我们暂时不会进行改动了，后续请关注 https://github.com/siyuan-note/siyuan/issues/3141 感谢反馈。
