### ISSUE TITLE
HTML `<scope>` 标签解析渲染问题

### ISSUE THREAD

**Issue by orangee-wi** [siyuan-note/siyuan#374]
## 现状
当输入``<scope>``后，再用``Backspace``键删除时，渲染会出错，用``Typora``打开时，发现源文件会出现大量``HTML``标签，这才导致思源程序卡死
## 希望修复
正确渲染``<scope>``标签
## Demo
![siyuan-note_issue6](https://user-images.githubusercontent.com/37354425/97728079-1329dc00-1b0c-11eb-92d3-f33658c0d93a.gif)

**Comment by 88250** [comment]
感谢反馈，v0.3.9 修复。
