### ISSUE TITLE
大纲未渲染行级元素

### ISSUE THREAD

**Issue by AShao0425** [siyuan-note/siyuan#3743]
### 描述问题 Describe the problem
****
I recently noticed a little nasty issue on the outline sidebar of the application as the image shown follow, I have a delta sign wrote in latex rendered with Katex inside a heading, the output in editor is fully rendered but on the sidebar, it's not, is there a possible way to make Katex also rendered on the outline? That will be so much helpful to read through a heavy LaTeX+markdown document, I greatly appreciate the developers for building this application. 😄 

(ps: I am not quite sure about the category about my question on whether is should be classified in bugs or enchantments, I guess it's a bug since nobody ever noticed this so far)

### 期待的结果 Expected result
Fix the sidebar outline preview with Katex rendered

### 截屏或者录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/79273649/147997576-49167c99-4ee3-47ea-a78e-8f5bd05ff3f6.png)

### 版本环境 Version environment

* Version: v1.6.1
* Operating system: Windows 10 Enterprise
* Browser (if used): Edge

**Comment by 88250** [comment]
It's a bug, the outline should render some inline elements such as math, code, strong, and em. We will fix it in the next release, thanks.
