### ISSUE TITLE
同步/备份限制单个文件最大为 100MB

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3747]
大小超过 100MB 的文件不会被传输。 https://github.com/siyuan-note/siyuan/issues/2785

关于思源笔记无法继续支持大文件传输的公告 https://ld246.com/article/1641315252517

**Comment by SineMark2020** [comment]
已经有总量限制，这样的限制会影响使用者体验，如果不是技术上问题，建议早鸟结束后可以涵盖在订阅价格内。或者另开一个可以超过100M的更高级会员价格

**Comment by 88250** [comment]
@SineMark2020 目前有一些技术限制，主要原因是 CDN 不支持大于 100M 的文件传输。后期等有时间会可能考虑其他方案来进行改进，比如自动拆分/重组文件。

**Comment by zhuzixian** [comment]
很多PDF文件都是大于100M的，这样的限制是会带来诸多不便，希望能尽快有其它方案进行改进，或者是可以设置一个本地资源库，用户自动通过其它方式进行进行同步。

**Comment by zxlzy** [comment]
用的是哪个CDN呀，还有文件大小的价格限制，不用CDN直接用对象存储呢？因为同步备份这种场景比较个性化，用CDN的意义感觉也不大。

**Comment by 88250** [comment]
@zxlzy 目前是阿里云 CDN，后面会考虑迁移到 OSS。
