### ISSUE TITLE
锁屏一段时间，重新登录系统后关闭按钮失效

### ISSUE THREAD

**Issue by C3-DLearning** [siyuan-note/siyuan#375]
win10,双屏，仅使用第二屏幕。锁屏一段时间后，重新登录系统，思源界面的关闭按钮高亮且有提示信息，但无法点击，只能通过通知栏托盘区控制，之后软件恢复正常使用

**Comment by 88250** [comment]
关闭按钮在 v0.4.9 中进行了一些改进，等发布 v0.4.9 后麻烦升级到该版本并帮忙留意观察。

该 issue 我关闭了，如果有反馈请继续跟帖即可，谢谢。
