### ISSUE TITLE
优化预览模式和导出功能

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3753]
希望思源在接下来提升下预览模式和导出功能，让页面和编辑页面样式、布局等更接近。

有时候我写个文档，导出和预览模式，有些引用的文字，我觉得不用再加其他样式了。有些标签也不用显示出来。比如下图，预览模式，标签加了#。希望有一种模式，让文档更像一种直接写出来的文档（只包括字体、颜色、布局，不要引用样式、标签样式等），能够让别人正常阅读即可。我不知道D大能不能理解我说的。
、
![image](https://user-images.githubusercontent.com/15650275/148146347-7f9c31cb-336d-4893-a574-2ecf6307fcf8.png)

**Comment by 88250** [comment]
* 预览的话得用 Markdown，不然无法复制到其他平台
* 尽可能原样导出 HTML/PDF 的话请关注 https://github.com/siyuan-note/siyuan/issues/3104
