### ISSUE TITLE
一直卡在云端同步信息获取失败

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3758]
这种情况下还可以编辑笔记吗

![image](https://user-images.githubusercontent.com/33319484/148218905-a94cc5c7-cad0-42a6-83b9-3f986a4ea4e6.png)

版本：1.6.2
系统 mac 11.6

**Comment by 88250** [comment]
可以编辑，但是不同设备上都离线编辑以后会相互覆盖，只能从历史找回。

云端服务的网络问题我们正在处理，明天应该能解决，感谢理解。
