### ISSUE TITLE
使用`` 标记的时候无法在内部最后一个字符上继续追加

### ISSUE THREAD

**Issue by kukukafei** [siyuan-note/siyuan#3760]
使用`` 标记的时候无法在内部最后一个字符上继续追加，
 例如：当我写完这个命令，需要继续在后面增加字符的时候，   ` ps -ef `  预览工具已经将 这句话格式化成单行代码，如果在结尾继续写入字符，字符会输出到符号外面，` ps -ef ` | grep   。

是否可以增加编辑makedown 源码的功能，方便修改

**Comment by 88250** [comment]
你好，请参考 https://github.com/siyuan-note/siyuan/issues/2904
