### ISSUE TITLE
移动文档后不再自动展开目标文档

### ISSUE THREAD

**Issue by laffael** [siyuan-note/siyuan#3764]
目前可以发现, 移动文档块A至另外文档块B后, 会自动展开从根文档块到文档块B的文档树的情况. 

这种情况, 如果从root到文档块B, 或者文档块B当中含有众多文档块的情况, 会展开很长. 
请问下是否能够提供选项, “不自动展开文档树”

谢谢

**Comment by 88250** [comment]
你好，我这里重现不了，麻烦录屏演示一下操作。

![issue](https://user-images.githubusercontent.com/873584/148383778-cc5cefa9-e693-4dd9-af61-2c97ab7b791d.gif)

**Comment by laffael** [comment]
![问题反馈](https://user-images.githubusercontent.com/19380552/148551464-40733da9-7b18-4532-966e-893fde6773b2.gif)
根据这个视频, 我这边按照点击文档块直接移动 和 通过右键移动, 都会自动展开文档树. 
软件版本已经更新为1.6.2.
