### ISSUE TITLE
开启访问授权以后导出 PDF/Word 时图片丢失

### ISSUE THREAD

**Issue by mufanx** [siyuan-note/siyuan#3765]
### 笔记导出 PDF 后图片丢失（图片是本地图片）

本地复制或者拖到笔记上的图片，并没有在图床上，程序会将图片复制一份到 /data/assert/ 目录下，然后在笔记中进行引用，显示均没有问题，但是导出 PDF 后，原来图片处显示图片失败。

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="803" alt="image" src="https://user-images.githubusercontent.com/35735090/148359460-fabc17d8-e3aa-4027-8f88-6918f554642f.png">
<img width="438" alt="image" src="https://user-images.githubusercontent.com/35735090/148359560-437e3dc4-750e-4aae-a85f-c523e829a42d.png">

### 版本环境 Version environment

* Version: 1.6.3
* Operating system: Mac OS 12.1 Apple Silicon
* Browser (if used): Desktop App

### 其他
因为测试了一下发现网络链接图片是导出正常的，所以怀疑是导出时图片链接有问题，然后尝试把链接前面加了一个 ./ 之后导出就正常了了。
<img width="842" alt="image" src="https://user-images.githubusercontent.com/35735090/148359971-3900fad7-4c74-4a7a-9ef8-fbdac62e24f7.png">
应该是资源链接的问题，希望早日修复。

**Comment by 88250** [comment]
你好，我这里重现不了问题，请看下是不是设置了访问授权码？

**Comment by mufanx** [comment]
你好，我发现是的，我开启了：
在关闭后导出 PDF 中图片显示正常了。

Sent with a Spark
在 2022年1月6日 +0800 PM10:24，D ***@***.***>，写道：

**Comment by 88250** [comment]
感谢确认，这个问题近期会修复。
