### ISSUE TITLE
改进移动包含大量子文档层级的文档时的性能

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3767]

**Comment by JokeenZhang** [comment]
这里的大量，包括数量多，以及文档本身大小也很大的范畴吗？还是仅仅支持多子文档的父文档移动？

**Comment by 88250** [comment]
@JokeenZhang 仅是多子文档数量的父文档移动。

**Comment by JokeenZhang** [comment]
如果数量过多，会失败吗，失败的话会怎么处理来着，这个有点慌

**Comment by 88250** [comment]
数量非常多的话会有个进度遮罩提示，只要不打断，文件不被占用应该不会失败。
