### ISSUE TITLE
Win11预览版闪退

### ISSUE THREAD

**Issue by checkwoodson** [siyuan-note/siyuan#3768]
### 期待的结果 Expected result
能够正常的运行

### 版本环境 Version environment

* Version: 1.6.3
* Operating system: win11预览版
* Browser (if used): 

### 日志文件 Log File
[siyuan.log](https://github.com/siyuan-note/siyuan/files/7822975/siyuan.log)

这是temp下面的日志。
I 2021/12/30 22:44:59 working.go:96: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
E 2021/12/30 22:44:59 rsync.go:82: unzip rsync failed: open C:\Users\checkwoodson\Documents\SiYuan\temp\rsync\bin\rsync.exe: The process cannot access the file because it is being used by another process.
I 2021/12/30 22:45:02 runtime.go:61: kernel is booting:
    * ver [1.5.5]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211218]
    * workspace directory [C:\Users\checkwoodson\Documents\SiYuan, data 20 kB]
    * rsync [version 3.2.4dev  protocol version 31]
    * pandoc [pandoc.exe 2.13]
D 2021/12/30 22:45:03 conf.go:108: initialized language [zh_CN] based on device locale
I 2021/12/30 22:45:03 conf.go:257: local serve path [http://192.168.1.11:6806]
I 2021/12/30 22:45:03 serve.go:68: kernel is booting [http://127.0.0.1:6806]
I 2021/12/30 22:45:03 database.go:73: reinitialized database [C:\Users\checkwoodson\Documents\SiYuan\temp\siyuan.db]
I 2021/12/30 22:45:03 conf.go:484: pre-init database size [4.1 kB]
I 2021/12/30 22:45:03 index.go:215: resolving refs...
I 2021/12/30 22:45:03 index.go:355: resolved refs
I 2021/12/30 22:45:03 conf.go:501: post-init database size [4.1 kB], tree stat [count=0, size=0 B]
I 2021/12/30 22:45:03 working.go:136: kernel booted
I 2021/12/30 22:45:07 index.go:202: rebuilt database for notebook [20210808180117-czj9bvb] in [0.22s], tree stat [count=46, size=890 kB]
I 2021/12/30 22:45:07 index.go:215: resolving refs...
I 2021/12/30 22:45:07 index.go:355: resolved refs
I 2021/12/30 22:45:40 index.go:202: rebuilt database for notebook [20210808180117-czj9bvb] in [0.22s], tree stat [count=46, size=890 kB]
I 2021/12/30 22:45:40 index.go:215: resolving refs...
I 2021/12/30 22:45:40 index.go:355: resolved refs
I 2021/12/30 22:45:43 conf.go:359: exited kernel
I 2021/12/30 22:46:43 working.go:96: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2021/12/30 22:46:46 runtime.go:61: kernel is booting:
    * ver [1.5.6]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211218]
    * workspace directory [C:\Users\checkwoodson\Documents\SiYuan, data 5.7 MB]
    * rsync [version 3.2.4dev  protocol version 31]
    * pandoc [pandoc.exe 2.13]
I 2021/12/30 22:46:46 conf.go:257: local serve path [http://192.168.1.11:6806]
I 2021/12/30 22:46:46 serve.go:68: kernel is booting [http://127.0.0.1:6806]
I 2021/12/30 22:46:46 conf.go:484: pre-init database size [2.4 MB]
I 2021/12/30 22:46:46 index.go:131: use existing database for box [20210808180117-czj9bvb]
I 2021/12/30 22:46:46 index.go:212: resolving refs...
I 2021/12/30 22:46:46 index.go:352: resolved refs
I 2021/12/30 22:46:46 conf.go:505: post-init database size [2.4 MB], tree stat [count=46, size=890 kB]
I 2021/12/30 22:46:46 working.go:136: kernel booted
I 2021/12/30 23:04:40 index.go:202: rebuilt database for notebook [20211230230440-adf4uuo] in [0.01s], tree stat [count=0, size=0 B]
I 2021/12/30 23:04:40 index.go:212: resolving refs...
I 2021/12/30 23:04:40 index.go:352: resolved refs
I 2021/12/30 23:22:23 conf.go:359: exited kernel

**Comment by netdog2019** [comment]
你哪个log显示是1.5.5版本啊，另外，你时间是不是设置不对？怎么是2021.12.30？

**Comment by netdog2019** [comment]
我也是win11，一点问题没有。

**Comment by 88250** [comment]
楼主，麻烦上传一下这个日志 C:\Users\用户名\.config\siyuan\app.log

**Comment by checkwoodson** [comment]
> 

回去我在看看时间对不对，在确认可能是因为时间问题导致应用打不开，但是时间应该不会导致应用打不开吧。electron不会因为时间而闪退吧。

**Comment by checkwoodson** [comment]
> 楼主，麻烦上传一下这个日志 `C:\Users\用户名\.config\siyuan\app.log`
晚上我在上传。

**Comment by checkwoodson** [comment]
我解决了， 看了日志说连接失败，然后我自己修复了网络就好了。 这个软件还要联网，这个玩意不联网不行嘛？

**Comment by 88250** [comment]
> 我解决了， 看了日志说连接失败，然后我自己修复了网络就好了。 这个软件还要联网，这个玩意不联网不行嘛？

可以断开互联网，但是不能禁用网卡。

**Comment by checkwoodson** [comment]
我修复的是host，可能之前加了一个host导致网络问题。好吧。不能禁用网卡。。。
