### ISSUE TITLE
微信提醒汇总

### ISSUE THREAD

**Issue by netdog2019** [siyuan-note/siyuan#3769]
添加了微信提醒的块能否加个标识，一眼能看出哪个块加了微信提醒，最好是还能看到设置了什么时间提醒。

**Comment by 88250** [comment]
这个编辑器里暂时就不添加了，后面考虑通过挂件进行汇总展示。

**Comment by yanyu2015** [comment]
> 添加了微信提醒的块能否加个标识，一眼能看出哪个块加了微信提醒，最好是还能看到设置了什么时间提醒。

其实觉得是很好的建议，因为如果你有很多todolist，而其中一个作为提醒标识，那么不加区分很容易就不小心自己勾了，删了，移动了导致提醒失效，目前我就遇到过两次，还纳闷咋个没提醒，回头一看，已经记不得当时设置的是哪个了。

**Comment by 88250** [comment]
@yanyu2015 提醒是即时设置的，和后续该块的状态没有关联，和块类型也没有关联，所以不只是任务列表可以设置。设置了提醒以后即使本地块不再存在，云端也会提醒的。
