### ISSUE TITLE
移动端界面优化：沉浸式状态栏

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#3772]
能否在ios和安卓端增加沉浸式状态栏，现在一条黑色的不太美观

**Comment by 88250** [comment]
麻烦截图一下，谢谢。

**Comment by lisontowind** [comment]
![cc6facf4dac6f0a5d25bb9970c71d3b](https://user-images.githubusercontent.com/47842345/148482471-9ec93f53-1793-428a-93f7-1c986e9b0619.jpg)
![b0e6e28ff1cc65ea0fd4bf5bc8eba91](https://user-images.githubusercontent.com/47842345/148482492-4a8959e5-6895-4659-bfdb-d0968a933f2a.jpg)

**Comment by 88250** [comment]
请问 Android 手机型号是？

**Comment by lisontowind** [comment]
> 请问 Android 手机型号是？

mi10

**Comment by 88250** [comment]
这个安全距离留出用的是 Android 提供的方式实现的，可能是手机系统还是有兼容性问题。主要是没有真机，不好调试，所以可能只能先这样了……

**Comment by mohuishou** [comment]
同 mi10 感觉这个就像是把应用全屏了，状态栏都不显示了

**Comment by 88250** [comment]
嗯，是设置了全屏。感觉不设置全屏要好一些吗？

**Comment by mohuishou** [comment]
> 嗯，是设置了全屏。感觉不设置全屏要好一些吗？

不设置全屏应该至少能看到状态栏，现在是状态栏都看不到，只有一个大黑边

**Comment by 88250** [comment]
了解了，应该是需要实现透明状态栏那种风格。

**Comment by 88250** [comment]
后续会将状态栏调整为不隐藏 https://github.com/siyuan-note/siyuan/issues/3900
