### ISSUE TITLE
iOS 端短时间关闭屏幕会出现内核中断

### ISSUE THREAD

**Issue by netdog2019** [siyuan-note/siyuan#3775]
ios端短时间关闭屏幕会出现内核中断，无法拉起后台，但是如果关闭屏幕时间比较长，反而会自动拉起。
1.6.3

**Comment by Vanessa219** [comment]
关闭多短的时间？这里试了很多次也无法重现

**Comment by netdog2019** [comment]
IOS端，关闭1~2min，再次打开就会显示内核中断。

**Comment by netdog2019** [comment]
IOS端，关闭1~2min，再次打开就会显示内核中断。

> 关闭多短的时间？这里试了很多次也无法重现

**Comment by Vanessa219** [comment]
无法重现，有错误日志么？

目前在中断界面加了个重试按钮先顶顶，等可以重现了再解决。

**Comment by netdog2019** [comment]
> 无法重现，有错误日志么？
> 
> 目前在中断界面加了个重试按钮先顶顶，等可以重现了再解决。

有了重试的按钮，也会出现内核中断，点击重试后，马上就可以了。另外，请问ios端，怎么打开日志文件呢？我看群里几个人用IOS端的都出现同样内核中断的问题。

**Comment by 88250** [comment]
@netdog2019 目前没法查看或者导出日志文件，后面考虑。
