### ISSUE TITLE
希望Android版本也可以修改work space的位置

### ISSUE THREAD

**Issue by elfzweik** [siyuan-note/siyuan#3787]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
我的新手机是Pixel 6 pro，运行Android 12，强制不显示/storage/simulated/0/Android/data下的文件夹，导致不能进行第三方网盘同步，故希望能够允许修改work space位置。谢谢！

**Comment by 88250** [comment]
你好，移动端需要先支持在 Android data 路径下的工作空间切换后才能考虑你的提议，但是目前看来，移动端切换工作空间还没有太多人需求，所以就先不考虑了，谢谢。

如果需要自建同步机制的话，请关注 https://github.com/siyuan-note/siyuan/issues/3736

**Comment by elfzweik** [comment]
谢谢回复。#3736提议的想法我也很赞同，如果能实现以docker为中心进行同步，就很完美了。我现在也是用syncthing以NAS为中心，分别与电脑、手机、平板进行同步，除了Android 12关闭了data目录权限，其他设备同步效果很好。另外，Joplin用webdav同步，这样处理是最简单的，我使用的时候也没有发现同步丢数据问题。只要把同步功能集成在思源内，可以自己控制同步的时点，应该不会出现争夺锁定文件导致出现同步问题的情况吧。供参考。

**Comment by heddxh** [comment]
Android12并没有关闭data目录的访问权限，我的设备是pixel4 xl，使用[foldersync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite)可以正常同步。是不是你哪里设置错了？

![Screenshot_20220202-112354.png](https://user-images.githubusercontent.com/63106571/152088375-a708810a-de1a-4209-8981-1983637a9f6a.png)

**Comment by realysy** [comment]
希望能修改笔记本文件夹的位置+1. 用户通过第三方同步带来的潜在数据损失风险，可在用户修改时弹窗提示，尽到告知义务，风险由用户选择是否承担。
