### ISSUE TITLE
文档块右侧偶然会出现蓝色Blocks滚动条

### ISSUE THREAD

**Issue by VisionTheta** [siyuan-note/siyuan#3792]
### 描述问题 Describe the problem

在某些打开的文档右侧，会出现一个蓝色的滚动条，观察了下可以在Blocks间进行滚动，但是不知道如何关闭/或如何在其他文档中打开。

由于不知道这个滚动条叫什么，使用开发者工具查看，显示input.b3-slider。详情请见截图。

### 期待的结果 Expected result

希望知道这个滚动条是什么，如何打开或关闭该元素。

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/7656532/148785701-9d579020-5580-4335-9180-eb56ab75f304.png">

<img width="146" alt="image" src="https://user-images.githubusercontent.com/7656532/148785870-6437f6a0-d8fb-44df-babe-6a04c5092c45.png">

### 版本环境 Version environment

* Version: v1.6.3
* Operating system: MacOS Version 12.1
* Browser (if used):

**Comment by 88250** [comment]
你好，这个是动态加载滚动条，用于在较大的文档中快速定位的。它应该是在文档中顶层子块大于 32 个时出现，无法关闭，是程序自动判断的。

我先关闭 issue 了，如果还有需要讨论的欢迎跟帖，谢谢。
