### ISSUE TITLE
导出 HTML 时自包含 js/css 和 assets

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3797]
https://ld246.com/article/1634630213727

**Comment by Zuoqiu-Yingyi** [comment]
还有图片静态资源要不一块安排上❓
#3581

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 谢谢提醒，这个会在这个 issue 内一起处理，但是不是用 Base64 嵌入，而是直接放到导出文件夹的 assets 文件夹下面。
