### ISSUE TITLE
支持空列表项回车断开

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3804]
https://ld246.com/article/1641992589780

**Comment by choyy** [comment]
最好也能支持方便的合并列表🧐

**Comment by hanson-reas** [comment]
> 最好也能支持方便的合并列表🧐

补充：是合并为一整个无序列表块，而不是合并为超级块

**Comment by choyy** [comment]
> > 最好也能支持方便的合并列表🧐
> 
> 补充：是合并为一整个无序列表块，而不是合并为超级块

补充: 有序列表、任务列表、**段落块**也需要这样的合并

**Comment by qifengle1998** [comment]
这个需求我在好早好早前提过。
有序列表断开后。
序号的编排也是一个问题
比如断开123456789。
有的时候希望是  12345  1234
有的时候又希望能够保持原来的结构。   12345 6789

所以要是能和word那样，有“继续编号”以及“设置编号值”这两个直接处理序号的选项就好了😂

**Comment by qifengle1998** [comment]
其实最理想的状态就是 可以自由地断开、合并所有容器块（逃

**Comment by Vanessa219** [comment]
其余功能请新建 issue
