### ISSUE TITLE
请求增加 用API导出整个笔记 为markdown的文件夹

### ISSUE THREAD

**Issue by rewreu** [siyuan-note/siyuan#3810]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
思源笔记已经可以手动批量导出整个笔记本为压缩文件夹。是否可以增加导出整个笔记本的API
原因和场景：
[思源笔记是否可以批量导出全部笔记为 markdown](https://ld246.com/article/1638701719178)

**Comment by 88250** [comment]
可以打开 F12 看下网络请求。

公开的 API 暂时不会有，因为这个导出实在太慢了，做成自动化可能会不够稳定。以后等有机会再考虑做成 public api。
