### ISSUE TITLE
切换页签的顺序改进提议

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#3812]
1.7.0版本的页签切换顺序为：
control/ctrl+tab 页签顺序切换
control/ctrl+shift+tab 页签倒序切换

建议：
这个 Ctrl + tab 能不能改为在最近的打开页签之间切换。类似 IntelliJ IDEA 等 JetBrain 系的软件那样。
比如打开的页签有a b c d e，当前查看的c，上一个查看的是a，ctrl tab之后会切换到a，再ctrl tab会切换到c；不停按 ctrl tab 会在 a c之间来回切换，而不是按照顺序切换到“非活动状态”的 d e 等页签。

原issue #533 

> 你在什么场景下需要该功能？ In what scenarios do you need this function?
日常切换标签页 (Shift) Ctrl Tab

> 描述最优的解决方案 Describe the optimal solution
behave like browsers

> 描述候选解决方案 Describe the candidate solution
NA

> 其他信息 Other information
NA

**Comment by 88250** [comment]
你好，这个设计暂时不会变了，两个页签之间切换的话可以考虑用前进后退。

**Comment by Wonderdch** [comment]
好像 VS 也是这样的，但这种设置真的让人很烦，尤其是它和常用的浏览器设置不一样。
