### ISSUE TITLE
点击setting-asserts 显示 "查找命令 [unusedassets] 失败"

### ISSUE THREAD

**Issue by SimonZYC** [siyuan-note/siyuan#382]
系统：MacOS 10.15.7
思源版本：0.3.9

![asserts](https://user-images.githubusercontent.com/21327543/97783296-b5f85e00-1bd1-11eb-883a-058ba5e3e67b.gif)

**Comment by 88250** [comment]
是自动更新升级的话麻烦重新全量安装一次，谢谢。

**Comment by SimonZYC** [comment]
全量重新安装后仍然有同样的问题。

**Comment by 88250** [comment]
我这里 Windows 和 macOS 都重现不了，从报错上看感觉是版本问题，麻烦完全卸载清理以后再安装试试。

**Comment by 88250** [comment]
你好，v0.4.0 已经发布，请重新安装再试试，谢谢。
