### ISSUE TITLE
table 嵌套类似页面功能，类似notion

### ISSUE THREAD

**Issue by pusuanzi1** [siyuan-note/siyuan#3821]
感谢支持我提的题头图用了网络链接的建议，非常好，建议是否可以增加notion的table，因为wolai 也有类似的功能，可以让思源更好地管理知识。目前使用过程中一直在notion和思源之间切换。就是因为思源没有这个table 嵌套页面的功能。期望作者能够考虑开发一下。如果有我觉得可以增加很大的市场份额。

**Comment by 88250** [comment]
我们应该不会开发和 Notion 一样的 database 功能，但是有类似的方案可以进行数据汇总展示，请关注 https://github.com/siyuan-note/siyuan/issues/2829
