### ISSUE TITLE
移除中西文间自动插入空格

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3826]
自动空格功能还是有些无法解决的问题，我们会在 v1.7.2 中移除中西文自动空格功能。

以后如果找到好的方案我们会继续尝试。

**Comment by glatavento** [comment]
可否考虑一下加入一个“在整个文档的中英文之间加入空格”的按键/快捷键？相当于把加空格的时间从编辑时改为编辑完成后，这样的话问题应该会少很多

**Comment by 88250** [comment]
@glatavento 考虑过的，但是反向操作（即移除空格）会有些问题。导出应该可以支持添加空格，这个后面考虑。

**Comment by Zuoqiu-Yingyi** [comment]
要不要搞个*实验性功能*选项, 将这些有一些问题的功能塞进去, 毕竟这个功能我用的时候没啥问题  o(╥﹏╥)o

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 后面考虑吧，现在得先继续推进主线。

**Comment by Shad0wpf** [comment]
> 要不要搞个_实验性功能_选项, 将这些有一些问题的功能塞进去, 毕竟这个功能我用的时候没啥问题 o(╥﹏╥)o

一直留在思源笔记其中一个原因就是因为这个功能，结果突然没了

**Comment by guidongyuan** [comment]
这里能否做到，不要插入一个空格，而是在UI展示的时候，中西文展示多一点间距
