### ISSUE TITLE
特定情况下文档树和大纲展开/折叠快捷键不直接生效

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3831]
### 描述问题 Describe the problem
当文档树和大纲分别在两侧且为展开状态时，快捷键alt+1和alt+2不是直接折叠，而是先“选中”该面板之后再折叠
比如当前文档树处于“选中”状态，此时若想用alt+2折叠大纲，必须按两次快捷键

### 期待的结果 Expected result

按下快捷键后直接折叠

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Peek 2022-01-15 20-20](https://user-images.githubusercontent.com/68107073/149622452-a06f6dfa-82b1-450e-9654-6847d405d3eb.gif)

**Comment by 88250** [comment]
这个是特性，第一次按下为聚焦到该面板，以便使用其他按键或者快捷键。
