### ISSUE TITLE
关于增加「回到上次编辑位置」功能的建议

### ISSUE THREAD

**Issue by JOYCELEEEEE** [siyuan-note/siyuan#3832]
# 场景描述
个人的文档以万字长文档为主，而关闭一个文档通常是在完成该文档的所有内容之后，因此一个页面经常处于长期不关闭的状态。

但每次在重新启动电脑或者第二天打开电脑（休眠状态）时，思源中没有关闭的页面的内容会重新跳到页首，需要手动翻回上次的编辑位置。
# 问题
如果对一个文档的编辑工作是从空白页开始的，那么上次编辑的位置应当是在文档的最底部，这种情况下可以直接利用右侧的拖动条；
但如果对一个文档的编辑工作是对已有内容进行的再加工，那么上次编辑的位置并非在文档的最底部，此时拖动条就无法产生作用（盲拖拖不准）。
# 建议
个人认为未关闭的文档意味着尚未处理完毕，为考虑便捷性，应当①在重启思源后直接固定在上次编辑处。

如果认为有重新加载至页首的必要，那么希望能够②增加「回到上次编辑位置」的功能。
# 功能参考：word
<img width="270" alt="Snipaste_2022-01-15_19-35-07" src="https://user-images.githubusercontent.com/89592448/149622521-ae3f432f-fec0-4dc6-af19-69f5b3a3a7ea.png">                     <img width="78" alt="Snipaste_2022-01-15_19-35-33" src="https://user-images.githubusercontent.com/89592448/149622532-46a50415-77c7-4268-a0d2-27427d59437f.png">

可模仿word中为方便浏览大型文档的「回到上次编辑位置」功能：重启思源时，可以提供**未关闭文档**（非仅当前）上次编辑位置的跳转弹窗，几秒后消失。

超大文档的加载与编辑是思源的核心竞争力之一，因此个人认为增加「回到上次编辑位置」功能有一定的必要性（实际个人倾向①）。

若能采纳，不胜感激。

**Comment by choyy** [comment]
上次我提的时候D说因为技术原因实现不了。。。

**Comment by JOYCELEEEEE** [comment]
> 上次我提的时候D说因为技术原因实现不了。。。

啊...直接保持原编辑位置也不行吗😔

**Comment by 88250** [comment]
目前实现不了，先关闭了。后面如果有方案我们会考虑的，感谢提议。
