### ISSUE TITLE
ctrl+shift+f 改为全局快捷键

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3833]
ctrl+shift+f的全局搜索单独使用时不生效，只有选中文本再用快捷键才生效
不知道这是特性还是bug

**Comment by 88250** [comment]
这是特性，选中以后打开搜索页签进行搜索。

**Comment by choyy** [comment]
@88250 还是希望支持ctrl+shift+f单独使用
应该也有不少人觉得这样更自然[https://ld246.com/article/1638088366097](https://ld246.com/article/1638088366097)

**Comment by 88250** [comment]
这个需求更适合用面板来做，后续请关注搜索面板 https://github.com/siyuan-note/siyuan/issues/3564

**Comment by choyy** [comment]
想起来一个事，`输入（（内容块引用搜索支持鼠标悬浮预览`这个特性好像有人提过，考虑支持吗
刚刚搜也没搜到

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3517

**Comment by choyy** [comment]
原来要悬浮在块标啊

**Comment by Vanessa219** [comment]
还是和 https://github.com/siyuan-note/siyuan/issues/3840 一起处理一下吧
