### ISSUE TITLE
Docker 多帐号系统特性

### ISSUE THREAD

**Issue by SineMark2020** [siyuan-note/siyuan#3838]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

一个家庭多只使用一台NAS，如果思源只能给一位成员使用很可惜，建议可以建立多帐号系统给多位成员使用

### 描述可能的最优解决方案 Describe the optimal solution

思源文档是以笔记本独立形式，所以只要让不同帐号只能显示存取特定笔记本，就能给不同帐号区隔使用。

设置由admin订阅帐号统一掌控，其他帐号只能建立修改自己的鉴权密码(多帐号特性建立会简单很多)。
也因为鉴权密码是由不同帐号自行设立，所以admin帐号也不会知道其他成员内容，除非是NAS(Docker)系统拥有者能进入文档，此部分建议在使用文档内说明。

登录类似如下
![image](https://user-images.githubusercontent.com/93247476/149644833-79621161-6cf1-45cf-9783-ef94d6c1d5cb.png)

### 其他信息 Other information

此为高级特性，只有订阅会员才能建立多帐号。
为了让云端同步备份单纯化，建立多使用者帐号时，可以将云端同步备份功能关闭(通常Docker使用者也不太需要云端同步功能)，或只有admin帐号能够拥同步功能。

**Comment by 88250** [comment]
你好，思源笔记目前的定位是个人知识管理系统，所以暂时不会考虑实现账号权限管理功能。

如果有多人使用 Docker 的场景，需要用不同的账号进行部署。

**Comment by SineMark2020** [comment]
了解，我记得思源的端口好像只有6806一组，似乎只能一人使用。
如果不让此功能实现，Docker使用者就不会想付费，这算是增加订阅动机，殊为可惜。

**Comment by 88250** [comment]
将 6806 映射到宿主机不同的端口，然后通过配置反向代理可以实现多个容器同时使用。

**Comment by SineMark2020** [comment]
原来如此，那就不需要多帐号特性，我确认看看，谢谢

**Comment by crendy** [comment]
诉求+1
我认为多账号和个人知识管理系统不冲突，docker部署多个容器相对麻烦了，也占用资源，更新升级也增加很多隐形的维护成本。
云端同步都有账号的概念，本地和docker是否也考虑可以加上多账号数据隔离

**Comment by crendy** [comment]
> 诉求+1 我认为多账号和个人知识管理系统不冲突，docker部署多个容器相对麻烦了，也占用资源，更新升级也增加很多隐形的维护成本。 云端同步都有账号的概念，本地和docker是否也考虑可以加上多账号数据隔离

@88250

**Comment by 88250** [comment]
@crendy 欢迎 PR 贡献代码
