### ISSUE TITLE
文档中 emoji 分类失效

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#3844]
![B](https://user-images.githubusercontent.com/38906705/149649666-c73c1413-16f8-4816-8e74-0a0f2a5da557.gif)

**Comment by Vanessa219** [comment]
搜索以后就没有进行分类了。符合条件的全部放在一起，在一起，一起，起了。

**Comment by 88250** [comment]
@Vanessa219 搜索结果可能要单独处理，去掉下面的分类避免误解。
