### ISSUE TITLE
移动端编辑工具栏

### ISSUE THREAD

**Issue by zhaiqi9999** [siyuan-note/siyuan#3845]
![Screenshot_20220116_193653](https://user-images.githubusercontent.com/75944555/149658241-ca123bfa-fc36-4ca8-8b5e-f9a24eecf6ce.jpg)
幕布的快捷工具栏体验很好，尤其是调整无序列表级别，在移动端很需要。目前移动端的编辑基本等于不可用的状态，只能用作查看
希望可以加入类似的工具栏，移动端如果完善的话可以一定程度上取代云端inbox的功能～

**Comment by Vanessa219** [comment]
同 https://github.com/siyuan-note/siyuan/issues/2621
