### ISSUE TITLE
空文档点击能否默认是一个文件夹

### ISSUE THREAD

**Issue by 89trillion-longzu** [siyuan-note/siyuan#3851]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
需求：创建一个空文档，可以设置它是一个文档或者一个文件夹
如果是文件夹的话点价它应该产生哪个文件夹专属的小箭头
如果是文档的话可以编辑

**Comment by 88250** [comment]
设计上文档既文件夹，不会进行区分的。
