### ISSUE TITLE
鼠标选中拖动代码块内容后行号消失

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3852]
默认主题也是如此
![Peek 2022-01-17 16-01](https://user-images.githubusercontent.com/68107073/149731068-b6cb1e50-ab7a-4c98-b6e5-da6dab534aac.gif)

**Comment by 88250** [comment]
代码块编辑器的问题不修复了，后面考虑重写 https://github.com/siyuan-note/siyuan/issues/3141
