### ISSUE TITLE
反链浮窗支持在标签中打开

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#3853]
思源中通过块后面的角标查看反链很方便，它是以浮窗形式展现，但浮窗目前貌似无法在标签中打开，很多时候想把反链的内容在新标签中打开却不行，只能打开文档再手动翻到那个地方
希望可以增加在标签中打开
![图片](https://user-images.githubusercontent.com/68107073/149731284-22599570-23bd-428f-b3c5-9dbfb55f3281.png)

**Comment by 88250** [comment]
Ctrl+单击反链条目。
