### ISSUE TITLE
Editor tab widget slot

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3862]
编辑器页签上下左右 4 个方位槽支持放置挂件。

**Comment by mozhux** [comment]
这个嵌套类似ob那样吗，其实就是并列一起那样就行，如果是侧边那种，鼠标移动路径太长了

**Comment by mozhux** [comment]
啥时候开始弄呀

**Comment by 88250** [comment]
@mozhux 等反链面板改造完再看情况。

**Comment by mozhux** [comment]
> 
嘿嘿，那反链面板改造要提上日程了

**Comment by 88250** [comment]
嗯，争取近期开工。

**Comment by lentikr** [comment]
> @mozhux 等反链面板改造完再看情况。

期待2.4.x加入插件机制

**Comment by 88250** [comment]
目前已经确立插件机制，所以不再考虑编辑器挂件槽了，后续考虑通过插件 API 支持这方面的扩展 https://github.com/siyuan-note/siyuan/issues/5066
