### ISSUE TITLE
新建文件位置异常

### ISSUE THREAD

**Issue by code4wt** [siyuan-note/siyuan#3863]
### 描述问题 Describe the problem
一个月前刚开始使用思源时，新建文档，文档排在最后位置。但不知道从什么开始，新建文档都是排在第一位了，这就导致每次都需要我手动拖到最后，非常麻烦。

### 期待的结果 Expected result
新建文档在自定义排序下，排在最后。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![新建文件位置异常](https://user-images.githubusercontent.com/25877772/149884910-6fc66cba-5904-40e3-b791-4c724b6c7c06.gif)

### 版本环境 Version environment

* Version: v1.7.3
* Operating system: Windows 10 21H1 专业版

### 日志文件 Log File
[siyuan.log](https://github.com/siyuan-note/siyuan/files/7886858/siyuan.log)

**Comment by 88250** [comment]
新建是放在顶部的，之前考虑过放在底部 https://github.com/siyuan-note/siyuan/issues/3181

**Comment by code4wt** [comment]
> 新建是放在顶部的，之前考虑过放在底部 #3181

默认放到顶部可以，但是能否个用户一个选项，让用户能够设定新建文档的位置？每个人的习惯

**Comment by 88250** [comment]
暂时不考虑，感谢理解。
