### ISSUE TITLE
单个文档字数较多时卡顿

### ISSUE THREAD

**Issue by Young-Flash** [siyuan-note/siyuan#3864]
![image](https://user-images.githubusercontent.com/71162630/149942498-b89ef53d-51a6-4668-8ada-1d5cf97693d4.png)
基本上都是代码，在大纲切换查看不同标题时有明显卡顿感，关掉代码行号后会好一些，建议优化

**Comment by Young-Flash** [comment]
机器的性能方面是没问题的，使用思源时内存占用不到 50%

**Comment by 88250** [comment]
你好，代码块相关的问题目前不做修复了，以后会重置代码编辑器 https://github.com/siyuan-note/siyuan/issues/3141
