### ISSUE TITLE
导出 PDF 时行内加粗/行内斜体内的行内公式消失

### ISSUE THREAD

**Issue by glatavento** [siyuan-note/siyuan#3866]
### 描述问题 Describe the problem

如题，导出 PDF 时行内加粗/行内斜体内的公式块消失

### 期待的结果 Expected result

导出 PDF 时行内加粗/行内斜体内的公式块应当按未加粗/斜体正常渲染

### 截屏或者录屏演示 Screenshot or screen recording presentation

文档：
![图片](https://user-images.githubusercontent.com/76601050/150046195-99a09a2b-477a-4cd1-8f45-f8f9a5fafabb.png)

导出的 PDF：
![图片](https://user-images.githubusercontent.com/76601050/150046218-3cc13249-9c5e-48d0-8b15-013a9e56dbbf.png)

### 版本环境 Version environment

* Version: 1.7.3
* Operating system: Linux

**Comment by 88250** [comment]
麻烦上传一下这个测试用的 .sy 文件。

**Comment by glatavento** [comment]
见[新文档.zip](https://github.com/siyuan-note/siyuan/files/7904129/default.zip)
