### ISSUE TITLE
正文中父级标题折叠后再展开子级标题的折叠状态丢失

### ISSUE THREAD

**Issue by Young-Flash** [siyuan-note/siyuan#3869]
如题：比如在**正文**中有一个一级标题，其下有若干个二级标题；此时将所有二级标题折叠后将该一级标题折叠，再展开这个一级标题后下面所有的二级标题都会展开。不知道这是 bug 还是没注意这点，大纲里就没有这个问题。

**Comment by 88250** [comment]
目前不支持保持子级的折叠状态，感谢反馈。
