### ISSUE TITLE
搜索栏中的类型过滤希望可以记忆是否打开和自己选择的类型

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#3870]
每次重开搜索栏类型过滤都会默认关闭且内容需要重新选择

**Comment by 88250** [comment]
设置 - 搜索 - 类型过滤那里可以调整。

**Comment by Kitsuta-le** [comment]
> 设置 - 搜索 - 类型过滤那里可以调整。

我想的是 设置中的类型过滤会关联到((的引用搜索，而通过调整搜索框的类型过滤可以实现两个搜索独立
