### ISSUE TITLE
大纲支持取消显示 H1,H2 等标题层级信息

### ISSUE THREAD

**Issue by chiuchiuuu** [siyuan-note/siyuan#3871]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
任何时候

阅读大纲时

### 描述可能的最优解决方案 Describe the optimal solution

支持取消显示 H1,H2 等标题层级信息，在设置中提供选项，或者直接取消

### 其他信息 Other information

文档比较长，大纲内容比较多的时候，H1,H2 这些非常干扰阅读，本身大纲就已经通过缩进表达了标题层级信息，再加上这个 H1,H2 非常多余。

![image](https://user-images.githubusercontent.com/30572942/150097900-d6b0678e-d4a2-402b-ab4e-4762473e437c.png)

**Comment by 88250** [comment]
块标不只有视觉效果，还有功能的，鼠标悬浮可以弹出编辑器浮窗。如果实在不需要，可以考虑通过自定义主题去掉显示。

**Comment by chiuchiuuu** [comment]
> 块标不只有视觉效果，还有功能的，鼠标悬浮可以弹出编辑器浮窗。如果实在不需要，可以考虑通过自定义主题去掉显示。

和鼠标悬浮可以弹出编辑器浮窗不矛盾吧？核心在于这个东西影响了大纲的可读性，大纲最首要的功能是清晰的展示内容结构和跳转，基本我用过的笔记软件 typora，obsidian, notion, wolai，包括各种各样的 wiki 的标题样式都很直观。

如果只是想要支持鼠标悬浮可以弹出编辑器浮窗这个功能，大可以把 H1H2 换成小圆点，或者把颜色样式改弱一点（比如size减小，颜色浅灰色）和标题文字有一定的区分度。

其次鼠标指针指到标题上就弹出这个功能也并不一定要通过这种方式实现，可以直接指针指到标题上就悬浮，或者 ctrl+鼠标悬浮弹出，方式有很多

如果我有能力通过自定义主题去掉的话也就不会上来提 issue 了，或许可以考虑一下在设置里增加一个开关可以控制这个 H1H2 的显示？

**Comment by 88250** [comment]
有这个块标可读性不是应该更好么？

**Comment by choyy** [comment]
希望不要取消，如果要改就增加设置控制吧

**Comment by chiuchiuuu** [comment]
> 有这个块标可读性不是应该更好么？

我也不知道咋解释，思源大纲我第一眼看过去就是 H1,H2这些无用的信息 ，原本的序号都变得不直观了。我贴一些图对比一下吧

siyuan

![image](https://user-images.githubusercontent.com/30572942/150140766-bcc8af37-a0c1-4220-b2c3-aadd96ca13b4.png)

obsidian

![image](https://user-images.githubusercontent.com/30572942/150140802-597aea30-b343-44a0-a35c-2943f3b21351.png)

typora

![image](https://user-images.githubusercontent.com/30572942/150141313-9927007f-cb4f-4d3c-ab4d-2f87eda6baa0.png)

notion

![image](https://user-images.githubusercontent.com/30572942/150141380-18a3c6fa-959c-4922-b849-60ad352d75b8.png)

**Comment by 88250** [comment]
下个版本会调小一些：

![image](https://user-images.githubusercontent.com/873584/150142477-d8515a91-1f32-4d08-8808-e9a8b550c92d.png)

**Comment by mozhux** [comment]
确实对于标题有序号的大纲来说，前面有H1这样的标识会更影响阅读，还是鼠标直接标题悬浮好点

**Comment by guidongyuan** [comment]
> 原本的序号

可能是你的文档，已经有序号了，所以才会觉得H1 、H2多余。
对应我这种基本不会自己写序号的，觉得有这个挺好的。

**Comment by chiuchiuuu** [comment]
> > 原本的序号
> 
> 可能是你的文档，已经有序号了，所以才会觉得H1 、H2多余。 对应我这种基本不会自己写序号的，觉得有这个挺好的。

没有序号确实相对没那么影响阅读，一般笔记其实我也不加序号，只有结构性比较强的或者篇幅比较长的笔记我会加序号加强每块内容的顺序关系。

我觉得 H1H2 这个信息挺多余的，大纲的层级结构基本通过缩进表达清楚了。感觉一般看大纲不会去关注这个标题是一级标题还是二级标题，而是更多关注这个标题是第几节，是在哪个标题之下等等

不过每个人的意见都不一样，所以我是觉得加个设置可以隐藏或者显示，就可以兼顾两者的需求了。类似一些笔记软件支持自动给标题添加序号 1. 1.1 这样的

**Comment by Zuoqiu-Yingyi** [comment]
@chiuchiuuu 
可以使用自定义 CSS 片段隐藏该标志

```css
.b3-list-item__graphic {
    width: 4px;
    color: transparent;
}
```

**Comment by Chorer** [comment]
> > > 原本的序号
> > 
> > 
> > 可能是你的文档，已经有序号了，所以才会觉得H1 、H2多余。 对应我这种基本不会自己写序号的，觉得有这个挺好的。
> 
> 没有序号确实相对没那么影响阅读，一般笔记其实我也不加序号，只有结构性比较强的或者篇幅比较长的笔记我会加序号加强每块内容的顺序关系。
> 
> 我觉得 H1H2 这个信息挺多余的，大纲的层级结构基本通过缩进表达清楚了。感觉一般看大纲不会去关注这个标题是一级标题还是二级标题，而是更多关注这个标题是第几节，是在哪个标题之下等等
> 
> 不过每个人的意见都不一样，所以我是觉得加个设置可以隐藏或者显示，就可以兼顾两者的需求了。类似一些笔记软件支持自动给标题添加序号 1. 1.1 这样的

完全同意你的看法，这个标题显示我也觉得影响了可读性，悬浮窗完全可以通过其它方式解决。目前我是改了css，将标题图标改成了圆点。
