### ISSUE TITLE
文档编辑器 `...` 菜单中新增 `中西文间插入空格` 格式化功能

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3873]
暂时无法支持撤销。

**Comment by Zuoqiu-Yingyi** [comment]
要不要仅格式化选中的块，避免长文档格式化时的卡顿❓

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 长文档一个一个手动格式化怕是太累了……

**Comment by Zuoqiu-Yingyi** [comment]
@88250 哦哦哦, 我还以为 Ctrl+A 能选中还未动态加载出来的块😂

**Comment by kuusei** [comment]
可以选中时只格式化选中部分, 未选中时格式化文档么.

**Comment by 88250** [comment]
@kuusei 这个暂时不考虑吧，先做全文档格式化。

**Comment by Shad0wpf** [comment]
还是不如输入时自动插入空格好用

**Comment by jearton** [comment]
我的...菜单里，还是没有你说的这个功能。已经更新到1.8了，Mac客户端。

![image](https://user-images.githubusercontent.com/10370433/154809766-53dd8a74-ed55-47c9-ad99-bcfddee58e00.png)

**Comment by Zuoqiu-Yingyi** [comment]
@jearton 是文档右上方的 `...` 中
