### ISSUE TITLE
搜索界面支持链接搜索

### ISSUE THREAD

**Issue by xfdj** [siyuan-note/siyuan#3879]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

当前搜索功能仅支持搜索到链接的锚文本（也就是显示在文档中的文字内容），日后希望可以支持对链接内容的搜索。
![image](https://user-images.githubusercontent.com/38575841/150271875-133d6379-81e0-44dc-9c8a-b740d3fa1199.png)
![image](https://user-images.githubusercontent.com/38575841/150272102-d301ffa5-069d-4b83-ad8f-a718fb7193ef.png)
事情的起因是想通过链接搜索一下笔记中引用的论文。

**Comment by 88250** [comment]
可通过设置标题字段达成。
