### ISSUE TITLE
我尝试将思源笔记做成便携版本，然而不成功

### ISSUE THREAD

**Issue by woaidianqian** [siyuan-note/siyuan#3884]
我在思源笔记的根目录下面创建data希望制作成便携版，但是发现不行，他会默认在document下面创建data相关文件夹，能够考虑将思源笔记弄成便携版本的。就像vscode一样，在根目录创建data文件夹之后，就会自动变成便携版本。

**Comment by 88250** [comment]
设置 - 关于里面可以切换工作空间路径。

**Comment by woaidianqian** [comment]
但是没有设置相对路径，假如我换了一台电脑，我还要复制文件夹，然后指定绝对路径，可不可以设置相对路径呢，我发现只能设置绝对路径

**Comment by woaidianqian** [comment]
但是没有设置相对路径，假如我换了一台电脑，我还要复制文件夹，然后指定绝对路径，可不可以设置相对路径呢，我发现只能设置绝对路径

**Comment by woaidianqian** [comment]
> 设置 - 关于里面可以切换工作空间路径。

但是没有设置相对路径，假如我换了一台电脑，我还要复制文件夹，然后指定绝对路径，可不可以设置相对路径呢，我发现只能设置绝对路径
