### ISSUE TITLE
代码块后用中文输入法格式会乱

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#3885]
https://user-images.githubusercontent.com/97490782/150506432-a093df6a-6bea-42a6-86c3-620792bcbe96.mp4

这太影响体验了，日常用得最多的就是代码块

**Comment by 88250** [comment]
代码块的问题近期不修复了，后续请关注 https://github.com/siyuan-note/siyuan/issues/3141

**Comment by 88250** [comment]
抱歉，这个问题是新引入的，会在下个版本修复。

**Comment by zhuzixian** [comment]
> 试下其他输入法，我这里在 Win11 的微软拼音下重现不了问题。

Win10的微软输入法下100%重现，重现的条件和步骤如下：
1. 插入代码块，代码块里有内容（代码块为空的情况下不会出现）
2. 在代码下后面的块的开头使用中文输入法
3. 光标跳回至代码块

![动画](https://user-images.githubusercontent.com/2361234/150625454-987bfb6e-8c4f-4709-a87c-d454ac2f9fda.gif)

**Comment by JokeenZhang** [comment]
我这里也会出现一样的情况，如果撤销莫名输入到代码块的字符时，会崩溃，在崩溃前会看到连代码块都会消失，明明我撤销的只是错误位置的字符。。。
这里是最新版，mac 11.6，使用搜狗输入法，苹果自带中文输入法也会这样，英文输入法正常

**Comment by JokeenZhang** [comment]
![image](https://user-images.githubusercontent.com/33319484/150628873-e28aea56-1331-4098-9b7f-960e93eefc33.png)

如图所示，本来「循环链表」那里是个二级标题，上方有一行空行，在那里输入箭头，然后这个箭头会跳到更上面的代码块，空行也会被「循环链表」这个二级标题块覆盖，但是还能看到有普通文本块光标闪烁，很神奇的现象。

**Comment by gslnzfq** [comment]
macOS 1.7.6 也发现了代码块相关的问题，但是会出现创建索引的错误提示，反复操作必现，详细看下视频文件，输入法是mac自带输入法
系统版本：macOS 12.1
思源版本：1.7.6

详细操作步骤：
1. 在代码块下面输入文本、修改为标题
2. 修改文本的内容，内容会跑到代码块中
3. 使用ctrl+z还原，系统就会提示重建索引，必现

备注：我使用过OneDrive同步，但是关闭同步仍然会出现错误

https://user-images.githubusercontent.com/12946062/150642734-1e1ba25b-ed52-4c1c-b1e0-cf0f86e6de09.mp4

**Comment by 88250** [comment]
@gslnzfq 下个版本修复，发布后请帮忙留意回测，谢谢。
