### ISSUE TITLE
图片批量操作（如base64 转 云端批量上传）

### ISSUE THREAD

**Issue by RichardStark** [siyuan-note/siyuan#3896]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

从其他平台如石墨迁移文档时

### 描述可能的最优解决方案 Describe the optimal solution

Typora 提供图片批量上传的功能

**Comment by 88250** [comment]
思源仅支持通过 Markdown 文件导入，其他格式的话可以考虑试试浏览器剪藏扩展 https://github.com/siyuan-note/siyuan-chrome
