### ISSUE TITLE
Base64 图片不能自动渲染，把( 删除再键入，就渲染出来了

### ISSUE THREAD

**Issue by RichardStark** [siyuan-note/siyuan#3897]
### 描述问题 Describe the problem

从石墨迁移到SY
### 期待的结果 Expected result
图片正常展示

### 截屏或者录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/49977764/150628852-bb94f130-e14d-4eb4-8675-b67458e28dbd.png)

删除括号再添加后
![image](https://user-images.githubusercontent.com/49977764/150628867-fa1b616a-2521-4df0-8a00-21bd1a12b0c0.png)

### 版本环境 Version environment

* Version: 1.7.6 仍未修复
* Operating system:  MacOS
* Browser (if used):

**Comment by 88250** [comment]
思源不支持 `![foo](data:image)` 语法解析。 https://github.com/siyuan-note/siyuan/issues/2750
