### ISSUE TITLE
支持表格可视化编辑

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#39]
> 插入表格，目前只看到三行三列的样式，不清楚如何增减行列数

目前是通过快捷键操作表格，应该支持可视化编辑，类似 Typora 那样。

**Comment by HaujetZhao** [comment]
![-6720672a5d9ce130](https://user-images.githubusercontent.com/19181833/99162985-d500ff00-273e-11eb-87ce-e3cff207d953.jpg)

![3a0bef844b588929](https://user-images.githubusercontent.com/19181833/99162989-d9c5b300-273e-11eb-812d-63d2b76c625f.jpg)

建议抄下 zettlr 的设计，通过这种在对应位置的半透明的按钮实现表格增删减。
