### ISSUE TITLE
搜索界面支持类型过滤

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#390]
0.3.9

**当前功能**
- 搜索是经常使用的功能，当前“Ctrl+P”搜索界面，不支持按类型过滤，搜索效率有待提高

**期望的改进**
- 比如我只需要搜索文件名，可以提供文件名过滤选项
- 比如我只需要搜索标题和待办事项，通过过滤类型筛选，就可以过滤掉其他无用信息

**Comment by 88250** [comment]
已经支持按类型前缀过滤 https://github.com/siyuan-note/siyuan/issues/342 

v0.4.1 中稍作改进，谢谢反馈。
