### ISSUE TITLE
1.7.6版本 无序列表加粗后，加粗文字会跳到下一行

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3903]
![Jan-23-2022 00-10-18](https://user-images.githubusercontent.com/33319484/150646555-a1200a18-213e-4d8b-8b4b-9b5b8235a68f.gif)

如图所示，在出现错误结果后，也无法撤销删除，只能重新编辑

**Comment by JokeenZhang** [comment]
撤销可能导致状态异常

**Comment by 88250** [comment]
这个应该和 https://github.com/siyuan-note/siyuan/issues/3891 是同一个问题，等 v1.7.7 发布以后再帮忙看下能否重现。

**Comment by JokeenZhang** [comment]
这种错误不仅出现加粗操作，在其他位置复制引用后，选中指定文字黏贴，也会出现一样的问题。。

**Comment by 88250** [comment]
嗯，应该也一并修复了。
