### ISSUE TITLE
1.7.6 无序列表中，文字选中后无法正确复制黏贴

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#3904]
操作步骤如图所示：

![Jan-23-2022 00-18-50](https://user-images.githubusercontent.com/33319484/150646883-244497fe-0a88-4f1e-aa8b-190632f52fe8.gif)

在多次操作无法获取到正确结果后，关闭再打开思源，有一定几率会在这个文档中的第一行开始出现以下文本：

![image](https://user-images.githubusercontent.com/33319484/150646832-dcf30938-f99b-4d46-87a4-80f520c4ccb6.png)

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3903
