### ISSUE TITLE
“在中英文间插入空格”功能对行内公式不生效

### ISSUE THREAD

**Issue by glatavento** [siyuan-note/siyuan#3905]
如题

![Peek 2022-01-23 10-08](https://user-images.githubusercontent.com/76601050/150661825-67030155-201c-4da0-a9ae-c3daf48e1acb.gif)

**Comment by Zuoqiu-Yingyi** [comment]
行内公式和行内代码按理说应该不能随便格式化吧❓

**Comment by glatavento** [comment]
> 行内公式和行内代码按理说应该不能随便格式化吧question

我可能没有表述清楚：行内公式和正常文字之间应当有空格，也就是 `文字$123$文字` 应当格式化为 `文字 $123$ 文字`
