### ISSUE TITLE
设置笔记的打开时的模式

### ISSUE THREAD

**Issue by grassvalley** [siyuan-note/siyuan#3906]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
打开笔记时

目前打开笔记时，默认时编辑模式，但许多时候仅仅时查看。虽然思源笔记是所见即所得，但这种情况下有可能会不小心修改了笔记内容。因为希望可以选择打开笔记时是预览模式。
### 描述可能的最优解决方案 Describe the optimal solution
可以在笔记本的属性里来设置这个默认打开模式。并且能指定预览的展示方式，比如 桌面、平板、或者手机模式。

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/2648
