### ISSUE TITLE
希望增加的功能：反向链接，可以增加根节点和上级节点的显示

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#391]
反向链接，是否可以考虑增加根节点和上级节点的显示。不仅仅只有被链接的当前节点或block。单独的一个链接节点，没有上下文内容的话，有时不能完整显示出构成链接的语境

**Comment by 88250** [comment]
感谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/295
