### ISSUE TITLE
使用```在未输入代码语言类型时直接回车，会变成自定义代码类型。

### ISSUE THREAD

**Issue by IlO0OlI** [siyuan-note/siyuan#3911]
### 描述问题 Describe the problem
使用```在未输入代码语言类型时直接回车，会变成自定义代码类型。而且右侧的代码类型需要用鼠标移上去才能看到。

### 期待的结果 Expected result
如果```紧跟的内容不是语言类型，语言类型置空，内容写到代码块内。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![bug](https://user-images.githubusercontent.com/41688190/150680563-356e43bb-1664-4838-b25a-37f342adf668.gif)
### 版本环境 Version environment

* Version: v1.7.7
* Operating system: win10
* Browser (if used):

**Comment by IlO0OlI** [comment]
另外新建代码块如果没有写代码类型，默认为上一次用的代码类型，应该为空

**Comment by 88250** [comment]
这两点是设计预期，感谢反馈。
