### ISSUE TITLE
”复制块超链接“将超链接显示为Markdown格式

### ISSUE THREAD

**Issue by hyjwonder** [siyuan-note/siyuan#3915]
1、在思源中，右键点击任何块，可使用“复制块超链接”选项自动生成类似于“siyuan://blocks/20210104090624-wx18pvo”之类的超链接，用于在其他app中打开这个超链接。
2、目前这个超链接在其他Markdown编辑器（如obsidian）中，不能直接点击跳回思源，必须改成类似”[复制文本](siyuan://blocks/20210104090624-wx18pvo)"格式，才能顺利跳转回思源。
3、为解决上面的问题，可否增加类似“复制Markdown格式的块超链接”选项，生成的块超链接的格式为“[复制文本](siyuan://blocks/20210104090624-wx18pvo)"，这样可以一次性生成在Markdown中可用的超链接。其中，[复制文本]表示自动复制该块的全文。
以上，请D大考虑。谢谢！
![CleanShot 2022-01-24 at 09 36 59@2x](https://user-images.githubusercontent.com/77609410/150709617-9c45489a-7e01-4302-835a-2ac0a351cf73.png)

**Comment by 88250** [comment]
这应该是粘贴时的处理，在其他 Markdown 编辑器里应该是需要改为 `[foo](bar)` 这样的超链接格式才行。

**Comment by hyjwonder** [comment]
对的，请问粘贴时，思源能自动复制块原文“foo”，并将格式生成为 ’[foo](bar)‘ 吗？

**Comment by 88250** [comment]
粘贴时需要粘贴所在软件处理。

**Comment by hyjwonder** [comment]
好吧。
