### ISSUE TITLE
默认限制创建文档层级最大深度为 7 层

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3919]
路径名过长的话使用操作系统文件管理器会遇到问题，比如无法复制文件。

**Comment by Zuoqiu-Yingyi** [comment]
计划限制到多少个字符长度呀❓

**Comment by 88250** [comment]
还没确认，这个需要找找资料，你哪里有参考的吗？

**Comment by Zuoqiu-Yingyi** [comment]
@88250 建议不作限制, 因为有的系统版本真的好短😭

[命名文件、路径和命名空间 - Win32 apps | Microsoft Docs 最大路径长度限制](https://docs.microsoft.com/zh-cn/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#maximum-path-length-limitation)

[最大路径长度限制 - Win32 apps | Microsoft Docs](https://docs.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)

**Comment by Zuoqiu-Yingyi** [comment]
@88250 升级时对于现有的大于7层的目录怎么处理?
能不能手动解除该限制呢:broken_heart:
不要一刀切呜呜呜😭

**Comment by 88250** [comment]
对于现有数据没有影响，只是不能在 7 层以上的位置创建子文档了。

**Comment by Zuoqiu-Yingyi** [comment]
> 对于现有数据没有影响，只是不能在 7 层以上的位置创建子文档了。

那能不能设置一个默认关闭的开关呢?
或者可以使用技术手段绕开该限制💔
目前 windows 的路径长度仅受限于 NTFS 的 32k💔

**Comment by 88250** [comment]
设置 - 文档树里会加个 `允许创建深度大于 7 层的子文档` 的选项，默认关闭。

**Comment by Rao-Jupiter** [comment]
Windows 11 里面好像没有这个问题

**Comment by 88250** [comment]
@Rao-Jupiter 外部应用软件可能会碰到问题，比如直接复制文件夹的时候。
