### ISSUE TITLE
支持将文档渲染为幻灯片演示

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#392]
集成reveal.js的幻灯片功能

**Comment by 88250** [comment]
能描述一下设想的使用场景和具体用法吗？

**Comment by xulei-shl** [comment]
> 能描述一下设想的使用场景和具体用法吗？

我在思源里编辑了文档，然后内部小组讨论时，直接幻灯片演示给其他人看。obsidian那种“开始演示”的功能
![微信截图_20201102105043](https://user-images.githubusercontent.com/13896259/97825324-4d0c0580-1cf9-11eb-8b92-165693c26a54.png)

**Comment by 88250** [comment]
收到，我们看下如何实现，谢谢建议。
