### ISSUE TITLE
New functions in the text editing tab

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#3921]
Siyuan, in my case, is an amazing study tool with outliner mode. I love the tags, the developers bringing news and fixes almost daily. I can only thank the team for the effort.

I would like to suggest a new functionality to mark up texts. In Anki Software, this tool is called "cloze". It's a tool that I use a lot to memorize laws in my country, others no doubt use it for medicine and other areas.

Basically, you hide the words you want. When hovering the mouse cursor over them, the letter appears. Here's an example:

![siyu](https://user-images.githubusercontent.com/90691302/150801783-b14907e5-264c-44c8-83d0-ffe3ab36e95f.gif)

I used the "mark" tool to create this example. 

Here's the code I got from a theme developer for the program. (I would like to leave this default option in the program)

```
:root {
	    /* Marks */
    --b3-protyle-inline-mark-background: #b38d1d;
    --b3-protyle-inline-mark-color: #ffffff;
}

mark {
    background-color: var(--b3-protyle-inline-mark-background);
    color: var(--b3-protyle-inline-mark-color);
}
.protyle-wysiwyg mark{
    color: transparent;
    transition: color 2s ease-in-out;
}
.protyle-wysiwyg [data-node-id] [spellcheck="false"] mark:hover{
    color: var(--b3-protyle-inline-mark-color);
    transition: color 0.2s ease-in-out;
}
```

Finally, I ask again for the option of a new icon to expand and collapse the topics in outliner mode. In my case, that's all that's missing to make the program perfect for my use.

**Comment by 88250** [comment]
Hello, we have considered the span element of "knock out and fill in the blank" before, but it is not very suitable for introduction at present, we need to wait for https://github.com/siyuan-note/siyuan/issues/2911 to be completed before considering it, thank you for the proposal.

Also, the list folding triangle arrow has to wait a bit longer, thanks for the reminder.
