### ISSUE TITLE
最左侧打开的页签样式问题

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3922]
如下图，打开的页签最左侧的左上角不是圆角，这是特意的吗。个人感觉还是统一圆角好看。

![image](https://user-images.githubusercontent.com/15650275/150893372-3f14f39a-b25b-401a-89ea-07bed8f670f2.png)

**Comment by Vanessa219** [comment]
选中后才是圆角
![image](https://user-images.githubusercontent.com/970828/150903455-4c854ecb-1298-4987-bc59-4b658f13c457.png)
