### ISSUE TITLE
开发者工具中Ctrl+R刷新刚钉住的页签会取消钉住

### ISSUE THREAD

**Issue by bestv5** [siyuan-note/siyuan#3923]
步骤
1.打开开发者工具
2.钉住一个页签
3.按ctrl+r刷新页面
4.钉住的页签被取消钉住了。

https://user-images.githubusercontent.com/15650275/150894291-b21be5db-04c7-4045-ab03-9a7c4313b2fe.mov

**Comment by Vanessa219** [comment]
ctrl+r 不会进行保存。只有在关闭/切换应用时才会。
