### ISSUE TITLE
PDF 标注双链预览引用快 功能意见

### ISSUE THREAD

**Issue by Zhayhp** [siyuan-note/siyuan#3925]
PDF 功能点

## 标注双链

PDF 预览时可使用划选进行标注，标注可复制到文档中形成双向链接：

* 在 PDF 中鼠标悬浮标注可预览引用块

这个功能感觉以 ctrl+点击的方式展现。不然鼠标悬浮在相关文档时显示预览引用快，影响文章阅读。
![image.png](https://b3logfile.com/file/2022/01/image-590286d9.png)

**Comment by 88250** [comment]
悬浮预览是统一的设计。
