### ISSUE TITLE
切换主题的时候通过 theme.js 增加的元素不会被清除

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#3927]
切换主题的时候通过theme.js增加的元素不会被清除
设定暗主题是roundark的时候，亮主题为原始主题，不断切换主题时，用theme.js增加的元素不会被清除，会反复叠加，导致其他主题错误
![微信图片_20220125193523](https://user-images.githubusercontent.com/47842345/150969863-01810fc6-d33e-4386-928d-ff9d7b3b5b69.png)

**Comment by 88250** [comment]
界面不刷新的话添加的 DOM 元素以及其他状态（比如变量）是不会清除的，如果刷新界面的话似乎对用户不太友好。你认为应该如何处理呢？

**Comment by leolee9086** [comment]
检查当前主题是否带有theme.js  提示当前主题在切换时会需要刷新界面?  用户有预期的话应该会好一些.

**Comment by 88250** [comment]
@leolee9086 目前看来似乎只有这个方案比较妥当 👍
