### ISSUE TITLE
 show full name of pinned docs

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#3937]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

I suggest to show full name of pinned docs

![image](https://user-images.githubusercontent.com/33789516/151229479-6bca53ad-5096-40ce-aec2-4e980643aeca.png)

**Comment by 88250** [comment]
To save some space, only the first character is displayed, the mouse hovers to view the full name.
