### ISSUE TITLE
一些PDF文档显示不正确。

### ISSUE THREAD

**Issue by hyrio** [siyuan-note/siyuan#3938]
### 描述问题 Describe the problem

PDF通过chrome或者其他PDF查看工具浏览是正常的，但是导入思源中显示有问题。群里说是PDF没有背景是透明的，所以会这样。

### 期待的结果 Expected result
给每个出问题的PDF加白色背景太麻烦了，希望能显示的跟浏览器一样，不用改背景就是正确的。

### 截屏或者录屏演示 Screenshot or screen recording presentation
思源渲染的，黑色默认主题：
![image](https://user-images.githubusercontent.com/12430118/151333807-537029d5-5bd2-4183-a8e5-4a77229d627a.png)
思源渲染的，白色默认主题，正常的：
![image](https://user-images.githubusercontent.com/12430118/151336589-2095bf85-a2a1-440a-bc85-f1898f963c60.png)
CHROME渲染的，正常的：
![image](https://user-images.githubusercontent.com/12430118/151334076-3f3ecde6-88ad-4861-a41a-55527fb8eaa2.png)

### 版本环境 Version environment

* Version: v1.7.8
* Operating system: 
* Browser (if used): 

### 日志文件 Log File

PDF附件不能提交，这边附上PDF下载地址。
https://sites.cs.ucsb.edu/~lingqi/teaching/resources/GAMES101_Lecture_01.pdf

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3583

这个问题目前无法处理，只能以后再看了，感谢反馈。
