### ISSUE TITLE
自定义表情 emojis 增强

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#3939]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

有的表情有 `*.png` 与 `*.gif` 两种格式, 分别对应静态表情与动态表情, 但是发现使用标识符 `:一级目录/图片文件名:` 无法区分同一级目录下的名称相同但扩展名不同的图片, 之后又新建了一层目录将这两类目录区分, 发现 `:一级目录/gif/图片文件名:` 无法被解析

### 描述可能的最优解决方案 Describe the optimal solution

emojis 索引支持多级目录

### 描述候选的解决方案 Describe the candidate solution

emojis 索引支持文件扩展名

### 其他信息 Other information

改进优先级不高, 插个眼👀

**Comment by 88250** [comment]
这个暂时不考虑改进，感谢反馈。
