### ISSUE TITLE
代码中包含 ``` 后复制的问题

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#3941]
## 问题
在vscode中匹配markdown代码块的正则复制到思源，再粘贴到vscode中就无法匹配了，貌似是?和(出了问题
```
(```).*([\s\S]*?```\n)
```
![image](https://user-images.githubusercontent.com/60436214/151395797-d8e36307-11e5-4f6f-96ea-4033531e70c6.png)
复制到思源代码块再粘贴就不行了
![image](https://user-images.githubusercontent.com/60436214/151395922-832f1e42-085b-4e38-a12b-e069fc85e989.png)

### 版本环境 Version environment

* Version:  v1.7.8
* Operating system: win10

**Comment by 88250** [comment]
试下复制到文本编辑器里看表达式的字符是否完全一致。

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/151398455-cf858832-fc9d-4168-a01f-5a9ec5e4f81a.png)
(和？被特殊标注，显示U+200d不可见
![image](https://user-images.githubusercontent.com/60436214/151398591-baa4d4e4-ebd3-41bb-8f92-83f1ec6d960a.png)

**Comment by Achuan-2** [comment]
应该是表达式中有```造成的
