### ISSUE TITLE
Linux 下集市动画问题

### ISSUE THREAD

**Issue by glatavento** [siyuan-note/siyuan#3943]
### 描述问题 Describe the problem

Linux 版本思源笔记中，鼠标经过某个包时（有时）会产生文字重影

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Peek 2022-01-28 14-37](https://user-images.githubusercontent.com/76601050/151499804-7bc94811-7874-46bd-8621-1823502b63ee.gif)

### 版本环境 Version environment

* Version: v1.7.9
* Operating system: Linux

**Comment by choyy** [comment]
我这里只会闪烁一下,kde plasma

**Comment by 88250** [comment]
先关闭了，请使用默认主题看看，可能是主题的问题。
