### ISSUE TITLE
可不可以支持自定义的js 而不是只在主题中使用js

### ISSUE THREAD

**Issue by Rioad233** [siyuan-note/siyuan#3944]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
例如我想写一些自定义的js，然后不管使用哪些主题都可以加载。 我现在是通过主题的theme.js来加载自定义的js，但这个有一个弊端，就是我一但切换或者更新了主题，就需要重新将这个加载js的代码重新写一次。可能这个东西更类似插件之类的东西吧
<!--

### 描述可能的最优解决方案 Describe the optimal solution
![image](https://user-images.githubusercontent.com/52393675/151500286-42ae75a2-033f-44f9-926b-b5646fc7e390.png)

**Comment by Rioad233** [comment]
图片怎么没了..
![image](https://user-images.githubusercontent.com/52393675/151500579-e56c615f-8272-4bbf-b95b-bc349cbe82f9.png)

**Comment by 88250** [comment]
暂时不考虑，感谢反馈。
