### ISSUE TITLE
IOS版无法修改网址？

### ISSUE THREAD

**Issue by bobo0810** [siyuan-note/siyuan#3947]
### 描述问题 Describe the problem
ios版调不出键盘，无法修改网址。

### 期待的结果 Expected result
自由修改网址，而非默认127.0.0.1

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/26057879/151528395-141758e9-d4a7-4474-a4d2-ec6421cdc6bd.png)

### 版本环境 Version environment

* Version: V1.7.8
* Operating system: IOS
* Browser (if used):

**Comment by 88250** [comment]
你好，这里不支持配置。

开启伺服功能以后会自动监听所有网卡，这样就可以用 IP:6806 在处于统一局域网的其他设备上访问。

**Comment by bobo0810** [comment]
> 开启伺服功能以后会自动监听所有网卡，这样就可以用 IP:6806 在处于统一局域网的其他设备上访问。

感谢回复。还有两个问题：
（1）假如在户外，就无法访问内网笔记了。
（2）以后也不会支持编辑网址。

**Comment by 88250** [comment]
内网笔记指的是？

**Comment by bobo0810** [comment]
> 内网笔记指的是？

假如我在外面，就无法访问局域网内的笔记了。

**Comment by 88250** [comment]
网络不通的话不行。
