### ISSUE TITLE
使用 URL 参数跳转到 Web 端的指定块

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#3949]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

最近使用 API 实现了云收集箱功能, 但是在查看过程中出现了问题: 无法在收集箱中插入一个内容块后使用 URL 从浏览器外部跳转到 Web 端的该内容块

### 描述可能的最优解决方案 Describe the optimal solution

添加 URL 参数 `id=<内容块 ID>`, 再 Web 端加载后跳转到指定的内容块

### 其他信息 Other information

在群友的帮助下目前使用 [siyuan-theme-dark-plus/script/utils/misc.js](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/blob/c8904465369ebe73c17e519250da4b47e8ba4406/script/utils/misc.js#L87-L160)  方案, 但是该方案无法在未打开任何文档页签时使用

**Comment by winter60** [comment]
我发现另一个场景好像也需要这个，比如将这个网页作为作为iframe嵌入另一个应用，这时就需要指定页面，需要用到块id。
刚看到b站的一个视频，https://www.bilibili.com/video/BV1PZ4y1t7NW?p=1，联想到thebrain和思源结合，嵌入网页比本地uri跳转更适合，可以一目了然。不过thebrain还不太熟练还在学习中。

**Comment by 88250** [comment]
这个我们暂时不考虑了，欢迎 PR 贡献代码。
