### ISSUE TITLE
关于调整字体大小的问题

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#395]
您好，我想调整编辑器的字体大小，但是在theme.css和custom.css文件中都没有看到控制字体大小的内容，请问该如何操作？

**Comment by Vanessa219** [comment]
试一下这个
```
.vditor-reset {
    font-size: 18px
}
```

**Comment by 2016201256** [comment]
> 试一下这个
> 
> ```
> .vditor-reset {
>     font-size: 18px
> }
> ```

It works. 感谢！
