### ISSUE TITLE
键入 SQL 查询后焦点没有自动跳转到 SQL 编辑框内

### ISSUE THREAD

**Issue by MilkBlock** [siyuan-note/siyuan#3956]
### 描述问题 Describe the problem

键入SQL查询后焦点没有自动跳转到SQL编辑框内

### 期待的结果 Expected result
键入{{}}后焦点自动跳转到sql编辑框内

### 截屏或者录屏演示 Screenshot or screen recording presentation
![bug](https://user-images.githubusercontent.com/47934647/151656962-b08fa94d-fbed-4a86-8247-608b9454b1ad.gif)

### 版本环境 Version environment

* Version: 1.7.9
* Operating system:  win 11
* Browser (if used):

**Comment by 88250** [comment]
我这里重现不了问题，麻烦切换到默认主题后再试试。

![issue](https://user-images.githubusercontent.com/873584/151685786-27d86faf-a8ec-48e1-bfd8-e6cd63cd38ba.gif)

**Comment by MilkBlock** [comment]
已切换为默认主题，依然出现了该问题我注意到了另外的细节
1.出现了'暂无相关内容'
2.焦点自动移到了第一行







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月30日(星期天) 中午11:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 键入 SQL 查询后焦点没有自动跳转到 SQL 编辑框内 (Issue #3956)





 
我这里重现不了问题，麻烦切换到默认主题后再试试。
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MilkBlock** [comment]
似乎是与 嵌入块 冲突


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月30日(星期天) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 键入 SQL 查询后焦点没有自动跳转到 SQL 编辑框内 (Issue #3956)





 
我这里重现不了问题，麻烦切换到默认主题后再试试。
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MilkBlock** [comment]
我在另一台电脑上又进行了尝试
如果先打开自带的 ”帮助“（笔记本） 使得存在可嵌入的块
那么 先行输入 {{  就会出现选择框，若忽略选择框继续输入 }}则焦点会移动到不期望的位置

**Comment by 88250** [comment]
感谢帮忙捉虫，已经可以重现问题。
