### ISSUE TITLE
将文档中的网络图片转换为本地资源文件

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#3959]
编辑器 `...` 菜单中提供该特性，点击后通过内核下载文档中的所有网络图片（`https://` 开头），然后将图片链接地址由网络地址替换为本地资源文件地址（`assets/` 开头）。

**Comment by Nyyyb** [comment]
发现一个小bug，转换的文件可能会失去.png后缀，这时候.asset里面存放的是没有后缀的文件，还会导致产生未引用资源，手动在.asset文件夹和图片地址加上.png就正常了

**Comment by 88250** [comment]
@Nyyyb https://github.com/siyuan-note/siyuan/issues/3972

**Comment by aantior** [comment]
如何批量转换为本地图片 ？
