### ISSUE TITLE
表格快捷键 Ctrl Shift + 失效

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#396]
0.4版本反馈一个bug：
表格 增减行 ctrl = ctrl -，删除列ctrl shift -都正常
增加列ctrl shift +没有反应

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/97831551-5736ff80-1d0b-11eb-8860-5ef082d4f4d4.png)

@Vanessa219 这几个也没有作用。
