### ISSUE TITLE
通过特定字符串+触发键的形式 ，提高打开特定模板的速度

### ISSUE THREAD

**Issue by MilkBlock** [siyuan-note/siyuan#3960]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
提高打开特定模板的速度
由于做笔记的常用模板通常少且集中

### 描述可能的最优解决方案 Describe the optimal solution
空格 +特定字符串 + 触发键（例如 Tab）直接映射到特定模板
而非 ‘/模板Enter搜索模板名Enter’ 这个操作略显‘重’
这里用Vim的Ultisnippet插件演示
![featuregif](https://user-images.githubusercontent.com/47934647/151690501-d099c776-bca1-447f-84d9-703083d9f069.gif)

不期望支持正则表达式
期望在go的模板中可以设置字符串

**Comment by 88250** [comment]
这个应该不会内置，可考虑使用外部工具（比如 Quicker）来实现。

> 不期望支持正则表达式
期望在go的模板中可以设置字符串

这个没看明白，麻烦再补充一下描述。

**Comment by MilkBlock** [comment]
抱歉是我表述有问题，指的是希望能在模板中设置这个特殊字符串
之前没有了解Quicker能解决这类问题，是我孤陋寡闻了

**Comment by 88250** [comment]
这倒没有，我只是感觉 Quicker 类似工具可以实现，但是没有实操经验 😂 

先关闭了，如果后续还需要讨论请随时跟帖，谢谢。
