### ISSUE TITLE
Web 端无法使用块超链接在页面内跳转

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#3961]
### 描述问题 Describe the problem

单击 Web 端内形如 `siyuan://blocks/20200812220555-lj3enxa` 块超链接会直接使用浏览器打开该链接, 浏览器将会使用 URL scheme 打开桌面应用(一般如下图所示), 因此在 Web 端完全无法使用超链接跳转块

![image](https://user-images.githubusercontent.com/49649786/151692312-9236eae4-b61a-4f51-a1fc-e7e067ba5679.png)

### 期待的结果 Expected result

首先从 Web 端中查询是否命中一个块, 如果命中则在页面内直接跳转, 如果没有命中再使用 URL scheme 唤起桌面端

### 版本环境 Version environment

* Version: 1.7.9
* Browser (if used): Firefox 96.0.3 (64 位)

**Comment by 88250** [comment]
这个不太确定是否能够拦截 URL 打开的请求，有空的话麻烦帮忙调研看看。

**Comment by Zuoqiu-Yingyi** [comment]
> 这个不太确定是否能够拦截 URL 打开的请求，有空的话麻烦帮忙调研看看。

@88250 覆写 `<a>` 标签的 onclick 方法应该可以？

**Comment by 88250** [comment]
DOM 最好不要改变，否则可能会引入其他问题。

**Comment by 88250** [comment]
即使能实现，但是如果要跳转 `siyuan://` 的话又得改变交互，所以暂时不考虑了。
