### ISSUE TITLE
查询嵌入块刷新问题

### ISSUE THREAD

**Issue by MilkBlock** [siyuan-note/siyuan#3967]
### 描述问题 Describe the problem
点击SQL刷新按钮未删除已有数据
![bug](https://user-images.githubusercontent.com/47934647/151755735-56c15a44-a9b2-48e1-bb8a-f941ceaee250.gif)

### 期待的结果 Expected result
除夕节快乐

### 版本环境 Version environment

* Version: 1.7.10
* Operating system: win11 
* Browser (if used):

**Comment by 88250** [comment]
感谢反馈，过两天排查。春节快乐 🎉

**Comment by 88250** [comment]
@Vanessa219 这个问题也在该 issue 中一并处理？ https://ld246.com/article/1643684897863
