### ISSUE TITLE
表格功能增强

### ISSUE THREAD

**Issue by SylleoYr** [siyuan-note/siyuan#3974]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

1. 目前插入表格默认3行3列，如需修改则需要多次点击插入行/列，多有不便，希望能够增加一个可视化或自定义行列数的插入方式
2. 表格默认样式拉伸至整行

### 描述可能的最优解决方案 Describe the optimal solution

1. 可视化表格插入不知道可不可以做成类似 Word 那样的，自定义行列数可以在这基础上增加两个输入框（或者可以像 `我来wolai` 那样新增一个指令：`/5*6`）
2. 在表格行列间增加类似 word 的动态插入行、列的按钮
3. 表格默认样式扩展至整行更加美观 🤣

**Comment by 88250** [comment]
目前的 Markdown 表格暂时不做改进，后续请关注 https://github.com/siyuan-note/siyuan/issues/3394

**Comment by SylleoYr** [comment]
> 目前的 Markdown 表格暂时不做改进，后续请关注 #3394

👌 

其实也可以将 md 表格渲染成 html <table>
