### ISSUE TITLE
iOS 端打开应用仅显示 images/

### ISSUE THREAD

**Issue by heddxh** [siyuan-note/siyuan#3976]
### 描述问题 Describe the problem

iOS端严重问题，点开应用仅显示`images/`字样，其他部分完全不可点击（空白）

### 截屏或者录屏演示 Screenshot or screen recording presentation

![IMG_20220202_200211_328.PNG](https://user-images.githubusercontent.com/63106571/152150032-588a2020-6c70-4fc8-99ac-594a7c37e181.PNG)

![IMG_20220202_200152_606.PNG](https://user-images.githubusercontent.com/63106571/152150042-8c572f41-0ef4-499e-ab8c-4c0f85680865.PNG)

### 版本环境 Version environment

* Version: App Store最新

* Operating system: iPadpro 10.5in iPad OS 15.2

**Comment by 88250** [comment]
请卸载后重新安装看看，这个问题应该已经修复。
