### ISSUE TITLE
虚拟引用问题

### ISSUE THREAD

**Issue by Csrayz** [siyuan-note/siyuan#3979]
### 描述问题 Describe the problem

两个问题：

1. 能否停止识别当前页面中对当前页面的虚拟应用， 可以看出整个页面都是“对象”的虚拟引用。
2. 两个面向对象的引用不一致，前者正确识别到而后者不能。

![Snipaste_2022-02-03_12-35-05](https://user-images.githubusercontent.com/33659823/152281771-8627d661-6ee6-479f-8304-96b4cbb7fdca.png)

### 期待的结果 Expected result

1. 在此页面中，“对象”没有虚拟应用下划线
2. 正确识别到”面向对象“

### 版本环境 Version environment

* Version: v1.7.10
* Operating system:  Win10 21H2
* Browser (if used):

**Comment by 88250** [comment]
* `对象` 和 `面向对象` 是根据搜索识别出来的不同关键字
* 不会排除在当前文档中搜索，这个之前有人提过

感谢反馈。

**Comment by Csrayz** [comment]
关于问题2，优先匹配长文本是否可行。
这样在文本：`重要区别是面向对象的语言`中，不会匹配为：面向`对象`，而匹配为：`面向对象`。

我认为这是一个合理的匹配方案，更长的文本一般具有更多的信息，指代的目标也更具体，所以应该匹配更长的文本。

**Comment by 88250** [comment]
@Csrayz 这个之前实现的时候好像考虑过，但我现在想不起来为啥是短词优先了 😂
