### ISSUE TITLE
Minor Editor Settings Description Error

### ISSUE THREAD

**Issue by ens100** [siyuan-note/siyuan#398]
In the Editor options there is a minor description error where where the description for Code Block Preview is the same as Math Block preview:

![image](https://user-images.githubusercontent.com/67863060/97864910-3ff31480-1d01-11eb-9856-675457b5bced.png)

Thanks

**Comment by 88250** [comment]
Thank you, we will fix it soon.

**Comment by ens100** [comment]
Thanks -  just a suggestion, maybe rather than "after opening,..". "After enabling..." or "Once enabled..." may be better.
hope this helps
