### ISSUE TITLE
从云端备份恢复data时报错

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#3982]
### 描述问题 Describe the problem
![image](https://user-images.githubusercontent.com/60436214/152353129-106b236e-aa55-4676-b22f-9af075892db0.png)

### 版本环境 Version environment

* Version: 1.7.11
* Operating system:  win10

**Comment by 88250** [comment]
看报错应该是因为文件被占用了（比如打开了资源管理器，或者刚好被其他进程访问）。

**Comment by 88250** [comment]
暂时无法重现，我关闭了，如果后续还能重现麻烦反馈，谢谢。

**Comment by Achuan-2** [comment]
好的，应该是打开了资源管理器
