### ISSUE TITLE
删除未引用的资源导致笔记图片消失

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#3983]
### 描述问题 Describe the problem

- 我点击删除未引用资源后，当提示已显示清理完成，可未引用资源还显示有部分图片，需要点击第二次才能全部清理干净
![image](https://user-images.githubusercontent.com/60436214/152354677-e40ffeac-6e30-426e-9c8d-f7eefdaf5605.png)

- 清理后发现部分笔记图片失效
![image](https://user-images.githubusercontent.com/60436214/152354567-7554d621-d2ec-42b5-a7cb-0ad9199b483b.png)

### 版本环境 Version environment

* Version: v1.7.11
* Operating system: win10

**Comment by Achuan-2** [comment]
备份还原后，我把笔记本下assets/assets子文件夹下的资源移动到笔记本asset/文件夹下就没事了

**Comment by Achuan-2** [comment]
不知道笔记本下assets/assets子文件夹是怎么出现的，六个笔记本，有两个笔记本都出现了这个文件夹，而该文件夹的资源文件在笔记中的引用只是assets/而不是assets/assets

**Comment by 88250** [comment]
请继续帮忙留意。

**Comment by 88250** [comment]
先关闭了，后续如果找到重现步骤麻烦反馈，感谢。
