### ISSUE TITLE
中英文混排时不会自动添加空格

### ISSUE THREAD

**Issue by NU-LL** [siyuan-note/siyuan#3986]
### 描述问题 Describe the problem

在中英文混排时不会自动添加空格，尝试过重启并更换为默认主题，均无效，在目前最新版本上测试

### 版本环境 Version environment

* Version: v1.7.11
* Operating system: Windows10 21H2
* Browser (if used):

**Comment by 88250** [comment]
这个功能已经改为手动点击菜单插入了。

![image](https://user-images.githubusercontent.com/873584/152476914-1ee0867f-b8a3-4de7-b06c-dda082e56a9f.png)

**Comment by NU-LL** [comment]
没注意这个菜单 感谢
