### ISSUE TITLE
不能拖拽md文件到思源笔记。

### ISSUE THREAD

**Issue by fanrongqitiancai** [siyuan-note/siyuan#3989]
1、打开思源软件
2、没有新建笔记本
3、把一个md文件拖拽到思源笔记界面
4、看得见出现 + 号
5、文件没有被打开
6、只能通过导入才能打开

能否添加拖拽打开md文件功能？能否不移动md文件的目录，在原始目录编辑保存？

**Comment by 88250** [comment]
请使用导入，在文档树右键。

**Comment by fanrongqitiancai** [comment]
导入太不方便了。
