### ISSUE TITLE
日记

### ISSUE THREAD

**Issue by ens100** [siyuan-note/siyuan#399]
This is more a feature request as opposed to an issue so hope you do not mind. 

It would be great if there was the possibility of having a button in SiYuan to create a "New daily note" based on today's date. Clicking the button would create a note with title (for eg. 2020-11-02). 

Hopefully this makes sense, if not I can upload a gif of Obsidian how has this feature.

Thanks in advance

**Comment by lss6378** [comment]
每日笔记是刚需呀，如果能原生支持就太好了^-^
![图片](https://user-images.githubusercontent.com/15924513/97871829-faaa0380-1d4f-11eb-8465-4000058b836c.png)

**Comment by yuhuai258852** [comment]
这个功能感觉还是有必要的，可以加个自定义开关；因为很多人（包括我自己）习惯了使用roamresearch、obsidian里的的这个功能，有一定的习惯依赖，而且dailynote的写东西时确实可以更加的心无旁骛，尽管写就是了，后期再统一整理，效率高好多

**Comment by hishistory** [comment]
同意，感觉有没有每日甚至能改变对一个软件的看法

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/431#issue-737427869

> 新建日记并不仅仅是题目是当天日期,日记页在关系图中,也应与普通页,块,标签,等有显示区别,可进行过滤显示。
> 
> 该功能有具体需求有两点:
> 
> 1. 新建日记时的标题可进行自定义设置 如 20201106或2020-11-06等
> 2. 日记页在关系图中与普通页有区别,可通过过滤器进行过滤显示,如不显示日记页,仅显示与日记页相关联引用,日记页中未引用普通页等供使用者在回顾个人知识体系时使用

**Comment by Tokubara** [comment]
但我觉得这本质上不就是模板么? 如果支持模板那更强了. 不过一般的模板, alfred这种就可以轻松生成, 也不需要软件来做.

**Comment by lss6378** [comment]
> 
> 
> 但我觉得这本质上不就是模板么? 如果支持模板那更强了. 不过一般的模板, alfred这种就可以轻松生成, 也不需要软件来做.

1. 使用多个软件实现一个功能，对用户来说不友好，学习成本高
2. **日记** 功能对笔记软件来说，是很常用的功能，原生支持肯定更香呀

**Comment by 88250** [comment]
需要在 设置 - 文件树中配置这几个参数：

![image](https://user-images.githubusercontent.com/873584/104084455-1535b700-5282-11eb-94fd-1bc4d7a1c551.png)

日记入口：

![image](https://user-images.githubusercontent.com/873584/104084459-21217900-5282-11eb-9850-58b2977811f3.png)
