### ISSUE TITLE
快速插入当前日期和时间

### ISSUE THREAD

**Issue by grassvalley** [siyuan-note/siyuan#3990]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
经常。
目前使用模板定义了几个日期和时间格式，按下 / 键，选择模板，再从模板里找到对应的日期和时间格式。
但总觉得这样操作还是繁琐，并且对于记事类应用，插入当前日期和时间是非常常用的功能，应该是默认提供的。
也许我没有找到吧

### 描述可能的最优解决方案 Describe the optimal solution
按下某个快捷键，比如 Ctrl-D ，可以选择几个常见的日期格式，选择后按下回车键，插入到当前位置。

**Comment by 88250** [comment]
你好，这个暂时不考虑了，因为一些输入法已经自带该功能。

**Comment by mlzxy** [comment]
@grassvalley 如果你在 OSX 上，实测这个方案可以 work  https://discussions.apple.com/thread/8651300  

需要把 Siyuan 加入 Privacy  → Accessibility 中
