### ISSUE TITLE
not working at Mac

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#4]
Version 0.1.6 mac version

1. rm -rf .siyuan
2. open Siyuan app
3. select **open local notebook**
4. editing markdown

<img width="1149" alt="Screen Shot 2020-09-10 at 10 52 25 PM" src="https://user-images.githubusercontent.com/15811943/92740471-bbe37700-f3b8-11ea-970a-8fb80c096074.png">

5. close all doc.
6. select **Connect to WebDav**
7. I can't remember the old password but it worked at liandi 1.1.3
8. Can not connect webdav.
9.  close Siyuan app
10. open Siyuan app
11. Toggle the Developer Tools,  I got the below errors

![vditor1](https://user-images.githubusercontent.com/15811943/92741574-b9cde800-f3b9-11ea-9721-d59e9c276937.gif)

**Comment by 88250** [comment]
After step 9 (close) please wait for 5s and then open to check this issue is gone.

**Comment by jakekwak** [comment]
Thanks,

Do I have to setup the websocket at server side?

<img width="1776" alt="Screen Shot 2020-09-11 at 6 25 11 AM" src="https://user-images.githubusercontent.com/15811943/92809553-b0637080-f3f7-11ea-829c-10941bfe7817.png">

**Comment by 88250** [comment]
The kernel process is booted by Electron process, please check port (6807) whether is bonded by other processes.

**Comment by 88250** [comment]
Checks ~/.siyuan/siyuan.log.

**Comment by jakekwak** [comment]
Here is the log.

I think test.md.json file is in the local.
```
I 2020/09/11 12:29:48 log.go:54: 运行模式 [prod]
D 2020/09/11 12:29:48 conf.go:65: 加载配置文件 [/Users/jakekwak/.siyuan/conf.json] 完毕
D 2020/09/11 12:29:48 conf.go:378: 开始导入笔记本 [http://127.0.0.1:6807/webdav/ye7z979/Downloads/] 下新的 Markdown 文件
I 2020/09/11 12:29:48 main.go:134: 内核进程 [v0.1.6] 正在启动 [/]，监听端口 [http://127.0.0.1:6806]
D 2020/09/11 12:29:48 conf.go:396: 导入笔记本 [http://127.0.0.1:6807/webdav/ye7z979/Downloads/] 下新的 Markdown 文件 [0] 完毕
D 2020/09/11 12:29:48 conf.go:398: 开始索引 [http://127.0.0.1:6807/webdav/ye7z979/Downloads/] 笔记本
D 2020/09/11 12:29:48 conf.go:416: 索引笔记本 [http://127.0.0.1:6807/webdav/ye7z979/Downloads/] 完毕
D 2020/09/11 12:29:48 conf.go:378: 开始导入笔记本 [http://74.208.27.41/webdav/] 下新的 Markdown 文件
D 2020/09/11 12:29:48 main.go:106: request [{"cmd":"getconf","reqId":1599794988541,"param":{}}]
E 2020/09/11 12:29:49 conf.go:319: Read notebook [http://74.208.27.41/webdav/] file [/test.md.json] failed: Write /test.md.json: 500
F 2020/09/11 12:29:49 conf.go:393: 生成笔记本 [http://74.208.27.41/webdav/] 下的文件 [/test] 的元数据失败：Read notebook [http://74.208.27.41/webdav/] file [/test.md.json] failed: Write /test.md.json: 500
```

conf.json
I think local is ok,  but when add the remote, something happen
```
   "boxes": [
      {
         "url": "http://127.0.0.1:6807/webdav/ye7z979/Downloads/",
         "auth": "",
         "user": "",
         "password": "",
         "path": "/Users/jakekwak/Downloads"
      },
      {
         "url": "http://74.208.27.41/webdav/",
         "auth": "basic",
         "user": "test1234",
         "password": "test1",
         "path": ""
      }
   ],
```

still error msg 
```
main.js:1 WebSocket connection to 'ws://127.0.0.1:6806/ws?id=14e9d4db-6d9c-475f-a8a1-59f413c53c8e' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connect @ main.js:1
(anonymous) @ main.js:1
main.js:1 WebSocket Error: Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
```

**Comment by 88250** [comment]
DON'T modify `boxes` configures manually, the `url` is always 127.0.0.1:6807, not the real WebDAV endpoint. SiYuan built-in a WebDAV server as the client of real WebDAV endpoint.

**Comment by jakekwak** [comment]
No, I didn't touch anything.

1. rm -rf .siyuan
2. open siyuan
3. connect local ok
4. connect webdav
5. I got the error msg.

If I miss something,  please let me know.

**Comment by 88250** [comment]
Checks ports 6806 and 6807 is whether listened by SiYuan.

**Comment by jakekwak** [comment]
no opened port.

I think it depends on the server's webdav configuration.

**Comment by 88250** [comment]
WebSocket connections used between UI and Kernel.

**Comment by jakekwak** [comment]
If there is a problem connecting to the WebDAV server, an error appears and the kernel processor seems to stop.
<img width="806" alt="Screen Shot 2020-09-11 at 2 07 23 PM" src="https://user-images.githubusercontent.com/15811943/92902628-62cd1f00-f45c-11ea-99d0-714cf9dddbfb.png">

**Comment by 88250** [comment]
Got it.
