### ISSUE TITLE
LaTeX 语法缺陷之equation环境和\label{}

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#40]
对于公式块中的内容，存在一些error渲染不出来的现象。

1. 不支持equation环境

```md
$$
\begin{equation}
\begin{aligned}
	I_n-I_{n+1}&=\frac{dQ_{n+1}}{dt}\\
	V_n-V_{n+1}&=\frac{d\Phi _{Jn}}{dt}
\end{aligned}
\end{equation}
$$
```

![image](https://user-images.githubusercontent.com/51868839/90198536-8c1a7100-de04-11ea-81bb-7301d835f172.png)

> 删除掉\begin{equation}和\end{equation}之后公式渲染成功，说明不支持的是equation环境

期待结果

![image](https://user-images.githubusercontent.com/51868839/90198712-11058a80-de05-11ea-84ed-1244aa7c87ac.png)

---
2. 公式块中的```\label{}```带来error，可能是由于不支持自动标号导致的

```
$$
\frac{\partial ^2\Phi}{\partial t^2}-\frac{\partial}{\partial x}\left[ v^2\left( x,t \right) \frac{\partial \Phi}{\partial x} \right] =0
\label{bodsfhig1}
$$
```

![image](https://user-images.githubusercontent.com/51868839/90198927-d2240480-de05-11ea-9b31-f85fddac34e2.png)

期待结果

- 正常渲染
![image](https://user-images.githubusercontent.com/51868839/90199040-1e6f4480-de06-11ea-9af9-6a03802b2518.png)
- 后续可以对该公式进行引用
![image](https://user-images.githubusercontent.com/51868839/90199083-4199f400-de06-11ea-83aa-7ee7eddfc30c.png)

### 其他信息
- 操作系统：win10

**Comment by 88250** [comment]
自动编号在 MathJax 引擎上支持 https://github.com/siyuan-note/siyuan/issues/1993

其他问题暂时忽略，关闭了。
