### ISSUE TITLE
剪藏简书网页时，遗漏了代码块部分

### ISSUE THREAD

**Issue by reinstallsys** [siyuan-note/siyuan#4002]
### 描述问题 Describe the problem

使用chrome剪藏插件收藏以下网页时，会遗漏代码块部分的内容

https://www.jianshu.com/p/8dfa51498343

### 期待的结果 Expected result

可以收藏所有网页内容

### 截屏或者录屏演示 Screenshot or screen recording presentation

原网页
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/5747138/152758524-d8a25186-5319-4d11-9ba9-d5ac9f9b4168.png">

收藏后的页面
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/5747138/152758877-8fbd72d4-685e-45ad-82b7-fa72dfb5ae10.png">

### 版本环境 Version environment

* SiYuan Version: 1.8.0 (1.8.0), Clipper Version: 0.3.7
* Operating system:  macOS 12.1
* Browser (if used): Chrome Version 98.0.4758.80 (Official Build) (arm64)

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8013883/siyuan.log)

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/3266

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/4361 中改进。
