### ISSUE TITLE
Android 端一加/OPPO 手机上部被遮挡问题

### ISSUE THREAD

**Issue by shizhiyun** [siyuan-note/siyuan#4008]
![Screenshot_20220208-184217_SiYuan](https://user-images.githubusercontent.com/70219915/152971377-6c0071d1-dad6-4549-a712-6da0081f3522.png)
如图，设备为一加9 pro，已知在color OS12和猫头鹰（类原生Android12）系统中都出现状态栏不适配的问题，且在最新的版本里仍未解决。

**Comment by 88250** [comment]
侧栏菜单能看全了吗？

**Comment by shizhiyun** [comment]
> 侧栏菜单能看全了吗？

![Screenshot_20220208-184551_SiYuan](https://user-images.githubusercontent.com/70219915/152971919-22dfe3ff-3c1c-449f-bfd6-1ea38096e795.png)
如图

**Comment by 88250** [comment]
那估计是暂时搞不好了……

Android 端已经开源，可能需要专门做 Android 开发的贡献者来帮忙解决了。

**Comment by shizhiyun** [comment]
> 那估计是暂时搞不好了……
> 
> Android 端已经开源，可能需要专门做 Android 开发的贡献者来帮忙解决了。

好的，非常感谢解答🌝

**Comment by HEILEIH** [comment]
一加8也出现不适配问
![{XS0MSUN0K{UD)R6UUTINI5](https://user-images.githubusercontent.com/32262422/153142135-c0b47e9e-5453-44a0-9e6c-e3dbb9014b74.png)
![(XFIQP(H`C @@@4Y7U{D5GI](https://user-images.githubusercontent.com/32262422/153142138-1b687909-8ccf-48d3-95e2-e8b7f88921de.png)
题

**Comment by Alive24** [comment]
> 一加8也出现不适配问题
> app界面：
> ![{XS0MSUN0K{UD)R6UUTINI5](https://user-images.githubusercontent.com/32262422/153142135-c0b47e9e-5453-44a0-9e6c-e3dbb9014b74.png)
> QQ打开 http://127.0.0.1:6806/appearance/boot/index.html 界面：
> ![(XFIQP(H`C @@@4Y7U{D5GI](https://user-images.githubusercontent.com/32262422/153142138-1b687909-8ccf-48d3-95e2-e8b7f88921de.png)
> 
> 这部分开源的代码好像无法进行修改

一加7 pro同样问题，完全无法使用

**Comment by 88250** [comment]
@Alive24 @HEILEIH 能帮忙看一下系统 WebView 的版本吗？

**Comment by Alive24** [comment]
97.0.4692.98

**Comment by Alive24** [comment]
> @Alive24 @HEILEIH 能帮忙看一下系统 WebView 的版本吗？

97.0.4692.98

**Comment by HEILEIH** [comment]
@88250 
87.0.4280.141

**Comment by Alive24** [comment]
> > @Alive24 @HEILEIH 能帮忙看一下系统 WebView 的版本吗？
> 
> 97.0.4692.98

再次更新到98.0.4758.87 问题依然存在

**Comment by whzecomjm** [comment]
> 你开高分辨率会好一些。

一加8Pro 亲测显示设置中开 QHD+ 高分辨率就不会有显示bug，

![image](https://user-images.githubusercontent.com/7845827/161668479-4ce6b0f5-aa93-4406-81e5-d9544e0b5f47.png)

**Comment by 88250** [comment]
这个好像是系统的问题，据说升级系统就好了 https://ld246.com/article/1651071489233

**Comment by 88250** [comment]
我们先关闭了，谢谢。

**Comment by Alive24** [comment]
> 这个好像是系统的问题，据说升级系统就好了 https://ld246.com/article/1651071489233

一加7pro还没收到这个更新orz
