### ISSUE TITLE
1.8.1  加上下划线后，导致下述问题

### ISSUE THREAD

**Issue by lvzhp** [siyuan-note/siyuan#4009]
下划线我自定义了一下样式。1.8.1 之前没有出现过这个问题
![1](https://user-images.githubusercontent.com/71172482/152986279-80afebc2-970c-4048-bc89-7974d2f17b48.gif)

**Comment by lvzhp** [comment]
[20220208202035-asiekd3.zip](https://github.com/siyuan-note/siyuan/files/8023725/20220208202035-asiekd3.zip)
源文件

**Comment by lvzhp** [comment]
@88250

**Comment by 88250** [comment]
标点符号（比如逗号）前后可能有解析问题，你试下不要划选到标点前后位置看看。

**Comment by 88250** [comment]
这个问题最终可能会在 https://github.com/siyuan-note/siyuan/issues/2911 中改进，目前暂时无法做调整了，先关闭，谢谢。
