### ISSUE TITLE
Android 7 无法打开程序

### ISSUE THREAD

**Issue by TonyW825** [siyuan-note/siyuan#4010]
### 描述问题 Describe the problem
无法打开程序。

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/46043068/153000308-9d348b5d-cd31-4454-b539-da454b366141.mp4

### 版本环境 Version environment

* Version: 1.8.1
* Operating system: Android 7.1.1
* Browser (if used): 

### 日志文件 Log File
无日志记录生成。

### 更多信息 More information
1.7.6 使用正常。

**Comment by 88250** [comment]
已经重新上传发布包，请从 https://github.com/siyuan-note/siyuan/releases/download/v1.8.1/siyuan-1.8.1.apk 下载试试。

**Comment by TonyW825** [comment]
已解决，谢谢。
