### ISSUE TITLE
希望能提升更新软件的体验

### ISSUE THREAD

**Issue by xfdj** [siyuan-note/siyuan#4011]
### 描述可能的最优解决方案 Describe the optimal solution

思源笔记更新速度很快，经常一两天一更新，但是更新软件的体验不是特别好，每次需要到网站手动下载最新安装包然后安装，不知道后续能不能提供一键升级，自动下载并安装的功能。

**Comment by 88250** [comment]
正在通过上架应用商店解决该问题，不过上架需要时间，我们还在努力。

先关闭了，感谢反馈。
