### ISSUE TITLE
无法开启中英文之间的自动空格

### ISSUE THREAD

**Issue by sunshineharry** [siyuan-note/siyuan#4019]
### 描述问题 Describe the problem

在原先的版本中，有`中英文之间自动空格`的功能，但是在最新版中，这个功能消失了

### 期待的结果 Expected result

`中英文之间自动空格`的功能回归

### 截屏或者录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/52942042/153323303-77c49ecb-10aa-4075-9cf4-6267ac47096b.png)
空格消失！！！

### 版本环境 Version environment

* Version: v1.8.1
* Operating system: win11
* Browser (if used):

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3986
