### ISSUE TITLE
右键选中内容后触发块引搜索和链接

### ISSUE THREAD

**Issue by logseq20182018** [siyuan-note/siyuan#402]

**Comment by 88250** [comment]
选中以后目前的操作是排版以及对所在块的操作：

![image](https://user-images.githubusercontent.com/873584/97953002-25d93500-1dda-11eb-8ad9-44f2271e6e32.png)

你的建议是在右键菜单里加一个全文搜索吗？

**Comment by logseq20182018** [comment]
就直接触发搜索框,就像remnote一样,很方便 在2020年11月03日 13:43，D 写道： 选中以后目前的操作是排版以及对所在块的操作： 你的建议是在右键菜单里加一个全文搜索吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 88250** [comment]
明白了，有了这个以后可以方便做链接，后面我们进行尝试，感谢建议。

**Comment by logseq20182018** [comment]
加油哈,看好你们------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;D&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月3日(星期二) 下午3:17
收件人:&nbsp;&quot;siyuan-note/siyuan&quot;<siyuan@noreply.github.com&gt;;
抄送:&nbsp;&quot;logseq20182018&quot;<1353575360@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 希望选中文字默认触发搜索功能，这样就可以很方便查看之前的笔记了 (#402)

**Comment by 88250** [comment]
> 已经建立了A、B两页并且各自输入了内容
> A页内容[a同b一起去了xxx]
> B页内容[xxx的游玩路线.......]
> 此时发现A页内容的xxx可以引用B页对应的文本块[xxx的游玩路线....]
> 
> 现在的方法为
> 1.在[a同b一起去了xxx]的xxx之前输入"[["然后找到B页中的内容块,建立引用,
> 2.把锚文本改为"xxx",
> 3.把引用后面的xxx删掉
> 
> 需求:
> 1.框选住A页中的"xxx"后,点击右键,在"新建文档"的选项下面多一个[根据已有内容块进行引用],建立引用后,锚文本自动为"xxx"
> 
> 从3步变为1步

https://github.com/siyuan-note/siyuan/issues#issue-739162133

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/747 中实现，谢谢。
