### ISSUE TITLE
支持笔记分享

### ISSUE THREAD

**Issue by sunshineharry** [siyuan-note/siyuan#4021]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

当我需要把我的笔记分享给好友的时候，能否提供一种格式，把单个或多个的文档或者页面（包括其子页面）打包成一个文件，方便其他思源笔记用户导入

### 描述可能的最优解决方案 Describe the optimal solution

比如我想把这个笔记本分享给好友：
![image](https://user-images.githubusercontent.com/52942042/153352941-77083322-1a51-4048-a834-8990bac7d940.png)
将其导出成一个思源笔记格式的压缩包（例如.syzip）
> 在压缩包中，包括笔记内容和附件（`assets`文件夹中用到的内容）
![image](https://user-images.githubusercontent.com/52942042/153353133-9bc70d73-1070-44a6-9fa9-0417777bc9c4.png)
**目前的导出只能是markdown的压缩包，在导入的过程中会出现格式问题**

**Comment by 88250** [comment]
直接将 .sy 文件发送过去，然后放到笔记本文件夹下面后重建索引即可，如果有资源文件的话，需要导出 Markdown，并将 assets 文件夹复制到 data/assets 下。

原始格式打包方式的导入导出之前考虑过，后续如果要做会重开 https://github.com/siyuan-note/siyuan/issues/3273
