### ISSUE TITLE
表格支持合并拆分单元格

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4022]

**Comment by Zuoqiu-Yingyi** [comment]
是类似这种的嘛?
[MultiMarkdown - Tables](https://fletcher.github.io/MultiMarkdown-6/syntax/tables.html)
[MultiMarkdown表格扩展使用方法详解（以Joplin为例）-Light](https://lightzhan.xyz/index.php/2020/04/04/multimarkdownbiaogekuozhanshiyongfangfaxiangjieyijoplinweili/)
