### ISSUE TITLE
支持转移引用

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4025]
* https://ld246.com/article/1644423355403
* https://github.com/siyuan-note/siyuan/issues/4786#issuecomment-1120330075

**Comment by fanglypro** [comment]
写一点我关于这个功能的看法：

这个功能的核心并不是把两个文档的正文进行合并，因为这个完全可以手动完成，而且也不算麻烦，核心在于把一个文档块的反链转移到另一个文档块上，这个是在思源软件本体中目前做不到的，而且在思源的架构之下，完全不用局限在文档块，任何类型的块的反链都可以转移，因此我认为这个功能更准确的叫法应该是“**反链转移**”，可以在两个文档块之间转移，可以在文档块和非文档块之间转移，可以在两个非文档块之间转移，在思源里实现这个功能可以比roam更加灵活。

目前可以直接操作底层文件来实现这个功能，比如我想把块A的反链转移到块B上，只需全局搜索块A的id，然后替换除了定义块A之外的搜索结果为块B的id。

我认为这个功能最终实现起来是这样的：首先用户给出两个块：块A与块B，用户想要把块A的反链转移到块B上，然后软件自动将所有引用块A的地方改成引用块B，最后，如果引用处是静态锚文本则锚文本不变，如果是动态锚文本则锚文本随之改变。
