### ISSUE TITLE
标签上光标无法正确显示

### ISSUE THREAD

**Issue by MilkBlock** [siyuan-note/siyuan#4029]
### 描述问题 Describe the problem
![bug](https://user-images.githubusercontent.com/47934647/153600218-51fb7db1-ac6e-4fc2-8fe3-52d862cd17df.gif)

### 期待的结果 Expected result
提示输入位置的光标应当显示在 #的左侧

### 版本环境 Version environment

* Version:  1.8.1
* Operating system: win11 
* Browser (if used):

**Comment by Vanessa219** [comment]
这个需要到相关主题的 github 上提 issue。
