### ISSUE TITLE
建议增加可导入Epub格式电子书，并支持标注笔记，笔记支持汇总显示

### ISSUE THREAD

**Issue by jomonylw** [siyuan-note/siyuan#4031]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

因目前大量电子书为Epub格式，阅读该格式时笔记需要使用其他阅读工具，笔记整合也不方便。
现已支持PDF格式的导入及阅读标记，如可以，希望能也能支持Epub格式。

**Comment by 88250** [comment]
你好，这个目前没有计划，可考虑通过其他工具将 epub 专为 pdf 格式。
