### ISSUE TITLE
右键取消表格自定义宽度

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4038]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在未拖动列分隔线调整列宽前, 表格宽度会随着内容自动调整, 在输入与编辑时非常直观, 但是一旦调整列宽后(包括误触列分割线), 该列便再也无法进行自动宽度调整, 只能删除该列后再插入

### 描述可能的最优解决方案 Describe the optimal solution

- 双击一条列分隔线取消该列的自定义宽度
- 在表格的块菜单中添加 `取消所有列自定义宽度` 菜单项

**Comment by 88250** [comment]
加菜单里了，按列设置：

![image](https://user-images.githubusercontent.com/873584/153799284-b6461b9e-e99b-4978-a890-735c140c477c.png)
