### ISSUE TITLE
记录文档浏览位置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4042]
https://ld246.com/article/1644762977238

**Comment by choyy** [comment]
刚才打开思源竟然就直接是上次浏览的位置（而且该位置上方及下方都未加载）
还以为是这个功能实现了，结果没有，这就很神奇了，所以这是 bug 吗？

**Comment by 88250** [comment]
@choyy 这个应该是聚焦到某个块了，看下编辑器上部的面包屑。

**Comment by choyy** [comment]
怎么看？是有个双向箭头吗
而且它只会聚焦到那一个文档的那一个位置，这有可能是什么原因？

**Comment by 88250** [comment]
聚焦到的层次图标会有高亮

![image](https://user-images.githubusercontent.com/873584/156565822-928e601c-d4d3-402a-8ab7-76d4d91f529b.png)

**Comment by choyy** [comment]
![图片](https://user-images.githubusercontent.com/68107073/156566547-9f5ac539-f756-4ec8-bf33-67e006a99bfa.png)
一打开是这样的，好像确实是高亮
但是不聚焦鼠标点一下标题那里也会高亮，又但是有的标题点一下又没有高亮？？？

**Comment by choyy** [comment]
而且同一标题有时候点一下会高亮，有时候又不会。。。

**Comment by 88250** [comment]
麻烦录屏演示一下操作。

**Comment by choyy** [comment]
https://user-images.githubusercontent.com/68107073/156568915-6a64e8ab-06f9-4828-8aed-cfa16c3e3e3f.mp4

**Comment by 88250** [comment]
麻烦再试下默认主题。

**Comment by choyy** [comment]
还是同样

**Comment by 88250** [comment]
通过大纲跳转以后，已经不再原来聚焦的层次里面了。

**Comment by 88250** [comment]
启动聚焦的问题暂时不清楚原因，后续会留意。

这个 issue 就是打算要做记住浏览位置，但是近期应该没有时间推进，还得再等等。

**Comment by choyy** [comment]
我似乎知道怎么回事了
- 步骤
    - 复制文档的某个块为嵌入块，然后关闭该文档
    - 在另一个文档嵌入
    - 点击嵌入块，在浮窗中 ctrl+点击面包屑在新标签打开
    - 然后关闭思源再打开就是直接聚焦到该块

**Comment by 88250** [comment]
@choyy 经过确认，这个是个特性，会保留聚焦状态。

**Comment by choyy** [comment]
似乎不是嵌入块打开的文档也会聚焦，暂时不清楚是什么原因

**Comment by woniuxia** [comment]
点赞~

**Comment by woniuxia** [comment]
@Vanessa219 V大这个功能上了后，[https://github.com/siyuan-note/siyuan/issues/5433](https://github.com/siyuan-note/siyuan/issues/5433) 这个功能是默认解决吗，还是需要单独处理？

**Comment by 88250** [comment]
@woniuxia 应该可以默认解决，如果不行的话请等发布后再到 #5433 中提醒我们一下，谢谢。

**Comment by choyy** [comment]
发现从文档树打开文档可以跳转到浏览位置，但从搜索面板打开文档不跳转
