### ISSUE TITLE
通过弹框显示最近编辑页面列表 Command/Ctrl + E

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#4043]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

虽然已经有了 #3952 可以查看最近关闭页签，但是最近编辑页面功能有助于更进一步的筛选。最近编辑页面快捷键功能可以减少搜索操作。

在显示列表后，可通过键盘或鼠标选择要打开/切换页面。

Command + E 现在好像是隐藏/显示 面包屑，该功能不一定需要这个快捷键，反正可以更改。

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/3293

**Comment by 88250** [comment]
PS：Ctrl+E 是标记高亮的快捷键。
