### ISSUE TITLE
文档较短时单击鼠标中键进入平移模式后无法退出

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4044]
### 描述问题 Describe the problem

单击鼠标中键可以进入平移模式, 此时光标变成如下所示
![image](https://user-images.githubusercontent.com/49649786/153761797-79d9cd35-8fd9-488d-86cc-753321f4f48c.png)
在平移模式再次单击鼠标左键/中键即可退出
但是在一篇较短的文章中(未显示滚动条)单击鼠标中键进入平移模式, 单击鼠标左键/中键均无法退出, 使用 Ctrl + 鼠标中键才可以退出平移模式

### 期待的结果 Expected result

较短的文章中(未显示滚动条)可以击鼠标左键/中键退出平移模式

### 截屏或者录屏演示 Screenshot or screen recording presentation

![思源笔记-bug反馈-07](https://user-images.githubusercontent.com/49649786/153762275-4b5fc01c-bdba-4052-a573-9b51c4ee94c8.gif)

### 版本环境 Version environment

* Version: 1.8.2

**Comment by 88250** [comment]
我这里在 v2.5.2 上重现不了问题，再次单击中建可以正常退出平滑滚动。

![issue](https://user-images.githubusercontent.com/873584/204692515-f7503c01-d73f-49ef-9579-45c36dd57d9d.gif)


我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
