### ISSUE TITLE
#号输入标题弹出内容块选项

### ISSUE THREAD

**Issue by JamYiz** [siyuan-note/siyuan#4045]
### 描述问题 Describe the problem

#号输入标题弹出内容块选项
### 期待的结果 Expected result

应在一个#后结束
### 截屏或者录屏演示 Screenshot or screen recording presentation

![图片](https://user-images.githubusercontent.com/44351690/153790898-b5c06213-13d9-4ef3-91e4-5fa45a199a43.png)

### 版本环境 Version environment

* Version: 1.8.2
* Operating system: windows 11
* Browser (if used):

**Comment by 88250** [comment]
输入 `#` 以后会触发标签自动完成，不是标题。
