### ISSUE TITLE
docker的latest版本拉取到是1.6.3

### ISSUE THREAD

**Issue by shanyan-wcx** [siyuan-note/siyuan#4055]
### 描述问题 Describe the problem

docker的latest版本拉取到是1.6.3，但是docker hub上显示的是最新的1.8.2，这是怎么回事呢？
### 期待的结果 Expected result

应该拉取到1.8.2
### 版本环境 Version environment

* Version: 
* Operating system: 群晖
* Browser (if used): edge

**Comment by Zuoqiu-Yingyi** [comment]
貌似是镜像源的问题

**Comment by shanyan-wcx** [comment]
> 貌似是镜像源的问题
那该怎么解决？

**Comment by 88250** [comment]
指定版本或者使用 Docker 官方仓库，或者找一下如何刷新镜像仓库的问题（这一点我不确定是否能工作）。

我关闭了，谢谢。
