### ISSUE TITLE
标签栏自动分屏

### ISSUE THREAD

**Issue by qiaomuliu** [siyuan-note/siyuan#4056]
### 描述问题 Describe the problem
编写查看笔记时,想要查看某个标签，点击标签后分隔出两个页面,并且按住Ctrl点击时，会在新的页面打开标签页
笔记本屏幕比较小，分隔之后显示不全。
如果先打开标签页面，再次打开其他要看的笔记 就不会出现分屏问题

### 期待的结果 Expected result
分屏是最优解吗？ 能否给个自定义情况呢，我不想分屏

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/8100135/154391460-75fd8a61-14b1-4d5f-84de-018901c4c2d0.png)

![image](https://user-images.githubusercontent.com/8100135/154391618-41cd9003-00a8-40a8-bc8b-d0d1bc5b3a2d.png)

### 版本环境 Version environment

* Version: 当前版本 v1.8.2

**Comment by 88250** [comment]
你好，如果经常使用标签搜索的话，可以考虑将搜索页签拖动到其他页签旁边，或者钉住搜索页签：

![image](https://user-images.githubusercontent.com/873584/154486727-7413a291-0ca9-40a9-833e-df596d982d0e.png)

**Comment by qiaomuliu** [comment]
钉住可以解决问题，谢谢
