### ISSUE TITLE
Firefox 浏览器剪藏扩展

### ISSUE THREAD

**Issue by JamYiz** [siyuan-note/siyuan#4057]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
使用Firefox时

### 描述可能的最优解决方案 Describe the optimal solution
上架firefox插件商店，实现chrome上的优秀剪辑功能

**Comment by 88250** [comment]
你好，我们目前没有时间精力开发。

如果可能的话，希望有社区开发者可以参与进来，代码可参考 https://github.com/siyuan-note/siyuan-chrome

**Comment by zher52** [comment]
@88250 我这实现了一版firefox的插件，
[https://github.com/zher52/siyuan-firefox.git](https://github.com/zher52/siyuan-firefox.git)
已知问题：由于firefox安全性的限制，api的地址必须使用https协议。
