### ISSUE TITLE
新建子文档能够置底

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#4059]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
文档自定义排序时, 常常需要新建的子文档排在已有子文档的下面, 即置底. 目前新建的子文档总是排在最前面, 每次需要手动拖到底部, 比较麻烦.

### 描述可能的最优解决方案 Describe the optimal solution
提供选项, 可以让新建的子文档总是排在已有文档的下面.

**Comment by 88250** [comment]
你好，这个选项提供不了，设计上只能统一在顶部 https://github.com/siyuan-note/siyuan/issues/3181
