### ISSUE TITLE
界面布局还原时页签大小不能复原问题

### ISSUE THREAD

**Issue by KaloSora** [siyuan-note/siyuan#406]
环境信息
  操作系统：MacOS
  软件版本: V0.4.0

功能需求
个人希望的排版，打开思源拖动“大纲”到左侧，同时点开“书签页面”（如下图）
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/35422660/97935714-560ddd00-1db4-11eb-955a-c7cc0b3caf05.png">

问题在于，每次重启都要重新调整"大纲位置"。并且“书签”和“标签”页面也要重新打开（如下图）
<img width="993" alt="image" src="https://user-images.githubusercontent.com/35422660/97935852-b69d1a00-1db4-11eb-8358-068f0909f76b.png">

能否让用户自行选择，是否启用保存用户界面布局的选项，并且添加一个能够重置界面布局的按钮

**Comment by 88250** [comment]
正常关闭（点x）的话会自动保存布局的，重置布局在设置 - 外观中。

**Comment by KaloSora** [comment]
在Mac下，布局会保存，但是大纲的宽度会变大，每次都要手动调整。

**Comment by KaloSora** [comment]
v0.4.1已修复该问题
