### ISSUE TITLE
win端文件树添加自定义emoji和win emoji的文档不对齐

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4060]
### 描述问题 Describe the problem

加了win emoji的文档名在文件树位置会偏右，自定义emoji则偏左
![image](https://user-images.githubusercontent.com/60436214/154500440-9686a2a9-ff64-4887-aee3-19e4f77015cb.png)

### 版本环境 Version environment

* Version: 1.8.2
* Operating system:  win10、win11

**Comment by Vanessa219** [comment]
win emoji 中的有些 emoji 无法对齐这个应该是系统的问题，自定义 emoji 的话需要看一下 emoji 是否上下居中

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/154683455-4db9c6e1-44d7-4e8b-8d90-37675e1eed89.png)
在win平台我把文档图标设置为 width: 20px; 就对齐了
```css
.file-tree .b3-list-item__icon {
    width: 20px;
}
```

**Comment by Achuan-2** [comment]
嗯，那是svg是20，但win 端的emoji是字体，svg和字体的宽度是有差别的

**Comment by Vanessa219** [comment]
字体不能限制宽度，要设置 font-size，宽度限制了有些比较宽的 emoji 就会和后面的内容重叠。

**Comment by Achuan-2** [comment]
默认就设置了font-size: 15px;好像，目前我还没有遇到重叠的情况，不过确实有些emoj会偏右边点，但我在乎的是文档名对齐，至少比默认主题相比有一样能对齐还能接受。
可能这个方案确实有问题吧，我个人的主题改改就是了
