### ISSUE TITLE
导出为 .docx 时无法正常转换公式

### ISSUE THREAD

**Issue by SimonZhouxz** [siyuan-note/siyuan#4062]
### 描述问题 Describe the problem

笔记导出为docx时无法正常转换公式。
采用导出为markdown再用pandoc命令转为docx时能正常导出公式

### 期待的结果 Expected result

希望导出的docx能保留公式

### 截屏或者录屏演示 Screenshot or screen recording presentation

采用笔记中选项直接导出：
![image](https://user-images.githubusercontent.com/71009679/154546947-369e7530-a045-4e02-b359-6fee71f24cb2.png)
先导出markdown再用pandoc转换为docx：
![image](https://user-images.githubusercontent.com/71009679/154547071-162014b2-637d-431d-be3a-a081d5af00dd.png)
使用的命令为``pandoc -o wordname.docx notename.md``

### 版本环境 Version environment

* Version: 1.8.1
* Operating system: windows10
* Browser (if used): /

### 日志文件 Log File

I 2022/02/17 20:40:14 runtime.go:32: kernel is booting:
    * ver [1.8.1]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [E:\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211218]
    * workspace directory [Q:\SiYuanDocument, data 30 MB]
I 2022/02/17 20:40:14 conf.go:263: local serve path [http://192.168.0.8:6806]
I 2022/02/17 20:40:14 serve.go:68: kernel is booting [http://127.0.0.1:6806]
I 2022/02/17 20:40:14 conf.go:479: pre-init database size [1.4 MB]
I 2022/02/17 20:40:15 index.go:132: use existing database for box [20220208033316-2jmwaox]
I 2022/02/17 20:40:15 index.go:132: use existing database for box [20220208102006-gjsg66p]
I 2022/02/17 20:40:15 index.go:132: use existing database for box [20220217184241-f6dqrmn]
I 2022/02/17 20:40:15 index.go:132: use existing database for box [20210808180117-czj9bvb]
I 2022/02/17 20:40:15 index.go:214: resolving refs...
I 2022/02/17 20:40:15 index.go:354: resolved refs [57]
I 2022/02/17 20:40:15 conf.go:500: post-init database size [1.4 MB], tree stat [count=53, size=1.3 MB]
I 2022/02/17 20:40:15 working.go:133: kernel booted

**Comment by 88250** [comment]
暂时没有找到解决方案，先手动 pandoc 顶顶。

**Comment by Geo123abc** [comment]
[如何将LaTeX公式拷贝到Word中_Expressing Youself Using Code-程序员宝宝_latex公式复制到word - 程序员宝宝](http://www.cxybb.com/article/bendanban/52823171  )

[优雅的拷贝公式到word中_weixinhum-CSDN博客_word复制公式](https://blog.csdn.net/weixinhum/article/details/87982407  )

这两天我也遇到了思源笔记公式往Word中复制的应用问题，然后查到了这两个，感觉 Typora 的解决方案挺好的，那么思源是否考虑在公式复制为PNG按钮旁增加一个功能“复制到Word”中 

（通过mathtype之类的软件也可以实现在Word中插入LaTeX公式之类的，但是感觉流程麻烦）

**Comment by bohong65** [comment]
> 暂时没有找到解决方案，先手动 pandoc 顶顶。

手动pandoc时发现md→docx时多级有序列表格式不能像暗黑模式那样数字+小写字母+小写罗马，html→docx时标题格式有问题。能否公开一下当前版本（v2.0.8）使用pandoc从html转换到docx的命令参数

**Comment by 88250** [comment]
@bohong65 `pandoc -f html --resource-path=请从这里开始 请从这里开始\index.html -o test.docx`

**Comment by bohong65** [comment]
> @bohong65 `pandoc -f html --resource-path=请从这里开始 请从这里开始\index.html -o test.docx`

已解决，感谢！

**Comment by Zuoqiu-Yingyi** [comment]
@88250 是否可以使用 `*.md` 文件中转的方式调用 pandoc, 目前使用 `*.html` 文件中转时所有公式都无法渲染😂

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 好像找到一个方案，我们把渲染 HTML 时公式改为 `$` 包裹，然后加 pandoc 参数 `-f html+tex_math_dollars` 似乎就能使用 pandoc 导出了。

**Comment by Geo123abc** [comment]
> 

使用pandoc导出的时候可以使用 参数了？

**Comment by 88250** [comment]
@Geo123abc 代码里写死的

**Comment by Geo123abc** [comment]
> @Geo123abc 代码里写死的

哦哦，我还以为可以自定义呢，是不考虑支持自定义吗？

**Comment by 88250** [comment]
后面看情况吧，目前似乎没有太多需求。

**Comment by Geo123abc** [comment]
> 后面看情况吧，目前似乎没有太多需求。

科研狗写文章，可能有需求，之前我提过、追过这个事情
