### ISSUE TITLE
预览模式提供全选

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4063]
https://ld246.com/article/1645169380998

**Comment by Vanessa219** [comment]
可以点击复制到知乎/公众号/语雀试试，这样就可以把全部内容复制下来了。

**Comment by jabobian** [comment]
原来close啦，这不是同一个问题哦，

知乎复制的图片链接是远程网址https://b3logfile.com/siyuan/1615425032500/assets/image-20220303222143-vipz9yg.png，而我需要的是本地链接http://127.0.0.1:6806/assets/image-20220304223640-xcq29n7.png。

我需要复制到Supermemo之类的软件。
能否增加一个复制本地的按钮呢。

我本来想自己动手把复制到知乎中的html内容更改image src，需要重新修改剪贴板数据，
但是总觉得对你们来说更简单。还请考虑一下，感谢！

**Comment by 88250** [comment]
@jabobian 用导出 Markdown HTML 顶顶。

**Comment by jabobian** [comment]
嗯，谢谢D大指导。
我试过用AutoHotkey的WinClip和RegExReplace将b3logfile替换为127.0.01，结果在其它浏览器（OneNote, Word, SeaMonkey等）都能正常显示，但是复制到Supermemo就不行，图片不显示，没搞懂什么原因。只能等你们这边出手了。

我只知道Supermemo对Html格式比较挑，比如剪贴板中的html内容不能有一些看似不影响的换行。
CodePage我没看出问题，思源可能默认是CP936，WinClip默认用UTF-8，但是RegExReplace默认是应该也没有破坏其它东西啊。捣腾了半天搞不定。目前采用的是AutoHotkey自动点击鼠标拖动选择。
