### ISSUE TITLE
Android 端移除录音功能

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4065]
#4041

**Comment by netdog2019** [comment]
IOS端支持的啊，可以录音啊。点击开始录音，结束录音后会把录音文件自动插入笔记中。

![46c76319ac2c53051c8ed1f402c1342](https://user-images.githubusercontent.com/49815951/154793102-da368324-8148-4e2c-b09a-3e02ed360f5c.jpg)

**Comment by 88250** [comment]
@netdog2019 收到，我们再确认一下看看。

**Comment by 88250** [comment]
有的应用商店审核过不了，只能先移除了。

**Comment by TCOTC** [comment]
为啥录音功能会过不了审核？现在能不能再加回来？

关联需求 https://ld246.com/article/1725594125957

**Comment by 88250** [comment]
加不了，加了过不了审核。
