### ISSUE TITLE
折叠列表子内容，按回车不会新建列表项

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4074]
### 描述问题 Describe the problem

如图，折叠列表子内容（即不设置子列表），按回车不会新建列表项，而是在内容前新增空行
![2](https://user-images.githubusercontent.com/60436214/154827180-889a5b9f-a7c7-4019-a334-edfee8d9852b.gif)

### 期待的结果 Expected result

用户折叠列表项按回车的预期是在下方新建一个列表项
> ps: 这其实是支持折叠列表子内容后一直都有的问题，貌似一直没看见有人提

### 版本环境 Version environment

* Version: v1.8.3 alpha1
* Operating system:  win11
* Browser (if used):

**Comment by Vanessa219** [comment]
目前无法重现，在 1.8.3-alpha2 中修改过一点，还麻烦再试试
