### ISSUE TITLE
Ctrl+F 页内搜索希望能够按块在文档中出现位置顺序排列

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4076]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

页内搜索，定位该文档中关键词出现的位置

### 描述可能的最优解决方案 Describe the optimal solution

按文档顺序排列，目前的顺序是乱序（不知道按什么顺序排列），如果关键词出现多次，就难以找到第一次出现的位置

**Comment by Achuan-2** [comment]
同时希望替换也是按块在文档的位置排序

**Comment by 88250** [comment]
这个估计实现不了，排序规则只能统一为按类型排序。我关闭了，感谢反馈。
