### ISSUE TITLE
Bug on Windows 11 and Windows 10

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#4077]
I need help. I study on my PC and my notebook (when I'm at work). PC is running windows 11, and the notebook is running windows 10. I am trying to copy the "SiYuan" folder from my PC to my notebook, but I can't. Whenever I open the program in Windows 10, it's like the folder is empty. I already changed the directory, name, export files, but nothing. Every time I open the program after having copied from Windows 11, the program in Windows 10 does not recognize the file folder.

**Comment by 88250** [comment]
Hello, try copying the workspace/data folder only, and clicking rebuild index on the doc tree panel.
