### ISSUE TITLE
docker 私有部署无法访问

### ISSUE THREAD

**Issue by iswbm** [siyuan-note/siyuan#4078]
## 问题描述 

当我使用如下命令进行部署后，容器正常启动
```
docker run -itd --name siyuan \
    --restart=always \
    -u 1000:1000 \
    -v /home/siyuan/notes:/home/siyuan/Documents/SiYuan \
    -v /home/siyuan/server/build:/opt/siyuan/stage/build \
    -p 6806:6806 \
    b3log/siyuan:v1.8.2
```
访问 ip:6806 后
<img width="774" alt="image" src="https://user-images.githubusercontent.com/22311419/154989976-dd5fba84-9dff-4791-8396-c6edb2482a27.png">

会重定向到 http://ip:6806/stage/build/desktop/?r=qwo8v46，无法访问，从日志上看也没有报错
<img width="902" alt="image" src="https://user-images.githubusercontent.com/22311419/154990465-7c478b4e-5949-4c0b-aa57-3e0c9fae347c.png">

**Comment by 88250** [comment]
请参考帮助文档进行部署，谢谢。

**Comment by iswbm** [comment]
可否给个官方官方链接-------- 原始邮件 --------发件人： D ***@***.***>日期： 2022年2月22日周二 01:18收件人： siyuan-note/siyuan ***@***.***>抄送： 王炳明 ***@***.***>, Author ***@***.***>主    题： Re: [siyuan-note/siyuan] docker 私有部署无法访问 (Issue #4078)

请参考帮助文档进行部署，谢谢。

**Comment by 88250** [comment]
帮助文档中搜索 Docker

**Comment by iswbm** [comment]
抱歉，昨天和早上都尝试了，但没有找到帮助文档。

在 https://ld246.com/ 里搜 docker ，结果如下
<img width="917" alt="image" src="https://user-images.githubusercontent.com/22311419/155063339-4b822758-969f-4738-9429-d2fc5a9ec0f9.png">

在该仓库下也没有找到对应的入口。

如果方便的话，还请给个指引

**Comment by 88250** [comment]
下载桌面端或者移动端思源，自带的帮助文档。

**Comment by iswbm** [comment]
> 下载桌面端或者移动端思源，自带的帮助文档。

谢谢，已经部署上了。

另，问一下，私有部署的 siyuan，是没有主题可以选的吗？

**Comment by 88250** [comment]
设置 - 集市里面可以选。
