### ISSUE TITLE
希望支持选中文字内容后可以纯键盘操作

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#4079]
## 如图：
![image](https://user-images.githubusercontent.com/72953189/155046587-3300467f-cf5e-4c8b-b980-1203ae7a278b.png)
## 而不是像下图一样：
![image](https://user-images.githubusercontent.com/72953189/155046756-d6c6dd9a-5b92-4b4f-a10d-d3ce29225fbc.png)

**Comment by Vanessa219** [comment]
工具栏上的按钮都有快捷键，可以直接使用
