### ISSUE TITLE
在挂件中使用中文数据法输入时,会出现焦点丢失导致默认选中挂件节点块的问题

### ISSUE THREAD

**Issue by jpanda-cn** [siyuan-note/siyuan#4081]
### 在挂件中使用中文数据法输入时,会出现焦点丢失导致默认选中挂件节点块的问题

当前使用的思源版本为: v1.8.2
操作系统为:MacOS BigSur 11.6.4
输入法: 搜狗中文输入法,MAC自带中文输入法
简单测试过三个挂件,均存在相同的问题(插件都存在于思源装修群文件): 
1. excalidraw
2. jpanda-json
3. cc-sy-luckysheet

### 问题复现步骤:

当我在挂件内部进行数据编辑操作时:

- 输入以第一个字符的时候,正常使用
- 输入第二字符的时候,输入法自带的文字候选面板消失,编辑器默认会选中挂件所属的节点块
- 输入第三个字符,会使用第三个字符替换掉挂件对应的节点块

### 截屏或者录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/50101020/155076672-7a4aa8cb-77f4-4b48-8072-908f69b206f5.png)
![image](https://user-images.githubusercontent.com/50101020/155076703-e441dcfe-06cf-4477-be5b-ff0a28687b35.png)

### 版本环境 Version environment

* Version:  1.8.2 
* Operating system:  MacOS BigSur 11.6.4
* Browser (if used):

**Comment by Vanessa219** [comment]
目前无法重现，在 1.8.3-alpha2 中修改过一点，还麻烦再试试
