### ISSUE TITLE
docker 部署后，界面卡住无法使用

### ISSUE THREAD

**Issue by iswbm** [siyuan-note/siyuan#4082]
使用 docker 部署后，输入鉴权密码后，一直处于该界面，换浏览器也是一样。

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/22311419/155171843-c4e32bf0-9c39-43cf-978c-c6f0f88b4aa4.png">

**Comment by 88250** [comment]
打开 F12 看下网络请求。

**Comment by iswbm** [comment]
> 打开 F12 看下网络请求。

 好像没有什么问题

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/22311419/155337494-1ed16f7d-845c-4014-9643-347ff16ff452.png">

**Comment by 88250** [comment]
手动刷新以后能进入吗？

**Comment by iswbm** [comment]
> 手动刷新以后能进入吗？

不可以，一直处在这个界面。

另外，有中间有 kill 一次 docker 容器，不知道跟这个有没有关系

**Comment by 88250** [comment]
重新使用域名进入呢？

**Comment by iswbm** [comment]
> 重新使用域名进入呢？

无论使用的是域名进入还是 ip:port，都是一样的

**Comment by 88250** [comment]
发一下 Docker 容器的启动命令。

**Comment by 88250** [comment]
加内核参数 `--servePath=你的域名:端口`

**Comment by iswbm** [comment]
加上了也不行。

我这里反向代理这么写没有问题吧

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

server{
        listen 80;
        server_name  mydomain.com;
        access_log note.log;
        index  index.php index.html index.htm;

        location / {
          proxy_pass  http://127.0.0.1:6806/; # 转发规则
          proxy_set_header Host $proxy_host; # 修改转发请求头，让8080端口的应用可以受到真实的请求
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
        }
}
```

**Comment by 88250** [comment]
NGINX 配置应该没错，参数这样加的吗？ `--servePath=mydomain.com:80`

**Comment by iswbm** [comment]
> NGINX 配置应该没错，参数这样加的吗？ `--servePath=mydomain.com:80`

原来是用 80 端口，我指定的 6806

目前可以了，感谢大佬开发耐心的答疑。

**Comment by Jackiexiao** [comment]
贴一下我的指令，如果界面卡主打不开，可能强制刷新一下页面(ctrl shift + R)就可以了
```
docker run \
    --name siyuan \
    --restart=always \
    -p 8021:6806 b3log/siyuan \
    --servePath "123.12.12.123:8021" \
    --accessAuthCode ""
```
