### ISSUE TITLE
Excel 粘贴时第一个单元格会出现换行

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#4083]
![演示](https://user-images.githubusercontent.com/56879067/155249594-7fdb2258-c34a-400c-a41d-c7ffaea5f356.gif)

**Comment by heimi98** [comment]
改个字体居然就没问题了，好神奇，是怎么回事？
![演示1](https://user-images.githubusercontent.com/56879067/155249877-a43644d8-5f4d-4215-858b-87f2978a3274.gif)

**Comment by 88250** [comment]
麻烦上传一下有问题的 excel 文件，我们调试看看。

**Comment by heimi98** [comment]
[测试文件.xlsx](https://github.com/siyuan-note/siyuan/files/8122300/default.xlsx)

**Comment by heimi98** [comment]
> 麻烦上传一下有问题的 excel 文件，我们调试看看。

已上传

**Comment by 88250** [comment]
主要是第一个当一个被换行了，是这问题吗？
