### ISSUE TITLE
Installation Directory.

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#409]
Currently

![3](https://user-images.githubusercontent.com/15811943/97961586-f1c03d00-1df6-11eb-8569-e2308c100554.PNG)

I think the best place will be

c:\Program Files\SiYuan

**Comment by ens100** [comment]
Hi @jakekwak  I think installs in with this directory as you selected to install for "this user only". If you select "all users" when installing it will be installed in C:\Program Files\

Hope this helps

**Comment by jakekwak** [comment]
@ens100 Thanks.  I got it.
