### ISSUE TITLE
a标签 +code标签,出现问题

### ISSUE THREAD

**Issue by noenif** [siyuan-note/siyuan#4090]
![image](https://user-images.githubusercontent.com/25174520/155426632-c923c2d7-6ba1-4c57-b5f7-73688293267e.png)
如上结构复制后,出现
![image](https://user-images.githubusercontent.com/25174520/155426890-c34f8aa1-ccc3-4759-93df-45046e755e9b.png)
实际的样式应该是这样的
![image](https://user-images.githubusercontent.com/25174520/155426952-ceb692fa-18ef-493b-ae3e-ca187f8c8e74.png)

**Comment by 88250** [comment]
你好，`<code>` 标签里的内容会按照原样解析渲染。
