### ISSUE TITLE
微软商店版思源更新后无法启动

### ISSUE THREAD

**Issue by JamYiz** [siyuan-note/siyuan#4091]
### 描述问题 Describe the problem
微软商店版思源更新后无法启动

### 期待的结果 Expected result

卡在下图界面
### 截屏或者录屏演示 Screenshot or screen recording presentation
![图片](https://user-images.githubusercontent.com/44351690/155448659-55cbe01e-81fa-4cfe-9008-926efafddcf4.png)

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by zhuzixian** [comment]
v1.8.3-alpha4 存在这个问题，通过浏览器可以正常访问。

**Comment by 88250** [comment]
感谢反馈，这个问题会在下次发布时修复。
