### ISSUE TITLE
Android 端上架酷安

### ISSUE THREAD

**Issue by ChirsGod** [siyuan-note/siyuan#4092]
目前看见近期计划有华为和小米应用商店的应用上架的计划。希望也考虑一下酷安的下载支持。

**Comment by 88250** [comment]
感谢提议，后面会考虑。

**Comment by checkwoodson** [comment]
**必须上酷安啊， 欢迎加入基友之家~**

**Comment by 88250** [comment]
已经提交酷安审核 😄

**Comment by 88250** [comment]
已经上架 https://www.coolapk.com/apk/292664
