### ISSUE TITLE
导出pdf功能增强：设置添加字号和字体设置

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4094]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

希望导出pdf设置添加字号和字体设置，
导出pdf一般有两个用途，1是打印，2是分享。
一般电脑阅读笔记会选择黑体等比较粗好阅读的字体，字号会稍微大些，对于打印需求来说，字体一般会选择宋体等公文偏爱的字体，而且字号一般也会稍小点
如果导出pdf能设置字体和字号，用户就不必在导出前后来回调整字体和字号了
![image](https://user-images.githubusercontent.com/60436214/155514306-18695c15-9b88-43c2-9305-2c8610643826.png)

**Comment by 88250** [comment]
应该是调不了 https://www.electronjs.org/docs/latest/api/web-contents#contentsprinttopdfoptions

先关闭了。
