### ISSUE TITLE
不确定这个算不算BUG，导出PDF功能缩放问题

### ISSUE THREAD

**Issue by lkk66** [siyuan-note/siyuan#4098]
### 导出PDF时，长的表格会出不来。缩放的问题

**使用了横向排列，然后导出了PDF，文件有点问题**
截图在这里，两个图片，一个是笔记里的，一个是导出后的
https://www.aliyundrive.com/s/iKWKFoxxPfB

如果设置成超级快的宽度为33%，导出就会这样 这个目录下的33%文件夹里的截图
https://www.aliyundrive.com/s/iKWKFoxxPfB

导出的PDF不会缩放表格好像

**Comment by Vanessa219** [comment]
PDF 的宽度和编辑器中的宽度是不一样的，要小很多。百分比也会对应的缩小。想要显示完整的话，取消横排试试。
