### ISSUE TITLE
引用的转换

### ISSUE THREAD

**Issue by studier7** [siyuan-note/siyuan#410]
建议提供引用转换文本的功能。
嵌入文本块只能换行，不能同行显示。建议引用的文本块，可以直接
生成被引用的文本，如此叠加文本生成段落。

在预览引用内容窗口，添加生成文本按钮。
![VV)0LWMDJKNH9MHH1X}A6 D](https://user-images.githubusercontent.com/72493469/97965821-eb7d9100-1df5-11eb-860c-59b20f823071.png)

**Comment by 88250** [comment]
我理解下来，是否是提供这样的功能：

在块中使用引用，形如：
```
foo ((id1)) bar ((id2)) baz
```

然后预览或者导出时不用块渲染，而是将这两个 id 所指向的内容合并到当前块中渲染，其结果为：

```
foo id1content bar id2content baz
```

后面截图应该是需要提供一个复制内容按钮，方便复制内容。

以上理解应该没错吧，谢谢建议。

**Comment by studier7** [comment]
按钮实现复制和粘贴两个操作更好，把引用的内容直接插入行：

hello（引用1）！hello world！

hello world！hello world！

**Comment by HarryHuaa** [comment]
> 按钮实现复制和粘贴两个操作更好，把引用的内容直接插入行：
> 
> hello（引用1）！hello world！
> 
> hello world！hello world！

我理解着你的意思其实是:通过引用的语法进行块内容的搜索,进行ctrl c+ctrl v 放到指定位置

其实这部分有两个可选项,一个是作者理解的引用的块内容渲染到当前块,一个是引用的块内容粘贴至当前块,两者的区别在于,当前块内容的改变是否会改变原被引用块的内容

**Comment by lss6378** [comment]
**块引用** 和 **块嵌入** 转换按钮还是非常有用的，预览窗口使用鼠标点击转换**引用**和**嵌入**状态，不需要手动输入`!`

**Comment by 88250** [comment]
块引嵌入文本计划在 https://github.com/siyuan-note/siyuan/issues/490 中通过锚文本模板用法实现。

@lss6378 转换功能后面如果需要请单独开 issue。

感谢各位讨论，谢谢。
