### ISSUE TITLE
所见即所得模式和导出模式的嵌入块数量不匹配

### ISSUE THREAD

**Issue by jiangbaiyan** [siyuan-note/siyuan#4104]
版本：mac m1 v1.8.4
问题：所见即所得模式，只有一个嵌入块。但转换成导出模式，出现了多个嵌入块。
预期：所见即所得模式和导出模式的嵌入块都为一个。
操作路径：所见即所得模式曾重复插入相同的嵌入块，后来又删除了，但好像导出模式下并没有删除成功，所以仍然保存了多个嵌入块

所见即所得模式：
<img width="736" alt="image" src="https://user-images.githubusercontent.com/23721125/155827636-5c8d5414-fa1b-4df3-af04-ef323ea970a0.png">

导出模式：
<img width="836" alt="image" src="https://user-images.githubusercontent.com/23721125/155827649-65fcd036-a42b-4a5a-ba1b-8bd228128b1d.png">

**Comment by 88250** [comment]
试下 F5 刷新当前编辑器以后再导出。

**Comment by jiangbaiyan** [comment]
> 试下 F5 刷新当前编辑器以后再导出。

试了，还是会复现的。重启也试过了

**Comment by 88250** [comment]
试下重建索引。

**Comment by jiangbaiyan** [comment]
> 试下重建索引。

重建索引后，所见即所得模式也变成三个了
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/23721125/155829363-9134f78f-0302-4818-9356-a181e3814e8a.png">

**Comment by 88250** [comment]
查询结果指向同一个 ID 一样的块吗？

**Comment by jiangbaiyan** [comment]
> 查询结果指向同一个 ID 一样的块吗？

是的，这三个id都一样

**Comment by 88250** [comment]
那可能是某些原因造成了 .sy 数据重复。关闭思源以后，用文本编辑器全局搜索这个 ID 看看。

**Comment by 88250** [comment]
我先关闭了，如果还有补充欢迎随时跟帖，谢谢。
