### ISSUE TITLE
`Ctrl+End/Home` 调整为在整个文档范围生效

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#4108]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

动态加载的文档能更快速的到达文档结尾继续编写，虽然可以使用引用或者大纲跳转，但是不够便利，望采纳。

**Comment by Vanessa219** [comment]
该快捷键已经被占用了。
<img width="491" alt="image" src="https://user-images.githubusercontent.com/970828/156101860-12c56d56-1b60-451a-9c60-3b84a24e62fc.png">

**Comment by royc01** [comment]
@Vanessa219 是的，但是动态加载的文档不能直接跳到最后的块，希望能更改一下。

**Comment by Vanessa219** [comment]
那把 ctrl+end 改成到最后的块？

**Comment by royc01** [comment]
是的，就是这个意思，非常感谢
