### ISSUE TITLE
HTML 标签 `<ms>` 导致卡死的问题

### ISSUE THREAD

**Issue by zZ-10** [siyuan-note/siyuan#411]
1、今天下午在写笔记， 莫名其妙就卡死了， 之后任务管理器强行关闭后，正在编写的笔记打不开了，

**Comment by zZ-10** [comment]
![image](https://user-images.githubusercontent.com/58500946/97966283-97bf7780-1df6-11eb-85c4-cf4c3ad1ba4e.png)
自我分析原因如下:
今天下午莫名其妙卡死几次， 不知道是我电脑问题还是软件问题，亦或者是 语法错误导致的；

在最后一次卡死后，通过任务管理器关闭后， 编辑器直接打开文档代码如下，：
![image](https://user-images.githubusercontent.com/58500946/97966531-eb31c580-1df6-11eb-8e91-71d799bf8e0d.png)
！！！文件后缀被我直接改成了txt
[2.5说明_20201103162553-nm4er1k.sy.txt](https://github.com/siyuan-note/siyuan/files/5480233/2.5._20201103162553-nm4er1k.sy.txt)

**Comment by 88250** [comment]
感谢反馈，v0.4.1 修复。

**Comment by zZ-10** [comment]
🐛  刚刚把图片需要保密的信息打码了， 别的没有修改

**Comment by 88250** [comment]
谢谢版主，已经解决了，稍后就发布 v0.4.1
