### ISSUE TITLE
思源图片无法使用第三方图床以及网络图片

### ISSUE THREAD

**Issue by sYstemk1t** [siyuan-note/siyuan#4110]
思源无法使用图床或网络图片，很困扰一天了！

无法使用的链接：https://github.com/sYstemk1t/Picture/blob/main/Pic/20220226/10.png

**Comment by 88250** [comment]
这个地址返回的是 HTML Document，不是图片。

![image](https://user-images.githubusercontent.com/873584/155843152-e44a77f6-f1ee-45eb-a9ad-c8bef4552efe.png)

**Comment by sYstemk1t** [comment]
ok，稍等，我使用微博的图床也无法使用！
我在思源的社区给您上传图片！
