### ISSUE TITLE
表格居中时无法对单元格宽度进行拖拽

### ISSUE THREAD

**Issue by somata-cn** [siyuan-note/siyuan#4111]
### 描述问题 Describe the problem
表格居中显示时，无法对表格宽度进行拖动操作。但是在居左的时候还是可以进行操作的。
![siyuan](https://user-images.githubusercontent.com/40385591/155844378-7d9dfadc-fa31-4e77-a6e4-2f7b2d48b6ba.gif)

### 版本环境 Version environment

* Version: 1.8.4
* Operating system: Docker
* Browser (if used): Microsoft Edge 版本 98.0.1108.62 (官方内部版本) (64 位)

**Comment by somata-cn** [comment]
好像是错位了。
![siyuan_2](https://user-images.githubusercontent.com/40385591/155844495-021e08b3-69ec-4a4e-bf01-049640e72db3.gif)

**Comment by 88250** [comment]
和 https://github.com/siyuan-note/siyuan/issues/4107 应该是同一个原因导致，我们在看了，感谢反馈。
