### ISSUE TITLE
One click is better

### ISSUE THREAD

**Issue by jakekwak** [siyuan-note/siyuan#412]
1. When clicked the directory area(not icon),  expanding is better

2. When one-clicked the file(not double-click), showing the content is better

![siyuan](https://user-images.githubusercontent.com/15811943/97982992-eb8e8880-1e17-11eb-839a-e4211adb6a57.gif)

**Comment by orangee-wi** [comment]
**as follows**
![image](https://user-images.githubusercontent.com/37354425/97987413-35766f00-1e16-11eb-8ed9-4d1c043e3900.png)

**Comment by wbooooooo** [comment]
You can set one-click by yourself,in the Settings-File Tree-Open Files with Single Click

**Comment by jakekwak** [comment]
@wbooooooo thanks
