### ISSUE TITLE
清理未引用资源时未忽略 `custom-data-assets` 属性定义的资源文件

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4122]
### 描述问题 Describe the problem

如题

#3249 

### 期待的结果 Expected result

清理未引用资源时忽略 custom-data-assets 自定义属性所引用的数据文件

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/49649786/155932283-db380d62-0591-4859-a107-86d1ac42bcc4.png)

![image](https://user-images.githubusercontent.com/49649786/155932324-db8ebd4c-e3b7-4384-a060-cdfd6fc561ec.png)

### 版本环境 Version environment

* Version: 1.8.4
* Operating system: Windows 10 21H2 19044.1566

### 更多信息 More information

重建索引后清理未引用资源时依旧未忽略 custom-data-assets 自定义属性所引用的数据文件

**Comment by 88250** [comment]
属性名是 `data-assets`，没有 `custom-` 前缀 https://github.com/siyuan-note/siyuan/issues/1488

**Comment by 88250** [comment]
https://ld246.com/article/1654713832912

这里似乎有个历史数据兼容问题，我们两种属性名 `custom-data-assets` 和 `data-assets` 都用作保留资源文件使用吧。
