### ISSUE TITLE
复制网页内容时在任何情况下都会代入原格式

### ISSUE THREAD

**Issue by mingyuezhaowo** [siyuan-note/siyuan#4123]
### 描述问题 Describe the problem

从网页复制文本标题，粘贴到思源笔记中。
粘贴到链接的 [] 中时，会代入原标题格式。

### 期待的结果 Expected result
希望与 typora 一致：
如果粘贴到链接的 [] 中时，希望只复制文本；
插入到其他位置时再代入原格式。

现在的情况下需要先把文本级别去除，再粘贴，多了 2 步。

### 截屏或者录屏演示 Screenshot or screen recording presentation
![复制问题](https://user-images.githubusercontent.com/17918944/155947456-a4cb8032-1387-4218-a71e-e5ebb58453a4.gif)

### 版本环境 Version environment

* Version:  1.8.4
* Operating system: win10
* Browser (if used): 

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8151601/siyuan.log)

### 更多信息 More information

typora 是根据粘贴到不同位置决定是否代入原格式的。

**Comment by 88250** [comment]
试试 Ctrl+Shift+V 来粘贴纯文本。

**Comment by mingyuezhaowo** [comment]
> 试试 Ctrl+Shift+V 来粘贴纯文本。

Ctrl+Shift+V 是可以达到目的的，不过用过之后格式就被丢掉了。
相比之下，typora 的做法更好一些，更灵活。

**Comment by 88250** [comment]
试试划选文字以后 Ctrl+K 粘贴超链接：

![issue](https://user-images.githubusercontent.com/873584/156091726-18dd1a88-15bf-459c-a274-503f5edb454e.gif)

**Comment by mingyuezhaowo** [comment]
> 试试划选文字以后 Ctrl+K 粘贴超链接：

可用。
从网上复制东西时，会贴标题和超链接，标题和超链接并不是同一行，所以会单独粘贴。
如果先贴标题再用 ctrl + shift + v 不会有问题。
就是有时候顺序会反过来，就会出现贴完超链接后，复制的内容格式丢掉，需要手动加上或重新复制。
这时候，typora 的处理对于我来说容错性高一些。

不过问题不大，就是个人习惯不太适应，你提的这俩快捷键可以满足需求，标题格式也很好敲，我试试这套方案吧。

多谢
