### ISSUE TITLE
输入引用块优化

### ISSUE THREAD

**Issue by somata-cn** [siyuan-note/siyuan#4124]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
输入引用块时，如果将光标移动到文字中间，然后选中引用块，光标后方的文本不会被替换为引用块。

![siyuan_4](https://user-images.githubusercontent.com/40385591/155960634-fc16d4d9-43f8-4fc8-815d-66188615dd92.gif)

### 描述可能的最优解决方案 Describe the optimal solution
如果直接将后方文本替换为引用块，那么在一段文本中间使用引用块时，会导致后方所有文本被替换。

可以选择弹出窗口供用户输入引用块链接。

**Comment by 88250** [comment]
可以用划选关键字，然后 Alt+[ 触发搜索。
