### ISSUE TITLE
iOS 端标题块无法折叠/展开

### ISSUE THREAD

**Issue by netdog2019** [siyuan-note/siyuan#4126]
### 描述问题 Describe the problem
IOS端H1-6及标题无法折叠/展开

### 期待的结果 Expected result
IOS端的无序列表可以点击前面的图标弹出菜单，选择折叠/展开，但是H1-6及标题却无法折叠/展开，希望H1-6级标题也能折叠展开，最好是双击的形式折叠/展开，或者参考无序列表，点击前面的图标弹出菜单，选择折叠/展开。

**Comment by Vanessa219** [comment]
无法重现，还麻烦说一下重现步骤。

https://user-images.githubusercontent.com/970828/156097781-6b6b8900-a83b-4368-b62f-bd57183db11e.mp4

**Comment by netdog2019** [comment]
> 无法重现，还麻烦说一下重现步骤。
> 
>  1646104253025356.mp4

哦，我把右上角的图标点成眼睛的形状，可以弹出菜单折叠了。点成笔形的无法点击。谢谢。
