### ISSUE TITLE
移动端通过伺服下载某些主题后无法打开

### ISSUE THREAD

**Issue by Morganwan90** [siyuan-note/siyuan#4127]
在移动端打开网络伺服，通过电脑端下载主题后。
思源无法再开启，每次都闪退。

手机：华为
版本：1.8.5

**Comment by 88250** [comment]
和这里的反馈好像是一个问题 https://ld246.com/article/1646053146964

我们后续排查了看。

**Comment by Morganwan90** [comment]
> 和这里的反馈好像是一个问题 https://ld246.com/article/1646053146964
> 
> 我们后续排查了看。

好的~感谢D大V大

**Comment by 88250** [comment]
我这里按照这个步骤重现不了问题。

1. 开启移动端伺服
2. 从桌面浏览器进入集市下载主题 zhang-light
3. 移动端重新启动
4. 能够正常进入

**Comment by Morganwan90** [comment]
> 

还真是...看来是主题的问题...只有我的Dark Blue和Light Blue都不行.......但是我不知道是为啥....

**Comment by 88250** [comment]
大概定位到问题了，不能打开的主题是因为样式里用了 rgb 格式的颜色，这种格式的颜色解析会报错导致闪退。下个版本会试着修复解析，感谢反馈。

**Comment by Morganwan90** [comment]
吖~果然是~谢谢D大~
