### ISSUE TITLE
行内代码以及行内公式的编辑体验建议

### ISSUE THREAD

**Issue by Whisht** [siyuan-note/siyuan#4131]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
由于采用了Notion所见即所得的编辑方式，思源中对公式及代码的编辑有一些不自在。
* 对于行内代码： 比如 #3760 中描述的问题，无法在代码开头或结尾添加字符。此外在句中行内代码前添加代码会导致其他内容变成代码，如下图：
	* ![image](https://user-images.githubusercontent.com/16497652/156128330-c8e49f6f-0666-4b2c-bf21-fe786865aa1e.png)
而要使用 `Ctrl+G` 编辑的话又会需要选中要修改的代码，导致手离开键盘。
* 对于公式，也有如上问题。公式被视为一个整体，每次需要修改公式内容时，都需要选中单击一下公式，才能对公式进行修改，这需要增加操作步骤。而出现的修改框又会遮挡一部分的内容，不方便写作中思考。

个人觉得 Typora 中代码和公式的编辑体验更符合 Markdown 的方式，尽情写作，将格式化交给编辑器来做。

如上，请问未来是否有计划将代码和公式所见即所得的编辑方式向 Typora 的方式转换？

公式，代码，粗体等需要将文本置于特殊符号间的编辑操作。

### 描述可能的最优解决方案 Describe the optimal solution

Typora 中所见即所得的编辑方式。

**Comment by 88250** [comment]
你好，感谢反馈，但是目前暂时不会做调整了，抱歉抱歉。
