### ISSUE TITLE
建议直接内置drawio，不要使用挂件

### ISSUE THREAD

**Issue by Learces** [siyuan-note/siyuan#4134]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
本人程序员，笔记设计大量流程图，一直使用vscode的drawio插件，然后导出svg复制到思源里面，非常不方便，而且每次修改都需要从新导入，并且删除原来的图片。
我希望思源能够内置drawio，并能够直接在笔记里面渲染该文件。

### 描述可能的最优解决方案 Describe the optimal solution
请参考vscode的Draw.io Integration（Henning Dieterichs）插件。
但是这个插件在制图时的显示效果和导出的效果不一样，所以这里还需要调整。

**Comment by 88250** [comment]
你好，不建议挂件的原因能描述一下么？

**Comment by Learces** [comment]
挂件现在不能显示图像最终效果，关键的UI、辅助网格全部可见，非常影响美观，编辑好的图像也不方便调整居中。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 建议直接内置drawio，不要使用挂件 (Issue #4134)





 
你好，不建议挂件的原因能描述一下么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 88250** [comment]
明白了，主要是一些细节体验可能有点不好，可以试着给挂件作者反馈。

我们开发精力有限，所以暂时没法考虑内置，抱歉抱歉。

**Comment by Learces** [comment]
理解，其实现在先使用vscode或者挂件编辑好图像，然后导出为SVG，再复制进文档也行，只是流程相对繁琐。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 建议直接内置drawio，不要使用挂件 (Issue #4134)





 
明白了，主要是一些细节体验可能有点不好，可以试着给挂件作者反馈。
 
我们开发精力有限，所以暂时没法考虑内置，抱歉抱歉。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by realysy** [comment]
@Learces 参考 [https://github.com/ooooooook/widget-excalidraw/issues/13](https://github.com/ooooooook/widget-excalidraw/issues/13)，现在draw.io挂件已经支持笔记内显示渲染好的图片了：编辑模式下编辑好之后，选中挂件所在block，按空格即可

**Comment by crendy** [comment]
https://github.com/jgraph/drawio-integration/tree/master/webdav
用下图的框住的方式就是这种效果，看能把挂件按[embedded PNG)方式集成吗？

<img width="807" alt="image" src="https://github.com/user-attachments/assets/ab12c44e-b495-4c24-b4a5-0932c92aa8a4">
