### ISSUE TITLE
多扩展名后缀文件上传为资源文件时 ID 位置错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4136]
### 描述问题 Describe the problem

我将一个具有多个后缀的资源文件(`release.ini.tar.gz`)上传至资源文件夹后, 发现文件被重命名为 `release.ini.tar-20220302135013-ufh4ywx.gz`, 显然这个文件无法使用关联 `*.tar.gz` 文件的默认解压程序解压

### 期待的结果 Expected result

在所有后缀的前面插入文件 ID, 形如 `release-20220302135013-ufh4ywx.ini.tar.gz`

### 版本环境 Version environment

* Version: v1.8.5

**Comment by 88250** [comment]
文件扩展名只计算最后一个 `.` 后面的部分，所以对于 `abc.tar.gz` 来说扩展名是 `.gz`，文件名是 `abc.tar`，对于 tar gz 包最好使用 `.tgz` 作为扩展名。

这个还是以标准为准，所以不做调整了。
