### ISSUE TITLE
关于离线同步的需求，能否添加同步为相加模式的选择

### ISSUE THREAD

**Issue by sunerpy** [siyuan-note/siyuan#4137]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
工作笔记本日常情况连接办公网无法访问互联网，工作中记录的笔记需要离线记录，每周末会接入互联网同步（OneNote）。但是思源的笔记同步模式经个人测试应为云端下载覆盖模式，我在离线期间记录的笔记会被云端数据覆盖掉，而不是与此期间在线同步的数据相加。 测试客户端为：win客户端（离线）  安卓客户端（在线）

### 描述可能的最优解决方案 Describe the optimal solution
参考其他笔记的同步方式，在线期间同步上传到云端，当离线客户端接入互联网同步时将离线更新推送到云端，并从云端下载本地没有的数据，

wolai的飞行模式支持此同步方式

**Comment by 88250** [comment]
你好，我们之前考虑过，但是有技术问题解决不了，比如出现数据冲突时的情况。举个例子：两个设备上都离线修改了同一段内容，或者一个设备删除另一个设备修改同一段内容，这些情况下无冲突合并比较困难。

目前思源同步的方案是覆盖，并将被覆盖的数据放到历史里，这样能保证数据一致性，不会出现数据混乱或者丢失。

**Comment by sunerpy** [comment]
![image](https://user-images.githubusercontent.com/30691040/156388015-acf3e867-11e3-4db3-acfa-d75e7c57f432.png)

**Comment by 88250** [comment]
在笔记本的 history 文件夹里。

**Comment by sunerpy** [comment]
谢谢回复   那我先按照这种方式使用吧

**Comment by 88250** [comment]
谢谢，我关闭了。
