### ISSUE TITLE
微软商店版任务栏图标问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4139]
https://ld246.com/article/1646268725965

**Comment by philhappy** [comment]
![image](https://user-images.githubusercontent.com/77133643/156499430-1a6a8088-a797-47ec-930d-4c6e470e00fd.png)
英文官网【未对齐】

**Comment by 88250** [comment]
@philhappy 刚刚更新了下，请再帮忙看下是否已经对齐。

**Comment by philhappy** [comment]
> @philhappy 刚刚更新了下，请再帮忙看下是否已经对齐。

D  is the sun in my world,OK了

**Comment by philhappy** [comment]
> @philhappy 刚刚更新了下，请再帮忙看下是否已经对齐。

D is the sun in my world,OK了

**Comment by 88250** [comment]
v1.8.8 上架完毕，目测已经修复该问题了。
