### ISSUE TITLE
复制块到表格触发状态异常

### ISSUE THREAD

**Issue by ziyue7575** [siyuan-note/siyuan#4141]
### 描述问题 Describe the problem

将只要一行的代码复制到表格的时候会内核崩溃。
![71L@7HM_NY7YVY)QPV}N~AS](https://user-images.githubusercontent.com/40845658/156529238-ee5c3838-c8d5-48b1-a865-602c3e20ca11.png)
测试发现将代码的块复制到表格就会崩溃
![image](https://user-images.githubusercontent.com/40845658/156529347-425ff50c-0e8e-4513-bb19-0f62e9194e13.png)

### 版本环境 Version environment

v1.8.6

**Comment by 88250** [comment]
发现其他块复制到表格也有类似问题，在这个 issue 中一并修复。

**Comment by 88250** [comment]
表格无法包含块级元素，只能粘贴行级元素。
