### ISSUE TITLE
文档树的文档Delete无法删除

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4145]
### 描述问题 Describe the problem

在文档树面板，笔记本可以按Delete删除，但是文档不一定行。

点击文档时，文档打开了，然后光标到了右边编辑区。此时按Delete只能删除文本内容。

但是，F2重命名却有效。

### 期待的结果 Expected result
点击文档树的文档时，文档可以打开，但是焦点需保持在文档树这边。如果需要编辑文档，需要在编辑区点一下。你不点这一下直接输入，也不确定当前光标在哪里吧。

### 版本环境 Version environment

* Version: 1.8.5
* Operating system: Win10
* Browser (if used):

**Comment by 88250** [comment]
这个交互应该比较符合大部分编辑场景，如果要使用键盘操作的话，可以用 Alt+1 然后上下键选择后 Delete。
