### ISSUE TITLE
大纲无法显示引用内部的标题

### ISSUE THREAD

**Issue by Learces** [siyuan-note/siyuan#4147]
### 描述问题 Describe the problem
![image](https://user-images.githubusercontent.com/94371988/156681675-f45e6288-33c9-47db-bacc-b2472c52b66c.png)

### 期待的结果 Expected result
虽然这个写法很奇怪，但是我还是希望能够支持

### 截屏或者录屏演示 Screenshot or screen recording presentation
（详见描述问题）

### 版本环境 Version environment

* Version: 1.8.6
* Operating system: windows 11
* Browser (if used):  N/A

**Comment by 88250** [comment]
引述块里的标题块不会计入大纲的。
