### ISSUE TITLE
Chrome extension can not clip equations rendered by MathJax

### ISSUE THREAD

**Issue by Lemoners** [siyuan-note/siyuan#4149]
### 描述问题 Describe the problem

I have been trying to make a clip of a [web page](https://agustinus.kristia.de/techblog/2018/03/14/natural-gradient/), which has integrated equations like this:
![image](https://user-images.githubusercontent.com/39124095/156719958-bf91e7bc-2a63-4f0e-b165-fb9b692c807a.png)

I think it's rendered with MathJax, and I suppose that it should be clipped properly, because if I copy the latex and paste them to Siyuan, it can be rendered correctly.

However, here's the result I got from the web extension:
![image](https://user-images.githubusercontent.com/39124095/156720710-331efcd9-bbd8-49f9-9dc4-fb4dcbbedfb8.png)

### 期待的结果 Expected result

![image](https://user-images.githubusercontent.com/39124095/156720522-7ebc74b6-54e1-442e-ad8f-f8790a53028d.png)

### 版本环境 Version environment

* Version: 1.8.5
* Operating system: Windows
* Browser (if used): 1.0.1

**Comment by 88250** [comment]
Hello, we have seen that this may not be possible because the formula has been rendered on the webpage, the rendering algorithm seems to be irreversible, and the original plain text of the formula cannot be obtained.

Thanks for the feedback, we have closed this issue.
