### ISSUE TITLE
复制行内代码会一同复制前后反引号

### ISSUE THREAD

**Issue by Hazx** [siyuan-note/siyuan#4153]
### 描述问题 Describe the problem

复制行内代码会一同复制前后反引号。
例如，在编辑器中复制行内代码 `TEST` （完整复制），在别处粘贴时则会粘出 \`TEST\`。
这样虽然比较方便文档的编辑，但在文档笔记的使用中存在诸多问题。
比方说，在笔记中使用行内代码记录了服务器的用户名、密码以及其他信息。从笔记中复制内容，直接粘贴到终端中就会出错（因为多了两个字符）。非常影响使用。

### 期待的结果 Expected result

完整复制行内代码时，仅复制内容，不带前后反引号。
例如完整复制 `TEST`，在粘贴时只有 TEST。

### 截屏或者录屏演示 Screenshot or screen recording presentation

笔记中的内容：↓

![1](https://tva2.sinaimg.cn/large/a183a0f1ly1gzxx7puk5ij208902r0sj.jpg)

使用笔记内容时，复制出来的内容：↓

![2](https://tva2.sinaimg.cn/large/a183a0f1ly1gzxx7pvq6dj206f02ljr7.jpg)

### 版本环境 Version environment

* Version: v1.8.6
* Operating system: Windows 10 21H2

**Comment by 88250** [comment]
复制是以 Markdown 格式复制的，所以会带有反引号等标记符。

可以试下双击 TEST（不要用划选）来复制。

**Comment by Hazx** [comment]
> 复制是以 Markdown 格式复制的，所以会带有反引号等标记符。
> 
> 可以试下双击 TEST（不要用划选）来复制。

双击会选中代码后的空格（如果有）。
并且当行内代码中存在特殊字符，双击并不会全选行内代码内容。
![1](https://tva2.sinaimg.cn/large/a183a0f1ly1gzxxq8fz4bj20920423yc.jpg)
