### ISSUE TITLE
页面卡顿的问题

### ISSUE THREAD

**Issue by hzjsea** [siyuan-note/siyuan#4154]
长时间应用下来，其他的功能都蛮好的，就是会遇到如下两个卡顿的问题
- 当页面量内容过多的时候，在点击左侧的目录树切换小标题的时候会出现长时间的卡顿问题，既然思源是存在本地的话应该不会这么卡吧，是否可以优化，一篇文档的字数为34359个字 4-5张图片，多个代码块，如果有需要我可以提供原文档做测试
- 代码块中书写内容的时候会出现卡顿，比方说我复制了一段20行左右的代码复制在思源上，然后我在代码块里写注释的时候就会出现卡顿

**Comment by 88250** [comment]
麻烦试下代码块关闭行号以后是否还卡。

**Comment by Vanessa219** [comment]
麻烦提供一下第一个问题的 .sy 文件

**Comment by hzjsea** [comment]
> 麻烦提供一下第一个问题的 .sy 文件

```bash
curl https://transfer.sh/FoRPln/backup.sy -o xx.sy
```

貌似是和上面的处理方式是一样的，关闭代码块行号以后就不卡了

**Comment by hzjsea** [comment]
> 麻烦试下代码块关闭行号以后是否还卡。

是的 在关闭代码块行号以后，上面两个问题似乎都解决了

**Comment by 88250** [comment]
这个问题暂时没法解决，因为开启行号以后，每一行的高度都要进行即时渲染计算用于折行处理。

后期我们打算更换代码编辑器 https://github.com/siyuan-note/siyuan/issues/3141 这个还在计划中，我关闭了，感谢反馈。
