### ISSUE TITLE
新建文档时，随机生成一个emoji图标

### ISSUE THREAD

**Issue by ameigancai1** [siyuan-note/siyuan#4156]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

新建一个文档时。

### 描述可能的最优解决方案 Describe the optimal solution

建议设置添加一个开关，开启时，每次新建文档的时候，可以随机生成一个emoji图标。

### 描述候选的解决方案 Describe the candidate solution

暂无

### 其他信息 Other information

谢谢

**Comment by 88250** [comment]
暂时还是用默认的，随机的可能不会好看，感谢提议。
