### ISSUE TITLE
可否在代码块处新增一个换行的功能？

### ISSUE THREAD

**Issue by ohyessir** [siyuan-note/siyuan#4158]
有的时候需要使用代码块   ```   对发送的数据包进行记录，但是有些数据包里面的url或者参数的值特别长，浏览的时候就得往后拉，可否加一个换行的开关？？？谢谢  麻烦了

**Comment by UltramarineSky** [comment]
设置里面有`设置-编辑器-代码块换行`

**Comment by ohyessir** [comment]
谢谢看到了，不好意思打扰了

**Comment by Zuoqiu-Yingyi** [comment]
@ohyessir 代码块的块菜单中可以只设置某一个代码块的自动换行
