### ISSUE TITLE
块元素支持悬浮和全屏操作

### ISSUE THREAD

**Issue by jpanda-cn** [siyuan-note/siyuan#4160]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在使用挂件时,有很多挂件全屏体验会更好,比如现有的挂件,luckysheet, Excalidraw等

这种类型的挂件受限于iframe自己的大小,使用体验其实并不好,因为窗口太小,导致无法有效的展示内容,使得用户很难拥有一个理想的编辑体验,基于同样的原因,在完成编辑之后,去查看挂件内容时,也需要通过拖拽现有挂件的块调整大小,来查看其中存储的内容.

因此,为了减少这种阻断体验,提升用户的感受,更好的方式是让**挂件所属的块能够全屏展示**.

在前面的基础上,衍生出一个新的优化体验: **允许块元素支持浮窗展示**,类似于Always On Top这种理念,举例说明,当我编写了一个PlantUml的时序图之后,后续大概率我会针渲染出的图形内容,来进行更细致的介绍.

这个介绍可能会跨域一屏的高度,这就会导致,后面我编写内容时,需要滚动到PlantUml对应的块,查看内容后,再继续编写笔记.

一个很好的解决方案就是,允许用户针对某一个块进行 Always On Top 操作.这种浮窗类型的支持可以很好的提升用户的编写体验.

### 描述可能的最优解决方案 Describe the optimal solution

关于**挂件所属的块能够全屏展示**这个特性,我查看了notion的实现,目前notion针对多媒体类型和iframe是支持全屏展示的:
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/50101020/156885360-690655b2-42bd-4305-a789-66537f0fc958.png">

不过,我能够想到的最优实现,更接近于一个支持全屏操作的浮窗操作,灵活性更强,当然实现也要比简单的全屏要复杂一些.

考虑到[D大](https://github.com/88250)关于[编辑器挂件槽](https://github.com/siyuan-note/siyuan/issues/3862)的特性设计,是否可以进一步的考虑允许用户将块元素的浮窗放置到插槽中.

### 描述候选的解决方案 Describe the candidate solution

之前在编写挂件时,遇到过类似的问题,挂件本身占用空间不大,但是他的辅助功能占用的空间比较大,比如: 挂件的配置窗口,当时考虑的方案是希望有一个API可以触发思源自带的浮窗或者模态框,但这种设计首先需要挂件开发者额外去对接一个新的API,同时和前面提到的方案对比来说,成本更好,体验感也要稍差一些.

**Comment by 88250** [comment]
挂件后续的路线是支持[挂件面板](https://github.com/siyuan-note/siyuan/issues/3689)，更进一步通过[浮动窗口](https://github.com/siyuan-note/siyuan/issues/3499)应该能达成你所描述的应用场景。

我关闭了，感谢提议。
