### ISSUE TITLE
希望能为文件夹设置新建笔记的默认模板

### ISSUE THREAD

**Issue by QiuMP** [siyuan-note/siyuan#4161]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在某一分类文件夹内创建文档的时候，经常会使用同一个模板，希望能够将该操作自动化

### 描述可能的最优解决方案 Describe the optimal solution

能够为文件夹设置默认使用的笔记模板，在这个文件夹内新建笔记则自动使用该模板

**Comment by 88250** [comment]
这个过于定制化，暂时不会考虑，如果非常需要，可以考虑通过 Quicker 等外部工具联动 API 达成，谢谢。
