### ISSUE TITLE
代码块编辑出现抖动

### ISSUE THREAD

**Issue by checkwoodson** [siyuan-note/siyuan#4164]
### 描述问题 Describe the problem
使用使用代码块功能出现抖动，既在代码块内输入代码会抖动。

### 期待的结果 Expected result
不能抖动，而且也能合理存在提示。

### 版本环境 Version environment

* Version: 1.8.7
* Operating system:  windows
* Browser (if used):

**Comment by royc01** [comment]
![A](https://user-images.githubusercontent.com/38906705/156908536-6e0cbf67-d015-42be-a633-04431e3a15ac.gif)

**Comment by checkwoodson** [comment]
不光是抖动，而且也没有括号闭合的功能了。

**Comment by checkwoodson** [comment]
对了，还有一个tab的间隔很长，一般来说两个就ok了吧。 希望赶快修复。

**Comment by Vanessa219** [comment]
tab 的空格数目可在设置中进行配置。
