### ISSUE TITLE
折叠标题后未触发动态加载

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4168]
如录屏所示，我的文档有三个H2标题，大纲可见。
利用小三角折叠时，最后一个H2标题不见了。在大纲点一下又出来了。
![小三角bug](https://user-images.githubusercontent.com/5968678/156910541-32cee1ed-b08b-40b3-8280-650a287732d9.gif)

我尝试创建一个简单的文档来复现，但复现不出来。
所以我把这个md也传给你们测试，导入思源即可。
[测试小三角bug.md](https://github.com/siyuan-note/siyuan/files/8191998/bug.md)

Win10+v1.8.7

**Comment by HowcanoeWang** [comment]
MacOS和windows在最新版也遇到，长文档中，一大段块消失的情况

不过我这个是鼠标往下滚动，滚着滚着卡一下，然后跳到了好几段文字之后，然后再往上滚，之前显示的内容也消失了

**Comment by 88250** [comment]
@HowcanoeWang 我们先解决楼主提的问题，你反馈的这个不确定是不是一个问题，等这个 issue 关闭发版以后麻烦再看看，谢谢。
