### ISSUE TITLE
表格中行内代码后换行问题

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4169]
表格中，行内代码后回车，然后接着输入内容，会出现换行失败，且前面的行内代码末尾会出现`<br />`：
![表格中行内代码后换行](https://user-images.githubusercontent.com/5968678/156910854-cfa554a3-5b0c-4f3f-ba81-7b64f9bb8cec.gif)

Win10 + v1.8.7/6

**Comment by 88250** [comment]
我这里重现不了……

![issue](https://user-images.githubusercontent.com/873584/156919098-8830117d-e8d7-41d7-8cf0-31136261529f.gif)

**Comment by whuwangyong** [comment]
> 

因为你这是`Ctrl+'` 键盘，我是`Ctrl+G`行内代码呀~

**Comment by whuwangyong** [comment]
> 我这里重现不了……
> 
> ![issue](https://user-images.githubusercontent.com/873584/156919098-8830117d-e8d7-41d7-8cf0-31136261529f.gif)

因为你这是`Ctrl+'`键盘，我是`Ctrl+G`行内代码呀~

**Comment by 88250** [comment]
抱歉抱歉，我看错了 🙏 确实有问题。
