### ISSUE TITLE
使用 iframe 块嵌入挂件时部分操作会触发选中块并导致运行时异常

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4172]
### 描述问题 Describe the problem

使用 iframe 嵌入挂件时(复现过程中资源设置为 `widgets/url-scheme`)
1. 若鼠标多次单击 iframe 内非空的 `input` 元素时会选中该 iframe 块
2. 在 iframe 内空的 `input` 元素中使用中文输入法(QQ拼音输入法)单击一个字母后使用数字键选字, 会选中该 iframe 块
3. 在 iframe 内空的 `input` 元素中使用中文输入法(QQ拼音输入法)单击一个字母后再单击一个字母, 会删除当前 iframe 块与上方部分相邻段落, 之后的撤销操作会出现运行时异常(该文档打开后未进行任何编辑操作时可复现), 日志详见 **问题 3 日志**
4. 若 3 中 iframe 块的上方没有其他块, 不会出现删除, 但 iframe 块样式出现问题, 同时块菜单失效, 日志详见 **问题 4 日志**

### 期待的结果 Expected result

焦点位于 iframe 中时, 任何事件都被 iframe 捕获, 并不会向上传递

### 截屏或者录屏演示 Screenshot or screen recording presentation

1. ![思源笔记-bug反馈-10](https://user-images.githubusercontent.com/49649786/156911420-372d2768-15d5-4c2e-9115-c1088f775b5a.gif)
2. ![思源笔记-bug反馈-11](https://user-images.githubusercontent.com/49649786/156911450-d6d33318-936f-4e93-b166-774c4575f5fb.gif)
3. ![思源笔记-bug反馈-12](https://user-images.githubusercontent.com/49649786/156911655-30395d69-3a2c-4b8b-add3-25fc5578aa94.gif)
4. ![思源笔记-bug反馈-13](https://user-images.githubusercontent.com/49649786/156911988-efe3ad92-17b2-4683-89fb-ff1bd498b08f.gif)

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used): 

##### 内核日志

```log
I 2022/03/06 14:08:11 database.go:72: reinitialized database [D:\Notebook\Siyuan\workspace\temp\siyuan.db]
I 2022/03/06 14:08:11 index.go:204: rebuilt database for notebook [20210808180117-czj9bvb] in [0.25s], tree stat [count=49, size=1.0 MB]
I 2022/03/06 14:08:11 index.go:204: rebuilt database for notebook [20211117210244-rd7a3f9] in [0.05s], tree stat [count=5, size=378 kB]
I 2022/03/06 14:08:13 index.go:204: rebuilt database for notebook [20210917000226-w9fa32i] in [1.22s], tree stat [count=85, size=1.1 MB]
I 2022/03/06 14:08:13 index.go:204: rebuilt database for notebook [20210916152511-9ihqyfi] in [0.54s], tree stat [count=122, size=3.2 MB]
I 2022/03/06 14:08:17 index.go:204: rebuilt database for notebook [20210918102434-mtrd8yr] in [2.52s], tree stat [count=884, size=11 MB]
I 2022/03/06 14:08:18 index.go:204: rebuilt database for notebook [20211202140059-zm0xt6u] in [0.05s], tree stat [count=9, size=8.4 kB]
I 2022/03/06 14:08:18 index.go:204: rebuilt database for notebook [20211203004753-8okas3v] in [0.04s], tree stat [count=5, size=23 kB]
I 2022/03/06 14:08:18 index.go:204: rebuilt database for notebook [20211204012232-tfejc3a] in [0.14s], tree stat [count=46, size=403 kB]
I 2022/03/06 14:08:18 index.go:204: rebuilt database for notebook [20210914201520-i0v92g9] in [0.26s], tree stat [count=95, size=1.8 MB]
I 2022/03/06 14:08:18 index.go:214: resolving refs...
I 2022/03/06 14:08:19 index.go:354: resolved refs [3055]
E 2022/03/06 14:12:54 transaction.go:947: update data is nil
```

##### Web 控制台日志

```log
main.f73cf3084fa173296595.js:1 addRange(): The given range isn't in document.
t.focusByRange @ main.f73cf3084fa173296595.js:1
t.focusBlock @ main.f73cf3084fa173296595.js:1
t.onTransaction @ main.f73cf3084fa173296595.js:1
(anonymous) @ main.f73cf3084fa173296595.js:1
render @ main.f73cf3084fa173296595.js:1
undo @ main.f73cf3084fa173296595.js:1
(anonymous) @ main.f73cf3084fa173296595.js:1
```

##### Web 控制台日志

```log
main.f73cf3084fa173296595.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'outerHTML')
    at main.f73cf3084fa173296595.js:1
    at Generator.next (<anonymous>)
    at main.f73cf3084fa173296595.js:1
    at new Promise (<anonymous>)
    at i (main.f73cf3084fa173296595.js:1)
    at t.input (main.f73cf3084fa173296595.js:1)
    at HTMLDivElement.<anonymous> (main.f73cf3084fa173296595.js:1)
(anonymous) @ main.f73cf3084fa173296595.js:1
(anonymous) @ main.f73cf3084fa173296595.js:1
i @ main.f73cf3084fa173296595.js:1
t.input @ main.f73cf3084fa173296595.js:1
(anonymous) @ main.f73cf3084fa173296595.js:1
```

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 在 `v1.9.1` 中该 bug 又出现了, 而且同时出现在挂件块与 iframe 块中
![image](https://user-images.githubusercontent.com/49649786/158810927-61d19af5-1e32-4f86-98fe-3a4ea63bc128.png)

**Comment by Vanessa219** [comment]
我这里重现不了

https://user-images.githubusercontent.com/970828/158812704-ddd1418e-f789-4a10-9686-be7231908ae8.mp4

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里重现不了

![思源笔记-bug反馈-18](https://user-images.githubusercontent.com/49649786/158813412-634adfc9-9816-4f5a-ac9d-694d61115df9.gif)

输入框内有内容时双击输入框后单击 `backspace` 键试试, bug 3 可能也是因为该原因

**Comment by Vanessa219** [comment]
又修改了下，就不新建 issue 了。还麻烦下个版本再看看。

**Comment by Zuoqiu-Yingyi** [comment]
> 又修改了下，就不新建 issue 了。还麻烦下个版本再看看。

目前看没有问题了🎉🎉🎉
