### ISSUE TITLE
选中图片后输入下一行，图片依然是选中状态

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#4173]
![b](https://user-images.githubusercontent.com/38906705/156913278-0af5225b-6c56-46aa-82b4-e2e4f0b03307.gif)
这是输入下一行后进行backspace操作，会把图片删掉

**Comment by HowcanoeWang** [comment]
联系这个bug https://github.com/siyuan-note/siyuan/issues/4179
这边删掉之后，有一定概率ctrl+z图片恢复不回来
