### ISSUE TITLE
关于SQL查询的建议

### ISSUE THREAD

**Issue by zuojianz** [siyuan-note/siyuan#4174]
## 现状
目前使用SQL语句进行查询的时候from前的子句好像只能写 "select * from  ...."，然后通过条件进行过滤查找

## 建议
1. 希望可以在select后面支持添加显示的具体字段
2. 比如可以查找某个笔记本下面的所有文件的列表，或者某个文档中的部分内容
```sql
select name from  blocks  
select h1 from blocks
```

**Comment by 88250** [comment]
这个只能通过挂件实现，因为编辑器需要完整的字段才能保证一致性。

**Comment by zuojianz** [comment]
> 

现在有现成的挂件吗？

**Comment by 88250** [comment]
试试这个 https://github.com/Zuoqiu-Yingyi/widget-query
