### ISSUE TITLE
为代码添加短描述

### ISSUE THREAD

**Issue by Learces** [siyuan-note/siyuan#4175]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
比如在做Spring框架笔记时，需要在笔记当中记录多个文件的代码，为了区分，要为代码块添加上文件名。

### 描述可能的最优解决方案 Describe the optimal solution
在左上角可以为添加代码块添加一段短描述

**Comment by 88250** [comment]
可通过备注实现。
