### ISSUE TITLE
复制块为引用块，字数多一点的话会有省略号，可否直接显示完整内容？

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#4177]
![image](https://user-images.githubusercontent.com/56879067/156926415-5ab69c45-399c-4b75-8efb-2b335830b8bf.png)
![image](https://user-images.githubusercontent.com/56879067/156926424-54dea912-1987-4943-afea-d7db39cda0ca.png)

**Comment by 88250** [comment]
设置 - 编辑器 - 块引动态锚文本最大长度
