### ISSUE TITLE
块属性备注栏 Ctrl+Z 撤销不撤销备注栏内容而撤销文档内容

### ISSUE THREAD

**Issue by Learces** [siyuan-note/siyuan#4179]
### 描述问题 Describe the problem
在代码块备注栏里面进行撤销动作不会撤销备注栏内容，而是会撤销文本内容。

### 期待的结果 Expected result
能直接撤销备注栏的内容

### 版本环境 Version environment

* Version: v1.8.7
* Operating system: Windows 11
* Browser (if used):

**Comment by Vanessa219** [comment]
备注中的内容暂时无法支持撤销
