### ISSUE TITLE
【咨询】有计划发布一个支持渲染为html的npm包吗

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#418]
我打算使用思源笔记作为我博客的文档编辑工具

而我的博客原本是直接从 md 渲染为 html ，现在使用思源笔记想得到比较好的渲染体验（id不显示以及块引用的正确渲染）

**Comment by 88250** [comment]
请参考 https://github.com/88250/lute 以及 https://github.com/Vanessa219/vditor

**Comment by 2234839** [comment]
已得到结果 https://github.com/88250/lute
