### ISSUE TITLE
微软商店版本的任务栏图标太丑, 建议替换掉

### ISSUE THREAD

**Issue by mingyuezhaowo** [siyuan-note/siyuan#4181]
### 描述问题 Describe the problem

微软商店版本的任务栏图标太丑。

### 期待的结果 Expected result

任务栏图标可以采用桌面图标这种正常的。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![任务栏图标](https://user-images.githubusercontent.com/17918944/156977663-fd6df242-35d1-4572-aeac-dabca2a5f886.PNG)

### 版本环境 Version environment

* Version: 1.8.7
* Operating system: win10
* Browser (if used): 

### 日志文件 Log File

NA

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/4139
