### ISSUE TITLE
免费提供一个月的订阅试用

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4186]
存储空间限制 128M。

**Comment by Belf-hu** [comment]
D大，这个同步再免费，你真是在做慈善了，256M一般来说都够用了。

**Comment by netdog2019** [comment]
免费的话，可以考虑限制登陆的终端数量，参考大象。

**Comment by JokeenZhang** [comment]
真的不会有财务上的压力吗😂

**Comment by 88250** [comment]
目前只是初步想法，最快也要等永久会员活动结束以后才会有所进展。

**Comment by WolkeAtreide** [comment]
确实这么做真是是慈善了，我用这么久算上25M图片才50M

**Comment by whzecomjm** [comment]
我觉得可以先让新用户免费试用一个月之类的就可以，后面感觉好应该都会付费支持的吧~

**Comment by 88250** [comment]
> 我觉得可以先让新用户免费试用一个月之类的就可以，后面感觉好应该都会付费支持的吧~

这个方案也在考虑中，等过段时间再决定，感谢提议。

**Comment by JCJC01** [comment]
那么好的软件，付费就完事；
siyuan不是入门版笔记软件，所以决定留下来的都是有点笔记经验的玩家，大家都懂得同步的重要性，所以感觉可以换个思路，免费可以，但是不需要那么长时间，可以缩短成1周，然后容量可以大点。大家只是想测试稳定性和速度而已，没有必要一个月，他觉得好用，一周就足够体验，不想定，你给他一年都不会订。但是容量为啥建议大点呢？就是让使用者测试稳定性和速度

**Comment by 88250** [comment]
@JCJC01 有道理，感谢建议。

**Comment by 88250** [comment]
@WolkeAtreide 你说得也有道理，先感谢了，我们会再考虑的。

**Comment by 88250** [comment]
经过考虑，我们决定推出一个月的免费订阅试用，感谢各位的建议和讨论。

**Comment by ijrou** [comment]
其实可以弄一个白嫖vip的功能，这样粘性上来后，会付费的人自然付费，不付费的自然还是继续白嫖继续黏

**Comment by WolkeAtreide** [comment]
> 其实可以弄一个白嫖vip的功能，这样粘性上来后，会付费的人自然付费，不付费的自然还是继续白嫖继续黏

这就有个度的问题，参考微信读书。

**Comment by aptexd** [comment]
介于思源这种双链笔记目前上手成本还有点高，我觉得
1. 如果用限制容量的方式，过一阵其实完全可以“容量再小点，直接免费开放”，充分上手
2. 一个月试用期，还限制容量没很大必要，不如索性就给1个月8G，过期后提醒，再不行就删了
