### ISSUE TITLE
Shift+Tab取消列表缩进时内容移位

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4187]
![shift+tab列表异常](https://user-images.githubusercontent.com/5968678/157076943-4435344d-894e-48fd-ae65-de74868c5cbc.gif)

预期的结果：1以及下面的1.1、1.2应该仍在在前面，不应该到2.1、2.2后面去。

Win10+1.8.7

**Comment by 88250** [comment]
这是列表大纲的特性，列表项降低级别以后会移到下面，顶层列表项降低级别以后变为普通段落。

**Comment by whuwangyong** [comment]
> 顶层列表项降低级别以后变为普通段落。

是变为普通段落，但是为什么要移到最后呢。假如我有一个长度为100的列表，然后我把第一项变为段落，我还是希望他在原来的位置，而不是自动跑到末尾去了，我还得去最后剪切过来。其他编辑器如 Typora 也不是这个逻辑。
这样做可能会麻烦一些：如果我把中间一项变为普通段落，这个列表大纲就成为三部分了：前列表+段落+后列表。
