### ISSUE TITLE
文件树外部操作变动监听

### ISSUE THREAD

**Issue by 11001010** [siyuan-note/siyuan#419]
![77D14283-3257-4de2-96B3-ED6458E6D737](https://user-images.githubusercontent.com/58500946/98090493-0bc55280-1ebf-11eb-8085-701a99dd9161.png)

我在文件浏览器里面，进行新增文件、文档，或者删除文件、文档， 思源软件里面可不可以进行提供一个类似idea的功能，从新从桌面加载一下，而不是需要重启【思源】

**Comment by zZ-10** [comment]
![image](https://user-images.githubusercontent.com/58500946/98090315-d456a600-1ebe-11eb-8509-b7b25949b2bb.png)

**Comment by 88250** [comment]
感谢建议， 外部操作现在都没有做同步监听，这一块估计要后面一些才会动过，请见谅。

**Comment by 88250** [comment]
计划通过手动刷新来支持，请关注 https://github.com/siyuan-note/siyuan/issues/794
