### ISSUE TITLE
分屏时页面乱跳

### ISSUE THREAD

**Issue by JOYCELEEEEE** [siyuan-note/siyuan#4191]
### 描述问题：分屏后，点击页面或将鼠标移至页面上方，页面会上下跳动

有时将鼠标移至页面上方，页面可能一直跳动直至鼠标移开

### 截屏或者录屏演示

https://user-images.githubusercontent.com/89592448/157177685-77107ee3-183a-4668-bf27-7c67f839a255.mp4

### 版本环境 

1.8.8
windows

### 日志文件

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8203212/siyuan.log)

**Comment by 88250** [comment]
麻烦使用默认主题进行测试，如果没有问题的话请将该问题反馈给主题仓库，谢谢。
