### ISSUE TITLE
合并表格出现的问题

### ISSUE THREAD

**Issue by JOYCELEEEEE** [siyuan-note/siyuan#4192]
### 描述问题 合并表格时会将表格中的文字全部加粗，无法取消

记得表格最顶上的一排是默认加粗的，现在看起来在这种合并情况下思源似乎将所有的内容都当成了表头

### 截屏或者录屏演示 

<img width="649" alt="Snipaste_2022-03-08_14-30-34" src="https://user-images.githubusercontent.com/89592448/157180821-41f984f4-f7b4-4b21-b653-5646b37a5cd9.png">

### 版本环境 Version environment

1.8.8
windows

### 日志文件
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8203356/siyuan.log)

**Comment by 88250** [comment]
如果合并单元格包含了表头行，那么合并结果就是多行都变成表头了。

**Comment by JOYCELEEEEE** [comment]
仅合并表头 表头下方的内容也会变成表头似乎不太合理呀..

https://user-images.githubusercontent.com/89592448/157383612-4f9a5a0c-bd82-4013-8b1e-7d2e02a67806.mp4

.

**Comment by JOYCELEEEEE** [comment]
仅合并表头 表头下方的内容也会变成表头似乎不太合理呀.

https://user-images.githubusercontent.com/89592448/157384055-171d5940-da05-481b-b8ec-ab52cdb0022d.mp4

.

**Comment by JOYCELEEEEE** [comment]
还有这种情况

https://user-images.githubusercontent.com/89592448/157385236-553005b7-6402-4db0-914f-8b7fbe325c93.mp4

**Comment by 88250** [comment]
这两种情况都是列上面合并的表头。
