### ISSUE TITLE
引用文档时锚文本没有跟随文档重命名

### ISSUE THREAD

**Issue by P4nda0s** [siyuan-note/siyuan#4193]
### 描述问题 Describe the problem
引用块标题有时候会与引用目标文档不一致，引用块标题显示”新文档“，实际文档标题已经修改，刷新后无效。

文档都是通过 /新建文档  命令创建的，概率性发生

非常影响使用。

### 期待的结果 Expected result
引用块标题保持与文档标题一致。

![image](https://user-images.githubusercontent.com/9513384/157198788-fdf8f772-2170-453d-9216-202ebb890227.png)

没有定义锚文本
![image](https://user-images.githubusercontent.com/9513384/157198913-fce596c3-54fc-4d26-9c68-6eb74f646f68.png)

### 版本环境 Version environment

* Version: 1.8.2
* Operating system: Windows
* Browser (if used):

**Comment by 88250** [comment]
请升级到最新版，重建索引后再观察。

我们先关闭，如果还有问题欢迎随时跟帖。

**Comment by P4nda0s** [comment]
仍然存在该问题

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/157266439-98ad11c8-dfb4-4995-8888-8c7b636fe377.gif)

我这里重现不了问题，如果可以的话请制作一个能够重现问题的最小数据集发送给我们 845765@qq.com 并进行录屏演示重现，非常感谢。

**Comment by P4nda0s** [comment]
视频
[2022-03-08 23-48-03.zip](https://github.com/siyuan-note/siyuan/files/8207611/2022-03-08.23-48-03.zip)

随便用 /新建文档 创建三个页面后刷新就可以复现。

**Comment by 88250** [comment]
感谢帮忙定位问题，会在近期版本修复。

**Comment by 88250** [comment]
修复以后需要稍微等待一下（大概 3s）后再刷新，或者等着界面自动刷新，应该能正常工作。
