### ISSUE TITLE
Ctrl+A全选所有块之后，此时的输入不会替换原有内容

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4194]
一般的编辑经验：Ctrl + A 全选，然后粘贴新内容进来。预期是旧内容会被删除，然后写入新的内容。

思源的编辑器在全选之后，光标依然处于输入状态，此时直接输入或者粘贴，将不会删除原有内容。

如果要删除，需按Backspace或者delete，然后再输入。

**Comment by 88250** [comment]
这个是设计如此，选择以后输入不会覆盖。
