### ISSUE TITLE
思源笔记-代码块输入时光标总是跳转到了最后

### ISSUE THREAD

**Issue by running-bugs** [siyuan-note/siyuan#4196]
### 描述问题 Describe the problem
思源笔记 v1.8.8
代码块输入时光标总是跳转到了最后

### 录屏

https://user-images.githubusercontent.com/36567382/157247205-0ee6d6ef-4f31-4030-83d9-2102c023f800.mp4

**Comment by 88250** [comment]
感谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/4190
