### ISSUE TITLE
优化数学公式、图表等渲染块编辑窗的弹出方式

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4199]
https://ld246.com/article/1646789631336

**Comment by choyy** [comment]
编辑窗初始弹出位置会遮挡公式：

https://user-images.githubusercontent.com/68107073/157443201-2e012f45-b0ff-464b-815b-936ea6bc0a66.mp4

**Comment by choyy** [comment]
![图片](https://user-images.githubusercontent.com/68107073/157444306-e89621ec-09a0-4d82-9d64-43c26067d92d.png)
像这种都会遮挡一点点，感觉可以再往下一点

**Comment by Vanessa219** [comment]
ok

**Comment by Vanessa219** [comment]
呃，你这个主题叫什么？我这里默认主题是好的。

**Comment by choyy** [comment]
Tsunduku Dark
不过我这里默认主题还是一样啊：

https://user-images.githubusercontent.com/68107073/157456437-8fe627b9-2838-4331-8c5c-f5afeba40753.mp4

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 目前 `v1.8.9` 并未实现公式框输入框高度随编辑内容自动调整, 仅在弹出时调整一次, 导致空公式框高度过小(只有两行), 需要使用鼠标拖动大小后才能正常使用
