### ISSUE TITLE
新建文件夹不显示问题

### ISSUE THREAD

**Issue by liuy0267** [siyuan-note/siyuan#420]
如题，需要重新打开本地笔记本才能显示新建的文件夹
![test1](https://user-images.githubusercontent.com/73935960/98094958-ea676500-1ec4-11eb-8d03-faa56b2b1098.png)
![test3](https://user-images.githubusercontent.com/73935960/98094977-f0f5dc80-1ec4-11eb-8d5a-4b447276b04b.png)
![test4](https://user-images.githubusercontent.com/73935960/98094986-f3f0cd00-1ec4-11eb-99ec-12e6cef9725c.png)

**Comment by 88250** [comment]
感谢反馈，稍后发布 v0.4.1.1
