### ISSUE TITLE
不知道可不可以给数据包添加代码颜色

### ISSUE THREAD

**Issue by ohyessir** [siyuan-note/siyuan#4205]
在做一些漏洞复现的时候，会经常使用代码块粘贴一些数据包。但是没有颜色，有时候参数比较多，值又是一些编码的时候，看的有点分不明白。例子，
`GET /user/recentread/ HTTP/1.1
Host: 
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: lf_user_auth=%74%68%69%6E%6B%3A%7B%22%75%69%64%22%3A%22%31%22%2C%22%75%73%65%72%6E%61%6D%65%22%3A%22%32%33%33%33%33%22%7D; lf_user_auth_sign=5f7af37c12f20b2ebbac7fef23f412a9ecfc3c2d;lf_read_log=O%3A27%3A%22think%5Cprocess%5Cpipes%5CWindows%22%3A1%3A%7Bs%3A34%3A%22%00think%5Cprocess%5Cpipes%5CWindows%00files%22%3Ba%3A1%3A%7Bi%3A0%3BO%3A17%3A%22think%5Cmodel%5CPivot%22%3A2%3A%7Bs%3A17%3A%22%00think%5CModel%00data%22%3Ba%3A1%3A%7Bs%3A3%3A%22lin%22%3Bs%3A6%3A%22whoami%22%3B%7Ds%3A21%3A%22%00think%5CModel%00withAttr%22%3Ba%3A1%3A%7Bs%3A3%3A%22lin%22%3Bs%3A6%3A%22system%22%3B%7D%7D%7D%7D; reader_config_web=0%7C18%7C1%7C0%7C1
Connection: close`

**Comment by 88250** [comment]
语法高亮是 https://github.com/highlightjs/highlight.js 实现的，思源已经打包了它所支持的所有语法。如果没有找到，估计就是不支持了，见谅。

也许可以给 https://github.com/highlightjs/highlight.js 提 issue 试试 :)
