### ISSUE TITLE
代码块中 Tab 键的缩进无法回退

### ISSUE THREAD

**Issue by LecoLu** [siyuan-note/siyuan#4207]
版本：1.8.9
问题：代码块中，如果缩进是使用Tab，无法使用shift+Tab进行回退缩进。而以空格为缩进的，可以回退。
![动画](https://user-images.githubusercontent.com/24625475/157469353-39db6d39-eea1-496a-8e68-69c71503bdc5.gif)

**Comment by LecoLu** [comment]
@88250  D大，这个问题能否解决呢？ 最近在写go语言，他默认推荐是使用tab键缩进的，粘贴代码时无法使用退回缩进功能。

**Comment by 88250** [comment]
暂时还没有时间细看，建议代码在 IDE 里写好后一次性粘贴。

**Comment by LecoLu** [comment]
> 暂时还没有时间细看，建议代码在 IDE 里写好后一次性粘贴。

好的。可以一次性粘贴，但是大部分都是得部分粘贴。如果有时间的话解决一下。

**Comment by Vanessa219** [comment]
tab 个数和编辑器中设置的不一致时，会选取最小值进行缩进。建议在 IDE 中缩进后再粘贴，否则一行一行的缩进也很幸苦。
