### ISSUE TITLE
代码块里面剪切时触发前文 `#` 号标签搜索以及剪切抖动

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4212]
![代码块剪切异常](https://user-images.githubusercontent.com/5968678/157583490-9db3060b-3212-4c6f-a5a4-18fa3f5016d4.gif)

win10 + v1.8.9

**Comment by 88250** [comment]
在代码块中粘贴抖动的问题应该已经在 https://github.com/siyuan-note/siyuan/issues/4202 中进行修复，请等 v1.9.0 发布以后帮忙回测，谢谢。

**Comment by whuwangyong** [comment]
@88250 我说的不是一个问题。
1.9.0依然存在：剪切时抖动；剪切时会出现前面`#`号后的内容。

**Comment by 88250** [comment]
剪切抖动的问题可以重现，出现前面`#`号后的内容这个暂时重现不了。

**Comment by whuwangyong** [comment]
![代码块bug](https://user-images.githubusercontent.com/5968678/158507782-f3a55f78-a3b0-4928-8af1-63785f449949.gif)

应该是触发了标签查找。如果用行内代码将前面的`#`包起来，剪切时就不会出现。

**Comment by whuwangyong** [comment]
> ![代码块bug](https://user-images.githubusercontent.com/5968678/158507782-f3a55f78-a3b0-4928-8af1-63785f449949.gif)
> 
> 应该是触发了标签查找。如果用行内代码将前面的`#`包起来，剪切时就不会出现。

补充一下：我没有标签，所有笔记本一个标签都没有。
