### ISSUE TITLE
语法转义字符

### ISSUE THREAD

**Issue by Learces** [siyuan-note/siyuan#4216]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
一段文本中的内容和语法冲突。例如一段文本为：
从域名后的最后一个“/”开始到“？”为止，是文件名部分；如果没有“?”,则是从域名后的最后一个“/”开始到“**#”为止，是文件部分；如果没有“？”和“#**”，那么从域名后的最后一个“/”开始到结束，都是文件名部分。本例中的文件名是“index.asp”。文件名部分也不是一个URL必须的部分，如果省略该部分，则使用默认的文件名。
加粗部分将被识别为语法格式，而不是文本内容。

### 描述可能的最优解决方案 Describe the optimal solution
使用转义字符“\”表示对涉及语法的符号进行转义，标识该符号被解析为内容而不是语法

**Comment by 88250** [comment]
目前应该已经支持 `\` 转义标记符。

**Comment by Learces** [comment]
那这里有一个小小的瑕疵：只能事前添加转义字符，不能事后添加转义字符。
比如我输入：
#
#test
#test#
渲染之后再添加转义字符，转义字符就会出现在#test#后面，成为#test#\。只能事前直接写#test\#，才能起效。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 语法转义字符 (Issue #4216)





 
Closed #4216.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 88250** [comment]
这估计没有办法解决，思源的编辑器不是 Markdown 文本编辑器，标记符不会保留的。

**Comment by Learces** [comment]
可以考虑为键入转义字符添加一个键盘事件，每次触发事件时就检查键入位置前面是否存在特殊标签，不存在就保留转义符，存在就重新渲染特殊标签。
比如下面这个段落：

其HTML结构为：

当我在糖后面添加转义符后变成：

为键入转义字符添加键盘事件，获取前一个节点，判断是否为特性类型，是则重新渲染，不是则不管。


当然这个功能不是必须的，语法冲突频率也比较低。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月11日(星期五) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 语法转义字符 (Issue #4216)





 
这估计没有办法解决，思源的编辑器不是 Markdown 文本编辑器，标记符不会保留的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
