### ISSUE TITLE
作为列表项的标题块不再具有“转换为”功能

### ISSUE THREAD

**Issue by haogeek** [siyuan-note/siyuan#4217]
### 描述问题 Describe the problem

1.8.8版里标题块和列表块都加了一个小三角折叠按钮，这确实比用快捷键方便，但有了这个按钮之后，在大纲笔记里作为列表项存在的标题块右键菜单里就没有之前的“转换为”功能了，要调整标题级别只能通过退格+重新打#的方式。

### 期待的结果 Expected result

恢复标题块右键菜单中的“转换为”功能。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/4096257/157788205-4b60bc40-6a19-4f11-ad9c-2af2bade1a3e.png)

![image](https://user-images.githubusercontent.com/4096257/157788216-0ad2681b-a729-40ef-ac57-cf3c1e5650c9.png)

![image](https://user-images.githubusercontent.com/4096257/157788287-a71b49c3-a5dd-4076-839b-08ff842a9271.png)

### 版本环境 Version environment

* Version: 1.8.8
* Operating system: Windows 10
* Browser (if used):

**Comment by 88250** [comment]
可使用 Ctrl+/ 触发当前块（标题块）的菜单。
