### ISSUE TITLE
给页签添加优先打开的位置和最佳大小

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#422]
每次我打开大纲的时候，总是希望它在右侧打开，但它总在左侧打开。

将它拖到右侧后，总是很宽大，需要手动调整大小。

![image](https://user-images.githubusercontent.com/19181833/98097099-7b3f4000-1ec7-11eb-8bf5-bd62eb5a25ca.png)

**Comment by 88250** [comment]
布局应该会自动保存的，不用每次都拖动调整大小。

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/635
