### ISSUE TITLE
请明示docker部署的具体步骤和方法　

### ISSUE THREAD

**Issue by yggcwx** [siyuan-note/siyuan#4220]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
docker部署

### 描述可能的最优解决方案 Describe the optimal solution

请在code下文明确公示docker部署的具体步骤和方法。在源码中，也无法找到相关文档。这个项目是用来做样子看的吗？？？

**Comment by 88250** [comment]
请参考帮助文档，或者参考一下 Issues 和链滴上其他用户贡献的教程。

**Comment by yggcwx** [comment]
就是找不到帮助文档啊！！readme里边也没说咋部署啊

**Comment by 88250** [comment]
下载桌面端就能找到了。

**Comment by yggcwx** [comment]
可我是想在服务器上部署啊！下载什么，下载源码吗？

**Comment by yggcwx** [comment]
还是建议在这里公布一下docker部署的具体步骤和方法！

**Comment by luckept** [comment]
可以参考一下 https://www.yuque.com/siyuannote/docs/20210725124311-ssp7qk4

**Comment by yggcwx** [comment]
> 可以参考一下 https://www.yuque.com/siyuannote/docs/20210725124311-ssp7qk4

非常感谢！

**Comment by yggcwx** [comment]
官方的这个思路真是非常奇怪，就是把docker安装文档不公布，为啥？搜了一下，也不止我一个人找不到。
说是下载客户端节就有，可我是想在linux服务器上部署啊！真还就试了一下，下了个windows客户端，毛都没有。
再见，还没用，就转到语雀去了！！！

**Comment by Zuoqiu-Yingyi** [comment]
> 官方的这个思路真是非常奇怪，就是把docker安装文档不公布，为啥？搜了一下，也不止我一个人找不到。 说是下载客户端节就有，可我是想在linux服务器上部署啊！真还就试了一下，下了个windows客户端，毛都没有。 再见，还没用，就转到语雀去了！！！

@yggcwx 因为 Docker 安装文档就在笔记中的帮助文档里面, 算是一个先有鸡还是先有蛋的问题...
