### ISSUE TITLE
思源协议块超链接加入 `focus` 参数

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#4221]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
在Supermemo等软件中转到思源笔记中的block，希望可以提供focus选项。没有这个选项时，光标所在位置不明朗，如果用脚本发送Alt->容易误操作。

为了简化Supermemo与思源之间的互动，除了将思源笔记页面复制到Supermemo中这种方式，另一个方式是将思源的块链接地址复制到Supermemo中，在Supermemo中学习时由脚本自动解析卡片中的内容（已经完成），并通过调用siyuan://xxxxxxx来刷新思源中的文档显示。这样好处是不用担心两个地方内容编辑后不同步。但是为了聚焦内容位置，希望进入聚焦模式，在uri后面增加focus?=1时，自动聚焦该block。对于记忆闪卡，还可以控制只聚焦显示"问题"block（也就是卡片的正面Front部分）。
这种方案下，Supermemo只是作为一个间隔时间管理软件，而内容一般都在思源笔记中。在思源笔记中，可以通过F4创建子卡片，也可以组建超级块作为子卡片。将这些块的信息发到Supermemo中建卡即可，不需要复制html。

同时提供 focus?=0，表示去掉该文本块或文档块的聚焦状态。
最好还能提供 focus?=2，表示聚焦，但切换页签离开一个文档页签之后，自动去掉该文本块的聚焦状态。

**Comment by jabobian** [comment]
这一机制也适用于Anki。短期内就可以为思源引入成熟的间隔学习机制。

**Comment by 88250** [comment]
`siyuan://blocks/20220312004051-pdoy4az?focus=1`，focus 参数为 1 表示以聚焦模式打开。

**Comment by Vanessa219** [comment]
不带 focus 的就不会缩放，除非已经打开过带缩放的该页签

**Comment by jabobian** [comment]
感谢V大答复
focus是聚焦，对应 Alt+→
defocus是取消聚焦，聚焦到上层，对应 Alt+←.

我希望目的是通过外部调用siyuan://xxxx?focus=1链接来显示问题
然后通过外部调用siyuan://xxxx?focus=0链接来显示问题和答案。
就是把思源做成一个闪卡的编辑保存端和显示端。
不知道我这么解释是否表述到位。

**Comment by jabobian** [comment]
#### Card 1:
##### Q：
##### A :

假设我用 
H1和下面的H2分别表示卡片的全部（正面+背面）和正面，通过在 H2 处按下 Alt+→ 显示的卡片的正面，然后再按下 Alt+←，显示的是全部。
我们只需要知道卡片的正面（H2）的siyuan://地址，就可以显示答案，但是需要能取消 H2 的聚焦。现在只能通过发送热键来执行，体验不太好。
