### ISSUE TITLE
增加快捷键获得当前文档的人类可读路径

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#4226]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
需要将Human readable path复制到其它软件，例如Supermemo或者Anki中作为溯源提示用。

为了让Supermemo与思源可以融合使用，又来麻烦您两位了。思源校友。
我创建Supermmemo卡片时只记录思源的block id就可以溯源，但是在Supermemo中创建的卡片只有block id是很难体现语义信息的，如果点击siyuan://链接进去看到是没有什么意义的，虽然可以手动去补充路径信息或tag等，但是在思源中其实已有有现成的上下文信息可以作为提示，一般就是HPath，直接使用就挺好。如果能通过快捷键或其它方式获得这个信息，在创建Supermemo卡片时，可以作为标题或者正文中的备注等。
目前我能想到的一个临时方法是用Autohotkey调用模版打出HPath，然后用剪切，但是不是特别流畅。

### 描述可能的最优解决方案 Describe the optimal solution
建议最好采用快捷键方式实现，当然界面上要做的事情比较多。
实在不行，也可以用 API实现，但是现在的API要求书籍和文档路径参数，感觉参数要求太多太高了，简化到只提供文档block id应该就够了吧。

**Comment by 88250** [comment]
@Vanessa219 文档块块标菜单 - 复制 - 复制路径

**Comment by 88250** [comment]
API https://github.com/siyuan-note/siyuan/issues/4229

**Comment by jabobian** [comment]
D大，API也是需要的，能否提供 getHPathByID?

**Comment by 88250** [comment]
@jabobian https://github.com/siyuan-note/siyuan/issues/4229
