### ISSUE TITLE
块聚焦时提及面板点击转换引用块没反应

### ISSUE THREAD

**Issue by mindstudy** [siyuan-note/siyuan#4230]
版本 1.8.9

聚焦模式进入某个引用块，提及面板有相关提及结果，点击某一项的转换图标时没有反应，无法转换为反链。

**Comment by 88250** [comment]
麻烦录屏演示操作，并上传一下 .sy 文档或者发送到邮箱 845765@qq.com 谢谢。

**Comment by mindstudy** [comment]
![Kapture 2022-03-13 at 17 08 57](https://user-images.githubusercontent.com/23169045/158052932-caa0a219-48f3-44a0-b512-c93ae9902506.gif)
[20220313164842-z60kmvg.zip](https://github.com/siyuan-note/siyuan/files/8239239/20220313164842-z60kmvg.zip)

**Comment by 88250** [comment]
感谢帮忙，已经确认问题，下个版本修复。
