### ISSUE TITLE
英文括号中无法输入反斜杠

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4231]
复现步骤：
新打一对英文括号，将光标移到括号中间，输入反斜杠`\`，发现没有输入，且光标移到了括号外面。再次将光标移入括号，可以输入`\`。
小、中、大括号都有这个问题。

Win10+1.8.9

**Comment by 88250** [comment]
这几个括号都是 Markdown 标记符，所以输入 `\` 后是转义标记符，如果需要输入 `\` 的话需要再次转义 `\` 本身，即 `\\`。

**Comment by whuwangyong** [comment]
那有两点不解：
1. 光标移动到外面了。
2. 如果不加行内代码，正文中没法连续输入多个反斜杠，即这样的：\\\\\\\\

**Comment by 88250** [comment]
试试在左侧输入 `\`，不要在右侧结尾输入。

**Comment by whuwangyong** [comment]
搞定！感谢！
