### ISSUE TITLE
文档快速滚动条提示当前块位于文档的位置

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4234]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

当文档比较长触发动态加载时, 就不能使用滚动条判断当前所处是文档的哪一部分, 判断剩下还有多少篇幅未浏览, 因此可以将文档快速滚动条利用起来, 实时提示当前所处的块位于本篇文章中所有块的位置
![image](https://user-images.githubusercontent.com/49649786/158071064-25e44fef-a0a5-42fc-98d2-44f5198b897d.png)

### 描述可能的最优解决方案 Describe the optimal solution

文档快速滚动条圆点与鼠标悬浮时显示的提示文字 `Blocks 当前块/总块` 均跟随当前显示的块更改

### 描述候选的解决方案 Describe the candidate solution

文档快速滚动条圆点与鼠标悬浮时显示的提示文字 `Blocks 当前块/总块` 均跟随光标所在块更改

**Comment by Vanessa219** [comment]
这样设计是为了记住上一次动态加载的位置，方便用户回到上一次动态加载的位置。如果需要显示当前进度，还需要再想想怎么交互。
我先关闭了，有更好的交互可以新开 issue。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/4612
