### ISSUE TITLE
通知自动关闭

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#424]
目前下图这个通知显示后就会一直占用着屏幕，需要手动去点那个小小的错号才能关闭。建议对于这种通知像 Android 上的 toast 一样，设定一定的时长，超过后自动关闭。

![image](https://user-images.githubusercontent.com/19181833/98098320-23a1d400-1ec9-11eb-9c23-62043e671521.png)

**Comment by 88250** [comment]
报错信息是故意留着的，方便复制。其他信息有做自动超时关闭，谢谢反馈。

**Comment by 88250** [comment]
话说这个报错怎么产生的，能告诉我一下重现步骤么？

**Comment by HaujetZhao** [comment]
> 报错信息是故意留着的，方便复制。其他信息有做自动超时关闭，谢谢反馈。

报错信息可以放到日志吧。



> 话说这个报错怎么产生的，能告诉我一下重现步骤么？

点击帮助按钮会出现帮助文档笔记本，这个笔记本是只读的，如果在里边编辑了，就会提示保存错误。

**Comment by 88250** [comment]
收到，理论上帮助手册应该也能编辑才对，稍后我再看下。
