### ISSUE TITLE
挂件提供设置项

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#4240]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
有些挂件很不错, 但是由于目前挂件没有设置选项, 所以如果需要个性化往往需要追踪到挂件安装目录并做相应修改.
对于桌面端应用还可以接受, 但是作为手机伺服时, 受限于android安全限制, 除非root几乎不可能了

### 描述可能的最优解决方案 Describe the optimal solution
挂件可以按照比较统一的显示页进行个性化设置

### 描述候选的解决方案 Describe the candidate solution
或者为每个挂件提供json设置文件

### 其他信息 Other information
暂无

**Comment by 88250** [comment]
挂件应该是自维护的，设置界面应该也需要挂件自己提供。

**Comment by banjuer** [comment]
好吧，只能说现在的挂件市场太弱了
