### ISSUE TITLE
先添加行内代码块，再添加下划线，导致本行之后无法输入

### ISSUE THREAD

**Issue by Learces** [siyuan-note/siyuan#4242]
### 描述问题 Describe the problem
![QQ截图20220314205858](https://user-images.githubusercontent.com/94371988/158176860-d0fa8a10-9817-4d0e-8bc5-e1399113283b.png)
将光标置在s行首，无法退格到上一行

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
我这里好像没发现问题，麻烦录屏演示一下输入过程，谢谢。

![image](https://user-images.githubusercontent.com/873584/158180293-e5113877-c822-42b0-abad-92da0b96993b.png)

**Comment by Learces** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 先添加行内代码块，再添加下划线，导致本行之后无法输入 (Issue #4242)





 
我这里好像没发现问题，麻烦录屏演示一下输入过程，谢谢。
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 88250** [comment]
我们先关闭了，如果有进一步信息请补充，谢谢。

**Comment by Learces** [comment]
嗯？收不到视频吗？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月14日(周一) 晚上9:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 先添加行内代码块，再添加下划线，导致本行之后无法输入 (Issue #4242)




 
我这里好像没发现问题，麻烦录屏演示一下输入过程，谢谢。
 

 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 88250** [comment]
没有看到视频文件哦。

**Comment by 88250** [comment]
目前还不支持行级元素交叉和嵌套，请关注 #2911
