### ISSUE TITLE
仅含有 `<u>` 与 `<kbd>` 的 HTML 块导出为模板后再导入会渲染为包含下划线与键盘行级元素的段落块

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4244]
### 描述问题 Describe the problem

这里有一个段落块与一个 HTML 块:
![image](https://user-images.githubusercontent.com/49649786/158229342-9962a7f1-d16c-418a-adb0-ca9dc693256d.png)
这两个块导出为模板后对应的内容为
```markdown
<u>12345</u> <kbd>67890</kbd>
{: id="20220315013255-p4rlxwu"}

<u>01234</u> <kbd>56789</kbd>

{: id="20220315013255-x9ul8yv"}
```
显然, 段落块 IAL 前没有空行, HTML 块 IAL 前有一个空行, 经过测试, HTML 块导出为模板后 IAL 前至少有一个空行, 因此, 可以通过该特征区分这是一个段落块还是一个 HTML 块, 但是使用该模板导入后, 这两个块均会渲染为段落块:
![image](https://user-images.githubusercontent.com/49649786/158229959-2a3592d4-ecf5-458c-bb4f-655d7558fe1c.png)

### 期待的结果 Expected result

模板导出后再导入, 前后块样式不发生改变

### 版本环境 Version environment

* Version: 1.9.0

**Comment by 88250** [comment]
修改后导出模板时会自动添加 `<div>` 包裹 HTML 块，这样才能保证后续解析正确。
