### ISSUE TITLE
MacOS_11.6.4 下 markdown 语法输入标题异常

### ISSUE THREAD

**Issue by kam1uSEC** [siyuan-note/siyuan#4246]
###  标题选择异常

1. 写完的文档里会有一些标题留存，影响文档的结构。
2. 使用markdown标题语法的时候，会出现空格换行且无法返回到原来的那一行，这就是文档里无用标题产生的原因。
3. 在windows上是正常的

### 期待的结果 Expected result

恢复正常的markdown编辑体验，及想知道为什么会出现这种异常。

### 截屏或者录屏演示 Screenshot or screen recording presentation
<img width="439" alt="image" src="https://user-images.githubusercontent.com/46443718/158284712-d66c71d9-1afa-439d-ae9c-f6ef6ebc0f0e.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/46443718/158284839-c619077f-5fff-41ff-8c24-a5c325e2035e.png">

### 版本环境 Version environment

* Version: <=1.9.0
* Operating system: MacOS11.6.4
* Browser (if used): 

### 日志文件 Log File

[app.log](https://github.com/siyuan-note/siyuan/files/8249310/app.log)

### 更多信息 More information

如果是新建的文档就没有这个问题。

**Comment by 88250** [comment]
麻烦录屏演示和提供 .sy 文件帮助我们重现该问题，谢谢。

**Comment by kam1uSEC** [comment]
https://user-images.githubusercontent.com/46443718/158291087-6d1d4c75-9fb1-4976-ae83-a59ca58d1299.mov

[20220302204827-1z2xsfc.zip](https://github.com/siyuan-note/siyuan/files/8249570/20220302204827-1z2xsfc.zip)

**Comment by 88250** [comment]
好像需要解压密码？

**Comment by kam1uSEC** [comment]
> 好像需要解压密码？

密码：11235813
忘记压缩软件是设置的默认添加密码 😂不好意思

**Comment by 88250** [comment]
Windows 上确认重现不了，我们也在 macOS 12.2 上测试了也无法重现。由于没有 11.x 的系统，所以没法测试了。

你试下切换到默认主题后再试试看。

**Comment by kam1uSEC** [comment]
> Windows 上确认重现不了，我们也在 macOS 12.2 上测试了也无法重现。由于没有 11.x 的系统，所以没法测试了。
> 
> 你试下切换到默认主题后再试试看。

看来确实是第三方主题的问题。我切换到默认主题之后就没有这个问题了。:)
