### ISSUE TITLE
复制为纯文本

### ISSUE THREAD

**Issue by MoonBottle** [siyuan-note/siyuan#4248]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

我在笔记中存储了帐号信息，并设置了样式，如图
![image](https://user-images.githubusercontent.com/12904505/158290503-d4ecdd1b-1501-4493-a1fc-bd08eefa571e.png)
我需要分享给别人的时候，通过直接复制的方式粘贴到微信
出来的效果是这样的（下图），对方的阅读效果并不好，也不方便直接进行复制粘贴使用我分享的信息
![image](https://user-images.githubusercontent.com/12904505/158290605-74db3eab-eea8-4f1c-b047-aba49ba322cc.png)

### 描述可能的最优解决方案 Describe the optimal solution

增加复制为纯文本的选项

### 描述候选的解决方案 Describe the candidate solution

增加复制为纯文本的快捷键

### 其他信息 Other information

mac 系统，软件版本 1.9.0，复制粘贴到微信
window 系统下从思源复制出来的信息粘贴到微信已经是纯文本，但是mac不行

**Comment by Achuan-2** [comment]
切换到预览模式复制

**Comment by 88250** [comment]
楼上说得对，我们关闭了，谢谢。
