### ISSUE TITLE
HTML块没有块标

### ISSUE THREAD

**Issue by bearxz** [siyuan-note/siyuan#4249]
### 问题描述
插入HTML块时，HTML块左侧没有显示块标

### 环境
OS：window11
APP：1.9.0

### 复现方式
插入HTML块必现

### 截图
![image](https://user-images.githubusercontent.com/37499441/158294819-52fad30f-3f43-4f41-99d7-712da8ba4085.png)

**Comment by 88250** [comment]
使用了自定义 icon 吗？

**Comment by 88250** [comment]
正常情况下（默认主题和图标）应该是这样的

![image](https://user-images.githubusercontent.com/873584/158295695-2a4051ae-8c04-4932-a109-41861bb007f7.png)

**Comment by bearxz** [comment]
原因的确是使用了notion-icon，没有这个HTML5的块标，切换为默认主题已经解决了

**Comment by 88250** [comment]
方便的话给图标作者反馈一波，谢谢。
