### ISSUE TITLE
为转换后的文档选择存储文件夹时提供默认位置

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#425]
如下图，在连接新笔记本时，会需要指定 `.sy.md` 的位置，但是大多数普通用户并没有文件组织能力，一时也想不到指定一个什么位置最好。

![image](https://user-images.githubusercontent.com/19181833/98099971-2f8e9580-1ecb-11eb-8b1c-7d6b3c28177a.png)

综上，建议提供一个位置作为默认选项，将 `选择存储文件夹` 这个按钮作为第二选项（就像是安装新软件时都是默认下一步时安装到 `C:\Program Files`，选择其它位置的按钮是第二选项）。

而这个默认位置建议就放到所导入笔记目录的 `.siyuan` 子目录。

**Comment by 88250** [comment]
~/.siyuan/ 配置目录还是只存放配置比较好，不然用户很可能会找不到……

**Comment by HaujetZhao** [comment]
> ~/.siyuan/ 配置目录还是只存放配置比较好，不然用户很可能会找不到……

说的不是 `~/.siyuan/`，而是在新打开的笔记本目录内新建一个 `.siyuan` 文件夹用于存放该笔记本相关的文件。

**Comment by 88250** [comment]
. 开头的文件夹在 Unix-like 上是隐藏文件，这样用户也找不到……

**Comment by HaujetZhao** [comment]
> . 开头的文件夹在 Unix-like 上是隐藏文件，这样用户也找不到……

我认为相较于每次导入一个笔记都要手动指定一个存储位置，把存储文件夹定义在 `.siyuan` 挺好的，让转换后文件和原始笔记存储在同一个文件夹也方便管理。默认隐藏正好可以让笔记本文件夹看着干净。

隐藏不隐藏不重要，只要用户知道那里有这样一个东西就成。反正普通用户接触 .siyuan 的内容也是通过思源笔记这个入口的，而有需要使用文件管理器修改 .siyuan 文件夹内容的人，也不会不知道显示隐藏文件的知识。

我给拟了一个新的提示：

🎉 这是你第一次通过思源笔记打开该文件夹，我们需要完成一些导入工作：

1. 将 [[link#heading|text]] 自动转换为 ((id "text"))
2. 将 #tag 自动转换为 #tag#
3. 生成转换后的 `.sy.md` 文档
4. 为笔记生成用于版本控制的 git 仓库

我们需要一个存储文件夹，用于存储转换后的 `.sy.md` 文档和 git 仓库，它的位置默认是您选择的笔记本文件夹下的 `.siyuan` 文件夹（默认是一个隐藏文件夹）。

　　　　　　　**取消**　　**自定义存储文件夹**　　**完成导入**
