### ISSUE TITLE
聚焦返回时的级次问题

### ISSUE THREAD

**Issue by mindstudy** [siyuan-note/siyuan#4250]
版本1.9.0

文档中有多级层次内容块的情况。最下一级聚焦后，再聚焦返回时，会返回上一级，而不是直接返回聚焦前的页面。

![Kapture 2022-03-15 at 10 50 43](https://user-images.githubusercontent.com/23169045/158297384-50ac3212-2b60-4c55-a8d8-5884c000023c.gif)

如图所示，在文档页面对h6标题聚焦后，要一级一级向上返回，最后才能回到文档页面，效率实在太低。

正常操作与心理认知上，应该是从哪一级进入聚焦，返回时也应该在哪一级。

希望考虑一下是否改善

**Comment by 88250** [comment]
是通过 <kbd>Ctrl+[</kbd> 后退的吗？

**Comment by mindstudy** [comment]
是通过聚焦返回的快捷键 Alt + 左方向键

 Ctrl+[ 会回到整个文档的顶部。如果文档长，而聚焦前位置是在文档比较下面的位置， Ctrl+[ 返回后再定位到聚焦位置貌似就没啥好办法

**Comment by 88250** [comment]
Alt+左右方向键是按层级聚焦和退出。Ctrl+[ 是后退，会后退到上一个光标编辑位置，后退完后可以使用前进快捷键 Ctrl+] 回到聚焦位置。
