### ISSUE TITLE
标签类型咨询

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#4251]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

我想通过sql在一个页面汇总标签内容, 做一些类似闪卡汇集. 所以想咨询下我们`getTags`是怎么实现的呢? 因为在思源的sqlite里并未看到有标签的type区分. 目前能想到的是content like 搜索

### 描述可能的最优解决方案 Describe the optimal solution
咨询类问题

### 描述候选的解决方案 Describe the candidate solution
无

### 其他信息 Other information
无

**Comment by 88250** [comment]
标签是个行级元素，在 span 表里有。
