### ISSUE TITLE
关联查询sql查不出结果

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#4253]
### 描述问题 Describe the problem
手机伺服
统计标签页的sql, 执行时返回 **不存在符合条件的内容块**
```sql
select bs.* from spans sp left join blocks bs on sp.block_id=bs.id where sp.type='tag' order by sp.content
```

### 期待的结果 Expected result

正确返回结果
### 版本环境 Version environment

* Version: 1.9.0
* Operating system: android 11
* Browser (if used): 

### 日志文件 Log File

手机伺服不好找文件

### 更多信息 More information

无

**Comment by 88250** [comment]
我这里无法重现问题（手机伺服和桌面端都测试过），能够正常查询显示：

![image](https://user-images.githubusercontent.com/873584/158339483-83146c47-b05c-4d8a-b520-85acaa9333be.png)

你再看下是不是没有标签，可打开帮助文档测试，里面有一些标签。

先关闭了，谢谢。

**Comment by 88250** [comment]
按一下 SQL 的刷新按钮看看。

**Comment by banjuer** [comment]
> 按一下 SQL 的刷新按钮看看。

按了, 但是日志没有更新, 数据也是没查出来

**Comment by 88250** [comment]
重建索引后再试试呢？

**Comment by banjuer** [comment]
> 重建索引后再试试呢？

也试了, 不行. 我可以给你开远程, 你试一下

**Comment by 88250** [comment]
做一个最小能重现问题的工作空间或者笔记本发给我们试试 845765@qq.com

**Comment by 88250** [comment]
这个 md 我导入了也没发现问题，是手机伺服测试的。

暂时不好定位问题了，估计只能先这样了，抱歉。

**Comment by banjuer** [comment]
删除了原来的笔记本，用着用着又出现查不出的情况了. 看来是个隐藏bug :)

**Comment by 88250** [comment]
升级到 v1.9.2 了吗？

**Comment by banjuer** [comment]
升级了。

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 88250** [comment]
试下把 temp 文件夹完全删掉后重启。

**Comment by banjuer** [comment]
安卓删不了啊，Android/data/下没权限操作。siyuan重建索引无效

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 88250** [comment]
哦，对……这个问题藏得比较深，暂时还没有头绪。

**Comment by banjuer** [comment]
多用用安卓伺服，大概没几天就会发现了。确实不好定位原因

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
