### ISSUE TITLE
块引浮窗内容显示不全

### ISSUE THREAD

**Issue by JOYCELEEEEE** [siyuan-note/siyuan#4255]
### 描述问题：对引用块进行查看时，发现反链面板无法正常显示文字引述块

具体表现为反链面板在引述块前自动增加了一个无序列表块，这是我将一个页面进行多个分屏并同时编辑时常出现的

### 截屏或者录屏演示

https://user-images.githubusercontent.com/89592448/158379192-d300de0c-f7c6-4ce5-8bf5-bd31cfd2e765.mp4

### 版本环境 Version environment

* Version: 1.9.0
* Operating system: windows

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8253179/siyuan.log)

**Comment by 88250** [comment]
你好，我没有看懂描述……麻烦录屏演示下。

**Comment by JOYCELEEEEE** [comment]
把图片换成录屏了🤐

**Comment by 88250** [comment]
录屏里面在浮窗的 11111 前面做的操作是？

**Comment by JOYCELEEEEE** [comment]
就是将11111的引用块打在1111111上，对1111111进行查看时，发现没有显示11111下方的文字引述，然后在浮窗里alt+←，发现浮窗里的引述前多了一个无序列表块，导致浮窗里没能显示该引述

**Comment by 88250** [comment]
我这里重现不了问题，麻烦把 .sy 上传一下。

**Comment by 88250** [comment]
你好，我在你发给我的邮件里没有找到 11111 这个关键字……麻烦重新制作一份可重现问题的数据集给我们，谢谢。

**Comment by 88250** [comment]
我们先关闭 issue 了，下个版本改进比较多，麻烦升级以后再看看，谢谢。
