### ISSUE TITLE
代码块超过99行显示错位

### ISSUE THREAD

**Issue by ad-calcium** [siyuan-note/siyuan#4260]
### 描述问题 Describe the problem

行号超过99显示错误，具体如下图

![image](https://user-images.githubusercontent.com/33044636/158406127-bb7b369d-781b-4ba8-9781-810a38fcd518.png)

### 版本环境 Version environment

* Version: 1.9.0
* Operating system: win10

**Comment by Achuan-2** [comment]
更新主题，这个问题已经解决了
