### ISSUE TITLE
折叠后光标移到被折叠块上

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4265]
https://ld246.com/article/1647397123809

**Comment by Zuoqiu-Yingyi** [comment]
`v1.9.1` 依旧存在这个问题

复现方案:
1. 打开 `思源笔记用户指南`>`请从这里开始`>`编辑器`>`排版元素`
2. 使用方向键 <kbd>↓</kbd> 一直向下移动
3. 移动至 `无序列表` 或 `有序列表` 中折叠的列表项 `Go` 与 `Java` 时再按 <kbd>↓</kbd> 看起来光标会移动至该列表项末尾, 实际通过 `window.getSelection().focusNode.parentElement` 发现焦点位于被折叠的子列表项中, 且此时使用 <kbd>Backspace</kbd> 也会删除被折叠的子列表中的内容
![思源笔记-bug反馈-16](https://user-images.githubusercontent.com/49649786/158742544-f1a26214-d123-4db8-b799-2ec080d98df7.gif)
