### ISSUE TITLE
1.9.0右键弹出菜单取消了吗

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4266]
1.8.9右键：
![img](https://user-images.githubusercontent.com/24625475/157406245-537cca4d-0cf5-4d00-9d78-d56456c0f0a8.gif)
图源#4202

现在在选中文本上右键菜单没反应，不管在正文还是代码块。
代码块里，不选中时点右键，行为也不一样：现在是弹出对代码块操作的菜单。

> 平时用快捷键，录屏时试了方便观看，使用鼠标右键，发现菜单没有了。

**Comment by whuwangyong** [comment]
不只是代码块，在其他如段落块右键，弹出菜单也是对整个块的操作。
![右键](https://user-images.githubusercontent.com/5968678/158509573-c5affbcb-0b9e-4d12-8da5-007ca784f239.gif)

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 `v1.9.1` 的修复方案又引入了新的问题: 列表项容器内第一个段落块的块菜单无法弹出
- 块标被折叠小三角占据, 无法通过单击弹出块菜单
- 没有子列表项时第一个段落块块标也不显示
- 使用 <kbd>Esc</kbd> 键选择该段落块后右键菜单依旧是编辑菜单, 而非块菜单
![思源笔记-bug反馈-17](https://user-images.githubusercontent.com/49649786/158753304-cfcab5dc-82c2-41f9-b337-0537b36945be.gif)

期待结果: 未使用 <kbd>Esc</kbd> 键选择该段落块时弹出编辑菜单, 使用 <kbd>Esc</kbd> 键选择该段落块时弹出块菜单

**Comment by Vanessa219** [comment]
1. 使用 ctrl+/
2. 
<img width="343" alt="image" src="https://user-images.githubusercontent.com/970828/158813855-6e4d1674-0e9c-4e10-97cc-2227a387e64d.png">
3. 使用 ctrl+/
