### ISSUE TITLE
HTML 块可导致XSS

### ISSUE THREAD

**Issue by fupinglee** [siyuan-note/siyuan#4274]
### XSS

复制代码到笔记本中
```
<img src=1 onerror=alert(1)>
```
<img width="711" alt="001" src="https://user-images.githubusercontent.com/19523172/158550748-2840aa3d-71a7-4104-811e-164d9a76dcf1.png">

关闭打开笔记本即可触发
<img width="786" alt="002" src="https://user-images.githubusercontent.com/19523172/158550897-2ccabcd5-a87d-4fd0-9254-ccf6b37387fc.png">

### 版本环境 Version environment

* Version: 1.9.0
* Operating system: MacOs

**Comment by 88250** [comment]
是的，这个目前不过滤阻止了，已在帮助文档 - 排版元素章节中进行了注意说明。

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/11172
