### ISSUE TITLE
字体样式取消快捷键绑定错误

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4278]
字体样式快捷键为 `Alt + X`，但是再次按`Alt + X`却不能取消字体样式。
经过测试，发现按`Ctrl + B`可以取消字体样式。再次按`Ctrl + B`则是加粗。
![字体样式快捷键](https://user-images.githubusercontent.com/5968678/158588605-f9f7f28d-3475-45d0-a079-fc8a1ff3fbcc.gif)

**Comment by mindstudy** [comment]
其实 Ctrl + B 倒是一个歪打正着的快捷键，很多样式用的是 strong 标签， Ctrl + B 用于取消并不奇怪

如果取消样式一个一个对应到按钮，反而会增加快捷键记忆量或者鼠标操作疲劳度。

现在这样的情况其实已经有点习惯了，不建议做改动。

**Comment by whuwangyong** [comment]
如果预期是这样也可以，帮助文档里关于此快捷键的描述也同步更新一下就好。

**Comment by 88250** [comment]
暂时就这样了，后面等行级交叉嵌套 #2911 后再考虑，感谢讨论。
