### ISSUE TITLE
使用头部 YAML front-matter 记录文档属性，将文件名中的文档块 id 放到头部 YAML 属性中

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#428]
思源笔记不可能满足所有用户的所有需求，甚至可以说思源笔记满足 20% 用户的所有需求也是不可能的，所以部分用户综合使用思源笔记和其它工具管理文档，是必然的现象。

至于用户用哪个工具，为什么用那个工具，这不是思源考虑的问题，因为用户的需求总是千方百怪。思源要做的只是，在做好自己功能的同时，尽可能地让用户使用地舒服。

而对于结合思源和其它工具管理文档的用户，思源笔记文件名后那长长的一串 id ，就非常的让人不舒服。对比一下：

![image](https://user-images.githubusercontent.com/19181833/98248082-6c33bd00-1faf-11eb-95ca-4686aa2b7e28.png)

![image](https://user-images.githubusercontent.com/19181833/98248051-650caf00-1faf-11eb-9702-caae35ec024f.png)

相较于正常的文件名，带有一大串 id 的文件名，在不管是文件浏览器还是其它软件的显示中，就像是屏幕上趴满了好几只被拍扁的苍蝇一样让人膈应难受。

因此提供一个方法，取代在文件名中记录文档 id。该方法是：在 md 文档的 YAML front matter 中记录文档 id。

YAML 是人类可读的、为所有编程语言设计的数据格式， [YAML front-matter](https://jekyllrb.com/docs/front-matter/) 是一种用于保存 Markdown 元数据的语法。

使用 [YAML front-matter](https://jekyllrb.com/docs/front-matter/) 的格式：

```markdown
---
Siyuan:
   doc-id: 20201105034138-uut4tfw
   author: xxxx
---

正文
```

或者这样的 YAML 格式：

```markdown
<!--
Siyuan:
   doc-id: 20201105034138-uut4tfw
   author: xxxx
-->

正文
```

在正文头部记录文档属性，将文件名中的文档块 id 放到头部 YAML 属性中，还可以在后续记录更多有用的属性。

对于已存在的 YAML 属性不用管，只需要将 Siyuan 的属性 append 上，不会与已存在的 yaml 属性有干扰。

yaml front  matter 是专门用于存储 markdown 元数据的，虽然在导入笔记本时需要修改 md 的内容，但是并不会涉及修改用户在 md 文档中的正文内容。

研究的话可以参考下 [marpit](https://marpit.marp.app/directives) 的语法实现。

这样的话，就不用在 .sy.md 文件名中记录文档块 id 了，也不用 .sy.md 扩展名来区别思源文档了。现在只需要对笔记本内所有的 .md 文档一视同仁：

* 如果有 YAML 文档块 id，就跳过处理
* 如果没有 YAML 文档块 id，就自动生成并 append 上 YAML 文档块 id

这样，就可以实现对所有 Markdown 编辑器的最大兼容，并且也不再需要在文件名中放置让人膈应的 id 了：

![image](https://user-images.githubusercontent.com/19181833/98240881-135f2700-1fa5-11eb-90d7-a2846ae34079.png)

YAML 的兼容性应该不需要担心，下图是 [YAML front-matter](https://jekyllrb.com/docs/front-matter/) 在 Typora 中的显示效果：

![image](https://user-images.githubusercontent.com/19181833/98240903-1c4ff880-1fa5-11eb-914a-140098549592.png)

为了实现这个的话，思源笔记中的 Vditor 可能也需要做一些改动以优化 YAML 标识的显示效果。

**Comment by 88250** [comment]
感谢建议，暂时维持现状，等再收集一些用户反馈伺机而动。

**Comment by 88250** [comment]
后续估计会通过 kramdown 属性解决，放在文档末尾，关闭了，谢谢。
