### ISSUE TITLE
在有列表下的代码框样式显示有问题

### ISSUE THREAD

**Issue by iswbm** [siyuan-note/siyuan#4282]
如图所示在有列表下的代码框样式显示有问题
<img width="804" alt="image" src="https://user-images.githubusercontent.com/22311419/158614109-2b6d0f5c-b9f6-4ea6-93c5-d792cdf23e25.png">

**Comment by 88250** [comment]
请更新对应主题，这个问题主题作者已经修复。

**Comment by iswbm** [comment]
> 请更新对应主题，这个问题主题作者已经修复。

我使用的主题是 BluePrint from Tsundoku

<img width="278" alt="image" src="https://user-images.githubusercontent.com/22311419/158616860-8b3a4a1f-e955-4ea7-9e48-553e552a0c67.png">

刚看了商店里，已经没有该主题了，请问是下架了吗？
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/22311419/158617146-b0975128-4141-4d61-b3e8-6242b5cec29a.png">

**Comment by 88250** [comment]
可能是下架了，GitHub 上搜索看看。
