### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by casselluu** [siyuan-note/siyuan#4284]
### 描述问题 Describe the problem

docker安装，之前能内网访问，设置授权码后无法进入，测试发现输入错误授权码会提示不正确，正确授权码会导致一直卡在check-auth界面
另外，nginx反向代理，通过https域名访问会导致Mixcontent，问题，无法获取pdf.json

### 版本环境 Version environment

* Version: 1.9.0
* Operating system: unraid 6.9.2
* Browser (if used):  edge(chrome)

### 日志文件 Log File

I 2022/03/17 07:11:53 runtime.go:32: kernel is booting:
    * ver [1.9.0]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20211218]
    * workspace directory [/home/siyuan/Documents/SiYuan, data 2.2 MB]
I 2022/03/17 07:11:53 conf.go:263: local serve path [https://note.143800.xyz:18443]
I 2022/03/17 07:11:54 serve.go:68: kernel is booting [http://0.0.0.0:6806]
I 2022/03/17 07:11:54 conf.go:479: pre-init database size [1.2 MB]
I 2022/03/17 07:11:54 index.go:134: use existing database for box [20210808180117-czj9bvb]
I 2022/03/17 07:11:54 index.go:216: resolving refs...
I 2022/03/17 07:11:54 index.go:355: resolved refs [56]
I 2022/03/17 07:11:54 conf.go:503: post-init database size [1.2 MB], tree stat [count=47, size=997 kB]
I 2022/03/17 07:11:54 working.go:133: kernel booted

### 更多信息 More information

servePath试过不加，加域名，加域名和代理端口。试过--ssl，也尝试内网直接https加ip访问，结果是ERR_SSL_PROTOCOL_ERROR
docker run -d --name='SiYuan' --net='host' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -e 'TCP_PORT_6806'='6806' -v '/mnt/user/Nas/Documents/Notes/SiYuan':'/root/Documents/SiYuan/data/':'rw' -v '/mnt/user/appdata/SiYuan':'/home/siyuan/Documents/SiYuan':'rw' 'b3log/siyuan' --servePath="192.168.1.100:6806" --ssl --accessAuthCode="14383610"

**Comment by 88250** [comment]
`--servePath` 是浏览器访问时使用的域名，比如 `yourdomain:443`。

**Comment by casselluu** [comment]
> 

因为80,443被联通封堵，用nginx1880和18443反代的，试过域名加端口，没有用
