### ISSUE TITLE
引用块和嵌入块搜索功能优化

### ISSUE THREAD

**Issue by codeMonkeyWang** [siyuan-note/siyuan#4285]
### 遇到的主要问题

因为思源文档是以块为单位进行组织的，引入块和嵌入块的时候也是从全部文档进行搜索的。

所以在长期使用之后可能就会出现信息淹没的问题，无论你搜索什么关键词都能搜索出大量的结果。使用SQL语句费时费力，同时也并不友好。并且在文档写一半的时候去查询如何使用 SQL 是非常影响工作节奏的。

并且，有时候会出现无法搜索到想要的块的情况：

比如说我想引入一个介绍显示器屏幕亮度的我块，但是显示器这个关键字可能只是在文档的大标题里出现了，在具体的块里面只出现了亮度，并没有出现显示器关键字。而直接搜索亮度关键字可能出现了大量的冗余的结果，选择起来非常困难。

我希望能够先搜索出文档块，然后在在文档块下选择标题块的方式来引入。

### 可能的最优解决方案 

1. 希望提供与或非一类的操作，比如 同时包含 A 和 B 的内容，使用 A && B （使用两个&&符号可以防止与原来内容就有的&符号发生冲突）
2. 引入点（.)搜索符，类似于编程里面的点，可以先搜索文档块，然后使用点的方式把子文档列出来。（Obsidian 里面使用了#进一步选择子标题，我觉得也是个不错的方式）。
同时，建议在设置里面添加选项，设定默认的搜索级别。例如，我只想搜索一二级标题，和列表标题，可以通过多选框勾选来实现。
或者我默认只想搜索文档块和标签，就可以把别的类型都屏蔽掉。

### 描述候选的解决方案 Describe the candidate solution

可以考虑在搜索框上面添加标签和文档类型的下拉选项，我并不认为这是个优雅的解决方案。

**Comment by 88250** [comment]
你好，全局搜索的类型筛选能解决这个问题吗？

**Comment by codeMonkeyWang** [comment]
> 你好，找到这种类型的筛选能解决问题吗？

还有一个问题，我在一个文档里面想找一些打上特定标签的块，也是没有办法搜索到的。

**Comment by 88250** [comment]
大概明白了，但是短期内搜索应该是不会改进了，高级搜索还是只能通过 SQL 进行。

我们期待社区挂件能够实现一些可视化的高级查询功能，感谢理解。
