### ISSUE TITLE
安卓端导出markdown失败

### ISSUE THREAD

**Issue by Anonymity-0** [siyuan-note/siyuan#4291]
### 描述问题 Describe the problem

每次将文件导出markdown的时候浏览器跳转到http://xxxxxx:6806/export/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92.zip
就会显示连接失败。

### 期待的结果 Expected result
希望能成功导出markdown文件

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
你好，我这里使用 Android 端伺服，在桌面端浏览器 Chrome 下面是正常的。

**Comment by 88250** [comment]
我们先关闭了，如果有进一步信息请随时补充，谢谢。
