### ISSUE TITLE
希望提供swagger格式或者其他任何结构化格式的API文档

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#4293]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

用于通过程序自动对接思源的API到Quicker子程序

![image](https://user-images.githubusercontent.com/35998162/158816720-0b1d12bd-7666-4d7b-b599-4fdc4cebaf83.png)

### 描述可能的最优解决方案 Describe the optimal solution

提供swagger格式或者其他任何结构化格式的API文档

**Comment by 88250** [comment]
这个估计需要社区开发者贡献了，分身乏术，感谢理解。
