### ISSUE TITLE
导入 Markdown 文件夹时卡住

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#4295]
### 描述问题 Describe the problem

从文件夹中导入文件夹时突然卡住
![4ER4$SNEJK{J~K_E%_3HDLW](https://user-images.githubusercontent.com/54146035/158833409-6e8f335b-34d4-434f-bb05-8e8c916d4487.png)

经过实验，在文件夹里放两个文件分别选择导入`markdown文档`没有任何问题
但只要选择导入`markdown文件夹`就会卡住，事后进行对比，发现选择导入的内容没有缺失，只是导入界面会卡住无法进行操作

**Comment by 88250** [comment]
使用的是最新版吗？

**Comment by UltramarineSky** [comment]
是最新版的，用API文档做得实验

![文件夹导入](https://user-images.githubusercontent.com/54146035/158838263-7ca4b1af-de26-4ccc-bfff-db8602433557.gif)
