### ISSUE TITLE
标题折叠展开后，下方的列表项块重复，删除后重建索引

### ISSUE THREAD

**Issue by Dammyxy** [siyuan-note/siyuan#4297]
### 描述问题 Describe the problem

标题折叠展开后，下方的列表项块重复，删除后重建索引
Please describe your problem as clearly and accurately as possible.
-->

### 截屏或者录屏演示 Screenshot or screen recording presentation

(It is recommended to use [Screen2Gif](https://www.screentogif.com/) to record the screen under Windows. If it is related to the editor input, please open the `Image - Key Strokes` after recording with Screen2Gif)
-->
![标题折叠列表项块重复](https://user-images.githubusercontent.com/48867926/158936702-4a9acc06-5261-4b2c-810b-3be998ebe0ba.gif)

### 版本环境 Version environment

* Version: 1.9.1
* Operating system: win11
* Browser (if used): 

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8301513/siyuan.log)

**Comment by Vanessa219** [comment]
多谢，是由于 https://github.com/siyuan-note/siyuan/issues/4288 造成的。已修复
