### ISSUE TITLE
多选块样式设置

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4298]
如图3个段落块，全部选中后，里面的文字是无法选中的。如果想加粗，只能逐个段落块加粗。
![image](https://user-images.githubusercontent.com/5968678/158942319-58a70299-1f0d-4b2b-a6bd-34c120035305.png)

预期效果：
选中块后，连带选中里面的内容。这样就能一键加粗了。

我搜了历史的issue #3037，但好像有点不同。

**Comment by Vanessa219** [comment]
多选的块里面可能已经有部分是粗体、斜体或者代码块等行内元素。如果这个时候加粗的话，很难判断用户想要的最终结果。在没有得到用户预期的结果前，先不进行修改了。

**Comment by HACK21** [comment]
> 



> 多选的块里面可能已经有部分是粗体、斜体或者代码块等行内元素。如果这个时候加粗的话，很难判断用户想要的最终结果。在没有得到用户预期的结果前，先不进行修改了。

语雀编辑器的做法是，如果选中部分存在非加粗字体，则优先加粗，如果已经全是粗体了，则直接变回正常

**Comment by 88250** [comment]
后续请关注 https://github.com/siyuan-note/siyuan/issues/8554
