### ISSUE TITLE
段落内部分文字取消样式时影响整个段落

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4299]
如图四个段落：
1. 第1个段落，可以在部分文字上添加样式
2. 第2、3、4个段落，在部分文字上取消样式时，把整个段落都影响了。
3. Alt + X 添加的样式，在清除样式时，也有这个问题。
![段落内文字样式取消bug](https://user-images.githubusercontent.com/5968678/158944050-fa4f7861-a01d-43f5-be6a-a9a47666a01d.gif)

Win10 + 1.9.0

**Comment by 88250** [comment]
请关注 #2911
