### ISSUE TITLE
标题添加标签快速删除后，标签管理面板出现无法删除的空标签

### ISSUE THREAD

**Issue by WJ231009014** [siyuan-note/siyuan#4300]
### 描述问题 Describe the problem
使用 Ctrl+T 给一级标题添加标签又快速删除后，标签管理面板出现无法删除的空标签(null)

### 期待的结果 Expected result
不创建或可以正常删除"null"标签

### 截屏或者录屏演示 Screenshot or screen recording presentation
1、使用 Ctrl+T 给一级标题添加标签又快速删除后，标签管理面板出现无法删除的空标签(null)。点击删除没用。
![image](https://user-images.githubusercontent.com/41817475/158962809-3035076e-0e85-4752-b87b-c2131ab127c0.png)
![image](https://user-images.githubusercontent.com/41817475/158962833-8985f503-8c09-4c14-b55f-34c5b1d0283a.png)
2、给页面添加"null"标签后，标签显示被引用数，但仍无法删除。
![image](https://user-images.githubusercontent.com/41817475/158962978-24d8bd83-77bb-467c-a753-25e5665c1184.png)
![image](https://user-images.githubusercontent.com/41817475/158962994-7f8f106a-a7ea-42d5-8fa3-6bba07e7e17c.png)

### 版本环境 Version environment

* Version: 1.9.1
* Operating system: Windows 10 专业版
* Browser (if used): 

### 日志文件 Log File
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8302780/siyuan.log)

**Comment by 88250** [comment]
点击标签面板的刷新按钮能恢复吗？

**Comment by 88250** [comment]
我这里有点重现不了，麻烦录屏演示一下操作步骤，谢谢。

**Comment by 88250** [comment]
我们先关闭了，如果有补充信息欢迎随时提供，谢谢。
