### ISSUE TITLE
脚注和自由定制表头

### ISSUE THREAD

**Issue by zhangxm2312** [siyuan-note/siyuan#4301]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
在很多情况下的文字工作和笔记记录中我都需要脚注和自由定制的列表表头，脚注可以帮助我插入我的随想和附加信息，定制的表头（markdown中对有序列表序号的不严格规定，以及word中对列表表头的可定制化）对文字记录的自由度有很大帮助。
另一方面，我不希望在另外某个笔记中写下注释内容再引用块到那里的文本，实际上注释和脚注是与主体文本一体的。

### 描述可能的最优解决方案 Describe the optimal solution
脚注功能可以类似markdown的实现，可以所见即所得的缩略在文本某处。也可以以块的方式嵌入上级块，而显示时显示为自动序号或可定制的上标，如[here]。

### 描述候选的解决方案 Describe the candidate solution
也可以将脚注段放在末尾，做成对文档末尾段落的引用块，而脚注段可以不可见。

### 其他信息 Other information
如果可能希望尽快实现！

**Comment by 88250** [comment]
你好，暂时没有计划支持脚注，目前可以通过引用实现类似效果。以后如果有计划的话会重新打开，感谢理解。
