### ISSUE TITLE
调整云端获取集市哈希和版本检查接口

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4305]
之前是从 rhythm.b3log.org 上获取，这个域是 CloudFlare 代理的，对于中国大陆地区的部分运营商网络似乎不太稳定，需要调整到国内代理接口。

**Comment by Tlonglan** [comment]
这个就是那个引起加载失败的问题吗😲

**Comment by 88250** [comment]
@Tlonglan 有一种情况是，其他情况还不确定。
