### ISSUE TITLE
崩溃重建索引后，PDF 标注就找不到符合条件的内容块了

### ISSUE THREAD

**Issue by Wonderdch** [siyuan-note/siyuan#4306]
### 描述问题 Describe the problem

崩溃重建索引后，PDF 标注就找不到符合条件的内容块了

![image](https://user-images.githubusercontent.com/12708888/159102592-2feb4903-9d0d-4bf7-9be2-bf666111457c.png)

### 版本环境 Version environment

* Version: 1.9.0
* Operating system: win10
* Browser (if used): edge

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8308418/siyuan.log)

**Comment by 88250** [comment]
重建索引的问题最近在陆续修复，请先升级到最新版后再观察，如果能够找到稳定重现步骤，麻烦随时补充，非常感谢。
