### ISSUE TITLE
建议开放切换页签的快捷键

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4308]
切换页签目前占用了`Ctrl + Tab`和 `Ctrl + Shift + Tab`这两个重要的快捷键，而顺序和倒序切换页签这个功能却很鸡肋（原谅我的直白）。

### 考虑如下这个普遍的使用场景
你在读/写一篇笔记，遇到一个引用块。你点过去查看详细内容。
> 为什么非要点进去看而不是使用浮窗？
> 1. 因为浮窗展示的不全，你可能要看整个文档块，而不是仅仅那一个引用的块
> 2. 等浮窗出现有延时，不如直接点过去看速度快
> 3. 浮窗也没大纲，在浮窗编辑体验也不好。总之浮窗没有直接打开新页签来得方便

你点开这个文档块后，这个块可能并不是在当前页签的旁边打开（在之前已经打开了的情况下），而是隔了很远。由于标签页开了很多，这个页签甚至不会在顶部标签栏显示。
![image](https://user-images.githubusercontent.com/5968678/159112079-a0b3ac8b-b77a-490c-b9fc-6585038e0c7b.png)

你在浏览了新开的这个块的内容后，然后想回到之前的页签。此时顺序/倒序切换页签都没用。你只能通过后退一步步回去。但是后退默认是`Ctrl + [`，这个键在右手区，要按这个键你就得把右手从鼠标上拿下来。如果有文字工作或编程的朋友，应该明白这个操作是很割裂的。
> 可能你会说右手区那么多键，难道你平时就不需要把右手从鼠标拿下来吗？但是，那些键基本是在编辑的时候使用的，手本来就在键盘上。而在多个页签之间跳来跳去时，你的右手正在鼠标上点击/滑动滚轮。这是不一样的。

### 目前变通方案
只能在左手区自定义快捷键来实现前进和后退，可是最好用的`Ctrl [Shift] + Tab`这个键被占用了。
因此，申请将切换页签的快捷键释放出来。

最后说一下顺序/倒序切换页签这个功能，什么场景会用到呢？打开一堆页签，然后从左到右一个个看吗？浏览器的确是这样的，但他是浏览器啊，编辑器并不适合这个逻辑。
如果能做到类似`VSCode`、`IDEA`等软件那样，`Ctrl + Tab`切换最近打开的页签，就最好了。我不知道开发者现在用的什么开发工具，但`Ctrl + Tab`肯定不是顺序切换页签。这个建议之前提过一次#3812

### 兼顾
可能有人就喜欢类似浏览器切换页签的逻辑，那么建议加一个禁用的开关，或者把这个快捷键也加到设置里面，不喜欢的就可以删掉，各取所需。

**Comment by 88250** [comment]
这个快捷键应该不会支持自定义，后期会加入切换最近使用文档 https://github.com/siyuan-note/siyuan/issues/3293

感谢反馈。

**Comment by whuwangyong** [comment]
好的，我再Argue一下：
由于这些笔记的关系是网状，所以不管是顺序还是倒序，这种线性的切换顺序都满足不了需求。可惜了ctrl tab键。

**Comment by iamqiz** [comment]
> 好的，我再Argue一下： 由于这些笔记的关系是网状，所以不管是顺序还是倒序，这种线性的切换顺序都满足不了需求。可惜了ctrl tab键。

用autohotkey改键
