### ISSUE TITLE
列表块里面的代码块无法单独选中

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4309]
下图是列表块里面的引用块和代码块的区别：
- 引用块前面有个图标
- 代码块前面没有

有序和任务列表也有该问题。

![列表里面的代码块无法选中](https://user-images.githubusercontent.com/5968678/159116447-b9d690d6-6d8b-4b6a-813a-18580840ffa3.gif)

后果是，上图中的代码块，如果要达到下面的效果，会很难：

![image](https://user-images.githubusercontent.com/5968678/159116494-45d1be41-72c7-4cc5-8d36-34bc4e8c1a1a.png)

Win10 + 1.9.2

**Comment by 88250** [comment]
* 使用 Ctrl+/ 选择并拉出菜单
* 使用 Shift+↑↓ 逐步扩选

需要在列表项代码块前面插入块可以试试：Ctrl+/ 然后 Ctrl+Shift+B

**Comment by whuwangyong** [comment]
谢谢！又学会了 Ctrl + / 这个新技巧！
