### ISSUE TITLE
关于新建[今日日记]的需求

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#431]
新建日记并不仅仅是题目是当天日期,日记页在关系图中,也应与普通页,块,标签,等有显示区别,可进行过滤显示。

该功能有具体需求有两点:

1. 新建日记时的标题可进行自定义设置 如 20201106或2020-11-06等

2. 日记页在关系图中与普通页有区别,可通过过滤器进行过滤显示,如不显示日记页,仅显示与日记页相关联引用,日记页中未引用普通页等供使用者在回顾个人知识体系时使用

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/399 中一并考虑，谢谢建议。

**Comment by hopebird** [comment]
日记应该有自己独特的模板和样式，并且至少能按月归入文件夹中。比如为知笔记的这种就很好看。
![IMG_0634](https://user-images.githubusercontent.com/67953024/104007138-71e19500-51e2-11eb-961c-4bd66274e639.jpg)

**Comment by 88250** [comment]
@hopebird 嗯，支持配置日记名称、存储路径还有使用的模板。
