### ISSUE TITLE
列表里面拖动块删除块等操作导致状态异常

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4310]
![状态异常319](https://user-images.githubusercontent.com/5968678/159117103-13090eac-baf7-449d-87d2-21eeb3a1163e.gif)

如上图的操作，反复执行。拖动块、删除块、`Ctrl Z`、`Ctrl Y`反复执行。
半小时异常4次。
日志：
[siyuan - 副本.log](https://github.com/siyuan-note/siyuan/files/8308977/siyuan.-.log)

```
E 2022/03/19 17:29:28 transaction.go:270: load tree [id=20220319150544-aal2jjx] failed: block not found
```

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/4312 中处理，感谢反馈。
