### ISSUE TITLE
OneNote://协议访问时提示没有权限，是编码格式问题

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#4311]
### 描述问题 Describe the problem
将含有中文的OneNote的链接复制到思源中，可以显示，但是点击会报错，而在Word中粘贴则没有问题。
错误信息是：

```
无法打开位置。该位置可能不存在，或者您可能没有打开该位置的权限
有关详细信息，请与onenote:D:/
OneNote/%E8%82%A1%E7%A5%A8%E5%88%86%E6%9E%90/%E8%82%A1%E796A5%A81.one#%E7%94%B3%E4%88%87%E4%B8%8A%E8%AF%8150ETF的所有则联系。
```

我的理解是思源笔记本身显示的是utf8格式，但执行时会把上面utf8格式转成url格式（也就是有很多%表示utf8字符），估计是为了确保跨网络和PC都能进行处理。我把上述url格式转成utf8之后用 cmd run也能访问。

由于我不清楚什么情况下一定要用url格式，所以不好建议直接用utf8替换掉。

另一个需求是，希望 iframe 能嵌入外部 oneNote:// 连接。

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
这里是按照 Markdown 规范实现的超链接地址处理 https://spec.commonmark.org/0.30/#link-destination

你试下用超链接，地址部分不要手工编码，还是用中文的看看。先关闭了，如果有其他信息随时讨论，谢谢。

**Comment by jabobian** [comment]
我一直是用的超链接，onenote://

全英文地址没问题。
地址只要含中文就会有问题 onenote://D:/OneNote/股票&经济交流/入门.one#银行股&section-id={DA52B4D5-B525-41E4-8D72-281118291027}&page-id={F5B8D35F-93AD-4E1C-B852-7ABF411FE3DD}&end
我自己定义了一个onenote1://协议，在协议处理的exe程序里面把上述 %xx 表示utf8字符转成 utf-8 就可以正常访问。

但是全英文也不能嵌入到ifame中显示。估计要一个html服务器。

`url=%1%
url:=StrReplace(url,"onenote1:","onenote:")
cmd := EncodeDecodeURI(url, false)  ; decode url
run "%cmd%"
return

;- from user 'teadrinker'
;~ https://www.autohotkey.com/boards/viewtopic.php?style=17&t=84825
EncodeDecodeURI(str, encode := true, component := true) {
   static Doc, JS
   if !Doc {
      Doc := ComObjCreate("htmlfile")
      Doc.write("<meta http-equiv=""X-UA-Compatible"" content=""IE=9"">")
      JS := Doc.parentWindow
      ( Doc.documentMode < 9 && JS.execScript() )
   }
   Return JS[ (encode ? "en" : "de") . "codeURI" . (component ? "Component" : "") ](str)
}`
