### ISSUE TITLE
列表里面拖动代码块导致该块异常重复

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4312]
在复现状态异常的时候，出现另一个bug：
- 在列表块里面，将一个代码块拖到上面组成超级块之后，代码块仍然在原来的位置保留了一份。
- Ctrl Z 无法撤销
- 反复的Ctrl Z Ctrl Y 之后，导致拖动的那个代码块在列表下方不停重复。

![拖动快bug319](https://user-images.githubusercontent.com/5968678/159117458-11865a1f-7ba4-4528-850b-5d69ca6e6474.gif)

**Comment by 88250** [comment]
这个问题麻烦等 v1.9.3 发布以后进行回测，谢谢。

**Comment by 88250** [comment]
你好，目前好像无法重现了，先关闭了。
