### ISSUE TITLE
运行时崩溃、卡住，无法打开笔记本；差点丢失了笔记。

### ISSUE THREAD

**Issue by Light0457** [siyuan-note/siyuan#4318]
### 描述问题 Describe the problem

在撤销粘贴过来的文档或者在调整排榜的过程中，出现了突然间的崩溃，弹框显示错误。接着就是重建索引、卡在了截图所示的位置。
许久都没动静。
强制退出后再重新进来，也仍然会卡住。
此时尝试使用另一台电脑打开笔记，会出现找不到指定引用块的情况。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/6023553/159144125-cf599722-93c8-4531-864f-0898a0d70a0d.png)

### 版本环境 Version environment

* Version: 1.9.0, 1.9.2
* Operating system:  Mac
* Browser (if used): 

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8310601/siyuan.log)

### 更多信息 More information
<img width="1891" alt="image" src="https://user-images.githubusercontent.com/6023553/159144455-a94474a6-95cf-4569-83e7-fc4468cfb1e3.png">
强制退出后，卡在了这样的界面：加载不出任何笔记，笔记本也打不开。

然后经试验，将思源删掉后再重新安装、再打开，就可以正常打开笔记了。

**Comment by Light0457** [comment]
补充：
强制退出后，卡在了这样的界面：加载不出任何笔记，笔记本也打不开。
<img width="1891" alt="image" src="https://user-images.githubusercontent.com/6023553/159144455-a94474a6-95cf-4569-83e7-fc4468cfb1e3.png">

**Comment by 88250** [comment]
请提供一下日志文件。

**Comment by Light0457** [comment]
日志是指temp文件夹下的这个siyuan.log吗？
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8310601/siyuan.log)

**Comment by Light0457** [comment]
> 请提供一下日志文件。

日志文件补充上去了。然后补充了一些情况。以及试验下来、出错后重装程序可以打开

**Comment by ohyessir** [comment]
我也是。之前是写东西的时候发现写错了，然后快捷键ctrl+z撤销时候，撤销个3-4次就会崩溃。今天是复制其他页面的内容，一粘贴到代码块里面就崩溃了

**Comment by ohyessir** [comment]
今天真的太频繁了，随随便便复制粘贴过来就会崩溃。重建索引后又把复制的内容重新粘贴一次软件又不崩溃。感觉不是复制的内容问题。

**Comment by ohyessir** [comment]
在把一段代码使用ctrl+shift+k快捷键设置代码块时，崩溃了

**Comment by ohyessir** [comment]
还真的丢笔记了卧槽。。。。。

**Comment by 88250** [comment]
重建索引的问题目前还在定位，请帮忙留意稳定重现步骤。

楼主的问题应该是内核在某个情况下卡住挂起了，强制结束内核进程并重启应该能恢复。

先关闭了，请帮忙留意重现步骤，谢谢。

**Comment by ttimasdf** [comment]
> 我也是。之前是写东西的时候发现写错了，然后快捷键ctrl+z撤销时候，撤销个3-4次就会崩溃。今天是复制其他页面的内容，一粘贴到代码块里面就崩溃了

这个确实，特别是和代码块、引用块相关的撤销操作，特别容易崩溃，有时候就是简单的格式错误，而且没办法撤销，有时候是崩溃。但我至少没丢笔记。

非常容易崩溃的地方在：

1. 在引用块、代码块的第一行、最后一行增加、删除内容，然后撤销、重复
2. 代码块的倒数第一行最开头，加个回车
3. 代码块的最后一行，空行，粘贴内容。很多时候会粘贴到代码块后面的文本段落中。此时撤销，很大概率会格式错乱（丢掉代码块倒数第二行，或丢掉整个代码块），同时历史记录也出问题，无法恢复到粘贴前的状态。

**Comment by 88250** [comment]
@ttimasdf 请保持版本升级，如果方便的话请把 设置 - 关于 里的这个选项打开，感谢。

![image](https://user-images.githubusercontent.com/873584/159727341-42dbb79e-628e-4959-bb7d-5e9aee3e5ff2.png)
