### ISSUE TITLE
关于浮窗上下文按钮，添加一个默认开启或关闭的选项

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#4320]
现在上下文按钮是默认关闭的，在快速查阅笔记的过程中，不可避免的带来了各种不便，我们需要一次又一次的点击按钮才能查阅到我们想知道的内容。因此提议上下文按钮添加一个默认开启/关闭的选项。以下提供两个场景。
不会加投票，找半天没找到先这样了（放弃治疗）
场景 1

当我快速过滤已有的知识点的时候，想知道一首诗词的下一句是什么（如图 1），这时候我就要点开虚拟链接，但由于上下文按钮是默认关闭的（图二），我需要再去点击上下文按钮，才能看到诗的下文（如图 3）。若是每一首诗词都要复习，我就需要重复这个繁琐的操作 6 遍，甚至到了后期积累多了就需要几十遍。
![image](https://user-images.githubusercontent.com/101959415/159146548-e707deb6-664c-4a51-8f2d-a68e0c690620.png)
![image](https://user-images.githubusercontent.com/101959415/159146555-c5b86cdc-7156-42fc-a53c-fffaeba5cdc8.png)
![image](https://user-images.githubusercontent.com/101959415/159146561-795cb2c5-0948-4a24-a7dd-1e979e5bf72a.png)

场景 2（感谢大米大佬提供）
![image](https://user-images.githubusercontent.com/101959415/159146564-ef3868d5-bd9b-400e-a01a-8bb3ea2b5537.png)

在阅读 PDF 使用标注引用做批注的时候，不默认开启就特别麻烦，浮窗是这样的，开启上下文后是这样的
![image](https://user-images.githubusercontent.com/101959415/159146569-e132fb82-8cd8-4a6e-95bc-44a698040be2.png)

**Comment by Zuoqiu-Yingyi** [comment]
关联链滴投票: [关于浮窗上下文按钮，添加一个默认开启或关闭的选项 - 链滴](https://ld246.com/article/1647743396243)

**Comment by netdog2019** [comment]
建议参考fly大佬的提议的方式展示~~~

**Comment by Zuoqiu-Yingyi** [comment]
可以先使用 [多窗口功能 - 链滴](https://ld246.com/article/1649992440500) 顶顶
- 鼠标中键单击(在新窗口打开块)
- Shift + 鼠标单击(在新窗口打开块并聚焦)

**Comment by 88250** [comment]
正如社区回帖中 fly 所言，这个问题的本质是引用计数浮窗的逻辑没有使用反链逻辑，导致聚焦和上下文无法平衡，不是开启上下文按钮是否默认能解决的。

这个问题我们新开一个 issue 考虑 https://github.com/siyuan-note/siyuan/issues/6853 感谢各位讨论。
