### ISSUE TITLE
光标无法进入剪切之后剩下的空段落

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4321]
如图，无论列表还是正文，将中间的内容（是内容，不是块）剪切掉之后，通过键盘上下移动光标，光标无法进入空段落。
但是，如果通过退格键删除内容，则光标可以进入空段落。
另外，标题块的表现行为与段落、列表不同：剪切内容时，整个标题块都不见了。

![剪切后的空段落光标无法进入](https://user-images.githubusercontent.com/5968678/159149569-360255d0-48d2-4eee-b6c4-2bb5d83f75cc.gif)

相关issue：#4167

**Comment by Vanessa219** [comment]
标题的块类型和使用方式和段落块不同，因此交互也会有细微的差别。
