### ISSUE TITLE
设置与搜索栏类型过滤、双链建议过滤的优化

### ISSUE THREAD

**Issue by mindstudy** [siyuan-note/siyuan#4322]
1.8.6实现了设置与搜索栏中的类型过滤相互独立，设置过滤类型更加快捷。

现有优点：
由于 [[ 双链建议菜单使用的类型过滤是设置-搜索-类型，相互独立后双链建议菜单范围可以缩小，比如可以设为只搜索页名、标题名等等。

一点冲突：
标签/固定搜索界面使用的类型过滤也是设置-搜索-类型，如果上述双链的类型过滤范围小，一些结果搜索不到

建议考虑：
标签/固定搜索界面使用搜索栏的类型过滤（要不要在该界面新增类型过滤按钮都行）

或者给 [[ 双链建议菜单的类型过滤在设置-搜索单开选项

**Comment by 88250** [comment]
[[ 块引搜索已经是按照 设置 - 搜索 - 类型 中进行过滤的。

**Comment by mindstudy** [comment]
> [[ 块引搜索已经是按照 设置 - 搜索 - 类型 中进行过滤的。

所以缩小了[[ 块引搜索，就影响到标签/固定搜索，反之亦然

能优化当然最好，这个事情也不急

**Comment by 88250** [comment]
全局搜索里面有单独的类型可以设置

![image](https://user-images.githubusercontent.com/873584/159168486-fe78b9bf-4b27-4a4a-a541-aec09ab442a6.png)

**Comment by mindstudy** [comment]
<img width="610" alt="Screen Shot 2022-03-20 at 11 39 10 PM" src="https://user-images.githubusercontent.com/23169045/159170366-090dd813-aa90-4ca7-9f50-92cc8e6fda15.png">

指的是标签面板，还有 Ctrl+Shift+F 出来的面板，该界面是没有类型设置的

**Comment by 88250** [comment]
哦，这里估计暂时不考虑类型过滤了，后面如果有更多人需要我们再考虑吧，感谢理解。

**Comment by mindstudy** [comment]
OK
