### ISSUE TITLE
PDF 页签 Ctrl+F 和全局搜索冲突

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#4324]
![image](https://user-images.githubusercontent.com/88605687/159163646-6d80366d-48a7-491f-9c17-b5c100dc3d98.png)

**Comment by 88250** [comment]
这个问题应该已经在 v1.9.5 中修复，请帮忙确认一下，谢谢。

**Comment by Kitsuta-le** [comment]
> 这个问题应该已经在 v1.9.5 中修复，请帮忙确认一下，谢谢。

是的，已解决
