### ISSUE TITLE
复制 Markdown 任务列表第一项为标题时错位

### ISSUE THREAD

**Issue by JOYCELEEEEE** [siyuan-note/siyuan#4325]
### 描述问题 Describe the problem

见录屏

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/89592448/159168794-1e5d6d4d-b208-4b48-9070-14af925d912e.mp4

### 一个优化建议：ctrl+L 任务列表能否直接加在光标所在的行？

https://user-images.githubusercontent.com/89592448/159168605-ee0b48c8-2bea-4c99-a0d7-10a48dea1ee0.mp4

### 版本环境 Version environment

* Version: 1.9.2
* Operating system: windows

### 日志文件 Log File

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8311496/siyuan.log)

**Comment by winter60** [comment]
> 一个优化建议：ctrl+L 任务列表能否直接加在光标所在的行？

其实可以用“【】 ”或者“[]”打出复选框 @JOYCELEEEEE

**Comment by Belf-hu** [comment]
> > 一个优化建议：ctrl+L 任务列表能否直接加在光标所在的行？
> 
> 其实可以用“【】 ”或者“[]”打出复选框 @JOYCELEEEEE

很多时候都是输入完后才会想着把当前块变成个任务块，
现在无论是ctrl+l 还是【】都无法实现这种情况的操作。

**Comment by 88250** [comment]
块标菜单里面有个转换。

**Comment by JOYCELEEEEE** [comment]
> > > 一个优化建议：ctrl+L 任务列表能否直接加在光标所在的行？
> > 
> > 
> > 其实可以用“【】 ”或者“[]”打出复选框 @JOYCELEEEEE
> 
> 很多时候都是输入完后才会想着把当前块变成个任务块， 现在无论是ctrl+l 还是【】都无法实现这种情况的操作。

明白了，上面演示的文档有一百来万字，我是想以一级标题为一个任务点，每天都用sql进行随机学习，手动加不现实，于是在外部对原文本进行批量处理（即加[ ]），但是处理完后导到思源里却错位了...

看来需要等待进一步优化，感谢两位

**Comment by JOYCELEEEEE** [comment]
> 块标菜单里面有个转换。

标题貌似不能实现转换，但是先打出任务列表再将后面的文字设为一级标题却能实现录屏中的效果。
文档比较大，手动转换比较费手
期待这项的优化💪
