### ISSUE TITLE
建议以笔记为单位允许全局设置其代码块语言

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#4332]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
当抓取某些网页资料后，可能存在很多代码块语言需要手动选择，如果能够以笔记为单位，开启设置其代码块语言，这样就可以极大方便网页抓取资料时手动设置各代码块语言的工作量。

**Comment by 88250** [comment]
手动编辑时，编辑器默认会沿用上次使用的高亮语言。剪藏的话估计只能考虑改善剪藏扩展，而不是在思源上加默认设置，感谢反馈。

**Comment by gagmeng** [comment]
> 手动编辑时，编辑器默认会沿用上次使用的高亮语言。剪藏的话估计只能考虑改善剪藏扩展，而不是在思源上加默认设置，感谢反馈。

不是指加默认设置，而是比如我选中某个笔记，某个菜单或右键里有设置统一代码块语言的选项。

**Comment by 88250** [comment]
这个可能不太适用大多数场景（我也不确定），如果后面还有用户反馈的话我们再考虑，谢谢。

**Comment by Achuan-2** [comment]
有的时候确实有这种需求，而替换功能又不支持替换代码块语言，只能复制到vscode用正则来批量改
