### ISSUE TITLE
浮窗下在聚焦返回后部分内容不显示

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4333]
有一篇文章，从大纲可以看到最后的标题是**运行**：
![image](https://user-images.githubusercontent.com/5968678/159211481-bca71940-efc6-4a26-b3e5-4fc4690fc738.png)

在引用这个块的地方，通过浮窗查看。然后选择某个块聚焦，再返回。滚到末尾，通过与前面截图的大纲对比，发现后面还有一个H3和H2的内容没有显示了：

![聚焦返回后部分内容不显示](https://user-images.githubusercontent.com/5968678/159212504-f5ef9ba8-44ab-4c37-807f-e4de87848d28.gif)

> - 点击上面的面包屑导航进行聚焦/返回，也有这个问题
> - 嵌入块的浮窗也有这个问题

前提条件可能是文章得够长。

**Comment by 88250** [comment]
浮窗是聚焦显示的，如果需要上下文需要手动点击浮窗右上角的更多按钮。

**Comment by whuwangyong** [comment]
第一次进浮窗的时候，显示的是全文；
选择某一个块聚焦进去，然后再返回，此时显示不是你刚刚聚焦过的那个块，而是从头显示。而且，由于聚焦的那个块太靠后，反而不显示了。当然点击点击上下文后，又能看到全文，但锚点也是在第一行，而不是你刚看的那个块。我觉得此时上下文已经丢失了。

**Comment by whuwangyong** [comment]
如果用面包屑的话：
1. 在浮窗里面，选择一个标题，点击面包屑导航，聚焦
2. 然后在面包屑导航点击其父块，回来
3. 回来之后并没有停留在之前的位置（图中的“运行”那个标题），而且此时滚到末尾，发现“运行”那个标题块隐藏了
4. 点击右上角上下文，显示全文，且停留在第一行

![image](https://user-images.githubusercontent.com/5968678/159233058-6c299de6-3618-4fb4-b741-b4bec44a565a.png)

**Comment by 88250** [comment]
第二步在面包屑上点击文档块以后是如何回到之前的标题的？正常情况下点击以后标题应该会变为这个文档下面第一个标题。下面是用帮助文档做的演示：

![issue](https://user-images.githubusercontent.com/873584/159257135-9baf79bf-bda5-4c47-95cc-46c26007fd52.gif)

**Comment by whuwangyong** [comment]
我之前想问的是：
在D大动图的这一步，点击面包屑的“主题”后，会跳到“主题”这个文档块的开始处，然后鼠标往下滚动，会发现后面有些内容未显示（只显示了安装、开发两节内容，最后一节“上架主题集市”未显示）。
![image](https://user-images.githubusercontent.com/5968678/159395968-42aa5cb0-2928-49f3-a9e0-b81485a681e4.png)

但我现在理解了：点击上面的面包屑导航，就是聚焦在文章开始处，只显示一部分内容（我发现一般是两个标题的内容）。如果要显示全文，点击上下文即可。这是个特性，符合聚焦的逻辑。

感谢D大耐心解释。
