### ISSUE TITLE
表格中增加针对所选择的行或列统一设置字体、颜色的功能

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#4335]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
比如我要针对指定行、指定列或者所选择的多行或多列进行字体、颜色等相关属性设置，现在是只能以单元格为单位进行操作。

**Comment by tcmtom** [comment]
支持， 功能可以放在这个多选单元格弹出来的菜单里面
![图片](https://user-images.githubusercontent.com/94541098/159451603-a5572370-763f-4402-9dfc-805f03c02bec.png)

**Comment by tcmtom** [comment]
支持， 功能可以放在这个多选单元格弹出来的菜单里面
![图片](https://user-images.githubusercontent.com/94541098/159451603-a5572370-763f-4402-9dfc-805f03c02bec.png)

**Comment by 88250** [comment]
暂时不考虑了，抱歉抱歉。
