### ISSUE TITLE
多种文字格式无法共存

### ISSUE THREAD

**Issue by wandth** [siyuan-note/siyuan#4337]
当我对一段话执行加粗或者加删除线或者行内代码时候，他们无法共存
![GIF 2022-3-21 21-12-57](https://user-images.githubusercontent.com/34237282/159268811-6fa29b62-1c1d-4dfb-afff-99e231c29209.gif)

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/2911
