### ISSUE TITLE
容器块在顶层内容删除后撤销导致状态异常

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4342]
今天晚上连续遇到3次状态异常，受不了了。花费3小时反复测试，终于稳定复现出来：
![容器块状态异常2](https://user-images.githubusercontent.com/5968678/159311512-ac742a57-032b-48d3-825f-b67cf74a4887.gif)

## 复现步骤（以列表块为例）：
1. 创建一个列表，并添加子项
2. 剪切子项的父item（需使用Ctrl X快捷键，鼠标右键剪切不会触发）
3. 用退格键删除父ite
4. Ctrl Z 撤销，触发异常

试了各种列表和引述块，都这样。推测**容器块都有这个问题**。（但是标题块行为不同，剪切时直接整个块消失，没有留下一个可以用退格键删除的空块。标题块的这个特性不知道是哪个版本加的。我记得1.7.x版本，标题块这样操作也会状态异常。
更新：标题块是叶子块，不是容器块。标题块id是下面内容的parent_id。这里混淆了。）

## 日志
不用说了，都是这一行：
```
E 2022/03/22 00:28:33 transaction.go:945: update data is nil
```

## 相关issue
#4310 
#4170

**Comment by whuwangyong** [comment]
补充：

在状态异常后，有时点击重建索引无法退出程序，只能杀进程。所幸数据未丢。
![正在清理过时索引](https://user-images.githubusercontent.com/5968678/159316213-560a942d-28a4-4caf-8b97-2fd8c4554710.png)

![微信截图_20220322003623](https://user-images.githubusercontent.com/5968678/159315888-5e0f5eb2-a85c-4cb8-a705-5593f3df45d6.png)

**Comment by 88250** [comment]
我这里能够重现了，非常感谢！

重建索引的问题稍微进行了调整，下个版本请继续帮忙留意。

老铁早点休息，晚安。

**Comment by 88250** [comment]
按照楼主老铁的思路，补充引述块和超级块的重现步骤：


![issue](https://user-images.githubusercontent.com/873584/159323042-1e1a9f89-8210-488a-94b4-1f82a7ac006c.gif)

![issue](https://user-images.githubusercontent.com/873584/159325594-661660d6-1790-48ad-8bfd-c390e8ad501d.gif)

**Comment by Kitsuta-le** [comment]
太牛了哥！

**Comment by mangost** [comment]
类似（？）异常在删除隐藏的标题后撤销时也会稳定重复出现，如下。


文档：
```
第一行
# 第二行
第三行
```

1. 点击第二行（H1）以隐藏第三行。
2. 用鼠标选中第二行所在块和下方的空白块
3. Backspace。

出现
> 状态异常 v1.9.5


#4422

**Comment by 88250** [comment]
@mangost 升级到最新版试试。
