### ISSUE TITLE
开放同步框架

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4344]
## 背景

该特性是订阅特性，主要用于官方同步无法满足用户的情况（比如容量不够大、单文件大小限制 100MB）下为第三方同步方案提供基础支撑。

## 接口规范

第三方同步方案需实现如下接口：

* 删除云端目录
* 创建云端目录
* 获取云端目录列表
* 获取云端空间数据统计（sync、backup、assets）
* 获取云端空间数据版本和数据统计（backup、assets）
* 获取云端文件索引列表 URL
* 获取上传文件 Token
* 获取云端文件 URL
* 删除云端文件

通过 #4343 提供的文件 API 实现本地文件读写。

**Comment by seekertang** [comment]
作为订阅用户，支持一下这个功能。

**Comment by iceofst** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JCJC01** [comment]
是否类似与joplin或为知笔记的方案？
这两种方案感觉比较好，joplin是用webdav，早期siyuan也开放过；为知是自有服务器，可以自己填写地址就可以使用
希望公有云和私有云都支持，使用者可以灵活选择，如果是只能公有云的话，没有公有云的使用者又要额外买公有云服务，这样还不如自己出siyuan 官方额外容量付费服务更好更安心，以上建议，谢谢你

**Comment by Danielypzhang** [comment]
能否把这个功能做成单独收费项目，不使用官方的云空间，价格优惠点。

**Comment by 88250** [comment]
@Danielypzhang 暂时不考虑做成单独的增值服务。

**Comment by JCJC01** [comment]
请问这个有计划什么时候推出吗

**Comment by 88250** [comment]
@JCJC01 还在考虑中，在此之前我们需要先将新版同步实现正式上线取代旧版同步。

**Comment by JCJC01** [comment]
如果这样子，也就是只能再付费给七牛云才能使用，还不如直接容量不够，思源官方付费扩容；
这样就是失去了这个issue的部分意义了

**Comment by woniuxia** [comment]
> 如果这样子，也就是只能再付费给七牛云才能使用，还不如直接容量不够，思源官方付费扩容； 这样就是失去了这个issue的部分意义了

七牛云有10g 的免费空间，大部分使用都是没问题的。
[免费空间](https://s.qiniu.com/3m2umm)

**Comment by JCJC01** [comment]
思源本身也有8g内存。不知道开放架构能否思源的8g和七牛云10g的叠加。如果不可以，需要来回切换，麻烦，这不是多此一举，就多了2个g

有这个需求的，第一，出于安全私隐考虑，希望数据在自己手上，所以才希望有这个框架开放，放在第三方云，那还不如思源自己出扩容套餐，起码支持思源的开发。
第二，就算七云牛和思源的空间可以叠加，来回切换不嫌麻烦，但是需要这个issue需求的，应该不是要多2个g或者10g的吧，不要质疑为啥需要那么大，如果不需要那么大，就不会有这个需求出来

**Comment by deerainw** [comment]
hhhhh

**Comment by 88250** [comment]
不考虑了，抱歉各位。

**Comment by 88250** [comment]
我们一步到位吧，开源整个项目 https://github.com/siyuan-note/siyuan/issues/5013

**Comment by jearton** [comment]
如果真要增加第三方同步的能力，我也认为直接内置各个OSS厂商的配置，体验是非常好的。举个例子：比如像这款图床工具，也是直接内置了主流厂商的配置。
![image](https://user-images.githubusercontent.com/10370433/170475833-78ac212f-7c07-425d-8432-f45c84b7c68b.png)

而如何对接这些云存储厂商，我觉得使用 rclone 这款开源工具来做是非常合适的。

**Comment by zxcvbnmzsedr** [comment]
如果开放同步的话，思源的订阅岂不是就没啥意义了吗？
那就真变成纯粹是靠爱发电了
