### ISSUE TITLE
笔记按自然升序时排序不正确

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#4345]
### 描述问题 Describe the problem
创建三个笔记，分别以一、二、三、开头，以自然升序排序是时的顺序显示成了一、三、二、，如上传的附件图片所示
![QQ图片20220322101658](https://user-images.githubusercontent.com/13564117/159395182-668c97e9-3617-4721-9e45-c1cc9f438b91.png)

**Comment by 88250** [comment]
自然升序指的是自然数，不包括中文。
