### ISSUE TITLE
PDF导出多次目录层级一直增加

### ISSUE THREAD

**Issue by DaveBoy** [siyuan-note/siyuan#4347]
![image](https://user-images.githubusercontent.com/16101638/159419650-f4928944-f913-4b8d-8e19-cea79b5b240f.png)
我是想导出pdf到已有目录（覆盖已有的文件），但是目前根本无法实现，只会在最后一个目录下面生成一个新目录。
即：第一次导出：桌面-->新文档-->新文档.pdf
第二次我想的是导出成：桌面-->新文档-->新文档.pdf（覆盖）
但是我如图选择目录后，实际会变成：桌面-->新文档-->新文档-->新文档.pdf
（如果按照一定得生成一层目录，此时其实选择到桌面层级也能实现覆盖，但目前似乎无法这样选择，在桌面已有要保存的文件夹名（新文档）时无法选择桌面这个层级，点击保存无法返回而是会打开这级目录（新文档）继续选择）

**这是个很不好的体验，特别是在pdf的时候，不停的创建不必要目录/目录层级**

![save](https://user-images.githubusercontent.com/16101638/159421519-3a2c54b7-d9da-4cea-92ce-0ea9002f0a20.gif)

**Comment by 88250** [comment]
不要放到一个路径下面，用其他文件夹，如果需要合并的话再手动复制。

**Comment by DaveBoy** [comment]
感觉这样不太方便。
目前一般软件导出到是用户自己选到处目录，而不是每次创建目录吧。
而且是pdf这种无太多额外资源的导出方式。

**Comment by 88250** [comment]
会有资源文件的，所以统一按文档名创建目录。

**Comment by DaveBoy** [comment]
好吧   可能是因为我没用到这部分吧
