### ISSUE TITLE
复制网络图片时可以同时保存到本地指定位置

### ISSUE THREAD

**Issue by mingyuezhaowo** [siyuan-note/siyuan#4348]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

复制网络图片到笔记本后，
1. 有时图源会失效，这时笔记本上复制的图片也不能查看了；
2. 墙外的图片在回到墙内后无法显示。

### 描述可能的最优解决方案 Describe the optimal solution

复制网络图片时保存到本地。
参考实现：
Typora 支持在复制图片时保存到本地：

![深度截图_选择区域_20220322152148](https://user-images.githubusercontent.com/17918944/159428420-4ccfdd79-540a-4ea9-b914-ca8956b0adee.png)

### 描述候选的解决方案 Describe the candidate solution

NA

### 其他信息 Other information

NA

**Comment by 88250** [comment]
编辑器页签右上角 `...` 菜单里面有网络图片转换本地。

**Comment by mingyuezhaowo** [comment]
> 编辑器页签右上角 `...` 菜单里面有网络图片转换本地。

找到了。
有考虑在设置里加个总开关不？

**Comment by 88250** [comment]
这个功能无法做成自动的，之前已经做过，不稳定，所以改成手动点击拉取。

**Comment by mingyuezhaowo** [comment]
> 这个功能无法做成自动的，之前已经做过，不稳定，所以改成手动点击拉取。

能不能提供个 api ，尝试下通过挂件实现触发？

**Comment by 88250** [comment]
暂时不考虑发布正式的 API，如果需要可以打开开发者工具看下这个功能对应的请求。

**Comment by mingyuezhaowo** [comment]
OK, 抽时间试试。
