### ISSUE TITLE
自定义显示字体和正文字体大小、自定义界面显示缩放比

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#435]
大一些的字体和界面按钮可以在大屏幕上更好地显示和观看。

对比下 Zettrl 的文档页面，大字体看着的时候眼睛省劲很多，看着更舒服。

所以希望可以提供选项，用于调整局部文档的字体和字体缩放比、全局布局的缩放比。

**Comment by 88250** [comment]
整体界面缩放 

![image](https://user-images.githubusercontent.com/873584/98950013-6dc32f00-2533-11eb-870b-d3e1e71772ab.png)

**Comment by 88250** [comment]
我们先做编辑器内容字体的自定义 https://github.com/siyuan-note/siyuan/issues/504 

其他部分使用自定义主题进行设置，感谢提议。
