### ISSUE TITLE
浮窗支持动态加载

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4350]
https://ld246.com/article/1647924914555

**Comment by netdog2019** [comment]
是不是悬浮窗支持动态加载后就会显示快很多啊。我的很多关键词的悬浮窗显示也非常慢，有图片和文字的关键词，有个需要5s才能显示出来。视频动图已经发到邮箱，供参考。

**Comment by 88250** [comment]
@netdog2019 这个应该是在加载查询嵌入块，查询嵌入块估计要考虑手动加 limit。

**Comment by netdog2019** [comment]
> 

嗯，明白，因为我通常是把一个主题词的内容汇总在一个文档中，如果加limit的话，就只能显示出部分的内容，另外的内容就显示不出来了，这并非我所愿。这种查询有没有可能优化成这种方案，比如像我这样，每个主题词都有个文档，里面都汇总了该主题词的全部内容，默认情况下不刷新，只有我点击刷新时，才会重新查询一次。当鼠标移动到主题词的链接上显示悬浮窗时，直接动态加载对应主题词的那个文档，也只有我在点击刷新时，才会重新查询。这样可能显示出来会不会快很多？

或者有没有其他的优化方式？

**Comment by 88250** [comment]
@netdog2019 点击才刷新查询查询嵌入块的话结果集较小时用起来就不方便了，目前暂时没有优化方案。

**Comment by Zuoqiu-Yingyi** [comment]
希望浮窗动态加载支持后也能有一个全部加载的按钮, 方便整篇文章的查看与复制

**Comment by jhan3657** [comment]
还有长列表也不支持动态加载
