### ISSUE TITLE
Adnroid 端无法插入大的资源文件

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#4357]
### 描述问题 Describe the problem

一些pdf上传时, 提示不支持的文件类型

### 期待的结果 Expected result
正常上传

### 截屏或者录屏演示 Screenshot or screen recording presentation
* 控制台信息 
![image](https://user-images.githubusercontent.com/18739609/159614808-d301edef-75f5-4874-9d61-fcc213579c79.png)
* 前端提示信息
![image](https://user-images.githubusercontent.com/18739609/159614890-7053db83-1ceb-41e4-97ac-ca065b81e0ea.png)

### 版本环境 Version environment

* Version: 1.9.3
* Operating system: Android12 
* Browser (if used): Microsoft Edge 版本 99.0.1150.46 (正式版本) (64 位)

### 日志文件 Log file
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8329342/siyuan.log)

### 更多信息 More information
**是否因为pdf文件过大导致的呢?**
pdf文件我会以链接形式发送到你的邮箱

**Comment by 88250** [comment]
麻烦发送一个 PDF 给我们测试用 845765@qq.com

**Comment by banjuer** [comment]
FYI

「labuladong的算法小抄（修订）.pdf」https://www.aliyundrive.com/s/exkwmmrWi3K
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。



***@***.***
 
发件人： D
发送时间： 2022-03-23 11:00
收件人： siyuan-note/siyuan
抄送： banjuer; Author
主题： Re: [siyuan-note/siyuan] pdf上传bug (Issue #4357)
麻烦发送一个 PDF 给我们测试用 ***@***.***

**Comment by 88250** [comment]
麻烦直接发一下 PDF 作为邮件附件，谢谢。

**Comment by banjuer** [comment]
issue里已经提到文件过大, 邮件发不了



***@***.***
 
发件人： D
发送时间： 2022-03-23 11:32
收件人： siyuan-note/siyuan
抄送： banjuer; Author
主题： Re: [siyuan-note/siyuan] pdf上传bug (Issue #4357)
麻烦直接发一下 PDF 作为邮件附件，谢谢。

**Comment by 88250** [comment]
好的，我试下阿里云盘。

**Comment by 88250** [comment]
对了，之前说的关联查询问题有空的话麻烦看下是否还能重现，v1.9.3 我们改了 SQLite 编译参数，不知道有没有影响到这个问题。

**Comment by banjuer** [comment]
好的



***@***.***
 
发件人： D
发送时间： 2022-03-23 11:43
收件人： siyuan-note/siyuan
抄送： banjuer; Author
主题： Re: [siyuan-note/siyuan] Adnroid 端无法插入大的 PDF 文件 (Issue #4357)
对了，之前说的关联查询问题有空的话麻烦看下是否还能重现，v1.9.3 我们改了 SQLite 编译参数，不知道有没有影响到这个问题。
