### ISSUE TITLE
文档重命名不阻塞

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#4358]
### 描述问题 Describe the problem
1.9.3版本更新后，文档重命名会弹出重命名及写入数据界面，一次大概要6-8秒左右才会重新进入文档编辑界面

### 期待的结果 Expected result
1.新建文档时，能直接输文档名
2.重命名文档时隐藏重命名界面

**Comment by 88250** [comment]
后面改进，感谢反馈。
