### ISSUE TITLE
文档树的Delete键按了没有反应

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#4363]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
需要删除文档节点，只能通过右键菜单。而右键菜单上的快捷键Delete按了没有反应。之前手动删除没有觉得累，现在急需要，因为。
据观察，在设置里面有没有删除的快捷键设置。
我的理解，按了Delete，只是删除文档中的当前光标位置所在内容。

另外能否提供快捷键直接删除，不显示提示是否删除的窗口。比如Ctrl-Delete

难道所有人都没有快速删除节点的需求吗，Am I missing something?
我还需要有一个快速定位到文档树打开的文档的快捷键，类似Supermemo的Alt-C。

**Comment by 88250** [comment]
试试这个操作顺序：Alt+1 切换到文档树，↑↓键选择文档，Delete，Enter。

我先关闭了，如需讨论请随时跟帖，谢谢。
