### ISSUE TITLE
RTL support for lists

### ISSUE THREAD

**Issue by osman1963** [siyuan-note/siyuan#4364]
Hi.. love your app :)
I just noticed that the bulleted lists, when writing with right alignment (alt+R) still appear on the left. Is there something I'm missing, a setting or so that I can use to make the bullets appear on the right when writing RTL languages like Arabic using the right alignment?
Thanks in advance :)

**Comment by 88250** [comment]
Hi, this might be possible with custom CSS (I'm not too sure). We may not consider this as a built-in configuration, thanks for the proposal.
