### ISSUE TITLE
android端数据手动备份"xxx"文件复制失败

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#4366]
### 描述问题 Describe the problem
**确定app已经关掉**, 且**停止了后台**. 备份`org.b3log.siyuan/files/siyuan/data`目录文件时, 经常出现, 某某文件访问失败, 无法复制等等. 
这种情况只能通过云端备份再下载到其他终端. 由于有比较多的pdf文件, 通过云是一个很不合适的方式

### 期待的结果 Expected result
1. 在应用停止的情况下, 能够正常复制文档内容
2. 如果1不能正常满足时, 可否自定义目录, 或者app支持直接导出笔记呢?

### 截屏或者录屏演示 Screenshot or screen recording presentation
![090a10bf514116e0d4bd34d1eddc9b6](https://user-images.githubusercontent.com/18739609/159839230-bf7e865e-bed9-489d-a6dd-cd82cd2ba9e9.jpg)

![acbe1537c798e1a306207cd27453398](https://user-images.githubusercontent.com/18739609/159839242-3ff54e06-9596-49f5-a55b-8d0f1556c203.jpg)

### 版本环境 Version environment

* Version: 1.9.3
* Operating system: Android 12
* Browser (if used): Edge

### 日志文件 Log file
无

### 更多信息 More information
无

**Comment by 88250** [comment]
试下系统自带的打包后发送功能。

**Comment by banjuer** [comment]
> 试下系统自带的打包后发送功能。

文件系统自带的压缩后, 提示有文件无法压缩

**Comment by 88250** [comment]
从第一个截图来看是帮助文档的笔记本，试下删除帮助文档再打包。

**Comment by banjuer** [comment]
> 从第一个截图来看是帮助文档的笔记本，试下删除帮助文档再打包。

安卓... 不能删的啊.. 帮助文档关闭后自己删除得了

**Comment by banjuer** [comment]
目前来看, 无法手动备份的原因确实由于**帮助文档**, 复制时手动跳过是成功的. 
不过需要考虑的是, 云端备份时, 是不是也把帮助文档同步了呢? 对于用户来说会占用上下行流量, 且没有必要的
