### ISSUE TITLE
剪藏插件抓取代码块异常

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#4368]
### 描述问题 Describe the problem
待抓取网页地址：[https://www.yanbinghu.com/2018/09/26/61877.html](url)
原网页效果如下图
![20220324001](https://user-images.githubusercontent.com/13564117/159883970-ae1e01cf-861d-47d4-beb2-0dea3908c36d.png)
剪藏插件抓取后的效果如下图
![20220324002](https://user-images.githubusercontent.com/13564117/159883976-61ba1a04-ac02-418c-9f1d-7cd8be918d9a.png)

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/3266
