### ISSUE TITLE
AppImage  start with error: InitializeSandbox() called with multiple threads in process gpu-process.

### ISSUE THREAD

**Issue by geosmart** [siyuan-note/siyuan#4369]
env: ubuntu 20.04 
```bash
chmod a+x siyuan-1.9.4-linux.AppImage
./siyuan-1.9.4-linux.AppImage        
```
error 

[125654:0324/200243.020324:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by 88250** [comment]
We will disable hardware acceleration https://github.com/siyuan-note/siyuan/issues/4405 in the next version, which may affect this problem. Please wait and upgrade after the release, thank you.
