### ISSUE TITLE
块图标竖项排列时进行倒序

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4374]
当块图标竖项排列时，进行倒序？其他小伙伴也看看是否能接受 😊

https://ld246.com/article/1646494740847/comment/1647878083112?r=Vanessa#comments

**Comment by mindstudy** [comment]
<img width="249" alt="Screen Shot 2022-03-26 at 9 58 31 PM" src="https://user-images.githubusercontent.com/23169045/160242809-541ace63-797f-46c8-b6d7-40932a3e0967.png">

这个问题其实和折叠关系很大，目前标题块和列表块后不容易看出有折叠的内容，小三角是鼠标放上去才显示

Concise主题专门对标题块和列表块的折叠做了处理，增加了红色三点提示。其中列表折叠红色三点是换行显示（如图），小三角位置也指向红色三点提示。这样即便是窗口宽度缩小了，折叠后感觉仍然还可以

要么思源把Concise主题红色三点折叠提示吸收进去，就不用调顺序了  ：）

**Comment by fanglypro** [comment]
> <img alt="Screen Shot 2022-03-26 at 9 58 31 PM" width="249" src="https://user-images.githubusercontent.com/23169045/160242809-541ace63-797f-46c8-b6d7-40932a3e0967.png">
> 
> 这个问题其实和折叠关系很大，目前标题块和列表块折叠后不容易看出有折叠的内容，小三角是鼠标放上去才显示
> 
> Concise主题专门对标题块和列表块的折叠做了处理，增加了红色三点提示。其中列表折叠红色三点是换行显示（如图），小三角位置也指向红色三点提示。这样即便是窗口宽度缩小了，折叠后感觉仍然还可以
> 
> 要么思源把Concise主题红色三点折叠提示吸收进去，就不用调顺序了，也解决了折叠后不容易看出有折叠的内容的问题 ：）

“折叠后不容易看出有折叠的内容”这是因为你的主题把相关样式给取消了，默认设计下有没有折叠内容还是很明显的，有折叠内容时列表圆点的样式会改变，目前基本所有的大纲编辑器都是这种设计的。

**Comment by mindstudy** [comment]
列表折叠后多一个灰圈，即便所有的大纲编辑器都是这种设计的，简洁是简洁了，在认知上貌似并没有深入广大人群的内心。

Concise主题有现在这种样式的原因，正是身边的朋友说即使有灰圈，列表折叠后仍然不容易看出有折叠的内容，这才增加了红色三点提示。当然不喜欢的人照样也会觉得红色三点提示多余、碍眼。

主题这种东西，主观性太强，选择适合自己的就好。另外成熟用户、普通用户的诉求有时并不相同，最终还是交给开发者考量吧。

**Comment by pureTrue** [comment]
“折叠小三角按钮”确实应该离圆点最近才符合逻辑。

因为一般折叠时，鼠标都是从正文部分平移到按钮处，所以这三个按钮应该符合【由近到远、由小到大】的逻辑。

也即：离鼠标近的按钮，应该是最小粒度的块（当前块）；离鼠标远的按钮，应该是块的聚合（当前块与子块的合集）

@Vanessa219

**Comment by Vanessa219** [comment]
看前面几位的需求点是标识不够明显，这个可以通过自定义主题来进行修改。

鉴于从上到下、从左到右的习惯，外加没有太多用户有此需求，目前就不对该 issue 进行修改了。

**Comment by fanglypro** [comment]
issue前面几个回帖可以忽略，那是mindstudy同学歪楼了，他只是推荐下自己的主题样式，和这个issue没有关系

pureTrue是为了回应“从上到下、从左到右的习惯”，和需求没关系

需求在链滴帖子中说的，比如窄宽度情况下折叠第一级列表非常不方便：

![temp233](https://user-images.githubusercontent.com/57083732/167331368-219b0449-448c-475d-9a4b-05c6964cd70e.gif)

正常情况下，我把鼠标放到圆点旁边就可以直接折叠了：

![temp234](https://user-images.githubusercontent.com/57083732/167331506-e6fa64b4-fada-4170-969c-4264c8b70d45.gif)

这个貌似通过改css没法实现吧

能在github上有8个thumbs也不算少了吧:joy:

**Comment by mindstudy** [comment]
fanglypro，我只是好意针对这个issue提出一个css方面的可能性，怎么就成了推荐自己的主题进而歪楼了？

你有你的需求，不代表别人也有这种强烈的需求，用不着厚此薄彼，谢谢

**Comment by fanglypro** [comment]
> fanglypro，我只是好意针对这个issue提出一个css方面的可能性，怎么就成了推荐自己的主题进而歪楼了？
> 
> 你有你的需求，不代表别人也有这种强烈的需求，用不着厚此薄彼，谢谢

@mindstudy ，我没表达清楚我的意思，让你产生了误解，不好意思，你的主题很不错，非常感谢你的主题

这个issue最开始是我在链滴上提的，但是讲述的时候有点偏离实际需求，过分强调设计上的逻辑，导致后续讨论时偏离最开始提这个issue的本意了
