### ISSUE TITLE
删除被引用的内容块时，对用户进行提示

### ISSUE THREAD

**Issue by ttimasdf** [siyuan-note/siyuan#4376]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在删除被交叉引用的内容块时，警告用户可能造成的失效链接。

![image](https://user-images.githubusercontent.com/2762704/159968218-bca538e6-a116-4818-aae1-2b8dc0d327b8.png)

### 描述可能的最优解决方案 Describe the optimal solution

删除被交叉引用的内容块时，弹出警告窗口，以类似 hover 时弹出的窗口的相似样式，列出可能失效的链接

### 描述候选的解决方案 Describe the candidate solution

周期性（如每次后端初始化时、index 时、同步时etc）扫描失效的反链，对用户进行提示。

或者提供一个方式，用户可以手动检查失效链接。

### 其他信息 Other information

TBD

**Comment by 88250** [comment]
被引用的块（定义块）已经有计数显示了，通过计数就能知道该块是否被引用了。

**Comment by 88250** [comment]
先关闭了，如果需要继续讨论欢迎跟帖，谢谢。
