### ISSUE TITLE
从 VS Code 粘贴 HTML 时解析错误

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4382]
我新建了一个文档，在文档中间插入了一个表格，但是从vscode中复制一小段代码粘贴进表格时，不知道为什么，总是粘贴不进去不说，而且在表格下方出现了文档错乱和我要粘贴代码的不断重复粘贴

https://user-images.githubusercontent.com/66512309/160119602-780504a7-047d-43c5-92eb-18282b2c9134.mp4

**Comment by 88250** [comment]
版本是？

**Comment by Faith-YSQ** [comment]
v1.9.4

**Comment by 88250** [comment]
我这里重现不了，麻烦在默认主题下测试看看，如果能够重现，请帮忙制作一个测试用笔记本并打包上传一下，谢谢。

**Comment by Faith-YSQ** [comment]
[20220326090634-ddk6mah.zip](https://github.com/siyuan-note/siyuan/files/8354444/20220326090634-ddk6mah.zip)

https://user-images.githubusercontent.com/66512309/160218861-53dcd468-2a95-4d38-a087-988a671b998c.mp4

**Comment by Faith-YSQ** [comment]
视频是新建笔记本的过程，测试的笔记本已经打包上传了

**Comment by 88250** [comment]
从其他地方复制 `<div></div>` 能够重现吗？

**Comment by Faith-YSQ** [comment]
从其他地方复制，不会重复好像，但是也粘贴不了；

https://user-images.githubusercontent.com/66512309/160220193-3f9e2d20-5599-4d2b-8495-0c4e6623472b.mp4

**Comment by 88250** [comment]
粘贴不了应该是正常的，被识别为 HTML 块，但是表格元素中不能包含块级元素，只能包含行级元素。

重复的问题从 .sy 看，是因为解析错误，导致了行级元素出现位置不对：

![image](https://user-images.githubusercontent.com/873584/160220319-9bae3350-9b54-459c-a42b-a05950f59e3f.png)

正常情况下，思源中不应该存在 InlineHTML 的，你关闭内核以后先手动删除一下 .sy 中的这个节点后重启重建索引。

**Comment by Faith-YSQ** [comment]
好的
