### ISSUE TITLE
搜索范围包括可读路径

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#4387]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
搜索时，已知（或凭经验知道）目标文档所在路径的部分关键字，也就是可读路径中的部分字符串，如果能把可读路径作为文档的属性用于搜索，可以更快定位。

类似用Everything时，只能用文件名快速定位，而用 Lucene 时会把文件名和内容一起建索引。

**Comment by jabobian** [comment]
另一个相关的问题，在Ctrl-Alt-] 移动文档时，能看到列表中有想要的路径，但是如果自己输入这个路径（或者复制粘贴）却显示为空白，我估计和上面不能搜索可读路径是同样的问题。

**Comment by 88250** [comment]
这个估计要用 SQL 查询，字段是 `hpath`，目前的搜索暂时先不动了，等后面通过挂件扩展，感谢反馈。
