### ISSUE TITLE
Windows 上行级元素通过快捷键排版后输入中文撤销异常

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#4388]
![b](https://user-images.githubusercontent.com/38906705/160235400-173764ab-534e-4d31-9474-439262109e5e.gif)

**Comment by 88250** [comment]
我这里重现不了，试下新建的文档能否重现。

**Comment by royc01** [comment]
![A](https://user-images.githubusercontent.com/38906705/160280928-5cfdfe93-9b2d-45bc-8ec3-fe4f54de43c3.gif)
可以重现

**Comment by 88250** [comment]
已经定位到问题，感谢感谢。
