### ISSUE TITLE
表格功能建议

### ISSUE THREAD

**Issue by sunjx97** [siyuan-note/siyuan#4389]
1. 创建表格时不能直接设置行列数，添加行列每次只能添加一行/列，希望创建/调整表格时能**设置行列数**。
2. 批量选中表格然后按backspace无法**批量删除表格内内容**，希望支持。
3. 鼠标停留在表格左/上时，可以**选中行/列**，支持批量选中（和word类似）。
4. 鼠标选中复数表格内容复制粘贴，**直接粘贴在表格内**，现在只能复制整个表格。
5. 希望支持**表格内内容拖动**。

建议可以参考下word里表格工具的各种功能，照搬就行：）

**Comment by 88250** [comment]
关联 https://ld246.com/article/1648294842942

目前暂时先不动了，开发资源有限（就两个人），也许后续会进一步开放编辑器能力，让社区开发者方便参与开发，感谢反馈。
