### ISSUE TITLE
“反链提及”不显示当前未引用文档名称问题

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#439]
若一篇笔记没有被其它文档引用过，则在其它文档中存在的“提及”也不会显示出来，只有当这篇文档被引用过一次后，其它文档提及的当前文档才会显示出来

例如：

# 无提及显示
## AA.md
blabla.....

## B.md
AA blalbalbal。。。

**此时，AA文档中无提及显示**

# 有提及显示
## AA.md
blabla.....

## B.md 
AA blalbalbal。。。

## C.md
((20200121-sdfsdf, "AA")) fsadfa

**此时，AA文档提及会显示B文档提及了AA文档**

**Comment by XinLi0111** [comment]
0.4.0-0.4.2均存在此问题，详细测试是在0.4.2中进行的

**Comment by 88250** [comment]
“提及”逻辑是根据引用时候的锚文本来搜索的，所以如果不存在引用的话也就搜索不到了。
