### ISSUE TITLE
优化拖拽形成超级块时放置位置展示

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4394]
https://ld246.com/article/1648293104820

**Comment by Vanessa219** [comment]
不太明白要怎么优化 😓

**Comment by Temacc0531** [comment]
现在的块拖动还存在以下问题

1. 拖动位置判定过于灵敏，鼠标很难把块精准的放到想要的位置上去，特别是在多级列表中指示条会一直乱跳
![test1](https://user-images.githubusercontent.com/101307399/179915319-45a30d2d-7de1-49a7-a372-47b3da061615.gif)

2. 列表项块项拖出来后就拖不回去了，变成另外一个列表块
![test2](https://user-images.githubusercontent.com/101307399/179915422-d80a5102-8d6b-43b3-b20f-4092596e138d.gif)

3. 指示条指示不够清晰

**Comment by 88250** [comment]
没有找到适合的优化方案，先关闭了。
