### ISSUE TITLE
将本机工作区目录挂载到容器无法启动

### ISSUE THREAD

**Issue by sandianyiyuan** [siyuan-note/siyuan#4403]
### 描述问题 
我在windows10使用思源笔记创建了一个工作区文件夹。
然后再运行一个镜像，将工作区文件夹挂载到容器中:  
`docker run  --name siyuan  -it -d --restart=always  -v E:\work_file\siyuanDocker:/home/siyuan/Documents/SiYuan -p 6806:6806 b3log/siyuan`  
提示`operation not permitted`
![image](https://user-images.githubusercontent.com/22078056/160271562-087ef7e0-de48-4f01-a138-997da7c7fb81.png)
我尝试将`boot/images`目录中的文件删除后重新启动容器，能启动成功。
又将本机备份的`boot/images`中的文件放到目录中重启容器，又报同样的错误。
### 期待的结果
对比了直接运行镜像生成的文件和本机'boot/images'中的文件，没有任何差异，不知为何会报这个错。
我认为svg文件应该不影响启动容器。
### 版本环境 Version environment
使用的镜像：b3log/siyuan:latest IMAGE ID:cbb1c8daf813
操作系统win10，Docker version 20.10.10, build b485636

**Comment by 88250** [comment]
Docker 容器启动时会拷贝一些必须的文件，如果没有权限会停止启动。帮助文档文档中有 Docker 权限相关描述，请参考一下。

**Comment by sandianyiyuan** [comment]
确实是权限问题，进入容器看到文件目录是root用户组的。
windows系统下不知道怎么改文件用户组，换到虚拟机里面搞定了。
