### ISSUE TITLE
笔记编辑与排版显示的建议

### ISSUE THREAD

**Issue by sunjx97** [siyuan-note/siyuan#4406]
## 键入时包住选中内容

希望选中内容后输入 `，```，'，"等可以**直接包住选中内容**，而不是键入时，删除选中的文本。

## 优化美观度的建议

1. 希望中文和英文（引申就是**不同的语言之间**）可以在显示上空开些距离，更美观。
2. **在文档上新建文档**希望能像 notion 一样生成目录样式的索引链接。
3. 显示时**不同块**之间空开些距离，更美观。
4. 显示时如果文段下一行是标题，自动判断文段结束，空开些距离（和 notion 类似）。其实就是根据标题之类**自动分划文章块**，然后再文章块间空开些距离，更美观。
5. 地址栏每一块如果没显示完则在后面加上` ...`，现在断得有点突兀😂 。

关联：
> https://ld246.com/article/1648385956253
> https://ld246.com/article/1648386629917

**Comment by 88250** [comment]
` ``` `估计不行，要输入三次 `` ` ``，单个字符的应该可以支持。

1. 编辑器菜单里有中西文自动空格，输入时不转换
2. https://github.com/siyuan-note/siyuan/issues/2711
3. 还在考虑是否在默认主题上做改动
4. 同上，可以考虑自定义主题
5. 地址栏？如果指的是块引用锚文本的话可以在 设置 - 编辑器 - 块引动态锚文本最大长度

我关闭了，感谢反馈。如果有需要讨论的请随时跟帖，谢谢。

**Comment by sunjx97** [comment]
``` 的话，每次输入 ` 时，仍然**保持文本选中状态**不变（其实所有对内容的包裹都可以键入符号后保持选中不变），``` 就相当于选中并输入了三次 ` 。这样可以吗？


1. 中西文自动空格在编辑器菜单里我没找到orz，docker版本，v1.8.9。

3. 4. 建议这种功能做在主程序里，主题应该只改变样式吧，这样比较符合逻辑

5. 关于地址栏，我的意思是显示的时候如果**没显示完**就加个` ...`提示下，没有提示就截断很突兀。
如notion：
![image](https://user-images.githubusercontent.com/42996565/161426364-5e0c07ad-8aab-4332-aceb-7273beb69967.png)
Windows：
![image](https://user-images.githubusercontent.com/42996565/161426533-58f0ec77-99ef-4e3f-9410-4e351749a060.png)

**Comment by 88250** [comment]
那样的话会有点奇怪吧，普通的文本编辑器（非代码编辑器）基本都是选中文本再输入符号是替换选中文本的。比较专业的编辑器确实会做一些补充优化，这个可能还需要继续收集更多用户反馈来确认。

**Comment by sunjx97** [comment]
确实是代码编辑器的功能，不过感觉很好用，所以希望有😂。
