### ISSUE TITLE
API `appendBlock` 插入多块时顺序不正确

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4409]
https://ld246.com/article/1648080763859

**Comment by netdog2019** [comment]
D大，这个bug又出现了。

**Comment by 88250** [comment]
@netdog2019 我这里测试好像没有发现问题

![image](https://user-images.githubusercontent.com/873584/161410616-60e8dc26-c50e-4631-88c8-9a1bbf35a3fd.png)

**Comment by Zuoqiu-Yingyi** [comment]
@88250 这个 bug 使用该方案在 `v1.9.6` 中可以复现
[使用 API `/api/block/appendBlock` 往超级块中插入内容后渲染错误 · Issue #4283 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/4283#issue-1171468082)

**Comment by netdog2019** [comment]
> @88250 经测试, 这个修复方法可能再次引入了如下 bug, 复现步骤未变😂(`v1.9.6`)
> 
> [使用 API `/api/block/appendBlock` 往超级块中插入内容后渲染错误 · Issue #4283 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/4283#issue-1171468082)

专业~~
