### ISSUE TITLE
1.9.5mac端打开无界面

### ISSUE THREAD

**Issue by xxhh12a** [siyuan-note/siyuan#4410]
### 期待的结果 修复，D大加油！
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8359790/siyuan.log)

### 版本环境 Version environment

* Version: macOS Monterey 12.3
* Operating system: 
* Browser (if used): 

### 日志文件 Log file
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8359790/siyuan.log)

### 更多信息 More information

[](url)

**Comment by xxhh12a** [comment]
[
<img width="1440" alt="截屏2022-03-28 13 13 37" src="https://user-images.githubusercontent.com/55382340/160330752-4f79d098-bd37-430c-bb75-6b14c05d034d.png">
](url)

**Comment by xxhh12a** [comment]
[
<img width="326" alt="截屏2022-03-28 13 16 11" src="https://user-images.githubusercontent.com/55382340/160330854-b002f189-74f1-4ea2-a32e-bcdc82d6cc8f.png">
](url)

**Comment by bearxz** [comment]
我这边也是这个问题。

**Comment by Tukali** [comment]
> ### 描述问题 如题
> ### 期待的结果 修复，D大加油！
> [siyuan.log](https://github.com/siyuan-note/siyuan/files/8359790/siyuan.log)
> 
> ### 截屏或者录屏演示 Screenshot or screen recording presentation
> ### 版本环境 Version environment
> * Version: macOS Monterey 12.3
> * Operating system:
> * Browser (if used):
> 
> ### 日志文件 Log file
> [siyuan.log](https://github.com/siyuan-note/siyuan/files/8359790/siyuan.log)
> 
> ### 更多信息 More information
> [](url)

我也是这个问题，mac M1

**Comment by 88250** [comment]
感谢反馈，请重新下载一下，应该修复了。
