### ISSUE TITLE
行内公式+字体颜色重启软件后渲染错误

### ISSUE THREAD

**Issue by WillisXue** [siyuan-note/siyuan#4413]
### 描述问题 Describe the problem

重启软件后会多出空行

### 截屏或者录屏演示 Screenshot or screen recording presentation

![动画](https://user-images.githubusercontent.com/9125768/160363430-232d4a1e-fdfe-4d35-84af-df524a36a668.gif)

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/2911
