### ISSUE TITLE
Alt+7 反链面板切换文档时没有触发刷新

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4414]
https://ld246.com/article/1648455869854/comment/1648734877895?r=Vanessa#comments

**Comment by fanglypro** [comment]
可以考虑在触发刷新时，面板上的刷新按钮也旋转吗，这样可以告诉用户这时候后台在计算。

不然有时候，反链很多，打开反链面板的时候一篇空白，刷新按钮也不动，打开任务管理器时才能确认这时候后台有没有在计算反链。

**Comment by Vanessa219** [comment]
@fanglypro 感谢建议，下个版本改进。
