### ISSUE TITLE
按窗口换行后使用移动到行首快捷键未移动到真正的行首

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#4425]
### 描述问题 Describe the problem

![截图_20225629085639](https://user-images.githubusercontent.com/54146035/160616275-c3f33b9f-ab57-45a2-ba8a-3b967794bd2e.png)
如图，这是一个因窗口宽度限制换行了的列表项段落，使用光标移动到行首快捷键<kbd>Home</kbd> / <kbd>⌘←</kbd>和选中行首至光标内容快捷键<kbd>Shift+Home</kbd> / <kbd>⇧⌘←</kbd>时，发现选中的内容只到因窗口宽度限制换行后的第二行行首，而非真正的行首。在段落块里也是同样的问题
按窗口换行不是真正的换行，移动至行首应该是到真正的行首吧

### 期待的结果 Expected result
使用快捷键后可以移动到真正的行首

### 版本环境 Version environment
* Version: 1.9.5
* Operating system: win10
* Browser (if used):

**Comment by Vanessa219** [comment]
你使用移动到块首看看

<img width="760" alt="image" src="https://user-images.githubusercontent.com/970828/160835627-c19ee0d8-a052-4342-b73a-ae08ce71fda0.png">

**Comment by UltramarineSky** [comment]
![使用Home键移动到行首](https://user-images.githubusercontent.com/54146035/160966034-839ee89b-4c77-4656-b384-52bdab0f2e91.gif)

win10系统用`Home`快捷键只移到到自动换行后产生的行首

使用vsc时发现vsc里`home`键一下光标移动到自动换行后的行首，两下则移动到逻辑行的行首，不知思源里能否实现
![使用Home键移动到行首 VSC](https://user-images.githubusercontent.com/54146035/160966583-a42d90d8-9e79-4f5f-ab3a-b8bcb3b3f01c.gif)

**Comment by 88250** [comment]
暂时实现不了，自动折行的算法主要依赖浏览器实现。

先关闭了，以后如果有机会的话再研究看看，感谢反馈。
