### ISSUE TITLE
加入附件管理功能

### ISSUE THREAD

**Issue by Asasahn** [siyuan-note/siyuan#443]

**Comment by 88250** [comment]
麻烦大致描述一下场景和用法，谢谢。

**Comment by Asasahn** [comment]
比如我在看一篇pdf或者word然后对照着做笔记这样的场景下 我可能需要多次的打开这篇pdf和word 但我不希望再最小化我的思源笔记然后再去操作 那么在每个笔记的文件夹下加入附件 然后在思源中可以便捷的查找和打开可能就会舒服很多 这些附件个人觉得也是不需要同步的发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2020年11月7日周六 10:39收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asashan <Asasahn@163.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 加入附件管理功能 (#443)

麻烦大致描述一下场景和用法，谢谢。

**Comment by Asasahn** [comment]
其实就是在思源中提供打开附件文件夹中相关文件的快捷方式发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2020年11月7日周六 10:39收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asashan <Asasahn@163.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 加入附件管理功能 (#443)

麻烦大致描述一下场景和用法，谢谢。

**Comment by Asasahn** [comment]
这个文件可以是pdf 视频 照片任何和当前笔记相关的文件 然后思源提供一个快捷方式让我在思源内部点击但是在思源外部开启这些文件 也就是附属于笔记的相关文件 然后在关系图中显示这些附件的名称即可发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2020年11月7日周六 10:39收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asashan <Asasahn@163.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 加入附件管理功能 (#443)

麻烦大致描述一下场景和用法，谢谢。

**Comment by 88250** [comment]
资源文件是放在 assets 目录下的，在编辑器内可以通过 Ctrl 点击打开，也可以在文件树上右键打开文件位置。

**Comment by Asasahn** [comment]
好像ctrl没有办法打开诶 然后就是我觉得很多附件其实可能不需要加入到文档中去 这个逻辑是不是不够简洁呢 附件附属文件 还是应该有一个外挂列表来点击更好吧发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2020年11月7日周六 11:36收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asashan <Asasahn@163.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 加入附件管理功能 (#443)

资源文件是放在 assets 目录下的，在编辑器内可以通过 Ctrl 点击打开，也可以在文件树上右键打开文件位置。

**Comment by Asasahn** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2020年11月7日周六 11:36收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asashan <Asasahn@163.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 加入附件管理功能 (#443)

资源文件是放在 assets 目录下的，在编辑器内可以通过 Ctrl 点击打开，也可以在文件树上右键打开文件位置。

**Comment by Asasahn** [comment]
个人觉得还是这种形式呈现会很符合附件的逻辑一些 因为附件本身很可能和我的笔记并不存在文字上的联系 特别是一些视频发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2020年11月7日周六 11:36收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： Asashan <Asasahn@163.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 加入附件管理功能 (#443)

资源文件是放在 assets 目录下的，在编辑器内可以通过 Ctrl 点击打开，也可以在文件树上右键打开文件位置。

**Comment by 88250** [comment]
不放在文件树目录下的话管理不到的，当做外部文件看待，就和超链接是一类的。

**Comment by 88250** [comment]
我关闭了，感谢讨论。
