### ISSUE TITLE
搜索功能是否可以加文档内容搜索

### ISSUE THREAD

**Issue by jipeng0918** [siyuan-note/siyuan#4438]
知识积累过程，会保存很多文档，PDF，word等，东西多了搜索功能就很重要了，之前我一直用的是OneNote，它有两个很好用的功能：
![image](https://user-images.githubusercontent.com/43375185/160825098-fe34c1d3-6eb6-462a-a1e0-253534712994.png)

1.粘贴文档时，他会提示是嵌入文档，还是插入打印输出

![image](https://user-images.githubusercontent.com/43375185/160825383-26acaf9e-ab4b-4f11-a262-0c2aa1ff3a9a.png)

2.打印输出后（打印输出的是图片格式），就是搜索可以图片内容的搜索。

不知道是否可以加这两个功能。

**Comment by 88250** [comment]
资源文件内容搜索由于技术原因目前实现不了，抱歉。
