### ISSUE TITLE
定义块引用计数浮窗高亮引用处锚文本

### ISSUE THREAD

**Issue by JOYCELEEEEE** [siyuan-note/siyuan#4446]
## 以表格为例
<img width="854" alt="Snipaste_2022-03-30_22-46-49" src="https://user-images.githubusercontent.com/89592448/160864211-d61a3a03-72ae-4137-9179-7ff26060da7a.png">

## 理想效果
<img width="786" alt="Snipaste_2022-03-30_22-55-46" src="https://user-images.githubusercontent.com/89592448/160865161-8959b5ad-0475-40e3-87ca-b46c2a01afe0.png">

**Comment by haogeek** [comment]
附议，在创建引用支持了自定义搜索后，如今锚文本和引用内容之间可以有更大的差别，这个高亮功能就显得更有必要了
