### ISSUE TITLE
Line to identify groups of information.

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#4448]
Hi! I wanted to thank you for implementing several features that are helping me a lot to study! I'd like to request another one, if I'm not abusing your work.

I study by the outliner method. I like to put all my information in a hierarchy order to know where each thing fits within a world of information.

To improve my experience, I would very much like a kind of "line" informing which group my information belongs to.

In the image below, let's imagine that I'm writing a task in the "night" group. Then there would be a line telling all the other subgroups that the information would be inside.

![image](https://user-images.githubusercontent.com/90691302/160899600-71db81f7-e4d2-4608-a1eb-3c10a5c718e3.png)

The customization of the line would be at your discretion. I just leave my idea here.

**Comment by 1995hanjian** [comment]
In the theme [dark+](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus#readme), you can add Attribute Name ‘list-guides’ to a list. Then dynamic list guides will be enabled.

**Comment by taozina** [comment]
@1995hanjian Hi friend. Can you help me? How enable this option? I do not understand.

**Comment by 1995hanjian** [comment]
> @1995hanjian Hello friend. Can you help me? I already downloaded the theme, but when it comes to assigning this value, I can't!

![image](https://user-images.githubusercontent.com/39188734/165026801-1b05790c-63eb-4927-98cf-3a22139efca7.png)

![image](https://user-images.githubusercontent.com/39188734/165026926-8fa87b72-998d-4ef7-8cfc-62c1e9a99f66.png)

just edit in the attribute pannel~

**Comment by 88250** [comment]
Don't consider it as a built-in feature for now, thanks for the suggestion.
