### ISSUE TITLE
SiYuan 1.9.6 for windows 无法完成安装，提示SiYuan 无法关闭。

### ISSUE THREAD

**Issue by tanaer** [siyuan-note/siyuan#4452]
首次在Windows 10 20H2安装SiYuan， 版本是1.9.6
https://release.b3log.org/siyuan/siyuan-1.9.6-win.exe

安装到一半提示这个，一直卡在这里。
![image](https://user-images.githubusercontent.com/3828685/160980595-2f917376-5ad3-4897-9442-b8573e313d28.png)

请问是无法关闭什么呢？ 我电脑上也没有运行过SiYuan（一直卡这里没安装成功过），进程也没有SiYuan

**Comment by isyngo** [comment]
右键——以管理员身份运行

**Comment by 88250** [comment]
按楼上说得试试，我先关闭了。
