### ISSUE TITLE
Docker 端支持网络代理选项

### ISSUE THREAD

**Issue by zbluex** [siyuan-note/siyuan#4453]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

思源笔记使用的环境可能是内网，需要使用Proxy才可以访问外网，如果没有代理功能，则无法正常联网使用。
特别是Docker版本，因其是Go语言编写的，Linux上一些全局代理软件也无法增加到容器中是它支持代理模式，如ProxyChains。希望原生能支持代理模式，应用内配置。

**Comment by 88250** [comment]
设置 - 关于 - 网络代理 可以配置 SOCKS5。

**Comment by zbluex** [comment]
> 设置 - 关于 - 网络代理 可以配置 SOCKS5。

容器不支持设置网络代理

**Comment by zbluex** [comment]
> 设置 - 关于 - 网络代理 可以配置 SOCKS5。

@88250 
容器不支持设置网络代理

**Comment by 88250** [comment]
这个我就不太清楚了，抱歉。

**Comment by zbluex** [comment]
@88250 是容器版本不支持，你们的容器版本里面把这个选项屏蔽了，是否可以开启？

**Comment by 88250** [comment]
抱歉之前没注意到是 Docker 版本，下个版本我们打开这个选项后你再试试看，谢谢。

**Comment by haifong** [comment]
原来之前不行是这个原因；试了下，现在可以了；
非常非常感谢官方对Docker的支持。
