### ISSUE TITLE
关于笔记崩溃的情况。

### ISSUE THREAD

**Issue by ohyessir** [siyuan-note/siyuan#4456]
version：1.9.2
win10.
步骤：记录漏洞的时候会在fofa寻找指纹。
![image](https://user-images.githubusercontent.com/45805851/161084286-c9d26313-b2b9-4511-8023-70a68d8ed177.png)
然后在编写笔记的时候，我是这么写的：
-----------------
\### FOFA：
\```
-----------------
然后在fofa把搜索栏里面的“app="vmware-Horizon"复制到思源笔记的代码块的时候，经常会崩溃
![image](https://user-images.githubusercontent.com/45805851/161085104-170cec07-82cc-475b-b116-e63e41c06378.png)
在重建索引之后会丢失近几分钟内写的笔记。有时候真的都不敢写太多，或者是写完一个地方，等到几分钟使其已经自动保存然后会再写下一个。麻烦了，不好意思

**Comment by 88250** [comment]
请更新到最新版后再看看。

**Comment by 88250** [comment]
我们先关闭了，如果最新版仍然有问题的话请继续跟帖反馈，最好能补充一个重现录屏，感谢。
