### ISSUE TITLE
能调整一下提示文字的位置吗

### ISSUE THREAD

**Issue by Yomance** [siyuan-note/siyuan#4460]
### 描述问题 
当鼠标放在这几个图标上时在图标下面会出现文字提示， 但是文字会被挡住一部分，看着特别难受，
![image](https://user-images.githubusercontent.com/57690311/161250709-13b43e51-ce6e-46fa-83e6-c1f9b87693cf.png)

### 期待的结果 
是否可以根据不同情况更改一下弹出方向，比如在图标的右侧弹出

### 截屏或者录屏演示 Screenshot or screen recording presentation
![IMG_20220401_190822](https://user-images.githubusercontent.com/57690311/161254380-33e8c965-47cb-4968-a463-6d1c4fee2216.jpg)
![IMG_20220401_190829](https://user-images.githubusercontent.com/57690311/161254408-06b8ae62-9bb3-42f6-9e2a-3d92c236c39f.jpg)

### 版本环境  V1.9.6

**Comment by Yomance** [comment]
抱歉 视频没能反应问题，请看这三张图片
![IMG_20220401_190812](https://user-images.githubusercontent.com/57690311/161252267-28cba4b3-428c-4060-9fa6-63f3ba14255f.jpg)

![IMG_20220401_190822](https://user-images.githubusercontent.com/57690311/161252275-72e9d07a-f13f-45f3-b7a0-d867968cfe62.jpg)
![IMG_20220401_190829](https://user-images.githubusercontent.com/57690311/161252281-48f426e5-38b9-4bc0-93c1-bb8f703acf41.jpg)

**Comment by Vanessa219** [comment]
右侧的话左右移动可能也会特别难受，我再放下一点，不要让光标挡住。

**Comment by Yomance** [comment]
> 右侧的话左右移动可能也会特别难受，我再放下一点，不要让光标挡住。

谢谢您的回复

但是如果鼠标指针大小变大了，还得向下调整， 
可以尝试一下获取系统鼠标指针大小，根据不同大小来确定具体位置。
或者在右下角显示这样既不影响左右移动也不影响提示被鼠标挡住。

**Comment by 88250** [comment]
暂时先按照默认鼠标指针大小吧，应该能解决大部分情况了。
