### ISSUE TITLE
希望 html 块不要自动识别

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#4462]
在剪藏的网页或者自己的笔记含有类似 \<div>等文字时，会自动识别为 html 块，并显示为一片空白。这显然不是完整的 html 块，希望这种情况不要自动转变为 html 块。

**Comment by 88250** [comment]
这个估计实现不了，因为解析的时候必须按照固定语法解析，类似无法将 Markdown 语法识别为普通文本。
