### ISSUE TITLE
关于关系图的改进

### ISSUE THREAD

**Issue by lobird** [siyuan-note/siyuan#4470]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
当我想写一点东西的时候，我不用建立文档或者手工搭建思维导图。直接打开某个文档，通过单个文档的关系图，进行自由联想发散，手动打开或关闭某些连接，生成逻辑框架，然后，将这个框架保持成文档。
发现关系图中的文档有逻辑关系，但没有关联时，可以鼠标直接托拽一下建立链接

我希望的关系图发展方向：
第一步，可以根据某个文档的现有关系定制关系图。能够像思维导图工具一样，手工的展开或折叠一些链接。
第二步，可以根据定制的关系图生成文档
第三步，可以在关系图通过鼠标托拽改变增加文档的连接

**Comment by lobird** [comment]
或者先做一个改进，
只文档与文档之间的关系，去掉段落这个中介。

**Comment by 88250** [comment]
感谢提议，但是现有关系图应该不会再改进了，长期计划请关注 https://github.com/siyuan-note/siyuan/issues/2024
