### ISSUE TITLE
表格中无法使用任务清单

### ISSUE THREAD

**Issue by ausmas** [siyuan-note/siyuan#4471]
表格中选择任务清单后会显示在表格外面，能不能在单元格直接显示任务清单？
![image](https://user-images.githubusercontent.com/2168423/161370842-4c451a27-9fee-4b28-b649-b23cb8e91f26.png)

**Comment by ausmas** [comment]
另外对标题也不能设置任务清单或列表样式，只能选其一。
而且标题转换成其他样式的操作也有点麻烦，需要先转换成段落再转换成其他样式。
这方面有什么快捷方式吗

**Comment by Zuoqiu-Yingyi** [comment]
单元格中只能存在行级元素, 而任务列表是块级元素, 因此没法在单元格中插入任务列表
标题中再按一次快捷键可以取消标题

**Comment by 88250** [comment]
楼上说得对，我们关闭了，感谢反馈。
