### ISSUE TITLE
#关于到处PDF的优化建议#

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4472]
这是我思源笔记的的样子
<img width="617" alt="Snipaste_2022-04-02_17-25-29" src="https://user-images.githubusercontent.com/66512309/161376893-67d31d88-00eb-488c-b90a-476fb1fad48e.png">
但是到处PDF后，上面多了小编号
<img width="468" alt="Snipaste_2022-04-02_17-25-13" src="https://user-images.githubusercontent.com/66512309/161376920-ffad3d23-de08-4738-9652-7ad24bae9025.png">
建议优化以下，可不可以不要这个小编号，跳转直接在文字上。
还有就是导出会发现，所有的子页面也被导出了，而我仅仅想导出当期页面，可不可以加一个仅导出当前页面的选项

**Comment by Faith-YSQ** [comment]
当前页面，打字错了

**Comment by 88250** [comment]
这个是块引用转换为脚注，目前只有这个方式才能尽量将块引用转换为通用方式进行导出，感谢反馈。
