### ISSUE TITLE
点击大纲后再点击动态滚动条后，反链显示错误

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4475]
https://ld246.com/article/1648455869854

**Comment by fanglypro** [comment]
不止是点击大纲后在点击动态滚动条后会出现这个情况，我点击大纲后再双击内容，面包屑上的聚焦也会变化（观察面包屑）：

![temp209](https://user-images.githubusercontent.com/57083732/161419139-c2840dd3-3565-4017-88f7-bb7baf6f36cd.gif)


是同一个问题吗？
