### ISSUE TITLE
块滑条移动至末尾后无法滚动

### ISSUE THREAD

**Issue by xxhh12a** [siyuan-note/siyuan#4479]
### 截屏或者录屏演示 [

https://user-images.githubusercontent.com/55382340/161416356-c332252a-e236-4235-b69c-c2af5c5edf29.mov

](url)

### 版本环境 Version environment

* Version: 1.9.6
* Operating system: mac 12.3.1
* Browser (if used):

**Comment by 88250** [comment]
应该和 https://github.com/siyuan-note/siyuan/issues/4467 是同一个问题，请等 v1.9.7 发布以后再试试，先关闭了，感谢反馈。
