### ISSUE TITLE
Copy image into clipboard

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#448]
- 从思源复制到Notion，希望能带图片
- 希望从思源能直接拖拽图片到Notion
![image](https://user-images.githubusercontent.com/26304888/98457997-25b8ab00-21c7-11eb-82ca-0969e947a164.png)
![image](https://user-images.githubusercontent.com/26304888/98457999-2b15f580-21c7-11eb-9064-1d2104116203.png)

![image](https://user-images.githubusercontent.com/26304888/98458001-32d59a00-21c7-11eb-8eb2-9a952b39b387.png)

**Comment by 88250** [comment]
论坛反馈 https://ld246.com/article/1606827532185 @Vanessa219

**Comment by Vanessa219** [comment]
这个是本地应用中的本地图片，需要使用图床。这样其他站点才可以拉取到图片，否则是没有权限的。

**Comment by 88250** [comment]
经过研究发现目前在技术上是做不到全文复制是携带图片的，但是能做单张复制，我们先实现单张复制吧，谢谢。

**Comment by Achuan-2** [comment]
Vscode 有一个知乎插件，可以把图片都转为知乎图床，是否可以借鉴一下

**Comment by 88250** [comment]
@Achuan-2 近期版本会上线云端图床，应该能彻底解决这些不便 :)
