### ISSUE TITLE
Issue export to html and PDF for nested subnotes

### ISSUE THREAD

**Issue by brogahavi** [siyuan-note/siyuan#4481]
Export works fine for single file, but for a folder (with subfiles) the export creates a pdf or html with no content. 
The only one to work for nested folder is markdown.

I'm on version v1.9.6

**Comment by 88250** [comment]
Hello, batch export is currently only supported when exporting Markdown. Because rendering is time-consuming when exporting to other formats, batch export is not supported, sorry.
