### ISSUE TITLE
Add "Move to" in the file tree and editor tabs

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#449]
现有文档在文件夹中的移动只有拖动一种形式,当文档或文件夹过多时难以方便的转移文档所在文件夹
需要在右键菜单中增加一个[移动]的选项,可以选择需要移动到的文件夹中

**Comment by 88250** [comment]
感谢反馈，过一段时间再改进。

**Comment by nn200433** [comment]
文档移动还要增加检索文档关联的附件自动移动到目标文件夹下，不然光文档移动了，附件却还要人工筛选一个个移动

**Comment by nn200433** [comment]
> 感谢反馈，过一段时间再改进。

文档移动还要增加检索文档关联的附件自动移动到目标文件夹下，不然光文档移动了，附件却还要人工筛选一个个移动

**Comment by 88250** [comment]
@nn200433 你好，目前文件树上的移动已经会复制资源文件了。
