### ISSUE TITLE
文档导出错误

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#4490]
### 描述问题 Describe the problem

在服务器的docker环境下部署，选择文档进行导出后，
跳转的链接为`http://127.0.0.1:6806/export/*****.zip`

无法下载，只有把`127.0.0.1`改为服务器的**公网IP**后才能下载

### 版本环境 Version environment

* Version: v1.9.6
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
应该是没有设置 `--servePath` 启动参数导致，请搜索 issues 有类似反馈和解决方案讨论。
