### ISSUE TITLE
`新建文档名模板` 改为 `新建文档存放位置` 并支持设置路径

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4494]
https://ld246.com/article/1649063843848

配置项改名为 `新建文档存放位置`，支持设置路径。

**Comment by 88250** [comment]
需求并不是太多，暂时不考虑了。

**Comment by AugustTuan** [comment]
虽然提的不是太多，但是着确实是一个问题

**Comment by winter60** [comment]
哇，是不是支持`/`就支持路径层级了呀，liandi不用回我了,D大。
