### ISSUE TITLE
改进列表折叠

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4496]
- [ ] alt 点击列表项后的箭头图标，对其所有子项进行折叠
- [ ] alt 点击列表项图标，对其所有同级项进行折叠

* https://ld246.com/article/1648886730560

**Comment by mrch027** [comment]
对节点处理这个优化思路很好。很有用的功能。
文档树内“定义块（page）”点击，打开的是page，但更需要的是直接看到page的上下文
