### ISSUE TITLE
挂件块支持内置属性 `命名`、`别名` 和 `备注` 搜索

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4497]
https://ld246.com/article/1649074618432

**Comment by Zuoqiu-Yingyi** [comment]
@88250 可能还需要支持内联属性 `data-assets` 与 `data-export-md` 的搜索

**Comment by 88250** [comment]
属性的搜索只能用关联查询，不在 blocks 表里。

**Comment by Zuoqiu-Yingyi** [comment]
@88250 在 blocks 表里的 ial 字段中也有关联的全部属性😂

**Comment by 88250** [comment]
嗯，后面再考虑一下吧。
