### ISSUE TITLE
列出指向某一个块的所有嵌入块

### ISSUE THREAD

**Issue by tomatl45** [siyuan-note/siyuan#4508]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

你好，

当我写笔记时，曾多次将某一个块复制为嵌入块，并粘贴到文档中的其他位置。现在，我想要找出该块对应的所有嵌入块，以便快速查阅与其相关的笔记。

### 描述可能的最优解决方案 Describe the optimal solution

当对某一个块进行聚焦时，如果可以在反向链接面板总列出所有指向该块的嵌入块。

### 描述候选的解决方案 Describe the candidate solution

或者，当点击某一个块左侧的菜单按钮时，如果可以有一个选项来列出所有指向该块的嵌入块。

或者，当进行搜索时，如果可以通过输入某一个块的ID来搜索所有指向该块的嵌入块。

### 其他信息 Other information

我所使用的思源笔记的版本为1.9.6。

**Comment by 88250** [comment]
你好，嵌入块是通过查询实现的，所以无法追踪反向链接，如果需要反向链接的话只能使用块引用。

**Comment by Zuoqiu-Yingyi** [comment]
将嵌入块的功能拆分为嵌入块与查询块有没有日程呀, 我记得社区讨论过实现方案❓
嵌入块语法为 `{{<块 ID>}}`, 显示在反链面板中
查询块语法为 `{{<SQL 语句>}}`, 不显示在反链面板中

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 语法设计是一方面，主要还是没有资源去实现。

**Comment by leolee9086** [comment]
select * from blocks where type= 'query_embed' and markdown='{{select * from blocks where id=''.root{.id}''}}'  结合query挂件先顶顶吧
