### ISSUE TITLE
git仓库同步

### ISSUE THREAD

**Issue by zZ-10** [siyuan-note/siyuan#451]
![image](https://user-images.githubusercontent.com/58500946/98491882-2dcd2500-2271-11eb-8eb4-bf786e90611f.png)
我添加过仓库地址了，这里提示我同步失败， 我在文件夹窗口进行提交，没有问题

**Comment by 88250** [comment]
目前暂时没有处理第三方仓库的 SSH 认证，建议使用 git 客户端提交。

**Comment by iiiyu** [comment]
@88250  所以 Public Key 是用来设置  WebDAV 的？

**Comment by 88250** [comment]
@iiiyu 思源的官方仓库，用于同步的。
