### ISSUE TITLE
Linux 端支持 URL Scheme `siyuan://`

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#4513]
目前 linux 下 url scheme 在思源未打开时无法正确跳转，不过在社区已有人给出解决方案：
>然后回到 main.js 文件，查找 mainWindow.webContents.on('did-finish-load', () => {，修改：
> 
>   ```  mainWindow.webContents.on('did-finish-load', () => {
>     if ('linux' === process.platform || 'win32' === process.platform) { //Modified
>       siyuanOpenURL = process.argv.find((arg) => arg.startsWith('siyuan://'))
>     }
>     if (siyuanOpenURL) {
>       setTimeout(() => { // 等待界面js执行完毕
>         writeLog(siyuanOpenURL)
>         mainWindow.webContents.send('siyuan-openurl', siyuanOpenURL)
>         siyuanOpenURL = null
>       }, 2000)
>     }
>   })
> ```
> 
> 作者：Clouder
> 链接：https://ld246.com/article/1634908196973
> 来源：链滴
> 协议：CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/

希望加入该更改

**Comment by 88250** [comment]
下个版本加入这个改动，但是不确定能否正常工作，发版以后请帮忙验证，谢谢。

**Comment by choyy** [comment]
这个改动我试过了，可以正常工作

**Comment by 88250** [comment]
我怕我改错了 😂

**Comment by choyy** [comment]
运行正常
