### ISSUE TITLE
输入表格崩溃

### ISSUE THREAD

**Issue by liuooo** [siyuan-note/siyuan#4515]
### 描述问题 Describe the problem
插入表格失败，笔记奔溃，需要重启

### 期待的结果 Expected result
bug 修复

### 截屏或者录屏演示 Screenshot or screen recording presentation

复现步骤如下：
1. 新开一行，输入 |-|-| 后 shift + 回车
2. 输入 |
3. 笔记奔溃，但能看到表格渲染成功
<img width="473" alt="image" src="https://user-images.githubusercontent.com/5405656/161939264-43d7e5f3-c0c9-48b4-80e6-b0d96b961baf.png">

### 版本环境 Version environment

* Version:  1.9.1
* Operating system:  macos 12.1
* Browser (if used):

**Comment by 88250** [comment]
你好，我们在最新版上没能重现问题，请升级到最新版后再试试。

先关闭了，如果还能重现问题麻烦继续跟帖，谢谢。
