### ISSUE TITLE
Hello! In the process of using Siyuan, it is found that the video cover can be displayed, but the video cannot be played. Please troubleshoot the problem and fix it in time. Thanks!

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#4517]
### 描述问题 Describe the problem

Hello! In the process of using Siyuan, it is found that the video cover can be displayed, but the video cannot be played. Please troubleshoot the problem and fix it in time. Thanks!

### 期待的结果 Expected result

According to the normal expected results, it should be able to play web videos perfectly, such as: *.mp4 | *.webm | etc., just like other Markdown editors, it can play web videos perfectly, etc.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![2022-04-06_191354](https://user-images.githubusercontent.com/54253524/161963611-34971e33-832c-4727-b4bc-e9878dac5096.png)

![161735916-886b52f9-e51f-42be-9d49-6ba511a1baea](https://user-images.githubusercontent.com/54253524/161961173-0f6afeaf-41a0-46b3-afeb-ccb720f0406a.png)

### 版本环境 Version environment

* Version: 1.9.6
* Operating system:  Windows 10 19044 
* Browser (if used): Desktop Client and Chrome

### 日志文件 Log file

```html
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/04/06 19:10:54 runtime.go:32: kernel is booting:
    * ver [1.9.6]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [E:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211218]
    * workspace directory [E:\SiYuan, data 54 kB]
I 2022/04/06 19:10:55 conf.go:263: local serve path [http://192.168.12.1:2808]
I 2022/04/06 19:10:55 serve.go:69: kernel is booting [http://127.0.0.1:2808]
I 2022/04/06 19:10:55 conf.go:488: pre-init database size [57 kB]
I 2022/04/06 19:10:55 index.go:116: use existing database for box [20220406175853-jgsen2k]
I 2022/04/06 19:10:55 index.go:189: resolving refs...
I 2022/04/06 19:10:55 index.go:316: resolved refs [0]
I 2022/04/06 19:10:55 conf.go:512: post-init database size [57 kB], tree stat [count=1, size=21 kB]
I 2022/04/06 19:10:55 working.go:132: kernel booted
I 2022/04/06 19:18:12 conf.go:364: exited kernel
```

**Comment by 88250** [comment]
Hello, it may be the video encoding is not supported, please try to play with other video files.

**Comment by 88250** [comment]
We are closed for now, if there is any further information welcome to provide it, thank you.

**Comment by zhouxinghong** [comment]
> Hello, it may be the video encoding is not supported, please try to play with other video files.

I have tried many times and the video can be played perfectly in vlc player and other editors including any *.MP4 | *.webm etc.
See the demo below. . .
![2022-04-06_1](https://user-images.githubusercontent.com/54253524/161999830-da615303-d396-4b27-972a-703607ad5915.png)
![2022-04-06_2222](https://user-images.githubusercontent.com/54253524/161999841-8148d729-3e24-4176-bbf3-397ec02fb1f5.png)
![2022-04-06_22333](https://user-images.githubusercontent.com/54253524/161999845-0309d738-5846-430e-801b-3f04eaf38ea8.png)
