### ISSUE TITLE
I have tried many times and the video can be played perfectly in vlc player and other editors including any *.MP4 | *.webm etc. See the demo below. . .

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#4519]
### 描述问题 Describe the problem

I have tried many times and the video can be played perfectly in vlc player and other editors including any *.MP4 | *.webm etc.
See the demo below. . .
https://github.com/siyuan-note/siyuan/issues/4517
Using any *.mp4 and *.webm cannot play in SIYuan. . . And HTML has good support for them. . .
### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
Please upload a sample file (.mp4 or .webm) to us.

**Comment by zhouxinghong** [comment]
> Please upload a sample file (.mp4 or .webm) to us.

[110도 변신! 제로투 댄스💙  Demo One Demo  heerrre #shorts.zip](https://github.com/siyuan-note/siyuan/files/8428139/110.Demo.One.Demo.heerrre.shorts.zip)

**Comment by 88250** [comment]
Can you provide another unplayable file in mp4 format? Thanks.

**Comment by 88250** [comment]
Sorry, I can't visit YouTube or Netflix... 

The video format is not decided by its suffix, encoding is the point, if it is encoded by HEVC/H.265, the browser can't play it, SiYuan is based on Electron, like a browser.

**Comment by 88250** [comment]
The .webm format will be supported in  https://github.com/siyuan-note/siyuan/issues/4522

**Comment by zhouxinghong** [comment]
> 

I will try my best to provide a *.MP4 sample for you to test! Please wait. . .

**Comment by zhouxinghong** [comment]
> The .webm format will be supported in #4522

Thanks! You are really great.

**Comment by 88250** [comment]
Hello, I tested this mp4 file on the SiYuan development version and can play it, please wait for the next version v1.9.7 to be released and upgrade it, thank you.

**Comment by zhouxinghong** [comment]
> Hello, I tested this mp4 file on the SiYuan development version and can play it, please wait for the next version v1.9.7 to be released and upgrade it, thank you.

Hello! You can also send me the beta download link if you think it's convenient, and I'll report any bugs I find. Thanks! Your productivity is awesome!
You can paste the beta download link below this article and I'll check it out later.

**Comment by 88250** [comment]
We have invited you to join SiYuan insider, please accept it and visit https://github.com/siyuan-note/insider

**Comment by zhouxinghong** [comment]
> We have invited you to join SiYuan insider, please accept it and visit https://github.com/siyuan-note/insider

Thanks!
