### ISSUE TITLE
0.4.2 version macOS dmg 包签名无法验证

### ISSUE THREAD

**Issue by iiiyu** [siyuan-note/siyuan#452]
![image](https://user-images.githubusercontent.com/1130144/98495191-7ac9ef00-22a3-11eb-8e32-2eb9ab2a8d34.png)

**Comment by Vanessa219** [comment]
选择后右键打开试试

**Comment by iiiyu** [comment]
> 选择后右键打开试试

能开是能开 需要去 Security & Privacy  点一下才能打开。 

要不要问问丁哥用不用我的证书去打包？

**Comment by 88250** [comment]
谢谢，我们先凑合吧……
