### ISSUE TITLE
支持代码块高亮语言 `bat`, `graphql`；新增 felipec，intellij-light，tokyo-night-dark，tokyo-night-light 主题

### ISSUE THREAD

**Issue by seekertang** [siyuan-note/siyuan#4525]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
在记录Windows上的环境配置的时候，会需要用到bat命令。
如果代码块支持bat语法的话，比较友好。

**Comment by 88250** [comment]
@Vanessa219 需要将 `dos` 改为 `bat`

**Comment by Vanessa219** [comment]
a99e9b97226d7d337fc835d7a4db78b5744051b3
