### ISSUE TITLE
Can't play mp4 video

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#4527]
### 描述问题 Describe the problem

I do not know why. I installed version 1.9.7, but Siyuan gave me the same feedback as 1.9.6, only the video cover is displayed, the play button is gray and cannot be clicked, and the htm source code is displayed below. . .
I installed the executable version: siyuan-1.9.7.exe, not siyuan-1.9.7.app
Win10 19044 x64
version 1.9.7
![2022-04-07_1111](https://user-images.githubusercontent.com/54253524/162158698-2bbb407f-d921-4c31-bf8c-dfb0cc4e92ae.png)
![161735916-886b52f9-e51f-42be-9d49-6ba511a1baea](https://user-images.githubusercontent.com/54253524/161961173-0f6afeaf-41a0-46b3-afeb-ccb720f0406a.png)

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
Please upload the log file, thanks.

**Comment by zhouxinghong** [comment]
> Please upload the log file, thanks.

```html
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/04/07 17:39:54 runtime.go:32: kernel is booting:
    * ver [1.9.7]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [E:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20211218]
    * workspace directory [E:\SiYuan, data 365 kB]
I 2022/04/07 17:39:58 conf.go:263: local serve path [http://192.168.12.1:2808]
I 2022/04/07 17:39:58 serve.go:69: kernel is booting [http://127.0.0.1:2808]
I 2022/04/07 17:39:58 conf.go:488: pre-init database size [86 kB]
I 2022/04/07 17:39:58 index.go:116: use existing database for box [20220406175853-jgsen2k]
I 2022/04/07 17:39:58 index.go:189: resolving refs...
I 2022/04/07 17:39:58 index.go:316: resolved refs [0]
I 2022/04/07 17:39:58 conf.go:512: post-init database size [86 kB], tree stat [count=2, size=50 kB]
I 2022/04/07 17:39:58 working.go:132: kernel booted
```

**Comment by 88250** [comment]
What Windows version are you using?

**Comment by zhouxinghong** [comment]
> Win10 19044 x64



> What Windows version are you using?

Win10 19044 x64

**Comment by 88250** [comment]
Try opening the developer tools with Ctrl+Shift+I, switch to the Console, and then refresh the interface with Ctrl+R to see if there is an error message output.

**Comment by zhouxinghong** [comment]
> 



> Try opening the developer tools with Ctrl+Shift+I, switch to the Console, and then refresh the interface with Ctrl+R to see if there is an error message output.

![2022-04-07_1222222222](https://user-images.githubusercontent.com/54253524/162181060-94d5edaf-4dd3-4ca4-bbef-0b90c8fedb62.png)
![2022-04-07_13333333333333333](https://user-images.githubusercontent.com/54253524/162181070-55a0a4d5-d8a1-487e-a3a8-af256e9438eb.png)

**Comment by 88250** [comment]
We are not sure if this is a system problem, I have Windows 11 and it can play normally.

**Comment by 88250** [comment]
Please try again with other files and see if it doesn't play.

**Comment by 88250** [comment]
We have just re-uploaded the v1.9.7 installation package, please download it again and try again.

**Comment by zhouxinghong** [comment]
I'm very sorry to tell you! The result remains the same. . .

**Comment by 88250** [comment]
Do you have another computer to test with? We think this is likely to be caused by a problem with the system environment.

**Comment by zhouxinghong** [comment]
I installed Windows 10 on March 3, 2022, and the system is running fine.

**Comment by zhouxinghong** [comment]
Hello, teacher! I would like to ask a special question about the modification of css style, such as the next style, how to modify it or remove it?
I have marked border-top with a red box??
![2022-04-08_1888888888](https://user-images.githubusercontent.com/54253524/162360779-9132b30a-892c-4942-8a29-388657dd1a06.png)

**Comment by zhouxinghong** [comment]
Hello, teacher! I would like to ask a special question about the modification of css style, such as the next style, how to modify it or remove it?
I have marked border-top with a red box??
![2022-04-08_1888888888](https://user-images.githubusercontent.com/54253524/162360779-9132b30a-892c-4942-8a29-388657dd1a06.png)

**Comment by zhouxinghong** [comment]
> I installed Windows 10 on March 3, 2022, and the system is running fine.

Regarding this issue, it is recommended to perform effective testing in the latest version of Windows 10 and determine the final result. . .

**Comment by Zuoqiu-Yingyi** [comment]
> Regarding this issue, it is recommended to perform effective testing in the latest version of Windows 10 and determine the final result. . .

@zhouxinghong
This example works fine: `https://cdn.jsdelivr.net/npm/kanbanniang-tia@0.1.6/siyuan/formatting-elements.mp4`
![image](https://user-images.githubusercontent.com/49649786/162369012-922c5e61-4eea-4376-9ba4-30787b8a744a.png)


- Version: `1.9.7`
- Operating system: `Microsoft Windows 10 10.0.19044`

**Comment by zhouxinghong** [comment]
My current system: 19044.1415
![2022-04-08_999999999999](https://user-images.githubusercontent.com/54253524/162375930-c77e230b-a18e-4f61-b2e2-54e1ea35fe95.png)

**Comment by zhouxinghong** [comment]
![2022-04-08_999999999999](https://user-images.githubusercontent.com/54253524/162376182-6e3c9f59-ef0b-491a-9f04-d8785b55fcb3.png)

**Comment by zhouxinghong** [comment]
> > Regarding this issue, it is recommended to perform effective testing in the latest version of Windows 10 and determine the final result. . .
> 
> @zhouxinghong This example works fine: `https://cdn.jsdelivr.net/npm/kanbanniang-tia@0.1.6/siyuan/formatting-elements.mp4` ![image](https://user-images.githubusercontent.com/49649786/162369012-922c5e61-4eea-4376-9ba4-30787b8a744a.png)
> 
> * Version: `1.9.7` [siyuan-1.9.7-win.exe](https://github.com/siyuan-note/siyuan/releases/download/v1.9.7/siyuan-1.9.7-win.exe)
> * Operating system: `Microsoft Windows 10 10.0.19044.1620 21H2`

When will this 1.9.7 version be packaged and released?

**Comment by Zuoqiu-Yingyi** [comment]
> When will this 1.9.7 version be packaged and released?

@zhouxinghong
It is recommended to reinstall this release, which seems to have been repackaged using `electron 15.5.1` yesterday.

**Comment by zhouxinghong** [comment]
I installed it more than once at 1:00 a.m. on April 8, 2022, and this should have been installed by me at present. . .

**Comment by zhouxinghong** [comment]
Hello, teacher! I would like to ask a special question about the modification of css style, such as the next style, how to modify it or remove it?
I have marked border-top with a red box??
![2022-04-08_1888888888](https://user-images.githubusercontent.com/54253524/162360779-9132b30a-892c-4942-8a29-388657dd1a06.png)
How can I change this style? only this place

**Comment by Zuoqiu-Yingyi** [comment]
> I installed it more than once at 1:00 a.m. on April 8, 2022, and this should have been installed by me at present. . .

@zhouxinghong Please enter `process.versions` in the console (using <kbd>Ctrl + Shift + I</kbd> to open) to view the version information. If the output is the same as the below, then I can't solve it.😂
```json
{
    "node": "16.5.0",
    "v8": "9.4.146.22-electron.0",
    "uv": "1.41.0",
    "zlib": "1.2.11",
    "brotli": "1.0.9",
    "ares": "1.17.1",
    "modules": "98",
    "nghttp2": "1.42.0",
    "napi": "8",
    "llhttp": "6.0.2",
    "openssl": "1.1.1",
    "icu": "69.1",
    "unicode": "13.0",
    "electron": "15.5.1",
    "chrome": "94.0.4606.81"
}
```

**Comment by Zuoqiu-Yingyi** [comment]
> Hello, teacher! I would like to ask a special question about the modification of css style, such as the next style, how to modify it or remove it? I have marked border-top with a red box?? ![2022-04-08_1888888888](https://user-images.githubusercontent.com/54253524/162360779-9132b30a-892c-4942-8a29-388657dd1a06.png) How can I change this style? only this place

@zhouxinghong Please use element select tool.
![image](https://user-images.githubusercontent.com/49649786/162380837-48e83d6e-9304-49e4-9093-61dba0097240.png)

**Comment by zhouxinghong** [comment]
> Please enter in the console (using to open) to view the version information. If the output is the same as the below, then I can't solve it.`process.versions`Ctrl + Shift + I😂

How can I check the version?

**Comment by zhouxinghong** [comment]
> > Hello, teacher! I would like to ask a special question about the modification of css style, such as the next style, how to modify it or remove it? I have marked border-top with a red box?? ![2022-04-08_1888888888](https://user-images.githubusercontent.com/54253524/162360779-9132b30a-892c-4942-8a29-388657dd1a06.png) How can I change this style? only this place
> 
> @zhouxinghong请使用元素选择工具。 ![image](https://user-images.githubusercontent.com/49649786/162380837-48e83d6e-9304-49e4-9093-61dba0097240.png)
I can't navigate to using the element tool?

**Comment by zhouxinghong** [comment]
> > I installed it more than once at 1:00 a.m. on April 8, 2022, and this should have been installed by me at present. . .
> 
> @zhouxinghong Please enter `process.versions` in the console (using Ctrl + Shift + I to open) to view the version information. If the output is the same as the below, then I can't solve it.😂
> 
> ```json
> {
>     "node": "16.5.0",
>     "v8": "9.4.146.22-electron.0",
>     "uv": "1.41.0",
>     "zlib": "1.2.11",
>     "brotli": "1.0.9",
>     "ares": "1.17.1",
>     "modules": "98",
>     "nghttp2": "1.42.0",
>     "napi": "8",
>     "llhttp": "6.0.2",
>     "openssl": "1.1.1",
>     "icu": "69.1",
>     "unicode": "13.0",
>     "electron": "15.5.1",
>     "chrome": "94.0.4606.81"
> }
> ```
```html
{node: '16.13.2', v8: '10.0.139.8-electron.0', uv: '1.42.0', zlib: '1.2.11', brotli: '1.0.9', …}
ares: "1.18.1"
brotli: "1.0.9"
chrome: "100.0.4896.60"
electron: "18.0.1"
icu: "70.1"
llhttp: "6.0.4"
modules: "103"
napi: "8"
nghttp2: "1.45.1"
node: "16.13.2"
openssl: "1.1.1"
unicode: "14.0"
uv: "1.42.0"
v8: "10.0.139.8-electron.0"
zlib: "1.2.11"
[[Prototype]]: Object
```

**Comment by Zuoqiu-Yingyi** [comment]
> ```
> {node: '16.13.2', v8: '10.0.139.8-electron.0', uv: '1.42.0', zlib: '1.2.11', brotli: '1.0.9', …}
> ares: "1.18.1"
> brotli: "1.0.9"
> chrome: "100.0.4896.60"
> electron: "18.0.1"
> icu: "70.1"
> llhttp: "6.0.4"
> modules: "103"
> napi: "8"
> nghttp2: "1.45.1"
> node: "16.13.2"
> openssl: "1.1.1"
> unicode: "14.0"
> uv: "1.42.0"
> v8: "10.0.139.8-electron.0"
> zlib: "1.2.11"
> [[Prototype]]: Object
> ```

There are problems with this version on Windows. Try downloading and installing this version: `https://github.com/siyuan-note/siyuan/releases/download/v1.9.7/siyuan-1.9.7-win.exe`

**Comment by zhouxinghong** [comment]
> > ```
> > {node: '16.13.2', v8: '10.0.139.8-electron.0', uv: '1.42.0', zlib: '1.2.11', brotli: '1.0.9', …}
> > ares: "1.18.1"
> > brotli: "1.0.9"
> > chrome: "100.0.4896.60"
> > electron: "18.0.1"
> > icu: "70.1"
> > llhttp: "6.0.4"
> > modules: "103"
> > napi: "8"
> > nghttp2: "1.45.1"
> > node: "16.13.2"
> > openssl: "1.1.1"
> > unicode: "14.0"
> > uv: "1.42.0"
> > v8: "10.0.139.8-electron.0"
> > zlib: "1.2.11"
> > [[Prototype]]: Object
> > ```
> 
> There are problems with this version on Windows. Try downloading and installing this version: `https://github.com/siyuan-note/siyuan/releases/download/v1.9.7/siyuan-1.9.7-win.exe`

ok

**Comment by zhouxinghong** [comment]
Will it conflict with the node environment installed on the machine?

**Comment by Zuoqiu-Yingyi** [comment]
> Will it conflict with the node environment installed on the machine?

The application environment of Electron is isolated.

**Comment by zhouxinghong** [comment]
> > Will it conflict with the node environment installed on the machine?
> 
> The application environment of Electron is isolated.

I have installed the latest version you gave, but the results are disappointing. . .

**Comment by zhouxinghong** [comment]
Skip this question for now!
I can't navigate to using the element tool?
Can you tell me which style attribute it is?

**Comment by Zuoqiu-Yingyi** [comment]
> Skip this question for now! I can't navigate to using the element tool? Can you tell me which style attribute it is?

```css
.layout__wnd--active .layout-tab-bar .item--focus {
    box-shadow: inset 0 2px 0 0 var(--b3-theme-primary-lighter);
}
```

**Comment by zhouxinghong** [comment]
> ```css
> box-shadow: inset 0 2px 0 0 var(--b3-theme-primary-lighter);
> ```

You are really great! I have been unable to find this element. thank you very much!

**Comment by zhouxinghong** [comment]
But the video still won't play on my PC. . . Very regrettable. . .
```html
node: '16.5.0', v8: '9.4.146.22-electron.0', uv: '1.41.0', zlib: '1.2.11', brotli: '1.0.9', …}
ares: "1.17.1"
brotli: "1.0.9"
chrome: "94.0.4606.81"
electron: "15.5.1"
icu: "69.1"
llhttp: "6.0.2"
modules: "98"
napi: "8"
nghttp2: "1.42.0"
node: "16.5.0"
openssl: "1.1.1"
unicode: "13.0"
uv: "1.41.0"
v8: "9.4.146.22-electron.0"
zlib: "1.2.11"
```

**Comment by Zuoqiu-Yingyi** [comment]
> But the video still won't play on my PC. . . Very regrettable. . .

@zhouxinghong
Try to use browser to visit `http://127.0.0.1:6806`, this should be the ultimate solution😂

**Comment by zhouxinghong** [comment]
Waiting for later versions to see if it improves. . . Thanks!
