### ISSUE TITLE
播放图片时会闪屏一次

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4529]
https://ld246.com/article/1649300125782/comment/1649302427635?r=88250#comments

**Comment by netdog2019** [comment]
图片切换，能否 不加缩放的动画，直接左右切换是不是更加简单直接？
![444](https://user-images.githubusercontent.com/49815951/162482911-1261cd22-e060-41fa-abbd-1370b8d27362.gif)

**Comment by 88250** [comment]
@netdog2019 这个暂时不改了，继续收集反馈再看，谢谢。

**Comment by 88250** [comment]
@netdog2019 领导还是给改了，把动画去掉了 😂

**Comment by Achuan-2** [comment]
这个貌似依然会闪，需要点击中间的播放按钮两次才能进入播放页面
![思源1 9 8 gif](https://user-images.githubusercontent.com/60436214/162556141-e0c6e18b-bc4a-4ea0-804f-c6d7fdec69c3.gif)

**Comment by 88250** [comment]
@Achuan-2 Windows 上确实还是会闪，但是浏览器端不会，目前看可能是 Electron 相关问题，暂时没有时间进一步排查了，先这样吧。
