### ISSUE TITLE
标签面板过滤掉代码块

### ISSUE THREAD

**Issue by maoqyhz** [siyuan-note/siyuan#4531]
### 描述问题 Describe the problem

在笔记中使用“#”可创建标签，并记录在标签视图中。

问题在于软件会自动扫描代码中出现的“#”也将其作为标签的内容，这是有问题的，在部分语言中，“#”仅代表注释而已，希望后续版本在标签的检测上可以过滤掉代码段中的内容。

### 期待的结果 Expected result

希望后续版本在标签的检测上可以过滤掉代码段中的内容。

### 截屏或者录屏演示 Screenshot or screen recording presentation

目前结果入下图所示：
![image](https://user-images.githubusercontent.com/20581706/162190897-8030a50a-9b6d-4387-9fa6-fcd0c044251f.png)

### 版本环境 Version environment

* Version: v1.9.6
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
我这里好像重现不了问题

![image](https://user-images.githubusercontent.com/873584/162233442-608dc0cf-64eb-41c0-9a25-db86819900ac.png)

麻烦再描述下重现步骤，或者帮忙制作一个能够重现问题的数据集，谢谢。

**Comment by maoqyhz** [comment]
无法复现，有问题的是我导入的md文件夹。但是很奇怪，我将相关的笔记全部删除后，此标签仍然存在。

双击标签，查找窗口显示“##”，而且“':表示通配多个层级，例如a”这段话是怎么出来的？


![image](https://user-images.githubusercontent.com/20581706/162338960-6d295164-52b9-4e5e-9d27-18ccfd6b1774.png)

**Comment by 88250** [comment]
试一下重建索引。

**Comment by 88250** [comment]
我们先关闭了，如果还有问题麻烦继续跟帖，谢谢。
