### ISSUE TITLE
部分 Windows 端上卡顿的问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4533]
https://ld246.com/article/1649321915142

https://github.com/siyuan-note/siyuan/issues/4532

**Comment by whuwangyong** [comment]
确实卡顿。也用的搜狗输入法，输入时字符上屏有延迟。
另一个直观的，在一段文字里面，长按左右方向键，没法看到光标逐个字符移动。

**Comment by whuwangyong** [comment]
快速连续输入字母或者数字，不会显示，直到停止输入后，才会突然出现一长串字符。
