### ISSUE TITLE
改进块引搜索交互

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4534]
https://ld246.com/article/1649338100756

**Comment by fanglypro** [comment]
提一个想法，供参考：

现在 `[[` 和 `((` 搜索的效果是一样的，或许可以把两者变成不一样的逻辑。例如，`[[` 可以维持现状不变，而 `((`  可以是定制化的搜索策略，比如只搜索文档标题、使用不同的排序算法之类的，甚至 `[[[` 还可以是另一种定制化搜索策略。

roam research 中，`[[` 相当于只搜索 page，`((` 相当于只搜索 block，但是他们的底层 page 和 block 是割裂的。思源在底层架构上统一，但在搜索时或许可以做出区分。

**Comment by 88250** [comment]
@fanglypro 感觉还是在搜索候选窗口上改进交互好一些，使用入口暂时不变。继续考虑一阵。

**Comment by fanglypro** [comment]
> @fanglypro 感觉还是在搜索候选窗口上改进交互好一些，使用入口暂时不变。继续考虑一阵。

我觉得候选窗口上的改进是一方面，我这边考虑的是排序的问题，不同的用户以及不同的搜索目标，可能有不同的排序需求，比如我有时候明确只要搜文档名，有时候明确只要搜标题，有时候明确只要搜列表项。

对于现在的排序规则，有一个问题是：大部分情况下我的搜索目标是文档，对应于roam中用户最常用的`[[]]`，使用频率远高于`(())`。而在现在的搜索规则下，很多时候我根本搜不到我想要搜的内容，尤其是在想搜文档块的时候。

比如有一个文档叫《多任务学习》，以前想要引用这个文档时，我直接`[[`后面输入`多任务`三个字，第一个就是我想要的文档，我回车就好。但是现在的搜索规则下，我想要引用的文档在搜索结果的非常后面，因为我在平时写文档时提到多任务学习，我都简化成多任务三个字，导致搜索结果被我的正文所淹没：

![image](https://user-images.githubusercontent.com/57083732/162438866-048808bc-e8fa-4bfa-9860-b495f9d967da.png)

上面这个例子可能看着还好，只要我还记得我的文档的全名，我只要打全了，总能搜到，而有时候是根本没办法搜到，比如说卡片盒笔记法中，经常提到永久笔记要写成一个陈述句，也就是说会建立一个文档，文档名是一句话，整句话的内容经常没办法完全记住，只能记得几个关键词，而这个关键词如果是非常常用的词语的话，块引搜索结果会变成灾难，根本找不到我想要引用的永久笔记，只能通过ctr+p改类型或反链找到文档，然后手动复制块引用，和之前相比又麻烦了很多。

我看在群聊里面也有用户提出对现在的排序规则不适应：

![image](https://user-images.githubusercontent.com/57083732/162436589-d33f3236-e1c6-4cfb-9ea3-98bcbb0c07a0.png)

感觉在块引排序上还是有改进空间

**Comment by 88250** [comment]
收到，我们继续改进看看。

**Comment by 88250** [comment]
搜索的排序规则先改进一次看看 https://github.com/siyuan-note/siyuan/issues/4546

**Comment by 88250** [comment]
继续改进搜索排序规则 https://github.com/siyuan-note/siyuan/issues/4558 

这个 issue 先关闭，先着重考虑改进搜索排序。
