### ISSUE TITLE
windows版本闪退

### ISSUE THREAD

**Issue by TerryCheni** [siyuan-note/siyuan#4542]
### 描述问题 Describe the problem
打开思源笔记直接闪退。
起初，应用在后台运行一段时间后会提示无法连接内核，关闭并重启计算机后无法打开思源笔记。

### 版本环境 Version environment

* Version: 1.9.6.0
* Operating system: windows 10
* Browser (if used): 

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8448982/siyuan.log)

**Comment by 88250** [comment]
请更新到最新版以后再试试。
