### ISSUE TITLE
安卓平板键盘输入，输入框漂移。

### ISSUE THREAD

**Issue by one2end** [siyuan-note/siyuan#4543]
![88df069d7fddd4e54bc35b62720f103](https://user-images.githubusercontent.com/24800653/162378450-fc42d629-4496-47f4-8c0c-b51521cae437.jpg)

## 问题
输入法中文输入框没有跟随光标而是出现在左下角。notion、remnote等应用都是这个问题，不确定是不是底层框架的原因。

## 环境
版本安卓10 鸿蒙2.0，外接键盘，百度、小艺输入法。

## 期望结果
在应用内使用外接键盘时，可以正确的跟随光标显示选字框。

**Comment by 88250** [comment]
如果其他应用也是这样的话那应该是框架的原因，暂时无法修复，抱歉抱歉。

我们关闭了，如果后续也有用户反馈这个问题，会关联到这里。
