### ISSUE TITLE
改进搜索排序规则

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4546]
在考虑匹配度的同时考虑 3 个类型：文档 > 标题 > 列表项

**Comment by fanglypro** [comment]
现在列表项和文档块的搜索结果都不会高亮：

![image](https://user-images.githubusercontent.com/57083732/162557721-bf9513bc-4295-4be6-a418-5d97efd2f3c8.png)

![image](https://user-images.githubusercontent.com/57083732/162557752-5657cf3b-d640-4210-93a6-2bcad673b9cb.png)

改进后的规则是在匹配度相同的情况下，再根据块类型排序吗？

现在的规则之下，还有一些问题：

1. 把匹配度放在第一位在思源中并不合适，因为思源的块太多了，一上来就按匹配度容易出问题。只有文档块和标题块时，按照匹配度没问题，一旦有了列表项，问题就变得复杂了。第一个例子是上面的图片，在笔记里面有大量只包含关键字的块的时候（这在写列表的过程中常见），搜索结果的前列会被这些块所淹没，找不到重要的文档块，和https://github.com/siyuan-note/siyuan/issues/4534#issuecomment-1092836329 里面我说的问题一样，这个issue并不能改善昨天提的问题。第二个例子见下图，这里的核心问题在于，文档块和标题块的content字段不包含子项，然而列表项的content字段是包含子项的，我想要搜的内容是红框中的父结点，但排序第一个的是在叶子结点的列表项，显然在叶子结点的列表项包含信息是最少的，排在第一个不合理，我上面的`多任务`的图片也是一样，排在前列的全部都是叶子结点的列表项，这些列表项所含有的信息量是垫底的，排在前面没有意义。

![image](https://user-images.githubusercontent.com/57083732/162558504-dad9dbf1-ee13-453c-98b1-c36b1932c3ba.png)

2. 由于列表项的content字段是包含子项的，所以也导致length字段有问题，下图中在子层的列表项length更小信息量更少，却排在顶层的列表项之前，之所以在块类型中文档块>标题块>列表项，是按照信息量期望值从大到小，但是在列表项中，因为content的问题，导致匹配度排序失效，只能往下面看length，而length越小，列表项信息量期望值越小。

![image](https://user-images.githubusercontent.com/57083732/162559137-f85899b3-c9ac-4044-b4cc-4ff83dda67fc.png)

我的搜索规则想法如下，供参考：先按sort字段(我不太清楚sort的具体计算公式，是否可以公布一下呢？但按我之前的体验，应该至少满足了文档块优先级>标题块)，然后按匹配度（对于列表块，希望能优化一下，不是直接匹配列表项content本身，而是匹配列表项的第一个块的content），然后是命中次数（我记得之前是有这个指标的，没有的话忽略也行），然后是按length从小到大，之后其他指标

还有对于列表项的搜索结果，和之前一样显示全content的内容比较好，1.9.8中只显示了第一个块的content

**Comment by 88250** [comment]
问题 1 先略过。

问题 2 单独建个 issue https://github.com/siyuan-note/siyuan/issues/4555

我们重点讨论问题 3。现在的实现大致是这样的 SQL：

```sql
select *
from blocks
where ((content like '%foo%' or name like '%foo%' or alias like '%foo%' or memo like '%foo%'))
  and type IN ('d', 'h', 'c', 'm', 't', 's', 'p', 'html', 'iframe', 'query_embed', 'video', 'audio', 'widget')
order by case
             when name = 'foo' then 10
             when alias = 'foo' then 20
             when memo = 'foo' then 30
             when content = 'foo' and type = 'd' then 31
             when content = 'foo' and type = 'h' then 32
             when content = 'foo' and type = 'i' then 33
             when content = 'foo' then 40
             when name LIKE '%foo%' then 50
             when alias LIKE '%foo%' then 60
             when memo LIKE '%foo%' then 70
             when content LIKE '%foo%' and type = 'd' then 71
             when content LIKE '%foo%' and type = 'h' then 72
             when content LIKE '%foo%' and type = 'i' then 73
             when content LIKE '%foo%' then 80
             else 65535 end ASC, sort ASC, length ASC
limit 64
```

`sort` 字段是定值：

* 文档块：`0`
* 标题块：`5`
* 段落块：`10`
* 代码块：`10`
* 数学公式块：`10`
* 表格块：`10`
* HTML 块：`10`
* 列表块：`20`
* 列表项块：`20`
* 引述块：`20`
* 超级块：`30`

改进的话 blocks 表现有字应该不够，缺乏容器块第一个子块的 content 字段 `fcontent`，通过这个字段做 length 排序，如果是容器块的话过滤也需要在 fcontent 而非 content 上做。

老铁有空的话可以基于上面这个 SQL 帮忙改改看，谢谢。

**Comment by 88250** [comment]
对了，改造以后，多任务学习那个案例如果是在自身文档中块引搜索的话，会排除自身文档名命中，只有在其他文档中块引搜索时才会排第一个。

![image](https://user-images.githubusercontent.com/873584/162581996-27c03694-b369-4aa5-80ba-5c990c06b546.png)
