### ISSUE TITLE
MacOS 使用思源笔记 1.9.7 版本 输入卡顿

### ISSUE THREAD

**Issue by ZinYY** [siyuan-note/siyuan#4549]
### 描述问题 Describe the problem

**问题：** Macbook Pro 2018, 系统为 MacOS 12.3.1, 使用思源笔记 1.9.7 版本，在输入字符时会卡顿。

退回 1.9.6 可解决该问题，怀疑是 Electron 升级导致的问题。

### 版本环境 Version environment

* Version: 1.9.7
* Operating system: MacOS 12.3.1

**Comment by 88250** [comment]
稍后会发布 v1.9.8，请发布后升级看看，先关闭了，如果还有问题请跟帖，谢谢。

**Comment by JokeenZhang** [comment]
2.0.4也会卡，macbook pro 2019，系统是11.6。
大概看了下，每次输入触控栏上的表情图标都会一闪一闪，按退格键每删除一个字符也会闪一下，其他软件不会这样，大概这就是其他软件输入上比较流畅的原因

**Comment by JokeenZhang** [comment]
> @JokeenZhang 不太清楚这个闪烁的含义，我们继续收集反馈，感谢告知。

好的，希望能多点关注输入卡顿的问题。
