### ISSUE TITLE
用edge浏览器页面总是空1/3 ，chrome不会

### ISSUE THREAD

**Issue by jllmh1987** [siyuan-note/siyuan#4550]
### 描述问题 Describe the problem
用edge浏览器页面总是空1/3 ，chrome不会

![image](https://user-images.githubusercontent.com/70119434/162557323-d29127c8-73ac-404f-a907-74f0416da7eb.png)

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
请升级到 Edge 最新版，如果还是有问题的话多半是不兼容，浏览器兼容性近期没有时间改进，我们先关闭了，感谢反馈。
