### ISSUE TITLE
`((` 引用时容器块显示子块内容

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4555]
https://github.com/siyuan-note/siyuan/issues/4546#issuecomment-1093749991 问题2。

**Comment by Tlonglan** [comment]
想到一个情景，如果用`（（`引用一篇长文笔记，这样搜索列表在显示时感觉会“爆炸”

**Comment by 88250** [comment]
@Tlonglan 其实之前一直都是这样的，只是上个版本改成了仅显示第一个子块。
