### ISSUE TITLE
servePath问题

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#4560]
### 描述问题 Describe the problem

暂时没有绑定域名，在公网的docker下部署此应用，添加--servePath=公网IP:8000，

+ 访问公网IP:6806，卡在初始化界面（中间一个大LOGO）

+ 访问公网IP:8000，无法访问

我在issue和社区试图寻找`--servePath`的有关问题，解决方法都是--servePath:域名

如果在没有配置域名，没有配置https的情况下，该如何使用docker部署呢？

### 期待的结果 Expected result

在仅有公网ip、没有域名和https的情况下能够用docker部署思源笔记

### 版本环境 Version environment

* Version: 1.9.8
*

**Comment by 88250** [comment]
需要 NGINX 反代 8000 端口到本地 6806，请参考帮助文档和在 issues/链滴上搜索相关教程。
