### ISSUE TITLE
块滑条拖动至末尾后无法滚动

### ISSUE THREAD

**Issue by xxhh12a** [siyuan-note/siyuan#4562]
### [截屏或者录屏演示](
https://user-images.githubusercontent.com/55382340/162601070-ac3b96c8-572d-4c02-b6df-ed3e1f3dcaf5.mov
)

### 版本环境 Version environment

* Version: 1.9.8
* Operating system: macos 12.3.1
* Browser (if used): 

### 日志文件 Log file
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8458228/siyuan.log)

**Comment by xxhh12a** [comment]
补充：还有块滑条拖动到任意位置后会出现标题，滚动后消失。不知道是新特性还是bug

https://user-images.githubusercontent.com/55382340/162601139-0cae8478-a05a-4b42-bd67-97a4f6b23d0c.mov

**Comment by 88250** [comment]
能够重现问题的文档能发给我们吗？ 845765@qq.com 谢谢。

**Comment by xxhh12a** [comment]
已发送

**Comment by 88250** [comment]
我这里有点重现不了问题：

![issue](https://user-images.githubusercontent.com/873584/162613283-61d9db8f-29b0-4315-9b04-d7e81f3dd246.gif)

麻烦用帮助文档 - 编辑器 - 元素 这一篇试试看能否重现：

![issue](https://user-images.githubusercontent.com/873584/162613328-ea291c35-248d-4aa7-8432-329e562d20f1.gif)

**Comment by xxhh12a** [comment]
我在我的windows电脑上尝试了一下，也是无法重现问题，明天上班我再mac端重新安装一下试试。
另外请问：块滑条拖动到任意位置后会出现标题和题头图，滚动后消失。是新特性还是bug？

**Comment by 88250** [comment]
目前算是特性，等继续收集用户反馈看看。

**Comment by Vanessa219** [comment]
@xxhh12a mac 上也无法重现，还麻烦再看看

**Comment by xxhh12a** [comment]
我重新下载安装之后正常了应该是安装问题，麻烦啦
