### ISSUE TITLE
闪退，这是第二次报告该issue

### ISSUE THREAD

**Issue by TerryCheni** [siyuan-note/siyuan#4563]
### 描述问题 Describe the problem
程序根本无法正常打开，之前使用1.9.6版本，报告issue后只告知我升级到新版本就关闭了issue。
现在升级到了1.9.8，再次闪退，之后尝试卸载并重装，问题并没有得到解决

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
请提供一下日志文件。

**Comment by 88250** [comment]
关联之前的报告 https://github.com/siyuan-note/siyuan/issues/4542

**Comment by 88250** [comment]
暂时无法定位到问题，我们先关闭了，非常抱歉。

如果还有其他人反馈类似问题，会关联到这里。

**Comment by 88250** [comment]
如果可能话，请提供更多环境信息和其他辅助信息，这样对定位问题会有一些帮助。

**Comment by TerryCheni** [comment]
sorry，刚才没来的及回复，
windows版本：
版本	Windows 10 家庭中文版
版本号	21H1
安装日期	‎2021/‎3/‎18
操作系统内部版本	19043.1586
序列号	PF29M5P6
体验	Windows Feature Experience Pack 120.2212.4170.0

软件版本：
1.9.8.0


[siyuan.log](https://github.com/siyuan-note/siyuan/files/8458829/siyuan.log)

**Comment by 88250** [comment]
看下这个日志文件：`C:\Users\用户名\.config\siyuan\app.log`，里面能找到最近一次拉起内核的日志：

`2022-04-09 04:11:24 ui version [1.9.8], booting kernel [C:\Users\用户名\AppData\Local\Programs\SiYuan\resources\kernel\SiYuan-Kernel.exe --wd=C:\Users\DL882\AppData\Local\Programs\SiYuan\resources]
`

方括号里面就是内核启动命令，拷贝到 cmd 下面执行看看输出。

**Comment by TerryCheni** [comment]
刚才尝试了一下，再cmd下运行会直接返回，没有输出。
cmd截图和app.log都在附件中，供参考，多谢
![image](https://user-images.githubusercontent.com/36291892/162619323-f323ace9-d0cb-410b-aab9-9752376b411b.png)
[app.log](https://github.com/siyuan-note/siyuan/files/8459007/app.log)

**Comment by 88250** [comment]
有安装杀毒软件吗？有的话关闭或加入白名单再试试。

**Comment by TerryCheni** [comment]
十分感谢，已经解决了该问题：
Windows Defender默认阻止了SiYuan-Kernel.exe对%userprofile%\Documents\SiYuan\conf\ 的访问，这个问题出现在最近一次通过安装包升级之后，不知道是否与升级有关

同时发现之前也存在Robocopy对SiYuan\sync文件夹的访问被阻止的情况，但没有注意过这个问题。
