### ISSUE TITLE
桌面端支持工作空间多开

### ISSUE THREAD

**Issue by pjpjp219** [siyuan-note/siyuan#4567]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

比如我想让工作笔记和学习笔记、剪藏笔记分开工作而互相不干扰时，目前来说，如果我所有笔记混在一起，哪怕在不同的笔记本中，引用提示、搜索等地方会出现不必要的干扰

### 描述可能的最优解决方案 Describe the optimal solution

也许可以设计一个开关，让我选择是否打开某个或多个工作空间、或者默认打开上次关闭前的工作空间？

### 描述候选的解决方案 Describe the candidate solution

或许设计不同笔记本隔离的开关也是个不错的选择

### 其他信息 Other information

冲！

**Comment by 88250** [comment]
可以在 设置 - 关于 - 工作空间 进行切换。

**Comment by pjpjp219** [comment]
我想表达的是，我想同时打开多个工作区，他们之间相互隔离，是这个意思

**Comment by 88250** [comment]
目前无法支持。

**Comment by jiewangjs** [comment]
我也有类似的需求，准确的说，我想软件能够开启多个窗口，这样可以把一些不同的工作流分隔开来

**Comment by Soltus** [comment]
像ob那样多开空间是一种效率的工作模式，多开空间的话我认为一定要处理好响应速度，目前思源的响应速度还是不进入人意，无论是软件打开速度（开启同步）还是笔记本（从关闭态）打开速度。相比多开空间，我还是希望能在单个工作空间内实现 `虚拟空间` ，一个笔记本可以属于多个虚拟空间，一个虚拟空间可以有多个笔记本，这样的好处是可以更好控制引用隔离。退一步讲，即使只是支持笔记本多选也是好的。不过从Sofill=对虚拟空间的探索来看，虚拟空间要实现首先需要先解决笔记本打开耗时过长且不可控的问题。

**Comment by GH-W94** [comment]
D 大，为什么把标题中的“同时打开”去掉了，是不是多开工作空间时，就不能实现像切换不同笔记本那样方便的切换不同的工作空间了呢？

**Comment by 88250** [comment]
操作系统会支持窗口切换。

**Comment by UFDXD** [comment]
可以给工作空间创建桌面快捷方式吗？，这样就可以直接在桌面启动指定工作空间了

**Comment by UFDXD** [comment]
测试了一下，发现多开工作空间，缩放页面，一个缩放另一个也会变，各自状态不独立。

**Comment by 88250** [comment]
> 可以给工作空间创建桌面快捷方式吗？，这样就可以直接在桌面启动指定工作空间了

是个好建议，稍后看下是否能支持。

**Comment by 88250** [comment]
启动命令加入参数 `--workspace`，例如：

![image](https://user-images.githubusercontent.com/873584/210913048-e518bbb8-6658-49de-9ccf-d4b38f40b726.png)

**Comment by Vanessa219** [comment]
> 测试了一下，发现多开工作空间，缩放页面，一个缩放另一个也会变，各自状态不独立。

这个是整个应用的，没办法分开。

**Comment by 88250** [comment]
> @Vanessa219 能同一个工作空间支持打开多个窗口吗❓👀

使用场景上应该是页签浮动窗口 #2955

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 鉴权页面能显示工作空间名称以区分不同的工作空间吗, 不同的工作空间可能使用不同的访问授权码

**Comment by 88250** [comment]
> @Vanessa219 鉴权页面能显示工作空间名称以区分不同的工作空间吗, 不同的工作空间可能使用不同的访问授权码

稍后支持。

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/211559360-0677cb6d-7ab5-4822-a152-a567ed6df027.png)
