### ISSUE TITLE
云端图床支持按页批量删除

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4568]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

思源之前有一段时间，应该是会自动把图片上传到图床的，导致我目前的图床有许多无用的图片，占用大量空间，需要批量删除无用的图片

### 描述可能的最优解决方案 Describe the optimal solution

- 添加删除整页的按钮
- 或支持多选后删除

### 描述候选的解决方案 Describe the candidate solution

- 添加删除全部的按钮

**Comment by 88250** [comment]
> 思源之前有一段时间，应该是会自动把图片上传到图床的

真没有这段时间，都是手动点击上传才会上传的。

批量删除后面考虑，现在主要在开发云端收集箱。

**Comment by Achuan-2** [comment]
> > 思源之前有一段时间，应该是会自动把图片上传到图床的
> 
> 真没有这段时间，都是手动点击上传才会上传的。
> 
> 批量删除后面考虑，现在主要在开发云端收集箱。

是吗，不过我云端图床的占用真的很大，300M，里面有很多图片都不是我主动会上传的那种。
好像是很早之前，图床功能刚出来的时候，云端图片和图床没有分开，把图片进行同步，就默认放图床里去了

**Comment by 88250** [comment]
云端图床和本地图片一直都是分开的，同步功能和图床也是分开的，我觉得不可能是程序自动上传的。
