### ISSUE TITLE
改进块引搜索排序规则

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4569]
https://github.com/siyuan-note/siyuan/issues/4558 继续改造。

**Comment by Zuoqiu-Yingyi** [comment]
这个改进貌似又将该特性搞丢了: `命中块命名/别名/备注` 的搜索结果优先级较 `命中块内容` 更高 :broken_heart:
![image](https://user-images.githubusercontent.com/49649786/165594337-1caa4202-0877-42aa-ab83-805d99474186.png)

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 输入在完全等于 name/alias/memo 时优先级最高，如果只是 LIKE 的话，content 的优先级高于这三者。
