### ISSUE TITLE
反链提及中默认纳入当前文档名作为锚文本进行搜索

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#457]
在[20201109]页引用了[xx会员日需求],但是在[xx会员日需求]这一页的反向链接中[链接]与[提及]都显示了该引用
![链接与提及均显示该引用](https://user-images.githubusercontent.com/11732858/98534702-d0ac9000-22bf-11eb-86b8-8f40cb1b11f0.png)

**Comment by 88250** [comment]
上面是列表项块，下面的提及是列表块。如果引用了列表项块，需要在提及中排除整个列表块吗？

**Comment by HarryHuaa** [comment]
A页为被引用页,B页为引用页,
A页在反向链接中的[提及]不应受其他因素影响。
经测试如果B页没有引用A页,此时A页的反向链接中仅会显示[需求1],而当B页的列表块引用了A页后,A页中会同时生成一条链接和一条提及。

我理解[提及]的作用为,提醒用户哪些其他页提到了本页,而两者没有建立引用关系,帮助用户捋清并建立知识节点的关系
因此上面的表现不是特别正确。

期待表现为:
A页标题为[a b],B页的文本中包含"a"或者"b"或者"’a‘c"时,A页显示被B页的某部分提及
A页标题为[ab],B页的文本包含"ab"或者"‘ab’c"时,A页显示被B页的某部分提及

举例:
A页标题为[xx品牌 会员日需求] B页内容为[xx产品会员营销需求],C页内容为[xx品牌相关信息],三页间原本没有建立引用关系
但是此时可以看到A页的[提及]中会显示两条提及,建立链接后
在B页中查看产品整体的会员日需求时,就可以看到"原来xx品牌之前提过这样的会员日需求"
在C页中查看品牌的情况时,也可以看到,"这个品牌之前提过会员日的需求"

因此[链接]的全称为[链接当前内容],[提及]的全称为[提及当前标题(但还没有建立连接)]

**Comment by 88250** [comment]
提及的搜索不是按标题搜索的，而是按块引锚文本（`((id "锚文本"))`）聚合出关键字列表，然后用这个关键字列表进行搜索而来。

我觉得举例场景使用 https://github.com/siyuan-note/siyuan/issues/48 应该会更适合。

**Comment by HarryHuaa** [comment]
对于同类块的收集整理确实如#48描述所说,我场景描述的有问题,我从新表述一下
按照我的理解
场景一:
![image](https://user-images.githubusercontent.com/11732858/98619304-ee203f00-233d-11eb-9856-bdaf2a06716d.png)
在[女朋友]页反向链接中应该能看到,[20201110]提及了本页,延伸开来,可以看到这一年提到[女朋友]的所有情况都有哪些,(内容块动态查询嵌入需要进行嵌入才能看到结果,可能此时我只是想看一下都有什么地方提到这一页了)

场景二:
![image](https://user-images.githubusercontent.com/11732858/98620925-32610e80-2341-11eb-97f1-159695058c34.png)
因为页可能并不是最小的信息单位,所以仅检索文档名也不是特别完善。
在[A品牌]页的提及可以看到[B产品]提及过标题[会员日],在和客户沟通时,可以直接跳转至[B产品]和客户直接沟通
在做[C产品]时,可以看到[B产品]的产品功能提及过[C产品]的标题[会员日],此时可以做内容块嵌入或直接进行复制粘贴

当前疑惑:
![image](https://user-images.githubusercontent.com/11732858/98621961-6ccbab00-2343-11eb-8308-016998b2b4d8.png)
在链接中我可以看到,有另外两个页引用了[INK笔记法]的内容,这没有问题,但是[提及]的内容我就没有看到意义是什么,其中第一个提及是另一个页引用了[INK笔记法]的内容块,第二个提及我感觉是对[链接]中第二项的重复。
经过测试,第一个提及应该是因为引用的是列表项块,所以跑到了[提及]中,正常来说这个应该也是在[链接]中的,引用列表块就可以正常出现在[链接]中

**Comment by 88250** [comment]
所以你需要的是将文档名称默认作为锚文本纳入到提及搜索中吗？

**Comment by HarryHuaa** [comment]
是的
第一需求为提到过当前文档名的其他文本块纳入到提及搜索中
第二需求为提到当前文档中标题的其他文本块纳入到提及搜索中

**Comment by 88250** [comment]
好的，稍后我们先将文档名默认作为反链提及锚文本纳入搜索试试。
