### ISSUE TITLE
公式块悬浮窗增加固定键

### ISSUE THREAD

**Issue by coderlemon17** [siyuan-note/siyuan#4570]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

![image](https://user-images.githubusercontent.com/39124095/162701675-58d3afe0-36f6-46d7-bce5-3b9ae533ae1e.png)

如图, 在输入较长公式时经常需要将悬浮窗调整到一边, 然后根据渲染的结果继续输入公式. 在此期间如果鼠标不小心碰到了其他地方, 悬浮窗就会消失, 就需要再将其调出来后重新调整位置, 如果能够将调整好的悬浮窗固定住, 将会方便很多.

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/39124095/162702225-337868b4-22dc-4912-90dc-14dbfafdf3b3.png)
如果能够类似预览block时增加一个"钉住"的功能就好了.

### 其他信息 Other Information
现在似乎悬浮窗的最大高度有一个限制, 当输入的公式很长的时候, 会比较麻烦... 在`theme.css`里找了一圈也没找到相关的配置, 感觉可能是写在了其他地方?

**Comment by Vanessa219** [comment]
最大值在这里，你需要重置一下
<img width="619" alt="image" src="https://user-images.githubusercontent.com/970828/165012984-e63e223e-5a34-4f41-afe0-4376f161ae9c.png">

**Comment by coderlemon17** [comment]
dbq 我不是很熟悉css操作, 参考思源用户指南里的说明, 我现在在`theme.css`里加了这一行:
```css
textarea.b3-text-field.b3-text-field--text.fn__block {
    max-height: 100vh;
}
```

但是似乎并没有起作用.

---
以及我想问一下, 如果我想修改一个已经安装的主题, 我是应该修改这个主题文件夹里的`custom.css`文件吗? 我现在是直接修改`theme.css`, 但是siyuan似乎每次更新主题都是直接覆盖整个文件夹. 想知道有没有能够保留我的修改的升级主题的办法.

**Comment by Vanessa219** [comment]
需要加 !important。 @88250 看一下覆盖的问题。

**Comment by coderlemon17** [comment]
谢谢, 现在`.css`的修改起作用了.
