### ISSUE TITLE
重制全局搜索

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4573]
之前在 https://github.com/siyuan-note/siyuan/issues/3591 中开始尝试 fts5，后来在 https://github.com/siyuan-note/siyuan/issues/3708 移除了。

现在继续尝试，主要解决中文分词问题。

特别鸣谢链滴社区的一位老铁，他贡献的 C 代码帮助我们实现了 SQLite FTS5 中文单字分词 https://ld246.com/article/1641042386027

**Comment by JCJC01** [comment]
搜索后的定位显示也请改进，
举个例子，在思源里建了一个很长的表格，列为产品号，行为其相关信息，但是通过搜索产品号的时候，搜索栏只显示了部分相关信息，具体信息需要准确定位到文本或表格才能查看完整
即在搜索栏的结果内无法通过点击定位到指定的产品号的位置。
谢谢

**Comment by fanglypro** [comment]
ctrp+p的搜索很快，但块引搜索貌似还是有点慢，块引搜索部分现在是还没修改吗？

**Comment by 88250** [comment]
@fanglypro 块引搜索没改，我们先在全局搜索上跑一段时间看看。`-` 是 FTS 的查询语法操作符 https://www.sqlite.org/fts5.html#full_text_query_syntax

**Comment by Zuoqiu-Yingyi** [comment]
@88250 D大, `2.0.0-beta1` 版本中 `搜索 dialog 面板` 与 `块引/块嵌入搜索菜单` 中的文件路径匹配的关键词都无法高亮了, 标签搜索用的搜索页文件人类可读路径匹配的关键词可以高亮

## Dialog 搜索面板
![image](https://user-images.githubusercontent.com/49649786/164145499-a05c8414-8634-4936-9821-c0cfbc0c366a.png)


## 悬浮搜索菜单
![image](https://user-images.githubusercontent.com/49649786/164145472-50bc37c1-9041-4183-b53f-7cb1f3512561.png)

## 搜索标签页
![image](https://user-images.githubusercontent.com/49649786/164145585-fa9ffcb9-49ac-47e6-8fcb-59772c1ffbb4.png)

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 感谢反馈，b2 修复。

**Comment by Zuoqiu-Yingyi** [comment]
> @fanglypro 块引搜索没改，我们先在全局搜索上跑一段时间看看。`-` 是 FTS 的查询语法操作符 https://www.sqlite.org/fts5.html#full_text_query_syntax

经过测试, 目前好像不支持使用 FTS 查询指定字段功能查询除 `content` 以外字段的功能
[https://www.sqlite.org/fts5.html#fts5_column_filters](https://www.sqlite.org/fts5.html#fts5_column_filters), 希望能使用如下语法触发指定字段的查询, 比如想查询某个域名所有超链接, `content` 字段只能查询锚文本查询不到
```
markdown: bilibili
```

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 看下帮助文档 - 查询语法，里面有提到一些限制。

**Comment by Zuoqiu-Yingyi** [comment]
> 另外，用自己写的完整 SQL 应该可以做到。

看到了, 多了 12 张表❤

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 收到，感谢反馈啊。

**Comment by Zuoqiu-Yingyi** [comment]
@88250 块引用/块嵌入搜索不支持标点符号了, 使用 `"` 包围也没法搜索到:broken_heart:

![思源笔记-bug反馈-26](https://user-images.githubusercontent.com/49649786/164407463-1687f765-5130-406c-93a5-386fac590f1b.gif)

貌似是因为光标后的 `"` 未被视为查询语句的一部分
``[["#js"` 光标在后引号前无法查询, 在后引号后可以查询
![image](https://user-images.githubusercontent.com/49649786/164408376-4a25c9c8-d850-4677-8294-b8991071902e.png)

![image](https://user-images.githubusercontent.com/49649786/164408365-1701a221-1436-4677-ab86-75233bf9382c.png)
