### ISSUE TITLE
导入markdown文件夹会产生多余空白文档

### ISSUE THREAD

**Issue by SineObama** [siyuan-note/siyuan#4577]
v1.9.9。导入md文件夹时，文件夹自身会形成一个空白文档，父md页面是另一个单独的文档，子页面在空白文档下面。

期望处理方式之一：文件夹与同级（或下级）同名md文件合并，避免重复和页面结构分离。

我刚上手，想导入外部markdown，最后发现内部导出再重新导入也会出现类似问题。

例如思源内树结构的文档：

* a
  * b

导出后，子文档会放在文件夹中：

* a.md
* a
  * b.md

再导入就成这样：

* a  （正文）
* a  （空白）
  * b  （正文）

同时我也想问问markdown是否有标准的树结构文件组织方式。

**Comment by 88250** [comment]
这是符合设计预期的，否则无法将父子文档结构映射到文件系统上（文件和文件夹会重名）。

Markdown 是一种标记语法，不涉及文件组织管理。

我们先关闭了，如果还有疑问欢迎跟帖。
