### ISSUE TITLE
手机、浏览器端支持滚动截屏

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4578]
### 描述问题

手机端（安卓红米k40）不支持滚动截屏
电脑端（win11）使用edge浏览器打开思源笔记也不支持浏览器自带的滚动截屏

**Comment by 88250** [comment]
滚动截屏估计是不好实现，后续先考虑导出长图 https://github.com/siyuan-note/siyuan/issues/2919
