### ISSUE TITLE
图片复制PNG无效

### ISSUE THREAD

**Issue by lvvlxu** [siyuan-note/siyuan#4579]
### 描述问题 Describe the problem
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/44394483/162900542-8a837496-1999-413f-88a6-404be72ebcb4.png">

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
你好，我们这里无法重现问题，麻烦提供更详细一些的重现步骤，谢谢。

**Comment by lvvlxu** [comment]
docker部署的版本，这个就点击图片复制png，没什么步骤吧，客户端应该没问题 @88250

**Comment by 88250** [comment]
在浏览器中单独打开这个图片复制能正常么？

**Comment by lvvlxu** [comment]
在浏览器单独打开可以复制

**Comment by lvvlxu** [comment]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/44394483/163193917-8273ba6d-5560-482e-a82f-d3e335d3e4c1.png">

**Comment by Vanessa219** [comment]
收浏览器安全限制，升级为 https 的再试试。
