### ISSUE TITLE
支持设置浏览器端访问鉴权

### ISSUE THREAD

**Issue by TonyW825** [siyuan-note/siyuan#458]
#### 场景
- 局域网办公环境

#### 问题
- 只要知道使用者IP地址就可以查看和编辑对方笔记本中的所有文档

#### 需求
- 设置有关规则来进行访问控制

**Comment by 88250** [comment]
目前想到的简单方案是通过 http://ip:port?code=xxx 控制，xxx 在设置中配置，配置后只有通过带 xxx 的链接才能打开思源网页端。

**Comment by 88250** [comment]
设置 - 关于里面会加入一项 `访问授权码`，配置以后通过浏览器访问时将自动弹出用户名/密码验证框。用户名使用固定的 `siyuan`，密码使用配置的访问授权吗。
