### ISSUE TITLE
绘图更新机制改进

### ISSUE THREAD

**Issue by yangguang760** [siyuan-note/siyuan#4580]
版本v 1.9.9

目前不管是使用 graphviz 还是 plantuml, 都是根据编辑框里的描述代码更新触发刷新图片。
在我的实际使用中，有两个问题
一是编辑代码体验不好，每次击键都刷一次图片，卡顿严重
二是多次出现整个程序白屏假死的情况出现，关窗口或者任务栏退出都没用，只能杀进程。

建议可以在编辑框添加”刷新图片“按钮，按了才刷新

**Comment by lingr7** [comment]
多次出现整个程序白屏假死的情况出现，关窗口或者任务栏退出都没用，只能杀进程。
