### ISSUE TITLE
增加按文件大小或按文件类型过滤同步列表

### ISSUE THREAD

**Issue by yangguang760** [siyuan-note/siyuan#4581]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?
我的云端大概200M 笔记图片，2G pdf
通常我在电脑端希望进行全量同步，而在移动端往往只是轻量查看（仅看笔记和图片，不看pdf），希望仅同步部分文件，从而省流量省存储省同步时间

### 描述可能的最优解决方案 Describe the optimal solution

希望可以增加按文件大小或按文件类型过滤同步列表

**Comment by 88250** [comment]
文件类型可以试试用后缀匹配忽略，参考帮助文档 `忽略文件`。

**Comment by yangguang760** [comment]
谢谢！刚看了文档，有些疑问：
1、syncignore 文件本身是否会被同步？（换言之，我希望基于不同设备有不同的ignore策略）
2、被syncignore中通配符所匹配的文件，是上传下载都会被ignore么？

**Comment by yangguang760** [comment]
如果syncignore本身会被同步的话，那么当前是无法实现不同设备采用不同ignore策略的，对么？
忽然想到一个workaround，syncignore添加自身的话，会被ignore么？

**Comment by 88250** [comment]
应该是无法实现针对设备忽略文件的。
