### ISSUE TITLE
目前API较少，希望提供更多的功能

### ISSUE THREAD

**Issue by ToForgiveNoll** [siyuan-note/siyuan#4582]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

1. 我是一个java开发
2. 我想用es去管理和搜索我的笔记 大数据分析自己的笔记内容
3. 希望后续开发中多提供一点API

### 描述可能的最优解决方案 Describe the optimal solution

- 开发相关API（包含但不限于我需要的），这同时也会助力于相关生态的发展
- 需要协助时请联系我，你将收获一个免费的外包苦力 Email: 1224177203@qq.com

**Comment by 88250** [comment]
API 主要用于交互，数据分析的话可以考虑从 SQLite 中获取数据灌入 ES。

先关闭了，如果有进一步讨论欢迎随时跟帖，谢谢。
