### ISSUE TITLE
某些情况下缺失 `updated` 属性

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4584]
https://ld246.com/article/1649675028485

**Comment by fanglypro** [comment]
这个问题貌似还在，还是有块没有显示updated，只显示created：

![image](https://user-images.githubusercontent.com/57083732/165798464-0db1b1ea-78c1-48eb-8533-6dd165d88bf2.png)

**Comment by 88250** [comment]
F5 刷新以后也是？

**Comment by fanglypro** [comment]
F5 后还是一样

**Comment by 88250** [comment]
重现步骤麻烦提供一下。

**Comment by fanglypro** [comment]
![temp225](https://user-images.githubusercontent.com/57083732/165878978-4ebd7e81-b000-4d24-92ae-ef19237f796f.gif)

**Comment by 88250** [comment]
F5 我这里是正常的

![issue](https://user-images.githubusercontent.com/873584/165880696-a70f1e3c-0c27-4dba-ac3f-6b74abe2a78c.gif)

**Comment by fanglypro** [comment]
换一种方法，见下图，刷新后，`3`是有updated的，但`1`和`2`没有：

![temp226](https://user-images.githubusercontent.com/57083732/165881102-a475c2bc-a4d2-4e0a-9f5c-b7954fe90f77.gif)

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/4733 中继续修复。
