### ISSUE TITLE
某些特定的笔记树开启/关闭外链分享功能。

### ISSUE THREAD

**Issue by flysaber** [siyuan-note/siyuan#4585]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

1. 日常办公生活交流，将自己的笔记生成外链，通过社交工具发送到群中，社区中，或者个人。
2. 笔记树生成外链，可以形成简单的产品说明书，电子书，共享知识库等。

### 描述可能的最优解决方案 Describe the optimal solution
3. 如果是在思源的官方云上实现，可将用户选择的部分笔记，生成静态网页，保留绝大部分渲染效果，然后通过官方的子域名发布，类似于Obsidian的发布服务：[Obsidian的发布服务](https://obsidian.md/publish)，这是其展示例子：[发布案例](https://notes.gnotract.com/00+%F0%9F%A4%AF+Meta/%F0%9F%93%8C+Landing+Page)
5. 也可以在Dokcer端实现该功能，用户自建服务器发布某部分笔记，功能可收费。
6. 已经查看思源的计划，发布笔记到链滴社区，但是窃以为，前面1，2功能的需求不适合发布到社区论坛成为一个帖子，比如语雀的外链分享也不会分享到语雀论坛成为帖子（当然可以通过思源官方发布分享）。

7. 思源的一个插件[oceanpress](https://github.com/siyuan-note/oceanpress)，已经实现了部分效果，然而非前台按钮控制，也不能方便指定某部分笔记分享。
8. 实现该功能的有 Notion ，coda，语雀，飞书，wolai，等。
9. 如果说 7 所涉及是云笔记和思源定位不一致的话，那么Obsidian，[trilium](https://github.com/zadam/trilium)和思源定位一致，也是离线笔记，但是 trilium 具有服务端，也有笔记分享功能，且根据作者自述，该功能还会加强。

**Comment by 88250** [comment]
已经在链滴回复，感谢提议。

https://ld246.com/article/1649788852154
