### ISSUE TITLE
表格改进

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4586]
- [x] 直接在表格中以链接的形式插入图片时，会变成在表格下方的块插入图片
- [x] 表格中双击图片预览没有显示
- [x] 表格中的超链接文本会对光标位置移动有影响，上下移动光标时会跳过文本所在行，光标在文本开头时按下回车键，应该是文本换到第二行，实际却是文本留在第一行，光标跳到了第二行

**Comment by Zuoqiu-Yingyi** [comment]
这里还有两个表格内行级元素的渲染问题
1. 表格内公示后输入文本会暴露标志符号
2. 表格内输入 `<kbd>` 会导致当前单元格无法聚焦
![思源笔记-bug反馈-22](https://user-images.githubusercontent.com/49649786/163107347-752cf5eb-2c71-475d-a879-4d6127fb80ad.gif)

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 麻烦单独提 issue，谢谢。
