### ISSUE TITLE
钉住的页签使用 Emoji 或标题的第一个字

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4588]

**Comment by Elliootalderson** [comment]
用":+图标名"输入emoji时,优先选中的是鼠标悬停位置的emoji,而非自己输入图标名的emoji.

希望可以取消一下鼠标悬停选中emoji,改为通过点击的方式选中emoji.

**Comment by Zuoqiu-Yingyi** [comment]
能不能仅使用 CSS 样式实现该特性, 现在 DOM 树中也只有一个字导致使用主题样式也没法完整显示文档名, 而我有不少数字开头的文档, 现在完全分不清了😭
