### ISSUE TITLE
更便捷建立两个块之间的联系

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#459]
已经建立了A、B两页并且各自输入了内容
A页内容[a同b一起去了xxx]
B页内容[xxx的游玩路线.......]
此时发现A页内容的xxx可以引用B页对应的文本块[xxx的游玩路线....]

现在的方法为
1.在[a同b一起去了xxx]的xxx之前输入"[["然后找到B页中的内容块,建立引用,
2.把锚文本改为"xxx",
3.把引用后面的xxx删掉

需求:
1.框选住A页中的"xxx"后,点击右键,在"新建文档"的选项下面多一个[根据已有内容块进行引用],建立引用后,锚文本自动为"xxx"

从3步变为1步

**Comment by 88250** [comment]
感谢场景举例，请看 https://github.com/siyuan-note/siyuan/issues/402
