### ISSUE TITLE
#下载恢复数据出现问题

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4592]
<img width="796" alt="Snipaste_2022-04-13_17-57-38" src="https://user-images.githubusercontent.com/66512309/163154010-24898be6-9618-4288-8c1c-f3fa2b19b9a4.png">
新按照的1.9.9，原来软件已经被完全删除，此状态一直持续，无法恢复到本地

**Comment by Faith-YSQ** [comment]
新安装，打错字了

**Comment by Faith-YSQ** [comment]
关闭软件后，换移动网络可以恢复了，之前使用的网络是广电的网络

**Comment by Faith-YSQ** [comment]
我上午备份的

**Comment by 88250** [comment]
那可能是数据没有下载到本地。解决就好，感谢反馈。
