### ISSUE TITLE
建议增加对划取字段的评论功能&建议重新考虑表格的功能键

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4595]
## 评论功能希望是类似对话气泡那种。和word审批功能应该是一个性质

**Comment by 88250** [comment]
你好，评论特性请关注 https://github.com/siyuan-note/siyuan/issues/174 如果要做的话会重开；表格的话估计不会改动了，否则无法导出为 Markdown 了，感谢反馈。
