### ISSUE TITLE
`<kbd>` 渲染错误问题

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4596]
两个表格内行级元素的渲染问题
1. 表格内公示后输入文本会暴露标志符号
2. 表格内输入 `<kbd>` 会导致当前单元格无法聚焦

![思源笔记-bug反馈-22](https://user-images.githubusercontent.com/49649786/163107347-752cf5eb-2c71-475d-a879-4d6127fb80ad.gif)

Version: `1.9.9`

_Originally posted by @Zuoqiu-Yingyi in https://github.com/siyuan-note/siyuan/issues/4586#issuecomment-1097578524_

**Comment by 88250** [comment]
这两个问题和表格好像没有关系，段落里也是这样的。先记录一下目前的排查情况：

* 第一个问题是因为 Lute 选项 `SetInlineMathAllowDigitAfterOpenMarker` 好像没生效导致
* 第二个问题是因为 kbd 没有闭合，暂时没有解决思路

**Comment by 88250** [comment]
行级公式解析的问题在 https://github.com/siyuan-note/siyuan/issues/4605 中处理。

**Comment by 88250** [comment]
新的编辑器不再支持通过 HTML `<kbd>` 和 `<u>` 输入键盘和下划线元素 https://github.com/siyuan-note/siyuan/issues/5877

这个我关闭了，谢谢。
