### ISSUE TITLE
#markdown文件夹导入有缺陷

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4601]
导入markdown文件夹，里面图片的路径会被的识别为HTML，这样会直接引入相对路径，但是siyuan的数据文件夹并没有这些相对路径，导致图片无法显示。并且建议这里可以识别为图片，而不是HTML。

**Comment by 88250** [comment]
你说的是 `<img>` 标签吗？

**Comment by Faith-YSQ** [comment]
<img width="900" alt="Snipaste_2022-04-14_10-18-12" src="https://user-images.githubusercontent.com/66512309/163301149-d1177c39-6ebf-4625-812d-8c07660d1b12.png">

**Comment by 88250** [comment]
这个是按照 Markdown 语法解析的，应该没有问题。估计只能在导入前外部处理好。
