### ISSUE TITLE
请问 linux 版本可以上架 deepin 系统的应用商店吗？

### ISSUE THREAD

**Issue by dabuge** [siyuan-note/siyuan#4603]
如题

**Comment by 88250** [comment]
暂时没有时间研究，如果不涉及到公司实体验证的话欢迎社区提供贡献。

**Comment by terwer** [comment]
目前测试deepin和uos无法运行，提示

➜  linux-unpacked git:(dev) ./siyuan
xdg-settings: unknown desktop environment

**Comment by terwer** [comment]
在星火商店找到了打包好的，不过不是最新版本。
spk://store/office/org.b3log.siyuan.spark

**Comment by terwer** [comment]
找到原因了，权限问题
https://bbs.deepin.org/post/240365

使用sudo运行，并且加上 --no-sandbox

如果是解压版的，使用下面命令就行了

```
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox
```

uos和deepin都可以这样做。
