### ISSUE TITLE
🎨 新图标征集

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4608]
## 背景

也许还有人记得第一版那个比较丑的官网，那是我和 @Vanessa219 花了半天时间做的，那时候开发时间太紧张了，所以我们优先考虑开发思源本身的功能。思源的图标大概花了几分钟做的，当时思源主要是基于 Vditor 和 Lute 开发的，所以图标也就取自这两个项目：

![Vditor.png](https://user-images.githubusercontent.com/873584/163508556-13cb6f2c-75aa-46ff-aad8-a1c79e94ca58.png "Vditor")![Lute.png](https://user-images.githubusercontent.com/873584/163508560-a4456144-b0b9-4ce1-a687-0da238eb4d76.png "Lute")![SiYuan.png](https://user-images.githubusercontent.com/873584/163508557-92ab80df-9022-4f6d-84e6-ec53554dbcff.png "SiYuan")

当然，以上这些显然不是什么值得炫耀的事情，只是想说明这个图标的来历。现在，随着思源功能的逐步完善，我们觉得是时候改进外观了，就先从图标开始吧。

## 构思

思源出自“饮水思源”，这个词提醒我们做人做事不能忘本；作为双链笔记，“思源”也提醒我们在引用时不要忘记定义的出处，这就是思源笔记命名的来历。

发散来说，“思源”提醒我们在个人成长的道路上应该不断回顾、总结复盘、整理知识和自己的所思所想。只要生命不息，这个过程就不应该终止。所以“思源”也无时无刻不在描述着无穷的当下。

基于这一点，新版图标的构思我们联想到了“[莫比乌斯带](https://zh.wikipedia.org/wiki/%E8%8E%AB%E6%AF%94%E4%B9%8C%E6%96%AF%E5%B8%A6)”：

![莫比乌斯带.png](https://user-images.githubusercontent.com/873584/163508562-d2691a77-a355-4940-893d-cae5c940229a.png "莫比乌斯带")

## 原型

结合思源的英文名称 SiYuan，取第一个字母“S”后，图标设计思路大概是这个样子：

![demo.png](https://user-images.githubusercontent.com/873584/163508529-9ab0d4c4-3f31-4ef1-9610-70e473d62dd7.png)

这里有几点基础需要考虑：

* 思源本身有水的含义，所以图标应该要表现出水的形态
* S 字母要能够容易识别出来

目前考虑的大概就是这么多，如果你有更多想法也欢迎讨论。

## 征集

我们需要专业的设计师帮忙制作图标，设计的图标作品需要公开在评论区，这样才能方便更多人进行点评。被选中的作品我们会保留设计师的署名，并在思源帮助文档和 GitHub 仓库项目 README 中按作者需求进行页面链接。

征集结束时间暂定为一个月后，还请设计师们踊跃投稿，谢谢！

**Comment by WolkeAtreide** [comment]
我果然是预言家。
希望能收到一个非常非常好的作品投稿！

**Comment by 88250** [comment]
链滴 https://ld246.com/article/1649990381675

**Comment by 88250** [comment]
暂时先不调整了，期待社区能有好的方案出现。
