### ISSUE TITLE
代码块使用 `Tab` 缩进后渲染异常

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4609]
### 描述问题 Describe the problem

复现步骤:
1. 新建一个代码块
2. 在代码块中粘贴文本
3. 回车
4. 使用 <kbd>Tab</kbd> 键时会生成一个未渲染出来的新行

![思源笔记-bug反馈-23](https://user-images.githubusercontent.com/49649786/163511854-165f9515-d294-4959-a69c-8fd5225f550b.gif)

### 期待的结果 Expected result

使用  <kbd>Tab</kbd> 键时正常缩进

### 版本环境 Version environment

* Version: v1.9.9

**Comment by Vanessa219** [comment]
好像重现不了，有什么需要注意的么？

https://user-images.githubusercontent.com/970828/163570721-b0ff74b3-f0ec-4b22-8708-38a4e7646431.mp4

**Comment by Zuoqiu-Yingyi** [comment]
> 好像重现不了，有什么需要注意的么？
> 
>  QQ20220415-202801-HD.mp4

剪贴板最后一个字符是一个换行符时可以复现

![思源笔记-bug反馈-24](https://user-images.githubusercontent.com/49649786/163572967-490cea3a-8167-4950-83b5-deff9ac6ea60.gif)
