### ISSUE TITLE
支持标签搜索

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#461]
- 能用多个标签进行搜索、筛选。
- 标签搜索能过滤，例如有文本含＂math＂，有标签含＂math＂，我只想要标签含＂math＂的内容块。
![image](https://user-images.githubusercontent.com/26304888/98619445-350e3480-233e-11eb-91a4-db4e22d76d25.png)
![image](https://user-images.githubusercontent.com/26304888/98619458-3b9cac00-233e-11eb-928a-384b540cbd16.png)

**Comment by 88250** [comment]
v0.4.6 支持，搜索标签时使用 `#tag#`。
