### ISSUE TITLE
Callout Blocks

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#4614]
For my personal needs, this would help me a lot!

I would suggest implementing "Callouts blocks".
Basically, they are notebooks that we enter a title and, just below, we add information. With a small difference, it is possible to open or collapse this information, showing only the title.

Closed:
![image](https://user-images.githubusercontent.com/90691302/163582751-7df01faa-09ce-4405-88e7-79533f6967b1.png)

Opened:
![image](https://user-images.githubusercontent.com/90691302/163582799-5249cbb5-a77a-4b17-ad1c-aafd0010554e.png)

**Comment by 88250** [comment]
Hello, consider using Super Block to achieve a similar effect.

![image](https://user-images.githubusercontent.com/873584/163656682-47316971-2b77-4ea9-9d7b-705d63cd7e6e.png)

**Comment by Achuan-2** [comment]
You can make a template.md like this
```html
<div>
<details>
  <summary>title</summary>
content
</details>
</div>


```

**Comment by taozina** [comment]
> ```
> <div>
> <details>
>   <summary>title</summary>
> content
> </details>
> </div>
> ```

Perfect friend! Could you help me with just one more thing? I don't know this programming language. Is it possible to make the "title" bold and with a different color (text or background)?

**Comment by Achuan-2** [comment]
you can change the color to ”blue“, "green", or just hex like "#8250df"
![image](https://user-images.githubusercontent.com/60436214/163672202-c8d461fb-c932-44d4-a3ee-06c2195b8138.png)
```html
<div>
<details>
  <summary style="font-weight:900; color:red">title</summary>
content
</details>
</div>
```

**Comment by taozina** [comment]
Perfect. Thanks, man. You are incridible.

**Comment by Achuan-2** [comment]
different background
```html
<div>
<details>
  <summary>title</summary>
content
</details>
</div>
<style>
summary {
	font-weight:900;
	 background:#e3f1de;
}
</style>
```

![image](https://user-images.githubusercontent.com/60436214/163672335-99d556eb-09a2-461d-adf4-7ad151675cc1.png)

**Comment by taozina** [comment]
> you can change the color to ”blue“, "green", or just hex like "#8250df" ![image](https://user-images.githubusercontent.com/60436214/163672202-c8d461fb-c932-44d4-a3ee-06c2195b8138.png)
> 
> ```
> <div>
> <details>
>   <summary style="font-weight:900; color:red">title</summary>
> content
> </details>
> </div>
> ```

Testing here... It's very limited! I can't add program functions inside the block. Anyway, thanks for the help...

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/163672523-4f53cd33-708e-409d-856a-5c4abf52d127.png)
or you can use list in siyuan , which is very convenient and powerful

**Comment by taozina** [comment]
@Achuan-2 Hello friend! Could I ask a question? I study for very difficult exams in my state. I need to be reviewing some materials all the time!

As it was my first contact with SiYuan, I made a lot of information formatting errors, I made internal links with several wrong information.

I would like to start over!

Is it possible for me to open another SiYuan on the same machine? Each with a different folder!

**Comment by Achuan-2** [comment]
The best chocie is that you can create a new notebook to write and put your old notes  in another notebook. I also have a notebook for all the messy stuff I wrote down earlier. my notebooks are as follows（using P.A.R.A organizational system)
![image](https://user-images.githubusercontent.com/60436214/163895637-e43d5b51-3c60-44c5-82da-11abab09e4ae.png)

or you change the workplace dir, but in this way you can't not open two Siyuan in the same time
![image](https://user-images.githubusercontent.com/60436214/163895297-81b1e0c7-46e7-4b64-8ba0-90bd1f420581.png)

**Comment by taozina** [comment]
@Achuan-2 Thanks, friend. How to add these icons in your notes? I'm use colorful icons in Windows 11, but is ugly.

**Comment by Achuan-2** [comment]
for notebooks, I just use Tsundoku icon in bazaar.
for notes, I used to use window 11 emoji, It's definitely uglier than Win10 emoji, but it's acceptable
you can add cutsom emoji to workplace/data/emojis/  or use twemoji in Settings/Appearence
![image](https://user-images.githubusercontent.com/60436214/163897921-46895681-0487-446e-bacd-6dc5dfbc1eb5.png)

**Comment by taozina** [comment]
@Achuan-2 I have a pack with 3000 thousand icons in .svg format that I use in Obsidian. Is it possible for SiYuan to recognize?

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/163898813-dfbde7e7-0dea-42ac-bf1e-8d3a181c0581.png)
you can try it

**Comment by taozina** [comment]
@Achuan-2  Perfect! Last question... All my icons are black. Can SiYuan convert to white automatically when the dark theme is activated?

**Comment by Achuan-2** [comment]
it need to change theme.css
