### ISSUE TITLE
1.9.9版本引用块失效了

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4617]
### 截屏或者录屏演示 Screenshot or screen recording presentation

![动画](https://user-images.githubusercontent.com/5968678/163661332-bc17b9a2-fef3-4479-baa2-2a1922ec4aca.gif)

Win10+1.9.9

**Comment by 88250** [comment]
感谢反馈，已在 https://github.com/siyuan-note/siyuan/issues/4571 中处理。
