### ISSUE TITLE
HTML块能否支持contenteditable="true"把修改内容写入

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4618]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

个人认为，思源引入html块后可以大大丰富笔记的样式，而免去主题自己自定义样式，造成不同主题功能上的差别。
如果html支持添加contenteditable="true"属性后，可以直接修改原html内容的话，可以增强html块的实用性，设计各种功能块，让小白用户也能使用html块进行编辑。
不大了解html，不知道此方案可不可行

**Comment by Vanessa219** [comment]
这样没发修改哦，修改了会打乱整个 html 结构的。
