### ISSUE TITLE
论坛无法访问

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#4619]
D大，这两天论坛打开特别慢，一直显示下面这个，我看很多人都遇到了，辛苦排查。
<img width="780" alt="image" src="https://user-images.githubusercontent.com/16383685/163705809-e7b328ce-2a2e-440e-aa25-b1eb33fd3e8d.png">

**Comment by fanglypro** [comment]
从之前遭受ddos攻击然后修复之后开始，链滴就常常打开得很慢，经常是：打开网站2分钟，点击“发布反馈或分享”2分钟，上传图片2分钟，点击发布两分钟，发一个帖子总共要花十多分钟

**Comment by woniuxia** [comment]
真实了。
有时候 github 比 ld246 打开的还快。。。

**Comment by 88250** [comment]
现在 CDN 用的是 Cloudflare，估计没法解决，只能先这样了。
