### ISSUE TITLE
增强搜索功能

### ISSUE THREAD

**Issue by Tokubara** [siyuan-note/siyuan#462]
首先, 我觉得最方便的是, 类似于vscode的command+P, 可以搜索文件名迅速跳转. 这是我觉得最重要的搜索. 但现在似乎还不支持对文件名的搜索, 我搜索文件名, 没有得到任何结果.

然后. 当前全局搜索功能, 是对块级别的搜索, 且支持一个关键词, 不支持标签(我输入#TODO#没有得到任何结果)
我觉得可以:
1. 支持标签过滤, 只搜索包含某标签的块
2. 支持多个关键词
3. 支持块和全文两级搜索范围. 这是因为如果支持多个关键词, 可能没有快同时包含所有关键词, 但都出现在一个doc中

最后, 对于((关键字搜索, 不知道怎么回事, 比如我输入((`, 应该有很多代码块, 但是候选列表却只出现了一个, 甚至没有出现文内已经有的块.

**Comment by 88250** [comment]
1. 文件名的搜索：`d文件名`。其中 `d` 是文档块前缀，具体请参考帮助文档搜索章节
2. `#tag#` 类型的搜索目前还没有支持，暂时只能通过搜索 `tag` 来匹配
3. 块引搜索在没有搜索条件的情况下只是随机列出，稍后会进行改进

**Comment by 88250** [comment]
感谢反馈，搜索功能会进一步加强改进。我关闭了，谢谢。
