### ISSUE TITLE
多次动态加载以后卡顿问题

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#4620]
希望思源开发者能够阶段性的优化
最新版

**Comment by 88250** [comment]
是否是多次动态加载以后卡呢？

**Comment by UFDXD** [comment]
@88250 
是的，特别是我从上到下全文浏览后拖动任意块反应特别慢（浏览器模式中更加慢）
我的文档没有图片，只有文本和和思源提供的各种块。
我发现即使只有3万字的文档，文件实际大小都超过2M了
打开sy原文件查看发现里面各种块的格式文本太多了比实际内容还多

**Comment by 88250** [comment]
多次动态加载以后，加载过的节点没有删除，所以会比较卡。后期会考虑优化。

**Comment by Vanessa219** [comment]
新版本已优化，还麻烦再看看。
