### ISSUE TITLE
使用内网穿透在外网访问时，卡在logo的加载界面

### ISSUE THREAD

**Issue by Tlonglan** [siyuan-note/siyuan#4621]
### 描述问题 Describe the problem
使用花生壳软件进行内网穿透，将伺服用的地址映射到外网上，并在外网进行访问时，卡在了logo的加载界面
![image](https://user-images.githubusercontent.com/38731172/163716029-1feb61c6-e0c6-4022-a488-3737c65b2379.png)

看了一下加载的过程，发现是下面一项加载失败了
![image](https://user-images.githubusercontent.com/38731172/163716082-d85a23a1-0e23-4de3-934d-a9ae84005386.png)

### 期待的结果 Expected result

希望使用外网访问时能正常打开应用

### 版本环境 Version environment

* Version: 1.9.8
* Operating system: 华为荣耀
* Browser (if used): Edge

### 日志文件 Log file
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8501660/siyuan.log)

### 更多信息 More information
无

**Comment by 88250** [comment]
你好，这个问题估计暂时无法解决，除非修改内核启动参数（加入 `--servePath`），但是移动端目前没有办法改参数。

**Comment by Tlonglan** [comment]
不是移动端的，是在访问win端的程序，（访问的时候没有开移动端）

**Comment by 88250** [comment]
哦，那可以试下单独启动内核，加入启动参数 `--servePath`，参考帮助文档 Docker 伺服章节。

**Comment by Tlonglan** [comment]
谢谢，我去试试看

**Comment by Tlonglan** [comment]
> 哦，那可以试下单独启动内核，加入启动参数 `--servePath`，参考帮助文档 Docker 伺服章节。

请问一下，是在填写映射的时候加入参数，还是在本地内核程序启动的时候加入这个参数呀，win端双击Siyuan-Kernel好像没有成功启动

**Comment by 88250** [comment]
启动内核时的参数，可以参考 `C:\Users\用户名\.config\siyuan\app.log` 里面的启动日志。

**Comment by Tlonglan** [comment]
请问怎么单独启动内核呢？双击启动 和 命令行启动 似乎没有生效

**Comment by 88250** [comment]
app.log 里面那一句应该没问题，如果执行了没有输出也没有拉起进程，看下是不是被杀毒软件拦截了。

**Comment by Tlonglan** [comment]
已经拉起进程了，但是加了`--servePath=域名`这个参数后进程很快就结束了，不加这个参数的话可以正常停留

**Comment by 88250** [comment]
启动命令发一下。

**Comment by Tlonglan** [comment]
D:\SiYuan\resources\kernel\SiYuan-Kernel.exe --workspace=E:\Program\SiyuanNote\Private\ a51829h171.zicp.vip:48265 --resident

**Comment by 88250** [comment]
> D:\SiYuan\resources\kernel\SiYuan-Kernel.exe --workspace=E:\Program\SiyuanNote\Private\ a51829h171.zicp.vip:48265 --resident

没加 `--servePath`？

**Comment by Tlonglan** [comment]
D:\SiYuan\resources\kernel\SiYuan-Kernel.exe --workspace=E:\Program\SiyuanNote\Private\ --servePath=a51829h171.zicp.vip:48265 --resident

**Comment by Tlonglan** [comment]
发错，已经加了的

**Comment by 88250** [comment]
`--wd` 呢？

**Comment by Tlonglan** [comment]
噢噢，我看帮助文档里说可以不填，默认调用`-workspace`里的，就没有加上去
现在可以访问了，谢谢D大耐心解答！！
