### ISSUE TITLE
退费申请到底过不过，我是七天无理由，没有用激活码，请你们看一看邮箱

### ISSUE THREAD

**Issue by dongnan-lice** [siyuan-note/siyuan#4623]
### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
正在处理，请耐心等待。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/4622

**Comment by 88250** [comment]
已经退款完毕，请看一下支付宝。
