### ISSUE TITLE
图片 OCR

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#4624]
### 描述可能的最优解决方案 Describe the optimal solution

可以借助这个轮子
[离线批量文字识别(图片转文字)软件 Umi-OCR v1.2.1](  https://www.52pojie.cn/thread-1623670-1-1.html  )    
[hiroi-sora/Umi-OCR: OCR离线批量图片文字识别软件，带界面。可排除视频图片中的水印、游戏图片中的UI等干扰，提取干净的文本。基于 PaddleOCR 。](  https://github.com/hiroi-sora/Umi-OCR  )    

感觉这个轮子很适合思源笔记，不知道可以不

**Comment by 88250** [comment]
感谢提议，但是这个项目似乎不是跨平台的，所以应该无法直接使用。

后续我们会考虑看是否还有适合的库来做这件事，也欢迎继续提供思路。先关闭了，谢谢。

**Comment by Jack20152019** [comment]
天若ocr识别挺好的，不知道能不能整进去

**Comment by lingr7** [comment]
这个是支持中文的，c++，源码级跨平台。https://github.com/DayBreak-u/chineseocr_lite/tree/onnx/cpp_projects/OcrLiteNcnn
