### ISSUE TITLE
支持块引和块超链接的相互转化

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4628]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

在思源中，块超链接就相当于单向的链接。块引则是双向链接，希望两者可以支持相互转化，让思源的链接能够更加灵活，一方面也能起到过滤无用双链的目的，比如之前使用双链来链接文档，之后信息得到处理，不希望再出现在反链面板，但又希望保留链接功能。

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/60436214/163801518-0de38463-2e3a-48b6-8076-ffb9ec5b251e.png)

![image](https://user-images.githubusercontent.com/60436214/163801565-72116a08-b0e8-4a17-b6ce-38d30510831f.png)

**Comment by Chenm4** [comment]
现在复制块超链接在ctrlv粘贴的是纯文本，用ctrl k粘贴虽然是超链接但是没有名字，这是个bug吗

**Comment by 88250** [comment]
@Chenm4 不是
