### ISSUE TITLE
导入 Markdown 功能支持解析 GKM 规范的引用链接

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4634]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

最近出土了一批两年前的 Markdown 笔记, 发现所有的图片链接都使用了引用链接 [reference link](https://github.github.com/gfm/#reference-link), 导致导入时部分链接与图片未解析

### 描述可能的最优解决方案 Describe the optimal solution

解析器支持 GKM 规范引用链接

### 其他信息 Other information

引用链接有如下三种形式

```markdown
![foo][bar]
[foo][bar]

[bar]: /url "title"
```
```markdown
![foo][]
[foo][]

[foo]: /url "title"
```
```markdown
![foo]
[foo]

[foo]: /url "title"
```

**Comment by 88250** [comment]
这个不考虑支持了，感谢提议。
