### ISSUE TITLE
嵌入块无法识别换行符

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#4635]
![image](https://user-images.githubusercontent.com/101959415/163914442-bdad4a00-4988-4861-9730-873614ebd3af.png)
![image](https://user-images.githubusercontent.com/101959415/163914499-10c7e8da-d53c-4969-926b-0dd5dbb33732.png)

**Comment by 88250** [comment]
正常情况下 SQL 脚本是可以换行的：

![image](https://user-images.githubusercontent.com/873584/163998696-5093c265-136f-4283-895d-2d173ce1b76c.png)

你反馈的问题应该是因为 `}}` 命中了查询嵌入块的结束标记符。这个估计没有办法，只能换个查询方式了。

**Comment by WolkeAtreide** [comment]
多谢
