### ISSUE TITLE
从浮窗三击全选复制内容粘贴后触发状态异常

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#4636]
![「思源笔记」，复制粘贴bug（Edge）](https://user-images.githubusercontent.com/98400319/163918425-88730ac5-bafb-4750-ba74-f476cfb6c52e.gif)
手动右键复制粘贴没问题，Ctrl+C/V就会出现 Gif动图的状况。
复制的内容是在另一个文档里的子文档浮窗中复制的。

**Comment by EberhardLin** [comment]
此外本来想在链滴发帖，但现在（2022年4月19日 12:10:51）又上不去链滴了...乏了

**Comment by 88250** [comment]
请在默认主题下测试看看，谢谢。

**Comment by 88250** [comment]
不用试了，默认主题也能重现问题，感谢反馈。

**Comment by EberhardLin** [comment]
> 不用试了，默认主题也能重现问题，感谢反馈。

收到，我没收到github的邮件，登github右上角铃铛也没弹出来消息通知，没注意到您回复我了。
