### ISSUE TITLE
Docker 1.9.9 版本右键总会出现页面卡死的情况

### ISSUE THREAD

**Issue by SleepyOcean** [siyuan-note/siyuan#4637]
### 描述问题 Describe the problem

右键左侧文档树，每次都会出现页面卡死，在等待一分钟左右才会恢复出现右键菜单，每次必现。

### 截屏
<img width="1462" alt="Snipaste_2022-04-19_13-24-55" src="https://user-images.githubusercontent.com/17136535/163926134-2ba9156d-81e5-4e5a-8a9d-517a4fc69d58.png">

**Comment by 88250** [comment]
请在默认主题下进行测试。

**Comment by 88250** [comment]
另外，请看下浏览器版本。

**Comment by 88250** [comment]
先关闭了，如果有补充请随时跟帖，谢谢。
