### ISSUE TITLE
忽略功能没有用

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#4638]
![image](https://user-images.githubusercontent.com/101959415/163941685-bf9d4cf1-546b-46bd-9f17-9a426054ccf7.png)
![Screenshot_20220419_144218](https://user-images.githubusercontent.com/101959415/163941905-f8ff8596-6e9e-439d-ae2e-ef7fbfc72b2a.jpg)

**Comment by 88250** [comment]
忽略文件指的是在云端同步时忽略指定路径下的文件，但是这些文件还是会在本地存在的，所以笔记本依然可以在这个端上使用。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/4639
