### ISSUE TITLE
云端同步忽略文件问题

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#4639]
1.第一张图是电脑端设置的忽略问题文件
2.第二张图是手机端的截图
3.diary文件夹我在电脑端设置了忽略，却依然同步到了手机端
4.我设置了新的同步空间确保手机端不会收到原数据的影响。
![image](https://user-images.githubusercontent.com/101959415/163949931-590d35cb-cf66-48fd-9e53-ed813a262eb8.png)
![Screenshot_20220419_144218](https://user-images.githubusercontent.com/101959415/163949996-c6bcb598-6c20-4d02-9ec1-14665ce9efa6.jpg)

**Comment by 88250** [comment]
手机端这个笔记本可以展开吗？可以到 data 下看看是否有文件同步进来。

**Comment by WolkeAtreide** [comment]
> 手机端这个笔记本可以展开吗？可以到 data 下看看是否有文件同步进来。

内容非常完整。

**Comment by WolkeAtreide** [comment]
> 手机端这个笔记本可以展开吗？可以到 data 下看看是否有文件同步进来。

补充：
先说问题：手机端已存在的笔记本并不会随着电脑端的忽略而自动删除，即使更换同步空间，此笔记本依然不会被删除，建议改进。
这个问题的解决办法：手机端软件删除，重新安装，重新同步。可以说相当繁琐。

**Comment by 88250** [comment]
明白了，手机端切换云端同步目录的话可能会有问题，这个后面再看如何解决，谢谢。

**Comment by WolkeAtreide** [comment]
> 明白了，手机端切换云端同步目录的话可能会有问题，这个后面再看如何解决，谢谢。

客气，思源越好，我用的越舒心

**Comment by WolkeAtreide** [comment]
> 明白了，手机端切换云端同步目录的话可能会有问题，这个后面再看如何解决，谢谢。

不仅仅是切换同步目录，手机端不能自动删除电脑端设置忽略的笔记本这个问题才是重点。

**Comment by 88250** [comment]
有空的话帮忙试下两台桌面端之间能否正常？

**Comment by WolkeAtreide** [comment]
> 有空的话帮忙试下两台桌面端之间能否正常？

不好意思，我这没有第二台电脑。。

**Comment by 88250** [comment]
没事，后面我们再看看，也希望有其他人能试试看。

**Comment by 88250** [comment]
试了下，同步忽略文件的逻辑应该没有问题。

这个问题主要是出在移动端不支持多工作空间切换，移动端现阶段暂时还无法支持多工作空间，先记录 https://github.com/siyuan-note/siyuan/issues/4642

我关闭了，如果有我有理解偏差的地方请直接跟帖反馈，谢谢。

**Comment by WolkeAtreide** [comment]
@88250 好的，我在此补充一下。首先，多空间只是为了测试是否能通过更改空间覆盖删除掉我想忽略的笔记本。
！！！接下来的话题，希望我们二人都不要再提及有关多工作空间切换的任何话题！！！
我这件问题，抛掉后半段切换空间的问题。前半段的重点是，以下步骤：
1. 手机电脑上做好完整同步。：这一步的作用是保证两端数据一致
2. 我在电脑上忽略了一个笔记本**diary**，点击同步。：这一步做完，理论上，被忽略的笔记本**diary**将在云端空间被删除
3. 手机端点击同步。：这一步做完，理论上，笔记本**diary**应该在手机端被删除。
实际上，第三步做完：
1. 手机端笔记本diary未被删除：表示同步失败
2. 电脑端的更新会同步到手机端：表示忽略失败
不知我讲的是否清楚。我已经尽我所能了。还请不要再把话题转移到多空间之类的问题。
！！！！多空间切换只是我用来测试bug的步骤，真正的问题在于单空间同步！！！！

**Comment by 88250** [comment]
这个逻辑是这样的，同步以后的数据本地并不会删除，比如忽略了 xxx，但是这个只能保证后续同步不再同步 xxx，并不能保证已经同步的 xxx 会删除，如果要删除的话，需要在本地手动删除。

这个逻辑和 git 的忽略逻辑是一样的，如果不这样的话，就无法做到忽略了。

**Comment by WolkeAtreide** [comment]
@88250 懂了懂了，我大概了解。
不过我遇到的问题特殊，我遇到的问题是同步依然在忽略之后进行了，所以我当时也不敢删除手机端的数据。
如果你们已经确认后台逻辑没问题，也许这是个个例吧，我就算再在我的账号测试依然是个例。
等等看有没有其他用户提出吧。
以上
