### ISSUE TITLE
剪切板里的图片无法粘贴

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#464]
剪切板里的图片在思源无法粘贴，在Notion可以直接粘贴。（用snipaste截图的图片在剪切板可以在思源粘贴）
![2020 11 10](https://user-images.githubusercontent.com/26304888/98626022-bf10ca00-234b-11eb-8ac4-08613024028f.gif)

**Comment by FastStonewkx** [comment]
你的意思是复制的图片文件不能粘贴到md中。我刚刚试了，确实不能
但是这个可以直接拖动到文件里的

**Comment by nanmao** [comment]
> 你的意思是复制的图片文件不能粘贴到md中。我刚刚试了，确实不能
> 但是这个可以直接拖动到文件里的

在读书摘录的时候，批量写入剪切板粘贴或者配合quicker对选中图片复制自动粘贴到思源，效率高很多的，而且不打断阅读。你想象一下看一下书然后打开思源拖拽一下图片，看一段文字又打开思源拖拽一下图片，看一段文字又打开思源拖拽一下图片...

**Comment by FastStonewkx** [comment]
@88250

**Comment by 88250** [comment]
稍等……我们会尽量解决的，谢谢。

**Comment by nanmao** [comment]
0.4.6已解决.
