### ISSUE TITLE
安装程序提示文案缺陷

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4640]
### 描述问题 Describe the problem

win-x64 安装包在安装时如果遇到待安装目录下文件被占用的问题, 则会提示思源内核未关闭, 实际是被其他程序占用(比如文件资源浏览器 `explorer.exe`), 词不达意, 导致用户无法意识到真正的问题并解决, 进而无法完成安装

### 期待的结果 Expected result

提示安装目录下有文件被占用而非内核未关闭

### 版本环境 Version environment

* Version: 1.9.9
* Operating system: win 10

**Comment by 88250** [comment]
我这里有点重现不了占用的情况，你是怎么做到的？

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里有点重现不了占用的情况，你是怎么做到的？

我也不知道, 我是在资源监视器搜关联的句柄搜出来的, 可能除了 `explorer.exe` 还有其他软件占用😂

**Comment by 88250** [comment]
我这里用其他方式占用以后，安装时不会弹任何报错，只是卡住进度条。

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里用其他方式占用以后，安装时不会弹任何报错，只是卡住进度条。

我也是卡了几分钟才出现对话框

**Comment by 88250** [comment]
之前你是看到这个提示吗？

![image](https://user-images.githubusercontent.com/873584/164130156-8c2bf0a8-9914-43ae-b215-e35e38694370.png)

好像没有说内核未关闭，只是说 SiYuan 无法关闭，这个是打包程序自行判断的。

**Comment by Zuoqiu-Yingyi** [comment]
> 之前你是看到这个提示吗？
> 
> ![image](https://user-images.githubusercontent.com/873584/164130156-8c2bf0a8-9914-43ae-b215-e35e38694370.png)
> 
> 好像没有说内核未关闭，只是说 SiYuan 无法关闭，这个是打包程序自行判断的。

✔

**Comment by 88250** [comment]
好的，那就先这样吧，我关闭了。
