### ISSUE TITLE
设置面板网络代理协议显示错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4641]
### 描述问题 Describe the problem

我在 `v1.9.9` 中设置了 `socks5` 协议网络代理, 升级 `v2.0.0-beta1` 后 <kdb>设置 > 关于 > 网络代理</kbd> 显示当前使用的代理协议为 `http`, 实际依然使用了 `socks5` 协议, 且在控制台中查询 `window.siyuan.config.system.networkProxy.scheme` 字段, 为 `"socks5"`
- 在此时选择 `直接连接` 后单击确认, 重新启动软件后切换为了 `直接连接`, 设置中也显示当前使用了 `直接连接`, `siyuan.config.system.networkProxy.scheme` 字段也为 `""`
- 在此时选择 `http` 后单击确认, 重新启动软件后代理协议切换为了 `http`, 设置中也显示当前使用 `http`, `siyuan.config.system.networkProxy.scheme` 字段也为 `"http"`
- 在此时选择 `socks5` 后单击确认, 重新启动软件后代理协议切换为了 `socks5`, `siyuan.config.system.networkProxy.scheme` 字段也为 `"socks5"`, 但设置中依然显示 `http` 协议

### 期待的结果 Expected result

设置 > 关于 > 网络代理 下拉选项卡中默认显示的内容为当前使用的代理协议

### 版本环境 Version environment

* Version: 2.0.0-beta1
* Operating system: win 10
* Browser (if used):

**Comment by 88250** [comment]
感谢反馈，下个版本修复。
