### ISSUE TITLE
拖动窗口分屏出现多屏无法恢复的情况

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#4646]
![image](https://user-images.githubusercontent.com/98400319/164018068-f5fabe0e-12b6-408a-882a-840c95e1173e.png)
很离谱，具体操作步骤我现在也没法复现（打不开文档了），大致就是打开了三个文档窗口、一个PDF窗口，三个文档窗口在左屏，PDF窗口在右屏（思源笔记内的分屏）。
下图为打不开文档界面：
![image](https://user-images.githubusercontent.com/98400319/164018661-d8ff8d75-b12c-4100-9cf8-1c0815ca939d.png)
将左侧三个文档窗口中的中间文档，拖动移到左屏下方，即“吕口”式分屏，结果BUG出现了：并没有变成“吕口”式分屏，而是变成了“口口口”三个分屏，并且中间的屏幕是图中灰色区域的部分，然后我就害怕了，尝试打开大纲栏又关闭，结果大纲栏的位置又留下了一个分屏，即：
![image](https://user-images.githubusercontent.com/98400319/164019369-df6309e7-aef4-46ab-98d3-40bc27d2a5e4.png)
关闭所有文档窗口后，就留下了一堆分屏。之后我的操作是：
1. 关闭所有文档窗口后，重建索引——没有任何变化，依旧是留下了四个分屏。
2. 在勾选了“退出界面时关闭内核”的情况，关闭思源再重启，但依旧没有恢复。
第一次碰见该情况，请问如何解决？

**Comment by 88250** [comment]
设置 - 外观 - 恢复默认窗口

恢复以后麻烦再试试能否重现，如果能的话请跟帖重现步骤，谢谢。
