### ISSUE TITLE
希望能增加下载渠道

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#4650]
2.0开始，不知为何，在论坛上没看到帖子，似乎只能从github上下载？
![image](https://user-images.githubusercontent.com/101959415/164187821-a9fa0169-7080-4d21-b304-452ecd614ea6.png)
问题在于，github下载频频出现如下图的情况，目前还在下，已经重复下载四五次了。是否有其他能够下载2.0的渠道呢？
![image](https://user-images.githubusercontent.com/101959415/164187460-3575ee9e-cf53-45fa-95d5-fa9a9c580410.png)

**Comment by WolkeAtreide** [comment]
部分记录，最新这个的网速应该也会失败。
![image](https://user-images.githubusercontent.com/101959415/164192001-8c5610fa-5d4d-44b1-b41b-f4a7dad9556f.png)

**Comment by 88250** [comment]
beta 版本暂时没有在官网发布，等后面正式版会在官网发布的，感谢反馈。

**Comment by WolkeAtreide** [comment]
> beta 版本暂时没有在官网发布，等后面正式版会在官网发布的，感谢反馈。

怪不得，我找群里的伙计给我发了一份。
github就离谱，
![image](https://user-images.githubusercontent.com/101959415/164358405-8577a689-136c-4dc9-8fd1-73279c9c8578.png)

**Comment by 88250** [comment]
GitHub 下载可以试试 https://ghproxy.com/

**Comment by WolkeAtreide** [comment]
> GitHub 下载可以试试 https://ghproxy.com/

不错不错不错，多谢!!
