### ISSUE TITLE
文档树支持管理其他资源文件

### ISSUE THREAD

**Issue by chiuchiuuu** [siyuan-note/siyuan#4652]
### 在什么情况下你需要该特性？ In what scenarios do you need this function?

当我们需要对附件进行管理的时候。

随着插入的附件（pdf，word，ppt）等越来越多，附件越来越难管理，例如

1. 这些附件只能通过插入引用的方法保存到 asset 文件夹中，散落在笔记的各个地方，无法自行组织分类
2. 如果引用的文字被删除，然后设置中清理未引用资源的话会把附件给删掉
3. asset 文件夹在文档树中不可见，无法直接浏览附件，现在siyuan已经支持浏览pdf，如果能在文档树直接点开pdf会很方便
4. 附件没有属性，无法通过自定义sql之类的搜索
5. 插入的附件不方便修改名字

### 描述可能的最优解决方案 Describe the optimal solution

我的建议是，能否将这些附件作为siyuan的一个“文档”进行处理，可以自行插入到文档树进行组织，可以定义属性方便管理。

可以参考obsidian，其实就是把附件单独作为一个“文档”

**Comment by 88250** [comment]
你好，如果实在需要搜索，可以考虑通过 SQL 接口搜索 assets 表。未来我们也期待有这方面的挂件支持作为补充。

对于思源本身的设计来说，我们认为管理链接比管理文件本身更有效，试想一大堆资源文件出现在文档树上，其实根本也无法管理和组织分类。

资源文件重命名请关注 https://github.com/siyuan-note/siyuan/issues/3454

我们关闭了，感谢反馈，如果需要继续交流随时跟帖即可，谢谢。

**Comment by chiuchiuuu** [comment]
可能我标题起的不太好，我并不是单纯想让资源文件能够在文档树显示。我的核心观点是让资源文件成为一个”文档“，我想谈论的资源文件并不包含插入的大量图片，而是指pdf，word之类的，比如论文，研究报告这类资源文件，我觉得是需要作为一个“文档”去管理的。例如我可能需要在不同地方引用同一个资源文件，可能需要看资源文件被哪些地方引用了。

此外我不认同这句话：

> 对于思源本身的设计来说，我们认为管理链接比管理文件本身更有效，试想一大堆资源文件出现在文档树上，其实根本也无法管理和组织分类。

如果资源文件本身就作为一个“文档”了，那它和其他文档有什么不同？……你说这句话就像在说 “一大堆文档出现在文档树上，其实根本也无法管理和组织分类”。

而且对于一些类别特别清晰的笔记，文档树确实就是一种优秀的组织方式。就好比我们会把工作，日记，读书笔记放在不同的文档树下，那我把论文，研究报告，书籍等不同的资源文件放在文档树中组织不是也很合理吗

> 资源文件重命名请关注 https://github.com/siyuan-note/siyuan/issues/3454

这个貌似四个月过去了也没什么进展，如果把资源当做一个“文档”处理了，那修改名字同时修改所有引用链接就很简单了。

**Comment by 88250** [comment]
正是因为文档树这样的分类方式存在缺陷，所以才有了双链日记的用法。

如果实在要管理资源文件，建议用类似 MoC 的方式管理。

**Comment by fanglypro** [comment]
[MOC - 管理链接而非本体](https://www.yuque.com/deerain/gannbs/hb0gsd)

**Comment by chiuchiuuu** [comment]
我已经找到一种 workaround 了，给每个资源文件单独建立一个页面就好了，这样方便引用和改名。

> 正是因为文档树这样的分类方式存在缺陷，所以才有了双链日记的用法。

另外我不明白你为什么这么纠结文档树的缺陷，我没有否认文档树的缺陷，我说了文档树是双链的一个子集，在某些场景下就是需要文档树，不然siyuan为什么不直接取消文档树？siyuan的用户指南为什么还要通过文档树的形式来组织？

**Comment by chiuchiuuu** [comment]
> MOC理念：[MOC - 管理链接而非本体](https://www.yuque.com/deerain/gannbs/hb0gsd)
> 
> 如果想要把某个资源文件当成文档块管理，也就是想看这个资源文件的反链等，可以新建一个文档，把资源文件拖动到这个文档中，想引用这个资源文件时，引用这个文档
> 
> 此外，思源里面的文档和传统意义上的文档有区别，思源里的文档是一个块，文档里面的段落也是一个块，所有内容都是块

我知道文档的本质是块，你可以把我的意思理解成把资源文件当作一个块。

你说的这个引用方法确实不错，我现在就是这么解决的。

**Comment by fanglypro** [comment]
> > MOC理念：[MOC - 管理链接而非本体](https://www.yuque.com/deerain/gannbs/hb0gsd)
> > 如果想要把某个资源文件当成文档块管理，也就是想看这个资源文件的反链等，可以新建一个文档，把资源文件拖动到这个文档中，想引用这个资源文件时，引用这个文档
> > 此外，思源里面的文档和传统意义上的文档有区别，思源里的文档是一个块，文档里面的段落也是一个块，所有内容都是块
> 
> 我知道文档的本质是“块”，但他们在前端交互上有区别，我理解的文档就是在文档树可以展示的“块”。你可以把我的意思理解成“把资源文件当作一个块”
> 
> 你说的这个引用方法确实不错，我现在就是这么解决的。

正因为如此，文档并不是传统文档，文档上附有各种块相关的元信息例如id和属性，所以如果要把资源也作为块的话，需要给资源文件加上这些元信息，而资源文件作为思源的外部文件，在技术上给外部文件加入这些元信息会非常困难。

此外，文档作为块，和列表项块等价，因此，使用列表组织文档和文档树等价，甚至还可以实现比列表更丰富的组织形式，参照[MOC - 管理链接而非本体](https://www.yuque.com/deerain/gannbs/hb0gsd)，而且目前的大部分双链笔记软件是没有文档树的，思源为了兼顾传统方法和双链方法以及一些历史包袱，还有文档树的存在。思源支持文档树，也不会排斥用户使用文档树，但在双链笔记时代还是有一些不一样的笔记理念，比如 MOC，可以参考这些理念尝试优化笔记系统。
