### ISSUE TITLE
拖拽/删除后形成超级块下仅有一个块时，取消该超级块

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4653]
https://ld246.com/article/1650496564994

**Comment by Zuoqiu-Yingyi** [comment]
有时候只有一个下级块的超级块是个编辑的中间状态, 比如有时需要将两个块合并后再拆分, 这时候就十分不方便了, 希望能取消该特性~
毕竟其他容器块都支持只存在一个下级块
