### ISSUE TITLE
bug##粘贴文本会出现奇怪的源文件json

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4657]
# 先看录屏

https://user-images.githubusercontent.com/66512309/164393102-3ffdc96a-deff-4c22-a2df-6b1b6aa77c34.mp4

这样会多出一会类似json的东西，是思源源文件里的信息好像

删掉就提示重建索引了

**Comment by 88250** [comment]
麻烦上传一下这个文本文件，如果不方便分享到公网的话可以发到邮箱 845765@qq.com

**Comment by Faith-YSQ** [comment]
[JavaScript基础第03天笔记.md](https://github.com/siyuan-note/siyuan/files/8528501/JavaScript.03.md)

**Comment by Temacc0531** [comment]
我上次浏览之前记录的文章时也发现代码块里面出现了这个类似块id的东西，不知道是什么时候被加上去的，手动删除之后，后续就没法复现了

**Comment by 88250** [comment]
@Temacc0531 之前有个版本的 bug，后面修复了。

**Comment by 88250** [comment]
@Faith-YSQ 用 Ctrl+Shift+V 粘贴或者复制包含 ` ``` ` 的代码块要闭合。

这个问题是因为富文本粘贴时代码块里面包含了 ` ``` ` 导致解析器触 bug，这个问题暂时无法改进，先关闭了，感谢反馈。
