### ISSUE TITLE
Docker 版丢失图片

### ISSUE THREAD

**Issue by JCJC01** [siyuan-note/siyuan#4660]
### 描述问题 Describe the problem
部署docker后，手机登录网页，文档中插入手机里面的图片，显示上传完之后图片不在文档中显示，又或者显示在文档里面显示了，刷新一下之后无法保存，直接丢失。但是插入视频的时候没有丢失问题。
目前是docker版本是2.0公测版，之前的1.99版也有这个问题

**Comment by 88250** [comment]
请看一下文件系统上是否还存在，并单独访问一下资源文件 URL 看看是否能显示。

**Comment by firstuanl** [comment]
1.9.6也有这个问题，直接从firefox拖进去，有显示，但在文件系统上存在或不存在（都有见过），浏览器刷新就不见了。

**Comment by firstuanl** [comment]
如果浏览器能直接贴图更好。

**Comment by JCJC01** [comment]
不懂哪里看url
直接调用相机拍照也会刷新后丢失，或传不成功，但是拍视频就没试过丢失和传不成功

**Comment by 88250** [comment]
@JCJC01 Docker 挂载的卷工作空间/data/assets/ 文件夹下看下是否插入成功
@firstuanl 试试其他浏览器，火狐基本没有做兼容性，可能是这个问题

**Comment by JCJC01** [comment]
看到了，assets里面有文件的。
我用edge和chrome都出现这个情况
但是目前用小米自带浏览器试用了几次，暂时没有发现

**Comment by 88250** [comment]
暂时还不确定问题，继续保持 issue 打开状态。

**Comment by JCJC01** [comment]
你好，几天的使用，确认了edge chrome，系统自带的小米，和safia都有丢失图片和上传后无法显示或刷新后丢失的情况，但是视频没有这种情况，请帮忙

**Comment by 88250** [comment]
请再试下使用桌面端伺服会不会出现该问题。

**Comment by 88250** [comment]
用桌面伺服，然后手机访问也是丢失吗？

**Comment by 88250** [comment]
先关闭了，如果有补充请随时跟帖，谢谢。
