### ISSUE TITLE
启动插画界面加载不出来

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4662]
![Video_20220422105712](https://user-images.githubusercontent.com/66512309/164588049-78714b6c-8cff-4cf0-a208-bd52406238ac.gif)
显示的是错误是images/

**Comment by Faith-YSQ** [comment]
<img width="256" alt="Snipaste_2022-04-22_11-06-21" src="https://user-images.githubusercontent.com/66512309/164588428-1ac56789-0a51-4817-85a8-0d8b7d91e1f1.png">

**Comment by 88250** [comment]
有开全局网络代理吗？

**Comment by Faith-YSQ** [comment]
没有，不过如果网络问题的话，有的时候官网要刷几遍才能进去

**Comment by 88250** [comment]
本地杀毒软件和防火墙加一下思源白名单看看。

官网的暂时就那样了。

**Comment by Faith-YSQ** [comment]
应该不是这两个的问题，我电脑很简单，用的火绒，用思源也没有弹出过防火墙提示，刚刚加了一下白名单，也没有恢复

**Comment by 88250** [comment]
任务管理器里看下是不是内核进程 SiYuan Kernel 还在？

**Comment by Faith-YSQ** [comment]
在

**Comment by 88250** [comment]
退出界面以后手动结束内核进程然后重启看看。

**Comment by Faith-YSQ** [comment]
退出界面任务管理器进程完全推出了，重启问题还在

**Comment by 88250** [comment]
发下日志文件吧。

**Comment by Faith-YSQ** [comment]
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8536585/siyuan.log)

**Comment by 88250** [comment]
用 Ctrl+Shift+I 打开开发者工具，然后 Ctrl+R 刷新看看。

**Comment by Faith-YSQ** [comment]
刷新了，然后重启，初始界面还是这个状况，出不来

**Comment by 88250** [comment]
截图看下开发者工具的 Console 和 Network

**Comment by Faith-YSQ** [comment]
<img width="900" alt="Snipaste_2022-04-22_11-29-25" src="https://user-images.githubusercontent.com/66512309/164590691-52ee2356-e69d-4284-bb74-1ed8106771f7.png">
<img width="900" alt="Snipaste_2022-04-22_11-30-06" src="https://user-images.githubusercontent.com/66512309/164590696-e1d5320a-721d-4b85-9be9-632157ef2bf5.png">

**Comment by 88250** [comment]
咦，你不是进去了吗？

**Comment by Faith-YSQ** [comment]
我说的是进入时的加载页面，以前不是有一个预加载那个界面吗？现在这个界面没有了，左上角多了个images/

**Comment by Faith-YSQ** [comment]
第一张图我就进去了，一直进得去

**Comment by 88250** [comment]
你说的是那个启动的插画界面？

**Comment by Faith-YSQ** [comment]
对

**Comment by 88250** [comment]
很有可能是因为安装不完整，重新安装试试。

**Comment by Faith-YSQ** [comment]
安装了两次，有一次是卸载原来版本重新装的

**Comment by 88250** [comment]
启动以后试下浏览器访问 http://127.0.0.1:6806/appearance/boot/index.html

**Comment by Faith-YSQ** [comment]
闪了一下插画界面

**Comment by 88250** [comment]
那说明安装应该没问题，资源文件是齐全的。

但是为啥你那里启动时加载不出来，我们也暂时没有收到类似反馈，感觉可能还是系统环境有影响，要不重启系统看看 😂

**Comment by Faith-YSQ** [comment]
好的好的

**Comment by Faith-YSQ** [comment]
试过了，重启不行，我还是暂时用回1.9.9吧，还好对云端收集箱没需求😂，就是想更新个版本

**Comment by Faith-YSQ** [comment]
**D大，我找到原因了，可能是我电脑上之前用less安装了nodejs的原因，我卸载了之后所有版本就没问题了，插画就出来了了😂😂😂**

**Comment by Faith-YSQ** [comment]
还有我还删除了一个出现在appdata里面的思源config文件夹

**Comment by 88250** [comment]
好的，那先这样吧，以后如果有人碰到类似问题我们就引用到此。
