### ISSUE TITLE
最新版---白屏

### ISSUE THREAD

**Issue by FastStonewkx** [siyuan-note/siyuan#467]
![image](https://user-images.githubusercontent.com/36177654/98650279-a61c0f00-2373-11eb-9f0a-0b25edabbc27.png)
下载的是最新解压版版，启动白屏。

第一次安装，没有在C盘

还是说第一次必须使用安装版

**Comment by 88250** [comment]
你好，请稍后下载 v0.4.32 再试，谢谢。

**Comment by FastStonewkx** [comment]
啥时候呢？

**Comment by 88250** [comment]
还在上传 GitHub，有点慢……方便的话可以加 Q 群 724713327，群里已经上传好了。

**Comment by FastStonewkx** [comment]
还是白屏，好吧！有时间试试安装版

**Comment by 88250** [comment]
v0.4.32 还是白屏吗？麻烦贴下 ~/.siyuan/siyuan.log

**Comment by FastStonewkx** [comment]
____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2020/11/10 20:22:39 log.go:65: kernel [v0.4.32] is booting, runtime mode is [prod], working directory is [G:\pcfunny\siyuanNote\resources], temp directory is [C:\Users\root\AppData\Local\Temp\siyuan], read only [false]
I 2020/11/10 20:22:39 lang.go:62: initialized languages
D 2020/11/10 20:22:39 conf.go:107: loaded conf [C:\Users\root\.siyuan\conf.json]
I 2020/11/10 20:22:39 conf.go:220: local serve path [http://192.168.0.111:6806]
I 2020/11/10 20:22:39 conf.go:231: initialized conf
I 2020/11/10 20:22:39 appearance.go:44: initialized appearance
I 2020/11/10 20:22:39 main.go:115: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2020/11/10 20:22:39 main.go:117: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2020/11/10 20:24:21 log.go:64: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2020/11/10 20:24:21 log.go:65: kernel [v0.4.32] is booting, runtime mode is [prod], working directory is [G:\pcfunny\siyuanNote\resources], temp directory is [C:\Users\root\AppData\Local\Temp\siyuan], read only [false]
I 2020/11/10 20:24:21 lang.go:62: initialized languages
D 2020/11/10 20:24:21 conf.go:107: loaded conf [C:\Users\root\.siyuan\conf.json]
I 2020/11/10 20:24:21 conf.go:220: local serve path [http://192.168.0.111:6806]
I 2020/11/10 20:24:21 conf.go:231: initialized conf
I 2020/11/10 20:24:21 appearance.go:44: initialized appearance
I 2020/11/10 20:24:21 main.go:115: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2020/11/10 20:24:21 main.go:117: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
I 2020/11/10 20:30:22 log.go:64: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2020/11/10 20:30:22 log.go:65: kernel [v0.4.32] is booting, runtime mode is [prod], working directory is [C:\Users\root\AppData\Local\Programs\siyuanNote\resources], temp directory is [C:\Users\root\AppData\Local\Temp\siyuan], read only [false]
I 2020/11/10 20:30:22 lang.go:62: initialized languages
D 2020/11/10 20:30:22 conf.go:107: loaded conf [C:\Users\root\.siyuan\conf.json]
I 2020/11/10 20:30:22 conf.go:220: local serve path [http://192.168.0.111:6806]
I 2020/11/10 20:30:22 conf.go:231: initialized conf
I 2020/11/10 20:30:22 appearance.go:44: initialized appearance
I 2020/11/10 20:30:22 main.go:115: kernel HTTP server is booting [http://0.0.0.0:6806]
F 2020/11/10 20:30:22 main.go:117: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by FastStonewkx** [comment]
![image](https://user-images.githubusercontent.com/36177654/98674917-79c4ba80-2394-11eb-9d64-23e413766ab6.png)

**Comment by 88250** [comment]
思源需要监听 6806 和 6807 两个端口。

**Comment by FastStonewkx** [comment]
![image](https://user-images.githubusercontent.com/36177654/98677510-0e7ce780-2398-11eb-91be-5e9ac8c31e87.png)

**Comment by FastStonewkx** [comment]
![image](https://user-images.githubusercontent.com/36177654/98678278-45073200-2399-11eb-8947-ea853920976f.png)
启动的时候就这两个进程
关闭后
![image](https://user-images.githubusercontent.com/36177654/98678335-59e3c580-2399-11eb-9fdd-f1f8d240979d.png)
然后6807没有找到占用

**Comment by FastStonewkx** [comment]
我试试安装版

**Comment by 88250** [comment]
> F 2020/11/10 20:30:22 main.go:117: boot kernel HTTP server failed: listen tcp 0.0.0.0:6806: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

从这句日志上看是因为没有权限，用管理员运行试试？

**Comment by FastStonewkx** [comment]
已经好了，我重启电脑。可以打开了


但是应该不是端口问题
![image](https://user-images.githubusercontent.com/36177654/98681090-40dd1380-239d-11eb-8566-60adb37efaff.png)


也许是我打开软件太多了，冲突了。还是非常感谢。

**Comment by FastStonewkx** [comment]
![image](https://user-images.githubusercontent.com/36177654/98681837-26576a00-239e-11eb-8622-51adcc3480aa.png)

**Comment by 88250** [comment]
好的，能用就行。

**Comment by FastStonewkx** [comment]
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5517684/siyuan.log)

**Comment by FastStonewkx** [comment]
感谢
