### ISSUE TITLE
有没有API可以获取到手动排序的笔记顺序

### ISSUE THREAD

**Issue by zxcvbnmzsedr** [siyuan-note/siyuan#4670]
目前在整一个通过从思源笔记导出生成思维导图的功能，但是由于没有办法获取到手动排序之后的笔记本顺序，导致生成的思维导图的节点顺序也是错误的

我目前是通过下面这个SQL，通过parent_id来生成树状结构

`select *
from blocks
where box = '20220420112442-p6q6e8w'
  and (type = 'h' or type = 'd')
  and hpath like '/topic/Java并发工具包%'
`

最后出来的结果：

笔记的顺序是这样的
<img width="389" alt="image" src="https://user-images.githubusercontent.com/14026790/164736433-883dcba0-6b14-4fe8-9157-d59bb3158c7d.png">

生成出来就是这样的
<img width="655" alt="image" src="https://user-images.githubusercontent.com/14026790/164736657-1b49b294-5489-4263-bb3a-c4ff8270d572.png">

**Comment by 88250** [comment]
文档排序值是存储在笔记本/.siyuan/sort.json 中的，可以试试用 [获取文件 API](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E8%8E%B7%E5%8F%96%E6%96%87%E4%BB%B6) 读取这个排序文件。

**Comment by zxcvbnmzsedr** [comment]
谢谢，已经可以拿到这个排序信息了，完美

**Comment by zxcvbnmzsedr** [comment]
调用api成功了

但是，我在软件上重新拖动了一下进行排序，再调用接口的时候，就返回了409

日志显示文件被占用

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/14026790/164873347-801a4017-a8ce-4e7f-a0d6-4ed09904ebf8.png">

**Comment by zxcvbnmzsedr** [comment]
我刚刚又尝试了一下，只要我拖动过，这个sort.json就会被锁定🔒

这种情况该如何处理

**Comment by 88250** [comment]
我们在 https://github.com/siyuan-note/siyuan/issues/4674 中处理，感谢反馈。
