### ISSUE TITLE
搜狗输入法划选输入中文再撤销触发状态异常

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#4672]
![A](https://user-images.githubusercontent.com/38906705/164844393-2e567eaf-9d1d-4fc0-8574-1f84640db5f4.gif)

**Comment by Vanessa219** [comment]
无法重现，你的输入法和操作系统是？

**Comment by royc01** [comment]
是搜狗和win10，但是我这边突然复现不了了，我先找个稳定复现的方法

**Comment by royc01** [comment]
![B](https://user-images.githubusercontent.com/38906705/164882420-fe808f35-3926-4c18-865e-53b2a0db3af5.gif)
子项按Tab缩进，然后父项框选输入中文再撤销

**Comment by 88250** [comment]
我这里也是重现不了。

**Comment by royc01** [comment]
![C](https://user-images.githubusercontent.com/38906705/165010392-f4c087b4-cc66-44d4-93b6-1cbbcb27cf64.gif)
我完整录一遍，要不行也没办法了

**Comment by tmkddskf** [comment]
我也可以重现，方法和他一样！

**Comment by royc01** [comment]
我这边测试了一波，搜狗输入法才会出现，微软输入法没问题

**Comment by 88250** [comment]
我这里是搜狗输入法，暂时还是重现不了。
![image](https://user-images.githubusercontent.com/873584/165109961-b35df0d3-a01c-4fe3-a73a-f025ee31b6e6.png)

**Comment by royc01** [comment]
那就没办法了，我这边搜狗更新到最新版了，而且win10、win11都测试过，都会复现这个问题，群里问了只有几位老哥可以复现，出现得有点随机，找不出原因我暂时用微软输入法吧。。。

**Comment by royc01** [comment]
![111](https://user-images.githubusercontent.com/38906705/165198327-1e88846c-67e8-471a-b996-d9fb7866cb5c.gif)
麻了。。现在只要下方有块上面划选输入中文都会异常

**Comment by 88250** [comment]
已经能够重现，感谢感谢。
