### ISSUE TITLE
长页面显示问题

### ISSUE THREAD

**Issue by jipeng0918** [siyuan-note/siyuan#4673]
页面里面内容很长的时候，打开页面只显示了一部分，需要拉到最底下才多显示一些，然后再往下拉继续显示。。。要操作下滑或者下拉好几遍。

可不可以页面打开全部显示，不用下滑才显示后面内容

**Comment by 88250** [comment]
这个是动态加载的特性，避免大文档卡顿。

**Comment by 88250** [comment]
如果要直接跳转到末尾的话，可以用 Ctrl+End
