### ISSUE TITLE
API鉴权错误

### ISSUE THREAD

**Issue by zxcvbnmzsedr** [siyuan-note/siyuan#4675]
在调用API的时候，发现API token在发起请求时不设置也能成功拿到数据

如果设置了访问鉴权码，则在调用API的时候则会抛出错误

所以，目前是不是只有鉴权码是有效果的，而API token是无效的？

**Comment by 88250** [comment]
设置 `Authorization` 请求标头的情况下会优先校验这个标头，然后才校验访问鉴权码。

你发一下标头看下。

**Comment by zxcvbnmzsedr** [comment]
哦哦，不好意思，我的网络工具把我自定义的Header给吃掉了。。是没问题的
