### ISSUE TITLE
关于渲染模板API的疑问

### ISSUE THREAD

**Issue by zxcvbnmzsedr** [siyuan-note/siyuan#4676]
这个 /api/template/render ，是用来做什么用的？文档上面没有具体的说明，出入参都没有写

目前好像没有API可以获取到block渲染之后的html

**Comment by 88250** [comment]
这个 API 目前还不确定是否有必要提供给开发者，传参的话可以在思源中看下 `/模板` 选择模板后的调用。

> 目前好像没有API可以获取到block渲染之后的html

使用场景是？

**Comment by 88250** [comment]
先关闭，暂时作为讨论帖，谢谢。

**Comment by zxcvbnmzsedr** [comment]
使用场景是想通过思源笔记，生成博客。

目前是通过`api/export/exportMdContent`那个接口将笔记当成markdown来进行渲染。

这就导致生成出来的效果，和笔记中写的效果有较大差异，所以就想着能不能有个接口哪到渲染之后的html

**Comment by zxcvbnmzsedr** [comment]
然后OceanPress这个项目我也看了，是通过解析原始文件来生成html的。

感觉不是很优雅，要有笔记有新特性出来，就可能需要修改生成的方式。

或者说，Vditor能够兼容思源的sy文件也可以。。😍😍

**Comment by 88250** [comment]
OceanPress 的方式应该是没问题的，通过 Protyle 和 Lute 做解析生成，思源底层也是用的这两个库。

**Comment by zxcvbnmzsedr** [comment]
因为我是通过GATSBY这个来实现的，将思源的API包装成graphQL，如果有现成的API，实现起来就简单很多。

要是没有就只能通过Lute去尝试一下了😅

**Comment by 88250** [comment]
获得 data 以后要调用插入块的 API 插入。

**Comment by leommjj** [comment]
渲染模板的api使用的是模板绝对路径，这在ios端会出现读取错误
