### ISSUE TITLE
Excel 读写

### ISSUE THREAD

**Issue by vanxuing** [siyuan-note/siyuan#4677]
这是21年有人提及的一个问题，我只是最近用到这个功能，查询到以前有朋友提交到了这个问题。
https://github.com/siyuan-note/siyuan/issues/1038#issue-784728168
400多天过去了，我是觉得可以从新考虑这个问题了。

### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

情景1
excel记账
当excel添加或者修改数据后,汇总界面的对应位置金额数据 被思源读取,展现在某些位置
模版或者报表

情景2
结合excel和文档的笔记需求
例如一份excel的接口文档 每个接口都在一个页面
思源在引入对应页面的数据
放到文档中
达到文本表格混排 同时自动更新的目的

情景3
excel插件化
思源本身的计算函数功能不够强大
如果在excel中使用excel自身的函数进行计算,再引入到思源中展示

相当于另一种意义上的插件
只是这个插件本身是excel及其对应的全部生态

可以描述为
打开excel插件 excel计算数据 组合数据 思源更新展示数据
### 描述候选的解决方案 Describe the candidate solution
插件化

**Comment by 88250** [comment]
现在已经有挂件机制了，但是得靠社区开发者贡献。

**Comment by zsxsoft** [comment]
如果你用的是Docker版本，可以用OnlyOffice集成 https://github.com/zsxsoft/onlyoffice-siyuan
