### ISSUE TITLE
在设置了图片宽度后，选择「复制到语雀」，复制后图片大小仍为原状

### ISSUE THREAD

**Issue by jiangbaiyan** [siyuan-note/siyuan#4679]
操作路径：
1. 图片右键 -> 宽度50% -> 复制到语雀 -> 把md原文复制进去
最终复制后的显示效果仍然是图片大小100%，并没有为设置的50%

**Comment by 88250** [comment]
Markdown 没有指定图片大小的语法，所以应该无法支持。

**Comment by jiangbaiyan** [comment]
> Markdown 没有指定图片大小的语法，所以应该无法支持。

使用img标签应该可以吧

**Comment by 88250** [comment]
语雀估计不支持 HTML 标签。

**Comment by jiangbaiyan** [comment]
> 语雀估计不支持 HTML 标签。

嗯，我看只有这个复制后是原生的md语法，其实目标的平台不一定是语雀，任意一个支持md的平台都可以

**Comment by 88250** [comment]
理论上是这样的，复制到语雀走的是 Markdown，因为语雀对 Markdown 支持很好。

**Comment by jiangbaiyan** [comment]
嗯嗯，可以评估下是否支持，大多数md的写作平台应该都是支持img标签的
