### ISSUE TITLE
是否能记忆页面位置

### ISSUE THREAD

**Issue by jipeng0918** [siyuan-note/siyuan#4683]
页面关闭、软件关闭是否能记忆页面浏览位置，重新打开页面后自动定位到上一次关闭时的位置。
比如我浏览某个页面到第二页，重新打开后显示第二页。

**Comment by jipeng0918** [comment]
就像阅读微信公众号文章，再次进入后，自动进入到上次浏览位置。

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/4042
