### ISSUE TITLE
undo和redo操作确定性优化

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#4684]
这个问题应该是不用描述啥场景的，ctrl+z进行undo操作的确定性非常让人疑惑，你不知道能不能撤销成功，撤销后的效果，甚至多按几次ctrl+z后就崩溃重建索引，个人觉得这个是最基本且最常用到的操作，操作所带来的确定性和稳定性也需要保证，否则光这一点就能让大家心里没底。建议能尽快优化此功能，谢谢。

**Comment by 88250** [comment]
麻烦帮忙找到触发状态异常的重现步骤。

**Comment by 88250** [comment]
先关闭了，欢迎随时补充细节，谢谢。

**Comment by whuwangyong** [comment]
我补个图吧。

注意我Ctrl Z、Ctrl Y 时操作的是文档A，但是文档B里面的块的内容变了。
另外：图中演示虽然aaa拖下去与bbb组成了超级块，但是，与超级块无关。即使放在bbb的下面，也会一样的效果。
再另外：这个步骤可能会导致状态异常。

![混乱的撤销](https://user-images.githubusercontent.com/5968678/167914195-28e1677c-8087-47f4-9dc2-74e4ba14049f.gif)
