### ISSUE TITLE
新的数据同步实现

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4687]
### 用户迁移方案

* 提供新的同步方式供用户选择
  * 选择新方式以后当前设备的本地数据会被全量上传一次
  * 其他设备上也选择新方式后完成数据迁移
* 新旧同步方式并行一段时间，云端同时提供新旧两种同步实现，但是数据不互通，所有设备上必须使用同一种同步方式

**Comment by deerainw** [comment]
“请查看帮助文档 - 云端 - 数据同步”

**Comment by EberhardLin** [comment]
是否有人知道新同步方案与旧同步方案有何区别？纯好奇想了解下

**Comment by 88250** [comment]
@EberhardLin 节省流量，性能好。
