### ISSUE TITLE
块引搜索默认使用双引号包裹

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4689]
也就是说不支持复杂查询语法，将输入强行转换为字符串短语。

**Comment by mozhux** [comment]
不能吧，这样很难模糊搜索呀。。主要是因为符号给挡住了，现在基本上是要每个符号加引号才能模糊搜索。如果是强行转化为字符串，那是要很精确的才能搜索了吧。手工添加整个引号的时候就是很精确才行。

**Comment by 88250** [comment]
@mozhux 块引搜索主要是要方便，大多时候应该不会有需要使用查询语法的情况出现，如果要用查询语法，就用全局搜索。
