### ISSUE TITLE
`块引新建文档存放位置` 支持模板变量

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4693]
https://ld246.com/article/1650800491094

**Comment by whuwangyong** [comment]
正好需要，一搜果然有！

**Comment by winter60** [comment]
非常感谢这个功能，但有点疑惑块引新建和ctrl+n新建是路径现在是分开的，是这样设计的吗？

**Comment by Vanessa219** [comment]
是的， `Ctrl+N` 是根据当前环境决定新建位置，没有打开文档的时候也可以新建。
