### ISSUE TITLE
外部修改已有资源文件后纳入云端同步

### ISSUE THREAD

**Issue by gslnzfq** [siyuan-note/siyuan#4694]
### 描述问题 Describe the problem

1. 在笔记里面插入一个xmind文件，同步到云端（成功）。
2. 修改xmind文件，点击同步，提示“本地数据暂无变更”，另外一台电脑查看，还是修改前的xmind文件。

### 期待的结果 Expected result

修改笔记中关联的文件后，可以同步到云端，并且在其他的电脑正常查看。

### 版本环境 Version environment

* Version:  2.0.0
* Operating system: macOS 12.3.1 
* Browser (if used): 无

**Comment by 88250** [comment]
是的，目前需要再修改一下任意文档才能触发同步。

* https://ld246.com/article/1650458217225
* https://ld246.com/article/1649995325773

这个问题暂时不做调整，后续再考虑改进，感谢反馈。

**Comment by 88250** [comment]
v2.0.3 会加入改进，但是仅支持 `工作空间/data/assets/*` 这一层的资源文件外部变更同步。
