### ISSUE TITLE
桌面端支持导出完整 data 文件夹 zip 压缩包 

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4696]
设置 - 关于 - 导出 Data

**Comment by Zuoqiu-Yingyi** [comment]
希望 Web 桌面端(`http(s)://host:port/stage/build/desktop/`)也支持导出完整 data 文件夹 zip 压缩包, 毕竟 Web 移动端(`http(s)://host:port/stage/build/mobile/`)是支持的😂

**Comment by 88250** [comment]
好的，下个版本支持。
