### ISSUE TITLE
类似notion的看板视图，可以做项目计划。

### ISSUE THREAD

**Issue by seekertang** [siyuan-note/siyuan#4707]

**Comment by 88250** [comment]
请参考 https://ld246.com/article/1644907839875

**Comment by seekertang** [comment]
我说的不是database，这个目前可以使用插件实现。而是类似 jira的看板。
比如有多个分栏，未开始，正在进行，已完成。

**Comment by 88250** [comment]
这个手动用超级块分栏应该就能做，好像集市里面有模板，可以找找看。
