### ISSUE TITLE
当表格在无序列表中时编辑有问题

### ISSUE THREAD

**Issue by liuy0267** [siyuan-note/siyuan#471]
如题，可以增加/删除行和列，输入或删除内容时出现图中现象。虽然一般也不会这样编辑...
![111](https://user-images.githubusercontent.com/73935960/98760380-1ecfa980-240e-11eb-8bae-0b3a98069155.png)

**Comment by 88250** [comment]
谢谢反馈，这个可能要过一段时间再处理了。

**Comment by 88250** [comment]
你好，这个问题在 v1.0.0 中已经修复。
