### ISSUE TITLE
代码块输入光标错误

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4710]
https://ld246.com/article/1650623107430

**Comment by WolkeAtreide** [comment]
from distutils.core import setup
setup(name="hm message",  # 包名
	version="1.0",  # 版本
	description="itheima's发送和接收消息模块”,  # 描述信息
	
long_description="完整的发送和接收消息模块"，#完整描述信息authora="itheima",#作者
author_email="itheima(@itheima.com",#作者邮箱url="www.itheima.com",#主页py_modules=["hm_message.send_message","hm_message.receive_message"])有关字典参数的详细信息，可以参阅官方网站：https://docs.python.org/2/distutils/apiref.html2)构建模块python3 setup.py build3)生成发布压缩包python3 setup.py sdist注意：要制作哪个版本的模块，就使用哪个版本的解释器执行！

**Comment by WolkeAtreide** [comment]
![image](https://user-images.githubusercontent.com/101959415/165471019-59824d56-47a5-4fdc-ae4d-1291c4b88e58.png)
将上文整理成如图格式，在第5行输入"()",")"会跳到下一行去。

**Comment by Vanessa219** [comment]
升级 Electron 和 highlight 后已经修复。
