### ISSUE TITLE
全局搜索支持搜索自定义属性

### ISSUE THREAD

**Issue by WJ231009014** [siyuan-note/siyuan#4711]
### 描述问题 Describe the problem
文档标签和文档内的标签都无法通过全局搜索进行搜索，只能点击标签在弹出的侧栏搜索中找到。

### 期待的结果 Expected result
全局搜索可以搜索标签

### 截屏或者录屏演示 Screenshot or screen recording presentation

1. 创建一个test文档，文档标签和文档内标签均为"0=test"。
![image](https://user-images.githubusercontent.com/41817475/165439628-d6d5ff10-84f5-4ece-bb67-3fd9de41b649.png)
2. 全局搜索"0=test"，无搜索结果。
![image](https://user-images.githubusercontent.com/41817475/165439793-9eb428d0-898b-4713-82c9-b300783f5bb3.png)
3. 点击标签，弹出的侧边栏搜索框中可以显示结果。
![image](https://user-images.githubusercontent.com/41817475/165439862-bc0c1000-30ec-4d40-afde-c4123fefc738.png)

### 版本环境 Version environment

* Version: 2.0.2
* Operating system: Windows 11
* Browser (if used): 

### 日志文件 Log file
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8568771/siyuan.log)

**Comment by mozhux** [comment]
全局搜索改了，有符号的话 要加“” 引号

**Comment by WJ231009014** [comment]
> 全局搜索改了，有符号的话 要加“” 引号

文档内的标签这样能搜到了，文档标签是一直都不能使用全局搜索吗？
![image](https://user-images.githubusercontent.com/41817475/165460705-88be0752-b174-4d0a-9c17-adfa1a2db3a0.png)

**Comment by 88250** [comment]
下个版本改进，届时直接搜索关键字就可以了，不用加 `#`。

**Comment by Zuoqiu-Yingyi** [comment]
> 下个版本改进，届时直接搜索关键字就可以了，不用加 `#`。

这个改进貌似又将该特性搞丢了: `命中块命名/别名/备注` 的搜索结果优先级较 `命中块内容` 更高 :broken_heart:
![image](https://user-images.githubusercontent.com/49649786/165594337-1caa4202-0877-42aa-ab83-805d99474186.png)
