### ISSUE TITLE
新版同步云端目录无法删除

### ISSUE THREAD

**Issue by Morganwan90** [siyuan-note/siyuan#4712]
![截图_20220427131651](https://user-images.githubusercontent.com/61633409/165445725-fd8c65b1-76c6-4f39-8cc2-7da6769c2c1d.png)
点击删除按钮并无法彻底删除同步档案

**Comment by 88250** [comment]
新版同步么？

**Comment by Morganwan90** [comment]
是的D大，选择旧版同步状态可以删除，但是再打开新版同步后又会出现，操作如图
![截图_20220427152118](https://user-images.githubusercontent.com/61633409/165463625-4c21a11d-45f7-41ef-9769-c93eafcc1b00.gif)

**Comment by 88250** [comment]
感谢反馈，应该已经修复，请帮忙测试一下。

**Comment by Morganwan90** [comment]
已正常~
