### ISSUE TITLE
收集箱公众号输入按日期合并

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4718]
通过公众号输入的文本、图片内容按日期 `2006-01-02` 作为一篇合并保存，每次新的输入追加到当天末尾。

输入的超链接还是按剪藏分篇保存。

**Comment by JCJC01** [comment]
你好，如果收集箱已经按照日期汇总了，后面的时间提示是否可以取消，增加有效的显示空间
![image](https://user-images.githubusercontent.com/103412730/165878757-fe0533ce-e6e5-4e97-b94c-7d9612fbb8ab.png)

**Comment by 88250** [comment]
@JCJC01 只是文本和图片按日期汇总，超链接还是剪藏生成新的条目，所以这个日期不适合简短。如果实在需要，可以考虑自定义主题。
