### ISSUE TITLE
提供通过资源文件相对路径获得资源文件绝对路径的 API

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4720]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

如果资源文件不在 `/data/assets/` 目录下, 那么由于不知道资源文件相对于工作空间的绝对路径, 因此无法使用 `/api/asset/upload` 与 `/api/file/putFile` 两个 API 完成资源文件的写入

### 描述可能的最优解决方案 Describe the optimal solution

提供通过资源文件相对路径获得资源文件绝对路径的 API

### 描述候选的解决方案 Describe the candidate solution

在数据库资源文件表 assets 中新增一个字段, 保存资源文件相对于工作空间根目录的绝对路径

**Comment by 88250** [comment]
试试 `/api/asset/resolveAssetPath`，参数：

```json
{
  "path": "assets/xxxx"
}
```

**Comment by Zuoqiu-Yingyi** [comment]
* `/api/asset/resolveAssetPath`
* 参数

  * ```json
    {
        "path": "assets/fx-991CN_X_CN-20220407213234-gbaani5.pdf"
    }
    ```
* 响应

  * ```json
    {
        "code": 0,
        "msg": "",
        "data": "D:\\Notebook\\Siyuan\\workspace\\data\\20210914201520-i0v92g9\\assets\\fx-991CN_X_CN-20220407213234-gbaani5.pdf"
    }
    ```
