### ISSUE TITLE
行内代码无法直接粘贴

### ISSUE THREAD

**Issue by xuhuanzy** [siyuan-note/siyuan#4722]
行内代码块无具体内容时直接粘贴会导致行内代码块消失
版本 v2.0.2

**Comment by 88250** [comment]
你指的是空的 `<code></code>` 吗？

**Comment by xuhuanzy** [comment]
> 你指的是空的 `<code></code>` 吗？
是空的<code></code>
而且刚刚发现光标移出行内代码, 然后输入随意内容, 再将光标移进行内代码, 粘贴, 粘贴内容会被放到<code></code>外
同时行内代码块无法在<code>我的内容</code>的最后一个字之后追加内容
