### ISSUE TITLE
收集箱发送纯文本和图片不能收集

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#4724]
### 描述问题 Describe the problem

版本v2.0.2
收集箱可以剪藏链接，但是发送纯文本和图片则不能正常收集

**Comment by 88250** [comment]
没有出现在以日期 2022-4-28 的条目中吗？

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/165701761-07c0f1ce-8cb3-40fb-b34b-033f0f3c5cbc.png)
没有，只有剪藏的内容

**Comment by 88250** [comment]
刚刚定位到问题，应该已经修复，请再试一下。

**Comment by Achuan-2** [comment]
可以了
