### ISSUE TITLE
新同步模式异常

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#4725]
如图，
1.开启之后，云端文件只剩65b，之前的都清空了。
2.云端同步栏一直在转圈，加载不了同步空间
3.同步失败
![image-20220428142451-4n4u2y3](https://user-images.githubusercontent.com/101959415/165690254-29e41d43-9e4a-4c31-b507-9193c858af41.png)

**Comment by WolkeAtreide** [comment]
同时，旧版同步功能，手机端无法同步
![Screenshot_20220428_122910_org b3log siyuan](https://user-images.githubusercontent.com/101959415/165691018-279fdb5d-6a13-45c1-9c6c-9aff75f0bb7a.jpg)

**Comment by WolkeAtreide** [comment]
![Screenshot_20220428_143050_org b3log siyuan](https://user-images.githubusercontent.com/101959415/165691211-112cac74-5e19-44e7-be4a-d295f32f0148.jpg)
![Screenshot_20220428_143034_org b3log siyuan](https://user-images.githubusercontent.com/101959415/165691222-b88a9b9b-54cc-4d0c-9b17-3ddfb3bcd7ff.jpg)

**Comment by 88250** [comment]
版本是？

**Comment by 88250** [comment]
看到版本，下载最新版试试。
