### ISSUE TITLE
在文档首插入代码块后三击后退格会删除下一个相邻块的内容

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4726]
### 描述问题 Describe the problem

复现步骤:
1. 新建一个文档
2. 在文档中随便输入几个字符
3. 使用 API `/api/block/prependBlock` 往文档中插入一个非空代码块, 这里请求体如下所示,  `paremtID` 为刚刚新建的文档块 ID
```sql
{
  "data": "```sql\n123\n```",
  "dataType": "markdown",
  "parentID": "20220428105203-l4r21a3"
}
```
4. 三击刚刚插入的代码块, 之后使用 <kbd>backspace</kbd> 删除选中内容
5. 代码块中所选内容删除, 下一个块内容移动到了代码块中, 刷新该文档后发现下一个块内容复制到了代码块中

### 期待的结果 Expected result

三击刚刚插入的代码块, 之后使用 <kbd>backspace</kbd> 删除选中内容时仅删除所选内容, 不影响相邻块

### 截屏或者录屏演示 Screenshot or screen recording presentation

![思源笔记-bug反馈-28](https://user-images.githubusercontent.com/49649786/165708488-6d72ca24-4eed-45ec-8620-ed494e68fe6b.gif)

### 版本环境 Version environment

* Version: 2.0.2
* Operatin system: 
* Browser (if used):

**Comment by 88250** [comment]
似乎不用 API 也是这个表现。
