### ISSUE TITLE
增加收起和打开边栏的按钮

### ISSUE THREAD

**Issue by lowwor** [siyuan-note/siyuan#473]
例如左边栏同时打开了文件树、大纲、标签，需要一个按钮快速收起左边栏，类似于vscode收起边栏的效果

**Comment by 88250** [comment]
UI 上没有“侧边栏”概念，请通过快捷键逐一收起，是有点麻烦……

后面考虑下是否有必要引入“Dock”这样的 UI 元素，用于盛放页签。
