### ISSUE TITLE
代码块语言样式改进

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4730]
https://ld246.com/article/1651116168643?r=88250

**Comment by Zuoqiu-Yingyi** [comment]
请问为什么要移除复制按钮呀❓

**Comment by choyy** [comment]
复制很常用的，别移除啊

**Comment by ttimasdf** [comment]
为啥要移除复制按钮？？

**Comment by ttimasdf** [comment]
而且这个样式改进完后，上下和左右的padding差距太大，视觉效果不对称，非常奇怪。然后复制按钮还消失了，我一度以为同步把主题给同步坏了，来回重装了好几遍，换了好几个主题，才发现原来是给更新了。。

**Comment by 88250** [comment]
抱歉抱歉，下个版本进行改进 https://github.com/siyuan-note/siyuan/issues/4737
