### ISSUE TITLE
支持列表大纲的嵌入块

### ISSUE THREAD

**Issue by Rao-Jupiter** [siyuan-note/siyuan#4736]
现在的嵌入块不能支持多列的列表大纲的嵌入，嵌入的块只有一行
![image](https://user-images.githubusercontent.com/70786042/165977317-da6d0a01-2c82-4d62-b000-36ab9f4cb5fb.png)

在 logseq 中，块的嵌入可以把 outline之下的全部行都显示
![image](https://user-images.githubusercontent.com/70786042/165977419-92699e46-de67-4e9e-94e3-21141340e2f9.png)

思源能不能也添加这个功能

如果使用超级块的话，实在是太麻烦了

**Comment by 88250** [comment]
可能是没有嵌入列表或者列表项块吧？思源里列表、列表项和段落是有区分的。

**Comment by Rao-Jupiter** [comment]
非常希望加上这个功能

**Comment by 88250** [comment]
这个是默认就支持的。

**Comment by Rao-Jupiter** [comment]
> 这个是默认就支持的。

那怎么才能嵌入列表呢？在帮助里没看到，网上也也没搜到解决办法

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/166086605-e60407c9-c6aa-4bdd-a208-a6414721f3b0.png)

这个是列表的块标，用这个下面的复制嵌入块。

**Comment by Rao-Jupiter** [comment]
那有没有可能加一个触发的语法呢？像Notion那样复制粘贴感觉有些麻烦

**Comment by 88250** [comment]
`[[` 搜索就可以了，在 设置 - 搜索 - 类型 里面可以把不需要的类型关掉。

**Comment by Rao-Jupiter** [comment]
> `[[` 搜索就可以了，在 设置 - 搜索 - 类型 里面可以把不需要的类型关掉。

非常感谢非常感谢！！
