### ISSUE TITLE
代码块改进

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#4737]
### 描述问题 Describe the problem

如题所述, 可能是 #4730 引入的问题

### 期待的结果 Expected result

代码块过长时, 如果禁用了自动折行, 使用快捷键 `Home` 将光标移动至当前行开头的同时将滚动条移动至最左侧

### 截屏或者录屏演示 Screenshot or screen recording presentation

![思源笔记-bug反馈-29](https://user-images.githubusercontent.com/49649786/166004397-f76e6def-b6a0-442d-9aaf-a106afba8a5e.gif)

### 版本环境 Version environment

* Version: 2.0.3
* Operating system: 
* Browser (if used):

**Comment by Zuoqiu-Yingyi** [comment]
还有个问题, 折叠该代码块后第一行显示一半, 样式怪怪的~

![image](https://user-images.githubusercontent.com/49649786/166088192-62422896-b353-4c44-a949-751bb6b967cf.png)

**Comment by Vanessa219** [comment]
好像重现了一次就再也无法重现了，有特定的重现步骤么？

折叠问题已修改。
