### ISSUE TITLE
[bug]反链提及中默认纳入当前文档名作为锚文本进行搜索未生效

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#474]
已更新至0.4.4 Windows版
![image](https://user-images.githubusercontent.com/11732858/98772008-b1794400-2420-11eb-9b47-6c96dfe0b26e.png)
反向链接中应出现[20201113]关于女朋友的提及

**Comment by 88250** [comment]
看上去好像是 UI 上面的问题，反链页签分为上下两部分，截图上只看到链接部分，下面应该还有提及部分：

![image](https://user-images.githubusercontent.com/873584/98773602-3ade4580-2424-11eb-85ed-9934fc1ae425.png)

**Comment by 88250** [comment]
在 v0.4.7 里进行了修复，请帮忙留意，我关闭了，谢谢。
