### ISSUE TITLE
当光标移动到图表等块上时统一显示编辑和菜单按钮，取消其点击事件

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#4742]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?
目前思源里对于图表块、html块的编辑代码功能操作逻辑不统一
- Mermaid、五线谱、Graphviz、FlowChart、PlantUML等图表都是点击直接弹出代码编辑窗口
- Echarts、mindmap、html块则是需要到块标菜单里选择后才能编辑

这两种编辑操作逻辑不统一，在块菜单里选择编辑按钮步骤有些繁琐。

### 描述可能的最优解决方案 Describe the optimal solution

sql查询嵌入块的编辑按钮一样，在图表块右上角添加编辑按钮进行代码编辑

**Comment by Vanessa219** [comment]
图标、脑图、html 的界面会有点击事件，因此目前不能和其他图标进行统一的操作。

如果都添加按钮的话，可以进行统一处理。
