### ISSUE TITLE
威联通NAS ts428 docker 安装思源启动后报错

### ISSUE THREAD

**Issue by idmanage** [siyuan-note/siyuan#4744]
是arm64 架构的

启动失败打开控制台查看如下报错代码：
standard_init_linux.go:228: exec user process caused exec format error

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/2580

**Comment by idmanage** [comment]
> #2580

什么时候才能支持啊，很好用的笔记，用不了。。。

**Comment by 88250** [comment]
有计划的时候会重开 2580。
