### ISSUE TITLE
增加块引用默认模板 | 锚文本模板

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#4746]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

有大量的笔记如下述格式：标题为Xi，编辑属性中的命名为Yi

直接用`((`进行块引用时(即锚文本为空)，默认显示Yi(当前的特性)。

**想要增加的特性**：

个人需要在一个汇总页面上，显示的名为`Xi-(Yi)`, 每次都得手动修改锚文本，非常费时费力，而且Xi改变后，更新起来还不方便

### 描述可能的最优解决方案 Describe the optimal solution

**更新点1：**

在笔记本设置中，提供一个栏目，为块引用锚文本模板

![{700C4A38-75CE-30E8-D020-61C48F14348C}](https://user-images.githubusercontent.com/19968935/166092946-b508d880-7a95-484c-8cd5-4702ec702b50.jpg)

并且在右键菜单，添加一个复制模板的选项：

![{C03D80F2-3E3D-A5F2-78BB-33E51944DA62}](https://user-images.githubusercontent.com/19968935/166092963-0ce425c6-b3cb-49a7-98a3-743956d58ffd.jpg)

如果设置为{{title}}-({{alias}}), 则粘贴块引用时，锚文本部分用这个替换：

![image](https://user-images.githubusercontent.com/19968935/166093023-5993f82b-b875-4603-b7a1-f211141039ec.png)

**更新点2**：
当锚文本存在模板时，自动根据模板渲染为Xi-(Yi)，并且会随着文本的更新而更新

可以用`\{`进行转义来区别模板字段和普通文本字段的区别

**Comment by 88250** [comment]
你好，这个应该不会考虑内置，因为模板变量感觉用法过于固定（没有几个变量可用），该用法也过于依赖笔记结构。

目前要达成需求的话可以考虑用外部工具或者通过 theme.js 实现，主要思路是复制时从块 DOM 中获取块属性，然后拼接为 `((id "title-alias"))` 的格式写入剪切板。

**Comment by HowcanoeWang** [comment]
> 你好，这个应该不会考虑内置，因为模板变量感觉用法过于固定（没有几个变量可用），该用法也过于依赖笔记结构。
> 
> 目前要达成需求的话可以考虑用外部工具或者通过 theme.js 实现，主要思路是复制时从块 DOM 中获取块属性，然后拼接为 `((id "title-alias"))` 的格式写入剪切板。

那如果是单纯的，锚文本区域支持模板变量呢？（更新点2）

**Comment by 88250** [comment]
应该是做不到啊，动态锚文本的机制比较复杂。
