### ISSUE TITLE
Delay when closing the program.

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#4748]
Since version 1.9.9 I've been noticing a delay of almost 40 seconds to close the program. Previously, the program closed in less than 5 seconds.
I have a 479mb repository, full of information and images for my studies. I believe the size of the local folder would not affect performance when closing the application.

![image](https://user-images.githubusercontent.com/90691302/166102094-50c10764-c42f-4040-8431-77fb04f85394.png)

System: Windows 10

**Comment by 88250** [comment]
Please upload the log file.

**Comment by taozina** [comment]
Can you help me? How is this file obtained? Sorry for my inexperience in this field.

**Comment by taozina** [comment]
this file?

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8596917/siyuan.log)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/166106222-f1493d2f-4a11-4f43-8b3d-16cde323e6c5.png)

**Comment by taozina** [comment]
I already found it! It's above your comment. Thanks,

**Comment by 88250** [comment]
Oh, I saw it, but I have not found the cause from the log file.

**Comment by taozina** [comment]
@88250 When I change the local folder in the program (I go to a new one with no information), the program is normal! Closes in less than 1 second. But with my local folder, there is this delay of more than 40 seconds.

**Comment by 88250** [comment]
Please help try the following steps:

1. Start, do not modify any documents after the startup is completed
2. Exit directly

See how long it takes.

**Comment by 88250** [comment]
It is closed first, if you have additional information, please feel free to post, thank you.

**Comment by 88250** [comment]
Hello, we will optimize it at https://github.com/siyuan-note/siyuan/issues/4812, please help to test it after release, thank you very much.

**Comment by taozina** [comment]
Thank you friend. I will be waiting for the new update. The program continues with the same performance when starting and executing its normal functions. But to close... It's taking around 40 seconds or more with the message "exiting..." at the top. It's really bothering me a little.

**Comment by taozina** [comment]
@88250  Friend, problem solved! It became extremely fast when opening and closing the program. Thank you so much for the experience!
