### ISSUE TITLE
注脚语法未生效

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#475]
已打开支持注脚语法开关,但使用时未生效,版本0.4.4 Windows版

![image](https://user-images.githubusercontent.com/11732858/98772866-ae7f5300-2422-11eb-98a5-640e9ab104de.png)

**Comment by 88250** [comment]
脚注定义写了吗？

```markdown
这里是脚注引用[^ggg]

[^ggg]: 这里是脚注定义
```

**Comment by 88250** [comment]
我关闭了，如果还有问题请继续跟帖，谢谢。
