### ISSUE TITLE
API 请求鉴权提示优化

### ISSUE THREAD

**Issue by Clouder0** [siyuan-note/siyuan#4753]
### 描述问题 Describe the problem

目前调用 API 时，若未鉴权会返回整个鉴权 html 页面。

### 期待的结果 Expected result

希望可以返回 json，例如：

```json
{
	"code": -1,
	"msg": "Authorization Failed.",
        "data": null
```

### 截图

![Authorization Failed](https://user-images.githubusercontent.com/41664195/166132407-d3daa5f2-e453-4af2-ac96-bd142b7497d5.png)

![Authorization Succeeded](https://user-images.githubusercontent.com/41664195/166132410-2320580f-1c00-46e4-982d-c89a2fbd2ff1.png)

### 版本环境 Version environment

* Version: v2.0.3

**Comment by 88250** [comment]
下个版本改进，鉴权不通过的话 HTTP 状态码 `401`，body：

```json
{
    "code": -1,
    "msg": "Auth failed"
}
```

**Comment by maoruibin** [comment]
@88250 你好，作者。

我使用 API 进行笔记发送时一直提示 401，但我检查我的 token 是对的，你可以看我截图，这里鉴权不通过还有什么原因吗，不会是因为没有开通会员吧，我看这个不是会员功能。

![image](https://github.com/user-attachments/assets/596e7df5-012b-4e91-b942-79f9cf48dd0a)

![image](https://github.com/user-attachments/assets/47990b03-c788-415e-9091-32389ddf2880)
