### ISSUE TITLE
关于data导出，以及data目录下emoji、templates、widgets是否考虑调整到conf/appearance下

### ISSUE THREAD

**Issue by mindstudy** [siyuan-note/siyuan#4754]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?
主要考虑：
1、emoji、templates、widgets 实际上与外观关系比较密切，相对恒定，不像用户数据每天都会变化
2、现在可以在设置里一键盘导出整个data目录了，而有些 widgets 如 drawio 会带有很大的库文件，导出的必要性不是很大
另 conf/appearance 也有 emoji 目录，不知与 data/emoji 的区别具体是什么，如果合并一处，也便于管理
 
### 描述可能的最优解决方案 Describe the optimal solution
将data目录下emoji、templates、widgets调整到conf/appearance下

### 描述候选的解决方案 Describe the candidate solution
导出data时不包含 emoji、templates、widgets 三个目录

**Comment by 88250** [comment]
这几个是和数据相关的，需要多端同步才能保证数据的完整性。

appearance/emojis 是内置的表情图片文件，data/emojis 是用户自定义的表情图片。
