### ISSUE TITLE
外观菜单修改为横排

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4757]

**Comment by Zuoqiu-Yingyi** [comment]
请问这里菜单是哪个菜单呀❓

**Comment by Vanessa219** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/970828/167333577-39eef622-9e6b-4f56-8061-d72c4211c6ad.png">

**Comment by JCJC01** [comment]
菜单方面，张亮主题的横排使用效果很好

**Comment by aplicher** [comment]
> 

![image](https://user-images.githubusercontent.com/92669750/167378486-1c60a90f-eae5-4d80-b3c1-beb36ec4f982.png)
不止那一个，望考虑全面些。许多内容我并没有直接提及，比如上图的斜杠唤出的菜单。比如同一类型的命令，在块属性鼠标唤出的菜单上可以考虑给出图标横排，以此缩减不必要的长度使得功能罗列的更有条理：
![image](https://user-images.githubusercontent.com/92669750/167379378-3e7fb565-8d0b-4c1a-b3d5-0c782c4f5ee4.png)

**Comment by mindstudy** [comment]
从测试的效果看，外观菜单和按/菜单使用横排效果较好
<img width="724" alt="Screen Shot 2022-05-10 at 6 48 15 AM" src="https://user-images.githubusercontent.com/23169045/167512771-c474b007-6175-4ce0-8b85-f1d765b40ea9.png">

![Kapture 2022-05-10 at 07 01 47](https://user-images.githubusercontent.com/23169045/167512782-456137b7-af13-424f-8105-6af784118f82.gif)

块引搜索不建议，一是宽度不够，二是如果有命名别名，很容易参差不齐
