### ISSUE TITLE
Pad 端支持 PDF 标注划选

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4758]

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/4238

**Comment by KuiyueRO** [comment]
D大可以看看这个的pdfjs压缩包。

ob的pdf标注插件，一样用的pdf.js，支持移动端划选，
- 包括支持高亮、下划线、删除线、自由绘制和截图

https://github.com/MarkMindCkm/obsidian-markmind/releases/tag/1.8.2

**Comment by 88250** [comment]
感谢提供相关资料，但目前时间有限，暂时还无法改进 Pad 端交互，见谅。
