### ISSUE TITLE
# 代码块复制按钮问题

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4761]
<img width="900" alt="Snipaste_2022-05-02_09-38-52" src="https://user-images.githubusercontent.com/66512309/166174748-3a16ecce-2985-4d03-a520-21e202fd7412.png">
不知道这算不算bug，选中的这个按钮应该是按下就会复制代码块内容，可是一个span标签里面没有任何内容，这个按钮是不是就看不见或者没用了😂。
还有建议js引入支持导入jQuery,这样比较方便自定义某些dom。

**Comment by 88250** [comment]
* 代码块会在下个版本改进 https://github.com/siyuan-note/siyuan/issues/4737
* theme.js 里面应该可以自定义加载 js
