### ISSUE TITLE
支持文档自定义属性导出

### ISSUE THREAD

**Issue by langzhou** [siyuan-note/siyuan#4766]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

自定义属于某个意义上来说也属于笔记内容的一部分，比如一篇内容为书评的笔记，我可能会设置这些属性值：

custom-author：张三
custom-rate：5
custom-read-date：2022-05-02

所以，当我把这篇笔记导出时，希望像题头图一样能够包含在导出的 md 文件里。

如果文档自定义属性不能支持导出，那么我在使用自定义属性时会变得更加谨慎，因为我不知道现在对文档所做的标记以后是否可以迁移。

### 描述可能的最优解决方案 Describe the optimal solution

在导出的 md 文件里以 YAML 语法放置自定义属性，类似于 Obsidian 或 Logseq 那样的处理方式。

### 描述候选的解决方案 Describe the candidate solution

暂无

### 其他信息 Other information

暂无

**Comment by 88250** [comment]
文档属性应该没问题，主要是支持文档属性以后其他块属性不支持，感觉不统一。

**Comment by Zuoqiu-Yingyi** [comment]
> 文档属性应该没问题，主要是支持文档属性以后其他块属性不支持，感觉不统一。

那提供一个由导出模板衍生的 API 接口如何❓
- 请求体为 `id`
- 响应体 `data` 为包含 kramdown-like IAL 的 Markdown 字符串, 如果 `id` 为文档块 ID, 那么首行为文档块的 IAL
  - 最好该接口支持所有块, 即如果 `id` 为容器块 ID, 那么容器内所有的下级块也都带有 IAL

**Comment by 88250** [comment]
kramdown 恐怕不是楼主期望 😂

**Comment by Zuoqiu-Yingyi** [comment]
> kramdown 恐怕不是楼主期望 😂

是我期望的嘿嘿~

**Comment by langzhou** [comment]
我暂时通过写个挂件来解决了，导出前将所有自定义属性插入到文档内。
