### ISSUE TITLE
从选中文字新建文档名称不全的问题

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#477]
如选中“ABCDEFGHIJKL”后新建文档，新建文档的名称会显示为“ABCDEFGHIJ...”，链接文字也是这样，后面部分的文字会被省略。

**Comment by 88250** [comment]
麻烦截图说明，谢谢

**Comment by 2016201256** [comment]
![微信截图_20201111202223](https://user-images.githubusercontent.com/58763608/98811385-bd362c00-245b-11eb-99a7-820a6e9207ed.png)
![微信截图_20201111202235](https://user-images.githubusercontent.com/58763608/98811391-c0c9b300-245b-11eb-9d94-266c039673a4.png)

**Comment by 88250** [comment]
哦，锚文本部分是自定义的，可以随意编辑的，不一定非要对应文档名称。

**Comment by 2016201256** [comment]
> 哦，锚文本部分是自定义的，可以随意编辑的，不一定非要对应文档名称。

就是之前可以直接以某段文字为标题新建一个文档，现在这样是文档名称和锚文本都不全，每次需要手动再把文档名称和锚文本中被省略的内容不全，不像之前那么方便

**Comment by 88250** [comment]
哦，好的，稍后我们改进，谢谢。
