### ISSUE TITLE
搜索支持按文档分组展现搜索结果

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4772]
https://ld246.com/article/1651503408588

~或者搜索面板 #3564 使用分组，全局搜索保持平铺不变。~

**Comment by haogeek** [comment]
搜索面板和全局搜索从功能上有什么区别？为什么既要有搜索面板又要有全局搜索呢？

**Comment by 88250** [comment]
搜索面板可能会支持按文档分组，全局搜索保持不变。

**Comment by haogeek** [comment]
两者的搜索规则和结果不一样吗？

**Comment by 88250** [comment]
正文中链滴上的帖子有描述。

**Comment by 88250** [comment]
主要是搜索结果展示有区别。

**Comment by QiuMP** [comment]
这个功能什么时候能上线呢？

**Comment by QiuMP** [comment]
这个功能我觉得可以做成用户能按照需求自行选择结果的展示形式

**Comment by 88250** [comment]
> 建议ctrl+p也能按所属文档分组，这个使用频率还挺高的，急需改进啊。

全局搜索注重的是快捷，使用分组展现的话反而影响了效率。搜索页签注重的是常驻对照，这里做分组展现的意义比较大。

**Comment by 88250** [comment]
@roverway 对了，你觉得按文档树结构（也就是层级）分组有必要吗？

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 V 姐, `v2.5.2` 中搜索对话框与搜索页签项的搜索结果列表均为 `<div id="searchList" class="search__list b3-list b3-list--background search__list">`, 导致该 HTML 元素的 id 重复, 且 `search__list` 类名有两个

**Comment by Vanessa219** [comment]
id 这个查询的时候会用父元素来进行限定，应该没有什么副作用。类重复这个下个版本修改。谢谢。

**Comment by roverway** [comment]
> @roverway 对了，你觉得按文档树结构（也就是层级）分组有必要吗？

@88250 刚看到这条，还没来得及时试用252。你指的是在按所属文档分组的基础上，进一步展现文档之间的层级关系吗？按我个人的使用习惯，觉得没必要，有点过于复杂了，没想到美观的展示方式，也不觉得这么有额外的效率方面的提升。

**Comment by 88250** [comment]
@roverway 嗯，文档树结构我们也觉得没有必要，后面再看情况吧。

**Comment by roverway** [comment]
> @roverway 嗯，文档树结构我们也觉得没有必要，后面再看情况吧。

252的分组展示方式我觉得就可以，不用更复杂了，只是我这边觉得这个版本搜索越发慢了。

**Comment by 88250** [comment]
@roverway 分组的话会比较慢，不分组应该和原来性能一样，这个我们后面再看看如何优化。
