### ISSUE TITLE
搜索无法搜索到列表项本身

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#4778]
### 描述问题 Describe the problem

如下图，只能搜索到列表项内的文字块，而不能搜到该列表项本身

![image](https://user-images.githubusercontent.com/19968935/166422073-06b95ac8-5ae3-4a4f-b7d0-39fd943ef50b.png)

不知这个是特性还是bug？

### 版本环境 Version environment

* Version: 2.0.3

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/166441436-d4a9a69f-35be-4e1a-b2da-3bb673ce5e1a.png)

这个应该就是吧？

**Comment by HowcanoeWang** [comment]
> ![image](https://user-images.githubusercontent.com/873584/166441436-d4a9a69f-35be-4e1a-b2da-3bb673ce5e1a.png)
> 
> 这个应该就是吧？

原来他会把后面的内容一起显示出来啊，连在一起太难区分了😂😂😂

中间要是能有个分隔就好了

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/4780 中改进。
