### ISSUE TITLE
支持设置悬浮窗弹出选项

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4781]
选项暂定如下：
选项 1：悬停显示浮窗，右键菜单（默认选项）
选项 2：Ctrl 显示浮窗，右键菜单（适合不太用浮窗的用户）
<del>选项 3：右键显示浮窗，ctrl+ 悬停修改锚文本（适合常用浮窗而且块引很多容易误触的用户)</del>

**Comment by winter60** [comment]
我是默认选项用户

**Comment by Zuoqiu-Yingyi** [comment]
选项三是不是更改为 *右键显示浮窗，ctrl+ 右键修改锚文本* 更符合交互逻辑❓

**Comment by fanglypro** [comment]
> 选项三是不是更改为 _右键显示浮窗，ctrl+ 右键修改锚文本_ 更符合交互逻辑❓

ctrl+悬停应该会更快捷一些，ctrl+右键 相当于在 ctrl+悬停 的基础上还多一个右键的操作（当然还需要保证ctrl+悬停后马上显示，悬停等待时间应当接近0，因为用户已经通过ctrl键给出意图反馈了，不需要再靠等待时间来判断用户意图，即不需要像现在直接悬停时需要等待0.几秒）

**Comment by Zuoqiu-Yingyi** [comment]
最好还可以自定义触发鼠标悬浮事件的时间

**Comment by UFDXD** [comment]
突然发现大量引用下悬浮窗还是比较烦人的，这里顶一下，支持一下

**Comment by andyer1511** [comment]
希望能再加一个选项，左击显示悬浮窗，右击修改锚文本，Ctrl+左击新页签打开

**Comment by UFDXD** [comment]
选项3这么没了呢，选项中最管用的就是3了

**Comment by UFDXD** [comment]
@88250 感觉可以点击长按弹出悬浮窗，可以的话支持一下

**Comment by Vanessa219** [comment]
右键一般都是菜单，就不进行修改了。
