### ISSUE TITLE
希望提供节点管理器

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#4783]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?
虽然思源默认只能选择单个节点，通过 【移动】来完成转移，但是对于一些特定场合不方便。
能否开发类似所有大纲管理软件的快捷管理界面，例如 Leo-Editor以及pdf阅读软件的书签管理器那样，方便缩进和上下移动。
通过快捷键呼出管理界面即可，管理界面置顶时，享有Alt-Left，Alt-Right等快捷键，与原来主界面不冲突。

或者先提供API, 支持移动到目标节点前、目标节点后、目标节点下的最后、目标节点下的最前。这样其他高手可以开发一个独立的节点管理器。

**Comment by 88250** [comment]
不太明白其他软件的交互，麻烦录屏演示，我们看下思源里是否已经有对应的功能。

**Comment by jabobian** [comment]
* ctrl+u 移动当前节点向上移动 （或 Shift+up）
* ctrl+d 移动当前节点向下移动  （或 Shift+down）
* ctrl+l  移动当前节点为上层节点 （或 Shift+←）
* ctrl+r  移动当前节点为子级节点  （或 Shift+→）

**Comment by 88250** [comment]
* 块向上移动 <kbd>Ctrl+Shift+↑</kbd> / <kbd>⇧⌘↑</kbd>
* 块向下移动 <kbd>Ctrl+Shift+↓</kbd> / <kbd>⇧⌘↓</kbd>
* 列表项反向缩进（移动到上层） <kbd>Shift+Tab</kbd> / <kbd>⇧Tab</kbd>
* 带子列表缩进（移动为子节点）<kbd>Tab</kbd>

**Comment by jabobian** [comment]
D大，你列出的上述快捷键只在文档内部能用，能否做到在文档树里面也能使用。
也就是当我们用Alt-1聚焦到文档树的时候，能够调整节点的位置。

**Comment by 88250** [comment]
@jabobian 抱歉做不了啊。
