### ISSUE TITLE
全局搜索提供创建新文档选项

### ISSUE THREAD

**Issue by Zijin-Cheung** [siyuan-note/siyuan#4786]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

全局搜索提供生成新文档的选项, 类似于block reference的操作. 这样在搜索无结果时可以直接创建文档, 节省在输入一次文档名的时间.

**Comment by 88250** [comment]
但是需要选择存放路径，就是放在根路径上，至少也要选择笔记本，所以实际上并不能提高效率，没有 Ctrl+N 快。

**Comment by Zijin-Cheung** [comment]
路径感觉可以提供一个全局的默认选项 create doc save location 之类的解决 (我自己是不用文档树的, 所以还挺希望能提供这样的选项).

这个适用场景在于不确定之前是否有过类似名称的文档, 从而需要先搜索再创建. 以及如果以后有文档直接合并的功能, 这个需要也可以间接解决.

**Comment by Zijin-Cheung** [comment]
RoamResearch 中把搜索时创建新文档的功能置于搜索首项 供参考

![image](https://user-images.githubusercontent.com/58776897/166865958-ef9fe907-8c53-48ce-b6ad-ecd8d00fef11.png)

**Comment by 88250** [comment]
搜索创建的话估计不适合思源；文档合并功能能描述一下吗？

**Comment by 88250** [comment]
先关闭了，欢迎随时补充讨论，谢谢。

**Comment by Zijin-Cheung** [comment]
谢谢D 大。我理解这个事情本质是 alias，举一个应用场景参考下：
假设之前做过关于 “Mount Everest”的笔记，今天看到了“珠穆朗玛峰”的报告，那么很自然的会先搜索“珠穆朗玛峰”(全局搜索/ref 也好），这时候搜不到相关笔记，才想着Ctrl+N创建。在目前一定会存在先搜索再创建新文档的过程（且这个搜索是局限的，即可能不会去搜索 “Mount Everest”）。假设在未来某一天突然意识到 “Mount Everest” 和 “珠穆朗玛峰”其实是指代同一个客体，那么此时的文档合并的最大困难在于不仅要合并文档内容，关于文档的链接ref block 和 link 都需要手动更改。
如果推出文档合并的功能，那么在workflow 上会节省这一步先搜索的过程，从而间接地解决了这个 issue。

**Comment by 88250** [comment]
谢谢，我明白了，请关注 https://github.com/siyuan-note/siyuan/issues/4025

**Comment by Zijin-Cheung** [comment]
另外一种直接的解决办法在 对搜索面框界面设定 一个特殊的“Ctrl+N”的快捷键/按钮，此时创建的新文档文档名带有 搜索内容 （类似template），不过这个可能只能对应于简单的搜索语句。

**Comment by 88250** [comment]
搜索新建这个先搁置，再考虑一下。

**Comment by Zijin-Cheung** [comment]
嗯嗯, 谢谢 D 大考虑,这个功能确实不太急
