### ISSUE TITLE
云存储文图

### ISSUE THREAD

**Issue by hzjsea** [siyuan-note/siyuan#4789]
网络正常，但是一旦切换网络场景（公司到家中） 会出现账户登录失败的问题

- 能否支持oss自定义图床的设置，即复制上传到自定义图床 类似于七牛阿里又拍这种
- 能否支持热更新

**Comment by 88250** [comment]
* 账号登录失败请检查版本，老版本的云端支持已经下线。如果已经使用了最新版，可能是本地网络的问题
* 暂时没有计划，请使用其他图床工具，然后粘贴链接
* 使用商店版可以自动更新
