### ISSUE TITLE
提供不带id的复制粘贴选项

### ISSUE THREAD

**Issue by Rao-Jupiter** [siyuan-note/siyuan#4790]
### 当我需要将文本复制到其他软件的时候（比如 word ，记事本）

![image](https://user-images.githubusercontent.com/70786042/166866295-624c3442-7e07-4f7c-a3d5-fa21afb9f78a.png)

之间复制出来会带着id符号

![image](https://user-images.githubusercontent.com/70786042/166866377-f99219c4-cb7e-465a-9b5f-f50b36edc533.png)

有些时候很难处理

能不能提供仅复制文本的选项，复制出来就是纯文本，而不带 id

**Comment by 88250** [comment]
在预览导出界面复制就可以了。
