### ISSUE TITLE
块引锚文本设置改进

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4793]
https://ld246.com/article/1651764688259

- [ ] 删除按钮修改为转换为文本
- [ ] 添加 * 转换
- [ ] 添加文本 * 转换
- [ ] 添加动态、静态锚文本转换
- [ ] 添加嵌入块转换
- [ ] 添加删除引用
- [ ] 添加复制引用
- [ ] 添加打开、右部打开、下部打开、打开新页签时保持光标位置

![image](https://user-images.githubusercontent.com/970828/167147723-8c58ec74-1fc7-4750-91f3-733d839b35ac.png)

**Comment by 88250** [comment]
转换为嵌入实现不了，嵌入块是块级元素。
