### ISSUE TITLE
代码块切换语言bug

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#4798]
![B](https://user-images.githubusercontent.com/38906705/167129633-dd844427-240f-420c-861a-f6a1f26c643d.gif)
有些电脑出现，有些电脑没出现，刷新就没了

**Comment by Vanessa219** [comment]
是不是有些电脑版本没升级？

**Comment by royc01** [comment]
这个bug出现不了了，或者是缓存问题，先关了
