### ISSUE TITLE
Copy or drag content with pictures to a different folder

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#480]
0.4.4
希望复制图片能正常显示

![图片复制](https://user-images.githubusercontent.com/15924513/98814368-89a9d080-2460-11eb-8db9-d847cab41524.gif)

**Comment by 88250** [comment]
这两个文档没有在同级目录下哦。

**Comment by lss6378** [comment]
> 
> 
> 这两个文档没有在同级目录下哦。

没有同级目录，希望能把图片拷贝过去哦

**Comment by 88250** [comment]
谢谢，我明白你的意思了，这个估计要等一阵子了，目前还在搞其他优先级更高的任务。

**Comment by lss6378** [comment]
> 
> 
> 谢谢，我明白你的意思了，这个估计要等一阵子了，目前还在搞其他优先级更高的任务。

不急，先拍个队
