### ISSUE TITLE
代码块行号错位

### ISSUE THREAD

**Issue by ad-calcium** [siyuan-note/siyuan#4804]
### 描述问题 Describe the problem

代码块行号错位

![image](https://user-images.githubusercontent.com/33044636/167238908-4ea1fd0e-ac51-4618-8ae4-09de9012a8a0.png)

siyuan和主题都是最新版

语言被遮挡住了
![image](https://user-images.githubusercontent.com/33044636/167238947-81d6b554-f7d0-4c3d-b188-53d99f1e285c.png)

### 版本环境 Version environment

* Version: v2.0.4
* Operating system: windows
* Browser (if used):

**Comment by 88250** [comment]
请试下更新主题，如果还是不行，请到主题参考反馈，谢谢。
