### ISSUE TITLE
docker部署思源笔记，文件存储位置

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#4809]
docker run --name siyuan -it -d --restart=always -v /data/SiYuan:/root/Documents/SiYuan -p 6806:6806 b3log/siyuan
使用上面代码部署的时候“-v /data/SiYuan:/var/SiYuan”并不会起作用，无论是在/data/SiYuan目录还是在/root/Documents/SiYuan目录（此目录找不到）均没有找到思源笔记存放的目录，但是可以正常地使用，不知笔记到底是存放在那个目录下？

**Comment by 88250** [comment]
你好，默认是在容器 /root/Documents/SiYuan 下，如果删除容器数据会丢失。

所以必须挂卷，然后通过内核启动参数 `--workspace` 指定到卷路径。
