### ISSUE TITLE
代码块折叠后，不能看到任何缩略内容

### ISSUE THREAD

**Issue by LecoLu** [siyuan-note/siyuan#4810]
新版2.0.4改版后，代码块将代码类型显示在了做左上角，折叠后只能看到代码类型，不能看到代码的缩略内容。

之前版本在折叠代码块后，可以看到代码块一行内容，现在什么都看不到，影响使用体检。

可以的话，建议在代码块折叠后，将代码类型背景弄透明（或者其他办法），显示代码块内容一行内容。这样使用体验比较好。

谢谢！

![image](https://user-images.githubusercontent.com/24625475/167255246-f30a1898-0af7-4e5e-ad59-6f1ec2d41acf.png)

**Comment by Vanessa219** [comment]
显示出代码的话，占用位置会太多了，如果代码只有一行的话就失去了折叠的意义。这个可以自定义 css 
```
.protyle-wysiwyg [data-node-id][fold="1"]:not(.li):not([data-type="NodeHeading"]).code-block {
    height: xxpx
}
```

**Comment by LecoLu** [comment]
代码可能是有几十上百行。之前旧版本，折叠后有显示第一行内容方便识别大概内容。而现在新版折叠后，什么都不显示。

**Comment by LecoLu** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
目前对代码块上方增加了横条来显示语言，当折叠后会固定显示语言的。目前考虑到只有一行代码的情况会比较尴尬，没有更好的办法来解决。
