### ISSUE TITLE
请增加对<span/>标签的支持

### ISSUE THREAD

**Issue by lightgis** [siyuan-note/siyuan#4813]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?
从其他软件生成的markdown文件会使用到span标签，但思源貌似不能解译span标签

### 描述可能的最优解决方案 Describe the optimal solution
请增加对<span/>标签的支持或者自动替换成<div />

**Comment by 88250** [comment]
行级 HTML 标签无法支持，只能导入之前在外部替换了，感谢反馈。
