### ISSUE TITLE
托盘bug

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#4815]
如图，经常发现这个问题。虽然一碰就没，但是终归是个小bug
![image](https://user-images.githubusercontent.com/101959415/167280516-79c69e34-1b76-440b-a898-aa42c16f9874.png)

**Comment by choyy** [comment]
其他托盘有时候也有这种情况，感觉是Windows的bug

**Comment by WolkeAtreide** [comment]
> 其他托盘有时候也有这种情况，感觉是Windows的bug

是吗？其他的没遇到过，思源挺频繁的，频繁到我习以为常了。所以才会这么久才来提。

**Comment by 88250** [comment]
暂时不清楚原因，先关闭了，后面如果还有人反馈这个问题就关联到这里，谢谢。
