### ISSUE TITLE
标签面板，标签引用同一个块，这个块作为被引用的结果多次出现

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#4816]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

2.0.5中，打开标签面板，选中要查看的标签，会发现引用同一个块会多次显示

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/33319484/167286243-c7c370dd-524a-4684-9a56-f128be48576c.png">

即标签引用同一个块，这里是列表项块，但是在标签列表中，会多出了一个段落块的引用，这里是否应该做一个筛选，只显示其一就可以？要么是段落块，要么是列表项块。

**Comment by royc01** [comment]
在设置-搜索里面过滤

**Comment by 88250** [comment]
楼上说的是对的，关闭了。

**Comment by JokeenZhang** [comment]
好的，看到直接关闭列表项即可。这样就能保留搜索结果里的段落块，那么这里可以理解段落块才是这里的基础，其他类型的块可以理解为更进一步的搜索筛选了。

royc01 ***@***.***> 于2022年5月8日周日 17:23写道：
