### ISSUE TITLE
Data lose issue when changing the notes directory

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#4817]
### 描述问题 Describe the problem

Happened with `2.4` version;   If we change the notes directory to a directory that already has notebooks, the app deletes all the old notebooks !

When I used an older version it didn't delete the old notebooks (thankfuly I had a backup)

**Comment by 88250** [comment]
Hi, are you referring to switching workspaces in <kbd>Settings - About</kbd>? If it is, I can't reproduce the issue.

**Comment by eslam-gomaa** [comment]
Yes that's what I mean

**Comment by 88250** [comment]
Can you reproduce the problem now?

**Comment by eslam-gomaa** [comment]
I can't after I used newer versions, I'll close it & reopen if faced it again
