### ISSUE TITLE
块引用的锚文本支持 Latex、加粗、强调等行级排版

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#482]
![image](https://user-images.githubusercontent.com/16791452/98908923-16ee3300-24fc-11eb-8748-d99ca0b03148.png)

开发者你好，我是一名研究生。对于理工科的人来说公式用得十分频繁，因此希望链接的文字也能支持latex渲染

**Comment by 88250** [comment]
你指的是这样 `[$latex$](url)` 的 Markdown 文本吗？

**Comment by frankli998** [comment]
![image](https://user-images.githubusercontent.com/16791452/98912755-7a2e9400-2501-11eb-9fb3-41b634db1c67.png)
不是，是思源的块引用。
markdown链接似乎能正确渲染

**Comment by frankli998** [comment]
准确来说是块引用的锚文本无法渲染latex

**Comment by frankli998** [comment]
该 bug 在0.5.41重现江湖
