### ISSUE TITLE
大纲面板里双链汇总无法显示下级标题

### ISSUE THREAD

**Issue by JCJC01** [siyuan-note/siyuan#4823]
![mmexport1651821102859](https://user-images.githubusercontent.com/103412730/167318876-418c1112-6e3f-409c-bc98-4a20a8e41114.png)
作用,如图，双链汇总是很重要的一个功能，方便daily note记录方法，在后期针对特殊内容的汇总回顾。
问题，目前在大纲面板中，双链汇总无法显示下级标题
如果后期内容多了，通过不同级别的标题在大纲面板中快速查找。

**Comment by 88250** [comment]
大纲面板只会展现当前文档的标题大纲，无法展现其他方式汇总到当前文档的标题大纲。
