### ISSUE TITLE
双链自定义解析

### ISSUE THREAD

**Issue by Zijin-Cheung** [siyuan-note/siyuan#4831]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

当前情况, 所以双链的解析为一个样式. 然而双链本身其实有多种语义: 段落之中的双链与对整个段落进行双链标记(类似 Tag)含义是不同的, 进一步而言双链不仅可以作为内容也可以设定为一种属性, 通过对双链加上不同的前缀/后缀或者设置完成对双链语义上的区分.  (解析这个词可能不太恰当)

### 描述可能的最优解决方案 Describe the optimal solution

提供一个简单可行的折中思路, 假设一个 Block Ref 为 " ((20211213211215-ky4xikt 'SiYuan')) ", 对应段落中的双链解析;
" #((20211213211215-ky4xikt 'SiYuan'))" 则可对应类 Tag 形式的双链解析;  " ((20211213211215-ky4xikt 'SiYuan')):: "则可对应属性的双链解析. 期待在样式上对这几种形式做出一定的区分.

参考 Roam Research 
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/58776897/167405106-cf2e3b2f-e348-41d7-9049-c8630548d549.png">

### 其他信息 Other information

进一步而言期待用户可以自定义解析, 从而用户可以在自定义主题 CSS 来完成不同样式的区分.

**Comment by Zijin-Cheung** [comment]
这个感觉算是块内文字的解析,如何用块级属性完成不同明白.

**Comment by 88250** [comment]
自定义解析的话支持不了，前面说的使用块级属性（比如书签）来进行另外维度的分类。
