### ISSUE TITLE
如何按引用数排序块

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4837]
为什么需要这个功能？
目前文档树可以按照引用数排序，但文档树不是扁平的，而且有多个笔记本，这个排序结果并不能快速找到被引用最多的那些块。logseq在 all pages里面可以看到引用最多的page。一般引用特别多的page，就表示需要整理了。

我看了blocks表的结构，里面没有被引用数这个字段。所以问一下是否有其他api可以实现这个功能。

**Comment by whuwangyong** [comment]
如果没有相关api，我能想到的一种变通方法是，把所有的块都放在一个同一个文档书目录下。即：
日记是按照年月归档的，但是在日记里用`[[]]`新建的块，全都放在一个地方，扁平化管理，这样文档树的引用排序就能起作用了。

**Comment by 88250** [comment]
估计不会内置支持，可以考虑通过 SQL 查询（关联 refs 表）。

**Comment by whuwangyong** [comment]
贴一下后续。
借助Query挂件，在 DashBoard 下面创建了一个页面用来显示高频引用的块：
![image](https://user-images.githubusercontent.com/5968678/167630741-dda38022-42ac-44e1-8b72-2659b3080977.png)

不足之处：最好是直接在“被引用方”上面添加块引链接，这样可以直接点击跳转过去。这可能需要去Query挂件改一点配置。暂时不折腾了。

看看有没大佬给个现成的方案。
