### ISSUE TITLE
`定位打开的文档` 增加快捷键

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4844]
https://ld246.com/article/1652182221881

**Comment by whuwangyong** [comment]
感觉不是很有必要，先说题主的描述：双手不离开键盘。
所谓的心流状态真的就是不用鼠标吗，动一下鼠标就影响专注了吗，这是否走进了极端。思源也有很多操作是只靠键盘做不到的，不可能所有操作都能被快捷键覆盖到。

仅供探讨。

**Comment by qifengle1998** [comment]
对我来说感知不强，我平常都不会打开文档树。快捷键的位置太珍贵了。

我觉得给用户开放自定义快捷键才是上策。

**Comment by woaihuangxueying** [comment]
支持自定义快捷键，用户自己加自己需要的快捷键。

或者可以做一个投票，反正我不觉得这个功能需要单独做一个快捷键。

**Comment by iamqiz** [comment]
个人觉得这个功能加个快捷键很必要, 同时也**支持自定义快捷键**
pycharm里这个快捷键为 alt+F1 然后按1
![image](https://user-images.githubusercontent.com/48077521/167678473-e6934efe-221c-4d39-9454-8053dc2fbdd7.png)

**Comment by whuwangyong** [comment]
赞同自定义。要说快捷键的话，我也有个刚需：Ctrl Tab 切换最近打开的页签，而不是现在这样按照顺序切。#4308

**Comment by Elliootalderson** [comment]
这都需要快捷键? 我内嵌网页/iframe+输入link 也需要一个快捷键.

**Comment by Elliootalderson** [comment]
删除当前页也该有个快捷键.建议:点击当前页面.,然后ctrl+delete

**Comment by Elliootalderson** [comment]
在目录中删除,就是点击后,ctrl+delete.目前基本都是点击后.右键,然后找到删除,然后才能删除.

**Comment by aobatu** [comment]
“定位打开的文档”是我最高频的一个操作，如果有一个快捷键的话还是会提升操作体验的。

**Comment by woaihuangxueying** [comment]
> 赞同自定义。要说快捷键的话，我也有个刚需：Ctrl Tab 切换最近打开的页签，而不是现在这样按照顺序切。#4308

这个快捷键也是我的刚需
