### ISSUE TITLE
调整启动/退出时云端同步网络连接超时

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4847]
https://ld246.com/article/1652195991553

**Comment by aobatu** [comment]
如果连接超时了会正常打开笔记吗？
我有一次在没有网络的环境下，打开笔记一直卡在同步，等了比较久的时间都没有进入。

**Comment by 88250** [comment]
能打开，但是要等 10 分钟超时，这个 issue 就是准备把启动/退出超时改短的。
