### ISSUE TITLE
Possible to change the language?

### ISSUE THREAD

**Issue by Kullenej** [siyuan-note/siyuan#4848]
Is it possible to change the language on ios?

**Comment by 88250** [comment]
Try this:

![IMG_20220511_092140](https://user-images.githubusercontent.com/873584/167750079-cca6b3bb-cdd9-4f76-91a7-309a50a5fa58.jpg)

![IMG_20220511_092211](https://user-images.githubusercontent.com/873584/167750092-7ba35bea-7c00-4dae-8f29-96c2859649d3.jpg)
