### ISSUE TITLE
macOS/iOS 端监听资源文件报错问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4855]
日志在 https://ld246.com/article/1652253135586 中获取，但暂时无法确认解密数据卡住的问题。

**Comment by william2113** [comment]
删除思源创建的文件夹、删除包内容之后重新安装。不再设置访问授权码，一切功能正常。不知道是不是和访问授权码有关。

**Comment by 88250** [comment]
@william2113 应该和访问授权码没有关系，我们先修复这个已知问题看看。

**Comment by CleinBlue** [comment]
@88250 重启之后又打不开了，卡在解密界面

**Comment by 88250** [comment]
@CleinBlue 先参考 https://ld246.com/article/1652253135586 这里看看

**Comment by CleinBlue** [comment]
@88250 我就是里面的tempvic，昨天部分时候能打开，今天又卡住，怀疑是个bug

**Comment by 88250** [comment]
打包内核日志上传一下。

**Comment by 88250** [comment]
@CleinBlue 内核日志文件位于工作空间/temp/siyuan.log

**Comment by CleinBlue** [comment]
@88250 已上传到链滴私信

**Comment by 88250** [comment]
@CleinBlue 1

**Comment by 88250** [comment]
已经确认是因为这个问题导致启动卡住，感谢各位反馈。
