### ISSUE TITLE
同时复制多张图片到思源后,默认黏贴在一个列表快,而不是一张图片占用一个块

### ISSUE THREAD

**Issue by Elliootalderson** [siyuan-note/siyuan#4857]
同时复制两张图片到思源
<img width="607" alt="image" src="https://user-images.githubusercontent.com/93273663/167845808-d14f8227-7756-4c3c-848a-3865e76b2ccc.png">

上面一张图片的名称为:10009.jpg
<img width="584" alt="image" src="https://user-images.githubusercontent.com/93273663/167846027-9247f327-e7c4-4109-abea-db351b8fb714.png">
使用的时候是这样
<img width="440" alt="image" src="https://user-images.githubusercontent.com/93273663/167846240-4435a487-10cd-4780-b6c9-a11f9b9219df.png">
他们黏在一起. 用不了,只能单独复制出来

这个提议优先级不高,只是发现了而已. 大佬不用急.

**Comment by 88250** [comment]
这是特性，思源支持行级图片，所以多个一起复制的话是按行级元素插入。
