### ISSUE TITLE
脚注块显示不全

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#486]
![image](https://user-images.githubusercontent.com/16791452/98932709-a6a2da00-251a-11eb-8c66-53265fd1dee3.png)

**Comment by 88250** [comment]
嗯，太长的话故意省略的。

**Comment by frankli998** [comment]
那是否考虑过加一个省略号？突然截断有点不适应，有时候甚至单词显示到一半就截断了看得很难受...

**Comment by frankli998** [comment]
![image](https://user-images.githubusercontent.com/16791452/98933376-7f98d800-251b-11eb-8416-ee08c4af6a30.png)

比如单词显示到一半就截断了

**Comment by 88250** [comment]
好的，谢谢，稍后优化。
