### ISSUE TITLE
谜之安装目录

### ISSUE THREAD

**Issue by shelllee** [siyuan-note/siyuan#4860]
### 不知道安装目录是什么，直接就提示要删除资源

![image](https://user-images.githubusercontent.com/11704124/167885028-4c10c3d2-aefe-4b9e-837e-5f38e077bbee.png)

### 期待的结果 Expected result

1. 至少知道是什么目录
2. 进阶如果是覆盖安装可支持old资源识别么？

PS：刚接触思源，要是issue提的有问题就直接关了吧

**Comment by 88250** [comment]
只要确保安装路径下没有你自己的文件即可。

**Comment by shelllee** [comment]
> 

是说这个界面弹出的太早了，还没到安装目录选择，我都不知道会安装到哪里，我也不知道会不会让选择安装目录，假如不让选择，直接安装了怎么办

**Comment by 88250** [comment]
没法置后啊，所以只能提前告知用户。
