### ISSUE TITLE
跨文档拖动列表块然后撤销导致块丢失

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4864]
今天思源丢笔记了。历史里也没有。

## 场景
通过反链面板整理笔记。把一个块从反链面板拖进目标文档，形成了超级块，不是我想要的，习惯性按了Ctrl Z，拖进来的块就没有了。当然此时这个块也没有回到原来所在的文档里。此时再按Ctrl Y，这个块也不会在这个文档出现了。这条笔记就丢了。

## 简化后的复现步骤
![4](https://user-images.githubusercontent.com/5968678/167911596-bd7656b9-58b5-4ea7-b187-7a0299f4acf4.gif)

**Comment by 88250** [comment]
跨文档不支持撤销，这个问题在 https://github.com/siyuan-note/siyuan/issues/4866 中明确，感谢反馈。
