### ISSUE TITLE
【建议】开发者应该更大力度的拒绝边缘需求

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#4865]
例如：
1. 增加xx快捷键
2. 取消创建桌面快捷方式（虽然这是我敬佩的哈桑大佬提的，但我也要说这个真的不重要）

难道状态异常都解决了吗？反链面板已经很好用了吗？核心功能还没打磨好，这些边角料真的可以放一放。毕竟开发者就俩人。有的也不是边角料，确实是很好的改进点，比如方向键展开文档树，但这些是锦上添花的功能，咱得先做好这块锦。

仅是建议，如有冒犯，先说声抱歉。

**Comment by Elliootalderson** [comment]
![image](https://user-images.githubusercontent.com/93273663/167955503-196de0a6-7189-4eb8-857d-815cd4fcd14e.png)
顺便提一个bug, 上面图中的有序列表.如果不是在一个列表块项中,即使是同级, 也不会按顺序显示. F5刷新也没用. 
![image](https://user-images.githubusercontent.com/93273663/167955780-49de483d-8004-4247-8953-68d317953752.png)

**Comment by 88250** [comment]
感谢建议，说实话已经拒绝很多了，稳定性得一点点来，之前集中解决过一部分，目前还遇到的稳定性问题优先级肯定是最高解决的。

**Comment by 88250** [comment]
@Elliootalderson 有序列表可以不以 `1` 开头。
