### ISSUE TITLE
mac端 从2.05版本开始重启电脑后 思源会卡住

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#4867]
![image](https://user-images.githubusercontent.com/62794181/167971751-15c692a2-a2a3-48f2-ac18-86a919ddcfe4.png)

呈现出的是如图的画面，重启软件，卸载重装都无效，删除文稿中的思源文件夹后可顺利进入，但会失去全部信息。目前更新版本都无效，win端和安卓端都无此现象。

**Comment by 88250** [comment]
https://ld246.com/article/1652317393293
