### ISSUE TITLE
列表块移动为子列表块时 ID 变化

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4868]
https://user-images.githubusercontent.com/873584/167983921-8c26f56d-b44a-49d9-b72f-96e6760b0e51.mp4

**Comment by Vanessa219** [comment]
引用的是列表，拖拽的是列表项。当列表项拖拽出去以后，空列表就会被清除。如果不想消失的话应该拖拽列表块而非列表项块。

**Comment by Tlonglan** [comment]
原来如此~ 然而这样会有个小问题，在这种情况下的子列表项 反向缩进 为同级的列表项时，就会触发这个状态导致反链消失，实际上应该还是要保留的

**Comment by 88250** [comment]
@Tlonglan 这里有点冲突，估计保留不了：子列表项反向缩进后列表块就丢失了，没有地方保留。

**Comment by Tlonglan** [comment]
enen理解，如果从逻辑上解决不了这个问题的话，那只能避免使用这样的操作了🤔

**Comment by 88250** [comment]
暂时先只能这样，后面再考虑看看有没有解决方案。

**Comment by Tlonglan** [comment]
好的~
