### ISSUE TITLE
行级公式渲染大小自适应标题级别

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#487]
typora latex 渲染有自适应
思源没有自适应

![image](https://user-images.githubusercontent.com/16791452/98935687-d8b63b00-251e-11eb-8953-bd289ec4cfd3.png)

**Comment by 88250** [comment]
麻烦用一样的截图对比，不然我有点看不明白……

**Comment by frankli998** [comment]
![image](https://user-images.githubusercontent.com/16791452/98935687-d8b63b00-251e-11eb-8953-bd289ec4cfd3.png)

**Comment by frankli998** [comment]
0.5.41 该 bug 重现江湖
