### ISSUE TITLE
结束推荐订阅送终身会员活动

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4872]
* 下线推荐码机制
* https://github.com/siyuan-note/siyuan/issues/4909

https://ld246.com/article/1650080818100

**Comment by Elliootalderson** [comment]
我倒觉得有一个方案. 就是每个月发放一定数量的永久会员(不能太多,比如3个), 在设置菜单里单独放一个位置显示. 显示截至日期.剩余数量.

![image.png](assets/image-20220512201939-wvtt3gi.png)

这种既能满足和促进某些用户想要购买会员的意愿,也不会担心因为数量太多而终生会员送不完的情况.

**Comment by Elliootalderson** [comment]
![image](https://user-images.githubusercontent.com/93273663/168073945-15828b6f-003e-4cab-acc2-bbb2139f6ee9.png)

**Comment by 88250** [comment]
@Elliootalderson 这个活动已经确认要结束的。

**Comment by woaihuangxueying** [comment]
有没有什么新活动吗？
比如做挂件，点赞高者奖励会员啥的

**Comment by netdog2019** [comment]
可以参考quicker，推荐送会员时间，也可以是高赞挂件或者主题之类的增加会员的时间。quicer上那么多人分享动作，其中 一个动机应该就是推荐增加会员时间。

**Comment by 88250** [comment]
@netdog2019 嗯，这个是推荐码的推广作用，但我们还是决定彻底结束这个机制，感谢建议。

**Comment by woniuxia** [comment]
挺好奇D大为啥这么决定？D大方便分享下原因吗？
从我的角度看，取消推荐机制会在一定程度上打击大家推荐的积极性。
能想到的合理解释是，当前订阅量达到一个预期，期望慢下来好好打磨产品。

**Comment by 88250** [comment]
@woniuxia 我个人是比较排斥病毒式营销的，但是产品初期在没有任何种子用户的情况下不得已才出此下策。现在产品已经有一些用户了，这个推广方式也是时候下线了。最近我们正在考虑商业推广方式，比如和专业的渠道商合作。

作为用户就安心使用吧，专心做好笔记。

**Comment by woaihuangxueying** [comment]
结束以后，会发这次活动的成果吗？
就是活动一共持续了多久？一共送出了多少份会员名额？这次活动推广了多少人？

**Comment by 88250** [comment]
@woaihuangxueying 活动持续了半年，以公告时间为准，送出了多少名额现在可以在订阅页看到，推广了多少人不太确定。
