### ISSUE TITLE
块标会和段落竖线重叠

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#4877]
### 描述问题 Describe the problem

块标会和段落竖线会有一点重叠

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/101307399/168211737-4d2b93b1-05cb-4118-8b3b-1ce2cad0ad56.png)

### 版本环境 Version environment

* Version: v2.0.8
* Operating system: Windows 10/11

**Comment by Vanessa219** [comment]
感谢建议，尝试调整了一下，会破坏原有大小的规范。
鉴于目前不影响使用，暂不进行修改。

**Comment by Temacc0531** [comment]
也许可以把块标稍微右移一点，竖线刚好在两个块标中间，不改也问题不大，等后续大优化😆
