### ISSUE TITLE
聚焦返回问题

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4882]
https://ld246.com/article/1652421473028?r=88250

**Comment by winter60** [comment]
面包屑也不能跳转哦

**Comment by winter60** [comment]
> 面包屑也不能跳转哦

2.0.9仍然存在哦

**Comment by winter60** [comment]
> > 面包屑也不能跳转哦
> 
> 2.0.9仍然存在哦

诶，好像现在又行了，刚刚点击面包屑，只是高亮block但不能定位光标，现在又可以定位光标了，不知道是什么原因。我先用着，以后再反馈
