### ISSUE TITLE
API  `/api/block/updateBlock` 更新文档块为空的问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4884]
刚刚有朋友发现了一个问题 [删除文档内容 · Issue #47](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/issues/47), 使用该 API 更新文档块时, 如果请求体 `data` 字段设置为空字符串 `""` 或者只有换行符 `"\n"` `"\n\n"` 的字符串, 如果该文档已经在编辑器中打开, 那么被更新的文档 DOM 会如下所示, 一个块都没有
```html
<div class="protyle-wysiwyg protyle-wysiwyg--attr" spellcheck="false" contenteditable="true" style="padding: 16px 96px 380.5px;" data-doc-type="NodeDocument"></div>
```
关闭该文档后再重新打开又出现了两个空的段落块

---
但是空文档块应该存在一个空的段落块, 如下所示
```html
<div class="protyle-wysiwyg protyle-wysiwyg--attr" spellcheck="false" contenteditable="true" data-doc-type="NodeDocument" style="padding: 16px 96px 380.5px;">
  <div data-node-id="20220513185535-5uuae2l" data-node-index="0" data-type="NodeParagraph" class="p" updated="20220513185535">
    <div contenteditable="true" spellcheck="false"></div>
    <div class="protyle-attr" contenteditable="false">​</div>
  </div>
</div>
```

_Originally posted by @Zuoqiu-Yingyi in https://github.com/siyuan-note/siyuan/issues/4165#issuecomment-1125934259_

**Comment by Zuoqiu-Yingyi** [comment]
貌似这个问题没有完全修复

请求体:
```json
{
    "id": "20201121212605-9td1a62",
    "dataType": "markdown",
    "data": ""
}
```

请求后显示正常(文档中只有一个空的段落), 但是关闭该文档后重新打开, 会出现两个空段落
![image](https://user-images.githubusercontent.com/49649786/168646944-710a4d8a-6791-4d85-b227-55af2ffb7a38.png)

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 下个版本处理，就不单独开 issue 了。
