### ISSUE TITLE
希望以后可以增加内置函数

### ISSUE THREAD

**Issue by szy854136968** [siyuan-note/siyuan#4886]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

实现页面动态变化时。

### 描述可能的最优解决方案 Describe the optimal solution

可以加入像Notion那样内嵌在内容里的函数的功能。
这样可以实现很多有用的功能啊，比如当天距离某天还剩多少天什么的。
现在用模板的话只能插入静态的时间。

**Comment by 88250** [comment]
这个计划通过挂件机制进行扩展，也可以考虑使用 HTML 块，可以执行 JavaScript。
