### ISSUE TITLE
视频块、音频块回车无法换行

### ISSUE THREAD

**Issue by AdachiQ** [siyuan-note/siyuan#4892]
### 描述问题 Describe the problem
在视频块、音频块上回车无法换行，会弹出菜单。

### 期待的结果 Expected result
希望能够和其他块一样，回车直接换行，到下一个块，这样方便用quicker动作插入多个视频、音频。

### 版本环境 Version environment

* Version: 
* Operating system: 
* Browser (if used):

**Comment by 88250** [comment]
选中以后用 Ctrl+Shift+A 就可以了。
