### ISSUE TITLE
数学公式块渲染错误

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#4894]
### 描述问题 Describe the problem

添加数学公式块，来显示多行数学公式，并添加编号，要渲染的公式内容：

> $$
\begin{eqnarray*}
x^n+y^n &=& z^n \tag{1.4} \\
x+y &=& z \tag{1.5} 
\end{eqnarray*}
$$

在typora和[latex](https://www.latexlive.com/##)验证没问题。如下所示：

<img width="994" alt="image" src="https://user-images.githubusercontent.com/33319484/168415010-650d7909-4b09-4316-bc94-8194e930c3de.png">

思源提示：
<img width="752" alt="image" src="https://user-images.githubusercontent.com/33319484/168414817-a83722ce-2979-42fd-8d7c-0f290b4fec26.png">

### 期待的结果 Expected result

能正确解析和显示公式

### 版本环境 Version environment

* Version: 思源2.0.8
* Operating system: MacOs 11.6
* Browser (if used):

**Comment by 88250** [comment]
[KaTex](https://katex.org/) 可能不支持该语法。

![image](https://user-images.githubusercontent.com/873584/168415184-dd83d324-ac2d-40ca-b4d4-629281c0959a.png)

**Comment by JokeenZhang** [comment]
Github渲染，显示少了个反斜杠，我改用代码块，直接复制代码块的内容

**Comment by JokeenZhang** [comment]
它是支持这个语法的。

**Comment by 88250** [comment]
好像不行：

![image](https://user-images.githubusercontent.com/873584/168415331-dad5889a-4541-4dc6-bb25-79718a916037.png)

**Comment by JokeenZhang** [comment]
好的。
