### ISSUE TITLE
下载主题时，出现无法新建页面情况

### ISSUE THREAD

**Issue by flzq** [siyuan-note/siyuan#4895]
### 描述问题 Describe the problem
当时在集市中下载主题，点击下载后，我就回到页面中编辑，在新建页面时出现如图所示情况

### 期待的结果 Expected result
不知道是偶然情况，还是下载主题的问题

### 截屏或者录屏演示 Screenshot or screen recording presentation
![H2%0B0IC09X W22(ZKRKA F](https://user-images.githubusercontent.com/14370681/168415517-956cefde-e830-4b5d-b124-13137207afda.jpg)

### 版本环境 Version environment

* Version: v2.0.8
* Operating system: win10
* Browser (if used):

**Comment by 88250** [comment]
请打包上传日志文件。

**Comment by 88250** [comment]
我这里重现不了问题，麻烦再试试，如果能重现请继续跟帖，先关闭了，感谢理解。

**Comment by flzq** [comment]
> 请打包上传日志文件。
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8697334/siyuan.log)

这个是日志文件吧？在工作空间/temp/下的

**Comment by 88250** [comment]
请更新到最新版以后再试试。
