### ISSUE TITLE
建议新增->转换为→

### ISSUE THREAD

**Issue by pky2006** [siyuan-note/siyuan#4897]
### 在什么情况下你需要该特性？ In what scenarios do you need this feature?

写笔记的时候，经常需要用→来表达因果关系，有时候写英文笔记时，不太方便切换为中文输入法来输入「→」等箭头。

### 描述可能的最优解决方案 Describe the optimal solution
其他笔记软件（如 我来wolai）能自动把->转换为→。

为避免误触发，可以输入`-> /-》`+空格时就自动转换为`→`，其他箭头如此类推（如`<-`转换为`←`）。

**Comment by Zuoqiu-Yingyi** [comment]
切换为支持连字的字体即可, 例如更纱黑体 [be5invis/Sarasa-Gothic: Sarasa Gothic / 更纱黑体 / 更紗黑體 / 更紗ゴシック / 사라사 고딕](https://github.com/be5invis/Sarasa-Gothic)

**Comment by Elliootalderson** [comment]
->需要切换shift键, 而且'-'和'>' 离得挺远的, 个人建议 '>>>' 实现 ➡;

**Comment by 88250** [comment]
感谢提议，但输入侧主要靠输入法解决，比如搜狗输入法：

![image](https://user-images.githubusercontent.com/873584/168425002-71c0053e-f85a-4275-9671-bd1cbdceadab.png)

**Comment by Elliootalderson** [comment]
直接用':'+emoji名称
![image](https://user-images.githubusercontent.com/93273663/168425146-c74099a7-a955-4366-9e87-cc7db2d34c5b.png)
