### ISSUE TITLE
块引锚文本支持模板变量

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#490]
例如 ((20201105161628-4vktwyt "{{.text}}")) ，那么显示出来的文本始终是20201105161628-4vktwyt 的文本。20201105161628-4vktwyt 修改了，这边引用显示的地方一起变。

如果使用 {{.title}} 则使用该内容块直接上级标题（如果有）或者是文档名（如果没有上级标题时直接使用文档名）。

**Comment by 88250** [comment]
![思源笔记锚文本模板使用演示](https://user-images.githubusercontent.com/873584/101277527-0de93c80-37f0-11eb-888c-9a9e1abb8632.gif)
