### ISSUE TITLE
数据历史文档和资源文件支持分页和搜索

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4901]
https://ld246.com/article/1652532948810

### 数据库设计

单独建立 FTS 全文索引数据库 history.db，包含一张表 `history_fts_case_insensitive`，列字段如下：

* type：0：文档，1：资源文件
* op：操作，sync/delete/clean/format
* title：文档标题或者资源文件名
* content：文档正文文本
* path：对应文件 history 文件夹下的相对路径
* created：历史创建时间

### 索引时机

* 生成数据历史文件后插入表数据
* 清理数据历史时删除表数据
* 数据历史界面提供重建索引按钮用于重建表

### 界面交互

数据历史文档和资源文件页签合并为数据历史页签，顶部加入分页搜索栏。

**Comment by 88250** [comment]
数据历史中数据快照已经支持分页，已有的文档、资源、已删除的笔记本这三个暂时不考虑支持了，后面会逐步切换到新的同步机制上 https://github.com/siyuan-note/siyuan/issues/5142

**Comment by Zuoqiu-Yingyi** [comment]
最好还支持查看某个文档的历史:heart:

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 理论上用搜索应该能看

**Comment by mozhux** [comment]
最好能加上某个块的历史

**Comment by 88250** [comment]
@mozhux 块历史估计加不了。

**Comment by Zuoqiu-Yingyi** [comment]
> @mozhux 块历史估计加不了。

@88250 能支持通过块ID搜索嘛, 感觉这个应该比较容易实现

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 历史数据没有分块索引。

**Comment by Zuoqiu-Yingyi** [comment]
> @Zuoqiu-Yingyi 历史数据没有分块索引。

那么通过文档 ID 过滤文档可以支持吗, 我今天使用文档名过滤时发现也匹配了不少其他文档(关键字命中了这些文档的内容)

**Comment by 88250** [comment]
已经在 https://github.com/siyuan-note/siyuan/issues/6257 中添加过滤选项。
