### ISSUE TITLE
多个BUG与建议

### ISSUE THREAD

**Issue by Faith-YSQ** [siyuan-note/siyuan#4907]
1、当用户是全新安装的思源笔记时（原SiYuan文件夹也删除）下载恢复数据会出现下图状况
<img width="900" alt="Snipaste_2022-05-15_10-30-48" src="https://user-images.githubusercontent.com/66512309/168455066-f9947e02-11f0-4a30-b45a-596ed8760279.png">
2、当新建一个页面时，添加图标会导致标签页标题消失，重新打开页面可恢复
3、默认主题，表格的头两行都会有类似表头的底色。望优化
5、建议：取消表格的colgroup标签，这个标签在表格里，表格设置100%宽度好像好像会没有用，表格设置样式变复杂了。

https://user-images.githubusercontent.com/66512309/168455141-fa51d1c0-fcf4-4953-84e4-bbc31896b150.mp4

**Comment by 88250** [comment]
1. 在 https://github.com/siyuan-note/siyuan/issues/4908 修复
2. 在 https://github.com/siyuan-note/siyuan/issues/4883 修复
3. 这个目前是设计如此
   ![image](https://user-images.githubusercontent.com/873584/168456218-c7046425-bba4-4341-8335-0fc081bb5bab.png)
4. colgroup 用于单元格合并

感谢反馈。
