### ISSUE TITLE
窗口最大化关闭按钮问题

### ISSUE THREAD

**Issue by LiWenGu** [siyuan-note/siyuan#491]
![image](https://user-images.githubusercontent.com/15909210/99024790-46f01180-25a2-11eb-9453-c46b61b98ce7.png)
如图，我没法直接让思源最小化

**Comment by 88250** [comment]
在 Windows 上失去焦点以后颜色不太对劲： 

![image](https://user-images.githubusercontent.com/873584/99180473-92045300-2761-11eb-938c-93ae312483f2.png)

**Comment by Vanessa219** [comment]
问一下是怎么重现的

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/491#issuecomment-727535648 在 0.4.9 中已解决

**Comment by 88250** [comment]
@LiWenGu 如果方便地话，请升级到 v0.4.9 再帮忙看看问题是否已经修复，谢谢！

**Comment by Vanessa219** [comment]
为了方便 issue 整理，我先将其关闭，如果还能复现的话还麻烦再打开。

**Comment by LiWenGu** [comment]
https://markdownnoteimages.oss-cn-hangzhou.aliyuncs.com/QQ20201124-142803-HD.mp4
仍然复现上面是视频，版本是0.491
