### ISSUE TITLE
当多个块成为一个超级快时. 无法调整超级快的布局.

### ISSUE THREAD

**Issue by Elliootalderson** [siyuan-note/siyuan#4913]
![image](https://user-images.githubusercontent.com/93273663/168481130-e284fcc0-7e09-4961-ac78-a67f906ec8cb.png)
当多个块成为一个超级快时. 无法调整超级快的布局.
只能居左

**Comment by Elliootalderson** [comment]
我记得以前的版本时可以的

**Comment by Vanessa219** [comment]
可以居右和居中的
<img width="839" alt="image" src="https://user-images.githubusercontent.com/970828/168503552-ec783445-9eaa-4d9f-9cdc-4749dce9f41c.png">

**Comment by Elliootalderson** [comment]
当`超级快中的三个子块的长度加起来没有100%时,是只能居左的,你看我的超级快和你发的, 明显不一样.

**Comment by Elliootalderson** [comment]
以前的版本三个子块如果宽度没有33%. 居中的时候会相互分开,而现在只能居左
