### ISSUE TITLE
当多个块成为一个超级快时. 子块的宽度不够填满超级块时, 无法调整超级快的整体布局

### ISSUE THREAD

**Issue by Elliootalderson** [siyuan-note/siyuan#4915]
![image](https://user-images.githubusercontent.com/93273663/168510443-f51f8dc7-b238-43ce-9bd9-e97326ac4c62.png)
当三个快的宽度不满足33%时, 以前的版本居中可以相互分开. 现在只能居左
![image](https://user-images.githubusercontent.com/93273663/168510743-513c691c-b706-48dc-85c2-6e1db199b8e3.png)

**Comment by Vanessa219** [comment]
这部分没有做过处理，是不是用了其他的主题。默认主题下个版本会对此进行改进。
