### ISSUE TITLE
面包屑改进：`Click` 为聚焦，聚焦返回文案修改

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#4916]
![222](https://user-images.githubusercontent.com/38906705/168516994-9a1e9a25-572c-4b43-8484-4f1a306c6983.gif)

**Comment by Vanessa219** [comment]
这个是考虑文档已经加载过了，只要定位下就行，省的用户点来点去的。在实际使用过程中，你觉得是定位好呢，还是聚焦比较好？

**Comment by fanglypro** [comment]
> 这个是考虑文档已经加载过了，只要定位下就行，省的用户点来点去的。在实际使用过程中，你觉得是定位好呢，还是聚焦比较好？

这两者不冲突呀，鼠标放上去是定位，点击是聚焦，以前版本不是都这么设计的吗？

**Comment by tcmtom** [comment]
支持点击后聚焦

**Comment by fanglypro** [comment]
> @royc01 @tcmtom 那点击就修改为进行聚焦吧 @fanglypro 以前的版本是鼠标移上去高亮，点击没有对内容是否加载进行业务的细化。这不是一个bug，是特性哦。

我试了2.0.6，是有这个功能的，鼠标点击后是聚焦，应该是2.0.6之后的某个改动导致这个功能失效了，我以前经常用这个功能的，应该说的是同一个功能吧:joy:

![temp238](https://user-images.githubusercontent.com/57083732/169273959-3b8b09e6-860c-441e-94c5-d5598e281dd4.gif)

**Comment by winter60** [comment]
@Vanessa219 其实聚焦不聚焦对我来说还好，主要是想通过面包屑能够定位块。目前好像只能高亮，进入聚焦块后面包屑才能定位返回上级，回到非聚焦块状态就不能定位了。

**Comment by Zuoqiu-Yingyi** [comment]
现在点击后不能聚焦嘛，我这里怎么可以呀❓

**Comment by CleinBlue** [comment]
我个人倒是觉得维持现有的逻辑不错，即点击高亮。因为有时不需要聚焦，可以设置为`某个按键+点击=聚焦吗？`，也希望有更多意见。

**Comment by winter60** [comment]
> 我个人倒是觉得维持现有的逻辑不错，即点击高亮。因为有时不需要聚焦，可以设置为`某个按键+点击=聚焦吗？`，也希望有更多意见。

妙啊，和原来风格一样了。移动到面包屑时为高亮，点击时为定位，ctrl+点击为聚焦块。

**Comment by Vanessa219** [comment]
@fanglypro 对，前面说过了，加了一个特性：内容块在当前编辑器中就进行高亮，否则才进行缩放。

**Comment by Vanessa219** [comment]
@winter60 定位在这个版本中再添加一下。

@Zuoqiu-Yingyi 因为你点击的面包屑的块没有显示在文档中

**Comment by fanglypro** [comment]
> @fanglypro 对，前面说过了，加了一个特性：内容块在当前编辑器中就进行高亮，否则才进行缩放。

但是现在这个版本中，内容块在当前编辑器中也可能会缩放，比如下面这个动图中，`6`这个列表项已经加载了，我点击后依然会聚焦。

![temp239](https://user-images.githubusercontent.com/57083732/169453687-f478296f-1c2f-4940-829c-555b5d4cffc7.gif)

编辑器聚焦在文档块和非文档块时的面包屑的交互逻辑是不同，逻辑上感觉有点混乱。

貌似是这个新特性只对当前聚焦在文档块时有效，但对当前聚焦在非文档块时并不有效，两者没有统一，这个issue会对两者的交互逻辑进行统一么？

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 我认为文档面包屑与悬浮窗面包屑的行为应该统一, `click` 在悬浮窗面包屑的行为是聚焦, `Ctrl + click` 在悬浮窗面包屑的行为是跳转, 那么文档的面包屑也应保持一致

**Comment by Vanessa219** [comment]
@Zuoqiu-Yingyi 悬浮窗的面包屑需要展开为页签，因此 Ctrl+Click 是打开新的页签并聚焦，对于页签也说也就是聚焦，加之块标的聚焦也是 ctrl +click。因此还是按照楼上的建议进行修改。

@fanglypro 这个没太注意，会统一逻辑的。

**Comment by fanglypro** [comment]
> @Zuoqiu-Yingyi 悬浮窗的面包屑需要展开为页签，因此 Ctrl+Click 是打开新的页签并聚焦，对于页签也说也就是聚焦，加之块标的聚焦也是 ctrl +click。因此还是按照楼上的建议进行修改。
> 
> @fanglypro 这个应该是 bug，会统一逻辑的。

现在悬浮窗的面包屑在 Ctrl+Click 的时候并不一定是打开新的页签并聚焦，也可能是打开新的页签并跳转（高亮并定位），如图：

![temp240](https://user-images.githubusercontent.com/57083732/169465447-9a397bcb-b0a0-45ff-b8a5-1874d45635e6.gif)

这部分的逻辑有点混乱，我建议click功能统一按照大纲软件的普遍用法，设置为聚焦，用户的习惯也更容易统一，ctrl+click功能可以设置为其他思源特色的功能。

**Comment by Vanessa219** [comment]
好的，那就还是和以前保持一致。

**Comment by fanglypro** [comment]
> 好的，那就还是和以前保持一致。 还想再请教一下聚焦返回。是应该返回当前块的父亲层，还是返回当前面包屑的上一层呢？比如下图，列表项4的聚焦返回到列表项2还是列表项 f1d 上要好一点呢？ <img alt="image" width="498" src="https://user-images.githubusercontent.com/970828/169468463-8e52e61b-04b1-4d52-a49a-84308590764e.png">

聚焦返回是指`alt+←`么

这个聚焦返回功能应该是和聚焦、复制、折叠展开这些功能对应，是块级别的，应当以该块为中心进行操作，所以，列表项4的聚焦返回在逻辑上应该是到列表项2。

“返回当前面包屑的上一层”这个应该是文档级别的操作了，对一个块无法感知到当前文档的面包屑聚焦在哪里，用户如果想做这个操作应当点击面包屑比较合适。

或者说，如果有“返回当前面包屑的上一层”这个功能的快捷键，应当单独再设置一个全局快捷键，而不是使用针对某个块的快捷键。

**Comment by Vanessa219** [comment]
面包屑还需要改进成 IDE 这样可用鼠标/键盘操作的。目前就先把文案改为“聚焦到上级”吧，谢谢。
<img width="400" alt="image" src="https://user-images.githubusercontent.com/970828/169521134-e7f4a6b0-9586-4351-b6c0-3f9efc4d98bc.png">
