### ISSUE TITLE
引述块下删除列表触发状态异常

### ISSUE THREAD

**Issue by Strelitzia-Reginae-Aiton** [siyuan-note/siyuan#4918]
### 描述问题 Describe the problem

在Consice Light主题下，在引述块中建立任务列表/无序列表（此时引述块中只有任务列表/无序列表）后，删除任务列表/无序列表会导致引述块无法输入内容，一定时间后系统会自动报错（即使撤销也会发生）

### 期待的结果 Expected result

解决在引述块中删除内容后将引述块整体删除

### 截屏或者录屏演示 Screenshot or screen recording presentation

创建引述块并创建任务列表

![image](https://user-images.githubusercontent.com/101028182/168580520-cf57addc-6585-4b23-b25b-e0a3bfd025b1.png)

清空引述块中的内容

![image](https://user-images.githubusercontent.com/101028182/168580754-91bb7379-c621-4279-8c44-e6fc7c4b037d.png)

一段时间后/撤销后系统提示

![image](https://user-images.githubusercontent.com/101028182/168580836-92a07010-dc1c-4553-ae83-56c351b280fc.png)

### 版本环境 Version environment

* Version: 2.0.9
* Operating system: Windows 10 家庭中文版 21H2 内部版本：19044.1706

### 日志文件 Log file

I 2022/05/16 18:05:04 sync.go:177: set sync interval to [16m]
I 2022/05/16 18:21:04 sync.go:177: set sync interval to [32m]
I 2022/05/16 18:44:06 sync.go:240: sync [cloud=47574, local=47575] uploaded in [0.82s]
I 2022/05/16 18:44:06 sync.go:248: set sync interval to [5m]
I 2022/05/16 18:49:07 sync.go:177: set sync interval to [8m]
E 2022/05/16 19:06:43 transaction.go:919: get node [20220330234403-iqox5pc] in tree [20220218115631-19yb9ef] failed
I 2022/05/16 19:06:45 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 19:06:45 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=141 kB]
I 2022/05/16 19:06:47 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.13s], tree stat [count=175, size=3.9 MB]
I 2022/05/16 19:06:47 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.22s], tree stat [count=8, size=841 kB]
I 2022/05/16 19:06:48 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [0.98s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 19:06:48 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.24s], tree stat [count=47, size=466 kB]
I 2022/05/16 19:06:48 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.09s], tree stat [count=23, size=547 kB]
I 2022/05/16 19:06:49 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.02s], tree stat [count=6, size=66 kB]
I 2022/05/16 19:06:49 index.go:191: resolving refs...
I 2022/05/16 19:06:49 index.go:318: resolved refs [195]
E 2022/05/16 19:07:06 transaction.go:823: not found previous block [id=]
I 2022/05/16 19:07:09 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 19:07:09 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=133 kB]
I 2022/05/16 19:07:10 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.06s], tree stat [count=175, size=3.9 MB]
I 2022/05/16 19:07:10 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.18s], tree stat [count=8, size=841 kB]
I 2022/05/16 19:07:11 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [0.99s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 19:07:12 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.22s], tree stat [count=47, size=466 kB]
I 2022/05/16 19:07:12 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.09s], tree stat [count=23, size=547 kB]
I 2022/05/16 19:07:12 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.02s], tree stat [count=6, size=66 kB]
I 2022/05/16 19:07:12 index.go:191: resolving refs...
I 2022/05/16 19:07:12 index.go:318: resolved refs [189]
E 2022/05/16 19:14:07 transaction.go:919: get node [20220516191142-41i1jjm] in tree [20220516191142-xtyyhmc] failed
I 2022/05/16 19:14:45 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 19:14:45 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=134 kB]
I 2022/05/16 19:14:46 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.11s], tree stat [count=176, size=3.9 MB]
I 2022/05/16 19:14:47 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.19s], tree stat [count=8, size=841 kB]
I 2022/05/16 19:14:48 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [1.02s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 19:14:48 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.23s], tree stat [count=47, size=466 kB]
I 2022/05/16 19:14:48 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.10s], tree stat [count=23, size=547 kB]
I 2022/05/16 19:14:48 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.02s], tree stat [count=6, size=66 kB]
I 2022/05/16 19:14:48 index.go:191: resolving refs...
I 2022/05/16 19:14:48 index.go:318: resolved refs [193]
I 2022/05/16 19:16:59 working.go:86: 

I 2022/05/16 19:16:59 runtime.go:33: kernel is booting:
    * ver [2.0.9]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [C:\Users\fohn\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\D\Siyuan, data 150 MB]
I 2022/05/16 19:16:59 serve.go:68: kernel is booting [http://127.0.0.1:6806]
I 2022/05/16 19:16:59 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 19:16:59 sync.go:93: sync before boot
I 2022/05/16 19:17:01 sync.go:251: sync [cloud=47575, local=47829, wroteFiles=7, transferSize=218 kB] uploaded in [1.30s]
I 2022/05/16 19:17:01 conf.go:493: pre-init database size [4.1 kB]
I 2022/05/16 19:17:01 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=134 kB]
I 2022/05/16 19:17:03 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.10s], tree stat [count=176, size=3.9 MB]
I 2022/05/16 19:17:03 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.22s], tree stat [count=8, size=841 kB]
I 2022/05/16 19:17:04 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [1.03s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 19:17:04 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.27s], tree stat [count=47, size=466 kB]
I 2022/05/16 19:17:05 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.15s], tree stat [count=23, size=547 kB]
I 2022/05/16 19:17:05 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.07s], tree stat [count=6, size=66 kB]
I 2022/05/16 19:17:05 index.go:318: resolved refs [193] in [131ms]
I 2022/05/16 19:17:05 conf.go:517: post-init database size [64 MB], tree stat [count=310, size=9.4 MB]
I 2022/05/16 19:17:05 working.go:122: kernel booted
E 2022/05/16 19:17:21 transaction.go:916: get node [20220516191252-nvgjsmy] in tree [20220516191142-xtyyhmc] failed
I 2022/05/16 19:17:23 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 19:17:23 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=134 kB]
I 2022/05/16 19:17:24 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.22s], tree stat [count=176, size=3.9 MB]
I 2022/05/16 19:17:25 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.19s], tree stat [count=8, size=841 kB]
I 2022/05/16 19:17:26 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [1.05s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 19:17:26 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.21s], tree stat [count=47, size=466 kB]
I 2022/05/16 19:17:26 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.10s], tree stat [count=23, size=547 kB]
I 2022/05/16 19:17:26 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.02s], tree stat [count=6, size=66 kB]
I 2022/05/16 19:17:26 index.go:318: resolved refs [193] in [135ms]
I 2022/05/16 19:17:52 sync.go:251: sync [cloud=47829, local=47839, wroteFiles=3, transferSize=49 kB] uploaded in [0.82s]

**Comment by Strelitzia-Reginae-Aiton** [comment]
Siyuan v2.0.3与v2.0.9中均出现该问题

**Comment by 88250** [comment]
请使用默认主题测试看看。

**Comment by Strelitzia-Reginae-Aiton** [comment]
> 

### 截屏演示

![image](https://user-images.githubusercontent.com/101028182/168595816-3a9a4702-5cd0-4de7-b0e0-09a6f72abfe6.png)

删除后
![image](https://user-images.githubusercontent.com/101028182/168595872-dc32105d-8045-4d6a-beb2-2fe80d2bd7a8.png)

撤销后：
![image](https://user-images.githubusercontent.com/101028182/168595950-7422cfa5-7e19-4c19-87e9-d426200f55ef.png)

### 日志

E 2022/05/16 20:45:46 transaction.go:916: get node [20220516192223-rpc1tmc] in tree [20220516191142-xtyyhmc] failed
I 2022/05/16 20:45:49 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 20:45:49 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=134 kB]
I 2022/05/16 20:45:50 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.15s], tree stat [count=176, size=3.9 MB]
I 2022/05/16 20:45:51 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.19s], tree stat [count=8, size=841 kB]
I 2022/05/16 20:45:52 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [1.00s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 20:45:52 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.23s], tree stat [count=47, size=466 kB]
I 2022/05/16 20:45:52 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.09s], tree stat [count=23, size=547 kB]
I 2022/05/16 20:45:52 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.01s], tree stat [count=6, size=66 kB]
I 2022/05/16 20:45:52 index.go:318: resolved refs [194] in [130ms]
E 2022/05/16 20:46:56 transaction.go:820: not found previous block [id=]
E 2022/05/16 20:46:56 transaction.go:963: load tree [id=20220516204612-hyf2r7i] failed: block not found
I 2022/05/16 20:46:58 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 20:46:58 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=134 kB]
I 2022/05/16 20:46:59 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.13s], tree stat [count=176, size=3.9 MB]
I 2022/05/16 20:46:59 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.19s], tree stat [count=8, size=841 kB]
I 2022/05/16 20:47:01 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [1.00s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 20:47:01 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.23s], tree stat [count=47, size=466 kB]
I 2022/05/16 20:47:01 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.10s], tree stat [count=23, size=547 kB]
I 2022/05/16 20:47:01 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.02s], tree stat [count=6, size=66 kB]
I 2022/05/16 20:47:01 index.go:318: resolved refs [194] in [139ms]
E 2022/05/16 20:48:33 transaction.go:820: not found previous block [id=]
I 2022/05/16 20:49:06 sync.go:251: sync [cloud=47907, local=47993, wroteFiles=4, transferSize=67 kB] uploaded in [1.19s]
I 2022/05/16 20:49:36 database.go:72: reinitialized database [C:\D\Siyuan\temp\siyuan.db]
I 2022/05/16 20:49:36 index.go:181: rebuilt database for notebook [20220218115446-11rdqfn] in [0.03s], tree stat [count=12, size=134 kB]
I 2022/05/16 20:49:37 index.go:181: rebuilt database for notebook [20220217211224-gqda1yh] in [1.11s], tree stat [count=176, size=3.9 MB]
I 2022/05/16 20:49:37 index.go:181: rebuilt database for notebook [20220218001309-cvhz2il] in [0.19s], tree stat [count=8, size=841 kB]
I 2022/05/16 20:49:39 index.go:181: rebuilt database for notebook [20220218001325-4ncj3ni] in [1.07s], tree stat [count=38, size=3.4 MB]
I 2022/05/16 20:49:39 index.go:181: rebuilt database for notebook [20220218110059-6l0lf0b] in [0.35s], tree stat [count=47, size=466 kB]
I 2022/05/16 20:49:39 index.go:181: rebuilt database for notebook [20220224184133-0fbdwab] in [0.11s], tree stat [count=23, size=547 kB]
I 2022/05/16 20:49:39 index.go:181: rebuilt database for notebook [20220218111418-s65acwp] in [0.02s], tree stat [count=6, size=66 kB]
I 2022/05/16 20:49:39 index.go:318: resolved refs [194] in [131ms]

**Comment by 88250** [comment]
麻烦录屏演示一下操作步骤，谢谢。

**Comment by Strelitzia-Reginae-Aiton** [comment]
https://user-images.githubusercontent.com/101028182/168775589-e39513eb-e794-4c3f-865e-296ca0861055.mp4

在删除后，只要不与该界面产生交互，则不会产生错误，目前在删除后打开文档树、大纲、进入设置页面、打开其它文档均不会产生任何错误信息，直到与该页面发生交互（包括但不限于Ctrl+Z与鼠标左键单击）

**Comment by 88250** [comment]
感谢帮忙，已经确认问题，近期版本进行修复。
