### ISSUE TITLE
建议新增以下批量选中及加工功能，便于后期写作输出

### ISSUE THREAD

**Issue by iforucc** [siyuan-note/siyuan#492]
真的很喜欢思源笔记，很早就买了终身买断，希望能越做越好，不仅能前期积累输入，后期又能方便写作输出。花了好几个小时试着来表述需求，不知是否表述清楚了，如果需要进一步沟通，可联系我。
1.支持在左侧文件树栏和搜索结果栏中可以批量选中部分或全部的笔记。
![1](https://user-images.githubusercontent.com/38482156/99020442-9c73f080-2599-11eb-951a-e0fe2e65bfe7.png)
2.可将上述选中的笔记一键以卡片（悬浮编辑框）方式显示，卡片笔记可使用鼠标自由拖拽、移动和排列。
![2](https://user-images.githubusercontent.com/38482156/99022956-8fa5cb80-259e-11eb-8d37-b55ddd14d5cd.png)
3.可在思源中新建一个项目，项目可视为笔记的容器，用鼠标点击或框选批量选中上面排列好的卡片笔记，拖拽至项目窗口，卡片自动拼接成长文，拼接的顺序按照被拖进项目窗口的先后，如果是被批量选中同时拖进项目的，按照之前选中时的排列方式（建议先从上往下，再从左往右）。同时，批量选中的卡片笔记，除拖动到项目外，也能拖拽到word拼卡成文。
![3](https://user-images.githubusercontent.com/38482156/99025295-79e6d500-25a3-11eb-8bbf-123f5a05334e.png)

**Comment by 88250** [comment]
感谢支持和建议，卡片式的交互估计要等以后才会考虑，目前还在集中精力做计划的特性。

卡片用法方面，目前建议是使用块引来做组合输出，虽然不是拖拽的交互方式，但是最终输出结果也应该没问题 🙏
