### ISSUE TITLE
在火狐浏览器中访问web，会出现额外的滑块

### ISSUE THREAD

**Issue by ssfdust** [siyuan-note/siyuan#4927]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在火狐浏览器中访问web，会出现额外的滑块

https://user-images.githubusercontent.com/3088610/168738488-c1b9661d-f1c5-4169-8a42-370b94564c8e.mp4

### 期待的结果 Expected result

没有多余的滚动条

我现在使用了stylus临时解决了这个问题

```
body {
    scrollbar-color: rgba(150, 150, 150, 0.5) transparent
}

#layouts > .fn__flex:last-child {
    display: none
}
```

### 版本环境 Version environment

```markdown
- Version: 2.0.7
- Operating System: Archlinux
- Browser (if used): Firefox
```

### 日志文件 Log file

无需

**Comment by 88250** [comment]
请更新到最新版后看下是否问题还存在。

**Comment by ssfdust** [comment]
确认已修复，感谢。
