### ISSUE TITLE
展开面板时出现滚动条抖动

### ISSUE THREAD

**Issue by kecrily** [siyuan-note/siyuan#4931]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Jitter when folding the sidebar. A scrollbar will appear, which makes the excess unnatural

### 期待的结果 Expected result

No scrollbar

### 截屏或者录屏演示 Screenshot or screen recording presentation

![collapse](https://user-images.githubusercontent.com/45708948/168780004-d2fe19ca-30b6-4f6b-b6d1-442eed9057ff.gif)

### 版本环境 Version environment

```markdown
- Version: v2.0.9
- Operating System: Windows
- Browser (if used):
```

### 日志文件 Log file

N/A

### 更多信息 More information

Just add `overflow-x: hidden;` attribute to `.fn__flex-1`

**Comment by Vanessa219** [comment]
这个动画效果在由窄变宽的过程中，在窄的地方出现滚动条是正常的。如果把 overflow-x: hidden; 驾到 .fn__flex-1 上，其他地方会有更多的问题。因为 fn__flex-1 在非常多的地方使用到。
