### ISSUE TITLE
状态栏显示选中内容的字数

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#4932]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

看选中部分有多少字

### 描述可能的最优解决方案 Describe the optimal solution

不知道

### 描述候选的解决方案 Describe the candidate solution

不知道

**Comment by lisontowind** [comment]
在右上角三个点打开可以查看块字数，但是只能以块为单位

**Comment by aptexd** [comment]
请问“字数”和“词数”有什么区别，是通过什么形式区分的

**Comment by 88250** [comment]
@aptexd 字数指的是字符数，词数是空格或者字母数字分隔。
