### ISSUE TITLE
模版失效，报错error calling queryBlocks: interface conversion

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#4933]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

ME模板中的find-recent-7day.md，以前一直正常运行，现在报错
find-recent-7day.md 文件内容如下
`## .action{ now | date "2006-01-02 Mon "} 7天内更新的文档

.action{$from := (now | date_modify "-144h") | date "20060102"}
.action{$to := (now | date_modify "+24h") | date "20060102"}

.action{$blocks :=queryBlocks "SELECT * FROM blocks WHERE id in (SELECT root_id FROM blocks WHERE (updated >= '?' AND updated <= '?' AND root_id != '?')) order by updated DESC Limit 10000" $from $to .id}

.action{range $b := $blocks}
📙 ((.action{$b.RootID} ".action{ trimPrefix "/" $b.HPath}"))
.action{end}
`

运行时报错：
模板解析失败：template: :7:18: executing "" at <queryBlocks "SELECT * FROM blocks WHERE id in (SELECT root_id FROM blocks WHERE (updated >= '?' AND updated <= '?' AND root_id != '?')) order by updated DESC Limit 10000" $from $to .id>: error calling queryBlocks: interface conversion: sqlparser.Expr is *sqlparser.Subquery, not *sqlparser.SQLVal

### 期待的结果 Expected result

希望指导怎么修改模版，使之正常运行。

### 版本环境 Version environment

```markdown
- Version: 1.9.8
- Operating System:  Win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8712395/siyuan.log)

**Comment by 88250** [comment]
升级到最新版再试试，如果没有问题请关闭，谢谢。
