### ISSUE TITLE
文档树文件夹吸顶展示

### ISSUE THREAD

**Issue by langzhou** [siyuan-note/siyuan#4934]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

<img width="367" alt="WX20220518-092228@2x" src="https://user-images.githubusercontent.com/6987229/168938163-68e30f0b-7390-4f51-afe8-2e9c57e02db0.png">

如图所示，当某个文件夹（父文档）下面的文档很多时，展开时页面会很高。这时如果我想快速折叠该文件夹，就必须滚动很久才能定位到文件夹。

### 描述可能的最优解决方案 Describe the optimal solution

希望文件夹展开时，在滚动的时候，文件夹能够吸顶固定不动，直到滚动到该文件夹底部。

### 描述候选的解决方案 Describe the candidate solution

增加快捷键折叠当前选中文档的文件夹

**Comment by Vanessa219** [comment]
这个难度有点大，我看 IDE 是左键回到父亲节点，这样可好？

**Comment by langzhou** [comment]
> 这个难度有点大，我看 IDE 是左键回到父亲节点，这样可好？#4852

嗯嗯，可以的

**Comment by Vanessa219** [comment]
那我就先关闭这个 issue 了
