### ISSUE TITLE
data目录下的图片文档里删除了，但是图片文件不会清除

### ISSUE THREAD

**Issue by cod-soap** [siyuan-note/siyuan#4937]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我发现笔记上的图片文件保存在这个目录:\notes\data\assets
但是我在某个笔记里面贴了一个截图，我去掉这个截图后，在这个目录还有图片文件，
甚至我删除了这个笔记，并且这设置-->清空所有历史 之后，我贴的这个图片还是在这个目录。

此外还有一个改进建议：贴图按照目录分类，这样也更好管理一点

### 期待的结果 Expected result

图片文件删除或者情况所有历史后，图片不保存到该目录

### 版本环境 Version environment

```markdown
- Version:  v2.0.7  window客户端
- Operating System: win10 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by isyngo** [comment]
可查阅`用户指南——请从这里开始——通用操作——资源文件`的内容

**Comment by cod-soap** [comment]
可以解决我的问题，感谢！
