### ISSUE TITLE
内容块嵌入触发存在问题

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#494]
![KO8}S8SK FNN`S~UF~6PESA](https://user-images.githubusercontent.com/28727933/99037669-1ec2db80-25bf-11eb-8765-af3999cbd141.png)
我每次这样不行，!(( 后生成的如下图
![92NCO2}WG1U9BX)OIXI XIX](https://user-images.githubusercontent.com/28727933/99037672-208c9f00-25bf-11eb-9906-13ee35bd0119.png)
要再去将!删掉重输入一次才行

**Comment by 88250** [comment]
能录个屏吗？

**Comment by 2234839** [comment]
> 
> 
> 能录个屏吗？

https://store-llej.oss-cn-hangzhou.aliyuncs.com/%E6%9D%82%E9%A1%B9/%E6%80%9D%E6%BA%90%E7%AC%94%E8%AE%B0%E5%B5%8C%E5%85%A5%E5%9D%97bug.mp4

**Comment by 88250** [comment]
选择以后回车即可，我关闭了，谢谢。
