### ISSUE TITLE
折叠起来的条目希望有更明显的标志

### ISSUE THREAD

**Issue by meizilp** [siyuan-note/siyuan#4944]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

条目不折叠占可视面积太大，折叠了又不用看出来被折叠了（目前只是灰显）

### 描述可能的最优解决方案 Describe the optimal solution

在条目前部增加一个下拉图标？

**Comment by 88250** [comment]
麻烦截图看下。

**Comment by netdog2019** [comment]
这是由主题设置的吧？换个主题就可以了。

**Comment by 88250** [comment]
先关闭了，如果有补充请随时跟帖，谢谢。
