### ISSUE TITLE
定位打开的文档增加快捷键设置

### ISSUE THREAD

**Issue by meizilp** [siyuan-note/siyuan#4945]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

今天的日记经常要参考昨天的，这个时候就要定位今天的，然后去找到昨天的，目前只能用鼠标去点击，不方便。

### 描述可能的最优解决方案 Describe the optimal solution

在快捷键设置里面增加支持为此功能设置快捷键

**Comment by isyngo** [comment]
试下搜索功能，没有关键字时会显示最近打开的文档。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/4844
