### ISSUE TITLE
想把双链删掉重新输入进入异常状态

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#4950]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

偶尔会出现想把双链删掉重新输入的时候变成更改锚文本

### 期待的结果 Expected result

区分双链删除与更改锚文本

### 截屏或者录屏演示 Screenshot or screen recording presentation

![F0RB%`ZQ86@A6)@KM$DF0Z](https://user-images.githubusercontent.com/101307399/169253268-ec8112e4-43a5-4d2a-adc7-7ab7f29e1d45.png)

### 版本环境 Version environment

```markdown
- Version: v2.0.11
- Operating System: Windows 10/11
```

### 更多信息 More information

这个缺陷无法稳定复现，一段时间可能会偶尔出现一下，如果无法解决可以继续观察，这里暂先留个记录

**Comment by 88250** [comment]
修改锚文本最好用右键菜单修改，直接改的话行级元素左右边界不一定能正确处理，这个问题暂时忽略，以后如果有空再统一改进，感谢反馈。

**Comment by Temacc0531** [comment]
这个我本意不是要修改锚文本的，我是要删除那个双链，重新输入`[[`建立新的双链，但是被处理成更改原来那个双链的锚文本

**Comment by 88250** [comment]
能录屏演示一下操作步骤么？

**Comment by 88250** [comment]
暂时不太确定重现步骤，可能是我之前说的行级元素左右边界的问题。

**Comment by Temacc0531** [comment]
嗯嗯，有get到我的意思就好😂，目前虽然碰见几次但概率不高，重新再操作一遍就可以解决

**Comment by Temacc0531** [comment]
https://user-images.githubusercontent.com/101307399/169948571-9ce1923d-74c3-4093-894f-d673e2a3f5b7.mp4

这个可以稳定复现了
首先更正一下，一开始我描述的是双链删掉重新输入会变成更改锚文本，但是现在发现实际不是变成更改锚文本，是进入了一个奇怪状态，和更改锚文本应该没啥联系

视频中
第一次删除双链重新输入：正常的预期情况
第二次删除双链重新输入：界面显示还是正常的，报了第一个错
第三次删除双链重新输入：界面双链进入奇怪状态，报了第二个错

**Comment by 88250** [comment]
@Vanessa219

**Comment by Temacc0531** [comment]
在进入奇怪状态后重建索引，会随机出现两种情况

1. 双链变成下图
![Z S2KUU3}BJK35)FIX6RJP2](https://user-images.githubusercontent.com/101307399/169952792-1411db77-26b5-405e-96be-674a8f1d4fb1.png)
2. 双链恢复到删除前的样子

**Comment by Vanessa219** [comment]
我无法重现，你看一下是否这样操作？

https://user-images.githubusercontent.com/970828/170163221-667fdc87-4fb5-4792-a6c3-b4d2ad92a557.mp4

**Comment by Temacc0531** [comment]
要在删除双链之后马上输入`【【`，动作要快
而且可能和笔记量的大小也有点关系
我输`【`后粘贴是为了避免显示到其他的搜索结果

**Comment by Vanessa219** [comment]
还是无法重现，你用的输入法是？

**Comment by Temacc0531** [comment]
就是微软原生输入法，但是这个操作好像不涉及到输入法。我在v2.0.16尝试了还是可以出现的，好像用notion-dark出现的概率会大一些，你可以尝试一下

**Comment by 88250** [comment]
我这里在 v2.0.24 上重现不了，麻烦使用默认主题测试看看。

**Comment by Temacc0531** [comment]
默认主题尝试会出现视频中的第一个报错。第二个报错不会出现，也不会进入异常状态

**Comment by 88250** [comment]
实在重现不了，我先关闭了，我们会留意类似反馈，谢谢。
