### ISSUE TITLE
桌面端内核进程使用随机端口

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4952]
桌面端环境 `6806` 容易被其他进程占用或者是其他程序的保留端口，应该改进为使用随机端口拉起内核。

* https://github.com/siyuan-note/siyuan/issues/6336
* https://github.com/siyuan-note/siyuan/issues/6337
* https://github.com/siyuan-note/siyuan/issues/6343

可在 设置 - 关于 - 使用固定端口 中开启固定使用 `6806`，不允许手动指定，主要是防止普通用户误输入后下次无法启动。

**Comment by UltramarineSky** [comment]
> 强烈建议在使用随机端口的同时支持用户自定义固定的端口 docker 必须能够自定义端口以进行端口映射，而且我把思源当本地 Web 静态文件服务器与图床使用了😂

希望允许自定义端口

**Comment by leolee9086** [comment]
还是建议保留自定义端口……

**Comment by mdzz2048** [comment]
建议保留自定义端口，目前社区很多Supermemo用户将思源当做本地图床使用：
[思源作为本地图床导入材料至 SuperMemo，以网页为例](https://ld246.com/article/1646449285544/comment/1646489422376#comments)
[如何排除剪藏内容对搜索的影响？](https://ld246.com/article/1647435614636)
如果端口设置为随机端口将失去这个功能，对于Supermemo用户来说是难以接受的……

**Comment by Danielypzhang** [comment]
希望允许自定义端口

**Comment by CleinBlue** [comment]
确实有的用户不知道怎么设置端口，有阻塞的情况。建议是默认随机，可选自定义

**Comment by 88250** [comment]
完全随意不可取，需要允许自定义，但是自定义以后可能会引入新问题，非程序员用户估计难以理解 `监听端口` 的含义。

从目前收到的端口占用问题来看，基本是由于 Hyper-V 保留端口所致，Hyper-V 一般来说非程序员用户不会安装，所以碰到端口占用的概率较低。

我们改一下那个报错弹框吧，把[处理方案](https://github.com/siyuan-note/siyuan/issues/2565?utm_source=ld246.com#issuecomment-986257137)加进去：

```
net stop winnat
netsh interface ipv4 add excludedportrange protocol=tcp startport=6806 numberofports=1
net start winnat
```

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/4957

**Comment by UltramarineSky** [comment]
手机上有时候也会出现端口被占用，能否允许自定义

**Comment by 88250** [comment]
@UltramarineSky 都不允许了，不然可能太过复杂。
