### ISSUE TITLE
搜索界面支持 `Alt+Click` 打开分屏

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#4953]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

为了快速打开其他辅助文档

### 描述可能的最优解决方案 Describe the optimal solution

希望能够从顶栏和搜索界面中能直接快捷分屏

**Comment by Vanessa219** [comment]
顶栏指的是页签顶部么？这个好像没有必要用 alt+click，需要打开重复的文档情况并不是太多。搜索界面可以支持一下。

**Comment by haogeek** [comment]
如果反链条目也能支持同样的操作体验那就简直是完美了
