### ISSUE TITLE
列表使用“复制为引用块”快捷键时能直接复制出列表而不是段落

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#4954]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

列表始终都需要点开几个选项来实现引用，这实在是不方便，还望能够考虑一下

### 描述可能的最优解决方案 Describe the optimal solution

快捷键能够根据当前行的属性来复制

**Comment by 88250** [comment]
使用 Shift+↑ 扩选到列表/列表项以后再 Ctrl+Shift+C
