### ISSUE TITLE
docker 可否使用UID GID变量来定义用户，不要强制使用1000:1000

### ISSUE THREAD

**Issue by AeolusC** [siyuan-note/siyuan#4955]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

因为使用的同步工具创建的文件不能直接赋权1000：1000。如果docker使用1000：1000，需要重新赋权才能继续使用，这让人感觉完全多余的一步，最先的版本用的默认root用户也比现在方便。

### 描述可能的最优解决方案 Describe the optimal solution

使用UID GID变量来定义用户

**Comment by AeolusC** [comment]
> 有完整的解决方案或者示例可以参考一下吗？

这位的image nn200433/siyuan

**Comment by 88250** [comment]
感谢提供参考，这个方案不太确定是否可行，我们暂时不改了。

如果需要的话，可以试试自己打包看看。
