### ISSUE TITLE
群晖docker安装，配置反向代理，https访问提示“内核连接中断...v2.0.11”

### ISSUE THREAD

**Issue by tonyltl** [siyuan-note/siyuan#4959]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

1. 群晖docker安装：docker run -v /volume1/docker/siyuan:/siyuan -p 6806:6806 -u 1000:1000 b3log/siyuan -resident -workspace /siyuan -accessAuthCode password --servePath domain.com --ssl true
2. 安装完http访问正常，但https访问报错，提示“此站点连接不安全 ERR_SSL_PROTOCOL_ERROR”，另外我的群晖nas是配置了ssl并且可以正常访问的。
3. 群晖-控制面板-系统-登录门户-高级-反向代理服务器，新建反向代理（来源是https+新映射的外网端口如9999，目的地是配置好的思源笔记内网http访问地址，端口6806），https（9999端口）可以加载页面，但报错提示“内核连接中断...v2.0.11”
4. 查看docker 错误日志，提示“runtime error: invalid memory address or nil pointer dereference”；“[31m2022/05/20 12:07:10 [Recovery] 2022/05/20 - 12:07:10 panic recovered:”
5. 安装容器，去掉参数“--servePath domain.com --ssl true”，https访问报错依旧。

### 期待的结果 Expected result

可以正常使用https访问，不报错。

### 版本环境 Version environment

```markdown
- Version: v2.0.11
- Operating System: 群晖DS218+ DSM7.1
- Browser (if used):Edge 101.0.1210.47 x64；Chrome 101.0.4951.54 x64
```

### 日志文件 Log file

[laughing_proskuriakova.zip](https://github.com/siyuan-note/siyuan/files/8735936/laughing_proskuriakova.zip)

**Comment by 88250** [comment]
需要反代 WebSocket，帮助文档里搜索 Docker。

**Comment by tonyltl** [comment]
群晖dsm6.1原版的不行，用docker重装了一个nginx搞定，谢谢指导

**Comment by hyjwonder** [comment]
> 群晖dsm6.1原版的不行，用docker重装了一个nginx搞定，谢谢指导

小白求救，我也是在群晖上用docker部署思源，用群晖的反向代理总是显示内核中断。请问您是怎么搞定的？

用docker安装nginx是怎么配置的，可否赐教啊？感谢！

**Comment by terwer** [comment]
> > 群晖dsm6.1原版的不行，用docker重装了一个nginx搞定，谢谢指导
> 
> 小白求救，我也是在群晖上用docker部署思源，用群晖的反向代理总是显示内核中断。请问您是怎么搞定的？
> 
> 用docker安装nginx是怎么配置的，可否赐教啊？感谢！

ws也要加，我的配置反代你可以参考

```
server{
    listen 9001;
    listen 9000 ssl http2;
    server_name siyuan.terwergreen.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /var/www/html;

    if ($server_port !~ 9000){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }
    # HTTP_TO_HTTPS_END

    ssl_certificate        /etc/ssl/siyuan.pem;
    ssl_certificate_key    /etc/ssl/siyuan.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;
    # SSL-END

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://120.25.179.230:6806;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
        client_max_body_size 100m;
    }

    location /ws {
        proxy_pass         http://120.25.179.230:6806;
        proxy_read_timeout 60s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
    }
}
```

访问地址：https://siyuan.terwergreen.com:9000/

目前稳定运行半个月，没有出现任何异常。

**Comment by hyjwonder** [comment]
感谢大佬！我只能请位高手来帮忙解读了。谢谢！

**Comment by rabbitlhf** [comment]
求大佬们指教下 apache 反向代理的配置
