### ISSUE TITLE
支持导入文档数据包 `.sy.zip`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4961]
导入时 .sy 需要重新生成包含的所有块的 ID。

**Comment by UltramarineSky** [comment]
请问导入时对双链引用的块id也会重新生成吗？那双链还也有用吗？

**Comment by 88250** [comment]
@UltramarineSky 导出数据包 #4965 时会将引用的文档一并导出，导入的时候会重新生成引用 ID，不破坏双链关系。
