### ISSUE TITLE
能否支持 shift+Enter快速换行

### ISSUE THREAD

**Issue by woaihuangxueying** [siyuan-note/siyuan#4968]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

光标处于某一行的中间，想快速换到第二行的时候

### 描述可能的最优解决方案 Describe the optimal solution

像Intellj IDEA 那样，按住 shift+enter 就可以快速进行换行， 不需要先把光标转移到行末再换行

**Comment by 88250** [comment]
之前讨论过，从中间软换行比较符合大部分用户的使用习惯，所以就不修改了，感谢反馈。
