### ISSUE TITLE
大幅提升启动速度

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4975]
之前因为考虑到文件系统外部变更（比如手工移动数据文件），所以每次内核启动都要做一致性对比，如果不一致则重建索引。

随着功能进一步完善（比如支持移动文档、数据历史回滚），在文件系统上直接操作数据文件的情况也变得比较少了。所以考虑跳过一致性对比，直接进入下一步。

这个改动之后，文件系统外部变更启动后需要手动触发重建索引。

**Comment by qifengle1998** [comment]
这个优化以后能有多快，是不是可以像手机软件那样秒开了?

**Comment by 88250** [comment]
@qifengle1998 同步数据的时候还是要卡一下。

**Comment by Tlonglan** [comment]
说起这个移动数据，[文档树多选拖拽 #1359](https://github.com/siyuan-note/siyuan/issues/1359?utm_source=ld246.com#ref-issue-1075133946)的功能什么时候会有呀

**Comment by 88250** [comment]
@Tlonglan 还要再等等，目前先继续解决一些细节问题。

**Comment by Tlonglan** [comment]
这样子。。。好吧
