### ISSUE TITLE
移除 `退出界面时关闭内核` 选项

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4977]
在 https://github.com/siyuan-note/siyuan/issues/4975 完成以后退出界面时固定关闭内核。

**Comment by Zuoqiu-Yingyi** [comment]
如果启用了 `关闭按钮后缩小到托盘中`, 是不是关闭界面也不会退出内核, 需要使用托盘右键退出才能关闭内核呀❓

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 是的
