### ISSUE TITLE
iOS 端根据系统语言初始化外观语言

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4978]
![image](https://user-images.githubusercontent.com/873584/169676510-0caa70da-93b5-4230-971c-6e5eea5dfc93.png)

**Comment by woaihuangxueying** [comment]
思源的mac版本和windows版本的功能是一样多的吗？会有mac版本功能阉割这种情况吗？

**Comment by 88250** [comment]
@woaihuangxueying 桌面端功能都是一样的。
