### ISSUE TITLE
增强锚文本的键盘操作

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#4979]
- [ ] 光标在锚文本内可使用  `ctrl+/` 唤出菜单
- [ ] 菜单出现时光标定位到输入框中
- [ ] `ESC/Enter` 关闭菜单时，光标回到编辑器原有位置

https://ld246.com/article/1653184732199

**Comment by mindstudy** [comment]
"光标在锚文本内可使用 ctrl+/ 唤出菜单"，这个操作：

a. 鼠标直接点击锚文字不行，会跳转到引用块。
b. 鼠标点击锚文字左侧或右侧，再按方向键才能进入，需要两步。
c. 特殊情况，如果锚文字只有一个字，这种情况就没法方向键进入锚文字内。

有没有可能实现：鼠标点击锚文字左侧或右侧，使用 ctrl+/ 唤出菜单？

**Comment by qifengle1998** [comment]
这个功能好，顶一下

**Comment by qifengle1998** [comment]
进入菜单时，光标可以选中文字吗
大部分情况下都可能会修改原文的

**Comment by qifengle1998** [comment]
> "光标在锚文本内可使用 ctrl+/ 唤出菜单"，这个操作：
> 
> a. 鼠标直接点击锚文字不行，会跳转到引用块。 b. 鼠标点击锚文字左侧或右侧，再按方向键才能进入，需要两步。 c. 特殊情况，如果锚文字只有一个字，这种情况就没法方向键进入锚文字内。
> 
> 有没有可能实现：鼠标点击锚文字左侧或右侧，使用 ctrl+/ 唤出菜单？

我看原帖也是这么建议的，估计技术上不好实现吧

**Comment by Vanessa219** [comment]
@mindstudy 在锚文本内有右侧都可以，左侧不支持

@qifengle1998 嗯，你说的应该就是第二点

**Comment by woaihuangxueying** [comment]
> * [x]  光标在锚文本内可使用  `ctrl+/` 唤出菜单
> * [x]  菜单出现时光标定位到输入框中
> * [x]  `ESC/Enter` 关闭菜单时，光标回到编辑器原有位置
> 
> https://ld246.com/article/1653184732199

试了一下新版，Enter好像没有办法关闭菜单，只有Esc可以
