### ISSUE TITLE
块引用与所引用的内容块进行交换

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#4981]
https://ld246.com/article/1653223724633

**Comment by aobatu** [comment]
这个功能真的好期待！现在反链基本上用不起来，就是因为拖入后从原始文档消失了，这样会极大的增加原始文档的内容完整性，同时对移动的信息丢失了上下文。有了这个功能之后，就能很好解决这两个问题。

**Comment by 88250** [comment]
@aobatu 按住 Alt 后拖拽是复制引用

**Comment by aobatu** [comment]
> 

天哪，之前居然不知道这个用法，可以解决一部分问题。
当然，最好还是能够支持在反链互换功能，从反链拖拽到正文后，然后经过反链互转，原始文档保留引用，新文档组织文字。
