### ISSUE TITLE
表格内粘贴 HTML 时异常

### ISSUE THREAD

**Issue by gagmeng** [siyuan-note/siyuan#4986]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

往表格中粘贴时异常，粘贴不成功，开发者工具中捕获到异常

### 期待的结果 Expected result

表格粘贴数据正常

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/13564117/169789512-da237a3b-ea07-45f0-a726-e820db705cf4.mp4

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

日志文件中未见异常

**Comment by 88250** [comment]
请把复制的文本发一下，谢谢。

**Comment by gagmeng** [comment]
<testnode>
          <name Value="1" />
          <value Value="1" />
          <description Value="1" />
          <note Value="0" />
        </testnode>

**Comment by gagmeng** [comment]
[test.zip](https://github.com/siyuan-note/siyuan/files/8758644/test.zip)

**Comment by 88250** [comment]
感谢反馈，已经可以重现问题，下个版本修复。
