### ISSUE TITLE
无法给整行文字设置样式，只能应用于行内部分文字

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#4987]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Always at the beginning of a line, I can't apply one of the 13 text styles. I press "alt+x" or go to the color menu, but nothing happens! The text remains unformatted.
In the middle of the text or at the end I can apply styles. But the problem is at the beginning!

### 期待的结果 Expected result

styles can be applied.

### 版本环境 Version environment

```markdown
- Version: 2.0.12
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8753907/siyuan.log)

**Comment by 88250** [comment]
Thanks for the feedback, it will be fixed in the latest version.

* https://ld246.com/article/1653308123625
* https://ld246.com/article/1653317129694

**Comment by gumugwen** [comment]
+1 Expected result
