### ISSUE TITLE
重建索引后退出重进编辑器页面不显示，钉住的页签无法进行操作

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#4991]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

点击帮助文档按钮更新帮助文档时卡了下，然后重建索引后弹窗显示数据库被占用，退出重进后编辑器页面不显示内容，页签栏钉住的页签无法关闭，页签右键不显示页签操作按钮，回退到2.0.11也是一样的

### 期待的结果 Expected result

可以显示编辑页面内容，页签右键显示操作菜单

### 截屏或者录屏演示 Screenshot or screen recording presentation

![2 0 12 编辑页面不显示](https://user-images.githubusercontent.com/54146035/169832468-3c9076fc-454b-42bc-83e4-934eff3b4068.gif)

### 版本环境 Version environment

```markdown
- Version: 2.0.12
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

I 2022/05/23 20:09:13 sync.go:253: sync [cloud=63858, local=63859, wroteFiles=113, transferSize=6.6 MB] uploaded in [13.17s]
I 2022/05/23 20:14:17 sync.go:181: set sync interval to [8m]
I 2022/05/23 20:22:20 sync.go:181: set sync interval to [8m]
I 2022/05/23 20:30:24 sync.go:181: set sync interval to [8m]
I 2022/05/23 20:38:29 sync.go:181: set sync interval to [16m]
I 2022/05/23 20:54:34 sync.go:181: set sync interval to [32m]
I 2022/05/23 21:05:58 database.go:75: reinitialized database [E:\00Base\SiYuan\temp\siyuan.db]
I 2022/05/23 21:06:00 index.go:210: rebuilt database for notebook [20211113205820-r7wceuq] in [1.06s], tree [count=141, size=2.6 MB]
I 2022/05/23 21:06:01 index.go:210: rebuilt database for notebook [20211030165340-cc16nzw] in [1.47s], tree [count=31, size=2.9 MB]
I 2022/05/23 21:06:08 index.go:210: rebuilt database for notebook [20211015163124-8of2qug] in [6.09s], tree [count=101, size=12 MB]
I 2022/05/23 21:06:26 index.go:210: rebuilt database for notebook [20211015163138-aqm171i] in [16.40s], tree [count=237, size=51 MB]
I 2022/05/23 21:06:30 index.go:210: rebuilt database for notebook [20211015163154-j4dns4k] in [3.37s], tree [count=319, size=8.3 MB]
I 2022/05/23 21:06:33 index.go:210: rebuilt database for notebook [20211015163215-a8k72mn] in [2.32s], tree [count=30, size=5.5 MB]
I 2022/05/23 21:06:55 index.go:210: rebuilt database for notebook [20210811072758-pmlq3e8] in [17.81s], tree [count=807, size=42 MB]
I 2022/05/23 21:07:00 index.go:210: rebuilt database for notebook [20220523155812-2bra67r] in [4.04s], tree [count=93, size=14 MB]
I 2022/05/23 21:07:01 index.go:210: rebuilt database for notebook [20210907134348-lmj1qf1] in [0.73s], tree [count=23, size=993 kB]
I 2022/05/23 21:07:03 index.go:347: resolved refs [1878] in [1964ms]
I 2022/05/23 21:07:05 index.go:210: rebuilt database for notebook [20210808180117-czj9bvb] in [1.29s], tree [count=49, size=1.1 MB]
I 2022/05/23 21:07:07 index.go:347: resolved refs [1944] in [2330ms]
E 2022/05/23 21:07:10 database.go:1028: begin tx failed: database is locked
      github.com/siyuan-note/siyuan-src/kernel/sql.BeginTx()
    	D:/88250/siyuan-src/kernel/sql/database.go:1028 +0x51
    github.com/siyuan-note/siyuan-src/kernel/model.(*Box).Index(0xc001be7548, 0x0)
    	D:/88250/siyuan-src/kernel/model/index.go:159 +0xd5d
    github.com/siyuan-note/siyuan-src/kernel/model.Mount({0xc00205e3f0, 0x16})
    	D:/88250/siyuan-src/kernel/model/mount.go:190 +0x6a5
    github.com/siyuan-note/siyuan-src/kernel/api.openNotebook(0xc000c8e500)
    	D:/88250/siyuan-src/kernel/api/notebook.go:149 +0x174
I 2022/05/23 21:07:30 working.go:89: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/05/23 21:07:31 runtime.go:34: kernel is booting:
    * ver [2.0.12]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\MySoftware\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\00Base\SiYuan, data 1.4 GB]
I 2022/05/23 21:07:31 conf.go:243: user has enabled [Automatically upload error messages and diagnostic data]
I 2022/05/23 21:07:31 serve.go:68: kernel is booting [http://0.0.0.0:6806]
I 2022/05/23 21:07:31 sync.go:94: sync before boot
I 2022/05/23 21:07:56 sync.go:253: sync [cloud=63859, local=63974, wroteFiles=2, transferSize=1.6 MB] uploaded in [21.19s]
I 2022/05/23 21:07:57 conf.go:499: database size [859 MB], block count [205005]
I 2022/05/23 21:07:57 working.go:125: kernel booted
I 2022/05/23 21:09:29 database.go:75: reinitialized database [E:\00Base\SiYuan\temp\siyuan.db]
I 2022/05/23 21:09:29 index.go:210: rebuilt database for notebook [20210808180117-czj9bvb] in [0.35s], tree [count=49, size=1.1 MB]
I 2022/05/23 21:09:30 index.go:210: rebuilt database for notebook [20211113205820-r7wceuq] in [0.84s], tree [count=141, size=2.6 MB]
I 2022/05/23 21:09:31 index.go:210: rebuilt database for notebook [20211030165340-cc16nzw] in [1.02s], tree [count=31, size=2.9 MB]
I 2022/05/23 21:09:36 index.go:210: rebuilt database for notebook [20211015163124-8of2qug] in [4.47s], tree [count=101, size=12 MB]
I 2022/05/23 21:09:51 index.go:210: rebuilt database for notebook [20211015163138-aqm171i] in [13.22s], tree [count=237, size=51 MB]
I 2022/05/23 21:09:54 index.go:210: rebuilt database for notebook [20211015163154-j4dns4k] in [2.62s], tree [count=319, size=8.3 MB]
I 2022/05/23 21:09:56 index.go:210: rebuilt database for notebook [20211015163215-a8k72mn] in [1.96s], tree [count=30, size=5.5 MB]
I 2022/05/23 21:10:15 index.go:210: rebuilt database for notebook [20210811072758-pmlq3e8] in [16.18s], tree [count=807, size=42 MB]
I 2022/05/23 21:10:19 index.go:210: rebuilt database for notebook [20220523155812-2bra67r] in [3.49s], tree [count=93, size=14 MB]
I 2022/05/23 21:10:20 index.go:210: rebuilt database for notebook [20210907134348-lmj1qf1] in [0.46s], tree [count=23, size=993 kB]
I 2022/05/23 21:10:22 index.go:347: resolved refs [1944] in [1815ms]
I 2022/05/23 21:10:47 database.go:75: reinitialized database [E:\00Base\SiYuan\temp\siyuan.db]
I 2022/05/23 21:10:48 index.go:210: rebuilt database for notebook [20210808180117-czj9bvb] in [0.33s], tree [count=49, size=1.1 MB]
I 2022/05/23 21:10:49 index.go:210: rebuilt database for notebook [20211113205820-r7wceuq] in [0.92s], tree [count=141, size=2.6 MB]
I 2022/05/23 21:10:50 index.go:210: rebuilt database for notebook [20211030165340-cc16nzw] in [1.05s], tree [count=31, size=2.9 MB]
I 2022/05/23 21:10:56 index.go:210: rebuilt database for notebook [20211015163124-8of2qug] in [4.79s], tree [count=101, size=12 MB]
I 2022/05/23 21:11:09 index.go:210: rebuilt database for notebook [20211015163138-aqm171i] in [12.29s], tree [count=237, size=51 MB]
I 2022/05/23 21:11:12 index.go:210: rebuilt database for notebook [20211015163154-j4dns4k] in [2.48s], tree [count=319, size=8.3 MB]
I 2022/05/23 21:11:14 index.go:210: rebuilt database for notebook [20211015163215-a8k72mn] in [1.79s], tree [count=30, size=5.5 MB]
I 2022/05/23 21:11:32 index.go:210: rebuilt database for notebook [20210811072758-pmlq3e8] in [14.71s], tree [count=807, size=42 MB]
I 2022/05/23 21:11:35 index.go:210: rebuilt database for notebook [20220523155812-2bra67r] in [3.34s], tree [count=93, size=14 MB]
I 2022/05/23 21:11:36 index.go:210: rebuilt database for notebook [20210907134348-lmj1qf1] in [0.44s], tree [count=23, size=993 kB]
I 2022/05/23 21:11:38 index.go:347: resolved refs [1944] in [1835ms]
I 2022/05/23 21:12:07 sync.go:97: sync before exit
I 2022/05/23 21:12:10 sync.go:181: set sync interval to [8m]
I 2022/05/23 21:12:10 conf.go:338: exited kernel
I 2022/05/23 21:12:32 working.go:89: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/05/23 21:12:33 runtime.go:34: kernel is booting:
    * ver [2.0.12]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\MySoftware\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\00Base\SiYuan, data 1.4 GB]
I 2022/05/23 21:12:33 conf.go:243: user has enabled [Automatically upload error messages and diagnostic data]
I 2022/05/23 21:12:33 serve.go:68: kernel is booting [http://0.0.0.0:6806]
I 2022/05/23 21:12:33 sync.go:94: sync before boot
I 2022/05/23 21:12:36 sync.go:181: set sync interval to [8m]
I 2022/05/23 21:12:36 conf.go:499: database size [859 MB], block count [205005]
I 2022/05/23 21:12:36 working.go:125: kernel booted
I 2022/05/23 21:13:26 sync.go:97: sync before exit
I 2022/05/23 21:13:29 sync.go:181: set sync interval to [8m]
I 2022/05/23 21:13:29 conf.go:536: removed temp file [E:\00Base\SiYuan\temp\blocktree.msgpackuetwnho.tmp]
I 2022/05/23 21:13:29 conf.go:338: exited kernel
I 2022/05/23 21:13:46 working.go:89: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/05/23 21:13:47 runtime.go:34: kernel is booting:
    * ver [2.0.12]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\MySoftware\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\00Base\SiYuan, data 1.4 GB]
I 2022/05/23 21:13:47 conf.go:243: user has enabled [Automatically upload error messages and diagnostic data]
I 2022/05/23 21:13:47 serve.go:68: kernel is booting [http://0.0.0.0:6806]
I 2022/05/23 21:13:47 database.go:75: reinitialized database [E:\00Base\SiYuan\temp\siyuan.db]
I 2022/05/23 21:13:47 sync.go:94: sync before boot
I 2022/05/23 21:13:50 sync.go:181: set sync interval to [8m]
I 2022/05/23 21:13:57 conf.go:499: database size [4.1 kB], block count [205005]
I 2022/05/23 21:13:57 working.go:125: kernel booted
I 2022/05/23 21:14:03 database.go:75: reinitialized database [E:\00Base\SiYuan\temp\siyuan.db]
I 2022/05/23 21:14:04 index.go:210: rebuilt database for notebook [20210808180117-czj9bvb] in [0.33s], tree [count=49, size=1.1 MB]
I 2022/05/23 21:14:05 index.go:210: rebuilt database for notebook [20211113205820-r7wceuq] in [0.89s], tree [count=141, size=2.6 MB]
I 2022/05/23 21:14:06 index.go:210: rebuilt database for notebook [20211030165340-cc16nzw] in [1.05s], tree [count=31, size=2.9 MB]
I 2022/05/23 21:14:11 index.go:210: rebuilt database for notebook [20211015163124-8of2qug] in [4.49s], tree [count=101, size=12 MB]
I 2022/05/23 21:14:26 index.go:210: rebuilt database for notebook [20211015163138-aqm171i] in [13.66s], tree [count=237, size=51 MB]
I 2022/05/23 21:14:29 index.go:210: rebuilt database for notebook [20211015163154-j4dns4k] in [2.66s], tree [count=319, size=8.3 MB]
I 2022/05/23 21:14:31 index.go:210: rebuilt database for notebook [20211015163215-a8k72mn] in [1.99s], tree [count=30, size=5.5 MB]
I 2022/05/23 21:14:50 index.go:210: rebuilt database for notebook [20210811072758-pmlq3e8] in [15.98s], tree [count=807, size=42 MB]
I 2022/05/23 21:14:55 index.go:210: rebuilt database for notebook [20220523155812-2bra67r] in [4.03s], tree [count=93, size=14 MB]
I 2022/05/23 21:14:55 index.go:210: rebuilt database for notebook [20210907134348-lmj1qf1] in [0.50s], tree [count=23, size=993 kB]
I 2022/05/23 21:14:57 index.go:347: resolved refs [1944] in [1909ms]
I 2022/05/23 21:15:10 sync.go:97: sync before exit
I 2022/05/23 21:15:13 sync.go:181: set sync interval to [8m]
I 2022/05/23 21:15:13 conf.go:338: exited kernel
I 2022/05/23 21:16:20 working.go:89: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/05/23 21:16:21 runtime.go:34: kernel is booting:
    * ver [2.0.12]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\MySoftware\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\00Base\SiYuan, data 1.4 GB]
I 2022/05/23 21:16:21 conf.go:243: user has enabled [Automatically upload error messages and diagnostic data]
I 2022/05/23 21:16:21 serve.go:68: kernel is booting [http://0.0.0.0:6806]
I 2022/05/23 21:16:21 sync.go:94: sync before boot
I 2022/05/23 21:16:24 sync.go:181: set sync interval to [8m]
I 2022/05/23 21:16:24 conf.go:499: database size [859 MB], block count [205005]
I 2022/05/23 21:16:24 working.go:125: kernel booted
I 2022/05/23 21:16:30 database.go:75: reinitialized database [E:\00Base\SiYuan\temp\siyuan.db]
I 2022/05/23 21:16:31 index.go:210: rebuilt database for notebook [20210808180117-czj9bvb] in [0.37s], tree [count=49, size=1.1 MB]
I 2022/05/23 21:16:32 index.go:210: rebuilt database for notebook [20211113205820-r7wceuq] in [0.97s], tree [count=141, size=2.6 MB]
I 2022/05/23 21:16:33 index.go:210: rebuilt database for notebook [20211030165340-cc16nzw] in [1.17s], tree [count=31, size=2.9 MB]
I 2022/05/23 21:16:39 index.go:210: rebuilt database for notebook [20211015163124-8of2qug] in [4.81s], tree [count=101, size=12 MB]
I 2022/05/23 21:16:55 index.go:210: rebuilt database for notebook [20211015163138-aqm171i] in [14.90s], tree [count=237, size=51 MB]
I 2022/05/23 21:16:58 index.go:210: rebuilt database for notebook [20211015163154-j4dns4k] in [2.87s], tree [count=319, size=8.3 MB]
I 2022/05/23 21:17:01 index.go:210: rebuilt database for notebook [20211015163215-a8k72mn] in [2.12s], tree [count=30, size=5.5 MB]
I 2022/05/23 21:17:20 index.go:210: rebuilt database for notebook [20210811072758-pmlq3e8] in [16.11s], tree [count=807, size=42 MB]
I 2022/05/23 21:17:25 index.go:210: rebuilt database for notebook [20220523155812-2bra67r] in [3.87s], tree [count=93, size=14 MB]
I 2022/05/23 21:17:25 index.go:210: rebuilt database for notebook [20210907134348-lmj1qf1] in [0.58s], tree [count=23, size=993 kB]
I 2022/05/23 21:17:27 index.go:347: resolved refs [1944] in [1916ms]
I 2022/05/23 21:17:41 sync.go:97: sync before exit
I 2022/05/23 21:17:44 sync.go:181: set sync interval to [8m]
I 2022/05/23 21:17:44 conf.go:338: exited kernel

**Comment by UltramarineSky** [comment]
删除conf.json文件和temp文件夹，重新启动后好了，2.0.11时也出现过重启后部分页签不显示内容，但可以操作页签关闭掉不显示内容的页签

**Comment by 88250** [comment]
我们没有找到重现步骤，可否帮忙看下如何重现，谢谢。

**Comment by UltramarineSky** [comment]
我试试看能不能重现，昨天一群里有位老哥是卸载旧版重装新版后，再打开，之前的页面就不显示内容了页签无法操作

**Comment by 88250** [comment]
好的，谢谢。
