### ISSUE TITLE
局部关系图中添加文档链接关系

### ISSUE THREAD

**Issue by tobealive** [siyuan-note/siyuan#4996]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Eventually, this request aims to improve document navigation in the PKM via the graph.

Currently, switching off options in the local graph like paragraphs / list items etc. makes links to other documents invisible if they are part of those nodes.

Personally, I mostly like a "decluttered" local graph that just shows related documents(2 or 3 levels deep) without additional headings, paragraphs etc. That way, relations between notes are nicely visible, and the graph becomes a valuable tool to navigate and overview connections in the PKM. At the present state I don't think that's possible.

### 描述可能的最优解决方案 Describe the optimal solution

Just like the global graph, it should be possible to show only related documents in the local graph. But instead of showing all document relations like the global graph does, it should show the links to the currently viewed document to a configurable depth.

An option that enables linked documents to be shown as direct links to the viewed document when having the mentioned options disabled would be a great feature.

### 描述候选的解决方案 Describe the candidate solution

I think logseq has outstanding graphs, especially the local graph is nice. They give a nice overview of document relationships. But logseq is pretty resource intensive, this siyuan already does better.

**Comment by 88250** [comment]
Thanks for the feedback, there have been similar proposals in the Chinese community.

Let's not add this special option, just add the relationship between documents, thank you.

When enable the paragraph type filter: 

![image](https://user-images.githubusercontent.com/873584/170165379-adf560ad-5f08-449b-92bd-c7e4a1539e03.png)

![image](https://user-images.githubusercontent.com/873584/170165296-8e61d1d4-bdc1-4f67-8da9-0cb0edfc040d.png)

When disable it:

![image](https://user-images.githubusercontent.com/873584/170165466-e610c651-197a-431a-bdaa-fb97ad05c668.png)

**Comment by tobealive** [comment]
Marvelous! Thank you for implementing it.

As #5004 mentioned, the depth of the references was a nice feature. If that can be combined with the new functionality, it would be the ultimate. 

But if I have to chose: the new functionality implemented 2.0.13 is better even without having the depth option. To find relations, one can substitute using the global graph.
