### ISSUE TITLE
光标在标题位置时，可使用快捷键唤出大纲、反链、关系图面板

### ISSUE THREAD

**Issue by mindstudy** [siyuan-note/siyuan#4999]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![222](https://user-images.githubusercontent.com/23169045/169982197-a5e6924e-3b1b-444b-867c-76cb05e92017.gif)

如所附gif显示，默认主题下操作，在文档标题按下 Alt+O，不能呼出大纲窗口，只会生成特殊字符

文档内容区按下 Alt+O 时正常呼出大纲窗口

### 期待的结果 Expected result

改进

### 版本环境 Version environment

```markdown
- Version: 2.0.12
- Operating System: Mac
- Browser (if used):
```

### 日志文件 Log file

无需

**Comment by Vanessa219** [comment]
大纲面板是 alt+1

**Comment by mindstudy** [comment]
是 alt + o （opq的o，不是012的0）独立呼出的大纲窗口，不是 alt + 2 大纲面板

没事，不改也无妨
