### ISSUE TITLE
【bug】待办事项 格式错乱

### ISSUE THREAD

**Issue by Dillzo** [siyuan-note/siyuan#5]
1. 待办事项格式错乱。比如我手动输入如下内容：
- [ ] 待办事项

显示效果会变成：
![image](https://user-images.githubusercontent.com/68283141/92844445-7060b580-f418-11ea-889a-728fdba9d1ec.png)

只有写"待办事项"，然后选中这些文字，再点击顶上的待办图标，才能正常显示。

2. 待办事项跟无序列表组合使用的时候格式错乱。如果我手动输入以下代码：
- [ ] 待办事项1
- [ ] 待办事项2
    - [ ] 待办事项2-1
    - [ ] 待办事项2-2

显示效果会变成：
![image](https://user-images.githubusercontent.com/68283141/92847846-2da0dc80-f41c-11ea-9204-5694cc6732f7.png)

3. 运行环境：
win10 64

**Comment by 88250** [comment]
感谢反馈，稍后解决。

**Comment by 88250** [comment]
请待 v0.1.7 发布后再帮忙测试一下是否修复，谢谢！
