### ISSUE TITLE
Release notes in English

### ISSUE THREAD

**Issue by desk7** [siyuan-note/siyuan#5000]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Please write release notes also in English.

### 描述可能的最优解决方案 Describe the optimal solution

Please write release notes also in English.

**Comment by UFDXD** [comment]
please learn Chinese

**Comment by UFDXD** [comment]
> ### 在什么情况下你需要该特性？在什么情况下需要此功能？
> 请同时用英文写发行说明。
> 
> ### 描述可能的最优解决方案
> 请同时用英文写发行说明。
> 
> ### 描述候选的解决方案
> _无响应_
> 
> ### 其他信息
> _无响应_

please learn Chinese

**Comment by UFDXD** [comment]
@desk7 
please learn Chinese

**Comment by taozina** [comment]
@desk7 I simply translate the page with the Google Translate addon in Brave Brownser! Translates in about 3 seconds...
The developers already give us updates almost daily! We cannot demand more unnecessary work as we have other resources to help us as well.

**Comment by 88250** [comment]
Sorry, we really don't have time to do this part of the work at the moment, please use the translation tool.

Hopefully someone in the community can help us solve this problem in the future.
