### ISSUE TITLE
提高代码块的缩进与反缩进体验

### ISSUE THREAD

**Issue by pjpjp219** [siyuan-note/siyuan#5003]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

比如我从 Idea 中复制代码到代码块，由于格式的原因，在思源笔记中会出现缩进，此时我使用反缩进快捷键 shift + z 是不起作用的，我希望能全选 然后 shift + z 就能调整好格式

### 描述可能的最优解决方案 Describe the optimal solution

如果能在多行缩进反缩进的基础上增加多行编辑功能就更好了

**Comment by 88250** [comment]
反向缩进是 Shift+Tab

**Comment by pjpjp219** [comment]
然而在代码块中反向缩进不起作用

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/170191263-d056fef4-6fad-4de4-a5f8-56aca357ba67.gif)

**Comment by pjpjp219** [comment]
稍等 我来录个 GIF

**Comment by pjpjp219** [comment]
我在疯狂的按 shift+tab了
![动画](https://user-images.githubusercontent.com/43691384/170192507-4e31782e-9eab-4c38-91e5-8ab1cfed57d8.gif)

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/170194026-2678a524-7d89-4e0b-bfd4-9c63d4592524.gif)

要选中前面的 Tab 字符。

**Comment by pjpjp219** [comment]
D大你好，最终我发现原因是 我从 1.9.x 跨版本升级到 2.12 导致快捷键失效了，我得手动删除工作空间下的 除 Data 目录之外的所有内容，再用新版打开该工作空间，就能解决 shift + tab 失效的问题
如果这个问题无法被解决在设置中是否可以有 【恢复设置配置】【清除所有设置】之类的选项

**Comment by 88250** [comment]
设置 - 外观里有重置功能。

**Comment by 88250** [comment]
编辑器 - 快捷键设置那里也有重置。

**Comment by jhzerone** [comment]
d大你好, 请教下, 也会有tab缩进问题 语言是python, 
![image](https://user-images.githubusercontent.com/58368113/196134504-6fc1a97b-5fe9-4acb-bc47-1c1c8d763ecf.png)

有两个问题.
1. 设置里面设置了tab宽度是4, 但是代码缩进还是8
2. 如上图,原始粘贴文本行前已经带了一个\t, 这个时候按shift-tab没办法往左缩进
![思源缩进](https://user-images.githubusercontent.com/58368113/196136670-d2db9b61-f2ab-4938-bed2-e24b15854b56.gif)
