### ISSUE TITLE
移除局部关系图 `层级` 参数

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5004]
这个参数和全局图的最小引用数有冲突，应该去掉。

**Comment by owlinMay** [comment]
局部关系图层级显示对发现和梳理文档之间的关系很重要，如果可以的话希望能把这个选项加回来。

**Comment by 88250** [comment]
嗯，目前暂时加不回来了，以后考虑。

**Comment by tobealive** [comment]
Maybe a solution is when the focused document is highlighted on the global graph. Then you can use the global graph nicely to find all the relations. Currently, it's hard to find the focused document in the global graph when you didn't use the graph to open it - only then it's highlighted.

**Comment by 88250** [comment]
For the improvement of the relationship graph, we will put it on hold for now, and give priority to solving other problems. Thank you for your understanding.
