### ISSUE TITLE
将图片下载到本地

### ISSUE THREAD

**Issue by Tukali** [siyuan-note/siyuan#5007]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在做笔记的时候，经常会有一些站点的图片，有的需要科学上网的网页上得图片，然后我本地查看笔记的时候，经常有的图片加载慢，或者有的图片被删了就访问不了了

### 描述可能的最优解决方案 Describe the optimal solution

1.添加一个选项，可以直接一键下载当前页的网页图片到本地的绝对路径或者相对路径，最好是当前目录下的一个自定义文件夹内

2.在网络图片的按钮增加一个选项，可选的下载到本地，即当前目录下的一个相对路径之类的

**Comment by 88250** [comment]
编辑器页签右上角 `...` 菜单里有这个功能。

![image](https://user-images.githubusercontent.com/873584/170231932-3f9adb2f-4bbd-43f2-903e-4ce1432bfa48.png)

**Comment by Tukali** [comment]
> 编辑器页签右上角 `...` 菜单里有这个功能。
> 
> ![image](https://user-images.githubusercontent.com/873584/170231932-3f9adb2f-4bbd-43f2-903e-4ce1432bfa48.png)

谢谢D大，没注意到上面的功能😝
