### ISSUE TITLE
data导入导出是全覆盖还是只覆盖名称相同的？

### ISSUE THREAD

**Issue by JCJC01** [siyuan-note/siyuan#5008]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有两个账号，一个for 工作，在公司电脑
一个for个人，在个人电脑
里面的资料不一样的
但是定期把工作账号备份到个人账号（个人账号已订阅），一方面日后管理，或者全资料搜索
请问？
通过客户端导入导出
是整个data文件覆盖掉？
还是说名称相同的文档才会被覆盖掉

### 描述可能的最优解决方案 Describe the optimal solution

导入导出时，不要整个data文件夹覆盖
只是覆盖相同文档名的文档

**Comment by 88250** [comment]
同路径覆盖。

**Comment by JCJC01** [comment]
即时整个data文件夹覆盖？

**Comment by JCJC01** [comment]
感谢回答。
类似20220412151136-qbkmkoc，如果导入的没有这个文件，就不会被覆盖吗？

**Comment by 88250** [comment]
理论上是的，为了保险最好备份好数据然后实测一下。
