### ISSUE TITLE
大纲面板加入文档标题

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#5011]
https://ld246.com/article/1653134603060/comment/1653477582666?r=Vanessa#comments

第一层缩进不要浪费左边距；图标更换为文档图标。

![image](https://user-images.githubusercontent.com/873584/170678633-dd770eff-58b7-4146-816e-3fea5af54334.png)

**Comment by 88250** [comment]
@Vanessa219 目前去掉顶层以后，折叠全部的这个 `isFirst` 参数应该可以去掉了 https://github.com/siyuan-note/siyuan/issues/2199
