### ISSUE TITLE
完整开源界面和内核

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5013]
* [x] 开源许可证 AGPLv3
* [x] 整理代码和开发文档
* [x] [修改用户协议](https://github.com/siyuan-note/siyuan/issues/5015)
* [x] [内置密钥算法公开](https://github.com/siyuan-note/siyuan/issues/5012)

正经开源，绝不跑路。

**Comment by woniuxia** [comment]
传下去，D大不过了~

**Comment by noobyan** [comment]
传下去，D大不过了~

**Comment by mozhux** [comment]
啥情况啊

**Comment by Anthony9897** [comment]
哈哈哈，不知道，开玩笑吧。

**Comment by Soo-3** [comment]
😄 hhhh传下去，D大不过了~

**Comment by linonetwo** [comment]
支持一下，思源↔开源

**Comment by luckept** [comment]
新的征程

**Comment by xuanbingBank** [comment]
啥情况，今天也不是愚人节啊

**Comment by netdog2019** [comment]
哇，这么快开源了，说到做到~~牛~~，但开源的太快了吧，让人都有点接受不了~~支持~~希望有能力的网友多多贡献力量，尤其是IOS移动端。

**Comment by gslnzfq** [comment]
突然开源有些慌啊

**Comment by aptexd** [comment]
D 你要是困难，就眨眨眼，我们可以多充几年会员的 😂

**Comment by pjpjp219** [comment]
听我说谢谢你……

**Comment by 88250** [comment]
感谢各位，我们继续努力。

**Comment by felix-ma** [comment]
今天还在聊开源的事情，有点害怕

**Comment by ronething** [comment]
D 大实在是优秀。

**Comment by 88250** [comment]
https://ld246.com/article/1653560278248

**Comment by jearton** [comment]
真的是良心产品，我会一直用下去的

**Comment by tcmtom** [comment]
开源真的是件大事，建议在readme以及官网更新一下介绍

**Comment by 88250** [comment]
@tcmtom 嗯，已经更新。

**Comment by terwer** [comment]
强烈支持，以后，思源笔记是我唯一的笔记软件了。

**Comment by sensfloron** [comment]
我想询问一下，索引相关的程序包含在已经开源的lute里了吗

**Comment by BonjourL** [comment]
什么时候独有格式，可以改成md

**Comment by Chenm4** [comment]
不明白独有格式为什么要改为md格式，独有格式是因为md文件格式有局限性不能很好的保存数据所以需要sy格式，但是思源也支持导出为md格式（就是可能有一部分md格式没有的功能会失效）所以改成md格式没必要，因为它可以是md格式，不过md格式好像十来年没有更新过了
