### ISSUE TITLE
面包屑继续改进 

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#5019]
- [x] 缩略调大为7个字 https://ld246.com/article/1653235932092/comment/1653538593453#comments
- [x] 横向滚动，支持鼠标 https://ld246.com/article/1653487018194/comment/1653488790635?r=Vanessa#comments
- [x] 滚动条定位 https://ld246.com/article/1653235932092/comment/1653718504081?r=Vanessa#comments

**Comment by roverway** [comment]
个人觉得横向滚动方案不如平常缩略显示（确保只有一行），鼠标hover之后浮动换行显示完整内容（不挤压正文位置）更方便。
横向滚动一行内容感觉怪怪的。
