### ISSUE TITLE
文档树的用户体验建议

### ISSUE THREAD

**Issue by spellman001** [siyuan-note/siyuan#5020]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当一个笔记本有多个层级，这时往往需要点击父目录前方箭头才能展示里面包含的层级
![image](https://user-images.githubusercontent.com/43229146/170478053-7078f1a0-b47e-41a2-acbb-f0e95044a174.png)

而点击父目录则父目录会按照文档方式进行展示（而不是直接展开该目录底下包含的文档）。这样用户在文档树中寻找相应笔记时往往需重复多次打开父目录层级，而且箭头那么小容易误操作。

如下所示  点击目录（不是箭头）时不会直接展开底下文档而是把当前目录作为文档显示
-目录
        \____文档1
        | 
        \____目录
        |             \____文档2
        |____文档1

### 描述可能的最优解决方案 Describe the optimal solution

可以的话是否能在新建时添加一个候选项  新建文档 or 目录

**Comment by 88250** [comment]
思源是父-子文档结构，不是文件夹，所以展开的时候是展开直接子级文档，不会全部展开所有子级文档。

不知道我有没有理解对你的建议 😓

**Comment by lisontowind** [comment]
可以用query挂件，查询该文档下所有子文档，而且可以多重嵌套，利用悬浮面板可以做到快速查找和预览，当只需要一个目录的时候非常方便。query插件的 sql语句这样写就行：
`SELECT
    '[' || b.content || '](siyuan://blocks/' || b.id || ')' AS __1____pre__文档标题
FROM
    blocks AS b
WHERE
    b.type = 'd'
    AND b.path LIKE '%.root{.root_id}/%'
ORDER BY
    b.path
LIMIT 25`

**Comment by lisontowind** [comment]
如果只需要查询一层，可以添加`AND b.path NOT LIKE '%.root{.root_id}/%/%'`

**Comment by spellman001** [comment]
> 思源是父-子文档结构，不是文件夹，所以展开的时候是展开直接子级文档，不会全部展开所有子级文档。
> 
> 不知道我有没有理解对你的建议 😓

这个父文档在点击的时候有两个动作一个是点击文档前  " > " 符号会展开子级文档
另一种是点击父文档名称时将这个文档作为文档打开，假设用户需要维护一个层次很深的文档树那么单单光点击 “ > " 将会非常吃力，而且容易误操作点到父文名称

父文档是否能有多个状态，对有需要的人以文档形式展示，然后在有一个精简版仅仅作为目录显示

**Comment by 88250** [comment]
> > 思源是父-子文档结构，不是文件夹，所以展开的时候是展开直接子级文档，不会全部展开所有子级文档。
> > 不知道我有没有理解对你的建议 😓
> 
> 这个父文档在点击的时候有两个动作一个是点击文档前 " > " 符号会展开子级文档 另一种是点击父文档名称时将这个文档作为文档打开，假设用户需要维护一个层次很深的文档树那么单单光点击 “ > " 将会非常吃力，而且容易误操作点到父文名称
> 
> 父文档是否能有多个状态，对有需要的人以文档形式展示，然后在有一个精简版仅仅作为目录显示

展开符号我们在界面交互上做了一个便利性改进，即可以点击的不只是 `>`，而是包括了左侧的矩形位置，这样尽量减少点击展开的操作成本。

关于目录展示请关注 https://github.com/siyuan-note/siyuan/issues/2711 ，即空的父文档打开以后会包含子文档的导航，这样能方便进入更深层级。

我们关闭了，感谢反馈。
