### ISSUE TITLE
linux上修改工作目录时，无法找到隐藏目录

### ISSUE THREAD

**Issue by x93008** [siyuan-note/siyuan#5021]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

设置->关于->工作空间目录， 选择修改目录，在弹出的文件选择弹窗里面没有出现以’.‘开始的隐藏目录

### 期待的结果 Expected result

隐藏文件应该也可以被找到

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/32192376/170483309-03947404-8c14-4133-90fc-16c6675a76a3.png)

### 版本环境 Version environment

```markdown
- Version: 2.0.13
- Operating System: linux
- Browser (if used): electron 15
```

### 日志文件 Log file

[Uploading siyuan.log…]()

**Comment by gslnzfq** [comment]
需要设置linux显示隐藏文件(夹)后，在选择工作空间的时候才能展示隐藏文件夹吧

**Comment by Clouder0** [comment]
![image](https://user-images.githubusercontent.com/41664195/170629519-f67ad9ad-2c88-4d9b-812d-8a3453904599.png)

**Comment by 88250** [comment]
似乎已经没有问题了，我们关闭了，谢谢。
