### ISSUE TITLE
是否可以考虑改进Windows客户端的本地锁定功能

### ISSUE THREAD

**Issue by istanb84** [siyuan-note/siyuan#5022]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在非私人电脑，比如办公电脑上使用时，无法确保始终只有自己使用，本地锁定功能来保护隐私非常实用。
现有的“访问鉴权”方式提供的锁定功能比较有限，只能在打开界面时锁定，锁定后无法最小化到托盘区，甚至无法最小化到任务栏。

### 描述可能的最优解决方案 Describe the optimal solution

是否可以考虑增强锁定的特性：
1.锁定后直接最小化到托盘区，或者界面锁定区域不包括标题栏，则在锁定后可以最小化到托盘区或任务栏；
2.托盘菜单中增加锁定选项，可通过右键托盘图标快速锁定。

**Comment by 88250** [comment]
在锁屏界面使用 Alt+M 即可最小化到托盘区。
