### ISSUE TITLE
建议添加【最近打开文档】功能，用于罗列最近打开过的文档；

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#5027]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

这个是文档编辑常用到的功能，方便浏览并快速跳转到最近编辑过的文档。

### 描述可能的最优解决方案 Describe the optimal solution

类似于浏览器的历史记录，编辑器中新打开tab页后，新增一条历史记录，包含

1. 时间戳
2. 文档标题作为锚文本的超链接或者引用块（点击后能跳转到对应文档）

这两个基本信息。顶部设有【清除历史记录】按钮。
如果刚打开的文档跟已有记录里最后一条对应的文档是同一篇，建议只更新最后一条记录的时间戳，不新增记录。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3293
