### ISSUE TITLE
使用 assets 路径的 `<img>` 标签图片无法显示

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#503]
![image](https://user-images.githubusercontent.com/19181833/99148022-5e252100-26c0-11eb-9427-7c5422584eb0.png)

**Comment by 88250** [comment]
中间可以显示那副图片也是 `<img>` 标签么？

**Comment by 88250** [comment]
这问题好像有点奇怪，麻烦开下开发者工具看下是否请求图片以及 assets 文件夹下的图片路径是否正确。
