### ISSUE TITLE
在阮一峰老师的周刊宣传一下

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#5030]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

思源现在开源了，可以在阮一峰老师的周刊中宣传一下，这个周刊程序员比较多，看看能不能吸引一些专业用户，为挂件（未来的插件？）贡献一波。

我提了一个issue，[【开源推荐】思源笔记 · Issue #2424 · ruanyf/weekly](  https://github.com/ruanyf/weekly/issues/2424  ) ，但是写的比较随意，有感兴趣的、文笔好的，可以细化一下。   

参考："工具软件 FlowUs 体验报告"[@HTTP](https://mp.weixin.qq.com/s/3JdX1hMBymlOTlnU0ah33g#:~:text=自己的晋升。-,工具软件 FlowUs 体验报告,-上周，一款 "《科技爱好者周刊（第 208 期）：晋升制度的问题》")

**Comment by 88250** [comment]
非常感谢推荐。
