### ISSUE TITLE
通过 GitHub Actions 实现每日构建

### ISSUE THREAD

**Issue by ssfdust** [siyuan-note/siyuan#5033]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

前两天看到思源不支持国产操作系统，原因是没有足够的机器来进行编译，国产操作系统大抵分为x86_64平台与aarch64的平台的linux操作系统，如果支持linux的aarch64那某种程度上也可以算支持国产操作系统，考虑到后台为go，前端为electron，那在linux平台上测试通过，那aarch64build通过某种程度上则支持国产操作系统。

鉴于现在思源开源了，我现在在尝试给思源添加github的ci/cd的模式，使用基于容器的环境进行构建。

在最新发布的思源的linux版本中，我发现使用的glibc的版本应该不高于2.14，但是似乎主流发行版没有默认glic为2.14。所以我不清楚思源是基于什么构建的。是否可以提升glibc版本，以及思源是否考虑在github上创建ci/cd系统？

支持开源，支持梦想，支持那句但行好事，莫问前程。

### 描述可能的最优解决方案 Describe the optimal solution

* github ci/cd
* 其他支持开源的ci/cd系统

我自己也只是用过jenkins和travis，但ci/cd大体流程应当相通。

**Comment by 88250** [comment]
glibc 应该是 golang 的 CGO 编译依赖（要编译 SQLite），[这里](https://stackoverflow.com/questions/55450061/go-build-with-another-glibc) 好像有更换的办法，我也没搞过，不太确定。

基于 Electron 的桌面端应该是能够通过 GitHub Actions 编译打包的（[Electron Builder Action](https://github.com/samuelmeuli/action-electron-builder)），但是 Windows 端编译后可能无法进行代码签名（我们目前用的签名方式是物理实体 USB Token）。不签名除了不大安全以为其他应该不影响。

打包方面可以参考一下 [scriptions](https://github.com/siyuan-note/siyuan/tree/master/scripts)，谢谢。
