### ISSUE TITLE
不使用原生 Emoji 的情况下，文档内表情提示应和最终输入结果保持一致

### ISSUE THREAD

**Issue by AloneFire** [siyuan-note/siyuan#5039]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在外观设置使用Twitter emoji 后，编辑器内输入的Emoji没有变化，但是选择器的图标已经变了，导致选择与输入的样式不一致
![捕获](https://user-images.githubusercontent.com/20330223/170828695-82ca961e-3709-41d7-ac68-8cd79be47138.PNG)

### 期待的结果 Expected result

编辑器内的Emoji图标样式与选择器内的样式一致

### 版本环境 Version environment

```markdown
- Version: v2.0.13
- Operating System: win10
- Browser (if used): Chrome
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8791253/siyuan.log)

**Comment by 88250** [comment]
`设置 - 外观 - 文档图标使用系统原生 Emoji` 仅针对文档图标，编辑器里面的图标目前只能使用原生字符。

**Comment by AloneFire** [comment]
> `设置 - 外观 - 文档图标使用系统原生 Emoji` 仅针对文档图标，编辑器里面的图标目前只能使用原生字符。

对的，所以编辑器内的Emoji选择器图标不应该变

**Comment by 88250** [comment]
> > `设置 - 外观 - 文档图标使用系统原生 Emoji` 仅针对文档图标，编辑器里面的图标目前只能使用原生字符。
> 
> 对的，所以编辑器内的Emoji选择器图标不应该变

@Vanessa219
