### ISSUE TITLE
页签数量过多无法显示

### ISSUE THREAD

**Issue by nicholaxs** [siyuan-note/siyuan#5040]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

页签数量如果过多会无法显示。

### 期待的结果 Expected result

发新版本解决。

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="1509" alt="图片" src="https://user-images.githubusercontent.com/34131305/170829250-84d0dbe3-877e-4801-94bd-b971acf2a823.png">

### 版本环境 Version environment

```markdown
- Version: v2.0.13
- Operating System: macos 12.4
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8791285/siyuan.log)

**Comment by 88250** [comment]
目前可以用鼠标滚轮滚动，长期改进请关注 https://github.com/siyuan-note/siyuan/issues/2098
