### ISSUE TITLE
大纲面板无法全部折叠

### ISSUE THREAD

**Issue by ZinYY** [siyuan-note/siyuan#5041]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

使用思源笔记 v2.0.13 Mac版时，无法折叠大纲

### 期待的结果 Expected result

大纲全部折叠

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="238" alt="bug" src="https://user-images.githubusercontent.com/17381012/170849708-b8082b8e-7cf1-4b78-9184-a3003f74d876.png">

### 版本环境 Version environment

```markdown
- Version: v2.0.13
- Operating System: MacOS 12.4
```

### 日志文件 Log file

None

**Comment by 88250** [comment]
这个问题在最新版上应该已经修复，感谢反馈。
