### ISSUE TITLE
代码块支持 Vue、React、JSX 等的语法高亮

### ISSUE THREAD

**Issue by Chorer** [siyuan-note/siyuan#5042]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

很多时候文章需要展示 Vue、React 等框架的 demo 代码

### 描述可能的最优解决方案 Describe the optimal solution

wolai 和 typora 都支持 React、Vue、JSX 等的语法高亮，似乎使用的是 CodeMirror。而思源使用的是 highlightjs，它本身不支持这些框架或语言的语法高亮。

**Comment by 88250** [comment]
highlightjs 不支持的话就暂时没办法了，请看下它的 issues 上是否有人提议过，没有的话可以试着提议看看，谢谢。
