### ISSUE TITLE
单元格所在行有跨行的单元格时禁止删除行

### ISSUE THREAD

**Issue by Morganwan90** [siyuan-note/siyuan#5045]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在存在合并单元格的表格中
1、合并单元格（合并列）删除某一行
会导致部分数据串列，且该行不可再删除
2、合并单元格（合并行）删除某一列
并无此选项

### 期待的结果 Expected result

类似excel，删除后不串行，在第一个动图中删除后，变为
![截图_20220530020719](https://user-images.githubusercontent.com/61633409/170885018-26e3b0a1-f84b-4fe6-b9b1-1bdfbeb6149c.png)
删除列同理。

### 合并列下删除行
![截图_20220530020000-20220530020855-k6y380b](https://user-images.githubusercontent.com/61633409/170885279-cdb07b99-a80b-464a-bcbf-53a9ebd8fd42.gif)

### 合并行下删除列
![截图_20220530020147-20220530020813-utdj99c](https://user-images.githubusercontent.com/61633409/170885302-f921e8bc-9985-48f8-91ca-c51d2a58f2d3.gif)

### 版本环境 Version environment

```markdown
- Version: 2.0.13
- Operating System: windows 11
```

### 日志文件 Log file

-

**Comment by Vanessa219** [comment]
第一个在删除行以后表格就有点问题了，稍后修改。

如果操做涉及到合并的单元格，由于在操作时会对它附近的一些单元格产生未知可选的影响，因此对其进行了屏蔽。
