### ISSUE TITLE
升级版本时能否保留任务栏、开始菜单固定的图标

### ISSUE THREAD

**Issue by pjpjp219** [siyuan-note/siyuan#5049]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

升级版本时能否保留任务栏、开始菜单固定的图标
以思源的更新频率，我隔段时间就得把这些操作再做一遍，后面慢慢的懒了就不想再加回任务栏了，现在我是手动搜出来打开的（注：我从不使用桌面图标）

### 描述可能的最优解决方案 Describe the optimal solution

1. 能否在升级时保留图标，该在哪个位置就在哪个位置
2. 能否在安装时提供，不在桌面创建图标的选项

### 其他信息 Other information

感谢你的阅读

**Comment by 88250** [comment]
之前研究过，实现不了 https://github.com/siyuan-note/siyuan/issues/3773
