### ISSUE TITLE
支持图片标题渲染

### ISSUE THREAD

**Issue by EndlessErrors** [siyuan-note/siyuan#505]
希望能将图片的名称（即md语法中的替代文字）渲染显示出来，并可在软件设置中选择是否显示以及显示位置
例子：
对于代码`![铁氧体磁珠的阻抗](assets/xxx.png)`希望显示成
![图片](https://user-images.githubusercontent.com/57283205/99152365-4eb3d100-26dc-11eb-81ea-539a8b16e8d1.png)

**Comment by 88250** [comment]
谢谢提议，我觉得可能用 `title` 更适合一些：![alt](src "title")。另外你提到的显示位置配置方面的建议是？

**Comment by EndlessErrors** [comment]
> 
> 
> 谢谢提议，我觉得可能用 `title` 更适合一些：`![alt](src "title")`。另外你提到的显示位置配置方面的建议是？

确实用 title 更适合一些。
显示位置就是显示在图片的上方或者下方。

**Comment by 88250** [comment]
明白了，计划在 v0.4.9 实现，谢谢。

**Comment by 88250** [comment]
位置咱们先默认在下方吧，如果以后有更多这方面的需求再进行优化，谢谢。
