### ISSUE TITLE
搜索结果一键复制

### ISSUE THREAD

**Issue by huangwzehii** [siyuan-note/siyuan#506]

**Comment by 88250** [comment]
你好，和 https://ld246.com/article/1605346599962 这里的建议是一样的吗？

**Comment by huangwzehii** [comment]
他需要直接在搜索结果里复制内容块id，我需要直接在搜索结果里复制所有结果的文本内容。目前还不会放图片，文字描述起来有点抽象。比如文本有三段，其中两段包含a，我搜索a，想提取包含a两段的文本。相当于搜索界面上半部分所有内容块的文本内容。

**Comment by 88250** [comment]
也就是在编辑器里的这个对吧？

![image](https://user-images.githubusercontent.com/873584/99161541-5dc36f00-272e-11eb-9fcc-7619d64430d7.png)

**Comment by huangwzehii** [comment]
是的。 第一次用这网站，想问一下，我提了两个issue，现在只剩下一个，是我操作失误吗

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/507 这个被我关闭了，因为已经有了……

**Comment by Vanessa219** [comment]
目前支持块操作
![Uploading image.png…]()

复制多个可以使用查询嵌入
