### ISSUE TITLE
优化pre-release主体内容

### ISSUE THREAD

**Issue by ssfdust** [siyuan-note/siyuan#5062]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

主要还是觉得太单调了，把脚本改了一下，之前那个透过提取CHANGE_LOGS最后信息的改为了根据`milestone`提取`issues`。

效果大概长这样:
![image](https://user-images.githubusercontent.com/3088610/171165471-ea7fe36a-4f69-4dd1-9736-c9eed2e0aae3.png)

主要就算不用在ci上，生成正式release信息也可以用。

### 描述可能的最优解决方案 Describe the optimal solution

- [x] 修改`parse_changelog.py`
- [x] 修改`ci.yml`

### 其他信息 Other information
EDIT:

* 脚本使用方式
```bash
pip3 install PyGithub
export GITHUB_TOKEN="<token>"
python3 scripts/parse-changelog.py -t <tag name> siyuan-note/siyuan
```

**Comment by 88250** [comment]
感谢，这个就不纳入 2015 版本发布了，关联 https://github.com/siyuan-note/siyuan/issues/5033
