### ISSUE TITLE
Frontend API

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#5066]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前来看，这两个方法在挂件中的应用带来的体验提升是非常明显的，它让挂件跟笔记文档之间的联系更加紧密。但是当前需要手动在main.js挂载方法的做法并不适用于每一个用户，如果开发者能默认开放这两种方法并简要描述一下其用法，那将是极好的。

之前尝试过在思维导图挂件中使用这两个方法，效果不错，希望PC端能默认支持，如果移动端伺服的时候也能支持，那就更好了。
[https://ld246.com/article/1651156033109](https://ld246.com/article/1651156033109)

### 描述可能的最优解决方案 Describe the optimal solution

以下是之前做过的一些粗浅的尝试：

之前尝试过在挂件中使用上述两种方法：

```ts
// 跳转
(0, window.parent._M.openFileById)({
  id: myId,
  position: "right",
  hasContext: !0,
  action: window.parent._o.Constants.CB_GET_HL,
});

// 悬浮预览
window.parent.siyuan.blockPanels.push(
  new window.parent._a.BlockPanel({
    targetElement: e.target,
    nodeIds: Arr,
  })
);
```

PC端windows平台 V 2.0.12 目前是通过以下方法手动挂载：

```css
t.WYSIWYG=class
```

替换成：

```css
window._o=n(1828);window._M=n(5751);t.WYSIWYG=class
```

```css
t.initBlockPopover=()
```

替换成：

```css
window._a=n(3781);t.initBlockPopover=()
```

移动端的话，之前在 v2.0.9 为了手机伺服的时候能在挂件中正常使用这两个功能，尝试过使用代理来替换main.js文件，实测是可用的，如果默认支持，则会方便很多：

```js
t.initBlockPopover=()
```

替换成：

```js
window._a=n(5933);t.initBlockPopover=()
```

```js
t.WYSIWYG=class
```

替换成：

```js
window._M=n(7683);window._o=n(2930);t.WYSIWYG=class
```

**Comment by choyy** [comment]
支持
如果能够悬浮预览，挂件与思源内容能够打通，像思维导图、excalidraw、timeline这些挂件体验会好很多

**Comment by Zuoqiu-Yingyi** [comment]
@BryceAndJuly 目前可以通过模拟单击的方式实现打开块与打开块并聚焦
https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/blob/b500654851084345c4be89208b4e47decf25d3d2/script/utils/misc.js#L90-L150

**Comment by BryceAndJuly** [comment]
@Zuoqiu-Yingyi [Zuoqiu-Yingyi](https://github.com/Zuoqiu-Yingyi)
给力喔。

**Comment by Zuoqiu-Yingyi** [comment]
> * [ ]  弹消息

这个功能已经由内核 API 实现了 #5102 , 且应用更广泛(比如在非 iframe 中打开的挂件), 应该没有必要支持了

**Comment by terwer** [comment]
期待啊，目前想做挂件，奈何没有更直接的文档和api支持

**Comment by william2113** [comment]
D 大，这个特性预计什么时候会发布呢

**Comment by 88250** [comment]
@william2113 还没有具体的时间表，请关注 https://github.com/orgs/siyuan-note/projects/1

**Comment by Yuminis98** [comment]
请问一下，这个前端API的作用和插件有什么区别吗？
还是说前端API只是面对开发者的？
以后用户有自由下载的扩展功能的机制吗？

**Comment by 88250** [comment]
@Yuminis98 还在考虑，插件是封装更好的，前端 API 是基础。

**Comment by HowcanoeWang** [comment]
当文件不存在时，GetFile API 返回null或者undefined

**Comment by Zuoqiu-Yingyi** [comment]
> 【feature request】 当文件不存在时，GetFile API 返回null或者undefined，方便后续写判断，而不是直接报404错误

404 错误也可以作为判断条件呀

**Comment by HowcanoeWang** [comment]
> > 【feature request】 当文件不存在时，GetFile API 返回null或者undefined，方便后续写判断，而不是直接报404错误
> 
> 404 错误也可以作为判断条件呀

目前就用try catch捕获进行判断的，但是捕获的不是404，而是无法解析传入的json，然后控制台依然输出404报错😂

**Comment by Zuoqiu-Yingyi** [comment]
> 目前就用try catch捕获进行判断的，但是捕获的不是404，而是无法解析传入的json，然后控制台依然输出404报错😂

使用这个试试
```js
const response = await fetch(/* params */);
if (!response.ok) throw new Error(response.statusText);
if (response.status !== 200) throw new Error(response.statusText);
/* 正常处理 */
```

**Comment by woniuxia** [comment]
@Vanessa219 V姐，像全屏打开这样的 API 可以先单独实现下吗？不必等着所有API一起实现，可以优先实现一部分优先级高的、常用的API 方便大家开发挂件。

**Comment by leolee9086** [comment]
> 

404 错误是网络错误  貌似是无法try catch捕获的

404 Error is a network error. It seems that it cannot be caught by try catch

**Comment by v-limc** [comment]
> @Yuminis98 还在考虑，插件是封装更好的，前端 API 是基础。

很棒，废了插件提案是好事，真心觉得前端插件很难很好的实现。参考VSCode的方式，前端功能扩展用API交互才更稳定，原生UI组件提供API调用创建、触发就好了，这样就能很方便的保持样式、设计的统一以及原生功能稳定不受干扰，非常棒，非常期待！

**Comment by 88250** [comment]
这个 issue 描述 API 将被包含在插件系统里，作为插件系统的一部分对外发布  #5086

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 目前对 Menu 功能的支持还不完善，最好可以支持在本体的各种 common menu 中添加菜单项，比如在块菜单添加一个包含下级菜单的 plugins 菜单项，下级菜单里面又包含各个插件注入的下级菜单，如下图所示

- 块菜单
  - 其他菜单项...
  - 插件扩展菜单
    - 插件1
      - 插件1注入的菜单项1
      - 插件2注入的菜单项2
      - ...
    - 插件2
      - 插件2注入的菜单项1
      - 插件2注入的菜单项2
      - ...
    - 插件...

**Comment by Vanessa219** [comment]
那我先扩展一下块标菜单。
目前插件没有加载顺序，做不到插件1的菜单里面放插件2的，有这样需求的话建议插件1和2写成一个插件。

**Comment by Zuoqiu-Yingyi** [comment]
> 目前插件没有加载顺序，做不到插件1的菜单里面放插件2的，有这样需求的话建议插件1和2写成一个插件。

这里插件1的菜单与插件2的菜单时并列的关系, 每个插件的菜单都是独立的下级菜单

**Comment by Vanessa219** [comment]
哦，我看这里还以为要混在一起
<img width="289" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/343d26b1-56eb-4df7-ad3c-6e04aeff608e">

**Comment by BryceAndJuly** [comment]
@Vanessa219  有个问题要请教一下，如果想在挂件里使用`Plugin.addFloatLayer()`方法，也就是根据块ID弹出悬浮窗的话，需要怎么使用呢？

有看到一个plugin-sample，但是它的引入方式看起来并不适用于挂件。

```js
import { Plugin } from "siyuan";
```

**Comment by Zuoqiu-Yingyi** [comment]
> @Vanessa219 有个问题要请教一下，如果想在挂件里使用`Plugin.addFloatLayer()`方法，也就是根据块ID弹出悬浮窗的话，需要怎么使用呢？

可以使用 `open API` 这个插件, 该插件会将插件 API 暴露至全局变量 `openAPI` 中

**Comment by BryceAndJuly** [comment]
@Zuoqiu-Yingyi  嗯，好的，感谢提醒
