### ISSUE TITLE
交互优化建议：优化代码块的语言选择列表的位置

### ISSUE THREAD

**Issue by Chorer** [siyuan-note/siyuan#5068]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如下图所示：https://test-1258623898.cos.ap-nanjing.myqcloud.com/3.gif

1. 当代码块靠近窗口顶端的时候，点击按钮选择代码块语言，此时的语言选择列表会出现在距离代码块较近的地方，无论是语言选择还是语言搜索，都非常方便。操作所需要的鼠标移动距离很短，如下所示：
![Snipaste_2022-06-01_16-07-45](https://user-images.githubusercontent.com/43442630/171359159-8cf13a7d-8c93-431a-ae86-42f195a39a4a.png)

2. 当代码块距离窗口顶端有半屏以上距离的时候，点击按钮选择代码块语言，此时的语言选择列表会出现在代码块上方，操作所需要的鼠标移动距离较长（需要将鼠标从按钮处向上移动一个列表的距离，到达搜索框处），如下所示：
![Snipaste_2022-06-01_16-08-13](https://user-images.githubusercontent.com/43442630/171359491-1d07fe75-31e9-48db-b890-128a40ad5e7f.png)

第二种情况是不符合操作直觉的，因为直觉上用户会认为语言选择列表应该出现在毗邻代码块的地方，这也是容易交互的位置。

### 描述可能的最优解决方案 Describe the optimal solution

始终让语言选择列表紧挨着语言选择按钮，尽可能出现在下方而不是上方。同时压缩语言选择列表的高度，减小鼠标需要移动的距离。如下图所示：

![Snipaste_2022-06-01_16-25-47](https://user-images.githubusercontent.com/43442630/171361446-01649ed7-f3f4-4932-a595-401622a0f98c.png)

虽然代码块距离窗口顶端较远，但这时候的语言选择列表也仍然是出现在语言选择按钮的下方，鼠标从语言选择按钮移动到语言选择列表的搜索框，只需要移动很短的距离，交互非常方便。

**Comment by Vanessa219** [comment]
这个是当下面的留空的位置显示不下且下面位置没有上面多，提示就会跑到上面去了，默认都是在下面的。
