### ISSUE TITLE
iPad 端无法正常显示扫描版 PDF

### ISSUE THREAD

**Issue by QiuMP** [siyuan-note/siyuan#5079]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我有一些书籍是扫描版 PDF，在 Mac 端能正常显示，在 iPad 端则是显示一片空白，只剩下标记的方框

文字版 PDF 则能够正常显示

### 期待的结果 Expected result

扫描版 PDF 能在 iPad 上正常显示

### 截屏或者录屏演示 Screenshot or screen recording presentation

![15617609-2732-4B68-9FF4-2B15367C066B](https://user-images.githubusercontent.com/14016627/171541431-fd401553-4dbc-4ec4-bd3d-d3b8538df5fd.png)

### 版本环境 Version environment

```markdown
- Version: 2.0.15
- Operating System: iPadOS 15.5
- Browser (if used):
```

### 日志文件 Log file

iPad 不清楚如何获取日志

**Comment by 88250** [comment]
能否发一份 PDF 文件给我们 845765@qq.com 谢谢。

**Comment by QiuMP** [comment]
> 能否发一份 PDF 文件给我们 [845765@qq.com](mailto:845765@qq.com) 谢谢。

已发送~

**Comment by 88250** [comment]
收到，谢谢。

**Comment by Vanessa219** [comment]
这个目前没办法解决，抱歉。  https://github.com/mozilla/pdf.js/issues/11245

**Comment by stonecutter-21** [comment]
请问这个问题现在能解决吗😂😂
ipad端不能看扫描版pdf还是很影响使用的

**Comment by Vanessa219** [comment]
pdf.js 升级过几次，还麻烦你看看现在是否能用，不行的话发一下 PDF，谢谢。

**Comment by stonecutter-21** [comment]
已发送至邮箱[845765@qq.com](mailto:845765@qq.com)

**Comment by stonecutter-21** [comment]
请问是否有进展呢 @Vanessa219

**Comment by Vanessa219** [comment]
我用 pad 打开 https://mozilla.github.io/pdf.js/web/viewer.html 然后上传你的 pdf 也是无法查看，看来官方并没有解决这个问题。

**Comment by stonecutter-21** [comment]
> 我用 pad 打开 https://mozilla.github.io/pdf.js/web/viewer.html 然后上传你的 pdf 也是无法查看，看来官方并没有解决这个问题。

我看pdf.js那边的相关issue都说，这种“平台特定的问题”不是pdf.js本身的错误，应该是ios系统的相关问题。刚才更新了最新版iPadOS 16.4.1，应该是解决了这个问题，现在扫描pdf可以正常显示了😁
