### ISSUE TITLE
加入编辑点前后跳转功能

### ISSUE THREAD

**Issue by EndlessErrors** [siyuan-note/siyuan#508]
如在VSCODE里可以按Alt+LeftArrow，Alt+RightArrow在前后编辑的位置跳转（包括在不同页面之间）
![_20205615095649](https://user-images.githubusercontent.com/57283205/99161072-0d95de00-2729-11eb-993d-8b6eca7ae277.gif)
这样在浏览A笔记时，点击链接到了B笔记编辑，用这个功能可以快速回到原来A浏览的位置。

**Comment by 88250** [comment]
感谢反馈，之前已有提议 https://github.com/siyuan-note/siyuan/issues/239
