### ISSUE TITLE
[Q]: How to use self-referencing variable within query in template?

### ISSUE THREAD

**Issue by arminta7** [siyuan-note/siyuan#5080]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

I am trying to figure out how to create a template that contains a query that says "find all blocks that contain a link to the current page" or "find all pages with the attribute Topic that equals the current page".

I've tried messing with the examples but can't figure it out. 

### 描述可能的最优解决方案 Describe the optimal solution

A template that contains a query with a self-referencing variable filter.

**Comment by 88250** [comment]
Hello, I don't know your specific needs, can you give an example?

**Comment by 88250** [comment]
SiYuan's query embedding block uses SQL as the query language, so you may need to understand the database table structure first. The table structure is explained in the user guide.

If you need to query by association, you may need to fully understand the table structure of SiYuan database (only the blocks table is described in the user guide, other tables are not described), use an SQLite client tool to open the workspace/temp/siyuan.db, you can seeing all the tables, you should get the effect of the example above through the associated query. 

Anyway, for the above example you mentioned, the general idea is to query for all blocks whose attributes contain `question` (or simplify to the `content` contains `question`) and whose `hpath` field contains the current document title `.title`.
