### ISSUE TITLE
快速连击使用模板时是在斜线的下一行出现

### ISSUE THREAD

**Issue by xxhh12a** [siyuan-note/siyuan#5083]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

快速连击使用模板时，是在斜线的下一行出现调用的模板。斜线在第一行，调用的模板从第二行开始出现

### 期待的结果 Expected result

能够正常使用

### 截屏或者录屏演示 Screenshot or screen recording presentation

[

Uploading 屏幕录制2022-06-02 16.32.38.mov…

](url)

### 版本环境 Version environment

```markdown
- Version: 2.0.15
- Operating System: mac 12.3.1
- Browser (if used):
```

### 日志文件 Log file

[
[siyuan.log](https://github.com/siyuan-note/siyuan/files/8822128/siyuan.log)
](url)

**Comment by 88250** [comment]
麻烦重新上传一下视频演示，谢谢。

**Comment by xxhh12a** [comment]
Uploading 屏幕录制2022-06-02 16.32.38.mov…

**Comment by Vanessa219** [comment]
视频没有上传上来，麻烦再传一下

**Comment by xxhh12a** [comment]
https://user-images.githubusercontent.com/55382340/172283663-490aa873-4b80-446d-82e8-653b6e6f4829.mov
