### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5086]
https://github.com/siyuan-note/petal

* [x] https://github.com/siyuan-note/siyuan/issues/8041
* [x] https://github.com/siyuan-note/siyuan/issues/8044
* [x] https://github.com/siyuan-note/bazaar/issues/1095
* [x] https://github.com/siyuan-note/siyuan/issues/8043
* [x] https://github.com/siyuan-note/siyuan/issues/8042
* [x] https://github.com/siyuan-note/siyuan/issues/8330
* [ ] https://github.com/siyuan-note/siyuan/issues/5066

**Comment by qifengle1998** [comment]
要开放插件了？爷青结

**Comment by woniuxia** [comment]
念念不忘，必有回响~

**Comment by woaihuangxueying** [comment]
终于等到你，还好没放弃~~

**Comment by checkwoodson** [comment]
有插件灵活性就更大了。奈斯~ 能像vscode那种可以敲代码就更刺激了~

**Comment by terwer** [comment]
非常期待，有了插件，能走的更远。不过目前可以先用挂件用一用。

**Comment by zxcvbnmzsedr** [comment]
插件有进展了吗

**Comment by 88250** [comment]
@zxcvbnmzsedr 短期内不会有进展，请关注 https://github.com/orgs/siyuan-note/projects/1

**Comment by beetaa** [comment]
关注，这应该是思源的一大步。

**Comment by beetaa** [comment]
关注，这应该是思源的一大步。

**Comment by Chenm4** [comment]
话说长期计划都是按照年为单位的吗，这个插件计划确实可以期待一下

**Comment by lentikr** [comment]
不知道这个打算什么时候开始呢，如果能做好感觉会是思源的一个吸引点。

**Comment by TDlimingcheng** [comment]
棒啊，有VSCode的实现模式珠玉在前，这肯定是一大步了，啥时候开始我也想参与贡献了，哈哈哈哈

**Comment by OriOYue** [comment]
> 不知道这个打算什么时候开始呢，如果能做好感觉会是思源的一个吸引点。

确实，感觉这个比白板之类之类的更有吸引力，毕竟个人的力量是有限的，有了插件后，思维导图、表格拓展、白板、发布、导出、分享之类的将变得更容易。

**Comment by primejava** [comment]
插件是个很强大的功能，但引入到页面里面，感觉和一个文档整体的割裂感太严重，就好像一个flash生硬地嵌入到了网页里面，不是一个整体

**Comment by 88250** [comment]
不再考虑实现插件机制，扩展性通过前端 API #5066 提供。

**Comment by 88250** [comment]
感谢由 @zuoez02 提供的插件系统基础 https://github.com/zuoez02/siyuan-plugin-system 

后续我们将在主程序中集成该插件系统，依然由社区开发者进行贡献维护，感谢各位插件开发者的探索！

**Comment by zuoez02** [comment]
共同维护

**Comment by mozhux** [comment]
咖啡二维码可以搞起来了，年底第一届插件评选大会去

**Comment by terwer** [comment]
看来我押宝插件是对的。我的未上架的新主题完全基于此插件系统。

**Comment by AugustTuan** [comment]
大的要来了👍

**Comment by AugustTuan** [comment]
主题里面耦合起来的各种特性，可以解耦成多个插件，给其他主题的用户使用了

**Comment by Yuminis98** [comment]
主题总算可以回归原来的地位了，只改变外观。
功能特性靠插件。🤩

现在的模式有多离谱，好比我在idea里面下了一个 onedark的主题，里面既然集成了mybatisX+Jrebel🤣

**Comment by frostime** [comment]
既然集成到本体里面，那么可以期待以后能支持更多 API 了。现在的插件系统server api 还好，client 接口可真的难，起码插件坞可以整起来了，否则大家都去抢占顶部那点空间成何体统。😋
