### ISSUE TITLE
公式块引用的块名称建议

### ISSUE THREAD

**Issue by wangfh5** [siyuan-note/siyuan#509]
引用公式块首先是一个相对小众的引用需求，其次其背后的原因很容易看出来，就是公式块很难进行搜索，一般通过左侧块标识进行复制块id。

- 复制之后的块引用语法如：`((20201115114603-lmzhgxq ""))`，这也就是默认没有块名称。
- 如果通过搜索的方式引用，那么如：`((20201115114603-lmzhgxq "\frac{C_V}{T}=\g"))`

我（也是所有使用latex或者typora进行科学写作的用户）习惯在需要被引用的公式中，在公式末尾加入引用语法如

```
%\label{4.3.1:heat_capacity}
```

- 其中加入注释语法`%`是因为思源暂不支持\label语法

这样的话，用（（触发块引搜索就可以通过**一串有意义的名字**来搜索，如果把搜索域限定在公式块中则更加快捷。
![image](https://user-images.githubusercontent.com/51868839/99162962-99fecb80-273e-11eb-8ca0-4f391ac4648b.png)

---

思源可以配合的地方：

1. 搜索到了要块引的公式之后，自动填充的块名称是`4.3.1:heat_capacity`而不是别的什么东西。现在搜索成功之后按回车得到的是：
```
((20201115114603-lmzhgxq "\label{4.3.1:hea"))
```

2. 如果公式块中存在`%\label{xxx}`的语法，那么点击块标识进行复制块id的时候，name用`xxx`。

**Comment by 88250** [comment]
需要再考虑一下，最好是支持 `\label{}` https://github.com/siyuan-note/siyuan/issues/40

**Comment by 88250** [comment]
将在 #660 中进行实现，谢谢。
