### ISSUE TITLE
搜索跳转

### ISSUE THREAD

**Issue by Tukali** [siyuan-note/siyuan#5095]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在全局搜索时，搜索到想要的笔记内容时，只能查看当前笔记内容，左侧文档树不会随之变化，如果我想看相邻的几个笔记或者是此文档目录下的笔记时，我还是要找到他的位置再打开才行，这就会很麻烦

### 描述可能的最优解决方案 Describe the optimal solution

希望在跳转到对应的笔记时，左边的文档树位置也随之变化，这样可以省很多事情，也比较方便

**Comment by choyy** [comment]
设置-文档树-始终定位打开的文档

**Comment by 88250** [comment]
也可以用文档树上的定位按钮。

我关闭了，如果还有问题请随时跟帖，谢谢。
