### ISSUE TITLE
能否提供“默认插入图片的宽度显示”的设置选项

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#5097]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

每次插入图片的时候，宽度都是以默认百分之100的宽度来插入的，而根据显示器分辨率不同，有时候默认不希望是100的宽度，比如我想每次插入的图片都是以百分之50的宽度

### 描述可能的最优解决方案 Describe the optimal solution

能否提供一个设置选项，设置每次插入图片的宽度百分比大小？

**Comment by qing-root** [comment]
![image](https://user-images.githubusercontent.com/30001685/171989199-fab92081-0fb8-4012-99a0-eeb3fa74688a.png)
每次插入以后都需要这样手动更改图片宽度 :(

**Comment by 88250** [comment]
暂时不考虑，请参考这里的回复，感谢理解。

https://github.com/siyuan-note/siyuan/issues/4878#issuecomment-1125820781
