### ISSUE TITLE
块引悬浮预览嵌套浏览

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#51]
块引的悬浮预览窗内展示富文本渲染结果，可以继续在里面递进跳转其他块引。

![image](https://user-images.githubusercontent.com/873584/94894519-19507c80-04bc-11eb-94d1-8afdc9672680.png)

**Comment by lss6378** [comment]
![悬浮预览递进跳转](https://user-images.githubusercontent.com/15924513/95819940-b089bf80-0d59-11eb-898e-2afef12dee00.gif)

**Comment by lss6378** [comment]
![悬浮预览递进跳转2](https://user-images.githubusercontent.com/15924513/95820453-b0d68a80-0d5a-11eb-95b2-348d587082c5.gif)

**Comment by wfan14513** [comment]
+1，嵌入块也有同样的需求。

**Comment by 88250** [comment]
决定套娃预览。
