### ISSUE TITLE
笔记丢失

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#510]
# 环境
* win10 1909
* 思源0.4.5
# 问题
* ＂历史＂打不开（一般重启思源后可以打开，但是过十分钟后就极可能打不开历史了）
* 笔记丢失。（笔记丢了三回了，这次特地录屏记录下来）
# 过程
文档＂lala1＂历史打不开。我在＂lala1＂文档里添加笔记，关掉思源重开，笔记丢失了。
文档＂号码＂打开后输入光标丢失，没法输入。
# 日志
I 2020/11/15 12:27:31 main.go:102: kernel [v0.4.5] is booting, runtime mode is [prod], working directory is [C:\Program Files\SiYuan\resources], temp directory is [C:\Users\Fabulous\AppData\Local\Temp\siyuan], read only [false]
I 2020/11/15 12:27:31 lang.go:63: initialized languages
D 2020/11/15 12:27:31 conf.go:107: loaded conf [C:\Users\Fabulous\.siyuan\conf.json]
I 2020/11/15 12:27:31 conf.go:217: local serve path [http://192.168.8.117:6806]
I 2020/11/15 12:27:31 conf.go:228: initialized conf
I 2020/11/15 12:27:31 appearance.go:45: initialized appearance
I 2020/11/15 12:27:31 main.go:148: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2020/11/15 12:27:31 webdav.go:35: initialized WebDAV server
D 2020/11/15 12:27:32 conf.go:756: indexed notebook [http://127.0.0.1:6806/siyuan/1602512336755/思源笔记用户指南/]
D 2020/11/15 12:27:32 conf.go:756: indexed notebook [http://127.0.0.1:6806/siyuan/1602512336755/Wow/]
D 2020/11/15 12:27:33 conf.go:756: indexed notebook [http://127.0.0.1:6806/siyuan/1602512336755/SiyuanTest/]
I 2020/11/15 12:27:33 conf.go:719: initialized notebook
E 2020/11/15 12:27:33 repo.go:271: init repo failed: mkdir C:\Program Files\SiYuan\resources\guide\思源笔记用户指南\.git: Access is denied.
I 2020/11/15 12:27:50 repo.go:44: initialized git repo
I 2020/11/15 12:32:24 main.go:101: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2020/11/15 12:32:24 main.go:102: kernel [v0.4.5] is booting, runtime mode is [prod], working directory is [C:\Program Files\SiYuan\resources], temp directory is [C:\Users\Fabulous\AppData\Local\Temp\siyuan], read only [false]
I 2020/11/15 12:32:24 lang.go:63: initialized languages
D 2020/11/15 12:32:24 conf.go:107: loaded conf [C:\Users\Fabulous\.siyuan\conf.json]
I 2020/11/15 12:32:24 conf.go:217: local serve path [http://192.168.8.117:6806]
I 2020/11/15 12:32:24 conf.go:228: initialized conf
I 2020/11/15 12:32:24 appearance.go:45: initialized appearance
I 2020/11/15 12:32:24 main.go:148: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2020/11/15 12:32:24 webdav.go:35: initialized WebDAV server
D 2020/11/15 12:32:25 conf.go:756: indexed notebook [http://127.0.0.1:6806/siyuan/1602512336755/思源笔记用户指南/]
D 2020/11/15 12:32:25 conf.go:756: indexed notebook [http://127.0.0.1:6806/siyuan/1602512336755/Wow/]
D 2020/11/15 12:32:26 conf.go:756: indexed notebook [http://127.0.0.1:6806/siyuan/1602512336755/SiyuanTest/]
I 2020/11/15 12:32:26 conf.go:719: initialized notebook
E 2020/11/15 12:32:26 repo.go:271: init repo failed: mkdir C:\Program Files\SiYuan\resources\guide\思源笔记用户指南\.git: Access is denied.
I 2020/11/15 12:32:41 repo.go:44: initialized git repo

![2020 11 15](https://user-images.githubusercontent.com/26304888/99166509-ee0aaf80-2740-11eb-9d23-f8e56f6d916a.gif)

**Comment by 88250** [comment]
长文档请看一下自动保存是否生效，相关 issue https://github.com/siyuan-note/siyuan/issues/354

**Comment by nanmao** [comment]
> 长文档请看一下自动保存是否生效，相关 issue #354

有手动保存的方法吗？丢失太可怕了。

**Comment by 88250** [comment]
抱歉了，0.4.6 做了一些修复，等发布后请帮忙再验证看看，谢谢。

**Comment by 88250** [comment]
对了，git 提交是定时的，默认每 10 分钟自动提交一次。

**Comment by nanmao** [comment]
> 对了，git 提交是定时的，默认每 10 分钟自动提交一次。

我没有配置git。而且现在想配置也打不开笔记，得不停重启。
![image](https://user-images.githubusercontent.com/26304888/99181813-ff1ce600-276b-11eb-9546-6cb18c0df5d2.png)
![image](https://user-images.githubusercontent.com/26304888/99181814-00e6a980-276c-11eb-9392-565d3fe2196b.png)

**Comment by 88250** [comment]
方便把笔记库发我一下么？ 845765@qq.com 可能是因为某个 bug 导致内核进程崩溃了。

**Comment by nanmao** [comment]
0.4.6暂时没发现丢笔记情况.

**Comment by 88250** [comment]
请继续帮忙留意观察，谢谢。

**Comment by 88250** [comment]
我关闭该 issue 了，如果还发现问题请 reopen。
