### ISSUE TITLE
建议添加选项：当鼠标悬浮在PDF高亮上时，不默认输出 “符合条件的内容块”

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5100]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

标记 PDF 时，当用户把鼠标放在高亮上，目前软件会做内容搜索，并展示结果，如下：

<img width="665" alt="Screen Shot 2022-06-04 at 11 05 04 PM" src="https://user-images.githubusercontent.com/7659710/172010500-4c5509fb-3059-48ce-9b7d-d10df984b876.png">

但当 highlight 很多时，会展示过多这样的窗口，影响阅读体验，无谓的搜索也降低了性能

### 描述可能的最优解决方案 Describe the optimal solution

希望设置中提供选项，可以关闭该自动搜索功能

**Comment by 88250** [comment]
这个不只是高亮的特性，主要是用于 PDF 标注以后复制到笔记中形成链接。

目前暂时不调整了，感谢反馈。
