### ISSUE TITLE
现在思源有了子文档概念，那么可不可以仿效scrivener的快照功能，对当前版本进行快速备份？

### ISSUE THREAD

**Issue by PumpkinSin** [siyuan-note/siyuan#5103]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

对重要的版本进行管理备份

### 描述可能的最优解决方案 Describe the optimal solution

给每个文档增加独立于历史记录的快照系统，其内容可以不被默认搜索搜到。

### 描述候选的解决方案 Describe the candidate solution

自动拷贝当前文档到某处，并在当前文档的页首/页末加上跳转连接。

**Comment by aptexd** [comment]
其实我也这样建议过，甚至还可以有“块”的历史呢
后来想到开发者人力有限，可能短期内实现都比较困难
但刚才看到这个问题一想，思源现在是笔记软件吧，这种形式更像是写作软件
不过现在的历史功能应该也可以按照时间进行快照记录吧

**Comment by 88250** [comment]
目前的数据历史主要使用场景是数据恢复，暂时不考虑引入单独的快照功能了，感谢提议。
