### ISSUE TITLE
改进云端数据加密安全性

### ISSUE THREAD

**Issue by BubbLess** [siyuan-note/siyuan#5105]
首先，该库中的AES-GCM使用了固定Nonce，无论出于什么目的，这都是很危险的行为。

一方面，对于AES-GCM而言，重复使用Nonce将允许攻击者恢复GCM中的认证密钥，这意味着攻击者可以篡改密文并自己生成MAC(这是相关的[会议论文](https://eprint.iacr.org/2016/475))，不过对于思源笔记的应用场景而言可能确实没有比较好的攻击方式。

另一方面，使用固定Nonce意味着相同的消息将产生相同的密文，同时两段密文的异或等于对于的明文的异或，一旦攻击者知道相应密文的明文，则可以利用这部分密文解密用户的其他密文，如果用户曾将其一些笔记进行过分享的话攻击者是完全有能力掌握这些信息的。因此一旦云端数据泄露，对于用户而言仍然是极其危险的。

此外，我注意到该库中使用md5来进行密钥派生，而且也没有进行任何的加盐操作，这样提供的安全保障是非常弱的。对于该库中期望使用的基于密码的密钥派生，我的建议是使用专门的password hash，像是[scrypt](https://pkg.go.dev/golang.org/x/crypto/scrypt), [argon2](https://pkg.go.dev/golang.org/x/crypto/argon2) 以及 [pbkdf2](https://pkg.go.dev/golang.org/x/crypto/pbkdf2)，Go的crypto标准库中也都提供了它们的实现，这能极大地增加攻击者进行暴力破解的负担，为用户提供更强的安全保障。

**Comment by 88250** [comment]
已有的云端同步机制不变，新的同步机制 #5142 使用新的密钥和数据加密实现。老铁如果有空请再帮忙 review 一下 https://github.com/siyuan-note/encryption

Issue 我先关闭了，任何建议请直接留言，感谢。
