### ISSUE TITLE
希望添加单词拼写检查功能 Spell Check 

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5109]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

英语书写中，单词拼写检查十分关键 （尤其对于 English as a second Language 人群，其他语种相信同样适用）

### 描述可能的最优解决方案 Describe the optimal solution

下面是 typora 的 UI，用于参考

<img width="327" alt="image" src="https://user-images.githubusercontent.com/7659710/172117976-6cdc9d63-074a-4105-821d-9e96fc796584.png">

**Comment by 88250** [comment]
Duplicate of #597
