### ISSUE TITLE
打不开笔记

### ISSUE THREAD

**Issue by nanmao** [siyuan-note/siyuan#511]
大概过十分钟就可能打不开笔记，只能重启思源。
思源0.4.5，win10 1909
一旦出现打不开笔记的情况，关掉重启思源刚刚做的笔记必丢失。
![2020 11 15](https://user-images.githubusercontent.com/26304888/99177292-7770b080-2746-11eb-85ba-c5a1dbaa31d1.gif)

**Comment by 88250** [comment]
麻烦发一下日志文件，谢谢。

**Comment by nanmao** [comment]
> 麻烦发一下日志文件，谢谢。

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5541986/siyuan.log)

**Comment by 88250** [comment]
应该和 https://github.com/siyuan-note/siyuan/issues/510 相关，等 v0.4.6 发布以后再帮忙看下，谢谢。

**Comment by 88250** [comment]
这个我关闭了，在 #510 中集中讨论。
