### ISSUE TITLE
希望增加插入指定位置文档的功能

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#5116]
https://ld246.com/article/1654151082620    帖子的功能希望别被淹没啊。。。。。

很多时候需要指定插入文档的位置，而不是每次生成新文档，都在当前的第一个或者最后一个，这个功能mybase做的很好

### 描述可能的最优解决方案 Describe the optimal solution

可以通过三个按钮，指定在那个文档的上、下或者子目录生成新文档，希望思源能够增加这个功能，一模一样的就太好了，太需要了！！！
![image](https://user-images.githubusercontent.com/30001685/172284903-cbe9edc5-688f-4f52-89b3-812c210ef1ef.png)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5098
