### ISSUE TITLE
手机端显示不全

### ISSUE THREAD

**Issue by sumengmsm** [siyuan-note/siyuan#5117]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

手机端上面被遮住了
![Screenshot_2022-06-07-13-55-25-52_ed1bdeca7a858bb430bfb9c256856672](https://user-images.githubusercontent.com/62458709/172308677-6fbf21c6-006e-49c7-a8fd-9e470f3b2be9.jpg)
旋转屏幕显示就没有问题了
![Screenshot_2022-06-07-14-01-32-45_ed1bdeca7a858bb430bfb9c256856672](https://user-images.githubusercontent.com/62458709/172308733-8a417386-8b56-462d-9a91-1457d5e24ded.jpg)

手机型号realme GT 大师探索版

### 期待的结果 Expected result

希望问题被解决

### 版本环境 Version environment

```markdown
- Version: 安卓 2.0.17
- Operating System: realme GT 大师探索版
- Browser (if used):
```

### 日志文件 Log file

I 2022/06/07 13:54:03 working_mobile.go:56: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2022/06/07 13:54:03 runtime.go:45: kernel is booting:
    * ver [2.0.17]
    * arch [arm64]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan, data 30 MB]
I 2022/06/07 13:54:03 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/06/07 13:54:03 conf.go:512: database size [10 MB], block count [3438]
I 2022/06/07 13:54:03 working.go:137: kernel booted
I 2022/06/07 14:00:27 working_mobile.go:56: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2022/06/07 14:00:27 runtime.go:45: kernel is booting:
    * ver [2.0.17]
    * arch [arm64]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan, data 30 MB]
I 2022/06/07 14:00:27 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/06/07 14:00:27 conf.go:512: database size [10 MB], block count [3438]
I 2022/06/07 14:00:27 working.go:137: kernel booted
I 2022/06/07 14:01:25 working_mobile.go:56: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2022/06/07 14:01:25 runtime.go:45: kernel is booting:
    * ver [2.0.17]
    * arch [arm64]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan, data 30 MB]
I 2022/06/07 14:01:25 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/06/07 14:01:25 conf.go:512: database size [10 MB], block count [3438]
I 2022/06/07 14:01:25 working.go:137: kernel booted
I 2022/06/07 14:08:37 working_mobile.go:56: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2022/06/07 14:08:37 runtime.go:45: kernel is booting:
    * ver [2.0.17]
    * arch [arm64]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan, data 30 MB]
I 2022/06/07 14:08:37 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/06/07 14:08:37 conf.go:512: database size [10 MB], block count [3438]
I 2022/06/07 14:08:37 working.go:137: kernel booted

**Comment by 88250** [comment]
应该是系统 WebView 的缺陷导致，之前在 OPPO 上有反馈，后来升级系统以后就好了， https://github.com/siyuan-note/siyuan/issues/4008

**Comment by sumengmsm** [comment]
我的webview是谷歌play最新版的
101.0.4951.61

**Comment by 88250** [comment]
@sumengmsm 那有可能是系统其他原因，这个之前我们尝试排查过，但是没有发现代码方面的问题，能升级系统的话升级看看也许就好了。
