### ISSUE TITLE
使用代码块数字出现不齐的问题。

### ISSUE THREAD

**Issue by checkwoodson** [siyuan-note/siyuan#5121]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

<img width="1613" alt="Snipaste_2022-06-07_20-08-46" src="https://user-images.githubusercontent.com/33786022/172375444-0d82c8ac-7a54-4e33-ba85-18de45aba3cb.png">

### 期待的结果 Expected result

对齐。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/33786022/172375596-6db4e46f-f8e5-4ed5-ae9d-d7724234e336.png)

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: win11 不过屏幕是4k屏幕
- Browser (if used):
```

### 日志文件 Log file

不需要吧

**Comment by 88250** [comment]
请试下默认主题，如果默认主题没有问题的话麻烦给该社区主题仓库反馈。

**Comment by woniuxia** [comment]
你这是代码块的位置放的不对。
前面几个代码块是和有序列表同级的。
最后那个是挂在有序列表下面的。
