### ISSUE TITLE
折叠状态的子标题展开时不展开下级折叠的块

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5134]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前我使用 子标题+列表的形式 的形式进行排版, 一个子标题下级一般只有级别更低的子标题与列表块, 由于列表块可能非常大, 渲染耗时较长, 因此我将部分子标题/列表块折叠了

此时发现将一个处于折叠状态的子标题展开后, 其下级所有的块全部展开了, 无论之前是否处于折叠状态, 导致展开时会消耗大量时间渲染

### 描述可能的最优解决方案 Describe the optimal solution

折叠状态的子标题展开时其下级处于折叠状态的块保持折叠状态

### 其他信息 Other information

![思源笔记-bug反馈-33](https://user-images.githubusercontent.com/49649786/172766647-19b42ec7-10dc-477f-af98-38d3d3de2f1c.gif)

**Comment by 88250** [comment]
这个目前做不到区分，只能统一折叠属性。
