### ISSUE TITLE
文档图标区分是否存在子文档

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#5135]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

提的帖子地址：https://ld246.com/article/1654743938423

思源笔记文件夹图标和文档图标问题

这个问题还是 mybase 做的不错的一个优点，希望思源笔记能考虑加入。。

### 描述可能的最优解决方案 Describe the optimal solution

mybase 中新建文档默认图标是文档的图标：
![image](https://user-images.githubusercontent.com/30001685/172777729-f8c40ed0-b9d7-41e6-a805-d9ec55f7acbc.png)
## 在当前文档新建子文档
如果在这个文档下，新建子文档，那么当前文档的图标自动变成文件夹图标：
![image](https://user-images.githubusercontent.com/30001685/172777769-dc233c83-8565-465f-b70f-65683e2b88f5.png)
在当前文档删除子文档
如果删除这个当前文档下，有 x 个子文档，现在把 x 个子文档删除了以后，当这个文档底下没有子文档，那么当前文档的图标从“文件夹图标”自动变成“文档图标”。

希望能够加入这个功能 😭

**Comment by 88250** [comment]
用这两个区分：

* 有子文档时 📑
* 没有子文档时 📄

**Comment by nickxsc** [comment]
来到思源之后发现，原来用mybase的人果然很多，mybase的文档树做的确实好，扛过了各种云笔记的吸引，终于遇到了思源，下定决心迁移，我日以继夜迁移了半个月才弄好。
