### ISSUE TITLE
0.4.6 mac版本搜索不出结果

### ISSUE THREAD

**Issue by Tokubara** [siyuan-note/siyuan#514]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/32409331/99204179-cd4d6300-27ef-11eb-927f-c13c550ee88f.png">

**Comment by 88250** [comment]
文档库里有该内容吗？

**Comment by Tokubara** [comment]
有的

**Comment by 88250** [comment]
方便把库打个包发我邮箱吗？ 845765@qq.com 谢谢。

**Comment by Tokubara** [comment]
不好意思, 啥是库, 是指笔记?

**Comment by 88250** [comment]
是的，笔记的文件夹打压缩包。

**Comment by 88250** [comment]
邮件回你了，这个 issue 关闭了。

**Comment by Tokubara** [comment]
我重启了电脑(在此之前删除了.git, 关闭了自动commit), 可以了. 我猜测主要还是重启电脑起的作用.
