### ISSUE TITLE
大纲页面随着文档切换而切换的问题

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#5140]
帖子：https://ld246.com/article/1654767158291

还有个个人觉得比较重要得问题，应该能增加一些使用好感。。。(感觉开发要累倒了 😭 )

默认打开一个文档，是没有大纲页面得，只要按了快捷键才有大纲页面，win 是 alt+o：

![image](https://user-images.githubusercontent.com/30001685/172815991-fc96abee-a386-4e53-9e2d-d72d9a0fbabf.png)

但是这个时候我切换文档，点其他文档时候，大纲页面并没有替换，还是上个文档得大纲页面：

![image](https://user-images.githubusercontent.com/30001685/172816042-bd96d889-d004-48fe-a0f7-d8f0b97a89b2.png)

## 希望改进的建议：

希望 alt+o 出现大纲页面，能够随着文档的切换而切换，并且如果能大纲自主选择靠左或者靠右就好啦

。。

**Comment by isyngo** [comment]
建议使用`Alt + 2`调取

**Comment by mindstudy** [comment]
顶楼的想法可能只考虑了一个文档的情况。

恰恰是 alt+o 跟随最初打开的文档，才能实现两个不同文档分屏时可以有各自对应的大纲：
<img width="1440" alt="dagang" src="https://user-images.githubusercontent.com/23169045/172822072-2d585ae2-807d-406b-8d98-c79b135351ae.png">

如果要同时显示文档树和Alt + 2大纲面板，可以在停靠栏更改Alt + 2大纲面板到右侧

<img width="296" alt="Screen Shot 2022-06-09 at 6 08 46 PM" src="https://user-images.githubusercontent.com/23169045/172822971-6d9dab0f-056e-4339-b9dd-3277e8fa3f71.png">

**Comment by qing-root** [comment]
> 

我去 大哥我要的就是这个效果  感谢感谢
