### ISSUE TITLE
Does the program work for iPad?

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#5146]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

I have never used the apple system (Mac or Ipad). I know nothing!
Does the program work for iPad? I'm looking to buy one.
Sorry to create this topic, but I don't see any other alternative.

### 描述可能的最优解决方案 Describe the optimal solution

Work on Ipad.

**Comment by 88250** [comment]
Yes, SiYuan can run on iPad, but if you are not in mainland China, there is currently no way to solve the data synchronization problem.

**Comment by taozina** [comment]
@88250  Friend, but which file can I download here on github? From what I was searching, .dmg files for MacBook doesn't work on it.

**Comment by 88250** [comment]
Install it from AppStore https://b3log.org/siyuan/en/download.html
