### ISSUE TITLE
思源和github实现交互

### ISSUE THREAD

**Issue by woaihuangxueying** [siyuan-note/siyuan#5147]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我既是思源的重度使用者，也每天在GitHub抄代码

### 描述可能的最优解决方案 Describe the optimal solution

思源获取github的授权后，
思源的md文档支持直接发布在github博客系统上， 你可以把你的作品放在github上，别人可以来fork可以来帮你纠错，给你发pull request。
同样github的文档也能直接拉取到思源
如果多个人合作一个文档， 多个人同时工作互不影响。所有的编辑历史都被保留。

### 其他信息 Other information

虽然有一个开源的gitbook，但是gitbook不管是使用的便利性，还是编辑功能都被思源吊起来打，想导入一个md文件都费劲。
好吧，这又是一个要被关闭的特性提议。😂
我只是提一下这个想法。🤣

**Comment by 88250** [comment]
你好，和外部应用/服务交互方面需要贡献者通过 API 进行扩展，谢谢。
