### ISSUE TITLE
资源附件本地打开问题

### ISSUE THREAD

**Issue by AiProgram** [siyuan-note/siyuan#515]
引用PDF文件的时候，如果是**绝对地址**，如“E:\XXX\assets\20201116105645-4ea3hwq-拉格朗日乘子法-KKT条件-对偶问题.pdf”则按住ctrl点击可以直接用默认软件打开。
而如果是**相对地址**，例如 ".\assets\20201116105645-4ea3hwq-拉格朗日乘子法-KKT条件-对偶问题.pdf" 或者 “assets\20201116105645-4ea3hwq-拉格朗日乘子法-KKT条件-对偶问题.pdf”则都不能直接打开，而是类似新建一个全新的资源管理器窗口（原“我的电脑”），然后就没反应了。
这个问题非常影响使用，因为相当于PDF附件功能直接无用了，毕竟绝对地址很容易改变。此外，考虑到作者使用的是Atom也就是基于chrome内核的应用程序，应该原生有打开PDF的能力，所以还**建议作者加上软件内预览PDF附件的功能**，规避此类问题。

系统版本：Win10 专业版 2004 19041.572
软件版本：0.4.5
文件位于Onedrive本地目录下。

**Comment by AiProgram** [comment]
Onedrive的原始目录带有空格，我通过文件硬链接的方法在绝对地址中规避了这个问题，建议作者可以排查这方面的问题。文件路径带有空格确实容易出错，我观察思源也不能处理带空格的路径，所以如果想解决可以支持类似 [PDF]("E:\xx xx\xxx.pdf") 的形式，用双引号说明不从空格处断开路径。

**Comment by 88250** [comment]
感谢反馈，后面进行优化，支持标准 Markdown 链接格式 `[PDF](<E:\xx xx\xxx.pdf>) `

**Comment by 88250** [comment]
对了，链接中的空格支持请在设置 - 编辑器中打开这个选项后再试试看：

![image](https://user-images.githubusercontent.com/873584/99212093-047a3f00-2805-11eb-9345-22e860d36333.png)

**Comment by foxleeda** [comment]
我遇到了同样的问题，我在路径中没有空格。我做了个测试：

1. 首先我拖拽一个pdf文件进来，它自动上传并创建了一个本地路径
![Snipaste_2020-11-17_22-05-41](https://user-images.githubusercontent.com/60538873/99400156-97a89700-2921-11eb-9644-e4d62c91aac0.png)
此时，如果我用 ctrl + 点击，只能打开一个资源管理器（“我的电脑”）

2. 我将上述链接改为绝对路径：
![Snipaste_2020-11-17_22-05-50](https://user-images.githubusercontent.com/60538873/99400396-df2f2300-2921-11eb-8184-c3203fd1ee94.png)
这次，当再次用 ctrl + 点击，就可以用默认的pdf阅读器打开了

同样的情况不仅限于pdf，也出现在其他格式、如txt, docx等等上面

**Comment by foxleeda** [comment]
> 
> 
> 我遇到了同样的问题，我在路径中没有空格。我做了个测试：
> 
>     1. 首先我拖拽一个pdf文件进来，它自动上传并创建了一个本地路径
>        ![Snipaste_2020-11-17_22-05-41](https://user-images.githubusercontent.com/60538873/99400156-97a89700-2921-11eb-9644-e4d62c91aac0.png)
>        此时，如果我用 ctrl + 点击，只能打开一个资源管理器（“我的电脑”）
> 
>     2. 我将上述链接改为绝对路径：
>        ![Snipaste_2020-11-17_22-05-50](https://user-images.githubusercontent.com/60538873/99400396-df2f2300-2921-11eb-8184-c3203fd1ee94.png)
>        这次，当再次用 ctrl + 点击，就可以用默认的pdf阅读器打开了
> 
> 
> 同样的情况不仅限于pdf，也出现在其他格式、如txt, docx等等上面

补充，我已经开启了“支持带空格的图片路径”。

**Comment by 88250** [comment]
感谢两位反馈，v0.4.9 修复。
