### ISSUE TITLE
图片居左和居右

### ISSUE THREAD

**Issue by Tukali** [siyuan-note/siyuan#5151]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在写文章的时候，有时候想要图片放在文字的左边或者图片放在文字的右边，提高美观程度

### 描述可能的最优解决方案 Describe the optimal solution

就类似这个开源编辑器的解决方式：https://mdsilo.com/writing/
正常状态：
<img width="798" alt="CleanShot 2022-06-10 at 09 59 24@2x" src="https://user-images.githubusercontent.com/45891208/172975102-9cb3da19-fe98-4e16-8449-ba233bfa4de2.png">

点击居左按钮后（居右也是同样的方式）：
<img width="826" alt="CleanShot 2022-06-10 at 09 59 41@2x" src="https://user-images.githubusercontent.com/45891208/172975142-b2f721b5-579a-4af2-9b63-121a4bfba053.png">

### 描述候选的解决方案 Describe the candidate solution

上面图片的图注也能实现就更好了，图注和图片一起居左或者居右，这样是最好的

**Comment by Tukali** [comment]
刚发现可以直接拖拽整个块的位置让他放到文字的左边或右边，但是这样的话分隔成两个部分了，而不像是一个整体，能像一个整体的那样居左或居右嘛

**Comment by 88250** [comment]
横向拖拽以后会形成超级块，这个超级块就是一个整体了。

**Comment by Tukali** [comment]
> 横向拖拽以后会形成超级块，这个超级块就是一个整体了。

1.那如何给图片添加一个图注呢，有时候这个功能也很需要
2.这种整体就是两个块并排在一起，能否实现图片嵌入文章的感觉呢，就像上面的图片例子一样，这种整体之后，右边文字只能够在右边块内编辑，无法像上面一下，下面继续可以从整个超级块的行首开始

**Comment by 88250** [comment]
* 图片上右键添加标题就是图注了
* 超级块可以嵌套
  ![image](https://user-images.githubusercontent.com/873584/172983850-098a2eea-7998-49e2-aee0-dde5c97c3d08.png)

**Comment by Tukali** [comment]
> * 图片上右键添加标题就是图注了
> * 超级块可以嵌套
>   ![image](https://user-images.githubusercontent.com/873584/172983850-098a2eea-7998-49e2-aee0-dde5c97c3d08.png)

好的，谢谢D大，没问题了

**Comment by 88250** [comment]
那我们关闭了，谢谢。

**Comment by Tukali** [comment]
> 那我们关闭了，谢谢。

好的，没问题
