### ISSUE TITLE
搜索面板高亮

### ISSUE THREAD

**Issue by Tukali** [siyuan-note/siyuan#5152]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

正常搜索内容是，只会在左边的缩略处高亮。而右边的详细处没有高亮，很难找到具体位置去查找编辑，如果内容很多而且在一个比较中间的位置的话，我只能确认有，具体在哪里还是很难找

![CleanShot 2022-06-10 at 10 17 41@2x](https://user-images.githubusercontent.com/45891208/172977330-d1bd362d-7218-4e3c-8b90-3bac7b88fad6.png)

### 描述可能的最优解决方案 Describe the optimal solution

在右边详细内容的地方也高亮找到的内容，方便查看

**Comment by 88250** [comment]
你好，目前无法在代码块中标注高亮，另外如果一个块内容较多，搜索命中定位的问题请关注 https://github.com/siyuan-note/siyuan/issues/3171

**Comment by Tukali** [comment]
> #3171

好的，我关注下
