### ISSUE TITLE
数据快照

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5159]
https://github.com/siyuan-note/siyuan/issues/5142 先上线手动数据快照功能。

* 支持手动创建快照，需要填写描述（Index memo）
* 支持浏览快照记录（Index log）

关联

* #5173
* #5160
* #5161

**Comment by qifengle1998** [comment]
这个功能主要是做啥的？

**Comment by 88250** [comment]
> 这个功能主要是做啥的？

请参考 #5142
