### ISSUE TITLE
Auto self-update

### ISSUE THREAD

**Issue by tobealive** [siyuan-note/siyuan#5164]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Aims to make updating automation for siyuan super easy when not building from source.

### 描述可能的最优解决方案 Describe the optimal solution

Provide download links for latest releases without version over specification. 

Examples :
https://github.com/siyuan-note/siyuan/releases/download/stable/siyuan-linux.appimage
https://github.com/siyuan-note/siyuan/releases/download/stable/siyuan-linux.tar.gz
https://github.com/siyuan-note/siyuan/releases/download/nightly/siyuan-linux.appimage
https://github.com/siyuan-note/siyuan/releases/download/nightly/siyuan-linux.tar.gz

Then an update alias command like `siyuan-update` could handle all the updating. 
Example using zsh on linux :
```sh
alias siyuan-update="cd ~/.local/share/applications/appimages/ \
	&& curl -LO https://github.com/siyuan-note/siyuan/releases/download/stable/siyuan-linux.appimage \
	&& chmod u+x siyuan-linux.appimage"
```
Especially for the appimage and binary releases this would be all that's necessary.
But all other formats would also become easy to pull. 

A solution like this can be provided either additionally to the current soltuion with the version numbers or it can become the default for latest releases .

### 描述候选的解决方案 Describe the candidate solution

This is nothing new, just another commonly used way to provide package download links. E.g., [nvim](https://github.com/neovim/neovim/releases).

### 其他信息 Other information
Of course those links can and should be tweaked to the preference of you as an developer. This issue is just to mention the general concept as an idea.

**Comment by 88250** [comment]
We've tried to implement automatic updates before, but it wasn't that easy. Because the SiYuan Kernel is an independent process, we haven't found a way to update our own process during cross-platform (such as supporting Windows).

Consider using the store version. The store version supports automatic updates. Some package managers on Linux seem to have community contributors to maintain and update them (we are not too sure about this, you can look for them), thank you.

**Comment by tobealive** [comment]
Yes the goal of this request was to get an easy accessible download link, directly from the developers release page and be able to use it in a little script. 

Redownloading the whole client is admittingly a pour man's solution for auto updating. But currently that's what I'm already doing  with the new releases. As this process with doing the system integration is often a little time-consuming, I often skip a few versions.

But I landed a luckshot and could do just what was intended in the request combining curl and wget, without needing to change change something.

If someone wants to use it, it should be adaptable to all other repos and formats: 
```sh
alias siyuan-update='cd ~/.local/share/applications/appimages/ \
&& echo "downloading siyuan latest release..." \
&& curl -s https://api.github.com/repos/siyuan-note/siyuan/releases/latest \
| grep "browser_download_url.*AppImage" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -O siyuan.appimage -qi - --show-progress \
&& echo "completed." \
&& chmod u+x siyuan.appimage'

```

Now all that's needed is to run siyuan-update

**Comment by Cyber-Syntax** [comment]
Inspired by @tobealive, I wrote this:
- [siyuan-install.py](https://github.com/Cyber-Syntax/Update-AppImages/tree/main)
- It would be great if you do a security review.
