### ISSUE TITLE
无法直接在内联代码块的首尾插入字符，并将字符作为代码块的一部分

### ISSUE THREAD

**Issue by Chorer** [siyuan-note/siyuan#5166]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

比如现在输入这个句子：这是一个`function`。`function` 已经被渲染成代码块了，但我发现它的命名不对，打算修改，我在它的开头或者结尾尝试插入其它字符，此时效果是这样的：

![GIF 2022-6-12 16-03-35](https://user-images.githubusercontent.com/43442630/173223671-be70687a-16a8-4d56-bc81-77ae0b8bb8bf.gif)

插入的字符无法被识别作为原有代码块的一部分，因此我只能在 `function` 后面再次加上一个反引号，取消代码块效果，插入字符后再把反引号去掉，如下图所示：

![2](https://user-images.githubusercontent.com/43442630/173223781-f1c5846a-9c09-4308-8b0c-ed033072b9bf.gif)

### 期待的结果 Expected result

将光标定位到反引号前面时，可以将新的字符插入到原有代码块的末尾，作为代码块的一部分；将光标定位到反引号后面时，可以将新的字符插入到原有代码块的末尾，但不作为代码块的一部分。
即应该提供一个选择，让用户决定新的字符是不是作为代码块的一部分，而不是默认让字符脱离代码块。

类似 Typora 的做法，如下图所示：
![GIF 2022-6-12 16-16-59](https://user-images.githubusercontent.com/43442630/173224026-ef460f37-9da5-414a-ae13-7c769eb55402.gif)

### 版本环境 Version environment

```markdown
- Version: v2.0.1.9
- Operating System: Win10
- Browser (if used): none
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
这个问题之前讨论过，暂时不做调整了，谢谢。

* https://github.com/siyuan-note/siyuan/issues/2904
* https://github.com/siyuan-note/siyuan/issues/3760
* https://github.com/siyuan-note/siyuan/issues/4131
