### ISSUE TITLE
完整删除整个章节

### ISSUE THREAD

**Issue by Tukali** [siyuan-note/siyuan#5169]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

将章节折叠后，不能直接删除整个章节，只能删除章节的标题和内容，无法删除下级标题和内容
原本：
<img width="1512" alt="CleanShot 2022-06-13 at 02 48 29@2x" src="https://user-images.githubusercontent.com/45891208/173248666-28334a31-ed99-43b5-94fa-2469680a1996.png">
折叠删除操作：
<img width="1527" alt="CleanShot 2022-06-13 at 02 49 33@2x" src="https://user-images.githubusercontent.com/45891208/173248707-7416c519-a68f-4df4-8076-b59843655737.png">
删除后的结果：
<img width="1289" alt="CleanShot 2022-06-13 at 02 50 05@2x" src="https://user-images.githubusercontent.com/45891208/173248717-024ec83d-a6df-42e9-a6cf-dfc5759290da.png">
实际上只删除了标题和下方内容，对于下级的标题及内容无影响
![CleanShot 2022-06-13 at 02 50 37@2x](https://user-images.githubusercontent.com/45891208/173248751-59dcaba6-7204-4fef-84e9-679e7e855312.png)

### 描述可能的最优解决方案 Describe the optimal solution

折叠整个大标题后，删除的应该包括他包含的所有层级和内容，应该是对一整个大标题及其内容的操作

### 描述候选的解决方案 Describe the candidate solution

其实原本想的是全部选中然后删除，但是鼠标选择这里好像有问题，明明是鼠标选择了第五章节的全部内容，松开鼠标之后，鼠标就之选中了最后的一点内容，这个十分的不方便，不知道是不是我选的太多了还是怎么回事，我的是m1 mac，如果这个能解决的话也还能接受

关于这个问题，我刚刚又试了一下，鼠标选择的时候，滑动鼠标滚轮就肯能会有丢失

**Comment by ro8ot** [comment]
Thanks

**Comment by 88250** [comment]
折叠标题不删除下方块的，如果要多选删除请使用 Shift+Click 跨页多选。
