### ISSUE TITLE
父文档图标和子文档图标太难区别

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#5170]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

帖子：https://ld246.com/article/1655034302183

2.19 开始 ，有区别文件夹和文档图标了，超级好，但是文件夹图标不好看：
但是这个父文档图和子文档图标很难看出**区别**，请问怎么把文件夹图标进行默认修改？

### 描述可能的最优解决方案 Describe the optimal solution

比如改成mybase这种
![image](https://user-images.githubusercontent.com/30001685/173266761-5f7ad23b-79de-43f7-a697-79404dc9e396.png)

**Comment by Vanessa219** [comment]
这个目前换不了，这个本身不只是文件夹，为了弱化文件夹的概念，才没有选文件夹的图标。

**Comment by qing-root** [comment]
> 

那就当不是文件夹  只存在父文档和子文档，那父文档的图标能提供默认替换的选项吗  太难受了
