### ISSUE TITLE
快捷键无法更改

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5172]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

设置>快捷键>功能项 的删除按钮失效, 具体表现为
1. 快捷键输入框内容被清空
2. 控制台抛出异常
3. 刷新后发现对应快捷键未被删除

### 期待的结果 Expected result

单击删除按钮时可以正常删除对应项的快捷键

### 版本环境 Version environment

```markdown
- Version: 2.0.19
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

```log
main.d786e0a43046d743718e.js:1 Uncaught TypeError: Cannot read properties of null (reading 'split')
    at main.d786e0a43046d743718e.js:1
    at NodeList.forEach (<anonymous>)
    at Object._setkeymap (main.d786e0a43046d743718e.js:1)
    at HTMLDivElement.<anonymous> (main.d786e0a43046d743718e.js:1)
(anonymous) @ main.d786e0a43046d743718e.js:1
_setkeymap @ main.d786e0a43046d743718e.js:1
(anonymous) @ main.d786e0a43046d743718e.js:1

```

### 更多信息 More information

貌似所有更改操作全部失效
可能是 #4808 引入的问题

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 貌似 `v2.0.22` 版本中 <kbd>Enter</kbd> 相关快捷键设置后不能使用, 比如 <kbd>Ctrl + Enter</kbd>, <kbd>Ctrl + Shift + Enter</kbd> 等等

**Comment by Vanessa219** [comment]
"⌘S", "⌘A", "⌘X", "⌘C", "⌘V", "⌘/", "⌘↑", "⌘↓", "⇧↑", "⇧↓", "⇧→", "⇧←", "⇧⇥", "⇧⌘⇥", "⌃⇥", "⌃⌘⇥", "⇧⌘→", "⇧⌘←", "⌘Home", "⌘End", "⇧↩", "↩", "PageUp", "PageDown", "⌫", "⌦", "F9" 这些是通用的，都不可自定义。

**Comment by Zuoqiu-Yingyi** [comment]
> "⌘S", "⌘A", "⌘X", "⌘C", "⌘V", "⌘/", "⌘↑", "⌘↓", "⇧↑", "⇧↓", "⇧→", "⇧←", "⇧⇥", "⇧⌘⇥", "⌃⇥", "⌃⌘⇥", "⇧⌘→", "⇧⌘←", "⌘Home", "⌘End", "⇧↩", "↩", "PageUp", "PageDown", "⌫", "⌦", "F9" 这些是通用的，都不可自定义。

并没有设置为这些保留快捷键, <kbd>⌘↩</kbd>, <kbd>⌃↩</kbd>与 <kbd>⌘⇧↩</kbd> 在之前版本是可以自定义且正常使用的~

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 V姐, 找到问题所在了, 将 conf.json 文件中快捷键由 `⌘Enter` 与 `⇧⌘Enter` 替换为 `⌘↩` 与 `⇧⌘↩` 即可正常使用, 但是在设置面板设置时依旧会往 `conf.json` 写入 `Enter`
