### ISSUE TITLE
添加笔记导出`单文件HTML`功能

### ISSUE THREAD

**Issue by l1xnan** [siyuan-note/siyuan#5178]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前导出`HTML文件`功能，`css`/`js`/`图片`等为单独文件，与 `index.html`分离，不方便分发，建议新增`导出到单个HTML文件`功能

### 描述可能的最优解决方案 Describe the optimal solution

github 上大致搜索了一下：
https://github.com/gildas-lormeau/SingleFile
https://github.com/zTrix/webpage2html

**Comment by 88250** [comment]
如果需要导出 mhtml 格式可以试下导出的 HTML 浏览器打开，然后另存为 

![image](https://user-images.githubusercontent.com/873584/173391992-aad264ac-1021-47bf-bb50-eb219d93ebea.png)


内置支持实现不了，之前研究过，感谢提议。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/773
