### ISSUE TITLE
提供类似HPath的NPath

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5179]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候需要把一个文件夹下的所有子文档按照文档树上的顺序嵌入到一个文档中，方便统一查看和导出pdf、docx。
现在用template，sql检索，用sort by HPath排序，一般都会出现顺序与文档树不一致的情况。

目前还有注意到有现成的方案，只是知道 [通过API getFile 和 解析sort.json](https://github.com/siyuan-note/siyuan/issues/4670) 可以间接达到这个目的。

个人在思源二次开发上比较业余，开发模版还将就，开发插件有点勉强，最好是能提供简单易用的方案， sort by NPath。

### 描述可能的最优解决方案 Describe the optimal solution

既然已经有sort.json，根据 HPath 应该可以衍生一个 Numerial Path (假设简称 NPath)，比如一个 Syid的 NPath 属性为 1/3/7，表示其为笔记本第一个子节点下面的第三个二级子节点下面的第7个三级子节点。

排序的话，就按照同一级之间数字大小比较排序。

**Comment by 88250** [comment]
你好，目前没有时间评估和处理，建议还是获取 sort.json 以后匹配 id 进行排序，谢谢。

**Comment by jabobian** [comment]
请问D大，sort.json文件中，序号并非是按照 0,1,2,3...的递增顺序，而是有跳空的数字和有重复的数字，而且重复的数字中，在文档树上靠前的节点在sort.json中对应的行号可能靠后也可能靠前（根据我有限的几次测试），这样的话也没法进行排序啊。

**Comment by 88250** [comment]
@jabobian sort.json 里面是个无序 map，使用时是根据 id 获取到 sort value，然后根据 value 排序 id。

**Comment by jabobian** [comment]
另外，通过API的getBlockAttrs和setBlockAttrs设置的Attr，和 sql 里面的 sort by key 的 key 能配合使用吗。 sql 里面有 sort 表头，但是 getBlockAttrs 无法获得（只能获得很少的基本属性，是否需要用户先设置？）。如果手动设置sort之后是可用于 sql sort by 的话，根据 sort.json 通过 API 设置 sort 属性，应该就可以基本满足我的要求了，即使遇到个别排序不对的情况，也可以手动修改 sort数值。

**Comment by 88250** [comment]
> 根据value排序id，那相同value的id，哪个在前哪个在后呢（上面提到了行号先后不能确定顺序），从syid的21位格式也实在看不出规则（是否前面14位数字小的靠前？）。

相同文件夹路径下应该不会出现这种情况。

**Comment by 88250** [comment]
> 另外，通过API的getBlockAttrs和setBlockAttrs设置的Attr，和 sql 里面的 sort by key 的 key 能配合使用吗。 sql 里面有 sort 表头，但是 getBlockAttrs 无法获得（只能获得很少的基本属性，是否需要用户先设置？）。如果手动设置sort之后是可用于 sql sort by 的话，根据 sort.json 通过 API 设置 sort 属性，应该就可以基本满足我的要求了，即使遇到个别排序不对的情况，也可以手动修改 sort数值。

应该可以关联查询自定义属性来做排序字段的。

**Comment by jabobian** [comment]
我做了一些测试，发现一些问题无法理解。有的文档节点的 sy_id 在 sort.json 文件里面没有定义。所以我先假设 setBlockAttrs 时使用 默认值1.
通过脚本我设置了所有的子节点，属性为 custom-sort1，在属性窗口中显示 sort1.
然后，我用模板，但是  Order by custom-sort1，和 Order by sort1 都没有效果，模板直接不显示任何东西。我的理解是用户自定义属性目前还不能直接用来 sort order。

**Comment by 88250** [comment]
@jabobian 自定义属性不保存在 blocks 表里，保存在 attributes 表，需要关联查询。

**Comment by jabobian** [comment]
D大能否给一个简单的关联查询例子（链接），我这方面没有太多经验，测试了下面的代码
`select blocks.* from blocks LEFT JOIN attributes ON blocks.id=attributes.id WHERE blocks.type= 'd'  AND blocks.path like '%/20211109165943-jwnnmbh/______________-_______.sy' Order BY attributes.id`
得到的结果等同没有用attributes，但是下面的代码
`select blocks.* from blocks LEFT JOIN attributes ON blocks.id=attributes.id WHERE blocks.type= 'd'  AND blocks.path like '%/20211109165943-jwnnmbh/______________-_______.sy' Order BY attributes.custom-sort1 （或attributes.sort1）`
都没有结果。在/20211109165943-jwnnmbh/路径下的子文档（对应.sy文件）都有sort1属性

**Comment by jabobian** [comment]
又试了一个
`select b.* from blocks b JOIN attributes a ON b.id=a.block_id WHERE b.type= 'd' AND b.path like '%/20211109165943-jwnnmbh/______________-_______.sy' AND a.name='custom-sort1' Order BY cast(a.value AS unsigned)`
虽然我没理解上面的代码，纯瞎编的。
但是排序也不正确，对于custom-sort1的value相同的几个节点，顺序和文档树上不同。

不过如果没有别的方案，只能考虑用小数点了。

**Comment by jabobian** [comment]
kernel/model/file.go 的 reindexblocktree 的代码原理还是没看懂，无从下手

**Comment by 88250** [comment]
这个只能自己试着理解了，如果不熟悉 SQL 和 golang 的话估计要花挺多时间的。

**Comment by jabobian** [comment]
D大，看代码是在 siyuan-master\kernel\util\path.go 里面使用 
`func TimeFromID(id string) (ret string) {
	ret = id[:14]
	return
}`

所以改成下面的就可以，14指的是length （flength），之前也试过14是可以的，但不敢确认，因为不清楚为什么不用更直观的规则（例如id），找到这块代码后就可以了。
`
select b.* from blocks b LEFT JOIN attributes a ON b.id=a.block_id WHERE b.type= 'd' AND b.path like '%/20211109165943-jwnnmbh/______________-_______.sy' AND a.name='custom-sort1' Order BY cast(a.value AS unsigned),14
`
