### ISSUE TITLE
希望修改公式时可以做到无鼠标操作

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5185]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

无论是行内公式还是公式块，如果需要修改，目前的编辑流程包括：

1. 鼠标点击公式，弹出公式编辑窗口 
2. 在窗口内修改 
3. 鼠标点击窗口外部 或 按 ESC，公式编辑窗口关闭
4. 把 “光标” 重新定位在要继续编辑的地点 （如按 ESC 关闭，则光标会在公式后方）

可以看出，流程比较繁琐，多次需要鼠标，产生的体验缺陷如：

1. 第一次鼠标需要点到公式上，才能弹出编辑窗口，如果一行内有多个短公式，如 $\alpha$,  $\beta$ 这种，(i) 不容易点准  (ii) 每个小公式都要操作一遍
2. 如果通过鼠标关闭编辑窗口，需要人为定位刚才的“修改点”，心智负担重

### 描述可能的最优解决方案 Describe the optimal solution

希望能在编辑公式过程中，不需要鼠标的参与

设想的编辑流程：

1. 通过左右键移动光标，假设此时 “自左向右” 移动光标
2. 当遇到公式时，
    1. 再按“右键” （或 ”shift-右键“ 之类的，以保持默认行为和现在一致），弹出公式编辑窗口 （目前的逻辑是 “右键” 会直接跳过公式）
         1. 此时，再按 “右键” 关闭编辑窗口（放弃编辑），跳过公式，光标位于公式后方 
         2. 但如按 “下键”，进入公式编辑  
             1.  编辑完成后，按 ESC，公式编辑窗口关闭，光标位于公式后方

其中差别在于 1.2.i, 1.2.i.b, 不需要鼠标点击就可以打开编辑窗口，和编辑公式。

其中 1.2.i.b.a 的逻辑目前已经存在，很合理，但由于现有流程中其他步骤需要鼠标，因此容易顺手用鼠标关闭窗口，反而没有用到它的好处。

**Comment by mlzxy** [comment]
> 同链接一样使用 ctrl+/ 处理如何？

刚刚试用了 `ctrl+/` (`cmd + /` in osx)，发现它是打开 context menu，感觉用不太上，也可能是我使用方式不对。

---

经过思考，感觉最合理的改进是： *保持现有功能不变，同时添加 `shift+左右键` 打开并聚焦公式编辑窗口的功能*


---

分析：

1. 现有功能有*很大优点*，即“光标”移动流畅快速。如果默认光标移动会打开窗口，则会干扰阅读思绪，降低体验。
2. 因此，需要基于现有功能，增加用键盘触发”公式编辑窗口“的渠道
3. 我感觉 `shift+左右键` 不错，因为这个按键默认是“选中文字后弹出tooltip，tooltip包括文字加粗/高亮等功能”，选中公式块也会展示 tooltip，但公式是不能高亮/加粗的，相当于浪费了这个按键组合。
   > 这里建议用起来，当光标左侧或右侧是“公式”时，`shift+左右键` 打开编辑窗口

**Comment by Vanessa219** [comment]
要把 cursor 放在链接上才行，否则就是块菜单。

**Comment by mlzxy** [comment]
![Untitled](https://user-images.githubusercontent.com/7659710/173732099-64892e27-ff7d-45b5-b21d-cc4d92100cf1.gif)

确实 tooltip 可以用，但似乎会把公式变成文本格式，可能不太好 （如上述 GIF）


我好像 cmd+/ 一直是块菜单 😂

**Comment by Vanessa219** [comment]
是不是没有升级版本，如下图位置按 ctrl+/
<img width="154" alt="image" src="https://user-images.githubusercontent.com/970828/173754362-0bdd73eb-c971-4a96-8cfb-89ff3850353e.png">

**Comment by mlzxy** [comment]
> 是不是没有升级版本，如下图位置按 ctrl+/ <img alt="image" width="154" src="https://user-images.githubusercontent.com/970828/173754362-0bdd73eb-c971-4a96-8cfb-89ff3850353e.png">

抱歉，确实没有，我升级到 2.0.19 试试，目前是 18

**Comment by Vanessa219** [comment]
嗯，你体验下，可以的话就统一用 ctrl+/

**Comment by mlzxy** [comment]
![Untitled](https://user-images.githubusercontent.com/7659710/173765808-f0a346d9-b9ae-48fb-afb5-2a835e5e43bf.gif)


更新了，在链接上可以里，但在公式上还不太行

**Comment by Vanessa219** [comment]
目前只有链接，可以的话那就下个版本添加。
