### ISSUE TITLE
增加伺服状态下浏览授权访问码

### ISSUE THREAD

**Issue by owlinMay** [siyuan-note/siyuan#5186]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当我想跟他人分享我在思源笔记内所写文章时，我需要将其作为md文档导出，但这会丧失许多思源笔记独有的特性，如双链。虽然可以思源笔记在导出文档时可以附带链接内容，但毕竟显得庞杂。

我的解决方案是将思源笔记部署在服务器上，然后通过伺服功能让他人在网页中直接查看我的思源笔记原生文档。

但问题是，他人可以查看我的思源笔记文档，意味着可以编辑我的思源笔记文档。这使得我只能将文档分享给我信任的人，以免他们对文档作出修改。

我希望可以在伺服状态上，让他人仅仅拥有浏览笔记的权限但没有修改笔记的权限。

### 描述可能的最优解决方案 Describe the optimal solution

将访问授权码分为浏览访问授权码和编辑访问授权码。
当输入浏览访问授权码时仅仅可以查看内容，当输入编辑访问授权码时才可以对笔记内容进行修改操作

**Comment by 88250** [comment]
* 分享可以考虑导出导入 `.sy.zip`，这样可以保留所有特性
* 服务器伺服可以添加内核参数 `--readonly` 实现只读模式

感谢提议。

**Comment by 88250** [comment]
@JhonCX 是的，需要自己处理数据同步，如果是订阅用户的话可以用云端同步。

**Comment by AlienHub** [comment]
> * 分享可以考虑导出导入 `.sy.zip`，这样可以保留所有特性
> * 服务器伺服可以添加内核参数 `--readonly` 实现只读模式
> 
> 感谢提议。

能否通过两个docker容器同时使用一个工作区，一个使用只读运行，一个可以编辑？ 我同时开两个容器后其中一个就会挂掉。
