### ISSUE TITLE
滚动式 Dailynote

### ISSUE THREAD

**Issue by philhappy** [siyuan-note/siyuan#5187]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

dailynote 不好查看和管理

### 描述可能的最优解决方案 Describe the optimal solution

希望能改成类似Logseq那样滚动式的dailynote

**Comment by winter60** [comment]
1. 希望支持自定义查询，这样就不仅仅是dailynote可滚动了~ 
2. 更希望是一种新的页签，不仅仅是嵌入的挂件，这样就能分屏进行编辑和拖动。
3. 最好能支持超链接一键打开这样的页签
对不起，说得太多无理的需求了，只是太想要了~😭😭😭
太高兴有人提这样的需求了😭😭😭😭😭，一步步来吧，有个挂件先实现也好~

**Comment by qifengle1998** [comment]
我就想要日历面板那样，
反正可以在多篇dailynote间流畅地阅读就行

**Comment by winter60** [comment]
> 我就想要日历面板那样， 反正可以在多篇dailynote间流畅地阅读就行

如果只是连续阅读的话，嵌入块能或许能满足你的需求。
如果你想要通过日历面板跳转的话，可以用query挂件（支持向右分屏 alt+单击链接），或者siyuan-calendar挂件，或者Daily Views挂件。
这些暂时都可以先用着。


但以上我都觉得不好用😂

**Comment by qifengle1998** [comment]
> > 我就想要日历面板那样， 反正可以在多篇dailynote间流畅地阅读就行
> 
> 如果只是连续阅读的话，嵌入块能或许能满足你的需求。 如果你想要通过日历面板跳转的话，可以用query挂件（支持向右分屏 alt+单击链接），或者siyuan-calendar挂件，或者Daily Views挂件。 这些暂时都可以先用着。
> 
> 但以上我都觉得不好用😂

我也觉得都不好用，我讨厌挂件，都没用， 现在日记都写在别的软件上去了。

**Comment by woaihuangxueying** [comment]
现在的dailynote，都是孤立分割开的，
只能通过文档树一个一个点。
我不知道什么样子是优秀的设计，
但是现在这种情况一定不是。

**Comment by Tlonglan** [comment]
> 我就想要日历面板那样， 反正可以在多篇dailynote间流畅地阅读就行

想要+10086

**Comment by woaihuangxueying** [comment]
> > 我就想要日历面板那样， 反正可以在多篇dailynote间流畅地阅读就行
> 
> 想要+10086

我第一次用思源的时候，以为左上角那个日历图标就是日历面板，结果只是一个选择器😂

**Comment by qifengle1998** [comment]
是可以像时间轴一样，把每天的笔记连接起来展示吗？
![E8C752B802DED50F2BF9D655704B8314](https://user-images.githubusercontent.com/37429029/175183261-a923e6a9-64b2-417c-8006-c4339a114259.jpg)

**Comment by winter60** [comment]
> 是可以像时间轴一样，把每天的笔记连接起来展示吗？

如果支持自定义查询，所有笔记应该就能这样，不知道后续会怎么开发~
