### ISSUE TITLE
支持设置启动时关闭所有页签

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#5189]
https://ld246.com/article/1655031666199/comment/1655221543323#comments

设置 - 文档树 - 启动时关闭所有页签

`config.filetree.closeTabsOnStart`

**Comment by woniuxia** [comment]
V 大，会考虑打开特定的页签吗？
https://github.com/siyuan-note/siyuan/issues/5258

**Comment by netdog2019** [comment]
> 

赞~~

**Comment by Vanessa219** [comment]
> V 大，会考虑打开特定的页签吗？ #5258

如果设置为关闭所有页签，钉住的页签依旧会打开。因此需要特定打开的页签可以进行顶住。
