### ISSUE TITLE
路径带 `%20` 的图片清理和导出 TextBundle 问题

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#519]
### 描述问题 Describe the problem

在使用资源清理后，无法显示带空格的图片。且textbundle无法导出带空格的图片。估计是引用了带空格的图片但是思源不认为自己引用了导致的。

PS：清理前可以正常显示

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/16791452/99336695-6649b000-28bc-11eb-8f9e-f963be2908a4.png)
![image](https://user-images.githubusercontent.com/16791452/99337063-8e391380-28bc-11eb-8e73-27f64f5a696c.png)

### 版本环境 Version environment

* 版本 Version：0.4.6
* 操作系统 Operating system：windows10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，请问是否打开了这个选项：

![image](https://user-images.githubusercontent.com/873584/99609773-7fcd3200-2a4b-11eb-9fb3-91faa7cd448e.png)

**Comment by frankli998** [comment]
我目前是打开了。但打不打开都一样，在支持带空格图片的功能出来之前该bug已经存在，打开之后依然存在。

**Comment by 88250** [comment]
这个选项打开以后应该就支持带空格的链接了，请看录屏：

![issue](https://user-images.githubusercontent.com/873584/99610543-00d8f900-2a4d-11eb-8a93-316bb6e3dd05.gif)

**Comment by frankli998** [comment]
我知道，打开选项后显示是没有问题的。但是请测试导出textbundle和资源清理。textbundle无法导出带空格的图片，资源清理会错误清理带空格的图片

**Comment by 88250** [comment]
上面的录屏中已经演示了带空格路径图片导出 TextBundle，下面的录屏演示清理资源：

![issue](https://user-images.githubusercontent.com/873584/99611651-08010680-2a4f-11eb-8f37-00796baf0fce.gif)


请注意，这个选项设置以后需要重启。如果还是有问题，麻烦等 v0.4.8 发布以后再试试看，谢谢。

**Comment by frankli998** [comment]
我明白了，也许不是空格的问题，是外部文件操作的问题。我把图片通过win10文件管理器拖入asset文件夹后能正常显示，但是没有被识别为引用。如图
![Uploading image.png…]()

**Comment by frankli998** [comment]
已经debug了，以前空格用%20代替后有这个问题，现在用了正常的空格后没问题了。（想要复现可以用引用时用%20代替空格，但是已经没必要了）

**Comment by frankli998** [comment]
assets/数大 HW2%206.png 能正常显示，无法导出，会错误清理资源
assets/数大 HW2 6.png 能正常显示，可以导出，不会错误清理资源

总结：不要用%20代替空格，正确的做法是打开选项然后用原生空格

**Comment by 88250** [comment]
感谢帮忙分享排查。`%20` 是标准用法，所以无论是否开启空格开关都应该支持，这确实是个 bug，我们稍后进行改进。
