### ISSUE TITLE
在 PDF 中直接进行标注

### ISSUE THREAD

**Issue by TankNee** [siyuan-note/siyuan#5192]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在阅读浏览 PDF 文件的时候，看到一些句子想要标注，但是只能在用颜色标记之后复制链接到文档中进行注解，实在是麻烦。

### 描述可能的最优解决方案 Describe the optimal solution

在 PDF 中用颜色标记文字之后可以直接弹出一个注解框来记录想法。

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

可以跟笔记文档中的批注功能一样。
<img width="558" alt="image" src="https://user-images.githubusercontent.com/43956168/173844108-cff8c566-9e80-4bd3-9655-98fd5f492563.png">

**Comment by 88250** [comment]
之前有过提议 https://github.com/siyuan-note/siyuan/issues/3359 

不考虑了，感谢理解。
