### ISSUE TITLE
粘贴链接文本时直接转化为 Markdown 链接

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5195]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前向Siyuan粘贴“链接”时，会以纯文本形式贴出，需要手动转化为链接，如下图：

![Untitled](https://user-images.githubusercontent.com/7659710/173975204-ff13db00-6554-420b-9602-38cd0b2ba56b.gif)

这个录屏体现了两个问题：

1) 链接以纯文本形式粘贴
2) 由于以纯文本粘贴，“/” 触发了菜单

虽然不影响使用，但还是希望能补充该功能

### 描述可能的最优解决方案 Describe the optimal solution

粘贴链接文本时，直接变成 Markdown Link

**Comment by 88250** [comment]
使用 Ctrl+K 插入链接。

**Comment by mlzxy** [comment]
感谢回复

这个能解决我的问题，但考虑到 Ctrl-V 是大众习惯（很多用户，尤其是非程序员，对于快捷键熟练度低的），如果能用 Ctrl-V 解决问题，感觉会对新用户更友好。所以还是值得低优先级考虑一下。

**Comment by liaozihang** [comment]
> 感谢回复
> 
> 这个能解决我的问题，但考虑到 Ctrl-V 是大众习惯（很多用户，尤其是非程序员，对于快捷键熟练度低的），如果能用 Ctrl-V 解决问题，感觉会对新用户更友好。所以还是值得低优先级考虑一下。

用过的好几个软件都是 Ctrl + K 或者L插入链接，建议习惯一下。

**Comment by mlzxy** [comment]
> > 感谢回复
> > 这个能解决我的问题，但考虑到 Ctrl-V 是大众习惯（很多用户，尤其是非程序员，对于快捷键熟练度低的），如果能用 Ctrl-V 解决问题，感觉会对新用户更友好。所以还是值得低优先级考虑一下。
> 
> 用过的好几个软件都是 Ctrl + K 或者L插入链接，建议习惯一下。

您用 GitHub 这个网站，就说明您不属于大众用户群体了。我并不是自己不习惯，而是想**提出建议，希望 Siyuan 能够做到细节上对各类用户都友好，而不只是程序员导向的小众软件**。至少 Typora, MarkText 等 Mac 上广泛被认可的软件，他们都实现了我上述所提到的功能，更不要说 Evernote，Onenote 了。

再者说，我这里并不是反对用 Ctrl+K 快捷键，而是希望把默认大众习惯的操作流做得更加人性化，这和 Ctrl+K 是不冲突的。

这也是小团队开发相比大团队开发的区别，小团队的优点是能快速做出突破性功能，缺点是难以做到面面俱到，细节打磨。 但如果开发人员觉得用户更应该学习工具，而不是工具应该吸收用户的建议，那么上述缺点就无法跨越，一个软件的天花板就被限制了。

**Comment by 88250** [comment]
这个还需要考虑下是否加入自动链接，谢谢。
