### ISSUE TITLE
希望能提供API, getBlockProperties

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5197]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

开发挂件过程中，需要获得当前 ID 所在文件夹，从而遍历子文档 .sy。
由于我的挂件不是基于go和模板语言，是第三方语言，所以需要 .sy 文件在操作系统中的路径。

现在 getBlockAttrs 没有 path 等属性。所以希望能提供 getBlockProperties，方便获得包括 blocks 表的所有字段

### 描述可能的最优解决方案 Describe the optimal solution

名称可以是其它名称，如 getBlockAttrsAll，等

**Comment by 88250** [comment]
可以用 SQL 接口获取。

**Comment by jabobian** [comment]
嗯，我是够懒的，早想到了SQL。多谢D大
