### ISSUE TITLE
模板中不能使用SQL关联查询

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5199]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

模版queryBlocks貌似不支持关联查询。我为当前页面的所有子页面设置了 custom-sort1 属性

`.action{$docid:=.id}
.action{$block:= (queryBlocks "select b.* from blocks b LEFT JOIN attributes a ON b.id=a.block_id WHERE b.type= 'd' AND b.path like '%/?/______________-_______.sy' AND a.name='custom-sort1' Order BY cast(a.value AS unsigned)" $docid )}
.action{range $v:=$block} 
- ((.action{$v.ID} ".action{$v.Content}")) 
.action{end}`

但在嵌入块中单独使用上述sql可以查询
`select b.* from blocks b LEFT JOIN attributes a ON b.id=a.block_id WHERE b.type= 'd' AND b.path like '%/20220427094830-fazfr5x/______________-_______.sy' AND a.name='custom-sort1' Order BY cast(a.value AS unsigned)`

### 期待的结果 Expected result

正常运行SQL关联查询

### 版本环境 Version environment

```markdown
- Version: 2.0.19
- Operating System: Win10
- Browser (if used):
```

### 日志文件 Log file

E 2022/06/15 09:30:46 block_query.go:487: query scan field failed: sql: expected 8 destination arguments in Scan, not 21
    github.com/siyuan-note/siyuan/kernel/sql.scanBlockRows(0xc001d84380?)
    	D:/88250/siyuan/kernel/sql/block_query.go:487 +0x258
    github.com/siyuan-note/siyuan/kernel/sql.selectBlocksRawStmt({0xc000d96de0, 0x29}, 0x20)
    	D:/88250/siyuan/kernel/sql/block_query.go:474 +0x152
    github.com/siyuan-note/siyuan/kernel/sql.SelectBlocksRawStmtNoParse(...)
    	D:/88250/siyuan/kernel/sql/block_query.go:415
    github.com/siyuan-note/siyuan/kernel/model.searchEmbedBlock({0xc000d96de0?, 0x10?}, {0xc0000da820, 0x2, 0xc00164d698?}, 0xc0000da820?)
    	D:/88250/siyuan/kernel/model/search.go:45 +0x65
    github.com/siyuan-note/siyuan/kernel/model.SearchEmbedBlock({0xc000d96de0, 0x29}, {0xc0000da820, 0x2, 0x2}, 0xc0019ad5e0?)
    	D:/88250/siyuan/kernel/model/search.go:41 +0x5a
    github.com/siyuan-note/siyuan/kernel/api.searchEmbedBlock(0xc000408900)
    	D:/88250/siyuan/kernel/api/search.go:141 +0x22b
E 2022/06/15 09:30:46 block_query.go:487: query scan field failed: sql: expected 8 destination arguments in Scan, not 21
    github.com/siyuan-note/siyuan/kernel/sql.scanBlockRows(0xc001d84380?)
    	D:/88250/siyuan/kernel/sql/block_query.go:487 +0x258
    github.com/siyuan-note/siyuan/kernel/sql.selectBlocksRawStmt({0xc000d96de0, 0x29}, 0x20)
    	D:/88250/siyuan/kernel/sql/block_query.go:474 +0x152
    github.com/siyuan-note/siyuan/kernel/sql.SelectBlocksRawStmtNoParse(...)
    	D:/88250/siyuan/kernel/sql/block_query.go:415
    github.com/siyuan-note/siyuan/kernel/model.searchEmbedBlock({0xc000d96de0?, 0x10?}, {0xc0000da820, 0x2, 0xc00164d698?}, 0xc0000da820?)

**Comment by 88250** [comment]
join 的结果完全必须匹配 blocks 表结构，不能少字段。

**Comment by jabobian** [comment]
我测试了一下，不是表结构全匹配的问题，是不支持cast,
queryBlock 里面不能用函数，类似 cast(xxxx AS unsigned) 这种。还请指点如何处理。

**Comment by 88250** [comment]
从报错看应该是字段结果不匹配：

```
E 2022/06/15 09:30:46 block_query.go:487: query scan field failed: sql: expected 8 destination arguments in Scan, not 21
```
