### ISSUE TITLE
页内搜索文本位于公式块中不会高亮

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#52]
### 描述问题

ctrl+F是页面内搜索，搜索的内容位于公式块内的时候内容不会高亮

### 期待的结果

如果搜索的内容存在于公式块之中，可以进入该公式块的编辑区域中，并高亮所搜索的文字。

### 截屏或录像

![image](https://user-images.githubusercontent.com/51868839/91640493-8b165000-ea50-11ea-8798-04187090dd78.png)

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/53 中一并处理。
