### ISSUE TITLE
文件树无法多选进行批量操作

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#520]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

希望批量删除无用的文件或者批量归档

### 描述最优的解决方案 Describe the optimal solution

类似windows文件管理器支持ctrl键多选（ctrl键似乎已经被在新标签打开占用）或者shift键（目前空闲）范围选取

### 其他信息 Other information

如果在windows文件管理器中批量移动，移动后的文件在思源中无法打开。因此必须通过思源实现批量管理文件的功能，否则一个个删除一个个移动有点痛苦。

**Comment by 88250** [comment]
在思源外部操作的话需要重启思源后才能看到结果，暂时先这样操作顶顶，谢谢反馈。

**Comment by frankli998** [comment]
哦，原来是没有在小托盘退出。这个workaround暂时可以接受
