### ISSUE TITLE
希望组件编辑窗口有语法高亮

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5204]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当编辑 Latex 公式，Mermaid 图，或任何使用弹出的组件编辑窗口时

### 描述可能的最优解决方案 Describe the optimal solution

目前弹出的公式/图等组件编辑窗口比较简单，是一个纯文本编辑器。

<img width="934" alt="image" src="https://user-images.githubusercontent.com/7659710/174039022-cc5bf6a7-67af-4c16-81b8-6c93e9b3512f.png">

但这些组件的书写通常需要使用某种编程语言，如 Latex, Mermaid/PlantUML 也有自己的语法。尤其是对于 Latex，其结构复杂，因此语法高亮能很好的帮助书写。

因此希望组建编辑窗口有语法高亮功能

**Comment by 88250** [comment]
这个暂时不考虑了，以后考虑能实现时再重开，感谢提议。
