### ISSUE TITLE
希望提供不弹窗的文本搜索功能

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5206]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在编辑文字时，我们经常会用 Ctrl+F 搜索某些关键词。

在大多数编辑器中，Ctrl+F 会触发页内搜索，用户不会离开当前编辑的界面

但在 Siyuan 中，目前 Ctrl-F 会打开一个大的窗口，完全盖在正在编辑的文档上，非常突兀，影响写作

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/7659710/174044013-2a76e5cd-13bd-4cdf-bf85-3e2a9516a8b0.png">

### 描述可能的最优解决方案 Describe the optimal solution

下面是 MarkText 的截图，也正是自己想要的效果：

![1](https://user-images.githubusercontent.com/7659710/174043616-8ac170d2-6790-493a-9418-6b0bb9ef226e.gif)

这也是绝大多数编辑器都遵循的页内搜索交互

**Comment by mlzxy** [comment]
感谢帮助，这个能满足需求，但是体验上还是有差距的：

1. 创建了第二个窗口，内容和本页面相同，只是有了搜索高亮，空间利用率低
2. 展示了其他页面的信息，但很多情况下并不需要

----

简而言之，我觉得需要标记的一个点是：“到底一个需求点是被 (a) 完美解决 (b) 仍有优化空间。“


如果是 (a) 则没有问题，但我认为这个 issue 提及的需求点目前仍处于 (b)，因为我们可以看到几乎所有主流编辑器都是采用了 MarkText 式的页内搜索 （Vim/Emacs 这类除外）。

如果是 (b), 希望开发者至少能在 close issue 的时候加一个 label，因为它明显还可以有提升的空间，只是优先级不够高，短期内精力有限要聚焦更重要的功能。 这个大家都理解，但不打任何标签，大家贡献的知识点就很难再找到了，而这些点是能够帮助 Siyuan 构建更好体验的，因此是社区的损失。

**Comment by 88250** [comment]
进一步的改进请关注 https://github.com/siyuan-note/siyuan/issues/3564
