### ISSUE TITLE
macOS 端窗口工具栏图标对齐问题

### ISSUE THREAD

**Issue by Marszs** [siyuan-note/siyuan#5209]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如图，窗口工具栏图标和系统的红绿灯没有对齐，请问有解决办法吗？

<img width="626" alt="image" src="https://user-images.githubusercontent.com/66620626/174103052-350477fb-aaea-4fba-9558-da5399da7d02.png">

思源版本：v2.0.20 mac arm-64

系统：m1 mac 12.4

### 期待的结果 Expected result

对齐

### 版本环境 Version environment

```markdown
.
```

### 日志文件 Log file

.

**Comment by 88250** [comment]
这个是设计如此，工具栏特意小一些的，暂时不考虑调整了，感谢反馈。
