### ISSUE TITLE
云端同步异常报错：An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by demo-will** [siyuan-note/siyuan#5211]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

云端同步异常报错：An existing connection was forcibly closed by the remote host

### 期待的结果 Expected result

云端同步正常

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/37354425/174202100-7fbecfca-ecb9-401e-a31c-5e3ad5b88a65.png)

### 版本环境 Version environment

```markdown
- Version: v2.0.20
- Operating System: WIN 10
- Browser (if used): Microsoft Edge 版本 102.0.1245.41 (正式版本) (64 位)
```

### 日志文件 Log file

I 2022/06/17 09:02:28 runtime.go:45: kernel is booting:
    * ver [2.0.20]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\08_universe\SiYuan, data 179 MB]
I 2022/06/17 09:02:28 conf.go:261: user has enabled [Automatically upload error messages and diagnostic data]
I 2022/06/17 09:02:28 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/06/17 09:02:28 sync.go:107: sync before boot
W 2022/06/17 09:02:29 osssync.go:810: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:5764->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
W 2022/06/17 09:02:29 osssync.go:810: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:5763->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
E 2022/06/17 09:02:32 osssync.go:500: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:7444->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
E 2022/06/17 09:02:32 osssync.go:500: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:7445->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
I 2022/06/17 09:02:33 conf.go:517: database size [20 MB], block count [5833]
I 2022/06/17 09:02:33 working.go:137: kernel booted
I 2022/06/17 09:02:37 sync.go:107: sync before boot
W 2022/06/17 09:02:37 osssync.go:810: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3957->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
W 2022/06/17 09:02:37 osssync.go:810: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3958->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
E 2022/06/17 09:02:40 osssync.go:500: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:3959->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
E 2022/06/17 09:02:40 osssync.go:500: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:3960->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
I 2022/06/17 09:02:51 sync.go:107: sync before boot
W 2022/06/17 09:02:52 osssync.go:810: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3962->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
W 2022/06/17 09:02:52 osssync.go:810: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3961->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
E 2022/06/17 09:02:55 osssync.go:500: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:3963->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
E 2022/06/17 09:02:55 osssync.go:500: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:3964->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
I 2022/06/17 09:03:04 sync.go:107: sync before boot
W 2022/06/17 09:03:05 osssync.go:810: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3991->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
W 2022/06/17 09:03:05 osssync.go:810: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3990->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
E 2022/06/17 09:03:08 osssync.go:500: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:3992->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
E 2022/06/17 09:03:08 osssync.go:500: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:3993->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
W 2022/06/17 09:03:43 osssync.go:810: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3997->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
W 2022/06/17 09:03:43 osssync.go:810: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:3998->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
E 2022/06/17 09:03:46 osssync.go:500: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:4000->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
E 2022/06/17 09:03:46 osssync.go:500: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:3999->180.101.136.89:443: wsarecv: An existing connection was forcibly closed by the remote host.
W 2022/06/17 09:08:48 osssync.go:810: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:4107->180.101.136.168:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
W 2022/06/17 09:08:48 osssync.go:810: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed [Post "https://up.qiniup.com": read tcp 10.32.2.44:4106->180.101.136.168:443: wsarecv: An existing connection was forcibly closed by the remote host.], retry it after 3s
E 2022/06/17 09:08:51 osssync.go:500: put file [D:\08_universe\SiYuan\sync\.siyuan\conf.json] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:4109->180.101.136.168:443: wsarecv: An existing connection was forcibly closed by the remote host.
E 2022/06/17 09:08:51 osssync.go:500: put file [D:\08_universe\SiYuan\sync\c095ff9\00fa653\b727617\a5bb34d\3b14998\12c0de7] to cloud failed: Post "https://up.qiniup.com": read tcp 10.32.2.44:4108->180.101.136.168:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by 88250** [comment]
可能是所在网络防火墙的原因，请切换个网络试试看。

我们先关闭了，如果还有问题请继续跟帖反馈，谢谢。
