### ISSUE TITLE
复制 PDF 高亮 Annotation 到笔记中时，对换行符的处理方式不适合英语

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5213]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在 Siyuan 中标记 PDF，并把 Annotation 复制到笔记中是个常用操作 （尤其对于经常用 Siyuan 读书的用户）。

但我发现，当复制PDF高亮到笔记时，文字的换行符会被删除，这对于CJK语言是合理的，因为CJK语言不存在单词这个概念。

但对于使用单词的语言（如英语），”删除换行符“存在如下问题：

1. 当”旧的行末“和”新的行始“是两个词时，这两个词会被连接在一起
2. 当”旧的行末“和”新的行始“是一个词时，往往会用 ”-“ 断开，此时单词中出现 ”-“

如下图GIF所示

![1](https://user-images.githubusercontent.com/7659710/174212441-91d51362-6c64-4225-aded-af6a2b6de100.gif)

### 期待的结果 Expected result

当复制英语时，作如下处理

1. 如果行末是 “-“，删除 ”-“ 和 换行符
2. 如果不是，替换换行符为“空格”

事实上，这就是 PDF Expert 的做法（OSX 下最好的 PDF 阅读器），我也尝试了 OSX 的 Preview，它的做法是把换行符替换为 “空格”，没有第一个优化。

### 版本环境 Version environment

```markdown
- Version: 2.0.20
- Operating System: osx bigsur 11.6.6
- Browser (if used):
```

### 日志文件 Log file

skip

**Comment by Vanessa219** [comment]
可以传一下这个 PDF 么？

**Comment by mlzxy** [comment]
好的

[Understanding Machine Learning_ From Theory to Algorithms-20220614223724-fyp4yx6.pdf](https://github.com/siyuan-note/siyuan/files/8933586/Understanding.Machine.Learning_.From.Theory.to.Algorithms-20220614223724-fyp4yx6.pdf)
