### ISSUE TITLE
文档树上添加搜索

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#5214]
https://ld246.com/article/1655435750849

**Comment by luy98** [comment]
能否做一个全局的搜索文档（类似typora的快读打开文档功能），这样不止是文档树的抬头有，所有位置就都可以使用了

**Comment by 88250** [comment]
@luy98 Ctrl+P

**Comment by 88250** [comment]
这个特性不考虑了，因为文档树面板上加入搜索框的话和全局搜索标题类型过滤功能上有重叠，后续改进方向应该是支持全局搜索配置多个过滤器，比如可以配置一个仅标题类型的，方便切换搜索。
