### ISSUE TITLE
不同的文本样式无法叠加

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5219]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

发现 Siyuan 目前不支持文本上有多种样式，即一个文字只能被高亮，或者下划线，但不能同时。

<s>`感觉这个 BUG 蛮严重的，比如一个用户高亮了一片区域，那么这个区域内的文本样式就都没了`</s> 倒是可以 undo  😺 

下面给一个GIF：

![1](https://user-images.githubusercontent.com/7659710/174225993-4c46607e-c0a9-4388-9f46-432f9063e00c.gif)

### 期待的结果 Expected result

文本可以支持有多种样式，如 高亮/粗体/行内代码 等等

### 版本环境 Version environment

```markdown
- Version: 2.0.20
- Operating System: OS X bigsur 11.6.6
- Browser (if used):
```

### 日志文件 Log file

skip

**Comment by isyngo** [comment]
可见#2911
