### ISSUE TITLE
/api/template/render 支持传入 markdown 字符串

### ISSUE THREAD

**Issue by langyamu** [siyuan-note/siyuan#5220]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

例如在日历挂件中想预览任务列表块下的列表项时 ，
最终效果类似  cc-template 那种 在挂件中通过点击块然后调取siyuan的悬浮窗预览

### 描述可能的最优解决方案 Describe the optimal solution

/api/template/render 支持传入 markdown 字符串

**Comment by 88250** [comment]
用模板接口估计不适合，因为这个接口会重新生成 ID。我不太明白你最终需要的效果是啥，如果是块引浮窗或者块标浮窗的效果的话，估计要等 #5066

**Comment by langyamu** [comment]
换种说法是在 挂件中 预览块内容，因为块数据里有 markdown 文本，所以想通过 将markdown 转换为 html 来实现，但是。。自己手写还得匹配各种样式，所以想可不可以有个接口来实现 markdown 转 思源的 html ，正好看见 /api/template/render 返回的就是一串 思源的html 所以就提了下这个 issue

**Comment by 88250** [comment]
明白了，那还是等前端 API 比较保险，我们先关闭了，谢谢。
