### ISSUE TITLE
导出 Word 时可选择不导出资源文件

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5223]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在导出word .docx时弹出的另存为对话框中所谓“文件名”选择的竟然是文件夹，我总以为输入的是导出后的docx文件名。
每次创建一个文件夹，搞得很混乱，因为我只需要导出的docx文件，assets 文件夹里面的图片之类的已经在word文件中有了，这个assets文件夹也没有必要。

所以希望默认导出成单个 docx 文件，不带 assets 文件夹，

### 描述可能的最优解决方案 Describe the optimal solution

约定在另存为对话框中输入的如果是文件名（带docx后缀），就只导出单个docx文件，否则导出成文件夹和assets。
当然，用文档属性也可以。
感谢！

**Comment by Morganwan90** [comment]
我觉得pdf也应该这样...

**Comment by Morganwan90** [comment]
> @Morganwan90 PDF 已经支持了。

啊D大，我的意思是原文说的“输入的如果是文件名（带docx后缀），就只导出单个docx文件，否则导出成文件夹和assets。”
现在导出pdf的话，他也是生成的一个文件夹，里面有一个pdf文件...要是能直接导出单个文件（不生成文件夹）感觉更直接好用一点。

**Comment by 88250** [comment]
@Morganwan90 哦，明白了，这个等后面再收集反馈看看。
