### ISSUE TITLE
添加文档树 `删除文档时不需要确认` 选项 

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5225]
https://ld246.com/article/1655519534981

新增配置项 `Conf.fileTree.removeDocWithoutConfirm`

**Comment by woniuxia** [comment]
![image](https://user-images.githubusercontent.com/16383685/174465979-47b1f448-5e57-4a27-b36c-10c21e99718f.png)
蓝色框框那里是不是也加上这个选项更好

**Comment by 88250** [comment]
@woniuxia 一般这个选项不会经常调整，就不放在外面了。

**Comment by woniuxia** [comment]
> @woniuxia 一般这个选项不会经常调整，就不放在外面了。

放在外面，可以让大家知道有这个功能，而且，可以直接进行设置，不需要进入到配置项里面。

**Comment by 88250** [comment]
这是显然的，但是缺点就是不常用选项放在外面容易造成干扰。

另外如果这个选项这样设计，那类似的选项是否也需要考虑呢？
