### ISSUE TITLE
行级数学公式无法正确渲染

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#523]
### 描述问题 Describe the problem

如题

````````markdown
- $Latex_{support}$

````````

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/16791452/99372836-b09e5180-28fb-11eb-95a2-95cb0e264ddb.png)

### 版本环境 Version environment

* 版本 Version：0.4.7
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/99392831-527f6780-2917-11eb-97ff-8fb56deb996c.gif)

@Vanessa219
