### ISSUE TITLE
搜索功能不足（不好描述，看图）

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#5234]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/97490782/174444470-91301872-0c50-448e-8c39-af02167884a9.png)
比如有图中这样的层级结构，当我想搜到OCR这个文档时，按C-p，然后输入 
```
python OCR
```
是搜不到OCR这个文档的，只有输入OCR，然后看右边的路径才知道哪个是我想要的。
搜索的时候这样输入上层目录名辅助定位应该是比较自然的方式吧，可以考虑加一下

### 描述可能的最优解决方案 Describe the optimal solution

搜索的时候把各层级文件名也考虑进去

**Comment by 88250** [comment]
目前可以使用 SQL 进行高级搜索，具体请参考帮助文档搜索进阶章节。

后续会考虑在文档树上加上搜索文档名的功能，请关注 https://github.com/siyuan-note/siyuan/issues/5214

感谢反馈。
