### ISSUE TITLE
按#呼出的标签列表不会更新

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#5238]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

按#呼出的标签列表不会更新

### 期待的结果 Expected result

及时更新按#呼出的标签列表

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/35998162/174479678-60aa4f41-3656-4d72-a01b-e0885f559dfc.png)

### 版本环境 Version environment

```markdown
- Version: 2.0.21
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[Uploading siyuan.log…]()

**Comment by 88250** [comment]
继续输入才能进行搜索过滤。

**Comment by 88250** [comment]
我们先关闭了，如果还有问题请继续跟帖，谢谢。
