### ISSUE TITLE
Too many tabs get open

### ISSUE THREAD

**Issue by jeison-AK** [siyuan-note/siyuan#5239]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Multiple tabs get open while using the program

### 描述可能的最优解决方案 Describe the optimal solution

it could have a similar behavior as the one we have on vs code regarding to tabs, they a new tab will get open over the one we where in if we didn't edit anything on the previous tab.

**Comment by leolee9086** [comment]
maybe you can try this
![image](https://user-images.githubusercontent.com/19915077/174486524-f1c2bb47-5c81-4b4c-98c8-1a3c6a1cca46.png)

**Comment by jeison-AK** [comment]
Perfect that's was I was looking for!! that feature probably should has a little spot in the guide
