### ISSUE TITLE
导出为pdf时文章末尾多出一部分前面的内容

### ISSUE THREAD

**Issue by HzfinChina** [siyuan-note/siyuan#5240]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

linux系统，单个文档导出为pdf时文章末尾会多出一部分前面的内容

### 期待的结果 Expected result

导出pdf顺序正确、内容不增不减

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/101701076/174507521-49603249-4b8f-49b4-aa21-ff2524b86fd1.mp4

见视频，在导出的pdf里，末尾本应该是第9-8节结束，但是多出了9-4，9-5节 

### 版本环境 Version environment

```markdown
- Version: 2.0.12
- Operating System:  ubuntu20.04 LTS
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8936746/siyuan.log)

**Comment by SurpriseLon** [comment]
导出html时也是这样，明明想导出一页，结果这页下面包含的页面也全部都在这一页上

**Comment by 88250** [comment]
请升级到最新版后再看看，如果还有问题，麻烦提供 .sy 文件，如果不方便公开的话请发到 845765@qq.com 谢谢。

**Comment by HzfinChina** [comment]
> 请升级到最新版后再看看，如果还有问题，麻烦提供 .sy 文件，如果不方便公开的话请发到 [845765@qq.com](mailto:845765@qq.com) 谢谢。

最新版仍然如此，已发

**Comment by 88250** [comment]
你好，已经收到数据。我们看了下，最后那部分是块引用转换的脚注，从第 18 页，分隔线下面开始是脚注列表：

![image](https://user-images.githubusercontent.com/873584/175763109-1d405bcb-05fc-4e8c-9a0c-799da3b9c5f6.png)

如果不需要块引转换脚注的话，可以选择其他的导出方式：

![image](https://user-images.githubusercontent.com/873584/175763153-db1b0d7b-442e-42f5-b792-2fcbfa0132dc.png)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
