### ISSUE TITLE
希望添加在多个打开的文档之间跳转的功能快捷键

### ISSUE THREAD

**Issue by HzfinChina** [siyuan-note/siyuan#5242]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

需要参考不同的笔记时需要不停地切换文档，需要用鼠标点击。

### 描述可能的最优解决方案 Describe the optimal solution

希望能像浏览器一样，通过给标签页编号(从左到右),能通过快捷键实现在页面间的跳转

### 描述候选的解决方案 Describe the candidate solution

给文档从左到右一次编号，通过快捷键比如Ctrl + 2跳转到左起第二个文档

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3293
