### ISSUE TITLE
可调节的自适应宽度和全屏宽度快速切换

### ISSUE THREAD

**Issue by philhappy** [siyuan-note/siyuan#5243]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

文档浏览和记录时

### 描述可能的最优解决方案 Describe the optimal solution

参照Notion 和 wolai

**Comment by 88250** [comment]
宽窄模式暂时还不确定是否需要，因为支持拆分多窗口，所以宽模式应该是较为常用的。两边留白的窄模式不一定好用，这个等限制页签 https://github.com/siyuan-note/siyuan/issues/2098 完成以后再看情况看看，感谢反馈。
