### ISSUE TITLE
列表项中包含多个块时 Ctrl+↑/↓ 功能等同于点击三角形

### ISSUE THREAD

**Issue by MoonBottle** [siyuan-note/siyuan#5244]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

问题 1，无序列表同级节点，使用 alt + click 执行折叠/展开操作会联动，command + ⬆️ 操作正常
![image](https://user-images.githubusercontent.com/12904505/174514497-ced8d3c8-86bb-4b65-aaac-3cac7a720d6b.png)

问题2，节点下包含图片的时候，使用快捷键 command + ⬆️ ，折叠图片后无法再次展开
![image](https://user-images.githubusercontent.com/12904505/174514803-1c176854-6647-4c60-9c27-10a0b1b62487.png)

### 期待的结果 Expected result

问题 1，不需要联动
问题 2，不应该能折叠或者是可以再次展开

### 版本环境 Version environment

```markdown
- Version: 2.0.22
- Operating System: mac 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
1. alt+click 功能设计如此，ctrl+arrowup 功能等同点击三角形图标
<img width="202" alt="image" src="https://user-images.githubusercontent.com/970828/174597978-9a17f971-10cd-409b-bd22-da7d461d3f45.png">

2. 按照以下操作，是可以进行折叠和取消折叠的，是哪里操作不对么？

https://user-images.githubusercontent.com/970828/174598910-0e4eadd1-8796-41bb-a5f5-55d042fdb4cc.mp4

**Comment by Vanessa219** [comment]
再按一次 ctrl+arrowup 就可以展开了。
如果列表项只有一个块的话，是不会出现折叠的三角形图标。这时 ctrl+arrowup 的折叠针对的是当前块的折叠。
