### ISSUE TITLE
“关闭按钮设置”问题

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#5245]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

设置“关闭按钮设置”，会影响到外观模式的切换，详情见录屏

### 期待的结果 Expected result

关闭按钮设置应该是独立的

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/16383685/174526264-ecf5033c-fb47-4978-a95d-c0ae48f7ad02.mp4

### 版本环境 Version environment

```markdown
- Version: 2.0.22
- Operating System: Windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8937544/siyuan.log)

**Comment by 88250** [comment]
我们这里重现不了问题，请在默认主题下测试。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
