### ISSUE TITLE
折叠标题带子标题改变层级

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5246]
https://ld246.com/article/1655699875950

**Comment by choyy** [comment]
![图片](https://user-images.githubusercontent.com/68107073/174693691-66472edb-3adc-4fea-814b-f8fa76bb826d.png)
其实折叠后标题的删除、剪切、复制也应该带上被折叠的内容
目前是不带的

**Comment by 88250** [comment]
折叠标题带子级改变层级不考虑了，升降标题层级还是分开为两个入口：

* 不带子级
* 带子级

已在 https://github.com/siyuan-note/siyuan/issues/2860 中记录。
