### ISSUE TITLE
windows闪退

### ISSUE THREAD

**Issue by yanke1311** [siyuan-note/siyuan#5247]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在新的windows上第一次使用，启动界面直接切换到onedrive上的backup，发现随后笔记闪退，重启电脑无效，其后卸载并在windows store上重装，启动界面也不再有就直接闪退

### 期待的结果 Expected result

正常加载

### 版本环境 Version environment

```markdown
- Version: 2.0.22.0
- Operating System: windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8938336/siyuan.log)

**Comment by 88250** [comment]
内核日志没有发现问题，建议看下是不是杀毒软件/防火墙设置问题，加下信任区试试。

先关闭了，还有问题请继续跟帖，谢谢。
