### ISSUE TITLE
重启后已经存在的页签动态加载失效

### ISSUE THREAD

**Issue by ZinYY** [siyuan-note/siyuan#5255]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在升级到v2.0.22 版本后，长文档的输入非常卡顿。经过观察，发现只有第一个打开的文档的懒加载机制生效了 (只渲染当前打开的section)；而其他文档的大纲都会全部展开并加载，如下图所示，导致输入非常卡顿。
<img width="342" alt="image" src="https://user-images.githubusercontent.com/17381012/174617844-e5202f88-91ea-453e-8290-158725843cce.png">

### 期待的结果 Expected result

懒加载机制应该全局生效

### 截屏或者录屏演示 Screenshot or screen recording presentation

如上图所示，除了第一个打开的文档，其余文档懒加载机制失效。

### 版本环境 Version environment

```markdown
- Version: v2.0.22(我是从2.0.16版本直接升级的，并不知道中间几个版本是否存在类似问题)
- Operating System: MacOS Monterey
- Browser (if used): N/A
```

### 日志文件 Log file

N/A

**Comment by 88250** [comment]
目前动态加载不会移除已经加载过的内容，可以通过 F5 刷新缓解。

#4620

**Comment by ZinYY** [comment]
> 

F5 之后确实可以了，但问题是打开文档时，会自动加载所有内容 (除了首次打开的第一个文档)。

**Comment by 88250** [comment]
这个我这里重现不了，方便发一下 .sy 么？

**Comment by ZinYY** [comment]
> 这个我这里重现不了，方便发一下 .sy 么？

我这里可以完全复现，方法是打开多个文档，此时退出思源笔记并重新打开，就会出现该情况 (即首个文档之外的其他文档动态加载失效)。

**Comment by ZinYY** [comment]
[example 动态加载失效.zip](https://github.com/siyuan-note/siyuan/files/8941453/example.zip)
可以试试这两个文档，try1.sy以及try2.sy，打开这两个文档 (两个标签页), 点击try1这个文档后，退出并重新打开思源笔记。重新进入后发现try1的动态加载正常，而try2的动态加载失效。

**Comment by 88250** [comment]
谢谢，能够重现问题了。
