### ISSUE TITLE
重启软件时，希望能直接跳转到上次的编辑位置，而非文档的开头处

### ISSUE THREAD

**Issue by ZinYY** [siyuan-note/siyuan#5257]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

重启软件时

### 描述可能的最优解决方案 Describe the optimal solution

重启软件时，希望能直接跳转到上次的编辑位置，而非文档的开头处。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/4042
