### ISSUE TITLE
首页功能

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#5258]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

D大好，希望添加首页功能。
可以将一些天气预报/每日英语/每日诗词/每日热榜等 ifram或挂件块放在首页中，每天首次打开思源的时候的时候可以考虑展示该页面。可以帮助了解一些信息。
也可以使用sql查询等机制，简单回顾昨天的笔记或者工作内容。
也可以直接写下今日的工作安排等。

### 描述可能的最优解决方案 Describe the optimal solution

1. 设置中添加首页配置，支持指定每日首次打开展示的页面
2. 思源当前除了父目录，其他每个子目录都可以存放内容信息。考虑父目录支持存放内容信息。

### 描述候选的解决方案 Describe the candidate solution

优先支持改动点1

**Comment by 88250** [comment]
目前可以用钉住页签+挂件简单实现，长期估计要等 #5086
