### ISSUE TITLE
移动端菜单被侧边面板遮挡

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5259]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

由于移动端悬浮菜单层级较低, 因此在侧面功能面板展开时会被遮挡

![image](https://user-images.githubusercontent.com/49649786/174712508-31003e9f-f99f-4921-ad99-98d19e94dbe4.png)

复现步骤:
1. 打开侧边功能面板
2. 选择文档树面板
3. 单击文档树中某篇文档的 <kbd>更多</kbd> 按钮

### 期待的结果 Expected result

提高悬浮菜单的显示层级

### 版本环境 Version environment

```markdown
- Version: 2.0.22
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5254
