### ISSUE TITLE
[新功能请求]允许表格堆叠

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#5261]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![示例图1](https://pic3.zhimg.com/80/v2-24449da6b60f763c1edcf7f698aac770_720w.jpg?source=1940ef5c)
![实例图2](https://pic1.zhimg.com/80/v2-472f16fa399c10610acee4601fcfb4af_720w.jpg?source=1940ef5c)
在进行一些较为复杂排版的时候需要用到

### 描述可能的最优解决方案 Describe the optimal solution

有这个特性的软件:OneNote

**Comment by 88250** [comment]
思源中的表格是叶子块，不是容器块，因此无法实现父子关系。

如果实在需要，可以考虑用 HTML 块，谢谢。
