### ISSUE TITLE
包含 `Enter` 的组合快捷键设置错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5264]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在 #5231 中将按键 `Enter` 替换为了 `↩`, 但是使用 API `/api/setting/setKeymap` 设置快捷键时依然使用 `Enter` 导致所有包含 `Enter` 的组合快捷键失效, 该 API 请求体的一部分如下所示
```json
{
    "default": "⇧⌘A",
    "custom": "⌘Enter" // 不能生效, 应该更改为  "⌘↩"
}
```

### 期待的结果 Expected result

包含 `Enter` 的组合快捷键可以正常使用

### 版本环境 Version environment

```markdown
- Version: `2.0.22`
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

关联 https://github.com/siyuan-note/siyuan/issues/5172#issuecomment-1162600853

**Comment by Vanessa219** [comment]
抱歉，还麻烦下个版本发布后再手动设置一下。
