### ISSUE TITLE
文档第一个块使用查询嵌入块触发状态异常

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5267]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

当尝试在子页面引用父页面中的 block 时，编辑器会崩溃

如下 GIF

![1](https://user-images.githubusercontent.com/7659710/175046065-ba324a55-de43-4475-bd1b-7f6b94349b9f.gif)

### 期待的结果 Expected result

能够成功引用父页面

### 版本环境 Version environment

```markdown
- Version: 2.0.23
- Operating System: osx 11.6.6
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8958246/siyuan.log)

**Comment by mlzxy** [comment]
似乎如果 块引用 不在全文第一行，就不会有这个问题。

**Comment by 88250** [comment]
好像和父子文档没有关系，文档第一个块使用查询嵌入块好像都有问题。

@Vanessa219
