### ISSUE TITLE
通过某种方式链接到某个文档中的某个标题的内容

### ISSUE THREAD

**Issue by GaN601** [siyuan-note/siyuan#5268]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在A文档中引用B文档中的某个标题的信息

### 描述可能的最优解决方案 Describe the optimal solution

Obsidian的[[这是一个文档#这是某个标题|这是一个显示出来的别名]]

### 其他信息 Other information

你好, 我想要从Obsidian迁移到思源, 因为Obisdian的表格用起来实在是太难受了.
我在官网和github上看到的帮助文档实在是太简陋, 翻了好久才知道(())是这里使用的双链. 虽然好像[[]]也支持的样子.

需求: 我希望能引用某个文档中的某个标题的信息, 而不是整个文档. 我该如何做?
比如, 一个文档中的某个关键字我想不起它的定义是什么, 这时候我希望想Obsidian一样, 鼠标移动到这个关键字上就可以自动跳转到对应文档中的对应标题(能直接预览也很棒). 这样我就能知道这个关键字的信息.

在Obsidian中是通过[[文档#标题|显示名称]]来使用, 我希望能知道在思源笔记中如何做到.

**Comment by 88250** [comment]
你好，请看一下用户指南，里面有很多这样的例子，谢谢。

**Comment by GaN601** [comment]
> 你好，请看一下用户指南，里面有很多这样的例子，谢谢。

好的, 感谢. 
新的问题出现了, 我该如何打开你的用户指南?
https://github.com/siyuan-note/user-guide-zh_CN.
我通过思源这个软件打开了没有东西. 这个仓库中也没有对应的说明

**Comment by 88250** [comment]
顶部 `...` 菜单中

![image](https://user-images.githubusercontent.com/873584/175091587-09a045e2-8e0d-4af1-890d-93a929a22237.png)

**Comment by GaN601** [comment]
> 顶部 `...` 菜单中
> 
> ![image](https://user-images.githubusercontent.com/873584/175091587-09a045e2-8e0d-4af1-890d-93a929a22237.png)

这个我已经看过了, 然而我还是无法理解这个文档中如何做到[[文档#标题|别名]]的表达, 我只能了解((文档))或((标题))的使用, 连别名都不知道.
![image](https://user-images.githubusercontent.com/80253667/175093212-6d8bab5b-271b-4eac-9b7c-242ad619c8b1.png)

**Comment by GaN601** [comment]
> 



> 1. `((关键字` 触发搜索
> 2. 搜索结果中选择 `H` 类型的标题块
> 3. 创建引用以后右键这个引用修改锚文本

好的, 谢谢, 这样就很易懂了嘛.
请问如何脱离右键来修改这个锚文本? 我刚刚找了快捷键一圈也没有类似的功能

**Comment by 88250** [comment]
把光标插入符移到引用里直接打字也可以改的。

**Comment by 88250** [comment]
目前差不多是这样子，也许以后还有改进余地。

**Comment by GaN601** [comment]
> 目前差不多是这样子，也许以后还有改进余地。

好的, 感谢回复.
可以的话, 我希望能像Obisidian一样, 光标移动进去后,显示的是原始格式((id "锚文本")), 这样修改的话就简单很多, 还能自己再改引用的内容块

**Comment by 88250** [comment]
其实很早以前就是这样的，后来根据用户反馈改为了所见即所得。

**Comment by GaN601** [comment]
> 其实很早以前就是这样的，后来根据用户反馈改为了所见即所得。

如果能改成在设置里手动开关就好了, 能否指路一下相关版本? 我降到那个版本去

**Comment by 88250** [comment]
大概是一年多以前的版本了，建议不要使用。

**Comment by 88250** [comment]
块引锚文本的用户文档在 https://github.com/siyuan-note/siyuan/issues/5276 中补充。

**Comment by GaN601** [comment]
> 

好的, 感谢回复
