### ISSUE TITLE
PlantUML 使用Tab键缩进内容时导致内容丢失且无法恢复

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#5270]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如图，在编辑PlantUML时，我想将选中内容缩进一下，按了Tab，内容没了。此时Ctrl Z也无法恢复。
![image](https://user-images.githubusercontent.com/5968678/175094179-aa1b18a9-7565-4528-9a07-071e29ff4009.png)

### 期待的结果 Expected result

代码可以缩进。或者缩进不了，至少可以撤销刚刚的操作。

### 版本环境 Version environment

```markdown
- Version: 2.0.22
- Operating System: Win 10
- Browser (if used):
```

### 日志文件 Log file

不适用。

**Comment by Vanessa219** [comment]
@startuml component
  actor client
  node app
  database db
  db -> app
  app -> client
  @enduml
