### ISSUE TITLE
服务端url路径建议增加统一路径前缀，方便反向代理

### ISSUE THREAD

**Issue by cybernamed** [siyuan-note/siyuan#5272]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

部署到服务器希望能在同一个nginx以及域名下反向代理多个服务

### 描述可能的最优解决方案 Describe the optimal solution

增加全局的url路径前缀，或者直接把当前所有的url都加一个统一的前缀
比如
/stage/* -> /siyuan/stage/*
/api/* -> /siyuan/api/*

**Comment by 88250** [comment]
你好，不建议用路径反代，建议用二级域名。
