### ISSUE TITLE
有没有可能实现siyuan://xxxx?var=xxxxx

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5278]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

想实现这么一个效果，在外部软件中控制siyuan里面页面的显示效果，
主要有两个效果，一个效果是正常显示，另一个是能隐藏部分字体，实现Flash卡片的效果。

最好是不切换模板，但是修改模版中的变量,
比如
siyuan://xxxx?hl_text_vis=0
使得Ctrl-E标志的黄色字体变成透明，但背景仍然是黄色。block_id部分如果是14个0则表示不切换当前正在显示的页面，只是切换黄色字体颜色。

或者
siyuan://xxxx?var_b3-font-color4=0
用户指定一个字体颜色，可以是color1-13中的一个。

### 描述可能的最优解决方案 Describe the optimal solution

使用var_b3-font-color4最有通用性

### 描述候选的解决方案 Describe the candidate solution

只要能使用在线切换字体颜色，不一定要使用 siyuan://链接，通过API也可以。

如果主界面上能提供一个按钮更好，不过这个要有人做主题。

**Comment by 88250** [comment]
这个需求使用[更新块 API](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E6%9B%B4%E6%96%B0%E5%9D%97) 可以做到。

**Comment by jabobian** [comment]
更新块里面的data能更新哪些呢，有没有完整的例子。
如果看示例，更新foobarbaz的作用是什么
`"data": "<div data-node-id=\"20211230161520-querkps\" data-node-index=\"1\" data-type=\"NodeParagraph\" class=\"p\"><div contenteditable=\"true\" spellcheck=\"false\">foo<strong>bar</strong>baz</div><div class=\"protyle-attr\" contenteditable=\"false\"></div></div>",`
