### ISSUE TITLE
能不能增加一个快捷键，一键关闭左侧窗口

### ISSUE THREAD

**Issue by qiaomuliu** [siyuan-note/siyuan#5281]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当我打开文档树，标签，书签，大纲时，需要一个一个关闭，并且如果光标在文档内容中，按下Alt+1 只是光标消失，再次按下Alt+1才能关闭文档树，每当我想要全部关闭左侧标签栏要一个一个按很麻烦。

### 描述可能的最优解决方案 Describe the optimal solution

能否增加一个一键关闭全部快捷键

### 描述候选的解决方案 Describe the candidate solution

在文档中按Alt+1 一次就关闭文档树，而不是两次

**Comment by 88250** [comment]
你好，这个暂时不考虑了。可以用编辑器全屏顶顶。


另外：

> 在文档中按Alt+1 一次就关闭文档树，而不是两次

第一次是聚焦。
