### ISSUE TITLE
忘了从哪个版本升级到当前（v2.0.23）版本，「图」里面文档节点显示错误。

### ISSUE THREAD

**Issue by wolongge** [siyuan-note/siyuan#5285]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我忘了从哪一个版本升级到当前（v2.0.23）版本，「关系图」里文档节点只有 5 个左右，折腾了一下，发现我需要到每个文档里做点改动，如加个空行、加个空格之类的，再刷新「图」，做过改动的文档就会出现在「图」里了。

### 期待的结果 Expected result

所有文档节点能出现在「关系图」视图中。

### 版本环境 Version environment

```markdown
- Version: v2.0.23
- Operating System: Win11
- Browser (if used): No
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/8984462/siyuan.log)

### 更多信息 More information

大概一个多月没有使用。

**Comment by wolongge** [comment]
有没有什么变通方法，能解决这个。

**Comment by wolongge** [comment]
我在「设置」-「导出」中，使用「导出 Data」和「导入 Data」后，视图正常了。

**Comment by 88250** [comment]
文档树 `...` 菜单中 `重建索引`。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
