### ISSUE TITLE
新增获取块 kramdown 源代码的 API

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5289]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前通过 API `/api/template/docSaveAsTemplate` 与 `/api/block/updateBlock` 可以实现不更改块 ID 的前提下查看编辑更新 kramdown 源代码, 但是目前还有如下问题
1. `/api/template/docSaveAsTemplate` API 可以创建指定文档的 kramdown 源码文件, 但是除了桌面端可以使用 Node.js 的 [fsPromises.rm(path\[, options\])](https://nodejs.org/api/fs.html#fspromisesrmpath-options) 方法, 其他端无法移除生成的模板文件
2. 除了文档块, 该方案无法更新其他容器块(比如超级块, 引述块, 列表块与列表项块)

新增获取指定块/文档 kramdown 源代码的 API 后可以更好地实现第三方的源代码模式编辑

### 描述可能的最优解决方案 Describe the optimal solution

新增获取指定块 kramdown 源代码的 API

### 描述候选的解决方案 Describe the candidate solution

新增获取指定文档块 kramdown 源代码的 API

### 其他信息 Other information

可以复用导出为模板功能中的
https://github.com/siyuan-note/siyuan/blob/54ced0a94fa26a03082472406365e0591c6c8958/kernel/model/template.go#L93-L132

**Comment by 88250** [comment]
> 但是除了桌面端可以使用 Node.js 的 [fsPromises.rm(path[, options])](https://nodejs.org/api/fs.html#fspromisesrmpath-options) 方法, 其他端无法移除生成的模板文件

可以考虑使用 [写入文件 API](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E5%86%99%E5%85%A5%E6%96%87%E4%BB%B6)

**Comment by Zuoqiu-Yingyi** [comment]
> 可以考虑使用 [写入文件 API](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E5%86%99%E5%85%A5%E6%96%87%E4%BB%B6)

API `/api/file/putFile` 可以删除指定文件吗❓

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 不能删除。
