### ISSUE TITLE
桌面端支持隐藏底部状态栏

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5292]
https://ld246.com/article/1656236020079

设置 - 外观 - 隐藏底部状态栏

**Comment by woaihuangxueying** [comment]
原来不止我一个人觉得有底栏丑🤣🤣

**Comment by roverway** [comment]
底部状态栏+底部dock栏，会出现双下巴；ui又需要优化一下了。

**Comment by 88250** [comment]
@roverway 这个是预期：

![image](https://user-images.githubusercontent.com/873584/176378804-8285115d-4198-4a09-a956-b493b5aefaf2.png)
