### ISSUE TITLE
route ip+net: netlinkrib: permission denied

### ISSUE THREAD

**Issue by TerickJojo** [siyuan-note/siyuan#5299]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

问题：
route ip+net: netlinkrib: permission denied
背景：
1、Ubuntu加了个新源，大更新之后重启
2、拉取最新镜像，启动报错
更新脚本如下：
![image](https://user-images.githubusercontent.com/24235319/175862393-f610a3bb-9a0c-48b0-862f-d1bb4e60b337.png)
docker-compose如下：
![image](https://user-images.githubusercontent.com/24235319/175862364-9c312d8c-deb1-42b8-bd66-7b0b1360ba0a.png)
采取措施：
1、加上user1000，不行
2、换端口，不行
3、检查各种防火墙，都没开启
4、回退版本，也起不来
5、给/var/run/docker.sock加666，不行

### 期待的结果 Expected result

如何解决

### 版本环境 Version environment

```markdown
- Version: 2.0.24
- Operating System: Ubuntu
- Browser (if used): -
```

### 日志文件 Log file

siyuan    | W 2022/06/27 12:44:06 path.go:99: get interface addresses failed: route ip+net: netlinkrib: permission denied
siyuan    | I 2022/06/27 12:44:06 serve.go:78: kernel is booting [http://0.0.0.0:6806]
siyuan    | E 2022/06/27 12:44:06 serve.go:82: boot kernel failed: listen tcp 0.0.0.0:6806: socket: permission denied

**Comment by ssfdust** [comment]
bind port失败了 docker自身的权限是什么 试试root启动 而非docker用户组启动

**Comment by TerickJojo** [comment]
> bind port失败了 docker自身的权限是什么 试试root启动 而非docker用户组启动

就是root启动的。。

**Comment by ssfdust** [comment]
lsof -i :6806
输出？

**Comment by 88250** [comment]
> siyuan | W 2022/06/27 12:44:06 path.go:99: get interface addresses failed: route ip+net: netlinkrib: permission denied

![image](https://user-images.githubusercontent.com/873584/175889564-25cdc612-a5c0-4a22-87f4-e6fcacdb66fc.png)


感觉是系统的网卡配置问题，暂时先关闭了，如果还有人遇到该问题我们再打开。

**Comment by TerickJojo** [comment]
> > siyuan | W 2022/06/27 12:44:06 path.go:99: get interface addresses failed: route ip+net: netlinkrib: permission denied
> 
> ![image](https://user-images.githubusercontent.com/873584/175889564-25cdc612-a5c0-4a22-87f4-e6fcacdb66fc.png)
> 
> 感觉是系统的网卡配置问题，暂时先关闭了，如果还有人遇到该问题我们再打开。

暂时就先这样了嘛。。
