### ISSUE TITLE
页内搜索问题

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#53]
### 描述问题

ctrl+F是页面内搜索

1. 输入文字后焦点会离开搜索输入栏，需要再点击搜索输入栏继续输入文字
2. 多个搜索结果的时候，向下一个搜索结果的跳转失灵

### 期待的结果

1. 搜索结果的跳转和高亮不会导致焦点离开搜索输入栏，可以持续搜索，比如说我先输了一个字“自”，然后不需要用鼠标再次点击搜索输入栏，可以再输入一个字“由”，搜索“自由”。
2. 切换搜索结果的时候跳转正常。

### 截屏或录像

1. ![搜索无法连续](https://user-images.githubusercontent.com/51868839/91640955-dc740e80-ea53-11ea-89d2-841f2fd503b9.gif)

2. ![切换搜索内容](https://user-images.githubusercontent.com/51868839/91640722-3ecc0f80-ea52-11ea-8009-a488b93b1c6f.gif)

**Comment by nanmao** [comment]
版本0.3.4, 搜索没有结果
![image](https://user-images.githubusercontent.com/26304888/97066224-43421e00-15e6-11eb-93b0-9e96385e2a0a.png)

**Comment by nanmao** [comment]
版本0.4.2，点击 下一条 的按钮没反应。（`Ctrl+P`的搜索比`Ctrl+F`的搜索好用多了）
![image](https://user-images.githubusercontent.com/26304888/98439618-0de11880-212e-11eb-8b2a-a741299f9211.png)
