### ISSUE TITLE
链接的打开菜单和点击事件保持一致

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#5300]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![222](https://user-images.githubusercontent.com/38906705/175875290-94e2289a-66ca-402a-b1c8-9482334677e2.gif)

### 期待的结果 Expected result

禁止右侧打开不支持的格式附件

### 版本环境 Version environment

```markdown
1
```

### 日志文件 Log file

1

**Comment by Vanessa219** [comment]
如果是本地资源且可以使用思源打开：
* 点击 - 右侧打开
* Shift+点击 - 使用默认程序打开
* Ctrl+点击 - 打开文件位置
如果是本地资源但不可以使用思源打开：
* 点击 - 使用默认程序打开
* Ctrl+点击 - 打开文件位置
如果不是本地资源：
* 使用默认程序打开
