### ISSUE TITLE
双链自动新建未来日期页面能否自动成为 d 类型并放在日期目录下，而不成为当前页面子页面

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#5305]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

日期页面是特殊页面，可以在未来特定日期看到关联项。

### 描述可能的最优解决方案 Describe the optimal solution

预生成未来日期页面

**Comment by 88250** [comment]
> 双链自动新建

是如何自动新建的？

**Comment by aGolduck** [comment]
> > 双链自动新建
> 
> 
> 
> 是如何自动新建的？

比如我在2022-06-28 页面下 ((2022-06-29这时就会自动创建一个 2022-06-29 的子页面

**Comment by 88250** [comment]
右键笔记本设置块引新建文档存放位置，使用 `../`

![image](https://user-images.githubusercontent.com/873584/176148428-385d0976-0d61-4884-8ad5-4875b79f3f54.png)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by aGolduck** [comment]
这样确实能绕过一下，但是跨月跨年的就有点问题了，其他的页面也会受到影响。我直接手动挪一下吧。后面我研究下创建页面的 api, 一次性把未来两三年的日期都生成应该就够用了
