### ISSUE TITLE
关于列表项转为段落块之后引用失效的问题

### ISSUE THREAD

**Issue by langzhou** [siyuan-note/siyuan#5306]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

之前为了解决「一炮三响」的问题，对于一个列表项块而言，前端只保留了列表项的操作，所有的引用都是基于列表项的。

但是如果将该列表项转换成了段落块，那么之前对这个列表项的引用都会失效，因为这个列表项已经不存在了。

为了避免这个问题，对于列表项的引用最好是链接在段落块中，但是现在前端无法执行该操作。

### 期待的结果 Expected result

列表项转为段落块之后也能保持之前的引用关系。

### 版本环境 Version environment

```markdown
- Version: 2.0.24
- Operating System: macOS
- Browser (if used):
```

### 日志文件 Log file

暂未涉及

**Comment by 88250** [comment]
容器块+叶子块转换为叶子块以后，容器块 ID 就没有地方保存了。这个暂时没有解决方案。

> 为了避免这个问题，对于列表项的引用最好是链接在段落块中，但是现在前端无法执行该操作。

这个可以在界面上操作的，使用 Ctrl+/ 触发光标所在块标菜单。

**Comment by langzhou** [comment]
> 容器块+叶子块转换为叶子块以后，容器块 ID 就没有地方保存了。这个暂时没有解决方案。
> 
> > 为了避免这个问题，对于列表项的引用最好是链接在段落块中，但是现在前端无法执行该操作。
> 
> 这个可以在界面上操作的，使用 Ctrl+/ 触发光标所在块标菜单。

好的，那我先用` Ctrl+/ `这个来处理了。
