### ISSUE TITLE
中西文间插入空格影响行级标记符

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5308]
https://ld246.com/article/1656383065801 最后一点

**Comment by Temacc0531** [comment]
![test](https://user-images.githubusercontent.com/101307399/176085984-d1fb0290-c334-4fe3-9e27-5465cba6fe20.png)
在列表中使用中西文插入空格还出现过这个异常

**Comment by Temacc0531** [comment]
暂时没能复现😂

**Comment by 88250** [comment]
收到，后续请留意，多谢。
