### ISSUE TITLE
导出 PDF、HTML 和 Word 时支持覆盖已有文件

### ISSUE THREAD

**Issue by TerryCheni** [siyuan-note/siyuan#5309]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我有一些需要迭代的文档需要导出成PDF，比如说明文档或开发文档。当我导出时希望可以覆盖之前的版本，或者在同一目录层级生成该PDF。而不是继续创建子目录。

### 描述可能的最优解决方案 Describe the optimal solution

在导出时，若目标目录存在同名文档，可以提供导出选项，如：覆盖文件，文件名加时间戳/版本信息等

**Comment by DaveBoy** [comment]
+1

**Comment by 88250** [comment]
先不加选项和后缀了，只是简单地让其可以在相同路径下覆盖文件。

**Comment by TerryCheni** [comment]
Thkans，现在基本可以解决我的问题。如果未来支持导出时设置文档名称可能会更好
