### ISSUE TITLE
公式渲染问题

### ISSUE THREAD

**Issue by YaooXu** [siyuan-note/siyuan#532]
### 描述问题 Describe the problem
公式不能及时渲染。

````````markdown
\boldsymbol{x}^2 + 1 = x
````````

### 期待的结果 Expected result
渲染成功的公式。

### 截屏或录像 Screenshot or video
编辑的时候就没有实时渲染。
![image](https://user-images.githubusercontent.com/44971199/99619811-3555b080-2a5f-11eb-8739-6e5cccb847bb.png)
退出编辑后仍然没有渲染成功。
![image](https://user-images.githubusercontent.com/44971199/99619886-5ae2ba00-2a5f-11eb-9c28-2f9fa35caf66.png)

### 版本环境 Version environment

* 版本 Version： v0.4.7
* 操作系统 Operating system：Windows 10 家庭版
* 浏览器（如果使用）Browser (if used)：

### 其他信息 Other information
这个时候只有重新选择渲染引擎，退出设置后才会渲染成功，但是即使这样，渲染功能依旧没有恢复。

**Comment by 88250** [comment]
感谢反馈，这个问题 https://github.com/siyuan-note/siyuan/issues/523 在做了一些修复，等 v0.4.8 发布以后请在帮忙留意观察一下，谢谢。

**Comment by 88250** [comment]
你好，v0.4.8 已经发布，请尝试一下是否已经修复。

该 issue 我先关闭了，如果还有问题请继续跟帖即可，谢谢。
