### ISSUE TITLE
编辑器 `...` 菜单增加 `优化排版` 和 `网络图片转换为本地图片` 图标

### ISSUE THREAD

**Issue by ChirsGod** [siyuan-note/siyuan#5321]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/50586375/176571478-596aa9c4-44a9-4536-a0b7-5a9cadfc79cf.png)
如上图所示，其他的几个功能前方都有图标，就这两个没有图标显得非常突兀。

### 描述可能的最优解决方案 Describe the optimal solution

选取两个合适的图标补上去

**Comment by Vanessa219** [comment]
菜单中有一些用图标无法确切阐述内容的都没有配备图标哦。
目前还没有找到比较合适的图标，先不做修改了，如果亲有合适的 svg 格式的图标可以推荐哦。

**Comment by 88250** [comment]
@Vanessa219 https://github.com/siyuan-note/siyuan/issues/5403
