### ISSUE TITLE
切换页签

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#533]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

日常切换标签页 (Shift) Ctrl Tab 

### 描述最优的解决方案 Describe the optimal solution

behave like browsers

### 描述候选解决方案 Describe the candidate solution

NA

### 其他信息 Other information

NA

**Comment by Vanessa219** [comment]
- [ ] ctrl+shift+[ 选中下一个页签
- [ ] ctrl+shift+[ 选中上一个页签
- [ ] control/ctrl+tab 面板及页签切换

**Comment by whuwangyong** [comment]
不好意思来晚了。这个Ctrl tab能不能改为在最近的打开页签之间切换。类似 IntelliJ IDEA 等 JetBrain 系的软件那样。
