### ISSUE TITLE
Data sync via the third-party cloud storage services

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5331]
Since v2.5.0, we can use third-party cloud storage services to achieve data synchronization and backup through simple configuration. Currently, S3 and WebDAV protocols are supported.

More importantly, even if a third-party cloud storage service is used, the data is encrypted end-to-end, which can fully guarantee that the third-party cloud storage service provider will not obtain our plaintext data.

The third-party cloud storage feature support is currently in the free public beta stage, and there is no need to register an account or log in. Please use it with confidence.

**Comment by SolarDesalination** [comment]
Would prefer a European host like Germany where data protection laws are stronger. But if North America, please choose Canada (OVH in Montreal can scale)

**Comment by 88250** [comment]
@SolarDesalination Hello, the PaaS provider we use has no German and Canadian nodes, only North America Los Angeles nodes, so it seems that we can only choose to establish services in Los Angeles, thank you.

**Comment by SolarDesalination** [comment]
Is it possible to provide an alternate option outside of the USA? Patriot Act allows for extrajudicial monitoring of data. In principle it's highly disagreeable. https://www.eff.org/deeplinks/2016/10/debunking-patriot-act-it-turns-15

**Comment by 88250** [comment]
@SolarDesalination SiYuan Sync data via End-to-End encryption (the sync source code is open sourced also), through technology, to guarantee privacy security is safer than law.

**Comment by 88250** [comment]
Proposal: [European Data Center for SiYuan Cloud Sync](https://github.com/siyuan-note/siyuan/issues/15047)
