### ISSUE TITLE
导出选择引用块为脚注时锚文本丢失

### ISSUE THREAD

**Issue by Morganwan90** [siyuan-note/siyuan#5333]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

当在设置中选择引用快样式为脚注时，锚文本会出现丢失情况

### 期待的结果 Expected result

正常显示锚文本

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Snipaste_2022-07-03_00-22](https://user-images.githubusercontent.com/61633409/177008565-17077a7a-cb9a-4e16-8178-87b6b24de900.jpg)
![Snipaste_2022-07-03_00-26](https://user-images.githubusercontent.com/61633409/177008618-52351abc-a827-4645-9d35-978ffa18d1f5.jpg)

### 版本环境 Version environment

```markdown
- Version: 2.0.25
```

### 日志文件 Log file

-

**Comment by 88250** [comment]
脚注的渲染就是以数字为锚文本的，原引用的锚文本已经作为脚注定义列表部分。
