### ISSUE TITLE
无法连续打印 反斜杠 \

### ISSUE THREAD

**Issue by Wyrande** [siyuan-note/siyuan#5339]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

pc 端和网页端测试发现无法连续打印反斜杠  \\  

### 期待的结果 Expected result

能连续打印 反斜杠 \\

### 版本环境 Version environment

```markdown
- Version: v2.0.25
- Operating System: windows10 19044.1766
- Browser (if used): edge 103.0.1264.37 (正式版本) (64 位)
```

### 日志文件 Log file

I 2022/07/04 08:50:24 conf.go:362: exited kernel
I 2022/07/04 08:50:30 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/04 08:50:34 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\ProgramData\SiyuanData, data 186 MB]
I 2022/07/04 08:50:35 conf.go:267: user has enabled [Automatically upload error messages and diagnostic data]
I 2022/07/04 08:50:35 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/04 08:50:36 conf.go:523: database size [6.5 MB], block count [2281]
I 2022/07/04 08:50:36 working.go:139: kernel booted

**Comment by 88250** [comment]
往左移动到之前输入的 `\` 前面后再输入 `\`。

这个问题暂时只能这样，后续等有空再看如何改进，先关闭了，感谢反馈。
