### ISSUE TITLE
支持上标下标语法

### ISSUE THREAD

**Issue by zhy91** [siyuan-note/siyuan#534]
Typora中支持`~下标~`和`^上标^`这样的语法，感觉非常方便，否则需要插入公式或者采用html语法。

我看到目前前者`~下标~`用在删除线上了，但是同时也存在`~~删除线~~`这样的语法规则，是否有些重复？

非常感谢！

**Comment by 88250** [comment]
你好，`~foo~` 和 `~~foo~~` 这俩都是删除线，是 GFM 规范定义的。

**Comment by zhy91** [comment]
> 你好，`~foo~` 和 `~~foo~~` 这俩都是删除线，是 GFM 规范定义的。

谢谢回复！

Typora是将这些非规范的语法作为设置中的可选项，可以自己选择是否使用。

实际上我有很多用到这些语法规则的文档，导入到思源笔记后一些格式有些混乱，所以提出这个建议。

**Comment by 88250** [comment]
收到，后续我们参考 Typora 的设置试下加入上下标语法。
