### ISSUE TITLE
建议改进日记，做到“无摩擦”记录

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5340]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

随时记录

### 描述可能的最优解决方案 Describe the optimal solution

参考 logseq 的日记模式，一打开软件就是日记界面，最重要的是，所有日记可以连续浏览不用手动切换。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5187
