### ISSUE TITLE
PDF Annotation 锚文本 中无法直接插入 Emoji

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5341]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

一个小 Bug，如下 GIF 所示，通过如果直接在锚文本中插入 Emoji，Emoji 会跳到锚文本最后，且不会成为锚文本的一部分

![1](https://user-images.githubusercontent.com/7659710/177104831-41ac6aa7-4879-4126-b62f-c693da8ff904.gif)

Workaround 是通过 C-/ 的窗口编辑

### 期待的结果 Expected result

PDF Annotation 锚文本中可以插入 Emoji

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: OSX 11.6.6
- Browser (if used):
```

### 日志文件 Log file

skip

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/5342
https://github.com/siyuan-note/siyuan/issues/3018
