### ISSUE TITLE
打开的文档无法显示层级路径

### ISSUE THREAD

**Issue by Elliootalderson** [siyuan-note/siyuan#5343]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

目前打开的文档只能显示目前块在文档中的位置:
![image](https://user-images.githubusercontent.com/93273663/177116116-16c9f31f-9af8-4b7d-9fd2-7468cec48436.png)
 却无法显示在文档树中的层级.

### 期待的结果 Expected result

1. 希望可以显示文档的完整位置/路径/层级. 这样方便查看目前文档的位置和深度. 使整个文件夹里面的文档更加有序.
2. 希望可以通过点击上方的路径/位置/层级,实现层级跳转,快速到上一层文档中.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/93273663/177115083-4e81d2be-ffdf-475f-bb8d-d286d21191f7.png): 浮窗可以显示完整路径
![image](https://user-images.githubusercontent.com/93273663/177115295-fe445ce5-141f-43d2-98aa-2033d6fb2d29.png)  完全打开的文档无法显示完整路径

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Elliootalderson** [comment]
既然目前已经打算隐藏文档树等内容. 那么就应该出现一个能快速辨识当前文档的位置信息. 这也有利于判断新建文档时的位置和层级.

**Comment by 88250** [comment]
这个之前考虑过：

* https://github.com/siyuan-note/siyuan/issues/2613
* https://github.com/siyuan-note/siyuan/issues/3007
