### ISSUE TITLE
隐藏停靠栏按钮请放在顶部菜单中

### ISSUE THREAD

**Issue by Elliootalderson** [siyuan-note/siyuan#5344]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

想要隐藏停靠栏和隐藏底部状态栏,但又可以方便的打开停靠栏(毕竟这个操作比较频繁)

### 描述可能的最优解决方案 Describe the optimal solution

隐藏停靠栏按钮请放在顶部菜单中,一键点击隐藏展开.

### 描述候选的解决方案 Describe the candidate solution

想要隐藏停靠栏和隐藏底部状态栏,最终会导致如果想要显示停靠栏 就要先打开底部状态栏(这意味你要去设置里面慢慢点击). 即底部状态栏捆绑了停靠栏. 一个低频操作捆绑了高频操作.

**Comment by Vanessa219** [comment]
我们是这样理解的：如果对应用不太熟悉的用户可以一直显示停靠栏；熟悉的用户就可以完全隐藏，通过快捷键对各面板进行操作。高频操作的背后会导致无法提高用户的效率，不太建议用户去频繁的切换停靠栏。
