### ISSUE TITLE
菜单中的折叠功能 和 Alt+点击 的折叠功能 表现不一致

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5346]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如 GIF 所示，当使用 Alt+点击 来折叠列表时，可以正确折叠

但当时用菜单折叠时，会有问题，内容被压缩在了一起

![1](https://user-images.githubusercontent.com/7659710/177251484-7791eab0-9720-4eda-8566-d4baf4d74597.gif)

### 期待的结果 Expected result

两者表现一致

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: osx 11.6.6
- Browser (if used):
```

### 日志文件 Log file

skip

**Comment by Vanessa219** [comment]
还麻烦上传一下这个文档的 .sy 文件，我用一般的列表无法重现。谢谢

**Comment by mlzxy** [comment]
这个可以吗 [List-1.sy.zip](https://github.com/siyuan-note/siyuan/files/9084980/List-1.sy.zip)

**Comment by Vanessa219** [comment]
重现不了

https://user-images.githubusercontent.com/970828/180652152-40366fef-0161-42be-b50b-b7787b8a7d19.mp4

**Comment by Vanessa219** [comment]
无法重现，先关闭了。
