### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#5349]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

pre-release 版本多处文字显示错误
![image](https://user-images.githubusercontent.com/16383685/177283236-2bee7810-ad73-4995-bcca-df3bfcd91347.png)
![image](https://user-images.githubusercontent.com/16383685/177283276-08ccf51e-ad72-4295-98c8-5f58b09581e4.png)

### 期待的结果 Expected result

正确展示文章

### 版本环境 Version environment

```markdown
- Version:  v2.0.25 pre-release
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
我这里没有重现问题，请试下卸载后再安装，或者换个安装路径看看。
