### ISSUE TITLE
一键生成脑图

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#535]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

复习和整理思路时。

### 描述最优的解决方案 Describe the optimal solution

利用大纲一键生成脑图。

### 其他信息 Other information

注意到思源会在接下来几个版本中加强TOC的功能，鉴于思源可以支持脑图的渲染（发现时还挺惊喜），可以顺便加入生成脑图的功能。脑图的交互性强，更加利于复习和整理思路

**Comment by 88250** [comment]
你好，之前有过类似提议：https://github.com/siyuan-note/siyuan/issues/66 https://github.com/siyuan-note/siyuan/issues/264 

 我们打算在 https://github.com/siyuan-note/siyuan/issues/62 中进行完善，谢谢反馈。
