### ISSUE TITLE
集市下架后主题无法删除

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#5353]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Ipad端主题下架后不在主题集市显示，ipad无法进入文件系统删除主题，因此无法删除集市下架的主题

### 期待的结果 Expected result

主题集市分为已安装主题和集市主题，已安装主题可以显示自定义或者下架了的主题，提供删除选项

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: ipad os
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
合并到 #5678 中考虑，谢谢。
