### ISSUE TITLE
云端同步资源文件按需下载

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5356]
## 问题

* 全量同步下载耗时太长，需要大量流量
* 本地占用太多存储空间，特别是移动端上可能空间不足

## 解决方案

同步时不同步资源文件，当打开文档请求资源文件时，如果本地不存在该资源文件再从云端下载。

**Comment by netdog2019** [comment]
应该也有个选项，可以全部下载。

**Comment by mozhux** [comment]
可以借鉴网盘同步盘那样的，本地就一个钩子在，有需要再下载，也不影响双链去

**Comment by 88250** [comment]
@netdog2019 大概就是和 @mozhux 类似网盘，本地不会存放实际文件，只是放一个空文件占位，需要时（比如打开文档渲染图片时）再判断是否实际存在文件，不存在文件的话再从云端下载。

应该不会加选项让用户选择是否全量下载资源文件，因为这个机制在很大程度上影响着运营成本，如果流量成本太高的话云端存储大小就无法提升了，这个制约比较大。

**Comment by mozhux** [comment]
> 

那对应的，未下载的还能查看双链或链接预览吗

**Comment by 88250** [comment]
文档会全量下载的，只是资源文件做按需加载。

**Comment by Zuoqiu-Yingyi** [comment]
> 应该不会加选项让用户选择是否全量下载资源文件，因为这个机制在很大程度上影响着运营成本，如果流量成本太高的话云端存储大小就无法提升了，这个制约比较大。

这样的话感觉就背离本地优先的初衷了, 在云服务宕机的话可能就得从各个设备与工作空间找资源文件了
要不再考虑一下单独设置资源文件目录? 给资源文件较大用户提供一个使用第三方同步服务的选择(这些用户也趋向于使用容量更大的第三方同步服务同步资源文件)

**Comment by 88250** [comment]
的确，这样会背离本地优先的理念，还需要继续考虑更好的方案。

**Comment by 88250** [comment]
先关闭了，还需要时间再考虑。

**Comment by TCOTC** [comment]
思源用得越久，资源文件越多，每个客户端都完整储存所有资源文件的负担就越大

**Comment by Achuan-2** [comment]
可以对多个设备进行配置，选择是全量同步还是按需同步，这样就可以根据自己的需求以及移动端存储空间进行考虑

一般默认主设备设置全量同步，手机因为就平常偶尔看看几篇文档的话可以设置资源按需同步

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/19149
