### ISSUE TITLE
在一个块内可以有多个空行，但却无法书写多个段落

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5359]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如下 GIF 所示，当我使用 Shift+Enter 时，我可以在一个 block 内创建空行。 但当我尝试在空行后继续书写（即一个 block 内的第二段）时，一个新的 block 被自动创建，而且空行被吃掉了。

![1](https://user-images.githubusercontent.com/7659710/177692868-34526da2-07cb-40be-a138-7a868921eea5.gif)

一个与之相关的 issue 是：#5347 

### 期待的结果 Expected result

一个块内可以书写多个段落

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: osx 11.6.6
- Browser (if used):
```

### 日志文件 Log file

skip

**Comment by 88250** [comment]
这个是分块规则决定的，多个空行会被分块。
