### ISSUE TITLE
自定义字符串映射

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#536]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

编辑时，可以按照自己的习惯来。

### 其他信息 Other information
![image](https://user-images.githubusercontent.com/16791452/99685423-88f6e700-2abd-11eb-9d37-af23b033e6fe.png)

举例，我是工科的，经常会用到公式。想打出$$，但是中文输入法会输出￥￥，很不方便。 其他人的情况也不一样。有这个功能之后会用得很顺手。

**Comment by frankli998** [comment]
参考 roamedit

**Comment by 88250** [comment]
这个建议用输入法带的配置解决……

**Comment by frankli998** [comment]
![image](https://user-images.githubusercontent.com/16791452/99691566-556b8b00-2ac4-11eb-995e-a3d991a85a79.png)
 搜狗输入法不支持特殊字符串的映射。如果有哪一款输入法能够支持欢迎大家在下方推荐。另纯英文用户可能不会使用输入法，但他们也可能会需要这个功能来自定义一些快捷操作

**Comment by frankli998** [comment]
不过这个功能不紧急就是了。只是效率问题并不产生决定性作用...

**Comment by 88250** [comment]
我们放到后期一点再考虑，谢谢。

**Comment by 88250** [comment]
输入侧的还是尽量靠输入法或者其他工具进行支持，思源内部类似的需求就不考了了，感谢讨论。
