### ISSUE TITLE
文档树和大纲等面板悬停展开/关闭

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5360]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

频繁打开和关闭大纲面板，减少操作。

### 描述可能的最优解决方案 Describe the optimal solution

鼠标悬停展开大纲面板，鼠标离开后自动收起。

**Comment by Vanessa219** [comment]
同 https://github.com/siyuan-note/siyuan/issues/3499
