### ISSUE TITLE
希望在增加删除文档按钮在编辑区的更多里面

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#5368]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

要删除文档的时候, 但是文件太多, 我设置文档树不显示这么多文件, 没办法从文档树去删除文档.

### 描述可能的最优解决方案 Describe the optimal solution

在增加删除文档按钮在编辑区的更多里面

**Comment by Vanessa219** [comment]
更多里面是针对编辑器的操作，删除文档可点击标题左侧的图标，然后选择删除
