### ISSUE TITLE
桌面端拖入文件时可选择 `插入 file:// 绝对路径` 或 `复制为资源文件`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5369]
https://ld246.com/article/1657248244625

**Comment by alvisliu818** [comment]
能监听文件路径变化吗

**Comment by 88250** [comment]
@alvisliu818 不太明白你的意思。

**Comment by alvisliu818** [comment]
就是文件的路径变了, 思源里的链接能跟着变吗

**Comment by 88250** [comment]
@alvisliu818 这个估计无法实现。

**Comment by funbinary** [comment]
笔记核心逻辑使用go实现的吗？是的话可以使用fsnotify来监控文件更改

**Comment by www766** [comment]
该功能何时能够上线，请加急处理上线该功能吧，对新用户转入思源十分有帮助，也带来操作效率上的提升。

**Comment by netdog2019** [comment]
希望粘贴资源文件进来的时候也能提供这个选择。

**Comment by Vanessa219** [comment]
> 希望粘贴资源文件进来的时候也能提供这个选择。

粘贴的话可能要使用其他快捷键，否则每次粘贴都弹出会很烦。

**Comment by 88250** [comment]
@netdog2019 复制文件后，支持使用 Ctrl+Shift+V 插入 file:// 超链接

**Comment by mlzxy** [comment]
发现在 2.1.9 版本中，在 osx 上截图到剪贴板后粘贴图片不 work 了，还挺麻烦的

**Comment by 88250** [comment]
@mlzxy 好像是有这个问题，我们先记录 https://github.com/siyuan-note/siyuan/issues/5722

**Comment by leommjj** [comment]
好像无法在思源里面，打开PDF标注了。

**Comment by leommjj** [comment]
> 好像无法在思源里面，打开PDF标注了。

这样，标注又用不了了

**Comment by 88250** [comment]
@leommjj 麻烦详细说一下问题，谢谢。

**Comment by leommjj** [comment]
> 

![1661945888908](https://user-images.githubusercontent.com/101880110/187669989-4c6b50f9-6bdf-4de3-8a90-46cc22ddea6b.jpg)
图片里的是链接的PDF文件，点击是用默认程序打开；没办法用思源的阅读器打开，所以自带的标注用不了。

**Comment by 88250** [comment]
@leommjj 仅支持资源文件（也就是插入到 assets）的 PDF 标注，外部绝对路径的 PDF 文件不支持标注。

**Comment by leommjj** [comment]
> @leommjj 仅支持资源文件（也就是插入到 assets）的 PDF 标注，外部绝对路径的 PDF 文件不支持标注。

可是PDF文件太多，又占用同步空间。这里有什么办法嘛？

**Comment by 88250** [comment]
@leommjj 可以试试这个分享中提到的操作 https://ld246.com/article/1633445197069

**Comment by leommjj** [comment]
> @leommjj 可以试试这个分享中提到的操作 https://ld246.com/article/1633445197069

诶，让我有点纠结了🔦
