### ISSUE TITLE
无法插入连续的行内公式

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5371]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如 GIF 所示

![1](https://user-images.githubusercontent.com/7659710/178001041-d1ebbd00-e1ce-49b0-8960-863773a3f639.gif)

当行内已有公式时，在旁边尝试插入另一个公式会出现奇怪的行为。

### 期待的结果 Expected result

可以插入连续的多个 inline 公式

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: osx 11.6.6
- Browser (if used):
```

### 日志文件 Log file

skip

**Comment by mlzxy** [comment]
实测在 $\frac{df}{dx_1}$ 右边插入可以，但在左边就不行

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/5372#issuecomment-1179446896
