### ISSUE TITLE
提供跨块文字选取

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#5373]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在日常使用中，复制笔记的部分内容，再粘贴到聊天软件是经常使用的功能之一。

当我看了下思源笔记、Notion、Wolai、FlowUs 四个块编辑器的笔记/文档工具，除了 Notion 外，其他都不支持跨块文字选取、复制的功能。

![image](https://user-images.githubusercontent.com/98400319/178010153-e8b73bcb-8004-40ec-84f0-7b03decfd0e4.png)

如图所示，Notion 支持跨块选取文字，并且复制到剪切板的操作，但思源笔记现在还不支持，令我在日常使用中，提取文档内的部分信息并粘贴分享出去十分不便，虽然在导出预览模式中可行，当复制后粘贴出来的文字却会有莫名的排版问题。

![image](https://user-images.githubusercontent.com/98400319/178010188-46e7289d-7fe5-4a79-991a-46758ac4b73b.png)

空行我还能理解，毕竟在不少 markdown 编辑器中，以空行作为段落于段落之间的分割符号，但复制出来的内容抛开空行，总有不完美的地方。（带有有序列表或无序列表的内容，也会在每个列表下方生成一个空行）

目前来说，虽然我接受思源不支持分享链接的形式去分享内容，但如果要分享部分内容，还要导出文件，并在其他的程序里进行复制（例如导出成 Word 文档或 Markdown 文档），然后再粘贴到聊天软件，未免有种使用上的不便与繁琐。而在导出预览里进行复制，粘贴的内容又会有种排版上的奇怪。

移动端也类似，社交聊天软件中，最多的场景就是使用手机，但...唉，怎么说呢，移动端到现在都不完善我能等，但桌面端也有这种基础的不便确实有点让我感到不满了，但思源有着不少的优点，所以我还是更希望思源能完善一些。

我在链滴也提过几次这事，这次发 issue 是我在 issue 里搜索了下，发现没有人提过，所以发一下，希望 D 大理解。

### 描述可能的最优解决方案 Describe the optimal solution

Notion具备该特性，但技术细节不祥。

### 其他信息 Other information

其实就是文档块内的块，支持跨块文字选取，像一个普通的纯文本一样，复制纯文本内容，哪怕不带markdown格式的复制都能解决许多个场景下对于该特性的需求，以聊天软件为例，聊天软件本身也不支持Markdown。（聊天软件只是其中一个使用场景，这个场景下我对该特性的需求是最高的。）

这样可以让思源笔记的笔记在日常的使用中具备更好地操作性。

**Comment by 88250** [comment]
跨块部分选择这个功能比较难做，Notion 应该是近期版本才加入的。这个我们考虑下以后可能会实现。

复制到外部目前还是在导出预览中复制吧，如果粘贴时不是预期，应该不是思源的问题，而是目标软件没有适当解析处理 HTML。

也许以后会考虑在编辑器中加入复制 HTML 功能，我们先记录 https://github.com/siyuan-note/siyuan/issues/5375 

这个 issue 关闭了，谢谢。

**Comment by EberhardLin** [comment]
> 跨块部分选择这个功能比较难做，Notion 应该是近期版本才加入的。这个我们考虑下以后可能会实现。
> 
> 复制到外部目前还是在导出预览中复制吧，如果粘贴时不是预期，应该不是思源的问题，而是目标软件没有适当解析处理 HTML。
> 
> 也许以后会考虑在编辑器中加入复制 HTML 功能，我们先记录 #5375
> 
> 这个问题 关闭了，谢谢。

是的，根据Notion的更新日志，他们是在2022年1月19日更新了新特性“Select text across multiple blocks”。
![image](https://user-images.githubusercontent.com/98400319/184469374-0cd771f5-780a-415b-a31d-5950da0b7a40.png)
