### ISSUE TITLE
公式中长的 vertical bar 会出现渲染偏差

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5374]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如该公式

$$
\left|f(x)-\frac{A(x+h)-A(x)}{h}\right|
$$

在 Siyuan 中渲染会呈现为：

<img width="313" alt="image" src="https://user-images.githubusercontent.com/7659710/178013039-3e72f171-d35f-4dac-8e99-68ccb20d5341.png">

其中 vertical bar 出现偏差，清晰可见，该效果会随着屏幕放缩而变化，但偏差一直存在

### 期待的结果 Expected result

vertical bar 能够正常渲染

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: osx 11.6.6
- Browser (if used):
```

### 日志文件 Log file

skip

**Comment by Vanessa219** [comment]
没看出具体的偏差，麻烦圈点一下，还有贴一下数学公式的源码。谢谢

**Comment by mlzxy** [comment]
> 没看出具体的偏差，麻烦圈点一下，还有贴一下数学公式的源码。谢谢
<img width="313" alt="178013039-3e72f171-d35f-4dac-8e99-68ccb20d5341" src="https://user-images.githubusercontent.com/7659710/178088993-d94971a6-f3cd-4371-b87d-380b1b4002fa.png">

```latex
 \left|f(x)-\frac{A(x+h)-A(x)}{h}\right|
```

**Comment by 88250** [comment]
这个可能是 KaTeX 的问题，已经向其报告 https://github.com/KaTeX/KaTeX/issues/3669

这里先关闭，如果那边有进一步进展我们再跟进，谢谢。

**Comment by mlzxy** [comment]
> 这个可能是 KaTeX 的问题，已经向其报告 [KaTeX/KaTeX#3669](https://github.com/KaTeX/KaTeX/issues/3669)
> 
> 这里先关闭，如果那边有进一步进展我们再跟进，谢谢。

感谢，确实是。刚才在 MarkText 里试了一下，也出现类似的效果了。
