### ISSUE TITLE
自0.4.7版本升级0.4.8后无法启动

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#538]
### 描述问题 Describe the problem

0.4.7版本正常使用，更新0.4.8版本后无法启动一直转圈

### 期待的结果 Expected result

正常启动

### 截屏或录像 Screenshot or video

![QQ截图20201120100756](https://user-images.githubusercontent.com/30611816/99749055-b755e000-2b18-11eb-8e1b-e36e6372de48.png)

### 版本环境 Version environment

* 版本 Version：0.4.8
* 操作系统 Operating system：Win 10 版本2004
* 浏览器（如果使用）Browser (if used)：Edge

### 其他信息 Other information

尝试卸载后重装仍出现相同问题

**Comment by 88250** [comment]
退出应用以后请看一下进程列表里是否有 kernel 进程，如果有的话请观察其是否自动退出，kernel 退出以后再重新启动一次试试。

**Comment by 050644zf** [comment]
> 退出应用以后请看一下进程列表里是否有 kernel 进程，如果有的话请观察其是否自动退出，kernel 退出以后再重新启动一次试试。

谢谢，退出进程后已经修复
