### ISSUE TITLE
搜索时笔记本可过滤

### ISSUE THREAD

**Issue by winter60** [siyuan-note/siyuan#5383]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我有两个常用笔记本，一个自用（写自己的感悟和学习笔记），一个用来收藏（需要精读的文章、书籍、歌词）。在搜索时默认是搜索已开启的笔记本，这时会出现很多不属于自己的内容，有时这并不是我需要的，指想搜索当前笔记本属于自己的内容。

### 描述可能的最优解决方案 Describe the optimal solution

- [ ] 搜索时加一个条件，“指定笔记本”（多选），自己只有三个笔记本（还有一个演示本），其他的同学可能更多，需要加一个过滤笔记本的条件。

### 描述候选的解决方案 Describe the candidate solution

- [ ] 搜索加一个“当前笔记本”选项，只搜索当前笔记本内容。和上面的方案的使用场景略有不同，这个会随着活动标签页“当前笔记本”会变化。希望这两个方案都能够考虑。

### 其他信息 Other information

好处是不不用频繁的关闭和开启笔记本，不会遇到块引用打不开的情况。
不管采纳不采纳，都先谢谢D大V大了~

**Comment by 88250** [comment]
后面考虑，先保持打开，谢谢。

**Comment by BryceAndJuly** [comment]
这个好。

**Comment by yuyuyu-github** [comment]
很早就想要这个功能了

**Comment by 88250** [comment]
目前已经支持在笔记本选中后 Ctrl+F 触发指定路径搜索，已经能够解决该需求，暂时不考虑在搜索框上加条件了，感谢提议。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
