### ISSUE TITLE
是否考虑加入飞书文档类似的多维表格?

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#5388]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

siyuan已经实现个人知识的管理.
如果加入表格, 也将能实现个人时间管理+项目管理.

### 描述可能的最优解决方案 Describe the optimal solution

飞书文档类似的多维表格.

每个多维表格可以看作一个db. 里面分多张表. 每张表有多个视图. 不同的维度进行管理.

**Comment by woniuxia** [comment]
参考：https://ld246.com/article/1644907839875

**Comment by woniuxia** [comment]
挂架里的 Note Views v3 支持类似的功能，欢迎尝试
![image](https://user-images.githubusercontent.com/16383685/178130361-13dacea1-cffa-4e9f-b702-277e68b85392.png)
