### ISSUE TITLE
是否有办法去掉 id... 的标签?

### ISSUE THREAD

**Issue by drmingdrmer** [siyuan-note/siyuan#539]
### 描述问题 Describe the problem

是否有办法去掉`{: id...` 的标签? 
因为要多个编辑器一起编辑同一个文档, 这些id在其他编辑器会显示出来,妨碍编辑:

````````markdown
现在要找到一组β, 使得均方差最小:
{: id="20201120112246-77j8s2l"}
````````

### 期待的结果 Expected result

期待没有id的干净的markdown源码
````````markdown
现在要找到一组β, 使得均方差最小:
````````

### 版本环境 Version environment

* 版本 Version：0.4.8
* 操作系统 Operating system：MacOS Catalina
* 浏览器（如果使用）Browser (if used)：无

**Comment by 88250** [comment]
你好，请检查是否勾选（默认情况下没有勾选）
![image](https://user-images.githubusercontent.com/873584/99758469-bb8bf880-2b2c-11eb-9ea1-a02cf21a6577.png)

清理未引用 ID 是在正常退出时进行的，退出思源以后再看下 .sy.md 中应该就没有了。

另外，如果需要标准 Markdown，请使用导出功能，谢谢。

**Comment by drmingdrmer** [comment]
多谢! 我找了半天没找到配置! 这里看完不知道ID指什么, 有个图示或有个产品FAQ应该会很有帮助哈.:DDD

**Comment by hxse** [comment]
@88250 
我试了下, 无论怎么关程序, 这个清理都没有生效, 很奇怪是bug吗

**Comment by 88250** [comment]
@hxse 目前要保持这个笔记本处于打开状态（在文件树上能够看到），然后再完全关闭程序就会清理了。但建议不要进行清理，因为清理后如果用了同步功能，可能会导致很多冲突。
