### ISSUE TITLE
增加间隔复习功能（flashcard）

### ISSUE THREAD

**Issue by Jack20152019** [siyuan-note/siyuan#5391]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

笔记里加上特殊符号，软件能自动识别成卡片，进入间隔复习里面，就像anki一样

### 描述可能的最优解决方案 Describe the optimal solution

参照obsidian里的space repetition插件就挺好，基本满足需求，但是复习的时候不能实时编辑，思源也做个类似的，能实时编辑，卡片里的引用也能查看

**Comment by 88250** [comment]
未来可能会考虑 #3284 感谢提议。
