### ISSUE TITLE
添加文档收藏或最近文档的功能，以快速访问最近经常需要访问的文档。

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5393]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

快速访问最近经常需要访问的文档

### 描述可能的最优解决方案 Describe the optimal solution

添加文档收藏或最近文档的功能

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3293
