### ISSUE TITLE
Search ignore case supports Unicode character folding

### ISSUE THREAD

**Issue by myownstandard** [siyuan-note/siyuan#5398]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Hi! Sorry I don't speak Chinese. But the problem is next:
I think it's a bug of fst5 for the SQLite3 that is used for full-text-searching in the desktop app. It doesn't handle Cyrillic upper case characters well. 
Maybe it can be repaired? Thank you very much!

### 期待的结果 Expected result

Example:
I cant find existing word "Окружающие" for example. When I am searching for that Russian word "Окружающие" it only finds if it is lower case "окружающие" in my notes. 
Case sensitive search if Off.
So I need not to use Upper case words at all (so it could be found) or remember how every word was written (lower or upper case) so I could find it in the future via Search panel...

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="1280" alt="Снимок экрана 2022-07-11 в 13 16 34" src="https://user-images.githubusercontent.com/78643199/178243592-7c9ca276-59cb-4438-a75d-e2193b47f711.png">
<img width="1280" alt="Снимок экрана 2022-07-11 в 13 16 49" src="https://user-images.githubusercontent.com/78643199/178243632-e4b2561c-8f14-41b5-b1ff-0bcd3a435148.png">

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: Mac OS Big Sur 11.6.1 and Windows 10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9083061/siyuan.log)

**Comment by 88250** [comment]
Hello, currently we are not dealing with Unicode Folding, only ASCII character case is supported. This may take time to resolve later, thank you.
