### ISSUE TITLE
安卓端 无法拖动调整窗口大小

### ISSUE THREAD

**Issue by yangguang760** [siyuan-note/siyuan#5402]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

安卓端 无法拖动调整窗口大小

### 期待的结果 Expected result

可拖动调整

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: addroid 
- Browser (if used):
```

### 日志文件 Log file

None

### 更多信息 More information

None

**Comment by Vanessa219** [comment]
你指的是拖动哪一个窗口的大小呢？是手机端还是 Pad ？

**Comment by yangguang760** [comment]
手机端，文档树和编辑页面的大小无法调整

**Comment by 88250** [comment]
这个估计暂时不会改变了，感谢反馈。
