### ISSUE TITLE
建议部分功能按钮使用如下svg图片

### ISSUE THREAD

**Issue by ChirsGod** [siyuan-note/siyuan#5403]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

siyuan笔记有一些功能选项没有图标，看着有些不协调
![image](https://user-images.githubusercontent.com/50586375/178464230-e5ea9ac3-b46e-40c2-ac1b-69003604dbfe.png)

### 描述可能的最优解决方案 Describe the optimal solution

<svg t="1657619480736" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2279" width="200" height="200"><path d="M42.073656 647.681604a41.638378 41.638378 0 0 0 41.518036-41.638378V312.047393c0-50.904723 42.360431-87.849758 100.606024-87.849757h710.620299l-70.520491 70.159464a41.277352 41.277352 0 0 0 0 58.726961 42.480773 42.480773 0 0 0 58.726962 0l116.972553-116.130159a76.657939 76.657939 0 0 0 0-109.029973L882.783801 12.034454a41.75872 41.75872 0 0 0-29.483822-12.034213 41.518036 41.518036 0 0 0-29.002455 71.001859l70.520491 70.159463h-710.018589a192.547414 192.547414 0 0 0-127.923688 45.730011A164.026328 164.026328 0 0 0 0.314935 312.047393v293.995833a41.518036 41.518036 0 0 0 41.758721 41.638378zM982.186404 376.310093a41.638378 41.638378 0 0 0-41.638379 41.638378v270.529116c0 59.20833-47.053774 111.316474-100.606023 111.316474H127.997939l70.520491-70.159464a41.518036 41.518036 0 0 0-28.882113-71.001859 40.675641 40.675641 0 0 0-29.604164 12.034213l-116.972554 116.130159a76.657939 76.657939 0 0 0 0 109.029973l116.972554 116.130159a41.518036 41.518036 0 1 0 58.486277-58.967645l-70.520491-70.159464h711.944063a176.301226 176.301226 0 0 0 131.41361-60.89312A202.295127 202.295127 0 0 0 1023.223071 688.477587V417.948471a41.638378 41.638378 0 0 0-41.036667-41.638378z" fill="#4D4D4D" p-id="2280"></path></svg>

![image](https://user-images.githubusercontent.com/50586375/178463619-6923ec56-7137-4591-a519-c892168d054f.png)
可以使用这个图标，svg代码在上方
![image](https://user-images.githubusercontent.com/50586375/178463727-b53805bb-aca4-41e6-9812-884c21377756.png)

<svg t="1657619692077" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3602" width="200" height="200"><path d="M907.17169 888.699478c0 3.208065-2.632967 5.875824-5.874801 5.875824H422.29135c-3.241834 0-5.879917-2.666736-5.879917-5.875824V747.754399a5.876847 5.876847 0 0 1 5.879917-5.875825h479.005539a5.872754 5.872754 0 0 1 5.874801 5.875825v140.945079z m6.340405-194.559161H410.080238c-22.684652 0-41.143049 18.526959-41.143049 41.340547V900.973012c0 22.775726 18.458397 41.340547 41.143049 41.340547h503.431857c22.694885 0 41.138956-18.565844 41.138956-41.340547V735.480864c0-22.814612-18.444071-41.340547-41.138956-41.340547z m-6.340405-112.493074c0 3.213181-2.632967 5.875824-5.874801 5.875824H422.29135c-3.241834 0-5.879917-2.661619-5.879917-5.875824v-140.939963a5.873778 5.873778 0 0 1 5.879917-5.875824h479.005539a5.872754 5.872754 0 0 1 5.874801 5.875824v140.939963z m6.340405-194.560184H410.080238c-22.684652 0-41.143049 18.526959-41.143049 41.340547V593.919754c0 22.775726 18.458397 41.340547 41.143049 41.340548h503.431857c22.694885 0 41.138956-18.565844 41.138956-41.340548V428.428629c0-22.814612-18.443048-41.335431-41.138956-41.33543v-0.00614z m-6.340405-112.49205c0 3.213181-2.632967 5.875824-5.874801 5.875824H422.29135c-3.241834 0-5.879917-2.661619-5.879917-5.875824v-140.939963a5.875824 5.875824 0 0 1 5.879917-5.875824h479.005539a5.871731 5.871731 0 0 1 5.874801 5.875824v140.939963z m6.340405-194.555068H410.080238c-22.684652 0-41.143049 18.520819-41.143049 41.339524v165.488055c0 22.780843 18.458397 41.340547 41.143049 41.340547h503.431857c22.694885 0 41.138956-18.560728 41.138956-41.340547V121.379465c0-22.818705-18.444071-41.339524-41.138956-41.339524zM263.021927 888.699478c0 3.208065-2.638083 5.875824-5.874801 5.875824H116.983853c-3.236718 0-5.879917-2.666736-5.879917-5.875824V747.754399a5.879917 5.879917 0 0 1 5.879917-5.875825h140.163273a5.875824 5.875824 0 0 1 5.874801 5.875825v140.945079z m6.336312-194.559161H104.77274c-22.684652 0-41.138956 18.526959-41.138956 41.340547V900.973012c0 22.775726 18.453281 41.340547 41.138956 41.340547H269.358239c22.694885 0 41.138956-18.565844 41.138956-41.340547V735.480864c-0.001023-22.814612-18.444071-41.340547-41.138956-41.340547z m-6.336312-112.493074c0 3.213181-2.638083 5.875824-5.874801 5.875824H116.983853c-3.236718 0-5.879917-2.661619-5.879917-5.875824v-140.939963a5.875824 5.875824 0 0 1 5.879917-5.875824h140.163273a5.875824 5.875824 0 0 1 5.874801 5.875824v140.939963z m6.336312-194.560184H104.77274c-22.684652 0-41.138956 18.526959-41.138956 41.340547V593.919754c0 22.775726 18.453281 41.340547 41.138956 41.340548H269.358239c22.694885 0 41.138956-18.565844 41.138956-41.340548V428.428629c0-22.814612-18.443048-41.335431-41.138956-41.33543v-0.00614z m-6.336312-112.49205c0 3.213181-2.638083 5.875824-5.874801 5.875824H116.983853c-3.236718 0-5.879917-2.661619-5.879917-5.875824v-140.939963a5.879917 5.879917 0 0 1 5.879917-5.875824h140.163273a5.873778 5.873778 0 0 1 5.874801 5.875824v140.939963z m6.336312-194.555068H104.77274c-22.684652 0-41.138956 18.520819-41.138956 41.339524v165.488055c0 22.780843 18.453281 41.340547 41.138956 41.340547H269.358239c22.694885 0 41.138956-18.560728 41.138956-41.340547V121.379465c-0.001023-22.818705-18.444071-41.339524-41.138956-41.339524z" p-id="3603"></path></svg>
![image](https://user-images.githubusercontent.com/50586375/178464045-e02f102a-4a40-4695-b171-c9c99cd20dab.png)
优化排版可以使用这个图标，svg代码在上方
![image](https://user-images.githubusercontent.com/50586375/178464174-a993e6bb-48e2-4a1f-bcb7-2825fa351c7a.png)

**Comment by ChirsGod** [comment]
排版链接：https://www.iconfont.cn/search/index?searchType=icon&q=%E6%8E%92%E7%89%88&page=1&fromCollection=1&fills=&tag=
转换网络图片到本地链接：https://www.iconfont.cn/search/index?searchType=icon&q=%E8%BD%AC%E6%8D%A2&page=1&fromCollection=1&fills=&tag=

**Comment by tcmtom** [comment]
可以pull一下

**Comment by 88250** [comment]
感谢反馈，重开 https://github.com/siyuan-note/siyuan/issues/5403 处理。
