### ISSUE TITLE
思源运行状态下打开欧路词典就会变得卡顿

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#5404]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

即便关掉欧路还是一样卡顿，且关闭要等很久
曾经有顶着卡顿写了一些东西，关闭重启后发现完全没有记录

### 期待的结果 Expected result

修复bug

### 版本环境 Version environment

```markdown
- Version: 2.05
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

已经是前段时间了，但是可以轻易复现

**Comment by 88250** [comment]
请先更新到最新版以后再试试。

**Comment by Kitsuta-le** [comment]
> 请先更新到最新版以后再试试。



> 请先更新到最新版以后再试试。

已更新，开启后仍旧会受到影响有一定掉帧感，但比2.025好不少

**Comment by 88250** [comment]
这个多半是因为它需要分析 DOM 或者有其他机制影响，思源估计无法做出调整，先关闭了。
