### ISSUE TITLE
请输入问题报告标题 Please enter the title of the bug report

### ISSUE THREAD

**Issue by gslnzfq** [siyuan-note/siyuan#5406]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

拖动窗口时，内容没有及时的适配到窗口的大小，查看附件视频

### 期待的结果 Expected result

窗口内容大小能正常展示

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/12946062/178629853-1930c459-09f5-43de-98f5-ba68ce65b191.mp4

### 版本环境 Version environment

```markdown
- Version: 2.0.26
- Operating System: macOS 12
- Browser (if used):
```

### 日志文件 Log file

null

**Comment by Vanessa219** [comment]
拖拽时会对内部的大小和边距、动画效果进行设置，如果每一个像素都重新计算的话，会导致严重的性能问题。在性能和效果之间，目前采取在拖拽完后进行统一计算。

**Comment by gslnzfq** [comment]
我看浏览器端没有这个问题，不过这也是小问题，也不经常拖动窗口，就是有点强迫症
