### ISSUE TITLE
录音改进

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#541]
### 描述问题 Describe the problem
如题，录音的块引用和块内容都无法使用

### 版本环境 Version environment

* 版本 Version：0.4.8
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
> 录音的块引用和块内容都无法使用

这个没看懂，麻烦在补充一下，谢谢。

**Comment by frankli998** [comment]
![image](https://user-images.githubusercontent.com/16791452/99865998-b7bdac00-2be8-11eb-984c-97cf124194e8.png)
没办法引用和嵌入录音块

**Comment by Vanessa219** [comment]
* 录音中提示一直显示
* 录音时可以编辑
* 录音菜单区分开始录音和结束录音
