### ISSUE TITLE
优化文档树聚焦状态

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#5412]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

`始终定位打开的文档`为关闭状态时，文档树选择一篇文档后会有一个聚焦状态，当编辑器切换到其他文档或者关闭文档时，文档树还是聚焦在之前选择的那篇文章。

### 期待的结果 Expected result

选择文档进入聚焦状态，编辑器切换到其他文档时更改聚焦文档，关闭文档时取消聚焦。

`始终定位打开的文档`开关打开和关闭时逻辑统一，大部分逻辑与开关打开时保持一致，焦点都是与编辑器联动，需要加入是关闭文档取消聚焦。

### 版本环境 Version environment

```markdown
- Version: v2.0.26
- Operating System:Windows 10/11
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
这个应该是设计如此，之前选择的文档保持不变。

**Comment by Temacc0531** [comment]
这样有个问题就是有时看文档树时会默认打开的就是聚焦的文档，然后就混乱了😅

**Comment by 88250** [comment]
选择的文档保留很重要的，和保持定位或者手动定位可以同时使用，如果不确定的话可以在此手动定位。

**Comment by 88250** [comment]
很重要的场景就是保留住这个位置，下次才能继续上下选择操作，而不是从头开始。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
