### ISSUE TITLE
使用文档树切换文档时无法回到上次编辑位置

### ISSUE THREAD

**Issue by LecoLu** [siyuan-note/siyuan#5420]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [x] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如果在标签页切换文档，他会正常显示上次编辑的位置。 
而在文档树切换文档的时候，他会出现直接跳到文档最顶部的问题。然后右边滑块还是在上次编辑位置，但是文档内容显示的是顶部。

### 期待的结果 Expected result

在文档树切换文档时，如果该文档已经被打开，直接跳到上次编辑的位置。而不是跳到文档顶部。

### 截屏或者录屏演示 Screenshot or screen recording presentation

这个问题应该很容易复现。

### 版本环境 Version environment

```markdown
- Version: 2.0.25
- Operating System: Windows 11  X64
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
可以使用
