### ISSUE TITLE
提供替换图片自剪贴板功能

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#5421]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

图片失效，需要进行更改，但是还需要保留图片的题注信息。

1. 翻找之前的网页剪辑，发现图源挂了
2. 复制网页内容，粘贴，防盗链导致URL无法显示

遇到以上情况，一般需要手动一张张复制粘贴图片，然后把之前的失效图片删掉进行替换，然后再手动复制题注

### 描述可能的最优解决方案 Describe the optimal solution

参考PPT的图片右键菜单：
![image](https://user-images.githubusercontent.com/19968935/179204303-99236bb1-76af-474a-b206-9e678ca932bb.png)

本质上做了两件事：保存剪贴板的图片到思源assets中，复制本地地址替换选中的图片地址。

目前的工作流似乎并不能方便的快速执行上面的操作

**Comment by 88250** [comment]
试试这个替代操作：

1. 将下载好的 assets 批量插入，这样它们就存在于 assets/ 文件夹中了
2. 找到要替换的图片，重新粘贴 `图片地址`

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by HowcanoeWang** [comment]
这套流程和直接粘贴图片然后复制题注好像操作量差不多，期待后续能更快捷的实现吧
