### ISSUE TITLE
复制/导入图片时，显示提示文本(复制提示文本到标题)

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#5422]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

复制wolai的图片，或导入wolai的markdown时。wolai的图片标题会变成思源中的提示文本隐藏起来，而不是可以显示的标题

![image](https://user-images.githubusercontent.com/19968935/179206479-5ef80e04-689a-4b45-b865-03c70619c9ba.png)

### 描述可能的最优解决方案 Describe the optimal solution

设置里面可以设定，复制图片时，图片题注保存为 **提示文本**(默认) 或 **标题文本**

### 描述候选的解决方案 Describe the candidate solution

复制图片时，将图片题注同时保存为**提示文本**和**标题文本**

**Comment by 88250** [comment]
这个主要是 Markdown 语法定义的： `![提示文本](bar "标题文本")` 

建议导入前在外部处理，感谢反馈。

**Comment by HowcanoeWang** [comment]
> 这个主要是 Markdown 语法定义的： `![提示文本](bar "标题文本")`
> 
> 建议导入前在外部处理，感谢反馈。

原来是wolai导出的格式不对啊=_=

markdown还能手动处理一下，那直接选中复制粘贴就有点麻烦了

**Comment by 88250** [comment]
不同软件之间复制粘贴总有些地方没法保持一致的，我们尽量以 Markdown 规范进行。
