### ISSUE TITLE
有些文档的内容和进度条有问题

### ISSUE THREAD

**Issue by ChirsGod** [siyuan-note/siyuan#5423]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/50586375/179210350-a1c8883d-88b4-4abe-b182-60a68bfacc33.png)
比如上图这篇文章，拖拽条到下文已经没法继续拖拽了，但是实际上内容却没有完。

手机移动端也有类似的情况，
![8025267f1de8324fffd1ec895ffe3cb](https://user-images.githubusercontent.com/50586375/179210743-60363c16-8d03-43c8-a685-9f91a807eb7b.jpg)
但是在pc中居然是正常的
![image](https://user-images.githubusercontent.com/50586375/179210869-06e2ac30-9c04-4246-a64e-4f7992bb4c62.png)

### 期待的结果 Expected result

优化拖拽条和内容显示

### 版本环境 Version environment

```markdown
- Version: 2.0.27
- Operating System: Windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9120284/siyuan.log)

**Comment by ChirsGod** [comment]
补充说明一点，https://user-images.githubusercontent.com/50586375/179210350-a1c8883d-88b4-4abe-b182-60a68bfacc33.png，这里如果硬拖拽蓝条往底下，也是可以看到内容的。这个时候灰色拖拽条就变正常了。。。。。

**Comment by ChirsGod** [comment]
[杨得志V2.0.sy.zip](https://github.com/siyuan-note/siyuan/files/9124757/V2.0.sy.zip)
[刘亚楼-修改.sy.zip](https://github.com/siyuan-note/siyuan/files/9124759/-.sy.zip)
@Vanessa219 附件已上传，请查收。

**Comment by Vanessa219** [comment]
感谢反馈，已经可以重现了。
