### ISSUE TITLE
希望不用官方的云储存而是私有云储存

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#5426]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

1. wps的事情告诉我们云厂家都是按关键词锁定文件和删除文件的 环境不好 私有云 docker 这些没问题
2. 搭建个群晖啥的成本也不高  黑裙就更便宜
3. 我当然是**希望我的数据能通过webdav啊 或者docker建立服务器版本的方式来达到同步 以及一个账号全平台登录管理**

### 描述可能的最优解决方案 Describe the optimal solution

1. 简单点儿 支持下webdav吧
2. 复杂点儿 docker版来储存数据 建立账号其他地方可以登录 数据本地储存 云端也同步 的全体系

### 描述候选的解决方案 Describe the candidate solution

不想用你们的云储存

**Comment by 88250** [comment]
之前支持过，但是不稳定，你可以测试一下把 WebDAV 通过工具模拟为磁盘驱动器，类似这样的网络文件系统不适合做频繁读写。
