### ISSUE TITLE
希望官方能更包容不要 写个帖子就能踢群的操作

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#5427]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

1. 在发了这个帖子的情况下
https://github.com/siyuan-note/siyuan/issues/5426?utm_source=ld246.com
这个帖子是发到你们论坛里的 

然后群主通缉我
踢人
![QQ截图20220716003614](https://user-images.githubusercontent.com/108032980/179268808-7c140ecd-edc3-40e4-9fbc-4ad94d28bee6.png)

这个群也是在你们官方链接你的 我不知道这个帖子有什么态度上 或者各个方面的问题

### 描述可能的最优解决方案 Describe the optimal solution

希望能更包容

### 描述候选的解决方案 Describe the candidate solution

希望能更包容

**Comment by 88250** [comment]
我们不太清楚发生了什么，抱歉。

**Comment by lmf-bit** [comment]
目前思源应该是主要靠私有云存储的方式作为收益手段，如果支持私有云，类似于joplin接入第三方网盘，可能会导致作者失去一大部分收入。我觉得这个提议可以提，但作者如果没有采纳，也不应该指责。况且目前思源已经开源，动手能力强可以自己接入第三方网盘。

**Comment by zhuhaisto** [comment]
是的 你说得非常正确  其实你看我刚那个帖子 里面是没有任何指责和要求的 我只是刚用这个软件问清楚情况，但我发了不到两分钟 群里就开始通缉我了 我承认是我发的 然后就被踢了。我也不想说了

**Comment by 88250** [comment]
老铁你可能想多了，通缉个啥哟……你发的帖子我们没觉得不妥，而且你提问的问题之前也陆续有人问过不止一次。

类似问题的讨论中不乏涉及到盈利模式的讨论，我们并不避讳，希望不要产生误解，谢谢。

**Comment by lmf-bit** [comment]
那希望官方给出合理的解释，为什么踢人。不要伤了思源的口碑。

**Comment by zhuhaisto** [comment]
感谢 我现在好多了 支持你们

**Comment by 88250** [comment]
> 那希望官方给出合理的解释，为什么踢人。不要伤了思源的口碑。

Q 群是其他热心用户建立的，所以我不太清楚发生了什么。

**Comment by lmf-bit** [comment]
> > 那希望官方给出合理的解释，为什么踢人。不要伤了思源的口碑。
> 
> Q 群是其他热心用户建立的，所以我不太清楚发生了什么。

好的，解释清楚就行，我一直以为是官方的群。

**Comment by zhuhaisto** [comment]
事情回顾：但我就真的只是发个帖子 没要求 就是问一下而已 额就马上有人在群里截图问是谁发的  然后开始踢人了 我觉得虽然不是官方的群 但是既然是官网公布的
描述：Q群是官网上面公布的群 但不是官方群 
建议：官方公布的也应该严谨些建立下规则比较好 大家开放 包装 讲规则
理解：其次我觉得 思源 不算一个商业化的软件 而且人员应该也不多 大家有些情绪也正常 但我还是希望 规则 包容 开放
另外：大佬可以的弄个key吧 搞个服务器版卖卖授权码也可以的 家里有群晖不用也蛮可惜的。而且空间大又快 我还是支持开源作者收入的 按年卖跟会员一样呗 给我们这种场景用户一个选择

**Comment by zhuhaisto** [comment]
就是发了刚刚那个帖子 我觉得 那个群是你们官方公布的群 我也有点儿心塞 我说错了什么吗？很严重吗？
