### ISSUE TITLE
块嵌入内容直接选择复制

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#543]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
V0.4.8

- 当前块嵌入内容需要在编辑模式下才能选择，略显不便
- 期望在预览模式能够直接使用鼠标选择并复制

**Comment by 88250** [comment]
目前块引支持用鼠标选择内容后复制，块嵌入不支持选择。

为了保持操作统一，计划这两者的框框上都加入一个“复制块内容”按钮，你感觉如何？

![image](https://user-images.githubusercontent.com/873584/99827286-697ebd80-2b94-11eb-9457-cfeece8a86cb.png)

![image](https://user-images.githubusercontent.com/873584/99827332-756a7f80-2b94-11eb-9bb7-35b9249d6c78.png)

**Comment by lss6378** [comment]
> 
> 
> 目前块引支持用鼠标选择内容后复制，块嵌入不支持选择。
> 
> 为了保持操作统一，计划这两者的框框上都加入一个“复制块内容”按钮，你感觉如何？
> 
> ![image](https://user-images.githubusercontent.com/873584/99827286-697ebd80-2b94-11eb-9457-cfeece8a86cb.png)
> 
> ![image](https://user-images.githubusercontent.com/873584/99827332-756a7f80-2b94-11eb-9bb7-35b9249d6c78.png)

嵌入引用选择部分复制更常用，比如我引用了一段古诗：
> 白日依山尽
> 黄河入海流
> 欲穷千里目
> 更上一层楼

在写作的时候，我只想拷贝其中一句`更上一层楼`，这种情况下不跳转直接选择是最方便的。
