### ISSUE TITLE
自动/批量删除云端未引用的图片资源

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#5430]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当我清空笔记时，云端的图片资源并没有被删除，并且需要遍历的删除。
![image](https://user-images.githubusercontent.com/47321059/179334619-e0d649cd-890e-45a3-a6b9-4a5cc5ef29a3.png)

### 描述可能的最优解决方案 Describe the optimal solution

增加批量删除的功能或者自动删除未引用的图片资源

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/4568

**Comment by 88250** [comment]
补充一下，云端图床没有计算是否引用的能力。
