### ISSUE TITLE
每天早上第一次打开日记模版中的SQL查询嵌入块都现实“不存在复合条件的内容”

### ISSUE THREAD

**Issue by netdog2019** [siyuan-note/siyuan#5431]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

每天早上第一次打开日记模版中的SQL查询嵌入块都现实“不存在复合条件的内容”
需要点击“重新索引”后，日记中的SQL查询才正常现实。也不一定是每天早上，又是中午，下午也会出现这种问题。最近几个版本才会这样，原来的版本没有这个问题。
![Uploading Quicker_20220716_102845.png…]()

### 期待的结果 Expected result

原来的SQL查询都能自动显示，现在就时不时不正常，希望能正常。

### 版本环境 Version environment

```markdown
- Version: 2.0.26
- Operating System: WIN10 64X
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9125009/siyuan.log)

**Comment by 88250** [comment]
可能是新版同步的问题，v2.1.0 修复了相关的一个 bug，等发布后请升级看下。

**Comment by netdog2019** [comment]
好的，D大高效威武~~~
