### ISSUE TITLE
给 Daily Note 加上更生动的 Icon

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5432]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

创建 Daily Note 时，目前 Siyuan 会使用默认的 Icon，比较单调

自己网上找了一些 Icon，感觉还蛮好看的，如下

<img width="181" alt="image" src="https://user-images.githubusercontent.com/7659710/179338437-6c43dadf-c9a4-4cb4-9624-787681334da2.png">

如果能内置一些关于日期的 Icon，并且自动换上，感觉会提升使用体验

### 描述可能的最优解决方案 Describe the optimal solution

见上

**Comment by 88250** [comment]
目前这个比较难实现：

* Emoji 没有全部日期的
* 没有精力自制图标

所以这个提议的前置是需要实现动态生成日历图标或者制作全量日历图标，就目前的任务计划和开发资源上估计无法达成。

先关闭了，期待更多开发者加入开发。
