### ISSUE TITLE
网络图片转换为本地图片功能优化

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#5433]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前网络图片转换为本地图片功能，使用后，会跳转到文档开头处。
希望转换完成后，仍保留在当前编辑处。
![image](https://user-images.githubusercontent.com/16383685/179342935-b0b7d2a7-76de-4bb3-86d9-ada6543a9a45.png)

### 描述可能的最优解决方案 Describe the optimal solution

无

**Comment by 88250** [comment]
目前不行，转换以后需要重新加载编辑器。位置保留请关注 #4042
