### ISSUE TITLE
调整程序图标大小

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#5438]
https://ld246.com/article/1658018347278

![image](https://user-images.githubusercontent.com/873584/179411077-0efadfc9-5232-477d-aaea-867dbccd4a4c.png)

**Comment by JokeenZhang** [comment]
调整后的图标会不会太大了，在程序坞中和别的应用图标比起来是这样

<img width="319" alt="image" src="https://user-images.githubusercontent.com/33319484/179693839-e509eea8-da2e-48c7-939d-2cd6a46c3b3f.png">

**Comment by Marszs** [comment]
貌似调整之后的图标在Mac中更大了
<img width="389" alt="image" src="https://user-images.githubusercontent.com/66620626/179897926-4fc24be5-41ae-4d6d-8290-a49331d21e51.png">
