### ISSUE TITLE
请问块查询的方式是怎么样的逻辑和语法

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#5440]
### {{引用}} 的时候
有没什么逻辑 例如：
1. 查询现在这个文档的结构 然后选中
2. 或者查询某个目录下的结构选中
3. 或者查询块的名称、备注、tags、等选中

### 文档结构
1. 另外一个文档 结构是文档树 有各种块的类型
2. 那么是不是要跟块做些命名标识后才能查询使用啊
3. 我看官方默认文档输入{{嵌入快}}就能出来很多类似的东西

图：
![QQ截图20220717161337](https://user-images.githubusercontent.com/108032980/179389891-37c212f9-183b-4829-9f04-51743941058b.png)
我自己的文档就引用不出来 哪怕上面有个列表

但是官方的却可以
![QQ截图20220717161438](https://user-images.githubusercontent.com/108032980/179389923-9fb678f3-7b69-4265-b01c-dec3b822df59.png)

### 描述可能的最优解决方案 Describe the optimal solution

希望有所解答

### 描述候选的解决方案 Describe the candidate solution

希望有所解答

### 其他信息 Other information

希望有所解答

**Comment by 88250** [comment]
重建索引后再试试搜索。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
