### ISSUE TITLE
Internal file management on Ipad.

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#5441]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

I bought an iPad exclusively to study. SiYuan is the main program for playing information, images and other files. But I have a problem! I need to copy the Windows 10 folder to the Ipad's internal memory. But the program, on Ipad, does not have the option to choose the information folder in the "about" menu. I'm also trying to find the local folder that the program automatically created on the Ipad, but I can't find it! Can someone help me?

### 期待的结果 Expected result

Find e choose folder 

### 版本环境 Version environment

```markdown
- Version: 2.0.27
- Operating System: Ipad
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9127641/siyuan.log)

**Comment by 88250** [comment]
Settings - Export - Import Data

**Comment by taozina** [comment]
@88250 Thanks.
