### ISSUE TITLE
希望提供docker server，支持client连接同步数据。

### ISSUE THREAD

**Issue by OLOrz996** [siyuan-note/siyuan#5443]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

更希望数据存储在本地，而不是外网的云服务

### 描述可能的最优解决方案 Describe the optimal solution

希望client可以连接docker同步数据，类似joplin的server。
如果担心影响盈利，希望可以通过出售licensee的方式支持。
本人已经是订阅用户，也愿意为这个特性额外付费。

**Comment by 88250** [comment]
目前没有精力进行相关开发，后续可能会考虑，感谢提议。
