### ISSUE TITLE
macOS 端程序图标调小

### ISSUE THREAD

**Issue by gslnzfq** [siyuan-note/siyuan#5444]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

mac版本，图标有点大

### 期待的结果 Expected result

图标和其他图标可以协调一点

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/12946062/179459269-78ea2500-9afb-4ed1-bbfe-0db805c3e9de.png)

![image](https://user-images.githubusercontent.com/12946062/179459510-9dffa949-64f8-493c-b6c6-d3a97e2dd3e8.png)

### 版本环境 Version environment

```markdown
- Version: 2.1.0
- Operating System: macOS 12.4 
- Browser (if used):
```

### 日志文件 Log file

null

**Comment by choyy** [comment]
Linux 下图标偏小
![图片](https://user-images.githubusercontent.com/68107073/179652760-d8a32356-0909-4287-bcd3-bedceb16fe2b.png)

**Comment by 88250** [comment]
@choyy 收到，这个 issue 里一起处理。

**Comment by 88250** [comment]
@choyy 好像不对，已经处理过了，你用的是 v2.1.0 吗？

**Comment by 88250** [comment]
@choyy 找到问题了，任务栏的没处理，这个版本改进，谢谢。
