### ISSUE TITLE
工作空间的选择做到侧边栏

### ISSUE THREAD

**Issue by better-cen** [siyuan-note/siyuan#5445]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

工作环境里要区分工作文档和个人文档，个人文档可以云同步，但是工作的不行

### 描述可能的最优解决方案 Describe the optimal solution

可以把工作空间放在侧边栏里，这样侧边栏从现在的笔记本->笔记的两层结构，变成了工作空间->笔记本->笔记的三层结构。切换非常灵活

**Comment by 88250** [comment]
工作空间切换在设计上不是高频功能，所以放到设置中。

建议仅使用同一个工作空间，通过 `忽略文件` 来控制同步。
