### ISSUE TITLE
剪切板复制 `粘贴转义文本` 丢失 `\`

### ISSUE THREAD

**Issue by o-h-l-c** [siyuan-note/siyuan#5446]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

剪切板中的文本，在黏贴到编辑器中后会出现丢失反斜杠的问题。
![image](https://user-images.githubusercontent.com/71399811/179501855-72b3d4ba-f136-4b82-9e72-6c3d6ecf1781.png)

### 期待的结果 Expected result

从剪切板中粘帖出来的文本不再丢失反斜杠。

### 版本环境 Version environment

```markdown
- Version: v2.0.25
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

I 2022/07/12 15:34:19 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/12 15:34:20 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Apps\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuanNote\SiYuan, data 5.6 MB]
I 2022/07/12 15:34:20 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/12 15:34:23 conf.go:523: database size [5.9 MB], block count [1914]
I 2022/07/12 15:34:23 working.go:139: kernel booted
I 2022/07/13 01:38:25 conf.go:362: exited kernel
I 2022/07/13 01:39:13 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/13 01:39:13 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Apps\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuanNote\SiYuan, data 5.6 MB]
I 2022/07/13 01:39:13 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/13 01:39:14 conf.go:523: database size [6.0 MB], block count [1932]
I 2022/07/13 01:39:14 working.go:139: kernel booted
I 2022/07/13 01:39:27 conf.go:362: exited kernel
I 2022/07/13 01:39:32 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/13 01:39:32 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Apps\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuanNote\SiYuan, data 5.6 MB]
I 2022/07/13 01:39:32 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/13 01:39:32 conf.go:523: database size [6.0 MB], block count [1932]
I 2022/07/13 01:39:32 working.go:139: kernel booted
I 2022/07/13 23:10:45 index.go:221: rebuilt database for notebook [20220713231043-gbq7n74] in [1.01s], tree [count=0, size=0 B]
I 2022/07/13 23:10:53 index.go:358: resolved refs [68] in [7370ms]
W 2022/07/13 23:11:10 blocktree.go:292: save block tree [size=485 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [3.65s]
W 2022/07/13 23:11:26 blocktree.go:292: save block tree [size=485 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [7.98s]
W 2022/07/13 23:11:30 transaction.go:138: tx [3683ms]
W 2022/07/13 23:11:45 blocktree.go:292: save block tree [size=485 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [3.65s]
W 2022/07/13 23:11:45 transaction.go:138: tx [2189ms]
W 2022/07/13 23:13:31 transaction.go:138: tx [2765ms]
W 2022/07/13 23:13:37 transaction.go:138: tx [2738ms]
W 2022/07/13 23:13:41 blocktree.go:292: save block tree [size=485 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [6.25s]
W 2022/07/13 23:14:14 blocktree.go:292: save block tree [size=485 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.85s]
W 2022/07/13 23:15:03 transaction.go:138: tx [8108ms]
W 2022/07/13 23:15:05 blocktree.go:292: save block tree [size=485 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [4.85s]
W 2022/07/13 23:15:23 blocktree.go:292: save block tree [size=485 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [3.99s]
W 2022/07/13 23:15:27 transaction.go:138: tx [2181ms]
W 2022/07/13 23:15:49 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [3.80s]
W 2022/07/13 23:16:38 transaction.go:138: tx [2046ms]
W 2022/07/13 23:16:42 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.91s]
W 2022/07/13 23:16:43 transaction.go:138: tx [3365ms]
W 2022/07/13 23:16:52 transaction.go:138: tx [3689ms]
W 2022/07/13 23:16:56 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [6.22s]
W 2022/07/13 23:17:22 transaction.go:138: tx [3284ms]
W 2022/07/13 23:17:28 transaction.go:138: tx [2579ms]
W 2022/07/13 23:17:35 transaction.go:138: tx [3774ms]
W 2022/07/13 23:17:42 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [8.22s]
W 2022/07/13 23:17:43 transaction.go:138: tx [2113ms]
W 2022/07/13 23:17:59 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.36s]
W 2022/07/13 23:18:34 transaction.go:138: tx [4150ms]
W 2022/07/13 23:18:35 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [4.86s]
W 2022/07/13 23:19:00 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.12s]
W 2022/07/13 23:19:18 transaction.go:138: tx [6130ms]
W 2022/07/13 23:19:21 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [6.30s]
W 2022/07/13 23:19:28 transaction.go:138: tx [3467ms]
W 2022/07/13 23:19:37 transaction.go:138: tx [2017ms]
W 2022/07/13 23:19:39 blocktree.go:292: save block tree [size=488 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.24s]
E 2022/07/13 23:19:44 transaction.go:982: update data is nil
W 2022/07/13 23:19:49 blocktree.go:292: save block tree [size=488 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.78s]
I 2022/07/13 23:19:50 database.go:84: reinitialized database [D:\SiYuanNote\SiYuan\temp\siyuan.db]
I 2022/07/13 23:19:53 index.go:221: rebuilt database for notebook [20220621182116-l45qgix] in [2.55s], tree [count=10, size=70 kB]
I 2022/07/13 23:19:55 index.go:221: rebuilt database for notebook [20220630004449-11j16st] in [0.01s], tree [count=2, size=3.1 kB]
I 2022/07/13 23:19:55 index.go:221: rebuilt database for notebook [20220713231043-gbq7n74] in [0.03s], tree [count=2, size=7.8 kB]
I 2022/07/13 23:20:14 index.go:221: rebuilt database for notebook [20210808180117-czj9bvb] in [14.43s], tree [count=49, size=1.2 MB]
I 2022/07/13 23:20:16 index.go:358: resolved refs [68] in [1918ms]
W 2022/07/13 23:23:31 blocktree.go:292: save block tree [size=486 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.68s]
I 2022/07/13 23:25:00 database.go:84: reinitialized database [D:\SiYuanNote\SiYuan\temp\siyuan.db]
I 2022/07/13 23:25:00 index.go:221: rebuilt database for notebook [20220621182116-l45qgix] in [0.06s], tree [count=10, size=70 kB]
I 2022/07/13 23:25:00 index.go:221: rebuilt database for notebook [20220630004449-11j16st] in [0.07s], tree [count=2, size=3.1 kB]
I 2022/07/13 23:25:00 index.go:221: rebuilt database for notebook [20220713231043-gbq7n74] in [0.01s], tree [count=2, size=3.3 kB]
I 2022/07/13 23:25:02 index.go:221: rebuilt database for notebook [20210808180117-czj9bvb] in [1.08s], tree [count=49, size=1.2 MB]
I 2022/07/13 23:25:03 index.go:358: resolved refs [69] in [550ms]
I 2022/07/13 23:29:30 index.go:221: rebuilt database for notebook [20220713232923-b8134az] in [0.73s], tree [count=0, size=0 B]
I 2022/07/13 23:29:34 index.go:358: resolved refs [68] in [2233ms]
W 2022/07/13 23:48:08 transaction.go:138: tx [4074ms]
W 2022/07/13 23:48:10 blocktree.go:292: save block tree [size=487 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [4.65s]
W 2022/07/14 00:04:03 blocktree.go:292: save block tree [size=488 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.59s]
W 2022/07/14 00:04:33 transaction.go:138: tx [4688ms]
W 2022/07/14 00:04:40 blocktree.go:292: save block tree [size=487 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.27s]
W 2022/07/14 00:04:57 blocktree.go:292: save block tree [size=487 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.67s]
W 2022/07/14 00:20:55 blocktree.go:292: save block tree [size=487 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.99s]
W 2022/07/14 00:20:55 transaction.go:138: tx [3133ms]
W 2022/07/14 00:22:52 blocktree.go:292: save block tree [size=488 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.59s]
W 2022/07/14 00:34:23 blocktree.go:292: save block tree [size=490 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.21s]
W 2022/07/14 00:34:23 transaction.go:138: tx [2323ms]
W 2022/07/14 00:37:45 blocktree.go:292: save block tree [size=492 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.37s]
W 2022/07/14 00:37:45 transaction.go:138: tx [4321ms]
W 2022/07/14 00:44:19 transaction.go:138: tx [2942ms]
W 2022/07/14 00:44:38 blocktree.go:292: save block tree [size=494 kB] to [D:\SiYuanNote\SiYuan\temp\blocktree.msgpack], elapsed [2.59s]
W 2022/07/14 00:48:35 transaction.go:138: tx [2195ms]
I 2022/07/14 18:28:28 conf.go:362: exited kernel
I 2022/07/14 19:33:50 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/14 19:33:51 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Apps\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuanNote\SiYuan, data 6.5 MB]
I 2022/07/14 19:33:51 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/14 19:33:57 conf.go:523: database size [6.3 MB], block count [2025]
I 2022/07/14 19:33:57 working.go:139: kernel booted
I 2022/07/14 21:34:20 conf.go:362: exited kernel
I 2022/07/14 21:34:31 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/14 21:34:31 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Apps\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuanNote\SiYuan, data 6.9 MB]
I 2022/07/14 21:34:31 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/14 21:34:32 conf.go:523: database size [6.3 MB], block count [2062]
I 2022/07/14 21:34:32 working.go:139: kernel booted
I 2022/07/15 17:31:49 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/15 17:31:49 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Apps\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuanNote\SiYuan, data 19 MB]
I 2022/07/15 17:31:50 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/15 17:31:55 conf.go:523: database size [7.0 MB], block count [2135]
I 2022/07/15 17:31:55 working.go:139: kernel booted
I 2022/07/18 13:31:42 index.go:221: rebuilt database for notebook [20220718133142-axpwsuc] in [0.03s], tree [count=0, size=0 B]
I 2022/07/18 13:31:43 index.go:358: resolved refs [70] in [590ms]
I 2022/07/18 16:04:10 conf.go:362: exited kernel
I 2022/07/18 16:04:20 working.go:103: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/07/18 16:04:20 runtime.go:45: kernel is booting:
    * ver [2.0.25]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Apps\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\SiYuanNote\SiYuan, data 20 MB]
I 2022/07/18 16:04:21 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/07/18 16:04:22 conf.go:523: database size [7.0 MB], block count [2247]
I 2022/07/18 16:04:22 working.go:139: kernel booted

**Comment by 88250** [comment]
下个版本可以使用 `粘贴转义文本` 进行粘贴，感谢反馈。

**Comment by Vanessa219** [comment]
xia
