### ISSUE TITLE
添加设置 pdf 窗口默认在左侧还是右侧打开

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5447]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前 pdf 窗口默认在右侧打开，本人觉得不太习惯，每次调整又很麻烦，希望能添加相关设置。

### 描述可能的最优解决方案 Describe the optimal solution

可以设置 pdf 窗口默认在左侧还是右侧打开

**Comment by 88250** [comment]
这个估计无法支持，页签默认的打开规则都是右侧的。
