### ISSUE TITLE
pdf 标注复制到文档中调整格式

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5449]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前 pdf 标注复制到文档中不能调整格式，例如加粗、斜体等，否则整个标注都会统一格式，而且会丢失链接。

### 描述可能的最优解决方案 Describe the optimal solution

pdf 标注复制到文档中支持调整格式，例如加粗、斜体等。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/2911
