### ISSUE TITLE
暗黑模式下剪藏 SVG 图片处理增强

### ISSUE THREAD

**Issue by crafter-z** [siyuan-note/siyuan#5455]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

使用浏览器插件从知乎上抓取文章时，使知乎的图片形式的公式适应思源的暗黑模式。
当前从知乎上抓取下来的图片，在思源的暗黑模式下显示效果如图：
![image](https://user-images.githubusercontent.com/62090995/179644918-2992ba38-47cd-43e9-8369-6f44184ac1ee.png)
在暗黑模式下的体验非常糟糕

### 描述可能的最优解决方案 Describe the optimal solution

在思源中添加一个选项，开启后可以对png的黑白做自适应，达到下图中的效果：
原文，正常显示：
![image](https://user-images.githubusercontent.com/62090995/179645089-4ec64445-6af7-4298-8157-62ed44ebb1a2.png)
暗黑模式，思源笔记当前的效果：
![image](https://user-images.githubusercontent.com/62090995/179644918-2992ba38-47cd-43e9-8369-6f44184ac1ee.png)
暗黑模式，浏览器插件DarkReader的显示效果，我想要的效果：
![image](https://user-images.githubusercontent.com/62090995/179645119-676de63e-5b5b-4b6f-8544-96cb8587e051.png)
该对比测试来源为知乎链接https://zhuanlan.zhihu.com/p/35893078 ，使用的浏览器插件是DarkReader，github地址为https://github.com/darkreader/darkreader。
知乎上的公式基本都是以图片形式展现的，在我日常使用中这样的体验非常有必要。

### 描述候选的解决方案 Describe the candidate solution

chrome插件dark reader解决了这个问题，可以舒适的在暗黑模式下阅读透明底黑字的图像，插件地址https://github.com/darkreader/darkreader，可以作为参考，我想请求的特性的就是这个插件一样的暗黑模式图片效果

### 其他信息 Other information

无

**Comment by crafter-z** [comment]
我没处理好链接，补一下，测试地址：知乎链接：[https://zhuanlan.zhihu.com/p/35893078](https://zhuanlan.zhihu.com/p/35893078)
DarkReader插件地址[https://github.com/darkreader/darkreader](https://github.com/darkreader/darkreader)

**Comment by 88250** [comment]
这个问题估计无法解决了，SVG 元素无法转换，我们关闭了，抱歉抱歉。
