### ISSUE TITLE
新建一个块，可以再修改

### ISSUE THREAD

**Issue by BonjourL** [siyuan-note/siyuan#5457]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

比如新建一个h2 ,我想再加一个# 变成h3,而不是去转换

### 描述可能的最优解决方案 Describe the optimal solution

可以本地直接存的是md5结尾的文件么，这样我用其他软件也可以编辑

**Comment by 88250** [comment]
1. 暂时只能用块标菜单转换，或者用快捷键
2. 思源不是 Markdown 编辑器

感谢反馈。

**Comment by Temacc0531** [comment]
回答一下第一个问题在H2标题前退格就可以把标题等级删除，然后重新输入###就变成H3了
