### ISSUE TITLE
增加外部应用通过协议打开思源的某篇笔记的某个header下

### ISSUE THREAD

**Issue by lowwor** [siyuan-note/siyuan#546]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

外部应用需要与思源笔记联动，例如anki配合记忆，在anki中通过协议，直接跳到某篇笔记，某个标题下

**Comment by 88250** [comment]
请通过内容块 URL 实现，谢谢。

![image](https://user-images.githubusercontent.com/873584/99865242-50e9c400-2be3-11eb-93e9-a3fd66247402.png)
