### ISSUE TITLE
支持更丰富的微信提醒方式

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#5461]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

主要可以用作长期复习或者定期任务的提醒

### 描述可能的最优解决方案 Describe the optimal solution

在微信提醒设置方式上可以增加：
1. 定时循环提醒（比如每三天提醒一次）
2. 或者是用户自定义时间提醒（比如设置按照记忆曲线的时间提醒）

**Comment by 88250** [comment]
这个后面如果要做间隔复习时再考虑，感谢提议。
