### ISSUE TITLE
IOS APP不支持自定义数据文件存储路径，希望支持

### ISSUE THREAD

**Issue by hekmon8** [siyuan-note/siyuan#5464]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我使用iCloud来实现多端的数据同步，在iCloud上自定义了存储数据的位置，电脑端的数据在此处存储，IOS APP似乎不行。

### 描述可能的最优解决方案 Describe the optimal solution

如果IOS系统的沙盒机制支持如此操作，那最好；如果不支持，希望可以在桌面端软件中加入对iCloud位置的存储，实现基于iCloud的多端数据同步；

**Comment by 88250** [comment]
目前暂时不考虑支持，感谢提议。

**Comment by hekmon8** [comment]
你好，我已经收到，谢谢！
