### ISSUE TITLE
给标题或者次级标题加关键字

### ISSUE THREAD

**Issue by xiaoheimissu** [siyuan-note/siyuan#5465]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候标题并不能将本节所记录的东西完全概括（毕竟标题只有几个字）。有些小点比较重要，但是可能只有几句话，分成次级标题又非常凌乱。虽然思源的搜索功能确实比较强大，速度很快并且可以搜索正文所记录的内容。但是如果显示所有搜索到的正文内容会显得比较凌乱，只显示标题会有很多搜索不到的东西。希望可以自己给标题添加关键字，在搜索的时候可以搜索到对应的关键字和标题。

### 描述可能的最优解决方案 Describe the optimal solution

类似于标签？但是好像在搜索中并没有看见可以把标签加上。
![image](https://user-images.githubusercontent.com/68829841/179806754-3e29afc9-de1d-488b-89f1-64bf67589b40.png)

**Comment by xiaoheimissu** [comment]
我的意思是说在搜索的时候我可以去掉搜索正文，但是此时会漏掉很多东西。如果我可以给标题加一些关键字，那么搜索的时候就可以根据关键字找到。这样控制了搜索的颗粒度。

**Comment by 88250** [comment]
设置 - 搜索 里面有类型过滤。
