### ISSUE TITLE
块引浮窗支持 Ctrl+悬浮 触发

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5467]
https://ld246.com/article/1658288220322

**Comment by choyy** [comment]
https://github.com/siyuan-note/siyuan/issues/4781

**Comment by UFDXD** [comment]
@88250 
目前鼠标一秒自动触发挺好的，不需要多一步操作，而这个习惯大部分人也养成了，突然变更只对某些人有利，而对于习惯的人不友好（比如我）。

可以支持Ctrl+触发，但希望这是个在设置里面的可选项，让那些觉得自动触发碍事的人自己手动开启。

**Comment by 88250** [comment]
@choyy 感谢提醒。
