### ISSUE TITLE
使用Query插件查询时，遇到CPU打满的情况

### ISSUE THREAD

**Issue by Foundation-Maker** [siyuan-note/siyuan#5469]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

想自己增加一个所有标签表格展示的功能，采用了Query插件，进行blocks 表的tag 内容查询，使用查询语句，自己实现字符切割功能。查询以下语句，CPU立刻打满了。
``` SQL
WITH split(word, str) AS (
	SELECT '', (select tag from blocks where type = 'd' and tag != '' and substr(tag,0,instr(tag,' ')) != '' and box != '20210808180117-czj9bvb')||','
		UNION ALL SELECT
		substr(str, 0, instr(str, ' ')),
		substr(str, instr(str, ' ')+1)
		FROM split WHERE str!=''
)
SELECT word FROM split WHERE word!='';
```

### 期待的结果 Expected result

能自己实现表格化的所有标签功能。 

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="929" alt="image" src="https://user-images.githubusercontent.com/46839690/179941025-fa5be423-3ed5-4a24-94b8-09fc6ced8060.png">

### 版本环境 Version environment

```markdown
- Version:  v2.1.0
- Operating System: macos
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9148215/siyuan.log)

**Comment by 88250** [comment]
我先关闭了，不太确定问题，能否给 Query 仓库作者反馈下看看，谢谢。
