### ISSUE TITLE
表格内 `<br>` 编辑表现不一致

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#547]
### 描述问题 Describe the problem

表格内HTML换行符在换行之后，切到其它单元格，切回来并编辑任何字符的时候会出现且无法隐藏

````````markdown
| 属性              | 变量       | 公式              | 描述                                                                                     |
| ------------------- | ------------ | ------------------- | ------------------------------------------------------------------------------------------ |
| **剩余价值率** | $m'$         | $m'=\frac{m}{v}$    | $m$社会必要劳动时间<br />$v$必要劳动时间                                     |
````````

### 截屏或录像 Screenshot or video

![QQ截图20201121101812](https://user-images.githubusercontent.com/30611816/99865261-8bebf780-2be3-11eb-87e6-2b695b9997c0.png)
切至其它单元格后编辑任何字符
![QQ截图20201121101829](https://user-images.githubusercontent.com/30611816/99865257-85f61680-2be3-11eb-804e-c3a504d24d2e.png)

### 版本环境 Version environment

* 版本 Version：0.4.8
* 操作系统 Operating system：Win10 版本2004
* 浏览器（如果使用）Browser (if used)：Edge

**Comment by 88250** [comment]
你好，换行符不隐藏是设计如此。编辑表现不一致稍后优化，谢谢。
