### ISSUE TITLE
为虚拟引用 添加笔记级别的引用隔离 

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#5476]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我有好几个笔记，这些笔记都有一个同名文档，这些同名文档在各自笔记下都有另一种不同的意义

在开启了虚拟引用的情况下，在其中一个笔记查看同名虚拟引用就会跳出好几个其他笔记的同名引用内容

面对这样的情况，在同名文档少的时候可以被接受，但同名的引用多了就不方便了，需要付出心力仔细的辨别需要的内容

### 描述可能的最优解决方案 Describe the optimal solution

方案1
为虚拟引用添加笔记级别的隔离，各自笔记文档的虚拟引用只能在各自笔记触发（自身笔记的虚拟引用只能显示自身笔记的引用内容）。
这样的好处就是虚拟引用不会出现其他笔记的同名引用的混乱，就算是同一个笔记下出现同名的虚拟引用，情况也会好很多（若真的需要跨笔记引用可以用“描文本引用”或“思源超链接”，而非虚拟引用）

### 描述候选的解决方案 Describe the candidate solution

方案2
不考虑笔记级别虚拟引用的隔离。
但是在本笔记的虚拟引用触发时，本笔记虚拟引用指向的内容要优先排在悬浮窗内的最上面，其他笔记的同名的虚拟引用内容排放在下面（其他笔记同名虚拟引用的内容排在同名引用悬浮窗内的下面）

**Comment by UFDXD** [comment]
其实如果可以同时多开工作空间，这个问题就不需要解决了

**Comment by 88250** [comment]
笔记本隔离可能不是太通用，比如有的知识需要分类存放，但是却需要跨类交叉查询。

这个情况估计要考虑类似 Wiki 上同义词的做法，将定义块按类分组，悬浮虚拟引用时按组展现。目前还没有想好，后续继续收集类似需求，谢谢。
