### ISSUE TITLE
输入 HTML 实体之后无法继续再输入其它字符

### ISSUE THREAD

**Issue by caizongchao** [siyuan-note/siyuan#548]
### 期待的结果 Expected result
输入 &copy; 之后可以继续输入其它字符。在Typora里试了是可以的。

### 截屏或录像 Screenshot or video
![siyuan](https://user-images.githubusercontent.com/1753934/99865861-9dcf9980-2be7-11eb-8857-a3bf7080af55.gif)
![typora](https://user-images.githubusercontent.com/1753934/99865866-a1632080-2be7-11eb-94c0-03cd44c4d143.gif)

### 版本环境 Version environment

* 版本 Version：0.4.8
* 操作系统 Operating system：windows 10

**Comment by 88250** [comment]
感谢反馈，目前输入 HTML 实体都有这个问题，会一并修复。
