### ISSUE TITLE
`清理未引用资源` 支持跟随 assets 文件夹符号链接

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5480]
https://ld246.com/article/1658393401741

**Comment by HowcanoeWang** [comment]
似乎符号链接删除资源，是直接删除而不是移动到.history里面？我删除后看是空的

**Comment by 88250** [comment]
@HowcanoeWang 我这里测试正常哦。

```
F:\SiYuan\data>mklink /D assets "F:\assets"
为 assets <<===>> F:\assets 创建的符号链接
```

然后清理未引用资源，会被移动到 `F:\SiYuan\history\` 下。

**Comment by HowcanoeWang** [comment]
> @HowcanoeWang 我这里测试正常哦。
> 
> ```
> F:\SiYuan\data>mklink /D assets "F:\assets"
> 为 assets <<===>> F:\assets 创建的符号链接
> ```
> 
> 然后清理未引用资源，会被移动到 `F:\SiYuan\history\` 下。

忘说了，我用的是Linux的AppImage，`ln -s`建立的软连接

**Comment by 88250** [comment]
理论上应该是一样的，暂时没有时间验证，估计只能等其他人帮忙试试看了。
