### ISSUE TITLE
关于移动端的反馈

### ISSUE THREAD

**Issue by ZephyrJung** [siyuan-note/siyuan#5481]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在移动端中使用Siyuan。
目前siyuan的客户端是同一套，在平板上使用与PC端上没有差异，但是在手机端，小屏幕、纵版的情况下，使用差异较大，且由于屏幕较小，客户端上按钮、图标较多，容易误触，编辑困难。之前写了一篇文章，感觉格式有点怪，在PC端上发现我以为写的是正文，实际写的是标签……

### 描述可能的最优解决方案 Describe the optimal solution

提供手机端专用版本Lite版（小屏幕）
1. 手机端只提供简单的编辑功能，在特定专区下，到PC、平板时进行格式处理，手机端只记录文字。
2. 非手机端文档只读（避免误操作引起文档变化）
3. 目录树不可更改（不小心点击了emoji后，基本就会被emoji选择框沾满）。
4. 编辑界面可尽量简洁，放大，不需要支持emoji操作，可插入照片足矣
5. 文档树功能不需要太多能力，只需要支持新建、删除等简单操作
6. 将同样式图标不同功能的，进行修改区分

### 描述候选的解决方案 Describe the candidate solution

对某些不常用的操作，在手机端模式下设置隐藏，避免因为屏幕小造成的误触，引起使用上的不便

### 其他信息 Other information

引起上述想法的操作问题：
1. 手机端，想点开目录，但经常进入目录本身
2. 误以为文件索引重建按钮是数据同步按钮

**Comment by 88250** [comment]
单独出版本估计不会考虑了，移动端目前暂时只能用来看，编辑体验比较糟糕，可能要等明年才会有时间进行改进。期待社区有移动应用开发者加入帮助开发。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
