### ISSUE TITLE
块级公式输入完成后换行出现问题

### ISSUE THREAD

**Issue by hytracen** [siyuan-note/siyuan#5482]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/43265307/180189609-ef5d3372-be49-4d68-9d51-dc0dc9d4959b.png)
数学公式输入完毕之后，按下Ctrl+Enter，光标会定位到一个奇怪的位置，此时无法任何字符。此时如果按下回车，则又会回到公式编辑的状态。

### 期待的结果 Expected result

提供键盘快捷键，使得在编辑完数学公式之后，可以不用鼠标，方便的跳转到下一行进行编辑。比如wolai笔记中的Ctrl+Enter。
![image](https://user-images.githubusercontent.com/43265307/180189168-96933f8a-40bb-40e8-8046-f6c9c82b7eb0.png)

### 截屏或者录屏演示 Screenshot or screen recording presentation

截图已在上述描述中提供

### 版本环境 Version environment

```markdown
- Version: 2.1.0
- Operating System: windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9158411/siyuan.log)

**Comment by Vanessa219** [comment]
这个光标表示选中数学公式，可以继续回车或者使用下键跳出
