### ISSUE TITLE
功能建议：可不可以在文件重命名时自动变更链接的摘要文字

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#549]
### 你在什么场景下需要该功能？

在 99% 的情况下，链接到一个文件时，该链接的摘要文字其实都是那个文件的文件名，这是前提。

当被链接的文件重命名时，尽管链接本身不会失效，但是链接的摘要文字不会变化。当一个文件重命名时，如果新名字在语义上有比较大的变动，我得手动去把每一个指向这个文件的链接的摘要文字给改了，当链接很多的时候，这一步非常费劲。

### 描述最优的解决方案

增加一个可手动开启的选项，当文件重命名时，把所有指向这个文件的链接的摘要文字也更新为新文件名。

「能自定义链接的摘要文字」这个特性在某些情况下可能是有用的，但我在绝大多数情况下并不需要自定义摘要文字，如果我很需要它，只能说明我的文件命名策略有很大问题。所以我的看法是，自定义摘要文字功能带来了一点小小的自由，但它实际上还带来了更大的不自由——我不敢轻易给文件重命名了。

**Comment by 88250** [comment]
你好，我们有个计划中的特性可以覆盖该使用场景，而且应该更灵活一些，请参考 https://github.com/siyuan-note/siyuan/issues/490

**Comment by deerainw** [comment]
@88250 

谢谢回复，等该特性正式发布之后我再来看看这个问题

**Comment by deerainw** [comment]
反向链接里的显示需要修一修：

![image](https://user-images.githubusercontent.com/32661922/101363237-1f0f7780-38dc-11eb-9c6f-f33690f09f46.png)

重命名的问题应该算是得到解决了。

另外，我忘了以前的版本是怎么样，现在如果用 `{{.title}}`，链接摘要文字是带路径的文件名，一般只要文件夹超过两级，带路径的链接摘要文字就会很长，感觉路径没必要带上，至少在链接里没必要。在嵌入的时候，因为嵌入一个块内容本来就很多，带上路径是没问题的。

**Comment by 88250** [comment]
`{{.title}}` 在 v0.5.3 里就不会带路径了，如果是指向文档的话只有文档名。反链显示后面修复，谢谢。
