### ISSUE TITLE
建议增加单向同步的功能

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#5496]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

同步功能感觉一直有问题，
假如我在a机器增加了内容，同步，
然后去b机器同步（结果可能会出现b上面旧的数据覆盖a上新增的数据

昨天晚上在家里在很久没用的mac上装了新版siyuan，然后导入密钥同步了下，今天回到公司发现一个很重要的文档被同步成老的版本了，还好能回滚，虽然也丢了昨天的数据。。。

前面也出现了好几次和我期望相反的覆盖的情况

总之就是现在的同步功能用着没有安全感，我不知道她到底会产生什么行为

### 描述可能的最优解决方案 Describe the optimal solution

建议增加单向同步的功能，比如提供两个按钮，明确我点她是用本地覆盖云端或者云端覆盖本地

**Comment by 88250** [comment]
可以使用云端标记快照功能实现，具体使用方式请参考用户指南 `云端-数据备份` 章节，谢谢。

**Comment by Zuoqiu-Yingyi** [comment]
> 可以使用云端标记快照功能实现，具体使用方式请参考用户指南 `云端-数据备份` 章节，谢谢。

快照功能不支持自动同步~

**Comment by Zuoqiu-Yingyi** [comment]
还有一个原因: 由于目前同步不再依靠时间戳, 导致用户对同步行为完全没有了预期, 进而无法感知覆盖行为的出现, 尤其是 `文档删除` 行为导致的覆盖

替代方案: 同步出现冲突时为用户提供手动处理冲突的选项, 或者明确告知哪些文档出现冲突

**Comment by 88250** [comment]
* `文档删除` 可能不存在冲突
* 单向同步的话还是需要手动操作，否则如果忘记下载的话依然有冲突情况
* 冲突的情况（编辑同一个文档）实际上可能很少发生

**Comment by mdzz2048** [comment]
支持增加单向同步功能。
当前同步方式对很多用户来说还是存在无法预期的情况，从而导致误操作。虽然可以通过本地快照等方式恢复数据，还是存在一定的使用负担。相比之下，给用户一个选择单向覆盖的操作，比看完帮助文档、理解云端同步机制再操作学习成本更低。

单向同步不一定是用来作为主要的同步方式，为的应该是在用户进行同步操作的时候有一个可预期的选择。就算用户阅读了帮助文档，也按照帮助文档操作了，可能还是会存在不符合预期的情况。当前的同步方式只能依赖于官方同步的同步算法，在出现这种不符合预期的情况时用户除了导入导出data似乎没有更好的选择，在没有选择的时候确实容易产生思源同步“不好用”的想法（手动标记快照上传到云端，再用云端快照覆盖似乎也可以，但是操作步骤相对较多，不如D大直接给一个单向覆盖的操作）
- 针对[多设备同步，部分设备为第一次同步](https://ld246.com/article/1660407986769/comment/1660728922018#comments:~:text=%E5%A6%82%E6%9E%9C%E6%95%B0%E6%8D%AE%E5%88%86%E6%95%A3,%E6%A1%A3%E8%87%AA%E5%8A%A8%E5%90%88%E5%B9%B6%E3%80%82) 的情况，如果增加单向同步可以避免通过数据快照找回，简化操作。
- 针对 [多设备同步存在旧文件夹](https://ld246.com/article/1659887169859/comment/1659892520424#comments:~:text=%E4%B8%A4%E4%B8%AA%E5%B9%B3%E5%8F%B0%E4%BD%BF%E7%94%A8%E6%89%80%E8%B0%93%E6%9C%80%E6%96%B0%E5%90%8C%E6%AD%A5%E6%9C%BA%E5%88%B6%EF%BC%8C%E5%B9%B6%E4%B8%8D%E8%83%BD%E5%90%8C%E6%AD%A5%EF%BC%8C%E4%BE%8B%E5%A6%82%E6%97%A7%E7%9A%84%E6%96%87%E4%BB%B6%E5%A4%B9%E4%BB%8D%E7%84%B6%E4%BF%9D%E5%AD%98) 的情况，如果增加单向同步也可以用某个设备上的数据直接覆盖，简化操作。

**Comment by Zuoqiu-Yingyi** [comment]
> * `文档删除` 可能不存在冲突
> * 单向同步的话还是需要手动操作，否则如果忘记下载的话依然有冲突情况
> * 冲突的情况（编辑同一个文档）实际上可能很少发生

- 但是看群里的消息, 因同步而丢失内容的情况是频发的, 如果不是冲突那么可能是其他 bug, 同步时提示哪些文档出现更改/覆盖/冲突有助于用户提前发现问题

**Comment by 88250** [comment]
@mdzz2048 增加单向上传、下载功能后不会简化问题，并且这个已经能通过标记快照上传、下载实现了，单独再给一个上传和下载的话同步功能用户会觉得更复杂吧。

@Zuoqiu-Yingyi 如果有 bug 我们得定位解决，但目前暂时没有发现。提示文档变更的话得像个好的交互方式，特别是有大量文件变更时。

**Comment by Zuoqiu-Yingyi** [comment]
> 



> @mdzz2048 增加单向上传、下载功能后不会简化问题，并且这个已经能通过标记快照上传、下载实现了，单独再给一个上传和下载的话同步功能用户会觉得更复杂吧。
> 
> @Zuoqiu-Yingyi 如果有 bug 我们得定位解决，但目前暂时没有发现。提示文档变更的话得像个好的交互方式，特别是有大量文件变更时。

那么先提示较少出现的冲突文档吧

**Comment by 88250** [comment]
得再想想交互，不然后面不好搞 😂
