### ISSUE TITLE
代码块移动光标 ↑ 跳过问题

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#5498]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

有一个标题与两个代码块：
<hr>

### 标题1

```bash
code1


```

```bash
code2
```

<hr>

可以用于复现的markdown如下：

````
### 标题1

```bash
code1

```

```bash
code2
```
````

### 问题

当指针初始位置在code1中时，按方向键的↓移动到第二个代码块，一切正常

但当指针从第二个代码块code2中，按方向键的↑，预期移动到第一个代码块时，指针却直接跳到了标题1处

**我觉得问题出在code1是以换行符结尾的，当把code1第二行删除时，此bug没有复现**

### 期待的结果 Expected result

指针正常跳转

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://github.com/wkmyws/issues_demo/blob/main/siyuannote%201.wmv

### 版本环境 Version environment

```markdown
- Version: v2.1.1
- Operating System: ubuntu docker
- Browser (if used): chrome
```

### 日志文件 Log file

null

**Comment by 88250** [comment]
我这里使用 v2.1.2 重现不了，请升级以后再试试。

![issue](https://user-images.githubusercontent.com/873584/180651533-7ee5211d-e2b9-4537-8990-83a5007dcbc6.gif)

**Comment by wkmyws** [comment]
https://github.com/wkmyws/issues_demo/blob/main/siyuan%20note%202.wmv

我想你这个`baz`是文章的大标题，你在大标题下面换行建立一个三级标题`### title`试试

如上面这个视频所示，当建立一个三级标题+代码块时，bug是会出现的，

而如果用大标题+代码块，就一切正常

**Comment by 88250** [comment]
没有重现哦

![issue](https://user-images.githubusercontent.com/873584/180652774-d7d0ae7e-a405-4db1-9b45-92f2c1ce37a5.gif)

**Comment by wkmyws** [comment]
那麻烦试下，把第一个代码块的第二行的”bar“字符删除，只保留换行符呢？

**Comment by 88250** [comment]
确实可以重现了，感谢感谢。

**Comment by wkmyws** [comment]
好的好的，作者辛苦了！
