### ISSUE TITLE
标签无法显示

### ISSUE THREAD

**Issue by AiProgram** [siyuan-note/siyuan#550]
### 描述问题 Describe the problem

标签功能失效了，无法显示已有的标签，而上一个版本还没有问题。
````````markdown
Analysis and application of modified ZNN design with robustness against harmonic noise

#ZNN# #鲁棒性#
````
Guo D, Li S, Stanimirović P S. Analysis and application of modified ZNN design with robustness against harmonic noise[J]. IEEE Transactions on Industrial Informatics, 2019, 16(7): 4627-4638.
````

DOI:`10.1109/TII.2019.2944517`
````````

### 期待的结果 Expected result

所有的标签能在侧边栏统一显示
### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/13717071/99866133-bb9dfe00-2be9-11eb-8d2b-5d4e53a5b930.png)

### 版本环境 Version environment

* 版本 Version： 0.4.8
* 操作系统 Operating system：Windows10专业版 2004
* 浏览器（如果使用）Browser (if used)：无

**Comment by AiProgram** [comment]
最新补充：重新安装0.4.7版本后问题解决，确认为新版本BUG
![image](https://user-images.githubusercontent.com/13717071/99866250-9d84cd80-2bea-11eb-9e1c-f1ea4e135553.png)

**Comment by 88250** [comment]
感谢反馈，v0.4.9 修复。
