### ISSUE TITLE
改进导入 Markdown 时 `<img>` 标签的处理

### ISSUE THREAD

**Issue by KuangJieRepository** [siyuan-note/siyuan#5501]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

md中图片如下：
![image](https://user-images.githubusercontent.com/59001444/180645037-4c28ad56-95b5-46b0-bc8b-b2f73a2d038e.png)

导入思源后：
![image](https://user-images.githubusercontent.com/59001444/180644861-20f1a204-d264-48c3-a2fa-3c4d12186a6e.png)

### 期待的结果 Expected result

---------------
希望能够解决下呀

### 版本环境 Version environment

```markdown
- Version: 2.1.1
- Operating System: Windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9175675/siyuan.log)

**Comment by 88250** [comment]
麻烦贴一下 Markdown 原文，或者上传 .md 文件。

**Comment by KuangJieRepository** [comment]
不太会搞这个上传文件，，，，，这个是文件地址：
  https://siyuan-1302559180.cos.ap-beijing.myqcloud.com/file/mysql/%E7%AC%AC09%E7%AB%A0_%E6%80%A7%E8%83%BD%E5%88%86%E6%9E%90%E5%B7%A5%E5%85%B7%E7%9A%84%E4%BD%BF%E7%94%A8.md

麻烦您了
