### ISSUE TITLE
挂件属性丢失

### ISSUE THREAD

**Issue by AloneFire** [siyuan-note/siyuan#5506]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

1. 在新建文档 创建挂件，挂件内通过接口`/api/attr/setBlockAttrs`设置属性，关闭文档再打开会偶现属性丢失
2. 文档内挂件通过接口设置完属性后，调整挂件大小会出现属性修改失效

### 期待的结果 Expected result

挂件属性设置实时生效且不会被丢失或覆盖

### 截屏或者录屏演示 Screenshot or screen recording presentation

![屏幕截图 2022-07-25 112315](https://user-images.githubusercontent.com/20330223/180703950-264252d4-bf09-449a-9725-3b94910d397e.png)
![屏幕截图 2022-07-25 112337](https://user-images.githubusercontent.com/20330223/180703958-412cd695-eb37-497e-8cb3-3e68dcbcd8b3.png)
![屏幕截图 2022-07-25 112401](https://user-images.githubusercontent.com/20330223/180703966-a892c305-b562-4d9c-ab0d-835ad593f368.png)
![屏幕截图 2022-07-25 112425](https://user-images.githubusercontent.com/20330223/180703971-93b8081b-07fb-492e-bc7e-e52cd45b6307.png)

### 版本环境 Version environment

```markdown
- Version: v2.1.2
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[Uploading siyuan.log…]()

**Comment by 88250** [comment]
感谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/4885
