### ISSUE TITLE
The right-click menu command similar to converting a network image to a local image

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#5507]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Hello! The right-click menu command similar to converting a network image to a local image does not have a corresponding shortcut key. . . Very troublesome. . .
Current version: 2.1.1
OS: Windows10

### 期待的结果 Expected result

Hello! The right-click menu command similar to converting a network image to a local image does not have a corresponding shortcut key. . . Very troublesome. . .
Current version: 2.1.1
OS: Windows10

### 版本环境 Version environment

```markdown
- Version: 2.1.1
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

Hello! The right-click menu command similar to converting a network image to a local image does not have a corresponding shortcut key. . . Very troublesome. . .
Current version: 2.1.1
OS: Windows10

**Comment by 88250** [comment]
Hello, this should not be a high-frequency function. If you need to use it frequently, please consider using the browser clipping extension.
