### ISSUE TITLE
网络代理支持用户名密码验证配置

### ISSUE THREAD

**Issue by danielbaggio** [siyuan-note/siyuan#5508]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

内网，必须使用带账号密码的HTTPS代理才能连接外网，现在的代理填写方式好像连不上去。

### 描述可能的最优解决方案 Describe the optimal solution

能否直接使用系统代理，或者在HTTPS代理那里增加填写账号和密码的选项？多谢！

**Comment by 88250** [comment]
Host/IP 这栏试下这样填写：`user:password@prox-server`
