### ISSUE TITLE
允许给一个笔记本的assets指定文件夹

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5514]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有个别笔记本需要在同事之间共享，文字对应的sy文件和文件夹还好处理，打包不难，但是assets没法打包，因为都在一个assets文件夹下面如果能支持为一个笔记本设置assets的文件夹路径就好了，默认可以都在assets，个别文件夹能自己定义。

### 描述可能的最优解决方案 Describe the optimal solution

提供笔记本属性：使用单独assets路径
在assets文件夹下面创建笔记本id文件夹，保存该笔记本对应的assets

### 描述候选的解决方案 Describe the candidate solution

或者对特定笔记本支持一个asset文件双处保存，也就是 assets 路径下沿用原来的不分笔记本方式，当某个笔记本需要导出时，提供菜单或API（更好），自动在assets文件夹下面对应“笔记本id”的文件夹中更新对应的assets文件。

**Comment by 88250** [comment]
楼上说得对，但是有副作用，具体请查看用户指南 - 通用操作 - 资源文件。
