### ISSUE TITLE
误识别带井号的文本为标签

### ISSUE THREAD

**Issue by alexcdever** [siyuan-note/siyuan#5517]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我发现我在添加标签的时候，会自动识别只带有一个井号的注释文本，如下：
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/14200813/180831520-7bdf05ad-6076-40ae-ba0a-fe8376bb7d27.png">
另外一个例子：
文中内容：
```sh
sh acme.sh  --issue -d www.xxx.com   --standalone #这里的-d后面接的就是你想要为其申请CA证书的域名
```
思源笔记会自动将上方的注释给加到标签里，像这样：
<img width="295" alt="image" src="https://user-images.githubusercontent.com/14200813/180830683-870e543e-709a-49c4-bdca-ba4ff2af390c.png">

### 期待的结果 Expected result

我希望对标签的识别可以更严格，跳过代码块内的井号

### 版本环境 Version environment

```markdown
- Version: v2.1.2
- Operating System: Intel版macOS 12.5
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9183200/siyuan.log)

**Comment by alexcdever** [comment]
补充一下，同时也会将标题识别为标签：
<img width="306" alt="image" src="https://user-images.githubusercontent.com/14200813/180835387-cdaf0917-ad55-40b6-9f48-211d53d66b1b.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/14200813/180835410-cc0fdd71-680f-424d-879a-2f2ce5d8d0b6.png">

**Comment by 88250** [comment]
`#` 之间的内容解析为标签应该是正常的，如果不需要的话请转义 `\#`。

**Comment by alexcdever** [comment]
代码块里的注释是`#注释文本`这样的，例如：
```yaml
a: 1 #变量a
b: 2 #变量b
```

```sh
rm rf /* #全盘删除
```
这样的话，**变量a**、**变量b**和**全盘删除**被识别为标签也正常吗？

还有就是标题，##a和###b这种二级标题和三级标题也会被识别为标签，这个也很奇怪吧？

**Comment by 88250** [comment]
我这里重现不了问题哦：

![image](https://user-images.githubusercontent.com/873584/180912117-b5ceea1f-d75e-48f6-a5f9-21144fa5d354.png)

标题的话还差个空格才是标题语法 `## a` 和 `### b`。

**Comment by alexcdever** [comment]
我找到问题所在了，是因为有一篇文章我用了Query挂件的时候，sql语句把内容也读取出来了，它的排版被压缩成一行，然后被井号包围的内容就被识别成标签了……我的锅
