### ISSUE TITLE
HTML 块选中部分内容无法复制

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#5521]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

HTML块选中部分使用`ctrl+v`复制没用，无法复制内容，只能使用HTML块菜单里的复制，复制整个HTML块的内容

### 期待的结果 Expected result

可以使用`ctrl+v`复制HTML块的内容

### 版本环境 Version environment

```markdown
- Version: 2.1.2
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

无异常信息

**Comment by 88250** [comment]
是 Ctrl+C 复制吗？

**Comment by UltramarineSky** [comment]
> 是 Ctrl+C 复制吗？

是的，昨天发的时没注意了，打成ctrl+v了

**Comment by 88250** [comment]
等发版后在帮忙测试看看，谢谢。
