### ISSUE TITLE
ECharts、PlantUML 和 Mermaid 等图表块报错

### ISSUE THREAD

**Issue by TonyW825** [siyuan-note/siyuan#5522]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

echarts 图表显示错误，返回 v2.1.2 恢复正常。

### 期待的结果 Expected result

echarts 正常显示。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/46043068/181194842-2e68d487-7542-4dda-867e-0118b15ca32c.png)

### 版本环境 Version environment

```markdown
- Version: 2.1.3
- Operating System: Win 11 / Android 10
- Browser (if used): -
```

### 日志文件 Log file

无异常

**Comment by jianxingyu** [comment]
一模一样的问题
