### ISSUE TITLE
数据仓库：主机A 和从机B 在确认秘钥正确的情况下依然无法同步

### ISSUE THREAD

**Issue by lvzhp** [siyuan-note/siyuan#5528]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我先关闭了主机A的数据同步，接着删除了数据仓库 ，然后重新设置 数据秘钥

然后在从机B中导入数据秘钥，开启同步。
此时从机报错 ![L9AG ZSG90X}G {C_(UMTLN](https://user-images.githubusercontent.com/71172482/181412501-12c35103-708b-4b08-bce9-629f161db6ec.png)
后续主机报错
![image](https://user-images.githubusercontent.com/71172482/181412007-b035edae-63f9-4481-8e3d-c16314ae0c85.png)

### 期待的结果 Expected result

Fix this 

### 版本环境 Version environment

```markdown
- Version: 2.1.3
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9205057/siyuan.log)

**Comment by 88250** [comment]
这是因为云端的数据已经用了旧密钥加密，本地重置数据仓库不影响云端已有数据。建议使用新的云端目录（最好不要删除再新建同名目录，而是直接新建不同名目录，旧的目录后面删除）。
