### ISSUE TITLE
切换文档时，编辑器区域出现抖动

### ISSUE THREAD

**Issue by gslnzfq** [siyuan-note/siyuan#5529]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

切换文档时，编辑器区域出现抖动

右侧的编辑器区域由宽变窄，出现抖动

### 期待的结果 Expected result

切换文档后，直接显示对应宽度的文档，不出现视觉上的变化；或者设置个开关，让用户可以关闭这个效果

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/12946062/181414921-e5dc79d4-f55a-4a04-b52a-4f4892d28082.mp4

### 版本环境 Version environment

```markdown
- Version: 2.1.3
- Operating System: macOS 12
- Browser (if used):
```

### 日志文件 Log file

null

**Comment by Vanessa219** [comment]
这个可以自定义 css
```
.protyle-wysiwyg {     transition: none; }
```
