### ISSUE TITLE
引用计数的气泡被侧边栏遮住了

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#553]
### 期待的结果 Expected result

气泡完整展现

### 截屏或录像 Screenshot or video

![图片](https://user-images.githubusercontent.com/28727933/99869762-7a691680-2c08-11eb-828d-cca4e6272ce7.png)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/99877807-ae116400-2c3b-11eb-976d-a61a91acd692.png)

这里调整一下。

**Comment by 2234839** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/873584/99877807-ae116400-2c3b-11eb-976d-a61a91acd692.png)
> 
> 这里调整一下。

我仍然觉得这算一个显示上的bug

**Comment by 88250** [comment]
嗯，稍后调整。
