### ISSUE TITLE
请问现在同步稳定吗？还有数据丢失风险不 我现在采取的同步方案是

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#5530]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我现在同步方案是这样的
1. 安装docker版 服务器上有整个data目录
2. 本地用的webdav直接加载成硬盘把本地的设置成了映射的硬盘目录
3. 其他电脑也这样 直接映射硬盘源

### 期待的结果 Expected result

这样是不是
1. 就没用到啥同步不同步 因为是网络磁盘映射
2. 多个端都是映射的一个目录
3. 所以哪个打开都应该是一摸一样 多端协作

但是手机端不行
1. 手机端不像obsidian那样是可以指定目录的
2. 所以我打算手机端还是用官方的云来同步吧

**你看我这个法子行吗？还存在不存在锁定 同步错误 数据损失的风险 数据还是蛮重要的**
**另外弱弱的问一句 现在的版本是全开源了吗**

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

```markdown
2.13
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by 88250** [comment]
目前来看新版数据仓库同步机制已经基本稳定，但是需要注意初始化配置，比如使用相同密钥以及多设备上有数据集的话需要注意合并结果，如果不符合预期可以用快照回滚。

思源笔记目前只有云端没有开源，本地端已经完全开源。
