### ISSUE TITLE
如何成为思源笔记的开发者

### ISSUE THREAD

**Issue by funbinary** [siyuan-note/siyuan#5536]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有没有关于开发者的资料，我对这个非常感兴趣

### 描述可能的最优解决方案 Describe the optimal solution

-

**Comment by 88250** [comment]
请看[这里](https://github.com/siyuan-note/siyuan/blob/master/.github/CONTRIBUTING_zh_CN.md)
