### ISSUE TITLE
macOS 端无法一次粘贴多张图片

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5537]
https://ld246.com/article/1659030742641

**Comment by Vanessa219** [comment]
无法重现

**Comment by HerrHuang** [comment]
> 无法重现

你好 V 大。我是从剪贴板复制的多张图片，思源只粘贴第一张。备忘录、微信聊天框、noton 都可以正确得到多张粘贴。
若直接从文件夹 command+c 再到思源粘贴是没有问题的。
另外是否能考虑一个改进：目前多张图片在思源中一次性粘贴是被归属到一个 block 中的，但是我们通常会做一些排版，就要手动在每张图片前加入回车修改为块，十分不方便。所以如果是每一张图片在粘贴时能各占一个块就会高效得多。
