### ISSUE TITLE
API `渲染模板` 文档描述

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#5538]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [x] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem
如题
https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E6%A8%A1%E6%9D%BF

### 期待的结果 Expected result

有

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/48077521/181771704-7fb85223-11ce-4174-a4b2-8fa4e8d1593f.png)

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/4676

**Comment by iamqiz** [comment]
这个api不错呦
