### ISSUE TITLE
有考虑过思维导图吗？思维导图可以切换大纲笔记 但大纲笔记并不一定是思维导图

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#5544]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我再写markdown的时候发现 比如空格阿 tab阿 它缩进的深浅其实不一的，
其次大纲笔记 是先要写大纲 然后一个一个填写点，但是它不好上下移动位置，
而且没思维导图那样更有全局性。思维导图全局性和发散性更方便创意

### 描述可能的最优解决方案 Describe the optimal solution

所以能否提议像幕布一样
1. 一边是编辑器支持markdown啥的
2. 另外也可以切换到思维导图进行编辑 两个可以切换来去的

**Comment by 88250** [comment]
暂时不考虑，感谢提议。
