### ISSUE TITLE
云端收集箱支持直接转发微信聊天记录

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5555]
需要先绑定公众号【B3log开源】然后再加思源小助手，可以实现聊天转发，支持文本、图片和超链接。

![)UVC9 VY0FO_E$}PV1EH {1](https://user-images.githubusercontent.com/873584/182516781-c1c54b64-327c-4d70-8d8f-fa8ba885bf28.jpg)

**Comment by woniuxia** [comment]
舒服了~

**Comment by Zuoqiu-Yingyi** [comment]
希望支持合并转发消息的解析❤

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 刚刚部署了，应该已经支持。

**Comment by JCJC01** [comment]
@88250 你好，
1.请问后期会支持视频或者文件的发送不？
2.请问会支持类似葫芦笔记那样把思源助手建群，然后就可以自动保存群的聊天记录不？这样可以作为重要群的聊天记录的被份。以便作为微信尚未支持聊天记录云备份的功能。这样对后期付费空间扩展的使用场景之一。
3.请问后期支持思源助手微信提醒功能。貌似提醒比此前的公众号提醒好，手机的微信有弹窗，公众号提醒没有弹窗，容易被忽略
4.请问能否后期通过特殊符号激活直接写入指定文档，例如#备忘，然后思源助手就会把录入的信息写入名字为备忘的文档。这样可以节省整理信息的步骤，不用先转出，复制，再选文档，再粘贴。做到真正助手的效果
，直接就更突出其中它作为收集及管理的功能

**Comment by JCJC01** [comment]
@88250 你好，
1.请问后期会支持视频或者文件的发送不？
2.请问会支持类似葫芦笔记那样把思源助手建群，然后就可以自动保存群的聊天记录不？这样可以作为重要群的聊天记录的被份。以便作为微信尚未支持聊天记录云备份的功能。这样对后期付费空间扩展的使用场景之一。
3.请问后期支持思源助手微信提醒功能。貌似提醒比此前的公众号提醒好，手机的微信有弹窗，公众号提醒没有弹窗，容易被忽略
4.请问能否后期通过特殊符号激活直接写入指定文档，例如#备忘，然后思源助手就会把录入的信息写入名字为备忘的文档。这样可以节省整理信息的步骤，不用先转出，复制，再选文档，再粘贴。做到真正助手的效果
，直接就更突出其中它作为收集及管理的功能

**Comment by 88250** [comment]
@JCJC01 你好，

1. 暂时不会支持
2. 暂时不会支持
3. 暂时没有找到微信接口能够推送消息
4. 收集箱的流程应该不会改变了，需要手动移动到笔记本中再整理
