### ISSUE TITLE
PDF 文件字体模糊

### ISSUE THREAD

**Issue by xeahsoon** [siyuan-note/siyuan#5556]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

桌面端开启深色模式下 PDF 字体飘忽不清，效果对比如下：
![image](https://user-images.githubusercontent.com/34468007/182108566-8fac64b3-e3bb-467b-b608-44d094e98f00.png)
---
![image](https://user-images.githubusercontent.com/34468007/182108661-c45bc23c-7ddf-4adb-aa55-5be8ee54a0f8.png)

### 期待的结果 Expected result

深色模式下字体依然清晰可见

### 版本环境 Version environment

```markdown
- Version: v2.1.4
- Operating System: None
- Browser (if used): Chrome
```

### 日志文件 Log file

None

**Comment by 88250** [comment]
这个问题目前无法处理，抱歉抱歉。
