### ISSUE TITLE
钉住的页签不能关闭，点击不显示内容，钉住功能也没了

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5560]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

不清楚是什么情况，还以为是自己订阅到期导致，一看订阅还没到期。
以前也遇到过钉住的页签，过了一段时间之后内容不再显示，但是至少还是能关闭的，现在都不能关闭了。

### 期待的结果 Expected result

钉住的页签能关闭，内容也应该正常显示。
钉住的功能菜单恢复。

### 版本环境 Version environment

```markdown
- Version: 2.1.2
- Operating System: Win10
- Browser (if used):
```

### 日志文件 Log file

I 2022/08/02 11:17:10 runtime.go:47: kernel is booting:
    * ver [2.1.2]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\Brain2, data 377 MB]
I 2022/08/02 11:17:10 serve.go:79: kernel is booting [http://127.0.0.1:6806]
I 2022/08/02 11:17:11 conf.go:527: database size [120 MB], block count [30956]
I 2022/08/02 11:17:11 working.go:143: kernel booted

**Comment by 88250** [comment]
试下升级到最新版，如果还不行的话再试下 设置 - 外观 - 重置。

**Comment by jabobian** [comment]
设置 - 外观 - 重置 可以，感谢D大。
