### ISSUE TITLE
建议新增模板管理模块

### ISSUE THREAD

**Issue by liun1221** [siyuan-note/siyuan#5561]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在模板使用中随着模板增多，有些模板废弃想删除，模板想归类

### 描述可能的最优解决方案 Describe the optimal solution

增加模板管理模块，支持本地模板的物理删除，模板分类等

**Comment by 88250** [comment]
暂时不考虑了，模板文件可以在桌面端文件系统上手动删除或者添加文件夹进行分类。

感谢提议。

**Comment by TCOTC** [comment]
关联：[可否考虑优化一下模版使用体验](https://ld246.com/article/1711966377606)

**Comment by TCOTC** [comment]
希望模板支持手动排序
