### ISSUE TITLE
PDF 支持展示所有标注

### ISSUE THREAD

**Issue by xeahsoon** [siyuan-note/siyuan#5563]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前 PDF 标注需要手动复制到文档内才可以查看，这样很容易被打断。往往阅读 PDF 的时候是一边阅读一边标记，之后再来统一整理过程中的标注内容。

### 描述可能的最优解决方案 Describe the optimal solution

希望能有像微信读书类似笔记的入口，点击后即可显示该文档中所有标注的内容。
![image](https://user-images.githubusercontent.com/34468007/182562877-b3dcdd21-e63e-457e-90c9-6b1196a88366.png)

**Comment by 88250** [comment]
感谢提议，目前的计划是通过挂件实现 https://github.com/siyuan-note/siyuan/issues/3082
