### ISSUE TITLE
CSDN 代码块剪藏会多出行号

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5564]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/56879067/182611476-85b4b99a-d6c9-499d-a457-3af00f120096.png)

### 期待的结果 Expected result

没有多出来的行号

### 版本环境 Version environment

```markdown
- Version: 2.1.5
- Operating System: win11 
- Browser (if used): edge
```

### 日志文件 Log file

不重要

**Comment by 88250** [comment]
请发一个测试用的网页地址，谢谢。

**Comment by heimi98** [comment]
> 请发一个测试用的网页地址，谢谢。

https://blog.csdn.net/weixin_42782150/article/details/106862236
