### ISSUE TITLE
assets目录增加子目录

### ISSUE THREAD

**Issue by meizilp** [siyuan-note/siyuan#5566]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

随着使用时间越来越长，assets目录的文件越来越多，通过链接打开文件时很乱。

### 描述可能的最优解决方案 Describe the optimal solution

参考现在常见的软件，每个月创建一个子目录

**Comment by 88250** [comment]
这个应该不会考虑，如果需要单独管理请参考用户指南资源文件章节。

**Comment by meizilp** [comment]
ok。笔记本自建assets也能解决一部分。
