### ISSUE TITLE
给小助手发链接，文章标题不对

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5567]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

给小助手发链接，收集箱中的文章标题为网址，而非文章本身的标题。

### 期待的结果 Expected result

文章标题为文章本身的标题。

### 版本环境 Version environment

```markdown
- Version: 2.1.3
- Operating System: win10
- Browser (if used): edge
```

### 日志文件 Log file

不重要

**Comment by 88250** [comment]
请发一下测试网址。

**Comment by heimi98** [comment]
> 请发一下测试网址。

https://zhuanlan.zhihu.com/p/66958390

**Comment by 88250** [comment]
直接发网址的话企业微信不会解析标题（但是公众号会），这个估计没法解决，先关闭了。
