### ISSUE TITLE
思源笔记需导入HTML、批量导入HTML；或者是导入mht、批量导入mht；望采纳！谢谢！

### ISSUE THREAD

**Issue by A15803** [siyuan-note/siyuan#5568]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

准备从为知笔记迁移到思源笔记，之前很多笔记（2K多个）只能导出HTML、mht、pdf格式，无法导入思源笔记，即无法被新的笔记引用，也无法建原笔记生成关系图，从而无法构建永恒的数字花园
望采纳！谢谢！

### 描述可能的最优解决方案 Describe the optimal solution

思源笔记可远程访问，本地使用时也有调试模式，应该是基于浏览器渲染的，浏览器也是可直接渲染HTML和mht；可创建一个目录放HTML，迁移时将原HTML的根目录直接复制过来即可完成迁移，遇到剪藏格式异常的笔记也可直接保存为HTML，从而保证格式正常
望采纳！谢谢！

**Comment by 88250** [comment]
思源仅支持导入 Markdown 格式的文件，请在外部自行转换（比如通过 Pandoc）。

**Comment by A15803** [comment]
我试了一下Pandoc转换后存在格式异常、图片丢失等，或者您这边有转换的手册没？不知道作者后续有支持html的计划没？

**Comment by 88250** [comment]
估计需要仔细看下 Pandoc 的文档，我也不确定是否能够按照预期完全转换。

没有支持 HTML 文件的计划。

**Comment by Chenm4** [comment]
现在计划的内置pandoc也是只在导出时支持使用pandoc吗？导入时不支持吗？感觉如果导入支持会更好点，比如我想看一本电子书但是这种一般都是epub格式，如果能直接转换为md格式就很好，省去自己再转换的步骤了，也更方便小白用户迁移数据

**Comment by 88250** [comment]
@Chenm4 后面可能会考虑
