### ISSUE TITLE
Android 端支持批量插入图片

### ISSUE THREAD

**Issue by FullOfWind-Sun** [siyuan-note/siyuan#5569]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在使用手机端时（需要将手机相册的图片传入笔记本），手机端不像PC客户端或者网页端、可以把图片批量拖入，手机端只能一张纸将图片插入

### 描述可能的最优解决方案 Describe the optimal solution

手机端 通过 “/插入图片”只能单选一张图片，无法批量选择并插入。

### 其他信息 Other information

期待开发者回复，感谢辛苦啦~

**Comment by JCJC01** [comment]
认同，而且感觉非常有需求。

**Comment by JCJC01** [comment]
期待，谢谢d大

**Comment by FullOfWind-Sun** [comment]
哇，处理神速！感谢开发团队，感谢D大！期待新版本
