### ISSUE TITLE
MAC版打开软件出现一直转圈的情况

### ISSUE THREAD

**Issue by chenli121120** [siyuan-note/siyuan#557]

**Comment by 88250** [comment]
你好，请问上次退出时是否是使用 Command Q？如果是的话请看下任务管理器里是否有 kernel-darwin 进程，有的话手动关闭一下。

**Comment by chenli121120** [comment]
问题解决了，网络的问题，但现在变成了网页上一直转圈了。。

**Comment by 88250** [comment]
你说的是思源在线工作空间吗？

**Comment by chenli121120** [comment]
对的，一直转圈没打开

**Comment by 88250** [comment]
在线工作空间目前只支持 Chrome，另外必须要从 https://ld246.com/xanadu/ 点击“开始使用”后进入。

后续我们会尽量改进浏览器支持，谢谢。
