### ISSUE TITLE
增加较为完整的任务功能（到期时间，提醒，状态，备注等）

### ISSUE THREAD

**Issue by tonyltl** [siyuan-note/siyuan#5571]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在“日计划”模板中，有任务列表，一行代表一个任务，打钩代表完成。
但是这样的任务不太满足要求，参考其他GTD软件，希望至少有到期时间，闹钟提醒，任务状态，备注说明等功能。

### 描述可能的最优解决方案 Describe the optimal solution

现在“日计划”模板中，有任务列表，一行代表一个任务，打钩代表完成。
但是这样的任务不太满足要求，参考其他GTD软件，希望至少有到期时间，闹钟提醒，任务状态，备注说明等功能。

**Comment by 88250** [comment]
这部分目前不考虑内置，可以通过属性扩展，感谢提议。
