### ISSUE TITLE
能否简化程序升级的步骤，特别是docker镜像

### ISSUE THREAD

**Issue by tonyltl** [siyuan-note/siyuan#5572]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

软件升级

### 描述可能的最优解决方案 Describe the optimal solution

我用的是群晖docker部署的思源笔记，每次升级要先备份文件，删除之前容器，更新镜像，再新建容器。
建议能否可以用一行命令，自动执行升级，避免手工多次操作。

**Comment by 88250** [comment]
建议了解一下 Docker 基础和相关命令，应该可以通过脚本做到自动更新。

**Comment by Zuoqiu-Yingyi** [comment]
docker 镜像自动升级请使用 watchtower

**Comment by tonyltl** [comment]
> docker 镜像自动升级请使用 watchtower

多谢，已经使用，很方便！
