### ISSUE TITLE
图片 裁剪功能 的使用需求

### ISSUE THREAD

**Issue by FullOfWind-Sun** [siyuan-note/siyuan#5573]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在使用笔记的过程中，可能有 对之前保存的图片 进行裁剪的需求。目前咱们现有的图片编辑功能为按比例缩放，无法裁剪掉 图片的多余部分。

### 描述可能的最优解决方案 Describe the optimal solution

裁剪 会涉及原图片保留与否、新图片覆盖与否 等问题。
个人感觉 可以增加一个覆盖提示，新图直接覆盖原图，不影响asset的链接地址。或者可以参照office的裁剪功能，裁剪仅改变图片在图片block内的显示区域，原图还是保留着，用户可以还原原图，或可随时调整裁剪区域。

### 其他信息 Other information

思源笔记 yyds，真的是每个人的永恒数字花园，哈哈哈

顺带提一句，还有个图片的文字识别功能，也算比较常用，后期可以考虑添加这个作为会员功能。

**Comment by 88250** [comment]
图片裁剪暂时不会考虑内置，请在外部使用其他工具处理，感谢提议。

**Comment by FullOfWind-Sun** [comment]
OK~谢谢回复
