### ISSUE TITLE
Would be great to support Vim in the future

### ISSUE THREAD

**Issue by johnny-liang-gd** [siyuan-note/siyuan#5578]
### In what scenarios do you need this feature?

This might be  a request from developer industry, which we'd like to especially navigate around the app mouse-free, more efficient

### Describe the optimal solution

Very often we'll be working while on the go, with very much limited space and equipment, only the built-in keyboard for the laptop to do everything

Basic Vim navigation would be just good enough for starter, maybe in the future could with more customizable config for keymap, currently almost all the shortcuts are for editing, and there's no extension for shortcut customization

**Comment by 88250** [comment]
Hello, VIM mode cannot be implemented at present. You can look at the existing shortcut keys, which should basically be able to achieve full keyboard operation, thanks.
