### ISSUE TITLE
列表中换行触发状态异常

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#5579]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

今日使用一开始都是正常的，过了一段时间再次使用突然发现列表一换行就报错
重建索引与强制退出都问题依旧，目前在我这里可以稳定复现

### 截屏或者录屏演示 Screenshot or screen recording presentation

![test3](https://user-images.githubusercontent.com/101307399/183013743-99a20775-bf55-4a06-965f-602b4970f4b8.gif)

### 版本环境 Version environment

```markdown
- Version: v2.0.15
- Operating System: Windows 10
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9265952/siyuan.log)

**Comment by 88250** [comment]
请将 .sy 打包发送至邮箱 845765@qq.com 谢谢

**Comment by Temacc0531** [comment]
已发送

**Comment by 88250** [comment]
已通过邮件沟通，这里关闭了，谢谢。
