### ISSUE TITLE
在 macOS Big Sur 上运行报错

### ISSUE THREAD

**Issue by PayneSnow** [siyuan-note/siyuan#558]
![截屏2020-11-22 10 37 51](https://user-images.githubusercontent.com/51922806/99892344-fddd4300-2cae-11eb-9835-14351a4897e2.png)

**Comment by 88250** [comment]
麻烦帖一下思源版本和操作系统环境，谢谢。

**Comment by PayneSnow** [comment]
![截屏2020-11-22 10 53 41](https://user-images.githubusercontent.com/51922806/99892566-fd45ac00-2cb0-11eb-9115-c583bef203ac.png)

**Comment by PayneSnow** [comment]
刚才是上一个版本，现在是刚刚安装最新的安装包，当前版本 v0.4.8。问题依然存在。

**Comment by PayneSnow** [comment]
可能是新系统的bug。我的另外一个应用打开后也出现了同样的提示

**Comment by 88250** [comment]
可能是思源用的 Electron 在新版 macOS 上有问题，估计需要等一段时间 Big Sur 正式发布后我们再升级 Electron 试试。

**Comment by PayneSnow** [comment]
已经正常了

**Comment by 88250** [comment]
哦，那我关闭了，谢谢反馈。
