### ISSUE TITLE
暗色主题下 `mindmap` 背景颜色设置为透明

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5582]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

`mindmap` 与 `echarts` 块使用 `canvas` 元素渲染, 但是该元素在暗色主题中设置了 `#100C2A` 背景颜色, 比较难看, 且无法使用主题样式覆盖, 希望 `canvas` 元素的背景颜色与明亮主题的一致, 设置为透明

### 描述可能的最优解决方案 Describe the optimal solution

`canvas` 元素暗色主题下的背景颜色与明亮主题的一致, 设置为透明

**Comment by Vanessa219** [comment]
mindmap 可以修改，但 echarts 由于是用户来设置，因此只能靠用户添加以下配置项。
```
{
    "backgroundColor": "transparent",
}
```

**Comment by Vanessa219** [comment]
mindmap 可以修改，但 echarts 由于是用户来设置，因此只能靠用户添加以下配置项。
```
{
    "backgroundColor": "transparent",
}
```
