### ISSUE TITLE
希望 Ctrl-I / Ctrl-B 后编辑格式能一直保持斜体或粗体

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5587]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如下 GIF 所示，目前当 Ctrl-I 后，当前单词的书写会变成斜体，但空格后，就自动恢复了普通格式。 Ctrl-B 的表现类似

![1](https://user-images.githubusercontent.com/7659710/183231211-59588ce9-5632-48e0-b978-704c3f39b223.gif)

希望空格后不要自动恢复格式，格式能保持直到重新 Ctrl-I 或 Ctrl-B，这也是文本编辑器的标准行为

### 描述可能的最优解决方案 Describe the optimal solution

如上

**Comment by 88250** [comment]
这里存在 Markdown 语法冲突，估计无法解决。

以 Markdown 加粗语法为例（`‸` 表示光标插入符）：

```markdown
**foo ‸**
```

结束标记符前存在空格的话就无法解析为加粗了，所以我们在这个细节上的处理是直接闭合标记符，并将光标插入符 `‸` 移动到空格后面：

```markdown
**foo** ‸
```

先关闭了，如果有好的方案欢迎讨论，谢谢。
