### ISSUE TITLE
Safari浏览器无法正常进入页面

### ISSUE THREAD

**Issue by kant-li** [siyuan-note/siyuan#5588]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

docker部署，safari访问网页，提示内核连接中断，持续在加载和错误提示之间循环；

### 期待的结果 Expected result

正常访问

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="438" alt="截屏2022-08-06 11 45 17" src="https://user-images.githubusercontent.com/10111857/183232459-bf07020b-79bd-4b34-b19a-4eb1e138f9c5.png">

### 版本环境 Version environment

```markdown
- Version: 2.1.5
- Operating System: macOS Monterey 12.3.1
- Browser (if used): Safari 15.4 (17613.1.17.1.13)
```

### 日志文件 Log file

log中无报错信息；
I 2022/08/06 11:39:47 runtime.go:47: kernel is booting:
    * ver [2.1.5]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuanworkspace, data 76 MB]
I 2022/08/06 11:39:47 serve.go:79: kernel is booting [http://0.0.0.0:6806]
I 2022/08/06 11:39:47 conf.go:527: database size [5.5 MB], block count [20021]
I 2022/08/06 11:39:47 working.go:147: kernel booted

**Comment by 88250** [comment]
Docker 部署的话应该是没有配置 WebSocket 反向代理，请参考用户指南配置。

**Comment by kant-li** [comment]
已配置，Chrome 和 Firefox 访问正常。
反向代理配置如下：
location / {
        proxy_pass http://127.0.0.1:6806;
        proxy_read_timeout 60s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
    }

    location /ws {
        proxy_pass http://127.0.0.1:6806;
        proxy_read_timeout 60s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
    }

**Comment by 88250** [comment]
请打开浏览器开发者工具看下 Console 和 Network

**Comment by kant-li** [comment]
Console 无报错；
1. 第一次加载 LsNoteBooks 和 twitter-emoji.js 异常：
<img width="1118" alt="截屏2022-08-06 12 13 40" src="https://user-images.githubusercontent.com/10111857/183233354-ce6d87f0-e5e9-4611-9cfc-48451d3b47f6.png">

2. 之后循环：twitter-emoji.js 和 setUILayout 异常：
<img width="1120" alt="截屏2022-08-06 12 14 09" src="https://user-images.githubusercontent.com/10111857/183233361-f0771006-dee7-47c6-8687-c25277c29524.png">

**Comment by 88250** [comment]
感觉像是网络相关的问题。

**Comment by 88250** [comment]
感觉像是网络相关的问题。
