### ISSUE TITLE
后端服务支持COROS预检请求验证

### ISSUE THREAD

**Issue by terwer** [siyuan-note/siyuan#5589]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前在Vite+Vue3的项目中使用fetch API调用siyuan的API时候，如果加上API鉴权，就会返回CORS错误，如下：
![](https://img1.terwergreen.com/api/public/20220806134238.png)

根据 https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request 这篇文章的理解

在检测到CORS跨域复杂请求（例如POST等）时候，会发送一个OPTIONS的预检请求，请求会返回下一个请求允许的header和method

检测请求可以看到

![](https://img1.terwergreen.com/api/public/20220806134552.png)

![](https://img1.terwergreen.com/api/public/20220806134634.png)

可以看到思源服务端返回的 Access-Control-Request-Headers 并没有 Authorization 字段。这就是导致最终CORS失败的根本原因。

### 描述可能的最优解决方案 Describe the optimal solution

查看 https://github.com/siyuan-note/siyuan/blob/master/kernel/server/serve.go) 代码可以看到，服务端是支持CORS的，代码如下

```go
ginServer.Use(cors.Default())
```

这里实用的默认策略。我们看看详细的默认策略

![](https://img1.terwergreen.com/api/public/20220806135023.png)

可以看到并没有包含 Authorization 字段。

而siyuan的API文档鉴权部分明确表示需要在header传递该字段

https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E9%89%B4%E6%9D%83

解决方案：
参考了
https://stackoverflow.com/questions/29418478/go-gin-framework-cors

代码修改如下

```go
func CORSMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {

		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Credentials", "true")
		c.Header("Access-Control-Allow-Headers", "origin, Content-Length, Content-Type, Authorization")
		c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	}
}
```

然后原来的 

```go
ginServer.Use(cors.Default())
```

调整为

```go
ginServer.Use(CORSMiddleware())
```

![](https://img1.terwergreen.com/api/public/20220806135531.png)

问题解决。

![](https://img1.terwergreen.com/api/public/20220806135619.png)

![](https://img1.terwergreen.com/api/public/20220806135641.png)

### 描述候选的解决方案 Describe the candidate solution

如果修改内核影响太大或者看看能不能把跨域策略提供配置可选。

**Comment by 88250** [comment]
目前来看应该没有多少影响，欢迎 PR。
