### ISSUE TITLE
支持一键将文档所有图片居中

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#5590]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在对网页内容进行剪藏之后，要进行重新排版。

### 描述可能的最优解决方案 Describe the optimal solution

图片居中是作为最常见的排版要求，所以可以作为默认操作。
或者增加一键居中文档图片的操作。

**Comment by 88250** [comment]
这个暂时不考虑了，等开放 API 以后等社区扩展，谢谢。
