### ISSUE TITLE
链接 open-graph 标题预览

### ISSUE THREAD

**Issue by wizyoung** [siyuan-note/siyuan#5592]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

粘贴链接的时候, 希望能实现 open-graph 协议的预览, 能快速知道链接的内容

### 描述可能的最优解决方案 Describe the optimal solution

类似 notion, craft, telegram 等 app 对链接的处理一样
对链接: https://softwareengineering.stackexchange.com/a/419847, 粘贴后自动显示如下

<img width="741" alt="image" src="https://user-images.githubusercontent.com/13296106/183243757-7d60664e-42c4-4441-adfa-6524c0ae00ef.png">

### 描述候选的解决方案 Describe the candidate solution

适用 open-graph 协议

**Comment by 88250** [comment]
卡片式超链接暂时不考虑，感谢提议。

**Comment by wizyoung** [comment]
能问下为什么不暂时考虑么, 我个人是觉得在记录一些技术性笔记添加大量参考链接的时候, 能解析这些链接对后面的二次审阅非常方便. open graph parser 我觉得第三方组件应该很多吧, 是否考虑添加下呢

**Comment by 88250** [comment]
已有待完成任务太多了，因为没有开发资源所以无法考虑部分需求，如果社区有开发者能够贡献的话非常欢迎。

**Comment by wizyoung** [comment]
好的, 感谢回复

**Comment by wizyoung** [comment]
前端开发能力有限, 暂时通过 alfred workflow 实现了简单的 og:title 自动解析然后替换链接锚文本的功能. (用到的 node js 包是 https://npm.io/package/open-graph)

https://ld246.com/article/1655622875831/comment/1660052594386?r=wizyangchen#comments

看社区反馈呼声似乎挺高, 还是希望作者或者其他第三方开发者有空时能实现下完整的卡片式超链接.
