### ISSUE TITLE
改进行级代码、键盘和标签元素边界编辑交互

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5595]
目前在代码左右边界上新增字符不会纳入代码。有两个方案可以考虑：

* Notion 方案：第一次编辑不纳入，Backspace 后再打字纳入
   
  ![issue](https://user-images.githubusercontent.com/873584/183272515-04501950-18e7-4da3-99f3-484cacafee32.gif)

* 语雀方案：使用零宽空格区隔

  ![issue](https://user-images.githubusercontent.com/873584/183272548-86fe8246-1651-4643-8e02-c3b72bebfa80.gif)

语雀的方案对用户更直观一些。

**Comment by yuyuyu-github** [comment]
语雀的确实更直观，顶

**Comment by woniuxia** [comment]
语雀 upupup~

**Comment by yuyuyu-github** [comment]
不光代码块吧， 其他凡是有格式的，变颜色，斜体呀，黑体呀，
只要在附近打字，输入法提示就会变色或者加粗，但是真正打出来的字却是正常格式
![image](https://user-images.githubusercontent.com/37429029/185771986-a5f2e0ec-18e5-470e-8cc0-e4c5dc5e4bdc.png)
![image](https://user-images.githubusercontent.com/37429029/185772038-3b676811-0b89-4f75-a0d3-fcad7fb8763a.png)

![image](https://user-images.githubusercontent.com/37429029/185772019-819a7d32-c8ba-4677-a938-8d7e76c5cef1.png)
![image](https://user-images.githubusercontent.com/37429029/185772034-eb689d74-d24c-4b38-9405-c2c3de0d395f.png)

**Comment by 88250** [comment]
这个改进有点困难，只能延后考虑了。

**Comment by 88250** [comment]
在 #2911 中我们改进了大部分行级元素的编辑交互，行级代码通过 Markdown 编辑有两种方式：

* 通过 `` ` `` 进行闭合标记符后再写代码内容，然后通过 Ctrl+G 跳出
* 通过 `` ` `` 起始标记符后写代码内容，然后通过 `` ` `` 闭合后就可以继续写非代码内容

[issue.webm](https://user-images.githubusercontent.com/873584/190857899-f810c186-1d68-4914-b784-b913aef92a32.webm)

当然，更方便的方式是直接通过 Ctrl+G 快捷键切换行级代码和普通文本。

边界上暂时不改变了，后续如果还有需求我们再考虑。

**Comment by Temacc0531** [comment]
感觉现阶段（v2.2.1）的行级元素边界比以前有很大改进，但当`输完闭合符号退格`或是`从后往前输闭合符号`后都只能使用快捷键才能跳出，但大部分用户还是习惯`←``→`键跳入跳出，如果始终有元素边界应该会好很多，比较符合直觉
![test6](https://user-images.githubusercontent.com/101307399/192236125-b1733a76-078d-4289-ab6e-898308ecdefa.gif)

**Comment by 88250** [comment]
@Temacc0531 左右键跳出应该不是大部分用户的习惯吧。

**Comment by Temacc0531** [comment]
用左右键应该是要比快捷键来的多的😂，因为不同元素使用的快捷键还不太一样，左右键的话直观所有元素都通用。其实重点应该不是用什么键的问题，是如何保持元素边界的操作直观统一，按现在的有些边界不使用快捷键也可以自由进出，有些又只能使用快捷键才能跳出，许多用户都误以为是遇到了bug，如果有了类似语雀的边界后会直观很多

**Comment by woniuxia** [comment]
@Temacc0531 老哥，去社区提个投票吧

**Comment by 88250** [comment]
大家应该都比较习惯类似语雀的处理方式，我们在考虑看下 https://ld246.com/article/1664451020956

**Comment by iamqiz** [comment]
> @Temacc0531 左右键跳出应该不是大部分用户的习惯吧。

![Snipaste_2022-10-01_13-42-46](https://user-images.githubusercontent.com/48077521/193394553-f49c4069-3516-4185-b9b8-9decfc664b6b.png)

左右键跳出是最自然的跳出方式,也应该是最基本的跳出方式了, 
如果能在这个基础上增加 Tab键/enter键跳出, 那就更好了 
,用组合键ctrl+G 应该是最麻烦的一种方法了
建议D大开个投票, 不出意外,左右方向键跳出方式应该完胜

**Comment by yuyuyu-github** [comment]
现在每次打一个标签块，或者行内代码块，后面输入的文本也跟着改样式了，只能用组合快捷键主动断开，这点超级打断我现在的笔记。 让我现在都只敢在文字全部码完以后再进行样式修改。

标签和代码块，本身就是对特性的文字进行标注的，标签还有重复使用的特点。

比如我 #问题   这个标签，我会重复打标签，而且标签的文本 就是固定的这两个字。
或者 对一段行内代码 ctl+G，后面输入的中文肯定不在行内代码的范围里。

但是现在，我 #问题  后面打上“xxxxxxx” ，这些文字也会跟着变成标签了。原来一个快捷键就可以增添样式，现在需要两个快捷键，增添样式，再主动中断样式。

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 上标与下标元素的边界也应支持使用左右方向键控制光标跳入/跳出

**Comment by yuyuyu-github** [comment]
> @Vanessa219 上标与下标元素的边界也应支持使用左右方向键控制光标跳入/跳出

附议

**Comment by Vanessa219** [comment]
这个和粗体一类就不跳出了。

**Comment by Zuoqiu-Yingyi** [comment]
> 这个和粗体一类就不跳出了。

粗体这些跳出前后没法分辨, 但是上下标可以呀~

**Comment by Temacc0531** [comment]
我也感觉上下标应该可以支持边界跳出，要不然分界处修改起来非常麻烦

**Comment by Achuan-2** [comment]
> 我也觉得上下标应该支持边界跳出，要不然分界处修改起来非常麻烦

+1，上下标的样式是很明显的，也应该做跳出

**Comment by TCOTC** [comment]
确实
