### ISSUE TITLE
尝试为arm64 linux编译内核的问题

### ISSUE THREAD

**Issue by kero990** [siyuan-note/siyuan#5596]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我尝试为一台国产机器编译此项目，electron部分是直接移植了resources文件夹，在没有内核支持的时候，electron部分能够运行，正常提示内核缺失。我用交叉编译了arm64的内核，内核在终端也能正常单独运行。但组合两者的适合，界面闪退。终端运行electron时报错xdg-settings: unknown desktop environment
当然这是个uos系统，也就是dde桌面，我不知道和这个桌面系统有没有关系，也不知道问题出在electron部分，还是内核部分。

很抱歉在支持外的情况打扰您，我想知道我该怎么进行下一步，能让这个程序可以在arm64 linux环境下运行。毕竟electron和go都是跨平台非常友好的。

### 期待的结果 Expected result

希望能在arm64 linux ，麒麟或者统信正常运行。毕竟是electron+go

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file
stat.go:38: query database version failed: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
 database.go:93: create table [stat] failed: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
但是我是交叉编译的，似乎不能使用CGO_ENABLED=1。

**Comment by 88250** [comment]
内核交叉编译应该没有问题，可以单独启动验证。从日志来看，需要启用 CGO 编译 SQLite，这个也支持交叉编译的，不同平台需要安装对应的 C 编译器，这部分可以参考 https://github.com/mattn/go-sqlite3

先关闭了，有问题请继续跟帖。

**Comment by red-co** [comment]
你好，请问解决方法是什么?
上下文: "我直接按照文档编译了 kernel.exe", "直接运行，显示 : “08 stat.go:38: query database version failed: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub”，
这意味着我需要以 “CGO_ENABLED=1” 编译 go-sqilte 吗? （或者，解决方法是什么?)
docker是解决方法吗?

**Comment by 88250** [comment]
参考我之前发的 go-sqlite3，上面有编译方法。

用 docker 也可以的，但是有部分功能不支持，具体可参考用户指南 Docker 伺服 章节
