### ISSUE TITLE
剪藏 SVG 公式丢失

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5598]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

剪藏一些公众号文章，文章中的公式会丢失。
文章链接：https://mp.weixin.qq.com/s?__biz=MzU0NjgzMDIxMQ==&mid=2247579406&idx=5&sn=0da15e076be89b3f8a822abd16ae8aef&chksm=fb5455e2cc23dcf4b753e5d20c35415ef62712c04bf9ce4f77f7cb678b65bddf0f7a5c3c955b&mpshare=1&scene=1&srcid=1227LZbGxZxEJLpWtkP4hAGk&sharer_sharetime=1640571185956&sharer_shareid=f456ad9cb0e21adbd322636a80e09af6#rd

### 期待的结果 Expected result

能剪藏公式

### 版本环境 Version environment

```markdown
- Version: 2.1.3
- Operating System: win10
- Browser (if used): edge
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
这问题有点复杂，暂时没有解决方案，先关闭了，感谢反馈。

**Comment by Godsing** [comment]
一个名为“[简悦](http://ksria.com/simpread/)”的 Chrome 插件，在导出为 markdown 时，对于某些格式为 svg 的 latex 公式，可以识别成功。例如这样的页面：https://zhuanlan.zhihu.com/p/35423404。可供参考。
