### ISSUE TITLE
The browser extension supports Zhihu formula

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5599]
知乎公式剪藏失败

### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

知乎公式剪藏失败，如下图：
![image](https://user-images.githubusercontent.com/56879067/183288918-3a31c56c-c520-45b4-9c65-0bf18931ad76.png)
原文链接：https://zhuanlan.zhihu.com/p/35423404

### 期待的结果 Expected result

公式剪藏正常

### 版本环境 Version environment

```markdown
- Version: 2.1.3
- Operating System: win10
- Browser (if used): edge
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5598
