### ISSUE TITLE
提及支持显示更多

### ISSUE THREAD

**Issue by svchord** [siyuan-note/siyuan#5604]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

1. 反链面板，点击【显示更多】
2. 反链面板能正常显示更多内容，但提及面板不能

### 期待的结果 Expected result

提及面板也能显示更多

### 版本环境 Version environment

```markdown
- Version: 2.1.5
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9279780/siyuan.log)

**Comment by 88250** [comment]
已有的反链和提及暂时不会添加改进了（只修复缺陷），后续请关注：

* https://github.com/siyuan-note/siyuan/issues/3565
* https://github.com/siyuan-note/siyuan/issues/4814
