### ISSUE TITLE
为链接新增转化为文本选项，删除选项修改为删除链接

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#5608]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

超链接的删除是只删除链接，保留锚文本
而块引用的删除是整个删除引用，不保留锚文本
会造成混乱

### 期待的结果 Expected result

个人是希望块引用的删除也转化为普通文本（虽然块引用中的转化已经有转化为文本的功能了）
因为多数情况下，是不会直接把块引用删除的，或者就算有需求也是习惯鼠标选择按backspace

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/60436214/183536754-9a50f8db-9be1-4ded-883f-d7c78f7acb6c.png)

### 版本环境 Version environment

```markdown
- Version: 2.1.5
- Operating System: Win11
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by aptexd** [comment]
终于有老哥提了这个，懒人表示感谢
