### ISSUE TITLE
图片居中后刷新页面会有一个换行

### ISSUE THREAD

**Issue by GuangDai** [siyuan-note/siyuan#5613]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

图片居中后刷新页面会有一个换行，试过换主题

可能和解析的时候有关。

看了之前的问题，那个问题是“居中操作后会有一个软换行” 可以看我下面的视频，居中操作后是没有的，但刷新或者重新打开就会出现这个换行

![image](https://user-images.githubusercontent.com/59678726/184069135-93eb2ce3-9030-41c6-bb31-489efecc7c6d.png)

2.1.6 ArchLinux Appimage

### 期待的结果 Expected result

即使刷新后也没换行

### 截屏或者录屏演示 Screenshot or screen recording presentation

[2022-08-11 13-24-41.zip](https://github.com/siyuan-note/siyuan/files/9306282/2022-08-11.13-24-41.zip)

### 版本环境 Version environment

```markdown
- Version: 2.1.6
- Operating System: ArchLinux
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9306294/siyuan.log)

**Comment by GuangDai** [comment]
可能和自动添加一个可输入的位置有关，（仅仅是猜测），因为图片居中后，那个段落块后面应该是有个输入的位置

对比一下：

1. 这个是将整个块设置为居中，此时刷新不会有换行

![image](https://user-images.githubusercontent.com/59678726/184154437-41845151-3e5b-4056-aa32-b3864b846820.png)

2. 这个是把图片设置为居中，此时就会有一个换行的

![image](https://user-images.githubusercontent.com/59678726/184154682-095a8147-1ba4-4da0-ba06-8befddbb8cf4.png)

然后BS删除 会把图片删除

![image](https://user-images.githubusercontent.com/59678726/184154800-b06bd2c5-8b39-4041-9cc6-e622bfd6f54e.png)

3. 这个是把图片和块都设置为居中，可以看见输入位置也居中

![image](https://user-images.githubusercontent.com/59678726/184155043-c44bc61a-5e67-498d-ac74-2d85ee8543c6.png)

**Comment by GuangDai** [comment]
那么其实解决办法就是，让图片居中的情况和1情况类似就行了，让文字的输入位置在图片的右边，不过不知道siyuan是如何设置图片居中的，可能改动不是那么容易

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/5626 中修复，感谢反馈。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/5626 中修复，感谢反馈。
