### ISSUE TITLE
无法正常退出

### ISSUE THREAD

**Issue by Tukali** [siyuan-note/siyuan#5620]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

最新的2.1.6版本，在mac m1上，无法正常退出，点击x退出和思源菜单的退出按钮都没有反应，其他功能正常，只能强制退出

### 期待的结果 Expected result

能够正常退出思源

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
2.1.6

macos m1   ventura 13.0
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9313296/siyuan.log)

**Comment by 88250** [comment]
Duplicate of #5615
