### ISSUE TITLE
分页处块标错位

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#5623]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

页面滚动分页处出现块标错位情况，应该是所有类型的块都有这个问题

### 期待的结果 Expected result

块标始终与块对齐

### 截屏或者录屏演示 Screenshot or screen recording presentation

![test4](https://user-images.githubusercontent.com/101307399/184312205-caeb5a9d-1122-4a71-9761-8191704b33b1.gif)

### 版本环境 Version environment

```markdown
- Version: v2.1.6
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
你说的是块滚动上去后块标没有对其么？

<img width="319" alt="image" src="https://user-images.githubusercontent.com/970828/184501674-ea80530f-872b-40ec-9ac4-750f69ec052c.png">

**Comment by Temacc0531** [comment]
就是块在分页处的时候，上一个块的块标会错位显示到下一个块上。看上面的图里第一处完整显示测试的块的块标位置其实是有两个块标的，其中一个是上一个块的

**Comment by Vanessa219** [comment]
块标有一个最高显示高度，超过这个高度就会在该位置显示。现在有点过低了，我改高一点下个版本你再看看。

**Comment by Temacc0531** [comment]
![test5](https://user-images.githubusercontent.com/101307399/184811714-8019cb03-384b-49fe-b82f-ec2cf854a414.gif)

我看修复完之后有所改善，但还是对不齐，也许可以把块标边界提高到面包屑下边界，超过之后则不再显示

**Comment by Vanessa219** [comment]
目前最大高度就是在面包屑下面了，再上就会遮挡到面包屑。不显示的话会不会还要增加用户的一个小小的滚动？

**Comment by Temacc0531** [comment]
那就是如果块标已经到面包屑里面重叠的话直接就不显示了，这样就是相当于是不在显示区域内，对用户来说也是预期情况内

**Comment by Temacc0531** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
但是块内容还显示在编辑区域中，因此块标还是需要显示的。

**Comment by Temacc0531** [comment]
飞书：
![飞书](https://user-images.githubusercontent.com/101307399/185656005-0a874fb0-7925-4347-b307-499064947241.png)
息流：
![息流](https://user-images.githubusercontent.com/101307399/185656014-ccf309b4-80c9-47f1-b13d-4061e64e967d.png)
思源：
![思源](https://user-images.githubusercontent.com/101307399/185656020-91997553-dae1-4e6c-8c04-bad21c6f8a4f.png)

这几个都是第二个块的块标，只有思源的错位了

![思源2](https://user-images.githubusercontent.com/101307399/185659194-c3a3b701-26e7-4a4f-a0f8-0d0f6fe145db.png)

把显示边界提高到红线位置就应该是正确的，目前的是在红线下面一些

**Comment by Vanessa219** [comment]
位置时刚好在红线下的，空白的是整个按钮的边距。这样用户会比较好点击。

**Comment by Temacc0531** [comment]
我明白了，那这个可以等后续需要优化块标的时候一块解决了 #4877
