### ISSUE TITLE
The browser extension supports CSDN formula

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5624]
CSDN 公式剪藏问题

### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

CSDN 公式剪藏问题
![image](https://user-images.githubusercontent.com/56879067/184321096-048a6ed7-9293-41af-8762-4b6384dad92f.png)
原文地址：https://blog.csdn.net/anshuai_aw1/article/details/88750673

### 期待的结果 Expected result

公式正常显示

### 版本环境 Version environment

```markdown
- Version: 2.1.6
- Operating System: win10
- Browser (if used): edge
```

### 日志文件 Log file

略

**Comment by EternalHXP** [comment]
问题是 csdn的公式有多种格式, 我再使用简悦 阅读模式时也出现这种问题
- 希望支持 KaTeX 方案 · Issue #4276 · Kenshin/simpread - https://github.com/Kenshin/simpread/issues/4276

**Comment by 88250** [comment]
无法支持公式剪藏，见谅。

**Comment by TCOTC** [comment]
@88250 如果剪藏的网页有公式的话，是否应该忽略行级公式语法的设置？

![image](https://github.com/siyuan-note/siyuan/assets/78434827/da48fde8-f52c-43a9-b710-a5d88060226b)

**Comment by 88250** [comment]
稍后改进看看。
