### ISSUE TITLE
关系图搜索框存在内容时不收缩隐藏

### ISSUE THREAD

**Issue by Febtw** [siyuan-note/siyuan#5628]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

1、在关系图中没有嵌入块的连线，但是逻辑上讲嵌入块应该是引用块的进阶，嵌入内容自然是希望与原文产生关联

2、在“关系图”、“反向链接”、“提及”这几处的搜索框是自动收缩的，但是即使切换文档或者重开文档，这些地方的搜索内容也不会被清除，这会导致默认搜索结果被筛选过了我却没注意
![image](https://user-images.githubusercontent.com/96163355/184469638-06a81e3b-9a29-44de-bfc7-fe7aa1b9e6e9.png)

### 期待的结果 Expected result

1、在关系图中把嵌入块的连线也显示出来，同时在文档树以及被嵌入的内容块上也对嵌入次数进行计数（或与引用次数合并计数）

2、“关系图”、“反向链接”、“提及”这几处的搜索框，在有输入内容时不进行自动收缩

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/96163355/184469638-06a81e3b-9a29-44de-bfc7-fe7aa1b9e6e9.png)

### 版本环境 Version environment

```markdown
- Version: v2.1.5
- Operating System: docker
- Browser (if used): Microsoft Edge 104.0.1293.54
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9330896/siyuan.log)

**Comment by 88250** [comment]
1. 思源中的嵌入块是查询嵌入块，所以没有记录引用关系
2. 搜索框的问题确实存在，这个应该会改进

感谢反馈。

**Comment by Febtw** [comment]
感谢回复，请问嵌入块可以记录引用关系吗，否则我只能在添加嵌入块时再添加一条引用块

**Comment by 88250** [comment]
@Febtw 嵌入块无法记录引用关系。

**Comment by Febtw** [comment]
好吧，感谢

**Comment by Febtw** [comment]
> 1. 思源中的嵌入块是查询嵌入块，所以没有记录引用关系
> 2. 搜索框的问题确实存在，这个应该会改进
> 
> 感谢反馈。

感谢更新
v2.1.7 Windows 端上“反向链接”和“提及”两处地方搜索框有内容时不自动收缩了；“关系图”/“全局关系图”上面的搜索框还是不能保持扩展

**Comment by Vanessa219** [comment]
下个版本改进。
