### ISSUE TITLE
闪屏

### ISSUE THREAD

**Issue by CH00CMJ** [siyuan-note/siyuan#5629]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

打开软件时会闪屏，无法进入主界面

### 期待的结果 Expected result

希望解决问题

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/109736641/184494103-af334c33-01f7-4a3b-8e8d-1054d9f3f2cb.mp4

### 版本环境 Version environment

```markdown
- Version: 最新版本
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9331413/siyuan.log)

**Comment by 88250** [comment]
试下任务管理器中结束 SiYuan Kernel 进程后重启。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by CH00CMJ** [comment]
重启之后进入还是一样

**Comment by CH00CMJ** [comment]
在闪屏前我重新设置了工作空间的路径，之前是好的

**Comment by 88250** [comment]
麻烦再发一下日志文件。
