### ISSUE TITLE
请输入特性提议标题 Please enter the title of the feature request

### ISSUE THREAD

**Issue by xjt2016** [siyuan-note/siyuan#5631]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前使用的是docker部署，希望可以单个文档，或者目录支持下导出文档pdf格式

### 描述可能的最优解决方案 Describe the optimal solution

暂无

### 描述候选的解决方案 Describe the candidate solution

暂无

**Comment by 88250** [comment]
你好，这个无法支持，仅支持桌面端导出 PDF。

**Comment by 88250** [comment]
你好，这个无法支持，仅支持桌面端导出 PDF。
