### ISSUE TITLE
目前无法注册，提示：密码格式有误（数字及字母组合，长度 6-16）

### ISSUE THREAD

**Issue by yltrcc** [siyuan-note/siyuan#5634]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

目前无法注册，提示：密码格式有误（数字及字母组合，长度 6-16）

我输入的密码是：zKEv95uO4kAfoV

### 期待的结果 Expected result

成功注册！！！

### 版本环境 Version environment

```markdown
- Version: 最新版
- Operating System: win11
- Browser (if used):Chrome
```

### 日志文件 Log file

wu

**Comment by 88250** [comment]
请试下将密码长度减少到 8 位左右看看。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by yltrcc** [comment]
> 请试下将密码长度减少到 8 位左右看看。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

"userPassword":"104a64de753c548753515524300fc531","userId":"1660487925128","referral":""}:  我输入的密码
{"msg":"注册失败 - 用户名仅允许使用数字或字母，最大长度 20"}

**Comment by 88250** [comment]
用户名不支持中文哦。
