### ISSUE TITLE
PDF 页签支持键盘滚动

### ISSUE THREAD

**Issue by Febtw** [siyuan-note/siyuan#5635]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

虽然在快捷键设置中没有，但是我发现桌面版上思源可以用Ctrl+Tab来切换页签。
不过由于没有设置选项，这个切换在浏览器上被浏览器自身占用了。
但即便是在桌面版，从笔记文档切换到pdf文档后，pdf页签上也还是不能用键盘进行翻页操作，甚至用鼠标也是要移到该pdf页签上才能滚轮翻页。

### 期待的结果 Expected result

思源的分屏功能用来边阅读边做笔记很方便，但阅读离不开频繁翻页动作，若需要频繁切换鼠标键盘的话，就削弱了这个便捷性。
所以希望切换到pdf页签后，能够用键盘翻页；同时也希望提供设置切换页签的快捷键选项，使浏览器端也能操作。

一个更激进的想法是，当双屏分屏时，当前分屏照常用 <kbd>Page Up</kbd> <kbd>Page Down</kbd> <kbd>↑</kbd> <kbd>↓</kbd> 来翻页和滚动，另一分屏省去切换步骤，直接附加 <kbd>Shift</kbd>/<kbd>Ctrl</kbd>/<kbd>Alt</kbd> 来翻页滚动（这甚至可以适用更多分屏）

### 版本环境 Version environment

```markdown
- Version: v2.1.5
- Operating System: Windows 10
- Browser (if used): Microsoft Edge 104.0.1293.54
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9332855/siyuan.log)

**Comment by 88250** [comment]
分屏附加快捷键滚动暂时不考虑了，感谢提议。

我们先记录 PDF 页签支持键盘滚动。

**Comment by 88250** [comment]
你好，我在 v2.1.7 Windows 端上测试可以通过 ↑ ↓ 和 PgUp PgDn 滚动翻页的。

页签切换可以通过 Ctrl+Tab 进行。
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Febtw** [comment]
可能我没有表述清楚。
Windows 端上通过 Ctrl+Tab 进行页签切换是可以；直接打开pdf文档，然后通过 ↑ ↓ 和 PgUp PgDn 滚动翻页，也是可以的。
但是通过 Ctrl+Tab 切换到pdf页签，它就不能用 ↑ ↓ 和 PgUp PgDn 滚动翻页了。
v2.17上还是有这样的问题

**Comment by 88250** [comment]
这是个 bug，请关注 https://github.com/siyuan-note/siyuan/issues/5655
