### ISSUE TITLE
改进没有模板时 `/模板` 的交互

### ISSUE THREAD

**Issue by Godsing** [siyuan-note/siyuan#5636]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

输入斜杠"/"并点击"模板"后，无反应。
查看控制台，看到如下 warning ⚠️：（每次输入斜杠"/"并点击"模板"，就会新增一条相同的 warning）
```
fetch post error TypeError: Cannot read properties of null (reading 'forEach')
    at main.fd9d4f134e610e43b7f5.js:1:746054
    at main.fd9d4f134e610e43b7f5.js:1:1035713
（匿名） @ main.fd9d4f134e610e43b7f5.js:1
Promise.catch（异步）
t.fetchPost @ main.fd9d4f134e610e43b7f5.js:1
showTpl @ main.fd9d4f134e610e43b7f5.js:1
fill @ main.fd9d4f134e610e43b7f5.js:1
select @ main.fd9d4f134e610e43b7f5.js:1
（匿名） @ main.fd9d4f134e610e43b7f5.js:1
```

### 期待的结果 Expected result

展示模板库供选择

### 版本环境 Version environment

```markdown
- Version: 2.1.6
- Operating System: macOS 12.2
- Browser (if used): Not used
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9333439/siyuan.log)

**Comment by 88250** [comment]
我这里重现不了问题，请重建索引以后再试试看。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Godsing** [comment]
发现原因了：是因为我没有下载任何模板，所以点击模板时无反应，随便下载一个模板后就可以使用了。
顺便提个小建议哈：当用户点击模板时，如果没有已下载的模板，可以给用户一个提示，比如“请到「设置->集市->模板」中先下载模板！”，否则像我这种第一次使用思源笔记的用户，折腾好几天，试了3台电脑(mac, mac-m1, windows)，debugger都报相同的错，才意识到“模板可能需要手动下载，而不是安装软件就有的！”(꒦_꒦)

**Comment by 88250** [comment]
收到，谢谢。
