### ISSUE TITLE
note 的 replicate 功能

### ISSUE THREAD

**Issue by Yubuxin** [siyuan-note/siyuan#5640]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

思源的文档结构是树状的，而树状结构用久了都很容易出现分类的问题，比如我有「美学」和「形而上学」两个笔记本，「柏拉图」这篇笔记既可以放进「美学」，也可以放进「形而上学」，但在目前的思源中只能选择其中一个来放置。

### 描述可能的最优解决方案 Describe the optimal solution

希望能像 Zotero 或者 devonthink 那样有一个 replicate 的功能，一篇笔记可以 replicate 至另一个笔记本或另一篇父文档，并且可以在其中正常编辑。

**Comment by 88250** [comment]
可以考虑使用 MoC 方式通过引用管理。
