### ISSUE TITLE
代码块中当\" 后面输入tab引发的bug

### ISSUE THREAD

**Issue by liun1221** [siyuan-note/siyuan#5645]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在代码块中任意行输入\"，在其后任意行，输入tab，会导致后续输入自动换行，每行只有一个字符

### 期待的结果 Expected result

修复bug

### 截屏或者录屏演示 Screenshot or screen recording presentation

![bug演示](https://user-images.githubusercontent.com/65383735/184613018-e5be2947-045d-4e21-bc8e-ce1874caa1ff.gif)

### 版本环境 Version environment

```markdown
- Version: 2.1.6
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
我这里重现不了问题哦。

![issue](https://user-images.githubusercontent.com/873584/184613751-b7199fd2-b80e-45f2-9bdf-f5fe2bd0e5b6.gif)

**Comment by liun1221** [comment]
客户端版本会有这个问题，\"后输入tab异常，浏览器正常

**Comment by 88250** [comment]
之前演示的就是桌面端。

**Comment by liun1221** [comment]
![bug演示](https://user-images.githubusercontent.com/65383735/184615662-909de970-0095-437a-91e8-c2659c48d5e9.gif)
输入新字符会有问题，中文正常，我还发现当驶入中文句号后，在输入新字符会在\"中间插入

**Comment by 88250** [comment]
搜狗输入法是最新版吗？或者切换到其他输入法试试。

**Comment by 88250** [comment]
我觉得可能是中文输入法相关的问题，试下不使用输入法，在 En 状态下能否重现。

**Comment by liun1221** [comment]
最开始是没用输入法的，是同样会有这个问题，后来输入中文才切的输入法，群里另一个人win11也是这个问题，我晚上回去在复现试试

**Comment by liun1221** [comment]
我想的是你是不是设置tab自动换空格，我设置自动换空格就没这个问题了

**Comment by 88250** [comment]
没有设置：

![image](https://user-images.githubusercontent.com/873584/184659073-a0215744-0a4b-4077-ab80-aafe4c46851c.png)

**Comment by liun1221** [comment]
我今天又试了一下，再次复现了第一种情况
![bug演示](https://user-images.githubusercontent.com/65383735/184763362-a4e5cc30-d76e-4854-a638-f49693ceedfa.gif)

**Comment by liun1221** [comment]
我多次尝试，发现代码块设置js、ts、java、json这些语言会有这种问题，其他的像html、css就正常

**Comment by 88250** [comment]
我这里重现不了呃，之前录屏用的就是 javascript。

暂时先关闭了，后面其他人如果有类似反馈我们会关联到这里，谢谢。

**Comment by liun1221** [comment]
好的，他人如果有类似情况再说，我更新到最新版还是有这个问题，win7系统和win11都可复现，附上.sy
[bug测试.sy.zip](https://github.com/siyuan-note/siyuan/files/9347707/bug.sy.zip)

**Comment by 88250** [comment]
嗯，我用这个 .sy 测试也还是不行，只能后续留意了，谢谢。
