### ISSUE TITLE
拖拉反向链接折叠状态文本块到正文区能否包含子文本块

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#5652]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

例：反向链接H2 下有 H3, p. 不管H2是否折叠都只会把H2拉到正文，留下H3,p

建议折叠状态下全部拉入，体验同分屏区间互相拖拉

### 描述可能的最优解决方案 Describe the optimal solution

同上

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/3565 中考虑，感谢反馈。
