### ISSUE TITLE
请求添加 Font icon 图标字体支持

### ISSUE THREAD

**Issue by ListenV** [siyuan-note/siyuan#5654]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

可以极大地丰富文章图标及文章内容

Font Awesome 图标字体示例：http://www.fontawesome.com.cn/

以下是我来的效果图：
![image](https://user-images.githubusercontent.com/45219522/184933148-5ce65d4e-bc55-4130-a5f7-22bdc4d48eaf.png)

![image](https://user-images.githubusercontent.com/45219522/184933037-ea01376f-7be9-43f7-b06f-5ac0ae7188f0.png)

### 描述可能的最优解决方案 Describe the optimal solution

可以用二级字体来实现，比如：

1. 用户自定义的字体优先级最高
2. 如果用户的字体中没有 Font icon 图标字体，那就采用思源给出的Font icon字体

思源也是前端那些，实现起来应该不难

**Comment by 88250** [comment]
目前暂时不考虑引入特性了，如果后续还有类似需求我们再考虑，感谢提议。
