### ISSUE TITLE
希望可以增加对代码块中部分进行高亮，划线，加粗，改变字体颜色，添加链接，批注等操作，或提供对应可开发插件的接口tle of the feature request

### ISSUE THREAD

**Issue by fantasyoung** [siyuan-note/siyuan#5662]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在进行技术文章撰写和阅读时，文章内涉及的代码可能会比较多，需要同时看上下文变量，函数名等不够醒目，需要对代码块进行一些标注和链接时。或需要对某些关键代码逻辑进行醒目的标注时(使用场景如同在正文中需要进行加粗高亮和改变颜色的内容一样，只是在代码块中无法进行这些操作)

### 描述可能的最优解决方案 Describe the optimal solution

如notion，wolai对于代码块中内容高亮，标注，链接等实现
![image](https://user-images.githubusercontent.com/22661474/185031744-69eaa7b6-50bd-44c3-8658-2605f9425655.png)

**Comment by 88250** [comment]
代码块内容无法支持，感谢提议。
