### ISSUE TITLE
可以对单篇文章内进行搜索并直接高亮所有要搜索的内容

### ISSUE THREAD

**Issue by fantasyoung** [siyuan-note/siyuan#5663]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

需要参考上下文关于某些关键字已经编写过的位置，或对于代码块中的内容需要快速找到相关变量(函数)的逻辑时。
当前的搜索对于代码块中的内容很不友好，一大坨代码块中的内容可能包含很多个某变量的名字，在搜索时无法高亮无法快速找到要搜索的位置

### 描述可能的最优解决方案 Describe the optimal solution

大多数笔记软件都提供该搜索方式，如为知笔记，notion，trilium等
![image](https://user-images.githubusercontent.com/22661474/185032811-e527a51e-3f92-43ad-9c37-dc4a83e90181.png)

**Comment by 88250** [comment]
不考虑页内搜索了，感谢提议。
