### ISSUE TITLE
home路径下创建 ~/.config/siyuan 失败，报告无写入权限？

### ISSUE THREAD

**Issue by Tback1** [siyuan-note/siyuan#5668]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

安装在 c:\Program Files\SiYuan\ 下 作为全局可用
 
![image](https://user-images.githubusercontent.com/8872546/185204975-6da45915-ea0d-440b-a714-f2944b8b0034.png)

事实上这个文件夹程序本身创建成功了，属性也没有只读。系统里卡在这一步，也没有log或别的进一步生成。
试过将该文件夹软链接修改到其他路径，也毫无效果。
![image](https://user-images.githubusercontent.com/8872546/185205318-d83ea851-3433-4954-a337-c0cc815a80dc.png)

### 期待的结果 Expected result

正常启动

### 版本环境 Version environment

```markdown
- Version: 2.1.7
- Operating System: Windows 10 LTSC 2021 (21h2 内部版本号 190441889)
- Browser (if used):
```

### 日志文件 Log file

无法提供该文件。

**Comment by 88250** [comment]
试试删了这个文件夹重新启动。

**Comment by 88250** [comment]
另外，有可能是 .config 文件夹权限的问题。建议试下用当前用户安装，不要为所有用户安装。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Tback1** [comment]
> 试试删了这个文件夹重新启动.

在卸载前,我甚至尝试了以管理员权限运行思源笔记.问题依旧

下一步,测试重新安装
首先
1. 将安装目录重新安装到了当前用户 位于 c:\Users\Username\AppData\Local\Programs\SiYuan\ 下
2. 清理删除了 c:\Users\<username>\.config\siyuan\ 目录
3. 删除以下目录
> c:\Users\<username>\AppData\Local\siyuan\
> c:\Users\<username>\AppData\Local\siyuan-updater\
> c:\Users\<username>\AppData\Roaming\siyuan\
4. 运行思源笔记,问题依旧
5. 运行后 \.config\siyuan 自动创建成功，但软件依旧报错 提示没有写入权限。（能否有个参数指定一下启动后的配置文件保存地址??）
6. 
![image](https://user-images.githubusercontent.com/8872546/185684716-42abab8f-bb93-4ec5-bfdd-f61b2f56f55a.png)

**Comment by 88250** [comment]
再试下删除 ~/.config/siyuan/ 文件夹后在 cmd 下用命令行直接拉起内核进程：

```
D:\思源安装路径\app\kernel\SiYuan-Kernel.exe --wd=D:\思源安装路径\app
```
