### ISSUE TITLE
块引锚文本不包含链接地址

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5672]
https://ld246.com/article/1660647944161

**Comment by CnsMaple** [comment]
刚刚, 将这篇文章的问题实现了一下

https://user-images.githubusercontent.com/92523839/185408088-dee2ff10-7a0a-4147-bf7f-1349c2f6a1ae.mp4

**Comment by 88250** [comment]
尝试了一下，这个问题目前没有解决方案，估计只能使用静态锚文本了。
