### ISSUE TITLE
图表类内容块编辑框钉住改进

### ISSUE THREAD

**Issue by CnsMaple** [siyuan-note/siyuan#5675]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

看演示视频演示

### 期待的结果 Expected result

功能恢复正常

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/92523839/185417562-fb18994c-55e9-4714-81f2-1e0dd77f6897.mp4

### 版本环境 Version environment

```markdown
- Version: 2.1.7
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
- [ ] 图标钉住失效
- [ ] 图标为空时无操作按钮
- [ ] 图标编辑框双击可以切换钉住状态
