### ISSUE TITLE
希望网页界面含有关闭自身标签页的功能按钮或快捷键

### ISSUE THREAD

**Issue by lingr7** [siyuan-note/siyuan#5677]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

点击链接查看QQ频道帖子【思源笔记pc端界面白屏，浏览器访问可用？如何单独启动内核服务？】：https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&appChannel=share&inviteCode=1W9EmUw&contentID=1eBnv&businessType=2&shareSource=5
QQ

在使用浏览器的且全屏模式浏览该网页的情况下，点击面包屑菜单，很容易触发鼠标移动到屏幕顶端提示退出全屏的关闭按钮。
在chrome浏览器中，有一种 kiosk 模式，可以去除鼠标移动到顶端触发的退出全屏按钮。

关于 Google Chrome 中的全屏模式和 APP 模式
https://www.cnblogs.com/abel/p/3235839.html

### 描述可能的最优解决方案 Describe the optimal solution

使用ctrl w关闭浏览器标签页的快捷键确实无法关闭该网页，会关掉打开的文档页面，不会关掉网页本身，我的核心需求是一种方便的方案去关闭这个标签页或者浏览器，快捷键也可以，或者思源笔记软件之外的方案也可以。

**Comment by 88250** [comment]
设置 - 快捷键 中将关闭页签快捷键改为其他的，这样就可以使用 Ctrl+W 来关闭浏览器页签了。
