### ISSUE TITLE
集市支持已安装的包单独显示

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#5678]
### 1. 优化集市已下载资源展示
在「集市」下载了许多主题、图标、挂件等，但因为是第三方作者制作与维护，所以有时集市内容更新也无从提示，需要自己时不时上「集市」里去看看，自己所用集市资源有无更新。
基于该场景，我认为可以让使用者打开「集市」时，看到归纳在一处的「已下载」资源，可以更方便的进行更行、卸载等操作。
### 2. 优化集市下载（更新）主题的体验
下载好的主题会自动替换，并把设置栏关掉（更换主题的时候也会），但我也有“感觉这个主题不错的样子，下载看看这个主题大致设计怎么样，然后换回去”这一需求，虽然这个场景并不多见，但偶尔学习、工作累了，确实会在主题里看看大佬们的作品设计如何、为何如此设计等休闲浏览等行为。

### 1. 集市已下载资源管理体验优化方案
（1）. 将使用者已下载的集市资源归纳至一处，设置在集市最上方（也可另开一个选项栏展示），让需要管理集市已下载内容的用户可以一目了然的查看、管理。
（2）. 最好不设分类，「主题」、「模板」、「图标」、「挂件」等统合一起，只展示所有已下载的「集市资源」。当然也可以设计分类展示，但从效率上来讲，大部分用户应该不会把所有集市资源都下载下来，而是选择性下载喜欢的集市资源使用，所以从这一点上来说，下载的集市资源并没有多到必须要分类展示的需求，而为了管理（更新、卸载）集市资源，将用户已下载的所有集市资源进行集中展示，更便于其更新或卸载。
（3）. 设置一键更新所有集市内已下载并且可更新的资源。
（4）. 集市内已下载或正使用的集市资源发布更新时，思源笔记进行提醒。
### 2. 集市下载（更新）主题的体验优化方案
（1）. 下载好主题后不自动切换
（2）. 切换主题后不关闭设置栏

### 其他信息 Other information

逛「集市」时想到的两个点，索性就在issue里发出来了，至于D大V姐采用与否，取决于他们，个人看来这个issue并不是优先级很高或一定要优化的需求，只是可以进一步提升使用体验的需求罢了。

**Comment by EberhardLin** [comment]
> ### 在什么情况下你需要该特性？In what scenarios do you need this feature?
> ### 1. 优化集市已下载资源展示
> 在「集市」下载了许多主题、图标、挂件等，但因为是第三方作者制作与维护，所以有时集市内容更新也无从提示，需要自己时不时上「集市」里去看看，自己所用集市资源有无更新。 基于该场景，我认为可以让使用者打开「集市」时，看到归纳在一处的「已下载」资源，可以更方便的进行更行、卸载等操作。
> 
> ### 2. 优化集市下载（更新）主题的体验
> 下载好的主题会自动替换，并把设置栏关掉（更换主题的时候也会），但我也有“感觉这个主题不错的样子，下载看看这个主题大致设计怎么样，然后换回去”这一需求，虽然这个场景并不多见，但偶尔学习、工作累了，确实会在主题里看看大佬们的作品设计如何、为何如此设计等休闲浏览等行为。
> 
> ### 描述可能的最优解决方案 Describe the optimal solution
> ### 1. 集市已下载资源管理体验优化方案
> （1）. 将使用者已下载的集市资源归纳至一处，设置在集市最上方（也可另开一个选项栏展示），让需要管理集市已下载内容的用户可以一目了然的查看、管理。 （2）. 最好不设分类，「主题」、「模板」、「图标」、「挂件」等统合一起，只展示所有已下载的「集市资源」。当然也可以设计分类展示，但从效率上来讲，大部分用户应该不会把所有集市资源都下载下来，而是选择性下载喜欢的集市资源使用，所以从这一点上来说，下载的集市资源并没有多到必须要分类展示的需求，而为了管理（更新、卸载）集市资源，将用户已下载的所有集市资源进行集中展示，更便于其更新或卸载。 （3）. 设置一键更新所有集市内已下载并且可更行的资源。 （4）. 集市内已下载或正使用的集市资源发布更新是，思源笔记进行提醒。
> 
> ### 2. 集市下载（更新）主题的体验优化方案
> （1）.下载好主题后不自动切换 （2）. 切换主题后不关闭设置栏
> 
> ### 描述候选的解决方案 Describe the candidate solution
> _No response_
> 
> ### 其他信息 Other information
> 逛「集市」时想到的两个点，索性就在issue里发出来了，至于D大V姐采用与否，取决于他们，个人看来这个issue并不是优先级很高或一定要优化的需求，只是可以进一步提升使用体验的需求罢了。

**Comment by 88250** [comment]
第二点暂时无法支持，因为有的主题增加了自定义 js，如果不切换刷新整体界面的话会有问题。

**Comment by woniuxia** [comment]
@88250 D大，当前使用人数好统计吗？或者最近七天使用人数，想要一个当前使用人数的排序，比历史下载量更有说服力。

**Comment by 88250** [comment]
@woniuxia 不太好统计……

**Comment by EberhardLin** [comment]
在这里提个新需求，能在集市中展示一个作者所作的所有主题吗？

**Comment by 88250** [comment]
> 在这里提个新需求，能在集市中展示一个作者所作的所有主题吗？

这个先不考虑了吧。

**Comment by 88250** [comment]
对了，issue 正文中提到的已安装包的展现方案我们不考虑分离，还是在原页签上加个过滤，也就是单独这个类型包的过滤，不新增“已安装包”的页签。另外，批量更新也不考虑支持了，这个有点危险，更新前最好还是由用户逐个确认。

**Comment by EberhardLin** [comment]
> 对了，issue 正文中提到的已安装包的展现方案我们不考虑分离，还是在原页签上加个过滤，也就是单独这个类型包的过滤，不新增“已安装包”的页签。另外，批量更新也不考虑支持了，这个有点危险，更新前最好还是由用户逐个确认。

理解，没事按你们的想法来。

**Comment by 88250** [comment]
呃，考虑了一下，还是加个新页签“已安装”的比较好……
