### ISSUE TITLE
内容块 URL 定位

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#568]
https://ld246.com/article/1606120848979

**Comment by Tokubara** [comment]
看到加入了定位功能, 就更新了, 但是我这里还是不能定位, 用浏览器打开还是在文档开始处.

**Comment by 88250** [comment]
@Tokubara 
![image](https://user-images.githubusercontent.com/873584/100745880-e1fa3f80-341a-11eb-99df-b8fed74c96c2.png)

**Comment by Tokubara** [comment]
好的. 不过我试了一下, 新创建了文档, 文档名从来没有用过. 对内容块打开url, 发现是这样
<img width="255" alt="image" src="https://user-images.githubusercontent.com/32409331/100749088-24258000-341f-11eb-854f-6a8beee78109.png">
重启软件, 再打开url, 还是这样.

我可能阅读理解有问题. 关于第二段, 我打开的并不是之前的url, 就是打开刚复制的url, 打不开.

 不过我试了很多个块, 还是有能够定位的.

**Comment by Tokubara** [comment]
不过过了一会儿, 我发现又行了, 对于新的文档不会出现上述情况, 能正确打开和定位.
对于旧文档的旧块很可能不能定位.
对于旧文档的新块, 也不能定位.

**Comment by 88250** [comment]
要保持 ID，也就是说 sy.md 里面每个块都需要有 id 标识才行，请继续观察一下，谢谢。

**Comment by Tokubara** [comment]
非常不好意思, 我真的不知道怎么才能让它work, 我也搞不懂. 我也不好描述. 我这样问:
1. 如果是在设置为块id持久化之前创建的文档, 无论新旧的块, 是不是一定不能正确定位? 如果这样的话, 我把它的内容复制粘贴到一个新文件, 逻辑上讲能不能work?
2. 如果是在设置为块id持久化之后创建的文档, 新创建的块, 是不是短时间内是不能正确定位的? 是需要时间么?

**Comment by 88250** [comment]
1. 如果在开启持久化 ID 之前已经用了块 ID URL，那这个 URL 最多只能定位到文档，定位不到具体的块 ID，现在复制粘贴也不行了，因为那个 ID 已经丢失了，复制粘贴会生成新的 ID
2. 新的块应该是即时生效的，持久化 ID 的作用是为了下次重启时能够从 .sy.md 文本中还原 ID 到内存中，以实现块 ID 不变，这样 URL 就能够继续使用

**Comment by Tokubara** [comment]
这样的话, 为啥复制粘贴不行?
> 复制粘贴会生成新的 ID

这样的话, 我用**复制粘贴后得到的块的url**来访问**复制粘贴后的块**, 而不是用旧的url, 应该可以吧?

**Comment by 88250** [comment]
可以的。

**Comment by Tokubara** [comment]
好像是这样的. 但还是希望能改善这一块的体验, 因为这个意义重大呀, 这意味着外部应用的访问(至于为啥会需要外部应用的访问呢, 比如间隔复习这样, 还有marginnote可以引用笔记).
目前有这些问题, 我不知道跟浏览器有没有关系, 我用的火狐.
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/32409331/101245518-68c75900-3748-11eb-994a-7e9373e6debc.png">
打开链接, 右边空白了一块. 虽然可以通过关闭所有tabs, 然后再打开文件, 处理这个问题. 但打开url又会出现同样的问题.
而且定位也不准确.  其实目标块应该在这个图的下方看不见的位置.

**Comment by Tokubara** [comment]
外链极其有用啊, git提交都可以引用一下笔记中的debug的过程. 如果没有外部应用, 那么笔记实际上只是个人知识或者创作的收纳箱. 而链接创造各种可能性

**Comment by 88250** [comment]
是的，这是内容块 URL 的意义，不然也不会做这个功能……

目前浏览器只支持 Chrome，其他浏览器没有做兼容处理。

**Comment by Tokubara** [comment]
我也装了chrome, 但是chrome打开也是一样的..

**Comment by 88250** [comment]
现在还是定位不了吗？

**Comment by Tokubara** [comment]
不不, 并不是定位不了, 定位不了的情况是: 打开是文件的开头. 现在是能定位的. 是显示的问题.
它能正确定位, 但是显示在浏览器上, 如果前面有多幅图片, 它会显示在前面图片那个位置, 而不是指向的内容块位置.
往下滑能看到它确实是定位在了内容块的位置(因为泛着蓝光嘛).
还有就是右边有一大片空白.就如前面的图展示的.

**Comment by 88250** [comment]
右边空白的问题应该是 UI 缺陷，关闭文档后重开估计就好了，或者重置一下 UI，这个问题 v0.5.2 里面进行了一次修复，等发布以后再帮忙留意观察。

定位的问题我还是不太理解你的意思，图片如果和文本在一个内容块的话，定位是最开始的地方，这应该没有问题。
