### ISSUE TITLE
`file://` 协议兼容 Window 平台使用 `/` 作为目录分割线

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5681]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

点击超链接 `[链接](file://C:/Sync/OneDrive/桌面/MouseWithoutBorders/)` 时会弹出如下错误提示框:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/49649786/185630814-3b8dbe00-bdea-400a-99a4-1836e2026d73.png">
而点击超链接 `[链接](file://C:\Sync\OneDrive\桌面\MouseWithoutBorders\)` 时则可以正常打开对应目录

window 系统实际上兼容 `/` 作为目录分割线

### 期待的结果 Expected result

超链接 `[链接](file://C:/Sync/OneDrive/桌面/MouseWithoutBorders/)` 与 `[链接](file://C:\Sync\OneDrive\桌面\MouseWithoutBorders\)` 等效

### 版本环境 Version environment

```markdown
- Version: v1.2.6
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

此外, 目前该版本也不兼容 `[链接](file:///C:/Sync/OneDrive/桌面/MouseWithoutBorders/)` 与 `[链接](file://\C:\Sync\OneDrive\桌面\MouseWithoutBorders\)`, `file://` 后的第一个 `/` 或 `\` 表示文件系统根目录

**Comment by Achuan-2** [comment]
点个赞，这样我用CopyQ快速获得file协议链接，就能不用修改也能插入思源了
