### ISSUE TITLE
云端同步发生冲突时生成副本

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5687]
云端同步发生冲突时单向的覆盖会让用户困惑（无论是云端覆盖本地还是本地覆盖云端），即使是让用户选择也不太稳，因为用户可能会选错。

改进为生成冲突副本，这样可以让用户更方便地处理冲突数据：直接在笔记本中就能看到或者用搜索找到冲突文档，然后编辑合并或者删除。

**Comment by HowcanoeWang** [comment]
建议参考Github的版本对比，提供一个冲突差异显示的界面

**Comment by 88250** [comment]
@HowcanoeWang 目前编辑器没有可视化 diff 的方案哦。
