### ISSUE TITLE
在文档中，新建子文档时，标题错误

### ISSUE THREAD

**Issue by Javier-Huang** [siyuan-note/siyuan#5688]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在文档中，新建子文档，然后在子文档中输入了标题，之后返回上一级文档，标题确实是我输入的内容。但是，
退出siyuan之后，重新打开文档，发现标题已经不正确了。如图：
![2022-08-21_11-15](https://user-images.githubusercontent.com/88572822/185773834-87a24f66-4f44-4ec7-bdb6-f8be78f0ac97.png)

这个问题在v2.0.18没有出现过，我升级之后发现的问题，而且当我安装回v2.0.18时，已经打不开了，报错：
![2022-08-21_11-20](https://user-images.githubusercontent.com/88572822/185773873-d594710c-97b1-46e5-a048-45b28a6210e0.png)

### 期待的结果 Expected result

期望能得到解决，或者能安装会旧版本

### 版本环境 Version environment

```markdown
- Version: v2.1.4
- Operating System: x86 Deepin Linux
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log.zip](https://github.com/siyuan-note/siyuan/files/9388365/siyuan.log.zip)

**Comment by Javier-Huang** [comment]
补充：已验证过最新版本v2.1.7，问题依然存在

**Comment by 88250** [comment]
日志中暂时没有发现问题，试试重建索引。

**Comment by Javier-Huang** [comment]
试过重建索引， 没有效果

**Comment by 88250** [comment]
试一下修改定义文档名，看下引用块是否会跟着变动，另外，请确认使用的是动态锚文本而不是静态锚文本。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Javier-Huang** [comment]
已经用回旧版本v2.0.19了，不折腾了，稳定为主

**Comment by 88250** [comment]
@zhongtao1hao 建议用最新版本试试。

**Comment by zhongtao1hao** [comment]
试了下，好像解决了，感谢 ！
