### ISSUE TITLE
linux应用程序列表和dock上没有应用图标

### ISSUE THREAD

**Issue by miaoerwu** [siyuan-note/siyuan#5692]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

linux应用程序列表和dock上没有应用图标

### 期待的结果 Expected result

linux应用程序列表和dock上，以及其他可以展示应用图标的位置显示应用图标

### 截屏或者录屏演示 Screenshot or screen recording presentation
应用列表：![截图 2022-08-22 10-08-08](https://user-images.githubusercontent.com/14366467/185824987-7e0bcc3b-c01e-4798-9003-f839f8bf6ef3.png)
dock：![截图 2022-08-22 10-08-27](https://user-images.githubusercontent.com/14366467/185824992-41b11d24-008e-4ab0-aafb-8a1023192e6d.png)

### 版本环境 Version environment

```markdown
- Version: 2.1.7
- Operating System: pop!_os 22.04
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9390642/siyuan.log)

### 更多信息 More information

**Comment by 88250** [comment]
应该是因为没有支持该发行版的桌面系统，这个暂时无法排查解决，抱歉抱歉。

**Comment by miaoerwu** [comment]
> 应该是因为没有支持该发行版的桌面系统，这个暂时无法排查解决，抱歉抱歉。

请问ubuntu支持到了么？这个系统是基于ubuntu的，绝大部分情况，ubunt是好的，这个系统个就是好的

**Comment by 88250** [comment]
支持的。

**Comment by miaoerwu** [comment]
> 支持的。

ubuntu上不会有缺少图标的情况么？appimage格式是与发行版无关的，理论上应该不会有问题。而且，如果是在ubuntu上没有问题的情况下，在这种基于ubuntu的系统上，出现问题的概率更低。我还是希望如果条件允许的话，您可以在百忙之中抽一点点时间看下这个问题。不过这个问题倒是没什么大的影响，应用还是可以正常使用的，只是图标是个缺省值的图标

**Comment by 88250** [comment]
抱歉了，我这边实在没有时间看，你可以试下根据源码构建调试看看。

**Comment by miaoerwu** [comment]
好的，多谢:smiley:
