### ISSUE TITLE
建议更换上下标为html标签

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#5694]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前思源的上下标是用标记符号来区别的
```markdown
2^64^，2~64~
````
但这不能在GitHub使用：2^64^，2~64~

Github的上下标语法是用html包裹
```markdown
2<sup>64</sup>
2<sub>64</sub>
```
2<sup>64</sup>
2<sub>64</sub>

### 描述可能的最优解决方案 Describe the optimal solution

个人觉得用html标签包裹会更有通用性，并且相比markdown的标记符在解析上也更不容易出现错乱的情况。
希望工具栏默认使用html标签来实现上下标，但同时也支持markdown扩展标记符的解析

### 描述候选的解决方案 Describe the candidate solution

无

**Comment by 88250** [comment]
暂时不考虑支持更多 HTML 行级元素了，感谢提议。
