### ISSUE TITLE
是否能够优化一下windows安装版的升级方式？

### ISSUE THREAD

**Issue by Lyn6969** [siyuan-note/siyuan#5696]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前同时使用Microsoft Store版和普通安装版，Store版可以无感升级，但是可能由于审核原因会延迟1天，长的时候可能要2-3天，桌面版升级需要下载安装包重新安装，因为思源更新比较频繁，每次更新都会修复一些比较严重的bug或添加比较实用的功能，所以每次下载安装包比较麻烦。

### 描述可能的最优解决方案 Describe the optimal solution

所以是否能在优化安装版的升级方式，实现类似于Store版的升级体验，并且没有延迟？

**Comment by UFDXD** [comment]
你选择可以不更新啊，或者一个星期更新一次。

**Comment by 88250** [comment]
因为技术原因目前无法支持自动更新，只能暂时这样了，抱歉抱歉。
