### ISSUE TITLE
F5 刷新文档支持重新加载图片

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5698]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

经常会用本地编辑器打开图片，加一些图片标注

但必须要把笔记关闭，重新打开，图片的改动才会显示在笔记中 （F5 刷新笔记也不行）

希望能有一个图片上的右键菜单，点击后把图片重新从磁盘读取+展示

### 描述可能的最优解决方案 Describe the optimal solution

比如在图片 URL 后面加一个 hash，刷新修改 hash 就可以

```html
<img src="path/to/image.jpg?hash-code" />
```

**Comment by 88250** [comment]
一次只能手动刷新一个图片的话会不会感觉操作太繁琐？

**Comment by mlzxy** [comment]
> 太

有可能，但我因为笔记都是一点点做的，所以主要的想法是能刷新当前图片就可以。

但如果能一键刷新全部图片也很好

**Comment by 88250** [comment]
我们看下能否改为 F5 刷新全部图片

**Comment by 88250** [comment]
暂时没有找到技术方案，先延后。

**Comment by 88250** [comment]
禁用缓存的话图片多了会卡，所以不能禁用，不禁用的话没有办法刷新图片。

地址后面加随机数的话会改变 assets 路径，有点不妥。暂时找不到方案了，先关闭了，抱歉抱歉。

**Comment by mlzxy** [comment]
> 禁用缓存的话图片多了会卡，所以不能禁用，不禁用的话没有办法刷新图片。
> 
> 地址后面加随机数的话会改变 assets 路径，有点不妥。暂时找不到方案了，先关闭了，抱歉抱歉。

好的没事，这个也是比较边缘的需求。

不过说到图片刷新方案，参考这个回答 https://stackoverflow.com/a/22429796/6238109 中的方案四，可以通过在 iframe 中加载所需刷新的图片，然后用 `iframe.contentWindow.location.reload(true)` 来更新 cache。

不过这个方案对 chrome / edge 比较简单，其他 browser 比较麻烦。
