### ISSUE TITLE
安卓手机端启动很慢很慢，

### ISSUE THREAD

**Issue by twsec-pro** [siyuan-note/siyuan#5699]
安卓手机端启动很慢很慢，卡死在启动页面![Screenshot_2022-08-22-20-56-54-622_org.b3log.siyuan.jpg](https://user-images.githubusercontent.com/58679784/185926568-8819477b-9e2b-4979-8ebc-bdd1a92e9a4d.jpg)

**Comment by 88250** [comment]
每次启动都能必现吗？

**Comment by twsec-pro** [comment]
是的，要不就是白屏界面![Screenshot_2022-08-22-21-07-49-658_org.b3log.siyuan.jpg](https://user-images.githubusercontent.com/58679784/185929148-b59915f1-d323-4795-912c-af2a89986351.jpg)我没订阅前，打开还挺快，订阅了之后再打开就变成这样了，

**Comment by 88250** [comment]
我注意到顶部系统状态栏有个 VPN 图标，禁用一下 VPN 试试。

**Comment by twsec-pro** [comment]
还有个问题，咱的服务器是在国外吗？我不开vpn就是白屏，开了vpn就卡死在启动界面，不开启动界面都不出现

**Comment by twsec-pro** [comment]
还有个问题，咱的服务器是在国外吗？我不开vpn就是白屏，开了vpn就卡死在启动界面，不开启动界面都不出现

**Comment by 88250** [comment]
服务器在国内，不要开 VPN 或者任何代理软件试试。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
