### ISSUE TITLE
在设置中支持只同步部分路径文件夹（主要是日记和备忘），减少延时流量等问题

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#5709]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

感谢D大和V大开发了这么好用的软件，我一直续订希望能为支持思源发展贡献绵薄之力。

平时我几乎不用云端数据，总感觉同步的延时会给我一定的心理压力，反而不愿意使用手机版的我思源。
其实我需要在手机上使用思源的部分目录，特别是日记目录和备忘目录。
毕竟每天晚上或早上记一下日记，身边打开手机更方便，最好能设置自动同步，比如每小时同步。

### 描述可能的最优解决方案 Describe the optimal solution

在设置中可选择几个路径做自动同步。并支持在全局同步不使能的情况下自动同步。
可以限制基本数量，如增加数量可以订阅不同套餐。

**Comment by 88250** [comment]
目前需要手动配置忽略文件，请在用户指南中搜索 `忽略文件`。
