### ISSUE TITLE
列表项块反链包含逻辑问题和引用计数问题

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#571]
某些反向链接既出现在了「链接」里，也出现在了「提及」里（链接的摘要文字又被搜索了一遍），应该是 bug。

折腾了几天这个问题，没找出复现规律，姑且先提一下。

**Comment by 88250** [comment]
方便截图的话麻烦截个图，谢谢。

**Comment by deerainw** [comment]
@88250 

试了半天，现在终于可以截图了，这不是必现 bug

![image](https://user-images.githubusercontent.com/32661922/100037086-71608b00-2e3c-11eb-9a64-8c5948c1aa38.png)

![image](https://user-images.githubusercontent.com/32661922/100037120-7de4e380-2e3c-11eb-800d-b32de6f1736a.png)

第一次发现这个问题是在导入 Obisidian 笔记文件夹的时候，后来发现直接在思源里创建的文件也会有这个问题

**Comment by 88250** [comment]
这个是因为链接里的是列表项块，提及那里是列表块。逻辑上他们存在包含关系，不是相同的。

这个点我们再考虑一下，排除掉应该更合理。

**Comment by deerainw** [comment]
@88250 

那这种包含关系确实该处理一下，不仅仅是在反向链接面板里

再上一个能反映这种包含关系带来的问题的截图：

![image](https://user-images.githubusercontent.com/32661922/100039376-0e70f300-2e40-11eb-94a7-c6fbd21db78b.png)

`缺点.md` 这个文件里只有一个无序列表，无序列表本来只有 3 项，每项里面都含有一个链接。按照这种包含逻辑，局部关系图里直接出现了整整 6 条连在列表块上的线条，并且那 3 条链接线被认为是从列表块上引出来的，但这 3 条线更应该被连接在 3 个列表项块上面

**Comment by 88250** [comment]
谢谢指出，后续进行改进。

**Comment by 88250** [comment]
修复了一下，应该稍微符合直观了：

![image](https://user-images.githubusercontent.com/873584/102494880-55a17b00-40b0-11eb-9fa0-d7ade4b415dd.png)

![image](https://user-images.githubusercontent.com/873584/102494927-63570080-40b0-11eb-884f-a2a5e5c3d0ba.png)
