### ISSUE TITLE
安装后界面不显示，完成安装过程，选择好库的位置，然后就没界面显示了。

### ISSUE THREAD

**Issue by better319** [siyuan-note/siyuan#5710]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

安装后界面不显示，完成安装过程，选择好库的位置，然后就没界面显示了。
但是在桌面部分位置右击是无效的，可以通过鼠标位置来确定中间位置有个透明的框。但是无法显示内容，只能含恨删除。
感觉可能是以下几种情况，electron的问题？gpu的问题？电脑配置低 的问题？有无类似的，求解决方法

### 期待的结果 Expected result

能显示界面，正常使用，现在只进入了选择语言和保存库的位置，其余的还没看到呢，出师未捷身先死！！！

### 版本环境 Version environment

```markdown
设备名称	DESKTOP-6ET1NO9
处理器	Intel(R) Pentium(R) Gold G5420T CPU @ 3.20GHz   3.19 GHz
机带 RAM	4.00 GB (3.81 GB 可用)
设备 ID	64F661FD-B182-472F-9F1F-9989AEBAF028
产品 ID	00331-10000-00001-AA332
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 10 专业版
版本号	20H2
安装日期	‎2021-‎09-‎15
操作系统内部版本	19042.1706
体验	Windows Feature Experience Pack 120.2212.4170.0
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9411653/siyuan.log)

**Comment by better319** [comment]
[app.log](https://github.com/siyuan-note/siyuan/files/9411664/app.log)

**Comment by 88250** [comment]
是不是开了 VPN 或者全局代理软件？

**Comment by better319** [comment]
时间我看他不对，怎么是1点钟，我是刚刚啊8点到9点左右

**Comment by 88250** [comment]
日志时间差了 8 小时，暂时忽略这个问题。

**Comment by 88250** [comment]
另外，可能是防火墙或者杀毒软件阻止了网络访问，如果是这个问题的话加一下白名单。

**Comment by better319** [comment]
也不像，我360页退出了。端口也试过了

**Comment by better319** [comment]
感觉他是在运行的，就是这个界面看不到。窗口能通过鼠标找到大致位置能拉伸缩小

**Comment by 88250** [comment]
能看到系统托盘吗？

**Comment by better319** [comment]
方便给个qq我发个视频给你，只能看到下方任务栏的，没有托盘的

**Comment by 88250** [comment]
麻烦发送到邮件 845765@qq.com

**Comment by 88250** [comment]
已经收到邮件，结合日志文件和视频演示来看，应该是卡在了启动界面，启动界面需要本地网络权限才能通过界面访问到内核 HTTP 服务器。建议还是排查一下网络方面的设置。

另外，在这个状态下可以试一下用 Chrome 浏览器直接访问 `http://127.0.0.1:6806`。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by better319** [comment]
不是的，那个6806是后面几次的记录，这个我能解决，主要是第一次的记录，他是没出错的。就是一个透明框

**Comment by better319** [comment]
我感觉是elctron的问题

https://zhuanlan.zhihu.com/p/442726579

但是增加  --disable-gpu  也不行啊，我纠结

**Comment by 88250** [comment]
安装路径下\resources\app\electron\main.js 打开，然后编辑这部分把值改为 false 试试：

![image](https://user-images.githubusercontent.com/873584/186302970-5ee22009-84e6-4b3e-a5e4-7a650fe947dc.png)

**Comment by better319** [comment]
if (firstOpen) {
    firstOpenWindow = new BrowserWindow({
      width: screen.getPrimaryDisplay().size.width / 2,
      height: screen.getPrimaryDisplay().workAreaSize.height / 2,
      frame: false,
      icon: path.join(appDir, 'stage', 'icon-large.png'),
      transparent: 'linux' !== false,
      webPreferences: {
        nativeWindowOpen: true,
        nodeIntegration: true,
        webviewTag: true,
        webSecurity: false,
        contextIsolation: false,
      },
    })

**Comment by better319** [comment]
if (firstOpen) {
firstOpenWindow = new BrowserWindow({
width: screen.getPrimaryDisplay().size.width / 2,
height: screen.getPrimaryDisplay().workAreaSize.height / 2,
frame: false,
icon: path.join(appDir, 'stage', 'icon-large.png'),
transparent: 'linux' !== 'false',
webPreferences: {
nativeWindowOpen: true,
nodeIntegration: true,
webviewTag: true,
webSecurity: false,
contextIsolation: false,
},
})

**Comment by better319** [comment]
这两个都试了，第一种后面就两个进程了，第二种还是4个进程

**Comment by 88250** [comment]
`transparent: false,`

**Comment by better319** [comment]
还是原样
I 2022/08/24 10:28:48 runtime.go:47: kernel is booting:
    * ver [2.1.8]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [C:\Users\Administrator\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\11111\SiYuan, data 20 kB]
I 2022/08/24 10:28:48 serve.go:78: kernel is booting [http://127.0.0.1:6806]
I 2022/08/24 10:28:48 conf.go:531: database size [4.1 kB], block count [0]
I 2022/08/24 10:28:48 working.go:146: kernel booted

**Comment by better319** [comment]
我感觉应该是渲染问题。
或者什么配置不对

**Comment by 88250** [comment]
那可能真是 Electron 的兼容性问题。近期有两个版本升级过 Electron，请回退试下：

* v2.1.7
* v2.1.6

**Comment by better319** [comment]
siyuan-2.0.16-win.exe
还是一样。我安装这个软件的时候360对这个d3dcompiler_47.dll 文件有过提示。其它我也想不出来问题了

**Comment by better319** [comment]
siyuan-2.0.16-win.exe
还是一样。我安装这个软件的时候360对这个d3dcompiler_47.dll 文件有过提示。其它我也想不出来问题了

我自己chrome版本是：版本 104.0.5112.102（正式版本） （64 位）

**Comment by 88250** [comment]
暂时无法定位问题了……试试其他产品吧，比如 Logseq 和 Obsidian，还有最近新出的 [AFFiNE](https://github.com/toeverything/AFFiNE)。

**Comment by better319** [comment]
好吧

**Comment by better319** [comment]
今天把一些开机启动项恢复了一下，下午重装以后九ok了，非常开心！！
