### ISSUE TITLE
Markdown 表格语法 会被自动转为 图形化的表格，之后无法转换回 Markdown 进行编辑

### ISSUE THREAD

**Issue by lengyu-lys** [siyuan-note/siyuan#5715]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Markdown 表格语法 会被自动转为 图形化的表格，之后无法转换回 Markdown 进行编辑

### 期待的结果 Expected result

可以在 图形化（预览） 与 markdown 语法（raw markdown）之间进行切换

### 版本环境 Version environment

```markdown
- Version: v2.1.0
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

工作空间/temp 目录下无 siyuan.log 文件

**Comment by 88250** [comment]
你好，思源不是 Markdown 编辑器，无法转换为原始 Markdown 文本，感谢反馈。
