### ISSUE TITLE
能否嵌入diagrams以支持在笔记内嵌入脑图/流程图/甘特图……

### ISSUE THREAD

**Issue by xvzhenduo** [siyuan-note/siyuan#5716]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在整理一些知识的时候使用，使用mermaid和markdown制作时序图、脑图、甘特图等等用起来个人感觉很不习惯，而且做起来个人感觉效率比较低，而单独使用diagrams导出图片在插入到笔记，而且每次都需要单独导出数据修改很不方便

### 描述可能的最优解决方案 Describe the optimal solution

嵌入drawio编辑器(在 https://github.com/jgraph/drawio 开源)，支持在页面中插入思维导图/UML(添加一种新的块的类型)，在保存的时候，导出数据和图片自动嵌入到笔记中，并且在下次编辑时自动导入数据(我可能没太描述清楚，为知笔记已经实现了这个功能可以参考一下，下面是截图)
![image](https://user-images.githubusercontent.com/74353173/186353880-338074f3-d1bc-45ad-ae1c-0732fcf7424e.png)
![image](https://user-images.githubusercontent.com/74353173/186353879-dc111e5c-a26e-4e0c-87f6-f7c752c3199d.png)

**Comment by 88250** [comment]
感谢提议，但是这个应该不会内置，可通过挂件扩展。
