### ISSUE TITLE
多个复选框（checkbox）会被视为同一个块，导致无法通过 sql 语句分别进行嵌入

### ISSUE THREAD

**Issue by lengyu-lys** [siyuan-note/siyuan#5717]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

创建第一个复选框A后，按下 enter 键会在下方创建新的复选框B，此时复选框 A 和 B 会作为同一个 block 存入数据库中，即 数据库的 markdown 字段为： “[ ]A   [ ]B”，这导致通过 sql 进行 sql 操作中无法对 A 和 B 进行区别嵌入。

比如，以 TODO list 场景，复选框 A 状态为完成（勾选），复选框 B 状态为未完成（未勾选），如果我想创建一个只显示未完成任务的列表，那么嵌入的sql 语句应该为：“SELECT * FROM blocks WHERE markdown LIKE '%[ ]%'”。然而，由于数据库中，复选框 A 和 b 被视为同一个 block，这就导致这个嵌入语句依然会把已经勾选的 复选框 A 筛选出来。

### 期待的结果 Expected result

不同复选框作为独立的block，这样可以通过 “SELECT * FROM blocks WHERE markdown LIKE '%[ ]%'” 进行分别嵌入

### 版本环境 Version environment

```markdown
- Version: v2.1.0
- Operating System: Windows
- Browser (if used):
```

### 日志文件 Log file

工作空间/temp/ 下没有 siyuan.log 文件

**Comment by 88250** [comment]
使用列表项块来区分即可。具体细节请参考用户指南 `内容块类型` 章节。

**Comment by lengyu-lys** [comment]
这样会有问题，比如，对于这样一个列表：

```

# Title 1
* [ ] item1
* [X] item2

# Title 2
* [ ] item3
* [ ] item4
    * [ ] item4-1
    * [X] item4-2

```

1. 使用 `select * from blocks where  markdown LIKE '%[ ]%' AND subtype = 't' AND type = 'i' ` 的时候， item4-1  会重复。实际展示的结果是：
``` 
* [ ] item1
* [ ] item3
* [ ] item4-1
* [ ] item4
    * [ ] item4-1
```

2. 无法只展示 Title2 下的复选框，不展示 Title1 下的复选框

**Comment by lengyu-lys** [comment]
> 使用列表项块来区分即可。具体细节请参考用户指南 `内容块类型` 章节。

这样会有问题，比如，对于这样一个列表：

```

# Title 1
* [ ] item1
* [X] item2

# Title 2
* [ ] item3
* [ ] item4
    * [ ] item4-1
    * [X] item4-2

```

1. 使用 `select * from blocks where  markdown LIKE '%[ ]%' AND subtype = 't' AND type = 'i' ` 的时候， item4-1  会重复。实际展示的结果是：
``` 
* [ ] item1
* [ ] item3
* [ ] item4-1
* [ ] item4
    * [ ] item4-1
```

2. 无法只展示 Title2 下的复选框，不展示 Title1 下的复选框

**Comment by 88250** [comment]
要排除父节点有点复杂，可参考一下集市中的 List-find 模板。

**Comment by lengyu-lys** [comment]
> 要排除父节点有点复杂，可参考一下集市中的 List-find 模板。

我尝试过那个模板，也会有上文中重复的现象出现

**Comment by lengyu-lys** [comment]
我觉得这个解法是不是可以将每个 checkbox 作为一个单独的block进行存储，只有子checkbox（带有缩进）才会并入当前block。

以如下列表为例

```
* [ ] item1
* [ ] item2
* [ ] item3
    * [ ] item3-1
```

存储时block为：

```
block0.markdown: * [ ] item1
block1.markdown: * [ ] item2
block2.markdown: * [ ] item3 *[ ] item3-1
```

**Comment by 88250** [comment]
对了，你可以试一下 fcontent 字段，这个字段就是只存储第一个子块的内容

**Comment by lengyu-lys** [comment]
> 对了，你可以试一下 fcontent 字段，这个字段就是只存储第一个子块的内容

我试了下，发现这个字段里面丢弃了 格式（markdown）信息

markdown: `* [ ] item1`
fcontent: `item1`

**Comment by lengyu-lys** [comment]
我觉得按照合理性来讲应该加一个 fmarkdown，就像 content 和 fcontent 的关系，markdown 也有一个 fmarkdown

**Comment by 88250** [comment]
嗯，我们再考虑一下。

**Comment by 88250** [comment]
试了一下，逻辑上还是有点问题，fcontent 是第一个叶子块的内容，也就是说忽略了中间出现的容器块，比如对于：

```markdown
* [ ] foo
   * [ ] bar
```

这个列表的第一个叶子块是段落 foo，而不是列表项 foo。所以如果加入 fmarkdown 的话值也是这个段落块的，不会包含 `[ ]`。

**Comment by lengyu-lys** [comment]
> 我觉得这个解法是不是可以将每个 checkbox 作为一个单独的block进行存储，只有子checkbox（带有缩进）才会并入当前block。
> 
> 以如下列表为例
> 
> ```
> * [ ] item1
> * [ ] item2
> * [ ] item3
>     * [ ] item3-1
> ```
> 
> 存储时block为：
> 
> ```
> block0.markdown: * [ ] item1
> block1.markdown: * [ ] item2
> block2.markdown: * [ ] item3 *[ ] item3-1
> ```

那我觉得是否可以按照这种方式进行存储，第一级待办项作为单独的block 进行存储，只将子项合并入父项进行存储

**Comment by 88250** [comment]
如果再出现一个 item3-2 时不单独存储吗？

**Comment by 88250** [comment]
对了，这个问题的相关讨论请参考 https://ld246.com/article/1634221433631

**Comment by lengyu-lys** [comment]
> 对了，这个问题的相关讨论请参考 https://ld246.com/article/1634221433631

看了下相关讨论，个人觉得添加一个 depth 能解决很大一部分的问题，这个 depth 值得是当前块在整个列表中的深度。
比如：

```
* [ ] item1
* [ ] item2
* [ ] item3
    * [ ] item3-1
    * [ ] item3-2
```

对应的数据库：

| type | markdown | depth |
| --- | --- | --- |
| l | * [ ] item1 *[ ]item2 ...... | 0 |
| i | * [ ] item1 | 0 |
| i | * [ ] item2 | 0 |
| l | * [ ] item3 *[ ]item3-1 .... | 0 |
| i | * [ ] item3 *[ ]item3-1 .... | 0 |
| l | * [ ]item3-1 * []item3-2 .... | 1 |
| i | * [ ]item3-1 | 1 |
| i | * [ ]item3-2 | 1 |

这样根据 type、subtype、depth就能够解决很多关于列表项区别的问题了

**Comment by 88250** [comment]
这个可能比较可行，我们考虑看看，谢谢。
