### ISSUE TITLE
浏览器端屏蔽浏览器快捷键

### ISSUE THREAD

**Issue by a1751504** [siyuan-note/siyuan#5718]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在浏览器中使用思源时，由于快捷键的冲突导致不易于使用，而自行调整快捷键是一件很折磨的事情，需要对照浏览器的快捷键一个个设置，费时费力

### 描述可能的最优解决方案 Describe the optimal solution

曾经接触过某些页面使用的js库，对用户的输入进行捕获,比如:
**keypress** https://github.com/dmauro/Keypress
**hotkey.js** https://github.com/jaywcjlove/hotkeys

### 描述候选的解决方案 Describe the candidate solution

none

### 其他信息 Other information

none

**Comment by Vanessa219** [comment]
所有输入都有监听的，可以说一下冲突的快捷键么？看一下能不能单独进行处理。

**Comment by a1751504** [comment]
> 所有输入都有监听的，可以说一下冲突的快捷键么？看一下能不能单独进行处理。

类似于 ctrl+w ctrl+d ctrl+shift+T  ctrl+alt+r 等等很多快捷键都冲突。我觉得单独处理可能会比较麻烦
我用的是chrome浏览器 104.0.5112.102（正式版本） （64 位）_（最新版本）_ ，以供参考

**Comment by Vanessa219** [comment]
这个目前没找到更好的办法，只能尽力处理了。不行的话就只能使用桌面端了。

ctrl+d, ctrl+alt+r 无法重现。其余两个关于页签的没有办法阻止。如果还有其他冲突的话可以继续留言，我们会在浏览器支持的情况下尽可能减少冲突。

**Comment by heartacker** [comment]
<kbd>ctrl+w</kbd>
没法重定向，很难过啊

**Comment by Vanessa219** [comment]
这个是关闭页签吧，重定向是?

**Comment by heartacker** [comment]
> 这个是关闭页签吧，重定向是?

就是浏览器里面，按这个，本想关闭思源里面的标签页的，但是他直接关闭浏览器页面了，相当于退出了siyuan网页版。

**Comment by Vanessa219** [comment]
重新设置一个快捷键吧，这个没有办法，不行就用桌面版，功能更多。
