### ISSUE TITLE
提供重建单个文档索引的 API

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#5719]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当使用/api/file/putFile写内容到sy文件后,需要重建索引才能识别到这个新文件,
但有时候重建索引(/api/filetree/refreshFiletree) 会卡住 (暂时不知道怎么稳定复现该问题)
, 而且重建索引很费时

### 描述可能的最优解决方案 Describe the optimal solution

提供更新单个文件索引的api, 参数为sy文件的路径

**Comment by 88250** [comment]
这个接口暂时不加入 API 文档中；使用方式如下：

```
POST http://127.0.0.1:6806/api/filetree/reindexTree

{
    "path": "/data/20210808180117-czj9bvb/20200812220555-lj3enxa.sy"
}
```
