### ISSUE TITLE
导出时支持配置标签的开闭标记符

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#572]
在导入 Obsidian 笔记文件夹时，所有的 `#标签` 被转换为了 `#标签#`，在导出标准 markdown 的时候，建议再转回 `#标签`

**Comment by 88250** [comment]
好的，估计会加个导出选项，让用户决定用哪种标签导出格式。

**Comment by 88250** [comment]
配置加在导出设置里了，如果需要间隔的话可以用空格：

![image](https://user-images.githubusercontent.com/873584/102688636-fd46b680-4232-11eb-92f2-50a91691b18d.png)
