### ISSUE TITLE
关于我们犯过的错和道歉

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5721]
在 2020 年之前，我们（我和 Vanessa）做过一些错事：

1. 2015 群发推广邮件
2. 2017 通过开源项目挖矿
3. 2019 通过 GitHub 注册黑客派时自动 star b3log/symphony 并 follow 账号

对于这些错事给我们的惩罚是：

* 2019 GitHub 上 b3log 组织已被封禁，相关项目的 stars 已被清零
* 2020 我们请求 GitHub 清空了个人账号的所有 follows
* 永久被钉在了网络耻辱柱上被人唾弃

我们已经充分认识到自己的过错，曾给大家多次[道歉 1](https://ld246.com/article/1550192905665)、[道歉 2](https://ld246.com/article/1580884292368) 和 [道歉 3](https://ld246.com/article/1606723827247)，希望能得到大家的原谅。但仅仅口头道歉是没有意义的。这些年以来，我们时常反省自己的这些过错，深知要做好一个开源项目非常不容易，项目本身给用户带来价值才有实际意义，想走捷径推广是错误的。对于我们所有的开源项目，我们保证：

* 不发送推广邮件
* 不使用非正常方式进行推广，比如滥用 GitHub API 进行项目 star 或者 follow
* 不包含挖矿代码
* 尽自己的最大能力去维护，直到我们手指按不动键盘为止

大家可以随时监督，这些开源项目也随时接受代码审查。

对于[思源笔记](https://b3log.org/siyuan/)项目，我们非常注重用户个人隐私和数据安全，所以我们：

* 完整开源了思源笔记代码
* 使用端到端加密技术来保障任何第三方（包括我们）都无法获取到用户数据

除了技术方面，在运营方面我们也没有主动到任何平台推广过思源笔记，用户社区的建立也完全依赖于用户对思源笔记的了解和使用。

这三年以来我们一直在用自己的实际行动争取重新获得大家的信任和支持。如果你恰好关注到思源笔记，希望我们曾经的过错不会影响你对思源笔记的判断。即使因为这个原因选择不用也合情合理，这是对我们过错应有的惩罚，但恳请你能够给我们一次悔改的机会。

给大家带来的困扰，再次诚恳致歉。

**Comment by netdog2019** [comment]
思源，YYDS，好软件，值得信赖~~~
