### ISSUE TITLE
Add new card styles

### ISSUE THREAD

**Issue by taozina** [siyuan-note/siyuan#5724]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

In my studies, I love to add some types of information like: prohibition, attention, news, law and other things.

In SiYuan it is only possible to have four types of cards: Error, Warning, Info and Success.

Is it possible to manually add other types of cards?

### 描述可能的最优解决方案 Describe the optimal solution

add other types of cards

### 描述候选的解决方案 Describe the candidate solution

add other types of cards

**Comment by 88250** [comment]
Hello, in this case, consider using HTML blocks or widget blocks, thanks.

**Comment by tcmtom** [comment]
You can try using themes
