### ISSUE TITLE
支持导出系统日志

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5726]
设置 - 关于中支持打包导出内核日志文件 siyuan.log，桌面端外加 app.log

**Comment by woniuxia** [comment]
D大，要不要加个详细 log 开关，对于一些疑难问题，打开这个开关输出更多日志，更好的帮忙排查问题

**Comment by 88250** [comment]
@woniuxia 暂时不加了，现在默认的日志级别是 debug 了。
