### ISSUE TITLE
大纲失效

### ISSUE THREAD

**Issue by AiProgram** [siyuan-note/siyuan#573]
### 描述问题 Describe the problem
大纲功能好像又失效了XD，前面0.4.7版本能看到所有的大标题列表，现在大纲是一片白了。同时还不时弹出那个"cannot find command outline"的提示，看起来就是大纲部分功能问题。不过这个提示0.4.7也出现过，那个时候大纲还没有失效。我关掉大纲页再打开也没有用。

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
If it is a problem of parsing and rendering, please post the original Markdown here
````````

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/13717071/100038839-41ff4d80-2e3f-11eb-8709-0f2bf29c531f.png)

### 版本环境 Version environment

* 版本 Version：0.4.91
* 操作系统 Operating system：Windows10专业版 2004
* 浏览器（如果使用）Browser (if used)：无

**Comment by 88250** [comment]
你好，请完全卸载以后再安装看看。

**Comment by 88250** [comment]
请使用最新版本重新安装。如果还有问题请继续跟帖，issue 我关闭了，谢谢。
