### ISSUE TITLE
使用 HTML 块时建议使用 `<div>` 包裹 HTML 代码

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#5732]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

建立了一个html块,其中包含
```html
<pre style="margin-bottom: 0; border-bottom:none; padding-bottom:0.8em;">/etc/mkinitcpio.conf</pre>
<pre style="margin-top: 0; border-top-style:dashed; padding-top: 0.8em;">HOOKS=(base <b>udev</b> ... block <b>lvm2</b> filesystems)</pre>
```
在重启SiYuan后发现只剩下了
```html
<pre style="margin-bottom: 0; border-bottom:none; padding-bottom:0.8em;">/etc/mkinitcpio.conf</pre>
```

### 期待的结果 Expected result

应该可以完整保存的啊?

### 截屏或者录屏演示 Screenshot or screen recording presentation

<https://www.aliyundrive.com/s/7d9vqWUiwEY>

### 版本环境 Version environment

```markdown
- Version: 2.1.9
- Operating System: Windows11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9438111/siyuan.log)

### 更多信息 More information

另外,编写完这个html块后(不退出),按ctrl+z,会出现
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/62456287/187034037-dc28a1c5-78ae-47f8-88c8-34980ad732a9.png">

**Comment by 88250** [comment]
这个问题主要是因为 Markdown 语法解析生成了两个 HTML 块：

![image](https://user-images.githubusercontent.com/873584/187038269-5f325726-a94d-4290-963d-a40d1b9d8fb7.png)

如果用 `<div>` 包裹 `<pre>` 的话就是一个 HTML 块：

![image](https://user-images.githubusercontent.com/873584/187038355-0af995ab-5f81-487e-a98b-54007584f36e.png)


对于前面不包裹的情况，也应该避免数据丢失，按照 Markdown 解析为两个 HTML 块。

**Comment by qiuzhiqian** [comment]
你好，请问该问题是还存在吗，我再思源2.5.2版本上面，使用html块插入html文本，预览是可以生效的，然后关掉这个文档页面，重新打开页面后，html就变成纯文本了。
![截图_选择区域_20221202103327](https://user-images.githubusercontent.com/19386888/205203059-736e9dd6-87da-4fd5-ace2-6c845310fdb0.jpg)

可以正常预览
![截图_选择区域_20221202103344](https://user-images.githubusercontent.com/19386888/205203147-49593f80-c060-4a40-b9e4-e2ed936a8c36.jpg)

重新关闭这个页面后重新打开
![截图_选择区域_20221202103406](https://user-images.githubusercontent.com/19386888/205203204-1a897ac8-8358-46b9-86e4-def410684b71.jpg)

**Comment by qiuzhiqian** [comment]
> 

不太确定是不是我的使用方式不正确

**Comment by 88250** [comment]
@qiuzhiqian 需要使用 div 包裹

**Comment by qiuzhiqian** [comment]
@88250 嗯，我的理解，对于一个普通用户而言，如果没有特殊提现，他一般是不知道需要包裹一个div的，那么这个div是否应该由软件来自动处理一下比较好。而且我上面的这个例子中，好像确实没有看到任何提示说需要用div包裹。关键是不重启的时候还预览生效了，也并没有包任何错误

**Comment by 88250** [comment]
目前会提示多个 HTML 块没有 div 包裹时数据丢失的情况：

![image](https://user-images.githubusercontent.com/873584/205205623-0a9f60d4-a773-4cfc-8638-7cb945003e45.png)

如果是行级元素的话没有提示，这个我们考虑下是否能像你说的，自动通过 div 包裹。
