### ISSUE TITLE
WebDAV 两台电脑笔记相互覆盖

### ISSUE THREAD

**Issue by guanlei1996** [siyuan-note/siyuan#574]
### 描述问题 Describe the problem
我目前有两台 MacBook 分别位于公司与家里，然后两台都是用了同一个 WebDAV 笔记库，会编辑同一个笔记。
家里版本为 0.4.8，公司为 0.4.5

在公司编辑完笔记后直接关系思源笔记，等回家后继续编辑，完事保存关闭。
第二天在公司打开软件，自动打开了笔记，但是内容是昨天关闭时候的版本且直接上传覆盖了。

### 期待的结果 Expected result
 如果可能，能否判断一下文件的最终修改时间或者 WebDAV 文件有冲突选择权可以交给用户处理？ 

### 截屏或录像 Screenshot or video
![image](https://user-images.githubusercontent.com/19180533/100055333-a2ea4e00-2e5e-11eb-8b79-9cb201f40be8.png)

#### 家
* 版本 Version： 0.4.8
* 操作系统 Operating system：macOS
#### 公司
* 版本 Version： 0.4.6
* 操作系统 Operating system：macOS

**Comment by guanlei1996** [comment]
补充问题，昨晚用 0.4.8版本最终保存的版本里面没有 id 信息
![image](https://user-images.githubusercontent.com/19180533/100055609-070d1200-2e5f-11eb-8c94-005f0281e382.png)
![image](https://user-images.githubusercontent.com/19180533/100055662-20ae5980-2e5f-11eb-9b8a-5685326997a6.png)

**Comment by guanlei1996** [comment]
公司版本已尝试更新 0.4.9，出现任何笔记都无法打开的情况，包括本地使用0.4.9 版本新建的笔记库以及新文件。
![image](https://user-images.githubusercontent.com/19180533/100056317-72a3af00-2e60-11eb-9558-e060e02e3461.png)

**Comment by 88250** [comment]
感谢反馈，目前暂时是支持不了同时并行使用，因为在外部修改后思源内部状态没有刷新机制，有点类似 https://github.com/siyuan-note/siyuan/issues/419

无法打开的问题请重新启动看看。

**Comment by guanlei1996** [comment]
好的，谢谢~

**Comment by 88250** [comment]
我关闭 issue 了，谢谢。
