### ISSUE TITLE
通过环境变量 `RUN_IN_CONTAINER` 判断是否在容器内启动

### ISSUE THREAD

**Issue by Tarocch1** [siyuan-note/siyuan#5744]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

使用 k8s 而非 docker 部署时，由于不存在 `/.dockerenv` 文件，无法判断当前运行在容器中，导致网络监听绑定在 127.0.0.1 上，容器外部无法访问。

### 期待的结果 Expected result

使用 k8s 部署依然可以正确判断运行环境，监听 0.0.0.0

### 版本环境 Version environment

```markdown
- Version: v2.1.10
- Operating System:
  - Debian
  - k3s
- Browser (if used):
```

### 日志文件 Log file

I 2022/08/28 23:11:54 runtime.go:47: kernel is booting:
    * ver [2.1.10]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace, data 196 kB]
I 2022/08/28 23:11:54 serve.go:78: kernel is booting [http://127.0.0.1:6806]

### 更多信息 More information

k8s 使用 containerd 而非 docker 作为容器运行时，因此不存在 `/.dockerenv`。

是不是可以在 dockerfile 里定义一个特殊环境变量，在代码中通过这个环境变量确定容器运行环境？

**Comment by 88250** [comment]
你好，请看如下改动是否妥当：

```go
func isRunningInDockerContainer() bool {
	if _, runInContainer := os.LookupEnv("RUN_IN_CONTAINER"); runInContainer {
		return true
	}
	if _, err := os.Stat("/.dockerenv"); err == nil {
		return true
	}
	return false
}
```

**Comment by Tarocch1** [comment]
> 你好，请看如下改动是否妥当：
> 
> ```go
> func isRunningInDockerContainer() bool {
> 	if _, runInContainer := os.LookupEnv("RUN_IN_CONTAINER"); runInContainer {
> 		return true
> 	}
> 	if _, err := os.Stat("/.dockerenv"); err == nil {
> 		return true
> 	}
> 	return false
> }
> ```

看起来这样应该可以

**Comment by 88250** [comment]
好的，那就先这样，谢谢。
