### ISSUE TITLE
模板渲染错误

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#5747]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

2.1.09 渲染的模板和2.1.10渲染模板显示不一致

模板是
```markdown
昨日｜明日

今日做事顺序
{: style="color: var(--b3-card-error-color); background-color: var(--b3-card-error-background);"}

* [ ] 待办

笔记
{: style="color: var(--b3-card-warning-color); background-color: var(--b3-card-warning-background);"}

* Inbox
* 工作与学习
  * 单细胞测序
  * 机器学习
  * 神经生物学
* 反思与展望
```
预期是

![Snipaste_2022-08-29_11-38-35](https://user-images.githubusercontent.com/60436214/187118321-ee1b7aa8-8d9e-4c7f-8d95-038fdfae6e0f.png)

而2.1.10是
![Snipaste_2022-08-29_11-38-53](https://user-images.githubusercontent.com/60436214/187118369-d7d15e26-4ead-4a82-afb5-0ec7f639179c.png)

### 期待的结果 Expected result

模板渲染正常

### 版本环境 Version environment

```markdown
- Version: 2.1.10
- Operating System:  Win11
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by 88250** [comment]
记录：在 https://github.com/siyuan-note/siyuan/issues/5723 中引入的
