### ISSUE TITLE
多行引用问题

### ISSUE THREAD

**Issue by lowwor** [siyuan-note/siyuan#575]
### 描述问题 Describe the problem
当选中多段，点击引用按钮进行引用的时候，仅第一段会有引用效果

**Comment by 88250** [comment]
你好，多行的话是多个段落块。如果需要将多个内容块”打包“，请使用[超级块](https://github.com/siyuan-note/siyuan/issues/73)。

**Comment by lowwor** [comment]
额，不是这个引用，是指markdown里面的>引用，就是选中多个段落点
![image](https://user-images.githubusercontent.com/5444033/100066915-95d65a80-2e70-11eb-90b3-b98fa7155819.png)
这个，只有第一个段落变成了引用。

**Comment by 88250** [comment]
明白了，只有有过问题报告，请关注 https://github.com/siyuan-note/siyuan/issues/132
