### ISSUE TITLE
Mac OS 复制/粘贴时，未保留原格式

### ISSUE THREAD

**Issue by ZinYY** [siyuan-note/siyuan#5751]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在 Mac 平台下使用复制、粘贴 (Command + c, v)，粘贴得到的文本没有格式。

### 期待的结果 Expected result

粘贴得到有格式的文本

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="161" alt="image" src="https://user-images.githubusercontent.com/17381012/187171292-aefe2845-b999-47e3-acab-25c615ef325f.png">
例如上图，复制选中文字，粘贴只能得到文本。

### 版本环境 Version environment

```markdown
- Version: 2.1.8, 2.1.9, 2.1.10均有该问题，2.1.7无该问题
- Operating System: MacOS Moneterey
- Browser (if used):
```

### 日志文件 Log file

N/A

**Comment by Vanessa219** [comment]
8.31 是标题还是什么？前面的 1.3 是什么行内元素？

**Comment by ZinYY** [comment]
> 8.31 是标题还是什么？前面的 1.3 是什么行内元素？

8.31 是二级标题，1.3是主题自带的序号，与内容无关。
总体的markdown代码就是：

```markdown
## 8.31

* [ ] 
```
