### ISSUE TITLE
两面板中间有间隔

### ISSUE THREAD

**Issue by lingr7** [siyuan-note/siyuan#5752]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

本来是在使用其他人开发的主题中出现的，我以为是主题的问题，主题作者告诉我，在多个主题中都出现这种问题，难以避免，本身是siyuan 的ui框架决定的。
相关issue见https://github.com/wxf-0415/Light-bf/issues/3

### 期待的结果 Expected result

处理好面板中的间隔控制方法，方便主题开发者开发主题，实现明亮主题的功能。

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="578" alt="空隙" src="https://user-images.githubusercontent.com/37898999/187190295-585b3152-dc1c-480e-aab9-6cb8c9409912.png">

### 版本环境 Version environment

```markdown
- Version: 2.1.10
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9444114/siyuan.log)

**Comment by 88250** [comment]
请切换到默认主题，没有间隔。
