### ISSUE TITLE
导出 PDF 的 SVG 图片链接无法正常显示

### ISSUE THREAD

**Issue by whzecomjm** [siyuan-note/siyuan#5757]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

类似于
“https://i.upmath.me/svg/%5Cbegin%7Btikzcd%7D%0A%09%7BX_i%7D%20%26%26%20X%20%5C%5C%0A%09%5C%5C%0A%09Y%0A%09%5Carrow%5B%22%7Bg_i%7D%22%2C%20from%3D3-1%2C%20to%3D1-1%5D%0A%09%5Carrow%5B%22%7Bp_i%7D%22'%2C%20from%3D1-3%2C%20to%3D1-1%5D%0A%09%5Carrow%5B%22g%22'%2C%20shift%20right%3D1%2C%20from%3D3-1%2C%20to%3D1-3%5D%0A%09%5Carrow%5B%22h%22%2C%20dashed%2C%20from%3D3-1%2C%20to%3D1-3%5D%0A%5Cend%7Btikzcd%7D”
![](https://i.upmath.me/svg/%5Cbegin%7Btikzcd%7D%0A%09%7BX_i%7D%20%26%26%20X%20%5C%5C%0A%09%5C%5C%0A%09Y%0A%09%5Carrow%5B%22%7Bg_i%7D%22%2C%20from%3D3-1%2C%20to%3D1-1%5D%0A%09%5Carrow%5B%22%7Bp_i%7D%22'%2C%20from%3D1-3%2C%20to%3D1-1%5D%0A%09%5Carrow%5B%22g%22'%2C%20shift%20right%3D1%2C%20from%3D3-1%2C%20to%3D1-3%5D%0A%09%5Carrow%5B%22h%22%2C%20dashed%2C%20from%3D3-1%2C%20to%3D1-3%5D%0A%5Cend%7Btikzcd%7D) 
的svg 或者 png 链接插入思源笔记能够正常显示，但是导出pdf以后显示异常

### 期待的结果 Expected result

导出PDF 能够正常显示相关链接图片

### 版本环境 Version environment

```markdown
- Version: 2.1.10
- Operating System: Win10
- Browser (if used): Edge
```

### 日志文件 Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/08/28 17:31:39 runtime.go:47: kernel is booting:
    * ver [2.1.10]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [C:\Users\Administrator\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\Administrator\Documents\SiYuan, data 40 MB]
I 2022/08/28 17:31:39 serve.go:78: kernel is booting [http://0.0.0.0:6806]
I 2022/08/28 17:31:39 sync.go:95: sync before boot
I 2022/08/28 17:31:41 repository.go:540: synced data repo [ufc=1, dfc=1, ucc=0, dcc=0, ub=49 kB, db=46 kB] in [2.09s]
D 2022/08/28 17:31:41 sync.go:138: sync reindex [upserts=1, removes=0]
I 2022/08/28 17:31:41 conf.go:533: database size [193 MB], block count [50474]
I 2022/08/28 17:31:41 working.go:146: kernel booted
I 2022/08/28 17:35:10 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=24 kB, db=46 kB] in [1.45s]
I 2022/08/28 17:36:17 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.43s]
I 2022/08/28 17:37:42 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.34s]
I 2022/08/28 17:38:59 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=55 kB, db=46 kB] in [1.35s]
I 2022/08/28 17:39:03 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.36s]
I 2022/08/28 17:39:06 sync.go:98: sync before exit
I 2022/08/28 17:39:06 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.41s]
I 2022/08/28 17:39:06 conf.go:370: exited kernel
I 2022/08/29 09:30:31 working.go:106: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/08/29 09:30:31 runtime.go:47: kernel is booting:
    * ver [2.1.10]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [C:\Users\Administrator\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\Administrator\Documents\SiYuan, data 40 MB]
I 2022/08/29 09:30:31 serve.go:78: kernel is booting [http://0.0.0.0:6806]
I 2022/08/29 09:30:31 sync.go:95: sync before boot
I 2022/08/29 09:30:32 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.64s]
I 2022/08/29 09:30:32 conf.go:533: database size [193 MB], block count [50474]
I 2022/08/29 09:30:32 working.go:146: kernel booted
I 2022/08/29 09:38:34 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=24 kB, db=46 kB] in [1.88s]
I 2022/08/29 09:41:56 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=56 kB, db=46 kB] in [2.01s]
I 2022/08/29 09:49:58 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [2.04s]
I 2022/08/29 09:57:59 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.49s]
I 2022/08/29 10:02:26 repository.go:540: synced data repo [ufc=16, dfc=0, ucc=16, dcc=0, ub=128 kB, db=46 kB] in [2.07s]
I 2022/08/29 10:03:37 repository.go:540: synced data repo [ufc=3, dfc=0, ucc=3, dcc=0, ub=34 kB, db=46 kB] in [1.30s]
I 2022/08/29 10:04:54 repository.go:540: synced data repo [ufc=24, dfc=0, ucc=24, dcc=0, ub=76 kB, db=46 kB] in [1.89s]
I 2022/08/29 10:06:16 repository.go:540: synced data repo [ufc=10, dfc=0, ucc=10, dcc=0, ub=56 kB, db=46 kB] in [1.48s]
I 2022/08/29 10:08:52 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.53s]
I 2022/08/29 10:09:28 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.19s]
I 2022/08/29 10:10:40 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=33 kB, db=46 kB] in [1.49s]
I 2022/08/29 10:11:41 repository.go:540: synced data repo [ufc=5, dfc=0, ucc=5, dcc=0, ub=41 kB, db=46 kB] in [1.31s]
I 2022/08/29 10:12:37 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.28s]
I 2022/08/29 10:14:39 repository.go:540: synced data repo [ufc=4, dfc=0, ucc=4, dcc=0, ub=34 kB, db=46 kB] in [1.86s]
I 2022/08/29 10:16:41 repository.go:540: synced data repo [ufc=3, dfc=0, ucc=3, dcc=0, ub=31 kB, db=46 kB] in [1.59s]
I 2022/08/29 10:18:09 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=42 kB, db=46 kB] in [1.24s]
I 2022/08/29 10:18:27 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.35s]
I 2022/08/29 10:18:28 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.32s]
I 2022/08/29 10:18:31 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.37s]
I 2022/08/29 10:19:30 repository.go:540: synced data repo [ufc=6, dfc=0, ucc=6, dcc=0, ub=36 kB, db=46 kB] in [1.45s]
I 2022/08/29 10:20:02 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.36s]
E 2022/08/29 10:45:04 sync.go:130: download cloud latest failed: download object [siyuan/1632795455138/repo/work/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1632795455138/repo/work/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com: no such host
E 2022/08/29 10:45:04 repository.go:519: sync data repo failed: download object [siyuan/1632795455138/repo/work/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1632795455138/repo/work/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com: no such host
E 2022/08/29 10:45:07 sync.go:130: download cloud latest failed: download object [siyuan/1632795455138/repo/work/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1632795455138/repo/work/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com: no such host
E 2022/08/29 10:45:07 repository.go:519: sync data repo failed: download object [siyuan/1632795455138/repo/work/refs/latest] failed: Get "https://siyuan-data.b3logfile.com/siyuan/1632795455138/repo/work/refs/latest": dial tcp: lookup siyuan-data.b3logfile.com: no such host
I 2022/08/29 10:50:11 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=24 kB, db=46 kB] in [1.77s]
I 2022/08/29 10:58:19 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [7.55s]
I 2022/08/29 11:10:07 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.60s]
I 2022/08/29 11:14:19 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.55s]
I 2022/08/29 11:32:37 liandi.go:293: get cloud user elapsed [6562ms]
I 2022/08/29 11:56:21 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.51s]
I 2022/08/29 11:57:27 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.28s]
I 2022/08/29 11:58:34 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.32s]
I 2022/08/29 12:00:45 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.69s]
I 2022/08/29 12:02:04 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.42s]
I 2022/08/29 12:02:41 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=27 kB, db=46 kB] in [1.33s]
I 2022/08/29 12:02:56 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.63s]
I 2022/08/29 12:03:01 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.43s]
I 2022/08/29 12:03:02 sync.go:98: sync before exit
I 2022/08/29 12:03:02 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.53s]
I 2022/08/29 12:03:02 conf.go:370: exited kernel
I 2022/08/29 19:34:06 working.go:106: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/08/29 19:34:06 runtime.go:47: kernel is booting:
    * ver [2.1.10]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [C:\Users\Administrator\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\Administrator\Documents\SiYuan, data 40 MB]
I 2022/08/29 19:34:06 serve.go:78: kernel is booting [http://0.0.0.0:6806]
I 2022/08/29 19:34:06 sync.go:95: sync before boot
I 2022/08/29 19:34:09 repository.go:540: synced data repo [ufc=4, dfc=4, ucc=3, dcc=0, ub=63 kB, db=83 kB] in [2.52s]
D 2022/08/29 19:34:09 sync.go:138: sync reindex [upserts=4, removes=0]
I 2022/08/29 19:34:09 conf.go:533: database size [193 MB], block count [50458]
I 2022/08/29 19:34:09 working.go:146: kernel booted
I 2022/08/29 19:38:46 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=31 kB, db=46 kB] in [1.60s]
I 2022/08/29 19:39:45 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=30 kB, db=46 kB] in [1.49s]
I 2022/08/29 19:40:27 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=33 kB, db=46 kB] in [1.32s]
I 2022/08/29 19:43:22 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=26 kB, db=46 kB] in [1.63s]
I 2022/08/29 19:43:41 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=26 kB, db=46 kB] in [1.29s]
I 2022/08/29 19:44:38 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=26 kB, db=46 kB] in [1.38s]
I 2022/08/29 19:48:53 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.74s]
I 2022/08/29 19:49:55 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=25 kB, db=46 kB] in [1.39s]
I 2022/08/29 19:51:01 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=30 kB, db=46 kB] in [1.47s]
I 2022/08/29 19:51:32 index.go:183: rebuilt database for notebook [20210808180117-czj9bvb] in [0.74s], tree [count=49, size=1.2 MB]
I 2022/08/29 19:51:33 index.go:320: resolved refs [1317] in [1121ms]
I 2022/08/29 19:52:39 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.51s]
I 2022/08/29 19:53:07 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.31s]
I 2022/08/29 19:55:34 repository.go:540: synced data repo [ufc=5, dfc=0, ucc=5, dcc=0, ub=39 kB, db=46 kB] in [1.82s]
I 2022/08/29 20:03:34 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.71s]
I 2022/08/29 20:11:35 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.56s]
I 2022/08/29 20:19:36 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.57s]
I 2022/08/29 20:35:37 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.81s]
I 2022/08/29 20:47:35 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.68s]
I 2022/08/29 20:48:38 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=31 kB, db=46 kB] in [1.52s]
I 2022/08/29 20:50:55 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=39 kB, db=46 kB] in [1.52s]
I 2022/08/29 20:54:27 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=42 kB, db=46 kB] in [1.97s]
I 2022/08/29 20:59:57 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=36 kB, db=46 kB] in [2.81s]
I 2022/08/29 21:00:27 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.36s]
I 2022/08/29 21:02:29 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=50 kB, db=46 kB] in [2.09s]
I 2022/08/29 21:03:36 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=54 kB, db=46 kB] in [1.45s]
I 2022/08/29 21:05:03 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=47 kB, db=46 kB] in [1.67s]
I 2022/08/29 21:06:19 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=47 kB, db=46 kB] in [1.38s]
I 2022/08/29 21:07:06 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=47 kB, db=46 kB] in [1.32s]
I 2022/08/29 21:07:34 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.44s]
I 2022/08/29 21:09:41 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=47 kB, db=46 kB] in [1.77s]
I 2022/08/29 21:09:56 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=46 kB, db=46 kB] in [1.46s]
I 2022/08/29 21:10:27 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.49s]
I 2022/08/29 21:11:33 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=46 kB, db=46 kB] in [1.54s]
I 2022/08/29 21:14:50 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=44 kB, db=46 kB] in [1.52s]
I 2022/08/29 21:16:02 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=44 kB, db=46 kB] in [1.78s]
I 2022/08/29 21:17:04 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=41 kB, db=46 kB] in [1.37s]
I 2022/08/29 21:17:52 repository.go:540: synced data repo [ufc=1, dfc=0, ucc=1, dcc=0, ub=38 kB, db=46 kB] in [1.45s]
I 2022/08/29 21:21:57 repository.go:540: synced data repo [ufc=2, dfc=0, ucc=2, dcc=0, ub=46 kB, db=46 kB] in [1.90s]
I 2022/08/29 21:22:40 repository.go:540: synced data repo [ufc=3, dfc=0, ucc=3, dcc=0, ub=71 kB, db=46 kB] in [1.45s]
I 2022/08/29 21:23:12 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.37s]
I 2022/08/29 21:31:13 repository.go:540: synced data repo [ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=46 kB] in [0.62s]

**Comment by 88250** [comment]
这个问题需要等 https://github.com/siyuan-note/siyuan/issues/5500 改进以后再看看，感谢反馈。
