### ISSUE TITLE
思源的严重恶性Bug！剪切大段文章，渲染出错

### ISSUE THREAD

**Issue by ListenV** [siyuan-note/siyuan#5758]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

从文章A剪切内容到文章B，会出现渲染问题（剪切掉的内容依然出现在文章A，文章B中实际没有剪切内容）进而导致用户误操作。
由于用户误操作，重建索引后剪切内容直接全部丢失！

此BUG自从2.0开始，我一直受此困扰，真的实在受不了了

真的建议思源先提高可靠性，再搞其他的

### 期待的结果 Expected result

解决问题即可
希望不要再出现这种数据丢失，体验极差的问题

### 版本环境 Version environment

```markdown
- Version: 2.1.9
- Operating System: Windows10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9445007/siyuan.log)

**Comment by 88250** [comment]
我尝试使用用户指南排版元素这篇文档重现，暂时没有发现问题，请看下面的录屏，是我重现步骤不对吗？

![issue](https://user-images.githubusercontent.com/873584/187217556-f55f9001-5482-442e-97cd-52930e1fad78.gif)

**Comment by ListenV** [comment]
请看我2021-11-13的文章https://ld246.com/article/1636732243131

多重复几次，就出现了

**Comment by ListenV** [comment]
最好再包含多个块 操作

**Comment by 88250** [comment]
目前不支持跨文档撤销操作，请关注 #4866

**Comment by 88250** [comment]
这个 issue 主要指的就是跨文档撤销吗？还是其他的问题，麻烦再录屏演示一下，谢谢。

**Comment by 88250** [comment]
好的，那就请关注 #4866，这个我关闭了，谢谢。
