### ISSUE TITLE
数据历史文档可视化 diff

### ISSUE THREAD

**Issue by ListenV** [siyuan-note/siyuan#5759]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

完全看不懂什么是什么

没有修改的文件，只是打开看了一下，也出现在了文档历史中

这种搞得不清不楚，整篇文章直接搬过来，这种功能还不如不要

### 期待的结果 Expected result

至少对于修改过的内容得给个高亮显示吧？

再高级一些，搞个类似于GitHub中修改记录的那种

Like this：
`-` 后面表示删除内容
`+` 后面表示新增内容

### 版本环境 Version environment

```markdown
- Version: 2.1.9
- Operating System: Windows10
- Browser (if used):
```

### 日志文件 Log file

no log

**Comment by 88250** [comment]
目前无法实现 diff 可视化，后期如果可能的话会重新打开这个 issue，感谢反馈。
