### ISSUE TITLE
公式补全

### ISSUE THREAD

**Issue by YaooXu** [siyuan-note/siyuan#576]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
编辑公式的时候，如果有补全，对效率的提升非常大，类似vscode上的md插件提供的补全功能，如下：
![image](https://user-images.githubusercontent.com/44971199/100079621-d689a000-2e7f-11eb-8528-d0e3c8edcee7.png)

### 描述最优的解决方案 Describe the optimal solution
进入公式编辑模式的时候，启用snippet集合。

### 描述候选解决方案 Describe the candidate solution
给出接口，让其他人开发插件。

**Comment by Tokubara** [comment]
公式和代码地位是等价的吧. 如果支持了公式补全, 那么要不要支持代码补全呢?
我觉得这不是一个markdown编辑器做的事, 这是代码编辑器的事. 
这个需求完全可以在vscode写好了再copy过来. 如果装alfred或者keyboard maestro之类的, 几乎没有什么时间代价.
这只是个人看法.

**Comment by 88250** [comment]
这应该是个好提议，不过确实正如 Tokubara 所言，我觉得还是暂时不引入这样的功能吧，谢谢提议。
