### ISSUE TITLE
能否提供根据id打开文档的api?🐱

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#5763]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

经常需要返回到当前文档的父级文档(不是"后退"ctrl+[ ) ,还有经常打开光标下的引用块,
有了这个api,就能实现前者,和改进后者(新文档将在前台打开而不是后台打开)了

### 描述可能的最优解决方案 Describe the optimal solution

提供根据id打开文档的api, 参数为文档id或者块id,执行后打开文档,并跳转到相应页签,如果是块id再跳到相应块

**Comment by 88250** [comment]
这个估计放在 #5066 上更合适一些，感谢提议。
