### ISSUE TITLE
Alt+Click分屏功能消失

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#5765]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

https://github.com/siyuan-note/siyuan/issues/4953#issue-1241700217
最新版本中已经无法使用且在设置中没有分屏的快捷键选项

### 期待的结果 Expected result

希望恢复

### 版本环境 Version environment

```markdown
- Version: 2.1.10
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9457974/siyuan.log)

**Comment by Vanessa219** [comment]
你是在哪里使用 alt+click，文档树上是可以使用的。

**Comment by Kitsuta-le** [comment]
> 你是在哪里使用 alt+click，文档树上是可以使用的。

我是哪里都用不了。。。

**Comment by 88250** [comment]
我这里也正常，你试下按住 Alt 后再点击，不要一起操作。

**Comment by Kitsuta-le** [comment]
> 是默认主题么？

试了默认主题，也是一样

**Comment by 88250** [comment]
升级到最新版试试。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Kitsuta-le** [comment]
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

最新版问题已解决！
