### ISSUE TITLE
页签右键菜单分屏功能异常

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#5775]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如录屏所示，v2.1.11，windows 10 平台，标签页处右键菜单分屏功能异常；
ps：在文档树那里Alt+点击 能正常分屏。

### 期待的结果 Expected result

正常分屏

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/58081876/187733484-cb5cbd65-f1ea-48a8-b47e-fc64d4ca0f90.mp4

### 版本环境 Version environment

```markdown
- Version: 2.1.11
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by aobatu** [comment]
分屏功能每天都在用，幸好现在还可以在文档树那里Alt+点击 能正常分屏，否则就很悲剧了。。。
