### ISSUE TITLE
自定义“引用”样式

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#578]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
使用“引用”（> blahblah...)

之前版本的“引用”语法，文字和文字之前的竖线符号都是白色的（黑夜模式下），现版本变成了深灰色，在黑色背景下不易阅读，希望能够提供选项，更改“引用”的颜色设置。

**Comment by 88250** [comment]
请自定义主题吧……单独的颜色配置估计还要再等等。

**Comment by 88250** [comment]
用自定义主题，默认样式众口难调，我关闭了，谢谢。
