### ISSUE TITLE
`docker run`启动失败，报权限不足

### ISSUE THREAD

**Issue by ql-isaac** [siyuan-note/siyuan#5780]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

容器启动命令：
```
docker run -d --name siyuan --restart always -v /home/xxx/Documents/SiYuan:/siyuan/workspace/ -p 6806:6806 -u 1000:1000 b3log/siyuan:v2.1.10 --workspace=/siyuan/workspace/
```
失败后查看容器日志：
```
2022/09/01 14:32:26 create os tmp dir [/siyuan/workspace/temp/os] failed: mkdir /siyuan/workspace/temp: permission denied
```

### 期待的结果 Expected result

容器正常启动。

### 截屏或者录屏演示 Screenshot or screen recording presentation

容器日志：
![image](https://user-images.githubusercontent.com/53886119/187865040-828cbcaa-bfa2-46a9-86b1-559ae3282e80.png)

### 版本环境 Version environment

```markdown
- Version: v2.1.10
- Operating System: Debian 11.4
- Browser (if used):
```

### 日志文件 Log file

无。

**Comment by 88250** [comment]
可能是挂载的文件夹权限不足，请检查一下。

**Comment by ql-isaac** [comment]
> 可能是挂载的文件夹权限不足，请检查一下。

是思源生成的工作目录在主机里的UID和GID为100999，我得给挂载的目录授予777才行，这是正常的吗大佬

**Comment by ql-isaac** [comment]
![image](https://user-images.githubusercontent.com/53886119/187896084-f1b65ee5-f69a-4d33-b1e2-a807afc6f0da.png)

**Comment by ql-isaac** [comment]
好

**Comment by Summa-rizer** [comment]
![image](https://user-images.githubusercontent.com/54730328/225001579-aae9bd27-86be-4e10-9e5e-a17dde0e7966.png)
镜像中是使用默认创建的普通用户 siyuan（uid 1000/gid 1000）来启动内核进程的，所以在宿主机创建工作空间文件夹时请注意设置该文件夹所属用户组：chown -R 1000:1000 /siyuan/workspace，在启动容器时需要带参数 -u 1000:1000。
from:https://hub.docker.com/r/b3log/siyuan

**Comment by Summa-rizer** [comment]
> > 可能是挂载的文件夹权限不足，请检查一下。
> 
> 是思源生成的工作目录在主机里的UID和GID为100999，我得给挂载的目录授予777才行，这是正常的吗大佬

镜像中是使用默认创建的普通用户 siyuan（uid 1000/gid 1000）来启动内核进程的，所以在宿主机创建工作空间文件夹时请注意设置该文件夹所属用户组：chown -R 1000:1000 /siyuan/workspace，在启动容器时需要带参数 -u 1000:1000。https://hub.docker.com/r/b3log/siyuan

**Comment by HK115** [comment]
启动命令没加授权码
