### ISSUE TITLE
导出 Markdown 时保留最基本引用关系信息

### ISSUE THREAD

**Issue by wdssmq** [siyuan-note/siyuan#5802]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

导出内容为 Markdown 文件时，对于其中的引用块标记，能够转换为 ：

`[[被引用的文件名]]`

对于其中具体标题块的引入，则转换为：

`[[被引用的文件名#标题锚点]]`

### 描述可能的最优解决方案 Describe the optimal solution

```md
<!-- 001.md -->
# 001

### ABC

### DEF
```

```md
<!-- 002.md -->
# 002

### HIG

-------↓↓这里是重点↓↓----------

#### 我希望的导出形式 

直接引用：[[001]]

引用其中的标题：[[001#ABC]]

-------↑↑这里是重点↑↑----------

### 下边是内置各种选项的导出效果

### 仅锚文本

直接引用：001

引用其中的标题：ABC

#### 锚文本块链

直接引用：[001](siyuan://blocks/20220903154203-fzna2py)

引用其中的标题：[ABC](siyuan://blocks/20220903154238-et1g3er)

#### 脚注模式（默认）

直接引用：001[^1]

引用其中的标题：ABC[^2]

<!-- [^1] [^2] 以脚注形式附加在结尾 -->
```

**Comment by 88250** [comment]
如果是文档引用的话，可以考虑通过这个选项达成目的：

![image](https://user-images.githubusercontent.com/873584/188261974-73c947e7-5a47-40a7-ae84-80bc2a30f86f.png)

锚点的话应该不会考虑，已经有脚注了，谢谢。
