### ISSUE TITLE
反链互换

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5805]
可否再加一个互换功能, 将原始块移动到新页面, 同时在旧页面生成引用块或者嵌入快, 这个对于整理和溯源很有帮助

_Originally posted by @why8023 in https://github.com/siyuan-note/siyuan/issues/3294#issuecomment-1236118471_

暂时不太确定和 #4025 的关系，先记录。

**Comment by Dammyxy** [comment]
和 #4981 是同一需求，可以做但优先级或许不是那么高

**Comment by 88250** [comment]
@Dammyxy 多谢提醒，我就觉得好像建过 😂 

Duplicate of #4981
