### ISSUE TITLE
Windows 端打开本地文件所在位置失效

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#5808]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Alt+拖拽文件到笔记后，未能通过右键菜单或者Ctrl+Click打开文件所在位置。去掉路径中多余的 \ 后，才能正常打开。建议去掉多余的 \

如录屏所示：

### 期待的结果 Expected result

能正常使用【打开文件所在位置】这个功能。

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/58081876/188277576-3d8502d6-055c-441f-8450-e8b0f5d9311f.mp4

### 版本环境 Version environment

```markdown
- Version: 2.1.12
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

null

**Comment by 88250** [comment]
`\` 这个应该保留两个的，否则会和包含 `)` 的文件名产生解析二义性 https://github.com/siyuan-note/siyuan/issues/5786
