### ISSUE TITLE
PDF 阅读器内存泄漏

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5809]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

有时阅读 PDF 的时候，突然软件就卡死了，需要强制关闭，重启后又好了，然后过一段时间又可能出现。

卡死时整个软件不能操作，连 Developer Tool 都卡死了

跟踪了 Siyuan 的内存使用状态，如下：

# 刚打开软件：

<img width="535" alt="Screen Shot 2022-09-03 at 1 20 53 PM" src="https://user-images.githubusercontent.com/7659710/188284622-a4701fe7-a457-43b2-87e8-ef6a3a76c480.png">

# 软件卡死时：

<img width="546" alt="Screen Shot 2022-09-03 at 2 59 50 PM" src="https://user-images.githubusercontent.com/7659710/188284628-9048a245-0683-4ddd-b835-3dd683089b59.png">

如果不阅读 PDF，没遇到过卡死的情况。

### 期待的结果 Expected result

阅读 PDF 时不会随机卡死

### 版本环境 Version environment

```markdown
- Version: 2.1.11 （这个问题其实多个版本一直存在）
- Operating System: OSX 
- Browser (if used):
```

### 日志文件 Log file

日志好像很空没啥，感觉是页面渲染层面出的问题

**Comment by 88250** [comment]
感谢反馈，确实没有正确释放 pdf.js 实例。
