### ISSUE TITLE
无序列表撤销编辑后触发重建索引

### ISSUE THREAD

**Issue by ProMachine** [siyuan-note/siyuan#5812]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在大纲（从幕布导入过来的）下操作，剪切、粘贴操作并不如其他大纲类笔记理想：多个无序列表在同一行，且在剪切、粘贴、shift+tab、ctrl+z撤销（怀疑是主要原因）操作出现内容丢失（公式）并强制重建索引

### 期待的结果 Expected result

类似幕布的体验，剪切、粘贴符合直觉，tab, shift+tab正常工作，ctrl+z撤销正常工作

### 版本环境 Version environment

```markdown
- Version: 2.1.11
- Operating System: Windows10
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/9483673/system-log.zip)

**Comment by 88250** [comment]
你好，触发重建索引的操作麻烦录屏演示，谢谢。

**Comment by ProMachine** [comment]
第一次录屏，前面很多操作可能无效，关键触发原因应该是撤销操作。但是可以看到多个无序列表在同一行、有的同层无序列表上下之间没有灰线连起来（或许是不认为它们是同一层级？）这些不希望出现的现象

https://user-images.githubusercontent.com/22593803/188294871-389577d9-7314-4536-9925-c27ad7717137.mp4

**Comment by 88250** [comment]
感谢提供录屏，但是……这个录屏有点太复杂了，能否帮忙试下最小化的重现步骤，谢谢。

**Comment by ProMachine** [comment]
中途长时间尝试也是在想快速把问题复现出来，也总结不出来什么模式⋯我想应该是最后几秒出现的问题，可以看到撤销操作并没有正常工作，连续撤销很多次仍然看不到什么变化，这已经是个问题；最后的操作是撤销-删除-撤销，可能是崩溃的关键

**Comment by 88250** [comment]
好的，这个 issue 先暂时保持打开，我们继续收集反馈，谢谢。

**Comment by ProMachine** [comment]
其他的一些关于大纲（无序列表）的bug或建议：

大纲内数学公式连续输入$\displaystyle $后消失（但仍然存在），希望有一种模式能可视化这些特殊字符；

* 行间距减小以展示更多信息，或者改为可行间距
* 优化大纲操作逻辑，建议不支持单个无序列表内换行（就是新建一个无序列表，然后按backspace），复制、粘贴其他大纲时不符合直觉，综合tab, shift+tab, backspace效果可参考幕布、RemNote或Dynalist等大纲类笔记
* 导出时默认自动展开全部大纲，为了避免内容过多，可选择对当前的展开状态进行保留
* 无论选哪种格式，导出效果不理想，没有颜色和其他格式

**Comment by 88250** [comment]
* 数学公式建议用快捷键触发公式输入框
* 行间距可通过自定义 CSS 调整
* 支持大纲文档混排是思源的特性，思源不是纯大纲笔记
* 为了保持导出内容可见性，导出 Markdown/HTML/Word/PDF 这些都是展开的，只有导出 .sy.zip 是原生导出
* 导出 SiYuan HTML 或者 PDF 应该是有颜色和格式的，但是标准 Markdown/HTML/Word 就无法保证了

感谢反馈。

**Comment by ProMachine** [comment]
若是需要分享文档给其他人阅读，为了减小篇幅，应该怎么操作呢？比如我的论文阅读笔记是按主题分类的，每次分享只想展示更新后的部分，但是希望整体框架还在。
在Dark+主题下导出不正常，刚刚试了下换不带背景的notion主题，能导出颜色，但是颜色错位，比如蓝色变成橙色，红色变成绿色。颜色的定义在CSS里不是统一的吗？

**Comment by 88250** [comment]
* 可以考虑导出 .sy.zip 然后导入，但是这个需要接收分享的人也使用思源，否则的话这个场景估计只能手动复制一个副本文档然后手动踢掉不要的部分再导出了
* 各个主题对 CSS 类的命名是统一使用的，但是实现不一样，所以切换主题颜色会切换

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
