### ISSUE TITLE
云端收集箱图标缺失

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5813]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

云端收集箱没图标了。

### 期待的结果 Expected result

云端收集箱有图标了。

### 版本环境 Version environment

```markdown
- Version: 2.1.10
- Operating System: win10
- Browser (if used):edge
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
请更新到最新版，并使用默认主题和图片看下是否有问题。
