### ISSUE TITLE
改进 `Ctrl+K` 超链接粘贴识别

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5817]
https://ld246.com/article/1662258278601

增加一些合法的域名后缀：pm to store shop love icu ltd news work group online game design link

关联 https://github.com/siyuan-note/siyuan/issues/4669

**Comment by Achuan-2** [comment]
思源自己的超链接siyuan://blocks希望也支持识别

**Comment by 88250** [comment]
@Achuan-2 收到，这个 issue 中一并处理。

**Comment by iamqiz** [comment]
@88250 d大,麻烦支持一下 jetbrains:// 协议
