### ISSUE TITLE
不要的云端同步目录删除又自动出现了

### ISSUE THREAD

**Issue by netdog2019** [siyuan-note/siyuan#5821]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

不要的云端同步目录删除又自动出现了，我尝试删除过好几次，要么是删除不了，偶尔有两次删除了，但是中午删除，晚上打开云端同步目录，发现那个删除了的目录又在那里了。

### 期待的结果 Expected result

删除了的云端同步目录就不在出现了。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/49815951/188321282-d866cd1e-cbf8-4aea-862b-2159b13f1683.png)
我这个里面的siyuan目录，删除过好几次，都还在。

### 版本环境 Version environment

```markdown
- Version: 2.1.12
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9484978/siyuan.log)
[app.log](https://github.com/siyuan-note/siyuan/files/9484979/app.log)

**Comment by netdog2019** [comment]
我刚刚又删除了，按照惯例，明天又会出现了。
![image](https://user-images.githubusercontent.com/49815951/188321581-2f5a8686-4368-48de-a279-a23afe2685fb.png)
[siyuan.log](https://github.com/siyuan-note/siyuan/files/9484996/siyuan.log)
[app.log](https://github.com/siyuan-note/siyuan/files/9484997/app.log)
这是刚刚删除后的日志文件。

**Comment by 88250** [comment]
试下如下步骤：

* 暂停**所有端**的同步
* 在一个端上执行删除

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by netdog2019** [comment]
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

我找到原因了，是我在办公室的一台很少用的电脑没有关闭，那个上面的思源开着忘了关闭，而且那个里面的云端目录没有修改过来，所以一直同步，现在把那台电脑关闭了，就可以了。
