### ISSUE TITLE
Git 版本管理支持

### ISSUE THREAD

**Issue by LiaoSirui** [siyuan-note/siyuan#5824]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

希望保存更改历史，存放到 Git 仓库（例如 Gitlab / Github）

### 描述可能的最优解决方案 Describe the optimal solution

gitbook  有类似的功能， sync from git repository

**Comment by 88250** [comment]
这个方案在早期我们已经尝试过，主要存在的问题是对非程序员用户不够友好，比如冲突不方便解决，另外就是性能不太好。

我关闭了，如果还有需要讨论或者建议欢迎继续跟帖，谢谢。
