### ISSUE TITLE
Linux 端不再支持 `粘贴为纯文本` 时处理文件绝对路径

### ISSUE THREAD

**Issue by crafter-z** [siyuan-note/siyuan#5825]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在编辑器内，“粘贴为纯文本”选项在右键菜单点击时，与使用快捷键时的行为不一致。
当使用右键菜单点击时正常工作：
![image](https://user-images.githubusercontent.com/62090995/188450151-a937dc06-a508-4e41-9f1c-b90aac55d48e.png)
![image](https://user-images.githubusercontent.com/62090995/188450067-659d3ad5-58df-44b8-8660-603761fb6835.png)
当使用默认快捷键“ctrl+shift+v”时，黏贴出如下内容：
![image](https://user-images.githubusercontent.com/62090995/188450344-cb48f96e-cdaf-4257-95ff-99905d85c7c0.png)
经测试，任何文本在使用“ctrl+shift+v”粘贴时均会被附加`file://`前缀
**当尝试切换快捷键为其他快捷键时出现了一个有意思的现象：**
![image](https://user-images.githubusercontent.com/62090995/188451099-3ff1474a-ee8a-4c25-94cd-07b0ed121b73.png)
![image](https://user-images.githubusercontent.com/62090995/188451341-882c731e-804c-4ba9-9926-c4f1b406e48f.png)
将快捷键切换为其他后（例如“ctrl+alt+M”），右键菜单的提示确实有跟着改变，快捷键也生效，且快捷键仍是错误的行为。
然而，当切换快捷键后，“ctrl+shift+v”却也能被正常响应，此时“ctrl+shift+v”与自定义的快捷键表现不同，但与点击右键菜单的按钮表现相同。

### 期待的结果 Expected result

修正快捷键的错误行为

### 版本环境 Version environment

```markdown
- Version: 2.1.12
- Operating System: ArchLinux，X11，KDE
```

### 日志文件 Log file

非崩溃问题，无有效日志

**Comment by crafter-z** [comment]
试了，默认的daylight和midnight都有这个问题

**Comment by 88250** [comment]
是不是其他程序改写了剪切板？

**Comment by 88250** [comment]
可以试下复制文字以后在记事本中粘贴。

**Comment by crafter-z** [comment]
我试了一下，此问题没在Windows中出现，只在Linux里有，且系统剪贴板未被篡改，异常的黏贴行为使用的是思源的自定义快捷键时出现。

**Comment by 88250** [comment]
我这里也在 Ubuntu 上测试了，没有重现问题哦。

**Comment by crafter-z** [comment]
我用ctrl+V是正常行为，ctrl+shift+V也是正常行为，思源自定义快捷键的粘贴就会异常地给内容加上`file://`的前缀

**Comment by crafter-z** [comment]
我尝试一下重新安装思源笔记

**Comment by 88250** [comment]
我的重现步骤是将粘贴为纯文本的快捷键改为 Ctrl+Alt+M，然后粘贴的。

**Comment by crafter-z** [comment]
![image](https://user-images.githubusercontent.com/62090995/188456526-b514d6e4-ff75-4fb9-bfb2-f48e422f30ec.png

**Comment by crafter-z** [comment]
复制了文本，使用自定义的“粘贴为纯文本”快捷键粘贴，会自动给这个文本加上`file://`

**Comment by 88250** [comment]
如果是从思源自己的编辑器中复制，然后再粘贴为纯文本呢？

**Comment by crafter-z** [comment]
从思源中“复制纯文本”，然后快捷键粘贴，一样的问题，我试了很多个快捷键，都是一样的效果

**Comment by crafter-z** [comment]
以上尝试均无效，我录了段视频你可以看下
https://pan.baidu.com/s/1Wd0TsSquzUWyaWJyuoJ4sA?pwd=fv6i 提取码: fv6i

**Comment by 88250** [comment]
这个确实有点奇怪，我们稍后调整一下，等下个版本发布以后请帮忙再试试。

**Comment by 88250** [comment]
对了，请打开开发者工具 Network，按下快捷键后看下这个请求：

![Uploading image.png…]()

**Comment by 88250** [comment]
谢谢，那应该是 Linux 系统上 readFilePaths 这个实现有点问题，下个我们先屏蔽掉，这样的话 Linux 复制文件就只能使用拖拽插入了。
