### ISSUE TITLE
blocks定位

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#5828]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

blocks块定位遇到代码块就会自动变到第一个
![image](https://user-images.githubusercontent.com/98648589/188471775-437c422a-fdfb-4315-81c2-4ae28862948b.png)
![image](https://user-images.githubusercontent.com/98648589/188471816-5b0c72bf-d23f-4d43-9cbc-2c006cd113c2.png)

### 描述可能的最优解决方案 Describe the optimal solution

不知道是不是个bug如果是bug希望修复

**Comment by 88250** [comment]
你指的是随着页面浏览位置定位吗？这个有个需求还在考虑 https://github.com/siyuan-note/siyuan/issues/4612

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Chenm4** [comment]
![image](https://user-images.githubusercontent.com/98648589/188528599-f9608bdb-0645-4e1e-a438-caca7b6fa3bc.png)
![image](https://user-images.githubusercontent.com/98648589/188529008-fbedcf04-8c59-4290-b17c-217b651c39a6.png)
不过我试了下发现这个问题发现好像复现比较困难（找了别的好几篇文档查看发现都没问题），应该是个bug。至于随着页面浏览位置定位功能我个人觉得属于是锦上添花的需求
