### ISSUE TITLE
Android 端打包错误

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#5829]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

刚刚安卓端更新到V2.1.13，发现更新完后版本号是V2.1.12，卸载后重装也是V2.1.12，建议顺手改一下版本号。

### 期待的结果 Expected result

版本与版本号对应

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/58081876/188487906-cadc1016-be8b-40cc-b8d1-ab9f273dd0d0.mp4

### 版本环境 Version environment

```markdown
- Version: 2.1.13
- Operating System: Android
- Browser (if used):
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
v2.1.13 的 Android 打包有问题，没有使用前端源码最新版构建，而是用的 v2.1.12 的前端源码构建。这个问题会在下个版本修复。
