### ISSUE TITLE
siyuan-0.4.91-win 版启动报错 ERROR: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by hwd-2020** [siyuan-note/siyuan#583]
系统版本：windows 10 专业版 18363.1198
版本号：1909

执行exe报错，无法进入界面：
`A JavaScript error occurred in the main process`
`Uncaught Exception:`
`Error: spawn ..\kernel\kernel.exe ENOENT`
`at Process.ChildProcess._handle.onexit(internal/child_process.js:267:19)`
`at onErrorNT(internal/child_process.js:469:16)`
`at processTicksAndRejections(internal/process/task_queues.js:84:21)`

清理 `C:\Users\*****\AppData\Roaming\siyuan` 缓存无效
exe安装版以及zip压缩版均报错
siyuan-0.4.9-win 版本同样报错

**Comment by 88250** [comment]
麻烦试下最新发布的 v0.4.92 谢谢。

**Comment by hwd-2020** [comment]
你好，重下了 siyuan-0.4.92-win 还是报错。

**Comment by 88250** [comment]
请看下安装目录/resources/ 目录下是否有 kernel.exe：

![image](https://user-images.githubusercontent.com/873584/100198129-62f69a00-2f36-11eb-847a-647502f87413.png)

**Comment by hwd-2020** [comment]
有的
![image](https://user-images.githubusercontent.com/65169631/100198384-ba950580-2f36-11eb-8456-a498f58ed627.png)
![image](https://user-images.githubusercontent.com/65169631/100198437-d39db680-2f36-11eb-9ab9-7ef24d883235.png)

**Comment by 88250** [comment]
是否设置过环境变量 `NODE_ENV`？

**Comment by hwd-2020** [comment]
🤣，我都忘记了，你这一说我想起来了。👍已解决，非常感谢
![image](https://user-images.githubusercontent.com/65169631/100200850-2dec4680-2f3a-11eb-90d4-8b9ba8e6636b.png)

**Comment by 88250** [comment]
我关闭了，谢谢。
