### ISSUE TITLE
桌面端自动下载更新安装包

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5837]
* 增加选项 设置 - 关于 - 自动下载更新安装包，默认关闭
* 运行期间如果检查到有更新版本，则自动下载安装包并提示用户
* Windows 商店版不支持该功能

**Comment by choyy** [comment]
有个问题，开发者写挂件，如果还没推到集市，本地版本比集市版本高，但这时候也会显示更新按钮，如果自动更新的话就会覆盖了

**Comment by 88250** [comment]
@choyy 嗯，没有判断版本号高低，只是用  `!=`，因为版本号格式不一致，判断高低的话会有问题。

**Comment by choyy** [comment]
那就用个默认格式的版号判断下高低（比如0.0.1这样的用的最多），非默认格式的就直接用`!=`

**Comment by 88250** [comment]
要不直接字符串大小判断吧。

**Comment by choyy** [comment]
能判断都行👍

**Comment by 88250** [comment]
:art: 集市已下载包版本判断改为字符串大小比较 https://github.com/siyuan-note/siyuan/commit/c11ffd147f4b349bdbca005d8c06a74bb3b608c0

**Comment by lentikr** [comment]
> * 增加选项 设置 - 关于 - 自动下载更新安装包，默认开启
> * 运行期间如果检查到有更新版本，则自动下载安装包并提示用户

想问一下D大，如果是微软商店安装的思源，自动下载安装包后再安装是不是会重新安装一个新版的思源而不是把微软商店安装的思源更新了？这样的话可能对于微软商店下载思源的用户有些不合理。

**Comment by lentikr** [comment]
> @lentikr 商店版不会有这个选项

收到👍

**Comment by Zuoqiu-Yingyi** [comment]
> * 增加选项 设置 - 关于 - 自动下载更新安装包，默认开启

最好默认关闭, 我发现不少用户是用包管理器安装/更新~

**Comment by 88250** [comment]
嗯，先默认关闭，等稳定以后再考虑默认打开。
