### ISSUE TITLE
集市已下载栏异常

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#5838]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

集市已下载栏异常

现象：
点击主题更新按钮，下载转圈，（下载完成后？）更新按钮依旧显示，继续点击无反应

继续观察发现
主题栏和已下载栏的当前版本和右侧的主题详情显示也不一致

按我的理解
当前版本应该是已下载的版本，也许还可以显示多一个最新版本

### 期待的结果 Expected result

无

### 版本环境 Version environment

```markdown
- Version: v2.1.13
- Operating System: Windows 10/11
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9502629/siyuan.log)

**Comment by 88250** [comment]
请导出系统日志上传。

**Comment by Temacc0531** [comment]
日志已上传

**Comment by 88250** [comment]
应该是之前手动安装的主题配置文件有点问题，试下重新下载。

**Comment by 88250** [comment]
如果不是手动安装的，也是配置文件有问题，可能现在这个主题的配置已经好了，我这里测试正常。

**Comment by Temacc0531** [comment]
我在主题栏点击更新是正常的，但是已下载栏就不行

**Comment by 88250** [comment]
大概知道问题了，确实是主题配置文件 theme.json 的问题，里面的 URL 不是仓库 URL。

**Comment by 88250** [comment]
麻烦给主题仓库反馈一下，这里我先关闭了，谢谢。
