### ISSUE TITLE
打开引用文档的时候，希望可以自动左右分屏，方便对比查看。

### ISSUE THREAD

**Issue by xian54966** [siyuan-note/siyuan#584]
当使用Ctrl+链接方式打开引用的文档的时候，希望能够两篇文章自动分屏显示，这样方便查阅信息。
另外，行内代码块背景好像不能使用设置里的主题渲染，辨识度不高。

**Comment by 88250** [comment]
分屏打开已在 https://github.com/siyuan-note/siyuan/issues/500 中实现，请等待下个版本 v0.4.93 发布。

行内代码麻烦截个图说明一下，谢谢。

**Comment by 88250** [comment]
v0.4.93 已经发布，使用悬浮窗口按钮实现分屏：

![image](https://user-images.githubusercontent.com/873584/100409829-d2d86200-30a7-11eb-8c80-8f28395c84ce.png)

我关闭了，如果还有反馈请继续跟帖即可，谢谢。
