### ISSUE TITLE
希望提供阅读模式，以及灵活的默认模式配置功能

### ISSUE THREAD

**Issue by YangHgRi** [siyuan-note/siyuan#5842]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

读文档或看小说的时候需要哦

### 描述可能的最优解决方案 Describe the optimal solution

右上角提供两个半透明的图标，单击左边的是编辑模式，单击右边的是阅读模式，阅读模式不会有光标碍眼，而且可以搞一些方便阅读的样式，在应用设置中可以配置默认模式，如果能给记事本单独设置默认模式就更好了

**Comment by 88250** [comment]
Duplicate of #2648
