### ISSUE TITLE
题头图支持从已上传的题头图中选择

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5848]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

选择在其他文档中已经用过的题头图

### 描述可能的最优解决方案 Describe the optimal solution

略

**Comment by 88250** [comment]
这个目前不考虑支持，后续如果有更多该需求再考虑，谢谢。

**Comment by boryun** [comment]
挖个坟，请问能重新考虑一下这个需求吗，目前虽然支持手动上传题头图，但上传完的题头图是与其它资源文件混在一起的，如果想要重新复用比较麻烦（特别是资源文件很多的情况下），不知道能否增加一个题头图库（比如说与内置的题头图放在一起），允许用户直接将自定义的题头图上传到题头图库中，并且最好能放在本地单独的文件夹中而不是和资源文件共用的assets文件夹，这样很方便复用和管理，也不会在清理资源文件时由于暂时没有使用而被意外删除。

**Comment by 88250** [comment]
不考虑了，用资源搜索功能吧。
