### ISSUE TITLE
删除被引用块被删除时发出警告

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#585]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

有时候修改文档时不小心就删除了一个被其他地方引用的块，但只是想重构一下不想改变引用。

### 描述最优的解决方案 Describe the optimal solution

删除被引用块被删除时发出警告被引用块被删除时发出警告

**Comment by wo4wangle** [comment]
最好是能显示一下被引用的上下文
比如 列一下 引用的文件有哪些
或像搜索里面显示一下局部上下文
更方便快速的抉择删不删，或做其他的修改
比如知道了引用处，先把引用处 处理一下再删
不然删了一堆原文，留下一堆无效引用，原文也不在了，处理时候有些迷茫

**Comment by 88250** [comment]
v1.2.0 以后定义块会显示引用计数了，能够很直观看到。我关闭了，谢谢。

**Comment by 88250** [comment]
https://ld246.com/article/1627769638186
