### ISSUE TITLE
使用github图床，无法显示图片

### ISSUE THREAD

**Issue by dzhl** [siyuan-note/siyuan#5851]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

笔记中使用的是github图床，图片经常无法显示，比如插入的图片地址是https://github.com/dzhl/Picture/raw/master/0090779021e84a5381f1f690fab6422a.jpg

或者

https://cdn.jsdelivr.net/gh/dzhl/Picture@master/0090779021e84a5381f1f690fab6422a.jpg

这两个地址分别是原生地址和使用cdn后的地址，这两个地址无论是在浏览器还是其他笔记软件中都可以正常显示，但是插入到思源笔记中，多数情况下都显示不出来，这是怎么回事呢?有办法解决吗？

### 期待的结果 Expected result

正确显示github仓库中图片

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/47837136/189296714-885b0ca8-4da8-4920-b34f-4859d3f2f563.png)

### 版本环境 Version environment

```markdown
- Version: 2.1.7
- Operating System:  windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9533283/siyuan.log)

**Comment by 88250** [comment]
多半是因为网络问题，如果其他软件能够显示，建议先升级思源最新版以后再试试。

**Comment by 88250** [comment]
补充一下我这里的测试截图：

![image](https://user-images.githubusercontent.com/873584/189301734-98c654eb-5bdc-4ef3-aec4-44f3af2837e5.png)

**Comment by dzhl** [comment]
> 补充一下我这里的测试截图：
> 
> ![image](https://user-images.githubusercontent.com/873584/189301734-98c654eb-5bdc-4ef3-aec4-44f3af2837e5.png)

自己仓库里图片地址样式是这样的，
https://github.com/dzhl/Picture/raw/master/0090779021e84a5381f1f690fab6422a.jpg
或者
https://cdn.jsdelivr.net/gh/dzhl/Picture@master/0090779021e84a5381f1f690fab6422a.jpg
不是user-imgae开头，你试下我上面给的两个图片地址

**Comment by dzhl** [comment]
> 补充一下我这里的测试截图：
> 
> ![image](https://user-images.githubusercontent.com/873584/189301734-98c654eb-5bdc-4ef3-aec4-44f3af2837e5.png)

我安装的是最新版，并且这些图片在我电脑手机、其他笔记里都可以显示的

**Comment by dzhl** [comment]
@88250 试过我给的图片吗？

**Comment by 88250** [comment]
会报域名解析错误，不大清楚为啥。

![image](https://user-images.githubusercontent.com/873584/189307974-3472a6b3-e950-4ef1-b59c-993a4ea32732.png)

**Comment by dzhl** [comment]
> 会报域名解析错误，不大清楚为啥。
> 
> ![image](https://user-images.githubusercontent.com/873584/189307974-3472a6b3-e950-4ef1-b59c-993a4ea32732.png)

不知是否跟这个编辑器有关

**Comment by 88250** [comment]
应该没有关系

**Comment by dzhl** [comment]
那这个问题，会考虑解决吗？

**Comment by 88250** [comment]
这个应该不是思源的问题，我试了 Obsidian 和 Logseq 也是一样的表现。

**Comment by dzhl** [comment]
> Obsidian

我用notion或者joplin，typora都是这正常的啊

> https://cdn.jsdelivr.net/gh/dzhl/Picture@master/0090779021e84a5381f1f690fab6422a.jpg
不会啊，我用Obsidian是正常的，用joplin，notion，
![image](https://user-images.githubusercontent.com/47837136/189310109-1db40094-252d-47fe-bd15-6a15c0caafa1.png)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/189312095-4e21963c-efb1-4ae5-a16a-36a49c23b1b4.png)

**Comment by dzhl** [comment]
> https://github.com/dzhl/Picture/raw/master/0090779021e84a5381f1f690fab6422a.jpg

图片地址是https://github.com/dzhl/Picture/raw/master/0090779021e84a5381f1f690fab6422a.jpg，而不是raw开头

**Comment by 88250** [comment]
一样的结果：

![image](https://user-images.githubusercontent.com/873584/189314395-f6ef4d69-8ed7-42a4-9de0-e7be863af0e0.png)

**Comment by dzhl** [comment]
> 一样的结果：
> 
> ![image](https://user-images.githubusercontent.com/873584/189314395-f6ef4d69-8ed7-42a4-9de0-e7be863af0e0.png)
我这边是正常的，但就是在思源里不正常

**Comment by TCOTC** [comment]
现在24年了，我这里能显示

![image](https://github.com/siyuan-note/siyuan/assets/78434827/978a81cc-c5b1-446e-9127-a436a17d75b5)
