### ISSUE TITLE
在文档树添加快速访问入口

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5852]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

快速访问经常需要使用的文档。

### 描述可能的最优解决方案 Describe the optimal solution

在文档树中添加“快速访问”分组，类似现在有的“已关闭的笔记本”，并能够添加文档到快速访问分组中。

**Comment by woniuxia** [comment]
支持

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3293
