### ISSUE TITLE
外观模式支持跟随系统切换

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5854]
https://ld246.com/article/1662710907148

移除主界面顶栏上的切换按钮。

**Comment by Zuoqiu-Yingyi** [comment]
解决方案: 可以参考 [nativeTheme | Electron](https://www.electronjs.org/docs/latest/api/native-theme)

```js
const { nativeTheme } = require('electron');
nativeTheme.themeSource = 'system';
nativeTheme.shouldUseDarkColors; // 通过该 boolean 属性可以判断当前操作系统是否启用的暗色 UI
```

**Comment by aptexd** [comment]
还是不建议轻易移除常用功能的，最好向前兼容
等发布后肯定会有人提议加回来或加开关
再就笔记软件作为一个文字处理为主的软件
“在长时间写作时，在明亮系统中启用黑色主题”是个很正常的需求

**Comment by 88250** [comment]
@aptexd 放在主界面顶栏的话会有冲突，需要两个开关才能控制，所以只能移除了。考虑到跟随系统设置之后一般不会再切换为特定的模式，所以放到设置是比较合理的，其他带有该功能的软件基本也是这样设计的。

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 在移除主题模式切换功能时貌似也将 `#iconMoon` 图标移除了, 希望这些图标不要移除, 因为自定义主题引用了该图标~

**Comment by Vanessa219** [comment]
看看能不能在自定义 js 里面加一下吧。
