### ISSUE TITLE
应用闪退，打不开

### ISSUE THREAD

**Issue by Pauluooooo** [siyuan-note/siyuan#5855]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

安装 32 位，64 位，应用商店安装都不能打开，直接闪退，无任何提示。
第一次打开的时候是能显示欢迎界面的，然后我把数据文件夹选择在了 OneDrive 上就卡住了，之后打开就一直闪退

### 期待的结果 Expected result

能正常打开

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无，因为我没有创建工作空间

**Comment by 88250** [comment]
删除用户家目录配置文件夹 `C:\Users\用户名\.config\siyuan\` 后再启动。

PS：思源不支持使用第三方同步盘，否则会造成数据损坏。
