### ISSUE TITLE
Android 端启动打开白屏

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#5856]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

一开始更新2.1.14后，启动加载界面卡在获取一个最新索引块什么的，然后彻底不动，没截图。
因为最新的数据在PC端，而PC端一切正常，我就把PC端数据备份了一下直接把Android端卸载了重装2.1.14，结果后面不管我怎么重新打开启动都是没法正常启动。
截屏为多次关闭打开后可能出现的四种情况，随机循环出现。

### 期待的结果 Expected result

...

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Screenshot_2022-09-10-00-04-08-025_org b3log siyu](https://user-images.githubusercontent.com/98400319/189394411-9a8d8016-8b12-4844-b9e3-4c1c9b91aac3.jpg)
![Screenshot_2022-09-10-00-05-30-380_org b3log siyu](https://user-images.githubusercontent.com/98400319/189394426-f74708ad-8f7a-451e-bdc2-bbce196b3555.jpg)
![Screenshot_2022-09-10-00-05-51-168_org b3log siyu](https://user-images.githubusercontent.com/98400319/189394436-efaab895-da05-455a-94e4-9a28606aff9b.jpg)
![Screenshot_2022-09-10-00-06-16-712_org b3log siyu](https://user-images.githubusercontent.com/98400319/189394442-637c3d55-3d97-4163-b0d5-e04527a75531.jpg)

### 版本环境 Version environment

```markdown
- Version: 2.1.14
- Operating System: 手机型号：Redmi K30 Ultra/MIUI 13.0.3/Android 12
- Browser (if used):
```

### 日志文件 Log file

卸载后没了捏，sorry。

**Comment by EberhardLin** [comment]
感觉现在PC端已经一骑绝尘了，移动端能不能跟上呀！

**Comment by EberhardLin** [comment]
表述有误，后续打开基本都是第四张截屏，直接白屏的情况。

**Comment by 88250** [comment]
网络有开 VPN 或者代理之类的软件吗？

**Comment by EberhardLin** [comment]
> 网络有开 VPN 或者代理之类的软件吗？

没有的。另外在家用WIFI和移动网络的情况下都测试过，都打不开。

**Comment by 88250** [comment]
试下复制日志文件上传，路径在内部存储/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.log

**Comment by EberhardLin** [comment]
> 试下复制日志文件上传，路径在内部存储/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9540469/siyuan.log)

**Comment by 88250** [comment]
内核进程应该没问题，可能还是本地网络原因，看下是否是没有给网络权限？

**Comment by EberhardLin** [comment]
> 内核进程应该没问题，可能还是本地网络原因，看下是否是没有给网络权限？

![IMG_20220910_214528](https://user-images.githubusercontent.com/98400319/189486217-0e5251ef-0e5c-438f-a704-7f53885ac1c2.jpg)
联网权限是正常的

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/189486264-721e0a8a-cd06-4625-a068-9a76fb37e4f9.png)

这个里面有哪些权限？

**Comment by EberhardLin** [comment]
> ![image](https://user-images.githubusercontent.com/873584/189486264-721e0a8a-cd06-4625-a068-9a76fb37e4f9.png)
> 
> 这个里面有哪些权限？

![1662817800755](https://user-images.githubusercontent.com/98400319/189486397-385b56a1-0c11-42cb-91af-5c4bc9b31914.jpg)

**Comment by 88250** [comment]
暂时定位不到问题，先保持 issue 打开看下是否有更多人遇到，谢谢。

**Comment by EberhardLin** [comment]
> 暂时定位不到问题，先保持 issue 打开看下是否有更多人遇到，谢谢。

我想测试一下2.1.13，但是我记得2.1.13是不是有打包错误的问题？

**Comment by 88250** [comment]
是的，v2.1.13 前端资源打包有问题，可以试下 v2.1.12。

**Comment by EberhardLin** [comment]
> 是的，v2.1.13 前端资源打包有问题，可以试下 v2.1.12。

2.1.12也无法正常启动，极有可能是手机问题。
[siyuan(1).log](https://github.com/siyuan-note/siyuan/files/9540519/siyuan.1.log)
日志发你，但是我记得2.1.13我是能打开的，现在不知道出什么问题了，后面我再把手机格式化看看，如果还不行就有可能是系统本身的问题了。

**Comment by EberhardLin** [comment]
早上突发奇想，卸载了思源后重启手机，又重下安装包，现在可以正常启动与使用了。

**Comment by 88250** [comment]
那先这样吧，我关闭了，谢谢。
