### ISSUE TITLE
功能建议：常驻搜索面板

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#586]
### 一、功能简单描述

- 增加一个像文件树、大纲一样的常驻搜索面板，该面板自身具有搜索框，搜索结果列表一直展示
- 展示的搜索结果可以选择按文件展示（不仅仅是按块展示）

一个性价比很高的功能。

### 二、使用场景分析

搜索和跳转并不是完全等同的，即使在 workflowy 这种大纲编辑器里，对这两个场景也有明确区分。在 workflowy 中，搜索界面会展示所有匹配的结果，并且可以对结果页面的所有文字进行直接编辑。而在「搜索=跳转」思源笔记中，假设用户对 10 处搜索结果中的 4 处进行编辑（不一定是编辑匹配到的文字本身），那么在整个过程中需要反复呼出 4 次跳转面板。

对真正体现了 zettlekasten 精神的 zettlr 来说，常驻的搜索结果列表是其最核心的功能， zettlr 把搜索框的作用挖掘到了极致：

![image](https://user-images.githubusercontent.com/32661922/100241866-23986f80-2f6f-11eb-89b3-dd73c743f87d.png)

常驻搜索结果列表的好处在于，它可以持续展示跟某一主题（该主题由正则搜索文本来体现）相关的全部内容，zettlr 甚至还用 heatmap 来从颜色上直接体现关键词的出现频次。在这种主题列表里，用户无需反复呼出搜索界面就可以在结果之间来回跳转、并对每个文件进行编辑。根据主题来聚合内容是卡片式写作的核心，真正复杂的卡片式写作必定是主题导向、而不是结构导向的。多数人可能感受不到，如果真的在平时积累了海量的元信息卡片，到了输出写作的时候只有主题聚合能派上用场。传统树状结构、双向链接、网状视图这些结构导向的方法在轻度使用的时候很舒适，但是在需要整理海量素材并输出的时候全都捉襟见肘。

细节补充：需要按文件展示的原因是，有时关键词在某个文件中出现的频率很高，如果只按块来展示，可能一屏甚至两屏都是这一个文件里的结果。

**Comment by 88250** [comment]
感谢提议，之前有过一点点搜索页签的考虑 https://github.com/siyuan-note/siyuan/issues/104 

我们看的产品太少了，主要还是根据自己的想象在做，有很多考虑不周之处。后面会结合大家的建议进行构思，也会参考其他产品的设计，尽量不偏离思源的核心。

实现方面估计要过一久才能安排上了，谢谢。

**Comment by deerainw** [comment]
@88250 

我觉得恰恰是因为没有看过太多的产品，才能不受传统思路的束缚。比如思源的块引用实现方式以前我也想到过，但心里一直觉得没有人会愿意做这种事，直到思源真的这么做了，有一种冲破乌云的感觉。

我自己深度使用过世界上几乎所有的笔记软件和写作软件，也写一点这方面的评测文章，思源是我心目中最有潜力的产品，
，我很愿意提供一些拙见，如果有讨论需要可随时加个微信：553459057

**Comment by 88250** [comment]
你好，我关闭 issue 了，后续在 #104 中计划，谢谢。
