### ISSUE TITLE
[建议] 使用搜索功能时，相同文件在视觉上缩进展示

### ISSUE THREAD

**Issue by Otto-J** [siyuan-note/siyuan#5860]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

使用搜索时候，如果一篇文章多次命中结果，希望在视觉上能看出来，比如使用相同的缩进，相同的背景色做标识。

下图红框里一篇文章命中了多次关键词，希望收拢到一起，看起来清晰

![image](https://user-images.githubusercontent.com/9958583/189472852-3cf8f7d5-c163-43d0-846c-d379010b2fc6.png)

### 描述可能的最优解决方案 Describe the optimal solution

视觉上更一致，一篇文章可以展开收起，缩进，提供颜色标识

### 描述候选的解决方案 Describe the candidate solution

我觉得缩进时最方便的

### 其他信息 Other information

当前版本 v2.1.12
主题 亮色 rem craft

**Comment by 88250** [comment]
Duplicate of #4772
