### ISSUE TITLE
使用 API `setBlockAttrs` 设置文档块属性后未更新文档 DOM 属性

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#5867]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在解析 `action: "updateAttrs"` 的 `Transaction` 消息时未区分文档块与非文档块

### 期待的结果 Expected result

使用 API `setBlockAttrs` 设置文档块属性后更新文档 DOM 属性

### 版本环境 Version environment

```markdown
- Version: 2.1.14
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5866
