### ISSUE TITLE
更新到2.1.14之后，文章页面没有了之前那样撑满整个页面的样式了

### ISSUE THREAD

**Issue by Light0457** [siyuan-note/siyuan#5868]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

之前的版本都是有撑满页面的样式的，很多笔记也是根据那样子来排版布局的。一缩小全都乱了。
![image](https://user-images.githubusercontent.com/6023553/189535656-121dd753-9999-4523-86cf-8aa423f80b18.png)

### 描述可能的最优解决方案 Describe the optimal solution

重新支持之前的样式，按个人喜好设置。不然原来喜欢宽屏的用户，笔记就跟毁了一样.
![image](https://user-images.githubusercontent.com/6023553/189535720-eb00471e-1676-41bd-a78c-456f32fc35f2.png)

**Comment by netdog2019** [comment]
没有打开“自适应宽度”的选项吧？设置-编辑器-自适应宽度。
