### ISSUE TITLE
新增默认打开为阅读模式的需求

### ISSUE THREAD

**Issue by Amwsup** [siyuan-note/siyuan#587]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
**答：**
- 功能一

> 场景一：打开文章，可能并不是为了修改，只是为了阅读某些资料。如果进去就是编辑模式，可能勿修改。
>场景二：文章存在附件，比如pdf的时候，若一进去就是编辑模式，无法直接打开附件。

- 功能二

> 为减少预览开销

- 功能三

> 打开图片，直接在当前页，而不是在新标签页打开？

![image](https://user-images.githubusercontent.com/74750630/100320498-3442f700-2ffc-11eb-9ac1-b4aff0f430f8.png)

### 描述最优的解决方案 Describe the optimal solution
**答：**
- 功能一方案：

> 	建议在设置界面增加，打开文档的默认选项：1-编辑模式 2-阅读模式(就是点那个预览的功能)，
> 	用户根据自己需要进行设置

- 功能二方案：

> 	预览模式的Desktop/ Tablet/ Mobile 是不是放到设置里面增加可选好点，
> 	比如某些用户只勾选了Desktop，另外两个就无需生成。
> 	某些用户需要都预览，那就都勾选。

**Comment by 88250** [comment]
直接预览可在文件树上右键选择：

![image](https://user-images.githubusercontent.com/873584/100329930-45463500-3009-11eb-8f3c-17e73ed59288.png)

**Comment by Amwsup** [comment]
> 直接预览可在文件树上右键选择：

> ![image](https://user-images.githubusercontent.com/873584/100329930-45463500-3009-11eb-8f3c-17e73ed59288.png)

好的，谢谢回答。
之所以有这个**功能一**建议，之前用过语雀，都是进去就是阅读，有个编辑按钮。

> 能否改成默认预览（放到设置中，可选模式呗，应该改动不大吧），把这个右键“预览”换成 右键“编辑”，哈哈。**比如还在构思怎么写，敲错都很难发现**。

但这个预览不知道是不是Desktop/ Tablet/ Mobile模式都预览，每次进去有点慢，随着文章长了，更慢。所以有了**功能二**的建议

**Comment by 88250** [comment]
那三个预览模式和性能关系不大，后续会尽量进行性能优化。笔记的话主要还是编辑，设置里如果统一设置其实也不方便的。

我关闭 issue 了，谢谢。
