### ISSUE TITLE
增加一点基础的vim操作，类似Obsidian

### ISSUE THREAD

**Issue by fc470505146** [siyuan-note/siyuan#5871]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

多数情况

### 描述可能的最优解决方案 Describe the optimal solution

Obsidian

**Comment by 88250** [comment]
这个实现不了。

* https://github.com/siyuan-note/siyuan/issues/1996
* https://github.com/siyuan-note/siyuan/issues/5578

**Comment by A15803** [comment]
参考vimium试一下
