### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#5872]
上架 F-Droid

### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如题

### 描述可能的最优解决方案 Describe the optimal solution

如题

### 描述候选的解决方案 Describe the candidate solution

[F-Droid - Free and Open Source Android App Repository](  https://f-droid.org/  )    
F-Droid 是一个 Android 平台上 FOSS（Free and Open Source Software，自由开源软件）的目录，并提供下载安装支持。使用客户端可以更轻松地浏览、安装及跟进设备上的应用更新。

刚刚看到这个，感觉思源笔记完全符合，可以考虑一下

**Comment by linsui** [comment]
@88250 那思源笔记是否同意发布呢？

**Comment by 88250** [comment]
@linsui 同意的，但请基于官方库代码和 release，不要基于其他 fork，谢谢。

**Comment by linsui** [comment]
好的，我稍后有时间会试试。

**Comment by linsui** [comment]
久等了 :joy: @88250 构建成功，运行也看起来没什么问题。现在还需要

1. 在 https://github.com/siyuan-note/siyuan-android 仓库里添加应用描述等元数据，我可以开个 PR
2. https://github.com/siyuan-note/siyuan-android 每个版本打 tag 才能自动更新

**Comment by 88250** [comment]
好的，麻烦 PR。另外，tag 的格式是否有要求，如果有的话麻烦描述一下，谢谢。

**Comment by linsui** [comment]
https://github.com/siyuan-note/siyuan-android/pull/11/files

tag 格式没有要求。

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14431 麻烦检查一下作者信息之类的有没有问题。构建失败是 https://github.com/siyuan-note/siyuan-android/commit/e10cf56773fd15c7e6d4c7fdcc3de804a98ed8f6 导致的。

**Comment by 88250** [comment]
信息没有问题。构建失败可能是因为 kernel 更新代码目前还没有合并到 master 分支导致的，稍后发版会合并，等合并后麻烦再试试。

**Comment by linsui** [comment]
MR 已合并，大概会在一周内发布。@88250 感谢帮助！

**Comment by 88250** [comment]
@linsui 再和你确认下，以后发布新版本后我只需要在 siyuan-note/siyuan-android 仓库上打 tag 就可以了吗？

**Comment by 88250** [comment]
好的，多谢了 🙏

**Comment by 88250** [comment]
你好，我注意到最近一个月 siyuan 没有构建 f-droid 新版发布，请问如何追踪定位这个问题？

**Comment by linsui** [comment]
https://github.com/siyuan-note/siyuan-android/pull/18 versionName 和 versionCode 不在默认位置所以要改一下更新检查配置。我应该用哪个 flavor？

**Comment by 88250** [comment]
在 /build.gradle 文件中配置的，请看下 [README 多渠道分发](https://github.com/siyuan-note/siyuan-android/blob/main/README_zh_CN.md#%E5%85%B3%E4%BA%8E%E5%A4%9A%E6%B8%A0%E9%81%93%E8%BD%AF%E4%BB%B6%E5%88%86%E5%8F%91) 是否能解决问题，渠道名称使用 `official`

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15142 更新了 :ok_hand:

**Comment by 88250** [comment]
多谢，辛苦了 🙏

**Comment by Integral-Tech** [comment]
@linsui  It seems that only `arm64-v8a` build is available on [F-Droid](https://f-droid.org/packages/org.b3log.siyuan).
Would you like to provide build for `x86_64`, which would make Android x86 and [Waydroid](https://waydro.id) users easier to use?

**Comment by linsui** [comment]
If the dev can set different version codes for different abis then we can add more abis.

**Comment by Integral-Tech** [comment]
@88250 Could you please add x86_64 support to Siyuan? It seems the Siyuan Android client depends on a native library to build.

**Comment by 88250** [comment]
@linsui 我不太熟悉 F-Droid 的构建过程，如果只是编译内核的话只需要将 `-target=android/arm64` 改为 `-target=android/amd64` 应该就可以了，你那边能否帮忙 PR 一下？

**Comment by linsui** [comment]
编译内核没问题，但要发布多个 abi 需要每个 abi 有不一样的 version code，比如 arm64 是 2762，x86_64 是 2764。

**Comment by 88250** [comment]
@linsui 好像可以都打在一个发布包里？不过即使可以的话发布包会变大很多。amd64 的需求目前看不是太多，并且该平台已经逐渐被手机厂商淘汰，所以还是不考虑支持了，感谢讨论。

@Integral-Tech

**Comment by Integral-Tech** [comment]
@88250 OK 👌
