### ISSUE TITLE
不再支持通过 HTML `<kbd>` 和 `<u>` 输入键盘和下划线元素

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5877]

**Comment by Zuoqiu-Yingyi** [comment]
`<kbd></kbd>` 和 `<u></u>` 有什么缺陷吗, 删除后之前的笔记不太好迁移😭

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 直接用 HTML 的话语法解析会有比较多的问题，且不是大众用户的用法，所以我们不再支持了。新版编辑器行级元素都是使用 `<span>` 标签，对于旧版渲染依旧支持，这点目前还在开发测试兼容性。
