### ISSUE TITLE
引述块中的标题无法被大纲识别

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#5878]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem
现在引述块中的标题块无法被大纲识别，我看到帮助文档中的【请从这里开始】页面用的合并超级块的方式，那超级块中的标题是能被大纲识别的。

但实际使用的时候，个人觉得将引述块作为容器，直接拖拽横排的方式比那种  先单独合并超级块（并指定布局方式）——选中多个超级快——点击打开菜单——点击菜单中【合并超级块】的水平布局  的方式更直观，体验更好。

希望能大纲能识别到引述块中的标题块。

### 期待的结果 Expected result

大纲能识别到引述块中的标题块。

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/58081876/190069673-6879f016-0692-4bb0-aa55-e2877fbffcd4.mp4

### 版本环境 Version environment

```markdown
- Version: 2.1.14
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
这个是设计如此，因为引述块中的内容一般不是本文档的大纲，所以特意不纳入的，感谢反馈。
