### ISSUE TITLE
预览时图片等附件资源链接错误

### ISSUE THREAD

**Issue by Amwsup** [siyuan-note/siyuan#588]
### 描述问题 Describe the problem

**答：**
1.上传名称中有空格的附件，[shell.pdf](assets/20201126150150-37lk8p2-shell .pdf)，路径带空格，导致无效

2. 浏览器中打开预览模式点击附件，比如ini、pdf，可能生成的路径为
http://127.0.0.1:6806/127.0.0.1:6806/siyuan/siyuan/%E6%8A%80%E6%9C%AF/assets/20201126150823-4a3m1hw-shell.pdf  存在两个http://127.0.0.1:6806/ ，导致找不到实际文件

3. 浏览器中打开预览模式点击附件，是在当前标签页打开，建议改成在新标签页打开，不然看完了，回退后看文章其他内容（有时打开只是阅读，不是编辑，见需求#587）还得再次点预览，造成资源消耗

4. 客户端以及浏览器中打开，无论预览模式还是非预览模式，到处pdf，都是代码模式，而不是所见的文章模式
- 文章
-  ![image](https://user-images.githubusercontent.com/74750630/100319815-39ec0d00-2ffb-11eb-819c-d78885da12ee.png)
- 生成
- ![image](https://user-images.githubusercontent.com/74750630/100319840-46706580-2ffb-11eb-83fd-8edfbb237113.png)

### 期待的结果 Expected result
1. 兼容带空格的文件上传
2. 浏览器路径避免两个IP和port
3. 在新标签页打开附件，比如ini、txt、pdf
4. 完善pdf导出

### 版本环境 Version environment

* 版本 Version：siyuan-0.4.92-win.exe
* 操作系统 Operating system：Windows 10
* 浏览器（如果使用）Browser (if used)：新Microsoft Edge

**Comment by 88250** [comment]
1. 带空格的路径支持需要打开这个选项：设置 - 编辑器 - 支持带空格的图片链接路径
2. 预览时路径错误的问题下个版本修复
3. 这个估计需要手动按着 Ctrl 打开链接，如果默认新页签开的话可能不是所有人都需要
4. PDF 导出请关注 https://github.com/siyuan-note/siyuan/issues/79

感谢反馈。
