### ISSUE TITLE
无法创建日记

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#5885]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

问题:无法创建日记
问题复现:建议看下方视频
1.在特定文件夹创建日记    2.数据快照回滚,回滚到创建日记前
3.再次创建日记,失败         4.关闭应用后重新打开,再次创建日记,失败

### 期待的结果 Expected result

解决问题

### 截屏或者录屏演示 Screenshot or screen recording presentation

「2022-09-15 09-05-50.mp4」
https://www.aliyundrive.com/s/eFN3CDmBJqM
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

### 版本环境 Version environment

```markdown
- Version: v2.1.13(tip:最新版本也没有说解决了这个问题)
- Operating System: 微软11  22H2
- Browser (if used):
```

### 日志文件 Log file

[Uploading system-log.zip…]()

**Comment by 88250** [comment]
请重新上传一下系统日志。

**Comment by linglongyoudoufu** [comment]
[app.log](https://github.com/siyuan-note/siyuan/files/9571038/app.log)
[siyuan.log](https://github.com/siyuan-note/siyuan/files/9571039/siyuan.log)

**Comment by linglongyoudoufu** [comment]
> 请重新上传一下系统日志。

上传了

**Comment by 88250** [comment]
从日志上看是这个路径缺失了文件：

```
load tree [20220501225752-e346nd0/20220501225837-3xjqtjt/20220501225837-spbvjul/20220914085800-benl3ru/20220915085528-uadmgan.sy] failed: file does not exist
```

试下在文件系统上看看这个路径的文件结构。

**Comment by 88250** [comment]
如果还没有解决并方便的话请把 data 打包（去掉 assets）发给我们 845765@qq.com 

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
