### ISSUE TITLE
思源笔记打不开

### ISSUE THREAD

**Issue by wanguano** [siyuan-note/siyuan#5886]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

window11系统专业版, 21H2
思源笔记: 我测试了最新的两个版本, 均按照知之后只在任务栏显示, 但是点击该图标什么都不显示, 打不开此软件(只在任务栏有图标显示，任务栏缩略图也有显示)

### 期待的结果 Expected result

希望可以运行打开此页面

### 截屏或者录屏演示 Screenshot or screen recording presentation

![](https://cdn.jsdelivr.net/gh/wanguano/cloudPic/img/siyuan.gif)

### 版本环境 Version environment

```markdown
- Version: 2.34.1和2.34.2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by wanguano** [comment]
https://cdn.jsdelivr.net/gh/wanguano/cloudPic/img/siyuan.gif

**Comment by 88250** [comment]
可以试下删除用户家目录/.config/siyuan/ 文件夹后再启动。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by 88250** [comment]
对了，如果有杀毒软件或者防火墙的话可能需要加一下信任列表白名单。

**Comment by wanguano** [comment]
> 

删除了/.config/siyuan/ 文件夹并且windows defender添加信任列表了, 还是打不开和原来一样

**Comment by 88250** [comment]
看下工作空间/temp/下是否生成了 siyuan.log 日志文件，默认的工作空间在我的文档 Documents 下。

**Comment by wanguano** [comment]
> 看下工作空间/temp/下是否生成了 siyuan.log 日志文件，默认的工作空间在我的文档 Documents 下。

在我的文档搜不到该文件, 我刚才用微软"疑难解答"运行该软件, 显示不兼容此软件, 难道window11系统都用不了吗?

**Comment by wanguano** [comment]
> Win7-Win11 都可以用的，但是你的系统上用不了我不太清楚原因，抱歉抱歉。

好吧😥

**Comment by tudou7990** [comment]
我的也出现了这种情况，好多个最新版本都无法显示，黑屏用不了

**Comment by Chellane** [comment]
Linux版本，今天打开思源笔记的时候，一直没反应，查找了下siyuan.log日志，没有今天的日志。
按照上面的方法，删除了~/.config/siyaun/文件夹，也是没啥作用，重启了电脑，仍然打不开，下载了最新版本的AppImage也是无济于事，咋办？

**Comment by Chellane** [comment]
> 看下工作空间/temp/下是否生成了 siyuan.log 日志文件，默认的工作空间在我的文档 Documents 下。

Linux版本，今天打开思源笔记的时候，一直没反应，查找了下siyuan.log日志，没有今天的日志。
按照上面的方法，删除了~/.config/siyaun/文件夹，也是没啥作用，重启了电脑，仍然打不开，下载了最新版本的AppImage也是无济于事，咋办？

**Comment by 88250** [comment]
@Chellane 使用 tar.gz 版本看看，在命令行下启动看看输出。

**Comment by Chellane** [comment]
> @Chellane 使用 tar.gz 版本看看，在命令行下启动看看输出。
下午定位了下，应该是AppImage所依赖的包不小心被卸载了，执行命令：sudo apt install libfuse2，安装好libfuse包即可正常打开AppImage文件。
感谢D大~
