### ISSUE TITLE
可以任意拖拽移动块吗？

### ISSUE THREAD

**Issue by better319** [siyuan-note/siyuan#5888]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

类似word中的插入图片或插入文本框，可以选择为悬浮，然后可以任意移动位置。

### 描述可能的最优解决方案 Describe the optimal solution

html 代码
<float>悬浮的文本内容</float>

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/2955

**Comment by better319** [comment]
可能我描述的不太清楚，有没有生成多个竖向列的功能。下面这个图是flow的图
https://imgse.com/i/vzNYkt

https://imgse.com/i/vzNttP

**Comment by 88250** [comment]
用户指南中搜索 `超级块`

**Comment by better319** [comment]
谢谢
