### ISSUE TITLE
偶发编辑文档标题后引用处的动态锚文本不更新

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#5891]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

这个问题为偶发，无法每次都复现，但是当目录页面的链接特别多的时候，体感触发概率会高一点

1. 使用`((AAAA`在目录页面下创建新页面，得到引用标题AAAA
2. 进入新创建的页面，修改标题BBBBAAAA
3. 进入目录页面，发现该链接显示的问题卡在了某个编辑标题时的中间状态BBAAAA
4. 尝试更新：
    1. 确认锚文本为空
    2. F5刷新没有用
    3. 重建索引没有用
5. 在下面重开一行，引用该新建的页面，显示正常，但之前的还是无法更新
6. 再次修改页面标题BBBBCCAAAA，两个引用都能成功更新

### 期待的结果 Expected result

虽然可以通过修改标题再改回来进行更新，但是总感觉是否为缓存的问题导致卡住无法更新？希望可以提供一个锚文本强制刷新的方法

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/19968935/190541467-433d2c7c-f6d7-465d-83d5-2aa65c2a98f7.png">

### 版本环境 Version environment

```markdown
- Version: 2.1.14
- Operating System: Win11
- Browser (if used): Edge
```

### 日志文件 Log file

Not applicable

**Comment by 88250** [comment]
这个问题估计还需要再帮忙留意一下重现步骤，感谢。

**Comment by 88250** [comment]
找到一个重现场景，在修改定义文档标题后迅速持续编辑引用所在块，这样会导致编辑操作覆盖更新的动态锚文本。
