### ISSUE TITLE
支持通过网络添加表情图标

### ISSUE THREAD

**Issue by jpanda-cn** [siyuan-note/siyuan#5897]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在现有的基础上，如果想要为文档添加**自定义图标**，需要经过下面几个步骤：

1. 从网络下载图标到本地emojis目录下
2. 进入设置->外观->刷新自定义表情
3. 为文档添加图标

如果可以提供类似**题头图**这种直接基于链接导入的题头图的方法，将大大减少这一过程。

### 描述可能的最优解决方案 Describe the optimal solution

从元素上来看，emoji是直接引用的具体地址：
<img width="625" alt="image" src="https://user-images.githubusercontent.com/50101020/190836710-bd83c7c3-f644-47b0-93eb-a12a8f2716a5.png">

那么直接将使用网络图片作为图标的基础是存在的，现在需要手动刷新自定义表情原因可能是： 选择图标面板中的数据是经过缓存的，且没有对应的API可以操作该缓存。

不过，单从使用角度上来看，通过url添加的图标往往是具有针对性的：
-  通常来说，该图标仅会用于当前文档，用户能够感知到该图标是一个网络图片，所以对无法在图标列表中找到该图标是有预期的。

## 比较合理的解决方案是：
1. 交互方面emoji选择面板： 新增：**上传**和**输入网络图片地址**，比如notion：
    <img width="621" alt="image" src="https://user-images.githubusercontent.com/50101020/190837190-bda15825-b435-4abd-9407-096c779985d6.png">
    当然，也可以简化该操作，直接提供一个粘贴窗口和上传按钮，根据粘贴文件的MIME来区分用户提供的URL还是图片
2. golang后端提供API，保存emoji，并刷新缓存（需要的话）
3.前端刷新缓存（ 需要的话）

## 比较快速的解决方案
1. 交互方面emoji选择面板： 新增：**输入网络图片地址**。
2. 将文件保存在emojis目录下，或者直接引用网络图片地址
3. 应用该图标

**Comment by 88250** [comment]
自动上传 Emoji 可能有个问题就是文件名是用于搜索的，一般截图或者网络链接图片的文件名都比较随意（或是自动生成的），这样会导致后面通过 `:名称` 进行搜索时出现很多干扰，所以暂时还是不考虑加入网络添加 Emoji 的入口了，感谢提议。
