### ISSUE TITLE
export siyuan notebook to HTML

### ISSUE THREAD

**Issue by wylited** [siyuan-note/siyuan#5899]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

This would make it easier for me to share my notes on siyuan to other people. I could export an entire notebook to html and make it viewable on that.

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/44154103/190843786-09b8f615-d463-4ce3-8f39-f7b0832a1ee5.png)
An HTML option gets updated here. Which provides a bundle using all the required files like HTML, CSS, Javascript.
Like the web client SiYuan can provide http://127.0.0.1:6806/stage/build/desktop/?r=gt4cvb5, without the option to edit the files.

### 其他信息 Other information

sorry, I do not understand chinese very well so there may be some communication issues.

**Comment by 88250** [comment]
Hello, this is a reasonable proposal, but considering that there are many higher-priority tasks that need to be completed, we will close this proposal first. If more users need it in the future, we will adjust the task priority. Thank you for your understanding and support. .
