### ISSUE TITLE
Android 平板无法导出 data

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#5907]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

1.  平板上无法导出data，但是进入浏览器可以，应该是bug，我导出系统日志的话它是能跳转到浏览器下载的，导出data不行
2. 平板上无法拖动，是不支持吗？（望支持）
3. 有时候将块内的内容删除干净时，光标会消失，软键盘会收起，影响输入

### 期待的结果 Expected result

无

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

```markdown
- Version: 2.1.14
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by 88250** [comment]
导出 Data 时有切换应用或者放入后台吗？

其他问题短期内无法改进了，按目前进度看最快估计也要明年下半年才会有开始考虑，抱歉。

**Comment by TinkMingKing** [comment]
没有切换或放后台，东西少只有几十mb，浏览器秒出，app点击后显示导出中，读完条就没反应了

**Comment by Vanessa219** [comment]
是 Android 还是 iPad？

**Comment by TinkMingKing** [comment]
android

**Comment by 88250** [comment]
麻烦再测试一下导出 data，然后不行的话导出上传一下系统日志。

**Comment by TinkMingKing** [comment]
启动，导出几次，关闭，重复了几次操作，你看看![siyuan.jpg](https://user-images.githubusercontent.com/32903588/191498645-c2563de7-afa7-481b-a19a-67852d4188b6.jpg)
手机上不能传文件我改jpg了

**Comment by 88250** [comment]
内核日志没有问题，估计还是弹出浏览器的地方有点问题，我这里在小米手机上导出 Data 倒是正常。

PS：升级内测版 a3

**Comment by TinkMingKing** [comment]
我在小米平板上测试的
日志能正常导出跳转浏览器下载
就是data不行
但是在浏览器里行

**Comment by 88250** [comment]
估计暂时无法定位了，先保持 issue 打开，看看有没有其他人遇到这个问题。

**Comment by TinkMingKing** [comment]
> 估计暂时无法定位了，先保持 issue 打开，看看有没有其他人遇到这个问题。

![Screenshot_2022-09-28-17-41-15-955_com tencent mobileqq](https://user-images.githubusercontent.com/32903588/192747176-e734a3a3-ddd9-42d7-a6a3-0b0e1016683a.jpg)

频道里有人遇到了

**Comment by 88250** [comment]
这个问题现在还能重现吗？之前的版本我记得我们改过一下跳转浏览器的实现。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
