### ISSUE TITLE
动态描文本鼠标进入刷新

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#5909]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候，不知道什么情况的缘故，动态描文本没有刷新

### 描述可能的最优解决方案 Describe the optimal solution

鼠标进入刷新一次

**Comment by 88250** [comment]
估计得帮忙留意一下原因，暂时不考虑增加修正方式，谢谢。

https://github.com/siyuan-note/siyuan/issues/5891
