### ISSUE TITLE
列表项不在末尾无法删除

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#591]
### 描述问题 Describe the problem
对于不在末尾的列表项，无法删除。比如我想删除b但保留acd，但思源做不到。

### 期待的结果 Expected result

![typora](https://user-images.githubusercontent.com/16791452/100499119-fd0e4a80-31a1-11eb-9c83-fe9825c186f2.gif)

### 截屏或录像 Screenshot or video

![siyuan](https://user-images.githubusercontent.com/16791452/100499125-04cdef00-31a2-11eb-9258-a94c003b23c9.gif)

### 版本环境 Version environment

* 版本 Version：0.4.93
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by frankli998** [comment]
虽然可以换到上一行然后再delete键删除，但这样感觉有点反直觉。。。

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/100533381-9db24800-323e-11eb-80a3-b8669be98a7e.gif)


这样删……
