### ISSUE TITLE
关于edge不能满屏的原因，能否更改一下?

### ISSUE THREAD

**Issue by jllmh1987** [siyuan-note/siyuan#5910]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

edge不能满屏，因为最后一个<div>里的<iframe>style="visibility:hidden",edge里不显示但占位置，能不能改成 display:none，或者给这个<iframe>一个id,在主题里可以自定义？
![image](https://user-images.githubusercontent.com/70119434/191050155-c5635643-529a-49d0-9028-a5377e092343.png)

### 期待的结果 Expected result

改成 display:none，或者给这个<iframe>一个id,在主题里可以自定义？
![image](https://user-images.githubusercontent.com/70119434/191050717-08e6149c-4b18-4157-b2da-bc3aed78b682.png)

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/70119434/191050155-c5635643-529a-49d0-9028-a5377e092343.png)

### 版本环境 Version environment

```markdown
- Version: v2.1.14
- Operating System: windows
- Browser (if used):edge
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
这个位置应该不是思源插入的 iframe 吧。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
