### ISSUE TITLE
思源笔记登录授权码怎么获得呢？

### ISSUE THREAD

**Issue by Fire-fier** [siyuan-note/siyuan#5915]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

思源笔记登录授权码怎么获得呢？

### 期待的结果 Expected result

Guide me how to get the auth code for Siyuan Note

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

**

**Comment by 88250** [comment]
如果是访问授权码的话可以在工作空间/conf/conf.json 中搜索 accessAuthCode；如果是端到端密码的话可参考帮助文档常见问题重置。
