### ISSUE TITLE
同文档块引转脚注缩略定义考虑标题块

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#5917]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前导出文档时，文档中所引用其他的内容块会以脚注的形式添加到导出的文件中，很不错。

但是如果文档内部有自我引用，如 Section-3 引用 Section-1，则也会把 Section-1 在脚注中重复一遍。有时引用一个大的章节，使得导出的 PDF 多很多页。

希望文内引用能够直接变成 `#id` 的链接跳转，而不是脚注。

### 描述可能的最优解决方案 Describe the optimal solution

如上

**Comment by 88250** [comment]
引用统一转换为脚注比较好，因为定义块可能还有引用，这些情况如果不统一处理为引用转换脚注的话会比较混乱。

对于同一篇文档中引用大段内容，之前已经做过缩略处理了 https://github.com/siyuan-note/siyuan/issues/3299

**Comment by mlzxy** [comment]
> 引用统一转换为脚注比较好，因为定义块可能还有引用，这些情况如果不统一处理为引用转换脚注的话会比较混乱。
> 
> 对于同一篇文档中引用大段内容，之前已经做过缩略处理了 #3299

我是引用的其他标题 h2, h3 这种，但我现在导出 PDF 还是会发现整个标题下的所有内容都被变成 footnote 了。下面是一个刚刚导出的 PDF

比如：

<img width="554" alt="image" src="https://user-images.githubusercontent.com/7659710/191643176-7da2ee6a-215c-440c-bd6a-efc89c6427b5.png">


<img width="535" alt="image" src="https://user-images.githubusercontent.com/7659710/191643227-1cc45e19-c09c-46d1-b34c-0d20ea37be0f.png"> 

这个章节内容很长，就不都截取了。

**Comment by 88250** [comment]
之前只处理了段落块，后续改进加入容器块和标题块。
