### ISSUE TITLE
支持中英字体各自调适的选择

### ISSUE THREAD

**Issue by JJCSAMA** [siyuan-note/siyuan#5918]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

中英文档使用情况都较多，希望设置字体区域可以支持中英字体各自调适的选择。

### 描述可能的最优解决方案 Describe the optimal solution

支持中英字体各自调适的选择

**Comment by Vanessa219** [comment]
可参加自定义主题，在相关 css 中加入
```
.b3-typography:not(.b3-typography--default), .protyle-wysiwyg, .protyle-title, .protyle-title__input{
    font-family: xxx;
}
```

**Comment by heimi98** [comment]
![image](https://user-images.githubusercontent.com/56879067/195334064-5835e051-16ff-4011-a561-2a87ffb63034.png)
希望可以像 obsidian 那样可以选择多种字体并设置优先级。
