### ISSUE TITLE
代码块在编辑框渲染语法高亮

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#592]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
编辑模式下查看代码块时没有高亮，希望能够实时渲染代码高亮，不用切换至预览模式

### 描述最优的解决方案 Describe the optimal solution
类似Typora的实时渲染

**Comment by 88250** [comment]
之前也有用户[建议过](https://ld246.com/article/1604549315471)，后续我们再看看如何实现，谢谢。

**Comment by 88250** [comment]
你好，短期内实现不了，我关闭了，谢谢。
