### ISSUE TITLE
正在上传数据仓库引用 缺少进度提示 (并卡住一整天无法打开笔记)

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#5921]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

备用机上很久没有开思源客户端了，然后打开尝试更新最新版，就一直卡在

> v2.2.0正在上传数据仓库引用 refs/latest

由于人在海外，看活动监视器里面的流量，SiYuan-Kernel似乎只有10kb/s的样子，希望能增加一个进度条提示，不然以为是卡住了

### 描述可能的最优解决方案 Describe the optimal solution

> v2.2.0正在上传数据仓库引用 refs/latest  (5.0MB / 24.5MB)

**Comment by HowcanoeWang** [comment]
两个小时了，只上传了30MBΣ（ﾟдﾟlll）

**Comment by HowcanoeWang** [comment]
一整天了⊙﹏⊙∥
![image](https://user-images.githubusercontent.com/19968935/191859583-0993ee53-f668-4b64-b1f0-516b47fe4158.png)

**Comment by 88250** [comment]
网络问题估计没办法解决，我关闭了，抱歉。

**Comment by HowcanoeWang** [comment]
> 网络问题估计没办法解决，我关闭了，抱歉。

感觉并不是网络问题，等了2天走了500mb的流量了，还是卡在这里，稍后把项目打包发邮件看看那边能不能复现？

**Comment by 88250** [comment]
先发一下日志文件。

**Comment by HowcanoeWang** [comment]
最近的日志如下：(把前面无关的都删了，后面的原封未动)

2022/07/19: 某一次出差前，带上备用机，用客户端同步数据（出差期间一直使用浏览器访问主力机的内网穿透，没启动客户端

2022/08/13：又一次出差前，在备用机上同步数据（出差期间还是使用浏览器访问主力机，没有启动客户端

2022/09/22：这次出问题的，依然是出差前尝试备用机客户端同步数据。

[siyuan_clear.log](https://github.com/siyuan-note/siyuan/files/9631788/siyuan_clear.log)

**Comment by 88250** [comment]
从日志中看到，同步虽然有点慢，但是还是执行完了。试下完整退出 SiYuan（包括内核），然后删除工作空间/temp 文件夹重启。

**Comment by HowcanoeWang** [comment]
> 从日志中看到，同步虽然有点慢，但是还是执行完了。试下完整退出 SiYuan（包括内核），然后删除工作空间/temp 文件夹重启。

重启电脑后删除temp解决问题，前面这个ui卡住可以追踪到问题原因吗

**Comment by 88250** [comment]
我们暂时先忽略这个问题，感谢帮助。
