### ISSUE TITLE
超链接嵌套图片情况下数据迁移导致一些未引用资源文件

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#5926]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

两个版本数据的差异

```python

v2.1.14数据格式

* [![](assets/paper-appleIcloud-20220831193950-5lqwxgr.svg)奶牛快传](https://cowtransfer.com/)
* [![](assets/paper-cloud-20220831193950-h53t9tc.svg)蓝奏云](https://pc.woozooo.com/)
* [![](assets/paper-cloudCheck-20220831193949-ccjjjxd.svg)文叔叔](https://www.wenshushu.cn/)


升级到v2.2.0之后，打开文档的时候，会自动把数据转为这种格式，导致图片成为未引用资源
* [奶牛快传](https://cowtransfer.com/)
* [蓝奏云](https://pc.woozooo.com/)
* [文叔叔](https://www.wenshushu.cn/)


v2.2.0 版本的正确格式是这样子
* ![](assets/paper-appleIcloud-20220831193950-5lqwxgr.svg)[奶牛快传](https://cowtransfer.com/)
* ![](assets/paper-cloud-20220831193950-h53t9tc.svg)[蓝奏云](https://pc.woozooo.com/)
* ![](assets/paper-cloudCheck-20220831193949-ccjjjxd.svg)[文叔叔](https://www.wenshushu.cn/)
```

这个问题，是因为这个吗？  [不再支持使用 Markdown 标记符嵌套行级元素 · Issue #5869 · siyuan-note/siyuan](  https://github.com/siyuan-note/siyuan/issues/5869  )    

如果是的话，我感觉移除功能这种操作会给用户带来很大困惑和烦恼，耗费一些不必要的时间。

### 期待的结果 Expected result

如题

### 版本环境 Version environment

```markdown
- Version: v2.1.14   v2.2.0
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by netdog2019** [comment]
我也有很多资源文件变成了未引用，这几天从alpha1折腾到alpha3，再到2.2正式版，尝试了很多方式恢复备份，包括新建云端目录，新建本地目录，停止更新然后再打开，但是几天电脑一同步，很容易就变成了未引用资源。可能是这同样的问题。

**Comment by mozhux** [comment]
这个问题挺大的。我的也是，应该是原来的有什么格式，转化后就不一样了。

**Comment by Zuoqiu-Yingyi** [comment]
嗯嗯, 好像我也有几个链接嵌套图片出现该问题

**Comment by s6492** [comment]
我也出现了类似的问题，大量带链接的图片升级后就没了

**Comment by Geo123abc** [comment]
先不要清理资源，等D大消息吧

**Comment by netdog2019** [comment]
不敢清理。这是个紧急bug，可能需要D大尽快更新。

**Comment by 88250** [comment]
@Geo123abc 不太确定，等发布以后再看。

**Comment by Geo123abc** [comment]
@88250   测试发现，
1. v2.2.1 好像是取消了嵌套，图片不会有HTTP链接了，我之前有嵌套的原因是：剪藏网页之后使用“网络图片转换为本地图片”功能，但是在v 2.2.1中，转换为本地图片之后，图片就没有HTTP链接了；
2. v2.2.0 转换的数据是不可逆的，也就是在 v2.2.0 转换导致的未引用资源文件 在 v2.2.1中仍为未引用资源文件，不会变成之前v2.1.14版中引用的资源文件，所以可能需要手动编辑每个v2.2.0版本导致“未引用资源文件”

**Comment by 88250** [comment]
@Geo123abc 

1. 是的，不支持超链接嵌套图片
2. 之前的数据只能手动重新编辑或者通过数据历史恢复

**Comment by Geo123abc** [comment]
> @Geo123abc
> 
> 1. 是的，不支持超链接嵌套图片
> 2. 之前的数据只能手动重新编辑或者通过数据历史恢复

好的，谢谢

**Comment by Zuoqiu-Yingyi** [comment]
@88250 锚文本为 `[\[foo\]bar](foobar)` 的超链接更新后会错误解析为 `[foo](foobar)[bar](foobar)`, 正确情况应为 `[[foo]bar](foobar)`

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 是通过界面设置的还是？

**Comment by Zuoqiu-Yingyi** [comment]
> @Zuoqiu-Yingyi 是通过界面设置的还是？

通过在编辑器中粘贴纯文本 `[\[foo\]bar](foobar)`, 在 `v2.2.1` 粘贴会得到 `[[]()​[foo](foobar)​[]]()​[bar](foobar)`

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 我这里是这个结果：

![image](https://user-images.githubusercontent.com/873584/192149141-330b51e4-b017-4d10-91a6-503ea003a94b.png)

**Comment by Zuoqiu-Yingyi** [comment]
> [\[foo\]bar](foobar)

哦哦, 我没有描述清楚, 复制时就是复制纯文本, 粘贴时普通粘贴

**Comment by Chenm4** [comment]
取消嵌套后它这个图床图片后面都跟着一个超链接，然后选择图床图片转本地后这个超链接还存在，有什么办法删除这个超链接吗
![B 7DC) B$VQWH)QLQD~8HAE](https://user-images.githubusercontent.com/98648589/192257695-bdf41b62-e0d0-4909-9bba-abf35b8cbf40.png)
@88250

**Comment by 88250** [comment]
@Chenm4 手动删除。
