### ISSUE TITLE
【alt+左键】选择多行编辑

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#5928]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如图，想要一次对多列进行处理，比如加上ctl+G的效果。（文档内还有多处，不适合替换）
现在只能一行一行的去处理
![6F{`$}VQBKT41BWQIC($8 T](https://user-images.githubusercontent.com/37429029/191895980-61b104ae-bd73-4597-92e3-80ec0bc364b4.png)

### 描述可能的最优解决方案 Describe the optimal solution

点击【alt+左键】多行一起编辑
![6c97451584a71c4431561112](https://user-images.githubusercontent.com/37429029/191896177-5c7ce97c-86a8-435c-abf3-4ec61f3fa63b.png)

**Comment by UFDXD** [comment]
@yuyuyu-github 之前有人提过，但D大说做不了

**Comment by yuyuyu-github** [comment]
好吧

> @yuyuyu-github 之前有人提过，但D大说做不了
