### ISSUE TITLE
表格增加表头固定，单元格合并，单元格内可以嵌套表格能力

### ISSUE THREAD

**Issue by crendy** [siyuan-note/siyuan#5929]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

一些技术文档，比如整理当前项目情况，合并单元格做为项目分类，单元格内嵌套表格 表现子项目内容等等

### 描述可能的最优解决方案 Describe the optimal solution

现在很多wiki应该有增强表格的通用实现方法

**Comment by 88250** [comment]
合并单元格已经支持，表头固定和嵌套表格无法实现，感谢提议。

**Comment by crendy** [comment]
1，目前的合并单元格，复制带合并单元格的内容到思源，还是会乱？
2，为什么不能支持表格内嵌套表格？是和什么未来方向有冲突吗？

**Comment by 88250** [comment]
@crendy 

1. 应该是不支持解析的
2. 技术上无法支持

**Comment by crendy** [comment]
1的问题是很影响体验的，这是基础能力，用了几个笔记软件都可以互相复制粘贴的，只要是其他笔记有合并单元格的表格，复制到思源就乱，这个问题还是要解决的。
2，技术上不支持不知道如何评估的，除非现在没有实现此功能的先例，问题是这个功能很普遍~

**Comment by 88250** [comment]
@crendy 其他开发者能做到的事情不代表我们也能做到，见谅。

**Comment by crendy** [comment]
理解，我只是建议，目前支持不了 不代表未来不能支持，加油。
