### ISSUE TITLE
表格合并单元格

### ISSUE THREAD

**Issue by huangwzehii** [siyuan-note/siyuan#593]

**Comment by GlowBlur** [comment]
目前可以使用HTML来实现，现在就缺少个可视化HTML表格的编辑器

**Comment by 88250** [comment]
[关于未来表格改进的思路咨询](https://ld246.com/article/1627541764253)

**Comment by 88250** [comment]
暂时不考虑在 Markdown 表格上加入支持了。

**Comment by 88250** [comment]
后续还是支持了 https://github.com/siyuan-note/siyuan/issues/4022
