### ISSUE TITLE
虚拟引用不应该保留编辑状态

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#5940]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

剪贴虚拟引用文本无法用于引用搜索

### 期待的结果 Expected result

正常搜索

### 截屏或者录屏演示 Screenshot or screen recording presentation

![剪贴虚拟引用文本无法用于引用搜索](https://user-images.githubusercontent.com/97731736/192082640-cf73b729-0eb5-4efc-9d99-f899c9c186fd.gif)

### 版本环境 Version environment

```markdown
- Version: v2.2.0
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
Fix https://github.com/88250/lute/commit/e9fcd6382190fbb8ca70527a1f68a93287da5f39
