### ISSUE TITLE
导出 PDF 支持保留折叠状态

### ISSUE THREAD

**Issue by Kitsuta-le** [siyuan-note/siyuan#5941]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我只想要标题而不需要下面的内容，结果整理好了发现导出PDF一律是全部展开，这样我的文档就导出了140多页。。。
我只想打印了看小标题呀，这可把我愁死了。肯定也是有其他类似的情况存在的
![EU~WE3ZMGB$NP%26LOYLZDW](https://user-images.githubusercontent.com/88605687/192089415-a94850eb-ab01-4109-8cff-f3444d5120e1.png)

### 描述可能的最优解决方案 Describe the optimal solution

提供选择按照现有折叠状况导出PDF的选项

**Comment by 88250** [comment]
变更 https://github.com/siyuan-note/siyuan/issues/4064
