### ISSUE TITLE
刷新窗口时记住钉住悬浮窗并重新打开

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#5945]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

打开了许多悬浮窗。
文本的批量替换操作后，思源会重新启动。
启动完成后，所有的悬浮窗需要重新翻找一一打开。
重新打开钉住悬浮窗的过程很繁琐并且严重打断笔记思路。
因为文本批量替换操作之后肯定需要查看替换后适合不适合是否需要针对修改，而且要继续进行笔记工作。

### 描述可能的最优解决方案 Describe the optimal solution

批量替换操作，记忆之前钉住的悬浮窗，并且重新打开。

**Comment by UFDXD** [comment]
攒

**Comment by Vanessa219** [comment]
想了下悬浮窗一般系统都不会进行保存吧，都是用于临时查看的。如果下次还需要查看的话可以按住 ctrl 点击悬浮窗上的面包屑使用页签打开。
