### ISSUE TITLE
快捷键识别不正确

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#5949]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

_getKeymapString 这个函数
无法正确识别以下快捷键
 shift+alt+\\
 shift+alt+;
 shift+alt+'
 shift+alt+,
 shift+alt+/
原因在于 下面344/351-352行, 
https://github.com/siyuan-note/siyuan/blob/a59014cf2de1b15298c349623dd7a374b55b1525/app/src/config/keymap.ts#L343-L358
\\;',/ 这5个键的code分别为:
Backslash/Semicolon/Quote/Comma/Slash
因此codeKey 分别取H/N/E/A/H, 导致351-352行不正确

- 还有个疑问:
为什么L343-L357 行的alt键要单独处理? 
351行 (codeKey !== "I" && codeKey !== "E" && codeKey !== "N" && codeKey !== "U") 这个为什么不处理呢?

### 期待的结果 Expected result

1 

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
     1
```

### 日志文件 Log file

  1

**Comment by iamqiz** [comment]
@Vanessa219 V姐厉害!
提个建议,不如把所有特殊符号_+{}|这些都变成小写? 
一是因为其他编辑器基本都是小写形式,
二是释义大写形式,则ctrl+shift+=会变成下图
![Snipaste_2022-09-25_13-27-57](https://user-images.githubusercontent.com/48077521/192129735-8a968c35-aa4a-406f-8534-cf4868280550.png)

**Comment by Vanessa219** [comment]
这个我也没太弄明白，在 IDE 里面，有些组合使用的是大写，有些组合使用的小写，而且这些判断在组合键不同的时候还不一样。所以这里我就统一使用了有 shift 的输出。

**Comment by iamqiz** [comment]
同一个IDE里面还会混用大小写形式的特殊符号吗? jetbrains和vscode里是小写的,  
在有shift键的时候再大写,感觉多此一举了
另外大写还有个缺点:
在快捷键搜索时, 输入 / 期望搜索出ctrl+shift+/ 这样的快捷键, 但因为它的keymapStr是⌘⇧? 里面没有/ 所以搜不出来
