### ISSUE TITLE
内容块命名、备注和样式

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#595]
内容块命名将用于反链提及搜索。

**Comment by canondin** [comment]
> * 可以给内容块命名，该名字全局唯一，和 ID 一一对应
> * 可以给内容块起别名，支持多个别名，可以和其他内容块别名重复

siyuan 打开目录文件夹后，把之前typora 的 markdown 文档都改掉加入了id，再用 typora 打开就变成这样
![image](https://user-images.githubusercontent.com/14855855/103392938-1c124a80-4b5b-11eb-978d-bd0ffd629823.png)

**Comment by 88250** [comment]
@canondin 请看帮助文档 FAQ，谢谢

**Comment by canondin** [comment]
> @canondin 请看帮助文档 FAQ，谢谢

多谢
