### ISSUE TITLE
无法保持子块的折叠状态

### ISSUE THREAD

**Issue by choora** [siyuan-note/siyuan#5950]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如**标题 1** 下有子块 **标题 1.1** 和 **标题 1.2**，如果折叠子块 **标题 1.2**，再折叠 **标题 1**，展开 **标题 1** 后，原本被折叠的 **标题 1.2** 也被展开了.

### 期待的结果 Expected result

希望可以保持子块的折叠状态，而不会被父块的折叠状态影响.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![2022-09-25 10-51-13 的屏幕截图](https://user-images.githubusercontent.com/8318196/192126112-f77ea9b6-66ce-463e-b47b-cd2186135bbc.png)
![2022-09-25 10-51-35 的屏幕截图](https://user-images.githubusercontent.com/8318196/192126122-c0ceb8e2-2fab-4f4c-960c-f2a1cacb4c64.png)
![2022-09-25 10-52-06 的屏幕截图](https://user-images.githubusercontent.com/8318196/192126124-8ebf4e1f-d8fb-4a2d-b3a0-9dd4a51582eb.png)

### 版本环境 Version environment

```markdown
- Version: 2.2.0
- Operating System: Ubuntu 20.04.5 LTS
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9639913/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，但是这个在设计上就无法支持，上级展开或者折叠会覆盖子级的设置。
