### ISSUE TITLE
行内元素添加样式后体验不一致

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#5951]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

行内字体元素添加样式后，以加粗和变红为例

加粗字体放在块的开头，在它前头和后头继续输入，输入的字体都会被加粗，但是如果加粗的字体在句中，前面的不会加粗，后面的会，其他输入可能又会造成其他情况

变红的字体，不同的位置又有不同的情况

字体样式设置以后，继续输入，体验不一致

其中带来一个小问题，字体加粗放在块开头，想在开头输入无序列表，-会被加粗而导致无法触发，同理#也会被加粗导致无法触发标题

### 期待的结果 Expected result

统一逻辑，比如对字体添加样式后，无论如何输入都不会改变后续输入字体，或者，只有在被改变的字体中间继续输入，才会被改变，无论什么情况下
以上建议仅做参考，期待有完美的解决方案

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

```markdown
- Version: 2.2.0
- Operating System: android
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by 88250** [comment]
Duplicate of #5924
