### ISSUE TITLE
模板搜索支持识别拼音

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#5952]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

搜索模板的时候，由于现在模板搜索只能支持汉字，导致经常需要切换输入法
![image](https://user-images.githubusercontent.com/37429029/192135802-73d50fe0-b686-4223-9794-9cfe4d06e769.png)

![image](https://user-images.githubusercontent.com/37429029/192135794-664e4437-be00-4307-9076-a344a000a22f.png)

### 描述可能的最优解决方案 Describe the optimal solution

除了识别汉字以外，可以支持识别拼音。
![image](https://user-images.githubusercontent.com/37429029/192135822-4fba1c88-0be6-4f07-8b79-d441fc66f4fb.png)

**Comment by 88250** [comment]
这个目前无法实现，抱歉抱歉。
