### ISSUE TITLE
webpack加速编译

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#5954]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在 pnpm run dev & pnpm run start 太慢了,将近50秒时
即便只修改一个文件的几行,也耗费这么长时间
能否优化一下,让webpack 增量编译,加速编译? 

### 描述可能的最优解决方案 Describe the optimal solution

webpack 增量编译?

**Comment by 88250** [comment]
好像一直是增量的。

**Comment by 88250** [comment]
老铁要不帮忙研究一下，我们先关闭了。

**Comment by iamqiz** [comment]
我对 webpack 基本一无所知, 要搞懂得费一段时间,  @Vanessa219 V姐会吗?

**Comment by 88250** [comment]
我问过她了，她没时间研究……
