### ISSUE TITLE
表格内光标和按键交互优化

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#5955]
https://ld246.com/article/1664100427683

- [x] 新建行列后将光标移动到对应的新单元格中
- [x] 表格后无内容时，按右键需新建空块
- [x] Enter 改为光标换到下一行对应的单元格
- [x] Shift+Enter 改为换行
- [x] ArrowDown/ArrowUp 遇到行内元素或多行元素时光标跳转错误

**Comment by lentikr** [comment]
请问可以实现类似typora那种可视化选择表格行列数的功能吗？或者提供输入行列数的功能。

**Comment by 88250** [comment]
> 请问可以实现类似typora那种可视化选择表格行列数的功能吗？或者提供输入行列数的功能。

https://github.com/siyuan-note/siyuan/issues/4785
