### ISSUE TITLE
退出时自动删除超过 30 天的安装包

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#5957]
退出内核时自动删除工作空间/temp/install/ 下超过 30 天的安装包文件。

**Comment by lentikr** [comment]
D大，或许这个逻辑应该改为退出时删除所有比当前版本低（或相等）的安装包吗？

**Comment by 88250** [comment]
@lentikr 考虑到用户可能会回退版本，所以暂时以时间为限。
