### ISSUE TITLE
Text no longer applies custom styles

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#5960]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

I made several modifications to the program to make my studies perfect. I applied several styles in the text that facilitated my reading and attention to certain topics.

Example:
In "background style 13" (inside the "theme.css" file in v2.1.14) I used to use the code:

>strong[style="background-color: var(--b3-font-background13);"] {
         font-size: 100%;
         padding: 1px 4px 2px 4px;
         color: var(--b3-theme-on-background)!important;
         background-color: transparent !important;
         border-bottom: 1px dashed rgba(250, 250, 250, .5);
         border-top: 1px dashed rgba(250, 250, 250, .5);
         border-left: 1px dashed rgba(250, 250, 250, .5);
         border-right: 1px dashed rgba(250, 250, 250, .5);
}

Expected outcome:
![image](https://user-images.githubusercontent.com/90691302/192145591-600d2d2a-42d3-4607-9b24-ba7972eb3111.png)

Other example:
>strong[style="color: var(--b3-font-color13);"] {
    text-decoration: underline wavy white;
    text-underline-offset: 3px;
    color: inherit !important;
}

Expected outcome:
![image](https://user-images.githubusercontent.com/90691302/192146073-c5e8d566-84e8-4765-920d-43b9fec09e6a.png)

Today (version 2.2) none of my edits work anymore! It is a mistake? Or did you stop supporting this type of editing? If they stopped I will stabilize in version 2.1.14. But if it's a mistake, I'll wait for the fix and always updating

### 期待的结果 Expected result

Enabling these features again

### 版本环境 Version environment

```markdown
- Version: 2.2.1
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9640834/siyuan.log)

**Comment by 88250** [comment]
Hello, after v2.2.0 inline-elements no longer use HTML semantic tags (such as `<strong>`, `<em>`, etc.), so the theme CSS needs to be rewritten.

Sorry for the inconvenience caused to you, thank you for your understanding and support.
