### ISSUE TITLE
在行级元素中添加公式、备注和链接导致类型丢失

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#5964]
在行级元素中添加公式、备注和链接会产生 `<span>` 嵌套导致类型丢失。

**Comment by alexalayoung** [comment]
同样遇到, 备注和标记内容丢失,整行丢失
奇怪的是, 部分文件没丢失

**Comment by mlzxy** [comment]
目前如果添加行内字体风格，会把行内公式删掉

![1](https://user-images.githubusercontent.com/7659710/192895119-6faa1a6a-a2fd-472e-8788-c549b37bf466.gif)
