### ISSUE TITLE
2.21版选择标签输入后一直保持标签内

### ISSUE THREAD

**Issue by hscui** [siyuan-note/siyuan#5965]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

输入 # ，然后出现已有标签，如果选择一个，然后回车输入后，此时光标依然在标签内，无论再输入任何字符均为标签；只有手动输入前后两个 # ，才会关闭标签。

如下图：
![标签问题](https://user-images.githubusercontent.com/7949195/192171974-23ba21c0-2af6-4bf8-9be8-2c2850f6b153.gif)

### 期待的结果 Expected result

这个应该是引入文字多重格式造成的BUG，希请修复。

### 版本环境 Version environment

```markdown
- Version: 2.2.1
- Operating System: WIN10
- Browser (if used):
```

### 日志文件 Log file

上传不了

**Comment by 88250** [comment]
这个是特性，行级元素跳出需使用对应快捷键。

**Comment by hscui** [comment]
> 

明白了。不过就这两天的试用，发现这个功能还是不稳定，有时会光标在标签内，有时还会和以往一样，在标签外，而且这个是随机的；同样两个标签，我尝试输入时，随机出现这两种现象。

**Comment by 88250** [comment]
@hscui 等下个版本发布以后再试试。
