### ISSUE TITLE
日记配置功能（daily note config feature）

### ISSUE THREAD

**Issue by HecterFang** [siyuan-note/siyuan#5976]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前设计，每次鼠标新建日记都要手动选择存放路径，（快捷键 Alt+5 是使用上次选择的目录）。
希望每天新建日记的时候，自动放置于默认的目录下。

### 描述可能的最优解决方案 Describe the optimal solution

设置界面增加日志配置功能，里面可以增加这个默认目录配置；日记标题的日期格式；日记模板的位置；是否启动时打开日记等等选项。

### 描述候选的解决方案 Describe the candidate solution

类似OB的设计。

**Comment by 88250** [comment]
这个设计之前考虑过，但是思源中存在笔记本，而笔记本是可以关闭的，所以只能在运行时通过交互判断是否笔记本可用。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by HecterFang** [comment]
如果笔记本关闭的，那就自动打开它呗。如果用户配置了，就只打开用户配置的默认存放的文件夹即可。只打开这一个，不多的。

**Comment by Zuoqiu-Yingyi** [comment]
> 这个设计之前考虑过，但是思源中存在笔记本，而笔记本是可以关闭的，所以只能在运行时通过交互判断是否笔记本可用。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

有一个非常简单的实现方案: 这里只配置笔记本, 作用等价于快捷键 <kbd>Alt + 5</kbd> 打开上次选择的记住的笔记本
