### ISSUE TITLE
搜索界面自动调整宽度

### ISSUE THREAD

**Issue by HecterF** [siyuan-note/siyuan#5979]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

搜索界面宽度和笔记界面宽度左右分（dark+）不能用鼠标自由调整宽度。

![image](https://user-images.githubusercontent.com/46716553/192336696-1295f98e-6c38-4c07-9fc3-183cc5af88a8.png)

### 期待的结果 Expected result

搜索界面宽度和笔记界面宽度左右分（dark+）能用鼠标自由调整宽度。

### 版本环境 Version environment

```markdown
- Version: 2.2.1
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

     ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/09/27 00:46:06 runtime.go:47: kernel is booting:
    * ver [2.2.1]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [I:\SiYuan-Data, data 18 MB]
I 2022/09/27 00:46:06 serve.go:79: kernel is booting [http://127.0.0.1:6806]
I 2022/09/27 00:46:07 conf.go:559: database size [8.5 MB], tree/block count [95/3049]
I 2022/09/27 00:46:07 working.go:151: kernel booted
I 2022/09/27 00:46:07 working.go:478: built-in pandoc [ver=2.19.2, bin=I:\SiYuan-Data\temp\pandoc\bin\pandoc.exe]

**Comment by 88250** [comment]
麻烦到 Dark+ 主题仓库反馈，谢谢。
