### ISSUE TITLE
编辑器里粘贴图片时，保存成 jpg 或 webp 格式

### ISSUE THREAD

**Issue by yyb1rd** [siyuan-note/siyuan#5983]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我喜欢收集图片，经常截屏，或者浏览器里对着图片复制它。这时若直接在编辑器里粘贴，默认会保存成一个png文件。png固然高质量，但体积过大，我电脑上已经有上百兆的png图片了。

### 描述可能的最优解决方案 Describe the optimal solution

如果能自动转成jpg格式，体积能减到 1/10，如果转成webp，能减到1/20。

所以建议增加一个设置：粘贴图片时自动转换格式。

实现方法，可以在前端网页里用canvas元素转换图片格式；
也可以用go的标准库 Image 转换 jpeg 格式，用 golang.org/x/image/webp 库转换 webp 格式。

### 其他信息 Other information

考虑到jpeg和webp都是有损压缩，建议初始默认保存成png格式。

**Comment by 88250** [comment]
开发精力有限，目前暂时不考虑了，可以找下外部截图工具，应该有功能能支持。

另外，如果能 PR 代码我们也非常欢迎，谢谢。

**Comment by boryun** [comment]
挖个坟，目前3.6.5版本了，能重新考虑一下这个功能吗。更具体的来说，希望粘贴图片时能保留图片原格式而不是总是自动转换为png，感觉非常实用，我也很多次遇到jpg图片粘贴后自动转换成png后导致占用空间成倍增加的问题了，每次都将图片先另存到本地再拖入思源实在是不太方便。
