### ISSUE TITLE
优化排版只对无格式文字有效

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#5984]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

优化排版（中英文之间加空格）只对无格式文字有效，文字加粗、斜体、高亮等操作后无效。
![image](https://user-images.githubusercontent.com/56879067/192475970-1601a50b-983b-4e29-896f-7d77ab2a7243.png)

### 期待的结果 Expected result

对有格式文字也有效。

### 版本环境 Version environment

```markdown
- Version: 2.2.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
排版后的行级不能加入排版优化，这个可能是用户有意为之，举个例子，比如代码 `foo测试bar` 和 `foo 测试 bar` 是不一样的。
