### ISSUE TITLE
使用社区主题时外观模式跟随系统切换异常

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#5985]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

系统环境：深色模式
思源设置：明亮模式 v2.2.1
升级 v2.2.2
打开思源，变成暗黑模式（异常）
切换为明亮模式，界面刷新变成明亮模式（正常）
重启思源，又变成暗黑模式（异常）
切换为跟随系统，界面刷新变成明亮模式（异常）
重启思源，又变成暗黑模式（未知）

### 期待的结果 Expected result

无

### 版本环境 Version environment

```markdown
- Version: v2.2.2
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by Zuoqiu-Yingyi** [comment]
该bug可能造成的原因: 切换后未加载主题配置文件 `<link id="themeDefaultStyle" rel="stylesheet" type="text/css" href="/appearance/themes/midnight/theme.css?v=2.2.2">`

**Comment by 88250** [comment]
@Temacc0531 使用的是默认主题还是？

**Comment by TsuiCyne** [comment]
我升级前用的明亮模式是默认主题，升级之后变成暗黑模式是notion-dark

**Comment by UltramarineSky** [comment]
升级前用的是黑暗模式dark+，升级后变成了明亮模式的salt，设置为黑暗模式后切换为dark+，但重启软件后自动变成明亮模式了，跟系统白天/黑夜模式没关系，电脑设置成夜间模式，重启后打开还是明亮模式
