### ISSUE TITLE
集市已下载界面更新主题有概率失败

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#5987]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在集市-已下载内有主题显示更新按钮，点击后加载圆圈显示了下，然后就消失了，更新按钮也没消失，所以我认为更新失败了。
但在集市-主题内更新的话，则没有任何问题，可以正常更新。
附录屏、系统日志。

### 期待的结果 Expected result

改进

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://ld246.com/article/1664288066348?r=EberhardLin

### 版本环境 Version environment

```markdown
- Version: 2.2.2
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/9656708/system-log.zip)

**Comment by 88250** [comment]
从日志来看应该是因为主题作者填写的 hash 不对或者仓库提交被重置了，麻烦给主题仓库反馈一下。
