### ISSUE TITLE
点击引用描文本跳转到聚焦状态的的内容，快捷键后退后不会回到文档点击位置（会回到文档开头）

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#5989]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

点击引用描文本跳转到聚焦状态的的内容，快捷键后退后不会回到文档点击位置（会回到文档开头）
（引用描文本指向的是折叠列表中的块）

### 期待的结果 Expected result

后退后，回到引用跳转前的文档位置

### 版本环境 Version environment

```markdown
- Version: v2.2.2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
可以录屏么？感觉有点复杂。是在同一个文档中还是？

**Comment by UFDXD** [comment]
@Vanessa219 

https://user-images.githubusercontent.com/97731736/192588525-a5e47d6a-f169-4358-833c-25d1237a79d5.mp4
