### ISSUE TITLE
复制带超链接的图片无法保存到本地

### ISSUE THREAD

**Issue by s6492** [siyuan-note/siyuan#5993]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

复制带超链接的图片后，进行网络图片转换为本地图片时，会提示不存在网络图片，图片也会消失
如果不进行网络图片转换为本地图片，重启软件后也看不到图片

### 期待的结果 Expected result

能保存对应图片到本地

### 版本环境 Version environment

```markdown
- Version: v2.2.2
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
请给一下网页地址。
