### ISSUE TITLE
界面显示异常

### ISSUE THREAD

**Issue by XiaoBingBy** [siyuan-note/siyuan#5995]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

界面显示异常
已截图

### 期待的结果 Expected result

界面显示异常
已截图

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/9722096/192591125-a83da7cc-233b-4184-bfc7-dc8d816c3ec6.png)

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
b3log/siyuan
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by eno1016** [comment]
我也是，关闭再打开就变成一片白，所有设置都不见了

**Comment by jllmh1987** [comment]
同样的问题，在设置的位置点击进入，改两次外观的主题选项，才可以恢复
