### ISSUE TITLE
【关系图】在小比例下查看节点时文字闪动

### ISSUE THREAD

**Issue by Dillzo** [siyuan-note/siyuan#6]
![image](https://user-images.githubusercontent.com/68283141/92925964-e8a59600-f46d-11ea-8119-a73a0aeb0805.png)
鼠标放到某个节点时，相关笔记会显示文字，但文字显示出来后，文字层好像在节点层上方，所以鼠标失去了焦点，文字就会隐藏，节点又变成了鼠标hover状态，文字又显示出来……如此循环，文字就闪动起来了。

**Comment by 88250** [comment]
收到，v0.2.0 修复，感谢反馈。
