### ISSUE TITLE
反向链接搜索栏优化

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6002]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

当反向链接栏宽度过窄时，点击搜索按钮无法显示出完整搜索栏（无变化），看不出实际已经可以输入

### 期待的结果 Expected result

可以改成平时未进入输入状态时只显示放大镜图标，点击后再变成搜索输入栏

### 截屏或者录屏演示 Screenshot or screen recording presentation

![test7](https://user-images.githubusercontent.com/101307399/192708275-050a503c-e7a1-40cc-8568-38a8a0879056.gif)

### 版本环境 Version environment

```markdown
- Version: v2.2.2
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/3565 中处理。

**Comment by Temacc0531** [comment]
`v2.3.0`改成了一个空白方框对于新用户可能有点意味不明😂，不知道这个原来是搜索输入框
从放大镜点击变成输入框应该会好些
