### ISSUE TITLE
无法定位到后退内容为动态加载的块

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6004]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

实际测试这个问题还存在

### 期待的结果 Expected result

希望解决问题

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/97731736/192732824-bd1c0d7c-5ab2-43bc-a160-5c528219351f.mp4

### 版本环境 Version environment

```markdown
- Version: v2.2.3
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
按照你视频里面的操作了，重现不了，是哪里不对么？

https://user-images.githubusercontent.com/970828/192803394-04358306-b77c-4a47-9583-789dce5eafbc.mp4

**Comment by UFDXD** [comment]
@Vanessa219  
[杂项文章.sy.zip](https://github.com/siyuan-note/siyuan/files/9666109/sy.zip)
我的测试文档很长，应该是这个原因
