### ISSUE TITLE
有更新时，点击检查更新应该提示有新版本并且可以直接下载

### ISSUE THREAD

**Issue by netdog2019** [siyuan-note/siyuan#6005]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

今天在办公室电脑上，思源笔记自动提示有新版本，然后重启自动更新，感觉很棒。回家后，在家里的电脑上，那个自动下载更新包的按钮也打开了，但是没能提示有新版本更新，看那个上面的提示是2个小时才检查一次。然后我想点击下面的“检查更新”，这个到时能发现新版本，但是它只能链接到论坛里的发布页面并不能自动下载，没办法，虽然有检查更新和自动下载更新安装包的功能，但是我还是需要到群里下载新版本，手动安装。

### 期待的结果 Expected result

希望打开自动下载后，点击检查更新，能查到新版本，然后提供下载功能，另外，将检查更新的按钮移到自动下载更新包旁边，便于统一。

### 版本环境 Version environment

```markdown
- Version: 2.2.2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
v2.2.3 已经支持 https://github.com/siyuan-note/siyuan/issues/5998
