### ISSUE TITLE
有计划支持客户端直连docker吗

### ISSUE THREAD

**Issue by crendy** [siyuan-note/siyuan#6006]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

自己部署docker，各端数据通过docker服务同步，即保证了数据私有化，还保证了多端同步

### 描述可能的最优解决方案 Describe the optimal solution

当前的云端同步开源， 可支持docker部署，客户端增加配置docker服务地址。

**Comment by 88250** [comment]
没有计划，这里有一些相关讨论 https://github.com/siyuan-note/siyuan/issues/5990

**Comment by crendy** [comment]
好吧....

**Comment by crendy** [comment]
> 没有计划，这里有一些相关讨论 #5990

不太一样，我说的类似于现在会员订购的同步功能类似，将同步功能开源就好了，这才是大多数人想要的效果吧，笔记软件一般都是多端使用，又想数据自己保存，也match思源的初衷

**Comment by crendy** [comment]
> @crendy 同步功能是开源的 https://github.com/siyuan-note/dejavu 云端闭源的部分只有很少量的数据统计和鉴权代码，如果需要的话完全可以自己 Fork 改造一下，谢谢。

嗯嗯 看到了，谢谢。  自己改造完 客户端如何设置 还是需要客户端有配置的地方哈。
