### ISSUE TITLE
移除文件锁

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6010]
https://ld246.com/article/1664418497446/comment/1664419411052?r=88250#comments

希望大家能够理解为什么无法支持第三方同步盘。我们已经做过很多改进尝试了，但是只能降低数据损坏的概率，最后该出问题还是会出问题。

与其降低出问题的概率不如让问题尽早暴露，这样用户也能在使用初期就发现并规避问题，而不是后期数据量起来以后莫名其妙损坏数据。

[关于不支持使用第三方同步盘同步数据的公告](https://ld246.com/article/1664442401353)

**Comment by woniuxia** [comment]
D大，有可能通过开关进行控制吗？
默认不打开，有需要的自行打开，感觉这个功能还挺重要的，与我而言感觉更安全。

**Comment by 88250** [comment]
@woniuxia 这个影响稳定性的设计不会考虑开关，谢谢。

**Comment by SineMark2020** [comment]
不确定使用文件有没有写，没有的话记得写上第三方同步盘免责声明

**Comment by 88250** [comment]
@SineMark2020 思源使用 AGPL 开源协议
