### ISSUE TITLE
我想要一个超级超级块的功能

### ISSUE THREAD

**Issue by better319** [siyuan-note/siyuan#6012]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候，写着写着就有事情插入进来了，无法归类定位，需要临时放一下。
有时候是为了排版好看
也有时候是头脑风暴，突然想类似脑图那样搞一下。

可以在界面中任意移动，不受限与行。宽度高度都可以自己调整。

### 描述可能的最优解决方案 Describe the optimal solution

简单的将就是类似word中的文本框。这个文本框可以悬浮，围绕模式，任意定位。
<float>

**Comment by better319** [comment]
css中有个float

**Comment by lentikr** [comment]
可以搜索一下affine这个笔记软件，支持搭建私服，不过好像还在开发，应该是蛮符合你的需求

**Comment by 88250** [comment]
超级块应该能满足大部分排版需求了，随意拖动的功能建议使用画布类应用，思源目前不会考虑引入类似特性，感谢提议。
