### ISSUE TITLE
[BUG] 登陆后在getConfig接口中存在密码返回值，不安全

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#6013]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/4801955/192992971-4b03919d-0280-452e-8e8b-d9587eccc80a.png)
在`/api/system/getConf`中返回值包含了密码敏感信息，应移除

### 期待的结果 Expected result

去除此返回值，或者通过加密方式返回

### 版本环境 Version environment

```markdown
- Version: 2.2.3
- Operating System: Windows 10
- Browser (if used): Microsoft Edge 105.0.1343.53 (正式版本) (64 位)

docker版本
```

### 日志文件 Log file

无需提供

**Comment by 88250** [comment]
经过授权以后应该没有安全问题吧。

**Comment by zuoez02** [comment]
比如挂件也调用这个接口，然后发送到远程，这不就不安全了么……得小心挂件有投毒也，毕竟没有跨域保护了

**Comment by 88250** [comment]
这个没法阻止的，接口授权以后都能访问，增删改查数据都行的。

**Comment by zuoez02** [comment]
源码我还没读到有用到这个值的地方，如果没有用到的直接去掉最好，否则的话至少是在服务端做个md5返回来也行呀，至少不能用明文

**Comment by 88250** [comment]
设置里面要用到明文的。

**Comment by zuoez02** [comment]
访问授权码功能吗？这种类似API TOKEN的东西，可以就是存在服务端，保存完用的人没记住让他重新换一个就完了。

**Comment by 88250** [comment]
是的，但是有的人要看啊，不然他不记得自己设置的是多少 😂

**Comment by zuoez02** [comment]
但是安全性更重要吧我觉得。这就跟你手机登陆过的wifi，很多手机都查不了密码一样，也是为了避免别人拿他手机就知道了密码一样。他忘了就让他自己设置一下密码就完了。

**Comment by 88250** [comment]
安全性肯定重要，但是这个接口是在授权过以后才返回的授权码。因为授权过后，所有数据都能增删改查，如果按照你说的逻辑，那么就相当于所有数据都是泄漏的，这个是不是更不安全？

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by zuoez02** [comment]
一个问题一个说吧，我们可以把思源类比成evernote这样，毕竟都是笔记软件了，evernote插件可以把数据发送给外人的话，想想也一样可怕的。

不是说有一个漏洞就会说系统完全会有不可信，但一些细小的漏洞组合起来一样是放大招的。

思源已经越做越大了，我发现周围有的人也在开始使用了，不算极客或者极小众的产品了，我觉得安全性问题还是要好好考虑考虑的。
就像VSCODE的插件也是有是否可信的问题的，是否信任工程目录这样。咱们可以多想想怎么设计系统的安全性，密码会明文拿到这种我们先干掉，插件的问题我们目前也算可控，毕竟集市在自己手里。

安全性是个持续的事情，不是一次就处理完的，也没啥问题我觉得。

**Comment by zuoez02** [comment]
我是自己在Docker上部署的用户，对我来说这种问题就比较严重，只要别人拿到我的地址和密码，数据就都泄露了。我选择思源也是因为私有部署的好处：数据自己持有，可以避免审查之类的。
终端用户倒是不怎么受影响，毕竟自己的手机自己的电脑上装APP的话，影响小一些，不过威胁场景也是存在的。怎么围绕开源搭建一个可信的插件系统，问题都有的，npm投毒的事情相信你也听说过。
所以问题我们一个一个解决就好 :)

**Comment by 88250** [comment]
我不太清楚 evernote 是不是所有数据都明文存储在本地上，另外它的插件是不是可以完全读写数据。思源作为数据明文存储本地的软件，关于数据安全和威胁模型已经在用户指南数据安全章节中进行了阐述。

另外，思源本身是完全开源的，这一点就像你举例的其他开源软件社区一样，无法避免会产生一些安全事件。数据安全最终还是要靠用户自己确保。

对于部署 Docker 而言，建议在反代这一层加上单独的验证授权机制，这样能够解决一些安全访问相关问题，并能规避软件自身潜在的授权机制漏洞，这也是安全运维的通用做法。

**Comment by zuoez02** [comment]
现在我是做了反代上支持SSH，但是没有做额外的证书认证，很麻烦，需要每个客户端都支持才行。SSL解决外部问题。

内部接口能获取明文密码，属于内部问题，容易被内部泄露出去。如果因为一个易用性问题不解决这个问题我是觉得有些不妥的。

Evernote只是个例子而已，这次开的issue关注的还是密钥的机密性，而不是整个系统信息的机密性问题。密钥机密性可以通过hash的方式解决。

**Comment by zuoez02** [comment]
支持https, 说成ssh了

**Comment by 88250** [comment]
我觉得还需要收集更多用户的反馈后再做评估。

**Comment by terwer** [comment]
https://brands.cnblogs.com/tencentcloud/p/9464

nginx反代授权有篇文章，这个应该能马上解决你的问题。至于软件本身的方案，可能会有比较久的考虑吧。

**Comment by zuoez02** [comment]
那我在链滴上发起一个投票？或者说我看咱们siyuan-note有个群组，是否需要内部投票一下？

我只知道D和V在做这个，群组那个我并不了解，只是猜咱们是否有个群组机制。

**Comment by 88250** [comment]
链滴上发起投票看看，谢谢。
