### ISSUE TITLE
提醒样式和提醒方式

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#6015]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

设置微信提醒后没有任何样式标记，不方便查看，可否自动设置样式用于标记

提醒方式单一，可否支持邮件提醒

### 描述可能的最优解决方案 Describe the optimal solution

设置提醒后自动块备注提醒时间，或者新增独立的样式便于查看修改时间，或者更优的解决方案

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
* https://github.com/siyuan-note/siyuan/issues/3769
* 应该不会考虑邮件提醒

感谢反馈。
