### ISSUE TITLE
Windows 端支持 `AppsKey` 按键 打开右键菜单

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6017]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

纯键盘操作的时候，需要右键光标所在块

### 描述可能的最优解决方案 Describe the optimal solution

支持AppsKey https://baike.baidu.com/item/appskey/4331015?fr=aladdin

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by Vanessa219** [comment]
是需要这个菜单？
<img width="248" alt="image" src="https://user-images.githubusercontent.com/970828/193171810-b7417139-5af5-406f-9502-088c64f9131f.png">

**Comment by UFDXD** [comment]
@Vanessa219 是的

**Comment by Vanessa219** [comment]
这个都有快捷键了嘛，直接按不是更快 😄
