### ISSUE TITLE
backend 能否支持git repo，这样普通用户就不用部署后端

### ISSUE THREAD

**Issue by godvmxi** [siyuan-note/siyuan#6021]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

不论是个人部署后端，还是使用公共后端，过去十几年的经历告诉我，都不太靠谱。。。跑路大把，或者是天朝的神奇的审核制度，满篇文章星号。
如果能参考gitnote https://gitnoteapp.com/ ，这个方案支持了后端github，但是作者自己不更新了，也不愿意开源让大家一起维护

### 描述可能的最优解决方案 Describe the optimal solution

本地数据库存储git repo跟踪，远端使用github等服务。
可以采用一次性买断的收费方式提供支持

**Comment by 88250** [comment]
本地文件在工作空间/data/ 下，可以自行使用 git。

**Comment by godvmxi** [comment]
> 本地文件在工作空间/data/ 下，可以自行使用 git。

那这样可以的，有没有什么触发信号，我可以考虑给你补充一个插件自动推送到git server

**Comment by godvmxi** [comment]
BTW,  账号注册机制能否支持邮箱注册，大陆手机号注销了很久了

**Comment by 88250** [comment]
> > 本地文件在工作空间/data/ 下，可以自行使用 git。
> 
> 那这样可以的，有没有什么触发信号，我可以考虑给你补充一个插件自动推送到git server

目前没有，建议不要在运行时使用任何外部同步方式，否则会造成文件占用。

> BTW, 账号注册机制能否支持邮箱注册，大陆手机号注销了很久了

不支持，只能通过手机号注册。
