### ISSUE TITLE
如何取消代码块的语言？

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6022]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如何取消代码块的语言，即不指定语言？

### 期待的结果 Expected result

略

### 版本环境 Version environment

```markdown
- Version: 2.2.3
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by Vanessa219** [comment]
没有办法取消哦，不需要的话可以设置为 plaintext
