### ISSUE TITLE
导出pdf将子文档整理为pdf的章节

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#6023]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

以一个大主题为核心，围绕这一些小主题，最后需要一起导出为pdf

### 描述可能的最优解决方案 Describe the optimal solution

以一个大主题为核心，围绕这一些小主题，最后需要一起导出为pdf

### 描述候选的解决方案 Describe the candidate solution

以一个大主题为核心，围绕这一些小主题，最后需要一起导出为pdf

### 其他信息 Other information

以一个大主题为核心，围绕这一些小主题，最后需要一起导出为pdf

**Comment by 88250** [comment]
如果后期有更多需求会重开 https://github.com/siyuan-note/siyuan/issues/3219 谢谢
