### ISSUE TITLE
UML修改后，有时会没有保存修改内容维持原样

### ISSUE THREAD

**Issue by s6492** [siyuan-note/siyuan#6024]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

UML修改后，有时会没有保存修改内容维持原样
编辑时，UML的内容有同步变化，但是关闭后还是原样

### 期待的结果 Expected result

能自动保存修改内容

### 版本环境 Version environment

```markdown
- Version: 2.2.3
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

-

**Comment by 88250** [comment]
麻烦录屏演示一下，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by s6492** [comment]
正确的说应该是嵌入块中的uml进行修改时，有时不会自动保存修改

https://user-images.githubusercontent.com/20492269/193394671-fcc62d78-a31a-43d9-80b7-124f3edc5741.mp4

**Comment by 88250** [comment]
请使用默认主题测试看看。

**Comment by s6492** [comment]
默认主题也一样，虽然不是每次会这样，概率问题

**Comment by 88250** [comment]
暂时不确定问题原因，跳转到定义处修改应该不会有问题。
