### ISSUE TITLE
文档树面板 `定位打开的文档` 显示在中间

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6033]
https://ld246.com/article/1664591875349

**Comment by Joe-rq** [comment]
嵌入块点击上下文时，也可以显示在中间吗？

**Comment by choyy** [comment]
大纲定位的标题也可以显示在中间吗？

**Comment by 88250** [comment]
这个 issue 只考虑文档树哦，其他需求麻烦单独提 issue 谢谢

**Comment by lentikr** [comment]
D大也要注意劳逸结合哇，国庆假期也注意休息 @88250
