### ISSUE TITLE
可否添加一个全局锁定按钮功能？

### ISSUE THREAD

**Issue by ohyessir** [siyuan-note/siyuan#6038]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候并不需要编辑文档，只需要查看或者复制就行，并不需要添加。但是经常会有没注意触碰到键盘添加内容但并没有留意到的情况。请问可否添加一个全局锁定，点一下不能添加，只能复制查看。再点一下解锁。默认是锁定

### 描述可能的最优解决方案 Describe the optimal solution

请问可否添加一个全局锁定，点一下不能添加，只能复制查看。再点一下解锁。默认是锁定

### 描述候选的解决方案 Describe the candidate solution

请问可否添加一个全局锁定，点一下不能添加，只能复制查看。再点一下解锁。默认是锁定

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/2648
