### ISSUE TITLE
选中内容合并为超级块

### ISSUE THREAD

**Issue by Maxpiner** [siyuan-note/siyuan#604]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
1.当块数较多时，关系图较为凌乱，文档碎片化严重。
2.有些连续的几个段落，或者段落+行间公式，编写时仅仅是出于排版习惯才分段，并没有必要视为数个块，完全可以看成一个整体。
3.仍然是出于简化关系图的需要，有时当某个标题下只有一个段时，对我而言在关系图中一个点就可以了

### 描述最优的解决方案 Describe the optimal solution
选中内容，右键菜单“合并块”。

### 描述候选解决方案 Describe the candidate solution
在全局视图中按shift选中几个点，右键菜单合并。

### 其他信息 Other information
另外，我觉得超级块看上去有点丑，或许有简洁大方一些的表现？

**Comment by 88250** [comment]
估计只能靠超级块语法来进行合并了，交互上你的建议很好，我们再考虑一下，谢谢。

**Comment by 88250** [comment]
关系图简化我们再考虑一下，这个交互暂时做不到，先关闭了，感谢提议。
