### ISSUE TITLE
资源 未引用 文件未与assets 目录文件区分开

### ISSUE THREAD

**Issue by HecterF** [siyuan-note/siyuan#6044]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

资源 未引用 文件未与assets 目录文件区分开，不方便去资源管理器定位查找

### 期待的结果 Expected result

将未引用 文件未与assets 目录文件区分开，单独存放一个目录，方便去资源管理器定位查找

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
未引用资源可以复用从而转换为引用资源，所以设计上不区分目录的，否则引用路径也会发生变化。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
