### ISSUE TITLE
资源 界面 不支持出图片之外文件的预览

### ISSUE THREAD

**Issue by HecterF** [siyuan-note/siyuan#6045]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

资源 界面 不支持出图片之外文件的预览

### 期待的结果 Expected result

可预览 .txt  .log  .pdf  .zip 等格式

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
这些格式暂时不考虑支持，特别是 zip，估计无法预览，感谢提议。
