### ISSUE TITLE
资源 界面 未引用文件不支持多选

### ISSUE THREAD

**Issue by HecterF** [siyuan-note/siyuan#6046]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

资源 界面 未引用文件不支持多选，要么只能删一个，要么全删。删一个的时候，每次都要确认一遍。效率低。

### 期待的结果 Expected result

支持一次确认多个文件，再多选之后，一次性删除。

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无。

**Comment by 88250** [comment]
确认可以使用回车这样能简化一些，多选目前不考虑支持，感谢提议。
