### ISSUE TITLE
关于改进浏览器插件 - 集成思源笔记到搜索引擎的搜索结果中

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#6047]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

[关于改进思源笔记的浏览器插件 - 集成到搜索引擎的搜索结果中 - Diamond 的回帖 - 链滴](  https://ld246.com/article/1664554604508/comment/1664628222972#comments  )    

### 描述可能的最优解决方案 Describe the optimal solution

改造思源笔记的浏览器插件，使其不仅仅是用来剪藏，和可以展示搜索结果

**Comment by 88250** [comment]
这个我们估计不会实现，如果有社区开发者看到可以考虑帮忙改进，感谢提议。
