### ISSUE TITLE
弹窗和题头图选择器提议

### ISSUE THREAD

**Issue by svchord** [siyuan-note/siyuan#6049]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

弹窗需要区分为笔记本设置、搜索替换、数据历史、软件设置、属性修改、移动文档、重命名文档、新建日记选择等弹窗；

题头图需要区分为无图无emoji、有图无emoji、无图有emoji、有图有emoji四种状态。

### 描述可能的最优解决方案 Describe the optimal solution

给.b3-dialog__container和.protyle-background添加不同的属性

**Comment by Vanessa219** [comment]
这样细化，会不会导致风格不太一致。可以具体说一下所呈现的效果和必须的场景么？

**Comment by svchord** [comment]
只是添加属性选择器，应该不会影响风格之类的吧……我理想的方案就类似现在.history__repo的data-type属性。

我现在想要呈现的效果是：

1. 搜索替换弹窗的宽度尽量宽、软件设置弹窗宽度适中、笔记本设置弹窗较窄，属性修改、移动文档、重命名文档、新建日记选择等弹窗也希望能有宽度细分
2. 题头图的四种不同场景下，标题距离文档顶部的高度也不同

**Comment by Vanessa219** [comment]
1. 感觉每种类型的弹框宽度依赖 CSS 选择器来设定其宽度不太合适，应该在弹出的时候通过 js 设置好就可以了。如果觉得哪一种类型的宽度不太好，可以在程序中统一进行修改。
2. 题头图的话可以把 `position: absolute;` 移除，然后用内部元素的 `margin` 或 `padding` 来调整试试。

**Comment by svchord** [comment]
1. 我之后试试看用js设置吧
2. 我主要是想调整.protyle-background的高度，但目前发现会出现有很多不同的高度（56px、64px、92px、96px、100px），不知道是为什么，所以想用选择器固定下来

**Comment by Vanessa219** [comment]
1. 觉得不太合理的可以直接 PR 修改就可以了，合理的都必将采纳
2. 我会根据有无背景对 `min-height` 进行设置，应该重置一下这个就可以了
