### ISSUE TITLE
软件启动错误

### ISSUE THREAD

**Issue by AiProgram** [siyuan-note/siyuan#605]
### 描述问题 Describe the problem
软件启动时经常出现如下图所示的错误，重装后解决

### 期待的结果 Expected result
正常启动
### 截屏或录像 Screenshot or video
![image](https://user-images.githubusercontent.com/13717071/100616254-c710c800-3353-11eb-9ecd-d6387ce9680f.png)

### 版本环境 Version environment

* 版本 Version：0.4.94
* 操作系统 Operating system：win10专业版 2004
* 浏览器（如果使用）Browser (if used)：无

**Comment by 88250** [comment]
请问重装以后没有再出现了吧？

**Comment by AiProgram** [comment]
> 请问重装以后没有再出现了吧？

目前没有发现

**Comment by 88250** [comment]
请帮忙继续观察。首次出现的问题我们基本能够定位到了，后续进行改进，谢谢。

**Comment by 88250** [comment]
主要问题是因为启动新版本时老版本内核没有退出，我们在 v0.5.0 中做了一些改进。提示用户老版本内核将被自动关闭，并需要用户手动重启思源：

![image](https://user-images.githubusercontent.com/873584/100692130-25c25a00-33c5-11eb-9479-521c1007321b.png)
