### ISSUE TITLE
切换工作空间后，使用相同云端同步目录，云同步失败

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#6050]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

<img width="370" alt="image" src="https://user-images.githubusercontent.com/33319484/193460258-22d54547-adfa-46e0-b728-d02d2cb6240e.png">

切换空间目录，输入秘钥，选择要同步的云端目录后，点击同步，在同步后几分钟，就会出现这个错误。在这里并没有使用第三方同步软件，也没有直接在文件管理器中去修改文件，但就是冒出了这个问题，且云端上的多个同步目录在同步到本地后都会出现这样的问题。

### 期待的结果 Expected result

期待能够正常同步到本地

### 版本环境 Version environment

```markdown
- Version: v2.2.2
- Operating System: mac 12.5
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9692821/siyuan.log)

**Comment by 88250** [comment]
v2.1.10 之前的版本同步会导致这个问题，建议切换一个云端目录用最新版重新同步一次。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by JokeenZhang** [comment]
即便了升级到最新版本，问题还是再次出现了

<img width="372" alt="image" src="https://user-images.githubusercontent.com/33319484/193468594-749f5b68-493c-4f89-8b23-a64e6eacc69b.png">

起初公司电脑先升级到2.2.0版本后，当天就在那台电脑写了些东西，然后本想在家里的电脑升级并同步数据，只是没想到的是家里的mac电脑在盒盖前没关思源，解锁后习惯性点开程序坞上的图标，然后就开始同步数据，所以这时候是慌张的，担心有些数据出问题。

第二天到公司打开软件前先备份data，再打开思源同步，同步结束后，关闭思源并将备份的data覆盖，然后再打开思源同步上去。只是回家后觉得有些不妥，因此在家里的电脑上同步下来后又增加新的云端目录并同步上去，所以这里就多了个云端目录。

只是现在的问题是两个目录都不能同步。在最后一次同步云端的记录，是公司那台电脑同步上去的，且两台电脑都是2.2.3，只是家里的mac一直同步失败所以就降级了。

上面的提示重置数据仓库，是否就按照提示进行操作，这样会对数据产生一些隐患吗？

**Comment by JokeenZhang** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/33319484/193469129-e508e13c-abdc-4f7d-95a6-cb9a684e8306.png">

在重置数据仓库后同步还是失败。或许只能在节后用公司那边的数据来作为最终基准，删除云端数据再同步了

**Comment by 88250** [comment]
只是重置本地的话可能没用，需要重新使用新的云端目录。

**Comment by JokeenZhang** [comment]
只能节后回去拿到data后重新上传到新的云端目录

**Comment by JokeenZhang** [comment]
@88250  我将以前上周备份的数据，那时用的应该是2.2.0之前版本，然后将它们上传到新的云端目录后，接着又再创建新的工作空间去同步这个新的云端目录，还是出现了同步失败，期间并没有别的电脑去操作，也没有用别的同步软件，不知道这个问题是怎么出现的，是因为新的云同步方案有bug吗？ 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/33319484/193636125-6dd6c1c8-fdb0-41b7-a2fa-5f665137bb96.png">

**Comment by 88250** [comment]
@JokeenZhang 设置 - 关于 - 导出系统日志上传一下。

**Comment by JokeenZhang** [comment]
[system-log.zip](https://github.com/siyuan-note/siyuan/files/9707846/system-log.zip)

昨天的数据删除了，今天再次新建工作空间去同步昨天上传的云端目录后失败，这是导出日志

**Comment by 88250** [comment]
有两个问题需要排除一下：

* 没有使用第三方实时同步盘（比如坚果云、iCloud 等）或者任何可能导致本地文件变更的第三方软件（比如硬盘实时加密程序）
* 新建的工作空间不要使用已经用过的工作空间名称（比如 main）

**Comment by JokeenZhang** [comment]
- 这里没有使用到第三方同步盘，期间也不会有其他软件会读取到这个路径里的文件，不同软件使用的目录都是固定的，不会都放在一起
- 新建的工作空间都是新的，当看到有这样的问题后，我都是以sy+序号来命名工作空间，以前没有这样的做法

**Comment by 88250** [comment]
有配置过忽略文件吗？

**Comment by JokeenZhang** [comment]
没有配置

**Comment by 88250** [comment]
使用新的云端目录上传时候的日志麻烦提供一下。
