### ISSUE TITLE
超级块默认内置

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#606]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

关系图使用时,当前关系图碎片化严重,手动选中段落再设置为一个超级块又较为繁琐,可以设置文档块下自然带一个超级块
### 描述最优的解决方案 Describe the optimal solution
文档块下自然带有超级块,所有子块均在该超级块内,"enter"为换行,如需跳出该超级块可通过按"shift+enter"跳出并自动生成新的超级块,光标移动至超级块内或可通过设置将"enter"与"shift+enter"的功能进行更换

类似功能软件:logseq
### 描述候选解决方案 Describe the candidate solution

[需求604](https://github.com/siyuan-note/siyuan/issues/604)

**Comment by 88250** [comment]
你好，关系图方面的问题我们计划在 v0.7.0 开始进行调整。

因为超级块不是 Markdown 标准语法，所以直接默认在标题块后启用的话可能不是太适合。 #604 中的方式可能较为适合，我们后续会进行考虑，谢谢。
