### ISSUE TITLE
通过浏览器使用时，剪切再粘贴会导致光标飞到文档开头

### ISSUE THREAD

**Issue by xuzheliang135** [siyuan-note/siyuan#6060]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

通过浏览器使用时，通过`ctrl+X`和`ctrl+V`快捷键进行剪切和粘贴时，光标会滚到文档开头，打断编辑

### 期待的结果 Expected result

粘贴后，光标仍留在原位，可以继续编辑

### 版本环境 Version environment

```markdown
- Version: 2.2.3
- Operating System: Win10
- Browser (if used):Microsoft Edge 版本 105.0.1343.53 (正式版本) (64 位)
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/9704684/system-log.zip)

**Comment by 88250** [comment]
我这里在 Edge 和 Chrome 均无法重现你说的问题，是否存在某些浏览器扩展影响的可能性？

**Comment by xuzheliang135** [comment]
我使用edge的隐身模式（没有允许扩展在其中运行），问题依旧存在。不过考虑到其他应用程序和我改了个别思源的快捷键的问题，我会尝试用更干净的环境尝试，但是在我这里非常好复现，之后会附上录屏。

**Comment by xuzheliang135** [comment]
录屏传不上去，直接发送给你的邮箱了。
我用了几乎全新的设备（不常用的电脑，docker部署在公网ip上，端口映射到36806），删除了edge的配置，关闭了所有的开机启动。重启后，还关闭了所有的后台程序。之后访问对应网址，新建笔记本和文档，快捷键进行剪切和粘贴，问题依旧。
windows版本为19044.2006，edge版本如上，这两个版本应该不用精确一致，我的非主力机有两个月没用了，肯定没更新到这么新。
你也可以使用这个网址进行访问我的文档环境，我应该还会开一段时间。202.112.26.111:36806/stage/build/desktop/?r=i7j1zyo

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by xuzheliang135** [comment]
我看了你的录屏，请使用`ctrl+X`与`ctrl+V`进行剪切粘贴，复制粘贴并不会出现问题。
同时尽量只选择部分文字，而不是多个块（虽然多个块应该也能触发）

**Comment by 88250** [comment]
我在你的环境上确实可以重现，麻烦继续保持环境打开，我们再定位一下问题。
