### ISSUE TITLE
收集箱可以内部编辑

### ISSUE THREAD

**Issue by Jamie-Wan** [siyuan-note/siyuan#6062]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

一般我会把所有需要保存的微信链接网址打成文档，再粘贴到思源的微信对话框里。在收集箱里的链接是可以点击的，转换到文件夹里后链接变成文本，无法直接点击；希望可以直接在收集箱里编辑文字，删掉不需要的链接。

### 描述可能的最优解决方案 Describe the optimal solution

收集箱内加入简单的编辑功能，能打字就行了

**Comment by choyy** [comment]
现在的收集箱只能整个转成一个文档，对于长文还好
但是对于一些碎片化的东西很不友好，这些东西一般并不想生成一个文档，而是移动到已有的文档中，现在的话只能复制粘贴，还是不太方便，如果可以直接拖动到文档里就好了

**Comment by 88250** [comment]
链滴上有类似提议，目前不考虑了，谢谢。

https://ld246.com/article/1664813508078
