### ISSUE TITLE
为 转换为无序列表/有序列表 添加快捷键

### ISSUE THREAD

**Issue by xuzheliang135** [siyuan-note/siyuan#6064]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

希望使用快捷键将当前光标所在块，或者选中块转换为无序列表/有序列表

### 描述可能的最优解决方案 Describe the optimal solution

为`转换为无序列表/有序列表`添加快捷键

**Comment by 88250** [comment]
使用 Ctrl+/ 唤出块级菜单，然后通过方向键选择转换即可。

**Comment by 88250** [comment]
直接在开头处输入 `* ` 或者 `1. ` 应该也行，是否是高频操作这个不好说，比如有的主要写文字的用户就用不到。

**Comment by 88250** [comment]
目前暂时不考虑了，继续收集一下反馈再决定，谢谢。
