### ISSUE TITLE
文档树 快捷键删除/批量删除

### ISSUE THREAD

**Issue by xuzheliang135** [siyuan-note/siyuan#6066]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

整理文件树时，无法通过`delete`快捷键删除文档，同时也无法多选文档批量删除。

### 描述可能的最优解决方案 Describe the optimal solution

点击文档时，焦点不定位到编辑区，而是选中左侧文档树对应文档，此时点击`delete`删除文档。
左侧文档树同时支持通过`ctrl`和`shift`快捷键进行多选，多选后可以使用`delete`快捷键批量删除。
当前的`delete`快捷键必须右键文档才能使用，而且时灵时不灵。

**Comment by 88250** [comment]
* 使用方向键选中以后再按 Delete
* 多选请关注 https://github.com/siyuan-note/siyuan/issues/1359
