### ISSUE TITLE
导出时可选只导出锚文本不包含文件名

### ISSUE THREAD

**Issue by xxhh12a** [siyuan-note/siyuan#6068]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前导出word、pdf、html均包含文件名，如图所示，希望能够导出时增加选项不包含文件名，只导出锚文本
<img width="467" alt="截屏2022-10-05 22 11 48" src="https://user-images.githubusercontent.com/55382340/194082107-3227a24a-0ce9-4d11-b498-8877a92ffe0b.png">

### 描述可能的最优解决方案 Describe the optimal solution

导出时增加选项不包含文件名，只导出锚文本

### 描述候选的解决方案 Describe the candidate solution

暂无

### 其他信息 Other information

暂无

**Comment by 88250** [comment]
暂时不考虑了，后续会继续收集类似需求，如果需要的人多我们再考虑，谢谢。
