### ISSUE TITLE
HTML 块预览开关

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#607]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

写笔记的时候插入音乐或者视频的时候。

### 描述最优的解决方案 Describe the optimal solution

允许用户填写 iframe 代码，进行一些链接的嵌入。
![image](https://user-images.githubusercontent.com/16383685/100704066-c887d200-33df-11eb-9de7-4d690cb4131c.png)
![image](https://user-images.githubusercontent.com/16383685/100704085-d5a4c100-33df-11eb-8a23-920ae4c5aa42.png)

### 描述候选解决方案 Describe the candidate solution

Null。

### 其他信息 Other information

思源现状，待优化。
![image](https://user-images.githubusercontent.com/16383685/100703771-2cf66180-33df-11eb-89de-a1566962a6f8.png)

**Comment by Vanessa219** [comment]
不显示 iframe 源码的话，没法进行修改。你想优化成什么样子呢？

**Comment by woniuxia** [comment]
类似于代码块那样的处理方式？
光标在块内，就显示源码，不在的时候就掩藏？

**Comment by 88250** [comment]
计划在 v0.5.2 中加入 HTML 块预览开关，和代码块/数学公式块预览开关类似，感谢反馈。

**Comment by 88250** [comment]
v0.5.4 实现，谢谢。
