### ISSUE TITLE
设置中部分限制字段设置为 `0` 表示为无限制

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6072]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

例如 `设置`>`文档树`>`页签打开最大数量`, 使用主题设置为多行页签/纵向页签后就无需设置最大数量

### 描述可能的最优解决方案 Describe the optimal solution

- 编辑器
  - 历史保留天数: 0 表示清空并禁用历史
  - 块引动态锚文本最大长度: 0 表示动态锚文本不限制长度
- 文档树
  - 最大列出数量: 0 表示无限制
  - 页签打开最大数量: 0 表示无限制
- 搜索
  - 搜索结果显示数: 0 表示无限制

**Comment by 88250** [comment]
这几个必须要有上限的，否则可能会导致内核或者界面卡死。

**Comment by Zuoqiu-Yingyi** [comment]
> 这几个必须要有上限的，否则可能会导致内核或者界面卡死。

`页签打开最大数量` 与 `块引动态锚文本最大长度` 这两项可以设置无限制嘛, 这两项应该不会导致阻塞

**Comment by 88250** [comment]
会的，不然也不会有这些配置项了。
