### ISSUE TITLE
导出的HTML格式的笔记，可否加入目录的索引

### ISSUE THREAD

**Issue by mengshuangqing** [siyuan-note/siyuan#6075]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

比如我笔记导出为HTML后，我需要快速定位某一个标题下的操作，目前手段是需要ctrl+f去搜索，但是更希望类似于PDF那样，在左侧或者右侧有目录的提示

### 描述可能的最优解决方案 Describe the optimal solution

https://www.matools.com/api/java8
类似于jdk的说明文档，一遍是目录，大标题，小标题，右侧则是具体内容

### 描述候选的解决方案 Describe the candidate solution

类似于Help manual 软件的生成效果

### 其他信息 Other information

我王者巅峰1800的辅助

**Comment by 88250** [comment]
这个之前有过提议 https://github.com/siyuan-note/siyuan/issues/4629 

暂时先不考虑了，如果后续要做的话会重新打开 #4629 谢谢。
