### ISSUE TITLE
字符“？”输入与鼠标位置问题

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#6082]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

很早在链滴社区发帖的时候就有这种问题，最近使用浏览器访问思源笔记又发现这个问题：
输入文字时，光标在文字最后面，这个时候我使用  shift+？  输入问号的时候，问号不是输入到光标的地方，而是输入到鼠标悬浮的地方

### 期待的结果 Expected result

可能是编辑器问题？！？

### 版本环境 Version environment

```markdown
- Version: v2.3.0
- Operating System: windows 10
- Browser (if used):谷歌浏览器
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
能截图或者录屏看下吗？

**Comment by Geo123abc** [comment]
![](https://s3.bmp.ovh/imgs/2022/10/08/e9dd1623d6f2d7a2.gif)

1. 这种情况在链滴社区、浏览器访问思源笔记都会出现，
2. 思源笔记客户端直接使用不会出现这个问题
3. 只要是和shift有关的输入都是这样
4. 好像是摁了shift按键之后，输入光标会移动到鼠标所在的位置，所以会出现这种情况

**Comment by Vanessa219** [comment]
思源和脸滴上都重现不了，是不是之前做了什么操作，或者是浏览器安装了什么插件？

**Comment by Geo123abc** [comment]
> 思源和链滴上都重现不了，是不是之前做了什么操作，或者是浏览器安装了什么插件？

真相了，是我自己浏览器插件的原因（虽然还没定位到哪个插件）
谢谢
