### ISSUE TITLE
提及面板没有转换为双链引用的功能

### ISSUE THREAD

**Issue by tomatl45** [siyuan-note/siyuan#6084]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [x] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

你好，

我在[这里](http://www.9tjj.com/27277/)看到，提及面板中有一个按钮可以方便地将提及当前页面的纯文本直接转换为双链引用，如下图1所示。

<img width="1252" alt="图1 - 右边可以看到转换为双链引用的选项" src="https://user-images.githubusercontent.com/103080586/194681093-04eb0daa-1336-4970-96a3-e94704b83459.png">

不过，我的思源笔记看起来没有这个功能，如下图2所示。

![图2 - 右边没有转换为双链引用的选项](https://user-images.githubusercontent.com/103080586/194681156-28621fe8-8fb8-417e-ac24-fef27cf302c9.png)

[这里](http://www.9tjj.com/27277/)说，

> 提及：就是系统自动显示的潜在反向链接，可以鼠标划过提及内容的右侧三点，出现 🔗 符号，点击即可生成一个反向链接。

但我即使鼠标划过提及内容的右侧和右侧附近，也仍然不能看到任何选项。

### 期待的结果 Expected result

请问我应该进行哪些设置或操作，以找到提及面板里的转换为双链引用的功能？

### 版本环境 Version environment

```markdown
- Version: v2.3.0
- Operating System: Linux
- Browser (if used): Firefox
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9738155/siyuan.log)

### 更多信息 More information

我使用的是AppImage版本的思源笔记。

**Comment by 88250** [comment]
v2.3.0 重写了反链面板，我们认为这个功能已经不再需要，因为新的反链面板已经可以直接编辑，选中关键字后通过 Alt+[ 可以更方便地搜索并链接。
