### ISSUE TITLE
可否加入功能：可以为文档添加密码访问

### ISSUE THREAD

**Issue by TerickJojo** [siyuan-note/siyuan#6089]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

协作的时候，某些文档需要对部分成员开放而不是全部

### 描述可能的最优解决方案 Describe the optimal solution

1. 方便的话添加密码访问
2. 后期可考虑对成员分组

**Comment by 88250** [comment]
思源笔记目前的定位是个人笔记，所以暂时不会考虑协作相关功能，谢谢。

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/9800
