### ISSUE TITLE
鼠标悬浮在容器块的第一个下级块时显示完整层级块标

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6090]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

经测试, 包含其他类型块的列表项在鼠标悬浮时都可以显示列表项的块标, 但只包含一个嵌入块的列表项在鼠标悬浮时不显示列表项的块标

### 期待的结果 Expected result

只包含一个嵌入块的列表项在鼠标悬浮时显示列表项的块标

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/49649786/194687443-6a3e6567-6011-4a51-ad42-b32534a5a462.png)

### 版本环境 Version environment

```markdown
- Version: 2.3.0
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
列表下只有一个列表项块且只有一个子块时不会有块标：

![image](https://user-images.githubusercontent.com/873584/194687564-b6733328-727b-4af3-ae93-deb85dac6f84.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 列表下只有一个列表项块且只有一个子块时不会有块标：
> 
> ![image](https://user-images.githubusercontent.com/873584/194687564-b6733328-727b-4af3-ae93-deb85dac6f84.png)

哦哦, 不过为啥不显示块标呢
还有列表项内第一个块的块标也不显示❓

**Comment by Zuoqiu-Yingyi** [comment]
其他容器块的第一个块的块标也都会显示

**Comment by 88250** [comment]
这个是之前做的优化，估计不会改动了。如果需要块标菜单，可以用 Ctrl+/ 唤出。
