### ISSUE TITLE
关闭应用的时候保存文档的打开的状态，重新打开应用的时候自动恢复

### ISSUE THREAD

**Issue by fade03** [siyuan-note/siyuan#6098]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

关闭思源笔记之后重新打开，左侧文档树默认全部折叠，还需要逐层打开之前的文档。

不知道在关闭应用的时候可不可以保存笔记的打开的情况，这样再启动应用的时候就可以恢复关闭之前的状态，除去了再逐级打开文档的冗余操作。

### 描述可能的最优解决方案 Describe the optimal solution

可以给文档做一个标记（opened），启动应用的时候读取所有文档的这个标记，然后自动打开所有被标记的文档。

### 描述候选的解决方案 Describe the candidate solution

-

### 其他信息 Other information

-

**Comment by 88250** [comment]
页签状态以及会保持，可以用文档树定位功能再展开文档树。文档树的展开状态保留目前暂时不考虑，谢谢。
