### ISSUE TITLE
支持使用模板为文档设置块属性

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6100]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

文档块作为一种常用的块, 但是目前除了 API 没有其他快速设置文档块属性的方案

### 描述可能的最优解决方案 Describe the optimal solution

模板文件的第一行有效内容(忽略`.action{}`)如果为 IAL Token, 则将其设置为文档的 IAL
将一篇文档导出模板时可选是否包含文档块属性
目前看没有二义性, 且向后兼容之前的模板

### 示例1

- 为文档设置块属性 `name`: `foo`
- 在光标处插入内容 `bar` 并为当前块设置块属性 `name`: `foobar`
```markdown
{: name="foo"}
bar
{: name="foobar"}

```
### 示例2

- 为文档设置块属性 `name`: `foo`
- 为当前块设置块属性 `name`: `bar`

```markdown
{: name="foo"}
{: name="bar"}

```
### 示例3

- 不设置文档块的块属性
- 为当前块设置块属性 `name`: `foo`

```markdown
<!-- 这里有个空行 -->
{: name="foo"}

```
### 示例4

- 不设置文档块的块属性
- 在光标处插入内容 `foo` 并为当前块设置块属性 `name`: `bar`

```markdown
foo
{: name="bar"}

```

### 其他信息 Other information

最好也支持使用 IAL 的 `title` 属性更改文档名

**Comment by 88250** [comment]
在文档内通过模板修改文档属性不大妥，这好比是通过子块属性修改父块属性。较为合理的应该是通过模板创建文档时携带模板属性。

先关闭了，感谢提议。

**Comment by SamoyedY** [comment]
支持模板创建文档时携带模板属性就好, 挺需要这个功能的

**Comment by Zuoqiu-Yingyi** [comment]
> 在文档内通过模板修改文档属性不大妥，这好比是通过子块属性修改父块属性。较为合理的应该是通过模板创建文档时携带模板属性。

这里是不是可以通过 YFM 的格式在创建文档设置文档块属性

**Comment by 88250** [comment]
感觉没有必要……

**Comment by Zuoqiu-Yingyi** [comment]
> 感觉没有必要……

感觉属性视图能用上呀, 通过模板批量创建具有相同属性的文档块

**Comment by 88250** [comment]
属性视图应该用不上，属性都是自动添加的。
