### ISSUE TITLE
希望能够添加文档树的多选功能

### ISSUE THREAD

**Issue by jimmyyukio** [siyuan-note/siyuan#6101]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在进行文件批量管理时，需要手动一个个的移动，文档较多时比较麻烦

### 描述可能的最优解决方案 Describe the optimal solution

添加文档树的多选功能，能够批量处理

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/1359
