### ISSUE TITLE
2.3.1版本，分隔线仍然被折叠

### ISSUE THREAD

**Issue by jimmyyukio** [siyuan-note/siyuan#6102]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

2.3.1版本，分隔线仍然被折叠

### 期待的结果 Expected result

分隔线不会被折叠

### 版本环境 Version environment

```markdown
- Version: 2.3.1
- Operating System: windows 11
- Browser (if used):
```

### 日志文件 Log file

如图
![Snipaste_2022-10-08_22-28-58](https://user-images.githubusercontent.com/60495173/194712603-4cc7ebeb-f702-4357-8242-5b23f3ff4b17.png)
![Snipaste_2022-10-08_22-29-16](https://user-images.githubusercontent.com/60495173/194712607-6723bf4f-47ff-45aa-9743-24e1fd51b251.png)

log file：
[siyuan.log](https://github.com/siyuan-note/siyuan/files/9739484/siyuan.log)

**Comment by Vanessa219** [comment]
是以前折叠的么？现在点击块标应该是没有折叠选项了，你怎么折叠的？

**Comment by jimmyyukio** [comment]
我就是点这个旁边的折叠按钮呀
![图片](https://user-images.githubusercontent.com/60495173/194712997-822a4b2d-43c4-4779-8444-5c05199af9f9.png)

**Comment by Vanessa219** [comment]
这个是标题的，和分割线没关系。

**Comment by jimmyyukio** [comment]
噢好的
