### ISSUE TITLE
使用官方同步因未知原因导致显示数据仓库因外部变更损坏

### ISSUE THREAD

**Issue by jimmyyukio** [siyuan-note/siyuan#6109]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

问题是昨天更新2.3.1后出现的，昨天更新后到今天遇到过两次了，使用的官方同步，没有从外部变更数据库内容和使用第三同步，但使用过程中突然提示数据库损坏要求重置数据库

### 期待的结果 Expected result

希望告知问题所在，或解决

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Snipaste_2022-10-09_10-21-51](https://user-images.githubusercontent.com/60495173/194734664-9732e697-8120-430c-81fa-a3b11914c3ae.png)

### 版本环境 Version environment

```markdown
- Version: 2.3.1
- Operating System: windows 11 22H2
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9740631/siyuan.log)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6106

**Comment by jimmyyukio** [comment]
OK
