### ISSUE TITLE
软件运行不了打不开

### ISSUE THREAD

**Issue by wanguano** [siyuan-note/siyuan#6112]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我试了 2.3.1 很多思源笔记版本，都是这个系统运行不了，我尝试更新系统，微软运行库各种方法都尝试了，还是不能运行（删除用户.config文件夹重启还是运行不了此软件）。
系统：windows11  22H2版本，是不是软件用到了哪些依赖库，我没有安装？？

### 期待的结果 Expected result

期待软件运行正常，能打开看到界面

### 截屏或者录屏演示 Screenshot or screen recording presentation

![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/Snipaste_2022-10-09_11-24-38.png)

![](https://mingcloudpic.oss-cn-beijing.aliyuncs.com/img/siyuan.gif)

### 版本环境 Version environment

```markdown
- Version: 2.3.1
- Operating System: window11 22h2
- Browser (if used):106.0.5249.103
```

### 日志文件 Log file

我工作空间创建不了，并且用everything软件全局搜索不到该日志文件

### 更多信息 More information

我尝试用虚拟机Windows7运行此软件，是正常没问题的。我之前有反馈过，我是真想使用思源笔记来使用。

**Comment by 88250** [comment]
抱歉了，这个问题我们估计也没法定位解决，可能还是和系统某些配置有关系。
