### ISSUE TITLE
切换到【跟随系统】模式后，当前打开的那个文档显示有异常

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#6118]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

切换到【跟随系统】模式后，当前打开的那个文档显示有异常，是空白的；此时去分屏，控制台会打印报错信息。不知道这个问题是不是个例，先记录一下。

### 期待的结果 Expected result

模式切换后，正常显示文档

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/58081876/194751907-e1323403-4933-45a2-bb27-1f90f7d43c62.mp4

### 版本环境 Version environment

```markdown
- Version: 2.3.2
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

none

**Comment by Vanessa219** [comment]
切换后有个过渡图片是在刷新界面的意思么？
我按照你的步骤操作了，重现不了，你使用默认的黑色和白色主题再试试？

**Comment by BryceAndJuly** [comment]
这个是默认主题。哦，我现在知道了，之前加在默认主题里的theme.js里有段脚本可能影响了，删了theme.js之后就好了。
