### ISSUE TITLE
文件树上下分割，上边为文件夹，下边为文件

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#612]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

在不同的文件夹之间查看多个文档

### 描述最优的解决方案 Describe the optimal solution

目前左侧的文件栏是和 Typora 一样的单栏树形，在展开一个目录后，如果这个目录的文件较多，就会将下面的目录挤出屏幕外，想查看下面的目录，还得先点南下当前的目录，将它收起来。

![image](https://user-images.githubusercontent.com/19181833/100758018-feea3f00-3429-11eb-9844-507dd25b6ef7.png)

我建议能够引入上下两栏文件栏的样式，当然，不是替代，而是多一种选择。

典例是 [VNote](https://github.com/vnotex/vnote)，如下图，左侧的文件栏被分成上下两部分，当鼠标在上面单选文件夹时，下面半栏就会显示其中的 md 文档条目，而上面半栏不需要展开而将下面的目录挤出屏幕。这种布局可以极大地方便在不同文件夹之间浏览文档。

![image](https://user-images.githubusercontent.com/19181833/100757988-fa258b00-3429-11eb-9338-ce8e512e0b83.png)

**Comment by 88250** [comment]
先用分屏顶顶，后面考虑。

**Comment by ayue2019** [comment]
类似OneNote那种**笔记本-分区-页面**的形式，可能是更好的选择
![image](https://user-images.githubusercontent.com/58946586/105635704-50013700-5e9f-11eb-9789-b0cdb5ef0443.png)

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。
