### ISSUE TITLE
文件树中文档前加上图标

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#613]
![image](https://user-images.githubusercontent.com/19181833/100767211-758c3a00-3434-11eb-96be-063b0ccbc258.png)

![image](https://user-images.githubusercontent.com/19181833/100767229-7ae98480-3434-11eb-906d-495b5aec28bb.png)

![image](https://user-images.githubusercontent.com/19181833/100767261-8341bf80-3434-11eb-9453-77a68351d5d3.png)

![image](https://user-images.githubusercontent.com/19181833/100767372-a8363280-3434-11eb-9cc7-67a82be1553e.png)

所以建议一：在文档名左侧，加上个文档图标，也就是像 Typora 那样：

![image](https://user-images.githubusercontent.com/19181833/100767404-b2583100-3434-11eb-8336-412e8720bf8d.png)

但是，像 Typora 那样，也会有一个小问题：

![image](https://user-images.githubusercontent.com/19181833/100767469-c3a13d80-3434-11eb-89f8-d116619e55af.png)

![image](https://user-images.githubusercontent.com/19181833/100767514-d4ea4a00-3434-11eb-82d2-3559401dacc9.png)

所以建议二：在文档左侧，加上文件树结构线，也就是像 VNote 或者注册表编辑器那样：

![image](https://user-images.githubusercontent.com/19181833/100767893-3c07fe80-3435-11eb-8abc-587195cd51ec.png)

![image](https://user-images.githubusercontent.com/19181833/100767685-0531e880-3435-11eb-8c8f-4128e20cce27.png)

当然，最好能引进上下两栏的目录视图：

![image](https://user-images.githubusercontent.com/19181833/100767994-593ccd00-3435-11eb-9a10-edf8aefae751.png)

不用担心分不清下面的视图处在哪个目录下，因为：

![image](https://user-images.githubusercontent.com/19181833/100768078-71145100-3435-11eb-81b6-57e7db39f622.png)

**Comment by 88250** [comment]
我们先在文档前加个 Markdown 的图标看下效果，谢谢。
