### ISSUE TITLE
行级代码、键盘和标签位于段首时光标交互改进

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6133]
https://ld246.com/article/1665291726758

**Comment by choyy** [comment]
当行内代码位于无序列表开头时, 光标好像无法移动到其边框开头外部

**Comment by Vanessa219** [comment]
> 当行内代码位于无序列表开头时, 光标好像无法移动到其边框开头外部

https://github.com/siyuan-note/siyuan/issues/6529
