### ISSUE TITLE
光标位于段落块首的图片前时无法显示

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6136]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

1. 光标使用方向键 <kbd>←</kbd> 移动至位于段落块首的图片前时无法显示, 虽然编辑时可以在段落块首正常编辑
   - 当图片前有文字内容时, 删除该文字后, 光标可以正常使用方向键 <kbd>←</kbd> 移动至段首, 但是位于段首时光标垂直居中显示
2. 光标使用 <kbd>Home</kbd> 无法移动至位于段落块首的图片前, 只能移动到段首图片后
3. 光标使用方向键 <kbd>←</kbd> 或 <kbd>Home</kbd> 移动至位于段落块首的行内元素前面时, 虽然编辑时位于行内元素外面, 但是光标依然在行内元素里面(光标位于行内元素外面:![image](https://user-images.githubusercontent.com/49649786/194799011-f8136cde-421f-4990-8584-fc3a1f5499c7.png); 光标位于行内元素里面:![image](https://user-images.githubusercontent.com/49649786/194799039-2b84efd3-f55a-44de-bd7e-e79412eda853.png))

### 期待的结果 Expected result

1. 光标使用方向键 <kbd>←</kbd> 移动至位于段落块首的图片前时正常显示(不垂直居中, 以免图片高度较大时光标移出视野外)
2. 光标使用 <kbd>Home</kbd> 移动至位于段落块首的图片前并正常显示
3. 光标在位于段首的行内元素内外时正常区分显示在元素内外

### 版本环境 Version environment

```markdown
- Version: 2.3.2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
3. https://github.com/siyuan-note/siyuan/issues/6133
