### ISSUE TITLE
段落块首输入 `$$` 会将当前段落的 HTML 源码转换为公式块内容

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6137]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在当前段落块行首输入 `$$` 会将当前段落的 HTML 源码转换为公式块内容, 因此非空段落块的 DOM 会转换为公式块内容

![image](https://user-images.githubusercontent.com/49649786/194800649-a5f3d85d-6d73-4f10-8eae-19a81a7c31f4.png)

### 期待的结果 Expected result

非空段落块首输入 `$$` 不会将当前块转换为公式块

### 版本环境 Version environment

```markdown
- Version: 2.3.2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
这个目前是解析器的特性，因为公式没有标准 Markdown 语法可参考，允许使用 `$$` 不带换行触发解析。
