### ISSUE TITLE
删除带PDF附件的笔记时未同步删除assets下的PDF文件

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#6139]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

将PDF复制到笔记里，做了一些高亮笔记。然后删除该笔记，发现assets下PDF仍在。未引用的资源下面也没有展示该PDF。

也就是说思源认为该PDF仍被引用。

- 重建索引无效。
- 清除历史无效。

### 期待的结果 Expected result

PDF文件同步删除。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/5968678/194817170-8fa62d30-0c52-44b1-98e7-189530bbd2f3.png)

### 版本环境 Version environment

```markdown
- Version: 2.2.3
- Operating System: win 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.zip](https://github.com/siyuan-note/siyuan/files/9743990/siyuan.zip)

**Comment by 88250** [comment]
存在标记文件 .sya 时无论是否引用都不会被纳入未引用资源，这个是之前特意做的改进，避免误删除标记。
