### ISSUE TITLE
增加公共代码 js/css 片段

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6143]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

关联: [[提议] 增加公共主题 css 文件, 无论使用哪个主题, 该 css 都会生效 - 链滴](https://ld246.com/article/1663475885890)

### 描述可能的最优解决方案 Describe the optimal solution

将公共主题 `theme.css` 文件与 `theme.js` 文件塞到某个 data 目录下某个现有的静态 Web 文件服务的目录

### 描述候选的解决方案 Describe the candidate solution

在 data 目录下设置一个新的提供静态 Web 文件服务的目录, 用于存放公共主题的 `theme.css` 文件与 `theme.js` 文件

### 其他信息 Other information

不急~

**Comment by Zuoqiu-Yingyi** [comment]
> 公共主题为 stage/build/app/base.css，所有主题都会进行加载。公共 js 里面主要的是前端 API 之类的么？

是指不与特定主题耦合的自定义主题片段, 优先级比用户所当前所使用的主题(`theme.css`或`custom.css`)与默认主题更高, 且无论用户切换到哪个主题都可以应用

**Comment by Vanessa219** [comment]
哦哦哦，想起来了，抱歉抱歉。

**Comment by mozhux** [comment]
这是不是类似ob的代码片段？
如果是可以不区分启用的话，那最好是能有选择性的开启某些样式或js，在设置里调节需要的功能

**Comment by 88250** [comment]
@mozhux 这个就不区分功能了，所有功能都塞到一个 js/css 中，区分功能的话还是通过插件机制比较好。

**Comment by 88250** [comment]
我不太清楚如何区分一个文件中的不同片段 😂

**Comment by mozhux** [comment]
应该是每个片段都独立，通过勾选让其生效。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月11日 22:18
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/siyuan] 增加公共主题 css 与 js 文件 (Issue #6143)


我不太清楚如何区分一个文件中的不同片段 😂

**Comment by leolee9086** [comment]
简单点可以使用不同文件吧  这个应该比较好实现  我之前试了就是片段的加载顺序不知道怎么交互比较好

**Comment by crendy** [comment]
问一下  公共代码 js/css 片段  怎么操作？

**Comment by Zuoqiu-Yingyi** [comment]
> 问一下 公共代码 js/css 片段 怎么操作？

1. 新建文件 `<workspace>/data/snippets/conf.json`
2. 直接编辑该文件

**Comment by terwer** [comment]
参照D大的实力，css直接改type即可，提供给有需要的参考：

```json
[
  {
    "name": "common",
    "type": "js",
    "enabled": true,
    "content": "console.log('这是自定义js片段');"
  },
   {
    "name": "common",
    "type": "css",
    "enabled": true,
    "content": ".protyle-background:has(.protyle-background__icon.fn__none) {min-height: 57px !important;}.protyle-title{margin-left:16px !important;margin-right:16px !important;}.protyle-wysiwyg{padding-left:16px !important;padding-right:16px !important;}"
  }
]
```

**Comment by Zuoqiu-Yingyi** [comment]
@88250 能不能将 `data/snippets` 目录也建立静态 Web 文件服务, 这样就可以在 `conf.json` 中通过 `@import url('/snippets/foo.css');` 与 `import('/snippets/bar.js');` 引用了, 不然想要同步的话只能另辟蹊径放在 `data/widgets` 或 `data/emojis` 目录了
