### ISSUE TITLE
能否支持链接到未来的日期

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#6145]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

写dailynote时，有时候，一些零碎的小事，想放到第二天，也不是说要做todo，就是第二天看着有思路

### 描述可能的最优解决方案 Describe the optimal solution

所以，能否支持dailynote链接到未来的日期，比如[[2022-10-10]]，这样第二天（或者日后某天）写dailynote时，直接在反链就能看到信息了

**Comment by 88250** [comment]
目前没有办法支持，只能先手动创建好文档并链接。
