### ISSUE TITLE
有没有复制为纯文本的快捷键

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#6146]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时复制一段文字到浏览器啥的，会默认携带文本格式，不知道有没有复制为纯文本的功能？

### 描述可能的最优解决方案 Describe the optimal solution

比如快捷键 Ctrl-Shift-C，类似粘贴为纯文本

**Comment by 88250** [comment]
切换到预览模式复制。

PS Ctrl+Shift+C 已经用于复制引用
