### ISSUE TITLE
支持编辑器悬浮大纲

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6148]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

编辑器悬浮大纲指的是在编辑器右侧显示一个大纲目录浮在文字上层，鼠标移过去显示移开隐藏，形态类似现有的 wolai、FlowUs 目录，但他们的是独立显示在右侧而不是浮在文字上层

我使用布局一般左侧文档树，右侧反链面板，这样大纲面板就不太放得下，现在我是把大纲挤在左侧底部，短的文章还好，长的文章也就看不完整
或者当做视频笔记时会把视频放在屏幕左侧，右侧放笔记软件，因为空间狭小只能只保留编辑器页面，但这样也看不到大纲

我觉得大纲面板我觉得和文档树、反链等面板不同地方在于：
- 大纲面板不像文档树、反链那么重，需要有新建、编辑等其他操作
- 对于短文章如日常笔记，大纲也通常也很短没必要单独使用一个面板位

### 描述可能的最优解决方案 Describe the optimal solution

现有大纲面板保持不变，新增支持编辑器悬浮大纲，支持在设置开关

悬浮大纲暂时仅支持显示大纲，定位跳转
后续如果有其他新增的大纲功能放在大纲面板

### 描述候选的解决方案 Describe the candidate solution

彻底取消大纲面板，改而使用悬浮大纲
这个方案对习惯于原大纲面板用户改变较大，可能需要更多用户讨论

**Comment by 88250** [comment]
悬浮大纲指的是？

**Comment by Temacc0531** [comment]
就是类似FlowUs\少数派这种悬浮显示在文章右侧的大纲目录
FlowUs：
![image](https://user-images.githubusercontent.com/101307399/194983706-2dd522e3-518c-4b9c-a419-9a499a93254f.png)

少数派：
![image](https://user-images.githubusercontent.com/101307399/194983967-59ab92ea-feb7-4483-b389-43704fa08f51.png)

**Comment by 88250** [comment]
> 因为空间狭小只能只保留编辑器页面，但这样也看不到大纲

这样不是也占用空间吗？

**Comment by lentikr** [comment]
> > 因为空间狭小只能只保留编辑器页面，但这样也看不到大纲
> 
> 这样不是也占用空间吗？

看意思应该是在编辑器的某个地方做一个悬浮的小窗口，实现大纲的显示以及点击跳转功能，不占两侧边栏的位置。

**Comment by UltramarineSky** [comment]
侧边悬浮大纲不会占边栏位置，但还是会在编辑器区域占用位置导致编辑器区域可用宽度变窄，对软件内文档分屏使用来说可能会很难受
另，个人认为悬浮目录比较适合左右侧边没有边栏工具栏显示，如果有侧边栏+悬浮目录体验效果可能并不会好

**Comment by Temacc0531** [comment]
> > 因为空间狭小只能只保留编辑器页面，但这样也看不到大纲
> 
> 这样不是也占用空间吗？

对，因为空间小所以把左右侧栏都关了，但是想要编辑器右侧可以悬浮一个大纲，鼠标移上去显示移走消失，编辑时不会占用空间

**Comment by 88250** [comment]
> > > 因为空间狭小只能只保留编辑器页面，但这样也看不到大纲
> > 
> > 
> > 这样不是也占用空间吗？
> 
> 对，因为空间小所以把左右侧栏都关了，但是想要编辑器右侧可以悬浮一个大纲，鼠标移上去显示移走消失，编辑时不会占用空间

那可以试试 Alt+O

**Comment by Temacc0531** [comment]
> 侧边悬浮大纲不会占边栏位置，但还是会在编辑器区域占用位置导致编辑器区域可用宽度变窄，对软件内文档分屏使用来说可能会很难受 另，个人认为悬浮目录比较适合左右侧边没有边栏工具栏显示，如果有侧边栏+悬浮目录体验效果可能并不会好

对于习惯用大纲面板的用户来说就不需要悬浮大纲了，所以可以支持在设置里面关闭。另外也许悬浮出来的大纲可以浮在编辑文字上方不占空间？

**Comment by 88250** [comment]
> > 侧边悬浮大纲不会占边栏位置，但还是会在编辑器区域占用位置导致编辑器区域可用宽度变窄，对软件内文档分屏使用来说可能会很难受 另，个人认为悬浮目录比较适合左右侧边没有边栏工具栏显示，如果有侧边栏+悬浮目录体验效果可能并不会好
> 
> 对于习惯用大纲面板的用户来说就不需要悬浮大纲了，所以可以支持在设置里面关闭。另外也许悬浮出来的大纲可以浮在编辑文字上方不占空间？

但是这会造成了遮挡编辑内容，所以所谓的悬浮目录好像都没有这个设计 😂

**Comment by 88250** [comment]
老铁，Alt+O 试了吗？

**Comment by lentikr** [comment]
> 老铁，Alt+O 试了吗？

我这儿试了一下，感觉不太好用，首先是样式与边栏完全一致，观感不好，另外也无法根据文档的切换自动切换大纲。

**Comment by Temacc0531** [comment]
> > > 侧边悬浮大纲不会占边栏位置，但还是会在编辑器区域占用位置导致编辑器区域可用宽度变窄，对软件内文档分屏使用来说可能会很难受 另，个人认为悬浮目录比较适合左右侧边没有边栏工具栏显示，如果有侧边栏+悬浮目录体验效果可能并不会好
> > 
> > 
> > 对于习惯用大纲面板的用户来说就不需要悬浮大纲了，所以可以支持在设置里面关闭。另外也许悬浮出来的大纲可以浮在编辑文字上方不占空间？
> 
> 但是这会造成了遮挡编辑内容，所以所谓的悬浮目录好像都没有这个设计 😂

试了 Alt+O 但是这样相当于还是开辟了一个新的栏来显示😅。就是要遮挡文字这样就不会占地方了，配合鼠标移开自动消失感觉还好

**Comment by 88250** [comment]
> > 老铁，Alt+O 试了吗？
> 
> 我这儿试了一下，感觉不太好用，首先是样式与边栏完全一致，观感不好，另外也无法根据文档的切换自动切换大纲。

Alt+O 是绑定文档的大纲，可以多个文档绑定不同的大纲哦。

**Comment by 88250** [comment]
> 就是要遮挡文字这样就不会占地方了，配合鼠标移开自动消失感觉还好

这个估计要等插件扩展了，原生支持不考虑了。

**Comment by Temacc0531** [comment]
其实想要的应该就是Alt+O，但是现有的好像和我想象的不太一样，现在的编辑器大纲和大纲面板功能重叠度感觉有点高

**Comment by 88250** [comment]
Alt+O 可以多个文档同时打开的，大纲面板是联动文档的。

**Comment by 88250** [comment]
鼠标悬浮停靠栏上面板图标然后展开后面可能会考虑，这个可以减少一次点击，鼠标移开面板以后自动折叠。

**Comment by Temacc0531** [comment]
> Alt+O 可以多个文档同时打开的，大纲面板是联动文档的。

这个多个文档同时打开有什么用法吗，或者可以直接把现有的改造一下
悬浮这个对于小尺寸设备应该用处还是蛮大的

**Comment by 88250** [comment]
Alt+O 的用处就是多个文档可以同时显示大纲啊……

我觉得悬浮大纲并不能节省屏幕空间（除非遮挡编辑器内容），目前缺少的应该是鼠标悬浮展开/折叠面板。

**Comment by Temacc0531** [comment]
等等，好像说的有点偏，我重新更新一下问题

**Comment by 88250** [comment]
没有偏吧 :trollface:

**Comment by Temacc0531** [comment]
> 鼠标悬浮停靠栏上面板图标然后展开后面可能会考虑，这个可以减少一次点击，鼠标移开面板以后自动折叠。

侧边栏自动展开的话如果不是悬浮在文字上层也会占位置吧，而且还有个问题就是如果停靠栏隐藏了那是不是也没法通过图标来控制（为了美观牺牲有点大😶）

其实想要实现的效果就是鼠标大概移到这个区域就自动显示出来目录，鼠标移走就隐藏

![_7{M0VAH__CE3Q 0H}YS$_Q](https://user-images.githubusercontent.com/101307399/194993089-f5d27033-d167-4475-9139-d4e3848fd8ec.png)

这样对于这篇文章的编辑浏览功能来说功能是完整的不需要额外再开其他窗口

**Comment by 1zhuimeng1** [comment]
用户选择去鼠标悬浮触发大纲，本就是为了看文档结构，或者进行跳转操作
此时遮挡编辑器中的内容也无妨，对用户来说完全无感，没有影响
更何况只需要将鼠标移开便能看到遮挡的内容

**Comment by Zuoqiu-Yingyi** [comment]
感觉和这个差不多呀: [Dock 面板加入 pin 和 float 模式](https://github.com/siyuan-note/siyuan/issues/3499)

**Comment by Temacc0531** [comment]
> 感觉和这个差不多呀: [Dock 面板加入 pin 和 float 模式](https://github.com/siyuan-note/siyuan/issues/3499)

这个就是上面D大提到的自动展开折叠的功能，和我这个还是有所区别😂

如果是为了不想正常模式编辑器变得更加复杂，可以考虑这个功能只在 Alt+Y 全屏模式中加入

**Comment by 88250** [comment]
等后面的编辑器挂件 #3862 实现以后看下社区是否有开发者实现吧，原生的目前不考虑了，我关闭了，谢谢。
