### ISSUE TITLE
切换版本丢失配置问题

### ISSUE THREAD

**Issue by leeyaunlong** [siyuan-note/siyuan#616]
### 切换版本丢失配置问题 
目前同时在用多个思源的压缩版本， 每次切换新版的时候间歇性会发生如下问题

1. 可以成功启动， 但是丢失，layout 或者之前默认的笔记目录没有了， 需要重新指定
2. 可以启动，一直处于 loading 状态(红黑的圈圈旋转).有的时候就是一个灰色空窗口，连 loading 都没有
3. 启动失败，且所有配置都失效了。
> 以上情况下， 笔记都没问题。

如果使用 mklink , 硬连接目录， 则问题 2 会出现。

> 比如 在 siyuan-note/目录下， 我安装了多个版本，
> sy-0.4
> sy-0.5
> 然后为了启动方便创建了一个 sy-now 的硬连接 指向 sy-0.4.
> 如果下次把 sy-now 指向了 sy-0.5 后， 有一定几率出现上面的问题。

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：0.4-0.5

**Comment by 88250** [comment]
你好，配置文件并不是每个版本都兼容的，请不要版本混用。

可以试下通过启动参数为不同版本指定不同的配置目录：

![image](https://user-images.githubusercontent.com/873584/100823501-47881380-348f-11eb-8d7f-b468ca0639d4.png)
