### ISSUE TITLE
将反向链接中的正文内容层级放在文档标题之下

### ISSUE THREAD

**Issue by UserZYF** [siyuan-note/siyuan#6162]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在的文档标题和正文内容是并列的，如果将正文内容（.protyle)）放在文档标题（.b3-list-item）之下，逻辑上更加像一个整体，而且能够更方便地设置样式，比如给这个整体加上边框或者阴影等。这样可以使反向链接的item区分更加明显
![Snipaste_2022-10-12_13-25-13](https://user-images.githubusercontent.com/38289979/195257494-b28ec216-3d76-4838-8c62-0bf4482c6346.png)

### 描述可能的最优解决方案 Describe the optimal solution

将反向链接中的正文内容层级放在文档标题之下

**Comment by Vanessa219** [comment]
没太明白，标题下面应该是面包屑，是不需要面包屑么？

**Comment by UserZYF** [comment]
用开发者工具查看，反向链看板中，文档标题和正文内容(包括面包屑和列表正文等)在结构上是并列的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月12日(周三) 下午3:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 将反向链接中的正文内容层级放在文档标题之下 (Issue #6162)

**Comment by Vanessa219** [comment]
看了一下树组件、文档树等折叠项和对应的内容都是并列的，这个结构上要改的话，重构的地方太多了，就先不动了。用 `~` 看看行不行
