### ISSUE TITLE
请问要如何去除or收缩右边多余的灰色阴影

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6167]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

能够去除或者收缩右边一片多余的阴影吗？
![image](https://user-images.githubusercontent.com/37429029/195340751-ab29b09c-3a27-4044-b4c9-c1fd351682be.png)

### 描述可能的最优解决方案 Describe the optimal solution

可以去掉多余的阴影部分，附上模板md
[面试题模板.md](https://github.com/siyuan-note/siyuan/files/9764757/default.md)

**Comment by 88250** [comment]
这个是引述的默认样式，可通过自定义主题 CSS 修改。
