### ISSUE TITLE
移除编辑器内拖拽功能

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#6169]
拖拽后浏览器的处理比较霸道，目前没有找到很好的办法去进行修正。如果不修正的话，表面上看没什么问题，但其实 Dom 已经发生了变化，不仅带有大量的 style，还会丢失行级元素的属性。在没有找到好的办法之前先禁用该功能。

https://ld246.com/article/1665326888611/comment/1665557995894#comments

**Comment by mozhux** [comment]
这个具体是什么操作？

**Comment by pisceswb** [comment]
请问能否先实现纯文本格式TXT的拖动？拖动后，被拖动的内容变为不带任何格式的TXT文本。拖动有格式的文本内容时可以进行一下提示，会丢失格式。
或拖动文本使用“剪切 → 粘贴”的方式来实现。
因为习惯了Word、记事本中的拖动功能，思源不能拖动不符合日常操作习惯

**Comment by pisceswb** [comment]
可以设置选项，让用户自己选择是否启用这样简陋的拖拽功能。应该会有相当量的人选择开启吧

**Comment by 88250** [comment]
实现不了，太多的边界情况目前无法处理。

**Comment by pisceswb** [comment]
不甘心地再问一下，请问当前有实现文字拖拽功能的可行性基础了吗？😜
或能否将原拖拽行为，以Ctrl X，Ctrl V的方式实现？

**Comment by Vanessa219** [comment]
通过浏览器接口获取的拖拽内容和 ctrl+X 的内容不同，无法去校验并校正。

**Comment by pisceswb** [comment]
收到，也就是还是不行呀，继续蹲守。。。
其实只实现纯文本的拖动也是很好的，这对于文字工作者还是蛮有用的。

**Comment by Vanessa219** [comment]
你看上去是纯文本，但是拖拽的时候系统会转换成一个标签，里面记录了字体、颜色、背景等很多信息。

**Comment by pisceswb** [comment]
感谢V姐的解释

**Comment by QQQOrange** [comment]
期待早日找到解决方式
