### ISSUE TITLE
文档树选中文档使用Ctrl+Shift+C（复制该块为引用块）逻辑修改

### ISSUE THREAD

**Issue by TracyIverson** [siyuan-note/siyuan#6173]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我在文档树中选中一篇文档后使用Ctrl+Shift+C（复制该块为引用块），原本以为可以将选中文档复制为引用块，但是实际操作后发现是将选中文档的第一行复制为引用块了。而使用菜单操作时，是可以把文档复制为引用块的。我不清楚是程序本身设计如此，因为文档树上的菜单没有提示可以使用Ctrl+Shift+C，如果不是，希望可以修改一下

### 描述可能的最优解决方案 Describe the optimal solution

希望选中文档后使用快捷键可以将选中文档复制为引用块

**Comment by Vanessa219** [comment]
没有标识的话就是不可以使用快捷键，你复制的应该是光标所在的文档或块。

**Comment by 88250** [comment]
文档树上的这个快捷键暂时不考虑提供了，可能会和后续要实现的文档树多选操作 #1359 有冲突，等多选结束以后如果需要这个的用户较多我们再重新考虑，感谢反馈。
