### ISSUE TITLE
顶栏改进数据历史图标

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#6174]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

之前的video和现在trashcan觉着都不太适合，容易混淆

### 描述可能的最优解决方案 Describe the optimal solution

新增一个名为history的icon

**Comment by 88250** [comment]
老铁建议一个？

**Comment by royc01** [comment]
![111](https://user-images.githubusercontent.com/38906705/195482222-5234461a-c2cb-46d0-8d3d-6278f8b7e344.png)
![222](https://user-images.githubusercontent.com/38906705/195482240-19b531c8-1189-4338-93b1-c41f030edcf0.jpg)
类似notion和wolai这样的应该比较妥

**Comment by 88250** [comment]
好的，我们考虑一下，谢谢。

**Comment by mozhux** [comment]
另外引用块的图标希望也能改一下，不要和关系图的一起，不然也不好改图标
