### ISSUE TITLE
反链面板支持关键字过滤

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6178]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

v2.3.0 之前的反链面板支持过滤文件内容
v2.3.0 之后的只支持过滤文件名了，这会让一些用法没法实现，希望可以继续支持

对于dailynote来说，文件名都是当天的日期，而过滤有一个用法是把不同日期的日记中相同内容过滤出来对比映照，这样就需要文件内容过滤

### 描述可能的最优解决方案 Describe the optimal solution

反链与提及面板重新支持内容过滤

**Comment by 88250** [comment]
针对内容的任意关键字过滤暂时不考虑了，可能会考虑支持已有锚文本的过滤，类似这里的提议 https://ld246.com/article/1665586130155

**Comment by Temacc0531** [comment]
> 针对内容的任意关键字过滤暂时不考虑了，可能会考虑支持已有锚文本的过滤，类似这里的提议 https://ld246.com/article/1665586130155

这个文章说的针对锚文本的过滤好像和我这个提议的有较大差异（他这里的锚文本按我的理解应该特指的是静态锚文本，如果是动态锚文本则都是目标文档名，则无过滤的意义）

在每篇dailynote只链接到目标文档一次的这个情况下，那过滤静态锚文本实际还是和过滤文件名一级没有区别

我现在想实现的应该是如下场景

dailynote1：
- [[项目记录]]
  - 项目A 0101-0230：xxxx
  - 项目B 0102-0321：xxxx

dailynote2：
- [[项目记录]]
  - 项目A 0101-0230：xxxx
  - 项目A 0102-0321：xxxx

这样我在《项目记录》文档的反链面板里面就可以过滤`项目A 0101-0230`看到这个具体项目在所有天数里面的记录，或者过滤`项目A`看到所有项目A的记录

**Comment by 88250** [comment]
@Temacc0531 这个在双链大纲 RR-Like 软件上有现成的功能吗？我去学习一下 😂

**Comment by 88250** [comment]
@thomasxin1994 我们考虑了下，还是支持任意关键字过滤比较灵活一些，下个版本改进，感谢反馈。
