### ISSUE TITLE
块引搜索不区分大小写，支持类型前缀转义

### ISSUE THREAD

**Issue by walklty** [siyuan-note/siyuan#618]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

1 在通过[[或((搜索要引用的内容时, 希望能够忽视英文字符大小写. 目前搜索功能能够实现该功能, 但是引用时不行.
![image](https://user-images.githubusercontent.com/47232102/100856710-bb91de00-34c6-11eb-804a-153773f25bfe.png)

2 类似"aa-bb"这样的字符搜索不到
![image](https://user-images.githubusercontent.com/47232102/100856656-a917a480-34c6-11eb-86ca-566b3aa49f51.png)

**Comment by 88250** [comment]
你好，第二个问题是因为 `d` 命中了类型前缀过滤，只会在文档名中进行搜索。

**Comment by 88250** [comment]
比如想要搜索所有包含 `Markdown` 的标题块，则可以使用 `#Markdown` 作为搜索条件。如果需要搜索的关键字开头字符在上述列表中，则需要使用 `\` 转义。比如想要搜索 `doc` 关键字，`d` 会命中文档块过滤，这样实际上搜索的关键字是 `oc`，需要通过 `\doc` 转义。
