### ISSUE TITLE
新的反链面板改进建议（支持文档跳转、高度自适应、全部展开）

### ISSUE THREAD

**Issue by tmkddskf** [siyuan-note/siyuan#6182]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在使用反链面板的时候

### 描述可能的最优解决方案 Describe the optimal solution

展开反链面板每一个条目的时候，有三个问题需要解决
1. 没有按钮可以点击跳转到对应的文档，只能在反链面板编辑文字。
2. 展开之后高度没有根据内容自适应
3. 无法一键全部展开

**Comment by 88250** [comment]
1. Ctrl/Alt+Click 文档块标
2. 不太明白你的意思，请截图或者录屏演示
3. Duplicate of https://github.com/siyuan-note/siyuan/issues/6083

我先关闭了，如果有补充请继续跟帖，谢谢 :pray:

**Comment by tmkddskf** [comment]
![image](https://user-images.githubusercontent.com/15048044/195738105-a4eb3208-9f7e-4bfe-a5d7-8375550760f8.png)
第二条的补充如图所示 @88250

**Comment by tmkddskf** [comment]
![image](https://user-images.githubusercontent.com/15048044/195738206-e82c75b4-47ee-4cd0-9c7a-a331625b4869.png)
您好，第二条的补充如图 @88250

**Comment by Vanessa219** [comment]
有的反链内容会比较多的话就不会出现空白

**Comment by tmkddskf** [comment]
之所以提这个问题是因为：
现在的设计导致我们永远只能同时看到一条反链文档，哪怕每个反链正文其实很短，也不能多摆几个在右边做参考。

**Comment by tmkddskf** [comment]
不好意思，是我的主题问题。
