### ISSUE TITLE
docker部署版本，外观模式跟随系统无法自动切换“暗黑”模式和”明亮“模式。

### ISSUE THREAD

**Issue by lerogo** [siyuan-note/siyuan#6185]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

本地系统：macOs Monterey 版本 12.6
服务器系统：linux
docker部署版本，外观模式跟随系统无法自动切换“暗黑”模式和”明亮“模式。

### 期待的结果 Expected result

修复

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/45483054/195587789-12bc131f-29b6-4fb0-a1d5-d1e5f6f36bdc.png)

### 版本环境 Version environment

```markdown
- Version: 2.4.0
- Operating System: macOs Monterey 版本 12.6
- Browser (if used): chrome 106.0.5249.91
```

### 日志文件 Log file

-

**Comment by 88250** [comment]
你好，这个模式只有桌面端支持。

**Comment by lerogo** [comment]
呜呜，能不能让chrome也支持一下

**Comment by lerogo** [comment]
求求让docker版本也支持一下吧

**Comment by 88250** [comment]
暂时没有精力改，这个估计要靠社区开发者贡献了。

**Comment by lerogo** [comment]
那可以麻烦在下个docker版本的左上角加入模式切换的图标吗？之后手动切换方便以前（之前的版本）

**Comment by 88250** [comment]
> 那可以麻烦在下个docker版本的左上角加入模式切换的图标吗？之后手动切换方便（之前的版本）

请关注 https://github.com/siyuan-note/siyuan/issues/6186
