### ISSUE TITLE
导出 markdown 用其他软件打开渲染效果不一致

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6190]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

行级元素支持多重样式类型后，似乎污染了 markdown 语法？导出 markdown 后用其他软件（例如 obsidian）打开，会有很多零宽字符，且渲染效果不一致。

### 期待的结果 Expected result

导出 markdown 后用其他软件打开，渲染效果一致。

### 版本环境 Version environment

```markdown
- Version: 2.4.0
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
行级叠加以后只能用零宽空格区分标记符，否则不符合 Markdown 语法。
