### ISSUE TITLE
备注支持导出为脚注

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#6195]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

思源有了备注功能，可喜可贺
不过导出的时候发现备注默认是导出为上标。这点不太实用
![Snipaste_2022-10-14_10-03-10](https://user-images.githubusercontent.com/60436214/195745114-fcad8f8d-4e2a-4334-b1f4-fb93e3f6097e.png)

希望备注导出为脚注样式，另一方面，这样也能用备注功能实现脚注的基本功能。
过去思源要实现脚注，基本得用引用块
- 要么是选中文字一段话新建一个文档，但很不现实，导致子文档过多
- 要么是新建一个子文档，在里面写入脚注，然后在引用，这点对于引用参考文献很实用，但平常脚注还是太麻烦了

现在既然有了备注功能，我觉得脚注功能已经不是很需要了，就希望能完成备注的导出

### 描述可能的最优解决方案 Describe the optimal solution

默认设置导出备注为脚注

### 描述候选的解决方案 Describe the candidate solution

在导出设置中增加导出备注的选项

**Comment by 88250** [comment]
感谢反馈，这个实现备注的时候考虑过，但是会和引用转换的脚注编号产生一些冲突，所以没有实现。

目前的行级备注使用上标感觉还是比较清晰明了的，因为本身行级备注就是简短的，直接放在原文旁边会好一些。

**Comment by Achuan-2** [comment]
D大，引用转换为脚注其实是可以关闭的，如果无法冲突解决的话，我觉得可以告知用户，备注和引用同时转脚注会冲突。让用户自己选择。设置-导出可以选择备注导出上标还是脚注。

**Comment by 88250** [comment]
这个估计不改变了，我个人觉得上标更符合行级简单备注。
