### ISSUE TITLE
顶部tabbar 主题切换按钮 或者主题切换快捷键

### ISSUE THREAD

**Issue by mingyong-g** [siyuan-note/siyuan#6196]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

快速切换主题

### 描述可能的最优解决方案 Describe the optimal solution

1. 在顶部tabbar 固定主题切换按钮，之前的版本是有这个功能的，最近的几次更新发现切换主题的按钮被取消了。
2. 或者能提供主题切换的快键键（查阅了相关文档没看到有关快键键，如果已经有了相关快键键请告知）

**Comment by 88250** [comment]
你指的是主题模式（暗黑/明亮/跟随系统）切换吗？

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6186

**Comment by mingyong-g** [comment]
👍
