### ISSUE TITLE
改进默认主题外观

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6197]
* 滚动条调窄并加入动效
* 页签打开关闭加入动效
* 左/右停靠栏加宽
* 顶栏/底栏/状态栏加高
* 顶栏按钮位置和聚焦状态
* 移除前进后退按钮

**Comment by mozhux** [comment]
终于要改默认了，建议
1.在合并帮助文件，反馈，设置，检测更新等功能到左下角问题与反馈图标，一个问号点开子菜单，类似展开边栏那样。
2.区分引用块和关系图图标名称，新建一个
3.题头图等内容可以自定义关闭不占位置
4.反链面板内容整体字号缩小，面包屑再缩小，筛选框缩小，左边的引用计数对齐

**Comment by 88250** [comment]
@mozhux 暂时先不改了，后面考虑，谢谢。

**Comment by mozhux** [comment]
> 。

行吧，是我提晚了
