### ISSUE TITLE
文档关系图按逻辑层级呈现

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#62]
![H}P4691KDTUU $8`E4~XC P](https://user-images.githubusercontent.com/873584/95647281-c486b480-0b00-11eb-9e98-d02f736f49d7.png)

在 https://github.com/siyuan-note/siyuan/issues/68 中已经完成默认显示文档块和标题块的文本，需要用户进一步反馈是否有必要实现本提议。

**Comment by 88250** [comment]
似乎没有必要了，先关闭。

**Comment by 88250** [comment]
重开提议，继续考虑。

**Comment by lss6378** [comment]
这样子分个层级，会稍微明确一点
![图片](https://user-images.githubusercontent.com/15924513/95674629-063c5b80-0be4-11eb-9ef7-82cf70b227c0.png)

**Comment by 88250** [comment]
> 即，所有的H2节点连接到上级H1节点而不是直接连到文件节点，H3节点连接到上级H2节点而不是直接连接到文件节点……以此类推,形成多层树状结构。
> 这样节点的层级关系在关系图上显示更清晰一些。
> 下面是一个Heading层级很多（有H1~H3）的MD文件，已经明显看出显示节点数量太多，杂乱无章。
> ![image](https://user-images.githubusercontent.com/35917471/96359588-1c4b9e00-1147-11eb-988a-6bb241bcbcc8.png)

https://github.com/siyuan-note/siyuan/issues/264

**Comment by 88250** [comment]
来自群友斑鸠的建议：[issue #62  思维导图的一点想法.docx](https://github.com/siyuan-note/siyuan/files/5397318/issue.62.docx)

**Comment by nanmao** [comment]
<img width="1192" alt="鱼骨图" src="https://user-images.githubusercontent.com/26304888/96439739-817fbc00-1239-11eb-80b8-106d9b75952e.png">
<img width="748" alt="逻辑结构图" src="https://user-images.githubusercontent.com/26304888/96439764-8d6b7e00-1239-11eb-8a8f-8d47ab22c1f7.png">
鱼骨图更容易发散;逻辑结构图层次结构更清晰.
我想要逻辑结构图,而且思源默认关系图布局在右边,逻辑结构图的方向很适合.

**Comment by wfan14513** [comment]
![有关系类型](https://github.com/wfan14513/PublicPic01/blob/master/%E5%8F%AF%E4%BB%A5%E6%A0%87%E6%B3%A8%E5%85%B3%E7%B3%BB%E7%B1%BB%E5%9E%8B.png?raw=true)
能标注关系类型的功能还是让人流口水的，仅供参考。

**Comment by lss6378** [comment]
## 层级节点折叠与展开

参考：https://markmap.js.org/

![节点折叠和展开](https://user-images.githubusercontent.com/15924513/97703904-61c77e00-1aec-11eb-9fc6-085ed7e01a14.gif)

**Comment by 88250** [comment]
在 v0.3.9 https://github.com/siyuan-note/siyuan/issues/376 中进行一些优化。

**Comment by atao-alt** [comment]
![5236](https://user-images.githubusercontent.com/59548991/97784120-2d7cbc00-1bd7-11eb-801b-1f42b10cc308.gif)
为了避免导图内部一个节点连接过多，导致同样的混乱的解决参考。  软件：Visual Thesaurus 3

**Comment by HarryHuaa** [comment]
关于关系图的一些建议与需求

1.关系图中设置过滤器,设置级别1意义为关系图仅显示页节点,级别2意义为关系图中显示页节点+一级块节点,以此类推;过滤器还可设置别的选项如是否显示标签为节点(参考obsidian),关系图以树形还是向心显示(参考wolai),过滤器是当前页生效还是所有页生效

2.左键点击节点会跳转到以对应节点为中心的关系图(类似上面的Visual Thesaurus 3),ctrl+左键可以将节点打开或缩起(类似上面的思维导图)

3.关系图节点间连接线可视性更强一些,如引用关系,层级关系等(参考wolai,logseq)

4.节点可视性更强一些,如块,页,标签的颜色不同,被引用的越多节点越大,全局关系图中越靠近中心

**Comment by atao-alt** [comment]
？？？？你该发给D大啊😂😂😂，我只是个普通用户



---原始邮件---
发件人: "HarryHua"<notifications@github.com&gt;
发送时间: 2020年11月4日(周三) 中午11:23
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;;
抄送: "atao-alt"<2227989395@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [siyuan-note/siyuan] 文档关系图按逻辑层级呈现 (#62)




 
关于关系图的一些建议与需求
 
1.关系图中设置过滤器,设置级别1意义为关系图仅显示页节点,级别2意义为关系图中显示页节点+一级块节点,以此类推;过滤器还可设置别的选项如是否显示标签为节点(参考obsidian),关系图以树形还是向心显示(参考wolai),过滤器是当前页生效还是所有页生效
 
2.左键点击节点会跳转到以对应节点为中心的关系图(类似上面的Visual Thesaurus 3),ctrl+左键可以将节点打开或缩起(类似上面的思维导图)
 
3.关系图节点间连接线可视性更强一些,如引用关系,层级关系等(参考wolai,logseq)
 
4.节点可视性更强一些,如块,页,标签的颜色不同,被引用的越多节点越大,全局关系图中越靠近中心

**Comment by Infinemen** [comment]
发现个问题，嵌入别的页面的内容的时候，关系图会多一个节点（最外层黄色节点）
![image](https://user-images.githubusercontent.com/19859842/98459234-e5abf500-21d3-11eb-8911-9dbfdfb6e8a2.png)

![image](https://user-images.githubusercontent.com/19859842/98459230-d7f66f80-21d3-11eb-9876-4f5870ead965.png)

**Comment by lss6378** [comment]
## A. 全局关系图仅体现“文档块”之间的联系，隐藏细节，连接数越多，节点越大
![图片](https://user-images.githubusercontent.com/15924513/102692997-5540e580-4252-11eb-9fec-dc22ae31fb5a.png)

## B. "文档块"内的关系，使用层级表示，层级可折叠
![图片](https://user-images.githubusercontent.com/15924513/102693048-a3ee7f80-4252-11eb-962a-833cb61e2c1a.png)


## C. 容器块使用外壳包裹
![图片](https://user-images.githubusercontent.com/15924513/102692936-d64bad00-4251-11eb-80fa-5f1aba70c756.png)

**Comment by 88250** [comment]
@lss6378 C 点没理解，请再补充一下。

**Comment by lss6378** [comment]
> 
> 
> @lss6378 C 点没理解，请再补充一下。
使用同一种颜色的外框，将容器内的叶子块包裹起来，表示他们在同一个容器内
![图片](https://user-images.githubusercontent.com/15924513/102693209-f2504e00-4253-11eb-8af6-da936ff527c8.png)

**Comment by 88250** [comment]
@lss6378 谢谢，估计到 v0.7.0 开始会进行实现。

**Comment by 88250** [comment]
各位，我关闭这个提议了，目前文档关系图已经是按逻辑层级实现了，非常感谢大家的建议和讨论。

大约在 v0.7.0 我们会对关系图进行进一步调整，主要是加入类型过滤、路径过滤、关系图渲染参数等，请大家关注 https://github.com/siyuan-note/siyuan/issues/793 

关于思维导图方面的考虑请关注 https://github.com/siyuan-note/siyuan/issues/735

再次感谢！
