### ISSUE TITLE
查询嵌入块点击面包屑后不应该出现可编辑状态

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6200]

**Comment by Chenm4** [comment]
希望能通过这个bug让嵌入块可编辑，不知道目前嵌入块的不能编辑是不是碍于性能原因

**Comment by 88250** [comment]
> 希望能通过这个bug让嵌入块可编辑，不知道目前嵌入块的不能编辑是不是碍于性能原因

性能有一些影响，最主要的还是编辑器的完整性有问题。

**Comment by aptexd** [comment]
对于直接编辑嵌入块的事情
是暂时没时间实现，还是没有这个计划，还是其他原因呢

**Comment by 88250** [comment]
@aptexd 不会支持直接编辑嵌入块。

**Comment by 88250** [comment]
目前似乎没有重现步骤，暂时先忽略解决。

**Comment by Vanessa219** [comment]
可以重现

**Comment by GH-W94** [comment]
> > 希望能通过这个bug让嵌入块可编辑，不知道目前嵌入块的不能编辑是不是碍于性能原因
> 
> 性能有一些影响，最主要的还是编辑器的完整性有问题。

D 大，“编辑器的完整性”是指什么呢？会造成什么后果呢？

**Comment by 88250** [comment]
嵌入块嵌套后编辑会有问题。

**Comment by GH-W94** [comment]
> 嵌入块嵌套后编辑会有问题。

D 大，能否仅让“通过块菜单复制该块为嵌入块”行成的嵌入块进行编辑，其他“查询嵌入块”禁止进行编辑呢？

**Comment by 88250** [comment]
说了实现不了啊……

**Comment by GH-W94** [comment]
> 说了实现不了啊……

哈哈，嵌入块直接编辑我倒是不需要，但非常需要在嵌入块里直接进行折叠展开列表，奈何它需要先支持直接编辑……
