### ISSUE TITLE
导出 PDF 时 KaTeX 样式文件引用路径错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6203]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

katex 压缩后的样式文件路径为 `/stage/protyle/js/katex/katex.css`, 但是导出时引用的文件为 `/stage/protyle/js/katex/katex.min.css`, 可能是打包时遗漏了 `*.min` 后缀, 或者引用时多添加了 `*.min` 后缀

### 期待的结果 Expected result

导出时可以正常引用 katex 的样式文件

### 版本环境 Version environment

```markdown
- Version: 2.4.0
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

```log
:6806/stage/protyle/js/katex/katex.min.css?v=0.16.0:1
Failed to load resource: the server responded with a status of 404 (Not Found)

katex.min.css:1
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by Vanessa219** [comment]
我这里可以加载的，没有 katex.css 这个文件和相关的代码，还麻烦重试后提供更多信息和重现步骤。
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/970828/195968924-f910b153-91ce-4161-8879-0a3feca96824.png">
