### ISSUE TITLE
合并超级块后删除再撤销超级块解体

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#6205]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

例如两个块合并成超级块，把这个超级块删除，撤销后两个块就分开了，还得重新组合

### 期待的结果 Expected result

撤销后应该保持原样

### 版本环境 Version environment

```markdown
- Version: 2.4.0
- Operating System: Windows
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by TinkMingKing** [comment]
顺带问一句，katex宏定义是不是，不支持带参数

**Comment by 88250** [comment]
> 顺带问一句，katex宏定义是不是，不支持带参数

这个我不太清楚，KaTex 官方文档上支持吗？

**Comment by TinkMingKing** [comment]
> > 顺带问一句，katex宏定义是不是，不支持带参数
> 
> 这个我不太清楚，KaTex 官方文档上支持吗？

参照官方文档，使用正常，之前没看文档用法不对，但还有一些小问题我提一下

1. **公式包含中文报警告**

如果输入公式：

```
\dfrac{总体}{部分}
```

会正常显示，但是开发者工具会报警告多条，类似如下：

```
LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "总" used in math mode [unicodeTextInMathMode]
t.reportNonstrict @ katex.min.js?v=0.16.0:1
```

2. **公式复制为png显示不全**

上述公式复制图片显示如下：

![image](https://assets.b3logfile.com/siyuan/1652357352984/assets/image-20221015082756-bapqgpt.png)​

**顺带一提**

github的readme是不是该更新一下了，我看很多使用的开源项目的链接都没有，`katex`​，`mermaid`​，之类的

**Comment by 88250** [comment]
* 公式 PNG 复制不全可能是因为警告所言 "Unicode text character"
* 开源项目依赖欢迎通过 PR 帮忙整理
