### ISSUE TITLE
列表项内容为空时数据库表 blocks 的 markdown 字段缺少换行

### ISSUE THREAD

**Issue by jhzerone** [siyuan-note/siyuan#6206]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

无序列表空行或者只有空格行markdown数据异常
![image](https://user-images.githubusercontent.com/58368113/195882225-f44fd0da-5b38-43b5-ba02-7b898a189123.png)
拉取的markdown
![image](https://user-images.githubusercontent.com/58368113/195882302-d6cec6c7-2175-449e-a890-7599d9d0dbb6.png)

### 期待的结果 Expected result

期望能和其他内容的无序列表缩进格式一致

### 版本环境 Version environment

```markdown
- Version: 2.4
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
抱歉我没看明白你指的异常在哪里，麻烦补充说明。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by jhzerone** [comment]
抱歉, 是我没表示清楚, 是markdown的格式不对了
比如下图的markdown内容是带\n和缩进的
![image](https://user-images.githubusercontent.com/58368113/196073938-0f94cefc-67b6-4ae3-873b-f8e97b691375.png)
![image](https://user-images.githubusercontent.com/58368113/196073989-27eb8117-f817-4b75-8dbc-77fe74facedd.png)
但是如果这里的内容1, 2 是空格的话, markdown格式会变成单行.

**Comment by 88250** [comment]
请贴一下 Markdown 原文文本。

**Comment by jhzerone** [comment]
我是在思源里面编辑, 然后通过api获取的markdown内容

**Comment by 88250** [comment]
哪一个 API？

**Comment by jhzerone** [comment]
/api/query/sql  select * from blocks where id = 'blockid'
