### ISSUE TITLE
单元格内容无法换行

### ISSUE THREAD

**Issue by zhuzixian** [siyuan-note/siyuan#6207]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

单元格内使用回车键无法换行

### 期待的结果 Expected result

单元格内可使用回车键换行

### 版本环境 Version environment

```markdown
- Version: 2.4
- Operating System: window10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
使用 Shift+Enter
