### ISSUE TITLE
移动文档支持文件夹层级展开

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6208]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

通过菜单移动文档时，目前只会显示笔记本，想要移动到某一文档下作为该文档的子文档时只能通过搜索该文档，不方便。希望能展开笔记本。

### 描述可能的最优解决方案 Describe the optimal solution

选择移动目标位置时，笔记本能展开。

**Comment by 88250** [comment]
移动面板主要是为了搜索移动，应该不会考虑做成树形展开控件，感谢反馈。

**Comment by heimi98** [comment]
可以做成既能搜索，又能展开选中？主要直接拖动文件移动的方式也不方便。

**Comment by 88250** [comment]
目前不考虑了，没有时间精力做。
