### ISSUE TITLE
查询嵌入块面包屑过长导致分栏失效

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6211]
https://ld246.com/article/1665807488681

**Comment by Vanessa219** [comment]
超级块中的元素没有设定宽度时时自适应的，目前已经限定子块最大宽度为 100%，如果还超出的话可以设置一下横向超级块的子块宽度。

**Comment by hscui** [comment]
> 超级块中的元素没有设定宽度时是自适应且换行的，目前已经限定子块最大宽度为 100%，如果还超出的话可以设置一下横向超级块的子块宽度。

2.4.1更新后我安装依然和2.4.0一样，无法并排显示，设置两个嵌入块宽度均33%时，依然是上下显示，无法并排。
而且我非常不满意那个面包屑，一点意义都没。
