### ISSUE TITLE
能否支持多种导入/导出文件格式

### ISSUE THREAD

**Issue by ErDongChen1973** [siyuan-note/siyuan#6213]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在从别的笔记软件导入笔记时，为了保证笔记中的图片能正常显示，有时需要导出html格式或者其他文件格式，所以希望能支持多种文件导入或者导出格式，方便笔记迁移

### 描述可能的最优解决方案 Describe the optimal solution

Joplin的导入和导出笔记格式比较多，可以参考一下

**Comment by 88250** [comment]
目前暂时不会考虑支持，请通过其他方式转换为 Markdown 文件，感谢提议。
