### ISSUE TITLE
docker版 使用nginx做https代理 内核连接中断

### ISSUE THREAD

**Issue by ErDongChen1973** [siyuan-note/siyuan#6214]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

安装docker版的siyuan v2.4.0，并使用nginx实现https代理，网页访问时报“内核连接中断”错误。不使用https代理则可以正常访问

### 期待的结果 Expected result

希望能帮助修复一下这个问题

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/44294575/196019695-38f01bd3-756b-4ab7-b677-2af651cc3f57.png)

### 版本环境 Version environment

```markdown
- Version: 2.4.0
- Operating System: win10 64bit docker
- Browser (if used):
```

### 日志文件 Log file

E 2022/10/16 13:30:59 serve.go:238: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2022/10/16 13:31:01 serve.go:238: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2022/10/16 13:31:04 serve.go:238: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2022/10/16 13:31:04 serve.go:238: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2022/10/16 13:31:08 serve.go:238: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2022/10/16 13:31:10 serve.go:238: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
E 2022/10/16 13:31:10 serve.go:238: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

**Comment by 88250** [comment]
请参考 README 配置 WebSocket 反向代理。
