### ISSUE TITLE
能不能添加一个搜索图片中的文字的功能?

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#6216]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

某些图片无需加工,可直接添加到笔记里,但是以后搜索就很不方便

### 描述可能的最优解决方案 Describe the optimal solution

添加一个搜索图片中的文字的功能

**Comment by 88250** [comment]
目前无法支持。

关联：

* https://github.com/siyuan-note/siyuan/issues/4624
* https://github.com/siyuan-note/siyuan/issues/3470

**Comment by ccxuy** [comment]
当前调用OCR会阻塞编辑，没法继续粘贴图片，请问这个问题可以修复吗？

**Comment by 88250** [comment]
> 当前调用OCR会阻塞编辑，没法继续粘贴图片，请问这个问题可以修复吗？

https://github.com/siyuan-note/siyuan/issues/9230
