### ISSUE TITLE
排版优化转义内容异常

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6219]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

情况1：
块内换行后，上下行不同行符号还会继续解析，出现异常
![test1](https://user-images.githubusercontent.com/101307399/196021752-5a6330bc-ae12-4c40-9756-17ad46dc9a89.gif)

情况2：
块内换行后，上下行不同行符号加入转义符后不再解析，但是在下方继续输入内容后，使用优化排版，出现异常
![test2](https://user-images.githubusercontent.com/101307399/196021765-bc299643-35cf-46b7-92f1-93307c6eccb2.gif)

情况3：
在表格内使用块内换行后，上下行不同行符号加入转义符后不再解析，但是在下方继续输入内容后，使用优化排版出现异常，撤销后尝试修改内容，出现异常
![test3](https://user-images.githubusercontent.com/101307399/196021766-a4f7bf17-df78-4f1d-b291-75e19250d04a.gif)

### 期待的结果 Expected result

块内换行正常解析

### 版本环境 Version environment

```markdown
- Version: v2.4.0
- Operating System: Windows 11
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
情况 1 是符合 Markdown 语法预期的。

情况 2 和 3 可能是同一个问题，但是我这里重现不了：

![issue](https://user-images.githubusercontent.com/873584/196022463-3819e0e0-27f3-4c67-b228-59fdf314e13e.gif)

**Comment by Temacc0531** [comment]
> 情况 1 是符合 Markdown 语法预期的。
> 
> 情况 2 和 3 可能是同一个问题，但是我这里重现不了：
> 
在底下继续输入一些内容，再优化排版试试

**Comment by 88250** [comment]
感谢反馈，已经确认问题，但是情况 3 我这里不确定是否修复，请等新版发布以后帮回测看下。
