### ISSUE TITLE
表格可视化编辑改进

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#622]
> 目前表格可以增加行、列了，但是只能逐行、逐列地添加，对于较大的表格颇有不便。建议添加通过输入行列数扩展表格的功能，或者参照 typora 的可视化编辑。 #619

**Comment by walklty** [comment]
我补充一下表格内容能否根据栏宽自动wrap?

**Comment by 88250** [comment]
@walklty 估计不行，Markdown 表格里面没有指定宽度的语法。后面可能可以通过设置块属性 CSS 来做，但需要等等。

**Comment by Vanessa219** [comment]
一直按着快捷键就可以一直添加，不用重复点击了。这是不是个不用开发的好主意。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/555 中处理。
