### ISSUE TITLE
`ctrl n` 新建文档和块引新建文档的位置不一样。提供选项设置 `ctrl n`新建文档的存放位置或提供类似的新快捷键

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#6222]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在当前笔记记录中间想到其他的概念需要记录，且和当前文档无关联或关联位置未定。希望直接快速地在“未分类”文档下新建子文档，然后在后期再进行整理。

### 描述可能的最优解决方案 Describe the optimal solution

目前的 `ctrl n` 是比较方便的方式，但是可能考虑到其是在选定文档下新建子文档，希望能提供新的快捷键完成这一功能，或为 `ctrl n`新建文档位置提供选项。

**Comment by 88250** [comment]
暂时不考虑了，后续看是否有社区插件或者挂件支持，谢谢。

**Comment by choyy** [comment]
新建文档的位置，用挂件或者插件也太小题大做了吧
