### ISSUE TITLE
行内latex被错误渲染,块latex渲染正确

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#6224]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

$\lim _{x \rightarrow x_0} g(x)=u_0$ 被错误的渲染
<img width="167" alt="image" src="https://user-images.githubusercontent.com/62456287/196029339-4cbdedc5-1a16-4b4e-b6f2-7e644ed1327a.png">

$$
\lim _{x \rightarrow x_0} g(x)=u_0
$$
渲染正确
<img width="234" alt="image" src="https://user-images.githubusercontent.com/62456287/196029347-ca1e9893-a6e0-4215-862c-d56434f40f51.png">

### 期待的结果 Expected result

<img width="234" alt="image" src="https://user-images.githubusercontent.com/62456287/196029350-f2f097c5-e1a6-425f-8540-79ffac0a14fb.png">

### 版本环境 Version environment

```markdown
- Version: v2.4.0
- Operating System: Windows11 22h2
- Browser (if used):
```

### 日志文件 Log file

I 2022/10/16 17:40:10 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/10/16 17:40:10 runtime.go:47: kernel is booting:
    * ver [2.4.0]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_2.4.0.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\文档\笔记\SiYuan\SiYuan, data 2.0 MB]
I 2022/10/16 17:40:10 conf.go:226: using Microsoft Store edition
I 2022/10/16 17:40:10 serve.go:79: kernel is booting [http://127.0.0.1:6806]
I 2022/10/16 17:40:10 conf.go:578: database size [3.1 MB], tree/block count [10/977]
I 2022/10/16 17:40:10 working.go:151: kernel booted
I 2022/10/16 17:40:14 working.go:478: built-in pandoc [ver=2.19.2, bin=D:\文档\笔记\SiYuan\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2022/10/16 17:41:24 tree.go:150: migrated tree [D:\文档\笔记\SiYuan\SiYuan\data\20221002215140-o0q1azh\20221016174124-kxnnvdi.sy] from spec [] to [1]
I 2022/10/16 17:41:24 tree.go:150: migrated tree [D:\文档\笔记\SiYuan\SiYuan\data\20221002215140-o0q1azh\20221016174124-kxnnvdi\20221016174124-32lzkqj.sy] from spec [] to [1]
I 2022/10/16 17:41:24 tree.go:150: migrated tree [D:\文档\笔记\SiYuan\SiYuan\data\20221002215140-o0q1azh\20221016174124-kxnnvdi\20221016174124-rsgfqzj.sy] from spec [] to [1]
I 2022/10/16 17:41:24 tree.go:150: migrated tree [D:\文档\笔记\SiYuan\SiYuan\data\20221002215140-o0q1azh\20221016174124-kxnnvdi\20221016174124-rsgfqzj\20221016174124-zl37v4x.sy] from spec [] to [1]
I 2022/10/16 17:41:24 tree.go:150: migrated tree [D:\文档\笔记\SiYuan\SiYuan\data\20221002215140-o0q1azh\20221016174124-kxnnvdi\20221016174124-rsgfqzj\20221016174124-zl37v4x\20221016174124-a7mdfrb.sy] from spec [] to [1]
I 2022/10/16 17:41:24 tree.go:150: migrated tree [D:\文档\笔记\SiYuan\SiYuan\data\20221002215140-o0q1azh\20221016174124-kxnnvdi\20221016174124-rsgfqzj\20221016174124-zl37v4x\20221016174124-x8wlyz4.sy] from spec [] to [1]
I 2022/10/16 17:41:27 database.go:93: reinitialized database [D:\文档\笔记\SiYuan\SiYuan\temp\siyuan.db]
I 2022/10/16 17:41:27 index.go:180: rebuilt database for notebook [20221002215127-2v34vcf] in [0.09s], tree [count=7, size=373 kB]
I 2022/10/16 17:41:27 index.go:180: rebuilt database for notebook [20221002215140-o0q1azh] in [0.08s], tree [count=19, size=534 kB]
I 2022/10/16 17:41:27 index.go:180: rebuilt database for notebook [20221002215232-t2s0nwy] in [0.00s], tree [count=0, size=0 B]
I 2022/10/16 17:41:27 index.go:317: resolved refs [0] in [37ms]

**Comment by Zuoqiu-Yingyi** [comment]
@a15355447898a 可以使用如下两种方案解决
```markdown
$\lim\limits_{x \rightarrow x_0} g(x)=u_0$
$\displaystyle \lim_{x \rightarrow x_0} g(x)=u_0$
```

**Comment by 88250** [comment]
我关闭了，谢谢。
