### ISSUE TITLE
搜索快捷键设置无效

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#6225]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

这里要修改的两个快捷键是固定搜索和全局搜索，两者的默认快捷键分别是command + shift + f，和command + p。现在想要将前者改为control + shift + g，后者改为 control + shift + f。设置后刷新并关闭设置弹框，鼠标移到全局搜索按钮后能看到提示的快捷键已经是修改后的结果

<img width="211" alt="image" src="https://user-images.githubusercontent.com/33319484/196030268-3bc88b9c-213b-4e0f-8be4-c4701d8b3159.png">

但使用control + shift + f还是无法唤起全局搜索窗口，也无法用默认快捷键唤起，重启思源也无效。记得以前是可以修改默认快捷键的

### 期待的结果 Expected result

能够正常设置修改默认快捷键

### 版本环境 Version environment

```markdown
- Version: v2.4.0
- Operating System: Mac OS 12.5
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9794183/siyuan.log)

**Comment by JokeenZhang** [comment]
下载新的主题后，鼠标移动到全局搜索按钮后，显示的是默认快捷键

**Comment by 88250** [comment]
我这里修改这两个快捷键没有遇到问题，但是改完后全局搜索按钮的 tip 确实没有变。

**Comment by Vanessa219** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/970828/196068179-639727f5-0b49-47fd-bcf3-79ead5285c47.png">
