### ISSUE TITLE
日历功能希望能关联所有的新建文档，不仅仅是日记

### ISSUE THREAD

**Issue by mingyong-g** [siyuan-note/siyuan#6226]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

- 日历功能可用于快速回顾历史
- 日历功能是时间玩儿维度的智能归档

### 描述可能的最优解决方案 Describe the optimal solution

日历功能不仅仅是关联日记文档，而是关联所有的文档（根据文档的创建日期）通过日历面板预览某日新建的文档列表

### 其他信息 Other information

越来越好用了👍

**Comment by mingyong-g** [comment]
这个日历看板，好像是notion theme 插件提供的，希望能原生实现并增强一下下。

**Comment by 88250** [comment]
介于时间精力有限，这部分估计不会考虑了，期待一下社区插件或者挂件吧，谢谢。
