### ISSUE TITLE
标签创建显示优化

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6227]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在使用#激活标签时，创建新标签的选项是排在使用现有标签上面的。

这样的排序顺序可能适用于文档，但是对于标签来说是利大于弊的。

因为标签和文档不同，标签的复用程度远高于文档。**使用标签的频率是明显要大于创建标签的频率。**
一般人创建几个or几十个标签就会一直复用，而不会一直创建新标签。

比如我打个“略”字，我希望可以回车直接复用“略差于预期”这个标签，而不是创建一个“略”标签。 现在这种排序方式，我只能每次都把这几个字完整地打出来，或者每次都得手动用鼠标点一下。
![image](https://user-images.githubusercontent.com/37429029/196037906-40addeb9-6588-46fa-92b6-f98b0eeedd94.png)

这一点真的对我这个标签使用较为频繁的用户造成了困扰。ε(┬┬﹏┬┬)3

### 期待的结果 Expected result

将复用现有标签的优先级排在创建新标签之上。 这样能最大化标签的使用效率和便捷程度
像这样
![QQ截图20221016110226](https://user-images.githubusercontent.com/37429029/196037844-c6721753-80ff-4395-95f8-f111e6a88732.png)

### 版本环境 Version environment

```markdown
- Version: 2.4
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9794629/siyuan.log)

**Comment by 88250** [comment]
新建应该只能放在第一个，否则标签过多的话要拉倒最后才能看到新建了。搜索可以多给几个关键字，或者用后面的关键字，比如你例子中的“预期”，我关闭了，谢谢。

**Comment by yuyuyu-github** [comment]
好的

**Comment by yuyuyu-github** [comment]
不过还是有些问题，

创建标签的次数可能会有10次，使用标签的次数却会有100次。  标签数多到需要下拉才能看到新建的次数可能只有1次。

牺牲1次、10次创建标签的便利度。 让100次的使用标签更加方便或许更妥。

 因为滴答清单的标签数量也是特别多的，采用新建在下用起来很方便，也没有出现新建需要下拉的烦恼。

**Comment by 88250** [comment]
暂时先不动了，需要继续收集用户反馈，谢谢。

**Comment by yuyuyu-github** [comment]
> 暂时先不动了，需要继续收集用户反馈，谢谢。

明白O(∩_∩)O
