### ISSUE TITLE
`private.key` 使用临时随机文件

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#623]
在同步时生成随机 key 文件，用完即删，降低泄露风险。

**Comment by SylleoYr** [comment]
> 私钥难道不是用户唯一的吗？🤷‍♂️，随机的怎么区分用户呀。

一个小的想法：不管是加密还是使用随机文件，都建议在内存中操作私钥（不知道是否可行）。

**Comment by 88250** [comment]
@SylleoYr Windows 上暂时搞不定，所以先用随机文件了。
