### ISSUE TITLE
是否有计划做一个分享功能？

### ISSUE THREAD

**Issue by zburu** [siyuan-note/siyuan#6234]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

思源笔记功能已经很强大了，涵盖我所需要的内容，但是有时候需要分享某些文档给好友，是否有计划做分享外链的功能？

### 描述可能的最优解决方案 Describe the optimal solution

参照trilium的share功能，可以给文件或者文件夹启用分享，个人觉得这种设定很棒。
1. 如果是文件夹的话，会在侧边生成一个目录树，类似于文档的形式
2. 如果是单文件，则直接以单页形式分享

参考链接：https://github.com/zadam/trilium 
https://trilium.zburu.com/share/weekly

### 描述候选的解决方案 Describe the candidate solution

希望最基础的单页分享功能可以做出来。

**Comment by 88250** [comment]
请看用户指南常见问题 `## 如何分享笔记？`。
