### ISSUE TITLE
编辑嵌入块内容时支持在新标签页打开

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6236]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前编辑嵌入块内容是在浮窗进行，页面太小了，希望可以在在新标签页打开编辑。

### 描述可能的最优解决方案 Describe the optimal solution

在新标签页打开编辑。

**Comment by 88250** [comment]
楼上正解。
