### ISSUE TITLE
引用显示优化

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6238]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

这是一段引用两个文档的文本

![QQ截图20221017161638](https://user-images.githubusercontent.com/37429029/196145896-0a87ac00-5612-4381-8bb1-aec0094cff61.png)

现在我在别的位置引用这一段内容，效果是直接连起来显示的。 
可是黑人+牙膏 和黑人牙膏完全不是一个意思，误导人。
能否对相邻的引用内容区分一下子。

![QQ截图20221017161720](https://user-images.githubusercontent.com/37429029/196145998-b5b112b8-4d13-49db-a4e5-8513e7420512.png)

### 期待的结果 Expected result

![image](https://user-images.githubusercontent.com/37429029/196146440-5f134659-c2e7-4b70-94c9-8ef492c6b721.png)
可以还原这种显示效果。
或者默认用空格分开一下。 连起来显示容易造成歧义。 不知道的以为我引用了一个叫做“黑人牙膏”的文档

### 版本环境 Version environment

```markdown
- Version: 2.4.1
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9799159/siyuan.log)

**Comment by 88250** [comment]
你引用的可能是这个块 
![image](https://user-images.githubusercontent.com/873584/196152998-2a2d1bc3-5bc4-4903-9fcc-aa912b5dda8c.png)

而不是原有两个分开的定义块。
