### ISSUE TITLE
设置-导出倒数第二、三选项选取范围不对

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#6243]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

具体看截图和录屏
我不知道该怎么形容，实在不好意思。

### 期待的结果 Expected result

在对应按钮上点击才能启用该功能

### 截屏或者录屏演示 Screenshot or screen recording presentation

截图：
![「思源笔记」设置-导出倒数第二、三选项选取范围不对](https://user-images.githubusercontent.com/98400319/196216038-80b6d919-1f7b-4be5-ac1a-d68f4527f524.png)
录屏：
![「思源笔记」设置-导出倒数第二、三选项选取范围不对](https://user-images.githubusercontent.com/98400319/196216075-671cfccb-3f0c-4ce3-9a57-c7ec172aa8f6.gif)

### 版本环境 Version environment

```markdown
- Version: 2.4.1
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/9801964/system-log.zip)

**Comment by Vanessa219** [comment]
这是浏览器对 label 标签的优化，在可以使用 label 的情况下我们会尽可能的使用它。这样不需要精确的点击到按钮上也可以有同样的效果。其他设置项中也有类似的情况。

**Comment by EberhardLin** [comment]
> 这是浏览器对 label 标签的优化，在可以使用 label 的情况下我们会尽可能的使用它。这样不需要精确的点击到按钮上也可以有同样的效果。其他设置项中也有类似的情况。

可是如果这样就会有误触（不小心点击）的风险，我就是不小心点到了，才发现的。
