### ISSUE TITLE
可以支持全局定义挂件插入后默认的大小和对齐方式（居左/居中/居右）吗

### ISSUE THREAD

**Issue by crendy** [siyuan-note/siyuan#6251]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

插入drawio挂件，目前默认居中，默认大小也比较小，每次都得手动调整，和挂件作者了解到可以改主题的全局css：
.b3-typography .iframe, .protyle-wysiwyg .iframe { text-align: left; }
.b3-typography iframe, .protyle-wysiwyg iframe { width: 765px; height: 256px; }
但是主题更新后还得自己再改，笔记设置里面可以支持这种全局的定义会更方便。

### 描述可能的最优解决方案 Describe the optimal solution

这笔记设置-外观里面 专门增加类似挂件的这种全局自定义能力，可以让用户自行设置

**Comment by 88250** [comment]
试试 css 片段 https://github.com/siyuan-note/siyuan/issues/6143
