### ISSUE TITLE
将无序列表转换成思维导图

### ISSUE THREAD

**Issue by zzw6776** [siyuan-note/siyuan#6253]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

将无序列表转换成思维导图,目前官方自带的思维导图功能不管是操作性,还是学习成本,还是美观度都有点欠缺
如果能将无序列表转为思维导图(类似于飞书思维导图的功能,或者简单实现像dark+主题里的功能)
不管是操作习惯还是视觉效果都好很多

### 描述可能的最优解决方案 Describe the optimal solution

参照dark+主题里的增强菜单里的无序列表转换为脑图的功能
![image](https://user-images.githubusercontent.com/14048998/196329285-cfd9ea71-c4a4-4baf-86bc-8d2f58ffc76e.png)

**Comment by 88250** [comment]
暂时不考虑了，后续如果要做的话会重开该提议，谢谢。
