### ISSUE TITLE
超级快中引述块中的嵌入块突破天际！

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6255]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/97731736/196343916-69edebd5-1918-4b3f-ab96-0f851cce7db8.png)

### 期待的结果 Expected result

正常

### 版本环境 Version environment

```markdown
- Version: v2.4.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

[测试文档.sy.zip](https://github.com/siyuan-note/siyuan/files/9806773/sy.zip)

**Comment by 88250** [comment]
感谢反馈，在 https://github.com/siyuan-note/siyuan/issues/6258 中改进。

**Comment by Vanessa219** [comment]
可先参考 https://ld246.com/article/1665807488681 解决
