### ISSUE TITLE
列表配色及缩进改进

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#6256]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

如图
![image](https://user-images.githubusercontent.com/32903588/196388500-82072f45-35bb-4a20-96fe-a7b56f8eded7.png)

### 期待的结果 Expected result

无

### 版本环境 Version environment

```markdown
- Version: 2.4.1
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
是不是感觉这个聚焦状态下的蓝色背景好像没有必要？

**Comment by TinkMingKing** [comment]
感觉有会好一点点，但是没有也没关系，图省事的话当然直接去掉，保留的话，颜色统一一下会舒服点
