### ISSUE TITLE
Edge插件不能保存某些文章

### ISSUE THREAD

**Issue by xibaoning** [siyuan-note/siyuan#6263]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [x] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

https://mp.weixin.qq.com/s/11Tszw-Sa1rQq5Zka7g08Q
如上地址的文章, 发送到思源, EDGE浏览器滚动条滚动完成,但笔记中并没有出现此文章

### 期待的结果 Expected result

正常保存

### 版本环境 Version environment

```markdown
- Version: docker 最新版
- Operating System: win10
- Browser (if used):edge
```

### 日志文件 Log file

无

**Comment by xibaoning** [comment]
我也录制了视频,请查看

**Comment by xibaoning** [comment]
请看操作, 好像的确有问题

**Comment by xibaoning** [comment]
操作过程
![image](https://github.com/xibaoning/BlazorWorker/blob/master/Video_2022-10-19_092342.gif)

**Comment by xibaoning** [comment]
请看操作过程
![image](https://github.com/xibaoning/BlazorWorker/blob/51ca151a33d8cb8df9f0b30dff003dd9d37a5200/Video_2022-10-19_092342.gif?raw=true)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/196702730-96285315-ba33-4cfa-a66b-15c6585a5141.png)

**Comment by xibaoning** [comment]
![image](https://github.com/xibaoning/BlazorWorker/blob/master/333.jpg?raw=true)
![image](https://github.com/xibaoning/BlazorWorker/blob/master/2222.gif?raw=true)

**Comment by 88250** [comment]
我之前截图的是 Chrome 😂 

这个问题估计一时半会不好排查，建议试下扩展连接桌面端内核。

**Comment by xibaoning** [comment]
好像选择正文后, 右键Copy To Siyuan, 然后去文档paste也没有任何内容, 好像没复制到剪贴板, 粘贴出来是其他内存, 不是本次复制内容

**Comment by 88250** [comment]
看下是不是浏览器没有给剪切板权限。

**Comment by xibaoning** [comment]
![image](https://github.com/xibaoning/BlazorWorker/blob/master/333.gif?raw=true)

**Comment by xibaoning** [comment]
有的, 其他文章插件模式, 手动复制正文都可以,  这个文章不行(插件与复制都不行)

**Comment by 88250** [comment]
那就不太清楚了……

**Comment by xibaoning** [comment]
1.14插件有些文章仍然无法保存, 插件开发调试打开后看到异常:
SyntaxError: Unexpected token '<', "html>
<h"... is not valud json
Promise.catch  background.js 123

样例文章 https://mp.weixin.qq.com/s/LY4hLa6rGRK6U14efAa3Gw

**Comment by xibaoning** [comment]
根据提示已解决, 配置了路由nginx的请求大小限制后正常
