### ISSUE TITLE
网络超时导致同步失败时提示报错异常

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6265]
https://ld246.com/article/1666160219487

不应该提示仓库损坏，而应该提示网络超时。

**Comment by TankNee** [comment]
由于我的网络环境经常会断网，导致经常出现网络连接超时的通知，并且这个通知不会自动消失。
能否给这个通知加一个定时消失的功能？

**Comment by 88250** [comment]
报错的提示文案需要手动确认才会消失，避免遗漏。
