### ISSUE TITLE
Linux error opening program

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6268]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/90691302/196721228-0ccf0d32-1011-4ca4-91f2-1236ebc02cc3.png)

### 期待的结果 Expected result

open normally

### 版本环境 Version environment

```markdown
- Version: 2.4.2
- Operating System: Linux AppImage
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9821382/siyuan.log)

**Comment by 88250** [comment]
Thanks for reporting this problem, we have re-uploaded the installation package, please download and install it in [Releases](https://github.com/siyuan-note/siyuan/releases).
