### ISSUE TITLE
虚拟引用解析渲染异常

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#6269]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![文档打开卡顿](https://user-images.githubusercontent.com/54146035/196733412-c81757d3-8584-4f86-a5e8-c418edf410bd.gif)

文档字数并不多，但是加载很卡，等加载完出现大量虚拟引用块
![JK}@@ZC4KK_2HG5}OO6N`7O](https://user-images.githubusercontent.com/54146035/196733521-c751b507-ceee-4d5e-b78b-e8beb73e30c6.jpg)

关闭虚拟引用后，加载没问题，直接加载成功

### 期待的结果 Expected result

打开虚拟引用后，可以正常加载文档

### 版本环境 Version environment

```markdown
- Version: 2.4.2
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无异常

**Comment by 88250** [comment]
方便打包一个能重现问题的最小数据集给我们吗？ 845765@qq.com

**Comment by UltramarineSky** [comment]
> 方便打包一个能重现问题的最小数据集给我们吗？ [845765@qq.com](mailto:845765@qq.com)

有点不好弄，得找有虚拟引用相关的文档，我试着单独弄一个笔记本出来但没触发

**Comment by 88250** [comment]
稍后我们会打包一个 dev 版本 v2.4.3-dev1，请在 Releases 下载帮忙测试，谢谢。

**Comment by 88250** [comment]
稍后会发布 v2.4.3，其中 https://github.com/siyuan-note/siyuan/issues/6272 对虚拟引用做了调整，请等发布以后再试试是否解决了该问题，谢谢。

**Comment by UltramarineSky** [comment]
> 稍后会发布 v2.4.3，其中 #6272 对虚拟引用做了调整，请等发布以后再试试是否解决了该问题，谢谢。

好了，可以顺利加载文档出来，没有卡很久
