### ISSUE TITLE
在加载界面卡住

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6275]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

Only this screen is left with the symbol flashing at times.

![image](https://user-images.githubusercontent.com/90691302/196759988-90d7c003-016b-43ff-b4de-207bd4db418f.png)

### 期待的结果 Expected result

Normall app

### 版本环境 Version environment

```markdown
- Version: 2.4.2
- Operating System: Linux AppImage
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9822791/siyuan.log)

**Comment by 88250** [comment]
Ctrl+Shift+I open dev tool, checks if there are some issues in Network and Console, thanks.

**Comment by 88250** [comment]
Did you use community themes or custom themes?

**Comment by taozina0587** [comment]
None. I like to use the original so I don't have to wait for the theme creators to update

**Comment by 88250** [comment]
Chinese community users also encountered similar problems, but we have not located the problem yet.

* https://ld246.com/article/1666194285947
* https://ld246.com/article/1666193709701
