### ISSUE TITLE
emoji 文件图标某些情况下无法显示

### ISSUE THREAD

**Issue by wanghuiyt** [siyuan-note/siyuan#6277]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在一些情况下, 比如切换明亮和黑暗主题. 或者其它情况(具体我忘了哪种情况, 暂时无法复现问题), emoji 图标无法显示.
具体可见附件的图片, 绿框里的图标是正常显示的, 红框里的是异常显示的. 

### 期待的结果 Expected result

正常显示图标

### 截屏或者录屏演示 Screenshot or screen recording presentation

![siyuan_1](https://user-images.githubusercontent.com/25444996/196843508-cb382a45-97a5-4d8b-9b3a-77e3f009e158.png)

![siyuan_2](https://user-images.githubusercontent.com/25444996/196843598-8dc2c34e-8711-48b2-aaeb-8b1ec6397678.png)

### 版本环境 Version environment

```markdown
- Version: v2.4.3 docker 版本
- Operating System: Ubuntu 22.04 LTS
- Browser (if used): Chrome 106.0.5249.119 (正式版本) （64 位）
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9825731/siyuan.log)

**Comment by 88250** [comment]
麻烦继续留意观察重现步骤，我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
