### ISSUE TITLE
全屏模式   时留一个可以拖动窗口的地方（两个普通按钮大小）

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#6279]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Alt+Y 全屏切换到全屏模式之后，如果层级太深，想要拖动窗口，但是没有鼠标下手的地方了，如下图

![](https://s3.bmp.ovh/imgs/2022/10/20/ff36cd0ece881ebd.png)

### 描述可能的最优解决方案 Describe the optimal solution

是否可以在右上角或左上角留一个可以拖动窗口的按钮（1-2两个普通按钮的区域），以便写笔记的的时候拖动窗口

### 描述候选的解决方案 Describe the candidate solution

目前可以使用下图的方式顶一顶

![](https://s3.bmp.ovh/imgs/2022/10/20/2020f51046a994e0.png)

**Comment by Vanessa219** [comment]
<img width="61" alt="image" src="https://user-images.githubusercontent.com/970828/197089487-4b4ab56a-fc36-4272-b199-3292f54af714.png">

**Comment by Geo123abc** [comment]
> <img alt="image" width="61" src="https://user-images.githubusercontent.com/970828/197089487-4b4ab56a-fc36-4272-b199-3292f54af714.png">

能不能改成这样子，以便于
1. 和主界面保持一致
2. 提高软件辨识度
3. 比之前的空白样式更醒目，方便操作

![](https://s3.bmp.ovh/imgs/2023/01/17/1029da4bf3b7feaf.png)

**Comment by Vanessa219** [comment]
使用默认主题试试
<img width="583" alt="image" src="https://user-images.githubusercontent.com/970828/213070956-ab6d3fd2-492a-44b7-821b-08e548168aab.png">

**Comment by Geo123abc** [comment]
> 使用默认主题试试 <img alt="image" width="583" src="https://user-images.githubusercontent.com/970828/213070956-ab6d3fd2-492a-44b7-821b-08e548168aab.png">

默认主题是“naive”吧？我试了下，和我想的不一样
可能是我前面没有表述清楚，重新表述一下

![](https://s3.bmp.ovh/imgs/2023/01/18/27640c539fa703d5.png)

![](https://s3.bmp.ovh/imgs/2023/01/18/929611e6bd8a3518.png)

**Comment by Vanessa219** [comment]
默认主题是 daylight

**Comment by Geo123abc** [comment]
> 默认主题是 daylight

我试了一下，还不是我描述的效果，再描述一下

![](https://s3.bmp.ovh/imgs/2023/01/23/0a865a375c4dd206.png)

![](https://s3.bmp.ovh/imgs/2023/01/23/1fa31f8942a71c15.png)

![](https://s3.bmp.ovh/imgs/2023/01/23/4ce703bc703b79d5.png)

**Comment by Soltus** [comment]
即使下图黄色区域满了，仍可以通过红色区域拖拽，还加啥啊？
![image](https://user-images.githubusercontent.com/83791825/213950049-9bdfa9d8-2afc-430d-8ec1-9d0f560985a7.png)

**Comment by Geo123abc** [comment]
> 

我是想在红色区域塞一个思源笔记的图标

黄色区域应该无法铺满（预留了一点空白区域作为拖拽点）

**Comment by Geo123abc** [comment]
> 即使下图黄色区域满了，仍可以通过红色区域拖拽，还加啥啊？ ![image](https://user-images.githubusercontent.com/83791825/213950049-9bdfa9d8-2afc-430d-8ec1-9d0f560985a7.png)

我是想在红色区域塞一个思源笔记的图标

黄色区域应该无法铺满（预留了一点空白区域作为拖拽点）

**Comment by Vanessa219** [comment]
已有功能已满足，可使用自定义进行个性化定制，主要修改 `.fullscreen > .protyle-breadcrumb, .fullscreen` 样式即可。
