### ISSUE TITLE
剪切折叠的标题默认是剪切标题以及下方的块

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#6287]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![Snipaste_2022-10-21_11-32-08](https://user-images.githubusercontent.com/60436214/197105412-56da7fa3-ddd2-4307-a906-13e9d3fa5b74.png)
虽然已经支持了标题可以设置剪切标题以及下方的块
但我觉得折叠的标题的剪切可以是默认剪切标题以及下方的块，这样比较符合直觉。因为通常来说只剪切标题需求并不大，完全可以通过复制标题解决。

### 描述可能的最优解决方案 Describe the optimal solution

- 未折叠的标题，直接Ctrl+X剪切只剪切标题，点击块标可以剪切标题以及下方的块
- 折叠的标题，Ctrl+X默认剪切标题以及下方的块

**Comment by 88250** [comment]
这个逻辑之前考虑过，但是折叠的时候也需要仅剪切标题块，所以目前这个折中方案较为稳妥。

**Comment by Achuan-2** [comment]
我觉得折叠的时候剪切标题块，我完全可以通过复制标题+删除解决，这个并不麻烦。
而如果多个标题折叠，需要同时剪切多个标题以及下方的内容，按照目前的方式则麻烦了，需要一个个点击删除

**Comment by 88250** [comment]
多个折叠标题的话试试分屏划选移动。

**Comment by Achuan-2** [comment]
嗯，我只是觉得剪切标题以及下方块在调整文档结构时用的特别多，不应该搞这么麻烦。
当然这只是个人的使用习惯，如果D大觉得没必要改进就不改吧，只是提提意见。

**Comment by 88250** [comment]
我们继续收集反馈看，谢谢。
