### ISSUE TITLE
关于思源备注功能的改进建议

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#6288]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

思源目前的备注功能我觉得使用起来还是不顺手。
编辑不方便、不支持方便的加样式、不支持图片，以及D大之前说过备注和双链导出脚注的话会冲突

最近觉得备注功能完全可以统一为双链，充分利用双链的优势。可以把备注改为另一种创建双链的方式，即使用备注默认在本文档创建一个【备注/annoation】子文档，每次在本文档的备注子文档末尾append要备注的内容，在该文档以有序列表的方式组织，并且这个备注子文档支持改名和移动（即在父文档属性中绑定备注子文档的id，更复杂点可以支持修改这个备注子文档的id）。这样备注既可以是富文本，也可以导出为脚注。用户可以选择划选文本Alt+【一个备注创建一个文档，也可以是把备注内容都放入一个文档里。

这样思源的双链、备注、脚注其实都统一了。
![Snipaste_2022-10-21_12-05-09](https://user-images.githubusercontent.com/60436214/197109224-406d3318-9a61-4510-a326-a3b8e05691f9.png)
![Snipaste_2022-10-21_12-05-31](https://user-images.githubusercontent.com/60436214/197109236-041a2044-3a60-4b7e-873a-0557cdde750f.png)

### 描述可能的最优解决方案 Describe the optimal solution

把备注改为另一种创建双链的方式，即使用备注默认在本文档创建一个【备注/annoation】子文档

### 描述候选的解决方案 Describe the candidate solution

通过用户自行写脚本实现。

**Comment by 88250** [comment]
目前内置的备注设计应该不会改变了，后续期待社区开发者进行扩展，感谢反馈。
