### ISSUE TITLE
粘贴引用描文本没有适应斜体中样式

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6291]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

默认黑暗主题下测试
![粘贴引用描文本没有适应斜体中样式](https://user-images.githubusercontent.com/97731736/197126515-7c2ce992-3a78-4cf0-9dd6-4944c9ea39f5.gif)

### 期待的结果 Expected result

粘贴拥有文本也能在斜体中适应样式

### 版本环境 Version environment

```markdown
- Version: v2.4.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
剪切板中的引用没有斜体就不会有斜体样式，如果是复制带有斜体的引用，粘贴后也会是斜体的。
