### ISSUE TITLE
设置的搜索设置存在误导问题

### ISSUE THREAD

**Issue by xiaoyoucheng** [siyuan-note/siyuan#6295]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/33143581/197215531-9bbaf6f8-a8b3-417c-a2e2-c5c61181ed1d.png)
如图所示，该界面的搜索设置很容易让人误导认为是Ctrl+P 或者 Ctrl+F 的搜索条件。但是实际上是“((”引用的搜索条件。

### 期待的结果 Expected result

在设置中更清楚的描述该项设置的意义。

### 版本环境 Version environment

```markdown
- Version: 2.3.0
- Operating System: Windows 10 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
改设置是对所有搜索相关的功能都生效的。

**Comment by 88250** [comment]
截图看下设置和搜索结果。

**Comment by xiaoyoucheng** [comment]
> 截图看下设置和搜索结果。

我明天补充一下相关截图，现在已经关电脑了。
还是说Ctrl+P那的搜索设置会覆盖设置中的搜索设置？

**Comment by 88250** [comment]
> 还是说Ctrl+P那的搜索设置会覆盖设置中的搜索设置？

会覆盖。

**Comment by xiaoyoucheng** [comment]
> > 还是说Ctrl+P那的搜索设置会覆盖设置中的搜索设置？
> 
> 会覆盖。

但是假如我第一次是把设置中的搜索里的列表项关了，但是因为搜索栏目中的设置默认是全开可以搜索的，此时从搜索栏搜索还是可以搜索出列表项。这样的情况下还是会发生我前面说的，使用者误以为自己设置了过滤，实际没有的情况。

**Comment by 88250** [comment]
割裂开是特性，否则全局搜索的类型过滤就没有存在的意义了。引用的搜索目前只有设置里面有过滤选项。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by xiaoyoucheng** [comment]
> 割裂开是特性，否则全局搜索的类型过滤就没有存在的意义了。引用的搜索目前只有设置里面有过滤选项。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

所以开始只是建议设置写清楚点，因为本来就是分开的，但是Ｄ大你说对所有设置都生效。假如不知道搜索中有设置，很容易让人误以为是bug。

**Comment by 88250** [comment]
好的，下个版本我们改进一下文案，谢谢。

**Comment by xiaoyoucheng** [comment]
> 好的，下个版本我们改进一下文案，谢谢。

麻烦Ｄ大了。
