### ISSUE TITLE
微信小助手支持语音、视频和文件

### ISSUE THREAD

**Issue by bemofan** [siyuan-note/siyuan#6296]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

分享生活片段，处理某些存档文件，需要手机分享到思源

### 描述可能的最优解决方案 Describe the optimal solution

无

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

因为不懂得数据传递的时候有什么类型限制，但是还是希望能用这个功能，这样基本就形成闭环了

**Comment by 88250** [comment]
感谢提议，语言、视频和文件应该可以支持。

**Comment by Achuan-2** [comment]
那文件是保存到思源的云端吗，还是从微信链接下载x

**Comment by 88250** [comment]
> 那文件是保存到思源的云端吗，还是从微信链接下载

只能转存到思源云端。

**Comment by 88250** [comment]
关联 #6301
