### ISSUE TITLE
限制笔记本名和文档名最大长度为 `512`

### ISSUE THREAD

**Issue by Soltus** [siyuan-note/siyuan#6299]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

因为未限制文档名最大长度，我创建了一个文档名有21万多字符的文档，结果导致了打开所在笔记本的卡顿（重点），以及涉及到索引的其他一些操作的卡顿。虽然说理论上用户不会创建如此长的文档名，但是软件还是应该禁止这种不规范操作

### 期待的结果 Expected result

限定一个文档名最大长度，例如一万字符，并在用户继续输入时提醒。

### 版本环境 Version environment

```markdown
- Version: 2.4.4
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9840504/siyuan.log)

**Comment by 88250** [comment]
我们限制在 512 个字符吧。

**Comment by Soltus** [comment]
补充：
![image](https://user-images.githubusercontent.com/83791825/197237970-4a79411d-4ee2-43ff-bc4f-b983e6d6455a.png)
文档名过长无法正常通过对话框删除，需要在【设置】-【文档树】开启【删除文档不需要确认】
