### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by Mehr-o-maah** [siyuan-note/siyuan#6304]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

when I try to import my files over I'm getting a file called 'corrupted'
![image](https://user-images.githubusercontent.com/50089525/197314776-bda5ef41-a229-40e9-b3fd-bcaeb5284713.png)
![image](https://user-images.githubusercontent.com/50089525/197314785-12cd56d8-9480-4844-8e7f-663663d5abeb.png)
Is there a way to get my notes back? I've been working on them for months

### 期待的结果 Expected result

fix corrupted file

### 版本环境 Version environment

```markdown
- Version: 2.4.4
- OperatingSystem: Ubuntu
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9843365/siyuan.log)

**Comment by 88250** [comment]
Hello, if not found .siyuan/conf.json under notebook folder, SiYuan will move this notebook folder to corrupted dir, check code here: https://github.com/siyuan-note/siyuan/blob/69a97137763a23e2324c0f64a45ac5aa0f73642f/kernel/model/box.go#L88

Move these notebook folder from corrupted dir to data folder manually, and then create a new ./siyuan/conf.json under it.

**Comment by Mehr-o-maah** [comment]
@88250  Can you better elaborate on what to do, steps to follow to restore my notes, now I know that I dont have .siyuan file so, what can I do?

**Comment by 88250** [comment]
> @88250 Can you better elaborate on what to do, steps to follow to restore my notes, now I know that I dont have .siyuan file so, what can I do?

![image](https://user-images.githubusercontent.com/873584/197348475-2241101f-e0f5-4fb7-833e-722af08d45fe.png)

**Comment by Mehr-o-maah** [comment]
This is what I'm doing after your response 

https://user-images.githubusercontent.com/50089525/197357305-6be5e102-d73f-4507-9aaa-a31edef4b703.mp4

-I tried emptying the conf file letting just the {}.  -moving the files to the new generated Siyuan after adding the .siyuan file

**Comment by 88250** [comment]
* Switch workspace in the Settings - About
* Notebook configuration file should be placed under the notebook dir (workspace/data/{notebook id}./siyuan/), do not place it under data dir (workspace/data/.siyuan/)

**Comment by Mehr-o-maah** [comment]
A big thanks, I really like this app, This was really important to me so thank you 😭

**Comment by 88250** [comment]
Not at all, have a good day.
