### ISSUE TITLE
云端收集箱文档内添加刷新按钮

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#6306]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![Snipaste_2022-10-22_15-46-02](https://user-images.githubusercontent.com/60436214/197327420-f9f25e93-d593-4d01-9b61-077551e14a5f.png)
在利用微信思源小助手在收集的时候，思源收集箱会收集当日的信息到当天的文档里，目前有一个问题是，如果又用手机发送了信息（比如图片），要刷新收集箱内容就得返回上一层才能刷新，稍微有点麻烦，很打乱节奏。希望能在收集箱文档里也添加刷新按钮，不用再退出刷新

### 描述可能的最优解决方案 Describe the optimal solution

云端收集箱每日文档内也添加刷新按钮，能刷新当前内容

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by Vanessa219** [comment]
adf424f7c45fef05e380420337dea54fca88b815
