### ISSUE TITLE
是否可以提供便捷版本

### ISSUE THREAD

**Issue by cnlxh** [siyuan-note/siyuan#6308]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

由于各种原因，我工作场景无法安装软件，但是我非常喜欢贵软件，是否可以提供无需安装的便捷版本，十分感谢

### 描述可能的最优解决方案 Describe the optimal solution

由于各种原因，我工作场景无法安装软件，但是我非常喜欢贵软件，是否可以提供无需安装的便捷版本，十分感谢

**Comment by 88250** [comment]
目前应该可以安装到 U 盘，暂时不考虑直接打包发布便携版，谢谢。
