### ISSUE TITLE
点击图片Ctrl+Shift+A新建一行输入文本后按Backspace会导致图片消失

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#6309]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![Snipaste_2022-10-22_22-51-50](https://user-images.githubusercontent.com/60436214/197345804-6e0e6ef9-97c4-4658-bbdd-3a4add0404b3.png)
复现步骤
1. 在点击图片后按Ctrl+shift+A，即使输入文本，也可以看到图片依然是处于聚焦状态
![Snipaste_2022-10-22_22-55-27](https://user-images.githubusercontent.com/60436214/197345972-d6f4bb90-6822-48fb-b317-f20a00fa65d7.png)
2、按删除
![Snipaste_2022-10-22_22-55-46](https://user-images.githubusercontent.com/60436214/197345992-af5bc54e-2345-46af-908d-6286f1612d24.png)
3、刷新后，图片又会回来（也就是说实际没有删除？）
我觉得原因在于点击图片后按Ctrl+Shift+A，图片依然处于聚焦状态，虽然后面依然能正常输入文字，但一按删除，就删除图片了。

### 期待的结果 Expected result

点击图片后按Ctrl+Shift+A，图片失去焦点

### 截屏或者录屏演示 Screenshot or screen recording presentation

见上

### 版本环境 Version environment

```markdown
- Version: 2.4.4
- Operating System: Win11
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by Achuan-2** [comment]
原来以为是列表内的问题，发现这个在正文也有问题
![Snipaste_2022-10-22_23-00-11](https://user-images.githubusercontent.com/60436214/197346244-1e350e61-56de-4cd5-804b-4b5358496af1.png)

**Comment by Vanessa219** [comment]
快捷键有点多，统一在删除后移除图片选中状态
