### ISSUE TITLE
反链直接显示在文档底部

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6312]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

不需要打开反链面板就可以看到反链内容。

### 描述可能的最优解决方案 Describe the optimal solution

像 Obsidian 那样，提供一个开关，将反链直接显示在文档底部。

**Comment by 88250** [comment]
这个需要等待 #3862 完成后再考虑，谢谢。
