### ISSUE TITLE
导出 PDF API

### ISSUE THREAD

**Issue by Clouder0** [siyuan-note/siyuan#6313]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

最近需要批量导出一些文档为 PDF，方便打印。

### 描述可能的最优解决方案 Describe the optimal solution

封装一下[这附近](https://github.com/siyuan-note/siyuan/blob/7fbae2f7438a313837218e419468e0b189163c6a/app/src/util/onGetConfig.ts#L398)的代码。

### 描述候选的解决方案 Describe the candidate solution

Kernel 调不了 Electron API 的话，可以考虑和导出 docx 一样调 pandoc ?

**Comment by 88250** [comment]
这个依赖 Electron 的 API，由现有的内核 API 机制无法提供，估计要等 #5066 提供以后再考虑，谢谢。
