### ISSUE TITLE
Reviews/tutorials of siyuan online?

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#6314]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

This is actually a question. Sorry for posting this as a Feature Request, however I couldn't find a Discussion Forum for siyuan.

I recently learned about siyuan, however I can't find much information online about it! I was hoping to see blog posts and perhaps videos of people using and reviewing the app.

Is it possible I'm getting few results because most of the discussion around the app is in Chinese (I'm using Google in the US)? If so, what search engine would you recommend I use instead?

### 描述可能的最优解决方案 Describe the optimal solution

-

### 描述候选的解决方案 Describe the candidate solution

-

**Comment by 88250** [comment]
At present, most of the developers of SiYuan are Chinese, so most of the discussions about SiYuan use Chinese. Nonetheless, using English in the GitHub issues is welcome.

We have a plan that expands SiYuan user group worldwide, please watch it here https://github.com/siyuan-note/siyuan/issues/5331

Thanks.
