### ISSUE TITLE
请输入特性提议标题 Self-hosting the cloud sync server.

### ISSUE THREAD

**Issue by pluja** [siyuan-note/siyuan#6320]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

I would like to be fully in charge of my data (on my own server) while still being able to sync everything. Would this be possible if the sync server was available for self-hosting.

### 描述可能的最优解决方案 Describe the optimal solution

A docker-compose and or/local build to self-host the sync server.

**Comment by pluja** [comment]
PS: Just added SiYuan to my [awesome list](https://github.com/pluja/awesome-privacy)

**Comment by 88250** [comment]
Hello, at present we have no plan to support this feature, please refer to: 

* https://github.com/siyuan-note/siyuan/issues/6006
* https://github.com/siyuan-note/siyuan/issues/5990

Thank you.

**Comment by pluja** [comment]
If I understood correctly (I can't understand Chinese), although the sync server is open source there are no means to easily self-host and integrate it to the SiYuan apps. This is sad, as I would not hesitate to use SiYuan if I were able to self-host easily. I will stay with other Markdown based options for the time being as I can sync them using Syncthing... I will keep an eye close to the issue to see if it gets better in the future!

Thank you :)

**Comment by 88250** [comment]
@pluja We are migrating the official sync server code into the local kernel in v2.4.10 https://github.com/siyuan-note/siyuan/issues/6445
support other third-party object storage services (via Amazon S3 protocol) in v2.5.0 https://github.com/siyuan-note/siyuan/issues/6426 thanks.

**Comment by TomLucidor** [comment]
Judging from the online comments, the benefits of things like Obsidian (non-FOSS) or LogSeq (FOSS) is that there are ways to use Syncthing to do easy syncing, and that Git can be used for version control, @88250 does SiYuan support that?
