### ISSUE TITLE
新建文档的位置使用块引新建文档相同的位置或支持自定义

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#6322]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Ctrl+N新建文档位置不想在当前文档下，建议与**块引新建文档的位置**保持一致，或者支持自定义也可

### 描述可能的最优解决方案 Describe the optimal solution

![图片](https://user-images.githubusercontent.com/68107073/197385326-c8fcd1ca-908b-4b49-bd33-222b977dc7b2.png)

### 描述候选的解决方案 Describe the candidate solution

建议与**块引新建文档的位置**保持一致，或者支持自定义也可

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6222
