### ISSUE TITLE
能否基于fsrs间隔重复实现官方的闪卡学习？

### ISSUE THREAD

**Issue by jDsszzrDev** [siyuan-note/siyuan#6323]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

一切需要进行记忆而不是记录的内容。

### 描述可能的最优解决方案 Describe the optimal solution

关于算法，已经有一个开源算法https://github.com/open-spaced-repetition/free-spaced-repetition-scheduler，并有javascript和python实现，实现难度应该不大。

### 其他信息 Other information

记忆功能作为笔记我认为是一个较为重要的功能，官方的实现能够减少数据冲突的可能。尽管我知道类似提议已经提过多次，但是看到有现成的算法出现，于是旧事重提。

**Comment by 88250** [comment]
如果后续有时间会考虑，谢谢。
