### ISSUE TITLE
图表块的内容在数据库 `blocks` 表 `content` 字段中被转义

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6326]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

下面是一个 `Mermaid` 块内容
````markdown
```mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    loop Every minute
        John-->>Alice: Great!
    end
```
````

数据库中该块 `markdown` 字段内容
````markdown
```mermaid
sequenceDiagram
    Alice-&gt;&gt;John: Hello John, how are you?
    loop Every minute
        John--&gt;&gt;Alice: Great!
    end
```
````

`>` 字符被转义

### 期待的结果 Expected result

`Mermaid` 块的内容在数据库 `blocks` 表 `markdown` 字段中不被转义

### 版本环境 Version environment

```markdown
- Version: 2.4.5
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
应该是 `content` 字段不对吧？

![image](https://user-images.githubusercontent.com/873584/197429789-075d18cb-d388-44a3-bcf8-6454921351f9.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 应该是 `content` 字段不对吧？
> 
> ![image](https://user-images.githubusercontent.com/873584/197429789-075d18cb-d388-44a3-bcf8-6454921351f9.png)

看来我记错了👀
