### ISSUE TITLE
删除撤销状态异常

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6329]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![状态异常](https://user-images.githubusercontent.com/97731736/197461335-66786a1e-d904-4a69-9472-008ebe625b87.gif)
按了两次backspace，和一次撤销删除
虽然是v2.4.1版本，但是相信最新版可能也存在这个问题

### 期待的结果 Expected result

修复

### 截屏或者录屏演示 Screenshot or screen recording presentation

[测试文档.sy.zip](https://github.com/siyuan-note/siyuan/files/9849258/sy.zip)

### 版本环境 Version environment

```markdown
- Version: v2.4.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Soltus** [comment]
@UFDXD 
![image](https://user-images.githubusercontent.com/83791825/197475536-6de06d45-8069-4f52-90f7-c64156f3e86b.png)

建议先更新到2.4.5查看问题是否解决

**Comment by 88250** [comment]
请在最新版和默认主题下测试看看。
