### ISSUE TITLE
复制粘贴的引用描文本自适应行内样式

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6331]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

关于这个问题：https://github.com/siyuan-note/siyuan/issues/6291

在斜体行内文本中键入文字会自适应成斜体。
那么复制引用描文本粘贴到斜体行内文本就不能自适应斜体呢？
思源中获得引用最快捷的方式就是“快捷键”“复制该块为引用块”了吧。
有了复制就要粘贴。
此时要粘贴的引用描文本应该是不带任何字体样式的才对。
那么在斜体文本中粘贴自适应斜体样式也合乎逻辑。
不然在斜体行内文本中出现一个不自适应斜体样式的引用描文本，就需要手动打样式修改，过程需要操作光标选中文本，再按斜体快捷键或鼠标操作。
这增加了在斜体行内文本中使用引用描文本时间操作的成本。
并且不只是斜体样式其他样式中粘贴引用描文本也一样。
从人的思考逻辑上来将，既然需要将引用描文本粘贴到某个行内文本样式中自然潜在的希望粘贴的引用描文本样式和行内文本样式一致。
不然就是这样的结果（在上标样式中更能说明问题）
![image_312](https://user-images.githubusercontent.com/97731736/197491607-acfe86ef-9952-4ab3-b793-dd6576fbee68.png)

为了让上标中粘贴的引用描文本样式一致，更好看，需要二次调整。

### 描述可能的最优解决方案 Describe the optimal solution

复制粘贴的引用描文本自适应行内样式

**Comment by 88250** [comment]
目前从 Notion 等产品来看，使用的是原行级样式，应该是考虑到不破坏原有样式，这个不是技术问题，而是一个设计取向问题。

所以我们也就直接参考 Notion 等产品的设计进行实现了，这是相对保险的。现在不考虑改动了，等继续收集反馈再看，谢谢。
