### ISSUE TITLE
获取引用后直接在行内样式中引用描文本未自适应样式

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6334]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

继续 https://github.com/siyuan-note/siyuan/issues/6332 问题

看到问题关闭前回复。升级到最新版，并在默认主题，实际测试。
快捷键、块菜单鼠标获取直接粘贴并没有自适应行内样式。

### 期待的结果 Expected result

获取后直接粘贴到行内样式自适应

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/97731736/197530441-6db8e587-0d18-4389-a7f7-de276d2f13c3.mp4

### 版本环境 Version environment

```markdown
- Version: v2.4.5
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
老铁，之前的 issue 已经说了啊，引用粘贴不会自适应插入位置的，除非是纯文本。

请不要再重复提这个问题了，谢谢。
