### ISSUE TITLE
超级块起始删除撤销触发状态异常

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6335]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

继续 https://[github.com](https://github.com/siyuan-note/siyuan/issues/6329)/siyuan-note/siyuan/issues/6329
升级到最新版，默认主题实测，问题存在

### 期待的结果 Expected result

消除异常

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/97731736/197533790-3d86afcd-9022-48fa-b019-58c90d98ac3e.mp4

### 版本环境 Version environment

```markdown
- Version: v2.4.5
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by UFDXD** [comment]
另外，问题关太快了吧，我也不是要老提issues的

**Comment by 88250** [comment]
相同的问题请直接在原 issue 下回复，不用开新的，如果我们确认问题会 reopen 的，谢谢。
