### ISSUE TITLE
桌面端内核进程不再以游离模式拉起

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6336]
由 Electron 派生内核子进程时设置 `detached` 参数值为 `false`，并将纳入引用计数。

之前的版本就不再支持退出界面后内核驻留，所以内核无需游离，这样能更好地保证程序的完整性，同时也为后续支持内核随机端口多开做铺垫。

**Comment by iamqiz** [comment]
D大 我现在运行pnpm run start 不会启动内核,导致运行失败
我是通过把下面这行改动为 if (isDevEnv) { 来解决的
https://github.com/siyuan-note/siyuan/blob/8b3e3d2c9a7100163250f6e283eb336d9dd72d68/app/electron/main.js#L547

这种方式会有问题吗? 有没有更好的方法?

**Comment by 88250** [comment]
@iamqiz 开发环境需要手动先启动内核，加参数 `--mode=dev`

**Comment by iamqiz** [comment]
开发环境打开的gui不能通过X关闭按钮关闭, ???
