### ISSUE TITLE
复制代码到代码块问题

### ISSUE THREAD

**Issue by BLACKT-T** [siyuan-note/siyuan#634]
### 问题1：代码块右键复制纯文本粘贴不能实现问题？
描述：```创建代码块，复制内容进代码块使用快捷键Ctrl+Shift+V可以实现，但是右键粘贴为纯文本不能实现。
### 问题2：多个相邻代码块合并问题？
描述：```创建了多个相邻的代码块，想要将多个代码块进行合并，如何合并。

**Comment by 88250** [comment]
问题1稍后修复
问题2只能删了 ``` 重新编辑

**Comment by Vanessa219** [comment]
如果从 IDE 或者 vscode 中复制，不需要先创建代码块，直接粘贴即可。
问题一正在修复中
