### ISSUE TITLE
挂件名称汉化

### ISSUE THREAD

**Issue by TerickJojo** [siyuan-note/siyuan#6346]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

挂件数量多，不好分辨
![image](https://user-images.githubusercontent.com/24235319/197675650-408c3709-5796-472d-87fb-3c8927542e69.png)

### 描述可能的最优解决方案 Describe the optimal solution

显示中文名称

**Comment by 88250** [comment]
这个主要看开发者的命名。
