### ISSUE TITLE
界面支持 Dock 停靠栏

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#635]
- [x] toolbar 上打开的面板，在关闭时需要记住上一次的位置
- [x] toolbar 上打开的面板，在关闭时需要记住上一次的宽度
- [x] 加入名称 https://ld246.com/article/1611804441837

**Comment by roverway** [comment]
这个界面dock化不知道会是什么样子呢？是文件树、大纲、标签、搜索之类的面板都可以从侧栏收缩或展开吗？很期待这个特性。目前为了节省空间，快捷键开关页签的方式还是不太方便（比如树和大纲公用一个空间，但要按两次快捷键才能释放这一空间）。

另外，060文件树关闭后再打开，宽度没有恢复成上次的宽度。 @88250
