### ISSUE TITLE
关于虚拟引用的一种用法

### ISSUE THREAD

**Issue by shimu527** [siyuan-note/siyuan#6350]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

- 你好，请问是否可以引入一个数据库或excel表，以此作为虚拟引用的源。使用场景是各类词典可以直接使用，相当于做一个活词典。

- 其中这个数据表或excel可以被编辑，如果可以做到实时修改更好，做不到就手动更改完数据库，再重新打开siyuan重新检索一遍。适用场景是一些词典，如常见的英文词典，或者是我们自行定义的一些专业类的词典，我们在用它的时候，既需要它的专业释义，有需要加入自己的理解(此时需要编辑)。

- 现在的虚拟引用其实也可以做这样的事，但所有词条若方便导入导出，就必须以页面形式存在，那样会产生太多的页面，而且每个词条的解释本身就有专业释义，没必要在复制粘贴一次，最主要的是加入自己的理解，而这样统一的释义最后是以页面属性做定义并且列成表的形式，我不知道现在siyuan是否有能力做这样的事。但如果以一个外在数据表为源头，就可以很好解决这样的问题，并且有很多现成词典可用。

- 可以选择在虚拟引用时二选一，可以选择仍然是索引页面/块，也可以检索数据表

### 描述可能的最优解决方案 Describe the optimal solution

ios里的听阅app
chrome插件市场里的relingo插件

**Comment by shimu527** [comment]
还有一个功能请教，虚拟引用是否可以增加一个以sql语句进行排除关键词的方法（或者说已经可以实现，能告知方法吗）

**Comment by 88250** [comment]
* 可以考虑使用命名功能增加虚拟引用关键字
* 排除关键字在设置 - 编辑器里

感谢反馈。

**Comment by shimu527** [comment]
> * 可以考虑使用命名功能增加虚拟引用关键字
> * 排除关键字在设置 - 编辑器里
> 
> 感谢反馈。

还有一个可参考的就是tiddlywiki的一种叫tiddlymemo，他是将excel表(英文词典)作为源，转成json格式，然后通过插件下载到tiddywiki，实现类似于虚拟引用+词典的功能

**Comment by 88250** [comment]
可能要等思源出插件机制先……

**Comment by shimu527** [comment]
不好意思，描述有误。我的意思是它把excel转成json格式后的文件，放到了插件市场，可以从插件市场中下载下来。我想的不是一步到位有一个插件市场(尴尬)，我想的是可以生成这样的文件可以导入到siyuan中可以直接被检索到，又或者转成siyuan的格式后不与现有的文件树相交织，毕竟相交织的话文件数量太多了，当然如果有别的思路也好。
当然如果实现还是较为困难的话就当我没说。。。。

**Comment by 88250** [comment]
目前应该不会考虑直接实现这个需求，期待一下插件机制吧，谢谢。

**Comment by 88250** [comment]
@shimu527 这个提议可能有一些相似的地方 https://github.com/siyuan-note/siyuan/issues/6354

**Comment by Soltus** [comment]
> 不好意思，描述有误。我的意思是它把excel转成json格式后的文件，放到了插件市场，可以从插件市场中下载下来。我想的不是一步到位有一个插件市场(尴尬)，我想的是可以生成这样的文件可以导入到siyuan中可以直接被检索到，又或者转成siyuan的格式后不与现有的文件树相交织，毕竟相交织的话文件数量太多了，当然如果有别的思路也好。 当然如果实现还是较为困难的话就当我没说。。。。

我还等着Obsidian的 https://tadashi-aikawa.github.io/docs-obsidian-various-complements-plugin/ 插件在思源的类似实现呢，和你需求有相关性，等什么时候有插件吧
