### ISSUE TITLE
关系图全屏切换后点击最小化丢失顶栏标题

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#6351]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![222](https://user-images.githubusercontent.com/38906705/197715401-dfde92ce-1b71-4427-9cd8-c5887beeaeaf.gif)

### 期待的结果 Expected result

修复

### 版本环境 Version environment

```markdown
- Version: v2.4.5
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
我这里重现不了。

**Comment by 88250** [comment]
重置外观后似乎就无法重现了，先关闭了。
