### ISSUE TITLE
支持伺服代码片段 `/snippets/`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6356]
@88250 能不能将 `data/snippets` 目录也建立静态 Web 文件服务, 这样就可以在 `conf.json` 中通过 `@import url('/snippets/foo.css');` 与 `import('/snippets/bar.js');` 引用了, 不然想要同步的话只能另辟蹊径放在 `data/widgets` 或 `data/emojis` 目录了

_Originally posted by @Zuoqiu-Yingyi in https://github.com/siyuan-note/siyuan/issues/6143#issuecomment-1291459569_

**Comment by Zuoqiu-Yingyi** [comment]
@88250 我认为如果未在 `conf.json` 中匹配到请求的内容, 应返回对应的文件, 比如请求 `/snippets/test.js` 文件
- 如果 `conf.json` 存在 `"name": "test", "type": "js"` 的片段, 返回该片段 `content` 字段
- 如果 `conf.json` 没有匹配的片段, 则返回 `data/snippets/` 目录下的 `test.js` 文件
