### ISSUE TITLE
希望加入多块合并、单块拆分功能

### ISSUE THREAD

**Issue by CLaSLoVe** [siyuan-note/siyuan#6358]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

对于多个块，希望开发者大大能够实现一键合并为一个块。比如每个块为一行文本，多个块可以直接合并为一个块/段落。
对于一个块，希望能够实现一键按行（\n）拆分为多个块。

### 描述可能的最优解决方案 Describe the optimal solution

合并：当选中多个块时右键，点击合并，获取当前内容，写入一个块内，更新。
拆分：当选中一个块时右键，点击拆分，可以按行拆分。
现在有[Quicker](https://getquicker.net/Sharedaction?code=63dbc621-0be6-49ad-0fd6-08d9af1a5800)插件可以实现拆分，但是感觉不够优雅，而且比较麻烦。

**Comment by 88250** [comment]
这个功能使用场景比较特殊，暂时不考虑了，感谢提议。
