### ISSUE TITLE
docker版由2.4.5升级到2.4.6后，数据丢失，恢复2.4.5后正常

### ISSUE THREAD

**Issue by joezjy** [siyuan-note/siyuan#6371]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

docker版由2.4.5升级到2.4.6后，数据丢失，恢复2.4.5后正常。

丢失内容包含设置、文章内容等，就像一个新的环境。

### 期待的结果 Expected result

修复BUG

### 版本环境 Version environment

```markdown
- Version: 2.4.5 -> 2.4.6
- Operating System: Docker
- Browser (if used): Chrome & Firefox
```

### 日志文件 Log file

2.4.6没有更新siyuan.log文件

以下是2.4.5的log，启动正常
I 2022/10/27 08:00:26 process.go:46: received os signal [terminated], exit kernel process now
I 2022/10/27 08:00:26 conf.go:363: exiting kernel [force=false, execInstallPkg=1]
I 2022/10/27 08:00:26 database.go:1122: closed database
I 2022/10/27 08:00:26 conf.go:660: cleared workspace temp
I 2022/10/27 08:13:11 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/10/27 08:13:11 runtime.go:47: kernel is booting:
    * ver [2.4.5]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/, data 147 MB]
I 2022/10/27 08:13:11 serve.go:79: kernel is booting [http://0.0.0.0:6806]
I 2022/10/27 08:13:12 conf.go:578: database size [10 MB], tree/block count [74/2519]
I 2022/10/27 08:13:12 working.go:151: kernel booted

**Comment by 88250** [comment]
请参考这里 https://ld246.com/article/1666840904245
