### ISSUE TITLE
加粗

### ISSUE THREAD

**Issue by JJCSAMA** [siyuan-note/siyuan#6372]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

多选文字块时，加粗快捷键应该有反应

### 描述可能的最优解决方案 Describe the optimal solution

command + B，一键加粗选中不同的文字块

**Comment by 88250** [comment]
目前加粗只能对一个块中的行级元素生效，不支持跨块选择，后续有空的话会考虑支持，感谢提议。
