### ISSUE TITLE
暗黑模式下浏览 PDF 支持调整为原色

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6376]
https://ld246.com/article/1666881226484

**Comment by Vanessa219** [comment]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/970828/198836014-bac2f9e4-0390-462e-9f24-7bd907417977.png">

**Comment by tcmtom** [comment]
可以跟随思源主界面的变化而变化不

**Comment by 88250** [comment]
> 可以跟随思源主界面的变化而变化不

现在的版本就是变化的吧。
