### ISSUE TITLE
从 Word 中复制粘贴触发状态异常

### ISSUE THREAD

**Issue by lins-521** [siyuan-note/siyuan#6378]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

步骤1：从word中copy了一段有序列表到思源中
步骤2：由于不是我想要的有序列表格式，因此我讲这一段转为有序列表，但是每一行都增加了序号，并且出现了奇怪的".a."序号
步骤3：试图删除多余的.a. 和多余的序号，有些删除了，但是有些在删除序号的过程中，该行直接消失，并在该段下方出现了没有删除序号的该行（称为bug行），此时试图删除bug行时，会弹出状态异常，发现系统运行时的bug，问我是强制退出还是重建索引，重建索引后，该bug行永远存在（目前证实bug的是该行的有序列表的序列号，该序列号为3. ，）
步骤4：在该bug序列号后面重复粘贴word中的有序列表，并且在思源中修改为有序列表，会立即弹出状态异常

### 期待的结果 Expected result

bug序号3. 不能删除，在他之后的有序列表也不能存在；希望删除它

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="403" alt="bug3" src="https://user-images.githubusercontent.com/53263061/198332296-822756f2-34ef-4fa5-b317-ca9581e6a548.png">
<img width="558" alt="bug1" src="https://user-images.githubusercontent.com/53263061/198332303-b8aadfe3-481e-4e83-b5cd-8d70038c81fc.png">
<img width="461" alt="bug2" src="https://user-images.githubusercontent.com/53263061/198332312-d913d52e-983d-42a7-b30c-9cd2a156378d.png">

### 版本环境 Version environment

```markdown
- Version: V2.4.5 V2.4.6
- Operating System: win11 22H2
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9880785/siyuan.log)

**Comment by 88250** [comment]
请上传一下 Word 文件。

**Comment by lins-521** [comment]
第2页第11行文件操作之后
[Gvim学习简易手册.docx](https://github.com/siyuan-note/siyuan/files/9880848/Gvim.docx)

**Comment by 88250** [comment]
我这里重现不了问题，请看我的重现步骤是否正确：

![issue](https://user-images.githubusercontent.com/873584/198495634-3d681b80-8734-4100-a341-f4513dcdca48.gif)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by lins-521** [comment]
感谢您的回复，我目前在2.4.7版本没有复现这个问题，感谢


| |
孙林
|
|
***@***.***
|
在2022年10月28日 ***@***.***> 写道：

我这里重现不了问题，请看我的重现步骤是否正确：

我先关闭了，如果还有问题请继续跟帖，谢谢 🙏
