### ISSUE TITLE
配置代理后内核自动退出

### ISSUE THREAD

**Issue by leolee9086** [siyuan-note/siyuan#6379]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

2.4.7版本启动后界面和核心失去连接，核心自动退出

我这里在将设置=》关于=》网络代理设置为直接连接之后能够解决问题，但qq群有用户反馈没有设置代理核心同样自动退出。

### 期待的结果 Expected result

核心正常启动，并兼容之前的网络代理设置

### 截屏或者录屏演示 Screenshot or screen recording presentation

![EQ@R}RT6B%7%12092HL9LNL](https://user-images.githubusercontent.com/19915077/198350737-b8f24442-ea91-4248-a7e5-915264d3d157.png)

### 版本环境 Version environment

```markdown
- Version: 2.4.7
- Operating System: windows 11 2022H2 
- Browser (if used):siyuan app
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9881527/siyuan.log)

**Comment by 88250** [comment]
需要将代理软件设置为排除 `siyuan.localhost` 代理。

**Comment by woniuxia** [comment]
@88250 D大，这个问题要不紧急修复下？感觉影响还挺大的

**Comment by 88250** [comment]
@woniuxia 这个应该只能调整代理软件的设置解决。
