### ISSUE TITLE
2.4.7 内核中断

### ISSUE THREAD

**Issue by tswwe** [siyuan-note/siyuan#6383]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

问题复现方法：
1. 安装思源 2.4.7。
2. 在软件的设置 → 关于 → 网络代理中，将“直接连接”修改为“SOCKS5”，并填上合适的 ip 和端口号（如 127.0.0.1:8888），确定。
3. 重启思源。

### 期待的结果 Expected result

正常启动，而不是卡在内核中断界面。

### 版本环境 Version environment

```markdown
- Version: 2.4.7
- Operating System: Win10
```

### 日志文件 Log file

暂不提供

**Comment by tswwe** [comment]
临时解决方案：
方案1：直接退回 2.4.6 版本。
方案2：如果坚持要用 2.4.7，可以修改 `conf.json`，把其中 `networkProxy` 表下 `scheme` 的值改成 `""` 后重启思源。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6379
