### ISSUE TITLE
思源导出html(思源)，chrome系浏览器无法正确加载资源

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#6384]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

导出html打开，项目列表样式等都无正确显示，查看console的报错，发现是使用了files://协议导致的

### 期待的结果 Expected result

导出路径采用相对引用？或者其他方法正确加载资源

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/19968935/198452552-9e30497d-5025-448d-8e98-25f4e632fc9e.png)

![image](https://user-images.githubusercontent.com/19968935/198448619-fd33baa9-9a60-4156-8ec8-6bf377386f1f.png)

### 版本环境 Version environment

```markdown
- Version: 2.4.6
- Operating System: win
- Browser (if used): Edge
```

### 日志文件 Log file

not applicable

**Comment by 88250** [comment]
我这里默认主题测试正常：

![image](https://user-images.githubusercontent.com/873584/198495196-f78400ef-5e33-4106-9def-79ea7c40f00e.png)


你那里可能是没有给浏览器读取本地文件的权限吧。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
