### ISSUE TITLE
Windows 端不再支持 32 位系统

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6386]

**Comment by aptexd** [comment]
对于取消32位系统支持，我没什么任何意见，只是好奇原因
按照粗浅的理解，应该是多个少个编译的包吧
还是32位的会耗费更多的精力

**Comment by 88250** [comment]
@aptexd 会的，比如 Pandoc 已经没有 32 位版本了，有的问题无法跟进。
