### ISSUE TITLE
在快速切换搜索结果时容易卡顿或延后渲染

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#639]
### 描述问题 Describe the problem

在快速切换搜索结果时容易卡顿或延后渲染

### 期待的结果 Expected result

不卡顿或延后渲染

### 截屏或录像 Screenshot or video

![快速切换搜索结果](https://user-images.githubusercontent.com/28727933/101117102-471f8200-3621-11eb-9071-2c2b6da45fae.gif)

### 其他信息 Other information

建议在快速切换时不要立即渲染或者说加入渲染队列，而是等待一小段时间之后确定了用户选中

项才开始渲染

**Comment by 88250** [comment]
v0.5.45 发布后请试下该问题是否得到改善，谢谢。

**Comment by 2234839** [comment]
可以了
