### ISSUE TITLE
调整 Windows 安装程序打包选项

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6390]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

REF: [Windows 端不再支持安装时选择安装路径和用户 · Issue #6385 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/6385)
REF: [[投票] 关于 Windows 端不再支持安装 / 更新时自定义安装路径和用户 - 链滴](https://ld246.com/article/1666938144530#comments)

### 描述可能的最优解决方案 Describe the optimal solution

- 直接安装(双击运行安装程序)
  - 初次安装
    - 用户可选为当前用户安装/为所有用户安装(需要管理员权限)
    - 用户无法自定义安装目录
      - 为当前用户安装默认安装目录为 `C:\Users\<用户名>\AppData\Local\Programs\SiYuan`
      - 为所有用户安装默认安装目录为 `C:\Program Files\SiYuan`
  - 覆盖安装(更新)
    - 用户可选为当前用户安装/为所有用户安装(需要管理员权限)
    - 用户无法自定义安装目录
      - 默认安装目录为原安装目录
- 带参数安装(使用命令行带参运行安装程序)
  - 带参数 `/D` 自定义安装目录(初次安装/覆盖安装均适用)
    - 示例: 将安装包 `siyuan-2.4.8-win.exe` 安装至 `D:\Program Files\SiYuan` 目录
      - `./siyuan-2.4.8-win /D=D:\Program Files\SiYuan`

**Comment by 88250** [comment]
已经合并，并更新了 https://github.com/siyuan-note/siyuan/issues/6385 的说明，感谢贡献。

**Comment by woniuxia** [comment]
@Zuoqiu-Yingyi 大佬，确认一下，如果是自定义的目录，就需要每次安装的时候都指定目录是吧？

**Comment by Zuoqiu-Yingyi** [comment]
> @Zuoqiu-Yingyi 大佬，确认一下，如果是自定义的目录，就需要每次安装的时候都指定目录是吧？

> - 覆盖安装(更新)
>   - 默认安装目录为原安装目录

**Comment by winter60** [comment]
> 带参数 /D 自定义安装目录(初次安装/覆盖安装均适用)
示例: 将安装包 siyuan-2.4.8-win.exe 安装至 D:\Program Files\SiYuan 目录
./siyuan-2.4.8-win /D=D:\Program Files\SiYuan

@Zuoqiu-Yingyi 萌萌大佬，这行命令路径不加引号的结果，直接给装D:\Program 里面了

![image](https://user-images.githubusercontent.com/23653326/206689211-7953ef81-9d96-45b8-93e0-aa81339e6f27.png)

个人记录，已提醒后人。

**Comment by Zuoqiu-Yingyi** [comment]
> 个人记录，已提醒后人。

我编辑一下😂
