### ISSUE TITLE
代码块语言不支持设置vue、react，建议可由用户创建非列表中的语言种类

### ISSUE THREAD

**Issue by yxl0520** [siyuan-note/siyuan#6394]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

作为前端程序员，经常会添加React、Vue组件模板代码。目前思源不支持在代码块设置语言种类的时候，选择或设置vue、React语法种类。只限于选择现有列表的代码语言种类。当然，也不支持相应的语法高亮。
![image](https://user-images.githubusercontent.com/19848190/198721164-7b3f8a3f-3690-4f59-941a-83f787f1072e.png)

typora中支持vue、vue语言的设置，或者支持添加其他自定义的语言语法。望大大这边可以考虑添加vue和React模板语法高亮支撑

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/19848190/198719097-65edf3be-117e-46ad-80c2-a226eeac9c80.png)

**Comment by 88250** [comment]
这个主要受限于 [highlightjs](https://highlightjs.org/) 提供的能力，欢迎给该项目提交 feature request 谢谢。
