### ISSUE TITLE
支持插入 `.im` 和 `.build` 域名超链接

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#6399]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

https://rime.im
https://www.electron.build/

### 期待的结果 Expected result

1

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

sd

**Comment by iamqiz** [comment]
话说能不能设置里加个选项,允许用户自行添加支持的域名?

**Comment by 88250** [comment]
少哪些补哪些吧，什么都加选项不合适哦。

**Comment by iamqiz** [comment]
补需要时间呀, 自己加可以立马解决问题, 
这个选项可以不显示在设置页面里, 而是允许用户通过conf.json自行添加, 如何?

**Comment by 88250** [comment]
这个要改解析器，目前没时间改哦。

**Comment by iamqiz** [comment]
.sh域名不支持 
https://scoop.sh/

**Comment by iamqiz** [comment]
.ms 域名不支持
https://aka.ms

**Comment by iamqiz** [comment]
这个网站列举了很多不同域名的谷歌网站: 
世界各国谷歌（Google）网址大全_百科大全_嘻嘻网
http://m.news.xixik.com/content/25df0c00ac300bdc/

我试了, 很多都能访问, 但是思源不支持其超链接, 比如下面几个, 还有一大堆我没试 

https://www.google.mn/
https://www.google.co.kr/
https://www.google.co.jp/
https://www.google.com.vn/
https://www.google.com.kh/
https://www.google.com.np/
https://www.google.com.pk/

**Comment by iamqiz** [comment]
今天又遇到个moe域名没有被思源支持,
于是查了一番资料, 从域名管理组织ICANN官网发现了顶级域名大全
- 注册管理机构资源 - ICANN
https://www.icann.org/resources/pages/registry-resources-2017-12-12-zh

  - [顶级域列表](https://www.icann.org/resources/pages/tlds-2012-02-25-en) – 该列表中包含由 [IANA](http://www.iana.org/) 维护的所有有效顶级域。
  - [新通用顶级域注册管理运行机构 CSV 报告](https://www.icann.org/resources/registries/gtlds/v1/newgtlds.csv) [CSV, 29.3 KB] – 新通用顶级域注册管理运行机构 CSV 报告是一份可下载的逗号分隔值 (csv) 文件，其中列出了与 ICANN 组织签署合同的所有新通用顶级域，另外在适用情况下，还会列出相应的注册管理运行机构、合同执行日期、申请 ID 和新通用顶级域授权日期。

其中,第二个csv里中文域名位于以xn--开头的域名部分,列名为u-label, 比如
```
"xn--5su34j936bgsg","香格里拉","Shangri‐La International Hotel Management Limited","2015-09-03","1-940-19689","2016-07-02"
"xn--5tzm5g","网站","Global Website TLD Asia Limited","2014-12-22","1-2101-67873","2016-04-17"
"xn--6frz82g","移动","Identity Digital Limited","2013-09-23","1-868-82489","2014-02-05"
```

**Comment by 88250** [comment]
暂时没有时间改了，以后等慢慢补全吧。

**Comment by iamqiz** [comment]
能不能在协议是http或https时不考虑域名?  
要么出个一劳永逸的办法,支持用户自定义?

**Comment by iamqiz** [comment]
不然这个issue永远解决不了

**Comment by Soltus** [comment]
这些域名都是什么网站啊，我都没接触过

**Comment by iamqiz** [comment]
> 这些域名都是什么网站啊，我都没接触过

新通用顶级域名_百度百科
https://baike.baidu.com/item/%E6%96%B0%E9%80%9A%E7%94%A8%E9%A1%B6%E7%BA%A7%E5%9F%9F%E5%90%8D/5565721?fromModule=lemma_inlink&fromtitle=%E6%96%B0%E9%A1%B6%E7%BA%A7%E5%9F%9F%E5%90%8D&fromid=4002570

**Comment by 88250** [comment]
@iamqiz 有空的话请帮忙 PR：

* https://github.com/88250/lute/blob/master/parse/auto_link.go 这个文件的末尾有个 map，直接添加就可以
* https://github.com/88250/lute/blob/master/test/autolink_test.go 这是对应的测试用例

**Comment by iamqiz** [comment]
@88250 
添加大量顶级域名 by iamqiz · Pull Request #188 · 88250/lute
https://github.com/88250/lute/pull/188
