### ISSUE TITLE
钉住页签

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#640]
![image](https://user-images.githubusercontent.com/970828/148488094-2cd537bb-1998-4c31-b7d1-77417a380f7b.png)

**Comment by lss6378** [comment]
平时隐藏，鼠标放上去显示
![图片](https://user-images.githubusercontent.com/15924513/104336269-2f47f180-552f-11eb-8c4b-2583e1c34276.png)

**Comment by aptexd** [comment]
![image](https://user-images.githubusercontent.com/15101966/148894176-4c11e5d0-dcd8-4279-82f3-b6d028a2733c.png)
所以这到底是什么网站这么重要🤪

**Comment by 88250** [comment]
> ![image](https://user-images.githubusercontent.com/15101966/148894176-4c11e5d0-dcd8-4279-82f3-b6d028a2733c.png) 所以这到底是什么网站这么重要🤪

https://gitmoji.dev/

**Comment by aobatu** [comment]
钉住的页签，是否可以不让其他页签替换？
现在的现状是，如果钉住的标签没有发生编辑，且打开“当前页签中打开”的开关，那么新打开一个页面后，就替换钉住的页签，这样钉的这个页签就没有什么意义了。
所以期望是：如果标签被钉住，无论是否发生过编辑，都不能被替代。 @Vanessa219
