### ISSUE TITLE
可设置为右键打开浮动工具栏

### ISSUE THREAD

**Issue by ippreacher** [siyuan-note/siyuan#6408]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前为选择文字时出现浮动工具栏，会导致多选不同文字时误点浮动工具栏的按钮。

### 描述可能的最优解决方案 Describe the optimal solution

设置中增加：[ x ] 选择文字时出现浮动工具栏；[ x ] 选择文字后右键出现浮动工具栏。
类似于word和WPS中的选项：
![_20221030144646](https://user-images.githubusercontent.com/53852556/198866130-98e080f1-73ec-4cec-838e-7bc10c0ef976.png)

**Comment by 88250** [comment]
不考虑了，感谢提议。
