### ISSUE TITLE
工作空间不存在 `data/snippets/` 目录时设置代码片段抛出异常

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6409]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

工作空间不存在 `data/snippets/` 目录时, 设置>外观>代码片段 设置后点击确认按钮时弹出如下错误提示
![image](https://user-images.githubusercontent.com/49649786/198866287-f42da367-4905-46c6-ba97-fa50bf816f09.png)

### 期待的结果 Expected result

若工作空间不存在 `data/snippets/` 目录与 `data/snippets/conf.json` 文件时, 则新建

### 版本环境 Version environment

```markdown
- Version: 2.4.7
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6382
