### ISSUE TITLE
图床工具支持

### ISSUE THREAD

**Issue by BB-fat** [siyuan-note/siyuan#641]
目前在文章中插入图片siyuan可以将其整理到assert目录下，但是如果想在博客上发布写好的文章，图片就需要放到公开图床上，手动迁移非常麻烦。

----

希望能想Typora那样支持图床工具，例如picgo。在向文章中插入图片的时候自动上传图床。
或者支持在导出md的时候进行图片迁移。

----

siyuan是一个不错的项目，有很多亮眼的功能，期待能越做越好。
感谢你们付出的努力！

**Comment by 88250** [comment]
之前有用户提过 https://github.com/siyuan-note/siyuan/issues/118 

我们在考虑一下，这个要支持估计要过一久了，谢谢。

**Comment by ishield** [comment]
siyuan直接保存图片到本地也挺不错的，typora是直接上传图片到图床，万一图床出问题无法访问，图片就有可能大批丢失。

意见：
希望siyuan后期增加上传到图床到功能时，可以同时保留本地的图片。图床+本地，这样的方案更加保险一点。支持你们！

**Comment by 88250** [comment]
我理解使用图床的主要目的是用于互联网发布，这个可能的确需要一个工具来支持将本地图片一键上传到指定图床，并且导出/预览 Markdown 时使用图床链接。这样通过导出/预览就能将带图床的内容输出到其他互联网平台了。

对于数据可用性来说，本地+网盘同步+定期其他设备备份应该就比较稳了。

**Comment by 88250** [comment]
先不考虑了，如有类似需求请直接使用 PicGo 的界面程序，谢谢。

**Comment by iamqiz** [comment]
@88250  为啥不考虑呢? 使用图床能节省不小的同步空间呢  而且可靠性也不低, 腾讯云的存储如下:
![Snipaste_环境返回_2023-05-03__11-30-31](https://user-images.githubusercontent.com/48077521/235827682-65c235ae-e143-4f5f-b251-bcc3dce0a246.png)

**Comment by 88250** [comment]
图床管理功能开发工作量有点大，目前无法考虑，建议直接用其他工具。

**Comment by iamqiz** [comment]
@88250 思源只需要调用picgo的API就可以了,图床的配置什么的是在picGo软件里进行管理的

**Comment by 88250** [comment]
抱歉了，我现在实在没有时间研究，只能看看其他开发者有没有空了。

**Comment by iamqiz** [comment]
好吧 我抽空研究研究
