### ISSUE TITLE
日记设置在思源重启后失效

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6410]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

最近只要关闭思源，重新打开
按alt+5就会跳出日记选择界面
选择以后再重新，按alt+5再跳出日记选择界面，如此反复。

### 期待的结果 Expected result

恢复正常

### 截屏或者录屏演示 Screenshot or screen recording presentation

![QQ截图20221030164343](https://user-images.githubusercontent.com/37429029/198870225-073db90b-9074-4960-8cdb-55710ccdfafa.png)

### 版本环境 Version environment

```markdown
- Version: 2.4.7
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9895459/siyuan.log)

**Comment by 88250** [comment]
会在 https://github.com/siyuan-note/siyuan/issues/6381 中解决。

**Comment by yuyuyu-github** [comment]
好的(●'◡'●)
