### ISSUE TITLE
内核因未知原因退出

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6411]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

更新2.4.7后首次遇到，昨天正常使用中，思源突然bai'pin白屏，报错。重启思源不管用，最后只能重启电脑解决。

### 期待的结果 Expected result

想知道出现这个错误的原因

### 截屏或者录屏演示 Screenshot or screen recording presentation

![IMG_20221029_111450](https://user-images.githubusercontent.com/37429029/198870315-889d6331-7196-478b-b5c3-b4a57cbef37d.jpg)

### 版本环境 Version environment

```markdown
- Version: 2.4.7
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9895467/siyuan.log)

**Comment by 88250** [comment]
目前从日志中无法确定问题，请等下个版本发布后再观察，我先关闭了，谢谢。

**Comment by yuyuyu-github** [comment]
明白(●ˇ∀ˇ●)
