### ISSUE TITLE
支持分别设置中英文默认字体。

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6412]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

日常记笔记中，希望英文和中文使用两种字体。
比如中文默认字体设置为微软雅黑
英文设置为Futura。
现在中英文都是默认用一个字体，想区分的话只能自己该css，希望可以提供这个设置，挺常用的。

### 描述可能的最优解决方案 Describe the optimal solution

中英文区别设置默认字体

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5918

**Comment by yuyuyu-github** [comment]
收到O(∩_∩)O
