### ISSUE TITLE
加入滚屏显示功能

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6413]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

滚屏显示已经在dark+主题被应用了很长一段时间，这个功能是某些场景不可替代的解决方案，希望可以把这个功能加入到系统功能中。

比如当有一个较长模板表格/列表，放在dailynote里面的时候。 
如果没有滚屏显示，每次都要下拉一长段才能看到当天daily notes的其他内容。 
但是有滚屏显示的话，表格就只会占据一个固定的空间。
![image](https://user-images.githubusercontent.com/37429029/198870889-0dc35798-47c9-4409-96b4-eecc78b8682c.png)
![image](https://user-images.githubusercontent.com/37429029/198870915-4586c7e5-b5f3-40e1-9f2f-9cb15ce79d59.png)

### 描述可能的最优解决方案 Describe the optimal solution

加入滚屏显示功能。

**Comment by Zuoqiu-Yingyi** [comment]
这里是可参考的实现方案: [custom-render-scroll.less](https://github.com/Zuoqiu-Yingyi/siyuan-theme-dark-plus/blob/main/style/module/custom-render-scroll.less)

**Comment by 88250** [comment]
暂时没有太多需求，先关闭了，谢谢。
