### ISSUE TITLE
编辑器动态加载块数由定值改为可配置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6415]
之前的定值是 `36`，改为可配置范围 `[128, 1024]`

**Comment by Zuoqiu-Yingyi** [comment]
最好下限可以设置低一些(感觉 32 或 16 比较好), 因为有些行内元素非常多的文档(比如数学笔记中有大量行内公式), 块数多了后渲染起来很慢

**Comment by Zuoqiu-Yingyi** [comment]
可以使用该文件测试一下: [mo-vic/Calculus: Chapter11.md](https://github.com/mo-vic/Calculus/blob/master/Chapter11.md)

**Comment by 88250** [comment]
调整为 `[36, 1024]` 吧。

**Comment by Zuoqiu-Yingyi** [comment]
> 调整为 `[48, 1024]` 吧。

`1024 / 48 = 21.333333`, 不能整除, 难受, 还是 32 顺眼👀

**Comment by 88250** [comment]
这个影响不大，它们之间没有倍数关系。

**Comment by Chenm4** [comment]
我也感觉可以调低一点，默认可以为48但是最好可以给一个低一点的选项。其实主要是在意打开文档的瞬间的响应速度的，其他时候的动态加载都还好，我现在如果是把这个数值调高那么会在打开的时候慢很多，是否可以在打开的时候先加载几十个先显示出来画面而非转圈圈，转圈圈给人的感觉总是很糟糕。先显示出来几个然后再动态加载剩余块。
