### ISSUE TITLE
听说思源笔记会通过用户电脑挖矿

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6416]
原谅我标题党一下 😂 

详情请看 https://www.zhihu.com/question/434530733/answer/2644563326

---

这确实是个常见问题，帮助文档中加入该条 FAQ。

**Comment by leolee9086** [comment]
皮这一下挺好玩奥……   看到邮件吓我一跳

**Comment by aptexd** [comment]
我认为之前的挖矿不算什么大问题
首先是开源项目不代表是免费项目
而且也当时已经提前说明的

**Comment by SineMark2020** [comment]
都开源了还有人说这，会信的人就会信，不信说再多也没用
