### ISSUE TITLE
导出 PDF 表格布局未居中

### ISSUE THREAD

**Issue by lim-0** [siyuan-note/siyuan#6418]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

版本：2.4.5

bug：使用思源笔记写完文档，导出pdf出现格式异常，笔记内将表格的布局调整为居中，但导出为PDF时，表格仍未居中显示

### 期待的结果 Expected result

写的笔记格式与导出格式一致

### 截屏或者录屏演示 Screenshot or screen recording presentation
笔记：
![image](https://user-images.githubusercontent.com/35923416/198923721-956ba55e-040e-4186-9723-0dc31b3c1818.png)

导出时：
![image](https://user-images.githubusercontent.com/35923416/198923756-333f7af7-093c-405f-bccd-a69d8864f217.png)

### 版本环境 Version environment

```markdown
- Version: 2.4.5
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
如果局中的话，表格过长，表头就不会重复。https://github.com/siyuan-note/siyuan/issues/3374

**Comment by lim-0** [comment]
> 如果局中的话，表格过长，表头就不会重复。#3374

啥意思？，和表头并没有重复的情况，只是导出的时候，不会居中

**Comment by Vanessa219** [comment]
意思就是表格居中的话，如果表格分页了，那么表头就会有问题。为了不让分页的表格出现问题，我们就没有支持居中了。

**Comment by lim-0** [comment]
> 意思就是表格居中的话，如果表格分页了，那么表头就会有问题。为了不让分页的表格出现问题，我们就没有支持居中了。

好的，了解了，谢谢
