### ISSUE TITLE
思源笔记体验录

### ISSUE THREAD

**Issue by wrwe3888** [siyuan-note/siyuan#642]
## 0 总说思源

笔记软件我用过不少了，为知、有道、印象、幕布、dynalist、typora、RoamResearch、RoamEdit、Obsidian、hulu、loseq、RoamOutline，乃至于 WPS、xmind、theBrain 等。今天说说思源。

我在思源 2.8 的时候用过一两天，感觉效果不太好，感觉还不如用 obsidian。这几天（20201202）再次用思源，发现功能上有很大改观，十分惊艳。不出意外的话，初步决定明年 8 月 RR 到期以后，把上面的上万条笔记都迁到思源上来（大工程）。

从用户角度来说，我觉得一款笔记软件最吸引人的，肯定是高效的知识组织方式，所有功能都应该围绕它来。高效组织的方式，最常见的是：互链、搜索、标签、关系图等。互链、关系图是当下最火的。不过大家居然都忘记了还有：搜索、标签。

## 1 搜索功能

无论怎么说，搜索绝对是知识组织最重要的方式之一。前几年传统笔记软件大战中，印象笔记突出重围的重要法宝之一，是多关键词搜索秒出结果，而那个时候，为知、有道云搜单关键词都卡半天。

我理想中的思源搜索有如下功能：

#### 1.1 多关键词 and or not 搜索

到目前为止，notion 还不支持多关键词搜索，这是让我抛弃它的唯一原因。就这个问题，我曾经给 notion 写过邮件，后来 notion 回复说近期（20200715）不打算升级搜索，让我从此告别 notion。

搜索功能强大，会给人很强的知识掌控感。而与或非搜索，肯定是基础之基础。目前（20201204）思源只能 or 不能 and，功能需要改进。而且思源把空格作为 or 关系，不太合乎一般把空格当作 and 的认知习惯。

#### 1.2 指定搜索范围

思源打动我的，是它的内容块、超级块的概念。这是非常好的搜索基础，一个内容块就可以作为一个搜索范围。比如，指定在列表块中搜索「苹果 and 手机 not 电脑」。类似的，也可以在文档块里搜，在列表块里搜，在引用块里搜，把 1 级标题下的全部内容作为一个超级块来搜……这样用户会对使用这些内容块有规划。比如，我就决定以后在引用块里只写自己的想法。以后在引用块里一搜，就知道以前某个时候是什么想法。而以前的笔记，比如 RR 之类的，总是把原文和自己的想法写在一起，非常不易区分，要打标签，又十分繁琐。

目前所有笔记软件的搜索都是基于节点。这就导致，如果我的某个文章的不同段落中有「苹果」和「手机」两个词，就不会被用 and 关系组合搜索出来。而思源笔记的超级块概念为解决这一问题，提供了很好的基础。这甚至可以打造成思源的一个亮点

#### 1.3 在 md 符号里搜

RE 对标 RR，虽然很不稳定，但功能还是很强大的。其中有个功能，比如，可以在所有标有指定颜色的文字里搜，在指定背景颜色里搜。近而，可以在所有删除符号里搜，可以搜所有标题文字。这就更近一步让用户对自己的笔记有了掌控感：只要做好了前期准备，我的知识随时可提取出来。

思源目前已经有了一些很好的基础，比如，可以在代码块里搜、在引用块里搜。很快思源会有文字颜色功能了，我相信这些搜索功能，真要做，对思源来说，不会特别难。

#### 1.4 高阶搜索

目前的高阶搜索似乎是通过select语句来的，我这几天正好学了mysql，马虎能看懂，不过这样是不是太麻烦？能否直接在界面上实现，或者简单的几个语句就实现？

这方面我觉得可以看一下dynalist 的搜索功能。

#### 2.1 标签分类

印象的另一法宝是标签。标签功能改变了早前的文件夹思维，让一个文件可以从属于多个类别。虽然标签也有缺点，比如维护管理麻烦。但其分类功能是不可替代的。wolai 的马总很讨厌标签，不知为何。

目前思源有标签功能，但总感觉标签层级的设置有点奇怪，它的标签类似这样#文学/中国文学/唐代文学 唐诗#，这样的话，一个标签如果有几个层级，打一个标签需要输入好几个层级，这太麻烦太麻烦。实际操作中，我估计不会有几个人用。

我觉得可以借鉴印象笔记的标签体系：比如，文学 中国文学 唐代文学 唐诗，印象笔记可以把这 4 个标签拖拽成 4 个层级，又可以独立作为一个标签。比如一篇欧洲文学的文章，我会把它标成「文学」，因为我的文章基本都是唐代文学，欧洲文学的没有细类，所以标「文学」就行了。这种标签方式比较灵活。

但印象有一点不足，比如新增一篇关于李白文章，我会马上想到标成「唐诗」，但如果我同时也把它们标唐代文学、中国文学、文学，那标签工作就太麻烦了。如果不标，到时候想搜「文学」主题的时候，又搜不到这篇文章，因为我没有给他标「文学」标签啊。

那能不能这样：所有「唐诗」标签的文章，都自动加上它的父级、祖先级标签？当然，也可以把自动加的标签和自己主动加的标签区分开，比如搜索「文学」标签的时候，可以给个选项：是在所有自己打的「文学」标签里搜？还是搜索的范围同时也包括机器自动打「文学」标签？

#### 2.2 多标签搜索

印象笔记的多标签搜索很棒，同时选中几个标签，则同时标有这几个标签的文章就出来了。这一功能，后来被 dynalist 发挥到极致。dynalist 左侧有个标签列表，可以显示每个标签的节点数量，点击 1 个或多个标签，就可以在右侧显示同时标有这些标签的节点。注意是点击哦，不是手动输入搜索内容，这丝滑度，感觉真是太爽。这一点三四年了，至今没有其它软件能达到，包括她们自己的 obsidian。不过 ob 应该尽早会有的。很多人赞赏的 notion 连标签都没有、多关键词都不能，简单还活在太古时代。

不过 dynalist 不足的地方是，它的标签列表没有层级，所有标签都在标签列表中，一溜的列下来。如果能像印象笔记那样加个层级，就更牛了。

#### 2.3 不同内容块的标签

一般标签被认为是打给节点的，也就是思源中的段落。既然列表也是块、超级也是块、文档也是块，为何不给它们也打标签呢？我是指给整个块打标签，比如整个文档而非某个段落。

以上功能，如果能达到，把这些功能组合起来搜索，功能就会强大无比了，想突破笔记重围，是分分钟的事。

#### 3.1 正向链接

3.1.1 目前的流行笔记，正向链接都用 [[ ，思源用(( ，这当然无不可。但顺手度不太好，毕竟 (( 需要用到 shift，比较麻烦。

3.1.2 RR 选中一段文字，alt+[ 即可使之成为一篇文章，如果这段文字作为标题已有文章，就链接到旧文章，没有文章，就创建新文章。思源没有这个功能。

3.1.3 可能是开发者遇到了与多关键词搜索一样的难题，输入(( 以后，无法通过搜索多关键词，来更细致的定位目标内容块。这让思源的互链功能有所削弱。

3.1.4 正向链接的预览功能很棒，能否给个功能设置一下预览窗口的颜色，这样方便区分主文档与预览文档。有时候叠到一起了，有点乱。当然，这是很小的问题。

3.1.5 想打开正向链接的文档，要点右侧的下或右，这不太方便。能否直接点击互链就能打开？这个问题说大不大，说小不小，说小，毕竟它只是个是否丝滑的问题。说大，又因为这个问题处在互链这个核心功能的当口上。一点点不够丝滑，就会让人体验不好，因为有明确的比较对象，这方面是明显的比较点啊。人大多数时候都是非理性、体验型的动物。

这一点上，wolai 的马总把握的相当好，就中英文自动隔开一个小距离，这么个小功能，就被拿出来当核心功能宣传。这个功能解决了一个小痛点，给人爽的体验，以此让人对整个软件都有了好感。然后人就忘记了这个功能其实没那么重要。这就类似餐厅3元送麻婆豆腐一样。代价很低，但因为宣传的好，博得了好感，引流不少。

#### 3.2 反向链接

3.2.1 思源的反向链接和 obsidian 一样，要点击才能出现，而不是像 RR 或 wolai 那样放到文尾。这当然也可以。但反向链接的内容展示比较乱。能否这样：假如 b 文档中有 10 处引用了 a 文档，查看 a 文档的反向链接时，这「链接」的 10 处能否放置于 b 文档的标题下？目前是 10 处都单独散开，每处是完整的路径名。这样看起来比较杂乱。同理，如果一个标题下的内容多次引用某处，也最好把它们归到一处。简言之，反向链接的内容展示，最好按原有内容层次组织起来，而不是一个一个的按顺序排下去。

3.2.2 反向链接内容如果过多，可否选择折叠部分内容？

3.2.3 同样可能是由于搜索功能有限，反向链接中的「提及」会出现很多冗余的内容，且其中的关键词用亮黄标出来，十分眨眼。这是没有必要的，因为，很明显，反向链接的内容中，上面的「链接」才是重要的，「提及」的亮黄盖过了「链接」。

#### 3.3 文件组织

3.3.1 需要给库下一个明确的定义。ob 的库是完全隔离的，所以在 a 库中无法链接 b 库的内容，这个大家可以理解。但思源以一级文件夹为库， 不同一级文件夹之间互相不通。这对新用户来说很是迷惑：为什么在一个界面中却无法互通呢？目前老用户知道什么叫不能跨笔记本，新用户就无法理解：一级文件夹是一个笔记本，难道二给文件夹就不是吗？如果不能跨笔记本，那二级之间能不能跨？

新用户打开界面以后，一般会自己新建一个一级文件夹，而试验互链等功能时，又会用到指南文件夹里的内容，这会导致互链不成功，然后去群里问。。。。这不是浪费时间吗？

3.3.2 能否为我们这些 RR 用户设置一些功能，放便导入 RR 文章。RR 被墙住了，一年或说半年后，很多人的使用期满，应该就会逃离了。需要一些批量替换的功能。

3.3.3 一个小问题：一个文章的标题能否在文中显示？一般的笔记软件，都是能很清楚的看到文章名的，思源虽然也可以，但是字体太小，有时候忘记了自己的文章是什么标题。

#### 3.4 其它方面

3.4.1 付费的 4G 如 果作为附件的媒体文件，那这空间真是太小太小了，功能再棒，空间小的话，也会直接劝退很多人的。这方面我觉得付费用户至少要 10G 或 20G 起吧。

3.4.2 建议将软件的图标与名称赋与意义，能给出可行的高大上的解释更好。笔记用户多半都是知识分子，从观念上打动，比从功能上打动，更有效，相对来说也更容易。

3.4.3 建议对功能指南的文章内容进行重新排布与编写，目前的文章体系比较乱。有些重要的地方，没有在重要的位置显示。有些语焉不详。有些太过专业，知识前提没有交待清楚。这也导致后续在 QQ 群之类的地方，用户们反复询问一些简单的问题，造成不必要的时间精力浪费。

比如，关于内容块的文章很重要，是开发者想强调的，那就把它放到指南的最前面啊。

再比如，markdown 有关的内容写了 4 篇文章，4 篇文章之间的逻辑关系不太清楚。。。我对 md 有一点点了解，看第一篇的时候，迷惑不少，看完整个 4 篇，才明白意思。。。但花了好长时间。。。可否按认知顺序，一篇篇的写？

webdav 的内容，指南中没有提到。希望能补上。

3.4.4 思源默认打开时是编辑功能，切到预览功能下比较慢。从编辑功能到预览功能时，界面布局有时候发生了改变。。。这方面体验不太好。

3.4.5 需要 ctrl+ 点击，才能打开网址。这是个小问题。能直接点开最好。当然，我知道这是在 md 编辑模式下，一点就开，可能不太好实现。

3.4.6 脚注上的数字与原文之间，不能互相跳转。

3.4.7 思源的营销几乎没有，我昨天搜微博，内容不到 10 条，知乎也很少。知名度低的话，让人担心是否活得下去啊。

3.4.8 把内容从思源上复制到其它地方，带有很多段落id，这是如何办？总不能每次都一个个去掉，和导出吧？

3.4.9 段落与段落之间的距离，大于行与行之间的距离。那每个标题之间，要不要把默认距离设置得更大一点？

**Comment by wrwe3888** [comment]
我是文科生，没考虑开发难度，建议都是从使用者的角度说的，开发者视情况而定咯。

**Comment by 88250** [comment]
* 搜索方面的改进大致分为两部分，Ctrl P 快速搜索和搜索页签 #104。这两部分都会考虑条件过滤和路径过滤，比如支持按选择的文件夹或者排除指定路径
* 标签方面还需要进一步收集用户反馈，也许标签结合双链是比较妥当的，仅靠其中一种方法可能会有场景限制。标签组合搜索之前有其他用户[反馈过](https://ld246.com/article/1604982159923)，我们还需要时间学习
* 引用时支持 `【【` 或者 `[[` 触发自动完成的
* 选中内容右键可以创建文档，文档块和标题块的互转 #556 
* 跳转块引可通过按住 Ctrl 点击，或者点击悬浮窗口中的链接图标（回形针）
* 反链列表的改进计划 #295 
* 笔记本的定义请参考帮助文档，界面上已经用图标做了和文件夹的区分
* 导入其他平台的数据暂时不是重点，也许已经有其他项目解决了，这一点暂时没有去了解
* 付费仅支持 4G 是出于风险考虑，我们尽量做一些有把握的事情。以后随着思源的发展，免费扩容应该是会有的
* 帮助文档一直在改进，需要些时间
* 文件树上右键菜单有用预览模式打开
* 感谢帮忙考虑生存问题，但我们不会去做内容营销，我们坚信产品自己能说话，坚信用户会帮助我们口口相传……
* 复制内容带 ID 是个[缺陷](https://github.com/siyuan-note/siyuan/issues/637)，在 v0.5.2 中修复

非常感谢你花时间帮助我们改进思源，我们会继续努力的。

**Comment by 88250** [comment]
感谢反馈，我关闭该提议了，如果需要进一步反馈请直接跟帖，谢谢。

**Comment by Jackiexiao** [comment]
这个反馈牛逼了

**Comment by onlyacat** [comment]
厉害，今天体验了一下思源，很多感觉和作者类似。
