### ISSUE TITLE
`Ctrl+F3` 遵循笔记本设置中的 `块引新建文档存放位置`

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#6420]
https://ld246.com/article/1667119635078?r=88250

**Comment by iamqiz** [comment]
能不能为创建子文档单独设置一个快捷键? 
我用F3这个快捷键是用来创建子文档的, 而 (( 用来创建双链式标签的,
如果F3也遵循  `块引新建文档存放位置` 那么他俩就只能使用一个了,
所以我建议为创建子文档单独设置一个快捷键
或者让F3 遵循新的设置,比如  "F3块引新建文档存放位置"

**Comment by lfsjack** [comment]
> 

赞成这个提议，很多软件创建子文档都是有专门的快捷键的，思源需要创建子文档时没快捷键就不太方便，用快捷键创建的话往往还要额外移动一下，所以目前还不如靠菜单来创建。但是如果把F3设置成创建子文档，又会出来新问题。所以说还是单独加一个快捷键比较好。

**Comment by 88250** [comment]
这个需求目前还不确定改进方向，维持原样不变了，等考虑清楚再改进，谢谢。

**Comment by aptexd** [comment]
经过多轮尝试，我这 F3 没有使用“块引新建文档存放位置”
看讨论这个功能当初时没有这样改吗

**Comment by aptexd** [comment]
我看快捷键 F3 叫“新建文档为”

**Comment by aptexd** [comment]
要不就只是把现在的 F3 改名为“新建子文档名为”，功能实现都不变，兼容老用户
增加一个“新建文档名为”，遵循创建路径设置，有需要的自己改成 F3 或者别的

**Comment by iamqiz** [comment]
> 要不就只是把现在的 F3 改名为“新建子文档名为”，功能实现都不变，兼容老用户 增加一个“新建文档名为”，遵循创建路径设置，有需要的自己改成 F3 或者别的

同意
