### ISSUE TITLE
数据同步支持接入第三方 S3 协议对象存储服务

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6426]
* 提供界面配置
* 结束订阅用户内测阶段，开始进入免费公测阶段

欢迎使用我们的推广链接：

* 七牛云 https://s.qiniu.com/VbQfeu
* 阿里云 OSS：https://www.aliyun.com/product/oss?userCode=yqovuas2

region 参数：

* 七牛云的 https://developer.qiniu.com/kodo/4088/s3-access-domainname
* 阿里云的 https://help.aliyun.com/document_detail/31837.htm

**Comment by woniuxia** [comment]
D大，不过了？

**Comment by netdog2019** [comment]
这是革自己的命啊~~虽然大赞，但是希望思源能一直有稳定的现金流入，做大做强。

**Comment by SineMark2020** [comment]
虽然开放接入第三方，但如果有问题官方是不负责的，官方只维护自己的cloud, 这点可以在文档内写明.

**Comment by leolee9086** [comment]
有理  免责还是要写清楚

**Comment by JCJC01** [comment]
请问只支持s3？nas支持吗？

**Comment by aptexd** [comment]
咋能解释成不过了呢，可以放到会员权益中的
或者可以把备份放到对象存储中的

**Comment by netdog2019** [comment]
> 咋能解释成不过了呢，可以放到会员权益中的 或者可以把备份放到对象存储中的

可以放到会员权益中，赞同。

**Comment by TopProgrammer** [comment]
希望思源做大做强

**Comment by GoodBorther** [comment]
再创辉煌

**Comment by yuyuyu-github** [comment]
格局起来了，让那些小人之心度君子之腹的人打脸。( $ _ $ )( $ _ $ )

**Comment by Zuoqiu-Yingyi** [comment]
> 请问只支持s3？nas支持吗？

NAS 可以使用 docker 部署 [MinIO](https://github.com/minio/minio), 其可提供私有的 S3 兼容对象存储服务

**Comment by JCJC01** [comment]
> > 请问只支持s3？nas支持吗？
> 
> @JCJC01 NAS 可以使用 docker 部署 [MinIO](https://github.com/minio/minio), 其可提供私有的 S3 兼容对象存储服务

docker部署了minlo，想着用ob设置练手，但是填写相关参数后同步不成功，参数设置有没有一下什么注意的；
网页登陆时成功的；但是ob和joplin都同步不成功
请教，是要在网页上设置一些啥吗？还是笔记客户端设置的时候填写参数需要注意些坑？

**Comment by Zuoqiu-Yingyi** [comment]
> docker部署了minlo，想着用ob设置练手，但是填写相关参数后同步不成功，参数设置有没有一下什么注意的； 网页登陆时成功的；但是ob和joplin都同步不成功 请教，是要在网页上设置一些啥吗？还是笔记客户端设置的时候填写参数需要注意些坑？

不知道, 我也没用过, 只知道有这一个东西👀

**Comment by ericma15** [comment]
> > > 请问只支持s3？nas支持吗？
> > 
> > 
> > @JCJC01 NAS 可以使用 docker 部署 [MinIO](https://github.com/minio/minio), 其可提供私有的 S3 兼容对象存储服务
> 
> docker部署了minlo，想着用ob设置练手，但是填写相关参数后同步不成功，参数设置有没有一下什么注意的； 网页登陆时成功的；但是ob和joplin都同步不成功 请教，是要在网页上设置一些啥吗？还是笔记客户端设置的时候填写参数需要注意些坑？

我记得minio那个默认账号用api调用不会成功，但是网页可以登录。你需要按照s3的方法，生成一个新的账号，那个账号就可以用了。

**Comment by better319** [comment]
> 

那还不如直接用docker的思源呢。。。。

**Comment by better319** [comment]
> > > 请问只支持s3？nas支持吗？
> > 
> > 
> > @JCJC01 NAS 可以使用 docker 部署 [MinIO](https://github.com/minio/minio), 其可提供私有的 S3 兼容对象存储服务
> 
> docker部署了minlo，想着用ob设置练手，但是填写相关参数后同步不成功，参数设置有没有一下什么注意的； 网页登陆时成功的；但是ob和joplin都同步不成功 请教，是要在网页上设置一些啥吗？还是笔记客户端设置的时候填写参数需要注意些坑？

![微信截图_20221126111457](https://user-images.githubusercontent.com/13842581/204070410-10d1a598-18fb-4738-96b0-e08d3e501455.png)

**Comment by Sirlanri** [comment]
目前是“公测”，也就是说，今后有可能会变成付费选项？

**Comment by 88250** [comment]
@Sirlanri 是的
