### ISSUE TITLE
支持折叠块块类型

### ISSUE THREAD

**Issue by rohnyoung** [siyuan-note/siyuan#6430]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

折叠块的设计首先来自于网页， 同类产品Notion在设计软件时将这种设计体现在了笔记软件当中，将折叠这种信息展示方式定义为了一种块。用户只需通过点击就能够对块内容进行折叠和展开，同时这种块支持类似于列表的层级，从功能实现上来看，这种块相当于大纲。

折叠块的设计，相当于是把大纲本身也当成了一种块，这样设计的好处就是，大纲不仅仅是一种大纲，它也可以出现在文档中。这样大纲就不是一种局限了。然而这只是一种类比。折叠块最重要的好处在于它能够整理具有层级关系的长内容。

在移动端，因为是以触摸的形式，特别需要直接和节省展示空间，这种折叠块的设计，不仅在移动端会具有非常好的体验。同时在PC端也有方便的效果。

思源目前有对标题进行折叠和对列表进行折叠的按钮或快捷键。这种功能本身是没错的。但并不像大纲那么直接。因为折叠块本身就是一种块，所以说能够达即点即用的效果。和连带折叠还是有区别的。更加方便直接。

### 描述可能的最优解决方案 Describe the optimal solution

从功能实现上来讲，我们可以保留目前的标题折叠和列表折叠。新增一种折叠块类型。也可以去掉标题折叠和列表折叠，直接使用折叠块来实现文档内折叠的功能。由于标题折叠和列表折叠本身是隐形的。不影响文档展示。所以我个人建议不需要去掉这个方式，而是新增一种折叠的块类型。
![image](https://user-images.githubusercontent.com/80030055/198974247-ce511a60-a316-49bb-bbf6-abc5fd03a646.png)

实践上可以参考编辑器内左侧的大纲上的折叠按钮以及设置→快捷键详细面面当中的折叠按钮。我们可以看到这种按钮的设计使用起来是非常方便的。区别于标题旁边的折叠和列表旁边的折叠。相比起来更加直接。如果把这种按钮当成一种块，那么在内文当中对于整理具有层级关系的文档以及对于提升移动端编辑体验将会非常的直接有用。
![795520227adf9da66dc1a8bb45222b5](https://user-images.githubusercontent.com/80030055/198974616-96eb1ede-9e80-483e-b71a-3b5888114420.jpg)
![image](https://user-images.githubusercontent.com/80030055/198974645-24dee26c-9ff6-4df9-86dc-d64b2c3ece89.png)

**Comment by 88250** [comment]
你好，我没理解这个和现有的列表块的区别是？在思源中所有块都可以折叠，所以理论上已经不需要单独的折叠块了。

**Comment by rohnyoung** [comment]
> 请仔细阅读一下应该可以比较容易理解。

**Comment by 88250** [comment]
我已经仔细阅读过了，实在 get 不到你的意思 😂

**Comment by rohnyoung** [comment]
简单来说就是目前的折叠方式是隐形的，而折叠快是直接的，这特别是对于移动端将会比较影响使用体验

**Comment by 88250** [comment]
那应该是改进移动端的折叠方式，而不是引入新的块类型吧？

**Comment by rohnyoung** [comment]
说起来就是目前的折叠方式是隐形的，而折叠块是直接的，特别是对于这端比较简单的编辑体验影响比较大

**Comment by 88250** [comment]
> 简单来说就是目前的折叠方式是隐形的，而折叠块是直接的，

那应该是改进移动端的折叠方式，而不是引入新的块类型吧？

**Comment by rohnyoung** [comment]
如果你仔细看了我上面的内容的话，你会发现，这不仅仅是针对移动端。只是说这种块对移动端会更友好。现有的折叠方式它不是一种块，它是一种隐形的折叠方式。这对于直接使用折叠块是有区别的。

**Comment by 88250** [comment]
不考虑引入块类型了，如果有需要可以通过挂件块扩展，感谢提议。

**Comment by rohnyoung** [comment]
好的，辛苦了。
