### ISSUE TITLE
收集箱/剪藏 扩展无法 收集/剪藏 公众号文章的字体元素

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#6432]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

一篇文章是包含字体颜色、删除线、下划线组成的，由于文章内容可能较为敏感，就截取一小部分截图。
![image](https://user-images.githubusercontent.com/98400319/199020019-15e9b23b-7b47-4ba4-90e9-cbdf152666f7.png)
如图所示，它是一份新旧内容的对比文章，旧的内容是删除线＋红色字体，新的内容是下划线＋蓝色字体，由于文章就是这么构成的，所以字体元素不可或缺，希望能够优化一下收集箱/剪藏扩展。

### 期待的结果 Expected result

优化改进

### 版本环境 Version environment

```markdown
- Version: 2.4.8
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
这个短期内无法支持，先关闭了，后续如果能支持再考虑，谢谢。

**Comment by EberhardLin** [comment]
> 这个短期内无法支持，先关闭了，后续如果能支持再考虑，谢谢。

好的，可以理解。
