### ISSUE TITLE
浏览器端 `Ctrl+N` 快捷键冲突

### ISSUE THREAD

**Issue by luke-zhang580** [siyuan-note/siyuan#6433]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在mac chrome 浏览器下打开自部署的思源笔记界面时，新建文档快捷键时command+N, 但是该快捷键与Chrome自由关闭窗口快捷键冲突，所以会导致失效。
<img width="641" alt="CleanShot 2022-10-31 at 21 46 57@2x" src="https://user-images.githubusercontent.com/45325652/199022837-e8453e04-462b-453f-afb5-6ff2d0267ef8.png">

### 描述可能的最优解决方案 Describe the optimal solution

虽然思源支持可以修改快捷键设置来避开这一限制，但是是否可以考虑不修改快捷键来完成这一设置呢？

**Comment by Vanessa219** [comment]
这个貌似没有办法，用桌面端吧 https://stackoverflow.com/questions/38838302/any-way-to-override-ctrln-to-open-a-new-window-in-chrome
