### ISSUE TITLE
zotero的链接无法自动转义了

### ISSUE THREAD

**Issue by ippreacher** [siyuan-note/siyuan#6438]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

2.4.8版本，使用粘贴转义文本功能来粘贴zotero的注释，无法自动转义为链接。我记得之前的版本是可以的。

### 期待的结果 Expected result

希望修复粘贴转义文本功能

### 版本环境 Version environment

```markdown
- Version: 2.4.8
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by HowcanoeWang** [comment]
原来一直支持的吗，我都是粘贴了之后手动选中然后ctrl+K

**Comment by 88250** [comment]
原来也不支持，需要使用 Ctrl+K。

**Comment by ippreacher** [comment]
原来确实可以的，我都靠这种方式写了半篇论文了。原来是复制zotero的注释，然后粘贴转义文本，就能自动识别为链接。
像这样：
![_20221101201952](https://user-images.githubusercontent.com/53852556/199230849-c3cc99a4-c969-47ac-a251-6e13be1e4837.png)
但现在不行了。
