### ISSUE TITLE
为页签右键菜单添加定位文档和删除文档等功能

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6439]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在文档树中定位打开的文档，以及快速删除文档。

### 描述可能的最优解决方案 Describe the optimal solution

为页签右键菜单添加定位文档和删除文档等功能

**Comment by 88250** [comment]
删除功能暂时不考虑，定位可以用文档树按钮，谢谢。
