### ISSUE TITLE
内容块链接预览改进

### ISSUE THREAD

**Issue by 2016201256** [siyuan-note/siyuan#644]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
光标放在内容块链接上时会弹出预览窗口，但有时弹出窗口会覆盖住原链接所在位置，导致点击链接不方便。

### 描述最优的解决方案 Describe the optimal solution
改进预览窗口弹出位置，避免覆盖原链接。

### 其他信息 Other information
![说明](https://user-images.githubusercontent.com/58763608/101228250-d6866d00-36d5-11eb-8056-62eeb7cd35f8.gif)

**Comment by 88250** [comment]
你好，目前版本的悬浮预览窗口的位置计算稍微做了一些优化，请体验新版。

如果还有反馈请继续跟帖，谢谢。
