### ISSUE TITLE
优化公式输入体验

### ISSUE THREAD

**Issue by TankNee** [siyuan-note/siyuan#6443]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

输入公式的时候，目前公式输入框是一个简单的纯文本输入框，连括号的自动补全都没有，输入公式一多，就很难分辨，字体也不够友好。

### 描述可能的最优解决方案 Describe the optimal solution

添加公式输入时括号自动补全，使用代码字体替换原本的字体，提供latex语法高亮。

**Comment by 88250** [comment]
这个短期内无法支持，先关闭了，以后如果有计划会重开，谢谢。
