### ISSUE TITLE
浏览器剪藏网页内容，丢失引述块

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#6444]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

与 #6325 表现接近，在使用浏览器插件来剪藏时，丢失里面的引述内容，剪藏页面地址是：[测试基础知识](https://developer.android.com/training/testing/fundamentals.html#testing-pyramid)。

<img width="882" alt="image" src="https://user-images.githubusercontent.com/33319484/199224957-35c7438d-3d20-4a0b-a7b1-debc55b58ba3.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/33319484/199224994-6b591942-db13-49ab-bf5b-185011a09b10.png">

### 期待的结果 Expected result

能剪切到引述内容块

### 版本环境 Version environment

```markdown
- Version: 2.4.8
- Operating System: Mac 12.5
- Browser (if used): 谷歌浏览器
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9909454/siyuan.log)

**Comment by 88250** [comment]
这个网页部分 Note 使用了 `<aside>` 标签，这个标签需要过滤掉，否则可能导致剪藏到不属于正文的内容。

这里使用了 `<p>` 是算入正文的，所以剪藏成功：

![image](https://user-images.githubusercontent.com/873584/199227088-473032cd-4e72-4b0d-b3f7-99ceef525468.png)

但是这里使用的是 `<aside>` 不算入正文，所以不剪藏：

![image](https://user-images.githubusercontent.com/873584/199227261-da5b3d53-e6cb-43e4-8254-c8a70008e3c4.png)
