### ISSUE TITLE
开源云端同步服务实现

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6445]
## 背景

https://github.com/siyuan-note/dejavu/pull/1#issuecomment-1298413278

将云端同步服务器实现完整复刻到本地，这个实现是针对七牛云做的，作为参考实现提供给社区开发者，以备后续支持 S3 协议扩展 https://github.com/siyuan-note/siyuan/issues/6426

## 使用方式

需要手动配置 工作空间/conf/conf.json 中的 `sync.provider` 为 `1` 以及 `oss`，参考如下：

```json
  "sync": {
    "cloudName": "main",
    "enabled": true,
    "mode": 1,
    "synced": 1667358208034,
    "stat": "同步于 2022-11-02 11:03:28\n\n上传/下载文件数 0/1\n上传/下载分块数 0/0\n发送/接收字节数 0 B/3.6 kB",
    "generateConflictDoc": false,
    "provider": 1,
    "oss": {
      "endpoint": "你的七牛云域名，例如 http://yourdoamin.com/",
      "accessKey": "你的密钥 AK",
      "secretKey": "你的密钥 SK",
      "bucket": "存储空间名称",      
      "region": "存储区域，七牛云不用配置，会自动获取"
    }
  },
```

目前该特性处于内测阶段，所以暂时只提供手动修改配置文件的配置方式，等内测稳定以后会在 #6426 中提供界面配置给普通用户使用。

开发者可参考源码：https://github.com/siyuan-note/dejavu/blob/main/cloud/qiniu.go

**Comment by mozhux** [comment]
不干了？

**Comment by aptexd** [comment]
考虑开通下国际捐赠渠道吧 😂
