### ISSUE TITLE
数据同步支持接入第三方 WebDAV 服务

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6446]
* 提供界面配置
* 结束订阅用户内测阶段，开始进入免费公测阶段

不建议使用坚果云 WebDAV，因为它的接口有频率限制，会导致可用性较低，具体限制可参考坚果云官方文档 [https://help.jianguoyun.com/?p=2064](https://help.jianguoyun.com/?p=2064)

**Comment by qujunde** [comment]
配置界面在哪里？没有找到

**Comment by 88250** [comment]
@qujunde 等 v2.5.0 发布就有了。

**Comment by suyiqin123** [comment]
![image](https://user-images.githubusercontent.com/76785377/201879577-06c12e23-63b5-4a94-b1ac-4ba54459e99c.png)
teracloud 总是同步到中途出错。

**Comment by suyiqin123** [comment]
每次同步失败的文件不一样。
进行删除历史记录，重新索引，重置数据库，清除无用的资源还是会出现。

**Comment by suyiqin123** [comment]
不是不能同步，状态条显示同步了不少文件，然后就显示同步失败，查teracloud目录确实自动创建了不少东西。删除重来也不行，更换目录也不行。留意一下，看看什么问题。

**Comment by 88250** [comment]
@suyiqin123 国内网络的话建议用国内的服务。

**Comment by chenyajunai** [comment]
WebDAV是不支持中文还是不支持子目录，在我系统都根目录下创建了好多文件

**Comment by 88250** [comment]
@chenyajunai 会在你选择的云端同步目录下进行同步

**Comment by better319** [comment]
其实我感觉这个没必要啊，利润点也没了。


你搞点vip的模板、界面和美化什么的，通过界面或vip模板来收费吧。

感觉这个套路和qq秀差不多，加油啊！！

**Comment by chenyajunai** [comment]
> @chenyajunai会在你选择的云端同步目录下进行同步

我用的子目录是中文的，居然在我根目录创建了一大堆文件

**Comment by qujunde** [comment]
云目录只能选择根目录 不能选择多层目录

**Comment by terwer** [comment]
我有个问题不知道算不算问题。
我用的阿里云oss，目前同步，换设备都正常，也很快。但是我在oss目录看不到同步的数据，不知道在哪里看

这是设置

![image](https://user-images.githubusercontent.com/3259282/202144612-f78f5d9b-5b11-402b-8529-747bc0587b46.png)

![image](https://user-images.githubusercontent.com/3259282/202144660-9f8afc9f-3b9d-4bc2-a95b-2fa52e048e53.png)


这是oss数据列表

![image](https://user-images.githubusercontent.com/3259282/202144470-40e18dc1-c36d-49dc-9e9c-9c36c8e030bf.png)

**Comment by geosmart** [comment]
家用truenas，自带webdav服务，用起来还行。
云端：k3s部署个pod
电脑：linux AppImage从webdav同步
手机：网站端从webdav同步

暂时体验同步还算正常

**Comment by geosmart** [comment]
> > 家用truenas，自带webdav服务，用起来还行。 云端：k3s部署个pod 电脑：linux AppImage从webdav同步 手机：网站端从webdav同步
> > 暂时体验同步还算正常
> 
> 我是从电脑同步到truenas的webdav服务，思源2.6.3里面选择同步目录只能选择到根文件下的两个文件，webdav里面配置的虚拟目录在选择同步文件时看不到，楼主时怎么配置的？

![1](https://user-images.githubusercontent.com/3156608/215366556-bf87602c-93a5-4258-9f97-959ce68567b0.jpg)
地址里面带上你的目录名称就好

**Comment by enjoywithme** [comment]
> > > 家用truenas，自带webdav服务，用起来还行。 云端：k3s部署个pod 电脑：linux AppImage从webdav同步 手机：网站端从webdav同步
> > > 暂时体验同步还算正常
> > 
> > 
> > 我是从电脑同步到truenas的webdav服务，思源2.6.3里面选择同步目录只能选择到根文件下的两个文件，webdav里面配置的虚拟目录在选择同步文件时看不到，楼主时怎么配置的？
> 
> ![1](https://user-images.githubusercontent.com/3156608/215366556-bf87602c-93a5-4258-9f97-959ce68567b0.jpg) 地址里面带上你的目录名称就好

谢谢，找到原因了，truenas的webdav不能用摘要认证，思源只认basic认证

**Comment by geosmart** [comment]
@enjoywithme  我换成minio了，truenas部署个minio，同步速度比webdav会快很多

**Comment by enjoywithme** [comment]
2.8.3版本同步到我本地的webdav提示“云端存储服务提供商网络连通性校验异常，请检查网络配置”，实际上我的webdav是好的，浏览器中是能正常访问的，哪里能看到具体原因导致的吗？

**Comment by enjoywithme** [comment]
同步自建的webdav提示“云端存储服务提供商网络连通性校验异常，请检查网络配置”，浏览器访问webdav没有问题的，配置云端同步时也能看到webdav上的目录，但是就是不能同步，貌似升级2.8.3后出的问题，哪里能看到有关的日志吗

**Comment by 88250** [comment]
@enjoywithme 可能是这个影响的 https://github.com/siyuan-note/siyuan/issues/7890 可以试下最新的 dev 版是否正常。

**Comment by enjoywithme** [comment]
> @enjoywithme 可能是这个影响的 #7890 可以试下最新的 dev 版是否正常。

没有测试dev，估计是这个原因，禁用HTTPS改用HTTP就正常了。
