### ISSUE TITLE
引用块显示原文格式

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6449]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

将一个块复制为引用块粘贴后，如果原文有加粗、高亮等格式，希望引用块也能显示。

### 描述可能的最优解决方案 Describe the optimal solution

略

**Comment by 88250** [comment]
锚文本在设计上是纯文本，所以无法支持其他行级元素，感谢提议。
