### ISSUE TITLE
关闭未保存文件问题

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#645]
### 描述问题 Describe the problem

关闭未保存文件时, 点击取消, 再尝试关闭, 则无提示直接保存+关闭

### 期待的结果 Expected result

实现较为常见的行为: 关闭为保存文件时, 提示是否保存, 选项为 是/否/取消

### 版本环境 Version environment

* 版本 Version：0.5.1
* 操作系统 Operating system：win10 x64
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，这是因为有自动保存（间隔 2s），刚好在这个时间内自动保存了，所以再次关闭是就是正常关闭了。
