### ISSUE TITLE
设备管理器

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#6451]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前各种同步问题，绝大部分是由于多设备同时在线各种覆盖导致的。

### 描述可能的最优解决方案 Describe the optimal solution

期望添加设备管理器，查看当前在线的客户端，并可以踢下线，下线前进行上传等操作。
最重要的是，打开软件前判断如果多端在线，进行提示，并进行文件版本之类的判断。

### 描述候选的解决方案 Describe the candidate solution

强制单点登陆。

**Comment by 88250** [comment]
这个估计无法实现，目前已经支持冲突文件保留，感谢提议。

**Comment by woniuxia** [comment]
> 这个估计无法实现，目前已经支持冲突文件保留，感谢提议。

当前冲突文件保留，经常会出现大量的冲突，没有很好的处理策略，很多人只能批量进行删除，感觉没有达到预期的目的。

**Comment by woniuxia** [comment]
还是希望D大在考虑下这个 issue。
昨天晚上在家里用自己的电脑打开思源的时候，就一直在想公司电脑的思源是否打开，因为我同步设置的手动，有改动可能没有同步到云端，现在去改，会不会导致冲突之类的。
个人还是比较反感解决冲突的，更希望是一种简单的线性方式去修改数据。
今天早上来到公司，看到思源是打开的，不过好在没有啥更改，没有出现冲突之类的。
所以还是挺希望能看到当前账号是否在其他地方登录，如果有登陆，可以让其他地方退出并立即同步。

**Comment by 88250** [comment]
官方同步的话可以试下打开同步感知。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月18日(周三) 上午9:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 设备管理器 (Issue #6451)




 
还是希望D大在考虑下这个 issue。
 昨天晚上在家里用自己的电脑打开思源的时候，就一直在想公司电脑的思源是否打开，因为我同步设置的手动，有改动可能没有同步到云端，现在去改，会不会导致冲突之类的。
 个人还是比较反感解决冲突的，更希望是一种简单的线性方式去修改数据。
 今天早上来到公司，看到思源是打开的，不过好在没有啥更改，没有出现冲突之类的。
 所以还是挺希望能看到当前账号是否在其他地方登录，如果有登陆，可以让其他地方退出并立即同步。

**Comment by woniuxia** [comment]
是官方的同步。
但是没有找到同步感知功能，请问D大功能是在哪里开启。

**Comment by 88250** [comment]
设置 - 云端 - 云端同步模式 - 自动同步 - 同步感知



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月18日(周三) 上午10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 设备管理器 (Issue #6451)




 
是官方的同步。
 但是没有找到同步感知功能，请问D大功能是在哪里开启。
