### ISSUE TITLE
关于docker版的升级

### ISSUE THREAD

**Issue by pstandard** [siyuan-note/siyuan#6452]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

似乎从V1.9.2开始，系统不会提示升级了，想问一下，我的docker版思源笔记是否可以直接从v1.9.2升级到v2.4.9?会否有兼容性问题？

### 描述可能的最优解决方案 Describe the optimal solution

无

### 描述候选的解决方案 Describe the candidate solution

无

**Comment by woniuxia** [comment]
去论坛看下吧，记得有几次大的更新不兼容。升级前备份好。

**Comment by 88250** [comment]
备份好数据再升级，如果有问题请跟帖，我先关闭了，谢谢。
