### ISSUE TITLE
鼠标的左右滚轮无法使用

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#6454]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我使用的鼠标有左右滚轮，型号是罗技M590。但在思源笔记PC客户端（版本v2.4.9，Win10）中左右滚轮无法使用。比如，在思源笔记中打开一个pdf然后放大，就会发现，上下滚轮正常，左右滚轮无效。

同样的问题我之前在VScode中遇到过，并提交了issue（ https://github.com/microsoft/vscode/issues/84136 ），他们给出了解决方法，那就是chromium的版本号要为78。然后我在edge浏览器（版本号107）中通过 127.0.0.1:6806 打开了思源笔记，经测试，在浏览器中，左右滚轮是正常使用的。

### 期待的结果 Expected result

鼠标滚轮在思源笔记客户端中正常使用。

### 版本环境 Version environment

```markdown
- Version: v2.4.9
- Operating System: Win10
- Browser (if used): Edge 107.0.1418.26
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9915684/siyuan.log)

**Comment by Vanessa219** [comment]
目前 Electron 是 21.2.0，Chromium 已经到 106.0.5249.61 了。

**Comment by 88250** [comment]
这个问题估计不是那么容易解决，先关闭了，后面有空再考虑了，谢谢。

**Comment by luo-chuan** [comment]
好像基于electron的软件很多都会遇到这个问题，electron方面称这是罗技的驱动导致的，但他们又解释不了为什么同一鼠标在chrome及其它软件中就正常。我找到了一个临时替代方案，需要用到X-Mouse Button Control这一软件。可以对鼠标中键（或侧键）设置和弦，将`中键+上滚轮`和`中键+下滚轮`分别映射为`Shift+上滚轮`以及`Shift+下滚轮`，如下图。可能你不明白我在说什么，你自己下载体验一下就懂了。软件链接： https://www.highrez.co.uk/downloads/XMouseButtonControl.htm  
![image](https://user-images.githubusercontent.com/33930736/208221571-cdff9b05-2450-4bab-8d2f-cf9c24c752f4.png)
