### ISSUE TITLE
请求 FlowChart、Graphviz、Mermaid、PlantUML 图表支持在块内缩放、拖动

### ISSUE THREAD

**Issue by Febtw** [siyuan-note/siyuan#6456]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前，如果图表过大，Mermaid、PlantUML 会将图表的内容缩小，来适应块的大小；而 FlowChart、Graphviz 会超出块甚至页面的大小呈现整个图表。但这样图表都是相对固定，不方便观察图表的细部和整体。所以如果图表能够在块的区域内拖动、缩放，会给阅读带来极大的方便。这个特性在 Mind map 中已经得到实现了。

### 描述可能的最优解决方案 Describe the optimal solution

如 Mind map 图表那样，可以在块的范围中进行拖动和缩放。

https://user-images.githubusercontent.com/96163355/199419932-5a03ac85-1be7-4072-817a-f9ea4403a2bf.mp4

### 其他信息 Other information

思源版本 v2.2.3

Mermaid、PlantUML 会将图表的内容缩小，来适应块的大小
Mermaid
![image](https://user-images.githubusercontent.com/96163355/199415499-f34d3c4a-69fb-46e7-ad2c-78ddb45a7236.png)
PlantUML
![image](https://user-images.githubusercontent.com/96163355/199415991-015a0621-5289-4451-8a0e-6e06e8f69598.png)

FlowChart、Graphviz 会超出块的大小呈现整个图表
FlowChart
![image](https://user-images.githubusercontent.com/96163355/199416607-05c1ea5d-027e-4f79-982c-36dbd8476bb2.png)
Graphviz
![image](https://user-images.githubusercontent.com/96163355/199416824-11dec665-cbb0-4d30-8587-1c17c7bbaa5e.png)

**Comment by Vanessa219** [comment]
这几个用的是不同的第三方库，需要看他们是否支持缩放。脑图用的是 Echart，所以本身是支持缩放的。

**Comment by Febtw** [comment]
> 这几个用的是不同的第三方库，需要看他们是否支持缩放。脑图用的是 Echart，所以本身是支持缩放的。 还麻烦把 .sy 文件发我一下，我看看是否能解决。

好的，麻烦看下
[DOT语言.sy.zip](https://github.com/siyuan-note/siyuan/files/9922488/DOT.sy.zip)

另外好像是Chart图表用的echart，并不是默认开启拖动、缩放的，但可以通过绘图语法实现，我找到一个例子确实可行，但是还是搞不明白怎么实现的。我想用 echart 绘制动态关系图，但网上甚至官网的关系图实例基本都不能用，都提示
echarts render error:
SyntaxError:Expected property name or }in JSON at position *
请问可否提供一些echart的使用说明

**Comment by Vanessa219** [comment]
可参考帮助文档中排版元素一文中的图表，严格使用 JSON 结构即可。

**Comment by Vanessa219** [comment]
看了一下剩余的图标，它们都没有自带缩放功能，这个没有办法实现，我先关闭了。

**Comment by Febtw** [comment]
> 可参考帮助文档中排版元素一文中的图表，严格使用 JSON 结构即可。
> 看了一下剩余的图表，它们都没有自带缩放功能，这个没有办法实现，我先关闭了。

好吧，还是感谢，不过帮助文档中只有 echart 没有语法参考，其他图表都有😂😂

**Comment by Vanessa219** [comment]
语法需要到官网去看 https://echarts.apache.org/examples/zh/index.html，稍后补充文档
