### ISSUE TITLE
New list type

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6459]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Sorry if I can't find this function... But, in Brazil, it's very common to use a list to sequence information.

In the program, I see that there is a sequence of numbers when we type "1.". After that, a sequence of numbers appears when pressing "enter" on the keyboard.

I would suggest implementing alphabetical sequence. For example, when you press "a)" the program recognizes and starts the listing.

      a)
      b)
      c)
      d)
      e)

### 描述可能的最优解决方案 Describe the optimal solution

new feature

**Comment by 88250** [comment]
Sorry, we are unable to support this feature.
