### ISSUE TITLE
用文档的首行作为标题

### ISSUE THREAD

**Issue by goodluck233** [siyuan-note/siyuan#646]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在创建新文档时不强行要求输入标题名称，而是在输入第一行并且换行后，把第一行的文本作为文档名称。

### 描述最优的解决方案 Describe the optimal solution
实现了以上所述功能的软件：印象笔记（换行时自动命名）、为知笔记（换行时自动命名）、Onenote（第一行输入的文本会实时地反应到名称上）、Typora（保存时会以第一行作为名称）

**Comment by 88250** [comment]
目前的使用流程是必须要先命名才能创建文档，v0.5.2 会支持文档名模板，可以解决快速创建的需求。你的建议是文档名跟随内容变化（首行或者首个标题块），这个在实现上有难度，暂时支持不了，见谅。

感谢你的建议，我关闭了。
