### ISSUE TITLE
win开发环境下设置外观里不显示默认以外的主题

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#6461]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![Snipaste_2022-11-02_23-21-33](https://user-images.githubusercontent.com/48077521/199529518-43070358-6ae2-425a-9f31-eed986eea704.png)

### 期待的结果 Expected result

1

### 版本环境 Version environment

```markdown
- Version: v2.4.9
- Operating System:  win 开发环境
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
启动参数加入工作目录 `--wd=D:\目录\siyuan\app` 后再试试，主题要放在 app/themes/ 下面：

![image](https://user-images.githubusercontent.com/873584/199531926-fc2f2a89-d7cf-41bd-aa4a-364c729958c6.png)

**Comment by iamqiz** [comment]
kernel的启动用的workspace directory 是 正式版本用的一样, 为啥主题却用app目录下的?
```
I 2022/11/02 23:19:15 runtime.go:47: kernel is booting:
    * ver [2.4.9]
    * arch [amd64]
    * pid [42120]
    * runtime mode [dev]
    * working directory [..]        
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\pcmsi\Documents\SiYuan
```
能不能 加个选项 --themes 指定主题目录?

**Comment by 88250** [comment]
开发环境这里做了单独的加载以方便开发：

![image](https://user-images.githubusercontent.com/873584/199540657-707469ab-96e2-4386-a9c4-612683f2e34e.png)
