### ISSUE TITLE
关于间隔重复功能建议

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#6462]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

思源想要真正成为 All in one 的笔记软件，间隔重复功能必不可少，因为定期复习是知识学习过程中不可缺少的一环。

### 描述可能的最优解决方案 Describe the optimal solution

虽然有人开发第三方工具来同步思源和 anki，但这并不是完美的解决方案，因为 anki 卡片中无法做到鼠标悬停预览。特别是对于理科学习，经常遇到一个知识点依赖于另一个知识点，举个简单的例子，线性代数中的”克莱姆法则”会涉及到“行列式”这一概念，假如用户在 anki 软件中复习到”克莱姆法则”时忘记了“行列式”这一概念，就无法通过鼠标悬停来查看行列式的定义。所以最完美的解决方案应该是直接在思源笔记软件中集成间隔重复的功能，就像 Remnote 那样。Remnote 的理念其实是非常先进的，让用户在做笔记的同时就完成了制卡，并且受益于“块引用”功能，让用户在复习卡片时可以通过鼠标悬停来回顾相关知识。

**Comment by 88250** [comment]
未来可能会考虑，请关注 https://github.com/siyuan-note/siyuan/issues/3284
