### ISSUE TITLE
编辑行始终居中功能

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#6463]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我在记录纸质书笔记的时候，会把书通过阅读架正立在显示器前方，让我不至于一会低头看书，又一会抬头盯着屏幕记笔记。
但这样会导致屏幕下方会被遮挡一部分，让我时不时就要把手放到鼠标上通过滚轮将回车敲下的下一行显示在我所能看见的地方。
查询了下，发现曾经有过这样一个issue：https://github.com/siyuan-note/siyuan/issues/840
我不知道这个issue的背景，所以提个issue想知道能不能恢复这个特性，提升我的编辑体验。

### 描述可能的最优解决方案 Describe the optimal solution

这个特性并不具备普适性，毕竟一直强制居中编辑会导致用户在编辑时无法轻松的看到上文的一部分。（有可能换行多了，导致有一部分内容直接顶上去了）
所以该特性建议设计为可开关选项，通过图标＋快捷键来控制开启关闭。
这种设计我个人是认为合理，可以满足快速记录和专注记录的需求，提升不同场景下的编辑体验。

### 其他信息 Other information

- https://github.com/siyuan-note/siyuan/issues/840
- 可开关

**Comment by woniuxia** [comment]
编辑行如果是最后一行的话，是在中间的。

**Comment by 88250** [comment]
打字机模式不考虑了，目前已经有聚焦功能，感谢提议。

**Comment by EberhardLin** [comment]
> 编辑行如果是最后一行的话，是在中间的。

![image](https://user-images.githubusercontent.com/98400319/199641924-563dcc18-4494-4223-86be-e9ad254219be.png)
没有哇，一直是在最底下。

**Comment by EberhardLin** [comment]
> 打字机模式不考虑了，目前已经有聚焦功能，感谢提议。

可是聚焦有种上下文分开的割裂感，也不能解决打字机模式的需求……

**Comment by EberhardLin** [comment]
> > > 打字机模式不考虑了，目前已经有聚焦功能，感谢提议。
> > 
> > 
> > 可是聚焦有种上下文分开的割裂感，也不能解决打字机模式的需求……
> 
> dark+不是有打字机模式吗

Dark+是个很好的主题，但我个人不喜欢它的外观，所以没有下载使用。
而颜值又很影响我的使用心情，所以坦率点讲我会因为不喜欢它的外观而放弃使用它自带的打字机模式。
PS：萌佬如果看到的话别伤心，人的审美各有不同，Dark+真的是很好的主题！
