### ISSUE TITLE
iPad在无外置键盘的情况下如何使用tab的功能?如何达到PC端右键的功能?以及iPadOS的自刷新功能有关问题?

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#6465]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

iPad在无外置键盘的情况下如何使用tab的功能?
如何达到PC端右键的功能?
---
iPadOS后台自刷新功能有什么用处?没百度到.
此外这个功能能否 解决思源笔记在iPad后台一两分钟就会内核中断的问题?

### 期待的结果 Expected result

iPad等移动端有格式快捷栏

### 版本环境 Version environment

```markdown
iPad air5 iPadOS16.1
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
感谢反馈，但是目前没有时间处理，我们先合并到 #4238 中进行记录。

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/9113
