### ISSUE TITLE
引入笔记本类型的概念，加入便签型笔记本。

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#647]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

应该都用过手机上的便签功能吧，打开便签，新建一条便签，将想要记录的东西写进去。也不管文件名的概念，反正就是新建一条便签，文字写进去。

所有便签条目在首页会以瀑布流的形式展示，通过上下滑动浏览内容、搜索关键词查找。

很多人在手机上记东西，不会去专门下载一个笔记软件，他们更倾向于使用手机自带的便签。手机上的笔记类软件也都趋同地发展成了便签型的笔记软件，因为只有

例如，小米便签、锤子便签等等。

电脑上的笔记都有这样一个特点：

* 要记下一个东西前，需要打开笔记软件，打开笔记本，找一个、新建一个合适的子文件夹，新建一个文件，给它合适的命名，以便方便以后找到，然后打开了打字页面，再记录内容。这是其缺点：
    * 操作复杂，分类、新建文件、输入文件名这一步尤其需要思考，大脑里突然有想记下的东西，此时却还要另外开一个线程去想放到哪里、什么文件名里合适，这是在难为单线程的大脑，等起好文件名，都忘记要写啥了。
    * 操作复杂，如果不能简化步骤，对于一些不太重要、有点想记下、以后可能用得着、但又不是太必要的东西，大脑就倾向于懒得去记了。点赞、评论、转发能让人上瘾、成为大公司软件的标配功能，就是因为这个动作简单，随手就能做。
    * 所有的笔记都是以文件名为主要索引方式，用户只能一大串文件名列表中查阅。但不管是知乎、链滴、便签，给用户浏览的时候，都是用一个瀑布流，每一个条目里显示一部分内容，而不是展示文件名。

基于文件名的归档、浏览的笔记本就是普通类型的笔记本，它对于归档、管理友好，但是在即时记录方面，不如便签方便。

### 描述最优的解决方案 Describe the optimal solution

如果要让用户对使用思源笔记上瘾，就需要简化记笔记、浏览笔记的行动难度。

这就需要引入便签类型的笔记本了，它与普通笔记本不同，用户点击笔记本，浏览里面的条目时，看到的不是在左侧文件列表里的一列文件名，而是在右侧一个 tab 栏里，过往便签以瀑布流的形式列出，每个条目显示该便签的一部分头部内容，具体画面可以借助手机便签想象下。

当想记东西时，用户只要打开思源，选择便签笔记本，新建便签，开始写东西。甚至可以更简化，为打开某个笔记本设置快捷键，一步打开笔记本，再按下 Ctrl + N 就可以在崭新的一页便签记录新东西。

### 描述候选解决方案 Describe the candidate solution

便签类型的笔记很多属性与传统笔记有所不同，所以我认为是需要引入一个实体的。

这个实体不是一个全新的东西，不过在实施上不是一个全新的类，应该是普通笔记本的一个子类，有了以下不同：

* 新建笔记时，不再过问文件名，直接以时间戳命名新建。
* 在浏览时，不再在软件层面像用户展示文件名列表，而是用一个大的 Tab 以瀑布流的形式展示便签列表。

### 其他信息 Other information

小米便签的瀑布流展示：

![Screenshot_2020-12-05-13-01-36-063_com miui notes](https://user-images.githubusercontent.com/19181833/101235105-7c4ed180-3700-11eb-9c0e-a93529eaeae5.jpg)

**Comment by 88250** [comment]
感谢提议，现阶段暂时不适合考虑多视图，等后期我们会进行回顾，谢谢。
