### ISSUE TITLE
使用 API `/api/block/updateBlock` 更新块内容时行内元素解析错误

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6470]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

## 问题1
使用 API `/api/block/updateBlock` 更新块内容时行内元素解析错误
复现方法: markdown 后缀标志前存在空格
出现该问题的行级元素:
- 加粗
- 倾斜
- 删除线
- 标记
- 上标
- 下标
- 使用行内 IAL 设置样式

复现代码:
```markdown
**加粗 **
*倾斜 *
~~删除线 ~~
==标记 ==
^上标 ^
~下标 ~
备注^（这是一个行级备注 ）^
**颜色 1 **{: style="color: var(--b3-font-color1); background-color: var(--b3-font-background1);"}
```

渲染样式:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/49649786/199766452-b70c9db0-c1ea-451b-9709-1a4fb4c5bba9.png">

## 问题2
无法使用 API 插入行内备注
数据库 markdown 字段中行内备注为 `备注^（这是一个行级备注）^` 与 `foo^(bar)^`
但是使用如下代码插入行内备注则显示为上标样式
```markdown
备注^（这是一个行级备注）^
foo^(bar)^
```
<img width="117" alt="image" src="https://user-images.githubusercontent.com/49649786/199767675-e30d2957-c5a8-41ce-82b6-7a3d40e38a99.png">

### 期待的结果 Expected result

markdown 后缀标志前存在空格的行内元素也能正常渲染(将空格视为行内元素的一部分)
支持使用 API 插入行内备注

### 版本环境 Version environment

```markdown
- Version: 2.4.9
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
1. 这个是符合 Markdown 语法的，不解析
2. 行级备注没有 Markdown 语法支持

**Comment by Zuoqiu-Yingyi** [comment]
> 1. 这个是符合 Markdown 语法的，不解析
> 2. 行级备注没有 Markdown 语法支持

1. 那么就是markdown导出与数据库中markdown字段的内容错误:
   输入 `foo bar` 后划选 `foo ` 并设置为加粗, 导出为 markdown 文档时对应的文本为 `**foo **bar`, 导入后解析出现该问题
