### ISSUE TITLE
块相关 API `/api/block/*` 提供 `dataType: "plaintext"` 模式插入转义文本

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6473]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

手动处理转义字符会出现一些奇奇怪怪意想不到的 bug REF #6472)
希望相关 API 提供 `dataType: "plaintext"` 模式, 以在后端将所有的 markdown 标志转义, 实现 `data` 参数中的字符串与渲染后的字符串完全一致

### 描述可能的最优解决方案 Describe the optimal solution

可以参考前端右键菜单 `粘贴转义文本` 的实现

**Comment by 88250** [comment]
那个 issue 已经回复，这里我先关闭了，使用转义应该没有问题才得行。
