### ISSUE TITLE
点击搜索标签出来的搜索项后，视图聚焦到项本身而不是项所在的页面

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#6474]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/35998162/199873292-d39051db-fd37-42f5-ab6d-43e1705dab2e.png)

### 描述可能的最优解决方案 Describe the optimal solution

聚焦到Item本身

**Comment by 88250** [comment]
这个是个段落块，不是列表项块，虽然内容可能一样，但是块类型不一样。
