### ISSUE TITLE
搜索时排除某些笔记

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#6475]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当用笔记给其他人做演示的时候，有时会跨笔记进行一定的搜索（不指定路径的情况下）。
这样会搜索到私人的文档，有时候比较尴尬。
笔记中某些私人文档，不想在全局搜索（不指定路径的情况下）中被检索到。
文档名称和内容都不想参与搜索。

指定路径的时候可以搜索。

### 描述可能的最优解决方案 Describe the optimal solution

是否可以在笔记中增加一个选项，不参与全局搜索？

**Comment by 88250** [comment]
你好，目前不考虑加特性了，可以试下将这些文档单独使用笔记本存放，或者使用其他工作空间以起到隔离作用，感谢提议。
