### ISSUE TITLE
根据最近使用来调整代码块语言选择列表

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#6479]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

<img width="188" alt="image" src="https://user-images.githubusercontent.com/33319484/199951870-c20174a2-50ff-4fa8-9514-74b3ca7df315.png">

如图中所示，如果常用语言是sql，那么可以把sql往上提，打开列表显示的就有十几种语言可选择，减少下拉选择sql等常用语言的次数

### 描述可能的最优解决方案 Describe the optimal solution

根据最近使用的语言，将其提到第一位，原第一位往后移动

**Comment by 88250** [comment]
这个暂时不考虑了，因为语言较多，如果使用了多种语言的话实际上按使用顺序置顶排序最后的结果仍然是需要找半天，不如直接搜索来得快。

另外，如果使用 md 语法输入的话可以直接带上语言 ` ```java ` 然后回车。
