### ISSUE TITLE
两个小特性建议，关于虚拟引用和反向链接

### ISSUE THREAD

**Issue by shimu527** [siyuan-note/siyuan#6482]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

- 关于虚拟引用：当前虚拟引用是可以自动弹出悬浮窗，或点击ctrl后弹出悬浮窗。但悬浮窗有时候过大会很占当前窗口，是否可以在设置的编辑器中，设置快捷键类似于点击alt或shift，可将该虚拟引用的窗口在右侧打开。
- 关于反向链接：反向链接是否可以默认为全展开，或者可以自行设置是否选择全展开

### 描述可能的最优解决方案 Describe the optimal solution

- 关于虚拟引用的建议，可以将虚拟引用的页面与双链页面等同，因为目前双联页面就可以将页面固定住选择右侧打开。
- 关于反向链接的建议，我个人认为反向链接是需要经常去看其中的内容的，可能和我的使用方式有关，但目前每次都需要点一下才能展开。不太清楚目前为什么设为默认半展开，但我个人认为全展开是有很大的应用场景的，故而建议可以有个设置，可以选择全展开或半展开。

**Comment by 88250** [comment]
* 虚拟引用可能存在多个结果，直接打开页签可能不太合理
* 反链只显示必要的上下文，这个应该是和使用方式有关

感谢反馈。

**Comment by shimu527** [comment]
> * 虚拟引用可能存在多个结果，直接打开页签可能不太合理
> * 反链只显示必要的上下文，这个应该是和使用方式有关
> 
> 感谢反馈。

- 可以选择打开虚拟引用的第一个页面，虚拟引用弹出页面是有顺序的，那自然可以选择打开第一个页面，如果页面唯一，自然打开的就是那一个页面，当然这并不作为默认设置，可以在编辑器栏中选择是否打开此功能。
    - 至于为什么请求该功能，其实与后面的希望反链全展开是一个承接使用的方式。
- 反链目前是半展开，即只显示必要的上下文。但我认为至少给予选择空间选择是否全展开，即增加一个选择全展开的设置，可以默认是目前的半展开模式。

**Comment by 88250** [comment]
* 这个不太好，如果加了的话是不是需要加一个设置允许打开几个？这一点上面我觉得不加比较好，因为虚拟引用和提及比较类似，是一种弱关联，发现关联即可，如果真的需要强关联就应该使用引用
* 反链是否要加全展的开关开后面会继续收集反馈

谢谢。

**Comment by shimu527** [comment]
那么是否可以考虑将反向链接嵌入到页面内，可以作为一种设置，默认是当前不在页面内的情况。
事实上这个才是我一开始的想法，只是问了一圈没人知道才想选择将虚拟引用打开为页面，这样可以看到反链

**Comment by 88250** [comment]
你指的是底部显示反链对吧？

**Comment by shimu527** [comment]
> 你指的是底部显示反链对吧？

是的是的

**Comment by 88250** [comment]
这个估计要等 https://github.com/siyuan-note/siyuan/issues/3862 完成后才会考虑。

**Comment by TCOTC** [comment]
第一点需求大约可以通过 #11127 实现：在新页签中打开
