### ISSUE TITLE
v2.4.9 docker运行失败

### ISSUE THREAD

**Issue by pstandard** [siyuan-note/siyuan#6488]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

在centos 7下，运行docker容器显示不断重试，无法成功运行。
 运行命令行：
  docker run  --name siyuan  -it -d   --restart=always -v /root/SiYuan:/home/siyuan/Documents/SiYuan -p 6806:6806  --resident=true --ssl=true --servePath=www.testhost.com

V2.4.9运行失败，经过测试v2.4.0, v2.3.0, v2.2.0均可以正常启动和运行。

### 期待的结果 Expected result

期待修正错误。

### 版本环境 Version environment

```markdown
- Version: v2.4.9
- Operating System: centos 7
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by 88250** [comment]
去掉 --resident 和 --servePath

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/6389
