### ISSUE TITLE
`Ctrl+Shift+V` 调用浏览器原生功能，不再支持配置

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#6489]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

复制markdown图片与音频链接，ctrl+shift+v粘贴

客户端中只会把标注文本贴进去，

但是在浏览器伺服里，表现正常

### 期待的结果 Expected result

跟浏览器端表现一致

**PS：增加一个feature request**

根据附件后缀，自动转换链接。

如`[xxxx](assets/xxxx.mp3)`,自动转换成音频块，而不是目前的链接

![image](https://user-images.githubusercontent.com/19968935/200121687-f4d29133-cfc3-447c-9471-d5dc0f6116c3.png)

如果是mp4，自动转换成视频块

### 截屏或者录屏演示 Screenshot or screen recording presentation

![orbitctrls](https://user-images.githubusercontent.com/19968935/200121618-f01d3361-f8b9-4d9f-b709-b64369afc367.gif)

### 版本环境 Version environment

```markdown
- Version: 2.4.8
- Operating System: win
- Browser (if used): Edge
```

### 日志文件 Log file

不适用

**Comment by 88250** [comment]
> 复制markdown图片与音频链接，ctrl+shift+v粘贴

是 Markdown 语法格式吗？

**Comment by 88250** [comment]
从截图上看复制的是个相对路径，可能是图片文件不存在？这个 `![]` 没有文本，所以不会显示出来。

**Comment by HowcanoeWang** [comment]
> 从截图上看复制的是个相对路径，可能是图片文件不存在？这个 `![]` 没有文本，所以不会显示出来。

相对路径就是assets里面的路径啊，文件是存在的，我预先放进去了

**Comment by Vanessa219** [comment]
鉴于 https://github.com/siyuan-note/siyuan/issues/6460 ，就不自动转换了。
