### ISSUE TITLE
音频块视觉优化

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#6490]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前的音频块使用浏览器内置的样式，能用但是视觉上不太讨喜

![image](https://user-images.githubusercontent.com/19968935/200121965-75039b8a-18a2-4a4a-8831-f52ea5739483.png)

### 描述可能的最优解决方案 Describe the optimal solution

希望能转换成更好看的音频块，比如下面这样：

![image](https://user-images.githubusercontent.com/19968935/200121982-1f0745bb-c59b-444b-8cc0-3939fd06a3be.png)

带名字、带控制(快进后退5s)，音量，播放速度，方便拖动的进度条

**Comment by 88250** [comment]
这个需要引入其他播放器组件，暂时不考虑了，感谢提议。
