### ISSUE TITLE
数据历史每页最后一条记录时间异常

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6491]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

#6455 修复后貌似还是有点问题
现在变成每页最后一条记录和倒数第二条记录时间总是一样的

这是我的变更记录恰好这样还是缺陷😂

### 期待的结果 Expected result

记录时间正常

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

```markdown
- Version: v2.4.10
- Operating System: Windows 11
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
应该是正常的

![image](https://user-images.githubusercontent.com/873584/200172103-04a95678-b704-4b34-b856-d1751c728e33.png)

**Comment by Temacc0531** [comment]
你看你截图的两个时间显示都是一样，而不是正确显示变更的时间
最底下的两个记录时间始终都显示一样的，这是异常所在

比如第二行的`15:29:01`这个记录
![test1](https://user-images.githubusercontent.com/101307399/200210025-86229121-4b05-4aa5-ba2a-dfd7c6aa1b9e.gif)

编辑一次之后，`15:29:01`这个记录应该下移到第三行，而现在是第三行和第四行的记录都被变更了
![test2](https://user-images.githubusercontent.com/101307399/200210035-72682838-35fd-42ac-9c94-c94f8a79f432.gif)

**Comment by 88250** [comment]
后续在 https://github.com/siyuan-note/siyuan/issues/6504 中改进，谢谢。
