### ISSUE TITLE
提议：聚焦到一个折叠内容块时，自动展开

### ISSUE THREAD

**Issue by Oltermare** [siyuan-note/siyuan#6496]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

简述：
目前思源笔记标题和列表都可以折叠，但是如果聚焦到这个折叠的内容时，不能自动展开，还需要手动展开，然后再关闭。希望可以聚焦到折叠的内容时，自动显示展开后的内容，离开聚焦之后，不影响原来折叠的状态。

为什么要折叠，以及为何要聚焦折叠内容：
例如我引用了一个文档，在下方写了很多与这个主题有关内容，但是由于思维的发散性，我不想在浏览时直接看到这些内容，所以把它折叠了起来（或者引用主题很多，导致不折叠就很长）。
而如果浏览时需要查看与这个主题的联系，就可以聚焦到这一部分，从而在界面上专注于这个主题的浏览和编辑。

思源笔记的解决方案：
目前想达到这一效果，只能：拖动这块内容形成新文档，然后在原位置引用这个文档，然而这就需要多进行一步文档的维护，比较麻烦。

### 描述可能的最优解决方案 Describe the optimal solution

Logseq在双链查看方面做得比较细致：
同时点击列表前的小圆点就可以聚焦，思源笔记点击小圆点的功能和段落前的按钮是重复的，也可以考虑改成点击聚焦
![聚焦自动展开.gif](https://s2.loli.net/2022/11/07/fDdLV5i4g8Kxsqv.gif)

### 描述候选的解决方案 Describe the candidate solution

简而言之就是达成在不改变文档结构的情况下，可以在**不显示一部分内容**，和**只显示一部分内容**中快速切换

**Comment by 88250** [comment]
折叠状态目前无法做到分离，以后如果有空会考虑，感谢提议。

**Comment by Oltermare** [comment]
你好，我突然发现原来notion那个主题，里面有自动展开功能，原来不会用都没发现，感觉还是比较实用的

![聚焦自动展开2](https://user-images.githubusercontent.com/64324088/200283650-6c8d6671-8237-413b-b3ca-d79752235608.gif)

**Comment by TCOTC** [comment]
聚焦后折叠展开 #8956
