### ISSUE TITLE
文档树上的文档无法拖动

### ISSUE THREAD

**Issue by Lyn6969** [siyuan-note/siyuan#6497]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

更新了2.4.10之后，像往常一样在文档树里面拖动文件到别的文件夹下，但是发现无法拖动了，是bug了，还是新特性需要设置？

### 期待的结果 Expected result

能跟以前一样拖动文件操作文件数

### 版本环境 Version environment

```markdown
- Version: 2.4.10
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/9949177/siyuan.log)

**Comment by 88250** [comment]
是自定义排序模式吗？

**Comment by Lyn6969** [comment]
> 是自定义排序模式吗？

不是的，按照名称排序。我想把我今天的日记拖到我的周总结里面，之前一直都可以的，今天突然不行了

**Comment by 88250** [comment]
按名称排序的话一直都是不可以拖拽排序的。

**Comment by Lyn6969** [comment]
> 按名称排序的话一直都是不可以拖拽排序的。

不是排序吖，是把一个文件拖到另一个文件上，他会直接变成这个文件的子文件，我刚刚试了切换到自定义排序，也不行啊。

**Comment by Lyn6969** [comment]
> > 按名称排序的话一直都是不可以拖拽排序的。
> 
> 不是排序吖，是把一个文件拖到另一个文件上，他会直接变成这个文件的子文件，我刚刚试了切换到自定义排序，也不行啊。

之前我一直都是这么操作的，把一个文件拖到另外一个文件上面，他自动就进去了，现在都没办法拖动了

**Comment by Lyn6969** [comment]
> > > 按名称排序的话一直都是不可以拖拽排序的。
> > 
> > 
> > 不是排序吖，是把一个文件拖到另一个文件上，他会直接变成这个文件的子文件，我刚刚试了切换到自定义排序，也不行啊。
> 
> 之前我一直都是这么操作的，把一个文件拖到另外一个文件上面，他自动就进去了，现在都没办法拖动了

要不然要移动文件，只能右键一级一级的选，好麻烦啊

**Comment by Vanessa219** [comment]
是这样操作么？没有办法重现
https://user-images.githubusercontent.com/970828/200260637-3512c432-1350-4069-a14b-2899ce603697.mp4

**Comment by Lyn6969** [comment]
> 是这样操作么？没有办法重现
> 
>  QQ20221107-162137-HD.mp4



> 是这样操作么？没有办法重现
> 
>  QQ20221107-162137-HD.mp4

是的，我也录个屏，您稍等

**Comment by Lyn6969** [comment]
https://user-images.githubusercontent.com/42564665/200263981-6ff28186-afa7-4dd8-86ba-a8b4133f62cd.mp4



总是选不中

**Comment by Lyn6969** [comment]
https://user-images.githubusercontent.com/42564665/200264707-0e96276a-1fbf-4a41-b704-b18f3cea1410.mp4

这个带鼠标指针

**Comment by 88250** [comment]
我这里也可以拖动的，你的是默认主题还是？

**Comment by Lyn6969** [comment]
> 我这里也可以拖动的，你的是默认主题还是？

不是默认主题，是dark+,我重启下电脑试一下

**Comment by Lyn6969** [comment]
> 我这里也可以拖动的，你的是默认主题还是？

我换成了默认主题，而且重启了，还是无法拖动。。

**Comment by 88250** [comment]
是否有使用代码片段或者有什么自定义代码影响？

**Comment by Lyn6969** [comment]
> 是否有使用代码片段或者有什么自定义代码影响？

我没有使用代码。我一直在使用store版的siyuan，我刚刚为了确认是不是版本的问题，我升级了我一开始使用的桌面版siyuan到2.4.9版本，我进入2.4.9版本（桌面版）之后拖动是正常的，进入到2.4.10版本（store版）就无法拖动了。

**Comment by Lyn6969** [comment]
> > 是否有使用代码片段或者有什么自定义代码影响？
> 
> 我没有使用代码。我一直在使用store版的siyuan，我刚刚为了确认是不是版本的问题，我升级了我一开始使用的桌面版siyuan到2.4.9版本，我进入2.4.9版本（桌面版）之后拖动是正常的，进入到2.4.10版本（store版）就无法拖动了。

我把我的桌面版siyuan也升级到了2.4.10，同样无法拖动了。

**Comment by 88250** [comment]
再试下重置外观。

**Comment by Lyn6969** [comment]
> 再试下重置外观。

重置过了还是无效，我在我另外一台电脑(win11)上试了一下，是好的。应该是我这个电脑上哪里和这个冲突了。。我再排查一下吧。。

**Comment by 88250** [comment]
好的，我们先关闭了，如果有解决麻烦回帖一下，谢谢。

**Comment by Lyn6969** [comment]
> 好的，我们先关闭了，如果有解决麻烦回帖一下，谢谢。

好的，我刚刚发现，感觉像是软件根本捕捉不到我的长按拖动操作，我在页签那里想要拖动都拖动不了。。。

**Comment by 88250** [comment]
是不是和其他软件冲突了？

**Comment by Lyn6969** [comment]
> 是不是和其他软件冲突了？

在浏览器模式下也是无法拖动，我检查一下。

**Comment by Lyn6969** [comment]
> > 是不是和其他软件冲突了？
> 
> 在浏览器模式下也是无法拖动，我检查一下。

我把能退的软件都退了，还是一样。真的好奇怪。。。所有地方的拖动都没了。。。

**Comment by 88250** [comment]
这就不大清楚了，你看下开发者工具 Console 里面有无报错。

**Comment by Lyn6969** [comment]
> 这就不大清楚了，你看下开发者工具 Console 里面有无报错。

![image](https://user-images.githubusercontent.com/42564665/200340606-79a6c594-dc8c-42ee-b7ab-7269e8a1f54c.png)
这是默认的白主题

**Comment by 88250** [comment]
默认的浅色主题是 daylight，你切换这个试下。

**Comment by Lyn6969** [comment]
> 默认的浅色主题是 daylight，你切换这个试下。
![image](https://user-images.githubusercontent.com/42564665/200342512-0f984730-7f99-437b-a5c8-0d48bc520e74.png)

还是一样的

**Comment by Lyn6969** [comment]
接着用2.4.9了，一切正常，感觉应该还是新增加的代码哪里有问题。。呜呜呜

**Comment by 88250** [comment]
等下个版本再升级看看。

**Comment by Lyn6969** [comment]
好的

**Comment by Lyn6969** [comment]
刚刚更新了2.4.11，问题依然存在。我在链滴发现了两个和我遇到同样问题的人，ru如下图所示
![image](https://user-images.githubusercontent.com/42564665/200561896-eb0baf7d-e994-4dbd-a2e4-af105b39f17a.png)
![image](https://user-images.githubusercontent.com/42564665/200562021-a83e2b06-4fd8-476f-b1c4-23e4d968fb73.png)

**Comment by Vanessa219** [comment]
是不是用了触摸屏？

**Comment by Lyn6969** [comment]
> 是不是用了触摸屏？

没有的，就是普通的win11笔记本。

**Comment by Vanessa219** [comment]
麻烦打开开发者工具，在 Console 里运行以下代码，把结果贴一下。谢谢。
```
console.log("ontouchstart" in window, navigator.maxTouchPoints);
```

**Comment by Lyn6969** [comment]
![image](https://user-images.githubusercontent.com/42564665/200721566-bef5b856-0c51-4f2a-825b-4057cdbb9563.png)
