### ISSUE TITLE
是否考虑文档导出时同时导出子文档

### ISSUE THREAD

**Issue by pokerLL** [siyuan-note/siyuan#6498]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

因为现在笔记很多，我的有一些文档实际上只是使用了ListChildDoc做一个目录用，这个文档下的子文档才是真正的内容，想要有一个导出文档及子文档的功能。

### 描述可能的最优解决方案 Describe the optimal solution

暂无

### 描述候选的解决方案 Describe the candidate solution

暂无

### 其他信息 Other information

暂无

**Comment by 88250** [comment]
目前只有导出 Markdown 时能够支持批量导出，其他格式不支持，感谢反馈。
