### ISSUE TITLE
文档树移除双击操作并优化点击笔记本展开速度

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#6500]
https://ld246.com/article/1667792111012?r=88250

**Comment by EberhardLin** [comment]
请问一下，「移除双击操作」是指以后不能通过双击文档树内的文档块名称来展开文档么？

**Comment by Vanessa219** [comment]
单击就可以展开了，点两下也是展开，效果一样，没必要点两下。

**Comment by EberhardLin** [comment]
> 单击就可以展开了，点两下也是展开，效果一样，没必要点两下。

如果我理解的没错的话，移除的是笔记本的双击操作对么？
文档块依旧能双击展开，而笔记本则移除双击展开的操作，我这么理解对么？

**Comment by 88250** [comment]
@EberhardLin 是的

**Comment by EberhardLin** [comment]
> @EberhardLin 是的

那就好，昨天还写了篇小作文想阐述父子级文档中，文档块的双击展开是多么贴合实际且独具特色的设计，那现在没事了。

**Comment by 88250** [comment]
@EberhardLin 看来无法支持双击展开子文档了，具体请看 https://github.com/siyuan-note/siyuan/issues/6523#issuecomment-1307257047

**Comment by EberhardLin** [comment]
> @EberhardLin 看来无法支持双击展开子文档了，具体请看 [#6523 (comment)](https://github.com/siyuan-note/siyuan/issues/6523#issuecomment-1307257047)

也罢，既然目前如此选择，也只能含泪接受，只求以后能够考虑恢复该特性，或考虑推出类似语雀的“分组”功能，文档树上的交互体验，其实真的很重要，而父子级文档固然是个很优秀的设计，但是还是可以更进一步的。
我好像一直和你们提这个，我也想解释一下。其实我那么重视这一点，很大程度是我经常误触打开文档，也许一两次没什么，多次后就很容易烦躁，即便随着层级展开而扩宽展开按钮，我也总会误触到展开按钮的边边，而展开按钮的边边偏偏不是该按钮的触发范围。
语雀是父子级文档+分组的文档树设计，经常提及不是因为我以前是语雀用户，而是用过它这种设计之后，发现这样既有父子级文档的强大，又没有父子级文档的不便，所以才一直念念不忘。
我以前经常提及另一款产品的设计恐怕有些许不妥，希望海涵。
