### ISSUE TITLE
鼠标移动到空文档名处光标状态改进

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#6503]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

![「思源笔记」请输入文档名光标未变化](https://user-images.githubusercontent.com/98400319/200268472-1143374c-b0a3-4905-bc20-a0c1f42e8fcf.gif)

### 期待的结果 Expected result

移上去应该显示竖线输入的光标。

### 版本环境 Version environment

```markdown
- Version: 2.4.10
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/9949746/system-log.zip)

**Comment by 88250** [comment]
> 移上去应该显示竖线输入的光标。

没看明白，麻烦再补充一下。

**Comment by EberhardLin** [comment]
> > 移上去应该显示竖线输入的光标。
> 
> 没看明白，麻烦再补充一下。

在鼠标移动到「文档名」的时候，光标状态应该是「文本选择」状态，即
![image](https://user-images.githubusercontent.com/98400319/200269770-faf1585a-ace0-4256-a3b5-0289266f95a6.png)
，但却是「正常选择」状态，即
![image](https://user-images.githubusercontent.com/98400319/200269599-947657c7-4cf3-44a0-917d-a543d63561e4.png)
