### ISSUE TITLE
Safari 剪藏插件支持

### ISSUE THREAD

**Issue by W-Mai** [siyuan-note/siyuan#6506]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在Safari浏览器中使用剪藏插件

### 描述可能的最优解决方案 Describe the optimal solution

增加Safari浏览器中的剪藏插件

**Comment by 88250** [comment]
你好，我们目前没有时间精力开发。

如果可能的话，希望有社区开发者可以参与进来，代码可参考 https://github.com/siyuan-note/siyuan-chrome
