### ISSUE TITLE
ipad端开启台前调度，同时使用外置输入（键盘或apple pencil），屏幕下半会变黑

### ISSUE THREAD

**Issue by Miobowl** [siyuan-note/siyuan#6508]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

rt，且关闭台前调度，且重启软件数次后才会恢复正常，暂不清楚恢复正常的条件

### 期待的结果 Expected result

台前调度情况下能正常使用外接键盘（如magic keyboard

### 截屏或者录屏演示 Screenshot or screen recording presentation

![d60be65c81ff122ae56e08319049faa](https://user-images.githubusercontent.com/116620090/200299805-375643e5-571b-4eb9-97d4-11fa9f4365b1.jpg)

### 版本环境 Version environment

```markdown
- Version: 2.4.10
- Operating System: ipad os 16.1
- Browser (if used):
```

### 日志文件 Log file

ipad上无法找到

### 更多信息 More information

logseq似乎也存在同样的情况

**Comment by 88250** [comment]
感谢反馈，目前暂时无法解决，合并到 https://github.com/siyuan-note/siyuan/issues/4238 中后续考虑。
