### ISSUE TITLE
开源数据同步 WebDAV 实现

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6513]
手动配置 工作空间/conf/conf.json 中的 sync.provider 为 3 以及 webdav，参考如下：

```
    "webdav": {
      "endpoint": "https://your-webdav-domain.com/",
      "username": "你的用户名",
      "password": "你的密码"
    }
```

目前该特性处于内测阶段，所以暂时只提供手动修改配置文件的配置方式，等内测稳定以后会在 https://github.com/siyuan-note/siyuan/issues/6446 中提供界面配置给普通用户使用。

**Comment by Zuoqiu-Yingyi** [comment]
测试了一下, 同步时提示: `同步失败：MkdirAll /siyuan/: 409 v2.4.11`

**Comment by AdachiQ** [comment]
坚果云，获取云端信息失败 PROPFIND /siyuan/0/repo/: 409
teracloud，获取云端信息失败 cloud object not found

**Comment by 88250** [comment]
@AdachiQ 坚果云可能需要手动建立一个根目录 siyuan

**Comment by AdachiQ** [comment]
> @AdachiQ 坚果云可能需要手动建立一个根目录 siyuan

错误信息变成 获取云端信息失败 cloud object not found

**Comment by AdachiQ** [comment]
> @AdachiQ 坚果云可能需要手动建立一个根目录 siyuan

搞定了，忘记生成密钥了

**Comment by jl0476** [comment]
https 可否跳过证书校验？

**Comment by 88250** [comment]
@jl0476 目前不行，后续看是否有更多需求。

**Comment by jl0476** [comment]
同步失败：MkdirAll /siyuan/0/repo/main/: 403 v2.4.11

**Comment by 88250** [comment]
@jl0476 服务端需要有创建文件夹的权限

**Comment by jl0476** [comment]
![image](https://user-images.githubusercontent.com/5226690/200599930-7ddde271-e24a-4efa-a886-5b18ebd077f8.png)


> @jl0476 服务端需要有创建文件夹的权限

@88250

**Comment by 88250** [comment]
@jl0476 那可能是服务端其他原因引起的，我不是太确定。

**Comment by jl0476** [comment]
服务端日志中未见异常。
![image](https://user-images.githubusercontent.com/5226690/200601195-c2eb7d5a-e409-467f-96c6-fc43db27ec10.png)

**Comment by 88250** [comment]
这有点奇怪，因为状态码是服务端返回的，可能是因为 403 没有记录日志吧。

**Comment by jl0476** [comment]
![image](https://user-images.githubusercontent.com/5226690/200602747-094e15f1-d1e2-45a1-9ad6-ec828865f619.png)
抓包未见403异常

**Comment by JCJC01** [comment]
> 同步失败：MkdirAll /siyuan/0/repo/main/: 403 v2.4.11
> 
> 群晖nas，我看自动创建了一些目录，不清楚是什么原因不允许创建了

你好，请教一下，我也是群辉同步
在conf设置后？需要如何执行同步？
需要登陆会员好？
需要选择云端空间不？

**Comment by jl0476** [comment]
> > 同步失败：MkdirAll /siyuan/0/repo/main/: 403 v2.4.11
> > 群晖nas，我看自动创建了一些目录，不清楚是什么原因不允许创建了
> 
> 你好，请教一下，我也是群辉同步 在conf设置后？需要如何执行同步？ 需要登陆会员好？ 需要选择云端空间不？

@JCJC01 直接点云图标进行同步

**Comment by JCJC01** [comment]
> > > 同步失败：MkdirAll /siyuan/0/repo/main/: 403 v2.4.11
> > > 群晖nas，我看自动创建了一些目录，不清楚是什么原因不允许创建了
> > 
> > 
> > 你好，请教一下，我也是群辉同步 在conf设置后？需要如何执行同步？ 需要登陆会员好？ 需要选择云端空间不？
> 
> @JCJC01 直接点云图标进行同步

一点，他就弹出来让我登陆会员账号

**Comment by 88250** [comment]
@JCJC01 目前只有会员可以参与内测。

**Comment by jl0476** [comment]
![image](https://user-images.githubusercontent.com/5226690/200603931-1c704f5d-7b1d-4b5a-855c-c0f3b8e047d9.png)
比较奇怪，抓包看返回的是201
![image](https://user-images.githubusercontent.com/5226690/200604094-60701259-de17-4e15-814a-6b19402b7a51.png)
实际目录也创建了

**Comment by JCJC01** [comment]
> @JCJC01 目前只有会员可以参与内测。

我是会员，忠实会员

**Comment by 88250** [comment]
@JCJC01 配置文件要在内核停止以后再改，不然会被覆盖回之前的状态。

**Comment by JCJC01** [comment]
> @JCJC01 配置文件要在内核停止以后再改，不然会被覆盖回之前的状态。

没有覆盖，我特意打开来看过了。
改的时候没有打开思源程序

**Comment by jl0476** [comment]
![Uploading image.png…]()
这是个什么方法，我看抓包里有这个405.
笔记端可以保存日志供调试吗？

MKCOL /siyuan/0/repo/main/objects/8d/ HTTP/1.1
Host: 
User-Agent: Go-http-client/1.1
Authorization: 
Accept-Encoding: gzip

HTTP/1.1 405 Method Not Allowed
Date: Tue, 08 Nov 2022 15:18:15 GMT
Server: Apache
Allow: 
Content-Length: 222
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method MKCOL is not allowed for this URL.</p>
</body></html>

**Comment by 88250** [comment]
@jl0476 这个是创建目录，你看下是不是 `/siyuan/0/repo/main/objects/8d` 已经有文件而不是目录。

**Comment by jl0476** [comment]
![image](https://user-images.githubusercontent.com/5226690/200607047-5e72ff33-ec74-446a-beeb-efcb6a105cc6.png)
8d 是一个文件夹 
@88250

**Comment by jl0476** [comment]
![image](https://user-images.githubusercontent.com/5226690/200607185-056bbd77-299a-4df9-89b4-3f2a2a5ce129.png)
里面还有上传的数据块  @88250

**Comment by 88250** [comment]
@jl0476 看上去正常，那不应该返回 405 才对，我估计是服务端对并发操作可能支持有点问题。

**Comment by jl0476** [comment]
发现了个情况，为什么先get已经成功了还要创建这个目录，目录已经存在，所以返回405了。
![image](https://user-images.githubusercontent.com/5226690/200609145-6ae872f2-aecb-4333-b6bb-40f1f9c893f6.png)

**Comment by 88250** [comment]
@jl0476 这里是因为在 put 前不确定是否有目录，所以每次 put 前都会 mkdir，这里应该先 用 stat 看一下是否存才目录，不存在再创建可能更好一些。目前的实现是直接 mkdir，主要考虑到少一次 stat 接口调用，看来不能省。

另外，WebDAV 并发请求估计也有问题，上面的这个场景就是只能等目录确定创建以后再上传，不能并发提交请求，这两个问题我们下个版本改进一下，感谢反馈。

**Comment by jl0476** [comment]
@88250 辛苦了，如果需要测试可以联系我。

我觉得可能是自动同步和手动同步有一定的冲突，但是抓包的时候未见403异常。
后续可能全量同步完了之后，也未见403异常。

405这个异常应该不影响同步，不抓包也很难发现。

**Comment by 88250** [comment]
@jl0476 好的，后续我们会在 GitHub Releases 上打一个 dev 包，有空的话请帮忙测试看看，谢谢。

**Comment by jl0476** [comment]
@88250 今天测试了docker版本，发现无法保存conf文件，容器启动后会覆盖掉配置。

配置的时候容器已经停止，siyuan目录映射在本地。

**Comment by 88250** [comment]
帮忙试下该其他配置项，比如 sync.enabled 是否有效。

**Comment by jl0476** [comment]
@88250 sorry 我的锅  配置没保存上

**Comment by jl0476** [comment]
> @jl0476 Docker 版目前还是 v2.4.11 正式版，估计和昨天使用桌面端测试一样的问题，等会麻烦用 https://github.com/siyuan-note/siyuan/releases/tag/v2.4.12-dev1 这个桌面端测试看看。

@88250 稍晚点哈，事情有点多。

**Comment by 88250** [comment]
@jl0476 好的，谢谢。

**Comment by jl0476** [comment]
@@88250 
![image](https://user-images.githubusercontent.com/5226690/200726165-f3817567-9512-46d8-810e-62f5770c63f8.png)
还是有

**Comment by caogle** [comment]
> ![image](https://user-images.githubusercontent.com/5226690/200602747-094e15f1-d1e2-45a1-9ad6-ec828865f619.png) 抓包未见403异常
顶层目录写权限不够，改一下就好了

**Comment by jl0476** [comment]
> > @jl0476 Docker 版目前还是 v2.4.11 正式版，估计和昨天使用桌面端测试一样的问题，等会麻烦用 https://github.com/siyuan-note/siyuan/releases/tag/v2.4.12-dev1 这个桌面端测试看看。
> 
> @88250 稍晚点哈，事情有点多。

@88250 全量同步测试了，没有403报错了。不过现在第一次的同步速度下降了。315M的数据仓库，内网大概需要15分钟左右。

405异常还是有，见之前回复。

**Comment by 88250** [comment]
@jl0476 405 的问题稍后修复，感谢反馈。WebDAV 的上传性能估计就只能是这样了，由于无法确定服务端是否支持并发操作，所以只能使用单线程上传。

**Comment by jl0476** [comment]
> @jl0476 405 的问题稍后修复，感谢反馈。WebDAV 的上传性能估计就只能是这样了，由于无法确定服务端是否支持并发操作，所以只能使用单线程上传。

可以考虑分文件夹进行并发，不过逻辑比较复杂。

**Comment by 88250** [comment]
@jl0476 先记录 https://github.com/siyuan-note/siyuan/issues/6535 估计可以通过缓存解决一部分问题

**Comment by JCJC01** [comment]
原来昨天忘了把provide改了3
现在同步成功了
但是https地址不成名，http地址成功
请问，如果是s3，provide也是3吗？

**Comment by 88250** [comment]
@JCJC01 S3 请等下个版本发布以后再测试。

**Comment by JCJC01** [comment]
> > @jl0476 405 的问题稍后修复，感谢反馈。WebDAV 的上传性能估计就只能是这样了，由于无法确定服务端是否支持并发操作，所以只能使用单线程上传。
> 
> 可以考虑分文件夹进行并发，不过逻辑比较复杂。

我这边内网测试速度还好，1G的内容10分钟不到就同步完了。

**Comment by JCJC01** [comment]
@88250 请问D大，我想用pc的思源的同步到nas的floder a，然后nas docker个思源，data路径也是设置floder a，
有个问题，好像他们的floder的样式是否不一样？
这样是否不能pc和 docker的数据保持一致？

**Comment by JCJC01** [comment]
@88250 请问D大，我想用pc的思源的同步到nas的floder a，然后nas docker个思源，data路径也是设置floder a，
有个问题，好像他们的floder的样式是否不一样？
这样是否不能pc和 docker的数据保持一致？

**Comment by 88250** [comment]
@JCJC01 你试下看看，我不太清楚。

**Comment by JCJC01** [comment]
pc webdav同步过来都是很散的文件夹，00，0a，0b，之类的200多个。
到正常的是data conf temp等常规文件夹

**Comment by 88250** [comment]
数据仓库是 repo 文件夹
