### ISSUE TITLE
优化提示信息位置

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#6516]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

提示在右上角比较小。
写笔记的时候注意力一般在页面中间，右上角的提示较易忽视。

![image](https://user-images.githubusercontent.com/16383685/200464286-ed5ff1ed-64ef-4de1-8d08-cbd13af3aecc.png)

### 描述可能的最优解决方案 Describe the optimal solution

提示应该在醒目且容易注意到的地方，要不这个提示是没有意义的。
推荐在中间进行提示。
如果是重要升级那种的提示，应该要带确认按钮的，而不是右上角一段时间自动消失，那样没有达到提示预期的效果。

**Comment by GH-W94** [comment]
或者可以设立一个消息按钮，将消息都存到里面，这样错过的消息或者一闪而过没看清的消息都能重复看了

**Comment by Soltus** [comment]
参考 Sofill- 主题的样式 https://github.com/Hi-Windom/winsay/blob/main/style/Popup-Message.css

**Comment by woniuxia** [comment]
@Vanessa219 V大，应该是不仅仅优化 / 的提升信息，与之类似的都需要优化下。
方便发下成果图示吗？

**Comment by 88250** [comment]
@woniuxia 还有哪些地方麻烦一并提出，谢谢。
