### ISSUE TITLE
类似文件资源管理器或Vscode编辑器的面包屑

### ISSUE THREAD

**Issue by mingyong-g** [siyuan-note/siyuan#6517]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

- 当打开的文档层级较深时，希望能通过面包屑路径快速返回文档的父级，祖先级

### 描述可能的最优解决方案 Describe the optimal solution

- 类似文件资源管理器的路径导航
- 类似vscode 的路径导航以及文档内部的路径导航

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3007
