### ISSUE TITLE
docker版本，使用时通过网页使用，pdf文件无法打开，按打开会进行下载

### ISSUE THREAD

**Issue by flyingnight** [siyuan-note/siyuan#6518]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

docker版本，使用时通过网页使用，pdf文件无法打开，按打开会进行下载

### 期待的结果 Expected result

希望可以在网页端直接打开pdf页面

### 版本环境 Version environment

```markdown
- Version: v2.4.10
- Operating System: docker
- Browser (if used):
```

### 日志文件 Log file

无需

**Comment by 88250** [comment]
不确定是不是浏览器设置的问题，我这里正常。

![issue](https://user-images.githubusercontent.com/873584/200493194-de352e23-b81b-489a-ae1b-3018debf4626.gif)

我们先关闭了，如果后续还有其他用户类似反馈再重新打开，谢谢。

**Comment by Franklin-Jiang** [comment]
遇到了相同的问题，我是通过 nginx 反向代理配好了 SSL 之后通过 https://siyuan.example.com 访问，PDF 文件无法显示——
![image](https://github.com/siyuan-note/siyuan/assets/23376352/1a672db8-6f9d-4f94-8b42-f47ccc0c2504)

控制台报错如下：
![image](https://github.com/siyuan-note/siyuan/assets/23376352/f469be66-a103-4ca9-9585-27074b517429)

但如果点击链接跳转则可以打开：
![image](https://github.com/siyuan-note/siyuan/assets/23376352/14d57f1d-ab9e-4bbf-95eb-43cb6acde206)

如果通过端口直接访问不经过反向代理也可以打开：
![image](https://github.com/siyuan-note/siyuan/assets/23376352/3435451b-99ac-4e07-a082-586bab85f38b)

请问这种问题如何解决？感谢！

**Comment by Franklin-Jiang** [comment]
我通过在 nginx 配置文件中加入如下内容消除了加载 PDF 时的 `500 Internal Server Error` 报错
```
proxy_set_header If-Modified-Since "";
proxy_set_header If-None-Match "";
```
