### ISSUE TITLE
PDF导出不全

### ISSUE THREAD

**Issue by SurpriseLon** [siyuan-note/siyuan#6519]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 描述问题 Describe the problem

我写了很长的笔记，结果只能导出第一页
![image](https://user-images.githubusercontent.com/56680662/200491297-36529593-a30d-42ba-8824-4a89adacacd9.png)
比如说一段H1写完了，下面新的H1开始
![image](https://user-images.githubusercontent.com/56680662/200491449-06306f1c-7477-43a1-8735-3c531eb0c155.png)
结果只能导出一页，正好到H1结束

### 期待的结果 Expected result

PDF能全部导出

### 版本环境 Version environment

```markdown
- Version: 2.4.10
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
请在默认主题下测试看看。

**Comment by SurpriseLon** [comment]
> 请在默认主题下测试看看。

试过了，切换到默认主题daylight也是只能导出一页，而且我测试了一下用html(siyuan)导出也是只能导出一页
只有word和markdown才能全部导出

**Comment by 88250** [comment]
请导出 .sy.zip 发给我们测试看看 845765@qq.com

**Comment by SurpriseLon** [comment]
> 请导出 .sy.zip 发给我们测试看看 [845765@qq.com](mailto:845765@qq.com)

问题解决了，不知道什么时候在最后插入了一个html段，删掉之后就能全部导出了
