### ISSUE TITLE
assets 资源文件支持改进

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#652]
* 支持更多类型的 assets 资源文件
* 文件树上新增
  - [x] 使用默认应用打开
* 编辑器内新增
  - [x] 在新页签中打开
  - [x] 打开文件位置
  - [x] 定位到文件树
  - [ ] 使用默认应用打开

https://ld246.com/article/1607179116179

**Comment by zzzzzzzs** [comment]
assets 是否支持与当前文档名字相同。例如往思源笔记中黏贴图片，会自动的创建一个与当前文档名字一样的文件保存图片。

**Comment by 88250** [comment]
@zzzzzzzs 需要用 ID 前缀，避免重名。
