### ISSUE TITLE
改进 WebDAV 数据同步实现

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6525]
https://github.com/siyuan-note/siyuan/issues/6513#issuecomment-1307428785

**Comment by jl0476** [comment]
405开始拦截了？

![image](https://user-images.githubusercontent.com/5226690/201024072-4877bdcb-7fb0-46a4-8fa3-5aeafbab6cf7.png)

**Comment by 88250** [comment]
麻烦导出日志上传一下。

**Comment by jl0476** [comment]
[system-log.zip](https://github.com/siyuan-note/siyuan/files/9978250/system-log.zip)

请查收。

**Comment by 88250** [comment]
手动建立文件夹了吗？现在的文件夹结构和之前版本不太一样了。

**Comment by 88250** [comment]
WebDAV 服务端建好根目录以后，在设置 - 同步 - 云端目录里面应该可以选择到。

**Comment by jl0476** [comment]
> 手动建立文件夹了吗？现在的文件夹结构和之前版本不太一样了。

什么都没动，之前同步的好好的。就升级了个思源版本。

**Comment by 88250** [comment]
重新设置一下看看，目录结构做了调整。

**Comment by jl0476** [comment]
> 重新设置一下看看，目录结构做了调整。

是说更换一个webdav目录，然后重新全量同步？

**Comment by 88250** [comment]
是的

**Comment by jl0476** [comment]
315M 半小时还没全量同步上去，比之前慢了。

**Comment by jl0476** [comment]
放弃了，改用minio了。

**Comment by jl0476** [comment]
> 是的

这版本的数据仓库占用小了40%
之前315M 现在185M
但是同步时间增长了1.5倍左右
现在全量同步完成需要41分钟
![image](https://user-images.githubusercontent.com/5226690/201074786-8c4c99cf-0038-471f-a4e0-4b858977c044.png)

**Comment by 88250** [comment]
我看另一个用户说挺快的 😂

**Comment by 88250** [comment]
https://ld246.com/article/1668078995573

是有点问题，下个版本再改改看。

**Comment by JCJC01** [comment]
> 我看另一个用户说挺快的 😂

1.02g，366秒，内网同步，设备群晖自带的webdav套件

**Comment by 88250** [comment]
后续增量同步有问题，下个版本会修复。

**Comment by jl0476** [comment]
> > 我看另一个用户说挺快的 😂
> 
> 1.02g，366秒，内网同步，设备群晖自带的webdav套件

我也是内网同步，群晖自带的webdav套件，不知道咱俩差距为啥这么大😂

**Comment by JCJC01** [comment]
请问，安装了2.4.12的，修改了conf的
现在安装了2.15，需要对conf还原吗？

**Comment by 88250** [comment]
@JCJC01 应该不需要，最好以实测为准。

**Comment by JCJC01** [comment]
> @JCJC01 应该不需要，最好以实测为准。

不用，图形界面直接反馈到之前conf的设置。
