### ISSUE TITLE
关于优化代码块显示的一点小建议

### ISSUE THREAD

**Issue by wanghuiyt** [siyuan-note/siyuan#6527]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在代码块中，一个 "tab" 和 "4 个空格" 的长度不一致(如附件中显示)，希望可以优化一下.

##### 版本环境
- Version: v2.4.10 docker 版本
- Operating System: Ubuntu 22.10
- Browser (if used): Chrome 106.0.5249.119 (正式版本) （64 位）

### 描述可能的最优解决方案 Describe the optimal solution

希望可以让它们长度一致

### 其他信息 Other information

![width](https://user-images.githubusercontent.com/25444996/200713457-9ead5ac4-8a4f-4f9e-af30-88c0ee0c45ab.png)

**Comment by Vanessa219** [comment]
代码块没有办法进行格式化，tab 是在输入的时候根据设置进行对应的替换。
