### ISSUE TITLE
数据同步接入 S3 协议兼容的对象存储服务

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6528]
欢迎使用我们的推广链接开通阿里云 OSS：https://www.aliyun.com/product/oss?userCode=yqovuas2

手动配置 工作空间/conf/conf.json 中的 sync.provider 为 2 以及 s3，参考如下：

```
    "s3": {
      "endpoint": "Bucket 对应的 Endpoint（地域节点）",
      "accessKey": "你的阿里云账号 AccessKey ID",
      "secretKey": "你的阿里云账号 AccessKey ID 对应的 Secret",
      "bucket": "你的 Bucket 名称",
      "region": "地域节点名称，对于 Endpoint 的二级域名，比如 oss-cn-hangzhou"
    }
```

阿里云的 region 参考 https://help.aliyun.com/document_detail/31837.htm
七牛云的 region 参考 https://developer.qiniu.com/kodo/4088/s3-access-domainname

目前该特性处于内测阶段，所以暂时只提供手动修改配置文件的配置方式，等内测稳定以后会在 https://github.com/siyuan-note/siyuan/issues/6426 中提供界面配置给普通用户使用。

之前的七牛云实现也一并改为 S3 SDK 对接 https://github.com/siyuan-note/siyuan/issues/6445

**Comment by Soltus** [comment]
希望增加腾讯云 COS

**Comment by 88250** [comment]
@Soltus 腾讯云兼容 S3 协议的话应该可以。

**Comment by 88250** [comment]
测试了一下，阿里云 OSS 可以并入 S3 实现里面，就不单独实现了。

**Comment by jl0476** [comment]
minio的情况，
bucket参数无效，设置了siyuan，调用的时候还是用的repo

**Comment by jl0476** [comment]
![image](https://user-images.githubusercontent.com/5226690/201046619-c5b2d5be-8fba-436a-bb36-7b3daf210d43.png)
抓包如图，建了一个repo的bucket，可以正常同步。

**Comment by jl0476** [comment]
s3是不是有两种请求风格，minio用的应该是path风格的
![image](https://user-images.githubusercontent.com/5226690/201048234-44aa0c57-5a82-4260-8065-31304d9003b7.png)

**Comment by 88250** [comment]
这个我不太清楚哦，两种都试一下看看。

**Comment by jl0476** [comment]
这么说吧，比如在参数里配置的bucket名称 是aaa，现在思源是采用virtual-host Style方式：
http://aaa.s3-cn-south-1.qiniucs.com/**repo**/xxx

但是minio可以用的是path方式，
应该是：http://s3-cn-south-1.qiniucs.com/aaa/repo/xxx

于是现在配置的bucket参数就不起作用了，minio识别的bucket是 repo

**Comment by 88250** [comment]
看下这里是不是有帮助 https://stackoverflow.com/questions/59693471/how-to-setup-minio-server-to-use-virtual-hosted-style

**Comment by jl0476** [comment]
> 看下这里是不是有帮助 https://stackoverflow.com/questions/59693471/how-to-setup-minio-server-to-use-virtual-hosted-style

好的 我也在搜索解决方案，感谢。

**Comment by jl0476** [comment]
> 看下这里是不是有帮助 https://stackoverflow.com/questions/59693471/how-to-setup-minio-server-to-use-virtual-hosted-style

好用。

**Comment by JCJC01** [comment]
我用joplin同步minio成功，但是思源一直提示找不到桶。问了minio团队，说是选path

**Comment by jl0476** [comment]
> 看下这里是不是有帮助 https://stackoverflow.com/questions/59693471/how-to-setup-minio-server-to-use-virtual-hosted-style



> 我用joplin同步minio成功，但是思源一直提示找不到桶。问了minio团队，说是选path

@JCJC01 两种解决方法，如果不改minio 就建一个名称为repo的bucket
不然就看下stackoverflow的 增加 MINIO_DOMAIN参数

**Comment by jl0476** [comment]
@88250 看看是不是把minio单独配置的写到版本介绍中，这样大家就不用问了。

**Comment by JCJC01** [comment]
> > 看下这里是不是有帮助 https://stackoverflow.com/questions/59693471/how-to-setup-minio-server-to-use-virtual-hosted-style
> 
> > 我用joplin同步minio成功，但是思源一直提示找不到桶。问了minio团队，说是选path
> 
> @JCJC01 两种解决方法，如果不改minio 就建一个名称为repo的bucket 不然就看下stackoverflow的 增加 MINIO_DOMAIN参数

我放弃minio了，直接用群晖的webdav同步更快，不用docker多一个minio感觉更稳定。而且我用joplin测试了minio，好像同步成功后还是有bug，时不时提示错误？你能docker minio，还不如docker个webdav更好

**Comment by Zuoqiu-Yingyi** [comment]
那我在这贴一个使用 Nginx 反代 Docker 部署的 MinIO OSS 服务的配置:

## Docker 容器运行命令Administrator
```bash
docker run \
   --detach \
   --name minio \
   --restart=unless-stopped \
   -p 9000:9000 \
   -p 9090:9090 \
   -v /data/minio/data:/data \
   -e "MINIO_DOMAIN=domain.name" \
   -e "MINIO_ROOT_USER=username" \
   -e "MINIO_ROOT_PASSWORD=password" \
   quay.io/minio/minio server /data --console-address ":9090"
```

## MinIO 配置
1. <kbd>User</kbd> > <kbd>Buckets</kbd> 新建一个名为 `your-bucket-name` 的 bucket
2. <kbd>User</kbd> > <kbd>Access Keys</kbd> 生成一组 Access Keys
   - `Access Key`: `123456`
   - `Secret Key`: `abcdef`
4. <kbd>Administrator</kbd> > <kbd>Settings</kbd> > <kbd>Region</kbd> 设置 Region
   - `Server Location`: `example-region-name`

## Nginx 配置

### 站点配置片段 (二选一)
```Nginx
# 设置为默认站点
listen 80 default_server;
listen 443 ssl http2 default_server;
server_name endpoint.domain.name;
```
---
```Nginx
# 或者直接设置子域名站点
listen 80;
listen 443 ssl http2;
server_name your-bucket-name.endpoint.domain.name;
```

### 反向代理配置
```Nginx
location ^~ /
{
    proxy_pass http://localhost:9000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}
```

## 思源 conf.json 设置

```json
"provider": 2,
"s3": {
  "endpoint": "https://endpoint.domain.name/",
  "accessKey": "123456",
  "secretKey": "abcdef",
  "bucket": "your-bucket-name",
  "region": "example-region-name"
},
```

**Comment by JCJC01** [comment]
应该是地址那一栏有坑。
joplin有个强制路径配置的按钮才设置成功

**Comment by JCJC01** [comment]
应该是地址那一栏有坑。还有端口需要9000，
joplin有个强制路径配置的按钮才设置成功

**Comment by Zuoqiu-Yingyi** [comment]
> s3是不是有两种请求风格，minio用的应该是path风格的
> ![image](https://user-images.githubusercontent.com/5226690/201048234-44aa0c57-5a82-4260-8065-31304d9003b7.png)

@88250 要不要添加一个参数设置 URL 风格的样式？

**Comment by Zuoqiu-Yingyi** [comment]
> @Zuoqiu-Yingyi 不太确定…… 以七牛云为例的话 SDK 这里的配置是这样的 
> 
> ![image](https://user-images.githubusercontent.com/873584/201452490-b196cd3d-96e1-45dd-9a09-d73aa32a3c9d.png)
> 

aws-sdk-go 里面 S3 会话有个 `S3ForcePathStyle` bool 字段设置是否启用 path 样式

**Comment by 88250** [comment]
好的，等会我们加一下吧。
