### ISSUE TITLE
选中一个文档时，点击另一个文档的块菜单会导致那个文档给滚动回最顶端

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#653]
### 描述问题 Describe the problem

选中一个文档时，点击另一个文档的块菜单会导致那个文档给滚动回最顶端

### 期待的结果 Expected result

页面应保持在原位置

### 截屏或录像 Screenshot or video

![bug4](https://user-images.githubusercontent.com/30611816/101274868-9362f180-37dc-11eb-98e8-03390d53f380.gif)

### 版本环境 Version environment

* 版本 Version：0.5.1

**Comment by 88250** [comment]
目前的版本应该已经修复，谢谢反馈。
