### ISSUE TITLE
添加上下移动块的快捷键

### ISSUE THREAD

**Issue by FrostMiKu** [siyuan-note/siyuan#6537]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在做列表，特别是todo list的时候会有优先排序的需求。（当然其他场景也可以使用，如段落重新排序）
现有的拖动要求鼠标精确地操作，效率较低。
如果有个快捷键可以将当前 block 上下移动，会很方便

### 描述可能的最优解决方案 Describe the optimal solution

嗯，就像是 vscode 里的 alt+↑ 或者 idea 里的 alt+shift+↑

### 描述候选的解决方案 Describe the candidate solution

目前我看 alt+↑ 还没有被占用

### 其他信息 Other information

类似 IDE 里有的 将当前行代码上下移动

**Comment by Vanessa219** [comment]
试一下 `Ctrl+Shift+↑`

**Comment by FrostMiKu** [comment]
这个似乎是带着子块一起移动的，抱歉我没有描述清楚，我是指那种上下交换的，嗯...比如：
- a
  - b

交换后

- b
  - a

**Comment by Vanessa219** [comment]
抱歉，没有交换的功能。
