### ISSUE TITLE
文档默认只读模式双击页面切换编辑模式

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6538]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

原作者提议：https://ld246.com/article/1668061388800

但我不是很建议再加快捷键，现在的快捷键已经非常多了，也很难记

### 描述可能的最优解决方案 Describe the optimal solution

我比较赞同作者提到的文档默认是只读模式，双击页面切换到编辑模式

这样也可以顺带解决现在的只读/编辑模式是全局设置不分文档的问题

**Comment by 88250** [comment]
在编辑模式下是无法通过双击切换回只读模式的，这个设计似乎不大合理。

**Comment by Temacc0531** [comment]
细想了一下这个模式切换还是要放到文档一级比较符合使用习惯

打开A文档，默认模式是只读模式，用户双击切换成编辑模式开始编辑，不需要支持双击切换成只读模式，但是用户可以手动点击图标再次切换，文档关闭也恢复成只读模式

A文档的状态不会影响B文档状态

**Comment by 88250** [comment]
单文档的编辑状态暂时不考虑，这个还是暂时不考虑了，等继续再收集更多反馈再考虑，我关闭了，谢谢。

**Comment by terwer** [comment]
我认为这个不加为好，单文档有的能编辑有的不能这样很混乱。

使用者应该提倡简单模式，而不是需要额外的记忆。因为文档一多，你很可能忘记了那一片是只读的，那一批不是，这样反而增加了误操作的可能性。

目前的全局开关应该是最简洁的了，不需要额外成本。
