### ISSUE TITLE
更新后首次打开展示更新日志

### ISSUE THREAD

**Issue by yuyuyu-github** [siyuan-note/siyuan#6541]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在支持自动下载更新以后，更新过程无感了，但是全程都看不到更新的相关信息

除非用户主动去github或者官网查看。但每次更新都主动去查看的人肯定是少数。

大部分人可能就是知道在更新，但是不知道更新了什么，反正继续接着用（我就是这样(。・ω・。)）

### 描述可能的最优解决方案 Describe the optimal solution

在更新以后，首次打开软件，展示更新日志。（一般app在更新前/后都会在应用内显示更新日志的）

**Comment by Soltus** [comment]
支持，像VSCode和VS那样

**Comment by AugustTuan** [comment]
> 有新版本的话自动下载时会有通知提示到社区查看发版公告的，软件内就不做版本变更的详细展现了。

思源在官网的更新公告的浏览量基本都超不过2k，就算思源只有2万的用户，那也就是有超过90%的人，根本不会去点击链接查看更新日志。

这是一个很吊诡的现象，因为更新日志这个东西，应该是用户每次更新被动接收的信息，而不是藏着让用户主动去查。 
这也是为什么大部分的应用更新后，都会主动把更新日志展示给用户查阅，而不是放一个链接

![image](https://user-images.githubusercontent.com/117956441/201237373-5dc45ecc-33aa-490f-a4ea-9c7a72647206.png)

**Comment by AugustTuan** [comment]
而且在右上角展示一个链接，一般人正在记笔记，都是直接勾选掉，不会中断自己记笔记的流程，去点进去。
![image](https://user-images.githubusercontent.com/117956441/201238220-7b6748fb-24a6-4013-a8b8-d240717b5b33.png)

就算是为了给论坛引流，而不在应用内放置更新日志。
这样给一条没有上下文的链接的方式，真的不如把更新日志概览展示出来，然后在旁边附上链接，可能更能吸引用户点击链接查看。
![image](https://user-images.githubusercontent.com/117956441/201238380-e9ce3e24-aa2c-4750-8965-b35d29a2012b.png)


![image](https://user-images.githubusercontent.com/117956441/201238103-a775f9a0-5c84-446b-a715-31dd2937f4f2.png)
