### ISSUE TITLE
坚果云webdav同步问题

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6543]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

坚果云webdav有请求频率限制，每30分钟只能上传一部分数据，然后报错 cloud service unavailable。经过多次上传后，似乎数据已经上传完成（坚果云的文件不再新增了），但是每次点击同步按钮似乎都要重新请求很多次，导致每次都会报错。

### 期待的结果 Expected result

略。

### 版本环境 Version environment

```markdown
- Version: 2.4.12
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

略。

**Comment by 88250** [comment]
这个没有办法解决，是坚果云 WebDAV 的接口限制。
