### ISSUE TITLE
有序列表优化

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#6545]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前有序列表只支持1. 2. 3. 的形式。层级较多的情况下没有区分度。

### 描述可能的最优解决方案 Describe the optimal solution

优化展示效果。
例如：
1.
 1.1
 1.2
2.
 2.1
 2.2
 2.3

### 描述候选的解决方案 Describe the candidate solution

或添加 ⅠⅡⅢ/a b c 这种形式。并提供转换功能，如下图。
![image](https://user-images.githubusercontent.com/16383685/201246419-a5850407-c610-4ac6-a58e-8443ba27e90f.png)

**Comment by 88250** [comment]
暂时不引入新特性了，目前可考虑通过自定义主题实现，感谢提议。
