### ISSUE TITLE
[feature request]根据id预览文档

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#6547]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

这个地方只能预览引用块 ,能否改进以下,使其能预览文档,通过传入id? 
https://github.com/siyuan-note/siyuan/blob/8a4d4ab3c9535b988255cda5e9a0b6d1f822fc6d/app/src/protyle/wysiwyg/keydown.ts#L1566-L1571

### 描述可能的最优解决方案 Describe the optimal solution

1

**Comment by Vanessa219** [comment]
nodesIds 传入文档 id 应该就可以了。

**Comment by iamqiz** [comment]
targetElement传入null被报错

**Comment by Vanessa219** [comment]
悬浮窗需要有一个目标，不然的话就不知道定位了。

**Comment by iamqiz** [comment]
默认居中呢?像ctrl+P那样

**Comment by Vanessa219** [comment]
可以说一下使用场景么？
这个还存在鼠标移除消失，固定，悬浮层内再弹出悬浮等场景，混淆的比较多。如果场景明确的话，可以重新提供一个接口。

**Comment by iamqiz** [comment]
是这样的: 我利用flomo来记临时笔记,但是它的win端没有全局快捷键来弹出小窗,很难受,而且它也是基于electron的,所以我就想干脆让思源实现按下一个全局快捷键,然后弹出特定文档让我记笔记,全局快捷键解决了(globalShortcut.register+ mainWindow.webContents.send),打开文档有两种选择,每种选择都有不足之处: 
1.右侧打开,我调用的是
```
                openFileById({
                    id: 文档id,
                    position: "right",
                    action: [Constants.CB_GET_FOCUS ]
                })
```
但有个问题: 如果我已经在右侧打开了这个文档,焦点也在右侧窗口(第2列),再次调用,就产生第三列(个)窗口,该文档会在该窗口打开,造成多余,我希望的是总是在第二列窗口打开,即如果只有1列窗口,则新建并在第2列窗口打开文档,如果有2列或以上窗口,则始终在第2列窗口中打开,也就是希望openFileById的position参数支持"0" "1"这样的参数,来在绝对位置窗口打开新文档

2. 浮窗打开, 好处是编辑区域很宽,不影响当前编辑的文本,缺点是它和思源主窗口绑定,主窗口隐藏,浮窗也会隐藏,
浮窗部分的代码我没怎么研究,不知道怎么只根据id来打开,还有不知道怎么让它持续显示,只在按下X按钮或esc才关闭

3.我理想的是这样的:
有个独立显示的siyuan子窗口(浮窗),和主窗口独立,也支持多页签,但更简洁,没有文档树这些东西,
有全局快捷键可以触发显示和隐藏,弹出之后可以通过快捷键和按钮触发置顶|取消置顶,ctrl+tab切换页签,像浏览器那样,  
这样的话感觉能部分取代滴答清单和flomo了,😁
另外全局快捷键触发时可以配置参数, 无参情况直接打开上面的浮窗,有参情况下可以先打开一个菜单,菜单里可以有"打开" "新建日记" "新建小记" 等选项, enter之后再打开浮窗,并根据用户选择的选项决定是否新建日记或小记等 😁

**Comment by Vanessa219** [comment]
这个不用右侧打开，直接在当前页签打开更加方便吧。
对于第二点的场景，那不适合修改这个方法，可能需要重新写一个，但写出来对这种场景也不太方便。可能还是新开子窗口比较好。但估计要先弄 https://github.com/siyuan-note/siyuan/issues/2955 这个。

那我就先关闭这个 issue 了。

**Comment by iamqiz** [comment]
@Vanessa219  V姐,openFileById怎么打开文档,并跳到第一个块?  我在action里加了 Constants.CB_GET_FOCUS,
Constants.CB_GET_FOCUSFIRST,
Constants.CB_GET_SCROLL,   
都没效果

**Comment by Vanessa219** [comment]
参看打开文档调用的方法试试
<img width="595" alt="image" src="https://user-images.githubusercontent.com/970828/205103429-2535061b-6324-47ad-a405-697193c2160f.png">

**Comment by iamqiz** [comment]
加上cb-get-focus 和cb-get-scroll  就可以了吗?

**Comment by Vanessa219** [comment]
试试看

**Comment by iamqiz** [comment]
@Vanessa219  原来这个功能被砍掉了 
我根据这个
https://github.com/siyuan-note/siyuan/commit/68beb1f5195f5fa1e928ad0a177f5cc6e41b19e4
把代码还原回来 解决了
不过只能在tab已经打开情况下切换到文档时(switchEditor)生效
如果是新打开文档, 不行, 
我试了修改
https://github.com/siyuan-note/siyuan/blob/b542a80f56eb01e99894dfbb74781754ad12c521/app/src/editor/util.ts#L150
为下面的,也不行
```js
                        let newtab=newTab(options);
                        targetWnd.addTab(newtab);
                        if (newtab.model && newtab.model instanceof Editor ) {
                       
                            switchEditor(newtab.model, options, allModels);
                        }
```

希望V姐增加一个options.action选项使这两种情况都能跳到第一个块 😄

**Comment by Vanessa219** [comment]
已打开的文档只是会进行切换，你这个的使用场景是？不行的话可以看一下回到顶部的方法。

<img width="932" alt="image" src="https://user-images.githubusercontent.com/970828/205503773-0d54a3fd-9c30-4cbf-b62b-3fecec61f7ba.png">

**Comment by iamqiz** [comment]
我把
https://github.com/siyuan-note/siyuan/blob/b542a80f56eb01e99894dfbb74781754ad12c521/app/src/editor/util.ts#L150
改成下面这段代码.使用了gohome 还是不行, 会提示 protyle.wysiwyg.element.firstElementChild 是个null 
```
                        let newtab=newTab(options);
                        targetWnd.addTab(newtab);
                        if (newtab.model && newtab.model instanceof Editor ) {
                            // switchEditor(newtab.model, options, allModels);
                            console.log(`204 ${newtab.model.editor.protyle.wysiwyg.element.firstElementChild}`)
                            goHome(newtab.model.editor.protyle);
                        }
```
@Vanessa219

**Comment by Vanessa219** [comment]
应该是 newTab 里面的编辑器还没有初始好，在 after 回调里面试试。你这里没有初始话好，在提供方法也没有办法调用的。
