### ISSUE TITLE
关于对思源笔记本进行加密的一种解决方案，但需要思源增加支持对data文件夹中的笔记本文件夹的软链接的识别，期望能添加这一特性

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#6548]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前思源笔记不能对最基本的笔记本单元实现加密，这是用户在使用过程的一大痛点，因为用户总是有一些私密的内容不希望在无易间别人窥看到。

目前的解决方案，一是随时关闭想要保密的笔记本，这种方法虽然能保持了要保密的笔记本与其他笔记本的双链引用，但保密级别就是掩耳盗铃。二是对想要保密的笔记本另建一个新的工作空间，这种方法虽然比上一种方法保密级别强，但带来的是繁琐的来回切换空间，以及保密的笔记本不能与其他笔记本的内容进行双链互动。

鉴于以上弊端，我提出了如下的解决方案。

### 描述可能的最优解决方案 Describe the optimal solution

我平时使用VeraCrypt这款软件进行加密文件，它的加密方式，是建立一个无格式的文件，软件可以将这个文件加载成一个虚拟的磁盘分区（实际使用效果类似电脑中的C盘、D盘），这个加载过程需要输入密码，然后将文件放入到里面，即可实现加密。（具体见https://www.zhihu.com/question/20023600/answer/198270485）

所以我的思路是：
先将需要加密的笔记本整个文件夹剪切到VeraCrypt建立的虚拟磁盘分区中，然后通过软链接的方式在思源的data文件夹建立加密笔记本文件夹的软链接，这样在不需要打开加密笔记时，将VeraCrypt的虚拟磁盘分区卸载掉即可，在需要打开加密笔记时，用VeraCrypt将虚拟磁盘分区加载上，在思源中重建索引即可显示出加密笔记本。

但现在苦恼的是，思源笔记好像并不能识别到data中笔记本文件夹的软链符号，期望能够支持这一特性。

**Comment by JCJC01** [comment]
来人啊，赶紧摇人，拱火
思源，让你的个私人笔记更加安全
强烈顶你

**Comment by terwer** [comment]
想法不错，其实我理解，作者想说的就是思源笔记底层支持软连接目录就行了吧。其他的我们自己来做，是不是这样。

**Comment by 88250** [comment]
这个如果要支持的话应该是整个工作空间路径而不只是 data/笔记本 ID/ 路径吧？否则会有泄漏，正如你说的“保密级别就是掩耳盗铃”。

**Comment by 88250** [comment]
暂时无法确定方案，先关闭了，欢迎继续跟帖讨论，谢谢 :pray:

**Comment by iamqiz** [comment]
windows 上mklink /d  创建目录软链接 不行吗? 感觉应该可以

**Comment by JCJC01** [comment]
@88250控制面板有折叠选项。能否通过新增一个需要输入密码的折叠，这样可以折叠需要加密的文档达到想要的效果？ @88250

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/9800
