### ISSUE TITLE
文档块转换为标题块时将文档标签移动到标题块下方

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#6550]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

带标签的文档转换为标题块时，在标签栏会留下无匹配项的标签且无法删除。

复现步骤：

1. 在文档上方添加标签（文档级标签），假设标签名为“A”
2. 将该文档拖进任一文档内转换为标题块
3. 标签栏内，“A”标签会出现，点击标签搜索界面没有匹配项，且该标签无法删除。

### 期待的结果 Expected result

关联：https://ld246.com/article/1668166950604/comment/1668167481328#comments
既然设计上不同的话，那么文档块在转换为标题块时，其标签（文档级标签）应该被清除吧。

### 版本环境 Version environment

```markdown
- Version: 2.4.12
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

.

**Comment by 88250** [comment]
> 其标签（文档级标签）应该被清除吧。

我认为清除的话不太合理吧。

**Comment by EberhardLin** [comment]
> > 其标签（文档级标签）应该被清除吧。
> 
> 我认为清除的话不太合理吧。

我也觉得不太合理，但直接打在标题旁边么，其实很丑说实话，见图：
![image](https://user-images.githubusercontent.com/98400319/201338279-f6cc11ab-5192-4c51-9b34-2458c795d743.png)
如果按照我所说的，直接打在标题旁边，就是这样：
![image](https://user-images.githubusercontent.com/98400319/201338458-eab081cd-9312-4505-806c-5547ab963480.png)
说实话有点丑。
原先是想说块属性界面可以添加一栏标签，但既然不行，我就暂时还想不到其他解决方案。

**Comment by EberhardLin** [comment]
> 那就保持现状吧，还少这种情况下将标题块转换回文档后标签还能用。
> 
> 数据上会出现一定冗余，但是不会丢失，目前来看较为稳妥。

但起码要在标签栏点击搜索时能出现匹配项比较好，不然的话这种操作多了，会给标签栏留下一些无法删除的无效标签，还不好找到是哪个标题块。

**Comment by 88250** [comment]
也许还有个方案，文档转换标题时，新建段落块，把标签放到其中，然后把这个段落块再放到标题下方第一个位置。

**Comment by EberhardLin** [comment]
> 也许还有个方案，文档转换标题时，新建段落块，把标签放到其中，然后把这个段落块再放到标题下方第一个位置。

![image](https://user-images.githubusercontent.com/98400319/201341551-7963560e-54e4-4784-a17b-f1289f7b45fa.png)
只是很可惜这样无法显示标题名，还是没办法将标题块和文档块在标签栏中对等起来。
PS：阅读模式下可以选中文字并Ctrl+X剪切，这算不算BUG？

**Comment by 88250** [comment]
> 只是很可惜这样无法显示标题名，还是没办法将标题块和文档块在标签栏中对等起来。

估计找不到更好的方案了，这也是权宜之计。

> PS：阅读模式下可以选中文字并Ctrl+X剪切，这算不算BUG？

麻烦单独开 issue。

**Comment by EberhardLin** [comment]
留下无效标签的情况，在我把标题，甚至块都删除后，还是会留下无效且无法删除的标题
![image](https://user-images.githubusercontent.com/98400319/201342078-563127ba-c849-4796-9e33-8286057a9942.png)
删除就显示这个：
![image](https://user-images.githubusercontent.com/98400319/201342054-4546b25a-04a0-4744-82df-d35c65a1ee83.png)

**Comment by 88250** [comment]
重建索引试下。

**Comment by EberhardLin** [comment]
> 重建索引试下。

OK解决了，本来还在苦恼测试、复现时的几个无效标签怎么办，阿里嘎多。
