### ISSUE TITLE
英文大小写替换功能

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#6551]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我是英文专业的，所以经常需要复制一些英文杂志、报刊的内容，
但是经常遇到很多内容都是整段整段的大写字母。

这个时候，粘贴到笔记中来以后，想批量替换成小写字母，只能照着打一遍
希望可以提供英文字母大小写批量替换的功能。

### 描述可能的最优解决方案 Describe the optimal solution

选中一段大写的英文文本，可以批量转换成小写

**Comment by 88250** [comment]
建议在外部处理好后再粘贴，软件内目前就不考虑内置该场景功能了，感谢提议。
