### ISSUE TITLE
点击搜索标签出来的搜索项后，下面的视图将点击项置于顶端

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#6560]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/35998162/201466082-ee4bd13a-8b81-4e8c-a469-057cd739daa6.png)

### 描述可能的最优解决方案 Describe the optimal solution

如图

**Comment by Vanessa219** [comment]
没太理解，点击以后会搜索的字会高亮，也会定位在前面的。

**Comment by cesaryuan** [comment]
> 没太理解，点击以后搜索的字会高亮，也会定位在前面的。

https://user-images.githubusercontent.com/35998162/201474878-43eecc5e-ee29-4093-be86-00d176652c30.mp4

**Comment by 88250** [comment]
* 只有纯文本会高亮，其他行级元素命中不会高亮
* 定位的话要看下边的内容是否足够高度撑满，如果高度不够的话，就只能定位在中间了

感谢反馈。

**Comment by cesaryuan** [comment]
> * 只有纯文本会高亮，其他行级元素命中不会高亮
> * 定位的话要看下边的内容是否足够高度撑满，如果高度不够的话，就只能定位在中间了
> 
> 感谢反馈。

谢谢回复，因为大部分页面的内容都比较少，也就是大部分都撑不起下面的高度，那就意味着大部分搜索内容都定位不了，每次使用搜索功能都要使用眼睛来定位，那么搜索的体验是不是大打折扣呢？

**Comment by 88250** [comment]
可以试试下面多留一些空块，把内容撑满。

**Comment by cesaryuan** [comment]
给后面遇到这个问题的人一个解决方案，添加下面的CSS片段：
```
.b3-typography, .protyle-wysiwyg {
    margin-bottom: 1000px;
}
```
