### ISSUE TITLE
反向链接面板添加显示上下文和展开按钮

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6567]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

方便一次性看完一个文档的所有反向链接，像 logseq 等那样。

### 描述可能的最优解决方案 Describe the optimal solution

添加显示上下文按钮，而不只是显示一个段落。
目前有一键折叠按钮，希望有一键展开按钮。

**Comment by JCJC01** [comment]
确实不理解，全部显示日期整齐漂亮不是目的，方便查看才是
如果是要查找用搜索功能就行
但是这个反链的应用场景除了汇总，应该也是有快速浏览查找逻辑思路的场景在，但是全部显示日期而且折叠起来，还不如用sql汇总然后分屏看更直观。
另外不同日期叫应该有明显的框区分

**Comment by 88250** [comment]
目前暂时不考虑支持，请参考之前的讨论：

* https://github.com/siyuan-note/siyuan/issues/6482
* https://github.com/siyuan-note/siyuan/issues/6182
* https://github.com/siyuan-note/siyuan/issues/6083
