### ISSUE TITLE
后期能否支持设置游客账号，该账号登录后，只能使用阅读模式，无法修改文档。

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#6568]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

使用场景是：在云服务器部署思源笔记后作为一个在线文档平台，然后通过主账号编辑笔记内容，其他人可以通过设置好的游客账号登录后进行内容查看和搜索，但是无法编辑修改文档。

现在虽然也能部署，通过同一个账号也能登录查看，但是查看的人可以直接修改文档就很不合适。如果支持设置游客账号并且该账号登录后锁定为阅读模式，那就可以作为一个在线文档平台或者个人笔记的分享平台了。

### 描述可能的最优解决方案 Describe the optimal solution

支持设置主账号和游客账号。游客账号登录后，笔记锁定为阅读模式，无法修改文档。

**Comment by BryceAndJuly** [comment]
当然了，这个可以加入到会员权益中。

**Comment by 88250** [comment]
多账号和权限管理目前暂时不考虑支持，这个场景目前可以用内核只读模式 `--readonly` 顶顶。

**Comment by BryceAndJuly** [comment]
嗯，感谢提醒，这个确实可以。
