### ISSUE TITLE
iPad 端无法通过外置键盘上下键在块和块之间移动

### ISSUE THREAD

**Issue by Miobowl** [siyuan-note/siyuan#6570]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

RT，使用上下键只能移动至当前所在块的开头和末尾

### 期待的结果 Expected result

上下键应能在不同块之间移动，和PC端相同

### 版本环境 Version environment

```markdown
- Version: 2.4.12
- Operating System: ipad os 16.1
- Browser (if used):
```

### 日志文件 Log file

N/A

**Comment by 88250** [comment]
感谢反馈，目前没有设备可以开发调试，先记录在 https://github.com/siyuan-note/siyuan/issues/4238
