### ISSUE TITLE
2.50正式版什么时候出啊

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#6571]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如题
2.50 支持s3和webdav 对我这种有nas的来说简直太友好了 

### 描述可能的最优解决方案 Describe the optimal solution

1

### 描述候选的解决方案 Describe the candidate solution

1

### 其他信息 Other information

1

**Comment by 88250** [comment]
估计就这两天内，感谢关注。
