### ISSUE TITLE
选中文字拖拽到光标位置以及拖拽大纲标题实现文章结构调整作用

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#6572]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

发现句子内容需要调整以及文章结构需要调整时使用

### 描述可能的最优解决方案 Describe the optimal solution

发现句子内容需要调整以及文章结构需要调整时使用

### 描述候选的解决方案 Describe the candidate solution

发现句子内容需要调整以及文章结构需要调整时使用

### 其他信息 Other information

发现句子内容需要调整以及文章结构需要调整时使用

**Comment by 88250** [comment]
行级元素内无法支持拖拽，原因见 https://github.com/siyuan-note/siyuan/issues/6169

**Comment by QQQOrange** [comment]
> 行级元素内无法支持拖拽，原因见 #6169

 好吧 短期内怕是实现不了了
