### ISSUE TITLE
云收集箱

### ISSUE THREAD

**Issue by JCJC01** [siyuan-note/siyuan#6575]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

通过微信思源小助手 收集了一些资料，或者快速写很多零散的灵感
一旦多了，又要分类整理，其实是增加了阻力的
dailynote的精神是阻力留给笔记处理，用户更专注于内容本身，减少分类等阻力

### 描述可能的最优解决方案 Describe the optimal solution

在微信思源小助手录入的时候，增加【【市场推广】】双链在内容前面
通过云收集箱一转到笔记，这样就可以通过双链面板快速使用及分类

flomos等类似软件是通过#标签内容#实现，既然双链及双链面板是思源主推的功能，希望可以在这方面也加上运用

云收集箱作为会员的功能，也希望通过赋予更多更好的体验强化它的体验

flomo年费也不便宜，但是拥有思源会员，就有用了flomos的功能+双链+本地私人笔记+同步功能，相信是更好的卖点

**Comment by 88250** [comment]
需要手动移动到笔记本是设计，整理请在笔记本里整理。
