### ISSUE TITLE
pc端设置里面的资源功能优化

### ISSUE THREAD

**Issue by JCJC01** [siyuan-note/siyuan#6577]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

随着笔记的增多，资源的种类和数量都不断增多
特别是开放第三方存储后，用户不用省着云空间用，相信资源很更多
除了管理哪些资源未引用外，希望能更好的管理笔记里面的资源

### 描述可能的最优解决方案 Describe the optimal solution

现有的资源功能非常好，能预览未引用的资源
能否支持类似列表模式
这样能更好地看到资源的类型，名称，是否被引用，体积大小等信息，并能直接点击打开

**Comment by 88250** [comment]
这个暂时不会考虑，感谢提议。
