### ISSUE TITLE
代码高亮支持oracle plsql

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6578]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

最近在学习Oracle，记录一些笔记，但是只能高亮标准的SQL语法，对于一些Oracle特殊的关键字，比如对于xml和json操作，Oracle有自己的语法，这样就没有办法进行高亮提示，影响了整体的美观，例如更高级的展示样式比如增加行号，代码格式化等等

### 描述可能的最优解决方案 Describe the optimal solution

希望可以增加这个模式

### 描述候选的解决方案 Describe the candidate solution

或者提供自定义样式等解决方案，例如附加CSS等，如果是主题层面的支持，会有一个问题，就是如果切换主题那么这些CSS也将失效

**Comment by terwer** [comment]
自定义css片段和js片段功能已经有了。


| |
youweics
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年11月14日 13:10 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [siyuan-note/siyuan] 代码高亮支持oracle plsql (Issue #6578) |

在什么情况下你需要该特性？In what scenarios do you need this feature?

最近在学习Oracle，记录一些笔记，但是只能高亮标准的SQL语法，对于一些Oracle特殊的关键字，比如对于xml和json操作，Oracle有自己的语法，这样就没有办法进行高亮提示，影响了整体的美观，例如更高级的展示样式比如增加行号，代码格式化等等

描述可能的最优解决方案 Describe the optimal solution

希望可以增加这个模式

描述候选的解决方案 Describe the candidate solution

或者提供自定义样式等解决方案，例如附加CSS等，如果是主题层面的支持，会有一个问题，就是如果切换主题那么这些CSS也将失效

其他信息 Other information

No response

**Comment by hackerhui** [comment]
thank you
