### ISSUE TITLE
代码按钮bug

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#658]
选中一段代码，并点击如图的按钮后
![image](https://user-images.githubusercontent.com/11142054/101279345-aa194080-37fc-11eb-96b9-eb0d4c6a796e.png)
选中的那一大段代码的第一行，会自动跟在```后面
![image](https://user-images.githubusercontent.com/11142054/101279393-f4022680-37fc-11eb-87fd-2f0207db2674.png)
这样就很麻烦，就不能让其空着，待会再补全具体的语言？

**Comment by 88250** [comment]
这个应该是自动沿用了上一次的语言设置……
