### ISSUE TITLE
支持设置 【禁用拖动产生超级块】

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#6582]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在进行上下文的段落块拖动的过程中，
让我非常痛苦的一点是，**思源的拖动需要特别细致的操作，只要一点点细微的位移，拖动产生的结果就会发生变化。
就是最简单的两个列表项，在进行上下拖动，就能在很细微的范围内，产生4种不同的效果**（两种产生超级块，两种是普通快的位置、层级变化），更不要说更复杂的结构了
![Snipaste_2022-11-14_19-46-57](https://user-images.githubusercontent.com/117956441/201652611-cc1325c6-ece1-42d4-9279-e5e46fbbea6a.png)
![Snipaste_2022-11-14_19-47-06](https://user-images.githubusercontent.com/117956441/201652692-5df31d3a-7a1a-4528-8d04-2cb83486b117.png)
![Snipaste_2022-11-14_19-47-47](https://user-images.githubusercontent.com/117956441/201652728-f4991d4f-81b5-434a-a241-f9fc2f68d087.png)
![Snipaste_2022-11-14_19-48-02](https://user-images.githubusercontent.com/117956441/201652753-3a84ebf9-6812-4c77-aeba-1622bda42333.png)

但我真正在拖动时需要的，就是蓝线标识的普通块位置变化的效果。 
从来不需要红线标识的超级块效果。
**（如果想使用超级块，比起微调半天的拖动，我更愿意选中两端文本，然后选择合并为超级块）**

### 描述可能的最优解决方案 Describe the optimal solution

希望开发者考虑，**支持设置 【禁用拖动产生超级块】**
从而给鼠标拖动文本提供更大的生效范围，更多的容错空间
我真的每一次拖动上下文，都要非常小心翼翼的微调，才能达到预期结果，给我造成了不小的困扰（**我统计最近一个星期的上下文拖动操作，一次就成功达到预期效果的概率竟然都没有到达50%）😞**

**Comment by Soltus** [comment]
现在版本貌似已经容易很多了

**Comment by Yuminis98** [comment]
> 现在版本貌似已经容易很多了

我就是用的最新的版本

**Comment by UFDXD** [comment]
这个跟主题有很大因素的

**Comment by 88250** [comment]
建议使用默认主题测试看看，
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Yuminis98** [comment]
谢谢开发者，我尝试了默认主题，但是其操作逻辑没有什么变化。
鼠标拖动段落块依然需要很细微的操作，稍微发生变化，就会产生不同的效果。
![Snipaste_2022-11-15_07-38-44](https://user-images.githubusercontent.com/117956441/201790765-aa898a22-5087-43e6-9e91-2e4ea5bba6ec.png)
![Snipaste_2022-11-15_07-38-53](https://user-images.githubusercontent.com/117956441/201790774-3e3aed71-11d4-4767-aeac-5e4ae56a5f6d.png)
![Snipaste_2022-11-15_07-39-01](https://user-images.githubusercontent.com/117956441/201790777-e1438f67-e170-4688-b4d6-fe46de3d3e0b.png)
![Snipaste_2022-11-15_07-39-14](https://user-images.githubusercontent.com/117956441/201790780-3a3b3ea5-259d-4b61-9564-f394a9c8e607.png)

我反馈该问题，是因为超级块是思源特有的一种机制，
 而我在用鼠标段落块时，只希望段落块的层级或者顺序发生改变，而不是两个段落块合并成一个超级块。
但是变成超级块占据了一半的拖动结果。
 在拖动段落快的过程中，总是失误将两个块变成了超级块，让我在记笔记的过程中感到了折磨。。

所以提出了希望可以设置 【禁用拖动产生超级块】，给鼠标拖动更多的容错空间。

**Comment by Yuminis98** [comment]
另外，D大，我看您已经把【卡片白板】作为近期计划了，是否可以开放那个issue的讨论，现在无法comment😂
![image](https://user-images.githubusercontent.com/117956441/201801338-7c52a21d-0802-4dde-b960-25a12a0df450.png)

**Comment by 88250** [comment]
* 禁用的开关估计不会考虑，后续会继续收集反馈看下如何改进拖拽体验
* Maze issue 已经恢复讨论
