### ISSUE TITLE
支持单文档查看追溯历史文档

### ISSUE THREAD

**Issue by aptexd** [siyuan-note/siyuan#6586]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

1. 对单个文档的历史进行整理查看的时候
2. 文档被错误覆盖，需要对各个版本进行集合
3. 历史文档里默认用时间分组，需要单个点开十分不便
4. 历史文档与当前文档没有视觉对比，很难记住差异

### 描述可能的最优解决方案 Describe the optimal solution

在单个文档的“更多”按钮中有“该文档历史记录”功能
最好将当前文档和历史文档并排显示，可以手动同步各个版本内容

### 其他信息 Other information

在文档历史中通过搜索文档名称的功能不够实用，也达不到上述单个文档追溯的效果

**Comment by mohuishou** [comment]
历史文档最好要有 diff 功能，不然真的不知道改了啥

**Comment by UFDXD** [comment]
以前有的，但是被去掉了

**Comment by terwer** [comment]
为啥去掉啊，我感觉是很好的功能。类似git diff

**Comment by 88250** [comment]
单个文档的历史依赖 history 文件夹历史文件，这个会自动过期删除，所以用于追溯文档的历史不太稳定。

我们先考虑解决快照对比吧 https://github.com/siyuan-note/siyuan/issues/6858 编辑器可视化 diff 暂时也没有方案可以做，这个还需要时间，感谢提议。
