### ISSUE TITLE
默认主题会出现透视现象，具体看图（部分主题也会有此现象）

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#6587]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

默认主题会出现透视现象，具体看图（部分主题也会有此现象）

### 期待的结果 Expected result

解决问题

### 截屏或者录屏演示 Screenshot or screen recording presentation

![NI{OGK8@X1VEMQ}QB8%W`QO](https://user-images.githubusercontent.com/62794181/201801360-dd20e78c-3541-4348-b3b7-f1f342295883.png)
![~B(%X~W{D6AC@NX_ D%$5)6](https://user-images.githubusercontent.com/62794181/201801367-5722bdd8-fb64-4c18-9af3-8c3d563d93d7.png)

### 版本环境 Version environment

```markdown
- Version: 2.5
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10008221/system-log.zip)

### 更多信息 More information

记得这个bug也是好久就有了 但一直没提issue

**Comment by 88250** [comment]
试下重置外观。

**Comment by QQQOrange** [comment]
> 试下重置外观。

还是这样
![image](https://user-images.githubusercontent.com/62794181/201801812-6257e4fa-e242-4cee-91e5-4013eb8cd25e.png)

**Comment by 88250** [comment]
打开开发者工具，禁用缓存然后 Ctrl+R 刷新。

**Comment by QQQOrange** [comment]
> 打开开发者工具，禁用缓存然后 Ctrl+R 刷新。

开发者工具在哪儿呢

**Comment by 88250** [comment]
鼠标悬浮右下角的问号。

**Comment by QQQOrange** [comment]
> 鼠标悬浮右下角的问号。

人傻了 我还是卸载重装吧

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by QQQOrange** [comment]
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

卸载重装后数据什么的都在，当然这个bug也在，话说，，，，，能不能给个清除缓存的按钮在设置里，开发者工具看不懂，，，，，，

**Comment by Soltus** [comment]
和开启了自定义主题的效果很像，目前一些采用JS动态加载样式的主题（比如Sofill-）还无法很好的兼容自定义主题，建议关闭后重载 @QQQOrange

**Comment by QQQOrange** [comment]
> 

嗷嗷嗷 谢老哥
