### ISSUE TITLE
列表易用性改进

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#659]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
1.先开始没有写无序列表或有序列表,后面需要把段落改成列表;或情况相反时
2.需要将整体的无序列表改成有序列表时

### 描述最优的解决方案 Describe the optimal solution
![段落与列表的转换](https://user-images.githubusercontent.com/11732858/101284796-c4fbad00-381c-11eb-9541-f783928dfe00.gif)
![有序列表与无序列表的转换](https://user-images.githubusercontent.com/11732858/101284833-feccb380-381c-11eb-9e9b-e8cfb15ba5ea.gif)
OneNote可实现该功能

### 其他信息 Other information
现在思源中仅可一行一行的添加或修改

**Comment by 88250** [comment]
感谢反馈，这是一个[已知缺陷](https://github.com/siyuan-note/siyuan/issues/132)，后续进行修复。
