### ISSUE TITLE
希望能在公式编辑器加入快捷语法提示

### ISSUE THREAD

**Issue by AngryAccelerated** [siyuan-note/siyuan#6591]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

记录大量公式的笔记的时候

### 描述可能的最优解决方案 Describe the optimal solution

比如 AxMath , 输入"\" 触发语法提示
![Snipaste_2022-11-15_15-44-59](https://user-images.githubusercontent.com/13927622/201859405-93eaf9fe-baca-45cc-abfb-dac47a7cf4ab.png)

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
这个短期内估计没有时间考虑，可以在外部比较好的公式编辑器里编辑好一次性拷贝进来，感谢提议。
