### ISSUE TITLE
S3 数据同步跳过 HTTPS 证书校验

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#6592]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

S3同步，自己搭建的minio
在两台windows和一台mac电脑、还有docker版本均正常同步。
使用app同步报错
![image](https://user-images.githubusercontent.com/5226690/201871498-188f57bc-b266-4f32-8f31-2aab3de2b08e.png)

### 期待的结果 Expected result

麻烦帮看下，
或者是否s3也可以绕过https证书？

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
android 12
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10010811/system-log.zip)

**Comment by 88250** [comment]
看上去是证书的问题？

**Comment by jl0476** [comment]
比较奇怪，其他几台设备都没有问题的。

**Comment by 88250** [comment]
@jl0476 手机系统上的根证书可能不一样。

**Comment by Zuoqiu-Yingyi** [comment]
@88250 基于传输安全考虑, S3 与 webDAV 同步是不是应该由用户可选跳过 SSL 证书校验?

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 理论上已经加密过的数据应该是传输安全的，但是 access secret 这些可能会不安全，这个暂时不加配置项了。
