### ISSUE TITLE
文档标题快速输入中文光标位置异常

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6594]
https://ld246.com/article/1668487895382

**Comment by Yuminis98** [comment]
输入英文也会异常

**Comment by 88250** [comment]
> 输入英文也会异常

应该已经一并修复，可下载 dev 版本帮忙测试看看。

**Comment by Yuminis98** [comment]
> > 输入英文也会异常
> 
> 应该已经一并修复，可下载 dev 版本帮忙测试看看。

已解决

**Comment by Yuminis98** [comment]
> > 输入英文也会异常
> 
> 应该已经一并修复，可下载 dev 版本帮忙测试看看。

![image](https://user-images.githubusercontent.com/117956441/202605357-1ca5dd3e-28fc-4005-bca6-782bc484b8ad.png)
我更新了测试版本以后，
按alt+5 又给我创建了一个新的dailynotes。🤣
更新前建立的那个内容还在，但是和alt+5失去绑定了。不知道怎么回事

**Comment by 88250** [comment]
@Yuminis98 这个问题偶尔会发生，但是我们还没有找到稳定重现的步骤，麻烦继续帮忙留意。
