### ISSUE TITLE
特性提议：增加数学公式块的快捷键

### ISSUE THREAD

**Issue by jiaojiaodubai** [siyuan-note/siyuan#6596]
## 场景
当需要插入行间数学公式时，（尤其是书写理工科时）。

## 目前的解决方案
对于一个正在**使用中文输入法**的用户而言，如果想插入一个行间公式块，他有两种方法：

    1. 敲击一次<kbd>Shift</kbd>将输入法切换为英文模式，再长按<kbd>Shift</kbd>，同时敲击两次<kbd>4($)</kbd>按键唤出行间公式输入框。
    2. 敲击一次<kbd>/(?)</kbd>键以输入`/`，然后使用箭头<kbd>↑</kbd>或<kbd>↓</kbd>，或者使用鼠标滚轮定位到`数学公式块`，并用鼠标点击或者键入<kbd>Enter</kbd>来确认。

## 目前的不足之处
无论是方法1还是方法2，都需要比较多的击键，对于需要输入大量公式的用户不够友好。

### 描述可能的最优解决方案 Describe the optimal solution

在`设置-快捷键-编辑器-插入元素`中增加`公式块`的快捷键设置项。

**Comment by 88250** [comment]
使用 `/公式` 或者 `/gs`
