### ISSUE TITLE
特性建议：中文公式混输优化

### ISSUE THREAD

**Issue by jiaojiaodubai** [siyuan-note/siyuan#6597]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

编辑中文文档时，如果需要输入大量公式，则需要频繁切换中文输入模式（在文本区）和英文输入模式（在公式区）

### 描述可能的最优解决方案 Describe the optimal solution

在`设置-编辑器`中增加两个设置项以优化中文-公式混输体验：

- 设置项名称：`进入公式区时追加Shift键`，设置项描述：`当以任何方式唤出公式输入框时自动追加Shift键以切换键盘为ASICC输入模式`
- 设置项名称：`退出公式区时追加Shift键`，设置项描述：`当以任何方式退出公式输入框时自动追加Shift键以切换键盘为ASICC输入模式`

当然，以上两个设置项也可以合并为一个设置项，这样用户就无需因为输入公式而频繁切换输入法的输入模式。并且这个设置项对大部分非英语国家的用户都非常实用。

**Comment by 88250** [comment]
这个可能会破坏已有用户的使用习惯，暂时不考虑了，感谢反馈。
