### ISSUE TITLE
特性提议：公式输入补全

### ISSUE THREAD

**Issue by jiaojiaodubai** [siyuan-note/siyuan#6598]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在行内或行间公式输入框书写Katex语句时

### 描述可能的最优解决方案 Describe the optimal solution

当输入KaTex支持的[命令](https://katex.org/docs/support_table.html)时，应当给予代码补全提示，这会大大提高公式的输入效率。
1. 最起码地，应该先支持以下代码的自动补全：
    -成对的花括号`{`和`}`
    - `\begin{}`和`\end{}`
    因为上述代码在KaTex语法中总是成对出现的。
2. 更进一步地，还应当支持补全剩下的原生KaTex命令。
3. 再进一步地，应当支持补全用户在`设置-编辑器-KaTex 宏定义`中定义的命令。

### 描述候选的解决方案 Describe the candidate solution

上述需求或许也能通过编写第三方插件实现，但要是SiYuan原生支持将会更好。

**Comment by 88250** [comment]
这个短期内无法实现。

* https://github.com/siyuan-note/siyuan/issues/6443
* https://github.com/siyuan-note/siyuan/issues/3501
* https://github.com/siyuan-note/siyuan/issues/576
