### ISSUE TITLE
大纲脑图（思维导图）页签

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#66]
![image](https://user-images.githubusercontent.com/873584/92454573-39f62100-f1f3-11ea-954d-7c8aaeab4bf0.png)

**Comment by LiWenGu** [comment]
非常期待这个思维导图特性，目前有些大纲类笔记用思维导图的方式看更加直观

**Comment by napretep** [comment]
https://markmap.js.org/repl
这个很不错

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/62 实现。
