### ISSUE TITLE
在 设置 - 搜索 中分别增加虚拟引用和反链提及 `关键字数量限制`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6603]
关键字过多之后匹配高亮算法的性能会急速下降，目前没有解决方案，只能限制最大关键字数量。

关联 https://github.com/siyuan-note/siyuan/issues/3715

**Comment by UFDXD** [comment]
@88250 希望可配置，电脑好的可不再乎这个

**Comment by Zuoqiu-Yingyi** [comment]
我瞅了一下一下, 我这只 `计算机通信与网络` 笔记就有 `268` 篇文档, 命名+别名加起来有 `759` 个, `512` 个关键字完全不够用呀~

**Comment by Zuoqiu-Yingyi** [comment]
@88250 D大, 搜索结果显示数与虚拟引用数是两个完全不同的需求, 搜索结果用户倾向于更快的响应, 因此会将`搜索结果显示数量`设为较小的值, 虚拟引用用户倾向于更完整的结果, 因此会将`虚拟引用关键字数量`设为较大的值
因此最好将这两个值解耦, 改为由用户单独配置😂

**Comment by UFDXD** [comment]
@88250 还是希望不要动虚拟引用这刀，非要动，请求弄个配置项，配置项提醒有性能影响，用户自己选择。选项可选，限制或无限制模式。
