### ISSUE TITLE
S3 本地标记快照上传报错

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#6604]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![12](https://user-images.githubusercontent.com/38906705/202069647-1375ccf0-4ef7-4f42-9f91-7e6ca660dbef.jpg)

### 期待的结果 Expected result

1

### 版本环境 Version environment

```markdown
- Version: 2.5.0
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
Fix https://github.com/siyuan-note/dejavu/commit/5d5af638b8e51efe1e780df4a24f20e0409b3ba1
