### ISSUE TITLE
增量导出功能

### ISSUE THREAD

**Issue by better319** [siyuan-note/siyuan#6605]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

主要用于加快数据的导出备份和恢复速度。

### 描述可能的最优解决方案 Describe the optimal solution

打个比方，三台设备，家庭pc，办公pc，手机（或者U盘）

我昨天导出了一个1G的压缩包。（办公pc到U盘）
今天我又做了点资料，增加了一些文档，大概50个。（办公PC）
今天我又备份，是否可以通过检测，前面已经有1g的压缩包了（U盘），那么现在只要备份这50个文件就行了，不用全部备份，从而达到增量备份的目的。（到此步骤，U盘内应该有1g压缩包和50个文件的增量压缩包）
在恢复的时候（U盘到家庭PC），是否也可以进行检测发现家庭PC的数据库中已经1g的文件，是否将这50个文件的增量压缩包合并入家庭PC的数据库中。

当家庭PC中文件发生变化时，比如大于1g或者小于1g，也可以设置提示，让使用者确定是否仅更新增量文件，还是恢复增量文件压缩包+1g压缩包（彻底恢复）

这样导出和恢复的速度就可以快很多了。

### 描述候选的解决方案 Describe the candidate solution

同上

### 其他信息 Other information

无

**Comment by 88250** [comment]
可以试下数据仓库，这个是增量的。

**Comment by better319** [comment]
![895e9ff6ac845fa45c6bbfead4b8096](https://user-images.githubusercontent.com/13842581/202094571-ed1b7624-7747-44ec-994a-53458cfb9849.jpg)
是指这个数据快照吗？
但这个好像不能导出，能详细说一下嘛？
还是说找到数据快照文件然后在不同电脑上恢复？有数据快照文件的路径吗？

**Comment by better319** [comment]
是指这个数据快照吗？
但这个好像不能导出，能详细说一下嘛？
还是说找到数据快照文件然后在不同电脑上恢复？有数据快照文件的路径吗？
![微信截图_20221116134923](https://user-images.githubusercontent.com/13842581/202095089-647965fb-0650-41f8-bd55-41746c40845c.png)

**Comment by 88250** [comment]
@better319 是这个，路径是工作空间 repo 文件夹
