### ISSUE TITLE
支持聚焦导出 图片/PDF/HTML/Word

### ISSUE THREAD

**Issue by aobatu** [siyuan-note/siyuan#6607]
现在导出长图的功能是：整个文档可导出图片，但不支持文档中部分内容导出图片
期望的诉求是：想要导出文档中部分内容为长图

可实现的方案方向（多选一）：

1. 支持内容快导出图片，无论是标题块，还是列表块，都可以导出长图；
2. 支持导出当前聚焦的块

暂时想到如上两种方式，都能支持将文档中部分内容导出为图片。

_Originally posted by @aobatu in https://github.com/siyuan-note/siyuan/issues/2919#issuecomment-1315503249_

**Comment by 88250** [comment]
这个暂时不考虑了，如果后续有需要的用户较多再考虑，感谢提议。

**Comment by Vanessa219** [comment]
https://ld246.com/article/1676386423118

**Comment by aobatu** [comment]
哈哈哈，终于等到了，感谢~
