### ISSUE TITLE
增加 设置 - 搜索 - 搜索结果显示数 影响说明

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6608]
![image](https://user-images.githubusercontent.com/873584/202119431-a6ccdb2b-0cde-4cb2-aa95-9eb4ce85cd28.png)

红框下部列出影响范围。

**Comment by choyy** [comment]
搜索结果超过了最大显示数搜索界面会有提示吗

**Comment by 88250** [comment]
@choyy 不会有
