### ISSUE TITLE
两个垂直超级块组成一个水平超级块时宽度显示不对

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#6612]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如图所示，正常来讲左侧超级块的宽度显示条（蓝条）应该显示宽度为50%，但不知道为什么是100%。

### 期待的结果 Expected result

Maybe 可以修复下，不过最好不止两个的，例如四个垂直超级块组成一个水平超级块时，每个超级块应该显示25%。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![EAIN}{8PLO`)4RFNH7%8EA7](https://user-images.githubusercontent.com/98400319/202179922-22814353-1242-4ac7-92fa-4828ebcff605.png)
![VGAAE}8_K6NNIM6X43O6@{Q](https://user-images.githubusercontent.com/98400319/202179952-0aad47b6-4721-4084-b7f0-d2efde659050.png)

### 版本环境 Version environment

```markdown
- Version: 2.5.0
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

~

**Comment by Vanessa219** [comment]
合并以后根据 flex 布局是等分的，因此没有值。默认就为 100% 了。
