### ISSUE TITLE
标签补全列表找不到某些标签

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#6615]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

按 # 弹出来的补全列表的找不到某些标签
![image](https://user-images.githubusercontent.com/35998162/202199384-92f3b511-fa25-497b-8415-cac0c5343d2b.png)

### 期待的结果 Expected result

标签补全列表能够找到所有的标签

### 版本环境 Version environment

```markdown
- Version: 2.5.0
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10022313/siyuan.log)

**Comment by 88250** [comment]
候选列表是有长度限制的，继续输入关键字搜索应该可以找到。
