### ISSUE TITLE
作为使用者，期望能自定义笔记列表中的排序顺序

### ISSUE THREAD

**Issue by huanongkou** [siyuan-note/siyuan#662]
###  笔记有优先级，期望手动拖动排序

>笔记目前的排序方式 可以按文件名字母 或者时间进行排序，期望多一点排序方式，手动拖动排序，主要解决笔记的优先级，或者其他权重想置顶

### 排序方式增加自定义拖动排序

![1RejUTOPat2ZyzC](https://i.loli.net/2020/12/07/1RejUTOPat2ZyzC.png)

**Comment by 88250** [comment]
谢谢，但支持不了手动自定义排序，如果一定需要的话可以用命名的方式来实现，虽然不是很雅观……

**Comment by 88250** [comment]
将在 https://github.com/siyuan-note/siyuan/issues/1513 中实现。
