### ISSUE TITLE
修改图片标题时，Ctrl-V触发对应代码有bug，粘贴结果为![xxx](assets/xxx.jpg)

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#6623]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

选择一个图片，右键，定位到标题位置，Ctrl-V，出现结果为：
![v2-35c6d4e04bb3ea4d9c2a769656c5f938_r](assets/v2-35c6d4e04bb3ea4d9c2a769656c5f938_r-20221117093214-wza3jkr.jpg)
Ctrl-V之后用剪贴板查看程序可以看到剪贴板内容已经被替换掉，需要保持右键菜单不关闭，重新去复制一次正确的来粘贴才能修改好标题（如果关闭右键菜单，还是一样的）。非常不方便。

经过剪贴板查看程序查看，每次右键选择图片时，会自动将剪贴板内容换成 ![xxx](assets/xxx.jpg)

### 期待的结果 Expected result

正常粘贴

### 版本环境 Version environment

```markdown
- Version: 2.4.0
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

I 2022/11/17 08:12:50 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/11/17 08:12:55 working.go:478: built-in pandoc [ver=2.19.2, bin=D:\Brain2\temp\pandoc\bin\pandoc.exe]
I 2022/11/17 08:14:27 runtime.go:47: kernel is booting:
    * ver [2.4.0]
    * arch [amd64]
    * runtime mode [prod]
    * working directory [D:\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\Brain2, data 660 MB]
I 2022/11/17 08:14:27 serve.go:79: kernel is booting [http://127.0.0.1:6806]
W 2022/11/17 08:14:32 file.go:316: query root block ref count elapsed [531ms]
I 2022/11/17 08:14:32 conf.go:578: database size [166 MB], tree/block count [3666/46283]
I 2022/11/17 08:14:32 working.go:151: kernel booted
I 2022/11/17 08:21:15 working.go:342: port [6806] is opened, try to check version of running kernel
I 2022/11/17 08:21:15 working.go:361: version of the running kernel is the same as this boot [2.4.0], exit this boot
I 2022/11/17 08:21:46 queue.go:129: op tx [21996ms]
W 2022/11/17 08:54:20 blocktree.go:289: save block tree [size=14 MB] to [D:\Brain2\temp\blocktree.msgpack], elapsed [2.72s]
W 2022/11/17 09:03:06 blocktree.go:289: save block tree [size=14 MB] to [D:\Brain2\temp\blocktree.msgpack], elapsed [2.67s]
W 2022/11/17 09:13:14 blocktree.go:289: save block tree [size=14 MB] to [D:\Brain2\temp\blocktree.msgpack], elapsed [2.47s]
W 2022/11/17 09:13:24 blocktree.go:289: save block tree [size=14 MB] to [D:\Brain2\temp\blocktree.msgpack], elapsed [2.74s]

**Comment by 88250** [comment]
麻烦使用最新版测试一下，谢谢。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by jabobian** [comment]
测试了最新版 2.5.0，问题还是一样的。但是我记得早期的版本没有这个问题。难道是Dark+主题的右键增强菜单功能修改了剪贴板？

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/202340365-17f0079f-42d8-4e36-91a4-98c11bb81992.png)

不是默认主题吗？

**Comment by jabobian** [comment]
默认主题也试过，但是我不知道默认主题会不会用custom.css, custom.js

**Comment by 88250** [comment]
默认主题没有这两个文件。

**Comment by jabobian** [comment]
默认主题是daylight吗，我把外观切换成该模式，并且注释掉 conf\appearance\themes\daylight 下面的 theme.js 之后，还是不行

**Comment by 88250** [comment]
复制后的剪切板内容是？

**Comment by jabobian** [comment]
右键点击图片，剪贴板的内容自动变成该图片的 `![图片说明](assets/图片路径.jpg)`
也就是说后台有未知的脚本做了一次Ctrl-C的操作，是哪个代码（主题还是Siyuan自身）做的不清楚。

**Comment by jabobian** [comment]
我发现我在Siyuan中任意位置右键点击，剪贴板的内容都会更新。

**Comment by 88250** [comment]
这个不是思源本体的功能。

**Comment by jabobian** [comment]
发现是一个叫词博词典4.0（cibo.exe）的软件，本来是右键划词，但是别的地方也都会乱触发。浪费D大时间，不好意思啊，感谢！
