### ISSUE TITLE
外观界面透明度Aero效果

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6629]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

让软件伤心鱼目

### 描述可能的最优解决方案 Describe the optimal solution

基于Electron开发的应用可以配置透明度

### 描述候选的解决方案 Describe the candidate solution

或者交由社区挂件实现

**Comment by 88250** [comment]
设置以后性能较差，暂时不考虑了。

**Comment by Soltus** [comment]
实时模糊除了分散你的注意力外似乎没什么用处，不过我们有个普通的磨砂效果方案

- https://github.com/Hi-Windom/winsay/issues/436
