### ISSUE TITLE
反向链接列表里文件引用和块引用区分开

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#663]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
查看边栏的反向链接列表时，可以区分块引用和文档引用
![image](https://user-images.githubusercontent.com/13896259/101309943-8d2a4f00-3888-11eb-9b72-0c71127b28ac.png)
如图所示，第一条是引用了该文档，第二条引用了该文档中的一个内容块

### 描述候选解决方案 Describe the candidate solution
也许可以将链接区分成2种，显示在左侧链接栏。一类是“链接了该文档”的列表，一类是“链接了内容块”的列表

**Comment by 88250** [comment]
你好，反链列表里展示的是 ref 块，这个图标是根据 ref 类型来的，不是 def 的类型。

现在的版本又做了一些更新，欢迎体验，谢谢。
