### ISSUE TITLE
云端多端同步

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6630]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当配置多个远程云端时，希望同时向多个云端同步，以避免单个云端出问题，导致云端数据丢失问题，加一个保险。

### 描述可能的最优解决方案 Describe the optimal solution

设置界面增强配置

**Comment by 88250** [comment]
这个估计无法支持，比如需要考虑如果数据不一致时以哪个云端为准，失败时如何处理等。
