### ISSUE TITLE
独立的资源管理界面例如资源列表

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6631]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前有文档树，但是没有资源树，现在是有简单的在设置界面的资源，清理未引用的资源等，不方便对于资源对象的管理，例如pdf，img，希望有一个界面来管理这些资源。

### 描述可能的最优解决方案 Describe the optimal solution

类似notion的静静即可，对于资源的类型比如pdf，img进行筛选，可打标签，可写替代文本（即描述）等等，查看引用了这个资源的文档

### 描述候选的解决方案 Describe the candidate solution

通过第三方挂件实现

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6577
