### ISSUE TITLE
内容块前端的被引用数，可以一直显示，并支持点击弹出链接列表

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#664]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
内容块前端的被引用数，可以一直显示，并支持点击弹出链接列表
![image](https://user-images.githubusercontent.com/13896259/101310096-e5f9e780-3888-11eb-8589-cad64ce32ba8.png)

**Comment by 88250** [comment]
感谢反馈，将在提议 https://github.com/siyuan-note/siyuan/issues/76 中完成。
