### ISSUE TITLE
块 `移动` 框支持可按文档树选择

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6641]
鼠标悬浮有提示 - https://ld246.com/article/1669186144766?r=88250
块移动靠右侧优化显示 - https://ld246.com/article/1669186144766

**Comment by qing-root** [comment]
备注建议
![image](https://user-images.githubusercontent.com/30001685/203587892-afe3a203-aa03-4be5-b6bb-0260b85f602c.png)

**Comment by qing-root** [comment]
mybase把一个文档移动的时候会弹一个框，里面是完整的文档树，可以精准选择移动到的位置：
![image](https://user-images.githubusercontent.com/30001685/203588122-a685b2b7-e1fc-4c24-bd79-d76bd97e4b56.png)

如果优化的话，希望可以参考
