### ISSUE TITLE
拖入嵌入块内容未刷新

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#6647]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![拖入嵌入块内容未刷新](https://user-images.githubusercontent.com/97731736/202722295-89a6f5b2-ffeb-4105-a6e2-66b3cd8b3612.gif)

### 期待的结果 Expected result

修复

### 截屏或者录屏演示 Screenshot or screen recording presentation

修复

### 版本环境 Version environment

```markdown
- Version: v2.5.0
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

w

**Comment by 88250** [comment]
查询嵌入块理论上是不能编辑的，后续会在 https://github.com/siyuan-note/siyuan/issues/6200 中禁止，感谢反馈。

**Comment by UFDXD** [comment]
@88250  这个情况是在“点击”嵌入块弹出“悬浮窗中”编辑的也不行吗？

**Comment by 88250** [comment]
抱歉，我看错了，这个问题后续我们会排查，感谢反馈。
