### ISSUE TITLE
代码块复制按钮改进

### ISSUE THREAD

**Issue by liukun** [siyuan-note/siyuan#665]
不是大问题，只是现在每次点击都进入编辑状态，也不提示复制成功。建议拦截点击事件，不要传递到下面的代码块。

**Comment by 88250** [comment]
感谢反馈，v0.5.6 改进。

**Comment by Vanessa219** [comment]
点击后按钮上会有提示 ![image](https://user-images.githubusercontent.com/970828/103651054-f2fb1b00-4f9b-11eb-806d-8b918137342a.png)
