### ISSUE TITLE
出现好几次了,就是两个目录下相同的文件,并且彼此间能相互影响

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#6654]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

出现好几次了,就是两个目录下相同的文件,并且彼此间能相互影响

### 期待的结果 Expected result

出现好几次了,就是两个目录下相同的文件,并且彼此间能相互影响

### 版本环境 Version environment

```markdown
- Version: 最新
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10047327/system-log.zip)

**Comment by 88250** [comment]
应该是因为 ID 相同了，但是如何出现的相同 ID 尚未明确，方便的话请后续帮忙留意。

目前可以通过 `重复` 功能制作一个副本文档，这样 ID 会重新生成，或者在文件系统上删掉重复 ID 的文件。
