### ISSUE TITLE
改进块引搜索性能

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#6655]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

我用了思源一年多吧。
自己的笔记一共也就1.2G，不算特别多吧
但从某次更新开始以后，我就觉引用的搜寻时间明显变慢了
**现在我基本每【【创建一个引用，都要等待5s左右，
这对一个双链笔记来说，已经没法正常使用了。。。**
特此来反馈，想看看是什么问题。
**如果是数据量太大，那1G就这样了，那再用个3、5年，笔记大小达到5、6G甚至更大的时候，岂不是打一个引用就要等十几秒了😂😂**
我的机器是yoga14是2021 刚买了2年，确定不是电脑性能的问题

### 期待的结果 Expected result

**现在【【一下就要等5s明显不是一个可用的速度，极大打断了记笔记的节奏。
如果是数据量导致的这个问题
那么引用的时候，先不要搜索所有的数据，而是先吧近期的数据或者高频的数据搜索出来， 再翻页的时候再去加载比较久远的数据
是否可以降低引用搜索时间**

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/117956441/202879702-60b49032-e030-454b-a111-a40e2c5dff6a.png)

https://user-images.githubusercontent.com/117956441/202879657-99664d8a-a902-4e98-ae29-fc3caea3f23e.mp4

### 版本环境 Version environment

```markdown
- Version: 2.5.1 beta
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10048320/siyuan.log)

**Comment by netdog2019** [comment]
我的笔记也是1.2G，最近也发现有这个问题，输入[[后要转很多圈，才能显示出来。

**Comment by Yuminis98** [comment]
> 我的笔记也是1.2G，最近也发现有这个问题，输入[[后要转很多圈，才能显示出来。

对的，而且我是在某一次更新以后，明显感觉变慢了。
以前都没有转圈这个加载过程，结果直接出来了。
现在一转圈，转5s，延迟太明显了

**Comment by Soltus** [comment]
我也感觉变慢了

**Comment by UFDXD** [comment]
限制搜索结果数量试试

**Comment by yuyuyu-github** [comment]
我只要 输入 【【
就能空转2、3秒
![image](https://user-images.githubusercontent.com/37429029/202901341-baa15d49-f011-42af-b43e-d3825808e9d4.png)

**Comment by 88250** [comment]
请各位试下最新发布的 dev 版是否有改观，谢谢。

**Comment by Soltus** [comment]
> 请各位试下最新发布的 dev 版是否有改观，谢谢。

有改观，很快

**Comment by 88250** [comment]
@Soltus 明天会发布 dev5，又改进了一些，有空的话麻烦再帮忙测试看看，多谢。

**Comment by Soltus** [comment]
> @Soltus 明天会发布 dev5，又改进了一些，有空的话麻烦再帮忙测试看看，多谢。

OK
