### ISSUE TITLE
搜索的时候，是否可以对重复的内容块进行去重处理

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#6657]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在搜索结果里面，会有大量的重复内容块
如截图所示，
一段话里面，如果出现了多次同一个词，那么搜索结果里面，就会把同一段内容复现多次。

这就导致搜索结果变得特别的多，重复量也大，有限空间中显示的有效结果变少。
![image](https://user-images.githubusercontent.com/117956441/202881311-5632782d-5256-457e-9b78-0646c92f235e.png)

### 描述可能的最优解决方案 Describe the optimal solution

如果同一段内容里面，出现多次搜索词
只要把同一段内容在搜索结果里面显示一次就好了。（然后把匹配关键词的多处位置都高亮标识出来就行，就像现在这样）

没有必要把一个结果复制多份显示

**Comment by Soltus** [comment]
这些项目只是看起来重复，实际上指向的是不同的块，你应该检查一下内容是否重复了

**Comment by 88250** [comment]
重建索引以后再试试，我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Yuminis98** [comment]
> 这些项目只是看起来重复，实际上指向的是不同的块，你应该检查一下内容是否重复了

我查看了块的id，就是同一个块

**Comment by Yuminis98** [comment]
> 重建索引以后再试试，我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

重建索引了，
![Snipaste_2022-11-20_22-19-14](https://user-images.githubusercontent.com/117956441/202907555-72e7bdc4-66c4-4c25-9d13-d3a886f42075.png)

可是问题依然存在，如图，这是随便举得一个例子
![Snipaste_2022-11-20_22-18-32](https://user-images.githubusercontent.com/117956441/202907578-0013d271-4ce9-4b43-b867-e28fa268b44b.png)
![Snipaste_2022-11-20_22-18-51](https://user-images.githubusercontent.com/117956441/202907584-7fe35a7f-cc1f-4daf-92af-ade69bcfc96f.png)

**Comment by Yuminis98** [comment]
两个块的id，我复制出来都是
20220605145274-dt5hy38

**Comment by 88250** [comment]
打开 .sy 文件看下是不是 id 重复了？

**Comment by Yuminis98** [comment]
> 打开 .sy 文件看下是不是 id 重复了？

抱歉昨天发完就睡觉了.我不知道怎么看.sy文件

但是我 在搜索结果1里面随便打了一行字，搜索结果2里面也跟着出现了这行字
可以说明这是两个搜索结果指向了一个块吧。
![image](https://user-images.githubusercontent.com/117956441/202935296-4a0988b4-7cbd-481e-a5b9-f106b9c010fd.png)
![image](https://user-images.githubusercontent.com/117956441/202935320-7ea1ef4a-a41d-4e46-8543-113c1fa1a7bd.png)

**Comment by 88250** [comment]
在文档树上定位到这个文档，然后右键打开文件位置就可以定位到 .sy 文件了，如果方便的话，请将该 .sy 文件上传一下，我们看下能否重现这个问题，谢谢。

**Comment by Yuminis98** [comment]
> 在文档树上定位到这个文档，然后右键打开文件位置就可以定位到 .sy 文件了，如果方便的话，请将该 .sy 文件上传一下，我们看下能否重现这个问题，谢谢。

确实是有很多副本

**Comment by Yuminis98** [comment]
> 在文档树上定位到这个文档，然后右键打开文件位置就可以定位到 .sy 文件了，如果方便的话，请将该 .sy 文件上传一下，我们看下能否重现这个问题，谢谢。

文档树中每一个文档都出现了两遍，
![image](https://user-images.githubusercontent.com/117956441/202960862-89c32445-3867-4499-a557-c5fd4ce3f904.png)

但是如果我删掉其中一个文档，另外一个也显示不存在了
![image](https://user-images.githubusercontent.com/117956441/202960846-7d53f821-9041-4c75-80e0-056cb574d960.png)

**Comment by Yuminis98** [comment]
我发现我的文件目录里面到处都是副本💀
![image](https://user-images.githubusercontent.com/117956441/202961192-79a6389d-b65d-4be4-b131-f586eab904e2.png)
![image](https://user-images.githubusercontent.com/117956441/202961219-342ecd0b-3ebd-4d4e-ac06-211f958e5096.png)

**Comment by 88250** [comment]
是不是使用了第三方同步？思源不支持使用第三方实时同步盘，请看用户指南常见问题。
