### ISSUE TITLE
云端同步增加强制本地同步到服务端和服务端同步本地功能

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6658]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

从思源2.5版本开始入了第三方云端S3协议和WebDAV同步引出本需求，因为可能存在如下场景。

假设本地库为1.0版本，原来只同步到SiYuan的云端，这时SiYuan的云端也为1.0。
这个时候，我将云端改为了S3例如使用阿里云OSS，这时，阿里云OSS也是1.0。
做了一些笔记以后，本地库变为2.0版本，这里同步阿里云OSS，那么阿里云OSS也变为了2.0。
总结，本地2.0，阿里云2.0，SiYuan1.0，如果有其他的云，对于同一个笔记库，那么他们的版本是不一致的。

关键操作，这时，把阿里云OSS切换为SiYuan，进行同步，这里本地库变为1.0版本，但是从逻辑上来说，我希望应该是本地2.0同步到SiYuan去，而不是本地把SiYuan上的库同步回来。

### 描述可能的最优解决方案 Describe the optimal solution

希望增加一个同步的选项，当检测到上次同步的云端和本地同步的云端不一致时，提示是本地同步到云端，还是从云端同步到本地，无论选择哪一项，先对本地生成快照。

### 描述候选的解决方案 Describe the candidate solution

将方案逻辑在切换云端时触发，而不是在同步时。

### 其他信息 Other information

场景主要用于当云端服务端不稳定，或者出于其他的考虑更换云存储供应商时使用

**Comment by 88250** [comment]
> 无论选择哪一项，先对本地生成快照。

同步的实现上就是先生成快照然后才对比快照进行增量同步的。

另外，切换云端服务提供商不在设计考虑内，如果有这个场景，建议考虑使用备份功能，这样比较可靠，感谢反馈。
