### ISSUE TITLE
文档树多选使用 shift + 鼠标左键

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#6659]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

选择连续的多个文档时使用 shift + 鼠标左键快速选择，而不是按住 ctrl 一个个选中。

### 描述可能的最优解决方案 Describe the optimal solution

shift + 鼠标左键快速选择连续的多个文档

**Comment by Vanessa219** [comment]
Shift 点击的话和在下方打开文档冲突了。目前只能使用 Shfit + ⬆️/⬇️。

**Comment by gaoluji** [comment]
> Shift 点击的话和在下方打开文档冲突了。目前只能使用 Shfit + ⬆️/⬇️。

@Vanessa219 好像没效果

**Comment by gaoluji** [comment]
> Shift 点击的话和在下方打开文档冲突了。目前只能使用 Shfit + ⬆️/⬇️。

@Vanessa219 能不能使用ctrl+shift+右键，=

**Comment by Vanessa219** [comment]
这个需要当文档树处于选中状态，没选中的话  alt+1 一下，否则的话就是操作其他面板里面的东西了。

https://github.com/siyuan-note/siyuan/assets/970828/2b75a0f1-bca9-4bac-a5f2-41216ae068bc
