### ISSUE TITLE
希望能以 ppt 的方式预览文档

### ISSUE THREAD

**Issue by huanongkou** [siyuan-note/siyuan#666]
### 希望能以 ppt 的方式预览文档

> 一直都有用 markdown 来写报告（非正式的），然后生成html，在浏览器 能以 ppt 的方式来展示。

### 类似方案

[https://marp.app/](https://marp.app/)
[https://www.npmjs.com/package/@marp-team/marp-cli](https://www.npmjs.com/package/@marp-team/marp-cli)

不值能否集成到思源里，或者有其他方案。

**Comment by 88250** [comment]
感谢提议，我们会在 https://github.com/siyuan-note/siyuan/issues/392 中进行实现。
