### ISSUE TITLE
退格键卡顿

### ISSUE THREAD

**Issue by FgywAwut** [siyuan-note/siyuan#6660]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

长按退格键删除文字时出现卡顿
只有两层子文档

### 期待的结果 Expected result

-

### 截屏或者录屏演示 Screenshot or screen recording presentation

视频看不了，用这个链接
`https://user-images.githubusercontent.com/90757590/202906724-c469ff15-947b-495f-86ff-3f3bdb1b7c11.mp4`

https://user-images.githubusercontent.com/90757590/202906724-c469ff15-947b-495f-86ff-3f3bdb1b7c11.mp4

硬盘信息
![20221120215053](https://user-images.githubusercontent.com/90757590/202906773-01081c14-2743-48e6-8495-f1464aca6eeb.png)

### 版本环境 Version environment

```markdown
- Version: v2.5.0
- 版本 Vindows10企业版LTSC
- 版本号 1809
- 操作系统内部版本 17763.2114
Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
```

### 日志文件 Log file

```
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/11/20 22:01:32 runtime.go:43: kernel is booting:
    * ver [2.5.0]
    * arch [amd64]
    * pid [4732]
    * runtime mode [prod]
    * working directory [C:\Users\aaa\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\ICT]
I 2022/11/20 22:01:32 conf.go:313: user has disabled [Google Analytics]
I 2022/11/20 22:01:32 port.go:65: check running kernel elapsed [0ms]
I 2022/11/20 22:01:32 serve.go:108: listen port elapsed [0ms]
I 2022/11/20 22:01:32 serve.go:115: kernel [pid=4732] is booting [http://127.0.0.1:6806]
I 2022/11/20 22:01:32 working.go:362: built-in pandoc [ver=2.19.2, bin=E:\ICT\temp\pandoc\bin\pandoc.exe]
I 2022/11/20 22:01:32 conf.go:610: database size [8.7 MB], tree/block count [130/5078]
I 2022/11/20 22:01:32 working.go:148: kernel booted
I 2022/11/20 22:01:59 conf.go:391: exiting kernel [force=false, execInstallPkg=0]
I 2022/11/20 22:01:59 database.go:1122: closed database
I 2022/11/20 22:01:59 conf.go:720: cleared workspace temp
I 2022/11/20 22:02:32 working.go:110: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/11/20 22:02:32 runtime.go:43: kernel is booting:
    * ver [2.5.0]
    * arch [amd64]
    * pid [6996]
    * runtime mode [prod]
    * working directory [C:\Users\aaa\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\ICT]
I 2022/11/20 22:02:32 conf.go:313: user has disabled [Google Analytics]
I 2022/11/20 22:02:32 port.go:65: check running kernel elapsed [0ms]
I 2022/11/20 22:02:32 serve.go:108: listen port elapsed [0ms]
I 2022/11/20 22:02:32 serve.go:115: kernel [pid=6996] is booting [http://127.0.0.1:6806]
I 2022/11/20 22:02:32 working.go:362: built-in pandoc [ver=2.19.2, bin=E:\ICT\temp\pandoc\bin\pandoc.exe]
I 2022/11/20 22:02:32 conf.go:610: database size [8.7 MB], tree/block count [130/5078]
I 2022/11/20 22:02:32 working.go:148: kernel booted
I 2022/11/20 22:03:32 box.go:79: auto stat [trees=130, blocks=5078, dataSize=6.1 MB, assetsSize=3.3 MB]
I 2022/11/20 22:03:33 conf.go:391: exiting kernel [force=false, execInstallPkg=0]
I 2022/11/20 22:03:33 database.go:1122: closed database
I 2022/11/20 22:03:33 conf.go:720: cleared workspace temp
```

**Comment by 88250** [comment]
我这里在一个较大的库上（database size [1.2 GB], tree/block count [10011/507259]）测试 5K 字的文档连续删除正常：

![issue](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif)

先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by awut-star** [comment]
![QQ录屏20230615114827~1](https://github.com/siyuan-note/siyuan/assets/90757590/a47211e1-1ebf-4c3e-889f-23108933fafd)
这里因为开了录屏软件，所以CPU占用是从50多开始的

以下都是没开录屏软件
![uTools_1](https://github.com/siyuan-note/siyuan/assets/90757590/ccb9cf3c-3f32-45fb-a256-eb14d6f70981)
空闲时，性能页显示的CPU占用

![uTools_2](https://github.com/siyuan-note/siyuan/assets/90757590/551f0a56-b256-49b1-a296-ecb207af0c04)
删除代码块的内容时，性能页显示的CPU占用

![uTools_4](https://github.com/siyuan-note/siyuan/assets/90757590/e04cc729-051f-4bf6-8c12-493606093c59)
空闲时，进程页显示的CPU占用

![uTools_5](https://github.com/siyuan-note/siyuan/assets/90757590/3197e47a-ec80-4360-bdb2-a9086840042b)
删除代码块的内容时，进程页显示的CPU占用

![uTools_6](https://github.com/siyuan-note/siyuan/assets/90757590/612a83ea-4f05-42c9-a891-2a714dea2ac2)
删除段落的内容时，进程页显示的CPU占用

除了代码块和段落，还有引述的占用也高，目前测试了这三种

**Comment by awut-star** [comment]
> 我这里在一个较大的库上（database size [1.2 GB], tree/block count [10011/507259]）测试 5K 字的文档连续删除正常：
> 
> ![issue](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif) [ ](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif) ![issue](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif) [ ](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif)
> 
> 先关闭了，如果还有问题请继续跟帖，谢谢 🙏

![QQ录屏20230615114827~1](https://github.com/siyuan-note/siyuan/assets/90757590/a47211e1-1ebf-4c3e-889f-23108933fafd)
这里因为开了录屏软件，所以CPU占用是从50多开始的

以下都是没开录屏软件
![uTools_1](https://github.com/siyuan-note/siyuan/assets/90757590/ccb9cf3c-3f32-45fb-a256-eb14d6f70981)
空闲时，性能页显示的CPU占用

![uTools_2](https://github.com/siyuan-note/siyuan/assets/90757590/551f0a56-b256-49b1-a296-ecb207af0c04)
删除代码块的内容时，性能页显示的CPU占用

![uTools_4](https://github.com/siyuan-note/siyuan/assets/90757590/e04cc729-051f-4bf6-8c12-493606093c59)
空闲时，进程页显示的CPU占用

![uTools_5](https://github.com/siyuan-note/siyuan/assets/90757590/3197e47a-ec80-4360-bdb2-a9086840042b)
删除代码块的内容时，进程页显示的CPU占用

![uTools_6](https://github.com/siyuan-note/siyuan/assets/90757590/612a83ea-4f05-42c9-a891-2a714dea2ac2)
删除段落的内容时，进程页显示的CPU占用

除了代码块和段落，还有引述的占用也高，目前测试了这三种

**Comment by awut-star** [comment]
> 我这里在一个较大的库上（database size [1.2 GB], tree/block count [10011/507259]）测试 5K 字的文档连续删除正常：
> 
> ![issue](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif) [ ](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif) ![issue](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif) [ ](https://user-images.githubusercontent.com/873584/202909070-933c2267-9045-4040-95ec-ca82b5f919f0.gif)
> 
> 先关闭了，如果还有问题请继续跟帖，谢谢 🙏

这个有可能优化吗？删除内容时，CPU占用过高。

**Comment by 88250** [comment]
应该无法优化了，思源笔记是实时保存的，但你可以通过划选删除来避免。
