### ISSUE TITLE
粘粘链接自动转卡片样式或者附加网页标题

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6663]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前当粘粘一个URL的时候，只是单纯的粘粘了一个URL，都要手动去编辑或者标注链接的描述信息，不方便。

### 描述可能的最优解决方案 Describe the optimal solution

当粘粘URL的时候，默认将获取对应URL的标题，或者粘粘为卡片样式块，当以纯文本粘粘的时候，保持现在的逻辑。

**Comment by 88250** [comment]
之前你提议过 https://github.com/siyuan-note/siyuan/issues/1020

目前暂时不考虑引入新特性了，我们先解决其他问题，感谢理解。
