### ISSUE TITLE
自动切换代理服务器 

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6667]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候需要上公司 VPN（只能通过代理上网），思源同步就不工作了，

### 描述可能的最优解决方案 Describe the optimal solution

如果同步的时候可以尝试先尝试代理服务器链接，在尝试直接连接，这样就可以无缝切换？
微信就是这样做的，否则 每次切换网络都要重新启动。
![image](https://user-images.githubusercontent.com/38936048/202985295-58f84be7-3620-4953-aea8-8679874ead07.png)

**Comment by 88250** [comment]
如果加入优先使用代理的话估计在切换网络的时候会遇到同步非常慢的问题，因为需要等待网络超时或者返回报错才会尝试切换成另外一个网络设置。

如果改成切换网络设置不需要重启是否能解决该场景需求？

**Comment by oijqws** [comment]
谢谢回复。如果同步慢是问题，是否可以设置2个网络（有代理和没有代理），哪个快用哪个？

**Comment by oijqws** [comment]
判断切换等待超时不是问题，因为切换网络之后有一次卡顿是正常的。手动切换代理会比卡顿花更多时间。

**Comment by 88250** [comment]
> 谢谢回复。如果同步慢是问题，是否可以设置2个网络（有代理和没有代理），哪个快用哪个？

这个无法判断的。

> 判断切换等待超时不是问题，因为切换网络之后有一次卡顿是正常的。手动切换代理会比卡顿花更多时间。

手动切换的话如果不重启是比较快捷的，等超时的话可能需要 30s 以上。

**Comment by oijqws** [comment]
谢谢

如果同步慢是问题，是否可以设置2个网络（有代理和没有代理），哪个快用哪个？

* 这个无法判断的。
  * 同步的时候失败就可以知道网络断了。

判断切换等待超时不是问题，因为切换网络之后有一次卡顿是正常的。手动切换代理会比卡顿花更多时间。
* 手动切换的话如果不重启是比较快捷的，等超时的话可能需要 30s 以上。
  *  切换到VPN，肯定是希望访问公司网的一些内容，找到再放到我们的笔记里，大部分时间都超过30秒了

**Comment by 88250** [comment]
> 同步的时候失败就可以知道网络断了。

所以还是得等失败了才知道，同步之前是无法判断的。

> 手动切换是比较快，但是要人为操作。自动稍微慢，但是更加方便。

自动切换网络有风险，目前不会考虑放到实现中。

**Comment by 88250** [comment]
正在考虑的改进是切换代理不再需要重启。

**Comment by 88250** [comment]
这个我关闭了，感谢反馈。

**Comment by oijqws** [comment]
谢谢
