### ISSUE TITLE
修改主题样式时多次回退一定概率出现白屏

### ISSUE THREAD

**Issue by scvoet** [siyuan-note/siyuan#667]
### 描述问题 Describe the problem

修改主题样式时多次回退一定概率（暂时无法准确判断造成原因）出现白屏。

### 期待的结果 Expected result

一切正常

### 截屏或录像 Screenshot or video

![图片](https://user-images.githubusercontent.com/45708948/101332574-70097680-38b0-11eb-8e1a-67bb6e40d0e9.png)

### 版本环境 Version environment

* 版本 Version： 0.5.2
* 操作系统 Operating system：Windows 2004（120.27512.10351.0）
* 浏览器（如果使用）Browser (if used)：X

**Comment by 88250** [comment]
你好，我关闭了，如果还有发生请跟帖反馈，谢谢。
