### ISSUE TITLE
`复制纯文本` 时移除所有零宽空格

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6674]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

使用右键菜单 <kbd>复制纯文本</kbd> / <kbd>Shift + Alt + C</kbd> 复制部分元素时复制的内容存在零宽空格
使用该功能复制行内代码后粘贴到 IDE/shell 中运行会出问题

### 描述可能的最优解决方案 Describe the optimal solution

复制纯文本功能移除复制内容中的零宽空格再写入剪贴板

**Comment by MMARVP** [comment]
+1，我也经常遇到这个问题，确实希望这点能够得到改善，纯文本不应该按照目前siyuan的块属性进行空行，在复制纯文本的情况下，应该自动去除空行
