### ISSUE TITLE
内核 复制粘贴 到用户目录，没有修改文件/文件夹权限，导致程序崩溃

### ISSUE THREAD

**Issue by xBLACKICEx** [siyuan-note/siyuan#6676]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

内核 复制粘贴 到用户目录，没有修改文件/文件夹权限，导致程序崩溃

在nixos下完成安装后，所有
文件都会变成 **只读** 模式，因此复制到用户目录下进行可写访问会报错。

![Screenshot_20221121_141501](https://user-images.githubusercontent.com/51036094/203080960-3886486d-9b02-4d81-a032-04a435c7a2c4.png)
![Screenshot_20221121_141901](https://user-images.githubusercontent.com/51036094/203081077-0d1025c9-7cb8-48d2-b9c4-706d826aa0ef.png)

### 期待的结果 Expected result

内核完成复制后 修改文件夹/文件 的  可读权限。

### 版本环境 Version environment

```markdown
- Version: 2.5.0
- Operating System: NixOS
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10057366/siyuan.log)

**Comment by 88250** [comment]
工作空间文件夹的权限需要安装前操作系统用户来手动创建并赋予正确权限。

**Comment by xBLACKICEx** [comment]
尴尬的是 NixOS 下打包的app 安装目录只能是只读模式没法改，内核他不能改变用户目录下的工作空间文件夹权限吗？

还是说 安装目录下也要可写？
