### ISSUE TITLE
文件树展开折叠状态保持

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#668]
### 描述问题 Describe the problem

在某个文件夹上右键-新建文件, 新建成功后, 该文件夹自动转成折叠状态

### 期待的结果 Expected result

维持原来状态, 即如果展开,则维持展开

### 版本环境 Version environment

* 版本 Version：0.5.2
* 操作系统 Operating system：win10 x64
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
感谢反馈，这个问题是实现上的缺陷，目前暂时没有时间进行细化，后期进行改进，谢谢。
