### ISSUE TITLE
希望ctl+/快速编辑引用文本时能保留原始文字

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#6681]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我在使用双链中，非常常用的一个操作就是修改引用文本。
思源可以通过 ctl+/ 快捷进入修改锚文本的界面，这点确实特别方便 (๑•̀ㅂ•́)و✧

但是我发现这里按下ctl+/存在两种效果

第一种是就是 按下 ctl+/ 后，锚文本的编辑界面为空
![image](https://user-images.githubusercontent.com/117956441/203321689-4114f1df-1d71-4949-903f-35138c59b336.png)

第二种则是 按下 ctl+/ 后，锚文本的编辑界面保留原始的文字并且处于选中状态

![image](https://user-images.githubusercontent.com/117956441/203321900-f6f1691b-5583-4869-aad8-f1cc39cfba56.png)

**第二种的泛用性明显好于第一种，既可以删除原始文字，又可以在原始文字的基础上追加内容。希望能稳定触发第二种效果**

### 描述可能的最优解决方案 Describe the optimal solution

**目前如果第一次按ctl+/ 修改引用， 就会出现编辑框为空的效果。
但是很多时候，其实都是在原始文本后面追加文字，比如例子中， 我就得重新打一遍原始的引用文字“思源笔记”再往后追加内容。 自己已经因为这个位置，重复打了好多遍原始的文字。**
![image](https://user-images.githubusercontent.com/117956441/203322279-b1f71563-a086-4987-b784-aef0a7565e3d.png)

所以希望V姐，可以让第一次按ctl+/ 修改引用时，也可以保留原始文字，并处于选中状态。

**Comment by Yuminis98** [comment]
> 留空的时候是动态锚文本，会跟随定义块变化；有内容时是静态锚文本，不跟随定义块内容变化。


好吧，我主要是想方便一点。
因为经常修改锚文本，都是在原始文字后面追加内容。

就导致我每次ctl+/ 都得重新把 原来的文字再打一遍， 所以希望进入编辑界面，可以让原始文本保留下来，并处于选中状态。 
这样我就可以自由选择往后面追加文字或者删掉码别的内容。

**Comment by Yuminis98** [comment]
现在只要是第一次修改，都是留空的效果。 
后面再修改就是我希望的那种效果了。 不过我大部分时候都只会改一次

**Comment by 88250** [comment]
建立块引的时候划选然后用 Alt+[ 搜索，这样建立的块引就是静态锚文本了。

**Comment by Yuminis98** [comment]
> 建立块引的时候划选然后用 Alt+[ 搜索，这样建立的块引就是静态锚文本了。

了解了，原来【【 和  alt+【的效果还不一样诶🙀

**Comment by Yuminis98** [comment]
谢谢
