### ISSUE TITLE
全局热键新建笔记

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6682]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

读电子书的时候

### 描述可能的最优解决方案 Describe the optimal solution

选中文字，按下热键，选中的文字就会复制到一个之前指定好的笔记里。

### 描述候选的解决方案 Describe the candidate solution

按下热键，粘贴板里的文字（图片）就会到一个之前指定好的笔记里。

### 其他信息 Other information

其实是印象笔记的一个功能（从剪切板粘贴）
![image](https://user-images.githubusercontent.com/38936048/203445249-44da2bf6-d6f4-40f6-8025-b9ac59fd9f5a.png)

**Comment by 88250** [comment]
> 一个之前指定好的笔记里。

这个是如何指定的？

**Comment by oijqws** [comment]
> > 一个之前指定好的笔记里。
> 
> 这个是如何指定的？

设置里指定一个文档。

**Comment by 88250** [comment]
这个需求通过外部工具扩展提供更合适，因为思源支持 API 创建/修改笔记，通过外部扩展能更好地适配特性化需求。

感谢提议，我关闭了。

**Comment by oijqws** [comment]
好的，谢谢
