### ISSUE TITLE
导出图片

### ISSUE THREAD

**Issue by hduwhyso** [siyuan-note/siyuan#6683]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

手机端和电脑端

### 描述可能的最优解决方案 Describe the optimal solution

1、手机端文档导出图片希望自动保存到相册
2、文档导出图片清晰度不够
3、文档导出图片有水印，希望可以去掉水印（我的工作场景导致我发的图片不能有水印“”）

**Comment by 88250** [comment]
1. 麻烦自己手动再多点一步
2. 这个估计只能这样了，后续有空我们再看看能否改进
3. 不支持去掉页脚“由思源笔记导出”，我们添加这个的目的是为了帮助思源宣传。如果实在需要去掉，请自行修改源码编译程序

感谢理解。

**Comment by 88250** [comment]
第三点已经去掉了 https://github.com/siyuan-note/siyuan/issues/7838
