### ISSUE TITLE
标签页大小能否统一？

### ISSUE THREAD

**Issue by MMARVP** [siyuan-note/siyuan#6685]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在的标签页，是根据字数多少来决定的，字数多的长一些，字数少的会很短，这样视觉非常的不统一，而且在字数少的时候，因为页签极短，很容易点到X
<img width="572" alt="image" src="https://user-images.githubusercontent.com/118741163/203470898-ed4902dc-091a-4300-8847-cef3091aa0c0.png">

### 描述可能的最优解决方案 Describe the optimal solution

希望可以借鉴下ob的那种标签模式，统一页签大小，无论字数多少，设置一个统一规格，以此减少误操作的可能。
对于字数显示不全的情况，可以通过鼠标悬浮显示。

**Comment by woniuxia** [comment]
我挺喜欢当前这种自适应的

**Comment by 88250** [comment]
这个是为了节省空间设计的，暂时不调整了，感谢反馈。
