### ISSUE TITLE
搜索内容有问题 搜索界面不够大 搜索内容相同时不能合并

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#6689]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

搜索内容有问题 
![image](https://user-images.githubusercontent.com/107289739/203581732-63d42d89-525e-4410-a33f-c42ebf0b88c2.png)

搜索界面不够大 

搜索内容相同时不能合并
![image](https://user-images.githubusercontent.com/107289739/203581979-d4a8523d-5df8-4f7c-ae8a-645d3968ec78.png)

### 期待的结果 Expected result

同上

### 版本环境 Version environment

```markdown
- Version: 最新
- Operating System: win11最新
- Browser (if used):
```

### 日志文件 Log file

不必

**Comment by 88250** [comment]
第一个截图确实不正常，能否导出一个可重现问题的数据集我们测试看看，谢谢。

**Comment by linglongyoudoufu** [comment]
> 第一个截图确实不正常，能否导出一个可重现问题的数据集我们测试看看，谢谢。

用百度云盘还是阿里云盘.
直接导出为思源zip就可以了吗
![image](https://user-images.githubusercontent.com/107289739/203589400-c15f01d9-44f9-4897-9f25-055b37dc1245.png)

**Comment by 88250** [comment]
重建索引以后还是不正常吗？是的话导出 .sy.zip 然后手动删掉 assets 发给我们 845765@qq.com 谢谢

**Comment by linglongyoudoufu** [comment]
好的,但是得等到明天再说

**Comment by 88250** [comment]
好的。

**Comment by 88250** [comment]
暂时还没有收到进一步反馈。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
