### ISSUE TITLE
web clipper 一直停在 Clipping, please wait a moment

### ISSUE THREAD

**Issue by jibwf** [siyuan-note/siyuan#6691]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

要剪辑内容:
https://www.cisco.com/c/en/us/td/docs/dcn/whitepapers/cisco-ndfc-zero-touch-provisioning-using-inband-poap.pdf

当前结果:
思源自动创建了一个新页，里面写着.
Clipping, please wait a moment... 等了半个小时也没完成.

### 期待的结果 Expected result

保存所有内容，包括文字，图片到本地. 

### 版本环境 Version environment

```markdown
- Version: 2.5.0
- Operating System: MACOS 13.0.1 
- Browser (if used):Edge 107.0.1418.56
extend tool version:1.1.4
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10080305/siyuan.log)

**Comment by 88250** [comment]
不支持 PDF 文件剪藏。
