### ISSUE TITLE
安卓版华为手机无法复制选中文字内容

### ISSUE THREAD

**Issue by LecoLu** [siyuan-note/siyuan#6697]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

从一年前开始使用思源，就发现了这个问题，选中文字内容后，没有复制的按钮弹出。

希望修复这个问题。

### 期待的结果 Expected result

选中文字内容后，能弹出复制 剪切等按钮。

### 版本环境 Version environment

```markdown
- Version: 2.5.1
- Operating System: 鸿蒙3系统（其实就是Android 11）
```

### 日志文件 Log file

这个问题日志应该没有记录有。

  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2022/11/24 12:05:47 runtime.go:43: kernel is booting:
    * ver [2.5.1]
    * arch [arm64]
    * pid [26568]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan]
I 2022/11/24 12:05:47 conf.go:100: initialized the specified language [zh_CN]
I 2022/11/24 12:05:47 serve.go:108: listen port elapsed [0ms]
I 2022/11/24 12:05:47 serve.go:115: kernel [pid=26568] is booting [http://127.0.0.1:6806]
I 2022/11/24 12:05:47 sync.go:81: sync before boot
I 2022/11/24 12:05:48 repository.go:519: boot get sync cloud files elapsed [0.76s]
I 2022/11/24 12:05:48 conf.go:617: database size [8.7 MB], tree/block count [71/4648]
I 2022/11/24 12:05:48 working.go:148: kernel booted
I 2022/11/24 12:06:08 repository.go:619: synced data repo [provider=3, ufc=21, dfc=0, ucc=21, dcc=23, ub=453 kB, db=1.1 MB] in [13.67s]
I 2022/11/24 12:06:08 repository.go:714: sync merge result [conflicts=0, upserts=22, removes=0]
I 2022/11/24 12:06:08 repository.go:735: sync merge upserts:
  /20210830105129-02f2rbh/20210414170242-ik78hua.sy
  /20210830105129-ky0m1k6/20210414131024-bihk50k.sy
  /20210830105129-3lhzugh/20210414165319-0iaybqk.sy
  /20210830105129-ky0m1k6/20210414131154-430xmoa/20220915124745-zfa5ewc.sy
  /20210830105129-x86kh8h/20210414160635-51cpli4.sy
  /20210830105129-02f2rbh/20210414170238-8a8fmaq.sy
  /20220917194745-h68k43o/20210516122707-h3xqfl2.sy
  /20210830105129-3lhzugh/20210414165257-mula41k.sy
  /20210830105129-ky0m1k6/20210414131019-gwufqfu.sy
  /20210830105129-ky0m1k6/20210414131154-430xmoa.sy
  /20210830105129-ky0m1k6/20210414163138-mc5uli5.sy
  /assets/image-20221121165320-ef6ci44.png
  /20210830105129-ky0m1k6/20210414131130-iczahl9.sy
  /20210830105129-ky0m1k6/20210414131154-430xmoa/20220308112131-tn3ssqm.sy
  /20220327172912-o6ijbby/20220917193636-ywoiy2i.sy
  /20210830105129-64qhfzm/20210428124539-zea32z0.sy
  /20210830105129-x86kh8h/20210414160700-lxi8tzl.sy
  /20220917194745-h68k43o/20220413115850-arlp08u.sy
  /assets/15e1d7db3bbf42ce9a266b4c0c45fdb-20221124120202-w35chxj.png
  /20210830105129-q59wo12/20210709140320-mvo07eb.sy
  /20210830105129-ky0m1k6/20210414131145-bjhswxd.sy
  /20210830105129-ky0m1k6/20210414131049-p65i6ym.sy
I 2022/11/24 12:06:12 database.go:97: reinitialized database [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2022/11/24 12:06:12 index.go:180: rebuilt database for notebook [20220527140048-0ld7fp6] in [0.23s], tree [count=7, size=168 kB]
I 2022/11/24 12:06:12 index.go:180: rebuilt database for notebook [20210830105129-x86kh8h] in [0.09s], tree [count=7, size=188 kB]
I 2022/11/24 12:06:12 index.go:180: rebuilt database for notebook [20210830105129-ky0m1k6] in [0.19s], tree [count=14, size=669 kB]
I 2022/11/24 12:06:12 index.go:180: rebuilt database for notebook [20210830105129-3lhzugh] in [0.21s], tree [count=7, size=273 kB]
I 2022/11/24 12:06:13 index.go:180: rebuilt database for notebook [20210830105129-02f2rbh] in [0.09s], tree [count=4, size=169 kB]
I 2022/11/24 12:06:13 index.go:180: rebuilt database for notebook [20210830105129-64qhfzm] in [0.06s], tree [count=5, size=100 kB]
I 2022/11/24 12:06:13 index.go:180: rebuilt database for notebook [20210830105129-9nnzbcy] in [0.08s], tree [count=10, size=222 kB]
I 2022/11/24 12:06:13 index.go:180: rebuilt database for notebook [20210830105129-ukj36g5] in [0.02s], tree [count=5, size=73 kB]
I 2022/11/24 12:06:13 index.go:180: rebuilt database for notebook [20210830105129-q59wo12] in [0.02s], tree [count=1, size=56 kB]
I 2022/11/24 12:06:13 index.go:180: rebuilt database for notebook [20220917194745-h68k43o] in [0.05s], tree [count=7, size=207 kB]
I 2022/11/24 12:06:13 index.go:180: rebuilt database for notebook [20220327172912-o6ijbby] in [0.05s], tree [count=4, size=64 kB]
I 2022/11/24 12:06:13 index.go:251: resolved refs [2] in [64ms]
I 2022/11/24 12:06:48 box.go:80: auto stat [trees=71, blocks=4674, dataSize=48 MB, assetsSize=46 MB]

**Comment by 88250** [comment]
试试长按。

**Comment by 88250** [comment]
双击是编辑工具栏，长按是右键菜单。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by LecoLu** [comment]
阅读模式下，不管按什么都无用。

![d4597e6207ccb22b9ee57c35d3bcb69](https://user-images.githubusercontent.com/24625475/203706537-42d8b743-e3ed-4eb9-9390-12d24adc4cde.jpg)

**Comment by LecoLu** [comment]
编辑模式下，可以弹出复制按钮。
但是是从选中文本开始就弹出，而不是在选择完成后再弹出。
这个问题不大，但是希望修复阅读模式下无法复制的问题。@88250 
![ff38b024adcf50324967739478a25ff](https://user-images.githubusercontent.com/24625475/203706806-f9ec3d5b-8568-47de-aad1-44e9a4f159f3.jpg)

**Comment by Vanessa219** [comment]
等 https://github.com/siyuan-note/siyuan/issues/6704 修复后，可使用块标的复制功能。
