### ISSUE TITLE
无法通过 toolbar 打开文件

### ISSUE THREAD

**Issue by scvoet** [siyuan-note/siyuan#670]
### 描述问题 Describe the problem

在通过 toolbar 上图标打开文件时失败，稍后我打开了 console 查看了相关报错信息。

```
main.54f516a95e065c3fdee2.js:4 Uncaught TypeError: Cannot read property 'length' of null
    at Object.t.initFile (main.54f516a95e065c3fdee2.js:4)
    at HTMLDivElement.<anonymous> (main.54f516a95e065c3fdee2.js:1)
```

### 期待的结果 Expected result

一切正常

### 截屏或录像 Screenshot or video

![图片](https://user-images.githubusercontent.com/45708948/101366100-83800600-38df-11eb-846d-198de56dd472.png)

### 版本环境 Version environment

* 版本 Version： 0.5.2
* 操作系统 Operating system：Windows 2004（120.27512.10351.0）
* 浏览器（如果使用）Browser (if used)：X

**Comment by 88250** [comment]
你好，指的是在文件树上打开么？

**Comment by scvoet** [comment]
> 你好，指的是在文件树上打开么？

是最上面一排的第一天 icon

**Comment by 88250** [comment]
麻烦重置界面，然后再试试，谢谢。

**Comment by scvoet** [comment]
> 麻烦重置界面，然后再试试，谢谢。

依旧，报错信息也是。

**Comment by 88250** [comment]
方便的话麻烦把配置还有库打个包发我邮箱，谢谢。

**Comment by scvoet** [comment]
> 
> 
> 方便的话麻烦把配置还有库打个包发我邮箱，谢谢。

已发送

**Comment by 88250** [comment]
我这儿打开似乎没有问题

![image](https://user-images.githubusercontent.com/873584/101602459-213b1880-3a39-11eb-9da3-5693e2c95b7b.png)

**Comment by 88250** [comment]
要不你关闭一次该笔记本文件夹然后重新打开试试看，如果还是不行，等 v0.5.3 发布以后再试试，谢谢。

**Comment by scvoet** [comment]
在关闭该笔记本后，点击该图标仍无效。但稍后我从 toolbar 中的 `?` 按钮中打开帮助（即该笔记本）后，一切正常了。

玄学
