### ISSUE TITLE
建议书签引入分组与自定义排序特性

### ISSUE THREAD

**Issue by kungjulianis** [siyuan-note/siyuan#6701]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前书签及其暂时内容按添加的时间顺序，在添加得越来越多之后难以有效管理。

### 描述可能的最优解决方案 Describe the optimal solution

建议像文档树一样可以通过拖拽进行分组、自定义排序。

**Comment by 88250** [comment]
这个不考虑了，感谢提议。
