### ISSUE TITLE
只读模式块标复制内容错误

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#6704]

**Comment by LecoLu** [comment]
块标是什么意思，只能复制整块内容，不能自定义选择部分内容进行复制吗？

**Comment by Vanessa219** [comment]
> 块标是什么意思，只能复制整块内容，不能自定义选择部分内容进行复制吗？

嗯，

**Comment by Vanessa219** [comment]
94fb5673d74045f1cd73ca462b97a296afaaae0d

**Comment by Vanessa219** [comment]
> 块标是什么意思，只能复制整块内容，不能自定义选择部分内容进行复制吗？

是的，选择复制可参看 https://github.com/siyuan-note/siyuan/issues/6709
