### ISSUE TITLE
请输入问题报告标题 Please enter the title of the bug report

### ISSUE THREAD

**Issue by YangHgRi** [siyuan-note/siyuan#6705]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

安卓和pc端同步配置相同，数据仓库密匙也相同，就是会创建两个同名文件夹各玩各的。。。

模式是 path style

tls验证是 skip

### 期待的结果 Expected result

两个设备走同一个文件夹然后正常的从pc同步到安卓

### 版本环境 Version environment

```markdown
- Version: 2.5.1
- Operating System: 安卓和windows
- Browser (if used):edge
```

### 日志文件 Log file

晚一点补充

**Comment by YangHgRi** [comment]
破案了，是bucket名有问题。。。前面多了个空格。。。

**Comment by 88250** [comment]
感谢反馈，下个版本会改进参数校验 6f7b04faa07ce55c61ab0c5641395f36078ce117
