### ISSUE TITLE
关闭代码块预览后无法渲染流程图

### ISSUE THREAD

**Issue by scvoet** [siyuan-note/siyuan#671]
### 描述问题 Describe the problem

在编辑器设置中关闭代码块预览后无法渲染流程图、五线谱及代码高亮等。

### 期待的结果 Expected result

一切正常。

### 版本环境 Version environment

* 版本 Version： 0.5.2
* 操作系统 Operating system：Windows 2004（120.27512.10351.0）
* 浏览器（如果使用）Browser (if used)：X

**Comment by 88250** [comment]
你好，目前这是设计如此，因为这些用的都是代码块语法……
