### ISSUE TITLE
使用 API 插入行级元素嵌套 HTML 实体时丢失实体内容

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6714]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

数据库 `markdown` 字段与 API `getBlockKramdown`, `exportMdContent` 返回的内容中行内元素
- `<` 被转义为 `&lt;`
- `>` 被转义为 `&gt;`
- `&` 被转义为 `&amp;`
- `"` 被转义为 `&quot;`

但是使用 API `/api/block/*` 增改块时若在行内元素中使用这些转义符, 增改的块将丢失原字符

比如插入/更新内容为 `**11&lt;22&gt;33&amp;44&quot;55**`, 插入/更新后的块只显示 `**1122334455**`

这样会导致 `导出/查询 → 处理 → 导入` 自动化流程无法正常进行

### 期待的结果 Expected result

输出时与输入时对这些符号处理原则保持一致

#### 解决方案 1

输出时(数据库 `markdown` 字段与 API `getBlockKramdown` 返回的内容)行内元素使用 `\` 转义, 比如使用 `\<` 转义 `<`

#### 解决方案 2

输入时(使用 API `/api/block/*` 增改块)行内元素同时支持解析 `&lt;` 等方式转义的字符

### 版本环境 Version environment

```markdown
- Version: 2.5.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by 88250** [comment]
我这里测试没有重现问题：


![image](https://user-images.githubusercontent.com/873584/203983902-9d3be174-b3a1-427d-b2a1-d966334cd430.png)

使用 insertBlock 插入：

![image](https://user-images.githubusercontent.com/873584/203984204-e51847b3-4f83-4503-82ec-b72e633564cd.png)

但是使用 HTML 实体插入确实有问题：

![image](https://user-images.githubusercontent.com/873584/203984369-9552d82f-41ee-4eb0-87cc-e41ed9685109.png)

我们先改进这个问题。

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里测试没有重现问题

出问题的是行内元素内部的 HTML 转义字符, 例如这个请求体

```json
{
  "dataType": "markdown",
  "data": "**11&lt;22&gt;33&amp;44&quot;55**",
  "id": "20211230161520-querkps"
}
```

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 明白了，谢谢。
