### ISSUE TITLE
展开折叠侧边栏时，编辑面板内容过渡动画不过平滑，跳跃性大

### ISSUE THREAD

**Issue by Jamie-Wan** [siyuan-note/siyuan#6715]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

展开折叠侧边栏时，编辑面板内容过渡动画不过平滑，跳跃性大

### 期待的结果 Expected result

编辑面板的内容根据面板宽度的改变发生变化时，能够过渡平缓，自然变化

### 版本环境 Version environment

```markdown
- Version: 最新
- Operating System: Win10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
目前通过 CSS 动画实现估计只能这样了，如果不需要的话可以用自定义代码片段关闭动画效果，感谢反馈。

**Comment by Jamie-Wan** [comment]
我不确定之前我的问题是否表述清楚，因此我录了一下obsidian和思源笔记的笔记面板缩放效果。在收起展开侧边栏的时候，obsidian编辑的内容是可以看清楚的，思源笔记的内容则用肉眼看不清，字跟着面板的收缩展开而滚动，体验不太舒服。这个现象是由css造成的吗还是其他原因？如果是动画的原因请问如何关闭呢？

![obsidian侧边栏缩放](https://user-images.githubusercontent.com/65280479/205275098-79f1b184-ddd6-46b7-8f7e-c2e82684614b.gif)

![思源笔记侧边栏缩放](https://user-images.githubusercontent.com/65280479/205275135-88293322-bb74-4002-8d22-17e4fcfb6498.gif)
