### ISSUE TITLE
搜索功能 bug

### ISSUE THREAD

**Issue by wizyoung** [siyuan-note/siyuan#672]
### 描述问题 Describe the problem

搜索的时候，往往一个词语还没输入完，就触发了搜索，导致搜索没法正常进行。另外，搜索到多个词后，前后跳转方向箭头点击无效。

### 期待的结果 Expected result

正常工作。

### 截屏或录像 Screenshot or video

![屏幕截图 2020-12-08 000307](https://user-images.githubusercontent.com/13296106/101374156-cb575b00-38e8-11eb-929b-b11dd064dcb3.png)

### 版本环境 Version environment

* 版本 Version：0.5.2
* 操作系统 Operating system：macOS 10.15.6 和 win10
* 浏览器（如果使用）Browser (if used)：None

### 其他信息 Other information
None

**Comment by 88250** [comment]
你好，这是一个已知缺陷，将在 https://github.com/siyuan-note/siyuan/issues/53 中进行修复，感谢反馈。
