### ISSUE TITLE
[新功能请求]请在"查找"与"查找与替换"中加入正则的支持

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#6721]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在使用"查找"与"查找与替换"的时候,有正则可以便利很多

### 描述可能的最优解决方案 Describe the optimal solution

可以像vscode一样,在"查找"与"查找与替换"的菜单中加入一个是否启用正则的选项
[![ztxrbF.png](https://s1.ax1x.com/2022/11/26/ztxrbF.png)](https://imgse.com/i/ztxrbF)

**Comment by 88250** [comment]
搜索支持正则的，但是需要用 SQL 语句：

```sql
select * from blocks where content regexp 'foo\\d+.*'  
```

不过目前替换功能似乎有 bug，在 https://github.com/siyuan-note/siyuan/issues/6722 中排查。
