### ISSUE TITLE
选中块按下Ctrl+L 不会建待办事项

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6723]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

选中块按下Ctrl+L 不会建待办事项，会把当前文本删除
![image](https://user-images.githubusercontent.com/38936048/204088860-d7d04539-18cc-4ddd-ab99-eab014cb0ce8.png)

### 描述可能的最优解决方案 Describe the optimal solution

按下C+l 把当前块设为待办事项

**Comment by 88250** [comment]
Ctrl+L 不支持转换块类型，所以请使用块类型转换。
