### ISSUE TITLE
希望docker版也能导出方便好用的pdf文件

### ISSUE THREAD

**Issue by lerogo** [siyuan-note/siyuan#6727]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

很多

### 描述可能的最优解决方案 Describe the optimal solution

加入功能，链接到资源库或者保存到tmp目录，一定时间后清理。

**Comment by 88250** [comment]
感谢反馈，但是这个估计无法实现，因为桌面端使用的是 Electron 的 API 导出的，浏览器上没有支持。

**Comment by demoshang** [comment]
> 感谢反馈，但是这个估计无法实现，因为桌面端使用的是 Electron 的 API 导出的，浏览器上没有支持。

https://developer.mozilla.org/en-US/docs/Web/API/Window/print
使用 原生 打印预览 + iframe 是否可以实现 打印?

**Comment by 88250** [comment]
可以帮忙试试。
