### ISSUE TITLE
块引创建文档时支持指定路径

### ISSUE THREAD

**Issue by EndlessErrors** [siyuan-note/siyuan#673]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

现在用[[ ]]只能在当前文件夹内创建新文档，在新文档不适合分到当前文件夹时需要手动移动，较麻烦。

### 描述最优的解决方案 Describe the optimal solution

希望用下面的语法可以指定新建文档所在的文件夹：
`[[/文件夹/文件名]]`
比如在编辑B文件夹文档时想在A文件夹新建一个C文档，可以用：`[[/A文件夹/C]]`
![图片](https://user-images.githubusercontent.com/57283205/101423244-958b9400-3933-11eb-8bf1-49fbfd767345.png)

### 描述候选解决方案 Describe the candidate solution

无

### 其他信息 Other information

1.建议加入文件夹模糊搜索，比如 "\微积分" 可以匹配到 "学习\数学\微积分"
2.建议自动将中文顿号"、" 识别为  "\\"

**Comment by 88250** [comment]
v0.5.4 支持，其他信息中提到的优化暂时不考虑，谢谢。
