### ISSUE TITLE
导出图片的时候似乎有内存泄漏

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#6738]
https://user-images.githubusercontent.com/58081876/204332156-3978aa0a-b93c-433b-a040-9998ea67132f.mp4

版本：windows平台 V2.5.2

**Comment by BryceAndJuly** [comment]
嗯，刚刚重新试了一下，跳到2G多内存之后，还要等久一点才能弹出图片。之前杀进程杀早了。不过文档才几百字要等这么久确实有点慢。

**Comment by 88250** [comment]
这篇文档我这里在默认主题下导出图片正常的：

![issue](https://user-images.githubusercontent.com/873584/204424680-beb77c33-3b6f-4396-9e06-c1c096cf2de8.gif)

**Comment by BryceAndJuly** [comment]
好，我到时卸载重装试试。
