### ISSUE TITLE
能右键直接复制为markdown格式吗

### ISSUE THREAD

**Issue by LiWenGu** [siyuan-note/siyuan#674]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

在思源上写完文档后，需要复制到公司的 wiki 平台，wiki 平台支持markdown语法，但是思源只能导出为 markdown 文件，不能直接右键复制为 markdown 格式，每次改动都要导出为文件覆盖再复制比较麻烦。

### 描述最优的解决方案 Describe the optimal solution

右键增加复制为 markdown 语法
![image](https://user-images.githubusercontent.com/15909210/101449931-a3a5d880-3964-11eb-8651-3ecff94444b3.png)

### 描述候选解决方案 Describe the candidate solution

无

**Comment by 88250** [comment]
你好，直接复制就是 Markdown 文本了。

**Comment by 88250** [comment]
我关闭了，如果还有问题请继续跟帖，谢谢。
