### ISSUE TITLE
paste from onenote

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6742]
如果从OneNote粘贴会变成图片
如果从OneNote粘贴到word，然后再到思源就没问题。
不知道粘贴前是否可以调用一下word，然后再粘贴？

**Comment by 88250** [comment]
这个估计是 OneNote 的特性吧。

> 不知道粘贴前是否可以调用一下word，然后再粘贴？

不行。

我关闭了，谢谢。
