### ISSUE TITLE
几个新功能

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#675]
1希望增加点击快的时候能出现一个在下方/上方插入新的行的功能
![image](https://user-images.githubusercontent.com/11142054/101464251-60099980-3979-11eb-895a-5484bcefdc88.png)
为什么要这么做？举个例子，比如我没有在代码块的后面空格，那么我回车的时候，依然处在代码块中，比如我插入了一个图片，后来发现还需要在后面键入的新的行，对图片结果做出说明，这种我就无法直接在图片后面回车插入空行，而如果是对下一段(块)内容回车，比如我图片后面跟的是列表，那么我回车就又变成列表了，而不是普通文本，这样就很麻烦。

2希望能拖动图片的四角直接修改图片的大小（就像word中一样）

**Comment by 88250** [comment]
你好，

1. 编辑器已经支持在上方或者下方插入行
   ![image](https://user-images.githubusercontent.com/873584/101477055-a1a24080-3989-11eb-8495-fb3c25ce6048.png)
2. 图片大小调整将在 https://github.com/siyuan-note/siyuan/milestone/34 中进行实现

感谢反馈。
