### ISSUE TITLE
无法添加题头图标签

### ISSUE THREAD

**Issue by Yinxihao** [siyuan-note/siyuan#6756]
使用版本V2.5.2最新版, 无法添加题头图上方标签
![image](https://user-images.githubusercontent.com/15810068/204950436-68c84522-b57c-4a9f-a9ba-cace922d802a.png)

**Comment by 88250** [comment]
没有使用 css/js 代码片段或者自定义主题吧？

**Comment by Yinxihao** [comment]
没有

**Comment by 88250** [comment]
请再看下开发者工具 Network 中 searchTag 的返回值：

![image](https://user-images.githubusercontent.com/873584/204952796-f17e9325-b721-47ab-856f-b2b1e694d69b.png)

**Comment by Yinxihao** [comment]
![image](https://user-images.githubusercontent.com/15810068/204953260-7cda075e-7f7d-4def-884b-383d2c804909.png)

**Comment by 88250** [comment]
麻烦上传一下内核日志，位于工作空间/tem/siyuan.log

**Comment by Yinxihao** [comment]
[siyuan.log](https://github.com/siyuan-note/siyuan/files/10128832/siyuan.log)

**Comment by 88250** [comment]
重建索引后再试试，如果还是不行，能否将整个工作空间打包发给我试下 845765@qq.com

**Comment by Yinxihao** [comment]
![image](https://user-images.githubusercontent.com/15810068/204954458-ad64734e-a5ee-4e75-9a0f-fb82f79a047a.png)
重建索引后 正常  请问这是什么原因导致的？

**Comment by 88250** [comment]
标签搜索依赖数据库，数据库状态不正常的话会有问题。

这个后面我们看下如何改进，我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Yinxihao** [comment]
辛苦， 多谢你的耐心解答~

**Comment by 88250** [comment]
也有其他用户遇到，目前暂时还无法定位到问题，先记录 https://ld246.com/article/1670049406782

**Comment by 88250** [comment]
下个版本我们先添加一些日志记录看看能否定位到问题。

**Comment by 88250** [comment]
请问各位这个问题在 v2.5.3 是否还能重现？麻烦提供一下日志以帮助我们定位下问题，谢谢。

**Comment by Yinxihao** [comment]
我这边自从上次重建索引后，到目前为止还没有重现。上次提交issue发你的日志有看出什么问题么?


| |
老断
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年12月9日 20:39 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [siyuan-note/siyuan] 无法添加题头图标签 (Issue #6756) |

请问各位这个问题在 v2.5.3 是否还能重现？麻烦提供一下日志以帮助我们定位下问题，谢谢。

**Comment by 88250** [comment]
@Yinxihao 之前的日志上看不出问题，后面我们又加了些日志。这样吧，我们先关闭 issue 了，如果后面还有问题麻烦继续跟帖，谢谢。
