### ISSUE TITLE
iOS 端外部链接跳转问题

### ISSUE THREAD

**Issue by mzcxiaohuanxiong** [siyuan-note/siyuan#6757]
思源笔记在ios客户端下，https的链接可以正常跳转。其它软件的外部链接无法跳转。如跳转zotero的外部链接zotero://open-pdf/library/items/K3X5ZW5E?page=39&annotation=G2YR2NFA   。zotero客户端支持外链跳转，并用obsidian笔记软件进行了测试，跳转正常。

**Comment by Vanessa219** [comment]
试了一下 PC 端是可以的，只是 iPhone 不行。你这里指的是 iPhone 么？

**Comment by mzcxiaohuanxiong** [comment]
感谢回复。是ipad。iPhone我没试过。




meng_zc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 中午12:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 改进 iOS 端外部链接跳转 (Issue #6757)





 
试了一下 PC 端是可以的，只是 iPhone 不行。你这里指的是 iPhone 么？

**Comment by Vanessa219** [comment]
好的，麻烦下个版本再看看。

**Comment by mzcxiaohuanxiong** [comment]
好的，谢谢。辛苦啦




meng_zc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月6日(星期二) 上午9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] iOS 端支持打开 `zotero://` (Issue #6757)





 
好的，麻烦下个版本再看看。
