### ISSUE TITLE
搜索类型选项加入确定按钮

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6759]
![image](https://user-images.githubusercontent.com/873584/205027851-626046bc-49b2-4b9f-8bce-69ac483eb94e.png)

加入确定按钮，避免每次选择后就消失进行搜索。

另外，这个地方好像无法点击：

![image](https://user-images.githubusercontent.com/873584/205028419-8340dbf8-12ed-4915-9686-293820330e28.png)

**Comment by Vanessa219** [comment]
包含子文档移动到指定路径前
