### ISSUE TITLE
卡片和复习功能

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#676]
**想要一个卡片功能，基于两个设想**
1卡片可能是收集碎片化信息收集比较方便的一种方式，以免大量信息的堆积（作为纯信息收集的笔记软件最终都会被边缘化）
2更终于的是，想借助卡片功能，实现复习的功能，做笔记的最终目的终究是信息的吸收和转化。但是很多笔记工具，都沦为记录的工具，很多东西都是想起来了靠检索才查到，其实可以考虑通过卡片的方式，做一定的复习和回归
关于这一点，我觉得初期其实不必考虑像anki一样的严格的按照记忆曲线复习，因为那样只会导致卡片量巨大，造成很大的记忆负担，阻止人复习和回归
当然如果能跟anki之类的软件结果，可能又会成为软件一个新的吸引用户的点。
在这个功能的实现上，我觉得既然目前思源可以对每一段都进行关系映射和引用，那么创建卡片也很简单的。直接设置一个正面（标题或问题），再在下面对应一个对话框贴入块引用就行了。这样就可以把复习回顾（碎片化）和笔记整体结合起来
类似的软件有日本的mochi、还有国外的remnote

再补充一点，建议出一个主页视图，显示日历，笔记时间抽，做一点的数据可视化。
这个可以参考在为知笔记的主页的基础进行优化提升。
这个可以作为一个长期的功能吧
为什么需要它？
直观的可视化展现，也是一种激励用户持续创作的动力啊
就像丰富的编辑功能，一个良好的视觉效果，本身就有让作者在写笔记的时候心情愉快、充满创作激情的功能。

**Comment by deerainw** [comment]
仅仅做个卡片正面背面还是不难，这个是编辑器层面的，麻烦的是自适应算法。anki 使用的是开放的 supermemo2 算法，不说实现一遍，光展示给用户的配置参数就已经一大堆了。
另外要制卡的话势必引入一堆 meta info，这也是需要考虑的问题。
用 win 的话，其实可以直接靠 quicker 来实现笔记软件和 anki 的联动：https://zhuanlan.zhihu.com/p/245218259

**Comment by yanyu2015** [comment]
> 仅仅做个卡片正面背面还是不难，这个是编辑器层面的，麻烦的是自适应算法。anki 使用的是开放的 supermemo2 算法，不说实现一遍，光展示给用户的配置参数就已经一大堆了。
> 另外要制卡的话势必引入一堆 meta info，这也是需要考虑的问题。
> 用 windows 的话，其实可以直接靠 quicker 来实现笔记软件和 anki 的联动：https://zhuanlan.zhihu.com/p/245218259

你说的是对的，其实也没有强求算法
我感觉知乎上的文章还是搞负责了
其实以前有人做过插件，可以直接把markdown笔记特定形式的内容导出到anki的
但是我觉得把笔记和知识转化结合是一个比较好的思路。
哪怕是能够较好地和一些记忆类的软件融合

或者其实可以考虑一个笔记工具适合的复习回顾方式。希望大家集思广益吧

**Comment by Tokubara** [comment]
复习一直是我很在意的功能, 软件提供了外链, 可以导出到anki. 但外链体验目前还算不上特别好, 延迟有几秒.
keep it simple stupid.能做到markdown编辑器中的最好就行了, 不要满足每个用户而强加各种功能, 一般来说, 这些功能已经有软件实现了, 只要有完善的外链, 就可以与各种软件结合起来.
插件生态我不懂, 没研究过marginnote的插件是怎么写出来的. 但我觉得有能力以及有闲情逸致写插件的人未必很多, 可能真正会写的也就几个人, 如果也要软件的开发者写, 插件就只不过是个形式.

**Comment by Maxpiner** [comment]
Anki还是有一定的门槛的，实现起来恐怕也有不小的难度，这些较为复杂的功能还是通过和Anki的对接实现比较好，专业的事情还是专业的软件做，由专业的用户自己去定制。
而对于我这样没什么兴致折腾卡片的人来说，能够快捷地将选中的内容转化为卡片发送到对应集合里，需要时拿出来看看回顾回顾，能够跳转回源头，就基本上够用了。等有了时间和兴趣后再去研究高级功能也不迟。
如果思源能够同时提供简易的卡片功能和与Anki的对接，满足普通用户和专业用户不同层次的需求，应该是比较好的方法。

**Comment by Tokubara** [comment]
感觉外链就是很好的方式, 如果是导出, 我觉得它和marginnote不同, 这里是一篇文档, 塞在一张卡片不合适. 也没啥用. 所以我觉得最简单的办法就是提高外链的响应速度.

**Comment by 88250** [comment]
通过链接和其他软件联动是不错的选择，感谢各位讨论。

**Comment by yanyu2015** [comment]
> Anki还是有一定的门槛的，实现起来恐怕也有不小的难度，这些较为复杂的功能还是通过和Anki的对接实现比较好，专业的事情还是专业的软件做，由专业的用户自己去定制。
> 而对于我这样没什么兴致折腾卡片的人来说，能够快捷地将选中的内容转化为卡片发送到对应集合里，需要时拿出来看看回顾回顾，能够跳转回源头，就基本上够用了。等有了时间和兴趣后再去研究高级功能也不迟。
> 如果思源能够同时提供简易的卡片功能和与Anki的对接，满足普通用户和专业用户不同层次的需求，应该是比较好的方法。

我说一下我的看法
1专业的事情让专业的软件做是对，前提是专业的软件真的是实现新需求的正确模式。
anki的强大是毋庸置疑的，但是这种碎片化的学习方式的弊端是无法克服的。
anki适合有比较好的卡片素材下的**应试**场景。
而之所以在笔记软件上需要复习或回顾功能，肯定是因为用户群体有了新的需求
**不然rem、mochi、专注笔记不会都在这个方向发力对不对？**
就像大家一拥而上做双链一样，这绝对是未来的一个大趋势，谁先领悟了谁有占据先机。
**说回来，笔记形式的复习和anki有什么不同？
1)一篇笔记，通篇的话只需要简单过一下，全部背下是不现实且低效的行为——只需提醒复习回顾
2)重要的点才需要记忆
——卡片复习，然后快速定位到原文，找到跟其他知识点之间的联系
3在此基础上，能够有一些统计功能以激励用户复习就更好了
**


2关于插件
其实建议D大可以参考为知笔记的一个插件，以前实现过这种功能
但是比较简陋
所以我希望还是集成到思源本身中吧，不然又是一个有点鸡肋的功能了。
