### ISSUE TITLE
同步失败增加切换代理服务器

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6768]
同步失败的时候，是否可以增加一个按钮询问是否打开/关闭代理服务器？谢谢
![image](https://user-images.githubusercontent.com/38936048/205214194-8b9d4cf5-2038-484f-bd5a-1ac87459a4ac.png)

**Comment by 88250** [comment]
目前看可能大部分用户不需要，我们就暂时不考虑添加了，关于自动切换代理我们之前也讨论过 https://github.com/siyuan-note/siyuan/issues/6667
