### ISSUE TITLE
IOS同步只要修改就会使同步中提示数据已损坏

### ISSUE THREAD

**Issue by kevencoff1116** [siyuan-note/siyuan#6770]
使用webdav同步，电脑端正常使用，IOS同步，修改一点东西就会提示数据已损坏，需要重新删除备份重新上传数据了。

**Comment by 88250** [comment]
不要多个端同时在线同步，具体请参考用户指南云端同步章节。

**Comment by kevencoff1116** [comment]
只有两端，而且都是同步关闭一个，再打开另一个

**Comment by 88250** [comment]
重置一下云端后再试试吧。
