### ISSUE TITLE
“文字大爆炸”功能

### ISSUE THREAD

**Issue by aptexd** [siyuan-note/siyuan#6772]
希望给增加类似锤子手机得“文字大爆炸”功能
类似很多安卓手机得文字爆炸功能以及界面
类似微信图片得“提取文字”功能
考虑到图片 OCR 通常需要联网，可能不适合思源
找到以下两个 Go 语言分词开源项目，希望可以对开发者有所帮助
[huichen/sego: Go中文分词](https://github.com/huichen/sego)
[yanyiwu/gojieba: "结巴"中文分词的Golang版本](https://github.com/yanyiwu/gojieba)
BTW：不知为何这次没有之前 issue 的模板了

**Comment by aptexd** [comment]
炸开文字后
1. 选中词，弹出不同选项，比如拆成单字、删除、复制
2. 选中后再长按，可以拖动到不同的词汇之间

**Comment by 88250** [comment]
对于图片的话需要 OCR 支持，如果要做的话估计只能是云端 OCR，本地的性能和准确率可能不大行。

现阶段暂时不考虑引入新特性了，感谢提议。
