### ISSUE TITLE
支持创建未来日期的 Daily Note

### ISSUE THREAD

**Issue by aptexd** [siyuan-note/siyuan#6773]
通过日历点击到未来日期
通过当前的模板日期，创建未来日的 Daily Note
此功能可以不用熬过 0 点，写下明日待办
可以在更远的日期提醒待办
提醒纪念日
提醒好友生日等 
如果该日期没有对应路径，则依次创建
因为已有“日历”面板，便可任意查看 Daily Note

**Comment by aptexd** [comment]
很多人抱怨这个，竟然没搜到
不知道是搜的关键词不对
还是就我“大聪明” [狗头]

**Comment by 88250** [comment]
日历不是思源内置的功能，目前暂时不考虑引入新特性了，感谢提议。
