### ISSUE TITLE
行级下标后标记出现部分空白

### ISSUE THREAD

**Issue by yulin011** [siyuan-note/siyuan#6775]
下标后的字符如果被高光标记或者改为键盘格式
会出现如下图所示的上部空缺问题
<img width="779" alt="image" src="https://user-images.githubusercontent.com/87841321/205423606-bfb2f11c-0d9b-4e65-b263-4f0b2d20b668.png">

**Comment by yulin011** [comment]
键盘布局出现空缺，如下所示
<img width="779" alt="image" src="https://user-images.githubusercontent.com/87841321/205423926-1176da8c-cb85-4b94-9aad-499f21187f67.png">

**Comment by Vanessa219** [comment]
目前只能取消 g 的下标标识。当 g 被标识为下标时，它的整个元素就会下沉并缩小。
