### ISSUE TITLE
任务列表换行时对勾不移动

### ISSUE THREAD

**Issue by Kanaricc** [siyuan-note/siyuan#678]
### 描述问题 Describe the problem

在使用过程中遇到一些略影响体验的小 bug。

* 当在任务列表中的特定位置换行创建新任务时，原本的勾选状态还会保持在原位。
* 导出的 HTML 中图片无法显示。URL不应该用相对路径。

### 期待的结果 Expected result

* 打勾项目应随回车移动到下一行。
* HTML中图片使用127.0.0.1的绝对URL。

### 截屏或录像 Screenshot or video

![test12](https://user-images.githubusercontent.com/46213939/101484670-f1d2d000-3994-11eb-9bd0-a52c1db0a92f.gif)

### 版本环境 Version environment

* 版本 Version：v0.5.2
* 操作系统 Operating system：Windows 10

**Comment by 88250** [comment]
感谢反馈，任务列表这个估计暂时做不了；图片路径问题已经修复，谢谢。
