### ISSUE TITLE
弹窗或关闭窗口应关闭无关的菜单

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6783]
### 描述问题 Describe the problem

- 现在的选项弹窗是由鼠标点击位置确定
- 多次点击均为弹出
- 部分弹窗在进入其他页面后仍未消失

### 期待的结果 Expected result

* 固定弹出位置
* 点击弹出，再次点击关闭
* 进入其他页面后弹窗消失

### 截屏或者录屏演示 Screenshot or screen recording presentation

![test](https://user-images.githubusercontent.com/101307399/205540967-5da14bc0-0e00-43d7-878d-21bcdd9de5b5.gif)

### 版本环境 Version environment

```markdown
- Version: v2.5.2
- Operating System: Windows 10
```

**Comment by Temacc0531** [comment]
1. 其他软件我看了下基本都是按固定位置弹出的😂，近不近的这么短的距离其实影响不大，但是固定的话会方便建立肌肉记忆
2. 按钮再次点击则可以改成点击开启点击关闭或者每次点击都有个重新打开的动作，这样用户重复点击才是有反馈的

**Comment by Temacc0531** [comment]
> 1. 其他软件我看了下基本都是按固定位置弹出的😂，近不近的这么短的距离其实影响不大，但是固定的话会方便建立肌肉记忆
> 2. 按钮再次点击则可以改成点击开启点击关闭或者每次点击都有个重新打开的动作，这样用户重复点击才是有反馈的

@Vanessa219 @88250

**Comment by Vanessa219** [comment]
1. IDE 上Project、页签等菜单等都没有按固定位置弹出，采取的都是就近原则。
2. 对于菜单第二次点击消失的交互应该很少见吧。
