### ISSUE TITLE
插入绘图块时希望提供案列

### ISSUE THREAD

**Issue by mingyong-g** [siyuan-note/siyuan#6785]
## 插入绘图块时希望提供案列
> 如题，插入绘图块时希望提供案列
初步梳理，涉及以下图标块
- ABC
- Chart
- FlowChart
- Graphviz
- Mermaid
- MInd map
- PlantUML

**Comment by terwer** [comment]
自己制作一个模板就行了

![image](https://user-images.githubusercontent.com/3259282/205582635-93190cfb-9b36-4564-b7f4-5f008018b764.png)

**Comment by terwer** [comment]
扔到 data/templates里面 / 模板 就行了，需要的拿走

思源图表模板.zip

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
