### ISSUE TITLE
支持选项卡切换的快捷键

### ISSUE THREAD

**Issue by chennbnbnb** [siyuan-note/siyuan#6789]
希望能够增加一个选项卡切换的功能, 比如command+左方向键, 就可以切换到当前页面左边一个页面, 这样配合pin page和page的状态栏十分方便
如下: 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/42932041/205646423-97607502-d022-4f04-a905-f80548d3323a.png">

**Comment by 88250** [comment]
试试 Ctrl+Tab，还有长按 Ctrl+Tab
