### ISSUE TITLE
公式块复制和预览堆叠问题

### ISSUE THREAD

**Issue by Maxpiner** [siyuan-note/siyuan#679]
### 描述问题 Describe the problem

反馈公式相关的两个问题：
（1）无法部分复制公式代码；当选中部分内容右击复制，粘贴后显示的是却是整个公式。
（2）引用预览时有推挤在一块的问题
例如说下面这段公式代码，我只选中了`\tag{6.2.1}`并复制，然后粘贴到网页上的结果表明实际上复制的是整个公式代码。

````````markdown
y(x_{i+1})=y(x_i)+\int^{x_{i+1}}_{x_i}f(x,y(x))dx
\tag{6.2.1}
````````
在其它地方引用这个公式，预览时就会出现图中堆挤在一起的问题。

### 期待的结果 Expected result
可以复制公式代码的部分内容。
扩大预览窗口宽度，分行或者部分显示

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/26576290/101490939-0798c300-399e-11eb-9e3d-71a8220d90df.png)

### 版本环境 Version environment

* 版本 Version：0.5.2
* 操作系统 Operating system：win10, 1909
* 浏览器（如果使用）Browser (if used)：

**Comment by Vanessa219** [comment]
目前窗口已经放大，不会堆叠

至于数学公式复制可以点击后在编辑区域进行复制
