### ISSUE TITLE
Docker 部署 HTTPS 下不显示网站 ICON

### ISSUE THREAD

**Issue by jianhong-li** [siyuan-note/siyuan#6792]
版本: 2.5.2 (Docker版)

![image](https://user-images.githubusercontent.com/5171385/205664441-d3f6d118-91e9-4feb-a7f1-d559fcf2b7a0.png)

使用HTTPS链接时. 不展示网站ICON. 确认图片加载没有问题. 使用http链接可以正常展示.

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by jianhong-li** [comment]
﻿可以访问，by the way，后面不知道为何今天访问图标又出来了。（未做任何变更）

发自我的iPhone
