### ISSUE TITLE
`优化排版` 支持行级元素加粗、斜体等

### ISSUE THREAD

**Issue by Joker-lkc** [siyuan-note/siyuan#6800]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

希望能够优化排版优化功能，数字和中文隔开，在有样式（加粗等情况下）无法被自动优化

### 期待的结果 Expected result

希望能够优化排版优化功能，数字和中文隔开，在有样式（加粗等情况下）无法被自动优化

### 版本环境 Version environment

```markdown
- Version: win11
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

希望能够优化排版优化功能，数字和中文隔开，在有样式（加粗等情况下）无法被自动优化

**Comment by 88250** [comment]
麻烦截图描述一下样式区隔情况。

**Comment by Joker-lkc** [comment]
![image](https://user-images.githubusercontent.com/56438623/205826517-5ba73a95-887d-45b4-8e52-ccd4dc31e561.png)
这是同样文本，一个没加粗，一个加粗后，自动优化排版的结果

**Comment by 88250** [comment]
嗯，这个情况应该是需要插入空格的，我们后续看下是否能解决，感谢反馈。

**Comment by Joker-lkc** [comment]
好的，期待改进。也可以添加一个，实时优化排版，或者5分钟优化一次，或者是优化排版的快捷键，我每次都需要手动按，经常按，有些麻烦了。

**Comment by 88250** [comment]
实时的不行，之前尝试过，输入法兼容问题比较多。

后面我们看下是不是能加快捷键。

**Comment by Joker-lkc** [comment]
好的

**Comment by Joker-lkc** [comment]
希望优化，数字和符号之间自动空格的问题

**Comment by 88250** [comment]
> 希望优化，数字和符号之间自动空格的问题

这个好像没有约定俗成的规则。

**Comment by Joker-lkc** [comment]
> > 希望优化，数字和符号之间自动空格的问题
> 
> 这个好像没有约定俗成的规则。

https://github.com/sparanoid/chinese-copywriting-guidelines 参考的这个，markdown一些书写的规范

**Comment by 88250** [comment]
数字和符号之间好像不推荐：

![image](https://user-images.githubusercontent.com/873584/205861935-77fb51db-52be-43ab-9207-15f3fbce267c.png)

**Comment by Joker-lkc** [comment]
啊，我是说 1+2=3 应该优化成 1 + 2 = 3 这样

**Comment by Joker-lkc** [comment]
> 是这样

**Comment by 88250** [comment]
那还是不加了，数字和符号保持原样比较好。

**Comment by Joker-lkc** [comment]
希望可以引进这个库 https://github.com/sivan/heti 用来优化排版
