### ISSUE TITLE
`Ctrl+Shift+↑/↓` 子项可移动到上下无子项的列表中

### ISSUE THREAD

**Issue by aptexd** [siyuan-note/siyuan#6802]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/15101966/205993970-9dbb7711-01f0-42b5-9bca-0864467a6082.png)
上图，这种情况下，按 `ctrl + shift + 方向下` 无法移动到下方父节点
![image](https://user-images.githubusercontent.com/15101966/205994376-1b46e091-eff4-4d68-8003-455e0a15dadd.png)
想要移动，就必须在下方父节点的下层建立一个空白节点，才能移动下来

### 期待的结果 Expected result

在同级子节点移动列表项时
即使目标子节点位置为空
也可以移动成功

### 版本环境 Version environment

```markdown
- Version: 2.5.3
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

no

**Comment by 88250** [comment]
你移动的是段落还是列表项？

**Comment by aptexd** [comment]
> 你移动的是段落还是列表项？

“B 站看了……”的列表项

**Comment by 88250** [comment]
同级只有一个列表项的话不能上下移动的，因为只有它自身一个节点啊。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Vanessa219** [comment]
我这里空项是可以移动的，是这样操作么？

https://user-images.githubusercontent.com/970828/206336567-8627bdac-e988-4cfd-8126-30b39b5ac17f.mp4

**Comment by aptexd** [comment]
@Vanessa219 按照演示视频，应该是 2 的子项不论是否为空都可以移动过来，这样才比较合理
