### ISSUE TITLE
修改标题以后alt+5就会创建新文档

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#6813]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如题
![image](https://user-images.githubusercontent.com/117956441/206200464-7ba0165d-8efb-4efa-8168-3094c16cc8c5.png)

### 期待的结果 Expected result

不会出现重复创建新文档

### 版本环境 Version environment

```markdown
- Version: 2.5.3
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10176770/system-log.zip)

**Comment by Yuminis98** [comment]
> 日记是按照文档名来判断是否重复的，如果文档名不一致则创建。

可是如果不在标题上面进行补充说明，我点开文档树，看到的就是一堆日期，人都是茫然的，我不一个一个点进去，完全不知道每一天主要发生了什么
![image](https://user-images.githubusercontent.com/117956441/206333086-19848dad-ed35-404d-8ae7-7007ea45f085.png)
所以我才想在dailynote标题上附加上这一天的总结，让自己能够一目了然的区分每一天。
![image](https://user-images.githubusercontent.com/117956441/206333375-13c5e0b2-4092-4ca4-92a8-9b32b16e5abd.png)
![image](https://user-images.githubusercontent.com/117956441/206333433-b9b63e08-c9bb-48a8-a5a9-1d7663fa1a2a.png)

**Comment by Yuminis98** [comment]
可以只按照文档上的日期名字来判定吗？

**Comment by 88250** [comment]
是的，双链 Daily note 的用法都是这样的。
