### ISSUE TITLE
访问授权页忘记授权码提示文案

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6822]
![image](https://user-images.githubusercontent.com/873584/206469168-b5b1d954-da53-4b89-852f-58cc316cdce8.png)

**Comment by 88250** [comment]
@tcmtom 前提是他能直接访问到工作空间文件。

**Comment by tcmtom** [comment]
> 

工作空间可不是加密的呀，我在想思源能不能调用Windows Hello呀。

**Comment by 88250** [comment]
工作空间不是加密的，所以能接触到工作空间文件的话也没有必要走授权页了。

我也不太清楚能不能调用 Windows Hello :joy:

**Comment by tcmtom** [comment]
> 工作空间不是加密的，所以能接触到工作空间文件的话也没有必要走授权页了。
> 
> 我也不太清楚能不能调用 Windows Hello 😂

明白这个逻辑了👍

**Comment by Soltus** [comment]
支持Windows Hello不如支持Windows账号登录
![image](https://user-images.githubusercontent.com/83791825/206483072-7c46fc20-9c36-4ca3-8958-3da72ddda231.png)

**Comment by Nauh521** [comment]
😂应该写：为防止忘记密码，请将密码写在便利贴上并粘贴到显示器边框

**Comment by UFDXD** [comment]
真是亲切的提示，本来还有点作用的，现在直接教你撬锁了
