### ISSUE TITLE
搜索支持按相关度排序

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6827]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

搜索的时候
搜索nokia id 的时候，我的笔记里有 Nokia id 也有 Nokia Identity，
这2种情况排在前面是不是更加合理？
谢谢
![image](https://user-images.githubusercontent.com/38936048/206612031-7af6a0a7-286e-478c-8fef-b2b171cce014.png)

### 描述可能的最优解决方案 Describe the optimal solution

优先全字匹配

### 描述候选的解决方案 Describe the candidate solution

全字匹配选项

**Comment by 88250** [comment]
目前的排序规则有这些：

![image](https://user-images.githubusercontent.com/873584/206612750-fc50a28c-ce64-4f94-a3ee-400dba176e5a.png)

可能还缺一个按搜索评分排序？

**Comment by 88250** [comment]
下个版本支持按相关度排序：

![image](https://user-images.githubusercontent.com/873584/206622374-b4e5f939-7895-457b-a1c5-55de67ce66c9.png)
