### ISSUE TITLE
列表项剪切撤销触发状态异常

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#6829]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

复现步骤
1. 新建列表块
2. 随便选中一个子块
3. 页面点剪切（使用Ctrl+X也会触发）
4. 撤销 Ctrl+Z
5. 回车

### 期待的结果 Expected result

状态正常

### 截屏或者录屏演示 Screenshot or screen recording presentation

![test](https://user-images.githubusercontent.com/101307399/206618745-ed2b7ce6-e055-4794-95aa-b663a8608bca.gif)

### 版本环境 Version environment

```markdown
- Version: v2.5.3
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by nsx0330** [comment]
![动画](https://user-images.githubusercontent.com/109409892/206625005-e92f0f98-4b3c-4d0b-8efd-056cef5b987b.gif)

**Comment by 88250** [comment]
@nsx0330 请在默认主题下测试是否能重现该问题。

**Comment by nsx0330** [comment]
> @nsx0330 请在默认主题下测试是否能重现该问题。

默认主题也是同样的问题。选中块，右键在选择删除就没问题。
