### ISSUE TITLE
对于路径中的中英文之间自动添加空格

### ISSUE THREAD

**Issue by yanyu2015** [siyuan-note/siyuan#683]
举个例子：
![image](https://user-images.githubusercontent.com/11142054/101559326-d9e26700-39fb-11eb-8cb3-626dc81b7f35.png)
w [wo]
而原始路径是**E:\tm教程**，中间没有空格

考虑到思源点击即可实现，所以我觉得针对路径的时候 不要默认加空格比较好，这样点击路径就能打开本地文件夹就很方便。

**Comment by 88250** [comment]
感谢反馈，自动空格确实有一些问题，类似的还有 https://github.com/siyuan-note/siyuan/issues/489

目前可以先关闭自动空格，或者先形成 []() 链接以后再修改地址。

**Comment by 88250** [comment]
你好，经过考虑我们决定将该选项从编辑生效改为预览/导出生效，请关注 #814 谢谢。
