### ISSUE TITLE
数据是否可以显示搜索结果？

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6830]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

是否可以显示搜索结果
![image](https://user-images.githubusercontent.com/38936048/206632820-7f7ac4f7-b0a1-4fc5-ae50-71eb7865a7b2.png)

### 描述可能的最优解决方案 Describe the optimal solution

显示搜索结果，不输入的时候现在全部最近编辑的文档

### 其他信息 Other information
既然在更新搜索了，麻烦也把这个部分优化一下可以吗？ :-)
谢谢

**Comment by 88250** [comment]
这个需要自己展开左边的条目，之前有用户反馈自动展开不合理。

**Comment by oijqws** [comment]
不可以显示在右边吗？反正右边也空着

**Comment by 88250** [comment]
不自动展开和显示较为合理。
