### ISSUE TITLE
Heading Indentation Feature

### ISSUE THREAD

**Issue by ziran3** [siyuan-note/siyuan#6831]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

更清晰的笔记结构

### 描述可能的最优解决方案 Describe the optimal solution

不知道是不是我没有找到这个功能， 但我觉得这个功能比较有用，其他类似笔记软件也有这个功能，当按下“Tab”时， heading 也可以缩进变为上一个父级的子级，而且其heading下级的paragraph(包括list)都会自动随着缩进而自动进行缩进
# Topic
    Heading 1
        Heading2
            heading3
                list 1
                list 2

**Comment by 88250** [comment]
这个只能通过列表块实现，谢谢。
