### ISSUE TITLE
导入空内容 Markdown 文件时报错

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6832]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

导入文件夹的时候会卡住，停住，试了很多次都这样。不知是不是因为中文文件名的原因？

### 期待的结果 Expected result

顺利导入

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/38936048/206650266-ef09f081-af5d-47e8-be01-66e8545f39bb.png)

### 版本环境 Version environment

```markdown
- Version: 最新版
- Operating System:  win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10192747/siyuan.log)
日志里好像看不出什么问题

**Comment by 88250** [comment]
一次性导入了多少 Markdown 文件？如果较多的话得多等一下。

**Comment by oijqws** [comment]
并不多。更多都成功了。导入过程中，文件名应该会不停的换的，但是卡住的时候30分钟都不换

**Comment by oijqws** [comment]
我从evernote导出4000多条没问题。youdao笔记大约1000条。而且我新建了用户专门测试这个问题，相当导入空的笔记本，也会卡住

**Comment by 88250** [comment]
或者帮忙用二分法定位一下出问题的文件，谢谢。

**Comment by oijqws** [comment]
明白了，如果有 0kb 的空文件就会卡住

**Comment by 88250** [comment]
0K 的 .md 文件吗？

**Comment by oijqws** [comment]
空的，或者只有换行符的都会卡住

**Comment by oijqws** [comment]
[年度调研课题分别是经济与管理学院于学江教授主持的“青岛市农村土地承包经营权流转的影响因素分析与对策建议”、孙葆春副教授主持的“青岛市消费者对地理标志农产品支付意.zip](https://github.com/siyuan-note/siyuan/files/10192982/default.zip)

**Comment by gmeer** [comment]
我也在v2.5.3版本导入Markdown文件时遇到了这个问题，参考 @oijqws 的方式删除0kb的只有文件名的md文件后，成功导入了。

**Comment by oijqws** [comment]
谢谢。我还有些文件是1kb的非空。等2.5.4发布再导入。
