### ISSUE TITLE
设置访问授权码后禁止访问

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#6834]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 使用的思源版本信息
1. docker部署
2. 版本号2.0.4
3. 使用的设备，linux系统部署，两台电脑访问
### 具体的情景
1. 在远端服务器使用docker部署好思源笔记
2. 用其中的一台电脑访问思源并设置访问授权码
![image](https://user-images.githubusercontent.com/72953189/206694570-de546bea-8011-40df-b52b-9e9ae8d734d5.png)
3. 另一台电脑出现无法访问
![image](https://user-images.githubusercontent.com/72953189/206694784-db2e0a29-cad2-45d6-8270-f80a7406cc2b.png)
如果关闭之后再启动，不会弹出填入授权码的窗口，一直保持下面的样子
![image](https://user-images.githubusercontent.com/72953189/206694871-b53f61b4-17b9-4ce2-b7f3-1d912bf4fe31.png)

### 期待的结果 Expected result

授权码问题解决

### 版本环境 Version environment

```markdown
- Version: 2.0.4
- Operating System: windows docker部署
- Browser (if used):edge google
```

### 日志文件 Log file

无这段时间的记录

**Comment by 88250** [comment]
请升级到最新版后再试试，可能已经修复，如果没有修复，请回帖，谢谢。

**Comment by 88250** [comment]
对了，另外一台电脑上需要刷新界面。

**Comment by tangjiahao2001** [comment]
> 对了，另外一台电脑上需要刷新界面。

刷新之后就出现第二个页面中的，只显示在思源图标，没有输入窗口，像是授权码设置了，但是没有上传给服务器端

**Comment by tangjiahao2001** [comment]
> 

因为只有设置了的那台电脑可以继续访问

**Comment by 88250** [comment]
升级到最新版看看。

**Comment by 88250** [comment]
迁移数据应该没问题，最近我们没有收到相关问题反馈。

为了稳妥起见，建议备份一下数据再迁移。

**Comment by tangjiahao2001** [comment]
好的 @88250
