### ISSUE TITLE
最顶上还有很多空，不知道是否可以把“钉住”放在这里可以迅速访问常用文档

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6836]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/38936048/206718314-e9e7ed15-25e9-4684-8678-7904bda574fb.png)

### 描述可能的最优解决方案 Describe the optimal solution

最顶上还有很多空，不知道是否可以把“钉住”放在这里可以迅速访问常用文档

**Comment by 88250** [comment]
访问最近打开的文档请关注 https://github.com/siyuan-note/siyuan/issues/3293

另外，可以考虑使用书签功能。
