### ISSUE TITLE
通过网页共享单篇笔记

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6839]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

通过S3 通过微信共享单篇笔记

### 描述可能的最优解决方案 Describe the optimal solution

既然支持S3 网络存储，是否可以有个功能可以一键发布这篇笔记，就是导出一个网页，上传到S3 空间，然后再生成一个链接。这样就可以把这篇笔记链接发给微信好友看了。

**Comment by 88250** [comment]
现阶段暂时不考虑了，如果社区开发者看到可以帮忙试试，谢谢。
