### ISSUE TITLE
希望增加新功能——增加看板视图、流程图、思维导图等功能

### ISSUE THREAD

**Issue by PayneSnow** [siyuan-note/siyuan#684]
希望借鉴 roam edit/logseq等编辑器，增加看板视图、流程图、思维导图等功能。

**Comment by scvoet** [comment]
流程图已得到支持，可通过 mermaid 和 flowchart 两个 markdown 扩展语法来使用。看板 D 大似乎在群里说过有计划来着。

**Comment by 88250** [comment]
你好，后期我们会引入“视图”概念，大致就是把底层查询进行开放（比如使用 SQL），让其他开发者可以通过该能力编写视图模板，有点类似插件的意思。目前还在早期构思，还需要一段时间进行考虑，谢谢。

**Comment by PayneSnow** [comment]
感谢你们所做的努力。
插件的想法很好，思维导图、看板等功能都可以通过插件加上。
看板功能希望早点加上，结合双向链接很好用。
期待 后期空闲后，优化界面，像其他roam应用一样，为标签或文字增加配色。
希望反向链接可以直接编辑，而不是直接跳转。如图，这是我之前使用roam edit的截图。
roam的重要功能，便是将关于同一个主题或者关键词的信息，通过双向链接汇总至同一个页面。如图，对于双向链接我不仅可以预览当时的引用文字，也可以进行编辑。这样的话，在使用一段时间  每日笔记后，我便可以 直接将 汇总在[[素材]]后面的各种文字信息，直接复制或者剪切至[[素材]]页面下。当然 siyuan笔记多开几个页面貌似也能实现这个操作。但是得不断跳转，总是感觉不太方便。

思源笔记很有特色，感觉是个很有想象力和发展空间的产品。同时，期待借鉴roam的一些功能和特征，使得应用变得既好用又优雅。
谢谢

**Comment by 88250** [comment]
* 模板视图也许真的能成为一个激动人心的特性
* 标签文字的颜色设置计划在 v0.5.6 中实现，请关注提议 #620 
* 反链列表以及其他一些出现内容块标识图标的地方是支持悬浮预览修改的：

  ![image](https://user-images.githubusercontent.com/873584/101652751-929abb80-3a79-11eb-83df-94b894a439f6.png)
* 数据汇总目前可以通过“内容块动态查询”：

  ![image](https://user-images.githubusercontent.com/873584/101653023-e0172880-3a79-11eb-9a30-6b7d6b93aef0.png)

这个提议我先关闭了，如果还有什么建议，欢迎跟帖或者重新提议，谢谢！

**Comment by PayneSnow** [comment]
好的，谢谢，知道了。数据汇总目前可以通过“内容块动态查询”：——这个看到了，感觉对于普通用户不太友好。

**Comment by 88250** [comment]
嗯嗯，的确不太友好，后期我们会看看能不能做个可视化的查询器，这样方便使用，写 SQL 对于非程序员用户来说太底层原始了……

**Comment by PayneSnow** [comment]
强烈期待优化这一功能。如果像 roam researcher、roam edit、logseq那样能自动汇总最好，而不是仅仅用户自己手动查询。手动查询可以提供给一些高级汇总。我用户群聊看的少，不知道其他用户主要需求是什么。自动汇总数据是我选择roam类软件的最主要原因，每天写一个 每日笔记，通过双向链接+自动汇总，可以有效解决传统笔记的分类问题，再也不用反复讲不同的内容剪切复制至不同的文件夹了。
所以现在我虽然很看好思源笔记，已经购买了思源笔记的终身会员，但是目前依然使用比较少。目前还是在使用roam edit。手动狗头。希望越来越完善。

**Comment by PayneSnow** [comment]
另外，
期待后期借鉴 写作类应用，增加聚焦/沉浸模式（段落、行、句子），类似ulysses那样。沉浸模式能有效提升用户的输入体验。
增加一键批量导出 md 功能。现在好像是只能单个文件导出。
如果文本中涉及块引用内容的话，导出后有一些ID，而不是文本。这样的话，涉及引用的文本，只能手动复制出来。这个后期可以优化吗，将涉及引用的文本也导出来，而不是生成一堆id？

**Comment by 88250** [comment]
收到，非常感谢你的反馈和支持！

* 汇总方面我们还需要学习一下，因为看的应用太少了（闭门造车……）
* [专注模式](https://github.com/siyuan-note/siyuan/issues/306)，可能不只是抄 Typora 作业，还会参考更多专业写作类应用进行设计
* [批量导出](https://github.com/siyuan-note/siyuan/issues/577) 
* 导出的是标准 Markdown，没有块 id 的。另外，导出选项里可以调整格式
  
  ![image](https://user-images.githubusercontent.com/873584/101716001-788fc600-3ad7-11eb-8055-a9d51b4eeb1b.png)

**Comment by PayneSnow** [comment]
专注模式：
typora并不是做的最好的。专注模式的鼻祖应该是IA Writer，设计很简洁优雅。
目前我感觉做的最好的是 Ulysses。期待参考。你们使用的Texrbundle等样式，好像就是ulysses和bear等软件组成的联盟所推广的格式。
另外，最近有一种 流模式，不知道您是否了解？流模式相当于完全的沉浸模式，只显示当前的输入内容，其他的内容完全看不见。可以参考 writeathon <https://www.writeathon.cn/>：https://www.writeathon.cn/ <https://www.writeathon.cn/>
数据汇总
roam edit：应该是目前国内开发最成熟，最接近roam researcher的应用了，缺点是那个应用有时候会丢失数据，不知道哪儿有问题。roam edit的功能很多，社区也很活跃，上面的很多功能都能抓住用户的痛点。
logseq：也是国人开发的，但是好像国外用户比较多。做的也不错。
