### ISSUE TITLE
打开图片之后可以选择用一个程序编辑图片

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#6840]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

打开图片之后可以选择用一个程序编辑图片

### 描述可能的最优解决方案 Describe the optimal solution

例如用ps打开，这样可以实现加红线标注图片之类的功能

**Comment by 88250** [comment]
桌面端右键可以打开文件位置。
