### ISSUE TITLE
屏蔽列表项拖拽到列表项第一个块上方和列表前一个块的下方

### ISSUE THREAD

**Issue by aptexd** [siyuan-note/siyuan#6843]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/15101966/206853294-0e3a3230-a98d-42b9-931c-54d7bae5ce02.png)
以上是演示场景
此时用鼠标将节点 2 拖到 A 下 也就是 1 前
![image](https://user-images.githubusercontent.com/15101966/206853400-fb89cc37-6d67-4c06-a504-1067ec6cc41c.png)
此时 节点 2 和 节点 1 是两个独立列表
不是整体的列表项

### 期待的结果 Expected result

移动后的列表项 2 和 1 应该是一个列表，而不是两个

### 版本环境 Version environment

```markdown
- Version: 2.5.3
- Operating System: Win 10
- Browser (if used):
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
拖动列表项，不要拖列表。

**Comment by aptexd** [comment]
![image](https://user-images.githubusercontent.com/15101966/206861613-979c66a2-cece-4c86-b203-9556d1de6812.png)

刚才切换到默认主题
当只有一个节点的时候
没有单个列表项的图标，只有三条杠的列表图标
就算拖动单个节点的的圆点，依然无法合并

![image](https://user-images.githubusercontent.com/15101966/206861776-bdceb59b-3443-4b56-9750-894c9e18565a.png)
此时当 A 有了 1 和 3 ，1 和 3 确定为一个列表
拖动 1 的列表项到 B 下，也就是 2 上的时候 
1 和 2 依然是两个独立的列表，如下图
![image](https://user-images.githubusercontent.com/15101966/206861883-4887c4c4-e35f-45f6-89ff-812b5174d47c.png)

**Comment by 88250** [comment]
拖动圆点。

**Comment by aptexd** [comment]
我在默认主题试过了，的确不可以

![image](https://user-images.githubusercontent.com/15101966/206864073-65d5c059-f5e3-421a-8d89-5329082d190f.png)
比如上图当前 1、3 是一个列表
这时把 1 拖动圆点 到 B 下方
1 和 2 依旧式两个列表，如下两图
![image](https://user-images.githubusercontent.com/15101966/206864147-9f164ae3-b710-4991-85c9-3372e41b5690.png)
![image](https://user-images.githubusercontent.com/15101966/206864190-ae349666-9de8-476b-827c-887fc540ecf6.png)

**Comment by 88250** [comment]
> 这时把 1 拖动圆点 到 B 下方

这个和拖到 1 上方是两个不同的插入点，你用后者试试。

**Comment by aptexd** [comment]
![image](https://user-images.githubusercontent.com/15101966/206864451-b3d2a4c3-b94c-46e0-a34d-522abca5541b.png)
上图是本次原始状态
此时我将 1 拖到 2 的上方（的确不是B的下方）
多次尝试均出现以下情况
![image](https://user-images.githubusercontent.com/15101966/206864522-ced71445-1a50-48c5-960f-70a441e0f51f.png)
不知道是不是跟你说的操作是一样的

**Comment by 88250** [comment]
你这个是拖到了 2 这个段落的上方，不是 2 这个列表项的上方哦。

**Comment by aptexd** [comment]
的确成功了
转念一想，这个地方还出现段落的上方，会不会不太合理
我认为，拖动列表的时候，应该屏蔽 列表2 的段落展示，以免造成误操作

**Comment by 88250** [comment]
之前考虑过，但是逻辑上允许空列表项（即 `* * foo`）存在，如果禁止的话感觉不太自洽。

**Comment by aptexd** [comment]
坦白的讲
为了找这个 2 的列表项的上方，而不是 2 的段落的上方
真的耗费了好多精力
操作也难以精确
操作也不够丝滑
十分容易操作错误

**Comment by aptexd** [comment]
> 之前考虑过，但是逻辑上允许空列表项（即 `* * foo`）存在，如果禁止的话感觉不太自洽。

这句没太理解
写完后想的可能说的时`* * 1`的情况吧，这个的确没有问题

但我想的是如果对于列表项进行拖动的时候
一律屏蔽**段落**方位的提示，这样会不会好些
而只有在**段落和段落**的移动时才予以展示
任何**列表**和**段落**的混排理论上都是不可以的

也就是只有单个列表项的“上中下”三个位置，这样怎么拖动起来就会容易很多
这样做会有问题吗
