### ISSUE TITLE
增加文档朗读功能

### ISSUE THREAD

**Issue by flytassel** [siyuan-note/siyuan#6845]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在背诵笔记时，听电脑语音的朗读是一个不错的方式，但目前思源没有相关的功能，希望能增加类似功能！

### 描述可能的最优解决方案 Describe the optimal solution

在word、Adobe Acrobat Pro中都有朗读的相关功能，且有选择语音的功能
![image](https://user-images.githubusercontent.com/60308594/206862766-95b8161b-0298-409a-9b45-4bfd01c7b68f.png)

**Comment by 88250** [comment]
目前在导出预览模式下划选后有个朗读功能基本可以凑合用一下，或者导出 Word 吧，感谢提议。
