### ISSUE TITLE
增加批量展开、折叠的快捷键

### ISSUE THREAD

**Issue by flytassel** [siyuan-note/siyuan#6846]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/60308594/206862887-8eccf6e7-e971-48e4-8ddc-fe9aa0387de4.png)
在制作笔记时，我比较喜欢使用列表的方式，包括数字列表和无序列表，阅读不同部分常需要展开和折叠，手动一个个去点十分麻烦，一级下面嵌一级，目前已有的alt+click的方式只能同级展开，无法实现上述功能，希望开发者能增加上述功能，十分感谢！

### 描述可能的最优解决方案 Describe the optimal solution

在幕布中，已经实现类似特性

**Comment by 88250** [comment]
思源不是大纲式笔记，折叠和展开需要考虑其他元素，所以这个需求暂时不考虑了，感谢提议。
