### ISSUE TITLE
文件树排序忽略 Emoji

### ISSUE THREAD

**Issue by MistRay** [siyuan-note/siyuan#685]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

1. 创建文件/文件夹并要在开头添加emoji时,要先在文档中把emoji打出来,然后复制.(有些麻烦)
2. 将emoji放在开头后,与文件名相关的排序会失效(其实是根据emoji排序了)
![image](https://user-images.githubusercontent.com/34370155/101615210-d6c19800-3a48-11eb-9a8d-8e1c9ab07930.png)

### 描述最优的解决方案 Describe the optimal solution
希望类似于notion,将emoji独立出来,特殊处理
![image](https://user-images.githubusercontent.com/34370155/101619291-0a52f100-3a4e-11eb-8c8b-107f0897c1eb.png)

### 描述候选解决方案 Describe the candidate solution
1. 在创建文件/文件夹时,可以选择emoji,或者使用`:`添加emoji.
2. 与文件名相关的排序,忽略emoji(应该没人想根据emoji排序吧)

### 其他信息 Other information
# 并非刚需

**Comment by 88250** [comment]
感谢提议，我们先将排序时 emoji 排除掉。输入的话因为一些输入法已经自带了，所以暂时先不提供，谢谢。

**Comment by 88250** [comment]
新建文档名通过 `:` 触发 Emoji 自动完成请关注 https://github.com/siyuan-note/siyuan/issues/688
