### ISSUE TITLE
代码片段在linux下无法运行

### ISSUE THREAD

**Issue by allblue** [siyuan-note/siyuan#6850]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

按社区[设置题头图方案](https://ld246.com/article/1669736129802 )配置思源后，windows可正常执行代码片段，可在题头图上显示自定义按钮。但linux下无效，新增按钮不显示。

### 期待的结果 Expected result

linux下也可正常执行代码片段，达到和windows客户端相同效果

### 截屏或者录屏演示 Screenshot or screen recording presentation

设置代码片段后
![image](https://user-images.githubusercontent.com/844763/206894292-e13bc707-4383-46a5-b477-1f4edc78e80c.png)

题头图按钮无变化
![image](https://user-images.githubusercontent.com/844763/206894418-4eb351f1-a2f6-45e9-b0b7-88d2ac7c9d66.png)

### 版本环境 Version environment

```markdown
- Version: 2.5.3 appimage
- Operating System: archlinux
- Browser (if used): vivaldi 5.6.2867.40 (Stable channel) stable (64-bit)
```

### 日志文件 Log file

I 2022/12/11 12:20:17 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/12/11 12:20:17 runtime.go:44: kernel is booting:
    * ver [2.5.3]
    * arch [amd64]
    * pid [2987]
    * runtime mode [prod]
    * working directory [/tmp/.mount_siyuanrJUslS/resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/home/archblux/Documents/SiYuan]
I 2022/12/11 12:20:17 runtime.go:89: use network proxy [system]
I 2022/12/11 12:20:17 port.go:65: check running kernel elapsed [0ms]
I 2022/12/11 12:20:17 serve.go:108: listen port elapsed [0ms]
I 2022/12/11 12:20:17 serve.go:115: kernel [pid=2987] is booting [http://127.0.0.1:6806]
I 2022/12/11 12:20:17 sync.go:81: sync before boot
I 2022/12/11 12:20:17 working.go:363: built-in pandoc [ver=2.19.2, bin=/home/archblux/Documents/SiYuan/temp/pandoc/bin/pandoc]
I 2022/12/11 12:20:23 repository.go:527: boot get sync cloud files elapsed [5.93s]
I 2022/12/11 12:20:23 conf.go:617: database size [88 MB], tree/block count [871/25382]
I 2022/12/11 12:20:23 working.go:149: kernel booted
I 2022/12/11 12:20:32 repository.go:627: synced data repo [provider=0, ufc=11, dfc=0, ucc=11, dcc=11, ub=127 kB, db=1.0 MB] in [2.03s]
I 2022/12/11 12:20:32 repository.go:722: sync merge result [conflicts=0, upserts=10, removes=4]
I 2022/12/11 12:20:32 repository.go:743: sync merge upserts:
  /20221121163436-ugy27un/20221121163454-wkb8fjk/20221210141926-qprvbh2/20221121163459-954lb9m/20221210171623-krn9jk2.sy
  /20221121163436-ugy27un/20221207220910-ragjkfo/20221126143041-qidj7uc.sy
  /assets/image-20221210171625-782w1bu.png
  /20221121163436-ugy27un/20221207220910-ragjkfo/20221121163433-nilqce3.sy
  /20221121163436-ugy27un/20221121163501-8573ls2/20221121163501-1ea6zek/20221205221553-n5fhsid.sy
  /20221121163436-ugy27un/20221121163501-8573ls2/20221121163501-1ea6zek/20221121163458-p4h25h7.sy
  /20221121163436-ugy27un/20221121163454-wkb8fjk/20221121163500-dseijum.sy
  /20221121163436-ugy27un/20221121163501-8573ls2/20221121163501-1ea6zek/20221121163355-vpoaf5r.sy
  /20221121163436-ugy27un/20221121163454-wkb8fjk/20221210141926-qprvbh2/20221121163459-954lb9m.sy
  /20221121163436-ugy27un/20221121163501-8573ls2/20221121163501-1ea6zek/20221121163355-vpoaf5r/20221210172841-krbidhj.sy
I 2022/12/11 12:20:32 repository.go:754: sync merge removes:
  /20221121163436-ugy27un/20221207220910-ragjkfo/20221124112710-h9v85jp.sy
  /20221121163436-ugy27un/20221207220910-ragjkfo/20221205231144-xhs70c9.sy
  /20221121163436-ugy27un/20221207220910-ragjkfo/20221205221553-n5fhsid.sy
  /20221121163436-ugy27un/20221207220910-ragjkfo/20221206172233-h04ye1u.sy
I 2022/12/11 12:21:23 box.go:80: auto stat [trees=873, blocks=25392, dataSize=143 MB, assetsSize=106 MB]
I 2022/12/11 12:25:22 repository.go:627: synced data repo [provider=0, ufc=1, dfc=0, ucc=1, dcc=0, ub=40 kB, db=75 kB] in [3.82s]
I 2022/12/11 12:33:22 repository.go:627: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=75 kB] in [0.18s]
I 2022/12/11 12:41:22 repository.go:627: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=75 kB] in [0.15s]
I 2022/12/11 12:49:22 repository.go:627: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=75 kB] in [0.15s]
I 2022/12/11 13:05:26 repository.go:627: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=75 kB] in [3.41s]
I 2022/12/11 13:37:26 repository.go:627: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=75 kB] in [0.13s]
I 2022/12/11 14:21:23 box.go:80: auto stat [trees=873, blocks=25392, dataSize=143 MB, assetsSize=106 MB]
I 2022/12/11 14:41:27 repository.go:627: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=75 kB] in [0.14s]
I 2022/12/11 14:58:49 process.go:31: received os signal [terminated], exit kernel process now
I 2022/12/11 14:58:49 conf.go:399: exiting kernel [force=false, execInstallPkg=1]
I 2022/12/11 16:37:01 working.go:111: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/12/11 16:37:01 runtime.go:44: kernel is booting:
    * ver [2.5.3]
    * arch [amd64]
    * pid [1715]
    * runtime mode [prod]
    * working directory [/tmp/.mount_siyuanrJbL97/resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/home/archblux/Documents/SiYuan]
I 2022/12/11 16:37:01 runtime.go:89: use network proxy [system]
I 2022/12/11 16:37:01 port.go:65: check running kernel elapsed [0ms]
I 2022/12/11 16:37:01 serve.go:108: listen port elapsed [0ms]
I 2022/12/11 16:37:01 serve.go:115: kernel [pid=1715] is booting [http://127.0.0.1:6806]
I 2022/12/11 16:37:01 working.go:363: built-in pandoc [ver=2.19.2, bin=/home/archblux/Documents/SiYuan/temp/pandoc/bin/pandoc]
I 2022/12/11 16:37:01 sync.go:81: sync before boot
I 2022/12/11 16:37:02 repository.go:527: boot get sync cloud files elapsed [0.85s]
I 2022/12/11 16:37:02 conf.go:617: database size [88 MB], tree/block count [873/25392]
I 2022/12/11 16:37:02 working.go:149: kernel booted
I 2022/12/11 16:37:10 repository.go:627: synced data repo [provider=0, ufc=1, dfc=0, ucc=1, dcc=1, ub=81 kB, db=88 kB] in [1.14s]
I 2022/12/11 16:37:10 repository.go:722: sync merge result [conflicts=0, upserts=1, removes=0]
I 2022/12/11 16:37:10 repository.go:743: sync merge upserts:
  /20221121163436-ugy27un/20221121163448-vfztcz4/20221121163448-kzkst79/20221201032557-wl07qvl/20221211163140-mscuixi.sy
I 2022/12/11 16:37:15 repository.go:627: synced data repo [provider=0, ufc=1, dfc=0, ucc=1, dcc=0, ub=41 kB, db=75 kB] in [0.59s]
I 2022/12/11 16:38:02 box.go:80: auto stat [trees=874, blocks=25432, dataSize=143 MB, assetsSize=106 MB]
I 2022/12/11 16:38:03 repository.go:627: synced data repo [provider=0, ufc=2, dfc=0, ucc=2, dcc=0, ub=43 kB, db=75 kB] in [0.71s]
I 2022/12/11 16:46:04 repository.go:627: synced data repo [provider=0, ufc=1, dfc=0, ucc=1, dcc=0, ub=41 kB, db=75 kB] in [0.92s]

**Comment by 88250** [comment]
你好，代码片段机制理论上应该是跨平台的，请测试其他一些简单的片段是否有效。

如果有效的话，请给代码片段原作者反馈一下，谢谢。
