### ISSUE TITLE
请输入问题报告标题 Please enter the title of the bug report

### ISSUE THREAD

**Issue by teivosic** [siyuan-note/siyuan#6852]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

创建chart失败

### 期待的结果 Expected result

成功创建表格

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/8881472/206902229-e825da92-bdb9-422e-91ef-1a0d83f359b8.png)

### 版本环境 Version environment

```markdown
- Version: 2.5.3
- Operating System: windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10202090/siyuan.log)

**Comment by 88250** [comment]
这个需要使用 JSON 格式，请看用户指南中的示例。
