### ISSUE TITLE
改进命名查询持久化

### ISSUE THREAD

**Issue by mdzz2048** [siyuan-note/siyuan#6856]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

之前提过[搜索排除指定笔记本](https://ld246.com/article/1647435614636)的需求，社区和 Issues 里也有类似的需求：[全局搜索能否屏蔽某个笔记本进行搜索？](https://ld246.com/article/1653885592762)、#6475

目前通过2.5.3引入的 #6589 可以将指定路径保存为“命名查询”或使用 SQL 语句查询实现排除部分笔记本，但是在每次使用 Ctrl + P 搜索时，上次使用的 SQL 搜索和指定路径都会变回默认值。

以排除指定笔记本的需求考虑的话，希望能保留上次使用的命名查询。

### 描述可能的最优解决方案 Describe the optimal solution

提供设置默认命名查询选项

### 描述候选的解决方案 Describe the candidate solution

搜索界面默认使用上次的命名查询

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/6828 中改进，谢谢。

**Comment by 88250** [comment]
看来得改进一下命名查询持久化默认。
