### ISSUE TITLE
docker 默认用户 与 控制转移

### ISSUE THREAD

**Issue by undefine-man** [siyuan-note/siyuan#6857]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

使用群晖储存数据的用户大都是比较在乎数据的管理的，我相信这和思源笔记的用户群是高度重合的，都对数据管理是较高的期望的。
同样我也是群晖NAS的用户。

群晖的docker使用的是图形界面创建新的容器，可设置自定义的参数。在常规docker通过命令行启动容器可以设置很多参数，而**群晖docker这里只能设置非常有限的参数**。

在使用群晖官方的docker套件部署思源笔记docker版的时候发现两个问题。

问题1）权限问题：
在将容器目录映射到宿主机的时候出现权限问题，且因为群晖可设置参数有限而无法在启动docker前通过传参以root用户启动docker。所以通过chmod修改文件夹权限的时候也因为无权限而受阻。[日志图1]

问题2）workspace 控制转移：
在群晖docker里通过启动参数修改思源工作目录似乎并不生效，在日志里有设置目录的stdout，但是在思源启动后还是使用了原默认的工作目录。[日志图2]

### 期待的结果 Expected result

问题1）：
思源的docker镜像默认用户由普通用户siyuan改为超级用户root。
问题2）：
将workspace的设置方式由容器启动前传参的方式改为和桌面端相同的，在笔记的设置内部进行设置。

相信这两点小的改进（为docker用户开放更高的控制权 及 减少对docker启动参数的依赖），能降低通过群晖官方docker套件进行部署用户的门槛，使得更多群晖用户方便的开始使用思源笔记进行知识管理。

### 截屏或者录屏演示 Screenshot or screen recording presentation

[日志图1]
![屏幕截图 2022-12-12 155900](https://user-images.githubusercontent.com/24623544/206991987-31c0f814-0996-4e56-9447-9e0774dbb25f.png)
[日志图2]
![屏幕截图 2022-12-12 161204](https://user-images.githubusercontent.com/24623544/206994720-afe83d6a-7b5d-4fab-b711-bcf0da9fd56f.png)

其他
![屏幕截图_20221212_161508](https://user-images.githubusercontent.com/24623544/206995577-6248d232-15c7-4863-b796-b89b8d57bb77.png)

### 版本环境 Version environment

```markdown
- Version: s
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无法获得

### 更多信息 More information

可能通过文字描述并不太直观，或者您没有群晖设备。
所以我在网上找了一个可公共访问的开放的群晖NAS。

链接：
http://szhaotian.top:5000/
账号：
admin
密码：
szhaotian

开启了VPN可能显示白屏，建议关闭VPN.

操作方法大纲：
登录 -> docker -> [注册表] -> 键入搜索镜像，并等待进行下载完毕 -> [镜像] -> 选择对应的镜像点击启动 -> ...

**Comment by undefine-man** [comment]
操作了不少次，发现切换工作目录需要在第一次就指定好新目录，然后第一次启动容器会提示指定目录不存在然后自动使用原工作目录，这时候通过群晖容器 [终端机] -> [通过命令启动] 然后 mkdir xxx 目录再重启容器就可以比较别扭地切换目录。但是映射工作目录还是会出钱权限不足，导致容器终止。

**Comment by 88250** [comment]
出于安全角度考虑，官方镜像不调整权限了，如果需要请自行构建镜像，谢谢。
