### ISSUE TITLE
支持数据快照对比

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6858]
* https://ld246.com/article/1670834792762
* https://ld246.com/article/1670766454703

通过对比 A、B 两个数据快照得出新增、删除和修改的文件列表。

**Comment by Zuoqiu-Yingyi** [comment]
数据快照对比中 `更新` 的文档是否应该将右侧设置为较新的文档, 或者标示一下快照的时间/名称?

**Comment by Zuoqiu-Yingyi** [comment]
数据快照对比中可以添加一个 鼠标右键单击取消所有数据快照项的选中状态 的功能, 使选择更加方便

**Comment by 88250** [comment]
再次点击就是取消选中。
