### ISSUE TITLE
新建表格时移除表头 col1 col2 col3

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#6864]

**Comment by 88250** [comment]
似乎没有太大必要，没有表头的话太窄了：

![image](https://user-images.githubusercontent.com/873584/209418913-a5d0e131-13a1-4df0-aded-d4fad454e055.png)

如果实在需要，可以用模板先做好表格再调用模板。

**Comment by Vanessa219** [comment]
还是修改了一下

**Comment by lunzilunzi** [comment]
去掉了也有问题，默认没有了动态宽度

**Comment by Vanessa219** [comment]
> 去掉了也有问题，默认没有了动态宽度

收到，我再改改，下个版本再看看。
