### ISSUE TITLE
长篇文档鼠标拖动右侧滚动条Bug

### ISSUE THREAD

**Issue by dhbxs** [siyuan-note/siyuan#6865]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

在长篇文档中，想要快速的从文档底部滚动到文档顶部，用鼠标拖动右侧滚动条到顶部会自动在中途回到初始的底部位置

### 期待的结果 Expected result

平滑滚动，不卡Bug，不会自动断掉滚动回到底部

### 截屏或者录屏演示 Screenshot or screen recording presentation

[Bug录屏地址](https://onedrive.dhbxs.top/api/raw/?path=/%E6%88%91%E5%9C%A8%E5%B7%A5%E4%BD%9C%E4%B8%AD%E6%98%AF%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%20git%20%E7%9A%84%20-%20%E6%80%9D%E6%BA%90%E7%AC%94%E8%AE%B0%20v2.5.4%202022-12-13%2015-31-47.mp4)

### 版本环境 Version environment

```markdown
- Version: 2.5.4
- Operating System: Windows 10 
- Browser (if used): None
```

### 日志文件 Log file

[Bug日志地址 https://onedrive.dhbxs.top/zh-CN/Siyuan-Note-BugReport/](https://onedrive.dhbxs.top/zh-CN/Siyuan-Note-BugReport/)

**Comment by 88250** [comment]
跳转到顶部/底部可以直接点击块滚动条顶部/底部的箭头。

另外，我这里无法查看录屏演示，如果有需要进一步反馈麻烦重新上传一下。我先关闭了，谢谢。

**Comment by dhbxs** [comment]
D大，录屏文件我重新上传了，https://onedrive.dhbxs.top/api/raw/?path=/Siyuan-Note-BugReport/%E6%88%91%E5%9C%A8%E5%B7%A5%E4%BD%9C%E4%B8%AD%E6%98%AF%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%20git%20%E7%9A%84%20-%20%E6%80%9D%E6%BA%90%E7%AC%94%E8%AE%B0%20v2.5.4%202022-12-13%2015-31-47.mp4

点击连接可直接下载查看，
这是云盘连接 Dhbxs's Drive<https://onedrive.dhbxs.top/zh-CN/Siyuan-Note-BugReport/>
，里面还有日志log，主要是在拖动滚动条的过程中，滚动条乱跳，还望D大能下载看下此Bug，如有需要随时联系。

以上，
谢谢！
2022年12月14日
发件人: ***@***.***>
发送时间: 2022年12月14日 12:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/siyuan] 长篇文档鼠标拖动右侧滚动条Bug (Issue #6865)


跳转到顶部/底部可以直接点击块滚动条顶部/底部的箭头。

另外，我这里无法查看录屏演示，如果有需要进一步反馈麻烦重新上传一下。我先关闭了，谢谢。

―

**Comment by 88250** [comment]
这个应该是正常现象，滚动是动态加载的，只有加载出来以后才能计算总体滚动高度。

**Comment by dhbxs** [comment]
那拖动右侧的块滚动条却不会，有没有办法能先加载第一个块和最后一个块，通过这两个块来计算总体的滚动高度，然后运用到最右侧的滚动条。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月14日 13:09
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/siyuan] 长篇文档鼠标拖动右侧滚动条Bug (Issue #6865)


这个应该是正常现象，滚动是动态加载的，只有加载出来以后才能计算总体滚动高度。

―

**Comment by 88250** [comment]
没有办法计算的，中间块的高度不一致，比如块包含了高度不一样的图片。
