### ISSUE TITLE
搜索优化建议

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#6867]
以前提的保存查询类型来搜索改进了真的很高兴，，但是还有一点想提

如题：
https://ld246.com/article/1670730489250

建议把保存的命名查询类型由原本这样：
![image](https://user-images.githubusercontent.com/30001685/207350183-55afd420-214d-43ab-8df6-193fa07abbd3.png)

变化成这样，把每个保存好的命名查询类型直接放搜索框这里，大概就在序号的位置，这样切换类型搜索的时候点一下这个序号就可以切换，这更加更加快捷：
![image](https://user-images.githubusercontent.com/30001685/207350802-705cf6ab-70d4-4155-abb9-1d58e6a54776.png)

当然我不是开发者不知道这个实现的难度和可行性，望回复

**Comment by 88250** [comment]
暂时不考虑，感谢提议。
