### ISSUE TITLE
导出 Markdown zip 包内不带文件夹

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#6869]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前导出PDF和Word的优化已经很满意了
但是导出Markdown，依然会带有文档所在路径的所有文件夹，一层套一层，希望导出Markdown只有该文档的文件夹，除去路径文件夹
![image](https://user-images.githubusercontent.com/60436214/207497877-7b8b110e-2c11-4d04-8132-3d6918b1967a.png)

### 描述可能的最优解决方案 Describe the optimal solution

导出Markdown只有该文档的文件夹，除去路径文件夹

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by Achuan-2** [comment]
貌似还是会导出路径文件夹
![image](https://user-images.githubusercontent.com/60436214/209164699-90c1de40-97d1-4645-a385-585d266e45d8.png)

**Comment by 88250** [comment]
父路径的文件夹会带的，去掉的是自己这一层。
