### ISSUE TITLE
切出思源后返回，代码块光标自动上移至代码块起始位置

### ISSUE THREAD

**Issue by BLACKT-T** [siyuan-note/siyuan#687]
我是用```编辑代码块，然后在内部手动敲入代码，然后Alt+Tab切换软件窗口，查看其他信息，再切回思源，此时代码块中光标自动移动到了代码块中的开始位置。请问有没有什么办法固定光标在代码块中的固定位置，哪怕切出思源再返回还是原来位置？
![image](https://user-images.githubusercontent.com/37499441/101633485-4728e300-3a62-11eb-9013-e333589be536.png)

再就是代码块中代码过长会有滚动条，请问能完整显示代码吗，代码块不会固定高度直接显示完整的代码。
![image](https://user-images.githubusercontent.com/37499441/101633393-1f397f80-3a62-11eb-82e2-02d580ad8e4c.png)

**Comment by 88250** [comment]
编辑代码请用 IDE，然后复制粘贴到思源里，短期内实现不了光标位置保留，见谅。滚动条应该可以通过覆盖主题样式定制，可以试一下，我关闭了，谢谢。

**Comment by BLACKT-T** [comment]
OK！客气啦。加油。
