### ISSUE TITLE
建议在"提及"窗口下方增加一个"最近打开文档"窗口

### ISSUE THREAD

**Issue by allblue** [siyuan-note/siyuan#6874]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

1. 跨文档编辑切换时，目前只能通过文档树或标签页切换，前者可能要展开多个节点，后者只针对已打开文档，均有点不够灵活。
2. 查询窗口能显示最近打开文档，但需要二次操作

### 描述可能的最优解决方案 Describe the optimal solution

1. 建议在“提及”窗口下方增加一个“最近打开文档”窗口，实现最近文档的快速切换

![image](https://user-images.githubusercontent.com/844763/208011580-a6d364c9-a616-47cf-bf2d-a8daa9c9b53a.png)

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by Temacc0531** [comment]
边栏已经塞了多东西了

**Comment by allblue** [comment]
> 边栏已经塞了多东西了

但不是每个都会用过，像我一般就开个提及

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。
