### ISSUE TITLE
丰富`siyuan://`协议动作，如创建文档

### ISSUE THREAD

**Issue by AloneFire** [siyuan-note/siyuan#6875]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

是否能像[熊掌记](https://bear.app/cn/faq/X-callback-url%20Scheme%20Documentation/#x-callback-url-scheme)、[OBsidian](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI)一样能够通过`X-callback-url`来实现如：创建文档、创建内容块、打开文档、打开新文档、内容搜索等功能，以更好的与周边笔记生态连接。

### 描述可能的最优解决方案 Describe the optimal solution

举例：
创建文档
`siyuan://create?title=[title]&text=[content_markdown]&tags=[tag1|tag2]&path=[hpath]`

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。
