### ISSUE TITLE
Add Flatpak/Flathub as a distribution channel for Linux

### ISSUE THREAD

**Issue by bevsxyz** [siyuan-note/siyuan#6877]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Currently, the available means to use Siyuan on Linux is with AppImage or from a tar file. As good as having options for Linux already, I think we could do one better by using a distribution channel supported by a popular package manager.

### 描述可能的最优解决方案 Describe the optimal solution

[Flatpak](https://flatpak.org/) is one of the best distro independent package management system for Graphical apps on Linux. [Flathub](https://flathub.org/home) is the official central repository where developers could submit their apps.

Siyuan already fulfills the technical requirement of a unique application ID. I think we are pretty safe on the legal requirements of license. However, it would be a good idea to check the [requirements](https://github.com/flathub/flathub/wiki/App-Requirements).

The app submission is straightforward and the instructions for it can be found [here](https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app). I think it would be better if one of the developers took up control of this distribution.

We could check out the Flathub manifest for the [Bitwarden client](https://github.com/flathub/com.bitwarden.desktop) for a reference.

**Comment by 88250** [comment]
Hi, we don't have time to deal with maintaining this at the moment, please help us distribute SiYuan on Flathub if it's convenient for you, thanks.

**Comment by RasheedAZ** [comment]
Thanks. Will be good it Flathub link is added to the Readme file app market section:
https://github.com/siyuan-note/siyuan#app-market
