### ISSUE TITLE
iPhone X，这个版本和上个版本都是搜索有问题

### ISSUE THREAD

**Issue by dogeow** [siyuan-note/siyuan#6878]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

上个版本是100%，搜索光标在搜索栏下面。
这个版本是搜索几次后，也一样在下面了。

### 期待的结果 Expected result

光标正常定位

### 版本环境 Version environment

```markdown
- Version: 2.5.3 2.5.4
- Operating System: iPhone X
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
没太明白什么叫下面，我的是这样的。
![image](https://user-images.githubusercontent.com/970828/208221839-cf656b5c-4fcf-4c16-9bdb-84ee188205ad.png)

**Comment by dogeow** [comment]
上次懒，没截图，现在测试了两遍，没复现，麻烦了。

**Comment by Vanessa219** [comment]
没关系，可以复现的话我们再进行修改。
