### ISSUE TITLE
建议增加双击关闭标签页的功能

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#6879]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前版本思源只能够通过鼠标中键关闭标签页。edge浏览器的最新版（105或更新）不仅仅可以通过鼠标中键关闭标签页，还可以在设置中开启双击关闭标签页的功能。如果思源也支持双击关闭标签页，那体验将和浏览器保持一致。另外，纯markdown应用vnote也支持双击关闭标签页。

### 描述可能的最优解决方案 Describe the optimal solution

。

**Comment by UFDXD** [comment]
双击标签页在思源中有功能了

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。
