### ISSUE TITLE
导出 Markdown 文件时开头附上一些元数据

### ISSUE THREAD

**Issue by zxkmm** [siyuan-note/siyuan#6880]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当我导出整个笔记本做备份时，我发现似乎无法判断这个笔记的创建和编辑时间，所以希望导出时每个单独的markdown文件有时间戳

### 描述可能的最优解决方案 Describe the optimal solution

joplin在导出时会在文件前方附上如下内容
```
title: 1
updated: 2022-01-13 06:44:53Z
created: 2022-01-13 06:41:03Z
latitude: **.91931586
longitude: 1**.48723170
altitude: 1***.2412
```

### 描述候选的解决方案 Describe the candidate solution

1. 导出笔记时在markdown文件开头附上时间戳
2. 导出时顺便导出一个info文件记录所有文件的时间
3. 把文件系统的元数据时间修改为这个笔记的时间，而不是导出的时间

**Comment by 88250** [comment]
以 YAML front matter 格式添加：

```markdown
---
title: foo
created: 2006-01-02T15:04:05Z07:00 
updated: 2006-01-02T15:04:05Z07:00
---
```

**Comment by FrostMiKu** [comment]
Hi，D大 @88250  ，我有一个想法
created 和 updated 是否可以设计为 hexo 或 hugo 兼容的格式？
```
date: "2020-02-21T23:00:00+08:00"
lastmod: "2021-06-28T21:22:00+08:00"
```
毕竟仅仅修改一下keyword就能为思源添加建站的能力，何乐而不为呢？

**Comment by Zuoqiu-Yingyi** [comment]
@88250 导出 Markdown 时在文档头添加 metadata 能否使用一个开关控制, 我有一些文档块自定义属性需要一块导出, 所以打算搞一个挂件专门对 metadata 进行管理, 此时需要关闭内置的 metadata 导出功能
