### ISSUE TITLE
kramdown 行内`字体`元素 IAL 丢失标志符

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6885]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

数据库中 `markdown` 字段与 API `getBlockKramdown` 及 `exportMdContent` 返回的包含 IAL 的行内元素(例如设置了颜色与背景颜色样式的行内元素)均丢失标志符

示例: ![image](https://user-images.githubusercontent.com/49649786/208247539-14c4f30b-75ee-4035-b2be-698a10316e85.png)

数据库 `markdown` 字段:
```markdown
123 456{: style="color: var(--b3-font-color1);"} 789
```

API `getBlockKramdown` 响应内容:
```markdown
123 456{: style="color: var(--b3-font-color1);"} 789
{: id="20221217223809-zr5e069" updated="20221217223818"}
```

API `exportMdContent` 响应内容:
```markdown
123 456 789
```

可以看到, 该行内元素的前后标志符`**`均丢失

### 期待的结果 Expected result

数据库 `markdown` 字段:
```markdown
123 **456**{: style="color: var(--b3-font-color1);"} 789
```

API `getBlockKramdown` 响应内容:
```markdown
123 **456**{: style="color: var(--b3-font-color1);"} 789
{: id="20221217223809-zr5e069" updated="20221217223818"}
```

API `exportMdContent` 响应内容:
```markdown
123 **456** 789
```

### 版本环境 Version environment

```markdown
- Version: 2.5.4
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

### 更多信息 More information

`*.sy` 中原`字体`元素为
```json
{
	"Type": "NodeTextMark",
	"Properties": {
		"style": "color: var(--b3-font-color1);"
	},
	"TextMarkType": "strong",
	"TextMarkTextContent": "456"
}
```

现(`v2.5.4`)`字体`元素为
```json
{
	"Type": "NodeTextMark",
	"Properties": {
		"style": "color: var(--b3-font-color1);"
	},
	"TextMarkType": "text",
	"TextMarkTextContent": "456"
}
```
可能是该原因造成的

**Comment by 88250** [comment]
仅标记颜色的话 TextMarkType 为 text，不再需要加粗。所以导出 md 以后不会导出为 `**foo**`，对于 kramdown 也是一样，不需要标记符。

**Comment by Zuoqiu-Yingyi** [comment]
@88250 如果没有标志符包围的话如何使用 API 通过 kramdown 设置呢❓

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 只设置 style 估计不行，加上 `**` 试试。
