### ISSUE TITLE
设置中的“打开浏览器”入口能不能改为localhost或者127.0.0.1

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#6886]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/33930736/208252682-615c12a3-e149-4c0f-ae1a-ff2a2fce61a3.png)
如上图，点击“打开浏览器”，打开的是`192.168.0.XXX:6806`这个路由器分配的地址。这会导致一个问题就是如果突然断网（比如路由器故障或者用户主动关闭wifi），那么浏览器里的思源就会断开连接，如下图所示，用户不得不去修改地址，改成`localhost`或者`127.0.0.1`，这样太麻烦了。
![image](https://user-images.githubusercontent.com/33930736/208252994-71a4e607-950c-4830-9111-062d0b86e871.png)

### 描述可能的最优解决方案 Describe the optimal solution

将设置中的“打开浏览器”入口的地址改为`localhost:6806`或者`127.0.0.1:6806`

**Comment by 88250** [comment]
优先使用局域网地址，否则的话其他设备打不开。

**Comment by luo-chuan** [comment]
> 优先使用局域网地址，否则的话其他设备打不开。

但是，其它设备并不能点击这个“打开浏览器”，其它设备只能手动输入地址。只有本机才能点击这个“打开浏览器”。

**Comment by 88250** [comment]
不打开网络伺服功能的话是 127，打开的话以其他 IP 优先。
