### ISSUE TITLE
浏览器思源的导出项没有pdf和html

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#6887]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如图。在浏览器中通过`127.0.0.1:6806`这种方式使用思源，导出项不全，缺少pdf和html。
![image](https://user-images.githubusercontent.com/33930736/208254924-76cf1568-83b9-469f-bd99-200762fc8fc9.png)

### 描述可能的最优解决方案 Describe the optimal solution

希望导出项增加pdf和html。

**Comment by Soltus** [comment]
依赖 electron ，因此无法在浏览器实现

**Comment by 88250** [comment]
楼上说得对，我们关闭了，感谢反馈。
