### ISSUE TITLE
PDF 页签移动后阅读位置保留

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#6890]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 期待的结果 Expected result

pdf不会自动跳到顶端

### 版本环境 Version environment

```markdown
- Version: 2.5.2
- Operating System: linux docker版本
- Browser (if used):edge
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
无法重现，还麻烦解压看一下是不是这样操作？
[QQ20221219-160509-HD.mp4.zip](https://github.com/siyuan-note/siyuan/files/10257085/QQ20221219-160509-HD.mp4.zip)

**Comment by tangjiahao2001** [comment]
> 无法重现，还麻烦解压看一下是不是这样操作？ [QQ20221219-160509-HD.mp4.zip](https://github.com/siyuan-note/siyuan/files/10257085/QQ20221219-160509-HD.mp4.zip)

稍等，我录一个视频给你

**Comment by tangjiahao2001** [comment]
[bandicam 2022-12-19 16-40-30-260.zip](https://github.com/siyuan-note/siyuan/files/10257589/bandicam.2022-12-19.16-40-30-260.zip)

**Comment by tangjiahao2001** [comment]
> [bandicam 2022-12-19 16-40-30-260.zip](https://github.com/siyuan-note/siyuan/files/10257589/bandicam.2022-12-19.16-40-30-260.zip)

版本是docker 2.5.2,使用edge浏览器
