### ISSUE TITLE
siyuan笔记复制粘贴成markdown格式的问题

### ISSUE THREAD

**Issue by zhuhaisto** [siyuan-note/siyuan#6891]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

我从obsidian复制过去 那玩意复制出来就是markdown所以一下就能粘贴进 siyuan笔记 但问题是我思源的我全选 我不能复制 不能粘贴回obsidian我估计她不是markdown 我必须导出markdown我才能再复制 
1. 这个有点儿麻烦
2. 最好能简单复制出去 或者右键复制成markdown

### 期待的结果 Expected result

1

### 版本环境 Version environment

```markdown
1
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
选择以后 Ctrl+C 然后 Ctrl+V 应该可以。
