### ISSUE TITLE
不提示授权码文件位置

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#6892]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

授权码本身就是为了安全才启动的，在授权码输入界面提示授权码位置，设置授权码不就没有意义了吗。
可以通过everything等搜索工具直接定位相关文件，授权码在配置文件中还是明文显示的。

![image](https://user-images.githubusercontent.com/5226690/208341021-e152ca30-c4bc-4c5b-a9ac-3657bcfe55dc.png)

![image](https://user-images.githubusercontent.com/5226690/208341079-92b14b02-0b92-4604-86db-8d6ef055ae8b.png)

### 期待的结果 Expected result

隐藏授权码提示

### 版本环境 Version environment

```markdown
- Version: v2.5.4
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无需日志

**Comment by 88250** [comment]
能够访问工作空间配置文件的话已经能够获取到所有数据了，如果不能访问到工作空间的话，授权码才有实际意义。

**Comment by jl0476** [comment]
> 能够访问工作空间配置文件的话已经能够获取到所有数据了，如果不能访问到工作空间的话，授权码才有实际意义。

这样其实是降低了爆破的难度，本来不清楚位置的人，寻找工作空间的成本相对较高，知道了文件，完全可以不需要知道工作空间位置，直接通过搜索定位文件。

另外，其实我是觉得，对于思源这么强调安全性的笔记，配置文件应该也加密比较稳妥。

**Comment by 88250** [comment]
这里不存在所谓的“爆破难度”的，无论是从网络上搜索还是从源码上都可以找到，所以这里直接提示位置并不会降低安全性。

获取配置文件不是攻击者的目的吧？配置文件就算提供了加密，数据文件依然是明文的。

**Comment by jl0476** [comment]
> 这里不存在所谓的“爆破难度”的，无论是从网络上搜索还是从源码上都可以找到，所以这里直接提示位置并不会降低安全性。
> 
> 获取配置文件不是攻击者的目的吧？配置文件就算提供了加密，数据文件依然是明文的。

但是配置文件中除了数据相关的内容，还有webdav、s3存储的相关配置，也都是明文的。

**Comment by 88250** [comment]
你有具体可行性建议吗？

**Comment by 88250** [comment]
这个方案提高不了破解成本吧，只有有一个人写下心得放到网络上，其他人就能知道加密方式了，并不需要查看源码。

这个问题本质上是一个密钥管理的问题，我估计目前我们没有精力去解决它。

**Comment by 88250** [comment]
@primejava 没有任何区别的，复制 data 文件夹到新的不配置授权码的工作空间就能查看。所以安全的前提是设备本身可控。
