### ISSUE TITLE
v2.5.5-dev1 siyuan-v202212191041-win启动报错

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6893]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

siyuan-v202212191041-win启动报错，已截图

### 期待的结果 Expected result

应该正常启动

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/42575324/208352579-e37a9e25-bf0a-4b56-a83e-7ead085c314f.png)

### 版本环境 Version environment

```markdown
- Version: siyuan-v202212191041-win
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2022/12/19 13:13:38 runtime.go:45: kernel is booting:
    * ver [2.5.4]
    * arch [amd64]
    * pid [6232]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Documents\SiYuan]
I 2022/12/19 13:13:38 runtime.go:90: use network proxy [system]
I 2022/12/19 13:13:38 port.go:65: check running kernel elapsed [0ms]
I 2022/12/19 13:13:38 serve.go:115: kernel [pid=6232] is booting [http://127.0.0.1:14479]
I 2022/12/19 13:13:38 serve.go:123: reverse proxy server [6806] is booting
I 2022/12/19 13:13:38 working.go:369: built-in pandoc [ver=2.19.2, bin=C:\Documents\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2022/12/19 13:13:38 sync.go:81: sync before boot
I 2022/12/19 13:13:40 repository.go:798: boot get sync cloud files elapsed [1.68s]
I 2022/12/19 13:13:40 conf.go:618: database size [344 MB], tree/block count [3723/103828]
I 2022/12/19 13:13:40 working.go:154: kernel booted
I 2022/12/19 13:14:40 box.go:81: auto stat [trees=3723, blocks=103828, dataSize=163 MB, assetsSize=101 MB]
I 2022/12/19 13:14:40 box.go:93: disk usage [total=511 GB, used=362 GB, free=149 GB]

**Comment by woniuxia** [comment]
+!
