### ISSUE TITLE
[新功能建议]为块属性-备注添加markdown的支持

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#6900]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在为了一个块标注来源,添加评论和其他想法的时候没有markdown十分的不方便
e.g.
![](https://s1.ax1x.com/2022/12/21/zOLqaQ.png)
![](https://s1.ax1x.com/2022/12/21/zOLXPs.png)
在这种情况下有markdown的支持,阅读和使用体验会好很多

### 描述可能的最优解决方案 Describe the optimal solution

加上markdown支持,并不需要像是siyuan的笔记的部分支持的这么多,也许仅仅需要加粗,高亮,链接,列表之类的支持就好

**Comment by 88250** [comment]
备注无法支持非文本元素。
