### ISSUE TITLE
思源剪藏插件问题

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#6907]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

思源插件可以完成剪藏动作，但是在思源中找不到文档。

### 期待的结果 Expected result

在相应的笔记本找到剪藏内容。

### 版本环境 Version environment

```markdown
- Version: 2.5.5
- Operating System: win10 
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10287288/siyuan.log)

**Comment by 88250** [comment]
请发一下剪藏的网址。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by dejavudwh** [comment]
> 请发一下剪藏的网址。

@88250 所有网页都是这样，可以完成剪藏动作，但是在思源里找不到。

**Comment by terwer** [comment]
@dejavudwh 下面的两个提示你有吗

![image](https://user-images.githubusercontent.com/3259282/209294322-9709cfe8-3323-4f19-901d-1992ef5ebdcb.png)
![image](https://user-images.githubusercontent.com/3259282/209294381-31ecef56-d893-4da3-802a-657920d4fa46.png)

**Comment by 88250** [comment]
> > 请发一下剪藏的网址。
> 
> @88250 所有网页都是这样，可以完成剪藏动作，但是在思源里找不到。

我这里重现不了，Chrome 浏览器版本如果有更新的话更新一下后再试试。

**Comment by dejavudwh** [comment]
> @dejavudwh 下面的两个提示你有吗？我一直在用，一般网站都没问题，刚刚测试了是好的。
> 
> ![image](https://user-images.githubusercontent.com/3259282/209294322-9709cfe8-3323-4f19-901d-1992ef5ebdcb.png) ![image](https://user-images.githubusercontent.com/3259282/209294381-31ecef56-d893-4da3-802a-657920d4fa46.png)

@tcmtom @terwer 第二个创建文章成功是没有的

**Comment by Mikeal-red** [comment]
这个问题我现在也在一直出现，create article successfully的提醒也没有，chrome是最新版的。跟装了tizi有关系吗？

**Comment by 88250** [comment]
@Mikeal-red 有可能，不要用代理后再试试。

**Comment by Mikeal-red** [comment]
> 

我关掉了，重启了，没有用，还是不行。如果剩下需要改mac端口啥的操作没人指导我就不会了

**Comment by Mikeal-red** [comment]
[system-log.zip](https://github.com/siyuan-note/siyuan/files/10299378/system-log.zip)

**Comment by dejavudwh** [comment]
> 这个问题我现在也在一直出现，create article successfully的提醒也没有，chrome是最新版的。跟装了tizi有关系吗？

记得前几个版本好像没有这个问题，具体忘记了

**Comment by Lyn6969** [comment]
edge浏览器出现了同样的问题，是最新的108.0.1462.54版本，剪藏插件时好时坏，我关闭了所有其他的插件，能够cliping但是无法cearte article ，滚动着就提示就没了。确认不是因为和其他插件冲突的问题。。。我在我低版本的chrome上试了一下还正常

**Comment by 88250** [comment]
我这里是 Chrome 108.0.5359.125 目前正常。

**Comment by Lyn6969** [comment]
> 我这里是 Chrome 108.0.5359.125 目前正常。

这个有log可以看吗，我看一下

**Comment by dejavudwh** [comment]
> edge浏览器出现了同样的问题，是最新的108.0.1462.54版本，剪藏插件时好时坏，我关闭了所有其他的插件，能够cliping但是无法cearte article ，滚动着就提示就没了。确认不是因为和其他插件冲突的问题。。。我在我低版本的chrome上试了一下还正常

我也是 108.0.1462.54，同样的问题

**Comment by 88250** [comment]
试下打开浏览器开发者工具后再触发剪藏，看看是否有报错输出。

**Comment by 88250** [comment]
刚刚我测试了 Edge 108.0.1462.54，SiYuan 扩展 1.1.4，剪藏测试地址 https://baijiahao.baidu.com/s?id=1753470093678498010

可以正常剪藏。

**Comment by Lyn6969** [comment]
> 刚刚我测试了 Edge 108.0.1462.54，SiYuan 扩展 1.1.4，剪藏测试地址 https://baijiahao.baidu.com/s?id=1753470093678498010
> 
> 可以正常剪藏。

![image](https://user-images.githubusercontent.com/42564665/209965743-31dcb26d-3cb0-4635-8eb3-06e40201ec7f.png)
有一个这个报错

**Comment by 88250** [comment]
这个是网页本身的报错，不是扩展报的。

**Comment by 88250** [comment]
对了，再确认一下是不是开了网络代理类的扩展或者软件，或者设置了网络代理，导致 SiYuan 扩展无法请求到 127.0.0.1 上的内核接口。

**Comment by Lyn6969** [comment]
> 

我的代理是在软路由上的，本地没有开代理。。软路由上的也会影响么

**Comment by Lyn6969** [comment]
> > 
> 
> 我的代理是在软路由上的，本地没有开代理。。软路由上的也会影响么

我那个低版本（102.0.5005）的chrome就没有这个情况，奇怪，

**Comment by Lyn6969** [comment]
> > > 
> > 
> > 
> > 我的代理是在软路由上的，本地没有开代理。。软路由上的也会影响么
> 
> 我那个低版本（102.0.5005）的chrome就没有这个情况，奇怪，

前面正常cliping,就到最后，需要create ariticle的时候，什么也不出现就过去了，最后就没有生成文章

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/209967088-65c4acff-21f9-4853-a213-28e35cd76412.png)

![image](https://user-images.githubusercontent.com/873584/209967107-d6c5d407-8e0f-4f35-876a-4151b980457f.png)


然后剪藏一个网页后看看这个检查视图中是否有请求

![image](https://user-images.githubusercontent.com/873584/209967208-d9b5c915-540a-4842-9e84-34494c01d871.png)

**Comment by Lyn6969** [comment]
![image](https://user-images.githubusercontent.com/42564665/209967754-1e92c979-c0ac-4be0-9075-bb9f43fa7fa4.png)

**Comment by Lyn6969** [comment]
![image](https://user-images.githubusercontent.com/42564665/209968250-670db568-edfe-4422-a00d-7d9b98ccf8e1.png)
重新截了一个

**Comment by 88250** [comment]
看下这个 Edge 选项，地址栏直接输入：`edge://flags/#block-insecure-private-network-requests`

![image](https://user-images.githubusercontent.com/873584/209968610-f83b126e-d6bf-4201-9c36-7266335468f7.png)

**Comment by Lyn6969** [comment]
![image](https://user-images.githubusercontent.com/42564665/209969737-d4271d10-477e-4541-8f5a-2eec386ed2c4.png)

**Comment by 88250** [comment]
下个开发版 v2.6.1-dev3 稍微调整了一下代码，但不确定是否有效，等发布以后麻烦下载测试看看。

**Comment by 88250** [comment]
> ![image](https://user-images.githubusercontent.com/42564665/209969737-d4271d10-477e-4541-8f5a-2eec386ed2c4.png)

这个选项调整成 Disabled 试试。

**Comment by Lyn6969** [comment]
好的，我要睡了，明天早晨起来继续测试，谢谢您！晚安！

**Comment by 88250** [comment]
好的，晚安。

**Comment by Lyn6969** [comment]
> > ![image](https://user-images.githubusercontent.com/42564665/209969737-d4271d10-477e-4541-8f5a-2eec386ed2c4.png)
> 
> 这个选项调整成 Disabled 试试。

修改了一下，还是不行呢

**Comment by 88250** [comment]
我搜了下，这个多半是 Chromium 内核的问题，可能下次 Edge 更新以后就好了。

**Comment by 88250** [comment]
目前也可以下载 v2.6.1-dev3 试试看有没有帮助，如果没有的话就等浏览器更新看看。

**Comment by Lyn6969** [comment]
> 目前也可以下载 v2.6.1-dev3 试试看有没有帮助，如果没有的话就等浏览器更新看看。

好的，辛苦啦

**Comment by Mikeal-red** [comment]
> ![image](https://user-images.githubusercontent.com/873584/209967088-65c4acff-21f9-4853-a213-28e35cd76412.png)
> 
> ![image](https://user-images.githubusercontent.com/873584/209967107-d6c5d407-8e0f-4f35-876a-4151b980457f.png)
> 
> 然后剪藏一个网页后看看这个检查视图中是否有请求
> 
> ![image](https://user-images.githubusercontent.com/873584/209967208-d9b5c915-540a-4842-9e84-34494c01d871.png)

我用chrome，查看视图Service Worker，network没反应

**Comment by Mikeal-red** [comment]
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/56062435/210033634-6bd63ddd-71dc-482b-9e59-c81ef2de0b5d.png">
chrome是酱婶的

**Comment by 88250** [comment]
@Mikeal-red 升级到最新版本的 Chrome 试试

**Comment by Mikeal-red** [comment]
> @Mikeal-red 升级到最新版本的 Chrome 试试

Chrome 已是最新版本
版本 108.0.5359.124（正式版本） (arm64)

**Comment by 88250** [comment]
下载 SiYuan v2.6.1-dev3 试试看有没有帮助

**Comment by dejavudwh** [comment]
> create article successfully

@88250 还是不可以，没有create article successfully的提示

**Comment by 88250** [comment]
暂时没法定位问题了，等 Edge 更新后再看看。

**Comment by Mikeal-red** [comment]
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/56062435/210348579-cfbce8b3-02de-4e84-95ea-0b520d827e1a.png">

大佬，更新了，没重启呢，这个能看出来问题么，需不需要我上传app log

**Comment by 88250** [comment]
@Mikeal-red 看一下 Console 里的报错信息。

**Comment by Mikeal-red** [comment]
[system-log.zip](https://github.com/siyuan-note/siyuan/files/10336183/system-log.zip)

**Comment by Mikeal-red** [comment]
> @Mikeal-red 看一下 Console 里的报错信息。
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/56062435/210349905-01a19812-3202-4778-b8e1-cf0c7dfbacac.png">

console里是空的

我刚才看了一眼trojanX的端口是 http://127.0.0.1:1089/proxy.pac 插件失灵跟这个有关系么

**Comment by 88250** [comment]
127.0.0.1 不要配置代理。

**Comment by Mikeal-red** [comment]
> 127.0.0.1 不要配置代理。

而且不对，我去翻了一下自己的使用历史，是先安装的代理，后使用的剪藏，剪藏好使过一段时间，如果变量没问题的话，不是代理的事儿

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/56062435/210367041-c7054877-35ff-455f-8b41-265ee015c3d1.png">


还有大佬，我看了下问题，可能是这个问题，个人可以刷新自己的API token么，会不会是这个账号下的api token失效了😂

**Comment by 88250** [comment]
API token 不对的话会报错提示的。

**Comment by Mikeal-red** [comment]
> API token 不对的话会报错提示的。

大佬不对哦，我刚才故意删了一半的token，只剩一半，反应全粘贴进去是一样的，我现在合理觉得是token不对😂

**Comment by Mikeal-red** [comment]
<img width="214" alt="image" src="https://user-images.githubusercontent.com/56062435/210473684-8f8ef2fe-0700-49b0-8046-89a561c7586d.png">
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/56062435/210473761-82fe43ec-b26c-4804-bb4b-8e965a555703.png">
<img width="214" alt="image" src="https://user-images.githubusercontent.com/56062435/210473788-8878fcbe-80a4-47d2-b1be-004d00f4f411.png">
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/56062435/210473848-19598e3f-7226-4017-ae86-779ea1d2c68b.png">
第1,2张图是明显不对的token和插件的Service Worker
第3,4张图是正确的token和Service Worker

**Comment by 88250** [comment]
红字的请求失败 Console 里面没有打印错误吗？

**Comment by Mikeal-red** [comment]
> 红字的请求失败 Console 里面没有打印错误吗？

我确定没有，昨天就翻了半个小时了，只有3个黄叹号还怎么勾条件都不显示

有办法调整一下我的token试验一下么

**Comment by 88250** [comment]
工作空间/conf/conf.json 里面可以改 token

**Comment by Lyn6969** [comment]
更新了思源2.6.2和新的edge108.0.1462.76，好像还是不行
![image](https://user-images.githubusercontent.com/42564665/210956207-d6d6e7f9-3ca0-417c-97d2-351f2a8ed1e3.png)

**Comment by Lyn6969** [comment]
> > 红字的请求失败 Console 里面没有打印错误吗？
> 
> 我确定没有，昨天就翻了半个小时了，只有3个黄叹号还怎么勾条件都不显示
> 
> 有办法调整一下我的token试验一下么

请问这个问题你修复了吗，我的还是没有修复

**Comment by Lyn6969** [comment]
> > create article successfully
> 
> @88250 还是不可以，没有create article successfully的提示

请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏

**Comment by 88250** [comment]
没有找到问题，我这里使用正常。

**Comment by Mikeal-red** [comment]
> > > 红字的请求失败 Console 里面没有打印错误吗？
> > 
> > 
> > 我确定没有，昨天就翻了半个小时了，只有3个黄叹号还怎么勾条件都不显示
> > 有办法调整一下我的token试验一下么
> 
> 请问这个问题你修复了吗，我的还是没有修复

我已经弃疗了，不用这个插件了，问题解决不了

**Comment by Mikeal-red** [comment]
> > > create article successfully
> > 
> > 
> > @88250 还是不可以，没有create article successfully的提示
> 
> 请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏

就神奇，你一直在问edge，我就下载了edge试了一下，我这edge居然没问题。。。果然挂着🪜也没事儿，跟端口没关系
要么就是chrome的问题，要么就是siyuan跟chrome的适配问题
不知道你那边是什么情况

**Comment by dejavudwh** [comment]
> > > > create article successfully
> > > 
> > > 
> > > @88250 还是不可以，没有create article successfully的提示
> > 
> > 
> > 请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏
> 
> 就神奇，你一直在问edge，我就下载了edge试了一下，我这edge居然没问题。。。果然挂着🪜也没事儿，跟端口没关系 要么就是chrome的问题，要么就是siyuan跟chrome的适配问题 不知道你那边是什么情况

感觉应该不是chrome的问题，俩都是chromium，我这边edge也有问题。

**Comment by Lyn6969** [comment]
> > > > create article successfully
> > > 
> > > 
> > > @88250 还是不可以，没有create article successfully的提示
> > 
> > 
> > 请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏
> 
> 就神奇，你一直在问edge，我就下载了edge试了一下，我这edge居然没问题。。。 然后看了公告，果然就是端口的问题，我改了下端口现在没问题了，插件能用了 D大流批

哪里的公告吖，我也改下端口试试

**Comment by Mikeal-red** [comment]
> > > > > create article successfully
> > > > 
> > > > 
> > > > @88250 还是不可以，没有create article successfully的提示
> > > 
> > > 
> > > 请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏
> > 
> > 
> > 就神奇，你一直在问edge，我就下载了edge试了一下，我这edge居然没问题。。。 然后看了公告，果然就是端口的问题，我改了下端口现在没问题了，插件能用了 D大流批
> 
> 哪里的公告吖，我也改下端口试试

版本更新公告，或者你去siyuan设置选项里边的端口那里看一眼就明白了，最新版的思源会告诉你现在用哪个端口，你去改了就行

**Comment by Lyn6969** [comment]
> > > > > > create article successfully
> > > > > 
> > > > > 
> > > > > @88250 还是不可以，没有create article successfully的提示
> > > > 
> > > > 
> > > > 请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏
> > > 
> > > 
> > > 就神奇，你一直在问edge，我就下载了edge试了一下，我这edge居然没问题。。。 然后看了公告，果然就是端口的问题，我改了下端口现在没问题了，插件能用了 D大流批
> > 
> > 
> > 哪里的公告吖，我也改下端口试试
> 
> 版本更新公告，或者你去siyuan设置选项里边的端口那里看一眼就明白了，最新版的思源会告诉你现在用哪个端口，你去改了就行

好的谢谢你

**Comment by Lyn6969** [comment]
> > > > > > create article successfully
> > > > > 
> > > > > 
> > > > > @88250 还是不可以，没有create article successfully的提示
> > > > 
> > > > 
> > > > 请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏
> > > 
> > > 
> > > 就神奇，你一直在问edge，我就下载了edge试了一下，我这edge居然没问题。。。 然后看了公告，果然就是端口的问题，我改了下端口现在没问题了，插件能用了 D大流批
> > 
> > 
> > 哪里的公告吖，我也改下端口试试
> 
> 版本更新公告，或者你去siyuan设置选项里边的端口那里看一眼就明白了，最新版的思源会告诉你现在用哪个端口，你去改了就行

好的谢谢你

**Comment by Lyn6969** [comment]
> > > > > > > create article successfully
> > > > > > 
> > > > > > 
> > > > > > @88250 还是不可以，没有create article successfully的提示
> > > > > 
> > > > > 
> > > > > 请问这个问题你解决了吗，我的edge更新到109版本了，这个问题还是存在，无法剪藏
> > > > 
> > > > 
> > > > 就神奇，你一直在问edge，我就下载了edge试了一下，我这edge居然没问题。。。 然后看了公告，果然就是端口的问题，我改了下端口现在没问题了，插件能用了 D大流批
> > > 
> > > 
> > > 哪里的公告吖，我也改下端口试试
> > 
> > 
> > 版本更新公告，或者你去siyuan设置选项里边的端口那里看一眼就明白了，最新版的思源会告诉你现在用哪个端口，你去改了就行
> 
> 我改了端口还是和原来一样

我发现每次失效之后，把思源插件关闭重新打开，就可以使用了，过一会又会失效
