### ISSUE TITLE
打开文件夹时同步打开文件夹下 README

### ISSUE THREAD

**Issue by lepecoder** [siyuan-note/siyuan#691]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在思源笔记用户指南中的markdown使用指南中，假设我对markdown一窍不通，我根本不知道应该从何看起，毕竟文件夹里的markdown文件又不能自定义顺序。
![](https://i.loli.net/2020/12/10/kWs5ySG3iMIZmdx.png)

### 描述最优的解决方案 Describe the optimal solution
一个简单的解决方案是在文件命名时标上序号，但这并不能将文件夹里的内容组织起来，而且也不好看。

更好的方案是在打开文件夹时同步的打开文件夹里**同名的markdown文件**。如果没有，那可能这个文件里的内容不需要组织。

**Comment by 88250** [comment]
我觉得还是现在这样好一些，因为如果展开文件夹就开一个编辑页签的话有的时候很干扰哦，谢谢提议。

**Comment by lepecoder** [comment]
> 我觉得还是现在这样好一些，因为如果展开文件夹就开一个编辑页签的话有的时候很干扰哦，谢谢提议。

是，我也考虑到了，所以我说打开**同名的文件**，如果不需要打开一个编辑页签不创建同名文件就好了。

**Comment by 88250** [comment]
但这个规则有点隐性，有点类似 README 的感觉，这个我们再考虑下，说不定用 README 也不错 😂

**Comment by lepecoder** [comment]
是的，README除了名字不太直观，用处和我想的倒是一样，在Github里打开一个子文件夹也会自动打开里面的README(如果存在的话)，我觉得还是挺有用的，许多时候还是需要给文件夹里的内容组织一下。

**Comment by 88250** [comment]
好的，要不我们就暂定为 README？我 reopen 一下，看看其他人的想法。

**Comment by 88250** [comment]
还是暂时关闭了，以后再考虑，感谢讨论。
