### ISSUE TITLE
卡包管理功能

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#6910]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

统一的卡包管理界面，包括卡包的增，删，重命名，合并功能

### 描述可能的最优解决方案 Describe the optimal solution

参考文件树功能

**Comment by 88250** [comment]
闪卡不是独立存在的，内容块即闪卡。

卡包的重命名还在考虑是否需要支持，感谢反馈。
