### ISSUE TITLE
Hello! Found a problem, there are too many export file formats, can you allow users to arbitrarily hide the export file formats that are not commonly used? Version: 2.5.5-dev1 System: Windows10 If possible, the file export experience will be even better! Hopefully it will be available in the next version.

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#6912]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Hello! Found a problem, there are too many export file formats, can you allow users to arbitrarily hide the export file formats that are not commonly used?
Version: 2.5.5-dev1
System: Windows10
If possible, the file export experience will be even better! Hopefully it will be available in the next version.

### 描述可能的最优解决方案 Describe the optimal solution

Hello! Found a problem, there are too many export file formats, can you allow users to arbitrarily hide the export file formats that are not commonly used?
Version: 2.5.5-dev1
System: Windows10
If possible, the file export experience will be even better! Hopefully it will be available in the next version.

### 其他信息 Other information

Hello! Found a problem, there are too many export file formats, can you allow users to arbitrarily hide the export file formats that are not commonly used?
Version: 2.5.5-dev1
System: Windows10
If possible, the file export experience will be even better! Hopefully it will be available in the next version.

**Comment by 88250** [comment]
Hello, there is no modification plan for this part, you can try to achieve it by customizing the theme or modifying the source code.

**Comment by zhouxinghong** [comment]
> Hello, there is no modification plan for this part, you can try to achieve it by customizing the theme or modifying the source code.

May I ask which code is this function implemented in, can I modify it through css?

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/209419000-425000e7-5040-41a6-93c4-b0fef706de3b.png)
