### ISSUE TITLE
Hello! Request a question, how to disable mouse click on picture to darken Version: 2.5.5-dev1 System: Windows10 I really don't know where to fix this problem, hope I can get your help. Thanks!

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#6913]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Hello! Request a question, how to disable mouse click on picture to darken
Version: 2.5.5-dev1
System: Windows10
I really don't know where to fix this problem, hope I can get your help. Thanks!

### 描述可能的最优解决方案 Describe the optimal solution

Hello! Request a question, how to disable mouse click on picture to darken
Version: 2.5.5-dev1
System: Windows10
I really don't know where to fix this problem, hope I can get your help. Thanks!

### 其他信息 Other information

Hello! Request a question, how to disable mouse click on picture to darken
Version: 2.5.5-dev1
System: Windows10
I really don't know where to fix this problem, hope I can get your help. Thanks!

**Comment by 88250** [comment]
Hello, this is a feature and cannot be disabled.

**Comment by zhouxinghong** [comment]
> Hello, this is a feature and cannot be disabled.

May I ask which code is this function implemented in, can I modify it through css?

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/209418968-2ac0c011-1e10-4f7c-ab05-b49b38ef07ad.png)

**Comment by zhouxinghong** [comment]
> ![image](https://user-images.githubusercontent.com/873584/209418968-2ac0c011-1e10-4f7c-ab05-b49b38ef07ad.png)

May I ask which style file this is from? Thanks!
