### ISSUE TITLE
命名查询不再持久化布局

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#6919]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![222](https://user-images.githubusercontent.com/38906705/209454714-229ad01c-b5c3-40b9-a6ef-5417b0f1e0ff.gif)

### 期待的结果 Expected result

保持搜索布局

### 版本环境 Version environment

```markdown
- Version: v2.5.5
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
需要保存为命名查询才能生效。

**Comment by 88250** [comment]
考虑了一下，布局还是独立存在比较好，不再通过命名查询持久化。
