### ISSUE TITLE
{{.title}} 模板需要修正的几个地方

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#692]
使用 `{{.title}}` 模板后，发现有如下位置未被正确替换：

* [x] 在反向链接里，`{{.title}}` 未被替换成文档名
* [ ] 在导出标准 Markdown 文件时，`{{.title}}` 未被替换成文档名
* [x] 书签、标签里，`{{.title}}` 未被替换成文档名
* [x] 在快速搜索里，`{{.title}}` 未被替换成文档名
* [x] 大纲中 `{{.title}}` 未被替换为标题名

**Comment by walklty** [comment]
另外, 能否只显示文件名而不是完整路径?

**Comment by 88250** [comment]
> 另外, 能否只显示文件名而不是完整路径?

v0.5.3 已做修正。

**Comment by deerainw** [comment]
> 在反向链接里，{{.title}} 未被替换成文档名

此问题未修复成功，现在引用文档的时候，反向链接里的 `{{.title}}` 被替换成了正文...

**Comment by 88250** [comment]
v0.5.41 中修复，谢谢。

**Comment by 88250** [comment]
做了一个不兼容变更：废弃锚文本模板变量 `{{.title}}` #771
