### ISSUE TITLE
docker windows版一直重启

### ISSUE THREAD

**Issue by pstandard** [siyuan-note/siyuan#6921]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

用这个运行命令一直重启
docker run  --name siyuan -it -d  --restart=always -v /mnt/d/software/SiYuan:/home/siyuan/Documents/SiYuan -p 6806:6806 b3log/siyuan --ssl=true

错误提示：
create os tmp dir [/home/siyuan/Documents/SiYuan/temp/os] failed: mkdir /home/siyuan/Documents/SiYuan/temp: permission denied

在本机的d盘下的SiYuan目录已经加入了everyone这个有用户的完全权限/。

### 期待的结果 Expected result

能正常运行。

### 版本环境 Version environment

```markdown
- Version: SiYuan v2.5.5
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

2022-12-25 14:49:39 2022/12/25 14:49:39 create os tmp dir [/home/siyuan/Documents/SiYuan/temp/os] failed: mkdir /home/siyuan/Documents/SiYuan/temp: permission denied

**Comment by 88250** [comment]
建议看下部署文档解决权限问题。

**Comment by pstandard** [comment]
Auto reply:
    Your E-mail message has been delivered.
    您的邮件已送达我的邮箱。
***@***.***

**Comment by HK115** [comment]
启动命令没加授权码
