### ISSUE TITLE
输入 -> 或者 --> 时自动转换成➝

### ISSUE THREAD

**Issue by ziran3** [siyuan-note/siyuan#6922]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当在写流程或步骤时， 不知可否也做一个类似的功能

### 描述可能的最优解决方案 Describe the optimal solution

不少类似软件都会有这样的功能

**Comment by 88250** [comment]
感谢提议，不过这个不考虑支持了，建议试下输入法是否有类似设置。
