### ISSUE TITLE
Ctrl+X 、 Ctrl+V 移动笔记之后，导致块ID变化

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#6923]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

非常喜欢思源笔记的 siyuan:// 功能，可以通过其他软件链接到思源笔记，但是在最新版本（v2.5.5）发现这个问题：
Ctrl+X 、 Ctrl+V 移动笔记之后，块ID发生变化，之前放在别的软件的 siyuan:// 变成无效链接，双击或单击跳转到思源笔记时，思源笔记右上角红框提示“未找到 ID 为 [20221226001926-cud6m9s] 的内容块，请在文档树面板菜单 [重建索引] 以后再试 ”

之前的版本好像是Ctrl+X 、 Ctrl+V之间的时间间隔比较短的话，块ID不变，时间间隔比较长的话，也会变，但是可以忍受，不知道从哪个版本开始，不管Ctrl+X 、 Ctrl+V之间时间间隔长短，都会更改块ID

另外一个问题应该也是这个机制导致的：我笔记右上角经常有 “block not found” 红色弹窗，之前一直不知道什么原因，现在发现是Ctrl+X 、 Ctrl+V移动块之后，会更改移动的块的ID，导致移动之前使用“复制该块为引用块”然后粘贴得到的双链失效（我的笔记哭唧唧）

使用     “复制该块为引用块”然后粘贴，“转换为-定义块及其子块”      这个流程移动笔记块不会出现上述问题，暂时可以顶一顶

### 期待的结果 Expected result

Ctrl+X 、 Ctrl+V 之间不管时间长短，都不会更改块ID，

但是可能会带来一个问题：如果Ctrl+X 之后，多次 Ctrl+V ，会不会使得第二次及其之后的Ctrl+V产生的块ID冲突？

### 版本环境 Version environment

```markdown
- Version: 2.5.5
- Operating System: windows 10
- Browser (if used): 谷歌浏览器
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/6807
