### ISSUE TITLE
设置块引静态锚文本转义问题

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6924]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如下图所示, 锚文本输入框中输入 `0-&-1-"-2-<-3->-4` 后渲染为了 `0-&amp;-1-&quot;-2-&lt;-3-&gt;-4`, 且关闭静态锚文本输入框后再打开输入框内容也更改为了 `0-&amp;-1-&quot;-2-&lt;-3-&gt;-4`, 应该是保存时出现了问题
![image](https://user-images.githubusercontent.com/49649786/209494269-d3a14f6f-86ed-4720-bf07-5549f8f616c2.png)

### 期待的结果 Expected result

锚文本输入框中输入 `0-&-1-"-2-<-3->-4` 正常渲染为 `0-&-1-"-2-<-3->-4`

### 截屏或者录屏演示 Screenshot or screen recording presentation

锚文本对符号 `&` `"` `<` `>` 不转义

### 版本环境 Version environment

```markdown
- Version: 2.6.0-dev3
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

### 更多信息 More information

动态锚文本无该情况出现

**Comment by Vanessa219** [comment]
e3d0573b5a199d729bd9c8a4aaa9ecfc3d70150c
