### ISSUE TITLE
反引号（` `）标记的文字全都没了

### ISSUE THREAD

**Issue by MingdaZheng** [siyuan-note/siyuan#6927]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

单个笔记本中所有笔记的中的反引号（\` \`）标记的文字全都没了.....

### 期待的结果 Expected result

非常着急，全部笔记都出现了该问题，需要马上修复。

### 版本环境 Version environment

```markdown
- Version: v2.1.13 年费用户
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10304154/siyuan.log)

**Comment by 88250** [comment]
不要混用 v2.2.0 之前的版本和最新版，否则会出现该问题。

只能通过备份或者快照回滚。
