### ISSUE TITLE
改进闪卡复习交互

### ISSUE THREAD

**Issue by L-M-Sherlock** [siyuan-note/siyuan#6928]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

今天试了一下 2.6.0 的闪卡功能，发现点开闪卡后，还没有点 show，就可以点  again、hard、good、easy 等评分按钮。另外这些评分按钮上也没有显示下一次复习是多久之后。

![image](https://user-images.githubusercontent.com/32575846/209610645-461be309-a6ff-4059-affd-f21a47a7f33e.png)

### 描述可能的最优解决方案 Describe the optimal solution

参考 Anki 的实现：

点击显示答案前：

![image](https://user-images.githubusercontent.com/32575846/209610786-9953e653-7713-41a2-828a-7a58980dfc82.png)

点击显示答案后：

![image](https://user-images.githubusercontent.com/32575846/209610798-b8ac7878-e77a-4798-8312-517372663368.png)

**Comment by Danielypzhang** [comment]
还有其他的改进，请考虑
没办法手动修改到期日
重要性没办法标识

**Comment by wfan14513** [comment]
安卓手机端，打开菜单选了闪卡后，菜单不会消失挡住了闪卡。

**Comment by Danielypzhang** [comment]
@88250 闪卡的时间计算感觉是精确到了小时，我下午创建的闪卡，第二天上午没有显示，到了下午才有，感觉是24小时。应该是过了零点到了第二天就应该显示。

**Comment by 88250** [comment]
@Danielypzhang 是的，这个应该没有问题。

**Comment by 88250** [comment]
> 安卓手机端，打开菜单选了闪卡后，菜单不会消失挡住了闪卡。

https://github.com/siyuan-note/siyuan/issues/6935

**Comment by Danielypzhang** [comment]
@88250 今天又遇到了，早上没有闪卡任务，晚上才有。

**Comment by 88250** [comment]
我感觉这个应该是正常的吧，按照算法给定的到期时间后才显示。

**Comment by Zuoqiu-Yingyi** [comment]
`2.6.1-dev3` 版本点击 show 按钮后就没法再次隐藏挖空的内容了, 是不是应该在点击后保留该按钮, 并将该按钮功能更改为显示/隐藏

**Comment by 88250** [comment]
> `2.6.1-dev3` 版本点击 show 按钮后就没法再次隐藏挖空的内容了, 是不是应该在点击后保留该按钮, 并将该按钮功能更改为显示/隐藏

好像其他软件也是这样的。

**Comment by L-M-Sherlock** [comment]
> 好像其他软件也是这样的。

他说大概是撤销复习的功能。

**Comment by 88250** [comment]
这个不太确定，先这样，后面收集反馈了再看看。

**Comment by 88250** [comment]
@L-M-Sherlock 老铁，有个问题请教一下，复习评分 go-fsrs 支持撤销吗？或者一般是如何处理评分后撤销的？

**Comment by L-M-Sherlock** [comment]
> @L-M-Sherlock 老铁，有个问题请教一下，复习评分 go-fsrs 支持撤销吗？或者一般是如何处理评分后撤销的？

go-fsrs 返回的是 card 和 revlog，把传入的 card 存一份，撤回的时候覆盖回去应该就行了。revlog 就直接丢掉最新的。

**Comment by 88250** [comment]
谢谢，后面我试试看。
