### ISSUE TITLE
增加钉住的快捷键

### ISSUE THREAD

**Issue by Danielypzhang** [siyuan-note/siyuan#6929]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

引用悬浮窗口，弹出后如果要钉住需要移动鼠标点钉住的按钮。有时候窗口高度和宽度问题，鼠标移动会比较麻烦，而且还有可能移到窗口外，导致窗口消失。

### 描述可能的最优解决方案 Describe the optimal solution

增加快捷键，可以方便操作。

**Comment by ippreacher** [comment]
个人觉得可以考虑移动了悬浮窗口后即自动设置为钉住。因为移动它就说明你想把它放在合适的位置作后续参考。

**Comment by 88250** [comment]
快捷键暂时不考虑增加了，移动后钉住的建议比较好，我们先实现这个，谢谢。
