### ISSUE TITLE
折叠的标题块拖动后未显示折叠状态

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6930]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

标题块折叠后拖动, 拖动后的小三角显示该块并未折叠, 点击小三角后折叠, 再点击小三角后展开

### 期待的结果 Expected result

标题块折叠后拖动, 拖动后的小三角显示该块折叠, 点击小三角后展开

### 截屏或者录屏演示 Screenshot or screen recording presentation

![思源笔记-bug反馈-45](https://user-images.githubusercontent.com/49649786/209619470-7344ac86-5ea2-4a7b-944d-4e97f535d859.gif)

### 版本环境 Version environment

```markdown
- Version: 2.6.0
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by Geo123abc** [comment]
https://github.com/siyuan-note/siyuan/issues/6807?utm_source=ld246.com#issuecomment-1364861339
