### ISSUE TITLE
Spaced repetition system

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#6932]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Today the flashcard system works:

        1 - Creating a title
        2 - Then select the answer with "Mark" in text editing.

I see this little bad, because what about the tables? Images? It will be a headache for you.

### 描述可能的最优解决方案 Describe the optimal solution

My sugestion:

       1 - Create a title
       2 - Add a command so that everything below it is the answer.

Example:

![image](https://user-images.githubusercontent.com/90691302/209652739-4753480a-41e6-4bdf-b553-45cfa5b69cfd.png)

Everything below the "::" command would be shown as a response to the card.

**Comment by 88250** [comment]
Hello, the part that needs to be an answer can be hollowed out with span-level mark elements. This is by design and will not be considered to change at present, thank you.
