### ISSUE TITLE
内置pdf阅读器的导航栏宽度可调

### ISSUE THREAD

**Issue by jiewangjs** [siyuan-note/siyuan#6933]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

阅读pdf文件时

### 描述可能的最优解决方案 Describe the optimal solution

Navigation pane宽度可调

### 描述候选的解决方案 Describe the candidate solution

pdf.js默认是可以调节的，作者您是不是写死了？

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3005
