### ISSUE TITLE
Deck（卡包）树状结构

### ISSUE THREAD

**Issue by kx1356** [siyuan-note/siyuan#6936]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前还看不了卡包里包含有哪些闪卡，没办法我只好新建一个笔记本单独放卡片，这样一来就增加了工作量，也破坏了原本的笔记结构。

### 描述可能的最优解决方案 Describe the optimal solution

![微信截图_20221228101648](https://user-images.githubusercontent.com/83316329/209746855-8938dbdb-9b7c-4ad1-ac00-bcd4fb499285.png)
![微信截图_20221228101952](https://user-images.githubusercontent.com/83316329/209747083-dcc6d93f-f087-4576-80f6-accdebc31039.png)

可否借鉴【闪记卡】这种文件结构来显示闪卡，这种文件结构跟思源很像。

**Comment by 88250** [comment]
这个暂时不考虑了，后期可能可以期待一下通过挂件查询实现，感谢提议。

**Comment by 88250** [comment]
下个版本改进 https://github.com/siyuan-note/siyuan/issues/6943 但是卡包结构不是树状的，所以是平铺闪卡。
