### ISSUE TITLE
关于间隔复习（闪卡）功能的建议

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#6940]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

非常欣兴喜的看到思源推出了间隔复习功能，感谢两位开发者的辛劳付出。多少年来，我一直觉的市面上的笔记软件功能是不完全的，因为学习的过程一直是“记+背”同时进行的，但市面的笔记软件却好像对“记”这一功能情有独钟，鲜有结合“背”这一功能进行开发的。思源这次推出的间隔复习功能补全了我多年的夙愿，但还有些地方需要改进，希望两位开发者能考虑。

### 描述可能的最优解决方案 Describe the optimal solution

1. 能像Anki那样自由地制卡，并能锚定制卡所依据的块位置。现阶段的闪卡，制卡只能在原文的内容的基础上简单的挖空，而不能在制卡中加入自己的理解过程。这样制的卡在记忆过程中会行成一种记住了但又没记住的错觉，典型的例子就是我们小时候背古诗，“床前明月光，疑是地上霜……”，老师检查时，“静夜思  李白  、嗯……嗯……”，这时，老师提醒了，“床前”，“哦，想起来了，床前明月光，疑是地上霜……”，看者全背下来了，好像学会记住了，但当考试时，若出的是后半句填前半句时，多半还是要挂掉的。所以我建议能给更高的灵活度去制卡，以加深理解，同时为了以后复习遇到疑惑方便溯源，制的每张卡都能锚定制卡所依据的块位置。比如，某个块的内容是“A 是 B 的父亲”，选中这个块开始制卡，制的第一张卡是“A 是 B 的？”，制的第二张卡是“B 是 A 的？”，制的第三张卡是“A 和 B 的关系是？”，并且以上三张卡都能锚定“A 是 B 的父亲”这个块，都能随时返回源文查看。
2. 所制卡片应该被看作是另一类笔记，而不是“内容块被删除（或者 ID 改变）后对应的闪卡会失效”。制卡的过程中每提一个问题（作一次QA问答）都是对原笔记的一次理解，这些卡片或许比笔记内容更有意义，所以当“内容块被删除（或者 ID 改变）时”，它们所对应的卡片应该仅仅是被标记为锚点位置丢失，应能继续对其进行背诵记忆，而非不可见。
3. 增加闪卡的管理和整理功能。选中某个卡包后，能进入这个卡包查看这个卡包里所有的卡片，并以表格的行式展示出卡片的问题内容、答案内容、所在卡包、锚定的块位置等关键信息，以方便筛选整理。
4. 改进卡片与其所对应内容块的交互形式。首先在卡片的区域，没必要把可编辑的笔记页面搬上去，只单纯地显示不可编辑的问题和答案就好了，在记忆卡片时，并不经常需要去编辑其对应的内容块，所以在卡片区域的边角不起眼地方放两个按钮“编辑卡片”、“回到其对应的内容块位置”即可。然后就是内容块区域，目前，制卡后，会有一道橙色的杠做为提示，这还不够，应该像反链那样，鼠标停留上去后，会显示出这个块对应的所有卡片的问题及对应的答案来，以便复盘自己对这个块的理解程度及思路。

**Comment by 88250** [comment]
1. 生成双向卡目前没有计划；A B 这个例子可以考虑用引用关联
2. 内容块即卡，这个是设计如此
3. 卡包浏览卡还继续收集需求
4. 可以编辑是特性，前期收集过需求讨论

感谢反馈。
