### ISSUE TITLE
支持超级块制作闪卡

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6941]
通过行级标记元素作为挖空答案有点不够用，因为有需要块级作为答案的时候，比如答案是个表格或者有序列表。

支持设置超级块为闪卡，第一个子块是问题，后续子块均为答案，这样可以更灵活地制卡。

**Comment by woniuxia** [comment]
这种想法这是绝了。
超级块 YYDS!

**Comment by zxhd863943427** [comment]
大力支持，之前一直想不出如何实现这个目标，超级块确实合适

**Comment by kx1356** [comment]
标题折叠为问答不是更直接方便吗？

**Comment by 88250** [comment]
@kx1356 有的情况下不需要标题，因为标题会影响排版。

后续可能也可以考虑将标题作类似处理，即设置标题为闪卡后，该标题下方块自动作为答案，不需要手动折叠隐藏。这个还需要继续收集需求，但很有可能超级块制卡支持以后就足够使用了，不需要更多类似的制卡方式。

**Comment by haogeek** [comment]
如果使用列表块的话，那么把某一列表项作为问题，其子项作为答案，这种形式是不是比标题块更灵活

**Comment by caohongliang92** [comment]
YYDS

**Comment by ocean0117** [comment]
还是觉得列表缩进比较合理一些，毕竟列表缩进点一下tab就可以了，超级块太繁琐了

**Comment by 88250** [comment]
@ocean0117 最新版已经支持列表了。
