### ISSUE TITLE
搜索建议 希望加入todo

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#6942]
ps：如果现在不考虑，也迫切希望加入todo。。。。。。。希望开发者能劳心考虑下我的建议 我真的想永久把思源作为自己笔记软件所以很在意  谢谢谢谢

现在支持命名查询，但是切着还是好慢，比如我现在要搜文档我要点三次才能完成一次搜索。。虽然比原来的“开启小开关”来变化搜索条件好一些了

![image](https://user-images.githubusercontent.com/30001685/209897649-6944ed71-0bb1-4195-a6c3-9f9171c49925.png)

这个问题我也是提了好几次。。。都说暂时不考虑。。但我尝试适应一段时间后还是觉得很有必要很有必要改进下搜索方式

以下为建议：

可以把保存的命名查询做成一个小按钮，一个按钮代表一个自定义的查询条件，放在搜索框这里，ctrl+f后直接就能看到，搜文档就选中按钮1，搜代码就选中按钮2 这样比切换搜索点三次快的多。。。。。

![image](https://user-images.githubusercontent.com/30001685/209897845-e872063b-431a-4582-925e-f887f0938527.png)

**Comment by qing-root** [comment]
那我去社区问问意见 确实挺在意

**Comment by qing-root** [comment]
https://ld246.com/article/1672283499629   投票结果：
![image](https://user-images.githubusercontent.com/30001685/210135647-3579f416-69a3-4ba9-a4c6-d1c25bfef456.png)

**Comment by qing-root** [comment]
> 这个还需要收集更多反馈，感谢理解。

D大 投票结果如链接

**Comment by 88250** [comment]
没有太多人需要，暂时不考虑了。

**Comment by qing-root** [comment]
> 没有太多人需要，暂时不考虑了。

社区投票的人本来就少。。那就先这样把， 希望d大以后记着有这个可以优化的选项，确实很重要
