### ISSUE TITLE
支持浏览卡包内的闪卡

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6943]
类似现在的搜索界面，列出闪卡列表，选择闪卡后可以预览和编辑块。

* 分页加载列表
* 支持 `从卡包中移除`

不支持搜索，因为可以通过全局搜索来确定一个块是否已经制卡。

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 卡包预览窗口 `z-index: 305;` 过大导致悬浮预览窗口会被遮挡

**Comment by Vanessa219** [comment]
> @Vanessa219 卡包预览窗口 `z-index: 305;` 过大导致悬浮预览窗口会被遮挡

多谢 6388b3dd08200d13d2ae41e989b690133eaae0c6
