### ISSUE TITLE
默认闪卡包移除后卡住

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#6946]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

1. 在块标界面打开闪卡，可以将块加入卡组或者移除，此时如果点击删除默认卡组，会导致界面卡死，无法交互，也无法退出程序，只能在任务管理器强行关闭，再次打开后会恢复正常
2. 将一个块加入卡组后，再删除卡组，块仍然显示在卡组中（即块右侧显示黄色竖线），重新加入任意卡组再删除才会恢复正常

### 期待的结果 Expected result

期待排除相关问题

### 版本环境 Version environment

```markdown
- Version: 2.6.0
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

日志未见异常，所以未上传

**Comment by 88250** [comment]
1. 这个问题我这里无法重现
2. 这个是设计如此，因为无法确保删除卡包数据后手动恢复卡包数据，所以块上依然保留闪卡属性

我们先关闭了，如果能重现第一个问题麻烦录屏演示并跟帖，谢谢。

**Comment by TinkMingKing** [comment]
> 1. 这个问题我这里无法重现
> 2. 这个是设计如此，因为无法确保删除卡包数据后手动恢复卡包数据，所以块上依然保留闪卡属性
> 
> 我们先关闭了，如果能重现第一个问题麻烦录屏演示并跟帖，谢谢。

![动画](https://user-images.githubusercontent.com/32903588/209928136-531164c7-34a5-41da-9612-2024d1cbbb64.gif)

**Comment by TinkMingKing** [comment]
图中两处入口会无法打开闪卡，两个地方单次点击似乎不会产生问题，这两个地方多次尝试点击，之后就会无法关闭思源主界面，但是其他操作似乎不会影响

**Comment by 88250** [comment]
@TinkMingKing 我这里还是重现不了，麻烦试下 dev 版。

**Comment by TinkMingKing** [comment]
@88250 dev版依旧会这样
复现步骤大致如下：
1. 块标菜单中，将块加入默认卡组
2. 删除默认卡组
3. 回到主界面，连续快速多次点击闪卡按钮（alt+0）
4. 发现主界面部分卡住，程序无法正常关闭
仔细参考下图
![动画](https://user-images.githubusercontent.com/32903588/209949353-aa6f1810-a3bb-4c9e-91cc-932e8666d9fe.gif)



总之就是默认卡组无卡时，无法删除，点击删除会英文提示，这是正常的逻辑。但是默认卡组里面有卡时，点击删除卡组，不会报错，产生了异常，这时，块标菜单的闪卡界面和主界面的闪卡界面无法打开，且连续快速点击主界面的闪卡按钮，主界面部分地方会卡死，导致某些主界面部分按钮失效，最直观的体现是无法退出程序

**Comment by 88250** [comment]
已经可以重现，感谢反馈。
