### ISSUE TITLE
避免启动时重复全量重建索引

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6950]
有的情况下（比如删除了 temp）启动后会全量重建索引，但是如果不修改任何数据直接退出后再次启动，仍然需要全量重建索引，这个 issue 会改进这个问题，尽量只全量重建一次。

**Comment by Chenm4** [comment]
我有时候关机可能等到siyuan正常关闭就关机了（因为我siyuan关闭有点慢，要十几秒，不知道是什么原因，如果是正常现象希望改进，点击关闭按钮后最小化siyuan慢慢关也好点，现在是点击了然后右上角弹窗然后就等着），未正常关闭siyuan再开机就会显示上次没有正常关闭，可能需要重建索引，我觉得这个其实可以直接帮我重建索引吧？没必要告知用户，毕竟这样可能会增加用户焦虑和对数据的不安全感。
还有下图这个，是否可以也直接帮我默认点一下直接同步，如果实在同步不了再来个提示，我遇到这种情况一般是点个直接同步就可以了，我不知道是否有我不知道的更深层的考虑。
![Clip_2024-06-29_13-33-04](https://github.com/siyuan-note/siyuan/assets/98648589/d84880a0-ea9e-46eb-a6e1-bfa736399dde) @88250
