### ISSUE TITLE
导出MD格式的时候，能否顺带着把类似字体颜色样式也一并导出

### ISSUE THREAD

**Issue by lvzhp** [siyuan-note/siyuan#6955]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当需要导出为MD格式的时候，会发现，在思源加了字体颜色的内容，导出为md后，并没有附加颜色。
包括高亮的格式。
当然一些特殊的CSS高亮样式 md格式不支持。但是把字体颜色一并导出，Md是支持的呀。比如我们使用font color 也是可以在md中进行颜色设置的。

都是对选定内容进行类似 font color #fffff 

### 描述可能的最优解决方案 Describe the optimal solution

无

**Comment by 88250** [comment]
这个不考虑了，虽然 Markdown 规范中定义了 HTML 元素，但是实际上很多 Markdown 编辑器都不支持 HTML。
