### ISSUE TITLE
不再覆写浏览器 localStorage 存取数据

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6956]
https://github.com/siyuan-note/siyuan/issues/6404 中覆写了浏览器 localStorage 存取数据函数，这里不再覆写（不改变浏览器的实现），也不再使用浏览器的 localStorage，以便后续支持工作空间多开 #4567 

对于开发者来说，建议不要使用 localStorage，否则切换工作空间后可能会造成数据覆盖丢失。如果需要持久化数据，可考虑使用 /api/storage/setLocalStorage /api/storage/getLocalStorage 等接口 https://github.com/siyuan-note/siyuan/issues/6960

**Comment by Zuoqiu-Yingyi** [comment]
接口 `/api/storage/setLocalStorage` 可以只复写部分字段吗, 可以删除指定字段吗❓

**Comment by 88250** [comment]
> 接口 `/api/storage/setLocalStorage` 可以只复写部分字段吗, 可以删除指定字段吗❓

https://github.com/siyuan-note/siyuan/issues/6960 这里讨论提一下需求吧。
