### ISSUE TITLE
设置中显示的本机 IP 同时显示 IPv4 与 IPv6 地址

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#6958]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前大多数家宽都普及了 IPv6, 可以为局域网中每台设备分配多个公网 IPv6 地址, 因此需要在 设置>关于 中同时显示出 IPv6 地址以方便用户访问

### 描述可能的最优解决方案 Describe the optimal solution

按照网卡分类, 分别显示对应的网卡名,  v4 与 v6 地址

### 其他信息 Other information

一张网卡可能同时拥有多个 v6 地址, 例如
- `IPv6 地址1`
- `IPv6 地址2`
- `临时 IPv6 地址`
- `本地链路 IPv6 地址`

**Comment by 88250** [comment]
这个提议的改进用意是？

**Comment by 88250** [comment]
这个不太确定是否有必要，先不考虑了，感谢提议。
