### ISSUE TITLE
块嵌入的灵活设置

### ISSUE THREAD

**Issue by Maxpiner** [siyuan-note/siyuan#696]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在文档中嵌入较大的块，例如标题块，文档块，只想部分展示块内容。

### 描述最优的解决方案 Describe the optimal solution
以文档块为例，假设文档块id0由id1,id2,...,idn组成。
（1）当需要嵌入的内容连续时，允许`!((id0=id1:idn,"text"))`的引用格式。
（2）当需要嵌入的内容不连续时，允许`!((id0=id1,id2,"text"))`的引用格式。显然这时候块嵌入的显示上可能要有些分割线一类的东西表明是部分显示。
引用格式仅仅是举个例子，开发上的细节请开发者大大确定。
在用户的操作上可以分两类
（1）在插入块引用前确定范围：
鼠标大范围选中数个块，被选中的块可以被“复制块引用”，“粘贴块嵌入”时合并嵌入。当拖动块功能上线后，可以用shift/ctrl多选，或者多选框的方式。
（2）在插入块引用后确定范围：
直接粘贴文档块嵌入，通过UI选择截止位置。例如说拖动嵌入窗口的下边缘。

### 其他信息 Other information
前文都是正向的，即从**待引用文档**到**被引用的位置**，有时则会有反向的需要。
配合[ #556 ](https://github.com/siyuan-note/siyuan/issues/556)，我再详细描述一类应用场景。
在通过笔记分析一个问题时，我会摘录**数个来源**（例如书籍，网页等）的**数个信息**（在思源里就是块）进行对照参考，分析时或完成后将各个信息**分别归档**，这时我希望能够快捷地
（1）选中同一来源的数个块 建立新文档 或 建立新文件夹/文档 或 建立文档并归入某个文件夹。
（2）选中的块原地转化为块嵌入，在当前页面上连续排列的合并，不连续的各自转化。当然它们都会按顺序组合成新文档。
（3）块嵌入的内容和范围可能要调整。
目前我可以进入文件树操作并在各个页签内转移，但是如果能在一个页签下完成会方便很多。

在我看来，既然思源一切都是块，那么自由方便地转移，转化，排列展示块，应该是最大地发挥潜力的重要途经。

**Comment by 88250** [comment]
1. 连续的块可以使用超级块嵌入
2. 非连续的块可以用 SQL 查询嵌入

第二个对于非程序员不够友好，后期看看能不能加个可视化 SQL 编辑器来解决。批量块引 id 语法在设计之初就考虑过，否掉的原因是语法有点啰嗦，且功能其实不足够强。

后面等块拖动还有折叠实现好，我们再考虑更多可能的转换、呈现特性，感谢讨论。

**Comment by Maxpiner** [comment]
虽然issue关闭了，我还是觉得有必要澄清一下，就当归档吧
1.这个需求并不想该改变嵌入源的内容，而是想让嵌入范围不受文档块和标题块默认范围的束缚。
2.底层怎么实现其实用户并不需要了解原理和格式，UI做好就行了。
