### ISSUE TITLE
新增内核 API `localStorage`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6960]
该系列接口基本已经稳定，现作为公开接口发布。

**Comment by 88250** [comment]
考虑了一下，这个由内核暴露不适合，会导致前端出现多个数据副本无法保证一致性。

这个接口应该由前端 API 提供。

**Comment by HowcanoeWang** [comment]
所以现在插件想要储存一些配置到本地而不进行云同步（由于不同机器配置不同，云同步会造成数据冲突，#14579），目前推荐的方式是什么？

使用插件系统 class Kernel的saveData会在 `data/storage/{plugin-name}/xxxx` 下写入json文件，似乎是会被云同步的；
使用 `window.localStorage` 貌似不被推荐，且重启后会数据重置；
使用 `window.siyuan.storage` 似乎也有重启后会被重置的问题，不能持久化。

目前想到的替代方案是，使用saveData但文件名后面加一个系统id，保存成 `data/storage/{plugin-name}/xxxx-{siyuan.config.system.id}.json`，能一定程度上解决数据同步冲突的问题，但感觉有点不太优雅

**Comment by TCOTC** [comment]
`/api/file/putFile` ？

**Comment by HowcanoeWang** [comment]
> `/api/file/putFile` ？

这不是个创建文件或文件夹的api么

**Comment by TCOTC** [comment]
> 持久化储存一些配置到本地而不进行云同步

存文件应该就是这个吧？不过我不会用

**Comment by 88250** [comment]
写文件的话使用 putFile，如果不想同步的话：

* 写在 data 以外的目录，比如 conf 或者工作空间下新建一个文件夹
* 写在 data 内，同时修改 syncignore 排除该文件路径
* 如果数据量不大的话可以考虑用 setLocalStorage，这个会保存在 data/storage/local.json 中，这个文件默认不同步

**Comment by HowcanoeWang** [comment]
我封装了一下getLocalStorage和setLocalStorage的API，发现写入的数据可以及时的保存在 `data/storage/local.json` 文件里，但是并没有反映在 `window.siyuan.storage` 和 `siyuan.storage` 变量中？

local.json数据如下，和使用`/api/file/getLocalStorage`
```json
{
  "aaa": {
    "bbb": "ccc"
  },
  "langzhou-color-href": "/appearance/themes/toy/palette/tonight.css",
  "local-bazaar": {
    "icon": "0",
    "plugin": "2",
    "template": "0",
    "theme": "2",
    "widget": "0"
  },
  "local-dailynoteid": "20230622232525-05xvx5v",
...
```

控制台中打印的 `window.siyuan.storage` 如下：

```json
{
    "langzhou-color-href": "/appearance/themes/toy/palette/tonight.css",
    "local-bazaar": {
        "icon": "0",
        "plugin": "2",
        "template": "0",
        "theme": "2",
        "widget": "0"
    },
    "local-dailynoteid": "20230622232525-05xvx5v",
    "local-dialogposition": {
        "dialog-setting": {
            "height": 835,
            "left": 260,
            "top": 94,
            "width": 1280
        }
    },
   ...
}
```

使用API和控制台打印的数据好像也不太一样

**Comment by 88250** [comment]
@Vanessa219 帮忙看看

**Comment by Vanessa219** [comment]
这个变量是需要手动同步的。

![Image](https://github.com/user-attachments/assets/bc4777a2-c358-4115-acf8-7ab2c88518b1)

**Comment by HowcanoeWang** [comment]
setLocalStorage调用完了，感觉自动更新一下更符合逻辑？

**Comment by HowcanoeWang** [comment]
> setLocalStorage调用完了，感觉自动同步一下更符合逻辑？

**Comment by Vanessa219** [comment]
应该是推给自己会有问题，后面修改为同步到其他实例上 https://github.com/siyuan-note/siyuan/issues/6965

目前搜索了一下，使用到的地方太多了，还是自己同步一下这个变量吧。

**Comment by TCOTC** [comment]
> 我封装了一下getLocalStorage和setLocalStorage的API，发现写入的数据可以及时的保存在 data/storage/local.json 文件里，但是并没有反映在 window.siyuan.storage 和 siyuan.storage 变量中

目前发现这里接口设计有点问题，应该是调用接口之后广播到所有前端实例自动应用，不需要自行操作 window.siyuan 才对

**Comment by Vanessa219** [comment]
封装的时候自行判断一下。
