### ISSUE TITLE
改进导出 Data 压缩包过程

### ISSUE THREAD

**Issue by ad56583964** [siyuan-note/siyuan#6961]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我创建了一个siyuan_backup文件夹用于存放"导出 Data"的文件并使用百度网盘的自动同步来捕获每次在这里生成的压缩包。
但是每次在执行导出的过程中实际上还会在"此文件夹"产生文件夹，好像是在就地打包？这个过程中"百度网盘"也会捕获到然后抢占资源，有时会生成失败。

### 描述可能的最优解决方案 Describe the optimal solution

希望可以有一个选项指定生成压缩包时的temp文件夹然后导出目标文件夹可以在另一个位置

**Comment by 88250** [comment]
最新版已经不会产生文件夹了。

**Comment by ad56583964** [comment]
> 最新版已经不会产生文件夹了。

是这样...它会在生成zip的过程中产生一个文件夹，在结束后这个文件夹会消失，但是导出有几十秒的时间，这个时候 网盘的自动同步已经开始工作在操作这个文件夹中的文件了(看里面应该是data文件夹的内容)
![image](https://user-images.githubusercontent.com/20683103/210129442-93d08ffa-0372-4b64-8cfb-f283f34b6f99.png)

![image](https://user-images.githubusercontent.com/20683103/210129435-13d99fe9-5b24-4bf5-8bd7-d6a76e6ebbc1.png)

**Comment by 88250** [comment]
明白了，我们下个版本把打包过程在工作空间/temp/ 下完成，然后将生成好的 zip move 到目标路径。
