### ISSUE TITLE
【讨论下】在顶栏打开的闪卡复习窗口添加个浏览卡包的入口

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#6962]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在浏览卡包，我只找得到从块标菜单进入制卡程序，然后才能浏览卡包内的卡片。多了一步制卡的流程，而且浏览卡包的入口也不明显。

另外，考虑选中块，提供快捷键快速制卡不？

闪卡复习的界面，考虑将 Hard (H) 改为 Difficult (D)？这样可以全部通过左手键盘完成，而不必还得需要右手来按 “H“ 按键。Good 也可以改成 well （W），但是不知道意思还对不对。 
或者右手小键盘 由难到易 设置为 0,1,2,3 和 enter 为显示
或者考虑给出自定义配置？

### 描述可能的最优解决方案 Describe the optimal solution

从复习（浏览）卡片的界面在进入浏览所有卡包内卡片 应当比进入制卡程序再浏览所有卡片更清晰一点。

**Comment by 88250** [comment]
浏览放到制卡中是考虑到属于管理功能，这个暂时不变了。

快捷键位置基本也可以用一只手完成，也暂时不改了。

感谢反馈。
