### ISSUE TITLE
引用嵌套容器块触发状态异常

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#6967]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

引用不显示引用文本，删除的时候还触发了重建索引

### 期待的结果 Expected result

修复这个bug

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/37429029/210189139-5c88141b-1ce6-460c-be73-d7526032de26.mp4

### 版本环境 Version environment

```markdown
- Version: 2.6.0
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10329768/system-log.zip)

**Comment by AugustTuan** [comment]
把出问题的行删除了以后，前面的行末尾，无法换行

**Comment by 88250** [comment]
请使用默认主题测试看是否还能重现。

**Comment by AugustTuan** [comment]
> 请使用默认主题测试看是否还能重现。

我特意去默认主题重现了一次，才来提issue的

**Comment by AugustTuan** [comment]
https://user-images.githubusercontent.com/37429029/210195358-985954cc-91cc-4169-a163-c1fa9b1389ec.mp4

**Comment by AugustTuan** [comment]
并且出现这个错误，我一旦ctl+z回退就重建索引了

https://user-images.githubusercontent.com/37429029/210195369-313ff859-59a0-4d25-ab3b-9e8fb32feeb1.mp4

**Comment by 88250** [comment]
这个录屏中看不出是如何操作触发的状态异常，麻烦录屏一个完整输入文本以后删除触发状态异常的，谢谢。

**Comment by AugustTuan** [comment]
https://user-images.githubusercontent.com/37429029/210220956-b3a8e816-789f-415f-85d5-acfa72a75f72.mp4

**Comment by AugustTuan** [comment]
首先【【引用，发现不显示锚文本，
然后删除，可以正常回退到上一行，但是无法换行。最后ctl+z触发重建索引。

只要当我引用当天的日记，就会异常。

**Comment by AugustTuan** [comment]
![image](https://user-images.githubusercontent.com/37429029/210222242-7957b9a5-f187-4f08-8fea-9f7647725c06.png)
这就是我录屏里面引用的文本，这个列表里面，每一个子列表，我引用都会出现同样的问题

**Comment by 88250** [comment]
能否把这个文档导出 .sy.zip 发我试试 845765@qq.com

**Comment by AugustTuan** [comment]
![image](https://user-images.githubusercontent.com/37429029/210289313-e1450922-d91f-4e25-ba73-e62314a134ce.png)

**Comment by AugustTuan** [comment]
你按照我截图里面这个操作，可以随时复现这个bug

首先打一个纯文本

然后引用上面的纯文本

再引用这个引用
就bug了

**Comment by 88250** [comment]
感谢反馈，可以重现问题了，下个版本修复。
