### ISSUE TITLE
适配windows鼠标悬浮全屏按钮分屏预览提示

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#6968]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

鼠标移到右上角全屏按钮时，会出现分屏预览提示，可以自主选择分屏
系统：WINDOWS 11

https://user-images.githubusercontent.com/112467275/210192178-ae8dff1b-bf8d-47e7-9ae9-dfbeac9d7308.mp4

### 描述可能的最优解决方案 Describe the optimal solution

就是这样，分屏很方便。我不知道这是不是WINDOWS 11新功能。

### 其他信息 Other information
谢谢开发者

**Comment by 88250** [comment]
这个目前无法实现，因为窗口按钮不是 Windows 系统原生的。

**Comment by Benjamin-Watson0** [comment]
好的，收到
