### ISSUE TITLE
开启访问授权码后仍开放图床使用

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#6969]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在打开思源的授权码功能之后，使用思源作为图床写的markdown全部无法显示。
思源以做笔记为主，不会对外公开，但是想把某一篇文章的图片以思源资源的公开链接形式“分享”出去，比如写在markdown中。
更进一步，思源可以增加分享笔记功能，仅仅以可读的形式分享一个page页，不会受到开启思源界面授权码的影响

### 描述可能的最优解决方案 Describe the optimal solution

访问sy.xxxx.com需要授权码输入，但是访问sy.xxxx.com/assets/example.jpg没有限制，也就是说访问授权码只会限制思源主界面的加载，但是通过url可以访问想要的资源（资源名称是有日期和随机串的，一般无法直接写出）。如果是安全考虑，可以选择提供一个开关来控制是否在有授权码的情况下仍然能够通过url访问具体资源。
或者设置排除以.sy结尾的文件

**Comment by 88250** [comment]
你好，这个开关估计不会考虑添加，否则和授权码的设计相违背了。

**Comment by tangjiahao2001** [comment]
**贴贴一个解决方案，安全性肯定没有使用思源的授权码安全：**
既能够将思源当作图传使用，同时也给思源设置密码登录
#### 利用nginx设置反向代理到/stage/build/目录，给此目录增加密码访问
```
location ~ ^/stage/build/.* {
        # 仅仅为主页面设置访问密码,单独访问资源仍然可以,比如图床
        auth_basic "Please input password";
        auth_basic_user_file cert/passwd;
        
        proxy_read_timeout 60s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';

        add_header Content-Security-Policy "upgrade-insecure-requests";
        proxy_pass http://127.0.0.1:6806;
    }
```
auth_basic的设置需自行百度，有很多的资料
