### ISSUE TITLE
建议增加块内容预览的开关

### ISSUE THREAD

**Issue by hopebird** [siyuan-note/siyuan#697]
建议增加一个开关，能设置鼠标放在链接上是自动弹出内容块预览，还是单击再弹出。现在的鼠标放上去就弹出，比较灵敏，容易遮挡，影响阅读连贯性。

**Comment by 88250** [comment]
单击的话会进入编辑。

**Comment by 88250** [comment]
我关闭了，如果还有建议请继续跟帖，谢谢。
