### ISSUE TITLE
`最近使用过的字体` 列表出现重复项

### ISSUE THREAD

**Issue by choora** [siyuan-note/siyuan#6970]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

同一样式重复选择，在「最近使用过的字体」列表中重复出现，导致列表一直增长。

### 期待的结果 Expected result

同一样式不应该在列表中重复出现。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![2023-01-03 08-46-21 的屏幕截图](https://user-images.githubusercontent.com/8318196/210288025-015fa538-4b04-4a91-b2db-e21331687e7b.png)

### 版本环境 Version environment

```markdown
- Version: 2.6.1-dev6 https://github.com/siyuan-note/siyuan/releases/tag/v2.6.1-dev6
- Operating System: Ubuntu 20.04.5
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10333896/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，这个是 dev 版的问题，稍后修复。
