### ISSUE TITLE
闪卡应该增加一个“浏览”入口。

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/siyuan#6971]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我希望增加一个“浏览卡包内块（卡片）的功能”，目的为了解决浏览包内，都有哪些卡片或者想从头到尾过一遍，尤其是当某一卡包的卡片分散在各个“文档”中的时候。

一个卡包的东西，不一定都会放到同一个文档中。如果闪卡创建的很多的时候，删除卡片将变的困难。

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/53116704/210291253-2cf01d59-4215-4181-a537-9b16372787ef.png)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6943
