### ISSUE TITLE
在内置PDF阅读器中复制时，不会去除行间换行

### ISSUE THREAD

**Issue by syheliel** [siyuan-note/siyuan#6973]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

选中如下段落，进行复制：
![image](https://user-images.githubusercontent.com/45957390/210304555-12c0cb59-a1c6-4418-a418-faf8d4704354.png)
复制的结果中会以换行符分隔
```
IoTFuzzer [14] performs blackbox fuzzing directly on
the real device. Its main advantage over previous blackbox
fuzzing based approaches is that it performs the fuzzing
through the companion mobile app of the target device.
```

### 期待的结果 Expected result

希望在复制时能得到以下去除换行后的结果：
```
IoTFuzzer [14] performs blackbox fuzzing directly on the real device. Its main advantage over previous blackbox fuzzing based approaches is that it performs the fuzzing through the companion mobile app of the target device.
```

### 版本环境 Version environment

```markdown
- Version: 2.6.1
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

该问题复现应该不需要日志

**Comment by 88250** [comment]
这个问题无法解决，否则会导致其他问题 https://github.com/siyuan-note/siyuan/issues/5213
