### ISSUE TITLE
超级快制卡，复习不能隐藏子块

### ISSUE THREAD

**Issue by Danielypzhang** [siyuan-note/siyuan#6975]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

超级快制卡，复习时全部显示出来，并不是隐藏其他地方子块

### 期待的结果 Expected result

第一块作为问题@后面的作为答案

### 版本环境 Version environment

```markdown
- Version: 2.61
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
请截图展现一下超级块的结构。

**Comment by Danielypzhang** [comment]
请查看图片
![IMG_20230103_160155](https://user-images.githubusercontent.com/26704645/210319053-6ac21aac-1ca4-408d-a30f-f1cb3906c988.jpg)
@88250

**Comment by 88250** [comment]
这个不是超级块，这个是列表块哦。
