### ISSUE TITLE
闪卡块剪切粘贴异常

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#6978]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

被制成闪卡的块剪切粘贴后，块保留闪卡属性，但是闪卡包无法正常查看、删除

### 期待的结果 Expected result

期望以下两个结果之一：

1. 被制成闪卡的块剪切粘贴后，不保留闪卡属性，并同步删除闪卡包内卡片
2. 被制成闪卡的块剪切粘贴后，保留闪卡属性，且闪卡包内正常查看、复习、删除

### 截屏或者录屏演示 Screenshot or screen recording presentation

![闪卡块剪切测试](https://user-images.githubusercontent.com/74853597/210322535-613ba1d0-758f-4966-b48d-f7678c4a2fda.gif)

### 版本环境 Version environment

```markdown
- Version: 2.6.1
- Operating System: win 10
- Browser (if used):
```

### 日志文件 Log file

该问题复现无需日志

**Comment by 88250** [comment]
粘贴的时候 ID 会变，这会导致闪卡失效。

不同步删除闪卡是因为可以有其他方式回滚（比如数据历史）。

**Comment by zxhd863943427** [comment]
> 粘贴的时候 ID 会变，这会导致闪卡失效。

对，那么合理的方式不是应该在闪卡被剪切失效后直接删除闪卡属性吗？

> 不同步删除闪卡是因为可以有其他方式回滚（比如数据历史）。

目前数据历史回滚时不能回滚卡包吗？所以只能保留卡包内失效的闪卡，然后在等待回滚？

**Comment by 88250** [comment]
> 对，那么合理的方式不是应该在闪卡被剪切失效后直接删除闪卡属性吗？

属性还是得保留，因为可以撤销删除。

> 目前数据历史回滚时不能回滚卡包吗？所以只能保留卡包内失效的闪卡，然后在等待回滚？

快照可以回滚，文件历史里只可以回滚文档，如果用文件历史回滚的话就会和卡包不一致。

综上，权宜之计就是现在这样处理。
