### ISSUE TITLE
预览时段落开头空两格对齐

### ISSUE THREAD

**Issue by hopebird** [siyuan-note/siyuan#698]
### 描述问题 Describe the problem

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
If it is a problem of parsing and rendering, please post the original Markdown here
````````

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
我这里是正常的……

![image](https://user-images.githubusercontent.com/873584/101785305-912fc880-3b37-11eb-94f3-455f0d68b2d6.png)

**Comment by 88250** [comment]
v0.5.3 修复，谢谢。
