### ISSUE TITLE
搜索高亮超链接锚文本后预览窗口修改导致地址失效

### ISSUE THREAD

**Issue by mdzz2048** [siyuan-note/siyuan#6982]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

2.6.2 搜索高亮链接后链接无法跳转
![image](https://user-images.githubusercontent.com/86549958/210370682-0b7414d7-ae2f-487e-a835-4d590758c83d.png)
![image](https://user-images.githubusercontent.com/86549958/210370695-76610894-8edf-4aca-8468-939519fb612f.png)
默认主题下
![image](https://user-images.githubusercontent.com/86549958/210371084-0cd49bd5-0669-48ca-bb49-88fa6b7fb620.png)

### 期待的结果 Expected result

高亮后链接可以正常点击

### 版本环境 Version environment

```markdown
- Version: 2.6.2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

该问题无需日志文件

**Comment by 88250** [comment]
目前测试下来，只要不在搜索结果预览窗口中修改块的话超链接数据不会丢失链接地址，如果修改的话会丢失。
