### ISSUE TITLE
`上传资源文件到图床` 每次都全量上传刷新 CDN

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#6985]
本地不再根据 data/assets/.siyuan/assets.json 判断是否已经上传过，而是每次都全量上传覆盖，并且服务端每次都刷新 CDN，以便其他平台能够获取到最新文件。

**Comment by Achuan-2** [comment]
感觉CDN刷新没用，请问间隔是多久，目前上传了图片，编辑修改图片，再上传，浏览器打开CDN链接，还是原来的图片

不过这个好像和浏览器缓存有关系

**Comment by 88250** [comment]
上传的时候就刷新了，社区图床的缓存过期时间目前是 30 天。

和本地浏览器缓存也有关系，强制刷新看看。

**Comment by Achuan-2** [comment]
目前文章图片多的时候，插入新图，想要上传，会把全部图片都上传，体验不是很好，对用户而言每次更新图片上传速度慢，对思源而言消耗官方流量（目前解决方式是聚焦块上传，但是图片分布在不同标题下，这个方法就不方便）

我觉得还是得有一个asset.json记录每个图片上次上传时间lastUploadTime，上传时检测图片是否已上传，已上传的图片需要检测文件更新时间是否晚于lastUploadTime，晚于才需要重新上传，做到增量上传。

**Comment by TCOTC** [comment]
如果要做增量上传，需要判断文件是否有改变

**Comment by 88250** [comment]
之前应该就是因为容易误判所以改成全量的

**Comment by Achuan-2** [comment]
> 之前应该就是因为容易误判所以改成全量的

1. 之前只是记录有没有上传过，上传了就不再上传，没有判断文件是否改变，导致更改了文件不方便再上传
2. 其实要判断文件是否改变，记录这个文件的上次上传时间，根据比较上次上传时间和文件更新时间，就可以判断是否要更新文件

**Comment by 88250** [comment]
文件更新时间可能不稳定会变的，另外这个记录的文件也可能因为同步等原因被改变，导致和实际是否修改了资源不一致。

慢点就慢点吧，至少稳定，另外这个也不是高频功能，慢点问题不大，只要稳定就好。
