### ISSUE TITLE
能否增加分享笔记的功能

### ISSUE THREAD

**Issue by zhoujun0601** [siyuan-note/siyuan#6988]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

希望能生成专门的笔记分享直链

### 描述可能的最优解决方案 Describe the optimal solution

希望能生成专门的笔记分享直链

### 描述候选的解决方案 Describe the candidate solution

希望能生成专门的笔记分享直链

### 其他信息 Other information

希望能生成专门的笔记分享直链

**Comment by terwer** [comment]
你说的是局域网共享，还是思源整一个云端共享？如果是局域网，目前已经有了。如果是云端，那涉及审核问题。而且有了发布到链滴，这个需求也成了伪需求吧。

**Comment by 88250** [comment]
单篇文档分享请关注 https://github.com/siyuan-note/siyuan/issues/2004

整个工作空间在线分享目前只能通过内核伺服（比如通过 Docker）达成。

**Comment by hausen1012** [comment]
> 你说的笔记共享是局域网共享，还是思源整一个云端共享？如果是局域网，目前已经有了。如果是云端，那涉及审核问题。而且有了发布到链滴，这个需求也成了伪需求吧。

自建的发布的话，是否审核也是和个人有关吧？

**Comment by terwer** [comment]
> > 你说的笔记共享是局域网共享，还是思源整一个云端共享？如果是局域网，目前已经有了。如果是云端，那涉及审核问题。而且有了发布到链滴，这个需求也成了伪需求吧。
> 
> 自建的发布的话，是否审核也是和个人有关吧？

不知不觉这个帖子过去那么久了，全托管分享，目前我做了收费版本 https://github.com/terwerinc/siyuan-plugin-share-pro

**Comment by hausen1012** [comment]
> > > 你说的笔记共享是局域网共享，还是思源整一个云端共享？如果是局域网，目前已经有了。如果是云端，那涉及审核问题。而且有了发布到链滴，这个需求也成了伪需求吧。
> > 
> > 
> > 自建的发布的话，是否审核也是和个人有关吧？
> 
> 不知不觉这个帖子过去那么久了，全托管分享，目前我做了收费版本 https://github.com/terwerinc/siyuan-plugin-share-pro
> 
> 分享之后的链接类似：https://siyuannote.site/x/20240903115146-wdyz9ue

大佬厉害，免费的是不是也是你做的？
