### ISSUE TITLE
移动端添加只读模式

### ISSUE THREAD

**Issue by YorickGu** [siyuan-note/siyuan#6990]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

对于移动端，我可能只是阅读，对于书写更多的是放于PC端去进行操作，然后有时候就会在移动端有误触的情况。

### 描述可能的最优解决方案 Describe the optimal solution

移动端添加一个只读模式的选项，同时可以保持这个模式

### 描述候选的解决方案 Describe the candidate solution

移动端添加只读模式

**Comment by 88250** [comment]
移动端已经有只读模式了，顶部有个铅笔/眼睛图标可以点了看一下。
