### ISSUE TITLE
文档按名称排序功能

### ISSUE THREAD

**Issue by qing-root** [siyuan-note/siyuan#6991]
可否增加一个功能，同级文档按字母、数字排序呢，自动排序
![image](https://user-images.githubusercontent.com/30001685/210723362-cba3c57c-8b83-4fab-ab43-83c8447fe163.png)

**Comment by 88250** [comment]
排序规则仅支持全局。

**Comment by qing-root** [comment]
> 

全局文档排序是已有功能吗 我搜了笔记和社区都没搜到这个功能。。

**Comment by 88250** [comment]
文档树面板 `...` 菜单中

**Comment by qing-root** [comment]
> 

谢谢 好使好使
