### ISSUE TITLE
更改只读模式和编辑模式切换时的文字提示

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#6993]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

经常鼠标准备点击只读或编辑模式切换的时候，提示的文字和图标存在相反的意思。点击的是编辑的图标，预期的是编辑模式，文字提示切换为只读模式，实际结果和预期结果不一致，比较不舒服。
![image](https://user-images.githubusercontent.com/31495943/210776011-fcec0819-363e-4d57-abe6-d382cb98cb97.png)

### 描述可能的最优解决方案 Describe the optimal solution

文字提示改为只读模式开/关 或 编辑模式开/关，图标也可以改为有开关模式的单一图标，也可以先不改。

**Comment by 88250** [comment]
没有相反吧，铅笔图标表示当前处于编辑模式。

**Comment by XinLi0111** [comment]
> 没有相反吧，铅笔图标表示当前处于编辑模式。

那考虑提示文字去掉 “使用” 两个字？铅笔图标表示编辑模式很合适，但是此时的提示文字是 “使用只读模式”，相反的是处于编辑模式的情况下提示文字却是“使用只读模式”，这个使用是当前使用，还是按下后使用？而且提示文字重点应该是“只读模式”，相反的是文字重点和图标含义。直接提示当前模式是编辑模式或只读模式，或统一更改为“切换只读/编辑模式”。

一个小小的建议，平时使用模式切换比较多。对于现在的提示文字，感觉没有提示文字的干扰反而能编辑图标的含义更清晰。

**Comment by Vanessa219** [comment]
提示是需要移动到图标上才显示，是告诉用户点击该按钮的作用。

**Comment by XinLi0111** [comment]
> 提示是需要移动到图标上才显示，是告诉用户点击该按钮的作用。

感谢解答！
