### ISSUE TITLE
为什么一个文档中的同一句话，搜索结果却显示了5遍？

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#6994]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如图，我确定自己没有重复的文档
这句话没有在文档中重复
但是搜索结果却显示了5条结果指向这一个块

### 期待的结果 Expected result

一个块，有且只有一种搜索结果

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/37429029/210783107-d78e9540-a647-4c69-85ba-17d269c5fa3b.png)

### 版本环境 Version environment

```markdown
- Version: 2.6.2
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[Uploading system-log.zip…]()

**Comment by 88250** [comment]
可以在设置 - 搜索中关闭不需要的类型。

**Comment by AugustTuan** [comment]
> 可以在设置 - 搜索中关闭不需要的类型。
这两对，都是列表和列表项，是由于什么原因重复呢

![image](https://user-images.githubusercontent.com/37429029/210787171-6c22a6a0-1446-49da-82df-758e94426540.png)

**Comment by AugustTuan** [comment]
> 可以在设置 - 搜索中关闭不需要的类型。

搜索结果会把列表和列表项都展示一遍吗？
列表、列表项、段落块，这几个常用搜索类型，我没法关掉啊

**Comment by 88250** [comment]
也可以使用搜索界面的类型过滤。都需要用的话就是都展示。

**Comment by AugustTuan** [comment]
> 也可以使用搜索界面的类型过滤。都需要用的话就是都展示。

谢谢，我自己再研究研究
