### ISSUE TITLE
在线图片无法查看

### ISSUE THREAD

**Issue by tunanx** [siyuan-note/siyuan#6995]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

插入在线图片无法显示
例如插入图片 https://github.com/JERRY-Z-J-R/I-love-you-3-thousand/blob/master/%E6%88%91%E7%88%B1%E4%BD%A0%EF%BC%8C%E4%B8%8D%E6%AD%A2%E4%B8%89%E5%8D%83%E9%81%8D/HTML%20CSS/01%E3%80%90HTML%E5%9F%BA%E7%A1%80%E3%80%91/mark-img/image-20220115163652252.png
或这个链接https://s1.ax1x.com/2023/01/05/pSAnkCR.png
无法显示，思源显示如下图
![屏幕截图_20230105_205248](https://user-images.githubusercontent.com/56903981/210784628-bce6a764-3b19-4b92-8053-b2b70ed642b9.png)
---
但是插入这张豆瓣图片可以正常显示
https://img1.doubanio.com/view/subject/s/public/s34349400.jpg
思源显示如下图：
![屏幕截图_20230105_205459](https://user-images.githubusercontent.com/56903981/210784916-bf0c2922-9e1f-4a71-82a3-ab2a4eb8aabc.png)

### 期待的结果 Expected result

正常显示图片

### 版本环境 Version environment

```markdown
- Version: 2.6.2
- Operating System: windows11 22621.963
- Browser (if used):
```

### 日志文件 Log file

I 2023/01/05 21:00:57 conf.go:392: exiting kernel [force=false, execInstallPkg=0]
I 2023/01/05 21:00:57 sync.go:158: sync before exit
I 2023/01/05 21:00:58 repository.go:922: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=3.4 kB] in [1.80s]
I 2023/01/05 21:00:58 database.go:1025: closed database
I 2023/01/05 21:00:58 conf.go:722: cleared workspace temp
I 2023/01/05 21:01:08 working.go:116: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/01/05 21:01:08 runtime.go:45: kernel is booting:
    * ver [2.6.2]
    * arch [amd64]
    * pid [5060]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_2.6.2.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Orange\document\siyuannote\SiYuan]
I 2023/01/05 21:01:08 conf.go:227: using Microsoft Store edition
I 2023/01/05 21:01:08 conf.go:314: user has disabled [Google Analytics]
I 2023/01/05 21:01:08 runtime.go:90: use network proxy [system]
I 2023/01/05 21:01:08 port.go:65: check running kernel elapsed [0ms]
I 2023/01/05 21:01:08 serve.go:115: kernel [pid=5060] is booting [http://127.0.0.1:6806]
I 2023/01/05 21:01:08 working.go:369: built-in pandoc [ver=2.19.2, bin=C:\Orange\document\siyuannote\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/01/05 21:01:08 sync.go:81: sync before boot
I 2023/01/05 21:01:10 repository.go:821: boot get sync cloud files elapsed [2.32s]
I 2023/01/05 21:01:10 conf.go:612: database size [8.5 MB], tree/block count [14/922]
I 2023/01/05 21:01:10 working.go:154: kernel booted
I 2023/01/05 21:01:48 conf.go:392: exiting kernel [force=false, execInstallPkg=0]
I 2023/01/05 21:01:48 sync.go:158: sync before exit
I 2023/01/05 21:01:54 repository.go:922: synced data repo [provider=2, ufc=2, dfc=0, ucc=1, dcc=0, ub=40 kB, db=3.4 kB] in [6.02s]
I 2023/01/05 21:01:54 database.go:1025: closed database
I 2023/01/05 21:01:54 conf.go:722: cleared workspace temp

**Comment by 88250** [comment]
GitHub 上图片的地址应该是这个格式：

https://raw.githubusercontent.com/JERRY-Z-J-R/I-love-you-3-thousand/master/%E6%88%91%E7%88%B1%E4%BD%A0%EF%BC%8C%E4%B8%8D%E6%AD%A2%E4%B8%89%E5%8D%83%E9%81%8D/HTML%20CSS/01%E3%80%90HTML%E5%9F%BA%E7%A1%80%E3%80%91/mark-img/image-20220115163652252.png

**Comment by tunanx** [comment]
> GitHub 上图片的地址应该是这个格式：
> 
> https://raw.githubusercontent.com/JERRY-Z-J-R/I-love-you-3-thousand/master/%E6%88%91%E7%88%B1%E4%BD%A0%EF%BC%8C%E4%B8%8D%E6%AD%A2%E4%B8%89%E5%8D%83%E9%81%8D/HTML%20CSS/01%E3%80%90HTML%E5%9F%BA%E7%A1%80%E3%80%91/mark-img/image-20220115163652252.png

这个链接一样无法正常显示 0.0

**Comment by 88250** [comment]
那估计是你的网络问题，试试科学上网。
