### ISSUE TITLE
笔记本默认文档功能

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/siyuan#6998]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

1. 现在的“日记”功能，可以创建或者打开每天的笔记，这个很赞。
2. 但现在我有一个需求，就是针对不同的笔记本，我可以分别设置一个默认的打开文档，也能向“日记”一样快速打开。

这个目的主要是有些笔记中，比如“任务日志”笔记本，我每天要建立一个“日记”去记录当天的工作，但是我又需要有一个地方记录“临时”、住着需要“汇总”的事情，现在是利用笔记本旁的“+”号，但是这个会每次产生一个新的，我会在每天的工作结束后，把这些笔记的内容，在归档到一个笔记里。

但是这样很麻烦。目前折衷的方案是建立两个“笔记本”一个的日记的创建规则写死（即不用.action{now “2006/01”}） 这类方式，但是，还是希望可以有“默认笔记”的打开方式。

### 描述可能的最优解决方案 Describe the optimal solution

方案1: 
1. 在“日记”旁边，添加一个”速记“（叫什么名字都行(*^_^*)）的按钮，功能和日记类似。
2. 在每个文档树的右键菜单中，增加 ”设置为默认文档“ 功能，设置好以后，就可以在”速记“按钮打开。
方案2：
1. 在下面的按钮旁，加一个”速记“，也就是打开默认文档的按钮。
2. 设置默认文档的方式，和方案1一样。
![image](https://user-images.githubusercontent.com/53116704/210913835-da7b3c40-dee9-4f96-a9d4-b0b4d753c8a4.png)

**Comment by 88250** [comment]
这个暂时不考虑了，如果有需要可通过 API 自行实现。
