### ISSUE TITLE
希望Docker版的思源笔记中的编辑器字体能够自定义

### ISSUE THREAD

**Issue by lfk2458** [siyuan-note/siyuan#6999]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

希望Docker版的思源笔记中的编辑器字体不能够自定义，只能显示默认字体

### 描述可能的最优解决方案 Describe the optimal solution

编辑器的字体能否读取服务器上某一指定的目录

**Comment by 88250** [comment]
这个暂时不考虑支持了，欢迎 PR 贡献代码，谢谢。

**Comment by lfk2458** [comment]
好的
