### ISSUE TITLE
新建文档块自顶向下用法

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#70]
![image](https://user-images.githubusercontent.com/873584/92996666-cda35680-f53f-11ea-90c3-0c2390bc088d.png)

---

![IT5_Z}_HPZ~QSYQ)9_2$% M](https://user-images.githubusercontent.com/873584/94938556-8f2c0680-0503-11eb-9c61-037d418bddd0.png)

![7)B4T(LW (N UC2XGZ{EG7N](https://user-images.githubusercontent.com/873584/94996708-d1734780-05d8-11eb-9a5c-ad203f75fc4f.png)

---

![image](https://user-images.githubusercontent.com/873584/95429064-6fba3100-097c-11eb-9c83-d8707485e8e0.png)

---

![N2C)AR797BH{NIZJ6IPOJQ8](https://user-images.githubusercontent.com/873584/95826048-56dac280-0d64-11eb-8280-83ef57e27931.png)

![DLL5T12CA3SLP}`0~(WX35N](https://user-images.githubusercontent.com/873584/95826016-4a566a00-0d64-11eb-854e-fa97716a23e6.png)

**Comment by lss6378** [comment]
## 划词关联已有文档
1. 鼠标选中文字“LYT System”(LYT System.md**已存在**)
2. 输入"[[",自动生成链接，关联到已有文档"LYT System.md"

![划词关联已有文档](https://user-images.githubusercontent.com/15924513/96329699-22c41200-1082-11eb-8172-6cd4ba7836dc.gif)


## 划词新建空连接，点击空连接新建页面
1. 鼠标选中文字“每日主题”(“每日主题”这个页面**不存在**)
2. 鼠标点击菜单"[[",自动生成**空链接**
3. 点击"[[每日主题]]",自动打开并跳转到新页面

![划词新建文档](https://user-images.githubusercontent.com/15924513/96329810-e1803200-1082-11eb-86b2-1e3973d31aba.gif)

**Comment by lss6378** [comment]
## 新建与取消引用

![新建与取消连接](https://user-images.githubusercontent.com/15924513/96330114-46d52280-1085-11eb-989a-1d82c478da50.gif)

**Comment by 88250** [comment]
@lss6378 后面这几个提议会分步实现，非常感谢！
