### ISSUE TITLE
取内核服务端口失败 Failed to get kernel serve port

### ISSUE THREAD

**Issue by gorexlv** [siyuan-note/siyuan#7001]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

<img width="924" alt="image" src="https://user-images.githubusercontent.com/331414/210934526-4a443da7-75e5-4ef1-a271-e6dbc46ba0de.png">

目前使用的是v2.6.0, apple m1版本的。
被这个问题困扰很久了，每次都需要重启电脑，才能正常使用。
但是使用过程中如果关闭了，很大概率还是报上面这个错误。

查看了log日志，报：
E 2023/01/06 13:06:44 working.go:456: lock workspace [/Users/xxxx/Documents/SiYuan] failed
E 2023/01/06 13:08:55 working.go:456: lock workspace [/Users/xxxx/Documents/SiYuan] failed

判断是关闭siyuan的时候，siyuan假死。即桌面和调度器视图都看不到思源了，但进程还在。
查看了活动监视器，确实siyuan主进程、helper进程都还在。

这个挺影响使用体验的，提出来看看开发团队能否修一下。

谢谢

### 期待的结果 Expected result

正常使用

### 版本环境 Version environment

```markdown
- Version: 
2.6.0
- Operating System: 
Apple M1
- Browser (if used):
```

### 日志文件 Log file

I 2023/01/06 10:21:57 box.go:80: auto stat [trees=399, blocks=17565, dataSize=217 MB, assetsSize=164 MB]
I 2023/01/06 10:21:57 disk.go:33: disk usage [total=995 GB, used=389 GB, free=606 GB]
I 2023/01/06 10:36:28 conf.go:392: exiting kernel [force=false, execInstallPkg=0]
I 2023/01/06 10:36:28 database.go:991: closed database
I 2023/01/06 10:36:28 conf.go:721: cleared workspace temp
I 2023/01/06 10:36:28 conf.go:440: exited kernel
I 2023/01/06 13:04:45 working.go:116:
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/01/06 13:04:45 runtime.go:45: kernel is booting:
    * ver [2.6.0]
    * arch [arm64]
    * pid [35609]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/xxxx/Documents/SiYuan]
I 2023/01/06 13:04:45 runtime.go:90: use network proxy [system]
I 2023/01/06 13:04:45 port.go:65: check running kernel elapsed [0ms]
I 2023/01/06 13:04:45 serve.go:115: kernel [pid=35609] is booting [http://127.0.0.1:6806]
I 2023/01/06 13:04:45 working.go:369: built-in pandoc [ver=2.19.2, bin=/Users/rexlv/Documents/SiYuan/temp/pandoc/bin/pandoc]
I 2023/01/06 13:04:45 conf.go:611: database size [61 MB], tree/block count [399/17565]
I 2023/01/06 13:04:45 working.go:154: kernel booted
E 2023/01/06 13:04:56 working.go:456: lock workspace [/Users/xxxx/Documents/SiYuan] failed
I 2023/01/06 13:05:45 box.go:80: auto stat [trees=399, blocks=17565, dataSize=217 MB, assetsSize=164 MB]
I 2023/01/06 13:05:45 disk.go:33: disk usage [total=995 GB, used=388 GB, free=606 GB]
E 2023/01/06 13:06:44 working.go:456: lock workspace [/Users/xxxx/Documents/SiYuan] failed
E 2023/01/06 13:08:55 working.go:456: lock workspace [/Users/xxxx/Documents/SiYuan] failed

**Comment by 88250** [comment]
退出思源的时候是点关闭退出的吗？

**Comment by 88250** [comment]
如果 SiYuan-Kernel 内核进程不正常退出的话可能会出现这个问题。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by grassvalley** [comment]
遇到同样问题，应该不存在“SiYuan-Kernel 内核进程不正常退出”的情况，因为开机后第一次启动就有这问题。
操作系统：深度20.9
思源笔记版本：appimage 2.8.9
另：appimage 2.8.6 是没有问题的

**Comment by 88250** [comment]
@grassvalley https://github.com/siyuan-note/siyuan/issues/8334

**Comment by Hang-shao** [comment]
看了半天，没有解决办法么？

**Comment by 88250** [comment]
> 看了半天，没有解决办法么？

手动结束 SiYuan-Kernel 进程后重启，如果还是不行，检查是不是防火墙/杀毒软件阻断。
