### ISSUE TITLE
重建索引出现多个后台图标

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7004]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

每重建索引一次，任务栏就会多一个后台图标，可以无限叠加

### 期待的结果 Expected result

后台图标始终只有一个

### 版本环境 Version environment

```markdown
- Version: v2.6.2 dev-v202301062325
- Operating System: Windows 11
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
确实存在这个问题，下个 dev 版修复，感谢反馈。
