### ISSUE TITLE
工作空间的定义和建议

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#7005]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

贴贴 我自己关于工作空间的一个看法：关于前段时间提的需要开启多个siyuan软件的workspace才能分区“工作”，“生活”等等，这些操作些许脱离了思源的新型笔记的本质。这样的区分无非增加了笔记整理的难度，更趋向于用“大纲”的思维做笔记

思源通过引用块或者嵌入块完全可以实现笔记的分类管理，重复利用。至于担心因为查找笔记的时候会有不同的的笔记内容混杂在一起，如果你已经建立了几个不同的笔记本，那么可以在使用对应的笔记本的时候关闭其它的即可，就不会有其它的笔记内容混杂在搜索里面。

再者，如果你的笔记的命名比较规范，搜索的结果几乎就是你需要的。

### 描述可能的最优解决方案 Describe the optimal solution

下面我想讨论以下我概念中的工作空间：

比如你现在正在学习Nginx的基础语法，并且使用思源做笔记，打开了很多的关于Nginx的笔记页面。一段时间后，你打算不学Nginx了，但是Nginx的内容并没有全部写完，打算下次继续。这里就有个需求，能够保存好我现在打开的所有页面的配置，比如命名为Nginx学习工作空间。

接着打开JavaScript的笔记学习，此时你肯定不想看到页面中还有很多的nginx的页面，但是你又不想关闭他们，而是暂时关闭并保存到一个配置文件，下次能够直接打开。

这个和VScode的工作空间的概念也比较符合
不知道这个功能是不是符合工作空间的最合适的想法？

**Comment by GH-W94** [comment]
支持了同时多开工作空间后，不一定要用于笔记类别或领域的分类，还可以将可以公开的笔记放在一个工作空间，不希望公开的私人笔记放在另一个工作空间，然后使用第三方加密软件进行加密，并且因为支持同时多开工作空间了，省去了来回切换工作空间的麻烦。

**Comment by tangjiahao2001** [comment]
贴贴我的想法

首先，能够支持开多个软件的“工作空间”和能够保存保存当前编辑的文档配置的“工作空间”并没有矛盾，开多软件工作空间同样也可以支持只保存当前打开的文档的“工作空间”。

我的主要想法在于开不同的workspace来设计的“工作空间”相比于直接保存当前打开的所有文档作为一个“工作空间”，可能前者的应用场景没有后者多。两者都可以有，但是我感觉要以保存当前的打开文档作为一个配置“工作空间"为主

**Comment by 88250** [comment]
工作空间是物理隔离的，不同工作空间可以拥有不同的配置和账号，也可以分开进行数据同步，这是工作空间的设计用意。
