### ISSUE TITLE
在顶栏添加切换工作空间的按钮和保存工作空间的路径

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7006]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

非常高兴看到思源支持了同时多开工作空间，这样极大的提高了记录笔记效率，方便了私人笔记和工作笔记的同时记录，感谢开发大佬的辛苦付出。
但还有个建议可以使多开工作空间获得更好的体验感，希望大佬能考虑。

### 描述可能的最优解决方案 Describe the optimal solution

1. 在顶栏位置添加一个切换工作空间的按钮，这样能更加方便快速切换不同的工作空间。
![image](https://user-images.githubusercontent.com/117154557/211135042-1ab928df-ad82-4b90-8aca-361a7d794924.png)

2. 能保存之前打开过的工作空间的路径。我有一个工作空间是放在 U 盘里的，但当我在打开思源前没有插上 U 盘的话，U 盘的这个工作空间的路径就会被删除（在切换工作空间的设置处），当下次插上 U 盘使用里面的工作空间时，就需要再次查找路径，非常不便。
3. 在顶栏中间添加工作空间名，即“工作空间名-文档名”。
![image](https://user-images.githubusercontent.com/117154557/211135284-7ae34690-c635-4337-a786-f1329da39e95.png)

**Comment by UFDXD** [comment]
两个办法：1.托盘显示工作空间，从托盘打开其他工作空间。2.软件向桌面发送该空间快捷方式，之后可以从快捷方式直接打开工作空间。

**Comment by GH-W94** [comment]
> 两个办法：1.托盘显示工作空间，从托盘打开其他工作空间。2.软件向桌面发送该空间快捷方式，之后可以从快捷方式直接打开工作空间。

这两个办法都不如在顶栏添加个切换按钮来的直接。比如你正在某个空间的页面记笔记的，寻思着要切换其他空间。

若是顶栏有切换按钮，直接鼠标移过去切换即可。

若是从托盘打开其他工作空间，你需要将鼠标移到托盘，然后点击倒三角打开托盘，接着需要鼠标一个一个查看哪个思源图标是你想要打开的空间，非常麻烦。

若是从快捷方式打开，你需要先返回桌面，然后在桌面的一大堆图标中寻找你想要打开的工作空间，这也是非常麻烦的。

**Comment by 88250** [comment]
顶栏切换暂时不考虑，因为可能大部分用户只会用到一个工作空间。

有多个工作空间需要经常一次性打开的话建议用快捷方式指定参数，比如 `--workspace F:\SiYuan\`

**Comment by GH-W94** [comment]
> 顶栏切换暂时不考虑，因为可能大部分用户只会用到一个工作空间。
> 
> 有多个工作空间需要经常一次性打开的话建议用快捷方式指定参数，比如 `--workspace F:\SiYuan\`

“顶栏切换”还是很有必要的，多空间同时打开这个功能是非常好用的，既然做出来了，为什么又要藏着掖着呢？

当时我下载了2.6.3 dev3 ，安装后打开，迫不急待的想去使用多空间同时打开功能，结果我懵了，找了半天没找到入口，最后还是求助别人还知道如何操作的。

大部分用户只会用到一个工作空间，那是很可能他们连思源能多开工作空间这个功能都不知道。
