### ISSUE TITLE
不同工作空间的笔记之间建立引用及超链接

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7007]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

虽然将不同领域的笔记或不同保密等级的笔记分放不同的工作空间，但有时这些不同空间的笔记之间还是有联系。

### 描述可能的最优解决方案 Describe the optimal solution

希望能支持不同工作空间的笔记之间建立双链引用。
若是双链引用难以实现，希望能支持单向的超链接。

**Comment by Temacc0531** [comment]
为啥不在笔记本维度进行划分呢

**Comment by tangjiahao2001** [comment]
如果是以workspace设计的“工作空间”是不便于产生引用关系的，因为workspace是指定了你的电脑上具体的位置，而思源内部的引用关系只能够引用到同一个workspace下面，也就是以workspace设计的“工作空间”。

**Comment by GH-W94** [comment]
> 如果是以workspace设计的“工作空间”是不便于产生引用关系的，因为workspace是指定了你的电脑上具体的位置，而思源内部的引用关系只能够引用到同一个workspace下面，也就是以workspace设计的“工作空间”。

若是这样的话，那就像Word里面的那种单向的超链接能否实现呢？

**Comment by GH-W94** [comment]
> 为啥不在笔记本维度进行划分呢

笔记本维度进行划分的话，有些场景不满足，比如一些私密的笔记可以单独放在一独立的工作空间，然后使用第三方加密软件进行加密，若是在笔记本进行划分的话，就需要把非私密的笔记也加密了。

**Comment by UFDXD** [comment]
这个不要吧

**Comment by terwer** [comment]
不建议，最好是不同空间之间默认完全隔离。

本来就是为了分开，你非要加上联系，违背了这个需求的初衷吧？

**Comment by GH-W94** [comment]
> 不建议，最好是不同空间之间默认完全隔离。
> 
> 本来就是为了分开，你非要加上联系，违背了这个需求的初衷吧？

笔记内容不可能是完全隔离的，相互之间在某些情况下总是会产生联系，需要个链接去提醒。

**Comment by zxhd863943427** [comment]
> > 如果是以workspace设计的“工作空间”是不便于产生引用关系的，因为workspace是指定了你的电脑上具体的位置，而思源内部的引用关系只能够引用到同一个workspace下面，也就是以workspace设计的“工作空间”。
> 
> 若是这样的话，那就像Word里面的那种单向的超链接能否实现呢？

单向超链接使用复制里的复制块超链接应该就能实现了

**Comment by 88250** [comment]
工作空间的目的之一就是为了物理隔离，所以不会提供多工作空间存在关联数据的特性，谢谢。

**Comment by GH-W94** [comment]
> 工作空间的目的之一就是为了物理隔离，所以不会提供多工作空间存在关联数据的特性，谢谢。

但很多时候，笔记并非能完全隔离，完全隔离只是理想状态，还是希望能支持单向的“块超链接”，而且因为是单向，所以也没有违背各个工作空间相互隔离的原则。

![image](https://user-images.githubusercontent.com/117154557/211154669-74d413fa-51a7-4b2f-a74c-d877057d92bc.png)
