### ISSUE TITLE
某个文档页面有音频或视频在播放时，在文档名旁添加个小喇叭以便提醒

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7009]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当文档开的多了后，某个文档页面有音频或视频在播放时，非常不好定位是那个文档在播放，需要一个一个点开查看。

### 描述可能的最优解决方案 Describe the optimal solution

当某个文档的页面有音频或视频在播放时，在文档名旁添加个小喇叭以便提醒是这个文档页面在播放。
![image](https://user-images.githubusercontent.com/117154557/211141063-6a0b9697-83b3-4435-96fc-5f2e943c32e9.png)

**Comment by UFDXD** [comment]
又不是浏览器，不需要。而且加一个图标又占用文本位，花里胡哨。

**Comment by 88250** [comment]
这个暂时不考虑了，感谢提议。
