### ISSUE TITLE
多开空间后，打开某个空间出现错误时，关闭弹窗后其他的空间也被一并关闭了

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7010]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当打开某个空间时，出现如下弹窗时，关闭这个弹窗时，会把其他已打开的工作空间也一并关闭。
![image](https://user-images.githubusercontent.com/117154557/211142398-d5495de0-4f2f-4e47-b5ec-52f2873968ee.png)

### 描述可能的最优解决方案 Describe the optimal solution

不要关闭其他已打开的工作空间。

**Comment by 88250** [comment]
目前是这样的，一旦某个工作空间出现内核无法恢复的报错就会关闭主进程，避免引起其他问题。
