### ISSUE TITLE
请输入问题报告标题 Please enter the title of the bug report

### ISSUE THREAD

**Issue by liyang-good** [siyuan-note/siyuan#7012]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/71406269/211155251-fc9364c5-278d-4746-9e4a-ea67bff1a2cf.png)

root 怎么去掉

### 期待的结果 Expected result

1

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
这个去不掉哦。

**Comment by liyang-good** [comment]
啊呜。

从 Windows 版邮件发送

发件人: D
发送时间: 2023年1月7日 22:21
收件人: siyuan-note/siyuan
抄送: kaoya; Author
主题: Re: [siyuan-note/siyuan] 请输入问题报告标题 Please enter the title of the bug report (Issue #7012)

这个去不掉哦。
