### ISSUE TITLE
1.手机端APP需要能支持右滑出笔记列表，2.docker服务器端web手机端能支持生成应用

### ISSUE THREAD

**Issue by loveu5522** [siyuan-note/siyuan#7013]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

手机端

### 描述可能的最优解决方案 Describe the optimal solution

无

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
1. 暂时不考虑改进了，后续优化移动端时再考虑
2. 这个应该是需要 HTTPS 才行
