### ISSUE TITLE
是否可以实现编辑文字时按快捷键选中下一个相同的内容，类似于 VSCode 中 Ctrl + D 的效果

### ISSUE THREAD

**Issue by NeverKnowsTomorrow** [siyuan-note/siyuan#7015]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

想给文章中某个关键词添加行内代码样式时，如果该关键词出现了多次，就需要挨个选中然后添加样式，希望可以像 VSCode 中按 `Ctrl + D` 选中下一个相同的内容，然后统一添加样式

### 描述可能的最优解决方案 Describe the optimal solution

实现 VSCode 中 `Ctrl + D` 的效果就可以

**Comment by 88250** [comment]
抱歉，思源的编辑器无法支持多插入符。
