### ISSUE TITLE
桌面端工作空间切换从 设置 - 关于 中移动到顶栏

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7017]
桌面端 设置 - 关于 中不再支持切换工作空间，该功能入口移动到主界面顶栏。

**Comment by mozhux** [comment]
我个人认为切换空间这样改有必要，但把日记和闪卡这些常用功能加到里面去，可能就不太必要。现在思源很多功能都在菜单里，并不是所有人都会去记那些快捷键，这样改动就增加了使用成本。
我个人建议不如趁此机会，改动一下主题结构。借鉴参考目前市面大多数笔记的三段式结构，将顶栏的部分按钮放到侧边栏。
![image](https://user-images.githubusercontent.com/46953371/211227824-8972ffe2-149c-4113-8e19-30caec6a4d3a.png)

**Comment by Temacc0531** [comment]
> 我个人认为切换空间这样改有必要，但把日记和闪卡这些常用功能加到里面去，可能就不太必要。现在思源很多功能都在菜单里，并不是所有人都会去记那些快捷键，这样改动就增加了使用成本。 我个人建议不如趁此机会，改动一下主题结构。借鉴参考目前市面大多数笔记的三段式结构，将顶栏的部分按钮放到侧边栏。

我倒是觉得顶栏越干净越好，最好都塞到二级菜单里面去😂

**Comment by Temacc0531** [comment]
![1673247821732](https://user-images.githubusercontent.com/101307399/211255778-b13ccc97-d80e-43bf-a99b-3d791004b661.png)

反馈几个问题
1. 快捷键指示可以把第一、第三行左移一些和第二行的对齐
2. 工作空间路径过长时菜单会被撑宽显示有问题，可以考虑固定菜单宽度，路径仅显示开头结束，中间省略
3. 工作空间名称过长时顶栏也会被占用过宽，可以考虑设置最大宽度，可能会影响 #6938 
4. `打开`现在是在工作空间的分割线上面，用户可能不太能理解是打开工作空间的意思
5. `已打开的工作目录`可以不单独显示在菜单里面，而是鼠标移至顶栏的工作空间时显示完整路径
菜单可以考虑改成如下结构
>（分割线）
>打开工作空间
>工作空间目录
>D:\test

**Comment by 88250** [comment]
我觉得默认还是不要显示路径好一些，悬浮显示路径。

**Comment by 88250** [comment]
> 5. 菜单中可以不单独显示已打开的工作目录，而是鼠标移至顶栏的工作空间时显示完整路径

@Temacc0531 这个是为了切换工作空间用的。

**Comment by Vanessa219** [comment]
已调整

**Comment by Temacc0531** [comment]
> 我觉得默认还是不要显示路径好一些，悬浮显示路径。

我没太理解这句话的意思

> 这个是为了在打开的工作空间之间切换用的。

这个是有什么特殊用法吗，因为我如果同时开了两个不同工作空间需要切换，那我可以直接通过系统切换不同窗口来切换，这样好像还比点击右上角菜单来的便捷一些😂

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/211265225-1a74c03b-72dd-40fe-8567-43be96841c41.png)

**Comment by 88250** [comment]
系统切换的话窗口多了不好找的。

**Comment by 88250** [comment]
托盘这里切换也行 

![image](https://user-images.githubusercontent.com/873584/211265453-ac1331a3-076a-4de9-8dd0-17999be2c0df.png)

**Comment by Temacc0531** [comment]
其实我说的是这个系统缩略窗口来切换😅
![image](https://user-images.githubusercontent.com/101307399/211266709-2fbc8eb1-9e08-4f9e-b8f3-f632e5fcaa85.png)

只是觉得菜单里面东西稍微有点多，这个不改也问题不大

**Comment by 88250** [comment]
后面会支持多窗口，所以靠系统窗口切换估计不好用。

**Comment by Temacc0531** [comment]
嗯嗯，先这样用一段时间看看
