### ISSUE TITLE
Nation daily tracker, to do's features

### ISSUE THREAD

**Issue by Cyber-Syntax** [siyuan-note/siyuan#7019]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Siyuan can be our other brain for projects, notes, and to-do lists. I think it's not enough to use checklist.

### 描述可能的最优解决方案 Describe the optimal solution

I think the Notion daily to-do list, calendar describe optimal solution. As you can see from this [video](https://www.youtube.com/watch?v=ddrMwfDzzqg), She can place his daily to-do list more in [Focalboard](https://www.focalboard.com/) style or calendar list.

### 描述候选的解决方案 Describe the candidate solution

I think this feature is very difficult to implement or even impossible to make like Notion , but basic logic can be added from other open source applications like Focal-board or any calendar app.

Also, focal-board table view feature can be really good for defining our projects from time to time.

### 其他信息 Other information

If you intend to add this feature, you will also need to add alarm and notification systems.

**Comment by 88250** [comment]
Please follow https://github.com/siyuan-note/siyuan/issues/2829, thanks.
