### ISSUE TITLE
伺服访问链接提供特定页面ID与访问权限

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#7022]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

部分需求和 #5186 重叠，主要想解决通过伺服分享给别人时，只给部分的页面或块的编辑/浏览权限，而不用给全部工作空间的访问

### 描述可能的最优解决方案 Describe the optimal solution

通过在伺服url中添加关键字ID，进行权限的过滤

如，目前默认的伺服地址为`http://note.my.site:6806/stage/build/desktop/?r=7xat7a1`，这个可以访问全部的工作空间

可以通过添加关键字，如：`http://note.my.site:6806/share/?workspace=xxxx&id=yyyy&encrypt=zzzz`

实现使用这个URL的人，只能编辑/浏览分享的部分，从而保护其他工作空间的内容，同时为了防止别人通过暴力修改连接中的xxx,yyy来访问其他的页面，生成分享连接时，自动随机生成encrypt(并记录在属性中)，只有匹配上才能访问

**Comment by 88250** [comment]
分享/协同权限相关的特性现阶段不考虑了，谢谢。
