### ISSUE TITLE
block URL跳转后自动聚焦

### ISSUE THREAD

**Issue by why8023** [siyuan-note/siyuan#7023]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如果父块处于折叠的状态, 通过URL跳转到子块, 只会显示折叠的父块

### 描述可能的最优解决方案 Describe the optimal solution

是否可以给URL增加一个Option, 实现URL跳转到内容块时, 自动聚焦, 类似siyuan://blocks/20210428224949-wtjqkhb?focus=true, 
或者默认打开就是自动聚焦

**Comment by 88250** [comment]
我测试了下，折叠父块然后通过块超链接带 focus 参数跳转子块好像没有问题。

**Comment by Vanessa219** [comment]
focus=1，不能写为 true
