### ISSUE TITLE
Daily note出现了两个2023同名文档

### ISSUE THREAD

**Issue by JokeenZhang** [siyuan-note/siyuan#7025]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/33319484/211266586-e9aac6b6-1214-4665-a8af-25cf52b3915b.png)

如上所示，出现了多个同名文档，我并没有在这里手动创建文档，都是点击软件左上方的日记按钮创建的。2023和01都应该是唯一的

我是先看到2023/01有Untitled文件，里面有多个日记文件，转移到01文件夹下，并重建索引后在定位到2023，发现有这些问题。

环境：都只在这台电脑操作，这个月也就前面几天同步到其他电脑，后面没有。用的是官方云端存储方案

### 期待的结果 Expected result

不会通过日记按钮在Daily note中创建多个同名文档

### 版本环境 Version environment

```markdown
- Version: v2.6.2
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10371608/siyuan.log)

**Comment by 88250** [comment]
这个问题确实偶尔会出现，但是目前尚未找到能够稳定重现的步骤，请继续帮忙留意，谢谢。

先关闭了，后续如果能稳定重现我们再重新打开。

**Comment by 88250** [comment]
对了，下个版本（v2.6.3）我们加入了一个新的机制来校验索引，对这个问题应该有帮助 https://github.com/siyuan-note/siyuan/issues/7016
