### ISSUE TITLE
改进 `/模板` 搜索排序

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/siyuan#7027]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

模板使用的时候，忘记模板名称时，想在一组相同的模板中，类比找到需要的。

![image](https://user-images.githubusercontent.com/53116704/211445005-5561b59e-dc11-4128-88fa-31d7f84b8b0e.png)

### 描述可能的最优解决方案 Describe the optimal solution

现在的排序会让不同 “模板集合” 中的模板交叉排序。希望先按照 "目录/模板组的名称"，再在给自的组内按照名称排序。

当前的：

![image](https://user-images.githubusercontent.com/53116704/211444387-1bd9736c-e5bc-4e08-84b1-a3a33a0e4f9e.png)

预期：
所有的  BWLabels 在一起，所有的 ZDaily 在一起

### 描述候选的解决方案 Describe the candidate solution

或者搜索的时候，可以搜 模板集合的名字。比如 搜  "ZDai" 可以出现类似下面的结果 

![image](https://user-images.githubusercontent.com/53116704/211445005-5561b59e-dc11-4128-88fa-31d7f84b8b0e.png)

**Comment by UFDXD** [comment]
支持
