### ISSUE TITLE
反链面板支持过滤关键字高亮

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7028]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

希望反链面板可以继续支持过滤关键字高亮，这样在列表中更容易找到过滤目标

反链面板改版前：
![test1](https://user-images.githubusercontent.com/101307399/211485979-a9c7214d-be58-4b32-9ab4-4005f9052619.png)

反链面板改版后：
![test2](https://user-images.githubusercontent.com/101307399/211486022-ba16d94a-7ce0-4616-aa09-6983fd2a1f44.png)

### 描述可能的最优解决方案 Describe the optimal solution

无

### 其他信息 Other information

现在的反链面板略显拥挤，可以考虑优化下界面显示😂

**Comment by Temacc0531** [comment]
> 现在的反链面板略显拥挤，可以考虑优化下界面显示😂

目前想到两个点
1. 反链面板里面字号可以缩小一些
2. 面包屑显示改小一些或者像嵌入块一样支持隐藏

**Comment by 88250** [comment]
从“反链即正文”的用法来看，缩小字号或者面包屑会有割裂感，整个编辑器的用户体验就不统一了。

**Comment by Temacc0531** [comment]
> 从“反链即正文”的用法来看，缩小字号或者面包屑会有割裂感，整个编辑器的用户体验就不统一了。

我也是“反链即正文”支持者，但我觉得这并不是说反链面板的编辑体验要和正文编辑器一模一样，这句话的意思应该是说可以通过反链面板可以把不同位置的信息组合到同一个页面里阅读，从这个角度讲，缩小字号并不会降低用户的使用体验，反而可以显示更多的正文内容，就如同图1、图2所示

> 反链的面包屑不应该支持隐藏，这个是反链上下文的核心功能。

明白面包屑是上下文的核心功能，但是像图2里面的信息关联汇总用法，面包屑一层而内容重复，完全可以隐藏，用户可以根据自己的具体用法来设置是否隐藏，现在标题格式之类信息会固定占用大量空间，没法在面积小的空间里面汇总更多的文档内容

**Comment by 88250** [comment]
编辑器的字体大小对整体体验有较大影响，这个我们暂时不考虑调整了。

面包屑如果单独只有一项的话似乎是可以自动隐藏，这个我们再考虑看看。

**Comment by Temacc0531** [comment]
上图红圈里面这个面包屑应该算有两层不隐藏，如果是同一双链都写在正文里面只有一层，那我觉得是同样可以隐藏的（或者实在要区分的话可以有一条小分割线）。

![image](https://user-images.githubusercontent.com/101307399/216989874-139872d8-cc45-4063-b164-c4a42351f0fe.png)

也就是说，面包屑只有一层应该都可以隐藏
