### ISSUE TITLE
编辑器代码块交互逻辑优化

### ISSUE THREAD

**Issue by MistRay** [siyuan-note/siyuan#703]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在编辑模式下点击代码块的某个位置
![image](https://user-images.githubusercontent.com/34370155/101856621-9ffe9580-3ba0-11eb-9776-3626a8e995ef.png)
得到的结果,光标的位置在下图位置
![image](https://user-images.githubusercontent.com/34370155/101856699-c9b7bc80-3ba0-11eb-81c6-a13a6db13907.png)

### 描述最优的解决方案 Describe the optimal solution
类似Typora的所见即所得方案
![image](https://user-images.githubusercontent.com/34370155/101857003-7a25c080-3ba1-11eb-842f-7a46f592e594.png)

### 描述候选解决方案 Describe the candidate solution
上面操作期望的结果如下图:
![image](https://user-images.githubusercontent.com/34370155/101856839-17342980-3ba1-11eb-858d-0f15125aeb6d.png)

**Comment by MistRay** [comment]
如果代码块很大的情况下,在编辑时需要再次寻找想要编辑的位置,体验不是友好

**Comment by 88250** [comment]
目前代码块编辑没有改进计划，尽量在 IDE 里编辑好一次性粘贴过来吧，感谢反馈。
