### ISSUE TITLE
能否在多工作空间的前提下，提供设置默认主空间的选项？

### ISSUE THREAD

**Issue by jhan3657** [siyuan-note/siyuan#7030]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前关闭所有空间后，再次打开的经常是不想开的空间（最后一个关闭的空间），需要手动切换主空间。

### 描述可能的最优解决方案 Describe the optimal solution

能否设置初次默认打开的主空间？

**Comment by yixna** [comment]
我也有这种观点，建议作者考虑一下

**Comment by 88250** [comment]
这个不支持设置，只能以最后一个关闭的为准。
