### ISSUE TITLE
When making references, full text does not appear

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#7031]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

When I go to search a reference
![image](https://user-images.githubusercontent.com/90691302/211755397-72338019-faff-4bd0-900c-f237f7e34c86.png)

When I select a reference
![image](https://user-images.githubusercontent.com/90691302/211755536-ed23ac2e-a824-42c3-a317-de6fa4091b1d.png)

### 期待的结果 Expected result

The text appears complete.

### 版本环境 Version environment

```markdown
- Version: 2.6.3
- Operating System: Linux
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10390198/siyuan.log)

**Comment by 88250** [comment]
Try to change this setting:

![image](https://user-images.githubusercontent.com/873584/211806467-e7bd0496-1f05-4771-90c0-37ae22a17aec.png)
