### ISSUE TITLE
Switch to English

### ISSUE THREAD

**Issue by chsnt** [siyuan-note/siyuan#7033]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

I propose to switch to English in order to expand the community in order to increase the reliability and longevity of the project.
Thanks

### 描述可能的最优解决方案 Describe the optimal solution

switch to English

**Comment by zxhd863943427** [comment]
Do you mean https://ld246.com/domain/siyuan?  Perhaps a new area could be added to the community.

**Comment by 88250** [comment]
I don't quite understand what you mean by "Switch to English". Please describe the details of the operation, thank you.

**Comment by rishacha** [comment]
I think the issue makes perfect sense. A lot of the plugin READMEs and documentation - especially the SDK is not in English. The suggestion is simple - Add i18n to everything !

**Comment by TCOTC** [comment]
> A lot of the plugin READMEs and documentation - especially the SDK is not in English.

Depending on the project author. You should raise the issue in the corresponding project
