### ISSUE TITLE
`工作空间列表 ` 不能保存打开过的工作空间历史记录

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7034]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我有个工作空间是放在 U 盘中的，当第一次启动思源时，若是没有插上 U 盘（U盘指定了盘符，每次插上后盘符是不会变化的），“工作空间列表”中之前打开的 U 盘上的工作空间记录就不见了，当下次插上 U 盘使用里面的工作空间时，就需要再次查找路径，非常不便。

### 描述可能的最优解决方案 Describe the optimal solution

希望能够在“工作空间列表”中保存 U 盘上的工作空间的打开记录。

**Comment by 88250** [comment]
如果启动时找不到工作空间路径，则会自动移除该路径并切换到默认工作空间路径（~/Documents/SiYuan/）上，这是为了避免启动失败。

**Comment by GH-W94** [comment]
> 如果启动时找不到工作空间路径，则会自动移除该路径并切换到默认工作空间路径（~/Documents/SiYuan/）上，这是为了避免启动失败。

能否在启动时找不到该工作空间路径时，直接跳过但保留这个路径，然后启动默认工作空间路径（~/Documents/SiYuan/）呢？

**Comment by 88250** [comment]
不自动删除的话会越来越多，这个也是参考 IDE（JetBrains） 处理的。

**Comment by GH-W94** [comment]
> 不自动删除的话会越来越多，这个也是参考 IDE（JetBrains） 处理的。

能否考虑把这个自动清理无效空间路径的动作往后移一下呢？即：
当点击打开“工作空间列表“的某个空间时，正好这个空间的路径是无效的，这时就弹窗提示”此空间路径无效，是否删除？“，将清理权交给用户。
这样即避免了“不自动删除的话会越来越多”的问题，又能保留“暂时失效的空间路径”。

**Comment by 88250** [comment]
自动清理就是为了解决用户手动清理费时的需求……
