### ISSUE TITLE
桌面端删除当前工作空间后报错

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7035]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

已打开的工作空间不应该能够被从工作空间列表删除。
![image](https://user-images.githubusercontent.com/117154557/211811212-9e2593a1-0154-47c0-b1a3-65626fe4e516.png)

### 描述可能的最优解决方案 Describe the optimal solution

已打开的工作空间不应该能够被从工作空间列表删除

**Comment by GH-W94** [comment]
> 请说一下原因。

当删除了已打开的空间后，在关闭了其他空间后，删除的这个空间会突然出现如下提示：
![image](https://user-images.githubusercontent.com/117154557/211826438-c535da35-a30c-4a6a-9520-bb65e9dff987.png)

所以，当鼠标移到“已打开的空间”下的空间名时出现的二级菜单中的“从工作空间列表移除“应替换成”关闭此工作空间“。
![image](https://user-images.githubusercontent.com/117154557/211827373-3260db9a-a12a-494e-a9f5-cd41dd79e115.png)

因此，对于已打开的工作空间，应该是先关闭后从工作空间列表中移除，直接移除时，应提醒工作空间已打开，请先关闭。

**Comment by 88250** [comment]
报错是因为删除后退出了内核进程，桌面端环境不应该退出内核的，这个稍后调整。
