### ISSUE TITLE
顶栏工作空间和外观模式下拉菜单二次点击收回

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7036]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![多开空间菜单收不回](https://user-images.githubusercontent.com/117154557/211811579-80cbe11f-09c4-4c0c-a4f9-631ebebc954e.gif)

### 描述可能的最优解决方案 Describe the optimal solution

希望点击第二下时能收回菜单

**Comment by Temacc0531** [comment]
感觉所有的菜单都可以改成二次点击消失， #6783 第二点

**Comment by Vanessa219** [comment]
菜单再次点击可以消失，再次右键就不消失了。

**Comment by svchord** [comment]
同样希望右下角帮助菜单能改成点击展开，二次点击或者点击空白处收回

**Comment by 88250** [comment]
@svchord 状态栏右下角和左下角菜单保持一致，悬浮展开。

**Comment by svchord** [comment]
> @svchord 状态栏右下角和左下角菜单保持一致，悬浮展开。

但左下角菜单是点击事件有另外的功能，而现在右下角菜单点击事件功能取消了啊

**Comment by Vanessa219** [comment]
> > @svchord 状态栏右下角和左下角菜单保持一致，悬浮展开。
> 
> 但左下角菜单是点击事件有另外的功能，而现在右下角菜单点击事件功能取消了啊

收到
