### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by chsnt** [siyuan-note/siyuan#7037]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Need Russian language translation

### 描述可能的最优解决方案 Describe the optimal solution

I started translating into Russian using the chatGPT translator. It's simple. If anyone has a desire - continue.   

[ru_RU.json](https://github.com/chsnt/siyuan/blob/79dbf66e9232c8182c0ee31ee07afab005dd8c3d/app/appearance/langs/chsnt/ru_RU.json)

**Comment by 88250** [comment]
Duplicate  of https://github.com/siyuan-note/siyuan/issues/3964

Please submit via Pull Request if available, thanks.
