### ISSUE TITLE
多开工作空间 `锁屏` 后访问鉴权失败

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7038]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当多个空间都设置访问鉴权码，用快捷键锁屏其中的一个时，其他的空间会出现如下情况，只能任务管理器中强制结束进程：
![多开空间访问鉴权bug](https://user-images.githubusercontent.com/117154557/211815099-963de28d-689f-45a7-a6c4-28d25452d359.gif)

![多开空间访问鉴权bug](https://user-images.githubusercontent.com/117154557/211815348-7a67338c-467f-4a18-8d13-43405119df28.gif)

### 描述可能的最优解决方案 Describe the optimal solution

即然各个空间的配置数据是隔离的，不考虑全局配置，那么能不能当各个空间的“锁屏”快捷键设置的都一样时，按一次快捷键，就能将打开的所有工作空间都锁屏呢。

离开电脑时，一个空间一个空间的去锁屏，实在是一项烦人的事情。

**Comment by 88250** [comment]
> 即然各个空间的配置数据是隔离的，不考虑全局配置，那么能不能当各个空间的“锁屏”快捷键设置的都一样时，按一次快捷键，就能将打开的所有工作空间都锁屏呢。

> 离开电脑时，一个空间一个空间的去锁屏，实在是一项烦人的事情。

这个我们单独开 issue 考虑处理，谢谢。
