### ISSUE TITLE
托盘快捷键

### ISSUE THREAD

**Issue by lepecoder** [siyuan-note/siyuan#704]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
比较习惯快捷键操作，缩小到右下角托盘后图标太小了，用鼠标点开不方便。

### 描述最优的解决方案 Describe the optimal solution
可否支持全局快捷键唤起？
我尝试为桌面图标设置快捷键，但是因为可以多开，这会打开一个新的思源窗口

**Comment by 88250** [comment]
v0.5.45 加入：<kbd>Ctrl Shift Y</kbd>
