### ISSUE TITLE
希望使用浏览器插件剪藏后，不要折叠文档树

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7040]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在使用浏览器插件剪藏后，总要把文档树折叠，因为需要将剪藏的文档移到之前打开的文档下面，所以还需要再次定位到文档的位置，非常麻烦。
![剪藏折叠文档树](https://user-images.githubusercontent.com/117154557/211823677-bdd8b1d6-1bcd-4614-a72e-ee05e232866d.gif)
![剪藏折叠文档树](https://user-images.githubusercontent.com/117154557/211823834-fff4ada8-5cce-4685-a2a3-f0db452f37e9.gif)

### 描述可能的最优解决方案 Describe the optimal solution

使用浏览器插件剪藏后，不要折叠文档树

**Comment by 88250** [comment]
不刷新的话看不到剪藏的文档，这个目前不大好改进，只能走统一的刷新文档树了，感谢反馈。
