### ISSUE TITLE
为同步状态添加对应的图标

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7041]
未启用、默认、同步中、同步失败。

https://ld246.com/article/1673420979805

**Comment by mozhux** [comment]
应该还有个同步成功吧。。

**Comment by 88250** [comment]
同步成功就是默认

**Comment by mozhux** [comment]
> 同步成功就是默认

那默认的图标可能也是要改改？不知道会是怎样的

**Comment by 88250** [comment]
默认图标应该就是现在这个了，新加其他三种。
