### ISSUE TITLE
希望能自定义程序图标以区分多开时不同的工作空间

### ISSUE THREAD

**Issue by ippreacher** [siyuan-note/siyuan#7050]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前已支持多开工作空间，但由于程序图标相同，导致切换时不容易区分。

### 描述可能的最优解决方案 Describe the optimal solution

建议采用自定义程序图标解决这一问题。

**Comment by 88250** [comment]
* 自定义程序图标应该可以通过操作系统完成
* 目前已经在窗口标题上加入了工作空间名称，托盘上悬浮也有，应该可以较为方便地区分
