### ISSUE TITLE
改进标签、引用、嵌入、表情和斜杆提示交互

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7052]
Esc、点击、左右键导致补全消失后的继续输入不再对其进行补全。

https://ld246.com/article/1673490514696

**Comment by Achuan-2** [comment]
我的想法是，esc 后不需要移除#号，就如目前的斜杆的输入交互一样，输入斜杆是可以唤起斜杆菜单的，但按了esc键之后，斜杆就是普通的字符了。同理，段落中输入#之后，按esc之后，#也变为普通字符

**Comment by Vanessa219** [comment]
收到，那我理解错了。已更新

**Comment by Vanessa219** [comment]
@Achuan-2 斜杆菜单按 Esc 后还是会继续被唤起。还有行内代码对标签的支持应该没有什么问题，不应该屏蔽。

**Comment by Achuan-2** [comment]
@Vanessa219 个人建议：行内代码支持标签没有意义，标签也不是GFM有的语法，一般使用标签也是在段落块末尾和给文档块打标签。

**Comment by Temacc0531** [comment]
v2.7.4-dev1 出现一个新的问题，现在输入`【【`后已经彻底不进行联想了

**Comment by Temacc0531** [comment]
v2.7.4-dev1 引入一个新问题，启动后，输入`【【`不会出现任何联想

**Comment by Vanessa219** [comment]
需要怎么操作么？我这里是 OK 的。 @Temacc0531 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/970828/217693633-2afcf918-c7ac-4366-ad4b-c8287393dca0.png">

**Comment by 88250** [comment]
[[ 关键字为空的时候会显示已有的 refs，如果没有的话就是空的了。

**Comment by Temacc0531** [comment]
启动完直接使用`【【`不会出现联想
先使用`[[`正常，再使用`【【`就会正常联想了（也出现了一次还是不会联想的情况）

![GIF 23-2-9 9-48-52](https://user-images.githubusercontent.com/101307399/217696797-41959d5f-9fe9-44b6-883d-56da03f307c6.gif)

**Comment by Vanessa219** [comment]
试了一下这里是正常的，看一下有没有报错或发送了这个请求？
<img width="486" alt="image" src="https://user-images.githubusercontent.com/970828/217699667-b3d605d3-520b-4de9-85f7-448a1c277ccd.png">

**Comment by Temacc0531** [comment]
没有看到`searchRefBlock`，只有这几个请求
![image](https://user-images.githubusercontent.com/101307399/217701871-b2cfee35-1b2f-48be-af42-d15d06ef58bc.png)

**Comment by Temacc0531** [comment]
找个另一个复现步骤，你试试。可以正常联想情况下，退格，点下另外一个块，再点回来，重新输入`【【`就不会联想了

![GIF 23-2-9 10-33-17](https://user-images.githubusercontent.com/101307399/217702945-c2d574ca-0752-42e1-96f6-2c5305a9e06b.gif)

**Comment by Vanessa219** [comment]
感谢反馈，已经可以重现，稍后修复
