### ISSUE TITLE
表格可以支持回车换行吗？

### ISSUE THREAD

**Issue by crendy** [siyuan-note/siyuan#7053]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

复制其他文档中的内容 或表格内容到思源，回车换行都没有了

### 描述可能的最优解决方案 Describe the optimal solution

表格单元格内支持回车换行

**Comment by 88250** [comment]
抱歉，粘贴其他软件无法支持，因为不同软件的格式解析太复杂多样了。

**Comment by crendy** [comment]
> 抱歉，粘贴其他软件无法支持，因为不同软件的格式解析太复杂多样了。

目前主流的几个是否可以支持，比如 语雀  飞书 ，他们之间复制都是可以的
