### ISSUE TITLE
支持链滴积分兑换扩容云端存储

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7055]
## 兑换规则

每 18 积分可扩容 1MB 云端存储，每次最少兑换 18 积分，暂时不设最多兑换上限。

兑换入口在链滴上（设置 - 积分 - 积分兑换思源云端存储），用户自助输入兑换积分数，除以 18 后如有余数则不计入兑换，比如输入 1000 积分兑换，实际兑换为 55MB，扣除积分 990。

终身订阅账号不支持积分兑换扩容云端存储。

## 中断订阅则清零扩容

积分兑换扩容仅在当前订阅期内有效，一旦订阅过期则积分兑换的扩容空间将被归零。

举个例子，我通过积分兑换扩容了 500MB，那么现在云端存储上限则是 8.5G（8G 默认加 500MB 扩容），但是订阅到期后没有续订，则到期时系统清理云端空间时会同时清理扩容空间。后来我再次重新付款订阅，但是之前扩容的 500MB 存储也不会回来，所以还是默认的 8G 上限。

再啰嗦一下，简单地说就是只要订阅中断过，之前扩容的存储大小就清零了。

## 链滴积分规则

详情请看[链滴积分规则](https://ld246.com/article/1441724208848)。

**Comment by wuyigui323** [comment]
赶紧去签个到

**Comment by zxhd863943427** [comment]
这个可以作为一个良好的开始，但还是建议主要为加价扩容

**Comment by lentikr** [comment]
那终身订阅的账户该怎么扩容呢？

**Comment by litcu** [comment]
中断订阅后，之前通过邀请码获取的云端大小也会清空吗？

**Comment by 88250** [comment]
> 中断订阅后，之前通过邀请码获取的云端大小也会清空吗？

不会。

**Comment by 88250** [comment]
> 那终身订阅的账户该怎么扩容呢？

介于目前运营成本有限，短期内可能不会考虑支持终身账号扩容。

**Comment by nscmiaoxin** [comment]
终身账号的确需要有个方案，对我而言，占空间的文件其实就是网页剪裁的图片，是否可以考虑像坚果云一样给个终身会员每月的同步流量

**Comment by strugglesharp** [comment]
> 终身账号的确需要有个方案，对我而言，占空间的文件其实就是网页剪裁的图片，是否可以考虑像坚果云一样给个终身会员每月的同步流量

还不明白吗, 思源有点想赶快处理掉终身账号.

**Comment by woniuxia** [comment]
> > 还不明白吗, 思源有点想赶快处理掉终身账号.
> 
> 你的理解有误，我们并没有这个想法，之所以不提供终身订阅账号扩容完全是因为成本有限。

D大，直接考虑出个付费买容量的服务吧。这样永久会员也可以考虑直接付费加量。
加的量都是按月服务。

**Comment by 88250** [comment]
> D大，直接考虑出个付费买容量的服务吧。这样永久会员也可以考虑直接付费加量。 加的量都是按月付费。

不管是对年付订阅还是终身订阅，我们之前考虑过付费扩容的，计划的定价是 ￥15/G/年。但是这个性价比实在太低了，就算出了也没有几个人会买的，所以暂时就无法考虑付费扩容了，也许以后改变订阅模式才能解决问题，比如通过流量计费。

**Comment by 88250** [comment]
已经支持终身订阅账号通过积分扩容 https://github.com/siyuan-note/siyuan/issues/7210
