### ISSUE TITLE
在工作空间的二级菜单增加一个“发送此空间的快捷键到桌面”的功能

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7058]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

为了实现能直接启动指定的工作空间，我研究了好半天才明白，所以希望大佬能在如下的工作空间的二级菜单增加一个“发送此空间的快捷键到桌面”的功能，以便更多小白操作。
![image](https://user-images.githubusercontent.com/117154557/212054592-c0fcae70-0889-40f4-92b2-e37fa43ca229.png)

### 描述可能的最优解决方案 Describe the optimal solution

增加一个“发送此空间的快捷键到桌面”的功能

**Comment by UFDXD** [comment]
早需要了，虽然会弄，但软件直接创建发送会更好

**Comment by 88250** [comment]
我刚刚搜索了一下，似乎没有简单可靠的技术方案，还是只能用户手动建立。
