### ISSUE TITLE
导出.sy.zip文件没有导入的方法

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#7063]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/72953189/212074688-eb3b2e12-8d2f-476a-a2f6-5b08eca960ba.png)

思源文档导出为.sy.zip形式貌似没有导入的方式，在设置中的导入只能够覆盖原来的空间

![image](https://user-images.githubusercontent.com/72953189/212075150-7cca8daf-6283-45c5-9d25-aab6794513b2.png)

目前这个功能只能通过拷贝文件到对应目录吗？

### 描述可能的最优解决方案 Describe the optimal solution

但是，如果是拷贝过去的，需要引用文件毕竟不是很方便。需要长长的文件名

**Comment by 88250** [comment]
文档树右键菜单有导入：

![image](https://user-images.githubusercontent.com/873584/212078249-58d10af6-3159-45b9-930d-b6dc9e021528.png)
