### ISSUE TITLE
每次打开软件后，localStorage的数据都被清空

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#7064]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

V2.6.3，Windows 10

刚刚才留意到，每次打开软件后，开发面板里localStorage的数据都被清空了。这是特意设计成这样的还是出bug了？

![图片](https://user-images.githubusercontent.com/58081876/212098566-36b4ea50-f280-4a46-b29b-7b9e82210dba.png)

### 期待的结果 Expected result

不自动清空LocalStorage的数据

### 版本环境 Version environment

```markdown
- Version: 2.6.3
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
不要使用 localStorage 存储数据，因为现在用的是随机端口。
