### ISSUE TITLE
闪卡添加卡包时区别卡包中是否已经存在该闪卡

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#7065]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/60436214/212229499-c0c1d990-3a68-4d83-a6b2-b8483cb1ab9c.png)
目前闪卡添加卡包时，并不区分卡包有无此闪卡

### 描述可能的最优解决方案 Describe the optimal solution

建议无此闪卡的卡包置灰，卡包添加闪卡后变成正常颜色
![image](https://user-images.githubusercontent.com/60436214/212229777-4998d998-4f71-4628-abf3-9c99edfe9d32.png)

另外创建卡包我认为放在界面下方比较符合逻辑
![image](https://user-images.githubusercontent.com/60436214/212230132-c0aa2bd7-2412-4f9d-8c3d-b5dd78f49d34.png)

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
* 因为支持批量添加闪卡，所以无法区别是否部分存在
* 即使重复添加也没有副作用的
