### ISSUE TITLE
Error opening color menu

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#7069]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/90691302/212330280-6da191cc-6c3e-4880-8638-5ab590bbde21.png)

I updated to version 2.6.3 but found an error in the table. So I went back to version 2.5.5 until the creator fixed the theme. When I go back to version 2.5.5, when I click on a text and then select the "Font" option, it doesn't open! When opening the developer menu, this error appears when clicking on the button. When going back to the original theme (midnight), the error still persists. Would you help me?

### 期待的结果 Expected result

The color selection appears.

### 版本环境 Version environment

```markdown
- Version: 2.6.3
- Operating System: Linux
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10411900/siyuan.log)

**Comment by 88250** [comment]
The screenshot does not seem to be the latest version, please try to upgrade to the latest version then reset the appearance.

**Comment by zxhd863943427** [comment]
Could you describe "found an error in the table" in detail?

As you know, developer cannot fix the bug in a obsolete version.

**Comment by taozina0587** [comment]
@zxhd863943427  I found an error on the sheet because of the theme I use. Some things lost formatting. I'll wait for the creator to try to fix it to use the new versions of SiYuan.

**Comment by taozina0587** [comment]
@zxhd863943427  But deleting SiYuan's workstation, I went back to old and recent versions. But nothing... The "font" tab in the menu doesn't work anymore.
