### ISSUE TITLE
笔记本快捷方式

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#707]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

用熟悉的方法快速用思源打开指定的笔记本、笔记。

### 描述最优的解决方案 Describe the optimal solution

没有成熟的解决方案，只有构想。

需要做一个为笔记本、单篇笔记创建桌面快捷方式的功能。创建快捷方式后，双击快捷方式，打开指向的笔记本、笔记。

打开笔记本快捷方式有需要做。

如果思源打算做 md 编辑器，双击 md 文件就能用思源笔记打开编辑的话，文档快捷方式功能就不用做了。

**Comment by 88250** [comment]
理论上可以在安装时给操作系统注册应用协议 `siyuan://`，然后类似这样的 URL 拉起应用  `siyuan://open?notebook={xxx}`。

没有做 .md 编辑器的打算……

**Comment by HaujetZhao** [comment]
> 理论上可以在安装时给操作系统注册应用协议 `siyuan://`，然后类似这样的 URL 拉起应用 `siyuan://open?notebook={xxx}`。

可以给这个过程做个快捷的功能吗？比如放到右键菜单或者其它合理的位置。毕竟个人弄快捷方式，又要考虑图标等待之类的繁琐细节。

估计右键菜单功能做多了以后，得加一个 **更多** 的父项，把一些不常用功能放进去，成为二级条目，在设置里面可以调整哪些放到 **更多**，哪些放到一级条目。

**Comment by 88250** [comment]
感谢讨论，目前不考虑了，因为有便携 zip 版本注册不了应用协议。另外，在思源内核工作时，可通过内容块 URL 在浏览器上进行打开定位。
