### ISSUE TITLE
改进主界面菜单和功能入口布局

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7071]
* 调整左上角顶栏工作空间菜单
  * 新增 `面板` 子菜单，放入各个面板的入口
  * 将顶栏右侧设置入口移到工作空间菜单中
  * 将 `已打开的工作空间` 合并到 `工作空间列表` 中，工作空间列表调整为二级菜单并支持纵向滚动
  * 将右下角状态栏帮助菜单`锁屏` 移到工作空间菜单下
* 调整右下角状态栏帮助菜单交互和菜单项
  * 需要点击才打开菜单
    * 帮助
    * 反馈
    * 开发者工具
    * 访问官方网站
    * 访问 GitHub 项目

**Comment by Soltus** [comment]
开发者工具没必要移动吧

**Comment by 88250** [comment]
开发者工具同时放在左上角和右下角吧。

**Comment by zxhd863943427** [comment]
其实我认为数据历史、闪卡、日记都可以移动到停靠栏，这样在统一全部 alt+ 按键的同时，还能方便用户自由选择位置了。
而且，停靠栏是可以选择是否隐藏的，那么把 数据历史、闪卡、日记 移到二级菜单来简化界面的目的也可以实现了。

**Comment by 88250** [comment]
@zxhd863943427 停靠栏是用于放置面板入口的，所以才会区分上下左右几个位置。像数据历史和闪卡不是面板，所以不应该放置在停靠栏上。

**Comment by Soltus** [comment]
主题可以用JS改，就是怕布局变动太频繁了

**Comment by 88250** [comment]
> 主题可以用JS改，就是怕布局变动太频繁了

@Vanessa219

**Comment by Temacc0531** [comment]
坚持自己想法，教育用户😃

**Comment by 88250** [comment]
> 坚持自己想法，教育用户😃

没这实力，会被用户教做人 😂 

https://ld246.com/article/1673616045037

**Comment by GH-W94** [comment]
建议将“锁屏”按钮放在顶栏的右侧，和“只读模式”按钮放在一起。
对于“锁屏”功能，和日记、闪卡一样，对于使用的人来说，是一个非常高频的操作，有时不便按快捷键时，用鼠标点一下就非常便捷，而且“锁屏”和“只读模式”都是保护笔记，放在一起，也有利于用户寻找。
![image](https://user-images.githubusercontent.com/117154557/212431066-d9f37358-97e8-4ac8-8b57-501d32c0ca05.png)

**Comment by isPoto** [comment]
> 

按闹分配？

要是这都能改回去，那我也有样学样好了

我支持现在的折叠式得设计，要是闹两下就改回去，我闹三下

闹就行了嘛，那多简单。不用费事沟通

**Comment by isPoto** [comment]
不要把界面搞成跟飞机驾驶舱一样，一些次要功能放置在二级菜单合理且让 UI 更加清爽
![A300_Upgrade_1440x752](https://user-images.githubusercontent.com/59009389/212444486-007a511b-942b-49d3-a79e-4bb51fd46b8a.jpg)

究竟是简洁吸引人心还是要迎合领导审美。
![媒体](https://user-images.githubusercontent.com/59009389/212444519-5c914faa-c94c-456a-be21-940ad5f1ae1b.jpg)
![有车以后](https://user-images.githubusercontent.com/59009389/212444525-259c8135-59a7-47ab-9b61-8b7b39d1a38b.jpg)

**Comment by Temacc0531** [comment]
> 没这实力，会被用户教做人 😂
> https://ld246.com/article/1673616045037

感觉现在也只是个别用户的多次抱怨造成大多数用户都不适应的假象，而发声的总是少数，我群里也看到不少说喜欢新版简洁外观的😂

**Comment by xy0124** [comment]
我支持新版简洁直观的界面设计
好多快捷按钮是方便了部分人嘛，也有很多人其实没有那么高频次使用。
比如现在那个闪卡，我都不懂是个啥功能，我也根本不会去用他。
我选择使用notion主题，就是能使思源的界面极简。
颜值是生产力

**Comment by 88250** [comment]
再次更新设计，维持现有简洁设计，仅调整其他细节，具体请参考 issue 描述。

自定义顶栏图标入口以后有空再作为新特性考虑。

**Comment by mozhux** [comment]
那个既然要改了，我也提一嘴，那个会员vip 和捐赠按钮单独在右边有点丑的，除非不显示，但又不能显示我尊贵的身份懂吧。希望能和什么东西合并一起展示。比如思源图标加个小皇冠啥的

**Comment by 88250** [comment]
@mozhux 这个后面考虑吧，目前先改进菜单。

**Comment by zznww** [comment]
个人建议软件产品设计决策基于数据而非个别用户的个人诉求（可以作为创意来源）。比如通过一些用户调查、ab测试结果或软件使用的行为数据来决策。不是这方面专业可能不一定对或许有更好做法。我是从那个什么背刺用户的帖子过来，不得不借github账号发个声，思源笔记这个软件真的太优秀了，从浏览社区上的一些帖子看，d大和v大既积极服务社区还能这么快不断完善和演进这个开源免费的软件，发自内心佩服和感谢！就这么几天使用和摸索下来，已经准备替换掉onenote了，不多说了回头钱包支持下

**Comment by zxhd863943427** [comment]
> 个人建议软件产品设计决策基于数据而非个别用户的个人诉求（可以作为创意来源）。比如通过一些用户调查、ab测试结果或软件使用的行为数据来决策。不是这方面专业可能不一定对或许有更好做法。我是从那个什么背刺用户的帖子过来，不得不借github账号发个声，思源笔记这个软件真的太优秀了，从浏览社区上的一些帖子看，d大和v大既积极服务社区还能这么快不断完善和演进这个开源免费的软件，发自内心佩服和感谢！就这么几天使用和摸索下来，已经准备替换掉onenote了，不多说了回头钱包支持下

话虽如此，但是现在并没有一个良好的统计机制，社区现在的参与度相对于用户数量而言并不高，更不要说投票率了。

我觉得要么一条路走到黑，除非是重大的功能问题，否则就坚持设计者的理念，要么就在思源内部加入统计功能，提高设计的用户参与度，不然这样的争执将永远秉承“按闹分配”原则。

**Comment by isPoto** [comment]
就一条路：有自己的独立思考

想清楚、想明白自己要做什么，自己的基本盘是什么

做自己想要的软件

敢于向用户说不

**Comment by mozhux** [comment]
刚试用了预览版，没有理解到面板菜单的入口用意，这个和底栏的关闭和打开有什么不同吗？还是说防止有人关了底栏看不到展开的?
![image](https://user-images.githubusercontent.com/46953371/212485585-0969d63a-8e6c-408e-a290-85331beb38eb.png)

**Comment by 88250** [comment]
@mozhux 是的，核心功能入口放在多个菜单中。
