### ISSUE TITLE
如果后一行的列表比前一行的列表先输入，那么第二行无法缩进

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7073]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如果后一行的列表比前一行的列表先输入，那么第二行无法缩进。

### 期待的结果 Expected result

第二行能缩进。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![动画](https://user-images.githubusercontent.com/56879067/212449176-05b9d627-0547-42cc-ac96-05d5dc9911ca.gif)

### 版本环境 Version environment

```markdown
- Version: 最新版
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
这个是两个列表块。
