### ISSUE TITLE
希望增加图片自动OCR识别文字到“提示文本”的功能

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7076]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

图片OCR是一个非常实用的功能，好多人都提出了OCR的需求，好多笔记软件也都有OCR功能，可见该功能还是很受笔记用户欢迎的。
相信提出OCR需求的人大部分都是为了“搜索”时，能够找到想要的图片，尤其是做了大量笔记的用户，尤其关注搜索功能的全面话和可靠性。

### 描述可能的最优解决方案 Describe the optimal solution

最理想的方案：
1. 能实现类似微信，打开图片后，能够直接选中图片中的文本内容。
2. 搜索时，如果图片含有搜索文本，能够像印象笔记那样，将搜索到的文本高亮标注。

### 描述候选的解决方案 Describe the candidate solution

简单实现方法：
感觉ocr功能没必要一定要跨平台，PC端能够实现图片ocr，并把ocr识别到的内容保存到图片的“提示文本”中就能够满足绝大部分人的需求，这样跨平台也能搜索。相信**提出ocr功能需要的人绝大部分都是为了搜索**需求的。
需要注意的是，如果在android端添加了图片，或以前就在思源笔记中存在的图片，ocr功能能够将这些未进行ocr的图片识别到，并自动对其ocr识别，保存到各自图片的“提示文本”中。这样就能满足图片文字搜索的需求了，感觉ocr功能很实用，提出该问题的人也很多，希望能够添加，谢谢！

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3470
