### ISSUE TITLE
文档树和笔记区的反向链接数量标记无法尽快更新

### ISSUE THREAD

**Issue by mzcxiaohuanxiong** [siyuan-note/siyuan#7077]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

笔记区增加链接后，该块后面的反向链接标记不能很快生成，去掉该链接，该标记也无法尽快消失。

### 期待的结果 Expected result

该标记能及时更新

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/49083219/212520210-b7ee7086-1ebc-4f66-9d94-0a8f99dd0179.png)

### 版本环境 Version environment

```markdown
- Version:  v2.6.3
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10419346/siyuan.log)

**Comment by 88250** [comment]
这个需要手动 F5 刷新。

**Comment by mzcxiaohuanxiong** [comment]
但F5对文档树里的标记无效




meng_zc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 文档树和笔记区的反向链接数量标记无法尽快更新 (Issue #7077)





 
这个需要手动 F5 刷新。

**Comment by 88250** [comment]
文档树的话需要重新展开。

**Comment by mzcxiaohuanxiong** [comment]
哦~，好的，谢谢




meng_zc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月15日(星期天) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 文档树和笔记区的反向链接数量标记无法尽快更新 (Issue #7077)





 
文档树的话需要重新展开。
