### ISSUE TITLE
设置了授权码（accessAuthCode）后输入正确授权码无法进入工作空间

### ISSUE THREAD

**Issue by aa1149479355** [siyuan-note/siyuan#7082]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/64082994/212554033-15e4e74d-d08c-40fc-ac5d-80f34066721b.png)

在xxx/check-auth的页面输入正确授权码accessAuthCode后跳转回了授权页面，没有正常进入工作空间！

### 期待的结果 Expected result

输入正确授权码后正常进入工作空间

### 版本环境 Version environment

```markdown
- Version: 2.6.3
- Operating System: window 11 专业版
- Browser (if used): Microsoft Edge 108.0.1462.76
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10420693/siyuan.log)

**Comment by 88250** [comment]
Docker 部署的话应该是因为没有正确配置反向代理，建议浏览器 F12 看下请求。

**Comment by aa1149479355** [comment]
> Docker 部署的话应该是因为没有正确配置反向代理，建议浏览器 F12 看下请求。

我没用nginx和域名，不需要反代，f12看是正常成功调用的，但是没进入到工作空间。。。

**Comment by aa1149479355** [comment]
> Docker 部署的话应该是因为没有正确配置反向代理，建议浏览器 F12 看下请求。

建议您们这边可以排查下仅在公网ip的情况下设置授权码校验授权码成功后有没有正常进入工作空间
