### ISSUE TITLE
无法导出为word

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#7083]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

导出为word失败

### 期待的结果 Expected result

导出为word

### 截屏或者录屏演示 Screenshot or screen recording presentation

[导出为word](https://user-images.githubusercontent.com/112467275/212583551-93cb946d-7b1e-4950-ad9f-dde8368488c4.mp4)

### 版本环境 Version environment

```markdown
- Version: 2.6.3
- Operating System: windows 11
- Browser (if used):edge
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10421981/siyuan.log)

### 更多信息 More information

就是上述问题

**Comment by Benjamin-Watson0** [comment]
忘记下载pannoc了

**Comment by 88250** [comment]
现在的版本 Pandoc 是自带的，不用单独下载。

**Comment by Benjamin-Watson0** [comment]
可是我导出没反应啊，我下载了才可以的

**Comment by 88250** [comment]
日志看上去初始化内置的 Pandoc 正常：

```
I 2023/01/16 10:03:35 working.go:370: built-in pandoc [ver=2.19.2, bin=D:\siyuan-bucket\temp\pandoc\bin\pandoc.exe]
```

**Comment by Benjamin-Watson0** [comment]
但确实不行,我以为不知道
