### ISSUE TITLE
Docker 部署的 siyuan v2.6.3 对表格操作的描述存在错误

### ISSUE THREAD

**Issue by benz9527** [siyuan-note/siyuan#7085]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/109717800/212598810-9e1188dd-9386-4aba-944b-7413856bdb68.png)
如上图，插入行，实际是插入列；插入列实际应该是插入行。
![image](https://user-images.githubusercontent.com/109717800/212599011-b7e5c59b-12de-447a-929b-87eff5175a64.png)
还有表格的删除行，实际是删除列。

### 期待的结果 Expected result

希望能修改下描述。

### 版本环境 Version environment

```markdown
- Version: v2.6.3
- Operating System: docker debian
- Browser (if used): Microsoft edge 108.0.1462.46
```

### 日志文件 Log file

这个是 ui 的文字描述问题，不需要日志

**Comment by 88250** [comment]
繁体中文的行列是相反的。

**Comment by benz9527** [comment]
还有这种说法

**Comment by SineMark2020** [comment]
這有歷史因素，導致矩陣運算兩邊討論常搞混，建議實際工程運用使用column ，row

**Comment by benz9527** [comment]
好的。查了下资料，以前的行文是垂直结构，称垂直的一排文字为行
