### ISSUE TITLE
Support custom top bar operation

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7090]

**Comment by tangjiahao2001** [comment]
支持，最好思源形成一个固定的面板风格，不要总是修改外观。老用户根据习惯自定义修改外观就可以

**Comment by 88250** [comment]
目前已经通过插件支持自定义顶栏操作，这个 issue 不再需要考虑了。

**Comment by lucifer-j** [comment]
> 目前已经通过插件支持自定义顶栏操作，这个 issue 不再需要考虑了。

请问哪个插件支持自定义顶栏？在市集没找到
