### ISSUE TITLE
建议增加个“笔记文档能在不同工作空间之间移动”的功能，以解决浏览器剪藏插件不能识别多空间的问题

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7091]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

看到论坛中讲“剪藏扩展自动填入的是默认的 IP 和端口，第一个启动的工作空间除了监听随机端口外也会同时使用 6806 端口，而后续启动的其他工作空间都是随机端口，所以无法设置。”，没法实现浏览器剪藏插件识别多空间的功能，但这在需要剪藏时，目标不是第一个打开的空间时，就需要将所有空间关闭，重新将目标空间放在第一位打开，非常不便。

### 描述可能的最优解决方案 Describe the optimal solution

若是能增加个“笔记文档能在不同工作空间之间移动”的功能，就可以先剪藏到第一个打开的空间，然后将剪下的文档拖到目标空间中，迂回解决浏览器剪藏插件不能识别多空间的问题。

**Comment by 88250** [comment]
这个目前不考虑了，因为工作空间的目的是为了物理隔离，所以不会加入不同工作空间之间直接的数据交互操作特性。

浏览器剪藏的话目前确实有局限性，因为只有 6806 端口是固定的，被第一个启动的工作空间使用。

后续可能可以加个 --port（类似 --workspace）启动参数来指定工作空间启动时监听的端口，然后浏览器剪藏固定配置这个端口。
