### ISSUE TITLE
关于编辑器的几个小建议

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7098]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

关于编辑器提几个小建议：
1、顶部标签页可以设置最小宽度和最大宽度。
2、顶部标签页右键增加删除标签页、重命名标签页的选项。
3、正文编辑文本时，选中文本不能拖动到其它位置，不知道能不能实现选中文本可以拖动位置（win11）。
4、在设置字体颜色的弹窗，建议把字体颜色设置改为“A”字母，而不是纯背景块，以和背景颜色的设置进行区别。
5、建议在顶部窗口标题栏右侧或您觉得合适的地方设置一个，用户可以自定义快捷操作的位置。毕竟用户都有自己的需求，经常用到的功能各自不一样。
6、在左侧栏，如果条目不是最后一级，建议能够双击展开和折叠，不用非得点击左侧的下拉箭头。
7、在搜索窗口，建议不要把搜索到文本的那一行显示在顶行，因为在用鼠标选择顶行文本时，一定会触发窗口的向上滚动操作，并弹出跨页多选提示。

### 描述可能的最优解决方案 Describe the optimal solution

没有大的问题，都是一些小建议，如果您觉得恰当的话请优化一下，如果感觉提的不合适这样用着也行。

### 其他信息 Other information

思源笔记是一款很棒的软件，感谢您的辛苦付出！

**Comment by pisceswb** [comment]
界面简洁，看起来清爽，高稳定性也是非常重要的，以上仅是建议

**Comment by 88250** [comment]
1. 通过自定义 CSS
2. 暂时不考虑
3. https://github.com/siyuan-note/siyuan/issues/6169
4. 是个好建议，稍后开个 issue 单独处理
5. Duplicate of #7090 
6. Duplicate of #6523
7. 是个好建议，稍后开个 issue 单独处理

感谢反馈。
