### ISSUE TITLE
插入资源文件时文件名长度最大限制 189 字节

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7099]
过长的资源文件名会导致同步后某些系统平台上迁出失败 https://github.com/siyuan-note/siyuan/issues/7097

大部分系统对于文件名最大长度支持都是 255 字节，但是由于编码方式不同，我们只能取较大编码算法进行计算（3 或 4 个字节），也就是 255-11（临时文件后缀）-23（id 部分）- 5 左右后缀 = 216 字节，216/3 = 72 汉字 或 216/4 = 54 汉字，由于大部分汉字都是 3 字节，所以取一个中间值大约是 63 汉字，63*3 = 189 字节

插入资源文件时，文件名长度大于 189 字节，则自动删除过长的部分。已有文件不做处理。

**Comment by Zuoqiu-Yingyi** [comment]
这是是不是应该对 ASCII 字符与非 ASCII 字符分别计算呢

**Comment by 88250** [comment]
是的，现在的实现有点粗暴。

**Comment by Zuoqiu-Yingyi** [comment]
那我今天找时间研究一下在合法字符之间根据字节长度进行切片的解决方案

**Comment by 88250** [comment]
不用了，我在改了，等会提交你 review 下。

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 已经提交

**Comment by Zuoqiu-Yingyi** [comment]
@88250 用了几个测试用例, 应该没啥问题 o(￣▽￣)ｄ
