### ISSUE TITLE
希望增加笔记加密功能

### ISSUE THREAD

**Issue by moneie** [siyuan-note/siyuan#710]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在单位使用的时候，有暂时离开电脑的情况，需要同事到笔记里差些东西，这时候不想对方看到自己的个人笔记

### 描述最优的解决方案 Describe the optimal solution
笔记或文件夹加密，不动什么加密等级，对于我来讲，设个密码就足够用了

**Comment by 88250** [comment]
你好，加密的话估计要做 md 原文本的加密才较为保险，目前暂时没有计划，该提议保留打开状态，等后期我们看下如何实现，谢谢。

**Comment by 88250** [comment]
数据加密不考虑了，我们对界面层的访问鉴权密码进行支持，请关注 #1139
