### ISSUE TITLE
容器中内核自动退出 Containerized kernel exits automatically

### ISSUE THREAD

**Issue by cyp0633** [siyuan-note/siyuan#7101]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

我用于部署思源笔记的容器环境是Podman，这是一种与Docker同样遵守OCI规范的容器管理工具。之前一直使用Podman在Arch Linux上运行b3log/siyuan:latest Docker镜像，一切正常。
近期更新之后，镜像会在启动约一分钟之后，自动停止运行。打开浏览器，发现容器start正常运行一段时间之后页面出现“正在退出”，稍后即出现”内核连接中断“（见截图）。
日志见后面的日志部分。

### 期待的结果 Expected result

思源kernel保持运行，不会自动退出，浏览器页面也不会出现”内核连接中断“。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![siyuan-exit](https://user-images.githubusercontent.com/16500188/212892554-ec564b94-ed3a-41e8-a3b4-02630c0a5790.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: Arch Linux（服务端）/Windows 11（浏览器端）
- Browser (if used): Chromium 108与Firefox 109均可稳定复现
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10434707/siyuan.log)

### 更多信息 More information

检查日志与issue列表，发现思源kernel会自动检测UI进程即Electron是否在运行（#7002），如果不存在则直接退出，而在容器化部署的场景下应该是没有Electron的。
个人有一个不成熟的方案，在检测UI进程决定是否退出时，将是否容器化部署（[`util.Container`](https://github.com/siyuan-note/siyuan/blob/9cf02cb629bceb6b5e787c1432b1bb93a0401c60/kernel/util/working.go#L289)）作为另一个条件。但因不熟悉应用总体架构，没有提PR。

顺祝contributor们，尤其是两位主要开发者兔年大吉。

**Comment by 88250** [comment]
Container 的赋值有个判断：

```go
func isRunningInDockerContainer() bool {
	if _, runInContainer := os.LookupEnv("RUN_IN_CONTAINER"); runInContainer {
		return true
	}
	if _, err := os.Stat("/.dockerenv"); err == nil {
		return true
	}
	return false
}
```

可以通过环境变量 `RUN_IN_CONTAINER` 指定 https://github.com/siyuan-note/siyuan/issues/5744

**Comment by cyp0633** [comment]
我指的不是如何设置util.Container，而是model.HookDesktopUIProc在不区分是否为容器的情况下简单粗暴地判断思源Electron进程是否在运行，导致在本就不该有Electron运行的情况下内核被错误地结束，大概是以下的流程：
容器启动->启动内核，没有Electron启动->过了一段时间->内核找不到UI进程->内核结束->用户发现浏览器内核连接断了

加入判断后，应该是：
……->内核找不到UI进程，但发现在容器中运行->内核不结束->用户正常使用

即 `process.go` 第76行附近可以改为（仅表达意思，未经测试）：
```go
		if !existUIProc && util.Container != util.ContainerDocker {
			logging.LogInfof("no active UI proc, exit kernel process now")
			Close(false, 1)
		}
```

我看到容器环境下可以判断`.dockerenv`文件来设置util.Container，这个是正常行为，并不是issue所谈论的问题。

**Comment by 88250** [comment]
上面有判断的，你仔细看一下：

```go
func HookDesktopUIProc() {
	if util.ContainerStd != util.Container || "dev" == util.Mode {
		return
	}
```

**Comment by cyp0633** [comment]
首先抱歉之前的建议考虑不周，疏忽了。

这个问题似乎是因为Podman的env位于`/run/.containerenv`而非`/.dockerenv`（ https://github.com/containers/podman/issues/1583 ），所以思源笔记无法检测到处于容器环境。也就是说问题出在容器环境的检测方式上。

为了证明这个结论，我使用我的Arch Linux+Podman PC和两台全新安装的Arch Linux云服务器（一台Docker，一台Podman）做了个实验。
1. 在PC上pull下来dev分支源代码，运行`podman build`并将镜像分别导入两个服务器。
2. 分别在两个云服务器上，由刚刚导入的镜像新建一个思源笔记容器。
3. 发现Docker服务器能够正常运行，Podman服务器自动退出，现象与本issue之前描述的相同。
4. 在PC中源代码的`/kernel/util/path.go`的123行左右加入以下内容：
```go
	if _, err := os.Stat("/run/.containerenv"); err == nil {
		return true
	}
```
5. 停止之前创建的容器，然后重新进行1-2步。
6. 两个新容器均正常运行，再使用原issue中使用的环境使用新镜像创建容器，也能够正常运行。

这证明修改后的思源笔记也可检测到Podman容器环境，从而避免意外退出。

如果您愿意为思源笔记加入如上所示的对Podman的额外适配，我很乐意提一个PR。

**Comment by 88250** [comment]
dev 上我们已经在 Dockfile 中加入了环境变量 https://github.com/siyuan-note/siyuan/issues/7104 通过这个判断应该是比较稳妥的方式。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/commit/5734548f78b75029f49d049dcf4f3a438ddffd37
