### ISSUE TITLE
macOS 端 Tesseract OCR 安装后不识别

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7107]
https://ld246.com/article/1673932379624

问题出在 HomeBrew 安装的 tesseract 不会加入到环境变量 $PATH 中，而是创建 /usr/local/bin/tesseract 符号链接。

**Comment by Shad0wpf** [comment]
> https://ld246.com/article/1673932379624
> 
> 问题出在 HomeBrew 安装的 tesseract 不会加入到环境变量 $PATH 中，而是创建 /usr/local/bin/tesseract 符号链接。

我这安装后创建的符号链接是 /opt/homebrew/bin/tesseract

**Comment by 88250** [comment]
稍后再加一次判断吧。

**Comment by alpaca121** [comment]
临时解决方法：sudo ln -s /usr/local/bin/tesseract /opt/homebrew/bin/

**Comment by hqweay** [comment]
> 稍后再加一次判断吧。

https://github.com/siyuan-note/siyuan/blob/ff0bcce9147d3b23e1c0542bb12bd59f511b4d17/kernel/util/ocr.go#L371

在我这（macOS 26.1 (25B78)）执行文件找不到终端报错「no such file or directory」，不清楚是特例还是都这样。

**Comment by 88250** [comment]
@hqweay 麻烦发一下 Tesseract OCR 可执行文件的路径

**Comment by hqweay** [comment]
> [@hqweay](https://github.com/hqweay) 麻烦发一下 Tesseract OCR 可执行文件的路径

<img width="898" height="143" alt="Image" src="https://github.com/user-attachments/assets/dc0354ff-0668-4332-b4ec-8ffc06fd6dfc" />

我的也在`/opt/homebrew/bin/tesseract`。

目前还是手动创建符号链接`sudo ln -s /opt/homebrew/bin/tesseract /usr/local/bin/tesseract`，能正常使用。

**Comment by 88250** [comment]
从代码逻辑上看会通过 `/opt/homebrew/bin/tesseract` 兜底，并且就算没有找到的话应该也不会有报错，这里没有记录报错日志的。

<img width="904" height="610" alt="Image" src="https://github.com/user-attachments/assets/6b87db01-b9b2-4b46-94a1-7eb0289b3d21" />

你那里报错是日志上显示还是弹窗？

**Comment by hqweay** [comment]
> 从代码逻辑上看会通过 `/opt/homebrew/bin/tesseract` 兜底，并且就算没有找到的话应该也不会有报错，这里没有记录报错日志的。
> 
> <img alt="Image" width="904" height="610" src="https://private-user-images.githubusercontent.com/873584/514949671-6b87db01-b9b2-4b46-94a1-7eb0289b3d21.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzODQyOTcsIm5iZiI6MTc2MzM4Mzk5NywicGF0aCI6Ii84NzM1ODQvNTE0OTQ5NjcxLTZiODdkYjAxLWI5YjItNGI0Ni05NGExLTdlYjAyODliM2QyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QxMjUzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDQyZDUzMzQwYTRkMjM1NDk5MDQ3MGFhZDM5YWVhYjE3NzU3NTczNzQwZjJkYzZmZDJlM2RhN2I5ZjliZTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FpoA_V8rV6xxLLyz-fF7idPqEBu8XM_DD1EWHSqeXoE">
> 你那里报错是日志上显示还是弹窗？

前面是自己终端执行的报错。

https://github.com/siyuan-note/siyuan/blob/ff0bcce9147d3b23e1c0542bb12bd59f511b4d17/kernel/util/ocr.go#L371

我怀疑是这段逻辑没有走进去，刚刚测了下：

<img width="674" height="726" alt="Image" src="https://github.com/user-attachments/assets/28e1d9dc-ead3-473a-9c16-b25d4e904b6f" />

执行`/...`找不到的报错是 no such file or directory。D 大看看有没有参考意义。

**Comment by 88250** [comment]
收到，稍后我加一下判断，谢谢。
