### ISSUE TITLE
改进图片 OCR 提取文本结果中的多余字符

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7109]
* 不可见字符
* 中文之间的空格

**Comment by 88250** [comment]
6d4aa07bc76c57dd4d324645277f5cc63a9ec7d6

**Comment by Zuoqiu-Yingyi** [comment]
@88250 请问若需要对已进行 OCR 的图片重新进行 OCR, 是直接重建索引还是删除 `siyuan.db` 后再重建索引
