### ISSUE TITLE
无法成功打开文档

### ISSUE THREAD

**Issue by ChengzuHuang** [siyuan-note/siyuan#711]
### 描述问题 Describe the problem

很奇怪，有时会无法成功打开文档，但等待一段时间又好了

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
If it is a problem of parsing and rendering, please post the original Markdown here
````````

### 截屏或录像 Screenshot or video

![bug](https://user-images.githubusercontent.com/10935766/101977214-d31b5480-3c86-11eb-9630-c31e9815171a.gif)

### 版本环境 Version environment

* 版本 Version：0.5.2
* 操作系统 Operating system：Windos10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，这个问题我这里无法重现，请等待我们发布 v0.5.3 以后再帮忙留意观察。

Issue 我先关闭，如果还有反馈请继续跟帖，谢谢。
