### ISSUE TITLE
自动校验索引时排除非 id 格式的 .sy 文件

### ISSUE THREAD

**Issue by xiaoyoucheng** [siyuan-note/siyuan#7111]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

今天同步被移动端同步覆盖了，使用数据快照恢复死卡住。一直剩余待处理78.
很长一段时间后，会出现回滚数据快照失败

### 期待的结果 Expected result

可以正常使用快照恢复

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/33143581/213081481-9404b6be-b4ad-4342-87a5-8bc21debcdc6.png)
![image](https://user-images.githubusercontent.com/33143581/213086554-60bf333f-74e6-4be5-9483-8202539d1eb2.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: win10
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10442144/siyuan.log)

**Comment by 88250** [comment]
笔记本路径下不要放置非 id 格式的 .sy 文件，比如这个路径：

data\20210823141557-05j4q4t\20210823141612-phuwl3e\20211022100707-dgelby7\20210823141612-ec2lf4f\templates\Meteor\dailynote.sy

**Comment by xiaoyoucheng** [comment]
> 笔记本路径下不要放置非 id 格式的 .sy 文件，比如这个路径：
> 
> data\20210823141557-05j4q4t\20210823141612-phuwl3e\20211022100707-dgelby7\20210823141612-ec2lf4f\templates\Meteor\dailynote.sy

这已经不知道怎么来的了。 看起来是之前的模板功能留下的。我也想找到快照文件删除，发现找不到快照。

**Comment by 88250** [comment]
等下个版本再试试，我们做了些调整。

**Comment by xiaoyoucheng** [comment]
> 等下个版本再试试，我们做了些调整。

有件事我很好奇 能不能想问下，这个数据快照是不是不是我想象中的完整备份。

**Comment by 88250** [comment]
基本是的，但是会根据用户配置的 ignore 文件进行忽略，同时也会默认忽略一些文件，比如 `*.tmp`、`.` 开头的文件/文件夹、隐藏文件和符号链接，具体规则可以参考 https://github.com/siyuan-note/dejavu/blob/main/repo.go 中 `builtInIgnore` 函数源码。

**Comment by xiaoyoucheng** [comment]
> 基本是的，但是会根据用户配置的 ignore 文件进行忽略，同时也会默认忽略一些文件，比如 `*.tmp`、`.` 开头的文件/文件夹、隐藏文件和符号链接，具体规则可以参考 https://github.com/siyuan-note/dejavu/blob/main/repo.go 中 `builtInIgnore` 函数源码。

好的，谢谢解答。
