### ISSUE TITLE
改进内核任务调度机制提升稳定性

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7113]
在用户在相继执行一些耗时操作后容易导致竞态，虽然之前通过一些锁尽量避免竞态，但是随着业务操作种类的增加，难免会遗漏处理一些场景，从而导致系统不稳定报错，这部分实现代码的维护也较为困难。

需要一个统一的任务调度机制来确保可能导致竞态操作的序列化执行，比较好的实现方式就是使用队列，将较为耗时且可能并发的操作按顺序阻塞执行，目前包括：

* 数据同步
* 快照恢复
* 数据索引
* 索引校验
* 图片 OCR 提取文本
* 嵌入块索引 https://github.com/siyuan-note/siyuan/issues/7112

**Comment by Soltus** [comment]
点赞
