### ISSUE TITLE
命令搜索框

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#7116]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

通过搜索命令即可找到对应的动作，如搜索 Find 可选择查找功能，无须背快捷键

### 描述可能的最优解决方案 Describe the optimal solution

类似 Intellij IDEA 的 search action, vscode cmd-shift-p

**Comment by Soltus** [comment]
类似于：

- [ ] https://github.com/Hi-Windom/Sillot/issues/48

**Comment by 88250** [comment]
这个需要先抽象出 Action，目前思源里面还没有这个概念，预计要等设计 #7090 时一并考虑，感谢提议。
