### ISSUE TITLE
撤回时页面会向上滚动一大截

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#712]
### 描述问题 Describe the problem

按Ctrl+Z撤回时页面会向上滚动一大截

### 期待的结果 Expected result

页面应停留于原位置

### 截屏或录像 Screenshot or video

![bug6](https://user-images.githubusercontent.com/30611816/101979878-d79e3800-3c9b-11eb-8f44-15bade598925.gif)

### 版本环境 Version environment

* 版本 Version：0.5.2

### 其他信息 Other information

滚动相关issue: #653  ~~#554~~ (已修复)

**Comment by Vanessa219** [comment]
由于嵌入块会加载，因此只能保证光标位置。
