### ISSUE TITLE
Android 端前后台切换时自动触发同步

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7122]

**Comment by Soltus** [comment]
安卓端内核驻留能力能不能加强一下，伺服网页时切个后台内核很容易失去链接

**Comment by 88250** [comment]
> 安卓端内核驻留能力能不能加强一下，伺服网页时切个后台内核很容易失去链接

这个没办法的，各种系统不允许保活的。

**Comment by heimi98** [comment]
ipad 端也要优化，用苹果的一般不会手动杀后台。
