### ISSUE TITLE
改进关闭笔记本体验

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7124]
放到后台任务中执行，减少界面卡顿感。

**Comment by Soltus** [comment]
再等一个打开笔记本支持并发，那虚拟空间就有望了啊

**Comment by GH-W94** [comment]
> 再等一个打开笔记本支持并发，那虚拟空间就有望了啊

虚拟空间是什么意思？

**Comment by Soltus** [comment]
> 



> > 再等一个打开笔记本支持并发，那虚拟空间就有望了啊
> 
> 虚拟空间是什么意思？

好东西
