### ISSUE TITLE
导入md 文件时自动识别双链

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7127]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

导入其他双链笔记的 md 文件时，将 [[ ]] 包裹的文字识别为双链。

### 描述可能的最优解决方案 Describe the optimal solution

导入其他双链笔记的 md 文件时，将 [[ ]] 包裹的文字识别为双链。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/3557
