### ISSUE TITLE
Support ARM architecture on macOS (Apple Silicon)

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#713]
![image](https://user-images.githubusercontent.com/873584/101980003-fa7d1c00-3c9c-11eb-986a-3af0277e8111.png)

https://tip.golang.org/doc/go1.16#darwin

https://github.com/golang/go/issues/39782

**Comment by wizyoung** [comment]
any progress?

**Comment by 88250** [comment]
@wizyoung Thanks for reminding, we will test it in the near version.

**Comment by wizyoung** [comment]
The arch still shows "Intel". Will there be a universal release in the near future?
