### ISSUE TITLE
内核中断报错等其他任何报错后，阻止编辑但允许复制，抢救当前编辑文本

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7130]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

报错后会弹出遮盖层，虽然知道目的是阻止继续编辑以免造成更大的问题，但很大概率重启后正在编辑块的文本会丢失。所以希望可以阻止编辑但允许抢救性复制。

### 描述可能的最优解决方案 Describe the optimal solution

允许抢救性复制！

### 描述候选的解决方案 Describe the candidate solution

允许抢救性复制！！

**Comment by yixna** [comment]
点赞

**Comment by 88250** [comment]
这个目前没有好的办法，只能弹层遮盖整体界面，如果有其他办法的话欢迎提出。

**Comment by UFDXD** [comment]
让可以让拖动啊，自己截图啊，不难吧，眼睁睁的看有可能丢东西这种感觉简直原地爆炸好吧！

**Comment by UFDXD** [comment]
顺手改一下吧，可以不作为更新内容展示。

**Comment by 88250** [comment]
内核中断的弹框不行，重建索引的弹框可以 Esc 取消。
