### ISSUE TITLE
编辑器的几个问题及其特性提议

### ISSUE THREAD

**Issue by LeeOswald368** [siyuan-note/siyuan#7131]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

1. 图片全屏播放时需要点击两次，第一次点击为思源窗口扩大到全屏，隐藏任务栏，第二次点击才能进入全屏播放界面。
    （使用主题为：Savor，软件版本为：2.7.0 ，切换到默认主题后并重启软件，依然出现该问题）
    我并不确定是否为编辑器特性。但我并没有找到更新日志中有关这一特性的描述。记得上一个版本是可以直接进入全屏播放界面。
    问题复现：
    https://user-images.githubusercontent.com/120121713/213553214-f495edc1-e99a-4f28-b662-595abc260fed.mp4

2. 图片全屏播放时，只有固定时间的播放。建议增加左右键切换功能。
    图片全屏播放从某种角度上来说也是聚焦的一种方式，虽然双击图片会聚焦于单张照片，但是受限于图片周围背景和文字的干扰，图片全屏播放的聚焦性更强一点，同时思源本身没有提供对全屏播放时间间隔的控制，因此感觉有必要对图片全屏播放功能有所加强。无论是Windows的自带图片查看软件和office的 power point 都给予用户在全屏播放时可以通过左右键进行切换的操作。

3. 内容块拖动时增加鼠标滑轮的操作。
    目前，在使用的笔记软件中，只有onenote可以。
    特性想法来源：某一次在攥写某个游戏攻略时，由于表格过长，对此需要排版，下意识的将内容块点击拖动到某个表格下面（表格并未出现在当前视野），发现鼠标中键无法滑动，最后只能通过笔记本的触屏功能拖动成功。（同时也因为，好像上一个版本，无法通过拖动内容块到一个超长表格下面，只有放置在上方的选项操作，但当前版本可以）
    虽通过剪切和复制同样可以达到此目的，当前并不影响使用，但是我想有助于增加编辑器体验，于是提出。
    问题复现：
    https://user-images.githubusercontent.com/120121713/213553219-e58e9650-1067-450e-b234-6bb1db4da9ce.mp4
    
4. 在某种情况下，表格会自动折叠。
    个人觉得，出现问题的表格是由于单个表格过长导致的，且在默认主题下依然重现。
    问题复现：https://user-images.githubusercontent.com/120121713/213553224-c62a9586-5b46-43ef-8cf2-559706c10a61.mp4

5. 资源文件的导出不应该仅限于图片格式。
    思源，对于我来说不仅仅是作为文字、笔记写作软件，同时他也是我的文档，PDF存档的一部分。大纲、双链等只是软件的特性。它可以是我的笔记记录、复习，同时也是我的生活中的记录器。因此，导入的文件不仅有图片格式，甚至有zip，rar，pdf等。但是都无法进行导出，只能通过定位文件当前位置，再从assets导出，同时assets中的文件加了很多后缀，因此文件拖出后还需要重命名。

6. 图片重命名更改一次就需要重写数据。若对大量图片进行重命名，则需要非常多的时间，同时多次进行重命名后，软件重启与打开多次会造成软件性能下降。
    这里有几个点，我想说明。
    (1). 为什么不在导入思源之前就对文件进行重命名？
     因为电脑系统不允许重名文件的出现，必须要加后缀。而思源导入的图片文件，会在图片文件后面加后缀，这样就可以在思源里面不同文件有相同的名字。因此便利了我在插入资源的时候，判断这个东西属于哪一个板块下的文件，而某些板块下的资源并不需要明确的区分1，2，3，4。
    (2). 不仅是图片，其他资源文件重命名都会重新写入数据并重启软件。
    (3). 目前思源对重命名后的文件是新建一个重命名后的同样的文件，但后缀不同，原有资源文件依然存在，但不再被引用，因此我觉得是否有方法可以解决在某种情况下对大量资源文件重命名时，后台重新写入数据或者重命名完后集体写入。
    (4). 可能surface go真的太垃圾了。多次数据写入重启后，思源会有明显卡顿的感觉。我导入的漫画图片动不动20张以上，每一次重新写入然后重启，我真的想死。

7. 双击图片后，图片下方文本名待优化。
    双击图片进入单个图片放大模式后，下方的文件名是asset中完整的文件名。
    既然，在资源插入中，文件后缀不会出现，图片导出后，图片资源文件同样不会有后缀，那么那个超长的英文和数字夹杂的文件名会有人注意到吗？可以优化成“当前文件名字.png or jpg”（不加后缀的）

8. assets文件有想过调整吗？
    电脑性能太低，OneDrive中视频若是以大图标排列的话，即使就几百个文件点进去的瞬间都会有点卡顿。目前我思源assets文件已经有450多个文件了，虽然现在并不算卡顿。但已经坚定选用思源后，文件会越来越多，有考虑不同资源文件调整到不同笔记文件下吗？而assets文件储存类似于ocr识别结果这些编辑器内部功能文件。
        ~感觉努力赚钱买新电脑才是正道。~

9. 工作空间添加重命名按钮，如果仅有一个工作空间，更改后自动加载新更名后的工作空间。
    简化操作。

10. 数据快照中支持单个页面的回滚。
      有一次在使用S3同步的时候，由于手机端的内容长期没有更新，内容是旧的，我想单纯的删掉手机端的内容然后点击进行拉取同步，但这个操作删掉了我在电脑上的所有笔记。
      虽然通过数据快照恢复了。后期在查找笔记时发现，有几篇并没有回来，但在对比不同时间的数据快照里发现了那几篇文章，但是由于我的笔记写了新的内容，如果全部回滚，新的内容将会被覆盖，所以处在很纠结的状态，虽然只有几篇，重写就回来了。

11. 所以当前的思源同步逻辑是这样的吗？
      电脑端上传到服务器后，手机端在打开的时候会有一个拉取数据同步的操作，同步完成后进入思源手机端编辑（或笔记）界面，通过编辑后点击立即同步，然后传到服务器，而电脑端想要接收这一新的数据，是必须要重启软件，进行下载数据然后进入操作界面还是点立即同步去拉取这个新的数据？
      为什么，手机端在拉取到新的数据之后，原有在电脑端上删除的笔记（即手机端还未更新前的旧笔记），在手机端还存在？

### 描述可能的最优解决方案 Describe the optimal solution

都是些日常使用中感觉可以优化的地方。仅为建议。

### 其他信息 Other information

祝思源笔记越来越好。

**Comment by 88250** [comment]
1. 这个一直是这样的，设计如此
2. 暂时不考虑支持了
3. 分屏后拖拽
4. 父层级的标题展开会将同时展开子级标题，折叠不是独立的，这个是设计如此
5. 导出 PDF 时可以选择带 assets 导出，ID 后缀无法去掉，否则可能会重名
6. 请关注 https://github.com/siyuan-note/siyuan/issues/7133
7. 请关注 https://github.com/siyuan-note/siyuan/issues/7134
8. 这个不考虑了，统一存放在 assets 文件夹下是最优解
9. 不考虑了，会有其他问题，且重命名工作空间不是高频操作
10. 暂时不考虑了，如果有更多反馈需求我们再考虑
11. 不要多个设备同时在线，否则会发生不可预期的同步结果，同步原理可参考用户指南云端同步章节

感谢反馈。
