### ISSUE TITLE
Add API for open document

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#7132]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前各种插件/挂件，打开新笔记的方式都是使用`siyuan:\\`拉起新页面，在本地使用没什么问题，但是无法在伺服的情况下使用

### 描述可能的最优解决方案 Describe the optimal solution

为document提供一个open的API，类似于[API-open-a-notebook](https://github.com/siyuan-note/siyuan/blob/master/API.md#open-a-notebook)的实现：

### Open a notebook

* `/api/notebook/openDocument`
* Parameters

  ```json
  {
    "document": "20210831090520-7dvbdv0"
  }
  ```

    * `document`: Document ID
* Return value

  ```json
  {
    "code": 0,
    "msg": "",
    "data": null
  }
  ```

### 描述候选的解决方案 Describe the candidate solution

网页端支持识别`siyuan:\\`?
网页伺服支持使用`?page`类似的字段进行跳转？

感觉都不如API来的简便

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5066
