### ISSUE TITLE
左右分屏后，鼠标（光标）不能移动到行尾

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7135]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

1、左右分屏后，鼠标（光标）不能移动到行尾，能否修正一下，谢谢！
2、左右分屏后，编辑框右侧的Ctrl+Home，Ctrl+End两个箭头能否去掉，右侧已经有滚动条了，添加后页面不够简洁（这两个都是常用快捷键，也没必要提示），或离编辑框远一写，且图标换的明显一点。不然很容易误点击，还不能用Ctrl+Z或回退按钮找到原来的位置。这样分屏页面能够延续单个页面的编辑体验，对用户友好。

### 描述可能的最优解决方案 Describe the optimal solution

希望分屏页面能够完全延续单个页面的编辑体验，简洁实用，不需要另外再注意什么。

### 其他信息 Other information

辛苦了！

**Comment by pisceswb** [comment]
左右分屏，若拖动中间条改变左右的窗口大小，则放大的那一个窗口，两侧会出现很大的留白位置，能否优化一下，谢谢！

**Comment by 88250** [comment]
第二个不考虑改了，这个是根据前期长期反馈才决定加上的。

**Comment by 88250** [comment]
> 左右分屏，若拖动中间条改变左右的窗口大小，则放大的那一个窗口，两侧会出现很大的留白位置，能否优化一下，谢谢！

设置编辑器自适应宽度

**Comment by pisceswb** [comment]
> 第二个不考虑改了，这个是根据前期长期反馈才决定加上的。

那能够把箭头和正文分开一些，如果鼠标能够选中行尾的话，可能误触的现象更容易发生了。
谢谢！！

**Comment by pisceswb** [comment]
> 

已经设置了自适应宽度

**Comment by 88250** [comment]
截图看下吧，不太清楚你的意思。

**Comment by pisceswb** [comment]
> 截图看下吧，不太清楚你的意思。

![image](https://user-images.githubusercontent.com/104658457/213614537-3a81cbf3-daa7-4937-9402-ff8c537c4327.png)
![image](https://user-images.githubusercontent.com/104658457/213614571-11215b58-9aef-454e-ade5-9180b09d8a91.png)

**Comment by pisceswb** [comment]
> 第二个不考虑改了，这个是根据前期长期反馈才决定加上的。

能否设置一个是否启用这个箭头的选项，确实很影响文字的选中体验
![image](https://user-images.githubusercontent.com/104658457/213614655-9963dac5-4ec7-4089-a074-4532f4147625.png)

**Comment by 88250** [comment]
两侧需要一定宽度的留白，不然菜单可能会有问题。

**Comment by 88250** [comment]
暂时不考虑加选项了，如果一定要选中的话可以试试键盘操作。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by GH-W94** [comment]
右侧的这两个箭头确实挺烦人的，能否将这两个箭头在垂直方向上的激活范围缩小一下并移到页面偏底部，这样可以在选不中行末尾的文字时，滚动鼠标将文字移出激活范围，就可以选中了。

**Comment by pisceswb** [comment]
> 暂时不考虑加选项了，如果一定要选中的话可以试试键盘操作。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

D大好，我描述一下右侧这两个箭头的使用步骤：
鼠标移动到窗口右侧特定位置，使两个箭头显示出来 → 鼠标再移动到箭头上点击 → 跳到页首或页尾后，不能回退返回原位置。

该功能与滚动条的功能重复，感觉滚动条就已经很方便很符合大众的使用习惯了，且也有快捷键可用。还影响文字的编辑选中，时不时就会不小心触发弹出（因为位置在屏幕中间，编辑时使用最多的位置），感觉这两个箭头不是大部分用户的功能需求。

虽然您暂时不考虑更改了，但还是建议您以后有空时能够再考虑一下，虽然是个小问题。
另外提一个建议，以后把您觉得不太常用或比较小众的功能，能否做成插件类的东西，让有需要的用户自己选择使用。感觉窗口干净清爽，所见功能都方便实用对一个软件是很重要的。

祝思源笔记越来越好！

**Comment by pisceswb** [comment]
在右侧滚动条的顶部、底部分别添加一个按钮（类似于“win11的记事本”），点击按钮向上或向下翻一页，双击按钮跳转到页面顶部或底部。感觉这个会比现有的占用编辑框区域，影响编辑体验的右侧Ctrl+Home、Ctrl+End箭头要好。D大后期可以考虑一下

![image](https://user-images.githubusercontent.com/104658457/213638226-b21ab64e-820d-4d1b-8dc3-9602196bc305.png)

**Comment by GH-W94** [comment]
> 在右侧滚动条的顶部、底部分别添加一个按钮（类似于“win11的记事本”），点击按钮向上或向下翻一页，双击按钮跳转到页面顶部或底部。感觉这个会比现有的占用编辑框区域，影响编辑体验的右侧Ctrl+Home、Ctrl+End箭头要好。D大后期可以考虑一下
> 
> ![image](https://user-images.githubusercontent.com/104658457/213638226-b21ab64e-820d-4d1b-8dc3-9602196bc305.png)

这个解决方案也不错

**Comment by Soltus** [comment]
> 在右侧滚动条的顶部、底部分别添加一个按钮（类似于“win11的记事本”），点击按钮向上或向下翻一页，双击按钮跳转到页面顶部或底部。感觉这个会比现有的占用编辑框区域，影响编辑体验的右侧Ctrl+Home、Ctrl+End箭头要好。D大后期可以考虑一下
> 
> ![image](https://user-images.githubusercontent.com/104658457/213638226-b21ab64e-820d-4d1b-8dc3-9602196bc305.png)

自行使用CSS实现即可，类似Sofill-主题这样：
![image](https://user-images.githubusercontent.com/83791825/213651840-7a6caae2-2f94-4215-9850-8b9399dd75db.png)

**Comment by pisceswb** [comment]
> > 在右侧滚动条的顶部、底部分别添加一个按钮（类似于“win11的记事本”），点击按钮向上或向下翻一页，双击按钮跳转到页面顶部或底部。感觉这个会比现有的占用编辑框区域，影响编辑体验的右侧Ctrl+Home、Ctrl+End箭头要好。D大后期可以考虑一下

> 
> 自行使用CSS实现即可，类似Sofill-主题这样：

我并不是想要这个功能，是想去掉现在编辑框中的这个箭头，因为他遮挡了编辑的文本内容了。请问能否有CSS能够实现去掉这个箭头的功能？谢谢！

![6f5fc6dafad5a585a092b59209b03c25_213614655-9963dac5-4ec7-4089-a074-4532f4147625](https://user-images.githubusercontent.com/104658457/213690080-bf8b3e82-65e0-448c-a53f-9405646a880a.png)

**Comment by pisceswb** [comment]
@Soltus 经过尝试，使用CSS完美解决问题，谢谢提供思路。
.protyle-scroll {
    position: absolute;
    right: 0;
    height: 0;
    top: 0;
    width: 0px;
    padding: 0 0px;
}

**Comment by pisceswb** [comment]
.protyle-scroll {
    display:none;
}
