### ISSUE TITLE
v2.7.1-dev1 面包屑点击无反应，无法聚焦

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7138]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![问题](https://user-images.githubusercontent.com/97731736/213773635-213271f9-1225-45fb-af6f-648b4a46bb88.gif)

### 期待的结果 Expected result

修复

### 版本环境 Version environment

```markdown
- Version: v2.7.1-dev1

- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
感谢反馈，合并到 https://github.com/siyuan-note/siyuan/issues/7113 中处理。
