### ISSUE TITLE
可以把左上角的思源图标换成日历面板吗？

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7139]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

日历这个功能，在其他双链笔记里面全部都有，但是思源不知道是出于什么原因，一直都没做

这就导致查看过去日历不太方便，也就没有太大动力去翻以前的dailynotes

### 描述可能的最优解决方案 Describe the optimal solution

日历模块其实能附带的功能和创造的便利是挺多的。
* 日历除了快捷查看过去的笔记，增加翻阅往期dailynotes的频率（如果思源支持创建未来的dailynotes的话，还可以达到给未来写信的效果）
* 还可以通过给日历中日期加标记，来对某一天进行标记（是否关键，是否有特殊的事情发生，当天的心情如何等等标记功能）
* 还可以通过日历日期的颜色，快速浏览哪一天的待办列表还未完成（比sql块搜索亲民，方便，够用）
* 还可以切换成统计面板，查看每一天的码字数量和热力图
* 当然还有日历最基本查看节假日，日期的功能。

不知道开发者为什么就是不做这个功能，可能觉得日历用处不大吧，但是现在左上角的这个思源图标是纯纯地占位子

**Comment by 88250** [comment]
目前没有时间支持日历，还是得靠社区扩展，左上角图标目前还没有想好具体的改进，有可能会先直接去掉。
