### ISSUE TITLE
能否增加左右侧边栏收起按钮

### ISSUE THREAD

**Issue by mzcxiaohuanxiong** [siyuan-note/siyuan#7141]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当分屏或在不同分辨率显示器编辑时，为扩大编辑区空间，需要收起侧边栏，但现在只能点击每一个展开的项目（文档树，大纲，标签等）。不方便。

### 描述可能的最优解决方案 Describe the optimal solution

在左右侧边栏附近各增加一个收起按钮。

**Comment by mozhux** [comment]
可以直接 alt+y实现你的要求

**Comment by 88250** [comment]
请用面板对应的快捷键。
