### ISSUE TITLE
自定义Emoji名字有空格，正文中无法正常显示

### ISSUE THREAD

**Issue by LeeOswald368** [siyuan-note/siyuan#7143]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

自定义Emoji名字有空格，正文中无法显示表情

### 期待的结果 Expected result

正常显示表情

### 截屏或者录屏演示 Screenshot or screen recording presentation

![微信截图_20230122043858](https://user-images.githubusercontent.com/120121713/213886287-a584ed74-3ace-4635-b766-7648a1214b6f.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: Windows
- Browser (if used):
```

### 日志文件 Log file

I 2023/01/22 04:31:11 runtime.go:46: kernel is booting:
    * ver [2.7.0]
    * arch [amd64]
    * pid [11892]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_2.7.0.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\LeeOs\Documents\东]
I 2023/01/22 04:31:11 conf.go:227: using Microsoft Store edition
I 2023/01/22 04:31:11 conf.go:317: user has disabled [Google Analytics]
I 2023/01/22 04:31:11 runtime.go:91: use network proxy [system]
I 2023/01/22 04:31:11 serve.go:111: kernel [pid=11892] http server [127.0.0.1:1219] is booting
I 2023/01/22 04:31:11 working.go:396: built-in pandoc [ver=2.19.2, bin=C:\Users\LeeOs\Documents\东\temp\pandoc\bin\pandoc.exe]
I 2023/01/22 04:31:11 sync.go:81: sync before boot
I 2023/01/22 04:31:11 tesseract.go:135: tesseract-ocr enabled [ver=v5.3.0.20221214, langs=chi_sim+chi_sim_vert+chi_tra+chi_tra_vert+eng]
I 2023/01/22 04:31:13 repository.go:821: boot get sync cloud files elapsed [1.58s]
I 2023/01/22 04:31:13 conf.go:616: database size [20 MB], tree/block count [114/4408]
I 2023/01/22 04:31:13 working.go:157: kernel booted
I 2023/01/22 04:31:13 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/01/22 04:32:13 box.go:80: auto stat [trees=114, blocks=4408, dataSize=4.5 GB, assetsSize=4.5 GB]
I 2023/01/22 04:32:13 disk.go:33: disk usage [total=101 GB, used=95 GB, free=6.1 GB]
I 2023/01/22 04:32:57 repository.go:922: synced data repo [provider=2, ufc=2, dfc=0, ucc=1, dcc=0, ub=29 kB, db=51 kB] in [3.97s]
I 2023/01/22 04:33:50 repository.go:922: synced data repo [provider=2, ufc=1, dfc=0, ucc=1, dcc=0, ub=28 kB, db=51 kB] in [3.28s]
I 2023/01/22 04:39:26 repository.go:922: synced data repo [provider=2, ufc=1, dfc=0, ucc=1, dcc=0, ub=28 kB, db=51 kB] in [3.29s]

**Comment by 88250** [comment]
这个无法支持，只能去掉空格。
