### ISSUE TITLE
通过拖拽到页签移动内容块

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7144]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在记笔记时，会把一些常用的文档钉在页签上常驻

平常记笔记，会quickadd快捷记录在dailynote上，

在进行整理的时候，不管是通过反链传递，还是通过复制粘贴，都需要在两篇文档间切换。但是对于常驻文档，文档的页签就在上面。

希望能够通过拖拽块到页签的方式，不用切换，不用搜索，直接将内容传递到钉住的文档中。

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/37429029/213897615-629ccce9-5b08-420f-92dd-745ab7e85b76.png)

**Comment by AugustTuan** [comment]
【拖拽笔记到页签】和【钉住页签】功能搭配使用，实现多个笔记间不需要通过分屏、搜索、切换文档也可以快速传递信息

**Comment by Yuminis98** [comment]
支持，这个想法和thebrain里面的操作类似

**Comment by Yuminis98** [comment]
再加上思源的文档块和标题块是互相可以转换的。
甚至可以把一个标题块钉在顶部页签栏，然后将内容快拖拽过去，就自动收入该标题，

**Comment by pisceswb** [comment]
能否实现将顶部页签拖拽到编辑页，插入链接？
能否其它页面的块按着ctrl拖动时，在新位置插入链接？

**Comment by 88250** [comment]
> 能否实现将顶部页签拖拽到编辑页，插入链接？ 
> 能否其它页面的块按着ctrl拖动时，在新位置插入链接？

* 这样的话就没法拖拽分屏了
* 这是复制块

**Comment by Chenmo1212** [comment]
> 

我刚想把侧边栏的文章拖到一个新的内容块企图作为引用，结果导致把原来的文章全部【移动】到内容块里了。我在撤销后重做，直接导致原来的文章消失了。siyuan目前的这种交互，是否会存在文章丢失风险很高的问题？这个交互与用户第一反应的交互完全不一样，而且文章直接丢失是否会不是很妥当？

**Comment by 88250** [comment]
这个提议暂时不考虑了，因为这个拖拽操作比较隐晦，暂时还是通过移动功能完成吧。
