### ISSUE TITLE
引用边界字体问题

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7145]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

在锚文本附近打字的时候，输入提示法和锚文本的字体一致，
导致我以为自己在修改锚文本，实际上打出来的字体确实正文

### 期待的结果 Expected result

在锚文本附近码字，输入法提示显示正文字体而不是有误导性的锚文本字体

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Snipaste_2023-01-22_10-21-55](https://user-images.githubusercontent.com/37429029/213897799-c0e88d6e-6ee1-4e75-a6c8-53c8590b3198.png)
![Snipaste_2023-01-22_10-22-09](https://user-images.githubusercontent.com/37429029/213897803-0fa613f7-ca7a-4885-85d4-1f30d56d7568.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10473593/system-log.zip)

**Comment by AugustTuan** [comment]
拖拽笔记到页签和钉住功能搭配使用，实现多个笔记间不需要通过分屏、切换文档也可以快速传递信息

**Comment by 88250** [comment]
这个通过样式不太好区分，建议使用右键修改锚文本。
