### ISSUE TITLE
/功能页面的交互需要优化，否则会影响正常的码字

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7147]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

当码字时，键入”/“ 会跳出功能页面，这虽然会对码字产生一定的干扰，但是问题不大

但是，当用户在跳出功能页面后，没有进行功能页面的选择，而是继续输入了文字。

这种情况下，就说明，用户并不想使用功能页面，

这里就系统应该就自动关掉功能页面，而不是继续显示功能页面并且处于选中状态，否则就会干扰正常的码字

比如录屏，输入I/O回车，出现的效果就不是在一个编辑器上正常码字的效果

### 期待的结果 Expected result

方案1：用户键入/后，继续键入其他文字，功能界面自动关闭
方案2：用户键入/后，弹出功能页面，但是不要选中。

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/37429029/213898896-d1338691-cf7d-4435-ad5b-02fc01db1317.mp4

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10473644/system-log.zip)

**Comment by Soltus** [comment]
建议桌面端改为 ctrl + / 调出功能面板，移动端不变
