### ISSUE TITLE
支持以数字角标的方式，统计子列表的数量

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7148]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有的时候，需要统计一个列表下面有多少列表项，
如果列表项过长的话，现在只能一个一个地数

希望可以在父列表处，增加一个角标来统计该列表一共有多少列表项

### 描述可能的最优解决方案 Describe the optimal solution

![Snipaste_2023-01-22_11-24-55](https://user-images.githubusercontent.com/37429029/213899166-7461bcc6-d68a-4ace-a517-6221ec1fcb2c.png)

**Comment by 88250** [comment]
这个暂时不考虑了，感谢提议。
