### ISSUE TITLE
右上角新增文档的位置和块引新建文档存放位置统一

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7149]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在点击右上角新增文档，文档会默认创建在和当前文档的同一个目录下。（但是实践上，这种f方式创建的文档，往往都和当前文档没有关联，因为有关联，就会用引用创建， 都是突发奇想，要创建一个别的文档）
![image](https://user-images.githubusercontent.com/37429029/213899582-8ba7c0f9-f610-40e3-83b3-2b105558b819.png)

由于平常，主要都是在dailynotes编写文档，这样就会导致很多创建的文档和dailynote参杂在一起，如图，导致我只能定期的手动地移动新建的文档
![Snipaste_2023-01-22_11-38-07](https://user-images.githubusercontent.com/37429029/213899437-2eee16de-b543-4a50-9efc-f9562e82a3a4.png)

### 描述可能的最优解决方案 Describe the optimal solution

希望，右上角创建的新文档能够像笔记本设置那样，进入到指定的目录下面，统一存放
![Snipaste_2023-01-22_11-40-06](https://user-images.githubusercontent.com/37429029/213899507-186cc09d-249b-43ca-9629-cd1329b02fab.png)

![Snipaste_2023-01-22_11-38-17](https://user-images.githubusercontent.com/37429029/213899495-da772912-a35c-4147-a9b4-8a94b1e1d90e.png)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/4494

**Comment by AugustTuan** [comment]
作为需求反馈者，在思源反馈上，感觉到了一些两难的点。

1. 明明有需求的人懒得提需求；在平常qq群里面交流发现这样一个现象，对于一些不是明显影响操作的问题，很多人都发现了，但是最后大家都在等着别人去提。这就导致虽然提议的人只有一个，但是拥有这个需求的人其实有很多。
2. 论坛得不到开发者本尊回复；讨论火热论坛上面讨论的人比较多，但是经常提出一个需求，虽然在论坛上得到了很多用户的拥趸，但是经常得不到开发者本尊的回复（因为开发者精力是有限的，没办法每天都去回复），但是一条被用户拥趸却得不到开发者回复的需求提议就是一条无效的提议
3.没有一个科学的需求人数统计；github上肯定能得到开发者的答复，但是访问人相对来说又非常少，很多人都被挡住了。
就算是插件这种非常热门的功能，也可能就2，30个讨论，很多还是同一个人发的，我在github上面的一些反馈，就会因为同时间提的人少而被拒绝。

这三个问题联合作用一起，让我觉得很蛋疼。

**Comment by 88250** [comment]
不管是论坛还是 GitHub Issues，基本所有提议和反馈我们都看的，但是不一定能立即得到回复，因为需要时间考虑，也需要进一步收集反馈。

**Comment by AugustTuan** [comment]
> 不管是论坛还是 GitHub Issues，基本所有提议和反馈我们都看的，但是不一定能立即得到回复，因为需要时间考虑，也需要进一步收集反馈。

好的，所以这么说，论坛虽然不一定会回复，但是一定会看的话，
那还是去思源论坛提议比较好，至少能有更多用户在下面讨论。

**Comment by 88250** [comment]
谢谢。
