### ISSUE TITLE
请输入问题报告标题 Please enter the title of the bug report

### ISSUE THREAD

**Issue by Joker-lkc** [siyuan-note/siyuan#7150]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

2.7.0.1测试版
无法上传图床
无法识别网络图片链接为图片（被识别成链接）

### 期待的结果 Expected result

能够一次上传图片至图床
能够识别网络图片

### 截屏或者录屏演示 Screenshot or screen recording presentation

2.7.0.1测试版
无法上传图床
无法识别网络图片链接为图片（被识别成链接）

### 版本环境 Version environment

```markdown
- Version: 2.7.0.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

2.7.0.1测试版
无法上传图床
无法识别网络图片链接为图片（被识别成链接）

**Comment by Joker-lkc** [comment]
https://i0.hdslb.com/bfs/bangumi/image/e9ad30dd6f8fa74df16c62de048e35dd5d7ffda1.png@268w_358h.webp

**Comment by Joker-lkc** [comment]
视频传不上来 录了一个

**Comment by 88250** [comment]
抱歉，我没看明白你指的问题，录屏好像是个静态图。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Joker-lkc** [comment]
我去论坛上提问吧 github放不了视频

**Comment by Joker-lkc** [comment]
https://ld246.com/article/1674395216191
