### ISSUE TITLE
引用文档时带图标

### ISSUE THREAD

**Issue by Cyber-Syntax** [siyuan-note/siyuan#7152]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

When using the Dashboard for pages.

### 描述可能的最优解决方案 Describe the optimal solution

Copy and paste references with icons.

### 描述候选的解决方案 Describe the candidate solution

I just want to copy the page reference with their icons.

**Comment by 88250** [comment]
Sorry, it is not possible to have a document icon when referring a document.
