### ISSUE TITLE
书签和标签重命名、删除不再需要等待数据写入

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7154]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

**现在只要删一个标签，就会重新加载一次数据，基本都在5~10s
我现在大概要批量删除多余的50多个标签，要坐在这操作十分钟。。。。😭**
![image](https://user-images.githubusercontent.com/37429029/214000503-5eb819b5-720c-4339-8104-d6740385e249.png)

### 期待的结果 Expected result

支持多选标签，进行批量删除。删除多个标签只用触发一次数据重载

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

x

**Comment by 88250** [comment]
多选操作暂时不考虑支持了，我们改为“标签重命名和删除不再需要等待数据写入”

**Comment by AugustTuan** [comment]
> 多选操作暂时不考虑支持了，我们改为“标签重命名和删除不再需要等待数据写入”

谢谢

**Comment by Yuminis98** [comment]
你好为什么，我现在是最新版本，每删一个标签还是要加载半天
![image](https://user-images.githubusercontent.com/117956441/224545426-b5e3c067-8824-4c92-a080-9342a69e7785.png)

**Comment by Yuminis98** [comment]
删一个标签要等好一会

**Comment by Yuminis98** [comment]
我是2.7.9版本

**Comment by 88250** [comment]
如果删除的标签在很多文档中用过的话只能等待一下了。

**Comment by Yuminis98** [comment]
> 如果删除的标签在很多文档中用过的话只能等待一下了。

https://user-images.githubusercontent.com/117956441/224550069-c664a291-bc2d-4c5f-b680-518876b6a7c9.mp4

你看，这个标签只有1个位置用，但是删一次就要把笔记刷新一次。

可以像重建索引那样，不打断用户的操作，后台进行吗？

或者我删除了以后，就显示已经删除了，等我下次关闭软件的时候，再批量给我删掉🥹

**Comment by Yuminis98** [comment]
另外，请问标签树的操作逻辑可以和文档树一样，也支持在标签树上创建标签结构吗？
比如我记日记的时候，经常会在旁边加上描述自己心情的标签。

按理说，我应该是在标签树创建一个心情标签，然后再心情标签下面建立开心、难受这样的心情标签。
但是思源只能通过父标签/子标签这种形式，在文档种创建结构。
但是我现在每次都需要输入心情/难受，心情/开心。

心情本身只是一个说明标签分类的结构描述，对于笔记文本来说是纯粹的冗余信息，也使得操作更加麻烦。😭
![image](https://user-images.githubusercontent.com/117956441/224550494-778ec4b2-b494-4d88-a5fd-275c4bf859f0.png)

**Comment by 88250** [comment]
* 暂时没有好的方案，主要是查询标签这里需要等待之前删除写入后再展示，否则数据会不一致
* 第二个问题你可以试下文档标签，这样正文中就不用出现标签内容了

**Comment by Yuminis98** [comment]
> * 暂时没有好的方案，主要是查询标签这里需要等待之前删除写入后再展示，否则数据会不一致
> * 第二个问题你可以试下文档标签，这样正文中就不用出现标签内容了

用文档标签，标签不出现在正文，我就不知道这个标签的出处在哪里了。 
比我的dailynotes里面有上百行，然后我打了一个难受的文档便签，但是我以后回来看这个文档，我就会不知道具体是什么事情让我难受了。

我用标签是用来取代一部分引用的。
因为我想起到标识和统计的作用，但是又不想创建很多的文档。这个时候我就用标签代替。比如前面说的不同的心情，我不想给每一种心情都单独去创建一个文档。

所以标签和内容需要挨在一起，就像引用和文本挨在一起一样。

**Comment by 88250** [comment]
那就还是只能写在内容块里了，不需要树形的话就用平铺标签吧，减少层级分类带来的困扰。

**Comment by Yuminis98** [comment]
> 那就还是只能写在内容块里了，不需要树形的话就用平铺标签吧，减少层级分类带来的困扰。

也行，谢谢D大耐心解答，
我最后想问一下，就是这个标签，每删一次就要刷新一次笔记，确实打断操作。
这个issue的发起者说的，【多选标签，然后删除】，感觉是挺好的解决方案，这个也无法实现吗？(┬┬﹏┬┬)(┬┬﹏┬┬)(┬┬﹏┬┬)

**Comment by 88250** [comment]
应该能实现，但是得等后面需求多一些再考虑，现在我们主要任务是改进移动端。

**Comment by Yuminis98** [comment]
> 应该能实现，但是得等后面需求多一些再考虑，现在我们主要任务是改进移动端。

有你这句话我就安心了，撤了，晚安👍

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/7641

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/14469 将改进为不再整体重载界面
