### ISSUE TITLE
打开时候标签栏空白无显示

### ISSUE THREAD

**Issue by ohyessir** [siyuan-note/siyuan#7155]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

有时候打开的时候，标签栏显示空白
![image](https://user-images.githubusercontent.com/45805851/214098371-628c5486-a617-4450-877b-d1ec698b1441.png)
之前的版本也是这样，升级了之后又出现了这个问题

### 期待的结果 Expected result

看是怎么回事，有时候启动的时候就会这样

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/45805851/214098746-ea0f1ba2-90f7-4ebc-bd4f-0c470157a760.png)

### 版本环境 Version environment

```markdown
- Version: 2.6.2
- Operating System: win11
- Browser (if used):chrome
```

### 日志文件 Log file

1

### 更多信息 More information

1

**Comment by 88250** [comment]
请升级到最新版，应该已经修复这个问题了。
