### ISSUE TITLE
v2.7.1-dev2 -- can't copy from a pdf

### ISSUE THREAD

**Issue by eslam-gomaa** [siyuan-note/siyuan#7159]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

A nice new feature introduced in  v2.7.1-dev2  release. [ PDF 按住 Ctrl 进行矩形标注，按住 Alt 进行矩形标注并显示背景](https://github-com.translate.goog/siyuan-note/siyuan/issues/3318?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=ar) however I can not use CTL + C to copy words from the PDF

maybe we can use another key for Rectangular annotation.

### 期待的结果 Expected result

copy text from the PDF with CTL + C

### 版本环境 Version environment

```markdown
- Version:  v2.7.1-dev2 
- Operating System: MacOS
- Browser (if used):
```

### 日志文件 Log file

not needed

**Comment by 88250** [comment]
We will improve it in the next dev release, thanks.
