### ISSUE TITLE
在文件管理器中新建/删除文件夹的时候，笔记软件中文件树不同步更新

### ISSUE THREAD

**Issue by liuzhilinux** [siyuan-note/siyuan#716]
思源笔记
版本：v0.5.2

操作系统版本：
Microsoft Windows 10 Pro 10.0.19042

复现：
打开文档所在的文件位置，在位置下新建一个文件夹，回到笔记，文件树中并没有体现刚才新建的文件夹。
同时，在笔记软件的文件树下，新建一个文件夹，然后回到文档所在的文件位置，把刚才新建的文件夹删除，回到笔记软件，文件树中仍然存在刚才删除的文件夹。

同时，如果在文档所在位置删除笔记软件的文件树中存在的文件夹，然后回到笔记软件中，在刚删除的文件夹下新建文件夹，会出现如下错误，但是新建文档却没有问题。

![image](https://user-images.githubusercontent.com/20591624/101988553-5bc0e180-3cd5-11eb-8422-a3675d839cca.png)

我不知道我们的思源笔记软件是否是**不建议在软件外修改文档**，如果是，那么也许我没有在文档或官方教程中看到有提示，也许只是我没有看到；如果允许在软件外对文档进行编辑，那么笔记软件自身是否需要在编辑后的变动做一定的处理。

希望思源笔记越做越好~

**Comment by 88250** [comment]
你好，在外部修改以后需要重启，可能是这个引起的报错吧。

**Comment by liuzhilinux** [comment]
了解了，原来需要重启软件，请问一下，思源笔记是否不建议我们使用者在软件之外进行文件的编辑呢？

**Comment by 88250** [comment]
是的，因为编辑之后要重启，如果没重启，内容会被覆盖或者出现其他问题。

之前有用户报过这个问题，但我们目前暂时没有时间精力去解决，所以……尽量不要在外部编辑，内部编辑能够保证完整性和一致性，谢谢。
