### ISSUE TITLE
移动端无法修改文件图标

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7160]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

移动端无法修改文件图标

### 期待的结果 Expected result

移动端可以修改文件图标

### 版本环境 Version environment

```markdown
- Version: 2.7.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
我这里测试在移动端浏览器下可以修改文档图标的，请说明一下你的操作。

![image](https://user-images.githubusercontent.com/873584/214466172-26ad82f0-d7a5-4f26-96dc-c910e643ce0d.png)

**Comment by heimi98** [comment]
我用的客户端，不是浏览器，似乎本来就不支持。

**Comment by 88250** [comment]
> - Version: 2.7.1

你是自己编译的吗？目前 v2.7.1 还没有发布正式版的。

**Comment by 88250** [comment]
2.7.0 我这里在 APP 上测试也可以修改的，在题头图那一块。

**Comment by heimi98** [comment]
> 2.7.0 我这里在 APP 上测试也可以修改的，在题头图那一块。

我这不行，ipad 上题头图都显示不了
