### ISSUE TITLE
对思源主题依赖逐渐加重的担忧

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#7162]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

我觉得目前，思源主题对用户体验的占比越来越重，我觉得这种趋势如果长期发展下去，对思源会产生如下不良影响。

1. 主题定位走形。主题越来越像独立软件，而不仅仅地变换 UI 外观，用两个主题就像在用两款软件。
2. 特性耦合度增高。用户下载主题相当于打包下载了一系列耦合在一起的插件。
选择这一组插件包，就无法选择另一组。我经常会同时想要多个主题的某些功能，在多个主题之间反复横跳。
3. 主题开发者重复造轮子，维护成本加大。一个主题做多个功能，这些功能可能有很多是重复的，但是又要单独开发一遍。
而且到后面不断地为主题增加新特性，会导致维护成本越来越高。
4. 用户依赖主题而不是软件本身。**主题作者一旦停更，对长期使用主题的用户来说，就不是换一个外观那么简单，而是要改变一系列已经熟悉的操作习惯和功能特性。（比如一旦 dark+ 的作者弃坑了，dark+ 停止更新，那我可能直接跑路了。）**

### 期待的结果 Expected result

还是希望能够把类似插件机制推出来，把一个主题的各种特性解耦成单个的插件，让主题回归到单纯的 UI 改变。

作为已经使用快2年，并且准备长期使用的用户，非常担忧主题占比越来越重所带来的上述4点问题。

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
这个主要看用户自己的选择了，无论是何种扩展方式，都有可能存在停止维护或者不兼容，特别是作为开源软件开发者是无法完全左右的。

https://ld246.com/article/1674374365489

**Comment by GH-W94** [comment]
> 这个主要看用户自己的选择了，无论是何种扩展方式，都有可能存在停止维护或者不兼容，特别是作为开源软件开发者是无法完全左右的。
> 
> https://ld246.com/article/1674374365489

还是希望将主题和挂件（或插件）的功能分开，进行一个规范，原因有如下：

1.主题应该定位于界面色彩、图标形状、原生功能按钮位置调整这三方面。
挂件（插件）定位于在原生功能外拓展的功能。

2.分开后，有助于减少主题体积，提高第三方主题的性能。

3.提高了主题和拓展功能的灵活搭配性，不必为了某个功能而来回切换主题。

4.避免产生某个第三方主题特有功能是原生功能的错觉。现在有很多人在论坛上提问，某个功能怎么没有了，最后实际原因是他讲的这个功能是第三方主题特有的功能，他更换了主题，功能不见了，之前一直以为是这个功能是原生的。

**Comment by Yuminis98** [comment]
> 这个主要看用户自己的选择了，无论是何种扩展方式，都有可能存在停止维护或者不兼容，特别是作为开源软件开发者是无法完全左右的。
> 
> https://ld246.com/article/1674374365489

但是单独维护一个功能插件的成本 和维护一个拥有大量功能特性的主题，前者的维护成本应该要小很多吧

**Comment by Yuminis98** [comment]
现在来说，部分主题的停更对我的影响会是直接无法继续使用思源。
 除非开发者在热门主题停更以后，将功能集成到本体，有一个兜底机制

**Comment by Yuminis98** [comment]
不知道出于什么考虑，插件的issue被直接关掉了。 😭😭😭😭😭😭😭😭😭
但是为了思源的长久发展打算，还是希望以后能够推出插件机制。

**Comment by Yuminis98** [comment]
如果只是一个插件停更了。我大不了不用某一个功能。
但是一思源个主题停更了，意味着我常用的功能、外观、操作习惯全都要跟着变。
还有某些常用的模板，也是基于主题制作的。（比如某些主题独有的列表转表格、看板）
除此之外，主题和主题之间的格式还会不统一，比如一个整齐的超级快模板，切到了另一个主题，会变得参差不齐。
总之切换成本特别高，所以我如此忧虑。

**Comment by 88250** [comment]
使用的扩展如果停止维护了，对用户的影响主要看使用频率和是否持久化了数据，特别是后者。

我能够理解用户对开发者社区秉持悲观态度，但是我之前已经说过，无论我们以什么方式，都无法控制其他开发者不在主题中实现功能的，因为对于社区开发者来说这是扩展功能效率最高的实现方式。

另外，实际上现在也是支持外观样式和功能特性分离的，比如可以通过 JS 代码片段来扩展功能特性，主题只负责外观定制。但这是理想情况，实际上社区开发者可能没有这么多时间精力考虑这些问题。

关于实现插件机制的前提是得提供较为完善的 API 和一些必要的内部组件封装，目前思源的开发进度还没有到达这一步，所以我们先关闭插件提议，等时机成熟再考虑。

**Comment by Yuminis98** [comment]
> 使用的扩展如果停止维护了，对用户的影响主要看使用频率和是否持久化了数据，特别是后者。
> 
> 我能够理解用户对开发者社区秉持悲观态度，但是我之前已经说过，无论我们以什么方式，都无法控制其他开发者不在主题中实现功能的，因为对于社区开发者来说这是扩展功能效率最高的实现方式。
> 
> 另外，实际上现在也是支持外观样式和功能特性分离的，比如可以通过 JS 代码片段来扩展功能特性，主题只负责外观定制。但这是理想情况，实际上社区开发者可能没有这么多时间精力考虑这些问题。
> 
> 关于实现插件机制的前提是得提供较为完善的 API 和一些必要的内部组件封装，目前思源的开发进度还没有到达这一步，所以我们先关闭插件提议，等时机成熟再考虑。

了解了，谢谢

**Comment by TCOTC** [comment]
手动关联一下 #8178
