### ISSUE TITLE
跨块选择问题。任意位置点击文字，按下shift，点击页面最后没有内容的空白位置，不能选中任何内容

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7165]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如题

### 期待的结果 Expected result

完善shift跨块选择

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by pisceswb** [comment]
点击到最后一行没有内容的块上，没有问题。
但点击到最后一行后面没有内容的空白部分，不能选中内容

**Comment by 88250** [comment]
空白位置没有块，所以会取消选择。

**Comment by pisceswb** [comment]
> 空白位置没有块，所以会取消选择。

不符合使用习惯，用户尤其是新手会觉得这是一个bug

**Comment by 88250** [comment]
块编辑器基本都是这样的，得先创建块才行。
