### ISSUE TITLE
改进块树数据存取

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7168]
之前使用单个文件存储块树数据（blocktree.msgpack）在块较多的情况下序列化保存较慢，且内存使用会较高，改进为散列存储在 temp/blocktree/ 文件夹下。

**Comment by aptexd** [comment]
“建议”用链表和数组的存贮结构，冲突时候用红黑树，不行再多加几个“桶”，并行操作🤣

**Comment by aptexd** [comment]
说到散列，想起之前路径过长的麻烦问题，当时就想：说不定可以将 .sy 文件也散列话存储呢，路径存在 .sy 文件中，依据路径进行散列，这样实际路径固定且变短，就彻底且跨平台解决文件路径问题了

**Comment by 88250** [comment]
@aptexd 这部分现在最好还是不改了，将可读路径存放之前也考虑过，弊端是移动的时候可能需要批量更新大量文件和索引。
