### ISSUE TITLE
导入markdown的图片资源在未引用的资源列表中

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#7169]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

自行导入 markdown 文件，因数量较多，将图片文件夹 evernote 放到了 Siyuan/data/assets 下
![Xnip2023-01-26_17-53-15](https://user-images.githubusercontent.com/2016363/214807804-81e0f8bf-240d-43c3-baea-27e007fccc65.jpg)

并对导入的的 markdown 的所有引用作了统一批处理，修改为 `![...](assets/evernote/...)` 格式。导入后页面显示正常

![Xnip2023-01-26_18-00-11](https://user-images.githubusercontent.com/2016363/214808098-1e5736b5-d907-4e7b-9cef-0bfe6f842c17.jpg)

但是图片出现在了未引用资源中
![Xnip2023-01-26_17-52-46](https://user-images.githubusercontent.com/2016363/214807877-902d3f15-5bcb-4f63-aeaa-991de6f3a15d.jpg)

### 期待的结果 Expected result

图片不出现在未引用资源列表

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: macOS 12.6.2
- Browser (if used):
```

### 日志文件 Log file

...

### 更多信息 More information

顺便想问一下，这种自行将图片资源放入到 assets 文件夹下的方法有风险吗？以后的版本迭代会导致图片丢失吗？如果有风险，是否有较好的方法规避？比如直接保存到 assets 文件夹下不要用嵌套文件夹？

**Comment by 88250** [comment]
我这里测试简单的路径没有发现问题：

![image](https://user-images.githubusercontent.com/873584/214809657-0744e7dc-b3ad-486c-a700-120168a3b804.png)


![image](https://user-images.githubusercontent.com/873584/214809577-47a03aa5-3791-4f61-bebf-64853d7e3dc2.png)

你那里有问题很可能是图片命名引起的，这个估计不会做改变了，有的符号不允许出现在资源文件名上，插入的时候特意做了过滤。

建议：

* 不要嵌套文件夹
* 使用 Markdown 导入方式，编入 ID 段
