### ISSUE TITLE
全局搜索会自动限定笔记本

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7170]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

想要使用全局搜索，但自动限定了一个笔记本。

### 期待的结果 Expected result

全局搜索。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![B1AQQXUO0}JF`$BDBE 2IPD](https://user-images.githubusercontent.com/56879067/214810923-ec889cd7-fd5f-4e1e-b24d-3be463ced12d.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
这个应该是你自己设置了命名查询吧，移除命名查询试试。
