### ISSUE TITLE
pandoc 是否在docker部署时被支持?

### ISSUE THREAD

**Issue by kuyagic** [siyuan-note/siyuan#7172]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前 app 版本是支持笔记导出为 docx 格式的,使用了 pandoc
是否 docker 纯 kernel 的版本 考虑支持 pandoc 来处理doc 文件呢?

### 描述可能的最优解决方案 Describe the optimal solution

不知道是不是 kernel 模式不能使用 pandoc

### 描述候选的解决方案 Describe the candidate solution

-

### 其他信息 Other information

-

**Comment by 88250** [comment]
你好，Docker 部署不支持通过 Pandoc 导出。
