### ISSUE TITLE
关系图点击标签节点报错

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#7176]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

* Open the `SiYuan User Guide`
  * Open the `Global Graph` node map and set the following display options
     * Tag enabled 
     * Arrow enabled
  * Search for `Note` tag in the Global Graph
    * You will see a couple of tags and there dependencies
    * Clicking on one of the `tag` nodes results in an error that the block id is unknown

### 期待的结果 Expected result

Clicking on a `tag` node in Global Graph should open the search window displaying all blocks where the `tag` had been found like using the editor.

### 截屏或者录屏演示 Screenshot or screen recording presentation

**Display options used for Global Graph**
![image](https://user-images.githubusercontent.com/13854802/215047914-5617344a-970b-44a1-bbb8-207803ed1a9e.png)

**Error message when clicking a `tag` node**
![image](https://user-images.githubusercontent.com/13854802/215047287-b7cefaff-ec38-412c-88e9-ec15589e23bb.png)

**Example (Expected behaviour when #Content Block# node was clicked)**
![image](https://user-images.githubusercontent.com/13854802/215048643-cb31fd36-9684-4dc7-9d24-a753421d70b5.png)

### 版本环境 Version environment

```markdown
- Version:v2.7.0 
- Operating System: Windows 10 (additionally I run a Docker-based cloud installation with the same bug)
- Browser (if used): Firefox 108.0.2 (64-bit) used for the cloud installation
```

### 日志文件 Log file

```text
I 2023/01/27 09:38:45 runtime.go:46: kernel is booting:
    * ver [2.7.0]
    * arch [amd64]
    * pid [6656]
    * runtime mode [prod]
    * working directory [C:\Users\HBE\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\HBE\Documents\siyuan]
I 2023/01/27 09:38:45 working.go:396: built-in pandoc [ver=2.19.2, bin=C:\Users\HBE\Documents\siyuan\temp\pandoc\bin\pandoc.exe]
I 2023/01/27 09:38:45 runtime.go:91: use network proxy [system]
I 2023/01/27 09:38:45 serve.go:111: kernel [pid=6656] http server [127.0.0.1:50538] is booting
I 2023/01/27 09:38:45 conf.go:614: database size [5.0 MB], tree/block count [60/1900]
I 2023/01/27 09:38:45 working.go:157: kernel booted
I 2023/01/27 09:38:47 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/01/27 09:39:45 box.go:81: auto stat [trees=60, blocks=1900, dataSize=3.2 MB, assetsSize=2.0 MB]
I 2023/01/27 09:39:45 disk.go:33: disk usage [total=253 GB, used=237 GB, free=16 GB]
```

**Comment by 88250** [comment]
Please try again after rebuilding the index, if that doesn't work, please wait until the next version is released, we are improving the data index.

**Comment by nekrondev** [comment]
Thanks D for your fast reply! Rebuilding the index did not resolve the issue for me so I'll wait for the next release with improved indexing and retry ` tag` lookup in graph display.

**Comment by 88250** [comment]
I noticed that this ID is not in the ID format of a legal .sy data file, which may be the reason.

![image](https://user-images.githubusercontent.com/873584/215091105-f898cbbe-7224-4d41-960a-ef313c68cdf1.png)

**Comment by nekrondev** [comment]
@Vanessa219 @88250 Maybe this is something for frontend development so ensure that clicked "tag" nodes will open the tag search window instead of trying to open a block.

In the current version (2.7.3) the behaviour can simply be reproduced by opening a blank page, adding some `#tag#` and generating the local graph view. If you click on the tag node the "Content block with ID..." message will appear.

Maybe you could disable any UI actions when the graph tag node is clicked or open the search window (so the the same action will be triggered as clicking a text block embedded `#tag#`).

![image](https://user-images.githubusercontent.com/13854802/217473716-4112d226-35a6-4ebb-928a-623b4f4ca81f.png)

![image](https://user-images.githubusercontent.com/13854802/217473930-31aa9e7b-0c2f-4bdc-b453-2a4faea70dc4.png)
