### ISSUE TITLE
v202301271540 logging.go panic 异常，导致内核崩溃

### ISSUE THREAD

**Issue by HildaM** [siyuan-note/siyuan#7179]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [x] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [x] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

编辑有序大纲时，按回车突然崩溃。
查日志发现是logging.go PANIC

### 期待的结果 Expected result

希望编辑能够稳定一点

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

```markdown
- Version: v202301271540
- Operating System: win10
- Browser (if used): edge
```

### 日志文件 Log file

I 2023/01/27 18:03:14 repository.go:934: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=340 kB] in [1.86s]
I 2023/01/27 18:04:14 repository.go:934: synced data repo [provider=0, ufc=1, dfc=0, ucc=1, dcc=0, ub=181 kB, db=340 kB] in [4.20s]
I 2023/01/27 18:11:09 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/01/27 18:11:09 runtime.go:49: kernel is booting:
    * ver [2.7.0]
    * arch [amd64]
    * pid [13272]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\个人资料\Database]
I 2023/01/27 18:11:09 runtime.go:94: use network proxy [system]
I 2023/01/27 18:11:09 serve.go:111: kernel [pid=13272] http server [127.0.0.1:3168] is booting
I 2023/01/27 18:11:09 working.go:396: built-in pandoc [ver=2.19.2, bin=E:\个人资料\Database\temp\pandoc\bin\pandoc.exe]
I 2023/01/27 18:11:10 sync.go:70: sync before boot
I 2023/01/27 18:11:11 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/01/27 18:11:14 repository.go:833: boot get sync cloud files elapsed [3.65s]
I 2023/01/27 18:11:14 conf.go:615: database size [381 MB], tree/block count [2555/216398]
I 2023/01/27 18:11:14 working.go:157: kernel booted
E 2023/01/27 18:11:15 logging.go:142: PANIC RECOVERED: not implemented
	C:/hostedtoolcache/windows/go/1.19.5/x64/src/runtime/panic.go:884 (0xc1c331)
D:/a/siyuan/siyuan/go/pkg/mod/github.com/json-iterator/go@v1.1.12/any.go:52 (0x18b9da6)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/filesys/tree.go:269 (0x18f218a)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/filesys/tree.go:93 (0x18f0636)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/model/tree.go:166 (0x1d79972)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1434 (0x1d7804c)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1324 (0x1d777f1)
C:/hostedtoolcache/windows/go/1.19.5/x64/src/reflect/value.go:584 (0xcdf904)
C:/hostedtoolcache/windows/go/1.19.5/x64/src/reflect/value.go:368 (0xcdedfb)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/task/queue.go:212 (0x1890fbd)
C:/hostedtoolcache/windows/go/1.19.5/x64/src/runtime/asm_amd64.s:1594 (0xc4ef20)

**Comment by HildaM** [comment]
在同一个地方编辑任何内容，均出现异常。使用默认主题稳定复现：

第二次崩溃日志：
I 2023/01/27 18:12:15 box.go:81: auto stat [trees=2555, blocks=216398, dataSize=3.2 GB, assetsSize=3.1 GB]
I 2023/01/27 18:12:15 disk.go:33: disk usage [total=409 GB, used=306 GB, free=103 GB]
I 2023/01/27 18:16:16 repository.go:934: synced data repo [provider=0, ufc=2, dfc=0, ucc=2, dcc=0, ub=188 kB, db=340 kB] in [4.10s]
E 2023/01/27 18:20:36 transaction.go:888: load tree [id=20230127181055-hol3xo2] failed: block not found
I 2023/01/27 18:20:41 conf.go:397: exiting kernel [force=false, execInstallPkg=0]
E 2023/01/27 18:20:42 transaction.go:888: load tree [id=20230127181055-hol3xo2] failed: block not found
I 2023/01/27 18:20:42 sync.go:114: sync before exit
I 2023/01/27 18:20:44 repository.go:934: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=340 kB] in [1.74s]
I 2023/01/27 18:20:44 database.go:1034: closed database
I 2023/01/27 18:20:44 conf.go:773: cleared workspace temp
I 2023/01/27 18:20:50 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/01/27 18:20:50 runtime.go:49: kernel is booting:
    * ver [2.7.0]
    * arch [amd64]
    * pid [3076]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\个人资料\Database]
I 2023/01/27 18:20:50 runtime.go:94: use network proxy [system]
I 2023/01/27 18:20:50 serve.go:111: kernel [pid=3076] http server [127.0.0.1:4097] is booting
I 2023/01/27 18:20:51 working.go:396: built-in pandoc [ver=2.19.2, bin=E:\个人资料\Database\temp\pandoc\bin\pandoc.exe]
I 2023/01/27 18:20:53 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/01/27 18:20:53 sync.go:70: sync before boot
I 2023/01/27 18:20:56 repository.go:833: boot get sync cloud files elapsed [3.01s]
I 2023/01/27 18:20:56 conf.go:615: database size [381 MB], tree/block count [2555/216398]
I 2023/01/27 18:20:56 working.go:157: kernel booted
E 2023/01/27 18:20:57 logging.go:142: PANIC RECOVERED: not implemented
	C:/hostedtoolcache/windows/go/1.19.5/x64/src/runtime/panic.go:884 (0xc1c331)
D:/a/siyuan/siyuan/go/pkg/mod/github.com/json-iterator/go@v1.1.12/any.go:52 (0x18b9da6)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/filesys/tree.go:269 (0x18f218a)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/filesys/tree.go:93 (0x18f0636)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/model/tree.go:166 (0x1d79972)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1434 (0x1d7804c)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1324 (0x1d777f1)
C:/hostedtoolcache/windows/go/1.19.5/x64/src/reflect/value.go:584 (0xcdf904)
C:/hostedtoolcache/windows/go/1.19.5/x64/src/reflect/value.go:368 (0xcdedfb)
D:/a/siyuan/siyuan/go/src/github.com/siyuan-note/siyuan/kernel/task/queue.go:212 (0x1890fbd)
C:/hostedtoolcache/windows/go/1.19.5/x64/src/runtime/asm_amd64.s:1594 (0xc4ef20)

**Comment by HildaM** [comment]
重建索引后，可正常编辑。默认主题与自定义主题均正常

**Comment by HowcanoeWang** [comment]
发个稍微不太一样的日志报错供参考

![@@CY$WXD$NX{9PE%IRH2`LW](https://user-images.githubusercontent.com/19968935/215995211-3db8ee74-53f1-427e-afbd-a1a73ce646c4.png)


```plaintxt

I 2023/02/01 14:37:48 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=162 kB, db=151 kB] in [2.49s]
I 2023/02/01 14:41:20 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=162 kB, db=151 kB] in [1.98s]
E 2023/02/01 14:42:56 serve.go:342: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
I 2023/02/01 14:43:45 box.go:74: auto stat [trees=803, blocks=41538, dataSize=70 MB, assetsSize=16 MB]
I 2023/02/01 14:43:45 disk.go:33: disk usage [total=2.0 TB, used=770 GB, free=1.2 TB]
E 2023/02/01 14:51:44 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x24c331)
D:/go1.19/src/runtime/panic.go:260 (0x261595)
D:/go1.19/src/runtime/signal_windows.go:255 (0x261565)
D:/gogogo/pkg/mod/github.com/siyuan-note/httpclient@v0.0.0-20230116125720-ee36ddf6f223/client.go:112 (0xb45917)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:562 (0xb24348)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:519 (0xb23d1e)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:598 (0xb24585)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:614 (0xb2451d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/cloud/siyuan.go:123 (0x1314a35)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1008 (0x1331813)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1061 (0x1331ee5)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:105 (0x132945d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:80 (0x1329106)
D:/88250/siyuan/kernel/model/repository.go:902 (0x1405319)
D:/88250/siyuan/kernel/model/sync.go:121 (0x141cf76)
D:/88250/siyuan/kernel/model/sync.go:93 (0x141c5ac)
D:/88250/siyuan/kernel/model/sync.go:54 (0x141c5a1)
D:/88250/siyuan/kernel/job/cron.go:52 (0x143b39d)
D:/88250/siyuan/kernel/job/cron.go:53 (0x143b316)
D:/go1.19/src/runtime/asm_amd64.s:1594 (0x27ef20)

I 2023/02/01 14:51:52 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=163 kB, db=151 kB] in [2.19s]
I 2023/02/01 15:00:30 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=163 kB, db=151 kB] in [2.19s]
I 2023/02/01 15:01:52 repository.go:935: synced data repo [provider=0, ufc=3, dfc=0, ucc=1, dcc=0, ub=163 kB, db=151 kB] in [2.03s]
I 2023/02/01 15:05:34 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=163 kB, db=151 kB] in [1.96s]
I 2023/02/01 15:14:22 repository.go:935: synced data repo [provider=0, ufc=3, dfc=0, ucc=1, dcc=0, ub=164 kB, db=151 kB] in [1.98s]
I 2023/02/01 15:15:44 repository.go:935: synced data repo [provider=0, ufc=3, dfc=0, ucc=1, dcc=0, ub=164 kB, db=151 kB] in [2.17s]
I 2023/02/01 15:16:42 repository.go:935: synced data repo [provider=0, ufc=3, dfc=0, ucc=2, dcc=0, ub=165 kB, db=151 kB] in [1.92s]
I 2023/02/01 15:21:54 repository.go:935: synced data repo [provider=0, ufc=4, dfc=0, ucc=2, dcc=0, ub=165 kB, db=151 kB] in [2.19s]
I 2023/02/01 15:22:31 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=143 kB, db=151 kB] in [1.65s]
I 2023/02/01 15:25:14 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=143 kB, db=151 kB] in [2.19s]
E 2023/02/01 15:25:43 serve.go:342: handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
I 2023/02/01 15:38:18 repository.go:935: synced data repo [provider=0, ufc=3, dfc=0, ucc=2, dcc=0, ub=145 kB, db=151 kB] in [2.85s]
I 2023/02/01 15:40:12 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=144 kB, db=151 kB] in [3.80s]
I 2023/02/01 15:42:59 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=144 kB, db=151 kB] in [1.88s]
I 2023/02/01 15:46:01 repository.go:935: synced data repo [provider=0, ufc=3, dfc=0, ucc=2, dcc=0, ub=166 kB, db=151 kB] in [2.29s]
I 2023/02/01 15:46:48 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=144 kB, db=151 kB] in [1.43s]
I 2023/02/01 15:49:55 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=144 kB, db=151 kB] in [2.04s]
I 2023/02/01 15:54:33 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=144 kB, db=151 kB] in [2.52s]
I 2023/02/01 15:56:56 repository.go:935: synced data repo [provider=0, ufc=2, dfc=0, ucc=1, dcc=0, ub=144 kB, db=151 kB] in [1.81s]
E 2023/02/01 16:05:29 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x24c331)
D:/go1.19/src/runtime/panic.go:260 (0x261595)
D:/go1.19/src/runtime/signal_windows.go:255 (0x261565)
D:/gogogo/pkg/mod/github.com/siyuan-note/httpclient@v0.0.0-20230116125720-ee36ddf6f223/client.go:112 (0xb45917)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:562 (0xb24348)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:519 (0xb23d1e)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:598 (0xb24585)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:614 (0xb2451d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/cloud/siyuan.go:123 (0x1314a35)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1008 (0x1331813)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1061 (0x1331ee5)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:105 (0x132945d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:80 (0x1329106)
D:/88250/siyuan/kernel/model/repository.go:902 (0x1405319)
D:/88250/siyuan/kernel/model/sync.go:121 (0x141cf76)
D:/88250/siyuan/kernel/model/sync.go:93 (0x141c5ac)
D:/88250/siyuan/kernel/model/sync.go:54 (0x141c5a1)
D:/88250/siyuan/kernel/job/cron.go:52 (0x143b39d)
D:/88250/siyuan/kernel/job/cron.go:53 (0x143b316)
D:/go1.19/src/runtime/asm_amd64.s:1594 (0x27ef20)

E 2023/02/01 16:06:21 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x24c331)
D:/go1.19/src/runtime/panic.go:260 (0x261595)
D:/go1.19/src/runtime/signal_windows.go:255 (0x261565)
D:/gogogo/pkg/mod/github.com/siyuan-note/httpclient@v0.0.0-20230116125720-ee36ddf6f223/client.go:112 (0xb45917)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:562 (0xb24348)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:519 (0xb23d1e)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:598 (0xb24585)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:614 (0xb2451d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/cloud/siyuan.go:123 (0x1314a35)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1008 (0x1331813)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1061 (0x1331ee5)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:105 (0x132945d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:80 (0x1329106)
D:/88250/siyuan/kernel/model/repository.go:902 (0x1405319)
D:/88250/siyuan/kernel/model/sync.go:121 (0x141cf76)
D:/88250/siyuan/kernel/model/sync.go:93 (0x141c5ac)
D:/88250/siyuan/kernel/model/sync.go:54 (0x141c5a1)
D:/88250/siyuan/kernel/job/cron.go:52 (0x143b39d)
D:/88250/siyuan/kernel/job/cron.go:53 (0x143b316)
D:/go1.19/src/runtime/asm_amd64.s:1594 (0x27ef20)

E 2023/02/01 16:06:40 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x24c331)
D:/go1.19/src/runtime/panic.go:260 (0x261595)
D:/go1.19/src/runtime/signal_windows.go:255 (0x261565)
D:/gogogo/pkg/mod/github.com/siyuan-note/httpclient@v0.0.0-20230116125720-ee36ddf6f223/client.go:112 (0xb45917)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:562 (0xb24348)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:519 (0xb23d1e)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:598 (0xb24585)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:614 (0xb2451d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/cloud/siyuan.go:123 (0x1314a35)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1008 (0x1331813)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1061 (0x1331ee5)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:105 (0x132945d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:80 (0x1329106)
D:/88250/siyuan/kernel/model/repository.go:902 (0x1405319)
D:/88250/siyuan/kernel/model/sync.go:121 (0x141cf76)
D:/88250/siyuan/kernel/model/sync.go:93 (0x141c5ac)
D:/88250/siyuan/kernel/model/sync.go:54 (0x141c5a1)
D:/88250/siyuan/kernel/job/cron.go:52 (0x143b39d)
D:/88250/siyuan/kernel/job/cron.go:53 (0x143b316)
D:/go1.19/src/runtime/asm_amd64.s:1594 (0x27ef20)

I 2023/02/01 16:06:47 repository.go:935: synced data repo [provider=0, ufc=1, dfc=0, ucc=0, dcc=0, ub=142 kB, db=151 kB] in [1.93s]
I 2023/02/01 16:14:49 repository.go:935: synced data repo [provider=0, ufc=1, dfc=0, ucc=0, dcc=0, ub=142 kB, db=151 kB] in [1.46s]
E 2023/02/01 16:23:01 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x24c331)
D:/go1.19/src/runtime/panic.go:260 (0x261595)
D:/go1.19/src/runtime/signal_windows.go:255 (0x261565)
D:/gogogo/pkg/mod/github.com/siyuan-note/httpclient@v0.0.0-20230116125720-ee36ddf6f223/client.go:112 (0xb45917)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:562 (0xb24348)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:519 (0xb23d1e)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:598 (0xb24585)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:614 (0xb2451d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/cloud/siyuan.go:123 (0x1314a35)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1008 (0x1331813)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1061 (0x1331ee5)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:105 (0x132945d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:80 (0x1329106)
D:/88250/siyuan/kernel/model/repository.go:902 (0x1405319)
D:/88250/siyuan/kernel/model/sync.go:121 (0x141cf76)
D:/88250/siyuan/kernel/model/sync.go:93 (0x141c5ac)
D:/88250/siyuan/kernel/model/sync.go:54 (0x141c5a1)
D:/88250/siyuan/kernel/job/cron.go:52 (0x143b39d)
D:/88250/siyuan/kernel/job/cron.go:53 (0x143b316)
D:/go1.19/src/runtime/asm_amd64.s:1594 (0x27ef20)

E 2023/02/01 16:23:20 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x24c331)
D:/go1.19/src/runtime/panic.go:260 (0x261595)
D:/go1.19/src/runtime/signal_windows.go:255 (0x261565)
D:/gogogo/pkg/mod/github.com/siyuan-note/httpclient@v0.0.0-20230116125720-ee36ddf6f223/client.go:112 (0xb45917)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:562 (0xb24348)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:519 (0xb23d1e)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:598 (0xb24585)
D:/gogogo/pkg/mod/github.com/imroc/req/v3@v3.30.0/request.go:614 (0xb2451d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/cloud/siyuan.go:123 (0x1314a35)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1008 (0x1331813)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:1061 (0x1331ee5)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:105 (0x132945d)
D:/gogogo/pkg/mod/github.com/siyuan-note/dejavu@v0.0.0-20230117131301-821aa3adc1e7/sync.go:80 (0x1329106)
D:/88250/siyuan/kernel/model/repository.go:902 (0x1405319)
D:/88250/siyuan/kernel/model/sync.go:121 (0x141cf76)
D:/88250/siyuan/kernel/model/sync.go:93 (0x141c5ac)
D:/88250/siyuan/kernel/model/sync.go:54 (0x141c5a1)
D:/88250/siyuan/kernel/job/cron.go:52 (0x143b39d)
D:/88250/siyuan/kernel/job/cron.go:53 (0x143b316)
D:/go1.19/src/runtime/asm_amd64.s:1594 (0x27ef20)

I 2023/02/01 16:23:28 repository.go:935: synced data repo [provider=0, ufc=1, dfc=0, ucc=0, dcc=0, ub=78 kB, db=151 kB] in [3.21s]

```

**Comment by 88250** [comment]
@HowcanoeWang 这个问题在 https://github.com/siyuan-note/siyuan/issues/7217 中解决，感谢反馈。
