### ISSUE TITLE
搜索界面的类型过滤设置界面的优化

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#7180]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![Snipaste_2023-01-27_19-55-06](https://user-images.githubusercontent.com/32903588/215080128-abf31e31-7405-4174-9e46-1114297632b6.png)
搜索时，会有些不同类型的块，内容重复，设置过滤时，第一注意到的是红框中的图标，而不是通过图标联想到这是个什么类型的块
![image](https://user-images.githubusercontent.com/32903588/215081094-846c1139-45e6-4e86-a710-76158824ff48.png)
所以，在这个界面设置时，脑海中总会卡住

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/32903588/215080600-005927f1-c803-43ac-bd41-6f8e68bd6b13.png)
文字前加上图标，体验会更好，我是这么觉得的

**Comment by 88250** [comment]
嗯，有道理哦。
