### ISSUE TITLE
标签中出现了很多无法删除的标签

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#7181]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/72953189/215087371-d0f042c2-baf6-4f65-bf98-ab2feb25a71b.png)
![image](https://user-images.githubusercontent.com/72953189/215087597-438f9e1f-2954-4497-988d-ab685543eaa3.png)

如果，我的标签使用中文的是我自己使用的标签，但是应该在某一次从浏览器导入文章后（不记得是多久），就出现很多这种类型数据，并且我点击到此标签显示并没有对应的数据。然后使用删除

![image](https://user-images.githubusercontent.com/72953189/215087949-cdea99d5-8ad9-4fd4-b939-2c0d3a96df4a.png)

出现界面，并且会刷新，但是标签还是存在无法删除。

使用重建索引也无效，已经好几天了

### 期待的结果 Expected result

标签删除无效

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: windows
- Browser (if used):edge
```

### 日志文件 Log file

没有错误信息

**Comment by tangjiahao2001** [comment]
![image](https://user-images.githubusercontent.com/72953189/215088777-d0444e02-bfd2-47dd-b0eb-fa10afdb6e79.png)

最长的像这样，这么长

**Comment by 88250** [comment]
请提供一个能够重现问题的 .sy 文件，谢谢。

**Comment by tangjiahao2001** [comment]
已经不知道到底是哪个文件呈现这个标签，因为无论我点击这个标签的哪里。都搜索不出来内容。

![image](https://user-images.githubusercontent.com/72953189/215099402-0522b1e6-505a-4fd5-b5c2-79e11eb69250.png)

已经没有这个标签指定的内容了，并且也无法删除。请问还有什么其它的办法手动删除吗？

**Comment by tangjiahao2001** [comment]
[优化一--hexo.sy.zip](https://github.com/siyuan-note/siyuan/files/10519406/--hexo.sy.zip)

我刚刚通过搜索发现上述文件存在标签中的内容

![image](https://user-images.githubusercontent.com/72953189/215101383-1750eb85-91d6-407d-ba90-35c1bff37dde.png)

也许是标题被识别了吧🤣 ;)

**Comment by 88250** [comment]
大概是这些元素造成的，思源不支持行级 HTML，所以直接粘贴代码的话可能会将里面的 `#...#` 解析为标签。

![image](https://user-images.githubusercontent.com/873584/215103873-694905a2-d53c-4c7d-9985-adf8d7163b47.png)

**Comment by 88250** [comment]
将这些代码删除后标签面板就恢复了，但是这些数据是否重要你得留意一下。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
