### ISSUE TITLE
关于“闪卡”功能的优化

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7182]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

经过使用了一段时间的闪卡，发现闪卡功能确实不好用，结合之前关于闪卡的讨论（ [希望取消闪卡的卡包，因为文档树就是天然的卡包](https://ld246.com/article/1673512327205) 、 [建议闪卡的关于 pdf 的链接可以显示](https://ld246.com/article/1673762231617) 、 [思源笔记关于闪卡的几个功能建议](https://ld246.com/article/1673100293107) ），发现大家对目前的闪卡功能的体验大部分还是不好的，问题主要集中在如下两点：

1. 卡片管理不便。
2. 制卡操作繁琐。

### 描述可能的最优解决方案 Describe the optimal solution

见：https://ld246.com/article/1674666586495

**Comment by 88250** [comment]
论坛上 openAI 这位朋友给出的建议比较好一些，目前批量制卡可以通过多选然后一次性制卡。

后面可能会提供将文档作为卡包制卡的入口，这个还需要时间考虑，也许也会考虑交由社区开发者实现。

感谢建议。

**Comment by GH-W94** [comment]
> 论坛上 openAI 这位朋友给出的建议比较好一些，目前批量制卡可以通过多选然后一次性制卡。
> 
> 后面可能会提供将文档作为卡包制卡的入口，这个还需要时间考虑，也许也会考虑交由社区开发者实现。
> 
> 感谢建议。

openAI 这位朋友所提的文档树即卡包的方案是好，比目前的卡包的状态好，但我认为我的方案是最优解，理由如下：

1.他的方案存在你讲的如下问题，我也认同你所讲的这些问题：
（使用文档树有一些局限，具体来说比如这两个情况：
- 不是所有文档树上的文档都需要制卡，如果需要界定，那么这也需要更多步骤
- Dailynote 用法下文档树基本都是不分类的，这种情况下如何处理）
（使用文档树还有其他问题，比如：
- 无法通过简单的方式将一个块放到多个路径下，也就是说无法简单地将一张闪卡放到多个不同父路径的卡包中
- 一旦文档移动了路径，所属卡包就会变化，这个不一定符合制卡时的预期
- 考虑到将来的扩展性，比如后期我们要实现卡包导出，绑定了文档树的话导出就必须带着文档树导出，这样另一个用户导入卡包后有可能会造成和他已有的文档树路径重复，也破坏了他的文档树结构
总结来说就是绑定文档路径的方案有局限性，没有逻辑上的卡包灵活。）

2.我的方案对于使用不同笔记方法的人群都能寻找到满足自己的解决办法：
- 对于使用文档树记笔记，又对闪卡有类似 RemNote 那样文档树即卡包需求的人，可以通过手动建立与文档标题对应的分级卡包，然后使用一键将文档所有标记加入卡包来实现。
- 对于实践 daily note 记笔记的人，也可以仍然使用目前的制卡习惯自由建立主题学习卡包，也可根据卡片情况将卡包进行分级管理。

3.我的方案是在目前的卡包功能上的优化，没有引入新的概念，用户使用成本较低，代码修改成本低。

4.RemNote的所谓文档树即卡包的方案不是行业标杆，需要根据实际情况去考虑。

**Comment by 88250** [comment]
> 代码修改成本低。

这个有待评估，目前底层的卡包实现在设计之初就不支持分层的。

**Comment by GH-W94** [comment]
> > 代码修改成本低。
> 
> 这个有待评估，目前底层的卡包实现在设计之初就不支持分层的。

这个是我的错，有点说过头了。

我认为我的方案还是可以解决你提出的那些问题，并且能最大程度地解决所有人的痛点，满足不同人的使用需求。

**Comment by GH-W94** [comment]
我的方案中卡包树中的卡片即保持了与文档之间的关联，又保持了相对独立，给了后期拓展闪卡功能的空间。

比如给别人分享卡包，轻松将一张卡加入到不同的卡包。

再如给标签赋予新的属性，增强闪卡功能。当某个块被打上一个特定类型的标签时，比如“card”，就会激活闪卡的“筛选”功能。比如某个块的标签是“card\考试前重点复习”，则可以在考试前，通过“筛选按钮”选择“考试前重点复习”标签将这张卡片筛选出来进行复习。

比如担心每条复习的卡片越集越多，可以把一些暂时不需要记忆的卡包关闭。就像关闭笔记本那样关闭某个卡包，关闭后的表现是，当复习时选的范围是所有卡片时，关闭的卡包中的卡片不会出现在复习的队列中。

**Comment by 88250** [comment]
我这里短期内应该是没有时间考虑你提的方案的实现细节了，等社区开发者看下或者后期我们再考虑吧，见谅。

**Comment by GH-W94** [comment]
> 我这里短期内应该是没有时间考虑你提的方案的实现细节了，等社区开发者看下或者后期我们再考虑吧，见谅。

好吧，希望思源后期能考虑原生支持，越来越好，祝 D 大新年快乐。

我认为思源是一种深度学习型的笔记软件，这类笔记软件带有一个好用的间隔复习功能是很有必要的。

社会中绝大部分人是没有记笔记需求的，
一部分人记笔记但是属于有个地方记就行，记完或用完就抛弃，这部分人大部分选择手机自带的便签就满足了；
小部分人有记笔记需求并且有保存笔记的习惯，这部分人大部分为了方便，选择了在线云笔记，如印象笔记；
更小的一部分人不仅记完笔记保存好，还需要深度学习笔记，还不想被笔记商捆绑笔记数据，选择了本地笔记软件；
有记笔记习惯的学生就属于更小的那部分人，并且他们一般是有对笔记进行记忆的需求的，一个能拥有一套好用的间隔复习功能的笔记软件对他们应该是挺有引力的，这些有记笔记习惯的学生在步入社会后也能大概率保持记笔记的习惯。
