### ISSUE TITLE
同步失败，显示云端数据已经损坏，按解决方案处理无效

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#7185]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

macOS 端导入一个 markdown 文件夹后 iOS, Linux 端都出现这个问题，把导入的文件和对应的资源文件删除后同步可成功。导入的文件有上千个，不方便排查是哪个文件引起的，看能不能通过日志找到什么信息。

### 期待的结果 Expected result

同步成功

### 截屏或者录屏演示 Screenshot or screen recording presentation

![0BF9D8F8-E993-4F4C-A4F1-01E26613C9CC_1_101_o](https://user-images.githubusercontent.com/2016363/215241175-bacf752b-4316-4442-b288-48212e7f7e51.jpeg)

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: macOS, iOS, Ubuntu
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10525264/siyuan.log)

**Comment by 88250** [comment]
不要多个端在线同时编辑同步，否则可能会导致该问题。

目前只能新建新的云端同步目录重新同步。

**Comment by aGolduck** [comment]
已经尝试过这个方法了，应该不是多端同时编辑造成的。因为把新导入的这些笔记全删掉后就没有这个问题了。在  ubuntu 端开一个全新的终端下载也遇到一样的问题。

**Comment by 88250** [comment]
同步上传的时候要确保完成再关闭应用。

**Comment by aGolduck** [comment]
再次尝试失败，步骤：1. macos 换云端同步目录，换完上传数据，上传关闭同步。2. 全新下载 iOS 端应用同步。附最新日志及日志中提到的找不到的文件(因 github 不支持，我加了 .txt 后缀) 
[siyuan.log](https://github.com/siyuan-note/siyuan/files/10526813/siyuan.log)
[f1ac2aedb13ab15ca1acd8fc30a839334e8316.txt](https://github.com/siyuan-note/siyuan/files/10526816/f1ac2aedb13ab15ca1acd8fc30a839334e8316.txt)

**Comment by 88250** [comment]
macOS 端上传之前重置数据仓库了吗？
