### ISSUE TITLE
文字加粗后不能识别为虚拟引用

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7186]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

文字一旦加粗后，就不能识别为虚拟引用了。

### 期待的结果 Expected result

即使文字加粗后，也能识别为虚拟引用。

### 版本环境 Version environment

```markdown
- Version: 2.7.0
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
这个目前不考虑支持，后期如果有更多需求再考虑，感谢提议。
