### ISSUE TITLE
调整外观配色

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7189]
调整默认主题 midnight 和 daylight 配色。

**Comment by mozhux** [comment]
支持，希望能借鉴目前流行的设计，默认主题总感觉像win7时代的

**Comment by Zuoqiu-Yingyi** [comment]
可以参考一下一些第三方组件的配色: [Arco Design Vue](https://arco.design/vue/docs/token)

**Comment by 88250** [comment]
@mozhux @Zuoqiu-Yingyi 这次只是微调配色，不改变总体风格了，感谢反馈。

**Comment by GH-W94** [comment]
能否在设置中增加个“顶栏颜色自定义”设置，不喜欢黑色的顶栏。
