### ISSUE TITLE
希望能添加一个“临时笔记（Fleeting Notes）”的功能

### ISSUE THREAD

**Issue by liuzhilinux** [siyuan-note/siyuan#719]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

我通常学习的习惯是，在学习的时候专心学习，不会用大量的时间和精力去记笔记，只会在必要的时候记录下一些关键词。
在等到回头进行复习的时候，才会根据之前所学的内容进行笔记整理。

现在目前的情况是采用记事本进行笔记，我希望思源笔记能有这样的功能整合到软件之中。

### 描述最优的解决方案 Describe the optimal solution

可以在笔记文档目录下专门建立一个目录用于保存每次学习的临时笔记，临时笔记文件关联日期信息。
同时支持小窗模式，可以固定在屏幕的一边，方便在学习的过程中随时记录关键词。

### 描述候选解决方案 Describe the candidate solution

无。

### 其他信息 Other information

Zettelkasten (Slip box)，其中有提到一种笔记类型，叫做临时笔记（Fleeting Notes），又称作灵感笔记，主要用于记录日常生活中或学习中出现的转瞬即逝的灵感，我主要用来记录学习过程中出现的关键性的概念性的名词，用以后续复习时进行整理，同时避免在学习过程中大量编写笔记，从而打断学习过程的连贯性，进而影响学习效率。

**Comment by 88250** [comment]
建立一个名为“临时笔记”的文档，然后将其编辑页签拖拽放置好应该就行了吧？

**Comment by 88250** [comment]
你的提议我大致能够理解了，不过还是先关闭了，后续如果还有类似需求我们再重新审视，谢谢。
