### ISSUE TITLE
选中图片状态下折叠回车再撤销触发状态异常

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7190]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

今天一共发生了两次。
就是在记笔记的时候，回车键是有概率失效的，
如录屏所示，
我按下了回车，但是后面新建的一行是无法被光标选中的。
这个时候只要我按照ctl+Z，就会触发重建索引，并且回车上面那行还丢失了

**我尝试了一下，是可以稳定复现的，下面有复现录屏**
### 期待的结果 Expected result

修复bug

### 截屏或者录屏演示 Screenshot or screen recording presentation

导致笔记丢失
![image](https://user-images.githubusercontent.com/37429029/215301114-b8e22523-b3fd-4618-bdc8-6eb19fc4e946.png)

复现演示
[QQ录屏20230129103141.zip](https://github.com/siyuan-note/siyuan/files/10528813/QQ.20230129103141.zip)

### 版本环境 Version environment

```markdown
- Version: 2.7.1
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10528815/system-log.zip)

**Comment by 88250** [comment]
请在默认主题下测试，谢谢。

**Comment by AugustTuan** [comment]
[2.zip](https://github.com/siyuan-note/siyuan/files/10528842/2.zip)
已测试
话说，这种造成重建索引的操作逻辑bug，也可以由某个主题造成吗？
每次都需要切换到默认主题再来反馈，有点麻烦，很容易忘了🤣

**Comment by 88250** [comment]
有的主题添加了一些功能，有可能会有问题。

能否帮忙重新在默认主题下录屏演示一下，方便的话录屏麻烦直接发我的邮箱 845765@qq.com 我今天网络下载 github 文件太慢了，多谢。

**Comment by AugustTuan** [comment]
> 有的主题添加了一些功能，有可能会有问题。
> 
> 能否帮忙重新在默认主题下录屏演示一下，方便的话录屏麻烦直接发我的邮箱 [845765@qq.com](mailto:845765@qq.com) 我今天网络下载 github 文件太慢了，多谢。

已发，了解了，但是觉得还是有些怪怪的，
感觉用了一个主题就是用了另一款app了(┬┬﹏┬┬)

我以后尽量养成反馈前先切换主题的习惯🥹

**Comment by 88250** [comment]
好的，我们邮件联系，我今天这里是村通网，有点老火 😂

**Comment by 88250** [comment]
感谢老铁帮忙，我们已经定位到问题，下个版本修复。

**Comment by AugustTuan** [comment]
> 感谢老铁帮忙，我们已经定位到问题，下个版本修复。

👍👍👍
