### ISSUE TITLE
增加嵌入块上直接进行展开、折叠列表和标题的操作

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7192]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前不能在嵌入块上直接进行展开、折叠列表和标题的操作，需要点即嵌入块弹出悬浮窗，才能展开、折叠，非常麻烦。
![嵌入块不能折叠列表和表题](https://user-images.githubusercontent.com/117154557/215308008-0615eb73-79a4-4c05-a25d-412f4cb11d99.gif)

### 描述可能的最优解决方案 Describe the optimal solution

增加嵌入块上直接进行展开、折叠列表和标题的操作

**Comment by 88250** [comment]
暂时不考虑了，因为嵌入块无法直接编辑。

**Comment by GH-W94** [comment]
> 暂时不考虑了，因为嵌入块无法直接编辑。

这个和嵌入块无法直接编辑并不冲突，可以直接展开和折叠操作只是供阅读时能提供更好的使用体验，不必啰嗦要点进去才能查看，不要求嵌入块支持直接编辑。

这也符合正正常的使用心理，有时嵌入的内容过长或有多级列表，阅读时，展开和折叠就会是一个比较高频的操作，能直接操作体验上就非常好，不必每次都弹出个浮窗才能操作，而编辑是个低频操作，弹出个浮窗编辑一次就完事了，也不显性。

还是说，直接展开和折叠需要在实现了直接编辑的基础上才能实现呢？

**Comment by 88250** [comment]
> 还是说，直接展开和折叠需要在实现了直接编辑的基础上才能实现呢？

是的。
