### ISSUE TITLE
支持关闭托盘图标

### ISSUE THREAD

**Issue by HerrKKK** [siyuan-note/siyuan#7193]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

"设置-外观-关闭按钮设置"设置为关闭时，此时如用户正常使用或关闭窗口退出，则托盘图标无用，如用户最小化，此时出现两个重新唤起程序的入口，像是冗余设计。

### 描述可能的最优解决方案 Describe the optimal solution

"设置-外观”中额外设置一个关闭托盘图标选项

### 描述候选的解决方案 Describe the candidate solution

当"设置-外观-关闭按钮设置"设置为关闭时，程序启动后不显示托盘图标

### 其他信息 Other information

请参考telegram window客户端"setting-advanced"中提供的两个选项：显示任务栏图标和显示托盘图标；

**Comment by 88250** [comment]
托盘上有一些必要的功能，比如窗口置顶和重置窗口以及其他一些其他信息，所以暂时不考虑支持关闭托盘，谢谢。
