### ISSUE TITLE
嵌入块查询响应慢

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7197]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时新添加了嵌入块，然后立即查询就查询不到，需要等相当长一段时间或手动强制刷新页面才能查到，如下图：
![嵌入块有时查询不到](https://user-images.githubusercontent.com/117154557/215308898-11cd174d-f145-4e0d-8b5d-445c54dc8e40.gif)

### 描述可能的最优解决方案 Describe the optimal solution

感谢修复。

**Comment by 88250** [comment]
搜索需要等数据库索引入库后才能搜到。
