### ISSUE TITLE
桌面端浮窗和引用菜单添加 `在新窗口打开` 按钮

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7198]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前可以将标签页从新窗口打开, 希望预览浮窗也可以打开为新窗口

### 描述可能的最优解决方案 Describe the optimal solution

在新窗口打开预览浮窗的内容, 保持与预览浮窗相同的浏览状态

**Comment by UFDXD** [comment]
建议引用右键也加入新窗口打开
