### ISSUE TITLE
提一个疑问，OCR识别图片没有文字的情况下，会反复对这张图片进行OCR识别吗？

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7199]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

提一个疑问，OCR识别图片没有文字的情况下，会反复尝试对这张图片进行OCR识别吗？
因为在系统状态栏，会间歇性看到ocr图片识别的提示。

另外，感觉状态栏提示有点多，有点分散注意力了

### 描述可能的最优解决方案 Describe the optimal solution

谢谢

**Comment by pisceswb** [comment]
大部分小白用户可能不太想要类似“数据库索引提交”这样经常出现的提示，尤其后面还带有一个醒目的动态条。
个人感觉一个“同步成功”的提示，让用户对数据放心，就足够了。

**Comment by pisceswb** [comment]
如果不修改，能否给一个隐藏 “数据库索引提交” 这些“后台动作提示”的CSS，谢谢！
![image-20230130080636-mfh5xpz](https://user-images.githubusercontent.com/104658457/215364013-55c3c88e-2f75-4137-96fe-f086a5c4ce35.png)

**Comment by 88250** [comment]
> OCR识别图片没有文字的情况下，会反复对这张图片进行OCR识别吗？

不会，识别成功或者失败（结果为空）后会写入 assets/ocr-texts.json，后续就不会再次识别了。

> “数据库索引提交”这样经常出现的提示

这是为了给用户知道数据库索引状态的，如果不出现的话可能会有其他疑问，比如“为什么搜索搜不到”。
