### ISSUE TITLE
希望加入Tab键补全

### ISSUE THREAD

**Issue by skyls03** [siyuan-note/siyuan#720]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

比如：
1. 使用块引入的时候，键入<kbd>((</kbd>，会出现很多提示，然后按`Tab`键 补全当前选中的项
2. 键入`:` 使用emoji表情的时候，按`Tab`补全当前选中的项

### 为什么要使用Tab键补全？

因为很多IDE的补全都是用Tab键的，虽然回车也能做，但是这样能更通用一点吧，也不会让程序员群体觉得很突兀。

**Comment by 88250** [comment]
你好，可以使用回车进行补全。

1. 块引输入 `((关键字` 选择以后，直接回车
2. `:` 继续输入 Emoji 后回车

**Comment by skyls03** [comment]
> 你好，可以使用回车进行补全。
> 
> 1. 块引输入 `((关键字` 选择以后回车
> 2. `:` 继续输入选择以后回车

我不是不会使用补全，而是希望加入用tab键来补全

**Comment by 88250** [comment]
哦，明白了，但是回车更符合大部分使用习惯吧，tab 在块引的时候目前也做了一些优化（从锚文本切换到后面，回车也行），但是输入补全的时候就统一用回车了。

**Comment by skyls03** [comment]
那好吧
