### ISSUE TITLE
悬浮窗希望能有按钮可以展开反链

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/siyuan#7204]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在有一个痛点是页面内引用的锚文本，浮窗显示后是对应引用的正文，很可能是空的，但看这个的目的其实更多是为了看这个主题的其他引用，所以是否能在预览浮窗增加新窗口打开的基础上，再增加显示该引用反链的功能，点击后则在打开的页面展开引用

### 描述可能的最优解决方案 Describe the optimal solution

在悬浮窗的面包屑那操作
![image](https://user-images.githubusercontent.com/46953371/215377040-2e647b46-4cff-48f7-9081-6d4fe63f67f0.png)

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
这个不考虑了，反链需要在反链面板中查看，放在浮窗里面空间不够。

**Comment by mozhux** [comment]
> 这个不考虑了，反链需要在反链面板中查看，放在浮窗里面空间不够。

空间够不够用户自己定嘛，而且浮窗可以拖动大小，可以新窗口打开（新特性支持后），这个就和反链面板是一样的。
比如我在日记页面写下 [[思源]]，写了其他东西，然后我悬浮查看思源这个文档，按目前来讲如果文档正文没有内容，大概率都是空的，但是我查看的本意是想知道这个文档有没有其他地方记录过，可以参考。这时候就很麻烦，需要先点开这个文档，然后在查看反链面板
