### ISSUE TITLE
PDF截图，笔记链接中图片错位

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7208]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如图，PDF截图，复制链接到笔记中，显示的图片与PDF框出的位置不同，assets文件夹中的图片文件也是错位的。
是我自己有这个问题吗？2.7.0版本好像是没有问题的
![image](https://user-images.githubusercontent.com/104658457/215443102-12d55702-9622-46de-8d6b-9ed4524315f9.png)

### 期待的结果 Expected result

望修正

### 截屏或者录屏演示 Screenshot or screen recording presentation

1

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by pisceswb** [comment]
PDF框出位置后，选择颜色，提示“不存在符合条件的内容块”

**Comment by 88250** [comment]
* 我这里测试没有发现错位的问题
* 提示“不存在符合条件的内容块” 是因为你没有进行引用吧

**Comment by pisceswb** [comment]
找到了bug。使用Ctrl+对屏幕进行缩放后，会导致该问题

**Comment by Vanessa219** [comment]
> 找到了bug。使用Ctrl+对屏幕进行缩放后，会导致该问题

可以重现了，下个版本改进
