### ISSUE TITLE
终身订阅账号支持通过积分兑换扩容云端存储

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7210]
https://github.com/siyuan-note/siyuan/issues/7055

对于终身订阅账号，扩容所需积分是年付订阅账号的 10 倍，也就是 180 积分兑换 1MB。

**Comment by Joker-lkc** [comment]
10倍会不会太高了 3、5被很高了吧

**Comment by TinkMingKing** [comment]
> 10倍会不会太高了 3、5被很高了吧
> 

我也觉得太高了，如果将其换算为RMB，普通订阅用户180RMB能得到1G空间，感觉勉强能接受，永久用户得1800，这太夸张了，说是鼓励社区互动，如果只是单纯社区获取，签到按3天100计算，加上每10天额外100，加上社区活跃，普通用户四舍五入按照1年能嫖到1G空间，那么永久用户得10年，那么这个兑换只不过是摆设
![Screenshot_2023-02-01-15-59-21-385_com.miui.calculator.jpg](https://user-images.githubusercontent.com/32903588/215984660-4a179c2c-d1df-47b1-881b-76a1c934f121.jpg)

**Comment by hopebird** [comment]
永久用户才512个，居然要10倍费用？这。。。

**Comment by Jamie-Wan** [comment]
积分作为代币本来就不应该支持大额兑换云空间吧？特别需要官方扩容的还是得期待官方是否会出购买云空间的方案。而且订阅用户的空间是限时的，相当于买一年；永久用户空间永久，至少可以当买10年算，十倍也能勉强接受吧

**Comment by ws198601** [comment]
虽然永久会员的空间相对来说永久的，但是感觉10倍还是太高了啊，
5倍比较能接受些

**Comment by zhangxoo** [comment]
有点伤心，作为最先支持思源的用户居然在扩容空间上得到了最残酷的待遇，不患寡而患不均啊

**Comment by TinkMingKing** [comment]
> 有点伤心，作为最先支持思源的用户居然在扩容空间上得到了最残酷的待遇，不患寡而患不均啊

没这么夸张，本来就是永久，就算不支持扩也认了，实际上能用满的也不多，不用为此提前焦虑

**Comment by hopebird** [comment]
我本来还想再捐助1800，买10g空间，现在需要18000，买不起啊

**Comment by Joker-lkc** [comment]
确实
&nbsp;


lkc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月3日(星期五) 晚上9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 终身订阅账号支持通过积分兑换扩容云端存储 (Issue #7210)





 
我本来还想再捐助1800，买10g空间，现在需要18000，买不起啊

**Comment by Joker-lkc** [comment]
> 我本来还想再捐助1800，买10g空间，现在需要18000，买不起啊

确实哈哈哈
