### ISSUE TITLE
未找到 ID 为 xxx 的内容块

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7215]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/56879067/215730987-23bd2952-29f2-4845-a331-da2c082afba6.png)
重建索引后能打开，但是关闭软件后重新打开软件，文档又打不开了。

### 期待的结果 Expected result

文档能打开。

### 版本环境 Version environment

```markdown
- Version: 2.7.1
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
使用了同步吗？

**Comment by heimi98** [comment]
> 使用了同步吗？

同步了，使用的 S3 。

**Comment by 88250** [comment]
其他端有编辑过吗？版本是？

**Comment by heimi98** [comment]
> 其他端有编辑过吗？版本是？

其他端未在工作，最新版 2.7.1

**Comment by 88250** [comment]
请上传内核日志文件。

**Comment by heimi98** [comment]
https://cowtransfer.com/s/bd6730dec5c345 点击链接查看 [ system-log.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 liubtf 查看；

**Comment by 88250** [comment]
发生问题的时间段大概是？或者麻烦你删掉 工作空间/temp/siyuan.log 日志文件，然后重新重现一下问题，之后再把日志发送一下，谢谢。

**Comment by heimi98** [comment]
https://cowtransfer.com/s/ff47ae8d387f42 点击链接查看 [ siyuan.log ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 kqi2lt 查看；

**Comment by winter60** [comment]
我也存在丢失文档的情况（都是同一个库下的几个文档），电脑和手机从数据历史中找不到文档最近的操作记录。不过离发现日期已经过去好多天了，因为不重要就没管了。
其他说明 ：
- 操作重建索引并没有恢复
- 这几个文档长期处于打开状态，我几乎不关机，都是从休眠状态恢复。
只是反馈一下。
@88250

**Comment by 88250** [comment]
@winter60 后续发现时麻烦上传日志反馈，谢谢。

**Comment by winter60** [comment]
> @winter60 后续发现时麻烦上传日志反馈，谢谢。

好的，下次一定留意

**Comment by DYLANXIANG** [comment]
> 请上传内核日志文件。

同类问题未找到xx内容块。没使用同步功能，复现问题后的日志：https://wwtt.lanzouw.com/i5B9H0m9lyxa；密码:8ae1
如果需要录屏的话，我再次上传，感谢

**Comment by 88250** [comment]
@DYLANXIANG 启动以后等状态栏上的索引检查完毕提示后再试试。

**Comment by DYLANXIANG** [comment]
> @DYLANXIANG 启动以后等状态栏上的索引检查完毕提示后再试试。

是的，等到左下角出现 索引校验完毕 后，再点击该文档，还是报错

**Comment by 88250** [comment]
重建索引以后也还能重现？

**Comment by DYLANXIANG** [comment]
@88250 Siyuan, S3, WebDAV都没有设置的

**Comment by 88250** [comment]
请试下改动完任何数据以后，不要退出程序，等待大概 10s 以后再退出，重启以后看看是否还能重现该问题。

**Comment by DYLANXIANG** [comment]
@88250 等10秒，退出重启，问题重现了

**Comment by 88250** [comment]
大概定位到问题了，今天稍晚点我们会发布一个 dev 版，有空的话请帮忙测试。

**Comment by DYLANXIANG** [comment]
@88250 啊太好了，好的会帮忙测试的

**Comment by DYLANXIANG** [comment]
@88250 用了最新的测试版一个多小时，具体情况是：1）如果只更新安装，想查看笔记时照样报错；2）我先重建索引一次，然后现在这么长时间过去了，没有再报错找不到内容块了，点击侧边栏能正常查看笔记；非常感谢！

**Comment by kirin521** [comment]
![image](https://user-images.githubusercontent.com/8955465/215921305-29cf7697-ca59-44e8-a9f7-30496d175b79.png)
出现了同样的错误~，在提示更新最新版本之后，更新到了最新版本之后，部分笔记出现了这个问题。。

**Comment by 88250** [comment]
@kirin521 下载 dev 版本安装，重建索引以后再试试。
