### ISSUE TITLE
网络请求时潜在的空指针问题

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#7217]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如下文的录像所示，打开帮助文档后，等不到1分钟的时间，会弹出崩溃提示。

不确定是否是个例，在我这边是一直能复现的。请检查一下能否复现。

日志里有提示：

E 2023/01/31 22:13:39 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x84c331)

### 期待的结果 Expected result

软件不奔溃。

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/58081876/215788876-694157c1-fccf-4991-86ab-4d2f257e1198.mp4

### 版本环境 Version environment

```markdown
- Version: 2.7.1
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

E 2023/01/31 22:13:39 logging.go:142: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.19/src/runtime/panic.go:884 (0x84c331)

**Comment by 88250** [comment]
麻烦上传完整的日志。

**Comment by 88250** [comment]
方便的话请测试一下 dev 版。
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by BryceAndJuly** [comment]
[system-log (2).zip](https://github.com/siyuan-note/siyuan/files/10552668/system-log.2.zip)

不能复现吗？那算了，平时也很少打开那个帮助文档，到时候安装新版的再试试。

**Comment by 88250** [comment]
我这里重现不了，有空的话麻烦测试一下最新的 dev 版，谢谢。

**Comment by 88250** [comment]
dev3 修复这个问题。
