### ISSUE TITLE
增加“块级标签”功能

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7218]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在思源里已级有了“行级标签”可以给行内内容打标签，“文档级标签”可以给文档打标签，所以还缺一个可以给“块”打标签的“块级标签”。
比如下图选中的一段话，我想给这段话整体打标签，目前只能用行级标签，达不到想要的目标。

![image](https://user-images.githubusercontent.com/117154557/215936320-88a67c4b-cdc5-4610-90be-2f679708b212.png)

### 描述可能的最优解决方案 Describe the optimal solution

1. 方案一：引入新的“块级标签”功能。

2.方案二：在现有的块属性“别名”的基础上改造。
“块级标签”的功能在一定程度上和“别名”的功能重合，都是对块内容的在某个角度进行了提炼，但却又比“别名”的用途广，可以对块内容进行分类整理。并且“别名”这个概念会给人一头雾水，难以理解，而修改成“块标签”就会好很多。所以建议通过改造现有的“别名”成为“块标签”。

**Comment by 88250** [comment]
这个提议和现有功能重叠较多，所以不考虑了，谢谢。

**Comment by GH-W94** [comment]
> 这个提议和现有功能重叠较多，所以不考虑了，谢谢。

“块级标签”并没有和现有功能重叠过多，“块级标签”的目的主要是给“块”打标签，现有的“标签”和“别名”功能都不能达此目的，特别是对于给”超级块“和”列表块“打标签。

有时将多个段落块组合成一个“超级块”后，想给这个超级块打标签，现有的功能没有一个能满足的，特别是超级块水平布局后，很难变通。
对于列表，想给列表中某几个连续的列表项块整体打标签时，现有功能也是无法满足的。

又由于“块标签”和块属性”别名“功能有一定重合，所以提出了方案二，在”别名“的基础上进行改造，让别名支持”层级“和”在标签面板显示“。

所以希望 D 大能考虑“块标签”，谢谢。

**Comment by 88250** [comment]
我理解你提的块标签应该就是属性，属性是后续扩展的基础，应用场景上应该不可能直接满足每个人不同的需求，所以属性只是基础，需求的满足还要看后续社区扩展。

**Comment by GH-W94** [comment]
> 我理解你提的块标签应该就是属性，属性是后续扩展的基础，应用场景上应该不可能直接满足每个人不同的需求，所以属性只是基础，需求的满足还要看后续社区扩展。

“块标签”可以简单的说成是“块属性”，但又不能等同于“块属性”，“块属性”只是实现“块标签”这一功能的手段，因为思源里的每个块都天然自带属性功能，所以在“块属性”的基础上去实现“块标签”，我认为是最便捷的，不用重新引入一套标签系统。

有了“块标签”后，就可以像现在的标签（在文档标题上或块内某句话的结尾打上标签，跳出文档树对文档或某句话从另一个角度进行归纳整理）一样，对文档内的某个块或某几个块，跳出文档标题从另一个角度进行归纳整理。

在思源中，唯一重要的核心概念是内容块。可以说“内容块”是思源笔记搭建的基础本单位，但目前却不能对这个基本单位进行多角度的归纳整理，我认为这是一个缺陷。

最后，我认为“块标签”是思源的基础功能，还是希望能原生支持，望 D 大考虑。

**Comment by 88250** [comment]
> “块标签”可以简单的说成是“块属性” .... 在“块属性”的基础上去实现“块标签”，我认为是最便捷的

这里的逻辑关系我没看明白，你指的基础到底是块标签还是块属性？这里的“实现”指的是代码层面的实现还是哪里的实现？

> 有了“块标签”后，就可以像现在的标签一样，对文档内的某个块或某几个块，跳出文档标题从另一个角度进行归纳整理。

前面我已经提到属性可以做这个事情了，但是因为属性很灵活，所以特定的需求场景我们无法去直接实现，这个需要社区扩展。

> 在思源中，唯一重要的核心概念是内容块。可以说“内容块”是思源笔记搭建的基础本单位，但目前却不能对这个基本单位进行多角度的归纳整理，我认为这是一个缺陷。

不知道是不是你没有理解属性的设计用意，内容块属性就是给内容块自身标记元数据的，完全可以用于归纳整理。

> 最后，我认为“块标签”是思源的基础功能，还是希望能原生支持

属性已经支持，界面的原生支持可以用嵌入块，或者等属性视图 #2829

**Comment by GH-W94** [comment]
> > “块标签”可以简单的说成是“块属性” .... 在“块属性”的基础上去实现“块标签”，我认为是最便捷的
> 
> 这里的逻辑关系我没看明白，你指的基础到底是块标签还是块属性？这里的“实现”指的是代码层面的实现还是哪里的实现？
> 
> > 有了“块标签”后，就可以像现在的标签一样，对文档内的某个块或某几个块，跳出文档标题从另一个角度进行归纳整理。
> 
> 前面我已经提到属性可以做这个事情了，但是因为属性很灵活，所以特定的需求场景我们无法去直接实现，这个需要社区扩展。
> 
> > 在思源中，唯一重要的核心概念是内容块。可以说“内容块”是思源笔记搭建的基础本单位，但目前却不能对这个基本单位进行多角度的归纳整理，我认为这是一个缺陷。
> 
> 不知道是不是你没有理解属性的设计用意，内容块属性就是给内容块自身标记元数据的，完全可以用于归纳整理。
> 
> > 最后，我认为“块标签”是思源的基础功能，还是希望能原生支持
> 
> 属性已经支持，界面的原生支持可以用嵌入块，或者等属性视图 #2829

我所希望的“块标签”是能和现在的标签统一起来的，即：
1.能统一在左下角的标签面板里显示。
2.应用于某句话的标签，也能应用于“块标签”，当在左下角的标签面板点击这个标签后，能筛选出打了这个标签的“话”和“块”。

**Comment by 88250** [comment]
统一显示在标签面板的话会变得混乱的，我不敢肯定这是不是其他用户想要的，所以暂时不会考虑这样做。

**Comment by GH-W94** [comment]
> 统一显示在标签面板的话会变得混乱的，我不敢肯定这是不是其他用户想要的，所以暂时不会考虑这样做。

不太理解你讲的“会变的混乱”是啥意思。无论是块标签还是现有的标签，在标签面板上反馈给用户的都是一个“分类”，为什么会混乱呢？

**Comment by 88250** [comment]
已有的标签面板从设计之初就是为了行级标签汇总的，假设实现了块标签，则已有的标签面板就会混入块标签数据，这对于有的用户来说是变得混乱了。

**Comment by GH-W94** [comment]
> 已有的标签面板从设计之初就是为了行级标签汇总的，假设实现了块标签，则已有的标签面板就会混入块标签数据，这对于有的用户来说是变得混乱了。

好吧，内部代码层级我是门外汉。
能否找个其他法子将“块级标签”和“现有的标签”统一起来呢？将来即使属性示图出来了，能实现对块进行打标签了，但还是不能和现有标签统一起来，就形成了两套系统了，总归体验还是不舒服的。

**Comment by 88250** [comment]
这个要看社区是否有开发者愿意实现扩展了。
