### ISSUE TITLE
思源的标签功能有些许太”智能”了

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#7219]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如图，从Edge浏览器粘贴一个富文本的链接过来时，由于文本中含有#这个符号，自动就识别成为一个标签。

貌似没有必要在超链接的文本内容也可以打标签吧。

![image](https://user-images.githubusercontent.com/72953189/215948501-09632045-5c44-477e-a7fd-717ee6819fc3.png)

结合我之前的一个issue 也是类似的标签识别过强问题
#7181 

思源的标签识别很强大，但是也许可以设置在某些情况下能够自动忽略构建标签信息

### 描述可能的最优解决方案 Describe the optimal solution

常见的网络链接含有#应该不要识别，因为一旦识别，就会创建很多个标签。像 #7181 一样。

粘贴链接的富文本也不需要识别标签。

**Comment by 88250** [comment]
我这里测试在超链接中带 `#` 锚点的部分解析正常：

![image](https://user-images.githubusercontent.com/873584/215963216-57e00e11-dccb-49e0-ab5d-c1865f5d7006.png)

> 粘贴链接的富文本也不需要识别标签。

可以试下粘贴转义文本。

**Comment by tangjiahao2001** [comment]
@88250 
![image](https://user-images.githubusercontent.com/72953189/216001162-15eaefde-df60-4274-99f6-34e1d3c208ee.png)

可能是我们使用的浏览器不同

![image](https://user-images.githubusercontent.com/72953189/216001360-eb19c42e-a34c-42a6-8f2a-92922540ccbd.png)

我使用的edge浏览器复制链接的时候，是可以把tab栏的标题复制下来的，并不是把原来的链接作为粘贴到思源中的锚文本。

所以同样粘贴的结果带有#号，但是我这个粘贴结果看上去可以表示这个链接的含义。

如果是使用转移文本的话，就是单纯的粘贴链接的文本了，不能够点击跳转浏览器:）

**Comment by tangjiahao2001** [comment]
这个是浏览器相关的设置信息 @88250 
![image](https://user-images.githubusercontent.com/72953189/216002472-d2b8c54e-db82-4c44-b231-a9d55be117fe.png)

**Comment by tangjiahao2001** [comment]
我觉得这种粘贴链接的方式比单纯的只粘贴链接本身文本形式可以保存原链接更多的信息。但是他自带的描述文本会在粘贴在思源的时候自动解析为标签（如果含有#）

**Comment by 88250** [comment]
我这里使用 Edge 并按照该设置测试正常：

![image](https://user-images.githubusercontent.com/873584/216060718-506d8fb3-a507-49c7-a528-b153553f429e.png)

**Comment by tangjiahao2001** [comment]
我刚刚使用默认的主题还是出现这个问题
设备是：docker部署的，使用浏览器访问。
![image](https://user-images.githubusercontent.com/72953189/216213818-50420b1d-c506-4237-8047-25ca2b9f8816.png)
![image](https://user-images.githubusercontent.com/72953189/216214086-1567ba6f-6d19-4ae9-83d6-b3ed8c4dfced.png)

**Comment by tangjiahao2001** [comment]
@88250

**Comment by 88250** [comment]
忽略不要选中即可。

**Comment by tangjiahao2001** [comment]
大段文字同时复制过来他会自动保存，只有最后一个标签是提示你选择，就像这个#7181

**Comment by 88250** [comment]
两个 `#` 闭合的部分会识别为标签的，最后一个半开的也做提示。
