### ISSUE TITLE
优化：多级标题外观的区分

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#722]
不光是思源，绝大多数 markdown 编辑器基本都有个问题，就是 markdown 各级标题的区分太不明显了。

特别是在有图片这类大块元素的时候，很容易产生艾宾浩斯视觉错觉：

![image](https://user-images.githubusercontent.com/32661922/102004613-615a0e00-3d4d-11eb-9483-2eeb13163eb7.png)

在上图中，左右两个中心圆是一样大的。

在 markdown 编辑器中：

![image](https://user-images.githubusercontent.com/32661922/102004848-7899fb00-3d4f-11eb-931d-2c2ecfbc0d16.png)

在上面这个截图里，如果我不说，恐怕没几个人能一眼看出上面的「一级标题」和「二级标题」其实都是一级标题。

...

如果有谁看出来了......其实上面那句话是误导，左边那个是二级标题，右边那个是一级标题。

多级标题的外观区分不明显，就导致对文档结构把握困难，扭头看大纲其实不怎么方便。

样式区分问题解决方式很多，简单点的做法就是像 zettlr 一样提供个选项直接显示 # 号，现在思源把它们隐藏起来了，但是光标移到标题上时 # 号跳出，整个标题文字往右跳了一下，看起来反而不舒服；要么就继续隐藏 # 号，但是始终保留向右的缩进距离。也可以靠标题自动编号之类的方式来解决。现阶段的各个 markdown 编辑器对这个部分过度简化了。

**Comment by xulei-shl** [comment]
自定义css设置里，增加多级标题的颜色配置，就满足个人需求了

**Comment by 88250** [comment]
v0.5.46 中将标题标识改为默认显示了

![image](https://user-images.githubusercontent.com/873584/103341305-87a7d980-4ac1-11eb-9348-b05a0a1691df.png)

关闭提议了，谢谢。
