### ISSUE TITLE
2.7.0 2.7.1 创建数据快照卡住

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#7221]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

创建快照然后一直卡在这里，然后所有功能均无法使用。按照 kernel 的 log 在 repo 文件夹下找了下这个文件确实不存在。

尝试过重建索引，显示重建索引成功，校验也成功了，但是依旧无法创建快照。

### 期待的结果 Expected result

顺利创建数据快照，或如何解决这种问题

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/31495943/215990745-9490c8d2-1a84-4ce4-92c1-0d4e4c450f3a.png)

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: win11 思源 exe 桌面版
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10554985/siyuan.log)

**Comment by 88250** [comment]
试下重置数据仓库，可能是文件系统上这个文件不知道什么原因缺失了。

**Comment by XinLi0111** [comment]
已解决，感谢 D 大。
