### ISSUE TITLE
重建索引未完整执行

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7222]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

重建索引只到建立搜索索引卡住，后续步骤未执行，未显示【索引校验完毕】
重启恢复，用一段时间又会出现

### 期待的结果 Expected result

重建索引完整执行

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/101307399/216020539-2f5d8a10-4533-402d-8cb5-2c79a109bab7.png)

### 版本环境 Version environment

```markdown
- Version: v2.7.2
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
重建索引完成后最后一条状态栏消息记录不会消失。

**Comment by Temacc0531** [comment]
> 重建索引完成后最后一条状态栏消息记录不会消失。

所以这个是已经执行完成了的是吗，为啥有时最后会显示【索引校验完毕】有时不会😂

**Comment by 88250** [comment]
`校验索引` 是启动以后执行一次，后续每 10 分钟执行一次。

**Comment by Temacc0531** [comment]
> `校验索引` 是启动以后执行一次，后续每 10 分钟执行一次。

还有个问题想请教下
有了这个校验索引在启动的时候自动校验一遍之后，是不是那种手工拷贝data进行同步的方式就不需要像以前一样拷贝完启动再需要自己手动重建索引一次了，类似于如之前的版本一样启动会自动重建索引？

**Comment by 88250** [comment]
差不多，但是校验过程比较慢，这段时间如果编辑的话会报错。
