### ISSUE TITLE
github 发布的时候同时也发布 商店版 msix

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#7226]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我安装的是商店版。商店版本 每次更新都延迟好几天。 有些时候有些bug 想尽快更新。就无法等待。

### 描述可能的最优解决方案 Describe the optimal solution

github 同时发布 msix 的版本
用户可以直接下载更新商店版到最新的。

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

感谢万分。

**Comment by 88250** [comment]
是同时发布的，但是应用商店需要等待审核。

**Comment by heartacker** [comment]
我不是这个意思，我的意思是，再release 页面，同时也附带 msix 的安装包。 我看release 只有 exe 的安装包

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/216219626-01cab342-7586-442c-bca5-c9539370c0cf.png)

**Comment by 88250** [comment]
商店版不是 msix 安装包，而是 appx 的

**Comment by heartacker** [comment]
没关系，我就是这个意思，仿真就是提供一个商店版本的安装包。我们可以自己更新，而不必等商店审核

**Comment by 88250** [comment]
安装不了的，这个要上架以后商店签名才行的。

**Comment by heartacker** [comment]
我看别的也行。他们需要安装一个证书。我看很多在在appx 里面附带，然后需要自己手动导入一次。

也就是需要在首次安装的时候需要导入，之后都可以直接更新。

**Comment by 88250** [comment]
这个我不太清楚如何制作，你有空的话可以帮忙研究一下，谢谢。

**Comment by heartacker** [comment]
这个就是 msix的

https://github.com/MicaForEveryone/MicaForEveryone/releases/tag/v1.3.0.0

安装说明：
https://github.com/MicaForEveryone/MicaForEveryone/wiki/Installation#msix-file

主要是我也不懂这个开发

**Comment by 88250** [comment]
Electron 的好像打不了 msix 包
