### ISSUE TITLE
文档名去掉 `_id.sy` 段

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#723]
## 背景

目前文档块 id 是放在文件名上的，该设计存在一些缺陷：

* 无法支持文档块书签，因为书签元数据没有地方存储
* 从外部文件管理器浏览时视觉干扰太多

## 方案

* [x] 通过 kramdown 内联属性列表语法来将文档块 id 移动到文档正文内容底部进行存储 `{: id="" type="doc" bookmark=""}`
* [x] 自动迁移老数据格式

**Comment by skyls03** [comment]
感觉可以只把`_id`去掉
因为原本文件中包含很多id段
这些id段不符合markdown规范的

所以采用 `.sy.md` 作为拓展格式，可能会好一点

**Comment by 88250** [comment]
@skyls03 这个 issue 是去除文档名的，不是内容中的 ID，内容中的 ID 是去不掉的……

**Comment by skyls03** [comment]
@88250  id是实现块内容的基础，肯定是不能去掉，这我是知道的。

我的意思是文件名中的id可以去掉，但是文件内容中的id是不符合md规范。
如果继续使用`.md`格式，有点不好，因为用别的编辑器打开后，有很多乱七八糟的id，不是markdown该有的样子。
所以可以使用`.sy.md`后缀就可能比较合理一些，比如：
- 原本的文件名：文章_idxxxxxxx.sy.md
- 作者想要改的文件名：文章.md
- 我推介的格式：文章.sy.md

当然这种事情无所谓啦，什么格式都行
