### ISSUE TITLE
IFrame 块、视频块、音频块、超链接和图片的输入选框支持拉伸

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#7232]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前超链接和图片的填充窗口较小，只适合粘贴填充，而不方便修改
![image](https://user-images.githubusercontent.com/60436214/216232270-db530093-2e65-494d-bc40-1d811d9bff10.png)
 
![image](https://user-images.githubusercontent.com/60436214/216232427-36e8b670-08ce-4c8d-8b73-0b85ac0a7ae4.png)

### 描述可能的最优解决方案 Describe the optimal solution

能否把title的input改成textarea呢？

### 描述候选的解决方案 Describe the candidate solution

或者整个弹出菜单是支持拉伸的
![image](https://user-images.githubusercontent.com/60436214/216232604-55415a0d-0eac-4624-90c0-f06197e568a6.png)

**Comment by Soltus** [comment]
这确实是值得优化的一个细节，先记下

**Comment by Vanessa219** [comment]
收到

**Comment by choyy** [comment]
还不如直接加长好用
![图片](https://user-images.githubusercontent.com/68107073/217813130-35f3ae3e-f592-4255-82bd-c0809e1bb294.png)

**Comment by Vanessa219** [comment]
我稍微再加长一点吧。
