### ISSUE TITLE
行级备注内容仅保留文本内容

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#7233]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

在使用行级备注的时候无意中发现的，在默认主题中也可以复现。

如下文的录像所示，复制一段包含引用块的文本到行级备注的编辑框中，关闭编辑框后，备注悬浮可以正常显示文本。
但是刷新后，备注文本中的引用块格式的文本被渲染成引用块，然后行级备注的标签内容被渲染出来，看着有点乱。

### 期待的结果 Expected result

备注文本中的引用块格式失效，解析后作为普通文本显示。

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/58081876/216240274-82cc2fa2-4926-42b2-a12e-8bf5d2fa34c9.mp4

### 版本环境 Version environment

```markdown
- Version: 2.7.2
- Operating System: windows 10
- Browser (if used):
```

### 日志文件 Log file

none

**Comment by mozhux** [comment]
2天内我要拿到大佬的主题

**Comment by 88250** [comment]
肯定不能啊，这个 issue 就是消除非文本内容的。

**Comment by BryceAndJuly** [comment]
> 2天内我要拿到大佬的主题

这主题也没啥稀奇的，你要体验一下的话我发一份给你就行了。

**Comment by mozhux** [comment]
> @mozhux 这主题也没啥稀奇的，你要体验一下的话我发一份给你就行了。

@BryceAndJuly 可以的话发一份？ wutingkun2012@hotmail.com ，我论坛里也问了哈哈。

**Comment by BryceAndJuly** [comment]
@mozhux 那我直接在社区发给你吧，好像有个聊天的功能可以发文件。

**Comment by 88250** [comment]
v3.5.1 调整为保留标记符 https://github.com/siyuan-note/siyuan/issues/16662
