### ISSUE TITLE
聚焦列表后反向缩进触发状态异常

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#7234]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如题

### 期待的结果 Expected result

正确处理反向缩进，不会出现重建索引

### 截屏或者录屏演示 Screenshot or screen recording presentation

![聚焦重建索引](https://user-images.githubusercontent.com/74853597/216256268-74f117e8-70ed-4f52-a4d9-76391825251b.gif)

### 版本环境 Version environment

```markdown
- Version: 2.7.2
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

无需日志

**Comment by pisceswb** [comment]
同样是列表，触发状态异常。
![无标题视频](https://user-images.githubusercontent.com/104658457/216285839-1af40ca0-01eb-47f8-8424-c97c29bfced7.gif)

**Comment by 88250** [comment]
@pisceswb 感谢反馈，这个 issue 中一并处理。
