### ISSUE TITLE
Android 端返回桌面白屏

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7235]
https://ld246.com/article/1675320484990

**Comment by Danielypzhang** [comment]
升级了7.3问题还是没有解决华为鸿蒙系统 @88250

**Comment by winter60** [comment]
仍然存在此问题

**Comment by 88250** [comment]
我这里只有小米系统，所以无法确认其他系统上是否修复，麻烦录屏演示一下操作。

**Comment by winter60** [comment]
荣耀鸿蒙。

https://user-images.githubusercontent.com/23653326/217435977-8ac7be90-f85d-4de6-9891-de49e0571039.mp4

**Comment by 88250** [comment]
从通知栏点击返回呢？

**Comment by winter60** [comment]
通过应用任务切换是正常的，只是再次点击应用或siyuan:链接打开，就会白屏。

**Comment by winter60** [comment]
> 从通知栏点击返回呢？

我没有通知栏返回，荣耀和华为好像都是侧边栏返回，我这里跟从哪里返回好像没关系，只要不重复打开应用或点击siyuan：协议就不会白屏。

**Comment by 88250** [comment]
收到，这个可能是系统兼容问题，我们这里没有设备暂时无法调试定位，等后续有空再调整看看。

**Comment by 88250** [comment]
大概找到一个问题，在 https://github.com/siyuan-note/siyuan/issues/7308 中继续修复。
