### ISSUE TITLE
白屏无法查看

### ISSUE THREAD

**Issue by guidongyuan** [siyuan-note/siyuan#724]
### 描述问题 Describe the problem

注册登录完成后，输入一个笔记后，点击同步，然后不断弹出终端窗口，笔记软件直接全部白屏，杀掉应用后，再次打开，一直白屏状态。

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
If it is a problem of parsing and rendering, please post the original Markdown here
````````

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
是 Windows 上么？麻烦贴一下日志，谢谢。

**Comment by 88250** [comment]
另外，有可能是杀毒软件禁止了内核启动，如果是这个情况需要手动添加到杀软的信任列表里。我先关闭了，如果还有需要请继续跟帖，谢谢。
