### ISSUE TITLE
Tesseract OCR 语言包支持通过环境变量设置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7242]
语言包不要安装太多，否则会导致 OCR 缓慢甚至超时返回空结果，并且占用过多的系统资源。

优先读取环境变量 `SIYUAN_TESSERACT_LANGS`，例如 `SIYUAN_TESSERACT_LANGS=chi_sim+chi_sim_vert+eng+fra+osd`，不存在环境变量的情况下自动过滤，只保留：eng、chi*、fra、spa、deu、rus、osd

**Comment by eulores** [comment]
Dear D,

please consider the need of users to do OCR with languages outside the suggested list.
Maybe a configuration variable can be added instead, with these default values, but which can be modified if needed?

Thanks for your cosideration!
