### ISSUE TITLE
改进多设备同时同步数据的可靠性

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7245]
一个设备在同步开始前先获取云端文件锁：

* 如果获取成功则继续同步，并每隔 30s 更新一次文件锁时间戳，完成同步以后释放删除云端文件锁
* 如果获取失败则根据已有的云端文件锁时间戳判断是否其他设备的同步过程超时（当前时间>锁时间+65s）
  * 如果超时则继续本次同步，同样也是每隔 30s 更新一次文件锁时间戳，完成以后释放云端文件锁
  * 如果不超时则等待 5s 后继续尝试获取文件锁同步，尝试次数超过 3 次则放弃本次同步

**Comment by mozhux** [comment]
这种情况下，启动思源就编辑的情况下会是如何？ 同步没成功的情况下就新建日记或其他文档了又如何？

**Comment by 88250** [comment]
启动时会进行一次同步，拉取变更列表以后锁定本地相关文件，但是新建文档不受影响，这些情况和以前一样。

**Comment by mozhux** [comment]
@88250 新建日记这种就很危险啊，假设以前设备已经有过日记，然后本机在未同步完对应日记文档的情况下新建日记，那是不是就会出现同名文件重复了呢？

**Comment by 88250** [comment]
不会同名的，文件 ID 不一样。

**Comment by mozhux** [comment]
ID不一样，最终效果不一样，可能一台机器在文档A写，另外一个在文档B写。单独看不看文档树就以为同步丢数据了。是不是也可以未完成同步前搜新建文档或新建日记文档，并明确给出提示，同步未完成。

**Comment by 88250** [comment]
未完成同步也可以创建文档我觉得是特性，这样可以不用等待就能记录了。

**Comment by woniuxia** [comment]
D大，这个需求是不是也可以考虑下，配套使用
https://github.com/siyuan-note/siyuan/issues/6451

**Comment by 88250** [comment]
@woniuxia 锁机制成功的话相当于已经解决多设备同步的问题了。

**Comment by woniuxia** [comment]
@88250 又重新想了下，感觉还是不能完全解决多设备同步问题。
假如当前A设备抢到锁，B设备等待A将锁释放，那么B获取到锁后可以有两种表现：
1. 用云端新的覆盖本地旧的，会丢失本地未上传部分
2. 用本地覆盖云端，那么云端新上传的也会丢失

所以限制单设备修改会不会更好，如果不想限制单设备修改，那就告诉用户其他设备可能有未同步数据，有数据丢失风险。

**Comment by 88250** [comment]
思源的同步逻辑只可能发生 2，不可能发生 1。按照你后面的逻辑，就算放弃同步然后告诉用户潜在的冲突，那么后续如何处理？不可能让用户自己线下合并文件吧……

**Comment by woniuxia** [comment]
如果在用户刚打开第二设备的时候进行提示，可以让用户选择是否将当前已在线的设备上的数据进行一次同步，并踢掉当前在线的设备。
不过存在另外一个问题：如果有一个离线的设备有未同步的数据，就无法处理，可以考虑在离线设备启动时，进行判断，如果当前设备有未同步的数据，并且云端有最新的数据，让用户进行合并然后提交。

**Comment by 88250** [comment]
数据仓库的设计是基于本地优先的策略，复杂一点的情况是多个离线设备上都有未同步数据，按照你的设想应该无法处理合并。

**Comment by woniuxia** [comment]
对于多个设备，“本地”这个词是相对的，所以本地优先这个策略是不是可以考虑变通下，云端对于其他设备也可以是本地。
另外，要不先抛开一些复杂的系统设计，通过添加一些简单的机制，减少问题发生的概率：
1. 对于打开同步的用户，定时检测网络情况，进行提醒
2. 增大同步频率，对于一个合适的频率，可以保证当前云端就是所有设备共同承认的最新版本

**Comment by 88250** [comment]
本地没有相对的，云端就是云端，本地就是本地，因为云端不可能跑内核的，我指的是云端存储，比如 S3 或者 WebDAV。

这个锁机制就是为了减少问题发生的概率，网络情况每次同步前都会检查，数据未变动后 30s 自动执行一次同步、移动端在返回桌面时也会触发同步，我觉得频率已经很高了。

**Comment by Soltus** [comment]
![QCO}_224QQI5@YP20@LE _8](https://user-images.githubusercontent.com/83791825/216582720-7e75ffcb-839e-45c2-aedc-f122592f566a.png)
版本不一致弹窗提示用户就很合适

**Comment by pisceswb** [comment]
还没敢尝试该新同步方式，但有个疑问。
按照新方式，是不是在一个设备上手动点了同步后，在另一个设备上需要隔1分钟（当前时间>锁时间+65s）后点同步才有效？

**Comment by 88250** [comment]
同时同步才会出现锁定情况，会自动等待，如果超时的话会报错告知用户。一个设备上同步完再另一个设备上点同步不会出现锁定情况。
