### ISSUE TITLE
对超级快自动删除机制优化。

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7248]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

用超级快包裹多个块，然后引用超级快，就可以从“描文本”悬浮窗看到被包裹块的所有信息内容了，这应该是超级块“基础的使用方式”之一，这种方式我觉得很好，好很方便。

于是我用它来包裹一些段落文本。

但是在编辑时发现会“引用丢失”。

排查之下发现，在删除到到段落只剩下一个时，包裹单个段落块的超级块会被“自动删除”。

我觉得这种“自动删除”的处理方式不好，在这个使用场景下会因超级块被删除而“丢引用”。（在只剩两个块段落的时候，删除其中一个块就是为了在再添加编辑，而此时只剩一个块，超级块自动删除，不注意就丢引用）

### 描述可能的最优解决方案 Describe the optimal solution

建议：在删除时，超级块内只剩下“单个块”时不要自动删除超级块。

方案：可以在删除到只剩下单个块的时候，检查外层超级块是否存在“被引用”，存在被引用就不自动删除（如果考虑性能影响，我觉得就简单检测是否存在“引用计数标记”就可以了）。

### 其他信息 Other information

场景动图展示。

![超级快自动删除](https://user-images.githubusercontent.com/97731736/216558904-a60f4ac5-4c7d-41f0-9647-b383e4e0df37.gif)

**Comment by 88250** [comment]
这个是个优化，请看 https://github.com/siyuan-note/siyuan/issues/4653

对于定义块，删除时不会检查引用计数的，因为用户自己可以通过界面看到引用计数。

**Comment by UFDXD** [comment]
只是别扭就如此优化吗？ 超级块是组织内容的框架，既然可以被引用，那它也就内容的本身，引用关系就该被保护。亦或者说请将删除的权利给用户，而不是因为个别用户所为的繁琐别扭就为他优化删除。引用计数是在太容易被忽略，而且只存在两个块的情况下删除其一就是为了再超级块中再编辑。现实中盒子难道就不可以只放一个东西吗？有没有考虑过整理盒子时丢掉一个又立即又放入一个东西的可能？丢掉放入，盒子只剩一个东西状态的过程中，难道连盒子都要丢掉吗？盒子是什么？盒子是装东西的，既然需要手动将东西放入盒子，就应该在不需要的时候手动拿掉盒子，这个是否需要拿掉的以及拿掉的过程应该全程由人自己操作，而不是硬性插手。固然在某些方向这种硬性插手是“优化”，但若是优化带来其他负面的作用，那这个优化还可以叫优化吗？难打我不可以不要这个优化吗？现实是这个优化给我带来了使用超级块上是困扰，它很反智，很不合逻辑，让超级块在结合实际使用过程中，这个盒子就像“薛定谔的猫”一样不稳定。我注意到引用计数我会小心的操弄它，这个没问题，很完美。当我不注意引用计数的时候，操弄它就会出现问题，重新弄出盒子的过程很别扭。https://github.com/siyuan-note/siyuan/issues/4653 我看了，还是有人之后反对的。现在我也进行反馈了。说明问题存在。

**Comment by 88250** [comment]
删除时还是注意一下引用计数比较好。

**Comment by UFDXD** [comment]
实际操作是注意也没有用，我动图你看了吗？，最后删除的时候我停顿了一下，只要第二个块删除，超级块就消失。

**Comment by 88250** [comment]
我知道的，这里是两个问题，但是第一个问题之前已经说了，是个优化，在没有明显副作用的情况下就不考虑再改了。第二个问题要靠用户自己看引用计数来避免删除定义块。

**Comment by UFDXD** [comment]
编辑思维的过程，就是这个块内容没用了，我需要它消失。所以不是 留一个字符，保留第二个块编辑。只有保留一个字符保留这个块，超级块才不消失。这太反智了。

**Comment by UFDXD** [comment]
可以加个是否针对此优化的开关。我需要他！

**Comment by 88250** [comment]
这个细节不会考虑加开关了，开关太多用户都不会用了 😂

**Comment by UFDXD** [comment]
用户不会这么脆弱的，现代人开关一多都不会用了吗？这不可能。人们可以享受开箱即用的快感，但同时也需要定制化。因为人和人的习惯是不同的，思维方式也是不同的。思源可以在这个方面再细微体贴一点。

**Comment by 88250** [comment]
你这样考虑也有道理，不过我们现在没有时间解决你的需求，你可以试下 PR 帮助改进。

**Comment by UFDXD** [comment]
开关问题，我觉得完全不是问题，和开箱即用并不矛盾。因为可以预设值。用户习惯预设值不会动她。也想不起来动它。用户使用过程不符合自己的操作习惯，就自己去动开关。这个并不矛盾。

**Comment by 88250** [comment]
我也不是强烈反对加开关，但是我们现在是真的没有时间去加。

**Comment by Clouder0** [comment]
这确实是一个问题，超级块作为容器块，即使删到只剩一个 child 也仍应当保持容器特性。

比如用超级块组织一个小知识点 chunk，并进行引用、嵌入等。这个确实是非常常用的用法，我自己也频繁使用。  

删到只剩下一个 sub block 时直接移除超级块事实上破坏了对超级块的各种使用。这不仅是引用的问题，包括对超级块设置的各种属性等都会同时失效。对用户来说这是不符合预期的。

PS：而且我发现撤回后超级块虽然回来了，但属性依然无法找回。

![image](https://user-images.githubusercontent.com/41664195/216575187-d453bdff-887c-41e3-8712-8e81cfb98b5f.png)

![image](https://user-images.githubusercontent.com/41664195/216575440-0928676a-d783-4c01-af39-0203356e3dde.png)

![image](https://user-images.githubusercontent.com/41664195/216575900-b537f41c-f4d7-41b0-a087-3e29fca448a6.png)

最后一张图是 `Ctrl+Z` 的结果，超级块上设置的背景颜色丢失了。

**Comment by UFDXD** [comment]
> 我也不是强烈反对加开关，但是我们现在是真的没有时间去加。

哈哈，估计我糟糕的代码水平，入不了D大的法眼。你看完做的主题就知道了。现在还没适配

**Comment by UFDXD** [comment]
希望这个问题重新打开考虑，可以优先级靠后，也让我和其他反感的用户有个盼头

**Comment by 88250** [comment]
关闭的也会考虑，但是得有足够用户反馈才行，不然改来改去的，影响其他用户已有的体验。

**Comment by UFDXD** [comment]
之前的优化说实话也很方便，只是太方便了。方便过头了。就像一把快利的剑。

**Comment by GH-W94** [comment]
“超级块”作为思源的一大特色功能，目前却只是个半成品，只发挥了排版布局功能，对于更重要的组织笔记内容方面功能毫无建树。

我之前提出的“块标签（https://github.com/siyuan-note/siyuan/issues/7218#issue-1565369186）”功能，建议引入“块标签”功能并与现有标签统一起来，利用超级块组织笔记数据，然后通过给超级块打块标签，并与现有标签功能统一起来，这样就可以将笔记内容在“句、块、文档”三级通过标签实现多维度联动整理归纳。

可是却被D大以将块标签和现有标签统一起来后，会造成混乱，我不懂编程，也不知道什么用户会关注底层代码混乱，我觉得用户层面统一了，让用户用起来无感就可以了。

总之，有时候想和 D 大共振到一个频道上很难，一些看起来很合理的使用逻辑，总是被奇怪的理由否掉。

**Comment by 88250** [comment]
> 总之，有时候想和 D 大共振到一个频道上很难，一些看起来很合理的使用逻辑，总是被奇怪的理由否掉。

麻烦解释一下我说的什么理由奇怪，谢谢。

**Comment by Soltus** [comment]
> “超级块”作为思源的一大特色功能，目前却只是个半成品，只发挥了排版布局功能，对于更重要的组织笔记内容方面功能毫无建树。
> 
> 我之前提出的“块标签（[https://github.com/siyuan-note/siyuan/issues/7218#issue-1565369186）”](https://github.com/siyuan-note/siyuan/issues/7218#issue-1565369186%EF%BC%89%E2%80%9D) 功能，建议引入“块标签”功能并与现有标签统一起来，利用超级块组织笔记数据，然后通过给超级块打块标签，并与现有标签功能统一起来，这样就可以将笔记内容在“句、块、文档”三级通过标签实现多维度联动整理归纳。
> 
> 可是却被D大以将块标签和现有标签统一起来后，会造成混乱，我不懂编程，也不知道什么用户会关注底层代码混乱，我觉得用户层面统一了，让用户用起来无感就可以了。
> 
> 总之，有时候想和 D 大共振到一个频道上很难，一些看起来很合理的使用逻辑，总是被奇怪的理由否掉。

作为用户，我就不同意你这个在现有标签系统里塞入块标签的提议，非常奇怪且不合理

**Comment by GH-W94** [comment]
> > 总之，有时候想和 D 大共振到一个频道上很难，一些看起来很合理的使用逻辑，总是被奇怪的理由否掉。
> 
> 麻烦解释一下我说的什么理由奇怪，谢谢。

不是说你的理由奇怪，是你说的理由让我感到奇怪，可能是我考虑问题时不是从全局出发的吧

**Comment by 88250** [comment]
> 也不知道什么用户会关注底层代码混乱

另外，那个 issue 里面我说的混乱指的是产品设计的混乱，不是代码实现的混乱。

**Comment by GH-W94** [comment]
> > “超级块”作为思源的一大特色功能，目前却只是个半成品，只发挥了排版布局功能，对于更重要的组织笔记内容方面功能毫无建树。
> > 我之前提出的“块标签（[https://github.com/siyuan-note/siyuan/issues/7218#issue-1565369186）”](https://github.com/siyuan-note/siyuan/issues/7218#issue-1565369186%EF%BC%89%E2%80%9D) 功能，建议引入“块标签”功能并与现有标签统一起来，利用超级块组织笔记数据，然后通过给超级块打块标签，并与现有标签功能统一起来，这样就可以将笔记内容在“句、块、文档”三级通过标签实现多维度联动整理归纳。
> > 可是却被D大以将块标签和现有标签统一起来后，会造成混乱，我不懂编程，也不知道什么用户会关注底层代码混乱，我觉得用户层面统一了，让用户用起来无感就可以了。
> > 总之，有时候想和 D 大共振到一个频道上很难，一些看起来很合理的使用逻辑，总是被奇怪的理由否掉。
> 
> 作为用户，我就不同意你这个在现有标签系统里塞入块标签的提议，非常奇怪且不合理

当属性视图出来后，能给块打标签了，但所打的标签不能与现有标签功能的标签共享，形成了两套标签，用起来你不觉得别扭？

**Comment by GH-W94** [comment]
> > > 作为用户，我就不同意你这个在现有标签系统里塞入块标签的提议，非常奇怪且不合理
> > 
> > 
> > 当属性视图出来后，能给块打标签了，但所打的标签不能与现有标签功能的标签共享，形成了两套标签，用起来你不觉得别扭？
> 
> 那是属性吧，虽然可以当标签用，但从设计理念上来说根本就不是一个东西，混在一起才别捏

标签难道不是一种属性吗？

**Comment by UFDXD** [comment]
你们，真是够了啊，话题都跑偏了。
