### ISSUE TITLE
链接多个反链时反链面板不会默认展开一层

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7249]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

链接单个反链时反链面板默认展开一层，但链接多个反链时反链面板则是默认折叠

### 期待的结果 Expected result

反链面板默认展开一层

### 截屏或者录屏演示 Screenshot or screen recording presentation

![test](https://user-images.githubusercontent.com/101307399/216570524-44bcb619-a182-43cc-a106-f23217ca53c0.gif)

### 版本环境 Version environment

```markdown
- Version: v2.7.2
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
中间有个个 `、` 的话不会展开，可以换成空格试试。

**Comment by Temacc0531** [comment]
这个是因为`、`就是被识别成底下第一层内容了吗😂

**Comment by 88250** [comment]
传递型和关联型双链的区别，不过标点符号是否计入我不太确定，我们目前是计入的。

**Comment by Temacc0531** [comment]
明白了，代码以为是用作关联型双链了，空格也可以的

**Comment by 88250** [comment]
是的，空格不计入，单独处理过。
