### ISSUE TITLE
希望可以一键导入有道云笔记

### ISSUE THREAD

**Issue by 1332987** [siyuan-note/siyuan#725]

**Comment by 88250** [comment]
你好，有道云好像有导出 Markdown 的功能，可以试试看。直接导入不太可能，因为有道云好像是私有格式的……

**Comment by 1332987** [comment]
你好，可以提供一下你们支持的md格式吗?我写一个工具类转一下

**Comment by 88250** [comment]
思源可以解析符合 GFM/CommonMark 规范的 Markdown 文件。
