### ISSUE TITLE
块引计数浮窗面包屑未高亮

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7251]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![悬浮窗面包屑没有高亮](https://user-images.githubusercontent.com/97731736/216637024-9ec96472-84a0-46e3-8159-89567c38d9e8.gif)

### 期待的结果 Expected result

1

### 截屏或者录屏演示 Screenshot or screen recording presentation

1

### 版本环境 Version environment

```markdown
- Version: v2.7.2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by Vanessa219** [comment]
为了减少不必要的层级，面包屑上列表会被省略。可以引用列表和列表项试一下。由于面包屑上不存在列表，因此无法进行高亮。
