### ISSUE TITLE
winPC从待机中恢复，思源笔记内核连接中断

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7255]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

1、思源笔记最小化到托盘
2.、待机
3、从待机中恢复，打开思源笔记
4、若右上角立即出现“数据同步中”的提示，必会导致思源笔记内核连接中断（延后1-3秒）；不出现提示，没有问题。

### 期待的结果 Expected result

请修复

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/104658457/216752276-a04b8557-97bd-47fb-840f-f065170cef84.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.3-dev1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
麻烦上传内核日志。

**Comment by pisceswb** [comment]
I 2023/02/04 14:10:18 runtime.go:49: kernel is booting:
    * ver [2.7.2]
    * arch [amd64]
    * pid [2724]
    * runtime mode [prod]
    * working directory [C:\Program Files\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\siyuan\SiYuan]
I 2023/02/04 14:10:18 conf.go:320: user has disabled [Google Analytics]
I 2023/02/04 14:10:18 runtime.go:94: use network proxy [system]
I 2023/02/04 14:10:18 serve.go:108: kernel [pid=2724] http server [127.0.0.1:59728] is booting
I 2023/02/04 14:10:19 working.go:396: built-in pandoc [ver=2.19.2, bin=D:\siyuan\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/02/04 14:10:19 tesseract.go:123: tesseract-ocr enabled [ver=v5.3.0.20221222, langs=chi_sim+eng+osd]
I 2023/02/04 14:10:19 sync.go:69: sync before boot
I 2023/02/04 14:10:19 repository.go:834: boot get sync cloud files elapsed [0.15s]
I 2023/02/04 14:10:19 blocktree.go:381: read block tree [1.0 MB] to [D:\siyuan\SiYuan\temp\blocktree], elapsed [0.02s]
I 2023/02/04 14:10:19 conf.go:615: database size [13 MB], tree/block count [84/3759]
I 2023/02/04 14:10:19 working.go:157: kernel booted
I 2023/02/04 14:10:20 box.go:74: auto stat [trees=84, blocks=3759, dataSize=140 MB, assetsSize=138 MB]
I 2023/02/04 14:10:20 disk.go:33: disk usage [total=859 GB, used=330 GB, free=529 GB]
I 2023/02/04 14:10:20 serve.go:121: reverse proxy server [127.0.0.1:6806] is booting
I 2023/02/04 14:11:22 repository.go:935: synced data repo [provider=3, ufc=2, dfc=0, ucc=2, dcc=0, ub=12 kB, db=21 kB] in [1.11s]
I 2023/02/04 14:11:56 process.go:97: no active UI proc count [1]
I 2023/02/04 14:12:02 repository.go:935: synced data repo [provider=3, ufc=1, dfc=0, ucc=1, dcc=0, ub=12 kB, db=21 kB] in [0.43s]
I 2023/02/04 14:12:30 liandi.go:310: get cloud user elapsed [10162ms]
I 2023/02/04 14:12:33 repository.go:935: synced data repo [provider=3, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=21 kB] in [0.04s]
I 2023/02/04 14:12:33 repository.go:935: synced data repo [provider=3, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=21 kB] in [0.05s]
I 2023/02/04 14:13:31 repository.go:935: synced data repo [provider=3, ufc=2, dfc=0, ucc=2, dcc=0, ub=12 kB, db=21 kB] in [0.50s]
I 2023/02/04 14:14:35 process.go:97: no active UI proc count [2]
I 2023/02/04 14:14:35 process.go:99: confirmed no active UI proc, exit kernel process now
I 2023/02/04 14:14:35 conf.go:397: exiting kernel [force=false, execInstallPkg=1]
I 2023/02/04 14:14:36 sync.go:113: sync before exit
I 2023/02/04 14:14:36 repository.go:935: synced data repo [provider=3, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=21 kB] in [0.27s]
I 2023/02/04 14:14:36 database.go:1114: closed database
I 2023/02/04 14:14:36 conf.go:761: cleared workspace temp
I 2023/02/04 14:14:37 conf.go:443: exited kernel
I 2023/02/04 14:20:49 working.go:119:

**Comment by 88250** [comment]
感谢，稍后改进了试试。

**Comment by 88250** [comment]
eea6c9468a229fdb9da3ee7a5073d1682f2ccf60
