### ISSUE TITLE
不能正常输入~符号

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7256]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

例如，今天温度是10~20℃，明天温度是15~25℃。
会将“~20℃，明天温度是15~”变成下标。
![image](https://user-images.githubusercontent.com/104658457/216758990-2e9f6820-a30f-419b-86f1-12eb71557fcc.png)

### 描述可能的最优解决方案 Describe the optimal solution

建议两个~符号间，含有其它标点符号（如逗号，句号）的话，不要作下标处理。

**Comment by 88250** [comment]
这个是按照 Markdown 语法解析的，你可以加个转义符 `\~`。
