### ISSUE TITLE
标签自动合并

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7257]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

当我#xxxx添加一个标签以后，我再#添加另外一个标签。
两个标签就合并在一起，自动创建了一个新标签。
![image](https://user-images.githubusercontent.com/37429029/216766458-bda9f3da-dfb6-460e-9eec-aa07f80b5049.png)

### 期待的结果 Expected result

两个相邻的标签之间应该是自然隔开的，
用户不需要每添加一个标签，就要手动空格一下
![image](https://user-images.githubusercontent.com/37429029/216766469-6e0f8819-0ca0-463c-99c6-ab5cc0c48d95.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.2
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
这个是特性，没有空格分隔的话自动合并。

**Comment by AugustTuan** [comment]
> 这个是特性，没有空格分隔的话自动合并。

这个特性有出处吗？
我没有理解这个特性的作用。 
就比如我在github上面
#选择一个issue，然后#选择第二个issue。
两个issue的文本合并了？

**Comment by AugustTuan** [comment]
> 这个是特性，没有空格分隔的话自动合并。

我是可以自己改变操作习惯，提醒自己每次#添加一个标签，要添加第二个标签就手动空格一下。
但是相邻的标签自动合并，这个我自己对标签是高频率使用的
但是我没有弄明白这个特性的用处，我单纯感到很不方便

**Comment by 88250** [comment]
基本所有行级元素都是这个规则，可以避免创建相邻的相同元素。比如输入 `**foo****bar**` 后形成了两个粗体元素，继续输入任何字符的话就会自动合并为 `**foobar**`，这样可以避免相邻的元素无法区分和一些语法问题。

**Comment by AugustTuan** [comment]
> 基本所有行级元素都是这个规则，可以避免创建相邻的相同元素。比如输入 `**foo****bar**` 后形成了两个粗体元素，继续输入任何字符的话就会自动合并为 `**foobar**`，这样可以避免相邻的元素无法区分和一些语法问题。

明白了，谢谢解答。
另外还有一个需求， 就是可否支持给标签定义颜色。
![image](https://user-images.githubusercontent.com/37429029/216798211-68d78df6-fe21-460d-a3ba-3f6081d5f9b4.png)
![image](https://user-images.githubusercontent.com/37429029/216798246-1b9a0faa-d327-4f47-95b5-e38fcd93a96f.png)
![image](https://user-images.githubusercontent.com/37429029/216798237-c9424ca1-eee2-42c6-84ac-4f1a0365e01b.png)

现在思源的所有标签都一个颜色，多个标签排在一起眼睛都花了。

**Comment by 88250** [comment]
这个可以自己加字体颜色来区别，或者通过自定义 CSS 给相同内容的标签赋值样式。

**Comment by AugustTuan** [comment]
> 这个可以自己加字体颜色来区别，或者通过自定义 CSS 给相同内容的标签赋值样式。

用字体颜色区别的话
同一个标签，每次添加，都需要手动改一次字体吗？

**Comment by 88250** [comment]
是的

**Comment by AugustTuan** [comment]
> 是的

好吧😭
D大，你平常用思源记笔记打标签吗？一般都是什么时候使用标签。 
你说思源的标签和其他笔记的标签不等价。
思源的标签不是用来标记一个内容块，提供一些辅助性的信息的吗？
我怀疑我是不是用错了

**Comment by 88250** [comment]
我用标签是管理待办 #TODO# 和 #注意实现# 这样的内容，基本不用于分类。

对于块的元数据目前可以通过属性进行记录，但是目前通过属性查询块比较麻烦，需要用到 SQL（用户只能里面有个 SQL 的例子），这个后面会通过属性视图 #2829 进行简化。
