### ISSUE TITLE
为页面 `html` 标签添加属性 lang、data-theme-mode、data-light-theme、data-dark-theme 

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7259]

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/7259

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 当用户使用深色主题导出 PDF 时, 虽然加载了浅色主题的样式文件, 但是的预览窗口的 `html` 标签的 `data-theme-mode` 属性依然设置为了 `dark`, 这会导致导出预览与实际导出内容均出现异常

因此导出 PDF 的预览窗口与实际导出时 `html` 标签的 `data-theme-mode` 属性应该强制设置为 `light`
