### ISSUE TITLE
ctl+P搜索bug

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7261]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

自从我在一个月前，搜索过一次“内存调优”

我后面每次使用ctl+P，搜索框都会默认显示“内存调优”

卸载重装、更新都是这样
不知道为什么会这样

### 期待的结果 Expected result

搜索框每次打开应该是干净的

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/37429029/216812307-5f597547-15fb-4e86-b1ad-2fbfa6ab47c5.mp4

### 版本环境 Version environment

```markdown
- Version: 2.7.2
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
移除一次命名查询试试。

**Comment by 88250** [comment]
参考 https://ld246.com/article/1675562282494

**Comment by AugustTuan** [comment]
哦哦，可以了，谢谢
