### ISSUE TITLE
增加上一级笔记对下层笔记的预览功能，参照Trilium，可以很方便知晓下层的笔记。DailyNotes可以也这样逐天列表显示。

### ISSUE THREAD

**Issue by coffeemirror** [siyuan-note/siyuan#7264]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

子笔记的初衷很好，但显示上层笔记的时候，可以在下方预览子笔记的缩略图，像Trilium一样，这样查看起来方便的多。[TriliumNotes](https://ibb.co/6WTW0Y6)

### 描述可能的最优解决方案 Describe the optimal solution

可参照上述triliumnote的方案，将下方子笔记的缩略图显示于上层笔记中

### 其他信息 Other information

DailyNotes只能点一下查看一下的也不方便，还是以缩略图或列表的方式查看比较方便，如果上述上级笔记显示子笔记功能完善，这dailynotes自然也可以顺便解决。dailynotes的显示可以参照logseq的解决方案。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/2711
