### ISSUE TITLE
点击开启自定义主题后整个软件一片黑，无法设置回来。

### ISSUE THREAD

**Issue by k650dg4d2** [siyuan-note/siyuan#7266]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [x] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/32454224/216948505-74de5c6a-9ec9-4345-84f8-f8768782658a.png)
点击了这个选项，然后变成了这样
![image](https://user-images.githubusercontent.com/32454224/216948741-23f0671d-4e3a-4645-aeff-2bc4ec798bec.png)
然后我点击设置或者别的选项什么也显示不出来

### 期待的结果 Expected result

期待可以变回来

### 截屏或者录屏演示 Screenshot or screen recording presentation

![VeryCapture_20230206183358](https://user-images.githubusercontent.com/32454224/216949626-5000205a-4db7-43c4-957b-a92151f2bc85.gif)

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
什么也看不见了
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10662113/siyuan.log)

**Comment by 88250** [comment]
试试删除工作空间/conf/appearance/ 文件夹后重启。

**Comment by k650dg4d2** [comment]
> 试试删除工作空间/conf/appearance/ 文件夹后重启。

恢复了，但是希望修复一下这个问题
