### ISSUE TITLE
新特性，增加可视化SQL查询

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#7267]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前虽然能够通过写SQL语句实现自定义查询，但是对于像我一样的普通用户来说，实在不知道如何写才能达到目的。我想思源有一个很大的特性就是能够自定义笔记的使用，比如搜索聚合在一起等等。但是需要有比较高的程序基础才能使用。

### 描述可能的最优解决方案 Describe the optimal solution

我希望能够有可视化的界面能够实现SQL的功能，比如

在____（笔记范围）范围下查找____（类型）的笔记，是否包含标题，是否含有某个标签，类型是什么。

能够通过点击选项或者勾选来实现筛选内容并显示。

目前的通过写SQL代码的方式，我已经看了思源的官方文档不小5遍了，跟着示例一起使用过，也思考了很久，最后也都以失败告终，真心感觉这个太难用了。

还一个方案就是可以在查找的基础上可以实现导出实现的SQL语法，使用者可以将其复制到笔记中常驻。

思源很好用！非常感谢你的软件开发！！！

**Comment by 88250** [comment]
之前考虑过，但是要做通用的 SQL 可视化查询在技术上不太现实，所以一方面可以关注社区开发者提供的一些特定场景的挂件，另一方可以关注属性视图 #2829

**Comment by 88250** [comment]
试试根据 parent_id 和 type 字段过滤

**Comment by tangjiahao2001** [comment]
有示例吗？我并不是很理解这个😂

**Comment by 88250** [comment]
我这里没有示例，你得自己学下 SQL

**Comment by tangjiahao2001** [comment]
subtype是获取子类型吗？

**Comment by tangjiahao2001** [comment]
然后遍历？

**Comment by 88250** [comment]
抱歉我目前没有时间帮助你解决 SQL 方面的疑问，你可以试下到链滴上提问，或者加思源用户 QQ 群咨询一下其他用户，谢谢。
