### ISSUE TITLE
比较数据快照时，时间戳显示错误

### ISSUE THREAD

**Issue by tswwe** [siyuan-note/siyuan#7269]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [x] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

1. 在**数据历史 🞂 数据快照**中，选中两个数据快照并执行**比较**。
2. 你会发现，比较界面中，左右面板的时间戳写反了。

### 期待的结果 Expected result

把左右面板的时间戳调换过来

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Snipaste_2023-02-06_22-56-02](https://user-images.githubusercontent.com/36465489/217005102-d7434aa0-e641-4ffc-b084-9196d7126099.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.2
- Operating System: Win10 22H2
- Browser (if used):
```

### 日志文件 Log file

暂不提供

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/7244
