### ISSUE TITLE
搜索结果不要只显示一个块，请恢复原先含有上下文的形式

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7274]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

2.7.3-dev4搜索结果非常不好，不符合常规习惯
现在搜索结果只显示一个块，不能联系上下文。请恢复原来含有上下文的形式，谢谢！
双击搜索到的条目后，仍然只显示一个段落块的聚焦，想看上下文退出聚焦，又定位到文章顶部，找不到搜索到的块了。
体验很差，忘改回原搜索显示方式，以整篇文章的内容显示，双击搜索到的内容后，也到整篇文章中，不要聚焦到块。
虽然每段一个块是一个特色，但对于大部分人来说，只有链接时候方便，正常编辑文档时，不希望过度强调块，以符合正常习惯。
搜索不只看关键字，更重要的是看关键字附件有什么内容

### 描述可能的最优解决方案 Describe the optimal solution

请恢复原搜索结果的显示方式，谢谢

### 描述候选的解决方案 Describe the candidate solution

请恢复原搜索结果的显示方式，谢谢

### 其他信息 Other information

请恢复原搜索结果的显示方式，谢谢

**Comment by pisceswb** [comment]
在单篇文章中的搜索，这种方式是最好用的。
![image](https://user-images.githubusercontent.com/104658457/217172778-18a5e9f8-f950-4a57-b456-df9b9977aa09.png)

**Comment by pisceswb** [comment]
例如，搜索“内容如下”四个字，按现在的搜索方式，根本得到的想要的“内容如下”中的下面的内容

**Comment by 88250** [comment]
如果搜索结果块位于折叠块中，则双击进入是聚焦，这个是特性。

**Comment by pisceswb** [comment]
这种方法是真找不到位置，怎样都找不到在原文中的哪儿，看不到上下文。

**Comment by 88250** [comment]
可以在面包屑块标浮窗上看的，不这样设计的话就无法定位折叠块下的搜索结果了。

**Comment by pisceswb** [comment]
在找呢，找了半天了也没有找到是折叠在哪儿了，真让人着急

**Comment by pisceswb** [comment]
有办法把所有折叠都展开吗？我先复制到Word中查找一下，应急。看来确实折叠起来了，现在复制到Word中，也没有折叠内容。

**Comment by 88250** [comment]
列表折叠的话只能一层一层展开。

**Comment by pisceswb** [comment]
怎样都找不到！！！！！！！！

**Comment by pisceswb** [comment]
全选，复制纯文本，粘贴到TXT中，终于找到了。以后再也不敢用大纲目录了，自己都不知道怎么折叠的，也不知道折叠到哪儿了，搜索到了也展不开，找不到

**Comment by pisceswb** [comment]
对照了一下，要搜索的内容没有折叠起来。但将全文复制到Word或TXT中，没有了部分内容。
可能原因为，当前文档为其它文档中删除的零碎内容，含有标题等各种乱七八糟的格式内容，全部直接都拖到当前文档中了。可能是这样，导致，不知怎么就把部分没有折叠起来的内容，认为是折叠状态了。能看到不是折叠状态，但搜索和复制到其它地方都被认为了是在折叠状态

**Comment by 88250** [comment]
有可能是之前折叠标题下的块会有问题，这个后续还需要观察和重现步骤。

**Comment by pisceswb** [comment]
辛苦D大！希望优化一下搜索功能，对内容多的用户，搜索功能很重要。
现在的搜索只显示关键词在的那一个段落块（没有折叠的也是聚焦显示段落块），双击到文章正文后，还是聚焦到段落块，退出聚焦后，定位到了文章开始位置。

**Comment by 88250** [comment]
@Vanessa219 请领导看一下这里。

**Comment by 88250** [comment]
@pisceswb 下个版本修复 https://github.com/siyuan-note/siyuan/issues/7276
