### ISSUE TITLE
通过 `Alt+M` 最小化后焦点回到先前的窗口

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#7275]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

通过alt+M最小化后, 焦点没有回到先前的窗口
复现步骤:
打开一个有输入框的应用,比如chrome, 光标放于地址栏, 确保能输入文本
此时按下alt+M打开思源, 再次按下最小化思源,  此时视野回到chrome了,但是输入焦点却没有了, 不仅如此, ctrl+F等快捷键也无法使用, 
但是如果是通过点击思源最小化按钮来最小化, 那么焦点是能够正常回到chrome的

### 期待的结果 Expected result

`

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
`
```

### 日志文件 Log file

`

**Comment by iamqiz** [comment]
@88250  刚试了 . hide() 改成 minimize() 可以解决

**Comment by 88250** [comment]
这样还能缩小到托盘区吗？

**Comment by iamqiz** [comment]
minimize 单独用, 任务栏还是有图标的,
hide 和minimize 一起用, 可以隐藏,同时也不会失去焦点

**Comment by 88250** [comment]
能重现的，截图或者 PR 一下你改动代码的地方，谢谢。

**Comment by iamqiz** [comment]
app/electron/main.js

![Snipaste_2023-02-07_17-24-35](https://user-images.githubusercontent.com/48077521/217204453-5d25706a-aa30-4df9-b72b-30e68662cfb4.png)

**Comment by 88250** [comment]
谢谢，我直接按照你的方案修改吧。
