### ISSUE TITLE
非折叠块搜索跳转不应该聚焦

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7276]
https://github.com/siyuan-note/siyuan/issues/7252 的实现有问题，迭代到顶层块为空时应该返回 false。

**Comment by pisceswb** [comment]
谢谢！
请问，搜索内容在折叠块中时，退出聚焦，能在全文模式下定位到折叠块条目上吗？（可以不用自动展开）
另外，能够高亮或着重标注一下哪个块是折叠块吗？现在的标记不够明显，配不上折叠这么大这么重要的动作。

**Comment by 88250** [comment]
折叠存在多层关系（比如容器块的折叠嵌套折叠），如果要定位的话好像不大好界定定位到哪一层折叠父块比较合适。小三角已经是着重标记了，这个之前调整过。

**Comment by pisceswb** [comment]
搜索过程不对原文内容进行任何更改，那就是定位到原文中能看到的，没有折叠的那一个块上。
小三角只有在鼠标放到那一个块上的时候才会显示，鼠标不放到那一个块上的时候，不知道这一个块是折叠块。要找的话需要鼠标每个试一下。能否改变一下，不用鼠标放到上面，一眼就能认出这个块是折叠块？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月7日(周二) 下午5:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 非折叠块搜索跳转不应该聚焦 (Issue #7276)




 
折叠存在多层关系（比如容器块的折叠嵌套折叠），如果要定位的话好像不大好界定定位到哪一层折叠父块比较合适。小三角已经是着重标记了，这个之前调整过。

**Comment by 88250** [comment]
现在应该就是定位到非折叠的这一层，但是只能通过聚焦定位。

还有个圆点可以看到折叠状态：

![image](https://user-images.githubusercontent.com/873584/217216171-e47ad98f-fcb6-4dad-bd0a-3006e624e6e2.png)
