### ISSUE TITLE
导入 Markdown 时解析报错

### ISSUE THREAD

**Issue by chars6** [siyuan-note/siyuan#7279]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

https://github.com/xiaoy-sec/Pentest_Note

下载这个项目，在siyuan中选择导入Markdown文件夹导入的数据不全或者卡死。

### 期待的结果 Expected result

可以导入全部数据。

### 版本环境 Version environment

```markdown
- Version: 2.7.3
- Operating System: Windows 11
- Browser (if used):
```

### 更多信息 More information

测试果通过Markdown文件夹数据不全的文件，单独导入Markdown文档可以导入。

**Comment by chars6** [comment]
> 日志中出现了一个异常的文件：`\data\20211119083744-b90ocyk\.siyuan.sy`，这个文件不是思源生成的，你移除以后再试试。

这个文件删除后打开思源会自动出现。

**Comment by 88250** [comment]
删一下 siyuan.log，然后重新走一遍重现过程，再发一下日志。

**Comment by chars6** [comment]
[system-log.zip](https://github.com/siyuan-note/siyuan/files/10675306/system-log.zip)
这是重现过程的日志。

**Comment by chars6** [comment]
> 删一下 siyuan.log，然后重新走一遍重现过程，再发一下日志。

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10675313/system-log.zip)
这是重现的日志。

**Comment by 88250** [comment]
这份日志里面没有这个报错，等会我试下导入你前面提到的 Markdown 文件夹试试。

**Comment by 88250** [comment]
已经定位到问题，下个版本修复，感谢反馈。

**Comment by 88250** [comment]
等会你看关联提交就知道了。
