### ISSUE TITLE
bug很多

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#728]
使用版本：当前最新的0.53
1、强调和加粗，嵌套使用时，解析错误
比如，\*\*\*aaa\*\*xxxxxx\*\*bbb\*\*xxxxxx\*
期望的效果应该是：aaa(加粗+强调)xxxxxx(强调)bbb(加粗+强调)xxxxxx(强调)
实际的效果却是：aaa(加粗+强调)xxxxxxbbb(强调)\*xxxxxx\*
2、删除线，如果自定义效果（我是直接去除删除线的效果，修改颜色），预览没有改变，还是原始的删除线
3、删除线和加粗，嵌套使用时，解析错误
正常使用可以，但是遇到加粗末尾是中文符号的，比如，。）的，加粗效果丢失
比如，\~\~aaa\*\*bbb）\*\*\~\~
期望的效果应该是：aaa(删除线)bbb）(加粗+删除线)
实际的效果却是：aaabbb）(删除线)
4、在设置、外观、自定义当前主题Midnight中修改任何一个选项，custom.css末尾都会加一大段重复代码
---
希望加入的功能，
1、图片功能，希望和typora一样
1）图片自动居中
2）右键图片，能修改图片缩放百分比
3）图片保存本地时，能 复制到本地=./.${filename}.images，也就是每个md文件的图片，会对应放到以这个md文件名命名的隐藏文件夹中
2、希望加入下划线<u></u>的快捷键
3、希望加强 嵌套使用，实在很多bug。

**Comment by 88250** [comment]
你好，

* 思源是遵循标准 Markdown 规范（GFM/CommonMark）实现的解析，加粗强调删除线相关的问题请看[这里](https://ld246.com/article/1597581380183)
* 定制外观 custom.css 应该没有问题，请贴图看下哪些代码重复了……
* 图片相关改进已经在着手，v0.5.4 会自动居中，v0.5.6 将支持调整大小

感谢指出思源的不足，我们会继续努力的。我先关闭了，如果还有反馈建议请继续跟帖，谢谢！

**Comment by yeshaopeng6688** [comment]
![image](https://user-images.githubusercontent.com/69628966/102071999-37334980-3e3c-11eb-9f6e-97de42d55200.png)

**Comment by 88250** [comment]
@yeshaopeng6688 收到，稍后排查，谢谢。

**Comment by yeshaopeng6688** [comment]
![Uploading image.png…]()

**Comment by 88250** [comment]
老铁，这个图裂了，没传完……

**Comment by yeshaopeng6688** [comment]
= =，口述吧，我在custom.css修改完以后，确实可以立马渲染（这点比typora好多了。），但是很经常，我打开设置，或者是重启siyuan，custom.css就恢复默认了，这就有点麻烦了，需要每次重新复制修改...

**Comment by 88250** [comment]
哦，我明白了……那个 custom.css 不能手改，程序会覆盖的，如果需要手动扩展，请参考帮助文档中的自定义主题，谢谢。

**Comment by yeshaopeng6688** [comment]
好的，我去瞅瞅。辛苦了

**Comment by yeshaopeng6688** [comment]
请问，后续版本会增加大纲视图的计划么？
- 大纲视图（可折叠）
- 全部展开
- 全部折叠
- 大纲视图（无折叠）
- 最后，预览的时候 大纲视图点击无反应。。

**Comment by 88250** [comment]
你好，你指的大纲是目前的目录还是想幕布那种大纲式编辑？如果是后者的话短期内没有计划……

**Comment by yeshaopeng6688** [comment]
幕布的我没用过。。我指的是typora的。
另外，发现一个小问题，就是代码高亮，shell的貌似不起作用，换成bash就好了。。
![image](https://user-images.githubusercontent.com/69628966/102481584-de162080-409c-11eb-9e99-d2d553fbdb2a.png)
![image](https://user-images.githubusercontent.com/69628966/102481647-f5eda480-409c-11eb-9a02-e26955298417.png)

**Comment by yeshaopeng6688** [comment]
引用复制好以后，好像不可以再剪切，复制，这样如果一堆引用在一起，修改起来很麻烦。
![image](https://user-images.githubusercontent.com/69628966/102567149-dd709f00-411b-11eb-9dc1-26f362d01402.png)

**Comment by yeshaopeng6688** [comment]
引用，能不能像链接一样，按住ctrl，左键点击才显示，而不是鼠标悬浮就显示，这样有的时候编辑引用名字很麻烦。

**Comment by yeshaopeng6688** [comment]
此外，对于引用名字来说，如果是标题，引用名字是标题名字还好；但如果是段落、列表等等，引用名字就是这些段落列表的内容，这样的引用名字没有什么意义，看看能不能根据引用的类型不同，给使用者自己自定义引用名字。

**Comment by 88250** [comment]
目前的编辑交互的确有点不流程，稍后我们改改看。

**Comment by yeshaopeng6688** [comment]
嗯嗯，我知道可以修改。但更流畅的使用是不是，根据类型来判断引用名字。
- 标题，直接就是{{.title}}
- 文本，光标定位到引用名字内
![image](https://user-images.githubusercontent.com/69628966/102567957-8370d900-411d-11eb-8b86-9285d1de440a.png)
因为确实默认用的{{.text}}，作为引用名字不太合理，这边最好直接是可以自定义，而不是我复制好了，还得手动删除那一串引用名字（主要有的时候鼠标悬浮就显示，太影响删除了）

**Comment by 88250** [comment]
`{{.title}}` 已经废弃了……目前统一用的是 `{{.text}}`。后面会做内容块命名和别名，如果有名字的块默认就用名字了。

**Comment by yeshaopeng6688** [comment]
- 0.54.1最新版本，全选复制代码框的代码
 - 比如java、xml的，会把\`\`\`一起复制
 - 但比如bash的，就不会复制\`\`\`
- 希望引进一下typora的大纲里的，高亮当前标题
 
![image](https://user-images.githubusercontent.com/69628966/102682708-99a69400-4206-11eb-93d5-304237f6bc8c.png)

**Comment by yeshaopeng6688** [comment]
另外上次提到的大纲，希望也能做成typora这样的。
![image](https://user-images.githubusercontent.com/69628966/102682754-e9855b00-4206-11eb-89a4-688edae8c99d.png)
- 全部展开
![image](https://user-images.githubusercontent.com/69628966/102682773-015cdf00-4207-11eb-847f-d8a13dbb25c7.png)
- 全部折叠
![image](https://user-images.githubusercontent.com/69628966/102682780-0de13780-4207-11eb-83bf-9993e270c639.png)
- 大纲视图（可折叠）
![image](https://user-images.githubusercontent.com/69628966/102682795-26515200-4207-11eb-85e9-528216c34190.png)
- 大纲视图（无折叠）
![image](https://user-images.githubusercontent.com/69628966/102682821-526cd300-4207-11eb-8a46-8719293c03dc.png)

**Comment by yeshaopeng6688** [comment]
插入表格，做成这样更人性化一点。
![image](https://user-images.githubusercontent.com/69628966/102682887-d030de80-4207-11eb-904f-51f8c440cd88.png)

**Comment by 88250** [comment]
* 代码块复制的问题我这里重现不了……
* 大纲折叠请关注 https://github.com/siyuan-note/siyuan/issues/564
* 表格优化后续会逐步进行

**Comment by yeshaopeng6688** [comment]
引用问题
- 复制 代码框 的引用
![image](https://user-images.githubusercontent.com/69628966/102836414-47e35100-4434-11eb-9611-35e1f7604e7a.png)
- 修改 引用名字，出现
![image](https://user-images.githubusercontent.com/69628966/102836441-5fbad500-4434-11eb-8639-550d0d8e07fd.png)
- 可能是因为 {{.text}}的缘故，把代码框的代码给整出来了。。

**Comment by 88250** [comment]
能帮忙录个屏吗，谢谢。

**Comment by yeshaopeng6688** [comment]
之前看到过你们推过的录屏工具，忘记是啥了，

**Comment by yeshaopeng6688** [comment]
= =。要录屏的时候又没有了。。怎么感觉跟之前复制代码框的代码一样，有的时候会复制处\`\`\`，有的时候不会。有的时候输入法的下选框会跑软件外，有时候又不会。。

**Comment by yeshaopeng6688** [comment]
- 你们的用户指南说过，“列表项可以包含其他任意元素。”
- 所以，现在列表项下使用表格会出现
![image](https://user-images.githubusercontent.com/69628966/102842932-1c1b9780-4443-11eb-8040-f0b3fa5528e2.png)

**Comment by 88250** [comment]
收到，稍后排查，谢谢。

**Comment by yeshaopeng6688** [comment]
- 提一个使用上优化的小点
- 鼠标双击，选中文本，有的时候可能会选中文本后的空格（在英文中很常见，选中一个单词，选连带选中单词后的一个空格）
- 这样，使用某些标记，比如斜线em，加粗strong等，就没有具体的效果（我有修改这些标记的效果）
- typora上这种操作，会自动去除多余的空格，希望有时间能够引进，谢谢啦~
![image](https://user-images.githubusercontent.com/69628966/102855914-855dd380-4460-11eb-80c4-2b1096634764.png)

**Comment by yeshaopeng6688** [comment]
![image](https://user-images.githubusercontent.com/69628966/102855984-af16fa80-4460-11eb-9bad-2d19dbd2b016.png)
![image](https://user-images.githubusercontent.com/69628966/102856054-c81fab80-4460-11eb-983e-5c52bd24bbdb.png)
![image](https://user-images.githubusercontent.com/69628966/102856136-e2f22000-4460-11eb-8796-7876bd1777aa.png)

**Comment by 88250** [comment]
好的，我们进行一下优化。

**Comment by yeshaopeng6688** [comment]
- 使用列表时，需要标记到行末，此时换行（shift + enter），想输入代码框\`\`\`，代码框会自动跳到上面
![image](https://user-images.githubusercontent.com/69628966/102858712-b096f180-4465-11eb-9f94-2a40f39815f8.png)
![image](https://user-images.githubusercontent.com/69628966/102858751-be4c7700-4465-11eb-8efb-d2c902a02554.png)
![image](https://user-images.githubusercontent.com/69628966/102858787-d15f4700-4465-11eb-9d3c-3f58e50b0d3e.png)

**Comment by yeshaopeng6688** [comment]
- 对含有<>的文本，使用快捷键标记，会出错。
![image](https://user-images.githubusercontent.com/69628966/102871126-ff01bb80-4478-11eb-85b1-c4ec3558629f.png)
![image](https://user-images.githubusercontent.com/69628966/102871145-05903300-4479-11eb-99c5-016963d923c8.png)
- 手动标记，可以。
![image](https://user-images.githubusercontent.com/69628966/102871261-2c4e6980-4479-11eb-96f4-47e7320baaa1.png)
![image](https://user-images.githubusercontent.com/69628966/102871283-31abb400-4479-11eb-89f7-5e585ce16e20.png)
![image](https://user-images.githubusercontent.com/69628966/102871296-36706800-4479-11eb-861b-a9b0cda5ce4e.png)

**Comment by 88250** [comment]
`<foo>` 会被解析为 HTML，需要用 `\` 转义

**Comment by yeshaopeng6688** [comment]
- 对“中西文中间自动插入空格”的一点想法
- 开发者（你们）永远不可能想到奇葩用户（比如我）的各种各样的需求，所以这个功能，最好可以是
- 输入时，自动对中西文插入空格，
- 但是，用户可以修改要不要空格，因为很多时候，一个标准适应不了所有奇葩的需求，比如这儿我就是不需要加入空格，但是你给我加了，我想改，也改不了，就算删除一个空格，也会强制保留另外一个空格，
- 这个功能对于我这种奇葩用户来说，可能就不用了。
- 所以，我的想法是，你可以控制输入时给我加空格，但要不要空格的自主权最好是交给用户。这样可能更自由点，这个功能也可能更实际点。
- 最后，和这个功能类似的“中文后标点符号自动替换为中文标点”，
- 同理，我大部分时候需要这个功能，但是偶尔有的地方，它就是要中文后跟英文标点。
- 这点也希望有空的时候能改进下~

**Comment by yeshaopeng6688** [comment]
> `<foo>` 会被解析为 HTML，需要用 `\` 转义

我两个都加了‘\’转义，也是这样的问题。只能手动标记，快捷键标记有问题。

**Comment by 88250** [comment]
中文空格的设计确实有缺陷，后面我们可能会考虑将其移到预览/导出设置中，谢谢。

**Comment by yeshaopeng6688** [comment]
> 中文空格的设计确实有缺陷，后面我们可能会考虑将其移到预览/导出设置中，谢谢。

其实这个功能，可以不考虑移到预览/导出设置，因为就如我刚刚说的问题一样，大部分时候，我需要你这个功能来给我加空格，但是偶尔有些地方，它不需要加空格，如果一刀切，这样可能太过武断，反而没那么实际。
所以，我的想法是，
- 输入时，该加空格加空格
- 用户输入后，发现，这个地方我不需要加空格，那么，我可以自己去除空格
- 可能这里，你们实现的难点在于，如何区分哪些是我整好的空格，哪些是用户不要的地方（我发现输入时，你们会检测之前的段落是不是也符合加空格的要求，而做出修正）
- 那么其实可以，将这个检测修正的功能，做成一个按钮，范围缩小，就在这篇md中，这样，你们既不用去自动检测修正，也能兼容之前这个功能的设计。
- 我不太清楚这个实现，所以我站在用户的角度思考，可能会欠考虑。李姐万岁~

**Comment by yeshaopeng6688** [comment]
编辑时，表格里的换行符`<br />`，能隐藏显示么。。

**Comment by 88250** [comment]
> 编辑时，表格里的换行符`<br />`，能隐藏显示么。。

暂时不能哦。

**Comment by yeshaopeng6688** [comment]
需求：引进新的快捷键操作 上下左右。
查了快捷键，正好没有和我平常在sublime、idea使用的发生冲突
* alt f：左
* alt j：右
  f，j对应左右食指放的位置，键盘上有小横线凸起
* alt m：下
* alt c：上
后续有时间可以考虑下，长时间编辑，还得移动右手去操作上下左右太累，尤其在使用标签之后。。

**Comment by yeshaopeng6688** [comment]
* 操作系统：win10
* 版本：0.54.2
* bug：在思源笔记里，对文件重命名，如果只是修改大小写，其余内容不变，会报以下错误
  * 
![image](https://user-images.githubusercontent.com/69628966/103116634-18398080-46a2-11eb-91f9-1e47e807db36.png)
  * 重启思源笔记，该文件丢失。

**Comment by yeshaopeng6688** [comment]
> * 操作系统：win10
> * 版本：0.54.2
> * bug：在思源笔记里，对文件重命名，如果只是修改大小写，其余内容不变，会报以下错误
>   *
>   ![image](https://user-images.githubusercontent.com/69628966/103116634-18398080-46a2-11eb-91f9-1e47e807db36.png)
>   
>   * 重启思源笔记，该文件丢失。

win不区分大小写。这个情况给个提示会比较好把。

**Comment by 88250** [comment]
收到，后面改进看看，谢谢。

**Comment by yeshaopeng6688** [comment]
> 需求：引进新的快捷键操作 上下左右。
> 查了快捷键，正好没有和我平常在sublime、idea使用的发生冲突
> 
> * alt f：左
> * alt j：右
>   f，j对应左右食指放的位置，键盘上有小横线凸起
> * alt m：下
> * alt c：上
>   后续有时间可以考虑下，长时间编辑，还得移动右手去操作上下左右太累，尤其在使用标签、emoji之后。。

* 还是上次提到的键位，作为一个长时间需要码字，手的活动范围最好可以固定在一块地方，尽量避免移动，这样码字也轻松点（idea和sublime都有提供这样的功能，码字码代码基本不用移手，真的很好用！！！）。
  * 对应地，也可以引进keymap，键位设置。
* 标签、书签，目前貌似是按照创建时间的顺序来排序的，能否引进其他排序？
  * 按照标签，在某个文件夹、某个文件中的位置 来排序。这样更符合写作思路的查看。
  * 尽管目前标签可以多级，但是如果为了实现我刚刚说的排序，而使用根据文件多级，
    1. 一是如果文件夹层级较深，或是文件名过长，标签过长，不美观，标签语义不凸显。
    2. 二是就算按照文件分级，也会因为 创建时间排序，笔记不是一次写完的，很经常会修修改改，但是整体思路是按照位置顺序下来的，而不是创建时间顺序。

**Comment by yeshaopeng6688** [comment]
![image](https://user-images.githubusercontent.com/69628966/103191650-adda4780-4910-11eb-9918-690ae24d98fc.png)

**Comment by 88250** [comment]
这样的话层级太多了……

**Comment by yeshaopeng6688** [comment]
那么。标签能否缩小范围，范围就是针对单个文件（当然也可以保留原本的全局），但是排序规则，能否修改为 根据 在文件中的位置 来排序。实现思路的话，看看能否根据 这个标签 的当前在整个文件中的行数 来排序。

**Comment by 88250** [comment]
我们正在对编辑器做调整，目前暂时不会动已有大的功能，见谅。

PS 后续如有反馈，请新开 issue，不然一直在这个下面太长了，不方便整理，谢谢。

**Comment by yeshaopeng6688** [comment]
好的好的~知道
