### ISSUE TITLE
改进 `退出聚焦` 后的定位

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7280]
* https://ld246.com/article/1674967902446
* https://ld246.com/article/1675776060440

**Comment by Soltus** [comment]
不只退出聚焦会滚动到文档开头，我觉得任何时候都应该记住定位

**Comment by GH-W94** [comment]
> 不只退出聚焦会滚动到文档开头，我觉得任何时候都应该记住定位

赞同

**Comment by Vanessa219** [comment]
> > 不只退出聚焦会滚动到文档开头，我觉得任何时候都应该记住定位
> 
> 赞同，比如聚焦后，按Ctrl+[ 后退，光标不应乱窜，而应保持在最后放置的位置处。 @88250

Ctrl+[ 是后退到上一个光标位置，如果遇到不正确的情况可以新建 issue 进行描述。

**Comment by GH-W94** [comment]
> > > 不只退出聚焦会滚动到文档开头，我觉得任何时候都应该记住定位
> > 
> > 
> > 赞同，比如聚焦后，按Ctrl+[ 后退，光标不应乱窜，而应保持在最后放置的位置处。 @88250
> 
> Ctrl+[ 是后退到上一个光标位置，如果遇到不正确的情况可以新建 issue 进行描述。

哦，Ctrl+[ 是这样设计的。那 V 姐，有没有聚焦之后，后退到“处于上一级聚焦状态”的快捷键，比如，处于列表中的某个子项的聚焦状态，当按下这个快捷键后，后退聚焦到这个子项的父项。前进同理。

以为日常使用，感觉这样更适用，因为当聚焦进列表的某个子项后，编辑过程中，仅仅是想后退到这个子项的父项，而现在的退出聚焦是一下全退出了，使用Ctrl+[ 也不能实现想要的目的。

**Comment by Vanessa219** [comment]
@GH-W94 
<img width="348" alt="image" src="https://user-images.githubusercontent.com/970828/217693400-aaa90ce5-714b-42e8-bc12-4e5f83d189a0.png">
