### ISSUE TITLE
SRS supports to delineate the review range by searching

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7281]
支持设置搜索条件用于闪卡复习界面，即 All 中的到期闪卡对应内容块 ID 联合搜索条件进行搜索，结果用于本次复习。

**Comment by Xuwennn** [comment]
请教一下，闪卡管理界面是否能显示对闪卡的掌握程度（类似于anki的平均难易度）。我自己觉得这是在间隔复习中挺重要的一个数据，可以帮助我们找出知识的薄弱点并解决。希望D大、V大可以考虑一下❤️
![image](https://user-images.githubusercontent.com/109729626/222939785-59929bc7-b261-4d39-8338-52a94c6c84ef.png)

**Comment by 88250** [comment]
@Xuwennn 统计数据我们没有记录，这个等以后有空再研究吧，感谢提议。

**Comment by IAliceBobI** [comment]
能否提供riff的api？

**Comment by 88250** [comment]
@IAliceBobI 麻烦单独提 issue 描述需求，谢谢。

**Comment by jih3657** [comment]
我觉得基于文档复习卡片，复习的范围应该包括反链中的卡片，因为双链笔记的核心就是”反链即正文“。
另外，这在一定程度上可以解决daily note用法的闪卡分类问题，比如在传递型双链[[错题本]]的文档中，如果可以直接复习反链内容，我就不用单独新建一个卡包。
