### ISSUE TITLE
Ctrl+Shift+C快捷键复制引用块，粘贴时为光标所在处的内容

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#7282]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

不确定这是bug还是特性

当鼠标悬浮(**不点击**)在需要进行引用块的列表项时，直接使用Ctrl+Shift+C复制，在别处粘贴时，为光标所在处的内容

当鼠标悬浮**并点击**需要进行引用块的列表项时，使用Ctrl+Shift+C复制，才是正常的需要的

### 期待的结果 Expected result

鼠标悬浮(不需要鼠标点击一下)选中时，快捷键复制也能复制选中的区域，而不是光标所在的区域

### 截屏或者录屏演示 Screenshot or screen recording presentation

![index](https://user-images.githubusercontent.com/19968935/217295609-34c972f9-d72c-4abf-ae80-e93c611980e8.gif)

### 版本环境 Version environment

```markdown
- Version: 2.7.2
- Operating System: Win
- Browser (if used):
```

### 日志文件 Log file

无异常日志

**Comment by 88250** [comment]
选择块需要点击，这个例子中光标插入符在一个代码块中，所以默认就选择了这个块。

如果你需要用快捷键选择块，需要用 Shift+↑ 扩选，然后再 Ctrl+Shift+C。
