### ISSUE TITLE
PDF 页签保存上次浏览位置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7283]
https://ld246.com/article/1674618344135

**Comment by hhh111119** [comment]
D大, 用的官方的同步, 好像还是会有这个问题. 每次思源笔记重启后, pdf 打开就会回到第一页.
目前是 Windows +mac 端进行同步. 客户端应该是最新的, 一直有保持更新

**Comment by Vanessa219** [comment]
pdf 页码不会在两台电脑之间同步。只会记录当前电脑的。

**Comment by hhh111119** [comment]
V大, 我 Windows 上面的现象是这样的.
打开 pdf 到第 10 页后, 关闭 pdf, 再次打开 会回到第 10 页.
但是如果我关闭思源, 然后再次打开思源, 打开 pdf. 这时就会到封面. 页码丢失了.

**Comment by 88250** [comment]
@hhh111119 我这里 Windows 上测试正常。

**Comment by hhh111119** [comment]
![siyuanpdf](https://github.com/siyuan-note/siyuan/assets/12663407/66abae64-2614-4fc6-b2be-d7a38afb5596)
@88250  D 大这是我电脑上的效果.  版本是 当前版本 v2.10.15
操作系统 Windows 11

**Comment by 88250** [comment]
我这里还是重现不了，也是 Win11，思源 v2.10.16，录屏如下：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/1f5f176a-46e6-41c9-a1db-6c6dfe04870e)

**Comment by hhh111119** [comment]
@88250  感谢 D 大. 我也升级了好像就好了.
