### ISSUE TITLE
支持窗口之间拖拽移动内容块

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7284]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在独立出的新窗口，不能与主窗口中文档进行块的互相拖拽，请问能支持吗？

### 描述可能的最优解决方案 Describe the optimal solution

望解决

**Comment by 88250** [comment]
> 无法将标题拖动到目录，使标题及其中的内容成为一篇独立的笔记。

https://github.com/siyuan-note/siyuan/issues/7430
