### ISSUE TITLE
web 端的是否有考虑添加自定义图标的上传功能

### ISSUE THREAD

**Issue by benz9527** [siyuan-note/siyuan#7288]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/109717800/217419462-6f01ac20-204d-4949-b381-2dee29df15a7.png)

目前 web 端无法提供自定义图标的功能，虽然可以手动把图标传入到工作空间的 `data/emojis` 目录下并刷新页面的方式来简介实现。但是使用体验上较差。

### 描述可能的最优解决方案 Describe the optimal solution

增加接口（带格式校验的）用于自定义图标的上传（最好带有图标大小统一标准化）和删除管理。

**Comment by 88250** [comment]
之前考虑过 https://github.com/siyuan-note/siyuan/issues/5897
