### ISSUE TITLE
2.7.3 docker部署一直显示内核连接中断

### ISSUE THREAD

**Issue by yangmingyuan380** [siyuan-note/siyuan#7291]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

在腾讯云轻量应用服务器上部署的思源v2.7.3 docker，每次启动自动重建索引过程中就会内核中断，查看日志并没有报错信息。数据是使用腾讯云s3对象存储同步过来的，本地计算机上重建索引并没有这个问题。

### 期待的结果 Expected result

希望可以正常使用，不在内核中断

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/32832374/217429159-447a4463-08d0-4518-a147-1eb09b623ceb.png)
![image](https://user-images.githubusercontent.com/32832374/217429253-e47bd20d-9b9f-4ab2-9697-88aaf5345a6c.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.3
- Operating System: Linux VM-4-15-centos 3.10.0-1160.36.2.el7.x86_64
- Browser (if used):chrome firefox
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10681518/siyuan.log)

**Comment by 88250** [comment]
从内核日志上看一切正常，内核并没有退出，请看下浏览器端 F12 后的网络请求，特别是 WebSocket 连接。

**Comment by yangmingyuan380** [comment]
是控制台先显示websocket关闭了，然后页面出现内核连接中断，后台docker容器也会退出运行。
![image](https://user-images.githubusercontent.com/32832374/217433276-7f2ad323-037e-43b5-9218-944cf031c93b.png)
但是刚刚启动时页面可以打开，数据也显示正常，是什么原因导致了websocket关闭了呢？

**Comment by 88250** [comment]
> 页面出现内核连接中断，后台docker容器也会退出运行。

内核正常退出的话会有日志显示，请再看下是否有。

**Comment by yangmingyuan380** [comment]
日志里确实没有退出的信息，我重启了几次docker容器都是这样的结果。不过我观察到，我在启动容器时，我的cpu占用率会飙到100%，是不是因为这样导致内核突然退出。
[siyuan.log](https://github.com/siyuan-note/siyuan/files/10681769/siyuan.log)

**Comment by yangmingyuan380** [comment]
我试着降级到2.5.3版本，重建索引也会报错，但是重启容器后就正常了，这是日志。
[siyuan.log](https://github.com/siyuan-note/siyuan/files/10681811/siyuan.log)

**Comment by 88250** [comment]
我这里刚刚测试了 2.7.3 的 Docker 是正常的，在空的工作空间上仅打开帮助文档。

**Comment by 88250** [comment]
```
I 2023/02/08 13:00:31 runtime.go:49: kernel is booting:
    * ver [2.7.3]
    * arch [amd64]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/siyuan/workspace/]
I 2023/02/08 13:00:31 runtime.go:94: use network proxy [system]
I 2023/02/08 13:00:31 serve.go:108: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2023/02/08 13:00:31 blocktree.go:386: read block tree [0 B] to [/siyuan/workspace/temp/blocktree], elapsed [0.01s]
I 2023/02/08 13:00:31 conf.go:615: database size [74 kB], tree/block count [0/0]
I 2023/02/08 13:00:31 working.go:157: kernel booted
I 2023/02/08 13:00:31 box.go:74: auto stat [trees=0, blocks=0, dataSize=29 kB, assetsSize=0 B]
I 2023/02/08 13:02:34 index.go:128: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.04s], tree [count=51, size=953 kB]
I 2023/02/08 13:02:34 index.go:187: resolved refs [0] in [0ms]
```

**Comment by yangmingyuan380** [comment]
那可能是我的笔记存在某些问题，下面的错误是什么意思呢？
`E 2023/02/08 12:59:23 upsert.go:42: insert tree [20211205163726-fl8gam1/20221110180445-mngs01e/20221110180510-h2p5omy.sy] into database failed: database disk image is malformed
E 2023/02/08 12:59:23 database.go:1190: exec database stmt [INSERT INTO blocks (id, parent_id, root_id, hash, box, path, hpath, name, alias, memo, tag, content, fcontent, markdown, length, type, subtype, ial, sort, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?),(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] failed: database disk image is malformed
E 2023/02/08 12:59:23 upsert.go:42: insert tree [20211205163726-fl8gam1/20221110180445-mngs01e.sy] into database failed: database disk image is malformed`

**Comment by 88250** [comment]
试下移除工作空间/temp/ 文件夹后再启动。

**Comment by yangmingyuan380** [comment]
我试了几次还是不行，我放弃了
```bash
E 2023/02/08 13:42:22 upsert.go:42: insert tree [20211205163726-fl8gam1/20221110180445-mngs01e.sy] into database failed: database disk image is malformed
I 2023/02/08 13:42:22 index.go:180: rebuilt database for notebook [20211205163726-fl8gam1] in [1.43s], tree [count=81, size=40 MB]
I 2023/02/08 13:42:22 conf.go:617: database size [852 MB], tree/block count [2231/94767]
I 2023/02/08 13:42:22 working.go:149: kernel booted
F 2023/02/08 13:42:42 database.go:1202: database disk image [/siyuanworkspace/temp/siyuan.db] is malformed, please restart SiYuan kernel to rebuild it
````

**Comment by 88250** [comment]
```
F 2023/02/08 13:42:42 database.go:1202: database disk image [/siyuanworkspace/temp/siyuan.db] is malformed, please restart SiYuan kernel to rebuild it
```

这个指的是数据库文件损坏，然后内核会自动退出。

**Comment by yangmingyuan380** [comment]
是的，我重建索引多次，也试着删除了工作空间/temp/ 文件夹后再启动，但仍然有这个问题

**Comment by 88250** [comment]
是不是外部有什么程序会读写这个文件？

**Comment by yangmingyuan380** [comment]
应该没有，我是在docker部署的，服务器上也没运行其他程序

**Comment by 88250** [comment]
试一下在新的工作空间能否重现这个问题。

**Comment by zuoez02** [comment]
database disk image is malformed. db文件损坏，需要尝试修复数据库文件，重建索引解决不了这个问题

**Comment by 88250** [comment]
重建索引在正常情况下会删除数据库文件，然后才重现建表建库并插入数据的。

**Comment by 88250** [comment]
这个问题我们暂时保持 open 3 天，如果没有其他类似反馈或者更多信息就先关闭了。

**Comment by catmade** [comment]
windows 版客户端也遇到这个问题，版本是 v2.7.4。

触发原因不清楚，是升级之后才有。

**Comment by 88250** [comment]
@catmade https://github.com/siyuan-note/siyuan/issues/7323

**Comment by CC1001001** [comment]
Mac v2.7.4 版本也出现该问题
<img width="562" alt="image" src="https://user-images.githubusercontent.com/49863518/218380383-74bbb628-12f6-47f8-aafb-f6e0d6c8a68b.png">

**Comment by MRHOPER** [comment]
再次遇到这个问题，我在局域网内部访问没有这个问题，但是在我使用外网访问的时候就出现这个问题

**Comment by MRHOPER** [comment]
已经解决WebSockets support没开
