### ISSUE TITLE
建议在启动思源时如果有多个工作空间时需要选择工作空间后再打开

### ISSUE THREAD

**Issue by caohongliang92** [siyuan-note/siyuan#7294]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如图，如果我有多个工作空间，启动思源时默认打开了上次最后打开的工作空间（即）「数字花园」，但我想打开工作空间是「Bug重现」。现在我必须先输入工作空间「数字花园」的密码，然后才能打开「Bug重现」
![image](https://user-images.githubusercontent.com/48972121/217448139-54066a72-84f0-471c-ae6a-91208bb06633.png)
![image](https://user-images.githubusercontent.com/48972121/217448602-5644af48-168f-44fa-b98b-4f7ab6c6186c.png)

### 描述可能的最优解决方案 Describe the optimal solution

可以参考Obsidian的解决方案，我记得Obsidian在打开时如果有多个空间，会先显示空间列表的

**Comment by 88250** [comment]
思源会以最后一个打开的工作空间作为下次启动的首选，这样效率较高。如果每次启动都要选择的话效率很低。

**Comment by GH-W94** [comment]
> 思源会以最后一个打开的工作空间作为下次启动的首选，这样效率较高。如果每次启动都要选择的话效率很低。

感觉题主提出的这个方案很好，要比自己设置各空间桌面快捷键来的实在，也更符合大众使用逻辑习惯和异于小白操作。

不太理解D大提出的“效率低”是指软件运行效率还是用户操作的效率。
若是指用户操作的效率，那当打开的空间不是自己想要的，那还需要打开想要的空间，然后再关闭不需要的空间，效率更低了。
