### ISSUE TITLE
反链面板显示优化

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7296]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

前情摘要：#7028
反链面板显示空间较小，在改版之后改为原文格式显示、又加入面包屑用于上下文跳转等功能，导致实际显示正文内容较少，或者说被格式占用的空间过大，因此提出该建议

### 描述可能的最优解决方案 Describe the optimal solution

1. 将原文格式重排按比例缩小字号（不一定要采用缩小字号这么简单粗暴的办法，可以是重排了用更紧凑的格式显示）
2. 面包屑如果只有一层时自动隐藏（如果是在同一层级有两个相同反链改用分割线区分）

第2点如果限定只能一层自动隐藏的话，用户实际使用中面包屑只有一层的场景可能较少，达不到触发隐藏要求，实际也起不到作用

### 描述候选的解决方案 Describe the candidate solution

暂时就想到这两点，大家可以讨论一下，提提建议

### 其他信息 Other information

面包屑自动隐藏这个可以拓展到其他显示面包屑的地方，例如浮窗、搜索等

**Comment by heimi98** [comment]
同意，反链面板希望以尽可能展示多的信息为目标。

**Comment by 88250** [comment]
缩小字号或者用其他方式进行紧凑布局的话主要是怕影响反链和正文的视觉一致性。

**Comment by Temacc0531** [comment]
对的，现在需要更多用户参与讨论。

到底反链面板是需要与正文保持相同格式来获得视觉一致性（虽然我觉得现在加上了很多面包屑之后也是很割裂😂，或许面包屑可以隐藏起来，鼠标移过去时悬浮显示？），还是用作一个汇总显示、联系上下文为主的可编辑紧凑面板。

就我个人对“反链即正文”这一用法的理解，会比较偏向于紧凑面板这一方案
> 我也是“反链即正文”支持者，但我觉得这并不是说反链面板的编辑体验要和正文编辑器一模一样，这句话的意思应该是说可以通过反链面板可以把不同位置的信息组合到同一个页面里阅读，从这个角度讲，缩小字号并不会降低用户的使用体验，反而可以显示更多的正文内容

**Comment by zxhd863943427** [comment]
我不希望，建议找有类似考虑的主题。

**Comment by litcu** [comment]
不希望，因为主流的双链笔记似乎没有这么做的，而且大多都在页面尾部显示反链，思源在侧边栏理论上一眼能看到更多。

但是有个问题，就是现在反链的展示逻辑好像和以前不一样了，以前按照传递型反链和关联型反链有不同的逻辑，现在似乎只跟正文保持一致了。

**Comment by Temacc0531** [comment]
> 不希望，因为主流的双链笔记似乎没有这么做的，而且大多都在页面尾部显示反链，思源在侧边栏理论上一眼能看到更多。
> 
> 但是有个问题，就是现在反链的展示逻辑好像和以前不一样了，以前按照传递型反链和关联型反链有不同的逻辑，现在似乎只跟正文保持一致了。

也许你没看懂我的意思，这个和显示位置没啥关系，大概差不多就是思源现在的反链面板字体小些格式紧凑些，显示更多的正文内容

**Comment by deerainw** [comment]
# 做进编辑器

**Comment by litcu** [comment]
> 也许你没理解我的意思，这个和显示位置没啥关系，大概的意思差不多就是思源现在的反链面板字体小些格式紧凑些，显示更多的正文内容

我知道你什么意思，我也只是表达个人观点，如果反链面板和正文显示效果不一样，反而会有割裂感。比起多看到一些反链内容，这种割裂感反而会让我不习惯。

**Comment by oneWaterMonkey** [comment]
我也发现这个问题，新版反链面板确实显示内容少了很多。或许可以不动原文格式，在面板右上角加个面包屑显示开关，不行直接整多个紧凑布局可供切换，小孩子才做选择，大人我全都要😁

**Comment by 88250** [comment]
@deerainw 编辑器挂件槽 https://github.com/siyuan-note/siyuan/issues/3862 实现后应该可以把反链放到底部，这个再说吧。

这次讨论还是挺有意义的，但是我们决定不改设计了，如果需要的话也许可以通过自定义 CSS 来完成。

**Comment by uulaile** [comment]
支持一下

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/12862
