### ISSUE TITLE
设置启动时关闭所有页签后，重启反链面板显示异常

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7298]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

打开`启动时关闭所有页签`选项，重启思源，可以看到虽然主页面显示【没有打开的文档】，但可以从反链面板、标题和最近打开的文档看到实际还是打开了关闭前最后显示的文档

### 期待的结果 Expected result

打开`启动时关闭所有页签`选项后页签应彻底关闭

### 截屏或者录屏演示 Screenshot or screen recording presentation

![GIF 23-2-8 16-13-48](https://user-images.githubusercontent.com/101307399/217472551-e6204e4d-e95b-4a6d-9262-aea0e3259898.gif)

### 版本环境 Version environment

```markdown
- Version: v2.7.3
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
`最近打开的文档` 中出现是预期，`反链面板` 中出现我这里无法重现。

**Comment by Temacc0531** [comment]
> `最近打开的文档` 中出现是预期，`反链面板` 中出现我这里无法重现。

`最近打开的文档` 应该也不应该出现吧，因为实际重启后你并没有再打开这个文件了，或者要显示的话应该是在没关闭思源前切换页签的时候显示，还有标题也是会出现的

**Comment by 88250** [comment]
`最近打开的文档` 目的就是为了记录这些，即使关闭也会有的。

**Comment by Temacc0531** [comment]
现在我看我这边是`最近打开的文档`的逻辑是：新打开页签会记录、关闭页签不会记录、已打开的页面切换不会记录，这是符合预期的吗😂

**Comment by mozhux** [comment]
这个不就是记录你近期打开了什么文档？你那些操作没啥关系吧

**Comment by Temacc0531** [comment]
> 这个不就是记录你近期打开了什么文档？你那些操作没啥关系吧

你是说我上面说的那个逻辑是符合预期的是吗，我没说这个逻辑有问题。我是想说如果是这个逻辑的话，那我重启完思源没有新打开页签按理来说也不应该记录到`最近打开的文档`里面

**Comment by mozhux** [comment]
这个就和你浏览器一样，新打开，但是历史记录还在呀，不然我想看之前的记录咋办。。过一段时间才清空

**Comment by Temacc0531** [comment]
不是不是，我不是说历史要清空的意思，你们理解错我的意思了😅，看那个视频重启思源前的记录的是【2023-02-08】，重启完就变成【请从这里开始】了，所以证明【请从这里开始】这个文档被打开过，我是想说这个意思

**Comment by mozhux** [comment]
这个你得关注一下是否关闭思源时没有完全关闭页签，如果没有，即使你勾选了启动时关闭所有页签，那启动的时候其实已经有开启过了。

**Comment by Temacc0531** [comment]
是的，我提的就是这个问题。就是我打开了`启动时关闭所有页签`开关，按理说我重启就应该是所以页签都是关闭的状态，如果关闭前还要先手动把页签都关闭的话，那这个开关就没有用了

**Comment by 88250** [comment]
我这里目前重现不了，你试下在一个全新的工作空间上是否能重现。

**Comment by mozhux** [comment]
这个就是字面意思。。他是启动时关闭，说明启动的时候还在，  不是关闭思源时关闭页面。你应该是说建议出一个关闭思源时关闭所有页签

**Comment by Temacc0531** [comment]
> 我这里目前重现不了，你试下在一个全新的工作空间上是否能重现。

全新的工作空间还是会出现，你重启完标题有出现文档名吗，试下开着反链面板重启

**Comment by mozhux** [comment]
我复现了。
@88250  开启动关闭页签那个设置， 先关掉所有页签， 然后打开思源帮助文档，请从这里开始，右边反链面板也开着，然后关闭思源退出，重新打开，反链就还是留存之前的。
![image](https://user-images.githubusercontent.com/46953371/217491408-a09875ec-a5ac-44f4-85d4-90a6ebc47a42.png)

**Comment by Temacc0531** [comment]
这是用全新工作空间的复现步骤，可以看到开不开反链面板还不太一样，但是标题是都会显示出来的

![GIF 23-2-8 17-38-47](https://user-images.githubusercontent.com/101307399/217492724-c617c276-6b79-46f1-8ca9-15c04bec94ce.gif)
