### ISSUE TITLE
点击文末空白时导致全选

### ISSUE THREAD

**Issue by benz9527** [siyuan-note/siyuan#7299]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/109717800/217472658-27315284-51ad-47d9-9127-6f3212f32330.png)

![image](https://user-images.githubusercontent.com/109717800/217472820-eefa2fab-b805-46a5-a197-543c322148a5.png)

这十分容易导致文本内容被覆盖掉。

复现步骤，无空行等待大约 30s，也就是自动同步的间隔时间，新增空行。

### 期待的结果 Expected result

新增空行不会导致其他文本被选中

### 截屏或者录屏演示 Screenshot or screen recording presentation

![siyuan-bug1](https://user-images.githubusercontent.com/109717800/217479852-0e353a3f-8bf6-45df-8208-c4aeb0835e17.gif)

### 版本环境 Version environment

```markdown
- Version: v2.7.3
- Operating System: docker debian
- Browser (if used): edge 109.0.1518.78 (正式版本) (64 位)
```

### 日志文件 Log file

界面操作，无日志

**Comment by 88250** [comment]
请在默认主题下录屏演示。

**Comment by benz9527** [comment]
稍等，我录着 daylight 的操作 gif

**Comment by benz9527** [comment]
![siyuan-bug1](https://user-images.githubusercontent.com/109717800/217479852-0e353a3f-8bf6-45df-8208-c4aeb0835e17.gif)

默认主题下的操作

**Comment by 88250** [comment]
我这里修改文档以后等 30s 发起自动同步后没有选中。

**Comment by 88250** [comment]
@OpaqueGlass 我这里只用两个挂件测试了下还是重现不了。

![image](https://user-images.githubusercontent.com/873584/217539640-ae70a3cd-1eb5-48ce-aae3-378483d79bf7.png)

**Comment by benz9527** [comment]
我昨天用的手心输入法，我没有考虑到有输入法的问题

**Comment by OpaqueGlass** [comment]
重新在虚拟机里试了一下（siyuan-v202302082201-win），发现在焦点从其他应用切换到思源也会出现。搜狗输入法按照之前的操作也能重现。v2.7.1没有这种情况。
![Repeat#7299](https://user-images.githubusercontent.com/52985952/217694689-a422206d-bce9-49fa-84eb-f7ef0b6ccf54.gif)

**Comment by Vanessa219** [comment]
是一启动就点击挂件再点击末尾么？还是之前有什么其他操作？

**Comment by OpaqueGlass** [comment]
我这里不需要其他操作，感觉和输入法有关系
a. 用搜狗或手心输入法，复现步骤：
  1. 点挂件
  2. 点文档末尾没有空行的位置
 
b. 用搜狗、手心或微软拼音，复现步骤：
  1. 分屏，或者让其他app显示在思源之上，点其他应用
  2. 在思源中点文档末尾没有空行的位置

**Comment by 88250** [comment]
@OpaqueGlass 可以重现了，多谢！
