### ISSUE TITLE
超级块 {{{ blocks }}}

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#73]
“超级块”是一种容器块，可以包含任意非文档块。

```markdown
{{{

段落块

* 列表块

> 块引用块

# 标题块

{{{
嵌套超级块
……
}}}

……

}}}
```

在没有超级块之前可以通过文档作为块容器，从这个角度上看，超级块和文档块非常像。

另外，超级块也许还能让 Markdown 支持横向布局：

```markdown
{{{row
blocks
}}}
```

包含的 blocks 将按照横向行式进行布局渲染，留空默认是 column 即纵向列式布局。

**Comment by 88250** [comment]
横向布局能力以后考虑。
