### ISSUE TITLE
新增空行导致文本被全选

### ISSUE THREAD

**Issue by benz9527** [siyuan-note/siyuan#7300]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

#7299 这里已经完成了默认主题的复现的 gif  
之前提过，没贴 gif 被 closed，只能新开一个 issue

### 期待的结果 Expected result

新增空行不影响其他的文本行

### 截屏或者录屏演示 Screenshot or screen recording presentation

![siyuan-bug1](https://user-images.githubusercontent.com/109717800/217479852-0e353a3f-8bf6-45df-8208-c4aeb0835e17.gif)

### 版本环境 Version environment

```markdown
- Version: v2.7.3
- Operating System: docker debian
- Browser (if used): edge 109.0.1518.78 (正式版本) (64 位)
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/7299

请不要重复报告问题，如果之前的问题已经补充信息，我们会看的，谢谢。
