### ISSUE TITLE
建议去掉2.7.3版本“重建索引”时一闪而过的“启动画面”

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7301]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我记的2.7.2版本在“重建索引”时就没有一闪而过的“启动画面”，而升级了2.7.3后，却又有了这个画面，一瞬间，感觉不高级了。
![重建索引](https://user-images.githubusercontent.com/117154557/217530366-09e93410-8037-4361-99d4-2503d0ee9a79.gif)

### 描述可能的最优解决方案 Describe the optimal solution

加油！

**Comment by 88250** [comment]
重建索引以后需要刷新一次界面的。

**Comment by GH-W94** [comment]
> 重建索引以后需要刷新一次界面的。

为什么在2.7.2版本就可以没有这个一闪而过的“启动界面”呢？

**Comment by 88250** [comment]
是个 272 的 bug

**Comment by GH-W94** [comment]
> 是个 272 的 bug

好吧，啥时候这个bug能成为特性就好了，没有这个界面的感觉很好。
