### ISSUE TITLE
将“移动块”功能的移动位置变的更加精确

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7304]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前，通过“剪切”移动块的位置，会造成引用的失效，当要移动的位置较远时，通过拖动的方式移动时，极易操作失误，而块标菜单中的“移动”功能只能移动至某个文档里，不能精确移动到某个文档内的某个位置。

### 描述可能的最优解决方案 Describe the optimal solution

在块标的菜单中增加个“将块移动至”按钮，当选中要移动的块后，点击此按钮后，后台程序锁定（记住）这个要移动的块，然后操作鼠标，将光标移动到目标位置处的上一行的末尾处后右键，在出现的菜单中点击“移动块至此”按钮后，将要移动的块移动到目标位置。

**Comment by 88250** [comment]
你说的方案用户操作起来太复杂了，建议分屏拖拽。

**Comment by GH-W94** [comment]
> 你说的方案用户操作起来太复杂了，建议分屏拖拽。

额，不复杂吧。和原来的剪切操作是一样的，步骤都没有多一步：

1.原来的第一步是选中块点“剪切”，现在对应成选中块点“将块移动至”。
2.原来的第二步是移动光标到目标位置，现在同样是移动光标到目标位置。
3.原来的第三步是右键点“粘贴”，现在对应成右键点“移动块至此”。

不明白是哪里复杂了？

**Comment by 88250** [comment]
一来是用户操作复杂，二来是有 ID 重复的隐患，你看下这里有过讨论 https://github.com/siyuan-note/siyuan/issues/6807

**Comment by GH-W94** [comment]
> 一来是用户操作复杂，二来是有 ID 重复的隐患，你看下这里有过讨论 #6807

唉，看了，囫囵者看了，没太看明白。

D 大，利用块菜单中的“移动”功能的原理来实现上述步骤，也会发生 ID 重复隐患？换句话，就是现在的”移动“功能的目标位置太大了，只能到文档末尾，能否进一步将移动的目标位置精确到文档里指定的位置。
![image](https://user-images.githubusercontent.com/117154557/217702433-0e27c9fb-8782-4518-8a95-023ebb95d955.png)

**Comment by 88250** [comment]
移动没有问题。

**Comment by GH-W94** [comment]
> 移动没有问题。

所以有希望实现：将现有“移动”功能的目标位置精确到文档里指定的位置？

**Comment by 88250** [comment]
拖拽……
