### ISSUE TITLE
这个是bug还是特性呢？

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7305]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

将光标移到标签后，按空格，会出现如下效果，不知到是bug还是特性，若是特性的话，建议去掉吧，因为现在可以通过右键标签，对标签进行编辑，不然很影响在标签后新建第二个标签的操作。
![标签](https://user-images.githubusercontent.com/117154557/217582571-e913e71b-f937-4073-a7a7-6423a4c7e1e5.gif)

### 描述可能的最优解决方案 Describe the optimal solution

加油！

**Comment by 88250** [comment]
特性，可以→键移出。
