### ISSUE TITLE
Android 端去掉保活用的通知栏

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7306]
https://github.com/siyuan-note/siyuan/issues/2274 

经过长期观察，实际上并没有起到保活作用，所以决定去掉了。

**Comment by Danielypzhang** [comment]
@88250 手机挂后台做伺服器，最近老是断联，是不是和这个有关系？

**Comment by 88250** [comment]
手动设置一下电源管理相关选项吧。
