### ISSUE TITLE
为代码块显示行号的开关设置一个快捷的操作方式

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#7310]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

从网上复制的教程有大量的代码块，有的代码块只有一两行，但是默认显示行号，会出现前面难看的 1。
如果每个都去设置不显示行号，也比较麻烦。

### 描述可能的最优解决方案 Describe the optimal solution

或者提供一个快捷键，比如 Ctrl-Shift-Alt-1，或者当点击行号位置时弹出 </> 代码块 对应的子菜单 （里面有代码块换行、连字和显示行号三个选项）

**Comment by 88250** [comment]
这个应该不会考虑加快捷键了，还是菜单操作吧。

**Comment by jabobian** [comment]
还是建议：
在 设置-》快捷键-》编辑器-》插入元素-》代码块 下面新增一个  切换显示行号。

不急，但是真的方便，页面也容易整洁。因为不用眼睛到处去找。
