### ISSUE TITLE
拖拽以改变当前编辑的文档后编辑该文档，有概率发生索引异常的错误

### ISSUE THREAD

**Issue by nyaachen** [siyuan-note/siyuan#7311]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

拖拽以改变当前编辑的文档后编辑该文档，有概率发生索引异常的错误，并导致思源报错。
尝试重建索引无效，此后对该文档进行的修改会在重新启动项目后丢失。
之前拖拽文档的时候也触发过一次。

### 期待的结果 Expected result

正确处理文档位置的变动。

### 版本环境 Version environment

```markdown
- Version: 2.7.2
- Operating System: Windows 10 专业版 20H2
- Browser (if used):
```

### 日志文件 Log file

E 2023/02/09 11:38:41 tree.go:178: load tree [20230105113643-ibi0yhx/20230208161857-t7qhewk.sy] failed: open C:\Users\nyaachen\Documents\SiYuan\SiYuan\data\20230105113643-ibi0yhx\20230208161857-t7qhewk.sy: The system cannot find the file specified.
[siyuan.log](https://github.com/siyuan-note/siyuan/files/10693307/siyuan.log)

**Comment by 88250** [comment]
请升级到最新版后再试试，应该已经修复。
