### ISSUE TITLE
搜索界面快捷键增强

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#7316]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前搜索界面的很多按钮没有**直接**触发的快捷键,
比如 "搜索历史" 切换搜索方式,还有"命名查询",
之前在链滴看到有人提议将命名查询直接显示在搜索面板上,而不是藏在子菜单里,
最近觉得命名查询很好用, 不过没有快捷键,用起来太麻烦, 
所以希望能增加快捷键

### 描述可能的最优解决方案 Describe the optimal solution

比如 在搜索输入框 按 alt+down  可以弹出命名查询列表, 然后 up/down切换命名查询,enter使用当前选中的命名查询,(只加载对应配置,但不实际执行,等用户在输入框按enter时才实际执行), esc关闭命名查询列表.

搜索历史的弹窗可以使用ctrl+down
其他按钮可以使用ctrl+数字 或者 alt+数字 来触发; 或者简单一点,用tab键和shift+tab, 不过现在我试了tab无效,不能在那些按钮间切换

windows资源管理器是按下alt键+数字或字母键来触发各种菜单,如下所示,按下alt还会显示出每个按钮对应的数字或字母
![Snipaste_2023-02-09_18-27-41](https://user-images.githubusercontent.com/48077521/217786902-edc5e90b-a95f-49bb-985c-2b55b426bc53.png)

![Snipaste_2023-02-09_18-28-20](https://user-images.githubusercontent.com/48077521/217787031-7a4f2c04-d4c2-420a-8190-a604a4b7afbe.png)

**Comment by 88250** [comment]
现阶段暂时不考虑了，等后续需求多一些时再考虑，感谢提议。
