### ISSUE TITLE
改进删除折叠列表的下一个空列表项

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7317]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

如录屏所示
当我有两个列表项
我折叠上面一个列表项，
![image](https://user-images.githubusercontent.com/37429029/217828850-696ce83c-57dc-4a3f-a06a-45f26d6aa2eb.png)

然后删除下一个列表项的第一层级列表，这个列表项的子列表会直接消失
![image](https://user-images.githubusercontent.com/37429029/217829482-482f7d0b-bc00-43b6-95f7-fc1e2f282039.png)
![image](https://user-images.githubusercontent.com/37429029/217828911-6d27a23e-c8de-46d5-8859-d626eab56f42.png)
![image](https://user-images.githubusercontent.com/37429029/217828988-deac5048-32cd-4d8d-9884-ee85bf15f0f3.png)

### 期待的结果 Expected result

子列表不应该消失，而是自动转换成外层列表。

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/37429029/217829071-a6a872b2-4fc5-401f-a766-2db45db70d07.mp4

### 版本环境 Version environment

```markdown
- Version: 2.7.3
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by AugustTuan** [comment]
录频用的是默认主题

**Comment by Vanessa219** [comment]
按照未折叠的情况应该是将子列表变为被折叠列表下方的列表项，但由于列表折叠了，应该同有内容时的处理，将光标上移。
