### ISSUE TITLE
‘动态查询嵌入语法’和‘中西文中间自动插入空格'配置冲突

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#732]
### 描述问题 Describe the problem
启用了`中西文中间自动插入空格`配置后，如下语句查询不生效：
```
!{{ SELECT * FROM blocks WHERE content LIKE '%内容块%' }}
```

### 期待的结果 Expected result

希望`中西文中间自动插入空格`配置不会影响正常的查询输入

### 截屏或录像 Screenshot or video

输入方式是手动输入或者语句后粘贴
![图片](https://user-images.githubusercontent.com/15924513/102086836-a8322b80-3e53-11eb-87ab-fe526e112816.png)

### 版本环境 Version environment

* 版本 Version：0.5.3
* 操作系统 Operating system：win10

**Comment by 88250** [comment]
你好，经过考虑我们决定将该选项从编辑生效改为预览/导出生效，请关注 #814 谢谢。
