### ISSUE TITLE
Improve the interactive user experience on the mobile

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7335]
拆分为如下任务：
Divided into the following tasks:

* [x] https://github.com/siyuan-note/siyuan/issues/7518
* [x] https://github.com/siyuan-note/siyuan/issues/7519
* [x] https://github.com/siyuan-note/siyuan/issues/7553
* [x] https://github.com/siyuan-note/siyuan/issues/7554
* [x] https://github.com/siyuan-note/siyuan/issues/7564
* [x] https://github.com/siyuan-note/siyuan/issues/7576
* [x] https://github.com/siyuan-note/siyuan/issues/7578
* [x] https://github.com/siyuan-note/siyuan/issues/7595
* [x] https://github.com/siyuan-note/siyuan/issues/7600
* [x] https://github.com/siyuan-note/siyuan/issues/7610
* [x] https://github.com/siyuan-note/siyuan/issues/7655
* [x] https://github.com/siyuan-note/siyuan/issues/7661
* [x] https://github.com/siyuan-note/siyuan/issues/7632
* [x] https://github.com/siyuan-note/siyuan/issues/7635
* [x] https://github.com/siyuan-note/siyuan/issues/7681
* [x] https://github.com/siyuan-note/siyuan/issues/7598
* [x] https://github.com/siyuan-note/siyuan/issues/7520
* [x] https://github.com/siyuan-note/siyuan/issues/7828
* [x] https://github.com/siyuan-note/siyuan/issues/7688
* [x] https://github.com/siyuan-note/siyuan/issues/7596
* [x] https://github.com/siyuan-note/siyuan/issues/7852
* [x] https://github.com/siyuan-note/siyuan/issues/7853
* [x] https://github.com/siyuan-note/siyuan/issues/7879
* [x] https://github.com/siyuan-note/siyuan/issues/7886
* [x] https://github.com/siyuan-note/siyuan/issues/7830
* [x] https://github.com/siyuan-note/siyuan/issues/7932
* [x] https://github.com/siyuan-note/siyuan/issues/7934
* [x] https://github.com/siyuan-note/siyuan/issues/7909
* [x] https://github.com/siyuan-note/siyuan/issues/7597

**Comment by aircolin** [comment]
D大、V大，目前用iPad打开思源，没有移动端的操作界面，是桌面端的界面，但是iPad操作本身又无法像桌面端那般灵活，能像移动端靠拢优化吗？

**Comment by Soltus** [comment]
> D大、V大，目前用iPad打开思源，没有移动端的操作界面，是桌面端的界面，但是iPad操作本身又无法像桌面端那般灵活，能像移动端靠拢优化吗？

正想给平板单独整个界面，要是官方动手就太好了

**Comment by Vanessa219** [comment]
Pad 需要等移动端优化玩以后

**Comment by 88250** [comment]
@Benjamin-Watson0 还在陆续改进，感谢反馈。

**Comment by aircolin** [comment]
D大，V大加油！～

**Comment by xp12047** [comment]
我在反馈的时候很有情绪。刚才有个人提醒了我。我觉得他是对的。感谢他。但我是觉得取消/增加了那个+号不合适啊。编辑页面不应该追求简洁嘛。你弄了个小点点+在手机屏幕它也不好按啊，大佬!原来的斜杠调出多方便啊，还节约了屏幕空间。 是要往富文本编辑器方向发展嘛，全是按钮了。
实际上我觉得现在已经很强大了。关键的问题是打开应用加载，一直加载那个可否给多加优化。那能不能是方向。

**Comment by Vanessa219** [comment]
点击和输入 “/” 相比，点击会更加方便

**Comment by xp12047** [comment]
> 点击和输入 “/” 相比，点击会更加方便

它真的不方便。不过是点击看起来直观了。但也无趣了。大佬，三思啊！你把斜杠去掉，没有灵魂了啊。

**Comment by mozhux** [comment]
> > 点击和输入 “/” 相比，点击会更加方便
> 
> 它真的不方便。 不过是点击看起来直观了。 但也无趣了。 大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。

不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看

**Comment by xp12047** [comment]
> > > 点击和输入 “/” 相比，点击会更加方便
> > 
> > 
> > 它真的不方便。 不过是点击看起来直观了。 但也无趣了。 大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。
> 
> 不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看

首先我没有回复你，就不要在我的回复下面回复。你想讨论在这个帖子下面留言那是你的自由但请别随便在我的回复下面回复我明白吗？我了解的我知道的也不一定就比你少明白吗？麻烦有点礼貌好吧？谢谢。

**Comment by mozhux** [comment]
> > > > 点击和输入 "/" 相比，点击会更加方便
> > > 
> > > 
> > > 它真的不方便。不过是点击看起来直观了。但也无趣了。大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。
> > 
> > 
> > 不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看
> 
> 首先我没有回复你，就不要在我的回复下面回复。你想讨论在这个帖子下面留言那是你的自由但请别随便在我的回复下面回复我明白吗？我了解的我知道的也不一定就比你少明白吗？麻烦有点礼貌好吧？谢谢。

现在你回复了我，我可以回复你了吧？首先我上面说的内容有什么不礼貌的字眼吗？其次，你在说人礼貌之前你自己做到了吗？你难道忘了你提的#7801 issue里是什么用词用语了吗？

**Comment by UvDream** [comment]
> > > > 点击和输入 “/” 相比，点击会更加方便
> > > 
> > > 
> > > 它真的不方便。 不过是点击看起来直观了。 但也无趣了。 大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。
> > 
> > 
> > 不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看
> 
> 首先我没有回复你，就不要在我的回复下面回复。你想讨论在这个帖子下面留言那是你的自由但请别随便在我的回复下面回复我明白吗？我了解的我知道的也不一定就比你少明白吗？麻烦有点礼貌好吧？谢谢。

issue，公开的讨论区，况且他有啥不礼貌的？不礼貌的是你吧，那么怕别人回复你，可以在issue里面说话呀

**Comment by xp12047** [comment]
> > > > > 点击和输入 "/" 相比，点击会更加方便
> > > > 
> > > > 
> > > > 它真的不方便。不过是点击看起来直观了。但也无趣了。大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。
> > > 
> > > 
> > > 不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看
> > 
> > 
> > 首先我没有回复你，就不要在我的回复下面回复。你想讨论在这个帖子下面留言那是你的自由但请别随便在我的回复下面回复我明白吗？我了解的我知道的也不一定就比你少明白吗？麻烦有点礼貌好吧？谢谢。
> 
> 现在你回复了我，我可以回复你了吧？首先我上面说的内容有什么不礼貌的字眼吗？其次，你在说人礼貌之前你自己做到了吗？你难道忘了你提的#7801 issue里是什么用词用语了吗？

你踏马一个纯纯二逼啊，我是跟大佬交流的。你麻痹你是有病吧你？二逼一个艹。你有意见你另起一个不就完了艹你麻痹你别在我这下边评论懂嘛？真你妈二逼艹。另外#7801那个我提到你了？对你这种智障我踏马服了。滚尼玛二逼有多远滚多远。草泥马

**Comment by mozhux** [comment]
> > > > > > 点击和输入 "/" 相比，点击会更加方便
> > > > > 
> > > > > 
> > > > > 它真的不方便。不过是点击看起来直观了。但也无趣了。大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。
> > > > 
> > > > 
> > > > 不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看
> > > 
> > > 
> > > 首先我没有回复你，就不要在我的回复下面回复。你想讨论在这个帖子下面留言那是你的自由但请别随便在我的回复下面回复我明白吗？我了解的我知道的也不一定就比你少明白吗？麻烦有点礼貌好吧？谢谢。
> > 
> > 
> > 现在你回复了我，我可以回复你了吧？首先我上面说的内容有什么不礼貌的字眼吗？其次，你在说人礼貌之前你自己做到了吗？你难道忘了你提的#7801 issue里是什么用词用语了吗？
> 
> 你踏马一个纯纯二逼啊，我是跟大佬交流的。你麻痹你是有病吧你？二逼一个艹。你有意见你另起一个不就完了艹你麻痹你别在我这下边评论懂嘛？真你妈二逼艹。另外#7801那个我提到你了？对你这种智障我踏马服了。滚尼玛二逼有多远滚多远。草泥马

这素质，确实不值得我回复了，再见。

**Comment by xp12047** [comment]
> > > > > > 点击和输入 "/" 相比，点击会更加方便
> > > > > 
> > > > > 
> > > > > 它真的不方便。不过是点击看起来直观了。但也无趣了。大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。
> > > > 
> > > > 
> > > > 不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看
> > > 
> > > 
> > > 首先我没有回复你，就不要在我的回复下面回复。你想讨论在这个帖子下面留言那是你的自由但请别随便在我的回复下面回复我明白吗？我了解的我知道的也不一定就比你少明白吗？麻烦有点礼貌好吧？谢谢。
> > 
> > 
> > 现在你回复了我，我可以回复你了吧？首先我上面说的内容有什么不礼貌的字眼吗？其次，你在说人礼貌之前你自己做到了吗？你难道忘了你提的#7801 issue里是什么用词用语了吗？
> 
> 你踏马一个纯纯二逼啊，我是跟大佬交流的。你麻痹你是有病吧你？二逼一个艹。你有意见你另起一个不就完了艹你麻痹你别在我这下边评论懂嘛？真你妈二逼艹。另外#7801那个我提到你了？对你这种智障我踏马服了。滚尼玛二逼有多远滚多远。草泥马

睁开你麻痹狗眼看看，尼玛比你是引用我的回复吧？我允许你引用了嘛？我里面也提到了我是给谁看的。所谓大佬你踏马你是吗？狗币啊卧槽

**Comment by xp12047** [comment]
> > > > > > > 点击和输入 "/" 相比，点击会更加方便
> > > > > > 
> > > > > > 
> > > > > > 它真的不方便。不过是点击看起来直观了。但也无趣了。大佬，三思啊！ 你把斜杠去掉，没有灵魂了啊。
> > > > > 
> > > > > 
> > > > > 不方便是因为现在那个加号的样式没有优化，单栏要一直滑动，等优化成双栏的你再看
> > > > 
> > > > 
> > > > 首先我没有回复你，就不要在我的回复下面回复。你想讨论在这个帖子下面留言那是你的自由但请别随便在我的回复下面回复我明白吗？我了解的我知道的也不一定就比你少明白吗？麻烦有点礼貌好吧？谢谢。
> > > 
> > > 
> > > 现在你回复了我，我可以回复你了吧？首先我上面说的内容有什么不礼貌的字眼吗？其次，你在说人礼貌之前你自己做到了吗？你难道忘了你提的#7801 issue里是什么用词用语了吗？
> > 
> > 
> > 你踏马一个纯纯二逼啊，我是跟大佬交流的。你麻痹你是有病吧你？二逼一个艹。你有意见你另起一个不就完了艹你麻痹你别在我这下边评论懂嘛？真你妈二逼艹。另外#7801那个我提到你了？对你这种智障我踏马服了。滚尼玛二逼有多远滚多远。草泥马
> 
> 这素质，确实不值得我回复了，再见。

我踏马就没让你回复，你他妈二逼。跟你这种二逼讲你妈什么素质我草泥马。上学上你妈脑残了吧你。

**Comment by SineMark2020** [comment]
@88250  xp12047这个人请再处理吧，这种中国低素质人群也挺丢人的.

**Comment by xp12047** [comment]
纯纯一个憨比我操。我是尊重大佬的，尊重siyuan的大佬。#7801那个提到的人可不是你这个二逼。   
我实在是搞不懂你他妈的哪里来的自信在人家给大佬的诉求下面随便评论的呢？人家那是求大佬，你算个鸡八啊？你可以反对。你在主贴下面随便回复。你跑到人家给大佬的留言下面装什么大佬呢？

**Comment by UvDream** [comment]
> 纯纯一个憨比我操。我是尊重大佬的，尊重siyuan的大佬。#7801那个提到的人可不是你这个二逼。 我实在是搞不懂你他妈的哪里来的自信在人家给大佬的诉求下面随便评论的呢？人家那是求大佬，你算个鸡八啊？你可以反对。你在主贴下面随便回复。你跑到人家给大佬的留言下面装什么大佬呢？

评论下咋了？言论自由都没有了？issue讨论区，不就给大家一起讨论的嘛，你咋了？你高贵？这就是你满嘴喷粪的理由？为啥大家都觉得你有问题？你想过吗？

**Comment by mozhux** [comment]
本来不想回复了，但看到你满口尊重，没见过这么阴阳怪气的。记住，互联网有记忆。
![image](https://user-images.githubusercontent.com/46953371/229400723-2e0fa9c6-90c0-4817-94d0-d3f3c22a6df9.png)

**Comment by xp12047** [comment]
> @88250 xp12047这个人请再处理吧，这种中国低素质人群也挺丢人的。

随便处理吧。麻烦你这种高素质人群。现实生活中能做的更好。

**Comment by gingde** [comment]
> 拆分为如下任务： Divided into the following tasks:
> 
> * [x]  [移动端编辑器悬浮工具栏移到底部 #7518](https://github.com/siyuan-note/siyuan/issues/7518)
> * [x]  [移动端键盘工具栏上添加块标菜单功能 #7519](https://github.com/siyuan-note/siyuan/issues/7519)
> * [x]  [移动端根据不同的输入场景对输入工具栏进行切换 #7553](https://github.com/siyuan-note/siyuan/issues/7553)
> * [x]  [移动端根据当前块的类型调整输入工具栏中对应的操作按钮 #7554](https://github.com/siyuan-note/siyuan/issues/7554)
> * [x]  [移动端斜杠菜单移到底部 #7564](https://github.com/siyuan-note/siyuan/issues/7564)
> * [x]  [移动端数据同步提示改进 #7576](https://github.com/siyuan-note/siyuan/issues/7576)
> * [x]  [移动端键盘工具栏上添加面包屑更多菜单功能 #7578](https://github.com/siyuan-note/siyuan/issues/7578)
> * [x]  [移动端底部工具栏移除删除按钮 #7595](https://github.com/siyuan-note/siyuan/issues/7595)
> * [x]  [Android 端块菜单返回支持左右滑动 #7600](https://github.com/siyuan-note/siyuan/issues/7600)
> * [x]  [移动端复习过闪卡后顶部需出现同步按钮 #7610](https://github.com/siyuan-note/siyuan/issues/7610)
> * [x]  [移动端设置二级页面滑动返回上一层 #7655](https://github.com/siyuan-note/siyuan/issues/7655)
> * [x]  [移动端属性设置界面优化 #7661](https://github.com/siyuan-note/siyuan/issues/7661)
> * [x]  [移动端软键盘顶部工具栏遮挡编辑位置 #7632](https://github.com/siyuan-note/siyuan/issues/7632)
> * [x]  [移动端支持点备注打开属性设置界面 #7635](https://github.com/siyuan-note/siyuan/issues/7635)
> * [x]  [移动端输入不触发斜杆菜单 #7681](https://github.com/siyuan-note/siyuan/issues/7681)
> * [x]  [块菜单、编辑器更多菜单等全屏菜单样式优化 #7598](https://github.com/siyuan-note/siyuan/issues/7598)
> * [x]  [移动端左右侧栏全屏和点击区域优化 #7520](https://github.com/siyuan-note/siyuan/issues/7520)
> * [x]  [Add recent documents on mobile #7828](https://github.com/siyuan-note/siyuan/issues/7828)
> * [x]  [Slide and pull out the left and right panel on the mobile #7688](https://github.com/siyuan-note/siyuan/issues/7688)
> * [x]  [Improve the style of the slash menu on the mobile #7596](https://github.com/siyuan-note/siyuan/issues/7596)
> * [x]  [Improve the menu style of the doc tree on the mobile #7852](https://github.com/siyuan-note/siyuan/issues/7852)
> * [x]  [After opening the doc on the mobile, the editor is no longer focused to avoid the pop-up of the soft keyboard #7853](https://github.com/siyuan-note/siyuan/issues/7853)
> * [x]  [Move the mobile exit app button to a more accessible location #7879](https://github.com/siyuan-note/siyuan/issues/7879)
> * [x]  [Prompt to return to the desktop on the Android #7886](https://github.com/siyuan-note/siyuan/issues/7886)
> * [x]  [Enhance mobile search function #7830](https://github.com/siyuan-note/siyuan/issues/7830)
> * [x]  [Flashcard fullscreen display on the mobile #7932](https://github.com/siyuan-note/siyuan/issues/7932)
> * [x]  [Add transitions for popup menu on mobile #7934](https://github.com/siyuan-note/siyuan/issues/7934)
> * [x]  [Support KaTex macro definition on the mobile #7909](https://github.com/siyuan-note/siyuan/issues/7909)
> * [x]  [Search input optimization for code block language, templates, embedded blocks, etc. #7597](https://github.com/siyuan-note/siyuan/issues/7597)

D大，我现在还是只要打开安卓移动端，切换到编辑状态，马上就卡死  思源笔记没有响应
每星期测试一次，都不行。不知道这个是什么情况
已经一个多月了，重装重启都不管用。 手机系统是MUI14.

**Comment by 88250** [comment]
@gingde 安装过社区主题或者其他什么扩展吗？

**Comment by Soltus** [comment]
@gingde 麻烦加我QQ 694357845 排查问题

**Comment by gingde** [comment]
仅仅在Windows端安装过集市里面的主题，除此之外，在安卓端没有任何其他 操作。手机端是MIUI14，电脑端一个是win10系统 一个是win11系统，&nbsp; 每次都及时更新，但是这个情况已经一个多月 了，很久了。电脑端的都能正常使用，但是安卓端一直不行。






刘某乐
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] Improve the interactive user experience on the mobile (Issue #7335)





 
@gingde 安装过社区主题或者其他什么扩展吗？

**Comment by dongyining** [comment]
文字一多就不响应

![Image](https://user-images.githubusercontent.com/22189919/231386104-33fc663b-f8e0-4337-bc6e-d2aa2c46772a.png)



![Image](https://user-images.githubusercontent.com/22189919/231386199-c2f782ce-81c7-4e52-81cb-64828a36138a.jpg)

**Comment by Soltus** [comment]
@dongyining 麻烦加我QQ 694357845 排查问题

**Comment by gingde** [comment]
已经添加&nbsp; 我的QQ是1287313055&nbsp; 要有
&nbsp;


刘某乐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月12日(星期三) 下午3:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] Improve the interactive user experience on the mobile (Issue #7335)





 
@dongyining 麻烦加我QQ 694357845 排查问题

**Comment by Soltus** [comment]
> 已经添加&nbsp; 我的QQ是1287313055&nbsp; 

我知道。艾特的是另一个人
