### ISSUE TITLE
PDF 页签中有时无法正确复制选中的文字

### ISSUE THREAD

**Issue by Louie901119** [siyuan-note/siyuan#7336]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

在思源笔记当中开启PDF时，有时无法正确複制选中的文字。

以此PDF為例：
[test.pdf](https://github.com/siyuan-note/siyuan/files/10712579/test.pdf)

当我如下图选中文字，並按Ctrl+C时，得到的剪贴板内容只有「transmission 」
![image](https://user-images.githubusercontent.com/88768177/218238530-f2b720d5-3cd6-4506-8b4c-5dcaff5370be.png)

如果想要复制「transmission rate」，必须如下图选中文字再按Ctrl+C
![image](https://user-images.githubusercontent.com/88768177/218238620-4622efee-e58f-4e7a-8a3b-0b3ccdeb6754.png)

这个问题在其他PDF编辑器（如Xchange pdf editor）当中没有遇到。

### 期待的结果 Expected result

希望能够正确複制选中的文字而不出现以上问题。

### 版本环境 Version environment

```markdown
- Version: v2.7.4
- Operating System: Win11
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10712593/system-log.zip)

**Comment by 88250** [comment]
我这里测试没有重现该问题。

![issue](https://user-images.githubusercontent.com/873584/218239871-c3f9395f-51e4-4279-87e8-14cce8bda419.gif)

**Comment by Louie901119** [comment]
可是我重新开了一个工作空间，所有设置都是默认的，依然会出现这个问题

https://user-images.githubusercontent.com/88768177/218241821-2fc1d5cb-2a0d-4a53-954b-5083c00f4e45.mp4

**Comment by 88250** [comment]
系统上有其他程序会读取/写入剪切板吗？比如单词软件啥的。

**Comment by Louie901119** [comment]
我把所有可能读取/写入剪切板的应用（比如剪贴板应用、Quicker）关掉了，再试一次还是一样。而且我在其他应用（如Xchange pdf editor）打开此PDF不会发生这个问题。
我感觉好像是PDF显示有错位问题，真正选中的文字並不是屏幕上反白的部分，
比如我上面的录屏原本是想複制「radio spectrum」，结果真正複制到的是radio spectrum前面的几个字母「fiber, and r」

**Comment by 88250** [comment]
方便的话请试下 dev 版是否能重现。

**Comment by Louie901119** [comment]
dev 版是指这个版本吗？
![image](https://user-images.githubusercontent.com/88768177/218250633-c2db1631-a696-49d5-9217-b6c354dbf9ac.png)

**Comment by 88250** [comment]
是的。

**Comment by Louie901119** [comment]
还是一样

https://user-images.githubusercontent.com/88768177/218251297-ca8a64d3-7e69-47a4-8bd7-f1359286a575.mp4

**Comment by 88250** [comment]
这个暂时无法确认问题，我们先保持 issue 打开吧。

**Comment by Louie901119** [comment]
找到原因了，
我原本的windows显示语言是「中文（台湾）」，
现在改成「中文（中华人民共和国）」就没有这个问题了。
![image](https://user-images.githubusercontent.com/88768177/218255659-a8ed85e9-a43f-4573-a7b9-797d50703652.png)



希望思源之后的版本能够针对「中文（台湾）」做出完整的适配。

**Comment by 88250** [comment]
原来如此，等有空我们会尝试解决这个问题的，感谢反馈。

**Comment by Louie901119** [comment]
更新一下，
雖然windows顯示語言改成「中文（中华人民共和国）」之後，PDF顯示錯位問題比起「中文（台湾）」改善很多，
但我覺得還有改善的空間，
以同一個PDF為例，
我想要複製第二段的「network core」，如下這樣選中，會得到「e network cor」
![image](https://user-images.githubusercontent.com/88768177/218310556-4874a75d-0170-4cf5-bf9b-6d51aa6d927d.png)
必須如下這樣選中，才能得到「network core」，「n」幾乎不在反白範圍，「.」已經在反白範圍內了
![image](https://user-images.githubusercontent.com/88768177/218311042-1f3dfc4d-b56e-425e-a4c1-69ec4cc49077.png)

這樣就導致有時候複製一段話要試好幾遍才能成功。

**Comment by Vanessa219** [comment]
可以看一下中文和繁体这块代码嘛？ Mac 下中文和英文字体都是一样的，画选复制没有问题。
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/970828/218358139-4810a719-7490-4f63-9ab9-112b56b19637.png">

**Comment by Louie901119** [comment]
![image](https://user-images.githubusercontent.com/88768177/218448634-0dec5a56-7ab5-4cb7-8b6f-a55f3e66fbbf.png)

**Comment by Vanessa219** [comment]
很难看出具体问题，可能需要等待 https://github.com/mozilla/pdf.js/labels/text-selection 的修复，我先关闭了。

**Comment by Louie901119** [comment]
後來發現，當「windows顯示語言」和「思源設置裡的外觀顯示語言」不同的時候，就會發生比較嚴重的錯位
![image](https://user-images.githubusercontent.com/88768177/228114501-86c1bddd-1aba-41ff-ad3f-b12b7ed9201b.png)
![image](https://user-images.githubusercontent.com/88768177/228114908-0cb56b07-1672-41a6-a1af-b821b68ce05b.png)

如果這是pdf.js的問題，建議提醒一下用戶不要將「windows顯示語言」和「思源設置裡的外觀顯示語言」設定成不同的語言，否則可能會導致顯示問題。

**Comment by Vanessa219** [comment]
最新版本升级了 pdf.js, 目前还有这个问题么？

**Comment by Louie901119** [comment]
v2.8.2 還是有這個問題。

**Comment by Vanessa219** [comment]
没有找到和系统语言相关的设置，我们设置语言的时候也没有做除了显示外的修改。目前还没有办法定位问题。
