### ISSUE TITLE
`只读模式` 下搜索预览窗口仍然可以编辑

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#7337]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

不小心在搜索的时候的预览窗内填入了不必要的文字，想请问这个是特性还是 bug

### 期待的结果 Expected result

只读模式的范围明确。另外之前发现只读模式下依旧可以在做文档树新建文档，但是不能编辑，是否考虑限制新建文档 （反正也不能编辑）。

### 版本环境 Version environment

```markdown
- Version: 2.7.4
- Operating System: win 11
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
> 另外之前发现只读模式下依旧可以在做文档树新建文档，但是不能编辑，是否考虑限制新建文档 （反正也不能编辑）。

编辑器的只读模式不控制新建/删除文档这些，这个需要用全局只读模式，不过在桌面端没有该功能入口，这个是个内核参数，主要提供给服务器部署时使用。

**Comment by XinLi0111** [comment]
明白了，桌面端的只读模式更多的防误触吧。感谢 D 大回复。
