### ISSUE TITLE
导出图片不显示表格

### ISSUE THREAD

**Issue by xp12047** [siyuan-note/siyuan#7338]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

导出浏览器打开的时候里面的表格内容没了，这是什么情况？

### 期待的结果 Expected result

帮忙看看，谢谢！

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Screenshot_20230211_220403_com android chrome](https://user-images.githubusercontent.com/56335408/218262239-187f9dc0-9a5e-4d54-adfa-207984fded7c.jpg)
![Screenshot_20230211_220346_org b3log siyuan](https://user-images.githubusercontent.com/56335408/218262221-ae866567-f5a4-4676-8a49-0473a4373727.jpg)
![Screenshot_20230211_220354_org b3log siyuan](https://user-images.githubusercontent.com/56335408/218262229-b24bb618-d442-4e9e-a7e6-99a41071eec0.jpg)         

### 版本环境 Version environment

```markdown
- Version: V2.7.4
- Operating System: 鸿蒙os3.0
- Browser (if used):chrome 安卓
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10713828/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，测试了一下发现桌面端也有这个问题。

**Comment by xp12047** [comment]
> 感谢反馈，测试了下发现桌面端也有这个问题。

谢谢😊

**Comment by 88250** [comment]
还没有修复的，修复后我们来关闭，谢谢。

**Comment by xp12047** [comment]
> 还没有修复的，修复后我们来关闭，谢谢。

哦
