### ISSUE TITLE
提几个编辑内容时提高效率的功能要求

### ISSUE THREAD

**Issue by windoversnow** [siyuan-note/siyuan#734]
1. 我很好奇，很多markdown软件竟然都不支持查找替换功能呢。既然能把查找做的很棒，加一个替换应该也不难吧，就类似word里的**查找替换**。这个最迫切。
2. **类ppt功能**，obsidian中有这个功能，其实也有专门做演示汇报的markdown软件，有时候，做个简报，不需要PowerPoint花哨的动画，只是每页几个大标题、简短的文字，配一张图足以，markdown专心写作、少操心排版的理念用来做这个也挺合适的
3. 纯markdown格式的文件支持**文字颜色**是不是挺难的？
4. 表格功能要加强一点，**想能够自定义列宽**，哪怕是表格充满页面宽度，只能定义各列的百分比也好。
5. 编辑窗口内，**按标题折叠**和按**缩进列表折叠**

**Comment by 88250** [comment]
你好，感谢提议。

1. 搜索替换请关注 https://github.com/siyuan-note/siyuan/issues/344
2. PPT 请关注 https://github.com/siyuan-note/siyuan/issues/392
3. 文字颜色请关注 https://github.com/siyuan-note/siyuan/issues/620
4. 列宽暂时没有考虑，因为语法问题……

我关闭了，如果还有反馈欢迎继续跟帖，谢谢。

**Comment by windoversnow** [comment]
> 你好，感谢提议。
> 
> 1. 搜索替换请关注 #344
> 2. PPT 请关注 #392
> 3. 文字颜色请关注 #620
> 4. 列宽暂时没有考虑，因为语法问题……
> 
> 我关闭了，如果还有反馈欢迎继续跟帖，谢谢。

额，回复好快，加了个5.。。。。。。

**Comment by windoversnow** [comment]
OK了，看到5在近期计划里了

**Comment by windoversnow** [comment]
很棒的软件，加油

**Comment by 88250** [comment]
5. 内容块折叠 https://github.com/siyuan-note/siyuan/issues/262
