### ISSUE TITLE
[New Feature] Completion of Back Links Support Searching Chinese by Pinyin

### ISSUE THREAD

**Issue by abd-liac** [siyuan-note/siyuan#7345]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Auto complete back link anchors.

### 描述可能的最优解决方案 Describe the optimal solution

[Example implemtation](https://github.com/mozillazg/go-pinyin)

**Comment by 88250** [comment]
这个估计实现不了，数据库没有拼音分词索引。
