### ISSUE TITLE
Windows 7, 8 and Server 2012 are no longer supported

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7347]
https://github.com/siyuan-note/siyuan/issues/7324

The last version to support these old systems is the next version v2.8.10, and later versions will no longer support Windows 7, 8 and Server 2012, please upgrade to Windows 10 and above.

**Comment by kaka77** [comment]
请问哪个版本支持WIN7呀？谢谢

**Comment by 88250** [comment]
@kaka77 目前的版本 v2.7.6 还支持。
