### ISSUE TITLE
引入新的编辑模式 - 脑图模式

### ISSUE THREAD

**Issue by jenkinchang** [siyuan-note/siyuan#735]
* 支持在即时渲染编辑模式之间切换或者分屏同时编辑
* 支持节点插入、拖拽移动、删除、编辑
* 通过悬浮编辑支持更新节点内容

为脑图添加以下菜单

* 缩放
* 模版
* 拖拽
* 居中
* 布局整理
* 布局
* 主题
* 展开层级

**Comment by 88250** [comment]
谢谢反馈，候选方案中提到的脑图目前已经有了，可以看下帮助文档 - Markdown 使用指南 - 完整示例，不过目前来说渲染比较丑……

该特性应该是要实现的，具体实现方案还需要时间考虑，请再等等看，谢谢。

**Comment by jenkinchang** [comment]
哇谢谢，我看了下mindmap已经够用了，但是能不能加一个展开的按钮，因为脑图在小框框里面看着太挤了

然后是能不能，在插入第三方脑图的附件时，渲染一个缩略图呢，这样也很方便，想编辑直接点击之后在脑图软件里编辑就可以了

**Comment by 88250** [comment]
* 编辑器内的脑图语法后面会调整优化
* 和第三方软件联动可以用超链接到具体文件路径，然后通过默认程序打开，缩略图渲染估计是办不到

谢谢。

**Comment by liyang-good** [comment]
![image](https://user-images.githubusercontent.com/71406269/211154167-0f4e8797-5f7d-4d30-b27b-2e3a2703380d.png)


我的root去不掉，请问怎么办
