### ISSUE TITLE
SQL 搜索支持多个搜索关键字匹配文档

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7350]
* https://ld246.com/article/1669862497678
* https://ld246.com/article/1671364011101

**Comment by 88250** [comment]
仅支持用 SQL 搜索方式：

```sql
select a.*
from blocks as a,
     (select *
      from blocks
      where id in
            (select root_id from blocks where content like '%思源%')
        and id in
            (select root_id from blocks where content like '%本地%')) as b
where a.root_id = b.id
  and (a.content like '%思源%' or a.content like '%本地%')
```

以下截图是按文档分组的结果：

![image](https://user-images.githubusercontent.com/873584/218360444-d4b34388-e9dc-441c-b644-5e8fa9aa834f.png)

**Comment by mozhux** [comment]
有点复杂啊。。那这样对应的高亮有吗

**Comment by 88250** [comment]
SQL 搜索没有高亮，如果一定要的话可以看下源码，参考源码用 fts 可以实现。

**Comment by mozhux** [comment]
那似乎现在的版本就支持多条件搜索匹配呀。。新版是支持了什么新东西吗？
```sql
select * from blocks where (id in(select root_id from blocks where content like '%思源%')) and  (id in (select root_id from blocks where content like '%本地%')) 
```
![image](https://user-images.githubusercontent.com/46953371/218367832-5109ef5b-c98d-441c-ad9f-be2a4ad2787a.png)

**Comment by 88250** [comment]
是的，支持显示到具体命中的块。
