### ISSUE TITLE
显示器缩放后新窗口的关闭按钮和下拉按钮重叠

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/siyuan#7355]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 描述问题 Describe the problem

新窗口顶栏图标重叠
![image](https://user-images.githubusercontent.com/46953371/218362396-f12bd372-527c-4ed5-92c1-a4af60e3c5b6.png)

### 期待的结果 Expected result

应该是不重叠的，另外希望能增加固定按钮，能固定新窗口，目前新窗口和主程序不能共存

### 版本环境 Version environment

```markdown
- Version: 2.7.4 （dev2）
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

wu

**Comment by 88250** [comment]
我这里正常，打开开发者工具强制刷新一下后再试试，开发版因为没改版本号，所以需要手动刷新缓存。

**Comment by mozhux** [comment]
> 我这里正常，打开开发者工具强制刷新一下后再试试，开发版因为没改版本号，所以需要手动刷新缓存。

刷新过的，我刚验证了一下，是因为窗口缩放了，我Ctrl+-缩放了一格，默认状态下没问题。
但缩放的情况应该也是要考虑的把

**Comment by 88250** [comment]
我这里缩小以后也正常。

**Comment by mozhux** [comment]
我这里显示器缩放125%
思源缩放1次。
复现步骤是。
1.先关掉所有新窗口，然后缩放主页面
2.打开日记，通过页签打开新窗口

如果是先打开新窗口再缩放没问题。
这里又印发一个新问题，新窗口的缩放和主程序不一致，在新窗口焦点上操作的缩放不会影响主程序，这个是特性吗？

**Comment by 88250** [comment]
还是重现不了。

> 在新窗口焦点上操作的缩放不会影响主程序，这个是特性吗？

是。

**Comment by 88250** [comment]
显示器 125% 以后可以重现了。

**Comment by mozhux** [comment]
> 显示器 125% 以后可以重现了。

那应该算问题咯

**Comment by mozhux** [comment]
> 显示器 125% 以后可以重现了。

显示器缩放应该是正常操作。2k缩放125  4k缩放150，但不知道4k缩放有没有问题
