### ISSUE TITLE
新窗口支持钉住置顶

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7356]

**Comment by pisceswb** [comment]
请问能否添加功能，在状态栏思源图标右键功能中，可以新建这样置顶的窗口？

**Comment by 88250** [comment]
@pisceswb 这个加不了。

**Comment by mozhux** [comment]
那对应的窗口置顶能不能像缩放一样，焦点在哪置顶哪个？
还有就是右键功能新增一个新建日记？

**Comment by 88250** [comment]
每个新窗口上都加一个 pin 按钮

**Comment by mozhux** [comment]
> 每个新窗口上都加一个 pin 按钮

这个明白，我意思这个只是在软件内的pin,右下角菜单那个是系统层级的，能不能强化到系统层级哈哈

**Comment by 88250** [comment]
这个 issue 就是系统窗口置顶。
