### ISSUE TITLE
文档树中的文档提示信息不正确

### ISSUE THREAD

**Issue by c-my** [siyuan-note/siyuan#7364]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

鼠标悬浮在【文档树】中的文档项上时，会在tooltip中显示【包括文档名称在内的文档信息】。

但重命名文档后，tooltip中的文档名不会更新。（重建索引后文档名才可以正确显示）

### 期待的结果 Expected result

tooltip中的文档名与实际一致

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/22538534/218688611-51ebe9f0-d7be-48b1-b672-3a2768674415.png)

说明：新建文档默认名称为"Untitled"，修改文档名称后，tooltip中仍显示"Untitled"。

### 版本环境 Version environment

```markdown
- Version: v2.7.4
- Operating System: Windows 11 22H2 22621.1105
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://gist.github.com/c-my/ae80dc57220ab2fb92f9201a0a3d0e2f)

**Comment by c-my** [comment]
> 这个需要重新展开文档树才会刷新。

所以这不被认为是功能缺陷哈？🙁

**Comment by 88250** [comment]
目前是设计如此，很多地方都需要手动刷新，不是实时更新的。
