### ISSUE TITLE
移动端链接菜单调窄

### ISSUE THREAD

**Issue by xp12047** [siyuan-note/siyuan#7365]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

当我输入/link 调出链接补充框的时候。那个框太大了还没办法缩小。

### 期待的结果 Expected result

希望和之前版本的一样不要那么大的框框。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Screenshot_20230214_173633_org b3log siyuan](https://user-images.githubusercontent.com/56335408/218696672-2478e792-9b82-4d33-b582-674862b6a89b.jpg)
通过手机谷歌市场升级的。界面是比原来丝滑多了很棒。就是这个框框也太靠边了吧。怎么把它缩小？

### 版本环境 Version environment

```markdown
- Version: V2.7.5
- Operating System: 华为鸿蒙
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10730935/siyuan.log)

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/7339 @Vanessa219
