### ISSUE TITLE
搜索自定义属性改为搜索全部属性

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#7367]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

这是一个非常奇怪的bug。它会搜索到完全不相关的内容。
![图片](https://user-images.githubusercontent.com/74853597/218733763-3147f03c-30e3-4738-a3ca-84fa766875ce.png)

### 期待的结果 Expected result

能搜索到正确的内容

### 截屏或者录屏演示 Screenshot or screen recording presentation

这是一个非常奇怪的bug。

我本来以为是版本的问题，但是我发现在虚拟机安装后，这个bug不会出现。

然后我以为是我数据的问题，结果把我的数据导入之后，他也没有问题。

所以我怀疑他可能是思源工作空间中某一项的问题，当我把思源工作空间完全导入虚拟机之后，这个bug就能复现了。

经过不断的筛选，我把问题定位到conf.json，也就是思源的设置文件。

在经过使用git diff逐项对比，默认生成的设置文件，我找到了问题在于搜索设置的 属性 自定义。

把这个选项打开，就会搜到这种完全不相关的内容。

不得不说，这个是真的很奇怪的bug，排查的很难，出现的也很奇怪，我要是直接报上来，感觉会因为无法复现而直接关闭……

### 版本环境 Version environment

```markdown
- Version: v 2.7.2
- Operating System: win10 
- Browser (if used):
```

### 日志文件 Log file

无需日志

**Comment by 88250** [comment]
感谢反馈，是因为打开这个选项以后会在属性中搜索，然后可能关键字会命中 ID 属性。

**Comment by 88250** [comment]
研究了一下，目前仅能够在所有属性上进行模糊搜索，无法界定自定义属性，这个问题我们改一下需求吧……

把 设置 - 搜索 - 属性 - 自定义 改为 所有属性

在属性名和属性值上同时搜索。

**Comment by zxhd863943427** [comment]
也就是说，以后搜索bookmark会搜索到所有带书签的块了？

**Comment by 88250** [comment]
现在也是这样的吧

**Comment by 88250** [comment]
这个 issue 相当于只是改一下配置项：

![image](https://user-images.githubusercontent.com/873584/218950848-ca68894e-a381-4cf4-bfbb-1f64eb214d28.png)

**Comment by zxhd863943427** [comment]
以前还真没注意到……所以示例里 png 现在会命中 data-node-id 感觉没办法了

**Comment by zxhd863943427** [comment]
话说，data-node-index是什么属性？

**Comment by 88250** [comment]
> 以前还真没注意到……所以示例里 png 现在会命中 data-node-id 感觉没办法了

好消息：可以搜索属性名和值了
坏消息：可能会被干扰

如果不要干扰的话，目前只能用 SQL 搜索了，关联 attributes 表，或者用正则表达式搜索。

**Comment by 88250** [comment]
> 话说，data-node-index是什么属性？

前端编辑器用于动态加载的。

**Comment by zxhd863943427** [comment]
刚刚测试了一下正则表达式，发现搜索到结果不会显示出来：
![图片](https://user-images.githubusercontent.com/74853597/218953026-ed926be0-771a-4eec-b76a-5d19ae98289c.png)
这是设计如此吗？

**Comment by 88250** [comment]
.*信息.*

**Comment by zxhd863943427** [comment]
就是单纯的内容文本，刚刚尝试移除了命名查询，又可以了。
![图片](https://user-images.githubusercontent.com/74853597/218955653-e07ec031-3f53-47da-aee1-5b00f2f2a495.png)

**Comment by 88250** [comment]
那可能是命名查询里面有其他条件吧。
