### ISSUE TITLE
弹框关不了

### ISSUE THREAD

**Issue by psyuhen** [siyuan-note/siyuan#7369]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/6522440/218898562-dc01cdb4-9cee-41b0-b9bb-61f065b21141.png)
弹出框关不了。

### 期待的结果 Expected result

能关闭或者不要显示出来。

### 版本环境 Version environment

```markdown
- Version: 2.7.4
- Operating System: windows 11
- Browser (if used):
```

### 日志文件 Log file

   /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/02/14 14:18:36 runtime.go:49: kernel is booting:
    * ver [2.7.4]
    * arch [amd64]
    * pid [37664]
    * runtime mode [prod]
    * working directory [C:\Users\psyuh\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\work\siyuan\SiYuan]
I 2023/02/14 14:18:36 runtime.go:94: use network proxy [system]
I 2023/02/14 14:18:36 serve.go:108: kernel [pid=37664] http server [0.0.0.0:9038] is booting
I 2023/02/14 14:18:36 working.go:396: built-in pandoc [ver=2.19.2, bin=D:\work\siyuan\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/02/14 14:18:36 blocktree.go:386: read block tree [1.8 MB] to [D:\work\siyuan\SiYuan\temp\blocktree], elapsed [0.01s]
I 2023/02/14 14:18:36 conf.go:622: database size [23 MB], tree/block count [122/6338]
I 2023/02/14 14:18:36 working.go:157: kernel booted
I 2023/02/14 14:18:37 box.go:74: auto stat [trees=122, blocks=6338, dataSize=150 MB, assetsSize=7.3 MB]
I 2023/02/14 14:18:37 disk.go:33: disk usage [total=296 GB, used=155 GB, free=141 GB]
I 2023/02/14 14:18:38 serve.go:121: reverse proxy server [0.0.0.0:6806] is booting
I 2023/02/14 16:18:37 box.go:74: auto stat [trees=123, blocks=6375, dataSize=150 MB, assetsSize=7.5 MB]
I 2023/02/14 16:18:37 disk.go:33: disk usage [total=296 GB, used=155 GB, free=141 GB]
I 2023/02/14 16:21:36 updater.go:173: downloading install package [https://release.b3log.org/siyuan/siyuan-2.7.5-win.exe]
E 2023/02/14 16:31:36 updater.go:182: download install package [https://release.b3log.org/siyuan/siyuan-2.7.5-win.exe] failed: net/http: request canceled (Client.Timeout or context cancellation while reading body)
I 2023/02/14 16:31:37 updater.go:173: downloading install package [https://ghproxy.com/https://github.com/siyuan-note/siyuan/releases/download/v2.7.5/siyuan-2.7.5-win.exe]
I 2023/02/14 16:32:12 updater.go:191: downloaded install package [https://ghproxy.com/https://github.com/siyuan-note/siyuan/releases/download/v2.7.5/siyuan-2.7.5-win.exe] to [D:\work\siyuan\SiYuan\temp\install\siyuan-2.7.5-win.exe]
W 2023/02/14 17:42:42 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/02/14 17:42:57 process.go:72: no active UI proc, continue to check from all processes after 15s
W 2023/02/14 17:43:12 process.go:80: confirmed no active UI proc, exit kernel process now
I 2023/02/14 17:43:12 conf.go:403: exiting kernel [force=false, execInstallPkg=1]
I 2023/02/14 17:43:12 database.go:1115: closed database
I 2023/02/14 17:43:12 conf.go:768: cleared workspace temp
I 2023/02/14 17:43:13 conf.go:450: exited kernel

**Comment by 88250** [comment]
请升级到最新版，应该已经修复。
