### ISSUE TITLE
大纲搜索过滤

### ISSUE THREAD

**Issue by leeyaunlong** [siyuan-note/siyuan#737]
需求: 
能否增加如下功能
- 大纲的自动更新
现在还有缺陷, 比如 创建连续创建多个 2级标题,以及子标题内容等.
只会在大纲上列出最先创建的一个.
反复用上下键滚动这些文本, 会吧剩下的二级标题带出来, 但是2级一下的无法显示
- 增加大纲自动展开或者手工快捷键展开(在编辑区焦点中). 
每次刷新大纲后,就会全部收拢, 非常不方便
- 大纲的搜索, 过滤
大纲目前不能跟关系图一样搜索,和过滤, 建议加上.

**Comment by 88250** [comment]
你好，感谢反馈。

* 大纲是自动更新的，子层级需要鼠标移动到大纲区域才会显示展开箭头
* 大纲的展开折叠请关注 https://github.com/siyuan-note/siyuan/issues/564 
* 搜索过滤是个很好的建议

**Comment by leeyaunlong** [comment]
> 你好，感谢反馈。
> 
> * 大纲是自动更新的，子层级需要鼠标移动到大纲区域才会显示展开箭头
能否提供一个选项,设置后一直自动展开, 不需要每次点, 或者移动
写长篇的文章的, 思路是跳跃的, 零碎的写些子片段进去后, 结果大纲是顶层折叠的.  无法整理思路.
尽管关系图是完整展开的,但是缺乏层次结构.
我想这也是大纲存在的作用.

**Comment by 88250** [comment]
@leeyaunlong 你好，大纲折叠展开将在 #564 中实现，谢谢。

**Comment by 88250** [comment]
@Vanessa219 大纲调整为默认展开。
