### ISSUE TITLE
思源手机端-左侧层级目录点击不能展开目录

### ISSUE THREAD

**Issue by geosmart** [siyuan-note/siyuan#7371]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

android手机端-左侧层级目录点击展开目录，每次点击都是打开当前页

### 期待的结果 Expected result

期望展开当前目录

### 版本环境 Version environment

```markdown
- Version: 3.7.3
- Operating System: android
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
需要点击展开箭头靠左一侧的空白区域，不要点箭头。
