### ISSUE TITLE
文档名虚拟引用遵循搜索大小写设置

### ISSUE THREAD

**Issue by why8023** [siyuan-note/siyuan#7372]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

大小写不一致时, 虚拟引用显示无法找到内容块 , 搜索设置中已经关闭了区分大小写选项

### 期待的结果 Expected result

不区分大小写的条件下, 能够正常引用

### 截屏或者录屏演示 Screenshot or screen recording presentation

<img width="775" alt="image" src="https://user-images.githubusercontent.com/22267652/218904343-239ed260-13ab-4c61-b643-1b05b8df83f9.png">

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: macOS Ventura
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10738407/siyuan.log)

**Comment by 88250** [comment]
虚拟引用是完全匹配才能识别，这个是设计如此，感谢反馈。

**Comment by 88250** [comment]
好像是个 bug，稍后我们确认下。

**Comment by 88250** [comment]
已经确认是个 bug，下个版本改进为虚拟引用遵循大小写设置。
