### ISSUE TITLE
iPad 7 上使用 WebDAV 同步文件闪退

### ISSUE THREAD

**Issue by livevol89** [siyuan-note/siyuan#7373]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

ipad 7设备上，使用webdav同步远端文件以后，同步过程中，突然闪退，重新打开也依然闪退，无法打开思源笔记

### 期待的结果 Expected result

修复该问题，支持ipad7，使用webdav同步远端数据，正常使用思源笔记

### 版本环境 Version environment

```markdown
2.7.5
```

### 日志文件 Log file

无法确认到

**Comment by 88250** [comment]
是正在下载了大量数据吗？

**Comment by 88250** [comment]
另外，能否使用其他设备测试一下是否正常，谢谢。

**Comment by livevol89** [comment]
对，远程文件大概有10g左右，本地已经下载9.几个G，下载过程中突然闪退，重新启动思源笔记以后就无法启动笔记本了。 重新卸载安装以后，同步远程文件依然有相同问题，目前手里只有一个ipad7设备。 本地PC端(win10）备份远程数据库是没有问题可以正常使用的。

**Comment by 88250** [comment]
请上传一下内核日志文件，位于工作空间/temp/siyuan.log

**Comment by 88250** [comment]
好像 Pad 上无法获取到文件，这个有点棘手。

**Comment by 88250** [comment]
试下开启同步前通过其他设备导出 Data 然后导入 Data，也许能解决问题。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
