### ISSUE TITLE
改进打开虚拟引用后加载文档的性能

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7378]
之前通过关键字限制可以解决部分问题 https://github.com/siyuan-note/siyuan/issues/6603 但是有的场景还是需要大量关键字，得尽量从根本上解决性能问题。

加载文档时缩小关键字范围，将全量的关键字列表缩小到该文档涉及的较小关键字列表，并加入缓存。

这个改进以后第一次打开文档可能还是会有点慢，后续再次打开命中缓存以后就好很多了。

**Comment by UFDXD** [comment]
性能提升明显。只是有的虚拟引用明显悬浮窗有内容，通知还是提示未找到ID

**Comment by 88250** [comment]
@UFDXD 重建索引后再试试。

**Comment by UFDXD** [comment]
已经重建索引了但是还是有问题。但仔细查看发现， 是同义虚拟引用问题。这个问题之前几个版本也存在。问题就是已经排查发现并不存在命名别名等其他导致出现同义虚拟引用词，但是还是会出现多虚拟引用悬浮窗。并且其中一个悬浮窗内容是空的。这个空的悬浮窗以前内会有文本提示的，现在没有文本提示而是改通知提示了。

虽然没办法定位具体原因。但能不要不由右上角通知，红色的通知老是出来要手动点很烦的。

**Comment by 88250** [comment]
能否将 data 压缩后打包发我测试一下 845765@qq.com 打包后去掉 assets 文件，这样小一些。

**Comment by UFDXD** [comment]
@88250 是工作内容笔记，不能发的。抱歉了。

**Comment by 88250** [comment]
没事，后面如果有重现数据集的话麻烦发我吧，谢谢。

**Comment by UFDXD** [comment]
好的，我会新开一个不重要的笔记，尝试重现问题。但是能不能改回以前那种悬浮窗内文本提示，而不是通知

**Comment by 88250** [comment]
报错通知内容是 "block not found" 吗？是的话改不了，这个是通用的。

**Comment by UFDXD** [comment]
是这种。
![image](https://user-images.githubusercontent.com/97731736/219558577-32a6d08f-e6f2-4901-bc9e-ac00a10f4ea8.png)

**Comment by 88250** [comment]
你看下全局搜索里面能否直接搜索到这个 id

**Comment by UFDXD** [comment]
![image](https://user-images.githubusercontent.com/97731736/219559178-42d0d74f-c624-4e2b-8f30-38263dcf4b68.png)

**Comment by UFDXD** [comment]
这是虚拟引用悬浮窗
![image](https://user-images.githubusercontent.com/97731736/219559528-9a3cf3da-20f1-4f02-a6f0-e297a5a2ce53.png)

**Comment by 88250** [comment]
那应该是因为这个引用锚文本指向的定义块已经不存在了。

**Comment by UFDXD** [comment]
![image](https://user-images.githubusercontent.com/97731736/219559702-b5307c2c-9c9c-4604-936a-7bdf7a502f28.png)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/219559718-b9a41872-318a-4b2b-b928-0996d02e7b2c.png)

**Comment by UFDXD** [comment]
事实是我排查过，并有导致出现同义虚拟引用的情况。

**Comment by UFDXD** [comment]
可能是历史同名过，后来修改删掉了。

**Comment by 88250** [comment]
不同引用（相同锚文本）分别指向不同的定义块这个是正常的。

**Comment by UFDXD** [comment]
[1772/1955] 已经建立 [13] 个块级元素的搜索索引 [445c856] (2023-02-17 14:03:23)

卡在这不动了是正常的吗？

**Comment by 88250** [comment]
多等一下，或者随便找个文档打个字看下是否会变，会变的话就正常了。

**Comment by UFDXD** [comment]
有办法消除“已经不存在”的“定义块”虚拟引用指向内容窗口吗？

**Comment by UFDXD** [comment]
重建索引几次了。好像不起效果。

**Comment by 88250** [comment]
找到那个引用，然后把引用指向存在的地方。试下在文件系统上搜索这个 id

**Comment by UFDXD** [comment]
好吧问题解决了，确实是引用描文本指向不存在问题。但是！我将描文本识别关掉了啊。根本没考虑这一层。
![image](https://user-images.githubusercontent.com/97731736/219567391-9585e520-a533-4595-9f9f-4246ceaa8caa.png)
这个开关没有生效。是bug吗？

**Comment by 88250** [comment]
这个是 10 分钟刷新一次，目前得等定时刷新缓存。

**Comment by UFDXD** [comment]
这个选项我怕影响性能用思源起起老早就关掉了哎……真是摸不着头脑。
