### ISSUE TITLE
左侧图标和系统的最大化图标距离太近了

### ISSUE THREAD

**Issue by 52511338** [siyuan-note/siyuan#738]
### 描述问题 Describe the problem
左侧图标和系统的最大化图标距离太近了

````````markdown
如果是解析渲染问题的话请在此处贴入 Markdown 原文
If it is a problem of parsing and rendering, please post the original Markdown here
````````

### 截屏或录像 Screenshot or video
<img width="181" alt="image" src="https://user-images.githubusercontent.com/46547255/102161075-3b517c80-3eb9-11eb-9c0f-d663eca7452d.png">

### 版本环境 Version environment

* 版本 Version：0.5.1
* 操作系统 Operating system：macOS Big Sur 11.1
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
收到，稍后排查，谢谢。

来自另一个用户的反馈：![I53`IXBD)CV$7 H9TT1{@)U](https://user-images.githubusercontent.com/873584/102163232-bae54880-3ec5-11eb-8337-343ef94b2406.jpg) 

@Vanessa219

**Comment by MistRay** [comment]
![image](https://user-images.githubusercontent.com/34370155/102451598-bc547380-4073-11eb-9cbc-ee67275c309b.png)
v0.5.4 + macOS Mojave 10.14.6 没有出现这种情况

**Comment by 52511338** [comment]
> 收到，稍后排查，谢谢。
> 
> 
> 
> 来自另一个用户的反馈：![I53`IXBD)CV$7 H9TT1{@)U](https://user-images.githubusercontent.com/873584/102163232-bae54880-3ec5-11eb-8337-343ef94b2406.jpg) 
> 
> 
> 
> @Vanessa219 
> 
> 

刚刚发现是Zoom in到一定程度就出现这个情况，Actual size下是正常的

**Comment by Vanessa219** [comment]
只能离远一点讲究下，原生的点无法缩小
