### ISSUE TITLE
优化嵌入块的反链计数

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7385]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前的嵌入块的反链计数在如下操作场景会出现重叠，不便识别。
![优化嵌入块反链计数](https://user-images.githubusercontent.com/117154557/219318740-cd648dd1-b601-4b05-8def-25727cd99591.gif)
![image](https://user-images.githubusercontent.com/117154557/219318917-18faa1ff-b3e1-4d61-bd13-8ee86ee75c68.png)

### 描述可能的最优解决方案 Describe the optimal solution

将嵌入块的嵌入内容的反链计数移到嵌入块内，这样更方便识别出反链计数是哪个嵌入块的，如下图：
![image](https://user-images.githubusercontent.com/117154557/219320077-80320965-5a5c-491e-876f-a9c9788d3310.png)

类似 logseq 这样：
![image](https://user-images.githubusercontent.com/117154557/219323519-0cba026c-fdf4-47ab-8d30-f3867053c38f.png)

**Comment by 88250** [comment]
放到里面的话会和里面的块引重叠。
