### ISSUE TITLE
Support doc-level `Adaptive Width`

### ISSUE THREAD

**Issue by Cyber-Syntax** [siyuan-note/siyuan#7388]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

In order to see more content on the parent pages we created as Dashboard.

### 描述可能的最优解决方案 Describe the optimal solution

With the full width option in Notion, it can be done differently on each page.

**Comment by 88250** [comment]
This issue is closed for the time being, and we may re-open it for consideration after completing the feature "Attribute View" https://github.com/siyuan-note/siyuan/issues/2829 . 

Thank you for your suggestion.

**Comment by 88250** [comment]
Already been implemented in https://github.com/siyuan-note/siyuan/issues/9107.
