### ISSUE TITLE
去掉代码块预览选项，代码块默认高亮

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#739]
在不开启编辑器设置的代码块预览时，焦点离开代码块编辑以后渲染为高亮预览，而不是现在的代码块文本。

**Comment by MistRay** [comment]
:+1: 是个不错的方案,这样等于变相解决了 #703

**Comment by MistRay** [comment]
不是要改成`在不开启编辑器设置的代码块预览时，焦点离开代码块编辑以后渲染为高亮预览`么,现在直接给开关弄没了...

**Comment by 88250** [comment]
嗯，不要开关了，直接默认预览吧。

**Comment by MistRay** [comment]
我认为还是焦点离开代码块编辑以后渲染为高亮的方式的方式比较好,交互上会比较自然.
现在点击代码块的时候屏幕会跳一下,眼睛的焦点会改变,要重新寻找需要修改的位置(关注点).
这个重新寻找修改位置的过程其实是很耗时的.
我现在都是关闭代码块高亮使用,如果近期没法对编辑器做出优化,建议还是要个开关吧

**Comment by 88250** [comment]
抱歉了，暂时先延后，后面再考虑，谢谢。

**Comment by jiangqizheng** [comment]
编辑代码块时下方跳出的代码块预览，非常影响编辑体验，尤其是笔记内很多代码的时候。如果目前无法快速实现类似typora的默认高亮，那是否能提供一个选项直接关闭代码块？就我而言，宁愿不要高亮...也不希望不断被干扰。

**Comment by 88250** [comment]
> @88250 编辑代码块时下方跳出的代码块预览，非常影响编辑体验，尤其是笔记内很多代码的时候。如果目前无法快速实现类似typora的默认高亮，那是否能提供一个选项直接关闭代码块？就我而言，宁愿不要高亮...也不希望不断被干扰。

收到，请再等待一下，我们目前正在调整编辑器，在 v0.6.0 之前会改进这一点，编辑时下方不进行预览。

**Comment by jiangqizheng** [comment]
@88250 v0.6.0了 😂，依旧没有改进，是被忽略了吗。

**Comment by 88250** [comment]
@jiangqizheng 再将就一下，这块暂时顾及不上了……等后面重新考虑，抱歉了啊……

**Comment by guvmao** [comment]
挠一下
