### ISSUE TITLE
图片标题支持像普通文本一样，直接在页面中编辑修改

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#7390]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当图片标题特别长的时候，在右上角的`[...]`里面编辑，只有一行特别不容易定位和修改

### 描述可能的最优解决方案 Describe the optimal solution

希望可以能直接对图片标题跟文本块一样，所见即所得的编辑修改

### 描述候选的解决方案 Describe the candidate solution

`[...]`里提供多行视图？目前单一行编辑太难受了

**Comment by 88250** [comment]
你好，这个改动工作量较大，目前暂时不考虑了，还是用右键修改吧。

另外，图片标题无法支持换行。
