### ISSUE TITLE
sync data repo failed: lock cloud repo failed

### ISSUE THREAD

**Issue by luke-zhang580** [siyuan-note/siyuan#7393]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

 sync data repo failed: lock cloud repo failed

### 期待的结果 Expected result

同步成功

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/45325652/219636553-00026887-85c1-4990-b583-92c839015fb5.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: linux docker 
- Browser (if used): chrome
```

### 日志文件 Log file

E 2023/02/17 19:09:07 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:09:18 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:09:41 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:12:35 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:13:30 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:13:35 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:13:36 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:13:37 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:13:39 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:14:27 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:14:28 repository.go:1042: sync data repo failed: lock cloud repo failed
E 2023/02/17 19:14:30 repository.go:1042: sync data repo failed: lock cloud repo failed

**Comment by 88250** [comment]
请上传完整的日志，谢谢。

**Comment by 88250** [comment]
看不到完整日志，所以不太确定是不是因为这个导致的：

![image](https://user-images.githubusercontent.com/873584/219675289-2d431a8f-f60f-4e99-b009-6fafb2ada62c.png)

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
