### ISSUE TITLE
改进状态栏显示后台任务执行计数

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7398]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

在 v2.7.4 手动重建索引左下角显示是 `[53/53] 已经建立 [292] 个块级元素的搜索索引`
在 v2.7.5 手动重建索引左下角变成了 `[53/75] 已经建立 [292] 个块级元素的搜索索引`，之后就后卡住不动，直到被下一个执行任务的信息顶掉

复现数据集
[data.zip](https://github.com/siyuan-note/siyuan/files/10773110/data.zip)

### 期待的结果 Expected result

进度条可以跑满，手动重建完成后可以增加显示个【重建索引完毕】

### 版本环境 Version environment

```markdown
- Version: v2.7.5
- Operating System: Windows 11
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
> 手动重建完成后可以增加显示个【重建索引完毕】

这个暂时做不到，后面再考虑吧，我们先改进计数。
