### ISSUE TITLE
支持列表制作闪卡

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7400]
如果将列表或者列表项设置为闪卡，则非子列表会被视问题，子列表会被视作答案。

**Comment by mozhux** [comment]
实际使用中，对于在列表项父项操作快捷键快速制卡，只会把父项视作段落块来生成闪卡，不是把整个这个列表来对应生成，希望能支持在列表中使用快捷键，对应是整个列表，而不是得点那个块标才行。

**Comment by 88250** [comment]
@mozhux 使用 Shift+↑ 扩选

**Comment by mozhux** [comment]
> @mozhux 使用 Shift+↑ 扩选

好吧，这个是个方法，只是对于有2 3个子列表以上的要按的次数有点多，问题不大，多的就还是鼠标吧

**Comment by wslrj123** [comment]
可以兼容列表填空吗，之前我用列表制卡都是父项显示锚信息子项挖空问题填空，现在直接把子项一次性都显示出来了
列表填空的场景如果只制作子项不带入父项的话，对一些比较笼统的问题根本不知道指的是什么，记笔记的时候也不会把父项的信息记到每个子项里去

**Comment by JOYCELEEEEE** [comment]
在没有问答卡之前，一切的卡片都是按照挖空卡的逻辑进行操作。

![Snipaste_2023-02-25_19-29-17](https://user-images.githubusercontent.com/89592448/221359198-06515499-867f-4c4f-8429-ef7765394378.png)

比如上面这张卡片，正常情况下，复习时卡片只遮挡高亮部分。

但是“如果将列表或者列表项设置为闪卡，则非子列表会被视问题，子列表会被视作答案。”，原来的卡片变成了这样：

![Snipaste_2023-02-25_19-28-37](https://user-images.githubusercontent.com/89592448/221359260-0a7aba84-0787-485c-9b35-69e4d9204266.png)

当初对闪卡改进时，D大有考虑过这些会**被**更改的卡片吗？

**Comment by 88250** [comment]
抱歉了，这个恐怕没有办法迁移，只能重新制卡。

**Comment by JOYCELEEEEE** [comment]
上百来张卡片诶，真的没有别的办法了吗（哭


发件人: ***@***.***>
发送时间: 2023年2月25日 21:27
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [siyuan-note/siyuan] 支持列表制作闪卡 (Issue #7400)


抱歉了，这个恐怕没有办法迁移，只能重新制卡。

―

**Comment by 88250** [comment]
应该没有办法了，因为规则首先会应用到列表上。

**Comment by JOYCELEEEEE** [comment]
> 抱歉了，这个恐怕没有办法迁移，只能重新制卡。

还是有一个问题，以上面展示的卡片为例子，我该怎么做才能达到原来挖空卡片的效果？

想了一下，貌似要把我的笔记全部做改动，也就是说，之后我要改变原来做笔记的整套习惯。

**Comment by 88250** [comment]
制卡的时候不要选列表/列表项块，选段落块就可以用标记挖空了。

**Comment by JOYCELEEEEE** [comment]
> 制卡的时候不要选列表/列表项块，选段落块就可以用标记挖空了。

但是我的一张卡的组成貌似是这样的：
![image](https://user-images.githubusercontent.com/89592448/221360344-a39d29e3-dd6c-4ae7-9613-f16f2448c887.png)

这样貌似只能以列表/列表项为单位制卡

**Comment by 88250** [comment]
那只能改块结构了……

**Comment by InEase** [comment]
@JOYCELEEEEE @wslrj123 这次的commit 687e08c通过指定列表下的list`display:none`来实现隐藏子列表，如果想回到之前那种方式，只需要在代码片段里面加上如下css
```css
.b3-dialog__cardblock--hide .li>.list {
    display: block; !important
}
```
即可显示子列表
![image](https://user-images.githubusercontent.com/88016816/221753853-1bb6d2b4-1a0e-457e-869e-b6effe9142b8.png)
不过我建议还是尽快适应新的闪卡机制叭，毕竟这个补丁不是官方支持的，后面可能会引发其他问题

**Comment by Achuan-2** [comment]
@88250 
列表制作闪卡后，如果列表块折叠了，闪卡回顾的时候，显示答案前能否隐藏折叠标记，
<img width="1285" alt="Snipaste_2024-01-18_12-25-35" src="https://github.com/siyuan-note/siyuan/assets/60436214/0f3ee2f5-8824-4827-917a-c3aa17c40d5c">


显示答案后能否自动展开呢
<img width="695" alt="Snipaste_2024-01-18_12-25-17" src="https://github.com/siyuan-note/siyuan/assets/60436214/e365cf75-0a59-445c-a9f7-1bdbe825fa62">

**Comment by 88250** [comment]
@Achuan-2 搞不定，折叠状态是统一的，这里展开的话原文就展开了。
