### ISSUE TITLE
2.7.6-dve3 选中多段拖动，只移动一段

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7401]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

2.7.6-dve3 选中多段拖动，只移动一段

### 期待的结果 Expected result

修正

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by 88250** [comment]
感谢反馈，下次发版修复。
