### ISSUE TITLE
无法连续输入两个\\

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7405]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

默认主题下，我无法连续输入两个\\

### 期待的结果 Expected result

正常应该允许这样的输入， 一些路径信息的正规写法就需要连续\\

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: Win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by AugustTuan** [comment]
当连续输入两个\\时， 第二个\不显示
但是删除，却需要两次删除才能清空

**Comment by AugustTuan** [comment]
我最近还发现了一个如果没有数据快照恢复的话，会很难受的bug。

就是当我有一个很长的列表，列表项都是折叠的。
我是用shift+选中所有折叠的列表项。（其实也不是很长，大概是50个左右的列表项）
然后我点击剪切，结果卡住了，然后就是自动重建索引。

等重建索引后，我的所有列表项第一行都被清除了，折叠在里面的内容全都暴露了出来。（而且无法ctl+z回退了）
还好有数据快照恢复救我狗命，不然我要疯了。🤣

**Comment by lentikr** [comment]
> 当连续输入两个\时， 第二个\不显示 但是删除，却需要两次删除才能清空

因为"\"本身是转义符号，输出两个"\"后第一个"\"作为转义符号，你是无法看见的。
类似的情况例如"\*"会显示为"*"。

不过这里确实发现一个问题，连续输入任意多个"\"只会显示一个"\"

**Comment by 88250** [comment]
输入第二个 `\` 的时候得到第一个 `\` 的左边输入，这个后面我们再看下是否能改进，谢谢。

https://github.com/siyuan-note/siyuan/issues/7405#issuecomment-1435968634 这个问题如果能重现的话麻烦单独开 issue，谢谢。
