### ISSUE TITLE
可否添加这个网站缩略图/预览的功能

### ISSUE THREAD

**Issue by xp12047** [siyuan-note/siyuan#7406]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

平时喜欢收藏网址。最近发现flowus这个"网页书签"的方式很棒  
![Screenshot_20230219_212527_com next space cflow](https://user-images.githubusercontent.com/56335408/219951118-004b9bd9-75ff-401d-ae73-a3356e8a4af3.jpg)
在这个之前都是用md格式记录网站，后来知道了siyuan但2.7.5有问题不好用了。现在还没给修复好。才去试了flowus发现它居然可以生成跟缩略图似的东西。点击还能跳转。  就是在复制了网址，或者/调出书签功能填完后。

### 描述可能的最优解决方案 Describe the optimal solution

知不道。我更想知道有啥办法能在siyuan上实现嘛

**Comment by 88250** [comment]
之前有过提议 https://github.com/siyuan-note/siyuan/issues/1020 但是因为依赖网络，怕不稳定所以先搁置。
