### ISSUE TITLE
停靠栏面板最小宽度改进为根据类型来判断

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#7407]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/60436214/219990167-e3ce8ecc-ec70-46f0-a0b0-e143c0050b13.png)

大纲、反链面板的宽度最小宽度过大，在14屏幕的电脑上编辑器显得很窄。
而且大纲面板在左边面板调整到较小宽度，移动到右边面板，保持原来宽度，一旦宽度调大，就调整不回来的情况

### 期待的结果 Expected result

大纲、反链面板的宽度最小宽度与文档树一致

### 版本环境 Version environment

```markdown
- Version: 2.7.6 dev4
- Operating System: Win11
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
文档树和反链的最小宽度是不一致的，否则会出现横向滚动。目前按照左右面板区分，可改为按照面板类型区分。

**Comment by mozhux** [comment]
大佬可以按 Ctrl+- 缩小一个比例用，挺好的。

**Comment by lllaterOn** [comment]
能否加入一个功能可以人为输入各个左右面板的宽度数值，调整反链面板、关系图、全局关系图面板的宽度全靠鼠标移动到边界上左右拖拽，没法做到让反链面板、关系图面板、全局关系图面板的宽度统一。一是逼死强迫症，二是当我在不同面板间切换时，正中间的笔记宽度会不断变化，比较影响编辑笔记时的连贯性体验。

> 文档树和反链的最小宽度是不一致的，否则会出现横向滚动。目前按照左右面板区分，可改为按照面板类型区分。

**Comment by Achuan-2** [comment]
> 能否加入一个功能可以人为输入各个左右面板的宽度数值，调整反链面板、关系图、全局关系图面板的宽度全靠鼠标移动到边界上左右拖拽，没法做到让反链面板、关系图面板、全局关系图面板的宽度统一。一是逼死强迫症，二是当我在不同面板间切换时，正中间的笔记宽度会不断变化，比较影响编辑笔记时的连贯性体验。
> 
> > 文档树和反链的最小宽度是不一致的，否则会出现横向滚动。目前按照左右面板区分，可改为按照面板类型区分。

每个面板的宽度都不一样这个确实很难受

**Comment by Vanessa219** [comment]
默认值是一样的，强迫症目前可以通过查看这个数值来解决一下
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/970828/220031664-22ad2065-cab3-41db-b0f2-306ca0bfbd1f.png">
