### ISSUE TITLE
ctrl+x时，判断为“块”，移入隐藏块，粘贴时移出至光标，不经剪切板

### ISSUE THREAD

**Issue by MXDMM** [siyuan-note/siyuan#7408]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

剪切粘贴，以创建新的块，导致旧引用失效。

发现时多是事后，如果引用的相关内容非常多，对整个笔记影响极大。

ctrl+x作为系统级的操作，绝大部分人第一意识，肯定是“移动过去”，而非创造一个新的块。

即便已经知道思源笔记的逻辑概念，也会因为日常习惯性操作而造成失误（将一个被很多文档引用的块剪切了一下，导致很多笔记文档出问题）。

### 描述可能的最优解决方案 Describe the optimal solution

ctrl+x时，判断是否为块（内容上拥有思源ID，或有剪切的标志），则作为块移动的操作，将块移动到“隐藏块”中，粘贴时再移动到光标处。

ctrl+x，判断为块时，做一个提示，即使用“软件剪切板”而非系统剪切板，系统剪切板清空（确保只有id不会被重复复制）。

如果是有ID的块粘贴（剪切板内有数据）进来，且“隐藏块”中有数据，二者数据造成冲突，则产生提示。

如不是块的时候，依旧保持系统剪切板的用法。

### 其他信息 Other information

剪切问题，是块ID重复的问题，采用移动的方式，确保块不脱离软件而独立存在（不放置在系统剪切板内），便不会产生重复。

**Comment by 88250** [comment]
和这个思路类似的方案之前已经在 https://github.com/siyuan-note/siyuan/issues/6807 中讨论过，需要先解决跨文档撤销，否则会导致 ID 重复。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
