### ISSUE TITLE
一键导出工作空间设置的配置数据

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7409]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前各个工作空间的设置是不通用的，需要一个空间一个空间的进行配置，所以希望能支持一键导出某个空间的设置数据，然后将其导入到另一个空间的设置中。

### 描述可能的最优解决方案 Describe the optimal solution

一键导出工作空间设置的配置数据

**Comment by 88250** [comment]
这个暂时不考虑了，移动端使用桌面端的配置会有问题，另外一些本地路径跨平台以后也有问题，目前没有可行的解决方案。
