### ISSUE TITLE
优化表格的显示，支持对于超宽表格添加横向滚动条

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#7413]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前思源笔记内置的表格，在列数比较多或者列比较宽等情况下，会把所有列的宽度强行压缩显示，导致单元格被迫换行显示，看起来十分丑陋且不便。

下面两张图展示了超宽表格被迫压缩宽度以适应屏幕的显示区域。 
![image](https://user-images.githubusercontent.com/27268127/220011862-f5a50f43-e179-4759-8ac4-3132afdd0308.png)
![image](https://user-images.githubusercontent.com/27268127/220012074-4d8f8e29-c93a-421e-a598-01fdc5441ace.png)

### 描述可能的最优解决方案 Describe the optimal solution

为超宽表格添加横向的滚动条，类似 Notion 等一系列笔记软件的展示样式。

示例：FlowUs 的宽表格显示。
![FlowUS示例](https://user-images.githubusercontent.com/27268127/220012646-e380b77a-c0a7-4e3c-b8a4-e61a3b26428c.png)

**Comment by 88250** [comment]
默认主题应该会显示横向滚动条的吧。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
