### ISSUE TITLE
导出 PDF 时支持将资源文件作为附件嵌入

### ISSUE THREAD

**Issue by vagaruy** [siyuan-note/siyuan#7414]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

I work as a software engineer and write a lot of root cause analysis reports. I use siyuan to manage my analysis and it contains a lot of log files and other binary resources. 

Currently when I export a pdf , these assets are exported in a separate directory but it makes it very hard to distribute the files. 

### 描述可能的最优解决方案 Describe the optimal solution

It would be great if the PDF export had an option to embed the local assets in the PDF file itself instead of exporting them in a separate directory. It can appear as a icon inside the pdf itself that anyone can open it if needed. 

### 描述候选的解决方案 Describe the candidate solution

1. Add option during Export PDF to specify the following 
Embed Assets (Yes/No) 
2. Generated pdf has the assets embedded inside.

**Comment by 88250** [comment]
Hello, this is a good idea.

I just did some experimentation and found a solution to add assets as attachments to the PDF, but I can't hyperlink the original asset to the attachment.

![image](https://user-images.githubusercontent.com/873584/220042726-444c25f6-6daf-4b08-bbc9-0f2f36b1888e.png)

**Comment by 88250** [comment]
You're right, but currently we haven't figured out how to point a hyperlink in a PDF to a local file.

**Comment by vagaruy** [comment]
For the external assets at least, I tested with a different pdf generator and the following links resolve correctly `file:///home/vagaruy/Desktop/assets/test_file` . I haven't been able to test with embedded attachments yet however.

**Comment by 88250** [comment]
Can you help to test whether a relative path can be generated?

**Comment by 88250** [comment]
After some exploration, we have found a technical solution to change the asset of the http://127.0.0.1 server to a local relative path and link it to the assets folder.

For example, when placing pdf and assets on the desktop:

![image](https://user-images.githubusercontent.com/873584/220508332-367d4604-bbbd-44ac-beeb-fc94c50c6d8a.png)

When we move the pdf and its assets, the relative path still works fine:

![image](https://user-images.githubusercontent.com/873584/220508472-e298bbd1-df3f-4d96-ac21-a4290e52f9a8.png)

**Comment by 88250** [comment]
Finally, we found a way to jump to embedded attachments, and unified improvement in this issue, thank you.

**Comment by vagaruy** [comment]
thank you for the great work on this.

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/220634888-a02b7bc2-aa0f-4dc4-b0ab-16488649bee6.png)

The previous hyperlink cannot be clicked, you need to double-click the attachment annotation to open the attachment.

**Comment by vagaruy** [comment]
I tested the pre-release **siyuan-v202302231520-linux.AppImagewith** the fix but there seems to be some problem with the embedding. The links still point to http:// and the files are not embedded either. 
Attached a screenshot of the incorrect link. 
![cropped_image](https://user-images.githubusercontent.com/3887130/220935067-c6b14604-97fa-4faa-962b-d28601e067ee.png)

**Comment by 88250** [comment]
Thanks for testing, we will fix it later.

**Comment by vagaruy** [comment]
Hello . I recently tried testing this on 2.10.2 and the embedding asset don't seem to be working anymore.

**Comment by 88250** [comment]
@vagaruy It will be fixed in the next version, thanks for the feedback.
