### ISSUE TITLE
加宽隐藏边栏后的面板展开触发区域

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7415]
感觉可以略微加宽一下隐藏边栏后的展开触发区域，现在的有些过窄，鼠标很容易就移到界面以外了

_Originally posted by @Temacc0531 in https://github.com/siyuan-note/siyuan/issues/7375#issuecomment-1436314641_

**Comment by 88250** [comment]
我觉得还是只有停靠栏宽度触发比较好，太宽的话容易误触发。

**Comment by 88250** [comment]
如果加宽的话，分屏以后这块区域很容易误触发：

![image](https://user-images.githubusercontent.com/873584/220029426-57f38e41-47d1-4449-809b-e40026af4194.png)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Temacc0531** [comment]
> 我觉得还是只有停靠栏宽度触发比较好，太宽的话容易误触发。

是的，现在停靠栏显示时是按照停靠栏宽度触发的，这个没有问题。但是隐藏停靠栏后触发区域就会变得很窄，可以改成也按照未隐藏停靠栏时的触发宽度
![GIF 23-2-20 14-35-10](https://user-images.githubusercontent.com/101307399/220030896-857363d1-3dae-4f86-b691-35be97d3df29.gif)

**Comment by 88250** [comment]
这里要留足块标的宽度，否则点不到块标：

![image](https://user-images.githubusercontent.com/873584/220032569-920f2be8-7412-4f15-bc3a-b4fd1dbd8b0f.png)

**Comment by Temacc0531** [comment]
居然还有这种排版我倒是没想到😂
但我看这个排版只有在使用最窄窗口时才会出现，宽一些的排版应该没有这个问题，也许可以这种特殊情况单独按现有窄触发区域，其余的加宽一些，倒也不用加到和原停靠栏那么宽

**Comment by 88250** [comment]
现在无法判断这些情况，左边和右边都可能会误触发的。

**Comment by Temacc0531** [comment]
那就暂时先这样吧😶
