### ISSUE TITLE
搜索结果条目区禁用复制

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#7416]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

在搜索框里复制会把搜索结果的高亮也复制出来

### 期待的结果 Expected result

只复制原文格式，不会复制搜索结果高亮

### 截屏或者录屏演示 Screenshot or screen recording presentation

![GIF 23-2-20 15-08-33](https://user-images.githubusercontent.com/101307399/220036830-b633159a-70a7-4b5d-b3a7-aa51d041cc36.gif)

### 版本环境 Version environment

```markdown
- Version: v2.7.5
- Operating System: Windows 10
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
这个地方应该是不支持复制的，我们把这个 issue 改为禁用复制你觉得如何？

**Comment by Temacc0531** [comment]
直接禁用了可能对用户不大友好。上面我写的预期是复制原文格式，重新想了下也许应该是复制纯文本

**Comment by 88250** [comment]
一般搜索的结果条目是不允许复制的，因为复制可以在下面的预览编辑区复制，这里也可以支持多种格式。

**Comment by 88250** [comment]
我们还是改为禁用复制吧。

**Comment by aptexd** [comment]
啊哈哈哈哈哈，本想反馈了一下的，结果把特性给整没了🤣
