### ISSUE TITLE
新款M2pro无法运行siyuan

### ISSUE THREAD

**Issue by zhang192073** [siyuan-note/siyuan#7418]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

(base) penguin@PenguindeMacBook-Pro ~ % /Applications/SiYuan.app/Contents/MacOS/SiYuan ; exit;
got kernel port [57321]
ui version [2.7.5], booting kernel [/Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 57321 --wd /Applications/SiYuan.app/Contents/Resources]
booted kernel process [pid=26273, port=57321]
checking kernel version
kernel [pid=26273] exited with code [1]

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

### 期待的结果 Expected result

运行起来

### 截屏或者录屏演示 Screenshot or screen recording presentation

![Uploading 图片.png…]()

![Uploading 图片.png…]()

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: mac os
- Browser (if used): firefox
```

### 日志文件 Log file

123

**Comment by 88250** [comment]
你下载的安装包是 arm64 那个吗？请打包上传工作空间/temp/siyuan.log

**Comment by zhang192073** [comment]
我的下载链接为 https://release.b3log.org/siyuan/siyuan-2.7.5-mac-arm64.dmg    log文件我并没有发现，因为我以前是windows用户想迁移到macos 程序可以正常安装，我只在 .config 下看到了
![image](https://user-images.githubusercontent.com/47629854/220221421-392becbf-6e06-472c-b2e4-ad62eaab81ff.png)

2023-02-20 08:08:27 booted kernel process [pid=26273, port=57321]
2023-02-20 08:08:27 checking kernel version
2023-02-20 08:08:28 kernel [pid=26273] exited with code [1]
2023-02-21 00:48:55 got kernel port [64908]
2023-02-21 00:48:55 ui version [2.7.5], booting kernel [/Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 64908 --wd /Applications/SiYuan.app/Contents/Resources]
2023-02-21 00:48:55 booted kernel process [pid=49639, port=64908]
2023-02-21 00:48:55 checking kernel version
2023-02-21 00:48:56 kernel [pid=49639] exited with code [1]
2023-02-21 00:52:46 got kernel port [65091]
2023-02-21 00:52:46 ui version [2.7.5], booting kernel [/Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 65091 --wd /Applications/SiYuan.app/Contents/Resources]
2023-02-21 00:52:46 booted kernel process [pid=49896, port=65091]
2023-02-21 00:52:46 checking kernel version
2023-02-21 00:52:47 kernel [pid=49896] exited with code [1]

**Comment by 88250** [comment]
试一下在命令行中直接执行这一句：

```
/Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 64908 --wd /Applications/SiYuan.app/Contents/Resources
```

**Comment by zhang192073** [comment]
提示了权限不足
(base) penguin@PenguindeMacBook-Pro siyuan % /Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 64908 --wd /Applications/SiYuan.app/Contents/Resources

2023/02/21 09:06:07 create os tmp dir [/System/temp/os] failed: mkdir /System/temp: operation not permitted

然后我sudo了一下
(base) penguin@PenguindeMacBook-Pro siyuan % sudo /Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 64908 --wd /Applications/SiYuan.app/Contents/Resources
Password:
I 2023/02/21 09:06:45 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/02/21 09:06:45 runtime.go:57: kernel is booting:
    * ver [2.7.5]
    * arch [arm64]
    * os [darwin 13.2.1]
    * pid [50745]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/var/root/Documents/SiYuan]
I 2023/02/21 09:06:45 conf.go:121: initialized language [zh_CN] based on device locale
I 2023/02/21 09:06:45 runtime.go:103: use network proxy [system]
I 2023/02/21 09:06:45 serve.go:108: kernel [pid=50745] http server [127.0.0.1:64908] is booting
I 2023/02/21 09:06:45 database.go:87: the database structure is changed, rebuilding database...
I 2023/02/21 09:06:45 database.go:107: reinitialized database [/var/root/Documents/SiYuan/temp/siyuan.db]
I 2023/02/21 09:06:45 conf.go:623: database size [4.1 kB], tree/block count [0/0]
I 2023/02/21 09:06:45 working.go:157: kernel booted
I 2023/02/21 09:06:45 box.go:75: auto stat [trees=0, blocks=0, dataSize=29 kB, assetsSize=0 B]
I 2023/02/21 09:06:45 disk.go:33: disk usage [total=995 GB, used=141 GB, free=854 GB]
I 2023/02/21 09:06:46 serve.go:121: reverse proxy server [127.0.0.1:6806] is booting
I 2023/02/21 09:06:50 working.go:419: initialized built-in pandoc [ver=2.19.2, bin=/var/root/Documents/SiYuan/temp/pandoc/bin/pandoc]

**Comment by zhang192073** [comment]
(base) penguin@PenguindeMacBook-Pro siyuan % cat app.log 

2023-02-21 01:09:27 got kernel port [49666]
2023-02-21 01:09:27 ui version [2.7.5], booting kernel [/Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 49666 --wd /Applications/SiYuan.app/Contents/Resources]
2023-02-21 01:09:27 booted kernel process [pid=50917, port=49666]
2023-02-21 01:09:27 checking kernel version
2023-02-21 01:09:27 kernel [pid=50917] exited with code [1]
(base) penguin@PenguindeMacBook-Pro siyuan % sudo /Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 49666 --wd /Applications/SiYuan.app/Contents/Resources
E 2023/02/21 09:10:01 working.go:483: lock workspace [/var/root/Documents/SiYuan] failed
(base) penguin@PenguindeMacBook-Pro siyuan %

**Comment by zhang192073** [comment]
![image](https://user-images.githubusercontent.com/47629854/220223500-08160c79-39bc-41c6-aa5a-f86b6a1c8cd4.png)
是权限的问题，软件启动的时候会在 /System/ 下建立 /tmp /os 等文件夹，但是普通是没权限的。我sudo 执行后。可以正常访问web端，但是软件页面还是打不开
、sudo /Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 50223 --wd /Applications/SiYuan.app/Contents/Resources

**Comment by zhang192073** [comment]
(base) penguin@PenguindeMacBook-Pro /System % ls
Applications	Developer	Library		iOSSupport
Cryptexes	DriverKit	Volumes
(base) penguin@PenguindeMacBook-Pro /System % /Applications/SiYuan.app/Contents/Resources/kernel/SiYuan-Kernel --port 50223 --wd /Applications/SiYuan.app/Contents/Resources
2023/02/21 09:15:05 create os tmp dir [/System/temp/os] failed: mkdir /System/temp: operation not permitted

**Comment by 88250** [comment]
看下这个命令返回值：

```
echo ~
```

**Comment by zhang192073** [comment]
![image](https://user-images.githubusercontent.com/47629854/220224686-79215c83-2cf5-4eee-9947-d3d557a403d2.png)

**Comment by 88250** [comment]
感觉不大对劲哦，你这个是 root 用户？

**Comment by zhang192073** [comment]
不是呀，这个是普通用户
![image](https://user-images.githubusercontent.com/47629854/220224922-bc9cf00f-fc84-49fb-8826-3ae46b0abb34.png)


(base) penguin@PenguindeMacBook-Pro /System % echo ~
/Users/penguin
(base) penguin@PenguindeMacBook-Pro /System % sudo -i
Password:
Sorry, try again.
Password:
PenguindeMacBook-Pro:~ root# whoami
root
PenguindeMacBook-Pro:~ root# exit
logout
(base) penguin@PenguindeMacBook-Pro /System % whaomi
zsh: command not found: whaomi
(base) penguin@PenguindeMacBook-Pro /System % whoami
penguin
(base) penguin@PenguindeMacBook-Pro /System %

**Comment by 88250** [comment]
但是你这个用户返回的用户家目录 `~` 为啥是 root 的？

**Comment by zhang192073** [comment]
![image](https://user-images.githubusercontent.com/47629854/220225357-634bbd4c-d39e-4d99-bbce-1f8266b62765.png)

**Comment by 88250** [comment]
启动日志里面：

```
* workspace directory [/var/root/Documents/SiYuan]
```

默认创建的工作空间是在 /root/ 下面。

**Comment by 88250** [comment]
也就是说内核启动应该是没问题的，只要有适当的权限。

**Comment by zhang192073** [comment]
penguin 用户启动的应该是在 penguin doc目录下

![image](https://user-images.githubusercontent.com/47629854/220225728-c3420a48-69bf-4fd7-b409-2c97ee7b90cf.png)

但是当前目录没任何文件

**Comment by zhang192073** [comment]
刚刚我看了下朋友的他的是2.0.18版本 /System 不可写，但是可以正常使用，他是M1 我在用M1尝试升级到最新版本使用

**Comment by 88250** [comment]
你在普通用户下执行这个看看：

```
echo $HOME
```

还有这个：

```
eval echo ~$USER
```

**Comment by zhang192073** [comment]
(base) penguin@PenguindeMacBook-Pro SiYuan % echo $HOME
/Users/penguin
(base) penguin@PenguindeMacBook-Pro SiYuan % 
(base) penguin@PenguindeMacBook-Pro SiYuan % eval echo ~$USER
/Users/penguin
(base) penguin@PenguindeMacBook-Pro SiYuan %

**Comment by 88250** [comment]
删一下 /Users/penguin/.config/siyuan/

**Comment by zhang192073** [comment]
![image](https://user-images.githubusercontent.com/47629854/220226999-2edc45d7-45ee-4d12-bc13-46935f328d39.png)

**Comment by 88250** [comment]
之前这个用户的配置文件里面用的是没有权限的目录。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by zhang192073** [comment]
谢谢帮忙解决  辛苦
