### ISSUE TITLE
是否有markdown 编辑模式和实时预览模式？

### ISSUE THREAD

**Issue by ma123456mai** [siyuan-note/siyuan#7419]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

建议出一版  markdown 编辑模式和实时预览模式？例：左markdown 实时预览模式  右markdown编辑模式（显示代码）

### 描述可能的最优解决方案 Describe the optimal solution

建议出一版  markdown 编辑模式和实时预览模式？例：左markdown 实时预览模式  右markdown编辑模式（显示代码）

### 描述候选的解决方案 Describe the candidate solution

建议出一版  markdown 编辑模式和实时预览模式？例：左markdown 实时预览模式  右markdown编辑模式（显示代码）

**Comment by 88250** [comment]
这个不考虑了，因为思源不是 Markdown 编辑器哦。
