### ISSUE TITLE
文档消失，源文件在 history 中发现

### ISSUE THREAD

**Issue by mingyuezhaowo** [siyuan-note/siyuan#7420]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

现象 1：
在已有文档的基础上 --- 简称 A 文档，更新文档内容 --- 简称 A-update；
第二天（隔了周末，且似乎思源自动更新了）打开思源，ctrl +f 寻找昨天编辑的文件，发现路径变成了 xxx/Untitled/Untitled/Untitled/xxx, 打开文档后，点击左侧定位文档位置，无法成功定位；
手动找到文档位置，发现打开的是 A 文档，也就是 A 和 A-update 共存。
点击重建索引，再次 ctrl +f 找不到 A-update。
在本地文件夹中 grep，发现 A-update 实际路径为：
.siyuan/history/2022-03-24-101756-update/20230220104043-3tvwv9r/20210804103358-wt2o9vx.sy

退出思源，重新打开，ctrl +f 可以搜索到  A-update，路径仍然为  xxx/Untitled/Untitled/Untitled/xxx。
且，在数据历史中无法找到 A-update 的修改历史。

现象 2：
出现很多 Untitled 父文件夹名称，并且文档结构似乎有变化，也就是子文件理应在已命名的文件夹下 --- 由于时间久，这个无法确认。

### 期待的结果 Expected result

文档不消失。
虽然文档都在本地留存，但是毕竟由于结构问题很难检索，如果笔记中的文件缺失不能展示，除了使用频次很高的文档，很难发觉到。
近几月还发现了另一个数据丢失的问题，笔记本展示的数据有缺失，但本地源文件中是完整的，最后通过手动恢复了，暂未复现。

现在担心会不会丢了更多的文档...

数据宝贵，希望思源可以再稳健一点。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![思源反馈](https://user-images.githubusercontent.com/17918944/220078876-401ff69e-bc09-472a-93dc-c16f59d00308.PNG)
![思源反馈2](https://user-images.githubusercontent.com/17918944/220078892-531cb2dc-d5fa-48a4-b0f6-8a591fa4e55d.PNG)

操作时间是在 2.17 日，但是自 14 日开始，就没有数据历史了。
![思源反馈3](https://user-images.githubusercontent.com/17918944/220079182-b6d7dec1-eb90-47ec-a774-007a8566d67f.PNG)

### 版本环境 Version environment

```markdown
- Version:  v2.7.5 （play store 版本）
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10783378/siyuan.log)

操作较多，可以取头尾部分的 log。

**Comment by 88250** [comment]
感谢反馈，这个问题是 v2.7.5 校验索引的 bug，我们已经定位到，下个版本进行修复，给你带来不便请多包涵。

关联 https://github.com/siyuan-note/siyuan/issues/7394
