### ISSUE TITLE
更改父文档标题或者移动父文档后使用状态栏推送子文档移动进度

### ISSUE THREAD

**Issue by jingjue** [siyuan-note/siyuan#7422]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

对于子文档较多的母文档，更改母文档的标题时会触发“正在移动文档”提示及其特效。
每当输入法输入一次后都会触发此提示，但是我此时标题没有更改完，就很影响观感。
![image](https://user-images.githubusercontent.com/71930132/220146487-1a833567-a50e-4184-b296-ea6ea3b4d0c4.png)

### 描述可能的最优解决方案 Describe the optimal solution

建议在标题更改完成后等待一段时间再触发移动文档提示

### 描述候选的解决方案 Describe the candidate solution

或者标题更改完后不提示或放在底端提示。
![image](https://user-images.githubusercontent.com/71930132/220146670-0f053512-813c-4c6e-bf6e-5ab83540195f.png)

**Comment by 88250** [comment]
同时会在这个 issue 中改进移动父文档后索引的性能。
