### ISSUE TITLE
快速制卡问题，闪卡问题

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#7423]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

1. 快速制卡的卡在哪儿？卡包里看不到
2. 无卡时无法预览，卡刷完就没有预览图标了
3. 快速制卡的卡片无法删除

https://user-images.githubusercontent.com/32903588/220155782-3d5a0452-f72f-499f-a118-200b16c6ade6.mp4

### 期待的结果 Expected result

改进修复

### 版本环境 Version environment

```markdown
- Version: 2.7.6-dev5
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
快速制卡后的闪卡在内置的卡包中，内置卡包无法查看，这是设计如此，使用快速制卡时用户不必关注卡包。如果要移除的话，可以在复习时的预览界面中移除。

**Comment by TinkMingKing** [comment]
> 快速制卡后的闪卡在内置的卡包中，内置卡包无法查看，这是设计如此，使用快速制卡时用户不必关注卡包。如果要移除的话，可以在复习时的预览界面中移除。
@88250 视频中我有尝试在预览界面中移除快速制卡的卡片，但是失败了，并且如果最近没有需要复习的卡片，无法预览卡片，这时候要编辑就很麻烦，请仔细查看视频

**Comment by 88250** [comment]
All 中目前无法移除，你试下在文档树闪卡复习界面中移除。
