### ISSUE TITLE
Duplication of renamed image assets

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#7424]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

* Pasting an image from clipboard or loading it from local storage into a block and 
* renaming the image afterwards
  * creates duplicate image asset files
  * one file with the old filename and one file with the renamed filename will be found if you use `/asset` action for locating the file (see my bad screen recording below).

![image](https://user-images.githubusercontent.com/13854802/220162676-e3c52267-b8bb-4401-b1e3-cee9cf05a2aa.png)

I run into this issue as my main screenshot tool "Greenshot" is storing the screenshot taken into clipboard as "image.png" filename. Now with pasting a lot of screenshots I eventually ended up with a long list of "image.png" assets. To locate the required assets more easier I started renaming them inside SiYuan and run into this problem.

### 期待的结果 Expected result

The former filename (and physical file) will no longer exists in `/asset` output and in `assets` physical folder.
The former file had been renamed and will show up in assets list and physical folder.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![screenshots](https://user-images.githubusercontent.com/13854802/220160334-c0aa2de4-05e1-495e-8f1b-c2d790f69ecf.gif)

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: Windows 10
- Browser (if used): None
```

### 日志文件 Log file

```plain
I 2023/02/20 17:20:32 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.08s], tree [count=51, size=964 kB]
I 2023/02/20 17:20:33 index.go:205: resolved refs [51] in [467ms]
W 2023/02/20 17:20:38 blocktree.go:436: save block tree [size=1.2 MB] to [C:\Users\HBE\Documents\siyuan\temp\blocktree], elapsed [3.21s]
E 2023/02/20 17:24:41 assets.go:497: copy asset [assets/old_filename-20230220172429-3kdupaj.png] failed: file does not exist
E 2023/02/20 17:24:46 assets.go:497: copy asset [assets/old_filename-20230220172429-3kdupaj.png] failed: file does not exist
E 2023/02/20 17:24:49 assets.go:497: copy asset [assets/old_filename-20230220172429-3kdupaj.png] failed: file does not exist
E 2023/02/20 17:24:50 assets.go:497: copy asset [assets/old_filename-20230220172429-3kdupaj.png] failed: file does not exist
E 2023/02/20 17:25:12 assets.go:497: copy asset [assets/old_filename-20230220172429-3kdupaj.png] failed: file does not exist
E 2023/02/20 17:25:20 assets.go:497: copy asset [assets/old_filename-20230220172429-3kdupaj.png] failed: file does not exist
```

### 更多信息 More information

If I look at kernel https://github.com/siyuan-note/siyuan/blob/06b7dfd1e24ce9802e365fac448e0b69f665cdf8/kernel/model/assets.go#L476 you are doing a copy of the old image asset into the new filename and replacing all links within the notebook tree with that updated asset filename. However I think some `os.Remove()` of the old file is possibly missing here causing the duplication of old and new filename.

**Comment by 88250** [comment]
Hello, this is designed so that a new asset will be copied after the asset is renamed, and the old asset will still be retained.

If you don't need it, you can clean it up in Settings - Assets, thanks.
