### ISSUE TITLE
支持在 All 卡包中移除闪卡

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7425]
All 中预览显示的闪卡会根据块 ID 去重（同一个块被加入多个卡包后只会在 All 中显示一次），如果从 All 中移除的话将在所有卡包中移除。

**Comment by zxhd863943427** [comment]
能问一下“从 All 中移除的话将在所有卡包中移除”这个是怎么操作吗？
我在[v202302261200](https://github.com/siyuan-note/siyuan/releases/tag/v2.7.7-dev3)版本进行测试，使用快捷键 ctrl+alt+f 能移除只是快捷制卡的卡片，但是无法移除被加入卡包的卡片。

**Comment by 88250** [comment]
在 All 中的预览界面移除。

**Comment by zxhd863943427** [comment]
在最新版中，从文档树进入的卡片管理界面移除卡片，卡片并不会从所有卡包移除。

**Comment by 88250** [comment]
> 在最新版中，从文档树进入的卡片管理界面移除卡片，卡片并不会从所有卡包移除。

我这里无法重现问题。是不是因为你重复制卡了，比如将一个块使用快速制卡，再使用添加到卡包，这个时候会有两张卡。从文档树右键闪卡管理，删除的只是快速制卡那张。

> 而且添加到正常卡包的卡片不能在文档树进入的间隔复习界面见到。
>
> 必须使用alt+0才能见到。

这个是设计如此，文档树右键闪卡是快速制卡相关的，这个用户指南里面有介绍。

**Comment by zxhd863943427** [comment]
emmm，那我理解了。我原本的理解是，all卡包是真的all卡包，所有卡片，无论是快速制卡还是手动添加到卡包里，都会生成一个备份在all卡包里，所以可以通过all卡包来管理所有卡片。
这样子，在all卡包里移除卡片，是能做到在所有的、包括自定义的卡包里同步把卡片移除了。

所以，目前的实现是all卡包是单独用于快速制卡的卡包？那建议修改一下描述，改为
“如果从 All 中移除的话将在 All 卡包中移除。”

**Comment by zxhd863943427** [comment]
话说能实现为这个样子吗？这样感觉文档树的卡片与普通的自定义卡包卡片割裂程度太大了。

**Comment by 88250** [comment]
All 是个逻辑上的卡包，它汇总了所有闪卡。

**Comment by zxhd863943427** [comment]
我尝试了一下，大概理解了，文档树卡片实际上不算在all卡包里，而是在一个默认卡包里，从总的管理界面进入，能够查看并移除all的卡片，从文档树的管理界面进入，只能查看并移除默认卡包的内容。

**Comment by 88250** [comment]
> 文档树卡片实际上不算在all卡包里

算入的。

**Comment by zxhd863943427** [comment]
我明白是算入的，只是不是那种只存在于抽象的all卡包的感觉，而是有一个独立的卡包来管理，最后在归纳进all卡包里。

**Comment by 88250** [comment]
对，快速制卡的卡片在内置卡包中，卡包列表看不到，但是算入 All。
