### ISSUE TITLE
导出为HTML的增强建议

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#7427]
### 背景
我整理了几篇资料，在文档块下，层级比较复杂，想要分享给朋友阅读。兼容性最好，开箱即用的是HTML格式

### 问题
只有加了双链的会被关联导出，**且在同一个页面**实际需求是该文档块下的所有文档块都被导出，即相当于是文件夹下的所有文件都导出，但是当前无法做到，因此无法批量便捷分享

### 描述可能的最优解决方案 Describe the optimal solution

1. 指定文档块下的所有文档块全部导出，即文件夹下的所有文件全部导出
2. 生成**主页**（父文档块）和**子页面**（子文档块）
3. - 主页右侧加上导航栏，可以看到文件层级并能够查看子页面内容，如此就实现了文档块下所有内容地分享（最佳）
    - 或者是主页只作导航，可以跳转到其他子页面

**总体感觉就像是一个网页版的CHM**，又或者，干脆**支持导出为CHM文件**，可能会是一种更简单可靠的方法？

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
只有 Markdown 格式支持批量导出，其他格式不考虑了，谢谢。

**Comment by Soltus** [comment]
关联：https://github.com/Hi-Windom/Sillot/issues/16

**Comment by HowcanoeWang** [comment]
> 主页右侧加上导航栏，可以看到文件层级并能够查看子页面内容

可以在右侧加上目录导航吗，这样分享的时候查看会更方便一点

![图片](https://github.com/siyuan-note/siyuan/assets/19968935/a9bf2444-f51b-4f4b-9749-ec042e2e6640)
