### ISSUE TITLE
导出空文档 Word 和 PDF 时合并子文档失败

### ISSUE THREAD

**Issue by nyaachen** [siyuan-note/siyuan#7429]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

导出下面有子文档的空文档时提示导出成功但实际上没有导出结果。
在正文里面写一个1就能正常导出，并且导出结果中包含子文档内容。

### 期待的结果 Expected result

预期：即使是只有标题的空文档，当下面有子文档的时候，导出结果应该也是有一个文档标题。

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

1
[siyuan.log](https://github.com/siyuan-note/siyuan/files/10790295/siyuan.log)

**Comment by nyaachen** [comment]
2.7.6 复现
文档树：
![image](https://user-images.githubusercontent.com/16128355/220849108-dd9e3357-c680-4d6c-86e0-85f63cc31ac1.png)
根文件
![image](https://user-images.githubusercontent.com/16128355/220849182-4305284f-bc53-4989-aeaa-d00675072e52.png)
导出为word格式
![image](https://user-images.githubusercontent.com/16128355/220849301-f89552d3-a2d0-4e92-900c-3e7b355ba8be.png)
提示导出成功
![image](https://user-images.githubusercontent.com/16128355/220849368-0692fa9c-b3ff-4c78-a768-5d0895f95a4b.png)
实际无导出文件
![image](https://user-images.githubusercontent.com/16128355/220849468-0a958592-3800-400c-8989-cb69f996dd25.png)

在根文件里面写一个1，然后正常导出
![image](https://user-images.githubusercontent.com/16128355/220849774-21853863-1840-40e8-ad0a-d28ad41cd631.png)

**Comment by 88250** [comment]
我之前以为你说的是导出 Markdown。刚刚测试了下，导出 Word 确实有这个问题，下个版本修复。
