### ISSUE TITLE
文件夹/大纲，双击时有时候不会折叠/收起，需要鼠标移动一下再双击才行

### ISSUE THREAD

**Issue by LiWenGu** [siyuan-note/siyuan#743]
### 描述问题 Describe the problem

文件夹/大纲，双击时有时候不会折叠/收起，需要鼠标移动一下再双击才行。
### 期待的结果 Expected result

希望灵敏点

### 截屏或录像 Screenshot or video

https://markdownnoteimages.oss-cn-hangzhou.aliyuncs.com/QQ20201215-180522-HD.mp4

### 版本环境 Version environment

* 版本 Version：0.53
* 操作系统 Operating system：Mac
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
请问这个问题最近的版本还能重现么？

**Comment by 88250** [comment]
我关闭了，如果还有问题麻烦继续跟帖，谢谢。
