### ISSUE TITLE
建议将“钉住”修改成“悬浮”，以便更好理解功能

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7432]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![mmexport1676964681635](https://user-images.githubusercontent.com/117154557/220278791-5d5268fb-7577-4b99-b0ca-36a157556920.png)
建议将上图的“钉住、取消钉住”修改为“悬浮上侧面板、悬浮下侧面板、悬浮左侧面板、悬浮右侧面板”，在未点击“悬浮XX面板”时，字体是黑色的，点击之后字体变为蓝色的即可，内容就不要变了。这样配合图标一眼就明白了，而且操作起来也不晕。

现在的钉住、取消钉住来回变的，晕迷糊了。

### 描述可能的最优解决方案 Describe the optimal solution

将“钉住”修改成“悬浮”，以便更好理解功能。

**Comment by heimi98** [comment]
+1，我对“钉住”的理解正好和目前的表现相反。

**Comment by GH-W94** [comment]
> +1，我对“钉住”的理解正好和目前的表现相反。

是的，一样

**Comment by 88250** [comment]
这个暂时不调整了，感谢反馈。
