### ISSUE TITLE
编辑器浮动工具栏最多显示一个

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7433]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

双开文档，A文档选择文字，出现弹出菜单，点击B文档后，A文档的选择文字丢失焦点，但弹出菜单依然存在
![image](https://user-images.githubusercontent.com/104658457/220281804-2ddbba8b-6a21-456d-8b81-1593837258d1.png)

### 描述可能的最优解决方案 Describe the optimal solution

望修改

**Comment by pisceswb** [comment]
![1](https://user-images.githubusercontent.com/104658457/220353074-d5c6bd3b-842a-4a06-9075-35f5db2949bf.gif)

**Comment by pisceswb** [comment]
![无标题视频——使用Clipchamp制作](https://user-images.githubusercontent.com/104658457/220354150-299aeeac-38ce-4339-a9e3-7b4ca03bf194.gif)
这个感觉也不是很方便

**Comment by pisceswb** [comment]
希望D大V大能优化一下，谢谢！

**Comment by pisceswb** [comment]
![无标题视频——使用Clipchamp制作 (3)](https://user-images.githubusercontent.com/104658457/220378095-31b41d68-2b94-4177-8bc7-0bde509d1ad4.gif)
再反馈一个小问题，如果选择文本时误触发了悬浮边栏，容易导致选中内容错误

**Comment by pisceswb** [comment]
请问是否能设置成，鼠标按下左键状态时，移动到边栏不触发悬浮菜单，这样能够减少选择段落时的误触，谢谢！

**Comment by Vanessa219** [comment]
> ![无标题视频——使用Clipchamp制作](https://user-images.githubusercontent.com/104658457/220354150-299aeeac-38ce-4339-a9e3-7b4ca03bf194.gif) [ ![无标题视频——使用Clipchamp制作](https://user-images.githubusercontent.com/104658457/220354150-299aeeac-38ce-4339-a9e3-7b4ca03bf194.gif) ](https://user-images.githubusercontent.com/104658457/220354150-299aeeac-38ce-4339-a9e3-7b4ca03bf194.gif) [ ](https://user-images.githubusercontent.com/104658457/220354150-299aeeac-38ce-4339-a9e3-7b4ca03bf194.gif) 这个感觉也不是很方便

这个没太明白要表达的意思，文本是不可以进行拖拽的。

**Comment by pisceswb** [comment]
> 这个没太明白要表达的意思，文本是不可以进行拖拽的。

V姐，这个我没有说清楚。感觉思源笔记和另一个窗口双开时，鼠标在窗口间移动会触发浮动面板的显示，遮挡思源笔记正文内容。建议鼠标移出浮动面板后（例如鼠标进入了另一个窗口），能够自动关闭浮动面板。谢谢！

**Comment by pisceswb** [comment]
如果能设计成，鼠标从思源内部经过停靠栏移动到思源外部时不触发边栏浮动面板就更好了，不过感觉好像不好实现

**Comment by Vanessa219** [comment]
> 如果能设计成，鼠标从思源内部经过停靠栏移动到思源外部时不触发边栏浮动面板就更好了，不过感觉好像不好实现

如果有用户在移除的时候还需要看一下浮动文档树或其他面板，收起来也不太好。

**Comment by pisceswb** [comment]
> > 如果能设计成，鼠标从思源内部经过停靠栏移动到思源外部时不触发边栏浮动面板就更好了，不过感觉好像不好实现
> 
> 如果有用户在移除的时候还需要看一下浮动文档树或其他面板，收起来也不太好。

个人感觉浮动面板应该是鼠标在的时候显示，鼠标移出就消失，才符合浮动的使用逻辑。
感觉在使用思源笔记和其它软件双开时，应该更想看到思源的正文内容，这是双开的目的，而临时出现却不消失的浮动面板遮挡了正文内容。个人还是感觉鼠标不在时浮动面板就收起来更好一点。
