### ISSUE TITLE
请求支持文档树双击展开层级

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#7436]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

文档树默认单击打开文档块，没有任何双击动作
实际使用，当层级很多时，常常需要到达较深的层级，只有文档块开头的箭头区域支持展开文档块，体验非常难受，尤其是最开始的几个，区域非常小，多次展开时，每次都要仔细找到开头区域，操作非常难受，那么，为什么不干脆添加双击展开的鼠标动作呢？

### 描述可能的最优解决方案 Describe the optimal solution

如上

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by Soltus** [comment]
习惯了也没什么，双击有别的安排

**Comment by 88250** [comment]
这个不考虑了，之前已经讨论过。
