### ISSUE TITLE
文档导出模板后能打开所在位置

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7437]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

文档导出模板后能打开所在位置，用以检查是否成功导出。

### 描述可能的最优解决方案 Describe the optimal solution

像导出 pdf 那样，能方便打开文件所在位置。
![image](https://user-images.githubusercontent.com/56879067/220378617-74f0358f-763e-4f6a-bcd8-1db60c9babf2.png)

**Comment by 88250** [comment]
模板主要用于内部，在外部打开的话实际意义不大，因为是私有格式，几乎无法人工修改，而导出其他格式主要是为了分享，所以才在文件系统上打开。
