### ISSUE TITLE
为闪卡复习界面添加 1024 px 的宽度限制

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7442]

**Comment by mozhux** [comment]
这个闪卡的界面能不能不是这样全屏的，导致其他的啥都看不到了，还是希望能自己改动大小

**Comment by Zuoqiu-Yingyi** [comment]
> 这个闪卡的界面能不能不是这样全屏的，导致其他的啥都看不到了，还是希望能自己改动大小

在子窗口显示复习界面试试

**Comment by mozhux** [comment]
> > 这个闪卡的界面能不能不是这样全屏的，导致其他的啥都看不到了，还是希望能自己改动大小
> 
> 在子窗口显示复习界面试试

这个可以曲线救国，但太麻烦了。。得先打开一个新窗口，再用快捷键调出来闪卡。
