### ISSUE TITLE
在反向链接面板中，如果链接对象为标题块。则默认将其折叠

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#7444]
## 背景
本人的双链笔记 workflow 为，将标题链接到某个主题的中心文档，然后在标题下写具体的内容，从而构成一个完整的笔记 Section。

当前在反向链接的面板里，对于标题块反链的处理方案是：展示一部分标题块下属的内容，多余的则隐藏起来，如下图所示

![image](https://user-images.githubusercontent.com/27268127/220513138-d09721e4-f0f8-414f-ae18-8de02578455c.png)

## 问题

带来的问题是，但是当链接多起来的时候，我在中心文档里查看反向链接就会变得不方便。由于每个文档块都默认显示一部分下属的内容，所以无法直观地一眼看出来到底有哪些反向链接文档，必须一点一点地往下翻才行。

### 描述可能的最优解决方案 Describe the optimal solution

当检测到源链接块为标题块（如果可以的话希望也能支持列表块），就默认将其折叠，这样在反向链接面板里看上去就十分清爽，一眼就能看出有哪些链接内容。

![image](https://user-images.githubusercontent.com/27268127/220513509-94313536-dc23-40de-9155-44b4e43dbb72.png)

**Comment by UFDXD** [comment]
不好吧

**Comment by fwzuw** [comment]
我也因为这个设计遇到了类似的问题，不过我期望的解决方法不同。

我在 daily note 中写下了几段文字，并将其放到了一个无序列表下成为一个无序列表。我在内容中间的一行添加了链接，作一个关联作用。
在反链中，只显示了这段内容（列表块）开头的第一段，而不是链接存在的那一段（叶子块）。
我修改格式，改为将这段内容放在一个标题块下，结果一模一样，依然只显示该标题块下的第一段，完全没有链接的上下文信息，连它所在的叶子块的内容都没有，甚至标题块下的第一段是负面信息
标题块可以与文档块相互转换，为什么他们链接出去的反链却不一样呢？

目前有一个间接解决方法，那就是把所有在列表块与标题块中的内容块都写成容器块，这样他们的反链呈现就和档块中的叶子块一样了
我希望列表块与标题块中的叶子块链接目标的反链可以像页面块中的叶子块一样呈现
https://github.com/siyuan-note/siyuan/issues/7447

**Comment by 88250** [comment]
对于标题目前只能这样处理，因为：

* 反链的折叠无法和正文的折叠区分开
* 参照列表项的缩略（列表下面多个子列表时“假”折叠），标题下方块也类似处理，但是标题块下方没有层级关系，所以为了缩略只能像目前这样处理了

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by zxhd863943427** [comment]
@88250 假如反链所在块（下称块a）位于标题块下，能否只显示标题块和块a？目前只显示标题块下的第一个块、甚至可能不包括反链是真的让人困扰

**Comment by 88250** [comment]
@zxhd863943427 等有空分析一下，这个有点复杂。

**Comment by 88250** [comment]
我再描述一下问题：

![image](https://user-images.githubusercontent.com/873584/221342253-4eb1319e-9881-4d9b-a92e-38cc25dadb42.png)

目前存在的问题是定位和下文缺失。

如果直接折叠标题的话会导致定位和上下文都缺失：

![image](https://user-images.githubusercontent.com/873584/221342276-cb4df4e5-a394-4c36-b578-aef4fe0382ed.png)

如果只显示标题和定位的块会导致下文缺失，并且编辑器完整性有一定问题。

目前分析下来较为理想的方案是类似这样：

![image](https://user-images.githubusercontent.com/873584/221342409-4da8cba8-5452-47c2-82ac-c018fadc8971.png)

但是这个方案也有弊端，就是上下的缩略太占位置。

综上，我们是否直接将其改为非传递？也就是类似第一个截图中段落那样，但是面包屑可以体现上文。

**Comment by fwzuw** [comment]
我认为非传递比较好，标题块下的段落块应与文档块下的段落块以同样的方式处理，因为标题是文档中自然的一部分，且二者在思源中可以自由转换，我认为他们应该完全等价。
如果他们的表现形式有区别，那么这种转换就并不自由。

**Comment by 88250** [comment]
之前的说明有点问题，标题传递应该指的是这样（截图也加了段落定位的效果）：

![image](https://user-images.githubusercontent.com/873584/221346057-959ca565-d2f7-41dd-9a91-75d0a985750a.png)

**Comment by leolee9086** [comment]
不建议改动   既然目前反链面板是可编辑的，那么编辑器的部分就不建议跟页签内的编辑器有太多的差异，容易让人迷惑

**Comment by 88250** [comment]
@fwzuw 思源中的双链是参考 RR 做的，列表项中的引用分为传递和关联两种，思源因为是文档型，所以标题块也做了类似处理。

**Comment by 88250** [comment]
考虑了下，我们还是打算改进一下，关联 https://github.com/siyuan-note/siyuan/issues/7484

**Comment by fwzuw** [comment]
是的，改进后的展示更符合预期，有直接关联的内容比不一定有关联的第一段更有价值。

传递型标题展示下文，这个也很好，与传递型列表是同样的逻辑。

关联型标题展示一段下文，像是一个折中的考量，我没怎么用过关联型标题，没有什么想法

最后我想问一下，列表块中的段落块是否也会这么改进
![image](https://user-images.githubusercontent.com/48246272/221347272-906126f0-fc48-46b1-8007-9df85e08a366.png)

**Comment by 88250** [comment]
@fwzuw 这个情况暂时不动了（实际上就是楼主提的全折叠）

**Comment by 88250** [comment]
一起改一下吧，感觉还行。

**Comment by fwzuw** [comment]
好耶 @88250 
这样所有段落块的反链展示就完全统一了

**Comment by zxhd863943427** [comment]
赞同，这个改进感觉符合逻辑很多了。
