### ISSUE TITLE
更改在列表项目内部块按 Enter 的行为方式

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#7445]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前版本：2.7.6

当前使用列表项目时候，如果在列表末尾按 Enter ，其行为方式如下：

1. 如果是单行表项，那么按 Enter 会新开一个新的表项，这个很合理
2. 如果是多行的表项，即在一个表项的内部块，当我们在末尾按 Enter的时候同样会新开一个表项，这个不太合理

![image](https://user-images.githubusercontent.com/27268127/220515736-6e7f0879-1aa4-4bf6-bf62-21ce51d2e6cb.png)

原因如下：当一个列表项内部还有内容块的时候，此时我在末尾的位置按 Enter，大概率是希望继续在这个表项下面写新的内容而不是开一个新的表项。

在当前版本下，如果希望在列表项下面写长内容的话，只能：

1. 每次在末尾按 Enter，然后按 Backspace取消新建的列表项
2. 在列表项末尾防止一个空行，然后在空行上方写作，最后删除这个空行

![image](https://user-images.githubusercontent.com/27268127/220516173-b0c063c3-2bb1-4d1f-bd83-6424cd4bb033.png)

上述两种方式都不甚优雅（2稍微好一点，但是不够优美直观），所以我希望可以更改默认的软件行为。
 

### 描述可能的最优解决方案 Describe the optimal solution

希望的行为：

1. 如果在一个列表项目的内部块里写作的时候，假如在结尾按 Enter，应该优先插入新的空行，而不是新建项目
2. 在空行的末尾再次按 Enter，则把空行转换为一个新的列表项

这个行为的合理之处在于，如果写作人希望写长内容列表，那么他新建空行的次数应该是远大于新建列表项的。这样调整交互逻辑后，可以有效降低需要的击键次数，让写作过程更加丝滑。

![image](https://user-images.githubusercontent.com/27268127/220516588-d4872a85-2d2b-4b10-9bba-ef2fa80c0593.png)

**Comment by fwzuw** [comment]
想要避免回车新建一个列表，只需按 shift enter 软换行

**Comment by 88250** [comment]
这个不考虑调整了，列表项下多个子块按回车跳出也有一些方便之处。
