### ISSUE TITLE
像文档块中的叶子块的反链一样呈现其他内容块（标题块、列表块）中叶子块的反链

### ISSUE THREAD

**Issue by fwzuw** [siyuan-note/siyuan#7447]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/48246272/220537224-16753fd5-fcc8-4e63-8cd1-863cb93ea1df.png)
![image](https://user-images.githubusercontent.com/48246272/220537260-32a0a58a-98a1-496e-8605-0a7f481880eb.png)
![image](https://user-images.githubusercontent.com/48246272/220537280-d3237ed5-40ad-46ff-8de2-34515f21eb5b.png)
![image](https://user-images.githubusercontent.com/48246272/220537305-af894045-b2a8-485d-8c17-668bcb437e8e.png)

### 描述可能的最优解决方案 Describe the optimal solution

如题，像文档块中的叶子块的反链一样呈现其他内容块（标题块、列表块）中叶子块的反链

### 描述候选的解决方案 Describe the candidate solution

用户把所有在列表块与标题块中的内容块都写成容器块，这样他们的反链呈现就和文档块中的叶子块一样了

### 其他信息 Other information

现在的列表块与标题块中叶子块的反链完全没有链接的上下文信息，只有所在容器块的第一段，连叶子块本身的内容都没有，甚至第一段还有可能是相反的负面信息
标题块可以与文档块相互转换，为什么他们内部的叶子块链接出去的反链却不一样呢？

**Comment by 88250** [comment]
我理解没错的话和 #7444 是同一个问题，先关闭了。

**Comment by fwzuw** [comment]
这不是一个问题，至少从用户诉求上来说不是
他的诉求是反链里默认折叠标题块以保持清爽
我的诉求是：**我链接的**是标题块/列表块中的**叶子块**，反链里**呈现的却是标题块**（以及下面第一段），这对于我链接的叶子块来说基本没有提供**有效信息**，甚至可能是**相反**的信息。（比如开头第一段是负面看法，链接的则是正面结论）
正如图中的三种情况，只有中间那种情况成功传递了有效信息，我希望另外两种情况能和这种情况一样表现。

如果我在一个标题块下写了十个段落块，并将其中三个段落块链接出去，反链里却只能看到他们所在标题块的第一个段落块。我要看到的是我链接的那个段落块，而不是他们所在的标题块以及标题块下第一个并不是我要链接的段落块

**Comment by 88250** [comment]
请参考我在 7444 中的回复。
