### ISSUE TITLE
优化 `添加到卡包` 对话框卡包列表

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7448]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

需要将多张卡片添加到同一个卡包时, 点击块菜单中的 `添加到卡包` 菜单项弹出的对话框中的卡包列表顺序是无须的且不固定, 这会导致每次都需要浏览一次列表才能找到想要添加的卡包, 效率较低且易发生误操作

### 描述可能的最优解决方案 Describe the optimal solution

1. 标示出已经包含当前卡片的卡包
2. 卡包列表加载时按照卡包更新时间逆序排序
3. 最常用的 `加入卡包` 按钮常显

**Comment by 88250** [comment]
> 标示出已经包含当前卡片的卡包

这里估计无法实现，因为支持多选块。
