### ISSUE TITLE
部分图片OCR没有识别到文本，能添加重新ocr识别功能吗？

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7451]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

部分图片OCR没有识别到文本，能添加再次重新识别功能吗？

### 描述可能的最优解决方案 Describe the optimal solution

希望在图片右键添加”重新进行ocr识别“的选项，谢谢！

**Comment by 88250** [comment]
请参考用户指南资源文件章节。
