### ISSUE TITLE
在有序列表当中使用flowchart制作流程图会出现箭头丢失问题

### ISSUE THREAD

**Issue by MengQH123** [siyuan-note/siyuan#7452]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

在有序列表当中使用flowchart制作流程图的时候，当展开第一个flowchart的时候，其实所有都正常的，
但是一旦第一个flowchart折叠之后会发现其它列表的flowchart视图当中的箭头会消失了

### 期待的结果 Expected result

1

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

1

**Comment by Vanessa219** [comment]
感觉应该和 https://github.com/siyuan-note/siyuan/issues/6056 是一类问题，如果不是的话麻烦上传一下 .sy 文件

**Comment by 88250** [comment]
暂时没有收到更多补充信息，先关闭了，谢谢。
