### ISSUE TITLE
展开包含包含 mermaid 或 flowchart 图表的折叠块时，图标无法渲染

### ISSUE THREAD

**Issue by MengQH123** [siyuan-note/siyuan#7453]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

在折叠列表当中插入制作好的mermaid视图，在程序重启之后发现会丢失视图

### 期待的结果 Expected result

在折叠列表当中插入制作好的mermaid视图，在程序重启之后依旧能够显示原来的图表

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

No

### 更多信息 More information

这个bug非常严重，而且没有给重视，容易出现数据丢失的问题！！！
如何需要我提供演示，可以随时联系我邮箱

**Comment by Vanessa219** [comment]
数据没有丢失，只是没有渲染。不要担心，展开后再刷新一下就可以看到了。
