### ISSUE TITLE
闪卡复习评分支持撤销

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7455]
https://ld246.com/article/1677115016430

https://github.com/siyuan-note/siyuan/issues/6928#issuecomment-1441267158

**Comment by zxhd863943427** [comment]
一个简单的思路：可以不要复习完一张卡片就立刻写入，可以直到退出闪卡界面再更新。

**Comment by 88250** [comment]
@zxhd863943427 就怕中间出现意外情况无法保存进度。
