### ISSUE TITLE
增长鼠标放在侧栏激活悬浮面板的时间

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7456]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前悬浮文档树面板后，鼠标放在侧栏上，弹出文档树面板所用的时间太短，非常容易误操作，如下图，思源与其他应用分屏，本来我只是想将鼠标从思源移到另一个应用，但路过思源的侧栏时，总是弹出文档树面板，非常烦人。
![增加悬浮面板的激活时长](https://user-images.githubusercontent.com/117154557/220811902-d1e4f0b1-e3cb-4b54-a4ff-80ca4bc5d848.gif)

### 描述可能的最优解决方案 Describe the optimal solution

建议鼠标移到侧栏后，停顿稍长时间后，再弹出悬浮面板。

**Comment by 88250** [comment]
延长的话响应就不及时了哦，所以暂时不考虑了。

**Comment by GH-W94** [comment]
> 延长的话响应就不及时了哦，所以暂时不考虑了。

悬浮主要解决的是节约屏幕空间的问题，不是及不及时的问题，

应该是鼠标在侧栏有停留动作，这才反映出用户有往出弹悬浮面板的意图，软件捕捉到这个信息后再弹出悬浮面板，但现在是正常速度鼠标划过没停留就往出弹，这不是用户的意图。

edge标签侧边放置悬浮后，就是这个逻辑，鼠标在上面停留一下后，弹出悬浮面板。

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/7470
