### ISSUE TITLE
在多选块的情况下，也应弹出行级样式设置面板

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7457]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我用浏览器插件将一篇文章剪贴到思源里的，文字内容全部给加粗了，我需要手动将其取消加粗，结果发现全选后并没有弹出样式设置面板，只能一个块一个块的去设置，那么多内容，一个一个太麻烦了。
![样式面板](https://user-images.githubusercontent.com/117154557/220813597-f8544c15-0a8e-4c9c-992a-b55561c9f996.png)

### 描述可能的最优解决方案 Describe the optimal solution

在多选块的情况下，也应弹出行级样式设置面板

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/5373

**Comment by GH-W94** [comment]
> Duplicate of #5373

没太看明白，他反映的那个是跨块部分选择文字，我反映的是将所有块全选后统一设置文字样式，应该不是一回事吧？还请 D 大详解

**Comment by 88250** [comment]
不支持跨块选择操作行级文本。
