### ISSUE TITLE
拖拽后布局自适应调整

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7458]
* 两栏：第一栏可自适应，固定最后一栏大小
* 三栏：第一栏和最后一栏固定，中间自适应
* 四栏及以上：倒数第二栏自适应，其余固定

**Comment by Vanessa219** [comment]
a5bee1533b1ce0364d616332f36fab09dabdb328

**Comment by pisceswb** [comment]
请问更改后，打开文档树会只压缩第一栏的宽度吗？
因为在小屏笔记本上，两栏分屏，若打开关闭文档树只压缩第一栏宽度的话，第一栏内容就没法看了。现在的设置就挺好，打开文档树，两栏都压缩，文档树及两栏都可以用。关闭文档树也不用手动调宽度。

**Comment by Vanessa219** [comment]
左栏、内容区和右栏属于三栏结构，会自适应内容区域
