### ISSUE TITLE
macOS 版本后期开发建议

### ISSUE THREAD

**Issue by LeokuJessica** [siyuan-note/siyuan#746]
软件内提供更多的快捷键支持
 快捷键可以参照finder（cmd+shift+N.......)

考虑与anki,keyboard maestro 的联动，增加软件相关支持/md格式导出至anki支持
可参考https://space.bilibili.com/10455225/ 应用场景

按照大部分macOS软件的设置，将部分功能移至menu bar,增加preference（cmd+，）

**Comment by LeokuJessica** [comment]
补：软件顶部功能栏可以考虑改成类似于Microsoft Office 自定义的quick access tool bar

**Comment by 88250** [comment]
* 快捷键支持请关注 https://github.com/siyuan-note/siyuan/issues/621
* Markdown 到 Anki 的转换可能要过一久，等再收集一些需求，届时会单独创建 Issue

该提议我先关闭，如果还有建议请继续跟帖，后面做到这一块的时候我们会回顾的，谢谢。
