### ISSUE TITLE
文档置顶功能

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7461]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

置顶文档，排序方式不影响置顶文档。

### 描述可能的最优解决方案 Describe the optimal solution

略。

**Comment by Soltus** [comment]
像WPS那种星标更合适吧

**Comment by mozhux** [comment]
其实书签就是的。。

**Comment by 88250** [comment]
是的，书签可以用来干这个。
