### ISSUE TITLE
Ctrl P 搜索框默认填充上一次搜索内容

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#7462]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

以前打开 Ctrl P 搜索页面搜索框中填充的是上一次搜索的内容，现在这个小特性不知什么时候被改了， Ctrl P 搜索框内默认无填充内容，虽然左侧图标可以打开搜索记录，但对于最常用的上一次搜索内容毕竟要手动操作。

### 描述可能的最优解决方案 Describe the optimal solution

Ctrl P 搜索框默认填充上一次搜索内容

**Comment by 88250** [comment]
支持命名查询以后就改了，如果需要保持关键字，需要使用命名查询。

**Comment by choyy** [comment]
命名查询怎么保存上一次查询的关键字？

**Comment by 88250** [comment]
一个命名查询只能保存一个关键字。

**Comment by choyy** [comment]
所以命名查询不能实现原来的功能，之前搜索页面默认是上一次搜索的关键词很方便，希望能加回来

**Comment by 88250** [comment]
用左侧的下拉箭头吧，因为有一些用户反馈不要默认填充关键字。

**Comment by choyy** [comment]
左侧下拉还没有重新打字快....
