### ISSUE TITLE
复制带有markdown样式字体之后粘贴会携带不必要字符

### ISSUE THREAD

**Issue by MengQH123** [siyuan-note/siyuan#7463]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

在我复制带有markdown样式（类似于加粗，行级代码，标签...）的字体的时候,我们把它粘贴到别处，
比如记事本或者是网页的时候，除了会粘贴文本之外还会把不必要的markdown符号也给一并粘贴
过去了，但是这并不是我们想看到的，因为在某些时候我们只是希望单纯的把这类文本内容粘贴到别处，
例如发送微信的时候，或者是我粘贴一些密码的时候（因为携带了特殊字符而导致密码错误）。
类似于notion或者是flowus这类双链笔记并不会出现此类情况

### 期待的结果 Expected result

复制markdown格式的文本内容，不会出现把markdown格式的文本也复制过来

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

no resources

**Comment by 88250** [comment]
请使用复制纯文本：

![image](https://user-images.githubusercontent.com/873584/221065018-f033dda4-830c-4d59-a9ab-4db09806a584.png)

或者在导出预览模式下复制。
