### ISSUE TITLE
改进浏览器剪藏扩展转换本地图片成功率

### ISSUE THREAD

**Issue by 3t2ugg1e** [siyuan-note/siyuan#7464]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

思源笔记chrome插件无法剪藏先知平台的文章。
参考链接https://xz.aliyun.com/t/12194
![image](https://user-images.githubusercontent.com/62066043/220968348-35479f17-5b70-469c-8f26-376f5c24b93f.png)
经过分析，主要问题是aliyun的图片需要refer才能访问。
![image](https://user-images.githubusercontent.com/62066043/220968588-7c908973-a350-4e03-ae02-28eb626a9a52.png)
![image](https://user-images.githubusercontent.com/62066043/220968747-c442e941-06a8-49e6-8b3f-32ec82074293.png)

### 期待的结果 Expected result

支持refer头

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
最新的思源笔记和插件
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by 88250** [comment]
应该有两个问题：

1. 这个站点上的图床不支持跨域请求
   
   ![image](https://user-images.githubusercontent.com/873584/221077119-640cb45c-d442-4cd9-9d4f-c68025d8d25d.png)

2. 使用后端的网络图片拉取转换报 403，应该是你分析的原因

   ![image](https://user-images.githubusercontent.com/873584/221077254-41f37d10-8f8f-4b5a-8ee8-82d427ac8f8f.png)

前端估计无法搞定跨域了，我们看看后端这里如何改进，谢谢。

**Comment by Zuoqiu-Yingyi** [comment]
@88250 `v2.7.7-dev2` 版本中, 下面超链接对应的图片无法使用 `网络图片转换为本地图片` 功能转换为本地图片
`https://sns-img-bd.xhscdn.com/37e3ba1b-9d7d-0cbf-87f7-a77cd96fb69b?imageView2/2/w/900/format/webp`

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 我这里最新开发版上测试重现不了问题，可以拉取成功。

![image](https://user-images.githubusercontent.com/873584/221449833-7ad7a93f-6c47-4c00-a879-75a04b3241ea.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里最新开发版上测试重现不了问题，可以拉取成功。

我使用 `2.7.7-dev4` 版本依然不能下载, `siyuan.log` 中提示
注: 启用了 socks5 代理

```log
E 2023/02/27 17:44:14 assets.go:148: download net img [https://sns-img-bd.xhscdn.com/37e3ba1b-9d7d-0cbf-87f7-a77cd96fb69b?imageView2/2/w/900/format/webp] failed: 403
```
