### ISSUE TITLE
更新版本后自动打开用户指南

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7469]
更新版本后第一次启动时打开最新的用户指南。

**Comment by mozhux** [comment]
打脸了，那这是直接覆盖本地？还是什么情况操作，等下说又必须联网了

**Comment by 88250** [comment]
用户指南一直是本地的嘛。

**Comment by Zuoqiu-Yingyi** [comment]
说实话, 感觉没啥意义👀
毕竟用户指南里面没有更新说明, 打开了用户也不知道用户指南哪一部分是新增的

**Comment by 88250** [comment]
意义在于更新用户指南本身。

**Comment by mozhux** [comment]
> 用户指南一直是本地的嘛。

那更新版本怎么更新这个？是安装包里带最新的？

**Comment by 88250** [comment]
> 是安装包里带最新的？

是的。

**Comment by 88250** [comment]
@tcmtom 软件本身会弹出更新通知的，链接到链滴上面的版本发布公告。

**Comment by aptexd** [comment]
2.7.7 打开后会出现两个新用户指南的笔记本，关掉其中一个，点击另一个就说“找不到笔记本”
两个都关了后，关闭的笔记本里实际就一个

**Comment by why8023** [comment]
2.7.6版本我钉住了十几个文档, 升级2.7.7之后弹出用户指南后, 之前钉住的文档全没有了, 然后我关了用户指南重启软件也不行

**Comment by aptexd** [comment]
给初级用户进行这种“不算麻烦”措施的“强提醒”还是有必要的
高阶用户一周关一次，还是可以接受的
中阶用户更新一次关一次，也是没有问题的

**Comment by aptexd** [comment]
我钉了两个文档和常开的三个文档也都关了…
这样的确也不够优雅了点……

**Comment by 88250** [comment]
应该不是这个 issue 影响的，可能是其他 bug。
