### ISSUE TITLE
编辑器内容右键划词搜索并链接

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#747]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
写下一段文字后,需要将其融入到整个信息体系中,将其中的关键字关联至已存在的文档块

### 描述最优的解决方案 Describe the optimal solution
选中关键字后,右键,有"关联至文档块"会直接关联至同文件夹下同名的文档块

### 其他信息 Other information
举例:在自然的写完一段文字"周日是女朋友生日,需要给他买礼物balabala。。。。",此时需要将关键字"女朋友"关联至已存在文档块"女朋友"中(人脉管理,事件管理),现有操作方法为,1.删除"女朋友"。2,输入"((女朋友"并回车。不仅操作繁琐,且打断输入流,故有该需求

**Comment by 88250** [comment]
你好，我觉得这个场景似乎加一个划选右键搜索更好一些，这样不仅是同级文件夹可以，还能有一些候选参考。

**Comment by HarryHuaa** [comment]
这样的适用性  确实更广,可以是 第一个默认项是同级文件夹,直接按回车就可以关联,如果想要关联外部的文档块,可根据需求再进行选择

**Comment by deerainw** [comment]
很好的创意，谢谢楼主
