### ISSUE TITLE
当鼠标划出软件时隐藏悬浮面板

### ISSUE THREAD

**Issue by crafter-z** [siyuan-note/siyuan#7470]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

鼠标从悬浮面板划入软件内时正常隐藏
但当鼠标从悬浮面板滑出软件时，悬浮页签不隐藏。
当我不全屏使用笔记时，不隐藏的页签会非常遮挡视野！
![image](https://user-images.githubusercontent.com/62090995/221102203-55aa0cf4-4afd-4585-981a-f90c0166561a.png)

### 期待的结果 Expected result

希望当鼠标从悬浮面板滑入软件内或软件外时都同样能进行隐藏

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: Windows11 22H2 Build22621.1265
```

### 日志文件 Log file

暂不上传

**Comment by pisceswb** [comment]
另外建议仅当鼠标从思源内部移动到边栏时触发悬浮面板，避免①从思源外部移动到思源笔记上触发，避免②按下鼠标选择内容误移动到边栏上，松开鼠标后触发

**Comment by Temacc0531** [comment]
如果按照现在隐藏侧栏时的触发区域话，用户可能很难把鼠标刚好移到展开而又不移出窗口，#7415

或许隐藏侧栏后可以在编辑器两侧有个隐藏浮块（鼠标移过去显示移走隐藏）可以触发展开

**Comment by pisceswb** [comment]
改成鼠标移动到按钮上展开相应按钮的悬浮面板也挺好，就没有移入、移出、选择等各种误触发问题了。
隐藏面板后，显示悬浮块，也能一样操作，移动到按钮上触发。这样形式功能统一
再加上ESC取消悬浮面板的功能。
还有悬浮面板尽可能最大化，因为是瞬时显示性质，不在乎遮挡任何内容

**Comment by pisceswb** [comment]
![image](https://user-images.githubusercontent.com/104658457/221144883-40aa8111-cc0b-40dc-9535-a7d4776b7dfb.png)
点击悬浮菜单的引用块按钮会错误触发悬浮面板

![image](https://user-images.githubusercontent.com/104658457/221145163-9da8b338-4478-4c45-af80-d7a05d3f61f5.png)
想点击段落前的这个标志时，可能会因为鼠标移动到边栏而触发悬浮面板

如果改为鼠标移动到文档树等按钮上触发悬浮面板就不会存在这样的问题，也不用添加任何设置选项和钉住按钮。
还可以实现在打开文档树（常规面板显示）的同时，鼠标移动到大纲按钮上，临时看一眼大纲这样的操作。现在的设置想实现这样的操作就很不方便。
还可以留着边栏空白区域以后添加其他功能，如快捷键等按钮。
便利性和误触是成正比的，感觉整个边栏触发悬浮的误触可能性太大了。

V大看一下可不可行

**Comment by Vanessa219** [comment]
> ![image](https://user-images.githubusercontent.com/104658457/221144883-40aa8111-cc0b-40dc-9535-a7d4776b7dfb.png) 点击悬浮菜单的引用块按钮会错误触发悬浮面板
> 
> ![image](https://user-images.githubusercontent.com/104658457/221145163-9da8b338-4478-4c45-af80-d7a05d3f61f5.png) 想点击段落前的这个标志时，可能会因为鼠标移动到边栏而触发悬浮面板
> 
> 如果改为鼠标移动到文档树等按钮上触发悬浮面板就不会存在这样的问题，也不用添加任何设置选项和钉住按钮。 还可以实现在打开文档树（常规面板显示）的同时，鼠标移动到大纲按钮上，临时看一眼大纲这样的操作。现在的设置想实现这样的操作就很不方便。 还可以留着边栏空白区域以后添加其他功能，如快捷键等按钮。 便利性和误触是成正比的，感觉整个边栏触发悬浮的误触可能性太大了。
> 
> V大看一下可不可行

这个用快捷键也很方便的，要移动到按钮上的话需要一定的精确性。

**Comment by Vanessa219** [comment]
从外部移入和内部自身的移动有冲突，没有很好的算法，就先不解决了。

**Comment by GH-W94** [comment]
建议参考微软的edge，检测到鼠标在侧栏停留时，再弹出悬浮面板，这样就不用考虑移入移出的问题了

**Comment by Vanessa219** [comment]
这个会和侧栏的点击按钮冲突

**Comment by GH-W94** [comment]
> 这个会和侧栏的点击按钮冲突

当鼠标停留在侧栏非按钮区域时，弹出悬浮面板。
当鼠标停留在侧栏按钮上时，弹出悬浮面板，进一步点击鼠标，关闭悬浮面板或打开对应的面板。

为什么讲会发生冲突呢？

**Comment by Vanessa219** [comment]
点击之前可能会悬停一下进行瞄准

**Comment by GH-W94** [comment]
> 点击之前可能会悬停一下进行瞄准

悬停那一下，就让悬浮面板弹出呗，点击后，是该关闭悬浮面板还是打开对应按钮的面板，这是下一步的动作，两者互不影响啊

**Comment by Vanessa219** [comment]
弹出的途中如果用户点击了，就不满足用户的预期了。这个需求我们先不支持。
