### ISSUE TITLE
希望添加uos统信arm64支持

### ISSUE THREAD

**Issue by filusilia** [siyuan-note/siyuan#7472]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

系统是飞腾cpu，arm64的无法安装appimage，会报错，编译安装也无法成功。

### 描述可能的最优解决方案 Describe the optimal solution

希望能添加arm64的支持

**Comment by 88250** [comment]
请参考：

* https://github.com/siyuan-note/siyuan/issues/5596
* https://github.com/siyuan-note/siyuan/issues/4603
