### ISSUE TITLE
建议增加点击关闭按钮最小化到托盘时，触发自动同步的功能

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#7474]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

设置中开启了“点击关闭按钮缩小到托盘”的选项。
工作完成后，一般习惯性的点击思源关闭按钮（最小化到了托盘），就准备关机了。
因此建议点击关闭按钮最小化到托盘时，思源笔记能够触发自动同步

### 描述可能的最优解决方案 Describe the optimal solution

希望增加，谢谢！

**Comment by 88250** [comment]
最小化不一定是要关机，所以自动执行同步不太好。

目前桌面端会监听操作系统关机事件，自动执行退出，但是这个时间内不一定能完成同步，建议还是正常关闭思源后再关闭操作系统。
