### ISSUE TITLE
PDF标注识别bug

### ISSUE THREAD

**Issue by tunshumengjun** [siyuan-note/siyuan#7475]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

对Pdf进行标注 在编辑器中显示的是未经识别的链接

经过测试 直接将pdf文件拖入到编辑器中 不会出现此问题
在assets下新建文件夹(英文) 使用导入资源功能导入的pdf 会出现此问题

### 期待的结果 Expected result

在assets下文件夹中的pdf文件 也能进行标注并识别

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/38078643/221214945-ce657e22-d032-4151-a998-9ea922dd77a4.png)
![image](https://user-images.githubusercontent.com/38078643/221214986-55b63964-41c4-4ab2-a677-65987cf4e422.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: Windows10 教育版
- Browser (if used):Windows客户端
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10825661/siyuan.log)

**Comment by 88250** [comment]
你好，这是设计如此，PDF 标注仅支持放在根目录上，不支持子文件夹。
