### ISSUE TITLE
PDF export supports setting footer template

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7478]
https://ld246.com/article/1676382396561

Built-in template vars:

* `%page` current page number
* `%pages` total page number
* Support [Sprig](https://github.com/Masterminds/sprig) funcs

**Comment by entps** [comment]
请看这个 https://ld246.com/article/1676520513129，也是我发的，总结的更完整一些。

**Comment by 88250** [comment]
@entps 其他导出的改进暂时不考虑了，谢谢。

**Comment by entps** [comment]
好的，谢谢，只要PDF导出完善了，可以导出美观的PDF，基本上也可以够用了！

**Comment by henmy168** [comment]
@88250 @Vanessa219 导出是使用思源后给别人看的门面（我发别人只有PDF，word格式一言难尽），好不好看好不好用直接决定读的人认为这个软件怎么样，这个优先级应该很高的，请问什么时候安排开发啊

**Comment by henmy168** [comment]
设置导出PDF功能的时候，可否设置是否导出头图？真的，美感真的是让人提起兴趣关注思源的重点

**Comment by 88250** [comment]
@henmy168 近期版本应该能安排上。导出题头图我这里测试正常。

**Comment by henmy168** [comment]
> @henmy168 近期版本应该能安排上。导出题头图我这里测试正常。

2.7.10默认主题下，我点pdf导出，是导不出头图的。

**Comment by 88250** [comment]
@henmy168 题头图是上传的图片的吗？默认的随机题头图不会导出的。

**Comment by henmy168** [comment]
> @henmy168 题头图是上传的图片的吗？默认的随机题头图不会导出的。

![image](https://user-images.githubusercontent.com/119473176/226307043-7ec834ca-1b2a-40d6-a86c-15b6d4b402cc.png)
我说的就是随机的题头图和图标。要是PDF能一并导出就很好了。
