### ISSUE TITLE
页签栏的自定义兼容性不够，自定义高度之后滚轮到后面的页签，页签会整体上移

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#7479]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

默认的页签栏（tab-bar）当前选中页签下面有蓝色条，是挺漂亮的，但是想缩小页签栏高度时，怎么调试都有问题。
滚轮移动到后面，所有页签都会上移，造成界面难看。

如果采用 Dark+ 或 Savor 的主题，补充下面css调整高度容易，但是当前选中页签下面没有蓝色条。 

···
.layout-tab-bar{
	padding:0 0 0 4px;
	position:relative;
	height: 28px;
	z-index:0;
	}

.layout-tab-bar .item{
	flex: none;
	border: 0px
	margin-right:4px;
	min-height:unset;
	min-width:unset;
	overflow:visible;
	height: 28px;
}
···

### 期待的结果 Expected result

鼠标滚轮移动到后面，页签不应上移。

### 版本环境 Version environment

```markdown
- Version: 2.7.5
- Operating System: Win10
- Browser (if used):
```

### 日志文件 Log file

没有log文件

**Comment by 88250** [comment]
这个和主程序应该无关，我们关闭 issue 了。

**Comment by jabobian** [comment]
好的，我发现加入下面的代码后就可以了。

···
.layout-tab-bar .item .item__text {
  /* 页签项文本 */
  min-width: 0;
  mask-image: none;
  -webkit-mask-image: none;
}
.layout-tab-bar .item .item__close {
  padding: 4px !important;
}
.layout-tab-bar .item .item__close[data-type="new"],
.layout-tab-bar .item .item__close[data-type="more"] {
  margin: 0 4px;
}
···
