### ISSUE TITLE
鼠标悬停被任务栏遮挡

### ISSUE THREAD

**Issue by jenkinchang** [siyuan-note/siyuan#748]
### 描述问题 Describe the problem

全屏状态下，太长的内容最后两行显示不全

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/74193006/102218835-93b86680-3f19-11eb-8860-b0bd58eed276.png)

### 版本环境 Version environment

* 版本 Version：v0.5.3
* 操作系统 Operating system：Windows 10 专业工作站版 20H2
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5696034/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，v0.5.4 修复。
