### ISSUE TITLE
标签是否可以拖拽排序？

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7480]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

多个标签并列的时候，我想切换两个标签的顺序。

现在只能通过剪切，粘贴实现调整两个标签的顺序，十分不方便

### 描述可能的最优解决方案 Describe the optimal solution

能否像拖拽块一样，通过鼠标切换两个标签的顺序
![image](https://user-images.githubusercontent.com/37429029/221334957-7189025e-d286-4a59-93b7-c30d45b9705c.png)

**Comment by 88250** [comment]
行级元素不支持拖拽 [#行级拖拽](https://github.com/siyuan-note/siyuan/issues/6169)

**Comment by AugustTuan** [comment]
明白
