### ISSUE TITLE
任务列表勾选以后，连带标签也加了删除线。

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7481]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

如题

### 期待的结果 Expected result

标签信息和任务信息是独立的，有的时候起到说明作用。

勾选任务以后，标签不应该也跟着加了删除线

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
默认主题是没有删除线的：

![image](https://user-images.githubusercontent.com/873584/221341155-dda66cdd-74fb-4a47-a8a8-6e24f6dac067.png)
