### ISSUE TITLE
光标无法切换到列表项和代码块之间

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7482]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

如图，光标无法来到列表项符号和代码块中间这个区域。这两个元素是一体的
* 比如我现在想删除掉代码块前面的 * ，这个操作是无法实现的，除非连带这个代码块一起删掉。 
* 再或者，我想临时在代码块前面插入一点说明信息再软换行，也不行，只能写在代码块里面了
![image](https://user-images.githubusercontent.com/37429029/221335312-55817ab8-454e-4812-9a57-b5e78febc102.png)

### 期待的结果 Expected result

允许光标切换到代码块和 * 之间

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
代码块前面不会出现光标插入符位置的，就算在顶层也不会出现，因为代码块是块级元素，在它前面能够输入行级元素是不合理的。

你需要的操作可以这样达成：

1. 在代码块中 Esc 选中这个代码块
   
   ![image](https://user-images.githubusercontent.com/873584/221341072-209e686d-de52-4307-9861-5a3f9f23da22.png)

‘2. Ctrl+Shift+B 在代码块前插入一个空段落块

   ![image](https://user-images.githubusercontent.com/873584/221341081-00941f0e-7686-4b40-b8fa-52775ff28986.png)

3. 按两下删除 Backspace
   
   ![image](https://user-images.githubusercontent.com/873584/221341122-4fbf88e7-06c7-49f4-bede-474f48407f25.png)

**Comment by AugustTuan** [comment]
好的，谢谢
