### ISSUE TITLE
编辑器字号无法调整

### ISSUE THREAD

**Issue by tunshumengjun** [siyuan-note/siyuan#7483]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

昨天使用思源的时候 不知道进行了什么操作 整个编辑器的字号小了一圈
不只是编辑器内 编辑器外也小了一圈
使用的是默认主题 没有使用插件
在设置中 调整字号大小 并没有恢复到之前的效果
恢复默认窗口 也没有恢复到之前效果
现在的大小看起来很别扭 不知道如何修复 

### 期待的结果 Expected result

恢复到之前的显示效果

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/38078643/221343097-2b2312bf-9509-4d79-b615-dbc0d79c875b.png)
![image](https://user-images.githubusercontent.com/38078643/221343135-a77541ce-eb3f-4b3f-a7c1-0b13f8ee4997.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: Windows10教育版
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10830473/siyuan.log)

**Comment by 88250** [comment]
Ctrl+0
