### ISSUE TITLE
复制可直接跳转的块超链接

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7485]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我经常会把思源笔记的一些内容，复制成块超链接，粘贴在其他软件里。 （比如滴答、thebrain、booxnote等等）

我粘贴一个块超链接，并且在其他软件可跳转，需要分两步走。
1. 找到需要复制的块，ctl+alt+h，复制块超链接
![image](https://user-images.githubusercontent.com/37429029/221348340-c1b52671-f077-4783-a64f-2909c09e9d9a.png)

2. 在其他软件或者思源里面，使用ctl+alt+k，填充复制的超链接并编辑链接标题。
![image](https://user-images.githubusercontent.com/37429029/221348357-57d19732-8797-4ed8-8d47-64c36cd606e1.png)

这个第二步操作，则是我在使用块超链接最消耗时间的地方，比如忘了标题的文本是啥，又要回切回思源复制之类的。

### 描述可能的最优解决方案 Describe the optimal solution

能否两步并作一步，除了这种纯文本的半成品块超链接
`siyuan://blocks/20230225150240-mxwymbp`

还可以通过比如_clt+alt+shift+H_的快捷键，
生成这种复制后可直接使用的成品块超链接，标题部分就是复制块的第一行文本。
真心可以节省很多操作时间

`[作息框架2.0](siyuan://blocks/20230225145654-2g67wo4)`

**Comment by 88250** [comment]
这个建议用其他工具（比如 Quicker）进行扩展，因为不一定每个人都希望用“第一行”作为锚文本。

**Comment by AugustTuan** [comment]
> 这个建议用其他工具（比如 Quicker）进行扩展，因为不一定每个人都希望用“第一行”作为锚文本。

明白，段落块的超链接文本需求不一致
但是我最常复制的就是文档块的块超链接，
对于文档的超链接来说，标题作为超链接标题肯定是符合的，
文档的超链接复制可以考虑一下吗？🥹
![image](https://user-images.githubusercontent.com/37429029/221348496-dea6cbe2-0420-44dc-9778-02278c853def.png)

**Comment by Vanessa219** [comment]
复制的 md 格式如果用户粘贴的软件不识别，也是需要手工再进行处理的。

**Comment by choyy** [comment]
双链目前有三种方式触发：
1. `((`， 即`shift+9`
3. `{{` ，即`shift+[`
3.  `[[`， 即`[`

个人觉得方式1和方式3用的比较多，而方式3用的人应该很少，因为方式2跟方式3相比需要按同一个键，但是要多按一个shift键，应该不会有人喜欢多按个键吧？
所以建议将`{{`分配给块超链接，即按`{{`出现与双链相同的引用操作，但是它是块超链接引用 @Vanessa219

**Comment by Vanessa219** [comment]
2 是块嵌入

**Comment by choyy** [comment]
> 2 是块嵌入

那算了....
或者用其他键，比如`^^`、`<<`、`]]`这样

**Comment by 88250** [comment]
这三个都有标记符在用了；块超链接我觉得还是复制粘贴比较好，因为设计上它主要是用于外部，不是内部。
