### ISSUE TITLE
表格能力增强

### ISSUE THREAD

**Issue by zbluex** [siyuan-note/siyuan#7487]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

将一些数据记录在思源笔记内，在笔记本内完成数据记录以及数据处理和分析

### 描述可能的最优解决方案 Describe the optimal solution

目前表格能力相对薄弱，是否可以如notion一样增加对表格的过滤和排序的处理，目前也没有找到相关插件能够支持类似功能。

**Comment by 88250** [comment]
已有的表格只是简单表格，无法完成这些操作。类似 Notion 数据库的功能请关注 #2829
