### ISSUE TITLE
改进任务列表项完成后的样式

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7489]
https://ld246.com/article/1677375468330

**Comment by ZinYY** [comment]
请问有可能提供一个选项吗？感觉改变之后的样式看的太不习惯了，灰色+删除线 基本看不出原来的内容是啥。希望能添加一个选项 选择具体的样式。谢谢！

**Comment by Vanessa219** [comment]
可以自定义

**Comment by ZinYY** [comment]
好的谢谢，我添加了如下的命令在custom.css中，成功改回了原来的样式：
`
.protyle-task--done>div:not([data-subtype="t"]) {
    color: var(--b3-font-family);
    text-decoration: none
}`
供后来的朋友们参考。
