### ISSUE TITLE
编写内容时一级标题的快捷键与顶部编辑器工具栏冲突

### ISSUE THREAD

**Issue by liuzhilinux** [siyuan-note/siyuan#749]
### 描述问题 Describe the problem

在编辑文本内容的时候，通过官方文档里面说明的快捷键 `Ctrl` + `H` 插入标题，然后还需要再一次通过鼠标点选自己想要的标题级别，或按屏幕上指示的快捷键选择标题级别。

![image](https://user-images.githubusercontent.com/20591624/102220884-615c3880-3f1c-11eb-8c64-a6083fc8971a.png)

这样有点反人类。

另外，如果打开设置 -> 编辑器 -> 隐藏编辑器工具栏的开关，使在编辑的时候编辑器工具栏处于隐藏状态，那么我们要插入标题，按下快捷键 `Ctrl` + `H` 的时候是没有效果的（因为隐藏掉了工具栏，原本没有隐藏工具栏的情况下，标题图标下面会有显示标题级别的选择下来菜单的），还需要紧接着再按下 `Ctrl` + `Alt` + `1` 表示使用一级标题。

可以建议你采用和 Typora 一样的插入标题的快捷键。

![image](https://user-images.githubusercontent.com/20591624/102221857-a03ebe00-3f1d-11eb-9e58-84315f3d365a.png)

### 期待的结果 Expected result

直接再页面上体现标题效果。

### 截屏或录像 Screenshot or video

无。

### 版本环境 Version environment

* 版本 Version：0.5.3
* 操作系统 Operating system：Windows 10 Pro
* 浏览器（如果使用）Browser (if used)：null

### 日志文件 Log

无。

### 其他信息 Other information

无。

**Comment by Vanessa219** [comment]
可以在设置中自定义快捷键
