### ISSUE TITLE
闪卡删除后更新复习界面

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#7492]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![动画](https://user-images.githubusercontent.com/32903588/221400317-8ed8fe0e-e842-4a84-8893-40f21cd5143c.gif)

### 期待的结果 Expected result

改进

### 截屏或者录屏演示 Screenshot or screen recording presentation

无

### 版本环境 Version environment

```markdown
- Version: 2.7.7-dev3
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/7497
