### ISSUE TITLE
DOM 中区分不同的对话框

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7493]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前不同的对话框只有一个 CSS 类 `b3-dialog--open` 与 HTML 属性 `data-key` 区分, 无法简单使用 CSS 选择器进行区分, 因此需要提供一个 CSS 选择器以用于区分不同的对话框

### 描述可能的最优解决方案 Describe the optimal solution

在最顶层的 `div.b3-dialog--open` 上通过添加 `id`, `class` 与 HTML 属性区分不同的对话框

**Comment by Vanessa219** [comment]
data-key 是用来确认快捷键后是关闭还是打开当前窗口的，快捷键是可以自定义的，无法用做区分。

dialog 较多，目前不会为每一种单独定义。
