### ISSUE TITLE
无可复习闪卡时复习界面无法预览

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#7494]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

右上角的预览按钮只有在有闪卡可复习的时候才显示。

### 期待的结果 Expected result

预览按钮一直显示。

另外，添加到卡包时候的提示文字能不能改成悬浮在上方？现在悬浮在左侧，遮挡了其他按钮。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/31495943/221407303-2446c6c5-f3ac-4833-b353-674082697fc4.png)
![image](https://user-images.githubusercontent.com/31495943/221407659-e2f68085-0f6c-4b29-a9c3-3e7d6451c295.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.7-dev3
- Operating System: win 11
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
我们考虑了下，在复习界面放预览不太合理，预览卡包的闪卡应该在制卡界面，这个 issue 进行该调整。
