### ISSUE TITLE
外部内容粘贴到表格中后编辑导致换行丢失

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#7501]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

https://user-images.githubusercontent.com/16383685/221465020-eea7c2e1-e1f9-405c-af52-6e304a9809ca.mp4

### 期待的结果 Expected result

预期不影响其他换行

### 版本环境 Version environment

```markdown
- Version: 2.7.7 dev
- Operating System: Windows 11
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
我这里无法重现问题，请上传一下 .sy 文件以便调试，谢谢。

**Comment by woniuxia** [comment]
[20230227112146-4u4bjx8.zip](https://github.com/siyuan-note/siyuan/files/10835783/20230227112146-4u4bjx8.zip)

**Comment by woniuxia** [comment]
补充一下，这个文本是从别的地方复制过来的

**Comment by 88250** [comment]
原始出处能发一下吗？

**Comment by woniuxia** [comment]
![image](https://user-images.githubusercontent.com/16383685/221468059-a741847b-9899-413e-b48c-791dbec3377c.png)
 是经过 OCR 之后的文本
A项错误，亚历山大·普希金，俄国诗人、剧作
家、小说家、文学批评家和理论家、历史学家、
政论家，俄国浪漫主义的杰出代表，俄国现实主
义文学的奠基人，是十九世纪前期文学领域中
最具声望的人物之一，被尊称为“俄国诗歌的太
阳”、“俄国文学之父”，现代标准俄语的创始人。
主要作品有诗歌《自由颂》《致大海》《致恰达耶
夫》等，诗体小说《叶甫盖尼·奥涅金》，短篇小
说《黑桃皇后》，长篇小说《上尉的女儿》等。
B项正确，果戈理，出生于乌克兰波尔塔瓦县，
俄国批判主义作家。他创作的作品有《死魂灵》

**Comment by 88250** [comment]
能够重现问题了，下个版本修复，感谢反馈。

**Comment by woniuxia** [comment]
辛苦D大。
