### ISSUE TITLE
表格宽度调整优化

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#7502]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

https://user-images.githubusercontent.com/16383685/221472624-22e1ee98-5e4b-43e8-a0af-5cf2757a8430.mp4

### 描述可能的最优解决方案 Describe the optimal solution

当前，如果表格宽度过宽，要调整的话，会默认从最小宽度慢慢扩大进行调整，可以优化为从当前宽度自行拖动缩小进行调整吗？

**Comment by 88250** [comment]
我这里无法重现这个问题，请排除其他扩展影响。

![issue](https://user-images.githubusercontent.com/873584/221729989-9d0f096a-dede-4099-aa73-ecf8609eedd3.gif)
