### ISSUE TITLE
光标在悬浮面板的输入框中时悬浮面板不进行隐藏

### ISSUE THREAD

**Issue by lllaterOn** [siyuan-note/siyuan#7504]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![动画5](https://user-images.githubusercontent.com/78646625/221512266-0091496c-0d70-40a0-a966-b8a3a72d2a7a.gif)
如动图所示，反链面板悬浮状态下，一在关键词过滤的框里面打字，面板就自己弹回去了。比较奇怪的是鼠标位置稍微往下一点就不会回弹，往上一点就会，并且这个分界线每次不太一样。已在默认主题下尝试过了，可以复现。

### 期待的结果 Expected result

正常输入关键词过滤

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

[Uploading siyuan.log…]()

**Comment by lllaterOn** [comment]
补充动图，网卡了刚才没上传上
![动画5](https://user-images.githubusercontent.com/78646625/221515651-3a8b15d5-4fc9-4c1f-804e-1563a3221861.gif)

**Comment by lllaterOn** [comment]
补充日志文件
[siyuan.log](https://github.com/siyuan-note/siyuan/files/10837712/siyuan.log)

**Comment by lentikr** [comment]
尝试了一下，应该是中文输入时会出现这种情况。
