### ISSUE TITLE
取消滚动缩放

### ISSUE THREAD

**Issue by YorickGu** [siyuan-note/siyuan#7505]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

是否可以添加一个开关为禁止鼠标滚动缩放

### 描述可能的最优解决方案 Describe the optimal solution

是否可以添加一个开关为禁止鼠标滚动缩放

### 描述候选的解决方案 Describe the candidate solution

是否可以添加一个开关为禁止鼠标滚动缩放

**Comment by YorickGu** [comment]
鼠标有时候滚动的时候不小心按在了command按键上，然后字体大小就变了

**Comment by 88250** [comment]
默认主题没有这个功能。
