### ISSUE TITLE
新增模板变量 `title`

### ISSUE THREAD

**Issue by alexcdever** [siyuan-note/siyuan#751]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
新建文档的时候

### 描述最优的解决方案 Describe the optimal solution
将文档名称作为默认的一级标题

**Comment by 88250** [comment]
你好，我觉得可以通过模板支持 `title` 变量来实现：

1. 自定义模板，使用 `{{.title}}` 变量
2. 在新建的文档中调用该模板完成插入，`{{.title}}` 变量会使用当前文档的名称进行填充

虽然有点麻烦，但是这样更灵活一些吧，你觉得呢？

**Comment by alexcdever** [comment]
> 你好，我觉得可以通过模板支持 `title` 变量来实现：
> 
> 1. 自定义模板，使用 `{{.title}}` 变量
> 2. 在新建的文档中调用该模板完成插入，`{{.title}}` 变量会使用当前文档的名称进行填充
> 
> 虽然有点麻烦，但是这样更灵活一些吧，你觉得呢？

已经有这个自定义模板的功能了吗？还是这只是一个方案？我觉得也行。

**Comment by 88250** [comment]
目前模板还不支持 `title` 变量，v0.5.4 会支持，谢谢。
