### ISSUE TITLE
关于笔记的表情选择建议

### ISSUE THREAD

**Issue by liutianbo** [siyuan-note/siyuan#7510]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

在文档树这个侧边栏里，我想要打开笔记时既要避开后面的功能按钮（【更多】，【新建子文档】），又要避开前面的表情选择，这会让我想要打开笔记的操作变得很小心，尤其在我把侧边栏留的很窄的时候。这个问题很困扰我。

### 描述可能的最优解决方案 Describe the optimal solution

建议修改成如下任意一种
1 在文档树界面不允许改文档表情，用户可以在笔记中修改表情。
2 把文档树中修改表情的功能隐藏到后面的【更多】菜单中
3 用户误点了表情时，能否在弹出表情选择框的同时，同时也打开对应的笔记。
如果考虑有用户很喜欢在文档树中点表情直接修改，可以考虑在配置文件中切换这种功能.

**Comment by 88250** [comment]
1. 文档树上直接选择图标更方便
2. 同上
3. 最好还是不打开

这个功能基本是参考 Notion 的交互，暂时不调整了，感谢反馈。

**Comment by liutianbo** [comment]
notion的三级笔记就没有表情了，思源这边，笔记不断向后缩进，用户点击空间越来越小，真的方便吗？
![image](https://user-images.githubusercontent.com/3666226/221734691-513f21d3-0f53-446f-a44f-b38efa25ee08.png)

**Comment by 88250** [comment]
> notion的三级笔记就没有表情了

我这里 5 级也可以更换图标的：

![image](https://user-images.githubusercontent.com/873584/221735271-d4990d03-1aba-4aa3-917d-5ab7e82b0e85.png)

**Comment by liutianbo** [comment]
好吧，高兴就好

**Comment by 88250** [comment]
这些细节交互上我们尽量学习大厂的经验，毕竟他们用户量较多，值得借鉴。

**Comment by liutianbo** [comment]
加油
