### ISSUE TITLE
图片标题功能增强

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#7511]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我对思源笔记的增改图片标题理想期待是这样的：
1. 打开图片菜单，在图片标题输入内容，编辑器实时增加图片标题（这点已经实现了，并且也支持拉伸input框）
2. 修改/复制/粘贴图片的标题，不需要再打开菜单（因为如果有很多图片，图片标题又很长，每次打开菜单还要拉伸选取是很烦的）

### 描述可能的最优解决方案 Describe the optimal solution

 希望像语雀等在线笔记一样，直接在编辑器就可以修改/复制/粘贴图片的标题，而不需要右键打开菜单，完善图片的使用体验
![image](https://user-images.githubusercontent.com/60436214/221737047-fed824fe-a0f3-4215-a420-84ec37b6a52a.png)

### 描述候选的解决方案 Describe the candidate solution

无

### 其他信息 Other information

无

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/7390
