### ISSUE TITLE
无法将标题块转换为文档块 

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#7513]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

按照帮助文档操作，无法将标题块转换为文档块 

> ## 将标题块转换为文档块
> 
> 在编辑器页签中选择需要转换的标题块，按住该标题块标识图标，然后将其拖拽到文档树需要放置的文件夹中。如果需要放置到笔记本根文件夹上，就将标题块标识图标拖动到顶层的笔记本图标这一行上。
> 
> 标题块转换为文档块后：
> 
> * 标题名将变为文档名
> * 原标题块下如果有子标题，则会按照这些子标题中最大的层级作为新文档中一级标题，其余子标题会根据相对层级进行调整
> 
>   * 比如原标题块下包含了三、四、五级子标题，则转换为文档块后会将这些子标题转换为一、二、三级标题

### 期待的结果 Expected result

将标题块转换为文档块 

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/35998162/221793500-30239708-a3dd-4206-8292-45b99caeeafc.mp4

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10847934/siyuan.log)

**Comment by zxhd863943427** [comment]
查看https://github.com/siyuan-note/siyuan/issues/7430
