### ISSUE TITLE
使用 esbuid-loader 提高前端代码的编译速度

### ISSUE THREAD

**Issue by yb6b** [siyuan-note/siyuan#7514]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

这个 issue 不是新增功能，只是提高一点编程的体验。

我的笔记本上，执行 `pnpm build`  需要90秒。在 dev 时，每次更新代码也颇为漫长。

### 描述可能的最优解决方案 Describe the optimal solution

在webpack的配置里，使用 [esbuild-loader](https://github.com/esbuild-kit/esbuild-loader) 代替 ts-loader, terser-webpack-plugin, babel-loader，编译速度立竿见影地提高。build 一次用时 18 秒。

### 其他信息 Other information

我没有严格地测试各平台，还望多小心。

**Comment by Soltus** [comment]
使用台式机可大幅提高编译速度。

**Comment by 88250** [comment]
能否帮忙 PR，谢谢。

**Comment by yb6b** [comment]
已经提交 #7525
