### ISSUE TITLE
IOS端版本要求能不能降低下，比如到13.0以上

### ISSUE THREAD

**Issue by lzylipu** [siyuan-note/siyuan#7515]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

历史最低1.8.2的最低要求都是13.6，身边所有的设备都安装不了

### 描述可能的最优解决方案 Describe the optimal solution

IOS端版本要求能不能降低下，比如到13.0以上

**Comment by 88250** [comment]
抱歉，降低不了。
