### ISSUE TITLE
移动端左右侧栏全屏和点击区域优化

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7520]

**Comment by 88250** [comment]
@tcmtom 不支持，这个是后退操作。

**Comment by 88250** [comment]
暂时还不确定，后续会参考 Notion 进行改进。

**Comment by Zuoqiu-Yingyi** [comment]
该优化影响到了 桌面端/Web 端 树结构的展开按钮点击区域的高度, 导致其过小
![image](https://user-images.githubusercontent.com/49649786/227771003-5bd6f9ba-9f85-4d52-96e3-adc97f80a8f8.png)
