### ISSUE TITLE
每次更新后，面板位置和钉住的标签页都需要重新设置

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#7523]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

每次更新后，面板位置和钉住的标签页都需要重新设置

### 期待的结果 Expected result

更新后，面板位置和钉住的标签页不需要重新设置

### 版本环境 Version environment

```markdown
- Version: 2.7.6
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

略

**Comment by 88250** [comment]
这个是 v2.7.7 改动布局的影响，请等下个版本（v2.7.8）发布以后再看下能否重现，感谢反馈。

**Comment by 88250** [comment]
这个是 v2.7.7 改动布局的影响，请等下个版本（v2.7.8）发布以后再看下能否重现，感谢反馈。
