### ISSUE TITLE
更新以后，我找不到隐藏侧边栏的按钮了

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7527]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

更新最新版本以后，两边的侧边栏都出来，笔记空间变窄了
鼠标经过侧边栏，还会弹出来文档树，特别干扰人

### 期待的结果 Expected result

我平常全部用的快捷键，不用鼠标点的，请问怎么把侧边栏隐藏起来？
![image](https://user-images.githubusercontent.com/37429029/222011324-49755a7c-bd9e-4311-bdf6-ce5ee4a93f38.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
停靠栏隐藏按钮在底部状态栏左边：

![image](https://user-images.githubusercontent.com/873584/222015800-e4249b81-571b-4fd7-9af9-52ed26540568.png)


![image](https://user-images.githubusercontent.com/873584/222015745-02ee3064-263e-4904-9736-3faf61cc2ba9.png)

**Comment by AugustTuan** [comment]
> 停靠栏隐藏按钮在底部状态栏左边：
> 
> ![image](https://user-images.githubusercontent.com/873584/222015800-e4249b81-571b-4fd7-9af9-52ed26540568.png)
> 
> ![image](https://user-images.githubusercontent.com/873584/222015745-02ee3064-263e-4904-9736-3faf61cc2ba9.png)

原来如此，先要在设置里面把底部状态栏打开，然后隐藏停靠栏。我说我怎么没找到🤣🤣🤣
