### ISSUE TITLE
2.7.7 编辑器自定义字体无效

### ISSUE THREAD

**Issue by ippreacher** [siyuan-note/siyuan#7528]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

编辑器更改字体无效，2.7.6无此问题，更新2.7.7后出现

### 期待的结果 Expected result

希望解决该问题😊

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
我这里无法重现问题：

![image](https://user-images.githubusercontent.com/873584/222015961-1d8d4a5d-9556-4e2a-8e46-91be397ecf51.png)

![image](https://user-images.githubusercontent.com/873584/222015992-f51ea5e6-cfcc-4e71-b2a0-240bf0e88bfa.png)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
