### ISSUE TITLE
为{{.text}}模板变量添加字数限制参数

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#753]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

旧版本锚文本显示是来自于引用文本的前数个字符的

在新版本v0.5.3下锚文本显示统一使用{{.text}}，引用了全文，这是好事，但在全文较长的情况下显示不美观，且在原文有格式的情况下又会把格式贴过来

![QQ截图20201216110842](https://user-images.githubusercontent.com/30611816/102300037-17606a80-3f8f-11eb-820e-ae587b69130b.png)

上方为旧版本锚文本显示，下方为新版本锚文本显示

### 描述最优的解决方案 Describe the optimal solution

为{{.text}}模板变量添加个字符限制参数，例如`{{.text | 10}}`限制前10个字符输出

### 描述候选解决方案 Describe the candidate solution

可以提供个设置以切换回旧版本的默认锚文本显示

**Comment by 88250** [comment]
可使用 `substr` 模板函数 http://masterminds.github.io/sprig/strings.html
