### ISSUE TITLE
文档制的卡不会出现在闪卡管理界面里bug

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7530]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

将文档制卡后，该卡片不会出现在闪卡管理界面里。

### 描述可能的最优解决方案 Describe the optimal solution

所制卡应该出现在管理界面里

**Comment by 88250** [comment]
麻烦描述一下重现步骤。

**Comment by GH-W94** [comment]
> 麻烦描述一下重现步骤。

刚才试了下，可以出现。
昨晚在家里弄，文档制的卡，没有出现在管理中，可能是当时分别快速制卡和加入自定义卡包了，结果不知道啥时候删除了快速制卡，没发现，但之后发现文档标题右侧的制卡标识还在，就去文档树的闪卡管理处去找，结果没找到。
