### ISSUE TITLE
建议将快速制卡和取消快速制卡状态做个区分

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7531]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

目前，将一个段落快速制卡后 ，再取消快速制卡，前后两个状态没有任何标识区别，不易辨识，只能到闪卡管理处查看，非常不便。

### 描述可能的最优解决方案 Describe the optimal solution

建议块标菜单中的“快速制卡”按钮的字体：
在未点击快速制卡时和取消快速制卡后的字体是黑色的，
在点击了快速制卡后，字体变为蓝色，以作区别。
![mmexport1677637788848](https://user-images.githubusercontent.com/117154557/222031454-449fb99f-4bea-4816-9ad1-e05fbc908d94.png)

**Comment by 88250** [comment]
如果已经制卡，可以通过块右侧竖线看到标识，菜单选项名称暂时不调整了，感谢反馈。

**Comment by GH-W94** [comment]
> 如果已经制卡，可以通过块右侧竖线看到标识，菜单选项名称暂时不调整了，感谢反馈。

是的，右侧的竖线可以看出是否已制卡，
但区分不了此卡是通“快速制卡”所得还是通过“添加到卡包”的卡，也即区分不了此卡是在文档树卡包里还是自定义卡包里了

**Comment by 88250** [comment]
从使用场景上来说，建议快速制卡和添加卡包二选一，没有必要同时使用两种。

**Comment by GH-W94** [comment]
> 从使用场景上来说，建议快速制卡和添加卡包二选一，没有必要同时使用两种。

同时使用的场景也是很常见的。比如：
平时大部分时间用“快速制卡”，通过文档树复习，
当考试前或制定某个复习主题任务时，就需要将重点复习的卡片通过“添加到卡包”加到自定义的卡包里进行复习。
这时，两者有个标识区分就很方便了

**Comment by luo-chuan** [comment]
> > 从使用场景上来说，建议快速制卡和添加卡包二选一，没有必要同时使用两种。
> 
> 同时使用的场景也是很常见的。比如： 平时大部分时间用“快速制卡”，通过文档树复习， 当考试前或制定某个复习主题任务时，就需要将重点复习的卡片通过“添加到卡包”加到自定义的卡包里进行复习。 这时，两者有个标识区分就很方便了

看我这个帖子 https://ld246.com/article/1673693363728
如果思源能进一步实现RemNote那样的利用嵌入块对卡片多分类，以及按标签分类的话，就可以满足你的需求
