### ISSUE TITLE
docker部署的时候映射的主机目录必须给 everyone 的完全控制权么？不给权限就启动不了

### ISSUE THREAD

**Issue by loveu5522** [siyuan-note/siyuan#7533]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

docker部署的时候映射的主机目录必须给 everyone 的完全控制权么？
不想给主机映射的目录everyone 的完全控制权，因为这样觉得主机目录就不安全了
有其他解决办法么，我给目录everyone 的完全控制权，就一直报错。

### 期待的结果 Expected result

希望有决绝方案

### 截屏或者录屏演示 Screenshot or screen recording presentation

![截图_20230301110829](https://user-images.githubusercontent.com/44762565/222035624-a740eee3-09f0-411d-a2c3-be9562bfbc2c.png)
![截图_20230301110920](https://user-images.githubusercontent.com/44762565/222035628-94d0d2ed-c409-47b1-895d-8ef0b1d6d121.png)

### 版本环境 Version environment

```markdown
- Version: docker v2.7.7
- Operating System: 群辉DS920+  DSM7.1.1
- Browser (if used): edge
```

### 日志文件 Log file

![0ab1b43ef546bcb32d3d436f4d69536](https://user-images.githubusercontent.com/44762565/222036282-4e03dd4a-4ea9-4c57-803f-383329286ffb.jpg)

**Comment by 88250** [comment]
-u 1000:1000 是给这个用户权限，不是所有用户都有权限。

**Comment by loveu5522** [comment]
> -u 1000:1000 是给这个用户权限，不是所有用户都有权限。

就是PUID PGID 都填1000么，但是映射的文件夹如何给这个1000的权限，在群辉系统里创建了用户但是每个用户的PUID和PGID都是固定的吧，系统给的吧

**Comment by loveu5522** [comment]
> -u 1000:1000 是给这个用户权限，不是所有用户都权限。
不是太明白

**Comment by loveu5522** [comment]
> -u 1000:1000 是给这个用户权限，不是所有用户都有权限。

PUID:1000  PGID：1000 还是没用，还是提示没有权限，因为群辉系统没有这个PUID:1000  PGID：1000用户的

**Comment by 88250** [comment]
看下用户指南中关于 Docker 伺服的章节可能会有帮助。

**Comment by loveu5522** [comment]
> 看下用户指南中关于 Docker 伺服的章节可能会有帮助。

谢谢，终于搞定了 `chown -R 1000:1000 /siyuan/workspace` 要用这条命令，就是感觉siyuan这个权限和其他的镜像不一样，其他的都可以自定义，思源docker只能用1000:10000

**Comment by own5464** [comment]
群晖上设置文件夹权限，难道只能用ssh吗，不能用图形界面更改设置吗，这样操作很不友好呢
