### ISSUE TITLE
希望将通过“添加到卡包”所制的卡也加入到此卡所在文档树处的闪卡复习和管理队列里

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7534]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当通过文档树处的闪卡复习入口进行复习时，目的是为了复习该文档中的所有闪卡，
但目前通过“添加到卡包”所制的卡不不会出现在复习队列中，这就造成了通过“顶栏”和“添加到卡包”两者所制的卡是相互孤立的，用起来总有种水火不容之势的感觉。

### 描述可能的最优解决方案 Describe the optimal solution

建议当通过“添加到卡包”制卡时，在将此卡加入到自定义卡包的同时，也将其在逻辑层面上加入到卡片所在的文档的闪卡复习和管理处，并且，在文档的闪卡管理处禁止删除此卡片。

**Comment by 88250** [comment]
这两个设计上就是分开的，因为文档树是动态的分类，卡包是固定的分类，这两个分别面向的是不同的使用场景。

**Comment by GH-W94** [comment]
> 这两个设计上就是分开的，因为文档树是动态的分类，卡包是固定的分类，这两个分别面向的是不同的使用场景。

这两个设计并不需要矛盾，一定要处于非此即彼的状态，

文档内的所有闪卡（即通“快速制卡”和“添加到卡包”制的卡）一起跟随文档树进行动态分类，

文档内通过“添加到卡包”所制的卡跟随自定义卡包进行固定分类。
