### ISSUE TITLE
提供新建锚文本模板选项

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#754]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

现阶段锚文本默认使用`{{.text}}`模板全文显示，使用嵌入时就会出现全文反复显示两次的情况，于是每次引用都需要修改锚文本显示 （~~#753~~)

### 描述最优的解决方案 Describe the optimal solution

类似于现有的`新建文档名模版`选项

![QQ图片20201216113708](https://user-images.githubusercontent.com/30611816/102302009-0fa2c500-3f93-11eb-8bd4-9d133ac59548.png)

**Comment by 88250** [comment]
后面再考虑，谢谢。

**Comment by 88250** [comment]
锚文本可能不适合作为配置项，因为一旦配置为非 `{{.text}}` 以后：

* 嵌入使用频率可能低于引用频率，每次引用都可能需要手动修改
* 在引用或者嵌入时修改锚文本的交互目前还算简单，偶尔改一下应该能接受

感谢提议，我关闭了，如果有考虑不周之处请继续跟帖讨论，谢谢。
