### ISSUE TITLE
Web版能否支持外链分享功能

### ISSUE THREAD

**Issue by ErDongChen1973** [siyuan-note/siyuan#7542]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

通过自己的域名把笔记分享给别人

### 描述可能的最优解决方案 Describe the optimal solution

例如在访问的域名后面添加字符串的方式，为需要分享的笔记生成链接，有些类似于群晖的分享功能

### 描述候选的解决方案 Describe the candidate solution

暂无

### 其他信息 Other information

暂无

**Comment by 88250** [comment]
请参考这里 https://github.com/siyuan-note/siyuan/pull/7086
