### ISSUE TITLE
通过双括号建立引用关系时，文档的排序按照创建时间最近的排在最前面

### ISSUE THREAD

**Issue by meizilp** [siyuan-note/siyuan#7543]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

做卡片或者写日记时，要和别的文档建立引用，很多时候都是要引用最近创建的。
目前双括号出来的引用列表看不出来是怎么个顺序

### 描述可能的最优解决方案 Describe the optimal solution

文档的排序按照创建时间最近的排在最前面

**Comment by 88250** [comment]
* 如果搜索关键字为空时则查询为空时默认的块引排序规则按最近使用优先 https://github.com/siyuan-note/siyuan/issues/3218
* 不为空时则使用块引搜索排序算法，这个算法有点复杂，大致就是按命名/别名/备注全匹配、文档名全匹配、文档名包含、命名/别名/备注包含、标题块全匹配、标题块包含、列表项首个子块全匹配、列表项首个子块包含、备注包含、非标题和列表内容包含 这个顺序进行的排序

**Comment by meizilp** [comment]
最近使用的定义有没有？
比如我通过Alt+5创建了3日的日记，然后在2日要建立一个到3日的链接，但是3日这个不在列表前面，必须得搜索。

**Comment by 88250** [comment]
“最近使用的引用”指的是已经建立过的引用，按引用建立时间降序。

**Comment by meizilp** [comment]
明白了。我上面那个场景因为3日还没有被任何引用，所以无法在列表中看到，必须要手动搜索

**Comment by 88250** [comment]
嗯，是这个意思。

**Comment by BoysFight** [comment]
为什么这个不考虑根据创建时间进行排序，而是选择了根据引用数量排序啊？
