### ISSUE TITLE
关系图日记过滤失效

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#7547]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

The local graph display ignores the daily notes toggle. Back linked daily notes are displayed even if toggle is turned off.
However the toggle is working if used with global graph view (daily notes nodes can be shown or hidden).

### 期待的结果 Expected result

If turned off daily notes nodes should be hidden from the local graph.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![screenshots](https://user-images.githubusercontent.com/13854802/222440515-0f1cba65-2057-470f-bf24-d4c240b6b34b.gif)

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: Windows 10
- Browser (if used): none
```

### 日志文件 Log file

none

**Comment by 88250** [comment]
Thanks for reporting it, we will fix it later.
