### ISSUE TITLE
自动添加标题序号

### ISSUE THREAD

**Issue by ListenV** [siyuan-note/siyuan#755]
比如：
MarkDown源代码：
```
## 标题一
...
### 标题一子标题
...
### 标题一子标题
...
#### 标题一子标题
...
## 标题二
...
### 标题二子标题
...
```
渲染后：
##################开始######################
## 1. 标题一
...
### 1.1 标题一子标题
...
### 1.2 标题一子标题
...
#### 1.2.1 标题一子标题
...
## 2. 标题二
...
### 2.1标题二子标题
...
###################结束#####################

这样可以使条理更清晰

这个功能可能有些人不需要，所以可以在设置里加入开关

而且最好以二级标题为基准（第一位数字从二级标题开始），开始计数；因为文章中如果有过多一级标题也就是`<h1>`标签，会影响文章的SEO。

**Comment by 88250** [comment]
你好，编辑器内估计加不了，预览这边后面我们看一下能否加个开关来实现，谢谢。

**Comment by skyls03** [comment]
> 你好，编辑器内估计加不了，预览这边后面我们看一下能否加个开关来实现，谢谢。

要的效果就是编辑器那边的md不用变，渲染可以显示出来就行

**Comment by 88250** [comment]
嗯，预览后面加开关应该可以做，但是要等一段时间了，近期有其他任务需要完成。

**Comment by skyls03** [comment]
可以参考这个实现：https://zhuanlan.zhihu.com/p/110257979





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 晚上9:00
收件人: "siyuan-note/siyuan"<siyuan@noreply.github.com&gt;; 
抄送: "一袋米扛几楼"<skyls03@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [siyuan-note/siyuan] 自动添加标题序号 (#755)





 
估计还是手动比较好，我关闭了，感谢讨论。

**Comment by 88250** [comment]
谢谢，可以试下自定义主题。
