### ISSUE TITLE
`Ctrl+Click` click on aliases, names and attributes to open search

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7551]
https://ld246.com/article/1677556550011

**Comment by luo-chuan** [comment]
可不可以把使用默认程序打开 pdf 的快捷键也改成 Ctrl+Click ？
我认为使用默认程序打开 pdf 相比打开 pdf 所在文件夹来说是一个更高频的操作，况且很多时候 pdf 文件位于 assets 文件夹，打开这个文件夹也没什么意义。
如果能够通过 Ctrl+Click 使用默认程序打开 pdf 的话，我甚至不需要左手按键盘，直接鼠标侧键+左键就行了。
我之前在论坛提过：
https://ld246.com/article/1671374605837

**Comment by Vanessa219** [comment]
可以 Shift+click 打开
