### ISSUE TITLE
Android 端 不能关闭 同步提示

### ISSUE THREAD

**Issue by netforfreedom** [siyuan-note/siyuan#7557]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [x] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

当启用云同步后, 在编辑时会一直提示'编辑数据尚未同步到云端 立即同步' 的提示框,不知道怎么关闭. 占用了屏幕资源,使可视区域变小了.

### 期待的结果 Expected result

希望能改进提示.

### 截屏或者录屏演示 Screenshot or screen recording presentation

无无无

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: Android
- Browser (if used):无
```

### 日志文件 Log file

无日志文件.log

### 更多信息 More information

无

**Comment by 88250** [comment]
这个不支持关闭，设计目的是提醒用户数据未同步 https://github.com/siyuan-note/siyuan/issues/7121

视觉上目前也暂时不调整了，如果有更多用户反馈这个问题我们再考虑调整，谢谢。
