### ISSUE TITLE
新建子文档时默认在父文档中插入引用

### ISSUE THREAD

**Issue by luoqixyz** [siyuan-note/siyuan#7558]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

父文档可以作为索引页使用，写日记时，2023年页面下会有1月、2月、3月的引用，1月下会有具体日期的引用，父文档不会感觉突兀，而且也方便整理查看，而且无需打开文件目录。可以在设置中添加功能开关，根据个人需求来进行设置，也可以针对具体文档，或者具体笔记本

### 描述可能的最优解决方案 Describe the optimal solution

可以在设置中添加功能开关，根据个人需求来进行设置，也可以针对具体文档，或者具体笔记本

**Comment by Soltus** [comment]
可以在父文档创建子文档

**Comment by royc01** [comment]
https://github.com/siyuan-note/siyuan/issues/2711

**Comment by TinkMingKing** [comment]
可以直接使用日历挂件或者目录生成挂件

**Comment by 88250** [comment]
先关闭了，正如 #2711 中提到的那样，谢谢。
