### ISSUE TITLE
威联通S3同步失败

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#7559]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

虽然还有些云端空间，但怕后面会不够用，尝试用S3进行同步，参照[这篇文章](https://ld246.com/article/1668517633654)在nas和软件里设置完后进行同步，同步中途报错
![截图_20230303202830](https://user-images.githubusercontent.com/54146035/222722729-2f3c553e-b44e-4955-8f9b-25018602e62e.png)

### 期待的结果 Expected result

希望可以正常同步

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

[新建文本文档.txt](https://github.com/siyuan-note/siyuan/files/10882008/default.txt)

**Comment by 88250** [comment]
从日志上看大概是什么地方的防火墙配置不正确：

![image](https://user-images.githubusercontent.com/873584/222723491-205aadc4-3486-4530-8da6-29d4d20fd15b.png)

你可能需要排查一下服务端配置，我先关闭 issue 了，谢谢。

**Comment by UltramarineSky** [comment]
> 从日志上看大概是什么地方的防火墙配置不正确：
> 
> ![image](https://user-images.githubusercontent.com/873584/222723491-205aadc4-3486-4530-8da6-29d4d20fd15b.png)
> 
> 你可能需要排查一下服务端配置，我先关闭 issue 了，谢谢。

好的，刚刚没注意到这个，只看到后面的`caused by: expected element type <Error> but have <html>`，我在看看配置
