### ISSUE TITLE
桌面端接入 OpenAI Chat API 

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7560]
https://ld246.com/article/1677555309934

* 配置环境变量
  *  `SIYUAN_OPENAI_API_KEY` 指定 API Key
  * `SIYUAN_OPENAI_API_TIMEOUT` 指定超时时间（秒），默认为 15 秒
  * `SIYUAN_OPENAI_API_PROXY` 指定代理，默认为空，即不使用代理
  * `SIYUAN_OPENAI_API_MAX_TOKENS` 指定 tokens 数量，默认为 0，即使用模型默认值
* `/` 菜单加入 `AI Chat` 输入框，输入的文本作为段落块插入
* 通过 https://github.com/sashabaranov/go-gpt3 接入 OpenAI Chat API
* 请求过程中弹出遮罩阻塞界面
* 响应添加到输入的段落块下方

后续计划：

* [ ] https://github.com/siyuan-note/siyuan/issues/7566

**Comment by leolee9086** [comment]
啊？  从未想到的展开

**Comment by SineMark2020** [comment]
震惊！！！ 出乎意料的进展

**Comment by AugustTuan** [comment]
卧槽，说整就整啊。
我以为要等到明年的🤣

**Comment by aptexd** [comment]
王炸来的太快，来不及防备🤣

**Comment by netdog2019** [comment]
哇，哇，哇~~~只能用这三声来表达敬意了。

**Comment by Danielypzhang** [comment]
设置环境变量是不是有点复杂？是否可以通过软件本身的设置界面进行设置，就像同步一样？ 这样手机端也可以使用，也容易修改。

**Comment by Yuminis98** [comment]
配置环境变量？

**Comment by 88250** [comment]
这个改进现阶段主要是面向开发者内测，等上线收集一段时间反馈后可能会考虑实现云端版本。

**Comment by lagunazeng** [comment]
期待啊，真的显著提升效率

**Comment by TinkMingKing** [comment]
我本地代理是使用clash，地址是`127.0.0.1:7890`，但是并不行，日志显示这个
> OpenAI API proxy failed: parse "127.0.0.1:7890": first path segment in URL cannot contain colon

**Comment by Xuwennn** [comment]
我也用的clash，但涉及到环境配置真的一脸懵了（普通小白）。
希望早日能通过简单的方法就能用上了OpenAI🔥

**Comment by xiaozhu1337** [comment]
> 我本地代理是使用clash，`SIYUAN_OPENAI_API_PROXY `环境变量使用`127.0.0.1:7890`并不行，日志显示这个
> 
> > OpenAI API proxy failed: parse "127.0.0.1:7890": first path segment in URL cannot contain colon
> 
> 除非我在设置项中为思源设置如上代理

我还没使用，但是这种一般得指定协议，比如下面这样
```
socks5://127.0.0.1:7890
```

**Comment by TinkMingKing** [comment]
> > 我本地代理是使用clash，`SIYUAN_OPENAI_API_PROXY `环境变量使用`127.0.0.1:7890`并不行，日志显示这个
> > > OpenAI API proxy failed: parse "127.0.0.1:7890": first path segment in URL cannot contain colon
> > 
> > 
> > 除非我在设置项中为思源设置如上代理
> 
> 我还没使用，但是这种一般得指定协议，比如下面这样
> 
> ```
> socks5://127.0.0.1:7890
> ```

明白了，感谢

**Comment by sunk926** [comment]
厉害了,感觉升级,跟上大部队...

**Comment by itachaaa** [comment]
是不是我们普通用户还不能使用这个功能哇？配置了环境变量，但是/菜单栏中没有看到AI 相关的标题

**Comment by s544838371** [comment]
@itachaaa 环境变量咋配置，我知道Docker是有环境变量，官方的在哪配置？

**Comment by jylihh** [comment]
浏览器端没有这个功能吗，我们docker用户是不是太惨了....

**Comment by s544838371** [comment]
@jylihh Docker有环境变量，可能要等更新？

**Comment by jylihh** [comment]
> @jylihh Docker有环境变量，可能要等更新？

开发人员重心应该是在桌面端的，docker版一直只有桌面端的大部分功能，并不是全部功能，不知道是不是会更新。

**Comment by s544838371** [comment]
[v202303072019](https://github.com/siyuan-note/siyuan/releases/tag/v2.7.9-dev1)
这个版本，添加了环境变量后，仍然用的是默认代理，我的文档temp下的siyuan.log日志如下：
OpenAI API enabled [maxTokens=0, timeout=15s, proxy=XXX]
create chat completion failed: Post "https://api.openai.com/v1/chat/completions": malformed HTTP response

**Comment by 88250** [comment]
@s544838371 看上去是代理的问题。

**Comment by suqi** [comment]
真的牛, 没想到这么快, 我之前也想到chatGPT对笔记用户来说非常契合, 因为都是做知识整理!

太太太太棒了

**Comment by Febtw** [comment]
期待docker版本也能接入 openai chat api

**Comment by 88250** [comment]
@Febtw 应该直接设置环境变量就行了

**Comment by Febtw** [comment]
@88250 感谢，已成功在用了

**Comment by Godsing** [comment]
Windows 和 Linux 设置环境变量的方式网上随便一搜就有。
MacOS 环境变量的设置复杂一些，可以参考这位大佬的分享：https://ld246.com/article/1678550510111

**Comment by yuyuchiyuyu** [comment]
![image](https://user-images.githubusercontent.com/57120741/225184367-35684859-497e-45d5-a318-b8f3c985acdd.png)
芜湖  成功了

**Comment by itachaaa** [comment]
> @itachaaa 环境变量咋配置，我知道Docker是有环境变量，官方的在哪配置？ 好家伙，我找到了，直接在windows的环境变量里配置是吗，让我去试试，正好昨天搞了个代理

在windows 设置里面搜索编辑环境变量就可以了，这里有个坑，如果思源笔记是安装到所有人的，就要添加系统环境变量，如果是个人的，应该添加到个人环境变量。

**Comment by lzfhome** [comment]
6
