### ISSUE TITLE
移动端基于文档的间隔重复被文档树遮挡

### ISSUE THREAD

**Issue by EberhardLin** [siyuan-note/siyuan#7562]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

如图所示，移动端无法正常的使用基于文档的间隔重复。

### 期待的结果 Expected result

解决。

### 截屏或者录屏演示 Screenshot or screen recording presentation

![29d545c9eff4d0ef8e6407d1772c7fa](https://user-images.githubusercontent.com/98400319/222735911-8a7e4850-d06a-4e5a-b57d-8e47820380cc.jpg)

### 版本环境 Version environment

```markdown
- Version: v2.7.7
- Operating System: Android 12|MIUI 13.0.4
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Vanessa219** [comment]
e772e97b72b3c6d1baa06a5d07bb930cd76603c4
