### ISSUE TITLE
接入语音转文字的 API

### ISSUE THREAD

**Issue by mlzxy** [siyuan-note/siyuan#7563]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

自己很喜欢记录语音笔记

看完一篇文章，或者博客后，记录是一个很好的提炼和加深理解的过程。 但打字太慢了，记录语音很方便，还可以发给其他人听

但语音的缺点是不能快速预览复习，每次都要重新听

我现在是直接把 mp3 文件拖拽到 Siyuan 里，有的时候会用讯飞的 API 来转文字，把文字贴进去，但很麻烦

### 描述可能的最优解决方案 Describe the optimal solution

如果 Siyuan 能支持语音转文字，哪怕就是把手动 讯飞 + 复制粘贴 这个过程自动化， 文本格式 和 UI 做一些优化，就太完美了

讯飞的 API 是按次和语音时间收费的

如果 Siyuan 内置了这个功能，贵一些也愿意付费，比如按次和语音长度付费

**Comment by 88250** [comment]
这个主线上暂时不考虑了，可能需要社区开发进行扩展，或者考虑使用语音输入法完成。
