### ISSUE TITLE
没有办法转化为代码块的格式

### ISSUE THREAD

**Issue by 1511563371** [siyuan-note/siyuan#7565]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

**期望功能描述**
```txt
在点击段落转化功能，实现将当前段落格式标题，列表或引述时，没有办法转化为代码块的格式类型。

```

### 描述可能的最优解决方案 Describe the optimal solution

**实现方案**
```txt
markText
```

**Comment by 88250** [comment]
这些块类型我们认为不适合转换为代码块所以没有加，谢谢。

**Comment by 1511563371** [comment]
> 这些块类型我们认为不适合转换为代码块所以没有加，谢谢。
我认为添加在哪个转化列表里面不会不合适、您认为呢？

**Comment by 88250** [comment]
举个例子，比如列表块转换为代码就不太适合，因为没有 `1. xxx` 这样的代码哦。

**Comment by 1511563371** [comment]
> 举个例子，比如列表块转换为代码就不太适合，因为没有 `1. xxx` 这样的代码哦。

您好，可能我的需求没有讲清楚。
我是说，将原本的使用快捷方式实现代码块插入的方法，再添加一个页转换，将原本的命令方式转化为鼠标点击方式。

**Comment by 1511563371** [comment]
> 举个例子，比如列表块转换为代码就不太适合，因为没有 `1. xxx` 这样的代码哦。

我这样子想是为了简化不必要的翻找过程。

**Comment by 88250** [comment]
这个我们后期再考虑一下吧，现在暂时不改动了，感谢提议。

**Comment by 1511563371** [comment]
> 这个我们后期再考虑一下吧，现在暂时不改动了，感谢提议。

软件打开的时候，有没有开发者模式

**Comment by 88250** [comment]
桌面端左上角工作空间菜单或者右下角帮助菜单中有。

**Comment by 1511563371** [comment]
> 桌面端左上角工作空间菜单或者右下角帮助菜单中有。

I get it
