### ISSUE TITLE
加入针对内容块的人工智能辅助支持

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7566]
* [x] 续写
* [x] 翻译
   * [x] 中文
   * [x] 日文
   * [x] 韩文
   * [x] 英文
   * [x] 西班牙文
   * [x] 法文
   * [x] 德文
* [x] 提取摘要
* [x] 头脑风暴
* [x] 修正语法和拼写
* [x] 自定义操作...

**Comment by zxhd863943427** [comment]
提示词可以参考https://github.com/briansunter/logseq-plugin-gpt3-openai/blob/master/src/prompts/prompts.toml和这个https://github.com/howl-anderson/unlocking-the-power-of-llms

**Comment by aptexd** [comment]
推荐再加一个更频繁和好用的叫“润写”或“文本润色”
如果“修正语法和拼写”达不到的话
<https://github.com/howl-anderson/unlocking-the-power-of-llms#%E6%96%87%E6%9C%AC%E6%B6%A6%E8%89%B2%E4%B8%8E%E6%94%B9%E9%94%99>

**Comment by 88250** [comment]
@aptexd 我们加个“自定义动作”，选择块以后用户再自己输入操作要求。

**Comment by aptexd** [comment]
dev版，操作生成后，各种容易导致重建索引

**Comment by Achuan-2** [comment]
提问的话我觉得加一个 > ,变为引述块，和chatgpt回答有区别
![image](https://user-images.githubusercontent.com/60436214/223784059-895b93ef-da05-423e-bb69-c9a56489a7b4.png)

**Comment by 88250** [comment]
@aptexd 我这里暂时无法重现。
@Achuan-2 不好区别是否是提问。

**Comment by aptexd** [comment]
场景
我在列表的“他们都走了，我成为了地球上最后一个人，这时门突然被敲响了”的这句话的菜单中选择了续写
然后给了我五六个段落，我本想把这五六个段落都转成列表，然后挪到第一句话下面，当成子项
这时候
1. 这五六个段落转成列表，百分百重建索引，同版本昨晚还能转的
2. 即使能转成列表，当我拖动到第一句话下面当子列表的时候，也百分百重建，而这个重建还会丢数据，把五六条只剩第一条的情况，我感觉会不会是回的数据不干净，所以才…

**Comment by 88250** [comment]
@aptexd 谢谢，我这里可以重现问题了，近期会修复。

**Comment by 88250** [comment]
68679fa90a3b0494e7d09a8c98c3d6f8e8691751

**Comment by aptexd** [comment]
![image](https://user-images.githubusercontent.com/15101966/224220542-98bcfd65-ecc0-41cf-a1ce-2d239e6bb45a.png)
这个场景，我把生成的两个段落生成列表，百分百出发索引重建

**Comment by HowcanoeWang** [comment]
> @aptexd 我们加个 `自定义操作...`，选择块以后用户再自己输入操作要求。

可以后续指定固定自定义操作吗，不然每次都要手动打操作指令还挺麻烦的

甚至可以考虑在设置面板中，专门开一栏AI助手的设置，包括API key，代理什么的，不用修改系统环境变量；以及固定自定义指令到快捷菜单里

**Comment by 88250** [comment]
暂时不加入了，复制粘贴顶顶。

配置上还在考虑是否要改进，等国内厂商的 API 出来以后再看看。

**Comment by Zayia** [comment]
后续是否会加入对移动端的支持?

**Comment by 88250** [comment]
@Zayia 还在考虑，等国内厂商的接口出来以后可能会加。

**Comment by Zayia** [comment]
> @Zayia 还在考虑，等国内厂商的接口出来以后可能会加。

快引用的人工智能辅助为啥只能在桌面端使用啊

**Comment by HowcanoeWang** [comment]
> > @Zayia 还在考虑，等国内厂商的接口出来以后可能会加。
> 
> 快引用的人工智能辅助为啥只能在桌面端使用啊

因为目前是通过系统环境变量读取chatgpt api key的，移动端没有系统环境变量😅
