### ISSUE TITLE
希望可以构建go程序直接运行

### ISSUE THREAD

**Issue by xiamuqingyu** [siyuan-note/siyuan#7567]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

服务器

### 描述可能的最优解决方案 Describe the optimal solution

打包成go程序

### 描述候选的解决方案 Describe the candidate solution

打包成go程序

### 其他信息 Other information

docker部署占用内存过多

**Comment by 88250** [comment]
SiYuan Kernel 本身就是 Go 语言实现的，请参考开发指南进行打包。
