### ISSUE TITLE
请输入问题报告标题 Please enter the title of the bug report

### ISSUE THREAD

**Issue by Phoenix-GR** [siyuan-note/siyuan#7568]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

2.7.7版本，这个问题有issue,但按里面议论的方法没有解决
工作区间添加不了
或者工作区间到底是怎么改的

### 期待的结果 Expected result

把笔记保存到不是C盘的位置

### 截屏或者录屏演示 Screenshot or screen recording presentation

![B](https://user-images.githubusercontent.com/59854442/222890057-2c9dc7b1-bae7-4a12-880a-a49ceaab73e5.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: window
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

![B](https://user-images.githubusercontent.com/59854442/222890225-4c4dbe69-7337-43ee-a46c-84a618f77ab7.png)
选择工作区间打开后却没有创建新的工作区间

**Comment by 88250** [comment]
选择第一个菜单 `打开...`

**Comment by Phoenix-GR** [comment]
设置里吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午5:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 请输入问题报告标题 Please enter the title of the bug report (Issue #7568)





 
选择第一个菜单 打开...

**Comment by 88250** [comment]
你截图的第一个菜单项：

![image](https://user-images.githubusercontent.com/873584/222890845-c4c067d5-e6c7-4c36-8413-4065483d2283.png)

**Comment by Phoenix-GR** [comment]
他提示我不能把工作区间放到SiYuan目录，我是放在SiYuanNote




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 如何修改工作空间位置 (Issue #7568)





 
你截图的第一个菜单项：

**Comment by 88250** [comment]
你的安装路径是在这个目录上层吗？

**Comment by 88250** [comment]
工作空间不能放到安装路径下，否则更新或者卸载程序的时候会删除安装路径下的所有文件。

**Comment by Phoenix-GR** [comment]
不是，安装路径就在SiYuan那个文件夹




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午5:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 如何修改工作空间位置 (Issue #7568)





 
你的安装路径是在这个目录上层吗？

**Comment by 88250** [comment]
我不太清楚你现在的路径情况，建议备份数据，把工作空间路径和安装路径彻底分开。

**Comment by Phoenix-GR** [comment]
不会删除放SiYuan的文件夹的同级的文件吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午5:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 如何修改工作空间位置 (Issue #7568)





 
工作空间不能放到安装路径下，否则更新或者卸载程序的时候会删除安装路径下的所有文件。

**Comment by 88250** [comment]
安装路径下所有文件、文件夹都会删除，和安装路径同级的不会。

**Comment by Phoenix-GR** [comment]
大概是文件路径字符匹配的问题，我的思源安装在D:\Writer\SiYuan ，思源笔记在D:\Writer\SiYuanNote，现在改了位置，是没问题了，谢谢大佬！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 如何修改工作空间位置 (Issue #7568)





 
安装路径下所有文件、文件夹都会删除，和安装路径同级的不会。

**Comment by Phoenix-GR** [comment]
辛苦了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月4日(星期六) 下午5:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 如何修改工作空间位置 (Issue #7568)





 
是的，这里目前是字符串按前缀匹配，没有严格按照实际的文件夹父子结构判断，稍后我们看下是否能改进，谢谢。
