### ISSUE TITLE
撤销编辑时，光标回复到撤销前的编辑位置

### ISSUE THREAD

**Issue by ippreacher** [siyuan-note/siyuan#757]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
编辑文本的过程中，进行ctrl+z撤销操作

### 描述最优的解决方案 Describe the optimal solution
目前撤销后，光标似乎位于按下ctrl+z当时的位置。能否类似于word，光标能回复到撤销之前的位置？这样也能方便确认撤销操作已完成。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/712 中进行考虑改进，谢谢反馈。
