### ISSUE TITLE
关于超级块水平布局无法正常显示及超级块内嵌入块面包屑消失

### ISSUE THREAD

**Issue by lllaterOn** [siyuan-note/siyuan#7572]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

bug1：简单来说就是超级块水平布局内嵌入块的面包屑宽度，会导致超级块水平布局无法正常显示。
bug2：超级块（无论水平、垂直）中的嵌入块，刷新后，面包屑消失。
具体可见这个社区链接https://ld246.com/article/1677858389162

### 期待的结果 Expected result

超级块水平布局内含嵌入块时正常显示，并且刷新超级块内的嵌入块，面包屑不会消失

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10888996/siyuan.log)

**Comment by zxhd863943427** [comment]
目前好像在超级块内就是不打算显示面包屑的：
![图片](https://user-images.githubusercontent.com/74853597/222917623-4120cf8f-2298-45b4-9b77-c2d8ce4d500f.png)

**Comment by 88250** [comment]
合并超级块后刷新下，面包屑应该是不显示的。超级块水平布局如果太窄了会自适应为上下显示。

![issue](https://user-images.githubusercontent.com/873584/222936544-e9d40e5e-2f8f-46a0-ba67-b3077462614e.gif)

**Comment by lllaterOn** [comment]
> 合并超级块后刷新下，面包屑应该是不显示的。超级块水平布局如果太窄了会自适应为上下显示。
> 
> ![issue](https://user-images.githubusercontent.com/873584/222936544-e9d40e5e-2f8f-46a0-ba67-b3077462614e.gif) [ ![issue](https://user-images.githubusercontent.com/873584/222936544-e9d40e5e-2f8f-46a0-ba67-b3077462614e.gif) ](https://user-images.githubusercontent.com/873584/222936544-e9d40e5e-2f8f-46a0-ba67-b3077462614e.gif) [ ](https://user-images.githubusercontent.com/873584/222936544-e9d40e5e-2f8f-46a0-ba67-b3077462614e.gif)

超级块中的嵌入块的面包屑，导致了超级块水平布局无法均分宽度。所以请问是超级块中的嵌入块的面包屑也是设计的不显示是吗？面包屑在超级块中不显示不是我的重点，我只希望水平布局能正常均分就好了。

**Comment by 88250** [comment]
不显示的。

**Comment by lllaterOn** [comment]
> 不显示的。

好的。我之所以发现这个问题，是如动图所示，在文档内使用SQL添加了一个可以随机显示当前文档子文档的嵌入块，并作为超级块和原文内容左右展示。但在刷新的过程中，如果嵌入块引用到了含有面包屑的文章，宽度就会改变。如果按您所说的_合并超级块时自动刷新包含的嵌入块_，是否会导致我这篇文章永远也无法被随机回溯到呢？我比较担心这个问题。

这是SQL的内容

```
SELECT * FROM blocks WHERE hpath like '/观影札记/%' and type = 'd'

ORDER BY random()

limit 1
```

![问题4](https://user-images.githubusercontent.com/78646625/222937159-34553591-277a-4d48-9739-d330000912b8.gif)

**Comment by 88250** [comment]
应该不影响，你现在手动点下刷新按钮试试。

**Comment by lllaterOn** [comment]
> 应该不影响，你现在手动点下刷新按钮试试。

手动点下SQL的刷新之后，这篇文章就随机成其它文章了，当再次刷新SQL直至出现这篇文章时，又会出现左右宽度不均。

**Comment by 88250** [comment]
在超级块内的嵌入块（包含递归嵌入的情况）应该都不显示面包屑才对，可能是这个导致的。

**Comment by lllaterOn** [comment]
> 应该不影响，你现在手动点下刷新按钮试试。

我将随即回溯的SQL更改为直接引用这篇显示异常的文档，不断点击刷新之后，会出现动图中的情况

![问题5](https://user-images.githubusercontent.com/78646625/222937507-ccba08a2-ef49-46c8-b86d-c86b3520266a.gif)

**Comment by 88250** [comment]
这个演示好像没啥问题，因为刷新的时候内容为空，所以会变窄。

**Comment by lllaterOn** [comment]
> 这个演示好像没啥问题，因为刷新的时候内容为空，所以会变窄。

我等下个版本看看，只要能正常显示就行，谢谢D大

**Comment by 88250** [comment]
下个版本不一定能解决，请关注关联的相关 issues。

**Comment by lllaterOn** [comment]
> 下个版本不一定能解决，请关注关联的相关 issues。

D大，我又接着上面的动图出现了新的问题。删除嵌入块之后，标题的布局变了，见动图。不知原因？

![问题6](https://user-images.githubusercontent.com/78646625/222937988-b8a7f2cb-3792-4a40-ac63-7ea08a30cc07.gif)

**Comment by 88250** [comment]
这两个是水平布局的超级块吧？

![image](https://user-images.githubusercontent.com/873584/222938076-91971243-a454-47c9-857a-63612d340c26.png)

是的话应该没啥问题，你删除的是这个标题的下方块：

![image](https://user-images.githubusercontent.com/873584/222938098-ff559889-a7d2-41f8-a23f-a8c2c1129f9b.png)

**Comment by lllaterOn** [comment]
> 

是水平布局的超级块。我再试验后发现如下现象：

标题2的文字，一旦被删去，标题2下没有块时，布局就发生改变。
1. 如这个超级块内有文字。Ctrl+Shift+B / Ctrl+Shift+A 正常。
2. 此刻这个超级块内无文字。如果想要在标题2下添加行，使用 Ctrl+Shift+B / Ctrl+Shift+A 都会新增一个水平超级块。也就是无法在这个标题下添加内容。

此处我为标题快添加了一圈 border，让现象更加明显。经验证使用默认主题也是同样的情况。

![问题7](https://user-images.githubusercontent.com/78646625/222938520-67a9efb9-22a1-410b-b965-92f8a8b477f4.gif)

**Comment by 88250** [comment]
标题 2 这里的垂直超级块如果只有一个子块时就会自动取消超级块，所以 CSA/B 后是在标题1和标题2这一层的超级块上操作。

**Comment by lllaterOn** [comment]
原来如此，明白了，谢谢D大
