### ISSUE TITLE
闪卡复习界面编辑状态切换

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#7573]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

复习界面复习时，很容易将光标放到卡片中，常常意识不到，想要按`空格`显示答案，却无意中不知在何处加上一堆空格……

### 描述可能的最优解决方案 Describe the optimal solution

希望增加编辑限制，**添加一个按钮**，默认无法编辑，点击按钮后才能编辑
为方便键盘交互，可同时设置——回车进入编辑，ESC退出编辑
编辑状态时，可添加类似这样的蓝色矩形框，进一步明确编辑状态
![2023-03-05_001735](https://user-images.githubusercontent.com/32903588/222917015-71b1eff5-5446-4fe0-b363-f1eb507c2011.png)

**Comment by zxhd863943427** [comment]
请问你问的是不是：右上角的只读模式？

**Comment by 88250** [comment]
这样感觉有点多余，因为光标插入符在编辑器中一闪一闪的已经能明显看出是编辑状态了。

**Comment by TinkMingKing** [comment]
> 这样感觉有点多余，因为光标插入符在编辑器中一闪一闪的已经能明显看出是编辑状态了。

有时候专注文字没注意到，不过我才发现主界面只读状态也管这边

**Comment by zxhd863943427** [comment]
这个只读模式的切换可以用快捷键的，ctrl+shift+G,，所以我认为你的问题已经解决了，这个问题可以关闭了。

**Comment by 88250** [comment]
> > 这样感觉有点多余，因为光标插入符在编辑器中一闪一闪的已经能明显看出是编辑状态了。
> 
> 有时候专注文字没注意到，不过我才发现主界面只读状态也管这边

对，主界面的编辑模式切换是在所有编辑器中生效的。
