### ISSUE TITLE
语雀图床的图片在思源笔记无法正常显示

### ISSUE THREAD

**Issue by AILHC** [siyuan-note/siyuan#7579]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

上传到语雀图床的图片贴到思源笔记里无法显示图片
`![](https://cdn.nlark.com/yuque/0/2023/png/671819/1675664222902-2b20db97-5273-400c-9763-1228e5df16b7.png)`
思源笔记里:
![image](https://user-images.githubusercontent.com/21373809/222961378-e9b87683-e540-4ca1-99fa-45197acfa2d7.png)

### 期待的结果 Expected result

正常效果:
![](https://cdn.nlark.com/yuque/0/2023/png/671819/1675664222902-2b20db97-5273-400c-9763-1228e5df16b7.png)

在其他笔记软件是能正常显示的。

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: 安卓伺服，windows浏览器编辑
- Browser (if used): Edge
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/10891864/system-log.zip)

**Comment by zxhd863943427** [comment]
你是使用markdown导入吗？

直接使用插入图片链接时可以显示的
![图片](https://user-images.githubusercontent.com/74853597/222968281-767407ac-15ed-4a7b-a329-2392a1b43689.png)

**Comment by 88250** [comment]
可能是移动端反盗链了，这个没法解决，建议使用本地图片看看。

**Comment by AILHC** [comment]
> 你是使用markdown导入吗？
> 
> 直接使用插入图片链接时可以显示的 ![图片](https://user-images.githubusercontent.com/74853597/222968281-767407ac-15ed-4a7b-a329-2392a1b43689.png)
> 
> 或许是你的网络问题？

怎么可能，issue里的图就是一样的链接。用vscode或者其他方式都可下载和查看

**Comment by AILHC** [comment]
> 可能是移动端仿盗链，这个没法解决，建议使用本地图片看看。

我把链接用手机浏览器打开，也是可以查看和下载的。用手机的obsidian也是可以查看的
