### ISSUE TITLE
同一文档分屏编辑时，两页面能否不彼此影响显示位置？

### ISSUE THREAD

**Issue by ippreacher** [siyuan-note/siyuan#758]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
同一文档分屏编辑时（例如一个页面显示文档上部分，另一页面显示文档下部分），当显示文档上部分的页面编辑时，另一页面会因增加或减少文字而上下跳动。

### 描述最优的解决方案 Describe the optimal solution
能否不上下跳动，类似于word。

**Comment by 88250** [comment]
麻烦录屏一下，我这里好像重现不了你说的问题，谢谢。

**Comment by Vanessa219** [comment]
另一个文档不要拉到最底部，否则会保持底部间距。
