### ISSUE TITLE
文档自定义属性名不能为中文

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#7581]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

创建中文自定义属性名，填入值。提示属性名无效

### 期待的结果 Expected result

是本来就不支持中文还是bug？属性视图已经在做了，还是希望能支持中文。

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
是的，属性名设计上不支持中文，仅支持数字和字母。

**Comment by 88250** [comment]
是的，属性名设计上不支持中文，仅支持数字和字母。
