### ISSUE TITLE
v2.7.8-dev1 块引浮窗空白

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/siyuan#7582]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

更新了最新的dev,块引浮窗失效了，显示空白
![image](https://user-images.githubusercontent.com/46953371/223058554-e0ca3461-0218-48b1-9757-8f9fda0de04d.png)

### 期待的结果 Expected result

应该正常显示

### 版本环境 Version environment

```markdown
- Version: 2.7.8dev1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by XinLi0111** [comment]
+1

**Comment by Vanessa219** [comment]
9916fe7f65d335376353e3bf2951230cc8baa997
