### ISSUE TITLE
进一步统一icon点击的圆角背景

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/siyuan#7584]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

如题，目前思源里的图标鼠标点击的效果不一致，比如顶栏是充满的正方形的，两侧的dock栏又是带有圆角的矩形，底栏又是充满的正方形。

![image](https://user-images.githubusercontent.com/46953371/223063366-11d92f6f-59e6-422c-861f-d86cc9a735a7.png)

![image](https://user-images.githubusercontent.com/46953371/223063478-9e8e3305-c2e7-4f61-962d-7c4c21d8e3b2.png)

### 描述可能的最优解决方案 Describe the optimal solution

类似主题效果那样
![image](https://user-images.githubusercontent.com/46953371/223062888-eba25ab9-3ba8-4c08-a0ea-2704d8b48473.png)

### 其他信息 Other information

无

**Comment by 88250** [comment]
这个是设计如此，暂时不考虑改动了。
