### ISSUE TITLE
搜索结果被高亮分割的同一行内元素应进行合并

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#7585]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

目前思源为了改进搜索的高亮问题，会导致当搜索文本击中超链接后，超链接被分割。
![image](https://user-images.githubusercontent.com/60436214/223145187-52185557-dcf4-4fe8-97a0-08adc9eba904.png)

### 期待的结果 Expected result

希望超链接不被分割，按理来说链接是支持内嵌mark的，是出于什么考量才这样设计

![image](https://user-images.githubusercontent.com/60436214/223144982-b820aec8-b1b0-4b29-ae9a-73d95a44dd4c.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.7
- Operating System: Win11
- Browser (if used):
```

### 日志文件 Log file

无

### 更多信息 More information

无

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/223431188-f543388b-4f2f-4963-8aa5-270a04f52579.png)
现在搜索高亮链接还是会被阻断

**Comment by 88250** [comment]
@Achuan-2 拆分为多个元素是为了高亮关键字
