### ISSUE TITLE
搜索结果内输入字符不应进行分割

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7586]
如下图，1 后面输入会被切分，1前面则不会

<img width="197" alt="image" src="https://user-images.githubusercontent.com/970828/223297759-74c65cee-88d6-42df-9c8a-db0736f71226.png">

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/223305381-d25cc50d-3ddc-4c57-826a-c7c8614dc1d3.png)

在两个行级元素之间 spin 的情况是需要分割的。
