### ISSUE TITLE
桌面端禁止自动播放多媒体

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7587]
https://ld246.com/article/1678118905430

https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions `autoplayPolicy` 选项设置为 `user-gesture-required`。

**Comment by Sunzijie** [comment]
手机端呢？Android手机端一年多了没有修复，打开logseq自动跳转B站

**Comment by Achuan-2** [comment]
@88250 这个设置会导致插件无法在特定时候播放声音，必须要用户点击才可以播放，比如任务提醒加一个提醒声音变得很麻烦，不知道有没有办法禁止自动播放视频，又无需用户点击就可以用代码播放声音

**Comment by TCOTC** [comment]
给个你的代码示例看看

**Comment by Achuan-2** [comment]
目前插件写的界面要点击按钮才会播放声音，比如想要10s后播放声音就会报错
```
setTimeout(() => {
const sound = new Audio("https://www.w3schools.com/tags/horse.ogg");
sound.volume = 0.1,
sound.play();}, 10000); 
```
Uncaught (in promise) NotAllowedError: play() can only be initiated by a user gesture.

**Comment by TCOTC** [comment]
试试这样：

```js
const sound = new Audio("https://www.w3schools.com/tags/horse.ogg");
sound.volume = 0.1,
setTimeout(() => {sound.play();}, 10000); 
```

**Comment by 88250** [comment]
我这里在 console 里两种都可以正常运行

**Comment by Achuan-2** [comment]
1. 控制台和实际插件环境是不一样的
2. 插件用户没直接点击，直接运行这个命令都会报错，只能在用户点击的时候，先播放，把音量设置为0，然后在需要的时候音量设置为1，才可以正常播放
```
const sound = new Audio("https://www.w3schools.com/tags/horse.ogg");
sound.volume = 0.1;
```

**Comment by TCOTC** [comment]
话说 `sound.volume = 0.1` 后面为什么是逗号

**Comment by Achuan-2** [comment]
我随便写的，不用在意这个

**Comment by 88250** [comment]
你试下手动删掉 main.js  `autoplayPolicy: "user-gesture-required"` 后插件能用么？

**Comment by TCOTC** [comment]
> 控制台和实际插件环境是不一样的

确实是有点不同

**Comment by TCOTC** [comment]
> 你试下手动删掉 main.js `autoplayPolicy: "user-gesture-required"` 后插件能用么？

插件可以播放

**Comment by TCOTC** [comment]
要不默认给 B 站的视频链接后面添加 `&autoplay=0` 参数，除非用户填的链接本身带有 `autoplay` 参数

**Comment by Achuan-2** [comment]
我现在的全局番茄钟就是再创建一个BrowserWindow，设置no-user-gesture-required，就可以随意播放声音的

目前这个限制，如果思源后面要做错误提醒的时候有警告声音的之类的功能，就会比较麻烦

**Comment by TCOTC** [comment]
试了一下在浏览器访问思源时也不能使用，只有客户端支持自动播放的话感觉不太对

![Image](https://github.com/user-attachments/assets/7ad25975-25a4-44b7-8448-bc0813ad94df)

**Comment by 88250** [comment]
这个开关估计是不能动了 😂

**Comment by TCOTC** [comment]
@Achuan-2 试试这样行不行？

```js
// 创建 AudioContext
const audioContext = new (window.AudioContext)();
// 检查 AudioContext 状态，判断是否需要用户互动才能播放音频
console.log('AudioContext 状态:', audioContext.state);
// 加载音频资源
fetch("https://www.w3schools.com/tags/horse.ogg")
.then(response => response.arrayBuffer())
.then(arrayBuffer => audioContext.decodeAudioData(arrayBuffer))
.then(audioBuffer => {
    // 创建 GainNode 控制音量
    const gainNode = audioContext.createGain();
    gainNode.gain.value = 0.1;
    gainNode.connect(audioContext.destination);

    setTimeout(() => {
        // 创建 AudioBufferSourceNode
        const source = audioContext.createBufferSource();
        source.buffer = audioBuffer;
        source.connect(gainNode);
        source.start(0);
    }, 5000);
})
.catch(error => {
    console.error('Error loading audio:', error);
});
```

---

我参考的资料：https://developer.chrome.com/blog/autoplay?hl=zh-cn ，https://developer.mozilla.org/zh-CN/docs/Web/API/AudioContext
