### ISSUE TITLE
列表项块引用计数显示

### ISSUE THREAD

**Issue by BRPolaris** [siyuan-note/siyuan#759]
### 描述问题 Describe the problem
如果单个引用列表的一个item，那么在被引用item界面无法显示被链接；如果同时引用列表的一个item以及这个item后面的item，那么在被引用item界面可以显示被链接。

### 期待的结果 Expected result
单个引用列表的一个item，也可以在被引用界面显示被链接。

### 截屏或录屏演示 Screenshot or screen recording presentation
如图，我在文档2中有一个无序列表，含有“itemA”、"itemB”
![image](https://user-images.githubusercontent.com/49936402/102352638-f88bc380-3fe2-11eb-9d71-9964263feb5a.png)

如果我单独引用itemA
![image](https://user-images.githubusercontent.com/49936402/102352864-4acce480-3fe3-11eb-9972-7365ffb092a7.png)
那么我在itemA所在的页面，无法查看到被链接到的信息
![image](https://user-images.githubusercontent.com/49936402/102353001-823b9100-3fe3-11eb-8576-79e13c032f20.png)

如果我复合引用itemA以及下面的itemB
![image](https://user-images.githubusercontent.com/49936402/102353160-a8f9c780-3fe3-11eb-94d0-6b17635a407b.png)
那么我在itemA所在的页面，就可以查看到被链接的信息
![image](https://user-images.githubusercontent.com/49936402/102353331-dc3c5680-3fe3-11eb-860a-022c33bac409.png)

### 版本环境 Version environment

* 版本 Version：0.5.3
* 操作系统 Operating system：win
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，目前只有引用顶层容器块才会显示引用计数，也就是文档根这一层显示。后面做折叠 https://github.com/siyuan-note/siyuan/issues/262 的时候会尽量考虑。

我关闭该 issue 了，如果还有建议请继续跟帖，谢谢。
