### ISSUE TITLE
斜杆菜单缺失 `AI Chat`

### ISSUE THREAD

**Issue by mdzz2048** [siyuan-note/siyuan#7592]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

v2.7.8-dev1
![image](https://user-images.githubusercontent.com/86549958/223369477-34478745-0f25-482c-9d4b-fcb83af867f3.png)

2.7.8
![image](https://user-images.githubusercontent.com/86549958/223369437-5b21e5f2-b88e-498f-91a0-27f20cafe2a7.png)

社区存在类似问题：[2.7.8 最新版 gpt 找不到哎 - 链滴](https://ld246.com/article/1678178022531)

### 期待的结果 Expected result

/ 菜单正常显示 AI Chat 选项

### 版本环境 Version environment

```markdown
- Version: 2.7.8
- Operating System: Windows 11
```

### 日志文件 Log file

[log.zip](https://github.com/siyuan-note/siyuan/files/10907447/log.zip)

**Comment by 88250** [comment]
@Vanessa219 `属性视图` 不应该出现。

**Comment by Vanessa219** [comment]
b55bdb2214ed283b52a264fc7cf8fbd960415c3e

**Comment by Vanessa219** [comment]
等下个版本

**Comment by s544838371** [comment]
2.7.8正式版，我这还有属性视图，然后没有AI Chat

**Comment by s544838371** [comment]
[v202303072019](https://github.com/siyuan-note/siyuan/releases/tag/v2.7.9-dev1)
这个版本，添加了环境变量后，仍然用的是默认代理，我的文档temp下的siyuan.log日志如下：
OpenAI API enabled [maxTokens=0, timeout=15s, proxy=XXX]
create chat completion failed: Post "https://api.openai.com/v1/chat/completions": malformed HTTP response

**Comment by 88250** [comment]
@s544838371 应该是代理的问题。

**Comment by s544838371** [comment]
> @s544838371 应该是代理的问题。

代理是可以使用的，在https://excing.github.io/chatgpt/这个测试网站，只需要输入代理域名即可

**Comment by HowcanoeWang** [comment]
提议参考notion的这个ai快捷方式，用空格直接呼出AI感觉还是比较方便的。

(为了避免给普通用户不必要的困扰，可以设定为检测到环境变量中存在API值的时候，再开启这个快捷方式)

![image](https://user-images.githubusercontent.com/19968935/224493000-abf46002-3c73-46f3-acb3-cee88a8bab54.png)
