### ISSUE TITLE
接入云端人工智能接口

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7601]
订阅后可用，公测阶段暂时不做太多限制，等上线测试一段时间后再考虑限制，比如使用频率限制等。

**Comment by zxhd863943427** [comment]
在中国AIGC有较大风险，官方提供这种服务务必谨慎。最好停留在之前的等级，既让用户通过较复杂的步骤设置自己获取的 api，并最好表明是 alpha 阶段，不对外公测。

**Comment by 88250** [comment]
@zxhd863943427 确实存在风险，我们先进行一些技术方面的探索吧，这个提议以后再考虑推进。

**Comment by luo-chuan** [comment]
暂时公测可以，商用的话还是等国内的互联网厂家推出类chatGPT产品再说，比如阿里、腾讯、百度、字节、华为等，然后用国内的chatGPT，这样就算有法律风险也是这些大厂的。

**Comment by mozhux** [comment]
目前我看国内商业软件已经有跟进了，比如欧陆词典，另外就是上市公司也在弄，法律风险可能主要是在不能自己提供国际信道

**Comment by Yuminis98** [comment]
会员总算有点吸引力了。 否则都不知道为什么要开会员了🤣

**Comment by Joe-rq** [comment]
可以考虑接入百度的文心一言嘛

**Comment by 88250** [comment]
> 可以考虑接入百度的文心一言嘛

还没有出 API 吧？

**Comment by 88250** [comment]
暂时先关闭这个提议，等过段时间再考虑。
