### ISSUE TITLE
docker部署后，一旦引用内存块则导致内核中断

### ISSUE THREAD

**Issue by Pockern** [siyuan-note/siyuan#7603]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

docker部署 v2.7.7 后，在文档中每次使用 `((` 引用，则一定导致内核中断

### 期待的结果 Expected result

能够正常使用引用功能

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/74174207/223667765-d3097858-79ba-4fd0-86b0-e3706c6ba4cf.png)

### 版本环境 Version environment

```markdown
- Version: v2.7.7
- Operating System: Ubuntu Server 22.04 LTS 64bit
- Browser (if used): Microsoft Edge
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10919047/siyuan.log)

**Comment by 88250** [comment]
> handle command failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

请参考部署文档配置 WebSocket
