### ISSUE TITLE
OpenAI API 接入增加环境变量 `SIYUAN_OPENAI_API_BASE_URL`

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7604]
比如可以配置为 `https://你的代理域名/v1`，默认值为 `https://api.openai.com/v1`

PS：

1. [使用 Cloudflare Workers 解决 OpenAI 和 ChatGPT 的 API 无法访问的问题](https://github.com/noobnooc/noobnooc/discussions/9)
2. `SIYUAN_OPENAI_API_PROXY` 和上述代理方案选其中一种就可以，不然多层代理后网络响应时间会变长

**Comment by s544838371** [comment]
牛哇，大佬，我去测测，谢谢

**Comment by l987845225** [comment]
cf部署之后卡的可以试试腾讯云
[[使用腾讯云函数一分钟搭建 OpenAI]](https://github.com/Ice-Hazymoon/openai-scf-proxy)
