### ISSUE TITLE
图片粘贴多出一行

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#7605]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/60436214/223709359-82d7ef1a-99f3-4bbd-8282-505685f1a20f.png)
![image](https://user-images.githubusercontent.com/60436214/223709472-0b03f9d4-7abc-4090-a795-00f5f8a54f8b.png)

### 期待的结果 Expected result

不出现多余的行
 

### 截屏或者录屏演示 Screenshot or screen recording presentation

不知道是不是whitespace的问题
![image](https://user-images.githubusercontent.com/60436214/223709814-f297eb6e-5f29-43fa-aec1-c7b5b86d712c.png)
 

### 版本环境 Version environment

```markdown
- Version: 2.7.8
- Operating System: Win 11
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by Achuan-2** [comment]
2.7.7 无此问题

**Comment by Vanessa219** [comment]
无法重现，是直接粘贴后再进行过什么操作么？

**Comment by Achuan-2** [comment]
没有操作，就是从资源管理器复制图片到思源，光标会撑开一行。
我退回2.7.7，发现正常光标是在图片左边而不是下边的

**Comment by Achuan-2** [comment]
此外也无法通过宽度按钮实现图片百分比大小的调整

**Comment by Vanessa219** [comment]
看一下这个属性上有没有 `display: block;`，只有为这个的时候才会折行。
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/970828/223713490-74a44947-a5c6-427d-abbf-aa31d10bb386.png">

**Comment by Achuan-2** [comment]
`.protyle-wysiwyg .img` display initial的问题，2.7.7 是 display: inline-block，改为这个就正常了

**Comment by Vanessa219** [comment]
奇怪了，我设置为 initial 也不会多行呀。我合并到 https://github.com/siyuan-note/siyuan/issues/7606 中。麻烦 dev 打包后再帮忙看看，多谢。

<img width="980" alt="image" src="https://user-images.githubusercontent.com/970828/223717931-b49695b0-db78-4456-80c2-fc46adccf76b.png">
