### ISSUE TITLE
导出 PDF 有时图片、代码块和图表等渲染有问题

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#761]
另外还有数学公式块滚动条问题 #762

**Comment by zhaoyangkun** [comment]
\phi_2(x)=f(x_0)+(x-x_0)f[x_0,x1]+(x-x_0)(x-x_1)f[x_0,x_1,x_2]\\=f(x_0)+(x-x_0)\frac{f(x_0)-f(x_1)}{x_0-x_1}+(x-x_0)(x-x_1)\frac{f[x_0-x_1]-f[x_1-x_2]}{x_0-x_2}
