### ISSUE TITLE
希望能够加入类似edge浏览器的页签分组功能，以便对文档页签进行整理形成不同的工作区

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7611]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当打开很多个文档或者不同笔记本（主题）的文档时，由于文档的主题不同，这时，若是能对顶部的文档页签栏进行类似edge浏览器的页签归类整理，再配合钉住功能，就能够将常用的不同主题的文档页签放在一起，形成不同的工作区。

edge上的效果：
![文档页签分组](https://user-images.githubusercontent.com/117154557/223893143-9eb8b46d-6ebc-45b7-a302-d8e7d1422f27.gif)

### 描述可能的最优解决方案 Describe the optimal solution

希望考虑

**Comment by ippreacher** [comment]
同意。其实思源可以借鉴浏览器的操作逻辑，obsidian也是如此，即页签可以空白的，然后可以从空白页签打开具体文档或其他操作。现在的思源是页签必须是一个文档，增加新页签就是增加新文档。

**Comment by 88250** [comment]
现阶段暂时不考虑添加这个特性了，以后如果有时间再考虑。

另外，欢迎社区开发者 PR。

**Comment by GH-W94** [comment]
> 现阶段暂时不考虑添加这个特性了，以后如果有时间再考虑。
> 
> 另外，欢迎社区开发者 PR。

好吧，期待以后能够加入这个功能。
现在的文档页签已经能分屏、能新窗口打开，就差个组织管理功能了，从浏览器的使用体验看，加入后会极大的提高工作效率。
