### ISSUE TITLE
嵌入块切换面包屑时背景重新计算高度

### ISSUE THREAD

**Issue by nyaachen** [siyuan-note/siyuan#7612]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

嵌入块切换显示面包屑时，嵌入块背景的阴影没有重新计算高度

### 期待的结果 Expected result

切换显示面包屑后，嵌入块的阴影重新计算高度

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/16128355/224011730-be17c8cc-243b-4899-aca9-a9a5eed7b7c7.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.8
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

内核日志没报错

**Comment by 88250** [comment]
你好，我这里使用用户指南中的文档测试无法重现问题：

![issue](https://user-images.githubusercontent.com/873584/224634629-8a951042-c1b6-475a-a047-cd5a8dc2912c.gif)

请帮忙按以上录屏试下这个步骤能否重现。如果不能重现，说明这个问题可能和文档数据相关，麻烦将能够重现问题的 .sy 文档发送给我们 845765@qq.com

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by nyaachen** [comment]
是这个地方有问题：
切换是否显示引用块的面包屑的时候

**Comment by nyaachen** [comment]
确实无法复现，于是排查了一下文档源码，找到了罪魁祸首。
出问题的那个块，很神奇的有一个自定义属性，height。
![image](https://user-images.githubusercontent.com/16128355/224669228-f68eff6e-df79-47d6-b8f9-a6fea4065755.png)

但是很神奇的就是，引用的文档是四天前新建的，这个出问题的文档我也是四天前新建的，我刚刚尝试了下用别的文件引用它，就没有这个问题，很神奇。

**Comment by 88250** [comment]
确实有点奇怪，请后续帮忙留意，谢谢。
