### ISSUE TITLE
改进内核只读模式

### ISSUE THREAD

**Issue by ylsislove** [siyuan-note/siyuan#7615]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我用docker部署了一个思源笔记，里面记录了我想公开展示的笔记内容。查阅了用户指南，发现内核参数提供了一个readonly模式，尝试了一下，发现很符合我的需求。但也存在一些小问题，主要是在指定了readonly模式下：
1. 用户仍可以点击“数据同步”按钮来登录账号；
2. 当用户点击了“免费试用订阅”按钮后，可以打开设置界面，从而修改一系列的设置；
3. 用户点击“帮助”按钮后，会打开思源笔记用户指南，但这个指南笔记本又无法在readonly模式下关闭或删除；

### 描述可能的最优解决方案 Describe the optimal solution

* 当部署时指定readonly模式后，希望能像下拉菜单中隐藏“设置”、“日记”和“闪卡”那样，将“数据同步”按钮和“免费试用订阅”按钮隐藏掉，或者是将其功能禁用，从而防止他人用户登陆账号或打开设置界面进行修改；
* 如何可以的话，希望能将“锁屏”、“数据历史”和“帮助”菜单项在readonly模式也隐藏掉，因为这几个菜单项在只读模式下用处也不大。

### 描述候选的解决方案 Describe the candidate solution

如果无法隐藏，功能禁用掉也可以。尤其是点击“免费试用订阅”按钮后可以打开设置界面的这个，如果被他人修改了设置就太糟心了🤣

**Comment by 88250** [comment]
界面隐藏

* 锁屏
* 数据历史
* 数据同步按钮
* 订阅按钮

内核接口

* 重新梳理接口

**Comment by Vanessa219** [comment]
* 移动端
* 标签排序

**Comment by ylsislove** [comment]
谢谢D大和V姐💕，我还有个想法，就是在只读模式下能否冻结conf.json的修改。比如说用户A在浏览器打开了思源笔记，然后调整了文档树的宽度，当用户B也打开思源笔记后，文档树的宽度也会和A的一样了。
我追踪了一下，发现每次调整宽度或激活/关闭标签页，都会对应修改conf.json。在只读模式下我不想将变动记录到conf.json，从而可以让所有用户浏览笔记本都保持独立，这个可以做到吗

**Comment by 88250** [comment]
@ylsislove 现在的版本应该就是这样，数据不会被持久化的。

**Comment by ylsislove** [comment]
@88250 刚尝试了一下，确实没有被持久化，挺完美的了哈哈，非常感谢！

**Comment by 88250** [comment]
@luo-chuan 现阶段不考虑引入多人权限机制。
