### ISSUE TITLE
移动端较老 WebView 版本启动后卡在加载界面

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#7616]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![Screenshot_2023-03-10-12-35-13-742_SiYuan](https://user-images.githubusercontent.com/1876302/224224573-fbfc6df7-112d-4775-9df1-db5d59bdb76f.png)

### 期待的结果 Expected result

OK

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 安卓11
- Browser (if used):
```

### 日志文件 Log file

，，

### 更多信息 More information

重置清空了，也不行

**Comment by 88250** [comment]
试试不要开启网络代理再启动。

**Comment by heartacker** [comment]
> 试试不要开启网络代理再启动。

招代理无关，我现在把网络代理成了全部都关闭了就是不行


今天哪怕开头怎么来代理都可以呀，我也没有代理他

**Comment by 88250** [comment]
手动复制日志文件上传一下，路径位于 Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.log

**Comment by heartacker** [comment]
I 2023/03/10 19:37:30 working_mobile.go:64: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/03/10 19:37:30 runtime.go:57: kernel is booting:
    * ver [2.7.9]
    * arch [arm64]
    * os [Android 11/30]
    * pid [23448]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/03/10 19:37:30 conf.go:103: initialized the specified language [zh_CN]
I 2023/03/10 19:37:30 runtime.go:103: use network proxy [system]
I 2023/03/10 19:37:30 serve.go:108: kernel [pid=23448] http server [127.0.0.1:6806] is booting
I 2023/03/10 19:37:30 database.go:88: the database structure is changed, rebuilding database...
I 2023/03/10 19:37:30 database.go:108: reinitialized database [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2023/03/10 19:37:30 conf.go:639: database size [4.1 kB], tree/block count [0/0]
I 2023/03/10 19:37:30 working.go:159: kernel booted
I 2023/03/10 19:37:30 box.go:75: auto stat [trees=0, blocks=0, dataSize=29 kB, assetsSize=0 B]
I 2023/03/10 22:07:43 working_mobile.go:64: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/03/10 22:07:43 runtime.go:57: kernel is booting:
    * ver [2.7.9]
    * arch [arm64]
    * os [Android 11/30]
    * pid [11513]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/03/10 22:07:43 conf.go:103: initialized the specified language [zh_CN]
I 2023/03/10 22:07:43 conf.go:221: downgraded from version [2.7.9] to [2.7.9]
I 2023/03/10 22:07:43 runtime.go:103: use network proxy [system]
I 2023/03/10 22:07:43 serve.go:108: kernel [pid=11513] http server [127.0.0.1:6806] is booting
I 2023/03/10 22:07:43 blocktree.go:386: read block tree [0 B] to [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/blocktree], elapsed [0.00s]
I 2023/03/10 22:07:43 conf.go:639: database size [4.1 kB], tree/block count [0/0]
I 2023/03/10 22:07:43 working.go:159: kernel booted
I 2023/03/10 22:07:43 box.go:75: auto stat [trees=0, blocks=0, dataSize=29 kB, assetsSize=0 B]
I 2023/03/11 11:25:39 working_mobile.go:64: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/03/11 11:25:39 runtime.go:57: kernel is booting:
    * ver [2.7.9]
    * arch [arm64]
    * os [Android 11/30]
    * pid [13426]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/03/11 11:25:39 conf.go:103: initialized the specified language [zh_CN]
I 2023/03/11 11:25:39 conf.go:221: downgraded from version [2.7.9] to [2.7.9]
I 2023/03/11 11:25:39 runtime.go:103: use network proxy [system]
I 2023/03/11 11:25:39 serve.go:108: kernel [pid=13426] http server [127.0.0.1:6806] is booting
I 2023/03/11 11:25:39 blocktree.go:386: read block tree [0 B] to [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/blocktree], elapsed [0.00s]
I 2023/03/11 11:25:39 conf.go:639: database size [4.1 kB], tree/block count [0/0]
I 2023/03/11 11:25:39 working.go:159: kernel booted
I 2023/03/11 11:25:39 box.go:75: auto stat [trees=0, blocks=0, dataSize=29 kB, assetsSize=0 B]
I 2023/03/12 12:06:55 working_mobile.go:64: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/03/12 12:06:55 runtime.go:57: kernel is booting:
    * ver [2.7.9]
    * arch [arm64]
    * os [Android 11/30]
    * pid [13119]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/03/12 12:06:55 conf.go:103: initialized the specified language [zh_CN]
I 2023/03/12 12:06:55 conf.go:221: downgraded from version [2.7.9] to [2.7.9]
I 2023/03/12 12:06:55 runtime.go:103: use network proxy [system]
I 2023/03/12 12:06:55 serve.go:108: kernel [pid=13119] http server [127.0.0.1:6806] is booting
I 2023/03/12 12:06:55 blocktree.go:386: read block tree [0 B] to [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/blocktree], elapsed [0.00s]
I 2023/03/12 12:06:55 conf.go:639: database size [4.1 kB], tree/block count [0/0]
I 2023/03/12 12:06:55 working.go:159: kernel booted
I 2023/03/12 12:06:55 box.go:75: auto stat [trees=0, blocks=0, dataSize=29 kB, assetsSize=0 B]

**Comment by 88250** [comment]
内核看来是启动正常的，试下启动以后用手机上的浏览器能否打开 http://127.0.0.1:6806

**Comment by heartacker** [comment]
不行

**Comment by 88250** [comment]
v2.7.7 可以正常启动对吗？

**Comment by heartacker** [comment]
倒退两个版本之前是OK的，后来升级了一个版本之后，不行再升级的第2个版本也不行

**Comment by 88250** [comment]
也就是说现在卸载再安装 v2.7.7 也不行？

**Comment by 88250** [comment]
麻烦发一封邮件给我 845765@qq.com 稍后我将调整过代码的新安装包通过邮件回复你，请帮忙测试看看是否正常。

**Comment by heartacker** [comment]
现在卸载了，又重新安装了277是可以的

**Comment by 88250** [comment]
好的， 麻烦给我发一下邮件，谢谢。

**Comment by heartacker** [comment]
> 好的， 麻烦给我发一下邮件，谢谢。

heartacker@outlook.com

**Comment by 88250** [comment]
收到，那我给你发邮件吧。

**Comment by heartacker** [comment]
如何看

**Comment by 88250** [comment]
试下这里：设置–>应用程序管理–>全部–>Android System WebView

**Comment by heartacker** [comment]
![Screenshot_2023-03-13-22-06-07-260_设置.png](https://user-images.githubusercontent.com/1876302/224725669-6585d2cb-dd7e-494c-8757-52d9dc950856.png)

![Screenshot_2023-03-13-22-03-56-623_设置.png](https://user-images.githubusercontent.com/1876302/224725668-0f0d91b5-842b-4f07-8754-d0c8d41f66b4.png)

不知道哪个是哪个

**Comment by 88250** [comment]
安装过 Chrome 浏览器吗？

**Comment by 88250** [comment]
试下打开开发者选项，然后看下 WebView 实现用的是哪个。

**Comment by heartacker** [comment]
我的手机看不到这个设置

**Comment by 88250** [comment]
这样吧，你换个邮箱发给我邮件，outlook 接受不了大附件，我们打个包发你帮忙测试看看。

**Comment by heartacker** [comment]
> 这样吧，你换个邮箱发给我邮件，outlook 接受不了大附件，我们打个包发你帮忙测试看看。

1014919474@qq.com

**Comment by 88250** [comment]
邮件已发，感谢帮忙测试。

**Comment by 88250** [comment]
已经定位到问题了，下个版本修复，感谢你的帮助。

**Comment by Soltus** [comment]
> 已经定位到问题了，下个版本修复，感谢你的帮助。

什么问题呀

**Comment by 88250** [comment]
@Soltus https://github.com/siyuan-note/siyuan/issues/7660#issuecomment-1467984894

**Comment by 88250** [comment]
嗯，没有关系。
