### ISSUE TITLE
能不能所有通知自动收纳，并可以回顾通知信息

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7617]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

![image](https://user-images.githubusercontent.com/97731736/224229708-233fe7ed-fb20-4666-a9d9-e0590fa4f9b2.png)
这种红色的通知是很重要的，但需要手动点很烦人的。能不能红色通知也有个自动关闭时间限制。但防止忽略信息收纳到一个地方，可以让人再查看。
就像Visual Studio Code 的
![image](https://user-images.githubusercontent.com/97731736/224230013-e2385721-248c-412e-88a1-a19cc3642338.png)

### 描述可能的最优解决方案 Describe the optimal solution

1

### 描述候选的解决方案 Describe the candidate solution

1

### 其他信息 Other information

1

**Comment by 88250** [comment]
感谢反馈，issue 先关闭了，后期如果需求较多再考虑。

**Comment by GH-W94** [comment]
希望能加入查看历史通知的功能，并将删除通知权限给用户。
有时，那个通知一闪而过，还没看清，就自动消失了，想再看却找不到。
而且大部分其他软件的通知都可以重复查看。
