### ISSUE TITLE
导出pdf后出现了滚动条

### ISSUE THREAD

**Issue by Maxpiner** [siyuan-note/siyuan#762]
### 描述问题 Describe the problem

导出pdf后页面上有时会有滚动条痕迹
（1）在一个有数个块嵌入的文档中，滚动条从文档首行沿伸到文末：
![image](https://user-images.githubusercontent.com/26576290/102362902-de0c1700-3fef-11eb-8d3f-3ba63b40758c.png)

（2）在一个公式块后：
```
y(x_{i+1})=y(x_i)+h\sum^{r-1}_{j=-1}f(x_{i-j},y(x_{i-j}))\int^1_0\prod^{r-1}_{\substack{l=-1\\ l\neq j}}\frac{l+t}{l-j}dt+h^{r+2}(\overline{\xi_i})\frac{1}{(r+1)!}\int^1_0\prod^{r-1}_{j=-1}(j+t)dt
```
pdf上的效果：（实际上这个公式已经显示全了，但是仍然有滚动条）
![image](https://user-images.githubusercontent.com/26576290/102361919-bc5e6000-3fee-11eb-9a8b-0a65265df518.png)

出于网络原因，我看不到上面自己上传的图片，如果没有正常上传的话和发在群里的差不多。
### 期待的结果 Expected result
（1）纵向的滚动条消失；
（2） 公式块自动调节字体大小适应页面宽度，在计算符号处换行或者其他避免显示不全的方法；
### 版本环境 Version environment

* 版本 Version：0.5.4
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
感谢反馈，我们合并到 #761 中一并处理。
