### ISSUE TITLE
允许设置文件夹/文档的默认图标

### ISSUE THREAD

**Issue by catmade** [siyuan-note/siyuan#7622]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

每次新建文章时，都会有一个默认空白的图标，看起来很不协调。论坛也有人反馈类似的需求：
- 新版本思源笔记怎么替换默认文件夹图标 https://ld246.com/article/1655034302183/comment/1655125037447
- 思源笔记修改目录层级的默认图标 (第二版) https://ld246.com/article/1635225279222

### 描述可能的最优解决方案 Describe the optimal solution

希望可以在“外观”设置中加入两项设置，用来设置默认的文件夹图标、设置默认的文档图标

**Comment by catmade** [comment]
在这里有设置

https://github.com/siyuan-note/siyuan/blob/0268a942435997f081ec77868bb71f035e1e00ac/app/src/constants.ts#L382-L384

**Comment by 88250** [comment]
这个暂时不考虑自定义了，如果实在需要建议通过 CSS 覆盖。
