### ISSUE TITLE
文档树加入最大宽度限制

### ISSUE THREAD

**Issue by tcmtom** [siyuan-note/siyuan#7623]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

现在文档树有最小宽度限制，现在文档树可以无限右拉，应该有个最大宽度限制才好

### 描述可能的最优解决方案 Describe the optimal solution

个人认为最大限制在半屏或者3/4屏就好

**Comment by luo-chuan** [comment]
你不拉这么多不就好了？

**Comment by 88250** [comment]
之前考虑过，但是从实际使用看暂时不加入最大限制比较好，因为有的适合确实需要拉很大。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
