### ISSUE TITLE
表格和有内容的段落块中插入多个文件时不进行分块

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#7624]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

如题，复制本地图片到表格中时：
1. 如果表格没有文字，则图片覆盖掉表格
2. 如果表格中有文字，则图片粘贴到表格外面

### 期待的结果 Expected result

图片能够正确粘贴到单元格中

### 截屏或者录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/5226690/224357667-24bf21d1-b322-4859-acd6-11508264b20e.mp4

### 版本环境 Version environment

```markdown
- Version: 2.7.9
- Operating System: win11
- Browser (if used):
```

### 日志文件 Log file

无需

**Comment by 88250** [comment]
@Vanessa219 除了表格，其他块也是一样 https://ld246.com/article/1678622684450
