### ISSUE TITLE
每次重新打开思源都会重置帮助文档而不是打开和关闭帮助文档笔记本

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/siyuan#7626]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

如题，根据帮助文档的消息提示，是打开和关闭帮助文档才会重置数据，我理解是说右键删除笔记本后重新打开或关闭笔记本后重新打开，这样会导致数据的重置，而不是在保留帮助文档的前提下，开关思源软件本体也会导致帮助文档的重置，但目前就是这样重置了，是否是打开思源的时候就在获取最新的文档？

### 期待的结果 Expected result

核实是否是bug，如果不是，希望变更一下通知描述，改为每次打开思源都会重置帮助文档

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/46953371/224382127-ab9f06cc-0078-4ed3-bc09-98de9abf1a25.png)
录入了测试数据文本
关闭思源后打开，空了
![image](https://user-images.githubusercontent.com/46953371/224382213-03e30b77-1848-458e-b824-cca560f1d778.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.9
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
感谢反馈，稍后调整一下提示文案：

![image](https://user-images.githubusercontent.com/873584/224487025-334637a6-31ae-459b-a8d9-c0d19bff09a1.png)
