### ISSUE TITLE
导出图片性能

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#7627]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

聚焦文档的第一个标题，导出标题和其下属内容的图片。耗时极长。CPU 和 内存 使用均比较大。
[.sy 文件](https://github.com/siyuan-note/siyuan/files/10947723/20230216191902-sf0twzj.zip)

### 期待的结果 Expected result

就一小节内容，应该不会造成明显的性能影响的，希望能找到原因

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/31495943/224467142-dba008f3-7cf4-4d93-9f5b-51bb93d0b9ba.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.9
- Operating System: win 11
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
我这里导出大概只需要 2s，不确定是不是因为图片缺失造成的无法重现问题：

![image](https://user-images.githubusercontent.com/873584/224486719-a39e97d7-5f4f-488e-977b-dd7276a6ee48.png)


我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by XinLi0111** [comment]
我测试了下，只有一个标题，什么内容也不写，导出图片的时间依旧很久。导出图片时，CPU 30%多，内存正常 400M左右，导出图片开始以及导出后内存一直维持在 1400多M，CPU占用回复正常。

**Comment by 88250** [comment]
如果不是标题，而是其他块（比如段落块）呢？

**Comment by XinLi0111** [comment]
可能是我表述的问题，不是 heading标题，是 title 文档名称。

我也测试了在新建只有文档名称（默认时间编码样式）的情况下写入一行文本（纯中文，不超过20字），无其他任何内容。导出也是很久。资源一样上升许多。

**Comment by 88250** [comment]
我这里始终无法重现问题，能否测试一下在一个新的工作空间中是否能重现，谢谢。

**Comment by XinLi0111** [comment]
新的工作空间正常，那有什么办法排查下这个问题？

**Comment by 88250** [comment]
这就很奇怪了……能否把现在的工作空间 data 打个包发我试试 845765@qq.com

**Comment by 88250** [comment]
另外你可以试下把整个工作空间换个路径看看。

**Comment by XinLi0111** [comment]
导出 data，然后导入到新的工作空间就好了。D 大知道可能的原因吗？硬盘问题？

另外，导出的 data.zip 文件是以纯时间命名的，要不是记得导出了，时间长了怕不好找。能不能添加个 "siyuan_" 在前面。也好通过 everything 等工具直接查找下备份。

**Comment by 88250** [comment]
有可能是文件系统相关的权限问题，我也不太清楚。

导出的数据文件估计不能改，因为可能已经有其他扩展在依赖。

**Comment by XinLi0111** [comment]
好的，谢谢 D 大。期待属性视图早日上线。

**Comment by WACrown** [comment]
我也遇到了这个问题，导出图片卡死10-30秒，内存暴涨到1.7G。
我发现了我这里导致这个问题的原因：
我把emoji的那个设置改为了twitter emoji，而不是原生emoji，就出现了这个问题

**Comment by 88250** [comment]
Ref https://github.com/siyuan-note/siyuan/issues/8205
