### ISSUE TITLE
在搜索预览窗口中修改文档,其中的高亮会消失

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#7630]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

搜索一个单词, 预览窗口中显示这个词所在的块,同时将该单词高亮显示, 然后在预览窗口中直接修改该块会导致高亮的单词消失,
应用场景:
搜索一个表格, 里面有多个匹配的单词, 在预览窗口中对匹配的单词挨个修改,
由于修改会导致高亮消失,因此找到下一处需要修改的地方变得麻烦

### 期待的结果 Expected result

在搜索预览窗口中修改,不会导致高亮消失

### 版本环境 Version environment

```markdown
`
```

### 日志文件 Log file

`

**Comment by 88250** [comment]
这个估计无法改进了，因为编辑器在处理输入时必须删掉高亮样式，否则高亮会被持久化。

**Comment by iamqiz** [comment]
这个会被持久化? 😲 没有办法忽略吗  感觉不难忽略 
```
<span data-type="search-mark"> 文本 </span>
```

**Comment by iamqiz** [comment]
在预览窗口中不取消高亮
保存时处理一下,把高亮去掉, 这可行吗
```
a=document.querySelector(`span[data-type="search-mark"]`)
a.replaceWith(a.textContent)
```

**Comment by 88250** [comment]
不行的，一打字就要保存，整个块的 search-mark 就没了。
