### ISSUE TITLE
特性提议：查看所有代办标记

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#7633]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

查看笔记中的所有代办（视频中软件为onenote）
我觉得很实用🧐

https://user-images.githubusercontent.com/112467275/224530329-a9a7b7f8-c307-4ac8-a8e8-bba1877c26c5.mp4

### 描述可能的最优解决方案 Describe the optimal solution

onenote
![image](https://user-images.githubusercontent.com/112467275/224530398-8790370f-abba-413a-8430-0391d0b3a662.png)

**Comment by 88250** [comment]
感谢提议，但是这个目前不考虑提供直接的功能入口了，建议通过嵌入块或者挂件进行实现。
