### ISSUE TITLE
支持保存和加载不同的界面布局

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7636]
https://ld246.com/article/1678611225445

**Comment by GH-W94** [comment]
D 大，没太看明白楼主讲的什么意思，这个特性能实现下面提的工作分区的效果吗？
https://github.com/siyuan-note/siyuan/issues/7611#issue-1616253259

**Comment by 88250** [comment]
@GH-W94 不支持页签分组，这个特性是将已有的页签和界面布局提供保存和加载。不过应该可以间接实现类似页签分组的效果，比如将一些常用的页签和当前界面状态保存为 `布局 1`，后续如果页签发生变化，也可以通过 `布局 1` 切换回来。
