### ISSUE TITLE
上线付费订阅

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#764]
* 付费订阅页面
* v1.0.0 发布前订阅享“早鸟”优惠价
  * ~￥96~￥64/年
  * 教育优惠 ~￥64~￥48/年
* 订阅期从 v1.0.0 发布后开始计算
* 教育优惠需要绑定 .edu.cn 邮箱

**Comment by leeyaunlong** [comment]
之前一次付费128的,还需要订阅吗?

**Comment by 88250** [comment]
> 之前一次付费128的,还需要订阅吗?

你好，￥128 是终身订阅买断（只有 512 个席位），现在这个是年付订阅，谢谢。

**Comment by L-09** [comment]
希望能够增加按照文件创建时间排序，一些按章节或特定知识点的文件会因为之后的文件引用导致浮上来，不利于复习。

**Comment by 88250** [comment]
@L-09 你好，请单独提 issue 谢谢。
