### ISSUE TITLE
书签和标签数据分离持久化

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7641]
从数据库中查询要等待之前的写入完成后才能查询到，耗时比较长。

考虑改进为书签和标签独立实现持久化存储：

* 数据索引
* 索引订正

**Comment by 88250** [comment]
@Yuminis98 老铁，我们技术评估了下，决定现阶段暂时还是不改了，主要是改进方案有一定影响稳定的风险，并且删除标签、书签功能目前来看不是非常高频的操作，从可用性上也能够接受。

虽然体验确实有待改进（就像你在[这里](https://github.com/siyuan-note/siyuan/issues/7154#issuecomment-1465217322)提到的），但是从开发计划和资源上看目前还是只能暂时放弃改进，等以后有机会再考虑了，抱歉抱歉。

**Comment by Yuminis98** [comment]
> @Yuminis98 老铁，我们技术评估了下，决定现阶段暂时还是不改了，主要是改进方案有一定影响稳定的风险，并且删除标签、书签功能目前来看不是非常高频的操作，从可用性上也能够接受。
> 
> 虽然体验确实有待改进（就像你在[这里](https://github.com/siyuan-note/siyuan/issues/7154#issuecomment-1465217322)提到的），但是从开发计划和资源上看目前还是只能暂时放弃改进，等以后有机会再考虑了，抱歉抱歉。

好的，理解，麻烦你了😊
