### ISSUE TITLE
页签支持到新窗口打开

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7645]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

发现页签右键有“移动到新窗口”选项，但没有“到新窗口打开”选项。移动是删除原来窗口页签移动到新窗口。有时候这个页签不想移动只想在新窗口再开一个。所以需要一个“到新窗口打开”选项。就是原窗口页签不变，在新窗口打开这个页签。
![image](https://user-images.githubusercontent.com/97731736/224614563-412dae8d-a398-4972-a1ee-ac8f902b7c3c.png)

### 描述可能的最优解决方案 Describe the optimal solution

1

### 描述候选的解决方案 Describe the candidate solution

1

### 其他信息 Other information

1

**Comment by 88250** [comment]
分屏以后再移动吧，稍微多加一个步骤顶顶。
