### ISSUE TITLE
docker版部署完成之后显示的是1.6.3的版本，是否可以更新到最新版？亦或者提供最新版更新文档？

### ISSUE THREAD

**Issue by lukelwai** [siyuan-note/siyuan#7646]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

安装完docker版本思源之后，发现里面的笔记版本可以用不过比较旧，连市场上的一些主题和最新的功能比如s3等都还没有支持，想着是否能够提供一下docker版本思源的更新方式？

### 期待的结果 Expected result

希望能够提供一下docker版本思源的更新方式？比如在文档里面加上这个

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

![image](https://user-images.githubusercontent.com/55864530/224633266-5f26b1c5-fc3e-4242-b9c6-36bc5b2d1853.png)

**Comment by mozhux** [comment]
你用的镜像源可能不对，论坛搜索一下解决方案

**Comment by 88250** [comment]
加版本号拉取试试  https://hub.docker.com/r/b3log/siyuan/tags

**Comment by lukelwai** [comment]
![image](https://user-images.githubusercontent.com/55864530/224635254-852d47b3-53e9-4861-bd0c-6266fe14ac04.png)
好的，谢谢各位，问题解决了需要制定版本号，直接拉latest拿到的版本应该是不对的，可能是标签没有处理好
