### ISSUE TITLE
代码片段设置界面用户体验优化

### ISSUE THREAD

**Issue by InEase** [siyuan-note/siyuan#7647]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

在代码片段的设置界面中的`textarea`在拖拽改变大小的时候，容易左右不对齐，同时也因为自带的语法检查，文本框里满地飘红，影响用户体验。

![image](https://user-images.githubusercontent.com/88016816/224634288-f9c3fcad-c219-4485-b813-2387926f6777.png)

### 期待的结果 Expected result

这个问题的解决比较简单（我就直接提PR啦），通过设置
```
style="resize: vertical" spellcheck="false"
```
就可以这个文本框只能竖向拓展，同时禁用语法检查，算是用户体验方面的一个小优化叭

### 版本环境 Version environment

```markdown
- Version: 2.7.9
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
欢迎 PR

**Comment by InEase** [comment]
哇哇哇D大好快的回复！第一次提PR，很激动 o(*////▽////*)q

**Comment by 88250** [comment]
感谢贡献，等 @Vanessa219 合并。
