### ISSUE TITLE
内容块标增加页签的分屏和新窗口打开功能

### ISSUE THREAD

**Issue by why8023** [siyuan-note/siyuan#7649]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

长文档或者容器块嵌套比较多的文档中, 加入此功能可以更快打开目标内容块进行查看, 修改, 对比等等,

### 描述可能的最优解决方案 Describe the optimal solution

在内容块标的菜单栏增加分屏和新窗口打开选项
<img width="414" alt="image" src="https://user-images.githubusercontent.com/22267652/224635449-df42e38d-7f61-4eeb-bae7-f638ee4ca58b.png">

### 描述候选的解决方案 Describe the candidate solution

目前使用页签的分屏也能实现, 但是步骤会多一点

**Comment by 88250** [comment]
感谢反馈，但是我们需要说明一下，内容块是不能分屏的，能分屏的是页签。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by why8023** [comment]
> 感谢反馈，但是我们需要说明一下，内容块是不能分屏的，能分屏的是页签。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

感谢回复, 明白您的意思, 其实内容块和文档块在一定条件是可以互通的, 这个功能本质上不是对内容块进行分屏, 其实应该是复制当前页签分屏或者新窗口打开, 然后聚焦到选择的内容块, 这样在长文档或者容器块嵌套比较多的文档就能快速对比和修改

不过, 我刚刚试了, 对文档先聚焦到 想要的内容块, 然后使用 页签的分屏 和 新窗口打开 功能, 发现其实是能够保持之前的 聚焦状态, 所以这个需求基本解决了

anyway, 谢谢啦
