### ISSUE TITLE
0.54更新后，文件名加了奇怪的后缀

### ISSUE THREAD

**Issue by LiWenGu** [siyuan-note/siyuan#765]
### 描述问题 Describe the problem

最新版文件名加了一堆后缀

### 期待的结果 Expected result

纯净的文件名

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/15909210/102436218-0aa54a80-4053-11eb-93e2-c5218aefd529.png)

### 版本环境 Version environment

* 版本 Version：0.54
* 操作系统 Operating system：Mac
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，054 做了 id 的移除，所以应该是因为升级没有成功。请按如下步骤：

1. 关闭所有思源前端界面
2. 等待 kernel 进程退出以后再重新安装一次

**Comment by heshang233** [comment]
![image](https://user-images.githubusercontent.com/13328402/102438356-14c94800-4057-11eb-9234-b1441271e4f5.png)
@88250 现在名字后面多了个'.md' 这也是新版本带来的变化么？

**Comment by 88250** [comment]
@heshang233 是的，目前的版本暂时不隐藏后缀，后面再看看是否需要调整，谢谢。

**Comment by 88250** [comment]
提主，我关闭了，如有问题请继续跟帖，谢谢。
