### ISSUE TITLE
多用户+笔记权限控制

### ISSUE THREAD

**Issue by wudigailun** [siyuan-note/siyuan#7652]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

虽然siyuan是一个，【个人】笔记，后续有没有考虑，增加，多用户+笔记权限控制。当然只作为公司内部使用。
这样，会有更多的人知道siyuan笔记。也间接的增加了推广，而且，confluse是商业的，如果国内搞一个开源的内部文档管理系统，那非常的不错。

### 描述可能的最优解决方案 Describe the optimal solution

作为公司内部wiki使用。类似confluse，因为siyuan的界面太爽了，并且可以http访问。

**Comment by 88250** [comment]
这个短期内不会考虑了，思源笔记主要定位还是个人知识管理系统，感谢提议。

**Comment by Soltus** [comment]
有好的方案欢迎PR至 [Sillot](https://github.com/Hi-Windom/Sillot/issues)
