### ISSUE TITLE
不支持配置坚果云 WebDAV 进行同步

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7657]
`cloud service unavailable`

* https://ld246.com/article/1678763787386
* https://ld246.com/article/1668134695314
* https://ld246.com/article/1676133067048
* https://ld246.com/article/1677458862564
* https://ld246.com/article/1668528076749
* https://github.com/siyuan-note/siyuan/issues/6543

为避免大家在这个上面浪费时间，程序会进行 `Endpoint` 校验，如果该配置项的值包含了 `dav.jianguoyun.com` 则提示：坚果云接口存在限制，请使用其他 WebDAV 服务。

---

具体限制详见坚果云官方帮助文档： https://help.jianguoyun.com/?p=2064

![image](https://user-images.githubusercontent.com/873584/224886162-544d0e67-7bd3-4d0b-84d1-9ad8d379a03e.png)

**Comment by PT123123** [comment]
那也得给用户好一点的提示吧..

**Comment by 88250** [comment]
@PT123123 配置 WebDAV 时如果地址填入坚果云的服务器地址 `https://dav.jianguoyun.com/dav/` 则会提示：

![image](https://github.com/siyuan-note/siyuan/assets/873584/87582e4f-e76e-40bc-b4bd-f8102c2245b8)

**Comment by Longlucky** [comment]
真无语，说禁就禁。那你搞个毛的功能特性？ 那在收费界面-WebDAV这一栏你写明白 不支持坚果云啊！  以前试用的时候正常，现在买了功能特性又用不了，真恶心

**Comment by Longlucky** [comment]
别全禁掉啊，给个提示只支持手动同步不行吗？  以前试用的时候正常，现在买了功能特性又用不了，收费界面，你又没写明不支持坚果云webdav

**Comment by Temacc0531** [comment]
> 别全禁掉啊，给个提示只支持手动同步不行吗？ 以前试用的时候正常，现在买了功能特性又用不了，收费界面，你又没写明不支持坚果云webdav

建议改用其他WebDAV服务，不是手不手动的问题，会不可预知出现问题
