### ISSUE TITLE
PDF 矩形标注支持默认颜色

### ISSUE THREAD

**Issue by LJpLJ** [siyuan-note/siyuan#7658]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候只是单纯标注，不需要设置颜色，就不用每次框选完都要用鼠标去确认颜色，效率很低

### 描述可能的最优解决方案 Describe the optimal solution

支持设置默认一种颜色，设置了之后，每次框选就不需选择颜色，
如需框选时选择颜色，可以多按ctrl

**Comment by 88250** [comment]
你指的是矩形标注吗？

**Comment by luo-chuan** [comment]
> 你指的是矩形标注吗？

我想楼主说的就是矩形标注，因为我也有这方面的困扰。

**Comment by 88250** [comment]
嗯，矩形标注的话我们考虑一下。

**Comment by 88250** [comment]
好的，我们后面一并处理。

**Comment by Vanessa219** [comment]
针对长按进行处理，但使用时还请确保焦点在 PDF 上。
