### ISSUE TITLE
提供删除文件 API

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#7678]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

插件系统需要卸载插件，移除本地的插件文件。

### 描述可能的最优解决方案 Describe the optimal solution

/api/file/removeFile，参数{ path: string, recursive: boolean, includeFolder: boolean }

**Comment by 88250** [comment]
> 参数{ path: string, recursive: boolean, includeFolder: boolean }

这里只传一个 path 就行了，如果传入的是文件夹路径，自动递归删除。
