### ISSUE TITLE
侧边栏和标签页显示错误

### ISSUE THREAD

**Issue by ericCHxia** [siyuan-note/siyuan#7679]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

标签页和侧边栏显示错误

### 期待的结果 Expected result

标签页和侧边栏正确地显示

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/52739449/225351866-4e8a44fd-197b-475a-825f-c06f0b71053e.png)

### 版本环境 Version environment

```markdown
- Version: v2.7.10
- Operating System: windows
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/10981411/siyuan.log)

**Comment by 88250** [comment]
请在默认主题下测试，如果是社区主题的问题，请到该主题的仓库上反馈，谢谢。
