### ISSUE TITLE
全局搜索卡顿问题

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#768]
### 描述问题 Describe the problem
12月16日发布的版本，搜索功能（点左上角搜索图标那个）有问题：表现为及其卡顿，kernel搜索瞬间可以占用90%以上的cpu，搜索结果延迟很久才能出现，而且不准确（可能只对应部分关键词）
-->

**Comment by 88250** [comment]
谢谢反馈，v0.5.41 会修复。

**Comment by roverway** [comment]
这回复太快了！！
