### ISSUE TITLE
思源不兼容幕布的行内代码

### ISSUE THREAD

**Issue by RocLoong** [siyuan-note/siyuan#7680]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

背景：我之前是使用的幕布，想要从幕布迁移到思源笔记，
问题：采用的是复制的方式，可能是因为幕布的格式的问题，所以复制过来后幕布的行内代码在思源中会变得加粗，而不是行内代码
幕布：
<img width="409" alt="image" src="https://user-images.githubusercontent.com/63897185/225484669-f8c20a9d-e6ea-4302-837d-91b960f81b4b.png">

思源的
<img width="404" alt="image" src="https://user-images.githubusercontent.com/63897185/225484599-da20c7a6-c246-49e3-a99f-5f164aef5783.png">

### 期待的结果 Expected result

我想知道这种可以兼容下吗？或者可以用脚本处理吗？

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
你好，思源仅支持通过 Markdown 导入数据，其他格式的话无法保证完全兼容。
