### ISSUE TITLE
使用第三方同步盘时弹出提示并退出内核

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7683]
* 工作空间不能放置在包含 `dropbox`、`google drive`、`onedrive`、`pcloud` 路径下
* 创建 data/.siyuan/filesys_status_check/ 文件夹，在其下随机创建 4K 数据大小的文件后重复尝试打开和重命名该文件，检测这个过程是否会被其他程序占用（Windows）
* 检查 data/.siyuan/filesys_status_check/ 下创建的随机文件的情况，大于一个说明可能是同步盘生成的冲突文件（Windows/Linux/macOS）

**Comment by GH-W94** [comment]
这下是不是“先暂停第三方同步盘，然后使用思源，关闭思源，最后再手动同步”这种使用方法也不能用了？

**Comment by woniuxia** [comment]
> 这下是不是“先暂停第三方同步盘，然后使用思源，关闭思源，最后再手动同步”这种使用方法也不能用了？

这个应该不影响，只要不是在思源使用期间使用第三方同步就行。

**Comment by Zuoqiu-Yingyi** [comment]
最好路径检查在 Electron 选择工作空间时进行，文件系统测试在内核中进行，这样侵入性就比较小了\~

**Comment by 88250** [comment]
> 最好路径检查在 Electron 选择工作空间时进行，文件系统测试在内核中进行，这样侵入性就比较小了~

路径会在安装初始化界面、主界面切换工作空间时也执行检查的。内核运行时也会定时检查路径和文件系统状态。

**Comment by Zuoqiu-Yingyi** [comment]
> 内核运行时也会定时检查路径和文件系统状态。
内核运行时检查路径的意义是啥❓

**Comment by 88250** [comment]
因为不知道用户啥时候开启的第三方同步盘的同步，比如已有的工作空间已经设置在同步盘路径下了，或者运行时加入了第三方盘同步。我们必须把影响第三方盘全面禁止掉，否则稳定性相关的问题很难排查。

**Comment by Zuoqiu-Yingyi** [comment]
> 比如已有的工作空间已经设置在同步盘路径下了

这在打开/切换工作空间时就已经校验过了, 因此无需再使用内核校验一次, 内核仅需要使用 `filesys_status_check` 方案进行校验即可

**Comment by 88250** [comment]
比如当前工作空间已经是 OD 路径了，没有调用打开/切换工作空间接口的，这时候就只能通过定时校验。

**Comment by Zuoqiu-Yingyi** [comment]
> 比如当前工作空间已经是 OD 路径了，没有调用打开/切换工作空间接口的，这时候就只能通过定时校验。

拉起内核前不能校验工作空间吗

**Comment by 88250** [comment]
能是能，但是也要给用户可以切换工作空间的机会。如果拉起前校验不过就进不了主界面，这样的话用户无法切换工作空间。

现在的定时校验是启动后 10m 才进行第一次校验。

**Comment by 88250** [comment]
这种不好用啊，每次启动用户都要选择。

**Comment by Zuoqiu-Yingyi** [comment]
> 这种不好用啊，每次启动用户都要选择。

可以默认打开上次关闭的工作空间，然后校验失败后回退到该页面即可，在认证界面也添加一个按钮退出内核并返回该页面，类似于 IDE

**Comment by 88250** [comment]
这样的改动相较于定时检查路径代价有点大，再说定时检查路径也没有副作用的。

**Comment by Zuoqiu-Yingyi** [comment]
> 这样的改动相较于定时检查路径代价有点大，再说定时检查路径也没有副作用的。

关键在于解耦，将打开工作空间拉起内核前所有的工作都抽取出来，而不是揉在一块，还是同时揉在两个地方

**Comment by 88250** [comment]
检查路径的代码实现本身就无法解耦，前端和内核都要单独实现一份。

**Comment by Zuoqiu-Yingyi** [comment]
> 检查路径的代码实现本身就无法解耦，前端和内核都要单独实现一份。

单独调用内核的用户应该不多见吧

**Comment by 88250** [comment]
这个问题我觉得不用纠结了，现在的实现在没有明显弊端的情况下应该是最优解了。

**Comment by why8023** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/22267652/226544423-29e88f75-6871-42c1-a94c-c1ad3d68fc7f.png">
请问, 我没有添加和删除操作, 这个文件数量的变化是和这个检查文件有关吗?

**Comment by 88250** [comment]
@why8023 和这个 issue 没有关系；可以对比快照看下具体变化。

**Comment by why8023** [comment]
> @why8023 和这个 issue 没有关系；可以对比快照看下具体变化。

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/22267652/226833627-232a52dd-f68b-4a72-ad64-882c791fc6ed.png">

您好, 我今天新建一个空库, 里面只添加了一个文档, 
其中:
1. 数据快照1是刚刚建好文档就创建的快照
2. 数据快照2是data/.siyuan/filesys_status_check/check_consistency_renamed文件夹出现时创建的快照
3. 数据快照3是data/.siyuan/filesys_status_check为空目录的时候创建的快照

测试期间我只对文档做了文字修改, 所以, 根据测试情况来看, 应该是check_consistency_renamed这个文件导致的问题

同时, 我也发现这个问题会导致这样的显示问题
<img width="612" alt="image" src="https://user-images.githubusercontent.com/22267652/226835387-d28f10d7-5145-4b2b-9c89-058de82041d1.png">

**Comment by xuhuanzy** [comment]
> 这下是不是“先暂停第三方同步盘，然后使用思源，关闭思源，最后再手动同步”这种使用方法也不能用了？

蚌埠住了, 还真不给用了, 直接检测目录将主流的同步盘全干掉, 只能自己编译或者写个定时计划同步咯

**Comment by Xiaobaishushu25** [comment]
> > 这下是不是“先暂停第三方同步盘，然后使用思源，关闭思源，最后再手动同步”这种使用方法也不能用了？
> 
> 蚌埠住了, 还真不给用了, 直接检测目录将主流的同步盘全干掉, 只能自己编译或者写个定时计划同步咯

我先暂停再打开还是弹这个，直接退出同步软件结果还弹😂

**Comment by Kiss-World** [comment]
@88250  没有使用同步盘仍然弹。使用的是nas每日定时同步备份，onedriver 也是每日定时同步到onedriver下。工作空间不再任何实时同步盘目录中。目前的体验就是，定时备份也不行了按

**Comment by 88250** [comment]
@Kiss-World 在思源运行期间只要有第三方软件读写工作空间数据就可能会提示，如果要定时备份的话正常退出思源以后再备份。

**Comment by Kiss-World** [comment]
> @Kiss-World 在思源运行期间只要有第三方软件读写工作空间数据就可能会提示，如果要定时备份的话正常退出思源以后再备份。
@88250 
我又看了下，我的定时它不是这个时间启动的，看了下可能是因为我使用的资源管理器是第三方资源管理器。它接管了的系统资源管理器。如果是因为这个，那确实无解了。
![image](https://github.com/siyuan-note/siyuan/assets/44720566/65c18d09-98ca-49cb-ae6d-e4b100bc6c4e)

**Comment by penzoe** [comment]
请问pcloud网盘如何同步思源笔记？设置了半天~
