### ISSUE TITLE
光标位于行级公式前后时无法使用 `Ctrl+/` 弹出输入框

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7685]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

光标在行内公式前后时使用快捷键 <kbd>Ctrl + /</kbd> 无法正常唤出行内公式编辑框, 此时控制台输出如下信息
```log
main.c6eaf19c4fbe32b13462.js:2293 Uncaught TypeError: Cannot read properties of null (reading 'replace')
    at zc (main.c6eaf19c4fbe32b13462.js:2293:1417)
    at Vc (main.c6eaf19c4fbe32b13462.js:2293:1711)
    at HTMLDivElement.<anonymous> (main.c6eaf19c4fbe32b13462.js:2293:12377)
```

### 期待的结果 Expected result

光标在行内公式前后时使用快捷键 <kbd>Ctrl + /</kbd> 可以正常弹出行内公式的编辑框

### 版本环境 Version environment

```markdown
- Version: 2.7.10
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出

**Comment by Vanessa219** [comment]
是这样操作么？无法重现
https://user-images.githubusercontent.com/970828/226079394-de614e1a-8d2e-4a37-9750-079c9ce175af.mp4

**Comment by Zuoqiu-Yingyi** [comment]
可能莫名其妙修复了，下个版本我再观察一下👀

**Comment by 88250** [comment]
有空的话帮忙试试 https://github.com/siyuan-note/siyuan/releases/tag/v2.8.0-dev2

**Comment by Zuoqiu-Yingyi** [comment]
> 有空的话帮忙试试 https://github.com/siyuan-note/siyuan/releases/tag/v2.8.0-dev2

这个版本已修复该问题
