### ISSUE TITLE
移动端能增加底部导航栏吗？

### ISSUE THREAD

**Issue by Timelesseternity** [siyuan-note/siyuan#7689]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

文档树的展开、笔记的查找和新建算是很常用的功能了。可以考虑放在底部导航栏的位置，更方便一些。

### 描述可能的最优解决方案 Describe the optimal solution

类似于Notion那样的设计。

**Comment by 88250** [comment]
你好，放在底部有点占位置，后面会支持滑动拉出左右栏 https://github.com/siyuan-note/siyuan/issues/7688 感谢反馈。
