### ISSUE TITLE
调整编辑器右侧边距

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7690]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当思源在小屏幕上分屏后，下图右侧的那两个箭头太影响选取文字操作了（即将光标移到行尾进行选取），光标很难移动到行尾，总是激活那两个箭头，很影响操作。
![image](https://user-images.githubusercontent.com/117154557/225924632-8a6b58a7-64d1-4faa-b9c1-c0bcfd00c3db.png)

### 描述可能的最优解决方案 Describe the optimal solution

希望能借鉴win10系统设置中滚动条样式（见下图），改进右侧的滚动条，将那两个烦人的箭头移到滚动条的上下两端。
![滚动条](https://user-images.githubusercontent.com/117154557/225923365-2cc070f5-d16c-4b49-a866-d9d60360d4ef.gif)
![滚动条](https://user-images.githubusercontent.com/117154557/225925134-1c26c41c-2c1c-4afb-8725-804e31fea9f6.gif)

**Comment by 88250** [comment]
没太明白为啥会影响选择操作，请录屏演示一下。

**Comment by GH-W94** [comment]
> 没太明白为啥会影响选择操作，请录屏演示一下。

如下图，我想把光标移到行尾“都”的后面，却总是激活那两个箭头，很难移过去
![两个箭头](https://user-images.githubusercontent.com/117154557/225927316-d5b308ed-80af-4b9a-afac-486ad8da17af.gif)

**Comment by 88250** [comment]
这个好像不是默认主题？

**Comment by GH-W94** [comment]
> 这个好像不是默认主题？

是默认主题

**Comment by 88250** [comment]
下个版本我们稍微调整一下边距，感谢反馈。

**Comment by GH-W94** [comment]
> 下个版本我们稍微调整一下边距，感谢反馈。

我记得之前有人反馈，已经调过一次了，目前看效果不理想，还是希望能考虑将那两个箭头挪个位置，或者干脆去掉。

在使用过程中，我是一次也没用过那两个箭头，想回文档开头或结尾时，都是直接拖动滚动条也是很方便，或按快捷键。

一键回文档开头和结尾这个场景我觉得也不是很常用的功能，没必要在那么明显地方占位置，而且在使用的其他软件中，也未见过有这个功能的箭头。

**Comment by 88250** [comment]
之前没有调整过这样的特例：

![image](https://user-images.githubusercontent.com/873584/225932847-3e43b834-ed32-4516-bce9-4a0416c0b520.png)

是否能调整还得 @Vanessa219 来评估一下。

箭头更符合新手使用习惯，这个也是很多用户反馈后我们才考虑加上去的。
