### ISSUE TITLE
点击带有层级的文件即可以打开也会展示层级(目前只有打开,层级没有自动展开)

### ISSUE THREAD

**Issue by funbinary** [siyuan-note/siyuan#7694]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

当前套多个层级时,每次都得准确点到>,那个位置挺小的,点起来挺不方便的,如果点击标题也能自动将其展开的话会省挺多事,每次点那个>,因为太小有时都没点到

### 描述可能的最优解决方案 Describe the optimal solution

点击标题时如果有层级也顺带调用下展开按钮

**Comment by 88250** [comment]
从主流设计看似乎没有这样设计的哦，因为这样的话如果只想打开文档但不想展开子文档怎么办？

**Comment by 88250** [comment]
目前来看，像 Notion 那样在父文档中显示子文档导航的设计较为妥当，思源也有类似计划，请参考 https://github.com/siyuan-note/siyuan/issues/2711

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
