### ISSUE TITLE
闪卡支持设置新卡上限

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7695]
https://ld246.com/article/1678973102779

**Comment by luo-chuan** [comment]
新卡应定义为当天新建的卡，而不是从未复习过的卡。
允许上限为0。

**Comment by luo-chuan** [comment]
建议再增加这样一个选项：当天新建的卡片自动搁置到第二天。
https://ld246.com/article/1678188149820

**Comment by 88250** [comment]
@luo-chuan 麻烦单独开 issue，谢谢。

**Comment by luo-chuan** [comment]
> @luo-chuan 麻烦单独开 issue，谢谢。

好的，已开新issue

**Comment by 88250** [comment]
拆分一下 https://github.com/siyuan-note/siyuan/issues/7703
