### ISSUE TITLE
闪卡复习时支持跳过

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#7697]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候对于不是那么急着掌握的卡片，可以跳过，放到队尾（也就是等其它卡片复习完了再复习跳过的卡片，如果今天不想复习了就关闭卡片复习窗口，相当于搁置到第二天了）。

### 描述可能的最优解决方案 Describe the optimal solution

目前 Anki [插件](https://ld246.com/forward?goto=https%3A%2F%2Fankiweb.net%2Fshared%2Finfo%2F1136455830)和 RemNote 提供了这一功能。
![](https://b3logfile.com/file/2023/03/image-E4wWtOL.png)
![](https://b3logfile.com/file/2023/03/image-CXj0ZLv.png)

原文链接： https://ld246.com/article/1678188149820

**Comment by 88250** [comment]
补充一下，我们实现的 `跳过` 是在本次复习中忽略，不是移动到本次复习的队尾。如果中途关闭复习界面的话，跳过缓存不会清空，这种情况下即使在打开复习界面，也不会出现这张卡了，除非重启思源。
