### ISSUE TITLE
建议新卡片自动搁置到第二天

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#7698]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

这里说的新卡片指当天新建的卡片，而不是从未复习过的卡片。对于今天新建的卡片，希望明天才复习，也就是自动搁置到第二天。

### 描述可能的最优解决方案 Describe the optimal solution

目前 anki 提供了这一选项。（电脑上很久没用过 anki 了，下图是手机上截的）
 ![](https://b3logfile.com/file/2023/03/image-NiV0ZLC.png)

原文链接： https://ld246.com/article/1678188149820

**Comment by 88250** [comment]
这个使用场景好像很局限，比如为什么是第二天不是第三天？

**Comment by Soltus** [comment]
我希望是隐藏三小时内的新卡片

**Comment by 88250** [comment]
支持跳过应该会更灵活 https://github.com/siyuan-note/siyuan/issues/7697 

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
