### ISSUE TITLE
打开某些 PDF 文件时缺失部分内容

### ISSUE THREAD

**Issue by ws198601** [siyuan-note/siyuan#7699]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

打开由ppt转来的pdf文件时，部分页的内容没有显示，但是文字其实还在的，且可以复制并粘贴出来。见下边的截图

而且不是百分百出现的，比如我的pdf文件由188页，其中只有几个页面出现这个问题。

### 期待的结果 Expected result

pdf页面可以正常显示内容

### 截屏或者录屏演示 Screenshot or screen recording presentation

用其他pdf软件打开的效果
![image](https://user-images.githubusercontent.com/4425067/226089281-7d45d3c2-e6c0-439d-976f-31241270f9c4.png)

思源笔记中打开的效果：
![image](https://user-images.githubusercontent.com/4425067/226089314-ab29cfee-4e1a-4541-b038-664b008456b5.png)

思源笔记中是可以选中的，选中的效果如下图：
![image](https://user-images.githubusercontent.com/4425067/226089344-9886bcba-9bf2-4b06-bbdf-fbbb721e8f9a.png)

### 版本环境 Version environment

```markdown
- Version: 2.7.10
- Operating System: win10 10.0.19045版本
- Browser (if used): 没有用浏览器打开
```

### 日志文件 Log file

无

**Comment by 88250** [comment]
请试下直接将该 PDF 拖入浏览器能否正常浏览。

**Comment by 88250** [comment]
另外，这里也帮忙试下 https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by ws198601** [comment]
> 
这个在浏览器是可以。
浏览器是 Google Chrome
Chrome 已是最新版本
版本 111.0.5563.65（正式版本） （64 位）

![image](https://user-images.githubusercontent.com/4425067/226096572-0dd1b61b-1118-4a40-ad81-c0b979a50f98.png)

**Comment by ws198601** [comment]
> 另外，这里也帮忙试下 https://mozilla.github.io/pdf.js/web/viewer.html

这个文章在思源里需要看哪页呢，我截图了一个，看着是正常的。同样的位置在我的浏览器中显示也ok的。 
![image](https://user-images.githubusercontent.com/4425067/226096817-8e134e4a-6087-47cb-83f9-9c3db057a4e0.png)

**Comment by 88250** [comment]
能把 PDF 发给我们一下吗？ 845765@qq.com

**Comment by ws198601** [comment]
> 能把 PDF 发给我们一下吗？ [845765@qq.com](mailto:845765@qq.com)
嗯嗯，好的。我这发送。

**Comment by ws198601** [comment]
> 能把 PDF 发给我们一下吗？ [845765@qq.com](mailto:845765@qq.com)

已经通过邮箱发送了，麻烦D大查收下。

**Comment by 88250** [comment]
已经收到，谢谢。
