### ISSUE TITLE
部分提高编辑效率的建议

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#770]
1. 选中多段文字，点击按钮或使用快捷键，批量转为列表。目前这样操作后，还是只对第一段生效。
2. 选中多段或者一行内部分文字，输入**自动加粗，输入==自动标记黄色。
3. 支持将带缩进的有序或者无序列表转化为脑图功能
4. 反正都是使用自己的markdown渲染引擎了，干脆自定义一种支持合并单元格的语法吧，有这个一定增色不少。比如<<表示本单元格与左侧单元格合并，^^表示本单元格与上方单元格合并（只是建议，没有深思）。就算其他渲染引擎不支持导出的md文件，其实也不太影响可读性。
5. 增加一次批量导出选定文件或整个文件夹下的全部文件为md文件功能。目前的保存后自动导出其实用处不太大。

**Comment by 88250** [comment]
1. 请关注  https://github.com/siyuan-note/siyuan/issues/132
2. 请用快捷键
3. 请关注 https://github.com/siyuan-note/siyuan/issues/735
4. 请关注 https://github.com/88250/lute/issues/97

感谢建议。

**Comment by 88250** [comment]
我关闭了，如果还有建议请继续跟帖，谢谢。
