### ISSUE TITLE
支持配置闪卡

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7704]
新增 设置 - 闪卡 配置界面，支持进行如下设置：

* [ ] https://github.com/siyuan-note/siyuan/issues/7695
* [ ] https://github.com/siyuan-note/siyuan/issues/7703
* [ ] https://github.com/siyuan-note/siyuan/issues/7701
* [ ] https://github.com/siyuan-note/siyuan/issues/7702

**Comment by 88250** [comment]
先关闭了，这个 issue 主要用于任务拆分，具体进度请关注拆分好的 issues。

**Comment by zxhd863943427** [comment]
经过又一段时间的测试，发现卡包制卡目前只有一个是文档树制卡无法替代的了，那就是嵌入块中的卡片。被嵌入后，这些卡片依然只能在原有位置才能查看和安排间隔重复。

我估计这个挺难的，但是确实是一个需求，也是我目前唯一不得不转向卡包制卡的需求。
