### ISSUE TITLE
New function for texts

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#7705]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Forgive me if this function exists and I haven't discovered it yet...
But it would be very useful for my studies to have the option to leave all words in uppercase. When opening the text selection box, it would be great to have the option to leave the text in uppercase or lowercase.
You could use simple ones like: "AA" and "aa"

Example: I would like **new** text function / I would like **NEW** text function

### 描述可能的最优解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/90691302/226110090-fb7c3371-dac4-4a21-a269-0532ff99b3f8.png)

Add here icons or text to choose from.

**Comment by 88250** [comment]
Hello, this feature is not recommended for consideration. There are two main reasons:

* Less usage scenarios
* Some languages are case insensitive

Thanks.
