### ISSUE TITLE
支持应用内配置人工智能

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7714]
支持在 设置 - AI 中配置接入 OpenAI API。

如果之前配置了环境变量 https://github.com/siyuan-note/siyuan/issues/7560 则启动新版本后自动读取并迁移到应用内设置。

**Comment by HowcanoeWang** [comment]
考虑后续各家都会出API之后，还应该有不同的AI的配置与切换功能(如设置文心一言为默认AI，类似于云存储的配置与切换那样的设置栏目)

**Comment by 88250** [comment]
嗯，已经考虑在内了，目前接入的是 OpenAI。

**Comment by noean** [comment]
请问配置之后显示  Requesting failed, please check kernel log for more details v2.8.6

**Comment by zhangjunhua** [comment]
> 请问配置之后显示 Requesting failed, please check kernel log for more details v2.8.6

同样的问题

**Comment by shallerpan** [comment]
我也是同样的问题，无法链接怎么回事，我用obsidian就可以啊

**Comment by shallerpan** [comment]
请问配置之后显示 Requesting failed, please check kernel log for more details v2.8.6
