### ISSUE TITLE
删除代码块类型后，候选栏不会消失

### ISSUE THREAD

**Issue by jenkinchang** [siyuan-note/siyuan#772]
### 描述问题 Describe the problem

删除代码块类型后，候选栏不会消失，点击空白区域也不会消失

### 截屏或录屏演示 Screenshot or screen recording presentation

![py](https://user-images.githubusercontent.com/74193006/102493835-b7f97c00-40ae-11eb-8c5a-237ed430b0ac.gif)

### 版本环境 Version environment

* 版本 Version：0.5.4
* 操作系统 Operating system：20H2
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，类似问题还比较多，请暂时先用 Esc 顶顶，后续我们会统一进行改进，谢谢。
