### ISSUE TITLE
浏览器扩展无法保存表格，但复制表格可以再保存到剪藏页面中

### ISSUE THREAD

**Issue by ccxuy** [siyuan-note/siyuan#7720]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

浏览器扩展无法保存表格，但复制表格可以再保存到剪藏页面中

### 期待的结果 Expected result

浏览器剪藏可以保存表格

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: Windows
- Browser (if used):Chrome
```

### 日志文件 Log file

NA

**Comment by 88250** [comment]
我先关闭了，如果有信息补充请跟帖，谢谢 :pray:

**Comment by ccxuy** [comment]
浏览器扩展是这个：
https://github.com/siyuan-note/siyuan-chrome
表格是内部网页，不过我测试了下，大概差别是<table>标签外侧多了<div class="doc-table-edit-scorll"><div class="slimScrollBar">两个标签。
