### ISSUE TITLE
Support `alt+[` to enter default characters when no text is selected

### ISSUE THREAD

**Issue by verymilan** [siyuan-note/siyuan#7721]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

Hi there, sorry if this is a duplicate, searching though chinese is quite a challenge for me. :)
I can't type letters/symbols like `[|{}]` because the number row is already occupied by UI navigation shortcuts using the `opt` key. This problem affects me with my QWERTZ keybloard in both, macOS and PC modes. This also means that i can't quickly link text, because i can't access that shortcut on my keyboard. **Normally i would just select text (in Obsidian/Logseq) and type `[` which then automatically creates a link.**

### 期待的结果 Expected result

The numberrow should not be blocked, there should at least be presets for easily changing SiYuan to the proper keymap, because now, my only option is to manually dig though all the keybindings and trying to find the offenders.

### 版本环境 Version environment

```markdown
- Version: 2.7.10
- Operating System: macOS Big Sur
- Browser (if used): Firefox (for the Docker image)
```

### 日志文件 Log file

not aplicable

**Comment by 88250** [comment]
Hello, I didn't understand the problem you encountered, is it impossible to type the symbol `[`?

**Comment by verymilan** [comment]
Yes, also any other symbol that requires that option key is overidden by the default layout. On top of this, when i navigate with the keyboard, i cannot jump from word to word because command+arrowkey also does some custom focus action. I am limited to jumping from beginning to end of the line.

**Comment by Vanessa219** [comment]
I'm not sure what you mean, please try after upgrading.
