### ISSUE TITLE
导出 Markdown 时在文档头添加 YFM 开关

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7727]
@88250 导出 Markdown 时在文档头添加 metadata 能否使用一个开关控制, 我有一些文档块自定义属性需要一块导出, 所以打算搞一个挂件专门对 metadata 进行管理, 此时需要关闭内置的 metadata 导出功能

_Originally posted by @Zuoqiu-Yingyi in https://github.com/siyuan-note/siyuan/issues/6880#issuecomment-1477199163_

该设置项默认不启用。

**Comment by Zuoqiu-Yingyi** [comment]
@88250 API `/api/export/exportMdContent` 的响应内容貌似不受该开关的控制, 这属于 🎨  还是 🐛 呀❓

**Comment by 88250** [comment]
@Zuoqiu-Yingyi API 也需要？

**Comment by 88250** [comment]
好的。
