### ISSUE TITLE
移动端无法打开

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7729]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

几个版本移动端没有更新，想着更新一下。没有覆盖更新，直接卸载下新版本安装的。可是安装后跳出一个要求同意页面点击后，就一直显示灰底思源图标界面进不去。

小米手机、MUI系统、安卓版本8.0，思源版本：2.7.10。进不去后打开后台发现两个思源后台预览页面，一个是白屏，一个是灰底思源图标的。

### 期待的结果 Expected result

正常使用

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image_320](https://user-images.githubusercontent.com/97731736/226509882-ad8d3d67-49f1-4fde-93b7-b5f18d8e845c.png)

### 版本环境 Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11024713/siyuan.log)

**Comment by Soltus** [comment]
安卓8.0是上古神机了吧

**Comment by UFDXD** [comment]
哪有那么夸张，日常使用没问题，思源支持7.0+

**Comment by Soltus** [comment]
因为思源就套了webview，申请的权限都是0，自然可以做到。

**Comment by 88250** [comment]
升级一下最新版，应该已经解决。

**Comment by UFDXD** [comment]
好的

**Comment by UFDXD** [comment]
白屏窗口自动消失了，灰的那个还在。还是进不去

**Comment by 88250** [comment]
卸载重现安装试试。

**Comment by 88250** [comment]
如果还是不行，估计只能更新下 WebView 了。

**Comment by UFDXD** [comment]
不行

**Comment by 88250** [comment]
WebView 的版本是？

**Comment by UFDXD** [comment]
62.0.xxx

**Comment by 88250** [comment]
这个实在太老了，至少要升级到 66 以上。

**Comment by 88250** [comment]
我关闭这个 issue 了，感谢反馈。
