### ISSUE TITLE
Export to mhtml

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#773]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

mht 是聚合HTML文档、Web档案或单一文件网页。单个文件网页可将网站的所有元素(包括文本和图形)都保存到单个文件中。

当导出为 html 时，如果要分享给他人，如果内含本地图片，往往还有一个 assets 文件夹需要同 html 分享，对于某些分享路径，就需要将 assets 文件夹和 html 文件压缩到一个 zip，分享和查看都麻烦。

而导出为 mht 后，整个文档 + 资源只有一个文件，直接分享，直接就能用浏览器打开，而且分享后的查看效果是与在思源笔记中的效果最接近的。

**Comment by 88250** [comment]
放到后期一点考虑，谢谢。

**Comment by 88250** [comment]
导出通用格式还是导出 PDF 或者 Word 比较好，因为即使导出 mhtml 还是依赖在线 js/css，我关闭了，感谢建议。
