### ISSUE TITLE
AIChat问题：create chat completion failed: error, status code: 404

### ISSUE THREAD

**Issue by geosmart** [siyuan-note/siyuan#7731]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

AI Chat环境变量已配置。
```
SIYUAN_OPENAI_API_KEY="sk-xxx"
SIYUAN_OPENAI_API_TIMEOUT=60
SIYUAN_OPENAI_API_BASE_URL="https://service-xxx-xxx.sg.apigw.tencentcs.com/release"
```

对话框输入文本后，taost提示报错：Requesting failed, please check kernel log for more details

### 期待的结果 Expected result

正常请求openai接口

### 版本环境 Version environment

```markdown
- Version: 2.7.10,AppImage
- Operating System: Ubuntu 20.04.5 LTS
- Browser (if used):chrome
```

### 日志文件 Log file

E 2023/03/21 11:29:03 openai.go:64: create chat completion failed: error, status code: 404, message: Invalid URL (POST /chat/completions)

**Comment by geosmart** [comment]
可以了，是我地址配置的不对,少了个/v1

SIYUAN_OPENAI_API_BASE_URL="https://service-xxx-xxx.sg.apigw.tencentcs.com/release/v1"

**Comment by 88250** [comment]
好的。
