### ISSUE TITLE
桌面端设置访问授权后退出应用时抛出异常

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7736]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

在退出应用时(右键托盘图标>退出应用; 访问授权界面>退出应用)出现如下异常

![image](https://user-images.githubusercontent.com/49649786/226528120-45cab347-9f51-499a-9b40-90c2a4bac153.png)

### 期待的结果 Expected result

捕获/排除该异常

### 版本环境 Version environment

```markdown
- Version: 2.8.0
- Operating System: Windows 11 22H2 22621.1413
- Browser (if used):
```

### 日志文件 Log file

内核正常退出, 主进程无日志输出

**Comment by pizixi** [comment]
我也出现了，我用的是dark+主题

**Comment by Zuoqiu-Yingyi** [comment]
关联: https://ld246.com/article/1679386499317

**Comment by 88250** [comment]
不开访问授权的话退出正常吗？
