### ISSUE TITLE
PDF连续框注标注支持

### ISSUE THREAD

**Issue by Aurora-eng** [siyuan-note/siyuan#7737]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

PDF阅读

### 描述可能的最优解决方案 Describe the optimal solution

希望PDF可以支持连续标注，每次都要点一次标注框才能标注，感觉很麻烦。类似WPS或者bookxnote那样的连续框选标注或者高亮笔标注都可

**Comment by 88250** [comment]
使用快捷键即可重复上次的画框标注。
