### ISSUE TITLE
PDF annotation do not follow zoom

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7740]
https://ld246.com/article/1679390564828

pdf.js v3.4.120 的 bug，得等它发布新版以后才能解决。

**Comment by a-bean-sprout** [comment]
PDF深度用户表示很难过

**Comment by whuwangyong** [comment]
> PDF深度用户表示很难过

我之前用的2.7.2版本是没问题的，可以先考虑用老版本顶一段时间
