### ISSUE TITLE
希望在人工智能操作选单中增加原文发送功能

### ISSUE THREAD

**Issue by mrl998** [siyuan-note/siyuan#7742]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

比如我想通过聊天对答的形式使用AI，在文档里写好了一个问题，要将其发送给AI。
在现版本思源笔记里需要这么操作：复制问题，另起一段输入/AI Chat唤出对话框，把我的问题粘贴到对话框里再发送。
这样操作繁琐，而且问题文本会在文档里重复出现两次。

### 描述可能的最优解决方案 Describe the optimal solution

希望能在操作选单中增加原文发送功能，像使用翻译、续写等功能一样直接点击使用。

**Comment by 88250** [comment]
嗯，自定义操作是一次性的，没有上下文。

这两个暂时只能选其一顶顶。
