### ISSUE TITLE
数据同步忽略用于文件系统检查的文件

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7744]
> @why8023 和这个 issue 没有关系；可以对比快照看下具体变化。

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/22267652/226833627-232a52dd-f68b-4a72-ad64-882c791fc6ed.png">

您好, 我今天新建一个空库, 里面只添加了一个文档, 
其中:
1. 数据快照1是刚刚建好文档就创建的快照
2. 数据快照2是data/.siyuan/filesys_status_check/check_consistency_renamed文件夹出现时创建的快照
3. 数据快照3是data/.siyuan/filesys_status_check为空目录的时候创建的快照

测试期间我只对文档做了文字修改, 所以, 根据测试情况来看, 应该是check_consistency_renamed这个文件导致的问题

同时, 我也发现这个问题会导致这样的显示问题
<img width="612" alt="image" src="https://user-images.githubusercontent.com/22267652/226835387-d28f10d7-5145-4b2b-9c89-058de82041d1.png">

_Originally posted by @why8023 in https://github.com/siyuan-note/siyuan/issues/7683#issuecomment-1479056752_

**Comment by why8023** [comment]
感谢开发者关注这个问题, 我发现history文件夹下面也会有这些文件, 这个也会一起和这个issue解决了吗?
<img width="428" alt="image" src="https://user-images.githubusercontent.com/22267652/226867330-e425783d-4e9e-4aec-9ff7-abf341ac21d8.png">

**Comment by 88250** [comment]
谢谢提醒，会一并解决。
