### ISSUE TITLE
支持应用内删除模板

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7746]
![image](https://user-images.githubusercontent.com/873584/226876359-8549413f-47c3-4480-ad9e-01eef3c984f2.png)

先解决删除模板这个需求吧，其他的继续尽力而为。

**Comment by LeeOswald368** [comment]
两个人又写程序又当客服，每个星期一个版，高强度肝代码。
接受自己的不完美，对别人的不完美足够挑剔。
要求人十全十美，享受相应的权益/便利，又不想付出。
发邮件者本人看起来挺搞笑的。

**Comment by 5kyfkr** [comment]
y1s1，删除模板确实是个用得到的功能，文件夹的模板路径选择应该也能直接调用模板文件夹下所有的模板就更方便了
