### ISSUE TITLE
重启后窗口大小恢复默认问题

### ISSUE THREAD

**Issue by paiooocn** [siyuan-note/siyuan#7755]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

如下两行代码一直使用screen的width和height, 没有将windowState的width和height读入使用.
https://github.com/siyuan-note/siyuan/blob/f83a07fb062683bef4807128b0820cda4696ef1f/app/electron/main.js#L189-L190
将代码改为下面的形式, 能够在下次打开程序时套用上次的windowState的width和height.
```js
        defaultWidth = oldWindowState ? oldWindowState.width : screen.getPrimaryDisplay().size.width;
        defaultHeight = oldWindowState ? oldWindowState.height: screen.getPrimaryDisplay().workAreaSize.height;
```

### 期待的结果 Expected result

请在后续版本修正此问题, 谢谢.

### 版本环境 Version environment

```markdown
- Version: 2.8.0
- Operating System: Windows 10
- Browser (if used):
```

### 日志文件 Log file

[app.log](https://github.com/siyuan-note/siyuan/files/11048407/app.log)

**Comment by 88250** [comment]
我这里重现不了问题，后面的代码会进行覆盖：

![image](https://user-images.githubusercontent.com/873584/227182206-6489cdc8-ac62-4967-8d17-bb326a5af9fc.png)

**Comment by 88250** [comment]
这是增加两句调试日志的输出：

![image](https://user-images.githubusercontent.com/873584/227189137-3764e6ef-4a71-4382-8c42-d11124bda1e8.png)

所以我觉得问题可能不是出在读取上。

你那里可以试下退出以后打开 windowState.json 看下是否已经持久化。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by paiooocn** [comment]
我输出了windowState, 和你说的一样, windowState加载了oldWindowState的数据.
发现在下面的代码里, 条件为真时使用了defaultWidth, defaultHeight
https://github.com/siyuan-note/siyuan/blob/f83a07fb062683bef4807128b0820cda4696ef1f/app/electron/main.js#L207-L212

我输出了workArea和windowState的width, height
```js
    const windowState = Object.assign({}, {
        isMaximized: true,
        fullscreen: false,
        isDevToolsOpened: false,
        x: 0,
        y: 0,
        width: defaultWidth,
        height: defaultHeight,
    }, oldWindowState);
    writeLog("windowStat: width " + windowState.width + ", height: " + windowState.height)
    writeLog("workArea: width " + workArea.width + ", height " + workArea.height)
```
```log
2023-03-24 01:56:54 got kernel port [58392]
2023-03-24 01:56:54 ui version [2.8.0], booting kernel [C:\Users\Yimo\AppData\Local\Programs\SiYuan\resources\kernel\SiYuan-Kernel.exe --port 58392 --wd C:\Users\Yimo\AppData\Local\Programs\SiYuan\resources]
2023-03-24 01:56:54 booted kernel process [pid=7716, port=58392]
2023-03-24 01:56:54 checking kernel version
2023-03-24 01:56:54 got kernel version [2.8.0]
2023-03-24 01:56:55 windowStat: width 1152, height: 1040
2023-03-24 01:56:55 workArea: width 1920, height 1040
2023-03-24 01:57:06 exited ui
```
返回的`workArea.height==windowState.height`, 
此条件生效`if (windowState.width >= workArea.width || windowState.height >= workArea.height)`, 
导致windowState.width, windowState.height被赋值defaultWidth, defaultHeight.

你可以将窗口高度拉到最大试试看能否重现. 我调小高度到1000后, 窗口大小正常了.

条件改为`>`后, 可以修正这个问题.
```js
if (windowState.width > workArea.width || windowState.height > workArea.height) { 
```

**Comment by 88250** [comment]
确实是这个问题，感谢指正，下个版本修复。
