### ISSUE TITLE
更新部分关闭/移除图标为圆形

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7756]

**Comment by Zuoqiu-Yingyi** [comment]
当文档标签与文档题头图同时存在时, 鼠标悬浮在文档标签上会快速闪烁
![思源笔记-bug反馈-46](https://user-images.githubusercontent.com/49649786/227770571-6064eba0-0f50-47c4-aaa3-05a878a87e8b.gif)
