### ISSUE TITLE
Graphviz作图时，CPU占用率高

### ISSUE THREAD

**Issue by Weijee** [siyuan-note/siyuan#7757]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

Graphviz作图时，CPU占用率高
![image](https://user-images.githubusercontent.com/13539500/227233896-77b0d7eb-f0d1-4c40-ab96-ded3a8198255.png)

在官方提供的画图工具中不会出现这个问题
![image](https://user-images.githubusercontent.com/13539500/227235056-bd574c33-b671-431e-990b-72e1560ea588.png)

### 期待的结果 Expected result

CPU使用正常

### 版本环境 Version environment

```markdown
- Version: v2.7.10
- Operating System: windows11
- Browser (if used): edge
```

### 日志文件 Log file

W 2023/03/23 22:19:37 blocktree.go:436: save block tree [size=92 kB] to [/siyuan/workspace/temp/blocktree], elapsed [2.73s]
E 2023/03/23 22:19:37 block_query.go:507: query scan field failed: database disk image is malformed
    github.com/siyuan-note/siyuan/kernel/sql.scanBlockRow(0x1b55975?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/block_query.go:507 +0x27d
    github.com/siyuan-note/siyuan/kernel/sql.GetBlock({0xc0010820d8?, 0x16?})
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/block_query.go:568 +0xbe
    github.com/siyuan-note/siyuan/kernel/sql.QueryRefsByDefID({0xc0010820d8, 0x16}, 0x0)
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/block_ref_query.go:353 +0x6b
    github.com/siyuan-note/siyuan/kernel/sql.GetRefsCacheByDefID({0xc0010820d8, 0x16})
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/cache.go:91 +0x1c5
    github.com/siyuan-note/siyuan/kernel/model.refreshDynamicRefText(0xc003c1c150, 0x0?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1106 +0x109
    github.com/siyuan-note/siyuan/kernel/model.(*Transaction).commit(0xc0054560f0)
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1061 +0xd4
    github.com/siyuan-note/siyuan/kernel/model.performTx(0xc0054560f0)
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:229 +0x5cd
    github.com/siyuan-note/siyuan/kernel/model.flushTx()
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:105 +0xdd
    github.com/siyuan-note/siyuan/kernel/model.FlushTxJob()
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:93 +0x17
    github.com/siyuan-note/siyuan/kernel/job.every.func1(0x2faf080?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/job/cron.go:54 +0x3e
    github.com/siyuan-note/siyuan/kernel/job.every(0xc0017fa3f0?, 0xc00045f7b8?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/job/cron.go:55 +0x37
    created by github.com/siyuan-note/siyuan/kernel/job.StartCron
    	/go/src/github.com/siyuan-note/siyuan/kernel/job/cron.go:38 +0x7d
    
E 2023/03/23 22:19:39 block_query.go:507: query scan field failed: database disk image is malformed
    github.com/siyuan-note/siyuan/kernel/sql.scanBlockRow(0x1b55975?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/block_query.go:507 +0x27d
    github.com/siyuan-note/siyuan/kernel/sql.GetBlock({0xc0013a0918?, 0x16?})
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/block_query.go:568 +0xbe
    github.com/siyuan-note/siyuan/kernel/sql.QueryRefsByDefID({0xc0013a0918, 0x16}, 0x0)
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/block_ref_query.go:353 +0x6b
    github.com/siyuan-note/siyuan/kernel/sql.GetRefsCacheByDefID({0xc0013a0918, 0x16})
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/cache.go:91 +0x1c5
    github.com/siyuan-note/siyuan/kernel/model.refreshDynamicRefText(0xc001c80840, 0x0?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1106 +0x109
    github.com/siyuan-note/siyuan/kernel/model.(*Transaction).commit(0xc002000780)
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:1061 +0xd4
    github.com/siyuan-note/siyuan/kernel/model.performTx(0xc002000780)
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:229 +0x5cd
    github.com/siyuan-note/siyuan/kernel/model.flushTx()
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:105 +0xdd
    github.com/siyuan-note/siyuan/kernel/model.FlushTxJob()
    	/go/src/github.com/siyuan-note/siyuan/kernel/model/transaction.go:93 +0x17
    github.com/siyuan-note/siyuan/kernel/job.every.func1(0x2faf080?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/job/cron.go:54 +0x3e
    github.com/siyuan-note/siyuan/kernel/job.every(0xc0017fa3f0?, 0xc00045f7b8?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/job/cron.go:55 +0x37
    created by github.com/siyuan-note/siyuan/kernel/job.StartCron
    	/go/src/github.com/siyuan-note/siyuan/kernel/job/cron.go:38 +0x7d
    
I 2023/03/23 22:19:57 queue.go:153: database op tx [15905ms]
E 2023/03/23 22:24:30 database.go:1174: commit tx failed: database disk image is malformed
      github.com/siyuan-note/siyuan/kernel/sql.commitHistoryTx(0x1912ba0?)
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/database.go:1174 +0x45
    github.com/siyuan-note/siyuan/kernel/sql.FlushHistoryQueue()
    	/go/src/github.com/siyuan-note/siyuan/kernel/sql/queue_history.go:89 +0x468
    reflect.Value.call({0x189c040?, 0x1c064d0?, 0x6f207c2020202020?}, {0x1ab3da2, 0x4}, {0x2eb8e78, 0x0, 0xc002103f88?})
    	/usr/local/go/src/reflect/value.go:586 +0xb07
    reflect.Value.Call({0x189c040?, 0x1c064d0?, 0x0?}, {0x2eb8e78?, 0x0?, 0x0?})
    	/usr/local/go/src/reflect/value.go:370 +0xbc
    github.com/siyuan-note/siyuan/kernel/task.execTask.func1()
    	/go/src/github.com/siyuan-note/siyuan/kernel/task/queue.go:207 +0x3e
    created by github.com/siyuan-note/siyuan/kernel/task.execTask
    	/go/src/github.com/siyuan-note/siyuan/kernel/task/queue.go:206 +0x358
    
E 2023/03/23 22:24:31 queue_history.go:90: commit tx failed: database disk image is malformed

### 更多信息 More information

docker部署v2.7.10

**Comment by 88250** [comment]
从内核日志报错看数据库文件已经损坏，建议重建索引以后再试试。

浏览器 CPU 高的话可能是因为还有其他内容需要渲染，不一定是 Graphviz 渲染的占用。先把第一个问题解决以后再观察看看，谢谢。
