### ISSUE TITLE
建议在锁屏页添加切换工作空间的按钮

### ISSUE THREAD

**Issue by caohongliang92** [siyuan-note/siyuan#7759]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

需要在启动时快速打开其他的工作空间

### 描述可能的最优解决方案 Describe the optimal solution

**在锁屏页面新增一个切换工作空间的按钮，以便快速切换工作空间，不需要输入密码进入不想要的工作空间后再进行切换**
![image](https://user-images.githubusercontent.com/48972121/227398574-c5d9eebc-b285-4767-8fbd-a26bde8ce1e9.png)

**Comment by 88250** [comment]
这也的话会降低安全性，可以在没有授权的情况下创建工作空间或者查看工作空间相关信息。

桌面端可以创建不同的桌面快捷键方式来启动不同的工作空间，具体使用方式请参考用户指南工作空间章节。
