### ISSUE TITLE
当文档名称以 emoji 图标开头时取代默认图标

### ISSUE THREAD

**Issue by scvoet** [siyuan-note/siyuan#776]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

文件树中查看文档名称时。

### 描述最优的解决方案 Describe the optimal solution

当文档名称以 emoji 开头时，使用 emoji 代替原先默认的 markdown 图标。此举可以一定程度上缓解千篇一律的 markdown 图标所造成的审美疲劳，并可以提高信息密度。

**Comment by 88250** [comment]
谢谢建议，考虑了一下还是决定先关闭了，后续可能会和自定义手动排序一起考虑。
