### ISSUE TITLE
思源笔记不能启动

### ISSUE THREAD

**Issue by acidgl8757** [siyuan-note/siyuan#7760]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

上个月还以正常使用，最近电脑想用的时候发现打不开了，用官网的最新版本也不能打开

### 期待的结果 Expected result

app可以正常启动

### 版本环境 Version environment

```markdown
- Version: v2.8.0
- Operating System: win10
- Browser (if used):
```

### 日志文件 Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11057555/siyuan.log)

### 更多信息 More information

最近安装了ps 和 开源软件He3
我的另外一个电脑也有一样的问题，启动中然后感觉像是crash了，siyuan.log看下日期不是最新的日期，感觉crash 的log没有保存进去，请提供本地 crash 输出的log的地址，请联系acidgl8757@gmail.com

**Comment by 88250** [comment]
另外，我注意到你日志中好像是把工作空间放到了 OneDrive 下，思源不支持使用任何第三方同步盘同步数据，v2.8.0 开始会做路径判断，使用的话会弹出警告对话框并退出内核进程。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by acidgl8757** [comment]
我安装老版本并且换了安装目录，理论上不会启动原来的笔记路径，但依然不能启动

**Comment by acidgl8757** [comment]
![image](https://user-images.githubusercontent.com/4157318/227815136-db534aca-67a6-4180-ab01-6cc23e3e9ac2.png)

**Comment by acidgl8757** [comment]
这个是 由于其他软件安装导致影响 思源笔记了么，需要什么log，我可以协助上传

**Comment by acidgl8757** [comment]
@88250 麻烦再跟进一下

**Comment by acidgl8757** [comment]
[app.log](https://github.com/siyuan-note/siyuan/files/11073549/app.log)

**Comment by 88250** [comment]
试下在 cmd 中执行：

```
D:\ProgramFiles\SiYuan\resources\kernel\SiYuan-Kernel.exe --port 4306 --wd D:\ProgramFiles\SiYuan\resources
```

**Comment by acidgl8757** [comment]
执行完后，再次打开软件，发生的error还是一样

**Comment by 88250** [comment]
执行完以后 cmd 的输出截个图吧。

**Comment by 88250** [comment]
另外，请上传一下这个文件 `C:\Users\用户名\.config\siyuan\workspace.json`

**Comment by acidgl8757** [comment]
![image](https://user-images.githubusercontent.com/4157318/227820720-e0bdf87f-b621-46f0-875b-41b995b2f484.png)

**Comment by acidgl8757** [comment]
[workspace.zip](https://github.com/siyuan-note/siyuan/files/11073804/workspace.zip)
你解压缩一下

**Comment by 88250** [comment]
把 workspace.json 删除，正常启动一下试试。

**Comment by acidgl8757** [comment]
十分感谢，删除后可以正常启动了

**Comment by 88250** [comment]
工作空间不要放在 OneDrive 里……

**Comment by acidgl8757** [comment]
好的，以后会注意了

**Comment by acidgl8757** [comment]
@88250 最后想问下，思源笔记的访问互联网的方式，有计划改成 类似Qt Maintenance Tool访问互联网那种通过web浏览器设置来访问的方式么？
因为在公司有代理的情况下，Notation或者Qt Maintenance Tool这种软件，如果web浏览器的代理账号密码通过了就可以访问互联网了，但是感觉 思源笔记是 直连互联网的方式，没有办法通过web浏览器的代理认证来上网，比较不方便。
我本来已经买了会员，但是没办法在公司环境同步。

**Comment by 88250** [comment]
设置 - 关于 - 网络代理

**Comment by acidgl8757** [comment]
@88250 【设置 - 关于 - 网络代理】这里面必须是要知道ip和端口号，没有办法直接依存web设置
Notion或者Qt Maintenance Tool 通过web上网的时候，是不用关心具体ip和端口号的，只要公司内部通过工号/密码登录代理，代理内部是web浏览器可以上网，user是不知道具体ip和端口的。

**Comment by 88250** [comment]
如果是系统代理的话默认应该就可以，但是如果支持浏览器代理的话不行。

**Comment by acidgl8757** [comment]
比如
eclipse的 软件市场
Notion或者Qt Maintenance Tool
都走的是 浏览器代理

思源笔记有可能通过源码访问网路api的更改来实现么，本来打算研究下源码，最近时间比较忙还没来得及看。

**Comment by 88250** [comment]
这个我就不太清楚了……
