### ISSUE TITLE
修改日记默认存储路径后，批量修改已有日记的文档名

### ISSUE THREAD

**Issue by svchord** [siyuan-note/siyuan#7768]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

修改日记默认存储路径后，以前的日记需要手动修改文档名，非常麻烦

### 描述可能的最优解决方案 Describe the optimal solution

修改日记默认存储路径后，自动批量修改已有日记的文档名

**Comment by 88250** [comment]
这个支持不了，只能手动修改了。
