### ISSUE TITLE
[FeatureRequest] Being able to choose a custom directory for our workspace on mobile.

### ISSUE THREAD

**Issue by Cyber-Syntax** [siyuan-note/siyuan#7772]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

It's really helpful for me to maintenance docs. It's very reliable way to backup locally.

### 描述可能的最优解决方案 Describe the optimal solution

It is available in the desktop version.

### 描述候选的解决方案 Describe the candidate solution

I just want to store my notes in my documents folder.

**Comment by Soltus** [comment]
@Soltus Useful and necessary

**Comment by leolee9086** [comment]
that's useful for some people as i know

**Comment by Soltus** [comment]
> that's useful for some people as i know

6

**Comment by terwer** [comment]
+1 i need this feaure too

**Comment by 88250** [comment]
We are very sorry, we will not consider providing this feature, the main reason is that once it is provided, the risk of data corruption caused by using third-party synchronization software cannot be controlled.

**Comment by Soltus** [comment]
不能采取类似桌面端检测同步盘的方式吗？ @88250

**Comment by 88250** [comment]
@Soltus 类 Linux 系统上不存在文件占用，检测不了。

**Comment by Soltus** [comment]
好吧，我在汐洛分支自己实现好了，自用就不需要考虑安全性了

**Comment by Cyber-Syntax** [comment]
> We are very sorry, we will not consider providing this feature, the main reason is that once it is provided, the risk of data corruption caused by using third-party synchronization software cannot be controlled.

Are you doing this so we don't use third-party sync software? Simply telling the user using this feature that there is such a risk is actually quite sufficient.

**Comment by Soltus** [comment]
Agree. The default path is too deep, not only inconvenient for users, but also troublesome for theme debugging.

**Comment by Cyber-Syntax** [comment]
Ok, but when i sync i can't use webdav because siyuan freezes the network. Probably my router is causing this. Anyway, can you tell me how to sync my notes locally via snychting to automate it?

**Comment by 88250** [comment]
Settings - Sync, using S3 as the cloud storage provider. Please don't use any sync software based on the filesystem, it will cause data corruption.
