### ISSUE TITLE
你好,希望能增加portable版

### ISSUE THREAD

**Issue by netforfreedom** [siyuan-note/siyuan#7773]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

便携,重装系统方便

### 描述可能的最优解决方案 Describe the optimal solution

把配置文件放到安装目录下

### 其他信息 Other information

谢谢.想你致敬

**Comment by 88250** [comment]
这个暂时不考虑了，感谢提议。

**Comment by Soltus** [comment]
可以自行编译

**Comment by fwzuw** [comment]
如果你使用的是 **windows 系统**，可以使用 **Scoop** 包管理器安装便携版思源，需要科学上网。

### 打开 powershell 并设置策略
如果系统不低于 win10，右键 windows 菜单，选择 Windows PowerShell 打开
运行命令`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`，设置策略以允许安装
如果系统低于 win10，可能需要检查一下 powershell 版本并升级到 5.0 及以上，这里不展开

### 更改安装路径（可选）
用户安装的程序和 scoop 默认位于 C:\Users\\<user\>\scoop，如需更改请使用以下命令，将 D:\Scoop 替换为你想要的路径
```
$env:SCOOP='D:\Scoop'
[Environment]::SetEnvironmentVariable('SCOOP', $env:SCOOP, 'User')
```
全局安装的程序（–global）默认位于 C:\ProgramData\scoop，如需更改请用打开 Windows PowerShell（管理员）使用以下命令，将 D:\Scoop_Global 替换为你想要的路径
```
$env:SCOOP_GLOBAL='D:\Scoop_Global'
[Environment]::SetEnvironmentVariable('SCOOP_GLOBAL', $env:SCOOP_GLOBAL, 'Machine') 
```
### 安装 Scoop
运行命令`iwr -useb get.scoop.sh | iex`安装 Scoop

### 安装思源
首先需要添加桶，如果你的电脑上没有安装 git，先运行`scoop install git`安装 git
运行命令`scoop bucket add extras`以添加官方 extras 储存桶，这里面有思源
运行命令 `scoop install siyuan-note`安装思源

#### 安装特定版本的思源
`scoop install siyuan-note@2.8.0`

#### 切换到特定版本
`scoop reset siyuan-note@2.7.6`
#### 切换回最新版本（在思源上似乎有问题）：
`scoop reset siyuan-note`

### 更新思源
`scoop update siyuan-note`

### 安装更多……
你可以在 https://scoop.sh/ 方便地搜索更多的便携应用，只需先添加桶，再安装即可。如果搜索结果较少，可在筛选中取消勾选 仅官方桶。
