### ISSUE TITLE
改进 Windows 端第三方同步盘检测

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7777]
查询 工作空间/data/ 属性，如果返回不为空的话说明该文件在同步盘路径下。

**Comment by Soltus** [comment]
希望可以解决误杀问题

**Comment by 88250** [comment]
> 希望可以解决误杀问题

那个应该已经解决了 https://github.com/siyuan-note/siyuan/issues/7744

**Comment by Soltus** [comment]
> > 希望可以解决误杀问题
> 
> 那个应该已经解决了 #7744

没有

**Comment by 88250** [comment]
你描述一下问题吧。

**Comment by Soltus** [comment]
> 请描述一下问题和重现步骤。

日志记录：
```log
filelock.go:135: write file 某个文件.tmp Access is denied.
````

**Comment by 88250** [comment]
估计是有其他软件正在访问文件导致的，检查一下吧。

**Comment by Soltus** [comment]
出现类似文件写入操作错误应该是无法预测和完全避免的。我觉得文件系统读写错误不应该作为内核退出的依据，希望可以通过其他方式避免文件冲突，或者用更准确和友好的判断机制告知用户。

**Comment by 88250** [comment]
这个是数据安全的基础，一旦文件写入报错就退出内核，没有补救方案的。

**Comment by Soltus** [comment]
用户数据可以理解，`recent-doc.json` 这种配置文件就没有必要了吧

**Comment by 88250** [comment]
这个也是用户数据的，记录了最近打开的文档。

**Comment by 88250** [comment]
其他配置数据同样重要，整个文件系统必须可用，否则报错以后无法排查问题，也无法恢复数据。

**Comment by Zuoqiu-Yingyi** [comment]
最好不要使用该方案, 这个调用行为很敏感...

**Comment by 88250** [comment]
> 强烈建议不要使用该方案, 这个调用行为很敏感...

稍后将 PowerShell 实现更换为 https://github.com/go-ole/go-ole
