### ISSUE TITLE
Windows10 安装更新后任务栏固定被取消

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#7779]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

从2.8.0正式版开始，更新安装后任务栏上固定的思源会被取消，需要重新固定到任务栏，2.8.0-dev3及之前的安装没有影响不会取消任务栏上的软件图标固定

### 期待的结果 Expected result

安装更新不会取消任务栏图标固定

### 截屏或者录屏演示 Screenshot or screen recording presentation

![安装更新任务栏固定被取消](https://user-images.githubusercontent.com/54146035/227714359-8c1850c1-aba5-45fd-94cf-ede00e4e728a.gif)

### 版本环境 Version environment

```markdown
- Version: 2.8.1-dev1
- Operating System: windows10
- Browser (if used):
```

### 日志文件 Log file

[siyuanlog.txt](https://github.com/siyuan-note/siyuan/files/11068701/siyuanlog.txt)

**Comment by UltramarineSky** [comment]
有时安装后还在固定在任务栏中，有时候又被取消固定

**Comment by Yuminis98** [comment]
是的，我电脑里面其他的软件更新以后，都不会从任务栏退出，
为啥就是思源会取消固定？
是因为使用的技术不一样吗？

**Comment by 88250** [comment]
这个目前没有办法解决，之前尝试过 https://github.com/siyuan-note/siyuan/issues/3773
