### ISSUE TITLE
内容块嵌入编辑时内容不保存

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#778]
内容块嵌入，编辑输入后，还没点保存，内容就先刷没了，然后自动结束编辑，并会出现如下图的提示
输入的内容有时能保存一部分，有时就都没保存，甚至遇到原先有的内容也没了
![image](https://user-images.githubusercontent.com/13896259/102583939-79140680-4140-11eb-990e-9e46e825e475.png)

版本：0.5.41

**Comment by 88250** [comment]
你好，编辑的块是普通的段落块还是？

**Comment by xulei-shl** [comment]
> 你好，编辑的块是普通的段落块还是？

普通文本, 无序列表 都测试过,都有问题. 另, 群里也有人反馈遇到同样的问题
