### ISSUE TITLE
左侧面板栏是否可以支持钉住一些操作

### ISSUE THREAD

**Issue by ad56583964** [siyuan-note/siyuan#7784]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

自己会把碎片的信息收集和想法先放到"周记里面"(因为不太适应日记较深的层级)，在文件多了之后每次回到“这一周”按下“+”号都需要翻找一下
![image](https://user-images.githubusercontent.com/20683103/227792257-fc970285-026e-4b9c-85e6-9b0f73efc5cc.png)

### 描述可能的最优解决方案 Describe the optimal solution

希望可以有一个快捷栏为其添加一些快捷操作入口

**Comment by 88250** [comment]
这个暂时不考虑了，需要等 #5066 完成以后再看情况，谢谢。
