### ISSUE TITLE
Avoid page jump after folding a header block

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7785]
* https://ld246.com/article/1678363717605
* https://ld246.com/article/1679836826296
* https://ld246.com/article/1682345198083

**Comment by HowcanoeWang** [comment]
The page jump also happens if the pages contains too many images, when redirected from the "cross-ref blocks"
当从块引用的链接跳转到一个有很多图片的文档时，图片加载完毕后也会触发页面跳动，等待图片加载完毕后，再从块引用链接跳转才不会出现

**Comment by 88250** [comment]
@HowcanoeWang 图片的高度似乎无法计算。

**Comment by HowcanoeWang** [comment]
> @HowcanoeWang 图片的高度似乎无法计算。

可以参考打字机模式，强制从块引用跳转的块在屏幕中间垂直居中？

**Comment by HowcanoeWang** [comment]
> @HowcanoeWang 对于图片加载的情况目前没有好的解决方案，因为图片加载完以后会把高度撑高，导致定位不准。

有没有可能通过给图片块记录高度信息，然后加载的时候先把高度计算好，用空白块先把图片“撑”起来，然后后续再把图片显示出来？

**Comment by 88250** [comment]
这个方案不行的，因为实际渲染大小是自适应界面大小的，高度会随着界面大小变化而变化，无法计算出绝对位置。

**Comment by HowcanoeWang** [comment]
> 这个方案不行的，因为实际渲染大小是自适应界面大小的，高度会随着界面大小变化而变化，无法计算出绝对位置。

我的想法是，图片渲染的显示逻辑修改一下，在元信息中记录图片的高宽比之后（而不是高度的具体像素），根据页面大小，先计算出图片容器的大小，然后图片后续只能在这个容器里加载出来

**Comment by Vanessa219** [comment]
只要是加载都会抖动
