### ISSUE TITLE
支持导出 PDF 书签大纲

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#779]
导出PDF，目录无法点击跳转

希望如果md有目录，在导出pdf时保留目录的点击跳转

**Comment by 88250** [comment]
收到，后续试着调整看看，谢谢。

**Comment by roverway** [comment]
https://www.jianshu.com/p/722b56b4c5c7

我验证过了，这个方法导出的效果很好。
不知道这个小功能点是否可以提前安排？

**Comment by 88250** [comment]
@roverway 提前不了……

**Comment by 88250** [comment]
@roverway 刚刚试了下，使用思源导出 HTML 再通过 wkhtmltopdf 转换 PDF 可以带书签，但是整体效果不大好。估计还是只能自己先加个 ToC 在顶部先，书签搞不定。

**Comment by roverway** [comment]
> @roverway 刚刚试了下，使用思源导出 HTML 再通过 wkhtmltopdf 转换 PDF 可以带书签，但是整体效果不大好。估计还是只能加个 ToC 在顶部，书签搞不定。

我之前尝试过把思源笔记导出的民法典html版本用这个转成pdf，感觉还不错。
不过民法典样式比较简单，只有标题和段落，我没尝试其他格式复杂的html文件，不知道导出效果怎么样。
你是尝试了复杂样式的html了吗？

**Comment by 88250** [comment]
我试了较为绚丽多彩的例子

![image](https://user-images.githubusercontent.com/873584/132616880-265d2ff2-1ebc-4a8f-a7af-a9c23c95ffe8.png)

我们找到其他方案了，正在开发。

**Comment by aibudanxing** [comment]
您好，请问具体怎么操作呢，现在不支持用TOC，导出为pdf时怎么根据标题生成目录呢

**Comment by 88250** [comment]
> 您好，请问具体怎么操作呢，现在不支持用TOC，导出为pdf时怎么根据标题生成目录呢

直接导出即可，文档内的大纲会自动转换为 PDF 书签。

**Comment by aibudanxing** [comment]
好的，十分感谢！
