### ISSUE TITLE
启动时移除处于网盘路径下的工作空间

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7790]
只是移除配置，不会删除数据。

**Comment by mozhux** [comment]
！！！这个操作太恐怖了，建议报错后弹窗，移除工作空间打开（不删除数据），退出程序，这样选

**Comment by 88250** [comment]
我没看明白恐怖的点，老铁细说。

**Comment by leolee9086** [comment]
妈耶 选择工作空间那里标记一下然后不让打开就可以了吧

**Comment by 88250** [comment]
@leolee9086 这个 issue 处理的是工作空间已经位于网盘的，不然还是陆续会有 https://github.com/siyuan-note/siyuan/issues/7760 这样的问题出现。

**Comment by mozhux** [comment]
> 我没看明白恐怖的点，老铁细说。

主要是用户没有感知，然后打开发现工作空间没了， 啥提示都没，第一反应不就是丢数据？

**Comment by leolee9086** [comment]
> @leolee9086 这个 issue 处理的是工作空间已经位于网盘的，不然还是陆续会有 #7760 这样的问题出现。

我知道，我的意思是还是把它列出在那里，给一个警告标记提示这个空间有问题，点击的时候不是打开，而是给出处理建议

**Comment by 88250** [comment]
那我们用工作空间网盘报错那个弹框提示用户如何？

**Comment by 88250** [comment]
但是还是要移除配置路径，不然用户每次启动都是报错弹框，无法进入主界面切换工作空间的。

**Comment by Zuoqiu-Yingyi** [comment]
最好再给个一键迁移工作空间目录的功能，将工作空间复制到选择的正常目录下

**Comment by leolee9086** [comment]
因为从用户的操作来看， 发现工作空间少了之后，这个操作的交互流程就断掉了，他无法快捷而且明确的知道自己现在面临的是什么样的情况， 后续有怎么样的处理方案。保留工作空间的列示，但是在点击之后不是打开而是弹窗，能够让这个操作流程继续下去，减少失控感

**Comment by 88250** [comment]
> 最好再给个一键迁移工作空间目录的功能，将工作空间复制到选择的正常目录下

这个我怕出问题（包括现在的导出 Data），因为有的用户文件系统上权限不正确，无法保证文件完整复制 :joy:

**Comment by leolee9086** [comment]
> 最好再给个一键迁移工作空间目录的功能，将工作空间复制到选择的正常目录下

这个不一定需要，因为这样可能会给用户一种心理暗示；软件给出的提示指向性越强，用户感受到的软件本身的“目的性”也就越强，就算要能够迁移，这个过程用户也必须能够选择迁移到的位置之类

**Comment by leolee9086** [comment]
如果一键迁移到一个软件本身默认的目录的话，用户会怀疑这个目录的特殊性并进一步怀疑这样做的目的

**Comment by Zuoqiu-Yingyi** [comment]
> 这个我怕出问题（包括现在的导出 Data），因为有的用户文件系统上权限不正确，无法保证文件完整复制 :joy:

文件系统权限有问题确定能正常使用吗👀

**Comment by 88250** [comment]
不能的，回弹文件系统错误那个报错 。

**Comment by 88250** [comment]
先这样处理吧：

1. 剔除工作空间配置
2. 弹文件系统报错框并退出内核

**Comment by mozhux** [comment]
主要还是思源的提示没有指导正确的使用方式，按目前的操作，可预见的未来论坛又是一堆骂声，所以对于这个我建议：
1.报错退出界面
2.给出两个选项，1.退出程序，2.导出data删除工作空间配置，3.重新设置工作空间的教程

**Comment by Soltus** [comment]
> 先这样处理吧：
> 
> 1. 剔除工作空间配置
> 2. 弹文件系统报错框并退出内核

既然选择统一退出内核处理，那么得提供对应的帮助措施吧。现在内核频繁退出，用户看着只有大概提示的窗口一脸懵逼，弱小无助可怜

**Comment by 88250** [comment]
> 主要还是思源的提示没有指导正确的使用方式，按目前的操作，可预见的未来论坛又是一堆骂声，所以对于这个我建议： 1.报错退出界面 2.给出两个选项，1.退出程序，2.导出data删除工作空间配置，3.重新设置工作空间的教程

在判断是网盘的情况下做任何文件系统的操作很危险，退出内核是目前已知最为稳妥的处理。

**Comment by Zuoqiu-Yingyi** [comment]
> 在判断是网盘的情况下做任何文件系统的操作很危险，退出内核是目前已知最为稳妥的处理。

复制文件操作的危险程度较低

**Comment by 88250** [comment]
这个 issue 已经是在修正问题了，如果再引入问题就更麻烦了。

**Comment by mozhux** [comment]
目前的操作肯定是引入更多问题，至少会有一系列因为口径不一样以为数据丢失的问题，比如工作空间配置，普通用户哪知道配置是啥。。就以为是数据啊。

**Comment by 88250** [comment]
你说的也有道理，那还是不加入这个校验了，明天回滚代码。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月27日(周一) 下午4:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 启动时移除处于网盘路径下的工作空间 (Issue #7790)




 
目前的操作肯定是引入更多问题，至少会有一系列因为口径不一样以为数据丢失的问题，比如工作空间配置，普通用户哪知道配置是啥。。就以为是数据啊。
