### ISSUE TITLE
Support import from logseq

### ISSUE THREAD

**Issue by mawek** [siyuan-note/siyuan#7791]
### In what scenarios do you need this feature?

I'd like to be able to migrate data from logseq go siYuan seamlessly.

### Describe the optimal solution

Although siYuan allows import from markdown, it doesn't interpret its content as logseq does. 
Import should correctly parse and interpret metadata - backlinks, block references, page/block tags, aliases, attributes, block embedes,...

**Comment by 88250** [comment]
Sorry, we cannot support the import of private formats, only the standard Markdown format.

**Comment by nhan000** [comment]
@mawek SiYuan now official supports Sync outside of mainland China and you can also import Wikilink in [2.9.3](https://github.com/siyuan-note/siyuan/releases/tag/v2.9.3)

**Comment by rishacha** [comment]
@nhan000 @88250 - Block refs are still messing up. Can we look at modifying logic in `import.go` just to include block-refs too?
