### ISSUE TITLE
搜索时提供选项“包含可读路径”

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#7792]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

因为很多时候子文档的名称有一部分已经在可读路径中有体现，就像硬盘中的文件夹路径一样。否则子文档名容易变得冗长。

在搜索软件Everything中也可以选择【匹配路径】，即同时搜索路径名和文件名。

### 描述可能的最优解决方案 Describe the optimal solution

在搜索窗口可以勾选 【包含可读路径】或 【匹配路径】

### 描述候选的解决方案 Describe the candidate solution

sql 应该可以做到吧

**Comment by 88250** [comment]
这个暂时不考虑了，建议用 SQL 查询 `hpath` 字段。

后期如果需要的人多，我们再重新打开考虑，谢谢。
