### ISSUE TITLE
什么时候会上wolai中类似模板库导入并编辑使用

### ISSUE THREAD

**Issue by ma123456mai** [siyuan-note/siyuan#7798]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

有时候自己建立或使用目前模板不够方便便捷

### 描述可能的最优解决方案 Describe the optimal solution

有类似 flowus wolai  notion类似的模板库引入对应模板 后进行自我编辑使用等

**Comment by 88250** [comment]
这个一直都有，可以在社区集市中下载模板，也可以将自己的文档导出为模板。
