### ISSUE TITLE
导出完成提示自动关闭

### ISSUE THREAD

**Issue by xulei-shl** [siyuan-note/siyuan#780]
![image](https://user-images.githubusercontent.com/13896259/102583753-33efd480-4140-11eb-8e75-41f2fb88f859.png)

如果所示，界面最上端的提示信息，一直存在，只能人工点击关闭。个人希望是自动关闭的

**Comment by jenkinchang** [comment]
+1

**Comment by xulei-shl** [comment]
不仅仅是导出PDF提示, 错误提示也会一直存在,如#778截图中的提示信息也会一直存在

**Comment by 88250** [comment]
错误提示是因为要方便截图或者复制，所以需要手动关闭哦。
