### ISSUE TITLE
打扰下。你们把移动端斜杠调出那个取消了吗？

### ISSUE THREAD

**Issue by xp12047** [siyuan-note/siyuan#7801]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

我平时习惯用输入/调出功能，现在没有了啊？安卓版本。

### 描述可能的最优解决方案 Describe the optimal solution

我不知道什么情况，输入斜杠加我需要没反应了

**Comment by Temacc0531** [comment]
使用屏幕下方工具栏最左边的+号

**Comment by xp12047** [comment]
> 使用屏幕下方工具栏最左边的+号

我是真的不理解你们是怎么想的。以前我只要输入/link它就直接出来了现在我确要先点击加号再挨个翻着找你们觉得这很好用吗？有意思？大佬你们牛逼
