### ISSUE TITLE
退出软件报错

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#7802]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/37429029/228138949-dc800586-8a29-4f2f-a3ba-d20263fa3219.png)

### 期待的结果 Expected result

想知道报错的原因

### 版本环境 Version environment

```markdown
- Version: 最新
- Operating System: win
- Browser (if used):
```

### 日志文件 Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11085750/system-log.zip)

**Comment by 88250** [comment]
这个报错应该是安装时候的报错吧？请参考这里 https://ld246.com/article/1678285508141
