### ISSUE TITLE
Embedded block content in-place editing

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#7804]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

Embedding blocks is a great feature to structure your notes. However often I would like to edit the embedded block in-place without opening an extra window for editing the content.

I can see that sometimes it is useful to edit the embedded blocks origin content document to get more context like upper document levels but on the other hand most often you really just want to edit simply a typo or something small where the popup window is an additional click inside the new editing window and it's cluttering the screen.

### 描述可能的最优解决方案 Describe the optimal solution

What I wanted to suggest is to change this behavior or make it customizable to the user how clicking on embedded blocks will work:

* option to allow to edit the embedded block just in-place without opening an additional edit window
  *  maybe a new keyboard shortcut or ctrl+alt+click could trigger the extra editing window
* option to allow to open an extra window where more block context can be displayed (like today's default behavior)

You can find a similar feature in LogSeq or Roam Research embedded block editing which is in-place as the default (however I'm not too familiar with both applications).

### 描述候选的解决方案 Describe the candidate solution

None

### 其他信息 Other information

This is not a priority one feature request.

**Comment by 88250** [comment]
In addition, Ctrl+Click on the block icon can open a new tab.
