### ISSUE TITLE
ld246.com is down?

### ISSUE THREAD

**Issue by nhan000** [siyuan-note/siyuan#7808]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

As in the title, the website is down.

### 期待的结果 Expected result

Should be up. I'm trying to access the story of the origin of SiYuan which was accessible yesterday.

### 截屏或者录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/85216095/228387604-69af86a3-84b0-4c18-ad84-0b8e611b0178.png)

### 版本环境 Version environment

```markdown
N/A (not applicable)
```

### 日志文件 Log file

N/A

**Comment by leolee9086** [comment]
yeah  there maybe some problem  ，D said thay'll try to fix it

**Comment by 88250** [comment]
Thanks for the feedback, it has just been fixed.

We are still investigating the specific reasons and hope that the subsequent operation will be more stable.
