### ISSUE TITLE
中文支持

### ISSUE THREAD

**Issue by leolee9086** [siyuan-note/siyuan#7814]
### 在什么情况下你需要该特性？In what scenarios do you need this feature?

作为一个母语是中文的用户，我的英语水平很差，但是为了了解开发进度和使用软件中遇到的问题，必须要到GitHub仓库翻阅issue，才能够完整的满足这一需求。

as a native chinese speaker，i can not read english fluently；but ，for me just myself ，this repo is important way to keep focus with the develop progress and to have a better scence about where those bugs may wait for me 。

目前思源的社区对中国用户非常友好，但是仅仅通过社区无法完全满足我的这一需求。

just by now ，ld246.com is still frindly to chinese user ，but only with this community my purpose cannot be  satisfied。

所以建议改善GitHub仓库件对中文的支持，毕竟中文是一种国际化语言， 中国市场对软件的发展也十分重要，已经有用户提出GitHub仓库的issue全部是英文难以阅读。

so i suggest here that the GitHub repo should be more frindly to chinese user too；by the reason  Chinese is a internal language too and Chinese market may also have some  importance to siyuan-note‘s development ， and there are by just now  someuser （including me）have trouble reading those pure English issue tittles

### 描述可能的最优解决方案 Describe the optimal solution

可能保留双语是一个更好地解决方案，用户可以用自己习惯的语言提出issue ，然后把那些重要的翻译成英语。

may double language be a better solution，users can use there own language in issues，and just translate those important one to double language 。

### 其他信息 Other information

如果我表现得不够友好， 在此请求原谅，但我仍然认为我提出的语言问题至少对我个人而言是比较重要的。

if I  have made myself  looks rudely ，please forgive me 。I can say sorry  but i still really think those thing i said above is important just for me。

**Comment by zxhd863943427** [comment]
强烈支持

**Comment by 88250** [comment]
对于目前正在进行的国际化支持来说使用双语是一种阻碍，一来是没有那么多精力翻译，二来是额外信息太多。

中文社区已经有官方讨论区链滴进行支持了，也有其他基本成型的用户社区组织（比如 QQ 群），所以其实 issues 上还是应该使用英文，这也是我们能做的最大努力了。

感谢老铁们的理解和支持。

**Comment by svchord** [comment]
支持，希望D大还是再考虑一下

**Comment by AugustTuan** [comment]
> 对于目前正在进行的国际化支持来说使用双语是一种阻碍，一来是没有那么多精力翻译，二来是额外信息太多。
> 
> 中文社区已经有官方讨论区链滴进行支持了，也有其他基本成型的用户社区组织（比如 QQ 群），所以其实 issues 上还是应该使用英文，这也是我们能做的最大努力了。
> 
> 感谢老铁们的理解和支持。

不过就反馈issue来说，还是github的体验最好， 反馈也是最及时的。

**Comment by AugustTuan** [comment]
看来得为了思源，好好学英语了

**Comment by luo-chuan** [comment]
可否开个gitee项目，专门用中文反馈？这样也避免用户魔法上网了。

**Comment by luo-chuan** [comment]
开个gitee项目，issue用中文，其中重要的issue再关联到github上用英文

**Comment by luo-chuan** [comment]
或者这样。另外开一个github项目，专门用于中文issue交流。并在主项目的readme和issue页面置顶提醒用中文交流移步至某链接。

**Comment by Yuminis98** [comment]
@Vanessa219  V姐劝劝D大

**Comment by Yuminis98** [comment]
还是建议这种重大改变，可以抛出一个话题，让大家充分讨论，看调研结果再进行抉择，不要这么迅速就落地了。

**Comment by Yuminis98** [comment]
给人一种一觉醒来就变天了的不安全感

**Comment by 88250** [comment]
> 或者这样。另外开一个github项目，专门用于中文issue交流。并在主项目的readme和issue页面置顶提醒用中文交流移步至某链接。

这个似乎是一个可行的方案。

**Comment by HowcanoeWang** [comment]
> > 或者这样。另外开一个github项目，专门用于中文issue交流。并在主项目的readme和issue页面置顶提醒用中文交流移步至某链接。
> 
> 这个似乎是一个可行的方案。

或者启用Github discussion呗，天生就是用来作为论坛使用的。所有的中文和英文反馈都在这里(用语言tag区分)，issue只作为更新log使用，不负责特性提议和bug咨询

![image](https://user-images.githubusercontent.com/19968935/228704096-a3deeceb-53b0-427f-bd59-7fa50f9d55ba.png)

**Comment by Soltus** [comment]
单开一个仓库无论对谁都会带来额外的心智负担

**Comment by 88250** [comment]
> 或者启用Github discussion呗，天生就是用来作为论坛使用的。所有的中文和英文反馈都在这里(用语言tag区分)，issue只作为更新log使用，不负责特性提议和bug咨询
> 
> ![image](https://user-images.githubusercontent.com/19968935/228704096-a3deeceb-53b0-427f-bd59-7fa50f9d55ba.png)

这样的话会和已有链滴的功能重合，分散管理的精力。

**Comment by 88250** [comment]
> 单开一个仓库无论对谁都会带来额外的心智负担

对于反馈提议者来说应该没有心智负担，我们会负责移动 issue 的操作。

**Comment by Vanessa219** [comment]
> @Vanessa219 V姐劝劝D大

👌 为了方便大家交流，中文肯定是会继续使用的，只是看用什么方式了。
老板急于展现中国制造，昨天头脑发热操作过猛了 😂

**Comment by 88250** [comment]
再总结一下缺点情况：

* 仓库使用中文：无法国际化推广，不利于思源笔记开源项目的发展。目前没有可行的解决方案
* 仓库使用英文：中文用户反馈不便。目前可行的解决方案：
  * 使用另一个仓库用于中文 Issues，提到主库上的中文 issue 会被先移动到这个仓库上
  * 在链滴上反馈
  
  以上两种反馈如果确认要处理，那么在主库上用英文创建 issue 并进行出处关联

思源笔记是一个开源项目，希望大家都能站在利于思源长远发展的角度看待变动，对反馈进行语言分区应该是目前唯一可行的解决方案了。

**Comment by SineMark2020** [comment]
> 👌為了方便大家交流，中文肯定是會繼續使用的，只是看用什麼方式了。 老闆急於展現中國製造，昨日腦洞大開操作過猛了😂

中国内卷严重对外输出是不错的方式. makedown笔记软件最大用户群还是在海外.,适当推广不是坏事.

**Comment by HowcanoeWang** [comment]
> > 或者启用Github discussion呗，天生就是用来作为论坛使用的。所有的中文和英文反馈都在这里(用语言tag区分)，issue只作为更新log使用，不负责特性提议和bug咨询
> > ![image](https://user-images.githubusercontent.com/19968935/228704096-a3deeceb-53b0-427f-bd59-7fa50f9d55ba.png)
> 
> 这样的话会和已有链滴的功能重合，分散管理的精力。

那就把Github discussions作为纯英文反馈论坛，相当于英文版的链滴？

**Comment by suka233333** [comment]
> 

同意！

**Comment by suka233333** [comment]
> > > 或者启用Github discussion呗，天生就是用来作为论坛使用的。所有的中文和英文反馈都在这里(用语言tag区分)，issue只作为更新log使用，不负责特性提议和bug咨询
> > > ![image](https://user-images.githubusercontent.com/19968935/228704096-a3deeceb-53b0-427f-bd59-7fa50f9d55ba.png)
> > 
> > 
> > 这样的话会和已有链滴的功能重合，分散管理的精力。
> 
> 那就把Github discussions作为纯英文反馈论坛，相当于英文版的链滴？然后让歪果仁负责这个板块的管理

这样也挺好

**Comment by mozhux** [comment]
就应该让github提供一个用户母语选项，然后自动双语翻译，气人

**Comment by AugustTuan** [comment]
确实，我觉得思源以后或许可以在国外火起来，然后出口转内销。 🤩

**Comment by haogeek** [comment]
我觉得可以参考下AntD、Vue、Kratos这些起源于中国开发者的知名开源项目，就目前来看这些项目的issue里是两种语言都包含的。其实对于现今的浏览器自动翻译来说，语言障碍（读方面）基本上不是什么问题，如果借力于ChatGPT那更是得心应手（写方面）

**Comment by UFDXD** [comment]
现在浏览器自动翻译那么便捷，也不见得有几个老外反馈。

**Comment by GoseRank** [comment]
我支持issue英文化，本来issue就是大家一起讨论，如果中文用户发中文的、英文用户发英文的，那么讨论还是割裂的。
借助现在的机器翻译软件，使用英语也不是问题。
最大的希望就是，思源在国外火起来，赚大钱，扩展公司规模。有钱请员工维护社区，中英文交流就不是问题。😃

**Comment by henmy168** [comment]
> 我支持issue英文化，本来issue就是大家一起讨论，如果中文用户发中文的、英文用户发英文的，那么讨论还是割裂的。 借助现在的机器翻译软件，使用英语也不是问题。 最大的希望就是，思源在国外火起来，赚大钱，扩展公司规模。有钱请员工维护社区，中英文交流就不是问题。😃

迎娶白富美走上人生巅峰
但是现在一进来全是英文，感觉很慌

**Comment by 88250** [comment]
大家能用英文还是用英文吧。

几年前我写过一篇[《我为什么要用中文写项目文档》](https://ld246.com/article/1566191673842)，现在是时候做出一些改变了。

**Comment by frostime** [comment]
从长远来看，一个开源项目想要更好地活下去，走向国际化是不可避免的。

思源的进步我们有目共睹，说实话就自身硬实力而言在国内的开源项目里面是排的上号的。但是，好酒也怕巷子深，思源笔记自身的酒已经够香了，所以下一步考虑走出巷子是必然的事情。

从最功利的角度来看，开源项目也需要钱，我记得很久之前群里面讨论的时候大家羡慕过 logseq 长长的捐助列表——这当中国际化我认为还是占了一个重要的比例的，毕竟实事求是讲拓宽「国际资本」的投资是money的重要来源。

但是同样，思源毕竟之前一直是靠中文用户支撑的，如果直接草率到切换到英文还是不太合适。这次的争议其实最大问题在于步子迈得太大了。大家一夜之间发现熟悉的中文 issue 页面全都不见了，自然会有怨言。

我认为如果开发者坚定了走向国际的医院，就应该去明确地告知现在已有的用户，和他们讨论、帮他们适应。就比如之前有人提过，支持英文可以但是也没有必要排斥中文。

> 我觉得可以参考下Ant Design、Vue、Spring Cloud Alibaba、Kratos这些起源于中国开发者的知名开源项目，就目前来看这些项目的issue里是两种语言都包含的。其实对于现今的浏览器自动翻译来说，语言障碍（读方面）基本上不是什么问题，如果借力于ChatGPT那更是得心应手（写方面）

当然，其实具体到 issue 里面，由于设计不少思源的专有名词，其实自动翻译也不一定完美。我觉得出一份「思源内部术语的中英文对照表」，也能为英语水平不好的用户提供不少帮助。

**Comment by ylsislove** [comment]
挺感慨D大之前说的”**国人可以啃英文，为什么外国友人不能啃啃中文**“😂我个人观点是Issues应该包容两种语言，可以既有中文，又有英文。对于一个真正上心的用户来说，语言都不是问题，借助浏览器翻译和ChatGPT，照样可以浏览Issues。
有人可能就会说了，既然翻译都不是问题，那么Issues全用英文交流不更方便外国友人吗。只是我个人觉得，思源起源于中国，基数在中国，发展壮大也在中国，中文又不比英文差，为什么非要让国内用户迁就国外用户呢。思源肯定会变得越来越优秀的，我希望可以通过思源慢慢改变国际环境，让国外友人也能适应中文的Issues环境。哈哈，希望这一天可以到来~

**Comment by nhan000** [comment]
@HowcanoeWang 我在这里使用谷歌翻译。 会说英语的人比任何其他语言都多。

[Wikipedia](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers)

![image](https://user-images.githubusercontent.com/85216095/229183900-a788c089-81aa-4cee-93c6-2a9b3e05f043.png)

此外，我们还需要考虑实际使用这些笔记工具的人。 如果您将范围缩小到足够关心记笔记以使用这些高级工具的人，他们就更有可能说英语。

这并没有剥夺中国的支持。 正如其他人所说以及我在英语支持问题中所争论的那样，在不冒犯中国用户的情况下支持英语是可能的。

**Comment by 88250** [comment]
我们先关闭这个 issue 了，会保持在 Issues 上钉住一段时间。

**Comment by sprders** [comment]
关于论坛，不太赞成只把 ld246 当作中文论坛，它可以是一个选择而不应该是唯一的选择。也许是我不会用，它的搜索体验不好，甚至可以用糟糕来形容，只想搜索关于思源的内容，但是实际结果还有其他内容，内容混杂。上面提到的Github discussion是一个很好的选择，赞成。如果有钱，也可以搞独立的中文/英文论坛。
关于issue，我是赞成一个英文，一个中文。如果只有英文，搜索一个问题，得先把中文翻译成英文，然后再搜，效率和准确度都得打折扣。
我觉得与其讨论中英文的选择问题，不如思考如何让中英文更好地共存，不要搞非此即彼那一套，二者可以共存，唯一的缺点应该是会浪费更多的精力。

**Comment by ylsislove** [comment]
@sprders 非常同意你的观点。针对issues来说，哪怕只是把标题弄成双语的就行，不管是对中文用户，还是英文用户，都可以很方便的搜索到问题。找到相关的issue后，具体内容再借助浏览器翻译和ChatGPT，了解issue就不是障碍了。
不搞此一套彼一套，本来看习惯的中文的issues，突然就全变成英文的了，就我个人而言心里会不舒服一下，我也确实是英语比较菜/捂脸，但还是希望思源能开个头，能让中文在国际开发社区里的分量变得更重一些~
>“这里是中国空间站，请使用中文”——《地心引力》

**Comment by 88250** [comment]
如果是确认要解决的 issue，标题如果不是英文我们就翻译为英文，如果是双语，会将中文部分移到正文中，这样既能保持 issues 列表的英文统一，也能方便搜索；对于不解决的 issue，标题和内容都不会做任何改变，讨论完毕后就直接关闭了。

这大概是目前为止能找到的最为折中的方案了。

**Comment by ylsislove** [comment]
@88250 为了思源能走向国际化，这确实算是个较好的折中方案了。真希望有一天能再看到中文列表的统一，让国外友人都能参与到中文的讨论中来。

**Comment by JARVISia** [comment]
> 如果是确认要解决的 issue，标题如果不是英文我们就翻译为英文，如果是双语，会将中文部分移到正文中，这样既能保持 issues 列表的英文统一，也能方便搜索；对于不解决的 issue，标题和内容都不会做任何改变，讨论完毕后就直接关闭了。
> 
> 这大概是目前为止能找到的最为折中的方案了。

想了解下issue标题为啥不考虑用双语呢？“this is a title | 这是一个标题”，类似这种形式感觉不错呀

**Comment by 88250** [comment]
@JARVISia 一来是列表看上去不够“国际化”，二来是工作量问题，需要两种语言都相互翻译。

**Comment by TCOTC** [comment]
@88250 我感觉这个挺好：

将非英文issue实时翻译成英文issue的action：https://github.com/dromara/issues-translate-action
