### ISSUE TITLE
After the document is transferred to the heading, occurs two copies of the reference block

### ISSUE THREAD

**Issue by fwzuw** [siyuan-note/siyuan#7819]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

将文档转为标题后把鼠标放在引用数量上会悬浮出双倍内容
![image](https://user-images.githubusercontent.com/48246272/228457199-4743091b-484e-489c-aa98-af2fe171a4c0.png)
下面那个引用的悬浮窗口是正常的，我给固定住了
重建索引后恢复正常

### 期待的结果 Expected result

修复

### 版本环境 Version environment

```markdown
- Version: 2.8.1
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

I 2023/03/29 15:24:26 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/03/29 15:24:26 runtime.go:51: kernel is booting:
    * ver [2.8.1]
    * arch [amd64]
    * os [Microsoft Windows 10 Pro for Workstations]
    * pid [23764]
    * runtime mode [prod]
    * working directory [C:\Users\fwz\scoop\apps\siyuan-note\current\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\工作与学习\思源]
I 2023/03/29 15:24:26 conf.go:221: upgraded from version [2.8.0] to [2.8.1]
I 2023/03/29 15:24:26 working.go:398: built-in pandoc [ver=2.19.2, bin=D:\工作与学习\思源\temp\pandoc\bin\pandoc.exe]
I 2023/03/29 15:24:26 runtime.go:97: use network proxy [system]
I 2023/03/29 15:24:26 serve.go:108: kernel [pid=23764] http server [127.0.0.1:62233] is booting
I 2023/03/29 15:24:27 blocktree.go:386: read block tree [322 kB] to [D:\工作与学习\思源\temp\blocktree], elapsed [0.02s]
I 2023/03/29 15:24:27 conf.go:671: database size [2.4 MB], tree/block count [134/1074]
I 2023/03/29 15:24:27 working.go:157: kernel booted
I 2023/03/29 15:24:28 box.go:74: auto stat [trees=134, blocks=1074, dataSize=185 MB, assetsSize=7.4 MB]
I 2023/03/29 15:24:28 disk.go:33: disk usage [total=4.0 TB, used=3.5 TB, free=510 GB]
I 2023/03/29 15:24:28 serve.go:121: reverse proxy server [127.0.0.1:6806] is booting
I 2023/03/29 15:25:08 conf.go:446: exiting kernel [force=false, execInstallPkg=0]
I 2023/03/29 15:25:08 database.go:1127: closed database
I 2023/03/29 15:25:08 conf.go:818: cleared workspace temp

**Comment by 88250** [comment]
请重建索引后再试。

**Comment by fwzuw** [comment]
该问题可以稳定复现，重建索引只能消除出现的错误，不能解决产生问题的 bug

![动画2023-03-29](https://user-images.githubusercontent.com/48246272/228499069-58c8e461-8524-49b6-b44d-4a1275d34dbd.gif)

针对动图的补充：
- 不是必须标题转文档再转标题才会触发，重建索引后直接用文档转标题也会出错
- 不是必须由子文档转标题才会触发，其他位置的文档转标题也会出错
