### ISSUE TITLE
The PDF export preview displays unexpectedly

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7825]
### 该问题是否已经被报告过了？ Is there an existing issue for this?

- [X] 我已经搜索了 Issues，没有发现类似问题 
I have searched the existing issues

### 该问题是否能够在默认主题（daylight/midnight）下重现？ Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] 我能够在默认主题下重现该问题
I was able to reproduce the issue with the default theme

### 该问题是否可能是由于扩展功能导致？ Could the issue be due to extensions?

- [X] 我已经排除了扩展导致问题的可能性
I've ruled out the possibility that the extension is causing the problem.

### 描述问题 Describe the problem

![image](https://user-images.githubusercontent.com/49649786/228544399-38698d04-b7c5-493d-be9e-829e24d6fd6b.png)

### 期待的结果 Expected result

预览窗口中预览面板与控件面板可以正常显示  
The preview panel and control panel in the preview window display normally.

### 版本环境 Version environment

```markdown
- Version: 2.8.2-dev2
- Operating System: 
- Browser (if used):
```

### 日志文件 Log file

无有效信息输出  
No valid information output

**Comment by Vanessa219** [comment]
It's ok in my APP, please check this:
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/970828/228706322-09797c9a-274e-45ac-8ef8-9677b375cd44.png">

**Comment by Zuoqiu-Yingyi** [comment]
> It's ok in my APP, please check this

该属性是正常的, 是因为该窗口尺寸的问题吗  
This property is normal, is it because of the size of the window?

![image](https://user-images.githubusercontent.com/49649786/228741523-27bdba71-88b2-4f73-8c7c-30df0da133dd.png)

**Comment by Vanessa219** [comment]
找到窗口打开小的原因了么？

**Comment by Vanessa219** [comment]
这个页面没有缩放，也不允许缩放

**Comment by Zuoqiu-Yingyi** [comment]
删除 `C:\Users\<用户名>\AppData\Roaming\SiYuan-Electron` 目录后就正常了\~
