### ISSUE TITLE
S3 synchronization online check not using configured endpoint

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#7831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Current S3 online check is broken as configured endpoint is not used for checking but `www.baidu.com` instead.

### Expected result

Online-check is requesting configured endpoint.

### Screenshot or screen recording presentation

see https://github.com/siyuan-note/siyuan/blob/127feaa8322019eda1342dafa65c97da806f3ee5/kernel/util/net.go#L62

### Version environment

```markdown
- Version: 2.8.2
- Operating System: Windows 10
- Browser (if used): None
```

### Log file

```
W 2023/03/30 09:37:16 net.go:56: network is offline [checkURL=https://my-private-s3-endpoint.com/]
```

### More information

-

**Comment by KarlKaijie** [comment]
从2.8.2更新到2.8.3，出现了这个问题。环境是Docker环境，Docker环境下有问题， 而在macos系统下却没有问题，S3的配置是一样的，不知为什么会出现不一样的结果
net.go:49: network is offline [checkURL=https://www.zzscloud.uk:50321/]

**Comment by 88250** [comment]
@KarlKaijie 下个版本继续改进 https://github.com/siyuan-note/siyuan/issues/7890
