### ISSUE TITLE
更新之后打开报错

### ISSUE THREAD

**Issue by leacoleaco** [siyuan-note/siyuan#7842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新后启动报工作空间被锁定的错误

### Expected result

正常打开工程

### Screenshot or screen recording presentation

<img width="719" alt="截屏2023-03-31 13 14 22" src="https://user-images.githubusercontent.com/17734288/229029552-b9ea6ed0-db0a-4b47-8e08-0b58cfba9950.png">
<img width="720" alt="截屏2023-03-31 13 14 12" src="https://user-images.githubusercontent.com/17734288/229029555-cedf56e8-fc76-490b-a30e-bcc43cbe7ba1.png">

### Version environment

```markdown
- Version: 2.8.2
- Operating System: MAC 13.2.1 (22D68)
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11118411/siyuan.log)

**Comment by 88250** [comment]
有其他内核进程占用了工作空间，建议重启一下系统后再试试。

**Comment by leacoleaco** [comment]
谢谢, 好像结束进程后再打开就好了
