### ISSUE TITLE
2.8.0版本后的安卓版无法插入图片

### ISSUE THREAD

**Issue by FullOfWind-Sun** [siyuan-note/siyuan#7843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

大大，报告一个问题：点击插入图片无反应。
以前是用斜杠调出菜单选择插入图片（手机端现在不能用斜杠调出了吗？），现在系统默认直接点击下方菜单的＋号键，就能选择插入图片，但点击插入图片，手机无任何反应。。。

### Expected result

大大，报告一个问题：点击插入图片无反应。
以前是用斜杠调出菜单选择插入图片（手机端现在不能用斜杠调出了吗？），现在系统默认直接点击下方菜单的＋号键，就能选择插入图片，但点击插入图片，手机无任何反应。。。

### Version environment

```markdown
- Version: 2.8.0-2.8.2
- Operating System: Android
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11119055/siyuan.log)

**Comment by 88250** [comment]
你好，移动端可以试下右上角 ... 菜单（面包屑一行的右边那个，不是右上角顶部的），`/` 菜单在移动端上取消了。

我这里目前无法重现问题，可以调出系统的文件选择。

PS：GitHub Issue 请尽量使用英文反馈，如果必须使用中文，建议到链滴上反馈，谢谢。
