### ISSUE TITLE
The Mobile Android Version cannot connect to my S3 storage

### ISSUE THREAD

**Issue by theRealBithive** [siyuan-note/siyuan#7844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The Mobile Android Version cannot connect to my S3 storage. It works on the mobile browser.

### Expected result

Connection to the Endpoint is possible and sync works

### Screenshot or screen recording presentation

![Screenshot_20230331_101544_SiYuan](https://user-images.githubusercontent.com/53299771/229064913-fd2fda2a-82ef-4feb-868b-d83c0ccbe753.jpg)

### Version environment

```markdown
- Version: 2.8.2
- Operating System: Android
- Browser (if used):
```

### Log file

  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/03/31 10:09:36 runtime.go:51: kernel is booting:
    * ver [2.8.2]
    * arch [arm64]
    * os [Android 13/33]
    * pid [26651]
    * runtime mode [prod]
    * working directory [/data/user/0/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/03/31 10:09:36 conf.go:105: initialized the specified language [en_US]
I 2023/03/31 10:09:36 conf.go:336: OpenAI API enabled
    baseURL=https://api.openai.com/v1
    timeout=30s
    proxy=
    maxTokens=0
I 2023/03/31 10:09:36 runtime.go:97: use network proxy [system]
I 2023/03/31 10:09:36 serve.go:108: kernel [pid=26651] http server [127.0.0.1:6806] is booting
W 2023/03/31 10:09:37 net.go:56: network is offline [checkURL=https://storage.bithive.space/]
I 2023/03/31 10:09:37 blocktree.go:386: read block tree [1.6 MB] to [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/blocktree], elapsed [0.04s]
I 2023/03/31 10:09:37 conf.go:671: database size [12 MB], tree/block count [267/5484]
I 2023/03/31 10:09:37 working.go:157: kernel booted
I 2023/03/31 10:09:37 box.go:74: auto stat [trees=267, blocks=5432, dataSize=53 MB, assetsSize=50 MB]
I 2023/03/31 10:09:37 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=52, size=1.0 MB]
W 2023/03/31 10:09:41 net.go:56: network is offline [checkURL=https://storage.bithive.space/]
W 2023/03/31 10:09:55 net.go:56: network is offline [checkURL=https://storage.bithive.space/]

### More information

Thanks for looking into it. It's a great app!

**Comment by 88250** [comment]
Hello, thanks for the report, this problem should be caused by https://github.com/siyuan-note/siyuan/issues/7831, please try again after the next version is released.

**Comment by KarlKaijie** [comment]
> Hello, thanks for the report, this problem should be caused by #7831, please try again after the next version is released.

从2.8.2更新到2.8.3，出现了这个问题。环境是Docker环境，Docker环境下有问题， 而在macos系统下却没有问题，S3的配置是一样的，不知为什么会出现不一样的结果
net.go:49: network is offline [checkURL=https://www.zzscloud.uk:50321/]

**Comment by 88250** [comment]
@KarlKaijie 下个版本继续改进 https://github.com/siyuan-note/siyuan/issues/7890
