### ISSUE TITLE
提议在每一个文档分别支持自定义宽度

### ISSUE THREAD

**Issue by WolkeAtreide** [siyuan-note/siyuan#7847]
### In what scenarios do you need this feature?

想法来源：notion的每个页面都可以自定义宽度
使用场景：
关闭自适应宽度：阅读笔记时，记笔记时，使用代码块时
开启开适应宽度：使用表格时，记日记时，无线列表转脑图时
总之，当使用思源来承担更多任务时，关于文本宽度的需求就多样化起来。

### Describe the optimal solution

![image](https://user-images.githubusercontent.com/101959415/229259656-ad9ecfa9-44c5-4925-a5c4-45707de52974.png)

### Describe the candidate solution

增加一个自适应宽度的快捷键

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/7388
