### ISSUE TITLE
思源笔记手机APP工作区存储位置问题 

### ISSUE THREAD

**Issue by bluebat1** [siyuan-note/siyuan#7857]
### In what scenarios do you need this feature?

 能不能添加一个功能，允许用户手动从手机的存储空间选择某个文件夹或路径作为工作区呢？并且多个工作区时 每个工作区可以放在不同的路径下。

### Describe the optimal solution

单独设置一个按钮【添加工作空间】，点击后调用类似  import {ipcRenderer} from 'electron' 的  ipcRenderer.send('open-directory-dialog','openDirectory');   ipcRenderer.on('selectedItem',this.getPath); 来选择 工作空间路径。但并不确定这个是否可以在移动端工作。

**Comment by 88250** [comment]
你好，这个暂时不考虑了，感谢提议。
