### ISSUE TITLE
在assets目录下加入多级目录

### ISSUE THREAD

**Issue by wangcn** [siyuan-note/siyuan#7858]
### In what scenarios do you need this feature?

单级目录下文件过多后，在Windows资源管理器里打开会有些卡顿。

### Describe the optimal solution

可以按yyyy/mm/dd多级目录保存。

**Comment by 88250** [comment]
你好，设计之初考虑到多级目录有一些缺陷，比如难以批量移动、分享图床后链接无法一一对应，所以默认是统一存放的。

如果有分开的需求，可以手动创建笔记本级 assets 文件夹，具体描述请看用户指南资源文件章节。

**Comment by wangcn** [comment]
能否给个选项呢？然后说明下相关缺陷，让大家有个选择。

**Comment by 88250** [comment]
这些选项无法克服的，所以折中方案就是后面提到的手动建立笔记本级 assets 文件夹，但是笔记本级 assets 也有副作用，具体副作用已经在用户指南资源文件章节中列出了。
