### ISSUE TITLE
Search presents - quickly change what / where are you searching

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7859]
### In what scenarios do you need this feature?

I want to use simple search (document titles and maybe headlines) for most of the time because of the speed, however, then sometimes I want to search everywhere. It takes a lot of time to manually activate / deactivate all search options. 

### Describe the optimal solution

I could save my selected search options as presents and quickly switch between them from the top bar. 
 
![image](https://user-images.githubusercontent.com/63197393/229355842-d40281bb-f6c9-4b1d-89ae-1e9508206d43.png)

### Describe the candidate solution

As a minimal solution, it would be sufficient to have a switch to just search in page titles only vs. full search.

**Comment by 88250** [comment]
Hello, in this scenario, you can consider using the `named criterion` function to persist the search conditions (such as type filtering, sorting, etc.), and you can click to switch when you use it next time.

**Comment by ciceronianus** [comment]
I tried it now but it has quite weird behaviour (which one is active?) and does not seem to work. 
![image](https://user-images.githubusercontent.com/63197393/229357395-c50a038c-a62a-4f50-955a-21241d58a19a.png)

**Comment by 88250** [comment]
Named criterion has no active/inactive state, and the query is executed directly after selecting a named criterion. As shown in the figure above, there is no keyword, and if there is no keyword, the most recently updated block is returned (not use search conditions specified by the named criterion).

**Comment by ciceronianus** [comment]
Hmm, but that does not seem to affect places where I want to search. This does not change, even when I save the criterion as a preset. Or what am I missing? 

![image](https://user-images.githubusercontent.com/63197393/229358035-798f1641-3912-4d3a-a5bc-09563d1869d8.png)

**Comment by ciceronianus** [comment]
Yeah, it does not seem to affect "type" at all. I am afraid this is not a solution for my problem.

**Comment by 88250** [comment]
If I understand your needs correctly, please try the following steps:

1. Adjust type filter like this

   ![image](https://user-images.githubusercontent.com/873584/229358250-c77a7551-26f6-40c3-b620-cf32bfeb93b0.png)

2. Save it as a named criterion 
3. Select the named criterion just created, than type in search keyword

   ![image](https://user-images.githubusercontent.com/873584/229358551-b9126b91-f105-4ea8-8cc2-728e7b007bfb.png)

4. If you want to use default search condition, just need to clear current named criterion

   ![image](https://user-images.githubusercontent.com/873584/229358600-5d24f333-e9f8-4905-97f2-c1d606137482.png)

**Comment by ciceronianus** [comment]
Thanks. Weird. I did exactly this and it did not work at the beginning. Now after some moment, it seems to somehow work... So I guess I can use it. Thank you!

**Comment by 88250** [comment]
Ok, let's close this issue, thanks.
