### ISSUE TITLE
The search fails in REGEXP/SQL with order by relevance

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7861]
正则表达式模式下搜索失效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用正则表达式模式进行搜索时无搜索结果, API `/api/search/fullTextSearchBlock` 响应体 `data.blocks` 字段值为空数组, `data.matchedRootCount` 与 `data.matchedBlockCount` 字段值不为 `0`  
No search results when searching using regular expression mode, API `/api/search/fullTextSearchBlock` response body `data.blocks` field value is an empty array, `data.matchedRootCount` and `data.matchedBlockCount` field values are not '0'

### Expected result

API `/api/search/fullTextSearchBlock` 响应体 `data.blocks` 字段值为正常的查询结果  
API `/api/search/fullTextSearchBlock` response body `data.blocks` field value is normal query results

### Version environment

```markdown
- Version: 2.8.3-dev1
- Operating System: 
- Browser (if used):
```

### Log file

无有效信息输出
No valid information output

**Comment by 88250** [comment]
I've tested fine here:

![image](https://user-images.githubusercontent.com/873584/229362203-04ea0ffe-d93d-49be-814c-8b36126af5ea.png)

Please give the regular expression used for testing and the data of the content block to be searched, thank you.

**Comment by Zuoqiu-Yingyi** [comment]
> Please give the regular expression used for testing and the data of the content block to be searched, thank you.

排序方案使用 `按相关度降序/升序`  
The sorting scheme uses `Relevance DESC/ASC`

请求体 | Request body
```json
{
    "query": "内容块.*\\d+",
    "method": 3,
    "types": {
        "blockquote": false,
        "codeBlock": true,
        "document": true,
        "embedBlock": false,
        "heading": true,
        "htmlBlock": true,
        "list": false,
        "listItem": true,
        "mathBlock": true,
        "paragraph": true,
        "superBlock": false,
        "table": true
    },
    "paths": [],
    "groupBy": 1,
    "orderBy": 7
}
```

**Comment by 88250** [comment]
已经确认问题，同时也发现另一个问题，即相关度排序是通过 FTS 查询语法实现的（排序字段是 `rank`），也就是说正则表达式和 SQL 搜索实际上不能使用相关度排序，下个版本会将该情况下强制使用 `sort` 字段进行排序。

The problem has been confirmed, and another problem has been found, that is, the correlation ranking is implemented through the FTS query syntax (the sorting field is `rank`), which means that regular expressions and SQL searches cannot actually use correlation ranking, the next version will force sorting using the `sort` field in this case.
