### ISSUE TITLE
The merged cells of the table no longer add a space at the end

### ISSUE THREAD

**Issue by diaominshushu** [siyuan-note/siyuan#7866]
合并的表格会在最后自动添加一个空格

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

表格中，合并两个表格之后，在这个新的表格单元里面，鼠标放上去后会自动生成一个空格，每次输入都需要先删除这个空格才行

### Expected result

合并表格不产生这个多余的空格

### Screenshot or screen recording presentation

[屏幕录制 2023-04-03 131153.zip](https://github.com/siyuan-note/siyuan/files/11134905/2023-04-03.131153.zip)

视频太大了，我压缩了一下。

### Version environment

```markdown
- Version: 2.8.2
- Operating System: windows11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11134925/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，分析了一下，这个问题和 https://github.com/siyuan-note/siyuan/issues/7556 有关联，解析器上的实现无法保证这两个场景都正确，我们只能优先保证 #7556 是正确的。

只能先关闭了，如果后面有解决方案再重新打开，谢谢。

**Comment by 88250** [comment]
昨晚睡觉的时候想了一个方案，今早实现测试了一下，可以保证两个场景都正确了。
