### ISSUE TITLE
Annotation overview for PDFs

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7871]
### In what scenarios do you need this feature?

I would like to see a list of all annotations that I did in a PDF. I am a researcher and this function would allow me to get quick overview of my annotations.

### Describe the optimal solution

It could be similar to Backlinks panel or outline panel, listing all annotations done in PDF, including their type. Ideally, it would be possible to add comments to them (but that is probably for a separate feature request).

**Comment by 88250** [comment]
Hello, we planned to implement this requirement through a widget https://github.com/siyuan-note/siyuan/issues/3082, but we have not yet determined the exact solution until today.

Keep the issue open for now to collect more related requirements and discuss, thank you.

**Comment by ciceronianus** [comment]
I find personally a widget impractical for this use because it would have to be inserted into another page, to get it work.

**Comment by 88250** [comment]
We have an idea for "Widget Panel" https://github.com/siyuan-note/siyuan/issues/3689

It is similar to a doc tree or outline panel, which acts as a container to place widgets. For example, after placing a "PDF Annotation" widget in it, the widget can automatically list the annotations related to the currently opened PDF tab.

**Comment by ciceronianus** [comment]
That sounds actually quite cool. Yes, that could be a solution.

**Comment by 88250** [comment]
We closed this issue, thank you.
