### ISSUE TITLE
Monitor the search performance and suggest solutions

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7873]
### In what scenarios do you need this feature?

It happened to me that my search became very slow and almost unusable on some occassions. It seems that following the advice and the change of the searching parameter to 32 helped a lot. 

![image](https://user-images.githubusercontent.com/63197393/229605065-9823f2e2-b586-4e14-977f-5b2f3d8c454a.png)

It would be great if there was some monitoring of the performance that would suggest solutions for the most common issues.

### Describe the optimal solution

Monitor the performance, especially search, start-up time, plugins and widgets and suggest what the user should do to improve the performance, if it is bad.

**Comment by 88250** [comment]
This is a good idea. Let's simply add an implementation to monitor only the performance of the global search interface, and a prompt will pop up after the response time exceeds 7s.
