### ISSUE TITLE
Recently opened documents dialog displays the document path

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7876]
最近打开的文档对话框显示文档路径

### In what scenarios do you need this feature?

使用快捷键 <kbd>Ctrl + E</kbd> 打开的 `最近打开的文档` 对话框中的文档列表仅显示文档名不显示文档路径, 失去了上文信息后就不能很好得找到所需的文档  
The document list in `Recently opened documents` dialog which using shortcut key <kbd>Ctrl + E</kbd> to open doesn't display the document path. Without the information above, it is not a good way to find the required document.

### Describe the optimal solution

参考搜索结果, 显示文档的完整可读路径  
Refer to the search results to show the full readable path of the document.

**Comment by 88250** [comment]
底部有显示。

![image](https://user-images.githubusercontent.com/873584/229760645-18c322ef-03b0-4f72-a843-0fd9e5269ca6.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 底部有显示。

没法扫一眼直接点击, 必须用方向键移动焦点, 基本和没有一个样

**Comment by 88250** [comment]
这个浮层太小，路径怕显示不下，等 https://github.com/siyuan-note/siyuan/issues/7676 搞好以后考虑吧。

我们忘了的话麻烦踢一下，谢谢。

**Comment by Zuoqiu-Yingyi** [comment]
> 我们忘了的话麻烦踢一下，谢谢。

建议打开本 issue, 这样就忘不了了👀

**Comment by 88250** [comment]
#7676 下面也有关联了，到时候我们看下吧。
