### ISSUE TITLE
Add flashcard to recently opened documents  and switcher

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7881]

**Comment by kx1356** [comment]
如果这个文档有抽认卡，自动显示打卡图标，然后点击快捷打卡就好了。

**Comment by Vanessa219** [comment]
没太明白

**Comment by kx1356** [comment]
就像remnote一样。
________________________________
发件人: V ***@***.***>
发送时间: 2023年4月7日 15:35
收件人: siyuan-note/siyuan ***@***.***>
抄送: kx1356 ***@***.***>; Comment ***@***.***>
主题: Re: [siyuan-note/siyuan] Add flashcard to recently opened documents and switcher (Issue #7881)


没太明白

―

**Comment by Vanessa219** [comment]
呃，没有 remnote
