### ISSUE TITLE
希望能将“布局”按钮移到侧边栏

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#7883]
### In what scenarios do you need this feature?

布局能重新组织文档，可以实现不同的工作区互不干扰，相当于一个虚拟的目录，但目前“布局”按钮位于顶栏的二级菜单里，使用起来相当不便，所以希望能够调整到侧边栏里（效果图见下图），另外 OB 的工作布局也是在侧栏的一级菜单里，这样使用起来的体验就非常好。
![image](https://user-images.githubusercontent.com/117154557/229795662-76d28596-2411-4af9-a9c6-1a9a0ec2cefc.png)

### Describe the optimal solution

希望考虑。

**Comment by GH-W94** [comment]
> 停靠栏也是布局的一部分，所以将布局入口放在停靠栏上不大合理。
> 
> 后续会考虑支持自定义顶栏操作 #7090 放在顶栏更合理一些。
> 
> 这个 issue 我们先关闭了，谢谢。

好吧，我没想到“布局”功能还包含了停靠栏。

D 大，我认为把现阶段的“布局”功能拆分成如下两个功能比较好：
1.“布局”功能。按钮位置就在现阶段的顶栏位置，功能是保存“停靠栏及未来自定义顶栏”的布局。
2.“工作区”功能。按钮位置位于停靠栏上，功能是组合不同文档，形成不同的工作区。

希望考虑，谢谢。

**Comment by 88250** [comment]
工作区不包含布局的话作用不大。

**Comment by GH-W94** [comment]
> 工作区不包含布局的话作用不大。

从我的使用过程中的体验来看，切切相反，布局功能毫无用处，若不是你讲有这个功能我都不知道，我完全当工作区功能在用。

在我实际使用中，停靠栏布局调整好了之后，就不在动了，布局功能就没啥用了，但工作区确经常调整，比如由若干文档组成的工作总结区、若干文档组成的当前工作区、若干文档组成的兴趣阅读区……，这些工作区经常互相切换。
所以我认为工作区功能要比布局功能有用的多了。

**Comment by GH-W94** [comment]
> 工作区不包含布局的话作用不大。

从我的使用过程中的体验来看，切切相反，布局功能毫无用处，若不是你讲有这个功能我都不知道，我完全当工作区功能在用。

在我实际使用中，停靠栏布局调整好了之后，就不在动了，布局功能就没啥用了，但工作区确经常调整，比如由若干文档组成的工作总结区、若干文档组成的当前工作区、若干文档组成的兴趣阅读区……，这些工作区经常互相切换。
所以我认为工作区功能要比布局功能有用的多了。
