### ISSUE TITLE
Call loadingElement.remove() after RenderSnippets

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#7884]
RenderSnippets之后再调用loadingElement.remove()

### In what scenarios do you need this feature?

需要在snippet同步加载完成后，再移除loading元素，避免用户能够发现snippet在动态加载的问题。

直接需求是由于插件系统的异步加载过程很长，计划像其他的笔记产品一样做个插件加载的loading，但是由于snippet加载时机太晚，导致界面出现中间显示了实际内容然后又被插件系统增加了遮罩这么个问题。

### Describe the optimal solution

重构加载流程。使用async/await, Promise等异步方式来控制加载的顺序。添加<script>是可以做到同步执行snippet的js代码的，也就是可以控制snippet的同步执行，其内部的其他异步动作由snippet自己控制。把目前的loadingElement从initAssets中抽取出来，放在其他位置执行。
```javascript
async function init() {
   await initAsset();
   await renderSnippets();
   removeLoadingElement();
}

async function renderSnippets() {
  const res = await fetch('/api/getSnippets');
  const data = await res.json();
  for (const snippet of res.data.snippets) {
    const script = document.createElement('script');
    script.innerHTML = snippet;
    document.body.appendChild(script);
  }
}

function removeLoadingElement() {
   document.getElementById('loading').remove();
}
```

**Comment by zuoez02** [comment]
实际来说的话，我觉得整个现在初始化流程用async/await来控制，比已有的fetch+回调处理的方式更优雅一些吧，另外把初始化流程可以单独抽到一个init.ts里，专门放初始化相关的逻辑，避免和util混在一起，这个东西毕竟不是工具代码而是实实在在的主线流程代码。

**Comment by Vanessa219** [comment]
这样可能会影响一丢丢速度，要不加一个 showLoading，在 renderSnippets  和 Snippets 中用户也可以自己调用。
可以问一下这些方法在插件中是怎么暴露出去使用的？

**Comment by zuoez02** [comment]
@Vanessa219 需要这个其实主要是解决衔接问题，否则主框架hideLoading了，过几百毫秒插件再showLoading，还是有闪烁出来实际内容的空挡，不太好。这一丢丢速度我觉得还好吧，主要还是为了确保实际运行时机的正确性。对于没有Snippet的用户来说当然还是没有什么影响的。

插件系统目前参照的是Obsidian的设计方案，提供给开发者通过require('siyuan')的方法拿到API。这个require对于插件本身来说是无感的，而实际插件系统对require做了魔改，因此插件里如果想调用真正的require需要使用window.require。

最终我这考虑把插件系统做成Obsidian一样，加载插件的过程显示进度条，完成后再显示实际界面。虽然严重“抄袭”，但是我觉得也算正常解了，

**Comment by Vanessa219** [comment]
如果把插件集成进来，会不会更好一点。至于 Snippet 本意为片段，它的 loading 应该是可以忽略。

由于精力有限还没来得及看插件的实现，非常抱歉。上面我比较想知道的是比如 `Protyle` 等类或方法目前是如何 export 出去作为 API 的，目前没有官方的 API 居然可以做那么多功能，非常的不可思议。

**Comment by zuoez02** [comment]
@Vanessa219 都是社区大家的力量，折腾群里的几个大佬提供了很多实际能够生效的代码片段，插件系统做的工作就是统筹这些API，方便大家按照一个固定的形式进行代码编写、管理、分发。

并不是所有类都能直接拿到的，Protyle目前我还没有发现能够拿到的方式。现在一部分能力是通过window.siyuan提供的，比如menu, dialog之类的，一部分是通过函数劫持实现的。剩下很多还是直接DOM操作，或者MutationObserver之类的编码，setInterval循环判断之类的，性能会有很大的影响，但是目前也就只能这么做。

siyuan本身提供API可以通过window.siyuan的属性来添加，和require('siyuan')相比也不存在说有很大的差异。我单独发了个siyuan的npm包也只是为了提供Typescript类型。

集成插件系统进入本体也可以的，不过跟集市里其他东西相比还是需要统筹一下最后的方案更好。社区的插件系统好处就是非常自由灵活，分发也是用公网的免费方案，比集市提交确实是快一些 :)

**Comment by leolee9086** [comment]
> 如果把插件集成进来，会不会更好一点。至于 Snippet 本意为片段，它的 loading 应该是可以忽略。
> 
> 由于精力有限还没来得及看插件的实现，非常抱歉。上面我比较想知道的是比如 `Protyle` 等类或方法目前是如何 export 出去作为 API 的，目前没有官方的 API 居然可以做那么多功能，非常的不可思议。

protyle目前我是在界面加载完成之后从window.siyuan中layout里面，找到各个界面类的实例，然后从它们的原型链上获取构造函数完成构造，具体的过程在这里：
https://github.com/leolee9086/noob-core/blob/master/frontEnd/noobApi/customTab/util/Protyle.js
使用这种方式完成的效果可以在这里看到：
https://ld246.com/article/1669540533711


各种菜单的注入实现在这里：
https://github.com/leolee9086/noob-core/blob/master/frontEnd/noobApi/customMenu/index.js
其他各种界面元素的实现也都在这个里面，包括大部分的菜单、部分块的自定义渲染（通过shadowdom避免跟原生功能冲突），都有一些实现，其他的像利用electron渲染进程环境做的带有后端子服务那些也都有实现。
然后具体能够实现的功能我都发到社区了
https://ld246.com/article/1679763518967
菜单比较典型的就是
https://ld246.com/article/1681050363335 这样的文字补全
和 https://ld246.com/article/1680778970640 这样对特定块添加功能之类
啊，反正没有接口就暂时是各种各样的绕过方式，如果直接暴露一些内部类的话可能会方便一些吧

**Comment by leolee9086** [comment]
http://www.siyuanplay.com/stage/build/desktop/?r=zy8699f  这些应该这个库都安装了，插件系统是不是最新的我就没注意了

**Comment by Vanessa219** [comment]
看来还是需要 API，我记录到 https://github.com/siyuan-note/siyuan/issues/5066 中了。
