### ISSUE TITLE
Show inline-element menu only after clicking `BIU` or selecting text

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#7892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

移动端选中文本并剪切后，不自动从字体菜单跳回块菜单

取消选中时也不会

### Expected result

正常来说，选中文字时工具栏会从默认的块菜单跳到文字菜单，剪切后以及没有选中文字的情况，这时应该自动返回默认菜单

### Version environment

```markdown
- Version: 2.8.3
- Operating System: Android 13
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
剪切以后没有选中的状态，此时光标位于行级元素内（比如普通文本），所以显示的是行级工具栏。
