### ISSUE TITLE
After clicking the slash menu on the mobile, modify the hidden keyboard to close the slash menu

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#7895]
https://ld246.com/article/1680597214642/comment/1680614374929?r=Vanessa#comments

**Comment by mozhux** [comment]
如果是关闭键盘那个功能转移过来的话可能有点歧义。
我理解应该是：当点击编辑，处于编辑状态，工具栏和键盘应该是展开状态，此时点击+号，斜杆菜单覆盖键盘，+号变成x，再次点击x，则键盘覆盖斜杆菜单。当点击最右的键盘收起，则是整个工具栏收起键盘，只显示工具栏，当失去焦点滑动查看或在阅读模式时，应该是工具栏消失？

**Comment by Vanessa219** [comment]
收起键盘以后光标消失，工具栏也会消失。
点击 + 后
1. + 并不会变 x，只会高亮。再次点击会弹琴键盘
2. 弹琴键盘变为 x，点击会弹琴键盘

**Comment by mozhux** [comment]
后面再体验一下，预览版没有手机端是真难受，听说退出应用改在了菜单中间，这更奇怪了。

**Comment by mozhux** [comment]
> 收起键盘以后光标消失，工具栏也会消失。 点击 + 后
> 
> 1. `+` 并不会变 x，只会高亮。再次点击会弹琴键盘
> 2. 弹琴键盘变为 x，点击会弹琴键盘

我体验了别人打包好的新版apk，点击+号添加块菜单，页面内容会闪烁，这个体验有点不好，每次点击都闪烁。不知道本体有没有这个问题？

**Comment by Vanessa219** [comment]
呃，那只能等正式发布再试试

**Comment by mozhux** [comment]
> 呃，那只能等正式发布再试试

测试了2.8.4，点击+号按钮还是闪屏

**Comment by 88250** [comment]
闪烁问题一时解决不了了，暂时只能这样了。

**Comment by mozhux** [comment]
> 闪烁问题一时解决不了了，暂时只能这样了。

好的吧。那个退出应用的位置也有点奇怪，不能是那种悬浮的，左右分栏 一边帮助，一边退出应用。
