### ISSUE TITLE
Show changelog after upgrading

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7902]
### In what scenarios do you need this feature?

My SiYuan was updated to 2.8.3 just now. Great! But it happened pretty much silently. I think it would be great to provide a small startup screen after the update (just once) with the info what is new. Be proud on your creation! :) 

### Describe the optimal solution

Provide a startup screen (just once) with the info what is new, link to the roadmap and info how to provide suggestions / report bugs and/or contribute.

### Describe the candidate solution

You may also consider to add "what is new" directly under the main menu. 
![image](https://user-images.githubusercontent.com/63197393/230310780-312e2fad-61d0-411d-9e25-e736447e3a3b.png)

**Comment by 88250** [comment]
Thanks for the suggestion, we don't have time to implement it now, maybe I will consider it later.

![image](https://user-images.githubusercontent.com/873584/230348341-72605eb2-e92f-4197-bf47-be6e34ced7b9.png)
