### ISSUE TITLE
Provide an anonymized versions of the .log file

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7907]
### In what scenarios do you need this feature?

I would like to report a bug (disfunctional drag and drop in large documents), however, I don't want to post my log because it includes private information (username, paths etc.). I would prefere to use an anonymized version of the log (i.e. without my user name and folder structure) - it would be great if there was this possibility. 

### Describe the optimal solution

A possibility to create something like siyuan-anon.log file with removed private information (username, document paths etc.).

**Comment by 88250** [comment]
Some information may not be fully desensitized, such as asset file paths and workspace paths, because sometimes we need these path information for problem diagnosis.

This may only be desensitized manually by the user, thanks for the feedback.
