### ISSUE TITLE
希望内核支持--publicPath参数配置不同访问路径

### ISSUE THREAD

**Issue by ylsislove** [siyuan-note/siyuan#7908]
### In what scenarios do you need this feature?

我通过docker将服务部署在云服务器上，想通过域名下的不同路径访问到不同的服务，这样可以节省我的域名资源，如：
* `https://example.com/note1` -> `容器1的思源笔记`
* `https://example.com/note2` -> `容器2的思源笔记`

我尝试了用nginx的反向代理，但一旦我配置了代理目录，内核总会将请求重定向到`/stage/build/desktop/`，貌似无法通过nginx反代达到我的目的。

希望D大可以考虑下是否可以通过在内核配置publicPath参数，来支持不同的访问路径

### Describe the optimal solution

我尝试更改了内核的`serve.go`文件，将下面两行代码进行了变更
* 将 `c.Redirect(302, "/stage/build/desktop/?r="+gulu.Rand.String(7))` -> `c.Redirect(302, "/note1/stage/build/desktop/?r="+gulu.Rand.String(7))`
* 将 `siyuan.Static("/stage/", filepath.Join(util.WorkingDir, "stage"))` -> `siyuan.Static("/note1/stage/", filepath.Join(util.WorkingDir, "stage"))`

然后重新在本地构建运行，貌似成功访问到`http://localhost:6806/note1/stage/build/desktop/`了，但控制台依然报了一些错误，如下
![QQ截图20230407055437](https://user-images.githubusercontent.com/41816449/230501173-142f89ea-bc9c-4ca1-bf4e-3130b681fde4.png)

导致无法创建和打开文档，我应该还需要做更多的变更，但我不确定还有哪些地方是我必须要更改的。

**Comment by 88250** [comment]
这个不考虑支持了，还是建议通过域名区别，谢谢。

**Comment by ylsislove** [comment]
@88250 可以说下不考虑的原因吗，是因为要变动的地方太多，还是说可能会出现不可预知的Bug，又或者是需求太小众，暂不支持考虑😂

**Comment by 88250** [comment]
三者皆有……

**Comment by ylsislove** [comment]
好吧
