### ISSUE TITLE
Save the new window layout

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7913]
重载界面后新窗口页签丢失

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

步骤：
1. 新开窗口，并继续添加页签
2. 无论在主窗口或新窗口使用转移引用功能
3. 主窗口、新窗口刷新，新窗口页签丢失

### Expected result

新窗口页签不丢失。（或将“转移引用功能”后台执行）

### Version environment

```markdown
- Version: v2.8.3
- Operating System: 
- Browser (if used):
```

### Log file

1

### More information

1

**Comment by 88250** [comment]
经过排查，主要是因为重载界面导致的问题 @Vanessa219
