### ISSUE TITLE
Build an English forum

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7914]
https://github.com/siyuan-note/siyuan/issues/7758

Some basic ideas:

* Use email verification to signup
* The forum does not set up topic grouping, that is, posts are not classified
* Use the point system, post to deduct points, and receive "Thank" to get points
* Use Bing, no built-in search engine
* Use https://twitter.com/b3logos for announcements

**Comment by ciceronianus** [comment]
For inspiration: I really like the style of the forum for Kinopio.club: see [club.kinopio.club](https://club.kinopio.club/).

**Comment by 88250** [comment]
The English forum will use our self-developed forum system (same as https://ld246.com), but will make some appropriate simplifications.

**Comment by 88250** [comment]
English forum testing: https://liuyun.io/
