### ISSUE TITLE
After switching tabs, reposition by range

### ISSUE THREAD

**Issue by UFDXD** [siyuan-note/siyuan#7915]
页签分屏后丢失浏览定位

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

步骤：
1.打开一个文档页签
2.文档浏览到任意位置
3.拖动文档页签分屏
4.页签文档丢失文档定位

### Expected result

页签拖动分屏不丢失文档定位

### Screenshot or screen recording presentation

1

### Version environment

```markdown
- Version: v2.8.3
- Operating System: 
- Browser (if used):
```

### Log file

1

### More information

1

**Comment by Vanessa219** [comment]
目前只能将原有光标位置移动到屏幕内。如果未曾有过光标的话，分屏宽度变化导致原有内容上下移动还没有算法对其计算定位。
