### ISSUE TITLE
Parse error when hyperlink dest/title in tables contain `|` symbol

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

表格中的超链接或图片的 链接/锚文本/标题 中包含 `|` 符号时渲染错误  
Rendering error when a hyperlink or image in a table contains the `|` symbol in the Link/Anchor Text/Caption

### Expected result

优化解析器以对超链接或图片中的 `|` 符号进行兼容  
Optimize the parser to be compatible with the `|` symbol in hyperlinks or images

例如使用 `\|` 对 `|` 进行转义  
For example, `\|` is used to escape `|`

### Version environment

```markdown
- Version: 2.8.4-dev1
- Operating System: 
- Browser (if used):
```

### Log file

无有效信息输出  
No valid information output

### More information

下面的 markdown 片段貌似 GitHub 的渲染器也无法兼容...

```markdown
|                 |                 |                 |
| --------------- | --------------- | --------------- |
| ![👉|👈](1 "1") | ![2](👉|👈 "2") | ![3](3 "👉|👈") |
| [👉|👈](1 "1")  | [2](👉|👈 "2")  | [3](3 "👉|👈")  |
```

|                 |                 |                 |
| --------------- | --------------- | --------------- |
| ![👉|👈](1 "1") | ![2](👉|👈 "2") | ![3](3 "👉|👈") |
| [👉|👈](1 "1")  | [2](👉|👈 "2")  | [3](3 "👉|👈")  |

需要使用 `\|` 符号进行转义
```markdown
|                 |                 |                 |
| --------------- | --------------- | --------------- |
| ![👉\|👈](1 "1") | ![2](👉\|👈 "2") | ![3](3 "👉\|👈") |
| [👉\|👈](1 "1")  | [2](👉\|👈 "2")  | [3](3 "👉\|👈")  |
```

|                 |                 |                 |
| --------------- | --------------- | --------------- |
| ![👉\|👈](1 "1") | ![2](👉\|👈 "2") | ![3](3 "👉\|👈") |
| [👉\|👈](1 "1")  | [2](👉\|👈 "2")  | [3](3 "👉\|👈")  |

**Comment by 88250** [comment]
重现步骤是将 Markdown 直接复制粘贴到编辑器中吗？

**Comment by Zuoqiu-Yingyi** [comment]
> 重现步骤是将 Markdown 直接复制粘贴到编辑器中吗？我这里测试好像正常：
> 
> ![image](https://user-images.githubusercontent.com/873584/230762267-8660aabd-7c37-462f-8c07-7b029863fb17.png)

在插入行级元素的输入框中输入, 之后需要在其他单元格随便输入一些字符

**Comment by 88250** [comment]
> 在插入行级元素的输入框中输入

抱歉，我没看懂你说的是哪个输入框，麻烦截图。

**Comment by Zuoqiu-Yingyi** [comment]
> 抱歉，我没看懂你说的是哪个输入框，麻烦截图。

直接上录屏吧

![思源笔记-bug反馈-47](https://user-images.githubusercontent.com/49649786/230782783-990edda6-7a9a-4437-85be-94122c4ea3be.gif)
