### ISSUE TITLE
Nested page titles

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7919]
### In what scenarios do you need this feature?

Sometimes pages grow quite big and it is time to separate them, however, there is an issue: how to see all pages that are connected one to another?

In Roam, LogSeq or RemNote, one can use nested titles. This means, that I can create something like [[[[TEI-XML]] - conversions]]. I can click on TEI-XML to get a general page on TEI-XML if I want.

![image](https://user-images.githubusercontent.com/63197393/230606566-cddf7e90-a6a9-4d3c-973f-bad701617a84.png)

Or click on the whole title.

LogSeq even allows for hierarchies when using "/" in the title of the page. See the example. 
![image](https://user-images.githubusercontent.com/63197393/230606744-0f465b25-caa7-429d-9d15-d209c13d2b6c.png)

SiYuan has already folders but they don't work very practically at the moment.

### Describe the optimal solution

I see two possible solutions: 
- One could use references to other pages within page titles like anywhere else in the text.
- One could use something like / character in the page title, this would put the note into the respective path. Somewhere then would be visible all related pages.

### Describe the candidate solution

Provide a simple button, e.g., next to the page title where when clicked, would reveal in the doc trea the respective folder in the open state.
![image](https://user-images.githubusercontent.com/63197393/230607131-052b7f46-45e0-4bf0-8596-4073eab5bcd5.png)

**Comment by 88250** [comment]
Thanks for the suggestion, but unfortunately neither of these two candidates is currently possible.

We have closed this issue. If there is a solution in the future, we will consider reopening it, thank you.

**Comment by ciceronianus** [comment]
I completely understand. What about seeing a list of all files under one file in some clearer form?
