### ISSUE TITLE
页内搜索图片不显示，且搜索完成后自动跳转回搜索前的位置

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#792]
### 描述问题 Describe the problem

1. 页内搜索图片不显示，但是正常浏览时正常显示
2. 搜索完成后自动跳转回原来的位置，但不希望跳转
3. 导出成pdf时也有1中图片不显示的内容

### 截屏或录屏演示 Screenshot or screen recording presentation

![siyuan](https://user-images.githubusercontent.com/16791452/102706523-a04c0e80-42cd-11eb-811d-f90c59fef479.gif)

### 版本环境 Version environment

* 版本 Version：0.5.41
* 操作系统 Operating system：win10

* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，目前的版本应该已经修复，如果还有问题请继续跟帖，谢谢。
