### ISSUE TITLE
将外界复制内容直接拖拽

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#7922]
### In what scenarios do you need this feature?

无论是移动端还是桌面端,都无法将文字或图片从浏览器等地方直接拖拽进APP,我想添加这个功能

### Describe the optimal solution

.

**Comment by 88250** [comment]
这个估计不好实现，现在还有其他开发任务，所以没有时间研究，抱歉抱歉。

建议使用复制粘贴。

**Comment by linglongyoudoufu** [comment]
可以加入到长远 的计划中吗,备个案
&nbsp;


愚者.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月7日(星期五) 晚上11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] 将外界复制内容直接拖拽 (Issue #7922)





 
这个估计不好实现，现在还有其他开发任务，所以没有时间研究，抱歉抱歉。
 
建议使用复制粘贴。

**Comment by Soltus** [comment]
[安卓端支持外部打开图片文件 ](https://github.com/Hi-Windom/Sillot/issues/473)
[安卓系统文本选择菜单汐洛选项](https://github.com/Hi-Windom/Sillot/issues/472)
