### ISSUE TITLE
Allow changing headings with `#`

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7924]
### In what scenarios do you need this feature?

Currently, if I write, e.g., 
`# Headline`
It will be converted into a headline:
# Headline
That is a great feature! However, if I want to change the depth of the headline, I have to use backspace to return in into non-formatted state and then writte # again. This takes more time than necessary

### Describe the optimal solution

When I position my cursor on the beginning of the line, it should be possible to change the depth of the headline in the same way as it was created. 
E.g.,
original headline was:
`# Headline`
Then I position my cursor an the beginning and write two ##, 
![image](https://user-images.githubusercontent.com/63197393/230646913-9dfd8f18-e19a-46d4-b00b-f5718e1d2e68.png)
Then the headline is automatically converted into H2:
![image](https://user-images.githubusercontent.com/63197393/230646960-5a702b3b-0da5-4a6e-b69e-d41683db5564.png)
This would make process of changing headlines more consistent and easier.

**Comment by woniuxia** [comment]
+1
