### ISSUE TITLE
Page title and headlines are too similar - customization?

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7925]
### In what scenarios do you need this feature?

Currently, I find the page title and headlines (especially H1 and H2) very, very similar and it is difficult to differentiate them by looking at them. 
![image](https://user-images.githubusercontent.com/63197393/230647508-1f8ab3fd-6262-418f-9c91-2853c9b3a5cd.png)

### Describe the optimal solution

I have no perfect solution but I could imagine, e.g., allowing the user to customize headlines in the appearance settings. 
Or something like my custom theme for Obsidian (optionally): 
![image](https://user-images.githubusercontent.com/63197393/230647833-dadea1cb-fa9b-4633-974c-07508d24c0f5.png)

**Comment by 88250** [comment]
Hello, please try custom theme or code snippet. The default theme will not be adjusted for the time being, thanks for the feedback.

**Comment by ciceronianus** [comment]
Sure, this is not something that has to be done but it is detail in which many note-taking apps (imho) fail: i.e. to differentiate clearly between different headlines. I will test custom CSS.
