### ISSUE TITLE
Allow shift + click in the doctree to select multiple files (or something similar)

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7926]
### In what scenarios do you need this feature?

In File Explorer and many other apps, I can click on an item, hold shift and click on another in a list to select multiple items.
![image](https://user-images.githubusercontent.com/63197393/230660333-2be4cecf-4597-463a-aa21-c7fbe70316d9.png)
This does not seem to be possible in DocTree.

### Describe the optimal solution

Allow shift + click to select multiple items or provide a similar interaction that would allow for selection of multiple files.

**Comment by 88250** [comment]
Hello, Shift+Click has been used to open the document in the down split screen.

**Comment by ciceronianus** [comment]
I understand. I would just encourage using standard UX interactions from Windows and Mac as much as possible .).
