### ISSUE TITLE
Cannot replace target text with markup

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#7927]
无法替换带有标记的目标文本

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

无法替换带有标记的目标文本

### Expected result

可以正常替换带有标记的目标

### Screenshot or screen recording presentation

![替换出错](https://user-images.githubusercontent.com/74853597/230697182-74091c4d-08e6-4304-9c44-414824205c4b.gif)

### Version environment

```markdown
- Version: 2.8.3
- Operating System: win 10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
感谢反馈，无法支持跨元素替换。

先关闭了，如果以后有方案再打开，谢谢。
