### ISSUE TITLE
Custom icon copying is not working

### ISSUE THREAD

**Issue by loopodi** [siyuan-note/siyuan#7928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Copying custom icons will create HTML block or code.

### Expected result

Copying like regular text

### Screenshot or screen recording presentation

![icon](https://user-images.githubusercontent.com/85782310/230701126-4af4f671-cdbb-4bf6-b30a-99dd21880b2a.gif)

### Version environment

```markdown
- Version: v2.8.3
- Operating System: Win10
- Browser (if used):
```

### Log file

No response

**Comment by Vanessa219** [comment]
7557c77b9fd0121d125bf05d00e7a893b72e7968
