### ISSUE TITLE
关系图搜索过滤和渲染参数配置

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#793]
## 全局关系图

* 搜索过滤
* 渲染参数

## 文档关系图

* 搜索过滤
* 按块类型区分颜色
* 渲染参数

**Comment by lss6378** [comment]
关系图上可预览预览卡片，和正常的块预览一样，可钉住就完美了：
![图片](https://user-images.githubusercontent.com/15924513/105708329-43d4b280-5f4f-11eb-9702-d28681a5e04a.png)
