### ISSUE TITLE
搜索界面分类默认设置

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#7930]
### In what scenarios do you need this feature?

为更好的搜索，建议可以设置分组的默认选项

### Describe the optimal solution

![image](https://user-images.githubusercontent.com/107289739/230718639-2c5de8e8-f81a-4f21-80cf-c81257eb4dba.png)

**Comment by 88250** [comment]
请使用命名查询来保存/载入搜索条件。
