### ISSUE TITLE
Improve the back button when browsing pictures on the Android

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#7938]
https://ld246.com/article/1681034346654

**Comment by Soltus** [comment]
图片的关闭按钮就正常的放在右上角就可以了，而不是和其他按钮混在一起。返回键逻辑就不用额外处理了吧

**Comment by Vanessa219** [comment]
a61e861503a7a3a6523900e45628e576e55a1839

**Comment by 88250** [comment]
滑动返回也是常规操作，支持一下没问题的。
