### ISSUE TITLE
API `/api/filetree/createDailyNote` 返回创建/已存在的文档信息 | API `/api/filetree/createDailyNote` Returns the document information that was created/existed

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#7941]
### In what scenarios do you need this feature?

计划使用内核 API 实现一个功能更加丰富的收集箱安卓 App, 但是仅使用内核 API 无法十分方便的获得当日 Daily Note 文档的信息  
I plan to use the kernel API to implement a more feature-rich Inbox App for mobile, but it is not very convenient to obtain the daily note information using only the kernel API

### Describe the optimal solution

希望可以从已存在的 API `/api/filetree/createDailyNote` 的响应体中获得 新建的/已存在 的当日 Daily Note 的文档信息  
I want to get created/existing document information from the response body of existing API `/api/filetree/createDailyNote`

**Comment by 88250** [comment]
用 SQL 接口搜索吧，这个 createDailyNote 没有公开，最好不要依赖。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
