### ISSUE TITLE
容器部署时可以支持持久化配置

### ISSUE THREAD

**Issue by fimreal** [siyuan-note/siyuan#7944]
### In what scenarios do you need this feature?

使用 swarm 或者 k8s 部署服务，避免不了容器重启，希望配置能提供一个优雅的持久化方案，不必要每次重新启动都要重新配置云同步

### Describe the optimal solution

做了一些小尝试，首先是看到配置都在 `conf/conf.json` 中存放，尝试挂载该文件到容器内会报错。试着覆盖 `conf/conf.json` 文件也不生效，应该是行不通的。

想了下如果挂载整个 conf 目录，会因为 `conf/` 目录下 `appearance/` 目录占用非常高，没办法使用 k8s configmap，单为了配置持久化用网络存储有点小题大做。

一个不完美的解决办法就是配置完容器，commit 后推到仓库自己用，代价可能是失去更新能力，每次配置修改都需要重新打包容器。

想象中比较完美的方式，就是能在初始化完成后，可以加载一个 ignition.json，覆盖原来 conf.json。源码中启动会执行 `model.InitConf()` 初始化配置文件，要是后面能增加读取自定义配置文件或者 url 就好了

**Comment by 88250** [comment]
conf 是在工作空间文件夹下的，挂载工作空间文件夹已经包含了 conf 了。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by fimreal** [comment]
就是想不挂载这个目录，`conf` 目录里 `appearance/` 体积太大了

**Comment by 88250** [comment]
不挂载的话无法保证工作空间的完整性哦。

**Comment by fimreal** [comment]
问题点也在于，工作空间内容保存问题可以通过同步存储解决，但是配置不行
