### ISSUE TITLE
The outline item in the outline panel supports dragging to adjust the level and position

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7957]
### In what scenarios do you need this feature?

First, I completely understand if this will not get implemented but maybe it could be interesting for you in future. 

What I would like to do sometimes is to reorganize a large document. Making outline panel more powerful could solve it.

### Describe the optimal solution

The outline panel could have the following functions:
1) Drag and drop to reorganize parts of the document. 
2) One could move the whole heading to another note and, if wished, to replace it with a link or embed. This would be triggered by the context menu.

![image](https://user-images.githubusercontent.com/63197393/231225604-f615abab-770c-4b39-9d25-e773627ca5c3.png)
![image](https://user-images.githubusercontent.com/63197393/231225672-acd2bdf0-8124-4679-8364-b940281beb0a.png)

**Comment by linglongyoudoufu** [comment]
希望能快点上线

**Comment by TCOTC** [comment]
希望调整大纲也能像调整文档树那样简单，操作逻辑可以是一样的。

**Comment by Achuan-2** [comment]
+1

**Comment by 5kyfkr** [comment]
+1社区提这个的人越来越多了

**Comment by TCOTC** [comment]
思源用户的文档内容记得越来越多了，有这样的需求也是自然而然的

**Comment by 5kyfkr** [comment]
D大有空试试Lattics吧，基本都靠拖拽实现文章管理和编排，实现后真的很方便

**Comment by 88250** [comment]
现在是产能不足……

**Comment by 5kyfkr** [comment]
D大可以考虑做个调查统计问卷，问卷设置个问题就能区分现有轻度和重度用户的情况，筛选一下就知道各种用户哪里需要改进的功能较多，这样也可能事半功倍，靠社区和github的声量我感觉会忽视掉很多沉默的用户的需求

**Comment by TCOTC** [comment]
把 Discussions 打开搞个简单的投票我觉得不是不行

**Comment by 5kyfkr** [comment]
> 把 Discussions 打开搞个简单的投票我觉得不是不行

不一样吧，看了下也只能像论坛的投票问一个问题，问卷星那些的可以一次问多个，就能组合筛选不同使用程度用户的答案，而且也能设置回答完马上显示结果的

**Comment by 88250** [comment]
> D大可以考虑做个调查统计问卷，问卷设置个问题就能区分现有轻度和重度用户的情况，筛选一下就知道各种用户哪里需要改进的功能较多，这样也可能事半功倍，靠社区和github的声量我感觉会忽视掉很多沉默的用户的需求

我们心里有谱的，放心好了。

**Comment by Vanessa219** [comment]
```
tx "moveOutlineHeading" {id, parentID, previousID}
```
