### ISSUE TITLE
Ctrl+Enter creates a task or completes it

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7958]
### In what scenarios do you need this feature?

Currently, there is no way how to quickly convert an item into a taks. 
CTRL+L creates a task list but does not convert the current item into a task.

![image](https://user-images.githubusercontent.com/63197393/231257549-09213363-56ee-467d-b426-f283d49e9cb0.png)

### Describe the optimal solution

The solution would be to use ctrl + enter. ctrl + enter currently completes tasks, however, it could also create a task if there is none at the moment. This is the solution that can be found in some other apps.

**Comment by 88250** [comment]
At present, we already support entering `[]` at the beginning of a non-empty block to convert it to a task list item, and `Ctrl+Enter` conversion is not considered for the time being, thanks for the feedback.
