### ISSUE TITLE
Context menu in outline panel

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7959]
### In what scenarios do you need this feature?

This is related to my previous suggestion: to allow using drag and drop to move different headings and all sections within a document and a context menu to move them into another page.

What if it would be possible to have the complete context menu in the outline panel? This would allow for changing headlines (like from h1-h4), changing their appareance directly from the outline menu, moving them, copying them, adding attributes.

### Describe the optimal solution

Adding the context menu to the outline panel, similar to this one: 

![image](https://user-images.githubusercontent.com/63197393/231268629-c82512c2-4606-4234-b7ed-40e93f7b0d41.png)

**Comment by 88250** [comment]
Try hovering over the block icon of the heading item in the outline panel, then click the block icon in the floating window:

![image](https://user-images.githubusercontent.com/873584/232371738-a6f43d24-d3b4-4740-aedc-a5aba567d9de.png)

Adding the context menu directly will not be considered. It is better to unify the entry of the block in the block icon menu of the editor. Thanks for the suggestion.
