### ISSUE TITLE
Bullet point backlink collapse state doesn't match current block state (low priority)

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#7966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

- I created a bullet point list block where the root bullet point contains a reference link to some different document
- Then I created child bullet points
- The root bullet point is not collapsed so all child nodes are displayed in the origin block
- Next I open the root bullet points referenced document and open the backlink view or backlink number count.
  The backlink window displays the root bullet point as collapsed where the origin bullet point list is still expanded.
  However if I change collapse state in the backlink window (expand the list and collapse it next) the state of the origin block is   modified to collapsed.

Is the backlink window bullet point list collapsed by default (which would break the same rendering state between origin and backlink window) or is this possibly a low-priority bug?

### Expected result

I would expect that the origin bullet point block state (expanded or collapsed) is used at the backlink window and not collapsed as default.

### Screenshot or screen recording presentation

![Animation2](https://user-images.githubusercontent.com/13854802/231444060-82dbb08b-f2b0-4087-b085-6e9c725b05f2.gif)

### Version environment

```markdown
- Version: 2.8.4
- Operating System: Win10
- Browser (if used): none
```

### Log file

none

**Comment by 88250** [comment]
Hello, thank you for your feedback, but we can't do this at present, that is, we can't support the separation of the folded state, we are very sorry.

We have considered solving this problem before, but until now we still haven’t found an easy-to-implement solution. If there is any progress, we will reopen this issue, thank you.
