### ISSUE TITLE
Ability to delete a doc from `⋮`

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7969]
### In what scenarios do you need this feature?

Currently, a page can be deleted only from a menu that appears when I click on a small "documnet" icon next to the page title. 

Somehow I find it unintuitive and difficult to click on. 

What if the "delete" the page (and ideally also "merge" the page) were under "⋮" menu that currently shows this:

![image](https://user-images.githubusercontent.com/63197393/231515338-ace854dd-abeb-4820-b9f4-c3374105a751.png)

### Describe the optimal solution

Consider providing an option to delete a document from "⋮" menu.

**Comment by Vanessa219** [comment]
Can be removed from the doc icon.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/970828/231622861-c09e648d-0dc9-4fda-815a-290e90b46e62.png">

<img width="373" alt="image" src="https://user-images.githubusercontent.com/970828/231622971-c1cac8e6-e0e0-4037-8c94-97aa84be3ff0.png">

**Comment by ciceronianus** [comment]
I know that there is this way. But I think that many people will look for that under those dots like me. It is also easier to click on them.

**Comment by 88250** [comment]
You are right, here we have to improve it to match the user's usage habits.
