### ISSUE TITLE
Supports quick search for block styles using "red", "green", etc.

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7970]
### In what scenarios do you need this feature?

I really like using `/` to call out options and select some of the colors available.

![image](https://user-images.githubusercontent.com/63197393/231516394-7d2a673e-f318-45bc-8e74-0bbfb928bc28.png)

What happens to me often is that I type "red" or "green" and I don't get anything, because the styles are called "Error", "Warning" etc. 

### Describe the optimal solution

I suggest to rename the styles because their current names are rather for programmers and don't correspond to the use of other people. 

Possibilities:
- Error style -> Error / Red style
- Error style -> Red style

I would also welcome more colors available directly from the `/` menu (but not too many, just like more than 4).

**Comment by Vanessa219** [comment]
This color can be customized from custom.css, if the user changes red to pink, it will be a bit weird to search for `red`.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/970828/231624006-88034f5d-4fff-495d-8acd-f9b23c3156fe.png">

**Comment by ciceronianus** [comment]
> This color can be customized from custom.css, if the user changes red to pink, it will be a bit weird to search for `red`.
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/970828/231624006-88034f5d-4fff-495d-8acd-f9b23c3156fe.png">

Then maybe another solution? Because for people outside of the programming world, these terms don't correspond to their usage.

**Comment by 88250** [comment]
There is indeed a problem if we search by color here, because the colors do not match after changing some themes.

There is no good alternative for now, so it is closed first, thank you for your understanding.

**Comment by ciceronianus** [comment]
Alternatives: 
- What about making "appearance" submenu accessible from / command? 
- Or picking up a couple of colors from appearance menu and putting them in the / command directly?

**Comment by 88250** [comment]
Select a block (select the current block by Esc, if you want to select the parent block, you can expand it by Shift+↑) and then use Ctrl+/ to switch out the block label menu.
