### ISSUE TITLE
Add `- `, `* `, `1. ` and `[] ` before the heading then convert it into the list with that heading

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7972]
### In what scenarios do you need this feature?

When I add "-" in front of the line, I get a list.
However, this does not work if the line is already headline.

![image](https://user-images.githubusercontent.com/63197393/231569445-4608fecb-f936-41de-856e-66efea3e57ca.png)

### Describe the optimal solution

Make possible to write "-" in front of the headline to convert it into the bulleted headline.

**Comment by Temacc0531** [comment]
First, use `Backspace` to clear the title format, and then use `-` to become a list type

**Comment by ciceronianus** [comment]
> First, use `Backspace` to clear the title format, and then use `-` to become a list type

Sure, but this means a lot of steps and I find it unnecessary. I tested now one of my markdown editors and it does this without issues.

It is a little thing but so is polishing :)
