### ISSUE TITLE
搜索结果中的列表块

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#798]
# 列表块

某一篇笔记里有这样的内容：

![image](https://user-images.githubusercontent.com/32661922/102730878-1ce3f900-4371-11eb-92b4-7e098208c3ae.png)

搜索其中的关键词的时候，会显示两个结果项：

![image](https://user-images.githubusercontent.com/32661922/102730931-456bf300-4371-11eb-8698-4cf840c3c3d1.png)

感觉在搜索结果里只显示列表项块就好了，现在这样相当于一个关键词在搜索结果里重复出现了两次

**Comment by 88250** [comment]
你好，搜索里还是尽量要展示所有块类型，因为在搜索结果上支持右键引用。另外，如果只是展示容器块的话，其实文档块就够了……

我关闭了，如果需要继续讨论请跟帖，谢谢。

**Comment by deerainw** [comment]
好的，重新想了想，感觉无解 😟
