### ISSUE TITLE
文字无法被修改

### ISSUE THREAD

**Issue by remoon1991** [siyuan-note/siyuan#7980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文字被备注或者评论后，无法被修改。
而且相同一行文字，只能备注或评论，无法同时对一行文字备注评论。

### Expected result

能够解决该文字，将备注像“评论”那样都显示在最下端

### Version environment

```markdown
- Version: 最新版本
- Operating System: win11 家庭版最新版
- Browser (if used): chrome
```

### Log file

none

**Comment by zxhd863943427** [comment]
我想思源是不支持评论的，这个估计是第三方主题和插件提供的功能。

文字被备注后，无法被修改。这个无法复现。

麻烦切换到默认主题后，给个动图或视频，方便复现和修复。

**Comment by zxhd863943427** [comment]
至于将备注像“评论”那样都显示在最下端……恕我不能支持了。

**Comment by 88250** [comment]
如果是扩展的问题麻烦到对应的扩展仓库上反馈，谢谢。

我先关闭了，如果还有其他问题请继续跟帖，谢谢 :pray:
