### ISSUE TITLE
About the search function

### ISSUE THREAD

**Issue by pizixi** [siyuan-note/siyuan#7983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1、After the search results are sorted and grouped, only the current search result takes effect
2、The search box is too large, and it is easy to touch it by mistake when closing the search box, resulting in closing the entire program

### Expected result

above

### Version environment

```markdown
- Version: v2.8.4
- Operating System: win10
- Browser (if used):
```

### Log file

.

**Comment by 88250** [comment]
1. Please try to use “Named Criterion” to save search conditions

   ![image](https://user-images.githubusercontent.com/873584/231742868-2bd30fd4-203b-4ff1-8292-f40a670d59dc.png)

2. Please watch https://github.com/siyuan-note/siyuan/issues/7676

Thanks.

**Comment by pizixi** [comment]
ok,Thanks
