### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#7985]
### In what scenarios do you need this feature?

Generally we do not remember the case of the text. So, it would be helpful if case insensitive search feature is available in `ctrl+f` / `ctrl+p`

### Describe the optimal solution

It would be helpful if we could have a button next to existing options to enable/disable case sensitivity just like IDE's (e.g. VS Code, PyCharm), and also show placeholder text like `Find` or `Type to search`

Current search UI
![image](https://user-images.githubusercontent.com/42742240/231741071-86d4b499-33f4-437e-82b4-3339428c3a24.png)

VS Code option to enable/disable case sensitivity
![image](https://user-images.githubusercontent.com/42742240/231740895-1a657747-eacb-418f-9f38-84e0488b4754.png)
Vishal

**Comment by 88250** [comment]
Hello, I can understand the importance of this requirement, but unfortunately, SiYuan cannot support dynamic switching of case. Every time you switch search case support, you need to rebuild the index.

![image](https://user-images.githubusercontent.com/873584/231744284-7d574f5c-c95d-401e-a485-668f9562dbaf.png)

**Comment by fenilgmehta** [comment]
Thanks a lot for pointing me to the right place in settings 🙏
