### ISSUE TITLE
有没有想过把思源笔记做成headless cms？

### ISSUE THREAD

**Issue by Ahidada** [siyuan-note/siyuan#7987]
### In what scenarios do you need this feature?

目前的headless cms的文档编辑和渲染没有思源的好，所以希望思源笔记能不能打通笔记软件和headless cms的桥梁

### Describe the optimal solution

1."思源headless cms"在"思源笔记"上把数据存入数据库、并且增加一些通过UI设置数据和CRUD的功能、再加上角色和用户权限管理、图片-文件-视频等资源管理等功能
2.做一个"思源渲染.js",方便前端可以在一个类似\<div\>这样的元素内对具体的某一篇文章进行“思源渲染”

**Comment by 88250** [comment]
原生的话不考虑了，如果实在需要请自行通过 API 进行扩展，感谢反馈。
