### ISSUE TITLE
Global search breaks after using `Ctrl+F`

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#7988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Steps to reproduce:
1. Open any document
2. Press `ctrl+f` to perform search in the open document
3. Press `Esc` to close the search panel
4. Press `ctrl+p` to open global search panel

### Expected result

**Observed** interface
![image](https://user-images.githubusercontent.com/42742240/231746405-0d64402d-9baa-4e1c-a0a1-6799bf5e8d74.png)

**Expected** interface
![image](https://user-images.githubusercontent.com/42742240/231746086-5fcaae25-a801-48e9-8d3d-161a68a25760.png)

### Version environment

```markdown
- Version: 2.8.2
- Operating System: Fedora 25, KDE
```

### Log file

Not needed as steps for reproducing the bug are given above

**Comment by Vanessa219** [comment]
Because of https://github.com/siyuan-note/siyuan/issues/7745, you must follow this, otherwise keep the last query condition.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/970828/232050981-fdf1eb3a-94e8-470a-b989-37964ba90a29.png">

**Comment by choyy** [comment]
不修复一下吗

**Comment by Vanessa219** [comment]
@choyy 这个是特性，在使用过命名后才会记录，否则保持上一次的搜索条件。可参看 https://ld246.com/article/1679284103263

**Comment by choyy** [comment]
那个也是我提的，是想保持上次搜索的关键字，但并不想保持ctrl f。快捷键的优先级应该比保持搜索条件高吧，上次搜索关键词保留，而ctrl f就是ctrl f，ctrl p就是ctrl p

**Comment by Vanessa219** [comment]
Ctrl+F 也属于搜索，ctrl+P 中不想保持的话，可以使用命名查询

**Comment by choyy** [comment]
问题是我Ctrl p却仍然保持ctrl f

**Comment by choyy** [comment]
我想保持关键词，命名查询做不到

**Comment by Vanessa219** [comment]
可以的呦，你按照这个步骤进行


https://user-images.githubusercontent.com/970828/234752912-0e0ae2c0-d8f0-4bc4-900e-3f2a7f201c21.mp4

**Comment by choyy** [comment]
你这是每次都保存“拖动”这个词吧，并不是上一次的关键词

你确定视频里的东西和这个链接里特性一样？

> @choyy 这个是特性，在使用过命名后才会记录，否则保持上一次的搜索条件。可参看 https://ld246.com/article/1679284103263

**Comment by Vanessa219** [comment]
这个是保持 ctrl+p 的，如果需要保持 ctrl+f 的可以点击一下
<img width="231" alt="image" src="https://user-images.githubusercontent.com/970828/234842704-3d491491-0366-48a7-a263-ccad71f2a57c.png">

**Comment by choyy** [comment]
用ctrl P搜索关键词“1”，然后搜索完了，下次打开搜索界面时搜索框默认保持关键词“1”；
然后再用ctrl P搜索关键词“2”，然后搜索完了，下次打开搜索界面时搜索框默认保持关键词“2”；
对于这个功能，命名查询做不到，是不是这样？？

> 我想保持关键词，命名查询做不到

**Comment by Vanessa219** [comment]
可以的呦，你按照上面我说的打开思源笔记试一下。具体可以看一下这个视频。


https://user-images.githubusercontent.com/970828/236597824-325283d9-02af-4996-96c0-5210d050253c.mp4

**Comment by choyy** [comment]
视频里只看到选词搜索的操作，并没有看到用ctrl p打开搜索界面后是否保留关键词

**Comment by Vanessa219** [comment]
可以的

**Comment by choyy** [comment]
可否麻烦给个演示，我没找到如何操作

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/assets/970828/1dbde5de-d2ed-48a2-ae6b-6fe9b7205d41

**Comment by choyy** [comment]
这个视频中你只搜索了“新建笔记本”，搜索只会保持这个关键词不会保持其他关键词

**Comment by Vanessa219** [comment]
是的，这样就可以保存上一次的搜索了。
