### ISSUE TITLE
docker version boot failure

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#7989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我运行了这个命令

```bash
docker run -d -v /root/思源:/siyuan/workspace -p 8000:6806 b3log/siyuan –restart=always --workspace=/siyuan/workspace
```

返回了错误

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: chdir to cwd ("/opt/siyuan") set in config.json failed: operation not supported: unknown.
```

### Expected result

应该可以启动啊

### Version environment

```markdown
- Version: b3log/siyuan:latest
- Operating System: OpenWrt 22.03.3 aarch64
- Browser (if used):
```

### Log file

没有

**Comment by 88250** [comment]
挂载卷之前 `/root/思源` 先创建好这个目录后再试试。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by a15355447898a** [comment]
> 挂载卷之前 先创建好这个目录（注意权限）后再试试。`/root/思源`
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢🙏

<img width="970" alt="image" src="https://user-images.githubusercontent.com/62456287/231917161-5cc892ba-b384-4c5a-9f6f-e26848228a06.png">
我已经创建了 /root/思源 这个目录 我的账户是root,应该没有权限问题

**Comment by 88250** [comment]
运行时容器的用户不是 root

**Comment by a15355447898a** [comment]
![4431aef9c2f65ca8](https://user-images.githubusercontent.com/62456287/231951524-f9cc1728-47d4-417b-b2b5-aee20d8c6de9.jpg)

把目录权限设置成777了，其他用户也应该可以读写了，但是还是有报错

**Comment by a15355447898a** [comment]
尝试在x86的archlinux上面复现错误,但是没有发生错误
似乎只能在arm设备上面复现

新尝试了运行
```bash
docker run -d -p 8000:6806 b3log/siyuan –restart=always
```
![1681460512612](https://user-images.githubusercontent.com/62456287/231987779-b4646b93-230e-4009-945f-8311c3e4d09b.jpg)
得到了一样的报错
```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: chdir to cwd ("/opt/siyuan") set in config.json failed: operation not supported: unknown.
```

**Comment by 88250** [comment]
估计得自己研究一下了，我无法给出建议，抱歉抱歉。
