### ISSUE TITLE
File suddenly missing from file tree

### ISSUE THREAD

**Issue by ms3056** [siyuan-note/siyuan#799]
### 描述问题 Describe the problem

I had two files in my vault. I added a folder to the vault. I added FILE2 to the new folder. I can no longer see FILE1 in the file tree. When I try to create a new file with the same file name, SiYuan tells me "duplicate" - so it knows the file is there. 

The other file is in the file tree in the folder. The links between the files work fine. I just cannot SEE the file that is in the original vault location. 

I CAN see the file in Windows Explorer, however. 

### 版本环境 Version environment

* 版本 Version：0.5.4.1
* 操作系统 Operating system：Win 10 Enterprise
* 浏览器（如果使用）Browser (if used)：Edge

**Comment by ms3056** [comment]
![SiYuan_file_error](https://user-images.githubusercontent.com/23712700/102750839-ee364480-43a9-11eb-8147-a7423e847c1c.png)

**Comment by 88250** [comment]
Hello, create a doc in a folder does not auto-expand the folder at present, please move the cursor to file tree you can see a right arrow to expand the folder.

**Comment by ms3056** [comment]
![file error2](https://user-images.githubusercontent.com/23712700/102764435-7b839400-43be-11eb-8ca2-dafddeb129be.png)

This is not the issue you are describing. The file is invisible in the tree, but I can link to it from another note.

**Comment by ms3056** [comment]
![Uploading error3.png…]()

Notice - I try to create a note of the same name, but it says there is a duplicate - yet - there is no visible file.

**Comment by ms3056** [comment]
Nevermind - I think there is some lack of my understanding - there are TWO vault folders. Please keep closed.
