### ISSUE TITLE
希望在docker版本增加共享笔记功能

### ISSUE THREAD

**Issue by lerogo** [siyuan-note/siyuan#7990]
### In what scenarios do you need this feature?

希望在docker版本增加共享笔记功能。
桌面版本可以导出pdf达到共享的目的，docker版本一年半载过了pdf依然不能导出。因此，希望增加docker版本共享笔记功能

### Describe the optimal solution

静态页面为佳，

**Comment by 88250** [comment]
抱歉，这个不考虑了，PDF 导出依赖 electron 所以无法在浏览器中实现。
