### ISSUE TITLE
文档块被引用数大于0，但反链面板显示空白（未找到相关内容）

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#7991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文档块被引用数大于0，点击数字位置可以看到所有被引用的地方，但反链面板显示空白（未找到相关内容）。
重建索引之后，再过一段时间，点击刷新，反链面板开始正常显示。

### Expected result

当文档块被引用数大于0，但反链面板显示空白（未找到相关内容）。自动重建局部索引。

### Version environment

```markdown
- Version: 2.7.5
- Operating System: Win 10
- Browser (if used):
```

### Log file

I 2023/04/13 08:02:37 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/04/13 08:02:38 runtime.go:57: kernel is booting:
    * ver [2.7.5]
    * arch [amd64]
    * os [Microsoft Windows 10 Home China 10.0.19045.2728 Build 19045.2728]
    * pid [11448]
    * runtime mode [prod]
    * working directory [D:\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\Brain2]
I 2023/04/13 08:02:38 runtime.go:103: use network proxy [system]
I 2023/04/13 08:02:38 serve.go:108: kernel [pid=11448] http server [127.0.0.1:1156] is booting
I 2023/04/13 08:02:40 working.go:396: built-in pandoc [ver=2.19.2, bin=D:\Brain2\temp\pandoc\bin\pandoc.exe]
I 2023/04/13 08:02:40 serve.go:121: reverse proxy server [127.0.0.1:6806] is booting
I 2023/04/13 08:02:45 blocktree.go:386: read block tree [23 MB] to [D:\Brain2\temp\blocktree], elapsed [3.32s]
I 2023/04/13 08:02:45 conf.go:626: database size [240 MB], tree/block count [5648/65345]
I 2023/04/13 08:02:45 working.go:157: kernel booted
W 2023/04/13 08:02:56 file.go:295: build docs [12] elapsed [1296ms]
W 2023/04/13 08:02:58 file.go:295: build docs [19] elapsed [1653ms]
W 2023/04/13 08:02:58 file.go:295: build docs [19] elapsed [1840ms]
I 2023/04/13 08:03:51 asset.go:88: loaded assets [66.01s]
I 2023/04/13 08:05:07 box.go:75: auto stat [trees=5648, blocks=65345, dataSize=973 MB, assetsSize=751 MB]
I 2023/04/13 08:05:07 disk.go:33: disk usage [total=742 GB, used=610 GB, free=132 GB]
I 2023/04/13 08:06:59 queue.go:147: database op tx [7425ms]
I 2023/04/13 10:05:08 box.go:75: auto stat [trees=5655, blocks=65370, dataSize=975 MB, assetsSize=753 MB]
I 2023/04/13 10:05:08 disk.go:33: disk usage [total=742 GB, used=610 GB, free=132 GB]
W 2023/04/13 10:48:36 blocktree.go:436: save block tree [size=0 B] to [D:\Brain2\temp\blocktree], elapsed [2.08s]
I 2023/04/13 12:05:10 box.go:75: auto stat [trees=5657, blocks=65381, dataSize=975 MB, assetsSize=753 MB]
I 2023/04/13 12:05:10 disk.go:33: disk usage [total=742 GB, used=610 GB, free=132 GB]
I 2023/04/13 13:31:29 queue.go:147: database op tx [7988ms]
W 2023/04/13 13:50:01 blocktree.go:436: save block tree [size=8.6 MB] to [D:\Brain2\temp\blocktree], elapsed [6.34s]
I 2023/04/13 13:50:04 queue.go:147: database op tx [9878ms]
I 2023/04/13 14:05:20 box.go:75: auto stat [trees=5657, blocks=65386, dataSize=975 MB, assetsSize=753 MB]
I 2023/04/13 14:05:20 disk.go:33: disk usage [total=742 GB, used=610 GB, free=132 GB]
I 2023/04/13 16:05:21 box.go:75: auto stat [trees=5657, blocks=65386, dataSize=975 MB, assetsSize=753 MB]
I 2023/04/13 16:05:21 disk.go:33: disk usage [total=742 GB, used=610 GB, free=132 GB]
I 2023/04/14 07:47:01 box.go:75: auto stat [trees=5657, blocks=65386, dataSize=975 MB, assetsSize=753 MB]
I 2023/04/14 07:47:01 disk.go:33: disk usage [total=742 GB, used=610 GB, free=132 GB]
W 2023/04/14 07:57:54 blocktree.go:436: save block tree [size=0 B] to [D:\Brain2\temp\blocktree], elapsed [4.83s]
W 2023/04/14 08:00:46 file.go:307: query root block ref count elapsed [744ms]
I 2023/04/14 08:00:57 queue.go:147: database op tx [9732ms]
W 2023/04/14 08:22:10 blocktree.go:436: save block tree [size=7.8 MB] to [D:\Brain2\temp\blocktree], elapsed [4.82s]
W 2023/04/14 08:22:30 blocktree.go:436: save block tree [size=7.5 MB] to [D:\Brain2\temp\blocktree], elapsed [4.41s]
W 2023/04/14 08:22:33 transaction.go:120: op tx [10619ms]
W 2023/04/14 08:22:39 transaction.go:120: op tx [6765ms]
W 2023/04/14 08:22:44 blocktree.go:436: save block tree [size=14 MB] to [D:\Brain2\temp\blocktree], elapsed [8.83s]
W 2023/04/14 08:23:36 blocktree.go:436: save block tree [size=4.8 MB] to [D:\Brain2\temp\blocktree], elapsed [2.72s]
I 2023/04/14 09:47:09 box.go:75: auto stat [trees=5660, blocks=65275, dataSize=975 MB, assetsSize=753 MB]
I 2023/04/14 09:47:09 disk.go:33: disk usage [total=742 GB, used=610 GB, free=132 GB]
I 2023/04/14 10:43:03 database.go:107: reinitialized database [D:\Brain2\temp\siyuan.db]
I 2023/04/14 10:43:04 index.go:132: rebuilt database for notebook [20220725213038-csm1kiz] in [0.59s], tree [count=260, size=1.1 MB]
I 2023/04/14 10:43:04 index.go:132: rebuilt database for notebook [20230317144207-qpy8o4j] in [0.01s], tree [count=10, size=25 kB]
I 2023/04/14 10:43:05 index.go:132: rebuilt database for notebook [20220324091819-431z1us] in [0.62s], tree [count=358, size=1.7 MB]
I 2023/04/14 10:43:13 index.go:132: rebuilt database for notebook [20211109165921-4ecaz78] in [8.19s], tree [count=5035, size=32 MB]
W 2023/04/14 10:43:17 blocktree.go:436: save block tree [size=13 MB] to [D:\Brain2\temp\blocktree], elapsed [13.07s]
W 2023/04/14 10:43:30 blocktree.go:436: save block tree [size=23 MB] to [D:\Brain2\temp\blocktree], elapsed [13.65s]
I 2023/04/14 10:43:35 index.go:205: resolved refs [574] in [4532ms]
I 2023/04/14 10:46:01 queue.go:147: database op tx [145694ms]
I 2023/04/14 10:47:58 queue.go:147: database op tx [33374ms]
I 2023/04/14 10:55:24 index.go:132: rebuilt database for notebook [20210808180117-czj9bvb] in [0.05s], tree [count=53, size=1.1 MB]
I 2023/04/14 10:55:28 index.go:205: resolved refs [595] in [3821ms]
W 2023/04/14 10:55:43 blocktree.go:436: save block tree [size=24 MB] to [D:\Brain2\temp\blocktree], elapsed [15.08s]

**Comment by 88250** [comment]
请更新到最新版后再试试。
