### ISSUE TITLE
API `listDocsByPath` add an optional parameter `maxListCount`

### ISSUE THREAD

**Issue by GuangDai** [siyuan-note/siyuan#7993]
### In what scenarios do you need this feature?

- I need an API to get all subdocs including the hidden docs in the filetree. The current API "/api/filetree/listDocsByPath" can only get limited docs.  The widget ListDocTree can only list limited docs.

### Describe the optimal solution

Maybe need to add an new api based on the listDocsByPath?

**Comment by 88250** [comment]
Hello, what is the usage scenario for this requirement?

**Comment by GuangDai** [comment]
> Hello, what is the usage scenario for this requirement?

In widget ListDocTree, I can only get limited results because of the global config. I have many docs(more than 100) in one dir. So I set the config to 30. If I raise the limit in global config, it will mess up my file tree. The widget  can display sub docs in several columns, which is much easier to find doc than doing it in file tree.

**Comment by 88250** [comment]
Understood, the next release will add a parameter `maxListCount` to this interface, which is used to specify the maximum list limit.

**Comment by GuangDai** [comment]
> Hello, what is the usage scenario for this requirement?

I hope there will be an api to get subdocs based on the para I requested. If 0, get all. If bigger than 0, get limited.

**Comment by 88250** [comment]
> I hope there will be an api to get subdocs based on the para I requested. If 0, get all. If bigger than 0, get limited.

It's a good idea!

**Comment by OpaqueGlass** [comment]
请问是否可以考虑在指定`maxListCount`时不再pushMsg提示；或增加参数忽略提示？

> 关联 https://ld246.com/article/1706681659402

**Comment by 88250** [comment]
> 请问是否可以考虑在指定`maxListCount`时不再pushMsg提示；或增加参数忽略提示？
> 
> > 关联 https://ld246.com/article/1706681659402

添加参数 `ignoreMaxListHint` https://github.com/siyuan-note/siyuan/issues/10290
