### ISSUE TITLE
When creating a new document through `((` , press `Tab` to specify its save path

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7995]
### In what scenarios do you need this feature?

I really love creating new document from [[ . Since in SiYuan the folders (parent documents) play an important role, I would like to sometimes save new documents into specific paths (person, work, glossary etc.). 

If I want to do it now, I have to create a document with [[, then open it, then move it and then close it. **A lot of steps.**

**A solution?** What if it would be possible to specify a path of a new document that is being created by [[ ?

![image](https://user-images.githubusercontent.com/63197393/231986101-7a38a8aa-b444-4f68-81ba-aac2fa4795bf.png)

I imagine something like like Quicksilver interaction, where one presses `Tab` that provides options what should be done with a document / app on the left. 

![image](https://user-images.githubusercontent.com/63197393/231986356-c3e29ee7-e1e4-46e2-b33a-f154f49a9a45.png)

### Describe the optimal solution

My proposed solution would be that if one creates a new document from [[, one could press `Tab` that would provide the person with the similar save dialog as the "move" provides. This would allow to quickly specify a path of the new document without the need to open it.

**Comment by GH-W94** [comment]
支持

**Comment by zxhd863943427** [comment]
The tab key could probably be used for a more useful purpose, which is type filtering after using `((` and entering a keyword. I think this is a more necessary interaction.

**Comment by ciceronianus** [comment]
I think that everybody needs something different. I need to easily manipulate documents and I see that this feature is currently not very well implemented. I propose the UI/UX language of Quicksilver and some other apps that is very flexible. You can adapt it to perform many different actions on any item. 

To be honest, I don't find the use of tab for your need as intuitive because of the vast number of filtering options that you can have. I also feel that the basic difference [[ and (( is for my personal needs enough if they work well, i.e. [[ for pages and (( for blocks. However, I understand you have different needs.

**Comment by ciceronianus** [comment]
However, having said this all, I could imagine a different key being used for my case instead of `tab`. E.g., a right arrow would probably work fine as well :).

**Comment by Vanessa219** [comment]
The right arrow is probably used to move the cursor, how about adding a selection path icon after the new document?
<img width="535" alt="image" src="https://user-images.githubusercontent.com/970828/233350423-0802d864-cb4e-4788-8879-42e70cf4ba0c.png">

**Comment by Aiviokoo** [comment]
> 右箭头大概是用来移动光标的，要不在新建文档后面加一个选择路径图标呢？ <img alt="图像" width="535" src="https://user-images.githubusercontent.com/970828/233350423-0802d864-cb4e-4788-8879-42e70cf4ba0c.png">

嗯嗯，可以加一个选择路径的图标（同时有一个快捷键，手就不用离开键盘了），这样创建的时候就能快速调出移动文档时的选择路径，方便用户通过搜索或直接在文档树选择该文档想要被安排的位置
![image](https://github.com/siyuan-note/siyuan/assets/87182333/2723d8b3-44a4-472c-b263-207abd524979)

**Comment by 88250** [comment]
This demand is not too common. Due to limited development resources, we will not consider it for the time being. Thank you for your understanding.
