### ISSUE TITLE
Tasklist bug

### ISSUE THREAD

**Issue by Yuminis98** [siyuan-note/siyuan#7998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

As shown in figure, in the default theme, check the task list, some check list item will line up and down, but others don't have an underscore.
![image](https://user-images.githubusercontent.com/117956441/231993453-a12ee5c1-a674-4b6e-9937-8f69a9555c53.png)

### Expected result

It should be underlined with the check box

### Version environment

```markdown
- Version: 2.8.4
- Operating System: win
- Browser (if used):
```

### Log file

without

**Comment by 88250** [comment]
Please export this .sy.zip then mail to 845765@qq.com, thanks.

**Comment by 88250** [comment]
We currently do not have a data set to reproduce this problem, so we will close it for now, thank you.
