### ISSUE TITLE
Holding `Shift` to hover a block ref to show backlinks of it

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#7999]
### In what scenarios do you need this feature?

One of the crucial parts of note-taking is an ability to discover connections between notes. SiYuan is good at it but it could be even better. 

I often write a note and then I link a specific word to an existing document by [[ or I create a new document by [[ . When I find that the document already exists, I would often like to know its connections / backlinks. In which other places I mention the same page / note? :) 

Currently, when I hover over a page, I get an editing window - which is great! 

![image](https://user-images.githubusercontent.com/63197393/231996526-24d20bc7-9d12-4a26-99ec-3d07d46fd93f.png)

However, would it be also **possible to somehow get backlinks?**

![image](https://user-images.githubusercontent.com/63197393/231996317-a0821180-d6e7-44d2-b2f2-1e9d520e7c72.png)

This would allow for much better and quicker navigation between related documents.

 

### Describe the optimal solution

I can imagine various solutions, e.g., the backlinks could be shown when one hovers over a [[link]] holding `shift`.
Another solution would be to somehow include them into the popup window of the note. 

### Describe the candidate solution

At least provide a possibility to open backlinks list from the popup menu. 

![image](https://user-images.githubusercontent.com/63197393/232000432-4164421d-d059-4f8d-97cf-e36a8b225491.png)

**Comment by mozhux** [comment]
2.8.9 dev1 这个功能的测试结果和预期不符，只展示了引用块本身，没有展示其层级。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/d1ec62f5-8593-4864-8faf-e6bf111bbb43)

**Comment by 88250** [comment]
和计数浮窗保持一致。

**Comment by mozhux** [comment]
> 和计数浮窗保持一致。

但目前和计数浮窗不一致的，计数浮窗可以显示内容
![image](https://github.com/siyuan-note/siyuan/assets/46953371/87948364-15e1-446a-802b-805df7b0215e)

**Comment by 88250** [comment]
收到，稍后改进，感谢感谢。
