### ISSUE TITLE
install 报错

### ISSUE THREAD

**Issue by gnafnim** [siyuan-note/siyuan#8]
<img width="541" alt="Screen Shot 2020-09-13 at 19 03 25" src="https://user-images.githubusercontent.com/69299895/93024154-80cd8780-f5f4-11ea-98cd-1fcaf01f8f88.png">

macOS: 10.13.6

**Comment by 88250** [comment]
需要创建 ~/.siyuan 目录，是不是没有权限？

**Comment by 88250** [comment]
我这里没有重现，需要更多信息，留观。

**Comment by gnafnim** [comment]
Solved! Thank you!
