### ISSUE TITLE
Add "about us" to the SiYuan menu

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8003]
### In what scenarios do you need this feature?

I think you, the programmers of SiYuan, deserve more visibility for your great work! :). It might also help to give new users more confidence in SiYuan if they knew who is developing it.  

### Describe the optimal solution

What if there was, e.g., a special "About us" menu item in the SiYuan menu? 
![image](https://user-images.githubusercontent.com/63197393/232172374-99db234f-4fbe-4f91-a3ea-e91883e5909a.png)

**Comment by 88250** [comment]
Thank you for your appreciation, but this is not suitable to be placed in the main menu, and the introduction has been placed in Settings - About, thank you.

**Comment by ciceronianus** [comment]
Sure, just brainstorming :)
