### ISSUE TITLE
Add explanation of what "SiYuan" means to the SiYuan User Guide

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8004]
### In what scenarios do you need this feature?

Just a super small think but, again, it could help new users to get to know your great software, SiYuan, and get more confidence into it. I can easily imagine what names like Obsidian, Roam, LogSeq, RemNote, Evernote etc. mean but I have no idea what SiYuan means. What if there was some nice welcome in the user guide? Like "SiYuan means... Because... In SiYuan, the only important core concept is..."

### Describe the optimal solution

Add somewhere to the User Guide (ideally somewhere to the top) just a couple of words why SiYuan is called SiYuan. 

![image](https://user-images.githubusercontent.com/63197393/232172632-28c19fa5-bc7e-4c5b-8f7b-040696939bd2.png)

**Comment by 88250** [comment]
Thanks for your suggestion, we have added the origin of the naming in the FAQ, reference it on the start page:

![image](https://user-images.githubusercontent.com/873584/232180756-f36fe88f-6309-4f98-ab2a-963bc817d6d8.png)

**Comment by ciceronianus** [comment]
Nice! :)
