### ISSUE TITLE
Remove Settings - Appearance - Customize the current theme

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8006]
![image](https://user-images.githubusercontent.com/873584/232181697-5fa77e49-8e1a-44f6-96fd-df4b2aeaed42.png)

The current custom theme function has some flaws that cannot be repaired, such as the inability to accurately merge CSS variables, not supporting certain CSS style grammars, not supporting data synchronization, and inconvenient for user maintenance, etc.

The above problems can be completely solved by the code snippet function, and the theme can be customized in a more fine-grained and flexible way.

---

* [x] User Guide
* [x] Settings entry
* [x] Load

**Comment by TonyAtlas** [comment]
Tell me, if I do not know CSS, is there still some way to edit the theme settings themselves? 

The menu you decided to remove was a relatively simplified interface for theme customization.

I'm currently using the default theme, which I customized with "Customize the current theme".

**Comment by TonyAtlas** [comment]
> @TonyAtlas Sorry, the previous settings will be invalid after the release of the next version, and the appearance can only be customized through CSS in the future.

I understand. Then I will be working out the CSS.

Are there any examples of CSS snippets of basic colors for SiYuan theme somewhere?

**Comment by 88250** [comment]
In the next version of the user guide, it will be explained in the custom theme chapter:

![d116b616e1b357ff597f60acbd226381](https://user-images.githubusercontent.com/873584/232683095-f3ff1dd4-47b8-498f-820e-d2be22aa3f75.JPG)

**Comment by TonyAtlas** [comment]
@88250 Thank you. I'll wait for updates and deal with CSS. Thank you for SiYuan.
