### ISSUE TITLE
网页使用QQ登录后出现404 Not Found

### ISSUE THREAD

**Issue by gccio** [siyuan-note/siyuan#801]
### 描述问题 Describe the problem
网页使用QQ第三方登录，在手机上确认后页面跳转至404页面

### 期待的结果 Expected result
正常登录

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/12553862/102758882-5b4bd900-43ae-11eb-8139-3f50fe8f44d0.png)

### 版本环境 Version environment

* 版本 Version：Web
* 操作系统 Operating system：Manjaro 20.2 Nibia
* 浏览器（如果使用）Browser (if used)：Chromium 版本 87.0.4280.66（正式版本）Arch Linux （64 位）

### 日志文件 Log
无

### 更多信息 More information
无

**Comment by 88250** [comment]
你好，注册时不支持第三方登录注册，只能通过手机号注册。注册以后在账号设置中绑定第三方登录后才能使用，谢谢。
