### ISSUE TITLE
Inline-level elements support pasted as plain text

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#8010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

行内代码在 "粘贴为纯文本"(ctrl+shift+V)时, 和粘贴(ctrl+V) 效果一样 ,即 \` 符号依然被保留,粘贴后依然是行内代码

### Expected result

`

### Screenshot or screen recording presentation

`

### Version environment

```markdown
`
```

### Log file

`

**Comment by iamqiz** [comment]
@Vanessa219 发现个问题 ctrl+shift+V粘贴之后, 换行符没了,导致所有内容都在一行里
比如
```
* 的撒发散
* 大使馆
```
变成
```
的撒发散大使馆
```

**Comment by iamqiz** [comment]
@88250 @Vanessa219 楼上这个算预期吗?

**Comment by 88250** [comment]
这个符合预期的，粘贴纯文本不带任何格式。

**Comment by iamqiz** [comment]
如果粘贴多段落的片段换行没了会很难看就像打字不加标点和空格比如我这句话

**Comment by 88250** [comment]
> 如果粘贴多段落的片段换行没了会很难看就像打字不加标点和空格比如我这句话

https://github.com/siyuan-note/siyuan/issues/8114
