### ISSUE TITLE
希望某个已保存的“布局”在修改后，能自动保存

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#8011]
### In what scenarios do you need this feature?

我在将“布局”功能当“工作区”来使用，但是当修改了某个布局里的打开的文档数量及其他文档时，就需要手动保存，并输入相同的布局名称，比较麻烦，所以希望能够自动保存布局的修改，或提供自动保存的设置开关。
希望采纳，谢谢。

### Describe the optimal solution

谢谢

**Comment by 88250** [comment]
这个不考虑了，后续可以看下社区是否有插件能够支持，谢谢。
