### ISSUE TITLE
New files created from the search should respect settings

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8017]
### In what scenarios do you need this feature?

In my settings, I have predefined paths for new files:
![image](https://user-images.githubusercontent.com/63197393/232508069-2ea682ac-f5fc-41a5-82de-1f39593872a2.png)

However, when I create a new file from the search, it is put as a child document the one that is open. Thus this: 

![image](https://user-images.githubusercontent.com/63197393/232507941-0955f8fd-17ad-47a5-8346-9fbf5f0520f3.png)

Results in the following path because I created it from the daily document:

![image](https://user-images.githubusercontent.com/63197393/232508421-8796f850-1ed6-4b79-bec3-a3af26ba6f24.png)

### Describe the optimal solution

I see two possible solutions:
1) Special new item in the settings to control the default path:
![image](https://user-images.githubusercontent.com/63197393/232508824-210ea125-7d44-461d-a075-e778d70223b5.png)

2) Simply use the ctrl+n path also for document from the search field.

**Comment by ciceronianus** [comment]
The search does not have access to the global settings? Or you mean that the search does not know from which notebook / page it was called?

**Comment by ciceronianus** [comment]
Alternatively, you can apply what I suggested elsewhere, i.e. using `tab` on creation of a new file to specify its path.

**Comment by Vanessa219** [comment]
I mean the search don't know which notebook's settings to use. What if there is no `tab`?

**Comment by Vanessa219** [comment]
If the notebook's settings are set, we'll use its configuration, otherwise we'll use the global configuration.
Yes, we don't know in which notebook to create the document if there is no document open.
