### ISSUE TITLE
Add multiple selections (multi cursor)

### ISSUE THREAD

**Issue by TonyAtlas** [siyuan-note/siyuan#8018]
### In what scenarios do you need this feature?

This is a very convenient setup that **greatly** reduces mechanical work and saves a lot of time.

I’m talking about mass editing function via `Alt` key like in Obsidian, [VS Code](https://code.visualstudio.com/docs/editor/codebasics), Sublime Text.

![multicursor](https://user-images.githubusercontent.com/82872888/232517604-6b96da89-62e3-4db1-b95e-9115e4bbd5bb.gif)

There are many scenarios where this can be of **great help**:

- To remove or add a sign in several blocks at once with a single click.
- To remove many extra spaces and line breaks with a single click.
- To bold or oblique the same term that is repeated several times on the same page.
- And more…

### Describe the optimal solution

I suggest the standard option: use Left Alt for Multiple Selection.

**Comment by 88250** [comment]
This usage scenario was not considered at the beginning of the editor design, and it is unrealistic to implement it now, so we will not consider it, thank you.

**Comment by TonyAtlas** [comment]
> This usage scenario was not considered at the beginning of the editor design, and it is unrealistic to implement it now, so we will not consider it, thank you.

I understand. I assumed that block editors don't have the ability to do this kind of typing, so none of them (as far as I know) have this function.

Thank you for your quick response.
