### ISSUE TITLE
反链提及文档名未正常显示

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#802]
![image](https://user-images.githubusercontent.com/32661922/102777260-30bc4900-43cb-11eb-9f6a-71fddddca3bb.png)

![image](https://user-images.githubusercontent.com/32661922/102777264-344fd000-43cb-11eb-8b68-54155275d9b9.png)

![image](https://user-images.githubusercontent.com/32661922/102777272-39ad1a80-43cb-11eb-9729-41b5cc94ff9d.png)

![image](https://user-images.githubusercontent.com/32661922/102777370-69f4b900-43cb-11eb-9a30-884be307dd36.png)

整个笔记本都是临时新建的，不是从老数据迁移过来的；笔记本里只有这 3 个文件，都在根目录。

**Comment by 88250** [comment]
感谢反馈，v0.5.43 修复。
