### ISSUE TITLE
希望同一个文档左右分屏后，折叠或展开其中的一个里面的列表时，另一个里面的列表保持原来的状态

### ISSUE THREAD

**Issue by GH-W94** [siyuan-note/siyuan#8021]
### In what scenarios do you need this feature?

希望同一个文档左右分屏后，折叠或展开其中的一个里面的列表时，另一个里面的列表保持原来的状态

### Describe the optimal solution

谢谢

**Comment by 88250** [comment]
目前的设计上无法做到分离的折叠状态，短时间内不大可能改进了，感谢反馈。

**Comment by GH-W94** [comment]
> 目前的设计上无法做到分离的折叠状态，短时间内不大可能改进了，感谢反馈。

好吧，期望以后能改进。
目前干扰最大的是：
当列表比较大时，分屏查看，折叠或展开左分屏的列表，会造成右分屏的列表也折叠或展开，将阅读的焦点一下挤压到其他位置，还需重新找位置
