### ISSUE TITLE
Adjust the style of the navigation bar on the left side of the settings interface

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8022]
![image](https://user-images.githubusercontent.com/873584/232650900-c0d235f8-fcfd-4a96-8258-9467a2951cfb.png)

**Comment by svchord** [comment]
能不能顺便把搜索框也缩小放在左侧tab的顶部，就类似win11的 设置界面

**Comment by 88250** [comment]
@svchord 暂时不动了，等会要打包了。
