### ISSUE TITLE
Support viewing inline-level memos in the read-only mode of the mobile editor

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8023]
https://ld246.com/article/1681751937956

**Comment by Aiviokoo** [comment]
@Vanessa219 很抱歉打扰到V姐，其实D大已经给予我回复了，暂时先这样了。（抱着一种精益求精的态度我还是想来尝试一下提议，如果你们最近弄插件系统太忙了就暂时算了叭）
非常感谢现在能在只读模式下长按查看备注。
但是我想，既然都加上了在只读模式下可以查看备注，能让它的体验更好就更棒了。
只读模式模式下是不能编辑的，所以查看备注最方便的方式就是**轻点即可查看备注**，就像在微信读书上轻点有评论的文字查看评论一样流畅，快乐。
也许使用移动端的人比较少，再加上使用备注的人可能也不多，大家对此没有太多反应。
我说说现在长按查看备注的不便吧
- 已读模式下轻点不会进入编辑模式，也没有其他任何效果（最方便的按键没有用上）
- 长按查看更耗时
- 长按查看的耗时与轻点空白即可退出备注显示页面形成了强烈的反差，极其影响体验，V
姐可以自己体验一下这种割裂感
改不改都谢谢V姐啦！

**Comment by Aiviokoo** [comment]
@Vanessa219 V姐，和群友讨论后发现当备注加在引用上的时候，单点进引用还是显示备注会冲突，所以当出现这种情况时，备注会变成脚注形式，点击文字还是跳转引用，点击脚注显示备注（应该没有硬核到3个同时使用的吧），好像也还有不合理的地方，实在不行还是先这样吧。抱歉打扰到您了。
