### ISSUE TITLE
Show (reveal) the page in the doctree

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8026]
### In what scenarios do you need this feature?

Sometimes I would like to see where in the doctree the opened page / note / document is, because I would like to either the manipulate with the note there or to see other notes in the same folder. Currently, I don't see how this is possible. 

### Describe the optimal solution

Add item "show in the doctree" to the tab context menu .

**Comment by 88250** [comment]
Please try this one.

![image](https://user-images.githubusercontent.com/873584/232743990-111c1e1c-e6f3-4571-a0b6-6ceea64d6cbf.png)

**Comment by ciceronianus** [comment]
Oh, sorry! I did not know it was there! :) I would still consider to put it (with the same icon) into the context menu when you click on the tab. So there would be a higher chance that the user finds it. 
![image](https://user-images.githubusercontent.com/63197393/232744614-09a7c852-9554-474e-8cfa-32318c917f47.png)

But it is not necessary. :)

**Comment by 88250** [comment]
The context menu will not consider adding this function for the time being, thank you.
