### ISSUE TITLE
There is an extra blank space on the right side of the Settings - Marketplace interface

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#8027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![思源笔记-bug反馈-48](https://user-images.githubusercontent.com/49649786/232716801-f3acbc51-dc1e-4406-ae04-dc718996998c.gif)

### Expected result

从集市内容预览界面返回后隐藏预览界面  
Hidden the preview interface after returning from the marketplace content preview interface

### Version environment

```markdown
- Version: 2.8.5
- Operating System: 
- Browser (if used):
```

### Log file

无有效信息输出  
No valid information output

**Comment by royc01** [comment]
打开集市右侧已经有了，不用返回就能出现😅

**Comment by benz9527** [comment]
遇到类似的问题
![image](https://user-images.githubusercontent.com/109717800/232740516-3a0d2678-9138-4163-8be0-bc48ffa139b5.png)
只要点开集市，就会在右侧多出一块区域

**Comment by 88250** [comment]
关联 https://ld246.com/article/1681803564688
