### ISSUE TITLE
Convert an online image to a local one by clicking on 🌐 or "⋮"

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8029]
### In what scenarios do you need this feature?

It is great that one can convert all online images to local images! Great feature! 

I just find myself often clicking on 🌐 or "⋮" of the single image expecting that I can convert that one image to the local one from there.

![image](https://user-images.githubusercontent.com/63197393/232746933-46beb640-8158-45d4-9061-7579c198e188.png)

### Describe the optimal solution

Consider adding ability to convert an online image to local image from 🌐 or "⋮" .

**Comment by ciceronianus** [comment]
It is not a big problem, just a suggestion.

**Comment by 88250** [comment]
Well, I thought about this before, but from the point of view of the interaction steps, there are as many steps as clicking the editor ⋮ menu in the upper right corner, and most of the time more than one image in the document needs to be converted, so we put it there uniformly.

**Comment by 88250** [comment]
We closed the issue, thanks for the discussion.
