### ISSUE TITLE
本地仓库使用其他软件修改.md文件相关问题

### ISSUE THREAD

**Issue by fengchaobio** [siyuan-note/siyuan#803]
0.5.42。使用 typora 修改 .md 文件，思源客户端打开同样的 .md 文件不显示修改的内容

**Comment by 88250** [comment]
你好，外部修改以后需要重启才能识别，这部分后面会在文件树上做一个刷新按钮来手动触发重新加载，请关注 https://github.com/siyuan-note/siyuan/issues/794
