### ISSUE TITLE
`:)` emoji should be not misinterpretted

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8030]
### In what scenarios do you need this feature?

I wanted to create a super simple emoji `:)`. When I started to type it, I got this, which was very confusing. 

![image](https://user-images.githubusercontent.com/63197393/232750937-ec546eea-3dfe-4bd2-a977-48e0f553ec95.png)

The reason seems to be that these emoji have `( )` in their description. 

![image](https://user-images.githubusercontent.com/63197393/232751312-f4771851-2542-4e5a-b305-b071fa702f44.png)

### Describe the optimal solution

Ideally, `:)` would provide a suggestion for conversion to an appropriate smiley. 
However, if not possible, I suggest to make the following exception in emoji recognition: After `:` ignore "( )" characters.

**Comment by 88250** [comment]
Well, it should, but what other "similar" emojis are there besides `:)`?

**Comment by ciceronianus** [comment]
True, probably `:)` should provide a suggestion to just 😊 . 
Maybe following some of the basic ones form this list? https://en.wikipedia.org/wiki/List_of_emoticons

**Comment by ciceronianus** [comment]
However, just not to offer 👩‍❤️‍👨 for `:)` would already be great! :)

**Comment by 88250** [comment]
Let's add so much for now, I hope someone else can help maintain [this search file config](https://github.com/siyuan-note/siyuan/blob/master/app/appearance/emojis/conf.json).

![image](https://user-images.githubusercontent.com/873584/232765902-65ef4f84-65bb-4cc0-ae28-db6f1fb410db.png)

**Comment by ciceronianus** [comment]
Amazing! That looks really good.
