### ISSUE TITLE
（android）Enter the app occasionally white screen can not operate, enter the app occasionally input method (vivo system default) click enter to put away the keyboard can not continue typing.

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#8031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The following are all Android apps.
The first problem has two cases, both of which are accidental, I encountered it within a few minutes after installing the Android 2.8.5 version, I don't know if it is a coincidence.
1. As demonstrated in the video, he is a white screen, and clicking the button in the upper left corner does not respond. It often happens on the first install, and I remember the first time I installed a new version of the app after every uninstall, including this time 2.8.5 (reboot problem solving).
2. The second is a white screen at the beginning, but it is not a problem, because he clicks on the upper right corner to see the notebook, which may be because the software does not open the notebook. But I often think he's stuck and he doesn't open the interface below.
![Screenshot_20230418_182008](https://user-images.githubusercontent.com/112467275/232753056-149f5ce7-b83b-427b-9cf0-6362b0ba22c3.jpg)
[Screenrecording_20230418_180441-2.zip](https://github.com/siyuan-note/siyuan/files/11260822/Screenrecording_20230418_180441-2.zip)

The second input method problem
The probability of this problem occurring is quite small, and I have only encountered it twice within minutes of installing version 2.8.5 so far.
The problem is that when the keyboard enters a carriage return, the keyboard is inexplicably put away, version 2.8.4 appears almost every time it is typed, it looks like it has been fixed.

The problem description may not be very smooth, excuse me.
Best wishes.

---
以下所讲的都是安卓应用。
第一个问题有两种情况，这两种都是偶然的，我安装安卓2.8.5版本后几分钟内遇到的，不知道算不算碰巧了。
1. 就像视频中演示的这样，他是白屏，而点击左上角的按钮也没反应。他常常发生在第一次安装，我记得过去每次卸载后，安装新版应用第一次都会这样，包括这次的2.8.5（重启问题解决）。
2. 第二种的是开局就白屏，但是它不算是一个问题，因为他点击右上角是可以看笔记本的，这可能是因为软件没有打开笔记本。不过我常常认为他卡住了，他没有打开下图的那个界面。
第二个输入法的问题
这个问题出现概率挺少，目前安装2.8.5版本的几分钟内，我只遇到了两次。
问题是当键盘输入回车时，键盘会莫名其妙收起来，2.8.4版本几乎每次输入都出现，看起来已经修复了。

问题描述可能的不太流畅，见谅。
祝好。

### Expected result

Open the screen and do not get stuck with a white screen
If the white screen is not stuck, the prompt in the display image does not open the notes page
The input method presses enter, not retracting the keyboard by mistake.

---
开屏不要白屏卡住
若白屏未卡住，显示图片中的提示未打开笔记页面
输入法按下回车，不在错误的收起键盘。

### Screenshot or screen recording presentation

[Screenrecording_20230418_180441-2.zip](https://github.com/siyuan-note/siyuan/files/11260839/Screenrecording_20230418_180441-2.zip)

### Version environment

```markdown
- Version: android 10
- Operating System:android 
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11260833/system-log.zip)

**Comment by Soltus** [comment]
通过描述和录屏无法定位到问题，你可以通过 https://github.com/Hi-Windom/Sillot/releases/download/v0.22.7-sillot/Sillot-v0.22.7_20230418_syv2.8.5-debug.apk 收集错误数据

**Comment by Soltus** [comment]
抱歉，我无法复现你的问题

**Comment by Soltus** [comment]
> 这个收集错误信息手机的软件无法安装，显示安装包解析错误。 This software that collects error messages for the phone cannot be installed, showing the installation package parsing error.
麻烦安装新版 https://github.com/Hi-Windom/Sillot/releases/download/v0.23.3-sillot/Sillot-v0.23.3_20230419_syv2.8.6-debug.apk
如果仍无法安装，是一个新的 bug

**Comment by 88250** [comment]
2.8.9 修改了一个移动端加载后空白的问题，可能是你遇到的情况，麻烦等发布以后帮忙测试看看。

**Comment by 88250** [comment]
暂时只能先这样了，等后面如果有更多反馈我们再排查，谢谢。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
