### ISSUE TITLE
Make bug reports more user friendly

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8035]
### In what scenarios do you need this feature?

I would suggest to make bug reports more user friendly and more calming. Imagine that a new user gets the following message: 

![image](https://user-images.githubusercontent.com/63197393/232771954-f81d39b2-d930-4472-8163-9ae41e515c91.png)

These words are for a normal user very difficult to understand and possibly scary.

### Describe the optimal solution

I would expect something like: 

"Don't panic. Something went wrong on our side but your data should be safe! Please, restart SiYuan. If the problem continues, look for the help (here... and here), or report the issue (here).

If you want to know technical details of the error, click here."

**Comment by ciceronianus** [comment]
Same for this. 
![image](https://user-images.githubusercontent.com/63197393/232797742-b4638e35-226e-4cd5-b112-3fa2d1531106.png)

(For some weird reason, I have to now start SiYuan twice before it starts...)

**Comment by 88250** [comment]
`Failed to get kernel serve port` No change for now, thank you.
