### ISSUE TITLE
SQL查询引起嵌套

### ISSUE THREAD

**Issue by zhoulukuan** [siyuan-note/siyuan#8039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

SQL查询语句嵌套问题。
正常情况：
![}OB)TQ5RCJ98 6~{SFEJ%Y](https://user-images.githubusercontent.com/16110591/232946316-02e671fd-3f5f-4b37-b49b-d347d18df1ba.png)
出现bug情况：
![K_DGCU C56G{M8 (A7LOB75](https://user-images.githubusercontent.com/16110591/232946340-144a824c-1dfc-4774-9e33-bdffbf56c09d.jpg)
查了下似乎以前出现过类似的问题，但是已经修复了，不太清楚是程序bug还是语句有问题？

以下是SQL，内容是筛选带有T标签的列表项
```SQl
SELECT
    *
FROM
    blocks
WHERE content not like '%#T%' AND
    id in (
        select
            parent_id
        from
            blocks
        where
            content like '%#T%'
    )

```

### Expected result

想要搞清楚是bug或者是SQL错误？

### Version environment

```markdown
- Version: 2.8.4
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11267713/siyuan.log)

**Comment by zhoulukuan** [comment]
补充：看到很久之前有过类似的问题https://github.com/siyuan-note/siyuan/issues/2668?utm_source=ld246.com
但显示是修复了？

**Comment by 88250** [comment]
搜索递归以后会在到达最大深度限制以后自动跳出，所以没有无限递归下去，是正常的。

建议修改 SQL，把自身的块排除在外。
