### ISSUE TITLE
还挺喜欢标题前的提示，希望可以常驻

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#804]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

希望标题前的 h1 h2 这样的提示可以常驻，不仅仅是鼠标放上才显示。
希望可以支持提供配置项，打开后 h1 h2 这样的提示就一直展示。

### 描述最优的解决方案 Describe the optimal solution

![image](https://user-images.githubusercontent.com/16383685/102794513-733f4f00-43e6-11eb-959d-59446145c2bd.png)

**Comment by Vanessa219** [comment]
最近的版本会有计划，
合并到 https://github.com/siyuan-note/siyuan/issues/76  中进行改进
