### ISSUE TITLE
获取内核服务端口失败 Failed to get kernel serve port

### ISSUE THREAD

**Issue by clx92clx** [siyuan-note/siyuan#8047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

是新电脑，软件是新安装的。首次安装完成后能启动，但在安装了其他软件、做了一些杂七杂八的系统配置后无法打开。

### Expected result

搜到过相同问题的issue，并尝试以下方法：
1. 重新安装 - 打不开
2. 管理员身份运行 - 打不开
3. 重启电脑后运行 - 打不开

### Screenshot or screen recording presentation

<img width="534" alt="image" src="https://user-images.githubusercontent.com/8463600/232999481-6209fd96-29e9-47e7-8e46-30388a4f6b40.png">

### Version environment

```markdown
- Version: 2.8.5
- Operating System: win11
- Browser (if used):
```

### Log file

 2023/04/19 15:16:59 runtime.go:51: kernel is booting:
    * ver [2.8.5]
    * arch [amd64]
    * os [Microsoft Windows 11 Home China]
    * pid [11416]
    * runtime mode [prod]
    * working directory [D:\AppGallery\SiYuanNote\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\AppData\思源笔记\siyuanNote]
I 2023/04/19 15:16:59 conf.go:367: user has disabled [Google Analytics]
I 2023/04/19 15:16:59 runtime.go:97: use network proxy [system]
I 2023/04/19 15:16:59 serve.go:111: kernel [pid=11416] http server [127.0.0.1:30119] is booting
I 2023/04/19 15:16:59 working.go:401: built-in pandoc [ver=2.19.2, bin=D:\AppData\思源笔记\siyuanNote\temp\pandoc\bin\pandoc.exe]
I 2023/04/19 15:16:59 sync.go:150: sync before boot
I 2023/04/19 15:16:59 repository.go:975: boot get sync cloud files elapsed [0.19s]
I 2023/04/19 15:16:59 blocktree.go:401: read block tree [5.0 MB] to [D:\AppData\思源笔记\siyuanNote\temp\blocktree], elapsed [0.03s]
I 2023/04/19 15:16:59 conf.go:673: database size [39 MB], tree/block count [204/16065]
I 2023/04/19 15:16:59 working.go:157: kernel booted
I 2023/04/19 15:16:59 box.go:74: auto stat [trees=204, blocks=16065, dataSize=148 MB, assetsSize=141 MB]
I 2023/04/19 15:16:59 disk.go:33: disk usage [total=362 GB, used=9.2 GB, free=353 GB]
I 2023/04/19 15:17:01 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
W 2023/04/19 15:17:59 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:18:14 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:18:29 process.go:76: active UI proc count [3]
W 2023/04/19 15:18:59 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:19:14 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:19:29 process.go:76: active UI proc count [3]
W 2023/04/19 15:19:59 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:20:14 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:20:29 process.go:76: active UI proc count [4]
W 2023/04/19 15:20:59 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:21:14 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:21:29 process.go:76: active UI proc count [4]
W 2023/04/19 15:21:59 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
I 2023/04/19 15:22:00 repository.go:1077: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=20 kB] in [0.09s]
W 2023/04/19 15:22:14 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:22:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:23:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:23:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:23:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:24:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:24:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:24:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:25:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:25:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:25:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:26:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:26:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:26:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:27:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:27:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:27:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:28:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:28:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:28:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:29:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/04/19 15:29:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:29:30 process.go:76: active UI proc count [4]
W 2023/04/19 15:30:00 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
I 2023/04/19 15:30:01 repository.go:1077: synced data repo [provider=0, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=20 kB] in [0.19s]
W 2023/04/19 15:30:15 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/04/19 15:30:30 process.go:76: active UI proc count [4]

**Comment by clx92clx** [comment]
已尝试，但没啥效果：
<img width="458" alt="image" src="https://user-images.githubusercontent.com/8463600/233009118-228fcd9c-24be-4a79-84be-d3931ea7a262.png">

1. 系统防火墙，做了如截图的设置
2. 360中没有拦截记录，我顺手把360关了
3. 删除siyuan文件夹后重启，在选择工作空间后，思源笔记依然无法启动
4. log内容没啥区别，不贴了

**Comment by 88250** [comment]
日志文件有两个：

* 工作空间/temp/siyuan.log 这个是内核日志文件
* C:\Users\用户名\.config\siyuan\app.log 这个是前端日志文件

麻烦打包这两个文件上传一下。

**Comment by zhanglianzhong** [comment]
问题没解决，为啥还closed？ 我也一样遇到这个问题，mac的

**Comment by org-den** [comment]
在Ubuntu下也出现了这个问题，根据[issues-7001](https://github.com/siyuan-note/siyuan/issues/7001#issuecomment-1373330509)中的回复：

> 如果 SiYuan-Kernel 内核进程不正常退出的话可能会出现这个问题。

kill掉SiYuan-Kernel进程再启动程序就好了。
