### ISSUE TITLE
CTRL+F can‘t find closed notebook.

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/siyuan#8049]
### In what scenarios do you need this feature?

I closed some notebook to improve siyuan running speed by user manual。
But I find I can't search the content in closed  notebook.
I think it need a way to search all content even it's in closed notebook.

### Describe the optimal solution

CTRL+F ： can search all content event it's in cloed notebook
or it can give a button option
![image](https://user-images.githubusercontent.com/53116704/233012527-79b9a5c0-8d31-460f-b8e9-648e991cf7d6.png)

**Comment by 88250** [comment]
Unfortunately, this is not possible as search relies on database indexes, which are deleted when the notebook is closed.
