### ISSUE TITLE
嵌入代码的另一种方式，嵌入gist代码

### ISSUE THREAD

**Issue by heshang233** [siyuan-note/siyuan#805]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

仅仅是一个嵌入代码的新方式，实际情况，如果不用gist的话，这个功能是个鸡肋。可以看一下，也是个新思路

### 描述最优的解决方案 Describe the optimal solution

并无

### 描述候选解决方案 Describe the candidate solution

并无

### 其他信息 Other information
这是其他markdown软件工具集成gist
https://weblog.west-wind.com/posts/2017/nov/20/using-gists-for-general-purpose-web-pages-with-markdown#gists-as-a-shared-document-store

**Comment by 88250** [comment]
谢谢提议，这个暂时不引入了，因为过于依赖网络并且依赖科学网络……
