### ISSUE TITLE
Data repo support for purging unreferenced indexes and objects

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8054]
All referenced data snapshots are recorded under the workspace /repo/refs/ folder.

If the snapshot index in repo/indexes is not referenced, it needs to be purged, and the data blocks contained in the unreferenced snapshot will be actually deleted to free up storage space.

<kbd>Settings</kbd> - <kbd>About</kbd> - <kbd>Data repo purge</kbd>

**Comment by zxhd863943427** [comment]
我其实就是想问，什么情况下数据快照会被记录在工作空间 /repo/refs/ 文件夹下，这个判断标准是什么？
目前的解释尚不清楚。

如果可以的话，也可以解释一下，清除未索引的对象能保证可见的数据快照还能完整回溯吗？因为这些对象都是来自数据快照的建立吧，假如数据快照需要始终可用，而且在多端一致，删除对象可能导致数据快照失效。

**Comment by 88250** [comment]
在手动创建数据快照或者同步自动创建数据快照后 refs/latest 会指向这个快照，这样至少就有一个引用了。

refs/tags/ 下面的是手动标记快照时指向的。

数据仓库清理功能会删除没有被指向的快照和这个快照关联的数据对象。比如执行清理前存在 100 个快照（indexes 文件夹下面有 100 个文件），在清理以后只剩下 1 个 latest 快照，只有这 1 个快照关联的数据对象会保留，其他数据对象会被一并清理删除。

**Comment by zxhd863943427** [comment]
也就是说，被引用的定义是被标记的快照和最后同步自动创建时的快照？那我觉得还行。

不过感觉这个清理功能最好能划定范围，一次性全部清除有点太大力出奇迹了。

**Comment by 88250** [comment]
一次性清理干净吧。
