### ISSUE TITLE
Improve local data repo, cloud data synchronization and backup

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8055]
* [x] https://github.com/siyuan-note/siyuan/issues/8052
* [x] https://github.com/siyuan-note/siyuan/issues/8048
* [x] https://github.com/siyuan-note/siyuan/issues/8054
* [x] https://github.com/siyuan-note/siyuan/issues/8075
* [x] https://github.com/siyuan-note/siyuan/issues/8057

**Comment by zxhd863943427** [comment]
在数据快照列表中显示缩写 ID 感觉效果不明显，可以在客户端获取当前的主机名，并写入云端数据快照吗？

如果在浏览器端，那就只写入浏览器的ua和版本。

**Comment by zxhd863943427** [comment]
或者还是在go端获取主机名比较好……

**Comment by 88250** [comment]
@zxhd863943427 等会我们改改看吧，但是 dev 版的云端快照就无法用了，得重新设计一下数据结构。

**Comment by zxhd863943427** [comment]
啊这
