### ISSUE TITLE
Automatically purge unreferenced data snapshots older than 30 days in official cloud storage

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8056]
Similar to the local repo to purge unreferenced data snapshots https://github.com/siyuan-note/siyuan/issues/8054

Ref https://github.com/siyuan-note/siyuan/issues/10081

---

## 关于思源笔记官方云端存储快照保留时间变更的公告

为了降低官方云端存储成本，我们将于 2024 年 10 月 15 号 0 点开始清理官方云端存储中未引用的快照，如果需要下载之前的云端快照请在此时间点之前下载完毕。

引用的快照指的是：

* latest 快照，即每次数据同步后的最新快照
* 手动标记备份上传到云端的快照
* 30 天以内的快照

除此以外的快照会被清理，清理后无法恢复。

该清理操作以后会自动定时执行，云端存储快照清理不影响本地数据，感谢大家的支持和理解！

**Comment by 88250** [comment]
Deleting cloud snapshots is a dangerous operation. After careful consideration, we still keep snapshots and do not delete them automatically.

**Comment by TCOTC** [comment]
现在这个 issue 是什么情况？

**Comment by 88250** [comment]
还在考虑



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Fri, Sep 20, 2024 17:24 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Automatically purge unreferenced datasnapshots older than 15 days in official cloud storage (Issue #8056)




 
现在这个 issue 是什么情况？

**Comment by 88250** [comment]
公告已经发出 https://ld246.com/article/1728492623400

思源笔记内也会推送

**Comment by 88250** [comment]
海外官方订阅目前还处于早鸟阶段，就不发公告了。



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Thu, Oct 10, 2024 01:17 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Automatically purge unreferenced datasnapshots older than 30 days in official cloud storage (Issue #8056)




 
海外的有没有公告？
