### ISSUE TITLE
latex array 环境导出pdf 失败

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#806]
### 描述问题 Describe the problem

$$
\begin{array}{l}
V_{DDmin}<V_{DD}<V_{DDmax}\\
V_{THmin}<V_{TH}<V_{THmax}\\
W_{min}<W \\
Delay(V_{DD},V_{TH},W)<D_{con}
\end{array}
$$

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/16791452/102844499-897cf780-4446-11eb-9512-7556e27d3c3a.png)

![image](https://user-images.githubusercontent.com/16791452/102844490-8255e980-4446-11eb-9a3f-42a61f5ffd2c.png)

### 版本环境 Version environment

* 版本 Version：0.5.42
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，期待的是换行吗？

**Comment by frankli998** [comment]
对。不过我觉得导出功能目前不紧急，导出频率不高，而且 typora 的导出功能足够好用。

**Comment by 88250** [comment]
谢谢理解。MathJax 的 `\` 换行我关联到 https://github.com/siyuan-note/siyuan/issues/340 上了，这个提议就关闭了，谢谢。
