### ISSUE TITLE
Spaced repetition supports tab and window

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8061]
https://ld246.com/article/1681639810442

**Comment by bin38121cn** [comment]
相关问题：
https://ld246.com/article/1679841432468
https://ld246.com/article/1681916184177
https://ld246.com/article/1681639810442
https://ld246.com/article/1679212683506

**Comment by kx1356** [comment]
我觉得目前的闪卡界面非常漂亮，尤其是最大化后，不知改成页签栏后会怎么样？要查看引用内容的上下文，改成弹出窗口即可，真的只能改成页签式吗？

**Comment by kx1356** [comment]
我觉得目前的闪卡界面非常漂亮，尤其是最大化后，不知改成页签栏后会怎么样？要查看引用内容的上下文，改成弹出窗口即可，真的只能改成页签式吗？

**Comment by 88250** [comment]
改成页签的话可以在新窗口打开，这样会更灵活一些。
