### ISSUE TITLE
Support mouse wheel zoom editor font size

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8064]
### In what scenarios do you need this feature?

Sometimes the font can be toos mall for my eyes. In a such case, I would like to simply increase it by zooming-in (increasing its size).

### Describe the optimal solution

ObsidianMD allwos for using `ctrl` + scroll wheel to increase and decrease zoom / font-size. I find it very useful. Same UI/UX is being used by internet browsers and other apps.

**Comment by 88250** [comment]
We intend to support overall interface scaling, not just editor font scaling, thanks.

**Comment by mozhux** [comment]
> 单独的编辑器字体缩放也是有需求的。。这两个还是不太一样的

**Comment by zxhd863943427** [comment]
加一，我觉得整体缩放已经有+-了，没必要这个

**Comment by littlecoby** [comment]
Is there a way to switch back to the original font size after scrolling? ctrl+0 does not work. Hope for such a shortcut.
In addition, when using ctrl++/- or ctrl+wheel, it is hard to know the exact current zoom level. Hope there is a graphic indicator (one row for overall, one for the font size) similar to that in e.g. Edge browser.

**Comment by Zuoqiu-Yingyi** [comment]
> Is there a way to switch back to the original font size after scrolling?

This is a quick way to adjust `Settings > Editor > Font Size` option. `Original font size` doesn't actually exist.

**Comment by littlecoby** [comment]
> This is a quick way to adjust `Settings > Editor > Font Size` option. `Original font size` doesn't actually exis

I see, Thanks.

Still wish for a zoom level indicator for visual adjustments.
