### ISSUE TITLE
Support `Copy block hyperlink (Markdown)`

### ISSUE THREAD

**Issue by wherejumpout** [siyuan-note/siyuan#8065]
### In what scenarios do you need this feature?

siyuan-note have the siyuan:// protocol, but  many other applications does not support it directly 
So when I copy  the hyperlink of an block to some other application,  the app does not recogize it.
  

### Describe the optimal solution

In the copy menu , add a new item:   "copy as markdown hyperlink"
copy the link as following:
[first 16 words of the block](siyuan://2023.....)

### Other information

there is a similar "copy-as-markdown" extension in chrome.  It's really popular
https://chrome.google.com/webstore/detail/copy-as-markdown/fkeaekngjflipcockcnpobkpbbfbhmdn

**Comment by leolee9086** [comment]
@wherejumpout 

http://www.siyuanplay.com/stage/build/desktop/?r=743v1w3&&id=20230417124836-a7fe6tm

there's a demo

**Comment by wherejumpout** [comment]
Cool,  I'm not familiar with javascript.  It's the code of a plugin  and you need to hack it by youself, or this feature will eventually on the future release?

**Comment by leolee9086** [comment]
> 

that's just a javascript code snippet, I  made  some trick to let docs runable

**Comment by 88250** [comment]
Hello, do you mean to add a copy `siyuan://` to Markdown format? For example, copy it as `[Content Block](siyuan://blocks/20210428222013-0afj8vn)`

**Comment by wherejumpout** [comment]
Yes.

[Content Block or the first 16/32/64 charactor of the Content Block](siyuan://blocks/20210428222013-0afj8vn)
  
Some app can recognize siyuan:// directly, but many others can only identify it as a link with the  help of markdown markup.

I think this feature can help more users to enjoy the benefit of siyuan protocol

**Comment by Vanessa219** [comment]
db16d8f7
