### ISSUE TITLE
[feature request]搜索结果中的文档列表把带有图标的文档排在前面

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#8067]
### In what scenarios do you need this feature?

我一般给重要的文档或者父文档设置图标, 而不重要的子文档不设图标,

所以建议搜索结果中按类型排序时带有图标的文档优先显示在前面, 

### Describe the optimal solution

解法可以通用一点,允许 多级排序,比如 类型> 修改日期 >创建日期  >是否有图标 >是否有属性

也可以简单一点 ,不考虑多级, 只对文档是否有图标进行二次排序

**Comment by 88250** [comment]
你好，这个需求有点过于个性化了，建议尝试通过 SQL 达成。

**Comment by iamqiz** [comment]
通用的需求是 多级排序 ,比如 "类型> 修改日期 >创建日期" 或者  "修改日期 >类型>创建日期" 等等   , 允许用户自定义

我的需求只是一个具体的例子,即  "类型> 是否有图标"

**Comment by 88250** [comment]
这个需求优先级应该不高，后期考虑吧。
