### ISSUE TITLE
The document title supports returning to the parent document via `Alt+←`

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#8068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文档标题支持通过 Alt+← 返回父文档

### Expected result

`

### Version environment

```markdown
`
```

### Log file

`

**Comment by 88250** [comment]
没太明白你意思，我这里测试 Alt+→ 进入聚焦和 Alt+← 返回聚焦正常：

![issue](https://user-images.githubusercontent.com/873584/233516764-743ebe00-81ec-4efb-98c1-cd8e8c4bb356.gif)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by iamqiz** [comment]
是文档标题 ,  不是块级标题

**Comment by 88250** [comment]
文档已经是顶层了。

**Comment by iamqiz** [comment]
在块里可以通过 "聚焦到上层" 来回到当前文档的父文档的,  
笔记本才应该是顶层

**Comment by 88250** [comment]
"聚焦到上层" 你用的是快捷键还是菜单，麻烦截图。

**Comment by iamqiz** [comment]
快捷键 alt+←
