### ISSUE TITLE
Support webclip short cut on the right click drop down menu | 支持在链接右键菜单中，增加剪藏快捷方式

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#8072]
### In what scenarios do you need this feature?

Currently, to clip a web as local notes, we need to use the chrome extension, and only can save to the root of one notebook。 Afterward, need manually change the note poisitions
目前，需要使用chrome的插件来把网页保存到本地，但是只能保存在笔记本的根目录下

When we need to arrange a large number of webpages, it is very time-consuming to manually change where these new notes save to 
当需要剪藏并管理大量的连接时，一个个手动去指定每个链接对应笔记的剪藏保存路径非常费时间

Wondering if it possible to provide a local web clip shortcuts, which can clip the website as a local notes belong to current notes, and convert the url to a block ref link.
希望能够支持，直接在笔记的超链接右键菜单中，增加一个剪藏的快捷键，直接在当前笔记目录下，生成一个剪藏笔记，并把URL链接转换为块引用链接。

![image](https://user-images.githubusercontent.com/19968935/233557463-fdace719-fb4a-408e-a217-34c89091f550.png)

(If possible, add a batch option, converting all links in this note to local notes)
(如果可能的话，给每个笔记提供一个批处理选项，把笔记中所有的链接都转换为本地笔记)

### Describe the optimal solution

Support webclip note save path in the Chrome extension.(but seems also very labor-intensive)
chorme剪藏插件，提供笔记的保存路径（但依然比较费功夫）

### Other information

If clipping in the backend not feasible for some website, please consider the feature that open the URL as a new tab in siyuan note, and build-in the chrome extension to implement the above feature.
如果在后台很难实现网页爬虫抓取，可以通过直接在思源笔记中打开网页作为新的页面，然后内置剪藏插件来进行笔记的剪藏

**Comment by HowcanoeWang** [comment]
related issue #2669

**Comment by 88250** [comment]
在主程序中无法准确解析网页，需要依赖浏览器扩展。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by HowcanoeWang** [comment]
那浏览器拓展支持保存路径到页面级呢？

**Comment by 88250** [comment]
等社区贡献吧，我们没有时间写这个细节了……
