### ISSUE TITLE
将文档块转换为标题块，撤销后文档块无法还原

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#808]
### 描述问题 Describe the problem
#556 增加了文档块和标题块相互转换的功能，大大提升了文档块的使用效率
目前在使用过程中，遇到了一点小问题，重现步骤如下：
-  将文档块A拖动到文档块B
- 按快捷键 `Ctrl + Z`，希望撤销刚才的拖动
- 文档块A 没有复原

### 期待的结果 Expected result
拖动后再撤销，原来的文档能正常还原

### 截屏或录屏演示 Screenshot or screen recording presentation

![拖动后撤销](https://user-images.githubusercontent.com/15924513/102892967-ac85c680-449b-11eb-9ccb-fae5d5e29357.gif)

### 版本环境 Version environment

* 版本 Version：0.5.42
* 操作系统 Operating system：win10

**Comment by 88250** [comment]
这类撤销操作确实需要，目前先集中精力搞编辑器，后面一点再考虑，谢谢。

**Comment by deerainw** [comment]
这个操作涉及到了文件树，所以不应该归撤销来管吧，撤销一般都只管编辑器，如果涉及到文件树的操作也要归撤销管的话，感觉实现起来非常烦人...... 其实转换成标题块之后想撤销的话，把它反向再拖回文档树就好了

**Comment by 88250** [comment]
那就干脆的关闭吧，因为这个实现起来代价较高，现阶段不适合深入……
