### ISSUE TITLE
Improve data snapshot comparison

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8081]
https://ld246.com/article/1682148754416

* Support switching direction
* Use new version as the default
* Add detail latest modification time for each file

**Comment by Zuoqiu-Yingyi** [comment]
我提一个具体的方案: 通过箭头与快照建立时间明确指示快照对比时所站的视角

| 视角           | 指示视角的文本                               | `更新`                                | `添加`                 | `删除`                 |
| -------------- | -------------------------------------------- | ------------------------------------- | ---------------------- | ---------------------- |
| 对比内容(默认) | `2023-04-21 01:00:00 => 2023-04-22 01:00:00` | 左侧为较旧的快照<br/>右侧为较新的快照 | 仅存在于较新快照的内容 | 仅存在于较旧快照的内容 |
| 准备回滚       | `2023-04-22 01:00:00 => 2023-04-21 01:00:00` | 左侧为较新的快照<br/>右侧为较旧的快照 | 仅存在于较旧快照的内容 | 仅存在于较新快照的内容 |

**Comment by 88250** [comment]
先加切换吧，加了应该就够用了，顺便把默认改为左侧为较新时间。

**Comment by Zuoqiu-Yingyi** [comment]
> 先加切换吧，加了应该就够用了，顺便把默认改为左侧为较新时间。

目标是为了解决问题, 不是为了够用呀

不明确提示出快照对比时所站的视角, 那么仅把默认改为左侧为较新时间会更加反直觉的

**Comment by 88250** [comment]
你指的是在顶部增加这个标识吗？

![image](https://user-images.githubusercontent.com/873584/233777512-9172fa93-11f9-4694-a7e3-d72fdfa33ab7.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 你指的是在顶部增加这个标识吗？
> 
> ![image](https://user-images.githubusercontent.com/873584/233777512-9172fa93-11f9-4694-a7e3-d72fdfa33ab7.png)

是的, 中间的箭头可以设置为一个按钮, 点一下切换方向

**Comment by 88250** [comment]
好的。

**Comment by Zuoqiu-Yingyi** [comment]
1. 根据 `2.8.6-dev2` 的效果来看, `添加` 与 `删除` 列表的内容好像还是颠倒的👀

`2023-04-15 02:39` → `2023-04-17 12:31` 应该表示从 `2023-04-15 02:39` 到 `2023-04-17 12:31` 这一段时间更新了哪些内容, 添加了哪些内容, 删除了哪些内容

`2023-04-17 12:31` → `2023-04-15 02:39` 应该表示若从 `2023-04-17 12:31` 回滚到 `2023-04-15 02:39` 将更新哪些内容, 添加哪些内容, 删除哪些内容

![image](https://user-images.githubusercontent.com/49649786/233783123-47761114-edba-4455-9285-7052dc1a6f29.png)

2. 中间的 `→` 按钮最好可以鼠标悬浮提示 `交换对比方向`, 不然可能用户会认为是回滚按钮导致不敢点击

**Comment by 88250** [comment]
1. 没有颠倒，是按左右对比的
2. 稍后添加

**Comment by Zuoqiu-Yingyi** [comment]
> 1. 没有颠倒，是按左右对比的

那么目前箭头具体的语义是什么，有点不太理解👀

**Comment by 88250** [comment]
左边相较于右边的 add/update/remove 差异

**Comment by zxhd863943427** [comment]
> 左边相较于右边的 add/update/remove 差异

这个解释是说的通的，但是与用户的第一直觉不符合。 a => b 的含义，在我作为用户的第一印象是从 a 更新到 b 产生的变化，而不是 a 相较于 b 的 add/update/remove 差异 

还是希望D大改一下图标，这种功能达到了，但是就是与用户第一印象相悖的感觉真的很怪异。

我敢断言，如果不改，那就是增加了第三方主题的负担：一大堆自定义主题将会以修改这个图标为己任。:)

**Comment by 88250** [comment]
你指的是改啥图标……

**Comment by zxhd863943427** [comment]
![图片](https://user-images.githubusercontent.com/74853597/233818709-e84af91d-69a8-432a-aa69-752df6d7af87.png)

把这个图标改成反过来的：）

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/233818778-ac385b80-f4df-40d5-b944-00ff6fb638c3.png)

这里没有歧义吧。

**Comment by Zuoqiu-Yingyi** [comment]
> 左边相较于右边的 add/update/remove 差异

除了常用 git 的人，一般人真的想不到这一层，箭头在这里大多数人都会认为是快照变更的方向而非指示以哪个快照为基础

**Comment by zxhd863943427** [comment]
当然最好还是把
![图片](https://user-images.githubusercontent.com/74853597/233818749-427fa2ee-ed65-4d27-87c1-b2cfbbeb3d36.png)
反过来，毕竟日常还是习惯从左边更新到右边的表示，改了图标后，从右边更新到左边并不符合习惯。

只是改图标是两害择其轻罢了。

**Comment by zxhd863943427** [comment]
> > 左边相较于右边的 add/update/remove 差异
> 
> 除了常用 git 的人，一般人真的想不到这一层，箭头在这里大多数人都会认为是快照变更的方向而非指示以哪个快照为基础

我日常使用git，也只是觉得这个解释可以理解，但还是接受不能。

**Comment by Zuoqiu-Yingyi** [comment]
> ![image](https://user-images.githubusercontent.com/873584/233818778-ac385b80-f4df-40d5-b944-00ff6fb638c3.png)
> 
> 这里没有歧义吧。

更新一直都没有，添加与删除才有

**Comment by 88250** [comment]
> 反过来，毕竟日常还是习惯从左边更新到右边的表示，改了图标后，从右边更新到左边并不符合习惯。

之前就是反过来的啊，你看下 https://ld246.com/article/1682148754416 的讨论。

**Comment by 88250** [comment]
> 更新一直都没有，添加与删除才有

![image](https://user-images.githubusercontent.com/873584/233818965-e6ed9117-ff65-4b2e-88e6-ee7aa00a3a14.png)

显示的是删除的文件，也没有歧义嘛。

**Comment by Zuoqiu-Yingyi** [comment]
> 之前就是反过来的啊，你看下 https://ld246.com/article/1682148754416 的讨论。

之前也是说新增与删除列表内容的是反的，更新预览面板的左右布局一直都没有问题

**Comment by Zuoqiu-Yingyi** [comment]
> ![image](https://user-images.githubusercontent.com/873584/233818965-e6ed9117-ff65-4b2e-88e6-ee7aa00a3a14.png)
> 
> 显示的是删除的文件，也没有歧义嘛。

瞅瞅这张图片

![image](https://user-images.githubusercontent.com/49649786/233783123-47761114-edba-4455-9285-7052dc1a6f29.png)

用户迷惑为什么从15号到17号删除了 2023-04-17 这个文件，明明是17号新增了这个文件

**Comment by 88250** [comment]
你把旧版放在左边的话就是这样的，旧版对比新版是删除。

**Comment by Zuoqiu-Yingyi** [comment]
> 你把旧版放在左边的话就是这样的，旧版对比新版是删除。

问题在于用户不知道箭头表示 `基于` 的意思，而是根据常识理解为 `由...到...` 的意思，这就是歧义

**Comment by 88250** [comment]
那就还是箭头的问题，改成 `...`？

**Comment by Zuoqiu-Yingyi** [comment]
> 那就还是箭头的问题，改成 `...`？

那更糟了，这下用户都不知道是啥东西了
按我的说法，将新增与删除列表内容调换一下就可以，不要在 `基于` 这方面下功夫了，用户没有经验的话无论如何都是 get 不到👀

**Comment by 88250** [comment]
调换以后图看上去不对啊，还是上面的例子，本来是新版新增的，调换以后放在删除里面了。

![image](https://user-images.githubusercontent.com/873584/233819365-62215842-0755-4ce8-a57a-ad713656283e.png)

**Comment by Zuoqiu-Yingyi** [comment]
> 调换以后图看上去不对啊，还是上面的例子，本来是新版新增的，调换以后放在删除里面了。
> 
> ![image](https://user-images.githubusercontent.com/873584/233819365-62215842-0755-4ce8-a57a-ad713656283e.png)
> 

哪里不对了，普通用户看来`由`新版本`到`旧版本会删除新添加的文件，这是顺理成章&符合实际的

不要去想 `基于`

**Comment by 88250** [comment]
那看来确实是图标的问题，会让人理解为 `到`，而不是 `对比`。

**Comment by 88250** [comment]
改成文字 `对比` 吧 :trollface:

**Comment by Zuoqiu-Yingyi** [comment]
> 改成文字 `对比` 吧 :trollface: 

不好，箭头本来还有方向性的语义，对比方向性直接没有了

**Comment by 88250** [comment]
→还有个问题是用户不知道可以点，改成 点击切换对比方向 应该是最优解了。



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 23, 2023 12:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve data snapshot comparison (Issue#8081)




  
改成文字 对比 吧 
  
不好，箭头本来还有方向性的语义，对比方向性直接没有了

**Comment by Zuoqiu-Yingyi** [comment]
> →还有个问题是用户不知道可以点，改成 点击切换对比方向 应该是最优解了。

不要想当然，在 `更新` 的预览界面本身也包含有方向的时序信息，不会因为把箭头移除了就能消歧

**Comment by zxhd863943427** [comment]
别啊，我觉得方向箭头就是挺好的，实在不行换个箭头方向就行了。

无论如何，“基于”的概念是不符合大多数用户的体验的，换成对比后，只是改把有方向的信息变成更模糊的信息了。

**Comment by Zuoqiu-Yingyi** [comment]
最好还是参考我上面那张表格，是我以普通用户视角全面考虑的结果👀

**Comment by zxhd863943427** [comment]
> 最好还是参考我上面那张表格，是我以普通用户视角全面考虑的结果👀

确实，我也认为这个合理。

**Comment by Aiviokoo** [comment]
> 最好还是参考我上面那张表格，是我以普通用户视角全面考虑的结果👀

赞同，我认为很合理，D大要是不放心，我们可以考虑去社区发个投票。

**Comment by 88250** [comment]
那好吧，既然大家都这样认为，等会我再改改看。
