### ISSUE TITLE
希望可以提供一个，可关闭自动ocr的选项

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8084]
### In what scenarios do you need this feature?

之前按照大米老师的这篇文章（感谢）：https://ld246.com/article/1674195427260 无脑配置了ocr。
最近版本又加了支持图片ocr出来，诚然，这是一个很使实用的功能。
但我现在都想关了，又有点舍不得直接删除全部配置（万一又要用呢），也不知道怎么暂时关掉。
还有以下原因：
自动ocr在一次性多放几张图后会影响性能
还有就是识别率有限，毕竟是开源包，这个确实没办法，要是有白描的识别率就挺无敌了，哈哈，我放弃幻想）

### Describe the optimal solution

希望可以提供一个ocr的总开关

**Comment by 88250** [comment]
只需要改一下环境变量的名称即可，暂时不考虑内置配置项，谢谢。
