### ISSUE TITLE
Support connecting mobile and desktop application to docker

### ISSUE THREAD

**Issue by Igorgro** [siyuan-note/siyuan#8091]
### In what scenarios do you need this feature?

I want to have full featured self-hosted notes application

### Describe the optimal solution

Allow desktop and mobile apps to connect to docker instance

### Other information

Readm says that docker instance "does not support desktop and mobile application connections, only supports use on browsers". Is this made intentionally or it is just unimplemented yet?

**Comment by 88250** [comment]
Hello, this is currently not considered for implementation, sorry.

**Comment by KaKi87** [comment]
Why not ? 😭
