### ISSUE TITLE
文档标题支持 emoji 快捷输入

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#8092]
### In what scenarios do you need this feature?

同名文档标题，通过补充emoji来区分。

### Describe the optimal solution

现在正文输入冒号加字母，会弹出emoji选择窗格，希望在编辑标题时也支持 :  触发

**Comment by 88250** [comment]
请通过文档图标调整，或者使用输入法键入（比如 Windows 端可以用 Win+.）
