### ISSUE TITLE
Azure OpenAI AI support

### ISSUE THREAD

**Issue by syan2018** [siyuan-note/siyuan#8095]
### In what scenarios do you need this feature?

https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

Azure的OpenAI接口更原生OpenAI接口有一定区别，目前没法直接配置使用，希望能予以支持

### Describe the optimal solution

```python
openai.api_type = "azure"
openai.api_base = "https://technicaldesigner.openai.azure.com/"
openai.api_version = "2023-03-15-preview"
openai.api_key = 

model = AzureChatOpenAI(
    openai_api_base = openai.api_base,
    openai_api_version = openai.api_version,
    openai_api_key = openai.api_key,
    openai_api_type = openai.api_type,
    deployment_name = "TestChat",
)
```

调用AzureOpenAI需要增补部署名、apitype、接口版本等属性

**Comment by 88250** [comment]
非常抱歉，这个目前就不考虑了，因为没有太多需求。

**Comment by BopSun** [comment]
现在这个问题还未解决对么？

**Comment by 88250** [comment]
没有的，谢谢。



---Original---
From: ***@***.***&gt;
Date: Fri, Jan 19, 2024 08:27 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Azure OpenAI AI support (Issue #8095)




 
现在这个问题还未解决对么？

**Comment by 88250** [comment]
由于我这里没有条件进行测试，新版本发布后还麻烦大家帮忙测试，谢谢。

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/d51182fa-9a42-4583-9096-f624f461bbf9)

**Comment by Donjae-Wang** [comment]
感谢作者增加azure支持，不过我在切换到azure之后没有找到填写部署名、apitype、接口版本这些属性的地方，请问一下这个该在哪里填写，如果在API 基础地址中填写完整的URL也仍然报错，我在gpt_acadimic中是可以正常使用的

**Comment by 88250** [comment]
@Donjae-Wang 现在设置有问题，下个版本改进 https://github.com/siyuan-note/siyuan/issues/10390
