### ISSUE TITLE
拖动标签会导致PDF后翻很多页

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

默认主题可以复现，见视频。
首先我的pdf在左侧（77页），我在左侧打开新文档覆盖了pdf界面，然后我把该标签挪动到右侧，左侧pdf重新显示后被翻到了424页，有时是419页，有时是420页，不规律。

![QQ录屏20230424225830](https://user-images.githubusercontent.com/125173405/234037193-83f07b46-e7cb-43e4-9c3e-e1a4d6cf3a0a.gif)

### Expected result

希望能修复或解释原因。

### Version environment

```markdown
- Version: 最新的2.8.5dev
- Operating System: windows
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
麻烦发一下这个 PDF 给我们 845765@qq.com
