### ISSUE TITLE
After using `The name of the new subdocument is` by `F3` in an empty block, it will no longer automatically select all

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#8099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 如果使用快捷键"新建子文档名为"时,当前行是空段落,那么在创建完引用时会选中当前文档所有块

![Snipaste_环境返回_2023-04-25__09-43-02](https://user-images.githubusercontent.com/48077521/234153962-4b4def19-224e-4611-bb88-3039360490e4.png)

2. 如果创建的子文档已经存在,那么会使用那个文档,而不是创建新的同名文档 ,即便是未命名文档 (Untitled),也会如此

建议: 如果同名子文档已经存在,则询问用户是使用已存在的,还是创建新的

两个子文档同名的场景举例:
一个文档有两个公式, 这两个公式各自都有一个对应的 "推导" 文档,

### Expected result

`

### Version environment

```markdown
`
```

### Log file

`

### More information

`

**Comment by 88250** [comment]
第一点问题稍后改进，第二点不考虑了，还是遵循优先沿用同名的规则。

**Comment by iamqiz** [comment]
第二点 手动创建时,是可以创建多个同名文档的(包括自定义名字和未命名),如下图

![Snipaste_环境返回_2023-04-28__18-29-01](https://user-images.githubusercontent.com/48077521/235124118-309dd934-b879-4b0d-8f5c-9af8310aa83c.png)

那通过快捷键创建也不应该强制同名哇

**Comment by 88250** [comment]
F3 的沿用同名比较方便，不然每次遇到要引用的子文档会新建不同的文档不符合设计。

**Comment by iamqiz** [comment]
引用同名文档,首选应该用 [[ 符号哇,如果没有同名文档,它还会提示创建新文档,
![Snipaste_环境返回_2023-04-28__20-20-46](https://user-images.githubusercontent.com/48077521/235145789-193e5958-6715-4648-b46c-88249a7da9c9.png)

但使用F3,如果想创建同名的新文档咋办?  

最好的方法就是 灵活处理: 
> 建议: 如果同名子文档已经存在,则询问用户是使用已存在的,还是创建新的

**Comment by 88250** [comment]
我指的是选择文本以后按 F3 的情况沿用同名，这样方便标记。

**Comment by iamqiz** [comment]
那不选中时, 出现同名, 是弹窗让用户选择,还是一律创建新的?

**Comment by 88250** [comment]
建新的吧

**Comment by iamqiz** [comment]
> 建新的吧

可以 不错
