### ISSUE TITLE
行内代码自动换行显示效果不佳

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![IMG_20230426_010459](https://user-images.githubusercontent.com/32903588/234351217-d6c3fadd-2de7-46bf-909a-99871b106a1a.jpg)
![IMG_20230426_010444](https://user-images.githubusercontent.com/32903588/234351235-89800fd5-baa8-403b-aaf5-30cd6a124b57.jpg)
自动换行后，上一行会有一点没下来

### Expected result

统一到一处

### Version environment

```markdown
- Version: 2.8.6
- Operating System: Android and win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
如果不换行的话，较长代码块就会撑坏界面，如果个人无较长代码块可在自定义 css 中修改。

由于需要兼容长代码块，这里就不进行统一处理。

**Comment by Temacc0531** [comment]
题主的意思应该是换行后不应该还残留一点行内代码的背景在上一行的意思吧😂

**Comment by Vanessa219** [comment]
这个是样式的自动换行，不是 `\n`

**Comment by TinkMingKing** [comment]
> 这个是样式的自动换行，不是 `\n`

就是 @Temacc0531 的意思

> 换行后不应该还残留一点行内代码的背景在上一行

**Comment by Vanessa219** [comment]
你截图上并没有真正的换行，是被宽度挤压了换行，如果窗口拖大的话就不会换行了。这种情况需参照上面说的方案进行解决

**Comment by TinkMingKing** [comment]
> 你截图上并没有真正的换行，是被宽度挤压了换行，如果窗口拖大的话就不会换行了。这种情况需参照上面说的方案进行解决

被挤压换行可以，我想说的问题是，图中几处，上一行已经没有内容了，还有样式残留在上面，**注意那并不是空格**。所以能否优化一下这样的情况。

正常情况应该是，要么被截断，要么全部挤压下来，内容全部下来了但是样式残留在上面是有问题的，让人觉得显示效果没那么好，当然，如果这是特性的话就当我没说吧。

**Comment by Vanessa219** [comment]
这个只能自定义 CSS 来进行解决，由于代码块的光标需在这四个位置可以停留，所以目前还没有办法解决你说的问题
<img width="179" alt="image" src="https://user-images.githubusercontent.com/970828/236590558-27340612-2114-4be8-aaf4-a69835afea9c.png">
