### ISSUE TITLE
Parse occurs exception after adding `- `, `* ` and `[] ` before heading

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8106]
* https://github.com/siyuan-note/siyuan/issues/7972
* https://ld246.com/article/1682434575654

**Comment by zxhd863943427** [comment]
我认为只有[] 有足够存在的必要，其他都是有可能作为内容出现在标题开头的。

**Comment by 88250** [comment]
参考 Notion，`* ` 也应该可以转换。
