### ISSUE TITLE
列表Shift换行后再输入，渲染异常

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#811]
### 描述问题 Describe the problem
1. 输入一个列表块
2. `Shift`+回车换行
3. 输入 `-`
4. 列表字体显示异常

### 期待的结果 Expected result
期望编辑体验能够更加顺滑一些，编辑列表时，字体能够正常显示

### 截屏或录屏演示 Screenshot or screen recording presentation
![列表渲染异常](https://user-images.githubusercontent.com/15924513/102896985-46e90880-44a2-11eb-9692-98580c44b1f1.gif)

### 版本环境 Version environment

* 版本 Version：0.5.42
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，这是因为命中了 Setext 标题语法……这个点上确实有点问题，我们后期再看看如何平滑解决。眼目前只能先打好一些内容再打 `-` 了：

![issue](https://user-images.githubusercontent.com/873584/103175108-8fd5fe00-48a2-11eb-81c5-c71b39820a36.gif)
