### ISSUE TITLE
Tab text overlaps in Ubuntu dark mode

### ISSUE THREAD

**Issue by work4blue** [siyuan-note/siyuan#8111]
ubuntu 黑色模式下，标签页文字重叠

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

每一次切换标签文字就叠加一次

### Expected result

每一次切换标签文字就叠加一次

### Screenshot or screen recording presentation

![截图 2023-04-27 09-05-12](https://user-images.githubusercontent.com/1583762/234733903-11f30ce9-67d9-4476-8845-b0341f9d8d06.png)

### Version environment

```markdown
- Version: v2.8.5
- Operating System: Ubuntu 22.04
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11338638/siyuan.log)

**Comment by 88250** [comment]
在明亮模式下正常吗？

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
