### ISSUE TITLE
File system access error

### ISSUE THREAD

**Issue by beaufang** [siyuan-note/siyuan#8112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

没有使用地三方同步盘，使用的是 S3 同步，输入的时候总是提示文件系统错误。

### Expected result

正常输入

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/18215661/234745504-5c97186c-01b4-4b56-8030-2dfdc103a11c.png)

### Version environment

```markdown
- Version: 2.8.6
- Operating System: win11
- Browser (if used):
```

### Log file

I 2023/04/26 17:52:59 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/04/26 17:52:59 runtime.go:51: kernel is booting:
    * ver [2.8.6]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [41532]
    * runtime mode [prod]
    * working directory [D:\Program Files\siyuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\tp\sy-notes]
I 2023/04/26 17:52:59 conf.go:126: initialized language [zh_CN] based on device locale
I 2023/04/26 17:52:59 runtime.go:105: use network proxy [system]
I 2023/04/26 17:52:59 serve.go:111: kernel [pid=41532] http server [127.0.0.1:61505] is booting
I 2023/04/26 17:53:00 database.go:88: the database structure is changed, rebuilding database...
I 2023/04/26 17:53:01 database.go:108: reinitialized database [E:\tp\sy-notes\temp\siyuan.db]
I 2023/04/26 17:53:01 conf.go:677: database size [4.1 kB], tree/block count [0/0]
I 2023/04/26 17:53:01 working.go:157: kernel booted
I 2023/04/26 17:53:02 box.go:74: auto stat [trees=0, blocks=0, dataSize=29 kB, assetsSize=0 B]
I 2023/04/26 17:53:02 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/26 17:53:06 index.go:132: rebuilt database for notebook [20210808180117-czj9bvb] in [0.39s], tree [count=56, size=1.2 MB]
I 2023/04/26 17:53:06 index.go:205: resolved refs [22] in [73ms]
I 2023/04/26 17:53:08 working.go:424: initialized built-in pandoc [ver=3.1.1, bin=E:\tp\sy-notes\temp\pandoc\bin\pandoc.exe]
W 2023/04/26 17:53:23 blocktree.go:451: save block tree [size=629 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [16.38s]
I 2023/04/26 17:58:39 index.go:132: rebuilt database for notebook [20230426175839-737lzge] in [0.00s], tree [count=0, size=0 B]
I 2023/04/26 17:58:39 index.go:205: resolved refs [22] in [68ms]
W 2023/04/26 18:03:04 blocktree.go:451: save block tree [size=117 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [2.04s]
I 2023/04/26 18:16:01 index.go:132: rebuilt database for notebook [20210808180117-czj9bvb] in [0.06s], tree [count=56, size=1.2 MB]
I 2023/04/26 18:16:02 index.go:205: resolved refs [22] in [136ms]
I 2023/04/26 18:26:51 repository.go:1138: synced data repo [provider=2, ufc=21, dfc=1, ucc=19, dcc=0, ub=52 kB, db=0 B] in [2.99s]
I 2023/04/26 18:28:10 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.36s]
I 2023/04/26 18:31:02 repository.go:1138: synced data repo [provider=2, ufc=4, dfc=1, ucc=1, dcc=0, ub=2.1 kB, db=1.2 kB] in [1.66s]
I 2023/04/26 18:32:10 repository.go:1138: synced data repo [provider=2, ufc=3, dfc=1, ucc=1, dcc=0, ub=1.7 kB, db=1.3 kB] in [2.39s]
F 2023/04/26 18:32:37 filelock.go:147: write file [E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230426175923-pca14eg.sy] failed: rename E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230426175923-pca14eg.sygisebqi.tmp E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230426175923-pca14eg.sy: Access is denied.
I 2023/04/26 18:32:51 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/04/26 18:32:51 runtime.go:51: kernel is booting:
    * ver [2.8.6]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [41860]
    * runtime mode [prod]
    * working directory [D:\Program Files\siyuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\tp\sy-notes]
I 2023/04/26 18:32:51 runtime.go:105: use network proxy [system]
I 2023/04/26 18:32:51 serve.go:111: kernel [pid=41860] http server [127.0.0.1:55078] is booting
I 2023/04/26 18:32:51 sync.go:150: sync before boot
I 2023/04/26 18:32:51 working.go:401: built-in pandoc [ver=3.1.1, bin=E:\tp\sy-notes\temp\pandoc\bin\pandoc.exe]
I 2023/04/26 18:32:52 repository.go:1034: boot get sync cloud files elapsed [0.63s]
I 2023/04/26 18:32:52 blocktree.go:401: read block tree [637 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [0.06s]
I 2023/04/26 18:32:52 conf.go:677: database size [5.1 MB], tree/block count [61/2309]
I 2023/04/26 18:32:52 working.go:157: kernel booted
I 2023/04/26 18:32:52 box.go:74: auto stat [trees=61, blocks=2309, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/26 18:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/26 18:32:53 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/04/26 18:32:54 index.go:132: rebuilt database for notebook [20210808180117-czj9bvb] in [0.39s], tree [count=56, size=1.2 MB]
W 2023/04/26 18:32:59 blocktree.go:451: save block tree [size=132 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [2.19s]
I 2023/04/26 18:34:44 repository.go:1138: synced data repo [provider=2, ufc=5, dfc=1, ucc=2, dcc=0, ub=3.0 kB, db=1.3 kB] in [2.12s]
I 2023/04/26 18:42:46 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.63s]
I 2023/04/26 18:50:47 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.43s]
I 2023/04/26 18:58:48 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.51s]
I 2023/04/26 19:14:51 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.81s]
I 2023/04/26 19:46:55 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.85s]
I 2023/04/26 20:32:52 box.go:74: auto stat [trees=62, blocks=2316, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/26 20:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/26 20:50:56 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.68s]
I 2023/04/26 22:32:52 box.go:74: auto stat [trees=62, blocks=2316, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/26 22:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/26 22:58:59 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.83s]
I 2023/04/27 00:32:52 box.go:74: auto stat [trees=62, blocks=2316, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 00:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/27 02:32:52 box.go:74: auto stat [trees=62, blocks=2316, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 02:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/27 03:15:03 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.1 kB] in [0.78s]
I 2023/04/27 04:32:52 box.go:74: auto stat [trees=62, blocks=2316, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 04:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/27 06:32:52 box.go:74: auto stat [trees=62, blocks=2316, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 06:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/27 08:32:52 box.go:74: auto stat [trees=62, blocks=2316, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 08:32:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
I 2023/04/27 08:43:35 repository.go:1138: synced data repo [provider=2, ufc=3, dfc=1, ucc=1, dcc=0, ub=1.9 kB, db=1.4 kB] in [1.98s]
I 2023/04/27 08:45:28 repository.go:1138: synced data repo [provider=2, ufc=6, dfc=1, ucc=3, dcc=0, ub=3.6 kB, db=1.4 kB] in [2.62s]
I 2023/04/27 08:48:45 repository.go:1138: synced data repo [provider=2, ufc=4, dfc=1, ucc=2, dcc=0, ub=2.8 kB, db=1.5 kB] in [2.15s]
I 2023/04/27 08:51:22 repository.go:1138: synced data repo [provider=2, ufc=3, dfc=1, ucc=1, dcc=0, ub=3.1 kB, db=1.6 kB] in [1.97s]
I 2023/04/27 08:52:25 repository.go:1138: synced data repo [provider=2, ufc=4, dfc=1, ucc=2, dcc=0, ub=3.6 kB, db=1.6 kB] in [2.41s]
I 2023/04/27 08:53:11 repository.go:1138: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=1.2 kB] in [0.42s]
F 2023/04/27 08:54:48 filelock.go:147: write file [E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy] failed: rename E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy859n0kp.tmp E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy: Access is denied.
I 2023/04/27 08:55:21 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/04/27 08:55:21 runtime.go:51: kernel is booting:
    * ver [2.8.6]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [35132]
    * runtime mode [prod]
    * working directory [D:\Program Files\siyuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\tp\sy-notes]
I 2023/04/27 08:55:21 runtime.go:105: use network proxy [system]
I 2023/04/27 08:55:21 serve.go:111: kernel [pid=35132] http server [127.0.0.1:57245] is booting
I 2023/04/27 08:55:22 working.go:401: built-in pandoc [ver=3.1.1, bin=E:\tp\sy-notes\temp\pandoc\bin\pandoc.exe]
I 2023/04/27 08:55:22 sync.go:150: sync before boot
I 2023/04/27 08:55:23 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/04/27 08:55:23 repository.go:1034: boot get sync cloud files elapsed [1.09s]
I 2023/04/27 08:55:24 blocktree.go:401: read block tree [630 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [0.53s]
I 2023/04/27 08:55:24 conf.go:677: database size [7.2 MB], tree/block count [64/2284]
I 2023/04/27 08:55:24 working.go:157: kernel booted
I 2023/04/27 08:55:24 box.go:74: auto stat [trees=64, blocks=2284, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 08:55:24 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
W 2023/04/27 08:55:31 blocktree.go:451: save block tree [size=119 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [2.27s]
I 2023/04/27 08:56:41 repository.go:1138: synced data repo [provider=2, ufc=4, dfc=1, ucc=1, dcc=0, ub=2.9 kB, db=1.6 kB] in [2.13s]
I 2023/04/27 08:57:43 repository.go:1138: synced data repo [provider=2, ufc=3, dfc=1, ucc=1, dcc=0, ub=2.8 kB, db=1.6 kB] in [1.44s]
I 2023/04/27 09:01:39 repository.go:1138: synced data repo [provider=2, ufc=3, dfc=1, ucc=1, dcc=0, ub=2.9 kB, db=1.7 kB] in [1.54s]
I 2023/04/27 09:03:07 repository.go:1138: synced data repo [provider=2, ufc=3, dfc=1, ucc=1, dcc=0, ub=2.1 kB, db=1.7 kB] in [1.75s]
W 2023/04/27 09:05:42 blocktree.go:451: save block tree [size=120 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [2.56s]
I 2023/04/27 09:11:12 index.go:132: rebuilt database for notebook [20210808180117-czj9bvb] in [0.06s], tree [count=56, size=1.2 MB]
I 2023/04/27 09:11:12 index.go:205: resolved refs [22] in [83ms]
W 2023/04/27 09:11:15 blocktree.go:451: save block tree [size=135 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [2.41s]
W 2023/04/27 09:36:06 blocktree.go:451: save block tree [size=120 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [2.20s]
F 2023/04/27 09:51:02 filelock.go:147: write file [E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy] failed: rename E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy1852c06.tmp E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy: Access is denied.
I 2023/04/27 09:51:15 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/04/27 09:51:15 runtime.go:51: kernel is booting:
    * ver [2.8.6]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [25312]
    * runtime mode [prod]
    * working directory [D:\Program Files\siyuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\tp\sy-notes]
I 2023/04/27 09:51:15 runtime.go:105: use network proxy [system]
I 2023/04/27 09:51:15 serve.go:111: kernel [pid=25312] http server [127.0.0.1:49740] is booting
I 2023/04/27 09:51:15 sync.go:150: sync before boot
I 2023/04/27 09:51:16 working.go:401: built-in pandoc [ver=3.1.1, bin=E:\tp\sy-notes\temp\pandoc\bin\pandoc.exe]
I 2023/04/27 09:51:17 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/04/27 09:51:18 repository.go:1034: boot get sync cloud files elapsed [2.81s]
I 2023/04/27 09:51:18 blocktree.go:401: read block tree [634 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [0.33s]
I 2023/04/27 09:51:18 conf.go:677: database size [7.2 MB], tree/block count [65/2300]
I 2023/04/27 09:51:18 working.go:157: kernel booted
I 2023/04/27 09:51:18 box.go:74: auto stat [trees=65, blocks=2300, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 09:51:18 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
W 2023/04/27 10:11:45 blocktree.go:451: save block tree [size=121 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [2.04s]
F 2023/04/27 10:25:54 filelock.go:147: write file [E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy] failed: rename E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.syfcaei7m.tmp E:\tp\sy-notes\data\20230426175839-737lzge\20230426175923-duv6usd\20230426175923-woy78r2\20230426175923-9zszloz\20230427084256-cwjl1e8.sy: Access is denied.
I 2023/04/27 10:26:50 working.go:119: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/04/27 10:26:50 runtime.go:51: kernel is booting:
    * ver [2.8.6]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [37672]
    * runtime mode [prod]
    * working directory [D:\Program Files\siyuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\tp\sy-notes]
I 2023/04/27 10:26:50 runtime.go:105: use network proxy [system]
I 2023/04/27 10:26:50 serve.go:111: kernel [pid=37672] http server [127.0.0.1:51432] is booting
I 2023/04/27 10:26:50 sync.go:150: sync before boot
I 2023/04/27 10:26:50 working.go:401: built-in pandoc [ver=3.1.1, bin=E:\tp\sy-notes\temp\pandoc\bin\pandoc.exe]
I 2023/04/27 10:26:51 repository.go:1034: boot get sync cloud files elapsed [1.44s]
I 2023/04/27 10:26:52 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
I 2023/04/27 10:26:52 blocktree.go:401: read block tree [635 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [0.04s]
I 2023/04/27 10:26:52 conf.go:677: database size [7.2 MB], tree/block count [67/2304]
I 2023/04/27 10:26:52 working.go:157: kernel booted
I 2023/04/27 10:26:52 box.go:74: auto stat [trees=67, blocks=2304, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/04/27 10:26:52 disk.go:33: disk usage [total=463 GB, used=20 GB, free=443 GB]
W 2023/04/27 10:27:00 blocktree.go:451: save block tree [size=121 kB] to [E:\tp\sy-notes\temp\blocktree], elapsed [3.33s]

**Comment by 88250** [comment]
请参考 https://ld246.com/article/1682411112522
