### ISSUE TITLE
Use the doc icon first in the block ref search list

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#8115]
https://ld246.com/article/1682575804598

**Comment by Vanessa219** [comment]
不显示对不齐不好看哇

**Comment by mozhux** [comment]
> 不显示对不齐不好看哇

好吧，那只能主题隐藏了，本身思源因为各样的块标、面包屑的存在，页面比较繁杂看起来，再多这个块搜索的，只能个人能隐藏就隐藏了。
