### ISSUE TITLE
Ctrl + K 插入链接时，链接被截断，需要再次 Ctrl + V 粘贴一次，有点麻烦了

### ISSUE THREAD

**Issue by sugarlesss** [siyuan-note/siyuan#8116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图所示：
![image](https://user-images.githubusercontent.com/49931320/234870370-a0f22792-870c-4815-9749-0900d468074b.png)

### Expected result

希望能修复一下，免去再次 Ctrl + V 这一次操作

### Version environment

```markdown
- Version: 2.8.6
- Operating System: Windows
- Browser (if used): None
```

### Log file

none

**Comment by 88250** [comment]
这个是缩略锚文本的特性，请看 https://github.com/siyuan-note/siyuan/issues/6798

目前暂时不考虑通过配置项控制缩略长短，还需要继续收集这方面的反馈。如果后续实在有必要我们再考虑，感谢理解和支持。
