### ISSUE TITLE
支持redis缓存方案

### ISSUE THREAD

**Issue by Lizhen0628** [siyuan-note/siyuan#8119]
### In what scenarios do you need this feature?

在导入大量的logo图标之后发现通过浏览器浏览笔记的时候会有些卡顿

### Describe the optimal solution

笔记作为一个低频修改，高频查询的信息，一旦录入很少变动。这一特性非常适合使用redis来进行优化。希望D大能够针对docker部署笔记软件的用户提供redis缓存支持。

**Comment by 88250** [comment]
这个暂时不考虑了，感谢提议。
