### ISSUE TITLE
对嵌入块生成 ref 链接逻辑的想法

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8121]
### 问题

我之前用嵌入块用的不多，这段时间开始用嵌入块后发现了这个问题。同样是 SQL 语句查询的结果，有的会生成一个 ref 链接，有的就不会。

我做了一个简单的实验，如下所示：

![image](https://user-images.githubusercontent.com/27268127/235051027-9070827b-ed33-4494-aff0-e2c30999e98e.png)

根据实验结果，我猜想当前思源的方案是只会对「id=""」类的 select 嵌入生成 ref 链接。是这个逻辑吗？

### 讨论

我猜测之所以这么做是为了避免以下的情况：

1. select 一次性选择了大量的块、让后台不得不瞬间大量创建 ref 链接项目。
2. 如果默认创建 ref，那么只要稍微改一下 sql 语句，后台就要耗费大量精力去 delete insert

换句话说，这种设计应该是处于性能考虑而不是功能考虑？

## Describe the optimal solution

但是根据 SQL 嵌入块批量制作链接的需求还是存在的，这里提出一个方案草稿：

1. 默认情况下嵌入块创建 ref 链接的行为和原来保持一致，依然保持：1) 对 id=xx 自动生成链接 2）其他查询不自动生成链接
2. 加入一个功能 menu item，让用户自己决定根据当前的嵌入块生成 ref 链接
    ![image](https://user-images.githubusercontent.com/27268127/235052026-c6f05560-cc2b-47a7-bc18-41c45c184b4d.png)
3. 添加设置，为批量添加 ref 链接设置数量上限；例如：默认设置上限 8，如果 sql 查询的块的数量 `count(*)` 大于 8，则即使用户要求生成 ref 也要拒绝，从而避免大批量 ref 生成影响性能
4. 对一个已经生成了 ref 的嵌入块，当 sql 表达式更改的时候，自动删除所有链接，即便后面又更改回来，原来的 ref 也不会自动恢复，仍然需要手动添加

## Other information

这个功能如果需要更新的话，肯定不是一个小工程，我自己设计的方案也可能存在一些问题，所以需要进一步思考讨论。

**Comment by zxhd863943427** [comment]
并不是，产生ref的根源是用户使用块菜单里的 复制嵌入块 后，需要找到嵌入块，检查嵌入块里面是否使用了id=只能说是实现方案，不是目的。

**Comment by zxhd863943427** [comment]
本质上是为了使思源使用 sql 查询实现的嵌入块，与其他能够找到引用的嵌入块的双链笔记更为接近。

**Comment by 88250** [comment]
楼上说得清晰，这个先关闭了，谢谢。
