### ISSUE TITLE
想法提议：父文档中文档内容若为空，若存在子文档，则打开子文档列表

### ISSUE THREAD

**Issue by svstardust** [siyuan-note/siyuan#8122]
### In what scenarios do you need this feature?

你好，我有个很好的想法

若父文档中文档内容为空，且存在子文档，打开子文档列表

### Describe the optimal solution

对点击的当前文档做判断，
1. 如果该文档中存在文本内容则打开该文档
2. 如果该文档中文本内容为空。则判断是否存在子文档，如果存在子文档，则显示子文档列表
![image](https://user-images.githubusercontent.com/104783889/235073159-48050fd7-b6b0-4b48-a2ad-725014c6817a.png)

**Comment by royc01** [comment]
那想编辑父文档呢？双击？

**Comment by royc01** [comment]
> > 那想编辑父文档呢？双击？
> 
> 想编辑父文档我大概大概有两个方案： 若父文档为空
> 
> 1. 判断是否存在子文档，若存在子文档打开子文档列表，同时打开父文档到编辑
> 2. 就是你说的双击编辑父文档

这样交互变得复杂，远不如之前的双击展开列表直观了

**Comment by 88250** [comment]
这个还是不考虑改交互了，感谢提议。
