### ISSUE TITLE
代码块的体验性增强请求:增加一个快捷键,使得点击某一行时可以复制一整行的内容,而不是把整个代码块复制

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#8124]
### In what scenarios do you need this feature?

在把笔记中的命令拿出来执行的时候,可以直接复制一整行而不是还需要选中再复制(参考logseq),可以提升很多的效率
![截图_20230428160300](https://user-images.githubusercontent.com/62456287/235090841-28db2d02-989b-44a0-8e3a-72ddbb497add.gif)

### Describe the optimal solution

logseq有相关的功能

**Comment by Soltus** [comment]
和直接复制相比，效率提升并不明显

**Comment by 88250** [comment]
用鼠标的话可以三击后选择，单独的功能就不考虑添加了，谢谢。
