### ISSUE TITLE
docker部署 widgets/custom.css  

### ISSUE THREAD

**Issue by crendy** [siyuan-note/siyuan#8125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="803" alt="image" src="https://user-images.githubusercontent.com/6448115/235136011-56ad01e2-47d8-4d26-9610-e6e68e8fcd84.png">

### Expected result

11

### Version environment

```markdown
- Version: 2.8.6
- Operating System: mac
- Browser (if used):chrome
```

### Log file

111

**Comment by 88250** [comment]
默认应该不会请求这个路径，请看下如果是挂件影响的麻烦到对应挂件仓库反馈，谢谢。
