### ISSUE TITLE
希望某些markdown语法可以支持中文符号

### ISSUE THREAD

**Issue by snjhho** [siyuan-note/siyuan#813]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
有时候中文输入法在输入 markdown 的一些功能符号时，需要切换至英文输入法，容易打断思考的流程，既然双链符号（（和【【都能支持中文的全角符号，那么希望“》”引用等符号也可以采用中文。

**Comment by 88250** [comment]
谢谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/42
