### ISSUE TITLE
中西文添加空格等选项从编辑时改为预览/导出时

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#814]
在编辑时添加实际空格会带来较多的问题（例如 #489、#683 和 #732），该选项需要改为仅预览/导出时生效。

这次调整从编辑器设置中移动到导出设置中的选项：

* 自动空格
* 术语修正
* 段首缩进

**Comment by frankli998** [comment]
开发者您好，我想能不能保留编辑时生效的开关？因为我常常需要中英文混排，现阶段思源的导出功能还不是很强。我一般会导出markdown 再从 pdf 导出。所以希望能够允许用户选择关闭自动补充空格，编辑时生效，或者仅仅预览或导出时生效。

**Comment by 88250** [comment]
@frankli998 这个提议就是将自动空格从编辑器选项移到导出选项里的，不是删掉这个功能……

**Comment by frankli998** [comment]
哦哦，理解了。导出markdown 也带空格就没问题
