### ISSUE TITLE
PDF annotation bug, from 2.8.0 onwards the rectangular annotation of the scanned pdf can not be displayed properly.

### ISSUE THREAD

**Issue by Ahidada** [siyuan-note/siyuan#8145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Although labeled, but not displayed in the pdf page, and can not be copied to the label link

### Expected result

Same as before

### Version environment

```markdown
- Version: 2.8.0～2.8.6
- Operating System: Mac-intel
- Browser (if used):
```

### Log file

……

**Comment by Vanessa219** [comment]
Can you screen record the process? I can't reproduce.

**Comment by Ahidada** [comment]
Just like in this video, the pdf rectangle is labeled, but not displayed. With the old version can be opened to see the labeled boxes. For example, version 2.5.3

https://user-images.githubusercontent.com/30532454/235356836-35bbe713-1dfe-45f9-b992-bd21d26b008e.mp4

**Comment by Vanessa219** [comment]
Same as https://github.com/siyuan-note/siyuan/issues/8088, please update and try again. Otherwise upload this pdf file, thanks.
