### ISSUE TITLE
I hope that the pdf rectangular labeling default with a screenshot function to change to set the "default with a screenshot" or "default without a screenshot"

### ISSUE THREAD

**Issue by Ahidada** [siyuan-note/siyuan#8146]
### In what scenarios do you need this feature?

我需要做pdf的目录，不需要截图，我可以ocr。默认带截图的标注该起来比较麻烦
I need to do a pdf of the table of contents, do not need a screenshot, I can ocr. default with a screenshot of the mark up that up more trouble

### Describe the optimal solution

可以配置“默认带截图”或“默认不带截图”。或者设置2个按钮，一个按钮“默认带截图”，一个“默认不带截图”
You can configure "Default with screenshot" or "Default without screenshot".
Or set 2 buttons, one button "Default with screenshot" and one button "Default without screenshot"

**Comment by 88250** [comment]
设计上默认以带截图的场景优先，不需要截图的话粘贴后 Backspace 手动删一下，这个不考虑加设置项了，谢谢。

**Comment by Ahidada** [comment]
每次都要多按3～4次按键、多按一下鼠标……

**Comment by 88250** [comment]
不这样的话截图就要多按一次。
