### ISSUE TITLE
“A content block with IDxxxx was not found”

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#8150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Every time I delete a note, I get a pop-up that says“No ID found for xxxx”

### Expected result

No pop-ups appear

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/37429029/235404912-326c6f7b-a5a1-4bdb-8108-624271ddeedb.png)

### Version environment

```markdown
- Version: 2.8.6
- Operating System: windows
- Browser (if used):
```

### Log file

null

**Comment by 88250** [comment]
请重建索引以后再试试能否重现。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
