### ISSUE TITLE
表格前后添加光标放置位

### ISSUE THREAD

**Issue by CofinCup** [siyuan-note/siyuan#8151]
### In what scenarios do you need this feature?

举例来说，在一个实验报告中往往需要如同下述的结构(有序列表带表格)：
```
1. <Text>
 | <Text>
 |- [Table 1]
```
而当误操作为如下状况时，无法在[Table 1]前点击并放置光标，并ctrl+enter来插入新行：
```
1. [Table 1]
```
不仅在有序列表中，如果表格被放在了页面首行，也同样没有足够便捷的方法在尾部写空行。

### Describe the optimal solution

基于易用考虑，或许可以在以下两处添加光标可插入的位置，这样来允许更多的表格附近的操作：
```
<place1>[Table 1]<place2>
```

### Other information

我能理解思源跟markdown的思路区别，表格是作为内容块来理解的；不过相比markdown类软件，不能随意放置光标还是有点不适应。

**Comment by 88250** [comment]
在表格中 Esc 选中当前块然后 Ctrl+Shift+B，或者使用 Ctrl+/ 唤出当前块菜单，然后 起始插入行。

**Comment by 88250** [comment]
可能会有其他问题，暂时先不做考虑了，谢谢。
