### ISSUE TITLE
Consider putting "add tag" to the document context menu

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8153]
### In what scenarios do you need this feature?

There is now a weird discrepancy. One can add a tag to a document from this little menu that appears when hovering above the title of the document:
![image](https://user-images.githubusercontent.com/63197393/235605736-630f17c4-b758-4e2e-88bb-9ee58242dc67.png)

However, there is also a context menu that appears when clicking on the small document icon next to the title, that says "update attributes". 
![image](https://user-images.githubusercontent.com/63197393/235605805-b9f3b41c-6b64-43fc-bf73-16f68fa52c6c.png)
The context menu that appears has, indeed, "attributes". 
![image](https://user-images.githubusercontent.com/63197393/235605850-76b7b561-bfdd-48f6-98c4-f19b712171c5.png)

When clicked on that, however, there is no tag option. 
![Uploading image.png…]()

This seems to be slightly confusing. Why are attributes under the context menu and not tags which are, in fact, also a type of attributes? 

### Describe the optimal solution

I would consider putting "tags" as an option to the context menu that appears when clicked on a document icon next to the document title:
![image](https://user-images.githubusercontent.com/63197393/235606020-493d5665-50da-438d-9421-263e8b20487c.png)

### Describe the candidate solution

Alternatively, add "tag" as one of the attribute options. 
![image](https://user-images.githubusercontent.com/63197393/235606145-8093a64f-adde-43c3-99c3-14af0a6c00bb.png)

**Comment by 88250** [comment]
Hi, tags in SiYuan are not part of the block attributes.

`#Tag#` is included in the content. You can see the tag elements such as `foo #bar# baz` in the editor. In order to keep the document block consistent with other blocks, we add a tag floating button in the title area to doc tags are supported.

**Comment by ciceronianus** [comment]
This is still confusing, in my opinion. Because the user cannot use #tags# in the page title just by writing them down. They don't convert. 
![image](https://user-images.githubusercontent.com/63197393/235837098-46f7cfca-843f-45f3-859f-d58a179a0da6.png)

So for all practical purposes, tags in the page title behave like attributes and not like tags elsewhere. Or am I missing something?

**Comment by 88250** [comment]
The title part of the document cannot support inline-level elements such as #Tag#, so the compromise solution is to add a tag button.

**Comment by ciceronianus** [comment]
Exactly, but then it behaves similarly to an attribute. It is not anymore in-line.

I don't argue it should be in the attribute menu but that there could be a menu item in the context menu when clicked on the document icon. It is not something super important but some things feel to be in various menus a little bit inconsistently and the this is especially affecting documents, when there are following menus/interactions just related to the whole document:
- context menu when clicked on the document icon left to the page title
- add tag / change icon / cover menu 
- three dots menu upper right

Each of them contains something and sometimes it seems not completely logical. 

Just for consideration.
