### ISSUE TITLE
插入图片时能够选择给图片增加边框

### ISSUE THREAD

**Issue by CodeYiShu** [siyuan-note/siyuan#8155]
### In what scenarios do you need this feature?

插入图片

### Describe the optimal solution

在插入图片时希望能够选择给图片增加边框，这样可以更加立体清晰。

特别是插入带文字的白色图片时，很容易和笔记的背景、文字等混合在一起，增加边框之后可以让图片位置一目了然，笔记整体结构也比较清晰。

比如可以参考有道云7版本插入图片时，可以选择加边框、阴影等。

**Comment by 88250** [comment]
这个暂时不考虑了，建议通过自定义 CSS 解决，感谢提议。

关联 https://ld246.com/article/1683019974642
