### ISSUE TITLE
[feature request] ctrl+v粘贴图片时借助picGo上传图片到图床

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#8159]
### In what scenarios do you need this feature?

希望思源支持自动将图片上传到图床

### Describe the optimal solution

粘贴图片时,调用picGo的api即可将剪贴板图片上传到自定义的图床,然后思源将picGO api返回的图片url地址作为图片链接地址,

picGo的api很简单: POST请求 http://127.0.0.1:36677/upload 即可上传剪贴板图片到默认图床

见:  高级技巧 | PicGo
https://picgo.github.io/PicGo-Doc/zh/guide/advance.html#http%E8%B0%83%E7%94%A8%E4%B8%8A%E4%BC%A0%E5%89%AA%E8%B4%B4%E6%9D%BF%E5%9B%BE%E7%89%87

思源设置里增加一个选项: "粘贴图片时调用picGo自动上传到默认图床", 并有以下几种值:
- 禁用
- 一律上传
- 询问是否上传

picGo github:
https://github.com/Molunerfinn/PicGo

补充: 这个功能还可以拓展到 / 菜单里的 "插入图片或文件", 通过调用picGo API  "HTTP调用上传具体路径图片" ,
见: 
高级技巧 | PicGo
https://picgo.github.io/PicGo-Doc/zh/guide/advance.html#http%E8%B0%83%E7%94%A8%E4%B8%8A%E4%BC%A0%E5%85%B7%E4%BD%93%E8%B7%AF%E5%BE%84%E5%9B%BE%E7%89%87

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/641
