### ISSUE TITLE
The block icon menu adds move-related key combination tips

### ISSUE THREAD

**Issue by StarDustSheep** [siyuan-note/siyuan#8163]
### In what scenarios do you need this feature?

需要引用、嵌入过去自己的笔记的时候。使用此种方法比较方便，但用户可能不知道可以这么操作或是忘记了具体各个组合键的操作。

### Describe the optimal solution

![C2AG)$AL)}C1SV H_Q_VWI](https://user-images.githubusercontent.com/114859111/235826634-6905da54-c671-4a66-bf2e-060ee1222c7c.png)
![F%R$_K{BXS@PRM_93}NPSE2](https://user-images.githubusercontent.com/114859111/235826645-9ad2462d-9e51-4484-8c39-c3e43b016b35.png)

拖拽块有四种可能的操作，默认是移动，还有组合ctrl: 复制并移动；组合alt：生成块引用；组合alt：生成嵌入
在用户已经通过按住块图标拖拽着块的状态下，默认情况以及按ctrl alt shift三种组合键的时候，分别显示四种文字提示，以指示用户将要发生的操作，呈现方式类似图中的样子。

### Describe the candidate solution

另：鼠标悬浮于块图标之上时的tooltip也可以增加这3种操作的提示。
![2H BEQ9L (V336@GC W1}ZL](https://user-images.githubusercontent.com/114859111/235826797-38482e81-6311-47fe-a7b0-7711701daa52.png)

**Comment by Vanessa219** [comment]
增加文字的话界面不太美观，而且用户用组合的话已经明确自己的操作，不需要再次进行提醒。
