### ISSUE TITLE
PDF cannot be moved using `↑/↓`

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用思源打开pdf后，无法使用方向键上下移动。

经过测试，为 2.8.1 向 2.8.2 升级时引入的错误，应该与 pdf 定位改进有关。

### Expected result

可以正常移动

### Version environment

```markdown
- Version: 2.8.6
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by Vanessa219** [comment]
划选有多种方式，我用文本划选的方式无法重现，还麻烦具体描述并录屏。谢谢。

**Comment by zxhd863943427** [comment]
不是划选，就是单纯的上下浏览 pdf，但发现无法使用方向键上下移动。
![pdf](https://user-images.githubusercontent.com/74853597/235961903-171de68a-668a-4829-871a-c9b43b0012b5.gif)
