### ISSUE TITLE
Make searching within a document easier

### ISSUE THREAD

**Issue by ciceronianus** [siyuan-note/siyuan#8166]
### In what scenarios do you need this feature?

If I press `ctrl+f`, I get the same window as when clicking on `ctrl+p` with the only difference that it searches within the document. 

![image](https://user-images.githubusercontent.com/63197393/235902083-b329dd56-e5cd-42f6-9533-a6506d5465a6.png)

The problems with this solutions:
1) If I deactivated searching in paragraphs for the speed (when searching for documents), it is deactivated even when searching within one page. Which does not make sense. So I have to always manually activate searching in paragraphs. 

2) It is much more complicated than what almost everybody else does, i.e. something like this:
![image](https://user-images.githubusercontent.com/63197393/235902297-252e2cec-d0ac-4ff5-8a73-edc509626c62.png) . Such solutions make it much more easier to simply look at different occurrences of specific words.

### Describe the optimal solution

I suggest to simplify default `ctrl+f` search and make it more similar to what everybody else does. 

![image](https://user-images.githubusercontent.com/63197393/235902487-f85951fe-c143-4741-ba2f-12547d2c2ca6.png)

**Comment by 88250** [comment]
A long time ago, the version used a browser-like in-page search, but this would cause a problem: it could not be dynamically loaded (content outside the visible area could not be searched).

So later we use global search and specify the path to limit the current document, which can bring some benefits to users, such as reusing sorting, filtering and other conditions.

This will probably not change in the future, thanks for the feedback.

**Comment by ciceronianus** [comment]
Fair, but what is another solution to my problem? I.e. that global filters don't make any sense for local search within one page?
