### ISSUE TITLE
API `/api/query/sql` add `LIMIT` clause

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8167]
https://ld246.com/article/1683097854903

**Comment by Zuoqiu-Yingyi** [comment]
感觉这个调整引入了好多问题啊, 不少依赖也出现问题了
- #8226 
- [WordCounter 挂件计数问题 - 链滴](https://ld246.com/article/1683858273521)

**Comment by 88250** [comment]
#8226 中进行了改进了，后面再看看。
