### ISSUE TITLE
自动同步多次失败

### ISSUE THREAD

**Issue by jackgreen12345** [siyuan-note/siyuan#8169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

退出思源笔记时，多次出现自动同步失败的问题（即“退出时同步失败，请手动执行一次同步以确保本地数据和云端数据一致 v2.8.6”），均需要强制退出。
失败原因为：同步失败：锁定云端同步目录失败，请稍后再试 (Provider: SiYuan) v2.8.6
由于其自动同步失败次数过多，手动同步同样失败次数过多，因此在此提issue反馈。

### Expected result

期望能不再出现自动同步失败的问题。

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/8382723/236105788-2e70c02d-5d90-49a6-924c-6523dab8bcc3.png)

### Version environment

```markdown
- Version: 2.8.6
- Operating System: Windows 10 64位
- Browser (if used):
```

### Log file

I 2023/05/04 10:41:19 working.go:157: kernel booted
E 2023/05/04 10:41:19 siyuan.go:443: add traffic failed: 401
I 2023/05/04 10:41:19 box.go:74: auto stat [trees=319, blocks=18721, dataSize=262 MB, assetsSize=253 MB]
I 2023/05/04 10:41:19 disk.go:33: disk usage [total=351 GB, used=27 GB, free=324 GB]
I 2023/05/04 10:41:20 serve.go:124: reverse proxy server [127.0.0.1:6806] is booting
E 2023/05/04 10:41:23 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 10:41:23 repository.go:1114: sync data repo failed: lock cloud repo failed
E 2023/05/04 10:46:25 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 10:46:25 repository.go:1114: sync data repo failed: lock cloud repo failed
E 2023/05/04 10:51:26 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 10:51:26 repository.go:1114: sync data repo failed: lock cloud repo failed
E 2023/05/04 10:56:30 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 10:56:30 repository.go:1114: sync data repo failed: lock cloud repo failed
E 2023/05/04 11:01:38 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 11:01:38 repository.go:1114: sync data repo failed: lock cloud repo failed
E 2023/05/04 11:06:39 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 11:06:39 repository.go:1114: sync data repo failed: lock cloud repo failed
E 2023/05/04 11:11:40 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 11:11:40 repository.go:1114: sync data repo failed: lock cloud repo failed
W 2023/05/04 11:13:01 blocktree.go:451: save block tree [size=5.4 MB] to [D:\Program Files\SiyuanDoc\SiYuan\temp\blocktree], elapsed [3.46s]
E 2023/05/04 11:13:30 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 11:13:30 repository.go:1114: sync data repo failed: lock cloud repo failed
I 2023/05/04 11:14:21 conf.go:452: exiting kernel [force=false, execInstallPkg=0]
E 2023/05/04 11:14:21 sync.go:254: failed to auto-sync too many times, delay auto-sync 64 minutes
E 2023/05/04 11:27:35 sync_lock.go:137: upload lock sync failed: cloud account auth failed
E 2023/05/04 11:27:35 repository.go:1114: sync data repo failed: lock cloud repo failed

**Comment by 88250** [comment]
请重新登录账号后再试。

这个问题已经在 https://github.com/siyuan-note/siyuan/issues/8101 中改进，感谢反馈。
