### ISSUE TITLE
文件树分屏拖动

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#817]
### 描述问题 Describe the problem
在整理文件过程中，分屏开了两个文件树，发现文件不能跨过分屏拖动

### 期待的结果 Expected result
希望文件能够跨过分屏拖动，有利于文件整理

### 截屏或录屏演示 Screenshot or screen recording presentation

![分屏拖动](https://user-images.githubusercontent.com/15924513/102961104-72113d80-451e-11eb-98d9-93588d995a6a.gif)

### 版本环境 Version environment

* 版本 Version：0.5.42
* 操作系统 Operating system：win10

**Comment by 88250** [comment]
v0.6.8 以后文件树已经不支持分屏操作 了，我关闭了，谢谢反馈。
