### ISSUE TITLE
The marketplace supports searching

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8173]

**Comment by Zuoqiu-Yingyi** [comment]
在集市 `已安装` 页签中的 `插件` 页面最好也提供如下筛选器
- `已安装`
- `已启用`
- `已禁用`

**Comment by mozhux** [comment]
建议增加一键更新。。

**Comment by Yuminis98** [comment]
同一键更新， 插件多了一个一个点更新，太麻烦了

**Comment by Yuminis98** [comment]
> 同一键更新、自动定期更新， 插件多了一个一个点更新，太麻烦了

那个每日热力图更新的好频繁，我印象中，每次打开集市，他都有更新，点了起码6，7次更新了，这一个插件

**Comment by svtardust** [comment]
> 有点恐怖啊，这一个月点5，6次了？

**Comment by svtardust** [comment]
> 
> 那个每日热力图更新的好频繁，我印象中，每次打开集市，他都有更新，点了起码5，6次更新了，这一个插件

这个月点了5，6次吗？

**Comment by LGRemdo** [comment]
集市插件过滤：未安装

**Comment by frostime** [comment]
搜索的范围是什么？只搜索插件的名称吗？

**Comment by 88250** [comment]
集市包的配置项应该都能搜索。

**Comment by 88250** [comment]
> 在集市 `已安装` 页签中的 `插件` 页面最好也提供如下筛选器
> 
> * `已安装`
> * `已启用`
> * `已禁用`
> * `可更新`

这个再缓缓吧。

**Comment by 88250** [comment]
一键更新也在缓缓……
