### ISSUE TITLE
Allow HTTP in the AI API Base URL

### ISSUE THREAD

**Issue by Airradda** [siyuan-note/siyuan#8175]
### In what scenarios do you need this feature?

I am trying to get the AI functionality running locally on my computer via [LocalAI](https://github.com/go-skynet/LocalAI). However, it isn't reachable using HTTPS and trying use the default URL (http://localhost:8080/v1/ or http://127.0.0.1:8080/v1/) for Siyuan's API Base URL fails with `openai.go:53: create chat completion failed: error, json: cannot unmarshal number into Go struct field APIError.error.code of type string`.

### Describe the optimal solution

Allow using HTTP universally or simply have exceptions for local domains or private IPs, i.e. `localhost`/`127.0.0.1`/`10.x.x.x`/`192.x.x.x` etc. 

### Other information

Thank you for making Siyuan, it has been pleasant to use even with the occasional untranslated bit or poorly worded messages.

**Comment by 88250** [comment]
Judging from the error report, it does not seem to be a problem with the HTTP protocol. It may be that the [go-openai](https://github.com/sashabaranov/go-openai) library used by SiYuan is not compatible with LocalAI.

If this is the case, it is estimated that it cannot be solved. It needs to be connected to LocalAI separately in other ways. We will see if there are people in the community to expand it. I will close the issue for now, thank you.
