### ISSUE TITLE
聚焦后自动展开

### ISSUE THREAD

**Issue by RocLoong** [siyuan-note/siyuan#8176]
### In what scenarios do you need this feature?

当我写大纲笔记的时候，为了使笔记结构看起来更加清晰，我选择把笔记都折叠起来，当我聚焦笔记后笔记还需要再次点击才展开（这显然是不方便的），通时当我返回上一级的时候还需要手动折叠。
希望做成和幕布或者logseq那样聚焦后自动展开，同时维持原有折叠的目录结构

### Describe the optimal solution

希望做成和幕布或者logseq那样**聚焦后自动展开**，同时**维持原有折叠的目录结构**

**Comment by 88250** [comment]
这个目前没有办法做到分离的折叠状态，后面有空再考虑了，见谅。

**Comment by TCOTC** [comment]
聚焦后折叠展开 #8956
