### ISSUE TITLE
Call `window.destroyTheme():Promise<void>` instead of refreshing when switching themes

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8178]
theme.js is a bad mechanism that results in a heavy coupling of theme appearance and functionality.

With the introduction of the plugin system, we should use the plugin mechanism instead of the outdated theme.js.

**Comment by Zuoqiu-Yingyi** [comment]
不建议直接停止支持, 理由如下:

1. 主题的部分逻辑功能与样式本身就是强耦合的, 例如设置背景图片, 需要同时设置多个 DOM 元素的背景颜色的透明度才可以实现
2. 目前插件系统功能还十分简单, 无法提供例如 `右键菜单`/`菜单栏按钮` 等交互控件的注册 与 `快捷键`/`数据持久化` 等必要功能的实现
3. 部分与样式低耦合的主题功能迁移到插件系统需要一定的工作量, 难以在短时间内完成

**Comment by Zuoqiu-Yingyi** [comment]
> 那我们把时间推后一些，等插件系统成熟后再考虑移除 theme.js

更好的方案是将 theme.js 也作为一个与主题相关联的、内置的插件加载👀

**Comment by 88250** [comment]
那样不能把外观和功能分开的，这个提议的目的就是为了解耦这部分。

**Comment by Zuoqiu-Yingyi** [comment]
> 那样不能把外观和功能分开的，这个提议的目的就是为了解耦这部分。

有些功能就是无法解耦的, 例如多种配色的主题切换配色文件

**Comment by 88250** [comment]
不分开的话现在主题捆绑太多功能，用户切换主题导致功能不可用很是烦恼。

**Comment by svchord** [comment]
> 一些尺寸与边距需要动态计算并调整

是这样的，我主题的顶栏就需要靠js动态计算出边距，底部状态栏也是通过js将一些按钮转移到点击弹出菜单

**Comment by Aiviokoo** [comment]
刚刚水了会儿群，看了看主题大佬们的讨论。作为一名代码小白说两句关于主题方面的吧！
突然记起了自己第一次用主题的时候，感受如下：
有一种换了一个软件的感觉（真的很惊艳），切换主题后多了很多功能，样式上面也有了很多变化，有些主题也特别精致。（这些功能都是主题作者打包好的，我只需要安装上这个主题加能体验这些打包好的功能了）
插件系统我是非常支持的，也体会到了插件的好用与灵活。
如果说插件是砖是瓦，可以搭建的很丰富，那么现在的主题可以说就是主题作者用爱发电精心搭建出的自己认为挺不错的房子。
（诚然，偶尔会有需要用到某个功能而去切换主题的：现在用插件切换主题也挺方便了）
我的想法是希望这次变革稍微无感一些：
1.让主题作者们不要因为这次变革导致主题不再能做到符合自己预期而选择不上架了
2.让现有使用主题的用户更加无感一些，不要因为突然更新了个版本，主题完全不能用了，大部分先前的立即全没了，得一个个的去找插件，去配置。（很多用思源的用户都是因为思源不用太折腾，而某个软件太折腾）
3.如果这个变革成为这样：用户下载主题，会自动匹配下载相应的插件，这些插件们会自动默认打开（插件对每个主题有特殊的适配以更适配主题），切换主题，不同的插件会打开或关闭，自动记住这个主题更改过的默认打开的插件们。插件产生冲突时，弹窗报错是哪个插件出错。
4.主题大佬们在群里提到了曾经一个大佬（张亮）很多主题下架的事，诚然，时间久了，可能主题不适配了（我觉得可以提供一个已过时主题的小角落，这里也许只给一个介绍就行），这样曾经的大佬再回来，也许看到会很有感触，从而拾起自己曾经的主题继续开发。（另外，他们曾经为思源做过贡献，也值得被记住，是作为思源发展史的一部分，完全可以给一个小角落，展示一下）
希望D大和V姐能和主题作者们商量商量怎么更合适的变革，谢谢！

**Comment by Temacc0531** [comment]
我还是支持主题和插件趁这次机会彻底解耦，长久痛苦不如短期阵痛

**Comment by Achuan-2** [comment]
如果要解耦，至少希望官方提供主题切换配色的功能，使得同一主题可以切换不同theme.css，否则直接砍掉theme.css, 会造成维护多个配色主题太过麻烦

**Comment by idea-zone** [comment]
1. 如果移除 theme.js ，希望对 theme.css 做两个方面的增加：
    *  主题内置切换多个主题配色的方式，或者提供一个这样的官方插件（社区有老哥做也行，但官方搞一个更合适一些）。
    *  支持一些简单的属性计算，有些样式 纯 css 实现很麻烦，一些辅助的计算还是很有必要的。
           * 或者说，让主题可以“捆绑”一些依赖的插件，比如有一个配置json来定义建议的插件列表，下载该主题会同时下载对应的插件列表。

**Comment by 88250** [comment]
主题依赖插件不大合理。

**Comment by Zuoqiu-Yingyi** [comment]
> 主题依赖插件不大合理。

不是依赖，是建议

**Comment by 88250** [comment]
这样不太好啊，本意就是想主题只提供外观，不涉及功能的，如果涉及功能，需要单独插件支持。

**Comment by svchord** [comment]
> 这样不太好啊，本意就是想主题只提供外观，不涉及功能的，如果涉及功能，需要单独插件支持。

但那些不涉及功能的外观js既然要从主题中迁移出来，就需要一个不割裂使用体验的方案啊，类似vscode也支持`.vscode/extensions.json`这样的文件，并且会自动提荐统一下载安装

**Comment by pureTrue** [comment]
支持D，不应该让主题绑架插件，多外观主题让主题开发者拆分发布算了

**Comment by Aiviokoo** [comment]
> 支持D，不应该让主题绑架插件，多外观主题让主题开发者拆分发布算了

感觉老铁说的好轻巧哟。减少依赖确实是好事，但怎么变革我觉得还是D大和主题开发者们多讨论讨论比较好。
据我说知，目前 集市里的主题 完全是热心老哥们开发出来免费分享给大家使用的。（虽然现在有打赏功能了，但几乎还算是为爱发电的情况）
并且维护主题应该也会消耗大量精力，我想，如果要从维护一个主题变成维护5个主题，我觉得主题开发者很有可能就只保留维护一个自己常用的了。
用户能使用的主题变向也就更少了。
（仅个人浅薄的观点）

**Comment by TCOTC** [comment]
拓展功能还是得依靠完善的插件系统才行，分而治之。想要的功能只在某个主题里面有还是太难受了。

**Comment by 88250** [comment]
又过了一段时间，大家有空的话再讨论一下吧，砍还是不砍？

**Comment by frostime** [comment]
我个人的观察是，主题对 js 的刚性需求主要体现在顶栏的开关选项上，比如不同的配色模式、开启或者关闭某些小样式的功能。去掉 theme.js 的前提是解决这些刚性需求。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/31200d26-9644-4589-af15-37773034d22b)
![image](https://github.com/siyuan-note/siyuan/assets/27268127/9e799ae6-7ef8-47ae-aaa3-42dd33fa4676)
![image](https://github.com/siyuan-note/siyuan/assets/27268127/430808ac-82e1-4726-a425-63c102bbe2e6)

**Comment by suka233** [comment]
没用过theme.js， 但是看到好像很多主题都用到theme.js， 主题市场的主题是思源很宝贵的财富， 如果直接砍了导致主题停更， 那损失也太大了。就比如说之前的集市改版，导致很多优秀的挂件下架了。。。
肯定需要更平滑的方案，至少不能过多影响主题开发者的开发体验。。

**Comment by zuoez02** [comment]
以前考虑theme.js的移除，是为了避免没人写插件都往主题里写。现在看这种情况并没有发生，大部分新东西都在插件里了，主题基本上功能也不多了，保持现状并没有什么大碍。

社区资源都挺宝贵的，先不动也没事，如果有人执意往theme.js里加料，我们再拦住也来得及

**Comment by royc01** [comment]
如果有影响到思源本体功能性的体验，趁早砍了也可以，我也断了念想，后面只能换其他方式做，能实现支持加载小样式就可以。

**Comment by zxhd863943427** [comment]
除了理论上满足了功能不能依赖主题的要求，去掉 theme.js 还有什么实质性的提升吗？如果没有的话，我还是建议保留的。毕竟这个功能说到底是为主题作者服务，在主题作者自己没有放弃使用之前，不应该砍掉它。

**Comment by WingDr** [comment]
我当初几乎重构过toy主题的theme.js（这个主题几乎包含了当时所有主题的js功能）。我感觉theme.js的功能大致可以分成四类：
1. 判断当前状态（手机/电脑/网页端）
2. 数据持久性保存和读取
3. 样式切换
4. 和渲染有关的持续性触发逻辑

其中前两点其实主要服务于第三点，也就是样式切换按钮的位置和功能，如果有更方便的接口和方法大家肯定也不愿意再写复杂的触发逻辑，慢慢地替换到theme.js的功能也可以。我的建议是先营造一个新的更好用的生态，把用的人多但是功能比较简单的主题移植到新生态里，大家就逐渐会往新生态靠拢了，之后再彻底废除theme.js也来得及。

至于第四点大可以扔到插件里（事实上目前插件里已经有很多移植过去的了）

**Comment by Achuan-2** [comment]
如果非要砍主题theme.js，希望官方至少做一个主题配色切换功能吧，支持一个主题提供多种明亮和黑暗配色，可以在theme.json配置多个配色的名称和css路径，多个配色是叠加在theme.css的基础上的，这个是我觉得目前主题js使用的最大用途，其他小功能用插件倒是都可以顶顶。出了这个之后，等大部分主题都适配这个功能之后，再慢慢砍theme.js不迟

**Comment by Vanessa219** [comment]
移除这个的目的是想在切换主题的时候不刷新页面，如果有办法限定使用场景应该是可以保留 js 的。

**Comment by WingDr** [comment]
> 移除这个的目的是想在切换主题的时候不刷新页面，如果有办法限定使用场景应该是可以保留 js 的。

这样的话就得做个和插件一样的加载和卸载机制吧，有个接口给统一注册触发器，然后在主题卸载的时候把所有触发器都统一注销掉。

**Comment by Vanessa219** [comment]
这样也可以，切换的时候不用刷新界面，还可以兼容原有 js 。

**Comment by Vanessa219** [comment]
请各位开发者在3月中旬前配合完成以下兼容性的升级：

1. 由于不刷新页面，主题切出再切入后需注意判断变量的声明
2. window.destroyTheme 中主要用于移除自己加载的 js，css；添加的 dom；还原修改的 dom 等。不要影响下一个主题即可。参考如下：
```
window.destroyTheme = () => {
    document.querySelector("#theme-color-style").remove();
}
```
幸苦各位了，十分感谢 🙏

**Comment by frostime** [comment]
> 请各位开发者在3月中旬前配合完成以下兼容性的升级：
> 
> 1. 由于不刷新页面，主题切出再切入后需注意判断变量的声明
> 2. window.destroyTheme 中主要用于移除自己加载的 js，css；添加的 dom；还原修改的 dom 等。不要影响下一个主题即可。参考如下：
> 
> ```
> window.destroyTheme = () => {
>     document.querySelector("#theme-color-style").remove();
> }
> ```
> 
> 幸苦各位了，十分感谢 🙏

是否有必要更新一下 theme-sample 的文档, 对这个问题进行说明？或者直接为样例添加 theme.js 样例？

**Comment by Vanessa219** [comment]
theme-sample 文档指的是？

**Comment by frostime** [comment]
> theme-sample 文档指的是？

主题的样例啊

**Comment by Vanessa219** [comment]
OK

**Comment by Temacc0531** [comment]
> 请各位开发者在3月中旬前配合完成以下兼容性的升级：
> 
> 1. 由于不刷新页面，主题切出再切入后需注意判断变量的声明
> 2. window.destroyTheme 中主要用于移除自己加载的 js，css；添加的 dom；还原修改的 dom 等。不要影响下一个主题即可。参考如下：
> 
> ```
> window.destroyTheme = () => {
>     document.querySelector("#theme-color-style").remove();
> }
> ```
> 
> 幸苦各位了，十分感谢 🙏

@Vanessa219 发现个错别字【辛苦】，更新日志里面也错了👀

**Comment by 88250** [comment]
感谢指正。



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 31, 2024 09:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Call `window.destroyTheme():Promise<void&gt;`instead of refreshing when switching themes (Issue #8178)




  
请各位开发者在3月中旬前配合完成以下兼容性的升级：
  
由于不刷新页面，主题切出再切入后需注意判断变量的声明
 
window.destroyTheme 中主要用于移除自己加载的 js，css；添加的 dom；还原修改的 dom 等。不要影响下一个主题即可。参考如下：
  window.destroyTheme = () =&gt; {     document.querySelector("#theme-color-style").remove(); }  
幸苦各位了，十分感谢 🙏
  
@Vanessa219 发现个错别字【辛苦】，更新日志里面也错了👀

**Comment by UFDXD** [comment]
希望不刷新开窗口的主题js和样式也一能起切换，我现在还在v2.8.9版本希望这个机制完善后让我顺利升级兼容新版本主题回坑。

**Comment by 88250** [comment]
@UFDXD 麻烦跟进 dev 版本看看，如果还需要改动欢迎反馈。

**Comment by Vanessa219** [comment]
这个主题名称发我试一下。谢谢。

**Comment by idea-zone** [comment]
> > 请各位开发者在3月中旬前配合完成以下兼容性的升级：
> > 
> > 1. 由于不刷新页面，主题切出再切入后需注意判断变量的声明
> > 2. window.destroyTheme 中主要用于移除自己加载的 js，css；添加的 dom；还原修改的 dom 等。不要影响下一个主题即可。参考如下：
> > 
> > ```
> > window.destroyTheme = () => {
> >     document.querySelector("#theme-color-style").remove();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 幸苦各位了，十分感谢 🙏
> 
> @Vanessa219 发现个错别字【辛苦】，更新日志里面也错了👀

mini-vlook 主题:  js 和 css 已经添加了destroyTheme 的实现。  对于需要移除的 Dom 包括这种吗？
![image](https://github.com/siyuan-note/siyuan/assets/53116704/83efbeaa-96f1-4f90-8f16-53d3c3dea24c)

**Comment by Vanessa219** [comment]
@idea-zone 是的，否则和其他主题不搭配，或者会报错。
