### ISSUE TITLE
调整窗口大小后能保证面板的高度比例

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8179]
### In what scenarios do you need this feature?

像是大纲和文档树在一侧同时显示时，假设最大化时是一比一的比例，恢复原窗口大小后似乎就会保证大纲或文档树的高度，另一个会缩短，这个可以变成根据比例调整吗？就是恢复窗口后上下还是一比一
![FPE4AhxSfo](https://user-images.githubusercontent.com/125173405/236459987-af798cc7-dc7d-4569-bbd6-664f88ae6544.gif)

### Describe the optimal solution

希望根据比例调整

**Comment by chenshinshi** [comment]
默认主题可以复现

**Comment by Vanessa219** [comment]
没有拖动过的情况下是1:1，如果拖动了就会记录高度，保持底部不变，上面自适应。
