### ISSUE TITLE
未来是否有支持第三方插件的计划？

### ISSUE THREAD

**Issue by jiangqizheng** [siyuan-note/siyuan#818]
个人有一些需求，可能需要进行略微的定制化。
比如希望能便捷的统计内容块被实际使用的频次，来分析笔记的实际利用率，便于整理笔记。

**Comment by 88250** [comment]
你好，请关注 [API](https://github.com/siyuan-note/siyuan/issues/213)，欢迎到该提议下跟帖，我们会逐步完成，谢谢。
