### ISSUE TITLE
手机端开网络伺服，在电脑浏览器打开pdf用矩形标注粘贴无法粘贴图片

### ISSUE THREAD

**Issue by xylyp** [siyuan-note/siyuan#8182]
### In what scenarios do you need this feature?

手机端开网络伺服，在电脑浏览器打开pdf用矩形标注粘贴无法粘贴图片，在电脑端软件可以打开pdf用矩形标注粘贴可以粘贴图片，求解决方法，谢谢

### Describe the optimal solution

手机端开网络伺服，在电脑浏览器打开pdf用矩形标注粘贴无法粘贴图片，在电脑端软件可以打开pdf用矩形标注粘贴可以粘贴图片，求解决方法，谢谢

**Comment by 88250** [comment]
你可以试下电脑端伺服后浏览器上使用是否能粘贴，如果不能的话多半是浏览器禁用了粘贴权限吧。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
