### ISSUE TITLE
有考虑增加目录加密和单个文章加密功能吗

### ISSUE THREAD

**Issue by G-Akiraka** [siyuan-note/siyuan#8185]
### In what scenarios do you need this feature?

比如我有个目录，不想让别人看到，点开来必须输入密码才可以查看该目录下内容，然后该目录下内容文档也可以设置这篇文档密码，必须输入密码才可以浏览到

### Describe the optimal solution

增加目录与文档加密

**Comment by 88250** [comment]
在界面上目前已经有一个启动时的访问鉴权，建议用这个。

文件系统上是明文存储的，不考虑加密了，感谢反馈。

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/9800
