### ISSUE TITLE
Access to the OpenAI API is no longer supported on Huawei devices

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8192]
![X5G4O3NQBW`VVN@GUIL_{4X](https://user-images.githubusercontent.com/873584/236653138-aabd620b-3873-47d4-b7c8-d479491c137b.png)

**Comment by EJianZQ** [comment]
逆天的华为

**Comment by W-Mai** [comment]
8192 多么美妙的issue号😁
