### ISSUE TITLE
docker版本能否加入UID和GID变量,因为群辉NAS没有U=1000:1000用户,造成部署的话映射目录只能给"Everyone"权限,但是这样很不安全.

### ISSUE THREAD

**Issue by loveu5522** [siyuan-note/siyuan#8194]
### In what scenarios do you need this feature?

群辉NAS上,docker版本

### Describe the optimal solution

docker版本加入UID和GID的变量,可以自定义用户UID,或者使用root权限运行也行吧.

**Comment by 88250** [comment]
建议试下 fork 仓库以后自行构建镜像，社区里面好像有其他人做好类似的解决方案可以参考一下，这里就不变更了，感谢反馈。

**Comment by xuw2024** [comment]
> 建议试下 fork 仓库以后自行构建镜像，社区里面好像有其他人做好类似的解决方案可以参考一下，这里就不变更了，感谢反馈。

虽然可以自行构建镜像，但大多数不会长期同步更新。商业nas有非常多的普通用户，因为思源docker不能部署，放弃使用思源

**Comment by loveu5522** [comment]
> > 建议试下 fork 仓库以后自行构建镜像，社区里面好像有其他人做好类似的解决方案可以参考一下，这里就不变更了，感谢反馈。
> 
> 虽然可以自行构建镜像，但大多数不会长期同步更新。商业nas有非常多的普通用户，因为思源docker不能部署，放弃使用思源

可以部署呀，我就一直用的呀，文件夹给"Everyone"权限就好

**Comment by loveu5522** [comment]
> 建议试下 fork 仓库以后自行构建镜像，社区里面好像有其他人做好类似的解决方案可以参考一下，这里就不变更了，感谢反馈。

还望您考虑一下添加一下呢，自行构建实在太麻烦，看您这边更新也挺频繁的，NAS用这个的也比较多的。☹☹☹☹☹☹☹
