### ISSUE TITLE
思源无法正确获取修改后的Documents路径

### ISSUE THREAD

**Issue by AidanYang0618** [siyuan-note/siyuan#8195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

假如修改了用户的Documents路径，每次启动思源，都会在用户目录 `%USERPROFILE%` 下创建Documents文件夹

推测思源获取当前Windows用户的Documents路径是通过类似于 `%USERPROFILE%\Documents` 的方式获取

### Expected result

通过Windows的环境变量获取当前Windows用户的Document路径

### Version environment

```markdown
- Version: 2.8.5
- Operating System: Windows 10
- Browser (if used):
```

### Log file

无

### More information

在PowerShell中，可以通过如下指令来直接获取当前用户的Documents目录

```
[Environment]::GetFolderPath('MyDocuments')
```

**Comment by 88250** [comment]
请参考 https://github.com/siyuan-note/siyuan/issues/5622
