### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://user-images.githubusercontent.com/32903588/236715983-fcaed350-67da-4d94-a19f-0bfc3b6bef46.png)

### Expected result

修复改进

### Version environment

```markdown
- Version: 2.8.7-dev2
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11417061/siyuan.log)

**Comment by terwer** [comment]
+1

环境：MacOS 13.3.1 (a) (22E772610a)

![image](https://user-images.githubusercontent.com/3259282/236716767-43dd4e41-37ca-4122-92a1-c990e8e87b11.png)

**Comment by 88250** [comment]
稍后发布 dev3 解决，感谢反馈。
