### ISSUE TITLE
放大镜浏览功能

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#82]
![9RZB%ECD2$6(1EISX2VMP28](https://user-images.githubusercontent.com/873584/94015118-044e5c00-fddf-11ea-8e53-1bf51b643f0f.png)

![ZA)IKPIFB`JNH FY8Y{38%3](https://user-images.githubusercontent.com/873584/94015262-365fbe00-fddf-11ea-8355-00716fe15a4d.png)

* 查看批注
* 查看标签

**Comment by 88250** [comment]
暂时不考虑了，后面有需要再打开。
