### ISSUE TITLE
文本内容自动补全

### ISSUE THREAD

**Issue by Tokubara** [siyuan-note/siyuan#820]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

单词太长不想打, vim有快捷键ctrl+P补全已经出现过的单词. 仅限于英语, 中文有分词的问题.

### 描述最优的解决方案 Describe the optimal solution

加个快捷键.

**Comment by 88250** [comment]
放到后期一点考虑，谢谢。

**Comment by 88250** [comment]
暂时不引入了，因为输入侧还是依靠输入法完成吧，谢谢。

**Comment by Tokubara** [comment]
我也同意这一点, 我有个想法, 如果真的有类似需求, 就在vscode写. 我发现vscode在写列表的时候也更有优势.
