### ISSUE TITLE
下载新主题不能使用，挂件不能更新

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://user-images.githubusercontent.com/87182333/236722535-180ff17b-880d-459f-81fb-eefee23bafc6.mp4

见录屏

### Expected result

希望改进

### Version environment

```markdown
- Version: 2.8.7 dev3
- Operating System: 
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11417288/system-log.zip)

**Comment by 88250** [comment]
感谢反馈，dev4 修复。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/commit/397683d567411dca180fe54ff39a30fdccbb1949
