### ISSUE TITLE
Optimize donation icon

### ISSUE THREAD

**Issue by mozhux** [siyuan-note/siyuan#8201]
### In what scenarios do you need this feature?

![CY 5PU22VF1I7%RS00} Q_tmb](https://user-images.githubusercontent.com/46953371/236731799-25691c96-84af-4df7-9820-90d21277f202.jpg)
This comment icon cannot express the meaning of donation

### Describe the optimal solution

Suggest changing to coffee icon for more versatility
![image](https://user-images.githubusercontent.com/46953371/236731922-98005c03-e66b-4f59-a622-f9ceee0e12a5.png)

**Comment by 88250** [comment]
默认应该是这个：

![image](https://user-images.githubusercontent.com/873584/236732661-0d591b3e-bfab-49b0-83f4-61c3d503b2c2.png)

**Comment by mozhux** [comment]
> 默认应该是这个：
> 
> ![image](https://user-images.githubusercontent.com/873584/236732661-0d591b3e-bfab-49b0-83f4-61c3d503b2c2.png)

那应该是用了图标包的关系，但这个图标在思源里和反馈是一个，也不合理呀，希望能独立一个，喝咖啡是全球通用的把

**Comment by mozhux** [comment]
因为反馈图标为了词更达意，都改成了类似这样的图标
![Uploading image.png…]()

**Comment by Vanessa219** [comment]
这个可能只会修改反馈的图标了，捐赠走粉色的爱心。

**Comment by mozhux** [comment]
> 这个可能只会修改反馈的图标了，捐赠走粉色的爱心。

也行，改了反馈的图标，相当于也是分开了。
