### ISSUE TITLE
Show count in spaced repetition tree filter floating window

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#8202]
### In what scenarios do you need this feature?

1. Provide the function to check the number of cards to be learned and reviewed under the deck, I want to see how many cards need to be memorized and reviewed.
2. Individual decks can be set with different daily learning and review amounts, and it seems that only all of them can be set at present.
3. The second piece of advice is less thoughtful and should require a more detailed solution, after all, there is a difference between decks and document trees. I'll just make a small suggestion.
![image](https://user-images.githubusercontent.com/112467275/236732852-a4c481c4-47a5-4197-8473-bbe783b9781a.png)
![image](https://user-images.githubusercontent.com/112467275/236732890-9aa19075-6c9f-40ae-a184-65aa88e80ee7.png)

1. 提供查看牌组下待学习和待复习卡片数目的功能，我想看看到底有多少卡片需要背诵和复习。
2. 单个牌组可设置不同的每日学习和复习量，目前是貌似只能设置全部的。
3. 第二条建议考虑不太周到，应该需要更详细的解决方案，毕竟牌组和文档树还是有区别的。我就在此提个小小建议。
![image](https://user-images.githubusercontent.com/112467275/236732852-a4c481c4-47a5-4197-8473-bbe783b9781a.png)
![image](https://user-images.githubusercontent.com/112467275/236732890-9aa19075-6c9f-40ae-a184-65aa88e80ee7.png)

### Describe the optimal solution

![image](https://user-images.githubusercontent.com/112467275/236732852-a4c481c4-47a5-4197-8473-bbe783b9781a.png)
![image](https://user-images.githubusercontent.com/112467275/236732890-9aa19075-6c9f-40ae-a184-65aa88e80ee7.png)

### Describe the candidate solution

未知

**Comment by Aiviokoo** [comment]
希望D大和V姐可以在闪卡文档树给出此提示，另闪卡文档树也在分页显示即可，提示如下：
![image](https://user-images.githubusercontent.com/87182333/236736064-582b5e0d-4dbc-4f19-8f09-de6afed9e108.png)
![image](https://user-images.githubusercontent.com/87182333/236736212-9bde3439-a06c-4897-b919-4cde8c4acd98.png)
@88250 @Vanessa219 
待复习卡片数字能显示更好，主要是有时候点进一个笔记本发现没有待复习的卡片比较影响体验。

**Comment by 88250** [comment]
大概明白了，选择文档树这个界面还是弹层吧。

**Comment by Aiviokoo** [comment]
> @Aiviokoo这里我没有理解：
> 
> ![图片](https://user-images.githubusercontent.com/873584/236754906-cc474946-8aa5-4836-8bb9-c276cce65ade.png)



> > @Aiviokoo这里我没有理解：
> > ![图像](https://user-images.githubusercontent.com/873584/236754906-cc474946-8aa5-4836-8bb9-c276cce65ade.png)
> 
> ![SODHLE%%W`}Y%QZ3_G8SQTG](https://user-images.githubusercontent.com/67812425/236762353-9f3a45f6-b7a1-49e9-b464-b1a12b241e51.png) 我认为类似于这种想法
![image](https://user-images.githubusercontent.com/87182333/236806323-6423471e-abfd-4b9e-9bee-d4d3fe4f2204.png)
![image](https://user-images.githubusercontent.com/87182333/236806572-d493bc76-97c3-42c2-807b-6aae9ba13cb0.png)
是这样的，是我之前表述的有点抽象了，抱歉。
图上这两个属于锦上添花的功能。
迫切需要的是上面最初评论的那个加数字的功能（至少是能区分有没有待复习的卡，点进去才发现没有很不优雅）

**Comment by 88250** [comment]
阶段性记录一下：

* 选择路径还是使用弹层
* 选择路径中应该可以加上新卡/复习卡数量，有待技术评估
* 细化到文档树的新卡/复习卡限制目前不考虑

**Comment by 88250** [comment]
考虑显示如下计数：

* 新卡数
* 到期卡数
* 总卡数
