### ISSUE TITLE
最新版本不能设置块备注，提示Memo无效

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![Quicker_aqOnJqEZdk](https://user-images.githubusercontent.com/125173405/236735600-680a23d2-6e21-4df6-bb70-470728fcda68.gif)
默认主题可以复现

### Expected result

修复

### Version environment

```markdown
- Version: 2.8.7 dev3
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
感谢反馈，在 https://github.com/siyuan-note/siyuan/pull/8204 中修复。
