### ISSUE TITLE
emoji设置为twitter emoji时，导出图片会很卡

### ISSUE THREAD

**Issue by WACrown** [siyuan-note/siyuan#8205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当我把“文档图标使用系统原生 Emoji”这个配置选项取消掉时（使用twitter emoji时），导出文档为图片的时候，编辑器会卡死10-20秒，cpu占用到15%，内存增长2G左右。

### Expected result

解决这个bug

### Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/48990489/236762293-e98e84e4-f714-4046-8487-f890eb0b0dfc.png)
![image](https://user-images.githubusercontent.com/48990489/236762370-a88343b6-3990-4726-88f9-8c6657b94477.png)
![image](https://user-images.githubusercontent.com/48990489/236762419-36557a91-15de-43bf-bcf2-3a9290e4e63e.png)
![image](https://user-images.githubusercontent.com/48990489/236762482-ad6a1388-1cb9-4145-9de1-95a8bd9fb233.png)

### Version environment

```markdown
- Version: 2.8.6
- Operating System: windows10
- Browser (if used): 桌面端
```

### Log file

无

**Comment by 88250** [comment]
按照这个步骤重现不了问题哦。

**Comment by XinLi0111** [comment]
2.8.6 可重现。上次在 #7627 后已经更换过全新的工作空间

**Comment by WACrown** [comment]
![image](https://user-images.githubusercontent.com/48990489/236780137-8d0aaee7-4d5e-4850-be97-ee1c0bc97863.png)
全新的工作空间，仍然会出现这个问题，只修改了设置中的“文档图标使用系统原生 Emoji”

**Comment by 88250** [comment]
感觉这个问题难以定位了；后面我们有计划移除 Twitter Emoji 支持 https://github.com/siyuan-note/siyuan/issues/8206

**Comment by 88250** [comment]
这个 issue 我们先关闭了，如果还有发现其他导出图片的问题请继续跟帖，谢谢。
