### ISSUE TITLE
There is no option to withdraw after learning the last flash-学完最后一张闪卡后没有撤回选项

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#8207]
### In what scenarios do you need this feature?

There is no option to withdraw after learning the last flash.
学完最后一张闪卡后没有撤回选项。

### Describe the optimal solution

After learning the last flashcard, there is an option to withdraw.
学完最后一张闪卡后有撤回选项。

**Comment by 88250** [comment]
是的，最后这张卡评分后无法撤回，主要是考虑到支持撤回的话最后会多一个交互步骤，这个步骤大部分时间对于用户来说是无效的，多一次确认复习完成不太顺畅。

暂时先维持现有设计，后面如果反馈这个点的用户较多我们再考虑改变，谢谢。
