### ISSUE TITLE
Cards with an empty first field cannot be issued.删除首行为空的空白行闪卡

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#8208]
### In what scenarios do you need this feature?

Cards with an empty first field cannot be issued.
删除首行为空的空白行闪卡
Or paragraphs with empty first fields cannot be carded.
或者说首字段为空的段落不能制卡。
![image](https://user-images.githubusercontent.com/112467275/236804126-06a0124f-3214-4af0-9db3-ebd82a08776b.png)

### Describe the optimal solution

Cards with an empty first field cannot be issued.
删除首行为空的空白行闪卡
Or paragraphs with empty first fields cannot be carded.
或者说首字段为空的段落不能制卡。

**Comment by 88250** [comment]
这个不做强制规定吧，因为内容块是可以修改的，制卡前后都可以为空。

**Comment by 88250** [comment]
制卡前手动跳过一下吧，可以不用 Ctrl+A，而用 Ctrl+Click 多选块。

**Comment by 88250** [comment]
Ctrl+A 以后 Ctrl+Click 反向选择空段落
