### ISSUE TITLE
The flashcard learning interface provides the option to delete individual flashcards 闪卡学习界面提供删除单个闪卡的选项

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#8209]
### In what scenarios do you need this feature?

This should be called canceling the card issuance, that is, not deleting the document content, only canceling the card issuance.
At present, only the entire document tree can be deleted, just now in order to delete a blank card, I accidentally deleted the entire document tree, fortunately restored.
![image](https://user-images.githubusercontent.com/112467275/236807755-6c034fd5-45c8-4082-a3d1-5a21bca06d22.png)

---

这应该叫取消制卡，即不删除文档内容，只取消制卡。
目前只能删掉整个文档树，刚才我为了删某一个空白卡，把整个文档树不小心删除了，还好恢复了。
![image](https://user-images.githubusercontent.com/112467275/236807755-6c034fd5-45c8-4082-a3d1-5a21bca06d22.png)

### Describe the optimal solution

The flashcard learning interface provides the option to delete individual flashcards.
闪卡学习界面提供删除单个闪卡的选项。

**Comment by 88250** [comment]
间隔重复界面（复习界面）不支持管理操作，删除闪卡需要在管理入口中进入删除。

**Comment by zxhd863943427** [comment]
从块标里再次点击快速制卡就能取消制卡了。
