### ISSUE TITLE
搜索结果中的列表块和列表项整合

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#821]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

引用和搜索时，类似的问题在 https://github.com/siyuan-note/siyuan/issues/798 提出

### 描述最优的解决方案 Describe the optimal solution

目前的问题是同时显示列表块和列表项显得很混乱，但是为了引用的需要不能隐藏他们任何一者。
![image](https://user-images.githubusercontent.com/16791452/103056703-9d586300-45d8-11eb-8b9f-4300b07cc833.png)
如图，明明下面的列表项从属于上面的列表块，但不仔细看看不出从属关系

### 描述候选解决方案 Describe the candidate solution

搜索结果排序时将列表项中的结果整合到列表块中，采用缩进或允许折叠的方式展示他们的从属关系

**Comment by deerainw** [comment]
在楼主贴的图中，“此外，由于堆叠效应，复杂门的静态功耗也会减小。” 这句话在「提及」里实际上重复出现了 3 次

**Comment by frankli998** [comment]
@deerainw 这是正常的，因为列表项块包含了列表项，列表项里面又包含了段落块。引用这三个会有不同效果，因此需要重复出现三次才能让我选择具体引用哪个。现在的问题是搜索结果没有体现包含关系显得很混乱。
![image](https://user-images.githubusercontent.com/16791452/103077441-ba0d8e80-460a-11eb-8ad5-e352c5b4c446.png)

**Comment by 88250** [comment]
* 全局搜索和块引搜索已在 https://github.com/siyuan-note/siyuan/issues/883 完成
* 反链简化请关注 https://github.com/siyuan-note/siyuan/issues/874
