### ISSUE TITLE
Requirement: Siyuan replaces zotero

### ISSUE THREAD

**Issue by zhang-hao-me** [siyuan-note/siyuan#8210]
### In what scenarios do you need this feature?

# reason
Zotero is a very popular open source literature management software, but the notes made on zotero are divided, which is very inconvenient for note organization.
# Advantages and disadvantages of zotero
## Advantages
1. It is very convenient to sort out the documents. Generally, you only need to drag the documents into the software to automatically identify the relevant data of the documents;
2. With the help of zotfile, it is very convenient to put the literature and books into the corresponding folder. The following picture is the corresponding folder, all of which are automatically created by the plug-in, which is very convenient.
![image](https://user-images.githubusercontent.com/83968146/236815259-547d1bbb-2e01-4669-876a-b7ab12199ba9.png)
![image1](https://user-images.githubusercontent.com/83968146/236815264-17fa7a59-8588-43f6-997a-6e0d13ca13c3.png)
## Disadvantages
1. The link between documents and documents is not very convenient (although it can be linked);
2. It is not very convenient to associate notes with notes.
# The direction of Siyuan
The advantages and disadvantages of zotero mentioned above are actually where Siyuan complement each other.
1. At present, Siyuan cannot identify any information in the document, nor can it be identified with the help of plug-ins, but this should be relatively easy to solve through plug-ins;
2. The folder corresponding to the literature, currently all pdf files are in the same folder, and the management of files is not as convenient as shown in the screenshot above;
3. The double chain of Siyuan can easily associate documents, notes, and the relationship between document information. This is what I think is the advantage of Siyuan Notes in document management.
# Requirement
The direction mentioned above is the requirement. At present, these two requirements should be solved through plug-ins.

### Describe the optimal solution

# The direction of Siyuan
The advantages and disadvantages of zotero mentioned above are actually where Siyuan complement each other.
1. At present, Siyuan cannot identify any information in the document, nor can it be identified with the help of plug-ins, but this should be relatively easy to solve through plug-ins;
2. The folder corresponding to the literature, currently all pdf files are in the same folder, and the management of files is not as convenient as shown in the screenshot above;
3. The double chain of Siyuan can easily associate documents, notes, and the relationship between document information. This is what I think is the advantage of Siyuan Notes in document management.
# Requirement
The direction mentioned above is the requirement. At present, these two requirements should be solved through plug-ins.

**Comment by 88250** [comment]
Thanks for the suggestion, we don't consider supporting it at the moment, and wait for the plugin system to go online to see if it can be extended through plug-ins.
