### ISSUE TITLE
Use double click to pin a newly opened tab

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8211]
使用 `Ctrl+S` 固定新打开的页签

### In what scenarios do you need this feature?

当设置「在当前页签打开」为 true 的时候，如果想要固定当前的页签使其不被新打开的页签替换，就必须要修改页签的内容。

![image](https://user-images.githubusercontent.com/27268127/236871171-223ef7d1-6fd4-4980-b3e0-d1ec47c3a986.png)

但是如果有些页签，我只是单纯想要放在那里看而没有打算写，就不得不随便编辑一下然后再删掉更改，这个交互很麻烦。

### Describe the optimal solution

我认为可以仿照 vscode 的设计逻辑。

vscode 也存在类似思源的设计，一个新打开的文件如果没有编辑，则再次点击另一个文件的时候就会替换这个页签。

![image](https://user-images.githubusercontent.com/27268127/236872313-a5de1978-f2e8-449e-84cd-941a7787f8b0.png)

但是在 vscode 中，如果我在当前页签按下了「Ctrl + S」 快捷键，就可以在没有编辑的情况下直接固定当前页签，我觉得这个设计可以参考一下。

**Comment by 88250** [comment]
可以考虑同时加入双击固定。

**Comment by Zuoqiu-Yingyi** [comment]
> 但是在 vscode 中，如果我在当前页签按下了「Ctrl + S」 快捷键，就可以在没有编辑的情况下直接固定当前页签，我觉得这个设计可以参考一下。

vscode 中 Ctrl + S 是保存文件的快捷键，保存后被认为该文件已被编辑，因此将该页签持久打开了

思源中 Ctrl + S 不是保存，建议不使用该按键组合作为快捷键

**Comment by 88250** [comment]
那估计还是双击固定比较适合，Jetbrains IDE 是这么设计的。

**Comment by frostime** [comment]
此功能早已实现，关闭 issue。
