### ISSUE TITLE
The shortcut keys are invalid after the spaced repetition is tabbed

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://user-images.githubusercontent.com/87182333/236993521-b969b7c5-a31a-4ba9-925d-d2193bf7c1a2.png)

### Expected result

希望改进

### Version environment

```markdown
- Version: v2.8.7 dev5
- Operating System: win
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11427183/system-log.zip)

**Comment by 88250** [comment]
你指的快捷键是？

**Comment by Aiviokoo** [comment]
> 你指的快捷键是？

分页后的闪卡复习界面不能使用1/2/3/4和空格，还有j/k/l/；这些闪卡复习的快捷键
