### ISSUE TITLE
PDF阅读支持更多字体

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8215]
### In what scenarios do you need this feature?

思源/BookxNote/Zotero/Edge：
![image](https://user-images.githubusercontent.com/125173405/236995299-5e5bb57b-424d-427d-b398-ce1692dc4a53.png)
Sumutra PDF：
![image](https://user-images.githubusercontent.com/125173405/236995367-543dfe91-043f-4fdd-b331-b30048ab0c74.png)
显然只有SumutraPDF解析成功了，知网到底用了什么偏门中文字体。

### Describe the optimal solution

希望能支持解析更多中文字体。

**Comment by 88250** [comment]
麻烦在浏览器上试一下能否支持。

**Comment by 88250** [comment]
这个估计不行了，我试了该 PDF 文件在浏览器和 Adobe Reader 中都无法加载字体，使用的是默认字体：

![image](https://github.com/siyuan-note/siyuan/assets/873584/abd91ce8-e6e7-4270-93a6-69932703a59d)

![image](https://github.com/siyuan-note/siyuan/assets/873584/decc97e3-7e0a-477b-8cba-68c98a0aa943)

估计我们也只能这样了，感谢反馈。
