### ISSUE TITLE
When multiple windows exist, each window should be isolated using the `Optimize Typesetting`

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#8216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 打开 A 文件移动到新窗口
2. 主窗口再打开 B 文件
3. 这时同时显示 A、B 两个文件
4. 对 A 文件使用优化排版功能，B 文件窗口会同时出现优化排版遮罩，实际未生效
5. 反之，对 B 文件使用优化排版功能，A 文件窗口会同时出现优化排版遮罩，实际未生效

综上，现多窗口存在使用优化排版功能所有窗口都会出现遮罩，会给用户一种所有文件都被优化了的错觉

### Expected result

多窗口存在时使用优化排版功能应互不影响，遮罩仅出现在实际被优化的文件窗口

### Version environment

```markdown
- Version: v2.8.6
- Operating System: Windows 10
```

### Log file

无

**Comment by Vanessa219** [comment]
6c1908ddf7cdf2d271e28c2209b47b00974f9c95
