### ISSUE TITLE
Improve marketplace UI

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8219]
集市UI捐赠链接过长导致界面跳动，且出现滚动条

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/32903588/80c5994a-f365-4d36-8891-b52f26060e6c

### Expected result

显示效果不太好，可能需要优化一下

### Version environment

```markdown
- Version: 2.8.7
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by mozhux** [comment]
我喜欢对于新用户更应该强调记住初始化的密码，弱化密钥的概念

**Comment by 88250** [comment]
> 我希望对于新用户更应该强调记住初始化的密码，弱化密钥的概念

https://github.com/siyuan-note/siyuan/issues/8220 这个的反馈？

**Comment by mozhux** [comment]
> > 我希望对于新用户更应该强调记住初始化的密码，弱化密钥的概念
> 
> #8220 这个的反馈？

是的，奇怪，怎么串了。。

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 `2.8.8-dev2` 中集市卡片还有一些问题
1. 存在描述信息 `.b3-card__desc` 的卡片高度会被拉伸, 导致图标在竖直方向不居中(例如下图上侧那张卡片)  
   ![image](https://github.com/siyuan-note/siyuan/assets/49649786/442c19d6-b7d0-4dc7-a8dd-4ecf4d51103b)
2. 当前激活得主题对应的卡片颜色高亮导致图标在水平方向也不居中(如下图所示)  
   ![image](https://github.com/siyuan-note/siyuan/assets/49649786/ef64353f-47f4-4611-bd44-2b9cf7875e6f)

**Comment by Vanessa219** [comment]
多谢，第一个最大是预留了3行的位置，都会被拉伸，第二个马上改。
