### ISSUE TITLE
编写块引用时联想反馈缓慢

### ISSUE THREAD

**Issue by MistRay** [siyuan-note/siyuan#822]
### 描述问题 Describe the problem

块引用联想卡顿,联想结果要很久之后才显示.(大概要等20多秒)

### 截屏或录屏演示 Screenshot or screen recording presentation
![录屏](https://user-images.githubusercontent.com/34370155/103066840-a2c3a680-45f4-11eb-8971-648cc58c98ef.gif)

### 版本环境 Version environment

* 版本 Version：0.5.42
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
请问同样的关键字，在全局搜索里卡么？

**Comment by MistRay** [comment]
> 请问同样的关键字，在全局搜索里卡么？

也卡,要等和上面差不多长的时间

**Comment by MistRay** [comment]
我用win10和macOS的症状是一样的,联想都要等很久.应该不是平台的原因.

**Comment by 88250** [comment]
嗯，应该是因为文档比较多导致的性能问题，大概有多少文档呢？

**Comment by MistRay** [comment]
并没有很多,只有不到100篇...

**Comment by MistRay** [comment]
我找到问题了,有个非常大的块引用,删掉就好了
![image](https://user-images.githubusercontent.com/34370155/103086852-a79e4f80-4620-11eb-9b0e-f1a62262234f.png)
