### ISSUE TITLE
Improve initialization data sync interaction

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8220]
强化新用户初始化密钥后的重要性提醒

### In what scenarios do you need this feature?

根据观察，存在大量用户初始化了同步密钥后，没有注意妥善保存密钥导致不良后果。
社区内部也有用户反馈，认为软件「对密钥的重要性的提醒还**不够强**」。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/b9704e8f-f05b-46e4-928e-94e11f9fd95a)

### Describe the optimal solution

- 提案一：优化生成密钥后的提示界面，仿照 github 的思路，要求用户输入特定的文字，例如「我已知晓同步密钥的重要性，会妥善保管备份」。如果嫌弃输入太麻烦，也可以提供复制按钮，总之就是要强化提醒。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/58804c2a-37f6-4f48-a96f-4d9a0218270f)

类似这样，通过输入强化用户对重要性的知觉：

![](https://github.com/siyuan-note/siyuan/assets/27268127/cc2d4284-b5c0-4798-9026-7d6705c43a7a)

- 提案二：生成密钥后，自动下载一个 txt 文件到本地，内容为思源的密钥，标题为「思源同步密钥，请妥善保管.txt」

**Comment by 88250** [comment]
第二种方案可能更好些，下载密钥文件妥善保管。

**Comment by zxhd863943427** [comment]
我认为可以两个一起来:)

**Comment by 88250** [comment]
两个一起来吧：

1. 无论使用何种方式生成密钥，在生成前都弹框让用户确认已经知晓密钥的重要性
2. 生成密钥以后跳转到浏览器下载密钥文本文件

**Comment by 88250** [comment]
考虑了一下，在主界面顶栏同步按钮的入口应该是初始化密钥的主要入口，这里只引导用户使用密码短语生成密钥的方式，所以实际上我们只需要强调密码的重要性即可：

* 红字文案强调多设备密码一致
* 再加入一个密码确认输入框
* 在确认初始化的对话框中告诉用户可以到 设置 - 关于 - 数据仓库密钥 中备份密钥字符串

这样通过这个入口进来的用户（主要是新用户）只要牢记这个密码即可，比引入更多密钥概念和导出密钥文件负担更小，更利于用户配置。

对于在 设置 - 关于 - 数据仓库密钥 这个入口初始化密钥的用户而言，能找到这里的配置我们可以假设用户基本也清楚密钥的重要性了，旁边也有足够的说明文字进行介绍，标红这里的部分文案以强调提醒 `所有设备必须使用相同的密钥，如果密钥不一致则无法云端同步数据`。

以上考虑的出发点是减少用户初次配置同步的压力，强调密码短语的重要性，同时也会引导用户手动复制密钥字符串来备份密钥，这样的流程我认为已经足够了。如果初始化同步时着重引导备份密钥，用户可能会感到困惑，到底是密钥重要还是密码重要，它们之前有什么区别等等问题。

**Comment by mozhux** [comment]
> 考虑了一下，在主界面顶栏同步按钮的入口应该是初始化密钥的主要入口，这里只引导用户使用密码短语生成密钥的方式，所以实际上我们只需要强调密码的重要性即可：
> 
> * 红字文案强调多设备密码一致
> * 再加入一个密码确认输入框
> * 在确认初始化的对话框中告诉用户可以到 设置 - 关于 - 数据仓库密钥 中备份密钥字符串
> 
> 这样通过这个入口进来的用户（主要是新用户）只要牢记这个密码即可，比引入更多密钥概念和导出密钥文件负担更小，更利于用户配置。
> 
> 对于在 设置 - 关于 - 数据仓库密钥 这个入口初始化密钥的用户而言，能找到这里的配置我们可以假设用户基本也清楚密钥的重要性了，旁边也有足够的说明文字进行介绍，标红这里的部分文案以强调提醒 `所有设备必须使用相同的密钥，如果密钥不一致则无法云端同步数据`。
> 
> 以上考虑的出发点是减少用户初次配置同步的压力，强调密码短语的重要性，同时也会引导用户手动复制密钥字符串来备份密钥，这样的流程我认为已经足够了。如果初始化同步时着重引导备份密钥，用户可能会感到困惑，到底是密钥重要还是密码重要，它们之前有什么区别等等疑问。

这里如果是通过云朵进来的，输入的密码，其实对于密钥没什么感知，在弹出来的导入密钥提示中，我建议是强调使用相同的密码，而不是相同的密钥，不然很可能会有人在云朵界面录入之前备份的密钥，而不是密码。
