### ISSUE TITLE
可否增加从笔记粘贴图片到word的功能？？

### ISSUE THREAD

**Issue by ohyessir** [siyuan-note/siyuan#8222]
### In what scenarios do you need this feature?

有时候需要从笔记里将图片拷贝到word，直接复制不行，得右键找到本地存储的源文件，再进行复制。好麻烦

### Describe the optimal solution

麻烦了麻烦了

**Comment by Chenm4** [comment]
右键有一个复制还有一个复制png，选第二个就行

**Comment by 88250** [comment]
使用 <kbd>复制 PNG</kbd> 的话可能会导致图片质量下降，要用原图的话只能在文件系统上手动复制了，感谢反馈。
