### ISSUE TITLE
当前插件系统读取目录的时候能否支持软链接？

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8227]
### In what scenarios do you need this feature?

我在测试开发插件的时候为了方便，试着把 dist 目录通过 mklink 制作一个软链接挂到 plugins 目录下，但是发现似乎插件系统无法读取这个目录。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/3ec589a4-7716-43e4-8a00-b1164b3f10ec)

源头可能是 Go 的接口不支持读取软链接？

![image](https://github.com/siyuan-note/siyuan/assets/27268127/78b64440-4079-4a51-88f8-933b793db17d)

### Describe the optimal solution

可否支持软链接读取

**Comment by 88250** [comment]
开发环境建议直接将 repo clone 的文件夹放在 plugins 文件夹下面，npm run dev 以后会编译出需要的文件。

**Comment by frostime** [comment]
> 开发环境建议直接将 repo clone 的文件夹放在 plugins 文件夹下面，npm run dev 以后会编译出需要的文件。

这样做会不会导致思源把整个开发目录都同步了？node_modules 可能会很大的。

**Comment by 88250** [comment]
设置一下同步忽略项。

**Comment by Zuoqiu-Yingyi** [comment]
@frostime

#8263 支持在资源目录使用软链接以进行开发测试了

**Comment by Achuan-2** [comment]
想问问插件的软链接会同步吗

**Comment by 88250** [comment]
不同步，可以测试看看
