### ISSUE TITLE
Improve `mindmap` render

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#8228]
### In what scenarios do you need this feature?

When typing /mindmap in the notes, a screen appears to create a map. This is fantastic for studying.

![image](https://github.com/siyuan-note/siyuan/assets/90691302/601964af-cb25-4f21-8e0c-2299b7017012)

But I think this lateral spacing between the blocks is very ugly. The height is nice, but the spacing... Unpleasant. I wanted to make it shorter for a more enjoyable read. Is it possible to create an option to change these settings? Something like that...

![image](https://github.com/siyuan-note/siyuan/assets/90691302/0ef8be52-0a48-4d2b-b33a-6673f858343c)

### Describe the optimal solution

New option

**Comment by chenshinshi** [comment]
If this advice can be accepted, I reccommend a method to show(By Effie).
![effie_kLmpjbWgkN](https://github.com/siyuan-note/siyuan/assets/125173405/d4434071-24ee-4679-9766-f5271570f23c)

**Comment by taozina0587** [comment]
@chenshinshi Friend, how do I do this? Would you help me?

**Comment by taozina0587** [comment]
@chenshinshi It would be perfect! It would help me a lot with my studies!

**Comment by 88250** [comment]
To be honest, the built-in /mindmap is not easy to modify, and the upstream dependent ECharts does not set the parameter of adaptive width.

At present, it is recommended to consider other extension methods (such as widgets or plugins) to write mind maps. Thanks for understanding, we will close this issue.

**Comment by zxhd863943427** [comment]
我觉得改成这个示例就差不多了
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/772f466e-9a6c-4842-99e3-120b7bf5dda5)
