### ISSUE TITLE
Uncontrollable page jumping

### ISSUE THREAD

**Issue by GoseRank** [siyuan-note/siyuan#8229]
2.8.7 页面不受控跳动 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新2.8.7版本之后。
1. 两篇文档同时打开，使用滚轮滑动页面之后，再单击页面，页面会发生不可控跳动
2. 打开单篇文档，鼠标点击标题，会发生不可控跳动
在官方主题、第三方主题、黑白主题下均能复现BUG。(插件系统已全部关闭)

After the 2.8.7 update.
1. Two documents are opened at the same time. After sliding the page with the scroll wheel and then clicking the page, the page will jump out of control
2. Open a single document and click the title. Uncontrollable jumping will occur
Bugs can reappear under official themes, third party themes, and black and white themes. (All plug-in systems have been shut down)

### Expected result

希望能恢复稳定的阅读体验
hope to restore a stable reading experience

### Screenshot or screen recording presentation

![跳转问题](https://github.com/siyuan-note/siyuan/assets/53933742/5bc26bf6-dc47-49e5-a859-b9f528a79ca7)
![跳转问题2](https://github.com/siyuan-note/siyuan/assets/53933742/46b5dd59-82c2-4186-a70e-e5ecf5b840f3)

### Version environment

```markdown
- Version: 2.8.7
- Operating System: windows11 专业版 22624.1690
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11440006/siyuan.log)

**Comment by Vanessa219** [comment]
我们使用的是 pdf.js, https://mozilla.github.io/pdf.js/web/viewer.html 官网上划选也是无法对齐。
