### ISSUE TITLE
在编辑器旁边增加笔记的行数

### ISSUE THREAD

**Issue by Mocuishle-Zuiren** [siyuan-note/siyuan#823]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

笔记篇幅长了，看的我有点头疼，总感觉写了很多，但心里又没数，所以申请下这个功能

### 描述最优的解决方案 Describe the optimal solution

创新一个，做一个实现这个小功能的编辑器

### 描述候选解决方案 Describe the candidate solution

在编辑器的某个角落，加上具体的行数

**Comment by 88250** [comment]
感谢提议，先缓缓，以后考虑。

**Comment by 88250** [comment]
暂时不考虑了，因为可能用行数来算并不太适合，以后可能会支持横向排版。我关闭了，再次感谢。
