### ISSUE TITLE
禁止将工作空间设置在第三方同步盘路径下问题

### ISSUE THREAD

**Issue by Smi1eSEC** [siyuan-note/siyuan#8230]
### In what scenarios do you need this feature?

在mac下当工作空间目录名以.nosync结尾时是不会同步到icloud中的

### Describe the optimal solution

在mac下允许icloud目录下以.nosync结尾的目录设置为工作空间

**Comment by 88250** [comment]
这个不考虑了，请将工作空间移到非 iCloud 路径下。
