### ISSUE TITLE
Improve dynamic anchor text and ref count auto-refresh stability

### ISSUE THREAD

**Issue by nekrondev** [siyuan-note/siyuan#8234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

A copy of a referenced bullet point list item text doesn't update "live" when the origin item is changed. In contrast to copy referenced headings or paragraphs the referenced text will only change if the document is closed and re-opened.

Steps to reproduce:

* Create a bullet point item
* Copy the bullet point item as reference into the same page or any other open document
* Modify the bullet points text

### Expected result

After modification of the bullet points text I would expect that the referenced bullet point text would change "live" without reloading the document page (like the same behavior when editing e.g. headers or paragraphs).

### Screenshot or screen recording presentation

![bulletpoint](https://github.com/siyuan-note/siyuan/assets/13854802/f577e7e5-3a5d-4e0d-bb31-f2633fc97323)

### Version environment

```markdown
- Version: 2.8.7
- Operating System: Win10
- Browser (if used): n/a
```

### Log file

n/a

### More information

This is a low-priority issue as it works after reloading the document.

**Comment by TCOTC** [comment]
补充一个场景：

- 引用时更新文档右上角的被引用数
- 取消引用时更新文档右上角的被引用数

[视频.webm](https://github.com/user-attachments/assets/4d444549-c01a-49f9-855b-fa591aff5bb7)

https://github.com/siyuan-note/siyuan/issues/12325

**Comment by TCOTC** [comment]
再补充：https://ld246.com/article/1725157288525 第二点

![image](https://github.com/user-attachments/assets/13381f72-993d-4123-98b9-5e948ab14a9a)

**Comment by 88250** [comment]
@TCOTC 这个问题会一并修复。
