### ISSUE TITLE
Provide API `/api/convert/pandoc`

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8235]
Support for importing EPUB 支持导入 EPUB 格式文件

### In what scenarios do you need this feature?

转换后再导入还是比较麻烦，希望能直接支持导入。EPUB格式是很多书籍的常用格式，如果支持，思源作为阅读神器的属性就有了，也是一个很好的亮点。据我所知，想要epub导入的人还蛮多的。
看到最近加了很多导出的，就想来试试看，能否考虑导入。（听群友说是调用pandoc实现的，就想着能否导入也调用pandoc）

### Describe the optimal solution

支持导入或支持在思源里面查看

### Describe the candidate solution

也许是导入也可以调用pandoc

### Other information

如果太难就算了吧

**Comment by 88250** [comment]
这个不考虑内置了，我想如果把 Pandoc 的能力通过接口暴露给外部（比如插件），通过 Pandoc 接口进行格式转换会更为灵活一些。

**Comment by Aiviokoo** [comment]
> 这个不考虑内置了，我想如果把 Pandoc 的能力通过接口暴露给外部（比如插件），通过 Pandoc 接口进行格式转换会更为灵活一些。
> 
> 

好嘛，谢谢D大，我等等大佬的插件吧

**Comment by terwer** [comment]
插件已入坑，欢迎提建议 https://github.com/terwer/siyuan-plugin-importer
