### ISSUE TITLE
Quickly insert daily note links for today and tomorrow

### ISSUE THREAD

**Issue by zengxulin** [siyuan-note/siyuan#8237]
### In what scenarios do you need this feature?

I often use daily notes to keep track of my thoughts, tasks, and events for each day. It would be helpful to quickly insert links to today's and tomorrow's daily notes, so I can easily navigate between them and create connections in my notes.

### Describe the optimal solution

Provide a feature that allows users to use slash commands (e.g., "/today" and "/tomorrow") to quickly insert links to the daily notes for today and tomorrow. This is similar to the "/today" feature in Logseq.

![快速插入日志双链](https://github.com/siyuan-note/siyuan/assets/54364623/7ae851af-0e8d-41fd-b84f-86d2ae472863)

### Describe the candidate solution

I hope to be able to support slash commands because they are more intuitive. They don't necessarily have to be added to the command panel.

**Comment by 88250** [comment]
A direct solution will not be provided for now, but there are some alternatives:

* Set phrases by input method
* Enter date via template

Enter the date and then select the date text link to a dailynote doc:

![issue](https://github.com/siyuan-note/siyuan/assets/873584/9454d0c3-c5f4-4f5d-b058-b4b0add529f1)

Template:

```
.action{now | date "2006-01-02"}
```

But for the link to the future (documents that do not exist at present), Siyuan cannot do it at present, and can only create a document before citing it.

**Comment by zengxulin** [comment]
> A direct solution will not be provided for now, but there are some alternatives:
> 
> * Set phrases by input method
> * Enter date via template
> 
> Enter the date and then select the date text link to a dailynote doc:
> 
> ![issue](https://github.com/siyuan-note/siyuan/assets/873584/9454d0c3-c5f4-4f5d-b058-b4b0add529f1)
> 
> Template:
> 
> ```
> .action{now | date "2006-01-02"}
> ```
> 
> But for the link to the future (documents that do not exist at present), Siyuan cannot do it at present, and can only create a document before citing it.

OK, thinks.

**Comment by zengxulin** [comment]
> A direct solution will not be provided for now, but there are some alternatives:
> 
> * Set phrases by input method
> * Enter date via template
> 
> Enter the date and then select the date text link to a dailynote doc:
> 
> ![issue](https://github.com/siyuan-note/siyuan/assets/873584/9454d0c3-c5f4-4f5d-b058-b4b0add529f1)
> 
> Template:
> 
> ```
> .action{now | date "2006-01-02"}
> ```
> 
> But for the link to the future (documents that do not exist at present), Siyuan cannot do it at present, and can only create a document before citing it.

ok, thanks

**Comment by fenilgmehta** [comment]
Hi, are there any plans for this?

To make it generic, we can have date picker
![image](https://github.com/siyuan-note/siyuan/assets/42742240/9fcc920d-8cae-4006-8fcc-ba54cec660d0)
![image](https://github.com/siyuan-note/siyuan/assets/42742240/901a6e73-8f8b-4543-b1c5-53cbd8e80111)

The primary importance for this is that we want to "create a daily note doc for some date D and get its ref" which follows the `New daily note` setting.
![image](https://github.com/siyuan-note/siyuan/assets/42742240/300090af-ade1-4010-a104-9633f3a234be)

This is mainly useful when we want to write "timeline or todo items" for work W1, W2,... in its doc for "past, present and future dates", and then use backlinking information to see what work we did on some date D. Below is an example of two work W1, W2 and the work done on each day
![image](https://github.com/siyuan-note/siyuan/assets/42742240/9df9d5d7-342b-4039-82a1-8b88e715ec37)

**Comment by 88250** [comment]
No plan, let's go through the template.

**Comment by candideu** [comment]
How can I get this working?
