### ISSUE TITLE
Export PDF hangs on focus heading

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复现方法如下：

1. 把一个引用块设置为标题
2. 聚焦这个标题块
3. 导出 PDF，卡死

![@{AY5%0JA)HFOALZAVS{7T1](https://github.com/siyuan-note/siyuan/assets/27268127/ca7c8670-f1c6-4354-be90-b8e504bbb542)

![G3RPTS6VDE5}S9E$Z90{SD](https://github.com/siyuan-note/siyuan/assets/27268127/5b5d14e3-07f3-46a7-991e-dfd09d79fd3b)

群友们成功复现了这个 bug

![image](https://github.com/siyuan-note/siyuan/assets/27268127/265a8064-7084-4adb-841f-bb976ca3a806)

### Expected result

正常导出。

### Version environment

```markdown
- Version: win10
- Operating System: 2.8.7
- Browser (if used): no
```

### Log file

没有特别反应：

```log
I 2023/05/12 16:24:04 runtime.go:124: use network proxy [system]
I 2023/05/12 16:24:04 serve.go:112: kernel [pid=2272] http server [127.0.0.1:12232] is booting
I 2023/05/12 16:24:04 pandoc.go:67: built-in pandoc [ver=2.19.2, bin=H:\Media\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/05/12 16:24:05 sync.go:150: sync before boot
I 2023/05/12 16:24:05 repository.go:1032: boot get sync cloud files elapsed [0.40s]
I 2023/05/12 16:24:05 blocktree.go:448: read block tree [10 MB] to [H:\Media\SiYuan\temp\blocktree], elapsed [0.03s]
I 2023/05/12 16:24:05 conf.go:682: database size [112 MB], tree/block count [720/33316]
I 2023/05/12 16:24:05 working.go:155: kernel booted
I 2023/05/12 16:24:05 box.go:78: auto stat [trees=720, blocks=33316, dataSize=237 MB, assetsSize=154 MB]
I 2023/05/12 16:24:05 disk.go:33: disk usage [total=846 GB, used=442 GB, free=404 GB]
I 2023/05/12 16:24:06 serve.go:125: reverse proxy server [127.0.0.1:6806] is booting
I 2023/05/12 16:24:52 repository.go:1133: synced data repo [provider=0, ufc=3, dfc=1, ucc=1, dcc=0, ub=76 kB, db=106 kB] in [1.91s]
```

**Comment by 88250** [comment]
我这里在 v287 和 dev 上均重现不了，操作如下：

![issue](https://github.com/siyuan-note/siyuan/assets/873584/6843916b-d888-46ab-ad01-32c0945ccf09)

**Comment by Dammyxy** [comment]
> 我这里在 v287 和 dev 上均重现不了，操作如下：
> 
> ![issue](https://user-images.githubusercontent.com/873584/237918183-6843916b-d888-46ab-ad01-32c0945ccf09.gif)

设置-导出里将引用改为脚注试试

**Comment by 88250** [comment]
@Dammyxy 能够重现了，多谢。
