### ISSUE TITLE
存储所有标签页

### ISSUE THREAD

**Issue by Maxpiner** [siyuan-note/siyuan#824]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在使用思源进行某一主题的写作时经常会涉及到多个笔记文档，有时需要将打开的所有文档页签存储起来以备后用。这样可以在进行其他主题的写作时保持页面干净，也避免下次打开时浪费时间在慢慢寻找需要打开的文档上。
效果可以参考Chrome和Edge的OneTab插件。

### 描述最优的解决方案 Describe the optimal solution
在页签的右键菜单里添加存储选项；或者设置一个专门的按钮。

**Comment by deerainw** [comment]
这个是会话保存吧，对应的应该是 FreezeTab 扩展

**Comment by Maxpiner** [comment]
意思差不多，似乎FreezeTab更强大一些？

**Comment by 88250** [comment]
书签标识右键加一个“打开全部”如何？

![image](https://user-images.githubusercontent.com/873584/103175306-f7d91400-48a3-11eb-98e9-d22f84129380.png)

**Comment by deerainw** [comment]
楼主提到的是「保存当前已打开的标签页」，如果只做这个的话，确实可以整合到书签面板里，每次保存会话的时候给当前窗口里打开的每个文档添加并命名一个新书签、再给书签右键加上「打开全部」选项就好了。但是我感觉这个特性可以作为一个长期计划仔细考虑一下，因为它和「保存搜索结果」应该有办法整合到一起。

「保存搜索结果」是印象笔记最有想法的一个功能，Twitter 的搜索框也有这个功能，实际上就是把常用的几个搜索关键词存下来，而印象笔记是支持高级搜索语法的，所以这个功能很适合用来保存跟某一个主题相关的内容，这种方式是基于搜索的，在精确性上欠缺一些；而「保存当前已打开的标签页」保存的是自己手动打开的一组文档，更精确，但是因为每篇笔记都是自己手动找出来的所以比较麻烦。它们有一个共同点，它们所保存下来的实际上都是针对某主题的一个个集合，针对主题的功能是现在所有的同类软件比较欠缺的。

现在我有个初步展望，在搜索页签完成后，这两个功能应该可以同时靠搜索页签来体现，一个是用保存下来的搜索关键字去匹配，一个是用保存会话时给每个文档添加的某个属性（比如书签）去匹配，但不知道实现上有没有什么未知问题。

如果考虑得再远一点，在块属性出来以后，「视图」既可以基于块属性筛选结果，也可以基于这种保存下来的文档集合。

**Comment by 88250** [comment]
@deerainw 谢谢，那我们就等块属性吧，基于统一一些的底层结构来考虑这个……

**Comment by 88250** [comment]
界面上的布局我们通过 Dock 停靠栏来放置页签 #635 
每种页签内的业务状态先换换，等界面搞好以后再细化，谢谢讨论。

**Comment by TCOTC** [comment]
@88250 可以为当前打开的文档页签批量添加书签吗？

**Comment by 88250** [comment]
> @88250 可以为当前打开的文档页签批量添加书签吗？

这个插件实现更合适吧。
