### ISSUE TITLE
避免插件开发的时候误删自己的项目

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8241]
### In what scenarios do you need this feature?

插件开发的推荐流程是直接在 plugins 下开发。但是存在不小心删除的风险。

![`7H1B1MS))_B72CLHIP~UBS](https://github.com/siyuan-note/siyuan/assets/27268127/7df11c83-fbf7-4a9e-a91c-e23238601553)

我测试了一下，卸载一个插件是直接把文件夹删掉而不是放入回收站，那如果误删了自己的工作目录，而且有没有提交到 remote，那可能整个工作就废了。这个代价对开发者来讲几乎不可接受。

更何况删除按钮和其他按钮离得很近，存在误触的可能。

![V ~534TT 6BP B6IX}~_ N6](https://github.com/siyuan-note/siyuan/assets/27268127/9c3435e5-6f15-4d78-a54b-128a15d0c769)

指望开发者的自觉完全不可靠，系统安全知识告诉我们：「如果存在风险，那么风险100%会在某天被触发」。所以有必要设置一些机制来防止这种事情发生。正如 `rm -rf` 也可能误操作，于是才有了 trash-cli，严格的权限管理机制等补救措施。

### Describe the optimal solution

- 方案一：删除插件变成放入回收站而不是删除文档树
- 方案二：在 plugin.json 中加入一个字段，表示当前是开发目录，对于开发目录，卸载按钮无效

**Comment by 88250** [comment]
这两个方案好像不可行：

1. 之前研究过，无法实现稳定的跨平台回收站
2. 这个会影响实际发布

现在缺失的应该是一个确认对话框，而不是直接点完就删除。

**Comment by frostime** [comment]
> 这两个方案好像不可行：
> 
> 1. 之前研究过，无法实现稳定的跨平台回收站
> 2. 这个会影响实际发布
> 
> 现在缺失的应该是一个确认对话框，而不是直接点完就删除。

对话框可以

**Comment by frostime** [comment]
那我就关 issue 了

**Comment by 88250** [comment]
回收站后面会继续留意有没有可靠的实现库，我们是需要一个兜底的措施。
