### ISSUE TITLE
Improve open doc performance

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

无论是快捷键F5刷新还是右上菜单点击刷新，都会跳转到标题，然后需要等待很长时间才能回到原来焦点的位置。
我测试的文档较大，但在小文档中的区别只是延迟的时间短了，但是必然会跳转回标题再重新定位到焦点位置。

### Expected result

预期成果：刷新后不跳转到标题位置，在焦点位置刷新。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/bdea2c3f-df0a-454a-8782-72447903ca11

https://github.com/siyuan-note/siyuan/assets/57566668/b14b04e2-bb6e-42f2-91c2-c4519aebfb6c

### Version environment

```markdown
- Version: 2.8.8dev2
- Operating System: win10 22H2
- Browser (if used):思源客户端
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11467324/siyuan.log)

**Comment by Vanessa219** [comment]
第一个慢的也太夸张了，你看一下网络加载时间。网络有没有开代理？
出现标题跳转是正文还没加载出来，这个后面可以优化一下。


https://github.com/siyuan-note/siyuan/assets/970828/631b9792-f9e5-4caf-b7f3-4718695111ba

**Comment by gdy106** [comment]
> 第一个慢的也太夸张了，你看一下网络加载时间。网络有没有开代理？ 出现标题跳转是正文还没加载出来，这个后面可以优化一下。
> 
>  QQ20230513-105412-HD.mp4

这个工作空间我没有开启云端同步，是纯本地的。也没有开启任何代码片段，唯一有一个列出子文档的挂件，应该也不影响。
所以应该不是网络因素影响？
电脑有开代理但是这个工作空间没有开启代理。
昨天思源和电脑系统都重启过，依然复现。但是刚才我再试了一下，延迟在3秒之内了。原因不明。

**Comment by 88250** [comment]
电脑开了全局代理的话会有影响，关闭再试试。

**Comment by gdy106** [comment]
> 电脑开了全局代理的话会有影响，关闭再试试。

我检查了一下代理，我开的是规则代理，不是全局。我改到直连模式重新测试了一下，然后又在思源里配置好代理端口，两者结果和之前没有明显区别，都是要卡一下，不过没有出现昨天那样刷新后要等待接近一分钟的情况。

https://github.com/siyuan-note/siyuan/assets/57566668/962cfcd9-3cc0-430f-8ea7-7b1edc763ca0

![Snipaste_2023-05-13_12-43-02](https://github.com/siyuan-note/siyuan/assets/57566668/11c214f5-d7d1-4277-bc37-2911721ba1de)

**Comment by 88250** [comment]
那可能还是代理相关的配置问题，建议完全不要配置代理再试试。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by gdy106** [comment]
> 那可能还是代理相关的配置问题，建议完全不要配置代理再试试。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

我不是很明白为什么我没有开启云端还和代理有关系，总之完全关闭任何代理软件后的网络情况截图和配置好网络代理的截图我都截屏了。都是会卡一下到标题然后再切回焦点。
完全关闭代理软件情况如图：
![Snipaste_2023-05-13_20-09-51](https://github.com/siyuan-note/siyuan/assets/57566668/42200904-9acb-4991-a0d3-bfc125323ad4)
![Snipaste_2023-05-13_20-11-08](https://github.com/siyuan-note/siyuan/assets/57566668/459c25f2-078b-42fd-a9e8-279d70bc55d0)

正确配置代理后网络情况如图：
![Snipaste_2023-05-13_20-14-13](https://github.com/siyuan-note/siyuan/assets/57566668/bd56a9ab-633d-4a5d-b77b-167b847f1637)
![Snipaste_2023-05-13_20-14-27](https://github.com/siyuan-note/siyuan/assets/57566668/75a9e06a-75bc-4b8f-8ad4-291c0dc15636)

目前都没有复现昨天那样卡一分钟的情况。

**Comment by 88250** [comment]
哦，那我理解错了，一分钟那个应该是网络代理的问题。

目前还是比较慢的问题正在优化，谢谢。
