### ISSUE TITLE
Add kernel API `/api/block/getChildBlocks`

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8249]
### In what scenarios do you need this feature?

新的 API ，

- 可以遵循在文档 DOM 中的顺序获取一个块**直接的子块** ID
- **包括标题块**

https://ld246.com/article/1683971024988

### Describe the optimal solution

- API : `/api/block/getChildBlocks`
- 参数
```json
{
    "parentID": ""
}
````
- 返回
```json
{
    "data": ["子块 ID"]
}
````

**Comment by 88250** [comment]
返回值有些许调整，请以 API 文档为准。

**Comment by frostime** [comment]
> 返回值有些许调整，请以 API 文档为准。

D 大速度，令人震惊😆
