### ISSUE TITLE
The PDF tab cannot be displayed on the iPad

### ISSUE THREAD

**Issue by zuiyuemuai** [siyuan-note/siyuan#8250]
iPad上PDF打开空白无显示

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

iPad上PDF打开空白

### Expected result

无法浏览PDF

### Version environment

```markdown
- Version: 2.8.7
- Operating System: IOS14.2
- Browser (if used):Not
```

### Log file

No Log

**Comment by 88250** [comment]
是扫描版的 PDF 吗？

**Comment by 88250** [comment]
如果是扫描版 PDF 的话请参考 https://github.com/siyuan-note/siyuan/issues/5079

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
