### ISSUE TITLE
[疑问] 语言文件请求结果是过时的 

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#8251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

前端请求语言文件:
https://github.com/siyuan-note/siyuan/blob/fb007a61c036aeebc1a5fdb3d6f5b10f9ce91cdd/app/src/index.ts#LL167C31-L167C31

内核接收:
https://github.com/siyuan-note/siyuan/blob/109462a22f5ad2696be3349e98c89289e0652166/kernel/server/serve.go#LL221C5-L221C5

但是启动后前端请求后收到的languages一直是旧数据
如果我直接 调用api
http://127.0.0.1:6806/appearance/langs/zh_CN.json
则能返回新数据

我估计是缓存原因;
但是 我在思源里面, 已经勾选了 网络>停用缓存

![Snipaste_环境返回_2023-05-13__22-37-09](https://github.com/siyuan-note/siyuan/assets/48077521/17f7530b-2789-4393-af91-8fa31cc8f8db)
![Snipaste_环境返回_2023-05-13__22-37-32](https://github.com/siyuan-note/siyuan/assets/48077521/f76fc016-1b50-43b8-a9ee-e84029365f96)

所以想问下, 思源内核是不是把语言文件给缓存了? 

### Expected result

`

### Version environment

```markdown
- Version: 2.8.7 dev
- Operating System: win10
- Browser (if used):
```

### Log file

`

**Comment by 88250** [comment]
网络那里禁用缓存然后强制刷新。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by iamqiz** [comment]
暂时解决了, 要取消 service workder 注册

另外有个疑问想请教一下 @88250  @Vanessa219 
app/src/protyle/util/hotKey.ts 里的 matchHotKey 函数为什么不把当前按下的按键(组合)转换成字符串,然后再和用户设置的快捷键进行比较,这样不是更高效吗? 
app/src/protyle/wysiwyg/keydown.ts 里面调用很多matchHotKey函数
