### ISSUE TITLE
无序列表的逻辑问题

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#8252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

无序列表中
假如内容如下

![Snipaste_2023-05-14_16-06-18](https://github.com/siyuan-note/siyuan/assets/107289739/2bd8da9f-b2e0-4db0-b416-c271fbf49836)
可以看到 # 后面并没有子分支，如果将 # 升到与 ！并列的等级，按逻辑讲应该是把#和#下的子分支升级一位，所以结果应如下
![image](https://github.com/siyuan-note/siyuan/assets/107289739/341d7de9-27d6-465f-8584-5aaffd8f89a6)

但是目前思源并不是这样的，反而呈现如下结果
![Snipaste_2023-05-14_16-11-55](https://github.com/siyuan-note/siyuan/assets/107289739/0ff8c107-57fd-40a7-80e6-813db5867cd5)

### Expected result

简单的列表中，人工手动调整就可以达到正确的预期结果，但是大量复杂的列表中调整会很麻烦，所以希望能更改逻辑。

导图模式下，因为无序列表的逻辑问题，这一现象更会凸显出来。

下面是导图中的问题，这部分问题也属于无序列表的问题。
问题一，![image](https://github.com/siyuan-note/siyuan/assets/107289739/75f6b111-6b79-4916-bf09-afadea73496e)
初始如上，输入光标位于“视频”后面
如果此时按回车，借鉴幕布app的逻辑则应该出现与“视频”同等级的分支，但如图所示
![image](https://github.com/siyuan-note/siyuan/assets/107289739/2559cd3e-fd18-4b6d-9846-e4225799ebd0)
siyuan中却出现了zi'fen'z子分支
问题二，如果选中新出现的子分支，然后按删除（不是del，后面也不是），在“视频”后出现一个并列块
如下
![image](https://github.com/siyuan-note/siyuan/assets/107289739/724e4ce0-159f-4316-97cf-0a28de586f36)
问题三，如果选中新出现的并列块，按逻辑讲应该。。。。我也不知道按逻辑应该怎么样。。。
问题四，如图所示，
![Snipaste_2023-05-14_16-25-56](https://github.com/siyuan-note/siyuan/assets/107289739/94a1f2c0-3383-4efe-a8f3-a6f18d5cf5d6)

在“武忠祥”末尾处按下回车键，会出现并排的分支，此时选中新出现的并排分支然后按删除键，会出现如下结果
![Snipaste_2023-05-14_16-25-24](https://github.com/siyuan-note/siyuan/assets/107289739/5575c78e-c59c-42e9-a5b4-3e1ee1e9ab33)

这与导图中的第一个问题类似又不完全相同，因为它并没有升级到母分支bin并与其xing'cheng形成并排的超级块，反而与子分支形成并排超级块

### Screenshot or screen recording presentation

完

### Version environment

```markdown
- Version: 最新
- Operating System: win11（最新）
- Browser (if used):
```

### Log file

懒

**Comment by mozhux** [comment]
可以在设置-编辑器-列表反向缩进中打钩，就可以按你结果显示了。

**Comment by linglongyoudoufu** [comment]
> 可以在设置-编辑器-列表反向缩进中打钩，就可以按你结果显示了。

部分问题还是存在

**Comment by mozhux** [comment]
如果是导图的话，列表转化导图也是按的列表的逻辑来的，它只是视觉上变化了，有些不一定是问题。另外导图那个是主题功能，开发者也不好回答，最好是换成列表形式的。

**Comment by 88250** [comment]
正如楼上的回复，谢谢，我们关闭了。

**Comment by linglongyoudoufu** [comment]
问题未解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月14日(周日) 晚上11:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 无序列表的逻辑问题 (Issue #8252)




 
正如楼上的回复，谢谢，我们关闭了。

**Comment by 88250** [comment]
你指的是列表转换思维导图的问题吗？
