### ISSUE TITLE
Hi guys, can't find a contact email anywhere

### ISSUE THREAD

**Issue by michaelbeijer** [siyuan-note/siyuan#8255]
### In what scenarios do you need this feature?

Sorry to post this in the wrong section, but I **can't find a contact email anywhere**. I'm interested in trying out your app.

Is the cloud sync subscription available to people in the United Kingdom?

### Describe the optimal solution

Sorry to post tis in the wrong section, but I can't find a contact email anywhere, and am interested in trying out your app. Specifically, is the clous sync subscription available to people in the United Kingdom?

### Describe the candidate solution

-

**Comment by 88250** [comment]
Hello, at present, SiYuan does not support subscriptions for non-mainland Chinese users.

However, at present, data synchronization can be performed by connecting to the WebDAV/S3 storage service by yourself. This function is free this year, and may be charged next year.

In the future, we may build data centers in North America to support paid subscriptions, please stay tuned, thank you very much.
