### ISSUE TITLE
[Feature request] Markdown import/export

### ISSUE THREAD

**Issue by SaifEl-Deen** [siyuan-note/siyuan#8257]
### In what scenarios do you need this feature?

I want to migrate from obsidian to siyuan but I can't find a way to import my markdown files into siyuan

### Describe the optimal solution

Implementing the ability to import/export markdown files or any universally supported file type.
Obsidian and Logseq are the main note-taking software that use markdown files as their default.

### Other information

The current way of storing data is not future-proof and is impossible to migrate into/from siyuan.

**Comment by 88250** [comment]
Hello, you can find the import Markdown function by right-clicking on the notebook/document:

![image](https://github.com/siyuan-note/siyuan/assets/873584/85b1654f-cd82-41c2-849b-2825ce8f3a9e)

**Comment by SaifEl-Deen** [comment]
> Hello, you can find the import Markdown function by right-clicking on the notebook/document:
> 
> ![image](https://user-images.githubusercontent.com/873584/238232934-85b1654f-cd82-41c2-849b-2825ce8f3a9e.png)

Sorry for my lack of attention, I didn't know it was there.

I just have a question about it, how can I import/export markdown files in bulk? I have about 500+ files

**Comment by 88250** [comment]
Try to use `Import - Markdown Folder`
