### ISSUE TITLE
Cannot return when loadData is empty

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8259]
### bug
插件执行如下方法，第一次会log输出空值，这是正常的，可如果此时再重载（重启）思源，不会有任何输出，也未显示报错，应该是文件为空时读取报错了，但是没有打印
```
async test(){
    await this.loadData("123");
    this.saveData("123", "");
    await this.loadData("123");
    console.log(this.data["123"]);
}
```
### features
1. 卸载插件时应该删除`/data/storage/petal`下对应的插件文件夹，否则未来可能会产生错误
2. 应该提供类似`deleteData()`这样的删除api，便于开发者删除无用的、错误的data文件
3. 应该提供类似`onUpdate(){}`这样的方法，当用户更新插件后，只执行一次，便于开发者升级配置，以及修复之前版本的错误，如果产生错误，用户只能够通过卸载重装来实现，过于麻烦且用户不一定想得到
4. 可以提供`initData()`方法供开发者预置数据

### Describe the optimal solution

无

**Comment by Vanessa219** [comment]
bug 已重现，稍后修复

1. 用户数据不应该删除，这样再次安装的时候还会有原来的数据
2. https://github.com/siyuan-note/siyuan/issues/5066
3. 可以在 onload 时对升级数据进行兼容处理
4. 默认值可用常量直接置于代码中，这样也不会和 data 有所冲突
