### ISSUE TITLE
希望能增加导出dokuwiki等格式的选项。

### ISSUE THREAD

**Issue by PumpkinSin** [siyuan-note/siyuan#826]
可以试试整合[pandoc](https://github.com/jgm/pandoc)等工具增加导出语法格式。
个人因为喜欢在dokuwiki归档文章，所以刚需相关语法。
之前用notion时我就是使用[quicker调用pandoc进行md到dokuwiki转换](https://getquicker.net/Sharedaction?code=6d72f89a-19cb-4579-cbff-08d843d73d4c&fromMyShare=true)。如果软件能原生支持那就最好了。
![](https://i.loli.net/2020/12/24/OIHL21CyRJ7eWfm.gif)

**Comment by 88250** [comment]
你好，原生支持导出估计不会支持，后期会尝试集成 Pandoc，谢谢。
