### ISSUE TITLE
插件初始化失败机制不正常

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我使用了比较老的版本的插件模板，内部使用了createTab而不是addTab，这使得加载到这一步时会失败。

但是，插件运行失败后，会同时导致后续插件无法运行，且控制面板没有报错产生，只有警告。这不是很合理。

### Expected result

插件运行失败不会影响其他插件加载，且能在控制面板见到报错

### Version environment

```markdown
- Version: 2.8.8dev3
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by Vanessa219** [comment]
e7288185beaa6edb8c8e3fe457829f9a0bbc5557
