### ISSUE TITLE
`Replace All` is no longer affected by pagination

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#8265]
替换的"全部替换"选项并没有实现"全部替换",只替换了匹配中的一页内容

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在使用"替换"功能时,查找到了好几页的匹配内容
<img width="1045" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/6d73be91-1779-4fdf-b2a6-21dc47b25cad">
但是在点击"全部替换"后,发现只替换了第一页的内容

### Expected result

我希望"全部替换"可以真正的"全部替换",把全部的匹配项都替换了,而不是只能替换一页的内容

现在每次替换都会让siyuan重启,然后我需要重新设置查找和替换的内容,如果有多页的匹配的内容需要替换,这将会极大的降低效率

### Version environment

```markdown
- Version: 2.8.7
- Operating System: fedora(使用AppImage包)
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11478747/siyuan.log)

**Comment by 88250** [comment]
这个目前无法实现，因为替换的前提是依赖搜索结果。

替换时通过传入搜索结果块 ID 列表后再在这些块中进行替换，搜索是分页进行的，因为性能考虑所以无法一次性列出所有搜索结果，进而无法一次性进行全部替换。

这个后面可能可以期待下社区插件实现进行特定场景的搜索替换全部，特定场景指的是不糅合太多复杂的搜索条件（比如查询字符串、正则这些），只是简单实现关键字匹配，或者是从文件系统（而不是数据库）的角度上进行实现，这样的特定场景实现起来会比较容易一些。内置实现的话问题会比较多，目前就不考虑了，谢谢。

**Comment by zxhd863943427** [comment]
那能否允许更改每页的数量？否则当需要替换的数量大了之后真的很烦人

**Comment by 88250** [comment]
暂时不考虑改了，改太大可能会导致卡死。

**Comment by zxhd863943427** [comment]
这只是个允许用户自定义的参数，大不了加一个提示就算了。

**Comment by 88250** [comment]
之前是允许的，但是有用户不太留意时会配置很大，导致卡死，所以写死一些可靠点。

**Comment by HopeLHP** [comment]
如果计划保持现状的话，我认为可以在替换文本框内设置占位文本提示大家替换是有限制的，不然可能存在用户以为已经替换完成但实际没有全部完成且用户没有留意的情况。我发现这种情况还是文件夹内随机选了几个文档进行检查发现的。
<img width="1214" alt="image" src="https://github.com/siyuan-note/siyuan/assets/70339118/80ec5bcf-1a40-4840-995e-654d9e47ba73">
