### ISSUE TITLE
unconsistent results when pasting a markdown style link from 3rd application to siyuan

### ISSUE THREAD

**Issue by wherejumpout** [siyuan-note/siyuan#8266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

when I paste a markdown style link "[Downloads](file:///Users/who/Downloads)" to siyuan.

It's parsed as an inline code.  
But when I copy this markdown style string from another application. Siyuan recoginzed it as a link, as following:  

<img width="375" alt="image" src="https://github.com/siyuan-note/siyuan/assets/128914992/3454a7de-9df2-4d30-9558-da1cdc7c9947">
 

### Expected result

I expect the same behaviour when pasting such string.  Or more detailed control on how to paste a string:
1.  paste as as plain text
2.  paste escaped text
3.  paste raw text 

### Version environment

```markdown
- Version: 2.8.6
- Operating System: Mac OS 13.3.1 (a) (22E772610a)
- Browser (if used):
```

### Log file

nothing but only the sync message
I 2023/05/16 00:23:42 repository.go:1138: synced data repo [provider=0, ufc=3, dfc=1, ucc=1, dcc=0, ub=259 kB, db=474 kB] in [2.29s]
I 2023/05/16 00:24:54 repository.go:1138: synced data repo [provider=0, ufc=3, dfc=1, ucc=1, dcc=0, ub=259 kB, db=474 kB] in [2.42s]
I 2023/05/16 00:27:32 repository.go:1138: synced data repo [provider=0, ufc=3, dfc=1, ucc=1, dcc=0, ub=259 kB, db=474 kB] in [2.51s]
I 2023/05/16 00:29:29 repository.go:1138: synced data repo [provider=0, ufc=3, dfc=1, ucc=1, dcc=0, ub=259 kB, db=474 kB] in [2.26s]
I 2023/05/16 00:35:02 repository.go:1138: synced data repo [provider=0, ufc=3, dfc=1, ucc=1, dcc=0, ub=259 kB, db=474 kB] in [2.44s]

**Comment by Vanessa219** [comment]
Paste from the IDE, we have no way to distinguish md or code.

Currently it can only be pasted into text editor and copied again.
