### ISSUE TITLE
improve the sync performance when opening siyuan app on mobile 

### ISSUE THREAD

**Issue by wherejumpout** [siyuan-note/siyuan#8267]
### In what scenarios do you need this feature?

when launching siyuan app on mobile ( iphone) , It takes quite a long time waiting the app to finish the data syncing and building.  Mostly on the mobile ,  user opens siyuan to read some information, rather than edit the documents.  It's really not a good experence to use siyuan on mobile.  

 

  

### Describe the optimal solution

Suggest that siyuan app to launch in a read-only mode in default. The data sync process can be done in the background process. 

In the 99% percent scenarios,  the documents of some old data snapshot is OK for mobile users.

**Comment by 88250** [comment]
Please try to change the sync mode to `Full manual sync`:

![image](https://github.com/siyuan-note/siyuan/assets/873584/b545a6db-2198-40b7-b7cc-0a430301b8d3)
