### ISSUE TITLE
Add some plugin APIs

### ISSUE THREAD

**Issue by MarkMindCkm** [siyuan-note/siyuan#8268]
### In what scenarios do you need this feature?

1. 目前可以通过使用思源链接（siyuan://） 来打开块，是否可以在插件 api 中暴露出一个打开块的方法 比如 `openBlock(id)`
2. 在插件 api 中暴露出定位 pdf 某个标注的方法 比如 `positionAnnot(annotationId)`
3. 当点击 pdf 标注时，向 tab 页广播一个事件，比如带上点击的标注的 id , 这样插件订阅这个事件，可以确定点击的是哪一个标注

通过这些方法，插件可以更好的处理一些问题，比如可以将思维导图节点和标注一一对应，并且可以点击相互定位

### Describe the optimal solution

需要暴露一些方法

### Describe the candidate solution

需要将目前已有的相关方法暴露到插件中

**Comment by MarkMindCkm** [comment]
另外 是否需要将 解析 markdown 的方法也暴露到插件 api 中，这样插件就不必自带一个解析器

**Comment by Vanessa219** [comment]
1. openTab https://github.com/siyuan-note/siyuan/issues/5066
2. 通过  openTab参数
3. 没太理解使用场景，目前点击事件都不会广播到每一个页签中
4. 解析的话看一下 Lute 是否满足
5. 没太理解使用场景
6. 是获取当前插件打开的所有页签还是其他页签也需要？
7. 目前有以下几个，是否满足？
```
    addTab(options: {
        type: string,
        destroy?: () => void,
        resize?: () => void,
        update?: () => void,
        init: () => void
    }): () => any
```

**Comment by MarkMindCkm** [comment]
感谢回复！

1. Lute 解析器是可以的，可以像 obsidian api  那样提供一个 `MarkdownRenderer ` 用以将 markdown 文本转为html，这样插件就不必自带解析器
2. 点击标注广播标注 id ，这个功能是为了做一个效果，即点击标注确定节点，类似这样
![test](https://github.com/siyuan-note/siyuan/assets/18719494/dc9f9b7e-9f71-437c-8586-4d155d5ecf41)
3. 插件注册一个协议，实际上也是类似 obsidian api , 有一个 `registerObsidianProtocolHandler` 方法
4. 插件获取打开的tab页，是获取属于插件本身 tab , 因为一个插件可以打开多个 tab页，比如当关闭插件时，需要将所有的插件tab页都给关闭，并且需要清理事件,比如这种
``` js
onunload:()=>{
   this.getTabs().forEach(tab=>{
       ...
      tab.close();
   })
}
```
6. addTab 是可以的，如果再有一个激活 和 非激活 tab 页 的方法就好了，比如在激活tab页时重新初始化调用 init 函数，在非激活的方法里清除事件等等，防止占用太多内存

**Comment by terwer** [comment]
window上面有Lute对象。思源笔记的环境可以直接获取window.Lute，docker和客户端都可以。
![image](https://github.com/siyuan-note/siyuan/assets/3259282/cb06f9ad-96dd-48ca-9dd6-6e9275f0e5a4)

**Comment by zuoez02** [comment]
这里提一点我的想法，希望能够增加钩子函数，插件可以在思源渲染前，渲染后分别做不同的操作。
目前两个问题：
1. 直接在插件onload的时候同时addTab和openTab是出错的，因为layout还没加载完会报错。
2. tab没有持久化，刷新之后我插件打开的tab就没了。

想到的解决方案：
1. onload的时候，通过addTab注册tab处理的函数。
2. onReady的时候，才允许插件执行openTab，前置不行。
3. layout正常持久化，在插件都onload之后，检查所有注册的tab，并进行对应的渲染。渲染不了的tab，再提示说缺少渲染函数。

通过生命周期钩子，让插件在需要的时候做正确的事情，确保流程运转正常和性能优化

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/5066

**Comment by HowcanoeWang** [comment]
好像没有在api文档中找到openTab相关的说明？

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/petal/blob/bb1a9b4507e89288599ba094ef6bd6d9374f83e2/siyuan.d.ts
