### ISSUE TITLE
多端同步最近文档

### ISSUE THREAD

**Issue by DionathanJostar** [siyuan-note/siyuan#8269]
### In what scenarios do you need this feature?

1.手机端文档树又深又不好操作

### Describe the optimal solution

将最近文档加入到同步内容当中，在电脑端同步之后，可以在手机端快速打开，无缝连接工作。

**Comment by 88250** [comment]
最近的文档设计上不进行同步 https://github.com/siyuan-note/siyuan/issues/7246

感谢反馈。

**Comment by DionathanJostar** [comment]
> 最近的文档设计上不进行同步 #7246
> 
> 感谢反馈。

D大是真的不准备改进手机端的使用舒适度啊。。。
