### ISSUE TITLE
希望可以添加移动端直接拍照插入图片的功能

### ISSUE THREAD

**Issue by zraistlin61** [siyuan-note/siyuan#8271]
### In what scenarios do you need this feature?

我觉得这个功能可以简化很多操作，希望可以采纳。
不是很懂github的使用，如有不对，还请见谅。

### Describe the optimal solution

略

### Describe the candidate solution

略

### Other information

略

**Comment by lunzilunzi** [comment]
图片直接保存到相册也挺需要的

**Comment by 88250** [comment]
抱歉了，这个目前无法解决，我们只能先关闭了，后面如果能够解决会考虑重新打开，感谢反馈。
