### ISSUE TITLE
Improve search result highlight and positioning

### ISSUE THREAD

**Issue by michaelbeijer** [siyuan-note/siyuan#8274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I have only just started using SiYuan, but have run into two problems with search.

**1.** Ctrl+P isn't finding anything. Well, it does sometimes, but mostly it is not finding longer phrases. Or even shorter prases.

For example, if I search (using Ctrl+P) for "Method of agitation and agitator for vats and the final products obtained", which I know is in a document with a table of patent names, it highlights a few random words near the top of the table. If I write the exact phrase ("Method of agitation and agitator for vats and the final products obtained") at the top of a page, and re-run the search, it finds it.

**2.** Ctrl+F just seems to open the same window as Ctrl+P. If I open the page with the table mentioned above, and click Ctrl+F, the same window opens up, and then try to search for "Method of agitation and agitator for vats and the final products obtained", I get the same behaviour as described above.

### Expected result

I expect search to find (and highlight) exactly what I am looking for. Not random words all over the page, as is currently happening.

### Screenshot or screen recording presentation

![search-problem](https://github.com/siyuan-note/siyuan/assets/16622240/784bd6f1-d262-4331-8b7d-d96941785b59)

### Version environment

```markdown
- Version: 2.8.7
- Operating System: Windows 11
- Browser (if used): Chrome
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11486674/siyuan.log)

**Comment by 88250** [comment]
Hello, the default search method is `Keyword`, which uses spaces to separate search keywords and connects them with "AND" logic.

![image](https://github.com/siyuan-note/siyuan/assets/873584/ac58221a-e8ce-4fbe-a603-85a4f8ce4d52)

If you want to fully match the search keyword, you can change the search method to `Query Syntax`, and use double quotes to wrap the input, such as `"foo bar"`.

**Comment by michaelbeijer** [comment]
Thanks for the info! However, changing it from **Keyword** to **Query Syntax**, and adding quotes to the search phrase hasn't solved the problem. Strangely, the results are exactly the same as before.

**Comment by michaelbeijer** [comment]
I made a quick video to show you what I mean: https://app.screencast.com/1PC4mbnCG2Mdr

**Comment by 88250** [comment]
We know what the problem is from your demo, but we need some time to think about how to improve it, thank you very much.

**Comment by michaelbeijer** [comment]
By the way, is there a keyboard shortcut to jump to the next match in the document? That would also be very useful in scenarios where there are multiple similar hits in a document, as otherwise you need to do a lot of scrolling. Spacebar would be a good one!

**Comment by 88250** [comment]
There is currently no shortcut key to switch, but you can switch with a mouse click.

![image](https://github.com/siyuan-note/siyuan/assets/873584/b7087022-edeb-4bf4-94e6-91ee45332e49)
