### ISSUE TITLE
Plugin API `onunload` not being called

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8277]
插件 API onunload 没有被调用

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

plugin 的 onunload hook 没有被调用，导致一些资源没有被释放。

### Expected result

正常调用

### Version environment

```markdown
- Version: 2.8.8
- Operating System: win10
- Browser (if used): 无
```

### Log file

无

**Comment by Vanessa219** [comment]
目前还没想好调用时机，是在卸载或禁用的时候，亦或是其他时候？

**Comment by frostime** [comment]
应该是禁用的时候，卸载应该另外提供别的接口。

以我的为例，我的插件有部分功能需要监听 DOM 的变化，必须才在禁用的时候手动把监听器释放掉。

至于卸载的接口，可以后面在额外加。

**Comment by Vanessa219** [comment]
卸载的时候也是先需要先禁用再移除，那我就先加在这两个地方吧。
