### ISSUE TITLE
Can the shortcut key function be upgraded?

### ISSUE THREAD

**Issue by nuistZPZ** [siyuan-note/siyuan#8278]
### In what scenarios do you need this feature?

个人感觉思源的快捷键操作还不够方便。
1.很多块不支持逆向操作，例如，代码块不能转换为普通文本。即使使用UI操作也不能直接转换，只能复制文本然后删除代码块。在其他笔记中，我经常使用逆向操作将几行转换成代码块格式，或将代码块中的几行转换成普通文本。
2. 许多常用的功能块不支持快捷键，如有序序列、无序序列和行间公式块。不知大佬没有设置这些快捷键是否是因为认为Markdown语法新建块更方便？

### Describe the optimal solution

比如有道云笔记，Typora。
感觉Typora的逆向操作不是那么好用，必须选中文字才可以逆向操作，有道云笔记这种选择该行进行逆向操作比较符合用户习惯

**Comment by 88250** [comment]
1. 这是因为在一些块类型之间我们认为不适合相互转换，比如你提到的段落不能转换代码块和代码块不能转换为段落。这个暂时只能像你说的那样重新输入，后面如果这方面需求较多我们再考虑是否改进
2. 是的，Markdown 语法更快捷一些，或者使用斜杆菜单

感谢反馈。
