### ISSUE TITLE
Content block with id [] not found

### ISSUE THREAD

**Issue by sinsiynan** [siyuan-note/siyuan#8280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

My database is large holding many doc's with numerous cross references, embed's 

A heading in one of my documents has 10 references in other documents. All ireferences are lost

Steps 1
1. On the heading right click --> cut (heading)
2. in the same or another document right click --> paste (heading)
3. All 10 references elsewhere in other documents gets lost

Steps 2: 
1. Place cursor to the start of heading
2. BACKSPACE x 2 (in essence moving to previous content block above)

During **copy** / paste the content block ID is lost / not retained.
During backspace x 2 content block ID is lost / not retained

### Expected result

If a heading is cut from a doc and pasted in the same or another doc the block ID should be retained.
Backspace should not cause the content block ID to be lost.

### Version environment

```markdown
- Version: 2.8.7 (also had the issue in prior versions)
- Operating System: Android (on network serving)
- Browser (if used): brave or any other
```

### Log file

  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/05/16 13:14:49 runtime.go:70: kernel is booting:
    * ver [2.8.7]
    * arch [arm64]
    * os [Android 13/SDK 33/WebView 113/Manufacturer Google/Brand google]
    * pid [20036]
    * runtime mode [prod]
    * working directory [/data/user/12/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/05/16 13:14:49 conf.go:107: initialized the specified language [en_US]
I 2023/05/16 13:14:49 conf.go:376: user has disabled [Google Analytics]
I 2023/05/16 13:14:49 runtime.go:124: use network proxy [system]
I 2023/05/16 13:14:49 serve.go:112: kernel [pid=20036] http server [0.0.0.0:6806] is booting
I 2023/05/16 13:14:49 blocktree.go:448: read block tree [25 MB] to [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/blocktree], elapsed [0.18s]
I 2023/05/16 13:14:49 conf.go:682: database size [225 MB], tree/block count [579/66685]
I 2023/05/16 13:14:49 working.go:157: kernel booted
I 2023/05/16 13:14:49 box.go:78: auto stat [trees=579, blocks=66629, dataSize=124 MB, assetsSize=25 MB]
I 2023/05/16 13:14:49 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=56, size=1.1 MB]
W 2023/05/16 13:18:53 transaction.go:118: op tx [4462ms]
I 2023/05/16 13:19:01 database.go:108: reinitialized database [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2023/05/16 13:19:01 index.go:132: rebuilt database for notebook [20220403232726-8mxl2gt] in [0.40s], tree [count=522, size=34 MB]
I 2023/05/16 13:19:01 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.01s], tree [count=56, size=1.1 MB]
I 2023/05/16 13:19:02 index.go:205: resolved refs [126] in [344ms]
I 2023/05/16 13:19:11 queue.go:154: database op tx [8971ms]
I 2023/05/16 13:22:32 database.go:108: reinitialized database [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2023/05/16 13:22:32 index.go:132: rebuilt database for notebook [20220403232726-8mxl2gt] in [0.38s], tree [count=522, size=34 MB]
I 2023/05/16 13:22:32 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.01s], tree [count=56, size=1.1 MB]
I 2023/05/16 13:22:33 index.go:205: resolved refs [126] in [308ms]
I 2023/05/16 13:22:42 queue.go:154: database op tx [8773ms]
I 2023/05/16 13:23:26 database.go:108: reinitialized database [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2023/05/16 13:23:26 index.go:132: rebuilt database for notebook [20220403232726-8mxl2gt] in [0.37s], tree [count=522, size=34 MB]
I 2023/05/16 13:23:26 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.01s], tree [count=56, size=1.1 MB]
I 2023/05/16 13:23:27 index.go:205: resolved refs [127] in [309ms]
I 2023/05/16 13:23:36 queue.go:154: database op tx [8936ms]
I 2023/05/16 13:25:03 queue.go:154: database op tx [10660ms]
I 2023/05/16 13:45:04 queue.go:154: database op tx [10532ms]
I 2023/05/16 13:55:04 queue.go:154: database op tx [10634ms]
I 2023/05/16 14:05:26 queue.go:154: database op tx [28855ms]
I 2023/05/16 15:23:33 working_mobile.go:65: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/05/16 15:23:34 runtime.go:70: kernel is booting:
    * ver [2.8.7]
    * arch [arm64]
    * os [Android 13/SDK 33/WebView 113/Manufacturer Google/Brand google]
    * pid [14111]
    * runtime mode [prod]
    * working directory [/data/user/12/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/05/16 15:23:34 conf.go:107: initialized the specified language [en_US]
I 2023/05/16 15:23:34 conf.go:376: user has disabled [Google Analytics]
I 2023/05/16 15:23:34 runtime.go:124: use network proxy [system]
I 2023/05/16 15:23:34 serve.go:112: kernel [pid=14111] http server [0.0.0.0:6806] is booting
I 2023/05/16 15:23:34 blocktree.go:448: read block tree [24 MB] to [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/blocktree], elapsed [0.20s]
I 2023/05/16 15:23:34 conf.go:682: database size [194 MB], tree/block count [578/65562]
I 2023/05/16 15:23:34 working.go:157: kernel booted
I 2023/05/16 15:23:34 box.go:78: auto stat [trees=578, blocks=65562, dataSize=124 MB, assetsSize=25 MB]
I 2023/05/16 15:23:34 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=56, size=1.1 MB]
I 2023/05/16 16:01:13 working_mobile.go:65: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|
I 2023/05/16 16:01:13 runtime.go:70: kernel is booting:
    * ver [2.8.7]
    * arch [arm64]
    * os [Android 13/SDK 33/WebView 113/Manufacturer Google/Brand google]
    * pid [23661]
    * runtime mode [prod]
    * working directory [/data/user/12/org.b3log.siyuan/files/app/app]
    * read only [false]
    * container [android]
    * database [ver=20220501]
    * workspace directory [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan]
I 2023/05/16 16:01:13 conf.go:107: initialized the specified language [en_US]
I 2023/05/16 16:01:13 conf.go:376: user has disabled [Google Analytics]
I 2023/05/16 16:01:13 runtime.go:124: use network proxy [system]
I 2023/05/16 16:01:13 serve.go:112: kernel [pid=23661] http server [0.0.0.0:6806] is booting
I 2023/05/16 16:01:13 blocktree.go:448: read block tree [24 MB] to [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/blocktree], elapsed [0.15s]
I 2023/05/16 16:01:13 conf.go:682: database size [197 MB], tree/block count [579/65568]
I 2023/05/16 16:01:13 working.go:157: kernel booted
I 2023/05/16 16:01:13 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=56, size=1.1 MB]
I 2023/05/16 16:01:13 box.go:78: auto stat [trees=579, blocks=65538, dataSize=124 MB, assetsSize=25 MB]
I 2023/05/16 16:46:13 database.go:108: reinitialized database [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2023/05/16 16:46:13 index.go:132: rebuilt database for notebook [20220403232726-8mxl2gt] in [0.42s], tree [count=524, size=34 MB]
I 2023/05/16 16:46:13 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=56, size=1.1 MB]
I 2023/05/16 16:46:14 index.go:205: resolved refs [126] in [390ms]
I 2023/05/16 16:46:23 queue.go:154: database op tx [8746ms]
I 2023/05/16 16:51:28 queue.go:154: database op tx [10512ms]
I 2023/05/16 16:51:42 database.go:108: reinitialized database [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2023/05/16 16:51:42 index.go:132: rebuilt database for notebook [20220403232726-8mxl2gt] in [0.61s], tree [count=524, size=34 MB]
I 2023/05/16 16:51:43 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=56, size=1.1 MB]
I 2023/05/16 16:51:45 index.go:205: resolved refs [126] in [435ms]
I 2023/05/16 16:52:00 queue.go:154: database op tx [14871ms]
I 2023/05/16 17:01:28 queue.go:154: database op tx [10601ms]
I 2023/05/16 17:10:22 database.go:108: reinitialized database [/storage/emulated/12/Android/data/org.b3log.siyuan/files/siyuan/temp/siyuan.db]
I 2023/05/16 17:10:22 index.go:132: rebuilt database for notebook [20220403232726-8mxl2gt] in [0.40s], tree [count=525, size=34 MB]
I 2023/05/16 17:10:22 index.go:132: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=56, size=1.1 MB]
I 2023/05/16 17:10:23 index.go:205: resolved refs [127] in [315ms]
I 2023/05/16 17:10:33 queue.go:154: database op tx [8905ms]

### More information

Block ID is retained when:
1. Moving the entire document does not cause content ID's to be lost
2. right click --> MOVE on a heading does not cause heading to be lost, but no control over the placement in the new location

There could be a workaround I am not aware of. 
There is one workaround I know of that **retains** block ID, but its not ideal:
1. On heading - right click --> copy block ref
2. elsewhere - right click paste (block ref)
3. on new block ref - right click --> turn into --> Def block (define block and its children)

This action prompts restart with logo (guessing the rebuild index is initiated). This is not ideal because:
1.undo/redo is lost
2. Works only in one content block per time. In case of multiple content blocks a Super block is required.

**Comment by 88250** [comment]
Hi, as you mentioned in `More info`, cutting and pasting will not keep the ID, if you want to keep it, you need to use <kbd>Move</kbd> or drag to move.

This issue has been discussed before, but the known implementations are difficult to guarantee that IDs will not be duplicated, so it is safer not to keep IDs.

Previous discussion (in Chinese): https://github.com/siyuan-note/siyuan/issues/6807
