### ISSUE TITLE
No more quote font optimization

### ISSUE THREAD

**Issue by michaelbeijer** [siyuan-note/siyuan#8281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

curly quotation marks are being displayed incorrectly in SiYuan. it appears that a space is being inserted, right before or after some of them

### Expected result

~

### Screenshot or screen recording presentation

![curly quotation marks displayed incorrectly](https://github.com/siyuan-note/siyuan/assets/16622240/c0bccc2d-cffc-4324-aac9-a7f7df1f8137)

### Version environment

```markdown
- Version: 2.8.8
- Operating System: Windows 11
- Browser (if used): Chrome
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11489800/siyuan.log)

**Comment by 88250** [comment]
This is due to the impact of this font optimization. We have considered it and will remove this optimization later. Thank you for your feedback.

![image](https://github.com/siyuan-note/siyuan/assets/873584/14c08bf9-0bff-443e-9952-d1bcdd33b1ea)

**Comment by michaelbeijer** [comment]
Great, thanks a lot!
