### ISSUE TITLE
v2.8.8不支持第三方S3对象存储了？certificate: x509: certificate signed by unknown authority (Provider: S3)

### ISSUE THREAD

**Issue by yzengwen** [siyuan-note/siyuan#8284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用自己NAS提供的S3对象存储服务地址，之前版本没有问题，升级2.8.8之后报错。
RequestError: send request failed caused by: Get "https://yzengwen.myqnapcloud.com:8110/": tls: failed to verify certificate: x509: certificate signed by unknown authority (Provider: S3)
请在 [设置 - 云端] 中进行配置

### Expected result

到底支不支持第三方S3

### Version environment

```markdown
- Version: 2.8.8
- Operating System: Windows11
- Browser (if used): Edge
```

### Log file

RequestError: send request failed caused by: Get "https://yzengwen.myqnapcloud.com:8110/": tls: failed to verify certificate: x509: certificate signed by unknown authority (Provider: S3)
请在 [设置 - 云端] 中进行配置

**Comment by 88250** [comment]
支持的，建议排查一下证书是否可用，不可用的话不要用 HTTPS 协议，或者试下跳过证书校验。

**Comment by yzengwen** [comment]
windows客户端仍然可以https，成功使用。web版skip证书校验才能使用第三方S3

**Comment by BoysFight** [comment]
我在v2.9.2遇到类似的问题：x509: certificate signed by unknown authority (Provider: WebDAV)； 用的是阿里云的免费证书，
![image](https://github.com/siyuan-note/siyuan/assets/8340897/2a53f586-d169-4125-8103-a4f046f4af2e)
这个问题是已知的吗？

**Comment by BoysFight** [comment]
我也遇到同样的问题，大佬后来找到原因了吗？

**Comment by yzengwen** [comment]
> 我也遇到同样的问题，大佬后来找到原因了吗？

放弃思源笔记了，小厂出品 后续没有保障 没空劳心劳力的使用 一个笔记而已

**Comment by UvDream** [comment]
> > 我也遇到同样的问题，大佬后来找到原因了吗？
> 
> 放弃思源笔记了，小厂出品 后续没有保障 没空劳心劳力的使用 一个笔记而已

菜鸡不会搞，没人手把手教，所以恼羞成怒了吗？好好反思自己，不用就不用呗，还非要丢下你肮脏的素质，真可悲

**Comment by yzengwen** [comment]
> > > 我也遇到同样的问题，大佬后来找到原因了吗？
> > 
> > 
> > 放弃思源笔记了，小厂出品 后续没有保障 没空劳心劳力的使用 一个笔记而已
> 
> 菜鸡不会搞，没人手把手教，所以恼羞成怒了吗？好好反思自己，不用就不用呗，还非要丢下你肮脏的素质，真可悲

不是每个人都像你一样为了一个工具省点钱每天蝇营狗苟的生活，你的世界里就这一个笔记！你不菜鸡你是腊鸡 垃圾！
不要用你狭隘的格局看待其他所有人，无聊透顶，恶心！

**Comment by UvDream** [comment]
> > > > 我也遇到同样的问题，大佬后来找到原因了吗？
> > > 
> > > 
> > > 放弃思源笔记了，小厂出品 后续没有保障 没空劳心劳力的使用 一个笔记而已
> > 
> > 
> > 菜鸡不会搞，没人手把手教，所以恼羞成怒了吗？好好反思自己，不用就不用呗，还非要丢下你肮脏的素质，真可悲
> 
> 不是每个人都像你一样为了一个工具省点钱每天蝇营狗苟的生活，你的世界里就这一个笔记！你不菜鸡你是腊鸡 垃圾！ 不要用你狭隘的格局看待其他所有人，无聊透顶，恶心！

那么高尚，走了就走了，为啥还要喷一句，是不是你更无聊，更没素质？（我不用思源，我用付费的，就是看不惯你这种狗罢了）自己菜，搞不好，然后恼羞成怒去黑一下别人，不觉得自己可耻吗，难以想象生活中你是什么辣鸡

**Comment by yzengwen** [comment]
> > > > > 我也遇到同样的问题，大佬后来找到原因了吗？
> > > > 
> > > > 
> > > > 放弃思源笔记了，小厂出品 后续没有保障 没空劳心劳力的使用 一个笔记而已
> > > 
> > > 
> > > 菜鸡不会搞，没人手把手教，所以恼羞成怒了吗？好好反思自己，不用就不用呗，还非要丢下你肮脏的素质，真可悲
> > 
> > 
> > 不是每个人都像你一样为了一个工具省点钱每天蝇营狗苟的生活，你的世界里就这一个笔记！你不菜鸡你是腊鸡 垃圾！ 不要用你狭隘的格局看待其他所有人，无聊透顶，恶心！
> 
> 那么高尚，走了就走了，为啥还要喷一句，是不是你更无聊，更没素质？（我不用思源，我用付费的，就是看不惯你这种狗罢了）自己菜，搞不好，然后恼羞成怒去黑一下别人，不觉得自己可耻吗，难以想象生活中你是什么辣鸡

你这种垃圾上来就骂人 跟泼妇骂街有什么区别，还用想象吗？你自己找找镜子就能看到最恶心人的嘴脸。你TM一天有时间去维护思源笔记 你怎么不去解决bug呢 还他妈有脸在这瞎逼逼 给你闲的满嘴放屁
