### ISSUE TITLE
moveBlock API 在移动列表项的时候行为异常

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8286]
### In what scenarios do you need this feature?

当我们正常拖动来移动一个 list item 的时候，移动后的 item 会单独成为一个新的 list

![MoveList-正常](https://github.com/siyuan-note/siyuan/assets/27268127/1fb5fd1a-366c-4871-8c20-ee12601071e8)

但是通过 API moveBlock 来完成移动块的操作的时候，移动后的 list item 还是一个单独的 item，不会成为一个新的 list。下面的案例是在插件中使用了 moveBlock API 后测试的结果，可以发现就是一个孤零零的 item，没有 list。

![MoveList-不正常](https://github.com/siyuan-note/siyuan/assets/27268127/3633d104-62e6-471c-b70c-17aedc64f6f5)

### Describe the optimal solution

希望 moveBlock 在移动 list item 的时候行为可以和手动移动保持一致。

**Comment by 88250** [comment]
需要自己创建列表，然后再把它移动进去。
