### ISSUE TITLE
Parse exceptions when copying and pasting hyperlink whose address contains `"`

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#8290]
复制地址含有 `"` 的超链接后粘贴时会解析异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复现过程
1. 插入一个超链接, 链接地址为 `http://foo "bar"`, 链接锚文本为 `123`, 链接标题为 `baz`  
   ![image](https://github.com/siyuan-note/siyuan/assets/49649786/a9ce0d9a-d8f9-4bef-bb0f-c803e4ee6cba)
2. 复制该超链接, 剪贴板内文本为 `[123](http://foo "bar" "baz")`, 可以发现, 链接中的空格与 `"` 未转义
3. 粘贴刚刚复制的超链接, DOM 会暴露, 应该是因为 `"` 未转义的缘故  
   ![image](https://github.com/siyuan-note/siyuan/assets/49649786/333d5e43-b7de-4985-8d0b-396c2484c886)

注: 使用 API 插入如下样式的超链接也无法正常插入, 第一个 `"` 后面的内容会丢失
```markdown
[123](<http://foo "bar" baz>)
```
![image](https://github.com/siyuan-note/siyuan/assets/49649786/047a9c3e-ede4-47e1-a387-1fb70377be06)

### Expected result

方案1: 复制超链接时对超链接地址进行 URI 编码, 粘贴超链接后对超链接地址进行 URI 解码
方案2: 粘贴超链接生成 `<span>` 标签时转义超链接地址中的 `"`

### Version environment

```markdown
- Version: 2.8.8
- Operating System: 
- Browser (if used):
```

### Log file

无有效信息输出

**Comment by 88250** [comment]
[12&quot;3](http://foo.com/bar&amp;quot;baz "45&amp;quot;6")
