### ISSUE TITLE
建议参考Taio优化移动端的菜单栏

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8291]
### In what scenarios do you need this feature?

Taio移动端的菜单栏和交互非常优秀，希望开发者可以看看Taio的设计，优化思源的菜单栏。

### Describe the optimal solution

Taio是纯md编辑器，所以有非常易用的md语法常有符号快捷按键。
例如

- Taio菜单栏有专门一个#号按钮，可以在一至六级标题和正文中循环切换，这个设计实际编辑的时候非常舒适。
- 文本样式面板使用宫格替代键盘，直观且易操作，目前思源滑动菜单太小了，无法显示全部内容，小屏手机按起来比较不容易。
![IMG_0902](https://github.com/siyuan-note/siyuan/assets/57566668/f730ef09-05c5-4f3f-91bb-7ba789058b31)

- 斜杠菜单不理解为什么砍掉，保留斜杠命令在移动端能快速完成操作，也和电脑端的操作体验更统一。Taio的设计是斜杠呼出浮动一级菜单，然后进行更多操作，思源只有一个块标菜单，占用了全屏，容易不确定操作的是哪一个块，在手机上菜单栏也太复杂了。
![IMG_0900](https://github.com/siyuan-note/siyuan/assets/57566668/c1d42303-241b-4fbe-b78c-2437308e30a6)
![IMG_0901](https://github.com/siyuan-note/siyuan/assets/57566668/9fb655d1-1272-4525-89aa-a25ba5d5c8a0)

### Describe the candidate solution

演示视频压缩得比较小

https://github.com/siyuan-note/siyuan/assets/57566668/770a1d32-405e-4007-b168-70d70ed7e4de

**Comment by 88250** [comment]
确实有一些值得借鉴的地方，但是 Markdown 文本编辑器和块风格编辑器在交互逻辑上还是有一些不同的，我们主要参考 Notion 进行设计，后续会逐步改进细节，感谢反馈。
