### ISSUE TITLE
The appimage sha256 hash does not exist on SHA256SUMS.txt.

### ISSUE THREAD

**Issue by Cyber-Syntax** [siyuan-note/siyuan#8292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

There is only apk sha256 hash in SHA256SUMS.txt.

### Expected result

appimage sha256 hash

### Version environment

```markdown
- Version: 2.8.8
- Operating System: 
- Browser (if used):
```

### Log file

I thing, there is no need for that.

**Comment by 88250** [comment]
Thanks for the feedback, the file has just been re-uploaded.
