### ISSUE TITLE
Freeze top row of tables (like in Excel)?

### ISSUE THREAD

**Issue by michaelbeijer** [siyuan-note/siyuan#8294]
### In what scenarios do you need this feature?

I intend to keep a very large number of bilingual and multilingual glossaries in SiYuan, and when searching for terms in my work as a patent translator, it would be super-useful to have the top row of the table frozen, so I don't have to scroll all the way up to the top to see the column headers/titles. 

### Describe the optimal solution

Basically, an optional setting to Freeze top row of tables. 

![Freeze top row of tables (like in Excel)](https://github.com/siyuan-note/siyuan/assets/16622240/bc1d3168-2e65-4f96-8c1d-4627319cc9b0)

**Comment by royc01** [comment]
冻结首行优化建议：
1. 表头改个样式
![1](https://github.com/siyuan-note/siyuan/assets/38906705/d6661b16-0939-49f2-bd9c-3a700d8ee127)
2. height: 50vh改为max-height，不然删除行后下方会空出一部分。
