### ISSUE TITLE
关于重启onedrive同步的提议

### ISSUE THREAD

**Issue by DionathanJostar** [siyuan-note/siyuan#8295]
### In what scenarios do you need this feature?

今日意外发现纯纯笔记可以通过onedrive实现同步，刷新了我的认知，让我知道通过onedrive同步并不是不能实现的功能。
思源的各项功能都比纯纯复杂，我相信既然纯纯能做到，那之前在技术层面上思源应该也能够实现。

### Describe the optimal solution

我们大家都知道onedrive对用户来说容量大空间价格便宜，对思源来说更多人会选择第三方同步意味着降低服务器成本。这终将是是一个winwin的结果。

### Describe the candidate solution

请参考纯纯
![Screenshot_20230518_061655](https://github.com/siyuan-note/siyuan/assets/133741096/56d020f1-f06c-4891-b5d8-a3345ef090bf)

**Comment by Aiviokoo** [comment]
感觉应该不行，可能是同步机制的问题吧，看看D大有什么办法没（估计悬）。
如果onedrive可以的话，我也希望可以像有些软件一样可以适配国内的云盘，像百度网盘，阿里云盘这些。（后话了，不是很报希望，随口一说）
![Screenshot_2023-05-18-07-43-07-660_com.newskyer.draw.jpg](https://github.com/siyuan-note/siyuan/assets/87182333/03ef80e2-ae60-47f5-8148-fee4ef93abbe)

![Screenshot_2023-05-18-07-42-57-086_com.newskyer.draw.jpg](https://github.com/siyuan-note/siyuan/assets/87182333/3674cfcd-40fb-41b3-802e-bf7ec7a49cbd)

**Comment by 88250** [comment]
通过 OneDrive 的接口可能可以实现，但是考虑到 OD 在国内网络可用性的问题目前就不考虑接入了，社区中如果有开发者帮忙尝试可以试下通过扩展 https://github.com/siyuan-note/dejavu 进行实现，感谢提议。
