### ISSUE TITLE
Inbox enhancement: editor mode, arbitrary move

### ISSUE THREAD

**Issue by littlecoby** [siyuan-note/siyuan#8296]
### In what scenarios do you need this feature?

In many cases, I'd send a few random messages to the inbox, then organize via selection/copy/paste of part of the text in the inbox item. Text selection and copy was supported in previous versions, but somehow lost since maybe v.2.8.7. In the current version (v2.8.8), I have to first move the inbox item to a notebook, edit, then delete the item, which is not convenient.

My first thought was to bring the text selection feature back. But on a second thought, why not make the inbox an editor, like the backlink panel. Editor mode would be much more powerful than text selection.

### Describe the optimal solution

Two features would greatly enhance the inbox:
(1) Inbox panel supports editor mode, just like the backlink panel. 
(2) Inbox item can be moved to an arbitrary location, just like moving an ordinary document (facilitated by a popup menu).

**Comment by 88250** [comment]
Hello, it is the design intention that the inbox cannot be edited. The inbox is only responsible for collecting data, and the processing and arrangement of data is unified in the notebook document.

**Comment by littlecoby** [comment]
> Hello, it is the design intention that the inbox cannot be edited. The inbox is only responsible for collecting data, and the processing and arrangement of data is unified in the notebook document.

I see. 
How about bringing back the text selection feature as in previous versions?
Will it support moving to an arbitrary location (others may have raised this issue before)? Currently the moving has to be done in two steps (inbox->notebook->destination).
