### ISSUE TITLE
Add editor font size scroll zoom switch

### ISSUE THREAD

**Issue by littlecoby** [siyuan-note/siyuan#8297]
Improve zooming experience: unintentional zooms (especially with touchpads)

### In what scenarios do you need this feature?

Currently (v2.8.8) two types of zooming are supported, the overall scaling via ctrl++/- and the editor font size via ctrl+mouse wheel. These features are convenient, in the meantime they also increase the probability of unintentional zooms, which can sometimes be annoying. Two candidate strategies are: reducing the probability of unintentional operations by design, and/or enable easy reversion of the zoom change.

The overall zooming is ok, since ctrl++/- is an infrequently-used combination, zoom change can be counted along with button pressing, and rescue can be easily done via ctrl+0. The newly introduced top bar button also helps (#8212).

The font size zooming is less ok, especially on laptop with touchpads. Both the mouse wheel/touchpad and the ctrl are highly frequently used, zoom change is harder to know by the exact amount of scrolling, and rescue is inconvient (Settings > Editor > Font Size). I've encountered several unintentional zooms in a few days since the introduction of this feature in v2.8.8 (#8064).

### Describe the optimal solution

A sensible improvement to the font size zooming is that, the zooming is **restricted to one-way** so that the font size can only be scaled up, but not scaled down. This restriction is seen on pinching on pads, where pinching in zooms in, pinching out zooms out, but only to the scale before zooming. Zoom change can be easily reverted by pinching out to the extreme.

Although there is no 'original font size' (#8064), the one set in the Settings can be viewed as the most frequently used size, and zooming is only **temporary**. In such scenario, zooming in but not zooming out is perhaps the more frequent demand. As a result, restriction to one-way zooming is reasonable.

Another solution along the lines of #8212 is to add a popup indicator of the current zoom level (in %) and the font size to the top bar, which helps knowing the current zoom level and reverting the change. Below is an example of the Edge browser.
![image](https://github.com/siyuan-note/siyuan/assets/27865589/a503109d-c995-4fbc-a7bc-a5451b1d8365)

**Comment by 88250** [comment]
We will add a switch for this feature, thanks for your feedback.

**Comment by littlecoby** [comment]
Is it possible to let the users customize the shortcuts for both the overall scaling and the font size zooming? Maybe something like this draft image.
![image](https://github.com/siyuan-note/siyuan/assets/27865589/cc75d889-4632-4e89-9c4a-ab7d70509dec)

Based on the two observations below, I personally would set ctrl++/- for font size zooming. Customizability would meet diverse demands. 
(1) It seems that font size zooming is more commonly used (e.g. Edge, WPS) than the overall scaling (e.g. VSCode). 
As for SiYuan, I guess the font size zooming would be more useful, because then I could zoom out to get an overview of long documents. (VSCode has a minimap, which offers an overview)
(2) From my experience and [this post](https://ld246.com/article/1684582782775), ctrl+touchpad sliding causes unintentional touches somewhat easily. I have not noticed such misoperations from using other apps before, which is perhaps due to the lighter use of ctrl in those apps than in SiYuan.

**Comment by littlecoby** [comment]
Or using a dropdown menu to be consistent with the style in settings.
![image](https://github.com/siyuan-note/siyuan/assets/27865589/47ab4399-e586-4f1b-ba22-ae4ac1f9022b)

**Comment by 88250** [comment]
After thinking about it, from the perspective of being based on the browser, it is more common to use Ctrl+- as the global scaling, and using the mouse+wheel to scale in the editor font size is also in line with the habits of most people.

The main usage scenario of global scaling is to scale the overall appearance on high-resolution screens.

Still keep the original design unchanged, thanks for the feedback.

**Comment by Shawnkurt** [comment]
> After thinking about it, from the perspective of being based on the browser, it is more common to use Ctrl+- as the global scaling, and using the mouse+wheel to scale in the editor font size is also in line with the habits of most people.
> 
> The main usage scenario of global scaling is to scale the overall appearance on high-resolution screens.
> 
> Still keep the original design unchanged, thanks for the feedback.

Searched for "minimap" in issues and found this thread. Is it possible to add a minimap to Siyuan's editor? Minimap is a common feature in popular IDEs and could be helpful in Siyuan as well. Just saying :)
