### ISSUE TITLE
如何做到批量更改字体格式？

### ISSUE THREAD

**Issue by DreamsCat** [siyuan-note/siyuan#8298]
### In what scenarios do you need this feature?

如何做到批量去除粗体？
我现在有很多段内容块在一个文档内，我没找到可以批量设置如字体格式，大小，更改粗体等，我还要一段一段去进行调整，非常麻烦

**Comment by 88250** [comment]
目前做不到，不支持跨块选择操作行级文本。

后续如果需求较多我们会考虑重开这个提议，谢谢。

**Comment by Aiviokoo** [comment]
我也想要支持跨块选择操作行级文本，有时候想批量删除一些样式（比如高亮，颜色，粗细等），没有确实不太方便，虽然我可以通过复制出去再复制回来，但是这样有点割裂也不太方便。

**Comment by DreamsCat** [comment]
确实，这个需求其他编辑器基本都能实现

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/8554 中跟进。
