### ISSUE TITLE
不知道怎么关闭自动弹出的悬浮窗（找了很久没找着设置项）

### ISSUE THREAD

**Issue by moroal** [siyuan-note/siyuan#8300]
### In what scenarios do you need this feature?

喜欢极简风格，不喜欢频繁弹窗
![image](https://github.com/siyuan-note/siyuan/assets/14798296/af473791-17db-4741-a196-094d023720b0)

### Describe the optimal solution

希望提供关闭选项

**Comment by 88250** [comment]
这个无法关闭，抱歉了。

**Comment by moroal** [comment]
主要是编辑区域，提示的太多了，相比起来幕布就比较简洁舒服（只是个体验建议哈，希望采纳）

**Comment by 88250** [comment]
不提示多一点很多人不会用，所以还是保留好一些，谢谢。

**Comment by moroal** [comment]
对于小白确实蛮好，我刚用的时候帮助我了解了快捷键。但是我习惯了之后，总觉得会打扰我的思考

**Comment by 88250** [comment]
我不确定用自定义主题或者代码片段能否关闭，可以加群咨询一下其他用户。

**Comment by moroal** [comment]
多谢大佬

**Comment by moroal** [comment]
大佬，群怎么加来着，麻烦指导下

**Comment by 88250** [comment]
https://ld246.com/article/1640266171309
