### ISSUE TITLE
D大可以增加多行选中转化为代码的功能吗

### ISSUE THREAD

**Issue by kindfaker** [siyuan-note/siyuan#8301]
### In what scenarios do you need this feature?

最近在做笔记迁移，有些代码导入思源之后显示为普通文本，我想要转为代码块。发现快捷方式不可用，只能将一段代码转化为代码块。
同时有些应该是文本但是识别为了代码块，我也只能粘贴纯文本出来。很不方便
![image](https://github.com/siyuan-note/siyuan/assets/133951019/9a6db6ad-c0a8-4fe0-9255-3d79b2b50f08)

### Describe the optimal solution

希望D大考虑给代码块加一个逆向操作的功能，我使用过的许多笔记软件都有这个功能

**Comment by 88250** [comment]
先创建代码块，然后再粘贴吧。否则即使能转换，效果也不会好。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
