### ISSUE TITLE
希望支持将每一个导入的资源都放在已引用中（通过导入插件导入epub时）

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8303]
### In what scenarios do you need this feature?

使用导入插件导入epub格式的书籍后，里面的图片会被放在未引用资源里，容易被误删除。
经过咨询插件开发大大，应该是思源后端的限制难以解决，希望D大能告知相应的办法，谢谢。

### Describe the optimal solution

希望能够解除后端限制，使插件开发大大能检测到资源引用情况。

### Describe the candidate solution

或者官方直接提供支持。

### Other information

![image](https://github.com/siyuan-note/siyuan/assets/87182333/ae958956-77e8-4e0e-b68d-024d287a5f1d)
![image](https://github.com/siyuan-note/siyuan/assets/87182333/eea31d5b-63d7-42f5-84dc-91ab68a412ff)
![image](https://github.com/siyuan-note/siyuan/assets/87182333/1f437f96-bd45-4408-97c0-bac38190e1c8)

**Comment by terwer** [comment]
文档是通过 https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E9%80%9A%E8%BF%87-markdown-%E5%88%9B%E5%BB%BA%E6%96%87%E6%A1%A3 这个API创建的

**Comment by 88250** [comment]
@terwer 使用截图的导入是会处理将 md 中的相对路径地址转换为 assets 的。

**Comment by 88250** [comment]
我先关闭了，后续在开发群中跟进。
