### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by DionathanJostar** [siyuan-note/siyuan#8304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Appeared on and off a few times. After a period of standby in the background of the software (not the lower right corner, but the taskbar), the following situation will occur, the cross in the upper right corner is red, and the whole software is unresponsive. The cause is unknown and cannot be reproduced. After all, you can't keep a computer and so on every day.
![1](https://github.com/siyuan-note/siyuan/assets/133741096/5a5509bc-b322-43bd-ae4f-564a7b1db340)

https://github.com/siyuan-note/siyuan/assets/133741096/3a54d344-adbd-48c5-8cfc-af9a6d1be7cb

### Expected result

repair it

### Version environment

```markdown
- Version: 2.8.8
- Operating System:win10 
- Browser (if used):
```

### Log file

before Alt + F4:[siyuan.log](https://github.com/siyuan-note/siyuan/files/11509261/siyuan.log)
AFTER Alt + F4:[siyuan.log](https://github.com/siyuan-note/siyuan/files/11509264/siyuan.log)

**Comment by 88250** [comment]
Please try rebuilding the index.

**Comment by DionathanJostar** [comment]
> Please try rebuilding the index.

have you ever seen my radio？the soft do not work ?how to  rebuilding the index?

**Comment by DionathanJostar** [comment]
> Please try rebuilding the index.

我不管什么逼格了。这个问题最早出现在2.8.6，到昨天2.8.8都有出现。出现问题的时候整个软件界面是不能进行任何操作的，甚至右上角关闭按钮都是固定红色不能点。（如上文）
群友说重建索引指的是关闭软件重建索引，不过问题出现的原因是固定的：
![image](https://github.com/siyuan-note/siyuan/assets/133741096/abcbf99b-ccfb-4c07-86d2-4017d284fc6f)
就像这样在后台呆一段时间后，有可能会出现，我这里到现在出现过3次。因此我认为这不是重建索引的问题，而就是一个固定的bug。

**Comment by 88250** [comment]
> 而就是一个固定的bug

我这里无法重现，麻烦提供重现步骤。

**Comment by DionathanJostar** [comment]
> > 而就是一个固定的bug
> 
> 我这里无法重现，麻烦提供重现步骤。

无法稳定复现，否则我就不会提供这么多数据了。光日志就提供了两份。

**Comment by 88250** [comment]
呃，那你怎么说是个固定的 bug 呢？另外，日志中我没有发现相关问题，所以没有办法帮助你了，抱歉。

**Comment by 88250** [comment]
如果后续你那边有进一步反馈，请在这个帖子里面跟帖反馈，不要开新的 issue，谢谢。

**Comment by DionathanJostar** [comment]
> > 而就是一个固定的bug
> 
> 我这里无法重现，麻烦提供重现步骤。

说明一下，鼠标在移动过程中是不断点击的，并不是单纯的移动。
之所以说是固定bug，是因为我从大概2.8.6开始回归用思源到2.8.8，昨天遇到了大概第3次。日志里如果没有迹象就算了。等我在研究研究把。

**Comment by DionathanJostar** [comment]
> 如果后续你那边有进一步反馈，请在这个帖子里面跟帖反馈，不要开新的 issue，谢谢。

我发新帖是因为，我没有用过github，我以为帖子关了你就收不到回复了。如往后知道了就不会开新贴了。

**Comment by DionathanJostar** [comment]
> 如果后续你那边有进一步反馈，请在这个帖子里面跟帖反馈，不要开新的 issue，谢谢。



> 说明一下，视频中鼠标在移动过程中是不断点击的，并不是单纯的移动。

哦对了，出现这3次的这段时间，我的系统版本也从win11跳到了win10,而我的电脑是联想拯救者Y7000（好像有个P)，买的时候大概8000左右，所以也不应该是电脑本身或者系统的问题。就只可能是软件自身的问题了。

**Comment by 88250** [comment]
另外，报告 bug 请认真一些，否则开发者会花更多时间在上面排查问题上，这对产品和你都是没有帮助的。

* Issue 标题请明确，不要连标题都懒得写
* 对于 bug，请给出重现步骤，最好是能够在新的工作空间中重现
* 确保 issue 模板中的前置条件已经完成，比如要能够在默认主题下重现，排除扩展影响等

一般来说，只要能重现的 bug 我们会尽力解决，即使不能解决我们也会说明原因。

**Comment by DionathanJostar** [comment]
> 另外，报告 bug 请认真一些，否则开发者会花更多时间在排查问题上，并且大概率无法得到任何有用的结论，这对产品和你都是没有帮助的。
> 
> * Issue 标题请明确，不要连标题都懒得写
> * 对于 bug，请给出重现步骤，最好是能够在新的工作空间中重现
> * 确保 issue 模板中的前置条件已经完成，比如要能够在默认主题下重现，排除扩展影响等
> 
> 一般来说，只要能重现的 bug 我们会尽力解决，即使不能解决我们也会说明原因。

标题是我的失误，我直到第二天才发现这标题怎么是英文的。读过之后才发现哦原来忘了写标题了。
以下是我和群里人讨论的截图。
![image](https://github.com/siyuan-note/siyuan/assets/133741096/b4196ae7-c566-4961-a1cd-bcd612449ac8)
不过真的不能重现，我对于反馈bug还是清楚的，但凡能的，我都尽量做到重现了。参照以下帖子https://ld246.com/article/1683695725888
我只能说，反馈bug我只能做到这一步。我不是it人士，也不是相关人士。我对bug的认知只停留在重复操作上，看日志什么的我是一概不懂的。但是这个bug一是时间跨度长，二是出现随机。让我复现。。。

**Comment by DionathanJostar** [comment]
> 另外，报告 bug 请认真一些，否则开发者会花更多时间在排查问题上，并且大概率无法得到任何有用的结论，这对产品和你都是没有帮助的。
> 
> * Issue 标题请明确，不要连标题都懒得写
> * 对于 bug，请给出重现步骤，最好是能够在新的工作空间中重现
> * 确保 issue 模板中的前置条件已经完成，比如要能够在默认主题下重现，排除扩展影响等
> 
> 一般来说，只要能重现的 bug 我们会尽力解决，即使不能解决我们也会说明原因。

标题是我的失误，我直到第二天才发现这标题怎么是英文的。读过之后才发现哦原来忘了写标题了。
以下是我和群里人讨论的截图。
![image](https://github.com/siyuan-note/siyuan/assets/133741096/b4196ae7-c566-4961-a1cd-bcd612449ac8)
不过真的不能重现，我对于反馈bug还是清楚的，但凡能的，我都尽量做到重现了。参照以下帖子https://ld246.com/article/1683695725888
我只能说，反馈bug我只能做到这一步。我不是it人士，也不是相关人士。我对bug的认知只停留在重复操作上，看日志什么的我是一概不懂的。但是这个bug一是时间跨度长，二是出现随机。让我复现。。。

**Comment by 88250** [comment]
对于这个 issue，日志上面无法确认问题的，后续如果有其他信息补充随时欢迎。

**Comment by DionathanJostar** [comment]
> 对于这个 issue，日志上面无法确认问题的，后续如果有其他信息欢迎随时补充。

行，等我再遇到我多研究一下，有条件的话，时候直接联系你远程操作，你自己来看怎么找问题在哪。

**Comment by 88250** [comment]
远程的话没有开发环境我也无法定位问题，如果可能的话，请制作一个能够重现问题的最小数据集发送给我们 845765@qq.com
