### ISSUE TITLE
Please be patient through each issue

### ISSUE THREAD

**Issue by DionathanJostar** [siyuan-note/siyuan#8307]
### In what scenarios do you need this feature?

When I feedback issue

### Describe the optimal solution

D, you close the issue too quickly, and don't even give people time to communicate. Yesterday's issue, there are detailed symptoms in the video I posted, which can not be solved by rebuilding the index at all, because the window of the entire software is stuck, nothing can be operated, nothing can be moved, and the only operation that can be done is to close the software in the lower right corner.

**Comment by 88250** [comment]
Please do not submit the same question repeatedly. If you have new discoveries, you can follow up on the original issue, thank you.
