### ISSUE TITLE
LLM enhanced full text searching

### ISSUE THREAD

**Issue by ttimasdf** [siyuan-note/siyuan#8308]
### In what scenarios do you need this feature?

Searching is a thing for personal knowledge base. It get more complicated when we put tons of things like, code snippets, fast notes, links, web clips, everything into a document tree. And any single piece of knowledge may be expressed in multiple ways. Especially when notes are taken in multiple languages. That makes it hard to find everything around a given topic through conventional keyword search.

This idea comes when I was trying to recall a python package called `click`. I forget its name and only remember it's an alternative to python standard library `argparse`. I put a lot of effort using multiple keywords to finally find what I was looking for.

So, why don't we just ask like a boss?

### Describe the optimal solution

The new feature could be implemented as a new _Search Method_, like, when I search for `argparse alternative`, it would return all the related content in the database.

The database may need to be indexed or pre-trained in a specific ways to match the context limit of LLM models. Like, using text embeddings to generate a vectorized representation of database.

An example to use GPT4 to query a document [mayooear/gpt4-pdf-chatbot-langchain: GPT4 & LangChain Chatbot for large PDF docs](https://github.com/mayooear/gpt4-pdf-chatbot-langchain)

An example to query a notion database [hwchase17/notion-qa](https://github.com/hwchase17/notion-qa)

### Describe the candidate solution

1. It may also be implemented in a way when I search for `argparse alternative`, LLM engine generate multiple keywords that may related for my intent and do a conventional keyword search for all of the keywords.
2. It could be a paid subscription service because in the projects I mentioned as example above use hosted AI and vector database services. Offline or self-hosted alternatives may require more development resources

**Comment by 88250** [comment]
That's a good suggestion, especially the "So, why don't we just ask like a boss?" that impresses me 👍

**Comment by 88250** [comment]
Perhaps through a plugin, natural language can be converted into keywords through AI, and then filled in the search box. This is an easier solution I can think of.

For the time being, let's put it in Idea first, and see if there are community developers willing to contribute to the implementation, thanks.
