### ISSUE TITLE
搜索中的类型过滤失效

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#831]
# 文档块

![image](https://user-images.githubusercontent.com/32661922/103125350-c6a2ed00-46c5-11eb-8f19-a93a85ca5569.png)

# 标题块

![image](https://user-images.githubusercontent.com/32661922/103125250-71ff7200-46c5-11eb-8e72-bf616523b0ec.png)

**Comment by 88250** [comment]
你好，类型条件请使用 `编辑器 AND type:d`（AND 可以省略）。

在 https://github.com/siyuan-note/siyuan/issues/835 中会对类型条件进行进一步简化：`胃口 type:h` 可以简化作 `h:胃口`，谢谢。

**Comment by deerainw** [comment]
不是写法的问题吧，我按照上面那种写法，不能搜出 `编辑器.md` 这个文档，别的文档也一样：

![image](https://user-images.githubusercontent.com/32661922/103130832-48e8dc80-46d9-11eb-8f09-0aaa9daec47f.png)
