### ISSUE TITLE
无全选笔记内容功能

### ISSUE THREAD

**Issue by lululu0515** [siyuan-note/siyuan#8310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

笔记内容界面没有提供全选功能吗，试了ctrl+a ，ctrl+shift+a快捷键都不能全选，也没有看到类似复制全文的按钮，
现在如果想复制笔记的全部内容，只能通过导出的方式，然后再打开文件全选十分不方便，

### Expected result

提供快捷键全选，或者新增全选按钮

### Version environment

```markdown
- Version: 2.8.8
- Operating System: centos
- Browser (if used):chrome
```

### Log file

无

**Comment by 88250** [comment]
如果是为了整篇复制的话建议用导出，或者切换到导出预览模式。

另外，在没有动态加载的情况下，可以试下两次 Ctrl+A，这个可以全选当前已经加载的内容。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by terwer** [comment]
哇哦。get 两次 Ctrl+A 彩蛋。以前竟然不知道。好用。
