### ISSUE TITLE
关于siyuan的代理设置提议:能否让ai部分默认走代理?

### ISSUE THREAD

**Issue by a15355447898a** [siyuan-note/siyuan#8313]
### In what scenarios do you need this feature?

我之前一直无法使用ai功能,阅读日记提示连接超时,但是我明明已经使用了软路由,理论上不应该遇到这种问题

软路由设置如下

<img width="725" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/b6bc0733-0774-41db-9e43-2b495f54a894">

最近在设置"SOCKS5 代理服务端（全局）"后,在siyuan的ai设置,代理部分使用了这个端口,ai部分才工作正常

<img width="569" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/7b4c52ec-f583-44d2-a994-42c05cfebc3f">

<img width="963" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/24158735-476f-4144-8482-114cf7b83cef">

在siyuan相关的qq群询问过后发现有好几个人在此遇到了相同的问题

<img width="415" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/ab6e6bb6-8182-4fac-b2ed-e9a326a92f75">

<img width="376" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/c5474800-ed34-4dfe-b333-470fbe526da2">

### Describe the optimal solution

请让ai部分的api请求默认走代理,以减少相关使用者的迷惑

**Comment by 88250** [comment]
从代码上看默认使用的不设置代理的 HTTP 客户端，只有指定了 ai 里的代理后才会走这个代理。

![image](https://github.com/siyuan-note/siyuan/assets/873584/b235d061-e265-43be-b133-720ef10a92c1)

还有个地方需要确认下，就是 设置 - 关于 - 网络代理 这里你是否配置过，这里如果选择 直链 的话默认应该就是走的系统的网络，如果配置了其他代理的话整个程序的 HTTP 客户端就会走这个代理。

**Comment by a15355447898a** [comment]
> 从代码上看默认使用的不设置代理的 HTTP 客户端，只有指定了 ai 里的代理后才会走这个代理。
> 
> ![image](https://user-images.githubusercontent.com/873584/239555221-b235d061-e265-43be-b133-720ef10a92c1.png)
> 
> 还有个地方需要确认下，就是 设置 - 关于 - 网络代理 这里你是否配置过，这里如果选择 直链 的话默认应该就是走的系统的网络，如果配置了其他代理的话整个程序的 HTTP 客户端就会走这个代理。

默认设置是"直链"

<img width="760" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/f9260bbe-ddc2-456f-84b5-9f99d190e58c">

但是为什么不走软路由的代理就非常让人迷惑

**Comment by 88250** [comment]
你那里能搭建 SiYuan 的开发环境吗？能的话帮忙调试看看，或者试下用其他 HTTP 客户端工具测试一下是不是软路由配置问题。

**Comment by a15355447898a** [comment]
手头没有siyuan的开发环境,抱歉只能用其他工具测试了

使用`Curl`进行测试(api和请求的网站都因为隐私原因隐藏了,设置的和上图的siyuan是一样的)
(另,我就是5月17号发邮件说遇到ai功能超时的人,源代码已经在回复的邮件里面了)

```bash
#!/bin/bash
OPENAI_API_KEY="sk-0PfcATp5ka2a"
curl https:/xxxxx/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [{"role": "user", "content": "Hello!"}]
  }'
```

返回值

```
{"id":"chatcmpl-7H3B6se4H9UpRuIvOOPKbVYRUCVTF","object":"chat.completion","created":1684298148,"model":"gpt-3.5-turbo-0301","choices":[{"index":0,"delta":null,"message":{"role":"assistant","content":"Hello there! How can I assist you today?"},"finish_reason":"stop"}],"usage":{"prompt_tokens":10,"completion_tokens":10,"total_tokens":20}}⏎
```

测试出来软路由配置应该是正常的

使用其他软件测试也正常(这软件没有单独设置代理)

<img width="502" alt="image" src="https://github.com/siyuan-note/siyuan/assets/62456287/205b8e1e-4ae4-42bb-8b44-2dda5648c586">

**Comment by 88250** [comment]
环境变量配置过 `HTTPS_PROXY`/`HTTP_PROXY` 吗？

**Comment by 88250** [comment]
你那里有 golang 的开发环境吗？

**Comment by a15355447898a** [comment]
> 你那里有 golang 的开发环境吗？

没有,我不会go

这个问题D大这里不能复现吗

**Comment by a15355447898a** [comment]
> 我没有全局代理软件……

https://github.com/Fndroid/clash_for_windows_pkg/tags

**Comment by a15355447898a** [comment]
> Clash 要搭服务端的吧？我这里没有时间搭建哦。
> 
> 刚刚写了个简单的测试程序麻烦你试下看看：
> 
> ```
> ./hello -key="sk-xxx" -baseURL="https://xxx/v1" -msg="Hello"
> ```
> 
> [hello.zip](https://github.com/siyuan-note/siyuan/files/11518225/hello.zip)

D大,请问可以编译一份linux版本的吗

**Comment by 88250** [comment]
我这里只能编译出 amd64 平台的：

[hello.tar.gz](https://github.com/siyuan-note/siyuan/files/11522802/hello.tar.gz)

**Comment by a15355447898a** [comment]
> 我这里只能编译出 amd64 平台的：
> 
> [hello.tar.gz](https://github.com/siyuan-note/siyuan/files/11522802/hello.tar.gz)

返回值:

```
2023/05/21 08:13:18 resp: {ID:chatcmpl-7IQzFLhAdTlcKgPuFiEU1opbuKHAb Object:chat.completion Created:1684627997 Model:gpt-3.5-turbo-0301 Choices:[{Index:0 Message:{Role:assistant Content:Hello! How can I assist you today? Name:} FinishReason:stop}] Usage:{PromptTokens:9 CompletionTokens:9 TotalTokens:18}}
```

看起来运行正常

**Comment by 88250** [comment]
麻烦把 key、proxy 和 baseurl 等参数发送给我调试看看 845765@qq.com

**Comment by 88250** [comment]
已经通过邮件沟通，暂时先关闭吧，谢谢。

问题的原因有可能是全局代理配置启用/禁用前网络连接还在保持，所以可能会导致不一致的测试结果。另外，也可能是代理软件配置问题，但是这些都只是猜测。
