### ISSUE TITLE
LDAP user authentication?

### ISSUE THREAD

**Issue by mxmilkiib** [siyuan-note/siyuan#8314]
### In what scenarios do you need this feature?

For SiYuan to be hosted in the YunoHost turnkey private cloud groupware distro.

https://yunohost.org/
https://github.com/YunoHost

### Describe the optimal solution

SiYuan to appear available through https://yunohost.org/#/apps / https://github.com/YunoHost/apps

### Describe the candidate solution

https://yunohost.org/en/packaging_apps_intro

### Other information

Thank you.

**Comment by 88250** [comment]
Sorry, this proposal deviates from the current work direction. SiYuan is mainly a personal knowledge management tool that runs locally. If you want to host it in the cloud, you can use Docker to deploy it. It is recommended to do the auth externally.
