### ISSUE TITLE
D大是否考虑为pdf增加插入文本框等编辑功能

### ISSUE THREAD

**Issue by nuistZPZ** [siyuan-note/siyuan#8316]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/103711400/92061fb7-e29c-444d-9d21-88a07217bff5)
我在使用思源做题并记笔记的同时发现思源没有编辑PDF的能力，我的需求也很简单，能插入一个单词，表明我选了哪个选项即可

### Describe the optimal solution

插入文本框或者画笔功能

**Comment by 88250** [comment]
不考虑了，之前有讨论。

* https://github.com/siyuan-note/siyuan/issues/5192
* https://github.com/siyuan-note/siyuan/issues/3359
