### ISSUE TITLE
粘贴zotero标注时不出现可点击的zotero链接

### ISSUE THREAD

**Issue by freezingbz** [siyuan-note/siyuan#8317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

一直很喜欢思源的一点是ctrl+v复制zotero中pdf的标注后，可以用ctrl+shift+v在思源中粘贴出可点击跳转到该标注的链接。最近升级到2.8.8后该功能失效了（升级前是2.8.3还是2.8.4？）。想麻烦大大修复一下该功能，非常感谢！

### Expected result

同上

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
试试使用 Ctrl+K 粘贴超链接。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by freezingbz** [comment]
谢谢大大回复。试了下您的方法，是可以的，需要一些操作。
例如从zotero中直接ctrl+C复制下来的链接会是这样的：“案例一” ([pdf](zotero://open-pdf/library/items/YYJRVFV6?page=25&annotation=H2EMBGP6))。
ctrl+K后，可以将zotero://open-pdf/library/items/YYJRVFV6?page=25&annotation=H2EMBGP6填入链接中，将“案例一”填入锚文本中，就能达到以前一样的效果。
不过就是没有了以前哪种行云流水的操作，处理起来会比较打断思路。。
另外也试过将“案例一” ([pdf](zotero://open-pdf/library/items/YYJRVFV6?page=25&annotation=H2EMBGP6))中的链接部分选中后设置为链接，但思源会在中间插入三个“\”变成zotero://open-pdf/library/items/YYJRVFV6?page\=25\&annotation\=H2EMBGP6，点击不能跳转，除非手动删除三个插入的“\”。

**Comment by Kelfvin** [comment]
我也遇到了同样的情况

> 谢谢大大回复。试了下您的方法，是可以的，需要一些操作。 例如从zotero中直接ctrl+C复制下来的链接会是这样的：“案例一” ([pdf] (zotero://open-pdf/library/items/YYJRVFV6?page=25&annotation=H2EMBGP6))。 ctrl+K后，可以将zotero://open-pdf/library/items/YYJRVFV6?page=25&annotation=H2EMBGP6填入链接中，将“案例一”填入锚文本中，就能达到以前一样的效果。 不过就是没有了以前哪种行云流水的操作，处理起来会比较打断思路。。 另外也试过将“案例一” (pdf)中的链接部分选中后设置为链接，但思源会在中间插入三个“\”变成zotero://open-pdf/library/items/YYJRVFV6?page=25&annotation=H2EMBGP6，点击不能跳转，除非手动删除三个插入的“\”（\粘贴过来后不显示了）。
