### ISSUE TITLE
Note as task

### ISSUE THREAD

**Issue by pztrn** [siyuan-note/siyuan#8319]
### In what scenarios do you need this feature?

As developer which participating in multiple open source and commercial projects I need a place where I can track all tasks from multiple issue trackers.

Also, there are tasks that should be recurring (e.g. monthly "pay for server" task or "upgrade machine X" which executes every 2nd wednesday every third month).

### Describe the optimal solution

Like in Joplin with "recurring tasks" plugin. Every note can be turned into a todo which differs from simple note in there parameters:

* A check in the note's name beginning (which defined "done" and "not done" states, obviously).
* You can specify due date for it.
* You can specify recurrence for it.

**Comment by 88250** [comment]
Hello, this is a very useful feature, but we don't have time to consider it in the development plan at the moment, maybe it would be a good idea as a community plugin.

Thanks for the suggestion, we have closed this issue and tagged it with `Plugin`, maybe some community developers will work on it later.
