### ISSUE TITLE
全局搜索失效？

### ISSUE THREAD

**Issue by windoversnow** [siyuan-note/siyuan#832]
[外链](https://s3.ax1x.com/2020/12/25/rWGAQ1.png)
啥都搜不出来
0.5.43

**Comment by 88250** [comment]
你好，文件保存以后大概要过几秒钟索引完成以后才能搜索到。

**Comment by windoversnow** [comment]
> 你好，文件保存以后大概要过几秒钟索引完成以后才能搜索到。

我到现在都不行啊
等了有一小时了

**Comment by windoversnow** [comment]
如同外链截图上那样，明明都能肉眼看见有这个字，就硬是搜索毫无结果
但有些字能搜，不知为什么

**Comment by windoversnow** [comment]
> 如同外链截图上那样，明明都能肉眼看见有这个字，就硬是搜索毫无结果
> 但有些字能搜，不知为什么

刚刚还能搜的“长”这个关键字，现在也一片空白了

**Comment by 88250** [comment]
估计是安装问题，请确定老的内核退出以后再安装。

**Comment by windoversnow** [comment]
> 估计是安装问题，请确定老的内核退出以后再安装。

开任务管理器确认过了，也罢旧的先卸载干净了，两个问题还是存在

**Comment by 88250** [comment]
请贴一下日志，谢谢。

**Comment by windoversnow** [comment]
> 估计是安装问题，请确定老的内核退出以后再安装。

重启电脑重装也不行，期待尽快出下一版吧

**Comment by 88250** [comment]
好的，我们正在努力。

**Comment by windoversnow** [comment]
> 请贴一下日志，谢谢。

![image](https://user-images.githubusercontent.com/75920913/103130087-2e613400-46d6-11eb-86f2-5ce283cbd63e.png)
https://s3.ax1x.com/2020/12/25/rWBaDJ.png

**Comment by windoversnow** [comment]
> 请贴一下日志，谢谢。

看到几个failed

**Comment by 88250** [comment]
看上去内核还是老的……不是最新版。

**Comment by windoversnow** [comment]
> 看上去内核还是老的……不是最新版。

按理说程序退出一会儿 内核就该自己退了啊，我都重启过电脑，卸载了，用everything搜索了关键词，手动删除一些残余东西，那内核究竟在哪？不就是那个kernel.exe？

**Comment by windoversnow** [comment]
再次开关程序，就没有failed项目了

**Comment by windoversnow** [comment]
I 2020/12/25 17:32:31 main.go:116: kernel [v0.5.43] is booting, runtime mode is [prod], working directory is [E:\Program Files\SiYuan\resources], temp directory is [C:\Users\967\AppData\Local\Temp\siyuan], read only [false]
I 2020/12/25 17:32:31 lang.go:64: initialized languages
D 2020/12/25 17:32:31 conf.go:96: loaded conf [C:\Users\967\.siyuan\conf.json]
I 2020/12/25 17:32:31 conf.go:175: local serve path [http://10.12.70.156:6806]
I 2020/12/25 17:32:31 conf.go:179: initialized conf
I 2020/12/25 17:32:31 appearance.go:47: initialized appearance
I 2020/12/25 17:32:31 main.go:159: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2020/12/25 17:32:31 webdav.go:36: initialized WebDAV server
D 2020/12/25 17:32:31 box.go:356: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/SIFORME/]
I 2020/12/25 17:32:31 conf.go:303: initialized notebook
I 2020/12/25 17:32:32 repo.go:39: initialized git repo
I 2020/12/25 17:32:32 updater.go:74: auto update is disabled
E 2020/12/25 17:32:32 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:14] with length 4
	D:/go1.15.2/src/runtime/panic.go:969 (0x62bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0x629e69)
D:/88250/siyuan-src/kernel/sql/database.go:153 (0x10ee656)
D:/88250/siyuan-src/kernel/sql/database.go:103 (0x10ee155)
D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.1-0.20201224115619-8618e56b89d0/ast/walk.go:51 (0xca577a)
D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.1-0.20201224115619-8618e56b89d0/ast/walk.go:44 (0xca574c)
D:/gogogo/pkg/mod/github.com/88250/lute@v1.7.1-0.20201224115619-8618e56b89d0/ast/walk.go:31 (0x10ecc95)
D:/88250/siyuan-src/kernel/sql/database.go:78 (0x10ecc39)
D:/88250/siyuan-src/kernel/sql/database.go:52 (0x10ec244)
D:/88250/siyuan-src/kernel/sql/queue.go:42 (0x10edb8c)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0x663420)

I 2020/12/25 17:32:38 setuilayout.go:43: set ui layout done
I 2020/12/25 17:32:40 process.go:72: ui process exited, exit kernel process now
I 2020/12/25 17:32:40 conf.go:227: exited kernel

**Comment by windoversnow** [comment]
https://s3.ax1x.com/2020/12/25/rWrkSf.png
这个配置文件夹不用管它吧？重装软件时不用删掉这个文件夹哈，要不然设置还得再点一遍
除了这个文件夹，别的相关文件我时都清理了，不知为啥这个内核会是旧的？？

**Comment by 88250** [comment]
配置文件不用删，日志中已经是 v0.5.43 了，升级应该没问题了。

从日志报错上看应该是因为数据格式有问题，方便的话请把你的笔记库打个包发我邮箱 845765@qq.com 谢谢。

**Comment by windoversnow** [comment]
> 配置文件不用删，日志中已经是 v0.5.43 了，升级应该没问题了。
> 
> 从日志报错上看应该是因为数据格式有问题，方便的话请把你的笔记库打个包发我邮箱 [845765@qq.com](mailto:845765@qq.com) 谢谢。

神奇的自愈了~(￣▽￣)~ 我就是正常的继续写东西而已。。。。。突然自己好了

**Comment by 88250** [comment]
好的，请继续观察，谢谢。
