### ISSUE TITLE
Add some api of plugin

### ISSUE THREAD

**Issue by MarkMindCkm** [siyuan-note/siyuan#8323]
### In what scenarios do you need this feature?

1. 跳转至PDF标注的方法，目前可以通过模拟点击的方法跳转，但是现在有一个弊端，就是需要首先打开一篇思源笔记，而插件的使用过程中，可能没有打开笔记，比如模拟方法如下：
``` js
function jump(id, callback = null) {
                                // console.log('jump:', id);
                                const editor = document.querySelector('div.protyle-wysiwyg div[data-node-id] div[contenteditable][spellcheck]');
                                if (editor) {
                                    let ref = document.createElement("span");
                                    ref.setAttribute("data-type", "file-annotation-ref");
                                    ref.setAttribute("data-subtype", "s");
                                    ref.setAttribute("data-id", id);
                                    editor.appendChild(ref);
                                    ref.click();
                                    ref.remove();
                                    if (typeof callback === 'function') setTimeout(callback, 20);
                                } else {
                                    // 插件使用过程中没打开思源笔记的情况
                                    showMessage('请先打开一篇思源笔记');
                                }
                            }
```
![pdf](https://github.com/siyuan-note/siyuan/assets/18719494/047b2d05-30d7-439d-92af-7242cef046a3)

2. 重命名文件的API , API 中关于文件部分有列表、新增、删除等API , 但是缺少重命名文件的API
3. 插件打开的标签移动至独立窗口，似乎没有执行init方法 ，对于依赖 init 方法生成 dom 的插件使用出现问题

### Describe the optimal solution

增加方法

### Describe the candidate solution

增加方法

**Comment by Vanessa219** [comment]
1. 参看 https://github.com/siyuan-note/siyuan/issues/5066 openTab: 目前仅支持打开自定义页签，后续添加 pdf 和文档
2. https://github.com/siyuan-note/siyuan/issues/8328
3. 是不是报错了，调试是可以进入的
<img width="894" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/17e55f35-8550-4906-a5a9-bdfb9443bd9b">
