### ISSUE TITLE
自动导入电脑中特定文件夹的md文件或是其他的软件支持格式的文件

### ISSUE THREAD

**Issue by ellya00** [siyuan-note/siyuan#8325]
### In what scenarios do you need this feature?

我会把想导入的文件都放在一个特定文件夹里，希望能有一个功能可以自动识别这个文件夹并将相关文件导入进思源

### Describe the optimal solution

希望用自动导入省去手动导入的时间

**Comment by 88250** [comment]
你好，这个不考虑原生支持，可能适合作为扩展由社区开发者支持，谢谢。
