### ISSUE TITLE
单个笔记字数较多时操作卡顿

### ISSUE THREAD

**Issue by marcusbai** [siyuan-note/siyuan#833]
如题：具体表现为我在网上复制了一段内容，通过Sublime Text转为纯文本之后复制到思源笔记里（单个文件夹单个笔记），删除或添加文字时出现卡顿。
字数约3万左右，在Sublime Text，记事本和obsidian操作则无卡顿现象

**Comment by 88250** [comment]
谢谢反馈，内容较长时编辑器确实容易卡顿，后期优化，谢谢。

**Comment by marcusbai** [comment]
感谢开发人员辛勤付出，希望越来越好

**Comment by 88250** [comment]
谢谢，我关闭了，这个问题我们会尽力的。
