### ISSUE TITLE
Search highlighting supports inline memo, image title, hyperlink content, and block memo

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8332]
搜索高亮提示支持行内备注、图片标题、超链接内容、块备注

### In what scenarios do you need this feature?

**行内备注**左侧由于超过一行被隐藏，没有特殊高亮，不清楚具体位置，右侧由于是行内备注，没有高亮，总而言之用户不知道自己搜索到了什么
![image](https://github.com/siyuan-note/siyuan/assets/125173405/6e9eaf97-7584-4278-be0e-1c785b71b4c6)
使用hbuiderx-light主题左边不会再默认隐藏超过一行的内容，左侧可以得到显示，但右侧同样没有对行内备注有特殊的高亮提醒
![image](https://github.com/siyuan-note/siyuan/assets/125173405/bcce59c5-d196-4143-b43d-8a4ef818af6a)
**超链接**内容同理，同样没有特殊定位。与没被搜索的超链接对比没有区别，没有应用其他高亮样式。
![image](https://github.com/siyuan-note/siyuan/assets/125173405/bef5422d-b209-4f70-b5d0-9eca6e8e9f08)
**图片标题**同理
![image](https://github.com/siyuan-note/siyuan/assets/125173405/40c41bb0-f60f-4ec6-bd1e-69771b4fe5a1)
右边没有高亮提示，尽管图片标题和行内备注、超链接都不同是直接显示在文档中的。
**块备注**更糟糕，左边搜索结果里无高亮（即使应用了hbuiderx-light的搜索设计），右边无提醒，用户更不知道自己搜索到了啥。
![~M`JSZ8OBUC} PGOF`C1BD8](https://github.com/siyuan-note/siyuan/assets/125173405/772f0374-5786-46d4-b791-dffdbc907049)

### Describe the optimal solution

希望能够增加提示，比如行内备注和超链接作为搜索结果时可以高亮被其备注的文本，让用户能够快速定位，图片标题增加高亮提示，块备注希望右侧文档区能给块备注标加样式或者其他的提示效果，或者至少在左侧搜索区增加提示。

**Comment by Aiviokoo** [comment]
简单点说就是备注或标题里的内容可以像搜索普通文字一样能够高亮
![image](https://github.com/siyuan-note/siyuan/assets/87182333/a51f78d4-56d7-48ce-9c4a-f3449448cc7b)
![image](https://github.com/siyuan-note/siyuan/assets/87182333/7e8ca13c-2c03-4f8f-b53f-824d6c1b5fff)

**Comment by 88250** [comment]
编辑器显示不出来的就没法高亮了。
