### ISSUE TITLE
Linux `version GLIBC_x.xx not found`

### ISSUE THREAD

**Issue by taozina0587** [siyuan-note/siyuan#8334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/90691302/b2e8c704-03f2-42d7-a1a8-cf4e3e606f87)

### Expected result

run app

### Version environment

```markdown
- Version: 2.8.9
- Operating System: Linux
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11541539/siyuan.log)

**Comment by 88250** [comment]
Please upload the app.log in ~/.config/siyuan

**Comment by taozina0587** [comment]
[app.log](https://github.com/siyuan-note/siyuan/files/11542304/app.log)

**Comment by taozina0587** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/90691302/38512099-3320-4bdc-8175-a25947618680)

**Comment by taozina0587** [comment]
Error persists. I went back to version 2.8.8 and it's working perfectly.

**Comment by 88250** [comment]
Please paste the command output.

**Comment by 88250** [comment]
And execute `ldd --version` in the terminal, post the output, thanks.

**Comment by zxhd863943427** [comment]
有着同样的问题，这是输出：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/0b45a983-b6e0-4d7a-a4ea-dd8c16677aed)

ldd 的输出：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/3f7ec2b9-a3cb-4b63-af83-8bcae915ee08)

**Comment by 88250** [comment]
@zxhd863943427 `ldd --version`

**Comment by zxhd863943427** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/6c3b1655-fed9-4436-bcbd-0f0cd9f842c0)
抱歉，截错图了

**Comment by 88250** [comment]
你的 Ubuntu 是哪个版本？

**Comment by zxhd863943427** [comment]
Ubuntu 18.04.6 LTS，大概理解问题了，不过是什么要求需要提升glibc版本吗？

**Comment by 88250** [comment]
我在 Ubuntu 22.04 上编译的，不兼容低版本。这个问题只能在低版本上重新编译才行。

**Comment by littlecoby** [comment]
I still encounter the same issue in [v202305250942](https://github.com/siyuan-note/siyuan/releases/tag/v2.8.10-dev1).

system info:
ubuntu 20.04 LTS
ldd version 2.31
resources\kernel\SiYuan-Kernel outputs:
![image](https://github.com/siyuan-note/siyuan/assets/27865589/f53bf766-4545-4093-baab-be1ebb6608c2)

**Comment by 88250** [comment]
@littlecoby We will adjust the GitHub Action later, please help to test it in the next dev version.

**Comment by littlecoby** [comment]
dev2 works [v202305261104](https://github.com/siyuan-note/siyuan/releases/tag/v2.8.10-dev2)

**Comment by benz9527** [comment]
This question I met before. You have to upgrade the GLibC version to v2.32. For example, I build SiYuan container image is based on Debian latest version image but its GLicC version is lower than v2.32，then I add 
```
echo "deb http://ftp.cn.debian.org/debian sid main" >> /etc/apt/sources.list
apt update
```
to dockerfile to build a new version SiYuan container image, it works. The GLibC v2.32 is included.
