### ISSUE TITLE
 Optimize the small window of Siyuan Notes

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#8338]
### In what scenarios do you need this feature?

Optimize the small window of Siyuan Notes。
This small window has no effect at all。
优化思源笔记小窗口。
这小窗口一点效果没有。

### Describe the optimal solution

[小窗口.zip](https://github.com/siyuan-note/siyuan/files/11543025/default.zip)

**Comment by 88250** [comment]
最小化会使用上次调整过的大小。

**Comment by 88250** [comment]
正常关闭的话会记录窗口状态的，下次启动以后应该是上一次正常退出的位置和大小。

**Comment by 88250** [comment]
试试点右上角的 X 退出

**Comment by 88250** [comment]
这个信息是记录在 `C:\Users\用户\.config\siyuan\windowState.json` 中的，可以看下是不是这个文件无法写入或者被其他软件还原了。

**Comment by 88250** [comment]
你看下改变窗口大小和位置后正常退出，这个文件中的相关内容是否会改变。

**Comment by 88250** [comment]
你是用的是最新版吗？最新版 最大化 后关闭，重启后 向下还原 是 0.8 倍大小。

**Comment by 88250** [comment]
要等微软审核，快的时候只要 1 小时，慢的话可能要 2-3 天。
