### ISSUE TITLE
保存过得文件，关闭时提示未保存？？0.5.43

### ISSUE THREAD

**Issue by windoversnow** [siyuan-note/siyuan#834]
保存过得文件，关闭时提示未保存？？0.5.43
[kk](https://s3.ax1x.com/2020/12/25/rWGMJH.png)

**Comment by 88250** [comment]
麻烦说一下重现步骤，我这里重现不了……

**Comment by windoversnow** [comment]
> 麻烦说一下重现步骤，我这里重现不了……

就是我编辑完一个文档，不管是手动点一下Ctrl+s 还是等几秒钟，让软件自动保存，再点关闭文件的叉叉时，就会弹出这个提示

**Comment by windoversnow** [comment]
> > 麻烦说一下重现步骤，我这里重现不了……
> 
> 就是我编辑完一个文档，不管是手动点一下Ctrl+s 还是等几秒钟，让软件自动保存，再点关闭文件的叉叉时，就会弹出这个提示

每个文件都这样，昨天用0.5.42还好好的，我一直用便携版

**Comment by 88250** [comment]
请确定一下老的内核完全退出以后再覆盖安装，不然内核文件因为被占用会导致安装不了。

**Comment by windoversnow** [comment]
> 请确定一下老的内核完全退出以后再覆盖安装，不然内核文件因为被占用会导致安装不了。

好，我试试

**Comment by windoversnow** [comment]
> 请确定一下老的内核完全退出以后再覆盖安装，不然内核文件因为被占用会导致安装不了。

不行，完全卸载干净，重装的 这个关闭提示为保存问题和全局搜索问题依旧存在

**Comment by windoversnow** [comment]
> 请确定一下老的内核完全退出以后再覆盖安装，不然内核文件因为被占用会导致安装不了。

[https://s3.ax1x.com/2020/12/25/rWdhEq.png](https://s3.ax1x.com/2020/12/25/rWdhEq.png)

**Comment by 88250** [comment]
内核确认关闭以后重新安装一下试试。
