### ISSUE TITLE
The `addItem` interface of the frontend API `Menu` supports to pass in the DOM element

### ISSUE THREAD

**Issue by svchord** [siyuan-note/siyuan#8343]
Menu 的 addItem 接口希望可以传入自己创建的DOM元素

### In what scenarios do you need this feature?

希望利用Menu浮层显示自己创建的界面，虽然热力图、闪卡增强等插件能通过一些偏门手段实现这一点，但这也说明了是有需求的，所以希望官方能够提供比较方便的方法。

### Describe the optimal solution

addItem接口可以传入IMenuItemOption类型或者HTMLElement类型的参数

**Comment by Vanessa219** [comment]
你看一下这样是否满足需求
<img width="882" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/b3a167f0-97bd-4b6b-8127-bc89b5ab0a01">

**Comment by svchord** [comment]
一定要传模板字符串吗，能不能直接传HTMLElement类型

**Comment by Vanessa219** [comment]
字符串都可以，element 只是没有接口，稍等我去添加一下。
