### ISSUE TITLE
Top bar buttons support unpin

### ISSUE THREAD

**Issue by svtardust** [siyuan-note/siyuan#8345]
是否能引入类似 windows 系统托盘的一种机制？

### In what scenarios do you need this feature?

插件库作者如果都把插件图标放到顶栏，那么如果有人开了大量插件势必会存在顶栏被占满甚至不够用的情况，那么是否可以引入类似系统托盘的这种机制？

### Describe the optimal solution

前端能否引入插件托盘？
类似这种
![图片](https://github.com/siyuan-note/siyuan/assets/132273422/21d167ae-58ff-4496-ab31-7401bd5e2af1)
或者firefox浏览器中的这种？
![图片](https://github.com/siyuan-note/siyuan/assets/132273422/9de08758-9686-4105-9577-002bf82ccf1f)

当插件被启用后先放入插件托盘，让用户选择是否显示在顶栏。

**Comment by 88250** [comment]
下拉菜单应该是比较好的选择。

**Comment by mozhux** [comment]
希望下拉菜单图标不要用三点菜单这个icon吧，在顶栏会比较奇怪。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/bc3f9675-a0c9-48d1-8419-a99d3b7b110f)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/60314d90-a18f-43f5-b852-9e66c1b55b82)

**Comment by Aiviokoo** [comment]
关于进入集市一步达的建议，希望D大V大可以考虑一下，谢谢：
1、双击顶部的button
2、alt+p直达的是集市而不是编辑器
理由如下：
![83BA0CE06A3234FD7FF9B91DEE941B1A](https://github.com/siyuan-note/siyuan/assets/87182333/293bf980-9a4f-43ee-a186-b3d9b2fa8fae)

**Comment by 88250** [comment]
不考虑了，谢谢。

**Comment by Aiviokoo** [comment]
> 不考虑了，谢谢。

好的
