### ISSUE TITLE
重载后，插件的Dock无法正确渲染

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

WebAPP插件，注册了dock，首次使用时正常。多次刷新之后无法正确显示，显示为空白，并且无法移动dock的按钮位置。

### Expected result

dock在刷新之后依然能够正确显示。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/4801955/a31669e1-125a-4a62-8d56-9ecc3559a376)

### Version environment

```markdown
- Version: 2.8.9
- Operating System: win11
- Browser (if used):
```

### Log file

- 

### More information

昨天自己调试了整个代码，从dock无法移动入手，找到了dock的初始化原理。

核心的根本问题在于加载插件本身是一个异步的事情，src/index.ts中的`loadPlugins()`是一个异步处理，而onGetConfig()又同步的做了根据已有配置恢复整个界面的布局。这导致了dock在判断非内置类型的dock时无法走到正确判断里面。

考虑在loadPlugins前增加await，阻塞住整个的渲染流程。

另外插件本身的钩子中应该做什么不应该做什么，也需要良好规范。目前代码实际上在构造函数里和onload钩子里别无二致。

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/8341

**Comment by Vanessa219** [comment]
参见 https://github.com/siyuan-note/siyuan/issues/8341 中第二和第三

**Comment by zuoez02** [comment]
@Vanessa219 loadPlugins增加await，是否赞同？或者你们喜欢用回调也都可以

**Comment by Vanessa219** [comment]
感谢建议，看了下确实是需要 await 的，否则后续无法获取到插件实例。目前修改为 

<img width="772" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/836f30aa-a1ad-4fe3-bb00-2c9fa2599efc">
