### ISSUE TITLE
在容器版本中，alt+d对内容进行标记的快捷键不起作用，修改该标记的快捷键已然不起作用

### ISSUE THREAD

**Issue by zbluex** [siyuan-note/siyuan#8349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在容器版本中，alt+d对内容进行标记的快捷键不起作用，修改该标记的快捷键已然不起作用

### Expected result

预期的功能无效

### Version environment

```markdown
- Version: 2.8.6
- Operating System: Docker
- Browser (if used): edge
```

### Log file

None

**Comment by 88250** [comment]
可能和浏览器其他快捷键冲突了，这个估计只能自己排查下了，感谢反馈。

浏览器 Alt+D 应该是切换到地址栏。

**Comment by zbluex** [comment]
@88250 我可以确认没有冲突，桌面版我快捷键修改成其他的，可以正常进行搜索触发，修改成很多其他快捷键组合，均无法生效。

**Comment by 88250** [comment]
是桌面端还是浏览器端？

**Comment by zbluex** [comment]
@88250 桌面端和容器端都存在

**Comment by 88250** [comment]
修改快捷键以后点击上面的刷新后再试试。

**Comment by zbluex** [comment]
@88250 找到原因了，确实是刷新的问题，我修改完没有刷新，导致快捷键没生效，感谢解答！
