### ISSUE TITLE
Can't boot on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by nickshv** [siyuan-note/siyuan#8351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当我尝试启动 SiYuan 时，我看到两个有错误的窗口： / When I trying to start SiYuan I see two windows with errors:

> ⚠️ 内核因未知原因退出 The kernel exited for unknown reasons
> 思源内核因未知原因退出 [code=1]，请尝试重启操作系统后再启动思源。如果该问题依然发生，请检查杀毒软件是否阻止思源内核启动。
> SiYuan Kernel exited for unknown reasons [code=1], please try to reboot your operating system and then start SiYuan again. If occurs this problem still, please check your anti-virus software whether kill the SiYuan Kernel.

> ⚠️ 获取内核服务端口失败 Failed to get kernel serve port
> 获取内核服务端口失败，请确保程序拥有网络权限并不受防火墙和杀毒软件阻止。
> Failed to get kernel serve port, please make sure the program has network permissions and is not blocked by firewalls and antivirus software.

仅适用于 2.8.9 版本。 版本 2.8.8 在 Ubuntu 20.04 上运行没有问题 / Only for version 2.8.9. Version 2.8.8 working without problems on Ubuntu 20.04

### Expected result

2.8.9 版开始没有问题。/ Version 2.8.9 starting without problems.

### Version environment

```markdown
- Version: 2.8.9
- Operating System: Ubuntu 20.04 LTS
```

### Log file

I 2023/05/24 15:21:21 working.go:117: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/05/24 15:21:21 runtime.go:70: kernel is booting:
    * ver [2.8.8]
    * arch [amd64]
    * os [ubuntu]
    * pid [5602]
    * runtime mode [prod]
    * working directory [/opt/siyuan-latest-linux/resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/home/nsh/SiYuan]
I 2023/05/24 15:21:21 conf.go:349: OpenAI API enabled
    baseURL=https://api.openai.com/v1
    timeout=30s
    proxy=
    model=gpt-4
    maxTokens=0
I 2023/05/24 15:21:21 conf.go:379: user has disabled [Google Analytics]
I 2023/05/24 15:21:21 runtime.go:124: use network proxy [system]
I 2023/05/24 15:21:21 serve.go:112: kernel [pid=5602] http server [127.0.0.1:43517] is booting
I 2023/05/24 15:21:21 pandoc.go:96: built-in pandoc [ver=2.19.2, bin=/home/nsh/SiYuan/temp/pandoc/bin/pandoc]
I 2023/05/24 15:21:22 sync.go:151: sync before boot
I 2023/05/24 15:21:22 repository.go:1035: boot get sync cloud files elapsed [0.55s]
I 2023/05/24 15:21:22 blocktree.go:448: read block tree [1.2 MB] to [/home/nsh/SiYuan/temp/blocktree], elapsed [0.01s]
I 2023/05/24 15:21:22 conf.go:685: database size [14 MB], tree/block count [199/4481]
I 2023/05/24 15:21:22 working.go:155: kernel booted
I 2023/05/24 15:21:22 serve.go:125: reverse proxy server [127.0.0.1:6806] is booting
I 2023/05/24 15:21:22 index.go:133: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.01s], tree [count=56, size=1.1 MB]
I 2023/05/24 15:21:23 box.go:79: auto stat [trees=199, blocks=4481, dataSize=116 MB, assetsSize=114 MB]
I 2023/05/24 15:21:23 disk.go:33: disk usage [total=983 GB, used=145 GB, free=788 GB]
I 2023/05/24 15:22:21 conf.go:460: exiting kernel [force=false, execInstallPkg=0]
I 2023/05/24 15:22:21 sync.go:196: sync before exit
I 2023/05/24 15:22:21 repository.go:1136: synced data repo [provider=2, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=11 kB] in [0.48s]
I 2023/05/24 15:22:21 database.go:1134: closed database
I 2023/05/24 15:22:21 conf.go:832: cleared workspace temp
I 2023/05/24 15:22:22 conf.go:507: exited kernel

------------------------------------------------------------

May 24 15:26:28 NSH-WORK systemd[2068]: Started Application launched by gnome-shell.
May 24 15:26:28 NSH-WORK siyuan.desktop[6578]: got kernel port [46425]
May 24 15:26:28 NSH-WORK siyuan.desktop[6578]: ui version [2.8.9], booting kernel [/opt/siyuan-latest-linux/resources/kernel/SiYuan-Kernel --port 46425 --wd /opt/siyuan-latest-linux/resources]
May 24 15:26:28 NSH-WORK siyuan.desktop[6578]: booted kernel process [pid=6634, port=46425]
May 24 15:26:28 NSH-WORK siyuan.desktop[6578]: checking kernel version
May 24 15:26:28 NSH-WORK siyuan.desktop[6578]: kernel [pid=6634, port=46425] exited with code [1]
May 24 15:26:28 NSH-WORK siyuan.desktop[6618]: libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
May 24 15:26:28 NSH-WORK siyuan.desktop[6618]: libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
May 24 15:26:28 NSH-WORK siyuan.desktop[6578]: get kernel version failed: request to http://127.0.0.1:46425/api/system/version failed, reason: net::ERR_CONNECTION_REFUSED
May 24 15:26:30 NSH-WORK siyuan.desktop[6578]: message repeated 14 times: [ get kernel version failed: request to http://127.0.0.1:46425/api/system/version failed, reason: net::ERR_CONNECTION_REFUSED]
May 24 15:26:30 NSH-WORK siyuan.desktop[6578]: get kernel ver failed

**Comment by 88250** [comment]
请在命令行下面执行 `ldd --version` 后贴一下输出结果。

**Comment by nickshv** [comment]
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by 88250** [comment]
这个问题会在下个版本修复，请参考 https://github.com/siyuan-note/siyuan/issues/8334
