### ISSUE TITLE
New documents can still be created in read-only mode

### ISSUE THREAD

**Issue by tomatl45** [siyuan-note/siyuan#8355]
只读模式下仍可新建文档

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

你好，

我发现当我按下右上角的按钮，切换为只读模式之后，我仍然能够新建文档。即使我在切换为只读模式后重启思源笔记，也仍然能够继续新建文档。并且，我可以在只读模式下使用下列任一方式新建文档：

- 在左侧文档树中按下加号按钮（新建子文档）
- 在左侧文档树中按下菜单（在上方新建文档、在下方新建文档）
- 按下键盘快捷键`Ctrl + N`

在新建文档之后，我并不能对文档进行命名，也不能对内容进行编辑，但我可以一直新建任意数量的文档。

### Expected result

请问我应该进行哪些操作，在切换为只读模式的同时，也临时禁用新建文档的功能？

### Version environment

```markdown
- Version: v2.8.9 (AppImage)
- Operating System: Fedora
- Browser (if used): Firefox
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11557263/siyuan.log)

**Comment by Vanessa219** [comment]
只读指的是编辑器只读，其他操作可以进行。需要全部只读的话，目前只能参照以下方式进行。
<img width="709" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/632df87f-2664-4207-8d60-5a0cc99bc7d5">

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
