### ISSUE TITLE
移动端选择字体样式（比如高亮）后不能直接滑动，复制文字后再选高亮（不选也可）可以直接滑动

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8358]
### In what scenarios do you need this feature?

在移动端编辑字体或进行相关操作完成后，需要手再点一下其他位置聚焦，然后才能划动，这个操作属实不太优雅，比较影响用户体验，希望可以改进，谢谢。（最后一张图应该非常清楚）

### Describe the optimal solution

希望直接进行文字相关操作后也可以直接进行划动（见视频2复制后，设置样式后仍然可继续划动）
现状是：现在如果是先选样式，那么手指需要在其他编辑区域聚焦后才能进行划动操作。

### Other information

https://github.com/siyuan-note/siyuan/assets/87182333/cbb4204e-e93a-4920-a7b6-3ab673d5830c

https://github.com/siyuan-note/siyuan/assets/87182333/f765bd38-11a3-42d8-a4a3-2a59c1e3e4df

![image](https://github.com/siyuan-note/siyuan/assets/87182333/7dbbd63e-6a33-45aa-a429-e743b819c359)
![image](https://github.com/siyuan-note/siyuan/assets/87182333/48ed16d6-05e0-4beb-9cf1-54c7d52aa2c7)

**Comment by Aiviokoo** [comment]
> 我不太确定是不是这个操作，我这里看起来没问题：
> 
> 
> https://github.com/siyuan-note/siyuan/assets/873584/b01e8cc1-4a7d-4e3d-9bc6-13ce0e949a08
> 
> 

是这里的，但是不一样的是，D大这里是没有出现复制那些选项的。
我这里是手指长按选中文字后，有下面的一排也有复制等选项的。这种情况下是稳定出现的。![Screenshot_2023-05-25-23-08-06-730_org.b3log.siyuan.jpg](https://github.com/siyuan-note/siyuan/assets/87182333/861bbdb0-eaaf-434e-80c2-fcf515118b6f)

**Comment by Aiviokoo** [comment]
找到原因了，长按选择才会出现复制那几个框框，轻触选择不会。
如果是长按选择后没复制，而是直接高亮了，就不能滑动。
改一下还是要好一些。

**Comment by 88250** [comment]
这是之前的改进，请参考 https://github.com/siyuan-note/siyuan/issues/5559

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
