### ISSUE TITLE
建议 Ctrl-P 搜索加个延迟

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#836]
进行全局搜索的时候，只要搜索框里的文字发生变化就会立即触发搜索，但是随着笔记本里的内容越来越多，在搜索框里连续打字和连续退格的时候都很卡，特别是输英文和五笔打单字的时候

建议加个延迟计时器，停止打字 0.5s 之后再执行搜索，就像 notion 那样，可以加个安慰剂小动画：

![image](https://user-images.githubusercontent.com/32661922/103129993-cc083380-46d5-11eb-9f32-139943b82542.png)

**Comment by 88250** [comment]
感谢，我们合并到 https://github.com/siyuan-note/siyuan/issues/835 中一并处理。
