### ISSUE TITLE
After turning off the "Doc icon uses the system native emoji" option, there is a freeze on the settings page

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#8361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

关闭【文档图标使用系统原生Emoji】选项后
每次进入设置页面都会很卡顿

也许有关联 #8205 

### Expected result

关闭【文档图标使用系统原生Emoji】选项和打开时一样流畅

### Version environment

```markdown
- Version: v2.8.9
- Operating System: Windows 10
```

### Log file

无

**Comment by 88250** [comment]
这个选项即将被移除 https://github.com/siyuan-note/siyuan/issues/8206
