### ISSUE TITLE
支持自定义显示右键菜单项的功能

### ISSUE THREAD

**Issue by youth54** [siyuan-note/siyuan#8364]
### In what scenarios do you need this feature?

随着功能的增加，右键菜单内容越来越多，平时通过点击图标或者右键，会弹出很长的内容，影响阅读。

![image](https://github.com/siyuan-note/siyuan/assets/72968849/d4e5fa08-2f00-4371-a2cc-ad45c2ef2ec9)

### Describe the optimal solution

希望能够增加自定义显示右键菜单的功能。
或者是否能够提供一个CSS例子用于如何隐藏菜单中的每个item，比如隐藏“人工智能”、“移动”、“微信提醒”、“快速制卡”等等。

**Comment by 88250** [comment]
这个目前不考虑了，也许将来会有社区插件进行支持，感谢反馈。
