### ISSUE TITLE
软键盘换行错误[Android, keyboard]

### ISSUE THREAD

**Issue by red-co** [siyuan-note/siyuan#8366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

siyuan,最新版本。
创建一个三级缩进的block,
使用换行符缩进列表，换行符行为错误。

91

### Expected result

对空节点缩进(回车键)将创建新行，或者无反应，或者分割成新段。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/75922982/df982480-e641-4542-b8c6-ab8ec23ad89b

https://github.com/siyuan-note/siyuan/assets/75922982/35553593-02cb-487b-8d63-b0657493e231

这个行为至少需要三级缩进才能触发。
(相关的，这周围，与节点缩进，还有一些bug无法每次都重复，比如编辑器崩溃，编辑器关闭。但是这个可以稳定重复）

下面这个，上面那个行为的后续，连undefined 都出现了。

https://github.com/siyuan-note/siyuan/assets/75922982/48e9e088-dab9-415b-bfa0-b7d3d43ef6

### Version environment

```markdown
- Version: 2.8.9
- Operating System: android 12
- Browser (if used): none
```

### Log file

E 2023/05/25 23:42:40 logging.go:159: PANIC RECOVERED: interface conversion: interface {} is nil, not string
	D:/go1.20/src/runtime/panic.go:884 (0x72ae2ecff3)
D:/go1.20/src/runtime/iface.go:262 (0x72ae2c0cfb)
D:/88250/siyuan/kernel/model/transaction.go:863 (0x72af3e1f6f)
D:/88250/siyuan/kernel/model/transaction.go:196 (0x72af3dd3ab)
D:/88250/siyuan/kernel/model/transaction.go:104 (0x72af3dc757)
D:/88250/siyuan/kernel/model/transaction.go:92 (0x72af3dc63b)
D:/88250/siyuan/kernel/job/cron.go:54 (0x72af3ef8ef)
D:/88250/siyuan/kernel/job/cron.go:55 (0x72af3ef883)
D:/go1.20/src/runtime/asm_arm64.s:1172 (0x72ae323773)

**Comment by red-co** [comment]
最后一个视频，删除键导致键盘反复关闭，是 google gboard 产生的。我换成小米自带的输入法不会触发这个键盘被错误关闭 的问题。

**Comment by red-co** [comment]
windows10也能复现
 " 
- 创建三个节点(如下面这个，)
在 1.3.1 后侧按回车，会创建一个带序号2.的空节点，对空节点按回车，会导致序号被删除，且下方序号3.变成1.
。删除空节点，此时第三行就是 1. 1. 2. 的序号。在第一个1.后面按回车，会创建第一个2.，再按回车，这个2.的块会跳转1.3的下方，

1. 1
    1. 1.1
    2. 1.2
    3. 1.3
        1. 1.3.1
        2. 1.3.2
        3. 1.3.3

**Comment by Vanessa219** [comment]
3变成1以后，段落块就将一个列表分割为两个列表。后续操作就会和只有一个列表时不一致了。

**Comment by red-co** [comment]
> 3变成1以后，段落块就将一个列表分割为两个列表。后续操作就会和只有一个列表时不一致了。
@Vanessa219 
感谢回复，
---
(还有关于 Gboard (google input methods) 容易导致键盘关闭，或者丢失
焦点丢失，键盘被关闭的问题)
gboard 使用 en 输入，
创建一个块 `1.`退格键无法删除它, 会导致键盘关闭。
enter 创建一个块，键盘也会关闭，
选中一个英语单词，瞬间就会丢失焦点。
(下面补充视频)
(这是要避免使用 gboard 吗?)

**Comment by red-co** [comment]
https://github.com/siyuan-note/siyuan/assets/75922982/82f0414b-2b42-4e8b-8dd3-ac9795cb9dbf

**Comment by red-co** [comment]
结论: 
1. 一种没在文档中写出来的，有特殊风味的降价语法,。(异常的输入法跳行行为) (我觉得这种语法也挺好，就是应该在 `文档/降价语法/ list-item` 那里写出来。否则这种行为令人困惑）
2. 一个不兼容，不推荐使用的 input methods, 
    1. (表现出无法删除item，反复关闭键盘，无法选中。)
    2. (但 goboard 是 android 默认使用的键盘。。。。但是这不是我的问题，我切换国内的输入法就行了。但是另外一些输入英语的用户会非常困惑)

**Comment by red-co** [comment]
1.null (好吧，)
2. Google play store,  https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

**Comment by Vanessa219** [comment]
我可能没有办法安装起来，我先在小本本上记录一下吧，以后有空在折腾
