### ISSUE TITLE
调整 Electron 窗体设置

### ISSUE THREAD

**Issue by Chenrt-ggx** [siyuan-note/siyuan#8368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

目前，思源笔记中的窗体设置与 Electron 官方文档[在安全上的最佳实践](https://www.electronjs.org/zh/docs/latest/tutorial/security)背道而驰，相关代码：

```js
webPreferences: {
    nodeIntegration: true,
    webviewTag: true,
    webSecurity: false,
    contextIsolation: false
}
```

Electron 官方文档[在安全上的最佳实践](https://www.electronjs.org/zh/docs/latest/tutorial/security)：

<img width="488" alt="" src="https://github.com/siyuan-note/siyuan/assets/64241518/b26ea015-8d9f-4081-81e1-219b18b8b999">

<img width="475" alt="" src="https://github.com/siyuan-note/siyuan/assets/64241518/8edde109-0211-4525-9b27-5c609b3fc45c">

<img width="488" alt="" src="https://github.com/siyuan-note/siyuan/assets/64241518/120b3486-431f-4ac4-a847-2b1358dbd9d3">

这个问题在两年前的 [Issue](https://github.com/siyuan-note/siyuan/issues/3444) 中就已被提出，但未被给予足够重视，相应 Issue 已被关闭。

### Expected result

```js
webPreferences: {
    nodeIntegration: false,
    webviewTag: true,
    webSecurity: true,
    contextIsolation: true
}
```

### Version environment

```markdown
- Version: Latest
- Operating System: Windows 10
```

### Log file

省流：看过了，一切正常。

**Comment by 88250** [comment]
你好，这是为了执行脚本特性而设置的，所以无法关闭，感谢反馈。
