### ISSUE TITLE
新窗口要点击页签才加载

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#8371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![1](https://github.com/siyuan-note/siyuan/assets/38906705/c128dbd1-dd9c-4651-9bd5-ba1ed3aa0702)

### Expected result

1

### Version environment

```markdown
- Version: v2.8.10-dev2
- Operating System: win10
- Browser (if used):
```

### Log file

1

**Comment by Vanessa219** [comment]
感谢反馈，这个是由于 https://github.com/siyuan-note/siyuan/issues/8350 改出来的 bug， dev 分支已修复。
