### ISSUE TITLE
Arrows, text, squares to highlight individual elements in images

### ISSUE THREAD

**Issue by ignatcolor** [siyuan-note/siyuan#8373]
### In what scenarios do you need this feature?

Hello!
Thank you very much for your wonderful app.
Could you add arrows, text, squares to highlight individual elements in images?

### Describe the optimal solution

![Untitled-2](https://github.com/siyuan-note/siyuan/assets/134678734/51ed0569-4de2-45ec-9b5b-6e8877e4f195)

**Comment by 88250** [comment]
Hello, we will not consider the function of editing images at present, please use external tools to edit images, and then insert them into SiYuan, thank you.
