### ISSUE TITLE
2.8.10-dev2 当中出现部分插件无法正常在顶栏加载的问题

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这是在 2.8.9 下，启用了五个插件，都能正常使用。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/75f423e3-21f1-4364-8eb8-a2cbad4031bc)

但是在最新的 dev2 下，插件的启用似乎出现了一些问题。下面的 gif 当中，请注意顶栏的变化，可以看到当有些插件启用的时候，顶栏并没有按照预期添加对应的图标。

![Bug](https://github.com/siyuan-note/siyuan/assets/27268127/24b89ad7-605b-4116-9d9d-35cffd62fb92)

### Expected result

我不清楚是不是思源内部做了什么调整我没有跟进，但是有些插件能启用有些插件不能启用还是太奇怪了。

如果是 bug 希望尽快修复，如果不是请告诉我要如何适配新的变化。

### Version environment

```markdown
- Version: 2.8.10-dev2
- Operating System: win10
- Browser (if used):「×」
```

### Log file

无，和内核无关

**Comment by Vanessa219** [comment]
这个 gif 没办法暂停和慢速播放，大概是挂件示例的图标放在了左上角么？

**Comment by Vanessa219** [comment]
这个版本为了提高初始化加载速度，对加载机制做了异步处理。addTopBar， addTab，addDock 不能放在 await 方法后。

如果是单个插件的启用的话，我做一下兼容处理吧。

**Comment by frostime** [comment]
> 这个版本为了提高初始化加载速度，对加载机制做了异步处理。addTopBar， addTab，addDock 不能放在 await 方法后。
> 
> 如果是单个插件的启用的话，我做一下兼容处理吧。

好的，我明天试试看。

**Comment by Vanessa219** [comment]
👌 需更新一下上面的代码
