### ISSUE TITLE
为什么从语雀复制过来的文档，文字总是加粗呢？

### ISSUE THREAD

**Issue by DreamsCat** [siyuan-note/siyuan#8376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

每次从语雀复制直接粘贴来过，格式倒是有保留，但是文字总是给我默认加粗体，每次还得一个一个去修改

### Expected result

复制过来后，字体跟随原文档样式

### Version environment

```markdown
- Version: 2.8.9
- Operating System: 13.4
```

### Log file

no

**Comment by mozhux** [comment]
你应该打开网页语雀复制，客户端的语雀。。就是那种自己带样式了

**Comment by 88250** [comment]
这个暂时没有办法解决了，语雀的 DOM 里有很多自定义标签无法按照标准 HTML 解析处理。
