### ISSUE TITLE
 `/api/filetree/createDocWithMd` 使用相同 path 重复调用接口行为与文档不符

### ISSUE THREAD

**Issue by mdzz2048** [siyuan-note/siyuan#8379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

根据文档描述

> 如果使用同一个 path 重复调用该接口，不会覆盖已有文档，而是新建随机数结尾的文档

实际上在 2.8.8 和 2.8.9 使用相同 path 重复调用接口，返回值都是第一次创建的返回值，并且不会新建随机数结尾的文档

https://github.com/siyuan-note/siyuan/assets/86549958/5abd9cd3-df40-4548-a935-576a21df3885

### Expected result

效果和文档描述一致

### Version environment

```markdown
- Version: 2.8.9
- Operating System: Windows 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11584272/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，稍后更新文档。
