### ISSUE TITLE
展现标签所属块之间的关系

### ISSUE THREAD

**Issue by windoversnow** [siyuan-note/siyuan#838]
## 增加关系图控制选项，可以选择按某几个指定的标签生成关系图

目前的关系网是按照**相互引用**关系来构建的，这种引用关系是随着文章的完善**一步步形成**的，那关系图所体现的就是我**已经写成**的或者**正在整理**的文章之间的相互关系。

但是，日积月累的素材、随手记录的灵感点子等一些欠整理欠分类的东西，一般就是再记录或剪藏时，顺手写个标签而已，或者比较粗的分几个大类文件夹，**没有相互引用**。

既然思源支持层级标签，能不能把这个关系体现在关系图中呢？

![image](https://user-images.githubusercontent.com/873584/106108862-d65d9780-6183-11eb-8387-5ffd21238911.png)

这样的作用就是为**将要进行**的文章或项目提供助力。

当然了，现有的按引用关系生成关系图也继续保留，**按需切换**。

**Comment by 88250** [comment]
我们计划在 v0.7.0 开始对关系图进行改进，你的建议我们会进行考虑的，谢谢。
