### ISSUE TITLE
有关搜索的两个改进提议

### ISSUE THREAD

**Issue by Vanly7710** [siyuan-note/siyuan#8380]
### In what scenarios do you need this feature?

1. 搜索当中如果我选择了按文档分组，然后排序选择了**按原文内容顺序**排序，这时候搜索到的内容是按照文档内的内容从前往后排序的，这个功能很棒。
但是在这个选项下，我认为**文档之间的排序，也应该继承文档树的顺序排列**比较好。这在查询日记内容中尤其有用，可以从1号顺序读到31号，而现在这个功能实现不了，文档会在1号到31号文档之间按照更新时间去排序，这和选项“按原文内容顺序”有些冲突

2. 搜索是否能和设置中的“编辑器-悬停出现浮窗”一样，推出一个“需按住Ctrl键点击搜索预览才会退出搜索窗口并跳转到文档界面”的选项呢？
这是因为在一个块内命中多个结果时，需要重复点击搜索预览跳到下一个命中结果，而这一操作和“双击预览退出搜索窗口并跳转到文档界面”这个功能太冲突了，经常我是想看同一个块内的下一个命中结果，结果给退出搜索窗口了。然后重新打开搜索窗口也不能恢复到上次浏览的位置，就又要开始一轮重复的搜索操作

### Describe the optimal solution

如上所述

**Comment by 88250** [comment]
1. 这个排序模式 `5` 下是按照块类型排序的，文档这一层也算入块，所以无法再单独排序了
2. 这个暂时不考虑了，需要在结果间切换的话不要快速双击，单击就可以切换了。另外，可以试下按住 Ctrl 再单击，这样目前可以阻止双击事件触发

感谢反馈。

**Comment by Vanly7710** [comment]
感谢D大回复

>可以试下按住 Ctrl 再单击，这样目前可以阻止双击事件触发

这么好的功能，怎么没人提过，我直到今天才知道有这个功能🤣

无论如何，我的第二个问题得到了解决，再次感谢D大

**Comment by 88250** [comment]
这个不是功能特性，而是个漏洞利用，以后不一定还能这么用。

**Comment by Vanly7710** [comment]
原来如此，是一个漏洞利用呀，但是希望这个漏洞可以一直用下去😆

>需要在结果间切换的话不要快速双击，单击就可以切换了

这个单击确实可以，但是快速的单击就很容易变成双击，这个速度非常不好把握🤣
