### ISSUE TITLE
在PDF标注时的更优解

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#8381]
### In what scenarios do you need this feature?

在导入pdf进行标注时

### Describe the optimal solution

希望矩形标注后复制到文档中不包含锚文字只有图片，能否有更优解直接定位到PDF，如果矩形标注较多的时候会很不美观，但是我又很需要这个定位的功能

### Describe the candidate solution

例如在类似网络图片形式在左上角加入一个图标如果鼠标悬停则展示图标，点击图标就能跳转到相关链接(不知道是不是技术上有难度，我记得之前图片是可以保存链接的但是好像是2.2之后图片就不能保存链接了）
同时反馈一个bug，在矩形标注完复制过去的图片会带标注框的颜色（如下图，矩形标注框为红色）
![image](https://github.com/siyuan-note/siyuan/assets/98648589/90eb43a9-28b8-4dfd-b791-e50233a938d1)

**Comment by 88250** [comment]
抱歉，这个做不到哦，PDF 标记元素只能保存固定格式的文本，无法保存图片路径。

带颜色是特性，因为可以选择不同的矩形框颜色的。

感谢反馈。
