### ISSUE TITLE
Support for listing missing files in Settings - Assets

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#8383]
设置中资源选单支持列出缺失资源

### In what scenarios do you need this feature?

之前某一次上古的bug导致思源笔记把引用的资源文件也算作未引用，删掉了很多图片而没有意识到，然后最近看之前的笔记有好多图都裂了，想快速定位那些缺失的笔记来进行尽量的补救

### Describe the optimal solution

提供sql索引，找出资源缺失的块？

### Other information

缺失资源和未引用资源，都算作资源选项卡，好像也非常合理。而且也能起到及时发现文件缺失的问题，回收站可能还能补救，太久远就完全没办法了

**Comment by HowcanoeWang** [comment]
> 缺失资源这个上古bug会造成还有别的渠道会导致吗？
> 
> 如果没有的话就直接引入一个设置项是不是有点多余？

还有可能用户手动误删，以及如果是同步盘托管的话，同步盘神秘的同步丢失（个人都遇到过，好在发现及时回收站里找回来了）

**Comment by HowcanoeWang** [comment]
感谢啊，最终只剩这些没有抢救回来，其他的都在回收站和历史记录存档里找到了
![image](https://github.com/siyuan-note/siyuan/assets/19968935/2e0a0ef6-9654-4890-8a5b-f9cedf6d6b51)

要是能在复制的旁边，增加一个定位到原文的按钮就更方便了！

**Comment by Chenm4** [comment]
同求一个定位按钮，刚才发现有个文档的大部分图片都丢了，还好最后找到了备份里面的
