### ISSUE TITLE
iPhone手机app无法调用外置iPhone外置浏览器

### ISSUE THREAD

**Issue by TurkeyD** [siyuan-note/siyuan#8384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我的手机是iPhone6sPlus
系统是ios15.7.4
我的ipad
系统是ios15.2

都遇到一个问题是 如果思源笔记里面包含连接URL
当我点击的时候 app就会调用软件内置的浏览器
问题是很卡而且非常不好用 滑动几乎无法使用
其次是浏览器没有标签页 没有返回按钮 我就卡在当前页面
然后是app软件内也没有设置 可以调用外置的浏览器

### Expected result

非常希望能调用外置的浏览器 
望给予帮助 谢谢

### Version environment

```markdown
- Version: 2.8.9
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
我这里是可以打开的，你的链接地址是什么？

https://github.com/siyuan-note/siyuan/assets/970828/c7e885c4-838a-4ada-9298-f08aa46ea36f

**Comment by TurkeyD** [comment]
谢谢V大的回复   回复速度这么快   你这个视频一下就让我明白了
我手机一直禁止使用safari浏览器 我改成了默认打开的是alook浏览器(因为我觉得这个好用点)
所以思源调用的时候无法打开这个浏览器  
但是我在使用ios的obsidian的时候没有出现这个问题 它是可以调用这个"当前默认的浏览器"的 
不知道是不是你这个代码必须指定用safari才能打开

总之问题已经解决了~~🙏感谢🙏

![iShot2023-05-29_11 16 57](https://github.com/siyuan-note/siyuan/assets/69117862/c22bfb5e-e3bb-43b3-b8f8-98e0cf9f1f56)
![441F8DD5-D7D3-48AA-952C-7433313B8C49_1_102_o](https://github.com/siyuan-note/siyuan/assets/69117862/5bb558eb-7c91-46ac-81d0-e3dcbfff40b6)

**Comment by Vanessa219** [comment]
没有找到上图中的这个设置界面 🤦‍♀️

**Comment by TurkeyD** [comment]
iOS 12以后的系统版本：到设置中下拉搜索“屏幕使用时间”-内容和隐私访问限制打开-允许的app-
就可以找到 safari浏览器的按钮~😄

我这边iPhone和ipad关闭之后 思源就调用不了别的浏览器

**Comment by Vanessa219** [comment]
好隐秘的设置，已经可以重现了，谢谢。

**Comment by TurkeyD** [comment]
哦 ? 已经可以调用非safari的浏览器了 是吗?
我该如何操作?是下个版本修复还是我现在重新下一下ios的思源app就可以了?

**Comment by Vanessa219** [comment]
下个版本

**Comment by TurkeyD** [comment]
辛苦了V大🫡🫡🫡🫡🫡---- 回复的原邮件 ***@***.***>发送日期2023年06月05日 10:54 ***@***.***> ***@***.***>***@***.***>主题Re: [siyuan-note/siyuan] iPhone手机app无法调用外置iPhone外置浏览器 (Issue #8384)
下个版本

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/siyuan-note/siyuan/issues/8384#issuecomment-1575961403",
"url": "https://github.com/siyuan-note/siyuan/issues/8384#issuecomment-1575961403",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
