### ISSUE TITLE
移动端云端数据损坏 -Mobile cloud data corruption

### ISSUE THREAD

**Issue by Benjamin-Watson0** [siyuan-note/siyuan#8385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

移动端提示云端数据已损坏。
我觉得我已经按照指引的那条方法尝试了，没有效果。
求助啊！！😭

The mobile side prompts that the data in the cloud is corrupted.
I think I've tried following the one in the guidelines, to no avail.

### Expected result

![Screenshot_20230529_083712](https://github.com/siyuan-note/siyuan/assets/112467275/414f7049-f7f7-4068-b9f1-fd34e54f0f43)

### Version environment

```markdown
- Version: 10
- Operating System: android
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11587085/system-log.zip)

**Comment by 88250** [comment]
需要重建本地仓库和云端目录，不要使用原有的云端目录。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by 88250** [comment]
是的，操作之前最好暂停所有设备的同步，并且云端目录名不能使用已经用过的。

**Comment by 88250** [comment]
要等一个端先上传完再开另一个端，不要两个端同时操作。

**Comment by 88250** [comment]
按照内核日志里面的细节：

```
E 2023/05/29 08:31:11 sync.go:1047: download cloud chunk [a78c148491f280689f5044781256f1ae0fa932a9] failed: cloud object not found
```

在 S3 存储上看下 repo/目录名/objects/a7/下面有没有 8c148491f280689f5044781256f1ae0fa932a9 这个文件。
