### ISSUE TITLE
网页点击`设置`后报错

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

网页打开思源，设置打不开，并报错如下

### Expected result

修复

### Version environment

```markdown
- Version: 2.8.10-dev3
- Operating System: win11
- Browser (if used):
```

### Log file

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6806/stage/build/desktop/main.939d09a6668d7a6398ae.js:2748" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">main.939d09a<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.js:2748</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of undefined (reading 'replace')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.genHTML (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6806/stage/build/desktop/main.939d09a6668d7a6398ae.js:2748:85" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">main.939d09a<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.js:2748:85</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ll (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6806/stage/build/desktop/main.939d09a6668d7a6398ae.js:4365:62" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">main.939d09a<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.js:4365:62</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.click (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6806/stage/build/desktop/main.939d09a6668d7a6398ae.js:4393:21883" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">main.939d09a<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.js:4393:21883</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at HTMLButtonElement.&lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" title="http://localhost:6806/stage/build/desktop/main.939d09a6668d7a6398ae.js:108:6959" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">main.939d09a<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.js:108:6959</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | genHTML | @ | main.939d09a….js:2748
-- | -- | -- | --
  | ll | @ | main.939d09a….js:4365
  | click | @ | main.939d09a….js:4393
  | （匿名） | @ | main.939d09a….js:108

</span></div>
</body>
</html>

**Comment by 88250** [comment]
dev 版的话试下打开开发者工具禁用缓存后强制刷新。

**Comment by terwer** [comment]
还真有用，dev2 前可用下面的刷新方法

![image](https://github.com/siyuan-note/siyuan/assets/3259282/9c7091ea-252f-4c29-b59b-eac8bf072457)
