### ISSUE TITLE
Improve interaction of plugin system settings

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8391]
插件系统插件设置统一风格。

### In what scenarios do you need this feature?

插件的设置大家做的风格都不太一样，并且入口很深。趁早统一避免未来统一困难

### Describe the optimal solution

1. 考虑迁移出现在插件的设置按钮的位置，按钮小，操作深，看是否能把插件设置抽出来，例如左上角的软件菜单中。
2. 统一由思源管理dialog，插件只是操作自己的配置而已
3. 组件使用建议，封装组件最好，不过这个费时费力，可以社区推动。
4. 插件设置设计指南，也可以社区推动。

之前插件系统的就挺好的我觉得，ob，logseq都这样统一，我觉得不无道理。思源设计上需要多努力才行。

**Comment by 88250** [comment]
考虑到可能会存在设置比较特殊的插件，所以单独实现设置界面比较好。

**Comment by mozhux** [comment]
我也觉得统一一个好点，单独实现的可以留口子，但必须有统一默认的。不然目前至少有三种设置方法，很容易乱

**Comment by zuoez02** [comment]
参考一下已经有大量插件的OB和Logseq，统一设置很方便，开发者和用户都很方便的。谁自己想摸复杂的，自己也可以用其他api摸。

现在这种比较乱的，用户学习成本还是比较高一些的。

**Comment by mozhux** [comment]
> 外观的话开发者按照 DOM 结构和使用对应 class 应该就可以统一了，设置入口也和其他软件一样放在已下载中。目前还没想好如何阻止开发者使用其他方式。

应该是指的统一的入口，不是每个点进去的那个设置，而是一个设置，不过软件名称，点了会切换不同的

**Comment by zxhd863943427** [comment]
> 外观的话开发者按照 DOM 结构和使用对应 class 应该就可以统一了，设置入口也和其他软件一样放在已下载中。目前还没想好如何阻止开发者使用其他方式。

不需要阻止，因为有些真的不走统一设置比较方便。

目前的问题是入口太深，而且不好点，就哪么一个小按钮。

此外，如果能像Menu一样友好就好了，使用addSetting的方式添加选项，手撸DOM终究还是不太好，增加了无效功，每个插件作者都要做一遍这种没太大意义的工作。

setting选项我觉得只需要文本输入、下拉框、开关就行，最多再加一个自定义，这样也方便统一风格的显示在一个方便进去的界面。

**Comment by Vanessa219** [comment]
> 应该是指的统一的入口，不是每个点进去的那个设置，而是一个设置，不过软件名称，点了会切换不同的

没明白`而是一个设置，不过软件名称，点了会切换不同的`

**Comment by Vanessa219** [comment]
- [ ] 按钮点击范围改进
- [ ] 添加设置方法 https://github.com/siyuan-note/siyuan/issues/5066
- [ ] 设置深度减少一级

**Comment by mozhux** [comment]
> > 应该是指的统一的入口，不是每个点进去的那个设置，而是一个设置，不过软件名称，点了会切换不同的
> 
> 没明白`而是一个设置，不过软件名称，点了会切换不同的`

![image](https://github.com/siyuan-note/siyuan/assets/46953371/40a4bf07-bb70-4e11-9647-2a7b1427f218)
就lw类似这样的统一的界面。

**Comment by Vanessa219** [comment]
@mozhux 放不下呀，现在没有二级菜单

**Comment by mozhux** [comment]
> @mozhux 放不下呀，现在没有二级菜单

不是二级菜单呢，是一个统一的界面。比如这个设置点开，预期ykg应该是进入类似系统设置那样的一个插件设置中心，集合了各类插件的设置。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/a59f004a-d2a4-4745-8ac2-dbf86ca29388)

**Comment by Vanessa219** [comment]
上个版本在这里加了一个 
<img width="465" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/7fd369d3-2f45-4850-89d8-96d709d3481f">

**Comment by zuoez02** [comment]
不在顶栏的插件不会显示在这里？

**Comment by Vanessa219** [comment]
是的
