### ISSUE TITLE
请问新版本行内样式菜单中合并的块外观样式会保留吗？

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

新版本中块外观菜单与字色菜单合并，字色菜单新增了一排块外观样式，并且可以对选中的行内文字添加样式。
![image](https://github.com/siyuan-note/siyuan/assets/125173405/1eadc690-660e-49ed-b37f-10abd0d785a4)
![image](https://github.com/siyuan-note/siyuan/assets/125173405/58cb19d3-de73-4b67-a3ec-7f6017b1ec0c)
请问这些样式以后会取消吗，也就是会恢复以前的仅对块外观提供这些选择，行内文本不提供这些选择。如果取消后那么已经开始使用这些样式修改行内文本的用户会不会很尴尬（
因为不知道是bug还是特性所以先按bug模板提问了

### Expected result

其实我本来就不知道以前为什么会分成两套，现在合并了也觉得怪怪的。

### Version environment

```markdown
- Version: 2.8.10dev4
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
会保留的，因为重叠功能太多，后面就合并了。
