### ISSUE TITLE
新建一个页面，然后粘贴几千至几万字的时候，会直接卡顿

### ISSUE THREAD

**Issue by qysaber** [siyuan-note/siyuan#8395]
### In what scenarios do you need this feature?

之前尝试把小说直接从wordpress搬到思源，结果发现粘贴的时候太卡了，粘贴完之后，页面右上角的选项是无法打开的，不知道是否有优化的可能性，或者这个速度的瓶颈是？cpu？磁盘？ 我看了下占用都很低，也可能自带的数据库从定位和功能上就不适合做这个？

### Describe the optimal solution

以前在wordpress做这类操作也是这样，一开始时修改了数据库相关参数才好一些，比如允许的字段最大长度等，但遇到几万字的还是不行。

**Comment by 88250** [comment]
你好，直接粘贴会卡的，建议使用导入功能。

**Comment by qysaber** [comment]
ok 我回头试试
