### ISSUE TITLE
新建文件自动加入拼音做别名

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#8396]
### In what scenarios do you need this feature?

在搜索文件的时候有用。

### Describe the optimal solution

新建中文名的文件时候，加入2个别名，全拼，和每个字的拼音首字母。

### Describe the candidate solution

目前我是手工加的，额外还加入对于的英文单词。

**Comment by 88250** [comment]
这个可能通过插件来实现更好些，我们先标记为 Idea 了，后面看下是否有社区开发者感兴趣，感谢反馈。

**Comment by terwer** [comment]
@IAliceBobI 您好，能否给个截图示例，英文别名是在哪里添加呢，直接在标题后面让标题变成双语吗？

可能的话我想做个插件。

**Comment by IAliceBobI** [comment]
> 

伟大的贡献者你好。


我目前文件名中文的居多。
为了查找的时候不切换输入法打字。
能做到这一点就好。

目前我认为其中一个可行的方案就是，在文件的属性里面，添加别名，多个别名逗号隔开。
针对中文名的文件。
全拼，和每个字的拼音首字母，另外能切词，查字典，加入英文单词更好。

目前没截图， [可以调研接口设置属性](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E8%AE%BE%E7%BD%AE%E5%9D%97%E5%B1%9E%E6%80%A7)



> @IAliceBobI 您好，能否给个截图示例，英文别名是在哪里添加呢，直接在标题后面让标题变成双语吗？
> 
> 可能的话我想做个插件。

**Comment by terwer** [comment]
如果是淡出你设置块属性，那还是比较简单的呀。我之前做发布工具的时候，其实已经有一个 custom-slug 的属性咯。他的规则是英文翻译+hash，比如：

MyBatis的二级缓存整合redis

mybatis-s-secondary-cache-integrated-redis-z9qyjo

![image](https://github.com/siyuan-note/siyuan/assets/3259282/cc208f88-3be0-4e7a-a572-f13080b1c5e2)

这个是已经可用的功能了，如果需要，我可以拆分一个插件出来。同时在支持拼音啥的。

**Comment by terwer** [comment]
但是，你说的搜索好像无效果吧

![image](https://github.com/siyuan-note/siyuan/assets/3259282/22da813f-0fa6-43d7-b3ca-d40c1323dc88)

**Comment by IAliceBobI** [comment]
> 但是，你说的搜索好像无效果吧
> 
> ![image](https://user-images.githubusercontent.com/3259282/241743950-22da813f-0fa6-43d7-b3ca-d40c1323dc88.png)

需要再`设置->搜索`里面，开启别名的开关。

**Comment by IAliceBobI** [comment]
> 如果是单纯的设置块属性，那还是比较简单的呀。我之前做发布工具的时候，其实已经有一个 custom-slug 的属性咯。他的规则是英文翻译+hash，比如：
> 
> MyBatis的二级缓存整合redis
> 
> mybatis-s-secondary-cache-integrated-redis-z9qyjo
> 
> ![image](https://user-images.githubusercontent.com/3259282/241742996-cc208f88-3be0-4e7a-a572-f13080b1c5e2.png)
> 
> 这个是已经可用的功能了，如果需要，我可以拆分一个插件出来。同时在支持拼音啥的。
> 
> 关注我的仓库：https://github.com/terwer/siyuan-plugin-custom-slug
> 
> 等开发完成即可上架。

好的。关注了.

**Comment by terwer** [comment]
OK。我刚刚试了可以，开启之后可以。近期我会上架，应该很快，代码基本上现成的。先搞个能用的，慢慢改。

**Comment by terwer** [comment]
@IAliceBobI  已上架集市，可以去插件商店下载啦。

**Comment by IAliceBobI** [comment]
> @IAliceBobI 已上架集市，可以去插件商店下载啦。

我创建后没看到加新属性。另外支持改名吗？

**Comment by terwer** [comment]
需要点击图标，不是自动生成的属性。
![image](https://github.com/siyuan-note/siyuan/assets/3259282/0fe6b8de-b346-41f6-8e5b-c83ee539cd2c)

![image](https://github.com/siyuan-note/siyuan/assets/3259282/b16de871-0521-4347-b467-0cc0f4fe90cd)

其它问题先看看我的README 和 faq

https://github.com/terwer/siyuan-plugin-custom-slug/blob/main/README_zh_CN.md#faq

**Comment by IAliceBobI** [comment]
> 需要点击图标，不是自动生成的属性。目前还没有新建文档的api回调可用。 ![image](https://user-images.githubusercontent.com/3259282/242210591-0fe6b8de-b346-41f6-8e5b-c83ee539cd2c.png)
> 
> ![image](https://user-images.githubusercontent.com/3259282/242210426-b16de871-0521-4347-b467-0cc0f4fe90cd.png)
> 
> 其它问题先看看我的 README 和 faq
> 
> https://github.com/terwer/siyuan-plugin-custom-slug/blob/main/README_zh_CN.md#faq
> 
> 右键打开菜单可以修改 值 ，key 目前不能修改。
> 
> ![image](https://user-images.githubusercontent.com/3259282/242211328-29f9bc7d-09f5-4c1c-8f17-74eb84aadf7d.png)

谢谢，挺好的。

**Comment by terwer** [comment]
有惊喜哟。重命名标题即将支持自动生成。敬请期待~
