### ISSUE TITLE
集市部分主题、模板无法更新

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://ld246.com/article/1685291827107?r=Gaffey
不是所有集市项目都有相同问题，已知主题中dark+有这个问题，群友那边“反向链接巧记单词”这个模板也无法更新。具体见帖子。

### Expected result

正常更新集市项目

### Screenshot or screen recording presentation

见论坛

### Version environment

```markdown
- Version: v2.9.10 dev3
- Operating System: Windows 10 专业版 22H2
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11592569/siyuan.log)

**Comment by 88250** [comment]
经过排查，是因为作者发布的 package.zip 中的版本号没有改哦。
