### ISSUE TITLE
是否能够支持Azure的Openai API

### ISSUE THREAD

**Issue by Pinuslin** [siyuan-note/siyuan#8399]
### In what scenarios do you need this feature?

是否能够支持Azure的Openai API

### Describe the optimal solution

修改openai_base
添加endpoint name、部署模型名称以及版本号即可

**Comment by Pinuslin** [comment]
原本在ai.go的代码为
`type OpenAI struct {
	APIKey       string `json:"apiKey"`
	APITimeout   int    `json:"apiTimeout"`
	APIProxy     string `json:"apiProxy"`
	APIModel     string `json:"apiModel"`
	APIMaxTokens int    `json:"apiMaxTokens"`
	APIBaseURL   string `json:"apiBaseURL"`
}
`

添加一个代码块
`type AzureConfig struct {
	BaseURL        string
	ResourceName   string
	DeploymentName string
	ApiVersion     string
	ApiToken       string
}
`

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/8095

目前暂时不考虑增加，等后面需求多一些时再考虑，谢谢。

**Comment by wherejumpout** [comment]
有越来越多的用户有类似需求了，请考虑支持

**Comment by poptree** [comment]
+1
