### ISSUE TITLE
能否增加设置，允许不对~或*等符号进行markdown转义？

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#8400]
### In what scenarios do you need this feature?

能否增加设置，允许不对~或*等符号进行markdown转义？会对写作，尤其是含有数字、数学相关的写作造成非常大的困扰

### Describe the optimal solution

能否增加设置，允许不对~或*等符号进行markdown转义？

**Comment by 88250** [comment]
这个是基础功能，不加配置了，加了的话可能会对数据一致性造成问题，比如之前的配置是不解析标记符，后面又打开了标记符，这种情况数据会出问题。

建议还是用转义符顶顶，谢谢。

**Comment by pisceswb** [comment]
> 这个是基础功能，不加配置了，加了的话可能会对数据一致性造成问题，比如之前的配置是不解析标记符，后面又打开了标记符，这种情况数据会出问题。
> 
> 建议还是用转义符顶顶，谢谢。

感谢D大的解释。那能否换一种方式，增加设置选项，允许在输入~或*时，自动将其变为转义字符\~或\*形式？这两个字符的转换对数学公式等的输入计算干扰太大了，谢谢！

**Comment by pisceswb** [comment]
> > 这个是基础功能，不加配置了，加了的话可能会对数据一致性造成问题，比如之前的配置是不解析标记符，后面又打开了标记符，这种情况数据会出问题。
> > 建议还是用转义符顶顶，谢谢。
> 
> 感谢D大的解释。那能否换一种方式，增加设置选项，允许在输入~或*时，自动将其变为转义字符\\~或\\*形式？这两个字符的转换对数学公式等的输入计算干扰太大了，谢谢！

**Comment by 88250** [comment]
公式的话使用行级公式或者块级公式吧，不需要转义。

**Comment by pisceswb** [comment]
> 公式的话使用行级公式或者块级公式吧，不需要转义。

1~2天/小时/分，
1*2*3=
等都会收到其干扰，对于学生和有数据输入时需求的人的影响还是挺大的。改进的话，能够增加很大的便利性☹

**Comment by terwer** [comment]
其实有折中办法，输入的时候加入 \ 就不会转义。之前折腾群里讨论过，或者用行类代码包裹。或者上面 D 打说的公式应该也可以。

例如

```
\*
\~
```

或者  

```
`*`  
`~`
```

**Comment by pisceswb** [comment]
谢谢建议，但在这样的正常书写中还是不方便，例如一个正常的句子中：
首先，准别。。。，然后把1\~2g盐加入到100\~200ml水中，加热3\~4分钟。后面再继续处理。。。。

**Comment by 88250** [comment]
大概只能这样了，加了开关目前不好评估会不会有副作用。另外，也可以等社区开发者探索一下是否能用插件实现。

**Comment by pisceswb** [comment]
> 

感谢D大，🌷🌷🌷

**Comment by pisceswb** [comment]
反馈一个含有\~符号的句子，删除时的问题。
1这是一个测试1\~2这是一个测试2~3这是一个测试3\~4这是一个测试4\~5这是一个测试1\~2ml水
![Video_2023-05-30_10290620235301038272](https://github.com/siyuan-note/siyuan/assets/104658457/06601806-157e-406c-b93a-207971e0aab8)

**Comment by 88250** [comment]
我这里转义粘贴后重现不了问题哦。

**Comment by pisceswb** [comment]
把1\~2g盐加入到100\~200ml水中，加热3\~4分钟。
麻烦D大测试一下这句话，放在首行第一次删除\~2无反应，再次删除能够正常删除。放到第二行，就出现了上面GIF中的情况了。
![image](https://github.com/siyuan-note/siyuan/assets/104658457/d547fc11-e00e-4d91-a144-6b2bdb888a1c)

**Comment by 88250** [comment]
@pisceswb 确实放到第二行可以重现问题，稍后修复。

**Comment by pisceswb** [comment]
哪位大神能够好心写一个插件，谢谢！

**Comment by pisceswb** [comment]
暂时找到替代办法，供参考，希望有人能够写一个插件。使用& # 126 ；代替\~， 使用& # 42 ；代替\*
![image](https://github.com/siyuan-note/siyuan/assets/104658457/425bf408-1d08-451f-8c05-70075c944d9c)

**Comment by pisceswb** [comment]
请问D大是否考虑添加功能，
**暂停转义的markdown字符：\*, \~**
字符可自己填写。
填写上的字符，在实时输入时，将被替换为& # 126 ；形式
谢谢！

**Comment by 88250** [comment]
目前不考虑了，谢谢。

**Comment by 88250** [comment]
目前已经支持，设置 - 编辑器 - Markdown 标记
