### ISSUE TITLE
The sidebar panel will no longer pop up when dragging kanban on the mobile phone

### ISSUE THREAD

**Issue by DionathanJoestar** [siyuan-note/siyuan#8402]
### In what scenarios do you need this feature?

手机端拖动较长表格时会弹出设置栏

https://github.com/siyuan-note/siyuan/assets/133741096/d156cacf-f1a0-410f-8261-6461627bf799

### Describe the optimal solution

操作表格时不要弹出设置界面

**Comment by Vanessa219** [comment]
这个看着不像 table，table 这样是可以的


https://github.com/siyuan-note/siyuan/assets/970828/f2d124d0-1577-4cda-bb5d-1ffd6c5b9d6e

**Comment by DionathanJoestar** [comment]
> 这个看着不像 table，table 这样是可以的
> 
>  10_1685454613.mp4

你这么说我反应过来，这是dark+的看板视图，不过savor的看板视图也有这种情况，是不是不应该反馈到这里，应该反馈给萌新？

**Comment by DionathanJoestar** [comment]
> 这个看着不像 table，table 这样是可以的
> 
>  10_1685454613.mp4

我给萌新和roy说了，看看你们谁能修复吧。

**Comment by Vanessa219** [comment]
我这里兼容了一下吧。感谢反馈
