### ISSUE TITLE
Unable to paste PDF annotation ref

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8403]
对PDF的这一部分选中文字建立批注似乎无法建立锚文本

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![SiYuan_UUOq49Bu47](https://github.com/siyuan-note/siyuan/assets/125173405/7d03cd0d-8906-40e6-9e87-d5fbc2e0f205)
位置是第五页的最下面的段落中的第二行开始。
适配中第一次复制的文字可以建立锚文本，但第二次第三次复制的部分无法建立。尽管批注是正常的。
pdf文件：
[领属结构的语义构成_张伯江-20230530093446-wb9zy5o.pdf](https://github.com/siyuan-note/siyuan/files/11595081/_.-20230530093446-wb9zy5o.pdf)

### Expected result

希望能解决或解释原因

### Version environment

```markdown
- Version: 2.8.10dev4
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by chenshinshi** [comment]
才发现不止这一处，对第七页的最后一行
![image](https://github.com/siyuan-note/siyuan/assets/125173405/9f9ce12c-6752-44ec-a6aa-78396ad1e3fb)
建立批注也无法复制建立锚文本。

**Comment by Vanessa219** [comment]
主要是由于该 PDF 本身复制的时候会出现换行和终结字符，可在官网 https://mozilla.github.io/pdf.js/web/viewer.html 上传 pdf 后进行复制查看。我们目前只能移除这些字符，想要复制完整的话还需要修改该 PDF 里面的内容。
