### ISSUE TITLE
Using displayName instead of plugin name in Plugin detail page.

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/4801955/ea5be923-6fbf-42a3-b958-e616d2ae427d)

Use displayName for better UI.

### Expected result

Use displayName

### Version environment

```markdown
- Version: 2.8.9
- Operating System: Win11
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
Thanks for the feedback, we will improve it later.
