### ISSUE TITLE
Linux版系统通知区弹出菜单文本信息错误

### ISSUE THREAD

**Issue by grassvalley** [siyuan-note/siyuan#8407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

即便是主程序窗口已经是隐藏状态，单击系统通知区图标，弹出的菜单信息依然是“隐藏主窗口”。不过不影响菜单功能。

### Expected result

如果主窗口是隐藏的，菜单信息应该是“显示主窗口”，如果主窗口是显示的，菜单信息应该是“隐藏主窗口”。

### Version environment

```markdown
- Version: 2.8.4 ？没有显示版本的菜单功能
- Operating System: 深度 20.9
- Browser (if used):
```

### Log file

哦哦

**Comment by 88250** [comment]
你好，你用的是 Alt+M 最小化还是只是窗口右上角的最小化？如果是窗口的最小化到任务栏的话托盘区菜单是显示“隐藏窗口”的。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by 88250** [comment]
补充一下我测试的截图：

![image](https://github.com/siyuan-note/siyuan/assets/873584/37563009-9632-48e0-bb79-5cade8c2fd0f)

**Comment by grassvalley** [comment]
原来还可以使用 alt+m 来隐藏窗口啊！
我是使用窗口按钮，最小化，或者 关闭，这样的操作，导致上述问题的。
