### ISSUE TITLE
希望集市内也有搜索功能

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8409]
### In what scenarios do you need this feature?

现在插件越来越多了，无论是对已下载插件的管理，还是查找需要的新插件都慢慢变的不那么轻松了。

### Describe the optimal solution

希望集市内也有搜索功能能，可以方便查未下载的插件，也可以用搜索来方便管理已经下载的插件。
可以考虑模糊词搜索就更好了。

### Other information

![image](https://github.com/siyuan-note/siyuan/assets/87182333/ecf00c27-9f21-4834-912c-e4ead072f2ff)
![image](https://github.com/siyuan-note/siyuan/assets/87182333/e5610416-2d8f-429b-83ab-42e86c77bf0a)

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/8173
