### ISSUE TITLE
Frontend API: Register a shortcut key for a plugin command

### ISSUE THREAD

**Issue by red-co** [siyuan-note/siyuan#8410]
### In what scenarios do you need this feature?

Using shortcut keys is more convenient than clicking buttons.
(Currently it seems that only setting keyboard listener can solve this problem)

### Describe the optimal solution

Register a shortcut key for the command.

**Comment by 88250** [comment]
Please checkout here, `addCommand` https://github.com/siyuan-note/siyuan/issues/5066#issuecomment-1147167160
