### ISSUE TITLE
Put the unpin plugins in the second menu on the mobile

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8411]
### In what scenarios do you need this feature?

手机不如电脑空间那么大，菜单栏显示一些经常需要用到的插件按钮就可以了，如果全都一股脑的显示在菜单栏处，是不太合适的。
但是有时候有需要这个插件的功能，只是有些不需要他显示菜单在这里，所以没有选择直接关闭该插件。

### Describe the optimal solution

还是像现在这样在手机菜单栏默认显示有按钮的插件，提供一个让用户可以自行选择是否隐藏在手机菜单栏的显示该插件按钮的功能。

### Other information

![image](https://github.com/siyuan-note/siyuan/assets/87182333/c88a9b62-1340-4bad-a76b-be18b3af6cdf)

**Comment by 88250** [comment]
这个暂时不考虑了，感谢提议。

**Comment by Vanessa219** [comment]
用桌面端的 pin 来做如何？unpin 的就放在二级菜单

**Comment by Aiviokoo** [comment]
> 用桌面端的 pin 来做如何？unpin 的就放在二级菜单

可以的，感觉V姐刚做好的这个 https://github.com/siyuan-note/siyuan/issues/8345 放到手机端就是这条的完全体了❤️
![image](https://github.com/siyuan-note/siyuan/assets/87182333/771fae4a-89e6-4ad8-b7b5-d0837760c894)
