### ISSUE TITLE
Improve `Save query criteria` and `Remove query criteria` function entry

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8412]
### In what scenarios do you need this feature?

有很多情况，用户想要保留之前的查询文本，比如：
1. 切换搜索的查询条件时
    ![image](https://github.com/siyuan-note/siyuan/assets/5683995/43f50453-a798-483d-a611-edcfd85a18db)

2. 用户有非常大的概率，在下一次查询时，用之前的查询文本。比如上一次查询进了一个页面，发现不是想要的，就需要再输入一遍，或者从搜索历史下拉框找到之前的查询文本

在论坛中，已经有多人提到这个问题，希望考虑

- [搜索预设包含关键词，切换预设的时候建议用预设内的关键词](https://ld246.com/article/1683404787982)
- [搜索一个小小建议，切换查询条件时，不要清除查询文本](https://ld246.com/article/1684370403738)

### Describe the optimal solution

....

**Comment by Vanessa219** [comment]
可参照 https://github.com/siyuan-note/siyuan/issues/7988 ，还有问题的话我们继续讨论。

**Comment by zhoutaosheng** [comment]
> 可参照 #7988 ，还有问题的话我们继续讨论。

看了相关的帖子，理解最大的问题可能是：**保留上一次查询文本**与现有的**命名查询**，在设计上有一定冲突

但这个问题，反复有人提出，被**反复讨论**。说明：**保留上一次查询文本**是一个非常自然而然的设计，无论是各种IDE（Jetbrains、VS），还是各种文本编辑器，都在搜索时**保留上一次查询文本**。

当然**命名查询**也是非常好的设计，能解决很多问题，比如全局搜索时，内容过多，提前设计**命名查询**过滤不同的内容块

对于用户而言，两个都好，两个都要。设计上，不知道可不可以，二者结合

1. 在Ctrl+P，打开搜索时
  - **命名查询**使用上一次的**命名查询**，跟现在保持一致
  - 文本，用上一次的查询文本
2. 如果用户选中文本，在Ctrl+P，打开搜索时
  - **命名查询**使用上一次的**命名查询**，跟现在保持一致
  - 文本使用用用户选中的文本

当然用户并不知道实现上的问题，所以一切以siyuan自己的设计思路为准。

不过，有另一个更小的建议，能否给搜索历史一个快捷键，比如Jetbrains IDE，会给`Alt + ↓`，弹出搜索历史
![image](https://github.com/siyuan-note/siyuan/assets/5683995/82c1b603-b461-46f5-bab5-92c1c821ebec)

**Comment by Vanessa219** [comment]
第二点目前是这样的，如果不是的话麻烦描述一下重现步骤。第一点也许可以再改进下。

alt+上下 我这里会直接更新搜索关键字，不是弹出历史列表。

**Comment by zhoutaosheng** [comment]
> 第二点目前是这样的，如果不是的话麻烦描述一下重现步骤。第一点也许可以再改进下。

确实是这样的，赞

> alt+上下 我这里会直接更新搜索关键字，不是弹出历史列表。

我这里，`Alt + ↓`和`Alt + ↑`，跟直接`↓`、`↑`的效果，是一样的，在搜索结果中导航，不会使用Search History中的查询，来作为当前的查询文本

**Comment by littlecoby** [comment]
附议一下，这里和论坛原贴已经描述的很贴切（至少我的）实际使用情况了

**Comment by Vanessa219** [comment]
1. 想了下还是有点问题，那搜索条件、目录什么的都无法保存上一次的。如果都保存上一次的，这样就失去了保存查询条件的意义。现在只要点击了清空查询条件都会保存上一次的，或者把清空查询条件移到查询条件的前面并改名为保存上一次查询？
<img width="869" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/cebf86ca-2a14-448b-8bd3-26e5b729a539">

3. https://github.com/siyuan-note/siyuan/issues/8446

**Comment by littlecoby** [comment]
搜索条件有很多项目：搜索文本，路径，路径是否包含子文档，搜索方式，类型，排序，分组，布局。试着捋一捋（1）打开搜索面板时，哪些项目应该和上一次保持一致；（2）“保存查询条件”时，应该保存其中哪些项目。

(1) 如果搜索界面像文档树一样是侧栏面板，更自然会认为“呼入/呼出”操作是在“显示/隐藏”面板，而不是“打开/关闭”。既然只是隐藏，那么重新显示的时候就应该是和上次一模一样的搜索条件。思源的搜索是弹框，但视为“显示/隐藏”应该更方便，即保持上一次搜索的所有条件，因为：
  (a) 用上一次的搜索条件概率大，如题主提出的第二点，或者不小心按掉了弹框（虽然几率不高）；
  (b) 即使不用上次搜索条件，清空新搜索要改动的地方（估计是文本、路径、包含子文档）也比重新输入一次简单，比如像上面评论的把按钮移动到更可及的地方。
  (c) 特殊情况如题主所说，如果已经选中了文本再打开搜索，那么文本替换为选中值，其它条件仍保留上一次。

(2) “保存查询条件”应该保存的项目各人使用习惯不同，那就让用户自己在“设置”中选择保存哪些（我个人会选除了文本和路径之外的其它项目）。这样以下几点可能会更清晰：
  (a) 命名查询如何高亮显示（#7751）：只要当前搜索条件中配置的项目与命名条件相同，就把相同的命名高亮；只要不同，就不高亮。这样也便于知道什么时候需要/不需要新保存一个命名查询。选择哪些项目是用户自己设的，所以可能不会迷惑。
  (b) 切换搜索的查询条件：把配置的项目变更为命名查询的值，而其它项目不变。比如我不配置文本，则切换命名查询时文本就不变，实现了题主说的第一点。
  (c) 更改配置项目：如果增删项目，之前保存的命名查询中的项目也随之增删，需要在“设置”中增加一个“确定”按钮，并警告点击“确定”后会发生的变化。用户配置哪些项目的习惯在一段时间内应该是恒定的，所以修改是一个低频事件，“确定”按钮也减少了误操作的可能性。写明警告之后，即使让之前保存的发生变化，也是用户在知情情况下自己选择的结果。

**Comment by Vanessa219** [comment]
1. 搜索放在面板上的话可以使用页签搜索来替代
2. 这样会增加复杂度，一般普通用户可能会更难上手

IDEA 中好像没有保存查询条件这一说法，是不是我们加了这个功能后导致用户无法适应？也许这个需求是个导致灾难的伪需求？

**Comment by zhoutaosheng** [comment]
> 1. 搜索放在面板上的话可以使用页签搜索来替代
> 2. 这样会增加复杂度，一般普通用户可能会更难上手
> 
> IDEA 中好像没有保存查询条件这一说法，是不是我们加了这个功能后导致用户无法适应？也许这个需求是个导致灾难的伪需求？

其实也不是，保存查询条件，还是比较有用的需求，比如下图中，用户设置了两组条件
![image](https://github.com/siyuan-note/siyuan/assets/5683995/58821c92-34dd-45d7-beee-8e29ad656dbf)

1. 在所有文档中查询，并且查询结果按文档分组
2. 只查询标题和页面

这两组条件，如果没有**保存查询条件**这个功能，一点点勾选，还是比较麻烦的

**Comment by littlecoby** [comment]
> 1. 搜索放在面板上的话可以使用页签搜索来替代
> 2. 这样会增加复杂度，一般普通用户可能会更难上手
> 
> IDEA 中好像没有保存查询条件这一说法，是不是我们加了这个功能后导致用户无法适应？也许这个需求是个导致灾难的伪需求？

1. 对，页签就像面板。这里是为了说明“保持上一次搜索的所有条件”的合理性。
2. 上手的话不一定会增加复杂度，把默认设置设成和现在（v2.9.0）的一样就行了，使用上没有变化。从相关issue和论坛帖子来看，争议背后的主要分歧在于“保存查询条件”时应该包括哪些项目，让用户自己设置就能解决了。而且能让2a,b两点更清晰。

**Comment by Vanessa219** [comment]
默认设置一样，还是无法解决新用户目前不知道怎么保留上一次查询的问题。我先把清空放在外面并更改一下文案，再看看还有没有人报这样的问题。

**Comment by littlecoby** [comment]
> 默认设置一样，还是无法解决新用户目前不知道怎么保留上一次查询的问题。我先把清空放在外面并更改一下文案，再看看还有没有人报这样的问题。

“清空”和“保留上一次”在需求上还是有些区别的。
“清空（查询文本）”在删除查询框中长文本时比“全选+删除”方便。
“保留上一次”做成呼出搜索框时的默认行为看上去自然一些。如果做成按钮可能会让用户不清楚上一次是指哪一次。

**Comment by zhoutaosheng** [comment]
> 1. 搜索放在面板上的话可以使用页签搜索来替代
> 2. 这样会增加复杂度，一般普通用户可能会更难上手
> 
> IDEA 中好像没有保存查询条件这一说法，是不是我们加了这个功能后导致用户无法适应？也许这个需求是个导致灾难的伪需求？


另外，查询条件中，除了包含查询类型、排序之类、是否分组的条件之外，还包含了查询文本，不知道这是不是造成这块功能很难设计的原因
我觉得，**查询条件，不应该包含查询文本**

**Comment by Vanessa219** [comment]
> 我觉得，查询条件，不应该包含查询文本
如果不包含的话，这个保存查询条件就会有缺失

@littlecoby 感觉为了避免这个问题，加深其他操作的复杂度来进行解决可能会引入更多的问题。

**Comment by littlecoby** [comment]
“罪魁祸首”还是“保存查询条件”以及可选项太多了 hhh，不确定用户们的使用习惯。

上面提议的是否保存文本和路径猜想是容易习惯不同的地方，所以加个可选项。如果都勾上，就和现在相同，使用上没有改变。

**Comment by Vanessa219** [comment]
这个版本先添加清空查询条件按钮后再看看反馈吧
