### ISSUE TITLE
添加默认工作空间的设置

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8413]
### In what scenarios do you need this feature?

由于我开发和自己使用的工作空间是分开的，所以经常需要切换。

我希望我每次打开的时候都能默认打开自己使用的工作空间，但是经常却默认开启开发空间。

我实在搞不清楚思源到底会默认打开那个工作空间。

### Describe the optimal solution

添加一个直观的设置选项，比如在工作空间的 menu 当中添加一个「将此空间设置为默认空间」之类的按钮。 

![image](https://github.com/siyuan-note/siyuan/assets/27268127/79a3c087-cb6c-4b0a-8a87-8d43bd6394b8)

**Comment by terwer** [comment]
+1
我目前是用来两个快捷方式的，但是还是不够直观。

![image](https://github.com/siyuan-note/siyuan/assets/3259282/a2fd4c4b-a834-4191-8d7b-bf624f2c5f3b)

之所以这么做，是因为默认情况打开本体空间是哪个好像全靠运气。如果有默认设置就好了。

**Comment by zxhd863943427** [comment]
实际上默认打开的是最后关闭的工作空间……不过确实有个默认工作空间好一点。

**Comment by 88250** [comment]
这个建议用快捷方式指定启动参数，感谢反馈。
