### ISSUE TITLE
可否为插件开放「完成同步」的事件

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8414]
### In what scenarios do you need this feature?

我在开发插件的时候遇到了一个问题，由于插件在同步之前启动，所以插件自动创建的日记可能会和同步过来的日记冲突。

https://github.com/frostime/siyuan-dailynote-today/issues/87

我目前想到的方案就是在前端完成同步后，通过总线通知一下各个插件，然后让他们自己处理同步冲突问题。

如果方便的话，不知可否增加一个 event 事件。

### Describe the optimal solution

新的一个事件，诸如：`on-sync-done` 之类的，似乎也不需要什么参数。

**Comment by Vanessa219** [comment]
参考以下代码就可以实现了，如果还有问题继续留言跟帖。
<img width="558" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/d4d2628e-d825-4018-928b-1c645c3cc161">
```
this.eventBus.on("ws-main", this.wsEvent);
```

**Comment by frostime** [comment]
请问 syncing 的 ws-main event是在什么时候会被调用？开始同步的时候？同步结束的时候？还是都会被调用？

**Comment by Vanessa219** [comment]
都会调用

data.code: 0  syncing; 1 success; 2 error.
