### ISSUE TITLE
页面大小过小时，顶部出现3点按钮，点击3点按钮无效

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

具体见图片描述
新版本已经默认保留3大金刚了，于是思源窗口很小的时候，上面插件就会没有插件的一些按钮，然后多了这3个点，但是好像不能点击它，我感觉可能是个bug，既然有这3点，应该是设计来点击3点 就能出现因为空间不足而隐藏了的按钮的。

### Expected result

希望点击时能显示出 隐藏的按钮 可供点击

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/87182333/4c692633-94b2-4c76-a3b1-70d8cc364fa9)

### Version environment

```markdown
- Version: v2.8.10-dev4
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11599854/system-log.zip)

**Comment by 88250** [comment]
默认主题也不行吗？

**Comment by Aiviokoo** [comment]
> 默认主题也不行吗？

我又新开了个空间测试了一下，是可以的。
然后随机下了个放在右边顶栏的插件，再缩小就失效了（比如下图这个）
![image](https://github.com/siyuan-note/siyuan/assets/87182333/73f6c42c-3c1d-4f1e-9dbd-adab2022a288)
