### ISSUE TITLE
Set read-only mode for individual documents

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#8417]
对单个文档单独设置只读模式

### In what scenarios do you need this feature?

阅读导入的外部大文件的时候有用，由于的导入的书籍，不想误修改。
同时保持其他文件可以修改，方便做笔记。

### Describe the optimal solution

只读模式只对一个文件有效。或者每个文件单独一个额外的开关

**Comment by mozhux** [comment]
支持

**Comment by luo-chuan** [comment]
这个可以有

**Comment by IAliceBobI** [comment]
是否可以在只读模式下，额外破例，允许创建引用。就是允许一边阅读，一边整理概念。

**Comment by 88250** [comment]
> 是否可以在只读模式下，额外破例，允许创建引用。就是允许一边阅读，一边整理概念。
> 
> 我有个模糊的想法：把sy文档看做一个pdf，可以做标注，但不改内容。
> 
> 不让改内容就是担心，把文档里的一些比如数字改了，自己都不知道。

这个估计是不行，只读模式下只能做到不变更内容。
