### ISSUE TITLE
Provide hook functions for the document life cycle, for example: onDocCreated, onDocDeleted

### ISSUE THREAD

**Issue by terwer** [siyuan-note/siyuan#8420]
### In what scenarios do you need this feature?

In some cases, we need to do some actual operations, for example: after the document is created, do some processing on some attributes of the document's title, etc.

### Describe the optimal solution

Hook functions that can provide document life cycle, for example: onDocCreated, onDocDeleted

It may like

```ts
const onDocCreated = async (doc: DocInfo) => {
   ...
}
```

We define this in plugin,the the function is auto trigger at the right time

**Comment by zuoez02** [comment]
Hook functions are defined for plugin lifecycle control, not outside events.

Use `this.eventBus.on('eventName', () => {})` is better.

**Comment by terwer** [comment]
ws-main 的 rename 事件可以实现。
