### ISSUE TITLE
Add `loaded-protyle` to eventbus

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8421]
### In what scenarios do you need this feature?

这里[自动更新目录](https://github.com/TinkMingKing/siyuan-plugins-index/issues/8)，需要在打开文档块时自动更新文档块下的目录列表

### Describe the optimal solution

需要添加相关事件事件

**Comment by zxhd863943427** [comment]
能否泛化为open-protyle？因为不只有打开文档有内容的刷新。这个应用更广泛一点。

**Comment by Vanessa219** [comment]
他这个可能需要页面加载完成才行，那改为 `onload-protyle`

**Comment by TinkMingKing** [comment]
> 他这个可能需要页面加载完成才行，那改为 `loaded-protyle`

我监听这个事件去更新块，更新完，protyle中被更新的块并不会及时更新，需要再次打开文档才会刷新，或者我必须加入延迟，我该如何让它及时更新
