### ISSUE TITLE
希望能增加朗读插件

### ISSUE THREAD

**Issue by nscmiaoxin** [siyuan-note/siyuan#8423]
### In what scenarios do you need this feature?

已经可以用插件实现书籍导入与渐进式阅读，希望大神能开发朗读文章插件，谢谢！

### Describe the optimal solution

插件解决，朗读指定位置之后的文本

**Comment by 88250** [comment]
我们归入 Idea 中了，谢谢。

**Comment by nscmiaoxin** [comment]
> 我们归入 Idea 中了，谢谢。

感谢感谢，期待大神制作！
