### ISSUE TITLE
加载速度太慢

### ISSUE THREAD

**Issue by 0nion1** [siyuan-note/siyuan#8425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Mac加载速度太慢

### Expected result

加快打开速度

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

x

**Comment by 88250** [comment]
目前暂时没有优化空间了，后续如果还有更好的方案会考虑，感谢反馈。

**Comment by 0nion1** [comment]
再提一个issue 就是我能不能做二级或者三级的目录，比较方便做分类。

**Comment by 88250** [comment]
直接用文档就行了，思源是父子文档结构。
