### ISSUE TITLE
安全模式不完善

### ISSUE THREAD

**Issue by svtardust** [siyuan-note/siyuan#8428]
### In what scenarios do you need this feature?

安全模式开启与关闭问题

### Describe the optimal solution

**安全模式开启时**，已安装所有插件应处于未启用(即关闭)状态，同时插件入口方法（如onload(),unonload()等）应被禁止调用，现在来看，当安全模式开启时，某些插件如heatmap控制台报错，说明onload()方法可被调用，关闭安全模式后插件处于启用状态，这与安全机制不太符合。

**安全模式关闭时**，应当再设置中增加再次启用安全模式按钮，同时需要调用每个插件的unonload()方法，关闭插件。

**Comment by 88250** [comment]
你好，这个不是安全模式，一旦信任以后就无法关闭了，只能手动禁用插件。
