### ISSUE TITLE
Improve the interaction of cloud inbox content conversion into note

### ISSUE THREAD

**Issue by DionathanJoestar** [siyuan-note/siyuan#8429]
建议优化云端收集箱的工作流程

### In what scenarios do you need this feature?

现在云端收集箱的工作流程如下：
1. 点开收集箱窗口——更多——刷新——勾选——点击更多——移动——随便找个笔记本——确定——找到新建文档——复制——打开目标文档——粘贴——整理
2. 点开收集箱窗口——更多——刷新——勾选——点击更多——移动——打开dailynote笔记本——按年月翻找本月文档（笔记本——dailynote——年——月）——确定——整理
算下来，每次整理一次收集箱，需要点击至少12下鼠标。如果一个人每天一整理，一周就要点击鼠标84下。。。。

### Describe the optimal solution

其实后半段流程本身可以简化，而且思源有现成的机制。希望能用新建文档，整合后半段流程，在移动的时候直接新建文档到dailynote中去，甚至最好设置一个默认笔记本，可以进一步减少操作是最好的了。。
![image](https://github.com/siyuan-note/siyuan/assets/133741096/823e4bee-ee99-4e90-aa39-a4c0dfbacde3)

**Comment by Aiviokoo** [comment]
确实有些麻烦，比如不能直接右键就选择移动了，要 勾选——再点顶部的更多 ，这些多的步骤都是负担了
![image](https://github.com/siyuan-note/siyuan/assets/87182333/c7305c18-d128-4011-9c78-0ba00b905b7e)

**Comment by zxhd863943427** [comment]
我记得以前云端收集箱是能拖动到笔记的，怎么现在拖动不了了？

**Comment by 88250** [comment]
考虑了下，先不加配置项了。

在每个项目后增加一个 移动 按钮？

![image](https://github.com/siyuan-note/siyuan/assets/873584/ae1387f3-451d-43cc-8fde-6b640de2a79c)

**Comment by 88250** [comment]
另外，考虑下是不是把 `⋮` 二级菜单去掉，直接将按钮放出来 @Vanessa219

**Comment by Aiviokoo** [comment]
> 考虑了下，先不加配置项了。
@88250 好吧，D大记得让右键也可以唤醒移动哟
>  ![image](https://user-images.githubusercontent.com/87182333/242520837-c7305c18-d128-4011-9c78-0ba00b905b7e.png) 
我个人最理想的想法就是，云端收集箱配置好后一个快捷键甚至是不用快捷键，就像同步一样，自动就到了指定笔记本或笔记页下了 ![image](https://user-images.githubusercontent.com/87182333/242523229-461e8c56-4574-422a-b78b-d5e22cdd18c8.png)

**Comment by 88250** [comment]
直接点移动和右键好像没有区别啊？

**Comment by Aiviokoo** [comment]
> 直接点移动和右键好像没有区别啊？

如果不点前面的框选就可以点移动那就不用加的

**Comment by DionathanJoestar** [comment]
> 另外，考虑下是不是把 `⋮` 二级菜单去掉，直接将按钮放出来 @Vanessa219

二级菜单去掉是非常好的。不过操作的大头依然在后面，也就是移动之后，插入文档树的时候。是否可以像3楼所说，直接拖动呢？
![image](https://github.com/siyuan-note/siyuan/assets/133741096/369604e2-f6ed-4c6e-93fa-67f9b7045f83)

**Comment by DionathanJoestar** [comment]
> 直接点移动和右键好像没有区别啊？

拖动似乎是最优解？可以不用点击前面的框，可以不用选择文档树。二级菜单去掉以后，就需要两步就能完成整理，刷新——拖动。

**Comment by 88250** [comment]
拖拽插入不行，只能用复制粘贴。因为文档编辑器目前无法支持行级文本拖拽。

**Comment by DionathanJoestar** [comment]
> 拖拽插入不行，只能用复制粘贴。因为文档编辑器目前无法支持行级文本拖拽。

综合上面的信息，换个角度，是否在这里加入一键复制会比移动更能让人接受？
![image](https://github.com/siyuan-note/siyuan/assets/133741096/3e4c729f-4fce-4d0d-b651-b070a9007675)

**Comment by 88250** [comment]
整篇复制的意思吗？

**Comment by AugustTuan** [comment]
我试验了一下，使用思源的云端收集箱，其效率并没有比我发送到文件传输助手，然后电脑端粘贴到目标文档快，最终步骤数量差不多

**Comment by 88250** [comment]
@AugustTuan 你说的是微信的 文件传输助手？

**Comment by AugustTuan** [comment]
> @AugustTuan 你说的是微信的 文件传输助手？

是滴，微信->思源云端收集箱很方便，但是思源云端收集箱这个模块和思源的文档之间互通性却很差，感觉和使用思源以外的一个暂存平台一样。

**Comment by 88250** [comment]
微信的话要用思源小助手，Android 上可以添加到桌面，用于简单速记要比文件传输助手快捷一些。

**Comment by 88250** [comment]
这个 issue 我们就是在讨论如何让收集箱面板使用起来更快捷。

**Comment by AugustTuan** [comment]
另外思源的云端收集箱并不是单独运营的一个账号，而是和链滴凑在一块的。导致和云端收集箱发送的很多内容，总是会被一条一条地登录信息给挤掉。
最后总是几条信息之间夹着好多登录信息。
![image](https://github.com/siyuan-note/siyuan/assets/37429029/a4dd4407-20c5-4d74-b1da-6636c65b4c60)

![image](https://github.com/siyuan-note/siyuan/assets/37429029/6df496ad-d018-4a78-beb3-547c4474edfe)

**Comment by AugustTuan** [comment]
还有就是思源云端收集箱因为是链滴公众号，所以如果是平台浏览的一些链接想要直接分享进云端收集箱，是没办法用微信的分享功能，只能自己复制粘贴

**Comment by 88250** [comment]
用思源小助手吧，公众号确实会有其他消息混在里面。

**Comment by AugustTuan** [comment]
> 微信的话要用思源小助手，Android 上可以添加到桌面，用于简单速记要比文件传输助手快捷一些。

我试试

**Comment by Aiviokoo** [comment]
> 微信的话要用思源小助手，Android 上可以添加到桌面，用于简单速记要比文件传输助手快捷一些。
我就添加到桌面上的，简单，输入端几乎就是微信发消息的体验。
目前不太好用的点就是这个issues提的，在思源里整理的步骤过多

**Comment by 88250** [comment]
@AugustTuan 另外，公众号登录消息推送可以关闭的 https://ld246.com/settings/function

**Comment by AugustTuan** [comment]
> @AugustTuan 另外，公众号登录消息推送可以关闭的 https://ld246.com/settings/function

了解，感谢D大

**Comment by DionathanJoestar** [comment]
> 整篇复制的意思吗？

是的，整体复制相较于移动，重点在于移动强制性选择路径，但是路径还不能保存，比较深的路径每一天重复性操作会显得非常繁琐。
而我们现在有各种插件可以一键打开dailynote，相较而言，选择路径反而十分漫长。整体复制+挂件也能讲整理步骤缩短到原来的1/4，即复制-打开dailynote-粘贴。
对于那些不用dailynote的用户，他们有自己的文档树管理规则，对他们来说，在移动界面一个一个翻还真不如复制以后ctrl+F查找的快

**Comment by AugustTuan** [comment]
> > 微信的话要用思源小助手，Android 上可以添加到桌面，用于简单速记要比文件传输助手快捷一些。
> 
> 我就添加到桌面上的，简单，输入端几乎就是微信发消息的体验。 目前不太好用的点就是这个issues收集下那个，

嗯嗯，我也是这个感觉，微信到云端收集箱特别方便，但是云端收集箱和思源文档之间的障碍却很多，整理到文档的流程不方便。

如果云端收集箱里面的内容也可以视作一个笔记块，
左边打开云端收集箱，右边打开文档，能直接把信息拖拽到文档里面就方便多了。

**Comment by 88250** [comment]
我觉得是不是可以再进一步，把刚刚说的“复制”按钮改为“一键发送到当前激活的编辑器”。

**Comment by Aiviokoo** [comment]
> 我觉得是不是可以再进一步，把刚刚说的“复制”按钮改为“一键发送到当前激活的编辑器”。

感觉应该很不错

**Comment by DionathanJoestar** [comment]
> 我觉得是不是可以再进一步，把刚刚说的“复制”按钮改为“一键发送到当前激活的编辑器”。

这个选择是优是劣我不好判断。建议问一下大家。
一键发送是个非常好的点子，我能想到它的好多优点。我在这提一下我的顾虑，在我的理解里，一键发送要么发送到文章开头，要么发送到文章末尾。假如说，我知道很多人用收集箱都是记todo清单的，而todo清单大多数人都有自己的模板，不在开头，也不在结尾，很可能在超级块里。

**Comment by DionathanJoestar** [comment]
> 我个人使用收件箱的情况：
> 
> * 公众号文章转发到收集箱，移动，做些编辑。不便之处像上面说的，移动按钮有点深，移动目的地可能要找一会儿，以及移动之后的文档也要找一会儿。
> * 自己写的一些东西发到收集箱，出现在收集箱的同一个时间条目里，但这些东西比较杂乱，需要手动复制不同部分到不同的文档来整理。这里如果能拖拽复制会方便一些。
> 
> 关于移动，感觉可以考虑的地方：（其中前两条对普通文档的移动也适用）
> 
> * 增加一栏移动目的地的历史，可以方便移动到前几次的目的地。
> * 增加一栏常用移动目的地，可以自己手动设置，比如在移动面板的文档前面加星标。
> * 对于条目移动之后需要编辑的情况，可以设为移动之后自动在编辑器打开（在设置里能选择是否自动打开；或者增加一个按钮，不过这样按钮就有些多，不方便把二级菜单释放出来）。
> 
> 关于复制粘贴，如果能拖拽复制就方便许多。之前提过（#8296）把收集箱变成编辑器模式，像反链面板一样，不过D大说设计就是不能编辑的。现在想来可编辑的话会有同步等问题。那是否可以变成只读编辑器的模式，把收集箱里的内容变成一个个块，可能就可以利用现有的块级拖拽了。

@88250 
这个兄弟的想法很有意思，不过拖拽已经确定不能实现。我延伸一下他的想法。
条目外部，添加一个当天整体复制的按钮。
在条目内部，按照发送时间分成若干个独立的块，左键或者右键点击的时候（对，不用通过右键菜单，直接点击复制，类似于一些手机app的功能），块自动复制到剪切板。从而实现多目的地的自由整理。

**Comment by 88250** [comment]
嗯，两位的建议对我们很有启发，但是还需要考虑一段时间，拖拽也不是完全不能实现，对于移动局部内容，暂时还是先选择后复制粘贴顶顶。

**Comment by DionathanJoestar** [comment]
> 嗯，两位的建议对我们很有启发，但是还需要考虑一段时间，拖拽也不是完全不能实现，对于移动局部内容，暂时还是先选择后复制粘贴顶顶。

目前最迫切而且最容易实现的还是整体复制

**Comment by 88250** [comment]
之前几个版本稍微改进过一些，不考虑更多变动了，感谢各位理解。

**Comment by littlecoby** [comment]
> 嗯，两位的建议对我们很有启发，但是还需要考虑一段时间，拖拽也不是完全不能实现，对于移动局部内容，暂时还是先选择后复制粘贴顶顶。

过了大半年回来看看，数据库大头弄好了，能优化一下收集箱嘛？

**Comment by littlecoby** [comment]
> 嗯，两位的建议对我们很有启发，但是还需要考虑一段时间，拖拽也不是完全不能实现，对于移动局部内容，暂时还是先选择后复制粘贴顶顶。

过了大半年回来看看，数据库大头弄好了，能优化一下收集箱嘛？

**Comment by 88250** [comment]
> 之前几个版本稍微改进过一些，不考虑更多变动了，感谢各位理解。
