### ISSUE TITLE
Code block support hlsl shading language highlighting

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8431]
### In what scenarios do you need this feature?

like glsl，hlsl is shading language, which is widely used in game engine (e.g. Unity and Unreal).
![image](https://github.com/siyuan-note/siyuan/assets/5683995/c396677e-1f04-42b7-a115-a70a56776333)

### Describe the optimal solution

expected to support hlsl

**Comment by 88250** [comment]
May be ref to https://github.com/highlightjs/highlightjs-hlsl @Vanessa219

**Comment by zhoutaosheng** [comment]
@Vanessa219 this issue has been opened for a long time, expect to be supported.
Easy things first if it is easy to implement.
