### ISSUE TITLE
希望插件市场能增加memos插件

### ISSUE THREAD

**Issue by gitxxp** [siyuan-note/siyuan#8432]
### In what scenarios do you need this feature?

https://github.com/usememos/memos
用过ob的memos插件，无压记录很好用.

### Describe the optimal solution

![Memos-Desktop](https://github.com/siyuan-note/siyuan/assets/33143774/ec0ce01e-1932-488c-a958-bd02a8dbb100)
https://github.com/Quorafind/Obsidian-Memos

**Comment by 88250** [comment]
已经归入 Idea 中，后续也许会有社区开发者关注，感谢提议。

**Comment by 88250** [comment]
https://github.com/siyuan-community/ideas/issues/1
