### ISSUE TITLE
建议从反链提及中过滤掉父节点为对应引用块的部分

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8433]
### In what scenarios do you need this feature?

在查找提及时发现了很多在父节点本身就是引用的情况。我认为这种提及没有必要在提及面板里出现了，它实际上是对于提及的误判。
目前可用的思路是先查询引用的内容，然后再查询提及，并排除出现再引用中的块。
```sql
SELECT markdown
FROM blocks
WHERE content LIKE '%闪卡插件%'
AND type is 'p'
AND content NOT IN (
    SELECT content
    FROM blocks
    WHERE markdown LIKE '%20230320095659-1ex3pqh%'
)
```
不过这种简单的查询还没有做一炮三响的处理，也只能处理列表，无法处理标题作为父节点的情况。故只作为参考，也不太清楚思源是怎么实现在反链提及中有列表项显示列表项，没有就显示段落的。

### Describe the optimal solution

希望能从反链提及中过滤掉父节点为对应引用块的部分，不需要修改数据库的方法可以先用我上面提及的，但是为了性能考虑建议在数据里多加一个项，也就是父节点列表，从最上面的标题到最下面的直接父节点单独储存起来，然后再进行提及过滤

**Comment by 88250** [comment]
我没太理解，麻烦截图或者录屏展示。

**Comment by zxhd863943427** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/00cbf44e-1d1b-473c-abe4-ae9f758dab77)
比如说这个提及，你可以看到它的父节点其实就是应用，在上方的反链里也能看到这个块，我认为这是无效的、应该被过滤的提及。

**Comment by zxhd863943427** [comment]
另外，我希望是只要它的上级节点、不只是直接的父级节点包含这种传递型引用，就应该要过滤掉。

**Comment by 88250** [comment]
这个暂时不考虑了，我们觉得提及和引用独立较好。如果存在包含关系的话很可能会漏掉提及，特别是你后面提到的这种父节点方向所有层级的情况。

我先关闭了，后面也可以随时讨论，谢谢。
