### ISSUE TITLE
Improve detecting Pad device, treat it as desktop device

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8435]

**Comment by littlecoby** [comment]
v2.9.0 华为平板上打开思源后，变成了手机模式，而之前的版本都是类似电脑端的平板模式。不知道其它平板上是怎么样的，能否改回平板模式？ @88250

**Comment by 88250** [comment]
@littlecoby 估计得帮忙看下 User Agent，可以试下加个代码片段看看。

**Comment by littlecoby** [comment]
> @littlecoby 估计得帮忙看下 User Agent，可以试下加个代码片段看看。

现在平板不在手边，能不能讲讲操作步骤，我晚上试试。

**Comment by 88250** [comment]
1. 手机 APP 上在设置关于中打开网络伺服
2. 电脑端使用浏览器访问手机的伺服地址
3. 电脑端打开设置-外观-代码片段，切换到 JS 页签录入一个代码片段：
   ```javascript
   alert(navigator.userAgent)
   ```
   
   ![image](https://github.com/siyuan-note/siyuan/assets/873584/ceae8b38-6189-4f89-b9eb-9d67e212c790)
4. 确定保存以后电脑这边应该会弹出电脑端的 User Agent，不用管这个。把手机 APP 退出重启，这个时候应该能在手机上看到弹出 User Agent，截个图发一下就行
5. 恢复的话按照上面步骤，在电脑端禁用或者删除那个 JS 代码片段即可

**Comment by littlecoby** [comment]
![matepad](https://github.com/siyuan-note/siyuan/assets/27865589/7013d684-5c7c-45d0-8005-1ab7cb3775ee)

**Comment by 88250** [comment]
@littlecoby 这个 user agent 判断不出来，我们下个版本试试其他方案，感谢反馈。

**Comment by littlecoby** [comment]
> 

嗯嗯好的，下个版本我再看看。

**Comment by littlecoby** [comment]
v2.9.1 华为平板成功显示平板模式了

**Comment by TopProgrammer** [comment]
v2.9.1  华为8.4寸 m6 目前还是手机模式。
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43

**Comment by 88250** [comment]
这有点老火，不按套路出牌 😂 

我们考虑下，后面可能会加个设置项，允许用户自己切换。

**Comment by sunduo0219** [comment]
请问什么时候可以增加用户自己切换平板模式的设置项，有时会想用手机直接在应用内查看pdf

**Comment by 88250** [comment]
@sunduo0219 暂时还没有计划，目前还在解决其他问题，见谅。

**Comment by sunduo0219** [comment]
> @sunduo0219 暂时还没有计划，目前还在解决其他问题，见谅。

好的感谢，辛苦了。
