### ISSUE TITLE
每个文档的最近编辑时间

### ISSUE THREAD

**Issue by YorickGu** [siyuan-note/siyuan#8437]
### In what scenarios do you need this feature?

对于每个文档，是否可以提供一下最近编辑时间呢

### Describe the optimal solution

因为想要查看一下，当时做记录的时候大致是在什么时候做的，这样也可以汇总一下时间和工作量

**Comment by 88250** [comment]
鼠标悬浮文档树上的文档可以看到。

**Comment by 88250** [comment]
或者在编辑器上点文档块的块标菜单：

![image](https://github.com/siyuan-note/siyuan/assets/873584/b4354cb8-d793-4200-8a37-56376f09d857)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
