### ISSUE TITLE
Improve bazaar responsive UI

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/125173405/55452baa-138c-4806-bf99-b67310c2859b

如视频所示，默认主题（以及其他主题）中，商店界面手动拖拽调整大小会正常调整项目尺寸与列数，但缩放后却只能显示为一列，但所占面积却并不需要取消双列。

### Expected result

希望缩放前后的列数能统一。

### Version environment

```markdown
- Version: 2.8.10
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
这个宽度下已经放不下2排了，放得下的话不会掉下去。
