### ISSUE TITLE
标签重命名

### ISSUE THREAD

**Issue by alphaleek** [siyuan-note/siyuan#844]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在一个标签下有大量的块时，我又想统一重命名该标签

### 描述最优的解决方案 Describe the optimal solution
希望在标签页面中，添加右键选中相关标签，进行重命名操作

### 其他信息 Other information

![image](https://user-images.githubusercontent.com/76611744/103148468-d3dddb80-479a-11eb-9518-5e7ec9df5f26.png)

**Comment by 88250** [comment]
收到，后期考虑，类似的还有 #436
