### ISSUE TITLE
自定义属性不支持中文

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#8440]
### In what scenarios do you need this feature?

在对块添加自定义属性的时候不能出现中文，感觉这个挺严重的，群里面说是因为解析器不兼容的问题，请问一下日后能解决这个问题，现在还是主要是国内使用，所以中文应该还是用的最多的。还有一个问题是备注目前不支持换行，这个跟解析器有关吗？如果可以的话还是挺希望能换行显示的

### Describe the optimal solution

自定义属性能够解析中文

**Comment by 88250** [comment]
你好，属性要放在 HTML 标签上，中文可能会有问题。备注不支持换行也是设计如此，感谢反馈。
