### ISSUE TITLE
聚焦后，右下角的字数，词数的统计基于聚焦的块重新统计.

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#8442]
### In what scenarios do you need this feature?

方便知道聚焦的块的情况。方便控制每个聚焦块的字数。

### Describe the optimal solution

字数，词数的统计基于聚焦的块重新统计

### Describe the candidate solution

聚焦的块内人肉全选

**Comment by 88250** [comment]
选择块以后就可以看到统计情况了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/642e7b86-4465-4d6c-a6f2-c2f5c8ec67f6)

PS：按 Esc 可以选中当前块。

**Comment by IAliceBobI** [comment]
> 选择块以后就可以看到统计情况了：
> 
> ![image](https://user-images.githubusercontent.com/873584/243035621-642e7b86-4465-4d6c-a6f2-c2f5c8ec67f6.png)
> 
> PS：按 Esc 可以选中当前块。

和我想要的不太一样，我刚才没说清楚。

主要的想一边打字一边看到变化，不需要选择。
比如我聚焦，进入一个块内打字，可以看到`实时`变化。

**Comment by 88250** [comment]
之前是显示聚焦字数的，后来大部分用户反馈需要全局的，所以才改为现在这个样子。

**Comment by IAliceBobI** [comment]
> 之前是显示聚焦字数的，后来大部分用户反馈需要全局的，所以才改为现在这个样子。

要不再追加加聚焦字数吧。就是想写作的时候，控制每一章节的字数。
