### ISSUE TITLE
创建文件api希望能控制新文档插入方向

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8444]
### In what scenarios do you need this feature?

目前闪卡插件使用了createDocWithMd创建文档，但是文档默认是插入到最上方，这与闪卡插件的目的相背。故希望能多一个传入参数，在默认情况下为插入到最上方，但可以通过传入这个参数改变为插入到最下方。

### Describe the optimal solution

创建文件api增加一个控制插入方向的参数

**Comment by 88250** [comment]
改这个 API 不太妥当，因为排序受排序模式影响，不应该和创建文档 API 耦合。

从实现上来看，目前无法通过 API 将自定义排序模式下的某个文档直接指定到底部，因为修改排序的内部接口 `changeSort` 需要传当前层级的所有文档路径列表，按照这个列表的顺序设置排序值。

如果一定要实现的话可以试下直接修改 笔记本/.siyuan/sort.json，暂时不会直接提供 API，谢谢。
