### ISSUE TITLE
Add plugin API protyle

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8445]
希望能获得protyle的接口

### In what scenarios do you need this feature?

我尝试在自定义的tab中创建类似思源本体的块，但是难以实现，希望官方能给一个创建、操作protyle的接口，方便再自定义的tab、dock、dialog中使用。

### Describe the optimal solution

如题

**Comment by 88250** [comment]
请问创建这种块的目的是，或者说下使用场景？

**Comment by zxhd863943427** [comment]
我在尝试改进思源的标签，通过sql查询获得块id，然后通过api获得块dom，最后放入protyle中。我希望能与思源内部的编辑器一样拥有块菜单、toolbar，同时编辑后能实时保存。

除此之外，获取思源的块，并且在自定义界面中进行编辑应该是之后比较常见的插件。

**Comment by 88250** [comment]
也就是说需要编辑器的功能？

**Comment by zxhd863943427** [comment]
对

**Comment by zxhd863943427** [comment]
目前pdf标注视图已基本实现，原本计划使用protyle实现，改用浮窗实现，性能达到瓶颈，主要开销来自打开浮窗和移动浮窗，只有使用protyle才能提升。

希望能尽早提供这个接口。
