### ISSUE TITLE
用web clipper将图片下载到本地图床的问题

### ISSUE THREAD

**Issue by freezingbz** [siyuan-note/siyuan#8447]
### In what scenarios do you need this feature?

之前用firefox的web clipper扩展剪藏页面时，在提取所需内容后（通常用智能提取），可以通过这个按钮（如下图）将图片直接下载到assets的本地图床。
![图片](https://github.com/siyuan-note/siyuan/assets/6426284/6555a4d3-267e-4c80-8386-5b7661dcd806)

然而最近发现这样操作后图片都不能显示了，点开图片链接看到前面都被加了选中的那部分。当我手动删除该部分后图片能正常显示，但该操作当图片多时比较麻烦。
![图片](https://github.com/siyuan-note/siyuan/assets/6426284/0cc3978c-70d8-41c6-910e-df5a8eb00b0f)

不太确定是思源还是web clipper的原因，麻烦问下能否fix？谢谢~

### Describe the optimal solution

同上

**Comment by 88250** [comment]
这个应该不是思源的问题，请给 web clipper 反馈，谢谢。

**Comment by freezingbz** [comment]
给web clipper反馈了两周没回应。再看了下发现他们这版是去年8月更新的，之后没有更新过，且此前没有出现过所述问题。
所以估计问题也不是web clipper那边。难道是火狐升版本导致的？求救~
