### ISSUE TITLE
文档无法打开

### ISSUE THREAD

**Issue by DreamsCat** [siyuan-note/siyuan#8449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文档无法打开，看截图
![iShot_2023-06-03_20 53 52](https://github.com/siyuan-note/siyuan/assets/52805134/a406e728-7a46-44c4-bb8d-62b2a274536f)
可以点击文档右键打开的，麻烦请看看这问题

### Expected result

麻烦请看看这问题

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
麻烦请看看这问题
```

### Log file

麻烦请看看这问题

**Comment by DreamsCat** [comment]
思源最新版本，macos 最新版

**Comment by 88250** [comment]
请打开开发者工具，然后看下 Console 是否有报错。

**Comment by DreamsCat** [comment]
> 请打开开发者工具，然后看下 Console 是否有报错。

看了，没报错，我点击一下父级，关闭后，打开父级，再点就能打开了

**Comment by 88250** [comment]
那现在已经无法重现问题了吗？

**Comment by DreamsCat** [comment]
> 那现在已经无法重现问题了吗？

我试试能不能复现，现在没这问题了

**Comment by 88250** [comment]
好的，那我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
