### ISSUE TITLE
商店外观改进

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/125173405/6cd0fb92-362d-4fdd-bf7f-9ca336db5335)
2.9.0dev2商店当某一排为单数只显示一列时会填满整行。
默认主题相同：
![image](https://github.com/siyuan-note/siyuan/assets/125173405/214df270-eee0-4650-8ff4-0e2b5b1441ce)

### Expected result

希望能修复。

### Version environment

```markdown
- Version: 2.9.0dev2
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
感谢反馈，继续修复。
