### ISSUE TITLE
一键删除空白页面

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#8451]
### In what scenarios do you need this feature?

添加一键删除空白页面的功能
使用频率不会太多，放在设置里即可

### Describe the optimal solution

添加一键删除空白页面的功能
使用频率不会太多，放在设置里即可

**Comment by UltramarineSky** [comment]
空白页面下的子文档如何处理

**Comment by 88250** [comment]
这个内置就不考虑了，标注为 Idea，等待社区开发者关注，谢谢。
