### ISSUE TITLE
只读模式到编辑模式提高其权限

### ISSUE THREAD

**Issue by lion-of-lei** [siyuan-note/siyuan#8453]
### 功能:
只读模式到编辑模式提高其权限
### 使用场景:
同一个局域网下查看笔记

### Describe the optimal solution

方案:
1. 只读模式到编辑模式续填写密码
2. 增加一个权限按钮,若打开则只读模式不能到编辑模式

**Comment by 88250** [comment]
你好，关于权限，可以考虑：

* 设置 - 关于 - 访问授权码
* 服务器伺服的话可以用内核启动参数 --readonly

暂时不考虑增加更多权限管理功能了，目前 SiYuan 主要定位是个人笔记软件，多人/协同方向暂时不会涉足，感谢反馈。
