### ISSUE TITLE
把插件自定义的 status bar icon 放到内侧而不是外侧

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8455]
### In what scenarios do you need this feature?

我总结觉得目前自定义的 statusbar icon 放置的位置很别扭

![image](https://github.com/siyuan-note/siyuan/assets/27268127/1630b218-895c-4672-8741-bd453c92a260)

自定义的 icon 直接插入了最左侧或者最右侧，对状态栏的布局影响非常大。这意味着**只要加一个插件自带的状态栏，那么状态栏按钮的位置就会和原来的完全不一样**。

### Describe the optimal solution

希望更改一下加入的位置，如果放到左边，就放在  `#status>div.fn__flex-1` 的前面；否则就放在他的后面，这样就算增加新的状态，对原本的状态栏布局也不会有太大的影响。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/e6006412-050a-450e-bda8-6924f6c49fc7)

![image](https://github.com/siyuan-note/siyuan/assets/27268127/7be3d412-8377-40f8-9875-905a72755be1)

**Comment by Vanessa219** [comment]
文本长度会变，放在你说的位置，按钮会随着文本的变化一下前一下后的进行移动。
