### ISSUE TITLE
按 `Alt+M` 后隐藏窗口，再次按 `Alt+M` 显示窗口后会卡住不能编辑

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如标题，如果隐藏后是从底部点击回到思源则不会出现问题。出现问题的情况如标题那样操作。
![image](https://github.com/siyuan-note/siyuan/assets/87182333/76e6dccf-7861-427a-b726-3c37010adc2e)

### Expected result

修复bug

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/87182333/c1484002-a8ee-486b-bebc-7bf8cf2a8d56)

### Version environment

```markdown
- Version: v2.9.10 dev2
- Operating System: win11
- Browser (if used):
```

### Log file

应该不需要，新空间就能复现

**Comment by 88250** [comment]
感谢反馈，稍后排查。
