### ISSUE TITLE
How to create folders in notebooks

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#8457]
### In what scenarios do you need this feature?

How to create folders in notebooks.
I remember that Siyuan could create folders in notebooks a long time ago, but found that the latest version cannot create folders in notebooks. Is there any other way to create folders in the notebook? Thank you for your help!
Version: 2.9.0
System: Windows

### Describe the optimal solution

How to create folders in notebooks.
I remember that Siyuan could create folders in notebooks a long time ago, but found that the latest version cannot create folders in notebooks. Is there any other way to create folders in the notebook? Thank you for your help!
Version: 2.9.0
System: Windows

**Comment by neonalton** [comment]
@zhouxinghong wondering if you ever found a way or if its no longer supported ? It's very hard to explore/browse the nested documents, I have been using the parent document as a "folder" to organize child'ren documents but it gets frustrating browsing the nested/child docs. Clicking on the Parent/"folder" takes you to the usually empty parent doc, and have to go back and browse the specific child doc, it's especially hard on the mobile, and create multiples undesirable tabs.

I see you closed the issue as complete, hoping it is doable.
