### ISSUE TITLE
希望保留twemoji作为外观可选项，或者增加为插件。

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#8459]
### In what scenarios do you need this feature?

win10有部分emoji不兼容会显示为`□`影响观感，希望twemoji能保留下来

### Describe the optimal solution

保留或者改为插件

**Comment by 88250** [comment]
内置不保留了，插件方式的话可能需要社区开发者看下是否能够实现，我们目前没有时间评估，感谢反馈。
