### ISSUE TITLE
在浏览器使用时，siyuan://超链接不能正确跳转

### ISSUE THREAD

**Issue by MusYi** [siyuan-note/siyuan#8465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在浏览器中使用时，打开`siyuan://`格式的超链接，不会在网页版的思源内打开，而是会被当做普通超链接在新标签页打开或者尝试打开本地应用。

### Expected result

`siyuan://`格式的超链接，可以在网页内跳转

### Screenshot or screen recording presentation
![image](https://github.com/siyuan-note/siyuan/assets/47479521/d1a93921-66d0-4e1c-be77-88c2bbceb4cc)
![image](https://github.com/siyuan-note/siyuan/assets/47479521/d8921ad4-3e56-409e-adfa-b90009d425e6)

### Version environment

```markdown
- Version: 思源v2.8.10
- Browser: Microsoft Edge
```

### Log file

None

**Comment by 88250** [comment]
这个好像不行，只能按照浏览器的行为来。

我们关闭这个 issue 了，如果后面有方案会重新打开，感谢反馈。
