### ISSUE TITLE
重建后内容丢失

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

群友最开始是发现`大纲显示貌似有问题`，使用了`优化排版`，导致`大片笔记消失`，后续`重建历史记录索引`，又有`其他打开的文档笔记丢失`，随后回滚最近一次数据，但是数据没有回来，D大帮忙看看，日志有报错群里有消息，三群，群友名`鱼跃光年`

### Expected result

修复

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11664873/siyuan.log)

**Comment by 88250** [comment]
日志中有个建立历史索引的报错，是因为 v2.9.0 我们更改了历史数据库表结构，这个手动重建历史索引后应该就恢复了。

重建索引或者重建历史索引不会导致文档数据丢失的，重建索引索引只是重建数据库，不会更改原始的 .sy 文件。

我在群里问下他吧，这个 issue 先关闭了，谢谢。
