### ISSUE TITLE
API `plugin.addFloatLayer` can be closed by pressing `esc`

### ISSUE THREAD

**Issue by BryceAndJuly** [siyuan-note/siyuan#8470]
### Describe the problem

通过API `plugin.addFloatLayer`打开的悬浮窗获得焦点后，无法通过按<kbd>Esc</kbd>键来关闭悬浮窗。

在文档的引用数或文中的引用块弹出的悬浮弹窗，获得焦点后是可以通过按<kbd>Esc</kbd>键来关闭悬浮窗的。相比于将鼠标移出弹窗来关闭，通过Esc键来关闭弹窗是个很方便用户的操作，希望能在API打开的悬浮窗中保留此逻辑。

备注：演示中顶栏的插件用的是集市官方的插件示例，在挂件中也能复现此问题。

https://github.com/siyuan-note/siyuan/assets/58081876/54176602-97a3-4636-88c8-b0100006119d

### Expected result

相比于将鼠标移出弹窗来关闭，通过Esc键来关闭弹窗是个很方便用户的操作，希望能在API打开的悬浮窗中保留此逻辑。

### Version environment

```markdown
- Version: 2.9.0
- Operating System: windows 10
- Browser (if used):
```

### Log file

none

**Comment by BryceAndJuly** [comment]
我看到main.js的最后那里在window对象上挂载了`window.openFileByURL`方法，能否默认把那个悬浮预览的方法`addFloatLayer`也挂上呢？这样在挂件就能直接用了，而且还没有【悬浮窗获得焦点后无法通过按Esc键关闭窗口】的问题。

不然现在要在挂件里用个方法，还得先去安装插件（还好有用户贡献了这个插件），搞完后弹出的弹窗还有点小问题，感觉没必要搞那么复杂吧，是有其他方面的考虑吗？

```js
const g_ = new p_();

window.openFileByURL = n => {
    if (n && dg(n)) {
        const e = (0, E.on)('focus', n) === '1'
        return (
            he({
                app: g_,
                id: cl(n),
                action: e
                    ? [f.Constants.CB_GET_ALL, f.Constants.CB_GET_FOCUS]
                    : [f.Constants.CB_GET_FOCUS, f.Constants.CB_GET_CONTEXT],
                zoomIn: e
            }),
            !0
        )
    }
    return !1
}

window._addFloatLayer = n => {
    try {
        return (
            window.siyuan.blockPanels.push(
                new _s({
                    app: g_,
                    isBacklink: n.isBacklink,
                    x: n.x,
                    y: n.y,
                    targetElement: n.targetElement,
                    nodeIds: n.nodeIds
                }))
            ,
            !0
        )
    } catch (err) { console.error(err) }

}
```

**Comment by Vanessa219** [comment]
window.openFileByURL 是为了提供移动端和 Pad 使用的，挂载其他方法目前还没有计划。

**Comment by Chenm4** [comment]
有一个问题是这个浮层为什么不可以移动出屏幕，有些时候它挡住了一些内容只能先关闭等看完了被挡内容再打开

**Comment by Vanessa219** [comment]
里面的内容是无法显示在程序以外的，可以使用新窗口功能。
