### ISSUE TITLE
Increase the number of search items displayed per page setting.

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8473]
### In what scenarios do you need this feature?

Currently, the default number of items per search page is 32, which requires frequent flipping through pages when searching for multiple targets. If the items to be compared and viewed in the search are spread across two pages (which is almost certain when searching for a large number of targets), I have to constantly flip forward, wait, view, flip backward, wait, view. This lag greatly affects the smoothness of using SiYuan. I believe that in some special cases, it is necessary to allow users to flip pages as little as possible, and the best way to do this is to add a search page item number setting.

### Describe the optimal solution

Increase the number of search items displayed per page setting.

**Comment by 88250** [comment]
Hello, the page size value is very important. If we allow custom configuration of its value, it will easily cause runtime problems (for example, if the configuration is too large, it may cause hang), so custom configuration of this value will not be allowed, thanks for the feedback.
