### ISSUE TITLE
自动为日记添加额外的元信息

### ISSUE THREAD

**Issue by svchord** [siyuan-note/siyuan#8474]
### In what scenarios do you need this feature?

为日记添加额外的元信息，方便插件查询和判断

### Describe the optimal solution

例如type=dailynote，date = 2006/01/02等

**Comment by 88250** [comment]
日记主要是通过配置的路径判断的，类型不做区分，都是文档块。

**Comment by zxhd863943427** [comment]
可以在类型上不在区分。都是文档块，但是希望能在创建日记时为日记的文档块增加一个自定义属性，比如说custom-type=dailynote，这样能为日记相关的插件开发带来极大的便利。否则使用路径作为区分的话，一则稳定性不够，因为存在用户直接取消了日记的根目录，二则官方的接口只能简单的获取当前的日记，如果要进行日期的跳转那并不容易。

**Comment by 88250** [comment]
加了属性可能不准确的，比如用 Alt+5 创建的日记也可以重命名为其他文档。

**Comment by zxhd863943427** [comment]
那这就是另一个问题了，这种情况，开发者是没有任何办法的。

我的建议是不要考虑这种情况比较好，最多在使用自定义属性获取文档后再进一步用正则进一步筛选，不管怎么说都比现在的模式要好。

另外，思源目前能够获取修改标题的事件，那其实在修改日记标题的时候直接去掉自定义属性也是一条可行的路。

**Comment by Temacc0531** [comment]
强烈不建议把dailynote加入特殊标记信息以此做出区分，我需要所有文档属性地位平等，这对我书写和整理都更方便没有负担

**Comment by zxhd863943427** [comment]
> 强烈不建议把dailynote加入特殊标记信息以此做出区分，我需要所有文档属性地位平等，这对我书写和整理都更方便没有负担

这是方便于开发者使用的属性，对于用户应该是无感的。

否则目前的日历插件、未来的流式日记插件、子弹笔记插件都难以改进和实现，时不时抽风。

**Comment by zxhd863943427** [comment]
> 不用路径判断的话无法稳定维护的，就是是本体也无法做到。

这个是什么原因？

**Comment by 88250** [comment]
上面已经说过了，因为路径会重命名，重命名的情况非常多，还包括修改模板等。

**Comment by svchord** [comment]
> 上面已经说过了，因为路径会重命名，重命名的情况非常多，还包括修改模板等。

但是本体也无法在修改模板后修改过去日记的路径啊，这不也是个问题吗

**Comment by 88250** [comment]
是的，所以不可能再添加新的维护方式了。

**Comment by svchord** [comment]
> 是的，所以不可能再添加新的维护方式了。

不是，如果添加了元信息不就能实现我上面说的那个功能吗，不然修改了模板后不能批量替换过去的日记，对用户来说也是一个问题

**Comment by Chenm4** [comment]
> 强烈不建议把dailynote加入特殊标记信息以此做出区分，我需要所有文档属性地位平等，这对我书写和整理都更方便没有负担

添加属性并不会产生什么地位不平等，因为它俩的地位都是文档块

**Comment by 88250** [comment]
“日记”在思源中不会被特殊对待，否则一些操作就会产生冲突，比如将一个文档移动到日记路径下，是不是这个文档就是日记？

**Comment by Chenm4** [comment]
我感觉有必要添加，或者能否插件实现，让有需求的人用插件添加，因为如果以后要改日记命名模板格式那之前的是否还能识别？

**Comment by Chenm4** [comment]
> “日记”在思源中不会被特殊对待，否则一些操作就会产生冲突，比如将一个文档移动到日记路径下，是不是这个文档就是日记？

添加属性之后不就解决“将一个文档移动到日记路径下，是不是这个文档就是日记”这个问题了吗，因为移动过去的文档没有日记属性所以不是日记，这样好像更双链了，不过我感觉能用插件解决这个问题是最好的

**Comment by svchord** [comment]
> “日记”在思源中不会被特殊对待，否则一些操作就会产生冲突，比如将一个文档移动到日记路径下，是不是这个文档就是日记？

如果路径不匹配，这个文档肯定就不会被识别成日记并添加元信息的，这样不是更方便维护吗

**Comment by 88250** [comment]
路径可以改啊，改了以后怎么维护。

**Comment by svchord** [comment]
> 路径可以改啊，改了以后怎么维护。

我的想法是模板路径改了，也可以根据元信息批量修改日记文档的标题

另外，不修改也可以啊，现在不就是不会修改吗

**Comment by zxhd863943427** [comment]
> 路径可以改啊，改了以后怎么维护。

那就改了呗，思源不需要管。

说到底，这只是对插件有意义，思源从来就没有管过日记的维护。只是每天新建一个文档而已。

**Comment by 88250** [comment]
这是个鸡蛋问题，最底层的依赖到底路径还是啥？

**Comment by 88250** [comment]
> 说到底，这只是对插件有意义，思源从来就没有管过日记的维护。只是每天新建一个文档而已。

对，设计上就是这样的，不可能去单独维护日记的。

**Comment by svchord** [comment]
> 这是个鸡蛋问题，最底层的依赖到底路径还是啥？

我的想法是最底层依赖的是元信息，模板路径改了的话可以做一个按钮批量替换日记路径，也可以不改，让用户决定

**Comment by zxhd863943427** [comment]
> 这是个鸡蛋问题，最底层的依赖到底路径还是啥？

思源可以不做处理，思源自己可以继续用路径，因为思源只是会创建文档。

但对于插件来说不一样，插件更需要依赖路径以外的东西。

**Comment by svchord** [comment]
> 这是个鸡蛋问题，最底层的依赖到底路径还是啥？

现在有依赖问题，主要还是因为目前元信息只能通过路径来判断过去的日记是否添加元信息，以后的日记生成时就添加元信息，就不会有这个矛盾了

**Comment by zxhd863943427** [comment]
思源其实完全不用管维护，因为现在的要求只是在新建文档时加一个元信息，这个信息有什么用思源不需要关心。

因为思源从来没有用到这个东西的地方。思源甚至都不支持打开昨天的日记。

**Comment by 88250** [comment]
那是不是插件自己维护更好一些？

**Comment by svchord** [comment]
> 那是不是插件自己维护更好一些？

插件可以自己维护，就是发送请求数量会比较多，性能上肯定有缺陷

**Comment by zxhd863943427** [comment]
不行，alt+5这个快捷键是打开的每日日记，而不是插件。左上角的按钮打开的也是每日日记，而不是插件。

并且，这个是所有日期相关的插件都会用到的功能，不应该每个插件写一遍。

**Comment by 88250** [comment]
创建文档以后插件应该能够获得通知的吧，获得通知以后判断是不是日记路径，是的话添加属性。

**Comment by svchord** [comment]
> 不行，alt+5这个快捷键是打开的每日日记，而不是插件。左上角的按钮打开的也是每日日记，而不是插件。


这个是有事件的，可以搞，就是比较麻烦。不过这样也会导致多个插件依赖相同的元信息，D大你能接受也行XD

**Comment by 88250** [comment]
这个不是我能不能接受的问题，最主要是看用户的反馈。

**Comment by zxhd863943427** [comment]
关键还是，这个是所有日期相关的插件都会用到的功能，这个其实还是官方把它抽象出来一并处理了比较好……

**Comment by 88250** [comment]
我觉得还是仅支持几种有限的格式即可，这样做即简单又稳妥，太特殊的格式就不要支持了。

**Comment by frostime** [comment]
其实插件开发者要求的东西很好实现，就是在思源的 `createDailyNote()` 函数当中额外增加一两行代码，在创建完日记后，自动给创建的文档添加一个自定义属性，比如 `custom-dailynote=20220602` 之类的。

这样做的目的就在于建立一个**官方认可的统一协议**，以后所有的日记相关插件都遵守这个协议。

这样，实现起来比较简单，对普通用户又无感，可以为后面日记相关插件开发节省不少精力。

------

至于以前的兼容性问题，其实没什么大不了的。因为这里的关键在于：**通过官方正常途径创建日记的时候，也要遵守这个协议**，只有这个问题解决了，后面的其他兼容性问题完全可以靠插件自我规范来解决。
