### ISSUE TITLE
Paste hyperlink parsing exception in text containing bold

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8475]
在包含加粗元素的情况下粘贴超链接解析异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如果文字部分加粗，如

> 你好**啊**

此时向其粘贴链接，就会有如下显示

> 你好啊**你好啊**

其中两个`你好啊`都会被加入链接

### Expected result

改进

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by TinkMingKing** [comment]
如果是给超链加上样式，会分割为两部分

**Comment by TinkMingKing** [comment]
> > 如果是给超链加上样式，会分割为两部分
> 
> 这个没太明白，还麻烦详细说一下。

比如加上加粗样式会这样，斜体下划线之类的也会
添加样式前为一部分
![image](https://github.com/siyuan-note/siyuan/assets/32903588/2a9547b0-7662-45e5-943a-8bddd06ca368)
添加样式后为两部分
![image](https://github.com/siyuan-note/siyuan/assets/32903588/da609a83-48cc-434a-b89c-eae3793c7a82)

**Comment by Vanessa219** [comment]
这个是正常的，由于不支持 a 标签内再嵌套 b 标签，因此拆分为2个标签
