### ISSUE TITLE
删除合并块时为块备注丢失添加提醒

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8476]
### In what scenarios do you need this feature?

当前块存在块备注等信息的情况下，如果用户删除换行将此块与前块合并会导致当前块信息丢失，
![SiYuan_A5aX7rezWZ](https://github.com/siyuan-note/siyuan/assets/125173405/7a2d7d96-9602-4853-8566-c15137122e62)

### Describe the optimal solution

而由于块备注的标识不明显其实用户不太能注意到，可以为这种情况添加提醒吗？

**Comment by Vanessa219** [comment]
这个提醒的话消息会比较多，也容易被用户忽略。除了备注，其他属性也会丢失的。
目前可通过撤销或历史找回丢失的属性。
