### ISSUE TITLE
引入 HTML 标签，导致程序严重异常，无法使用

### ISSUE THREAD

**Issue by DreamsCat** [siyuan-note/siyuan#8477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我引入了了 html 模块，并且在里面自定义了一段代码：
<div>
<a href='https://www.zhihu.com/hot'>知乎</a>
</div>
打开之后，无法关闭，无法使用，只能强制杀死进程，必然复现

### Expected result

正常打开，能正常关闭，不需要强制杀死程序进行退出，不单止 2.9.0版本会，之前的版本都遇到过

### Screenshot or screen recording presentation

![iShot_2023-06-07_11 29 02](https://github.com/siyuan-note/siyuan/assets/52805134/8ba6864c-20f7-4173-9c57-76646c06e1c6)

### Version environment

```markdown
- Version: 2.9.0
- Operating System: macos
- Browser (if used):chrome
```

### Log file

无

**Comment by DreamsCat** [comment]
正常途径无法退出，只能强制杀死进程

**Comment by 88250** [comment]
感谢反馈，已在 https://github.com/siyuan-note/siyuan/commit/b24c06fbce88d9080fb6aa6ef8416101cf577d79 中修复。
