### ISSUE TITLE
Sometimes the memo update dialog cannot be opened

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

2.9.0正式版本似乎无法右键行内备注打开备注修改了。是改变交互了吗？现在则只能先选中文字再修改备注了。

### Expected result

个人还是更喜欢原来的交互。

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
我这里右键和 ”ctrl+/“ 都可以打开的，你看一下是否有报错？

https://github.com/siyuan-note/siyuan/assets/970828/55397622-0679-4922-a6d7-9473be47beaf

**Comment by zxhd863943427** [comment]
测试了一下，确实还可以。

**Comment by chenshinshi** [comment]
测试了下似乎是一部分备注可以打开一部分备注不能，我还在排查问题。

**Comment by chenshinshi** [comment]
我把问题文件导出给你吧。

https://github.com/siyuan-note/siyuan/assets/125173405/df83e233-a76b-4964-b62f-d922270dfcdc
[测试.sy.zip](https://github.com/siyuan-note/siyuan/files/11672402/sy.zip)

**Comment by chenshinshi** [comment]
好像确实有报错但我看不懂
![image](https://github.com/siyuan-note/siyuan/assets/125173405/066542d8-e0dc-47eb-89dd-459dbc0e2204)

**Comment by chenshinshi** [comment]
[ces2.sy.zip](https://github.com/siyuan-note/siyuan/files/11672420/ces2.sy.zip)
这个的government的备注也有相同问题。成分的备注没问题。

**Comment by Vanessa219** [comment]
可以重现了，下个版本修复
