### ISSUE TITLE
ld246.com 500 Internal Server Error

### ISSUE THREAD

**Issue by whuwangyong** [siyuan-note/siyuan#8479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

- ld246.com打不开
- 收集箱无法使用
- 笔记无法同步

![image](https://github.com/siyuan-note/siyuan/assets/5968678/78a83971-929f-4185-9992-654b3d7974a0)

![image](https://github.com/siyuan-note/siyuan/assets/5968678/4027ab79-7003-4fff-8931-7fe13b4f725d)

深圳移动

### Expected result

正常使用

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win 10
- Browser (if used):
```

### Log file

[siyuan - 副本.log](https://github.com/siyuan-note/siyuan/files/11672578/siyuan.-.log)

**Comment by 88250** [comment]
现在应该已经恢复，感谢反馈。

**Comment by whuwangyong** [comment]
好像没有完全恢复。整理收集箱时，将收集箱的内容移到其他目录，会转很久。有时新的目录下已经有了，收集箱下的文件还在，点刷新又是转很久。当然最后还是都移过去了，只是比较卡顿。操作时的日志：

```
I 2023/06/07 13:50:40 repository.go:1170: synced data repo [provider=0, ufc=4, dfc=1, ucc=2, dcc=0, ub=19 kB, db=31 kB] in [3.16s]
E 2023/06/07 13:51:05 queue_history.go:85: queue operation failed: table histories_fts_case_insensitive has no column named id
E 2023/06/07 13:51:05 queue_history.go:85: queue operation failed: table histories_fts_case_insensitive has no column named id
I 2023/06/07 13:52:18 repository.go:1170: synced data repo [provider=0, ufc=4, dfc=1, ucc=2, dcc=0, ub=19 kB, db=31 kB] in [2.97s]
E 2023/06/07 13:52:42 liandi.go:464: get cloud shorthands failed: Post "https://siyuan-sync.b3logfile.com/apis/siyuan/inbox/getCloudShorthands?p=1": context deadline exceeded
I 2023/06/07 13:55:15 repository.go:1170: synced data repo [provider=0, ufc=3, dfc=1, ucc=1, dcc=0, ub=17 kB, db=32 kB] in [1.47s]
E 2023/06/07 13:56:42 queue_history.go:85: queue operation failed: table histories_fts_case_insensitive has no column named id
I 2023/06/07 13:57:17 repository.go:1170: synced data repo [provider=0, ufc=3, dfc=1, ucc=0, dcc=0, ub=17 kB, db=32 kB] in [1.28s]
```
