### ISSUE TITLE
分屏或移动tab时保留tab的内容，而不是重新加载

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

目前移动插件创建的tab，会导致内容重新加载，这对没有保存的内容或者操作进度来说是灾难性的影响。

### Expected result

希望在移动tab的时候，可以保留原有的元素不变。

移动功能应该拿出原有已经渲染的dom元素，移动它的位置，而不是删除原有的建立新的。

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by zuoez02** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
这个使用了 append 调整 dom，调整以后 range 等会出现问题，只能刷新一下。
