### ISSUE TITLE
docker版在MacOS端的浏览器下无法正常打开笔记

### ISSUE THREAD

**Issue by tsaihsiaoyi** [siyuan-note/siyuan#8483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker版在MacOS端的浏览器下无法正常打开笔记

### Expected result

应该能正常展开文档树并打开笔记

### Screenshot or screen recording presentation

<img width="2560" alt="image" src="https://github.com/siyuan-note/siyuan/assets/61139623/c9aeeaa6-8965-4fa4-ab5f-6a30111137bb">

### Version environment

```markdown
- Version: 2.9.0
- Operating System: DSM-docker
- Browser (if used): Arc Browser and Safari
```

### Log file

I 2023/06/07 15:40:30 working.go:117: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/06/07 15:40:30 runtime.go:70: kernel is booting:
    * ver [2.9.0]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/home/siyuan/Documents/SiYuan]
I 2023/06/07 15:40:30 conf.go:354: OpenAI API enabled
    baseURL=https://api.openai.com/v1
    timeout=30s
    proxy=socks://172.17.0.1:7890
    model=gpt-3.5-turbo
    maxTokens=0
I 2023/06/07 15:40:30 runtime.go:122: use network proxy [http://172.17.0.1:7890]
I 2023/06/07 15:40:30 serve.go:113: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2023/06/07 15:40:30 sync.go:151: sync before boot
I 2023/06/07 15:40:31 repository.go:1069: boot get sync cloud files elapsed [0.02s]
I 2023/06/07 15:40:31 blocktree.go:448: read block tree [41 kB] to [/home/siyuan/Documents/SiYuan/temp/blocktree], elapsed [0.01s]
I 2023/06/07 15:40:31 conf.go:690: database size [614 kB], tree/block count [13/158]
I 2023/06/07 15:40:31 working.go:155: kernel booted
I 2023/06/07 15:40:31 box.go:79: auto stat [trees=13, blocks=158, dataSize=2.8 MB, assetsSize=2.5 MB]
E 2023/06/07 15:40:39 plugin.go:91: plugin [Calendar-heatmap] js not found
E 2023/06/07 15:41:55 plugin.go:91: plugin [Calendar-heatmap] js not found
E 2023/06/07 15:43:51 plugin.go:91: plugin [Calendar-heatmap] js not found
E 2023/06/07 15:44:04 plugin.go:91: plugin [Calendar-heatmap] js not found
E 2023/06/07 15:44:21 plugin.go:91: plugin [Calendar-heatmap] js not found
I 2023/06/07 15:45:31 repository.go:1170: synced data repo [provider=3, ufc=3, dfc=1, ucc=0, dcc=0, ub=9.1 kB, db=8.8 kB] in [0.36s]
E 2023/06/07 15:46:05 plugin.go:91: plugin [Calendar-heatmap] js not found
W 2023/06/07 15:46:36 serve.go:423: closed an unauthenticated session [106.39.42.38]
E 2023/06/07 15:46:55 plugin.go:91: plugin [Calendar-heatmap] js not found
I 2023/06/07 15:50:48 repository.go:1170: synced data repo [provider=3, ufc=29, dfc=1, ucc=26, dcc=0, ub=433 kB, db=8.9 kB] in [1.95s]

### More information

由浏览器报错可知这个bug似乎是由`Lute is not defined`引起的，希望对你们有帮助

**Comment by 88250** [comment]
建议使用 Chrome，其他浏览器没有做兼容。
