### ISSUE TITLE
Add plugin with setting to top bar plugin menu

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#8486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/37429029/f867ab5a-21de-46da-a0f0-f984a63ca891)

我下了4款插件，并且都是2.9.0以后重新下载的。
但是我点击插件图标，只能看到2款插件，和集市里面对不上。

![image](https://github.com/siyuan-note/siyuan/assets/37429029/5435f1ff-8b95-4ec5-a1c9-b15d7d4c9d59)

### Expected result

集市里面已经下载的插件都能通过插件图标的下拉框展示

### Version environment

```markdown
- Version: 2.9
- Operating System: win
- Browser (if used):
```

### Log file

none

**Comment by TinkMingKing** [comment]
你问的是为什么有的插件没有顶栏图标，答案是并不是所有插件都会在这里提供一个图标，这是用于实现某些功能，是非必须的， 数学插件要打开公式块才能看到，护眼插件能够在底部状态栏最右边看到一个倒计时

**Comment by AugustTuan** [comment]
> 你问的是为什么有的插件没有顶栏图标，答案是并不是所有插件都会在这里提供一个图标，这是用于实现某些功能，是非必须的， 数学插件要打开公式块才能看到，护眼插件能够在底部状态栏最右边看到一个倒计时

我问的是，为什么点击 主页【插件】按钮，不能把握下载的插件都展示出来（像一般的浏览器插件的逻辑）
![image](https://github.com/siyuan-note/siyuan/assets/37429029/34ddf377-3f1c-48f5-8e15-222869dcbac3)

能不能置顶图标两说，起码下拉框把插件都展示出来，这样我配置插件也方便一点，不用专门进入集市设置
![image](https://github.com/siyuan-note/siyuan/assets/37429029/33faffc1-7878-414a-a655-59507243324c)

**Comment by TinkMingKing** [comment]
确实这样会更好

**Comment by AugustTuan** [comment]
> > > 你问的是为什么有的插件没有顶栏图标，答案是并不是所有插件都会在这里提供一个图标，这是用于实现某些功能，是非必须的， 数学插件要打开公式块才能看到，护眼插件能够在底部状态栏最右边看到一个倒计时
> > 
> > 
> > 我问的是，为什么点击 主页【插件】按钮，不能把握下载的插件都展示出来（像一般的浏览器插件的逻辑） ![image](https://camo.githubusercontent.com/57844700702a47ef7002e8041a395632730fd2cb20961f11a363c81dd463fc36/68747470733a2f2f75736572636f6e74656e742e676974687562666173742e636f6d2f757365722d696d616765732f33373432393032392f3234343037323831322d33346464663337372d336631632d343866352d386531352d3232323836396463626163332e706e67)
> > 能不能置顶图标两说，起码下拉框把下载的插件都展示出来，这样我配置插件也方便一点，不用专门进入集市设置 ![image](https://camo.githubusercontent.com/dc6886b6695da257669272dd8bbe6916911884ae86f686caba427fb57fa07abd/68747470733a2f2f75736572636f6e74656e742e676974687562666173742e636f6d2f757365722d696d616765732f33373432393032392f3234343037333135382d33336661666663312d373837382d343134612d613635352d3539353037323433333234632e706e67)
> 
> 你好，我觉得你应该问下插件作者是否做了适配？而不是在这开issue @AugustTuan

已下载的插件是否能够通过主页插件图标查看到，这个功能的实现是交给插件作者决定的吗？

那如果这个完全取决于插件作者是否主动适配，那后面出来100多个插件，我一个一个去问插件作者？

**Comment by AugustTuan** [comment]
> > 已下载的插件是否能够通过主页插件图标查看到，这个功能的实现是交给插件作者决定的吗？
> > 如果这个完全取决于插件作者是否主动适配，那后面出来100多个插件，我一个一个去问插件作者？
> 
> 你是没看懂我说的还是什么？ 我说你先要去问插件作者是否实现相关接口。懂？不实现接口，怎么给他收进去？不实现接口思源怎么给他显示？ 对，插件作者不适配，思源有天大的本事他也给插件收不进去啊。

原来显示已下载还要主动适配，好吧

**Comment by Vanessa219** [comment]
各位，这个顶栏的插件菜单目前考虑到不是每个插件都有设置、都放在顶栏、都有图标、点击都有回调事件，因此过滤了一些，减少干扰。比如“Web工具集成”是放在 dock 上的，没有设置。这个时候放进去就没有什么意义，还会造成干扰。

**Comment by AugustTuan** [comment]
> 各位，这个顶栏的插件菜单目前考虑到不是每个插件都有设置、都放在顶栏、都有图标、点击都有回调事件，因此过滤了一些，减少干扰。比如“Web工具集成”是放在 dock 上的，没有设置。这个时候放进去就没有什么意义，还会造成干扰。

V姐，比如这个保护眼睛的插件， 它有设置选项，但是下载了也无法通过【插件】图标查看到，只能去集市里面设置
是被过滤掉了吗？ 还是得插件作者自己来适配这个功能？
![image](https://github.com/siyuan-note/siyuan/assets/37429029/094778eb-19c8-47b7-a5c1-5c2650004fce)

**Comment by Vanessa219** [comment]
目前只做了顶栏的，这种情况的插件应该也可以放置进去，只是没有 pin 选项。

**Comment by AugustTuan** [comment]
> 目前只做了顶栏的，这种情况的插件应该也可以放置进去，只是没有 pin 选项。

对的，我的需求就是这个，只要放置进去就好了，不需要pin起来

**Comment by Vanessa219** [comment]
浏览器的插件只要是启用的都会放进去。像“Web工具集成”还是无法放进去，因为放进去没有意义，还会造成干扰。

**Comment by AugustTuan** [comment]
> 浏览器的插件只要是启用的都会放进去。像“Web工具集成”还是无法放进去，因为放进去没有意义，还会造成干扰。

对于·既没有·单独功能和设置的可以过滤掉

**Comment by AugustTuan** [comment]
> 浏览器的插件只要是启用的都会放进去。像“Web工具集成”还是无法放进去，因为放进去没有意义，还会造成干扰。

所以，这些插件是否可以显示出来，是思源决定的，不是插件作者是否适配吧
