### ISSUE TITLE
插件系统提供「更新日志」的接口

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8487]
### In what scenarios do you need this feature?

当插件提交了比较重要的升级的时候，开发者可能希望用户知道插件在这个版本发生的变更。这个时候就有必要弹出一个插件更新日志的窗口——毕竟不是每个人都会常常去看插件的 README 文档的，所以一个简单的更新日志我觉得还是有价值的。

### Describe the optimal solution

插件在提交的时候可以附带一个 `CHANGELOG.en-US.<version>.md` 的文档。

当插件更新之后，插件系统可以自动查看新的插件目录下有没有匹配的 md 文档，如果有的话就读取然后使用 Lute 解析后作为一个 dialog 弹出来。比如以下面这个为例，这是我自己 diy 的一个 changelog 功能。

https://github.com/frostime/siyuan-dailynote-today/blob/main/src/changelog.ts

**Comment by 88250** [comment]
这个暂时不考虑了，如果需要的话插件自己实现吧，感谢提议。
