### ISSUE TITLE
pdf 标注后，不支持云同步吗？

### ISSUE THREAD

**Issue by DreamsCat** [siyuan-note/siyuan#8488]
### In what scenarios do you need this feature?

我在 PDF 上标注后，同步后，到手机发现并没有同步，我使用的是 S3 协议进行同步，同时在手机上复制的标注链接，手机上打开后也无法跳转

### Describe the optimal solution

1

**Comment by 88250** [comment]
同步是支持的，但是不支持手机上打开 PDF，手机上打开 PDF 会跳转浏览器。

**Comment by DreamsCat** [comment]
> 同步是支持的，但是不支持手机上打开 PDF，手机上打开 PDF 会跳转浏览器。

不行吧，我看我在 PDF 上的标记了颜色，手机打开后看不到

**Comment by 88250** [comment]
是不是用了其他扩展把默认的覆盖了。
