### ISSUE TITLE
Android device‘s network hosting support random port

### ISSUE THREAD

**Issue by HildaM** [siyuan-note/siyuan#8490]
### In what scenarios do you need this feature?

While using android network hosting to edit in computer brower, the port is fixed in "6806". This is not secure because network administrators will find your link based on a fixed port number.

The company I work for has monitoring of the local area network, so a fixed port can be more easily to be found.
Random port with random IP can increase the chances of not being detected.

In the desktop app, siyuan supports customizes port. I hope android app can support this feature. But I can't use desktop app on company's computer......

### Describe the optimal solution

In the settings page, add a setting to modify the port. After remaking the port, just rebotting the app to let changes modified.

### Describe the candidate solution

If it is hard to modify port in the app, maybe this can be changed in the app's file

**Comment by 88250** [comment]
Hello, using a fixed port is beneficial to improve stability. In addition, there will be no port conflicts on the mobile-end, so we will not consider making relevant changes for the time being, thank you.
