### ISSUE TITLE
文档树双重滚动条

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/4801955/ff4b3d26-1980-4b39-b9e5-bd9bb3ad4f22)

### Expected result

只有一个滚动条

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by chenshinshi** [comment]
我常常遇到，但我一直以为是我的css修改的太多，因为我状态栏和底栏都调整了位置，导致多出一个滚动条来移动最外面的界面（（（

**Comment by chenshinshi** [comment]
> 我常常遇到，但我一直以为是我的css修改的太多，因为我状态栏和底栏都调整了位置，导致多出一个滚动条来移动最外面的界面（（（

灾难现场
![SiYuan_FnxYmGUwG8](https://github.com/siyuan-note/siyuan/assets/125173405/05325c20-56c2-461c-a352-d241fa81c348)

**Comment by 88250** [comment]
我这里重现不了，默认主题下试试？ @chenshinshi

**Comment by chenshinshi** [comment]
> 我这里重现不了，默认主题下试试？ @chenshinshi

默认主题没事，就是我的主题的问题，但我不清楚提问人zuoez02的原因是什么

**Comment by 88250** [comment]
@zuoez02 楼主，默认主题下如何重现？

**Comment by 88250** [comment]
我这里用足够多的文档（高于上限 512 个）测试未能重现问题，暂时先关闭了，后面如果有稳定重现的步骤麻烦反馈一下，谢谢。
