### ISSUE TITLE
Better Git

### ISSUE THREAD

**Issue by Mellobrainbox** [siyuan-note/siyuan#8493]
https://github.com/android/storage-samples/actions/runs/3383802788/jobs/5620048915

**Comment by 88250** [comment]
Sorry, I didn't understand what you meant, I closed it first.

**Comment by terwer** [comment]
I didn't understand what he means either.

**Comment by frostime** [comment]
It seems that there hasn't been any GIT support in SiYuan yet? So it's wiered to heard so called "better git".
