### ISSUE TITLE
PC端增加不创建桌面快捷方式选项

### ISSUE THREAD

**Issue by guvmao** [siyuan-note/siyuan#8494]
### In what scenarios do you need this feature?

每次更新都会新建桌面图标，但是我不想让其显示在桌面上。

### Describe the optimal solution

安装时增加不创建桌面快捷方式选项

**Comment by 88250** [comment]
这个好像需要自定义 nsis 脚本，目前没有时间研究实现，暂时不考虑了，抱歉抱歉。

如果后续有人看到，可以尝试 PR 贡献代码，谢谢。
