### ISSUE TITLE
可否增加类似 Notion 的多维表格功能

### ISSUE THREAD

**Issue by Valpha** [siyuan-note/siyuan#8503]
### In what scenarios do you need this feature?

Notion 类似的块编辑工具很多都有“多维表格”功能，比如飞书、wolai 等，本地化的工具也有 FocalBoard 这类工具。
![image](https://github.com/siyuan-note/siyuan/assets/35476904/deb83073-df55-4a43-9c65-2ab05545b07a)

这个看板功能用来做一些项目管理会非常有用，请问是否有相关的引入计划嘞？

### Describe the optimal solution

比如集成 FocalBoard 社区版，或者是自己实现

**Comment by 88250** [comment]
已经在实现中，请关注 https://github.com/siyuan-note/siyuan/issues/2829

**Comment by Valpha** [comment]
> 已经在实现中，请关注 #2829

D 大，我滴超人

**Comment by 88250** [comment]
对了，属性视图特性会先实现 Table 视图，其他的视图后续再考虑。
