### ISSUE TITLE
docker 无法正常访问集市

### ISSUE THREAD

**Issue by MasterJobSteam** [siyuan-note/siyuan#8504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker 无法正常访问集市。之前还能访问，最近两天突然就不能访问了。

### Expected result

docker 正常访问集市。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/60995722/7a10a5b4-beb4-4c71-81bf-7c206bccf330)

### Version environment

```markdown
- Version: b3log/siyuan:v2.9.0
- Operating System: docker v20.10.3
- Browser (if used): edge v114.0.1823.41
```

### Log file

E 2023/06/09 11:16:26 rhy.go:43: get version info failed: Get "https://siyuan-sync.b3logfile.com/apis/siyuan/version?ver=2.8.10": dial tcp: lookup siyuan-sync.b3logfile.com on x:53: read udp 172.17.0.4->x:53: i/o timeout

**Comment by 88250** [comment]
请排查一下你服务器的网络。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by MasterJobSteam** [comment]
服务器能正常拉取docker镜像

**Comment by 88250** [comment]
但是日志里面显示无法访问社区服务器哦。

**Comment by MasterJobSteam** [comment]
找到原因了，服务器防火墙设置有问题
