### ISSUE TITLE
文档树显示 Emoji 与文档显示 Emoji 不一致

### ISSUE THREAD

**Issue by choora** [siyuan-note/siyuan#8505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新为 2.9.0 前，原本文档树的 Emoji 是正常显示的，即和文档左上方的 Emoji 相同。更新后文档树 Emoji 显示不统一，表现为某些小黄脸为「黑白线条」风格，部分正常显示为小黄脸。在默认主题下存在这个问题，在安装了 Emoji 插件（目前集市里的两个，Twitter Emoji 和 Google Noto Color Emoji）后，仅仅部分 Emoji 随之改变，非正常显示（或者说显示为我叫不出名字的 Emoji 风格）的 Emoji 没有随着插件的安装而改变。

### Expected result

希望文档树 Emoji 和文档 Emoji 保持一致，并且通过插件可以正确地切换不同的 Emoji 风格。

### Screenshot or screen recording presentation

![2023-06-09 12-02-09 的屏幕截图](https://github.com/siyuan-note/siyuan/assets/8318196/d7dad713-f979-4bb9-bba6-064a3a18436d)

### Version environment

```markdown
- Version: 2.9.0
- Operating System: elementary OS 6.1 Jólnir
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11702183/siyuan.log)

**Comment by 88250** [comment]
这个问题麻烦给插件库反馈一下，目前主程序只会使用系统自带的 Emoji 字体，可能会有缺失。
