### ISSUE TITLE
openSUSE TumbleWeed 无法显示启动画面和主窗口

### ISSUE THREAD

**Issue by jDsszzrDev** [siyuan-note/siyuan#8508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

- 起因(才测可能的原因)：下载2.9.0启动后，由于插件系统内置的缘故，直接从挂件面板删除插件系统，此时已打开的思源(2.9.0)正常，第二天重启之后，无法从2.9.0启动思源启动画面如下

![image](https://github.com/siyuan-note/siyuan/assets/109229333/9b769e95-a136-4d2d-a1a7-ef030d63039a)

- 此时仍可以启动2.8.10并正常使用，于2.8.10切换主题对此没有帮助。

问题发生于两天之前，最初以为是主题的问题，今日更新主题、切换默认主题仍有问题，于是上报

### Expected result

希望能修复这个问题或者提供解决方法

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/109229333/41ed7d76-2ffc-49f2-922b-65db83afdbfb)

### Version environment

```markdown
- Version: 2.9.0
- Operating System: Linux(openSUSE TumbleWeed)
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11703012/siyuan.log)

**Comment by 88250** [comment]
把 ~/.config/siyuan/workspace.json 文件重命名为 workspace.json1，然后再启动看看能不能进入初始化界面。

**Comment by jDsszzrDev** [comment]
> 把 ~/.config/siyuan/workspace.json 文件重命名为 workspace.json1，然后再启动看看能不能进入初始化界面。

![image](https://github.com/siyuan-note/siyuan/assets/109229333/2a8f0986-d360-4d9e-8815-9d12c5f16c46)

**Comment by 88250** [comment]
看内核应该是正常启动了，可能是 Electron 兼容的问题。

**Comment by 88250** [comment]
对了，麻烦测试一下 Electron 本体 https://github.com/electron/electron/releases/tag/v25.1.0 是否能正常启动。

**Comment by jDsszzrDev** [comment]
> 对了，麻烦测试一下 Electron 本体 https://github.com/electron/electron/releases/tag/v25.1.0 是否能正常启动。

如何测试

**Comment by 88250** [comment]
下载你的系统对应的包，解压以后运行里面的 electron 可执行文件。

**Comment by 88250** [comment]
比如这个 https://github.com/electron/electron/releases/download/v25.1.0/electron-v25.1.0-linux-x64.zip

**Comment by jDsszzrDev** [comment]
> 

![image](https://github.com/siyuan-note/siyuan/assets/109229333/ba2d7286-3a4d-4c58-97d8-92b61a3adccc)
这个吗

**Comment by 88250** [comment]
看来是可以执行的，再试试这个版本 https://github.com/electron/electron/releases/download/v25.0.1/electron-v25.0.1-linux-x64.zip

**Comment by jDsszzrDev** [comment]
> 

![image](https://github.com/siyuan-note/siyuan/assets/109229333/9c6238a4-0770-4fed-bc1a-7756b45d1337)
依然可以

**Comment by 88250** [comment]
好的，再试下 siyuan 的 [tar.gz 包](https://github.com/siyuan-note/siyuan/releases/download/v2.9.0/siyuan-2.9.0-linux.tar.gz)

**Comment by jDsszzrDev** [comment]
> 好的，再试下 siyuan 的 [tar.gz 包](https://github.com/siyuan-note/siyuan/releases/download/v2.9.0/siyuan-2.9.0-linux.tar.gz)
![image](https://github.com/siyuan-note/siyuan/assets/109229333/c52ecf3e-dfba-40e6-affc-0bd19f329592)

```log
I 2023/06/09 16:07:43 runtime.go:70: kernel is booting:
    * ver [2.9.0]
    * arch [amd64]
    * os [opensuse-tumbleweed]
    * pid [19994]
    * runtime mode [prod]
    * working directory [/home/long/L-09/03/Notes/Siyuan/siyuan-2.9.0-linux/resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/mnt/veracrypt1/Siyuan]
I 2023/06/09 16:07:43 conf.go:227: upgraded from version [2.8.10] to [2.9.0]
I 2023/06/09 16:07:43 conf.go:384: user has disabled [Google Analytics]
I 2023/06/09 16:07:43 runtime.go:124: use network proxy [system]
I 2023/06/09 16:07:43 serve.go:113: kernel [pid=19994] http server [127.0.0.1:35623] is booting
I 2023/06/09 16:07:44 pandoc.go:115: built-in pandoc [ver=2.19.2, bin=/mnt/veracrypt1/Siyuan/temp/pandoc/bin/pandoc]
I 2023/06/09 16:07:44 blocktree.go:448: read block tree [2.0 MB] to [/mnt/veracrypt1/Siyuan/temp/blocktree], elapsed [0.68s]
I 2023/06/09 16:07:44 conf.go:690: database size [15 MB], tree/block count [135/6028]
I 2023/06/09 16:07:44 working.go:155: kernel booted
I 2023/06/09 16:07:44 box.go:79: auto stat [trees=135, blocks=6028, dataSize=11 MB, assetsSize=2.0 MB]
I 2023/06/09 16:07:44 disk.go:33: disk usage [total=3.2 GB, used=198 MB, free=2.5 GB]
I 2023/06/09 16:07:44 serve.go:126: reverse proxy server [127.0.0.1:6806] is booting
I 2023/06/09 16:08:15 conf.go:465: exiting kernel [force=false, execInstallPkg=0]
I 2023/06/09 16:08:15 database.go:1134: closed database
I 2023/06/09 16:08:15 conf.go:837: cleared workspace temp
I 2023/06/09 16:08:16 conf.go:512: exited kernel
```

**Comment by 88250** [comment]
焦点切换到窗口，按 Ctrl Shift I 组合键看看能否打开开发者工具，能的话看下报错。



---原始邮件---
发件人: "Roger ***@***.***&gt;
发送时间: 2023年6月9日(周五) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] openSUSE TumbleWeed 无法显示启动画面和主窗口 (Issue #8508)




  
好的，再试下 siyuan 的 tar.gz 包
 
  I 2023/06/09 16:07:43 runtime.go:70: kernel is booting:     * ver [2.9.0]     * arch [amd64]     * os [opensuse-tumbleweed]     * pid [19994]     * runtime mode [prod]     * working directory [/home/long/L-09/03/Notes/Siyuan/siyuan-2.9.0-linux/resources]     * read only [false]     * container [std]     * database [ver=20220501]     * workspace directory [/mnt/veracrypt1/Siyuan] I 2023/06/09 16:07:43 conf.go:227: upgraded from version [2.8.10] to [2.9.0] I 2023/06/09 16:07:43 conf.go:384: user has disabled [Google Analytics] I 2023/06/09 16:07:43 runtime.go:124: use network proxy [system] I 2023/06/09 16:07:43 serve.go:113: kernel [pid=19994] http server [127.0.0.1:35623] is booting I 2023/06/09 16:07:44 pandoc.go:115: built-in pandoc [ver=2.19.2, bin=/mnt/veracrypt1/Siyuan/temp/pandoc/bin/pandoc] I 2023/06/09 16:07:44 blocktree.go:448: read block tree [2.0 MB] to [/mnt/veracrypt1/Siyuan/temp/blocktree], elapsed [0.68s] I 2023/06/09 16:07:44 conf.go:690: database size [15 MB], tree/block count [135/6028] I 2023/06/09 16:07:44 working.go:155: kernel booted I 2023/06/09 16:07:44 box.go:79: auto stat [trees=135, blocks=6028, dataSize=11 MB, assetsSize=2.0 MB] I 2023/06/09 16:07:44 disk.go:33: disk usage [total=3.2 GB, used=198 MB, free=2.5 GB] I 2023/06/09 16:07:44 serve.go:126: reverse proxy server [127.0.0.1:6806] is booting I 2023/06/09 16:08:15 conf.go:465: exiting kernel [force=false, execInstallPkg=0] I 2023/06/09 16:08:15 database.go:1134: closed database I 2023/06/09 16:08:15 conf.go:837: cleared workspace temp I 2023/06/09 16:08:16 conf.go:512: exited kernel

**Comment by jDsszzrDev** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/109229333/a4f1e60b-30fb-42dd-a388-ce859065a5c3)

**Comment by 88250** [comment]
Ctrl R 刷新看看



---原始邮件---
发件人: "Roger ***@***.***&gt;
发送时间: 2023年6月9日(周五) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] openSUSE TumbleWeed 无法显示启动画面和主窗口 (Issue #8508)

**Comment by jDsszzrDev** [comment]
闪了一下 无变化

**Comment by 88250** [comment]
看看 Console 和 network 里面是不是有报错



---原始邮件---
发件人: "Roger ***@***.***&gt;
发送时间: 2023年6月9日(周五) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] openSUSE TumbleWeed 无法显示启动画面和主窗口 (Issue #8508)




 
闪了一下 无变化

**Comment by jDsszzrDev** [comment]
我说的闪了一下，是指刷新了，无变化是跟上面那张图比较，还是全黑，别说报错了，连字都没😂

**Comment by 88250** [comment]
开发者工具里面没有任何报错和网络请求吗？



---原始邮件---
发件人: "Roger ***@***.***&gt;
发送时间: 2023年6月9日(周五) 下午4:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] openSUSE TumbleWeed 无法显示启动画面和主窗口 (Issue #8508)




 
我说的闪了一下，是指刷新了，无变化是跟上面那张图比较，还是全黑，别说报错了，连字都没😂

**Comment by jDsszzrDev** [comment]
这个开发者工具只有黑色背景和部分颜色块，以及滚动条

**Comment by 88250** [comment]
这就有点奇怪了，你再试下前面的 electron 能否打开开发者工具，应该是一样的快捷键



---原始邮件---
发件人: "Roger ***@***.***&gt;
发送时间: 2023年6月9日(周五) 下午4:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] openSUSE TumbleWeed 无法显示启动画面和主窗口 (Issue #8508)




 
这个开发者工具只有黑色背景和部分颜色块，以及滚动条

**Comment by jDsszzrDev** [comment]
前面两个electron版本的开发者工具均可打开，2.8.10的亦可打开

**Comment by 88250** [comment]
好的，等下个版本再试试吧，暂时定位不到问题。



---原始邮件---
发件人: "Roger ***@***.***&gt;
发送时间: 2023年6月9日(周五) 下午4:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] openSUSE TumbleWeed 无法显示启动画面和主窗口 (Issue #8508)




 
前面两个electron版本的开发者工具均可打开，2.8.10的亦可打开

**Comment by jDsszzrDev** [comment]
行

**Comment by 88250** [comment]
dev 版已经发布，有空的话帮忙测试看看。

**Comment by 88250** [comment]
感谢帮忙测试。



---原始邮件---
发件人: "Roger ***@***.***&gt;
发送时间: 2023年6月9日(周五) 晚上11:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] openSUSE TumbleWeed 无法显示启动画面和主窗口 (Issue #8508)




  
dev 版已经发布，有空的话帮忙测试看看。
  
能够正常打开使用，暂无发现其他问题

**Comment by jDsszzrDev** [comment]
2.9.2版本再次出现问题，同样是使用一段时间后出现，但是这次可以看见部分文字，布局仍然无法看见

**Comment by jDsszzrDev** [comment]
开发者工具如图
![image](https://github.com/siyuan-note/siyuan/assets/109229333/3f84dd18-17c8-4008-915f-7284f57ee00e)

```log
I 2023/06/25 13:53:18 runtime.go:71: kernel is booting:
    * ver [2.9.2]
    * arch [amd64]
    * os [opensuse-tumbleweed]
    * pid [8094]
    * runtime mode [prod]
    * working directory [/tmp/.mount_siyuan4ABKbj/resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/mnt/veracrypt1/Siyuan]
I 2023/06/25 13:53:18 conf.go:388: user has disabled [Google Analytics]
I 2023/06/25 13:53:18 runtime.go:125: use network proxy [system]
I 2023/06/25 13:53:18 serve.go:113: kernel [pid=8094] http server [127.0.0.1:44449] is booting
I 2023/06/25 13:53:18 pandoc.go:125: built-in pandoc [ver=2.19.2, bin=/mnt/veracrypt1/Siyuan/temp/pandoc/bin/pandoc]
I 2023/06/25 13:53:18 conf.go:907: pandoc initialized, set pandoc bin to [/mnt/veracrypt1/Siyuan/temp/pandoc/bin/pandoc]
I 2023/06/25 13:53:18 blocktree.go:446: read block tree [2.3 MB] to [/mnt/veracrypt1/Siyuan/temp/blocktree], elapsed [0.01s]
I 2023/06/25 13:53:18 conf.go:699: database size [18 MB], tree/block count [142/7194]
I 2023/06/25 13:53:18 working.go:153: kernel booted
I 2023/06/25 13:53:18 box.go:79: auto stat [trees=142, blocks=7194, dataSize=7.0 MB, assetsSize=2.0 MB]
I 2023/06/25 13:53:18 disk.go:33: disk usage [total=3.2 GB, used=195 MB, free=2.5 GB]
I 2023/06/25 13:53:19 serve.go:126: reverse proxy server [127.0.0.1:6806] is booting
```

**Comment by 88250** [comment]
感觉是网络的问题，建议检查一下本地网络配置，试试最新的 dev 版本。

**Comment by jDsszzrDev** [comment]
自上次对ISSUSE之后，Siyuan正常使用了很长时间。
但是，在更新思源至2.10.0版本之后，2.9.x全版本和2.10.0(包括2.10.1)均出现主界面无法加载的问题。
今天，我对电脑无任何操作，包括系统升级(zypper ref&&dup)，我进行删除`~/.config/siyuan`和`~/.config/SiYuan`和`.config/SiYuan-Electron`三个文件夹操作，随后思源初始化，并可正常使用。

希望能帮助作者定位问题所在。
