### ISSUE TITLE
有序列表，加粗后，换行展示有问题

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#851]
### 描述问题 Describe the problem

有序列表，加粗后，换行展示有问题，详情见录屏
### 期待的结果 Expected result

正常展示换行格式。
### 截屏或录屏演示 Screenshot or screen recording presentation

https://user-images.githubusercontent.com/16383685/103166945-f2f37080-4861-11eb-9209-f17a89a998da.mov

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，你用的版本是最新版吗？如果不是的话麻烦用最新版试下。我这里在最新版上重现不了：

![issue](https://user-images.githubusercontent.com/873584/103167565-0e14af00-4867-11eb-9edb-5e3a44d70c1b.gif)

**Comment by 88250** [comment]
我先关闭了，如果还有反馈请继续跟帖，谢谢。
