### ISSUE TITLE
关于拖动块操作的时候很难触发

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#8515]
### In what scenarios do you need this feature?

感觉目前定义的拖动一个块与另一个块并列的操作的有效区间太窄了，不太容易实现出现。普通的两个块拖动效果还好一点，我刚才有一个引述块里面有一个超级块，我想在别的地方拖动一个超级块和这个超级块并列很难实现，经常是实现和引述块并列了。还有就是新建表格能不能学习一下typora的方式，它的表格是完全撑满整个界面的，在美观度会好很多，希望思源也能提供一个这个选项。下图是两个的比较，个人认为撑满会好看一点。
![image](https://github.com/siyuan-note/siyuan/assets/98648589/ff7a5d72-d91b-446f-82fd-c4342f08b323)
![image](https://github.com/siyuan-note/siyuan/assets/98648589/28d44313-8e7d-49dd-9cf6-790c47044d18)

### Describe the optimal solution

希望能有更好的鼠标拖动交互逻辑，让它更加方便。

**Comment by 88250** [comment]
* 之前考虑过 https://github.com/siyuan-note/siyuan/issues/4394
* 表格样式建议通过自定义 CSS 覆盖

感谢反馈。
