### ISSUE TITLE
插件系统请求提供echarts的依赖

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8516]
### In what scenarios do you need this feature?

自己引入echarts，在客户端正常工作但是在网页报错
![image](https://github.com/siyuan-note/siyuan/assets/32903588/a378cd22-8e17-4a6f-ba66-d87a71984b8d)
一时半会解决不了问题，反正siyuan内置了echarts，所以请求提供一下，避免引入出错，也减少插件依赖，减小插件体积，避免重复引入

### Describe the optimal solution

提供echarts的依赖

**Comment by Vanessa219** [comment]
echarts 是全局的，你参照 https://github.com/siyuan-note/siyuan/blob/ccd48618e523201906eeb2ba3566ab3617710819/app/src/protyle/render/chartRender.ts 进行引用应该就可以了
