### ISSUE TITLE
插件系统的 menu icon 恢复对 unicode 的支持

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8517]
### In what scenarios do you need this feature?

通过 getNotebookConf 获取到的 icon 是 unicode 字符类型。在此前的插件系统当中，通过给 menu item option 传入  `icon-{code}` 可以正常解析图标。但是在 2.9.0 版本更新后原来的方案就无法使用了。

我也是在翻阅了源代码后才发现需要自己解析；

```ts
let emoji = String.fromCodePoint(parseInt(code, 16));
return `<span class="b3-menu__icon">${emoji}</span>`;
```

### Describe the optimal solution

希望插件系统的 menu item option 重新恢复 unicode emoji 的解析。

@Vanessa219

**Comment by Vanessa219** [comment]
麻烦发一下 icon 值转入的是什么？我匹配一下。

**Comment by frostime** [comment]
> 麻烦发一下 icon 值传入的是什么？我匹配一下。

例如：1f605, 1f5c3，1f9fe

---

这些值都是直接通过 `lsNotebooks` API 获取到的 Notebook 的 Icon。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/7b0e6991-c13f-423e-a909-993a65135b2f)

**Comment by frostime** [comment]
如果不方便直接和 `icon` 参数混在处理，额外加一个 `iconUnicode` 参数也可以。

**Comment by Vanessa219** [comment]
可以使用 `iconHTML:'<img src="/emojis/b3log.png" class="b3-menu__icon">'` 或者
 `iconHTML:'<span class="b3-menu__icon">👨</span>'`
