### ISSUE TITLE
嵌入块浮窗出现异常抖动

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这是一个非常难复发的bug，使用示例文件需要在字体调整为17的情况下才能复现，可能还需要限定屏幕为1080p。

具体操作如下
![浮窗抖动](https://github.com/siyuan-note/siyuan/assets/74853597/995c5753-0b62-4ce5-9cbb-6783a92df64c)

这个问题的优先级并不高，因为只需要打一个空格都足以解决。

[bug.sy.zip](https://github.com/siyuan-note/siyuan/files/11714273/bug.sy.zip)

### Expected result

修复浮窗抖动现象

### Version environment

```markdown
- Version: 2.9.0
- Operating System: win10 
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
我这里在 291-dev2 上测试无法重现问题，有空的话麻烦帮忙试下。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by zxhd863943427** [comment]
2.9.1仍可以复现，要点是必须把字体调大至下方不换行而上方换行了。

![浮窗跳动](https://github.com/siyuan-note/siyuan/assets/74853597/501a5c6f-2727-437a-87df-2d1f22449f15)

**Comment by 88250** [comment]
@Vanessa219 我这里可以重现了，你看下能不能改进。
