### ISSUE TITLE
Custom menu

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8524]
增加文档右上角更多功能里功能的选择（用上类似插件系统pin的更为nice）

### In what scenarios do you need this feature?

有时候需要用到一些功能，比如说移动，或想看文件历史，等等，要打开文档树，再去点击更多很不方便。
直接右上角更多就有会少一步，方便很多。

### Describe the optimal solution

<img width="1080" alt="右上角菜单" src="https://github.com/siyuan-note/siyuan/assets/87182333/41f1cf2e-1fd8-4019-9632-bed6da8fb2d3">
<img width="880" alt="Snipaste_2023-06-13_07-25-40" src="https://github.com/siyuan-note/siyuan/assets/87182333/67956698-f484-4563-8aa4-2695f5147f9b">

如上图所示，参考的是 https://github.com/siyuan-note/siyuan/issues/8345 和 https://github.com/siyuan-note/siyuan/issues/8411 实际效果类似导出菜单那样有2级菜单（2级菜单里的功能也可以移到一级），就很不错了

**Comment by Temacc0531** [comment]
我也觉得有些功能入口可以移动文档内的菜单里面，和大多数共享文档保持相同逻辑。文档树的选项可以适当精简，不用多个地方提供相同入口😂

**Comment by Vanessa219** [comment]
目前入口有标题左侧块标，文档树，编辑器右上角。这个初期已经修改过一版本了，目前还需要调整的话需要重新设计，不是单纯的添加这么简单。

**Comment by Aiviokoo** [comment]
> 目前入口有标题左侧块标，文档树，编辑器右上角。这个初期已经修改过一版本了，目前还需要调整的话需要重新设计，不是单纯的添加这么简单。

好呢，谢谢V姐，看来确实很不容易呢😭，是我想简单了，以为能很轻松的加一个 类似插件系统的 可控的二级菜单

**Comment by Aiviokoo** [comment]
> 我也觉得有些功能入口可以移动文档内的菜单里面，和大多数共享文档保持相同逻辑。文档树的选项可以适当精简，不用多个地方提供相同入口😂

赞同，但是精简到什么程度，一千个人可能有1000种想法，目前的方案也是V姐精心设计的。
确实有精简或添加其他功能的需求，毕竟每个人常用的功能可能不同，所以我提出了将不那么必要的东西放到 其他 菜单的2级菜单下，如果其优先级提高了又可以再移出来的想法。(默认还是V姐设计的这个方案，定制化就是自己微微调整了）

**Comment by Aiviokoo** [comment]
> 标题左侧块标点击估计很多人不知道，目前也不知道要怎么弄了。全部放在右上角菜单中，会比较多，要找自己需要的也比较麻烦。目前稳定的方法就是没有更好方案之前先不动 😂

嗯嗯，应该是的。
我之前也没怎么使用左侧这个，前两天在群里问到移动的时候，D大突然想起左侧的文档块标可以。(左侧这个和右侧的相比，需要在文档顶部的时候才会显示，右侧那个是文档页面内任意位置时都有显示)
目前我能想到的想法就是有一个
一级菜单叫其他(类比顶部插件管理)
二级菜单放很多文档可操作的功能(如果觉得乱，二级是分类，三级放具体的也行)
(这个类比插件管理点击后，可以控制是否在一级菜单处显示)相对而言更符合不同人需求一些。
目前文档树，左侧，右侧，部分功能有重叠，又有不同。用户如果使用的时间不长，就会有些混乱(比如想移动或点闪卡点到右边发现没有，需要左边或文档树才有)
如果全加在一级菜单下又是很不合理的，就太长了，这应该是V姐之前精选了一些的缘故。(所以可将功能隐藏到2级菜单的功能还是有一定的优势)
不过昨天听V姐说这样好像需要重新设计，比较麻烦。(设想就是原来的布局不动，3个地方都有一个更多的菜单，里面放着不常用的功能，当这个功能常用时又可以在1级显示，不常用时就一直隐藏在更多里)
实在难以实现就先这样吧，感谢V姐的回复。

**Comment by littlecoby** [comment]
入口除了文档树、标题、右上角之外，页签里面还有个“复制” hh

我倒是更习惯用标题左侧的，不需滚动页面时很容易点到，但向下滚动之后就挺麻烦。

带有个人偏好的设想是，滚动页面时钉住标题，把操作文档的功能集中到标题左侧，其它入口精简。

![image](https://github.com/siyuan-note/siyuan/assets/27865589/990a5e81-1de3-46da-b210-bc083e17b755)

文档树：不用打开文档就能操作，打开文档后需要定位才能操作。可以放针对整个文档，不涉及文档内容的功能，这里的属性、搜索、替换、文件历史可以移除。

页签：主要放和操作页签相关的功能，这里的复制可以移除。

页面右上角：可以专注于页面排版和资源相关的功能，这里的删除和导出可以移除（虽然删除是近期一个issue里加上的）。

**Comment by Vanessa219** [comment]
你这都是移除，移除了以后会不会被打 😄

**Comment by Aiviokoo** [comment]
> 你这都是移除，移除了以后会不会被打 😄

移除大概率会被反馈的。有些功能有些用户都用习惯了，突然没了或不容易找到了是很恼火的事情。
现在就是要么暂时不动：
如果动的时候，暂时可以考虑一下我提的那个放2级菜单的方案（然后不同的人可以把不需要的都放这里，也可以还原成1级菜单，就很简洁了，也能满足不同人的个性化需求）就是不知道实现起来的困难程度如何。

**Comment by littlecoby** [comment]
> 你这都是移除，移除了以后会不会被打 smile

会吧 hhh，所以只是个人的偏好。

能不能在设置里加个滚动文档时是否钉住标题的选项，这样就可以开心的使用标题左侧入口了，而且对现在的使用不影响。

**Comment by Aiviokoo** [comment]
> 入口除了文档树、标题、右上角之外，页签里面还有个“复制” hh
> 页签：主要放和操作页签相关的功能，这里的复制可以移除。

页签我也是想用起来的，因为它就和右边的更多一样，一直固定在这个位置，甚至还有多页签时可以更方便操作没聚焦的页签（比之文档树，他可以很快速的操作不同笔记本下打开的文档）
但是好像有技术难点![Screenshot_2023-06-15-13-07-49-024_com.tencent.mobileqq-edit.jpg](https://github.com/siyuan-note/siyuan/assets/87182333/a0a64bd1-f64b-40ac-be05-366444aabb69)

**Comment by littlecoby** [comment]
使用不同入口时，优先使用的功能是不同的。我上面就是在猜想用每个入口时主要想干啥。(https://github.com/siyuan-note/siyuan/issues/8524#issuecomment-1592250139)

比如页签，现在有的这些应该都是优先级高的功能。关闭页签已经占了好多行，如果把其他功能（比如移动、删除）也加上来，就得排在下面，点起来也不方便。

感觉有三个入口就够了，文档树一个，用来做不打开文档的操作；页签一个，用来操作页签；文档页面左上角放一个固定的，用来执行针对文档的大部分功能。其中文档树和页签入口的功能可以精简，文档左上角的功能多些，做做分组和二级菜单。

现在右上角按钮虽然是固定的，但如果使用大屏，点起来需要移动很远的距离，不大方便。标题左侧的如果能钉住，移动距离短一些，但也有问题，一个是标题钉住会占用页面空间，一个是长得有点像块标，但又和块标功能差别很大。

**Comment by littlecoby** [comment]
可用户自己定制的话，之前还讨论过顶栏定制来着（比如把日记按钮放上去），看来是优先级不高 hhh

**Comment by Vanessa219** [comment]
看来只有自定义是最终解决方案

**Comment by Aiviokoo** [comment]
设想补充，详细见链接：https://ld246.com/article/1701669406727/comment/1703140120112#comments 
![image](https://github.com/siyuan-note/siyuan/assets/87182333/940624d1-ea40-46e4-95f8-6d36e7354015)

**Comment by TCOTC** [comment]
希望能自定义块标菜单，大部分人都只用其中一部分：

![image](https://github.com/user-attachments/assets/0e990a40-d5bb-4a1a-b86d-e2e89396ab9f)

**Comment by 88250** [comment]
考虑通过插件实现自定义吧。
