### ISSUE TITLE
Command Palette for plugins

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8526]
### In what scenarios do you need this feature?

目前插件增多，系统自带功能也越来越复杂，需要一个便于使用的入口了。希望能够提供内置的命令面板，用于调用系统自带功能和插件注册的命令。

### Describe the optimal solution

类似前任插件系统的命令版本。

**Comment by mozhux** [comment]
附议，对于一些插件，完全没有必要占据一个按钮位置。

**Comment by zxhd863943427** [comment]
复议，有些功能在命令面版中切换开关就好。

**Comment by zuoez02** [comment]
Hope this feature implemented in 2.9.2 :)

**Comment by Vanessa219** [comment]
系统内部的命令还没有规划好哪些命令放到命令面板中。感觉大部分命令用户都已经习惯了现在的操作，如果再放入命令面板中会不会显得多次一举反而会产生干扰。未整理出来之前就先放插件的吧。

**Comment by zuoez02** [comment]
但是需要给插件提供操作入口呀，才能方便插件接入更多

**Comment by zuoez02** [comment]
但是需要给插件提供操作入口呀，才能方便插件接入更多****
