### ISSUE TITLE
There are ZERO WIDTH SPACE in the exported markdown file

### ISSUE THREAD

**Issue by NeverKnowsTomorrow** [siyuan-note/siyuan#8527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

There are ZERO WIDTH SPACE in the exported markdown file. You can see the `ZWSP` character when you open the exported markdown file with IntelliJ IDEA 2023.1.2.
<img width="1353" alt="image" src="https://github.com/siyuan-note/siyuan/assets/36879844/e66eddaa-0420-4e78-9108-ff82d17a567a">

### Expected result

There are no ZERO WIDTH SPACE in the exported markdown file.

### Version environment

```markdown
- Version: 2.9.1
- Operating System: MacOS 13.1
- Browser (if used): Microsoft Edge 114.0.1823.43
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11732298/system-log.zip)

**Comment by 88250** [comment]
这些零宽空格的添加是为了解决导出行级标记符时被标点符号打断的情况，应该没有副作用，如果不需要的话请自行批量替换，感谢反馈。

**Comment by 88250** [comment]
另外，现在为了稳定性，暂时不调整已有实现了，等后面接收跟多反馈后再看看，谢谢。

**Comment by Zuoqiu-Yingyi** [comment]
> 等后面接收更多反馈后再看看

希望在导出时可以批量移除, 毕竟这个字符在非 WYSIWYG 编辑器中编辑时非常影响编辑体验

**Comment by frostime** [comment]
顶一下，对程序猿来说在IDE里面打开makdown的情况还是挺多的。

**Comment by 88250** [comment]
去掉的话导出 Markdown 会有很多解析失败的情况哦。

**Comment by 88250** [comment]
> 移除非嵌套的行内元素标志符前后的零宽字符没有任何问题

还是有问题的，参考这种情况 https://ld246.com/article/1597581380183

https://github.com/siyuan-note/siyuan/issues/9542 会减少零宽空格使用：将零宽空格改为实际空格。

这个变更的原因是 Pandoc 转换时无法处理零宽空格。但使用实际空格的话会改变文本，综合考虑还是只能使用实际空格。

嵌套情况仍然还是使用零宽空格区隔。
