### ISSUE TITLE
Search dialog and doc tree panel support `Alt+.` to open in right

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8528]
打开搜索结果时，“向右分屏打开” 能否给一个键盘快捷键

### In what scenarios do you need this feature?

如下，“向右分屏打开” 现在的快捷键是Alt+Click，但有时候，切回鼠标操作，会比较慢，能否给一个键盘快捷键，比如Alt+Enter

![image](https://github.com/siyuan-note/siyuan/assets/5683995/7102eeea-c8b1-4818-add3-c4ed72461ae0)

### Describe the optimal solution

*

**Comment by 88250** [comment]
@Vanessa219 文档树上也不支持 Alt/Shift+Enter 分屏打开

**Comment by zhoutaosheng** [comment]
> 和这个保持一致如何？ <img alt="image" width="399" src="https://user-images.githubusercontent.com/970828/245525923-5516d22a-51ac-45da-bbae-559ab503e0e6.png">

赞，保持一致性，当然最好了
