### ISSUE TITLE
Incorrect rendering of exporting images on iOS

### ISSUE THREAD

**Issue by DreamsCat** [siyuan-note/siyuan#8532]
iOS 端导出图片渲染异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在电脑中导出没问题，在手机上导出会有这问题
1.手机上导出
![IMG_1242](https://github.com/siyuan-note/siyuan/assets/52805134/c39bea59-e191-44f6-81de-3e61f2803a52)

### Expected result

导出格式正常

### Version environment

```markdown
- Version: 2.9.1
- Operating System: IOS 16.6
```

### Log file

源文件
[Scope 作用域.sy.zip](https://github.com/siyuan-note/siyuan/files/11740603/Scope.sy.zip)

**Comment by 88250** [comment]
![Screenshot_2023-06-14-10-35-50-971_com android ch](https://github.com/siyuan-note/siyuan/assets/873584/66c52653-fa4e-47a7-9a07-15a3ac09f6a8)

我这里在 Android 上测试正常（打开了编辑器代码块换行） @Vanessa219
