### ISSUE TITLE
Pandoc is not initialized in some cases

### ISSUE THREAD

**Issue by DreamsCat** [siyuan-note/siyuan#8533]
在某些情况下未初始化 Pandoc

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Word 导出未生效，没有生成文件
![iShot_2023-06-14_10 16 52](https://github.com/siyuan-note/siyuan/assets/52805134/60ae2a67-f471-4db5-aea7-aa91aab3f3d3)

### Expected result

成功导出 word

### Version environment

```markdown
- Version: 2.9.1
- Operating System: macos13.4
- Browser (if used):
```

### Log file

无

**Comment by DreamsCat** [comment]
点击导出后，没有生成相关 word

**Comment by 88250** [comment]
请导出系统内核日志上传。

**Comment by DreamsCat** [comment]
@

> 请导出系统内核日志上传。

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11740959/system-log.zip)

**Comment by DreamsCat** [comment]
@88250 D大看看

**Comment by 88250** [comment]
日志中没有报错，导出 Word 有点慢，上面你的录屏看不到提示，你等正在导出提示完看看会不会弹出导出完成的提示。

**Comment by DreamsCat** [comment]
> 日志中没有报错，导出 Word 有点慢，上面你的录屏看不到提示，你等正在导出提示完看看会不会弹出导出完成的提示。

不行，就上文的测试文档，等了几分钟都没弹出窗口，不应该呀

**Comment by DreamsCat** [comment]
> 日志中没有报错，导出 Word 有点慢，上面你的录屏看不到提示，你等正在导出提示完看看会不会弹出导出完成的提示。

你那边试试能不能复现

**Comment by 88250** [comment]
呃，我之前就试过了才给你说的，如果能重现的话就直接标记为 Bug 了……

再试下打开开发者工具，切换到 Console 看看导出按下后有没有报错。

**Comment by DreamsCat** [comment]
> 呃，我之前就试过了才给你说的，如果能重现的话就直接标记为 Bug 了……
> 
> 再试下打开开发者工具，切换到 Console 看看导出按下后有没有报错。

我重新试了下，帮忙看看
![iShot_2023-06-15_09 13 56](https://github.com/siyuan-note/siyuan/assets/52805134/661e769f-12c5-402f-888f-721dd549e0f4)

内核日志：
[system-log.zip](https://github.com/siyuan-note/siyuan/files/11751749/system-log.zip)

**Comment by 88250** [comment]
内核日志里还是没有报错，试试切换到 Network 看看请求。

**Comment by 88250** [comment]
还有，试下新建一个工作空间，在新的工作空间上测试看看。

**Comment by DreamsCat** [comment]
> 内核日志里还是没有报错，试试切换到 Network 看看请求。

<img width="668" alt="image" src="https://github.com/siyuan-note/siyuan/assets/52805134/e64e0fca-1d2f-482e-a2b6-089d0c52cc39">
发现问题了，没有导出配置，至少也得给出个提示吧，不然都不知道哪里有问题

**Comment by 88250** [comment]
好的，稍后我们看下可能是前端显示的 bug，感谢反馈。

**Comment by DreamsCat** [comment]
> 内核日志里还是没有报错，试试切换到 Network 看看请求。

<img width="1075" alt="image" src="https://github.com/siyuan-note/siyuan/assets/52805134/36e58437-fe8b-453e-941c-3c639e5d5aec">
而且这个是思源自带了吗？为啥还不行的，难道需要自己下载？

**Comment by DreamsCat** [comment]
> 好的，稍后我们看下可能是前端显示的 bug，感谢反馈。

我知道原因了，之前安装思源的时候，工作空间默认就是这个，随后把工作空间手动迁移到其他文件夹下了，这个可执行路径没有更新过来，一直都是旧的

@88250 D大 麻烦看看这个是否可以处理下？跟着工作空间的路径走，不要按照第一次初始化的路径固定住，不然容易引发此问题

**Comment by 88250** [comment]
之前你手动调整过 设置 - 导出 - Pandoc 路径 吗？

**Comment by DreamsCat** [comment]
> 之前你手动调整过 设置 - 导出 - Pandoc 路径 吗？

从来没有，我是昨天才发现有导出 Word 功能的，所以试了下，之前都不知道有 Pandoc 路径这一配置

**Comment by 88250** [comment]
```
I 2023/06/15 09:12:58 pandoc.go:115: built-in pandoc [ver=3.1.1, bin=/Users/dream/SiYuan/temp/pandoc/bin/pandoc]
```

现在你手动设置这个选项了吗？没有的话先不要动，看下工作空间/conf/conf.json 中 `pandocBin` 的值。

**Comment by DreamsCat** [comment]
> ```
> I 2023/06/15 09:12:58 pandoc.go:115: built-in pandoc [ver=3.1.1, bin=/Users/dream/SiYuan/temp/pandoc/bin/pandoc]
> ```
> 
> 现在你手动设置这个选项了吗？没有的话先不要动，看下工作空间/conf/conf.json 中 `pandocBin` 的值。

。。。额，我刚已经手动设置过了，现在这个值就是我手动设置过的值。。

**Comment by 88250** [comment]
好的，没关系，通过上面你的截图基本也确认问题了，感谢感谢，后续会改进 Pandoc 的初始化代码实现来避免这个问题。

**Comment by mozhux** [comment]
dev2 导出opml直接卡死， pandoc占用爆内存，dev3 导出opml 无内容。
![_{1PBETZJQGIX@59O_ D5NA](https://github.com/siyuan-note/siyuan/assets/46953371/48083fd0-bb43-42f7-b678-dec3965ea68f)

**Comment by 88250** [comment]
@mozhux 感谢反馈，稍后修复。
