### ISSUE TITLE
思源版本变来变去

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#8534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

今天早上，我打开思源，显示版本是2.8.9

我正奇怪呢，因为前几天就一直在用2.9.1了

然后我选择更新，显示更新失败。

再次打开，变成2.9.1 了

然后现在中午再打开思源，好嘛，版本变成 2.8.8 了我晕了。
![image](https://github.com/siyuan-note/siyuan/assets/37429029/5eb9968c-3d7d-41b7-8506-1363b45ed4b4)

### Expected result

版本不要再变化了

### Version environment

```markdown
- Version: 2.8.8~2.9.1
- Operating System: win
- Browser (if used):
```

### Log file

none

**Comment by AugustTuan** [comment]
我上周反馈地时候，版本还是2.9.0
[Add plugin with setting to top bar plugin menu · Issue #8486 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/8486)

**Comment by 88250** [comment]
你得确定一下是不是安装了多个版本，启动了不一样的版本。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
