### ISSUE TITLE
插件介绍页readme的markdown checkbox显示与github不一致

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#8536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

```markdown
- [ ] aaa
- [x] bbb
``` 

Github上markdown的checkbox表示如下:

- [ ] aaa
- [x] bbb

但是在思源笔记的插件介绍页，渲染成了这样：

![image](https://github.com/siyuan-note/siyuan/assets/19968935/75ce2420-03ef-4a51-be15-759fc3fd7f79)

### Expected result

问题不大，但还是希望能统一一下显示

### Version environment

```markdown
- Version: 2.9.1
- Operating System: Win11
```

### Log file

N/A

**Comment by Vanessa219** [comment]
思源上会统一使用 Lute 渲染器进行渲染，样式也没有照抄 GitHub 的，因此没有办法保持和 GitHub 上的完全一致。
