### ISSUE TITLE
闪卡复习界面是否可以显示是否是闪卡的标记，以便在复习时取消闪卡或者新增，方便辨识

### ISSUE THREAD

**Issue by Miluo2** [siyuan-note/siyuan#8537]
### In what scenarios do you need this feature?

闪卡复习界面
![image](https://github.com/siyuan-note/siyuan/assets/105217767/17dcd007-b4a9-427f-99c1-e67f5c926c7c)

### Describe the optimal solution

闪卡复习界面建议显示是否是闪卡的标记，建议增加笔记中的闪卡标记
![image](https://github.com/siyuan-note/siyuan/assets/105217767/243c8517-a724-4f42-9849-fa83c39cef25)

**Comment by 88250** [comment]
复习时就是这个块已经制卡了，再显示右边的标记的话有点多余啊。

**Comment by Miluo2** [comment]
考虑到会取消闪卡，但是按了快捷键之后无法确定自己是否取消了。或者是将当下的闪卡拆分成了两个，后面一个闪卡加标记无法确定是否加上了。

**Comment by Miluo2** [comment]
当然，D大考虑下就行，不一定非得加，毕竟众口难调，我的需求可以自己克服的

**Comment by 88250** [comment]
先不添加了，这个也许可以通过插件或者自定义 CSS 扩展，谢谢。

**Comment by Miluo2** [comment]
好的

**Comment by zxhd863943427** [comment]
请查看闪卡增强插件，这个有针对闪卡的样式增强。

**Comment by Miluo2** [comment]
嗯嗯，的确可以了，感谢感谢
