### ISSUE TITLE
搜索支持锚文本模板

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#854]
v0.5.44 版本，`{{.text}}` 模板在搜索候选项里不转换显示，模板指向的那个名称无法用做搜索关键词

![image](https://user-images.githubusercontent.com/32661922/103170670-fc400580-4880-11eb-83b4-ccf7bdc4419c.png)

**Comment by 88250** [comment]
感谢反馈，v0.5.45 修复。

**Comment by 88250** [comment]
对了，你觉得搜索时应该出现这个吗？
![image](https://user-images.githubusercontent.com/873584/103171824-277b2280-488a-11eb-8b67-bd6240d52a14.png)

**Comment by deerainw** [comment]
感觉这个 id 就没必要在搜索里显示了吧，比如上面这个例子里的 bar 只是刚好出现搜索结果里，用户真正想搜的是 foo 相关的内容，如果 bar 把自己的一串 id 显示出来就喧宾夺主了。如果搜索 foo 的时候某行结果里有 bar1 bar2 bar3，它们三个全都显示一串信息出来，这一行搜索结果就没有可读性了
