### ISSUE TITLE
插件API调用冲突导致产生无法预知的后果

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/TinkMingKing/siyuan-plugins-index
我的插件在调用后端api时曾产生严重错误
## 操作步骤及现象
首先，插件的功能（文档构建器）调用了`changeSort`，`createDocWithMd`，`sql`三个api
某次操作时，发现没有成功创建文档，之后多次调用，发现文档树没有正确显示，但是双链能够发现，也能够打开文档，打开后，只有被打开的文档在文档树显示，于是手动点击了重建索引，但是没有效果，又多次使用插件功能，此时思源检测到了索引错误，自动重建，重建后部分文档数据丢失
## 原因推测
可能当时思源正在重建索引或者某些重要操作，此时插件调用api，导致索引出错，如果是siyuan后端自身，此时不会进行冲突操作，但是插件此时调用，产生了预料之外的错误

### Expected result

我认为后端在进行重要操作时，应该屏蔽部分api，确保不会被插件干扰操作

### Version environment

```markdown
- Version: 2.9.1
- Operating System: win10
- Browser (if used):
```

### Log file

回头再去找找，如有再补

**Comment by 88250** [comment]
走 API 的话操作都是异步的，内核会控制具体的执行，不会导致冲突的。重建索引不会影响文件系统数据写入或者读取，只是影响数据库的状态，这两个操作不会相互阻塞。

具体的问题我估计需要你后续帮忙留意，特别是重现步骤，谢谢，我先关闭了。

**Comment by TinkMingKing** [comment]
> 走 API 的话操作都是异步的，内核会控制具体的执行，不会导致冲突的。重建索引不会影响文件系统数据写入或者读取，只是影响数据库的状态，这两个操作不会相互阻塞。
> 
> 具体的问题我估计需要你后续帮忙留意，特别是重现步骤，谢谢，我先关闭了。

这是昨天的日志
2023/06/14 15:50前后

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11752329/siyuan.log)

**Comment by 88250** [comment]
日志上暂时无法分析出原因，还是需要重现步骤，多帮忙留意，谢谢。
