### ISSUE TITLE
Open custom tab from link by custom protocol

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8544]
### In what scenarios do you need this feature?

Insert excalidraw into document. Open the excalidraw by click the link instead of clicking in plugin dock.

### Describe the optimal solution

Define a protocol link like `siyuan-tab://{tab-type}?paramsA=1&paramsB=2. 

1. tab-type is defined by plugin when register a tab.
2. Pass the request parmas as data to `openTab` and automatically open it.
3. Plugin developer can generate the links for users and paste in the document.

**Comment by ippreacher** [comment]
辛苦Z大！另外能否在白板中引用和嵌入思源的文档或块？这样基本是白板的完全体了

**Comment by zuoez02** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/4801955/f19df361-aa2c-48dc-a0c9-0925882a2329)
现在简单来做的话，你可以复制一个文档或者块的超链接给一个元素，点击连接可以打开它。后面再想办法支持浮动的文档框

**Comment by ippreacher** [comment]
谢谢，我目前也是这样用的。希望在白板中能通过[[来搜索块，然后引用或嵌入，不知道能否实现。如果能够实现的话，思源的白板也基本差不多了：）
