### ISSUE TITLE
建议新增多个图片、代码段中可以直接插入新的换行符的功能

### ISSUE THREAD

**Issue by ChirsGod** [siyuan-note/siyuan#8545]
### In what scenarios do you need this feature?

目前思源笔记如果两个代码段是连续的情况下，在中间想要增加文本内容非常困难。只能把某一个代码段剪切后，手动增加新的一行然后再粘贴回来这个代码段。如下图所示：
![image](https://github.com/siyuan-note/siyuan/assets/50586375/81f71807-b3fa-4aeb-8627-4067491cf9d4)

### Describe the optimal solution

建议的做法是，仿照飞书云文档的做法。当两个代码段、图片连续时，想要在中间增加文本只需要鼠标点击中间区域，直接就插入了新的一行。如下图所示：
之前：
![image](https://github.com/siyuan-note/siyuan/assets/50586375/29626c52-d595-4064-acb8-2220da7829a3)
之后：
![image](https://github.com/siyuan-note/siyuan/assets/50586375/a4f10d7c-0bf0-4660-8f90-92b3c6a57eee)

**Comment by 88250** [comment]
用块标菜单中的：

![image](https://github.com/siyuan-note/siyuan/assets/873584/2b677ab7-aeca-4af6-bd37-820d31a4bdb1)
