### ISSUE TITLE
`Clear inline elements` can work without selection

### ISSUE THREAD

**Issue by loopodi** [siyuan-note/siyuan#8546]
### In what scenarios do you need this feature?

目前清除样式功能必须先选中文字。

带格式的文字可以在末尾按相应的快捷键取消之后的文字格式，
如果清除样式也有这样的操作逻辑的话，就能用统一的快捷键在光标处清除之后的样式，而无需考虑当前样式的快捷键。
特别是文字本身有多重样式时，这样取消样式更便捷。

### Describe the optimal solution

清除样式快捷键允许在字符边界处使用

**Comment by loopodi** [comment]
就是说前面无论什么样式，按下清除样式快捷键，之后的文字就变正常了。这样做的好处是：不用选中文字；用固定的快捷键清除，还能一次性清除多重样式。

比如目前字体是加粗与下划线，只用快捷键清除的话，要用 ctrl+b 和 ctrl+u。有了这个功能就不用拿鼠标选中文字，直接按一个固定快捷键就清除了。而且和目前操作逻辑一致。

**Comment by Vanessa219** [comment]
现在不按清除打出来的也是普通文本。

**Comment by loopodi** [comment]
像这样有加粗，斜体，标记的样式，在光标之后打出来的是带样式的：
![text](https://github.com/siyuan-note/siyuan/assets/85782310/5c23b5f9-5170-405c-bdf2-40ebe05a2c1e)

用快捷键的话，要把所有对应样式快捷键按一遍，才能打出普通文本。

**Comment by Vanessa219** [comment]
你这个是粗体、斜体等等的行内元素的组成的了，清除样式顾名思义只是清除样式（字号，大小，背景，颜色），清除不了这些行内元素。

**Comment by loopodi** [comment]
工具栏上的那个清除样式，就是默认快捷键 ctrl+\ 那个，不是可以清除一切样式吗？包括行内样式。

现在只是允许这个快捷键在光标处可用。

**Comment by Vanessa219** [comment]
哦，抱歉，我理解为这个去了。可能需要修改一下文案来进行区分。
<img width="397" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/a04ff2bc-a93d-4994-9b81-3e6d4cd1538e">
