### ISSUE TITLE
我在cos云端已经有几十个快照了

### ISSUE THREAD

**Issue by oct1231** [siyuan-note/siyuan#8549]
### In what scenarios do you need this feature?

如果现在的快照逻辑是像git那样的分布式,那么将无法放心的在思源上面存一些文件,一旦上传 永久性的占用cos空间  ,我这个需求应该是最基础的需求了 ,或者官方有在其他的地方释放吗  我现在没有发现

### Describe the optimal solution

需要可以删除快照的功能,或者数量超过多少自动删除

**Comment by 88250** [comment]
是类似 git 那样累计数据，这样才能最大限度保障数据安全。

如果担心空间占用太大，可以考虑手动删除云端后再重新上传。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by fangguangyang** [comment]
官方云最多支持12个快照，能不能给第三方webdav也支持这种设置啊

**Comment by 88250** [comment]
@fangguangyang 使用自己的存储不限制标记快照的。

**Comment by oct1231** [comment]
>  官方云最多支持12个快照，能不能给第三方webdav也支持这种设置啊
@88250 
我们不担心数据丢失，但担心日益增长的数据缓存在COS上。如果删除了大量文件，我们还得手动到COS上清空并重新同步。一般使用COS同步的用户都有一定的计算机基础，不用担心会弄丢之前的数据。另外，官方也只支持12次同步，可以提供没有快照的同步（我个人认为这种方式最好）。与Obsidian类似，我的想法是思源不仅仅是一个笔记，还是一个网盘，可以放置许多资料。此外，我们也可以使用快照过期机制自动释放，或者开发界面手动管理删除不需要的快照。

**Comment by 88250** [comment]
12 个的限制那个不是同步产生的快照，而是手动标记快照的数量限制，同步产生的快照不限制数量的。

目前没有过期机制，这个可能需要等其他人贡献了，我们目前没有精力进行开发，相关源码库 https://github.com/siyuan-note/dejavu 感谢理解

**Comment by fangguangyang** [comment]
> 12 个的限制那个不是同步产生的快照，而是手动标记快照的数量限制，同步产生的快照不限制数量的。
> 
> 目前没有过期机制，这个可能需要等其他人贡献了，我们目前没有精力进行开发，相关源码库 https://github.com/siyuan-note/dejavu 感谢理解

能不能将自动同步的速率支持自定义配置，30s不变动就同步一次产生一个快照，我一个上午就产生几十个了
![image](https://github.com/siyuan-note/siyuan/assets/14014903/2cf8ad5e-20ff-4644-9210-e5d618ba243f)

**Comment by 88250** [comment]
@fangguangyang 试试 设置 - 云端 - 云端同步模式

**Comment by fangguangyang** [comment]
@88250 另外两个手动同步配置还是不满足使用场景，即能满足不需要人去点同步，又能按时上传

比如公司电脑24小时开机，软件也常驻，在公司写的文档不追求很实时同步上传，下班后或者周末能在家里同步到就行（用户自定义自动上传同步频率）

**Comment by 88250** [comment]
那没办法了……你需要自动同步但是又觉得快照太多，这是冲突的啊……
