### ISSUE TITLE
用图标的方式表示空文件夹、非空文件夹、已打开文件夹

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#855]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

在用了 Typora 一段时间之后，发现左侧文件列表，中文件夹，左侧的小箭头图标非常烦人，经常让我对左侧文件夹列表的级别感到迷惑，要仔细缓上两三秒钟才能看懂文件夹的级别关系：

![image](https://user-images.githubusercontent.com/19181833/103190780-61d9d380-490d-11eb-8341-4d8e861aee56.png)

而目前思源也是用的这种带小箭头的方式表示文件夹是否为空，用小箭头的方向表示该文件夹是否被展开。如果在比较深的层级，比如第三层、第四层，有时候一眼看到这个列表，就会让大脑困惑一两秒钟，仔细查看后才能弄明白所表示的文件夹层级。

所以希望可以用另外一种方式来表示文件夹是否为空和文件夹的层级，不要使用在左边添加一个符号的方式来表示。

### 描述最优的解决方案 Describe the optimal solution

现在的文件夹只有一个图标。设计三种文件夹图标，分别对应空文件夹、非空文件夹、已打开文件夹，对三种文件夹状态使用不同的图标，就无需在文件夹图标左边再添加一个可能造成视觉干扰的小箭头图标。

**Comment by 88250** [comment]
你好，你描述的解决方案似乎也不能解决一眼看到层级的问题……另外，我觉得层级似乎不是问题……

**Comment by HaujetZhao** [comment]
> 你好，你描述的解决方案似乎也不能解决一眼看到层级的问题……另外，我觉得层级似乎不是问题……

可能没讲清楚使用箭头图标导致层级模糊的根本原因：多重态的左对齐。

因为：

* 有的文件夹图标左边带一个向右的小箭头（非空，但是未打开）
* 有的文件夹图标左边带一个向下的小箭头（非空，已打开）
* 有的文件夹图标左边没有小箭头（空文件夹）

这就导致同一个层级的 item，他们本来应该有同样的缩减量用于表示其所处层级，但实际上却在视觉上有着不同的缩进量，用一个图来表示，这是在我一眼扫到文件夹列表时所看到的缩进数：

![image](https://user-images.githubusercontent.com/19181833/103205735-379c0c00-4935-11eb-9077-cfa6c4dcecf6.png)

如上图，各种犬牙差互、缩进量不同的 item 一下子把层次思维打乱了，要多仔细看两秒，才能反应过来要以哪里对齐，来查找缩进量。

但是，如果把箭头图标去掉，再扫一眼，就会看到很整齐的缩进量：

![image](https://user-images.githubusercontent.com/19181833/103205833-70d47c00-4935-11eb-88e5-0bc091f13c1f.png)

如上图，视线只要以左对齐为基线，就可以很清晰地一瞬间判断出具体的层级关系。

上图中所有的文件夹图标都使用了一个样式，不能表达文件夹是否被打开、文件夹是否为空，所以在实际应用的时候需要三种大小一样、但是略有差异的文件夹图标，用于表示三种状态的文件夹。

**Comment by 88250** [comment]
我觉得在思源里好像还是对齐的呢 :joy:
