### ISSUE TITLE
云端同步目录bug

### ISSUE THREAD

**Issue by oct1231** [siyuan-note/siyuan#8550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/43901930/014d8b37-089a-4b9c-8bdd-f207a640d9fb)
这里显示的是我云端所有的buket,并且也不可选中 我的这个时腾讯云的cos 也没有创建所谓的main文件夹  在我填写的buket里面创建了repo 但是这个功能岂不是没有任何用处 我认为可能我的使用出了bug

### Expected result

正常使用

### Version environment

```markdown
- Version: 2.9.1
- Operating System: windows
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11757031/siyuan.log)

**Comment by 88250** [comment]
使用第三方同步的话这里对应的是云端的 bucket，无法在这个界面管理（比如删除操作），需要到云端服务提供商的界面管理，感谢反馈。
