### ISSUE TITLE
Add `Paste as plain text` to the editor right-click menu in the browser

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#8553]
### In what scenarios do you need this feature?

目前只`粘贴`、`粘贴转义文本`。希望右键菜单加`粘贴纯文本`选项。
用于快速去除一些内部链接和其他效果。

### Describe the optimal solution

右键菜单加`粘贴纯文本`选项

**Comment by 88250** [comment]
请问是什么环境？

**Comment by IAliceBobI** [comment]
> 请问是什么环境？

linux下，直接运行的 `SiYuan-Kernel -wd /data/siyuan/app`

**Comment by 88250** [comment]
浏览器上使用的吗？

**Comment by IAliceBobI** [comment]
> 浏览器上使用的吗？

对
