### ISSUE TITLE
docker下选择导出为图片的时候，跳转的下载链接无效，显示当前无法使用此页面

### ISSUE THREAD

**Issue by kokojacket** [siyuan-note/siyuan#8557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我使用最新版的siyuan ,部署在我的openwrt上，选择导出为图片的时候，跳转的下载链接无效，显示当前无法使用此页面

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/74887370/1c63584a-0464-41d8-967b-680189dd7666)

### Version environment

```markdown
- Version: v2.9.1
- Operating System: openwrt
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
应该是反向配置的问题，不要使用请求转发，配置为二级域名吧。

**Comment by kokojacket** [comment]
> 

我没有做反向代理，不太明白请求转发是啥。不好意思请问具体怎么解决，因为导出其他格式的网页跳转都是可以直接下载的。
