### ISSUE TITLE
输入数学公式{\displaystyle f_{X}(x)=p^{x}(1-p)^{1-x}=\left\{{\begin{matrix}p&{\mbox{if }}x=1,\\q\ &{\mbox{if }}x=0.\\\end{matrix}}\right.}，不能正确显示，其他数学公式

### ISSUE THREAD

**Issue by edisonzf2020** [siyuan-note/siyuan#8558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

输入行级公式或者公式块：{\displaystyle f_{X}(x)=p^{x}(1-p)^{1-x}=\left\{{\begin{matrix}p&{\mbox{if }}x=1,\\q\ &{\mbox{if }}x=0.\\\end{matrix}}\right.}
标准的LaTeX
提示：undefined
版本：2.9.1

### Expected result

显示公式

### Screenshot or screen recording presentation
出错截图：

![image](https://github.com/siyuan-note/siyuan/assets/95912883/c7f8bc6c-f748-4fc2-a40b-97387950c1f9)

正确的公式显示：

![QianJianTec1686898616421](https://github.com/siyuan-note/siyuan/assets/95912883/5c093ddd-b107-4a1d-9ba9-7579e2981d10)

### Version environment

```markdown
- Version: 2.9.1
- Operating System: ubuntu20.04 docker
- Browser (if used):edge
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11767277/siyuan.log)

**Comment by 88250** [comment]
这个在 KaTex 官网上测试也无法显示，应该是语法不正确。

https://katex.org/
