### ISSUE TITLE
通过siyuan的浏览器插件导入网页到笔记中，数学公式不能以正确的格式保存

### ISSUE THREAD

**Issue by edisonzf2020** [siyuan-note/siyuan#8559]
### In what scenarios do you need this feature?

比如CSDN或者知乎、维基百科的带有LaTeX数学公式的网页，通过siyuan的浏览器插件一键导入到笔记中，文字部分的导入没有问题，数学公式导入后格式都是错的，不是LaTeX格式了。

### Describe the optimal solution

导入数学公式，仍然是LaTeX格式

**Comment by 88250** [comment]
抱歉，浏览器剪藏扩展可能无法处理数学公式。

**Comment by 88250** [comment]
后续请关注：

* https://github.com/siyuan-note/siyuan/issues/5599
* https://github.com/siyuan-note/siyuan/issues/5624
