### ISSUE TITLE
希望能支持alert box

### ISSUE THREAD

**Issue by heshang233** [siyuan-note/siyuan#856]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在某些情况下需要着重提示某些信息时，使用 引用并不能表达出重要信息，且提示信息可能存在轻重不一的情况 比如警告 或者普通。
https://stackoverflow.com/questions/50544499/how-to-make-a-styled-markdown-admonition-box-in-a-github-gist
这里面给出的最佳方式是这样：
> :warning: **If you are using mobile browser**: Be very careful here!

但是并不是特别醒目。在全文中可能无法做到一眼就能看到。

从最下面的回答中我找到了来自于微软的docs markdown的示例
>[!WARNING]
>This is a warning

即支持alert box： https://docs.microsoft.com/en-us/contribute/markdown-reference#alerts-note-tip-important-caution-warning
能通过颜色直观的提示警示信息

**Comment by 88250** [comment]
估计不会通过引入新语法来实现，而是通过块属性来实现。得等块属性……

谢谢！

**Comment by Vanessa219** [comment]
使用 https://github.com/siyuan-note/siyuan/issues/595  中的样式进行实现。

**Comment by heshang233** [comment]
> 使用 #595 中的样式进行实现。

是否有相关示例，目前我更新后查看帮助文档，没找到相关用法。

**Comment by heshang233** [comment]
体验了一下给文字加颜色和背景色的方式，只能说从颜色方面能够提示到，但是并不雅观。。
> INFO <-这块字体是蓝色
> 这是一条消息

这样的表现结果如下图：
![image](https://user-images.githubusercontent.com/13328402/103986960-a34c6780-51c6-11eb-8733-c76ee4b76d71.png)
虽然表现不尽如人意，但是是个展示方面的改进。
