### ISSUE TITLE
Full-text search should be case insensitive

### ISSUE THREAD

**Issue by vibl** [siyuan-note/siyuan#8562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Full-text search is currently case sensitive, which is very unusual and makes it almost unusable for European languages.

### Expected result

Search should be case insensitive (at least for European languages).

An option for making it case sensitive might be useful (although no use case comes to mind).

### Version environment

```markdown
- Version: v2.9.0
- Operating System: Kubuntu 23.04
- Browser (if used):
```

### Log file

(Not relevant)

**Comment by mozhux** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/46953371/efecf43d-8c46-4b3b-8ba9-229de29f16b5)

**Comment by vibl** [comment]
Ok. I'd recommend making it case insensitive by default for European language. A case sensitive full-text search does not make any sense for any use case I can think of.

Thanks so much for Siyuan, which seems to be an amazing piece of software! I'm a long-time user of many note-taking apps and outliners and it seems much better than any other I've tried so far. I'm considering migrating to it from Logseq.

**Comment by mozhux** [comment]
> Ok. I'd recommend making it case insensitive by default for European language. A case sensitive full-text search does not make any sense for any use case I can think of.
> 
I also think so
