### ISSUE TITLE
Custom keyboard layout in Linux (with XKB) are not fully recognized

### ISSUE THREAD

**Issue by vibl** [siyuan-note/siyuan#8564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I use a custom keyboard layout in Linux (with XKB) which is standard, bug-free and works fine with every app I've been using so far (probably hundreds at this point).

When not using any key modifier (i.e. when typing normally), I can use Siyuan fine with this keyboard mapping.

But when using the `ctrl` key modifier in Siyuan, my keyboard mapping is not recognized (it seems that Siyuan goes back to a standard English keyboard). For example, `ctrl+c` does not trigger `copy`, etc. 

### Expected result

Custom keyboard layouts in Linux should be usable in Siyuan. This should not be difficult to achieve since it's based on Electron, and I use a lot of Electron apps which all work fine.

### Version environment

```markdown
- Version: v2.9.1
- Operating System: Kubuntu 23.04
- Browser (if used):
```

### Log file
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/06/16 18:18:58 runtime.go:71: kernel is booting:
    * ver [2.9.1]
    * arch [amd64]
    * os [ubuntu]
    * pid [1914349]
    * runtime mode [prod]
    * working directory [/tmp/.mount_siyuanWDjHQI/resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/home/vianney/_/siyuan/vibl]
I 2023/06/16 18:18:58 conf.go:227: upgraded from version [2.9.0] to [2.9.1]
I 2023/06/16 18:18:58 runtime.go:125: use network proxy [system]
I 2023/06/16 18:18:58 serve.go:113: kernel [pid=1914349] http server [127.0.0.1:38581] is booting
I 2023/06/16 18:18:58 tesseract.go:153: tesseract-ocr enabled [ver=5.3.0, maxSize=2.0 MB, langs=eng+osd]
I 2023/06/16 18:18:59 pandoc.go:138: initialized built-in pandoc [ver=, bin=/home/vianney/_/siyuan/vibl/temp/pandoc/bin/pandoc]
I 2023/06/16 18:18:59 serve.go:126: reverse proxy server [127.0.0.1:6806] is booting
I 2023/06/16 18:19:00 sync.go:140: sync before boot
I 2023/06/16 18:19:01 repository.go:1072: boot get sync cloud files elapsed [0.90s]
I 2023/06/16 18:19:01 blocktree.go:448: read block tree [6.5 MB] to [/home/vianney/_/siyuan/vibl/temp/blocktree], elapsed [0.03s]
I 2023/06/16 18:19:01 conf.go:695: database size [108 MB], tree/block count [170/24328]
I 2023/06/16 18:19:01 working.go:155: kernel booted
I 2023/06/16 18:19:01 box.go:79: auto stat [trees=170, blocks=24328, dataSize=18 MB, assetsSize=1.9 MB]
I 2023/06/16 18:19:01 disk.go:33: disk usage [total=502 GB, used=442 GB, free=35 GB]
I 2023/06/16 18:19:01 index.go:133: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.01s], tree [count=56, size=1.1 MB]
I 2023/06/16 18:20:03 repository.go:1180: synced data repo [kernel=ad934kp, provider=2, ufc=5, dfc=1, ucc=0, dcc=0, ub=8.4 kB, db=7.7 kB] in [0.73s]

**Comment by vibl** [comment]
I think I found the reason: You're using a deprecated JS property (`keyCode`) at https://github.com/siyuan-note/siyuan/blob/e1ae93271e5c1e9a66f5786a62a5fd39e643fb24/app/src/protyle/util/hotKey.ts#L146, 

Instead, you should use the `key` property of the `KeyboardEvent` returned by the `keydown` event.

**Comment by 88250** [comment]
Perhaps it is similar to https://github.com/siyuan-note/siyuan/issues/7115 @Vanessa219

**Comment by vibl** [comment]
It could be similar but I don't know if it is the same problem (I don't read Chinese).

What do you think about the solution I'm suggesting above? (https://github.com/siyuan-note/siyuan/issues/8564#issuecomment-1594992756)

**Comment by Vanessa219** [comment]
This is not the problem, please try it if it is resolved when the next version is released?

**Comment by 88250** [comment]
v2.9.2 has been released, please check if resolves this issue, thanks.

**Comment by vibl** [comment]
It does! Thank you :-)
