### ISSUE TITLE
Move around Doc Tree when searching or creating a ref

### ISSUE THREAD

**Issue by uxiun** [siyuan-note/siyuan#8565]
### In what scenarios do you need this feature?

It would be great if I could search documents hierarchically or create a new document and specify it's path at once. 

### Describe the optimal solution

This is the recursive operation flows for interacting with hierarchy. Some of them are already implemented in RemNote.

- Flows
    - All modes hove `shortcut` to confirm current selection and exit.
    - global search mode (default) 
        - input text to search all documents
            - existing doc or block
                - `Tab` to zoom in. Go to hierarchy mode with **scope root** = current item.
                - `Shift Tab` to zoom out. Go to hierarchy mode with **scope root** = current scope root's parent
                - `ArrowUp / Down` to move in displaying list.
    - Following 3 modes have `shortcut` for
        - go back and forth operation history per mode change, restoring input text.
        - select new doc (useful when number of matching is large)
    - hierarchy mode (if only after move hierarchically). attribute: **scope root** 
        - input text to search **scope root**'s descendants or direct children (toggle search depth by `shortcut`) 
        - display **scope root**'s children or search result.
        - selecting 
            - existing doc 
                - same as above 
            - new doc
                - `Tab` to go to new child mode to create another new doc under this new doc. 
                - `Shift Tab` to go to new parent mode to specify the parent doc of selecting item.
    - Following 2 modes create **virtual tree** structured with new docs that persists through modes.
        - When confirming, if **virtual tree**'s root is a header, it is instanciated as subheading or if there is not enough heading level, remaining deeper parts are represented by list. 
    - new child mode 
        - input name of new doc.
        - `Tab` ... same as above
        - `Shift Tab` to go to new parent mode to specify the parent doc of **virtual tree**'s root. 
    - new parent mode 
        - input text to search all documents. 
        - display **virtual tree**'s root or search result.
        - selecting 
            - existing doc or block 
                - same as above
            - new doc 
                - `Tab` to go to new child mode to create another new doc under this new doc (add branch to **virtual tree**)
                - `Shift Tab` to go to new parent mode to specify the parent doc of **virtual tree**'s root. 

### Describe the candidate solution

Displaying Doc Tree as normal list block will allow us to easily mutate not only one doc but also multiple docs, which will be useful. (Actually, I sometimes get confused and have questions to separate documents and normal blocks because I used to outliners, though)

**Comment by 88250** [comment]
SiYuan can only limit the search scope by specifying a path. For more complex searches, you can consider using SQL, which is different from outline tools, but similar to Notion-like tools.

Specifying the save path when creating a block reference is still discussed in https://github.com/siyuan-note/siyuan/issues/7995, thanks.

We have closed this issue, thank you again for your understanding and proposal.
