### ISSUE TITLE
搜狗输入法下，全角符号不能自动变半角，其他编辑器可以

### ISSUE THREAD

**Issue by ippreacher** [siyuan-note/siyuan#857]
### 描述问题 Describe the problem
搜狗输入法的中文输入状态下，全角符号不能自动变半角，其他编辑器可以，如notepad，notepad2，everedit，word都可以

### 期待的结果 Expected result
希望能修正

### 截屏或录屏演示 Screenshot or screen recording presentation
![_20201228162552](https://user-images.githubusercontent.com/53852556/103201066-ea666d00-4929-11eb-975f-d4f561c5d114.gif)
![_20201228162722](https://user-images.githubusercontent.com/53852556/103201070-ed615d80-4929-11eb-8240-56ad84d867ef.gif)

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
应该是因为搜狗输入法不能识别思源的文档结构导致，这个暂时无解，见谅。
