### ISSUE TITLE
chatgpt Requesting failed, please check kernel log

### ISSUE THREAD

**Issue by lutgcy** [siyuan-note/siyuan#8570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Requesting failed, please check kernel log
![image](https://github.com/siyuan-note/siyuan/assets/42140616/811f04a7-dbdb-432f-89c4-5074dad85762)

### Expected result

<img width="993" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42140616/98c407e7-b001-41c5-b7e6-4390d302102c">

key是自己的且是可用的，使用的时候为什么会报错，已经使用代理软件了，网页也能正常使用chatgpt，应该怎么配置

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

I 2023/06/18 00:59:52 working.go:115: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/06/18 00:59:52 runtime.go:71: kernel is booting:
    * ver [2.9.1]
    * arch [arm64]
    * os [darwin]
    * pid [5261]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/guochengye/develop/siyuan-data]
I 2023/06/18 00:59:52 conf.go:109: initialized the specified language [zh_CN]
I 2023/06/18 00:59:53 runtime.go:125: use network proxy [system]
I 2023/06/18 00:59:53 serve.go:113: kernel [pid=5261] http server [127.0.0.1:55567] is booting
I 2023/06/18 00:59:53 database.go:88: the database structure is changed, rebuilding database...
I 2023/06/18 00:59:53 database.go:108: reinitialized database [/Users/guochengye/develop/siyuan-data/temp/siyuan.db]
I 2023/06/18 00:59:53 conf.go:699: database size [4.1 kB], tree/block count [0/0]
I 2023/06/18 00:59:53 working.go:153: kernel booted
I 2023/06/18 00:59:53 box.go:79: auto stat [trees=0, blocks=0, dataSize=33 kB, assetsSize=0 B]
I 2023/06/18 00:59:53 disk.go:33: disk usage [total=494 GB, used=75 GB, free=420 GB]
I 2023/06/18 00:59:53 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.01s], tree [count=60, size=1.2 MB]
I 2023/06/18 00:59:53 index.go:206: resolved refs [25] in [8ms]
I 2023/06/18 00:59:54 serve.go:126: reverse proxy server [127.0.0.1:6806] is booting
I 2023/06/18 00:59:58 pandoc.go:141: initialized built-in pandoc [ver=3.1.1, bin=/Users/guochengye/develop/siyuan-data/temp/pandoc/bin/pandoc]
I 2023/06/18 00:59:58 conf.go:906: pandoc initialized, set pandoc bin to [/Users/guochengye/develop/siyuan-data/temp/pandoc/bin/pandoc]
I 2023/06/18 01:01:24 index.go:133: rebuilt database for notebook [20230618010124-x8dlnsq] in [0.00s], tree [count=0, size=0 B]
I 2023/06/18 01:01:24 index.go:206: resolved refs [25] in [22ms]
I 2023/06/18 01:09:23 conf.go:472: exiting kernel [force=false, execInstallPkg=0]
I 2023/06/18 01:09:23 database.go:1134: closed database
I 2023/06/18 01:09:23 conf.go:846: cleared workspace temp
I 2023/06/18 01:09:24 conf.go:518: exited kernel
I 2023/06/18 01:09:24 sync.go:649: sync websocket closed
I 2023/06/18 01:09:28 working.go:115: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/06/18 01:09:28 runtime.go:71: kernel is booting:
    * ver [2.9.1]
    * arch [arm64]
    * os [darwin]
    * pid [5718]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/guochengye/develop/siyuan-data]
I 2023/06/18 01:09:28 runtime.go:125: use network proxy [system]
I 2023/06/18 01:09:28 serve.go:113: kernel [pid=5718] http server [127.0.0.1:55825] is booting
I 2023/06/18 01:09:28 blocktree.go:435: read block tree [677 kB] to [/Users/guochengye/develop/siyuan-data/temp/blocktree], elapsed [0.01s]
I 2023/06/18 01:09:28 conf.go:699: database size [4.7 MB], tree/block count [63/2491]
I 2023/06/18 01:09:28 working.go:153: kernel booted
I 2023/06/18 01:09:28 pandoc.go:118: built-in pandoc [ver=3.1.1, bin=/Users/guochengye/develop/siyuan-data/temp/pandoc/bin/pandoc]
I 2023/06/18 01:09:28 conf.go:906: pandoc initialized, set pandoc bin to [/Users/guochengye/develop/siyuan-data/temp/pandoc/bin/pandoc]
I 2023/06/18 01:09:28 box.go:79: auto stat [trees=63, blocks=2491, dataSize=4.7 MB, assetsSize=2.0 MB]
I 2023/06/18 01:09:28 disk.go:33: disk usage [total=494 GB, used=75 GB, free=419 GB]
I 2023/06/18 01:09:28 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.01s], tree [count=60, size=1.2 MB]
I 2023/06/18 01:09:29 serve.go:126: reverse proxy server [127.0.0.1:6806] is booting
E 2023/06/18 01:14:03 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
E 2023/06/18 01:21:22 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
E 2023/06/18 01:21:53 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
I 2023/06/18 01:22:27 conf.go:472: exiting kernel [force=false, execInstallPkg=0]
I 2023/06/18 01:22:27 database.go:1134: closed database
I 2023/06/18 01:22:27 conf.go:846: cleared workspace temp
I 2023/06/18 01:22:27 conf.go:518: exited kernel
I 2023/06/18 01:22:27 sync.go:649: sync websocket closed
W 2023/06/18 01:22:28 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
I 2023/06/18 01:23:11 working.go:115: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/06/18 01:23:11 runtime.go:71: kernel is booting:
    * ver [2.9.1]
    * arch [arm64]
    * os [darwin]
    * pid [639]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/guochengye/develop/siyuan-data]
I 2023/06/18 01:23:11 conf.go:358: OpenAI API enabled
    baseURL=https://api.openai.com/v1
    timeout=10s
    proxy=
    model=gpt-3.5-turbo
    maxTokens=0
I 2023/06/18 01:23:11 runtime.go:125: use network proxy [system]
I 2023/06/18 01:23:11 serve.go:113: kernel [pid=639] http server [127.0.0.1:49159] is booting
I 2023/06/18 01:23:11 blocktree.go:435: read block tree [677 kB] to [/Users/guochengye/develop/siyuan-data/temp/blocktree], elapsed [0.01s]
I 2023/06/18 01:23:11 conf.go:699: database size [5.8 MB], tree/block count [63/2492]
I 2023/06/18 01:23:11 working.go:153: kernel booted
I 2023/06/18 01:23:11 box.go:79: auto stat [trees=63, blocks=2492, dataSize=4.7 MB, assetsSize=2.0 MB]
I 2023/06/18 01:23:11 disk.go:33: disk usage [total=494 GB, used=75 GB, free=420 GB]
I 2023/06/18 01:23:11 pandoc.go:118: built-in pandoc [ver=3.1.1, bin=/Users/guochengye/develop/siyuan-data/temp/pandoc/bin/pandoc]
I 2023/06/18 01:23:11 conf.go:906: pandoc initialized, set pandoc bin to [/Users/guochengye/develop/siyuan-data/temp/pandoc/bin/pandoc]
I 2023/06/18 01:23:11 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.01s], tree [count=60, size=1.2 MB]
I 2023/06/18 01:23:12 serve.go:126: reverse proxy server [127.0.0.1:6806] is booting
E 2023/06/18 01:25:38 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
E 2023/06/18 01:25:58 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
I 2023/06/18 01:26:29 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.01s], tree [count=60, size=1.2 MB]
I 2023/06/18 01:26:29 index.go:206: resolved refs [25] in [8ms]
E 2023/06/18 01:31:23 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
E 2023/06/18 01:33:04 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded
E 2023/06/18 01:34:11 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": dial tcp [2a03:2880:f10d:183:face:b00c:0:25de]:443: i/o timeout
E 2023/06/18 01:34:42 openai.go:54: create chat completion failed: Post "https://api.openai.com/v1/chat/completions": context deadline exceeded

**Comment by 88250** [comment]
试试超时时间 配置为 45。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
