### ISSUE TITLE
反链显示重叠

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#8572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图，默认主题：
![图片](https://github.com/siyuan-note/siyuan/assets/68107073/618f47ef-0c47-4967-9056-7180f1c05594)
原因：该块有两个反链，一个链接的是“无序列表块”，一个链接的是“列表项块”，看起来两个反链是分开显示的，但是重叠了

### Expected result

不重叠

### Version environment

```markdown
- Version: 2.9,1
- Operating System: windows store
- Browser (if used):no
```

### Log file

no

**Comment by 88250** [comment]
这个目前是设计如此，在同一行的块只能这样显示反链计数，无法完全错开显示，感谢反馈。
