### ISSUE TITLE
为虚拟引用也添加shift悬浮查看被引用处的反链的功能

### ISSUE THREAD

**Issue by StarDustSheep** [siyuan-note/siyuan#8574]
### In what scenarios do you need this feature?

在前几个版本，思源添加了[按住shift悬浮于块引用上时查看反链的功能](https://github.com/siyuan-note/siyuan/issues/7999?utm_source=ld246.com)，我认为这个功能也应该加到虚拟引用上。
在生疏的知识文本中看到一个曾经建立过页面但理解和记忆都比较单薄的概念的虚拟引用的时候，也想看看其反链，因为有时候被引处只是作为链接其他信息的节点，真正需要的信息在反链中。

### Describe the optimal solution

按住shift时鼠标悬浮于虚拟引用之上时查看被引用的块的反链

**Comment by 88250** [comment]
这个做不到的，虚拟引用不是引用，所以没有反链关系。

**Comment by StarDustSheep** [comment]
但是鼠标悬浮虚拟引用不是能打开被引用的块的编辑窗吗？既然能获取到被提及的块的信息，在悬浮的时候不能根据这个块的信息来打开这个块的反链面板吗？







                       
原始邮件
                       
                     

发件人："D"< ***@***.*** &gt;;

发件时间：2023/6/18 20:33

收件人："siyuan-note/siyuan"< ***@***.*** &gt;;

抄送人："吃星尘的羊"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [siyuan-note/siyuan] 为虚拟引用也添加shift悬浮查看被引用处的反链的功能 (Issue #8574)




 
这个做不到的，虚拟引用不是引用，所以没有反链关系。

**Comment by 88250** [comment]
技术上是可以，但是逻辑上可能说不通，因为虚拟引用是根据锚文本来获取定义块的，它们之间并没有引用关系，所以逻辑上不应该存在反链关系，这个我们目前不考虑支持了，用插件应该能做。
