### ISSUE TITLE
升级 pdfjs ，或提供pdfjs的 getCachedPageViews() 接口。

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8575]
### In what scenarios do you need this feature?

在写插件的时候需要获取当前pdf已加载的页面，目前思源仅能获取到isPageCached的接口，实现这个功能比较困难。

在pdfjs 的更新[isPageCached](https://github.com/mozilla/pdf.js/commit/c4c8227d20b2a1662e8e119bfcabe2ca6e8738cc)，增加了一个getCachedPageViews的接口，可以返回当前已经加载了的页面，我认为这是一个比较好的接口。这个接口的位置在[pdf_viewer](https://github.com/mozilla/pdf.js/blob/a5c10b6d89854448da0963bdfae00b3e463c46e7/web/pdf_viewer.js#LL347C1-L347C1)，实现也比较简单：
```js
  getCachedPageViews() {
    return new Set(this.#buffer);
  }
```

因此，请求更新pdfjs或修改pdf_viewer以提供该接口。

### Describe the optimal solution

更新pdfjs，或提供getCachedPageViews接口

**Comment by zxhd863943427** [comment]
已使用其他方法实现

**Comment by Vanessa219** [comment]
后续还是会抽空更新的 😊
