### ISSUE TITLE
红黄蓝绿快速样式无法通过alt+x快捷键应用，只会应用背景色而不会应用字色

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8577]
### In what scenarios do you need this feature?

当我需要通过快捷键快速应用字体样式时

### Describe the optimal solution

当我先前使用过红黄蓝绿快速样式后，再次按下alt+x键时同时应用快速样式的字色和背景色。

**Comment by Vanessa219** [comment]
这个只会应用最后一次的字体样式
