### ISSUE TITLE
loaded-protyle 事件无法达到预期效果

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/issues/8421#issuecomment-1594095742

### Expected result

改进

### Version environment

```markdown
- Version: 2.9.1
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
这个已经是放在最后了，你把测试代码发我，我看一看。

**Comment by TinkMingKing** [comment]
https://github.com/TinkMingKing/siyuan-plugins-index/tree/dev
开发分支代码以提交
找一个有子文档的文档插入目录，然后给文档添加新的子文档，下次打开该文档，会更新目录，但是第一次打开时不会更新，第二次打开才会，或者是需要加入延时
相关代码在`protyleevent.ts`文件

**Comment by Vanessa219** [comment]
视频上传不了，我只能压缩。调试的时候界面是已经加载完成，sleep 移除也是没有问题的。
[QQ20230620-195958-HD.mp4.zip](https://github.com/siyuan-note/siyuan/files/11800116/QQ20230620-195958-HD.mp4.zip)

**Comment by Vanessa219** [comment]
桌面端有进行 pnpm run dev:desktop 吗？我这里无法重现。

**Comment by TinkMingKing** [comment]
@Vanessa219 
奇怪，我在我另一台电脑上它能够正常工作，可能是我使用vite的插件模板，热重载导致了某些问题？
算了，先就这样吧，后续有问题再说，我先关了
