### ISSUE TITLE
数据同步功能发生重大变更时使用版本检查保护数据

### ISSUE THREAD

**Issue by DaveBoy** [siyuan-note/siyuan#8582]
### In what scenarios do you need this feature?

> 升级该版本后云端数据不兼容之前的版本，需要所有端都升级到该版本后才能正常使用，混用版本会引起云端数据索引相互覆盖，很有可能会导致云端数据损坏

类似这种情况，是否对同一账户的不同设备增加版本检查判定，如果已经有设备用过高版本，则在其他低版本设备启动时强制要求更新（不然无法使用低版本或者软一点使用一个非常明显的弹窗提示允许继续使用，就不会触发修改影响数据）

使用这种强制措施避免数据损坏，而不是转移到用户看到公告先把所有设备上的都升级再开始使用，毕竟公告很多人都不一定注意看

### Describe the optimal solution

尽量使用强制或明显的提示降低数据损坏的风险，而不是靠用户看更新后弹出来的公告

**Comment by 88250** [comment]
有的设备上更新不了最新版了，比如 Win7/8。

这个估计只能用户自己注意了，强制升级的话体验会比这个更糟糕的，感谢建议。
