### ISSUE TITLE
charles开启代理 思源web端弹出无网络提示

### ISSUE THREAD

**Issue by TtBJSH** [siyuan-note/siyuan#8583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

因为要开启charles进行接口抓包而且有多个思源笔记地址 需要使用chrome浏览器进行访问思源笔记地址 就会出现一个问题 web端会弹出无网络的提示 ，客户端正常，一开始我以为是因为charles没有过滤思源笔记域名的原因，单后来charles过滤掉了域名还是会提示

### Expected result

web端能和客户端一样开启代理也正常使用

### Screenshot or screen recording presentation

**
![image](https://github.com/siyuan-note/siyuan/assets/46512682/b2d2f978-7c72-4783-a2dc-b31167025dcf)
**

### Version environment

```markdown
Version: 2.9.0
- OperatingSystem: windows 11
- Browser (if used):chrome 114.0.5735.134
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11796915/siyuan.log)

**Comment by 88250** [comment]
打开开发者工具看下 Network 请求，多半还是网络配置的问题。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by TtBJSH** [comment]
> 打开开发者工具看下网络请问，多半还是网络配置的问题。
> 
> 我先关了，如果还有问题请继续跟贴，谢谢🙏

**Comment by TtBJSH** [comment]
> 打开开发者工具看下网络请问，半还是网络配置的问题。
> 
> 我先关了，如果还有问题请继续贴，谢谢🙏

Network里接口都是正常的 charles抓包时本地会开启一个代理 为什么使用客户端正常呢 客户端有做过什么处理吗

**Comment by 88250** [comment]
客户端一般用的是 127.0.0.1，路利器端的话是当前 IP 地址。

**Comment by TtBJSH** [comment]
> 客户端一般用的是 127.0.0.1，路利器端的话是当前 IP 地址。

这样的话能不能双开客户端 我指定新开的客户端用户数据指定在另一个文件夹也不行（思源笔记.exe --remote-debugging-port=9527 --user-data-dir="D:\newsiyuan\AutomationProfile"） ，我这种使用场景有什么办法可以解决吗

**Comment by 88250** [comment]
你打开了 网络伺服 功能了吗？打开的话客户端和浏览器可以同时使用的。

**Comment by TtBJSH** [comment]
> 你打开了网络支持功能了吗？打开的通话客户端和浏览器可以同时使用的。

我在浏览器上访问的地址是部署在docker里的，客户端是部署在nas上面的，我的使用场景是要在同台设备上访问两个思源服务事务，但现在的问题是启动打包工具之后只有客户端能正常使用，web端就不能正常使用

**Comment by TtBJSH** [comment]
> 你打开了网络支持功能了吗？打开的通话客户端和浏览器可以同时使用的。

我在浏览器上访问的地服务是部署在docker里的，客户端同步的云同步数据和地址是部署在nas上面的，我的使用场景是要在同台设备上访问两个思源服务，但现在的问题是启动抓包工具之后只有客户端能够正常使用，web端无法正常使用

**Comment by 88250** [comment]
估计只能你自己排查一下了……

**Comment by 88250** [comment]
对了，留意一下 WebSocket 相关的网络配置，可能是这个影响的。

**Comment by TtBJSH** [comment]
> 对了，留意一下 WebSocket 相关的网络配置，可能是这个影响的。

好的，感谢您的回复
