### ISSUE TITLE
嵌入B站视频的页面在打开时自动播放？

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#8585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，当点击打开一个嵌入有b站网络视频的页面时，视频总是会自动播放，通过查找设置没有找到关闭的按钮

### Expected result

第一种：默认设置打开页面，视频不会自动播放。
第二种：在设置中有修改是否自动播放视频的开关。

### Version environment

```markdown
- Version: 2.9.1
- Operating System: window
- Browser (if used):docker部署，edge浏览器访问
```

### Log file

无

**Comment by 88250** [comment]
可能需要检查一下浏览器的配置，默认是不会自动播放的。
