### ISSUE TITLE
打不开“SiYuan”，因为 Apple 无法检查其是否包含恶意软件

### ISSUE THREAD

**Issue by RogerHuHu** [siyuan-note/siyuan#8586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Macbook Pro Intel版，通过github上的镜像升级到 2.9.2后，提示见截图，在系统偏好设置->安全性与隐私中未出现相应的打开选项

### Expected result

能正常使用

### Screenshot or screen recording presentation

<img width="420" alt="image" src="https://github.com/siyuan-note/siyuan/assets/3404169/992339a0-4e18-41fc-a6e2-11d7d46a28f4">

### Version environment

```markdown
- Version: 2.9.2
- Operating System: MacOS 10.14.6
- Browser (if used): Edge
```

### Log file

no

**Comment by 88250** [comment]
感谢反馈，稍后修复。
