### ISSUE TITLE
Can the sync be stopped if the cloud is not compatible

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#8588]
### In what scenarios do you need this feature?

I have been using Siyuan Notes for a long time, but I have encountered problems with synchronization many times. This time I updated to 2.9.2 and there is also an error. 
When the sync data in the cloud is not compatible with the local version, stop directly, and then prompt that it is not compatible. Why do you have to forcefully destroy the cloud data every time?
Every time the cloud data is damaged, it must be backed up, cleared and re-synchronized. The experience is really bad

### Describe the optimal solution

Do a compatibility check when synchronizing data, such as the version. When the cloud synchronization data is incompatible with the local version, stop directly, instead of forcibly uploading and damaging the cloud data.

**Comment by 88250** [comment]
We are very sorry for this, and we will continue to improve in the future, thank you for your feedback.
