### ISSUE TITLE
右键菜单加入"全局搜索关键词""为关键词匹配块引"功能

### ISSUE THREAD

**Issue by EndlessErrors** [siyuan-note/siyuan#859]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

1.希望能直接选中一段文本，右键全局搜索。
2.临时想为某个关键词添加链接时，希望可以用匹配块引功能补充链接。

### 描述最优的解决方案 Describe the optimal solution

如图：
匹配块引时在右键菜单旁边显示搜索结果，并且可以修改搜索的关键词以更准确地匹配。
![图片](https://user-images.githubusercontent.com/57283205/103204949-674a1480-4933-11eb-88ab-e4492b53a717.png)

### 描述候选解决方案 Describe the candidate solution

匹配块引也可以单独开一个窗口，类似全局搜索那样

### 其他信息 Other information

无

**Comment by 88250** [comment]
你好，已有计划请关注 https://github.com/siyuan-note/siyuan/issues/747
