### ISSUE TITLE
Support FSRS Optimizer

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#8594]
### In what scenarios do you need this feature?

叶神在QQ频道说RemNote支持FSRS Optimizer，并且建议思源也跟进。好像是用来设置闪卡复习参数的，不是很懂，可以请叶神解释一下。 @L-M-Sherlock 

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/33930736/950a606a-7162-4192-83d3-711c4c3d6cc9)

**Comment by L-M-Sherlock** [comment]
只要支持复习数据导出，和 FSRS 参数设置即可。优化器这边我可以做。

**Comment by L-M-Sherlock** [comment]
导出一个 csv，有以下 4 列数据即可：
card_id, revlog_id, rating, datetime

**Comment by luo-chuan** [comment]
@88250 呼叫D大

**Comment by 88250** [comment]
@L-M-Sherlock 方便简要介绍一下这个优化器的作用吗？另外，现在思源没有存储复习数据，所以一些统计功能也没法实现 :joy:

**Comment by L-M-Sherlock** [comment]
> 方便简要介绍一下这个优化器的作用吗？另外，现在思源没有存储复习数据，所以一些统计功能也没法实现 😂

就是可以从用户的复习记录里面训练一组记忆模型的参数，可以让算法更准确。

**Comment by 88250** [comment]
@L-M-Sherlock 结果后续是用于初始化 fsrs 参数的吧：

```go
type Parameters struct {
	RequestRetention float64
	MaximumInterval  float64
	EasyBonus        float64
	HardFactor       float64
	W                weights
}
```

看来我们得先把 review log 持久化一下，持久化该数据结构有什么建议吗，或者说有什么需要注意的地方，我问题有点多，麻烦不吝赐教，多谢。

**Comment by L-M-Sherlock** [comment]
Anki的复习记录是存在sqlite里

**Comment by 88250** [comment]
@L-M-Sherlock 我大概了解了，谢谢。

**Comment by luo-chuan** [comment]
关联： https://ld246.com/article/1688456801826

**Comment by qiuqiao** [comment]
持久化复习数据之后，一些统计功能（如正答率）也可以做出来了

**Comment by 88250** [comment]
@L-M-Sherlock v2.9.8 会持久化闪卡复习数据了 #8833 接下来需要麻烦你抽空实现一下 golang 的优化器，谢谢！

**Comment by L-M-Sherlock** [comment]
好的，我最近正在将 FSRS 的所有语言实现升级到 v4 版本，可能得等几天开始做优化器。另外这个优化器必须做成本地版本吗？涉及机器学习的包可能会很大，编译完都有两百多MB。

**Comment by 88250** [comment]
@L-M-Sherlock 原来如此复杂啊，这样的话先缓缓，对了，其他笔记软件接入 fsrs 的优化器是如何给用户使用的呢，是否存在一个开箱即用的办法，比如思源导出你前面提到的 csv，然后用户用这个 csv 导入到某个服务中后输出优化参数？

**Comment by L-M-Sherlock** [comment]
拿 RemNote 举例，用户可以将自己的复习记录以 CSV 格式导出，差不多像这样：

![image](https://github.com/siyuan-note/siyuan/assets/32575846/78adda5f-fc6b-49ac-9ad7-c711b8a1fbec)

然后用户可以在 Google Colab 上打开我写好的优化器 NoteBook:

https://github.com/open-spaced-repetition/fsrs4remnote/blob/main/optimizer.ipynb

上传 CSV 文件，运行所有代码，即可得到优化后的参数。

**Comment by 88250** [comment]
明白了，这样吧，我们把导出 csv 也交给社区开发吧，本体功能仅解决之前提到的复习日志持久化。

**Comment by L-M-Sherlock** [comment]
补充一下，如果社区后续要做复习数据导出，可以参考一下这个库中的数据标准：https://github.com/open-spaced-repetition/fsrs-optimizer

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/9309
