### ISSUE TITLE
2.92 docker 反向代理之后pdf.js路径问题导致进步了笔记系统, 无法使用

### ISSUE THREAD

**Issue by xibaoning** [siyuan-note/siyuan#8595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

F12发现: http://www.xxxxxx.com:6806/stage/protyle/js/pdf/pdf.js?v=1.6.3
正常应该是 http://www.xxxxxx.com:1002/stage/protyle/js/pdf/pdf.js?v=1.6.3
其他文件正常, pdf.js的端口并没有识别到正确的端口1002

### Expected result

问题严重, 不能使用,完全进不了系统

### Version environment

```markdown
- Version: 2.9.2
- Operating System: docker desktop
- Browser (if used):edge
```

### Log file

none

**Comment by xibaoning** [comment]
version: '3.6'

services:
  note:
    image: b3log/siyuan
    container_name: note
    restart: always

    environment:
      - TZ=Asia/Shanghai

    command: [--ssl=true]
    volumes:

      - data:/home/siyuan
    networks:
      - mynas_network  

volumes:
  data: 
  
networks:
  mynas_network:
    external: true
	
	
	
server {
   	listen        1002  ssl;
   	server_name     siyuan;
	
	client_max_body_size 10240m;
	
	ssl_certificate  /etc/nginx/cert/1_www.xxxxxxx.com_bundle.crt; 
	ssl_certificate_key /etc/nginx/cert/2_www.xxxxxxx.com.key; 
	ssl_session_timeout 5m;
	ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
	
	gzip on;
	gzip_min_length 10k;
	gzip_buffers 4 16k;
	gzip_http_version 1.1;
	gzip_comp_level 6;
	gzip_types text/plain application/x-javascript text/css application/xml text/javascript application/x-httpd-php application/javascript application/json;
	gzip_disable "MSIE [1-6]\.";
	gzip_vary on;
	

     location /ws {
              proxy_pass http://siyuan:6806; 
              proxy_read_timeout 60s;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'Upgrade';
           }  
		   
	location / {
		add_header Access-Control-Allow-Origin *;
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_pass http://note:6806;
		
	}
	
}


说明: 之前使用正常, 今天只更新了镜像出现的问题, 可能与代理配置无关

**Comment by 88250** [comment]
域名是如何映射到反代服务器的，是不是用了请求转发？如果用了请求转发的话可能会有问题，建议直接将 serve_name 配置为域名。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by xibaoning** [comment]
docker容器名称可以互通的,    而且之前的版本很正常, 是昨晚更新了才出现, 其他什么也没动,  现象很明显,  其他文件请求正常, pdf.js 端口没被匹配正确, 记得之前有版本也出现过类似的问题, 后来修复, 现在又出现了

**Comment by 88250** [comment]
这部分代码最近都没有变动过，建议检查一下配置看看。

**Comment by xibaoning** [comment]
怀疑的地方:&nbsp;&nbsp;
docker compose yaml:&nbsp;command: [--ssl=true]
浏览器F12调试:
n.SIYUAN_APPID = Math.random().toString(36).substring(8),
n._SIYUAN_ADDRESS = (window.location.hostname || "127.0.0.1") + ":6806",

n.SERVER_ADDRESS = (n._SSL ? "https" : "http") + "://" + n._SIYUAN_ADDRESS,&nbsp; &nbsp;//这里的_SSL为false
n.PROTYLE_CDN = (n._SSL ? "https" : "http") + "://" + n._SIYUAN_ADDRESS + "/stage/protyle",





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月23日(星期五) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] 2.92 docker 反向代理之后pdf.js路径问题导致进步了笔记系统, 无法使用 (Issue #8595)





 
这部分代码最近都没有变动过，建议检查一下配置看看。

**Comment by xibaoning** [comment]
搜索到: https://github.com/siyuan-note/siyuan/issues/4459  
修改后的yml: command: [--ssl=true,--servePath=www.xxxxx.com:1002]  现在能正常访问了, 
但好像记得已经取消了servePath参数

**Comment by xibaoning** [comment]
以上测试不准确, 使用了强制刷新然后就正常了, 以为是servePath参数的原因,
取消servePath后强制刷新就能正常访问,  但右键清除缓存或F5刷新仍然有问题, 
后来发现: 浏览器/应用程序/存储/清除网站数据  之后就彻底正常

**Comment by xibaoning** [comment]
什么也没动, 升级到最新版又出现上面的问题了,而且无法解决

**Comment by xibaoning** [comment]
什么也不动, 降级到v2.11.1就正常了
