### ISSUE TITLE
段落shift+enter换行后，有时不会保存。

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#860]
### 截屏或录屏演示 Screenshot or screen recording presentation

![SS](https://user-images.githubusercontent.com/69628966/103206298-826a5380-4936-11eb-98ab-b3d50350a56d.gif)

### 版本环境 Version environment

* 版本 Version：0.5.45
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
请看下日志是否有报错，谢谢。

**Comment by 88250** [comment]
你好，v0.5.46 中进行了一些修复，我先关闭了，如果还有问题请继续跟帖，谢谢。
