### ISSUE TITLE
列表下创建代码块后不能正常跳出作用域

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#8600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

请结合上传的[动态截图](https://github.com/wkmyws/forPublicIssue/blob/main/bug/siyuyanNote20230623.gif)查看，

当输入列表+代码块后，例如：

1. test
    ``` 
    test I(I是鼠标光标所在处)
    ```
此时按下键盘的↓，预期的结果是：

1. test
    ``` 
    test
    ```
    I(I是鼠标光标所在处)

预期光标可以跳出代码块，而仍然在列表的范围内，

此时按下回车可以创建列表第二项，再次按下回车跳出列表的范围

**但是**查看截图，我做了两次这样的操作，

1. 第一次：
    我从新建文档开始，依次输入标题，列表，代码块，按下↓时，直接跳出了整个列表
2. 第二次
    然后紧接着，我把内容删除，再次重复上述步骤，当按下↓时，光标又符合预期地跳出了代码块，没有跳出整个列表

### Expected result

预期两次操作的结果都是按下↓时，只跳出代码块（最近的一个作用域），而非跳出 代码块 和 列表 两个作用域

### Screenshot or screen recording presentation

[bug复现动图](https://github.com/wkmyws/forPublicIssue/blob/main/bug/siyuyanNote20230623.gif)

### Version environment

```markdown
- Version: v2.9.2
- Operating System: win11
- Browser (if used):
```

### Log file

这个应该没有log记录，毕竟只是编辑文本

**Comment by Vanessa219** [comment]
无法重现，问一下代码块你是怎么输入的？我没有看到你输入三个 `
还麻烦看看是哪里操作不对么？

https://github.com/siyuan-note/siyuan/assets/970828/02a6e133-9bc1-4f99-bcd5-5a8495fe8e01

**Comment by wkmyws** [comment]
代码块我是通过快捷键按出来的，不过这个不影响，

为了保持一致，我重新录制了一段按```出代码块的视频，视频右上方带有实时的键盘按键信息

[点击这里查看，把reproduce.mp4这个文件下载下来观看](https://github.com/wkmyws/forPublicIssue/blob/main/bug/reproduce.mp4)

我测试了下win的客户端和docker部署的网页端，按这个流程都可以复现

您复现时最好和我保持，从**新建文档**开始，依次输入**标题**，正文的**列表**、**代码块**

**Comment by Vanessa219** [comment]
看了下，这是因为在标题处回车会导致有2个空块。按下键的时候如果下方有块就不会创建，而是光标跳到下一个块去。如果没有的话才会创建新块。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
