### ISSUE TITLE
锚点跳转

### ISSUE THREAD

**Issue by wkmyws** [siyuan-note/siyuan#8601]
### In what scenarios do you need this feature?

链接可以跳转到当前页面的锚点，例如：

----------------------

[goto anchor1（因为锚点就在下行，所以看上去没有跳转）](#anchor1)
### anchor1
-----------------------
完整的例子详见：

https://github.com/wkmyws/forPublicIssue/blob/main/improve/anchor.md

### Describe the optimal solution

这个就是markdown的语法吧，github就支持

+ \[xxx\]\(url\)  跳转到url

+ \[xxx\]\(#title\)  跳转到页内title(不管是几级的title，前面都是一个#)

**Comment by 88250** [comment]
抱歉，这个无法支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月23日(周五) 下午4:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 锚点跳转 (Issue #8601)




 
In what scenarios do you need this feature?
 
链接可以跳转到当前页面的锚点，例如：
 
 
goto anchor1（因为锚点就在下行，所以看上去没有跳转）
 
anchor1
 
 
完整的例子详见：
 
https://github.com/wkmyws/forPublicIssue/blob/main/improve/anchor.md
 
Describe the optimal solution
 
这个就是markdown的语法吧，github就支持
  
 
[xxx](url)  跳转到url
 
 
 
[xxx](#title)  跳转到页内title(不管是几级的title，前面都是一个#)
 
  
Describe the candidate solution
 
No response
 
Other information
 
No response
