### ISSUE TITLE
将 移动 赋予快捷键后，在编辑页面按快捷键可以弹出页面，但是不能移动成功

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/87182333/c404a84d-d639-4d63-8c19-bfa192f8f794)
上图我赋予了`移动`按钮快捷键为Alt+T
但是
![image](https://github.com/siyuan-note/siyuan/assets/87182333/63e49989-2cd5-4585-8ba1-069e4916bc68)

### Expected result

希望可以使用快捷键对文档进行移动

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/87182333/4c2c7735-0ad8-481e-ad1c-6176a3919288

### Version environment

```markdown
- Version: v2.9.2
- Operating System: win
- Browser (if used):
```

### Log file

应该不需要

**Comment by Vanessa219** [comment]
这个如果光标在块上的话是移动块，移动块的话点击笔记本是无法移动的，需要点击文档。然后会把当前块移动到所选文档后。

如果需要移动文档的话，光标需要在标题位置。

**Comment by Aiviokoo** [comment]
> 这个如果光标在块上的话是移动块，移动块的话点击笔记本是无法移动的，需要点击文档。然后会把当前块移动到所选文档后。
> 
> 如果需要移动文档的话，光标需要在标题位置。

好吧，谢谢V姐解答。还是有些想这样直接就可以移动文档（算了，我多点几下或再改改习惯好了，哈哈，谢谢）
