### ISSUE TITLE
提供多选块后转换为引述的快捷键

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8610]
### In what scenarios do you need this feature?

目前要把多个块合并进一个引述块必须经过：多选-右键-转换为-引述，共四步操作，比较繁琐。

### Describe the optimal solution

希望能支持自定义转换为引述快捷键。

### Other information

![缺少多选后转换为引述的快捷键](https://github.com/siyuan-note/siyuan/assets/57566668/0a560cf9-ae74-4701-a44b-638128fc7221)

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。
