### ISSUE TITLE
Importing markdown files that include `<kbd>A</kbd>` freezes SiYuan

### ISSUE THREAD

**Issue by nhan000** [siyuan-note/siyuan#8611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The following markdown file only has `<kbd>Win</kbd>` in its content and it can't be imported.

[Can't be imported.md](https://github.com/siyuan-note/siyuan/files/11858261/Can.t.be.imported.md)

### Expected result

Should be able to imported as other markdown files.

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/85216095/19a2b35e-2f89-4706-a83f-8206201ac711)

### Version environment

```markdown
- Version: https://github.com/siyuan-note/siyuan/tree/v2.9.3-dev3 v202306242136
- Operating System: Windows 11, updated.
- Browser (if used): None
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11858263/siyuan.log)

### More information

I think it'd be nice if the import feature let users know what the offending file that interfered with the import is. I had to bisect hundreds of my files to narrow down to what caused the problem. Please consider this as an enhancement.

**Comment by 88250** [comment]
We will fix it later, thank you for taking the time to help locate the bug, and we will report similar errors in the user interface and kernel logs later.
