### ISSUE TITLE
docker版本无法启动

### ISSUE THREAD

**Issue by liyepan** [siyuan-note/siyuan#8612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker run -v /siyuan/workspace:/siyuan/workspace -p 6806:6806 -u 1000:1000 b3log/siyuan --workspace=/siyuan/workspace/

E 2023/06/25 12:11:12 working.go:240: create os tmp dir [/siyuan/workspace/temp/os] failed: mkdir /siyuan/workspace/temp: permission denied

### Expected result

no

### Version environment

```markdown
- Version: 2.9.2 /latest
- Operating System: centos 7
- Browser (if used): firefox
```

### Log file

no log

**Comment by 88250** [comment]
权限不正确，建议按照 README 中的部署步骤操作。
