### ISSUE TITLE
Hiding the dock fails when there is a dock plugin

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#8614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

点击左下角的 `隐藏停靠栏` 按钮隐藏侧边栏后, 重新加载窗口时停靠栏会再次显示  
After clicking the `Hide Dock` button in the lower left corner to hide the sidebar, the dock will be displayed again when the window is reloaded.

### Expected result

记住停靠栏的状态  
Remember the state of the dock

### Version environment

```markdown
- Version: 2.9.3-dev4
- Operating System: windows 11
- Browser (if used): none
```

### Log file

无有效信息输出  
No valid information output

**Comment by 88250** [comment]
我这里无法重现。

布局是在退出或者系统切换窗口后获得焦点时才保存，如果没有这些条件触发，调整布局后直接重载窗口是不会保存布局的。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Zuoqiu-Yingyi** [comment]
@88250 我定位到具体的问题了, 如果插件(例如插件示例)添加了 dock 面板, 那么该面板所在的侧边栏就无法在重新加载后隐藏, 如下所示

![思源笔记-bug反馈-49](https://github.com/siyuan-note/siyuan/assets/49649786/5051494a-efb1-41a8-9a8a-96d2a0546c76)
