### ISSUE TITLE
能否在闪卡中加入文档树功能

### ISSUE THREAD

**Issue by zero150717** [siyuan-note/siyuan#8615]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/74139709/f941ba5a-2a1d-4aab-bde0-dbe7e9da787e)
能否加入可拖动的文档树，单独的闪卡很难将卡片联系到一起
类似sm18这样：
![image](https://github.com/siyuan-note/siyuan/assets/74139709/142847d0-1e8e-4723-84eb-68d749ac457b)

### Describe the optimal solution

参考sm18

**Comment by 88250** [comment]
建议使用快速制卡，本身就是在文档树上了。

**Comment by zero150717** [comment]
> 建议使用快速制卡，本身就是在文档树上了。

我的意思是，能否在闪卡的页面，像sm18一样将文档树显示出来，方便对闪卡内容的联系

**Comment by 88250** [comment]
不考虑了，谢谢。
