### ISSUE TITLE
Add `open-menu-xxx` event bus for plugins

### ISSUE THREAD

**Issue by leolee9086** [siyuan-note/siyuan#8617]
### In what scenarios do you need this feature?

为了实现向链接、图片等行内元素右键菜单添加自定义项，需要能够捕捉这些元素的右键点击事件。

在实现单个图片上传图床、设置文档内某图片为文档头图、复制链接为链接卡片等等操作时可能需要。

### Describe the optimal solution

与现在的click-editorcontent等事件类型一致即可，例如contextmenu-editorcontent，在事件的detail中应该能够获取触发事件的元素和对应的自定义菜单对象

**Comment by Vanessa219** [comment]
"open-menu-blockref" | "open-menu-fileannotationref" | "open-menu-tag" | "open-menu-link" | "open-menu-image" | "open-menu-av" | "open-menu-content"

**Comment by leolee9086** [comment]
好耶  感谢V姐
