### ISSUE TITLE
请求官方增添加密块功能替代原先的sy-secret-block挂件

### ISSUE THREAD

**Issue by HowardMei** [siyuan-note/siyuan#8618]
### In what scenarios do you need this feature?

在写服务器或软件配置文档的时候，随手嵌入账号密码，最方便复现或问题查找，但是从安全角度，肯定要块加密一下，
原本用sy-secret-block挂件觉得挺方便，但从synote更新到v2.9.2之后，这个挂件从集市里面消失了。
看原作者也好久没更新过了：https://github.com/dicarne/sy-secret-block

### Describe the optimal solution

从安全角度，采用挂件或者插件都不是最佳选择，最好官方下次升级的时候能内置加密块功能，解决一下燃眉之急。

**Comment by HowardMei** [comment]
如果不愿新增功能开发，能否直接将这个挂件吸收到官方功能里，确保以后安全可用？已经用它加密了蛮多文本块了，真心不希望自己另搞个碎片版本。

**Comment by 88250** [comment]
这个不考虑了，感谢提议。



---原始邮件---
发件人: "Howard ***@***.***&gt;
发送时间: 2023年6月26日(周一) 凌晨1:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 请求官方增添加密块功能替代原先的sy-secret-block挂件 (Issue #8618)




 
In what scenarios do you need this feature?
 
在写服务器或软件配置文档的时候，随手嵌入账号密码，最方便复现或问题查找，但是从安全角度，肯定要块加密一下，
 原本用sy-secret-block挂件觉得挺方便，但从synote更新到v2.9.2之后，这个挂件从集市里面消失了。
 看原作者也好久没更新过了：https://github.com/dicarne/sy-secret-block
 
Describe the optimal solution
 
从安全角度，采用挂件或者插件都不是最佳选择，最好官方下次升级的时候能内置加密块功能，解决一下燃眉之急。
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by kx1356** [comment]
既然挂件都能实现的功能，D大为何不搞，不明白。这也算是一项杀手级的功能。
