### ISSUE TITLE
Question: Does SiYuan use internet

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Hello team,
Just wanted to know if SiYuan works fully offline or does it use internet to send any analytics/telemetry data.

If needed: I am not using any sync and all the notes are on local only.

### Version environment

```markdown
Latest
```

### Log file

[EmptyFile.txt](https://github.com/siyuan-note/siyuan/files/11867485/EmptyFile.txt)

**Comment by 88250** [comment]
Hello, SiYuan can be used completely offline, but please note that "offline" here refers to leaving the Internet, not disabling the network card, because the SiYuan kernel is essentially a server program that requires a network card to work normally.
