### ISSUE TITLE
Improve breadcrumb on the mobile

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

移动端聚焦后面包屑右侧没有退出聚焦选项

### Expected result

加上退出聚焦按钮

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/99a02b87-a58c-43dd-94f2-6a97545a3fe0

### Version environment

```markdown
- Version: 2.9.2
- Operating System: iOS
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
这是设计如此，移动端面包屑放不下，所以不显示 `退出聚焦`，感谢反馈。

**Comment by gdy106** [comment]
> 这是设计如此，移动端面包屑放不下，所以不显示 `退出聚焦`，感谢反馈。

我认为退出聚焦是有必要的，当上级标题和我聚焦的块距离很远时，如果没有退出聚焦选项会很难操作。反而是菜单栏里聚焦和返回上层聚焦的选项很多余，已经有面包屑了还要放俩选项在那么靠前的位置占地方。
![image](https://github.com/siyuan-note/siyuan/assets/57566668/13ad3a74-b481-4b8d-acfa-1f6ad3005c74)
有电脑端的操作逻辑在，即使只留一个“退”字或“×”符号的小选项也可以，我认为退出聚焦这个功能是刚需。
如果考虑空间利用问题，我倒是很奇怪为什么这个利用率超级低的文档菜单选项要放在本来就非常拥挤的键盘菜单栏上，尤其是在面包屑右上角本来就有这个按钮的情况下。
![PF`FK_J`AC45@_(N564X@0P](https://github.com/siyuan-note/siyuan/assets/57566668/2ceba0d9-782c-4609-a7e3-968b851492d8)

**Comment by Vanessa219** [comment]
底部需要键盘弹起才能点击，而右上角不需要。退出聚焦可以直接点击面包屑的第一个文档按钮。

**Comment by gdy106** [comment]
> 底部需要键盘弹起才能点击，而右上角不需要。退出聚焦可以直接点击面包屑的第一个文档按钮。

右上角的文档菜单按钮已经有了，为什么要在键盘菜单上再加一个文档菜单按钮？我认为累赘。
点击文档按钮就回到文档顶部了，在打开大文档的场景完全是灾难操作，点击上级面包屑同理，当我操作的块距离上级（标题或列表）很远的情况时，这两个操作都会造成麻烦。
我认为退出聚焦按钮是有必要的，如果考虑屏幕占用的问题，可以把面包屑做成可滑动的，就和键盘菜单栏那样。

**Comment by Vanessa219** [comment]
底部按钮有光标的情况下插入文档会插入到光标所在位置。

至于退出聚焦使用面包圈的文档图标和大文档应该没有关系，还麻烦详细演示及说明一下具体需求，谢谢。

**Comment by gdy106** [comment]
> 底部按钮有光标的情况下插入文档会插入到光标所在位置。
> 
> 至于退出聚焦使用面包圈的文档图标和大文档应该没有关系，还麻烦详细演示及说明一下具体需求，谢谢。

因为电脑端的文档菜单按钮只有右上角的一个，所以我觉得手机端也可以只有一个，提议删掉键盘菜单上的文档菜单按钮是因为键盘菜单已经非常拥挤了。
点击面包屑左边的文档图标的退出聚焦，是回到文档开头，而不是正常退出聚焦应该有的上下文，当我浏览在第1000个标题下的第20段正文时，我想要看到上下文，这时我没法直接退出聚焦看到第19段或者第21段，这就是我说的问题所在。
我个人认为移动端不至于挤不出来一个退出聚焦的按钮，但是如果你们认为按钮不可以增加，那可不可以设置成点击一次面包屑左侧文档图标是退出聚焦，双击文档图标是回到顶部？（或者聚焦状态图标显示为×，点击退出聚焦；非聚焦状态显示为文档标志，点击回到文档顶部。）这样就不需要增加按钮了。
![image](https://github.com/siyuan-note/siyuan/assets/57566668/f86420e9-2bca-4002-adb3-26a2cb78c8f9)

**Comment by Vanessa219** [comment]
哦，这个使用场景确实是有问题，后续改进。感谢你耐心的反馈。
