### ISSUE TITLE
Improve search default sort

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

之前在https://ld246.com/article/1687574578775这个帖子借楼反馈过这个问题，但我后来再测试的时候没有复现，现在发现问题所在：我第一次录屏的时候测试的文件是加粗的关键词放在开头了，如图：
![image](https://github.com/siyuan-note/siyuan/assets/57566668/4cc3e7d7-2a50-4004-b13b-8287fd6b7791)
我今天调整了测试文档的内容，在加粗的关键词前面加上了没有行级样式的正文，复现了搜索和引用中带有行级样式文字的检索结果被置底的bug。
![image](https://github.com/siyuan-note/siyuan/assets/57566668/a2f26b8e-043c-4687-b2fc-a10ebd278b7a)

![image](https://github.com/siyuan-note/siyuan/assets/57566668/23d5588c-cedd-4603-a732-7d24a43bbbb7)
![image](https://github.com/siyuan-note/siyuan/assets/57566668/7c3ee7ec-5fe9-4176-8130-4e5f4813c4ae)

### Expected result

检索结果按照正常顺序显示

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/d84b6f0f-15f6-4d37-a420-7b09b2d9a9a2

### Version environment

```markdown
- Version: 2.9.2
- Operating System:win10 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11870765/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，这和加粗等行级元素没有关系的，搜索时不指定排序规则的话是按 `sort` 字段排序，也就是块类型，如果块类型都一样，比如都是段落块的话会按照 SQLite FTS5 内建的排序算法，这个排序算法我没有仔细研究，观察了下大概是最新更新的数据会被放在最后。

下个版本我们稍微调整一下，在不指定排序的情况下默认使用 `sort` 升序和 `updated` 降序，这样就能在同类型时稳定得到按更新时间降序的结果了。
