### ISSUE TITLE
优化iPad使用体验

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#8627]
### In what scenarios do you need this feature?

在iPad上使用siyuan的体验简直不能再糟糕，能不能把基础的东西做好再做其他的
1.切换app后，内核立刻中断
2.编辑时会跳转
3.无法实现右键功能
4.按钮太小
5.其他

### Describe the optimal solution

。

**Comment by 88250** [comment]
抱歉，暂时没有精力优化 iPad 端，请关注 https://github.com/siyuan-note/siyuan/issues/4238

**Comment by KuiyueRO** [comment]
对于1，可以用侧拉将它挂在后台

对于2，不清楚跳转是什么意思

对于3，如果你有键盘和触控板的话，打开双指辅助点按，双指按下触控板即可显示右键菜单
