### ISSUE TITLE
希望移动端能支持拖拽列表项调整顺序

### ISSUE THREAD

**Issue by choora** [siyuan-note/siyuan#8628]
### In what scenarios do you need this feature?

尝试用思源笔记记录每日待办，条目多且短，目前不支持拖拽调调整列表顺序，只能剪贴、粘贴来编辑列表，很不方便。

### Describe the optimal solution

希望能实现长按列表项、上下拖拽，调整顺序。

**Comment by 88250** [comment]
移动端暂时不会有大的变更了，以后如果有精力再考虑，谢谢。
