### ISSUE TITLE
like image, video can have an title

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8629]
### In what scenarios do you need this feature?

below is set title for image, video need a title, too
![image](https://github.com/siyuan-note/siyuan/assets/5683995/ea2959b6-8d06-4fec-95d2-885136e2fff1)

When I refer to a image, the anchor text is the title of the image, if I haven't name it, which is quite natural.
So when refer to a video, I want a similar behavior like refer to a image.

**Comment by mozhux** [comment]
meiyou duiying de yufa , jianyi dui shiping tianjia minging shuxing.

**Comment by 88250** [comment]
Hi, this feature is not considered supported. If it is a reference, you can modify the anchor text, thank you.

**Comment by zhoutaosheng** [comment]
> Hi, this feature is not considered supported. If it is a reference, you can modify the anchor text, thank you.

Not only the reference, the text (set by title) below the image, is also what users what. We want set text to describe the video in brief.
![image](https://github.com/siyuan-note/siyuan/assets/5683995/5ca8d7ee-22a2-431b-b8f1-73bcf26a8a6b)

**Comment by 88250** [comment]
Sorry, there are currently no plans to improve this.

**Comment by zhoutaosheng** [comment]
> Sorry, there are currently no plans to improve this.

Could you consider putting it on the to-do list?
