### ISSUE TITLE
导出pdf时报错

### ISSUE THREAD

**Issue by shuaimeng** [siyuan-note/siyuan#863]
导出pdf时报错
![image](https://user-images.githubusercontent.com/20830351/103247240-30124c80-49a1-11eb-968b-266ff1066703.png)

**Comment by shuaimeng** [comment]
Macbook pro 16寸
big sur 11.1

版本0.5.45 (0.5.45)

**Comment by Vanessa219** [comment]
文件是打开或者被占用了么？
我这里重现不了，麻烦说一下步骤及给一下导出的原文。

**Comment by shuaimeng** [comment]
1、正常输入文档，文档大概就几行文字，有图无图不影响结果；
2、点击导出pdf，点击保存；
3、直接报错，webContents.......
4、导出html无问题
5、使用的是macbook pro 16笔记本，32g，i9；
6、Macos是big sur 11.1
7、其他没有任何操作，不太清楚为啥会出现这种情况

**Comment by shuaimeng** [comment]
![image](https://user-images.githubusercontent.com/20830351/103254825-dc642b00-49c1-11eb-9552-26bb8ddd938d.png)
l另外一个问题是某个主题下，光标会显示在原点左侧，比较奇怪，不影响使用

**Comment by shuaimeng** [comment]
> 文件是打开或者被占用了么？
> 我这里重现不了，麻烦说一下步骤及给一下导出的原文。

我还不清楚win下面是否有这个情况，可能没有

**Comment by Vanessa219** [comment]
是不是安装的时候没有赋予写的权限

**Comment by dsc6636926** [comment]
我导出pdf和html的时候都会报这个错
![image](https://user-images.githubusercontent.com/7552492/103283862-a8febc00-4a14-11eb-896f-32de8282f378.png)

**Comment by dsc6636926** [comment]
> 我导出pdf和html的时候都会报这个错
> ![image](https://user-images.githubusercontent.com/7552492/103283862-a8febc00-4a14-11eb-896f-32de8282f378.png)

![image](https://user-images.githubusercontent.com/7552492/103283923-cd5a9880-4a14-11eb-886d-e382f4e0f6eb.png)
![image](https://user-images.githubusercontent.com/7552492/103283951-dd727800-4a14-11eb-8471-3539a17fcd00.png)

**Comment by 88250** [comment]
@dsc6636926 完全卸载以后重新安装一下。

**Comment by dsc6636926** [comment]
> @dsc6636926 完全卸载以后重新安装一下。

可以啦，谢谢

**Comment by 88250** [comment]
@shuaimeng 你好，我们这里重现不了问题，先关闭了，如果还有反馈请继续跟帖，谢谢。
