### ISSUE TITLE
Unify the rounded corner size of the pop-up layer

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#8631]
https://ld246.com/article/1687941769547

**Comment by mozhux** [comment]
闪卡的重复和管理界面还是有漏网之鱼
![image](https://github.com/siyuan-note/siyuan/assets/46953371/d41759cd-4fb7-439b-9b82-e383969fd137)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/b25089b4-687a-4e28-9d10-1cd939177b1c)

另外就是大圆角导致许多界面的内容过于靠近窗口边缘，比如设置界面的滚动条
![image](https://github.com/siyuan-note/siyuan/assets/46953371/32c1ec9c-1cbb-4606-9949-a46f63c8b905)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/6064c63d-79ff-426d-b69a-399d4f68e934)

标题的添加标签那三个控件
![image](https://github.com/siyuan-note/siyuan/assets/46953371/454d7af6-3245-49d8-ae35-ed8b45841137)
题头图处理后的控件
![image](https://github.com/siyuan-note/siyuan/assets/46953371/918a472b-c818-4fdb-80d8-9d81e7ccb904)
感觉应该都要缩小图标或者放大那个框框

**Comment by Vanessa219** [comment]
多谢，但`缩小图标或者放大那个框框`这个意思是点击区域太小了么？

**Comment by mozhux** [comment]
> 

不是哈，注意看设置界面右上角关闭处，那个滚动条因为上方圆角太大的缘故，显示不是很好看，通顶了。

**Comment by mozhux** [comment]
最后，因为圆角变大，希望增加描边，会更精致点，阴影就小点或不要了？
![image](https://github.com/siyuan-note/siyuan/assets/46953371/6b009d93-ed43-48fa-8fe6-5612cf4f8404)
其他应用案例：
新版qq
![image](https://github.com/siyuan-note/siyuan/assets/46953371/b95e856d-295c-4a84-acbc-a0a10e631206)

微信输入法：
![image](https://github.com/siyuan-note/siyuan/assets/46953371/ef13e60b-15c1-4e38-9f4e-ffb5ac63c1c3)

新版wps
![image](https://github.com/siyuan-note/siyuan/assets/46953371/2993171f-c09e-4168-81ec-825e8b85479a)

**Comment by mozhux** [comment]
最新发现，关系图里的块筛选也是没有圆角。而且还是透明的，关系图性能差的罪魁祸首？
![image](https://github.com/siyuan-note/siyuan/assets/46953371/b8963c8b-5664-4fb7-91eb-58f36da3d6d6)
