### ISSUE TITLE
插入图片提示系统异常

### ISSUE THREAD

**Issue by liluoaikunbang** [siyuan-note/siyuan#8632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

桌面端用粘贴方式插入图片时有大概率提示系统异常，要重建索引或强制退出，而且重建索引后新插入的段落都无法同步。是新版本出现的问题，以前的版本没有出现过。

### Expected result

解决bug

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):--
```

### Log file

无

### More information

-

**Comment by 88250** [comment]
请上传内核日志文件，另外，是否使用了第三方同步方式或者使用了外部工具会读写工作空间文件，比如 utools 等？

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
