### ISSUE TITLE
2.9.3的UI有点粗糙

### ISSUE THREAD

**Issue by Soywei00** [siyuan-note/siyuan#8633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Win的右上角关闭按钮明显没有对齐。

### Expected result

希望尽快调整。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/16738821/7a1ac671-fd7b-4c2f-9769-205fee6cd121)

### Version environment

```markdown
- Version: 2.9.3
- Operating System: Win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11895027/siyuan.log)

**Comment by 88250** [comment]
这个看上去不是默认主题，请给该社区主题反馈，谢谢。
