### ISSUE TITLE
图片复制直接原图大小复制，而不是拉伸大小复制

### ISSUE THREAD

**Issue by roingbu** [siyuan-note/siyuan#8637]
### In what scenarios do you need this feature?

图片复制直接原图大小复制，而不是拉伸大小复制

### Describe the optimal solution

图片复制直接原图大小复制

**Comment by 88250** [comment]
你好，你指的复制是从哪里复制？



---Original---
From: "Roing ***@***.***&gt;
Date: Thu, Jun 29, 2023 11:41 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [siyuan-note/siyuan] Please enter the title of the feature request(Issue #8637)




 
In what scenarios do you need this feature?
 
图片复制直接原图大小复制，而不是拉伸大小复制
 
Describe the optimal solution
 
图片复制直接原图大小复制
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
