### ISSUE TITLE
列表项聚焦后回车应该创建子级节点

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8638]
### In what scenarios do you need this feature?

我发现在思源聚焦列表项后，回车创建的是同级节点而非子级节点，这一点有一点违反直觉。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/2f3b9b01-3162-4d33-9af0-b4d2d2b00fc3)

这不是很要紧的问题，创建同级节点后tab即可，但还是觉得有点别扭，希望能够改进。

另外还希望能够不允许创建同级节点，或者shift+tab创建同级节点后让同级节点消失。

### Describe the optimal solution

列表项聚焦后回车应该创建子级节点

**Comment by Vanessa219** [comment]
这个和聚焦块的交互式一样的，也和非聚焦状态保持一致。如果是创建子级的话就会不太一致，怕其他用户不好理解。

**Comment by zxhd863943427** [comment]
列表项聚焦跟其他类型的块聚焦还是有区别的。

列表项聚焦后，其实大家是把它当成其他大纲笔记中的打开子弹来理解的。而在常规的大纲笔记中，不仅聚焦后会只会自动创建子节点，甚至可能无法创建同级节点。部分支持创建同级节点的也会直接隐藏掉这些新创建的同级节点。

因此我觉得会使用列表项聚焦的这些用户是能直接理解这种区别的，特别是从其他大纲笔记迁移过来的用户。

当然，如果V姐觉得对于列表项特殊处理不太好，那不处理也没啥，毕竟只是顺手与否而已 : )

**Comment by Vanessa219** [comment]
workflowy 好像是这样的，但是他是把列表项做为了标题。在正文的列表处回车还是创建同级列表，这个我们再看看有没有其他用户反馈吧。
