### ISSUE TITLE
思源笔记最新变化窗口显示异常

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#8640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新思源后，弹出的`思源笔记最新变化窗口`显示异常，不能显示完整更新内容

### Expected result

显示正常

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/35998162/27c04457-c47c-46b6-b574-8c9f62c7ce8e

### Version environment

```markdown
- Version: 2.9.3
- Operating System: Windows 10 22h2
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11903581/siyuan.log)

### More information

印象里从好久之前就这样了，就自从更新窗口出来之后就没有正常显示过😂

**Comment by 88250** [comment]
你好，请检查是否是代码片段或者其他扩展影响。
