### ISSUE TITLE
云端同步是全量的吗？希望增量同步

### ISSUE THREAD

**Issue by wq163** [siyuan-note/siyuan#8646]
### In what scenarios do you need this feature?

我用自建的webdav进行同步，现在数据多了之后发现每次同步都要很久，状态栏显示都是几千个数据文件之类的，而我只是修改了笔记的几个字而已。
怀疑每次同步都是全量的，非常影响体验

![image](https://github.com/siyuan-note/siyuan/assets/1230366/65271a26-f440-4285-a916-c68396ead1cb)

### Describe the optimal solution

希望增量同步

**Comment by 88250** [comment]
增量分块同步，看下帮助文档吧。
