### ISSUE TITLE
Please enter the title of theEnhance the effect of text when selected bug report

### ISSUE THREAD

**Issue by wanyunr** [siyuan-note/siyuan#8648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The display effect is particularly inconspicuous after using the left button to select text, resulting in the inability to see that it has been selected.
[See for details](https://ld246.com/article/1688113174691)

### Expected result

The selected word is given a heavier blue, or further the text color is changed to white

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/105478325/8db48770-8787-407b-b379-ae5a4db7d9e2)
---
![image](https://github.com/siyuan-note/siyuan/assets/105478325/65aa17d7-7b4c-487f-b8b0-01b35d2a390e)
---
Ideal results
![image](https://github.com/siyuan-note/siyuan/assets/105478325/19d71124-4f63-4464-a545-f48a1867de97)

### Version environment

```markdown
- Version: v2.9.3
- Operating System: Windows 10
```

### Log file

none

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/b433ff63-8737-4457-9510-2ddd8e3ae266)

Looks good on the default theme.

**Comment by wanyunr** [comment]
> We have changed a little:
> 
> ![image](https://user-images.githubusercontent.com/873584/250087613-8b918a1f-9954-4768-9751-b393d27eaf69.png)

This is the effect selected under my default theme, and it is so weak that it is almost invisible


https://github.com/siyuan-note/siyuan/assets/105478325/63a312ba-db79-4217-a2cd-b73c4044c3c8

**Comment by 88250** [comment]
We have changed a little above.
