### ISSUE TITLE
多级列表shift enter不对齐

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#865]
### 描述问题 Describe the problem

![多级列表不对齐问题](https://user-images.githubusercontent.com/46141646/103251300-593bd880-49b3-11eb-8c82-cbf326695791.gif)

"子列表" shift enter 后的 “这个地方对齐有问题吧”
应该和“子列表”是左对齐的吧

因为“这个地方对齐有问题吧”和“子列表”是同级的概念
缩进应该是一致的
### 期待的结果 Expected result

如我最后用空格手动对齐的一样

### 版本环境 Version environment

* 版本 Version：v0.5.45
* 操作系统 Operating system：win10

**Comment by yeshaopeng6688** [comment]
能分享下字体么 = =。

**Comment by wo4wangle** [comment]
> 能分享下字体么 = =。

就用的思源默认的啊，你和我的不一样吗

**Comment by 88250** [comment]
你好，我这里重现不了……

![issue](https://user-images.githubusercontent.com/873584/103296697-8fb83880-4a31-11eb-9b0f-f524023eb75a.gif)

**Comment by wo4wangle** [comment]
> 你好，我这里重现不了……
> 
> ![issue](https://user-images.githubusercontent.com/873584/103296697-8fb83880-4a31-11eb-9b0f-f524023eb75a.gif)

可能是 Fountain Dark 主题的问题
回到 midnight 恢复正常

**Comment by yeshaopeng6688** [comment]
很可能是主题里的列表添加了 list-style-position: inside;，将列表项标志 放在行内容里，所以看到的不对齐。

**Comment by 88250** [comment]
可以给该主题仓库提 issue :)
