### ISSUE TITLE
unraid商店默认模版安装后数据目录里没有数据

### ISSUE THREAD

**Issue by 929126387** [siyuan-note/siyuan#8655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

unraid商店默认模版安装后数据目录里没有数据，重启后笔记依然在，现在只能通过web导出。
![微信截图_20230702002428](https://github.com/siyuan-note/siyuan/assets/77496052/1d25dd86-29d5-4cd5-ba95-9b980ddfd9cf)
![微信截图_20230702002445](https://github.com/siyuan-note/siyuan/assets/77496052/f2d7cc29-c47b-4ac6-8784-8262fa739447)
![微信截图_20230702002451](https://github.com/siyuan-note/siyuan/assets/77496052/e13479c3-bdcb-4288-8203-4b6f4f40cea8)

### Expected result

1嘎嘎嘎嘎嘎嘎嘎嘎嘎

### Screenshot or screen recording presentation

1嘎嘎嘎嘎嘎嘎嘎嘎嘎

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
1
```

### Log file

1嘎嘎嘎嘎嘎嘎嘎嘎嘎

### More information

1

**Comment by 88250** [comment]
你好，这个模板不是我们制作的，请给相关作者反馈，谢谢。

**Comment by leeima** [comment]
> 你好，这个模板不是我们制作的，请给相关作者反馈，谢谢。

unraid不少再用的，大佬不打算上架个官方模板吗，路径怎么填，文件里都没东西，看了社区也没解决，重装或更新数据就全没

**Comment by 88250** [comment]
抱歉不太清楚如何上架，如果可行的话请 PR 直接贡献，谢谢。

**Comment by leeima** [comment]
> 抱歉不太清楚如何上架，如果可行的话请 PR 直接贡献，谢谢。
好的，我已经解决unraid问题了，我提交一下
