### ISSUE TITLE
指令触发和slash触发的protyle不一致

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在这里，command触发回调函数还是原来的参数，但是slash触发变成了新的，新的参数的protyle里面才是原来的参数。

应该是`ICommandOption.editorCallback`的输入参数也得更新一下

![image](https://github.com/siyuan-note/siyuan/assets/63407442/53788669-bd13-4829-bb70-5ea27632803c)

### Expected result

`ICommandOption.editorCallback` 这里的参数，应该是 `(protyle: Protyle)`，具体调用的地方应该也得改一下

![image](https://github.com/siyuan-note/siyuan/assets/63407442/0846a837-0e8b-4487-b256-ef3f9ca6b336)

### Version environment

```markdown
- Version: v2.9.3
- Operating System: windows
- Browser (if used):
```

### Log file

none

**Comment by Vanessa219** [comment]
这个问题是 Vditor 就遗留下的，上个版本加的 event bus 传入的是 Protyle，因为涉及到 inset、reload 等方法。至于以前的接口不太方便动。其实并不是 Protyle， 而是如下：

```
 editorCallback?: (protyle: Protyle.protyle) => void
```

**Comment by WingDr** [comment]
好的好的，既然不好改就先不用动了，相关的功能都放在slash里也比较统一，我去把这个command删掉
