### ISSUE TITLE
Exporting PDF crashes UI

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8658]
导出大pdf会卡退

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题所述，导出大pdf时会卡退，但检查生成目录，发现pdf已经生成，但未删除资源文件夹和生成pdf内目录

以下是测试文件

[Composing Programs.sy.zip](https://github.com/siyuan-note/siyuan/files/11929267/Composing.Programs.sy.zip)

### Expected result

希望修复这个错误

### Version environment

```markdown
- Version: 2.9.3
- Operating System: win 10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
你试下按下导出确定按钮以后最小化主界面，看看能否正常导出。

**Comment by zxhd863943427** [comment]
抱歉回的有点晚。

经过测试，最小化主界面后可以正常导出。

**Comment by 88250** [comment]
使用的输入法是搜狗拼音吗？打开任务管理器，然后展开前端进程，观察下导出时的 SiYuan 子进程的状态。

**Comment by zxhd863943427** [comment]
使用的是微软自带的输入法，导出时，任务管理器状态见下：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/8080fdbd-c4bd-4205-a94a-79276cc5c9d4)

**Comment by 88250** [comment]
导出确定按下以后把焦点移到其他窗口呢？

**Comment by zxhd863943427** [comment]
同样会闪退

**Comment by 88250** [comment]
好的，暂时无法确定原因，等 Electron 有新版本我们升级下看看。

**Comment by zxhd863943427** [comment]
在siyuan2.9.5dev中，能成功复现导出失败和导出成功。
目前我观察到目前是只要焦点切出思源，并且正在进行导出，就会失败
 只要焦点保持在思源界面内，就能正常导出

**Comment by 88250** [comment]
v2.9.7 升级了 Electron 我这里好像已经不能重现该问题，请帮忙确认。

**Comment by zxhd863943427** [comment]
可以复现。

**Comment by 88250** [comment]
@zxhd863943427 有空的话帮忙试下目前最新的开发版（v2.10.2-dev1），我这里好像正常了。

**Comment by zxhd863943427** [comment]
同样出错，出错的复现步骤：导出PDF后，立刻切换到其他应用。
假如停留在siyuan，则不会出错。

**Comment by zxhd863943427** [comment]
与之前的测试结果是一致的。

**Comment by 88250** [comment]
收到。



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 27, 2023 21:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Exporting PDF crashes UI (Issue #8658)




 
与之前的测试结果是一致的。

**Comment by 88250** [comment]
麻烦使用最新的 dev 版测试看看，升级了 Electron。

**Comment by 88250** [comment]
我这里测试了几次，好像已经无法重现了，老铁再帮忙试试？

**Comment by zxhd863943427** [comment]
目前似乎是正常的
