### ISSUE TITLE
建议支持：页面级别的自适应宽度

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8659]
### In what scenarios do you need this feature?

需要的场景：
通常情况下，很多用户的全局配置，会关闭自适应宽度，一方面，这符合大多数软件的使用习惯，让用户关注中心编辑区域，另一方面，可以在不同的比例的显示器上，有相同的编辑体验
但有些场景，需要自适应宽度
1. 文档中，有比较长的表格，有比较宽的图片时
2. 以后siyuan全面支持数据表格，表格的属性列比较多，用户希望看得更加全一些

另外，在一些其他的笔记软件看到支持了文件级别的自适应宽度，希望思源也有

### Describe the optimal solution

实现也许在块嵌入时，可能有些问题
比如，没有开启自适应宽度的页面，**块嵌入**开启自适应宽度的页面

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/7388
