### ISSUE TITLE
底栏显示当前文档闪卡总数

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8660]
### In what scenarios do you need this feature?

可以增加闪卡功能的体验。

### Describe the optimal solution

希望能添加这项功能。

**Comment by 88250** [comment]
对于不使用闪卡的人来说总是显示 0 不太好，这个应该可以期待插件支持，谢谢。

**Comment by chenshinshi** [comment]
> 对于不使用闪卡的人来说总是显示 0 不太好，这个应该可以期待插件支持，谢谢。

但不是为0的不会显示吗，比如本文的链接和引用如果是0就不会显示在底栏。

**Comment by 88250** [comment]
等考虑下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月3日(周一) 中午1:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 底栏显示当前文档闪卡总数 (Issue #8660)




  
对于不使用闪卡的人来说总是显示 0 不太好，这个应该可以期待插件支持，谢谢。
  
但不是为0的不会显示吗，比如本文的链接和引用如果是0就不会显示在底栏。
