### ISSUE TITLE
Add `open-menu-breadcrumbmore` event bus to plugins

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8666]
### In what scenarios do you need this feature?

想做一个结合citation插件导出LATEX的功能，如果如果这种导出都要交给D大V姐做就太麻烦了。另外Citation插件的文档内更新引用格式的功能也是文档级的功能。

所以希望能够在这里加入一些接口，能够添加一些二级甚至三级菜单（二级菜单是插件列表，每个插件一个三级菜单？不过这样是不是太繁琐了），允许插件进行文档级的操作（只要给文档信息就行）

![image](https://github.com/siyuan-note/siyuan/assets/63407442/65a542c7-36d6-420c-8d0f-47625e774b0c)
![image](https://github.com/siyuan-note/siyuan/assets/63407442/fd743cce-f007-4c20-9ff2-403236565555)

### Describe the optimal solution

可以类似标题块的菜单一样放到eventBus里，但是这个好像本身也有一点小问题，我会单开一个issue说，但是这个形式是非常好的，不会导致api拥挤而且也可以和列表渲染结合（尽量避免对于同种类型的问题加入不同的API）

![image](https://github.com/siyuan-note/siyuan/assets/63407442/fd659f41-9057-4261-b280-74d41e8b4b28)

**Comment by Vanessa219** [comment]
这样是否可以

* 导出
* 插件
  * citation
    * update
    * export 
* 信息

**Comment by WingDr** [comment]
对对，我觉得这样就挺好的，插件本身的功能和地位不和原本你们规划好的功能冲突是最好的
