### ISSUE TITLE
Losing "this" in eventBus triggering

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在点击触发的三个 eventBus 上都试了一下，先打印的是event，然后打印的是this，我不知道这算js的特性还是程序bug，并且没有找到相关的issue，所以我先提一下

![image](https://github.com/siyuan-note/siyuan/assets/63407442/db5c7716-797e-43a4-840b-59310c3c7935)

### Expected result

this应该是指向这个函数所在类的

### Version environment

```markdown
- Version: 2.9.3
- Operating System: windows 
- Browser (if used):
```

### Log file

I 2023/07/03 22:03:14 box.go:79: auto stat [trees=275, blocks=13238, dataSize=210 MB, assetsSize=24 MB]
I 2023/07/03 22:03:14 disk.go:33: disk usage [total=785 GB, used=233 GB, free=552 GB]
I 2023/07/03 22:07:27 repository.go:1182: synced data repo [kernel=xy62sf2, provider=0, ufc=4, dfc=1, ucc=2, dcc=0, ub=163 kB, db=72 kB] in [1.89s]

**Comment by Vanessa219** [comment]
JS 中的 this 在 EventBus 中就是这样的。需要使用 this 可参考 7cfba4ae27fd3bddf82c2d9cc9a512a94c898ae3
