### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by lion-of-lei** [siyuan-note/siyuan#8673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/89855648/2507197a-eb18-4b9a-8653-5ffc53a5b87a

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):2.94
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11944265/siyuan.log)

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/99dcbbaa-7d53-4af4-a231-c6809b87a149)
