### ISSUE TITLE
是否可以在大纲点击跳转时，考虑到插件导致的编辑器上方高度变化？

### ISSUE THREAD

**Issue by OpaqueGlass** [siyuan-note/siyuan#8674]
### In what scenarios do you need this feature?

在文档面包屑插件中，在块面包屑之上插入了文档面包屑，这导致编辑区域距离窗口顶部距离增大；这时点击大纲跳转，将会导致跳转到的标题文字被遮挡（似乎还是个概率问题，不太明白原因）；

![跳转？](https://github.com/siyuan-note/siyuan/assets/52985952/5d56a607-c21b-4656-8b11-ba18ac417420)

### Describe the optimal solution

是否可以在大纲跳转时检查编辑区上方的实际高度再进行跳转？（考虑到面包屑等位置可能的高度变化）
如果已经考虑了，可以的话麻烦指路一下实现代码具体在哪儿（我没找到@_@）；

或者麻烦给一些修改插件的建议。谢谢。

**Comment by Vanessa219** [comment]
这里是写死的，你插入的 Dom 及其位置是什么样的？我这里重新计算一下吧。
