### ISSUE TITLE
Can't install the .apk

### ISSUE THREAD

**Issue by Silverhawk85** [siyuan-note/siyuan#8677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I can't install the .apk on my device (Samsung Galaxy A6+, Android 10).
I already checked that installing Apps from unkown sources is allowed and that I have enough space on my device, but it always refuses to intall the app (App not installed).

### Expected result

Installation of the apk

### Version environment

```markdown
- Version: 10
- Operating System: Android
- Browser (if used):
```

### Log file

no log availlable

**Comment by 88250** [comment]
Sorry, we can't locate the problem according to the current information, please try to install it from the app store to see if you can get some other information.

The issue is closed first, if you have further information, please feel free to post feedback.
