### ISSUE TITLE
引入新的编辑模式 - 专家模式

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#868]
专家模式即源码模式，完全以 .md 源文件文本使用。

**Comment by woniuxia** [comment]
这个好呀~
有时候格式调不好，在专家模式下更容易调整~

**Comment by woobhurk** [comment]
支持一波

**Comment by Andy-AO** [comment]
@88250 不建议思源笔记内搞什么专家模式，只提供比较简陋的查看源代码功能就行了，主要用于临时应急.

重要的是支持与著名的编辑器联动.真正的专家不会在一款笔记软件中编辑MarkDown，我猜测大多数的人应该喜欢在他们喜爱的代码编辑器中来进行编辑，因为那里有最得力的工具，是其他地方所完全不能比的.

有很多的著名代码编辑器，好像是可以通过某些Api或者是命令行参数比较精确操控的，也许可以参考一下Windows上git的实现，反正当需要编辑的时候(例如`git commit --amend`)，会自己唤醒Visual Studio Code(当然还有其他很多选项)，而且当我关闭标签页的时候，它也能知道.

**Comment by 88250** [comment]
@Andy-AO 你好，专家模式中的“专家”指的是对 Markdown 非常熟悉的用户（比如我 😏 ），有的时候直接对着源码编辑效率更高。

**Comment by Andy-AO** [comment]
> @Andy-AO 你好，专家模式中的“专家”指的是对 Markdown 非常熟悉的用户（比如我 😏 ），有的时候直接对着源码编辑效率更高。

令人感到困惑.

在Visual Studio Code中编辑也是'对着源码编辑',并不会打开什么带有渲染的所见即所得编辑器.

但由于Visual Studio Code是代码编辑器,所以里面有各种扩展工具和插件.

我想你是误解了我的意思.

**Comment by 88250** [comment]
@Andy-AO 思源笔记是面向大众用户的，不能只以程序员的视角看待。

**Comment by Andy-AO** [comment]
> @Andy-AO 思源笔记是面向大众用户的，不能只以程序员的视角看待。

那希望扩展功能尽快可用

这种事情只需要几行代码就可以做了

**Comment by 88250** [comment]
@Andy-AO 感谢你对思源使用方面的反馈和缺陷报告，但在技术实现方面，你的观点我并不认同：

> 这种事情只需要几行代码就可以做了

以及你在 https://github.com/siyuan-note/siyuan/issues/1101#issuecomment-761285930 中说的：

> 事实上这个功能实现起来并不困难

作为程序员，欢迎你参与到思源的开发中（思源目前底层 Markdown 引擎 Lute 是完全开源的），或者你也可以自己动手尝试构建一个笔记系统，，请不要在不了解设计思想和实现方案的时候下结论，谢谢。

**Comment by Andy-AO** [comment]
> @Andy-AO 感谢你对思源使用方面的反馈和缺陷报告，但在技术实现方面，你的观点我并不认同：
> 
> > 这种事情只需要几行代码就可以做了
> 
> 以及你在 [#1101 (comment)](https://github.com/siyuan-note/siyuan/issues/1101#issuecomment-761285930) 中说的：
> 
> > 事实上这个功能实现起来并不困难
> 
> 作为程序员，欢迎你参与到思源的开发中（思源目前底层 Markdown 引擎 Lute 是完全开源的），或者你也可以自己动手尝试构建一个笔记系统，，请不要在不了解设计思想和实现方案的时候下结论，谢谢。

想要知道当前的'文件名'需要MarkDown引擎底层吗?

**Comment by Andy-AO** [comment]
> @Andy-AO 感谢你对思源使用方面的反馈和缺陷报告，但在技术实现方面，你的观点我并不认同：
> 
> > 这种事情只需要几行代码就可以做了
> 
> 以及你在 [#1101 (comment)](https://github.com/siyuan-note/siyuan/issues/1101#issuecomment-761285930) 中说的：
> 
> > 事实上这个功能实现起来并不困难
> 
> 作为程序员，欢迎你参与到思源的开发中（思源目前底层 Markdown 引擎 Lute 是完全开源的），或者你也可以自己动手尝试构建一个笔记系统，，请不要在不了解设计思想和实现方案的时候下结论，谢谢。

'当前的文件路径是什么',如果这个事情是难以知晓的,那么我认为你的软件开发有很大的问题.

**Comment by Andy-AO** [comment]
> > @Andy-AO 思源笔记是面向大众用户的，不能只以程序员的视角看待。
> 
> 那希望扩展功能尽快可用
> 
> 这种事情只需要几行代码就可以做了

还有就是你刚刚提到的,`#1101 (comment)`,这个跟MarkDown底层完全没关系,这是你的文件管理问题根本就不关MarkDown的事情,只要涉及到本地文件的任何工具都会遇到这个问题.

这个问题的实践思路是明摆着的,你在文件树上挂个监听器就行了,每次点击的时候你检测一下文件路径上那个文件是不是还存在这就可以了.

所以说我对你的回复真的感到非常困惑,也许你只是对'容易'这个词比较敏感,如果真的是那样,以后我不会说这话了,或者我在说之前先给出具体的思路.

**Comment by Clouder0** [comment]
是否考虑在专家模式中加入隐藏块id的选项？
因为大部分使用场景下，不会对块id进行修改，而是为了调整格式，隐藏块id可以增加可读性。
这也是第三方编辑器很难做到的事情。

**Comment by 88250** [comment]
@Clouder0 专家模式是直接引入第三方编辑器 CodeMirror，不隐藏 ID，只是加个样式稍微视觉弱化一下。

**Comment by lovefishs** [comment]
> 是否考虑在专家模式中加入隐藏块id的选项？
> 因为大部分使用场景下，不会对块id进行修改，而是为了调整格式，隐藏块id可以增加可读性。
> 这也是第三方编辑器很难做到的事情。

我也很赞同在“专家模式”下隐藏 块 id，因为块 id 的存在会扰乱记录者的书写习惯

我个人非常喜欢 Typora 软件中的 “源代码模式”，我的所有文档基本都是在该模式下进行编写，然后通过 `cmd + /` 快捷键切换查看预览样式，随后再 `cmd + /` 切换回源代码模式继续编辑，源代码模式下就是标准(或者扩展)的 Markdown 语法，简单好用，效率很高

另外，“专家模式” 这个名字我个人建议修改为 “源代码模式”，虽然我喜欢在源码模式下书写文档，但我并不认为自己是“专家”，建议是不要预设使用者的角色，而是以功能所提供的具体作用来命名

一些小小的建议，思源软件越来越好

**Comment by willzhang** [comment]
专家模式有吗，在issue里没看出来这个功能是否已经实现？

**Comment by willzhang** [comment]
功能没了，有插件可以做到，论坛：https://ld246.com/article/1702362699971

**Comment by 88250** [comment]
已经废弃了，现在的版本可以通过社区插件实现，你找找看，有个编辑器插件。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月19日(周二) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 引入新的编辑模式 - 专家模式 (#868)




 
专家模式有吗，在issue里没看出来这个功能是否已经实现？

**Comment by pongfcnkl** [comment]
插件好像没法在手机端实现
