### ISSUE TITLE
同步失败：锁定云端同步目录失败，请稍后再试 (Provider: WebDAV) v2.9.4

### ISSUE THREAD

**Issue by FadingLight9291117** [siyuan-note/siyuan#8681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

同步失败：锁定云端同步目录失败，请稍后再试 (Provider: WebDAV) v2.9.4

连新建workspace都是这样

### Expected result

可以同步

### Version environment

```markdown
- Version:  v2.9.4
- Operating System: win11客户端
- Browser (if used):
```

### Log file

I 2023/07/04 21:11:34 working.go:115: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/07/04 21:11:34 runtime.go:71: kernel is booting:
    * ver [2.9.3]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [2628]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_2.9.3.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\clz\Documents\SiYuan\WPS]
I 2023/07/04 21:11:34 conf.go:130: initialized language [zh_CN] based on device locale
I 2023/07/04 21:11:34 conf.go:263: using Microsoft Store edition
I 2023/07/04 21:11:34 runtime.go:125: use network proxy [system]
I 2023/07/04 21:11:34 serve.go:114: kernel [pid=2628] http server [127.0.0.1:50901] is booting
I 2023/07/04 21:11:34 database.go:88: the database structure is changed, rebuilding database...
I 2023/07/04 21:11:34 database.go:108: reinitialized database [C:\Users\clz\Documents\SiYuan\WPS\temp\siyuan.db]
I 2023/07/04 21:11:34 conf.go:709: database size [4.1 kB], tree/block count [0/0]
I 2023/07/04 21:11:34 working.go:153: kernel booted
I 2023/07/04 21:11:34 box.go:79: auto stat [trees=0, blocks=0, dataSize=37 kB, assetsSize=0 B]
I 2023/07/04 21:11:34 disk.go:33: disk usage [total=284 GB, used=224 GB, free=61 GB]
I 2023/07/04 21:11:34 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.01s], tree [count=60, size=1.2 MB]
I 2023/07/04 21:11:35 index.go:206: resolved refs [25] in [15ms]
I 2023/07/04 21:11:35 pandoc.go:155: initialized built-in pandoc [ver=3.1.1, bin=C:\Users\clz\Documents\SiYuan\WPS\temp\pandoc\bin\pandoc.exe]
I 2023/07/04 21:11:35 conf.go:917: pandoc initialized, set pandoc bin to [C:\Users\clz\Documents\SiYuan\WPS\temp\pandoc\bin\pandoc.exe]
I 2023/07/04 21:11:36 serve.go:127: reverse proxy server [127.0.0.1:6806] is booting
W 2023/07/04 21:11:42 blocktree.go:496: save block tree [size=660 kB] to [C:\Users\clz\Documents\SiYuan\WPS\temp\blocktree], elapsed [3.45s]
I 2023/07/04 21:12:05 conf.go:475: exiting kernel [force=false, execInstallPkg=0]
I 2023/07/04 21:12:05 database.go:1134: closed database
I 2023/07/04 21:12:05 conf.go:857: cleared workspace temp
I 2023/07/04 21:12:06 conf.go:521: exited kernel
I 2023/07/04 21:12:06 sync.go:649: sync websocket closed
I 2023/07/04 23:53:57 working.go:115: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/07/04 23:53:57 runtime.go:71: kernel is booting:
    * ver [2.9.4]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [6836]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_2.9.4.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\clz\Documents\SiYuan\WPS]
I 2023/07/04 23:53:57 conf.go:231: upgraded from version [2.9.3] to [2.9.4]
I 2023/07/04 23:53:57 conf.go:263: using Microsoft Store edition
I 2023/07/04 23:53:57 runtime.go:125: use network proxy [system]
I 2023/07/04 23:53:58 serve.go:114: kernel [pid=6836] http server [127.0.0.1:50388] is booting
I 2023/07/04 23:53:58 blocktree.go:446: read block tree [660 kB] to [C:\Users\clz\Documents\SiYuan\WPS\temp\blocktree], elapsed [0.01s]
I 2023/07/04 23:53:58 conf.go:709: database size [4.6 MB], tree/block count [60/2415]
I 2023/07/04 23:53:58 working.go:153: kernel booted
I 2023/07/04 23:53:58 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=C:\Users\clz\Documents\SiYuan\WPS\temp\pandoc\bin\pandoc.exe]
I 2023/07/04 23:53:58 conf.go:917: pandoc initialized, set pandoc bin to [C:\Users\clz\Documents\SiYuan\WPS\temp\pandoc\bin\pandoc.exe]
I 2023/07/04 23:53:58 box.go:79: auto stat [trees=60, blocks=2415, dataSize=3.4 MB, assetsSize=2.0 MB]
I 2023/07/04 23:53:58 disk.go:33: disk usage [total=284 GB, used=224 GB, free=60 GB]
I 2023/07/04 23:53:58 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.01s], tree [count=60, size=1.2 MB]
W 2023/07/04 23:54:06 blocktree.go:496: save block tree [size=665 kB] to [C:\Users\clz\Documents\SiYuan\WPS\temp\blocktree], elapsed [3.69s]
E 2023/07/04 23:54:35 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/04 23:54:35 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/04 23:54:35 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/04 23:55:35 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/04 23:55:35 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/04 23:55:35 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/04 23:57:28 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/04 23:57:28 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/04 23:57:28 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:02:07 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/05 00:02:07 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/05 00:02:07 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:03:04 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/05 00:03:04 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/05 00:03:04 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:04:22 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 403
E 2023/07/05 00:04:22 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 403
E 2023/07/05 00:04:22 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:04:24 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 403
E 2023/07/05 00:04:24 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 403
E 2023/07/05 00:04:24 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:04:37 webdav.go:82: upload object [WPS/siyuan/repo/lock-sync] failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/05 00:04:37 sync_lock.go:143: upload lock sync failed: Write WPS/siyuan/repo/lock-sync: 405
E 2023/07/05 00:04:37 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:06:30 webdav.go:82: upload object [main/siyuan/repo/lock-sync] failed: Write main/siyuan/repo/lock-sync: 405
E 2023/07/05 00:06:30 sync_lock.go:143: upload lock sync failed: Write main/siyuan/repo/lock-sync: 405
E 2023/07/05 00:06:30 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:06:38 webdav.go:82: upload object [main/siyuan/repo/lock-sync] failed: Write main/siyuan/repo/lock-sync: 405
E 2023/07/05 00:06:38 sync_lock.go:143: upload lock sync failed: Write main/siyuan/repo/lock-sync: 405
E 2023/07/05 00:06:38 repository.go:1155: sync data repo failed: lock cloud repo failed
E 2023/07/05 00:06:52 webdav.go:82: upload object [main/siyuan/repo/lock-sync] failed: Write main/siyuan/repo/lock-sync: 405
E 2023/07/05 00:06:52 sync_lock.go:143: upload lock sync failed: Write main/siyuan/repo/lock-sync: 405
E 2023/07/05 00:06:52 repository.go:1155: sync data repo failed: lock cloud repo failed

**Comment by 88250** [comment]
应该是配置问题，如果服务端是自己搭建的，请结合服务端日志查看。

**Comment by FadingLight9291117** [comment]
客户端更新之前就好好的。而且我别的应用都好好的能同步。

**Comment by codeses** [comment]
同样出现了问题。 试过webdav和s3都有同样的问题。卸载过思源客户端 一样的问题

**Comment by whuwangyong** [comment]
一样的问题，用的官方同步。没升级，没有多客户端上传。今天打开就报这个。

**Comment by whuwangyong** [comment]
> 一样的问题，用的官方同步。没升级，这两天也没有多客户端上传。今天打开就报这个。

没做别的操作，从2.9.0升级到2.9.4，然后就好了。

**Comment by wanghg1992** [comment]
> 应该是配置问题，如果服务端是自己搭建的，请结合服务端日志查看。
订阅的思源的同步服务，配置也好久没变了，突然出的问题，所以不知道问题在哪。能提示下排查方法吗？

**Comment by 88250** [comment]
@wanghg1992 请升级到最新版。

**Comment by inos-github** [comment]
Same problem in 2.9.5
WebDAV sync is still broken

**Comment by luke-zhang580** [comment]
<img width="394" alt="CleanShot 2023-07-15 at 00 26 16@2x" src="https://github.com/siyuan-note/siyuan/assets/45325652/a0292260-d65a-4f8c-942f-22ed27d89d5f"> 同样的问题。

**Comment by zhpj18** [comment]
升级到 2.9.7 了，还是同样的问题

**Comment by 88250** [comment]
@zhpj18 检查一下 WebDAV 服务端配置

**Comment by zhpj18** [comment]
@88250 WebDAV 是正常的，Joplin 和 Obsidian 通过 WebDAV 同步都正常。思源笔记连续好几个版本都不能同步了，今天又装了 2.9.8 也是不行。

**Comment by 88250** [comment]
@zhpj18 把服务端所有数据都清空后再试试，我这里测试正常。

**Comment by taozuinb** [comment]
我也出现了这个问题，

> @88250 WebDAV 是正常的，Joplin 和 Obsidian 通过 WebDAV 同步都正常。思源笔记连续好几个版本都不能同步了，今天又装了 2.9.8 也是不行。
我也出现了这个问题，你这个后来好了吗

**Comment by zhpj18** [comment]
@taozuinb 没有，又搭了个 minio，现在改成用 s3 协议同步了。

**Comment by newproplus** [comment]
> 同步失败：锁定云端同步目录失败，请稍后再试 (Provider: WebDAV) v2.10.11

v2.10.11 还是不行，而且是一开始可以，后来坏掉了

**Comment by ibaoger** [comment]
应该是思源对于 WebDAV 协议的支持不够完善，还是换S3协议吧，无法忍受丢笔记，代价实在是太高了

**Comment by deyoulee** [comment]
2.11.0版本，minio S3协议。连续两天了，用着用着就这样了，退出账号重新登陆也不行
<img width="411" alt="iShot_2023-11-30_14 36 06" src="https://github.com/siyuan-note/siyuan/assets/5405135/d06649f8-9ac3-4479-a274-d2f5cdb5db58">

**Comment by mozhux** [comment]
> 2.11.0版本，minio S3协议。连续两天了，用着用着就这样了，退出账号重新登陆也不行 <img alt="iShot_2023-11-30_14 36 06" width="411" src="https://private-user-images.githubusercontent.com/5405135/286838685-d06649f8-9ac3-4479-a274-d2f5cdb5db58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzE3NTEsIm5iZiI6MTcwMTMzMTQ1MSwicGF0aCI6Ii81NDA1MTM1LzI4NjgzODY4NS1kMDY2NDlmOC05YWMzLTQ0NzktYTI3NC1kMmY1Y2RiNWRiNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDgwNDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzc5YzE0MDQxYTAzYzExNWQxNWQ4OGMzOGRjYmZkODcxNTZjM2I1ZmZjYjNiNjQyOWQyMmE1OWRmNDVkMDZkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3CjZIKGRl-6V7cQcM54S87kipfBOIlAiUf3v-EYelSA">

S3设置最后那个什么ve配置，选成path试试

**Comment by dongdong2300** [comment]
我用的是 webdav ，同步一直不成功。
后面的解决办法是：
1. 在 webdav 配置后，点击【云端同步目录】后选择的目录里面创建一个文件夹，名称为【siyuan】
2. 把本地思源笔记的文件先上传上去。
3. 这样就可以同步了。

**Comment by xia0ming** [comment]
我也出现了同样的问题, 但是最后发现是 webDav 服务端思源对应的文件夹权限有问题
