### ISSUE TITLE
请求支持删除查询条件历史

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8682]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/32903588/908177f3-0a85-43b0-9e35-316bbcc9845b)
- 如图，有时候查询时反复修改查询条件，会有许多无用的记录，之后再去翻阅会影响复用

### Describe the optimal solution

- 请求提供单条删除和全部删除，私以为是必要且基础的功能

**Comment by 88250** [comment]
你好，这个我们不认为是基础功能，不过我们也期待它可以通过插件管理。
