### ISSUE TITLE
同步失败：锁定云端同步目录失败，请稍后再试

### ISSUE THREAD

**Issue by coderDancer** [siyuan-note/siyuan#8684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/22238447/ce6141cd-7352-4519-a228-e4e43a11c13c)

### Expected result

希望可以正常同步

### Version environment

```markdown
- Version: 2.9.3 
- Operating System: windows
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11953488/system-log.zip)

**Comment by 88250** [comment]
从日志上看是网络问题，建议升级到最新版后再试试。

**Comment by newproplus** [comment]
>  同步失败：锁定云端同步目录失败，请稍后再试 (Provider: WebDAV) v2.10.11

v2.10.11 还是不行，而且是一开始可以，后来坏掉了
