### ISSUE TITLE
为标题 添加虚拟层级序号

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#8687]
### In what scenarios do you need this feature?

如
```
# title a
## title b
### title c
### title d
## title e
### title d
```

**- 原始显示**
# title a
### title d

**- 虚拟层级序号显示**
# title a
### Describe the optimal solution

可以设置控制是否显示 以及可以设置层级模式

**Comment by 88250** [comment]
这个目前实现不了，抱歉。

Duplicate of https://github.com/siyuan-note/siyuan/issues/522

**Comment by gdy106** [comment]
例如暗色这类主题有这个功能，但是思源是动态加载来负载大文档的，所以如果你文档大的话，序号就不准，而且开了还非常容易卡。如果你刚需这个功能可以用支持的主题，或者把相关代码加到设置-外观-代码片段里面，这样全局都可以使用。
