### ISSUE TITLE
emoji 搜索补全增强

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#869]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

输入 emoji 的时候

### 描述候选解决方案 Describe the candidate solution

建议参照这个网站的释义 https://emojixd.com/list ，不仅可以输入英文检索而且应当可以输入中文检索

**Comment by 88250** [comment]
后面考虑，谢谢。

**Comment by 88250** [comment]
暂时不考虑了……还是靠英文吧，不然以后也许还有其他语言呢……
