### ISSUE TITLE
Click on the link without jumping

### ISSUE THREAD

**Issue by NU-LL** [siyuan-note/siyuan#8697]
### In what scenarios do you need this feature?

点击链接不进行跳转，而是直接将光标移动到点击的位置上方便直接修改链接文本（只读模式下或许可以保持不变？）

当前右键点击链接，再进行修改文本比较繁琐，而且在链接附近插入文本时容易误触

### Describe the optimal solution

跳转可以改为Ctrl+点击，或者其他方式

**Comment by 88250** [comment]
感谢反馈，但从使用频率角度考虑，修改低于点击跳转，所以点击跳转需要更便利。
