### ISSUE TITLE
导出pdf时，数学公式的换行有问题

### ISSUE THREAD

**Issue by OrderSpace** [siyuan-note/siyuan#870]
这个是源代码，以及实时渲染效果
![image](https://user-images.githubusercontent.com/23428698/103265689-1dbc0100-49e9-11eb-9822-9230bdaefd03.png)
这个是导出后的pdf结果
![image](https://user-images.githubusercontent.com/23428698/103265743-404e1a00-49e9-11eb-89ce-c5eeb87627a0.png)
换行处有问题

**Comment by 88250** [comment]
你好，你使用的是 KaTex 引擎吗？

**Comment by OrderSpace** [comment]
不，我使用的是MathJax

**Comment by 88250** [comment]
思源里 MathJax 的换行 `\\` 有问题，请关注 https://github.com/siyuan-note/siyuan/issues/340

**Comment by OrderSpace** [comment]
好的谢谢

**Comment by OrderSpace** [comment]
好的，谢谢



在 2020-12-29 22:52:53，"D" <notifications@github.com> 写道：

思源里 MathJax 的换行 \\ 有问题，请关注 #340
