### ISSUE TITLE
Improve create workspace interaction

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8700]
额外增加「新建工作空间」的按钮

### In what scenarios do you need this feature?

多年来不断有用户反应创建工作空间的功能比较不容易理解。
https://ld246.com/article/1688664947698
![image](https://github.com/siyuan-note/siyuan/assets/27268127/51f79216-31f6-4269-8d63-abcc74720dea)

![image](https://github.com/siyuan-note/siyuan/assets/27268127/c1b2c7b3-00e7-4079-890e-ee3ed344b545)

------

我以为，目前的问题在于：

1. 很多人不知道「打开」同时也具有创建工作空间的能力
2. 目标不明确：「打开」之后到底是在选择的路径下创建新的工作空间，还是自动在该目录下新建一个目录在里面创建工作空间？这个用户在操作之前是不知道的。

### Describe the optimal solution

单独增加一个新建工作空间的按钮，并且附上提示对话框

![image](https://github.com/siyuan-note/siyuan/assets/27268127/2c90b112-15c5-4ef3-b54d-3a93fa170539)

基本交互逻辑类似安装软件：

1. 用户点击按钮，选择一个目录
2. 在文本框中**显示工作空间的最终实际路径**
3. 用户可以手动更改路径，这样方便他们自定义名称
4. 点击创建

**Comment by 88250** [comment]
我觉得这样更好：`打开...` 自动检测是不是已有工作空间，是的话直接打开；不是的话弹出确认框询问用户是不是要把这个路径作为工作空间。

这样可以避免增加入口，操作路径也短，和初始化时选择工作空间保持一致，都是用选择的路径做工作空间。

**Comment by frostime** [comment]
> 我觉得这样更好：`打开...` 自动检测是不是已有工作空间，是的话直接打开；不是的话弹出确认框询问用户是不是要把这个路径作为工作空间。
> 
> 这样可以避免增加入口，操作路径也短，和初始化时选择工作空间保持一致，都是用选择的路径做工作空间。

可以简化但是有两个东西我觉得是必须的：

1. 明确告知用户「打开」也是可以用于「创建」的，比如可以把「打开」的文本改成「打开/新建」
2. 明确告诉用户工作空间的路径，也就是这个路径文本还是有必要显示的；通过明确指定路径来**避免用户对「到底是将我打开的目录作为工作空间还是在这个目录下新建一个目录作为工作空间」产生疑惑**

    
![image](https://github.com/siyuan-note/siyuan/assets/27268127/96d0440b-0321-4c61-9ce5-1714a9c3d9c4)

**Comment by 88250** [comment]
不引入工作空间名称，只需要让用户知道路径就行了，现在这里的设计是一致的。

**Comment by frostime** [comment]
那就是需要增加用户说明了，弹出对话框，明确的告知用户

「我们将打开路径 xxx 下的工作空间」或者「我们将在路径 xxx 下创建一个新的工作空间」

**Comment by 88250** [comment]
打开就没有必要再重复提示了吧，新建提示确认即可。

**Comment by gdy106** [comment]
我觉得可以不增加按键，但是第一次使用时新建工作空间，给一个引导。就是那种其他地方都是暗的，只有新建工作空间步骤的按钮是亮的，搭配文字提示，用户操作过一遍就会了，想不起来就开启新用户引导。
如果引导比较花时间的话，这方面我觉得也可以学一下marginnotes的用户手册，手册就是学习笔记，从头看一遍就会了，非常直观好懂。忘记也能再去看。

**Comment by 88250** [comment]
先加确认提示看看。



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 8, 2023 14:26 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve create workspace interaction (Issue#8700)




 
我觉得可以不增加按键，但是第一次使用时新建工作空间，给一个引导。就是那种其他地方都是暗的，只有新建工作空间步骤的按钮是亮的，搭配文字提示，用户操作过一遍就会了，想不起来就开启新用户引导。
 如果引导比较花时间的话，这方面我觉得也可以学一下marginnotes的用户手册，手册就是学习笔记，从头看一遍就会了，非常直观好懂。忘记也能再去看。
