### ISSUE TITLE
Open links in background with mid-button click

### ISSUE THREAD

**Issue by 7eopard** [siyuan-note/siyuan#8701]
### In what scenarios do you need this feature?

Open in the current tab is enabled, while the tab isn't pinned. 

If disabled, there's no easy way to open links in the current tab.
If enabled, there's no way to open them in the background easily.

### Describe the optimal solution

Open links in the background with a mid-button click at any time.

### Describe the candidate solution

Open links in the background with a mid-button click, when open in the current tab is enabled at least.

**Comment by 88250** [comment]
Hello, we think it is relatively rare to open Tab in the background in the current window, please consider opening it in split screen (Alt/Shift+Click), thank you for your feedback.
