### ISSUE TITLE
Can't modify font appearance after triple-clicking to select all the text in a cell of a table

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8703]
表格中三击左键全选当前单元格文字，无法修改字体外观。

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

表格中三击左键全选当前单元格文字，无法修改字体外观，字体外观面板可以弹出但是点击后字色或背景不会修改。
但是光标从头划到尾选中所有文字后，可以修改字体外观。

### Expected result

鼠标三击选中全部文字后可以修改字体外观。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/d93a29e2-040a-4ed2-b4c8-4de27e4caf8d

### Version environment

```markdown
- Version: 2.9.4
- Operating System: win 10
- Browser (if used):
```

### Log file

不需要，新工作空间可复现。

**Comment by zxhd863943427** [comment]
win 10, 2.9.4dev1，无法复现
![更改](https://github.com/siyuan-note/siyuan/assets/74853597/8f025e49-90d0-4185-b5e8-cc90524f43b6)

**Comment by gdy106** [comment]
> win 10, 2.9.4dev1，无法复现 ![更改](https://user-images.githubusercontent.com/74853597/251947345-8f025e49-90d0-4185-b5e8-cc90524f43b6.gif)

因为你这个文本本身没有字体外观，我测试过，在无任何字体外观的单元格里可以给文字添加外观，但是如果字体本身有外观，不能覆盖。
