### ISSUE TITLE
【特性提议】搜索框支持退格（Backspace）清空搜索条件

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#8704]
### In what scenarios do you need this feature?

ctrl+f 本文档搜索非常干扰常用的ctrl+p搜索，建议在搜索框中，当光标位于行首时，按退格（Backspace）可以清空搜索条件

### Describe the optimal solution

搜索框支持退格（Backspace）清空搜索条件

**Comment by gdy106** [comment]
要考虑到误触的可能性，如果要用退格键清除，我建议三击才生效。

**Comment by 88250** [comment]
这个交互有点过于“隐僻”了，建议还是鼠标点击来取消已经指定的路径，感谢反馈。
