### ISSUE TITLE
`Show in Folder` hangs on macOS

### ISSUE THREAD

**Issue by toint-cn** [siyuan-note/siyuan#8705]
MacbookPro M1 在思源笔记中，右键「打开文件位置」导致「Finder」崩溃

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

MacbookPro M1 在思源笔记中，右键「打开文件位置」导致「Finder」崩溃

### Expected result

能够打开文件位置

### Screenshot or screen recording presentation

<img width="140" alt="截屏2023-07-08 16 22 09" src="https://github.com/siyuan-note/siyuan/assets/97728917/447e598a-ad52-43c8-92f7-11cc94560454">

### Version environment

```markdown
- Version: 版本2.9.4 (2.9.4)
- Operating System: 13.4 (22F66)
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/11990083/siyuan.log)

**Comment by 88250** [comment]
这应该是 Electron 的 bug，关联上游 https://github.com/electron/electron/issues/38540
