### ISSUE TITLE
视频上传到思源有时会消失

### ISSUE THREAD

**Issue by scckele** [siyuan-note/siyuan#8708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

视频上传到思源有时会消失
c:\file\视频.mp4
鼠标右键复制
然后打开思源
鼠标右键粘贴或者ctrl+v
右上角提示上传中
上传完成后，视频在思源可正常浏览预览。点击播放，倍数，可正常使用
好的，有事情去忙，关闭思源文档
但是等我过一会儿回来重新打开该视频所在文档，视频区域有播放框，但时长为0，黑屏，点击不能播放，右键资源-打开文件位置-提示失败

### Expected result

上传后不消失

### Version environment

```markdown
2.9.4
win
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/11990733/system-log.zip)

**Comment by 88250** [comment]
从日志看暂时无法确定问题，建议先解决日志中接入第三方 S3 同步报错问题。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
