### ISSUE TITLE
Can we have two new categories in `New Issue` template

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8711]
### In what scenarios do you need this feature?

Hi team,
As Siyuan grows, people will have `questions/doubts` (as not much resources are currently available) and `suggestions` for improving Siyuan. `Questions` generally do not come under any of the current options (i.e. `Bug report`, `Request new features`, `Report a security vulnerability`, `Market package feature request`, `Twitter`).

### Describe the optimal solution

It would be nice to add `questions` and `suggestions` as new categories in the GitHub issues template.
Having these categories will make it easier for the Siyuan team too to differentiate between `Questions/Doubts`, `Suggestions`, `Bug reports` and `Feature Request`. And, the issues under `Questions/Doubts` can also act as a type of documentation.

**Comment by 88250** [comment]
This may have some effect, just from the perspective of developers or search, I think adding Label (Question) should be enough.

Anyway, you are welcome to contribute the two mentioned Issue templates via PR, thank you.
