### ISSUE TITLE
Support for saving .sy files in the single-line format

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8712]
Possible performance improvement of more than 20% at multiple places

### In what scenarios do you need this feature?

Hello team,
I would like to share a performance improvement idea.

Currently, Siyuan stores a formatted version of JSON in `.sy` files which results in many `\t` and `\n` characters being saved to the file. Following is a table showing number of extra characters per file (for some files in `SiYuan User Guide`)

|File name|Total characters|Tabs and new line|% of Tabs and new line|
|:----|----:|----:|:----|
|Please Start Here|16,068|5,466|34.0%|
|Privacy Policy and User Agreement|10,333|2,664|25.7%|
|FAQ|44,585|13,988|31.3%|
|Acknowledgements|44,281|15,255|34.4%|
|Data Security|24,648|7,292|29.5%|
|Performance Optimization|15,687|4,367|27.8%|
|Glossary|21,955|4,849|22.0%|

Doing the same counting for all files under `SiYuan User Guide` and summing it up, we get
|Total characters|Tabs and new line|% of Tabs and new line|
|:----|:----|:----|
|10,78,664|3,56,675|33%|

The "Notebooks which users will create (over years)" will generally be way larger than "SiYuan User Guide". So, the percentage of "tabs and new line" characters could go even upper.

### Describe the optimal solution

Based on numbers shared above, I feel if we store raw JSON (without any formatting), then it would result in:
1. Smaller file/note size on the storage disk
2. Faster file/note save operation
3. Faster loading of notes
4. Reduced memory usage when loading the notes
5. Faster parsing of the notes/JSON when loading
6. Reduced network load when syncing files
7. Faster notes syncing

Most of the above improvement are linked to each other, and the primary source of all improvement is 1 (i.e. smaller file/note size on the storage disk)
The performance improvements sum up to a noticeable amount as the note/doc size increase. For example, for basic operation like opening a note, editing it, saving and syncing it will look like:
1. Load the note (i.e. read the `.sy` file from the disk)
    - 🚀 faster as smaller file/note size on the storage disk, and reduced memory usage as the `\t` and `\n` characters are not loaded
2. Parse the JSON
    - 🚀 faster as lesser number of characters to parse
3. Render
4. User edits the notes
5. Save the note
    - 🚀 faster as converting JavaScript object into JSON string will be quick and lesser amount of data is to be written on the disk
6. Sync to cloud
    - 🚀 faster as lesser amount of data to sync (due to smaller file size), and reduced network load too

I believe the expected improvement in most of the above operations is about `22%` to `35%` (based on the tables shown above in the previous section)

Thank You 🙏

**Comment by 88250** [comment]
Actually, we thought about it before, but at that time because some users need to use git management (they need diff text), such as (in Chinese):

* https://ld246.com/article/1626434677993
* https://ld246.com/article/1629599006639

It is also because of this requirement that we retain blank characters. If we want to remove it, maybe we can only add one setting item: whether to use the single-line format, which is enabled by default in the new version.

**Comment by 88250** [comment]
Settings - Doc Tree - Save with a single line

![image](https://github.com/siyuan-note/siyuan/assets/873584/7ab141cc-d0c6-410c-8463-e97499d3fea6)

**Comment by 88250** [comment]
Yes, the added option is turned off by default, but it is turned on by default for users of newly initialized configurations.

**Comment by Zuoqiu-Yingyi** [comment]
@88250
It seems that this setting is not searchable in the search panel❓
![image](https://github.com/siyuan-note/siyuan/assets/49649786/e7cc7c67-9e62-4692-983a-21984abc736c)

**Comment by 88250** [comment]
Thanks for reporting it.



---Original---
From: ***@***.***&gt;
Date: Tue, Jul 11, 2023 13:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support for saving .sy files in thesingle-line format (Issue #8712)




 
@88250
 It seems that this setting is not searchable in the search panel❓
