### ISSUE TITLE
Overlap of reference count and other buttons

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Steps to reproduce
1. Go to `SiYuan User Guide/Please Start Here/Editor/Formatting elements`
2. Hover over the embedded block
<img width="702" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/e3ff07f9-6f28-4e72-8efe-19d7739806df">

Issues:
1. The buttons on the top right overlap with the reference count. Thus making it hard to click the "three dots button" (i.e. the rightmost button for more options)
2. The three button with "refresh icon, pencil icon and three dots icon" do not have tooltip to understand what they do. It would be nice if you could give some info on what each of them does.

### Expected result

No idea how this overlap issue can be solved.

### Version environment

```markdown
- Version: 2.9.4
- Operating System: macOS 12.6
```

### Log file

\-

**Comment by fenilgmehta** [comment]
Based on `Three dots icon (i.e. More options) > Embed block > *` I guess `Refresh SQL` and `Update SQL` would be the right tooltip for the refresh icon and pencil icon respectively.

**Comment by Vanessa219** [comment]
Move the counter to the right.

<img width="804" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/cf38aa10-d69f-4912-be5c-59728f847854">
