### ISSUE TITLE
改进ui和提示

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8716]
### In what scenarios do you need this feature?

可能需要改进部分ui的文本，或增加ui的悬浮显示，如
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/ae440ce3-8a28-43e7-983d-d035e62cba4d)

改进的意见征求见如下在线文档：
https://docs.qq.com/sheet/DTkFnTURyVVJrT3Vu?groupUin=Es7Xx%252Br38a%252BvDlhazMcRrQ%253D%253D&tab=BB08J2

### Describe the optimal solution

改进ui和提示

**Comment by 88250** [comment]
术语表中列过的点就不再考虑改变了。

**Comment by 88250** [comment]
老铁，这个我暂时关闭了，麻烦帮忙整理完修改点以后回复一下，我们重新打开，谢谢。
