### ISSUE TITLE
单引号锚文本能够渲染但不被识别

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在引用格式`(( 块id “锚文本”))`中，如果包裹锚文本的引号是单引号，虽然编辑器中能正常显示，但是是处于缺少锚文本的状态，修改对应块内容会导致锚文本变化（也就是此时锚文本为空）

![image](https://github.com/siyuan-note/siyuan/assets/63407442/43f2145e-6e5f-42b7-ada5-5e7ab2b37e8f)
![image](https://github.com/siyuan-note/siyuan/assets/63407442/a2e86119-63e2-4867-8e96-008040bc3f65)

### Expected result

要么单引号包裹的锚文本不被渲染，要么就同样视为锚文本吧

### Version environment

```markdown
- Version: 2.9.4
- Operating System: windows
- Browser (if used):
```

### Log file

null

**Comment by 88250** [comment]
单引号包裹的是动态锚文本，修改定义块以后才会跟随变动。
