### ISSUE TITLE
Alt+X的bug

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/125173405/6469c31e-2d90-4029-a480-e7f27a0e10be

如视频所示，对行内文本通过字色面板选取卡片颜色修改了背景色和字色，但是alt+x只修改背景色不修改字色。
对块也是一样的。
![image](https://github.com/siyuan-note/siyuan/assets/125173405/e0eeb0b4-0328-4538-8ca3-0630b78b1489)

### Expected result

希望能统一一下，因为卡片的背景色本来就是背景色1，如果用户只需要添加背景色1选背景色1就行了。

### Version environment

```markdown
- Version: 2.9.5 dev2
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
Alt+X 只会应用最后一次字体外观设置，感谢反馈。
