### ISSUE TITLE
Possible scope of reducing the unnecessary reload/rerendering

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When using the block scroller, the page/blocks reload even when they have already been loaded and rendered. Please see the attached video for the steps to reproduce the issue.

https://github.com/siyuan-note/siyuan/assets/42742240/397a8371-6f44-4c85-a0a7-7bfe7c1fb313

### Expected result

- Blocks should not be reloaded in the scenario shown in the above video
- Some sort of caching should be done to improve the experience and reduce the rerenders (I would be happy to discuss more about this)

### Version environment

```markdown
- Version: 2.9.4
- Operating System: macOS 12.6
```

### Log file

\-

**Comment by 88250** [comment]
This is a feature of SiYuan's dynamic loading. If too many blocks are loaded, the UI will freeze. There is no better technical optimization solution for this part, thanks for the feedback.

**Comment by fenilgmehta** [comment]
I agree that dynamic loading is used to avoid UI freeze. My concern is little different.

In the UI, we have two types of scrollbars:
1. The regular scrollbar (which looks just like any webpage in a browser)
2. Block scrollbar (which is to the left of the regular scrollbar, in blue color in the video I shared)

Consider the page P which I showed in the video. Let us assume it has 80 blocks. When the page is opened for the first time, let us say only first 20 blocks are loaded. Now, I manually scroll to the bottom of the page, thus causing all 80 blocks to be loaded and rendered. Now, once all 80 blocks are loaded, we can manually scroll up and down without any reloading.

If I use regular scrollbar (i.e. type 1), no reloading happens. But, if I use block scrollbar (i.e. type 2), already loaded blocks are also reloaded.

We can reproduce the issue of block scrollbar using:
1. Open `/Please Start Here/Editor/Formatting elements` and we should be at the top of the page
2. Manually scroll to the bottom of the page (thus causing all blocks to be loaded)
3. Manually scroll to the top of the page
4. Use block scrollbar (i.e. type 2) to go to block 60.
5. By looking at the size of the regular scrollbar (i.e. type 1), we can conclude that the block from 0 to some number X (where X < 60) have vanished and they will be reloaded when we try to manually scroll to the top of the page.

Had we used regular scrollbar in step 4, no reloading would happen in step 5.

Another way to reproduce the issue:
1. Open `/Please Start Here/Editor/Formatting elements` and we should be at the top of the page
2. Use block scrollbar to go to block 60
3. Just do left click on the blue button of the block scrollbar (as visible in the video which I had shared, the color is blue in dark theme) a couple of times and we observe that we are taken to the same block of the page, but still they are reloaded/rerendered everytime we click the blue button.

Let me know if anymore info or a video is needed.

**Comment by 88250** [comment]
The loaded blocks will not be reserved by default, otherwise the interface will freeze after multiple scrolling, so we will also dynamically delete the loaded blocks. If you want to keep it, there is a reserve option in the upper right menu to do it.

**Comment by 88250** [comment]
In addition, there is an option in Settings - Editor to adjust the number of dynamic loading blocks. If the device performance is good, adjusting it larger will reduce dynamic loading.

**Comment by fenilgmehta** [comment]
Did not find the reserve option. Can you please share screenshot for it.

I still think that the situation which I explained under `Another way to reproduce the issue:` needs improvement because we are repeatedly going to the same block which is already being displayed. Still it is getting rerendered/reloaded. Go to block 63 on the same page and keep clicking the blue dot of the block scrollbar and you will notice that the chart is getting rerendered/reloaded, which is not expected.

https://github.com/siyuan-note/siyuan/assets/42742240/027a5034-a4f2-46a1-97b1-987ce17e3c98

Ideally, the block scrollbar should act more like [this](https://stackoverflow.com/questions/4855168/what-is-href-and-why-is-it-used) ([demo](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_links_bookmark) -- clicking at any place in the block scrollbar should work like clicking `Jump to Chapter 10` in the demo which I shared)

---

### Expected behaviour of block scrollbar in different situations are shown below.
**Assumptions**
`1` denotes the block we are at in the page/doc (same thing is shown when we hover over the block scrollbar)
`2` denotes block is loaded/rendered
`x` denotes the block at which someone move the block scrollbar
`-` denotes block is not loaded/rendered

**Case 1:**
Initial situation: `1222-----x---`
Now, when we click on `x`, I agree that we offload `1222` and the resulting UI will become more like `---------1222`
This is the current behaviour too.

**Case 2:**
```
Initial situtation:
1222222------
    ^ go to this block using block scrollbar

Observed result is as follows and reloading happens
----122------

Expected result is as follows and neither reloading nor any offloading should happen
2222122------
```

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/5c853e66-8052-4f11-8172-da00f60af15b)

If you click the block scroll bar to jump to load, the position of the block will be recalculated, and some blocks will be loaded up/down from the position, and the original loaded blocks will not be retained.
