### ISSUE TITLE
Ability to mark task as done in embedded blocks

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#8720]
### In what scenarios do you need this feature?

I understand that currently there are no plans for implementing editing in place for embedded blocks, as per this closed issue: https://github.com/siyuan-note/siyuan/issues/7804

However it would be good if we could at least check/uncheck tasks within embedded blocks.

### Describe the optimal solution

Make the task checkbox interactive within an embedded block.

### Describe the candidate solution

None.

### Other information

None.

**Comment by 88250** [comment]
Sorry, this cannot be done, it can only be edited through the floating window.

**Comment by ognsya** [comment]
Thank you for replying.

I see the Issue has been Closed. Does this mean this Feature Request will never be reconsidered in the future? Also, doesn't this make it harder for other users to find this Feature Request, so they can comment on it, instead of opening new (duplicate) Feature Requests?

I apologize if these are stupid questions. I am just an end user, and not familiar with github.

**Comment by 88250** [comment]
Hello, this issue will not be considered for implementation at this stage and will be reopened if it is considered in the future.

Other users can find this issue by searching, thanks.

**Comment by ognsya** [comment]
> will be reopened if it is considered in the future.

Ok, now I understand!

Thank you for clarifying.
