### ISSUE TITLE
希望加入一个本地文件链接功能.

### ISSUE THREAD

**Issue by kingxi82** [siyuan-note/siyuan#8721]
### In what scenarios do you need this feature?

思源我是作为一个重要的离线本地笔记软件来使用,有时不是所有文件都要以资源形式加入到笔记内.
而且我用到了文档的版本管理,所以现在不能直接把文档放到思源的资源里,我需要以链接本地文件路径的形式来使用文件,希望思源大佬可以考虑加入支持.

### Describe the optimal solution

加入一种链接,不同于嵌入资源,也不同于url链接,只是链接到本地文件,而且单击打开本地文件. 
链接方式可以是拖入,或这/菜单加入.

**Comment by 88250** [comment]
现有的超链接可以达到这个效果，具体请看用户指南资源文件章节。
