### ISSUE TITLE
Option to highlight search terms in the document itself (as in Google Chrome browser)

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#8723]
### In what scenarios do you need this feature?

I'd like an option to make the document search (triggered by CTRL-F) behave the same as the Find function in Google Chrome (same shortcut) - i.e. all occurrences of the search term are highlighted directly in the document, and hitting ENTER jumps from one to the next.

### Describe the optimal solution

Same behaviour as in Google Chrome browser.

**Comment by 88250** [comment]
Sorry, this can't be done.
