### ISSUE TITLE
通过`/api/block/updateBlock`和`/api/filetree/createDocWithMd`使用markdown创建/更新块的HTML渲染问题

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

通过Markdown代码创建块时，使用了markdown混杂HTML的写法，并且专门给HTML块加了<div></div>并且去掉了空行，结果虽然HTML代码在一个块里，但是不渲染为HTML块，还是保持着文本的格式。然而当我点到HTML代码内部时，面包屑上直接把这段代码渲染了，就很神奇，但是是不太对的。

如果我把这段代码剪切再粘贴到同一个位置，它又会自动渲染，是不是这两个api的导入在处理HTML块的时候有什么问题？

### Expected result

理论上应该是HTML块渲染，面包屑上显示代码的（复制渲染的HTML块是这个样子的）

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/63407442/153458c3-594f-4aea-8f0e-648960118391)

### Version environment

```markdown
- Version: 2.9.4
- Operating System: Windows
- Browser (if used):
```

### Log file

null

**Comment by 88250** [comment]
感谢反馈，接口不支持 HTML 和 Markdown 标记混合插入的。
