### ISSUE TITLE
Swiping on the breadcrumb doesn't trigger opening side panel on the mobile

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#8729]
### In what scenarios do you need this feature?

I sometime activate the Doc Tree and the Settings menu by mistake, when doing left/right swipes on mobile. For example, this happens when navigating the breadcrumbs.

### Describe the optimal solution

I suggest having the Doc Tree and Settings menu be activated by an edge swipe (i.e. a swipe that starts outside of the screen and comes in, either from the left or from the right).

This would also free up the left and right swipes for other functions (for example, it could be used for indenting/outdenting list items).

### Describe the candidate solution

Designate a certain margin on the left and right where the swipe needs to start in order to activate the Doc Tree and Settings menus on mobile. Around 1cm for example.

### Other information

This can be optional. Users can choose in Settings if they prefer this behaviour or not.

_No response_

**Comment by 88250** [comment]
Hi, swipe from the edge is back function.

**Comment by ognsya** [comment]
> Hi, swipe from the edge is back function.

Thanks for the reply

Sorry, what does "back function" mean?
On my phone edge swipe does the same as a left swipe anywhere.

**Comment by 88250** [comment]
After jumping by reference, you can use the back function to return to the previous document.

**Comment by ognsya** [comment]
Thanks for explaining.

On my phone (Pixel) this isn't happening. Edge swipe behaves the same as a normal swipe.

Edge swipe works in other apps in my phone. For example, on Feedly (RSS reader app), the menu is invoked by an edge swipe, which frees up side swipping for other actions.

**Comment by Vanessa219** [comment]
We improved breadcrumb on the mobile in the https://github.com/siyuan-note/siyuan/issues/8623 
<img width="500" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/60c097d7-3913-429f-9b91-40433cb3eb23">
