### ISSUE TITLE
SHIFT+ALT+UP to fold parent block

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#8730]
### In what scenarios do you need this feature?

I'd like a shortcut to fold the **parent** of the block currently in focus. This would make it much easier and quicker to navigate and tidy up a List.

Ideally once the folding happens, focus should go to the parent. This would allow users to then keep folding parents as needed.

I understand SiYuan is not intended to be an Outliner app, however the editor is so good that I think it could easily become a first-class Outliner. All it needs is a few extra shortcuts.

### Describe the optimal solution

Have that shortcut be mapped to folding the parent.

### Describe the candidate solution

At least have the action available in the Keymap, so users can add a key binding for it if they want.

### Other information

- Currently that shortcut shows in the Keymap as Expand Up, however it doesn't seem to have any effect. Is it a bug? What is it supposed to be doing?

-  SHIFT+ALT+DOWN would still be free for something else.

**Comment by Vanessa219** [comment]
Outline software does not seem to have the function of folding parent block, can you list them?

⌥⇧↓ and ⌥⇧↑ is work for this:

https://github.com/siyuan-note/siyuan/assets/970828/fe79d31f-e4ad-4f92-af70-933a2850814f
