### ISSUE TITLE
建议保留原移动端面包屑设计，现在不直观操作繁琐。

### ISSUE THREAD

**Issue by enneaa** [siyuan-note/siyuan#8733]
### In what scenarios do you need this feature?

面包屑顾名思义应该 一层/一层/一层 的展示，即直观又方便操作，点击即可进入聚焦模式，点击上下层即可在不同层级之间导航。还可以设计成再点击一次退出聚焦模式，这样也符合一般操作的习惯。
如果觉得面包屑过长显示不下，可以左右滚动。

现在的设计，进入聚焦模式不方便，点击面包屑还要先点面包屑再点对应层级，而且现在那一栏都空着挺浪费的。

### Describe the optimal solution

面包屑顾名思义应该 一层/一层/一层 的展示，即直观又方便操作，点击即可进入聚焦模式，点击上下层即可在不同层级之间导航。还可以设计成再点击一次退出聚焦模式，这样也符合一般操作的习惯。
如果觉得面包屑过长显示不下，可以左右滚动。

现在的设计，进入聚焦模式不方便，点击面包屑还要先点面包屑再点对应层级，而且现在那一栏都空着挺浪费的。

**Comment by 88250** [comment]
你好，这个不考虑改回去了，请参考之前的讨论 https://github.com/siyuan-note/siyuan/issues/8623

**Comment by enneaa** [comment]
> 你好，这个不考虑改回去了，请参考之前的讨论 #8623

我看了下原讨论，提出的是没有退出聚焦按钮的问题，可是就算加一个退出按钮，也不需要把面包屑收到另一个按钮。

**Comment by enneaa** [comment]
![Screenshot_2023-07-12-08-08-03-377_org b3log siyuan-edit](https://github.com/siyuan-note/siyuan/assets/11749618/41886ec9-49b6-4895-b048-aed0d7755e96)
现在面包屑那一栏右侧空着也没啥用。

**Comment by Vanessa219** [comment]
正常是这样的，现在的版本有点问题，下个版本会进行改进
<img width="381" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/d3de9a06-67a2-4906-8086-6fda1bc9d67b">

**Comment by gdy106** [comment]
现在版本的面包屑点进去还是一串滑块，确实没啥单开的必要。
![IMG_1249](https://github.com/siyuan-note/siyuan/assets/57566668/207f0acf-a277-40ed-83e3-4ad2877cd43f)

既然单开一个窗口了，我建议面包屑的父子文档层级也和文档内的块层级一样，按列表显示，右侧提供一个小三角的块标可以缩起来。当前文档的名称用放大字号或者加粗、字色等方式进行强调。
这样建议是为了适配手机端上下滑动的习惯，完全去掉左右滑动。毕竟都给了一整个版面给面包屑了，那就在直观性上进一步发挥一下。
我大致做了个效果图：
![手机端面包屑](https://github.com/siyuan-note/siyuan/assets/57566668/dc3953b1-6a2b-44ea-aee1-8d0f39570104)

**Comment by Vanessa219** [comment]
缩紧的话屏幕本身就小，很容易显示不全

**Comment by gdy106** [comment]
> 缩进的话屏幕本身就小，很容易显示不全。

可以考虑不缩进或者只有当前文档层缩进。但是竖排版是必须的，文档名非常长的情况下完全可以换行，因为这是竖屏手机页面，上下滑动完全没有负担的。

**Comment by Vanessa219** [comment]
你说的是 https://github.com/siyuan-note/siyuan/issues/2613 这个需求么？

**Comment by gdy106** [comment]
> 你说的是 #2613 这个需求么？

不是，引用里举例的vscode界面是需要鼠标悬浮到文档上才能看到路径，在手机端这种增加点击操作的交互设计不合适。
我仅仅指可以删掉缩进，避免层级太深的文档不方便看。

**Comment by Vanessa219** [comment]
你的意思是把zhe yi hang这一行分成四行显示么？
<img width="471" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/e3289f7d-15a0-4105-861c-29eacae781c8">

**Comment by gdy106** [comment]
> 你的意思是把这一行分成四行显示么？
> <img alt="image" width="471" src="https://user-images.githubusercontent.com/970828/255062422-e3289f7d-15a0-4105-861c-29eacae781c8.png">

是的，在手机上上下滑动比左右滑动要容易很多，要区分层级可以用字色、大小、粗细等方式区分，不一定要有缩进。

**Comment by Vanessa219** [comment]
这个目前和 PC 端是保持一致的，如果每个目录显示一行的话，点击跳转就会脱离这个文档，跳转到其他文档，而且如下所示，感觉有点奇怪。

<img width="398" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/4852f333-d9a9-49e2-99bd-b0bd7dd2faf2">

**Comment by gdy106** [comment]
我做的效果图是这样：
![思源手机端面包屑-统一缩进](https://github.com/siyuan-note/siyuan/assets/57566668/27a24703-d6c3-4efd-a865-ed737a1b252b)

上下级文档的列表不设置分隔线，非当前层级的文档统一用细体小字号灰色呈现，当前文档左侧蓝色引导线体现层级关系。文档内的层级（标题、列表、正文等）有分隔线，黑色字体常规字重，焦点块以加粗蓝色字体显示。
跳转上级文档的功能我觉得是可以有的，不过如果开发者认为不应该跳转，设置为点击无反应就可以了呀。

> 这个目前和 PC 端是保持一致的，如果每个目录显示一行的话，点击跳转就会脱离这个文档，跳转到其他文档，而且如下所示，感觉有点奇怪。
> 
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/970828/255136395-4852f333-d9a9-49e2-99bd-b0bd7dd2faf2.png">

**Comment by gdy106** [comment]
另外，如果要避免层级过深的文档占用屏幕，可以加一个默认当前文档在第一行的设定，手指下滑（屏幕上滑）才显示上级文档。
上级文档可以露出来半行，以便用户知道上面还有内容。

**Comment by Vanessa219** [comment]
可以不增加设定么？目前已经有太多的设定了。

**Comment by gdy106** [comment]
我只是建议，哪些能实现哪些不能实现肯定还是看你们啦。

> 可以不增加设定么？目前已经有太多的设定了。
