### ISSUE TITLE
虚拟引用未按预期生成

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![deba6a6ea565a6223bcf6562a916a695](https://github.com/siyuan-note/siyuan/assets/32903588/d42704b3-1c62-4aee-8e1c-686f9b14e0d9)
如图，下方有两个未生成虚拟引用
但是文档中是有的
![beed9861fc0a9e6c0e991ad78b7e587b](https://github.com/siyuan-note/siyuan/assets/32903588/8a731b44-0e91-46c2-951b-428766cdb1ca)
![a338fe5458ccf325fc132eb4cf762e93](https://github.com/siyuan-note/siyuan/assets/32903588/2b168e9a-25b9-478d-a6f5-c37ad818ca78)
- 手动点击了重建索引，还是不行
- 未对相关文本设置虚拟引用的忽略规则

### Expected result

按预期生成虚拟引用

### Version environment

```markdown
- Version: 2.9.5
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请在 设置 - 编辑器 中关闭再打开虚拟引用开关后看看是否有变化。

**Comment by TinkMingKing** [comment]
> 请在 设置 - 编辑器 中关闭再打开虚拟引用开关后看看是否有变化。

还是不行

**Comment by 88250** [comment]
恐怕得把库完整打包发我们看下才能定位问题了 845765@qq.com （资源文件 assets 文件夹不用打包），谢谢。

**Comment by TinkMingKing** [comment]
突然发现，对 pdf 的引用不会生成虚拟引用，之前有引用是因为在其它地方有双链引用，所以应该是没有问题的，我理解岔了，关问题了我
