### ISSUE TITLE
When there are nested container blocks, the breadcrumb displays incorrectly.

### ISSUE THREAD

**Issue by why8023** [siyuan-note/siyuan#8735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/22267652/61ae8f21-8679-4b7b-98c8-cd13f11c3a52

1. 列表块里面嵌入引述块时, 最里层的容器块如果只有一个段落块时, 左侧块标是不会显示引述块的块标
2. 列表块里面嵌入引述块时, 面包屑没有显示引述块
3. 引述块里面嵌入列表块时, 左侧块标能正常显示, 但是面包屑, 不显示引述块, 很奇怪
4. 其他容器块(超级块等)也会出现类似的问题
---
1. When a quote block is embedded in a list block, the left block label does not show the block label of the quote block if the innermost container block is only a paragraph block.
2. when a quote block is embedded in a list block, the breadcrumbs do not show the quote block.
3. when embedding a quote block in a list block, the left block tag can be displayed normally, but the breadcrumb does not show the quote block, which is very strange.
4. Other container blocks (super blocks, etc.) will have similar problems.

### Expected result

嵌套容器块时,正确显示块标
When nesting container blocks, the block tags should be displayed correctly.

### Version environment

```markdown
- Version: 2.9.5
- Operating System: macOS 13.4.1
- Browser (if used):
```

### Log file

这个应该不用吧

**Comment by 88250** [comment]
只是特意做的优化，目的是简化面包屑路径。

**Comment by 88250** [comment]
不加选项了，见谅。

**Comment by why8023** [comment]
<img width="577" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22267652/135af23a-686b-4df0-95fc-d27049ca18f0">
<img width="569" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22267652/e8c94f1d-675d-47af-b0ef-af323458b90a">


D大, 这个也是优化吗? 列表项有子列表项的时候,引述块的块标就消失了

**Comment by why8023** [comment]
列表项嵌入超级块时
<img width="195" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22267652/0534d167-2408-4724-a7e9-721ca9187c94">
<img width="214" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22267652/965a40d0-9ae9-4904-8a8c-435f4e8714cc">
---
列表项嵌入列表项时
<img width="206" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22267652/2f860769-07a0-4d3b-ae7c-c0e191f18586">
<img width="226" alt="image" src="https://github.com/siyuan-note/siyuan/assets/22267652/992acbfd-8eea-492b-89ba-8048f8d7788f">
这应该是个bug吧😂

**Comment by 88250** [comment]
不是 bug。

**Comment by why8023** [comment]
不好意思, D大, 再啰嗦几句
可以问一下:这样处理是出于什么考虑的吗?


面包屑这样处理可以理解, 容器块嵌套会导致面包屑过长, 实际有效信息只有段落块, 可以处理掉容器块


但是, 内容块左边块标这个为什么要这样处理呢? 如果这么处理, 最里层的容器块无法被选中, 无法聚焦, 想要删除只能全部删除外层容器块, 最里层的容器块完全没作用.


嵌套容器块本来是思源的优势, 其他笔记软件都不具备, 这样处理完全削弱了这个优势.

**Comment by 88250** [comment]
都是为了简化，之前这个问题讨论过，我一下找不到原内容了，你搜搜看吧。



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 13, 2023 11:18 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] When there are nested container blocks, thebreadcrumb displays incorrectly. (Issue #8735)




 
不好意思, D大, 再啰嗦几句
 可以问一下:这样处理是出于什么考虑的吗?
 
面包屑这样处理可以理解, 容器块嵌套会导致面包屑过长, 实际有效信息只有段落块, 可以处理掉容器块
 
但是, 内容块左边块标这个为什么要这样处理呢? 如果这么处理, 最里层的容器块无法被选中, 无法聚焦, 想要删除只能全部删除外层容器块, 最里层的容器块完全没作用.
 
嵌套容器块本来是思源的优势, 其他笔记软件都不具备, 这样处理完全削弱了这个优势.
