### ISSUE TITLE
SiYuan "Failed to get kernel serve port"

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

SiYuan sometimes launches without any problem and sometimes shows the message "Failed to get kernel serve port". Not sure what the issue is. I think it should either show the error message everytime or always work without any issue because I am not making any change to network or any permissions.

### Expected result

SiYuan should launch properly.

### Version environment

```markdown
- Version: 2.9.5
- Operating System: macOS 12.6
```

### Log file

```
E 2023/07/12 09:40:37 working.go:417: lock workspace [/Users/someName/Documents/fm/0200-notes/siyuan-notes] failed
W 2023/07/12 09:40:40 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/07/12 09:40:55 process.go:76: active UI proc count [6]
W 2023/07/12 09:41:25 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/07/12 09:41:40 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/07/12 09:41:55 process.go:76: active UI proc count [1]
W 2023/07/12 09:42:25 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
E 2023/07/12 09:42:28 working.go:417: lock workspace [/Users/someName/Documents/fm/0200-notes/siyuan-notes] failed
W 2023/07/12 09:42:40 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/07/12 09:42:55 process.go:76: active UI proc count [6]
```

**Comment by fenilgmehta** [comment]
After quitting SiYuan, and on searching SiYuan in `Activity Monitor > CPU tab`, `SiYuan-Kernel` was the only SiYuan process running. On quitting it from `Activity Monitor`, the app launched successfully. Any idea why `SiYuan-Kernel` had not stopped properly when the whole app was quit?

**Comment by 88250** [comment]
Under normal circumstances, closing the SiYuan interface will exit the SiYuan kernel process by the way. If there is no interface, the SiYuan kernel will automatically exit after about 1 minute under normal circumstances on the desktop.
