### ISSUE TITLE
Tooltip text not visible

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The tooltip text is not visible
<img width="96" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/a08357e8-9e1f-4fd7-8dbe-b468cd137ac3">
<img width="170" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/ab750431-95e2-49ea-b686-c2e5d0c0d66a">
<img width="203" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/b6e6640d-ff56-47fd-bcc6-717d9801676e">

### Expected result

Text should be shown like previous versions

### Version environment

```markdown
- Version: 2.9.5
```

### Log file

\-

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/f15303c1-db88-4e74-bd9c-88b17390b4a9)

![image](https://github.com/siyuan-note/siyuan/assets/873584/680f2b83-1230-4f22-8d27-13cd7e9e4a3e)

![image](https://github.com/siyuan-note/siyuan/assets/873584/7c84c34e-ad39-42c9-9ccf-1f857de7c84f)

I tested it with the default theme here.

Ref https://liuyun.io/article/1689091954220
