### ISSUE TITLE
To standardize the tabs opening method and optimize the logic for opening tabs

### ISSUE THREAD

**Issue by aooaa** [siyuan-note/siyuan#8738]
### In what scenarios do you need this feature?

In Siyuan, the default behavior for opening a note is to open it in a new tab, which is acceptable. However, there is an option in Siyuan's settings to open notes in the current page. This option has an additional condition where if the page has been edited, it will still open in a new tab. This design seems redundant. A better approach could be to follow the logic of browser tab behavior, where a single click opens a link in the current page and using the middle mouse button or Ctrl+left click opens it in a new tab. This approach would be simple and clear.

By adopting Siyuan's default design of opening notes in the current page, it becomes difficult to achieve the following scenario: suppose I made some edits to a page, but I still want to open a new page within the current tab. This limitation also leads to Siyuan quickly filling up with numerous tabs, which can be problematic.

To optimize the logic of opening new tabs, it would be beneficial to only create a new tab when the user explicitly requests it. This way, the issue mentioned earlier can be resolved, and it would eliminate the need for an additional setting to control the maximum number of open tabs. Since the tabs are created by the user's deliberate action, there won't be a situation where an excessive number of tabs clutter the tab bar, causing confusion during usage.

### Describe the optimal solution

Taking inspiration from browser settings, consider setting the default behavior to open notes in the current tab while enabling middle-click/ctrl+left click to open notes in a new tab by default.

### Describe the candidate solution

To simplify the settings, consider removing the extra conditional check and enforcing all notes to open in the current tab once the option is enabled. This eliminates the possibility of different outcomes for the same command, which can be confusing. Then, adopt the solution of using middle-click/ctrl+left click as the option to force opening in a new tab.

This approach is straightforward, but it does introduce some redundancy. Without the option to open in the current tab, both single-click and middle-click would result in opening in a new tab, creating duplicated functionality. Therefore, Solution 1 from before remains a more concise and straightforward option.

**Comment by yylicon** [comment]
是的是的，浏览器那种才是很舒服的

**Comment by 88250** [comment]
Solution 1 will have some conflicts because Ctrl+Click is multi-select. Also, it's inconvenient on devices that don't have a middle button.

From the current feedback, the setting item opened in the current tab is a compromise solution. If you want to fix it, you can double-click it on the Tab, so that it will open a new tab instead of replacing the current tab.

We are not currently considering changing this point, thanks for the feedback.
