### ISSUE TITLE
Pandoc template for exporting docx

### ISSUE THREAD

**Issue by BeneBladeCannon** [siyuan-note/siyuan#8740]
思源笔记的pandoc导出word，能否自定义输出word的模板？

### In what scenarios do you need this feature?

如题所示，我在思源笔记中整理了一些资料文件。现在因为工作原因，需要将其导出为word格式。

但是思源笔记目前使用代码里面调用pandoc的方式，导致无法找到默认的模板对其进行修改或指定特定的模板，使得每次导出word还需要大量的时间修改word的格式，最后发现还不如直接不使用导出功能，直接复制效率高。

### Describe the optimal solution

希望软件能够开放pandoc的默认输出模板修改功能。

**Comment by Achuan-2** [comment]
+1

**Comment by yalidabuda** [comment]
+2

**Comment by pth2000** [comment]
同上 其实可以加一个pandoc附加参数的功能，或者围绕那些参数封装一下也好😉

**Comment by 88250** [comment]
各位能提供一个模板给我们测试吗？

**Comment by 88250** [comment]
不用麻烦各位提供了，我生成了一个模板测试了，大概知道怎么用了。
