### ISSUE TITLE
Add `Copy text * ` hotkey

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#8742]
https://ld246.com/article/1689152586608

**Comment by gdy106** [comment]
反馈问题，选中文本后使用复制文本*的快捷键失败，粘贴后的文本不带有引用的*。只有在未选中任何文本的情况下使用该快捷键才能复制*成功。

**Comment by 88250** [comment]
@gdy106 抱歉，我没看懂你说的操作，麻烦截图或者录屏，谢谢。

**Comment by gdy106** [comment]
@88250 
已录屏，就是说选中文本后按快捷键使用`复制为文本*`功能，实际上粘贴时不会带引用的星号。上面那条把星号识别成斜体了……

https://github.com/siyuan-note/siyuan/assets/57566668/6d377de7-6ecb-456a-84ae-330188090980

**Comment by gdy106** [comment]
@88250 我换了个快捷键，显示的情况一样。

https://github.com/siyuan-note/siyuan/assets/57566668/7aa953d3-a8ae-4375-9aca-339bbd22f036

**Comment by 88250** [comment]
新工作空间测试看看。



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 31, 2023 19:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Add `Copy text *` hotkey (Issue #8742)




 
@88250 我换了个快捷键，显示的情况一样。
 
https://github.com/siyuan-note/siyuan/assets/57566668/7aa953d3-a8ae-4375-9aca-339bbd22f036

**Comment by gdy106** [comment]
> 新工作空间测试看看。

两次录屏都是在新工作空间里，没有开通集市。

**Comment by 88250** [comment]
我这里真的无法重现。

**Comment by gdy106** [comment]
@88250 我在论坛发帖放了两个对比录屏，麻烦D大再看一下。
https://ld246.com/article/1693566506800
也和群友确认过可以重现。之前可能没表达清楚意思，我说的是在选中文字的情况下，使用快捷键启用`复制为文本*`功能，然后粘贴出来的文本末尾不会带引用的星号，即`文本*`。
类似的用`Ctrl+Shift+c`复制块引用功能和这个功能应该操作逻辑是一致的，选中文字后按`Ctrl+Shift+c`是能复制选中的文字为锚文本的块引用的，那么选中文字后用快捷键启用`复制为文本*`功能应该也能粘贴出`文本*`。

**Comment by 88250** [comment]
> @88250 我在论坛发帖放了两个对比录屏，麻烦D大再看一下。 https://ld246.com/article/1693566506800 也和群友确认过可以重现。之前可能没表达清楚意思，我说的是在选中文字的情况下，使用快捷键启用`复制为文本*`功能，然后粘贴出来的文本末尾不会带引用的星号，即`文本*`。 类似的用`Ctrl+Shift+c`复制块引用功能和这个功能应该操作逻辑是一致的，选中文字后按`Ctrl+Shift+c`是能复制选中的文字为锚文本的块引用的，那么选中文字后用快捷键启用`复制为文本*`功能应该也能粘贴出`文本*`。

@Vanessa219

**Comment by 88250** [comment]
@gdy106 https://github.com/siyuan-note/siyuan/issues/9093
