### ISSUE TITLE
Outline block Copy Sticking Bug

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#8743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

粘粘大纲列表时的一些问题，主要操作步骤是首先在笔记中有两个大纲，然后由大纲2剪切粘粘到大纲1中的问题
数据准备，同时已禁用所有插件、主题、挂件等

![image](https://github.com/siyuan-note/siyuan/assets/42575324/7e06f28f-fa71-4d62-929a-11e43b52e7e2)

情况一：直接在大纲1项目的后面粘粘
![image](https://github.com/siyuan-note/siyuan/assets/42575324/d220134d-bc89-4223-a036-0dfd78c30abf)
情况二：大纲1空列表项粘粘
![image](https://github.com/siyuan-note/siyuan/assets/42575324/009175b9-284e-466b-a0b6-3457836fe063)
情况三，正常，带列表层级一起粘粘
![image](https://github.com/siyuan-note/siyuan/assets/42575324/6d982987-c90c-4931-b78a-a70e6f0b1020)

### Expected result

都应该符合正常的大纲结构的插入

### Version environment

```markdown
- Version: 2.9.5
- Operating System: windonws 11
- Browser (if used):
```

### Log file

略

**Comment by Vanessa219** [comment]
好像无法重现，是这样操作的吗？
https://github.com/siyuan-note/siyuan/assets/970828/8933fa59-327f-45ae-b3be-0e893b53241c

**Comment by hackerhui** [comment]
@Vanessa219 Ctrl+X Ctrl+V

**Comment by Vanessa219** [comment]
在列表2中 ctrl+x 会变成这样，无法复制整个列表
<img width="311" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/b14a789b-f52b-487b-91f6-f5eacf704983">

**Comment by hackerhui** [comment]
> 在列表2中 ctrl+x 会变成这样，无法复制整个列表
> 
> <img width="311" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/b14a789b-f52b-487b-91f6-f5eacf704983">
> 
> 
是的

**Comment by 88250** [comment]
```markdown
* * foo
```

这是符合预期的结构，不考虑调整了，感谢反馈。
