### ISSUE TITLE
Full page embed

### ISSUE THREAD

**Issue by ThinkSalat** [siyuan-note/siyuan#8744]
### In what scenarios do you need this feature?

I love to organize my pages like portals. For example, for a project, I'll have my main project page. Then I'll have a features page, a technical page, a tasks page, etc.

Project Main Page:
  Features page:
     Feature 1:
     Feature 2:
     Feature 3:
  Goals:
  Tasks:
  Technical resources:

For me, the ideal way to organize these is for each to be their own page, embedded into the main project page. This way there is no changing of context: I am always on my main project page until I want to really go specific for a feature or other subpage. 

The way SiYuan is handling block embeds is beautiful. It's actually my favorite transclusion system I have discovered in any PKMS. However only being available for blocks is limiting to its potential!

### Describe the optimal solution

Ideally I could embed an entire page the same way I can embed a block. 

Going even further, being able to resize the embed - for example you can change the width of an embedded block. It would also be nice to collapse the embed to a smaller preview. 

It would also be great to give it a set height - maybe something like number of lines - so you could have a page embed and tell it to only take up 5 lines of space, but you're still able to scroll through the entire embedded page. 

### Describe the candidate solution

Reuse what block embeds use but for entire pages. Allow to set the height of an embed by number of lines, similar to how you can set the width of an embed using a percentage. Allow the entire page embed to be scrolled through if the height is set. This would act like overflow: scroll in css. Allow a page embed to be collapsed to a single line, or a card like page preview.

**Comment by 88250** [comment]
Maybe it's possible to get this effect with block custom attributes + CSS snippet.

**Comment by ThinkSalat** [comment]
The primary feature would be to embed a page - for example I have a page called Travel. When I open the embed menu and search for travel, that page doesn't show up, only blocks containing the word travel. I would like to have full pages be embeddable. To start, I at least need to be able to select a page to embed. Is this possible?

**Comment by 88250** [comment]
Please check the settings:

![image](https://github.com/siyuan-note/siyuan/assets/873584/9d7aa3ea-c01f-4bee-8e4f-b92590000392)

**Comment by ThinkSalat** [comment]
I see! Well that's terrific! I already had that checked, however I checked and unchecked it and I was able to embed a page directly. Fantastic! Thank you
