### ISSUE TITLE
希望增加目录或文档的加密功能

### ISSUE THREAD

**Issue by hello2099** [siyuan-note/siyuan#8747]
### In what scenarios do you need this feature?

有一些文档，比如记录了一些密码，需要加密一下。

### Describe the optimal solution

希望增加目录或文档的加密功能，还是很实用的。

**Comment by 88250** [comment]
你好，这个暂时不考虑了，请参考 https://ld246.com/article/1689224966405

**Comment by TCOTC** [comment]
https://github.com/siyuan-note/siyuan/issues/9800
