### ISSUE TITLE
点击md文件打开思源，只显示这个文件【用户体验】【隐私保护】

### ISSUE THREAD

**Issue by o-ut-man** [siyuan-note/siyuan#875]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
使用everything等桌面搜索工具，直接搜文档名字打开对应文档

现在即使通过文档打开思源，还是会显示上一次退出时的文件树配置，而不是显示当前打开的文档，相当不方便。
从隐私角度来说，当你点开其他md文件时，却把你之前的文档状态暴露在别人面前。
### 描述最优的解决方案 Describe the optimal solution
点击思源客户端图标打开的情况下，才读取上一次退出时的文件树配置。
点击md文件打开的情况下，不读取文件树配置，退出时也不保存文件树配置。

**Comment by 88250** [comment]
你好，思源不支持直接打开 .md 文件的，需要先讲文件夹打开为笔记本以后才能使用。
