### ISSUE TITLE
"[["块引用搜索时排除指定笔记本或文档

### ISSUE THREAD

**Issue by HopeLHP** [siyuan-note/siyuan#8750]
### In what scenarios do you need this feature?

使用简悦等阅读标注工具导入的原文或标注文本，使得在块引用[[搜索块时，出现大量未经处理的原文内容（或者原文内容经过标注提取形成新的文档导致重复文档的出现），导致需要更多时间才能找到目标块。
如果在搜索时，排除指定笔记本下的全部文档，或指定的文档，或排除某个关键词，那么可以增强在块引用方面的体验细节，减少搜索的消耗。

### Describe the optimal solution

可以在设置-编辑器中增加相关设置。
目前obsidian有类似的忽略文件的设置，如图
<img width="514" alt="image" src="https://github.com/siyuan-note/siyuan/assets/70339118/f0fa66e4-fb93-43f2-8843-216326aeeffa">
目前siyuan的虚拟引用有关键词排除列表。
<img width="1057" alt="image" src="https://github.com/siyuan-note/siyuan/assets/70339118/ef6c5db5-7f58-40a9-95f3-531d67f6b262">

**Comment by 88250** [comment]
目前有两个替代方案：

* 使用全局搜索，然后复制块引
* 将不需要纳入搜索的笔记本关闭

块引搜索加入排除目前暂时不考虑了，如果后续需要的人多再考虑，感谢反馈。
