### ISSUE TITLE
为什么下载最新版的siyuan到服务器上部署还是旧版的？是我的操作系统内核问题吗

### ISSUE THREAD

**Issue by Mr-KouZhe** [siyuan-note/siyuan#8751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

111

### Expected result

111

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
111
```

### Log file

111

**Comment by mozhux** [comment]
应该是源不对

**Comment by 88250** [comment]
可以试下带版本号下载。
