### ISSUE TITLE
MacOS hangs on first launch when selecting workspace

### ISSUE THREAD

**Issue by benwaco** [siyuan-note/siyuan#8754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When choosing "select" the app hangs after closing a folder.

### Expected result

App proceeds as normal.

### Screenshot or screen recording presentation

https://share.cleanshot.com/m1pDJGNvCV2qN0FWJ5dT

### Version environment

```markdown
- Version: 2.9.5
- Operating System: 14.0 Beta (23A5286i)
- Browser (if used):
```

### Log file

no log file

**Comment by 88250** [comment]
Please do not select the files located in the iCloud sync path, for example, try the ~/SiYuan/ folder.
