### ISSUE TITLE
Attribute View date column calculate

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8757]
* [x] Date https://github.com/siyuan-note/siyuan/issues/8692
  * Count all
  * Count values
  * Count unique values
  * Count empty
  * Count not empty
  * Percent empty
  * Percent not empty
  * Earliest
  * Latest
  * Range

**Comment by Achuan-2** [comment]
日期列能不能只选择日期，现在必须还要选时间

**Comment by 88250** [comment]
时间那里应该可以不选的吧，直接确定。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 24, 2023 13:12 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Attribute View date column calculate (Issue#8757)




 
日期列能不能只选择日期，现在必须还要选时间

**Comment by Achuan-2** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/60436214/c6af16cb-d5b1-4cdd-9caa-c77b2aa03474)
我一点击，就自动显示当前时间了

**Comment by Achuan-2** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/60436214/c6af16cb-d5b1-4cdd-9caa-c77b2aa03474)
我一点击时间列想要填写，就自动显示当前时间了
![image](https://github.com/siyuan-note/siyuan/assets/60436214/28815986-9490-456b-97b4-ce03c2c84849)

**Comment by 88250** [comment]
暂时先这样吧，后面看反馈再考虑调整了。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 24, 2023 17:42 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Attribute View date column calculate (Issue#8757)




 

 我一点击，就自动显示当前时间了
