### ISSUE TITLE
改进文件树上的文档拖拽转换标题时的交互

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#876]
* 支持位置（上或下）
* 改进样式

**Comment by deerainw** [comment]
v0.5.46 这个版本文档块转标题块时，标题的升降级规则被搞乱了

这是转换前的文档块：

![image](https://user-images.githubusercontent.com/32661922/103391216-30eae000-4b53-11eb-9ba8-5d090bd097c6.png)

这是转换成标题块之后：

![image](https://user-images.githubusercontent.com/32661922/103391273-8cb56900-4b53-11eb-8a4d-0ed08a053366.png)

上面的「秦朝」在转换成标题块后应该变为 H1 才对。因为下面的「重刑主义」「罪名」原本是隶属于「秦朝」的，它俩是 H2 那么「秦朝」应该是 H1

---

如果把文档块拖动到 H2 标题的下方，又有另外的问题，原本的文档标题变成了 H4，比隶属于它的标题还低一级：

![image](https://user-images.githubusercontent.com/32661922/103391463-9ee3d700-4b54-11eb-903a-fc1e843804dd.png)

---

把文档块拖动到 H3 标题下方的时候，原本的文档标题变成了 H6，比隶属于它的标题还低两级：

![image](https://user-images.githubusercontent.com/32661922/103391536-f1bd8e80-4b54-11eb-83ea-5527cf748b46.png)

---

感觉问题可能出在处理文档块标题的代码上......

**Comment by 88250** [comment]
@deerainw 收到，下个版本修复。
