### ISSUE TITLE
katex宏定义问题

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如果我使用了katex宏定义，宏定义的设置项不会被同步，在其他设备上，公式就会报错，如果要在每个设备上自行设置，显然是麻烦且不好用，极大增加了操作成本

### Expected result

1. katex宏定义设置项支持同步
2. 或者，输入宏定义代码后，在保存后自动替换为自定义的代码，以确保使用宏定义后，同步到其他设备依旧能够正常显示

### Version environment

```markdown
- Version: 2.9.5
- Operating System: win10
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个暂时没有办法了，配置不同步是设计如此。直接替换公式内容可能风险太高了，还是保持现有设计吧，感谢反馈。
