### ISSUE TITLE
Add template type column to Attribute View

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8766]

**Comment by zxhd863943427** [comment]
D大，这个是什么功能？

**Comment by 88250** [comment]
表格视图列类型 - 模板，目前还在考虑设计，大致就是类似于 Notion Database 中的公式列的功能，使用模板语法，列属性作为模板变量填充。

**Comment by ttimasdf** [comment]
钉钉多维表格有两种类似的功能，
一个是引用列，将一个列链接到另一个表格的一列并显示其中一行的值，
一个是聚合列，引用另一个表中另一个列的值或者整列所有行的值并进行处理（取极值、计算平均数、去重等等）

**Comment by 88250** [comment]
结合自定义属性测试的示例：

![image](https://github.com/siyuan-note/siyuan/assets/873584/7d975fb3-9a97-4cab-a132-8ed583666be8)

**Comment by zxhd863943427** [comment]
无法使用数据库的属性吗？

**Comment by 88250** [comment]
嗯，还不支持使用其他列值，后面考虑一下。

**Comment by zxhd863943427** [comment]
感觉看上去像是直接把思源模板的模板语法给搞过来了？所以能够使用相同的函数吗？

**Comment by 88250** [comment]
嗯，和模板语法一样，不过思源特有那些内置函数没有支持，sprig 的都支持。

**Comment by zxhd863943427** [comment]
这个感觉还是自己造一套解析成模板语法的轮子比较好……思源的模板语法特别难写，感觉不是一般人驾驭的了的，而且感觉上也做不了定义变量。
里面可以继续使用sprig模板，但外面还是要包装的简单一点。

**Comment by zxhd863943427** [comment]
我对于他的期待是能够像excel那样写的简单😂

**Comment by 88250** [comment]
主要是想和模板用一套语法，一致一些用户也方便。



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 1, 2023 19:07 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Add template type column to Attribute View(Issue #8766)




 
我对于他的期待是能够像excel那样写的简单😂

**Comment by zxhd863943427** [comment]
老实说，思源的模板语法是我用过可能并不是很友好的那几个。

从集市里就可以看出来，他比插件和主题的数量少太多了……

模板只用写一次，以后就可以少写，还勉强能忍受，但是模板列应该是要频繁修改的，真的有必要使用更加友好一点的语法。

**Comment by frostime** [comment]
模板语法真的不是什么很好用到的东西。而且本身 sprig 也不是什么特别流行的。

我还是废了点力气找到了 sprig 的文档之后才勉强理解要怎么用它，对普通用户来讲，这玩意就是天书。

我直接搜索 sprig 甚至都找不到这东西的相关信息。
![image](https://github.com/siyuan-note/siyuan/assets/27268127/473b0595-3768-46f7-9da3-b1fb73cc853e)


必须要添加一个 golang 关键词才能找到他的文档，可想这玩意对普通用户来讲到底有多难懂。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/89d55b14-8233-483b-a5c0-eb4983f94632)

**Comment by frostime** [comment]
我的建议是，在 sprig 的语法基础上，自定义几个常用但是简单的语法。
这样常见的需求用思源自定义的语法，更复杂的需求就让用户学习 sprig 去。这样学习曲线不至于那么陡峭。

对了，建议把 sprig 的文档链接放到用户帮助手册里面，普通人根本搜索不到。

http://masterminds.github.io/sprig/

**Comment by 88250** [comment]
帮助文档里面我记得有写。



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 2, 2023 00:17 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Add template type column to Attribute View(Issue #8766)




 
我的建议是，在 sprig 的语法基础上，自定义几个常用但是简单的语法。
 这样常见的需求用思源自定义的语法，更复杂的需求就让用户学习 sprig 去。这样学习曲线不至于那么陡峭。
 
对了，建议把 sprig 的文档链接放到用户帮助手册里面，普通人根本搜索不到。
 
http://masterminds.github.io/sprig/

**Comment by mozhux** [comment]
我也觉得不知道如何下手，在pdf页脚出来的时候我去研究过一次。。也不知道怎么写

**Comment by 88250** [comment]
v2.10.8 里面包含了 https://github.com/siyuan-note/siyuan/issues/9327 修改，即其他列也能用于模板变量了。

**Comment by 88250** [comment]
模板列中使用自定义属性语法有所调整 https://github.com/siyuan-note/siyuan/issues/9401
