### ISSUE TITLE
I want the application to be able to sense if the data in the data changes when SiYuan Notes is opened.

### ISSUE THREAD

**Issue by zero-face** [siyuan-note/siyuan#8770]
### In what scenarios do you need this feature?

应用打开的情况下，希望能够实时感知data中的数据变化

### Describe the optimal solution

resolved

**Comment by 88250** [comment]
抱歉，我没看明白你的意思，请详细描述。

**Comment by zero-face** [comment]
当我们打开应用之后，如果data文件中的笔记内容在其他地方有改动，打开的应用是不能实时感知到的。必须重启应用进行加载。我希望应用能够支持这种实时感知变化的功能

**Comment by zero-face** [comment]
当我们打开应用之后，如果data文件中的笔记内容在其他地方有改动，打开的应用是不能实时感知到的。必须重启应用进行加载。我希望应用能够支持这种实时感知变化的功能

**Comment by zero-face** [comment]
> 抱歉，我没看明白你的意思，请详细描述。

当我们打开应用之后，如果data文件中的笔记内容在其他地方有改动，打开的应用是不能实时感知到的。必须重启应用进行加载。我希望应用能够支持这种实时感知变化的功能

**Comment by zero-face** [comment]
> 抱歉，我没看明白你的意思，请详细描述。

笔记内容应该是能够实时感知的，但是新增笔记本就不能实时感知了

**Comment by frostime** [comment]
反对一下，sy文件本来就不应该被用户更改。
你不能把它理解为 markdown 的源码模式。它并不是单纯的笔记文件，而是包括了所有结构在内的抽象语法树的定义，这东西本来就应该是对用户透明的。

**Comment by 88250** [comment]
这个不考虑了，外部变更文件请通过内核 API 操作，不要直接修改数据文件，感谢反馈。
