### ISSUE TITLE
Improve find replace

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在思源中进行正则替换，能正常检索到内容，但是替换失效

### Expected result

正常进行正则替换

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/79925e7b-5884-4673-b46b-91258545978b

### Version environment

```markdown
- Version: 2.9.5
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12071444/siyuan.log)

**Comment by 88250** [comment]
录屏中的替换是准备将什么替换成什么？请将输入和期待的输出描述清楚，谢谢。

**Comment by 88250** [comment]
我这里测试待替换文本 `阿布一姆贝勒神(彩插一2)`，正则 `([^一])一([^一])`，替换结果 `阿布-姆贝勒神(彩插-2)`，和[这里](https://tool.oschina.net/regex/)的在线工具测试结果一致。

![image](https://github.com/siyuan-note/siyuan/assets/873584/5bc2375c-c1cc-4d7d-a734-4cd5f693d49f)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by gdy106** [comment]
> 我这里测试待替换文本 `阿布一姆贝勒神(彩插一2)`，正则 `([^一])一([^一])`，替换字符串 `$1-$2`，替换结果 `阿布-姆贝勒神(彩插-2)`，和[这里](https://tool.oschina.net/regex/)的在线工具测试结果一致。
> 
> ![image](https://user-images.githubusercontent.com/873584/254591688-5bc2375c-c1cc-4d7d-a734-4cd5f693d49f.png)
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

我是用图片转文字，所以识别出来所有的短横-变成了破择号里的长横—，这是我进行替换的原因。
为了修正，我查找的是—，要替换成-，但是视频里很明显了，我点击替换后实际上文本并没有发生任何改变，思源里文本还是 `阿布一姆贝勒神(彩插一2)`，而没有显示为替换结果 `阿布-姆贝勒神(彩插-2)`。

**Comment by gdy106** [comment]
> 我这里替换正常：
> 
> ![image](https://user-images.githubusercontent.com/873584/254611215-54714e7e-5a26-47a2-8803-05444f0f9ccc.png)

我再测试了，单个替换是可以正常替换的，但是点击全部替换是无效的，显示执行完成替换，但是实际上并没有对文本做出改变。

**Comment by 88250** [comment]
我这里重现不了，使用的是全部替换。

**Comment by 88250** [comment]
你把可以重现问题的工作空间打包上传一下吧，谢谢。

**Comment by gdy106** [comment]
> 你把可以重现问题的工作空间打包上传一下吧，谢谢。
[思源暂存-20230719234545.zip](https://github.com/siyuan-note/siyuan/files/12097293/-20230719234545.zip)
我上个录屏的工作空间连集市都没开，很迷惑为啥会出现这种问题。
日志顺便也传一下：
[siyuan.log](https://github.com/siyuan-note/siyuan/files/12097422/siyuan.log)

**Comment by gdy106** [comment]
就很奇怪，我在日常使用的工作空间里，是单个替换能生效，但是全部替换失效。
视频如下：

https://github.com/siyuan-note/siyuan/assets/57566668/3dde2c32-1ded-4813-b23e-dee7bcf9e9a9

在测试用的连集市都没有开的干净工作空间里反而是连单个替换都无效了。

**Comment by 88250** [comment]
你这里多了个空格吧？

![image](https://github.com/siyuan-note/siyuan/assets/873584/68478ec3-2c23-4ee7-b091-775dea1d1ab6)

**Comment by 88250** [comment]
下个版本会自动剔除首尾空格。

**Comment by gdy106** [comment]
> 下个版本会自动剔除首尾空格。

在新工作空间中测试，去掉查找行首的空格后正常替换了：

https://github.com/siyuan-note/siyuan/assets/57566668/061210f5-a4ad-45ed-902f-75d1a04945cf

这里有个bug，正常而言，因为我查找里有多余的空格，查找结果中根本不应该检索到任何匹配的结果，但是它显示了我预期的匹配内容，替换也显示成功，只是没能应用替换结果，这里逻辑有问题。
而且我是从旧工作空间里复制过来的查找原文，说明是空白的查找输入栏里默认就有一个空格，才导致我粘贴过去的时候有未发现的空格，这点我觉得也需要优化。因为确实有可能有的人就是需要查找空格啊，如果会被自动删除的话，那就只能用`\s`来指代空格了吧？

目前问题依旧没有解决，因为我在常用的工作空间中用同样的文本，在确保没有多余空格的情况下依旧替换失败，我不明白两边为什么会有这样的区别：

https://github.com/siyuan-note/siyuan/assets/57566668/2c19e49d-5fb5-464c-bd9d-b14a8489b816

**Comment by 88250** [comment]
等晚上我们发布一个 dev 版本再看看。



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 20, 2023 18:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve find replace (Issue #8771)




  
下个版本会自动剔除首尾空格。
  
在新工作空间中测试，去掉查找行首的空格后正常替换了：
 
https://github.com/siyuan-note/siyuan/assets/57566668/061210f5-a4ad-45ed-902f-75d1a04945cf
 
这里有个bug，正常而言，因为我查找里有多余的空格，查找结果中根本不应该检索到任何匹配的结果，但是它显示了我预期的匹配内容，替换也显示成功，只是没能应用替换结果，这里逻辑有问题。
 而且我是从旧工作空间里复制过来的查找原文，说明是空白的查找输入栏里默认就有一个空格，才导致我粘贴过去的时候有未发现的空格，这点我觉得也需要优化。因为确实有可能有的人就是需要查找空格啊，如果会被自动删除的话，那就只能用\s来指代空格了吧？
 
目前问题依旧没有解决，因为我在常用的工作空间中用同样的文本，在确保没有多余空格的情况下依旧替换失败，我不明白两边为什么会有这样的区别：
 
https://github.com/siyuan-note/siyuan/assets/57566668/2c19e49d-5fb5-464c-bd9d-b14a8489b816

**Comment by gdy106** [comment]
我重启了一下思源，然后点了`清空查询条件`之后再和之前一样查找替换，居然成功了！这个操作昨天也重复过，不知道什么原因上次不行这次居然行了。迷惑。
那应该就只有前面那个首尾有空格能检索但不能替换的问题了（虽然我还是不懂什么导致两次情况的差别）。

> 等晚上我们发布一个 dev 版本再看看。

**Comment by gdy106** [comment]
已更新到2.9.7 dev-1，经测试，目前正则批量替换功能正常使用。不过正则模式下的查找结果不会像关键词模式下高亮关键词，在单个块内容比较多的情况下找关键词会比较麻烦，不知道能不能让正则模式和关键词模式一样高亮关键词。

> 等晚上我们发布一个 dev 版本再看看。

**Comment by 88250** [comment]
高亮目前实现不了。

**Comment by gdy106** [comment]
那只能遗憾了，展望一下以后

> 高亮目前实现不了。

**Comment by 88250** [comment]
首尾空格不再自动剔除 https://github.com/siyuan-note/siyuan/issues/9229

**Comment by Jasonsey** [comment]
@88250 我也遇到了这个问题，从notion导入的公式有问题，所以我需要手动去掉美元符号，所以执行了批量删除美元符号发现无效

![Image](https://github.com/user-attachments/assets/60b3261c-e620-4273-aa79-d49884f7a569)

选择了正则表达式。我的表达式写错了吗？
