### ISSUE TITLE
思源笔记启动后窗户非屏幕居中，而是在屏幕边缘，尤其在双屏场景下。

### ISSUE THREAD

**Issue by inolive** [siyuan-note/siyuan#8772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源笔记启动后窗户非屏幕居中，而是在屏幕边缘，尤其在双屏场景下。

### Expected result

单屏、双屏场景下，思源笔记启动后窗口在屏幕上居中。

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你好，这是按照上一次关闭的位置记录的。

**Comment by inolive** [comment]
实际不是，我是双屏显示器，每次启动都是默认位置，在主屏幕左边。

**Comment by inolive** [comment]
又测试了多次，所有版本都相同，关闭方式不同，只会记录主屏幕还是副屏幕，思源窗口的大小和位置均会是默认的大小和左上角位置。

**Comment by 88250** [comment]
有一些判断，如果窗口宽度或者高度大于主显示器宽度或高度，则会将窗口位置重置到左上角，大小使用默认大小（主显示器大小 * 0.8）。

**Comment by inolive** [comment]
两个显示器同规格同型号

**Comment by 88250** [comment]
窗口的大小呢，比如窗口太大可能会超出当个显示器的范围，该情况下也会重置。

**Comment by gdy106** [comment]
如果窗口上下高度占满全屏（只有高度，不是最大化），重启思源的时候也会重置窗口。

**Comment by 88250** [comment]
@gdy106 高于屏幕的工作区（比如占到了任务栏）的话会重置。

**Comment by inolive** [comment]
这些情况都没有，窗口尺寸都远小于屏幕。

**Comment by 88250** [comment]
暂时找不到问题了，后续我们会留意，谢谢。
