### ISSUE TITLE
image and video need a small feature to reset to default size

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8773]
### In what scenarios do you need this feature?

when the image is dragged to a unnormal size, I don't know the default size, I can't restore it

### Describe the optimal solution

provide this feature

**Comment by royc01** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/38906705/8b040e02-331a-44dc-bfff-9d0ea2ffcbb7)

**Comment by zhoutaosheng** [comment]
> ![image](https://user-images.githubusercontent.com/38906705/254132850-8b040e02-331a-44dc-bfff-9d0ea2ffcbb7.png)

Get it
