### ISSUE TITLE
a modest proposal: need a function to copy and paste the title image

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8776]
### In what scenarios do you need this feature?

I want to apply the title image of a page to another page, but there is no way to
1. get the image link of page title
2. then apply the image to anthor page

### Describe the optimal solution

provide the function, like copy and paste an image
which give me, `![image](assets/image-202307181xxxx.png)`

**Comment by 88250** [comment]
Consider implementing it through a plugin, thanks for the suggestion.
