### ISSUE TITLE
希望提供设置图片的默认宽度，每次手动调图片，很麻烦，虽然有固定值，当依旧需要每张图片手动调整

### ISSUE THREAD

**Issue by Joker-lkc** [siyuan-note/siyuan#8777]
### In what scenarios do you need this feature?

撰写笔记的时候，希望能够在设置页面配置

### Describe the optimal solution

希望能够在设置页面配置

**Comment by 88250** [comment]
FYI https://github.com/siyuan-note/siyuan/issues/8683
