### ISSUE TITLE
希望增加打印功能，直接打印，而不需要导出PDF再打印。同时希望增加优化排版的快捷键/

### ISSUE THREAD

**Issue by Joker-lkc** [siyuan-note/siyuan#8778]
### In what scenarios do you need this feature?

希望增加打印功能，直接打印，而不需要导出PDF再打印。同时希望增加优化排版的快捷键/

### Describe the optimal solution

希望增加打印功能，直接打印，而不需要导出PDF再打印。同时希望增加优化排版的快捷键/

**Comment by 88250** [comment]
直接打印支持不了；v2.9.6 已经支持 优化排版 快捷键 https://github.com/siyuan-note/siyuan/issues/8767

感谢反馈。
