### ISSUE TITLE
表格编辑：单元格内换行符的隐藏，单元格内插入列表，表格的题注

### ISSUE THREAD

**Issue by wangfh5** [siyuan-note/siyuan#878]
在思源编辑了一个表格，有几个建议如下。
![image](https://user-images.githubusercontent.com/51868839/103290847-6abdc880-4a25-11eb-826d-72c88ab9c5af.png)
1. 换行符`<br />`可不可以隐藏
2. 表格内一个单元格有没有办法嵌入无序和有序列表？感觉只是渲染问题，Typora0.9.98还没有做到。
3. 现在图片可以加题注了，表格有没有办法加题注？
4. 表格首行和第二行的背景都是同一个阴影颜色“灰”，个人认为可以再设计一下。最简单的就是第二行背景为白，第三行改为灰（这是Typora的背景安排）……

**Comment by 88250** [comment]
你好，

1. 表格内换行符暂时隐藏不了，后面尝试
2. 表格内嵌入不了其他块，受限于 Markdown 语法
3. 表格题注应该没问题，后面尝试
4. 稍后改进

谢谢！

**Comment by wangfh5** [comment]
可以不作为块，但是渲染可以按列表渲染吗？

**Comment by 88250** [comment]
不行，因为渲染列表的前提是解析为列表块……

**Comment by 88250** [comment]
颜色问题是设计如此，我关闭了，感谢提议。

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/19188
