### ISSUE TITLE
S3/WebDAV data sync and backup are available for a fee

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8780]
The free public beta stage ends, and a fee is required for use.

This feature is available for a one-time fee, and if you are a subscriber, you do not need to pay separately.

For the pricing and more details please visit https://github.com/siyuan-note/siyuan/issues/8906

**Comment by taylormao** [comment]
怎么付费？

**Comment by 88250** [comment]
@taylormao 定价已经确定，请看正文更新内容。

**Comment by oott123** [comment]
请问如果已有订阅想购买终身特性解锁，如何购买？

**Comment by 88250** [comment]
@oott123 订阅用户在订阅期内的话不用单独购买，如果没有在订阅期内，可以单独购买，但是购买页面我们还没做，还要再等等。

**Comment by oott123** [comment]
> 如果没有在订阅期内，可以单独购买

我是希望可以在订阅期内以早鸟价购买，万一不续费订阅了还能用这个功能。

**Comment by 88250** [comment]
可以的，等我们做好购买页面，谢谢。

**Comment by ranggasan** [comment]
Is there any feature difference between LiuYun’s lifetime subscription and S3/WebDAV sync fee?

**Comment by 88250** [comment]
> Is there any feature difference between LiuYun’s lifetime subscription and S3/WebDAV sync fee?

In addition to data sync/backup, at present subscribers also have:

* Distinguished identity (VIP badge)
* Cloud assets serving (LiuYun)
* Cloud Inbox (API)

**Comment by ranggasan** [comment]
> > Is there any feature difference between LiuYun’s lifetime subscription and S3/WebDAV sync fee?
> 
> In addition to data sync/backup, at present subscribers also have:
> 
> * Distinguished identity (VIP badge)
> * Cloud assets serving (LiuYun)
> * Cloud Inbox (API)

If we pay for S3/WebDAV sync, can we upgrade to lifetime subscription later?

**Comment by jiaoting** [comment]
有个问题，后期如果不干了，或者服务器崩溃，那三方同步还能用吗？

**Comment by 88250** [comment]
> 有个问题，后期如果不干了，或者服务器崩溃，那三方同步还能用吗？

请参考 https://github.com/siyuan-note/siyuan/issues/8835

**Comment by jiaoting** [comment]
> > 有个问题，后期如果不干了，或者服务器崩溃，那三方同步还能用吗？
> 
> 请参考 #8835

感谢，了解了这块同步需要额外的工作量。我已经付费啦。
其实就是担心，比如说5年或者10年之后，服务停止了，用于验证的服务器下线了，这样同步功能是否还可用。
因为我一开始用纸质笔记本记录，随着记录时间，资料是越来越多，而且无法索引，不能串联，特别是搬家的时候，要搬好多。后来开始着手建立知识库数据化，把自己积累的资料都保存起来，国内的笔记软件基本上用了个遍，一开始挑选了几家大厂，后来由于产品调整或者下线，或者资费不断提升，导致被迫出现多次数据迁移，最近几次是从有道云、wolai、ob一路迁移的，由于数据量比较多，而且各家的数据格式又不统一，实在是苦不堪言。我发现笔记云端话的确很方便，但数据审查，包括服务不稳定，都会对个人使用带来很大影响，而且我又没太有协作的需求，后来决定笔记本地化。为了保障数据安全和多端使用，特别需要数据同步功能。
所有我才有这个担心。
如果在代码里加上几个判断，在官方服务器下线或者异常的情况下，可以自动取消登录验证，如果服务器重新可用，再重启登录验证，这样在无人维护的情况下，保证同步功能可用。
我知道虽然开源可以自编译，但是有这样的容灾判定，是不是在出现极端情况下，能更好一些呢？

**Comment by 88250** [comment]
@jiaoting 感谢你付费支持我们开发。

> 其实就是担心，比如说5年或者10年之后，服务停止了，用于验证的服务器下线了，这样同步功能是否还可用。

不用有任何担心和压力，我们完整开源思源笔记代码的目的就是打消类似的担心。

说个万一，就算我们在某个时刻无法坚持维护思源笔记了，我们也会在那个时候把鉴权部分去掉的（其实现在很多 fork 代码分支已经去掉了，相关代码[见此](https://github.com/siyuan-note/siyuan/blob/7892e0f4be538607ccba829c746e28503a5714f4/kernel/model/conf.go#L730)），所以完全不用有这方面的顾虑。

关于服务器偶然宕机也不必太过担心。用户鉴权是有很长的时效性的（目前是一年吧，如果我没记错的话），所以就算我们的鉴权服务器偶然宕机，只要之前登录过，依然是可以正常使用 功能特性（PRO）的。

开源商业化是需要我们和社区、和用户一起努力的，我们坚信 **但行好事莫问前程**，我们对所有思源笔记用户抱有最大的期待，也期望大家对我们抱有同样的信心！

**Comment by 88250** [comment]
@Sean-Xiao-365 不会的，可以同时存在的。

**Comment by gaoyiping** [comment]
牛的！升级之后我都没办法同步了，至少要等一个版本，让我把现在数据备份好吧。

**Comment by gaoyiping** [comment]
> @gaoyiping 你好，这里可以下载到老版本 https://github.com/siyuan-note/siyuan/releases

为我的无知，道歉。
