### ISSUE TITLE
中文语境优化：阿拉伯数字后面跟英文标点

### ISSUE THREAD

**Issue by wangfh5** [siyuan-note/siyuan#879]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

写有序列表的时候，小功能很常用。

### 描述最优的解决方案 Describe the optimal solution

阿拉伯数字后面打。变为.

**Comment by 88250** [comment]
你好，这个靠输入法完成，思源实现的话会有比较多的问题，谢谢。
