### ISSUE TITLE
Content shows multiple times in a row on my document

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#8790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I opened my document and found that its contents repeat several times in a row.

What I'm experiencing is exactly what is described here:
https://ld246.com/article/1689566685831

I apologize if there is already an issue for that here. I read the forums using Google Translate, however am not able to search terms, as they are in Chinese.

### Expected result

No repetition.

### Version environment

```markdown
- Version:  2.9.6
- Operating System:  Android
- Browser (if used):
```

### Log file

.

**Comment by 88250** [comment]
Hi, please upload a dataset that reproduces the problem, thanks.

**Comment by ognsya** [comment]
The content is private, so I can't share that.

The appearance is just like the screenshot shown in the link I referenced. In my case, the content shows repeated 17 times.

All my content is structured within a List.

**Comment by 88250** [comment]
Can you just send it to me for debugging 845765@qq.com I promise not to leak your data, if it is still inconvenient, forget it, thank you.

**Comment by ognsya** [comment]
> Can you just send it to me for debugging [845765@qq.com](mailto:845765@qq.com) I promise not to leak your data, if it is still inconvenient, forget it, thank you.

Sorry I can't. It's sensitive data.

If it helps, I had been accessing SiYuan (running on my phone) via a Chrome browser on my laptop.

**Comment by Temacc0531** [comment]
> Sorry I can't. It's sensitive data.

Maybe you can use some insensitive data to try to reproduce this flaw?

**Comment by 88250** [comment]
We have closed this issue. If you have further information, please feel free to add it. Thank you.
