### ISSUE TITLE
可以支持多用户吗？

### ISSUE THREAD

**Issue by ITKJO** [siyuan-note/siyuan#8791]
### In what scenarios do you need this feature?

在企业推广使用时需要使用多用户的场景，方便集成到现有的系统中

### Describe the optimal solution

在duocker端支持使用多用户的场景，可通过网络集成到其他的B/S架构的系统中

**Comment by 88250** [comment]
你好，思源主要面向个人使用场景，多租户的场景目前暂不考虑，感谢反馈。
