### ISSUE TITLE
希望有批量管理闪卡的功能

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#8794]
### In what scenarios do you need this feature?

提几点
1、一键清除无效的闪卡
2、批量选中删除卡片
3、批量的重置卡片
4、闪卡的批量导出功能

### Describe the optimal solution

可以在目前的闪卡管理界面上解决

**Comment by 88250** [comment]
考虑到一些特殊情况，应该不会内置这些功能了，后续看下是否有插件吧，感谢反馈。

**Comment by Joe-2002** [comment]
> 考虑到一些特殊情况，应该不会内置这些功能了，后续看下是否有插件吧，感谢反馈。

想问下，siyuan后续对闪卡是否有更新和迭代的计划呢，目前主力Anki，想看是否有机会转siyuan的闪卡，记得之前关于思源的闪卡有个很长的帖子，找不到了

**Comment by 88250** [comment]
后续可能会先支持保存复习记录数据，然后引入 fsrs 优化器 #8594
