### ISSUE TITLE
Clarify the "Cross-page multi-selection" mesage

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#8796]
### In what scenarios do you need this feature?

What does this message mean? Where do I find this More menu?

![image-20230720161500-q5olvoy](https://github.com/siyuan-note/siyuan/assets/67518000/9cad4dbf-5c82-49b1-872e-915935cf2edf)

I figure it warns me that the selection might not work due to it being multi-page. However the operation I wanted to do (deletion) seemed to work OK.

### Describe the optimal solution

Clarify that message.

**Comment by 88250** [comment]
Hello, this prompt message will appear when you need to dynamically load (longer) documents with multi-select blocks across pages. For large documents, SiYuan will use dynamic loading (only a limited number of blocks are loaded) to avoid performance degradation when opening large documents, so cross-page selection needs to enable this setting to avoid "recycling" of already loaded blocks.

![image](https://github.com/siyuan-note/siyuan/assets/873584/e22db814-c3dc-4fdb-ae9d-f5d801d64e61)

**Comment by ognsya** [comment]
Thank you!

I suggest clarifying what is the "more menu". Maybe include the three dot icon in the message?
