### ISSUE TITLE
在查询界面操作删除某个对象时查询结果不刷新

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#8799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在查询界面操作删除某个对象时查询结果不刷新

### Expected result

理论上在查询界面操作了删除块或者某个文档，应当刷新查询结果

### Version environment

```markdown
- Version: 2.9.6
- Operating System: 
- Browser (if used):
```

### Log file

略

**Comment by 88250** [comment]
后面考虑在 #8800 中增加刷新按钮，谢谢。
