### ISSUE TITLE
Search word not getting highlighted in code block

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Found a related issue https://github.com/siyuan-note/siyuan/issues/8332. Not sure if it is for the same thing.
Steps to reproduce:
1. Copy and paste the below block into a new doc.
````
nice

wow 1

nice

```bash
hello
wow 2
how
are
you
```

ok

wow 3

nice
````

2. Press `Ctrl+F`/`Cmd+F` and search `wow`
3. `wow` which is followed by `1` and `3` get highlighted, but `wow` followed by `2` does not get highlighted

`wow 3` - working as expected
<img width="277" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/ba8e3158-7b2d-464e-9861-bf4cf2ff491f">

`wow 2` - not working as expected
<img width="239" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/5c8d2257-d506-425a-a40a-3ecc42be419e">

### Expected result

`wow` which is followed by `2` should also get highlighted like other occurrences of `wow`

### Version environment

```markdown
- Version: 2.9.6
```

### Log file

\-

**Comment by Vanessa219** [comment]
The code block is rendered using highlight.js, so it can only be positioned, but not marked.
