### ISSUE TITLE
Option to select the order of search results

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8802]
### In what scenarios do you need this feature?

When searching notes/docs/code in other apps we generally go from top to bottom. But, when using Search and Global Search, the results are in the descending order of block modification time.
<img width="958" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/942bd9cd-55f5-4b65-afbd-f919a3636219">

### Describe the optimal solution

Ideally, in text editor, IDE (VSCode) and docs (MS Word, Google Doc) the search results are ordered based on their position in the file, and results of same file are together (please note that I am not talking about `More > Group > Group by document`)

VSCode can be used as a reference to decide the ordering and showing of results. I believe it does that really well.

**Comment by 88250** [comment]
The default is to sort by update time. Only when the documents are grouped can they be sorted in text order. Thank you for your feedback.

**Comment by fenilgmehta** [comment]
Even when using `Group by document`, the results are not sorted according to sequence in doc
<img width="1076" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/8beb457c-14d9-475e-97b8-4fb615cfe3ff">

Expected order in the above case is:
* wow 1
* wow 2
* wow 3

**Comment by 88250** [comment]
Did you change this?

![image](https://github.com/siyuan-note/siyuan/assets/873584/7f609d5f-7589-44ad-af43-a34a8d73fa0a)

**Comment by fenilgmehta** [comment]
I do not see this `Original content order` option in SiYuan v2.9.6
<img width="960" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/3544c1ae-e696-40b0-a21d-a9672bc979ea">

**Comment by fenilgmehta** [comment]
Thanks for sharing this. Just found it, and got to know that this option only shows up when `Group > Group by document` is enabled.
Now it is working 👍
