### ISSUE TITLE
pdf的批注无法跳转

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#8804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

pdf的批注无法跳转

### Expected result

1

### Version environment

```markdown
- Version: 最新
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12123014/siyuan.log)

**Comment by 88250** [comment]
你好，从内核日志上无法诊断问题，如果方便的话请导出 .sy.zip 发给我们调试 845765@qq.com

这个 issue 我们先关闭了，感谢反馈。

**Comment by linglongyoudoufu** [comment]
霞幕倾松风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] pdf的批注无法跳转 (Issue #8804)





 
你好，从内核日志上无法诊断问题，如果方便的话请导出 .sy.zip 发给我们调试 ***@***.***
 
这个 issue 我们先关闭了，感谢反馈。

**Comment by linglongyoudoufu** [comment]
链接：https://pan.baidu.com/s/1_sUDACZhI_5WYmF25QdDkQ?pwd=0000&nbsp;
提取码：0000&nbsp;
--来自百度网盘超级会员V3的分享



霞幕倾松风
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月21日(星期五) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] pdf的批注无法跳转 (Issue #8804)





 
你好，从内核日志上无法诊断问题，如果方便的话请导出 .sy.zip 发给我们调试 ***@***.***
 
这个 issue 我们先关闭了，感谢反馈。

**Comment by 88250** [comment]
你好，数据已经收到，分享了下是因为 PDF 标注元素格式已经变动，是不是之前导出过 md 又导入了，这样的话无法保证标注元素可以复原，只有导出 .sy.zip 才能保证原始格式。

**Comment by linglongyoudoufu** [comment]
好像改过插入的 在思源笔记里的pdf的名称 和 资源管理器的pdf的名称。用过并卸载插件“pdf标注”
&nbsp;


霞幕倾松风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月22日(星期六) 晚上9:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] pdf的批注无法跳转 (Issue #8804)





 
你好，数据已经收到，分析了下是因为 PDF 标注元素格式已经变动，是不是之前导出过 md 又导入了，这样的话无法保证标注元素可以复原，只有导出 .sy.zip 才能保证原始格式。
 
&mdash;

**Comment by 88250** [comment]
暂时无法确认重现步骤，麻烦后续留意，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月22日(周六) 晚上11:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] pdf的批注无法跳转 (Issue #8804)




 好像改过插入的 在思源笔记里的pdf的名称 和 资源管理器的pdf的名称。用过并卸载插件“pdf标注” 
 &amp;nbsp; 
 
 
 霞幕倾松风 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年7月22日(星期六) 晚上9:57 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [siyuan-note/siyuan] pdf的批注无法跳转 (Issue #8804) 
 
 
 
 
 
   
 你好，数据已经收到，分析了下是因为 PDF 标注元素格式已经变动，是不是之前导出过 md 又导入了，这样的话无法保证标注元素可以复原，只有导出 .sy.zip 才能保证原始格式。 
   
 &amp;mdash;
