### ISSUE TITLE
手机端、平板端的集市数据应该同步（主题、插件等），避免每次都需要手动更新，安装

### ISSUE THREAD

**Issue by Joe-2002** [siyuan-note/siyuan#8806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

手机端、平板端的集市数据应该同步（主题、插件等）

### Expected result

手机端、平板端的集市数据应该同步（主题、插件等）

### Screenshot or screen recording presentation

手机端、平板端的集市数据应该同步（主题、插件等）

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
手机端、平板端的集市数据应该同步（主题、插件等）
```

### Log file

手机端、平板端的集市数据应该同步（主题、插件等）

**Comment by 88250** [comment]
插件是同步的，主题不会同步，感谢反馈。

**Comment by Achuan-2** [comment]
大部分主题其实能兼容手机端和平板端的，尤其是现在有了插件，很多主题只有css代码。
比起插件，主题的兼容性更好，不明白为什么插件可以同步，主题却不同步？

**Comment by 88250** [comment]
主要是担心移动端兼容性，如果不兼容的话移动端没法重置，只能卸载重装，这样会带来很多问题。

**Comment by Achuan-2** [comment]
> 主要是担心移动端兼容性，如果不兼容的话移动端没法重置，只能卸载重装，这样会带来很多问题。

目前插件同步也没太发觉到兼容性问题，而且对于安卓端而言，我真觉得大部分主题是没有兼容性问题的，我自己也一直在安卓手机端用我的主题，用户也可以选择避开那些真有兼容性问题的主题。
如果有兼容性问题，不能移动端切换主题吗？或者通过浏览器打开，切换主题？
想到一个解决方案，或者可以在theme.json添加一个字段，是否兼容移动端，主题作者设置true，同步之后才可以在外观设置选择该主题，D大看下可行不

**Comment by 88250** [comment]
对普通用户来说有点不够稳妥，还是不支持保险一些。

**Comment by 88250** [comment]
目前通过伺服的方式启用集市下载主题是比较折中的方案，这样可以尽量避免普通用户切换到不兼容的主题，有折腾能力的用户也可以使用。

**Comment by Achuan-2** [comment]
那我选择用代码片段来同步主题吧。
只是不明白难道插件没有兼容问题，主题反而有兼容问题？

**Comment by 88250** [comment]
插件已经有是否支持某个端的设置项了，如果开发者设置了不支持就不会加载，但是主题似乎不能搞，因为设置了不兼容后不加载的话就没有能加载的了。这个和插件不太一样，插件就算不加载影响也不会大到无法进入界面。

**Comment by Achuan-2** [comment]
主题应该也可以设置不兼容选项吧
我的想法：不需要同步当前选择了什么主题，只需要同步主题文件夹，默认加载默认主题，之后用户去外观选择能兼容该端的主题，不兼容
疑问：主题会导致无法进入界面是为什么？是有的主题直接把一些界面给display none了，还是因为其他方式呢？

**Comment by 88250** [comment]
* 主题中元素错位之类的问题可能会导致不可用
* 另外还有个问题是主题不在 data 下面，设计之初就已经排除在同步外了

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/17151
