### ISSUE TITLE
Breadcrumb bar in search panel not showing right values

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The element pointed in the following image does not update irrespective of which search result we select.
<img width="872" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/fefbb8de-cc26-4708-9cba-4be5dbc9c0e4">

### Expected result

The pointed element in the above image should have shown the below value
<img width="339" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/aac4967e-138a-4a4e-b08c-b2508eb1208a">

### Version environment

```markdown
- Version: 2.9.6
```

### Log file

\-

**Comment by 88250** [comment]
Please try the latest dev version, we add a refresh button here:

![image](https://github.com/siyuan-note/siyuan/assets/873584/2bfe9664-fbb4-4c1d-a183-dd6dd2a89c65)

If the issue continues, please let us know, thank you very much.

**Comment by fenilgmehta** [comment]
Refresh button does not help

**Comment by fenilgmehta** [comment]
Thanks for the fix, it is working rightly in some cases. But, sometimes it still works incorrectly.

Observed
<img width="501" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/c7543937-c6ee-4d43-8e2a-b680b25289a8">

Expected
<img width="395" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/676b172c-a7ad-4072-9d13-f1a1f7772178">

File content used for testing
<img width="207" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/d9c8daca-6b05-4cea-b586-307399b1bcc5">

**Comment by 88250** [comment]
@fenilgmehta We will improve it in the next version, thank you.
