### ISSUE TITLE
v2.9.7-dev2无法呼出字体外观

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如录屏，快捷键和编辑器菜单都无法呼出字体外观选项。重装dev1版本后正常呼出字体外观。

### Expected result

正常呼出字体外观。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/4d340074-e216-456a-84d2-35b5c94ee6c4

### Version environment

```markdown
- Version: 2.9.7-dev2
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12136545/siyuan.log)

**Comment by Vanessa219** [comment]
改移动端字体设置改出了点问题，多谢。
