### ISSUE TITLE
反链提及快速链接问题

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#881]
### 描述问题 Describe the problem

在[提及]中,点击无法跳出[转换为内容块引用]

### 期待的结果 Expected result
GIF中[市场营销-科特勒]的表现

### 截屏或录屏演示 Screenshot or screen recording presentation
![转换引用为链接](https://user-images.githubusercontent.com/11732858/103325388-9fae3780-4a86-11eb-87c8-7efc8572782b.gif)

### 版本环境 Version environment

* 版本 Version：0.5.45
* 操作系统 Operating system：Windows 10
* 浏览器（如果使用）Browser (if used)：Chrome

### 日志文件 Log
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5752769/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，v0.5.6 修复。
