### ISSUE TITLE
手机伺服，浏览器的clipboard无法使用，报错

### ISSUE THREAD

**Issue by AILHC** [siyuan-note/siyuan#8810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

右键粘贴为纯文本、转义文本都会报错

其他插件用了writeText，也会报错

看了控制台默认的navigator.clipbord对象没了

### Expected result

正常使用navigator.clipbord

### Version environment

```markdown
- Version: 2.9.6
- Operating System: Android(伺服)
- Browser (if used): Edge(Windows)
```

### Log file

main.e26e29bc561f2a4f1997.js:401  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'readText')
    at main.e26e29bc561f2a4f1997.js:401:1534
    at Generator.next (<anonymous>)
    at main.e26e29bc561f2a4f1997.js:401:1348
    at new Promise (<anonymous>)
    at Vu (main.e26e29bc561f2a4f1997.js:401:1168)
    at Wu (main.e26e29bc561f2a4f1997.js:401:1472)
    at Object.click (main.e26e29bc561f2a4f1997.js:1108:24621)
    at HTMLButtonElement.<anonymous> (main.e26e29bc561f2a4f1997.js:42:6958)

**Comment by 88250** [comment]
可能是浏览器没有给剪切板权限，请确认一下。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
