### ISSUE TITLE
Doubled Backslash in Table of Embedded Block

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#8811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复现步骤：
1. 创建一个表格，在某个单元格加入反斜杠 `\`
2. 复制为嵌入块
3. 粘贴到别处，会发现反斜杠重复了

### Expected result

反斜杠不应重复

### Screenshot or screen recording presentation

原始表格
![image](https://github.com/siyuan-note/siyuan/assets/30611816/91c57d01-242d-456d-a093-92313b577184)
复制粘贴为嵌入块后
![image](https://github.com/siyuan-note/siyuan/assets/30611816/b33cf40b-47e2-4407-9497-e50ea0a4a4aa)

### Version environment

```markdown
- Version: 2.9.6
- Operating System: Windows 11 22H2
- Browser (if used): /
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12137946/siyuan.log)

**Comment by 88250** [comment]
在打一个 `\` 应该就正常了，暂时不做调整，感谢反馈。
