### ISSUE TITLE
Sort by `Type` in search not working

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Sort by `Type` not working in Search
<img width="928" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/94a74a51-be9e-48a0-b88d-68c3b4b6520a">

### Expected result

`wow 1` and `wow 3` should be together because both are `Paragraph block`

### Version environment

```markdown
- Version: 2.9.6
```

### Log file

\-

**Comment by 88250** [comment]
This is because the sorting values for paragraph blocks and code block types are the same.

![image](https://github.com/siyuan-note/siyuan/assets/873584/a57a94ef-edf8-474e-8e2e-52f6ed3781b2)
