### ISSUE TITLE
Highlight active `Query criteria`

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8813]
### In what scenarios do you need this feature?

When there are multiple `query criteria`, it is hard to know which `query criteria` is active. It would be really helpful to know which one is active.
<img width="203" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/5d8bbc5d-171b-4da2-ad25-91e840961949">

### Describe the optimal solution

Not sure what would the ideal solution be in terms of UI/UX.

One solution I could think is to use solid background for selected `query criteria` and colored border (`border: 2px solid var(--b3-theme-secondary)`) for other `query criteria`. In the below image, `FileName` is the active `query criteria`, and `SearchAll` is non-active `query criteria`
<img width="193" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/4ca1eda7-ebc7-49a2-bcb6-53bf0a14cc49">

**Comment by fenilgmehta** [comment]
This seems to be behaving strange. When we open the search panel, it looks like below
![image](https://github.com/siyuan-note/siyuan/assets/42742240/fa088e1e-47ee-4905-81ca-3c013e414184)

When we start typing, it changes to the following
![image](https://github.com/siyuan-note/siyuan/assets/42742240/eaf7025e-0411-446e-b870-b9045cf4ca1d)

Type `a` and stop. `Default` will get highlighted
Type `b` and stop. `testing` will get highlighted
...

The query criteria `Default`, `testing` and `default` were created in the following fashing:
1. Open search panel
2. Click `Remove query criteria`
3. Click `Save query criteria` and save it as `Default`
4. Click `Save query criteria` and save it as `testing`
5. Click `Save query criteria` and save it as `default`

---

Another observation is that whichever query criteria is clicked, that becomes bordered style. In the below case, I clicked `Default` and it became bordered style, and rest have solid color filled in them. The idea suggested in the `Describe the optimal solution` section was the opposite - use solid color filling for selected query criteria and bordered style for the rest
![image](https://github.com/siyuan-note/siyuan/assets/42742240/020e4beb-d0d9-4e8f-a14c-59054f7acec9)

**Comment by Vanessa219** [comment]
* When the conditions are the same, saving should be directly overwritten?
* Highlight improvements for next version.

**Comment by fenilgmehta** [comment]
Following is the behavior which I would prefer for different cases:
1. query criteria with name `N1` with conditions `C1` exists, and user tries to save another query criteria with the name `N2` and condition `C2` --> we **directly save** the new query criteria
2. [issues/8913](https://github.com/siyuan-note/siyuan/issues/8913): query criteria with name `N1` with conditions `C1` exists, and user tries to save another query criteria with the same name `N1` with conditions `C2` --> we **prompt** the user if they would like to overwrite conditions `C1` with `C2`
3. This issue: query criteria with name `N1` with conditions `C1` exists, and user tries to save another query criteria with the name `N2` but with same condition `C1` --> we **prompt** the user if they would like to rename query criteria `N1` to `N2`
4. query criteria with name `N1` with conditions `C1` exists, and user tries to save another query criteria with the same name `N1` with same conditions `C1` --> **inform** the user that query criteria with same name and conditions already exist

I know this will complicate the logic a bit. But, I feel it will resolve the issue fully.

Thanks
