### ISSUE TITLE
Push database index commit event

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8814]
插入/更新块的Promise完成时，其内容没更新到sql中

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

await运行prependBlock之后，当我尝试通过SQL查找插入的部分内容时，会出现找不到的情况，后来尝试在我的电脑上等待2秒后才能查到。但是问题在于我不知道用户的电脑需要多久才能更新出来。

![image](https://github.com/siyuan-note/siyuan/assets/63407442/2565ef97-211d-4df7-8f78-4ca99819a8fe)

但是由于HTML块不能和markdown一起更新，我只能这么做

### Expected result

不管await多久，理论上Promise结束的时候这个块应该在SQL里是准备好的，或者说有个指示标明更新完毕我可以开始下一个操作了

### Version environment

```markdown
- Version: 2.9.6
- Operating System: windows
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
数据库索引是个异步任务，无法确定具体执行完成时间。

要不我们加个 SQL 索引结束的事件推送？

**Comment by WingDr** [comment]
> 数据库索引是个异步任务，无法确定具体执行完成时间。
> 
> 要不我们加个 SQL 索引结束的事件推送？

我觉得ok，只要是能知道啥时候能再查就行

**Comment by Vanessa219** [comment]
使用 EventBus 监听  `ws-main`  ，检测 cmd 为 `databaseIndexCommit` 即可。
