### ISSUE TITLE
添加子标题后，希望大纲是展开的

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#8816]
### In what scenarios do you need this feature?

比如下面，添加了一级标题后
![image](https://github.com/siyuan-note/siyuan/assets/5683995/e3a6bc9f-c2a3-4d05-9cb7-3ad983bdf6b4)
再添加二级标题，希望二级标题的大纲，默认是展开的
![image](https://github.com/siyuan-note/siyuan/assets/5683995/6d724aaf-2fc6-4a34-b452-bf7d869e08ec)

### Describe the optimal solution

提供这个小特性

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/60a0deee-0a58-440c-92dc-0fdc847602a5)

**Comment by zhoutaosheng** [comment]
> 

@88250 每个页面，都需要点一次，还是比较麻烦的。能否默认就是展开的

**Comment by 88250** [comment]
不需要啊，这个状态是全局保持的。
