### ISSUE TITLE
【请求】代码块添加可进行版本选择切换

### ISSUE THREAD

**Issue by Febtw** [siyuan-note/siyuan#8818]
### In what scenarios do you need this feature?

有些功能的代码，对应不同系统需要不同的版本，如果顺序罗列，显得累赘。
希望可以进行版本选择切换显示。
类似于这样的效果
![1690292149221](https://github.com/siyuan-note/siyuan/assets/96163355/d5158115-f681-46b6-b507-526109fc856c)

上例来自：[https://icloudnative.io/posts/wireguard-docs-practice/#安装](https://icloudnative.io/posts/wireguard-docs-practice/#安装)

### Describe the optimal solution

不知道如何实现，但本输入框恰好有类似功能。
见 Write 和 Preview
![image](https://github.com/siyuan-note/siyuan/assets/96163355/6194dda1-db37-4fc4-b484-858a46114e09)

### Describe the candidate solution

或者可不可以给列表以另一种可选择的显示方式
将下面列表显示成上面的样式

* CentOS7

  ```bash
  yum install epel-release https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
  yum install yum-plugin-elrepo
  yum install kmod-wireguard wireguard-tools

  # 如果你使用的是非标准内核，需要安装 DKMS 包
  yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  curl -o /etc/yum.repos.d/jdoss-wireguard-epel-7.repo https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/epel-7/jdoss-wireguard-epel-7.repo
  yum install wireguard-dkms wireguard-tools
  ```
* Ubuntu

  ```bash
  # Ubuntu ≥ 18.04
  apt install wireguard

  # Ubuntu ≤ 16.04
  add-apt-repository ppa:wireguard/wireguard
  apt-get update
  apt-get install wireguard
  ```
* MacOS

  ```bash
  brew install wireguard-tools
  ```
* Windows

  下载地址：
  [https://download.wireguard.com/windows-client/wireguard-amd64-0.1.1.msi](https://download.wireguard.com/windows-client/wireguard-amd64-0.1.1.msi)
* 其他

  Android 和 iOS 可通过应用商店下载相关客户端
  其他操作系统请参考官方文档： [https://www.wireguard.com/install/#installation](https://www.wireguard.com/install/#installation)

**Comment by Joe-2002** [comment]
支持

**Comment by 88250** [comment]
语法层面不会考虑单独为其添加支持了，这里仅提供几个思路：

* 通过你提到的候选方案结合自定义样式
* 通过自定义块 #8418 
* 通过 HTML 块

**Comment by Achuan-2** [comment]
Tsundoku主题实现了列表转标签页功能，不过还是期待官方能出各种列表转化样式，或者提供自定义块功能给插件来做

<img width="1435" height="327" alt="Image" src="https://github.com/user-attachments/assets/8ebf605e-3ea3-4dac-9819-4dda2a941d74" />
