### ISSUE TITLE
指定文档清除已丢失的资源文件

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8819]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/125173405/adba4f92-59cf-48e3-ae78-5d95491629f6)
例如这种情况，图片是不同文件，无法批量替换和删除。

### Describe the optimal solution

希望能提供在指定的文档中一键清除所有已丢失资源文件的功能。

**Comment by 88250** [comment]
这个还是手动清理比较好，或者等社区插件，不考虑原生提供，感谢反馈。
