### ISSUE TITLE
tab键替换为空格

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#882]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

日常使用的vscode及其他代码编辑器中, tab键输入的都是四个空格, 希望能实现(提供选项或默认)此行为.

且, markdown中, 制表符有用吗?

### 描述最优的解决方案 Describe the optimal solution

提供选项(或设为默认) (如下参考vscode的行为):
- 按下tab键后输入4个空格, 或补充到4个空格的整数倍 (如0->4, 5->8);
- 再按下backspace键, 删除到剩余4个空格的整数倍 (如4->0, 7->4);

### 描述候选解决方案 Describe the candidate solution

NA

### 其他信息 Other information

NA

**Comment by 88250** [comment]
谢谢，制表符输入优化后期考虑，也很有可能不会有优化……

Markdown 里面开头缩进大于等于 4 个空格或者一个 `\t` 的话会变代码块。

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/705
