### ISSUE TITLE
Remove the target docx file when exporting

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#8822]
导出文档出现“工作空间下的文件被第三方软件占用”

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

导出docx文件后，打开导出的docx文件
再次导出该docx文件到相同路径，提示：
>工作空间下的文件正在被第三方软件（比如同步盘 iCloud/OneDrive/Dropbox/Google Drive/坚果云/百度网盘/腾讯微云等）扫描读取占用，继续使用会导致数据损坏，思源内核已经安全退出。

### Expected result

应提示docx文件被占用，而不应该退出内核

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
为了保险起见，只要工作空间路径下的文件读写出错都会退出内核。

**Comment by choyy** [comment]
导出的docx跟工作空间没关系了，这有点过了

**Comment by 88250** [comment]
有关系的，是从工作空间 temp 路径下复制文件到目标路径上。

**Comment by choyy** [comment]
但对用户来讲这样之间退内核太粗暴了，而且还不容易找到啥原因

**Comment by 88250** [comment]
是有点粗暴，我看看下个版本能否加个提示。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月26日(周三) 中午11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 导出文档出现“工作空间下的文件被第三方软件占用” (Issue #8822)




 
但对用户来讲这样直接退内核太粗暴了，而且还不容易找到啥原因
