### ISSUE TITLE
引述块中添加标题样式不会显示在大纲中是 bug 还是特性？

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://ld246.com/article/1690274492482/comment/1690340817679#comments

### Expected result

我感觉可以作为特性保留，这样就能在引述块中创造不会出现在大纲中的标题，应用标题样式和标题功能。

### Version environment

```markdown
- Version: 2.9.6
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
引述块中的标题不在大纲面板中显示是设计如此。

**Comment by zxhd863943427** [comment]
那列表块和超级块中的标题呢？我觉得还是统一不显示比较好。
它们自带一套层级，不完全服从大纲中的层级。

**Comment by 88250** [comment]
暂时不动了，这些规则很早之前讨论过。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月26日(周三) 下午2:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 引述块中添加标题样式不会显示在大纲中是 bug 还是特性？ (Issue #8823)




 
那列表块和超级块中的标题呢？我觉得还是统一不显示比较好。
 它们自带一套层级，不完全服从大纲中的层级。
