### ISSUE TITLE
Anchor text repeats after conversion of non-plain text inline-level elements to a block ref

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8825]
将带格式的文本转化为引用块会出错

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

将带格式的文本转化为引用块会出现重复文本，示例如下：
![引用块错误](https://github.com/siyuan-note/siyuan/assets/74853597/df38126c-557a-4bc7-82ca-0fd7ee90b976)

### Expected result

修复该问题

### Version environment

```markdown
- Version: 2.9.7
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
转换时估计只能自动取消已有的行级元素。
