### ISSUE TITLE
Run siyuan note from Subdirectory

### ISSUE THREAD

**Issue by lin1810** [siyuan-note/siyuan#8826]
### In what scenarios do you need this feature?

I'd like to be able to run a siyuan note container and access it from https://.../base-path/.
Currently the docker image only allows siyuan at the root of the server. This makes it unsuitable for deployment on a shared server or behind an SSL front-end appliance.

### Describe the optimal solution

No way to specify non-root base path

**Comment by 88250** [comment]
Sorry for not supporting it, if you want to support it, you may only have to study NGINX reverse proxy forwarding requests.
