### ISSUE TITLE
Improve mobile selection text menu

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8829]
手机端选中文字后的快捷菜单会遮挡文字

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在手机端使用思源，可能由于扣除键盘后剩余屏幕区域较小，会出现选中文字后跳出的菜单遮挡选中的文字的情况。
建议这里选中文字还是常规的跳出横排复制粘贴剪切选项，添加一个更多选项，点击更多再跳出不同的复制选项。
这时候菜单也可以放到键盘区域而不是占用上方屏幕。

### Expected result

复制粘贴复杂菜单不遮挡选中的文字。

### Screenshot or screen recording presentation

![Screenshot_2023-07-26-18-30-58-560_org b3log siyuan](https://github.com/siyuan-note/siyuan/assets/57566668/d0fdc575-6a3d-4cfd-85e2-25e30c6ff3a6)

### Version environment

```markdown
- Version: 2.9.7
- Operating System: 安卓
- Browser (if used):
```

### Log file

-

**Comment by Vanessa219** [comment]
Android 选中是横排，但是我们这个选项有点多，如果横排可能需要移除几个不常用的选项。

**Comment by gdy106** [comment]
这个简单。我做个一套横排用的效果图。

选中文字的菜单：
![复制粘贴菜单](https://github.com/siyuan-note/siyuan/assets/57566668/fa139565-4a91-4d46-8d6f-dbea79e857e3)

点击复制+后跳出复制为纯文本：
![复制粘贴菜单-复制](https://github.com/siyuan-note/siyuan/assets/57566668/632776ff-18fe-4961-9ede-3e6c996d8e7f)

点击粘贴+后跳出粘贴选项：
![复制粘贴菜单-粘贴](https://github.com/siyuan-note/siyuan/assets/57566668/1835d925-717b-40e9-a5e9-55ff8bf1ff12)

> Android 选中是横排，但是我们这个选项有点多，如果横排可能需要移除几个不常用的选项。

**Comment by Vanessa219** [comment]
这两个加号合并为一个吧

**Comment by gdy106** [comment]
> 这两个加号合并为一个吧

都行，我就提供一个横排菜单的思路。我是觉得非必要的选项可以不出现，点+号选择了复制还是粘贴，接下来跳出的选项就可以少一点。
不过两行也不算多，反正塞得下，放一起也可以。
要进一步精简还可以把复制粘贴和剪切的文字删掉，仅保留图标。毕竟图标足够直观了。（当然，反过来也可以，删图标仅保留文字）
