### ISSUE TITLE
self-xss

### ISSUE THREAD

**Issue by Mete0r666** [siyuan-note/siyuan#8830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在粘贴代码时，程序会自动执行html 语句，可产生xss效果，虽然使用有限，但是也存在一定安全风险。
payload：<html><script>alert(document.cookie)</script></html>

<img width="853" alt="image" src="https://github.com/siyuan-note/siyuan/assets/19746164/e972f24d-2086-4a80-83d1-55fb4e0faf4f">

### Expected result

识别复制字符，以html开头不作为页面执行

### Version environment

```markdown
- Version: 2.9.6
- Operating System: 
- Browser (if used):
```

### Log file

a

**Comment by zxhd863943427** [comment]
siyuan一直是不过滤xss攻击的，因为执行脚本是html块需要的功能。

**Comment by 88250** [comment]
是的，HTML 块没有 XSS 过滤，先这样吧，后面如果安全问题突出我们再想办法，感谢反馈。

**Comment by 88250** [comment]
后续 https://github.com/siyuan-note/siyuan/issues/11172
