### ISSUE TITLE
希望社区贡献者支持swagger展示

### ISSUE THREAD

**Issue by silence-coding** [siyuan-note/siyuan#8836]
### In what scenarios do you need this feature?

在做需求设计的文档时，我们经常用swagger承载接口的设计

### Describe the optimal solution

能否实现像IntelliJ IDEA 打开swagger的效果

### Describe the candidate solution

将swagger描述的关键接口信息展示出来也可

**Comment by 88250** [comment]
这个需求考虑插件实现，感谢提议。

**Comment by silence-coding** [comment]
可能与https://github.com/siyuan-note/siyuan/issues/4293关联
