### ISSUE TITLE
提及简化,仅文档块,一级标题块,二级标题块会被检索出现在别的文档块内容中

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#884]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在需要查看有哪些其他文档块的内容提及本文档块时,据观察现提及是所有标题块和文档块都会被进行检索,此时当标题块内容较简单时会出现大量提及,造成[提及]功能本身的无效化
![image](https://user-images.githubusercontent.com/11732858/103326252-62e43f80-4a8a-11eb-92d6-7cd04837362e.png)

### 描述最优的解决方案 Describe the optimal solution
用户可选细化至哪一层标题,如一二三级标题均可被提及,一二三四级标题可被提及,仅文档块可被提及等

### 描述候选解决方案 Describe the candidate solution
文档块及一二级标题块会被提及就可以,用户可根据需求,设置标题块的等级

**Comment by 88250** [comment]
感谢反馈，估计会简化到顶层容器块这一级，即文档块的直接子块。


我们在 https://github.com/siyuan-note/siyuan/issues/874 中一并考虑，谢谢。

**Comment by frankli998** [comment]
希望恢复默认显示文档块，或者加入过滤让用户自行选择。
