### ISSUE TITLE
Please add some instruction on how to add a new notebook

### ISSUE THREAD

**Issue by raelb** [siyuan-note/siyuan#8840]
### In what scenarios do you need this feature?

The user guide says:
![image](https://github.com/siyuan-note/siyuan/assets/13108198/5eea478b-2ab6-4500-892b-346b74f11551)

I saw no button to add a new notebook, so I am wondering how one can do this..

### Describe the optimal solution

The same block could include some information on how to achieve this.
Thanks

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/75ab1c95-76e5-421d-8968-b25ad8baa09e)

We'll add a little clarification later, thanks.
