### ISSUE TITLE
PDF 阅读支持前进、后退

### ISSUE THREAD

**Issue by HoollyFox** [siyuan-note/siyuan#8842]
### In what scenarios do you need this feature?

阅读 pdf 跳转的时候返回原先位置没有途径，现在的 pdf 阅读交互仅能上下翻页和到结尾、开头。

### Describe the optimal solution

增加前进、后退的功能，且配置快捷键（比如 cmd+left, cmd+ right）

**Comment by 88250** [comment]
抱歉了，这个实现不了，之前有过提议 https://github.com/siyuan-note/siyuan/issues/3780
