### ISSUE TITLE
gomobile 编译安卓报错

### ISSUE THREAD

**Issue by hac425xxx** [siyuan-note/siyuan#8844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

报错如下
![image](https://github.com/siyuan-note/siyuan/assets/56855299/fe62ddc0-8198-4d69-8456-e9ae6eed9b9e)

### Expected result

x

### Version environment

```markdown
- Version: Master dev 都测试过
- Operating System:  win11
- Browser (if used):
```

### Log file

x

### More information

x

**Comment by 88250** [comment]
感觉是 gomobile 环境的问题，试下把所有 sdk 都更新到最新版看看。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
