### ISSUE TITLE
编译安卓版本后运行报错  - 网页无法打开

### ISSUE THREAD

**Issue by hac425xxx** [siyuan-note/siyuan#8847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/56855299/64a266a0-38fb-4569-89c1-0069236b156f)

工程：
![image](https://github.com/siyuan-note/siyuan/assets/56855299/ef079329-5284-4be5-af50-5900f46e2338)

### Expected result

能正常运行

### Version environment

```markdown
- Version: android 
- Operating System: 
- Browser (if used):
```

### Log file

x

**Comment by 88250** [comment]
你好，我一下子也看不出问题来，请参考一下这篇可能会有帮助 https://zhuanlan.zhihu.com/p/627080063
