### ISSUE TITLE
admonition 支持

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#885]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

使用思源编辑mkdocs (material) 文档时.

### 描述最优的解决方案 Describe the optimal solution

实现admonition 的渲染支持

### 描述候选解决方案 Describe the candidate solution

部分实现: 识别admonition 语法, 用现有样式, 如blockquote, 包起来 

### 其他信息 Other information

关于admonition:
- https://squidfunk.github.io/mkdocs-material/reference/admonitions/
- https://python-markdown.github.io/extensions/admonition/

**Comment by 88250** [comment]
请参考 https://github.com/siyuan-note/siyuan/issues/856 回复，谢谢。
