### ISSUE TITLE
Improve attribute panel

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8855]
![image](https://github.com/siyuan-note/siyuan/assets/873584/d9c876bf-1fae-4d4a-a1eb-34f3a8305bab)

**Comment by 88250** [comment]
@mozhux 等插件吧

**Comment by mozhux** [comment]
> @mozhux 等插件吧

插件还能读这些信息吗？有相关接口就行，方便看和改

**Comment by 88250** [comment]
读写属性都可以的，早就有[接口](https://github.com/siyuan-note/siyuan/blob/master/API_zh_CN.md#%E5%B1%9E%E6%80%A7)了。
