### ISSUE TITLE
swap lines and blocks up and down

### ISSUE THREAD

**Issue by omega3** [siyuan-note/siyuan#8856]
### In what scenarios do you need this feature?

Please, add option and custom shortcut for swapping text lines and blocks (instead of drag and drop for people who are more keyboard oriented). This would speed up writing and organizing notes and thinking.

### Describe the optimal solution

Here is an example from Obsidian

https://youtu.be/6Hn1_UMTgPo?t=320

**Comment by zxhd863943427** [comment]
You may want to take a closer look at the shortcuts provided, because shift+ctrl+arrow is probably what you need
