### ISSUE TITLE
Hope to provide console output for the kernel

### ISSUE THREAD

**Issue by LinuaBio** [siyuan-note/siyuan#8857]
### In what scenarios do you need this feature?

![ac77998a7e5d7ebe467a150a04a000c0](https://github.com/siyuan-note/siyuan/assets/104708810/d9f00908-1ba4-4afc-a526-d74bcffccd44)
这是调用API: "/api/block/insertBlock" 出现的，而且该错误是否出现是有概率事件，而不是确定事件

![image](https://github.com/siyuan-note/siyuan/assets/104708810/f3033f74-f91f-4e9e-b16e-6b072d61b445)
这是具体代码，经排查，是API的问题，但是不知道为什么出错，

在这个情况下，我希望知道报错的具体原因，以便排查错误。

所以请求能够看到内核控制台输出，报错的具体原因

### Describe the optimal solution

1. 在弹出”状态异常“的同时，向浏览器控制台输出内核报错的具体原因，报错的代码位置
2. 加入新的API，能够查看内核输出

**Comment by 88250** [comment]
看下内核日志文件，里面有报错信息。
