### ISSUE TITLE
切换页签时光标跳回先前光标编辑位置而不是先前浏览位置

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

其他人的反馈，但情况可能比我遇到的更复杂：https://ld246.com/article/1690770975769

复现步骤：
编辑文档1，继续阅读文档1
打开文档2
回到文档1

近期的版本都有这个问题。

### Expected result

希望能正常记住浏览位置，我在编辑中经常遇到这个问题，会被打断操作体验不是很流畅

### Version environment

```markdown
- Version: 2.9.7
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by chenshinshi** [comment]
评论中我还提到有时切换页签后先前编辑的文字片段会进入选中状态。如添加评论的文字。

**Comment by Vanessa219** [comment]
这个问题是改进 https://ld246.com/article/1673704873983/comment/1673765814595#comments 造成的，目前只能再改进一下：如果编辑器宽度不变的情况下，就不对其进行定位。
