### ISSUE TITLE
链接功能优化

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#886]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
[链接]排除内部链接,相对于我们知道文档块内的内部引用,我们更想知道的其实是外部哪些文档,也引用了本文档的内容(我知道了文档内部进行了10次互链,然后呢?)
![image](https://user-images.githubusercontent.com/11732858/103326299-b191d980-4a8a-11eb-87d5-a52727f34847.png)

### 描述最优的解决方案 Describe the optimal solution
有一个开关可以控制如下四种状态供用户选择
1.[链接]仅显示外部的链接引用
2.[链接]显示内部+外部的链接引用
3.[链接]仅显示内部的链接引用
4.[链接]分为[内部链接]和[外部链接]两部分进行显示

### 描述候选解决方案 Describe the candidate solution
直接去掉内部的链接引用

**Comment by 88250** [comment]
感谢反馈，直接去掉文档内的链接（你提到的候选方案）似乎不错，稍后我们再考虑一下。

**Comment by 88250** [comment]
v0.5.6 后文档内的引用不会计入反链了，我们先这样，等以后再看看，谢谢。
