### ISSUE TITLE
滚轮放大字体后行号的位置发生错位

### ISSUE THREAD

**Issue by Mete0r666** [siyuan-note/siyuan#8861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

滚轮放大子弟 行号的位置发生错位
<img width="735" alt="image" src="https://github.com/siyuan-note/siyuan/assets/19746164/5184e4ab-52af-4f2a-83f7-5f9ed95a4cb6">

### Expected result

<img width="735" alt="image" src="https://github.com/siyuan-note/siyuan/assets/19746164/d7ca3f22-eb1b-4cab-b725-41b14d031884">

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

0

**Comment by 88250** [comment]
你好，我在默认主题下无法重现该问题，方便的话请录屏演示操作。

![image](https://github.com/siyuan-note/siyuan/assets/873584/e129f58a-dfa7-49cd-8cfb-6c045dfa07e0)

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
