### ISSUE TITLE
Inline Code block at the end of line not wrapping properly

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

I feel the trailing "empty inline code block background" pointed in the below image should not be there.
<img width="915" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/e9209a7b-d5e3-4480-bbdd-8089a1b5f513">

### Expected result

<img width="905" alt="image" src="https://github.com/siyuan-note/siyuan/assets/42742240/9a284124-16b8-47f4-aa9c-e5ba470f28c2">

### Version environment

```markdown
- Version: 2.9.7
```

### Log file

\-

**Comment by 88250** [comment]
Sorry, there is still no way to solve this problem, we have tried it before https://github.com/siyuan-note/siyuan/issues/8104
