### ISSUE TITLE
ipad端无法记住打开页签的状态

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

切换主题或者重启软件新打开的页签还是关闭的页签都没有记录。

### Expected result

希望能正常记录。

### Version environment

```markdown
- Version: 2.9.7
- Operating System: ipad
- Browser (if used):
```

### Log file

无需

**Comment by chenshinshi** [comment]
演示视频已发邮件。

**Comment by 88250** [comment]
窗口状态只有在切换应用或者正常退出时才能记录，直接划走关闭无法记录的。

**Comment by chenshinshi** [comment]
可是我在设置-关于-退出应用，退出，也无法记住状态。

**Comment by 88250** [comment]
切换应用后再退出呢？

**Comment by chenshinshi** [comment]
切换应用是指？例如我从思源划到浏览器再划回思源，标签没有变（思源在后台没有关闭），但是退出后重进就又没有记住了。

**Comment by 88250** [comment]
收到，这个问题我们没有 iPad 设备，所以没法排查，先记录一下 https://github.com/siyuan-note/siyuan/issues/4238
