### ISSUE TITLE
有什么办法能够去掉command

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8867]
### In what scenarios do you need this feature?

我在做的插件中有一些命令只有使用一些特别的设置才会有，如果全都列出来未免太影响观感了，所以希望能够有一个方法修改已经添加的command（或者干脆有个方法能够直接重置所有命令也行）我试了一下把commands赋成空列表然后再添加，但是会报下面这个错，应该是因为本体只是在特定时间读取的吧

![image](https://github.com/siyuan-note/siyuan/assets/63407442/a3d86e7d-2388-44b3-9ef5-cd02aee106e2)

### Describe the optimal solution

可以提供一个重新载入command的方法，这个应该比较好做

**Comment by Vanessa219** [comment]
这个可以权衡一下不要调用加入的方法就可以了。
