### ISSUE TITLE
文件、文件夹等自定义顺序

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#887]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
查看文件树时候，希望文件和目录按照自己想要的顺序排列
因为顺序也是一种重要的信息，比如 依赖先后、难度递进、重要性、优先级、时间先后、综合先后…
希望 文件树本身可以携带这些重要的信息

### 描述最优的解决方案 Describe the optimal solution
提供 文件树 自定义排序的 开关，比如在设置中，或右键文件树标签可以开启/关闭
开启后调整为 自定义 顺序，并开启顺序调解的功能

顺序由用户拖拽完成：
和移动文件操作一样，只不过放置到同级文件位置时候识别为移动文件顺序到当前文件

提供选中文件时候快捷键上下移动：
同级文件/文件夹可能很多，拖动可能比较费劲，故提供快捷键方式
最好还可以提供 移动到头/尾 快捷键

选中文件右键新建文件：
新建文件顺序为选中文件的位置

### 其他信息 Other information
顺序的笔记系统各个概念广泛存在：
文件内部 各个块的顺序，还可以在大纲中拖动/移动
列表表项的顺序
行的顺序
标签栏的标签的顺序
打开窗口的顺序

由上倒下也是我认为从重要到相对不重要的顺序（可见顺序广泛存在）
在快捷键上可以考虑统一一下（希望可以提高一下顺序功能的 开发优先级顺序 谢谢！！！）

**Comment by 88250** [comment]
你好，感谢花时间提出建议和帮忙考虑，但目前实现不了，请见谅。

https://github.com/siyuan-note/siyuan/issues/662
