### ISSUE TITLE
Support for searching asset content

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8874]
Assets that can be parsed as text, such as:

* .txt
* .md
* .docx
* .xlsx
* .pptx

Dependencies:

* https://github.com/sajari/docconv
* https://github.com/qax-os/excelize

---

This is a one-time payment PRO feature, for more details please visit https://github.com/siyuan-note/siyuan/issues/8906

**Comment by DereckZhang** [comment]
hope it will support PDF files

**Comment by 88250** [comment]
> hope it will support PDF files

PDF parsing has not yet found a suitable open source library, so it is currently impossible to support this format, sorry.

**Comment by DereckZhang** [comment]
> > hope it will support PDF files
> 
> PDF parsing has not yet found a suitable open source library, so it is currently impossible to support this format, sorry.

It seems like docconv support pdf files.(at least in its README)

**Comment by 88250** [comment]
@Zuoqiu-Yingyi ledongthuc/pdf doesn't work, I've tested it and can't parse the text.

UniPDF may be possible, but this requires the purchase of a license, which is a bit expensive.

![image](https://github.com/siyuan-note/siyuan/assets/873584/6cd553dd-8878-49f1-8adf-83958cb35ade)

**Comment by 88250** [comment]
感谢反馈，下个版本更新。



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 16, 2023 12:04 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support for searching asset content (Issue#8874)




 

 
帮助文档改更新了
