### ISSUE TITLE
Cannot select `Again` for spaced repetition

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#8875]
间隔复习

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/107289739/a26c01db-a7f0-46d1-a647-186a1e598531)
，更新后，重来选择不了

### Expected result

。

### Version environment

```markdown
- Version: 最新
- Operating System:win11 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12225518/siyuan.log)

**Comment by hackerhui** [comment]
up +1 @88250
