### ISSUE TITLE
在浏览器端使用思源时，增加按住shift键然后鼠标右键，显示浏览器系统自带的右键选项

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#8880]
### In what scenarios do you need this feature?

浏览器本身的右键菜单含有很多的功能，加上安装不少的插件之后可以提高浏览器页面使用效率，目前思源笔记目录右键是使用思源内部的菜单，如下是思源的右键显示
![image](https://github.com/siyuan-note/siyuan/assets/72953189/af609323-efca-49e7-8fb3-37776208945f)

个人在使用jupyterlab的时候，发现它的文档中同时支持右键显示内置的目录（下图一），在同时按住shift点击右键时（下图二）
jupyter文档介绍：https://jupyterlab.readthedocs.io/en/latest/user/interface.html
The browser’s native context menu can be accessed by holding down Shift and right-clicking:
可以通过按住 Shift 并右键单击来访问浏览器的本机上下文菜单：

![image](https://github.com/siyuan-note/siyuan/assets/72953189/261ebbbc-5b2a-4ad3-bafd-db5d91559756)
![image](https://github.com/siyuan-note/siyuan/assets/72953189/0b78d893-5f32-4569-b9b8-f590417e6254)

### Describe the optimal solution

shift+右键支持显示浏览器原始的右键菜单（context menu）

**Comment by Vanessa219** [comment]
sdf
