### ISSUE TITLE
能否支持类似飞书文档的高亮块

### ISSUE THREAD

**Issue by Joe-2002** [siyuan-note/siyuan#8883]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/56438623/e4b25c1c-9941-432f-b965-4fea85967142)
能否支持类似飞书文档的高亮块

**Comment by hackerhui** [comment]
外观样式即可实现 ctrl+art+x
![image](https://github.com/siyuan-note/siyuan/assets/42575324/54e3dbca-fe84-46a4-80c0-5d559bcf6afb)

**Comment by Joe-2002** [comment]
希望能够支持自定义样式，上述实现一行的高亮，需要打开配置多次样式，快捷键只能快速变化为最近的一次更改（如：高亮我需要配置字体颜色、背景颜色、字体大小）多种步骤，而快捷键只能实现一个步骤的快速变化。希望能够增加自己新建的样式，进行管理
