### ISSUE TITLE
能否支持表格单独导出成excel

### ISSUE THREAD

**Issue by CNJackyYe** [siyuan-note/siyuan#8884]
### In what scenarios do you need this feature?

在日常使用过程中经常会用到表格插件，但是有时候需要把记录的表格输出成excel文件转发给其他人。
但是markdown的表格实在是不方便转换，希望可以在表格控件里新增单独导出excel文件选项。

### Describe the optimal solution

现在使用的是：[tableconvert](https://tableconvert.com/)这个网址

**Comment by 88250** [comment]
你好，这个不考虑了，后续看下是否有插件，感谢提议。
