### ISSUE TITLE
Question - directory structure of SiYuan notes

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Hi team, when setting up git repository for SiYuan notes, few doubts came up. Can you please guide me.
- Is there any doc which I can use to understand the directory structure of SiYuan notes so that I can rightly configure the `.gitignore` file. If no doc is there then can you please give a high level overview.

Thanks 🙏

### Expected result

\-

### Version environment

```markdown
- Version: 2.9.8
```

### Log file

\-

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/ed091807-f602-469b-991d-41d40babc0c3)
