### ISSUE TITLE
小屏窗口插入图片会出现空行

### ISSUE THREAD

**Issue by tangjiahao2001** [siyuan-note/siyuan#8887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/72953189/341d4974-8b95-4135-ab34-76255e809c52)

![image](https://github.com/siyuan-note/siyuan/assets/72953189/31a2aaf9-57a3-426a-afbd-9e8fe4718384)

如图，使用的是浏览器，第一图是全屏显示，插入图片之后，后面没有多出一个空行来，但是当我把浏览器窗口小化，这个后面慕明奇妙多出一个空行，使用backspace删除的时候会删除了图片

![image](https://github.com/siyuan-note/siyuan/assets/72953189/668a0ff4-d5a3-400c-be61-b32ca72aa13c)
如上图，空行和图片是属于同一个块

### Expected result

窗口小化时不要出现换行

### Version environment

```markdown
- Version: 2.9.6
- Operating System: windows
- Browser (if used):Edge
```

### Log file

没有运行错误

**Comment by Vanessa219** [comment]
我按照你的描述没有空行，是那里操作不对么？

https://github.com/siyuan-note/siyuan/assets/970828/3f777c98-d290-42b3-836a-54c9a9a91a19

**Comment by tangjiahao2001** [comment]
我是用docker部署的，使用平台是edge浏览器

**Comment by Vanessa219** [comment]
你用 chrome 试一试，我电脑上没有 Edge，在 Chrome 上是正常的。

**Comment by tangjiahao2001** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/72953189/7f1906f2-2204-4393-a57c-deff4bc16b60)

![image](https://github.com/siyuan-note/siyuan/assets/72953189/c5cc0c07-483b-4355-89d8-2377075f2c45)
仍然有

**Comment by 88250** [comment]
麻烦把这个文档导出 .sy.zip 发给我们调试看看 845765@qq.com

**Comment by tangjiahao2001** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/72953189/ddf0d037-53f4-448b-a4c1-af6c72616367)

确定这个不是自己使用的换行，因为插入的很多图片都是这样。有时候在小窗口的时候，插入图片就出现了

**Comment by 88250** [comment]
我这里还是无法重现问题：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/873584/cf97f6cf-c6e7-4f7a-9f9d-d8e85ba56b98)

你可以试下默认主题并关闭所有代码片段和插件等扩展看看能否重现。

**Comment by tangjiahao2001** [comment]
我试了前面说的多种可能性，依然出现了这个问题，不缩小屏幕就是正常，一旦缩小就会出现问题。

尝试修改为不同的主题，以前使用的一个主题zhang-light没有问题，目前商城的一个比较火的主题瑞姆工艺也没有问题。但是官方主题daylight、pink-room和mini-vlook都会出现空行

![image](https://github.com/siyuan-note/siyuan/assets/72953189/0d138317-d399-4da9-9e52-f6dcd24d956f)

![image](https://github.com/siyuan-note/siyuan/assets/72953189/bef72d7f-619d-4930-9fbf-a9fefaa83c07)

**Comment by 88250** [comment]
建一个新的工作空间看看能否重现。

**Comment by tangjiahao2001** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/72953189/f7e65b8a-b9cb-4b4a-9668-3ac8ad726b8d)
建立一个新的工作空间之后就正常来了！感谢！！！从来没有用过自定义主题配置，都是安装主题商店的，不知道为什么突然就变成这样了

**Comment by 88250** [comment]
估计是什么扩展影响了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月3日(周四) 晚上10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 小屏窗口插入图片会出现空行 (Issue #8887)




 

 建立一个新的工作空间之后就正常来了！感谢！！！从来没有用过自定义主题配置，都是安装主题商店的，不知道为什么突然就变成这样了

**Comment by tangjiahao2001** [comment]
哎
