### ISSUE TITLE
全选功能优化

### ISSUE THREAD

**Issue by o-ut-man** [siyuan-note/siyuan#889]
现在全选时是直接选中文档全文， 最好能第一次点全选，只选中当前块的内容，方便删除或修改。第二次点全选，才是选中全文。

**Comment by 88250** [comment]
感谢建议，后期考虑。

**Comment by Vanessa219** [comment]
删除可使用 <kbd>Ctrl+Shift+X</kbd> / <kbd>⇧⌘X</kbd> 快捷键
