### ISSUE TITLE
Search does not accept case insensitive diacritics search

### ISSUE THREAD

**Issue by sdnnvs** [siyuan-note/siyuan#8893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Search does not accept case insensitive diacritics search. Even with the insensitive case option checked in the Settings, the search distinguishes the same word with and without diacritical characters. For example, the word "maçã" (apple in Portuguese) cannot be located if the term used in the search is "maca".

### Expected result

The expected result is that the search, with the insensitive case option checked, accepts words with and without diacritical characters as synonyms.

### Version environment

```markdown
- Version: 2.9.8
- Operating System: Windows 11 Pro
- Browser (if used):
```

### Log file

none

**Comment by sdnnvs** [comment]
From "Query syntax" page, about Case Sensitive:

"The disadvantage of this is that it increases disk space usage and reduces indexing performance, but there is currently no better solution, so it can only be done first. In addition, Unicode case folding and diacritics are not supported, only English letters are supported ignoring case.

If you have a better implementation, please let us know, thank you very much."

**Comment by 88250** [comment]
Unicode case folding is currently supported (we will update the docs later), but diacritics are still not supported, thanks.

**Comment by SolarDesalination** [comment]
Hi, will case sensitivity be fixed in the next release? If I search for "kunming" nothing appears in the search. If I search for "Kunming", the file or reference will appear. This is definitely a bug based on english users workflow.

Diacritics would also be helpful for the Brazilian/Portuguese gang.

**Comment by 88250** [comment]
@SolarDesalination 

![image](https://github.com/siyuan-note/siyuan/assets/873584/17b4a16f-e209-4086-af68-af1edacef156)
