### ISSUE TITLE
在图片的资源文件菜单中添加重命名功能

### ISSUE THREAD

**Issue by StarDustSheep** [siyuan-note/siyuan#8896]
### In what scenarios do you need this feature?

在用户进行笔记编辑的时候，插入图片是常有的事。而如果一个图片用户想在多个地方多次使用的话（不是指emoji这种多次使用的小图片，而是指想多次使用的中、大尺寸图片，emoji受样式限制只能以一个很小的尺寸显示出来），则很不方便，原因如下：

用户往往是直接在浏览器或别的软件中直接将图片的图像信息复制到剪贴板，这是最简单最轻松的操作。而这样复制到思源的编辑器中时，并不会有包含关键词的文件名。而如果文件名没有关键词，则用户想用斜杠菜单中的插入资源的功能来再次插入之前存过的图片就变成一件几乎不可能的事情。

![image](https://github.com/siyuan-note/siyuan/assets/114859111/31198fa2-4e62-4948-b9d6-974cef22cfd9)
在资源路径中改动文本并不能重命名该图片
![image](https://github.com/siyuan-note/siyuan/assets/114859111/409a81e2-bc4c-464d-921e-2f81401ba711)

诚然，用户也可以在系统的资源管理器中自己手动修改文件名，然后在思源里也修改一次图片资源路径来达到修改图片资源文件名的效果，但这实在是太麻烦了。

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/114859111/9d6ee9fb-87d4-4082-81d3-436d4cfe61cd)
对于视频资源文件，当前是可以重命名的

![image](https://github.com/siyuan-note/siyuan/assets/114859111/172d504f-90b0-4276-8178-1c109b423c3e)
希望在图片右上角通过三点按钮打开的菜单中，也能重命名该图片，这样用户就能轻松地将部分图片修改名称，以在日后撰写文档或是编写笔记的过程中，通过斜杠菜单-资源，通过关键词搜索出自己想要的图片。

![image](https://github.com/siyuan-note/siyuan/assets/114859111/151e3b18-b159-43bd-ab2e-33df1abde15b)
比如这样

**Comment by 88250** [comment]
已经有重命名了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/533841df-753d-40f1-a779-5a71fb177582)

**Comment by StarDustSheep** [comment]
不好意思是我瞎了

**Comment by StarDustSheep** [comment]
快快快删了这issue吧丢人死了Σ(lliдﾟﾉ)ﾉ

**Comment by 88250** [comment]
没事的，放轻松。

**Comment by Geo123abc** [comment]
@88250 ，这个功能非常好啊，相见恨晚，但是我刚才测试过程中偶然发现一个bug，以下是我的测试过程和心得：

“重命名”图片的assets名字过程推断：

1. 复制这个图片文件并赋予副本一个新名字，
2. 然后在整个思源工作空间的文档中查找（关键词是“旧名字+时间随机码”）、替换（新名字+时间随机码）
3. 替换之后，思源笔记会有一个类似重启的动作（冷启动时的标志）


实操：

在多个文档里面分开粘贴下面这个（也就是多个地方使用assets下的一个图片文件）


```md
![原来的文件名-测试重命名功能.png](assets/原来的文件名-测试重命名功能-20230803174145-np5h79a.png "原来的文件名-测试重命名功能（在文档A中的第一个）")

![原来的文件名-测试重命名功能.png](assets/原来的文件名-测试重命名功能-20230803174145-np5h79a.png "原来的文件名-测试重命名功能（在文档A中的第二个）")

![原来的文件名-测试重命名功能.png](assets/原来的文件名-测试重命名功能-20230803174145-np5h79a.png "原来的文件名-测试重命名功能（在文档B中的第一个）")

![原来的文件名-测试重命名功能.png](assets/原来的文件名-测试重命名功能-20230803174145-np5h79a.png "原来的文件名-测试重命名功能（在文档B中的第二个）")
```


重命名之后，分散在各个文档里面的文件会被重命名，不会失效，各个图片的“标题”和“提示文本”也会保持不变，并且在“设置--资源”里面应该会多出来一个未引用图片（重命名前使用的名字），清除即可【这个地方不知道是否考虑自动清除？】。


**但是有一个bug**，如果文档里面恰好有这个图片全名，比如上面这个md代码块里面的内容，也会被改变为下面这样

```md
![原来的文件名-测试重命名功能.png](assets/重命名之后的文件名-测试重命名功能-20230803175212-zk2xcsd.png "原来的文件名-测试重命名功能（在文档A中的第一个）")

![原来的文件名-测试重命名功能.png](assets/重命名之后的文件名-测试重命名功能-20230803175212-zk2xcsd.png "原来的文件名-测试重命名功能（在文档A中的第二个）")

![原来的文件名-测试重命名功能.png](assets/重命名之后的文件名-测试重命名功能-20230803175212-zk2xcsd.png "原来的文件名-测试重命名功能（在文档B中的第一个）")

![原来的文件名-测试重命名功能.png](assets/重命名之后的文件名-测试重命名功能-20230803175212-zk2xcsd.png "原来的文件名-测试重命名功能（在文档B中的第二个）")
```

**Comment by 88250** [comment]
> 【这个地方不知道是否考虑自动清除？】

为了保险起见，不自动删除。

---

目前用的是全部替换（类似于 IDE 里面的函数重命名，会把注释也考虑在内），这个暂时不认为是 bug，等更多反馈后再看。

**Comment by Geo123abc** [comment]
> > 【这个地方不知道是否考虑自动清除？】
> 
> 为了保险起见，不自动删除。
> 
> 目前用的是全部替换（类似于 IDE 里面的函数重命名，会把注释也考虑在内），这个暂时不认为是 bug，等更多反馈后再看。

ok，这两点都理解，

全部替换这个像我遇到这种情况是很低概率事件
