### ISSUE TITLE
Access to the marketplace is no longer supported on Huawei devices

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8898]
华为应用市场审核不过：

![image](https://github.com/siyuan-note/siyuan/assets/873584/b0a3c0c6-2227-49e8-832d-cc5248e342b3)

![image](https://github.com/siyuan-note/siyuan/assets/873584/cb671154-6360-476b-9026-b203a1437da5)

**Comment by mozhux** [comment]
最新的似乎是不给任何有gpt的字样出现
