### ISSUE TITLE
能否将在属性面板中，将数据表页签中的某个属性设为跨数据表通用属性

### ISSUE THREAD

**Issue by lovelife88** [siyuan-note/siyuan#8899]
### In what scenarios do you need this feature?

思源笔记目前的Database理念非常先进，将数据表中的行与块绑定，属性面板作为快的自身信息，数据表只是一种展示形式。
对内测版本进行了一下测试，目前同一个块在不同数据表中的同名属性，在属性面板中作为独立的属性进行展示和编辑。
这样无法实现数据复用。
例如，客户信息数据，  性别、地址、电话号码等信息，在不同数据表中应该是相同的。

### Describe the optimal solution

建议可以对某个属性设为跨数据表通用属性，在一个数据表中修改后，其他数据表同步修改，实现数据的复用。

**Comment by 88250** [comment]
还在考虑，有可能是类似 Notion 的关联列来实现，也有可能是其他方案，还没有考虑清楚。

暂时先关闭，后续如果有相关提议会关联到这里，谢谢。

**Comment by lovelife88** [comment]
> 还在考虑，有可能是类似 Notion 的关联列来实现，也有可能是其他方案，还没有考虑清楚。
> 
> 暂时先关闭，后续如果有相关提议会关联到这里，谢谢。

两个的应用场景是不同的。关联是两个数据表格之间的关联。
而全局属性是属于块本身的，不受数据表格的限制。
例如：
客户表中有一个人员A，表格涉及属性（性别、地址、单位、电话、email等）
同学表中有一个人员B，表格涉及属性（性别、学校、爱好、专业、电话等）
现在需要新建一个重要联系人表格，属性有（性别、电话等），并把A、B都放到该表格。
如果使用关联的方式，就无法实现性别、电话两个属性数据的复用。但是块的全局数据属性的方式就很容易实现。

我认为全局数据属性可以作为思源数据表格的一个亮点，这是notion类数据表没能实现的。
通过这种设计，用户可以关注块的本身，数据表格作为展示方式。就像类和函数的区别了。
@88250

**Comment by 88250** [comment]
后面有个模板列的计划，会考虑看下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月3日(周四) 下午2:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 能否将在属性面板中，将数据表页签中的某个属性设为跨数据表通用属性 (Issue #8899)




  
还在考虑，有可能是类似 Notion 的关联列来实现，也有可能是其他方案，还没有考虑清楚。
 
暂时先关闭，后续如果有相关提议会关联到这里，谢谢。
  
两个的应用场景是不同的。关联是两个数据表格之间的关联。
 而全局属性是属于块本身的，不受数据表格的限制。
 例如：
 客户表中有一个人员A，表格涉及属性（性别、地址、单位、电话、email等）
 同学表中有一个人员B，表格涉及属性（性别、学校、爱好、专业、电话等）
 现在需要新建一个重要联系人表格，属性有（性别、电话等），并把A、B都放到该表格。
 如果使用关联的方式，就无法实现性别、电话两个属性数据的复用。但是块的全局数据属性的方式就很容易实现。
 
我认为全局数据属性可以作为思源数据表格的一个亮点，这是notion类数据表没能实现的。
 通过这种设计，用户可以关注块的本身，数据表格作为展示方式。就像类和函数的区别了。
 @88250
