### ISSUE TITLE
打开文件: 预览模式

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#890]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

想快速过一遍一系列文件时, 希望有类似vscode的行为: 
- 浏览文件时, 单击每一个文件, 在单个预览tab上替换显示, 预览tab只有一个;
- 双击文件, 同目前的打开行为, 新建tab;

(预览tab样式上区分于正常tab, 也可考虑将其固定在最左)
(结合思源的自动保存策略, 临时tab不允许编辑?)

### 描述最优的解决方案 Describe the optimal solution

参考vscode, 实现上述行为

### 描述候选解决方案 Describe the candidate solution

NA

### 其他信息 Other information

NA

**Comment by Vanessa219** [comment]
1. 可参见配置项
2. 有单双击的设置，因此不太好配置
![image](https://user-images.githubusercontent.com/970828/103352779-20e6e800-4ae2-11eb-9dc4-8d55f708d404.png)
