### ISSUE TITLE
自定义图标应该支持文件夹嵌套

### ISSUE THREAD

**Issue by lindalinya** [siyuan-note/siyuan#8901]
### In what scenarios do you need this feature?

看到自定义图标的功能，但是当前版本支持一级目录下的图标，嵌套的文件夹内部的图标在图标面板没有显示（应该是没有load上来）

### Describe the optimal solution

建议支持文件加嵌套

**Comment by 88250** [comment]
你好，这个设计上只支持一层文件夹分类，谢谢。

**Comment by lindalinya** [comment]
是否可以分享更多的By design原因的细节？
同时，想问一下，开发指南是不是需要更新了

**Comment by 88250** [comment]
一层已经能够表示分类了，所以没有必要多层。

开发指南有什么问题吗？

**Comment by lindalinya** [comment]
1. 海量图标下，文件夹嵌套是可以增加图标分类灵活性，方便用户查找图标
2. 没有写过go和electron，有一些疑惑，不知道是不是我理解有问题
![image](https://github.com/siyuan-note/siyuan/assets/74670117/ef179b12-5c2c-4c06-bec5-e598a876ed1c)
- 看到app文件夹下有package.json文件，为什么不是进入app目录，直接执行pnpm i
- 开发指南中并没有提及go相关的内容，自己装了go以后，build kernal完成，在执行`./SiYuan-Kernel.exe --wd=.. --mode=dev`时报错：
![image](https://github.com/siyuan-note/siyuan/assets/74670117/be1bdb2b-1565-4f21-aff6-6889db74cb10)

**Comment by 88250** [comment]
你好，还是之前说的那样，这里不考虑多层了。

1. 直接 pnpm i 我不确定是否可以，最好指定版本单独安装，我们这里的开发环境是这样做的
2. 按照提示打开 CGO 环境变量开关

**Comment by lindalinya** [comment]
1. 感谢大佬的回答，项目跑起来了
2. 看了一下相关的代码，
      1. 从代码上看是支持一级子文件夹的
      2. 二级子文件夹会被当成图标返给前端，大概率显示会乱码。既然不想要支持多级目录，建议在这之前先把文件夹filter掉
![image](https://github.com/siyuan-note/siyuan/assets/74670117/fb14f5b6-e643-4838-84b1-da648b75a8d2)

**Comment by 88250** [comment]
好的，等有空我们看下，也欢迎你提交 PR

**Comment by lindalinya** [comment]
找了一下，只看到开发指南下一个简单的pr模板文件
![image](https://github.com/siyuan-note/siyuan/assets/74670117/167d1f02-a541-4229-b190-0d7a639714fd)
（感觉这里有点歧义，改为Please create your PR to the dev branch可能比较好）
没有看到分支名规范、commit message规范等更详细的内容
新开了分支 `emoji/filter-nesting-folder-of-custom-emoticons` ，改完代码以后自测通过。
尝试pr过程中，push失败，报了403

**Comment by 88250** [comment]
需要自己 fork 仓库然后再 PR

**Comment by lindalinya** [comment]
sorry, it is my virgin pr.
Thank you for your patient response
