### ISSUE TITLE
请求闪卡筛选功能

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#8902]
### In what scenarios do you need this feature?

在思源上实现渐进阅读的过程中，发现需要这种功能。
筛选特定卡片或排除特定卡片。
### 个人设想的方案：
![image](https://github.com/siyuan-note/siyuan/assets/139356383/253d5669-f98a-432f-9b97-c863e367e234)
通过思源的闪卡增强实现的摘录
![image](https://github.com/siyuan-note/siyuan/assets/139356383/412ba0dd-a508-4fc8-98b9-806c72cfc774)
对摘录的挖空处理
---
区分摘录卡片与挖空卡片
在间隔重复中，只复习摘录卡片或挖空卡片
![image](https://github.com/siyuan-note/siyuan/assets/139356383/69bf4a62-86da-4416-963f-1288769764d5)
在思源中的间隔重复是在一个文档中直接进行的，那么就需要一种特定的筛选功能，排除或只选择某种类型的卡片

### Describe the optimal solution

个人设想的是，对卡片添加某种特征，实现标记，然后通过闪卡筛选功能来复习特定的卡片（卡片类型）。
特征可以是：
1. 属性：比如说，在闪卡增强功能中，`alt+q`功能实现的是摘录，那么在摘录（alt+q）的同时，添加了是`摘录`的属性；而`alt+w`实现挖空，那么在挖空的同时，自动添加了`挖空`卡片的属性（即此卡片是挖空卡片）。当然，属性也可以是自己设置不同类型的。
2. 标签：在卡片中添加标签，通过不同标签来区分不同类型卡片
3. 其他
从而建立卡片类型，这样就可以筛选卡片（筛选器应当在间隔重复界面）
另外，由卡片类型可以建立不同的复习模型（时间跨度，这通常可以自定义）：比如，摘录卡片我们并不怎么需要高强度的复习，只需要偶尔看一看就好，那么这里就可以设置不同的时间跨度（某某类型卡片复习强度）；而普通卡片则只需要按通常复习功能来就好了（或许也可以设置）

**Comment by 88250** [comment]
你好，这个之前考虑过，期待通过插件扩展 https://github.com/siyuan-note/siyuan/issues/7281

**Comment by gaoluji** [comment]
@88250 好的，期待ing
