### ISSUE TITLE
被引用是否可以在菜单中显示

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#8905]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/139356383/807cb3b5-f166-45a5-97ae-064067441c05)

如图，我在使用闪卡增强插件中，对摘录进行挖空，但这个摘录块由于思源渲染的原因（在闪卡界面中不能刷新），不能直接显示被引用的情况。
只能通过下方的来源去显示
![image](https://github.com/siyuan-note/siyuan/assets/139356383/0f065ae0-dd98-4090-9735-23287821cab1)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/30fb95f6-9d1a-4038-b647-60787b41039d)
只有这样才能查看挖空卡片

### Describe the optimal solution

是否可以在块菜单中添加查看链接，来查看这个块被哪些所引用，以及引用了哪些？
![image](https://github.com/siyuan-note/siyuan/assets/139356383/f66afaf7-56cd-42c8-b9cc-23155ea397c0)

**Comment by 88250** [comment]
应该有个引用计数才对，通过计数浮窗可以看引用处。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月5日(周六) 下午3:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 被引用是否可以在菜单中显示 (Issue #8905)




 
In what scenarios do you need this feature?
 

 
如图，我在使用闪卡增强插件中，对摘录进行挖空，但这个摘录块由于思源渲染的原因（在闪卡界面中不能刷新），不能直接显示被引用的情况。
 只能通过下方的来源去显示
 
 
 只有这样才能查看挖空卡片
 
Describe the optimal solution
 
是否可以在块菜单中添加查看链接，来查看这个块被哪些所引用，以及引用了哪些？
 
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by gaoluji** [comment]
@88250 但是在闪卡界面无法刷新，推出去进来又会变成别的卡片……

**Comment by 88250** [comment]
只是显示的话鼠标悬浮计数，会有浮窗。

**Comment by gaoluji** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/139356383/9b3791ef-e722-4412-bf2f-67fcbc7393bf)
使用闪卡增强摘录，然后再使用alt+w挖空
![image](https://github.com/siyuan-note/siyuan/assets/139356383/48c2b063-c73a-4d75-974d-4ce34707e20f)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/b58585ae-bbb4-4d4d-9de5-37abe6580eff)
但是闪卡界面没有刷新，只能退出去才有
![image](https://github.com/siyuan-note/siyuan/assets/139356383/a1ed4e64-f9a3-47d3-9f6e-33538295bb75)

**Comment by gaoluji** [comment]
> 只是显示的话鼠标悬浮计数，会有浮窗。

在哪？

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/65dea3d2-a3d3-4ade-a561-cb9366c2ff1a)

**Comment by gaoluji** [comment]
> ![image](https://usercontent.githubfast.com/user-images/873584/258576547-65dea3d2-a3d3-4ade-a561-cb9366c2ff1a.png)

但这个只能通过不断延伸……
如果我是一张非常孤立的卡片
![image](https://github.com/siyuan-note/siyuan/assets/139356383/906ccd0e-8f43-42c8-bbf2-a76ec9ff719a)
然后我通过alt+w挖了很多空
![image](https://github.com/siyuan-note/siyuan/assets/139356383/b7813092-d8e4-44ba-930c-d0ed6a3662b1)
但我就无法在闪卡页面直接查询了
![image](https://github.com/siyuan-note/siyuan/assets/139356383/f1fd6d90-1b8a-4ecf-9d10-370183f787ce)

**Comment by 88250** [comment]
你需要的是根据关键字搜索闪卡吗？

**Comment by gaoluji** [comment]
> 你需要的是根据关键字搜索闪卡吗？

不是啊……，那我说的简单些吧……，就是间隔重复界面没有刷新f5，我想刷新只能退出去重新点进来，但点进来后又变成换成了新的卡片

**Comment by 88250** [comment]
哦，确实没有刷新操作，复习的时候主要是记忆吧，刷新好像没有太大意义。

**Comment by gaoluji** [comment]
> 哦，确实没有刷新操作，复习的时候主要是记忆吧，刷新好像没有太大意义。

@88250 主要是实现渐进阅读，一张摘录卡片，在间隔重复时（等于回顾摘录），我会挖空，但挖空不是在原来的摘录卡片上，而是在别的文档上（这是闪卡增强插件的特性，用于实现渐进阅读的），但摘录那边不能同步显示被引用，退出去重进来的话又会变成其他的闪卡……

**Comment by 88250** [comment]
嗯，大概了解了，不过目前是支持不了这个用法的，等后面有空再看看，谢谢。

**Comment by gaoluji** [comment]
> 嗯，大概了解了，不过目前是支持不了这个用法的，等后面有空再看看，谢谢。

好的d大，我在b站也发了个视频，宣传了一下思源的间隔重复和渐进阅读【思源笔记实现渐进阅读以及间隔重复】 https://www.bilibili.com/video/BV1Z84y1f7kc/?share_source=copy_web&vd_source=4f519069f515b020073ca14e58edb897

**Comment by 88250** [comment]
大致看了下你的视频教程，我觉得也许可以试下浏览器再开一个界面，这样应该能够挖空的同时保留复习界面。

**Comment by gaoluji** [comment]
> 大致看了下你的视频教程，我觉得也许可以试下浏览器再开一个界面，这样应该能够挖空的同时保留复习界面。

@88250 ok，我试试
