### ISSUE TITLE
Add membership one-time payment PRO features

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8906]
Some features will be available as a one-time fee, including:

* [S3/WebDAV](https://github.com/siyuan-note/siyuan/issues/8780)
* [Asset content search](https://github.com/siyuan-note/siyuan/issues/8874)

Additional features may be added in the future.

One-time fee pricing:

* LianDi: ￥64 (earlybird ￥48) https://ld246.com/one-time-pay/siyuan
* LiuYun: $64 (earlybird $48) https://liuyun.io/subscribe/siyuan

The differences between FREE, PRO (one-time fee), and VIP (annually subscribe) are figured here: 
* https://b3log.org/siyuan/en/pricing.html (English)
* https://b3log.org/siyuan/pricing.html (Chinese)

By the way, LiuYun’s lifetime subscription activity is still going on, and the early bird price of lifetime subscription is $148, including all one-time pay features https://liuyun.io/subscribe/siyuan

**Comment by ognsya** [comment]
How often are new features going to be limited to paying users?

I'm considering committing to SiYuan because I have no need for sync, so I'm assuming the software would always be free for me.

However now I'm concerned that there doesn't seem to be any guarantees that new features might require paid membership in the future.

**Comment by 88250** [comment]
> How often are new features going to be limited to paying users?
> 
> I'm considering committing to SiYuan because I have no need for sync, so I'm assuming the software would always be free for me.
> 
> However now I'm concerned that there doesn't seem to be any guarantees that new features might require paid membership in the future.

Not all new features that will be added in the future need to be paid for, thank you.

**Comment by ognsya** [comment]
> Not all new features that will be added in the future need to be paid for, thank you.

I'm sure "not all" will be paid.

My concern is how often this will happen.

In any case, in order to be honest with newcomers, I suggest making this clear in your communication with users. Currently you state that "All local features are free, even for commercial use." and that "Cloud services require a paid subscription.". I suggest adding that this will change in the future. 

Otherwise people might use this assumption (that Siyuan might be free forever) and invest a lot of time and effort populating their data in Siyuan, then later be surprised to see that certain features will no longer be free.

**Comment by 88250** [comment]
> > Not all new features that will be added in the future need to be paid for, thank you.
> 
> I'm sure "not all" will be paid.
> 
> My concern is how often this will happen.
> 
> In any case, in order to be honest with newcomers, I suggest making this clear in your communication with users. Currently you state that "All local features are free, even for commercial use." and that "Cloud services require a paid subscription.". I suggest adding that this will change in the future.
> 
> Otherwise people might use this assumption (that Siyuan might be free forever) and invest a lot of time and effort populating their data in Siyuan, then later be surprised to see that certain features will no longer be free.

Don't worry about this, the existing functions do not need to be paid, and the payment is only for some new functions developed in the future, and we will clearly mark this function as a free public beta stage at the beginning of the function's launch  (like S3/WebDAV before), and there may be charges later.

**Comment by ognsya** [comment]
I appreciate your responses.

However I believe I am not explaining myself well.

If a typical user reads "All local features are free" , they assume that all local features - including future ones - will always be free, as the statement suggests that your criteria for monetisation is that (local x non-local).

I'm not saying you have incorrect information. I'm just explaining to you how it might be misleading.

I suggest at least changing this sentence to:
""**Currently**, all local features are free"

**Comment by 88250** [comment]
You are right, we have modified the README and related documents on the dev branch, please take a look at https://github.com/siyuan-note/siyuan/tree/dev

**Comment by nhan000** [comment]
Thanks @ognsya for asking these questions. I make a forum post here https://liuyun.io/article/1691268668882 for further discussion.

**Comment by unfortunatelyalex** [comment]
> By the way, LiuYun’s lifetime subscription activity is still going on, and the early bird price of lifetime subscription is $148, including all one-time pay features https://liuyun.io/subscribe/siyuan

I just want to understand this correctly, it's a one-time-payment of $148 to get the lifetime VIP? 
I can't find the text/article anymore but I swear I've read somewhere that it's an annual payment.

**Comment by 88250** [comment]
@unfortunatelyalex Hello, yes, this is LiuYun's lifetime VIP event, seats are limited (total 512, remaining 499 at present).

We will start annual subscriptions after the lifetime event is over, thanks.
