### ISSUE TITLE
强烈希望大纲列表前的 “点” 用鼠标点击即可聚焦，而非现在的3个紧挨着的均为弹出菜单（很重复）

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#8908]
### In what scenarios do you need this feature?

如下图，workflowy、remnote、幕布、logseq等软件均是如此的，已经多方验证其实用性，我记得曾经思源也是如此，不知为何某天就不是了，强烈希望改回来，谢谢！
这样无论是移动端还是电脑端都会更好用。

### Describe the optimal solution

<img width="657" alt="Snipaste_2023-08-06_15-05-46" src="https://github.com/siyuan-note/siyuan/assets/87182333/fc228b17-5d4f-4909-b5cf-e90b187914e3">

### Describe the candidate solution

无

### Other information

无

**Comment by 88250** [comment]
这个交互不再改变设计了，谢谢。

**Comment by Aiviokoo** [comment]
> 这个交互不再改变设计了，谢谢。

这个交互实在影响使用，不知道为何这样考虑呢，可以告知一下么谢谢（我相信我绝不是唯一一个想要这个交互的人，之前在群也有很多人反馈，只是他们都没上github来提，我相信未来某个时候随着大多数人反馈不合理，终究会改过来的，如果不关掉这个issues我相信很快就会有很多人鼓起勇气来这条下面评论反馈）
![image](https://github.com/siyuan-note/siyuan/assets/87182333/b35f909c-a031-4573-bcc3-d5a5ea8b6a2f)

**Comment by 88250** [comment]
之前讨论过，现在也不确定有多少用户希望改变，所以得谨慎一些。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月6日(周日) 下午3:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 强烈希望大纲列表前的 “点” 用鼠标点击即可聚焦，而非现在的3个紧挨着的均为弹出菜单（很重复） (Issue #8908)




  
这个交互不再改变设计了，谢谢。
  
这个交互实在影响使用，不知道为何这样考虑呢，可以告知一下么谢谢（我相信我绝不是唯一一个想要这个交互的人，之前在群也有很多人反馈，只是他们都没上github来提，我相信未来某个时候随着大多数人反馈不合理，终究会改过来的，如果不关掉这个issues我相信很快就会有很多人鼓起勇气来这条下面评论反馈）

**Comment by Aiviokoo** [comment]
> 之前讨论过，现在也不确定有多少用户希望改变，所以得谨慎一些。

好呢，我在社区发了一个讨论，等等大家的反馈看看：[https://ld246.com/article/1691310992434](https://ld246.com/article/1691310992434)

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/3502
