### ISSUE TITLE
Global search has file restriction applied

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Steps to reproduce:
1. Open search using `ctrl+p`, click `Remove query criteria`, then click `Save query criteria` and use the name `test`
2. Open search using `ctrl+f`, select saved query criteria (i.e. `test`), and close the panel using `Esc`.
3. Press `Ctrl+P`, the file restriction remains.
![image](https://github.com/siyuan-note/siyuan/assets/42742240/ab1de7d4-49ca-49f2-b115-43fc4320090f)

### Expected result

The file restriction should not be there when global search is opened

### Version environment

```markdown
- Version: 2.9.8
- Operating System: Linux
```

### Log file

\-

**Comment by Vanessa219** [comment]
When you "Save Query Criteria", the criteria will be preserved when you open the search.

**Comment by fenilgmehta** [comment]
Can you please share the list of items which get saved when we use "Save Query Criteria"

**Comment by Vanessa219** [comment]
* group
* Human readable path
* is replace
* search key
* Search method keywords
* replace key
* sort
* type
* id path
