### ISSUE TITLE
latex 默认环境下不支持换行

### ISSUE THREAD

**Issue by frankli998** [siyuan-note/siyuan#891]
### 描述问题 Describe the problem

如题，默认的latex环境不支持换行。
![image](https://user-images.githubusercontent.com/16791452/103332886-cbd9b080-4aa6-11eb-9288-b3df6e35417e.png)
必须要使用 array 或 align 等环境才支持换行
![image](https://user-images.githubusercontent.com/16791452/103332913-e3b13480-4aa6-11eb-8715-9214f64611eb.png)

### 期待的结果 Expected result

typora 默认支持换行
![image](https://user-images.githubusercontent.com/16791452/103332955-004d6c80-4aa7-11eb-82b0-13fc4195bf79.png)

### 版本环境 Version environment

* 版本 Version：0.5.45
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，请关注 https://github.com/siyuan-note/siyuan/issues/340
