### ISSUE TITLE
Emoji not rendering as expected

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Emoji not showing rightly:
1. 😅 does not work normally, but works fine in inline code block
2. ⚠ / `⚠` / ⚠️ / `⚠️` does not work in both regular form and in inline code block too
![image](https://github.com/siyuan-note/siyuan/assets/42742240/3470b8cb-c77d-4c20-834a-0d09b48c1177)

### Expected result

The colorful form should be rendered

### Version environment

```markdown
- Version: 2.9.8
- Operating System: Linux
```

### Log file

\-

**Comment by 88250** [comment]
Hello, this depends on system fonts, please install fonts with Emoji and try again.

**Comment by fenilgmehta** [comment]
Hi @88250, just got to know that this colorful emoji rendering is not much dependent on the system fonts. Instead it is more about the unicode character being inserted.

`⚠` is the character which SiYuan's emoji picker inserts. But, if we see `SiYuan User Guide > Please Start Here > Custom Appearance > Theme` > `INSIDE_FILE > Development > Encoding` `⚠️` is being used.

For these characters (`⚠` and `⚠️`) I ran below Python code:

```py
for char in ['⚠', '⚠️']:
    print(len(char))
    for ch in char:
        print(f'\t{ord(ch)}')
```

this is the output it gives

```
1
	9888
2
	9888
	65039
```

When I asked ChatGPT about this, following is the result it gave:

> ...there is a subtle difference in their appearances.
> 1. ⚠ (U+26A0):
>     * This is the Unicode character for the warning sign, and it does not include an emoji modifier.
>     * It is a black triangle with a black exclamation mark inside it.
> 2. ⚠️ (U+26A0 U+FE0F):
>     * This is the Unicode character for the warning sign with an emoji modifier (variant selector-16).
>     * The inclusion of the emoji modifier may result in the symbol being displayed as a color emoji, especially on systems that support emoji rendering.
> 
> ...
> In terms of semantics, both symbols are used interchangeably to convey a warning or alert. The choice between them often depends on the visual style or context of the message where they are being used.

So, I believe if we could modify SiYuan's emoji picker to insert Unicode character for emojis with an emoji modifier (variant selector-16) then this issue will get fixed.

**Comment by 88250** [comment]
Hello, I'm not sure how you inserted the Emoji characters. My test here doesn't seem to find any problems:

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/caf09a42-05a8-4cdf-abdf-d5765381c761)

**Comment by fenilgmehta** [comment]
I am doing the same as you and still facing the issue.

https://github.com/siyuan-note/siyuan/assets/42742240/b2ccb81a-ebb0-4eeb-8315-476eba11e8f6

What is the language set in SiYuan for you?

**Comment by 88250** [comment]
My operating system is Win11 Chinese version.

Please check whether the characters in the exported markdown are correct, or use developer tools to check the characters.

**Comment by fenilgmehta** [comment]
Here is the text in `.sy` file
```json
{
	"ID": "20231116143129-vx7mzu9",
	"Type": "NodeParagraph",
	"Properties": {
		"id": "20231116143129-vx7mzu9",
		"updated": "20240101181902"
	},
	"Children": [
		{
			"Type": "NodeText",
			"Data": "⚠"
		}
	]
}
```

Developer tools

![Screenshot from 2024-01-01 18-33-49](https://github.com/siyuan-note/siyuan/assets/42742240/ef964127-9400-4fb5-a4f0-c88b08a4cc87)

Markdown file content
```
⚠
```

**Comment by fenilgmehta** [comment]
When I add the character with the emoji variant, the `.sy` file looks like this:

```json
{
	"ID": "20240101183456-m3qzscy",
	"Type": "NodeParagraph",
	"Properties": {
		"id": "20240101183456-m3qzscy",
		"updated": "20240101183505"
	},
	"Children": [
		{
			"Type": "NodeText",
			"Data": "⚠⚠️"
		}
	]
}
```

**Comment by 88250** [comment]
It seems that there are indeed bugs somewhere, but they cannot be located at the moment. If it is convenient, you are welcome to help us find the bug from the source code. Thank you.

**Comment by fenilgmehta** [comment]
If I find it I will surely let you know.
Can we reopen this issue then.

Can you share a screenshot of what you see in Developer Tools in the below case.
![Screenshot from 2024-01-01 18-42-48](https://github.com/siyuan-note/siyuan/assets/42742240/6304f105-8b02-428c-9a6c-0d3d8f2669a3)

Thank you🙏

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/4b0aafd1-524f-4a5a-88ff-ae1352317df5)

![image](https://github.com/siyuan-note/siyuan/assets/873584/8dffb4bf-7a07-41c5-ba2a-a48537b4e5a8)


Thank you.

**Comment by fenilgmehta** [comment]
If I understand the situation correctly, the character getting inserted by SiYuan's emoji picker is the same for both of us. However, the font which you are using renders that emoji character colorfully even in the absence of the emoji modifier. But, for me the default font (Arial) does not do so. Arial requires the emoji modifier to display it colorfully. If I change my font to some selected other fonts (I do not recall the names as I had done testing long time back) then the emoji renders correctly.

The question is how did the emoji character with emoji modifier got used in `SiYuan User Guide > Please Start Here > Custom Appearance > Theme > INSIDE_FILE > Development > Encoding` ([link](https://github.com/siyuan-note/siyuan/blame/171b91513423811cf1eedc827cf48e3a28c293b6/app/guide/20210808180117-6v0mkxr/20200923234011-ieuun1p/20210808180303-axh6q1d/20200924095938-a9p5450.sy#L1121))

We can say that it is not a bug. But, it would be really nice to have SiYuan's emoji picker add the emoji modifier (variant selector-16) wherever needed.

I hope this helps.

Thanks
