### ISSUE TITLE
Strange behaviour when pressing tab after selecting text in code block

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. Create code block like below
    ![image](https://github.com/siyuan-note/siyuan/assets/42742240/4a0c3476-0698-4d91-9711-8698f9f66aac)
2. Click and drag the mouse from point 1 to point 2
3. Press `tab`
4. Result will look like below
    ![image](https://github.com/siyuan-note/siyuan/assets/42742240/ad0d86d4-26c0-4864-8cb0-ca3f9c56bbd4)

### Expected result

Expectation is that the selected text should just get indented. Here, something strange is happening.

### Version environment

```markdown
- Version: 2.9.8
- Operating System: Linux
```

### Log file

\-

**Comment by fenilgmehta** [comment]
Thanks for the fix.
What does `range.startContainer.nodeType !== 3` mean?

**Comment by Vanessa219** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType
