### ISSUE TITLE
Save query criteria with the same name and prompt whether to overwrite

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. Open global search
2. Click `Save query criteria`, use the word `test`, and click `Confirm` to save the query criteria
3. Repeat step 2 few times
4. Press `Esc` to close the search panel
    ![image](https://github.com/siyuan-note/siyuan/assets/42742240/e6ef0cfa-2fc3-443f-a76f-c9484f27075e)
5. Open global search again and now you will be able to see just one query criteria with the name `test`, the duplicates have vanished.
    ![image](https://github.com/siyuan-note/siyuan/assets/42742240/18367242-d2d9-43db-82ce-510908defeda)

### Expected result

If a query criteria with the same name already exists, then:
1. We should block the user from being able to click the `Confirm` button 
2. We should somehow inform or give a hint that this name cannot be used as it has already been used

### Version environment

```markdown
- Version: 2.9.8
```

### Log file

\-

**Comment by Vanessa219** [comment]
This is an overwrite operation, which allows the user to confirm whether to overwrite?

**Comment by fenilgmehta** [comment]
Prompting the user to confirm the overwrite is great, thanks 👍

**Comment by fenilgmehta** [comment]
The confirmation prompt is only shown when we click the `Confirm` button. If we press `Enter` then it does not show up, it seems to directly overwrite the existing query criteria in that case.

**Comment by Vanessa219** [comment]
Thank you, the next version will improve.
