### ISSUE TITLE
Wrong count for hierarchical level tag count

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. Create tag `task/testing`
2. Create tag `task/testing2`
3. Refresh the tag panel. The count for `task` will be shown as `1`
4. Clicking the entry for `task` will open the search panel. But, it will show `0` results
![image](https://github.com/siyuan-note/siyuan/assets/42742240/ed745982-d394-4344-8696-4b297a868273)

### Expected result

Count for `task` in the tags section should be 0.

### Version environment

```markdown
- Version: 2.9.8
```

### Log file

\-

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/331a8e8d-edd4-4dfe-b7ea-b9f9aceeb635)

**Comment by fenilgmehta** [comment]
I agree that the search is showing results. But there are two issues:
1. On clicking the number shown at Point `A` in below image, the search opens with the search text being `#test#` which results in `0` matching results (this is shown in Point 4 of the image under the `Describe the problem` section of this issue). You would have had to manually remove the trailing `#` to see the two results as shown in your image.
2. Point `A` marked in the below image is showing the count as `1`. I feel it should be `0` due to the above mentioned issue.
![image](https://github.com/siyuan-note/siyuan/assets/42742240/63c8c3b8-a101-4fdb-85d1-7b3978d73cb4)

Multiple ways to get consistency in this:
a. fix the count
b. improve the search to better handle hierarchical level tag

For the below case, what do you think should the counts be for `test` and `testing2`?
![image](https://github.com/siyuan-note/siyuan/assets/42742240/3ef2122d-9855-457e-8af2-fd1b8df46f83)

**Comment by 88250** [comment]
I understand your description, there is indeed a problem. What do you think of changing it to the following?

![image](https://github.com/siyuan-note/siyuan/assets/873584/c1dc204d-5521-452d-ac17-37083c875e7e)

![image](https://github.com/siyuan-note/siyuan/assets/873584/dd263069-6b8a-438c-bc57-6328741097a1)

**Comment by fenilgmehta** [comment]
The change looks great. Thanks for the fix 🙏
