### ISSUE TITLE
Missing bookmark labels from those mentioned in the docs

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

The `SiYuan User Guide` says: `The built-in bookmark label are ✨💡️⏳, you can create other text as the bookmark label.`
But, on opening the bookmark panel shows just one label which is `✨`

### Expected result

Either the docs needs to be updated or the missing bookmark labels need to be added.

### Version environment

```markdown
- Version: 2.9.8
```

### Log file

\-

**Comment by 88250** [comment]
We will remove the description, thanks for the feedback.
