### ISSUE TITLE
Suggestion list stops working and scrolls strangely

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

There are three issues regarding the suggestions list which is shown when we type `/`. Since the root cause seems related, I am mentioning all of them in this single issue.

#### Issue 1
Press `/` and then press `up arrow`. The UI will look like below image and then `up` & `down` arrows will stop working.
Same happens when we Press `/` and press the `down arrow` when we are on the last element of the list.

![image](https://github.com/siyuan-note/siyuan/assets/42742240/57f1e5fc-1d82-4e59-a34b-82ae6d111b79)

#### Issue 2 & 3
* Issue 2: Press `/`, down arrow, down arrow, up arrow -- the list automatically scrolls and the first entry gets hidden. Ideally there should be no movement.
* Issue 3: Press `/`, down arrow 14 times, up arrow -- strange scrolling of the list when we press the up arrow

### Expected result

* Issue 1: two possible solutions/expectations:
    1. the selection should cycle same as `cmd+tab` and `cmd+shift+tab` of MacOS -- when we keep `cmd+tab` pressed, then we reach the end of the apps list and automatically stop there. But, on pressing `cmd+tab` when at the last entry, we cycle back to the first entry. Same for `cmd+shift+tab`
    2. no movement when at the first entry
* Issue 2: no scroll should happen
* Issue 3: no scroll should happen

### Version environment

```markdown
- Version: 2.9.8
- Operating System: Linux
```

### Log file

\-

**Comment by Vanessa219** [comment]
After fixed https://github.com/siyuan-note/siyuan/issues/8881 , these issues cannot be reproduced, please try again after the next version.
