### ISSUE TITLE
Option to set tab width

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8919]
### In what scenarios do you need this feature?

In code blocks, tabs are rendered with a width of 8 spaces. Having a way to reduce this can be really useful.

### Describe the optimal solution

1. Giving an option in the settings to control this tab width can be helpful
2. If creating a new setting for this is not possible, then I suggest that we reduce the width to 4 spaces as I feel it is more commonly used at most of the other places

I guess option 1 is preferred to avoid breaking notes (e.g. Python code blocks) of existing users.

**Comment by Vanessa219** [comment]
This option can set the tab width.
<img width="1107" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/432f7841-b97d-4825-8781-0257f8ab280b">

**Comment by fenilgmehta** [comment]
There are two things:
1. `tab` key to **generate** an indent consisting of N space characters
2. `tab` characters in the file to **appear** N character cells wide
    * Currently tab characters are 8 character cells wide and not configurable

`Settings > Editor > Number of Tab Spaces` allows us to configure 1. I am talking about 2.

**Comment by Vanessa219** [comment]
Sorry, this is just an editor, and the formatting function of the IDE is not implemented in the code block, so we cannot format the code block.
