### ISSUE TITLE
音频标签 `<audio>` 体验优化

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#892]
### 描述问题 Describe the problem

![图片](https://user-images.githubusercontent.com/28727933/103349891-2855c380-4ad9-11eb-8d65-9d5400287df2.png)

 .aac 音频chrome edeg firefox 中都可以播放，但思源不可以

还有思源对于 audio 的代码编辑很差劲

### 期待的结果 Expected result

可以播放更多格式的音频，编辑体验优化

### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
编辑问题在 v1.2.0 中已经重写，等发布新版以后有空的话请帮忙提议测试，我先关闭了，谢谢。
