### ISSUE TITLE
Browser like search

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8920]
### In what scenarios do you need this feature?

When we want to search a single word in the current document (especially code block) and have them highlighted, then launching full fledged search using `ctrl+f` seems too much and also is not capable enough to highlight text in code blocks (ref https://github.com/siyuan-note/siyuan/issues/8801)

### Describe the optimal solution

Having a simple browser like search which just does simple string matching can be really useful and more performant too.
I agree that due to dynamic block loading, we may miss some matches. But, I feel we can have this information conveyed before a user enables this search or performs this for the first time.
Logseq also provides this kind of search functionality.

**Comment by 88250** [comment]
Thanks for the suggestion, but it will not be considered for the time being. If you have similar needs, you can consider using SiYuan directly on the browser.

**Comment by fenilgmehta** [comment]
Thanks, the idea to directly use the browser worked 👍
