### ISSUE TITLE
1 line comment initiative

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8921]
### In what scenarios do you need this feature?

Having a documented code makes it easy for existing team to think of corner cases, and help new contributors to understand the code and make the right changes.

### Describe the optimal solution

Hi team,
I feel that SiYuan is one of the **best** notes taking app I have seen. So, I thought of making this suggestion of adding 1 line comments to the code. I feel starting this initiative and _as per convenience_ adding just one line of description for functions & variables will have massive impact in the long run. Please feel free to ignore and close this.

Curious to know which IDE do you use for development?

Thanks a lot for this wonderful app 🙏

**Comment by 88250** [comment]
We will add comments (but maybe in Chinese) for key codes.

We use JetBrains series development (IDEA and Goland), thank you.
