### ISSUE TITLE
Option to have `Keep loaded content` always enabled

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#8922]
### In what scenarios do you need this feature?

Option to have `Keep loaded content` always enabled and not reset its value automatically can be useful and would save us from having to repeatedly enable it every time for large documents.
Currently it seems `Keep loaded content` option is shown in some limited cases (e.g. document is large) and as soon as we close and reopen that document, the value is reset.

### Describe the optimal solution

Maybe moving the `Keep loaded content` option to Settings can be a good solution.
PS: Not sure if having this option always enabled can have some unexpected side effect other than consuming more memory.

**Comment by TCOTC** [comment]
No longer limits the number of dynamically loaded blocks in the editor #12359

@88250 能不能实现比如将“动态加载块数”设置为 `-1` 时禁用动态加载？

**Comment by 88250** [comment]
就用数量限制吧



---Original---
From: "Jeffrey ***@***.***&gt;
Date: Thu, Sep 19, 2024 00:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Option to have `Keep loaded content` alwaysenabled (Issue #8922)




 
No longer limits the number of dynamically loaded blocks in the editor #12359
 
@88250 能不能实现比如将“动态加载块数”设置为 -1 时禁用动态加载？
