### ISSUE TITLE
Custom options for `/api/export/exportMdContent`

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#8924]
### In what scenarios do you need this feature?

在写插件的导出功能的时候，引用参考文献的部分要变成另一种格式，但是不希望破坏思源本身的导出markdown效果（包括今后新添加的块类型的导出效果），所以希望能够在调用导出api的时候自定义一些参数（比如我就需要把引用的导出设定为"锚文本块链"，因为要获取链接中的块id，但是我不知道用户是不是这么设置的，还是自己直接设定好比较好）

另外就是有没有办法能够读取某些设置信息？比如锚文本的包裹符号之类的，但是开这种接口有可能会触碰到用户隐私（比如ai的key），所以不开也可以理解

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/63407442/9cb8407a-80bf-471a-a2e0-0e64eef2ae8a)

这里的参数给一个options之类的

**Comment by 88250** [comment]
目前可以考虑通过变更导出配置来切换，抓包这个内部 API：

![image](https://github.com/siyuan-note/siyuan/assets/873584/f6a5975d-5787-4c31-8145-fbe21ba09134)

操作做完以后再恢复之前的配置值。

设置可以通过 window.siyuan.config 读取。
