### ISSUE TITLE
希望块标能够访问到列表块中的段落块

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#8925]
### In what scenarios do you need this feature?

有时候需要复制列表块中的一段内容到其他文档作为嵌入块，如果直接复制，由于列表块中不显示段落块，只能复制出列表块或列表项块，列表项块前面有小圆点，有时影响排版，就像下面这样
![image](https://github.com/siyuan-note/siyuan/assets/32903588/1572a34b-ca20-4f58-86c1-eea743226abc)
如果块标菜单能够显示列表块或列表项块中的段落块，这个问题就解决了，目前只能通过搜索来曲线救国
![image](https://github.com/siyuan-note/siyuan/assets/32903588/5ba5283b-203c-4050-b85c-0e4dc66537d1)

### Describe the optimal solution

所以希望能够有所调整

**Comment by 88250** [comment]
光标在段落中，然后按 Ctrl+/ 就是段落块了。

**Comment by TinkMingKing** [comment]
> 光标在段落中，然后按 Ctrl+/ 就是段落块了。

@88250 
大致没问题，但似乎有一点bug？
![2023-08-07_120451](https://github.com/siyuan-note/siyuan/assets/32903588/36855712-f020-4801-acfa-9d8d8affce90)
使用这个复制的时候，复制的不是段落块而是列表项块
