### ISSUE TITLE
Stick search and open tag automatically recognize whether to open on the right according to the width of the application

### ISSUE THREAD

**Issue by littlecoby** [siyuan-note/siyuan#8928]
### In what scenarios do you need this feature?

Currently, pressing ctrl+shift+f or clicking on tags open a search tab in a new right panel.
However, there are a few scenarios where opening in the current tab is preferred.
1. When the siyuan window is narrow;
2. When I'd like to open search results or tagged documents in the current panel, without having to drag the tabs once more.

### Describe the optimal solution

Offer an option in the setting that do not open the search tab in a new panel.

**Comment by Vanessa219** [comment]
Maybe we can automatically identify based on the application width, what is the width of your app?

**Comment by littlecoby** [comment]
> Maybe we can automatically identify based on the application width, what is the width of your app?

If switching based on the width, maybe the threshold can follow that of the setting menu (when the full size icons get switched to small ones)?

I guess what bothers me is the tag search but not the general search. For the latter, I can choose between ctrl+p or ctrl+shift+f depending on the scenario. But for the tag search, clicking on a tag always triggers a ctrl+shift+f equivalent. In addition, the global search panel can be converted to a fixed tab by a click, but the reverse does not work.

Tentative solutions:
1. As for the tag search, provide an option in the setting such that users can choose whether to trigger ctrl+p or ctrl+shift+f.
2. As for ctrl+shift+f, open in the current tab if the width is below a threshold, which is similar to the behavior of the setting menu.
3. Provide a button in the fixed search tab (ctrl+shift+f) that converts it to a global search panel (ctrl+p).

**Comment by Vanessa219** [comment]
Since there are too many configuration items at present, subsequent additions need to be evaluated for necessity. If the default value satisfies most users, no new configuration items will be added.

1. To open the tag, you can use the width of the app to identify the opening on the right or the opening of the current tab
2. Same as above
3. No other users have mentioned this requirement, and I feel that there is no usage scenario

**Comment by littlecoby** [comment]
> Since there are too many configuration items at present, subsequent additions need to be evaluated for necessity. If the default value satisfies most users, no new configuration items will be added.
> 
> 1. To open the tag, you can use the width of the app to identify the opening on the right or the opening of the current tab
> 2. Same as above
> 3. No other users have mentioned this requirement, and I feel that there is no usage scenario

Sounds ok!
