### ISSUE TITLE
编辑器默认显示标题符号的功能，能否由用户自由选择是否开启

### ISSUE THREAD

**Issue by alphaleek** [siyuan-note/siyuan#893]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
编辑文档时

用第三方主题或者自行修改各级标题颜色后，各级标题的区分十分清晰。此时在左侧默认显示标题符号，反而有点干扰文本
![image](https://user-images.githubusercontent.com/76611744/103364645-46cbb700-4af9-11eb-8049-9ce8214af5a0.png)

### 描述最优的解决方案 Describe the optimal solution
添加默认显示标题符号的开关，由用户自行选择是否开启该功能

**Comment by 88250** [comment]
你好，v0.5.6 在编辑器设置中已经加入开关，谢谢。
