### ISSUE TITLE
短时间多次setBlockAttrs接口会失败

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在插件中使用了setBlockAttrs来设置样式，返回值成功了，在思源中查看也正常，但是重新打开文档发现实际上失败了。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/dc395048-330b-4642-b0fe-bd787e2a13b3)
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/a0e9d8a5-ed5a-42a2-b1ca-8f65b147be46)

### Expected result

希望setBlockAttrs正常运行

### Version environment

```markdown
- Version: 2.9.8
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
请提供一下接口参数，谢谢。

**Comment by zxhd863943427** [comment]
{"id":"20230809232141-donjd8n","attrs":{"style":"background-color: var(--b3-font-background1);"}}

**Comment by 88250** [comment]
我这里重现不了问题，录屏如下：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/873584/43d47f5e-c760-4ac9-82f5-372e3cc035a8)


测试用例代码：

```go
package main

import (
	"log"

	"github.com/imroc/req/v3"
)

func main() {
	ids := []string{
		"20230809202353-tv2vt3o",
		"20230809202354-gjkp146",
		"20230809202354-lzhcw4r",
		"20230809202354-wh5pvle",
		"20230809202355-50yasur",
		"20230809202355-cryhmn5",
		"20230809202355-7axwp0y",
		"20230809202355-3749cjf",
		"20230809202356-9updg3n",
		"20230809202357-43ep952",
		"20230809202357-tovj8oc",
		"20230809202358-gcta1e9",
		"20230809202358-1zmuqgj",
		"20230809202359-bgvur14",
		"20230809202359-6aeq139",
	}

	for _, id := range ids {
		request := req.R()
		request.SetBody(map[string]interface{}{
			"id": id,
			"attrs": map[string]interface{}{
				"style": "background-color: var(--b3-font-background1);",
			},
		})
		response, err := request.Post("http://127.0.0.1:6806/api/attr/setBlockAttrs")
		if nil != err {
			log.Fatal(err)
		}

		log.Println(response.String())
	}
}
```

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
