### ISSUE TITLE
Support the conversion of Moc list to database

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#8939]
### In what scenarios do you need this feature?

之前大多使用列表块引的方式制作MOC，管理笔记
![image](https://github.com/siyuan-note/siyuan/assets/60436214/ebfee987-0f91-43bd-87f5-0fc848bd8669)

现在有了database，对于随笔撰写、文献书籍阅读等等有项目管理性质的笔记而言，database会更加适合，希望有一个功能，可以将moc列表（指列表文本中中只有块引的列表）快速转化为database

因为目前database只能逐行逐个选择块输入，不能批量导入数据，对已有数据的转化还是很麻烦的。也应该有一种更方面的快速生成多行database的功能。

### Describe the optimal solution

支持moc列表块引转化为database，不必太复杂，就是获取列表块中第一级列表含有的所有块引，如果一个列表项中没有块引则跳过。最后在列表块的下面创建只有block一列的database

功能可以添加在块菜单的【转化为】
![image](https://github.com/siyuan-note/siyuan/assets/60436214/3f809251-6898-4940-afc4-b3a36b81562e)

### Describe the candidate solution

none

**Comment by 88250** [comment]
这个估计不会考虑作为内置功能，等数据库基础功能完善以后看下是否有插件支持，感谢提议。
