### ISSUE TITLE
Mac客户端BUG

### ISSUE THREAD

**Issue by fengchaobio** [siyuan-note/siyuan#894]
文件树刷新MacOS客户端不可用
[文件树刷新BUG](https://tva1.sinaimg.cn/large/0081Kckwgy1gm6s7hi5vrj30zn0u074p.jpg)
关于页面无任何显示内容
[关于页面BUG](https://tva1.sinaimg.cn/large/0081Kckwgy1gm6s8l8pshj318e0u0wem.jpg)

**Comment by 88250** [comment]
你好，请尝试如下步骤：

1. 完全卸载一次
2. 删除 ~/.siyuan/ 配置文件夹
3. 重新安装后启动

如果还有问题请继续跟帖，谢谢。
