### ISSUE TITLE
行内代码无法通过中文标点正确触发渲染

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#8940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，
参考视频：

https://github.com/siyuan-note/siyuan/assets/5226690/386d89f2-fd3b-4d88-aa68-66cf21987751

同样的标点，代码块可以正确触发渲染

### Expected result

通过中文标点正确触发行内标点渲染

### Version environment

```markdown
- Version: 2.9.9
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个之前讨论过，单个 `·` 会用于人名，如果加入支持的话会产生更多不便，感谢反馈。
