### ISSUE TITLE
闪卡答题界面增加计时器读秒

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#8941]
### In what scenarios do you need this feature?

闪卡答题界面增加计时器读秒

### Describe the optimal solution

在现有的按钮最右边增加一个方框内倒计时，或者顺计时读秒

### Describe the candidate solution

提供接口让第三方插件有能力实现该需求

**Comment by 88250** [comment]
读秒的意思是倒计时吗？

**Comment by hackerhui** [comment]
@88250 是的这个时间可以从配置中读取，比如配置3分钟，那么3:00 2:59 2:58

**Comment by 88250** [comment]
这个考虑通过插件支持吧，我先关闭了，感谢提议。
