### ISSUE TITLE
please support RWKV for AI assistant writing

### ISSUE THREAD

**Issue by xiaol** [siyuan-note/siyuan#8942]
### In what scenarios do you need this feature?

Writing novel with RWKV world model, like notionai, but notion ai have very bad typesetting.

FYI:https://huggingface.co/xiaol/RWKV-claude-4-World-7B-65k

If have any question ,Welcome to contact QQ：114242123

### Describe the optimal solution

May support GPT-like API is fine, because RWKV runner is Compatibility with it .

https://github.com/josStorer/RWKV-Runner/tree/master

**Comment by 88250** [comment]
Hello, the local large language model environment is not considered for the time being, because it is difficult for common users to build it. If there are more needs, we will consider it later. Thanks for the suggestion.
