### ISSUE TITLE
Plugin API custom.fn => custom.id in openTab 

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

openTab时指定data为{}时，很容易与其他插件冲突，导致tab打不开。

源码调试时发现：
https://github.com/siyuan-note/siyuan/blob/95c0955735388d5ec76fbfa150015d2d5f1bcdf0/app/src/editor/util.ts#L103

用的是data作为判断依据，而没有进行插件名称的判断。按理说只有相同插件的相同data才考虑复用问题。

### Expected result

不同类型tab的data相同时，不冲突导致无法打开

### Version environment

```markdown
- Version: 2.9.9
- Operating System: MacOS
- Browser (if used):
```

### Log file

-

**Comment by suka233** [comment]
萌佬的pr似乎可以搞定这个问题：[#8927](https://github.com/siyuan-note/siyuan/pull/8927)

**Comment by Vanessa219** [comment]
目前没有办法识别，唯一标识需在初始化页签后才能获取的。再加一个 title 和 icon 的判断够用么？

**Comment by zuoez02** [comment]
> 目前没有办法识别，唯一标识需在初始化页签后才能获取的。再加一个 title 和 icon 的判断够用么？

@Vanessa219 或者在data里默认就放个__plugin_name__: siyuan-plugin-xxx，类似这样呗。简单有效也算。一般人也用不到它，真有需要的也能用

**Comment by Vanessa219** [comment]
openTab 是个方法，参数好像没法加上去。

**Comment by zuoez02** [comment]
> openTab 是个方法，参数好像没法加上去。

或者考虑弄个新的api替换掉这个。对于标签页希望不仅能够插件openTab，同时也希望比如刷新之后插件能获取到自己有哪些tab实例之类的，让插件可以完全掌握它所掌控的tab。

另外openTab不是有fn嘛，可以在上面做做文章，看看能不能拿到想要的上下文
