### ISSUE TITLE
Improve kernel API `/api/file/readDir` for returning file mod time

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#8945]
获取文件列表接口，支持获取文件的创建时间

### In what scenarios do you need this feature?

插件获取文件显示文件的创建时间，如果有更新时间就更好了。这样可以按照时间进行排序了。

### Describe the optimal solution

kernel中获取文件信息后增加更多的文件信息到返回值中。

**Comment by 88250** [comment]
麻烦描述接口 URL 我们确认下，谢谢。

**Comment by zuoez02** [comment]
/api/file/readDir

**Comment by 88250** [comment]
创建时间无法保证跨平台可用，暂时不加了，最后更新时间可以加，感谢提议。
