### ISSUE TITLE
有时启动会一直loading进不去

### ISSUE THREAD

**Issue by lowwor** [siyuan-note/siyuan#895]
有时启动会一直loading进不去
![image](https://user-images.githubusercontent.com/5444033/103390820-58d94400-4b51-11eb-8165-51d553f2a690.png)
报错的打印
![image](https://user-images.githubusercontent.com/5444033/103390816-537bf980-4b51-11eb-8179-8a53b9f317b6.png)
![image](https://user-images.githubusercontent.com/5444033/103390839-70183180-4b51-11eb-80db-1f73178fe0f6.png)

**Comment by 88250** [comment]
你好，请尝试如下步骤：

1. 完全卸载
2. 删除 ~/.siyuan/ 配置文件夹
3. 重新安装后启动

如果还有问题请继续跟帖，谢谢。

**Comment by Vanessa219** [comment]
做了一下加强判断，但是很奇怪数据为什么不对，你有自己改过配置么？可以的话麻烦把 n 的值文本发我一下。谢谢。
![image](https://user-images.githubusercontent.com/970828/103393559-284bd700-4b5e-11eb-9297-34504c818e53.png)
