### ISSUE TITLE
v2.9.9-iOS系统下点击下半屏的块后呼出的键盘会遮挡正在编辑的块

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#8950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

v2.9.9-iOS系统下点击下半屏的块后呼出的键盘会遮挡正在编辑的块，需要手指上滑移动到正在编辑的块。

### Expected result

正常的使用应该是在呼出键盘的同时，如果正在编辑的区域会被遮挡，就把页面上移到不会遮挡的区域。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/005dea64-128b-462c-ab48-f79a627e1691

### Version environment

```markdown
- Version: 2.9.9
- Operating System:iOS 
- Browser (if used):
```

### Log file

-

**Comment by Vanessa219** [comment]
我打开应用，打开你说的文档，然后点击是可以的。在此之前有做过其他操作么？

https://github.com/siyuan-note/siyuan/assets/970828/acdc45e6-f1d2-4ea7-aa4f-0655c190c179

**Comment by gdy106** [comment]
> 我打开应用，打开你说的文档，然后点击是可以的。在此之前有做过其他操作么？


测试过可复现。目前判断是位置判断有问题，我手机型号是SE2，当光标点击中段偏下的时候，思源仍然判断为键盘不会遮挡文字，实际上是会的。如果点击很靠下的文字呼出键盘的话则会调整位置。

https://github.com/siyuan-note/siyuan/assets/57566668/5e48d939-9793-4298-a5a4-c0b966adf99b

**Comment by Vanessa219** [comment]
已修改，还麻烦下个版本再帮忙看看。

**Comment by gdy106** [comment]
发版之后我天天点开App Store，这周都马上过去了，应用商店硬是停留在10.0不动……晕

**Comment by 88250** [comment]
@gdy106 还在等审核，估计快了。

**Comment by gdy106** [comment]
https://github.com/siyuan-note/siyuan/assets/57566668/7a946560-25d8-40dc-8ce4-7d371b1a6d15

已测试，在安卓手机上键盘呼出的体验良好，iOS上则有点问题，目前是在呼出键盘后先遮挡下半屏，然后再快速滑动屏幕露出光标，体验上比较不流畅，如果可以安卓上一样同步键盘呼出和屏幕滑动会好很多。
