### ISSUE TITLE
列表圆点鼠标左键点击改回聚焦

### ISSUE THREAD

**Issue by edward-kyle** [siyuan-note/siyuan#8954]
### In what scenarios do you need this feature?

点击列表圆点进行聚焦。
ctrl+鼠标左键点击完全是浪费了一个快捷打开方式。
听说以前是有很多人认为：直接鼠标左键点击会误触。
但是目前的直接鼠标左键点击和直接用鼠标右键点击是相同的：弹出了块标菜单。
事实上，这并没有改变误触，只是改变了误触打开了什么东西。
以前的直接鼠标左键进行聚焦，哪怕误触了，也能直接在里面码字。现在的直接鼠标左键误触却是打开了菜单，需要关闭才能进行写作。这反而让人无法专心写作了。

### Describe the optimal solution

取消鼠标左键点击列表圆点打开块标菜单的功能（鼠标左键点击、鼠标右键点击是完全一样的功能，不觉得很重复吗？）
改回鼠标左键单击列表圆点进行聚焦。之后再在快捷键设置中可以做到可以开/关是否要直接鼠标单击圆点进行聚焦。
(ps.是只能进行开关：是否需要聚焦，而不是更改快捷键。聚焦的快捷键依旧只是鼠标左键单击列表圆点。)

### Other information

本解决方案将会真正帮助那些不希望误触列表圆点的人，让他们误触也不会打开任何其他功能。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3502
