### ISSUE TITLE
Automatically expands the directory of the document where the current cursor is located

### ISSUE THREAD

**Issue by dejavudwh** [siyuan-note/siyuan#8955]
### In what scenarios do you need this feature?

When we want to access the current document's siblings, it is troublesome to re-expand the table of contents

![image](https://github.com/siyuan-note/siyuan/assets/47321059/c4177c97-9e34-426f-b2e0-7ecc93d5848f)

### Describe the optimal solution

Automatically expands the directory of the document where the current cursor is located

**Comment by 88250** [comment]
Try this:

![image](https://github.com/siyuan-note/siyuan/assets/873584/c34d0a03-4d2c-46f1-8162-81d20025beb8)
