### ISSUE TITLE
SQL 脚本占位符

### ISSUE THREAD

**Issue by copyliu** [siyuan-note/siyuan#8957]
### In what scenarios do you need this feature?

考虑 `思源笔记用户指南/请从这里开始/内容块/嵌入内容块` 中的案例场景.

场景中为了"排除当前文档" 使用了 `hpath NOT LIKE '%嵌入内容块%'` 的语法, 实际上该筛选并不准确, 考虑有一篇文档名字叫 `加强型嵌入内容块` 或者叫 `嵌入内容块使用限制` 等诸如此类的名字, 则"排除当前文档"的意图便失效.

### Describe the optimal solution

一般而言, 我们可以通过指定`path`, `hpath` 等方式限制搜索到本文档或者加%搜索到子文档, 但是需要使用`复制ID` 或 `复制可读路径`功能把需要的精确条件复制出来, 再填入到SQL中, 假设子文档层数很深的时候, 使用 `path` 来 **精确** 搜索便非常麻烦, 需要复制每一层的ID再组装起来. 而且同一句SQL拿到别处(比如box换了一个)之后可能需要重新修改. 

我建议为嵌入SQL增加数个特定的占位符, 例如 `@box @path @hpath @parent_path @parent_hpath`

实际执行时可以写成
```
SELECT * FROM blocks WHERE content LIKE '%子文档递归搜索%' AND path LIKE @path+'/%' AND path != @path;
SELECT * FROM blocks WHERE content LIKE '%子文档不递归搜索%' AND path LIKE @path+'/%' AND path NOT LIKE @path+'/%/%'  AND path != @path;
SELECT * FROM blocks WHERE content LIKE '%本笔记搜索%' AND box = @box  AND path != @path;

```
等等, 这样免去了复制ID复制可读路径的烦恼并且SQL能够直接挪到别处使用.

**Comment by 88250** [comment]
实际执行的时候并不知道如何填充变量，比如 `@box`，执行时无法确定所选笔记本。

我先关闭了，如果还有建议请继续跟帖，谢谢 :pray:

**Comment by copyliu** [comment]
这占位符指代的都是"当前脚本所在", 比如`@box`, 实际执行时都以`当前脚本所在的笔记本` 指代.

**Comment by 88250** [comment]
服务端是“无状态”的，并不知道前端请求所处位置，另外还要考虑接口的情况也是如此，所以类似变量无法填充的。

**Comment by copyliu** [comment]
能否在这个块中多保存一套SQL参数化结构, 这样就顺便能把参数化功能做了.

**Comment by 88250** [comment]
估计不太行，块可以移动位置的。
