### ISSUE TITLE
Heading convert to doc does not use naming as doc name

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8959]
标题拖拽成子文档，标题命名变成了标题

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://github.com/siyuan-note/siyuan/assets/125173405/6d398409-437a-4330-8ae2-f1118820db5c

https://ld246.com/article/1691747868688

### Expected result

希望能正常让标题内容作为标题

### Version environment

```markdown
- Version: 2.9.9
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by chenshinshi** [comment]
视频如果看不到可以下载后看

**Comment by zxhd863943427** [comment]
过于神奇了……这个我看到是改回来又改回去几次了。

**Comment by 88250** [comment]
我都不太记得了....



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 22, 2023 18:36 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Heading convert to doc does not use namingas doc name (Issue #8959)




 
过于神奇了……这个我看到是改回来又改回去几次了。

**Comment by 88250** [comment]
不过现在修改代码后基本都会带上注释，关联到修改的 issue 以便以后溯源。
