### ISSUE TITLE
右键备注判定面积

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

明明鼠标都正常触发了悬浮高亮效果，指针也有变化，但是右键似乎只有在字的右边缘才能触发。

https://github.com/siyuan-note/siyuan/assets/125173405/3b6d5e1b-470d-4d6c-9ff4-993d5f26b183

![image](https://github.com/siyuan-note/siyuan/assets/125173405/47941bb8-c59c-4f18-82a1-1787a9a09d68)

### Expected result

希望判定面积能和正常的悬浮相同。

### Version environment

```markdown
- Version: 3.0.0
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
你用默认主题试试，我这里是正常的

https://github.com/siyuan-note/siyuan/assets/970828/90f53063-a600-4e57-81b4-dd87ac35050c

**Comment by chenshinshi** [comment]
https://github.com/siyuan-note/siyuan/assets/125173405/253a144b-9f9b-41d7-add2-9dfd1bbad0ca

排除了鼠标指针和插件影响，也启用了默认主题，你可以把鼠标再往左移动下。这个判定面积问题还挺困扰的，因为有时备注是会添加给字号还要小的上标下标的。
