### ISSUE TITLE
额外功能，更多级别的标题（如h7，h8等等）

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#8961]
### In what scenarios do you need this feature?

在导入一些书籍后，发现六级标题不够用，希望能否添加一些新设置，设置添加更多的标题级别

### Describe the optimal solution

在设置中设置，看是否有人需要，需要的话就打开此功能

**Comment by 88250** [comment]
这个不考虑了，只能支持到 H6，感谢反馈。
