### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by Lizhen0628** [siyuan-note/siyuan#8962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用docker版思源
使用nginx反代
日志一直输出：http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)

### Expected result

解决 2023/08/13 11:30:17 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
和 
changelog not found: /opt/siyuan/changelogs/v2.9.9/v2.9.9.md

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/52586068/55659307-7199-4cce-a5e0-2fae2ced9d7f)

### Version environment

```markdown
- Version: v2.9.9
- Operating System: docker
- Browser (if used): chrome
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/08/13 11:28:26 runtime.go:74: kernel is booting:
    * ver [2.9.9]
    * arch [amd64]
    * os [alpine]
    * pid [1]
    * runtime mode [prod]
    * working directory [/opt/siyuan]
    * read only [false]
    * container [docker]
    * database [ver=20220501]
    * workspace directory [/home/siyuan/SiYuan]
I 2023/08/13 11:28:26 conf.go:110: initialized the specified language [zh_CN]
I 2023/08/13 11:28:26 runtime.go:128: use network proxy [system]
I 2023/08/13 11:28:26 serve.go:119: kernel [pid=1] http server [0.0.0.0:6806] is booting
I 2023/08/13 11:28:26 blocktree.go:446: read block tree [9.0 MB] to [/home/siyuan/SiYuan/temp/blocktree], elapsed [0.01s]
I 2023/08/13 11:28:26 conf.go:710: database size [99 MB], tree/block count [530/29095]
I 2023/08/13 11:28:26 working.go:154: kernel booted
I 2023/08/13 11:28:26 box.go:79: auto stat [trees=530, blocks=29095, dataSize=795 MB, assetsSize=632 MB]
E 2023/08/13 11:28:47 system.go:56: changelog not found: /opt/siyuan/changelogs/v2.9.9/v2.9.9.md
2023/08/13 11:29:22 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
2023/08/13 11:29:22 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
2023/08/13 11:29:56 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
2023/08/13 11:29:56 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
2023/08/13 11:30:17 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
2023/08/13 11:30:17 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)
2023/08/13 11:30:17 http: response.Write on hijacked connection from github.com/gin-gonic/gin.(*responseWriter).Write (response_writer.go:83)

### More information

![image](https://github.com/siyuan-note/siyuan/assets/52586068/b131fccc-b589-488b-a0c8-3ca4ac20e918)

**Comment by 88250** [comment]
你好，第一个问题多半是 NGINX 反代配置不正确导致；第二个问题 `changelog not found` 下个版本修复，感谢反馈。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
