### ISSUE TITLE
文档树单个文档内的展开与折叠

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#8964]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/139356383/405ed983-7bfc-4ba4-a7af-28356ac46c8c)
文档树只能折叠全部，但假设文档多起来，就不太好弄

### Describe the optimal solution

是否可以在对文档右键时添加一些功能：如折叠和展开
![image](https://github.com/siyuan-note/siyuan/assets/139356383/2a48a394-d851-4a58-bd3f-c590eb99f633)

**Comment by 88250** [comment]
后面可能会添加文档树的全部展开功能（不是笔记本这一级的，而是全部），先关闭这个 isuee，感谢提议。
