### ISSUE TITLE
drag and drop block from one document to the end of another document

### ISSUE THREAD

**Issue by omega3** [siyuan-note/siyuan#8965]
### In what scenarios do you need this feature?

I need this for easy organization of small blocks of text. For example on Obsidian there are plugins that can pull rss or articles from various services like Instapaper, Readwise, Pocket and append them to note / document. I hope it will be available in the future for siyuan as well. With drag and drop it will be easy to organize this constant flow of information.

### Describe the optimal solution

Click on icon that is on the left of block and drag to the destination document. It gets appended / pasted at the end of this document. I think this way small blocks = small chunks of text information could be treated similarly to files in file manager and this is very intuitive way to organize things on computer.

**Comment by 88250** [comment]
Try this:

![image](https://github.com/siyuan-note/siyuan/assets/873584/36947498-12fa-45a0-ac6b-e425a700d341)

**Comment by omega3** [comment]
I am aware of this feature but with long list of blocks like for example input of RSS where dozens of feeds comes daily it would be easier to drag and drop than typing document name in search box.

**Comment by 88250** [comment]
Well, I guess we can only try split-screen dragging.

**Comment by 88250** [comment]
Dragging and dropping blocks will move the position of the block (sometimes this may destroy the context). For viewing to-do items, you can also consider searching through the tag `#TODO#`, or managing through the attribute view (similar to Notion Database).

**Comment by omega3** [comment]
> Dragging and dropping blocks will move the position of the block 

Yes. That is what I want sometimes. Instead of cut and paste.

< sometimes this may destroy the context

But sometimes there is no context.
