### ISSUE TITLE
jump from pasted embedded block to source text and get back easily

### ISSUE THREAD

**Issue by omega3** [siyuan-note/siyuan#8966]
### In what scenarios do you need this feature?

When I want read more of original context of embedded block and get back easily without to many distractions like operating the app itself by using panels.

### Describe the optimal solution

Actually, I would like to be able to jump back and forth from destination to source and from source to destination.

Now embedded block has a link indicating source document but it doesn't take me to the source
https://i.imgur.com/h74t9lS.png
Also I see there is a number on the right site indicating some link but clicking on it doesn't do anything.

And when I am in source there also should be some indication to all embedded. Perhaps an icon that on hover shows me a list all embedded destinations.  I know there is backlinks panel but I'd prefer something more straightforward. Using backlinks panel is good when creating structure and organizing links but not that great when user just want to read and learn already structured content.

**Comment by 88250** [comment]
My test here is ok, please see the screen recording:

[视频.webm](https://github.com/siyuan-note/siyuan/assets/873584/6c3d0a58-4e14-417d-8a9d-d0c30adeb135)

Temporarily closed, if I did not understand your question, please post more, thank you.

**Comment by 88250** [comment]
A single embedded block (src/def) can get the embedded location (dest/ref) by hovering over the count icon, and then pressing Ctrl+Click on the breadcrumbs to open the required block in a new tab (not supported in the same tab switching, only supports open in a new tab).

[视频.webm](https://github.com/siyuan-note/siyuan/assets/873584/1d0601a2-0afd-4001-a9a5-3307caf89618)
