### ISSUE TITLE
一些功能汇总

### ISSUE THREAD

**Issue by pengcheng820** [siyuan-note/siyuan#8970]
### In what scenarios do you need this feature?

1、建议可以快速分栏，效果如下

![image](https://github.com/siyuan-note/siyuan/assets/12994898/7c9dc06f-91ef-476e-9f7d-bd76111ffdae)
![image](https://github.com/siyuan-note/siyuan/assets/12994898/98b4b77b-1865-4371-aa41-29ad83a00e81)

2、显示块结构，方便定位

![image](https://github.com/siyuan-note/siyuan/assets/12994898/c05ebc3b-075d-459e-95e1-ccf016f41192)

3、支持上传自定义图标

![image](https://github.com/siyuan-note/siyuan/assets/12994898/d5c5a2c2-0b6e-433a-b9b0-fadd5fee4554)

### Describe the optimal solution

如上

**Comment by 88250** [comment]
1. 使用模板
2. 自定义 CSS
3. 请参考用户指南

感谢反馈。
