### ISSUE TITLE
Output a block query as a Gantt chart 

### ISSUE THREAD

**Issue by ognsya** [siyuan-note/siyuan#8971]
### In what scenarios do you need this feature?

Is it possible to generate a Gantt chart based on a block query, using custom (or built-in ) attributes, or block content, as parameters?

For example, if I have many task item blocks with start and end dates, I'd like to be able to show them within a Gantt chart.

I tried adding SQL queries within the gantt chart code but that doesn't seem to work...

### Describe the optimal solution

-

### Describe the candidate solution

Either have Gantt chart show as a view (alongside list and database), or be able to use query results within gantt code blocks.

### Other information

-

**Comment by 88250** [comment]
Hello, it is recommended to implement this requirement by developing a widget or a plugin, thank you.

**Comment by ognsya** [comment]
Thank you.

Is there a forum where plugin ideas can be suggested and discussed?

**Comment by 88250** [comment]
Maybe here https://github.com/siyuan-community/ideas/issues

**Comment by ognsya** [comment]
> Maybe here https://github.com/siyuan-community/ideas/issues

Thank you
