### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by Walleeeda** [siyuan-note/siyuan#8974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

bug

打开一段时间后点击关闭 关不掉界面，只能任务管理器关闭，可以继续输入但不能切换文档，后下角显示数据库索引订正。已经升级成了最新版了。 

### Expected result

 求大佬给个解决方法，太麻烦了。

### Screenshot or screen recording presentation

![Uploading 微信图片_20230815101905.png…]()

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12340751/siyuan.log)

**Comment by 88250** [comment]
你好，我看不到你上传的图片。

从日志分析，建议重建索引，并检查 20230809203444-dd6qh2x 这个笔记本文件夹是否缺失了配置文件，如果这个文件夹已经不再需要，就手动删除一下吧。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
