### ISSUE TITLE
大纲树融入文档树

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#8975]
### In what scenarios do you need this feature?

能否提供一个选项将大纲树放入到文档树功能中。

1. 工作面板每块独立空间都是宝贵的，同时打开文档树和大纲树空间占用太大。
2. 融合在一起就有一种类 workflowy 无限层级似的感觉，目前思源对页面和大纲底层是统一的，是可以往这个方向努力的。如果能有虚拟页面的抽象，那么一个子文档树加文件放在一个页面显示也是可以的，可以认为是 #556 的进一步深化

### Describe the optimal solution

如上

**Comment by 88250** [comment]
不考虑了，感谢提议。
