### ISSUE TITLE
插件无法卸载，无法正常运行

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#8976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我想有些可能不是插件本身的问题
插件已经删除，在data的plugins目录已经没有了，但是仍然出现在界面中，并且可以正常使用。但是无法删除。与此同时，插件的开关可能会失效。如图，点击删除后无反应，且无法关闭此插件的使用（显示是关闭的，但实际上还有）：
![image](https://github.com/siyuan-note/siyuan/assets/47842345/238979ba-0d4e-45b9-934a-9e80b4f5638b)
![image](https://github.com/siyuan-note/siyuan/assets/47842345/ca4ee6a2-8adb-4b34-8bb0-f9d973414147)
文件目录无此插件：
![image](https://github.com/siyuan-note/siyuan/assets/47842345/c030bbc3-1e03-441d-8118-ebe6f3297703)
插件仍然可以使用，多次关闭重启删除重复都没用：
![image](https://github.com/siyuan-note/siyuan/assets/47842345/d702e606-b35b-4a55-9df6-dd971f9f48e9)
与此同时，有些插件无法开启：
![image](https://github.com/siyuan-note/siyuan/assets/47842345/b287b482-9263-402e-96d3-0e326faf50c1)
已开启但是界面上无显示。
有的插件打开了但是没有任何显示（可能是插件本身的问题）：
![image](https://github.com/siyuan-note/siyuan/assets/47842345/17e1559d-862f-4a60-a459-f6bcce1dac90)
会出现所有插件都在界面上，但是打开设置面板发现插件开关都关闭了，然后再开启插件开关，结果界面上所有图标都再重复一遍的情况，这个时候需要重启思源（已无法复现，可能是因为更新或者同步的原因？）。

### Expected result

希望能够用的更加顺畅一点

### Version environment

```markdown
- Version: 2.9.9
- Operating System: win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/12341037/system-log.zip)

**Comment by 88250** [comment]
日志中没有发现相关问题，目前不太清楚重现步骤，请在新的工作空间中测试看看。

我先关闭了，如果还有更多信息补充请继续跟帖，谢谢 :pray:

**Comment by lisontowind** [comment]
> 日志中没有发现相关问题，目前不太清楚重现步骤，请在新的工作空间中测试看看。
> 
> 我先关闭了，如果还有更多信息补充请继续跟帖，谢谢 🙏

我发现问题了，删不掉的原因是因为插件作者弄混了，安装的是list2table插件，但实际上安装的是TreeandGraph，导致怎么写卸载都不行，删除list2table的文件夹就好了。。。json上的信息和文件夹名称对不上

其他的是我乌龙了。。。我不知道Kmind插件还要依赖于它的同名挂件。。。

**Comment by 88250** [comment]
haode -_-#
