### ISSUE TITLE
js访问路径端口和docker映射端口不一致

### ISSUE THREAD

**Issue by TtBJSH** [siyuan-note/siyuan#8980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用docker部署新版本 无法访问页面 js文件请求的地址端口不对时默认的6806端口 而不是访问主页自定义的端口

### Expected result

请求js文件应和docker映射的端口一致

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/46512682/ffa09a4e-528b-4ebc-b734-bc25cd601de7)

### Version environment

```markdown
- Version: b3log/siyuan:latest
- Operating System:  contos7.6、windows11
- Browser (if used):115.0.5790.171（正式版本） （64 位）
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12353990/siyuan.log)

**Comment by 88250** [comment]
请配置反向代理解决该问题。
