### ISSUE TITLE
Webdav error

### ISSUE THREAD

**Issue by abdcef** [siyuan-note/siyuan#8984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When initiating the sync, I can see the directories in my webdav location. I select the cloud directory and confirm to upload local snapshot. However, I get an error message "Failed to lock the cloud sync directory". Screenshots attached.

### Expected result

Successful webdav sync

### Screenshot or screen recording presentation

<img width="311" alt="image" src="https://github.com/siyuan-note/siyuan/assets/56148250/d5f70844-84d3-4503-86eb-be5e43066e41">

<img width="1072" alt="SCR-20230816-pcxp-2" src="https://github.com/siyuan-note/siyuan/assets/56148250/edfc902b-f530-44a1-a2cb-ed1eda693fd8">

### Version environment

```markdown
- Version: 2.10.0 (2.10.0)
- Operating System: MacOS 13.5
- Browser (if used): Mac App for Apple
```

### Log file

E 2023/08/16 17:07:17 sync_lock.go:154: upload lock sync failed: Write SiYuan/siyuan/repo/lock-sync: 403
E 2023/08/16 17:07:17 repository.go:1056: sync data repo upload failed: lock cloud repo failed
E 2023/08/16 17:16:56 webdav.go:82: upload object [SiYuan/siyuan/repo/lock-sync] failed: Write SiYuan/siyuan/repo/lock-sync: 403
E 2023/08/16 17:16:56 sync_lock.go:154: upload lock sync failed: Write SiYuan/siyuan/repo/lock-sync: 403
E 2023/08/16 17:16:56 repository.go:1056: sync data repo upload failed: lock cloud repo failed

**Comment by abdcef** [comment]
I also shared a screenshot of the webdav server configuration

<img width="1072" alt="SCR-20230816-pcxp-2" src="https://github.com/siyuan-note/siyuan/assets/56148250/0714d7bd-ea2c-44c7-8b8a-e6157c6c461c">

**Comment by 88250** [comment]
Hello, please check the WebDAV server conf and log (if the server is built by yourself), because from the analysis of the kernel log, the server returns a 403 error (no permission).

**Comment by abdcef** [comment]
Thank you. I restarted everything. Here is a new error:
<img width="273" alt="image" src="https://github.com/siyuan-note/siyuan/assets/56148250/ddf1e955-210b-4d28-a8ab-be6bdc94fbed">

**Comment by 88250** [comment]
From the logs, it may be a network problem or a server problem, but it should not be a bug with SiYuan.

Please try another WebDAV service provider, but it is best not to use WebDAV and use the S3 protocol instead, which has better performance and is more stable, thanks.
