### ISSUE TITLE
代码片段的开关状态可否不在平板端与桌面端之间同步？

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#8986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

设置页面的开关在不同端不同步，插件开关状态也不同步，这点很好，但是代码片段的开关状态似乎是同步的，我在平板端关闭了代码后桌面端也被关闭了。

### Expected result

希望可以不同步。

### Version environment

```markdown
- Version: 2.9.10
- Operating System: win/Android
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
只能通过手动忽略同步文件 data/snippets/conf.json，代码片段内容需要完全分开平台重新手动配置，似乎没有其他方案了，感谢反馈。
