### ISSUE TITLE
Support searching some plaintext assets content

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#8987]
* .json
* .log
* .sql
* .html
* .xml
* .java
* .h
* .c
* .cpp
* .go
* .rs
* .swift
* .kt
* .py
* .php
* .js
* .css
* .ts
* .sh
* .bat
* .cmd
* .ini
* .yaml
* .rst
* .adoc
* .textile
* .opml
* .org
* .wiki

**Comment by mozhux** [comment]
这还是需要支持限定后缀吧，快捷的方式限制，目前那个需要自己选

**Comment by 88250** [comment]
@mozhux 没看懂你的意思，麻烦补充一下。

**Comment by mozhux** [comment]
> @mozhux didn't understand what you mean, please take the trouble to add.

  css-css 搜索css文件里的css内容

**Comment by 88250** [comment]
哦，这个暂时先不加了。
