### ISSUE TITLE
protyle 接口在使用scroll参数时表现不符合预期

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#8988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在使用protyle创建可编辑区域时使用下面的参数时，会显示预期之外的范围。

```js
let pro = document.createElement("div")
let protyle = new Protyle(this.app,pro,{blockId: "20230816232111-48uimm4",render:{scroll:true}})
```
显示效果见下，其中 `20230816232111-48uimm4` 是第一个标题 1 的 id 
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/686ea2bb-52a9-4feb-b1c9-6da4debc3371)

最小可复现文档见下：
[Untitled.sy.zip](https://github.com/siyuan-note/siyuan/files/12361247/Untitled.sy.zip)

### Expected result

只显示指定的范围。

### Version environment

```markdown
- Version: 2.10.1
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by Vanessa219** [comment]
scroll 指的是是否显示右侧的动态滚动条，和滚动位置无关。如果打开过会自动记住上一次的滚动位置。

**Comment by zxhd863943427** [comment]
与滚动条和滚动位置无关，单纯就是启用这个参数后会对显示范围照成影响，但是理论上是不会的，这应该是一个bug。

**Comment by Vanessa219** [comment]
设置为 true 的时候，是正常的。只是设置为 false 的时候，该块为动态加载，但是没有动态滚动条，从而导致无法进行动态加载。

**Comment by zxhd863943427** [comment]
所以说，使用protyle时指定显示一个标题，显示了其他标题的内容，是符合预期的吗？

但是它的反应也不均一啊，下面的列表任意删除几项后，也不动态加载了。

这让我不能理解protyle的展示逻辑，使用他来显示标题和标题下内容，有时会显示不在标题下的其他内容，有时又不会。

**Comment by Vanessa219** [comment]
块数量达到配置后才会显示动态加载。加载 portyle 时会自动判断是否保存过滚动位置，保存过的话打开会使用上次的位置点。

**Comment by zxhd863943427** [comment]
我认为这可能需要添加判断机制，这导致原本只打算显示标题下内容的部分显示了其他的部分。

**Comment by Vanessa219** [comment]
把  action 设置为 ["cb-get-all", "cb-get-focus"] 试试
