### ISSUE TITLE
为 `forwardProxy` 添加 proxy 参数

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#8989]
### In what scenarios do you need this feature?

由于思源不走系统代理，所以 forwardProxy 无法访问需要科技的url，可能带来一些不便之处。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/89e8cff7-fa2d-4aef-98b2-b0e466711114)

### Describe the optimal solution

为 forwardProxy 添加 `proxy` 参数，允许通过代理转发请求。

**Comment by 88250** [comment]
代理统一在 设置 - 关于 中配置，其他地方不单独做，感谢反馈。

**Comment by frostime** [comment]
OK，谢谢
