### ISSUE TITLE
自定义整体窗口显示隐藏快捷键

### ISSUE THREAD

**Issue by yuuuxt** [siyuan-note/siyuan#899]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

默认的全局快捷键不是很方便单手按, 建议允许自定义

### 描述最优的解决方案 Describe the optimal solution

允许自定义全局快捷键

### 描述候选解决方案 Describe the candidate solution

NA

### 其他信息 Other information

https://github.com/siyuan-note/siyuan/issues/704

**Comment by 88250** [comment]
只是托盘唤起的快捷键吗？如果只实现这个的话会觉得有点残……而全部快捷键的自定义短时间是实现不了的……

**Comment by yuuuxt** [comment]
> 
> 
> 只是托盘唤起的快捷键吗？如果只实现这个的话会觉得有点残……而全部快捷键的自定义短时间是实现不了的……

看排期吧, 个人需求上比较需要的是托盘唤起的这个, 别的暂时没需求

**Comment by 88250** [comment]
你好， https://github.com/siyuan-note/siyuan/issues/621 中会实现自定义快捷键，谢谢。
