### ISSUE TITLE
Slow response to hyperlink activation

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#8990]
### In what scenarios do you need this feature?

实际上，在很多时候（比如Zotero、 Quicker调用）我们都需要通过超链接的方式打开 SiYuan 的特定文档或者定位到特定的块。但实际上，这个过程的响应时间是十分久的。尤其是这种操作在短时间内高频率激活，每次等待响应的时间就难以忍受。

### Describe the optimal solution

能不能通过API的方式操控编辑器打开特定文档（定位到特定块），因为我发现如果通过原生的 SiYuan 软件（在文档树 / 行内块引）任意点击，它的响应速度是会比超链接快N倍。
所以，可能需要将原生的 SiYuan 打开文档的接口暴露给 API

**Comment by 88250** [comment]
你好，已经提供前端插件 API 打开块，但从描述上看你需要的是内核 API？

**Comment by LGRemdo** [comment]
> 你好，已经提供前端插件 API 打开块，但从描述上看你需要的是内核 API？

你好，请问有内核API的相关描述文档吗？

**Comment by 88250** [comment]
请看项目根目录。



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 17, 2023 12:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990)




  
你好，已经提供前端插件 API 打开块，但从描述上看你需要的是内核 API？
  
你好，请问有内核API的相关描述文档吗？

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by LGRemdo** [comment]
原来内核API就是所提供的那些http吗，那个我都会用，我知道这个，但是确实缺少一个api实现我说的那个激活功能。有的时候外部应用是脱离前端的，所以还是提供一个api执行操作比较好。

**Comment by 88250** [comment]
好的，我们考虑看看，应该是可以做的。

**Comment by LGRemdo** [comment]
> 好的，我们考虑看看，应该是可以做的。

十分感谢，辛苦，这个issue是否需要open呢？

另外，API可否支持，能够返回编辑器正在阅读的文档的ID，虽然我可以曲线救国（赋值块id查询所属文档id，但是这样还是会在小概率出现误差）

**Comment by 88250** [comment]
要等等再 reopen，还在考虑。


内核 api 无法返回当前激活的文档。



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 17, 2023 20:54 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990)




  
好的，我们考虑看看，应该是可以做的。
  
十分感谢，辛苦，这个issue是否需要open呢？
 
另外，API可否支持，能够返回编辑器正在阅读的文档的ID，虽然我可以曲线救国（赋值块id查询所属文档id，但是这样还是会在小概率出现误差）

**Comment by 88250** [comment]
研究后发现内核 API 做不了，因为前端支持多开工作空间，仅通过块 ID 的话无法确定工作空间，并且 6806 端口只能在最先启动的内核上监听，其他工作空间内核监听不了（使用随机端口）。

这个需求估计还是靠 `siyuan://` 拉起比较好，目前的问题是拉起太慢？

**Comment by LGRemdo** [comment]
> 研究后发现内核 API 做不了，因为前端支持多开工作空间，仅通过块 ID 的话无法确定工作空间，并且 6806 端口只能在最先启动的内核上监听，其他工作空间内核监听不了（使用随机端口）。
> 
> 这个需求估计还是靠 拉起比较好，目前的问题是拉起太慢？`siyuan://`

哦哦，原来还有这难度，目前的问题就是慢，如果是一两次点击还好，短时间高频率或者次数一上去，就忍不了这个速度了。

**Comment by 88250** [comment]
慢是第一次拉起应用的时候还是正常开着的时候外部点击块超链接跳转慢？

**Comment by LGRemdo** [comment]
> 

正常开着的，一直没关闭，我最大同时打开文档数限定的30，但是不论多少正在打开的文档，都很慢，跟电脑配置有关吗？

**Comment by LGRemdo** [comment]
> 慢是第一次拉起应用的时候还是正常开着的时候外部点击块超链接跳转慢？

反正我如果通过文档树打开文档或者点击引用跳转就很快，但是外部应用，协议打开就比较久

对了，似乎sy内的协议跳转会打开快一点？我下火车了再试试看

**Comment by 88250** [comment]
在应用开启的情况下，内部和外部的跳转都很快才对。我这里的录屏你方便的时候看下：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/873584/ad636d44-5de1-4975-961c-8ca6c5402fdd)

**Comment by LGRemdo** [comment]
> 在应用开启的情况下，内部和外部的跳转都很快才对。我这里的录屏你方便的时候看下：
> 
>  default.webm

确实很快！请问这跟当前工作空间文档数量有关吗？和使用的主题有关吗？（我目前是savor主题）
另外，这个是否和协议激活方式有关呢？比如您用的浏览器，您这边私底下试试cmd？或者qk的运行模块呢？

我下火车也会重新过一遍各种方式，对比一下。

**Comment by 88250** [comment]
你试下吧，我目前没有时间测试其他程序。测试的时候请用默认主题，关闭所有插件，先试试一个工作空间的情况。

**Comment by LGRemdo** [comment]
> 你试下吧，我目前没有时间测试其他程序。测试的时候请用默认主题，关闭所有插件，先试试一个工作空间的情况。

好的，十分辛苦您对问题的跟进，稍晚些我将再次测试一遍。

**Comment by LGRemdo** [comment]
> 你试下吧，我目前没有时间测试其他程序。测试的时候请用默认主题，关闭所有插件，先试试一个工作空间的情况。
你好，我这边已经测试过了，换了一台新的电脑，然后首先还是通过quicker的一些外部应用来打开，但是速度确实跟我之前测试的笔记本电脑一样慢.

神奇的来了，我模仿您通过类似于浏览器这种超链接的方式，打开一次后面就都快了，不知道是不是打通了任督二脉？

**Comment by 88250** [comment]
不知道是不是系统安全相关导致的。



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 18, 2023 19:07 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990)




  
你试下吧，我目前没有时间测试其他程序。测试的时候请用默认主题，关闭所有插件，先试试一个工作空间的情况。
 你好，我这边已经测试过了，换了一台新的电脑，然后首先还是通过quicker的一些外部应用来打开，但是速度确实跟我之前测试的笔记本电脑一样慢.
  
神奇的来了，我模仿您通过类似于浏览器这种超链接的方式，打开一次后面就都快了，不知道是不是打通了任督二脉？

**Comment by LGRemdo** [comment]
> 不知道是不是系统安全相关导致的。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Aug 18, 2023 19:07 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990) 你试下吧，我目前没有时间测试其他程序。测试的时候请用默认主题，关闭所有插件，先试试一个工作空间的情况。 你好，我这边已经测试过了，换了一台新的电脑，然后首先还是通过quicker的一些外部应用来打开，但是速度确实跟我之前测试的笔记本电脑一样慢. 神奇的来了，我模仿您通过类似于浏览器这种超链接的方式，打开一次后面就都快了，不知道是不是打通了任督二脉？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

还有这个说法吗？那请问我应该从哪些方面来入手改善这个现象呢？我现在是windows10系统。不应该是杀毒软件的锅吧？

**Comment by 88250** [comment]
我也不太清楚，只能关了杀毒软件防火墙等看看，或者加信任列表看看。



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 18, 2023 20:08 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990)




  
不知道是不是系统安全相关导致的。
 …
 ---Original--- From: @.&gt; Date: Fri, Aug 18, 2023 19:07 PM To: @.&gt;; Cc: @.&gt;;"State @.&gt;; Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990) 你试下吧，我目前没有时间测试其他程序。测试的时候请用默认主题，关闭所有插件，先试试一个工作空间的情况。 你好，我这边已经测试过了，换了一台新的电脑，然后首先还是通过quicker的一些外部应用来打开，但是速度确实跟我之前测试的笔记本电脑一样慢. 神奇的来了，我模仿您通过类似于浏览器这种超链接的方式，打开一次后面就都快了，不知道是不是打通了任督二脉？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
还有这个说法吗？那请问我应该从哪些方面来入手改善这个现象呢？我现在是windows10系统。不应该是杀毒软件的锅吧？

**Comment by LGRemdo** [comment]
> 我也不太清楚，只能关了杀毒软件防火墙等看看，或者加信任列表看看。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Aug 18, 2023 20:08 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990) 不知道是不是系统安全相关导致的。 … ---Original--- From: @.&gt; Date: Fri, Aug 18, 2023 19:07 PM To: @.&gt;; Cc: @.&gt;;"State @.&gt;; Subject: Re: [siyuan-note/siyuan] Slow response to hyperlink activation (Issue#8990) 你试下吧，我目前没有时间测试其他程序。测试的时候请用默认主题，关闭所有插件，先试试一个工作空间的情况。 你好，我这边已经测试过了，换了一台新的电脑，然后首先还是通过quicker的一些外部应用来打开，但是速度确实跟我之前测试的笔记本电脑一样慢. 神奇的来了，我模仿您通过类似于浏览器这种超链接的方式，打开一次后面就都快了，不知道是不是打通了任督二脉？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 还有这个说法吗？那请问我应该从哪些方面来入手改善这个现象呢？我现在是windows10系统。不应该是杀毒软件的锅吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

好的，非常感谢您耐心的指导，我在反复试一试，应该会有所好转。如果实在解决不了的话，再向您提出反馈
