### ISSUE TITLE
自定义或记忆在嵌入块上左键点击打开的弹窗尺寸

### ISSUE THREAD

**Issue by holduan** [siyuan-note/siyuan#8992]
### In what scenarios do you need this feature?

目前的在SQL嵌入块上打开的弹窗高度很小，要滚动才能看全信息，编辑更麻烦。
虽然可以拖放窗口大小，但在频繁操作时会多出很多操作；
还可以通过alt+点击 新窗口打开解决，但操作也多了——Alt键，还有关闭新窗口的操作。

### Describe the optimal solution

自定义或记忆在嵌入块上左键点击打开的弹窗尺寸

**Comment by 88250** [comment]
你好，麻烦截图看下。

**Comment by holduan** [comment]
> 你好，麻烦截图看下。


https://github.com/siyuan-note/siyuan/assets/80377040/d1b413f6-0811-43e2-8156-23090935fc9d

**Comment by Vanessa219** [comment]
根据潜入块重新设定了高度，还麻烦下个版本在看看。
