### ISSUE TITLE
Asset file support `Save As...` on the desktop

### ISSUE THREAD

**Issue by yangjuncheng** [siyuan-note/siyuan#8993]
对于上传到编辑器里的文件，右击可以另外到其他位置

### In what scenarios do you need this feature?

当有些文件上传到笔记中后，如果后续需要使用该文件，想从笔记中下载下来，目前没有途径，只有到资源文件夹中copy。但是copy的文件名称又不是原来笔记中的名称，造成很多麻烦。

### Describe the optimal solution

在文件上右击，弹出另存为选项，点击选项，选择文件夹，保存文件。

**Comment by yangjuncheng** [comment]
编辑模式下，可以进行导出，但是在只读模式，仍然没有导出功能。

**Comment by 88250** [comment]
是的，仅在编辑模式下支持。



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 22, 2023 08:37 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support single asset file `Export` (Issue#8993)




 
编辑模式下，可以进行导出，但是在只读模式，仍然没有导出功能。
