### ISSUE TITLE
多端同步后，容易出现太多Untitled的文档（笔记名字丢失），太多了，很崩溃，无法修复

### ISSUE THREAD

**Issue by Joe-2002** [siyuan-note/siyuan#8995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/56438623/b5d4d603-3431-40e2-8a90-219953f989fe)
尝试过恢复快照，没有用，无法干掉云端同步文件，一同步就Untitled

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/56438623/b5d4d603-3431-40e2-8a90-219953f989fe)
尝试过恢复快照，没有用，无法干掉云端同步文件，一同步就Untitled

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/56438623/b5d4d603-3431-40e2-8a90-219953f989fe)
尝试过恢复快照，没有用，无法干掉云端同步文件，一同步就Untitled

### Version environment

```markdown
- Version: 2.10.0
- Operating System: 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12372070/siyuan.log)

### More information

希望尽快修复

**Comment by 88250** [comment]
使用快照恢复以后再随意修改一个文档后再同步试试。

这个问题我们目前无法重现，无法定位问题，如果上面的步骤不起作用的话，试下重置云端目录吧。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by Joe-2002** [comment]
> 使用快照恢复以后再随意修改一个文档后再同步试试。
> 
> 这个问题我们目前无法重现，无法定位问题，如果上面的步骤不起作用的话，试下重置云端目录吧。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

@88250 如何重置云端目录？？ 使用快照恢复后，修改的文档的标题不会再丢失。当时不管哪个快照恢复，还有是100多的笔记名称没了

**Comment by 88250** [comment]
创建一个新的云端目录。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月18日(周五) 中午1:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 多端同步后，容易出现太多Untitled的文档（笔记名字丢失），太多了，很崩溃，无法修复 (Issue #8995)




  
使用快照恢复以后再随意修改一个文档后再同步试试。
 
这个问题我们目前无法重现，无法定位问题，如果上面的步骤不起作用的话，试下重置云端目录吧。
 
我先关闭了，如果还有问题请继续跟帖，谢谢 🙏
  
@88250 如何重置云端目录？？ 使用快照恢复后，修改的文档的标题不会再丢失。当时不管哪个快照恢复，还有是100多的笔记名称没了

**Comment by Joe-2002** [comment]
> 

希望尽量减少这类问题的出现，有点恐怖，用华为平板siyuan 同步就有这个问题了
