### ISSUE TITLE
Visual indicator next to linked source block

### ISSUE THREAD

**Issue by omega3** [siyuan-note/siyuan#8996]
### In what scenarios do you need this feature?

Currently when creating a link to block (let’s call it source document) in other document (let’s call it destination document) only when we are in the destination document that has this link (embedded, reference or hyperlink ) there is a visual indicator that there is somewhere a source document. 
In source document there is no visual indicator that would show that a block is mentioned somewhere.
https://i.imgur.com/uWNmncj.png

### Describe the optimal solution

I know that there is backlinks panel and graph view but in my opinion this is good when user creates links, references, etc, in other words when creating some structure, editing, generally speaking for making and analyzing connections. For reading and learning using this might be kind of destructing if we need to use those features. I think reading and learning would be much smoother experience if user could have such indicator as perhaps some icon next to block and see where it was made for this particular block. 

With complex text where there are a lot of links, references, etc. using a long list of these in backlinks panel require a lot of attention to find where this particular block was mentioned. 

This would make backlinks bidirectional. 

### Describe the candidate solution

Create automatically icon next to source block and on hover show backlinks.

**Comment by 88250** [comment]
Try F5 to refresh the source doc, you will see a ref count icon on the right:

![image](https://github.com/siyuan-note/siyuan/assets/873584/c4a12edc-4144-4d42-b0c0-bc24bf3b577c)
