### ISSUE TITLE
无法打开"SiYuan"，因为Apple 无法检查其是否包含恶意软件

### ISSUE THREAD

**Issue by stevenlee87** [siyuan-note/siyuan#9001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/4190121/2f63d587-f4a7-46ae-9a4e-3245272176e8)

### Expected result

可以打开软件

### Version environment

```markdown
- Version: 13.5
- Operating System: macos
- Browser (if used): 版本 115.0.5790.170（正式版本） (x86_64)
```

### Log file

No log

**Comment by 88250** [comment]
从官网下载的吗？如果是的话应该不会有问题，感谢反馈。

**Comment by stevenlee87** [comment]
隐私和安全中选择“仍然要打开”就可以了。
![image](https://github.com/siyuan-note/siyuan/assets/4190121/fd268746-284e-47ac-88a2-eda7c52b5fd2)

**Comment by stevenlee87** [comment]
> 

官网下载的哈。隐私和安全中选择“仍然要打开”就可以了。
