### ISSUE TITLE
Dialog里面Protyle的菜单被遮盖

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#9003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图，我点击红圈部分的blockIcon，弹出的菜单出现在编辑器里，但是被dialog遮盖

![image](https://github.com/siyuan-note/siyuan/assets/63407442/3aa4b809-6f55-4194-b502-b98d3d15c91c)

### Expected result

查了一下代码，发现menu的z-index是210，dialog的z-index是305，那么能不能把menu的z-index设置为根据触发的protyle的z-index变化（永远比protyle高）？

### Version environment

```markdown
- Version: 2.10.0
- Operating System: Windows
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
这个 Dialog 是？目前是写死的，后面需要 https://github.com/siyuan-note/siyuan/issues/7602

**Comment by WingDr** [comment]
> 这个 Dialog 是？目前是写死的，后面需要 #7602

哦哦ok，这个Dialog是我自己在插件里用new Dialog()生成的，里面嵌入了Protyle，主要是要用来快速新建文档并输入内容（有可能会取消输入，所以采用了Dialog），这个菜单目前也没那么影响

**Comment by Vanessa219** [comment]
好的，那我就关闭了，后面统一处理器
