### ISSUE TITLE
Improve list outline

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#9004]
关于大纲圆点改后一些想说的话（希望再精进一点）

### In what scenarios do you need this feature?

感谢 D 大和 V 大让小圆点点击即可聚焦，谢谢！
以上展示均为原皮。
小圆点被误触可能的原因：
![image](https://github.com/siyuan-note/siyuan/assets/87182333/830b126f-e767-43fa-80db-633f388938aa)

小圆点被误触后误以为丢了笔记的原因 1：
WorkFlowy 有非常明显的动画提示（思源没有相应的动画告知用户已经点了聚焦了，几乎没有聚焦的过程，只有右上脚有一个不太明显的 退出聚焦 几个字，以及页面变化了，的聚焦后的结果）
![{3808E93A-2804-E634-E0E0-87B0405F9BF4}](https://github.com/siyuan-note/siyuan/assets/87182333/8d131c14-6340-4d51-ae57-b1e163d95eff)

小圆点被误触后误以为丢了笔记的原因 2：
![image](https://github.com/siyuan-note/siyuan/assets/87182333/9aa2fbc5-e4cc-4782-8f70-958cee1d58cf)

另外还需要反映一个 bug：小圆点在只读模式下点击没有任何反应，不能聚焦。
![image](https://github.com/siyuan-note/siyuan/assets/87182333/bc832d72-d24a-43b2-ad19-3eeb3fb2ca1e)

重现这个小杠也是可以考虑考虑的（理由如下）：
![image](https://github.com/siyuan-note/siyuan/assets/87182333/16805cd9-a080-44cd-9c9f-a12073026104)
![image](https://github.com/siyuan-note/siyuan/assets/87182333/f6c75c9f-e58d-40ae-8bcf-01efd8642673)

这里贴上今天还热乎的群里问题：
![image](https://github.com/siyuan-note/siyuan/assets/87182333/41c3dd2c-987b-4685-a44f-f361ad9f8767)

其实我想要的大纲圆点聚焦已经有了，我完全不需要花时间来组织语言来这个更精进，因为我的使用习惯会让我误触的概率极小，误以为笔记丢失的概率更是不可能有，发这个帖子完全是为了让思源更好，对思源，对新人更为友好。诚然，可能就需要麻烦D大和V大评估精不精进了，毕竟这就要您们花时间花精力了。

### Describe the optimal solution

关联ld帖子：[https://ld246.com/article/1692449830823](https://ld246.com/article/1692449830823)
主要用来看看大家的反馈。

### Describe the candidate solution

无

### Other information

无

**Comment by chenshinshi** [comment]
可以参考savor的块上浮聚焦动画或者toy的页签变色聚焦动画。星羊还有块消失动画的想法。除了大纲聚焦需要动画外其实其他块的聚焦也可以有动画提示。
我们还讨论了聚焦按钮和退出聚焦按钮不对等的问题，聚焦后的圆点如果可以安排退出聚焦事件的话就对等了。群里已经有人制作了相关插件，虽然存在一些bug，由开发者实现应该会更好。

**Comment by JOYCELEEEEE** [comment]
另外d大考虑“再次点击退出聚焦”的功能吗，这样有进有出更符合逻辑。

**Comment by 88250** [comment]
@JOYCELEEEEE 这个还是不加了，大纲类工具似乎没有这样设计的。

**Comment by 88250** [comment]
改进点：

* 增加鼠标悬停小圆点样式
* 只读模式下可以点击小圆点聚焦
* 聚焦小圆点后再次点击小圆点返回上一层
