### ISSUE TITLE
Support heading blocks to make flashcards

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9005]
https://ld246.com/article/1692373237249

**Comment by luo-chuan** [comment]
关联： https://ld246.com/article/1692429627394

**Comment by LoneFireBlossom** [comment]
同样需要这个功能。
我认为只需要实现「如果用户把标题块设置成了闪卡，那么在卡片复习界面的展示时默认折叠此标题块，按一下展示答案就展开标题块」即可。
虽然不懂代码，但感觉应该不太麻烦

**Comment by Jiangshuon** [comment]
> 同样需要这个功能。 我认为只需要实现「如果用户把标题块设置成了闪卡，那么在卡片复习界面的展示时默认折叠此标题块，按一下展示答案就展开标题块」即可。 虽然不懂代码，但感觉应该不太麻烦（当然也有可能我想错了……）
> 
> 不过感觉这充其量也只能算临时解决方法，因为展开有个加载过程会让人难以忍受

我的初衷是想让标题块制卡替代超级块制卡（超级块制卡太麻烦，而且手机端完全不能用），如果仅仅只是折叠标题块，那么意义不大，问题相关的所有内容都需要写入标题中，这对制作复杂问答题很难受，全部需要用shift+enter的形式弄到一起

**Comment by Jiangshuon** [comment]
### 问题1的简要描述
问题详细描述，可能涉及图片，公式，pdf引用等等
#### 答案1
详细解答，自己的思维过程等等
### 问题2的简要描述
问题详细描述，可能涉及图片，公式，pdf引用等等
#### 答案2
。。。
以后制卡直接将问题标题块加入闪卡，次级标题块以及以下部分直接就作为答案。
anki的一些导入模版就是这样的，我感觉思路还是很自然的，就是不知道思源能否实现。

对于闪卡复习，只用挖空这种机械记忆的方式我觉得效果不大，还是问答题好点，在复习闪卡的过程中，把自己的思维过程记录下来，我觉得是有必要的，而这目前用列表块制卡和超级块制卡都非常局限。

**Comment by Jiangshuon** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/67137548/b336727c-5327-42a1-b3dd-b49b6714a037)

比如这种复杂问答题，用列表块和超级块就很难搞，用标题块就非常方便，并且我可以在复习过程中嵌入自己的思考、想法，也基本不会影响闪卡本身

**Comment by Jiangshuon** [comment]
另外用标题块制卡还有个好处，就是可以直接看大纲对问题进行快速扫描，甚至不用打开闪卡，重要问题直接在标题上用符号或者标签标记

**Comment by JOYCELEEEEE** [comment]
想问问，能不能将文档块设置为”第零级“（比第一级大）？

这样的话可以实现一次性对整个文档的复习😋

**Comment by 88250** [comment]
@JOYCELEEEEE 这个不考虑了，请参考 https://github.com/siyuan-note/siyuan/issues/9360#issuecomment-1750885387

**Comment by SamJ2018** [comment]
虽然用标题制卡方便了很多，但是问题描述如果过长标题中可能放不下。能不能做成像上面说的，将标题和标题下的描述都显示出来，然后子标题是答案呢？

**Comment by 88250** [comment]
这个不行，抱歉了，这个功能就这样了。



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 17, 2023 15:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support heading blocks to make flashcards(Issue #9005)




 
虽然用标题制卡方便了很多，但是问题描述如果过长标题中可能放不下。能不能做成像上面说的，将标题和标题下的描述都显示出来，然后子标题是答案呢？
