### ISSUE TITLE
`[[` search meaning

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#9006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Can you please guide on the working of `[[` search (meaning of ``Use `[[` to search only within doc blocks``)
![image](https://github.com/siyuan-note/siyuan/assets/42742240/6df08e0e-40e6-4cfe-b31e-05602634f451)

Case 1 - paragraph block being searched
![image](https://github.com/siyuan-note/siyuan/assets/42742240/53c91e36-fe38-4a1b-a6f5-024310b3e98f)

Case 2 - doc blocks and paragraph blocks both are being searched
![image](https://github.com/siyuan-note/siyuan/assets/42742240/753c24a0-db27-477d-9093-900fb7cfef44)

### Expected result

Understanding 1: `[[` should either search "doc blocks only", or search "non-doc blocks only"
Understanding 2:
* `[[` behaves same as `((` if <kbd>[[ only search documents</kbd> is disabled
* `[[` will search only doc blocks if <kbd>[[ only search documents</kbd> is enabled

### Version environment

```markdown
- Version: 2.10.0
```

### Log file

\-

**Comment by 88250** [comment]
> Understanding 2:
>
> [[ behaves same as (( if [[ only search documents is disabled
> [[ will search only doc blocks if [[ only search documents is enabled

Right.

My test (after enabling `[[ only search documents`): 

![image](https://github.com/siyuan-note/siyuan/assets/873584/4caa51f5-6d1c-4305-b568-d1ef03c7fdd2)

**Comment by fenilgmehta** [comment]
Can we please update ``Use `[[` to search only within doc blocks`` to ``Use `[[` to search only doc blocks`` (and link `doc`/`doc blocks` to`Content Block Type > Documentation block`) because the former gives a feeling that we are search inside the doc blocks (i.e. something like page search).

**Comment by 88250** [comment]
OK, the description text will be adjusted later. However, the `doc` link user guide in the text cannot be implemented, so it is ignored for now.

**Comment by 88250** [comment]
Sorry, I got confused above, it was a modification of the user guide document.

**Comment by fenilgmehta** [comment]
Thanks🙏
