### ISSUE TITLE
Update string for plugin settings

### ISSUE THREAD

**Issue by fenilgmehta** [siyuan-note/siyuan#9008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/42742240/95fc73f7-a3e0-4579-97bc-c298f03dbc3a)

The `Plugin button > dropdown` just says `Settings`. It should be renamed to `Plugin Settings` to avoid confusion. For a long time I had the below misconceptions:
1. Something is broken because the `Settings` entry does not show the shortcut to open it on the right.
2. Why is settings always opening `Settings > Marketplace` and not the first entry of Settings (i.e. `Settings > Editor`)
3. Why is `Settings` kept under `Plugin` dropdown

It is after a long time that I realized that `Plugin button > Settings` refers to `Plugin Settings`

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/42742240/43aa8660-8c06-4bba-811f-cab97a111617)

### Version environment

```markdown
- Version: 2.10.0
```

### Log file

\-

**Comment by 88250** [comment]
The menu itself already expresses the hierarchical relationship, and the text will not be added repeatedly. 

Thanks for the feedback.
