### ISSUE TITLE
Logseq  保留双链和图片 迁移 思源

### ISSUE THREAD

**Issue by msjsc001** [siyuan-note/siyuan#9012]
### In what scenarios do you need this feature?

开发者好，
希望能出一个logseq md文件数据批转换导入思源的功能，导入后能保留双向链和图片。

我想从logseq迁移到思源使用，但文件内的双链、图片太多，用md导入的方式会全失效，阻碍了我迁移到思源，我原始Logseq 文件中有很多**双向链和图片**，如果迁移意味着大量的双链和图片丢失（我一共有上万个页面，如果是几百个丢了也就无所谓了）。

在中文群里讨论过都没有很好的解决方法，交流中有一些群友也是想迁移到思源，但都是碍于双链和图片会全丢就没能迁移成功。

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/93178788/5ce74f2f-5e6b-4d27-aba1-599b075292fe)
我发现思源里边源块的ID格式为："xxxxID": "时间戳+7位随机码"

![image](https://github.com/siyuan-note/siyuan/assets/93178788/8b02e44a-e55f-45a5-b5f2-f4aba1cb61f9)
Logseq里边的源块的ID格式为： id:: uudi

能不能基于这种数据格式转换的前提，做一下Logseq文件的迁入功能（嵌入思源后保留Logseq的双链）

另外logseq的图片 都是用md语言的相对路径希望也能识别后批量导入到笔记替换：` ![image.png](../assets/图片名.png) `

**Comment by 88250** [comment]
你好，如果只是 `[[wikilink]]` 的话思源已经支持，但是块级引用格式几乎没有通用的，支持起来比较复杂，目前没有时间研究其他软件的格式。图片的问题应该比较好解决，你本地全局搜索替换一下再导入应该可以。
