### ISSUE TITLE
移动端增加日历📅功能

### ISSUE THREAD

**Issue by Suiyuchi** [siyuan-note/siyuan#9013]
### In what scenarios do you need this feature?

![IMG_0229](https://github.com/siyuan-note/siyuan/assets/101962873/0121ab14-2263-4336-b227-e9914e81702c)
日记的翻找有点难度

### Describe the optimal solution

![IMG_0229](https://github.com/siyuan-note/siyuan/assets/101962873/2602a28e-4b93-49af-aa57-d55b3c892fa2)
日记界面点开是个日历，直接定位或者创建选中日期的日记

**Comment by Suiyuchi** [comment]
![Uploading IMG_0231.jpeg…]()

**Comment by Suiyuchi** [comment]
![Uploading IMG_0231.jpeg…]()

**Comment by edward-kyle** [comment]
只要插件系统上了移动端，就可以解决这个问题了

**Comment by 88250** [comment]
插件系统是支持移动端的，主要看插件本身的实现是否支持，先关闭了，感谢反馈。
