### ISSUE TITLE
一些使用体验

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#9014]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/98648589/c5cc0f77-6d9a-4661-ae76-9ac36dc517a3)
我有时候xi希望能把这四个列表项并排显示，但是目前并排结果如下，他并不是均匀分配一行的，请问能否实现均匀分配？版本2.10.0
![image](https://github.com/siyuan-note/siyuan/assets/98648589/6adbe72a-db53-4808-84b4-8b9275149d9f)
而且还有一个建议就是感觉在搜索完结果，有时候我需要一个个点开看是否是我想要搜索的内容，然后点的时候感觉有点不流畅，虽然不是卡但是有时候就是会明显慢半拍的感觉。不知道是不是没有能否通过提前缓存解决。还有点击鼠标向下的那个按键我感觉是否可以设置为打开下一项搜索结果内容会更好？（可能有个人喜好在里面，所以仅供参考）

### Describe the optimal solution

同上

**Comment by 88250** [comment]
默认主题应该没有并排显示的功能；列表项建议不要使用超级块横排，如果要横排的话，使用分开的列表。

搜索预览需要实时加载，另外，建议在默认主题下测试并关闭所有扩展，感谢反馈。
