### ISSUE TITLE
Support `￥￥` input formula block

### ISSUE THREAD

**Issue by donny-chan** [siyuan-note/siyuan#9015]
Auto-convert full-width characters to corresponding half-widths of Markdown syntaxes

### In what scenarios do you need this feature?

When entering full-width Chinese characters such as `￥￥`, `·`, `···`, I want it to be converted to `$$`, <code>`</code>, <code>```</code> automatically to avoid having to change input method everytime I want to type a Markdown keyword. This option should be optional to consider people that do not want this.

### Describe the optimal solution

FlowUs support this already, but I don't think inline math works in FlowUs.

### Describe the candidate solution

Just a quick check and automatically convert the character. Or, you could just extend the Markdown renderer/parser to support these full-width characters as keywords.

**Comment by 88250** [comment]
Hello，`···` already supports converting to code block，`￥￥` do not support it at present.

`·` do not consider support converting to inline math, caused by a conflict easily with a human name.
