### ISSUE TITLE
Add plugin event bus `loaded-protyle-dynamic`

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#9021]
### In what scenarios do you need this feature?

试了一下，目前ws-main里还没有动态加载触发的EventBus（ws-main里不会触发），目前的监听还在使用"DOMSubtreeModified"的eventlistener，很不方便（包括每次动态加载都会触发非常多次，然后取消监听也比较难受），希望能够加上这种情况的触发，每次加载完毕之后只触发一次就最好了

### Describe the optimal solution

一个dynamic-load-complete（或者类似名字）的EventBus，在当前所有块（文档界面/动态加载的块）加载完毕之后触发，让我们能对加载后的界面进行操作，最好是返回一个触发所在的protyle

**Comment by zxhd863943427** [comment]
赞同，没有动态加载的事件使得完全无法对文档本身下手。

**Comment by Vanessa219** [comment]
动态加载指得是？如果是打开文档的加载完成可以监听 `loaded-protyle`。

**Comment by WingDr** [comment]
> 动态加载指得是？如果是打开文档的加载完成可以监听 `loaded-protyle`。

好像用的词不是很准确？就是文档的懒加载
