### ISSUE TITLE
Slash menu cannot be called after writing heading by using `#`

### ISSUE THREAD

**Issue by TaxDevOp** [siyuan-note/siyuan#9022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

If i do a / ("Slash") the function menu is called. As soon as i do a "#", "##", "###" and so an, namely a header, the function menu cannot be called anymore by the / ("Slash").

### Expected result

/ ("Slash") always calls function menu regardless of using Headers.

### Screenshot or screen recording presentation

![21-08-2023_15-38-26](https://github.com/siyuan-note/siyuan/assets/54500911/bffb39fa-60e4-4c1d-9461-59cfa3d19236)

### Version environment

```markdown
- Version: 2.10.0
- Operating System: Windows 10
- Browser (if used): not relevant
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12396710/siyuan.log)

**Comment by zxhd863943427** [comment]
I am unable to reproduce your issue. Please close all plugins, code snippets, and switch back to the default theme before attempting again.

**Comment by zxhd863943427** [comment]
This is the situation of my test:
![testheader](https://github.com/siyuan-note/siyuan/assets/74853597/8b3b033c-6fd3-4c43-a9fe-e011b199b4d2)
Maybe you can try upgrading and disabling the input method? Here is my device information:
```
- Version: 2.10.1
- Operating System: Windows 10
- Browser (if used): not
```

**Comment by zxhd863943427** [comment]
Is it possible to try Chinese? As far as I know, this is the language used by the developers.

**Comment by zxhd863943427** [comment]
If you reopen this document, will the Function menu open normally?

**Comment by zxhd863943427** [comment]
please try `((`, `[[`, `{{`,  `#`,  `/` , `:`, This is other special input in SiYuan, if you can't call up the menu, it means that SiYuan should have a problem in this regard.

**Comment by 88250** [comment]
@achseu Please open the developer tool, and switch to the Console tab to check whether exist error logs.

![image](https://github.com/siyuan-note/siyuan/assets/873584/380be033-09f6-4dfe-8a61-203e98e672f2)

**Comment by monsterfurby** [comment]
Came here looking for this issue. I have encountered the same, also after a #-triggered headline. This only happens when in the same document and session, a #-headline was created. After restarting, the respective doc has the /-menu available again.

**Comment by zxhd863943427** [comment]
I'm sorry to make you feel this way, but it's really hard for developers to fix your problems at the moment. But the unfortunate reality is that if the developer's device can't reproduce your problem, you won't be able to figure out the cause of the problem and fix it. At present, developers are focused on two aspects, one is the more important synchronization corruption issue, and the other is database. Until there are enough error reports for this problem to allow developers to capture the location of the real problem, it can only stay open and wait.

**Comment by zxhd863943427** [comment]
For hotkey, you need to open a new issue and list them in detail. As far as I know, this kind of request is usually passed very quickly.

**Comment by 88250** [comment]
We are very sorry, but we are still unable to locate this bug. If there is any progress in the future, we will solve it as soon as possible. Thank you for your understanding and support.

**Comment by 88250** [comment]
@achseu @monsterfurby Could you try it on the latest Chrome browser? 

`http://127.0.0.1:6806/`

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/b32529e7-6784-409a-b771-cc0c25e55c02)

**Comment by zxhd863943427** [comment]
> If you are already programming Markdown, you should use it. If we press "#", "/" is no longer usable. It's that simple. And now you want to tell me that if developers do the same, it won't happen? I have proven it on three operating systems, via video: MacOS, Windows, Linux. It doesn't work in all three systems, proven live on video.
> 
> The world works a little differently: if you don't take users seriously, no more will come, especially if they read lines like the one above. We're all fed up with big companies telling us all day long that "not enough other users" want the feature/bugfix and that's why it's not being delivered. This is exactly what drives us to OpenSource. So, what do I listen to now with OpenSource? Exactly the same thing: We don't care as long as not "enough" users want it. The fact that a) many users don't give any feedback at all and b) enough users drop out because of such bugs - these are not measurable figures, so they are simply swept under the carpet. So-called "dark figure". But if you don't care, it doesn't matter.
> 
> Good luck with this attitude. Keep the ticket open, it is a good warning for everyone who considers to buy this software.

Unfortunately, despite performing these operations every day, I am unable to reproduce your issue. This holds true even in a virtual machine specifically modified for language modifications. If you pay close attention, you will notice that I have already posted videos of me performing similar operations above.

**Comment by Vanessa219** [comment]
@monsterfurby Can you provide the input method, operating system, and Siyuan version information? Thank you.

**Comment by 88250** [comment]
It seems to be due to a keyboard issue. German keyboards have this bug.

Are you using a German keyboard? @achseu @monsterfurby
