### ISSUE TITLE
功能组件列表显示不全，无法选择

### ISSUE THREAD

**Issue by caibojian** [siyuan-note/siyuan#9025]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [ ] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [ ] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/12643041/21ae4465-93a0-440f-af82-3432c6843e7e)

### Expected result

为什么要改成纵向排列啊？都选不到下面的选项？

### Version environment

```markdown
- Version: 版本2.10.1 (2.10.1)
- Operating System:  mac os
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你好，默认主题会有滚动条，社区主题请到主题仓库反馈，谢谢。
