### ISSUE TITLE
compare/diff two documents side by side

### ISSUE THREAD

**Issue by jumpoutofworld** [siyuan-note/siyuan#9026]
### In what scenarios do you need this feature?

I have a document with multiple versions, each for different situation.
I want to figure what the differences between the two versions 

### Describe the optimal solution

Diff with colors is a common and important feature for modern editors.

**Comment by 88250** [comment]
Hello, we can only support comparison through snapshots, thanks for the feedback.

**Comment by zxhd863943427** [comment]
请查看插件：集成编辑环境。

**Comment by jumpoutofworld** [comment]
好思路，发现新天地了。怎么比较任意两个文档呢？ 
如下，比如在这个添加一个快捷键？
<img width="359" alt="image" src="https://github.com/siyuan-note/siyuan/assets/6281381/e0f8adf0-10fd-4262-8079-9789eb7907f2">
