### ISSUE TITLE
文档以 点号 开头，在文档树中，显示为空

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#9027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如下，.class 文档，在文档树中，显示为空
![image](https://github.com/siyuan-note/siyuan/assets/5683995/3ced9be2-6e9b-46cc-99c7-5a2c807c8c6e)

### Expected result

显示正常

### Version environment

```markdown
- Version: 2.10.1
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by zxhd863943427** [comment]
无法复现，请关闭全部插件、第三方主题、代码片段后再试，如能复现请导出相关部分并导入到新的工作空间看看能否复现。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/545ccc5d-eba2-496f-8a51-9321890dc22d)

**Comment by 88250** [comment]
我这里也无法重现，请检查插件或者其他扩展，谢谢。
