### ISSUE TITLE
“内容块标识区域显示层级结构和引用数” 添加开关配置

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#903]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

新年好~
现在使用最新的版本：0.5.46，有一点很不习惯。
就是在编辑的时候，看到很多的层级结构（尤其是列表较多的时候），**以前显示的层级结构就很好**。
### 描述最优的解决方案 Describe the optimal solution

* 添加开关配置
  * 关，就是 以前的 显示的层级结构
  * 开，就是 当前的 显示的层级结构 
### 描述候选解决方案 Describe the candidate solution
* 鼠标**只在最左侧悬浮才显示**，其他位置不显示。
  * 编辑器不是有设定一个最大宽度么，默认800，超过800两边空白，最左侧就是指左边的空白
  * 鼠标放在最左侧悬浮，显示的是 当前这个块的 全部层级结构，比如
![image](https://user-images.githubusercontent.com/69628966/103432230-b71c2a80-4c16-11eb-8700-65e6d763e0b9.png)
  * 鼠标放在其他位置，或者编辑的时候，只显示 当前的层级结构
![image](https://user-images.githubusercontent.com/69628966/103432235-cdc28180-4c16-11eb-8751-e8e57071e545.png)

**Comment by yeshaopeng6688** [comment]
补充下，我指的是这个
![image](https://user-images.githubusercontent.com/69628966/103432106-3b6dae00-4c15-11eb-8165-0f8f464e76d2.png)

**Comment by yeshaopeng6688** [comment]
![image](https://user-images.githubusercontent.com/69628966/103432116-66f09880-4c15-11eb-9681-148ccbbe6383.png)

**Comment by 88250** [comment]
新年好！移开不消失是个 bug，等 v0.5.5 发布以后再试，谢谢。

**Comment by yeshaopeng6688** [comment]
鼠标悬浮放到列表项中间也会显示。
![image](https://user-images.githubusercontent.com/69628966/103434874-48ed5d00-4c42-11eb-8f3f-a7119aa387a8.png)

**Comment by 88250** [comment]
这个是正常的，因为中间这个位置在 ul 里。
