### ISSUE TITLE
Plugin API add openWindow and command.globalCallback

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#9032]
### In what scenarios do you need this feature?

我现在在公司的内网环境，没有办法上外网。
通过安装包安装了思源笔记。
而思源本体有一个很重要的功能没有提供，就是快速添加笔记的功能。

原来在家，都是通过quicker的动作辅助实现的。 但是那个quicker的快速添加做的有些半成品和本体配合起来，也总会出现一些重复创建日记、添加图片不方便，不支持在快速添加中使用markdown等等问题。UI和思源的风格也不搭

现在在内网环境，没法使用quicker，就没法使用快速添加笔记了。

### Describe the optimal solution

像写拉松那样，支持本地的quickadd操作。

可以快速添加笔记和截图

### Other information

思源作为一个主打离线笔记软件，这么重要的功能必须借助联网，有点说不过去。

或者有没有啥离线支持快速添加笔记的app或者解决方案可以推荐吗？

**Comment by 88250** [comment]
不太懂你说的快速添加笔记是什么意思，麻烦详述需求。

**Comment by AugustTuan** [comment]
> 不太懂你说的快速添加笔记是什么意思，麻烦详述需求。

你怎么换成海贼王的头像了，差点没认出来🤣

**Comment by AugustTuan** [comment]
> 不太懂你说的快速添加笔记是什么意思，麻烦详述需求。

等我回家了详细说一下

**Comment by AugustTuan** [comment]
> 不太懂你说的快速添加笔记是什么意思，麻烦详述需求。

就是可以通过快捷键，快速唤出小窗。
然后可以快捷记录笔记，也可以把图片粘贴到小窗发送到当天的dailynotes里面

这个功能平常经常会用到的，不管是工作，开会，上网课。 这种想到什么就记录什么的方式很常用。

现在是可以通过quicker这类第三方工具，安装对应的动作实现
问题主要就是，
1. 第三方的quicker有很多缺陷，使用起来和思源搭配的并不是很理想，然后UI也不太搭。
2. 就是我现在在华为内网里面，没法连接外网了，也就没法用第三方的quicker去实现这个功能，现在无法快速添加笔记了。
3. 【快速笔记】这个功能我觉得很重要，也很泛用，应该可以作为本体自带的功能特性。 而不是要靠其他软件才能做到。
例如writeathon自带的这个快速笔记。支持快速记录笔记，也支持粘贴图片发送。
![Snipaste_2023-08-23_21-28-58](https://github.com/siyuan-note/siyuan/assets/37429029/b9932fe6-11dc-4137-a2fc-f18772e87ee1)
![image](https://github.com/siyuan-note/siyuan/assets/37429029/be43783c-769d-4499-b8d2-404fe4101503)
![image](https://github.com/siyuan-note/siyuan/assets/37429029/6a596279-aff6-4c93-a62e-d5bfe3185c07)

**Comment by AugustTuan** [comment]
> > 不太懂你说的快速添加笔记是什么意思，麻烦详述需求。
> 
> 就是一个快速笔记功能，通过快捷键，快速唤出一个添加笔记的小窗口，可以输入文字，粘贴图片、视频时间戳到小窗口，发送到当天的dailynotes里面
> 
> 这个功能平常经常会用到的，不管是工作，开会，上网课。 这种想到什么就记录什么的方式很常用。 否则就需要反复地切屏，十分地痛苦
> 
> 现在是可以通过quicker这类第三方工具，安装对应的动作实现 问题主要就是，
> 
> 1. 第三方的quicker有很多缺陷，使用起来和思源搭配的并不是很理想，然后UI也不太搭。
> 2. 就是我现在在华为内网里面，没法连接外网了，也就没法用第三方的quicker去实现这个功能，现在无法快速添加笔记了。
> 3. 【快速笔记】这个功能我觉得很重要，也很泛用，应该可以作为本体自带的功能特性。 而不是要靠其他软件才能做到。
> 
> 例如writeathon本体自带的这个快速笔记。支持快速记录笔记，也支持粘贴图片发送。 ![Snipaste_2023-08-23_21-28-58](https://user-images.githubusercontent.com/37429029/262686433-b9932fe6-11dc-4137-a2fc-f18772e87ee1.png) ![image](https://user-images.githubusercontent.com/37429029/262686686-be43783c-769d-4499-b8d2-404fe4101503.png) ![image](https://user-images.githubusercontent.com/37429029/262686522-6a596279-aff6-4c93-a62e-d5bfe3185c07.png)

就是咨询思源是否可以本体支持【快速笔记】这功能，离线也能用到

**Comment by WingDr** [comment]
我最近准备写一个新的卡片盒式笔记的插件，你说的这个需求可以拆分成两个：思源提供注册全局快捷键的支持 + 插件自动新建笔记并显示protyle弹窗。后者我可以来做，前者就需要思源给API了

**Comment by AugustTuan** [comment]
> 我最近准备写一个新的卡片盒式笔记的插件，你说的这个需求可以拆分成两个：思源提供注册全局快捷键的支持 + 插件自动新建笔记并显示protyle弹窗。后者我可以来做，前者就需要思源给API了

话说离线环境可以用插件吗

**Comment by AugustTuan** [comment]
> 我最近准备写一个新的卡片盒式笔记的插件，你说的这个需求可以拆分成两个：思源提供注册全局快捷键的支持 + 插件自动新建笔记并显示protyle弹窗。后者我可以来做，前者就需要思源给API了

可以像浏览器那样，下个压缩包，然后解压就能用了之类的

**Comment by AugustTuan** [comment]
这个在工作，开会，上网课的时候很重要。 
想到什么就记录什么，和不停地来回切屏、分屏记笔记体验完全不一样。 

希望可以本体支持，这样就可以离线使用了。
而且本体做出来的效果，肯定要比现在那个quicker动作要好很多。

或者有什么离线能实现的方案或者别的app推荐的吗。 我现在超级需要这个功能。 😭

**Comment by AugustTuan** [comment]
思源的编辑体验真的吊打很多笔记app，我在内网给给同事都推荐了。
 他们原来都是用word，notepad，typora和华为自研的一些markdown笔记。
看到思源都惊呆了

**Comment by WingDr** [comment]
> > 我最近准备写一个新的卡片盒式笔记的插件，你说的这个需求可以拆分成两个：思源提供注册全局快捷键的支持 + 插件自动新建笔记并显示protyle弹窗。后者我可以来做，前者就需要思源给API了
> 
> 话说离线环境可以用插件吗

可以的，到时候关注一下github上，插件更新之后把release里面最新的package.zip下载下来，解压到和github仓库同名的文件夹下面（确保进入这个文件夹直接就能看到index.js），然后把这个文件夹直接复制到`{你的工作空间}/data/plugins`中就能直接在集市里面看到了

**Comment by 88250** [comment]
我觉得还是插件支持比较好。

注册全局快捷键这个需要考虑下 @Vanessa219

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/9042

**Comment by Vanessa219** [comment]
目前插件已支持快捷键注册，可参考 https://github.com/siyuan-note/plugin-sample/blob/08bf68de828fa36dab47d2bb4ccc6c09b1b12b3b/src/index.ts 中的 addCommand

**Comment by WingDr** [comment]
> 目前插件已支持快捷键注册，可参考 https://github.com/siyuan-note/plugin-sample/blob/08bf68de828fa36dab47d2bb4ccc6c09b1b12b3b/src/index.ts 中的 addCommand

addCommand能注册全局快捷键吗？（在思源外能唤起后台思源的功能的）

**Comment by Yuminis98** [comment]
快速笔记这个功能确实是极大地缓解了输入地成本。

最近使用quicker一直出问题，也没有解决，就卸载掉了。

以前又想法就会快速通过小窗记录下来。 
现在很多时候基本就任灵感流逝，因为懒得切笔记记了。

**Comment by Vanessa219** [comment]
addCommand 只能注册思源内的。

Alt+M 目前可以换出思源，然后再 Alt+5 使用日记功能记录灵感，后面也方便整理。或者是用 `addCommand` 添加一个内部命令，这样是否满足需求了呢？

**Comment by Yuminis98** [comment]
> addCommand 只能注册思源内的。
> 
> Alt+M 目前可以换出思源，然后再 Alt+5 使用日记功能记录灵感，后面也方便整理。或者是用 `addCommand` 添加一个内部命令，这样也许就可以满足了 😊

看似只是少了一个快捷键，但是实际体验其实差了很多很多，这些细节差异，只有两种模式都使用了很久才能体会出来。 
我用思源也有2年了，记录的笔记不说上百万字，几十万字是有的。
上网课，学习，工作，开会，写作，很多场景都是用思源完成的。
 如果思源只留3个功能，quickadd我一定算一个。


你说的这种解决方案和全局快速笔记小窗的实际体验差异，大概有这么几点。

1. 是否切屏打断当前专注区域，侵入式的高低，输入是否无感。
 * alt+M这个快捷键是会直接唤出思源，你当前的屏幕会被思源直接挡住、打断。 切屏地这种侵入式体验，会导致我在上网课，开视频会议的时候，有想法也懒得去切，或者没法去切思源记录了。 特别是一些节奏比较快的时候，我切个屏记录再回去，人家都翻篇了 。。。。
 * 但是如果是通过全局快捷键唤出一个小窗，特别是可以调节透明度的那种，是可以“无感、无侵入”地记录。
 
![image](https://github.com/siyuan-note/siyuan/assets/117956441/16fda6cb-ab33-4ca0-a2df-33bd18f955fb)

 
![image](https://github.com/siyuan-note/siyuan/assets/117956441/7e10ecdb-8d70-4c33-ae3c-957dad050ae1)
2. 就是最直接地，每次输入都少摁一个键盘，当输入频次高的时候，感知就会非常明显。
3. 隐私安全，别人只能看到我输入，但是看不到我的上下文。
对于我这种会把工作笔记，生活感想都记在思源的人。 当我在跟别人开视频会议的时候，我有一些笔记，我打开添加笔记的小窗去发送笔记的时候。人家只会看到我记得这一条笔记。 也就是人家只能看到我输入的过程。
但是如果使用alt+M，alt+5组合。 我就不敢在开视频会议的时候记笔记。 因为我怕人家看到我上年记录的一些隐私信息（比如喷某个领导的信息）这种场景下，quickadd小窗还有保护隐私的作用。
5. 流畅无感地添加时间戳笔记
当我看视频地时候，唤出小窗记笔记，小窗可以读取视频地时间错，然后我记录笔记发送到dailynotes，是可以带上时间戳。 还有比这种方式体验更丝滑的时间戳笔记记录方式吗？ 这个通过alt+M，然后alt+5可以做到吗？
![image](https://github.com/siyuan-note/siyuan/assets/117956441/74b89520-15ad-48ec-9c2f-995047e79f5b)

6. 频繁alt+5对笔记常驻页面的打断。
我是会把【常用的工具和资料】作为置顶页面，作为思源默认打开看到的界面。
而alt+5进入的这个dailynotes，我都是会在晚上或者周末定期打开回看，然后整理的。
对于我这样使用思源的用户，是不喜欢每记一次笔记，就要alt+5切到日记界面，希望笔记是发送到dailynotes，而不是每次都要打开dailynotes记笔记。
7. 有限输入，上下文对当前输入的影响
 用快速笔记小窗，我每一次记录都是一个独立的空间，不受其他上下文的干扰，我可以独立记录。事后再去调整
而我一旦是进入到一堆笔记里面添加新笔记，我就会去琢磨排版，被上下文所打扰。
![image](https://github.com/siyuan-note/siyuan/assets/117956441/d8723814-5a03-41cf-a242-9f311e83c16f)




  哪怕是单纯少按了一个快捷键都会对使用意愿产生影响，更何况我上面提到的这些区别。
  我在没有使用外挂的quicker进行快速笔记以后，日均笔记数量肉眼可见的下滑。输入门槛变得非常明显。当然也可能是我被快速笔记给“养叼了” 
  因为我的工作真的节奏很快，这种情况下没有快速添加笔记地全局小窗，那我就最多在中途休息地时候总结两句，至于那些一闪而过地灵感和疑问，基本都是留在脑子里了。

另外quicker确实问题挺多的，那个动作视频，粘贴图片和编辑地体验都不算很理想。 如果思源本体出一个适配度会好得多，另外也就支持离线不联网地时候也享用这种丝滑地输入方式。
本来记笔记就和联不联网没有关系。
另外这个功能，至少在我心里，是极大地减少了输入的成本，不止应该作为一个插件。
以上都只是建议，截图都来自 写作软件“写拉松”桌面版自带的qickAdd发射功能。

**Comment by Yuminis98** [comment]
> > addCommand 只能注册思源内的。
> > Alt+M 目前可以换出思源，然后再 Alt+5 使用日记功能记录灵感，后面也方便整理。或者是用 `addCommand` 添加一个内部命令，这样也许就可以满足了 😊
> 
> 看似只是少了一个快捷键，但是实际体验其实差了很多很多，这些细节差异，只有两种模式都使用了很久才能体会出来。 我用思源也有2年了，记录的笔记不说上百万字，几十万字是有的。 上网课，学习，工作，开会，写作，很多场景都是用思源完成的。 如果思源只留3个功能，quickadd我一定算一个。
> 
> 你说的这种解决方案和全局快速笔记小窗的实际体验差异，大概有这么几点。
> 
> 1. 是否切屏打断当前专注区域，侵入式的高低，输入是否无感。
> 
> * alt+M这个快捷键是会直接唤出思源，你当前的屏幕会被思源直接挡住、打断。 切屏地这种侵入式体验，会导致我在上网课，开视频会议的时候，有想法也懒得去切，或者没法去切思源记录了。 特别是一些节奏比较快的时候，我切个屏记录再回去，人家都翻篇了 。。。。
> * 但是如果是通过全局快捷键唤出一个小窗，特别是可以调节透明度的那种，是可以“无感、无侵入”地记录。
> 
> ![image](https://user-images.githubusercontent.com/117956441/263505944-16fda6cb-ab33-4ca0-a2df-33bd18f955fb.png)
> 
> ![image](https://user-images.githubusercontent.com/117956441/263505867-7e10ecdb-8d70-4c33-ae3c-957dad050ae1.png) 2. 就是最直接地，每次输入都少摁一个键盘，一次两次还好，但是当输入频次提上去的时候，感知就会非常明显。 3. 隐私安全，别人只能看到我输入，但是看不到我的上下文。
> 
> * 对于我这种会把工作笔记，生活感想都记在思源的人。 当我在跟别人开视频会议的时候，我有一些笔记，我打开添加笔记的小窗去发送笔记的时候。人家只会看到我记得这一条笔记。 也就是人家只能看到我输入的过程。
>   但是如果使用alt+M，alt+5组合。 我就不敢在开视频会议的时候记笔记。 因为我怕人家看到我上面记录的一些隐私信息（比如喷某个领导的信息）这种场景下，quickadd小窗还有保护隐私的作用。
> 
> 5. 流畅无感地添加时间戳笔记
> 
> * 当我看视频地时候，唤出小窗记笔记，小窗可以读取视频地时间错，然后我记录笔记发送到dailynotes，是可以带上时间戳。 还有比这种方式体验更丝滑的时间戳笔记记录方式吗？ 这个通过alt+M，然后alt+5可以做到吗？
>   ![image](https://user-images.githubusercontent.com/117956441/263505574-74b89520-15ad-48ec-9c2f-995047e79f5b.png)
> 
> 6. 频繁alt+5对笔记常驻页面的打断。
> 
> * 我是会把【常用的工具和资料】作为置顶页面，作为思源默认打开看到的界面。
>   而alt+5进入的这个dailynotes，我都是会在晚上或者周末定期打开回看，然后整理的。
>   对于我这样使用思源的用户，是不喜欢每记一次笔记，就要alt+5切到日记界面，希望笔记是发送到dailynotes，而不是每次都要打开dailynotes记笔记。
> 
> 7. 有限输入，上下文对当前输入的影响
> 
> * 用快速笔记小窗，我每一次记录都是一个独立的空间，聚焦的编辑体验，不受其他上下文的干扰，我一条一条独立发送，事后再去调整
>   而我一旦是进入到一堆笔记里面添加新笔记，我就会去琢磨排版，被上下文所打扰。
>   ![image](https://user-images.githubusercontent.com/117956441/263505912-d8723814-5a03-41cf-a242-9f311e83c16f.png)
> 
> 哪怕是单纯少按了一个快捷键都会对使用意愿产生影响，更何况我上面提到的这些区别。 我在没有使用外挂的quicker进行快速笔记以后，日均笔记数量肉眼可见的下滑，从日均几天条几笔，变成日均几条笔记。输入门槛变得非常明显。当然也可能是我被快速笔记给“养叼了” 因为我的工作真的节奏很快，这种情况下没有快速添加笔记地全局小窗，那我就最多在中途休息地时候总结两句，至于那些一闪而过地灵感和疑问，基本都是留在脑子里了。
> 
> 另外quicker确实问题挺多的，那个动作视频，粘贴图片和编辑地体验都不算很理想。 如果思源本体出一个适配度会好得多，另外也就支持离线不联网地时候也享用这种丝滑地输入方式。 本来记笔记就和联不联网没有关系。 另外这个功能，至少在我心里，是极大地减少了输入的成本，提高记笔记地意愿，应该作为一个基础设施，而不止应该作为一个插件。
> 
> 以上都只是建议，另外截图都来自 写作软件“写拉松”桌面版自带的qickAdd发射小窗功能，可以体验一下这个竞品

另外切屏记笔记还有一个麻烦。 就是我打开一个idea，再打开一个bilibili。 好我为了记笔记，切了一个思源/。
那么我本来是很方便地在bilibili和idea之间相互切屏。
而记了一次笔记，思源就会插在中间。 我又得调整一次切屏顺序，才能回到开始的状态

**Comment by WingDr** [comment]
> addCommand 只能注册思源内的。
> 
> Alt+M 目前可以换出思源，然后再 Alt+5 使用日记功能记录灵感，后面也方便整理。或者是用 `addCommand` 添加一个内部命令，这样也许就可以满足了 😊

正如上面所说，还是需要一个能够直接注册全局快捷键的情况的。另外还有想问一下悬浮窗的在新窗口打开是调用哪个函数？还是说得插件自己写window.open和new Protyle？

**Comment by Vanessa219** [comment]
@Yuminis98 问题目前没有小窗输入的功能呀。

@WingDr 目前用的是 https://github.com/siyuan-note/siyuan/blob/fb0c2e3d6a394e94bc969068153341a3bbb17243/app/src/window/openNewWindow.ts 中的 openNewWindowById，没有添加到插件中。

**Comment by WingDr** [comment]
> 问题目前没有小窗输入的功能呀。

> 目前用的是 https://github.com/siyuan-note/siyuan/blob/fb0c2e3d6a394e94bc969068153341a3bbb17243/app/src/window/openNewWindow.ts 中的 openNewWindowById，没有添加到插件中。

小窗快速输入我的插件来做，只要能给注册全局快捷键和openNewWindowById的功能到插件就行（打开新窗口需要的ID插件会给，新建的文档和放置到dailynote中的内容插件来管理，最好能返回一个windowProxy之类的让插件也能操作，剩下的思源本体应该都不用管）

**Comment by mdzz2048** [comment]
@WingDr 是[这个插件](https://github.com/WingDr/siyuan-plugin-zettelkasten)吗？

**Comment by WingDr** [comment]
> @WingDr 是[这个插件](https://github.com/WingDr/siyuan-plugin-zettelkasten)吗？

对，这个是我在写的插件（虽然目前主要在忙citation搁置了好久，尽快开工）

**Comment by Zuoqiu-Yingyi** [comment]
> > 话说离线环境可以用插件吗
> 
> 可以的，到时候关注一下github上，插件更新之后把release里面最新的package.zip下载下来，解压到和github仓库同名的文件夹下面（确保进入这个文件夹直接就能看到index.js），然后把这个文件夹直接复制到`{你的工作空间}/data/plugins`中就能直接在集市里面看到了

@WingDr 这里解压的文件夹名称应该与 `plugin.json` 文件中的 `name` 字段一致, 插件全局唯一的 `name` 与仓库名是独立的

**Comment by Vanessa219** [comment]
@WingDr 代码已提交到开发分支，麻烦看一下是否满足需求了？

**Comment by WingDr** [comment]
> @WingDr 代码已提交到开发分支，麻烦看一下是否满足需求了？

尝试了一下，功能上没问题，但是希望通过id打开的文档能有像openDialog一样的width、height和destroyCallback设定（destroyCallback可以没有参数），这个麻烦吗？

**Comment by Vanessa219** [comment]
👌 已提交，麻烦再看看。

```
 {
    position?: {
        x: number,
        y: number,
    },
    height?: number,
    width?: number,
    tab?: Tab,
    doc?: {
        id: string,     // 块 id
    },
}
```

**Comment by WingDr** [comment]
看了下源码没啥问题（虽然这个好像没推送到pre-release），打开窗口的功能测试了也没问题，可以先这样了

**Comment by Vanessa219** [comment]
嗯嗯，多谢。

**Comment by AugustTuan** [comment]
> > > 我最近准备写一个新的卡片盒式笔记的插件，你说的这个需求可以拆分成两个：思源提供注册全局快捷键的支持 + 插件自动新建笔记并显示protyle弹窗。后者我可以来做，前者就需要思源给API了
> > 
> > 
> > 话说离线环境可以用插件吗
> 
> 可以的，到时候关注一下github上，插件更新之后把release里面最新的package.zip下载下来，解压到和github仓库同名的文件夹下面（确保进入这个文件夹直接就能看到index.js），然后把这个文件夹直接复制到`{你的工作空间}/data/plugins`中就能直接在集市里面看到了

大佬，你这个quickadd插件大概会在什么时候推出？
望眼欲穿(⊙o⊙)

**Comment by WingDr** [comment]
> 大佬，你这个quickadd插件大概会在什么时候推出？ 望眼欲穿(⊙o⊙)

github仓库在[这里](https://github.com/WingDr/siyuan-plugin-zettelkasten)，看思源2.10.3的更新时间，更新了之后我会尽快整出一个可以全局快捷键弹窗输入的版本（这个插件的主要功能不是这个，但是可以先把这个做出来，后续我再去做主要功能）

**Comment by Vanessa219** [comment]
2.10.3 已发布 😊

**Comment by AugustTuan** [comment]
> > 大佬，你这个quickadd插件大概会在什么时候推出？ 望眼欲穿(⊙o⊙)
> 
> github仓库在[这里](https://github.com/WingDr/siyuan-plugin-zettelkasten)，看思源2.10.3的更新时间，更新了之后我会尽快整出一个可以全局快捷键弹窗输入的版本（这个插件的主要功能不是这个，但是可以先把这个做出来，后续我再去做主要功能）

好嘞，感谢大佬。 我现在只要有一个全局发送到笔记的输入框就能解决大问题了
