### ISSUE TITLE
Hello friends! How to set rounded corners for note table?

### ISSUE THREAD

**Issue by zhouxinghong** [siyuan-note/siyuan#9034]
### In what scenarios do you need this feature?

I want to set rounded corners for note table
Windows 10
Version 2.10.1

### Describe the optimal solution

I want to set rounded corners for note table
Windows 10
Version 2.10.1

### Other information

Windows 10
Version 2.10.1

**Comment by zhouxinghong** [comment]
I hope you can provide specific css fragments that effectively set the rounded corners of the note table, thank you very much! 👍😜

**Comment by zhouxinghong** [comment]
```
.protyle-wysiwyg table,.b3-typograp
y table {
border-radius: 12px;
}
.protyle-wysiwyg table thead,.b3-typogra
hy table thead , th ,td{
border-radius: 12px;
}
```
I set these codes in css file but they don't work.

**Comment by royc01** [comment]
可以加qq群交流  1017854502

**Comment by zhouxinghong** [comment]
If you know how to achieve this effect, please let me know the code snippet that works, thanks a lot!

**Comment by zhouxinghong** [comment]
@royc01 Your theme is great! 👍
