### ISSUE TITLE
Remove inline code format on backspace

### ISSUE THREAD

**Issue by donny-chan** [siyuan-note/siyuan#9040]
### In what scenarios do you need this feature?

When the caret is located at the beginning or the end of an inline code (right after the first <code>\`</code> or right before the last <code>\`</code>), pressing backspace should remove turn that inline code into ordinary text.

### Describe the optimal solution

Just remove the corresponding format on backspace.

**Comment by 88250** [comment]
For WYSIWYG editors, if you press the backspace key to cancel on the inline-level element boundary, the probability of misoperation will become higher.

So we still recommend canceling the inline-level element by selecting the entire element, and then pressing the shortcut key corresponding to the element again, thanks for the feedback.
