### ISSUE TITLE
Backspace on empty math block should remove it

### ISSUE THREAD

**Issue by donny-chan** [siyuan-note/siyuan#9043]
### In what scenarios do you need this feature?

Similar to #9040, when the caret is in an empty math block and I press backspace, I want to remove the math block, which is convenient and intuitive considering this is the case with quote and code blocks. 

### Describe the optimal solution

Just remove math block when entering backspace.

**Comment by Vanessa219** [comment]
After looking at it, I found that other software does not have this function. Is it easy to delete by mistake when too many words need to be deleted?

**Comment by 88250** [comment]
We will not consider it for the time being and will continue to collect relevant feedback later, thank you.
