### ISSUE TITLE
When copying the table in HTML, the structure of the table became disorganized

### ISSUE THREAD

**Issue by jumpoutofworld** [siyuan-note/siyuan#9044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

the table is from this url: [关于印发《上海市抗菌药物 临床应用分级管理目录（2021年版）》的通知](https://wsjkw.sh.gov.cn/yzgl4/20210316/7bf75a6fe963446d9ff97d99fef5572f.html)
![image](https://github.com/siyuan-note/siyuan/assets/6281381/0724d500-1f6b-4eec-beb7-d3cbe999dee0)

Copy it to siyuan, the format is disorganized.
![image](https://github.com/siyuan-note/siyuan/assets/6281381/582816c7-c227-47cf-aafa-d2ad8b2393b8)

### Expected result

Copy it to word, the format is OK.
![image](https://github.com/siyuan-note/siyuan/assets/6281381/eb5fa55c-8058-4bf2-98e9-adf204e57cad)

### Version environment

```markdown
- Version: 2.10.0
- Operating System:  mac
- Browser (if used):
```

### Log file

I 2023/08/25 09:06:57 sync.go:720: sync websocket reconnected
I 2023/08/25 09:06:57 sync.go:733: sync websocket message: &{0  map[cmd:kernels kernels:[map[hostname:pengtaoMBP.local id:om6s6wu os:darwin repo:main ver:2.10.0]]]}
I 2023/08/25 09:08:19 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.33s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 09:16:20 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.13s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 09:32:22 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.42s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 10:05:38 sync.go:720: sync websocket reconnected
I 2023/08/25 10:05:38 sync.go:733: sync websocket message: &{0  map[cmd:kernels kernels:[map[hostname:pengtaoMBP.local id:om6s6wu os:darwin repo:main ver:2.10.0]]]}
I 2023/08/25 10:05:49 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [2.13s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 10:57:01 box.go:79: auto stat [trees=3977, blocks=287417, dataSize=2.7 GB, assetsSize=2.5 GB]
I 2023/08/25 10:57:01 disk.go:33: disk usage [total=1.0 TB, used=872 GB, free=128 GB]
I 2023/08/25 11:09:51 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.76s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 11:47:05 queue.go:152: database op tx [8399ms]
I 2023/08/25 11:48:31 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=354 kB, db=578 kB] in [4.12s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 11:56:33 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.60s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 12:04:35 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.81s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 12:12:38 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.85s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 12:28:40 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [1.54s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 13:16:27 sync.go:720: sync websocket reconnected
I 2023/08/25 13:16:27 sync.go:733: sync websocket message: &{0  map[cmd:kernels kernels:[map[hostname:pengtaoMBP.local id:om6s6wu os:darwin repo:main ver:2.10.0]]]}
I 2023/08/25 13:28:27 sync.go:720: sync websocket reconnected
I 2023/08/25 13:28:27 sync.go:733: sync websocket message: &{0  map[cmd:kernels kernels:[map[hostname:pengtaoMBP.local id:om6s6wu os:darwin repo:main ver:2.10.0]]]}
I 2023/08/25 13:39:28 box.go:79: auto stat [trees=3977, blocks=287417, dataSize=2.7 GB, assetsSize=2.5 GB]
I 2023/08/25 13:39:28 disk.go:33: disk usage [total=1.0 TB, used=873 GB, free=127 GB]
I 2023/08/25 13:43:13 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [2.31s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 14:47:17 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=482 kB] in [2.01s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 15:07:53 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=347 kB, db=578 kB] in [15.12s], merge result [conflicts=0, upserts=0, removes=0]
W 2023/08/25 15:12:55 index_fix.go:371: tree [20230824215926-3adi85a] is not up to date, reindex it
I 2023/08/25 15:14:08 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=347 kB, db=578 kB] in [4.09s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 15:15:42 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=7, dfc=2, ucc=3, dcc=0, ub=899 kB, db=578 kB] in [3.60s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 15:17:55 sync.go:720: sync websocket reconnected
I 2023/08/25 15:17:55 sync.go:733: sync websocket message: &{0  map[cmd:kernels kernels:[map[hostname:pengtaoMBP.local id:om6s6wu os:darwin repo:main ver:2.10.0]]]}
I 2023/08/25 15:18:18 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=8, dfc=2, ucc=4, dcc=0, ub=1.1 MB, db=578 kB] in [10.70s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 15:20:04 sync.go:720: sync websocket reconnected
I 2023/08/25 15:20:04 sync.go:733: sync websocket message: &{0  map[cmd:kernels kernels:[map[hostname:pengtaoMBP.local id:om6s6wu os:darwin repo:main ver:2.10.0]]]}
I 2023/08/25 15:20:54 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=6, dfc=2, ucc=1, dcc=0, ub=348 kB, db=578 kB] in [20.16s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/08/25 15:21:13 sync.go:720: sync websocket reconnected
I 2023/08/25 15:21:13 sync.go:733: sync websocket message: &{0  map[cmd:kernels kernels:[map[hostname:pengtaoMBP.local id:om6s6wu os:darwin repo:main ver:2.10.0]]]}
I 2023/08/25 15:21:49 repository.go:1253: synced data repo [kernel=om6s6wu, provider=0, mode=a/false, ufc=6, dfc=2, ucc=1, dcc=0, ub=348 kB, db=578 kB] in [4.75s], merge result [conflicts=0, upserts=0, removes=0]

**Comment by zxhd863943427** [comment]
思源并不支持从外部复制粘贴带有合并单元格形式的表格。你只能粘贴原始形式的并在思源中调整为合并单元格。

**Comment by 88250** [comment]
嗯，不支持合并单元格的表格拷贝，感谢反馈。

**Comment by 88250** [comment]
后续关联 https://github.com/siyuan-note/siyuan/issues/11888
