### ISSUE TITLE
Fix some asset file content indexing issues

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9045]
The index attachment notification in the upper right corner keeps appearing.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

first use the asset content search, and rebuild index, then the notification keeps appearing for several miniute and cannot stop.

### Expected result

the notification only appears once

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/31495943/57411d96-9790-4655-8c9e-59e6f4130a3c)

### Version environment

```markdown
- Version: 2.10.1
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12436681/siyuan.log)

**Comment by 88250** [comment]
We are aware of this issue, but it is difficult to fix due to a lack of asset files that can reproduce the problem.

If it is convenient, please pack the workspace/data/assets/ folder and send it to us for testing 845765@qq.com, thanks.

**Comment by 88250** [comment]
We have solved some known problems, if it is convenient, please download the latest development version to help test, thank you.

**Comment by XinLi0111** [comment]
Thanks, it's sovled. 👍
