### ISSUE TITLE
Change code indentation width and remember indentation level

### ISSUE THREAD

**Issue by donny-chan** [siyuan-note/siyuan#9046]
### In what scenarios do you need this feature?

Currently, using tab to indent in a code block creates a padding width equivalent to 8 spaces, which is not beautiful and does not follow the guidelines of some languages such as Python.

Also, the indentation level is not remembered, which means when I enter a new line in a function block in Python, the caret is located on outside of the function's indentation level, which is counter-productive, because most other editors will remember the indentation.

### Describe the optimal solution

Allow user to set the indentation width in code blocks, and if possible, automatically change it to spaces.
Also remember the current indentation level in code blocks.

**Comment by 88250** [comment]
Please try this one:

![image](https://github.com/siyuan-note/siyuan/assets/873584/7df52e0b-126c-4d21-8c26-4aa467feba5f)

There is a high probability that the code block editing experience cannot be improved. It is recommended to paste it into the code block once after editing in the IDE. Thanks for the feedback.
