### ISSUE TITLE
Option for auto-downloading updates

### ISSUE THREAD

**Issue by donny-chan** [siyuan-note/siyuan#9047]
### In what scenarios do you need this feature?

Redownloading the installer everytime is very cumbersome.

### Describe the optimal solution

Add an option for users to allow the program to auto-download updates in the settings.

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/921aa4c3-7214-434b-a21b-ad3d29789cef)
