### ISSUE TITLE
显示链接类型

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9048]
### In what scenarios do you need this feature?

在思源中实行卡片笔记，但在实行双链时，对链接的样式是模糊（目前思源的特性）
是否可以添加另外一些模式，同时保留当前锚文本的情形下，等于用户可以以这样或那样的方式去实现双链

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/139356383/75865b23-9e52-4a72-a0c0-464661a4c6e9)
普通的锚文本是这样的，我们无法直接显示它的块的类型
我们可以拥有像这样的锚文本，也可以拥有其他样式的锚文本
如，我们需要特意显示，
![image](https://github.com/siyuan-note/siyuan/assets/139356383/63bbf1ef-e5a4-4174-950d-22c0f0bee0c0)
当我们去实行双链，并且显示被链接的类型，假设我链接了一个文档块，那么我可以链接了文档块之后，这个引用块前面显示一个文档的图标。
同样，我们要去引用其他的块，也可以显示被链接的块的类型

**Comment by gaoluji** [comment]
logseq中是这样的，虽然它只是大纲，但它可以实时预览样式
![image](https://github.com/siyuan-note/siyuan/assets/139356383/2f020f7f-7825-406d-bcc5-8ba4090d5aa1)
添加了h3，同时也显示出h3

**Comment by 88250** [comment]
显示块类型会对排版形成一定干扰，暂时不考虑了，感谢提议。

**Comment by gaoluji** [comment]
> 显示块类型会对排版形成一定干扰，暂时不考虑了，感谢提议。

@88250 其实不是全部，我是指在保留原来功能的基础上，再添加这么一个选择吧，一个是指向，一个是引用

**Comment by 88250** [comment]
指向？

**Comment by gaoluji** [comment]
> 指向？

@88250 
d大的思路大概是引用（就是所谓对块的引用），但我在实践卡片笔记中发现，知道自己指向什么还是很有必要的，有些笔记我是引用（就是思源的锚文本，d大认为的锚文本，我认为有点类似链接其他网址的锚文本，只显示文字，但链接潜在，观看者也不知道它到底指向什么，只知道这段文字里有这么些锚文本），但有些我则是直接的指向，不是作为在一段话的内容（这不影响排版），由于思源的块引用过于丰富，这容易造成一些混乱（我不清楚我指向的到底是什么，这个锚文本我甚至不是在段乱中，我只是放在这段话后，摆在那边），若对标ob，则ob是如此（但ob由于其特性，能够即使渲染，我们能很清楚就知道我们链接的是页面，还是页面中的块【它有单独的功能用于说明
![image](https://github.com/siyuan-note/siyuan/assets/139356383/abacc701-a43d-48f9-a819-7470ab78eacb)
】），若对标其他笔记，则确实需要添加这么一个模式，我们可以清楚的指向什么，是文档块，还是段落块，或者其他什么。
d大可能误解了，我是说在当下基础上是否可以再添加这么一种功能，这个是否显示链接类型也是用户可以自己选择的，思源的目前块引用功能也是有极大用处的，这是思源的一个特色。

**Comment by 88250** [comment]
明白了，我之前的理解应该没有问题，你需要的是引用元素上标识出定义块的类型，这个会对排版显示造成一定干扰，所以就不考虑了。

**Comment by gaoluji** [comment]
> 明白了，我之前的理解应该没有问题，你需要的是引用元素上标识出定义块的类型，这个会对排版显示造成一定干扰，所以就不考虑了。

@88250 
![image](https://github.com/siyuan-note/siyuan/assets/139356383/1404c2b8-9c1f-4509-977d-725df24c9d06)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/31730198-42e1-4a99-9395-258d25607afc)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/b10ce5df-dde7-4968-a650-40bcc48de339)
trilium和思源有点类似

**Comment by gaoluji** [comment]
> 明白了，我之前的理解应该没有问题，你需要的是引用元素上标识出定义块的类型，这个会对排版显示造成一定干扰，所以就不考虑了。

![image](https://github.com/siyuan-note/siyuan/assets/139356383/de9991a2-c8a5-4fe3-9c53-232ef8746596)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/28256e54-0273-4feb-9144-c42b7298a222)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/ab694483-394d-494c-a90b-1102b244cb3e)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/9e5476c7-86df-4019-b9cc-292b567f3fe1)

@88250 trilium类似这样
