### ISSUE TITLE
块的单独打开

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9049]
### In what scenarios do you need this feature?

在思源中块可以单独聚焦，但没有单独在侧边打开的功能。
我在一个文档中建立了许多块，并且实行卡片笔记法，但一个块与另一个块间隔很多，我想要固定一个块在侧边展开，如同logseq一般。——单独打开并不是聚焦（聚焦是在原文档内聚焦的）
例：我在一个文档中建立了许多卡片，以一个标题为卡片的象征。
![image](https://github.com/siyuan-note/siyuan/assets/139356383/4c44591f-1ddf-4a37-937b-52da3f8c7792)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/9294f997-fcde-46c6-890a-520007a443a6)
这个文档总计的卡片
但一个卡片去链接另一个较远的卡片，则不太方便

### Describe the optimal solution

参考logseq，实行一个侧边栏（实际上是一个展示各中文本的空间），并且展示的文本可以以一种连续的方式展示，可以折叠，关闭，停留
![屏幕截图 2023-08-25 221704](https://github.com/siyuan-note/siyuan/assets/139356383/0fb21142-a38c-4af6-9343-6e11712d9a0c)
侧边栏上的三个，实际上是文档，可以，展开，可以关闭
![image](https://github.com/siyuan-note/siyuan/assets/139356383/6a27ffd0-02a9-4501-9919-ad103b5b3c5a)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/471136e7-3f6c-4c76-830d-2585a8c95bdd)
也就是说，侧边栏作为一个展示的空间，我们可以把我们想要显示的东西固定在侧边，并且可以随时收缩，展开
![image](https://github.com/siyuan-note/siyuan/assets/139356383/c5deda76-dda6-4516-a8d1-7dadf2c1b7e4)
目录实际上就是一个md文件，只不过以一种固定的方式显示为按钮，我们可以对目录文档进行修改编辑
按住shift再右键，可以在侧边打开（实际上就是打开一个展示的空间）
![image](https://github.com/siyuan-note/siyuan/assets/139356383/f7b3937d-cf86-43fa-a17a-2bb0ff87486e)
我们可以在侧边栏展开多个页面（演示需要，都将其收缩）
![image](https://github.com/siyuan-note/siyuan/assets/139356383/5313bb17-84fb-47f0-b441-89748155a8c8)
我们在正文页面shift+右键，使一个块可以在侧边
![image](https://github.com/siyuan-note/siyuan/assets/139356383/5fa78c18-6b76-4ee5-a380-501790c39eb8)
也可以对这个文档（页）显示在侧边栏
![image](https://github.com/siyuan-note/siyuan/assets/139356383/8b5d47ce-8ea6-4462-9726-ff58cc13bece)
我们可以发现，它们的图标类型也是不一样的
![image](https://github.com/siyuan-note/siyuan/assets/139356383/cab09b56-5560-49e9-befd-7fd69c7c62d8)

### Describe the candidate solution

使用ctrl+shift+右键，使一个块（各中类型的块）显示在侧边栏，并且可以固定住
侧边栏作为一种功能，类似插件文档流
![image](https://github.com/siyuan-note/siyuan/assets/139356383/20b8ba1d-509f-42f9-b4fb-7e7602170b51)
在侧边栏上，我们可以像logseq一样，把某些文档设置为按钮（这样我们直接点击，直接就在侧边栏中显示，这和普通的点击双链不同，普通的双链点击后是直接打开页面的），按钮可以自定义，比如，我可以把“日记”、“目录”、“学习”这些文档作为固定按钮

**Comment by gaoluji** [comment]
在侧边栏的文本也是可以编辑的

**Comment by zxhd863943427** [comment]
想法很好，但官方估计不会有时间做，建议先用分屏吧。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/fbc811b4-f1e4-4eac-b312-ad1dbbca8650)

**Comment by mozhux** [comment]
在面包屑上对想要单独看的块悬浮出来盯住也可以变成新窗口打开。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/3f731a9c-d0b3-467e-b78c-302ae1b848d5)
![image](https://github.com/siyuan-note/siyuan/assets/46953371/d12105f3-bfcd-45a4-9ef6-3f2e7529b175)

**Comment by 88250** [comment]
暂时就这样吧，感谢各位。
