### ISSUE TITLE
预览时模糊标记

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#905]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

当前可以直接使用的标记有
* *斜体*
* **加粗**
* ==高亮==
* `行内代码`
* ~~删除线~~
通常使用这些标记，表示某些重点、含义。
那么希望在预览时，能够模糊（当然可以是其他形式，只要遮掩住就好）这些标记，这样很方便复习。
### 描述最优的解决方案 Describe the optimal solution

为了顾及之前的使用习惯，可以这么设计，在预览处，或者工具栏上添加
 * 全局 模糊 or not？
 * 需要 模糊，那么模糊什么标记？
 * 下拉选择标记模糊，打勾：斜体、加粗、高亮、行内代码、删除线。
 * 预览的模糊效果，可以使用filter: blur(px);。
### 其他信息 Other information
这个功能希望能引进，对于很多做笔记用来复习的同学会很有用，当然短期不可能实现，希望后期能够考虑~辛苦了

**Comment by 88250** [comment]
v0.5.6 会实现行级元素属性，届时就可以自定义行级元素的样式了，谢谢。
