### ISSUE TITLE
关于参照 supermemo 改进闪卡

### ISSUE THREAD

**Issue by edward-kyle** [siyuan-note/siyuan#9050]
### In what scenarios do you need this feature?

https://ld246.com/article/1676997996787

我不是这个链接里帖子的原作者，只是转载一下

先把这条加进issue里，等明年开始更新闪卡功能后再参照着改进吧

### Describe the optimal solution

https://ld246.com/article/1676997996787

**Comment by zxhd863943427** [comment]
为什么不看看闪卡增强插件……闪卡增强插件的图片遮挡也快出了，如果没bug的话。

**Comment by gaoluji** [comment]
> 为什么不看看闪卡增强插件……闪卡增强插件的图片遮挡也快出了，如果没bug的话。

@zxhd863943427 真的吗，老哥

**Comment by edward-kyle** [comment]
> 为什么不看看闪卡增强插件……闪卡增强插件的图片遮挡也快出了，如果没bug的话。

老哥，闪卡增强和supermemo还是有很大差距的，好吧

**Comment by edward-kyle** [comment]
再加一个帖子，里面的讨论很好
https://ld246.com/article/1676961215572

**Comment by edward-kyle** [comment]
再加一个
https://ld246.com/article/1646971096168

**Comment by edward-kyle** [comment]
再加一个
https://ld246.com/article/1646971096168

**Comment by edward-kyle** [comment]
再加一个
https://ld246.com/article/1646971096168

**Comment by zxhd863943427** [comment]
闪卡增强的目标不是完全追上sm，客观来说，sm 18 $60.00，而闪卡插件既没有这个售价，也不会有这个追求。我仅仅是说，摘录和挖空功能是实现的，而且我认为在思源中不会有更好的实现了。

此外，你也没有总结提炼帖子的内容，说出你认为的改进之处可以在哪里，我认为这个issue作为特性提议是不太好的。
