### ISSUE TITLE
PDF files longer than 1024 pages are not included in asset file content searching

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9053]
Performance has been improved in https://github.com/siyuan-note/siyuan/pull/9051, but it is still very slow for too large PDF files (and the memory usage is too high), so it can only be excluded from parsing.

```
PDF with 13744 pages using 12 workers took 17m4.761218s
```

**Comment by zxhd863943427** [comment]
我认为这个最好设置为可设置项，因为确实存在哪怕需要长时间索引也能接受的需求。

**Comment by 88250** [comment]
@zxhd863943427 后面看有需求再考虑。
