### ISSUE TITLE
docker版本下控制台输出访问172.16.92.202资源报错

### ISSUE THREAD

**Issue by garrettzuo** [siyuan-note/siyuan#9057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

访问i位于172.16.92.202的资源
111.67.204.91/:1 Access to fetch at 'http://172.16.92.202/disable/disable.htm?url_type=%E8%AE%BF%E9%97%AE%E7%BD%91%E7%AB%99/%49%50%E7%AB%99%E7%82%B9&plc_name=%E7%B3%BB%E7%BB%9F%E4%B8%9A%E5%8A%A1%E4%B8%AD%E5%BF%83%E7%A6%81%E6%AD%A2' (redirected from 'http://111.67.204.91:6806/api/asset/upload') from origin 'http://111.67.204.91:6806' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

### Expected result

正常使用

### Version environment

```markdown
- Version: v2.10.1
- Operating System: Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016
- Browser (if used):chorme
```

### Log file

分享名称：siyuanlog
分享链接：https://www.pandazoo.top/#s/9mQ6p85A
访问密码：c4TQP

**Comment by 88250** [comment]
你好，请配置反向代理，并使用同一个 IP/域名 访问。

**Comment by garrettzuo** [comment]
@88250 你好问一下怎么配置反向代理
我在ngnix中配置存在问题server {
    listen                80;
    server_name           biqu.deone.pandazoo.top;
      location / {
    		proxy_pass        http://127.0.0.1:6806;
                proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        }
}

**Comment by 88250** [comment]
网络搜索一下吧，有一些其他人写的经验教程。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月28日(周一) 晚上7:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] docker版本下控制台输出访问172.16.92.202资源报错 (Issue #9057)




 
@88250 你好问一下怎么配置反向代理
 我在ngnix中配置存在问题server {
 listen                80;
 server_name           biqu.deone.pandazoo.top;
 location / {
 proxy_pass        http://127.0.0.1:6806;
 proxy_set_header Host $host;
 proxy_set_header X-Real-IP $remote_addr;
 }
 }

**Comment by garrettzuo** [comment]
配置好了之后开启插件市场还是有问题，关闭没有
