### ISSUE TITLE
Fix some broken references in Chinese user guide

### ISSUE THREAD

**Issue by Demonese** [siyuan-note/siyuan#9059]
浏览Windows商店版客户端自带的用户指南-数据安全部分时提示有内容块未找到

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

提示有内容块未找到

### Expected result

不会出现报错

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/57629614/aadbcfb8-d2ff-4f44-9903-1861fadc2c75)

### Version environment

```markdown
- Version: 2.10.1
- Operating System: Windows 11 22H2 2023年7月更新
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12449906/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，下个版本修复。
