### ISSUE TITLE
修改自定义主题，重启后无效

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#906]
### 描述问题 Describe the problem

自定义主题（不是custom，自己整了个新主题，也应用上了），貌似只会记住最初的设置。
后续我再修改，重启思源后，修改无效，还是最初的设置。

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/69628966/103433217-8e049580-4c28-11eb-962b-1e0e8e426a0e.png)
![s](https://user-images.githubusercontent.com/69628966/103433239-ed62a580-4c28-11eb-984a-e47f5cac4e08.gif)

### 版本环境 Version environment

* 版本 Version：0.5.46
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

![image](https://user-images.githubusercontent.com/69628966/103433243-16833600-4c29-11eb-982f-47082c5bce4c.png)

**Comment by 88250** [comment]
请参考帮助文档中主题章节进行开发，谢谢。

**Comment by yeshaopeng6688** [comment]
> 请参考帮助文档中主题章节进行开发，谢谢。

我就是按照你们要求开发的 = =。只不过我没有上传到社区，自己用而已。
我刚把名字改了（对应的主题文件夹名也改了），重启更换就改过来了。
但是，我再去修改，还是保持原样，= =。这应该是个bug吧。
因为以前在theme.css我直接修改就能改，重启后也能保持。
但这个版本就不行了。难道新版本修改主题要重新换主题这么麻烦的么= =。。

**Comment by 88250** [comment]
下面打开了自定义主题么？打开的话关闭了看看。

**Comment by yeshaopeng6688** [comment]
我知道为啥了 = =。
貌似之前theme.json的要求，没有说要name。
也可能是我忘记加了，但是我之前没加name，用以前的版本也可以随时修改成功。
现在加了name，可以随时修改了 = =。打扰了

**Comment by yeshaopeng6688** [comment]
不新开帖子了，记一个小问题。
最新版本0.5.5，撤销操作，只有光标定位到撤销位置，但页面还是停留在当前位置。

**Comment by 88250** [comment]
收到，后期改进，谢谢。
