### ISSUE TITLE
能否像remnote一样使用【【功能检索时，显示锚文本

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9060]
### In what scenarios do you need this feature?

思源引用中容易检索到锚文本，是否可以在使用【【功能时，可以显示出锚文本来？

### Describe the optimal solution

remnote的解决思路
![image](https://github.com/siyuan-note/siyuan/assets/139356383/c6ad2ae3-e767-405d-9376-7e2475bb0eac)
【【功能引用检索时，可以同时展示锚文本（被加粗），并且可以悬浮显示
![image](https://github.com/siyuan-note/siyuan/assets/139356383/50bf5eca-345d-4e64-94a0-4829f8b66ebb)

**Comment by 88250** [comment]
这个做不到，自动完成候选列表中的是纯文本，感谢反馈。
