### ISSUE TITLE
prependBlock存在特殊格式的链接/嵌套格式会导致无法渲染和错误

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#9062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

插入的数据是这样的：

```JSON
{"data":"((20230827220737-ojz44ha 'User Data'))\n\n---\n\n**Title**:\t测试条目\n\n**Type**:\tjournalArticle\n\n**Authors**:\t瑞奇 柯\n\n**Year**:\t2008\n\n\n\n**Zotero URL**:\t[Select on Zotero](zotero://select/library/items/G684WP42)\n\n---\n\n# Abstract\n\n这是一个摘要\n\n\n# Files\n\n[[Locate]](zotero://select/library/items/N5UL9J94)\t|\t[柯_2008_测试条(目.txt](file://D:&#92;Documents&#92;Box Sync&#92;Zotero&#92;测试的期刊2008&#92;柯_2008_测试条&#92;(目.txt)\n\n\n\n\n","dataType":"markdown","parentID":"20230827170752-j2femhz"}
```

其中 `[柯_2008_测试条(目.txt](file://D:&#92;Documents&#92;Box Sync&#92;Zotero&#92;测试的期刊2008&#92;柯_2008_测试条&#92;(目.txt)`无法被识别为链接（如下图），然后在末尾按下空格之后才会被完整地识别为链接。

![image](https://github.com/siyuan-note/siyuan/assets/63407442/eef270ef-559b-4380-b458-9bac4a1eee57)

### Expected result

识别并渲染为链接的过程应该是在插入的时候就完成的。

### Version environment

```markdown
- Version: 2.10.1
- Operating System: windows
- Browser (if used):
```

### Log file

无

**Comment by WingDr** [comment]
另外，通过markdown插入超级块中的引用也没法正确渲染，我插入的内容为：

```javascript
return `{{{row
          > ${content.detail.annotationText}
          [Open on Zotero](${content.openURI})

          ${content.detail.annotationComment ? content.detail.annotationComment : ""}
        }}}`;
```

这段内容会被渲染为

![image](https://github.com/siyuan-note/siyuan/assets/63407442/51f7d1f9-f58a-4ba3-85bf-c64ff724826c)

超级块确实分好了，但是引用块没渲染。如果我在这里直接插入dom的话，因为超级块用的是div标签所以会直接被识别成HTML块。

此外，我还试验了一下直接复制，代码为：

```markdown
{{{row
> 韩炳哲试图用此书阐明这样一个观点：纯粹意义上的爱， 曾经被置于一个悠久的历史传统之中的爱，如今受到了威胁， 甚至已经死亡；不管怎样，当今的爱是病态的，正如作者给这 本 书 所 起 的 题 目 一 样 ——“ 爱 欲 之 死 ” （ Agonie Des Eros）。
[Open on Zotero](zotero://open-pdf/library/items/R23X3PJ4?page=3&annotation=2P8R93AJ)

comment
}}}
```

直接复制到编辑器中的结果为：

![image](https://github.com/siyuan-note/siyuan/assets/63407442/d9e2b7c8-66fa-4534-a44e-32c85e064850)

确实是正确渲染了

**Comment by 88250** [comment]
第一个问题：超链接地址需要加转义：

![image](https://github.com/siyuan-note/siyuan/assets/873584/cf860ede-da17-4545-9bb6-d2ea618e4618)

第二个问题：我这里测试正常，你看下是不是你的换行符不对：

![image](https://github.com/siyuan-note/siyuan/assets/873584/6fac4464-6d1f-4cf9-a9b0-6b1b3ae707c8)

**Comment by 88250** [comment]
建议用个 http 客户端测试一下，比如 postman

**Comment by WingDr** [comment]
找到原因了，是template.js的锅，自动把东西给我转义了，思源没问题。感谢D大陪我这么搞了一通

**Comment by 88250** [comment]
没事。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月28日(周一) 晚上9:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] prependBlock存在特殊格式的链接/嵌套格式会导致无法渲染和错误 (Issue #9062)




 
找到原因了，是template.js的锅，自动把东西给我转义了，思源没问题。感谢D大陪我这么搞了一通
