### ISSUE TITLE
Abilities to conceal unnecessary icons on main interface

### ISSUE THREAD

**Issue by STMRabbit** [siyuan-note/siyuan#9067]
### In what scenarios do you need this feature?

There are multiple icons on the panels/ title bar that some user don't use, like the inbox, subscription crown, and graph view, etc.

### Describe the optimal solution

There ought to be options to select to hide them.

### Describe the candidate solution

I apologize if this design is driven by business operational reasons. If so, I think this “hide icon” feature could be included into the new “one-time-paid” plan, how do you think?
Thank you!

**Comment by 88250** [comment]
Hello, Native does not consider providing such a function for the time being. Maybe we can look forward to the community plugin implementation, thanks for the suggestion.
