### ISSUE TITLE
Improves the quality of annotated copies of PDFs in Windows

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9068]
### In what scenarios do you need this feature?

在左右分屏情况下，pdf矩形标注获得的图片比较模糊，不能满足使用，导致实际使用时必须放大pdf区的比例来获得更清晰的图片，但对于左右分栏的pdf还是不够。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/cb7c42bf-3f1c-450a-b206-9ae22f155473)

如果能给pdf矩形标注复制增加一个可设置的固定系数，就能提高这样的体验，增强pdf分屏模式下矩形标注的实用性。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/291f9b03-7c37-490f-acba-52f4a84ccfcc)

### Describe the optimal solution

将固定系数的调节加入到思源的设置中，固定系数的实现参看
https://github.com/siyuan-note/siyuan/commit/cc2cc04581cba2569c8da4a80530914e231cf3c4

### Describe the candidate solution

如果实在不行，那我也希望能设置一个恒定的固定系数，我认为可以是1

**Comment by zxhd863943427** [comment]
emmm，核心想法不是为了相对实际大小设置的，而是相对目前显示大小设置的，因为canvas渲染的效果在相同像素下明显比思源中查看要好，所以需要调大截取的比例，保证两者的显示效果差不多。如果使用其他的图片查看器，比如直接使用window的照片，增加0.5的系数就很足够了。

不过移除后为什么是两倍大小？这个结论是怎么来的，能发来测试的pdf吗？

**Comment by Vanessa219** [comment]
如果放太大的话，这种小图片就每次都需要用户去手动调整大小，很麻烦
<img width="1040" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/9525eff3-8dcf-4b32-96f1-781ece2569c0">

不用实际的话，用户每次调整缩放后再次复制的就都不一样（尤其是选择自动缩放后），这样用户还是需要去手动调整成一样，感觉也很麻烦。


不知道是不是因为 scale 等于 2，这个 debugger 能看出问题么？不能的话我再私发  PDF 给你
<img width="983" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/074c7d13-6752-4255-8bf2-56cf7cdbe17c">

**Comment by zxhd863943427** [comment]
那我明白了，这个scale获取的是全局或应用的缩放，也就是windows的这个设置：

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/eb1c8ec5-15b5-4e73-ada6-770462155e29)

v姐你应该用的是4k屏加全局2倍缩放，才会有这个scale。

但是，在思源或者说web应用中，canvas使用的是实际像素，应用中的图片使用的是被全局缩放影响过的放大像素。因此，虽然从canvas中截取的就是真实的图片大小，但是在思源中显示是会放大的。

如果要保证两者的目测大小一致，那应该取scale的倒数，这样会导致显示效果更加的模糊，在v姐你的设备上相当于原始图片放大4倍的清晰度，我认为这才是不可接受的。

因此，这虽然与用户的第一直觉不符，但是才是合理的做法。

另外，截取这么少的面积对于矩形标注来说才是少见的用法，大面积的框选才是更为常见的，为了这方面的用途，还是需要增加放大系数。

**Comment by zxhd863943427** [comment]
另外，使用显示的大小作为基准是很有必要的，因为pdf的大小和形式都是不确定的，有分屏的、纵向的、还有大小经过缩放的，我们没办法使用pdf上的参数确定这个图片截取到什么缩放才是合理清晰的，只能以用户在查看时使用的是什么缩放作为参考。

所以我的想法就是在用户目前查看的缩放等级上增加一个固定值，这样才能更好的以不变应万变。

**Comment by Vanessa219** [comment]
我的是 Mac，应该没有进行过缩放。

是否可以把导出的图片的大小设置为实际大小下的像素值，这样不仅可以兼容中小图，还可以保持任何情况下复制后的图片大小。

**Comment by zxhd863943427** [comment]
我查了一下，mac的应该会有默认的缩放设置
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/6a16e6ab-076a-4314-86cc-3cc72d503a01)
v姐你可以使用手动截图看看，应该会发现截图的显示大小是你实际截取大小的2倍。

因此，这实际上是一个显示的问题，可以在初始化阶段先获取缩放系数，然后反向设置css即可。

**Comment by Vanessa219** [comment]
我调整了一下，你看看这个效果是否可以？

**Comment by zxhd863943427** [comment]
依然模糊，这个真的是显示大小的问题。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/928c6496-8fbe-455f-bcca-db4139eb32df)

**Comment by zxhd863943427** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/69866abb-c504-43fd-8ce5-934e0a4b9c43)
这是我直接修改css的效果。

**Comment by Vanessa219** [comment]
我换个电脑看看 ，感觉我这个还可以
<img width="1168" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/2773a8bb-dfe6-46a6-a482-260308879031">

**Comment by zxhd863943427** [comment]
但是清晰度下降真的很严重啊……明显是变大且模糊了。

而且v姐你不应该截取小区域进行测试吗？

**Comment by Vanessa219** [comment]
我在 Window 上看并不模糊，大的2倍不到。
![f66bb407bed54f111eab96f4ab03f6f3_720](https://github.com/siyuan-note/siyuan/assets/970828/18bff8c0-bd20-4977-8748-7a49b55b68b8)

**Comment by zxhd863943427** [comment]
完全不行，属于不可接受的等级。正如我之前说的，不可能从pdf中得知什么样的缩放最合适，比如我找了一个字比较小的pdf，那么公式已经完全看不清了。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/b7d92f26-5a85-43aa-9b41-c3d1203b81fc)
依靠用户当前的缩放才是更加合理的，

**Comment by Vanessa219** [comment]
这应该属于比较特殊的情况，可以用 QQ 截图代替一下。

**Comment by zxhd863943427** [comment]
而且，特殊情况也并不特殊，从我的图片版pdf里，一半都会出现这种情况。文本还能直接划选，那图片版该怎么办？

**Comment by zxhd863943427** [comment]
我提交这个pr是为了能根据需要获取高清的截图，痛点是之前总是有边框，截的图片不够清晰，但是这越改越难用……我是真的很难受。

**Comment by zxhd863943427** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/f3e35969-0b00-4593-a51d-b6fbb99100af)
这种例子是很多的。

**Comment by zxhd863943427** [comment]
[Uploading test.pdf…]()
v姐你也可以自己用这个pdf试试。

**Comment by zxhd863943427** [comment]
再来一个过大的
[干燥技术在果蔬中的应用综述.pdf](https://github.com/siyuan-note/siyuan/files/12496476/default.pdf)

**Comment by Vanessa219** [comment]
好像也有道理，可能平常 pdf 用的比较少。

**Comment by zxhd863943427** [comment]
那v姐可以重新考虑一下这个吗？

**Comment by Vanessa219** [comment]
嗯嗯，这个版本会改的，要晚一点，还在改其他的 issue。

**Comment by Vanessa219** [comment]
设置为 1.5 倍，麻烦再帮忙看看是否可行？

**Comment by zxhd863943427** [comment]
能同时满足这两个文件的只能是动态缩放。

**Comment by Vanessa219** [comment]
昨天已经改成动态的了

**Comment by zxhd863943427** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/bc443c7e-42a6-4d76-9755-42d186aa955a)
从实际情况来看，依然是固定的

**Comment by Vanessa219** [comment]
是 Dev 分支的代码，在 600% 和 200% 下的情况
<img width="985" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/cb840aff-ca52-4949-9734-41ced06df6dd">

**Comment by zxhd863943427** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/6db7a13e-374d-43b6-8fa4-ae9e3aa48717)
刚刚试了下，是我没刷新的原因……

**Comment by Vanessa219** [comment]
画质什么没问题的话，这个 issue 就这样吧，今天要打包发布了。

**Comment by zxhd863943427** [comment]
在左右分屏的情况下，分栏的pdf图像略微模糊……v姐你要不还是用我这个提交 https://github.com/siyuan-note/siyuan/commit/cc2cc04581cba2569c8da4a80530914e231cf3c4 吧，目前这个在小缩放的时候还是会有点模糊。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/7376c9b0-b0fb-40e4-8fa1-3bdf2531d743)


<html>
<body>


原缩放 | 1.5倍放大 | +1放大
-- | -- | --
0.5 | 0.75 | 1.5
0.75 | 1.125 | 1.75
1 | 1.5 | 2
1.25 | 1.875 | 2.25
1.5 | 2.25 | 2.5
2 | 3 | 3
3 | 4.5 | 4
4 | 6 | 5



</body>
</html>
如果发包要紧的话，那下个版本继续调整也行

**Comment by zxhd863943427** [comment]
这个模式在不使用分栏的pdf的情况下是能接受了。

**Comment by Vanessa219** [comment]
这个 PDF 看上去是不太清晰的，我们是否可以理解为用户在使用的时候如果不在乎清晰程度，最终也不会太在意截图的清晰程度。

<img width="670" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/83f8d667-1755-4531-b733-caa159f825b9">

如果要修改的话，是不是需要在这里根据缩放的大小来使用某个算法来使其最终截图不会过于太大而且清晰？

<img width="723" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/4814e395-c423-4de9-9094-655796b4c673">

**Comment by zxhd863943427** [comment]
这个pdf是一个矢量化的pdf，实际上的分辨率是无限的。显示较不清晰只是受到分屏时屏幕大小的限制。

> 是否理解为用户在使用的时候如果不在乎清晰程度，最终也不会太在意截图的清晰程度。

我认为这一点是不太正确的，实际上用户自然是希望无限清晰的，只是受到了图片体积的制约。如果说用户最终选择了较为有限的清晰度，那也只是出于图片体积和图片清晰度的综合考量。

但无论如何，用户肯定是希望图片在查看的时候是清晰的，只是不要求无限放大也能保持清晰。因为思源图片总是相较于pdf中相同的像素放大显示，因此增加放大系数来获取截图是符合用户意愿的。

> 如果要修改的话，是不是需要在这里根据缩放的大小来使用某个算法来使其最终截图不会过于太大而且清晰？

因此，这里的说法只能有限的成立，正确的说法是需要根据缩放的大小，来使用某个算法来使其最终截图在清晰度可接受范围内、体积不会过大。

在我观察了各种算法的效果后，我觉得还是直接使用加法来增加放大系数比较简单且效果可接受，更强的算法是获取截取面积和屏幕面积，然后进行在使用非线性算法进行计算，但这个就比较麻烦一点。我pr的哪个原始版本直接修改getCaptureScale就行，在v姐你改成现在的代码后，我觉得是有点难以下手了。

**Comment by zxhd863943427** [comment]
如果v姐你觉得可以的话，我觉得可以到ld社区进行一下投票，来一个小规模的抽样调查。

**Comment by Vanessa219** [comment]
搜索 1.5 这个，目前是写死的，修改为需要的算法应该就可以了。
