### ISSUE TITLE
Cursor lost while editing while zoom in on document

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#9071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

视频里是我写的一个插件，在2.10.1中没有问题，但是在2.10.2中出现了视频中的情况，控制台中显示没有querySelector（应该是没找到protyle的节点），剩余的插件我已经关闭，插件本身的监听也已经关闭，布局用的是murri.js，本身没有大量的监听（2.10.1中我也使用了这个，但是没有这个问题，应该是新增的功能产生的）。

使用默认主题也是一样的，只不过录视频的时候是用的Savor主题

https://github.com/siyuan-note/siyuan/assets/63407442/567ccaa2-bb4e-496e-a470-a19e49ab7ae0

另外关闭这个tab以及关闭插件之后仍然出现了这种情况，呈现的效果就是输入之后光标消失

### Expected result

应该确切定位到原本位置

### Version environment

```markdown
- Version: 2.10.2
- Operating System: Windows
- Browser (if used):
```

### Log file

控制台的错误完整是这样的：

```log
main.1e7b2c2c5d76f49ec39a.js:3174 fetch post error TypeError: Cannot read properties of undefined (reading 'querySelector')
    at Jf (main.1e7b2c2c5d76f49ec39a.js:1249:24229)
    at Object.callback [as afterCB] (main.1e7b2c2c5d76f49ec39a.js:1249:26142)
    at lp (main.1e7b2c2c5d76f49ec39a.js:1384:11881)
    at ct (main.1e7b2c2c5d76f49ec39a.js:1384:6583)
    at main.1e7b2c2c5d76f49ec39a.js:1247:26355
    at main.1e7b2c2c5d76f49ec39a.js:3174:2854
（匿名） @ main.1e7b2c2c5d76f49ec39a.js:3174
Promise.catch（异步）
b @ main.1e7b2c2c5d76f49ec39a.js:3174
Ut @ main.1e7b2c2c5d76f49ec39a.js:1247
Nc @ main.1e7b2c2c5d76f49ec39a.js:1249
（匿名） @ main.1e7b2c2c5d76f49ec39a.js:3447
msgCallback @ main.1e7b2c2c5d76f49ec39a.js:3447
i.onmessage @ main.1e7b2c2c5d76f49ec39a.js:34
```

发成错误的代码是这里：

![image](https://github.com/siyuan-note/siyuan/assets/63407442/62604299-7505-4aad-aff5-f5c972cdf865)

然后再进入Jf之后是这里

![image](https://github.com/siyuan-note/siyuan/assets/63407442/f3a87351-92cb-47ee-973a-08ac86700732)

应该是这个n有问题

**Comment by Vanessa219** [comment]
这个可能需要调试一下，你的插件发我看一下

**Comment by WingDr** [comment]
[siyuan-plugin-zettelkasten.zip](https://github.com/siyuan-note/siyuan/files/12483153/siyuan-plugin-zettelkasten.zip)

名字就是这个压缩包的名字，这个是编译后的版本，github的链接[在这](https://github.com/WingDr/siyuan-plugin-zettelkasten)

**Comment by WingDr** [comment]
[siyuan-plugin-zettelkasten.zip](https://github.com/siyuan-note/siyuan/files/12483153/siyuan-plugin-zettelkasten.zip)

名字就是这个压缩包的名字，这个是编译后的版本，github的链接[在这](https://github.com/WingDr/siyuan-plugin-zettelkasten)

**Comment by Vanessa219** [comment]
点按钮没作用，是因为报错了么？
<img width="1307" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/48e645c8-3e01-4d2f-a9c1-b040a5bfe043">

**Comment by WingDr** [comment]
忘了说咋用了orz

设置界面在这里：
![image](https://github.com/siyuan-note/siyuan/assets/63407442/f03507e8-d16c-4b51-8091-4d8dd890fa67)

打开之后设置好这两项：
![image](https://github.com/siyuan-note/siyuan/assets/63407442/f3b38dfd-6132-47be-93a6-b18608e947a8)

就是放置文档的笔记本和路径（最后没有'/'）。在这个路径下面放上任意内容的文件
![image](https://github.com/siyuan-note/siyuan/assets/63407442/e4a08f72-a90a-487b-9193-f99f50a2764d)

然后再打开卡片视图就行了。设置好路径之后也可以用这个快速新建文件，点保存就会新建，点取消或者点外面关闭就不会。
![image](https://github.com/siyuan-note/siyuan/assets/63407442/103dfd67-40b5-4453-b33e-f4c8d7d45f7a)

抱歉这个目前大部分都是直接复制的我之前插件的东西，所以设置起来有点复杂，辛苦了
