### ISSUE TITLE
Versions below Android 11 are no longer supported

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9077]
![image](https://github.com/siyuan-note/siyuan/assets/873584/0084daf8-7e61-46e4-94aa-53d188937042)

![image](https://github.com/siyuan-note/siyuan/assets/873584/406df888-7312-4e3a-98ba-69bb424a1410)

**Comment by zxhd863943427** [comment]
请问minSdkVersion会改吗？

**Comment by 88250** [comment]
公告没有要求这个，暂时不会改变。

**Comment by 88250** [comment]
似乎现在已经满足公告要求了，那我们就暂时不调整了。

**Comment by 88250** [comment]
之前我理解有误，已经删除思源相关公告，给各位造成误解十分抱歉。
