### ISSUE TITLE
Reduce the memory usage of PDF asset file content parsing on the mobile

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9079]
Otherwise, it is easy to cause the application to crash when indexing asset files on the mobile.

**Comment by 88250** [comment]
@nekrondev Hello, I tested a PDF here. The memory occupied by a single core is about 1G. If it is 4 cores, it will take more than 3G, so it will cause the mobile app to crash.

Do you currently have a better way to reduce memory usage? If you need the PDF sample, please send me an email (845765@qq.com), and I will send you this PDF sample as an email attachment, thank you.

**Comment by zxhd863943427** [comment]
2.10.2的移动端似乎并不能搜索资源文件。

**Comment by nekrondev** [comment]
Hello @88250 I'll have a closer look into this. The `go-pdfium` project writes about memory consumption if multiple workers are added. I think I'll do some investigation into dynamically allocating a worker pool if there is no memory pressure, i.e. read the available system memory and launch more or less workers.

**Comment by 88250** [comment]
@nekrondev 

It was only found through today's test that the mobile does not support PDF parsing and an error will be reported under Android:

```
convert [/storage/emulated/0/Android/data/org.b3log.siyuan/files/siyuan/temp/convert/asset_content/u6uhcrz.pdf] failed: [could not instantiate webassembly module: module[] function[_initialize] failed : permission denied (recovered by wazero)
```

It will directly cause a crash under iOS (I guess wazero is not compatible with iOS).

For PDF parsing, let's give up mobile support for now.
