### ISSUE TITLE
能否允许siyuan客户端关闭chrome的禁止autoplay安全策略

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#9081]
### In what scenarios do you need this feature?

在做一个思源启动页面美化插件，想在auth页面的时候自动播放bgm，目前必须要手动点击时间之后，才允许播放音频，可以通过下面的方法添加打包代码，把这个限制去掉，这样就能在登录页面自动播放bgm了，不知道是否可行？

### Describe the optimal solution

https://juejin.cn/post/6844903877305712654

> electron打包的客户端可以在主进程中嵌入如下代码即可解决（至少目前发现是可用的）：
>
> ```
> reasonml复制代码// 在creatWiindow的时候使用
> app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');
> ```

**Comment by 88250** [comment]
这个是故意禁止自动播放的 https://github.com/siyuan-note/siyuan/issues/7587

**Comment by HowcanoeWang** [comment]
我就说好像最近b站自动播放给停了，原来是这样
