### ISSUE TITLE
The floating window preview doc block no longer loads the last browsed location

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9082]
https://ld246.com/article/1693481468348

**Comment by choyy** [comment]
希望从搜索面板打开一个文档块时能跳到上次浏览位置

**Comment by Vanessa219** [comment]
> 希望从搜索面板打开一个文档块时能跳到上次浏览位置

搜索是需要定位到搜索的内容

**Comment by choyy** [comment]
我是说像这样搜索一个文档，打开文档定位到上次浏览位置，搜索界面打开文档应该等效于从文档树打开文档




chu-yy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siyuan-note/siyuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [siyuan-note/siyuan] The floating window preview doc block no longer loads the last browsed location (Issue #9082)





  
希望从搜索面板打开一个文档块时能跳到上次浏览位置
  
搜索是需要定位到搜索的内容

**Comment by 88250** [comment]
@choyy 懂了，感谢反馈。
