### ISSUE TITLE
Improve block loading performance on Windows/Linux/macOS amd64 arch

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9084]
https://github.com/bytedance/sonic

**Comment by zxhd863943427** [comment]
性能提升如何？

**Comment by 88250** [comment]
大致快两倍。



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 1, 2023 11:52 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve block loading performance onWindows/Linux/macOS amd64 arch (Issue #9084)




 
性能提升如何？

**Comment by zxhd863943427** [comment]
windows出现什么问题了？

**Comment by 88250** [comment]
部分系统内核崩溃，不确定是不是这个引起的。



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 6, 2023 18:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve block loading performance onWindows/Linux/macOS amd64 arch (Issue #9084)




 
windows出现什么问题了？
