### ISSUE TITLE
思源启动和锁屏资源优先从工作空间中读取

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#9088]
### In what scenarios do you need this feature?

开发启动项美化插件时，在折腾群里听到的一些主题作者的要求，希望该插件可以读取主题中的一个配置文件，从而实现不同主题能自定义启动和锁屏界面，使得主题风格统一。

但上面的需求和目前思源的启动逻辑重度不相容。因为目前思源启动(index.html)和工作空间的锁定页面(auth.html)，都是从安装目录下拉取的（**我的插件目前也是通过直接修改安装目录下的文件实现的**），这意味着，一个工作空间中插件的修改，会影响思源所有的启动效果。

但是同时经测试，我发现每次思源启动，都会先把`${appDir}/appearance/boot/`文件夹下所有的文件(`index.html` +` icon.png`) 覆盖到工作空间的目录`${workspaceDir}/conf/appearance/boot`中。或许可以通过利用这个特性来作为突破口。于是想出来一个可能的方案，还希望能探讨一下可行性：

1. 工作空间初始化时(新建工作空间时)，把启动页面和锁定页面都复制一份到`${workspaceDir}/conf/`中，具体而言，重点要包括以下几个文件夹（其余的文件也可以复制一份）：
    * `${appDir}/resources/app/electron/` -> `${workspaceDir}/conf/app/electron/`，重点包括boot.html、icon.png (启动页面一开始，会调用这两个)
    * `${appDir}/resources/appearance/boot/` -> `${workspaceDir}/conf/appearance/boot/`, 重点包括index.html、icon.png (跟前面的一样，但启动页面随后会用这两个来进一步更新进度条，**这边是不是跟前面重复了但算bug没发现？**)
    * `${appDir}/resources/stage/` -> `${workspaceDir}/conf/stage/`, 这个目录下的auth.html、icon.png、loading.svg等，都是主题可以自定义的替换元素
2. 在`${workspaceDir}/conf/conf.json`中(或重新用个json记录一下)，记录一下启动页面的版本号，用于后续客户端更新后，更新上面复制过的文件
3. 思源启动时，优先从上面的工作空间文件夹中拉取html等元素，进行前端的渲染，这样就能保证每个工作空间都是独立的启动文件，插件也能直接通过工作空间的根目录，去进行html的修改等操作，而不用担心影响安装目录和其他工作空间。

### Describe the optimal solution

另外，我在修改锁定界面auth.html时，发现添加图片等src的路径，不论是'xxx.png'，'./xxx.png'，'/xxx.png'，都解析为`127.0.0.1: 54235/xxx.png`，而不是安装目录下和auth.html同路径的xxx.png。这个特性或许在上面的迁移时，也要考虑。

举个例子：迁移后为`${workspaceDir}/conf/stage/auth.html`, 如果能支持src="./xxx.png" 解析为同路径下`${workspaceDir}/conf/stage/xxx.png`，在主题开发调试时直接用浏览器双击打开auth.html然后原封不动的迁移到思源中即可。但目前还需要把src="./xxx.png"更改为`/conf/stage/xxx.png`才能保证资源不404。

**Comment by 88250** [comment]
有些比较复杂的情况，比如回退版本和混用版本启动同一个工作空间，这些情况按 conf 版本号的话估计会有问题。另外还要考虑移动端和浏览器端，启动过程最好不要动，否则进不去影响比较大。

我关闭 issue 了，谢谢。
