### ISSUE TITLE
Subdocuments created by the database are not displayed in the doc tree

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9091]

**Comment by mozhux** [comment]
不显示的前提是他也要能支持点击侧栏打开这样的或者新页签打开，也能在视图里被整个搜索到？

**Comment by 88250** [comment]
@mozhux 是的，在视图里可以打开页签的。

**Comment by mozhux** [comment]
> @mozhux 是的，在视图里可以打开页签的。

嗯，我的意思是侧栏打开也支持一下呢，就是那些笔记传统的样子，很多时候还是要对照着看，然后改视图的内容，右侧分屏啥的也行，就是步骤会多。

**Comment by 88250** [comment]
思源没有侧栏这种 UI 元素，打开页签就差不多了，后面看看反馈，实在需要的话加个分屏打开。

**Comment by 88250** [comment]
@mozhux 按住 Alt 在点击 打开 就是右分屏打开了

**Comment by hackerhui** [comment]
@88250 如果是不在database中的文档，也就是说把文档移入database呢，这种情况又如何展示

**Comment by 88250** [comment]
估计也得隐藏，你建议呢？



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 5, 2023 17:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Subdocuments created by the database are notdisplayed in the doc tree (Issue #9091)




 
@88250 如果是不在database中的文档，也就是说把文档移入database呢，这种情况又如何展示

**Comment by 88250** [comment]
考虑了下，非数据库内移入的情况不隐藏，只有直接在数据库中创建的文档隐藏。

**Comment by hackerhui** [comment]
> 考虑了下，非数据库内移入的情况不隐藏，只有直接在数据库中创建的文档隐藏。

设计成开关吧，是不是会好一些，也不用纠结了

**Comment by 88250** [comment]
加了开关容易导致混乱，还是确定一下规则好。

**Comment by 88250** [comment]
先这样吧，后面看反馈再考虑调整了。

**Comment by zxhd863943427** [comment]
数据库创建的文档要不还是专门放在笔记本根目录下的一个位置？不然文件太多可能会导致展开文档树卡死。

如果直接放在笔记本根目录下的一个位置，就可以在遍历的时候直接跳过了。

**Comment by 88250** [comment]
暂时不变设计了，遍历父文档时跳过应该问题不大，因为是分散的父文档。



---Original---
From: ***@***.***&gt;
Date: Wed, Sep 6, 2023 12:20 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Subdocuments created by the database are notdisplayed in the doc tree (Issue #9091)




 
数据库创建的文档要不还是专门放在笔记本根目录下的一个位置？不然文件太多可能会导致展开文档树卡死。
 
如果直接放在笔记本根目录下的一个位置，就可以在遍历的时候直接跳过了。

**Comment by zxhd863943427** [comment]
有一种做法就是把新建的文档都放到一个路径下，像这样：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/685e52d7-63fe-4f42-b3c7-672aaee4dcf2)

数据库创建的文档服从这个设置吗？服从的话就有问题了。

**Comment by 88250** [comment]
不服从，数据库中创建是作为子文档（隐藏的）。

**Comment by andyer1511** [comment]
现在有一个问题，把文档树的文档放入数据库后再把数据库删除，文档的数据库属性里会有信息残留。文档数据库属性只能修改，不能删除。如果再新建一个数据库把文档放进去，文档数据库属性栏又会出现第二个数据库的属性。这些无用信息不能删除的话会越积越多。

**Comment by 88250** [comment]
@andyer1511 嗯，这个目前是设计如此，以便在数据库中移出后又添加时能够保留之前的数据（类似 Notion）。移出后属性是否要自动（或者支持手动）隐藏还在考虑，初版暂时就不调整这个设计了，后面继续收集反馈，谢谢。

**Comment by zxhd863943427** [comment]
> @andyer1511 嗯，这个目前是设计如此，以便在数据库中移出后又添加时能够保留之前的数据（类似 Notion）。移出后属性是否要自动（或者支持手动）隐藏还在考虑，初版暂时就不调整这个设计了，后面继续收集反馈，谢谢。

实际情况是移出后重新移入，数据不会保存，而是会覆写。这是bug还是没做相关功能？

**Comment by 88250** [comment]
@zxhd863943427 是 bug，后面修复。

**Comment by andyer1511** [comment]
如果只是把文档移出数据库，数据库并没有删除，保留之前的数据，以便复用当然是合理的。
但是直接把原有数据库删除，再新建一个数据库把文档放入，填入的数据和之前完全一致，也是会在文档数据库栏加入一个新的数据库数据的。原有的数据库数据就变多余了，因为原有的数据库已经删除不能再调取出来。我认为这是两个需求。

- 数据库没删除，文档移出数据库，保留数据，以便复用。
- 数据库删除后，文档数据库栏允许删除原有数据库信息，以免造成无用数据堆积。

多进行几次数据库删除的操作，文档数据库栏会多出好几个数据库的信息，不管怎么隐藏，这些无用数据还是在的，因此单纯的隐藏并不能满足需求。希望可以在后续的改进版本中，在文档数据库栏下的每个数据库名称旁，加上删除按钮，以便删除多余的数据库信息。

**Comment by 88250** [comment]
@andyer1511 隐藏应该是必要的，删除的话暂时就不考虑了。

**Comment by 88250** [comment]
又考虑了下……

保留属性的话意味着数据肯定是冗余保存的，即使提供删除入口给用户好像也不怎么实用，因为手动删除太繁琐了。虽然保留属性的设计可能会有些用，但是实际上我们已经有数据历史和快照能够恢复文档数据，所以在数据恢复的场景下保留属性的设计意义就不大了。

更改设计为从数据库中移出块时不保留属性。

**Comment by zxhd863943427** [comment]
custom-avs似乎没有移除。

**Comment by 88250** [comment]
> custom-avs似乎没有移除。

感谢反馈，稍后改进。
