### ISSUE TITLE
移动快捷键无效

### ISSUE THREAD

**Issue by YuLv-o3o** [siyuan-note/siyuan#9094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

移动快捷键无效

演示视频：https://ld246.com/article/1693586975046

### Expected result

not have

### Version environment

```markdown
- Version: 2.10.2
- Operating System: macOS M1
```

### Log file

not have

**Comment by TCOTC** [comment]
在演示视频中不是有效的吗？
1. `“其他方式操作有效”块` 移入 `a文档` （光标在块上时按快捷键）
2. `c文档` 移到 `a文档` 下 （通过菜单移动）（也可以：光标放在 c 文档的标题上时按快捷键）

**Comment by 88250** [comment]
同上，我先关闭了，如果还有补充请随时跟帖，感谢反馈。
