### ISSUE TITLE
"Don't panic" window pops out too often when switching between siyuan and other apps (ios)

### ISSUE THREAD

**Issue by STMRabbit** [siyuan-note/siyuan#9097]
### In what scenarios do you need this feature?

When switch from background, it should do some check (try to connect backend/kernel firstly, if failed, then pop it out) instead of pop out an error window immediately.

### Describe the optimal solution

maybe at least add a delay before it pops out

### Other information

im not sure if it's caused by some deep reason by iOS or the init design of siyuan.

![IMG_0906](https://github.com/siyuan-note/siyuan/assets/112855065/2eb228f5-42d2-494f-95f9-2db2337dbf96)

![IMG_0907](https://github.com/siyuan-note/siyuan/assets/112855065/7703d5de-22d1-4e49-aa3f-e4e80467dd28)

**Comment by 88250** [comment]
Hello, in fact, we have automatically reconnected the kernel, but it takes a few seconds to start the kernel, thanks for the feedback.

**Comment by STMRabbit** [comment]
Thank you very much for replying! If I may ask, is it possible to use ``background fetch`` aka ``Background App Refresh`` of ios to reduce this happens? Thanks again :)

**Comment by 88250** [comment]
This may be a good solution, but we don't have time to study whether the background mode will have side effects on the golang kernel HTTP server. We need the help of developers who are good at iOS in the community.
