### ISSUE TITLE
是否有纯markdown 文本编辑模式？

### ISSUE THREAD

**Issue by heartacker** [siyuan-note/siyuan#9099]
### In what scenarios do you need this feature?

1. 很喜欢有类似vscode 的编写markdown的体验，不需要所见即所得那种，
2. 如需要所见即所得，可以左右分列编辑和预览
3. 程序员强需求

### Describe the optimal solution

添加一个模式，可以类似vscode 编辑

### Describe the candidate solution

一键切换为markdown 模式。

### Other information

恳求支持这种模式

**Comment by mozhux** [comment]
下载那个集成编辑插件就可以了

**Comment by heartacker** [comment]
> 下载那个集成编辑插件就可以了

希望有官方的支持和体验

**Comment by 88250** [comment]
这个不考虑了，思源的编辑器不是 Markdown 文本编辑器哦，只是支持 Markdown 语法输入，感谢提议。
