### ISSUE TITLE
仓库清理和仓库重置

### ISSUE THREAD

**Issue by HaujetZhao** [siyuan-note/siyuan#910]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

仓库中无用的文件过多，导致体积过大时

### 描述最优的解决方案 Describe the optimal solution

在资源管理页面提供仓库的清理功能，包括：

* 设置筛选条件（例如大小、拓展名、已从工作区删除），列出仓库中的文件，选中文件， 从仓库中彻底清理。将文件一键添加到忽略列表 `.gitignore` 
* 清除指定数量或指定时间以前的 commit ，并清理无用的仓库文件
* 一键重置仓库，将整个仓库删除重新 init
* 一键强制 push 到云端

**Comment by 88250** [comment]
感谢提议，后期考虑，谢谢。

**Comment by 88250** [comment]
还是外部通过手动操作吧，我关闭了。
