### ISSUE TITLE
Cancel the read-only mode message notification after startup

### ISSUE THREAD

**Issue by HopeLHP** [siyuan-note/siyuan#9100]
只读模式取消启动后弹窗提醒

### In what scenarios do you need this feature?

为了避免误操作改变文档内容，只读模式是我日常保持打开的模式。
但是只读模式启动后弹窗，让我没办法启动后立马点右上角的插件或按钮（包括退出只读），必须要点击打钩或者等它消失，如图
<img width="939" alt="image" src="https://github.com/siyuan-note/siyuan/assets/70339118/ad981597-6530-4a69-82cf-59f92743c604">

--- 

不清楚当初为什么要设置只读模式打开后弹窗提醒？
如果只是为了提醒人们目前在只读模式无法进行文档操作，那么右上角红色的退出只读按钮完全能做到提醒的作用，更持久更美观。
我相信大家都讨厌广告弹窗，之所以广告弹窗令人讨厌，我想就是它没有意义，现在只读模式的弹窗就像个狗皮膏药，每天打开siyuan都要撕一遍，非常影响整体感。

### Describe the optimal solution

取消弹窗提醒即可，如有必要加强“退出只读”按钮的面积或颜色

**Comment by 88250** [comment]
没有提示不行的，之前太多用户来问为什么无法编辑，不是这么多的反馈我们也不会画蛇添足的，感谢反馈。

**Comment by HopeLHP** [comment]
首先，我认为退出只读的按钮比强制弹窗提醒效果好。不知道当时右上角有没有退出只读的按钮，我认为红色的按钮已经能起到提示的作用了，如果他们还无法看到这个一直存在的且颜色鲜明的按钮，难道还能期望他们能注意到只在启动时才出现的弹窗吗？
其次，真的是因为启动的弹窗让他们立马知道还在只读模式吗？我每次发现想要编辑内容但无法编辑，都停顿一下，然后习惯性的想起或瞟到右上角的红色按钮，而不是因为启动时给我的那个弹窗。
再次，启动时的弹窗或许对第一次打开siyuan或刚开始使用的人有那么一点强制性提醒作用，但是要为此而在以后的每次都弹窗，我想这有点因噎废食。
最后，我不否认弹窗的强制提醒作用的效果，但我认为应该把这种弹窗用在例如同步失败、内核崩溃等等重要的有意义的场景上，而不是这种提示效果边际递减的场景。

**Comment by 88250** [comment]
默认主题不是红色的……而是这样的：

![image](https://github.com/siyuan-note/siyuan/assets/873584/d5f009d2-660a-4f93-a93b-ffdbadde67b6)

**Comment by HopeLHP** [comment]
> 默认主题不是红色的

所以我说我们可以用更好的办法解决用户忘记只读模式的问题，就比如写未主题的按钮就显得很自然不突兀，至少我认为强制弹窗不是一个好的解决办法。
只读模式刚发布时或许用户还不明白，但是人总是有记忆力的或者养成习惯的，所以现在大家提无法编辑的问题变少了，会不会只是因为习惯了，而不是这个强制提醒的弹窗。所以我说提示效果的边际递减的，但是他给别人造成的麻烦是一直存在或递增的。

**Comment by 88250** [comment]
也要考虑到新用户和整体设计，我们再考虑一段时间看看反馈吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月2日(周六) 晚上9:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 只读模式取消启动后弹窗提醒 (Issue #9100)




  
默认主题不是红色的
  
所以我说我们可以用更好的办法解决用户忘记只读模式的问题，就比如写未主题的按钮就显得很自然不突兀，至少我认为强制弹窗不是一个好的解决办法。
 只读模式刚发布时或许用户还不明白，但是人总是有记忆力的或者养成习惯的，所以现在大家提无法编辑的问题变少了，会不会只是因为习惯了，而不是这个强制提醒的弹窗。所以我说提示效果的边际递减的，但是他给别人造成的麻烦是一直存在或递增的。

**Comment by 88250** [comment]
在 https://github.com/siyuan-note/siyuan/issues/9145 和 https://github.com/siyuan-note/siyuan/issues/8417 中调整了只读模式设计，现在应该可以取消这个通知了。

**Comment by mozhux** [comment]
> 在 #9145 和 #8417 中调整了只读模式界面设计，加了较为明显的图标：
> 
> ![image](https://user-images.githubusercontent.com/873584/266767413-6d2325a5-6ed7-4a6e-85c6-cf2b7db692bd.png)
> 
> 现在可以取消这个通知了 #7700

图标换成原来顶栏全局的那个吧，眼睛和笔的，不然这个锁还以为是笔记加锁了呢

**Comment by 88250** [comment]
@mozhux 用锁图标好像较为通用，比如 Notion 和 IDE

**Comment by woniuxia** [comment]
D大，这个锁跟在文件名后面会不会效果更好一些。
或者在文件名的后面添加上[只读模式]，感觉会更明显些

**Comment by 88250** [comment]
我们考虑下，估计暂时就先这样。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 10, 2023 14:06 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Cancel the read-only mode messagenotification after startup (Issue #9100)




 
D大，这个锁跟在文件名后面会不会效果更好一些。
 或者在文件名的后面添加上[只读模式]，感觉会更明显些
