### ISSUE TITLE
Please enter the title of the bug report

### ISSUE THREAD

**Issue by johnnyqko0124** [siyuan-note/siyuan#9102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用#字鍵喚出標籤視窗後不等輸入又快速的消失了

### Expected result

修復

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/142400886/4af73166-5fd2-4831-98ae-a499b39d80a6

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/12508462/system-log.zip)

**Comment by 88250** [comment]
请使用原生主题并排除扩展（比如插件或者代码片段等）的影响后测试看看。

**Comment by johnnyqko0124** [comment]
謝謝D大，我關掉插件也使用原生主題，但狀況一樣存在，後來我按了重建索引就好了

**Comment by 88250** [comment]
好的，那先关闭了，如果后续频繁出现该问题请跟帖。
