### ISSUE TITLE
浏览器扩展提供 crx 文件下载

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9105]
### In what scenarios do you need this feature?

目前只提供了两个商店和源代码的下载
![1374612485fd8a88b987b6ba5767f7bf](https://github.com/siyuan-note/siyuan/assets/27268127/70f4f662-0c33-4169-a8ad-25ab5d04a067)

 群里面有个 360 浏览器的就无法使用两个商店，最后是在网上找到了 crx 文件安装的。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/ad0bec12-1d7d-44d9-89ae-83c851fabe2c)

### Describe the optimal solution

在 siyuan-chrome 里添加 realease ，提供 crx 文件下载

**Comment by 88250** [comment]
这个不提供了，还是商店安装吧。
