### ISSUE TITLE
Set Adaptive Width for individual documents

### ISSUE THREAD

**Issue by Shad0wpf** [siyuan-note/siyuan#9107]
独立设置笔记页面的只读模式和自适应宽度

### In what scenarios do you need this feature?

1. 笔记中部分页面需要随时编辑，还有部分平时基本不会做编辑的，现在的只读模式切换方式，会切换整个软件的状态，需要频繁切换。
2. 根据笔记内容的不同，有些适合自适应模式展示（如包含多列表格的），有些适合固定宽度展示，希望能增加独立设置自适应宽度的功能。

### Describe the optimal solution

每篇笔记页面增加记录只读模式和自适应宽度的参数信息，未设置时，使用系统默认方式，设置了只读或自适应宽度时，则使用笔记自身的参数状态。

**Comment by 88250** [comment]
独立设置只读模式请关注 https://github.com/siyuan-note/siyuan/issues/8417

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/4dbe83d1-44d9-4dcf-83bc-6ad2daa353b1)

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 开启全局 `自适应宽度` 后浮窗预览中编辑器的 `protyle-content` 元素未设置 `data-fullwidth="true"`

**Comment by Vanessa219** [comment]
我这里是有的，是有经过什么操作后不见了吗？检查一下这个是否为默认
<img width="348" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/69d7d036-79df-4615-b579-c579a875fb6a">

<img width="759" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/cfffb377-433d-4956-a05c-63dd1dbfefa5">

**Comment by Zuoqiu-Yingyi** [comment]
> 我这里是有的，是有经过什么操作后不见了吗？检查一下这个是否为默认 <img alt="image" width="348" src="https://user-images.githubusercontent.com/970828/268445008-69d7d036-79df-4615-b579-c579a875fb6a.png">

**悬浮窗口** 打开后即是 `默认`, 同时没有 `data-fullwidth` 属性
将文档自适应宽度从 `默认` 切换至 `启用` 后 `data-fullwidth` 属性才会被设置为 `true`, 再将其从 `启用` 切换至 `默认` 后 `data-fullwidth` 会被保留

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 经过我的测试, 在打开浮窗预览窗口时确实没有调用 `WYSIWYG.renderCustom` 方法
https://github.com/siyuan-note/siyuan/blob/5e21b218b600eeb3b6b9b689ef38f2978be35033/app/src/protyle/wysiwyg/index.ts#L110-L134

也没有调用 `editor.onSetEditor` 方法

https://github.com/siyuan-note/siyuan/blob/5e21b218b600eeb3b6b9b689ef38f2978be35033/app/src/config/editor.ts#L339-L361

而这两个地方是唯二设置 `data-fullwidth` 属性的位置

**Comment by Vanessa219** [comment]
浮窗没有弄，下个版本加上，这里就不新建 issue 了。
