### ISSUE TITLE
预览时无法显示图片

### ISSUE THREAD

**Issue by SylleoYr** [siyuan-note/siyuan#911]
### 描述问题 Describe the problem

插入图片时在编辑器中可查看，但开启预览状态（<Ctrl+E>）后无法显示图片。

### 期待的结果 Expected result

编辑状态和预览状态均正常显示图片。

### 截屏或录屏演示 Screenshot or screen recording presentation

**编辑：**
![editor](https://user-images.githubusercontent.com/23133978/103436188-d4bbb500-4c53-11eb-9917-f5260e53b670.png)

**预览：**
![preview](https://user-images.githubusercontent.com/23133978/103436191-dbe2c300-4c53-11eb-8266-8429d7b295c8.png)

### 版本环境 Version environment

* 版本 Version：0.5.46
* 操作系统 Operating system：Windows 10 20H2 19042.630
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，请在完全卸载一次（kernel 进程退出）以后安装 v0.5.5 试试，谢谢。

**Comment by SylleoYr** [comment]
重新安装0.5.5版本之后仍然存在上述问题。

**Comment by 88250** [comment]
我这儿重现不了……我们正在对底层进行重构，请等下个版本发布以后再试试，谢谢。

**Comment by SylleoYr** [comment]
嗯嗯
