### ISSUE TITLE
闪卡间隔重复增加删除或者归档功能

### ISSUE THREAD

**Issue by aGolduck** [siyuan-note/siyuan#9114]
### In what scenarios do you need this feature?

复习闪卡时发现有些闪卡已经不需要了，直接跳过后面还会再出现，希望有选项直接归档或者从闪卡列表里删除。

### Describe the optimal solution

rt

**Comment by 88250** [comment]
你好，间隔重复界面不考虑添加管理功能了，感谢提议。
