### ISSUE TITLE
Enhance openWindow parameter judgment

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#9116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

因为直接传块id打开的话会加载很多东西，并且显示没必要显示的标题（直接取的文档id），然后看到openWindow里面有tab的参数所以想尝试一下。问题就在于这个要传进去的ITab从哪里获取，我试了一下用openTab的结果，这里我写的代码是这样的

![image](https://github.com/siyuan-note/siyuan/assets/63407442/d54775d2-77b9-4b0d-b703-1f80b3f744f3)

然后就出现了下面的报错：

![image](https://github.com/siyuan-note/siyuan/assets/63407442/061ec578-2533-4e22-8599-2db1f1048308)

然后我试了下自己手搓ITab：

![image](https://github.com/siyuan-note/siyuan/assets/63407442/bbda0b79-921e-49af-8793-b3662d83a4ae)

发现又报这个错

![image](https://github.com/siyuan-note/siyuan/assets/63407442/00ab9696-19a2-40cb-88dd-b94b48fa7ad3)

就真不懂这个咋用了

### Expected result

不管是手搓还是openTab总得有个方法吧，但是感觉也不是不让用那种，是不是有哪里没做对？

### Version environment

```markdown
- Version: 2.10.3
- Operating System: Windows
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
tab 目前的使用场景如下，具体实现为：
https://github.com/siyuan-note/siyuan/blob/336eaef0000e2ef63b06f9b91a2b280b906210b3/app/src/window/openNewWindow.ts ，主要是将 json 传递给 Electron 的主线程，然后再根据 json 内容新建页签。

<img width="403" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/8e3de756-6f86-4ca6-b1bd-560ddbd3d2ee">

**Comment by WingDr** [comment]
我知道了，这里确实是有个bug，还是这个错误提示

![image](https://github.com/siyuan-note/siyuan/assets/63407442/8081526e-c302-4f73-8e5f-472406fcd5bb)

看到它错误的源码在这里

![image](https://github.com/siyuan-note/siyuan/assets/63407442/76a9db62-6651-442b-aebc-54dbd7927cc0)

这里在ts里doc本身是可选参数，所以应该先判断n.doc是否存在。为了验证我在参数里加了这个

![image](https://github.com/siyuan-note/siyuan/assets/63407442/6c9c02ef-24a5-4bed-a5eb-06c204afe657)

就可以正常传入openTab的结果打开了

**Comment by Vanessa219** [comment]
好的，多谢。已修改。
