### ISSUE TITLE
First lunch kernel failed 首次启动笔记显示连接内核失效

### ISSUE THREAD

**Issue by zhengxinchang** [siyuan-note/siyuan#9118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

每次关闭思源笔记之后重新打开第一次就会失败显示内核获取服务端口失效，紧接着关闭报错窗口，重启就能打开。这个问题只在我单位配发的笔记本中能够重现，我自己的笔记本没有这个问题。

报错提示：

获取内核服务端口失败，请确保程序拥有网络权限并不受防火墙和杀毒软件阻止。

Failed to get kernel serve port, please make sure the program has network permissions and is not blocked by firewalls and antivirus software.

防火墙已经通过了 siyuan 的所有请求。

可以在最新版本的思源笔记2.10.2中复现，在之前至少三个小版本中也可以复现。

作者：zhengxc
链接：https://ld246.com/article/1689079194807
来源：链滴
协议：CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/

### Expected result

第一次正常打开思源笔记

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/16239108/0d85dce0-b8f3-4eac-a07a-2831cce5abc7)

### Version environment

```markdown
所用的系统是：

版本 Windows 11 专业版
版本 22H2
安装日期 ‎2023/‎7/‎10
操作系统版本 22621.1848
序列号 PF4BW5Y7
体验 Windows Feature Experience Pack 1000.22642.1000.0
```

### Log file

      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/09/05 10:37:10 runtime.go:74: kernel is booting:
    * ver [2.10.2]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [24460]
    * runtime mode [prod]
    * working directory [C:\Program Files\WindowsApps\89C2A984.SiYuan_2.10.2.0_x64__1qfd3tsw4ngc2\app\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\softwares\Siyuan_note\data_directory]
I 2023/09/05 10:37:10 conf.go:264: using Microsoft Store edition
I 2023/09/05 10:37:10 runtime.go:128: use network proxy [system]
I 2023/09/05 10:37:10 serve.go:119: kernel [pid=24460] http server [127.0.0.1:62829] is booting
I 2023/09/05 10:37:10 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=E:\softwares\Siyuan_note\data_directory\temp\pandoc\bin\pandoc.exe]
I 2023/09/05 10:37:10 conf.go:927: pandoc initialized, set pandoc bin to [E:\softwares\Siyuan_note\data_directory\temp\pandoc\bin\pandoc.exe]
I 2023/09/05 10:37:11 sync.go:140: sync before boot
I 2023/09/05 10:37:12 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
I 2023/09/05 10:37:13 repository.go:1139: boot get sync cloud files elapsed [1.42s]
I 2023/09/05 10:37:13 blocktree.go:448: read block tree [9.7 MB] to [E:\softwares\Siyuan_note\data_directory\temp\blocktree], elapsed [0.59s]
I 2023/09/05 10:37:13 conf.go:710: database size [80 MB], tree/block count [564/35214]
I 2023/09/05 10:37:13 working.go:154: kernel booted
I 2023/09/05 10:37:14 box.go:79: auto stat [trees=500, blocks=32862, dataSize=73 MB, assetsSize=58 MB]
I 2023/09/05 10:37:14 disk.go:33: disk usage [total=215 GB, used=44 GB, free=171 GB]
I 2023/09/05 10:37:14 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.46s], tree [count=64, size=1.2 MB]
W 2023/09/05 10:37:22 blocktree.go:502: save block tree [size=9.7 MB] to [E:\softwares\Siyuan_note\data_directory\temp\blocktree], elapsed [3.28s]
W 2023/09/05 10:38:13 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/09/05 10:38:28 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/09/05 10:38:43 process.go:76: active UI proc count [4]
W 2023/09/05 10:39:13 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/09/05 10:39:28 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/09/05 10:39:43 process.go:76: active UI proc count [4]
W 2023/09/05 10:40:13 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/09/05 10:40:29 process.go:72: no active UI proc, continue to check from all processes after 15s

**Comment by 88250** [comment]
估计和系统环境有关系，建议试下安装版，感谢反馈。

**Comment by zhengxinchang** [comment]
尝试过安装版了，仍旧为解决问题

**Comment by 88250** [comment]
如果其他电脑上无法重现的话大概率是这个系统环境的问题，这个就不好排查了，只能你自己尝试一下。

**Comment by zhengxinchang** [comment]
好的，我也多复现一下，我感觉是跟域账户有关系，如果有更详细的错误内容，会再更新到这里。
