### ISSUE TITLE
部分地方的遮挡错误

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

错误1：
使用悬浮停靠栏时，更多的菜单无法显示。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/1a390e62-c7d9-444c-9b81-a0c6c38264e3)
错误2：
间隔重复时，无法看见被遮挡的文档块菜单和更多。
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/6a35f901-39c7-409c-a09c-7e7e9cbcdac3)

### Expected result

显示正常

### Version environment

```markdown
- Version: 2.10.3
- Operating System: windows10
- Browser (if used):
```

### Log file

无需日志

**Comment by Vanessa219** [comment]
https://ld246.com/article/1693907895080
