### ISSUE TITLE
通过文件树新建文档，在其他文档中无法引用的问题

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#912]
### 描述问题 Describe the problem
复现步骤
要文档树中新建一个文档，例如1
再新建一个文档，例如2
在2中使用（（语法引用1，无法出现引用提示
通过文件树的同步按钮点击同步后可以正常引用
### 期待的结果 Expected result
希望修复该问题，任何入口新建文档都可以正常引用
### 版本环境 Version environment
* 版本 Version：0.5.5
* 操作系统 Operating system：Windows 10

**Comment by 88250** [comment]
感谢反馈，v0.5.6 修复。
