### ISSUE TITLE
从块不经拖动直接加入数据库

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9120]
### In what scenarios do you need this feature?

目前把块加入数据库需要经过创建块、打开数据库所在文档、分屏数据库所在文档、拖动块到数据库四个步骤，这未免有点漫长，而且频繁的鼠标操作感觉并不好，因此希望能直接在块所在位置把块加入数据库。

### Describe the optimal solution

1. 使用一个类似于[[的符号输入如<<来选择数据库并加入。具体什么符号可以在ld中进行讨论。
2. 使用块标菜单来挑选并加入数据库。
3. 使用/菜单来挑选并加入数据库。

我个人是最喜欢第一种方案，但是对于非段落、标题块不是太友好，思源其实使用块标菜单最好，但是还是需要使用鼠标，不是很顺手。

**Comment by 88250** [comment]
第一种现在已经支持了，添加的时候可以搜索的，不过是从数据库这侧搜索。你说的应该是从块这一侧搜索，这个还要考虑一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 中午12:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 从块不经拖动直接加入数据库 (Issue #9120)




 
In what scenarios do you need this feature?
 
目前把块加入数据库需要经过创建块、打开数据库所在文档、分屏数据库所在文档、拖动块到数据库四个步骤，这未免有点漫长，而且频繁的鼠标操作感觉并不好，因此希望能直接在块所在位置把块加入数据库。
 
Describe the optimal solution
  
使用一个类似于[[的符号输入如<<来选择数据库并加入。具体什么符号可以在ld中进行讨论。
 
使用块标菜单来挑选并加入数据库。
 
使用/菜单来挑选并加入数据库。
  
我个人是最喜欢第一种方案，但是对于非段落、标题块不是太友好，思源其实使用块标菜单最好，但是还是需要使用鼠标，不是很顺手。
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by zxhd863943427** [comment]
我想了下，还是使用第二种比较好，文档块也是重要的一种块，而它只能使用这种方案添加。

**Comment by 88250** [comment]
直接在数据库中创建也是需要的，所以暂时就这样吧，后面再继续收集反馈，谢谢。

**Comment by zxhd863943427** [comment]
> 直接在数据库中创建也是需要的，所以暂时就这样吧，后面再继续收集反馈，谢谢。

我同样这么认为，这个issue的意思是额外添加一种添加到数据库的方法，而不是替换掉原来的。

**Comment by zxhd863943427** [comment]
这个功能我觉得还是必要的，可以先保留，没必要关闭。

**Comment by 88250** [comment]
以后要实现的时候再重开吧。
