### ISSUE TITLE
2.10.3 打开显示内核未知原因退出

### ISSUE THREAD

**Issue by choyy** [siyuan-note/siyuan#9121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

2.10.3 dev2、2.10.3 dev3、2.10.3 版本均有这个问题
2.10.3 dev1、2.10.2无问题
电脑无杀毒软件，目前在链滴、QQ群各有 1 位用户有同样的问题
[更新到 2.10.3 打开显示内核未知原因退出 - 链滴](https://ld246.com/article/1693891714190)
![图片](https://github.com/siyuan-note/siyuan/assets/68107073/e551ff35-02bc-468c-a407-30ac152e0a3d)

### Expected result

正常启动

### Version environment

```markdown
- Version: 2.10.3
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12533476/siyuan.log)

**Comment by 88250** [comment]
请在启动后观察一下 SiYuan-Kernel 的内存占用情况。

**Comment by choyy** [comment]
30MB，50MB这样

**Comment by 88250** [comment]
方便的话请把工作空间 data 文件夹打包发我测试看看 845765@qq.com 谢谢

**Comment by choyy** [comment]
我用的新工作空间，仍然是这个问题

**Comment by choyy** [comment]
右侧是2.10.3dev1版，左侧是2.10.3版

https://github.com/siyuan-note/siyuan/assets/68107073/218009eb-1366-4926-b867-cb538a012f33

**Comment by 88250** [comment]
我重新打包一个开发版的内核麻烦帮忙测试看看，请发邮件给我 845765@qq.com

**Comment by 88250** [comment]
这样吧，稍后我们发布一个 dev 版，麻烦下载测试看看。

**Comment by choyy** [comment]
siyuan-v202309061722-win.exe  这个吗

**Comment by 88250** [comment]
是的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上6:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 2.10.3 打开显示内核未知原因退出 (Issue #9121)




 
siyuan-v202309061722-win.exe  这个吗

**Comment by choyy** [comment]
依然有问题

**Comment by 88250** [comment]
麻烦再上传一下内核日志，谢谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 晚上7:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 2.10.3 打开显示内核未知原因退出 (Issue #9121)




 
依然有问题

**Comment by choyy** [comment]
[siyuan.log](https://github.com/siyuan-note/siyuan/files/12536768/siyuan.log)
似乎还是一样

**Comment by 88250** [comment]
好的，我们再看看其他原因。

**Comment by choyy** [comment]
有个群友有相同问题，他是输入锁屏密码后才内核退出

**Comment by 88250** [comment]
估计还是需要 data 数据才能定位到问题。

**Comment by choyy** [comment]
> 右侧是2.10.3dev1版，左侧是2.10.3版
> _51Record.mp4

我这里是新工作空间，需要这个吗

**Comment by 88250** [comment]
需要的，打包发我一下 845765@qq.com

**Comment by choyy** [comment]
已发送

**Comment by 88250** [comment]
以前确认问题，在 https://github.com/siyuan-note/siyuan/issues/9131 中解决，谢谢。
