### ISSUE TITLE
Add scrolling to float layer by `addFloatLayer`

### ISSUE THREAD

**Issue by suka233** [siyuan-note/siyuan#9123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

插件的api: addFloatLayer，创建的悬浮窗口，目前发现有如下两个问题：
1.如果悬浮窗口内的内容过长，无法展示纵向的滚动条，导致内容看不完全
2.如果手动调整悬浮窗口的大小，那么悬浮窗口会自动将高度铺满内容区，并且无法上下移动，只能左右移动
以上两个bug在如下gif动图可以看出来：
![floatBug](https://github.com/siyuan-note/siyuan/assets/43712875/32b37bc6-7f4b-478b-8e67-0395e9ba09ff)

### Expected result

1.希望通过addFloatLayer创建出来的悬浮窗口可以像普通的块引用悬浮预览窗口一样，可以任意拖动，并且有纵向滚动条
2.还想请问一下，addFloatLayer的这两个参数是啥意思
![image](https://github.com/siyuan-note/siyuan/assets/43712875/58056bd9-27ed-49e9-8ec6-6bb0951f7d44)

### Version environment

```markdown
- Version: v2.10.3
- Operating System: windows11
- Browser (if used):
```

### Log file

暂无

**Comment by zxhd863943427** [comment]
targetElement是用来定位的，大概就是填了啥，浮窗就会到那个位置。
defIds我也不理解干啥用。
其实在protyle出来后，还是自己写浮窗装protyle更能自定义一点。

**Comment by Vanessa219** [comment]
defIds 传入后会红框文字会高亮
<img width="972" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/20135b8e-45f5-4aa6-8bb2-2ea571aed251">
