### ISSUE TITLE
【样式】换行逻辑不统一

### ISSUE THREAD

**Issue by HarryHuaa** [siyuan-note/siyuan#9125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

样式中的“段落”在换行时通过回车，光标会跳出样式。只能通过shift+enter进行换行。
当光标在一行的末尾执行shift+enter时，可正常换行，但当光标在一行的开头执行shift+enter时会将该行上门的“段落”移出样式，两者的逻辑未统一。

### Expected result

1. 将两者的换行逻辑统一，即在行首处执行shift+enter也将执行换行
2. 最好的方案是可以使样式包含多个段落块，即执行enter后不会跳出样式而是在样式内增加一个段落块。执行shift+enter跳出样式。

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/11732858/3ffe97ee-dff6-446f-afe8-0f437cb40da4)
光标位于2前时执行shift+enter

### Version environment

```markdown
- Version: 2.10.3
- Operating System: Win 11
- Browser (if used):
```

### Log file

无报错

**Comment by 88250** [comment]
样式包含多个段落的话得使用容器块（比如超级块）。

段落开头 Shift+Enter 是为了拆分块，因为存在一种情况：

![image](https://github.com/siyuan-note/siyuan/assets/873584/41e38351-f2a1-47c0-bf27-a288b28cce7d)

在这个位置 Shift+Enter 必须拆分为两个段落：

![image](https://github.com/siyuan-note/siyuan/assets/873584/27b2bd4b-32f4-4ee5-9cf6-b17f62621dce)

该情况可忽略 foo 文本（将 foo 视作空），如果不拆分的话会导致同一个段落中出现多个空行从而存在语法二义性。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
