### ISSUE TITLE
The image file name is too long and truncated abnormally

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#9129]
将长文件名图片插入思源笔记出错

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，将文件名为“this is a test，1，这是一个测试，2，this is a test，3，这是一个测试，4，this is a test，5，这是一个测试，6，this is a test，7，这是一个测试，8，this is a test，9，这是一个测试，10，this is a test，11，这是一个测试，12.png”的图片复制到思源笔记或直接拖动到思源笔记时，不能正确将图片插入。

### Expected result

允许长文件名图片插入思源笔记

### Version environment

```markdown
- Version: 2.10.3
- Operating System: win10
- Browser (if used):
```

### Log file

1

**Comment by WingDr** [comment]
有没有可能是因为Windows的路径长度限制？参考[这个](https://learn.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation?tabs=registry)

**Comment by 88250** [comment]
长文件名的截断处理有问题，感谢反馈。

REF: https://github.com/siyuan-note/siyuan/issues/7099

**Comment by pisceswb** [comment]
@请问D大，能够保留原长文件名，而不将其截断吗？
使用场景为：①使用quicker截图PDF，以路径+标题命名截图文件。②将截图复制到思源笔记中。③因为图片文件名中含有完整路径和PDF文件名，经过对路径简单处理后即可找到并打开原PDF文件。
因此，需要完整的图片名称，而不要将其截断，只取部分内容。
谢谢！

**Comment by 88250** [comment]
保留不了，你看下那个关联的 issue，操作系统有限制。



---Original---
From: ***@***.***&gt;
Date: Thu, Sep 7, 2023 21:50 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] The image file name is too long andtruncated abnormally (Issue #9129)




 
@请问D大，能够保留原长文件名，而不将其截断吗？
 使用场景为：①使用quicker截图PDF，以路径+标题命名截图文件。②将截图复制到思源笔记中。③因为图片文件名中含有完整路径和PDF文件名，经过对路径简单处理后即可找到并打开原PDF文件。
 因此，需要完整的图片名称，而不要将其截断，只取部分内容。
 谢谢！

**Comment by pisceswb** [comment]
图片文件使用长文件名时，OCR不能作用于该图片，请问能解决吗？

**Comment by 88250** [comment]
打包这个图片文件发一下我测试看看。



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 8, 2023 07:48 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] The image file name is too long andtruncated abnormally (Issue #9129)




 
图片文件使用长文件名时，OCR不能作用于该图片，请问能解决吗？

**Comment by pisceswb** [comment]
> 

谢谢D大，已解决问题。在使用html格式将图片写入剪切板时，将图片文件名缩短，只使图片标题过长，不影响OCR

**Comment by pisceswb** [comment]
建议将长文件名图片复制进思源笔记时，只将图片文件名截断到合适长度，而保留图片标题为原文件名

**Comment by 88250** [comment]
这个尝试过，还搞不定。
