### ISSUE TITLE
文档的批量操作功能

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#913]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
整理文档和迁移时
### 描述最优的解决方案 Describe the optimal solution
在文件树中批量选中文档操作移动、删除、复制、剪切、黏贴等操作
允许直接批量将现有的MD文档导入现有库中
### 描述候选解决方案 Describe the candidate solution
单独的文件管理器

**Comment by 88250** [comment]
你好，文件树上的批量操作暂时不引入，后期考虑。

批量导入请看帮助文档，谢谢。
