### ISSUE TITLE
Revert Improve block loading performance on Windows/Linux/macOS amd64 arch

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9131]
https://github.com/siyuan-note/siyuan/issues/9121

Revert https://github.com/siyuan-note/siyuan/issues/9084

github.com/bytedance/sonic is not available on some old amd64 CPU (Intel(R) Pentium(R) Gold G5400 CPU @ 370GHz)

**Comment by aptexd** [comment]
仅好奇，是这些低端CPU缺少指令集么

**Comment by 88250** [comment]
有可能吧。



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 8, 2023 12:14 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Revert Improve block loading performance onWindows/Linux/macOS amd64 arch (Issue #9131)




 
仅好奇，是这些低端CPU缺少指令集么
