### ISSUE TITLE
有没有一个用户系统, 控制不同用户的读写权限

### ISSUE THREAD

**Issue by rusuvchao** [siyuan-note/siyuan#9132]
### In what scenarios do you need this feature?

有没有一个用户系统, 控制不同用户的读写权限
最好不同空间有不同的权限设置
增加一个本地用户注册接口

### Describe the optimal solution

官方

**Comment by 88250** [comment]
你好，思源笔记目前主要面向个人使用，所以这个需求不在设计考虑以内，谢谢。
