### ISSUE TITLE
复制名称为"PDF模板.pdf"的文件到思源笔记中，会出错

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#9138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，复制名称为"PDF模板.pdf"的文件到思源笔记中，会出错。

### Expected result

望修复

### Version environment

```markdown
- Version: 2.10.3
- Operating System: 
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
具体是什么报错？

**Comment by pisceswb** [comment]
D大您好，修正一下问题：
PDF文件名称为“1.pdf”，将其复制到思源笔记，正常。
Windows文件夹中修改“1.pdf”为“2.pdf”，或将其移动到其它文件夹中，再将其复制到思源笔记中，其仍会关联到1.pdf对应的assets文件夹的文件中。
请问这是一个特性还是bug？

**Comment by 88250** [comment]
这是特性，为了避免文件重复。只有内容改动的情况下才会真正的重新上传插入新文件，否则就复用已有文件。

**Comment by 88250** [comment]
我先关闭了，谢谢。

**Comment by pisceswb** [comment]
清楚了，谢谢

**Comment by pisceswb** [comment]
抱歉，还有一个问题，我复制1.pdf到思源笔记中，显示的名称是1.pdf.pdf。后缀重复了

**Comment by 88250** [comment]
等 v2.10.4 发布后再试试。
