### ISSUE TITLE
🎨 关于显示的小问题

### ISSUE THREAD

**Issue by xtfsoc** [siyuan-note/siyuan#9139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在使用 emoji 后, 文字不能左对齐. 详情看附件截图箭头处. 

怀疑是 Windows 10 的 emoji 引起的, 因为在老版本思源的选项中可以选择系统 emoji 还是软件自带的 emoji, 选择后者时, 不会有这种情况. 
但是最新版本貌似取消了 emoji 切换按钮, 有任何可能解决的办法吗 ? 因为对强迫症不是很友好. 

谢谢作者的作品.

### Expected result

期待可以正常的对齐

### Screenshot or screen recording presentation

![xtfs](https://github.com/siyuan-note/siyuan/assets/25444996/3284bd44-fb8e-45cc-bf37-b3a305e3cdf5)

### Version environment

```markdown
- Version: Docker 2.10.1
- Operating System: Windows 10 的浏览器使用 Docker 版本的思源
- Browser (if used): Edge, Chrome
```

### Log file

--

**Comment by 88250** [comment]
这个估计没有办法，Emoji 字体大小不一致，可以试试安装最新的 Emoji 字体或者集市里面有 Emoji 插件，感谢反馈。
