### ISSUE TITLE
内容块字数统计

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#914]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
专注写作时使用，关注每个段落的文档字数
### 描述最优的解决方案 Describe the optimal solution
目前在工具栏上是有字数显示的，但显示的是全文的字数
希望能够显示全文字数的同时，同时显示当前选中的字数
至于展示的方式，可以是按钮触发弹出对话框，也可以是右下角或者目前的方式

**Comment by 88250** [comment]
感谢建议，后面尝试，谢谢。

**Comment by 88250** [comment]
v1.2.0 调整到文档导航 - 更多中了，谢谢。
