### ISSUE TITLE
是否考虑直接建立内容块？

### ISSUE THREAD

**Issue by asasn** [siyuan-note/siyuan#9143]
如题，现在的笔记组织形式，似乎是：笔记=>文档=>内容块

但又据说

>在思源中，唯一重要的核心概念是内容块。通过排版格式即可形成内容块，这样我们就能在块级粒度上对思绪和知识进行整理，同时也能方便长文阅读和输出。

个人认为，建立文档，再以文档为容器创建内容块的逻辑，是很别扭的，粒度的不统一（又或许在作者看来，只是名称上的不统一，实际上文档也是内容块？），容易在日常使用的时候带来一些额外的心智负担，比如连接内容块时，实际上是连接了内容块所在的文档，在图谱当中表现也是如此，甚至反引用也是到文档级别。

如果可以统一粒度，把大部分工作放在内容块（相当于卡片盒笔记当中的闪念笔记的概念），或许会更好一些？

考虑把笔记当成工作区，把内容块当成卡片笔记来使用，把文档当成项目、容器……

当然，**也许有人会说，你建立一个文档，只在这个文档建立一个内容块不就行了？**

事实上我也是这样做的，但体验并不理想，不妨更进一步强化内容块的原子性，尤其是引用的时候，排除其他无关元素的干扰（比如说，文档）

**Comment by 88250** [comment]
> 又或许在作者看来，只是名称上的不统一，实际上文档也是内容块？

是的，文档也是内容块，建议看下用户指南 内容块类型 章节，文档是一种容器块。引用可以选择链接到任何类型的内容块，设置 - 搜索 中可以过滤类型。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by asasn** [comment]
> > 又或许在作者看来，只是名称上的不统一，实际上文档也是内容块？
> 
> 是的，文档也是内容块，建议看下用户指南 内容块类型 章节，文档是一种容器块。引用可以选择链接到任何类型的内容块，设置 - 搜索 中可以过滤类型。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

作者大大，我知道你是这样认为的，我就是对这一点提出异议啊！

>名者实之宾也，名称都不一样，怎么可能会是同一样事物呢？就算是同一事物，观察角度不同，也是横看成岭侧成峰，这和原子性、统一性是相违背的，无形之中就产生了多种变体，还有干扰的信息。

**抛开这个争议不论，或许可以通过屏蔽文档信息来得到实际的解决？**

目前我认为在文档当中储存内容块也是可以接受的，最大的麻烦就在于：

1. 引用的时候，会把“所在文档/容器”这个多余的信息也引用进去。
2. 块和块之间没有明显分割
3. 太多干扰信息，未能保持块的原子性

![image](https://github.com/siyuan-note/siyuan/assets/48091517/52e0428d-4704-4fd8-aa92-b1fd9a13c074)

![image](https://github.com/siyuan-note/siyuan/assets/48091517/a1631b6e-686b-4e43-a264-7307ff6d4e94)


**请问有设置可以屏蔽多余信息么？暂时没有在设置里面找到。** 🙏

设置=>搜索，的确可以过滤掉一些东西，但似乎无法屏蔽文档信息。它是针对“搜索”，而不是针对“展现”

**Comment by 88250** [comment]
没有这样的设置，文档块是最基础的容器块，其他块都是以此为基础。
