### ISSUE TITLE
Remove the global read-only mode toggle button on the top bar

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9145]
https://github.com/siyuan-note/siyuan/issues/8417 A single document read-only mode has been added. In order to maintain the consistency of functional design, the global read-only mode button needs to be removed from the top bar.

If you need to change the global read-only status, you can set it in Settings - Editor - Read-only mode, or use shortcut keys.

**Comment by 88250** [comment]
Fixed in 2659052bb92eaf71f1407343cbf53835ce935d9b

**Comment by 88250** [comment]
全局也放的话状态会有冲突，比如全局是只读，而文档是允许编辑，此时全局这个按钮是应该显示只读还是编辑呢？这样会给用户造成困扰。要调整全局只读模式的话建议用快捷键。

**Comment by 88250** [comment]
逻辑没有问题，我指的是界面元素的展现。

**Comment by 88250** [comment]
全局只读时，全局按钮图标到底是显示编辑还是只读？

**Comment by 88250** [comment]
@tcmtom 总的只读只能设置里面调整，单篇的面包屑有按钮，对手机端使用影响不大。

**Comment by chenshinshi** [comment]
想提个有关“默认”用词的问题：现在的只读模式默认是预设/默认，用户选择了启用后，关闭会优先选禁用而不是默认，估计也不太理解默认是什么意思，也许改成跟随全局设置或者加个提示会好一些？

**Comment by chenshinshi** [comment]
全局按钮图标我觉得是表示全局只读和全局编辑，现在是面包屑上一个锁，顶栏上的图标我觉得不会引起歧义，主要是更方便，由插件实现也担心思源卡顿。

**Comment by 88250** [comment]
暂时不改了，这个应该问题不大吧。



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 11, 2023 16:08 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Remove the global read-only mode togglebutton on the top bar (Issue #9145)




 
想提个有关“默认”用词的问题：现在的只读模式默认是预设/默认，用户选择了启用后，关闭会优先选禁用而不是默认，估计也不太理解默认是什么意思，也许改成跟随全局设置或者加个提示会好一些？

**Comment by 88250** [comment]
插件实现的方案主要就是改变设置，应该不会卡的。



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 11, 2023 16:10 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Remove the global read-only mode togglebutton on the top bar (Issue #9145)




 
全局按钮图标我觉得是表示全局只读和全局编辑，现在是面包屑上一个锁，顶栏上的图标我觉得不会引起歧义，主要是更方便，由插件实现也担心思源卡顿。
