### ISSUE TITLE
Some improvements on Siyuan function

### ISSUE THREAD

**Issue by GitHubAmos** [siyuan-note/siyuan#9146]
### In what scenarios do you need this feature?

1. I think Siyuan needs a whiteboard feature like obsidian
2. Can pdf display content directly when referenced?

### Describe the optimal solution

1. pdf display content directly when referenced
2. whiteboard like obsidian

**Comment by 88250** [comment]
1. REF https://github.com/siyuan-note/siyuan/issues/2024
2. Implementation of this function is not considered for the time being, please look forward to the community plugin implementation

Thanks.
