### ISSUE TITLE
客户端登陆时验证码失效

### ISSUE THREAD

**Issue by xian54966** [siyuan-note/siyuan#915]
客户端多次密码错误出现验证码，验证码不能正确验证，多次输入都提示“验证码错误”，无法正常使用

**Comment by 88250** [comment]
你好，验证码请用小写试试，如果还是不行请到链滴上重置密码后再试，谢谢。

**Comment by xian54966** [comment]
当时，第一次出现验证码的时候，输入验证码之后，提示验证码错误，点击图片，重新出现新的验证码，输入仍然错误。同时，验证码图片自动换回第一次出现的验证码。之后，不管怎么样点击图片，总会回到第一次出现的验证码图片发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2021年1月1日周五 21:16收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： xian54966 <xian54966_1@126.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 客户端登陆时验证码失效 (#915)

你好，验证码请用小写试试，如果还是不行请到链滴上重置密码后再试，谢谢。

**Comment by 88250** [comment]
你好，刚才我测试了一下，出现验证码以后输入小写的应该没问题，请再试试看，谢谢。

**Comment by xian54966** [comment]
我是说验证码图片会重复出现，这可能有些问题。您尝试每次都输入错误，然后可能会有验证码重复出现。并且输入错误并不会自动更新新的验证码。您试下，谢谢。发自我的华为手机-------- 原始邮件 --------发件人： D <notifications@github.com>日期： 2021年1月1日周五 22:03收件人： siyuan-note/siyuan <siyuan@noreply.github.com>抄送： xian54966 <xian54966_1@126.com>, Author <author@noreply.github.com>主    题： Re: [siyuan-note/siyuan] 客户端登陆时验证码失效 (#915)

你好，刚才我测试了一下，出现验证码以后输入小写的应该没问题，请再试试看，谢谢。

**Comment by 88250** [comment]
好的，感谢反馈，我们后面改进一下 ❤️
