### ISSUE TITLE
自动更新 doctree 文件顺序

### ISSUE THREAD

**Issue by sublimeclemency** [siyuan-note/siyuan#9150]
### In what scenarios do you need this feature?

所有的时候都需要

### Describe the optimal solution

将文件改名后, doctree 的文件顺序并不会刷新; 创建的新 subdoc 会在底部, 没有自动文件顺序刷新
拜托加上一个自动文件顺序刷新的功能, 谢谢!~

**Comment by 88250** [comment]
这个不会自动刷新，请手动重新展开，感谢反馈。
