### ISSUE TITLE
墨案 Air 6英寸电子书无法安装APK

### ISSUE THREAD

**Issue by yjps** [siyuan-note/siyuan#9154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

按官方参数显示为android12 四核A53处理器。安装包为2.10.3，无法安装。
![image](https://github.com/siyuan-note/siyuan/assets/32375607/1207757a-4b4f-41a9-92e5-3e8a09e68e23)

### Expected result

请适配电子书机型。

### Version environment

```markdown
- Version: 2.10.3
- Operating System: android12
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
可能是 CPU 类型不兼容，这个无法支持，抱歉抱歉。

**Comment by Temacc0531** [comment]
这个机型的系统是32位的所以无法安装
