### ISSUE TITLE
硬件时序图

### ISSUE THREAD

**Issue by xingrz** [siyuan-note/siyuan#9155]
### In what scenarios do you need this feature?

作为一个嵌入式开发者，有时候需要记录一些硬件时序。

虽然都叫「时序图」，但和思源目前支持的那种可以说完全不是一个东西。

![image](https://github.com/siyuan-note/siyuan/assets/288288/8460d9e4-775d-4bb0-9942-62b39bcd8990)

### Describe the optimal solution

说实话原本我也不知道有什么现成的时序图编辑器。以前我是手绘或者用 draw.io 手动画的，非常痛苦。

刚随便搜到一个可能可以用上的：https://github.com/wavedrom/wavedrom

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/2954 https://github.com/siyuan-note/siyuan/issues/7621

Thanks.
