### ISSUE TITLE
provide a right click menu for virtual citation to exclude current selected word

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9157]
### In what scenarios do you need this feature?

There are many documents named by common words, their virtual citation is meaningless. 

However, if I want to disable them, I need to look through all my documents, and then put those words into the excluded list. For now, the operation is not very convenient.

Using the including list is same non-convenient that looking through is neccessary.

### Describe the optimal solution

provicding a right click menu "exclulde from virtual citation", therefore, I can easily exclude the common word during my reading or writing process, instead of opening the setting windows and fulfill the exclude list, then back to continue reading or writing.

**Comment by 88250** [comment]
Hello, since virtual reference is an optional feature, we will not consider adding exclude/include key functions in the menu for the time being. Thanks for the suggestion.
