### ISSUE TITLE
关于大纲的自动缩进功能

### ISSUE THREAD

**Issue by o-ut-man** [siyuan-note/siyuan#916]
在文档中，用户并不会严格根据标题的大小逐级使用，比如只使用2、4、6。
在这种情况下，现在的大纲还会预留1、3、5的层级，导致大纲看起来比较别扭。

希望能增加自动缩进的功能，比如文档中都没有1级标题，那么就不留1级标题的层级位置。

<img width="149" alt="Snipaste_2021-01-01_22-03-52" src="https://user-images.githubusercontent.com/34265164/103440055-7d323f00-4c7d-11eb-9685-1330196b101a.png">

**Comment by 88250** [comment]
这个……算是特性吧，谢谢。
