### ISSUE TITLE
like an image block, a video block need a title, too

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#9160]
### In what scenarios do you need this feature?

Like an image block, it's very natural to has a title below for a video block, as the following image shows.
![image](https://github.com/siyuan-note/siyuan/assets/5683995/97874d06-8016-4760-86d0-06f6e6d8ebee)

I don't know why video block did not provide this feature, perhaps some technique issues. but for users, we really need it.

### Describe the optimal solution

provide this feature

**Comment by woniuxia** [comment]
想要 +1

**Comment by zhoutaosheng** [comment]
@88250 It seems like lots of people need this tiny feature, would you consider support it?

**Comment by 88250** [comment]
还是通过扩展解决吧，原生不考虑了，感谢反馈。
