### ISSUE TITLE
讲=将表格搜索的结果分开

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#9161]
### In what scenarios do you need this feature?

搜索

### Describe the optimal solution

当表格内容很大时，对某一关键词的搜索结果有无数个，但是只显示一条，应该可以选择拆开

### Other information

链接：https://pan.baidu.com/s/1kHr68EirxwUQW6RR9f5xbg?pwd=0000 
提取码：0000 
--来自百度网盘超级会员V3的分享

**Comment by 88250** [comment]
试下单击搜索结果，应该会跳转到下一个命中项。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月11日(周一) 晚上7:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 讲=将表格搜索的结果分开 (Issue #9161)




 
In what scenarios do you need this feature?
 
搜索
 
Describe the optimal solution
 
当表格内容很大时，对某一关键词的搜索结果有无数个，但是只显示一条，应该可以选择拆开
 
Describe the candidate solution
 
No response
 
Other information
 
链接：https://pan.baidu.com/s/1kHr68EirxwUQW6RR9f5xbg?pwd=0000
 提取码：0000
 --来自百度网盘超级会员V3的分享

**Comment by linglongyoudoufu** [comment]
> 

这个我知道，但是找内容不好找
---
其次文档内搜索也可以优化一下，弄成不需要弹出框那种，类似word查找

**Comment by 88250** [comment]
这个估计是改不了了，见谅。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月11日(周一) 晚上8:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 讲=将表格搜索的结果分开 (Issue #9161)




   
这个我知道，但是找内容不好找
 
其次文档内搜索也可以优化一下，弄成不需要弹出框那种，类似word查找
