### ISSUE TITLE
Click on an custom emoji to edit

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9164]
https://ld246.com/article/1694447058299

**Comment by suka233333** [comment]
emoji面板能用，但是不够好用，主要是想要自己添加一些icon的时候，操作就过于麻烦了，需要打开 **设置-外观-自定义表情** 然后在弹出的文件夹粘贴想要的icon。
所以希望能在emoji面板增加一个快捷上传icon的tab页，类似于notion的emoji面板：
![image](https://github.com/siyuan-note/siyuan/assets/115850846/5ea181a0-27b7-45b9-87f5-cab477a21765)
可以看到，notion支持图片链接和直接点击按钮上传文件。

思源除了实现以上俩功能外，完全可以再进一步，直接支持粘贴剪贴板中的图片作为icon，这样在用思源摘录网页的时候，直接复制网页的icon作为文章icon，会很方便。

**Comment by 88250** [comment]
@suka233333 https://github.com/siyuan-note/siyuan/issues/5897

**Comment by suka233333** [comment]
> @suka233333 #5897

那如果说在这个tab页内再加上一个title输入框呢，默认显示为 未命名（1），并自动选中。方便随手更改

**Comment by 88250** [comment]
@suka233333 这部分目前不考虑改变了，谢谢。

**Comment by suka233333** [comment]
> @suka233333 这部分目前不考虑改变了，谢谢。

:心碎emoji

**Comment by mozhux** [comment]
目前Z佬补了个插件可以了。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/654bf2a2-089c-4554-b0ae-e3a6abe75046)

**Comment by Achuan-2** [comment]
默认emoji不支持点击修改吗

**Comment by Vanessa219** [comment]
默认的是字符，不好接受点击识别。可能以后要和 notion 一样把 emoji 用标签包裹起来才行。
