### ISSUE TITLE
Hide dock icon

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9166]
https://ld246.com/article/1694410269029/comment/1694484740346#comments

**Comment by zxkmm** [comment]
这个已经插件实现了，应该可以close了？

**Comment by 88250** [comment]
暂时先不关闭，后续可能需要原生支持。

**Comment by zxkmm** [comment]
好的，谢谢老大。如果可以的话希望菜单项和顶栏按钮也原生支持一下隐藏，然后插件就可以下岗了。因为插件要每次DOM变化就遍历一遍然后style.display，性能有点差（虽然感觉出来）。

**Comment by 88250** [comment]
菜单项怕是不会考虑了。

**Comment by zxkmm** [comment]
好的，谢谢老大。那还是用插件好了。

**Comment by TCOTC** [comment]
我建议还是考虑一下隐藏菜单项（最好还能排序），大部分人都只用其中一部分：

![image](https://github.com/siyuan-note/siyuan/assets/78434827/8c145fe4-0529-4bb1-a0d4-2fc8ccdb1fab)

**Comment by 88250** [comment]
这个不考虑了，还是插件来搞吧。

**Comment by 88250** [comment]
不考虑了，插件实现 😂

**Comment by zxkmm** [comment]
菜单项这个虽然移除按钮插件实现了，但是有点麻烦，因为如果用domnodeinserted的话运行还算OK，因为他会阻塞，所以等思源判断弹出上下文菜单的位置的时候是按移除之后的长度来算的，所以没有发现问题。

但是domnodeinserted已经被web标准deprecated了，目前如果不想要控制台有warning的话，只能用mutationobserver,这个似乎是异步的，最后造成的结果就是如果用户隐藏的太多的话，菜单就会严重的飘往上。而且mutationobserver唤醒调用handler的次数太多了，所以性能有点堪忧。相比之下domnodeinserted基本上只有很少的场景会唤醒然后调用handler。

目前插件的最佳方案是凑活用domnodeinserted然后打印个消息提醒用户warning的由来。

css方案的话非常不优雅，不能按需隐藏分割线，只能全都隐藏或者全不隐藏，而且不能移除node所以导致键盘上下选择的时候会把被隐藏的item虚选中。

目前插件能实现的凑活用最佳方案还是domnodeinserted。如果有更好的也欢迎PR：https://github.com/zxkmm/siyuan_rmv_btn

**Comment by TCOTC** [comment]
> css方案的话非常不优雅，不能按需隐藏分割线

其实可以

**Comment by zxkmm** [comment]
> 其实可以


欢迎PR

**Comment by zxkmm** [comment]
> 给每条分割线都添加一个 data-id 属性

但是这样的话我插件这边加属性还是要监听器🫣，那当初为啥用css🫣

**Comment by TCOTC** [comment]
下个版本将支持通过 CSS 隐藏部分菜单选项，请关注 #12518 和 #12506
