### ISSUE TITLE
Replace fails when search results contain mixed case in text elements

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9171]
https://ld246.com/article/1694509288443

**Comment by TCOTC** [comment]
我刚刚测试了一下，将 `issue` 替换为 `123` ，使用 `全部替换` 和 `替换` 都无效

[test-O1dUnQ4.sy.zip](https://github.com/user-attachments/files/17056067/test-O1dUnQ4.sy.zip)

**Comment by 88250** [comment]
这个 issue 中仅处理文本节点的大小写不敏感替换。

**Comment by TCOTC** [comment]
同时包含大小写的情况下还是不能替换，这个 issue 改了什么来着？

**Comment by 88250** [comment]
这个改的是纯文本元素的大小写替换，你看下是否开启了忽略大小写搜索。

**Comment by TCOTC** [comment]
搜索区分大小写的话可以替换，不区分的话替换不了

[视频.webm](https://github.com/user-attachments/assets/d52aa177-1b3d-44f5-85ab-0cf7d0aee5ba)
