### ISSUE TITLE
当表头为空时无法删除第一行表格

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#9174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当表头为空时无法删除第一行表格

### Expected result

当表头为空时，可以删除第一行表格，此时第二行自动成为表头。

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/a32875fb-57c9-4da5-aa27-3a2dddbc09e8

### Version environment

```markdown
- Version: v2.10.5
- Operating System: win10
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
这个暂时不考虑改变了，感谢提议。

**Comment by 88250** [comment]
对了，可以在表头单元格右键菜单中试试这个：

![image](https://github.com/siyuan-note/siyuan/assets/873584/6ccd24d0-6009-4a41-bb20-7d49668eb60e)

**Comment by gdy106** [comment]
> 对了，可以在表头单元格右键菜单中试试这个：
> 
> ![image](https://user-images.githubusercontent.com/873584/267502312-6ccd24d0-6009-4a41-bb20-7d49668eb60e.png)

我现在也是用这个方法来顶一下。用快捷键也不复杂就是了。
