### ISSUE TITLE
内容ID变动时候提醒引用上下文，尤其是被删除时候

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#918]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

希望对内容进行删除或导致内容的ID变化时候提示被引用的状态
最好提示引用的上下文
让用户知道这个引用情况后再对内容删除或ID方面的变更做决定

### 描述最优的解决方案 Describe the optimal solution

比如IDEA 删除一个文件时候也会检查文件的引用情况
并提示用户，用户可能知道：哦，这个不能随便删
不然就会出现引用失效，但是内容又不在了，又不知道是什么被删了导致的，如下:
![image](https://user-images.githubusercontent.com/46141646/103448891-e85e2e80-4cda-11eb-9d69-ccc032304452.png)

而笔记的双链真正发展起来后，到处都是双链的id引用，这种情况必然就会遇到

### 其他信息 Other information

这也是双链的意义所在，内容不是孤立的，也许孤立起来看内容意义不大，但是联系起来意义就大了
有时候长期没碰一个被引用的内容，忘记它的联系了，被谁引用了，以为不重要了，就删了
所以希望能在删除或变动时候检查引用情况，最好是能提示引用上下文，然后用户再决定删不删

双链笔记提供了双链创建时候的便利
希望双链笔记也能提供双链变更时候的维护

**Comment by 88250** [comment]
感谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/585
