### ISSUE TITLE
PDF annotation supports pasting after selecting text

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9183]
pdf 标注能选中文字粘贴

### In what scenarios do you need this feature?

目前pdf 标注只能粘贴得到默认的锚文本，无法像超链接、块引一样，选中文字粘贴

### Describe the optimal solution

pdf 标注能选中文字粘贴

### Describe the candidate solution

none

**Comment by Vanessa219** [comment]
没太明白，是这个菜单加一个复制纯文本的功能？
<img width="295" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/1a71af8d-3197-4d4a-a43b-9b8c4c595576">

**Comment by 88250** [comment]
@Vanessa219 就是在选择文本上粘贴 PDF 标注，应该使用选择的文本作为锚文本。

**Comment by 88250** [comment]
楼主，我们这里测试是支持选择文本后粘贴 PDF 标注的，暂时先关闭了。

**Comment by Achuan-2** [comment]
哦，发现是矩形标注不支持，文字标注是可以粘贴的

**Comment by 88250** [comment]
收到，那应该正常。



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 18, 2023 15:25 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] PDF annotation supports pasting afterselecting text (Issue #9183)




 
哦，发现是矩形标注不支持，文字标注是可以粘贴的

**Comment by Vanessa219** [comment]
还是修改了一下。
