### ISSUE TITLE
在自动同步的情况下，本地更新的内容被云端覆盖

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/5831aa00-21e1-4634-b736-db67e4bc11ec)

如图所示，下面的内容为更新，在开启感知同步的自动同步中，更新的内容在编辑后丢失了。

设备为2台pc，一台安卓。这个问题可能是因为多台设备竞争同步导致的，感知同步的自动同步在目前可能还有较大缺陷。

### Expected result

不会发生错误覆盖的情况

### Version environment

```markdown
- Version: 2.10.5
- Operating System: win 10 android huawei
- Browser (if used):no
```

### Log file

```
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/09/14 14:13:08 runtime.go:74: kernel is booting:
    * ver [2.10.4]
    * arch [amd64]
    * os [Microsoft Windows 10 Pro]
    * pid [17776]
    * runtime mode [prod]
    * working directory [C:\Users\admin\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\admin\Documents\SiYuan]
I 2023/09/14 14:13:08 conf.go:362: OpenAI API enabled
    baseURL=https://oa.api2d.net/v1
    timeout=300s
    proxy=
    model=gpt-4
    maxTokens=1024
I 2023/09/14 14:13:08 conf.go:383: user has enabled [Automatically upload error messages and diagnostic data]
I 2023/09/14 14:13:08 runtime.go:128: use network proxy [system]
I 2023/09/14 14:13:08 serve.go:119: kernel [pid=17776] http server [0.0.0.0:2111] is booting
E 2023/09/14 14:13:08 package.go:335: parse theme.json [C:\Users\admin\Documents\SiYuan\conf\appearance\themes\pink-room\theme.json] failed: invalid character 'ï' looking for beginning of value
I 2023/09/14 14:13:09 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=C:\Users\admin\Documents\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/09/14 14:13:09 conf.go:927: pandoc initialized, set pandoc bin to [C:\Users\admin\Documents\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/09/14 14:13:09 sync.go:140: sync before boot
W 2023/09/14 14:13:25 repository.go:1486: index data repo before cloud sync elapsed [16199ms]
I 2023/09/14 14:13:26 repository.go:1139: boot get sync cloud files elapsed [17.52s]
I 2023/09/14 14:13:27 blocktree.go:448: read block tree [15 MB] to [C:\Users\admin\Documents\SiYuan\temp\blocktree], elapsed [0.81s]
I 2023/09/14 14:13:27 conf.go:710: database size [296 MB], tree/block count [1203/49012]
I 2023/09/14 14:13:27 working.go:154: kernel booted
I 2023/09/14 14:13:28 box.go:79: auto stat [trees=1203, blocks=49012, dataSize=544 MB, assetsSize=238 MB]
I 2023/09/14 14:13:28 disk.go:33: disk usage [total=511 GB, used=396 GB, free=116 GB]
I 2023/09/14 14:13:32 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=16, dfc=2, ucc=8, dcc=29, ub=302 kB, db=3.2 MB] in [5.57s], merge result [conflicts=0, upserts=34, removes=0]
I 2023/09/14 14:14:06 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=0, dcc=0, ub=199 kB, db=316 kB] in [3.09s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 14:17:09 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/true, ufc=7, dfc=2, ucc=1, dcc=0, ub=201 kB, db=316 kB] in [3.70s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 14:17:38 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.52s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 14:25:41 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [2.29s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 14:33:47 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=15, dfc=2, ucc=9, dcc=0, ub=576 kB, db=316 kB] in [5.14s], merge result [conflicts=0, upserts=0, removes=11]
I 2023/09/14 14:33:54 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=242 kB] in [1.59s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 14:49:59 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=316 kB] in [3.04s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 15:22:08 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=9, dfc=13, ucc=5, dcc=11, ub=281 kB, db=1.5 MB] in [6.07s], merge result [conflicts=0, upserts=11, removes=0]
I 2023/09/14 15:22:42 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=218 kB, db=316 kB] in [3.23s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 15:30:47 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=3, ucc=0, dcc=0, ub=199 kB, db=317 kB] in [4.41s], merge result [conflicts=0, upserts=1, removes=0]
I 2023/09/14 15:30:54 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.36s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 15:38:59 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=6, dfc=4, ucc=2, dcc=2, ub=208 kB, db=419 kB] in [4.79s], merge result [conflicts=0, upserts=2, removes=0]
I 2023/09/14 15:39:06 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.43s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 15:47:11 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=3, ucc=1, dcc=1, ub=202 kB, db=327 kB] in [4.36s], merge result [conflicts=0, upserts=1, removes=0]
I 2023/09/14 15:47:18 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.70s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 16:03:23 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=316 kB] in [3.31s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 16:13:29 box.go:79: auto stat [trees=1204, blocks=49079, dataSize=546 MB, assetsSize=240 MB]
I 2023/09/14 16:13:29 disk.go:33: disk usage [total=511 GB, used=396 GB, free=115 GB]
I 2023/09/14 16:35:31 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=10, dfc=11, ucc=6, dcc=8, ub=285 kB, db=908 kB] in [5.18s], merge result [conflicts=0, upserts=9, removes=0]
I 2023/09/14 16:36:05 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=0, dcc=0, ub=199 kB, db=317 kB] in [3.09s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 16:44:09 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [2.97s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 16:52:13 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [2.97s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 17:00:19 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [5.33s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 17:16:24 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [3.14s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 17:48:35 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=21, dfc=31, ucc=10, dcc=21, ub=293 kB, db=4.3 MB] in [8.08s], merge result [conflicts=0, upserts=29, removes=0]
I 2023/09/14 17:48:42 asset_content.go:868: convert [C:\Users\admin\Documents\SiYuan\data\assets\mtcas-20230914172252-0eo2f9a.pdf] PDF with [377] pages using [4] workers took [8.5343461s]
I 2023/09/14 17:48:42 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.66s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 17:48:50 asset_content.go:868: convert [C:\Users\admin\Documents\SiYuan\data\assets\mtcas-20230914172252-0eo2f9a.pdf] PDF with [377] pages using [4] workers took [8.3395932s]
I 2023/09/14 17:56:47 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=219 kB, db=318 kB] in [4.27s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:04:51 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=318 kB] in [2.81s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:12:55 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=318 kB] in [3.19s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:13:29 box.go:79: auto stat [trees=1205, blocks=49100, dataSize=550 MB, assetsSize=244 MB]
I 2023/09/14 18:13:29 disk.go:33: disk usage [total=511 GB, used=396 GB, free=116 GB]
I 2023/09/14 18:29:01 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=318 kB] in [3.62s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:33:25 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=202 kB, db=318 kB] in [3.60s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:35:14 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=6, dfc=2, ucc=2, dcc=0, ub=227 kB, db=318 kB] in [3.92s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:36:05 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=7, dfc=2, ucc=3, dcc=0, ub=234 kB, db=318 kB] in [5.03s], merge result [conflicts=0, upserts=1, removes=0]
I 2023/09/14 18:36:40 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=6, dfc=2, ucc=2, dcc=0, ub=250 kB, db=318 kB] in [5.20s], merge result [conflicts=0, upserts=1, removes=0]
I 2023/09/14 18:37:15 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=7, dfc=2, ucc=3, dcc=0, ub=283 kB, db=318 kB] in [5.03s], merge result [conflicts=0, upserts=0, removes=1]
I 2023/09/14 18:37:22 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.58s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:45:27 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=126 kB, db=318 kB] in [3.58s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/09/14 18:47:18 working.go:116: 
```

**Comment by 88250** [comment]
得看下被覆盖的文件更新时间，有一种情况是手动解压可能会导致文件更新时间延后。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月14日(周四) 晚上6:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 在自动同步的情况下，本地更新的内容被云端覆盖 (Issue #9185)




 
Is there an existing issue for this?
  
 I have searched the existing issues
  
Can the issue be reproduced with the default theme (daylight/midnight)?
  
 I was able to reproduce the issue with the default theme
  
Could the issue be due to extensions?
  
 I've ruled out the possibility that the extension is causing the problem.
  
Describe the problem
 

 
如图所示，下面的内容为更新，在开启感知同步的自动同步中，更新的内容在编辑后丢失了。
 
设备为2台pc，一台安卓。这个问题可能是因为多台设备竞争同步导致的，感知同步的自动同步在目前可能还有较大缺陷。
 
Expected result
 
不会发生错误覆盖的情况
 
Screenshot or screen recording presentation
 
No response
 
Version environment
 - Version: 2.10.5 - Operating System: win 10 android huawei - Browser (if used):no
 
Log file
       ___                                   ___           ___           ___      /  /\        ___           ___        /__/\         /  /\         /__/\     /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\    /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\   /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\  /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\  \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/   \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~    \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\      /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\      \__\/                                 \__\/         \__\/         \__\/ I 2023/09/14 14:13:08 runtime.go:74: kernel is booting:     * ver [2.10.4]     * arch [amd64]     * os [Microsoft Windows 10 Pro]     * pid [17776]     * runtime mode [prod]     * working directory [C:\Users\admin\AppData\Local\Programs\SiYuan\resources]     * read only [false]     * container [std]     * database [ver=20220501]     * workspace directory [C:\Users\admin\Documents\SiYuan] I 2023/09/14 14:13:08 conf.go:362: OpenAI API enabled     baseURL=https://oa.api2d.net/v1     timeout=300s     proxy=     model=gpt-4     maxTokens=1024 I 2023/09/14 14:13:08 conf.go:383: user has enabled [Automatically upload error messages and diagnostic data] I 2023/09/14 14:13:08 runtime.go:128: use network proxy [system] I 2023/09/14 14:13:08 serve.go:119: kernel [pid=17776] http server [0.0.0.0:2111] is booting E 2023/09/14 14:13:08 package.go:335: parse theme.json [C:\Users\admin\Documents\SiYuan\conf\appearance\themes\pink-room\theme.json] failed: invalid character 'ï' looking for beginning of value I 2023/09/14 14:13:09 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=C:\Users\admin\Documents\SiYuan\temp\pandoc\bin\pandoc.exe] I 2023/09/14 14:13:09 conf.go:927: pandoc initialized, set pandoc bin to [C:\Users\admin\Documents\SiYuan\temp\pandoc\bin\pandoc.exe] I 2023/09/14 14:13:09 sync.go:140: sync before boot W 2023/09/14 14:13:25 repository.go:1486: index data repo before cloud sync elapsed [16199ms] I 2023/09/14 14:13:26 repository.go:1139: boot get sync cloud files elapsed [17.52s] I 2023/09/14 14:13:27 blocktree.go:448: read block tree [15 MB] to [C:\Users\admin\Documents\SiYuan\temp\blocktree], elapsed [0.81s] I 2023/09/14 14:13:27 conf.go:710: database size [296 MB], tree/block count [1203/49012] I 2023/09/14 14:13:27 working.go:154: kernel booted I 2023/09/14 14:13:28 box.go:79: auto stat [trees=1203, blocks=49012, dataSize=544 MB, assetsSize=238 MB] I 2023/09/14 14:13:28 disk.go:33: disk usage [total=511 GB, used=396 GB, free=116 GB] I 2023/09/14 14:13:32 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=16, dfc=2, ucc=8, dcc=29, ub=302 kB, db=3.2 MB] in [5.57s], merge result [conflicts=0, upserts=34, removes=0] I 2023/09/14 14:14:06 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=0, dcc=0, ub=199 kB, db=316 kB] in [3.09s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 14:17:09 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/true, ufc=7, dfc=2, ucc=1, dcc=0, ub=201 kB, db=316 kB] in [3.70s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 14:17:38 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.52s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 14:25:41 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [2.29s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 14:33:47 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=15, dfc=2, ucc=9, dcc=0, ub=576 kB, db=316 kB] in [5.14s], merge result [conflicts=0, upserts=0, removes=11] I 2023/09/14 14:33:54 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=242 kB] in [1.59s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 14:49:59 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=316 kB] in [3.04s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 15:22:08 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=9, dfc=13, ucc=5, dcc=11, ub=281 kB, db=1.5 MB] in [6.07s], merge result [conflicts=0, upserts=11, removes=0] I 2023/09/14 15:22:42 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=218 kB, db=316 kB] in [3.23s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 15:30:47 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=3, ucc=0, dcc=0, ub=199 kB, db=317 kB] in [4.41s], merge result [conflicts=0, upserts=1, removes=0] I 2023/09/14 15:30:54 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.36s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 15:38:59 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=6, dfc=4, ucc=2, dcc=2, ub=208 kB, db=419 kB] in [4.79s], merge result [conflicts=0, upserts=2, removes=0] I 2023/09/14 15:39:06 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.43s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 15:47:11 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=3, ucc=1, dcc=1, ub=202 kB, db=327 kB] in [4.36s], merge result [conflicts=0, upserts=1, removes=0] I 2023/09/14 15:47:18 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.70s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 16:03:23 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=316 kB] in [3.31s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 16:13:29 box.go:79: auto stat [trees=1204, blocks=49079, dataSize=546 MB, assetsSize=240 MB] I 2023/09/14 16:13:29 disk.go:33: disk usage [total=511 GB, used=396 GB, free=115 GB] I 2023/09/14 16:35:31 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=10, dfc=11, ucc=6, dcc=8, ub=285 kB, db=908 kB] in [5.18s], merge result [conflicts=0, upserts=9, removes=0] I 2023/09/14 16:36:05 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=0, dcc=0, ub=199 kB, db=317 kB] in [3.09s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 16:44:09 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [2.97s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 16:52:13 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [2.97s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 17:00:19 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [5.33s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 17:16:24 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=317 kB] in [3.14s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 17:48:35 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=21, dfc=31, ucc=10, dcc=21, ub=293 kB, db=4.3 MB] in [8.08s], merge result [conflicts=0, upserts=29, removes=0] I 2023/09/14 17:48:42 asset_content.go:868: convert [C:\Users\admin\Documents\SiYuan\data\assets\mtcas-20230914172252-0eo2f9a.pdf] PDF with [377] pages using [4] workers took [8.5343461s] I 2023/09/14 17:48:42 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.66s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 17:48:50 asset_content.go:868: convert [C:\Users\admin\Documents\SiYuan\data\assets\mtcas-20230914172252-0eo2f9a.pdf] PDF with [377] pages using [4] workers took [8.3395932s] I 2023/09/14 17:56:47 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=219 kB, db=318 kB] in [4.27s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:04:51 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=318 kB] in [2.81s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:12:55 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=318 kB] in [3.19s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:13:29 box.go:79: auto stat [trees=1205, blocks=49100, dataSize=550 MB, assetsSize=244 MB] I 2023/09/14 18:13:29 disk.go:33: disk usage [total=511 GB, used=396 GB, free=116 GB] I 2023/09/14 18:29:01 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=125 kB, db=318 kB] in [3.62s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:33:25 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=5, dfc=2, ucc=1, dcc=0, ub=202 kB, db=318 kB] in [3.60s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:35:14 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=6, dfc=2, ucc=2, dcc=0, ub=227 kB, db=318 kB] in [3.92s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:36:05 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=7, dfc=2, ucc=3, dcc=0, ub=234 kB, db=318 kB] in [5.03s], merge result [conflicts=0, upserts=1, removes=0] I 2023/09/14 18:36:40 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=6, dfc=2, ucc=2, dcc=0, ub=250 kB, db=318 kB] in [5.20s], merge result [conflicts=0, upserts=1, removes=0] I 2023/09/14 18:37:15 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=7, dfc=2, ucc=3, dcc=0, ub=283 kB, db=318 kB] in [5.03s], merge result [conflicts=0, upserts=0, removes=1] I 2023/09/14 18:37:22 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=243 kB] in [1.58s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:45:27 repository.go:1253: synced data repo [kernel=wc4exw5, provider=0, mode=a/false, ufc=4, dfc=2, ucc=0, dcc=0, ub=126 kB, db=318 kB] in [3.58s], merge result [conflicts=0, upserts=0, removes=0] I 2023/09/14 18:47:18 working.go:116:   
More information
 
No response

**Comment by zxhd863943427** [comment]
额，这个该怎么查看？

**Comment by 88250** [comment]
文件系统上看下文件的更新时间。

**Comment by zxhd863943427** [comment]
这个是在快照里的，并不存在于文件系统中。

**Comment by 88250** [comment]
我指的是被覆盖的文件，看下这个文件的时间。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月15日(周五) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 在自动同步的情况下，本地更新的内容被云端覆盖 (Issue #9185)




 
这个是在快照里的，并不存在于文件系统中。

**Comment by 88250** [comment]
另外，帖子正文的日志没有看到启用了同步感知，请确认一下。

**Comment by 88250** [comment]
论坛上也有个类似问题 https://ld246.com/article/1694192059951 

暂时定位不到原因，下个版本加一些日志看看。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
