### ISSUE TITLE
建议ALT+Y全屏时，保留所有分屏页面

### ISSUE THREAD

**Issue by zhoutaosheng** [siyuan-note/siyuan#9187]
### In what scenarios do you need this feature?

这样做
1. 很多时候，全屏，就是因为当分左右屏显示的时候，左右两边的面板占据了空间，不方便。而如果，能左右分屏的页面都显示，会大大提高笔记效率
    不分屏，对于大多数显示器的长宽比，空间其实是够了的 
2. 另一方面，跟大多数编辑的习惯是一致的，会比较舒服
![image](https://github.com/siyuan-note/siyuan/assets/5683995/2ed8f434-5f7c-44a3-9af9-335d1cdb2fa2)

另外，全屏时，任务栏仍然在，这和大多数软件也不一致

### Describe the optimal solution

1. 全屏时，保留左右分屏
2. 全屏时，全屏区域覆盖任务栏

**Comment by 88250** [comment]
这个估计就不改了，全屏主要是为了聚焦到一个页签里的内容，去掉多余的干扰。

无法全屏到任务栏是目前看是技术限制，暂时也改不了。

感谢反馈。
