### ISSUE TITLE
pseudocode.js support

### ISSUE THREAD

**Issue by tcx4c70** [siyuan-note/siyuan#9188]
### In what scenarios do you need this feature?

希望能支持[pseudocode.js](https://github.com/SaswatPadhi/pseudocode.js)来渲染算法伪代码。比如，很多论文都提供了latex源码，在阅读这些论文并做笔记时，如果能够支持渲染latex中algorithm environment，则只需要复制粘贴论文源码就可以（或进行少量修改）。

### Describe the optimal solution

希望能支持[pseudocode.js](https://github.com/SaswatPadhi/pseudocode.js)来渲染算法伪代码

Joplin中通过[插件](https://github.com/SeptemberHX/joplin-plugin-enhancement/tree/master/src/driver/markdownItRenderer/pseudocode)实现了这个功能

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6142
