### ISSUE TITLE
表格功能加强

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#919]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
表格可以压缩大量的信息，目前不支持合并单元格等复杂的表格
### 描述最优的解决方案 Describe the optimal solution
引入HTML语法来支持复杂的表格
### 描述候选解决方案 Describe the candidate solution
第三方表格嵌入

**Comment by 88250** [comment]
HTML 嵌入目前应该已经支持，请在编辑器设置中打开 HTML 预览选项。

**Comment by 88250** [comment]
你好，我关闭了，如果还有建议请继续跟帖，谢谢。
