### ISSUE TITLE
导出保留双链色彩样式

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#9193]
### In what scenarios do you need this feature?

文档中双链会变紫色，导出时却没有样式，就算再手动添加其他样式也不生效

### Describe the optimal solution

希望导出时保留双链的样式（不管是色彩还是其他），确保**所见即得的导出效果**
导出主要是指图片以及 pdf，其他能做到也行

**Comment by 88250** [comment]
导出时引用会被转换为超链接，所以实际上是没有引用元素的。这个地方就不再改变了，谢谢。

**Comment by TinkMingKing** [comment]
只是想要导出来有文本样式就行，不需要其他效果，我就算把双链加粗，导出来还是普通文本字体，我想要导出满意的效果还得手动复制一篇文档，手动去掉双链，再手动添加样式，太麻烦了 @88250

**Comment by 88250** [comment]
估计是搞不定了，引用元素转换超链接是必要的。
