### ISSUE TITLE
Improve doc menu

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9195]
<img width="1098" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/7a29b42e-07dc-41df-bf72-8e969558aa13">

Doc:
* Add search
* Add replace
* Add show in folder
* Add file history
* Add Import
* Add Export
* Remove Transfer Reference

Doc more:
* Add Transfer Reference
* Remove export
* Remove delete

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 

`Transfer Reference` item should be consistent with other block menus, appears in the document block menu.

**Comment by Vanessa219** [comment]
> @Vanessa219
> 
> `Transfer Reference` item should be consistent with other block menus, appears in the document block menu.

好的，下个版本改进一下

**Comment by Vanessa219** [comment]
> 替换没必要显示出来，本来就是和搜索在一起的，只留一个搜索就行 @Vanessa219

好的，下个版本改进一下
