### ISSUE TITLE
Support ignore index

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9198]
为 SearchRefBlock 功能添加黑名单

### In what scenarios do you need this feature?

当我们键入 [[ 并输入锚文本的时候，就会给出一个长长的列表，允许用户在里面选择一个 Ref Block。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/9c9900b6-1f44-4a43-860d-0c30cf662c61)

但是有时有会有这种需求：某些文档我们已经很确信不打算把它作为一个引用的目标。所以希望允许用户设置让某些文档，或者某些路径下的文档不在 Search Ref Block 菜单当中显示。

### Describe the optimal solution

这个过滤功能甚至可以直接在前端完成，直接对 searchRefBlock API 的结果 Array 做一个 filter。

例如如果是不显示特定 Block，就根据 id 过滤掉对应的 block，如果是不显示特定文档树下的内容，就根据 path 过滤。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/b089b009-9975-4648-bb4e-d87da1a4ed85)

**Comment by 88250** [comment]
目前考虑有两个方案：

1. 使用块自定义属性 `custom-sy-search-exclude-ref=true` 来过滤
2. 添加配置文件 data/.siyuan/search.json，支持配置 pathPrefix 和 id

估计方案 2 更好一些（支持路径前缀），配置步骤也简单一些。两个方案都不考虑做界面了，考虑通过插件实现配置界面。

**Comment by 88250** [comment]
另外，之前也有收到不编入全局搜索索引的需求，比如某个路径（包含子文档）不想编入搜索索引，和这个需求有点类似，只不过一个是直接不编入索引，一个是搜索结果过滤。

如果用方案 2 的话可以在 search.json 中增加 noindex 配置项来忽略索引。

**Comment by frostime** [comment]
两个都可以。前者是块粒度的，后者是文档树粒度的。
不过总体来讲，后者确实更好一点，大部分情况下需要忽略也就是忽略到文档这个层次。

**Comment by 88250** [comment]
后者也支持 id 过滤，可以到块。再考虑一段时间，看看是否有更多需求。

**Comment by LoneFireBlossom** [comment]
双链笔记本来主打的就是互相连接吧，楼主的意思是会有已经「从链接毕业」的笔记，纯好奇能不能举个例子。
---
我随便想了一个。
我是小学生，学了加法，思源笔记里一堆链接到加法的。
后来上了初中，不需要再链接这么简单的内容了（明明我会还让我敲俩【【是做无用功），所以就不想让它显示了。
但是以后还是会学二进制里的加法之类加法衍生出来的东西，感觉还是有机会链接的。
---
再想了想，模板？

**Comment by HoollyFox** [comment]
支持，另外建议在搜索设置中设置黑名单，不和引用列表 共用 黑名单，因为有的内容不想搜索时看到，但是想引用时看到。 

这个需求挺大的，因为有很多在网上收集的文章，但是不想作为引用材料或者搜索材料，只想自己特定地块引用。

**Comment by TCOTC** [comment]
关联：https://ld246.com/article/1701076921619/comment/1701087045514#comments

**Comment by 88250** [comment]
> 支持，另外建议在搜索设置中设置黑名单，不和引用列表 共用 黑名单，因为有的内容不想搜索时看到，但是想引用时看到。
> 
> 这个需求挺大的，因为有很多在网上收集的文章，但是不想作为引用材料或者搜索材料，只想自己特定地块引用。

分开范围搜索的需求好像不多见，暂时就不考虑了，谢谢。

**Comment by 88250** [comment]
经过一段时间的考虑，方案如下：

* data/.siyuan/indexignore：用于忽略索引
* data/.siyuan/searchignore：用于忽略全局搜索
* data/.siyuan/refsearchignore：用于忽略引用搜索

~~这些 ignore 配置文件的语法和 syncignore 一致，即使用 gitignore 语法。~~
只有 indexignore 配置文件的语法和 syncignore 一致，即使用 gitignore 语法

**Comment by 88250** [comment]
搜索任务拆分到 https://github.com/siyuan-note/siyuan/issues/10089

**Comment by TinkMingKing** [comment]
请问三种忽略方式的区别是怎样的，忽略全局搜索、忽略引用搜索这两个还好，主要有点不太理解忽略索引

**Comment by 88250** [comment]
* 忽略索引：完全不会编入数据库索引
* 忽略搜索：编入数据库索引，但是搜索时过滤

**Comment by 88250** [comment]
会的。



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 15, 2024 23:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support ignore index (Issue #9198)




 
进入忽略索引的文件会被同步吗？
