### ISSUE TITLE
希望在软件的“图片单独显示”状态下提供图片放大的功能

### ISSUE THREAD

**Issue by AiProgram** [siyuan-note/siyuan#920]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
目前最新的版本支持：图片双击后占居屏幕焦点显示，类似于“查看大图功能”，但是我发现这种状态下并不能放大图片，而仅仅是凸出图片信息。所以希望在这种状态下加入图片放大的功能，不需要单独调整markdown普通状态下的图片大小，只需要在双击预览后提供放大功能。
![image](https://user-images.githubusercontent.com/13717071/103452215-d34bc480-4d07-11eb-94b3-cc2e57df962d.png)

**Comment by Vanessa219** [comment]
双击打开后就是原图哦。
![image](https://user-images.githubusercontent.com/970828/103594720-76812180-4f34-11eb-9375-ee67a50c414f.png)
