### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by passionate2023** [siyuan-note/siyuan#9200]
### In what scenarios do you need this feature?

Easy access

### Describe the optimal solution

1. Import menu to import txt files, docx files
2. Option to share the whole note for other users to view/search what we see in web application. basically the shared users should be able to view, search but should not have the privilege to edit/delete the notes of the entire notebook
3. type ahead with number of matches on typing and highlight text in search results in 1st level and second level navigation
4. navigation arrows to navigate the occurrences of the searched keyword in the notes when clicked via search result

**Comment by 88250** [comment]
Hello,

1. You can try the import plugin in the marketplace
2. Please use Docker deployment and use kernel read-only mode
3. Search is currently only available through global search, and notebook navigation does not support search
4. Highlighted results can be seen in the search preview area

Thanks.
