### ISSUE TITLE
PDF render engine is not so good

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9205]
### In what scenarios do you need this feature?

我使用自己购买的富士通扫描仪扫出来的PDF在思源里渲染速度很慢。多打开几个，刚开始几页还行，往下滚动几百页，得好一阵子才能渲染出来。
（我暂时还没有使用ABBYY进行OCR所以是纯图片的。不过想必应该差不多）

还有超长页面PDF也可以考虑优化一下（这种页面是用macOS Safari生成的，效果比chrome的打印要好很多）

我可以把PDF打包发送一下，应该发到哪里呢？QQ，云盘，GitHub，邮件？几百MB的

### Describe the optimal solution

感觉目前的PDF标注也就是堪堪可用的状态，希望能做得更好一点。在Apple平台上可以直接用Apple的PDF渲染引擎，MarginNote就是这么做的，高亮/画图等等批注是一个单独的图层（图层可以有多个），有没有PDF信息都还在，甚至可以把图册放到别的PDF上显示。
<img width="149" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/6e2be647-6238-499b-a14c-834a47bf3e24">

MN是从差不多20年的时候就引入Apple的PDF渲染引擎了，之前一直用自己开发的。我觉得Apple引擎用着没问题，只有极少、极少、极少数情况需要切换到MN引擎。MN已经默认用Apple引擎了。

至于windows安卓平台我就不清楚了

### Other information

思源最新版 macOS最新稳定版 MBP 16 Intel末代

用上Apple引擎对付这种PDF也不能秒加载。只能说会好很多

**Comment by 88250** [comment]
感谢提议，但是技术上估计是无法替换了，为了跨平台而使用了 pdf.js。
