### ISSUE TITLE
Recommended PDF highlight color 

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9206]
### In what scenarios do you need this feature?

感觉提供的几种PDF高亮的颜色不好看。

### Describe the optimal solution

直接抄Apple Preview里提供的PDF高亮颜色即可：

<img width="191" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/1e175d5f-fbeb-424f-93ee-48ec13de59ec">

- FC5C88
- 7CC868
- 69B0F2
- FACA5A
- C885DA

这是实际效果：
<img width="1281" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/2a5e2195-1b45-48cb-8abf-5714027d0b51">

另外再提供一个橙色FC6A08

再加个红色，灰色啥的就够了（*红色肯定得有，估计很多人想用这个颜色标错题重点之类的*），另外也可以去
https://chrome.google.com/webstore/detail/%E5%87%A0%E6%9E%9D/hfohpokminpknagcgncibpacohagppjn
打开这个插件之后的chrome首页选几个颜色，左下角的设置里都有色号
或者小红书搜搜，比如  
```
90 九宫格草莓发布了一篇小红书笔记，快来看吧！ 😆 IkpoVOTtFWdlCfK 😆 http://xhslink.com/Tq5zDu，复制本条信息，打开【小红书】App查看精彩内容！
```

### Other information

颜色还是尽早改得好看一点，避免以后背上太多历史包袱。

_No response_

**Comment by 88250** [comment]
@Vanessa219 是不是可以考虑使用和行级字体一样的颜色？

![image](https://github.com/siyuan-note/siyuan/assets/873584/09c40029-bfbc-4e2d-8903-f176375d01e3)

**Comment by LoneFireBlossom** [comment]
我没想到第三方主题也能改变PDF高亮的颜色。
所以开发者看情况选择吧

**Comment by Vanessa219** [comment]
这个应该是改过一遍的了，可以把黄绿蓝粉紫修改一下

<img width="448" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/f8a549ae-7400-4bdf-8c26-75c0676d0e70">

<img width="460" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/9a5fd281-924a-4831-ba17-58db1f04b501">
