### ISSUE TITLE
PDF text highlight can be overlaped

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9207]
### In what scenarios do you need this feature?

例如MarginNote就可以，希望思源也能实现这样。
<img width="495" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/dac330c8-59c7-45e3-8f30-13b028ef28d5">

### Describe the optimal solution

nothing

### Other information

并不是重要的内容，因为矩形标注可以重叠也够用了。
优先级并不高以后再做也行。如果不能做就不做了。

**Comment by 88250** [comment]
大概是不考虑了，感谢提议和理解。
