### ISSUE TITLE
在macOS&iPadOS上提供至少一种通用的打开「Settings」的方法

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9208]
### In what scenarios do you need this feature?

在macOS上的一个软件里打开「设置」界面，所有软件至少会提供下面三种中的一种：

- 把设置⚙️放在软件首页
- 使用快捷键`CMD+,`
- 在菜单栏-软件名称（SiYuan）里有按钮
- <img width="177" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/a65c6309-4349-4b08-8750-856904f33bfa">

我用过很多软件，思源真的是我（印象里）见到的头一个这三种方法都不提供的。
开发者大大，你能想象我在界面上翻来覆去找了10遍多都没找到设置⚙️在哪里的心情么，在我知道怎么打开设置后我确实可以自己改快捷键了，但这样弄，怎么推广……

### Describe the optimal solution

electron软件第三种就先不考虑了，前两种选一个呗。

Obsidian过了好久才实现macOS-like menubar的。
https://forum.obsidian.md/t/add-app-menus-to-the-macos-menu-bar/965/9

**Comment by LoneFireBlossom** [comment]
再顺带提一个，软件竟然把macOS系统级的CMD+H给覆盖了，这种操作我也是头一次见……

**Comment by 88250** [comment]
可能是为了跨平台的统一性吧。

**Comment by LoneFireBlossom** [comment]
但是Ob在macOS上就这两个快捷键没有被覆盖啊。
用户规模大了以后，我相信这两个快捷键的问题还是会被经常提及的。不懂代码，如果不统一导致每次打包更麻烦那就以后再改吧，但总之肯定是要面对的我认为

**Comment by 88250** [comment]
可能设计理念不一样吧，这个暂时就不改了，感谢反馈让我们知道这个问题，谢谢。
