### ISSUE TITLE
Backlink Button should be placed on top-right

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9209]
### In what scenarios do you need this feature?

在思源里反链面板比关系图明显更重要，为何要把关系图按钮放在右上，而反链面板放在相对不起眼的右下呢。

### Describe the optimal solution

「全局关系图」本来就没什么用，在思源里显示得还很丑，连截图装逼都不好看，不如直接把按钮隐藏起来得了。
虽然没什么用，但很多新人恐怕会把全局关系图是否好看作为选择的一个因素。所以干脆别让新手看到。
等以后哪天有空了把这个网弄得好看点再摆出来。

不过我不知道用思源的人有多少用局部关系图的。

**Comment by 88250** [comment]
或许是应该对调一下按钮位置，两个关系图按钮放在右下，反链按钮放在右上 @Vanessa219

**Comment by 88250** [comment]
暂时先不动了，等 https://github.com/siyuan-note/siyuan/issues/9166 做好以后考虑默认隐藏吧。
