### ISSUE TITLE
有序列表识别中文顿号（、）以及设置中的搜索无效

### ISSUE THREAD

**Issue by SylleoYr** [siyuan-note/siyuan#921]
### 描述问题 Describe the problem

1. 我想输入`2、3月份`，但是将顿号识别成了有序列表。
2. 点开设置，搜索设置项无效。

### 期待的结果 Expected result

1. 有序列表不识别顿号
2. 设置中的搜索给出关联结果

### 截屏或录屏演示 Screenshot or screen recording presentation

![insert_pic](https://user-images.githubusercontent.com/23133978/103453609-a226c080-4d16-11eb-802b-88c08496ed16.gif)

### 版本环境 Version environment

* 版本 Version：0.5.5
* 操作系统 Operating system：Windows 10 20H2 19042.630
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
1. 输入侧的“优化”确实不太好，这应该是输入法干的事情
2. 稍后检查修复

感谢反馈！

**Comment by 88250** [comment]
你好，两个问题在 v0.5.6 中修复，谢谢。
