### ISSUE TITLE
More customizable hotkeys to navigate between tabs

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9210]
### In what scenarios do you need this feature?

在支持多标签页的软件上浏览与编辑时，我通常使用快捷键完成大部分操作，手基本上不会离开键盘；在单纯浏览时，我会倾向使用触控板。在Mac上使用触控板，除少数情况外可以完美替代鼠标。

典型的就是浏览器：Safari、Chrome、Edge。有下面几个情况：

1. 快捷键CMD+数字键1-8切换到指定序号的标签页。例如，CMD+2切换到从左往右数第二个标签页。特别地，CMD+9是切换到最后一个标签页，无论序号是几。

思源目前不支持。

2. Ctrl+Tab切换到下一个标签页，Ctrl+Shift+Tab切换到上一个。并且，使用触控板自定义软件设置触发此快捷键的手势。

思源目前支持，但不清楚为何设置-快捷键里看不到这两个？不过不影响我使用快捷键和触控板手势。

3. CMD+W关闭当前标签页，CMD+Shift+T恢复刚才关闭的标签页。如果是一次性关掉多个标签页，那么CMD+Shift+Tab会将其全部恢复。并且，使用触控板自定义软件设置触发此快捷键的手势。

思源目前不支持后者，也没法设置触控板手势。
思源提供的「后退」CMD+[也是这些软件常用的，但「后退」和「恢复标签页」还是不太一样。

4. CMD+Shift+W关闭当前窗口的除当前标签页外的所有标签页。

思源目前不支持。

### Describe the optimal solution

希望能支持操作1，像Obsidian这样提供快捷键预设：
<img width="777" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/af77844c-4272-4b80-8728-3ffd8d1d0ca1">

操作2不知是出于什么考虑才不能在设置-快捷键里看到和定制？这个我倒是无所谓。

希望能支持操作3。
<img width="530" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/6a0a4d6e-261c-43ba-b7c5-b49bb5c86135">

希望能支持操作4。
<img width="531" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/ca111797-207f-4aa5-986e-a5083528cf0c">
因为思源一个窗口里可以左右上下分栏，所以，到底是「关闭所有其它标签页」，还是「关闭此栏中的其它所有标签页」，有两种选择。我觉得都可以，稍微倾向于后者。Obsidian倒是都提供了，供用户选择：
<img width="793" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/64cd2210-054e-40ad-95d4-37c79dbefc34">

### Other information

手不离开键盘效率高很多。我觉得Obsidian支持的快捷键设置很多，希望思源也能多加一些。例如这个：
<img width="544" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/7ded004f-612d-419e-8849-f18b251e297f">

**Comment by LoneFireBlossom** [comment]
思源这个，不像是tab group。
因为设置-快捷键里没有解释，我想问下Ctrl+Tab, Ctrl+Shift+Tab准确来说是什么功能？

这是Chrome里这两个快捷键的说明：
<img width="429" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/aa731385-f07d-4ecd-b3d6-3dbe6403a759">


思源笔记因为可以分栏、每个栏有各自的一堆标签页所以情况更复杂。
![CleanShot 2023-09-18 at 17 19 16](https://github.com/siyuan-note/siyuan/assets/50087596/57ca2276-a4e5-443e-a2c1-b5c7d74520c7)

![CleanShot 2023-09-18 at 17 20 13](https://github.com/siyuan-note/siyuan/assets/50087596/fef0bae5-f4be-4a59-b0f9-b184e3bec2b3)


Ctrl+Tab我看懂了，就是当前标签页和上一个标签页之间来回切换。（和chrome的逻辑不一样，Chrome里ctrl+tab就是一直往右切换标签页，到头了再回到第一个）
但是Ctrl+Shift+Tab这是啥逻辑？完全看不出有什么规律。


我希望都能改成Chrome那样的，这样用户体验也更统一。
并且把快捷键限制在一个分栏里。


切换到其它分栏就用 https://github.com/siyuan-note/siyuan/issues/9211 这里的快捷键，然后继续ctrl+(shift+)tab，或者ctrl+数字键之类的。

**Comment by Vanessa219** [comment]
Ctrl+Shift+Tab 倒着选，Ctrl+Tab 按照时间选。可以按慢一点，看弹层的高亮情况。

**Comment by Vanessa219** [comment]
- [ ] 为页签切换加入 ctrl1-9 快捷键
- [ ] 为以下操作加入快捷键
<img width="175" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/21df16cb-7d71-4a67-b7da-6b9283a34650">


* Ctrl+Shift+Tab，Ctrl+Tab 为大部分软件常用快捷键，用户一般不会再进行自定义，因此就不增加了
* 打开关闭页签这个目前没有记录关闭的页签及其位置等信息，只能使用 ctrl+e 找一下了
* 有关闭全部页签的快捷键，就可以关闭页签所在的窗口了

**Comment by LoneFireBlossom** [comment]
> * Ctrl+Shift+Tab，Ctrl+Tab 为大部分软件常用快捷键，用户一般不会再进行自定义，因此就不增加了

因为很多软件里都会用到，所以希望能和其它软件例如chrome统一一下，这样体验上不会有割裂。
Chrome里ctrl+tab就是一直往右切换标签页，到头了再回到右起第一个。ctrl+shift+tab就是一直往左切换标签页，到头了再回到左起第一个。


> Ctrl+Shift+Tab 倒着选，Ctrl+Tab 按照时间选。可以按慢一点，看弹层的高亮情况。

上面发过这个图，这是chrome的情况：
<img width="429" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/aa731385-f07d-4ecd-b3d6-3dbe6403a759">

再比如这是macOS的Finder（文件管理器）的情况，和chrome逻辑相同：
<img width="309" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/00675989-9368-40a4-ac8c-424396995586">


按我的理解，思源中目前ctrl+tab是在最近使用的两个标签页中来回切换，与Chrome等软件的功能不同。
「在最近使用的两个标签页中来回切换」也是一个实用的功能，它可以用另外的快捷键来实现。
我建议默认使用ctrl+`。

ctrl+shift+tab「倒着选」我觉得不太行。
如果每次都只是按一下也没问题。
但如果每次都是连续按好几下，因为每次按键以后弹层里标签页的顺序都可能发生改动，所以不可能实现一定程度的盲操作指哪打哪，得看着弹层一点点用快捷键。
