### ISSUE TITLE
Add shortcut keys for moving tabs between windows

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9211]
### In what scenarios do you need this feature?

obsidian里把各个分栏叫tab groups，不知道思源里叫啥，pane么

希望提供这几个快捷键预设，第一组是往右/下分栏，第二组是把焦点放在上/下/左/右栏里。
<img width="760" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/fc2ff052-e31e-4fea-a51c-80e00f3c620a">
<img width="776" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/05b49f29-1117-4d3e-967a-0f9e0445e1b9">

### Describe the optimal solution

快捷键空着就好了，空着就好了，让用户自已设置即可。

### Other information

开发者可以开一个obsidian不带第三方插件的仓库，看一下里面有哪些快捷键，思源能用的直接也提供让用户能预设，不知会不会很难

**Comment by Vanessa219** [comment]
指的是为这几个分屏加上快捷键么？
<img width="424" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/95e24c02-db2c-4ff9-ab4f-323dc385489e">

**Comment by Vanessa219** [comment]
目前还没有这个功能，但可以用 Ctrl+Tab 进行切换后就会定位了。
<img width="296" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/8f7b60fa-e7d0-4a3a-b8b3-5298c02ec750">

**Comment by LoneFireBlossom** [comment]
> 指的是为这几个分屏加上快捷键么？ <img alt="image" width="424" src="https://user-images.githubusercontent.com/970828/269150301-95e24c02-db2c-4ff9-ab4f-323dc385489e.png">

嗯，这几个包含了1楼的split down/right

**Comment by 88250** [comment]
分屏快捷键拆分到 https://github.com/siyuan-note/siyuan/issues/9470 中完成。

**Comment by Vanessa219** [comment]
第二点不需要修改的话我就先关闭了
