### ISSUE TITLE
Crash on Android 14

### ISSUE THREAD

**Issue by chjchen** [siyuan-note/siyuan#9212]
安卓14 闪退

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

手机是一加的，更新了安卓14内测，思源app闪退，不明白是手机系统的问题，还是安卓还没有适配。

### Expected result

希望可以正常使用。

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你好，能否收集到崩溃日志或者相关的日志？

**Comment by 88250** [comment]
那估计只能再等等看了，我们手头上没有设备，一些云平台测试（小米、华为）也没有这个系统版本，暂时无法定位问题。

**Comment by chjchen** [comment]
好的，也可能是系统的问题。等更新到正式版，我再来反馈。谢谢。

**Comment by owen-laney** [comment]
Version 2.10.2 and older work on android 14 if you need a temporary fix

**Comment by 88250** [comment]
@owen-laney Thanks for the information, we will try to fix it in the next version.

**Comment by chjchen** [comment]
新版本问题解决了。
