### ISSUE TITLE
Sorting notebooks automatically after creating a new notebook

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9213]
### In what scenarios do you need this feature?

现在新建一个笔记本之后，竟然不是自动按排序规则排好（例如我设置的按名称升序），还需要再点一下排序规则……

### Describe the optimal solution

*

### Other information

我搜到开发者之前说基本功能做得差不多了可以考虑推广了（原话忘了，大意如此）。
不过我以一个转移过来的新用户的角度，感觉对新人上手还有很多细节没优化……

可能之后我还会继续提一些FR

**Comment by 88250** [comment]
感谢反馈，我们再看看，细节确实还有很多不完善的地方，不着急推广。
