### ISSUE TITLE
如果一个快捷键覆盖了系统快捷键，那么应该彻底覆盖

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9214]
### In what scenarios do you need this feature?

举例：macOS上，CMD+H默认是隐藏当前app，CMD+M默认是将当前APP最小化，这是系统级的快捷键。
思源的快捷键将这两个快捷键覆盖了。
但是没全覆盖。

当思源笔记的焦点不满足此快捷键执行条件时，思源会把快捷键命令让系统处理。
**这会造成操作相同结果却不统一。**

举个极端一点的例子，如果我在chrome里设置alt+F4为新建标签页（只是假设一种不存在的情况），结果有的时候Chrome给我新建标签页，有的时候给我直接关闭窗口，这显然是不行的。

### Describe the optimal solution

预设/用户自定义的快捷键应该全部接管，如果快捷键在当前情况下无效就不执行任何操作，而不是丢给系统。

### Other information

macOS上的electron软件的菜单栏固定会有这么几个：
<img width="212" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/22d1fc14-4069-40f0-8284-2aa1d194ff38">
并且也自带了系统默认的快捷键：
<img width="172" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/b9453a52-e7a9-44dc-9a79-804a583136e3">
<img width="215" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/9bc957e5-fbe9-42f7-9ef5-899c2db50e80">
<img width="372" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/40acb0d6-0717-4d45-ace8-00475743fc0c">

以前obsidian也是这样的菜单栏的时候，这里也是如此，但是CMD+M如果在Obsidian-Settings-Hotkey里面预设了的话，菜单栏里的这个CMD+M就虽然还在但是没效果。所以electron也是能做到的。

**Comment by LoneFireBlossom** [comment]
补充：
我也不太清楚这个应该叫「系统级快捷键」还是「App级快捷键」，就像上面展示的那样，这些快捷键都是在app自己的菜单里的，不知道是electron打包自带的，还是macOS给每个没有自带菜单的软件强制安插的，所以有些地方说“系统”可能不准确，不过我也不清楚了😂

**Comment by Vanessa219** [comment]
没有在编辑器中，用户按这个键就应该是当前范围所监听的功能。在不同的 dock 或编辑器中按下同一个键，效果也会不同。这里就不进行强制覆盖了。

**Comment by LoneFireBlossom** [comment]
这个问题不大，发现这种快捷键我肯定会选择去掉/换掉思源里的这个快捷键。
