### ISSUE TITLE
Chinese-friendly embed block command on macOS

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9216]
### In what scenarios do you need this feature?

目前在中文输入法下输入`（（`，`【【`都可以触发双链。
但是输入`「『`不能触发块嵌入。

macOS和Windows的`{`键不一样，macOS、iPadOS在（自带的）中文输入法下按这个键，第一下会出来`「`，如果系统检测到这个括号没有包起来，第二下会出来`『`。

### Describe the optimal solution

建议当用户输入以下几种符号时全部触发块嵌入：
```
「『
「「
『『
『「
```
也可以只有`「『`和`『「`触发块嵌入，足够了。我没有遇到过按两下Shift+大括号键的输入是「「或『『的情况。

### Other information

我很疑惑：

# 之前没有人在macOS&iPadOS上用思源笔记吗？
思源两年还是三年了，这应该是再基本不过的优化中文用户体验的操作……竟然没有人提过？

**Comment by LoneFireBlossom** [comment]
在群里交流了一下。他们很多用Mac人都用第三方输入法所以没这个问题，我用的是macOS自带的。因为自带的搭配一些软件对我来说更有优势

**Comment by Vanessa219** [comment]
直接使用 【【 就可以了，为什么还要去按一下 shift ？

**Comment by LoneFireBlossom** [comment]
> 直接使用 【【 就可以了，为什么还要去按一下 shift ？

因为是要用`{{`进行块嵌入，不是`【【`！
所以要按shift

**Comment by LoneFireBlossom** [comment]
额，开发者还有邮件提醒吗？能看到吗？重开一下啊

**Comment by Vanessa219** [comment]
😄 搞错了，搞错了
