### ISSUE TITLE
设置-快捷键里的「编辑模式」改成「只读/编辑模式」

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9217]
### In what scenarios do you need this feature?

简单来说就是我不小心触发了锁定找半天才找到，所以快捷键这里加几个字方便搜索。
**思源默认就是编辑模式，绝大多数人绝大多数场景也是编辑模式，快捷键叫`编辑模式`着实不合理。**
这么小的事情不想多打字了

<img width="376" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/083d5b75-4d07-4829-890a-a0fb7a6589e6">

### Describe the optimal solution

改成「只读/编辑模式」或者「只读/编辑模式切换」「开关只读模式」之类的，开发者看着办。

**Comment by 88250** [comment]
感谢反馈，下个版本优化，改为 编辑模式/只读模式。

**Comment by Vanessa219** [comment]
统一改为"只读模式"
<img width="357" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/dfcb4d76-7873-4148-8001-186a71206080">
<img width="1296" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/f957813b-0ab4-46f2-a45d-726681fc7c5f">
