### ISSUE TITLE
搜索面板应做得像反链面板那样

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9218]
### In what scenarios do you need this feature?

https://www.yuque.com/deerain/gannbs/ffqk2e
<img width="759" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/c9242363-a83c-4853-98e4-48c917449625">

既然如此，为什么不把搜索面板做成和反链面板一样呢。
参见：https://ld246.com/article/1694881740283

**标签在大多数情况下就是没有那个空页面的双链，只是语法不一样。这些元数据本质是一样的，所以我认为应该提供相同的筛选呈现方式。**

### Describe the optimal solution

我提供一种思路。

这是MarginNote 3的大纲视图，双指上下放缩即可展开/收起内容，收起是只显示卡片标题，展开是显示卡片所有内容。

![CleanShot 2023-09-18 at 16 57 00](https://github.com/siyuan-note/siyuan/assets/50087596/16a95755-37cf-4fed-8b22-999dd1841006)

也就是说，**提供一种「现在的搜索面板」和「展开搜索内容」的切换方式。** 另外，反链面板也可以提供一个展开/收起的操作。
展开搜索内容时的动画顺带把右侧/下侧这个栏给推出去。收起的时候再拉回来。
快捷键也好，鼠标也好，触摸板也好，按钮也好，总之有这个方式。

<img width="712" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/fa2a97fa-29af-43f4-8a61-be3755dc2ddb">

展开之后，就要能在搜索面板上直接编辑、拖动块，就像现在的反链面板一样。
其中，拖动块显然只能在「固定搜索」时提供。

### Other information

不知技术上是否很难做到？

**Comment by 88250** [comment]
文本标签那个不会有改变了（不会改成等价引用）。

反链和搜索不太一样，反链主要是确切关系情况下的上下文展现，而搜索主要是精确定位，如果要看上下文也提供了预览区滚动，这样也比较符合大部分用户对搜索的期望。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by LoneFireBlossom** [comment]
> 进一步地说，
文件夹就是不能复用的标签，双链就是能补充信息的标签，其它各种元数据（例如作者、出版年份等等）都是标签。
它们都是附加在文档上的元数据，本质上没什么区别，只是人们为了方便平时使用所以做了一些分类，有一种元数据面对这种情况、有一类元数据面对那种情况而已。

首先，标签我觉得维持现状即可，我没有要提议改这个。

其次，这里提到的功能是新增的，不想这么用的人该怎么用还是怎么用，不受影响。

再次，预览区是需要点/按一下的，每看一行就要点/按一下，而放缩只需要一次操作，方便很多。

最后，举一个假设的场景。
假设我已经做了很多关于数学的笔记，现在我要筛选出`「几何学」`中所有`在证明过程中使用` `[[多元函数的极限]]`的`必要条件`，全部浏览，并做归纳整理、视情况需要讲内容拖到正文中。以上`   `中的内容都已经打好标签或双链或分类。
函数极限是一个相当常用的概念，`[[多元函数的极限]]`这个块的反链面板中恐怕得有几千个块，直接浏览是不可能的。

现在的反链面板能做到吗？显然不能，反链面板上的搜索功能太弱了。
SQL一是门槛太高，二是展示的结果似乎只能是嵌入块，不能拖到正文。
搜索面板能做到吗？也许可以，但不能方便地将内容拖到正文。

如果没预先弄好标签和分类就更是灾难了，直接搜文本搜索结果会更多。

所以，要么把搜索面板做成和反链面板一样，要么增强反链面板的筛选功能，要么全都要。
我觉得：

1. 给这两个面板都提供展开/收缩的功能
2. 统一增强这两个面板的筛选功能


是迟早要做的。

**Comment by LoneFireBlossom** [comment]
再举一个例子。有那么一点相关性。

我刚才好不容易找到文档块的标签竟然是在上面按钮里（不在菜单里。说明文档也没写）
然后我立刻试了试，把文档块拖到一个文档里之后，标签就单独成了一行。

那我在搜索里搜这个标签，搜索展示的内容就所在文档了，具体什么内容不知道，只能到预览里看。
还是能直接看到上下文才好。

**Comment by LoneFireBlossom** [comment]
增强筛选功能（可交互？是这么叫的吧）我想是这样：

DEVONthink：
<img width="1256" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/439b3b7f-75c8-4781-8735-473f7d887576">

OmniFocus：
<img width="752" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/b0b22662-204e-4356-b98d-b42faf56ab1e">
