### ISSUE TITLE
安卓端美观易用

### ISSUE THREAD

**Issue by remoon1991** [siyuan-note/siyuan#9228]
### In what scenarios do you need this feature?

我目前使用安卓版思源笔记，发现插入照片和录音会特别麻烦。而且软件后台后会断开连接，感觉不是很棒，希望能够优化。

### Describe the optimal solution

只要和notion类（wolai，flowus等）差不多就行，和evernote差不多也行

### Describe the candidate solution

大D会懂意思的，就是觉得PC端已经很不错啦，建议补齐手机端使用，因为我开会时用手机记录发现特别麻烦，就用notion或者flowus记录，然后导出md给思源。就很麻烦

**Comment by 88250** [comment]
后台会断开连接这个没有办法，只能试下关闭耗电等权限看看。

插入照片的话没有对接相册接口（这个好像要对不同机型适配），目前没有开发资源来实现，只能后面看情况慢慢优化了，感谢反馈。
