### ISSUE TITLE
通过页签重命名文件无法立即体现到文件树

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#923]
### 描述问题 Describe the problem
复现步骤
一、右键页签，重命名
二、输入新文件名
三、查看文件树并没有变化
四、刷新文件树生效
### 期待的结果 Expected result
无论从哪个入口修改了文件名，理论上应该都是直接生效
### 版本环境 Version environment
* 版本 Version：0.5.5
* 操作系统 Operating system：Windows 10

**Comment by 88250** [comment]
你好，我这里在 v0.5.5 和目前的开发版上都没能重现问题，请等 v0.5.6 发布以后再看看，如果没问题的话麻烦关闭，谢谢。

**Comment by GlowBlur** [comment]
新版本没有这个问题了
