### ISSUE TITLE
修改文档名后已打开的标签页上的标题不会同步修改

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#9232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题

### Expected result

标签页标题同步修改

### Screenshot or screen recording presentation

![9756a85692521a02c1dfd72453a0e029](https://github.com/siyuan-note/siyuan/assets/57566668/b4980502-08b9-48df-8ecc-94d98960108e)

### Version environment

```markdown
- Version: 2.10.6
- Operating System: win10
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
我这里在默认主题下测试正常。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
