### ISSUE TITLE
难以用 down arrow 到达下一个 content block

### ISSUE THREAD

**Issue by sublimeclemency** [siyuan-note/siyuan#9233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

<img width="190" alt="Screenshot 2023-09-20 at 3 41 24 pm" src="https://github.com/siyuan-note/siyuan/assets/124845026/e42a5f7e-8cb9-45e8-bfcb-b4c44998a6cf">

在编辑 list 的时候, 不能用 down arrow 来到达下一个 content block, 没有反应

### Expected result

<img width="253" alt="Screenshot 2023-09-20 at 3 37 38 pm" src="https://github.com/siyuan-note/siyuan/assets/124845026/cf1fcf0d-40fc-4156-a20f-8670c1cbefcd">

要是编辑一个 quote block 的话, 用 down arrow 是可以的

希望编辑 list 的时候也同样

### Version environment

```markdown
ㅤ
```

### Log file

ㅤ

**Comment by 88250** [comment]
你好，这个是设计如此，↓ 在列表中不会创建新块。
