### ISSUE TITLE
嵌入块无法 shift+拖拽 快捷操作

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用嵌入块功能时，快捷方式失效

### Expected result

能够尽快修复此功能

### Version environment

```markdown
- Version: 2.10.6
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12670817/siyuan.log)

**Comment by Dammyxy** [comment]
先按住 shift 没法拖拽成嵌入块，先拖拽块后按住 shift 再放开是能拖拽成嵌入块的 https://github.com/siyuan-note/siyuan/issues/3294#issuecomment-1236124109

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by TCOTC** [comment]
现在是可以的，不过列表项有问题 https://github.com/siyuan-note/siyuan/issues/12542
