### ISSUE TITLE
重命名文件与同级文件夹名称相同时出错同时丢失文件和文件夹

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#924]
### 描述问题 Describe the problem
复现步骤
一、在同级目录新建文件夹 测试
二、在同级目录下新建文件 测试1
三、将测试1重命名为测试
四、出错提示，同时测试文件夹与测试1丢失
五、检查文件资源管理也没有这个文件夹和文件
### 期待的结果 Expected result
不应该丢失文件和文件夹
### 版本环境 Version environment
* 版本 Version：0.5.5
* 操作系统 Operating system：Windows 10

**Comment by 88250** [comment]
你好，和 https://github.com/siyuan-note/siyuan/issues/923 一样，我这里重现不了。麻烦等新版发布以后帮忙确认一下，谢谢。

**Comment by GlowBlur** [comment]
E 2021/01/02 17:25:24 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 17:26:31 box.go:240: 重命名笔记本 [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/] 下的文件 [/Projects/MES/MES/] 失败：MOVE /Projects/MES/MES/: 403
E 2021/01/02 17:26:31 box.go:733: worktree move failed: 重命名笔记本 [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/] 下的文件 [/Projects/MES/MES/] 失败：MOVE /Projects/MES/MES/: 403
E 2021/01/02 17:26:37 box.go:240: 重命名笔记本 [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/] 下的文件 [/Projects/MES/MES/] 失败：MOVE /Projects/MES/MES/: 403
E 2021/01/02 17:26:37 box.go:733: worktree move failed: 重命名笔记本 [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/] 下的文件 [/Projects/MES/MES/] 失败：MOVE /Projects/MES/MES/: 403
D 2021/01/02 17:26:45 box.go:379: unindexed note book [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
D 2021/01/02 17:26:45 box.go:355: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
D 2021/01/02 17:27:16 box.go:379: unindexed note book [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
D 2021/01/02 17:27:16 box.go:355: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
D 2021/01/02 17:27:44 box.go:379: unindexed note book [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
D 2021/01/02 17:27:44 box.go:355: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
I 2021/01/02 17:28:43 setuilayout.go:43: set ui layout done
I 2021/01/02 17:28:44 process.go:71: ui process exited, exit kernel process now
I 2021/01/02 17:28:44 conf.go:224: exited kernel
I 2021/01/02 17:28:46 main.go:121:

**Comment by GlowBlur** [comment]
当时的版本确实存在问题，但是现在无法复现了，暂时关闭吧，后期观察

**Comment by 88250** [comment]
谢谢，欢迎使用最新的 v0.5.6-alpha1 进行测试。
