### ISSUE TITLE
try catch plugin `onunload` 

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#9240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

起因是[小窗无法关闭的问题](https://github.com/WingDr/siyuan-plugin-zettelkasten/issues/4)，后来检查到是因为列表预览插件的onunload报错了导致之后都进行不下去

![e11c2c57f9e478fa406c4e3208efa85f](https://github.com/siyuan-note/siyuan/assets/63407442/10ffdc6f-7713-49e6-af82-ef8d933263f6)

这个显然是默认的onunload，也就是说所有覆写了i18n的插件都会有这个错误导致无法关闭

### Expected result

建议把插件里面非必要的默认函数都设置成空的，不然之后很有可能还会有其它乱七八糟的报错，主要是i18n里面不一定会留默认的那些东西

### Version environment

```markdown
- Version: 2.10.6
- Operating System: windows 
- Browser (if used):
```

### Log file

![image](https://github.com/siyuan-note/siyuan/assets/63407442/5e1e456c-07ca-411d-bcfb-1d9d0755b959)

**Comment by Vanessa219** [comment]
我这里重现不了，检查了下这个多语言是存在的。具体是要怎么操作可以重现呢？

**Comment by WingDr** [comment]
> 我这里重现不了，检查了下这个多语言是存在的。具体是要怎么操作可以重现呢？

最简单的就是开启那个"预览折叠列表"插件（siyuan-plugin-fold-list-preview），我截图里的错误就是开这个插件出来的

**Comment by Vanessa219** [comment]
可以重现了，下个版本加强下容错性，多谢。
