### ISSUE TITLE
Improve error tip when renaming tags/bookmarks containing Markdown markers

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9248]
标签"请勿包含Markdown语法标记符"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [x] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

`#test/test & abc#`可以在文档里正常打出来作为一个标签，并被软件识别。
但是在标签栏-菜单-编辑里打开编辑窗口，什么也不干点确定，会出现如下提示：

<img width="305" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/d3f8d806-93a0-471c-b1ec-3224610447bf">

### Expected result

*

### Version environment

```markdown
- Version: 2.10.6
- Operating System: macOS 13.5.2
- Browser (if used):
```

### Log file

*

### More information

思源打算允许`#test/test & abc#`这种情况吗？目前是哪个字符造成的提示，打算之后禁止吗，我好提前修改一下

**Comment by 88250** [comment]
`&` 符号，暂时不会做调整了，先避免使用吧。

**Comment by LoneFireBlossom** [comment]
搜了一下没找到“markdown语法标记符”有哪些，试了试`-`可以用，开发者能说一下还有哪些不能用么

**Comment by 88250** [comment]
看下这个文件 https://github.com/siyuan-note/siyuan/blob/master/kernel/treenode/marker.go

**Comment by LoneFireBlossom** [comment]
> `&` 符号，暂时不会做调整了，先避免使用吧。

我不清楚开发者关闭issue的原因，这个问题迟早是要改的，有没有记录下来（等打算改的时候再reopen）？
现阶段没时间改，可以至少在说明文档-标签里添加「标签不能用哪些符号」的说明啊。

**Comment by 88250** [comment]
技术上改不了的，不然也不会有这个判断了。

帮助文档增加说明是个好主意，等有空就改进一下，感谢反馈。

**Comment by 88250** [comment]
看了下代码，还是直接在报错文案上明确提示不可用字符好一些，下个版本就改进。

**Comment by LoneFireBlossom** [comment]
> 看了下代码，还是直接在报错文案上明确提示不可用字符好一些，下个版本就改进。

这解决不了正文里输入的问题啊，起码得输入`#A & B#`后软件不认这是个标签不会自动变成标签的样子。
如果难以实现就得先得在说明文档里说一下标签里有哪些不能用的字符

**Comment by 88250** [comment]
好的，还是说明一下吧。
