### ISSUE TITLE
希望支持表格全宽显示

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#9249]
### In what scenarios do you need this feature?

不太会表达这个特性名称，稍微长一点的表格都需要这个功能把！！！

### Describe the optimal solution

- 大部分笔记软件都支持，有点影响体验。例如：↓
- 链滴
![image](https://github.com/siyuan-note/siyuan/assets/72399630/51725a70-894b-4563-8990-4a36e273f805)
- obsidian

https://github.com/siyuan-note/siyuan/assets/72399630/0aeb3f9f-3810-478a-b442-f087b55edf49

…………

**Comment by 88250** [comment]
默认主题表格可以横向滚动的。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by shuojie819** [comment]
> 默认主题表格可以横向滚动的。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

哦哦，好吧🥲，我的问题
