### ISSUE TITLE
笔记库与附件库分离

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#925]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
笔记库一般记录纯文本类笔记，不包含或者少数包含图片等媒体文件
在笔记中通过引用URL或者地址来引用资源文件
很多时候浆洗文件会移动因此无法在笔记中使用绝对路径
使用相对路径又会导致笔记库过大同时也不更于版本控制和快速同步
希望可以宝姿资源库挂载资源库功能
### 描述最优的解决方案 Describe the optimal solution
设置中配置资源库地址，可以是图床，可以是阿里OSS，可以是URL，可以是一个本地路径等
笔记中使用 资源库名称加上路径即使用了相对路径
资源库路径变化只要修改对应的路径即可
### 描述候选解决方案 Describe the candidate solution
资源库以快捷方式的形式存在于目录中

**Comment by deerainw** [comment]
Obsidian 就是这样的

**Comment by 88250** [comment]
你好， 这一块估计不会有变动了，图床相关请关注 #641 谢谢。
