### ISSUE TITLE
Use `Git LFS` to manage static resource files in `app/stage/protyle/**`

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#9253]
### In what scenarios do you need this feature?

在目录 `app/stage/protyle` 下有许多静态资源文件 (例如 `*.min.js`), 这些文件使用 `Git` 管理会导致仓库体积快速膨胀, 应使用 [Git LFS](https://git-lfs.com/) 管理这些文件
There are many static resource files (such as `*.min.js`) under directory `app/stage/protyle`, Managing these files with 'Git' causes the repository to expand rapidly and should be managed using [Git LFS](https://git-lfs.com/).

### Describe the optimal solution

在仓库根目录下使用如下命令:
Run the following command in the root directory of the repository:

```bash
git lfs install
git lfs track 'app/stage/protyle/*/**'
git lfs track 'app/stage/protyle/**.min.js'
```

**Comment by 88250** [comment]
对于初次 git clone 时有什么注意事项吗？有的话可能得改改开发指南文档。

**Comment by Zuoqiu-Yingyi** [comment]
> 对于初次 git clone(克隆) 时有什么注意事项吗？有的话可能得改改开发指南文档。

经过我的测试, 使用 `git clone` 命令时可以同步拉取 LFS 中的文件, 无需其他配置

不过开发指南文档可以说一下拉取时可以添加 `--depth` 参数以避免将整个库拉下来

**Comment by 88250** [comment]
好的，帮忙 pr 一发吧 🙏🏻



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 22, 2023 17:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Use `Git LFS` to manage static resourcefiles in `app/stage/protyle/**` (Issue #9253)




  
对于初次 git clone(克隆) 时有什么注意事项吗？有的话可能得改改开发指南文档。
  
经过我的测试, 使用 git clone 命令时可以同步拉取 LFS 中的文件, 无需其他配置
 
不过开发指南文档可以说一下拉取时可以添加 --depth 参数以避免将整个库拉下来

**Comment by Zuoqiu-Yingyi** [comment]
> 好的，帮忙 pr 一发吧 🙏🏻

无法在 fork 仓库里面设置 LFS...

**Comment by 88250** [comment]
明白了，等过两天我试试。

**Comment by 88250** [comment]
增加一个 `git lfs track 'app/pandoc/*'`

**Comment by 88250** [comment]
用了一天，免费流量配额超了……稍后我还是回滚吧。
