### ISSUE TITLE
`Exit focus` should not be displayed when opening an embedded document block

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#9254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

# 问题一

当列表只有一项时，应该显示列表项块图标 
![image](https://github.com/siyuan-note/siyuan/assets/72399630/b7f725aa-cf18-46e3-aeb9-aea0c105d0ac) 
而不是无序列表块图标 
![image](https://github.com/siyuan-note/siyuan/assets/72399630/7689a5ec-31b0-4933-993d-a5ed606f6ae2)

---

# 问题二

打开嵌入内容块时，会触发聚焦，当嵌入内容块是文档时也会触发聚焦（而且点击无法关闭，必须先触发一次聚焦才可以关闭）

https://github.com/siyuan-note/siyuan/assets/72399630/f0bc8be8-13b7-4ce5-9e4c-c0db3554d055

### Expected result

问题一：当列表只有一项时，应该显示列表项块图标 。
问题二：打开嵌入内容块时，不应该触发聚焦。

### Version environment

```markdown
- Version: v2.10.6
- Operating System: Windows 11 23H2
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/12696808/system-log.zip)

**Comment by 88250** [comment]
问题一是一个优化，可以使用圆点/数字操作列表项块。

**Comment by 88250** [comment]
问题二对于文档块不应该显示 退出聚焦 稍后改进 @Vanessa219

**Comment by shuojie819** [comment]
> 问题一是一个优化，可以使用圆点/数字操作列表项块。

哦哦，好的，使用上不影响。就是我看一直没优化就来提提。
“问题是一个一个优化的”是后面优化的意思，还是我这是两个问题，需要分开提？

**Comment by 88250** [comment]
问题一是一个特意做的优化。

**Comment by shuojie819** [comment]
哦哦，好吧😊，没问题了ヾ(•ω•`)o
