### ISSUE TITLE
关于思源笔记中公式复制到公众号会乱码的反馈

### ISSUE THREAD

**Issue by 891680996** [siyuan-note/siyuan#9258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在思源笔记中将编辑好的含有公式的文章复制到微信公众号时，发现稍复杂一点的公式就会出现乱码，下面给出三种情况下，公式复制前后效果对比：
1. 行内公式：V_{g0}，复制前后效果对比：如下图：
![公式复制1](https://github.com/siyuan-note/siyuan/assets/23329511/3f05a321-2769-4a2a-a426-128d1d57db32)

2. 行间公式：I_S(T)=CT^{4-m}e^{-\frac{V_{g0}}{V_T}}，复制前后效果对比：如下图：
![公式复制](https://github.com/siyuan-note/siyuan/assets/23329511/53191cbe-a10f-4fc0-bf47-2b15122344f4)

### Expected result

1. 期望公式从思源笔记复制到微信公众号之后显示与原始格式基本保持一致，或者可再编辑；

### Version environment

```markdown
- Version: 2.10.6
- Operating System: Win 11
- Browser (if used):Edge
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12708133/siyuan.log)

### More information

有一个插件可以很好的处理微信公众号里面的公式，不知道它的实现方式对思源有没有一些启示，这个工具实现的公众号公式可以随时编辑。
![image](https://github.com/siyuan-note/siyuan/assets/23329511/39f820b7-f77e-4cf9-81aa-2f94cf51c87b)

**Comment by qingtian805** [comment]
我没写过微信公众号。
搜了一下，微信公众平台好像不兼容Latex公式……我看[别人](https://zhuanlan.zhihu.com/p/651874507)写公众号还得转换一下格式。
集市里的“发布工具”插件你看看能用不？虽然我也没用过……。

**Comment by 891680996** [comment]
感谢回复，这个插件试用了一下，公众号不支持markdown，所以在公众号平台上面发布的内容是源码，没有格式；另外微信公众平台确实不支持markdown公式，目前都是转成图片或者svg的方式比较好，上面提到的那个浏览器插件很好用，但是需要一个一个敲进去，公式多了效率很低

**Comment by qingtian805** [comment]
今天申请了个微信公众号测试了一下，找了个方法。
SiYuan打开文档右上角三点菜单里有一个模式切换，可以切换到导出预览模式，按ctrl+alt+9也行，在导出预览模式下有复制到公众号的按钮。复制到公众平台是这样的：
![图片](https://github.com/siyuan-note/siyuan/assets/59603685/85860c2c-1a47-4705-b7ef-488feffb39d9)
![图片](https://github.com/siyuan-note/siyuan/assets/59603685/a322fd55-d0dd-4548-8f65-09a55f685b05)

两个问题：
1. 只能一下子把整页文档复制过去，不能只复制一个公式
2. 没法居中

**Comment by qingtian805** [comment]
**补充一点信息**，今天注册了个公众号测试了一下，我这边的情况是这样的：
复制过去的时候是正常的
![图片](https://github.com/siyuan-note/siyuan/assets/59603685/709cb3d3-9230-4150-bb27-47353d326f84)
但是保存之后就变了
![图片](https://github.com/siyuan-note/siyuan/assets/59603685/2b5863ff-f19b-44b1-be9a-6d959e3fd0f2)
发布出去的预览看到的结果和保存后编辑器里的一样，就不贴截图了。
如果光标在文章末尾输入退格，则会显示消失的内容或者乱码
![图片](https://github.com/siyuan-note/siyuan/assets/59603685/a7f21fbe-6754-4558-a2b2-c23335a0c7ff)
![图片](https://github.com/siyuan-note/siyuan/assets/59603685/216f47d0-148e-4fb1-ac49-8ae18eb63608)

**Comment by 891680996** [comment]
好奇怪，你用的思源版本和浏览器是哪个？我这里看到复制过去就是乱的，跟你看到的保存之后结果很像呢

**Comment by qingtian805** [comment]
> 好奇怪，你用的思源版本和浏览器是哪个？我这里看到复制过去就是乱的，跟你看到的保存之后结果很像呢

确实，之前测试忽略了环境的问题。之前的测试环境：

SiYuan：2.10.7-Windows
浏览器：Firefox 117.0.1

收到消息后我去edge那边看了看，情况跟你一模一样。

**Comment by qingtian805** [comment]
微信公众平台对代码进行了大量的裁切，包括但不限于 class=和style="position: " 裁切掉了。

File: https://cowtransfer.com/s/eb186dc8ed424c
Password: dnx7cc

**Comment by 88250** [comment]
这个问题可能解决不了了，非常抱歉。

后续如果其他人有类似问题，我们会关联到此 issue，谢谢。
