### ISSUE TITLE
拖动关系图窗口后编辑器无法选中

### ISSUE THREAD

**Issue by zqhjl** [siyuan-note/siyuan#926]
### 描述问题 Describe the problem

点开关系图，拖动窗口，当该窗口不经过编辑器窗口时，即使结束拖动窗口后，编辑器窗口也还是蓝色，且无法选中。
### 期待的结果 Expected result

修复这一现象
### 版本环境 Version environment

* 版本 Version：0.5.5
* 操作系统 Operating system：windows 10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

I 2021/01/03 09:40:26 main.go:122: kernel [v0.5.46] is booting, runtime mode is [prod], working directory is [D:\Program Files\SiYuan\resources], temp directory is [C:\Users\mmc\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/03 09:40:26 lang.go:67: initialized languages
D 2021/01/03 09:40:26 conf.go:87: loaded conf [C:\Users\mmc\.siyuan\conf.json]
I 2021/01/03 09:40:26 conf.go:171: local serve path [http://192.168.0.5:6806]
I 2021/01/03 09:40:26 conf.go:175: initialized conf
I 2021/01/03 09:40:26 main.go:165: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/03 09:40:26 webdav.go:36: initialized WebDAV server
D 2021/01/03 09:40:26 box.go:358: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/思源笔记用户指南/]
I 2021/01/03 09:40:26 conf.go:292: initialized notebook
E 2021/01/03 09:40:26 box.go:508: init repo failed: mkdir D:\Program Files\SiYuan\resources\guide\思源笔记用户指南\.git: Access is denied.
I 2021/01/03 09:40:26 repo.go:39: initialized git repo
E 2021/01/03 09:40:33 updater.go:102: check update failed: [Get "https://rhythm.b3log.org/version/siyuan?ver=0.5.46": context deadline exceeded (Client.Timeout exceeded while awaiting headers)]
E 2021/01/03 09:50:26 log.go:44: PANIC RECOVERED: runtime error: invalid memory address or nil pointer dereference
	D:/go1.15.2/src/runtime/panic.go:969 (0xf8bed5)
D:/go1.15.2/src/runtime/panic.go:212 (0xfa1255)
D:/go1.15.2/src/runtime/signal_windows.go:246 (0xfa10ed)
D:/gogogo/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/repository.go:497 (0x1c4d8d1)
D:/88250/siyuan-src/kernel/model/box.go:532 (0x1c4d8c8)
D:/88250/siyuan-src/kernel/model/box.go:700 (0x1c50533)
D:/88250/siyuan-src/kernel/model/repo.go:60 (0x1c7152e)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xfc3420)

**Comment by 88250** [comment]
你好，日志显示内核版本是 v0.5.46，请关闭后卸载重新安装 v0.5.5 后再试，谢谢。
