### ISSUE TITLE
讯飞星火认知 AI support

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9261]
https://www.xfyun.cn/doc/spark/Web.html

**Comment by leolee9086** [comment]
source/throne/processors/language_processors/LLMAPIS/sparkChat.js

**Comment by leolee9086** [comment]
之前弄了一下星火的，不知道有没有参考价值

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/9262#issuecomment-2009177382
