### ISSUE TITLE
Refactor the AI API access framework

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9262]
* https://github.com/siyuan-note/siyuan/issues/8095
* https://github.com/siyuan-note/siyuan/issues/8189
* https://github.com/siyuan-note/siyuan/issues/10467
* https://github.com/siyuan-note/siyuan/issues/9024
* https://github.com/siyuan-note/siyuan/issues/9261
* https://github.com/siyuan-note/siyuan/issues/10464
* https://github.com/siyuan-note/siyuan/issues/10593

Extract common interfaces to enable access to different API implementations.

**Comment by Zuoqiu-Yingyi** [comment]
最好在使用时不再使用遮罩, 在执行一些用时较长的 AI 任务时难以多任务并行执行, 且无法进行其他内容的编辑

**Comment by Lizhen0628** [comment]
可以增加 temperature 和 n 等参数调节的能力

**Comment by mohuishou** [comment]
感觉最好支持流式api实时显示生成结果，现在siyuan的ai功能基本没用就是等待太久了，会导致没有预期

**Comment by Zuoqiu-Yingyi** [comment]
> 只是整合AI API，其实作用不大，目前市面上已经有这样的软件了，对话体验、保留历史对话记录、对话支持导出markdown、支持各种prompt，本身体验都已经很好了

能直接在笔记里面用的话体验还是挺好的, 比如翻译下文档之类, 比粘贴来粘贴去方便不少

**Comment by Lizhen0628** [comment]
阿里通义千问的效果非常不错，建议支持。

**Comment by ttimasdf** [comment]
> 其实笔记软件使用ai，我觉得最大的前景是向量化个人知识库，使用ChatGPT询问，打造个人的知识管家

之前开发者好像说过这个以后不在核心里实现，社区可以自己做插件……

但其实我也觉得只有引入embedding，嵌入LLM才有意义，AI 不知道笔记的上下文，光嵌入个api，使用体验不仅比不上chatgpt，甚至不如API套壳的webui（如[Yidadaa/ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)），存储embedding的向量数据库存储额度，也可以计入年付订阅里，也可以通过pro feature让用户自建（[🗄️ Vector databases - Embedchain](https://docs.embedchain.ai/components/vector-databases)）。

如果这个能进到年付订阅里，那我只能说：

![image](https://github.com/siyuan-note/siyuan/assets/2762704/09353622-c147-489a-97f8-8f33ef1a0961)

**Comment by dwinkler1** [comment]
Possibly relevant here [https://liuyun.io/article/1704494054801](https://liuyun.io/article/1704494054801)

I think it would be great if e.g. we could pick models from ollama directly. There are very good models out there small enough to run on newer consumer hardware.

**Comment by 88250** [comment]
@Benjamin-Watson0 你好，这个问题暂时不作调整了。

**Comment by 88250** [comment]
@Benjamin-Watson0 在 https://github.com/siyuan-note/siyuan/issues/10255 中加入一个菜单操作“清空上下文”。

**Comment by dwinkler1** [comment]
Possible inspiration https://github.com/reorproject/reor

**Comment by TCOTC** [comment]
google gemini #10104

**Comment by Zuoqiu-Yingyi** [comment]
@88250 
瞅到一个 **通过标准的 OpenAI API 格式访问所有的大模型** 的项目, 可以参考一下
[GitHub - songquanpeng/one-api: OpenAI 接口管理 & 分发系统](https://github.com/songquanpeng/one-api)

**Comment by 88250** [comment]
考虑了下，AI 服务太多，仅靠我们对接的话不大现实，这个方面还是靠社区插件对接吧。

后续内核仅考虑对接兼容 OpenAI API 的模型（需要略微调整的，比如 Azure OpenAI），感谢各位理解和关注。

**Comment by frostime** [comment]
> 考虑了下，AI 服务太多，仅靠我们对接的话不大现实，这个方面还是靠社区插件对接吧。
> 
> 后续内核仅考虑对接兼容 OpenAI API 的模型（需要略微调整的，比如 Azure OpenAI），感谢各位理解和关注。

插件提供功能的话，是不是提供一套标准化接口比较好？否则一个插件有一个插件的实现方式，最后容易乱掉。

**Comment by 88250** [comment]
AI 参数和能力各异，提供规范可能不大现实。



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 20, 2024 18:06 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Refactor the AI API access framework (Issue#9262)




  
考虑了下，AI 服务太多，仅靠我们对接的话不大现实，这个方面还是靠社区插件对接吧。
 
后续内核仅考虑对接兼容 OpenAI API 的模型（需要略微调整的，比如 Azure OpenAI），感谢各位理解和关注。
  
插件提供功能的话，是不是提供一套标准化接口比较好？否则一个插件有一个插件的实现方式，最后容易乱掉。

**Comment by heartacker** [comment]
openai限制非支持国家和地区的api调用

**Comment by TCOTC** [comment]
用代理或者转发

**Comment by heartacker** [comment]
> 用代理或者转发

作为一个普通用户，用上AI 的心智投入和成本越来越高

**Comment by TCOTC** [comment]
用国内的

**Comment by jaar23** [comment]
除了openai 不支持国内以后，还有其他的支持吗？在国内有没有统一的API spec, 就好像OpenAI API spec那样？

**Comment by TCOTC** [comment]
国内的大模型多数都兼容 OpenAI 的格式

**Comment by X-49** [comment]
How can I use Gemini in SiYuan? In Obsidian, it was enough for me to install the 'Smart Connections' plugin and specify my API key.

**Comment by FYZAFH** [comment]
能嵌入个terminal支持claude code不
