### ISSUE TITLE
代码块内含 $$ 的代码被渲染为斜体

### ISSUE THREAD

**Issue by jagger2048** [siyuan-note/siyuan#9263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

代码块内，输入以下，内容时，$$ 包括的内容被异常渲染为斜体：
```
docker run -d  -p 443:443 -p 9000:80 -p 22:22 --name gitlab --restart always -v $HOME/docker/gitlab/config:/etc/gitlab -v $HOME/docker/gitlab/logs:/var/log/gitlab -v $HOME/docker/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce
```

### Expected result

粘贴的代码不需要进行额外的渲染和转化，直接按照原本的内容进行显示即可

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/35281281/f9d6ce3e-397b-408d-9e0e-3fa34d9c607e)

### Version environment

```markdown
- Version:   v2.10.6
- Operating System: linux/docker
- Browser (if used): edge
```

### Log file

not

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by jagger2048** [comment]
![20230925195744_rec_](https://github.com/siyuan-note/siyuan/assets/35281281/b3ecf4df-7923-40a7-bedc-7e05034258e7)
用默认的主题（daylight/midnight，代码主题用 github），先创建了一个代码块后，把上边提到的代码复制进去就能看到变化了

> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

**Comment by 88250** [comment]
我这里在浏览器端和桌面端中均无法重现问题，请试下在新的工作空间测试，已排除其他插件或者扩展影响。

**Comment by jagger2048** [comment]
> 我这里在浏览器端和桌面端中均无法重现问题，请试下在新的工作空间测试，已排除其他插件或者扩展影响。

我重新测了一下， 客户端没有这个现象，通过 docker 部署出来的有这个现象
![20230926103027_rec_](https://github.com/siyuan-note/siyuan/assets/35281281/0ed408f1-a5dc-4923-91c6-deaf16519220)

**Comment by jagger2048** [comment]
用 docker 新起了一个，不做任何修改，可以必现：
![20230926104956_rec_](https://github.com/siyuan-note/siyuan/assets/35281281/fac31276-0a56-40a3-8eb4-216289fc3ae9)

**Comment by 88250** [comment]
启动桌面端，用浏览器 127.0.0.1:6806 访问能重现吗？

**Comment by jagger2048** [comment]
> 启动桌面端，用浏览器 127.0.0.1:6806 访问能重现吗？

是可以重现的，本地 windows 客户端版本是 v2.10.6

![image](https://github.com/siyuan-note/siyuan/assets/35281281/8fe428d1-e0db-4156-9957-0c133d7e292e)

**Comment by 88250** [comment]
好的，那应该是浏览器插件导致了。
