### ISSUE TITLE
Improve transformation with sub-headings

### ISSUE THREAD

**Issue by 7eopard** [siyuan-note/siyuan#9264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Pressing delete at the beginning of a heading, which is transformed with subtitles, cause unexpected result in structure below:

```
* list item

# a heading at any level
```

recurrence steps:
1. theHeading.transformationWithSubtitles(anyOtherLevel)
2. make the cursor at the beginning of the transformed heading
3. press delete

### Expected result

the heading is turned into paragraph

### Screenshot or screen recording presentation

1. unexpected result after pressing delete: 
![image](https://github.com/siyuan-note/siyuan/assets/62825807/b3981b6f-194e-470e-bafe-cfc5e5fdbe65)

2. unexpected result after pressing Ctrl+Z: 
![image](https://github.com/siyuan-note/siyuan/assets/62825807/63333767-91e9-41a7-a426-ba3247b1093c)

3. unexpected result after refresh: 
![image](https://github.com/siyuan-note/siyuan/assets/62825807/fa79aa46-c627-4883-9af9-375e3d15a73d)

### Version environment

```markdown
- Version: 2.10.6
- Operating System: W11 
- Browser (if used):
```

### Log file

no need

**Comment by zxhd863943427** [comment]
2.10.6, cannot be reproduced

https://github.com/siyuan-note/siyuan/assets/74853597/4fb9c6c2-1c97-4a34-8de1-13d222a3e524

**Comment by 7eopard** [comment]
> 2.10.6, cannot be reproduced

Transformation with subtitles should be excuted before pressing delete.

**Comment by zxhd863943427** [comment]
Still unable to reproduce, you need to record the screen to show your reproduction process

**Comment by 7eopard** [comment]
> Still unable to reproduce, you need to record the screen to show your reproduction process

check this:

https://github.com/siyuan-note/siyuan/assets/62825807/4743ed83-12d8-400a-a0fe-efb8c57ec932

![image](https://github.com/siyuan-note/siyuan/assets/62825807/2dd4f399-635c-4573-9b18-cb0cf2681ec6)

**Comment by 88250** [comment]
Thanks to your feedback, we have been able to reproduce the issue.
