### ISSUE TITLE
日程管理插件只能在插件市场里面更新

### ISSUE THREAD

**Issue by RogerHuHu** [siyuan-note/siyuan#9266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/3404169/53b753d7-c9fd-4919-9c28-5f337930a348)
如图，日程管理插件无法在已下载处更新，只能到插件市场里更新，是我上传的 package 有问题吗？

### Expected result

解决日常管理插件的更新问题

### Version environment

```markdown
- Version: 2.6.10
- Operating System: windows 10
- Browser (if used):
```

### Log file

I 2023/09/26 10:51:56 runtime.go:128: use network proxy [system]
I 2023/09/26 10:51:56 serve.go:119: kernel [pid=11812] http server [127.0.0.1:56839] is booting
I 2023/09/26 10:51:56 blocktree.go:448: read block tree [5.8 MB] to [D:\Documents\Notes\SiYuan\temp\blocktree], elapsed [0.02s]
I 2023/09/26 10:51:56 conf.go:710: database size [67 MB], tree/block count [411/20320]
I 2023/09/26 10:51:56 pandoc.go:132: built-in pandoc [ver=2.19.2, bin=D:\Documents\Notes\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/09/26 10:51:56 working.go:154: kernel booted
I 2023/09/26 10:51:56 conf.go:927: pandoc initialized, set pandoc bin to [D:\Documents\Notes\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/09/26 10:51:57 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
I 2023/09/26 10:51:58 box.go:79: auto stat [trees=411, blocks=20320, dataSize=557 MB, assetsSize=256 MB]
I 2023/09/26 10:51:58 disk.go:33: disk usage [total=1.0 TB, used=577 GB, free=423 GB]
E 2023/09/26 10:52:07 package.go:550: get bazaar package [https://oss.b3logfile.com/package/RogerHuHu/siyuan-plugin-schedule-manager.git@a07a762652e04dacb86ad0af08b4dcffb8487ae3] failed: 404

**Comment by 88250** [comment]
感觉是这里的地址不对：
![image](https://github.com/siyuan-note/siyuan/assets/873584/b4b50705-cd8b-4b17-b8d8-4e98d8623e6c)

试下参考其他插件包的 plugin.json 改改，然后重新发版新版看看。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
