### ISSUE TITLE
属性视图应该在移除项时同步移除仅属性视图引用的文档。

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当前版本在属性视图中新建并删除后，会出现一个无法看见，只能搜索的幽灵文档，这不符合用户的预期。

但是假如这个文档被其他文档引用后，则不应该删除。

### Expected result

第一种解决方案如标题所示。

第二种方案，或许可以在删除后使子文档可见？不过这会与我另一个issue冲突。

### Version environment

```markdown
- Version: 2.10.6
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志。

**Comment by 88250** [comment]
现在的设计是删除行以后不再隐藏文档块（移除文档的 custom-hidden 属性），我这里刚刚测试是正常的。

不过结合 https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1736545636 的考虑，这个 issue 先关闭，我们在那边讨论吧，谢谢。
