### ISSUE TITLE
PANIC RECOVERED: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#927]
### 描述问题 Describe the problem
似乎存在运行时错误
### 期待的结果 Expected result
找出原因修复可能出现的问题
### 版本环境 Version environment
* 版本 Version：0.5.5
* 操作系统 Operating system：Winndows 10
### 日志文件 Log
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/02 20:26:45 main.go:122: kernel [v0.5.5] is booting, runtime mode is [prod], working directory is [C:\Users\zhenghui\AppData\Local\Programs\SiYuan\resources], temp directory is [C:\Users\zhenghui\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/02 20:26:45 lang.go:67: initialized languages
D 2021/01/02 20:26:45 conf.go:88: loaded conf [C:\Users\zhenghui\.siyuan\conf.json]
I 2021/01/02 20:26:45 conf.go:172: local serve path [http://192.168.1.101:6806]
I 2021/01/02 20:26:45 conf.go:176: initialized conf
I 2021/01/02 20:26:45 main.go:164: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/02 20:26:45 webdav.go:36: initialized WebDAV server
D 2021/01/02 20:26:45 box.go:355: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
I 2021/01/02 20:26:45 conf.go:293: initialized notebook
I 2021/01/02 20:26:46 repo.go:39: initialized git repo
I 2021/01/02 20:26:48 setuilayout.go:43: set ui layout done
I 2021/01/02 20:26:51 setuilayout.go:43: set ui layout done
I 2021/01/02 20:26:54 process.go:71: ui process exited, exit kernel process now
I 2021/01/02 20:26:54 conf.go:224: exited kernel
I 2021/01/02 20:26:55 main.go:121: 
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/02 20:26:55 main.go:122: kernel [v0.5.5] is booting, runtime mode is [prod], working directory is [C:\Users\zhenghui\AppData\Local\Programs\SiYuan\resources], temp directory is [C:\Users\zhenghui\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/02 20:26:55 lang.go:67: initialized languages
D 2021/01/02 20:26:55 conf.go:88: loaded conf [C:\Users\zhenghui\.siyuan\conf.json]
I 2021/01/02 20:26:55 conf.go:172: local serve path [http://192.168.1.101:6806]
I 2021/01/02 20:26:55 conf.go:176: initialized conf
I 2021/01/02 20:26:55 main.go:164: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/02 20:26:55 webdav.go:36: initialized WebDAV server
D 2021/01/02 20:26:55 box.go:355: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
I 2021/01/02 20:26:55 conf.go:293: initialized notebook
I 2021/01/02 20:26:55 repo.go:39: initialized git repo
D 2021/01/02 20:34:49 box.go:379: unindexed note book [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
D 2021/01/02 20:34:49 box.go:355: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
E 2021/01/02 20:43:13 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 20:43:15 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 20:43:16 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 20:43:17 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 20:43:19 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 20:43:20 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 20:43:21 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

E 2021/01/02 20:43:22 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

D 2021/01/02 20:43:24 box.go:379: unindexed note book [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
D 2021/01/02 20:43:24 box.go:355: indexed notebook [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
E 2021/01/02 20:59:35 log.go:44: PANIC RECOVERED: runtime error: slice bounds out of range [:-1]
	D:/go1.15.2/src/runtime/panic.go:969 (0xb1bed5)
D:/go1.15.2/src/runtime/panic.go:98 (0xb19e69)
D:/88250/siyuan-src/kernel/model/search.go:153 (0x180bdd3)
D:/88250/siyuan-src/kernel/model/search.go:110 (0x180b1ea)
D:/88250/siyuan-src/kernel/model/search.go:69 (0x180ac10)
D:/88250/siyuan-src/kernel/model/search.go:34 (0x180a7a8)
D:/88250/siyuan-src/kernel/cmd/searchblock.go:21 (0x183328f)
D:/88250/siyuan-src/kernel/cmd/cmd.go:219 (0x1837279)
D:/go1.15.2/src/runtime/asm_amd64.s:1374 (0xb53420)

**Comment by 88250** [comment]
v0.5.6 修复，等发布以后请帮忙验证，谢谢。
