### ISSUE TITLE
属性视图创建新的块时，允许使用「创建新文档」之外的方案

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9270]
### In what scenarios do you need this feature?

> 这个 issue 我个人来看很重要，希望还是予以考虑。
> 如果觉得不方便很快实现，也可以放在 backlog 中作为长期的考虑。

目前属性视图在创建一个新的块的时候，默认会创建一个文档块。长远看这会带来生成大量小文件的问题。

例如：我想要使用属性视图来背单词，我可能会新建成百上千个单词，对应的就会有成百上千个几乎为空的小文件。长久积累下来的大量小文件肯定会造成一些**在文件系统层面不好**的影响。（还有心理上也觉得膈应）

### Describe the optimal solution

建议可以上用户在数据表格当中选择不同的新建行的策略。目前的策略是直接新建一个文档块，也可以给其他的策略选择。

比如，可以将一整个数据视图绑定一个独立的文档，然后每次新建一行，就在对应文档中新建一个段落块（也可以是别的类型）。这样就避免了大量小文件的问题。

**Comment by zxhd863943427** [comment]
附议。

**Comment by 88250** [comment]
能否考虑反过来使用以规避该场景的问题，比如先创建块，然后再拖拽到表中？或者考虑定期整理子文档，将其移动到某个文档中。

另外，关于创建文档是否隐藏可能需要先讨论清楚 https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1736545636

这个 issue 我们先关闭，暂时不考虑了（原因请参考上面的讨论链接），后期也许能够通过插件进行批量重构移动这些子文档，比如实现批量文档转换为标题，谢谢。

**Comment by zxhd863943427** [comment]
> 能否考虑反过来使用以规避该场景的问题，比如先创建块，然后再拖拽到表中？或者考虑定期整理子文档，将其移动到某个文档中。
> 
> 另外，关于创建文档是否隐藏可能需要先讨论清楚 [#9272 (comment)](https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1736545636)
> 
> 这个 issue 我们先关闭，暂时不考虑了（原因请参考上面的讨论链接），后期也许能够通过插件进行批量重构移动这些子文档，比如实现批量文档转换为标题，谢谢。

实际上就是感觉到这个步骤太繁琐了，才希望官方能提供更简便的操作方案……使用插件和定期整理都很麻烦。

另外，我观察到块中储存的属性实际上是无用的，无论是在块的属性菜单中还是属性列表中都完全不会用到，真的不能实现脱离块的属性列表行吗？

**Comment by frostime** [comment]
> 能否考虑反过来使用以规避该场景的问题，比如先创建块，然后再拖拽到表中？或者考虑定期整理子文档，将其移动到某个文档中。
> 
> 另外，关于创建文档是否隐藏可能需要先讨论清楚 [#9272 (comment)](https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1736545636)
> 
> 这个 issue 我们先关闭，暂时不考虑了（原因请参考上面的讨论链接），后期也许能够通过插件进行批量重构移动这些子文档，比如实现批量文档转换为标题，谢谢。

用户体验也是需要考虑的指标啊。「先创建块，然后再拖拽到表中」这个作为常规基础操作，有点太复杂了。

**Comment by 88250** [comment]
>另外，我观察到块中储存的属性实际上是无用的，无论是在块的属性菜单中还是属性视图中都完全不会用到，真的不能实现脱离块的属性列表行吗？

有用啊，Query 类需求就可以通过属性扩展了。

> 用户体验也是需要考虑的指标啊。

用户体验那是必须要考虑的，我们集中到 #9272 中讨论吧。

**Comment by zxhd863943427** [comment]
> > 另外，我观察到块中储存的属性实际上是无用的，无论是在块的属性菜单中还是属性视图中都完全不会用到，真的不能实现脱离块的属性列表行吗？
> 
> 有用啊，Query 类需求就可以通过属性扩展了。

没啥用……目前的思源本来用sql查询自定义属性就难，查询使用json类型的更难，查询不仅是json，而且名称全是id化的属性视图定制属性更是难上加难。

我们群里的算是比较熟练使用思源的用户了，但没有敢于使用思源这种类型的属性的，都是只能考虑自起炉灶，复用思源原有的块属性。

如果真要为用户的查询需要做考虑，我建议是sqlite里新建一个表，或者提供用名称查询的api，这个块属性里的属性视图属性真的没人用的了，不如删掉，以支持脱离块的属性视图。我相信如果能实现，所有用户只会拍手称赞，而不会对无法使用sql来查询目前的块属性视图属性表示遗憾。

**Comment by 88250** [comment]
删是不可能了啊，删了没有地方放数据了，后面要做模板列也就不可能了，这些设计都是牵一发动全身的，不可能现在这个时候还推翻重来了。

**Comment by zxhd863943427** [comment]
可是我看思源的实现是直接放到data/storage/av下啊，根本就不是储存在块中的，我在实验时直接全部删掉都不会影响。

**Comment by zxhd863943427** [comment]
模板列像现在这样直接从这个位置获取数据难道不可以吗？

**Comment by 88250** [comment]
`custom-av-key-` 好像确实可以删，但是其他属性不能删，删了的话从块这一侧就无法关联到数据库。

**Comment by zxhd863943427** [comment]
对，custom-avs是不能删的，这个是唯一标识到连接什么属性视图的。

但是在属性视图上新建的、没有关联到块的行，不需要这个属性，因为他们只会与当前的属性视图关联。这说明不管当初的设计意图是怎么样，思源在客观上已经实现了能够脱离块的属性视图的基础结构。

**Comment by leolee9086** [comment]
> 对，custom-avs是不能删的，这个是唯一标识到连接什么属性视图的。
> 
> 但是在属性视图上新建的、没有关联到块的行，不需要这个属性，因为他们只会与当前的属性视图关联。这说明不管当初的设计意图是怎么样，思源在客观上已经实现了能够脱离块的属性视图的基础结构。

复议，如果实现上已经是高度独立的，没有太大必要绑在一起

**Comment by 88250** [comment]
这里集中讨论吧 https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1736628110

**Comment by Zuoqiu-Yingyi** [comment]
既然如此，是不是属性表里面可以添加一种“块引用”的元素，这样一行可以与多个块建立连接

**Comment by 88250** [comment]
@Zuoqiu-Yingyi 好像是有可能的，这个后面再议，可以帮忙先开个 issue 记录。
