### ISSUE TITLE
When rebuilding the index, it is prompted that the block cannot be found

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#9271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

刚刚安装完v2.10.7，启动软件，进入主界面，重建索引，提示找不到块，但是索引好像还是正常重建了

然后我等跑完又重新点了再一次重建索引，好像又没有这个提示了，不知道具体里面有没有什么问题😂

### Expected result

重建索引存在块缺失时，稳定报错

### Version environment

```markdown
- Version: v2.10.7
- Operating System: Windows 11
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12726526/siyuan.log)

**Comment by zxhd863943427** [comment]
使用以下sql嵌入块查找缺失块：
```
select *
from blocks
where id in (
        select block_id
        from refs
        where not def_block_id in (
                select id
                from blocks
            )
    )
```
注意缺失可能是因为你关闭的对应的笔记本。

**Comment by 88250** [comment]
出现 未找到块 的提示是因为鼠标悬浮了引用后或者进行块打开操作后系统发现块找不到触发的，重建索引时应该不会提示才对，我先关闭了，请后续继续留意观察，如果能有稳定重现的步骤就更好了，谢谢。

**Comment by Temacc0531** [comment]
> 出现 未找到块 的提示是因为鼠标悬浮了引用后或者进行块打开操作后系统发现块找不到触发的

应该不是，我查出来是一篇很古老的文章里面引用的（根本没有打开），我后续再留意一下
