### ISSUE TITLE
Allows a doc to be dragged into its containing attribute view

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

把属性视图所在的文档，从文档树中拖到属性视图上，然后这个文档就直接没了

![av](https://github.com/siyuan-note/siyuan/assets/27268127/9d7fa774-1467-464b-8535-016bf0b7a38e)

文档树重新折叠展开一下，这个文档又出来了，但是里面变成了这个样子

![56d8067da7b754658ec73ef047700e9d](https://github.com/siyuan-note/siyuan/assets/27268127/65e2695b-78f0-4bda-9a36-2b0a42786d2d)

### Expected result

直接禁止把 root_id 的文档拖进来

### Version environment

```markdown
- Version: 2.10.7
- Operating System: win10
- Browser (if used): no
```

### Log file

无

**Comment by 88250** [comment]
看上去是因为拖拽放置的时候没有确切拖入到表格中，所以最后是文档转换为标题了。

@Vanessa219 看下能否改进一下放置点的判断？
