### ISSUE TITLE
属性视图细节问题

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#9274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

属性视图一些优化的问题：

I. 数字列
1. 数字列的辅助输入列宽过长，看起来非常的怪
2. 数字列的最小列宽限定的还是过于大了，这会让小屏幕用户使用起来比较难受。

II. 文本列
1. 无法渲染引用
2. 可以考虑添加 SiYuan 特色：虚拟引用功能

III. 单（多）选列
1. 配置问题，编辑的时候，面板很。。。空

IV, 选中行
1. 选中行后，selected 会影响数据库的命名
2. 只能点选，不能区间选，效率很低【文档树也是如此 ^_^】
3. [bug] 右键 → 属性 → block：对应没有任何响应
4. 右键菜单：不要用“删除”，用“移除”比较好；因为删除是真删了吗？想删的人担心没有删，不想删的人担心删了。

其他功能建议：
1. 新增ID列：
   将对应行的块ID / 超链接形式 / 引用 / 嵌入形式 渲染出来（因此形式可以切换）。本列数据只可复制，不可编辑。
   鼠标右键单击直接写入ID剪贴板（选中多个单元格则对选中的行做该操作）【其实拿ID的用处是快速拿到ID，配合API做事情】
2. 列排序 / 筛选的细节（参考最后两张图，最后一张图为飞书的细节，列顶会有提示，该列被做操作）

### Expected result

其实，已经做得很好了，继续加油，DV

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/54077803/04bbfc94-c8bb-425b-8361-ed8d1ae12693)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/13bdb754-ba29-4fe4-86a2-4467c3c9d649)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/be7f4cc4-b947-4547-9f5a-a5ad266d8db3)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/3f120ddb-145d-4e4c-830c-1c193990a48a)
![动画1](https://github.com/siyuan-note/siyuan/assets/54077803/f288ce1d-76e5-446a-975d-2135edae915c)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/22fdd21b-ae06-4126-8bd2-95860a496acd)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/83372f79-ada5-44a5-a7ef-fccadb598257)

### Version environment

```markdown
- Version: 2.10.7
- Operating System: win 10 22h2
- Browser (if used): 0
```

### Log file

0

**Comment by 88250** [comment]
关于“新增ID列”可参考 #8766

**Comment by LGRemdo** [comment]
> 感谢建议，关于“新增ID列”可参考 #8766 
> 
> 其他点我们需要时间逐步分析，暂时无法一一回复了，请多包涵。

没事，理解，辛苦，继续加油

**Comment by 88250** [comment]
关于 II. 文本列 仅支持纯文本这一点大概是不会变了，后面可能会引入单独的引用列 https://github.com/siyuan-note/siyuan/issues/9305 可能要等数据库正式上线以后再考虑。

**Comment by LGRemdo** [comment]
> 关于 II. 文本列 仅支持纯文本这一点大概是不会变了，后面可能会引入单独的引用列 https://github.com/siyuan-note/siyuan/issues/9305 可能要等数据库正式上线以后再考虑。
> 
> 

可是，这样不影响阅读吗？有的时候文本狂需要插入的片段就....

另外，文本框支持渲染latex吗？wolai的可以，飞书不想。所以，我不知道d大有没有这个打算，冒昧问一问

**Comment by 88250** [comment]
估计是支持不了，只能用纯文本。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月2日(周一) 凌晨0:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 属性视图细节问题 (Issue #9274)




  
关于 II. 文本列 仅支持纯文本这一点大概是不会变了，后面可能会引入单独的引用列 #9305 可能要等数据库正式上线以后再考虑。
  
可是，这样不影响阅读吗？有的时候文本狂需要插入的片段就....
 
另外，文本框支持渲染latex吗？wolai的可以，飞书不想。所以，我不知道d大有没有这个打算，冒昧问一问

**Comment by 88250** [comment]
选中行后，selected 会影响数据库的命名
只能点选，不能区间选，效率很低【文档树也是如此 ^_^】

这两点是设计如此。

---

[bug] 右键 → 属性 → block：对应没有任何响应

这一点是有问题的吧 @Vanessa219 

---

右键菜单：不要用“删除”，用“移除”比较好；因为删除是真删了吗？想删的人担心没有删，不想删的人担心删了。

暂时先这样，应该没有歧义。

---

列排序 / 筛选的细节（参考最后两张图，最后一张图为飞书的细节，列顶会有提示，该列被做操作）

尽量参考一下 @Vanessa219

**Comment by Vanessa219** [comment]
- [ ] 数字列的最小列宽限定的还是过于大了，这会让小屏幕用户使用起来比较难受。
- [ ] [bug] 右键 → 属性 → block：对应没有任何响应
- [ ] 配置问题，编辑的时候，面板很。。。空

> 列排序 / 筛选的细节（参考最后两张图，最后一张图为飞书的细节，列顶会有提示，该列被做操作）
目前有排序和筛选，对应的图标会高亮，点击后可查看细节。
