### ISSUE TITLE
文档树多选操作

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9275]
增强文档树体验：子文档全选操作

### In what scenarios do you need this feature?

我在一个父文档下面有许多子文档，但我想把底下所有的子文档都给放到别的地方，但思源中只能一个一个的选择（包括ctrl+左键），不能像别的软件那样shift+左键全选。
以及，把文档块作为闪卡时，如果选择多个文档块，可以再接在文档树中多个选择，然后右键（快速制卡），这样文档块在文档树中也能制卡，而不用再点进去打开再制卡

### Describe the optimal solution

像ob那样，能够全选子文档

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/6659

**Comment by gaoluji** [comment]
> Duplicate of #6659

@88250 还有就是在文档树直接对文档快速制卡
