### ISSUE TITLE
a part of file history is empty

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/31495943/27598591-6299-4c05-b145-d725e2f1c58b)

### Expected result

if the older file history can not be used, please remove them, instead of listing them in file history list

### Version environment

```markdown
- Version: 2.10.7
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
Hello, I have no data here to reproduce this issue. If it is convenient, please find the history file on the file system (workspace/history/) to see if there are any abnormalities.

**Comment by XinLi0111** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/31495943/b498b8c5-a93b-42f3-abf4-7b3e08d13524)
![image](https://github.com/siyuan-note/siyuan/assets/31495943/7768e18f-ee42-4d5b-af99-4312e450879c)

There only are history files after 2023-08-28 in `workspace/history/`, while the file history in single document show the empty history that earlier than 2023-08-28.

**Comment by XinLi0111** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/31495943/9be81192-5b6d-4129-ae32-699bb72ed7ac)

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/8ab60aea-0c4b-4569-9a36-4c32288cd792)

Can you upload the original file under history for testing?

**Comment by XinLi0111** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/31495943/89cec073-5810-4c2e-bac2-b80f3242a0f0)
![image](https://github.com/siyuan-note/siyuan/assets/31495943/7c453964-34fa-4488-963b-02551748d663)

find a reindex button in file history pane in picture 1, after reindex, the file history shows the right content.
and the reindex button of document tree in picture 2 is useless for file history.

So, do users have to reindex file history by hand after a perid time?

**Comment by 88250** [comment]
In some cases, the database index and the file system may be inconsistent (for example, the application is closed before the database index is executed). Rebuilding the index is mainly to keep the file system and the database consistent. Currently, it can only be performed manually by the user. There is no better solution. 

I can only close this issue now. If there is similar feedback later, we will try to link it here. Thank you for taking the time to try.
