### ISSUE TITLE
A more secure mechanism for deleting cited blocks to avoid losing information when the original block is deleted

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9277]
### In what scenarios do you need this feature?

Sometimes, when I try to click or hover a block reference, SiYuan tell me that can not find ID xxxx.

That's great terrible, because I can not rember what I have written under the original block in the long past.

Therefore,  could you please give me some advice or try to make the block deleting action more robust?

### Describe the optimal solution

when user try to delete the blocks that were cited in other place, give a dialog to show a warn of the risks of infomation lost.

### Describe the candidate solution

Or,  detecte whether the original  block is cited in other place, then store the snapshot of original block (maybe store them in a "deleted bak" file or folder?) and show a red warn message in top of the pop-up windows.

**Comment by 88250** [comment]
Normally it can be identified by the block reference count identifier.

![image](https://github.com/siyuan-note/siyuan/assets/873584/1843a035-a8e6-49c1-826d-1afd4d4c974a)

However, there are actually some situations that cannot be automatically detected. For example, after cross-notebook reference, the notebook where the definition block is located is closed. Therefore, detection and prompts cannot be made in these cases, and the user needs to make his own judgment.

I've closed this issue, thank you.
