### ISSUE TITLE
Change the style of anchor text will cause the repeat reference count mistake

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/31495943/e86533fa-e03f-44fb-876b-fab025c37e50)

### Expected result

Dose changing the style of anchor text allowed? 

Or, do not show the toolbar of selected anchor text (even shortkey?).

### Version environment

```markdown
- Version: 2.10.7
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
Hello, this part is designed so that a reference element will be split into multiple references if different elements are superimposed. There is no solution for the moment. You can only pay attention when using it. Don't use it like this. Thank you.
