### ISSUE TITLE
Improve attribute view menu style

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 思源目前的b3-menu都没有关闭按钮，属性视图的菜单却给了关闭按钮，我会误以为是清空而不是关闭菜单。
<img width="228" alt="a1639b3ad874beede17de046ce20a9e2" src="https://github.com/siyuan-note/siyuan/assets/125173405/269fc5de-bb25-4e73-82c0-76852e3f5ecb">

2. 这里应该排除下title，不需要应用cursor:point样式
<img width="263" alt="e5b84d9f53ac780712c1e75f832a6427" src="https://github.com/siyuan-note/siyuan/assets/125173405/c193fac5-5e12-4fc6-a02a-75f9f419cb27">

3. 属性视图的页签是不是给个新选择器会好一些？像item-full那样。

### Expected result

希望修改下细节

### Version environment

```markdown
- Version: 2.10.7
- Operating System:win 
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
1. 移除关闭按钮你
2. 修改为默认样式
3. 后期有多页签的话再看是否需要修改，目前修改的话有点不好看

<img width="982" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/fa446e4d-e3bc-499b-aa4e-9735f937f244">
