### ISSUE TITLE
调整属性-自定义-添加后按ESC键时关闭窗口的顺序

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9282]
### In what scenarios do you need this feature?

😵‍💫正常逻辑按ESC肯定是先把最后出现的窗口关掉啊，现在这样看着太奇怪了……

![CleanShot 2023-09-26 at 23 13 40](https://github.com/siyuan-note/siyuan/assets/50087596/8aea0b08-e7ba-4c89-8239-28d01d7784f1)

另外这样添加自定义属性太复杂了吧。以后应该会优化吧？
（我不用属性，只是今天点开看了看）

### Describe the optimal solution

*

**Comment by Vanessa219** [comment]
可以用快捷键或者 shift+click，其他更简单的办法目前还没有想出来。
