### ISSUE TITLE
Cut and copy operate on the entire block when text is selected

### ISSUE THREAD

**Issue by gdy106** [siyuan-note/siyuan#9283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

v2.10.7选中文字后用快捷键剪切会剪掉整个块

### Expected result

只剪切选中的文字

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/57566668/05f9b83f-6b9d-47f7-9582-038195bd070f

### Version environment

```markdown
- Version: v2.10.7
- Operating System: win10
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
关联 https://ld246.com/article/1695733792801

**Comment by alphatyy** [comment]
升级到2.10.8问题依旧（选中部分，剪切全部）。。。而且升级过程不顺利，提示无法停止某个文件，把旧版本2.10.7卸载后重新安装依旧如此。【2023-10-04，00:14】

**Comment by 88250** [comment]
@alphatyy 估计是升级不成功，试下完全卸载，把 Electron 相关的缓存都清理一下（具体路径请网络搜索）。

**Comment by alphatyy** [comment]
> @alphatyy 估计是升级不成功，试下完全卸载，把 Electron 相关的缓存都清理一下（具体路径请网络搜索）。

谢谢回复。又尝试了2遍才成功，似乎需要手动卸载后以管理员方式运行才可以。

**Comment by 88250** [comment]
这个可能和系统有关系吧，我个人是使用默认用户安装的。
