### ISSUE TITLE
拖动编辑器的标题到属性表中

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9286]
### In what scenarios do you need this feature?

目前可以从文档树中拖动，但是不能拖动编辑器的标题到表中

### Describe the optimal solution

允许拖动编辑器的标题，并插入到表中

**Comment by Vanessa219** [comment]
标题属于可编辑文本，一本可以编辑文本不适用于拖拽文本以外的操作。

**Comment by frostime** [comment]
> 标题属于可编辑文本，一般情况下可以编辑文本不适用于拖拽文本以外的操作。在此就不添加此功能了。

我是说标题旁边的 icon，那个也不能拖拽嘛

**Comment by zxhd863943427** [comment]
我倒是有另一个想法……上面横栏的标题能不能拖动到属性视图里？

**Comment by Vanessa219** [comment]
> 栏的标题能不能拖动到属性视图里？

哦，这个理论上是可以拖拽的，但是浮窗呀，向下滚动以后都没有了，不太实用。

**Comment by Vanessa219** [comment]
> 我倒是有另一个想法……上面横栏的标题能不能拖动到属性视图里？

这个我居然无法回绝，但是大部分软件都不这样操作，要做的话也要排到无事可做的时候了，到时候没 issue 的话记得来 at 我 😄

**Comment by frostime** [comment]
> > 栏的标题能不能拖动到属性视图里？
> 
> 哦，这个理论上是可以拖拽的，但是浮窗呀，向下滚动以后都没有了，不太实用。

但是**符合直觉**啊。我一开始使用视图的时候，发现块可以拖动到表里，下意识就拖动标题图标，然后才发现不能拖。

在普通用户眼里面，gutter 图标和标题 icon 是差不多的，既然前者能拖动那后者直觉上会觉得也能拖动。

**Comment by Vanessa219** [comment]
其他块标拖拽主要用来调节位置等，但文档标题这个块标和其他块标不太一样，它没有调节位置功能，如果只用到拖拽到数据表格上这个功能上的话，再加上以上不可见的场景，使用频率就比较低。

外加当前文档拖拽到当前数据表格，且数据表格和文档标题都显示在同一个屏幕内的概率也很小；如果要拖拽其他文档到数据表格中操作起来也会很麻烦。目前可以直接用添加，然后搜索引用会快捷方便很多，因此就先不添加了。
