### ISSUE TITLE
Delete attributes of related blocks when deleting database blocks

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9287]
https://ld246.com/article/1695780728736

**Comment by zxhd863943427** [comment]
需要考虑复制视图的引用情况。在视图引用不清零前不要删除。

**Comment by 88250** [comment]
目前复制数据库块是浅克隆（也就是引用），实际上其中的行指向的块的 custom-avs 属性是没有包含多个 av id 的，av id 都是一个。要判断的话只能遍历解析整个 data 下的 .sy 文件，从块的 custom-avs 上判断，感觉这个方法代价太高了，有点得不偿失。

换个思路就是用户手动清理，删除数据库的时候虽然没有关联删除块 avs，打开这个块属性面板后：

![image](https://github.com/siyuan-note/siyuan/assets/873584/b7605f1b-25e0-427d-a4c8-eac9d86c1428)

这里的 表格1 就是删掉的，这里加一个删除按钮，表示从这个库里面移除这一行（当前这个块），这样也算是能够清理了。你觉得呢？

**Comment by 88250** [comment]
重新考虑了下整体设计，这个地方还是不做删除吧，原因和闪卡类似，考虑到多种数据恢复的场景，无法做到强一致性，所以就还是让 custom-avs 属性冗余吧。

https://github.com/siyuan-note/siyuan/issues/9285 也存在类似的问题，以这边这条讨论为基础继续考虑。

**Comment by zxhd863943427** [comment]
这个设计我觉得可以，不过还得看看最终的效果怎么样。

另外，是否需要考虑当表内的行清零后删除属性视图？

**Comment by 88250** [comment]
> 另外，是否需要考虑当表内的行清零后删除属性视图？

不考虑啊，初始的时候就是空的。

**Comment by zxhd863943427** [comment]
好像也是……那有删除属性视图的设置吗？

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/9285#issuecomment-1747980285 用户手动删除行。

**Comment by zxhd863943427** [comment]
我是说数据库本身的哪个json，有删除的机制吗？

**Comment by 88250** [comment]
没有的，后面考虑看看能不能出个清理机制。



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 6, 2023 11:27 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Delete attributes of related blocks whendeleting database blocks (Issue #9287)




 
我是说数据库本身的哪个json，有删除的机制吗？
