### ISSUE TITLE
Support make flashcard on the doc tree

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9288]
还有就是在文档树直接对文档快速制卡

_Originally posted by @gaoluji in https://github.com/siyuan-note/siyuan/issues/9275#issuecomment-1736587082_

**Comment by gaoluji** [comment]
> 还有就是在文档树直接对文档快速制卡
> 
> _最初发布者 #[9275 （评论）](https://githubfast.com/siyuan-note/siyuan/issues/9275#issuecomment-1736587082)_

可以选中多个文档一块制卡
