### ISSUE TITLE
手机伺服的鉴权提醒

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9289]
### In what scenarios do you need this feature?

我很久没有使用过手机伺服了，今天使用伺服发现卡在页面进不去。看错误说是 Authorize 问题

![737721e95e249e5f37cb11b63fed3ffe](https://github.com/siyuan-note/siyuan/assets/27268127/b604af24-963c-4a17-a57f-5432c85da651)

问了一下群友，才知道原来现在手机伺服如果访问的是非 localhost 需要把鉴权码打开。连我都不知道要怎么做还需要问群友，可以想象普通用户遇到这个问题会有多迷茫。

### Describe the optimal solution

建议如果是遇到这种需要鉴权的时候，在启动页面悬浮一个提示「当前你在不安全的网络环境下使用伺服，请开启思源的鉴权码功能」。不然的话卡在页面真的会很迷茫。

![8f65eba6950521708091c4f0d8e204fa](https://github.com/siyuan-note/siyuan/assets/27268127/6257e2af-58ea-4d86-9c05-a0ad4f0ad573)

**Comment by 88250** [comment]
最新版应该是会提示的才对哦。

**Comment by frostime** [comment]
> 最新版应该是会提示的才对哦，类似这样：
> 
> ![image](https://user-images.githubusercontent.com/873584/270852263-357bc081-9592-4daa-88c3-9571f51bd5da.png)

额，我这边测试的时候，使用的是非 127/localhost 的 ip 访问，但是并没有弹出这个 alert

**Comment by 88250** [comment]
强制刷新一下看看。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月27日(周三) 中午12:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 手机伺服的鉴权提醒 (Issue #9289)




  
最新版应该是会提示的才对哦，类似这样：
 

  
额，我这边测试的时候，使用的是非 127/localhost 的 ip 访问，但是并没有弹出这个 alert
