### ISSUE TITLE
编辑文档删除被引用块上方块导致被引用块引用失效

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#929]
### 描述问题 Describe the problem
复现步骤
一、新建文档测试一
二、在测试一中列三个块标题一，内容一，标题二，内容二
三、新建文档测试二
四、在文档二中引用标题二
五、测试一中可以看到标题二被引用
六、选中内容一、用Backspace键删除
七，可以看到标题二的引用失效
八、测试二中可以看到引用ID无效

### 期待的结果 Expected result
等待修复
### 版本环境 Version environment

* 版本 Version：0.5.5
* 操作系统 Operating system：Windows 10

**Comment by 88250** [comment]
这个问题在 v1.2.0 中应该能够得到修复，感谢反馈。
