### ISSUE TITLE
将浮窗中的「Pin」按钮放在左边

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9290]
### In what scenarios do you need this feature?

每次想要钉住还得把鼠标移动到右边太麻烦了，把按钮放到左边的话鼠标指针稍微移动一下就可以点了，就很方便和正文之间的对照编辑。
<img width="1190" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/c5cdafe0-f1d4-44ee-b4f0-775848dc1b4a">

### Describe the optimal solution

「使用新窗口打开」「关闭」按钮维持放在右边即可，因为前者可以点击正文中的`[[引用]]`实现，后者有变通的实现方式——「取消钉住」然后把鼠标移到浮窗外面/按ESC键即可。

除此之外，我认为还应该加上一个逻辑：
钉住一个浮窗后，如果用户通过「点击正文中的`[[引用]]`将其使用新窗口打开」，那么此浮窗自动消失。

**Comment by gaoluji** [comment]
直接拖动也可以钉住

**Comment by LoneFireBlossom** [comment]
> 直接拖动也可以钉住

学到了，不过取消钉住没有这样方便的操作吧。

**Comment by chenshinshi** [comment]
丰衣足食，用css把空白部分删掉让按钮挤过去。

**Comment by LoneFireBlossom** [comment]
> 丰衣足食，用css把空白部分删掉让按钮挤过去。

1. 我太垃圾了，没这个本事，羡慕你们会鼓捣CSS
2. 我认为所有用户都会欢迎这个改动
3. 我认为既符合操作直觉、又能优化所有用户体验的事情应该让软件自己来做
4. 我觉得开发者改变这个按钮的位置应该很简单
5. 你的建议只能解决这个FR的一部分，这个FR后面还有一段（

**Comment by chenshinshi** [comment]
> > 丰衣足食，用css把空白部分删掉让按钮挤过去。
> 
> 1. 我太垃圾了，没这个本事，羡慕你们会鼓捣CSS
> 2. 我认为所有用户都会欢迎这个改动
> 3. 我认为既符合操作直觉、又能优化所有用户体验的事情应该让软件自己来做
> 4. 我觉得开发者改变这个按钮的位置应该很简单
> 5. 你的建议只能解决这个FR的一部分，这个FR后面还有一段（

.block__icon[data-type="pin"]{display:block;position:absolute}
![image](https://github.com/siyuan-note/siyuan/assets/125173405/21092af9-e403-45d4-ab88-ad576013115b)

啥是打开正文引用？

**Comment by chenshinshi** [comment]
别说自己垃圾，好像在骂我高傲……我只是提供d大不采纳本回答后的一种diy方式而已

**Comment by LoneFireBlossom** [comment]
> 啥是打开正文引用？
感谢


<img width="992" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/90f1952e-4fd1-46dd-bb3f-f20439bab938">

**Comment by chenshinshi** [comment]
如果是直接点击双链文本是通过新建签页打开不是新窗口。
现在是有两套逻辑，一种就是只针对悬浮窗的操作，悬浮窗可以独立钉选可以变为新窗口。
另一种是你说的情况：如果悬浮窗置顶后，用户通过双链文本打开新签页或者新窗口，悬浮窗不会受影响，这样也方便一些会开相同部分的窗口的人，比如可以同时编辑首尾，让首尾对照等情况。

**Comment by LoneFireBlossom** [comment]
有道理，那就只改📌位置吧

**Comment by royc01** [comment]
我反对改位置，改到左侧比较反直觉。

**Comment by chenshinshi** [comment]
楼主主要是假设悬浮窗正好从文本下方弹出的情况，其实思源很多时候悬浮窗不会恰巧在下方出现，是会计算最大空间的，有时向上弹有时向下弹，啊不过水平距离自然是左比右更近。

**Comment by LoneFireBlossom** [comment]
> 啊不过水平距离自然是左比右更近。

嗯，主要就是这个原因


> 我反对改位置，改到左侧比较反直觉。

是因为用Windows吗？
用过Mac就习惯按钮在左边了。
现在按钮在哪边我都无所谓，不怎么按这几个按钮主要用快捷键（但是pin没有快捷键）

**Comment by chenshinshi** [comment]
> 直接拖动也可以钉住

不拖动也行，悬浮窗的顶栏上右键按钮外任何位置都可以钉住，不过没有取消钉住的更方便操作

**Comment by 88250** [comment]
那暂时先这样了，我关闭 issue 了。

**Comment by LoneFireBlossom** [comment]
@88250 
我仍然认为需要改动。
这是Obsidian里实现浮窗编辑功能的插件，就是把pin放在左边的。
https://github.com/nothingislost/obsidian-hover-editor

”pin放在左边就是方便pin/unpin操作、鼠标移动距离短“这个理由绝对成立，没什么可反驳的。

楼上那位说反直觉，我说得不好听，建议改改自己的直觉。

**Comment by 88250** [comment]
这地方不太好决定，能不动就暂时不动了，改了位置已有用户会不习惯，等后面再继续收集反馈看看吧，感谢理解。

**Comment by chenshinshi** [comment]
啊不过现在置顶可以右键顶栏任何地方，取消钉住时就不是从正文的文本移动鼠标了距离差别应该也没那么大，我觉得已经不太影响提问人的体验了。而且我也给了代码，实在强迫症放左边也可以满足。

**Comment by chenshinshi** [comment]
因为取消钉住也有点像是关闭窗口，和关闭窗口放一起是不是更好（（（

**Comment by LoneFireBlossom** [comment]
@zxhd863943427 
https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1738412675

> 在我日常使用的window和linux平台中，使用右上角关闭都是一个被训练得自然习惯的方式。直到群里有人提醒我之前，我都不知道mac是左上角关闭的。

我提的这个issue不是把关闭按钮挪到左边，而是把pin按钮放到左边……
pin放到左边对浮窗来说是一个正常的选项。很简单，我认为这样总体上来说更方便浮窗的固定和取消固定了。

**Comment by zxhd863943427** [comment]
> 我提的这个issue不是把关闭按钮挪到左边，而是把pin按钮放到左边…… pin放到左边对浮窗来说是一个正常的选项。很简单，我认为这样总体上来说更方便浮窗的固定和取消固定了。

使用关闭作为例子是因为大部分软件都没有钉住这个功能，这个比喻确实不太恰当，造成了误解。我的意思其实是说，在我所使用的这些平台上，对窗口的默认操作按键都是分布在右上角的，如果新增一个功能按键，在默认情况下它也会被放在这个位置。

客观来说，放置在左上角确实有可取之处，至少固定和取消固定的时候不担心误触到关闭了，确实会更方便一点。但是目前更方便的固定方法是稍微拖动一下窗口，这样会自动固定。而浮窗的取消固定从达成的效果上看都是为了关闭浮窗，那么误触就无伤大雅了。

**Comment by LoneFireBlossom** [comment]
> 客观来说，放置在左上角确实有可取之处，至少固定和取消固定的时候不担心误触到关闭了，确实会更方便一点。但是目前更方便的固定方法是稍微拖动一下窗口，这样会自动固定。而浮窗的取消固定从达成的效果上看都是为了关闭浮窗，那么误触就无伤大雅了。

1. 如你所说，放在左上角有可取之处
2. 放在左上角也不影响习惯去右上角按❎的人按❎

所以综上不还是放在左上角更好么。


> 在我所使用的这些平台上，对窗口的默认操作按键都是分布在右上角的

1. 即使是windows，绝大部分软件右上角也同样有按钮，你可以点点软件图标看看。
2. 把PIN按钮放在左上和「对窗口的默认操作按键都是分布在右上角」没有冲突，PIN按钮基本上只是浮窗才需要的特殊操作
3. 我认为把PIN放在左上并不「反直觉」。什么叫反直觉？看这个issue： https://github.com/siyuan-note/siyuan/issues/9208 ，用户用了所有常见方式都没法调出设置面板才叫反直觉。PIN按钮放在左上所有人都能看到，看到就会用，
4. 我完全想不出把PIN放在左边对用户体验有任何负面影响。想右上角关的人就去右上角，习惯在右上角点PIN的人“把鼠标移动到右上稍微拖动一下窗口”就行了。我觉得好处远大于坏处。

**Comment by WingDr** [comment]
> 1. 如你所说，放在左上角有可取之处
> 2. 放在左上角也不影响习惯去右上角按❎的人按❎
> 
> 所以综上不还是放在左上角更好么

这个逻辑我是服气的

> 即使是windows，绝大部分软件右上角也同样有按钮，你可以点点软件图标看看。
> 把PIN按钮放在左上和「对窗口的默认操作按键都是分布在右上角」没有冲突，PIN按钮基本上只是浮窗才需要的特殊操作

浮窗不是窗口吗？pin不是对窗口的操作吗？左边放的一般都是对内容操作的菜单/按钮吧（文件、设置、显示等等）为什么单独一个pin就要区别对待？

> 我认为把PIN放在左上并不「反直觉」。

对你来说不反直觉，但是对我来说是反直觉的，因为我的Windows电脑里所有软件（没有“几乎”，就是所有软件）这种操作都是放在右上角的

> 我完全想不出把PIN放在左边对用户体验有任何负面影响。想右上角关的人就去右上角，习惯在右上角点PIN的人“把鼠标移动到右上稍微拖动一下窗口”就行了。我觉得好处远大于坏处。

我完全想不出把pin放在右边对用户体验有任何负面影响。想pin就拖动下窗口，解除的时候谁知道鼠标在哪，移动的距离也不会因为放在左边就变少，和关闭一起都在右边还能减少判断移动方向的思考（我到底是要取消钉住呢还是直接关掉呢？

总之，涉及到一些不同平台之间的操作习惯问题，**请不要将自己的操作习惯默认为所有人的操作习惯**，更何况你之前说的除了主观性的想法之外没有给出任何有足够说服力的技术性/逻辑性上的理由

最后，如何看待电脑版微信这种最大众的软件将pin按钮放在右上角的行为？如果你想的话我还可以举出很多软件的例子
![image](https://github.com/siyuan-note/siyuan/assets/63407442/64315ee3-f2bb-47fa-994b-484fa67c09ae)

**Comment by zxhd863943427** [comment]
> 所以综上不还是放在左上角更好么

我后半段的论述是说，尽管移动到左上角在我所叙述的角度来说确实有好处，但是这个好处从固定和取消固定的角度分别看都是不多的，并不足以做出决定把它移动到左上角。

> 把PIN按钮放在左上和「对窗口的默认操作按键都是分布在右上角」没有冲突，PIN按钮基本上只是浮窗才需要的特殊操作

如果你认为PIN按钮并不算是浮窗这个窗口的功能按键，那在这个话题我们很难继续进行沟通了……因为我想不到该怎么定义它的性质了。

> 我认为把PIN放在左上并不「反直觉」

直觉这个词语我觉得有点太含糊了，不利于讨论。具体到你提到的那个问题上，我觉得可以把这个意思描述成“基于以往经历期待软件能支持的操作”，而在这里，直觉更接近于“基于以往经历认为软件如此布局能方便操作”，你是否能认同？

> 我完全想不出把PIN放在左边对用户体验有任何负面影响。
这一部分我是否可以理解为“将按钮移动到左上角没有足够阻碍它的害处”？那自然也是成立的，但我希望你看到的是，无论是移动还是不移动，在功能性上，它的好处、坏处都不算多，这并不是足以决定结果的原因。

具体来说，就是我在承认“移动到左上角有如上所述的好处”、“移动到左上角没有其他未知、已知的坏处”这个条件的情况下，依然觉得不需要移动。这是看起来是不符合“有利则改”的逻辑的，但确实是我的真实想法。考虑再三，只能把这种意图归类为“使用习惯”，不知道你是否能够理解。

**Comment by LoneFireBlossom** [comment]
> 最后，如何看待电脑版微信这种最大众的软件将pin按钮放在右上角的行为？如果你想的话我还可以举出很多软件的例子 ![image](https://user-images.githubusercontent.com/63407442/271194030-64315ee3-f2bb-47fa-994b-484fa67c09ae.png)

你应该找的，是「浮窗窗口把PIN放在左上角的例子」，是浮窗，而不是软件主体的窗口。
思源的浮窗PIN只是在软件内部生效，而不是在整个系统内把这个窗口置顶。
思源的浮窗从来都是在鼠标处触发。
> 其实思源很多时候悬浮窗不会恰巧在下方出现，是会计算最大空间的，有时向上弹有时向下弹，啊不过水平距离自然是左比右更近。

我已经举了一个 https://github.com/nothingislost/obsidian-hover-editor 例子了。

当然只有上面这些还不够有说服力。

> 想pin就拖动下窗口，解除的时候谁知道鼠标在哪，移动的距离也不会因为放在左边就变少，和关闭一起都在右边还能减少判断移动方向的思考（我到底是要取消钉住呢还是直接关掉呢？

就不说细了，笼统地说：
用户为什么要取消PIN？很大概率是用户要关闭这个浮窗。注意这和你说的微信窗口的例子是不同的，用户要取消微信PIN不代表要关闭窗口，例如之前想看到微信的联系人列表顺便在word里打字，看完之后取消固定，只看一个群聊的聊天内容（联系人列表被word盖住了）。还是之前说的，“思源的浮窗PIN只是在软件内部生效，而不是在整个系统内把这个窗口置顶。”
基于「取消PIN约等于关闭浮窗」这个逻辑，反正右上角有一个关闭了，多放一个PIN对于取消PIN又有什么用呢？放在左上角，至少提供了左上、右上两个位置关闭窗口的方式，这就比现在更好。

**Comment by LoneFireBlossom** [comment]
> 具体来说，就是我在承认“移动到左上角有如上所述的好处”、“移动到左上角没有其他未知、已知的坏处”这个条件的情况下，依然觉得不需要移动。这是看起来是不符合“有利则改”的逻辑的，但确实是我的真实想法。考虑再三，只能把这种意图归类为“使用习惯”，不知道你是否能够理解。

可以看我楼上的说法，感觉我想说的理由差不多就这些，算是总结了一下？

我理解你的想法了。我提的这个issue确实很小。

**Comment by LoneFireBlossom** [comment]
> 补充一个盲区：如果你是喜欢把大纲面板放在右侧然后用大纲中的h1 h2符号打开标题悬浮窗的话右侧离你最近因为弹窗没有空间只能往左弹。这也是许多人的使用场景。

学到了，不过pin放在左上我觉得不影响：
想pin住就稍微拖动一下窗口。
取消pin就点关闭。

**Comment by chenshinshi** [comment]
> > 补充一个盲区：如果你是喜欢把大纲面板放在右侧然后用大纲中的h1 h2符号打开标题悬浮窗的话右侧离你最近因为弹窗没有空间只能往左弹。这也是许多人的使用场景。
> 
> 学到了，不过pin放在左上我觉得不影响： 想pin住就稍微拖动一下窗口。 取消pin就点关闭。

所以对你来说，悬浮窗打开后最方便的是鼠标直接去左边寻pin键将他钉在原处，而不是去移动他的窗口调整窗口大小吗？这个才是我的更经常的使用场景。我是不会先去pin它的，我会先挪动窗口找位置放。
取消pin和关闭不是一回事，取消pin后你还可以在窗口内编辑，我经常是挪动了窗口后被迫触发pin，然后我还得多一步取消pin。

**Comment by chenshinshi** [comment]
我本来以为你会用多数和少数来分析，没想到你直接答没影响，取消pin并不存在左右侧距离更近的问题，只有pin是存在你说的左右侧距离更近，你给出的理由是这样可以让两边都能关窗口，这个理由真的有点孤单，他最多只是一种负作用而不是采纳的理由。
那么放左还是右？如果你是挪窗口派的话对你没有影响。

**Comment by chenshinshi** [comment]
直线距离好测量，可是如果要讨论人用鼠标到底习惯往右上还是左甩和挪动就是复杂的问题了。上面的情况，即便我挪窗口我的鼠标并不会直线向下上找顶栏而是会有右边的偏移，大约落在顶栏中间位置，然后取消pin我直接去寻右上角。

**Comment by chenshinshi** [comment]
还有一个问题之外的建议，你对主题、插件的开发者提建议都很友好，会道谢，可是我和roy都是主题开发者，甚至你还在roy下面提过issue，可为什么我们开始平等的讨论问题时你就有些说话难听了，你自己也说了“说话难听点他应该改他的直觉”，我们对你没有敌意也不是要否定你的想法，我们是在共同讨论一个答案。

**Comment by LoneFireBlossom** [comment]
> 所以对你来说，悬浮窗打开后最方便的是鼠标直接去左边寻pin键将他钉在原处，而不是去移动他的窗口调整窗口大小吗？这个才是我的更經常的使用場景。我是不會先去pin它的，我會先挪動窗口找位置放。 

比起移动浮窗位置，我更喜欢滚动正文，因为只是简单编辑。要是编辑很长的内容、复杂编辑干脆打开单栏/双栏新页面就好了。所以思源是否支持直接分栏打开新页面（例如按住cmd键点击双链就分栏打开）？电脑没电了试不了

> 取消pin和关闭不是一回事，取消pin后你还可以在窗口内编辑

在我的理解中如果需要pin是这样的：
显示浮窗，（无论按钮，拖动，调整大小）pin，编辑，编辑完成关闭浮窗（无论叉号还是取消pin）。
pin后取消pin就意味着不打算再关注这个浮窗了，鼠标移出浮窗浮窗很快就消失了。
既然想“继续在浮窗内编辑”那为何还要取消pin呢？编辑完再取消pin啊


> 我经常是挪动了窗口后被迫触发pin，然后我还得多一步取消pin。

这个问题解决起来更简单了
提issue，让思源支持焦点在浮窗中时用与“关闭标签页”相同的快捷键关闭浮窗。这样你编辑完之后按一下快捷键立刻就关上了，符合习惯，比鼠标更快捷，我也赞成。

顺带，那么pin用快捷键呢？还不太一样，pin有可能只是浏览+与正文对比。
当然pin能快捷键的话也很好。**我支持所有的操作都允许用户自定义快捷键。**

> 取消pin并不存在左右侧距离更近的问题，只有pin是存在你说的左右侧距离更近，你给出的理由是这样可以让两边都能关窗口，这个理由真的有点孤单，他最多只是一种负作用而不是采纳的理由。

类似本文第一条，很多时候我不拖动浮窗，“悬浮窗打开后最方便的是鼠标直接去左边寻pin键将他钉在原处”。
至于你说的负作用我则没看懂是什么意思。


> 可是如果要讨论人用鼠标到底习惯往右上还是左甩和挪动就是复杂的问题了。上面的情况，即便我挪窗口我的鼠标并不会直线向下上找顶栏而是会有右边的偏移，大约落在顶栏中间位置，然后取消pin我直接去寻右上角。

pin放在左上角你依然能去右上角取消pin（也就是关闭）啊，效果不变
你习惯鼠标“落在顶栏中间位置”那拖动一下浮窗就pin了，pin放在哪一边都不影响

> 可为什么我们开始平等的讨论问题时你就有些说话难听了，你自己也说了“说话难听点他应该改他的直觉”

他是特例，一个人想要参与讨论应该说清楚他的理由，而不是只写一句不清不楚的话。表达反对但是一击脱离，我都不知道他说的反直觉是什么，回复他过了一夜也没有回应，这人真的是想讨论吗？我没有办法每句话都说得特别客气。
除了这一句我没有其它任何说的重一点的话了。顺带，我认为一句话末尾加上句号比不加标点语气要柔和，一句话加上正向的emoji语气比不加要柔和，但我一般不用，因为我讨厌这样，这么发展下去就是日语里那一大坨恶心的敬语了，我不喜欢说话要带一大串敬语。
我提issue都要认真写好久，那几个稍微长点的issue写了1到3小时不等（所以我说提issue折磨），提交之后还要再看好几遍可能会有多次编辑记录，即使如此还是可能有时候表达不精确。
真正说话难听的是上面某一层对我的回复，我对他的回复也没任何难听的，你应该是对我没有敌意但我不知道那位有没有敌意。

**Comment by royc01** [comment]
呃。。前面你回复已经说了是习惯问题，我觉得话题已经可以结束了吧？我就没有回了。我纯懒癌发作，不要太在意。我也没有什么都聊到底的习惯，或者你来群里面混混，一直都是友好交流的，不存在敌意。

**Comment by LoneFireBlossom** [comment]
> 呃。。前面你回复已经说了是习惯问题，我觉得话题已经可以结束了吧？我就没有回了。我纯懒癌发作，不要太在意。我也没有什么都聊到底的习惯，或者你来群里面混混，一直都是友好交流的，不存在敌意。

不是指你，我没去那一楼复制链接是因为手机上编辑很不方便 我怕窗口编辑的文字都丢了。
