### ISSUE TITLE
Add the data-href attribute to the link in the attributes view

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

现有的主题以及插件识别链接种类新增文字颜色样式和图标都是靠data-href判断，但数据库中的链接只有文本，可不可以加一个data-href属性，内容即链接本身，这样也方便主题适配？这样也可以延续之前用表格当数据库放链接可以显示图标的习惯，不会有割裂感。

### Expected result

希望增加data-href属性

### Version environment

```markdown
- Version: 2.10.7
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
目前已加，但是没效果，估计主题还需要再改改才行
