### ISSUE TITLE
关于「内置属性」「数据库属性」「自定义属性」的讨论

### ISSUE THREAD

**Issue by LoneFireBlossom** [siyuan-note/siyuan#9292]
### In what scenarios do you need this feature?

因为想说的不局限在这两个主题内，所以单开一个帖子。
[关于属性视图创建文档和关联块属性的讨论 · Issue #9272 · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/9272)
[属性视图反馈 - 链滴](https://ld246.com/article/1695732053015)

<img width="903" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/e80959f6-abe0-467d-9a60-1ce20acd6b58">

# 「内置属性」和「自定义属性」应该统一起来吧？

先不讨论数据库属性。
内置属性和自定义属性，对用户来说有什么区别吗？

我觉得Obsidian的实现方式就很好：每次都让用户自己新增一栏，下拉菜单给出所有内置的+自定义过的属性，给出输入提示。
![CleanShot 2023-09-27 at 13 16 49](https://github.com/siyuan-note/siyuan/assets/50087596/e915311d-bf28-4abb-bfb7-30569b4b82e3)
我不懂为何要把这两个东西分栏展示。

开发者大大可以看下：[Properties - Obsidian Help](https://help.obsidian.md/Editing+and+formatting/Properties)

> Obsidian supports the following property types:
>
> * **Text**
> * **List**
> * **Number**
> * **Checkbox**
> * **Date**
> * **Date &amp; time**
>
> Once a property type is assigned to a property, all properties with that name are assumed to have the same property type.

>  For the name, you can choose anything you like. Note that Obsidian provides several default properties:** **`tags`**​**,** **`cssclasses`**​**, and** **`aliases`.
>
> Once you choose the property name, you can give it a value.

> ## Default properties
>
> Obsidian comes with a set of default properties:
>
> | Property | Description                                  |
> | ---------- | ---------------------------------------------- |
> | `tags`         | See [Tags](https://help.obsidian.md/Editing+and+formatting/Tags).                                        |
> | `aliases`         | See [Aliases](https://help.obsidian.md/Linking+notes+and+files/Aliases).                                        |
> | `cssclasses`         | Allows you to style individual notes using [CSS snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets). |

# 支持「数据库行不绑定块」

> [https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1736628110](https://github.com/siyuan-note/siyuan/issues/9272#issuecomment-1736628110)
>
> 另外，如果数据库行不绑定块，类似 Notion 那样点击 Open 才创建可能是最优解，一方面解决了无故创建子文档的问题，一方面又能支持“轻量化表格”需求，看似很不错，是否可行我们还需要分析看看。

我支持这个想法。

**如果这一行没有绑定块，那这一行就是多维表格；如果绑定了或者新创建了块，那这一行就是属性视图，这一行的属性都要归属在这个块上。**

# 属性视图，数据库属性和其它属性应该统一起来吧？

例如有两个块：「千与千寻」「你的名字。」，我将千与千寻添加属性「导演」：「宫崎骏」。

下面是database：

|            | 1. 下拉菜单中应有「导演」选项。如果这里选择「导演」                                               |  |
| ------------ | ----------------------------------------------------------------------- | -- |
| 千与千寻   | 2. 那么这里会立刻显示「宫崎骏」。                                     |  |
| 你的名字。 | 3. 这里输入「ABC」的话会在「你的名字。」上附加「导演」：「ABC」的属性。 |  |

另外：

1. 我希望一眼看到所有属性。而不是还要点击「数据库属性」才能看到别的属性。
2. 我不希望整出一个这样分数据库展示的视图：
![image](https://github.com/siyuan-note/siyuan/assets/50087596/297cba61-0843-4f35-823e-63985aa62d70)
**注释「某某属性在哪个数据库中被用到了」的任务，应该交给反链面板。**

# 在块上展示所有属性

**把属性放在右键菜单里太难用了。添加、删除、浏览都不方便。**

* 非浮窗

  * 如果是一个页面块，那么在顶部展示所有属性，支持直接编辑、添加、删除属性。
  * 如果是其它块，那么聚焦这个块时在顶部展示所有属性，支持直接编辑、添加、删除属性。
* 浮窗

  * 在浮窗中是否展示属性由用户自己决定，在设置中弄一个开关选项。

> * 文档属性显示在顶部还需要考虑，近期暂时不会安排

想知道是什么原因导致还需要考虑？

# 书签单独列出

书签（对某些用户来说）是一个特别常用的功能，不应该和其它属性放在一起。或者说，应该有一个更快捷的设置书签的方式，比如放在右键菜单的首位、可以用快捷键设置。

### Describe the optimal solution

*

**Comment by suka233333** [comment]
呃   俺也一样。。！

**Comment by 88250** [comment]
属性需要区别对待，至少要区别内置属性和自定义属性的，数据库的属性正在考虑是否要移除。关于属性面板的设计是要保持统一，因为思源中所有块都可以添加属性，不只是文档块。


这个就在 https://github.com/siyuan-note/siyuan/issues/9272 中集中讨论吧，谢谢。
