### ISSUE TITLE
属性视图多选标签支持光标在两个标签间

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/125173405/f896b885-5f14-4a07-a4d1-3692c960e954)
比如现在的情况，给了关闭键可以不用光标退回去删除之前的标签，但没法在已有的标签间创建新标签。
这种需求可能是为了这种情况：用户想在本行自定义排序（不是应用于全局的升序降序），就像把新标签放在中间，但是现在就只能是先删除再添加。

### Expected result

但好像看了看notion也不支持……嗯，如果d大愿意考虑的话

### Version environment

```markdown
- Version: 2.10.7
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
大部分产品没有做这个可能是由于实现成本高过高，我们目前阶段就先不考虑了。后面没有 issue 的话可以 at 我再进行添加。谢谢。
