### ISSUE TITLE
块在剪切粘贴中能保持id不变

### ISSUE THREAD

**Issue by Tokubara** [siyuan-note/siyuan#930]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

对文档重构的时候需要调整块的位置. 比如原来的文档太大, 把内容剪切到新的文档中, 此时块id会发生变化. 那么各处对这些块引用都会失效.

### 描述最优的解决方案 Describe the optimal solution
希望剪切块的时候, 也含有块id信息. 粘贴一个被剪切的块所得到的块, 与原来的块id相同, 保证各处引用不失效.

**Comment by 88250** [comment]
你好，粘贴多次如果不重新生成 id 的话会重复。拆分请使用标题块转换文档块特性，谢谢。

**Comment by Tokubara** [comment]
argue一下, 粘贴多次是非法的, 如果检测到这个块id已经存在, 就不粘贴, 总之保证块的id是唯一的. 
正常使用情况也是剪切粘贴, 而不是重复粘贴, 因为目的就是修改内容顺序.
想要调整一个块在文档中的位置, 可以拖拽而保持id不变, 但我觉得调整到比较近的位置是方便的, 长距离拖动还是麻烦的.

或者等价这样操作, 直接在块的菜单提供对块的cut和paste block(区别于普通的粘贴)操作, 这种操作和拖拽等价, 不改变id.

**Comment by Tokubara** [comment]
当然, 可能说, 如果有了拖拽, 还要cut paste干啥呢, 拖拽有两个局限:
1. 长距离拖拽有点难受
2. 不能跨文档
所以我觉得cut paste是解决重复问题的一个不错的方法

**Comment by 88250** [comment]
跨文档后续会支持的，请等待几个版本，谢谢。
