### ISSUE TITLE
Attribute view line wrapping issues

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#9303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

属性视图单元格中的内容换行存在如下问题
The following issues exist with content wrapping in attribute view cells

- 文本单元格开启多行模式后未在 `textarea` 中换行的位置换行
  The text cell do not wrap at the position of the line break in the `textarea` after multi-line mode is turned on
- 文本单元格输入框 `textarea` 无法使用 `Enter` 或 `Shift + Enter` 换行
  The text cell input box `textarea` cannot be wrapped using `Enter` or `Shift+Enter`

### Expected result

- 文本单元格输入框 `textarea` 使用 `Enter` 或 `Shift + Enter` 换行
- 文本单元格开启多行模式后在 `textarea` 内容换行的位置换行

### Version environment

```markdown
- Version: 2.10.7
- Operating System: 
- Browser (if used):
```

### Log file

NULL

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 文档块属性编辑面板 > 数据库页签 > 文本类型的字段编辑框 也应该同步支持换行

**Comment by Vanessa219** [comment]
> @Vanessa219 文档块属性编辑面板 > 数据库页签 > 文本类型的字段编辑框 也应该同步支持换行

2.10.9 中改进
