### ISSUE TITLE
PDF 矩形标注复制到笔记中未识别为链接

### ISSUE THREAD

**Issue by hscui** [siyuan-note/siyuan#9308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在PDF文件中矩形标注后，点击选择 复制标注后，在笔记中粘贴时，会形成类似 <<assets/某某书.pdf/20230928154058-rr0ck5e "某某书.pdf-P34-20230928154058">> 的文本 ，以前应该是形成链接，点击后会跳转到PDF标注页。
![图片](https://github.com/siyuan-note/siyuan/assets/7949195/04c0da1f-538c-4659-8909-f5bf34d00c36)
此现象在默认主题下也复现了。

### Expected result

修复此BUG

### Version environment

```markdown
- Version: 2.10.7
- Operating System: WIN10 22H1
- Browser (if used):
```

### Log file

LOG无法上传

**Comment by 88250** [comment]
你好，我这里无法重现问题，请发一下该 PDF 文件给我 845765@qq.com

**Comment by hscui** [comment]
我明白问题出在哪里了，与pdf文件无关，与我对pdf的操作有关：
这个pdf文件最开始我是直接拖入思源笔记的，此时思源笔记会把pdf文件复制到assets目录下，然后将文件名最后加上校验码；出于洁癖和文件管理的目的，我把文件名的校验码那段删除了，同时修改了思源笔记的链接，将其指向无校验码的文件；这样处理后在思源笔记中能正常查看，但想做标注时应该就与思源自身记录不符了，导致无法识别此pdf，进而形成不了链接。


D ***@***.***> 于2023年9月28日周四 16:38写道：

**Comment by hscui** [comment]
> 你好，我这里无法重现问题，请发一下该 PDF 文件给我 [845765@qq.com](mailto:845765@qq.com)

我明白问题出在哪里了，与pdf文件无关，与我对pdf的操作有关：
这个pdf文件最开始我是直接拖入思源笔记的，此时思源笔记会把pdf文件复制到assets目录下，然后将文件名最后加上校验码；出于洁癖和文件管理的目的，我把文件名的校验码那段删除了，同时修改了思源笔记的链接，将其指向无校验码的文件；这样处理后在思源笔记中能正常查看，但想做标注时应该就与思源自身记录不符了，导致无法识别此pdf，进而形成不了链接。

此问题可以关闭了。
