### ISSUE TITLE
Apply result optimized by FSRS optimizer

### ISSUE THREAD

**Issue by qiuqiao** [siyuan-note/siyuan#9309]
应用FSRS optimizer优化后的复习参数

### In what scenarios do you need this feature?

现在思源的复习记录已经可以通过插件mdzz2048/siyuan-plugin-export-revlog导出，并使用FSRS optimizer计算出优化后的参数，但思源目前不支持使用优化参数。

参数的优化是相当重要的，最新的FSRS算法经过参数优化后可以和supermemo 18的算法媲美。

### Describe the optimal solution

可以在闪卡设置界面里填写优化后的参数。

具体而言，我希望能直接把python版FSRS optimizer的输出（是一个json数据）直接粘贴到设置界面，而不是一个参数一个参数地填写，因为这样比较方便。

数据格式请参见mdzz2048/siyuan-plugin-export-revlog。

### Describe the candidate solution

当然了，要是思源能内置FSRS optimizer就好了。可以一键运行并自动设置参数，还可以定时运行等。不过这个的实现可能比较困难，开发者也没有精力。

**Comment by L-M-Sherlock** [comment]
方便给一份导出的数据吗？我打算在 huggingface 上支持思源导出的 csv 格式的数据：

https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_app

**Comment by 88250** [comment]
@L-M-Sherlock 好像是个 JSON https://github.com/mdzz2048/siyuan-plugin-export-revlog/issues/1#issuecomment-1738768762

**Comment by L-M-Sherlock** [comment]
这个 JSON 是参数。我想要一份导出的复习数据，应该是 csv 的。

**Comment by 88250** [comment]
哦哦，召唤作者 @mdzz2048

**Comment by qiuqiao** [comment]
话说回来，思源的“Next Day Starts at ”是可设置的吗？如果不是，那么默认参数是什么？进行优化时好像需要输入这个

**Comment by L-M-Sherlock** [comment]
默认是 4，一般取你正在熟睡的时间。

**Comment by 88250** [comment]
@L-M-Sherlock 叶神帮忙看看，这个 JSON 优化结果是不是直接对应的就是 https://github.com/open-spaced-repetition/go-fsrs/blob/main/params.go

**Comment by mdzz2048** [comment]
---Original---
From: ***@***.***&gt;
Date: Thu, Sep 28, 2023 17:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Apply result optimized by FSRS optimizer(Issue #9309)




 
哦哦，召唤作者 @mdzz2048

**Comment by mdzz2048** [comment]
抱歉，数据文件在电脑上，晚一些发给您

**Comment by L-M-Sherlock** [comment]
> @L-M-Sherlock 叶神帮忙看看，这个 JSON 优化结果是不是直接对应的就是 https://github.com/open-spaced-repetition/go-fsrs/blob/main/params.go

这个是 fsrs-optimizer 在 CLI 里面运行的输出。如果是 GUI 的话，一般只会输出 [0.4, 0.6, 2.4, 5.8, 4.93, 0.94, 0.86, 0.01, 1.49, 0.14, 0.94, 2.18, 0.05, 0.34, 1.26, 0.29, 2.61]。

**Comment by L-M-Sherlock** [comment]
<img width="721" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32575846/9eeb7820-b2f2-4123-8717-07a2621e40da">

Anki 里的 FSRS 配置如上。

**Comment by 88250** [comment]
@L-M-Sherlock 我没理解错的话，按照字段名直接初始化 go-fsrs 参数应该没问题吧？

**Comment by L-M-Sherlock** [comment]
直接填 JSON 吗？我不确定，最好还是有几个栏让用户填吧。 RemNote 也是这样的：

<img width="691" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32575846/777941ce-af39-43b5-bbac-d9914ba301ec">

**Comment by 88250** [comment]
嗯，懂了，多谢多谢。



---Original---
From: "Jarrett ***@***.***&gt;
Date: Thu, Sep 28, 2023 17:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Apply result optimized by FSRS optimizer(Issue #9309)




 
直接填 JSON 吗？我不确定，最好还是有几个栏让用户填吧。 RemNote 也是这样的：

**Comment by qiuqiao** [comment]
> 能不能填个 0，不然我这边读出来是 NaN，一个 dropna，数据全没了。

fillna不行吗？

**Comment by mdzz2048** [comment]
> > 思源持久化的复习数据是这样的，review_duration 那列没有数据
> 
> 能不能填个 0，不然我这边读出来是 NaN，一个 dropna，数据全没了。

好的，插件这边改好了。

[revlog.csv](https://github.com/siyuan-note/siyuan/files/12751386/revlog.csv)

**Comment by L-M-Sherlock** [comment]
https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_app

可以用了：

<img width="1254" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32575846/85172cf2-6586-48f5-85e1-90aa9642dac5">

直接上传 CSV 文件，然后选一下 timezone，点击优化，稍等片刻，就有优化参数了。
