### ISSUE TITLE
改进 HTML 转换 Markdown 时加粗、斜体等空格的处理

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#931]
### 描述问题 Describe the problem
思源目前自带网页转换为Markdown功能，使用了一下，
和 Web Clipper 浏览器网页提取插件相比，还有一些不完善的地方,
存在部分格式提取不完整，需要手动编辑的情况。

### 期待的结果 Expected result
1. 思源网页提取Mardown能尽量保持网页的效果
2. 当前先用Web Chipper顶顶，需求不紧急，但还是希望能逐步完善优化

### 截屏或录屏演示 Screenshot or screen recording presentation

使用Web Chipper 提取网页，并保存为Markdown：
![图片](https://user-images.githubusercontent.com/15924513/103481405-c917ec00-4e15-11eb-919e-cc6797af347c.png)

**提取效果对比**：
> 左边是思源网页提取，粗体末尾部分没有填充空格，导致不能渲染，需要手动编辑
> 右边是Web Chipper提取，格式基本和原网页保持一致
![左边思源提取，右边插件提取](https://user-images.githubusercontent.com/15924513/103481310-1e073280-4e15-11eb-913e-b67ced1a8517.png)

### 版本环境 Version environment

* 版本 Version：0.5.5
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：FireFox 78.6.0esr (64位)

### 更多信息 More information

Web Chipper GitHub 地址：https://github.com/webclipper/web-clipper
测试网页地址：https://mp.weixin.qq.com/s/X73t6xssTe2u3PuXvbkDLg

**Comment by 88250** [comment]
看上去主要问题是行级排版元素包含中文标点，闭合标记符后面缺失空格导致没有解析成功，估计需要自动补充个空格进去。
