### ISSUE TITLE
Improve the layout of the bottom dock

### ISSUE THREAD

**Issue by Zuoqiu-Yingyi** [siyuan-note/siyuan#9310]
### In what scenarios do you need this feature?

当前侧边栏的布局如下图所示, 这里面有一些问题
The layout of the current dock is shown in the figure below, and there are some problems

- 左右侧边面板中的内容以纵向的列表为主, 需要更多的纵向显示面积, 但是现在会被底部停靠栏占用一部分
  The content in the left and right side panels is dominated by portrait lists, which require more portrait display area, but are now partially occupied by the bottom dock
- 底部停靠栏中的内容以横向为主, 虽然需要较宽的显示面积, 但是目前的宽度过剩
  The content in the bottom dock is mainly horizontal, and although a wide display area is required, the current width is excessive

![无标题](https://github.com/siyuan-note/siyuan/assets/49649786/5b6899a7-4cfd-4908-b43b-c2f2e4a2c0c2)

### Describe the optimal solution

根据窗口可视区域的形状自动调整底部停靠栏的布局
Automatically adjusts the layout of the bottom dock based on the shape of the window's viewable area

窗口宽度大于高度 | width > height

![无标题](https://github.com/siyuan-note/siyuan/assets/49649786/5e994bfb-e905-49ac-a792-5da884feafe3)

窗口宽度小于高度 | width < height

![无标题](https://github.com/siyuan-note/siyuan/assets/49649786/b64d9e66-cba9-4535-af72-80f06fa9d3e9)

**Comment by Vanessa219** [comment]
这样在拖拽过程中会跳动，面板不够稳定。

https://github.com/siyuan-note/siyuan/assets/970828/ed9d15b5-1c69-4ebe-9ba3-d052e3f99f1a


这个布局会觉得左右两栏太过细长

![image](https://github.com/siyuan-note/siyuan/assets/970828/84569e98-e71f-4ee8-850b-e915341f99f6)


基于以上就先不进行改进了。

**Comment by Zuoqiu-Yingyi** [comment]
> 这个布局会觉得左右两栏太过细长
> 
> ![image](https://user-images.githubusercontent.com/970828/274137237-84569e98-e71f-4ee8-850b-e915341f99f6.png)

目标就是为了更加细长以显示更多内容
