### ISSUE TITLE
新窗口打开文档，窗口无法关闭

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#9311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，用新窗口打开文档，该窗口无法关闭，通过其他方式也无法关闭（例如 Quicker 操作窗口关闭）

### Expected result

正常即可

### Screenshot or screen recording presentation

见视频：
新窗口关闭BUG9.mp4
https://www.aliyundrive.com/s/z6Qk92McmKR

### Version environment

```markdown
- Version: 2.10.7（该BUG持续很多个版本了）
- Operating System: win 10 22H2
- Browser (if used):
```

### Log file

无，需要提供吗

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/7e40497c-a920-4844-9c63-ac55fc57a34f)

你好，请在默认主题并排查扩展影响后测试看看。

**Comment by LGRemdo** [comment]
> ![image](https://user-images.githubusercontent.com/873584/271314878-7e40497c-a920-4844-9c63-ac55fc57a34f.png)
> 
> 你好，请在默认主题并排查扩展影响后测试看看。

好，但是有另外一个问题，悬浮在双链这种上面，弹出来的窗口，大小怎么设一个默认呢？我默认弹出来的太小了。又不能通过windows api调节窗口大小，很难受

**Comment by Vanessa219** [comment]
高度会自动计算，宽度可以使用 CSS 进行重制
```
.block__popover { width: 70vw}
```

**Comment by LGRemdo** [comment]
> 高度会自动计算，宽度可以使用 CSS 进行重置
> ```
> .block__popover { width: 70vw}
> ```

如果我不喜欢自动高度呢，我就想要很高。

另外，弹出来的窗口，从某种意义上来说，的确不是新的窗口吗？

我待会儿也会尝试一下关闭插件，默认主题确实也有问题，所以可能待会儿这个问题还要开启。

**Comment by LGRemdo** [comment]
> ![image](https://user-images.githubusercontent.com/873584/271314878-7e40497c-a920-4844-9c63-ac55fc57a34f.png)
> 
> 你好，请在默认主题并排查扩展影响后测试看看。

已找到罪魁祸首
![K0$1F~)DJ3B $)}H~(12UG](https://github.com/siyuan-note/siyuan/assets/54077803/5db139cd-e70b-46df-9e7b-ad6ac27a8e9e)

**Comment by Vanessa219** [comment]
1. 高度的话就设置高度
2. 没太理解弹出的窗口不是新窗口
3. 移除插件就没有问题了么？

**Comment by LGRemdo** [comment]
> * 高度的话就设置高度
> * 没太理解弹出的窗口不是新窗口
> * 移除插件就没有问题了么？

1. 好
2. 就是windows窗口，siyuan悬浮窗口不是真正的窗口，而是一个html元素？用新窗口打开才是真正意义上的窗口
3. 对

**Comment by Vanessa219** [comment]
是的，浮窗只能使用这个转换为新窗口

<img width="216" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/19836ab1-22c5-41cd-b0f1-7832d9f85e42">

**Comment by LGRemdo** [comment]
> 是的，浮窗只能使用这个转换为新窗口
> 
> <img alt="image" width="216" src="https://user-images.githubusercontent.com/970828/273250723-19836ab1-22c5-41cd-b0f1-7832d9f85e42.png">

嗯嗯，弄清楚了，感谢，辛苦
