### ISSUE TITLE
自定义属性支持使用非英语和数字外的其他语言字符

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#9312]
### In what scenarios do you need this feature?

目前思源的自定义属性仅支持英文字母和阿拉伯数字，而不支持其他语言，但对非英语母语及长期使用英语的使用者来说，想到添加自定义属性时，首先想到的可能就是自己的母语进行输入

### Describe the optimal solution

自定义属性名支持英语及数字外的其他字符

**Comment by zxhd863943427** [comment]
请参阅https://github.com/siyuan-note/siyuan/issues/9272 下面的讨论。

自定义属性主要是为拓展功能提供的，它会直接出现在dom中，使用unicode字符命名会导致不可预见的错误。

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/8440 https://github.com/siyuan-note/siyuan/issues/7581

**Comment by UltramarineSky** [comment]
> 请参阅#9272 下面的讨论。
> 
> 自定义属性主要是为拓展功能提供的，它会直接出现在dom中，使用unicode字符命名会导致不可预见的错误。

才发现现在多了个数据库属性，这个就可以满足做书单和追番清单的要求了，自定义块属性还是丢给插件和主题玩花活吧：）
