### ISSUE TITLE
属性视图的 URL 能否支持输入 markdown 格式语法

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9314]
### In what scenarios do you need this feature?

目前 URL 字段似乎只能属于一个链接，是否可以允许输入一个 ![]() 格式的 markdown 格式链接？

### Describe the optimal solution

略

**Comment by 88250** [comment]
这个不支持。另外，普通文本字段目前也无法支持排版元素，只能用纯文本，我先关闭了，谢谢。
