### ISSUE TITLE
搜索体验加强

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9315]
### In what scenarios do you need this feature?

在思源中搜索比较繁琐，需要不断打开搜索界面
是否可以将搜索页面固定住
将搜索页面固定在页签中时，打开文档，就会覆盖掉搜索界面，是否可以对于分开的一页签进行设置：此页签数量永远为1，新打开的文档就不会遮挡搜索页面，打开的新文档永远在另一页签打开。
是否可以将搜索功能在不改变原有功能的情况下，再添加一个侧边栏搜索，这样的话，再侧边栏就可以直接使用搜索功能，并且不再需要按下“在新页签中打开”

### Describe the optimal solution

改善搜索时的情况

**Comment by 88250** [comment]
固定搜索后会单独向右分屏窗口，新开文档页签是在当前激活（焦点所在）的窗口，所以可以试下把焦点移动已有的左边窗口后再打开文档，这样新开的文档就在左边窗口了。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
