### ISSUE TITLE
列表：选中多行应该变成同级列表、当前列表缩进应该变成上一列表的子级列表、列表复制后内容和格式出现了问题、列表转正文繁琐、行间距不齐

### ISSUE THREAD

**Issue by ZIP97** [siyuan-note/siyuan#932]
版本：v0.5.5
一直以来列表用得都不太爽，目前发现以下几个问题：
1. 选中多行应该变成同级列表
2. 在很多编辑器里面，当前列表使用 Tab 缩进之后都是变成上一列表的子级列表。思源里面只能通过删除到父级列表后面换行+缩进来实现子级列表
![多选行变成列表 和 直接从一级列表通过缩进变成上一个列表的二级列表](https://user-images.githubusercontent.com/25300418/103492009-fb036f80-4e62-11eb-938e-bf7cef3ec8fc.gif)
3. 多选行复制列表出现：粘贴后出现ID内容、粘贴过去所在的列表格式混乱
![列表复制时会带上块ID 而且导致之前的项目列表换行](https://user-images.githubusercontent.com/25300418/103492011-fccd3300-4e62-11eb-850d-f5f9e205f9f1.gif)
4. 把一级列表转化成普通正文很繁琐 无法通过 `shift + Tab` 来实现
![把一级列表转化成普通正文很繁琐 无法通过 shift Tab 来实现](https://user-images.githubusercontent.com/25300418/103492476-14f28180-4e66-11eb-9378-ab6357e20abb.gif)
5. 行间距不齐（貌似第一个多级列表会出现这种不齐的情况）
![image](https://user-images.githubusercontent.com/25300418/103492858-ddd19f80-4e68-11eb-9731-9c304dc1156b.png)

**Comment by 88250** [comment]
感谢反馈，后续改进，谢谢。

**Comment by guidongyuan** [comment]
同样反馈列表的问题，发现列表切换下一行的显示 > 的时候，> 经常又跑到上一行去了。
比如我想输入如下
* 第一行
  > 引用内容。

结果通过 Enter 切换到下一行后，输入 > ，老是跑会上一行。D大可以试一下输入看看

**Comment by 88250** [comment]
@guidongyuan 你好，我这里好像正常：

![issue](https://user-images.githubusercontent.com/873584/103646203-41a4b700-4f94-11eb-9ed3-81010710de9d.gif)

**Comment by guidongyuan** [comment]
> @guidongyuan 你好，我这里好像正常：
> 
> ![issue](https://user-images.githubusercontent.com/873584/103646203-41a4b700-4f94-11eb-9ed3-81010710de9d.gif)

我知道问题了，你再试一下列表内容是链接看看。类似
* [插入链接](https://blog.csdn.net/u013762572/article/details/90233221)
  > 再试一下这种情况看看是否正常。

**Comment by guidongyuan** [comment]
再试一下，好像列表是链接的内容，就有问题



在 2021-01-05 20:26:39，"D" <notifications@github.com> 写道：

@guidongyuan 你好，我这里好像正常：

**Comment by 88250** [comment]
@guidongyuan 收到，我这里可以重现了，稍后修复。

**Comment by guidongyuan** [comment]
> @guidongyuan 收到，我这里可以重现了，稍后修复。

D大这个问题在新版本修复了吗？我这边发现，列表是快引用，还是会出现问题。

**Comment by 88250** [comment]
@guidongyuan 
![issue](https://user-images.githubusercontent.com/873584/103843459-d57c9d00-50d2-11eb-9b64-cb25226a753d.gif)

**Comment by guidongyuan** [comment]
> @guidongyuan
> ![issue](https://user-images.githubusercontent.com/873584/103843459-d57c9d00-50d2-11eb-9b64-cb25226a753d.gif)

你先复制一下快引用，然后列表内容粘贴块引用看看。
另外，再反馈一个粘贴块引用的bug，把id都显示出来了。

![image](https://user-images.githubusercontent.com/13446866/103845127-61dc8f00-50d6-11eb-893e-f93348210c8e.png)

**Comment by guidongyuan** [comment]
上面的“关闭”打错了，应该是光标

**Comment by 88250** [comment]
@guidongyuan 收到，后期改进粘贴块引，先用搜索块引顶顶，提主的描述里已经包含了这个问题。
@ZIP97 这个 issue 我先关闭了，相关问题后续我们会进行改进，谢谢。
