### ISSUE TITLE
创建文档链接会产生两个

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/139356383/02c548aa-7120-4605-bd74-afca8ddcb172)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/2ae3c798-58e6-43ea-ac8c-8731a58cf763)

### Expected result

改善此问题

### Version environment

```markdown
- Version: 最新测试版
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12780507/siyuan.log)

**Comment by 88250** [comment]
感谢反馈，正式版发布前会修复。
