### ISSUE TITLE
文件树、大纲等页签可以设置为浮动在编辑区域上层显示；大纲增加默认自动展开选项（或添加一键展开选项）

### ISSUE THREAD

**Issue by roverway** [siyuan-note/siyuan#933]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
笔记本屏幕，编辑区域左右分屏，同时打开两个笔记文件对比编辑（一个固定编辑文件，另一个参考文件，来自不同文件夹，需要不时在不同文件夹中查找切换）。

目前习惯的布局是：最左侧文件树，中间为编辑区域（如上述左右分屏，展示两个文件）右侧为大纲、反向链接公用区域。
根据前述应用场景，受限于笔记本屏幕尺寸（14寸），为便于对比编辑，需要最大化编辑区域，目前采取的方法是，编辑时候隐藏编辑区左右两侧的文件树区域和大纲及反向链接区域，需要切换文件夹或者需要查看大纲或反链的时候，再用快捷键打开对应页签。感觉不便之处在于，每次打开文件树或者大纲等编辑区之外的页签，都会挤占编辑区空间，影响当前屏幕显示的内容（当前光标定位位置可能被挤出屏幕），而且左右分屏的编辑区被挤占后，观感和编辑效率都有降低。

希望能够最大化编辑区域面积（方便至少两个文件的同时展示）的同时，还能够随时切换不同文件夹、随时根据大纲定位当前文件的不同位置，或者随时查看反向链接（书签等等）

### 描述最优的解决方案 Describe the optimal solution

为页面布局增加新特性，最主要的是允许浮动页签存在，详细描述如下：
为窗口左右两侧页签（文件树、大纲、反向链接等）设置两种显示模式：1为目前的形式，永久占据当前窗口，挤占编辑区空间；2为新增特性，可以将文件树等页签设置为在编辑区上层浮动显示，根据需要弹出（鼠标边缘触发或快捷键换出），用完后隐藏（自动隐藏或快捷键）。因为文件树或大纲的使用频率远低于编辑区域，我感觉这种用完即退的设置要更好些。

此外，希望增加大纲默认展开特性，或者添加一键展开大纲按钮，因为我经常使用思源笔记阅读很大大文件（5万字以上），大纲默认展开能够节约不少点击次数，提高定位效率。

**Comment by 88250** [comment]
感谢建议，计划改进如下：

* 窗口布局进行 Dock（类似 Windows 上的任务栏，macOS 上的程序坞）支持 #635 
* 页签支持转换为浮动窗口
* 大纲展开折叠请关注 #564

目前可通过快捷键打开/关闭文件树、大纲来使用，快捷键在 v0.5.6 中会支持自定义，谢谢。
