### ISSUE TITLE
允许用户禁用关系图的自动刷新

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9330]
### In what scenarios do you need this feature?

之前没怎么用关系图，今天试用了一下，发现排除掉所有的文档内部内容块，只显示引用关系的话，还是比想象中好用的。
但是有一个地方我不太满意，当点击关系图当中某个节点，自动调整到对应的文档后，关系图就会自动刷新变成当前文档的引用关系。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/38be08fd-c165-4364-9c83-63edc4a96175)

问题的关键在于，用户无法控制关系图是否要自动刷新。而有时候，用户可能只是想查看某个文档的关系图，而并不想要这个关系图自动刷新。

### Describe the optimal solution

可以增加一个「固定」关系图的功能，让关系图不随着文档的切换自动刷新。

**Comment by 88250** [comment]
我记得有个关系图页签，你找找看，应该在文档块标菜单里。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月2日(周一) 下午4:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 增加固定关系图显示的功能 (Issue #9330)




 
In what scenarios do you need this feature?
 
之前没怎么用关系图，今天试用了一下，发现排除掉所有的文档内部内容块，只显示引用关系的话，还是比想象中好用的。
 但是有一个地方我不太满意，当点击关系图当中某个节点，自动调整到对应的文档后，关系图就会自动刷新变成当前文档的引用关系。
 

 
希望可以增加一个「固定」关系图的功能，让关系图不随着文档的切换自动刷新。
 
Describe the optimal solution
 
增加一个「固定」按钮。
 
Describe the candidate solution
 
No response
 
Other information
 
No response

**Comment by frostime** [comment]
> 我记得有个关系图页签，你找找看，应该在文档块标菜单里。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月2日(周一) 下午4:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [siyuan-note/siyuan] 增加固定关系图显示的功能 (Issue #9330) In what scenarios do you need this feature? 之前没怎么用关系图，今天试用了一下，发现排除掉所有的文档内部内容块，只显示引用关系的话，还是比想象中好用的。 但是有一个地方我不太满意，当点击关系图当中某个节点，自动调整到对应的文档后，关系图就会自动刷新变成当前文档的引用关系。 希望可以增加一个「固定」关系图的功能，让关系图不随着文档的切换自动刷新。 Describe the optimal solution 增加一个「固定」按钮。 Describe the candidate solution No response Other information No response — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

可以，那这个 issue 可以先 close 了。
