### ISSUE TITLE
允许使用 `siyuan --help` 命令查看所有可用的参数 (命令行文档)

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9333]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/27268127/4410249d-9ff6-4f46-adf4-8f73a481b699)

### Describe the optimal solution

`siyuan --help` 运行后，只打印可用参数，不启动思源进程

**Comment by 88250** [comment]
这个只有内核程序支持。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月3日(周二) 凌晨1:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [siyuan-note/siyuan] 允许使用 `siyuan --help` 命令查看所有可用的参数 (命令行文档) (Issue #9333)




 
In what scenarios do you need this feature?
 

 
Describe the optimal solution
 
siyuan --help 运行后，只打印可用参数，不启动思源进程
 
Describe the candidate solution
 
No response
 
Other information
 
No response
