### ISSUE TITLE
Support AI Q&A based on siyuan database

### ISSUE THREAD

**Issue by LAD021** [siyuan-note/siyuan#9335]
### In what scenarios do you need this feature?

Will siyuan support Answering question based on users siyuan note database and ChatGPT api?
Can this application be provided by both UI and API?
Will double-link be helpful of this.

### Describe the optimal solution

If I want to contribute for this feature, what can I do for you.

**Comment by 88250** [comment]
Hello, please refer to Settings - AI, and block icon menu, thanks.

**Comment by LAD021** [comment]
<img width="170" alt="截屏2023-10-05 12 50 22" src="https://github.com/siyuan-note/siyuan/assets/60390821/e0754324-0ffb-463b-b0bf-e8e9641faad5">
Do you mean AI icons here?
In fact I wonder whether there is a method to query AI for answer which is based on the whole workspace of my SiYuan. Like New Bing does, providing answer with SiYuan links.

**Comment by 88250** [comment]
Sorry, there is currently no such function. To implement such a function, does it require that all data be completely uploaded to the AI service? In this case, will the price be more expensive?

**Comment by LAD021** [comment]
Maybe this can be realized just by SQL, but what about we treat the article (or block) we are writing as an input?

**Comment by 88250** [comment]
Sorry, I don't know much about "vectorization" at the moment and may not be able to have an effective discussion with you...
