### ISSUE TITLE
【Bug】属性视图搜索块不完全、超链接不符合预期

### ISSUE THREAD

**Issue by LGRemdo** [siyuan-note/siyuan#9336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. block属性搜不到文档
2. 超链接列重影、飞蚊症（已排除，默认主题正常）
3. 为什么超链接列填写Baidu.com，打开确是资源管理器

### Expected result

正常即可

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/54077803/c05967db-f44c-436a-87b8-d5c9b94aebca)
![image](https://github.com/siyuan-note/siyuan/assets/54077803/21b86720-f48a-464f-8b81-f126503020fa)

### Version environment

```markdown
- Version: 2.10.8
- Operating System: win 10 22h2
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
* 当前文档会被排除在搜索外，这个暂时算作是特性吧，后期如果反馈的人多我们再考虑支持
* 超链接需要添加协议，比如 https://

感谢反馈。
