### ISSUE TITLE
悬浮窗口内，块菜单中「大纲」「反向链接」「关系图」三个按钮无效

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在悬浮窗口中，点击块菜单后，第3~6个按钮点击后无反应

![image](https://github.com/siyuan-note/siyuan/assets/27268127/b55157e5-0ca7-4196-a51d-37dfb74916dd)

控制台报错为 undefined 错误

![image](https://github.com/siyuan-note/siyuan/assets/27268127/8c05822d-d7d9-49d2-8862-80485fea6969)

### Expected result

修复错误，让这三个按钮在悬浮窗口中也能使用

### Version environment

```markdown
- Version: 2.10.8
- Operating System: win10
- Browser (if used): no
```

### Log file

无

**Comment by Vanessa219** [comment]
大纲等在悬浮窗上没有面板，无法打开，只能移除。

**Comment by frostime** [comment]
> 大纲等在悬浮窗上没有面板，无法打开，只能移除。

大纲无所谓，但是后面两个反向链接和关系图是在思源当中打开一个新的标签页的啊，文档在悬浮窗口中应该不影响新建一个标签页吧?

![image](https://github.com/siyuan-note/siyuan/assets/27268127/2a48b851-eb76-44cd-bf3c-78b950f3a72b)

**Comment by 88250** [comment]
都是面板，不是页签。

**Comment by frostime** [comment]
> 都是面板，不是页签。

这个不是 Tab 页嘛？🤨

![image](https://github.com/siyuan-note/siyuan/assets/27268127/40497f4d-b74b-4d41-8ce2-6ee6f2813a47)

**Comment by 88250** [comment]
@Vanessa219 到底是不是页签 😂

**Comment by Vanessa219** [comment]
以为是要在浮窗上面打开大纲、反链、关系图页签。在主窗口打开的话会被浮窗遮住，也不太好看吧。

**Comment by frostime** [comment]
> 以为是要在浮窗上面打开大纲、反链、关系图页签。在主窗口打开的话会被浮窗遮住，也不太好看吧。

这个好不好看也无所谓，但是实用啊（起码对我来说）。常见的使用场景比如：

我在文档中引用了一个主题 def block X，现在我想要快速查看主题 X 的相关反链作为参考，这时候就可以在悬浮窗内快速打开反链面板。

目的和 shift + 鼠标悬浮在引用上相同，都是为了快速查看一个特定的 def block 所有的相关反链块——但是shift 悬浮呼出的窗口太狭窄了，并不适合阅读，而如果用正规的反链标签页来查看体验会好很多。

**Comment by frostime** [comment]
> > 以为是要在浮窗上面打开大纲、反链、关系图页签。在主窗口打开的话会被浮窗遮住，也不太好看吧。
> 
> 这个好不好看也无所谓，但是实用啊（起码对我来说）。常见的使用场景比如：
> 
> 我在文档中引用了一个主题 def block X，现在我想要快速查看主题 X 的相关反链作为参考，这时候就可以在悬浮窗内快速打开反链面板。
> 
> 目的和 shift + 鼠标悬浮在引用上相同，都是为了快速查看一个特定的 def block 所有的相关反链块——但是shift 悬浮呼出的窗口太狭窄了，并不适合阅读，而如果用正规的反链标签页来查看体验会好很多。
> 
> 并且本来原本在文档中点击「反链」「关系图」的按钮也是打开一个新的 tab 标签页，这个行为是一致的。

自顶，不知道 @Vanessa219 能否考虑一下。

**Comment by Vanessa219** [comment]
浮窗大部分情况下只是用来预览和进行简单的修改，因此窗口大小会收到限制，如果再在上班加一个反链页签会更加拥挤。需要查看的话可以固定打开反链面板，然后点击引用，反链面板就会自动刷新为需要查看的内容了。

**Comment by frostime** [comment]
> 浮窗大部分情况下只是用来预览和进行简单的修改，因此窗口大小会受到限制，如果再在上面加一个反链页签会更加拥挤。需要查看的话可以固定打开反链面板，然后点击引用，反链面板就会自动刷新为需要查看的内容了。

我说的不是在 FloatWindow 当中打开新的页签啊，就是在正常的编辑器里打开一个页签，就和点击文档图标选择「反向链接」打开一个新的页签一样的行为。

**Comment by Vanessa219** [comment]
上面提到过打开后会被悬浮窗遮挡，这样也没关系么？

**Comment by frostime** [comment]
> 上面提到过打开后会被悬浮窗遮挡，这样也没关系么？

这个 issue 中我谈论的核心目的，其实就是「为了能够更加方便快速的打开一个链接的反链内容」（shift + 悬浮并不好用），被遮挡问题也不大。

---

其实，「为了能够更加方便**快速的打开一个链接的反链内容**」，我此前还想过在双链引用的右键menu当中增加按钮，可以快速打开对应引用对象的反链页签。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/eee2eeae-491f-4646-b239-017d42716a07)

但是后来想到反链页签是以文档为单位的，而引用则不限制块的类型，所以才放弃了这个想法——这次在这个 issue 里顺便把这个想法也提出来，看 V 如何考量。

**Comment by Vanessa219** [comment]
嗯嗯，反链面板会根据聚焦进行过滤，这样感觉可以更好的满足需求。

那么在引用的右键菜单上加一个“打开反向链接”，这样是不是就可以了？

**Comment by frostime** [comment]
> 嗯嗯，反链面板会根据聚焦进行过滤，这样感觉可以更好的满足需求。
> 
> 那么在引用的右键菜单上加一个“打开反向链接”，这样是不是就可以了？

这样也可以！（另外关系图也能加上去吗？）
