### ISSUE TITLE
反链、标签等查询出来的内容支持通过悬停窗口显示上下文

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#9344]
### In what scenarios do you need this feature?

目前反链查看上下文需要退出该层聚焦，标签查看上下文在条目下方的窗口。通过悬停窗口显示上下文能更节约空间和方便查看上下文。

### Describe the optimal solution

像 Obsidian 那样通过悬停窗口查看上下文。

**Comment by mozhux** [comment]
思源所有面包屑路径都能悬浮看上下文啊，鼠标放上去就行

**Comment by 88250** [comment]
楼上说得对，我关闭了。
