### ISSUE TITLE
网页高亮与属性视图功能整合

### ISSUE THREAD

**Issue by Geo123abc** [siyuan-note/siyuan#9345]
### In what scenarios do you need this feature?

很多信息都是从网页获得的，一直在纠结网页高亮、标注等，

最近思源笔记也出了属性视图功能，然后看到了这个[插件分享：可能是最实用的高亮插件Hamsterbase Highlighter](  https://mp.weixin.qq.com/s/tKP4Gt2nZSVpLfggCwYqeg  )    ，

这个浏览器插件可以和notion联合，并且是开源的[hamsterbase/hamsterbase-highlighter: highlighter for notion, hamsterbase](  https://github.com/hamsterbase/hamsterbase-highlighter  )    ，

### Describe the optimal solution

思源笔记能不能把“网页高亮、网页笔记”功能整合一下，实现“思源笔记浏览器插件+思源笔记客户端的属性视图”联合使用？

**Comment by 88250** [comment]
这个应该不会考虑，可使用浏览器剪藏扩展将网页内容拉取到本地，在本地做整理。

**Comment by Geo123abc** [comment]
> 这个应该不会考虑，可使用浏览器剪藏扩展将网页内容拉取到本地，在本地做整理。

拉取的话只是单向的，下次浏览这个网页，可能会不知道有没有做过笔记，希望社区有人出手搞一搞
