### ISSUE TITLE
批量去除选中内容中指定的格式

### ISSUE THREAD

**Issue by Clz-SkyWalker** [siyuan-note/siyuan#935]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

某些从网络上拷贝下来的文字，某些关键字总是会带上一些超链接，我要一个个去除这些超链接让我感觉非常麻烦，特别是在大篇文章中有很多的超链接

### 描述最优的解决方案 Describe the optimal solution

能否给链接按钮添加新特性，选中一大段文字后，点击链接按钮，给我吧所有的带有超链接的文字变成普通文字

**Comment by 88250** [comment]
感谢，很好的建议，可能类似的还需要取消选中加粗、斜体等。估计会做成选中内容后右键菜单，提供多种取消格式的选项。

**Comment by 88250** [comment]
v1.2.0 以后操作模式变化比较大，这个特性需要以后重新收集需求再考虑了，谢谢。
