### ISSUE TITLE
希望输入授权码后能直接登录，不需要再次按回车键

### ISSUE THREAD

**Issue by ITKJO** [siyuan-note/siyuan#9352]
### In what scenarios do you need this feature?

希望输入授权码后能直接登录，不需要再次按回车键，从而加快输入流程

### Describe the optimal solution

可以参照windows进入系统时的pin码输入方式；或者也可以检测输入的授权码位数和设置的位数一样时自动回车确认

**Comment by 88250** [comment]
感谢提议，不过这个想法行不通，因为有验证码机制，如果输入一个字符后就提交一次很容易触发验证码，pin 码是因为位数固定所以可以在输入满位数后自动确认。另外，位数不能提前让客户端知道，否则有安全问题。
