### ISSUE TITLE
希望开启开机启动的时候，不要开机后就弹出页面让我输入密码，而是让他在后台运行，我去点击的时候在让窗口到前台

### ISSUE THREAD

**Issue by ITKJO** [siyuan-note/siyuan#9353]
### In what scenarios do you need this feature?

希望开启开机启动的时候，不要开机后就弹出页面让我输入密码，而是让他在后台运行，我去点击的时候在让窗口到前台

### Describe the optimal solution

希望添加一个按钮设置，可以让他在后台运行，我去点击的时候在让窗口到前台，

**Comment by 88250** [comment]
可使用 Alt+M 隐藏/显示窗口。
