### ISSUE TITLE
希望可以根据标题生成思维导图，或者直接让思维导图模式在MD之间切换

### ISSUE THREAD

**Issue by ITKJO** [siyuan-note/siyuan#9354]
### In what scenarios do you need this feature?

希望可以根据标题生成思维导图，或者直接让思维导图模式在MD之间切换

### Describe the optimal solution

希望可以根据标题生成思维导图，或者直接让思维导图模式在MD之间切换

**Comment by 88250** [comment]
感谢提议，但是这个功能不考虑了，如果需要脑图请看下集市中的插件。
