### ISSUE TITLE
像logseq那样，反链和笔记的查看逻辑保持一致

### ISSUE THREAD

**Issue by AugustTuan** [siyuan-note/siyuan#9355]
### In what scenarios do you need this feature?

如无必要，勿增实体

如无必要，不要引入新窗口，不要分屏。

反链和引用就和看文档笔记一样，直接在文档内部看，并且出现在离原文最近的位置

### Describe the optimal solution

能够增加logseq这种浏览反链地方式，将反链放到文档下方显示反链和提及
![image](https://github.com/siyuan-note/siyuan/assets/37429029/1907cc18-cec9-4ec5-8b77-620c59fd7c89)

![image](https://github.com/siyuan-note/siyuan/assets/37429029/dca26f57-33d5-4d43-ab4b-a15aed7b02b1)

思源查看反链 对比
![image](https://github.com/siyuan-note/siyuan/assets/37429029/91838df9-5afe-4180-ad06-2a924db5ca4c)

### Describe the candidate solution

logseq这种处理方式，我可以像看文档中地笔记一样，去看反链和提及

而思源目前的处理方式，我必须要打开窗口，必须要分屏， 才能看到这些信息

![image](https://github.com/siyuan-note/siyuan/assets/37429029/91838df9-5afe-4180-ad06-2a924db5ca4c)

### Other information
反链最好出现在离内容最近的位置，因为从反链跳到原文，再从原文回去会很方便。

**Comment by 88250** [comment]
感谢提议，但我们不考虑底部反链了，如果觉得反链面板麻烦的话建议通过浮窗查看。

**Comment by winter60** [comment]
pc上的反链面板非常nice，不过移动端浏览就有点不方便了

**Comment by AugustTuan** [comment]
> pc上的反链面板非常nice，不过移动端浏览就有点不方便了

移动端和小屏幕ipad，一打开反链面板，几乎正文就没什么空间了😭
