### ISSUE TITLE
Improve some UI details

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9359]
1.  ~~暂时无法重现~~
![image](https://github.com/siyuan-note/siyuan/assets/970828/31ac7af5-7096-4612-816a-f64367bee542)
2. Update row icon
![image](https://github.com/siyuan-note/siyuan/assets/970828/6c5c3a8d-a199-4a99-9c3e-0de96a8e8e3b)
3. 
![image](https://github.com/siyuan-note/siyuan/assets/970828/a7c224a7-18b3-4baf-a8fc-ca0edf6f13e3)

https://ld246.com/article/1696588249918?r=88250
https://ld246.com/article/1696512420662

**Comment by luoxxib** [comment]
思源笔记英文乱码怎么办

**Comment by 88250** [comment]
麻烦截图看看。



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 7, 2023 17:44 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve some UI details (Issue #9359)




 
思源笔记英文乱码怎么办

**Comment by luoxxib** [comment]
思源笔记软件件以及思源下载页面也出现类似的英文乱码：
![image](https://github.com/siyuan-note/siyuan/assets/9431773/f790a2ee-1276-4c53-8749-5e8899b505d9)
![image](https://github.com/siyuan-note/siyuan/assets/9431773/05aa1bf9-578a-466a-96e0-02e2d6a3dad6)

**Comment by 88250** [comment]
@luoxxib 感觉是系统字体的问题，英文字体好像不对劲。

**Comment by luoxxib** [comment]
@88250 打开其它英文网站不出现这种情况，使用其它笔记软件输入英文也没问题。就思源的笔记和网站出现这个问题

**Comment by 88250** [comment]
建议还是看下字体，特别是系统默认的字体比如微软雅黑。



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 7, 2023 23:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve some UI details (Issue #9359)




 
@88250 打开其它英文网站不出现这种情况，使用其它笔记软件输入英文也没问题。就思源的笔记和网站出现这个问题

**Comment by luoxxib** [comment]
系统设置默认字体是微软雅黑，但是你们的网站还是乱码；思源笔记 设置->编辑器->字体 设置为默认就是乱码，设置为等线编辑器中的英文就正常显示，但思源笔记的界面上文档树、标签等控件上的英文仍然是乱码，我觉得你们应该改进一下字体设置

**Comment by luoxxib** [comment]
如果是非英文乱码还可以理解，居然是英文乱码，有点奇怪

**Comment by 88250** [comment]
这个问题我们也是第一次收到反馈，暂时无法定位具体原因，后续我们会留意类似反馈的，谢谢。



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 8, 2023 00:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve some UI details (Issue #9359)




 
系统设置默认字体是微软雅黑，但是你们的网站还是乱码；思源笔记 设置-&gt;编辑器-&gt;字体 设置为默认就是乱码，设置为等线编辑器中的英文就正常显示，但思源笔记的界面上文档树、标签等控件上的英文仍然是乱码，我觉得你们应该改进一下字体设置
