### ISSUE TITLE
Database template column supports `created` and `updated` built-in variables

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9364]
Database 支持显示块的创建时间和更新时间

### In what scenarios do you need this feature?

目前的时间列只能手动选择及更改时间，database的显示时间更多情况下，需要显示笔记的创建时间和更新时间，有自动更新时间的需求。

目前的模板列当我输入.action{.created}是不加载数据的，
![image](https://github.com/siyuan-note/siyuan/assets/60436214/8985f149-4dbb-4eb0-8afb-f6b9bd62ea3c)
输入.action{.updated}可以显示时间数据，但又是纯文字的，不支持直接使用action{.updated | date "2006.01.02 Mon"}格式化数据。
![image](https://github.com/siyuan-note/siyuan/assets/60436214/a3c4e1d2-bbbe-4aa4-ab65-6b8094132b22)

### Describe the optimal solution

更友好些的优化，直接提供块创建日期和更新日期列，也可以直接从当前的日期列添加选项，是否为块的创建日期或更新日期列

### Describe the candidate solution

硬核方面的优化，模板列能格式化显示块的创建时间和更新时间，得到比如2023-10-07，或2023.10.07格式的显示数据

### Other information

none

**Comment by 88250** [comment]
列类型就不添加了，还是使用模板比较好，这样可以方便更多场景和格式化。

稍后会为模板列添加内置变量 `created` 和 `updated`，是 time 类型，可以使用 sprig 的日期格式化函数：

```
.action{ .created | date "2006-01-02" }  .action{.updated | date "2006-01-02"}
```

**Comment by zxhd863943427** [comment]
> 列类型就不添加了，还是使用模板比较好，这样可以方便更多场景和格式化。
> 
> 稍后会为模板列添加内置变量 `created` 和 `updated`，是 time 类型，可以使用 sprig 的日期格式化函数：
> 
> ```
> .action{ .created | date "2006-01-02" }  .action{ .updated | date "2006-01-02" }
> ```

使用模板列的话对于日期是难以筛选和排序的吧。

**Comment by 88250** [comment]
格式化成字符串以后可以。

**Comment by zxhd863943427** [comment]
比如说，创建日期从3月到12月，我需要筛选出从4月到8月的数据，我不认为使用以下的文本筛选功能：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/54bd7f21-ac54-4b49-9b91-12f7e4e2b2fd)
能够筛选出我想要的数据。

两个特殊的内置时间列和模板列可以调用的变量都是需要的。

**Comment by 88250** [comment]
哦，我之前以为你说的是模板语法。这样的场景确实有必要支持创建时间和更新时间类型列，单独开个 issue 吧 https://github.com/siyuan-note/siyuan/issues/9371
