### ISSUE TITLE
Document-level new card/review card limit control

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9365]
文档级新卡/复习卡上限控制

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源的闪卡复习逻辑疑似是有问题的
新卡和旧卡之间的界限没有明确划分。
![image](https://github.com/siyuan-note/siyuan/assets/139356383/fe2df626-98ae-4e97-a147-791cef516d50)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/c90aa8bf-e9e4-449f-97da-3c205c86d1fa)
在一个文档内部，闪卡全部是新卡，但实际上的新卡上限是200。

### Expected result

新卡和旧卡之间的界限应当明确划分

### Version environment

```markdown
- Version: 2.10.8
- Operating System: win10
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12837928/siyuan.log)

**Comment by gaoluji** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/139356383/dc6cf117-9217-40a5-95eb-6f691a040f9b)
在anki中有一个中间状态，而思源中一张新卡被复习后直接就变成了旧卡片，这是违反操作逻辑的
@88250

**Comment by 88250** [comment]
新卡指的是没有出现过，即第一次出现的卡，复习卡指的是已经出现过的。

**Comment by gaoluji** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/139356383/ad94c243-29a8-4631-aa3a-076e238afdd1)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/c2df54f6-22de-44fd-a534-b103dfbded18)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/6c914d17-a4b7-4271-ace8-78ca843f8117)
还是出问题了，复习疑似是无上限的 @88250

**Comment by gaoluji** [comment]
> 新卡指的是没有出现过，即第一次出现的卡，复习卡指的是已经出现过的。

这些全是新卡，但复习新卡没有上限……，每次打开都只是单次的上限，关闭后打开又会重置（只是学习和复习的数量限制）

**Comment by 88250** [comment]
这个设置没有按照当天进行计算，只是限制一次间隔重复的数量。

**Comment by 88250** [comment]
关于限制数量的问题之前这里讨论过一下，仅供参考 https://github.com/siyuan-note/siyuan/issues/8305

**Comment by gaoluji** [comment]
> 关于限制数量的问题之前这里讨论过一下，仅供参考 #8305

我觉得还是改成一天的比较好……，否则太违反操作了。
卡片还是按天来算比较好

**Comment by 88250** [comment]
按天的话可以自己掌握一下，比如我家用的时候就是每天给娃背一次单词，但是我觉得这用法实际上还是不够科学，因为间隔重复算法实际上已经计算出了时间了，按照那个时间的话应该是记忆效率最高的。

**Comment by 88250** [comment]
再补充一些信息，FSRS 算法的卡片状态实际上是有 4 种：

* New State
* Learning
* Review
* Relearning

我们现在是用的 New State 来判断新卡，其余状态都是复习卡。

**Comment by gaoluji** [comment]
> 再补充一些信息，FSRS 算法的卡片状态实际上是有 4 种：
> 
> * New State
> * Learning
> * Review
> * Relearning
> 
> 我们现在是用的 New State 来判断新卡，其余状态都是复习卡。


前几天刚推荐给朋友，他就遇到了这个……，说实在，他没问我还没感觉到。
但按照这种算法来看，不知道是否可以这样？
每个文档设置复习数量，我试了一下，目前要不断调总的闪卡复习量，
![image](https://github.com/siyuan-note/siyuan/assets/139356383/9b64111d-9d90-4911-9d08-f3d891a96c70)
在每个文档内设置闪卡复习量。当日新学可以不断减去新学的量，这样减到0就不会遇到这种事情了

**Comment by 88250** [comment]
按文档来设置限制我个人觉得是一种比较特殊的用法，一是要考虑子文档的情况（是排除还是包含），二是不一定按文档就是合理的，卡片可能是分散在不同文档中的。

**Comment by gaoluji** [comment]
> 按文档来设置限制我个人觉得是一种比较特殊的用法，一是要考虑子文档的情况（是排除还是包含），二是不一定按文档就是合理的，卡片可能是分散在不同文档中的。

这个很简单，参考anki，remnote，子文档算入父文档闪卡限制，但子文档自身也可以设置卡片限制（父文档的卡片的使用情况也会影响子文档的卡片数量，比如今日新卡片，在父文档中使用间隔重复，子文档的闪卡数量也会影响），anki中的卡包就是如此，remnote也是如此。父文档是10新卡，而子文档是20新卡，父文档如果自身内部没有卡片，只是占用子文档新卡片，则子文档还有10新卡。
置于卡片分散在不同文档，是分散在子文档还是不同文档，如果分散在不同的文档（非此父文档的子文档），则可以参考logseq以及remnote，通过反链来实现处于不同文档中的闪卡，logseq通过检索双链[[文档名]]，remnote通过标签（也类似双链）

**Comment by 88250** [comment]
等其他人反馈看看是否有这个需求。


搜索圈定范围那个之前考虑过，先缓缓。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月7日(周六) 晚上10:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 闪卡上限设置失效 (Issue #9365)




  
按文档来设置限制我个人觉得是一种比较特殊的用法，一是要考虑子文档的情况（是排除还是包含），二是不一定按文档就是合理的，卡片可能是分散在不同文档中的。
  
这个很简单，参考anki，remnote，子文档算入父文档闪卡限制，但子文档自身也可以设置卡片限制（父文档的卡片的使用情况也会影响子文档的卡片数量，比如今日新卡片，在父文档中使用间隔重复，子文档的闪卡数量也会影响），anki中的卡包就是如此，remnote也是如此。父文档是10新卡，而子文档是20新卡，父文档如果自身内部没有卡片，只是占用子文档新卡片，则子文档还有10新卡。
 置于卡片分散在不同文档，是分散在子文档还是不同文档，如果分散在不同的文档（非此父文档的子文档），则可以参考logseq以及remnote，通过反链来实现处于不同文档中的闪卡，logseq通过检索双链[[文档名]]，remnote通过标签（也类似双链）

**Comment by gaoluji** [comment]
> 等其他人反馈看看是否有这个需求。 搜索圈定范围那个之前考虑过，先缓缓。
> [...](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月7日(周六) 晚上10:54 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 闪卡上限设置失效 (Issue #9365) 按文档来设置限制我个人觉得是一种比较特殊的用法，一是要考虑子文档的情况（是排除还是包含），二是不一定按文档就是合理的，卡片可能是分散在不同文档中的。 这个很简单，参考anki，remnote，子文档算入父文档闪卡限制，但子文档自身也可以设置卡片限制（父文档的卡片的使用情况也会影响子文档的卡片数量，比如今日新卡片，在父文档中使用间隔重复，子文档的闪卡数量也会影响），anki中的卡包就是如此，remnote也是如此。父文档是10新卡，而子文档是20新卡，父文档如果自身内部没有卡片，只是占用子文档新卡片，则子文档还有10新卡。 置于卡片分散在不同文档，是分散在子文档还是不同文档，如果分散在不同的文档（非此父文档的子文档），则可以参考logseq以及remnote，通过反链来实现处于不同文档中的闪卡，logseq通过检索双链[[文档名]]，remnote通过标签（也类似双链） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

这个还是蛮重要的，我给人推荐思源笔记就是闪卡功能主推，希望闪卡功能更完善些吧

**Comment by 88250** [comment]
嗯，我们会抓紧时间评估的。

**Comment by 88250** [comment]
通过文档块的自定义属性覆写全局配置：

* `riff-new-card-limit`
* `riff-review-card-limit`

![image](https://github.com/siyuan-note/siyuan/assets/873584/d56caa4b-3510-421b-ab75-1544a8866cb8)

不同文档上单独配置，相互独立不影响，比如父文档上配置为 5，子文档为 10，那么从父文档复习的时候就是 5，不会叠加子文档的配置。

**Comment by gaoluji** [comment]
> 通过文档块的自定义属性覆写全局配置：
> 
> * `riff-new-card-limit`
> * `riff-review-card-limit`
> 
> ![image](https://usercontent.githubfast.com/user-images/873584/273447537-d56caa4b-3510-421b-ab75-1544a8866cb8.png)
> 
> 不同文档上单独配置，相互独立不影响，比如父文档上配置为 5，子文档为 10，那么从父文档复习的时候就是 5，不会叠加子文档的配置。

是文档属性还是新功能？

**Comment by 88250** [comment]
文档块自定义属性。



---Original---
From: ***@***.***&gt;
Date: Sun, Oct 8, 2023 21:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Document-level new card/review card limitcontrol (Issue #9365)




  
通过文档块的自定义属性覆写全局配置：
  
riff-new-card-limit
 
riff-review-card-limit
  

 
不同文档上单独配置，相互独立不影响，比如父文档上配置为 5，子文档为 10，那么从父文档复习的时候就是 5，不会叠加子文档的配置。
  
是文档属性还是新功能？

**Comment by gaoluji** [comment]
> 文档块自定义属性。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Oct 8, 2023 21:39 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [siyuan-note/siyuan] Document-level new card/review card limitcontrol (Issue #9365) 通过文档块的自定义属性覆写全局配置： riff-new-card-limit riff-review-card-limit 不同文档上单独配置，相互独立不影响，比如父文档上配置为 5，子文档为 10，那么从父文档复习的时候就是 5，不会叠加子文档的配置。 是文档属性还是新功能？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

d大请问属性值咋写？还是说是后续功能的升级

**Comment by 88250** [comment]
你看我上面那个截图，就是在文档块的属性面板对话框 - 自定义属性里添加属性和值就行了。

**Comment by gaoluji** [comment]
> 你看我上面那个截图，就是在文档块的属性面板对话框 - 自定义属性里添加属性和值就行了。

![image](https://github.com/siyuan-note/siyuan/assets/139356383/19d9968f-7079-40cc-99e1-e30018e74a52)
![image](https://github.com/siyuan-note/siyuan/assets/139356383/a6d94cc4-3620-49b4-8c69-5ec993b2e4ff)
仍然出问题

**Comment by 88250** [comment]
版本还没发布……

**Comment by gaoluji** [comment]
> 版本还没发布……

原来如此……（苦笑）

**Comment by gaoluji** [comment]
> 版本还没发布……

D大，我试了最新的测试版，似乎重新打开间隔重复仍然有新卡重置的问题

**Comment by gaoluji** [comment]
> 这个是设计如此嘛，不会按天计算的，人为控制。

但这样弄的话，不太能计划行事。——思源中的复习时间是真的按几分钟来算，但这样来，就真的是通过几分钟后打开再复习，但这样弄又会导致学习新卡片。
虽然算法为了实现精确科学来考虑，但实际上目前的间隔重复软件都做了取舍，以天来算。
思源笔记的间隔重复其实是可以和remnote对标的。
实际上用天来算就是为了使计划能够持续，按分钟来算实际上根本不能控制。

**Comment by 88250** [comment]
人为控制一下。。。。一天开一次，时间多的时候可以按算法多开几次，这样灵活一些。



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 9, 2023 22:53 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Document-level new card/review card limitcontrol (Issue #9365)




  
这个是设计如此嘛，不会按天计算的，人为控制。
  
但这样弄的话，不太能计划行事。——思源中的复习时间是真的按几分钟来算，但这样来，就真的是通过几分钟后打开再复习，但这样弄又会导致学习新卡片。
 虽然算法为了实现精确科学来考虑，但实际上目前的间隔重复软件都做了取舍，以天来算。
 思源笔记的间隔重复其实是可以和remnote对标的。
 实际上用天来算就是为了使计划能够持续，按分钟来算实际上根本不能控制。

**Comment by gaoluji** [comment]
> 人为控制一下。。。。一天开一次，时间多的时候可以按算法多开几次，这样灵活一些。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Oct 9, 2023 22:53 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [siyuan-note/siyuan] Document-level new card/review card limitcontrol (Issue #9365) 这个是设计如此嘛，不会按天计算的，人为控制。 但这样弄的话，不太能计划行事。——思源中的复习时间是真的按几分钟来算，但这样来，就真的是通过几分钟后打开再复习，但这样弄又会导致学习新卡片。 虽然算法为了实现精确科学来考虑，但实际上目前的间隔重复软件都做了取舍，以天来算。 思源笔记的间隔重复其实是可以和remnote对标的。 实际上用天来算就是为了使计划能够持续，按分钟来算实际上根本不能控制。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

要不还是征集一下意见吧……看看这个间隔重复有多少人用，以及他们的看法吧……

**Comment by 88250** [comment]
嗯，我们一直在收集反馈。
