### ISSUE TITLE
搜索引用块的加强

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#937]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
当我们在整理笔记的时候，只关心文档级的引用，对于块级别太细碎无法立刻定位到想要引用的内容，例如写专题笔记更注重文档级别的引用，目前（（和【【语法是不区分搜索文档和非文档块的
还有一种情况例如在整理法条类笔记的时候，因为法条类笔记本身层次结构分明，例如无法哪个法规都会有第一条-第N条，我们在引用某一条的时候显然直接（（第一条是不合适的，但是我知道我要引用哪个法律的某一条，这样就首先会确定哪个文档，然后在该文档中查找块
总之一切为了提高写引用笔记的效率。
### 描述最优的解决方案 Describe the optimal solution
（（语法搜索所有，【【语法只搜索文档级
当语法中出现/，#或者其他特定转义字符，就锁定在该文档下继续检索
### 描述候选解决方案 Describe the candidate solution
在目前检索方式不变的情况下，加入快捷键或者引用检索框加强，例如加几个按钮，支持正则表达式等

**Comment by 88250** [comment]
你好，块引搜索支持类型过滤的，可以使用 `((d:文档名`，具体请参考帮助文档试试看，谢谢。
