### ISSUE TITLE
Export related flashcard data when exporting .sy.zip

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9372]
导出思源格式的数据时闪卡数据应当一块导出

### In what scenarios do you need this feature?

当我导出一个工作空间的文件于另一个工作空间时，闪卡数据并没有被导入进去，相反，它是分离的数据。
如果另一个工作空间也有闪卡，则两个闪卡的数据是无法兼容的

### Describe the optimal solution

改善导出时候的闪卡数据，应当一块被带过来

**Comment by 88250** [comment]
你指的是导出文档 .sy.zip 吗？

**Comment by gaoluji** [comment]
> 你指的是导出文档 .sy.zip 吗？

是的，如果有两个工作空间，且每个工作空间的闪卡数据不同，这样的话闪卡数据根本弄不了（我的旧的工作空间打开不了一些插件，但在新的工作空间里可以打开插件），所以我需要把数据导入到新的工作空间

**Comment by 88250** [comment]
嗯，目前还没有支持导出导入闪卡数据，暂时先保持 issue 打开，后面处理，谢谢。

**Comment by 88250** [comment]
基本已经实现，补充一下，导出后再导入是算作新卡，不会保留之前的复习进度。因为为了避免重复导入引起块 ID 不一致，所以导入时会重新生成块 ID，类似地，闪卡也是新生成的，所以没有任何复习进度。

**Comment by gaoluji** [comment]
> 基本已经实现，补充一下，导出后再导入是算作新卡，不会保留之前的复习进度。因为为了避免重复导入引起块 ID 不一致，所以导入时会重新生成块 ID，类似地，闪卡也是新生成的，所以没有任何复习进度。

ok，我再看看闪卡有没有好改善的地方，到时候继续推广一下思源
