### ISSUE TITLE
Add plugin CSS and custom CSS to the export PDF page

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9376]
### In what scenarios do you need this feature?

目前在导出 PDF 的时候，主题的 css 样式是生效的。
但是插件的样式却不能生效。

### Describe the optimal solution

希望插件的样式在导出的时候同样生效。

**Comment by terwer** [comment]
+1

**Comment by royc01** [comment]
+1

**Comment by Vanessa219** [comment]
还麻烦举例详述一下。

**Comment by frostime** [comment]
> 还麻烦举例详述一下。

1. link icon 插件在思源中可以显示 url 的图标，但是导出 PDF 后就没有图标了

![image](https://github.com/siyuan-note/siyuan/assets/27268127/962c60b8-ff6e-4520-b9a5-3d63401bee7f)

![image](https://github.com/siyuan-note/siyuan/assets/27268127/4e5ff7e9-105a-42b4-90db-453009a95d80)

2. savor 有一个 callout 样式的功能，这个样式我同样抽离成了一个插件，代码基本是一致的

但是使用 savor 主题导出的时候，callout 样式在PDF中会保留；使用插件的时候，PDF导出里面就没有对应的样式。

savor 可以导出：
![52437e955061626907846b008eda8563](https://github.com/siyuan-note/siyuan/assets/27268127/1cce3fb7-7faf-4391-840f-a19bd2f1b0a7)


 但是插件就不能导出

![b4af3e96366e647ef506f178827e4da8](https://github.com/siyuan-note/siyuan/assets/27268127/3aaf47c0-0024-49b8-99d2-2e30d5a60601)

![8a13dce69ec4f40904b0eef71db55094](https://github.com/siyuan-note/siyuan/assets/27268127/5be6023b-4e27-43af-8ce6-a761677cde9f)

**Comment by Zuoqiu-Yingyi** [comment]
代码片段样式也有同样的需求

**Comment by Vanessa219** [comment]
看了一下，由于 PDF 是单独的静态页面，目前没办法引用插件。但是代码片段是可以添加的。

**Comment by frostime** [comment]
> 看了一下，由于 PDF 是单独的静态页面，目前没办法引用插件。但是代码片段是可以添加的。

请问同样是插入到 head 的 style 标签里，代码片段的css和插件的css有什么区别呢？

还是说导出 PDF 时不是从 head 当中读取 style 样式，而是根据特定的接口获取代码片段 css？如果是这样的话，是否可以给插件提供一个类似 addStyle 的接口，允许插件传入 css 字符串，让其在导出的时候生效？

**Comment by Zuoqiu-Yingyi** [comment]
> 看了一下，由于 PDF 是单独的静态页面，目前没办法引用插件。但是代码片段是可以添加的。

这里是指引用插件的 index.css

**Comment by Vanessa219** [comment]
> > 看了一下，由于 PDF 是单独的静态页面，目前没办法引用插件。但是代码片段是可以添加的。
> 
> 这里是指引用插件的 index.css

@frostime 

link-icon 这个没细看，里面好像是有 js 代码的，如果只加在 css 就可以了话那应该是没有问题的。

**Comment by frostime** [comment]
> > > 看了一下，由于 PDF 是单独的静态页面，目前没办法引用插件。但是代码片段是可以添加的。
> > 
> > 
> > 这里是指引用插件的 index.css
> 
> @frostime
> 
> link-icon 这个没细看，里面好像是有 js 代码的，如果只加在 css 就可以了话那应该是没有问题的。

只需要让 style 里面的 css 生效就行，至于 js 操作的样式可以不用管。

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 能不能在导出图片与导出 PDF 的预览页面中的 `.protyle-wysiwyg` 元素中添加文档块的块属性, 否则一些依托于文档块块属性的样式将会失效
