### ISSUE TITLE
Distinguish between new cards and review cards during spaced repetition

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9377]
间隔重复时区分新卡和复习卡

### In what scenarios do you need this feature?

在复习界面的新卡与旧卡分开来展示：在思源中，新卡和旧卡是直接在一块的
![image](https://github.com/siyuan-note/siyuan/assets/139356383/9f2adaba-8ee2-4386-8f36-073260ca06db)
应当新卡和旧卡是分开来展示的

复习时的新旧卡片顺序
这个应当可以设置为：混合卡片、先新后旧、先旧后新

### Describe the optimal solution

参考anki
![image](https://github.com/siyuan-note/siyuan/assets/139356383/9cf212c2-12c1-42ca-a12f-04fcc05d93ba)
蓝色为新卡片，绿色为旧卡片

**Comment by gaoluji** [comment]
还有 @88250 
复习时的新旧卡片顺序
这个应当可以设置为：混合卡片、先新后旧、先旧后新

**Comment by 88250** [comment]
嗯，等有空再分析下。

**Comment by linearalgebra17** [comment]
支持

**Comment by feihuobuzhun** [comment]
很有意思

**Comment by 88250** [comment]
> 还有 @88250 复习时的新旧卡片顺序 这个应当可以设置为：混合卡片、先新后旧、先旧后新

这个暂时不考虑了，还是按照目前的顺序。

**Comment by 397334469** [comment]
关注

**Comment by 88250** [comment]
> 还有 @88250 复习时的新旧卡片顺序 这个应当可以设置为：混合卡片、先新后旧、先旧后新

关联 https://github.com/siyuan-note/siyuan/issues/10303
