### ISSUE TITLE
Show notebooks in hpath of block ref search list results

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9378]
输入 [[ 搜索块的时候，同时显示块所在的笔记本

### In what scenarios do you need this feature?

多个笔记本中如果有重复名称的文档（实际上这很常见），那么输入 [[ 的时候就很难去区分它们。所以我希望能有更加明显的所属笔记本提示。

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/27268127/80d587e0-0e4a-4e3e-9167-abd8b6d8d21f)

**Comment by JokeenZhang** [comment]
如果只有一个笔记本的话就不用了吧

**Comment by mozhux** [comment]
我感觉直接面包屑拓展成文档面包屑插件那样就行

**Comment by frostime** [comment]
> 我感觉直接面包屑拓展成文档面包屑插件那样就行

这样也可以，就类似这种格式

![image](https://github.com/siyuan-note/siyuan/assets/27268127/f029362a-3f7a-48df-a452-e3fa191c18ef)
