### ISSUE TITLE
在protyle中粘贴内容会不在块内

### ISSUE THREAD

**Issue by WingDr** [siyuan-note/siyuan#9379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

来源于[zettelkasten插件的issue](https://github.com/WingDr/siyuan-plugin-zettelkasten/issues/8)，在protyle内粘贴一段文字，这段文字会出现在块的外面，就像下面这张图一样

![image](https://github.com/siyuan-note/siyuan/assets/63407442/d630de09-d3f4-4ff6-8f35-0c8f1b32936f)

不管是新建卡片的dialog还是新窗口tab里面的protyle都是这样，应该是transactions的过程出了问题

### Expected result

粘贴上去的
`DMD的模态相当于经过处理的SVD的模态的线性组合，在这种情况下一般相当于傅里叶变换`
这句话应该在`20231009134256-7pwz31z`这个块里面

### Version environment

```markdown
- Version: 2.10.8
- Operating System: Windows
- Browser (if used):
```

### Log file

截图控制台

**Comment by 88250** [comment]
我安装插件以后，使用 新建卡片，然后在弹框的编辑器中粘贴内容正常，无法重现该问题。

请安装一下最新的 dev 版本，在默认主题下测试看看。

**Comment by 88250** [comment]
我可以重现问题了，弹框以后鼠标不点击聚焦，直接粘贴会出这个问题。

**Comment by Vanessa219** [comment]
怀疑是聚焦的问题，具体代码不太清楚在哪里，也可能是[这里](https://github.com/WingDr/siyuan-plugin-zettelkasten/blob/37c7cb04c4cc70a0d5b624cb3a073f97a77f9249/src/display/newCardDialog/newCardDialog.svelte#L22C34-L22C43)？

这个是聚焦错误的 range
<img width="1377" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/e7a817fe-3332-4c48-a3ad-ce90c63d1d23">

正常应该是这个样子
<img width="944" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/56f61e65-ba91-48dd-8cf6-17657ffa2816">

**Comment by WingDr** [comment]
懂了，还要等protyle渲染好，确实是这里的问题
