### ISSUE TITLE
页签右键删除和移动文档的功能

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#938]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
有时候笔记多了，在文件树中到到对应的笔记删除或者移动太麻烦了，但是目前引用到文档确是非常方便的
### 描述最优的解决方案 Describe the optimal solution
当然文档页签右键删除文档功能移动文档功能
### 描述候选解决方案 Describe the candidate solution
右键页签定位到文件树也行

**Comment by 88250** [comment]
编辑器页签上右键菜单加删除之前考虑过，因为不是高频功能又要占用一个位置，所以没有引入；文件树定位请用快捷键或者文件树上那个定位按钮，谢谢。

**Comment by GlowBlur** [comment]
好的
