### ISSUE TITLE
数据库单选类型唯一值计数错误

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#9380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/32903588/2704698e-30dd-4045-a11f-a8fa20c066e8)

### Expected result

改进

### Version environment

```markdown
- Version: 2.10.9-dev3
- Operating System: win10
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
感谢反馈，下个版本解决。
