### ISSUE TITLE
ctrl+alt+F can't work in the Spaced Repetition

### ISSUE THREAD

**Issue by qiuqiao** [siyuan-note/siyuan#9384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在PC端的间隔重复页面中，ctrl+alt+F无法制卡或者取消制卡，但打开块菜单，手动选择快速制卡却可以。
测试了一下其他快捷键如ctrl+alt+X，能正常打开外观菜单。

在非间隔重复页面的文档页面、聚焦文档页面上测试，ctrl+alt+F、ctrl+alt+X都正常。

### Expected result

间隔重复页面中，ctrl+alt+F应当像普通的文档界面中的行为一样，即制卡/取消制卡。能在间隔重复页面中随时制卡与取消制卡，对于渐进阅读来说至关重要。

### Version environment

```markdown
- Version: v2.10.8
- Operating System: windows 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/12847549/siyuan.log)

**Comment by Vanessa219** [comment]
感谢反馈，稍后修复。

目前由于隐藏了右侧闪卡标记，取消制卡用户是无感知的。
