### ISSUE TITLE
更改代码片段设置页面中编辑框的字体为等宽字体

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#9385]
### In what scenarios do you need this feature?

现在的`设置-外观-代码片段`默认字体无法分清中文引号和英文引号，且不是等宽字体，不方便查看和编辑

### Describe the optimal solution

将`设置-外观-代码片段`中输入框的字体改为等宽字体，方便编辑，如果有可能，还希望加入语法高亮。

![image](https://github.com/siyuan-note/siyuan/assets/35998162/d88abc9e-25fc-4097-af4d-78d506a01c23)

### Describe the candidate solution

无

**Comment by Vanessa219** [comment]
这个是个 textarea，高亮要改的话比较麻烦，大后期可以再来说一说。
我这里中英文引号是有区别的，目前 dev 已经改了，还麻烦再看看。

**Comment by heartacker** [comment]
> @Vanessa219 谢谢大佬的更新，补充一下，`数学公式块`、`嵌入内容块`的字体也存在分不清引号的问题，是否可以同样改为等宽字体呢？
> 
> ![image](https://user-images.githubusercontent.com/35998162/274224941-4994c166-1665-4225-889e-28751ce78463.png)

建议提一个new issue

**Comment by Vanessa219** [comment]
> @Vanessa219 谢谢大佬的更新，补充一下，`数学公式块`、`嵌入内容块`的字体也存在分不清引号的问题，是否可以同样改为等宽字体呢？
> 
> ![image](https://user-images.githubusercontent.com/35998162/274224941-4994c166-1665-4225-889e-28751ce78463.png)

现在代码片段已经可以正常显示了么？
