### ISSUE TITLE
设置默认打开的工作空间

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#9387]
### In what scenarios do you need this feature?

电脑上有多个工作空间，但是希望每次都是打开主工作空间，而不是打开上一次最后一个打开的工作空间。主要原因是用windows商店下载的siyuan快捷方式难以操作。

### Describe the optimal solution

在设置中增加一个每次都是默认开启某个工作空间的选项。

**Comment by 88250** [comment]
你好，这个不添加支持了，安装包版可以用快捷方式指定，其他版本的话还是按照最后一次打开的为默认，感谢反馈。

**Comment by HowcanoeWang** [comment]
linux上有没有什么启动指令，可以指定默认的工作空间？

**Comment by HowcanoeWang** [comment]
找到了 `siyuan --workspace="/home/hwang/Documents/SiYuan" `

**Comment by TCOTC** [comment]
![Image](https://github.com/user-attachments/assets/34106478-fbbf-435d-935e-92a88edc2fe0)
