### ISSUE TITLE
Authenticate requests of assets other than 127.0.0.1

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9388]
https://ld246.com/article/1696916952777

**Comment by frostime** [comment]
这个会不会影响到插件的路由？有些插件，比如图库、背景之类的需要访问 data 目录下的资源文件。

**Comment by 88250** [comment]
127.0.0.1 加载的话不影响，其他地址的话一开始进入就需要鉴权，所以应该是不影响的，等后面发布 dev 帮忙测试看看。
