### ISSUE TITLE
块删除和粘粘功能

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#939]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

整理笔记的时候，特别是对于笔记内容修整的时候，需要删除和移动块
目前右键有复制块，粘粘块就是没有删除块

### 描述最优的解决方案 Describe the optimal solution

右键增加删除块功能，支持Del快捷键
粘粘块时特别是带格式的和引用的支持不是很好，特别是剪切块的内容，如果被剪切的是一个引用块，黏贴后就只显示 一串ID的文本了，还有有格式的块，黏贴的时候也变成了全文本，粘粘的时候需要区分数据来源是原本思源的还是外来的，这样才方便些。

**Comment by 88250** [comment]
你好，复制的时候请用 
![image](https://user-images.githubusercontent.com/873584/103596862-d4643800-4f39-11eb-8191-7c56ee86f098.png)
 粘贴时请用 
![image](https://user-images.githubusercontent.com/873584/103596878-e0e89080-4f39-11eb-92de-e6bbfc6a8810.png)

删除的话……应该是直接删除内容就好，后期会改进全选功能 https://github.com/siyuan-note/siyuan/issues/889 这样通过键盘也能快捷操作了，谢谢。

**Comment by GlowBlur** [comment]
这知道这个功能，但我的需求不是这个
主要是对原文一模一样的复制，如上操作只是在新地方加了一个到原文的链接
对于大段落的操作删除，我认为选中右键删除效率更高
对了目前对于表格的删除操作有点麻烦

**Comment by 88250** [comment]
粘贴内容的话直接 Ctrl C/V 有问题吗？

**Comment by GlowBlur** [comment]
谢谢，直接使用Ctrl C/V没有问题，但是菜单操作的话有问题，这样的话感觉菜单有点鸡肋，应该不会怎么使用了哈
