### ISSUE TITLE
Rows in the database without bound blocks should not show created and updated

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9391]

**Comment by zxhd863943427** [comment]
在行拥有创建和更新时间的逻辑后，能否使用sy的合并来处理database？

**Comment by 88250** [comment]
同步还是遵循统一的逻辑。



---Original---
From: ***@***.***&gt;
Date: Sat, Oct 14, 2023 17:42 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve database created and updated columnvalues (Issue #9391)




 
在行拥有创建和更新时间的逻辑后，能否使用sy的合并来处理database？
