### ISSUE TITLE
高度计算失效，导致插件显示异常，只有在更改窗口大小后才能恢复

### ISSUE THREAD

**Issue by RogerHuHu** [siyuan-note/siyuan#9398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新到2.10.9后，桌面客户端在打开日程管理插件时，无法正常加载日历视图，在更改窗口大小后可恢复。
通过浏览器访问docker部署的版本时，没有问题。
![B~{HYVTM39IA6@9$}HI_G{1](https://github.com/siyuan-note/siyuan/assets/3404169/5091ec0a-0d73-470d-b908-5de55546c983)
![I3P5CR QRSAEAGYCY~V}L}B](https://github.com/siyuan-note/siyuan/assets/3404169/38b4f60e-9bb2-49cc-920b-ce74b15a1256)
height属性在刚打开插件时，值为0

### Expected result

插件能正常显示

### Version environment

```markdown
- Version: 2.10.9
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
这块代码只是优化了 remote，不太清楚以前为什么可以，目前看来需要把高度的计算放到 init 中，此时 tab 才会被添加好，才有高度。
<img width="717" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/eaca9c5e-46bf-4489-9d48-bf121fa20d08">
