### ISSUE TITLE
文档块的应带变为标题块移动

### ISSUE THREAD

**Issue by gaoluji** [siyuan-note/siyuan#9399]
### In what scenarios do you need this feature?

在思源中，文档能移动到另一文档内部变成标题块。但此操作只能一个一个的拖入进一个文档。
若我拥有多个文档，需要同时变成一个文档内部的标题块，则会很麻烦。

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/139356383/1310888f-0039-4391-ba01-507d7ad5a8a8)
两个文档只能批量移动为子文档，而我需要直接批量移动为文档内容

**Comment by 88250** [comment]
这个无法支持批量操作，要改变和计算的东西太多，容易出问题，所以仅支持单个文档转换为标题，感谢反馈。
