### ISSUE TITLE
网络图片引用失效

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#94]
![image](https://user-images.githubusercontent.com/29135984/94330094-75fef380-fff3-11ea-9bbb-15ae4538e495.png)
在ob没问题

**Comment by 88250** [comment]
麻烦给我一下这个链接的文本，我这里测试看看。

**Comment by zhl111** [comment]
![](https://mmbiz.qpic.cn/mmbiz_jpg/ml6Vz4DXAETmIN6mDicmia2CqPLyicYBnsNBQGYHlLcF1pBjdlf572QzWJxyDUyuWunyz8ddiamw2tqjTDYwbT68eQ/640?wx_fmt=jpeg)
微信平台的图片都不显示，别的网站的还好
![image](https://user-images.githubusercontent.com/29135984/94330263-92039480-fff5-11ea-8c1e-58020075014c.png)

**Comment by 88250** [comment]
v0.2.3 修复，感谢反馈。

**Comment by zhl111** [comment]
我这还不行呀

**Comment by 88250** [comment]
应该是有本地缓存，试下打开开发者工具，把缓存禁用掉，然后在图片后面打个字让它渲染一下看看。

![image](https://user-images.githubusercontent.com/873584/94358284-8c2fb100-00d2-11eb-91f9-737c89d1ca77.png)

**Comment by zhl111** [comment]
好了，缓存还需要打开吗？

**Comment by 88250** [comment]
不需要了，以后正常使用就行了。
