### ISSUE TITLE
文件树大纲等的加强

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#940]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
整理文档和梳理单个文档的结构时需要展开所有的节点，一个一个操作不方便
自定义文件夹和文档图形使导航更加美观
### 描述最优的解决方案 Describe the optimal solution
右键增加全部展开和折叠大纲和文件树的功能
修改文档和文件夹图标功能

**Comment by 88250** [comment]
文档文件夹图标的话估计只能用 Emoji 顶顶了……

文件树和大纲的展开和折叠请关注 https://github.com/siyuan-note/siyuan/issues/564
