### ISSUE TITLE
是否可能允许一个块被加入多个不同书签中？

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9400]
### In what scenarios do you need this feature?

数据表中的书签实质上是属性，是一个（bookmark, block）的数据对。这个结构本身就是多对多的，并不存在数据结构层面对块所属数据的限制。

那么是否有可能允许用户将一个块加入多个不同的书签当中？

### Describe the optimal solution

放开加入书签的操作，允许加入多个不同的书签

![image](https://github.com/siyuan-note/siyuan/assets/27268127/ad4bef65-641b-4096-b65e-9cb555ad1765)

**Comment by 88250** [comment]
书签属性是块上的，和数据库没有关系。bookmark 这个属性设计时就是只允许单值，所以只能一个块加入到一个书签中。
