### ISSUE TITLE
Math and embed block editing use fixed-width fonts

### ISSUE THREAD

**Issue by cesaryuan** [siyuan-note/siyuan#9406]
### In what scenarios do you need this feature?

见 #9385 

![image](https://github.com/siyuan-note/siyuan/assets/35998162/f6f5a651-d626-473b-b40b-43bc3843ac7c)

### Describe the optimal solution

见 #9385

**Comment by Vanessa219** [comment]
话说你这个为啥会分不清呀？是不是设置了什么特殊的字体？

**Comment by cesaryuan** [comment]
> 话说你这个为啥会分不清呀？是不是设置了什么特殊的字体？

好像因为我的默认字体是苹方🤣
