### ISSUE TITLE
2.10.6版本用快捷键创建空白文档只会有一个，2.10.9、2.10.10可以多次创建空白文档

### ISSUE THREAD

**Issue by GuangDai** [siyuan-note/siyuan#9407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在2.10.6版本中，用快捷键创建空白文档一次后有空白文档A，再次使用快捷键会跳转到A

在2.10.9 2.10.10，用快捷键多次创建空白文档，会有空白文档ABCDE...

不知道是不是新的功能，以前的功能对于我每次只需要创建一个新文档的比较方便，但也不是必须的

### Expected result

如上所诉

### Version environment

```markdown
- Version: 2.10.6 2.10.9 2.10.10
- Operating System: ArchLinux
- Browser (if used):
```

### Log file

和上一个issue一样

**Comment by 88250** [comment]
在设置项 新建文档存放位置 为相对路径（包括空值）的情况下，第一次新建一个文档后焦点就在这个文档上了，再次新建时会相对于该文档建立子文档，所以这个是正常预期，感谢反馈。

**Comment by Temacc0531** [comment]
重建索引之后再试下
