### ISSUE TITLE
代码框复制

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#941]
### 描述问题 Describe the problem

* 复制后，代码格式前缩一个tab（或者4个空格，我修改过一个tab=4个空格），并且缺失语言类型
![s1](https://user-images.githubusercontent.com/69628966/103598453-98cb6d00-4f3d-11eb-826c-389e7ec945c2.gif)
### 期待的结果 Expected result

复制代码框的代码，一般是两个使用场景
* 复制某个笔记中的某一段代码 ，到另一个笔记中去。
* 复制某个笔记中的某一段代码 ，到其他软件，比如ide。
我猜想你们会根据场景不同，复制不一样的代码，
* 复制到另一个笔记，会携带\`\`\`
* 复制到其他软件，就单纯的代码。
但是，不知道是不是场景区分有点问题，很多时候，会混淆场景，导致动作错误。
![s2](https://user-images.githubusercontent.com/69628966/103599162-73d7f980-4f3f-11eb-85fb-a7b137158f1f.gif)
所以，我的一个想法是，要不单纯地，不区分使用场景，就单纯的复制代码本身。
我复制到另一个笔记中去，我自己加\`\`\`，自己加语言类型，这样可能会比较简单（不一定简单，哈哈），也比较不会乱，只要你们保证代码复制时，不会改变格式（比如前面的缩一个tab）就行。
复制到其他软件，也不会说是因为有\`\`\`，导致还得手动删除，整理格式。

### 版本环境 Version environment

* 版本 Version：0.55
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

![image](https://user-images.githubusercontent.com/69628966/103599475-2e67fc00-4f40-11eb-851d-ae7b1802ff5c.png)

**Comment by 88250** [comment]
你好，复制的时候是完整的 Markdown 格式，包括了 ` ```lang ` 这部分的，如果在其他软件中粘贴没有这部分那可能是那个软件做了处理。

**Comment by yeshaopeng6688** [comment]
再提一嘴。看到0.5.6有开发自定义快捷键什么的。
真的真的强烈安利**能自定义上下左右**，移手去敲↑↓←→太麻烦。。

**Comment by yeshaopeng6688** [comment]
> 你好，复制的时候是完整的 Markdown 格式，包括了 `` ```lang `` 这部分的，如果在其他软件中粘贴没有这部分那可能是那个软件做了处理。

哦哦。但注意看下第二个截图。。我复制代码失效了。复制的是aaaaa，说明没有复制上。

**Comment by yeshaopeng6688** [comment]
![Uploading image.png…]()

**Comment by 88250** [comment]
点完复制那个按钮以后里面不用首选再复制了……

**Comment by yeshaopeng6688** [comment]
![image](https://user-images.githubusercontent.com/69628966/103600075-910dc780-4f41-11eb-9b1a-85f5fc4e8d06.png)
![image](https://user-images.githubusercontent.com/69628966/103600174-c9ada100-4f41-11eb-9e46-31a783f9aea8.png)

**Comment by yeshaopeng6688** [comment]
> 点完复制那个按钮以后里面不用手选再复制了……

那是因为我点了复制按钮，没有用，我才去全选复制的。 = =。

**Comment by 88250** [comment]
![issue](https://user-images.githubusercontent.com/873584/103600347-290bb100-4f42-11eb-9347-e9013e34c199.gif)

我这里挺正常的……

**Comment by yeshaopeng6688** [comment]
![s3](https://user-images.githubusercontent.com/69628966/103600558-b18a5180-4f42-11eb-85e4-3bfabcc46bf3.gif)
可能bug的问题是，缩进引起的。

**Comment by 88250** [comment]
应该是，缩进的话 md 里就是不带 lang 的代码块了，虽然用围栏代码块可以支持代码内容的缩进，但是复制的时候就没法还原了，因为内容中已经有缩进……

**Comment by yeshaopeng6688** [comment]
![s4](https://user-images.githubusercontent.com/69628966/103601642-075ff900-4f45-11eb-835e-1191313c245d.gif)
如果之前有复制其他内容，再去复制代码，复制不上。🤣🤣🤣，而且这bug时有时无，我都不知道是不是我没选上按钮了。。

**Comment by 88250** [comment]
好的，我们在 https://github.com/siyuan-note/siyuan/issues/665 中一并改进。
