### ISSUE TITLE
Outline supports Ctrl+Click focus opening

### ISSUE THREAD

**Issue by AiurQIAN** [siyuan-note/siyuan#9410]
使用组合键， 从侧旁 outline 直接跳转到对应章节的 focus mode.

### In what scenarios do you need this feature?

使用时， 可能笔记会比较大， 记录内容比较多.
在后续更新的时候 可能只想针对其中某一个章节进行更新.

一般的操作为： 在 outline 中找到对应章节， 点击， 跳转到位置， ctrl + click 进入章节 focus mode
但如果可以直接在 outline 中通过组合键直接进入， 体验感会更好

### Describe the optimal solution

使用组合键 ( 比如 ctrl + click) ， 从侧旁 outline 直接跳转到对应章节的 focus mode.

### Describe the candidate solution

使用组合键 ( 比如 ctrl + click) ， 从侧旁 outline 直接跳转到对应章节的 focus mode.

**Comment by salmund** [comment]
Yes and with hover editor also ?

**Comment by 88250** [comment]
Please try hovering the mouse over the block icon:

![image](https://github.com/siyuan-note/siyuan/assets/873584/1a5a983c-2c71-4953-8adf-791091b755fa)

**Comment by salmund** [comment]
> Please try hovering the mouse over the block icon:
> 
> ![image](https://user-images.githubusercontent.com/873584/275318718-1a5a983c-2c71-4953-8adf-791091b755fa.png)

THANKS !!! 🤩🤩🤩
