### ISSUE TITLE
Supports searching database view content

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9419]

**Comment by jl0476** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/5226690/3ca23cb6-313b-4797-958e-67c58008a648)
![image](https://github.com/siyuan-note/siyuan/assets/5226690/113a23dc-31e2-4939-857b-ffe21e23138c)
![image](https://github.com/siyuan-note/siyuan/assets/5226690/82aae45e-78dc-4425-8776-b42414ba6d1d)


@88250 版本v2.10.11，还是无法搜索数据库内容，是我理解有误吗

**Comment by 88250** [comment]
试试修改视图名称或者单元格列值（不是增减行或者列，而是列中的值，比如 text 列中单元格的值）后等几秒钟后再搜索。

**Comment by jl0476** [comment]
> 试试修改视图名称或者单元格列值（不是增减行或者列，而是列中的值，比如 text 列中单元格的值）后等几秒钟后再搜索。

我是新建的视图。
按你说的也无法搜索，如图。
![image](https://github.com/siyuan-note/siyuan/assets/5226690/7a988a31-10a8-40c0-89e1-f7fc3e19a65c)
![image](https://github.com/siyuan-note/siyuan/assets/5226690/fb059f6e-adb0-4d29-95c1-2c507bf34735)

**Comment by 88250** [comment]
看下是不是没有打开类型过滤中的 数据库 块类型。

**Comment by jl0476** [comment]
> 看下是不是没有打开类型过滤中的 数据库 块类型。

之前确实没打开，但是打开了之后也搜不到。
重建了索引，修改了视图的名称和行数据。新建属性视图，均搜不到。
![image](https://github.com/siyuan-note/siyuan/assets/5226690/3e7a4580-1370-472a-9a5f-57957a2b11cf)
![image](https://github.com/siyuan-note/siyuan/assets/5226690/29c6c22a-4908-4db6-a984-8ea5f69201b7)

**Comment by jl0476** [comment]
我又尝试把搜索数据库块类型开关关闭又打开，可以搜索到了。
操作过程是这样的，看看可不可以复现。
1. 从官网新下载2.10.11并安装
2. 再搜索中打开数据库搜索开关，此时搜索不到数据库块内容。
3. 关闭数据库块搜索开关，重新打开，可以搜索到数据库块内容。

![image](https://github.com/siyuan-note/siyuan/assets/5226690/912987fa-3357-43fa-8811-bca6e1b0a03e)

**Comment by 88250** [comment]
有两个地方的过滤需要调整，一个是 设置 - 搜索 中的全局设置，还有一个是搜索功能中的类型过滤（那个漏斗）。

**Comment by 88250** [comment]
能搜索到的话先这样吧，这两个选项对于全新安装的用户来说默认是打开的。

**Comment by jl0476** [comment]
> 能搜索到的话先这样吧，这两个选项对于全新安装的用户来说默认是打开的。

好的，辛苦了。晚安。

**Comment by 88250** [comment]
感谢，晚安。

**Comment by wk-coder** [comment]
> 有两个地方的过滤需要调整，一个是 设置 - 搜索 中的全局设置，还有一个是搜索功能中的类型过滤（那个漏斗）。

试了下，设置中的那个可以打开，ctrl p 的时候漏斗中的数据库只能当次搜索，这次打开，下次在使用自动又关了。不知道是我这自己的问题还是都是这样

**Comment by 88250** [comment]
@wk-coder 我这里测试正常，升级最新版试试？

**Comment by wk-coder** [comment]
> @wk-coder 我这里测试正常，升级最新版试试？

就是最新版，有点奇怪
