### ISSUE TITLE
思源笔记日记功能个人建议

### ISSUE THREAD

**Issue by congjinyebaiya** [siyuan-note/siyuan#942]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

日记功能应该现代笔记软件的必备功能之一了吧，可能不同软件叫法不一样，但是最核心的功能是一样的——那就是满足最便捷无障碍的快速记录和方便管理

### 描述最优的解决方案 Describe the optimal solution

我觉得我心目中的思源的日记功能应该满足以下几点：
- 入口简单（想记录的时候点击一下就能直接进入写作模式而不需要跟其他类型笔记一样需要找到对应的文件夹，新建，命名，开始写作, 从源头让用户可以无负担的开始记录）
- 可以做一个一级菜单，点击就可以自动生成一篇对应日期为名的笔记文件，没有任何其他多余的东西，不会在记录的时候被打断灵感

比如可以参考一下 RoamResearch:
![](https://i.loli.net/2021/01/05/KnC7gtT34Fec96b.png)

或者像 logseq 这样：
![](https://i.loli.net/2021/01/05/9csiWBrXZ5z4HxY.png)

- 我觉得上述两者中的大纲式笔记在日记功能里可能也是一个非常值得借鉴的点，大纲在简洁的前提下能做到极其优雅的排版，一条一条的列项和永远空着的最后一行也更容易激发出写日记时的灵感
- 在全局关系图中有对应的过滤日记的选项，不然的话关系图可能可视化方面就会比较差一点

**Comment by congjinyebaiya** [comment]
不知道图床为什么加载不出来，反正就是 RR 和 logseq 的日记功能的截图, D大应该见过（确信.jpg）

**Comment by 88250** [comment]
你好，之前已有计划，请关注 https://github.com/siyuan-note/siyuan/issues/399 谢谢。
