### ISSUE TITLE
使用浏览器发送文章至siyuan出现Cannot read properties of null (reading 'tagName')报错

### ISSUE THREAD

**Issue by ccxuy** [siyuan-note/siyuan#9422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用浏览器发送文章至siyuan出现Cannot read properties of null (reading 'tagName')报错，且siyuan内未出现文章

### Expected result

无报错

### Version environment

```markdown
- Version: 
- Operating System: Windows 10
- Browser (if used): Google Chrome
```

### Log file

NA

**Comment by ccxuy** [comment]
卸载插件后重装插件并配置后恢复正常，原因不明

**Comment by 88250** [comment]
如果是新安装插件，需要刷新页面后再剪藏，不然可能会有该问题。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
