### ISSUE TITLE
Remnote's style calendar view

### ISSUE THREAD

**Issue by salmund** [siyuan-note/siyuan#9429]
### In what scenarios do you need this feature?

- intuitive calendar view to write daily notes
- review old notes easily

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/105465034/71dfe0eb-b4fb-45d9-ab16-0f1d29393eef)

**Comment by 88250** [comment]
Please try this plugin in the marketplace:

![image](https://github.com/siyuan-note/siyuan/assets/873584/3067de3a-2e64-458f-93d5-5314f98c4f09)

**Comment by salmund** [comment]
Wow thanks !!! 👌🤩🥳❤️
