### ISSUE TITLE
最新版本的搜索内容，搜索排列又乱序了

### ISSUE THREAD

**Issue by guidongyuan** [siyuan-note/siyuan#943]
### 描述问题 Describe the problem

上一个版本更新了，搜索出来的内容，会优先显示文件，然后再显示内容。
更新了alpha后，可以搜索到文件，但是发现文件不是在前面，而是穿插显示。

### 期待的结果 Expected result

和之前一致，优先显示文件，再显示内容。

![image](https://user-images.githubusercontent.com/13446866/103642502-2df65200-4f8e-11eb-9766-28abc7fe38ee.png)

### 版本环境 Version environment

* 版本 Version：当前版本 v0.5.6-alpha1 / Kernel v0.5.6-alpha1
* 操作系统 Operating system：window 10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
收到，056 正式版修复。
