### ISSUE TITLE
Show block name, aliase and memo in search results

### ISSUE THREAD

**Issue by Louie997** [siyuan-note/siyuan#9430]
在 Ctrl+P 搜索中顯示內容塊的命名、别名、備註

### In what scenarios do you need this feature?

有時用 Ctrl+P 搜索時會想順便看一下內容塊的命名、别名、備註，但這些屬性不會直接顯示在 Ctrl+P 搜索結果中，如下圖：
![image](https://github.com/siyuan-note/siyuan/assets/88768177/f52f1682-15e7-4d67-aa71-39db2f5abbda)

### Describe the optimal solution

希望在 Ctrl+P 搜索結果中能夠顯示這些屬性，如同用`【【`搜索時顯示的一樣：
![image](https://github.com/siyuan-note/siyuan/assets/88768177/a64d0c41-701c-4a5b-b3a1-4b2a3c264ce1)

**Comment by gaoluji** [comment]
兹磁
