### ISSUE TITLE
Hide text toolbar when using ref on the mobile

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#9431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![Screenshot_20231015_003656](https://github.com/siyuan-note/siyuan/assets/32903588/2b802045-683e-4c9e-a844-569320bae0a0)

### Expected result

改进

### Version environment

```markdown
- Version: 2.10.10
- Operating System: Android
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
我这样操作重现不了，是要怎么操作呢？

https://github.com/siyuan-note/siyuan/assets/970828/ffc09e1a-566f-4d1d-aaad-7b884a8ebdfb

**Comment by TinkMingKing** [comment]
我这里就是会这样，要不你多试几次试试，长按显示文字菜单，然后点双链按钮，实在复现不了就关了吧，没准是系统问题

**Comment by Vanessa219** [comment]
哦，多试几次就可以了。下个版本改进，多谢。
