### ISSUE TITLE
公式弹出窗口显示问题

### ISSUE THREAD

**Issue by xfdj** [siyuan-note/siyuan#9434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

公式预览过长的时候，弹出框的长度会超出屏幕显示范围，导致无法点击关闭按钮，鼠标无法向左拖动到能显示关闭的位置。下方截图的宽度是整个屏幕的宽度了。

### Expected result

.

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/38575841/48b4e831-5d93-4cba-8474-37b7db3df03a)

### Version environment

```markdown
- Version: 2.10.10
- Operating System: Windows 10 x64
- Browser (if used): App from Microsoft Store
```

### Log file

.

**Comment by Vanessa219** [comment]
这个是不是使用了插件，正常的编辑层是没有预览的。如果是插件的问题，可以在集市中打开插件，找到插件的项目，去上面提 issue。

**Comment by zxhd863943427** [comment]
这个是数学增强插件的插件效果，同时它不支持直接使用\\换行。
