### ISSUE TITLE
Ctrl+滚轮放大字体时，代码块的左边颜色没跟着调整

### ISSUE THREAD

**Issue by psyuhen** [siyuan-note/siyuan#9436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/6522440/c49c11bd-4b97-4344-99e0-c946586b25bf)

### Expected result

![image](https://github.com/siyuan-note/siyuan/assets/6522440/3609db73-6307-4cab-adb6-ec0118bb7f6d)

### Version environment

```markdown
- Version: 2.10.6
- Operating System: windows 11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
请升级版本后再试试，我们这里在最新版（v2.10.10）上已经无法重现。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
