### ISSUE TITLE
在 ``` 标记的代码框编辑文本时，选中多行代码后，shift+tab 能否兼容空格？

### ISSUE THREAD

**Issue by dusdong** [siyuan-note/siyuan#9437]
### In what scenarios do you need this feature?

目前在 ``` 标记的代码框编辑文本时，选中多行代码后，按 tab / shift+tab 键可以对选中行进行tab缩进/反缩进。
但如果是从外部复制到siyuan的代码，很多情况下代码是使用空格缩进的；这时，使用 shift+tab 键进行反缩进时，siyuan无法识别。

### Describe the optimal solution

比如Notepad2中，shift+tab 可以对tab符号、空格兼容。shift+tab 每次退两个空格，直至空格全部退格完毕。

**Comment by Vanessa219** [comment]
配置这个为需要缩进的 Tab 数再试试
<img width="1073" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/30babd45-a3bc-48e8-ab35-8954e7cc9fba">

**Comment by dusdong** [comment]
1、这个需求针对的是：shift+tab，反缩进
2、来源的代码tab数不固定，无法设置 Tab 数
3、希望可以兼容各种长度空格的反缩进

下面是 Notepad2 的演示：

![1](https://github.com/siyuan-note/siyuan/assets/3461709/9b9f18dc-9389-407d-b485-5a170c266dfd)

感谢~

**Comment by Vanessa219** [comment]
这个目前实现不了，可在 IDE 中修改后再进行粘贴。

**Comment by Achuan-2** [comment]
如果能直接在思源能shift tab代码就好了，不兼容空格真的挺难受的，每次粘贴都要用外部编辑器改改

**Comment by Vanessa219** [comment]
目前只可以简单的 shift tab，限制比较多。
