### ISSUE TITLE
Table cannot paste text correctly

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When pasting text in a table, the pasted text will run to the bottom of the table and cannot be in a cell

### Expected result

Can be correctly pasted into table cells

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/60436214/e011783b-b922-450b-99e9-e5645349a062)

### Version environment

```markdown
- Version:  2.10.11
- Operating System: Win11
- Browser (if used):
```

### Log file

none

**Comment by Vanessa219** [comment]
0aef5b164c16ad1c7eee3051ba055f0862f0fae7

**Comment by Vanessa219** [comment]
0b29428994fa4a1e63e6d01409aaae92486c3094
