### ISSUE TITLE
思源笔记折行问题

### ISSUE THREAD

**Issue by yahhossu** [siyuan-note/siyuan#944]
![思源](https://user-images.githubusercontent.com/77004889/103647354-22a72480-4f96-11eb-824f-c9dbe45a2673.jpg)
1、思源笔记直接敲回车的时候，每一行都是一个块，可以被单独引用；
2、用<br>折行，然后把<br>删掉，在上面打字，行间距相对紧凑，且整块（3句话）同时被引用；
请问第二种情况如何才能简单的实现，目前是“用<br>折行，然后把<br>删掉”，有没有直接一点的操作？

**Comment by 88250** [comment]
Shift + Enter
