### ISSUE TITLE
Cloning / mirror note system

### ISSUE THREAD

**Issue by salmund** [siyuan-note/siyuan#9442]
### In what scenarios do you need this feature?

When I discover a concept and I take a note of it in my journal, I could maybe reference the same note in another tree, but it would be the same note...

Changes to one would affect the other

### Describe the optimal solution

Mirror note system like in Trilium :
- it's the same note but it can be present in multiple trees

**Comment by 88250** [comment]
Please try to use query embed block instead of it.
