### ISSUE TITLE
在KDE中使用KDE样式的Minimize/Maximize/Restore/Close按钮

### ISSUE THREAD

**Issue by perok8** [siyuan-note/siyuan#9444]
### In what scenarios do you need this feature?

在KDE中使用的时候，外观上与其他KDE程序不太协调，使用KDE样式的Minimize/Maximize/Restore/Close按钮感觉会好一点。

### Describe the optimal solution

在KDE中直接使用KDE样式的Minimize/Maximize/Restore/Close按钮，或者像Firefox、Chrome那样添加一个“Use system title bar and borders“的选项

**Comment by GuangDai** [comment]
我也是KDE用户，没必要吧...太多和KDE不一样的，好看就行了

**Comment by 88250** [comment]
感谢提议，诚如楼上所言，将就顶顶吧，我关闭 issue 了。
