### ISSUE TITLE
反链窗口面包屑与命名、别名等属性显示重合

### ISSUE THREAD

**Issue by xfdj** [siyuan-note/siyuan#9445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如图所示

### Expected result

首先希望解决重合问题，其次是提一个小建议：在反链面板中，面包屑的默认显示，其实让内容辨识起来更加费劲了，阅读反链的笔记内容比较费眼。面包屑的上的文字其实也和块的内容或者命名是重复的，建议可以调整一下面包屑的对比度和大小，或者将面包屑自动隐藏，鼠标悬浮再显示。望采纳~并感谢开源开发者的辛勤付出~

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/38575841/295dfcea-b974-4093-8de3-6ffb229ac89d)

### Version environment

```markdown
- Version: 2.10.10
- Operating System: Windows 10
- Browser (if used):
```

### Log file

.

**Comment by Vanessa219** [comment]
面包屑在这里起到一个分割和导航的作用，不建议进行隐藏。为了整体保持一致，目前就不对外观进行修改了。
