### ISSUE TITLE
The access authorization code command line parameter (--accessAuthCode) must be set when deploying via DockerPlease enter the title of the bug report

### ISSUE THREAD

**Issue by crendy** [siyuan-note/siyuan#9447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

docker 部署 2.10.11 版本，启动报错：The access authorization code command line parameter (--accessAuthCode) must be set when deploying via Docker

### Expected result

正常启动

### Version environment

```markdown
- Version: 2.10.11
- Operating System: docker
- Browser (if used):
```

### Log file

docker

**Comment by Temacc0531** [comment]
如报错所示，需要在启动命令加入授权码参数`--accessAuthCode`

**Comment by crendy** [comment]
使用的是极空间的docker管理工具 ， 无法自己配置命令， 之前2.10.7之前的设置都没问题：
![Uploading image.png…]()

**Comment by 88250** [comment]
抱歉我没有用过这个，但我感觉应该是可以设置参数的，网络搜索一下看看。



---Original---
From: ***@***.***&gt;
Date: Wed, Oct 18, 2023 15:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] The access authorization code command lineparameter (--accessAuthCode) must be set when deploying via DockerPlease enterthe title of the bug report (Issue #9447)




 
使用的是极空间的docker管理工具 ， 无法自己配置命令， 之前2.10.7之前的设置都没问题：

**Comment by Temacc0531** [comment]
你这个图上栏右边的命令项里面看看？我也没有用过这个...

**Comment by 88250** [comment]
这个不是程序的问题，我关闭了，感谢反馈和理解。

**Comment by 88250** [comment]
这个不是程序的问题，我关闭了，感谢反馈和理解。

**Comment by 88250** [comment]
这个不是程序的问题，我关闭了，感谢反馈和理解。

**Comment by crendy** [comment]
> 你这个图上栏右边的命令项里面看看？我也没有用过这个...

<img width="635" alt="image" src="https://github.com/siyuan-note/siyuan/assets/6448115/16fd292d-773b-4311-9548-916a6808d521">

**Comment by crendy** [comment]
> 这个不是程序的问题，我关闭了，感谢反馈和理解。

v2.10.7之前都是可以的

**Comment by 88250** [comment]
后面特意加上的，必须设置 访问授权码 才能启动，避免在互联网裸奔。



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 19, 2023 09:59 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] The access authorization code command lineparameter (--accessAuthCode) must be set when deploying via DockerPlease enterthe title of the bug report (Issue #9447)




  
这个不是程序的问题，我关闭了，感谢反馈和理解。
  
v2.10.7之前都是可以的

**Comment by crendy** [comment]
> 后面特意加上的，必须设置 访问授权码 才能启动，避免在互联网裸奔。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Oct 19, 2023 09:59 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [siyuan-note/siyuan] The access authorization code command lineparameter (--accessAuthCode) must be set when deploying via DockerPlease enterthe title of the bug report (Issue #9447) 这个不是程序的问题，我关闭了，感谢反馈和理解。 v2.10.7之前都是可以的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

噢噢 那目前就是我这个docker管理软件 不支持加参数.....

**Comment by crendy** [comment]
> > 后面特意加上的，必须设置 访问授权码 才能启动，避免在互联网裸奔。
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Oct 19, 2023 09:59 AM To: _**@**_.**_>; Cc: _**@**_._**>;"State _**@**_.**_>; Subject: Re: [siyuan-note/siyuan] The access authorization code command lineparameter (--accessAuthCode) must be set when deploying via DockerPlease enterthe title of the bug report (Issue #9447) 这个不是程序的问题，我关闭了，感谢反馈和理解。 v2.10.7之前都是可以的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 噢噢 那目前就是我这个docker管理软件 不支持加参数.....

问了一下，目前这个工具暂时还不支持自己设置参数，这个参数能在部署完成后 使用阶段做提示让用户设置吗？比如打开笔记的时候 如果没有设置授权码，提示去设置中心去设置，不要在docker部署或启动阶段做限制？

**Comment by crendy** [comment]
> 后面特意加上的，必须设置 访问授权码 才能启动，避免在互联网裸奔。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Oct 19, 2023 09:59 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;;"State ***@***.***&gt;; Subject: Re: [siyuan-note/siyuan] The access authorization code command lineparameter (--accessAuthCode) must be set when deploying via DockerPlease enterthe title of the bug report (Issue #9447) 这个不是程序的问题，我关闭了，感谢反馈和理解。 v2.10.7之前都是可以的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

目前我使用的这个工具暂时还不支持自己设置参数，这个参数能改成 在docker部署启动完成后使用阶段做提示让用户设置吗？
比如用户打开笔记的时候 ，如果没有设置授权码，提示去设置中心去设置，不要在docker部署或启动阶段做限制？

**Comment by 88250** [comment]
考虑到潜在的安全风险，暂时不作调整了，见谅。

**Comment by Temacc0531** [comment]
论坛里面看到其他用户的配置，可以参考试试
![image](https://github.com/siyuan-note/siyuan/assets/101307399/1c41cb03-36f5-4e2d-b1ca-bb635cdb6588)

**Comment by crendy** [comment]
> --accessAuthCode

谢谢 已解决：
<img width="644" alt="image" src="https://github.com/siyuan-note/siyuan/assets/6448115/7fe2c66e-2fa1-43d9-8dd8-701d49e54016">
