### ISSUE TITLE
编辑器 Ctrl 点击标签触发搜索页签

### ISSUE THREAD

**Issue by moonlune** [siyuan-note/siyuan#945]
思源笔记用了这么久，也尝试寻找新的想法，今天在写东西的时候突然想到一个问题，既然思源笔记是突出网状的笔记，那么能否加强下**标签**的功能？

众所周知，现在有很多基于标签的文件管理软件，通过把**多个标签联合**起来创建条件达到筛选某些资料的效果，例如某份资料既属于**某一年**的，也属于**某个项目**的，还属于**某个单位**的等等，那么通过：**年份+项目+某个单位** 的标签就可以定位到某一份或者几份资料；但是这些软件仅仅限于都某个资料个体的管理，而达不到对资料内部的某一段实现关联筛选与管理；

我想如果所要选找的资料位于多篇文章的多个段落，那么是否可以实现网状与筛选呢？例如几篇文章中的，基于某几个条件的**预设标签**的筛选？

或者在文内通过某几个标签设定文章的属性锚点后，然后在标签栏中，可以把**几个标签联合**起来达到某个筛选条件？

谢谢！

**Comment by 88250** [comment]
谢谢，之前有用户建议过 https://ld246.com/article/1604982159923 应该和你的想法类似。

我们也有同样的想法，预计会在 v0.6.x 着手实现，谢谢。
