### ISSUE TITLE
Add plugin event bus `paste`

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9452]
### In what scenarios do you need this feature?

一些特殊情况下粘贴内容到思源的结果还是不太理想，希望可以开一个接口允许用户自定义
![image](https://github.com/siyuan-note/siyuan/assets/27268127/1b33d1c5-f53d-4138-aa56-2b85ed1e754e)

例如从 zotero 粘贴标注过来的时候，会自动把文字高亮，如果有这种接口就可以自定义去掉高亮的功能
![4771d1f77537c1a778ad629553b03d20](https://github.com/siyuan-note/siyuan/assets/27268127/4b9f4b29-f845-4bfa-8bdc-fbf71b8e86d0)

### Describe the optimal solution

略

**Comment by zxhd863943427** [comment]
支持，需要这个事件改进粘贴的处理。

**Comment by zxhd863943427** [comment]
这个事件能否劫持官方的粘贴处理？就是使用插件处理后的结果替换官方原本的结果？

**Comment by pisceswb** [comment]
请问大神们，有没有可能从网页能够直接拖动图片到思源笔记中，成为思源笔记的本地图片呢？部分网站可能需要登录用户名和密码，不知有没有大神感兴趣做一个这样的插件

**Comment by 88250** [comment]
@pisceswb 可能是目标网页的服务端有反盗链，这个不一定能绕过，可以看下内核日志，上面会有相关细节记录。

**Comment by pisceswb** [comment]
> @pisceswb 可能是目标网页的服务端有反盗链，这个不一定能绕过，可以看下内核日志，上面会有相关细节记录。

返回的是failed: 401，需要在思源中登录网页？是不是就没法解决了

**Comment by 88250** [comment]
在思源中登录网页没有作用，因为这个是内核发起的请求，估计是没有办法了，除非目标站的能够设置不鉴权，或者开个白名单（比如根据 User-Agent）。

**Comment by pisceswb** [comment]
> 在思源中登录网页没有作用，因为这个是内核发起的请求，估计是没有办法了，除非目标站的能够设置不鉴权，或者开个白名单（比如根据 User-Agent）。

了解了，感谢D大🌷
