### ISSUE TITLE
Add plugin event bus `switch-protyle`

### ISSUE THREAD

**Issue by shenjinglei** [siyuan-note/siyuan#9454]
### In what scenarios do you need this feature?

我正在开发“关系图增强”插件，我想要实现根据当前文档自动更新关系图的功能。当前我的做法是监听click-editorcontent事件，但是这需要用户在打开文档后额外再点击一次内容块，才能触发该插件重新绘图。

### Describe the optimal solution

最好能提供一个类似 TabSelectedChanged 的事件。这样我能根据当前文档的变化来重新绘图。我看到当前思源自带的关系图是能根据当前文档自动更新的，我不知道是怎么实现的，我想是不是我漏过了什么其他实现方式，也可以指导我下。 
![Snipaste_2023-10-20_09-52-41](https://github.com/siyuan-note/siyuan/assets/11613616/83eb7d68-5d43-434e-a1e5-967307a91f88)

**Comment by Vanessa219** [comment]
修改文档时没有更新对应的关系图，你是怎么操作以后会更新对应的关系图的？

**Comment by shenjinglei** [comment]
插件设置中有一个“自动跟随打开的文档”，需要选择“是”。
![image](https://github.com/siyuan-note/siyuan/assets/11613616/399d50c4-cfff-4318-9dc2-23bcd1996f11)
![image](https://github.com/siyuan-note/siyuan/assets/11613616/4f9b8731-f342-4a50-bb82-d0252f3935bf)

**Comment by shenjinglei** [comment]
如果是增加了链接，增加了文章。需要手动点一下刷新按钮去更新下数据。

**Comment by Vanessa219** [comment]
切换文档主要通过  updatePanelByEditor 中的 updateBacklinkGraph 进行更新。由于页签可以分屏，因此在点击的时候也会调用该方法，如果需要使用的话，插件需要自己记录 protyle.block.rootID 和 protyle.block.id，然后判断是否需要更新。

**Comment by 88250** [comment]
没有问题的话我先关闭了哦，如果还有问题请继续跟帖，谢谢。

**Comment by shenjinglei** [comment]
那 updatePanelByEditor 中的 updateBacklinkGraph，可以做一个事件出来吗？方便插件监听来更新插件的渲染。

**Comment by Vanessa219** [comment]
> 那 updatePanelByEditor 中的 updateBacklinkGraph，可以做一个事件出来吗？方便插件监听来更新插件的渲染。

可以的， `switch-protyle`

**Comment by shenjinglei** [comment]
哈哈，那太好啦，谢谢。

**Comment by Vanessa219** [comment]
dev 分支已提交，你试一下

**Comment by shenjinglei** [comment]
我现在还没有siyuan的开发环境，dev暂时还跑不起来。

**Comment by 88250** [comment]
等会发布 dev 版吧。

**Comment by shenjinglei** [comment]
好的

**Comment by shenjinglei** [comment]
- 我这边测试了， `switch-protyle`事件没有问题。
- 但是发现，在关闭最后一个页签后。页签位置显示空白，然后就再也打不开文档了。重启思源之后也无法打开任何文档。切换另一个工作空间才能正常使用。而这个空间就再也无法使用了。（可复现，未安装插件）
![test1](https://github.com/siyuan-note/siyuan/assets/11613616/4aa8cf12-b272-4429-a38f-fadfb17d402b)
思源是安装的 siyuan-v202310281648-win.exe
但是显示的版本是
![test2](https://github.com/siyuan-note/siyuan/assets/11613616/7933dfe5-06f2-494b-89ba-6098b4af706b)

**Comment by Vanessa219** [comment]
谢谢反馈，更新到昨晚的版本再试试。界面损坏的话可以使用重置界面。

**Comment by shenjinglei** [comment]
dev4版本已测试，没发现问题。
