### ISSUE TITLE
After pressing Escape, the pop-up layer only closes the top layer

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

闪卡复习状态下通过ctrl+p打开搜索后按esc关闭搜索会连带闪卡一起关闭

### Expected result

希望能修复

### Version environment

```markdown
- Version: 最新发行版
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by Crowds21** [comment]
我也有类似的问题.

能否类似通过 cmd+shift+f 能够将搜索栏当做页签显示.闪卡能否也能够支持类似页签的显示方式?

我个人的场景是这样的: 我每天大概限制的是复习 50 张卡. 完成了每天的复习任务之后卡池里面还会剩下一些没有复习的卡和需要学习的卡,但是总体数量是会不断减少的.

然后我在复习某张卡的时候,我会突然想到一些之前没意识到的问题,或者发现相关的其他卡片需要做出一定的调整. 但是这时候如果我关掉了间隔复习的页面. 我再次打开,我就又得重头看 50 张卡. 

我的需求是: 我希望我能够在背诵记忆卡片的时候,随时能够对其他笔记进行修改调整或者是记录一些突然想到的东西. 目前这个不断开关的方式很影响学习的流畅程度. 
修复目前这个 Issues 我觉得可行, 但是我个人还是喜欢那种分开的界面显示. 不知道其他人都什么想法.

**Comment by Vanessa219** [comment]
> 我也有类似的问题.
> 
> 能否类似通过 cmd+shift+f 能够将搜索栏当做页签显示.闪卡能否也能够支持类似页签的显示方式?
> 
> 我个人的场景是这样的: 我每天大概限制的是复习 50 张卡. 完成了每天的复习任务之后卡池里面还会剩下一些没有复习的卡和需要学习的卡,但是总体数量是会不断减少的.
> 
> 然后我在复习某张卡的时候,我会突然想到一些之前没意识到的问题,或者发现相关的其他卡片需要做出一定的调整. 但是这时候如果我关掉了间隔复习的页面. 我再次打开,我就又得重头看 50 张卡.
> 
> 我的需求是: 我希望我能够在背诵记忆卡片的时候,随时能够对其他笔记进行修改调整或者是记录一些突然想到的东西. 目前这个不断开关的方式很影响学习的流畅程度. 修复目前这个 Issues 我觉得可行, 但是我个人还是喜欢那种分开的界面显示. 不知道其他人都什么想法.

可点击闪卡中的 
<img width="263" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/4d362874-26c1-438b-9f75-a773c9db2639">
