### ISSUE TITLE
在复习闪卡的时候快速定位原文；闪卡界面

### ISSUE THREAD

**Issue by linglongyoudoufu** [siyuan-note/siyuan#9457]
### In what scenarios do you need this feature?

扩展很有用，在复习闪卡的时候想要更改内容总是会用到扩展，目前的复习界面不能利用扩展，所以希望能快速回到原文来修改或增减闪卡
或者是在闪卡界面也能够利用扩展，但是感觉太麻烦了
---
复习界面如何改为默认最大化

### Describe the optimal solution

。

**Comment by 88250** [comment]
这个不考虑调整了，复习界面和管理是分开设计的，感谢反馈。

**Comment by 88250** [comment]
这个不考虑调整了，复习界面和管理是分开设计的，感谢反馈。
