### ISSUE TITLE
loaded-protyle event improvement

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#9458]
### In what scenarios do you need this feature?

文档会在许多情况下重载，触发文档加载完成的loaded-protyle事件，但是无法去区分，例如：打开文档，浮窗显示，聚焦退出，或者是其他情型

### Describe the optimal solution

请求改进api，区分情形
当下是需要在文档打开时更新指定块，但是会被浮窗和聚焦退出所触发的loaded-protyle所干扰，导致异常，无法区分

### Describe the candidate solution

无

### Other information

无

**Comment by frostime** [comment]
比如在 detail 里面可以添加一个 source 字段，用来标识触发源对象。

最低限度的，起码要区分打开一个文档和打开别的什么浮窗、聚焦之类的区别。

**Comment by Vanessa219** [comment]
浮窗使用 protyle.model 是否存在进行判断，聚焦使用 protyle.block.showAll  进行判断。

打开的时候可能是聚焦，也可能是全文档显示。
