### ISSUE TITLE
protyle 接口在无法上下滚动加载

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

插件的api protyle在加载内容后无法上下滚动加载，使用的代码如下：
```typeScript
            new Protyle(plugin.app,(mainCard.value as HTMLElement),{
                action:["cb-get-append","cb-get-before"],
                blockId:"20230922225710-nc6tskx"
            })
```
滑动到protyle的最下方无法动态加载：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/eb646872-aed0-47e6-82f6-57ec6ecec9e9)

打开的文档实际上具有2000行：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/6fb34612-f661-4077-828e-459d297efc85)

### Expected result

protyle在加载内容后可以上下滚动动态加载内容

### Version environment

```markdown
- Version: 2.10.11
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by Vanessa219** [comment]
上下滚动是根据滚动事件自动加载的，不需要传入 ["cb-get-append","cb-get-before"]

**Comment by 88250** [comment]
没有问题的话我先关闭了哦，谢谢。
