### ISSUE TITLE
嵌套引用锚文本模板渲染问题

### ISSUE THREAD

**Issue by YeChengMinMin** [siyuan-note/siyuan#946]
### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，麻烦截图或者录屏描述，谢谢。

**Comment by YeChengMinMin** [comment]
![image](https://user-images.githubusercontent.com/59163865/103714382-80208d00-4ff9-11eb-8c5d-7da3ee228bc4.png)
![image](https://user-images.githubusercontent.com/59163865/103714387-8282e700-4ff9-11eb-92fe-367d22137f7d.png)

**Comment by 88250** [comment]
![image](https://user-images.githubusercontent.com/873584/103714598-ec02f580-4ff9-11eb-9bcf-f876eae787c0.png)

这个块是什么样子的呢？

**Comment by YeChengMinMin** [comment]
![image](https://user-images.githubusercontent.com/59163865/103714870-105ed200-4ffa-11eb-9ecc-e121b5612c0e.png)
可以看的见吗，是这个样子

**Comment by 88250** [comment]
`配置元件`也是一个块引用对吗？

**Comment by YeChengMinMin** [comment]
先是引用了`HTTP信息头管理器`这个块，`HTTP信息头管理器`这个块里面有一个`线程组-配置元件`的块，但`线程组-配置元件`的块无法显示

**Comment by YeChengMinMin** [comment]
`HTTP信息头管理器`是被嵌入的，如果直接打开`HTTP信息头管理器`是可以看见‘线程组-配置元件’的，但嵌入的页面就看不见‘线程组-配置元件’了

**Comment by 88250** [comment]
好的，已经明白问题了，谢谢反馈，稍后修复。

**Comment by YeChengMinMin** [comment]
好的，谢谢
