### ISSUE TITLE
protyle 的 title参数无效

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

打开protyle参数后，在protyle中显示出了title的位置，但没有值
```ts
            new Protyle(plugin.app,(mainCard.value as HTMLElement),{
                action:["cb-get-append","cb-get-before"],
                blockId:props.currentCard.blockID,
                render: {
                    title: true,
                    gutter: true,
                    scroll: false,
                    breadcrumb: true,
                    breadcrumbDocName: true,
                }
            })
```
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/33d2b947-b616-4e7e-8149-139d41713f45)
以下是正常情况：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/372cf15b-093e-4e69-a711-644fd245009f)

### Expected result

正常显示title

### Version environment

```markdown
- Version: 2.10.11
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by Vanessa219** [comment]
action 移除  ["cb-get-append","cb-get-before"]
