### ISSUE TITLE
Bold text selected by mouse cannot be copied

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When I selected the bold text and clicked ctrl + C, I found that the text was not copied successfully

### Expected result

Normal replication

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/60436214/5674d422-cf49-4ef9-8951-87021bc42371)

### Version environment

```markdown
- Version: 2.10.11
- Operating System: Win11
- Browser (if used):
```

### Log file

none

**Comment by 88250** [comment]
你好，我这里无法重现问题，请看录屏操作：

[视频.webm](https://github.com/siyuan-note/siyuan/assets/873584/f14a4d0d-7d32-4236-a878-a2a428264153)

**Comment by Achuan-2** [comment]
我这边现在又没问题了，先关闭issue了
