### ISSUE TITLE
键盘操作改进

### ISSUE THREAD

**Issue by TinkMingKing** [siyuan-note/siyuan#9465]
### In what scenarios do you need this feature?

1. 现在shitf拖拽块标生成嵌入块的功能取消了吗？还是bug导致失效？我看帮助里的快捷键篇还写着
2. 常常需要在最外层块下方或上方插入行，但是没有对应快捷键，只能用鼠标去操作块标，比较高频的操作，不支持快捷键有点膈应，比如层级比较深的列表，只能多次回车才能出去，或者使用鼠标；又或者其他层级复杂的块中
3. `ALT+[`操作引用块只能产生静态锚文本

### Describe the optimal solution

1. 请回复解惑或者解决问题
2. 请求添加快捷键，个人认为'ALT+/'比较合适，弹出最外层块的块标菜单，这时候支持使用CTRL+SHIFT+A/B插入块
3. 支持`ALT+[`操作后，'ENTER'生成静态锚文本，'CTRL+ENTER'生成动态锚文本

**Comment by 88250** [comment]
1. 我这里测试正常

**Comment by TinkMingKing** [comment]
> 1. 我这里测试正常

我这里测试结果是，如果按住shift就拖不动，如果先拖动再按shift就能生成嵌入块，其他两个按键ctrl和alt都是按住再拖没问题

**Comment by 88250** [comment]
哦哦，确实是这样，下个版本改进 Shfit 键的问题 https://github.com/siyuan-note/siyuan/issues/9479

> 请求添加快捷键，个人认为'ALT+/'比较合适，弹出最外层块的块标菜单，这时候支持使用CTRL+SHIFT+A/B插入块

这个暂时不考虑了，还是扩选后按快捷键吧，考虑的点是每一层都一视同仁。
