### ISSUE TITLE
文档树星标置顶

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#9466]
### In what scenarios do you need this feature?

见：[https://ld246.com/article/1697878476103](https://ld246.com/article/1697878476103)

### Describe the optimal solution

见上面链接

**Comment by 88250** [comment]
书签拖拽加入 https://github.com/siyuan-note/siyuan/issues/9340

**Comment by Aiviokoo** [comment]
D大，置顶显示在这里哇（全局在文档树顶，局部在文档下或笔记本下的顶部），
![578b9db02422a65ce341697125af5387](https://github.com/siyuan-note/siyuan/assets/87182333/b3297705-f30f-41bc-897c-066c1fc8d7c3)
不是书签那里哟。

**Comment by 88250** [comment]
嗯，这个和书签没有任何关系的。

**Comment by MrIntellectX** [comment]
Please add a pinned section at the top of the doc tree, thanks.

**Comment by TCOTC** [comment]
有这个功能的话确实很方便，最近常用的文档置顶了就不需要翻来翻去了，也不用一直保留页签

**Comment by 5kyfkr** [comment]
前来支持，置顶应该可以再弄多个转换为书签的功能，使用频次应该是这样的：标签页钉住(非常常用)->文档树置顶(近期常用)->书签(长期常用)

**Comment by TCOTC** [comment]
- https://ld246.com/article/1723516556402

**Comment by 88250** [comment]
不考虑实现了，看看是否有相关插件吧。

**Comment by wish5115** [comment]
https://ld246.com/article/1741359650489 这个实现了

**Comment by 88250** [comment]
将在 v3.8.4 中实现该功能 https://github.com/siyuan-note/siyuan/issues/19401
