### ISSUE TITLE
Improve PDF export code block line number display

### ISSUE THREAD

**Issue by dream-tentacle** [siyuan-note/siyuan#9471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When extracting a PDF file, if there is a code block which is cut into two pages, the line numbers are a mess.
![image](https://github.com/siyuan-note/siyuan/assets/127286614/6b460661-4eeb-4728-9fc1-5b5026343332)

### Expected result

make sure the line numbers are correct

### Version environment

```markdown
- Version: 2.10.11
- Operating System: Windows 11
```

### Log file

No need I think

**Comment by 88250** [comment]
If convenient, please provide code blocks or export .sy.zip for uploading for testing, thank you.

**Comment by dream-tentacle** [comment]
[第十一周.sy.zip](https://github.com/siyuan-note/siyuan/files/13062170/sy.zip)


> If convenient, please provide code blocks or export .sy.zip for uploading for testing, thank you.
> 
> Ref: https://ld246.com/article/1697600947047

**Comment by Vanessa219** [comment]
又优化了下，还麻烦下个版本看看。如果行数过多的话 ，Chrome 导出在分页时也同样会有问题，估计只能移除行号在导出了。
