### ISSUE TITLE
是否能在折叠时也能显示评论(comments)的存在与否以及个数呢？

### ISSUE THREAD

**Issue by ZheyuanHuang** [siyuan-note/siyuan#9472]
### In what scenarios do you need this feature?

在Notion中，就算被折叠（如Toggle list），折叠栏目右侧仍然会显示comments的个数（见附图），这便于在对文档进行修改或者复习时快速而方便地定位所需要修改或者着重复习的地方。
![image](https://github.com/siyuan-note/siyuan/assets/113876607/75892f69-13fa-42c7-a379-b7fab5f1044d)

### Describe the optimal solution

可以采用类似Notion一样的方案，在折叠后于折叠栏目的右侧显示所折叠内容是否有未完成的comment。

**Comment by 88250** [comment]
思源原生是没有 comment 功能的，暂时不考虑了。也许可以通过其他方式实现，比如将 comment 分散在 daily note 中，通过反链计数来实现，这也是 dn 的惯用法。
