### ISSUE TITLE
在快捷键中搜索ALT+M时会隐藏视窗

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

的确ALT+M默认是隐藏视窗，但是用户要去修改这个快捷键，在设置-快捷键中输入ALT+M搜索时是不是最好暂时不要生效这组快捷键的功能？

### Expected result

希望在快捷键-搜索框中输入按键时可以不生效该组快捷键的功能

### Version environment

```markdown
- Version: 最新dev
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by Vanessa219** [comment]
这个检测到的时候已经隐藏了，来不及处理。
