### ISSUE TITLE
Persist spaced repetition interface fullscreen setting

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#9477]
配置唤出闪卡时，直接全屏。

### In what scenarios do you need this feature?

打开闪卡时，初始显示的窗口太小了。希望可以配置alt+0后直接全屏。

### Describe the optimal solution

加入个全屏打开闪卡的配置

**Comment by 88250** [comment]
@Vanessa219 看下能不能本地存储中记录一下上次的设置。
