### ISSUE TITLE
After ALT+[, `CTRL+ENTER` and `CTRL+Click` generates a dynamic ref

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9480]
https://github.com/siyuan-note/siyuan/issues/9465 第三点

**Comment by Achuan-2** [comment]
这个改进只是针对添加原有引用，能否Alt+【创建文档时，也是 Ctrl+Enter and Ctrl+Click 创建动态锚文本呢

**Comment by Vanessa219** [comment]
引用创建文档使用的是笔记本配置中规则，就不添加子文档了。创建新文档问题下个版本继续修改。

**Comment by Achuan-2** [comment]
> 引用创建文档使用的是笔记本配置中规则，就不添加子文档了。创建新文档问题下个版本继续修改。

嗯嗯，我说的就是Alt+【引用创建文档也能变为动态锚文本

**Comment by Vanessa219** [comment]
👌 dev 分支改进了
