### ISSUE TITLE
Add  open icon

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9481]
<img width="231" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/3145b873-26c4-4caf-80a7-d20bcd241fca">

**Comment by Vanessa219** [comment]
88f9318e0b3fb40f32f76a3392050f9b761abb06

**Comment by 88250** [comment]
@tcmtom 这个放在外面好像不大统一，等我们看看换个其他的，感谢反馈。
