### ISSUE TITLE
数据历史展示优化

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9482]
### In what scenarios do you need this feature?

2023-10-23 14:11:29 那个应该是直接从云端下载的 2023-10-23 12:31:44
这个地方能否优化下，如果完全用的云端的快照，就显示 pull 的哪个快照，如果确实是 merge的也显示下是与哪个云端的快照 merge的，要不本地快照历史一下子就跳过了好几个云端快照，心里多少有些慌慌。
虽然可以用比较进行查看，但是我每次可能更新很多文件内容，没有那么方便，感觉添加更多的快照关系，会更安心些。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/f2e1b83b-9abb-4008-9fbe-584a680c0fb5)

### Describe the optimal solution

展示 merge的 origin，已经展示 pull 的 origin

**Comment by 88250** [comment]
这个对应不起来，建议还是用时间+设备判断吧，谢谢。

**Comment by woniuxia** [comment]
时间+设备虽然可以判断，但是不够直观和友好。
还是希望可以比较直观看到当前的merge 是从哪merge 的。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/0cf9a13b-b0d8-4a6d-8ed6-39daf50aed41)

**Comment by woniuxia** [comment]
当前本地与云端是分两个页面进行展示，想要比对也没有那么方便

**Comment by 88250** [comment]
这块一时半会应该是完善不了了，我们先搞其他更重要的任务吧，感谢理解。

**Comment by woniuxia** [comment]
明白的，那有可能 open 下吗？

**Comment by 88250** [comment]
等后面考虑吧，有相同需求会关联到这里的。
