### ISSUE TITLE
折叠标题后关闭再打开文档时，下方显示被折叠的超级块

### ISSUE THREAD

**Issue by royc01** [siyuan-note/siyuan#9483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![1](https://github.com/siyuan-note/siyuan/assets/38906705/431493a7-8366-4bbe-9de8-322c76c79d5a)

### Expected result

1

### Version environment

```markdown
- Version: 2.10.11
- Operating System: win10
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
请看下我的重现操作是否正确：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/1ef095b5-39a5-465f-95dd-1be52ed6b517)

**Comment by royc01** [comment]
你操作是正确的，但虽然下方不显示，用鼠标框选的时候超级块也是在的。

**Comment by royc01** [comment]
![22](https://github.com/siyuan-note/siyuan/assets/38906705/a06a48db-171a-4b7f-86a5-a50b8a675825)

**Comment by 88250** [comment]
确实是，稍后排查。

**Comment by 88250** [comment]
这个问题有点复杂，我们后面在 https://github.com/siyuan-note/siyuan/issues/9488 中跟进讨论吧，感谢反馈。
