### ISSUE TITLE
请问一下，思源的工作空间有独特的id吗？如果有的话，该如何在前端获取呢

### ISSUE THREAD

**Issue by suka233** [siyuan-note/siyuan#9484]
### In what scenarios do you need this feature?

目前思源生成的超链接，如帮助文档的超链接：[siyuan://blocks/20200812220555-lj3enxa](siyuan://blocks/20200812220555-lj3enxa)，并没有携带工作空间的id，这就导致了如下情况：
如果当前打开了多个思源客户端（通常是打开多个工作空间的需求），那么点击这个超链接的时候，所有的思源客户端都会响应。

这会导致一些支持解析siyuan超链接的插件异常
比如：
如果这些工作空间都安装了kmind插件，那么点击这个超链接:
[siyuan://plugins/kmind-plugin?data=%7B%22name%22:%22233%22%7D](siyuan://plugins/kmind-plugin?data=%7B%22name%22:%22233%22%7D)

会出现如下效果：
A工作空间如果已经存在了名为233的kmind导图的话，就会直接打开这张导图
B工作空间如果不存在名为233的kmind导图的话，就会直接创建一张名为233的导图
C工作空间如果同样存在名为233的kmind导图的话（但是内容跟A工作空间不一致），也会被直接打开

如果有工作空间的id的话，那么插件作者拦截非预期的超链接就简单多啦

### Describe the optimal solution

我在全局对象找到了这个id，请问一下这个是什么id？可以安全的拿来标识不同的工作空间吗？
![image](https://github.com/siyuan-note/siyuan/assets/43712875/fe38457d-6a78-4944-a387-bbf42a51ee3e)

**Comment by Vanessa219** [comment]
可以使用 `window.siyuan.config.system.workspaceDir` 或者 `/api/system/getConf` API

**Comment by suka233** [comment]
> 可以使用 `window.siyuan.config.system.workspaceDir` 或者 `/api/system/getConf` API

window.siyuan.config.system.workspaceDir不可以，因为如果多个PC端同步使用的话，不同端的工作空间目录可能是变化的，无法作为唯一值来标识。
然后我自测了一下，window.siyuan.config.system.id也不行，不同的PC端，这个id也是会变化的。
然后我上面标注的siyuan.storage.local-docinfo 在不同的PC端，这个值也是会变化的

所以有其它办法获取当前工作空间的唯一标识值吗？

**Comment by 88250** [comment]
工作空间没有 ID，因为工作空间本身的配置是不同步的，只在本地存在，所以路径是唯一值了。上面说的打开超链接的场景是多工作空间同时运行才存在，我不太理解为啥该情况下使用工作空间路径不能判断。
