### ISSUE TITLE
Hierarchical tags - Last tag non-exclusive filtering

### ISSUE THREAD

**Issue by sdnnvs** [siyuan-note/siyuan#9489]
### In what scenarios do you need this feature?

As it currently stands: two hierarchical tags #tag1#tag1.1/tag1.2# and #tag2#tag1.1/tag2.1# were created. 
Note that the subtag #tag1.1# is common to both hierarchical tags. 
In the filtering on the Alt+4 panel, when we click on the #tag1.1# tag, the wrong filtering returns to a supposed independent tag #tag1.1#. 
As would be expected in a hierarchical tag system, if we filter by the intermediate tag, as a result, it has to show all its subtags, in this case, #tag1.2# and #tag2.1#, as in the example.

#tag1#tag1.1/tag1.2#
#tag2#tag1.1/tag2.1#

In Alt+4, click in #tag1.1#

Result:

nothing

### Describe the optimal solution

As would be expected in a hierarchical tag system, if we filter by the intermediate tag, as a result, it has to show all its subtags, in this case, #tag1.2# and #tag2.1#, as in the example.

#tag1#tag1.1/tag1.2#
#tag2#tag1.1/tag2.1#

In Alt+4, click in #tag1.1#

Result:

#tag1.1/tag1.2#
#tag1.1/tag2.1#

### Describe the candidate solution

The possibility of filtering the intermediate hierarchical tag and not just the final tag in the hierarchy.

### Other information

In fact, the function of a hierarchical tag is the possibility of filtering subtags into groups. Simply allowing the creation of hierarchical tags #primary tag/secondary tag/final tag# without the possibility of filtering all final tags that share the same secondary tag is limiting its purpose.

**Comment by 88250** [comment]
Tag search actually performs a search for the tag content text, so if it is an intermediate tag, please remove the #:

![image](https://github.com/siyuan-note/siyuan/assets/873584/237b0502-7b60-4264-b9c1-18c635823737)
