### ISSUE TITLE
Multi-tag filtering - Progressive tag filtering

### ISSUE THREAD

**Issue by sdnnvs** [siyuan-note/siyuan#9490]
### In what scenarios do you need this feature?

Currently, tag filtering is exclusively unique, meaning it is only possible to filter based on a single tag.
We have the tags #rabbit#, #male#, #female#, #white# and #black#, for example.
It is not possible to simultaneously filter #rabbit# + #male# + #white#, or #rabbit# + #female# + #black#, for example. You would have to choose between the tags, which would bring many unwanted results.

### Describe the optimal solution

Temos as tags:

#rabbit#
#male#
#female#
#white#
#black#

Em Alt+4, Control+Left Click in #rabbit#, #female# and #black# RESULT:

Blocks with all tags #rabbit#, #female# and #black#

### Describe the candidate solution

An example of an application that uses this feature is Cintanotes, which supports hierarchical tags and multiple filtering.

### Other information

Multiple tag filtering is a feature that optimizes the location of tagged blocks more precisely.

**Comment by 88250** [comment]
The current tag panel cannot support it. Please consider using SQL search. Thanks for the feedback.
