### ISSUE TITLE
Maintain relationships between database blocks and database storage

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9496]
https://github.com/siyuan-note/siyuan/issues/9285#issuecomment-1776312454

**Comment by 88250** [comment]
不考虑深克隆了：https://github.com/siyuan-note/siyuan/issues/9285#issuecomment-1784146180

考虑改为使用单独的 JSON 文件维护数据库块（Node）和数据库存储（JSON）之间的关联，在数据库块增加、复制和删除时变更关联关系。

**Comment by zxhd863943427** [comment]
> 不考虑深克隆了：[#9285 (comment)](https://github.com/siyuan-note/siyuan/issues/9285#issuecomment-1784146180)
> 
> 考虑改为使用单独的 JSON 文件维护数据库块（Node）和数据库存储（JSON）之间的关联，在数据库块增加、复制和删除时变更关联关系。

没太理解，什么意思？

**Comment by 88250** [comment]
就是单独用个结构（不一定是 JSON）来维护 av-blocks 的关联关系，这样后面就可以方便通过 av id 查找到 av blocks 了。也能在渲染 av block 的时候判断是不是“镜像块”（通过 av-blocks[avID] 是否存在多个 blocks，如果存在说明有多个 av blocks 引用到了同一个 av）。
