### ISSUE TITLE
Add `data-doc-type` attribute when exporting image and PDF

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9497]
@Vanessa219 能不能在导出图片与导出 PDF 的预览页面中的 `.protyle-wysiwyg` 元素中添加文档块的块属性, 否则一些依托于文档块块属性的样式将会失效

_Originally posted by @Zuoqiu-Yingyi in https://github.com/siyuan-note/siyuan/issues/9376#issuecomment-1774854053_

**Comment by Zuoqiu-Yingyi** [comment]
这里貌似理解错了, `文档块的块属性` 是指 `name`, `alias`, `memos` 与 `custom-*` 等块属性

**Comment by Vanessa219** [comment]
哦，我再添加一下。
