### ISSUE TITLE
关系图定位偶有失灵，似乎是不确定的某个文件

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#95]
![test](https://user-images.githubusercontent.com/29135984/94330656-160b4b80-fff9-11ea-83e6-d91d1c248c12.gif)
反复重启可以消除某个文件不能定位的问题

**Comment by 88250** [comment]
这个问题在 v0.2.3 修复。

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/89
