### ISSUE TITLE
PDF files larger than 128MB are not included in asset file content searching

### ISSUE THREAD

**Issue by GuangDai** [siyuan-note/siyuan#9500]
当增加较大PDF文件时候，内存量占用异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

复制一个大PDF文件到内容的时候，就这样了，几次尝试都是相同的结果

![image](https://github.com/siyuan-note/siyuan/assets/59678726/fafed129-a5c7-4ca9-941f-ebbc627ce194)
![image](https://github.com/siyuan-note/siyuan/assets/59678726/adb37c3f-1c54-4909-85fe-8a2131300c61)

### Expected result

正常的占用

### Version environment

```markdown
- Version: 2.10.11
- Operating System: ArchLinux
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13121170/siyuan.log)

**Comment by 88250** [comment]
应该是因为建立 PDF 内容索引导致的，麻烦发一下这个 PDF 文件给我们测试看看 845765@qq.com

**Comment by GuangDai** [comment]
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Oct 25, 2023 08:48 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [siyuan-note/siyuan] 当增加较大PDF文件时候，内存量占用异常 (Issue #9500)

&nbsp;



 
应该是因为建立 PDF 内容索引导致的，麻烦发一下这个 PDF 文件给我们测试看看 ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 



从腾讯企业邮箱发来的超大附件

880.pdf (868.94M, 2023年11月24日 08:53 到期)进入下载页面：https://exmail.qq.com/cgi-bin/ftnExs_download?k=5b393536938c83fa6c21a51b43660401490c5655510406050714505507051e07000b021b5c5502004b00010707515105000a530f066634335e0105181402553358&amp;t=exs_ftn_download&amp;code=f956df33&amp;s=email&amp;fid=72/5cc5b56a-eccc-4f27-8313-941c7b6f3f9b

**Comment by 88250** [comment]
感谢提供测试数据，下个版本我们会限制资源文件索引 PDF 大小为 64MB，超过这个大小的 PDF 不支持内容搜索。

**Comment by GuangDai** [comment]
64MB可能有点小，我看了一下我的asset文件夹下，基本上100MB以内，有两个300MB的，以上都没出现过问题，只有这个接近900MB的出现了问题，感觉可以限制到128作业

**Comment by 88250** [comment]
好的，那就限制在 128MB 看看，后面可能可以支持设置调整，看后续需求吧。

**Comment by woniuxia** [comment]
> 好的，那就限制在 128MB 看看，后面可能可以支持设置调整，看后续需求吧。

D大，感觉还是直接加上设置吧。要不其他用户遇到问题，还得等下个版本修复，观感不太好。

**Comment by 88250** [comment]
等需求吧，不是扫描版的 PDF 很少有这么大的。

**Comment by zxhd863943427** [comment]
存在一种可能：扫描版加文字夹层。
这实际上才是最常见的文字版。

**Comment by UltramarineSky** [comment]
> 等需求吧，不是扫描版的 PDF 很少有这么大的。

国内没有几个提供原版PDF的出版社，大部分都是扫描版加ocr文字夹层，直接限制128可能会有其他使用这个功能的人出现问题，还是加设置比较好

**Comment by 88250** [comment]
这样吧，咱们加个环境变量 `SIYUAN_PDF_ASSET_CONTENT_INDEX_MAX_SIZE=256000000`（单位字节）进行设置。
