### ISSUE TITLE
关于同步错误提示的优化建议

### ISSUE THREAD

**Issue by newproplus** [siyuan-note/siyuan#9501]
### In what scenarios do you need this feature?

当同步设置有问题的时候， 比如 Addressing 是 **Virtual-hosted-style** 而服务端只支持 **Path-style** 的时候，会导致错误

```
E 2023/10/25 01:29:36 sync_lock.go:106: remove unmarshalled lock sync failed: RequestError: send request failed
caused by: Delete "http://sy.abc.com/repo/lock-sync": dial tcp: lookup sy.abc.com on 192.168.1.1:123: no such host
E 2023/10/25 01:29:36 repository.go:1056: sync data repo upload failed: RequestError: send request failed
```

但这些错误只在日志文件中记录，用户看不到明确的错误原因。

### Describe the optimal solution

在 **siyuan/kernel/model/repository.go**  执行 `logging.LogErrorf("sync data repo upload failed: %s", err)` 的前后添加一个判断：
1. 错误中是否由于 host 不通，或者报错文本包含 “no such host” 。
2. 如果是的话，尝试切换 Addressing 测试一下，是否是 Addressing 配置的问题。
3. 如果是 Addressing 配置的问题，给出弹窗提示，让用户明白是配置的问题，避免用户抱怨。

### Describe the candidate solution

在状态栏给出提示。

_No response_

**Comment by 88250** [comment]
你好，分析了下 no such host 判断可能会误判，我用 Cloudflare R2 测试，Addressing 切换两种方式都可以成功同步，所以使用这个判断的话可能会在真的 no such host 的时候误导用户。

no such host 在 sync.go 中有相关判断，错误文案是 "网络超时，请稍后再试"，主要是考虑到可能是网络域名解析的问题。

以稳妥为主，暂时不进行相关代码变更了，感谢反馈。
