### ISSUE TITLE
开启仓库的 discussions 功能

### ISSUE THREAD

**Issue by yb6b** [siyuan-note/siyuan#9506]
### In what scenarios do you need this feature?

链滴论坛的搜索功能不好用，很难找到许多优质的资源。比如两位作者对产品功能的取舍、技术方面的设计等等。

### Describe the optimal solution

本仓库可以开启 [GitHub Discussions](https://docs.github.com/zh/discussions/quickstart) 功能。它就是个偏向技术的论坛。

那些不会进入开发TODO的内容，可以在discussions里聊。

**Comment by 88250** [comment]
感谢提议，但是暂时不考虑了，没有时间管理……
