### ISSUE TITLE
Collect users' behavior automatically.

### ISSUE THREAD

**Issue by yb6b** [siyuan-note/siyuan#9507]
### In what scenarios do you need this feature?

几乎每个成熟的应用，都会收集用户行为，便于产品设计、项目规划、E2E测试、灰度测试、营销推广……

思源目前使用谷歌分析，它是为web设计的，不能精细地收集每个操作。因此只能自己做一套。

### Describe the optimal solution

前端相对容易些：直接监听body元素的click事件等。部分核心功能需要具体地代码埋点，收集更完整的信息。

但服务器麻烦些，如何减小宽带使用、避免作弊、数据整理分析等等。

这是个复杂的工程，需要慢慢做。

### Other information

收集用户行为数据，涉嫌隐私问题。所以宣传时明确“不收集用户的文件内容。代码开源，欢迎监督。”

思源功能已经极其丰富，不再小而美了。用户复杂、功能繁多，关注点太多，如果没有数据，那就很难区分主次，可能浪费开发精力，或许满足了小部分用户却反感了大多数。

思源笔记未来的方向，需要参考一张地图，从长计议吧。谢谢阅读。

**Comment by 88250** [comment]
感谢提议，不过这个就不采集了，目前 Google 分析也只采集了在线情况，不会采集具体数据。
