### ISSUE TITLE
Support modifying database column types

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9513]
https://ld246.com/article/1698291998384

**Comment by mozhux** [comment]
试用了一下，建议块类型能在第一层，不要点进去编辑才能看到呢，本身是先改了类型再编辑嘛，就和友商的一样就行，多一步感觉没啥必要。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/9a49e8c2-0b86-41ac-af04-3351f9f7a5c1)
