### ISSUE TITLE
浏览器的siyuan插件发送网页内容会导致大量html内容被识别为标签，导致标签功能基本无法使用

### ISSUE THREAD

**Issue by ccxuy** [siyuan-note/siyuan#9514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

浏览器的siyuan插件发送网页内容会导致大量html内容识别为标签，导致标签功能基本无法使用，希望能增加标签特殊字符的过滤功能的选项，siyuan的文章（可能）更类似于markdown不直接依赖于html？

并且标签中有删除的功能，但是点击后siyuan会重启，但是标签并未实际删除，这里删除的含义只是删除标签数据对吧？

### Expected result

导入文章不会生成标签

### Version environment

```markdown
- Version: 
- Operating System: windows
- Browser (if used): chrome
```

### Log file

NA

**Comment by 88250** [comment]
这个估计没法改了，因为如果不按 Markdown 语法来的话会有语法冲突的问题。删除标签的含义就是把 `#tag#` 这个元素删除。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by ccxuy** [comment]
也不是要改markdown的语法机制什么的，单纯是看看html引入的是否能不识别为tag，或者关闭某个文章的tag索引，不然一用网页插件就会导致tag功能无法使用

**Comment by 88250** [comment]
@ccxuy 请发一下具体的网址实例我们分析下。

**Comment by ccxuy** [comment]
应该只要收藏的网页带有#的这种tag语法就会出现，比如
http://www.wowotech.net/process_management/Process-Creation-1.html

**Comment by ccxuy** [comment]
并且删除标签会实际删除原文，并且编辑器会重启

**Comment by 88250** [comment]
正常情况下，代码块应该是包裹在 pre code 标签中的，但是这个网页用的是 blockquote p：

![image](https://github.com/siyuan-note/siyuan/assets/873584/7ceab4f0-d21c-46f6-8386-61c3a2a30019)

所以会识别为文本，进而转换为标签。这个剪藏插件没有办法兼容的，否则正常的 blockquote q 就会被识别为代码块。

**Comment by ccxuy** [comment]
没法兼容也不要紧, 允许排除某些文章的tag, 或者剪藏不导入tag都可以, 不然之前整理的tag会被淹没在错误的tag里
