### ISSUE TITLE
Data should also be saved when the formula and chart edit boxes are not closed normally

### ISSUE THREAD

**Issue by GaN601** [siyuan-note/siyuan#9515]
Mermaid创建sequenceDiagram的流程图经常出现保存失败

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用Mermaid创建sequenceDiagram的流程图经常出现保存失败的情况, 以为保存了, 然后关闭标签后又打开发现数据没了

### Expected result

正确保存数据

### Version environment

```markdown
- Version: 2.10.12
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13174503/siyuan.log)

**Comment by 88250** [comment]
从日志中暂未发现相关问题，如果有确定重现步骤的话麻烦录屏演示，谢谢。

**Comment by GaN601** [comment]
https://github.com/siyuan-note/siyuan/assets/80253667/c76883c7-54b1-4fd0-a668-9d7d746f545f



> 从日志中暂未发现相关问题，如果有确定重现步骤的话麻烦录屏演示，谢谢。

这样可以吗

**Comment by 88250** [comment]
我明白了，目前那个 Mermaid 编辑框如果不点 <kbd>X</kbd> 关闭的话是不会保存的，这个我们看下能否改进，感谢反馈。

@Vanessa219

**Comment by GaN601** [comment]
确定了, 是编辑框没有关闭, 我直接关闭当前文档数据就会丢失,可以稳定复现.
希望能修复一下, 如果我编辑好了, 不关闭编辑框切换到别的文档, 这时候我关闭程序或者关闭刚刚编辑sequenceDiagram的文档都会导致数据丢失
