### ISSUE TITLE
Improve file tree dragging to top and bottom scroll interaction

### ISSUE THREAD

**Issue by lisontowind** [siyuan-note/siyuan#9516]
### In what scenarios do you need this feature?

文档树实在太长了，移动的时候想拖动总是发现文档树不能滚动

### Describe the optimal solution

希望能够在拖动的时候文档树可以滚动，这样操作起来可以方便一点。
同时，页面里面希望也可以这样，文档一长就不太好拖动了。

**Comment by 88250** [comment]
移到底部或者顶部会自动滚动的。

**Comment by lisontowind** [comment]
> 移到底部或者顶部会自动滚动的。

偶偶，好的，谢谢D大！（一直没有发现，但刚刚用发现一个bug，拖动如果不小心碰到表格块的范围的话就会停下来，需要把鼠标挪到边上去）。但还是希望能通过鼠标滚动实现，手感上好很多，而且可以控制滚动的速度，拖动也更加自由一点。

**Comment by 88250** [comment]
嗯，等后面看看能不能做 @Vanessa219

**Comment by Vanessa219** [comment]
我先参照 https://github.com/siyuan-note/siyuan/issues/9813 进行改进一下。滚轮滚动 @88250  看一下，以前是可以进行滚动的。
