### ISSUE TITLE
新建过滤问题

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

新建一个过滤，没有填写具体过滤内容，就取消了，但是过滤项中出现了
![image](https://github.com/siyuan-note/siyuan/assets/16383685/cad8096c-16eb-45f8-b213-ce5db8f56da5)

![image](https://github.com/siyuan-note/siyuan/assets/16383685/a24a85fe-038f-4375-8bbe-94596bb6f3b7)

### Expected result

过滤项中应该不出现，因为是想取消掉该过滤的

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

null

**Comment by 88250** [comment]
请使用删除，因为过滤项的值是可以为空的，空值是有存在的意义的。
