### ISSUE TITLE
Auto-scroll screen to the top when editing database cells on the mobile

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9520]
https://ld246.com/article/1698329060263

**Comment by zxkmm** [comment]
您好，抱歉，原帖反应的问题在2.10.13 ios上还是存在。表现是一样的。

**Comment by 88250** [comment]
嗯，目前如果表格下方没有太多内容，依然无法滚动到位，如果下方内容较多把高度撑够的话应该是可以滚动的。

这个问题后续在 https://github.com/siyuan-note/siyuan/issues/9565 中跟进，谢谢。
