### ISSUE TITLE
Doc title picture supports searching in assets

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#9524]
题头图支持资源文件搜索

### In what scenarios do you need this feature?

库内的资产一直不能很方便的添加到题头图与图标中。

#### 使用例子

我需要建立一个人物（或是其他任何）的笔记，将人物作为图标，人物相关的照片作为题头图。

### Describe the optimal solution

直接选择并使用库内的文件，这是anytype的选择界面，可以进行预览和搜索。

![image](https://github.com/siyuan-note/siyuan/assets/63145205/315e1346-4fe0-4dea-9f75-57efde13b5ee)

### Describe the candidate solution

选择并使用库内的文件，自动将图标添加入emoji（这可能导致一些图片出现两份。）

#### 目前的解决方案需要

1. 将图标拖拽入emoji文件夹（作为图标）
2. 上传人物相关的照片，或是获取文件的路径然后填入链接中  
![image](https://github.com/siyuan-note/siyuan/assets/63145205/5a518626-3bba-425e-a4ac-fdd5fa3165db)

#### 造成的问题
1. 不够方便快捷
2. 一个图标可能只会用于一篇笔记，如果此类笔记创建过多，会导致自定义emoji下出现很多一次性的图标。

**Comment by 88250** [comment]
感谢反馈，但是图标就不考虑上传了，原因见 https://github.com/siyuan-note/siyuan/issues/5897

题头图支持资源文件搜索我们考虑下，谢谢。
