### ISSUE TITLE
This includes Electron? You need to make this information known.

### ISSUE THREAD

**Issue by kendofriendo** [siyuan-note/siyuan#9525]
### In what scenarios do you need this feature?

This includes Electron? You need to make this information known.

### Describe the optimal solution

Include the "electron" tag in your about section and preferably in the description.

**Comment by 88250** [comment]
Hello, SiYuan desktop is developed based on Electron. Please refer to this section of REAMD for all dependencies:

![image](https://github.com/siyuan-note/siyuan/assets/873584/d81dda8e-152f-4be5-84f5-90f5914fb3bb)
