### ISSUE TITLE
Support `Jump to the next block in the parent level` on focus status

### ISSUE THREAD

**Issue by oijqws** [siyuan-note/siyuan#9527]
打开节点不能”跳到上一层的下一个块“

### In what scenarios do you need this feature?

在这个时候是不能从28 跳到29，如果可以跳会更加方便
![image](https://github.com/siyuan-note/siyuan/assets/38936048/3909c4c2-1e4c-4e37-981a-55a881180b98)
![image](https://github.com/siyuan-note/siyuan/assets/38936048/ddab9a34-5d54-4a04-a3a7-bc1a77ea7e3b)
如果全部打开就可以跳转
![image](https://github.com/siyuan-note/siyuan/assets/38936048/10ffd2d1-2f5a-4684-abb1-33d35ce0832b)

### Describe the optimal solution

这个按钮在这种情况没有任何用处，加上更加合理

**Comment by 88250** [comment]
关联 https://ld246.com/article/1698139921608

**Comment by oijqws** [comment]
如果实现这个功能，可以把上层当成一个个文件，可以始终专注在当前文件里。这样有一系列视频，可以用视频命作为上层的目录，看一个视频针对它做笔记。看完这个视频直接可以跳下一个视频的笔记。不知道我说的是否清楚？:-)

**Comment by 88250** [comment]
嗯，大概明白了，就是聚焦状态下实现跳转到父级下一个块。

**Comment by oijqws** [comment]
谢谢更改code，请问如果下个块如果不存在，是否可以自动新建一个空的呢？

**Comment by Vanessa219** [comment]
不建议新建，这个只是跳转功能。新建可能会和用户预期的不太一致。
