### ISSUE TITLE
腾讯云 S3 异常

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#9532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

一直使用腾讯云S3，最近几天突然报错。
![image](https://github.com/siyuan-note/siyuan/assets/56879067/d68d5d3b-ab86-479d-b4a2-ff1e570f0f38)
而在 PicGo 中使用正常，应该不是腾讯云的原因。

### Expected result

使用正常。

### Version environment

```markdown
- Version: v2.10.12
- Operating System: win11
- Browser (if used):
```

### Log file

I 2023/10/28 11:15:55 conf.go:485: exiting kernel [force=false, execInstallPkg=0]
I 2023/10/28 11:15:55 sync.go:176: sync before exit
E 2023/10/28 11:16:09 sync_lock.go:103: unmarshal lock sync failed: unexpected end of JSON input
E 2023/10/28 11:16:17 sync_lock.go:106: remove unmarshalled lock sync failed: RequestError: send request failed
caused by: Delete "http://cos.ap-chengdu.myqcloud.com/siyuan-1255477845/repo/lock-sync": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
E 2023/10/28 11:16:17 repository.go:1218: sync data repo failed: RequestError: send request failed
caused by: Delete "http://cos.ap-chengdu.myqcloud.com/siyuan-1255477845/repo/lock-sync": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
I 2023/10/28 11:16:21 conf.go:485: exiting kernel [force=true, execInstallPkg=0]
I 2023/10/28 11:16:21 database.go:1199: closed database
I 2023/10/28 11:16:21 conf.go:880: cleared workspace temp
I 2023/10/28 11:16:21 sync.go:670: sync websocket closed
I 2023/10/28 11:16:54 working.go:121: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/10/28 11:16:54 runtime.go:74: kernel is booting:
    * ver [2.10.12]
    * arch [amd64]
    * os [Microsoft Windows 11 Home China]
    * pid [9052]
    * runtime mode [prod]
    * working directory [D:\Software\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [E:\SiYuan]
I 2023/10/28 11:16:54 conf.go:392: user has enabled [Automatically upload error messages and diagnostic data]
I 2023/10/28 11:16:54 runtime.go:128: use network proxy [system]
I 2023/10/28 11:16:54 serve.go:119: kernel [pid=9052] http server [127.0.0.1:1860] is booting
I 2023/10/28 11:16:54 pandoc.go:132: built-in pandoc [ver=2.19.2, bin=E:\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/10/28 11:16:54 conf.go:940: pandoc initialized, set pandoc bin to [E:\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/10/28 11:16:55 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
W 2023/10/28 11:16:58 net.go:81: check url [http://cos.ap-chengdu.myqcloud.com/] is online failed: Get "http://cos.ap-chengdu.myqcloud.com/": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
W 2023/10/28 11:17:01 net.go:81: check url [http://cos.ap-chengdu.myqcloud.com/] is online failed: Get "http://cos.ap-chengdu.myqcloud.com/": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
W 2023/10/28 11:17:04 net.go:81: check url [http://cos.ap-chengdu.myqcloud.com/] is online failed: Get "http://cos.ap-chengdu.myqcloud.com/": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
W 2023/10/28 11:17:04 net.go:49: network is offline [checkURL=http://cos.ap-chengdu.myqcloud.com/]
I 2023/10/28 11:17:04 blocktree.go:463: read block tree [4.6 MB] to [E:\SiYuan\temp\blocktree], elapsed [0.01s]
I 2023/10/28 11:17:04 conf.go:723: database size [66 MB], tree/block count [221/16586]
I 2023/10/28 11:17:04 working.go:159: kernel booted
I 2023/10/28 11:17:04 box.go:79: auto stat [trees=221, blocks=16586, dataSize=249 MB, assetsSize=229 MB]
I 2023/10/28 11:17:04 disk.go:33: disk usage [total=524 GB, used=61 GB, free=463 GB]
W 2023/10/28 11:17:10 net.go:81: check url [http://cos.ap-chengdu.myqcloud.com/] is online failed: Get "http://cos.ap-chengdu.myqcloud.com/": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
W 2023/10/28 11:17:13 net.go:81: check url [http://cos.ap-chengdu.myqcloud.com/] is online failed: Get "http://cos.ap-chengdu.myqcloud.com/": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
W 2023/10/28 11:17:16 net.go:81: check url [http://cos.ap-chengdu.myqcloud.com/] is online failed: Get "http://cos.ap-chengdu.myqcloud.com/": dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.
W 2023/10/28 11:17:16 net.go:49: network is offline [checkURL=http://cos.ap-chengdu.myqcloud.com/]

**Comment by 88250** [comment]
> dial tcp 223.75.236.241:80: connectex: No connection could be made because the target machine actively refused it.

从日志中看是服务端拒绝连接了，可以试下切换本地网络后看看，如果还不行，试试发工单问下服务提供商。
