### ISSUE TITLE
PDF 页签拖拽显示有误

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

今天发布的dev版pdf页签拖动后会留下空白页签，并且后续切换页签后也会有空白，默认主题可复现

### Expected result

希望可以修复

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/125173405/b7a3c873-cffa-4d6f-979d-025718cfc3e6

### Version environment

```markdown
- Version: 2.10.13dev2
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by chenshinshi** [comment]
并且当左边仅剩pdf，右边的页签无法正常关闭

**Comment by chenshinshi** [comment]
且重启后会在挪动前后位置（即左右排）上出现多个pdf页签

**Comment by chenshinshi** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/125173405/a0466395-b20f-429a-b712-5737ae3cb62f)


https://github.com/siyuan-note/siyuan/assets/125173405/59d92319-dae2-4e4c-9563-0ffb3e48294b

都是与pdf页签有关的怪bug

**Comment by chenshinshi** [comment]
且重启后会刷新dock布局清空所有页签
![image](https://github.com/siyuan-note/siyuan/assets/125173405/f0586bfb-472c-4c9d-a212-ae004e3fa812)

**Comment by zxhd863943427** [comment]
v2.10.12 未成功复现

**Comment by Vanessa219** [comment]
多谢，修改 https://github.com/siyuan-note/siyuan/issues/9454  的时候失误了

已修复 5d2be98eab701e8ff9c7dcc374d5086d6598689d
