### ISSUE TITLE
202310281648 无法打开页签

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#9537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

无论是覆盖安装，还是全新安装，即清除.config/siyuan都会导致无法打开页签

进行测试后发现，卸载202310281648，同时删除.config/siyuan，再安装旧版本可以解决这个问题

### Expected result

无

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
开发版安装的话需要打开开发者工具，禁用网络缓存然后 Ctrl+R 强制刷新。
