### ISSUE TITLE
Add plugin `app.appId`

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9538]
### In what scenarios do you need this feature?

一些 API 会在结束的时候调用 `PushEvent` 方法，这个方法用到了 appId 这个参数用于定位广播的对象。

appId 来源于 `Constants.SIYUAN_APPID`，它无法直接被开发者访问到。

我现在的办法是，访问 websocket 的 url  `window.siyuan.ws.ws.url` 然后获取到对应的 appId。可否能直接一点，把这个作为一个字段挂载在 window 对象下？

### Describe the optimal solution

将 `Constants.SIYUAN_APPID` 挂载到 window 下。

**Comment by Vanessa219** [comment]
this.app.appId

**Comment by zxhd863943427** [comment]
能否直接挂载Constants到plugin下？
