### ISSUE TITLE
在搜索中无法调整图片大小

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在搜索面板中没有办法通过滑杠调整图片大小

### Expected result

希望修复

### Version environment

```markdown
- Version: 2.10.13dev3
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by HoollyFox** [comment]
可以双击打开文档后调整图片大小？

**Comment by chenshinshi** [comment]
> 可以双击打开文档后调整图片大小？

以前的版本是可以正常调整的吧我记得
