### ISSUE TITLE
Blacklist for search and block quote 针对搜索和块引的黑名单（排除列表）

### ISSUE THREAD

**Issue by HoollyFox** [siyuan-note/siyuan#9547]
### In what scenarios do you need this feature?

有的材料有引用需求，但没有搜索需求，有的材料有搜索需求，但是没有引用需求。

关闭笔记本的可以看做是搜索和引用黑名单，但是有的文章里面已经有引用链接了，点进去会显示无此 id 的块，其实是在关闭的笔记本里面。

### Describe the optimal solution

可以设置

1. 搜索黑名单，正则匹配的路径名称或 id
2. 引用黑名单，正则匹配的路径名称或 id

### Describe the candidate solution

在文档块加入内嵌属性：是否索引

但是不如正则匹配路径方便

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/9198
