### ISSUE TITLE
Support shortcut for the list item in search panel

### ISSUE THREAD

**Issue by HoollyFox** [siyuan-note/siyuan#9548]
### In what scenarios do you need this feature?

如下快捷键均不能在搜索面板使用，建议可以使用，比如复制嵌入块或者引用块，现在只能手动右键选择复制引用块或嵌入块。

<img width="911" alt="image" src="https://github.com/siyuan-note/siyuan/assets/23378900/923645ff-f4d0-4f83-8e30-e51b256cdd2d">

### Describe the optimal solution

Support shortcut for the block in the search panel 

在搜索面板支持针对 block 的快捷键

<img width="911" alt="image" src="https://github.com/siyuan-note/siyuan/assets/23378900/923645ff-f4d0-4f83-8e30-e51b256cdd2d">

和

`⌘+/` 打开右键菜单（另外该命令没有在设置中可以设置）

**Comment by Vanessa219** [comment]
我试了一下 chtr+shift+c  是可以的。

**Comment by HoollyFox** [comment]
> 我试了一下 chtr+shift+c 是可以的。

可能我表达的不准确，搜索面板内的 block 是可以用这些快捷键的，但是搜索面板的搜索项不能，
也就是
<img width="563" alt="image" src="https://github.com/siyuan-note/siyuan/assets/23378900/6204ce5d-61e9-4cef-86d2-fa269dc2f9ec">
搜索面板右键菜单里面的里面的复制项，是不能快捷键操作的。

**Comment by Vanessa219** [comment]
后面没有标识快捷键的就不能使用。
