### ISSUE TITLE
新增文件类型

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9549]
### In what scenarios do you need this feature?

一个文件在分类上既可能属于文件夹1也可能属于文件夹2，有没有可能增加一个新的文件类型，类似于引用文件，虽然是出现在两个地方，但是本质还是同一个文件。
当文件有了类型的分类，后面新增白板类型的文件也可以直接复用，以及不知道有没有可能有的思维导图类型文件。

### Describe the optimal solution

如上

**Comment by 88250** [comment]
这个可以考虑使用嵌入块，新增类型暂时不考虑了，感谢提议。
