### ISSUE TITLE
代码块内禁用标签补全

### ISSUE THREAD

**Issue by 050644zf** [siyuan-note/siyuan#955]
### 描述问题 Describe the problem

代码块内出现标签补全功能

### 期待的结果 Expected result

应在代码块内禁用标签补全功能

### 截屏或录屏演示 Screenshot or screen recording presentation

![QQ图片20210106191701](https://user-images.githubusercontent.com/30611816/103762740-c9052f80-5053-11eb-925e-ccffa6507815.png)

### 版本环境 Version environment

* 版本 Version：0.5.6

**Comment by 88250** [comment]
感谢反馈，后续考虑。

**Comment by 88250** [comment]
已经完成，我关闭了，谢谢。
