### ISSUE TITLE
Add option "screen always on" for Android, keep the server alive

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#9552]
### In what scenarios do you need this feature?

关联： https://ld246.com/article/1697560390605 
重述下问题，部分手机省电机制造成必须亮屏且思源在前台，网络伺服才能用。所以希望思源提供一个选项，就是当思源在前台时保持手机亮屏。

### Describe the optimal solution

别的APP也有这样的功能，可参考“静读天下”这样的阅读APP，“拟声”这样的音乐播放器APP。

**Comment by 88250** [comment]
这个搞不定的，对于常规 APP 来说，没有常驻的办法，如果用了某些方案，商店审核过不了。

我关闭了，谢谢。
