### ISSUE TITLE
iPad 端思源闪退

### ISSUE THREAD

**Issue by xiriyeyu** [siyuan-note/siyuan#9554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

ipad端思源
打开设置时候会闪退，有时候是点开设置就闪退，有时候点开设置后过一会闪退

### Expected result

希望解决闪退问题

### Version environment

```markdown
- Version: 2.10.12
- Operating System: ios17.0.3
- Browser (if used):
```

### Log file

[system-log (1).zip](https://github.com/siyuan-note/siyuan/files/13198625/system-log.1.zip)

**Comment by 88250** [comment]
你好，我目前从日志上暂时看不出原因，是不是存了很多剪藏的书籍？我看文档只有 300 多个，但是占用了 100MB 的空间，说明其中包含了非常大的文档，非常大的文档加载会比较占用内存，iPad 上有内存限制，占用大的话可能会被系统 kill，可能是这个原因。

**Comment by xiriyeyu** [comment]
奇怪的很，我之前刚重装完了打开设置也会闪退，反倒是打开文档的时候没闪退过

**Comment by 88250** [comment]
现在方便再测试看看新安装的情况吗？

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
