### ISSUE TITLE
独立添加选中文字为命名的快捷键

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

不知道是功能特性还是bug，选中文字后按下快捷键添加为该块命名的快捷键，与直接选中某块打开其属性的快捷键一样。
但在快捷键中没有相关说明，用户认为快捷键是为“打开属性"这一个功能服务的。

### Expected result

建议独立添加为命名的快捷键
或补充说明书
或删除添加为命名的快捷键

### Version environment

```markdown
- Version: 2.10.13dev5
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
快捷键是？

**Comment by chenshinshi** [comment]
比如我在【设置-快捷键】中将“属性”的快捷键设置为ALT+P了，然后我选中文字后点击alt+P就会将该文字添加为命名

D ***@***.***> 於 2023年10月30日 週一 上午9:52寫道：

**Comment by chenshinshi** [comment]
我本来是想打开属性面板，选中文字纯属意外，我也不知道为啥会有添加选中文字为命名的快捷键

Zone Carlton ***@***.***> 於 2023年10月30日 週一 上午9:55寫道：

**Comment by Vanessa219** [comment]
选中文本的话才会进行命名，不选中的话为打开属性，稍后完善文档。谢谢
