### ISSUE TITLE
撤销操作，页面没有跟踪光标处

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#956]
### 描述问题 Describe the problem

撤销操作，页面始终停留在当前页面，不会自动跳到撤销处。
### 截屏或录屏演示 Screenshot or screen recording presentation

![s1](https://user-images.githubusercontent.com/69628966/103765039-7ded1b80-5057-11eb-85e6-61018862e9b4.gif)

### 版本环境 Version environment

* 版本 Version：0.5.6
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
@Vanessa219 和这个 https://github.com/siyuan-note/siyuan/issues/712 一起看下。

**Comment by yeshaopeng6688** [comment]
补充：撤销操作，无法复制代码。
![s1](https://user-images.githubusercontent.com/69628966/103866200-5bfba380-5100-11eb-924f-1e3ee9c2f86a.gif)

ps:新版本啥时候上线~

**Comment by 88250** [comment]
v0.5.7 已经发布，安装包还在上传中……

**Comment by yeshaopeng6688** [comment]
0.6.4 撤销操作，页面已经可以跟踪光标处啦~牛逼
但目前，只要有撤销操作，仍然无法复制代码。。
