### ISSUE TITLE
Database table view supports adding a row below/above

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9560]
类似表格一样，在database 菜单添加在上/下方添加一行功能

### In what scenarios do you need this feature?

RT

### Describe the optimal solution

RT

**Comment by crendy** [comment]
已经有database功能了吗？

**Comment by woniuxia** [comment]
> 已经有database功能了吗？

有了，不过当前是会员公测中，可能等稳定后再完全开放

**Comment by crendy** [comment]
> > 已经有database功能了吗？
> 
> 有了，不过当前是会员公测中，可能等稳定后再完全开放

好的 谢谢
