### ISSUE TITLE
Flashcard "Open in New Tab" retains its status

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

现在的话变更窗口会刷新页面稍微有点反直觉

### Expected result

希望能不刷新页面

### Version environment

```markdown
- Version: 2.10.13dev4
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by chenshinshi** [comment]
omg这个bug修了后，我在新页签复习了一部分闪卡然后中途关闭软件（同步正常），又要从头复习@Vanessa219

**Comment by chenshinshi** [comment]
以前的话是即便不通过关闭新页签和新窗口重新打开闪卡，通过关闭软件重启打开闪卡都会正常记录闪卡复习进度，现在就是关闭软件无法记录复习进度，只能关闭闪卡界面才能记录。

https://github.com/siyuan-note/siyuan/assets/125173405/c735bda4-bdbc-445a-b46f-dcc34f5ff4ed

**Comment by chenshinshi** [comment]
啊等下，进度记录了，重启软件后虽然页签没有刷新，但是关闭页签重新打开后可以看到闪卡数量变少了。所以问题是出在窗口没有刷新。

**Comment by luo-chuan** [comment]
所以还是要刷新？改回来？

**Comment by chenshinshi** [comment]
> 所以还是要刷新？改回来？

不知道能不能加个判断。

**Comment by chenshinshi** [comment]
> 所以还是要刷新？改回来？

螚识别关闭软件为关闭窗口就行，然后触发一次刷新

**Comment by chenshinshi** [comment]
刚才又观察到一个怪bug但没有录屏也不太清楚具体细节，新页签复习状态下，用户没有任何操作，突然右上角的闪卡数量增加，卡片界面白屏（就是没有显示任何字和按钮）。

**Comment by chenshinshi** [comment]
补个可能有关联的社区bug

**Comment by Vanessa219** [comment]
> 刚才又观察到一个怪bug但没有录屏也不太清楚具体细节，新页签复习状态下，用户没有任何操作，突然右上角的闪卡数量增加，卡片界面白屏（就是没有显示任何字和按钮）。

这个很奇怪，无法重现。但  https://github.com/siyuan-note/siyuan/issues/9589  下个版本修复。

至于数据保持那就仅在转换为页签的时候记录一下，后续不进行保持。
