### ISSUE TITLE
希望增加单文章内统一调整图片宽度的功能

### ISSUE THREAD

**Issue by crendy** [siyuan-note/siyuan#9562]
### In what scenarios do you need this feature?

其他笔记迁移过来的文章，在思源内图片展示偏大，目前每个图片可以单独调整宽度，希望可以批量调整文章内所有图片的宽度

### Describe the optimal solution

增加可以批量调整文章内所有图片的宽度

**Comment by 88250** [comment]
这个没有计划，请参考 https://ld246.com/article/1674904322058
