### ISSUE TITLE
Support resetting the learning progress of flashcards

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9564]
### In what scenarios do you need this feature?

希望在闪卡管理界面增加“重置学习进度”功能。有这样一种使用场景：

某些卡片平时也在复习，临近考试，需要高强度复习这些卡片，所以需要将卡片重置进度，让它成为新卡片，重新学习。

### Describe the optimal solution

anki有这个功能，这个应该是闪卡的必要功能。

![image](https://github.com/siyuan-note/siyuan/assets/67137548/38dc3ca5-05d0-4fbe-9fe0-326adb5a0e83)

### Other information

![image](https://github.com/siyuan-note/siyuan/assets/67137548/925b7bed-b606-470d-bf6e-3b299ac693c1)

应该是在管理界面加上按钮，可以将某文件夹或者某文档及子文档的闪卡全部重置

**Comment by 88250** [comment]
通过取消制卡再制卡应该可以重置。

**Comment by Jiangshuon** [comment]
大佬你是看到群里群友的建议了吧(ಡωಡ) ，一个主题下的闪卡好几百张，散落在某文档本身及其子文档中，要在管理界面一个个地点删除，然后遍历该主题下的所有文档页面。。。再重新制卡（还要保证不遗漏）。。。这一番操作下来，黄花菜都凉了。。。群友提到了用闪卡增强插件，可这个不能跨文档，而且制卡方式多种多样。。闪卡重置是很频繁的操作，经常用anki的同学应该是离不开的(ಥ_ಥ)

**Comment by gaoluji** [comment]
这个确实得有

**Comment by Jiangshuon** [comment]
大佬，这个技术上好实现吗？我之前以为很简单，就是把相关的参数初始化一下，但刚瞅了瞅代码，好像没对应参数，似乎没这么简单。

希望明年上半年能有这个功能，我明年6月有个考试，是死是活就靠思源闪卡了(ಥ_ಥ) 。到那时肯定有几千张闪卡，这个功能真少不了，求大佬救我狗命。

**Comment by 88250** [comment]
我们近期分析一下吧，理论上应该就是取消制卡然后再制卡就可以实现重置。

**Comment by Jiangshuon** [comment]
感激不尽！大佬真是活菩萨
