### ISSUE TITLE
移动端对于数据库表格的编辑较大问题

### ISSUE THREAD

**Issue by muhanstudio** [siyuan-note/siyuan#9565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

版本为2.10.13，存在视频中的诸多问题，包括但不限于

- 对于非空的表格会出现无法直接点击修改的现象
- 编辑光标只有放到文档末尾才可以在弹出键盘后将文档尾部滑到键盘上面
- 编辑光标会乱跳现象，点击末尾或者其他地方，弹出键盘以后，光标就弹到了表格标题那里
- 表格的显示和特性输入或者选择也有待优化，在移动端，如果不移开光标，不管任何属性的表格都只是一个文本框，而没有对应的选择属性

### Expected result

- 修复表格的编辑层判断，正常编辑
- 不管编辑光标在哪里，都可以滑到文档末尾
- 光标不会因为任何非用户点击因素而乱跳
- 优化表格在移动端的显示及特性输入或者选择（如果有余力的话）

### Screenshot or screen recording presentation

https://github.com/siyuan-note/siyuan/assets/29907393/764af4ed-6694-425c-b4c2-d7edb5a7c6b8

https://github.com/siyuan-note/siyuan/assets/29907393/ae26e927-0b9b-4862-9de7-8af676fa5030

### Version environment

```markdown
- Version: 2.10.13
- Operating System: Android12-MIUI13.0.5
- Browser (if used):None
```

### Log file

No need.

**Comment by Vanessa219** [comment]
* 非空单元格需要点击没有内容的地方
* 第二点和第三点应该说的是 https://github.com/siyuan-note/siyuan/issues/9520 ，目前已修复，还麻烦再看看
* 对应的选择属性是？

**Comment by muhanstudio** [comment]
- 对应的属性就是点击输入框的时候，不只是输入文本，而是直接弹出列表选择对应的属性项，例如文档/附件/other
![GIF 2023-11-12 8-06-47](https://github.com/siyuan-note/siyuan/assets/29907393/48257d44-038c-402b-b2ac-5e0005b0b4cf)
- 然后就是为什么非空单元格需要点击没有内容的地方呢，在移动端还怎么编辑已经填好的数据呢

**Comment by Vanessa219** [comment]
试了一下多选列，点击是正常的，具体有什么优化建议呢？录屏中的问题也麻烦具体说一下，没太看明白。

链接点击了是跳转，文本的话点击文字也是可以修改的。

**Comment by muhanstudio** [comment]
谢谢V姐了，刚刚在移动端试了一下数据库，已经可以编辑任何表格了，筛选也正常了，看来已经优化好了，没什么问题了

**Comment by Vanessa219** [comment]
刚才发现链接点击空白还是无法编辑，这个需要等下个版本修复了。
