### ISSUE TITLE
哪个版本开始只能用在Windows 11上了？

### ISSUE THREAD

**Issue by norainsX** [siyuan-note/siyuan#9568]
### In what scenarios do you need this feature?

windows 10受众面还是比较广的，但使用最新的代码包安装，提示10无法安装，如：
![image](https://github.com/siyuan-note/siyuan/assets/29322364/fcfe99a8-21a0-47d2-803e-7f636587d2cf)

### Describe the optimal solution

希望windows 10也能用

**Comment by 88250** [comment]
Windows 10 是支持的，不支持的是 Windows7/8 https://github.com/siyuan-note/siyuan/issues/7347

**Comment by LoneFireBlossom** [comment]
如果提示窗如标题所示，那么建议修改1楼中的“以下”为“低于”。
因为“windows 10以下”包含windows 10。
<img width="814" alt="image" src="https://github.com/siyuan-note/siyuan/assets/50087596/e34dbbb1-cf55-4fcd-b6fd-cd336cf2a99a">
