### ISSUE TITLE
Improve database table view data type column prompts and input

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. 日期类型的年份现在可以输入六位数，请问这是feature吗？感觉不太合理，现在输入四位更合理些。
2. 鼠标悬浮预览的内容没有将起始时间与结束时间进行分割
3. 结束时间可不可以作为列的属性，而不是某一个单元格的属性，或者单元格和这一列都可以进行设置，列作为单元格的默认设置，单元格可以进行自己具体的设置
![image](https://github.com/siyuan-note/siyuan/assets/16383685/c3f6c046-841c-4a17-88e1-9b94f7b36350)

### Expected result

1和3希望进行优化
2应该是问题

### Version environment

```markdown
- Version: 2.10.13
- Operating System: Windows 11
- Browser (if used):
```

### Log file

null

**Comment by 88250** [comment]
3 目前不考虑了，参考业界设计。
