### ISSUE TITLE
粘贴代码块会出错

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

粘贴代码块到思源会产生非预期的字符。

如粘贴下述内容：

````
```powershell
ping 127.0.0.1
ping 网关
ping 114.114.114.114
```
````

会出现如图所示的结果：

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/bed545fd-962f-4e76-a4f4-5718c43f2b39)

### Expected result

正常粘贴

### Version environment

```markdown
- Version: 2.10.12
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
我这里无法重现问题哦：

![image](https://github.com/siyuan-note/siyuan/assets/873584/e990f089-0496-4d60-9262-05731a46af76)

**Comment by zxhd863943427** [comment]
最新版好像修复了，神奇。
