### ISSUE TITLE
win版本，能否增加开机自启动最小化到系统托盘

### ISSUE THREAD

**Issue by jiaoting** [siyuan-note/siyuan#9572]
### In what scenarios do you need this feature?

win版本，能否增加开机自启动最小化到系统托盘，这样我做思源服务器的话，就不用每次都输入鉴权密码，然后在最小化了

### Describe the optimal solution

win版本，能否增加开机自启动最小化到系统托盘，这样我做思源服务器的话，就不用每次都输入鉴权密码，然后在最小化了

**Comment by 88250** [comment]
你好，这个暂时不考虑了，可以在鉴权界面使用 Alt+M 隐藏窗口的。

**Comment by jiaoting** [comment]
对了，鉴权界面使用 Alt+M 隐藏窗口，我用了，无法隐藏，没反应。只有在输完密码进入之后才能使用快捷键隐藏窗口



在 2023-11-01 15:18:58，"D" ***@***.***> 写道：

你好，这个暂时不考虑了，可以在鉴权界面使用 Alt+M 隐藏窗口的。

**Comment by 88250** [comment]
收到，我们在 https://github.com/siyuan-note/siyuan/issues/9575 中继续跟进排查和讨论，谢谢。
