### ISSUE TITLE
WebDav同步老是报错，但是多点几次又可以同步

### ISSUE THREAD

**Issue by EJianZQ** [siyuan-note/siyuan#9574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

经常同步的时候报错：同步失败：网络异常，请稍后再试 (Provider: WebDAV) v2.10.13
我多点几次同步也能同步上。但是多端同步的时候很麻烦，总是浪费很多时间反复同步
我使用的WebDav是Alist的，目录挂载的是我服务器本地磁盘，我测试WebDav在我的电脑上使用RaiDrive和PotPlayer连接都良好

### Expected result

请大大帮我看看，是我的WebDav问题还是什么情况

### Version environment

```markdown
- Version:  v2.10.13
- Operating System: Centos
- Browser (if used):Chrome
```

### Log file

I 2023/11/01 15:47:23 sync.go:1192: upsert file [9ec7d9c5bead3ae91fc8038ecb5c12c1e9b8e9c8, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:46:48] chunk [fdd9199bc8f6ba26ff76250c9545ad971212dfd8]
I 2023/11/01 15:47:23 sync.go:1208: upsert chunk [fdd9199bc8f6ba26ff76250c9545ad971212dfd8]
I 2023/11/01 15:47:23 sync.go:1128: uploaded chunk [objects/fd/d9199bc8f6ba26ff76250c9545ad971212dfd8, 1/1]
I 2023/11/01 15:47:23 sync.go:1075: uploaded file [objects/9e/c7d9c5bead3ae91fc8038ecb5c12c1e9b8e9c8, 1/1]
I 2023/11/01 15:47:23 diff.go:50: upsert [lID=330d2b4549e690b7864a37efc602b3d0630983aa, lPath=/20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, lUpdated=2023-11-01 15:36:39, rID=9ec7d9c5bead3ae91fc8038ecb5c12c1e9b8e9c8, rPath=/20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, rUpdated=2023-11-01 15:46:48]
I 2023/11/01 15:47:23 sync.go:234: cloud upsert [330d2b4549e690b7864a37efc602b3d0630983aa, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:36:39]
I 2023/11/01 15:47:23 sync.go:240: local upsert [3a5a4b453716855d4a59b54dbc0f86a4c98bfff7, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719171730-2vvc415.sy, 2023-11-01 15:23:16]
I 2023/11/01 15:47:23 sync.go:240: local upsert [9ec7d9c5bead3ae91fc8038ecb5c12c1e9b8e9c8, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:46:48]
I 2023/11/01 15:47:23 sync.go:240: local upsert [1ae259fc358f1ef56b695b04240194df0dbfcf63, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230718193554-hkeqwuj.sy, 2023-11-01 15:14:51]
E 2023/11/01 15:47:23 sync.go:512: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:47:25 sync.go:414: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:47:25 repository.go:1218: sync data repo failed: unexpected EOF
I 2023/11/01 15:48:09 sync.go:1192: upsert file [6952a2fc6ebd8d22c0d1f81b05f772cf0050442a, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:48:07] chunk [4d0c76cd24a5e9a84e91cc29c8b5d782c5d498da]
I 2023/11/01 15:48:09 sync.go:1208: upsert chunk [4d0c76cd24a5e9a84e91cc29c8b5d782c5d498da]
I 2023/11/01 15:48:09 sync.go:1128: uploaded chunk [objects/4d/0c76cd24a5e9a84e91cc29c8b5d782c5d498da, 1/1]
I 2023/11/01 15:48:09 sync.go:1075: uploaded file [objects/69/52a2fc6ebd8d22c0d1f81b05f772cf0050442a, 1/1]
I 2023/11/01 15:48:09 diff.go:50: upsert [lID=9ec7d9c5bead3ae91fc8038ecb5c12c1e9b8e9c8, lPath=/20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, lUpdated=2023-11-01 15:46:48, rID=6952a2fc6ebd8d22c0d1f81b05f772cf0050442a, rPath=/20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, rUpdated=2023-11-01 15:48:07]
I 2023/11/01 15:48:09 sync.go:234: cloud upsert [9ec7d9c5bead3ae91fc8038ecb5c12c1e9b8e9c8, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:46:48]
I 2023/11/01 15:48:09 sync.go:240: local upsert [3a5a4b453716855d4a59b54dbc0f86a4c98bfff7, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719171730-2vvc415.sy, 2023-11-01 15:23:16]
I 2023/11/01 15:48:09 sync.go:240: local upsert [6952a2fc6ebd8d22c0d1f81b05f772cf0050442a, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:48:07]
I 2023/11/01 15:48:09 sync.go:240: local upsert [1ae259fc358f1ef56b695b04240194df0dbfcf63, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230718193554-hkeqwuj.sy, 2023-11-01 15:14:51]
E 2023/11/01 15:48:11 sync.go:512: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:48:11 sync.go:414: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:48:11 repository.go:1218: sync data repo failed: unexpected EOF
I 2023/11/01 15:48:14 repository.go:1253: synced data repo [kernel=x8g4vsu, provider=3, mode=a/true, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=36 kB] in [1.05s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/11/01 15:50:33 sync.go:240: local upsert [1ae259fc358f1ef56b695b04240194df0dbfcf63, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230718193554-hkeqwuj.sy, 2023-11-01 15:14:51]
I 2023/11/01 15:50:33 sync.go:240: local upsert [3a5a4b453716855d4a59b54dbc0f86a4c98bfff7, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719171730-2vvc415.sy, 2023-11-01 15:23:16]
I 2023/11/01 15:50:33 sync.go:240: local upsert [6952a2fc6ebd8d22c0d1f81b05f772cf0050442a, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:48:07]
E 2023/11/01 15:50:33 sync.go:512: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:50:33 sync.go:414: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:50:33 repository.go:1218: sync data repo failed: unexpected EOF
I 2023/11/01 15:50:35 repository.go:1253: synced data repo [kernel=x8g4vsu, provider=3, mode=a/true, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=36 kB] in [0.68s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/11/01 15:55:35 repository.go:1253: synced data repo [kernel=x8g4vsu, provider=3, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=36 kB] in [0.05s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/11/01 15:56:36 repository.go:1253: synced data repo [kernel=x8g4vsu, provider=3, mode=a/true, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=36 kB] in [0.06s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/11/01 15:59:15 sync.go:1192: upsert file [64d8246b019c6e48ee11c3db48ec7aeaccf51ef8, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:59:14] chunk [cda57f8b3f62c67b73502a0897dbc8d2dbefc54b]
I 2023/11/01 15:59:15 sync.go:1208: upsert chunk [cda57f8b3f62c67b73502a0897dbc8d2dbefc54b]
I 2023/11/01 15:59:15 sync.go:1128: uploaded chunk [objects/cd/a57f8b3f62c67b73502a0897dbc8d2dbefc54b, 1/1]
I 2023/11/01 15:59:15 sync.go:1075: uploaded file [objects/64/d8246b019c6e48ee11c3db48ec7aeaccf51ef8, 1/1]
I 2023/11/01 15:59:15 diff.go:50: upsert [lID=6952a2fc6ebd8d22c0d1f81b05f772cf0050442a, lPath=/20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, lUpdated=2023-11-01 15:48:07, rID=64d8246b019c6e48ee11c3db48ec7aeaccf51ef8, rPath=/20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, rUpdated=2023-11-01 15:59:14]
I 2023/11/01 15:59:15 sync.go:234: cloud upsert [6952a2fc6ebd8d22c0d1f81b05f772cf0050442a, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:48:07]
I 2023/11/01 15:59:15 sync.go:240: local upsert [3a5a4b453716855d4a59b54dbc0f86a4c98bfff7, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719171730-2vvc415.sy, 2023-11-01 15:23:16]
I 2023/11/01 15:59:15 sync.go:240: local upsert [64d8246b019c6e48ee11c3db48ec7aeaccf51ef8, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230719225123-qp4zkso.sy, 2023-11-01 15:59:14]
I 2023/11/01 15:59:15 sync.go:240: local upsert [1ae259fc358f1ef56b695b04240194df0dbfcf63, /20221227215309-vjue4fz/20221229215827-edr4r8v/20230717190741-5lqn4mk/20230718193554-hkeqwuj.sy, 2023-11-01 15:14:51]
E 2023/11/01 15:59:15 sync.go:512: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:59:18 sync.go:414: update cloud indexes failed: unexpected EOF
E 2023/11/01 15:59:18 repository.go:1218: sync data repo failed: unexpected EOF

**Comment by 88250** [comment]
日志中有一些这样的报错：

```
sync data repo failed: unexpected EOF
```

应该是云端存储或者网络的问题，建议看下云端存储服务的日志，应该有相关记录。

**Comment by EJianZQ** [comment]
在我整个删掉同步的目录，然后重新整个上传了数据之后，情况消失了。
我怀疑可能是我手机上用了新的版本，并且进行了同步。然后在旧的docker版本上出现了这个问题，紧接着手机上也有了
