### ISSUE TITLE
The authentication page after startup Alt+M fails

### ISSUE THREAD

**Issue by jiaoting** [siyuan-note/siyuan#9575]
访问授权码的界面，能否可以最小化或者后台隐藏

### In what scenarios do you need this feature?

<img width="336" alt="image" src="https://github.com/siyuan-note/siyuan/assets/12553424/4df39ba7-9678-4f51-890a-cae7dc5e483f">
这个界面，能否有最小化或者后台隐藏的功能？
这样平时在离开电脑时，可以自动锁定并隐藏在后台，要不然每次回来打开电脑都会显示这个画面

### Describe the optimal solution

加一个最小化和关闭按钮，可以最小化到任务栏，关闭按钮可以关闭到后台隐藏

**Comment by 88250** [comment]
这个应该是 bug，之前是可以使用 Alt+M 最小化的 @Vanessa219

**Comment by jiaoting** [comment]
好嘛，直接@老婆。。。。



在 2023-11-02 09:30:38，"D" ***@***.***> 写道：

这个应该是 bug，之前是可以使用 Alt+M 最小化的 @Vanessa219
