### ISSUE TITLE
Freeze on Startup Screen on Wayland

### ISSUE THREAD

**Issue by abd-liac** [siyuan-note/siyuan#9576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

After running command `appimage-run siyuan-2.10.13-linux.AppImage --ozone-platform-hint=auto`, the application freeze on "Finishing boot" screen.

### Expected result

Load everything.

### Version environment

```markdown
- Version: 2.10.13
- Operating System: NixOS Unstable
- Browser (if used):
```

### Log file

```
I 2023/11/01 11:58:02 working.go:121: (deliberately removed)
I 2023/11/01 11:58:02 runtime.go:74: kernel is booting:
    * ver [2.10.13]
    * arch [amd64]
    * os [nixos]
    * pid [8375]
    * runtime mode [prod]
    * working directory [/home/abd-liac/.cache/appimage-run/39a275f3f14a2cfcd7a9907ae724f5be51a60181277c65bebde1bdb30b1b1e01/resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/home/abd-liac/SiYuan]
I 2023/11/01 11:58:02 conf.go:130: initialized language [en_US] based on device locale
I 2023/11/01 11:58:02 runtime.go:128: use network proxy [system]
I 2023/11/01 11:58:02 serve.go:119: kernel [pid=8375] http server [127.0.0.1:43847] is booting
I 2023/11/01 11:58:02 database.go:89: the database structure is changed, rebuilding database...
I 2023/11/01 11:58:02 database.go:109: reinitialized database [/home/abd-liac/SiYuan/temp/siyuan.db]
I 2023/11/01 11:58:02 conf.go:723: database size [4.1 kB], tree/block count [0/0]
I 2023/11/01 11:58:02 working.go:159: kernel booted
I 2023/11/01 11:58:03 box.go:79: auto stat [trees=0, blocks=0, dataSize=37 kB, assetsSize=0 B]
I 2023/11/01 11:58:03 disk.go:33: disk usage [total=110 GB, used=27 GB, free=80 GB]
I 2023/11/01 11:58:03 pandoc.go:155: initialized built-in pandoc [ver=, bin=/home/abd-liac/SiYuan/temp/pandoc/bin/pandoc]
I 2023/11/01 11:58:03 conf.go:940: pandoc initialized, set pandoc bin to [/home/abd-liac/SiYuan/temp/pandoc/bin/pandoc]
I 2023/11/01 11:58:03 index.go:133: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.02s], tree [count=61, size=1.1 MB]
I 2023/11/01 11:58:03 index.go:206: resolved refs [29] in [13ms]
I 2023/11/01 11:58:03 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
```

### More information

Maybe a low priority task, as the environment is **Electron on Wayland with nVidia**, which is currently not quite stable, meaning that it may require upstream effort to fully solve the issue.

But AFAICT, Electron is **working** fine, and the SiYuan-Kernel is **loaded**. No error message was delivered from currently known logs, so I personally have no idea where might the problem be. What I want to know is the general way to debug SiYuan-note.

**Comment by 88250** [comment]
Hello, please try to press Ctrl+Shift+I to open the developer tool, Ctrl+R to refresh the user interface.

Maybe there is some useful information we can find in the debug tool.

**Comment by abd-liac** [comment]
I have tried so, and in the Sources Menu there is still `appearance/boot`.
Any debug suggestion is welcome.

**Comment by 88250** [comment]
Please check requests in the Network tab.

**Comment by abd-liac** [comment]
Only `boot/ icon.png bootProgress` appeared, maybe something goes wrong when decompressing the bootProgress?

**Comment by 88250** [comment]
Please check the latest bootProgress's response data.

**Comment by abd-liac** [comment]
```
{
    "code": 0,
    "msg": "",
    "data": {
        "details": "v2.10.13 Finishing boot...",
        "progress": 100
    }
}
```

**Comment by 88250** [comment]
Can you access it using https://127.0.0.1:6806 in your browser?

**Comment by abd-liac** [comment]
`https://127.0.0.1:6806/` doesn't work with Error code: SSL_ERROR_RX_RECORD_TOO_LONG;
127.0.0.1:6806 works fine.

**Comment by abd-liac** [comment]
That's totally fine as there are more vital features to introduce. It might be a issue from the distribution as well.

For anyone who searching for the issue, use XWayland instead. The only problem with X11 is scaling in HiDPI, just set `xwayland { force_zero_scaling = true }` in Hyprland or something similar in your desktop environment, then zoom inside siyuan-note.

You can close the issue at your convenience if you want. :-)
