### ISSUE TITLE
Identify the database view whether is a "mirror"

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9578]

**Comment by zxhd863943427** [comment]
为什么要专门标识镜像块呢？或者说，原块和镜像块有什么区别呢？

**Comment by 88250** [comment]
就是前面讨论过的数据库块浅克隆，得让用户明确知道是个镜像，修改这个数据库块中的视图后关联的数据库块中的视图也会跟着改变。

**Comment by mozhux** [comment]
说起来，一个文档多个属性视图也是没大意义。。通过关联库去引用属性都好

**Comment by 88250** [comment]
一个块可以放到多个数据库中很正常的，一个数据库块被复制多次也很正常。

**Comment by zxhd863943427** [comment]
> 就是前面讨论过的数据库块浅克隆，得让用户明确知道是个镜像，修改这个数据库块中的视图后关联的数据库块中的视图也会跟着改变。

那我认为不必区分原块和镜像块。全部打上标记即可。

**Comment by 88250** [comment]
是的，就是全部标识为镜像。



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 2, 2023 17:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Identify the database view whether is a"mirror" (Issue #9578)




  
就是前面讨论过的数据库块浅克隆，得让用户明确知道是个镜像，修改这个数据库块中的视图后关联的数据库块中的视图也会跟着改变。
  
那我认为不必区分原块和镜像块。全部打上标记即可。
