### ISSUE TITLE
Database created/updated colmun support hide time

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9581]
### In what scenarios do you need this feature?

数据库创建时间和更新时间支持隐藏具体时间

### Describe the optimal solution

RT

**Comment by 88250** [comment]
这个暂时不考虑了，参考 Notion 等设计。

**Comment by woniuxia** [comment]
这是notion 的
![image](https://github.com/siyuan-note/siyuan/assets/16383685/dfc5ac7f-8821-4750-bc6f-50e018bde4c2)
