### ISSUE TITLE
The referenced block under the folded heading cannot be hovered to view

### ISSUE THREAD

**Issue by whoishuai** [siyuan-note/siyuan#9582]
引用折叠标题下的列表无法悬浮查看

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

引用内容被标题折叠后，不能直接悬浮查看
例子：
####  标题1
引用内容 //引用1
### 页面2
[[引用1]]
****
当标题1被折叠时，不能直接悬浮查看引用块，需要设置标题1为不折叠状态，才能查看

### Expected result

![c7446a658a89c3e69532541130a43c46](https://github.com/siyuan-note/siyuan/assets/96950313/f58900f9-0bbf-4f5b-81dd-ba5618b0418a)

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
你好，我这里测试正常：

![71d97fb2cc7d0cda993e2665bb407438](https://github.com/siyuan-note/siyuan/assets/873584/a4ab5e9c-5c8d-44e4-97d3-c2ab2019d747)

**Comment by whoishuai** [comment]
谢谢作者的回复，但是不好意思，我再次尝试了，发现了问题

文本内容是可以折叠后是可以悬浮查看的
但是如果是列表的就不可以的了
***

https://github.com/siyuan-note/siyuan/assets/96950313/3899bea5-2c8b-4628-a22c-6ce58185f945


例子：
文本内容

1. 列表内容

**Comment by 88250** [comment]
列表可以重现问题了，感谢反馈。

**Comment by 88250** [comment]
下个版本会解决该问题，已经折叠的标题需要手动重新展开再折叠一次。

**Comment by 88250** [comment]
这个改动会导致 https://github.com/siyuan-note/siyuan/issues/12205 中提到的第二点问题，所以折中考虑修改为该情况下依然显示折叠状态：

![image](https://github.com/user-attachments/assets/60c6807c-67f3-454c-b3c6-1fefb8679bfb)

![image](https://github.com/user-attachments/assets/231d60da-38c1-4c53-a723-50ff8cb06758)
