### ISSUE TITLE
Support "Unsplit All" and "Unsplit" tabs

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#9586]
Add "cancel split-screen" button

### In what scenarios do you need this feature?

安卓平板不是用鼠标或触摸板来操作的，不能像电脑一样把右栏的窗口拖到左栏来。建议增加“取消分屏”按钮，方便平板用户取消分屏操作。

### Describe the optimal solution

![Screenshot_20231104_120022](https://github.com/siyuan-note/siyuan/assets/33930736/f6816af9-c149-4bcf-b054-a77ceee1a036)

**Comment by luo-chuan** [comment]
关联： https://ld246.com/article/1699070837062

**Comment by 88250** [comment]
感谢反馈，但平板上的交互优化还要再等等。

**Comment by 88250** [comment]
我们先考虑加一个取消所有分屏的按钮菜单项吧。
