### ISSUE TITLE
Set the maximum width of floating windows

### ISSUE THREAD

**Issue by KuiyueRO** [siyuan-note/siyuan#9587]
### In what scenarios do you need this feature?

思源的预览窗口基于整个应用的右侧对齐，其实不太方便关闭等操作，尤其在21:9的屏幕上。

并且预览窗口会随着屏幕比例拉长

![image](https://github.com/siyuan-note/siyuan/assets/63145205/2ab9a8ff-099e-4f92-80ba-fe2f20f6abc0)

### Describe the optimal solution

obsidian 插件 strange new world 的预览窗口，在计数按钮左侧展开，且有最大宽度限制

![image](https://github.com/siyuan-note/siyuan/assets/63145205/56b31523-7ff6-49ce-8b16-a245d9a8f7f5)

### Describe the candidate solution

希望可以更改预览窗口的宽度和位置

**Comment by Vanessa219** [comment]
我先修改一下宽度吧，如果往左的话，遮挡正文内容过多。
