### ISSUE TITLE
The code block in PDF file has strange shift

### ISSUE THREAD

**Issue by dream-tentacle** [siyuan-note/siyuan#9590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

导出的PDF中跨页的代码块出现了很奇怪的错位现象，例如此处应该在第3、4行的else语句：
![image](https://github.com/siyuan-note/siyuan/assets/127286614/067be2c2-9ed1-4a75-b98b-a216b547bca4)

导出选项：
![image](https://github.com/siyuan-note/siyuan/assets/127286614/c48fb757-f30a-4779-9eb6-2785f36b2fe1)

### Expected result

避免出现此类错位

### Version environment

```markdown
- Version: 2.10.13
- Operating System: Windows 11
```

### Log file

I think the sy.zip file is enough for debugging.

[10.sy.zip](https://github.com/siyuan-note/siyuan/files/13259584/10.sy.zip)

**Comment by Vanessa219** [comment]
这个就是上次提到的问题 https://github.com/siyuan-note/siyuan/issues/9471#issuecomment-1777218061 。目前找不到解决方案进行修改。

**Comment by dream-tentacle** [comment]
> 这个就是上次提到的问题 [#9471 (comment)](https://github.com/siyuan-note/siyuan/issues/9471#issuecomment-1777218061) 。目前找不到解决方案进行修改。

这个不是行号的问题，或者也可能是上次修改后产生的问题？——我去掉行号，也会有这样的移位，明显看到上一页最后一行是空的。

**Comment by Vanessa219** [comment]
这个使用 Chrome 也会存在问题。思源的导出底层调用的就是 Chrome 的。
<img width="743" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/cfa46a5d-0f78-4241-93c3-783922f17abf">
