### ISSUE TITLE
Abnormality in Korean input

### ISSUE THREAD

**Issue by Esdyee** [siyuan-note/siyuan#9591]
If I type in Korean on a Mac, it will be broken like below.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

If I type in Korean on a Mac, it will be broken like below.

In detail,
To use a Chinese analogy, each stroke is written separately.

### Expected result

The image on the error page is embedded with my expectations.

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/24427316/b95e563e-52aa-4b7b-9d49-cdc50f0958fd)

### Version environment

```markdown
- Version: 2.10.13
- Operating System: Mac
- Browser (if used): None
```

### Log file

none error log.

### More information

none

**Comment by fengqiii** [comment]
ｌｉｋｅ　ｔｈｉｓ？
after press down `shift space`

**Comment by Vanessa219** [comment]
麻烦把韩文输入的对应字母发一下。

**Comment by Esdyee** [comment]
@fengqiii 
yes. like that.
If you press and hold SHIFT + SPACE.
You can type normally.
But when you reboot your Mac, the same thing happens again.

**Comment by Esdyee** [comment]
@Vanessa219 
In your screenshot, the first option is probably the one that Koreans usually use.
"2-Set"

**Comment by Vanessa219** [comment]
Sorry, I can't type in Korean. After selecting the configuration, enter abc and space, as shown below. The question you mentioned is how to input it.

<img width="640" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/6f673b21-458a-4a51-bd8a-00fcd7cddd70">

https://github.com/siyuan-note/siyuan/assets/970828/6a066d2b-eeb2-48d6-9e16-8e238b9d01c7

**Comment by 88250** [comment]
Hello, we have closed the issue first. If you still have any questions, please feel free to add them. Thank you.

**Comment by 88250** [comment]
Ref https://liuyun.io/article/1703119939210

**Comment by 88250** [comment]
我这里在 Win 11 上测试微软韩语输入法正常：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/4afbc4ba-a1a5-4465-98cc-91ad0d7079c0)

**Comment by 88250** [comment]
Ref https://liuyun.io/article/1703293706845

**Comment by Vanessa219** [comment]
合并到 https://github.com/siyuan-note/siyuan/issues/4826 进行处理
