### ISSUE TITLE
复制英文文章时候'的bug

### ISSUE THREAD

**Issue by cctv130** [siyuan-note/siyuan#9593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Let’s reverse 复制这句到siyuan里面 出现
![1699270682678](https://github.com/siyuan-note/siyuan/assets/133784576/72b5abf7-5215-43be-9cb4-d91f4a6c9478)
这有两个’,下面的是我改过的

### Expected result

![1699270682678](https://github.com/siyuan-note/siyuan/assets/133784576/e3a50f24-1e33-430f-8681-b326d70dfc44)

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
all
```

### Log file

null

**Comment by zxhd863943427** [comment]
抱歉，但我没有看出区别

**Comment by 88250** [comment]
这个不是 bug，因为 `’` 和 `'` 是两个不同的标点符号，使用撇号 `’` 更准确一些，参考 [英文中的撇号「’」 该如何输入？和「'」有什么区别？ - Klaaaaaaaaaaas的回答 - 知乎](https://www.zhihu.com/question/21755396/answer/2950649700)
