### ISSUE TITLE
云端数据损坏

### ISSUE THREAD

**Issue by jl0476** [siyuan-note/siyuan#9597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

自建的minio，这几个月出现好几次这个问题。
大概了下，一般都是我调整了笔记本的结构，比如将几个笔记移动到某一个笔记之下。
其他的设备就会有这个异常。

现在笔记本规模比较大了，折腾一次要挺久的，看看怎么处理下？

以 `06bcade5c6d1da8785d6d6a65d91d69850b78e07` 这个块为例，在调整那个日志里可以看到upsert的日志
在出问题的客户端就报找不到了

I 2023/11/07 15:15:51 sync.go:1075: uploaded file [objects/db/49fdefe810173ccb10e978596c878328bf54bc, 69/70]
I 2023/11/07 15:15:51 sync.go:1075: uploaded file [objects/13/558b5d45dd60f2290012b452b97b7f29efc777, 70/70]
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [5ff884b8094d989e622e7cee6ce38dd8ef53e394] failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:205: download cloud chunks put failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [da4044c3bd23094222392e0d7b22307a012da463] failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [1de6b15db65071c3243f50ceae94fb5a399f25b1] failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [06bcade5c6d1da8785d6d6a65d91d69850b78e07] failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [2b384dd53e2c9a93768a013556d9a9f681b9267f] failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [a80f9e0aa5002d6e94d9f82f10bf481a037a64c8] failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [a4326463bb164a7eab8e484e76ce639533102eba] failed: cloud object not found
E 2023/11/07 15:15:51 sync.go:1326: download cloud chunk [66e5fbf20396484d476b8cb2fcce3990a2e07b55] failed: cloud object not found
E 2023/11/07 15:15:51 repository.go:1218: sync data repo failed: cloud object not found

### Expected result

解决存储损坏的问题

### Version environment

```markdown
- Version: 2.10.13
- Operating System:  win11
- Browser (if used):
```

### Log file

这个是出问题的客户端日志
[siyuan - 副本.zip](https://github.com/siyuan-note/siyuan/files/13277099/siyuan.-.zip)

这个是调整目录结构的日志
[siyuan -调整.zip](https://github.com/siyuan-note/siyuan/files/13277123/siyuan.-.zip)

**Comment by 88250** [comment]
从目前的日志只能分析出 20230324112216-p0lt859.sy 的分块是 `06bcade5c6d1da8785d6d6a65d91d69850b78e07`，在同步前该 .sy 文件路径移动过（和云端路径不一致），但发现一个和预期不太相符的情况（自上一次的同步点计算问题）还无法确认，我们会在下个版本中加一些日志来确认该问题。

另外，也请你帮忙继续留意云端数据损坏问题，谢谢。

**Comment by jl0476** [comment]
> 从目前的日志只能分析出 20230324112216-p0lt859.sy 的分块是 `06bcade5c6d1da8785d6d6a65d91d69850b78e07`，在同步前该 .sy 文件路径移动过（和云端路径不一致），但发现一个和预期不太相符的情况（自上一次的同步点计算问题）还无法确认，我们会在下个版本中加一些日志来确认该问题。
> 
> 另外，也请你帮忙继续留意云端数据损坏问题，谢谢。

确实移动过，我调整了笔记的结构。将这个笔记移动到其他笔记的下层了。
这几次出问题都是调整了笔记的结构。

**Comment by 88250** [comment]
收到，麻烦继续留意。

**Comment by 88250** [comment]
你好，我们近期发现一个 S3 存储相关的同步 bug #9631 

下个版本 v2.10.15 进行修复，麻烦保持所有设备都升级最新版再观察测试，多谢。

**Comment by jl0476** [comment]
> 你好，我们近期发现一个 S3 存储相关的同步 bug #9631
> 
> 下个版本 v2.10.15 进行修复，麻烦保持所有设备都升级最新版再观察测试，多谢。

好的 辛苦

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by jl0476** [comment]
@88250

 今天下午移动了文档，又出现了同步损坏的问题。
损坏的从8号开始一直没有启动该工作空间。

[1 - 移动文档，调整目录结构日志-siyuan.zip](https://github.com/siyuan-note/siyuan/files/13670333/1.-.-siyuan.zip)
[2-报云端存储损坏的日志-siyuan.zip](https://github.com/siyuan-note/siyuan/files/13670355/2-.-siyuan.zip)

**Comment by 88250** [comment]
请升级到最新版后再观察一下，最新版修复了一个云端数据损坏的问题。

**Comment by jl0476** [comment]
> 请升级到最新版后再观察一下，最新版修复了一个云端数据损坏的问题。
> 
> 对了，升级后需要重置本地数据仓库和云端目录。

升级前调整的目录结构，
升级之后报的异常。

**Comment by 88250** [comment]
嗯，升级前云端已经损坏了，后面麻烦继续观察，记得一定要重置本地和云端。

**Comment by jl0476** [comment]
docker版本今天能发布吗，要重置的的客户端太多了

**Comment by 88250** [comment]
还在打包，应该能发。

**Comment by 88250** [comment]
考虑的，但是要等数据同步完全没有 bug 才能搞。

**Comment by jl0476** [comment]
> 考虑的，但是要等数据同步完全没有 bug 才能搞。

额外多问一句，我两台机器的客户端，同一个同步的数据源。这个图标样式不一致，我想都用第一张图的图标，如何配置？
![image](https://github.com/siyuan-note/siyuan/assets/5226690/758f1eff-a888-4848-89ce-2fdfc4d9ba2e)
![image](https://github.com/siyuan-note/siyuan/assets/5226690/858ae001-216a-4efb-ba6e-42dadccd412d)

**Comment by 88250** [comment]
这个主要是系统 Emoji 字体影响，如果要统一的话可以试试社区集市里面的 Emoji 插件，或者安装一样的字体文件。

**Comment by jl0476** [comment]
> 这个主要是系统 Emoji 字体影响，如果要统一的话可以试试社区集市里面的 Emoji 插件，或者安装一样的字体文件。

具体是哪个字体？
我win10新装的客户端是上面的图标，mac和win11都是下面的图标。
我看论坛里也都是上面的那个图标。

**Comment by 88250** [comment]
Windows 上应该是这个 Segoe UI Emoji font
