### ISSUE TITLE
搜索关键词不能定位问题

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#96]
![test1](https://user-images.githubusercontent.com/29135984/94331407-9da78900-fffe-11ea-82e4-99a9fa3f2294.gif)
图截多了有些没显示出来，同样的段落块有的能定位有的不能，不知为何。（最新版本）

**Comment by 88250** [comment]
这个问题应该和 https://github.com/siyuan-note/siyuan/issues/89 相关，等 v0.2.3 发布以后再帮忙试试看是否修复，谢谢。

**Comment by Vanessa219** [comment]
定位不到的内容是否在文档中？

**Comment by zhl111** [comment]
在

**Comment by Vanessa219** [comment]
今天晚些时候发布 0.2.3，还有问题的话麻烦把文档上传一下。谢谢。

**Comment by 88250** [comment]
@zhl111 你好，v0.2.3 已经发布，请更新到新版本帮忙测试，谢谢！

**Comment by zhl111** [comment]
![test](https://user-images.githubusercontent.com/29135984/94358394-38719780-00d3-11eb-8657-df06629498be.gif)
 还不行呀

**Comment by 88250** [comment]
能把这个笔记本库打包发我邮箱吗？ d@b3log.org

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/94360728-4844a800-00e2-11eb-9fed-9f1bda35cd0b.png)

**Comment by zhl111** [comment]
[大萧条1929_20200926120200-143xjfs.sy.zip](https://github.com/siyuan-note/siyuan/files/5288000/1929_20200926120200-143xjfs.sy.zip)
rar改成zip了。这篇是不能定位的文章，试试

**Comment by 88250** [comment]
感谢，我这里能够重现问题了，我们会尽快修复的。

**Comment by 88250** [comment]
问题主要是因为目前思源笔记还不支持引用“列表项块”，也就是说不能引用列表下面每个项，只能引用这个列表。但是搜索却能搜到列表项下面的段落，所以造成了这个问题。v0.2.4 发布以后会修复，只能引用到列表块，如果列表项下面还有其他块级元素（比如子列表块或者块引用块是可以引用的）。

列表项块的支持请关注 https://github.com/siyuan-note/siyuan/issues/111

**Comment by 88250** [comment]
补充一下，列表如果是“松散模式”（同一个列表项下包含多个块的时候），每个块是可以分别引用的，只有一个当这个列表中每个列表项都只包含一个块时，整个列表会变成“紧凑模式”，这样就只能引用这个列表块了。

松散模式举例：

```markdown
* foo

  foo1
* bar

  bar1
```

在这个“松散”列表中，每个段落块都可以引用到。关于列表的松散/紧凑模式定义，我们是完全遵循 CommonMark/GFM 规范中的定义做的实现，技术细节请参考[这里](https://spec.commonmark.org/0.29/#loose)。
