### ISSUE TITLE
希望通过数据库直接建立的不关联块的条目也可以打开类似属性面板-数据库的弹窗来修改内容

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

现在只能在表格内填写地方太小了
还是两种方式都给会更好些（就像notion那样），用户需要输入大量文字时就可以打开属性面板，少量文字直接在表格内修改

### Expected result

希望能为不关联块的条目提供属性面板

### Version environment

```markdown
- Version: 2.10.14
- Operating System: win
- Browser (if used):
```

### Log file

无需

**Comment by chenshinshi** [comment]
![5c5ca1243823c867b1ed76fd2a2952b2](https://github.com/siyuan-note/siyuan/assets/125173405/ef123aa5-17c9-45b1-801c-7617d01d7e0a)
![200babe89d110256e1332f53ea838650](https://github.com/siyuan-note/siyuan/assets/125173405/6b67a798-1a04-4431-92a9-b7b181c43bd9)
另外发现现在属性页面的数据库是不会显示没有填写的项目的，这就意味着用户确实没法像notion那样在一个纵向表单页面去填写空白项目，就把用户限制在现在这个真的面积特别小的表格里了……

**Comment by chenshinshi** [comment]
或者我有个折中的方案就是把现在的填写数据库内项目的界面改成打开行内备注框的那种界面：
![image](https://github.com/siyuan-note/siyuan/assets/125173405/0488f470-1ba8-42fa-b269-858d4c62ed2a)
![image](https://github.com/siyuan-note/siyuan/assets/125173405/232a17f6-7c91-49da-8ab6-4f9e9a8e4a2d)
这样面积就够了！

**Comment by 88250** [comment]
不关联块的行是没有办法使用属性面板的，估计只能考虑改变输入框交互，但是考虑到类型不一样，哪些需要哪些不需要还不确定。

另外，还在考虑 #9305 是否可以用现有的 Text 替代，即 Text 改为富文本格式，通过编辑器编辑，这样的话必然是需要一个类似浮窗的交互界面的。

**Comment by zxhd863943427** [comment]
> 另外，还在考虑 #9305 是否可以用现有的 Text 替代，即 Text 改为富文本格式，通过编辑器编辑，这样的话必然是需要一个类似浮窗的交互界面的。

可以有这个富文本格式，但是也需要引用列，这两者的粒度和操作都应该是不同的。

这个issue的实现可以参考affine中的database：

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/1e383bd7-dd76-48a4-8990-9c3a24beced3)

简单来说，可能需要一个新的侧面面板。

**Comment by 88250** [comment]
> 可以有这个富文本格式，但是也需要引用列，这两者的粒度和操作都应该是不同的。

有富文本格式的话就不需要引用列了，富文本编辑器里面可以引用。

侧栏面板暂时还是不考虑了，等后面再说吧，感谢提议和讨论，我关闭了。

**Comment by zxhd863943427** [comment]
最简单来说，一个单独的引用列我可以排序每个条目的引用次数。但一个富文本列显然不能。

我的建议是哪个好做先做哪个，但它们的功能不可能完全覆盖的，无法混为一谈。

**Comment by 88250** [comment]
有道理，那个 issue 还开着的，等后面看看。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月9日(周四) 晚上8:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 希望通过数据库直接建立的不关联块的条目也可以打开类似属性面板-数据库的弹窗来修改内容 (Issue #9605)




 
最简单来说，一个单独的引用列我可以排序每个条目的引用次数。但一个富文本列显然不能。
 
我的建议是哪个好做先做哪个，但它们的功能不可能完全覆盖的，无法混为一谈。

**Comment by TCOTC** [comment]
- 关联 #11553
