### ISSUE TITLE
provide a seperate icon for read-only status of single note when it was set to read-only mode alone

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9609]
### In what scenarios do you need this feature?

the global read-only mode can be changed by `ctrl shift g`, however, when I try to use this hotkey to unlock read-only note, it doesn't work fine in some note (they were set to read-only mode by hand).

### Describe the optimal solution

provide a seperate icon to tell user this note is locked by hand, it doesn't follow the global read-only mode.

### Describe the candidate solution

maybe locked-eye, locked-pen, eye, pen, could be used as icons.

**Comment by 88250** [comment]
For the read-only mode, the rule is that a single doc setting overwrites the global setting, and the introduction of more complex settings is not considered. Thank you for your feedback.

[Here](https://github.com/siyuan-note/siyuan/issues/9598) is a discussion thread (in Chinese) of it.
