### ISSUE TITLE
多级列表的编辑逻辑优化

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#961]
### 描述问题 Describe the problem

![子表项编辑逻辑优化](https://user-images.githubusercontent.com/46141646/103825720-5e361180-50b0-11eb-93a7-7f1816c7f953.gif)

如图 我想插入属于3的列表项3.1, **但是却把和3同级的4也变成了3的表项了**
我在3 shift enter后键入 "* "，意思是我想插入一个子表项对3 做补充，而不是想把4 也变成表项
如果我想把4 变成3的子表项，我应该直接到4前 键入"* "

### 期待的结果 Expected result

shift enter后的"* "  **只针对当前行，不要把下面都变成了子表项**

或者保持现有逻辑，提供 **便捷的 插入子表项的操作手段**
因为这样的操作实在是太多了
笔记在编辑和阅读的过程中总会发现，某句话需要进一步补充和解释
这是常见的，高频的操作，值得设计更好的体验

### 版本环境 Version environment

* 版本 Version：0.56
* 操作系统 Operating system：win10

### 更多信息 More information

把所有 “下面的行” 全变成子表项也是一种需求
这个更多是 对层级的 便捷调整
我目前的思路是：
选中tab 降级为子表项
选中shift tab 升级为父级表项

因为目前选中列表项tab没有任何反应，tab可以利用起来
如果有，层级的调整也属于高频功能了

**Comment by lss6378** [comment]
体验了 [Effie](https://www.effie.co/) 的列表编辑，功能看起来很简单，但是使用起来确实非常舒适
- **单行列表编辑**
  - `TAB` 向后缩进
  - `Shift + TAB` 向前缩进
  - `backspace` 在行首向前缩进，在行中删除文字
![backspace单行列表删除与缩进](https://user-images.githubusercontent.com/15924513/104019692-f8a06d00-51f6-11eb-8da4-5d6440d3e362.gif)


- **列表展开/收起**
![列表展开与折叠](https://user-images.githubusercontent.com/15924513/104019901-4f0dab80-51f7-11eb-8780-36f0c907ab8d.gif)

**Comment by wo4wangle** [comment]
> 体验了 [Effie](https://www.effie.co/) 的列表编辑，功能看起来很简单，但是使用起来确实非常舒适
> 
> * **单行列表编辑**
>   
>   * `TAB` 向后缩进
>   * `Shift + TAB` 向前缩进
>   * `backspace` 在行首向前缩进，在行中删除文字
>     ![backspace单行列表删除与缩进](https://user-images.githubusercontent.com/15924513/104019692-f8a06d00-51f6-11eb-8da4-5d6440d3e362.gif)
> * **列表展开/收起**
>   ![列表展开与折叠](https://user-images.githubusercontent.com/15924513/104019901-4f0dab80-51f7-11eb-8780-36f0c907ab8d.gif)

嗯， 我也觉得 Effie 这个列表编辑体验很好
我在“更多信息”里也是这样建议的，这是一个自然的用户习惯

不知道Effie能否多选进行调整
思源可以考虑设计成多选的

调整在笔记中太常见了：顺序调整，层级调整
顺序调整其实也可提供快捷键的方式，因为手动拖动有手动定位成本
