### ISSUE TITLE
If the data repo indexing time is greater than 7s, prompt user to purge the data repo

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9613]

**Comment by zxhd863943427** [comment]
我更希望是30天以外的数据快照每天只保存一份，而不是直接删除。
而且最好是对云端应用这个配置，本地默认关闭，可以自定义开启。
本地的不要有太多的自动清理功能，因为思源目前的数据稳定性并不是无懈可击的，有时候会出现发现数据丢失，需要从很久之前的数据快照中回滚，在论坛里确实有这样的例子。

**Comment by 88250** [comment]
@zxhd863943427 可以通过手动标记快照进行引用，这样就不会被清理了。

**Comment by zxhd863943427** [comment]
但是，在数据丢失前，是不会想到需要快照的……

**Comment by zxhd863943427** [comment]
这个功能毕竟也只是减轻用户本地的数据量，如果不能控制保存快照的频率，那默认开启可能是一种倒退。因为真的需要清理快照的话，这个功能已经存在了。自动清理快照只有在不影响数据冗余的情况下才是合理的。

**Comment by 88250** [comment]
快照太多影响到了启动速度……但是用户不知道哪里有问题，所以自动清理 30 天之前的快照。

**Comment by zxhd863943427** [comment]
建议论坛投票，我认为这是一个需要讨论的问题。

**Comment by 88250** [comment]
还是你来发起一个吧。

**Comment by zxhd863943427** [comment]
已发布。https://ld246.com/article/1699520221020

**Comment by 88250** [comment]
这样吧，现阶段为了稳妥起见，先只进行提示。

数据仓库索引时间如果大于 7 秒，则弹出提示 `检测到数据仓库快照过多，降低了程序启动和数据同步速度，请考虑执行 [设置 - 关于 - 数据仓库清理]`，剩下的决策交给用户自己处理。7 秒这个时间是暂定的，应该足够支撑大部分设备和场景了，等上线一段时间再收集反馈看看。

**Comment by 88250** [comment]
v2.11.0 后将默认时间调整为 12s。
