### ISSUE TITLE
Supports via environment var `SIYUAN_TESSERACT_ENABLED=false` to close OCR

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9619]
OCR 功能开关

### In what scenarios do you need this feature?

数据快照中产生了一个只有ocr-texts.json 的变更，期望对OCR 功能提供开关，如果关闭不产生 ocr-texts.json 文件与相关的变更，即不产生不需要的快照。如果点击开启，请协助用户检查环境变量是否正确，或者把OCR相关环境变量的设置移到思源设置项中。
![image](https://github.com/siyuan-note/siyuan/assets/16383685/c74a1f0e-8704-4451-8aaa-5b5f29ee8d0a)

### Describe the optimal solution

优化 OCR 功能

**Comment by 88250** [comment]
应用内暂时不加开关了，通过环境变量 `SIYUAN_TESSERACT_ENABLED=false` 关闭。

**Comment by woniuxia** [comment]
D大，如果没设置，默认是关闭吗

**Comment by 88250** [comment]
如果 Tesseract 安装到了 PATH 中（就是随便开一个命令行都能执行 `tesseract`），那么思源就默认开启 OCR。

**Comment by woniuxia** [comment]
D大再确认下，本次改动后，如果没有安装Tesseract 就不会生成 ocr-texts.json 文件是吗？



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 10, 2023 11:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Supports via environment var`SIYUAN_TESSERACT_ENABLED=false` to close OCR (Issue #9619)




 
如果 Tesseract 安装到了 PATH 中（就是随便开一个命令行都能执行 tesseract），那么思源就默认开启 OCR。

**Comment by 88250** [comment]
因该是不会了，需要帮忙测试看看。

**Comment by pisceswb** [comment]
需要复制大量图片，想临时关闭一下OCR，请问关闭后复制图片，再启用OCR，新复制到思源笔记中的那些图片还会被OCR吗？

**Comment by 88250** [comment]
应该是会的，可以测试看看。
