### ISSUE TITLE
0.5.6存在无法打开笔记的问题0.5.6-alpha1没有问题

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#962]
### 描述问题 Describe the problem
复现步骤
一、安装0.5.6-alppha1版本
二、新建笔记一切正常
三、再安装0.5.6版本
四、笔记无法打开
已经暂时回退使用上一版本
### 截屏或录屏演示 Screenshot or screen recording presentation
![微信截图_20210107081303](https://user-images.githubusercontent.com/42575324/103835132-5d0ce080-50c0-11eb-919d-e14995c715e3.png)

### 版本环境 Version environment

* 版本 Version：0.5.6
* 操作系统 Operating system：Windows 10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/07 08:02:12 main.go:121: kernel [v0.5.6] is booting, runtime mode is [prod], working directory is [C:\Users\zhenghui\AppData\Local\Programs\SiYuan\resources], temp directory is [C:\Users\zhenghui\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/07 08:02:12 lang.go:67: initialized languages
D 2021/01/07 08:02:12 conf.go:89: loaded conf [C:\Users\zhenghui\.siyuan\conf.json]
I 2021/01/07 08:02:12 conf.go:176: local serve path [http://127.0.0.1:6806]
I 2021/01/07 08:02:12 conf.go:180: initialized conf
I 2021/01/07 08:02:12 main.go:162: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/07 08:02:12 webdav.go:37: initialized WebDAV server
I 2021/01/07 08:02:12 box.go:363: indexing [93] trees, cpus [16]
W 2021/01/07 08:02:12 tpl.go:173: parse ref text template failed: template: :1: unexpected bad character U+2014 '—' in command
W 2021/01/07 08:02:12 tpl.go:173: parse ref text template failed: template: :1: unexpected bad character U+2014 '—' in command
D 2021/01/07 08:02:12 box.go:398: indexed box [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
I 2021/01/07 08:02:12 conf.go:297: initialized box
I 2021/01/07 08:02:13 repo.go:39: initialized git repo
I 2021/01/07 08:02:19 setuilayout.go:43: set ui layout done
I 2021/01/07 08:02:21 process.go:71: ui process exited, exit kernel process now
I 2021/01/07 08:02:21 conf.go:228: exited kernel

**Comment by 88250** [comment]
请在设置中重置一下快捷键应该就行了。

**Comment by GlowBlur** [comment]
重置快捷键后，问题解决
