### ISSUE TITLE
Webdav同步报错

### ISSUE THREAD

**Issue by RabbitHareLu** [siyuan-note/siyuan#9622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我在已关闭的问题中发现有人提了这个问题
![image](https://github.com/siyuan-note/siyuan/assets/150005948/43d963c8-5093-4e0d-b6cd-5e4af6df0d51)

我觉得是不是可以优化一下webdav同步的稳定性
本人其实看中的就是webdav同步, 但是这个同步真的是挺糟心的, 我本来用的是goodsync将笔记同步到infinicloud的, 从来没出过问题. 现在切到思源同步笔记到infinicloud, 真的就是经常报错, 我不清楚是infinicloud的问题还是思源的问题; 但是希望优化一下吧, 这个同步用起来挺恼火的.

### Expected result

webdav同步稳定不报错, 尽量性能好一点

### Version environment

```markdown
- Version: 2.10.14
- Operating System: windows 10
- Browser (if used): 用的是本地的client端
```

### Log file

I 2023/11/09 13:26:59 sync.go:1128: uploaded chunk [objects/eb/c233b3dc959cbe110dc8f2fa5645499417daf6, 96/192]
I 2023/11/09 13:27:00 sync.go:1128: uploaded chunk [objects/89/ae8800c10fd7f9d198a5aab5493f439fc16cc4, 97/192]
I 2023/11/09 13:27:07 sync.go:1128: uploaded chunk [objects/08/0790c858e76755e934247012eb2a87333b7b8d, 98/192]
I 2023/11/09 13:27:07 sync.go:1128: uploaded chunk [objects/f5/48663d4b8efada52e278bb373dac4fe4243634, 99/192]
I 2023/11/09 13:27:09 sync.go:1128: uploaded chunk [objects/1d/98734a050e8933894583eaf227b3714035a48f, 100/192]
I 2023/11/09 13:27:14 sync.go:1128: uploaded chunk [objects/7f/92e1b9ed2dae594e2ea04d0f7dd11ca48bef01, 101/192]
I 2023/11/09 13:27:15 sync.go:1128: uploaded chunk [objects/8a/62947e3edcf406e98a7abe3bbc398c35919425, 102/192]
I 2023/11/09 13:27:15 sync.go:1128: uploaded chunk [objects/ad/81d085c86ee75fd5887398b4bb0b6a5b6861a6, 103/192]
I 2023/11/09 13:27:19 sync.go:1128: uploaded chunk [objects/23/e93f6e03dc26c049699e6e84fd5fcc0938cd8c, 104/192]
E 2023/11/09 13:27:29 webdav.go:89: upload object [study_note/siyuan/repo/objects/8a/2a1b4299f41c3a91c00c3f4971e2db451d8d27] failed: Put "https://futtsu.teracloud.jp/dav/study_note/siyuan/repo/objects/8a/2a1b4299f41c3a91c00c3f4971e2db451d8d27": write tcp ip:63877->103.139.238.147:443: use of closed network connection
E 2023/11/09 13:27:29 sync.go:1276: upload chunks failed: Put "https://futtsu.teracloud.jp/dav/study_note/siyuan/repo/objects/8a/2a1b4299f41c3a91c00c3f4971e2db451d8d27": write tcp ip:63877->103.139.238.147:443: use of closed network connection
E 2023/11/09 13:27:29 sync.go:198: upload cloud failed: Put "https://futtsu.teracloud.jp/dav/study_note/siyuan/repo/objects/8a/2a1b4299f41c3a91c00c3f4971e2db451d8d27": write tcp 172.16.20.42:63877->103.139.238.147:443: use of closed network connection
I 2023/11/09 13:27:29 sync.go:1128: uploaded chunk [objects/a0/4d91a499915c31da875a5162cd4ee662481ba6, 105/192]
I 2023/11/09 13:27:32 sync.go:1128: uploaded chunk [objects/3c/eca4f472b94c9bcb4f59f43e16f8588e3f4f04, 106/192]
I 2023/11/09 13:27:33 sync.go:1128: uploaded chunk [objects/f1/586f97746aaa9dcd05a2bd04a2e40589fb7c3e, 107/192]
I 2023/11/09 13:27:33 sync.go:1128: uploaded chunk [objects/25/0ef638c60326f6b14287779fe0309381d86b0b, 108/192]
E 2023/11/09 13:27:34 repository.go:1218: sync data repo failed: Put "https://futtsu.teracloud.jp/dav/study_note/siyuan/repo/objects/8a/2a1b4299f41c3a91c00c3f4971e2db451d8d27": write tcp ip:63877->103.139.238.147:443: use of closed network connection
I 2023/11/09 13:27:34 sync.go:1128: uploaded chunk [objects/a0/53cb004603f56c4428e1e7be27f555e49ed2d0, 109/192]
I 2023/11/09 13:27:35 sync.go:1128: uploaded chunk [objects/b9/55650c5c9404135ba538711ddf7e12f6f0a749, 110/192]
I 2023/11/09 13:27:37 sync.go:1128: uploaded chunk [objects/d7/ec632ad7a8cb9281b57335ef568bb2b91f8c85, 111/192]
I 2023/11/09 13:28:03 ref.go:49: got latest [5bbde138be5d6638d25b12b2afcede2303ce3b2f, 2023-11-09 13:23:30]
I 2023/11/09 13:28:03 ref.go:49: got latest [5bbde138be5d6638d25b12b2afcede2303ce3b2f, 2023-11-09 13:23:30]
I 2023/11/09 13:28:03 ref.go:49: got latest [5bbde138be5d6638d25b12b2afcede2303ce3b2f, 2023-11-09 13:23:30]

**Comment by 88250** [comment]
你好，从报错日志上看，这个不是思源的问题，是网络的问题。

如果是在国内使用，建议不要用国外的云端服务，网络不稳定。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
