### ISSUE TITLE
能否通過字符标识来快速制卡？

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#9627]
### In what scenarios do you need this feature?

例如：

- 问题？
   - 答案
目前的“闪卡”增强插件，可以利用加粗的问号来实现，例如：
- 问题**？**
    - 答案
bug出在复杂粘贴文本进入思源，插件是不会响应的。我想建议官方来实现这个功能。

### Describe the optimal solution

建议能通过？字符来自动制卡，这样效率高很多。

**Comment by 88250** [comment]
你好，通过输入制卡可能会和正常输入产生冲突，所以我们不打算这样做，可以考虑使用快捷键提高效率，谢谢。
