### ISSUE TITLE
ghproxy.com has been GFW.

### ISSUE THREAD

**Issue by yb6b** [siyuan-note/siyuan#9628]
### In what scenarios do you need this feature?

ghproxy.com 已经 ping 不通，它[官网](https://gh.ghproxy.com/)解释：被墙了。这将导致大陆用户难以自动更新思源笔记。 

### Describe the optimal solution

ghproxy 官网推荐换成 https://mirror.ghproxy.com/ 这个域。

**Comment by 88250** [comment]
感谢告知，稍后改进。
