### ISSUE TITLE
[提议] 给行内代码添加右键菜单,用于复制其纯文本内容

### ISSUE THREAD

**Issue by iamqiz** [siyuan-note/siyuan#9630]
### In what scenarios do you need this feature?

用于快速复制其内容,但不保留反引号

### Describe the optimal solution

1

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/347bed2c-1177-45bb-b209-d62e43f92ceb)

**Comment by iamqiz** [comment]
> ![image](https://user-images.githubusercontent.com/873584/282252098-347bed2c-1177-45bb-b209-d62e43f92ceb.png)

@88250 这个我知道,我是想要"快速复制其内容",手动拖选文字速度慢,且可能会遗漏代码的首尾字符导致命令运行出错.

**Comment by 88250** [comment]
双击再复制



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月12日(周日) 中午12:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] [提议] 给行内代码添加右键菜单,用于复制其纯文本内容 (Issue #9630)




  

  
@88250 这个我知道,我是想要"快速复制其内容",手动拖选文字速度慢,且可能会遗漏代码的首尾字符导致命令运行出错.

**Comment by iamqiz** [comment]
@88250 你试过吗?双击不行的, 比如 `rm -rf `

**Comment by 88250** [comment]
我试的是一个单词....


有的话如果只想复制其中一部分咋办？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] [提议] 给行内代码添加右键菜单,用于复制其纯文本内容 (Issue #9630)




 
@88250 你试过吗?双击不行的, 比如 rm -rf

**Comment by iamqiz** [comment]
@88250 部分就手动拖选,全部就直接右键行内代码,就像块引用和超链接那样

**Comment by 88250** [comment]
我们考虑下，谢谢。

@Vanessa219

**Comment by Vanessa219** [comment]
感觉没有必要，超链接没有复制功能，引用复制的不是可选中的文本。

**Comment by Vanessa219** [comment]
标签是有其他功能，而且上面也没有复制功能。行内代码的话就划选一下吧，可能由于不太必须，感觉基本没有软件实现。

**Comment by iamqiz** [comment]
@88250 @Vanessa219 支持率90%  https://ld246.com/article/1700027015184

**Comment by Vanessa219** [comment]
但是看评论需求不大呀。这个右键弄个菜单出来就一个选项，还会占用这个内容菜单。
<img width="221" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/ae1ca55a-8280-41c1-a503-6239ff87b025">

**Comment by iamqiz** [comment]
@Vanessa219  eeeee.... 评论区几个人都是有复制纯文本需要的哇,只有一个不赞成以右键菜单的形式
选项少可以加,比如"转换为文本"(感觉不常用)  "转换为代码块" (感觉难度大)  "删除行内代码"
关于占用,
我看了下,无论是哪种菜单,菜单项都是放在 id="commonMenu" 的元素里,把右键菜单和这个通用菜单整合在一起就行了

**Comment by Vanessa219** [comment]
检测到行内元素的话在这个上面加一项：复制行内元素。这样行否？

![image](https://github.com/siyuan-note/siyuan/assets/970828/a8ad710a-f943-479b-b4ba-1479c77bd9ca)

**Comment by iamqiz** [comment]
@Vanessa219 对,是这个意思
