### ISSUE TITLE
Data synchronization accidentally deletes local files

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9631]
思源卡住，强制关闭后，刚添加的数据库被删除

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

图1是添加的记录
![image](https://github.com/siyuan-note/siyuan/assets/16383685/55d28757-8f6c-49ca-863f-b0abd9fb13a3)
图2是被删除的记录
![image](https://github.com/siyuan-note/siyuan/assets/16383685/4f3b32c8-7a4b-44da-8de0-754f2c0a4c03)

### Expected result

D大帮忙看下，卡住的原因和数据被删除的原因。

### Version environment

```markdown
- Version: 2.10.14
- Operating System: Windows 11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13324635/siyuan.log)

**Comment by 88250** [comment]
你好，感谢提供日志，卡住的问题暂时没有找到。删除的问题是云端同步删的，还记得 14:07 到 14:11 分之间有使用过其他设备同步吗？

**Comment by woniuxia** [comment]
没有，很确定当时只有这一个设备在运行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月11日(周六) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 思源卡住，强制关闭后，刚添加的数据库被删除 (Issue #9631)




 
你好，感谢提供日志，卡住的问题暂时没有找到。删除的问题是云端同步删的，还记得 14:07 到 14:11 分之间有使用过其他设备同步吗？

**Comment by 88250** [comment]
收到，我再分析看看，多谢。

**Comment by 88250** [comment]
已经找到原因了，是因为下载云端快照文件时存储服务返回了旧的快照文件，但同步算法假设这是最新的，导致合并时删除了本地文件。

根本的原因我们已经发工单咨询存储服务提供商，还需要一些时间排查，谢谢。

**Comment by 88250** [comment]
已经找到一个解决方案，但需要上线测试进行验证，请后续帮忙留意修复情况，谢谢。
