### ISSUE TITLE
Click on the blank area of the link column cannot be edited

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9632]
### In what scenarios do you need this feature?

当前鼠标点击链接类型数据都是直接跳转，想重新编辑不是很方便

### Describe the optimal solution

鼠标悬浮后添加编辑按钮，或者双击进行编辑。
期望链接属性提供比较方便的编辑功能。

**Comment by Vanessa219** [comment]
编辑在非文字区域点击即可，或者当单元格选中后使用方向键和 Enter 进行编辑。
<img width="91" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/2d798d10-353b-4909-ade8-a09f71845f96">

**Comment by woniuxia** [comment]
单行的情况下，可以点击进行编辑的空白区域很小，D大可以试下，如果可以增大空白区域检测的面积也可以的。
使用方向键在操作上有点割接，每次鼠标选中链接旁边的列，然后使用方向键移动到相应的列，再粘贴，不太方便。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月11日(周六) 晚上10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 数据库中链接类型的数据无法修改 (Issue #9632)




 
编辑在非文字区域点击即可，或者当单元格选中后使用方向键和 Enter 进行编辑。

**Comment by Vanessa219** [comment]
类似链接列确实有问题，下个版本修复 [29a805c](https://github.com/siyuan-note/siyuan/commit/29a805c94c1f356edf6db2d009e8ee1c0ada417a)
https://github.com/siyuan-note/siyuan/issues/9565#issuecomment-1806995999
