### ISSUE TITLE
如何给数据库中的链接添加锚文本？

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9635]
### In what scenarios do you need this feature?

我想要在数据库一行中引用多个块，但是目前似乎只能直接绑定一个块。所以另外的块只能用链接的形式。但我发现没办法添加锚文本。我尝试把链接弄好锚文本再复制到数据库中，似乎也不行，点击后不会跳转到对应块。

![image](https://github.com/siyuan-note/siyuan/assets/67137548/8ea11b49-d06e-4b34-a117-54aa5796052c)

### Describe the optimal solution

无

**Comment by 88250** [comment]
链接列目前仅支持超链接地址，使用引用的话请关注 https://github.com/siyuan-note/siyuan/issues/9305 谢谢。
