### ISSUE TITLE
打开多个窗口，新建日记，所有窗口都变成了日记界面

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9636]
### In what scenarios do you need this feature?

不知道算不算bug

1、目前打开三个窗口，第一个窗口是文档页面，另外两个是pdf窗口

![image](https://github.com/siyuan-note/siyuan/assets/67137548/c5b03135-e14a-436d-97d2-a8f262fa8ce3)

2、进入第一个窗口，atl+5创建新日记

3、三个窗口均切换成了日记页面（按理说另外两个不应该切换）

![image](https://github.com/siyuan-note/siyuan/assets/67137548/d72bc48c-9092-42a5-81b3-1e85e1e2c8f2)

### Describe the optimal solution

希望能优化下

**Comment by 88250** [comment]
你好，这是设计如此，应该是之前有需求提过。创建日记文档后广播到所有窗口上，这设计暂时不改变了，谢谢。
