### ISSUE TITLE
D 大考虑设置里面加一个取消聚焦的选项吗？没有需要的人可以关掉

### ISSUE THREAD

**Issue by Leberabit** [siyuan-note/siyuan#9637]
### In what scenarios do you need this feature?

聚焦功能对于没有需要的人很烦

### Describe the optimal solution

设置里面加一个取消聚焦的选项，这样需要的人和不需要的人都能受益

**Comment by 88250** [comment]
你好，聚焦功能是必须存在的，比如从搜索界面跳转到折叠块中就必须是聚焦的。另外，对于主动聚焦的交互而言，我们觉得设计已经较为平衡，所以目前不考虑加入选项关闭了，感谢提议。
