### ISSUE TITLE
更新 2.10.13 后无法使用局域网中的 WebDAV 进行同步

### ISSUE THREAD

**Issue by BruceKangCN** [siyuan-note/siyuan#9639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

- Windows 11 和安卓出现问题，ArchLinux 无问题
- Windows 11 使用 scoop 更新到 2.10.14 后问题依旧，有时提示连通性差，有时提示无法锁定目录
- curl 和 Windows 资源管理器可以正常访问WebDAV服务
- ArchLinux 上的 2.10.13 可以正常同步
- Windows 11 下微软商店和 scoop 中的 2.10.13 均无法同步
- 安卓手机 play 商店的 2.10.14 也无法同步

---

WebDAV 服务是使用 Debian 系统官方源的 `nginx-full` 部署的

### Expected result

正常使用同步功能

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/43891241/75c623ab-5467-4cc3-84a1-26e063e4b361)
![image](https://github.com/siyuan-note/siyuan/assets/43891241/4a753d09-d1b8-4d4d-92d1-21fd969c00c4)
![image](https://github.com/siyuan-note/siyuan/assets/43891241/84835b1f-80c9-4695-b003-28d9561f2f39)
![image](https://github.com/siyuan-note/siyuan/assets/43891241/c124a661-ad0b-436e-8475-ddd1fc3673a3)
![QQ截图20231112215953](https://github.com/siyuan-note/siyuan/assets/43891241/2bb41c15-fae4-49bb-be18-53bf09e384af)

### Version environment

```markdown
- Version: 2.10.13 / 2.10.14
- Operating System: Windows 11 / RedMagicOS8.0.21MR (based on Android 13)
- Browser (if used): none
```

### Log file

https://gist.github.com/BruceKangCN/98a874487977fe417ca7ffbe974043de

**Comment by BruceKangCN** [comment]
> 你好，从日志分析是域名解析的问题，建议排查一下网络设置，谢谢。

我在同一台 PC 上通过域名可以正常访问其他端口的服务，资源管理器也可以正常访问 WebDAV，通过 dig 也可以正常查询到域名对应的 IP，ArchLinux 通过域名也可以同步，我觉得不是域名的问题

**Comment by 88250** [comment]
从报错 "no such host" 判断是域名解析的问题，可以重启下思源看看。

**Comment by BruceKangCN** [comment]
> 从报错 "no such host" 判断是域名解析的问题，可以重启下思源看看。

已经重启过了

**Comment by 88250** [comment]
这就有点难定位了……我看日志中报错的是 `http://bruce-r720.lan:7999` 这个地址，你再确认下是不是配置问题？

**Comment by BruceKangCN** [comment]
> 这就有点难定位了……我看日志中报错的是 `http://bruce-r720.lan:7999` 这个地址，你再确认下是不是配置问题？

不是

**Comment by 88250** [comment]
要不手动配置一下 hosts 解析试试？

**Comment by BruceKangCN** [comment]
> 要不手动配置一下 hosts 解析试试？

今天回家发现 Windows 11 解析不出错了，能正常同步了，怀疑是咖喱系统的问题

**Comment by 88250** [comment]
有可能....

**Comment by BruceKangCN** [comment]
> > 要不手动配置一下 hosts 解析试试？
> 
> 今天回家发现 Windows 11 解析不出错了，能正常同步了，怀疑是咖喱系统的问题

前两天刚被推送 Windows 11 23H2，把系统更新了，时间点上很可疑

**Comment by 88250** [comment]
可以试试刷新 dns `ipconfig /flushdns`
