### ISSUE TITLE
Improve default operation of `^D` on the Mac

### ISSUE THREAD

**Issue by qxj** [siyuan-note/siyuan#9643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

macOS下编辑列表时候如果使用Ctrl-d，会导致如下<异常1>和<异常2>。

比如：

- item1
- item2
- item3

此时，如果想删除item2，挪动光标到item1后，按Ctrl-d，此时列表变成如下形式，出现<异常1>的空白行

- item1<光标>item2
- <异常1>
- item3

然后，在<光标>位置继续按回车，出现<异常2>列表没变化，item2也无法回到原来位置，并且 Cmd-z 也无法undo。

### Expected result

如果光标位置Ctrl-d删除，再enter回车，列表能够复原。

- item1<光标>
- item2
- item3

此时，按Ctrl-d

- item1<光标>item2
- item3

再按回车，列表复原

- item1
- item2
- item3

### Version environment

```markdown
- Version: v2.10.14
- Operating System: macOS 13.4
- Browser (if used):
```

### Log file

编辑期间的log看起来没有异常

```
I 2023/11/13 09:43:07 repository.go:1253: synced data repo [kernel=3iyqj5p, provider=2, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=133 kB] in [0.70s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/11/13 09:51:07 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:51:07 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:51:08 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:51:08 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:51:08 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:51:08 repository.go:1253: synced data repo [kernel=3iyqj5p, provider=2, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=133 kB] in [0.76s], merge result [conflicts=0, upserts=0, removes=0]
I 2023/11/13 09:55:05 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.89s], tree [count=64, size=1.2 MB]
W 2023/11/13 09:55:09 blocktree.go:532: save block tree [size=17 MB] to [/Users/qxj/SiYuan/temp/blocktree], elapsed [5.50s]
I 2023/11/13 09:55:11 index.go:206: resolved refs [32] in [5656ms]
I 2023/11/13 09:55:38 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:55:38 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:55:39 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:55:39 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:55:39 ref.go:49: got latest [46630350da0916e12b46d315eec05a7e049d2e4f, 2023-11-13 09:41:05]
I 2023/11/13 09:55:39 repository.go:1253: synced data repo [kernel=3iyqj5p, provider=2, mode=a/false, ufc=0, dfc=1, ucc=0, dcc=0, ub=0 B, db=133 kB] in [0.92s], merge result [conflicts=0, upserts=0, removes=0]
```

**Comment by 88250** [comment]
你好，默认的 Ctrl+D 快捷键应该是重复块吧？

**Comment by qxj** [comment]
> 你好，默认的 Ctrl+D 快捷键应该是重复块吧？

我查了一下Ctrl-d没有绑定任何快捷键？而且我也没有修改过快捷键。
<img width="1052" alt="image" src="https://github.com/siyuan-note/siyuan/assets/225400/0eff5100-2a5f-402d-ad0a-9dd78972b2f8">

**Comment by qxj** [comment]
重复块是指“重复”吗？我看绑定在Cmd-d
<img width="1048" alt="image" src="https://github.com/siyuan-note/siyuan/assets/225400/837eba10-7e3d-4049-aca0-6ea979221b52">

**Comment by qxj** [comment]
打开开发者工具发现按完ctrl-d再回车，出现null报错，如下图 @88250 
<img width="534" alt="image" src="https://github.com/siyuan-note/siyuan/assets/225400/05264660-bdd6-4aa1-8fc4-411fe48bf429">

**Comment by 88250** [comment]
收到，稍后 @Vanessa219 排查看看。

**Comment by Vanessa219** [comment]
我对段落块操作是正常的，是有什么特殊的操作么？

https://github.com/siyuan-note/siyuan/assets/970828/7a7da670-6e9c-46a6-9604-d772c424659b

**Comment by qxj** [comment]
> 我对段落块操作是正常的，是有什么特殊的操作么？
> 

不是段落块呢，我报的是**列表块**使用Ctrl-d后异常。 @Vanessa219

**Comment by Vanessa219** [comment]
抱歉，按照正文 `ctrl+D` 的话，会重复块 1 ，并不会出现这个问题

* item1<光标>item2
* <异常1>
* item3

https://github.com/siyuan-note/siyuan/assets/970828/fc921a83-00a1-4baf-9e90-dfcb9a08f958

**Comment by qxj** [comment]
> 抱歉，按照正文 `ctrl+D` 的话，会重复块 1 ，并不会出现这个问题
> 

请问录屏环境是Win还是Mac呢？ @Vanessa219 

你这里看起来是ctrl-d绑定了“重复”，但macOS“重复”默认是cmd-d，而ctrl-d是未绑定的，默认行为是delete。

**Comment by Vanessa219** [comment]
哦，macOS 中 `⌃D` 是等于 `fn⌫` ？

**Comment by qxj** [comment]
> 哦，macOS 中 `⌃D` 是等于 `fn⌫`，还是说有细微的差别？
> 
> 那把 `⌃D` 的实现同 `fn⌫` 保持一致并禁止快捷键设置为 `⌃D` 应该就可以解决这个问题了。

没有太看懂，这是需要code fix吗？

`^D`的逻辑就是Delete one charactor，相当于Windows下按delete键。

**Comment by Vanessa219** [comment]
那 `^D` 和 `fn⌫` 是等价的功能，你可以在 item1 后试一下 `fn⌫`。后续修改的效果和 `fn⌫` 一致。

按照以上修改的话，在快捷键设置中就无法将快捷键设置为 `^D`  了。

**Comment by qxj** [comment]
> 那 `^D` 和 `fn⌫` 是等价的功能，你可以在 item1 后试一下 `fn⌫`。后续修改的效果和 `fn⌫` 一致。
> 
> 按照以上修改的话，在快捷键设置中就无法将快捷键设置为 `^D` 了。

理解了。不过我试了`fn⌫`也不太符合预期，不过至少不会报null错误了（打开开发者工具观察），先这么fix也行。

BTW：不太符合预期说明
<img width="88" alt="image" src="https://github.com/siyuan-note/siyuan/assets/225400/e0825635-537d-47c3-af91-e8b56d5bf711">
按`fn⌫`后：
<img width="73" alt="image" src="https://github.com/siyuan-note/siyuan/assets/225400/95eb3f7f-0eaf-4d0b-99dd-af21f8982f2c">
预期结果是：
<img width="61" alt="image" src="https://github.com/siyuan-note/siyuan/assets/225400/850a2d5e-229d-4de9-a250-1b1fac993567">
不过我目前没有Windows系统，回头我试试Windows下按Delete是不是也同样表现。

**Comment by Vanessa219** [comment]
这个是为了和在 2 前面 `⌫` 保持一致。
