### ISSUE TITLE
Support keymap configuration for `Ctrl+Tab` and `Ctrl+Shift+Tab`

### ISSUE THREAD

**Issue by ni554n** [siyuan-note/siyuan#9645]
### In what scenarios do you need this feature?

In general, `Ctrl + Tab` & `Ctrl + Shift + Tab` are mostly used for _Go to Next / Previous tab_ in the OS and the browser. Two of my mouse keys and touchpad gestures are set to those keys for easy tab switching.

### Describe the optimal solution

We should be able to remove the key mappings of **Switcher** and assign them to other functions.
> I prefer to use `Ctrl + E` to view _Recent Documents_ anyway.

**Comment by Vanessa219** [comment]
Swap the following keymap?

Ctrl + Tab <=> Ctrl + Shift + ]
Ctrl + Shift + Tab <=> Ctrl + Shift + [

<img width="1037" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/07e4f1bc-b9ce-471f-82a7-c00699feee3c">

**Comment by ni554n** [comment]
Yes, exactly. Currently `Ctrl + Tab` and Ctrl + Shift + Tab` are invalid in the key mapper.

**Comment by Vanessa219** [comment]
Sorry, I just referred to IDE and Chrome again. Our default values are consistent with the IDE. Perhaps as you said at the beginning, providing shortcut key configurations for `Ctrl + Tab` and `Ctrl + Shift + Tab` can solve this problem.
