### ISSUE TITLE
Query embed block supports executing JavaScript

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9648]
允许嵌入块内执行 Js 以增强复杂查询能力的提案

### In what scenarios do you need this feature?

* **需求**：希望能允许在嵌入块内执行 JS，以弥补原始的 SQL 本身逻辑不足的缘故
* **理由**：SQL 虽然强大，但是由于缺失基本的顺序执行。条件片段等逻辑，在处理复杂逻辑查询方面会异常受限

  * 一方面：我个人高强度使用 SQL 查询，但是还是会遇到「即便写了非常复杂的 sql 语句仍然得不到满意的查询效果」的情况
  * 另一方面：友商的查询语法选择了自定义的 DSL，虽然不能像 SQL 那样通用强大，但是却可以定义简单的执行逻辑，从而在特定的复杂查询方面胜过 SQL
* **思路**：

  * 不引入新的 DSL，而是直接允许使用 js 代码来控制嵌入块的内部逻辑
  * 在**不变更思源本体机制的前提**下，通过一些小 trick 变相能在嵌入块中执行 js 逻辑
  * **原则**：动刀子尽可能小，**绝对不涉及**大规模代码更新甚至重构

### Describe the optimal solution

具体的实施方案分为两个部分：

* 第一部分：如何告知思源，某一个嵌入块要执行 js 代码而非单纯的执行 SQL 查询
* 第二部分：如何具体的将 js 翻译成需要查询的块。

#### 1. 通过（在嵌入块开头加入 shebang || 设置自定义属性）来声明本嵌入块是否要执行 js

* 方案总结

  1. 方案一：当嵌入块内容以以下声明为开头的时候，将这个嵌入块视为一个可执行 js 的嵌入

      ```sql
      //!js
      ```
  2. 方案二：设置自定义属性，特定属性的嵌入块会被认为应该作为 js 来执行
* 具体说明

  嵌入块的相关代码在[https://github.com/siyuan-note/siyuan/blob/master/app/src/protyle/render/blockRender.ts](https://github.com/siyuan-note/siyuan/blob/master/app/src/protyle/render/blockRender.ts)，其中第 32 行会读取嵌入块的内容并当作一个 sql 查询内容，然后交给 `/api/search/searchEmbedBlock` API 执行

  
  ![image](https://github.com/siyuan-note/siyuan/assets/27268127/9f547af1-14fa-4e22-8ca7-963584e63c39)

  所以只需要在 32 行后面加上判断即可获知改嵌入块是否需要用 js 来执行

#### 2. 如何将 js 转化为嵌入块查询：两个独立的方案

* 基本原理

  1. 规定： JS嵌入块最后一句，应当返回一个 `Block[]`
  2. 在前端部分，将 JS 嵌入块代码放入 `Function` 对象中，并提供一个 `sql` api 用于查询 sql

      * `sql` api 可以直接比照前端的 api
      * 为了保证数据安全，可以在 Function 对象内部禁用 `fetch` 等可能引起安全问题的 API
  3. 根据 JS 嵌入块代码返回的 Block 列表来构造嵌入块，具体而言有两种方案

      * 【优选】后端方案：让后端加一个 API，好处是非常直接直观后面也方便继续优化，坏处是后端需要加一个额外的 API
      * 【次选】前端方案：把 js 翻译成 `selelct * from id in (...)` 语句，坏处是不够直接且可能让前端代码逻辑变复杂，好处是后端完全无感

##### 2.1 后端方案：后端提供一个新的 API，直接给定 block list 返回嵌入块查询

由弘哥首先提议

![image](https://github.com/siyuan-note/siyuan/assets/27268127/17380966-d087-4ce5-8550-7b01491a33b4)

我后面也研究了一下后端嵌入块查询的调用过程，觉得应该可以实现。只需要去掉 `search.go` 的调用，直接用前端给的 block list 就行。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/ae660ef4-2d74-4959-ba18-a77d2cd60cff)

##### 2.2 前端方案：将 js 执行过程拼接为新的 SQL 语句

基本思路是：

* 执行 js 代码，获取 block list
* 将 block list 拼成 `select * from blocks where id in ("id1", "id2", ...)`，比如这样：

  ```js
  const func = async () => {
      let sql = `select * from blocks where content like "%Python%" and root_id != '20231114083336-jti8mwu' and type not in ('t', 's') order by updated desc limit 8 ;`;
      const blocks = await api.sql(sql);
      let idList = blocks.map((block) => `"${block.id}"`);
      sql = `select * from blocks where id in (${idList.join(",")})`;
      return sql
  }
  ```
* 将新的构造的 SQL 语句发往后端
* 将返回结果按照发送时候的顺序重新排列一下

  * 我自己做了一下测试，发现 `select * from blocks where id in ("id1", "id2", ...)` 语句可以查询到正确的结果，但是嵌入块内部DOM的排列顺序却是乱的，所以为了保证顺序正确，需要前端在 [searchEmbedBlock](https://github.com/siyuan-note/siyuan/blob/25c656a88a02fd162402970ef752472c2cc8e342/app/src/protyle/render/blockRender.ts#L44) 的返回结果中将 `response.data.blocks` 重新排序一下。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/e2db0a1d-d044-4f96-a3f2-3a50beb0065c)

## 补充：为什么不想做成插件

1. 希望操作更加顺滑
2. 希望复用原生的嵌入块显示能力
3. 插件能力有限，就比如如果要使用插件，只能用「前端方案」，但是由于无法控制后端的逻辑，所以查询的结果会乱序

**Comment by 88250** [comment]
后端方案中需要新增的内核接口麻烦描述一下入参出参。

**Comment by frostime** [comment]
> 后端方案中需要新增的内核接口麻烦描述一下入参出参。
> 
> 另外，这里的 `//!js` 是参考 sh 吗？
> 
> ![image](https://user-images.githubusercontent.com/873584/283318747-141f4777-c2bf-45eb-9da9-1252a5a10f9b.png)
> 
> 可能在前端开发看来会理解为 **非js** 😂

关于出入参数，也许可以参考一下 `/api/search/searchEmbedBlock` 的接口？比如 searchEmbedBlock 的输入是

```ts
{
    embedBlockID: string,
    stmt: string,
    headingMode: 1 | 0,
    excludeIDs: [item.getAttribute("data-node-id"), protyle.block.rootID],
    breadcrumb: boolean
}
```
可以仿照这个接口，直接输入给定的 block id
```ts
{
    embedBlockID: string,
    includeIDs: string[],
    headingMode: 1 | 0,
    breadcrumb: boolean
}
```

至于输入和 searchEmbedBlock 保持一致，都是吧。
```ts
{
	blocks: blocks
}
```

------

那个 `//!js` 确实就是无脑模仿 `sh`，当时如果不合适也可以换成别的，比如就一个 `//js`；或者不一定用 shenbang，用块自定义属性判断也行。😂

**Comment by 88250** [comment]
能否来一段脚本示例，比如完成某个功能的，这样我们好具体再讨论看看。

**Comment by frostime** [comment]
> 能否来一段脚本示例，比如完成某个功能的，这样我们好具体再讨论看看。

以下面这个例子为例，这个是我使用 `RunJs` 插件运行的，这个插件就是基于 `Function` 来运行 js 的。

下面这个案例的目标是，将查询的结果，按照笔记本自定义排序的大小来排列。程序最后返回一个 `Promise<Blocks[]>` 对象，可以在调用 `Function` 对象的代码中获取返回值。
```js
//js
const notebooks = window.siyuan.notebooks.reduce(
    (target, key, index) => { target[key['id']] = key; return target;},
    {}
);
/**
 * 查询的结果按照文档树上笔记本自定义排列的顺序排列
 */
const query = async () => {
    //为了方便测试，加了 order by random()
    let blocks = await api.sql(`
    select * from blocks where created like '20231116%' order by random() limit 16`);
    blocks.sort((b1, b2) => notebooks[b1.box].sort - notebooks[b2.box].sort);
    console.log(blocks.map((b) => {return {box: notebooks[b.box].name, content: b.content};}));
    return blocks;
}
//返回一个 block 列表，嵌入块就根据这个 block 的内容和顺序来展示
return query();
```

![image](https://github.com/siyuan-note/siyuan/assets/27268127/445adf85-6b22-4789-a238-2cf878697858)

前端获取到返回的 `Block[]` 后，可以将对应的 `id` 传入`includeIDs`参数，从而来要求内核获取相应的笔记内容。

---

实际操作的时候，还可以做一些简化，比如可以允许用户只编写 `query` 函数内部的内容，然后前端部分将其包裹在一个 `async () => {${code}}` 内部。

**Comment by 88250** [comment]
感谢，我还需要确认下，需要内核新开接口主要原因是 /api/query/sql 接口返回不了嵌入块接口需要的格式对吧，后半段要使用已有嵌入块渲染的代码？

**Comment by frostime** [comment]
> 感谢，我还需要确认下，需要内核新开接口主要原因是 /api/query/sql 接口返回不了嵌入块接口需要的格式对吧，后半段要使用已有嵌入块渲染的代码？

对，或者更确切的说是由于 SQL 语法本身的一些缺陷，有些复杂一点的查询难以或者无法实现；希望可以通过引入 js 的程序逻辑来增强查询的能力。

**Comment by 88250** [comment]
嗯，逻辑增强我知道，上面主要问的是实现上的参数格式。这样吧，我们再考虑看看，也许下个特性版 v2.11.0 就安排上。

**Comment by 88250** [comment]
实现方案：

* 使用 `//js` 作为标识
* 使用内核接口 `/api/search/getEmbedBlock` https://github.com/siyuan-note/siyuan/issues/9681

前端 @Vanessa219

**Comment by IAliceBobI** [comment]
![image](https://user-images.githubusercontent.com/27268127/282654012-e2db0a1d-d044-4f96-a3f2-3a50beb0065c.png)

是否还可以有另外的方案？

这里能否直接由js，给出符合渲染需要的数据格式。不需要js来拼装sql？

**Comment by Vanessa219** [comment]
目前前端支持 return Promise 或者 array

```
//!js 
return ["20230506210010-houyyvy"]

//!js 
const query = async () => {
    let blocks = await fetchSyncPost("/api/system/getConf", {});
    return ["20230506210010-houyyvy"]
}
return  query()
```

**Comment by zxhd863943427** [comment]
能否进一步解偶，直接由js运行getEmbeBlock？

**Comment by Vanessa219** [comment]
目前是通过执行 js 获取 id 数组，进一步解耦要如何做？

**Comment by zxhd863943427** [comment]
初步想法是嵌入块直接使用js返回的html，但是从代码来看，/api/search/getEmbedBlock 的返回结果好像不是html数组
，使用的renderEmbeBlocks也不是返回html，而是直接操作protyle，emmm，感觉要改还是需要仔细想想怎么操作。

**Comment by zxhd863943427** [comment]
我先研究一下接口，还不知道真的返回了什么，新版还没测试。

主要想法不是在内核返回了什么，而是嵌入块能显示什么能否自定义。比如说，能否直接显示一个表格？

**Comment by 88250** [comment]
那恐怕不行，这个和编辑器相关。

**Comment by zxhd863943427** [comment]
看了下接口，我觉得是完全符合要求的

**Comment by Jiangshuon** [comment]
大佬，请问这个功能可以实现，嵌入块查询某一篇文档的内容，其结果按原文内容排序吗？

**Comment by Jiangshuon** [comment]
我的用法是这样，所以想能按块在文档中的顺序排序
![image](https://github.com/siyuan-note/siyuan/assets/67137548/c136c33d-e479-4d15-b058-0ac798829fe5)

**Comment by 88250** [comment]
@Jiangshuon 这个还不行，后面等看看需求，如果多的话会考虑。

**Comment by frostime** [comment]
> 大佬，请问依靠这个特性，我可以用js让嵌入块查询某一篇文档的块时，其结果按块在文档中的顺序排序吗？

这个确实，有时候用 SQL 查询内容的时候，同一个文档里面的顺序都是乱的。
我想问一下，各个块在同一个文档里面先后顺序的信息是在哪里记录的？SQL 表里面好像也没有相关的信息。

**Comment by 88250** [comment]
数据库里面没有记录的，这个需要加载文档 ast 后去匹配，搜索 按文档分组 下支持 原文内容顺序排序：

![image](https://github.com/siyuan-note/siyuan/assets/873584/b3e80930-a834-4792-8bde-029e7f21b1c9)


![image](https://github.com/siyuan-note/siyuan/assets/873584/31e84762-c150-495f-b9de-54cb6dce63df)

**Comment by zxhd863943427** [comment]
> > 大佬，请问依靠这个特性，我可以用js让嵌入块查询某一篇文档的块时，其结果按块在文档中的顺序排序吗？
> 
> 这个确实，有时候用 SQL 查询内容的时候，同一个文档里面的顺序都是乱的。 我想问一下，各个块在同一个文档里面先后顺序的信息是在哪里记录的？SQL 表里面好像也没有相关的信息。

其实可以使用/api/block/getBlockIndex获取位置，然后进行排序。

**Comment by zxhd863943427** [comment]
经过测试，runjs的功能可以拓展为返回html渲染结果，并且不改变原有结果。js可以执行在定义在全局变量中的视图生成函数。

并且，这时候嵌入块内容依然可以被索引到。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/e7b2c627-b0d6-42f1-acc0-3e6d6c0884bc)

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/bbb20929-37d7-4df3-875c-16134e8cef6c)

我觉得这个一个不错的改进方向。

代码可见于 https://github.com/zxhd863943427/siyuan/tree/runjsEnhance

是否可以pr这个？

**Comment by 88250** [comment]
@Vanessa219 review 下看看 https://github.com/zxhd863943427/siyuan/commit/326dcd9ec20434e89defc976d4acf4ac9d75f5ad

**Comment by Vanessa219** [comment]
genTable 这个函数是在哪里声明的？

**Comment by zxhd863943427** [comment]
这是一个在外部的代码片段中声明的函数，定义见下：
```
const genTable = (blocks)=>{
    let body = ''
    blocks.forEach((blockItem)=>{
        body += `<tr><th>${blockItem.block.hPath}</th><th>${blockItem.block.type}</th></tr>`
    }
    )
    let table = `<table>
    <thead><th>hPath</th><th>type</th></thead>
    ${body}
    </table>`
    return table
}

function generateCardViewHTML(blocks) {
    let html = `<div class="card-deck">`;

    blocks.forEach(block=>{
        html += `
      <div class="card">
        <div class="card-header">
          ${block.block.hPath}  
        </div>
        
        <div class="card-body">
          <p class="card-text">${block.block.content}</p>
        </div>
      </div>
    `;
    }
    );

    html += `</div>`;

    return html;
}
```

卡片视图还使用了这些css：
```css
.card-deck {
    display: flex;
    flex-wrap: wrap;
}
.card {
    margin-left: 1%;
    margin-right: 1%;
    margin-top: 10px;
    padding: 3%;
    max-height: 400px;
    overflow: hidden;
    overflow-y: scroll;
    border-radius: 10px;
    flex-direction: column;
    flex: 1 0 250px;
    display: flex;
    background-color: #c4c4c486;
}
```
我认为生成视图的函数没必要捆绑到思源中，完全可以让插件和代码片段来自定义。

**Comment by Vanessa219** [comment]
这样的话 renderCustomEmbed 也应该与其放在一处。

在 return 的时候返回空，后续的所有都可以由用户自己进行处理。

**Comment by zxhd863943427** [comment]
renderCustomEmbed需要处理一些共通的逻辑，附加元素到嵌入块中，并且取消事件冒泡。

有一些是可以拆分出来的，但需要对这个部分进行改造，需要对new Function(content)()传入上下文，不然无法实现。比如说附加元素到嵌入块。

有一些是完全没必要拆分的，比如说取消滚动图，还有设置style，以及取消冒泡。

**Comment by Vanessa219** [comment]
这部分还是由用户自己定义吧，这样比较开放，后期也不需要去维护。

**Comment by zxhd863943427** [comment]
那么需要修改一下new Function，改为：
```js
new Function("protyle","item","top",content)(protyle,item,content)
```
这样才能让元素实现自定义操作。不过这样可能会导致无法索引，还需要进行测试。

**Comment by Vanessa219** [comment]
嗯嗯，顺便把返回空的情况处理一下，不要再走 renderEmbed 即可。你直接 PR 吧。

**Comment by zxhd863943427** [comment]
还需要一个api来更新块的content，目前sql api只能查询，无法执行update操作。

**Comment by 88250** [comment]
@zxhd863943427 你说的是内核还是前端？

**Comment by zxhd863943427** [comment]
前端，需要一个新的api便于索引内容。

**Comment by Vanessa219** [comment]
是 `api/transactions` 这个么？

**Comment by zxhd863943427** [comment]
并不是，是 sqlite 的 blocks 表里的 content 字段，这个是用来搜索的字段，自定义渲染内容最好能自己更新这个字段，才能被搜索到。如果直接写在备注、别名等位置，虽然可以达成搜索的效果，但是会污染原有的 sy 文件。

**Comment by 88250** [comment]
@zxhd863943427 你说的是 js 嵌入块需要更新 content 字段对吧？这里目前是不支持自动索引的，因为 go 里面没法执行 js：

![image](https://github.com/siyuan-note/siyuan/assets/873584/c2e9ea7f-8303-42c5-8da8-e2d328efcaa9)

所以是需要加个接口来主动更新 content 字段？

**Comment by zxhd863943427** [comment]
对的，需要一个接口，至少要能实现这种操作：
```js
 fetchSyncPost('/api/query/updateContent',{"id": id, "content": content})
```

**Comment by 88250** [comment]
执行 searchEmbedBlock/getEmbedBlock 的时候后端会自动索引的，怕是没有必要重复索引了：

![image](https://github.com/siyuan-note/siyuan/assets/873584/6dd9091f-f158-4a50-b63b-f8879245e926)

**Comment by zxhd863943427** [comment]
但是，searchEmbedBlock/getEmbedBlock 自动索引的内容和自定义渲染的内容可能是不一样的。

**Comment by 88250** [comment]
那等晚点我们还是提供一个更新 content 的内核接口吧。

**Comment by zxhd863943427** [comment]
另外，api/search/getEmbedBlock的返回感觉缺了好多值：
```
 "block": {
                    "box": "20230917171404-1s8stgn",
                    "path": "/20231122202402-vcooo3s.sy",
                    "hPath": "test/2222222",
                    "id": "20231123131215-t1m9qa5",
                    "rootID": "",
                    "parentID": "",
                    "name": "",
                    "alias": "",
                    "memo": "",
                    "tag": "",
                    "content": "\u003cdiv data-node-id=/div\u003e...",
                    "fcontent": "",
                    "markdown": "而言，插件主要面向程序功能扩展，不面向内容块扩展。",
                    "folded": false,
                    "type": "NodeParagraph",
                    "subType": "",
                    "refText": "",
                    "refs": null,
                    "defID": "",
                    "defPath": "",
                    "ial": {
                        "alias": "11",
                        "bookmark": "111",
                        "custom-avs": "20230808232238-9qwehxq,20231124153111-pdtnnfo",
                        "custom-block": "1111",
                        "custom-temp": "111",
                        "id": "20231123131215-t1m9qa5",
                        "memo": "222",
                        "name": "111",
                        "updated": "20231123133525"
                    },
                    "children": null,
                    "depth": 0,
                    "count": 0,
                    "sort": 0,
                    "created": "",
                    "updated": "",
                    "riffCardID": "",
                    "riffCard": null
                },
```
什么部分是会正确返回，什么只是留一个空字符串，这个能说明吗

**Comment by 88250** [comment]
好像提供更新 content 的接口会有问题，因为这个 content 适合 block 绑定的，如果提供更新 content 的接口的话 block 变动后就不一致了。

**Comment by 88250** [comment]
嵌入块返回的结果很多字段没有填充，前端目前没有用上的就不填充了。

**Comment by zxhd863943427** [comment]
> 好像提供更新 content 的接口会有问题，因为这个 content 是和 block 绑定的，如果提供更新 content 的接口的话 block 变动后就不一致了。

额，不乱用应该没问题，毕竟自定义渲染肯定是每次更新都会重新调用一次。

**Comment by 88250** [comment]
改了原块就会被自动覆盖，失去效果了。数据库上最好是只读单向的，仅从 block -> content 方向索引，否则后面可能会引起其他问题。

**Comment by zxhd863943427** [comment]
等等，和block绑定，是哪个block？

**Comment by 88250** [comment]
编辑器里面的 block

**Comment by zxhd863943427** [comment]
为什么getEmbedBlock没有违反这个规则呢？

**Comment by 88250** [comment]
searchEmbedBlock/getEmbedBlock 仅更新嵌入块的 content，不能更新其他块。

**Comment by zxhd863943427** [comment]
那能否同样提供一个能自定义内容、仅更新嵌入块的 content的api？

**Comment by 88250** [comment]
能是能，就是感觉破坏单向的设计怕后面出事 😂

**Comment by 88250** [comment]
后面试试这个接口 https://github.com/siyuan-note/siyuan/issues/9736

**Comment by Zuoqiu-Yingyi** [comment]
@Vanessa219 @88250 该功能的具体使用方法是否未写入用户手册中❓
