### ISSUE TITLE
导出 HTML 的图片问题

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#965]
### 你在什么场景下需要该功能？

有一个频率比较高的使用场景是用本地软件写好一篇东西之后，导出 HTML 并复制发布到在线平台上，现在导出的 HTML 里图片是一个本地 url 形式，往任何一个在线平台复制都会导致图片转存失败

### 描述最优的解决方案

导出 HTML 的时候，图片有没有可能改为直接用 base64 插入...

### 描述候选解决方案

本来想导出 PDF，但是导出 PDF 一直不成功

**Comment by 88250** [comment]
你好，目前看的话如果有线上分享需求最好是使用在线图床，一些在线平台的编辑器会自动拉取图床图片插入。

PDF 导出有什么报错吗？

**Comment by deerainw** [comment]
用图床的话主要有三个问题，一是某些平台只中转不拉取或者用懒拉取，以后原图床链接一失效图片就会挂；二是能同时应对好墙外平台与国内平台的方便商业图床基本没有；三是在最开始编辑文档的时候，最佳最便捷的插图方式就是直接粘贴图片到本地，如果导出 HTML 时图片是本地链接的话，导出的意义就没有了，相当于导出了也只能给自己看

不过这个不改的话也没什么，有发布需求的人确实不多...

导出 PDF 没有直接报错，就是一直卡在这里，我都是在小文件上试着导出，但是目前只成功导出过一次

![image](https://user-images.githubusercontent.com/32661922/103862372-f4daf080-50f9-11eb-9000-156a5d1b2f44.png)

**Comment by 88250** [comment]
PDF 导出的问题麻烦升级到 v0.5.7，然后重置一次界面和快捷键后再试试，谢谢。
