### ISSUE TITLE
[渐进阅读] 思源下一个版本可以加上脚注功能吗

### ISSUE THREAD

**Issue by Leberabit** [siyuan-note/siyuan#9650]
### In what scenarios do you need this feature?

如题，渐进阅读的第 1 步就是导入，但由于思源无法识别脚注语法，导入后会失去脚注 😭

希望 D 大在下一个版本加上，毕竟这似乎很好实现（？）
在论坛上也反映了这个问题（https://ld246.com/article/1699937073319）因为真的很急😂

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/150246877/6a14beba-bf85-4b4e-a3f7-36ba9078dc08)
强烈建议在 备注 的同时增加 脚注 功能（能自动编号的那种，如图），学习古文、经典著作时特别需要。
（截图来自 wolai）

**Comment by 88250** [comment]
你好，不考虑加入脚注功能，感谢提议。

**Comment by Leberabit** [comment]
> 你好，不考虑加入脚注功能，感谢提议。

请问这是出于什么考量呢😂

**Comment by 88250** [comment]
1. 可以使用引用
2. 非常难实现

**Comment by Leberabit** [comment]
> 1. 可以使用引用
> 2. 非常难实现

好的，谢谢回复。另外，我那个闪卡挖空依次显示的需求多久reopen

**Comment by 88250** [comment]
目前看没有太多需求，就算有近期应该也没有精力解决，抱歉了。
