### ISSUE TITLE
编辑器输入双引号光标位置异常，迅速跳到左侧

### ISSUE THREAD

**Issue by juzideju** [siyuan-note/siyuan#9651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在编辑器界面输入中文的双引号“ ”时，光标并不会出现在双引号中间，会立马快速跳到双引号左侧。

### Expected result

输入中文双引号后，光标定位于双引号之间，方便编辑。

### Version environment

```markdown
- Version: 2.10.14
- Operating System: windows 11
- Browser (if used):
```

### Log file

I 2023/11/14 19:34:51 conf.go:401: user has disabled [Google Analytics]
I 2023/11/14 19:34:51 runtime.go:128: use network proxy [system]
I 2023/11/14 19:34:51 serve.go:119: kernel [pid=11712] http server [127.0.0.1:8669] is booting
I 2023/11/14 19:34:51 blocktree.go:478: read block tree [164 kB] to [C:\Users\86182\SiYuan\temp\blocktree], elapsed [0.01s]
I 2023/11/14 19:34:51 conf.go:723: database size [2.0 MB], tree/block count [11/582]
I 2023/11/14 19:34:51 working.go:159: kernel booted
I 2023/11/14 19:34:51 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=C:\Users\86182\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/11/14 19:34:51 conf.go:940: pandoc initialized, set pandoc bin to [C:\Users\86182\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/11/14 19:34:51 box.go:79: auto stat [trees=11, blocks=582, dataSize=19 MB, assetsSize=2.4 MB]
I 2023/11/14 19:34:51 disk.go:33: disk usage [total=255 GB, used=119 GB, free=136 GB]
I 2023/11/14 19:34:52 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
I 2023/11/14 19:48:38 conf.go:485: exiting kernel [force=false, execInstallPkg=0]
I 2023/11/14 19:48:38 database.go:1199: closed database
I 2023/11/14 19:48:38 conf.go:880: cleared workspace temp
I 2023/11/14 19:48:38 sync.go:670: sync websocket closed
I 2023/11/14 19:48:44 working.go:121: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/11/14 19:48:44 runtime.go:74: kernel is booting:
    * ver [2.10.14]
    * arch [amd64]
    * os [Microsoft Windows 11 Pro]
    * pid [7684]
    * runtime mode [prod]
    * working directory [C:\Users\86182\AppData\Local\Programs\SiYuan\resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [C:\Users\86182\SiYuan]
I 2023/11/14 19:48:44 conf.go:401: user has disabled [Google Analytics]
I 2023/11/14 19:48:44 runtime.go:128: use network proxy [system]
I 2023/11/14 19:48:44 serve.go:119: kernel [pid=7684] http server [127.0.0.1:8811] is booting
I 2023/11/14 19:48:44 blocktree.go:478: read block tree [163 kB] to [C:\Users\86182\SiYuan\temp\blocktree], elapsed [0.01s]
I 2023/11/14 19:48:44 conf.go:723: database size [2.0 MB], tree/block count [11/582]
I 2023/11/14 19:48:44 working.go:159: kernel booted
I 2023/11/14 19:48:44 pandoc.go:132: built-in pandoc [ver=3.1.1, bin=C:\Users\86182\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/11/14 19:48:44 conf.go:940: pandoc initialized, set pandoc bin to [C:\Users\86182\SiYuan\temp\pandoc\bin\pandoc.exe]
I 2023/11/14 19:48:44 box.go:79: auto stat [trees=11, blocks=582, dataSize=19 MB, assetsSize=2.4 MB]
I 2023/11/14 19:48:44 disk.go:33: disk usage [total=255 GB, used=119 GB, free=136 GB]
I 2023/11/14 19:48:45 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting

**Comment by 88250** [comment]
你好，这个可能是输入法无法识别编辑器的 DOM 格式，目前无法兼容解决，只能考虑关闭输入法的标点匹配，抱歉。

**Comment by juzideju** [comment]
好的感谢，使用的是百度输入法最新版，会出现问题。
尝试过搜狗输入法、微软输入法，这两款不会触发标点匹配（即使打开该功能）

期待日后有条件改进该功能。
