### ISSUE TITLE
请求段落首行缩进功能开关，符合中文习惯

### ISSUE THREAD

**Issue by juzideju** [siyuan-note/siyuan#9652]
### In what scenarios do you need this feature?

1、编辑长篇、长段落文章需要
2、长文本阅读
3、另外添加标题大小以及颜色设置

### Describe the optimal solution

1、设置界面添加首行缩进开关
2、工具栏设置快捷按钮

**Comment by 88250** [comment]
你好，这个不考虑增加了，见谅。

标题大小和颜色可通过代码片段或者自定义主题实现，谢谢。
