### ISSUE TITLE
Add kernel API `/api/filetree/getIDsByHPath`

### ISSUE THREAD

**Issue by jabobian** [siyuan-note/siyuan#9654]
Allow more paremeters for /api/filetree/createDocWithMd

### In what scenarios do you need this feature?

I used to use  /api/filetree/createDocWithMd to append markdown to a doc with specified human readable path, e.g. Notes/YYYY/MM/DD
But after some version, the API will not append the existing doc, but create a new doc with same name. As is said in the API document: If you use the same path to call this interface repeatedly, the existing document will not be overwritten.

So I want an API to get the id of a human readable path. I know I can use SQL to get it, but the code is bulky, can you afford one more API to "Get ID based on human readable path and the notebook id", and one can specify to get the first ID or all the IDs.

### Describe the optimal solution

Can you afford one more API to "Get ID based on human readable path and the notebook id", and one can specify to get the first ID or all the IDs.

**Comment by 88250** [comment]
Hello, thanks for your proposal, we will add the following kernel API in the next release:

* `/api/filetree/getIDsByHPath`
* Parameters

  ```json
  {
    "path": "/foo/bar",
    "notebook": "20210808180117-czj9bvb"
  }
  ```

  * `path`: Human-readable path
  * `notebook`: Notebook ID
* Return value

  ```json
  {
    "code": 0,
    "msg": "",
    "data": [
        "20200813004931-q4cu8na"
    ]
  }
  ```
