### ISSUE TITLE
建议出个 选择 上面和下面的, 然后中间的一起都选中

### ISSUE THREAD

**Issue by 834116404** [siyuan-note/siyuan#9658]
### In what scenarios do you need this feature?

详细看链滴: https://ld246.com/article/1695887679106

### Describe the optimal solution

详细看链滴: https://ld246.com/article/1695887679106

### Describe the candidate solution

详细看链滴: https://ld246.com/article/1695887679106

### Other information

详细看链滴: https://ld246.com/article/1695887679106

**Comment by 88250** [comment]
抱歉，这个不考虑了，请使用 Ctrl+Click 或者 Shift+↑/↓ 多选。

**Comment by 834116404** [comment]
> Shift+↑/↓
Shift+↑/↓ 不管用,

**Comment by 88250** [comment]
焦点要在文档树面板上才有用。

**Comment by 834116404** [comment]
> 焦点要在文档树面板上才有用。

我点击左侧的文档树,然后焦点不在文档树上, 在右侧的文章详情上..

**Comment by 88250** [comment]
试试 Alt+1



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月16日(周四) 中午11:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 建议出个 选择 上面和下面的, 然后中间的一起都选中 (Issue #9658)




  
焦点要在文档树面板上才有用。
  
我点击左侧的文档树,然后焦点不在文档树上, 在右侧的文章详情上..
