### ISSUE TITLE
日记与关系图建议

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#966]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
当梳理笔记时通过关系去想按标签目录等特过滤显示
目前只能给特定块打标签，希望能够针对文档级可以打标签

### 描述最优的解决方案 Describe the optimal solution
关系图删选功能，排除特定目录，或者只针对特定目录渲染
可以打按文档标题，标签等过滤
后期有日记功能，也应该可以选择是否排除日记，因为日记很多是流水线或者碎片化的，整理的时候不会特别关注

**Comment by 88250** [comment]
感谢建议，v0.7.0 会加入关系图上的过滤条件。

**Comment by 88250** [comment]
请关注 https://github.com/siyuan-note/siyuan/issues/793 ，谢谢。
