### ISSUE TITLE
Improve heading2doc/li2doc sorting

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9668]
heading2doc api 插入子文档的顺序不一致

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

我在改进重构插件的拆分标题为子文档的功能，结果发现按顺序调用api的结果是乱序的。经过排查，发现哪怕手动拖动标题到文档述操作的结果也是乱序的，因此确实是api实现的问题。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/623b67cb-44a4-4e96-a857-0b179897d9e7)

### Expected result

希望heading2doc的结果是确定的，无论是新插入的会在最下方还是最上方都好，但千万不要是随便找一个位置插入或上下交替插入。

### Version environment

```markdown
- Version: v2.10.13
- Operating System: win10
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
使用的排序规则是？

**Comment by 88250** [comment]
标题转换文档后不设置 sort 值，在列出文档树的时候如果是自定义排序，sort 值相同（为 0）的情况下会根据文档 ID 中的时间部分进行降序，其他排序方式没有这个比较，可能会有问题。

![image](https://github.com/siyuan-note/siyuan/assets/873584/5bcfd6b8-63fe-46ab-92f2-eb7715f9b756)

**Comment by zxhd863943427** [comment]
使用的是自定义排序。那应该如何操作才能让它按顺序插入？

**Comment by 88250** [comment]
我们调整一下，heading2doc/li2doc 时在自定义排序 sort.json 中插入一个当前层级下最小的 sort 值，这样就可以排序在顶部了。
