### ISSUE TITLE
笔记模板功能建议

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#967]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

我们在新建笔记时特别是日记、工作日志、学习笔记等有特定的格式来整理思路
目前我都是整理一个模板文件夹，要建新笔记复制一份新建很不方便

### 描述最优的解决方案 Describe the optimal solution
从文件树新建文档时，新建文档对话框可以选择应用模板
文档模板目录在设置中配置
-->

**Comment by 88250** [comment]
你好，命名为 `templates` 的文件夹会自动作为模板文件夹，目前需要通过 `{{` 触发模板搜索来手动调用，可参考帮助文档模板相关内容。

**Comment by 88250** [comment]
我关闭了，感谢提议， 后续的日记功能 #399 会支持配置日记模板路径。
