### ISSUE TITLE
Can the 'Fixed Search' page be configured to open without splitting the screen?

### ISSUE THREAD

**Issue by Foundation-Maker** [siyuan-note/siyuan#9675]
### In what scenarios do you need this feature?

<img width="694" alt="image" src="https://github.com/siyuan-note/siyuan/assets/46839690/60b5341a-e753-41c1-b393-5bd85aafc408">

### Describe the optimal solution

When the pinned search is turned on, it is full page

**Comment by 88250** [comment]
Hello, this is designed like this, use split-screen tabs to open it, thank you.

**Comment by Foundation-Maker** [comment]
> Hello, this is designed like this, use split-screen tabs to open it, thank you.您好，这是这样设计的，使用分屏选项卡打开它，谢谢。
What is the reason for the design?

**Comment by 88250** [comment]
Avoid covering existing tabs.

**Comment by Foundation-Maker** [comment]
> Avoid covering existing tabs.避免覆盖现有选项卡。
Then you must have a big screen;

**Comment by 88250** [comment]
If you just want to make the search interface larger, you can drag the border of this layer to make it larger.

**Comment by Foundation-Maker** [comment]
> If you just want to make the search interface larger, you can drag the border of this layer to make it larger.如果只是想让搜索界面变大，可以拖动该图层的边框使其变大。

Why can't we make it easier for users to operate?

**Comment by 88250** [comment]
I don't quite understand what you mean by "easier"?

**Comment by Foundation-Maker** [comment]
> I don't quite understand what you mean by "easier"?
Your analytics tool should be able to see that search is a high-frequency feature, and it would be a mistake to want the user to drag and adjust it every time. Your product design principles should include user simplicity and ease of use.

**Comment by 88250** [comment]
You may not have seen SiYuan's code. We do not have such analysis tools...

I think it’s a good idea to retain the size after dragging the global search interface @Vanessa219

**Comment by Foundation-Maker** [comment]
> You may not have seen SiYuan's code. We do not have such analysis tools...你可能没有看过思源的代码。我们没有这样的分析工具......
> 
> I think it’s a good idea to retain the size after dragging the global search interface @Vanessa219我认为在拖动全局搜索界面后保留大小是个好主意@Vanessa219

NO！No, I'm not clear enough, you misunderstood, it's a fix search page, not a global search floating page

**Comment by 88250** [comment]
That will cover other tabs, as mentioned before, so I think retaining the drag size is a better solution.

**Comment by Foundation-Maker** [comment]
> That will cover other tabs, as mentioned before, so I think retaining the drag size is a better solution.如前所述，这将涵盖其他选项卡，因此我认为保留拖动大小是更好的解决方案。

But after you're done searching, you click on the content and you'll be taken to a page.

**Comment by Foundation-Maker** [comment]
Don't know if other users are behaving differently than me

**Comment by 88250** [comment]
If you don’t need to split the screen, you can unsplit the search tab.

![image](https://github.com/siyuan-note/siyuan/assets/873584/da9c96e1-0c9a-4d96-9c36-6be37d53713f)

**Comment by mozhux** [comment]
you can use left and right layout
![image](https://github.com/siyuan-note/siyuan/assets/46953371/a156bdb5-feb3-45c3-9084-095abf9602d6)

**Comment by Foundation-Maker** [comment]
> you can use left and right layout您可以使用左右布局 ![image](https://user-images.githubusercontent.com/46953371/283750030-a156bdb5-feb3-45c3-9084-095abf9602d6.png)

yes, I'm currently on the left and right layout, why don't I use global search because it refreshes and I need to search multiple times to find what I want

**Comment by Foundation-Maker** [comment]
> If you don’t need to split the screen, you can unsplit the search tab.如果不需要拆分屏幕，可以取消拆分搜索选项卡。
> 
> ![image](https://user-images.githubusercontent.com/873584/283749467-da9c96e1-0c9a-4d96-9c36-6be37d53713f.png)

Yes, I can unsplit the search tab, but why do I have to have a config item? Because you have a problem with the tab management logic, even if I lock the fixed search in the tab, it will close by mistake. 1. Your window closes based on the order in which it is opened, not the order in which it is arranged, and 2. The title of your window is displayed outside the screen instead of zooming out.

**Comment by 88250** [comment]
Sorry, I still can't understand what you need.
