### ISSUE TITLE
关于缩小.sy文件大小提升部分性能

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#9676]
### In what scenarios do you need this feature?

之前不是已经做了去除结构化数据提升性能的功能吗，然后我感觉还可以再彻底一点，比如把所有属性都改成无意义的标识，我感觉两位字母就可以搞定，例如Children、NodeParagraph、NodeListItem、Properties这种高频出现的完全没必要用这么长的标识，全部用两位字母表示的话我测试了一个4mb的文档大概是原先的百分之75左右的大小，性能还是能提升一点的，不知道这个想法能否实现？

### Describe the optimal solution

如上

**Comment by Chenm4** [comment]
感觉用两位数字这样是否还能更快一点？我不太了解，只是有时候数字作为tag处理起来比字符串可能更快一点

**Comment by Foundation-Maker** [comment]
I think software performance is related to language, for example, you can take a look at the zip archive after the word docx format is extracted

**Comment by 88250** [comment]
这个暂时不考虑了，目前这部分性能已经够用了，调整的话要动的地方太多，风险有点高，感谢提议。
