### ISSUE TITLE
Do not show history in search panel

### ISSUE THREAD

**Issue by luo-chuan** [siyuan-note/siyuan#9677]
### In what scenarios do you need this feature?

关联： https://ld246.com/article/1700199194140 
希望搜索界面不要显示最近编辑的块，保护隐私。
![图片](https://github.com/siyuan-note/siyuan/assets/33930736/b8cd7419-6ec4-4fc0-aa0c-1d5b3d43d859)

### Describe the optimal solution

给个选项或开关。

**Comment by 88250** [comment]
这是个设计特性，不考虑增加关闭选项了，见谅。
