### ISSUE TITLE
Support `Close all tabs at startup` on mobile

### ISSUE THREAD

**Issue by STMRabbit** [siyuan-note/siyuan#9678]
### In what scenarios do you need this feature?

Like most note-taking app, they start up without showing the previous visited page.  
This option works nice on desktop, but missing on mobile app.  
When I enabled 'network serving' on phone and then enable it on a web browser, it still doesn't work.  

### Describe the optimal solution

Users should have capabilities to enable it on the mobile UI.

### Describe the candidate solution

if not planned to change mobile UI, user should have the capability to enable it in the settings accessed through the web serving mode, and the this sets should be valid on regular mobile UI as well. 

### Other information

Tysm!   : - )

**Comment by luo-chuan** [comment]
me too

**Comment by 88250** [comment]
Thanks to the feedback, we chose to improve via the candidate solution you proposed.

**Comment by STMRabbit** [comment]
Tysm and have a good day! : - )  Thanks for the amazing work!

**Comment by zxkmm** [comment]
Hello all, I think I found a new bug which is related to this post.  
Here is details: https://ld246.com/article/1700581893083  
Could be this one or https://github.com/siyuan-note/siyuan/issues/9680, and I'm still researching it.

**Comment by luo-chuan** [comment]
感觉这个问题在安卓手机端（不是伺服）并没有修复呢。

**Comment by 88250** [comment]
@luo-chuan 需要伺服状态下打开开关
