### ISSUE TITLE
升级0.5.7后应用启动报错

### ISSUE THREAD

**Issue by w91** [siyuan-note/siyuan#968]
### 描述问题 Describe the problem
升级后应用启动一直显示loading，控制台有报错

### 期待的结果 Expected result
程序正常启动

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/2599455/103873268-84889b00-510a-11eb-84b7-511c66b7ef9e.png)

### 版本环境 Version environment

* 版本 Version：0.5.7
* 操作系统 Operating system：Mac 10.14.6

### 日志文件 Log
今天的只有 
I 2021/01/07 14:32:21 setuilayout.go:43: set ui layout done
这一条

**Comment by 88250** [comment]
请重置设置快捷键后再看看，谢谢。

**Comment by w91** [comment]
> 请重置设置快捷键后再看看，谢谢。

现在应用进不去，没法打开设置页，需要回退上一个版本重置吗？

**Comment by 88250** [comment]
删除 ~/.siyuan 重启试试。

**Comment by w91** [comment]
![image](https://user-images.githubusercontent.com/2599455/103875432-61131f80-510d-11eb-98a8-da485cb70563.png)
现在点击“打开本地文件夹”报错，之前的打开记录丢失了

**Comment by w91** [comment]
![image](https://user-images.githubusercontent.com/2599455/103875840-dd0d6780-510d-11eb-9791-db9956106c10.png)
删除 ~/.siyuan 重启又试了下，有新的报错

**Comment by 88250** [comment]
完全卸载以后重装看看。

**Comment by w91** [comment]
还是一样，appearance目录是不是没配置路由，整个目录都访问不到

**Comment by 88250** [comment]
你本地启用了代理或者什么其他 VPN 之类的软件吗？

**Comment by w91** [comment]
是有代理，但是像 http://127.0.0.1:6806/stage/vditor/dist/js/lute/lute.min.js?v=0.5.7 这些我启动应用后都能在chrome里正常打开的，就那个语言文件404，很奇怪
![image](https://user-images.githubusercontent.com/2599455/103878494-768a4880-5111-11eb-96cf-b3e06b1d762f.png)

**Comment by 88250** [comment]
不要代理本地 6806 和 6807 端口。

**Comment by deerainw** [comment]
我升  056 的时候遇到编辑器不显示的问题，删除重装或是删除 `~/.siyuan` 不起作用，后来把全盘所有名字带 `*siyuan*` 的文件都删除再重装解决了问题（包括那堆 `.pf` 文件），楼主可以试试。。

**Comment by w91** [comment]
> 我升 056 的时候遇到编辑器不显示的问题，删除重装或是删除 `~/.siyuan` 不起作用，后来把全盘所有名字带 `*siyuan*` 的文件都删除再重装解决了问题（包括那堆 `.pf` 文件），楼主可以试试。。

谢谢，卸载先装了个0.4的版本，再装最新的版本可以了😂

**Comment by 88250** [comment]
我关闭了，谢谢。
