### ISSUE TITLE
无法制作出这样的表格

### ISSUE THREAD

**Issue by awut-star** [siyuan-note/siyuan#9683]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![2](https://github.com/siyuan-note/siyuan/assets/90757590/e0e50162-73b5-4db5-8027-e9cea2cf3ebc)

https://github.com/siyuan-note/siyuan/assets/90757590/3e767969-818f-4a50-8ff4-8ccbcd3f13fa

无法制作出 `Expected result` 里面图片那种表格，在合并第二个输入 6 的三个单元格时好像会“删除”排在最后一行的单元格。

### Expected result

![1](https://github.com/siyuan-note/siyuan/assets/90757590/8dc74a38-5bb6-4dab-8a87-1c1d7948360d)

### Version environment

```markdown
- Version: v2.10.9
- Operating System: windows 10 1809 
- Browser (if used):none
```

### Log file

```
I 2023/11/16 09:46:14 working.go:121: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/11/16 09:46:14 runtime.go:74: kernel is booting:
    * ver [2.10.9]
    * arch [amd64]
    * os [Microsoft Windows 10 Enterprise LTSC 2019]
    * pid [7076]
    * runtime mode [prod]
    * working directory [C:\]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [D:\]
I 2023/11/16 09:46:14 conf.go:401: user has disabled [Google Analytics]
I 2023/11/16 09:46:14 runtime.go:128: use network proxy [system]
I 2023/11/16 09:46:14 serve.go:119: kernel [pid=7076] http server [127.0.0.1:53931] is booting
I 2023/11/16 09:46:14 blocktree.go:463: read block tree [244 kB] to [D:\], elapsed [0.01s]
I 2023/11/16 09:46:14 conf.go:719: database size [2.0 MB], tree/block count [63/1019]
I 2023/11/16 09:46:14 working.go:159: kernel booted
I 2023/11/16 09:46:14 pandoc.go:115: custom pandoc [ver=3.1.1, bin=C:\]
I 2023/11/16 09:46:14 box.go:79: auto stat [trees=63, blocks=1019, dataSize=583 kB, assetsSize=33 kB]
I 2023/11/16 09:46:14 disk.go:33: disk usage [total=256 GB, used=1.8 GB, free=254 GB]
I 2023/11/16 09:50:21 conf.go:485: exiting kernel [force=false, execInstallPkg=0]
I 2023/11/16 09:50:21 database.go:1205: closed database
I 2023/11/16 09:50:21 conf.go:876: cleared workspace temp
I 2023/11/16 09:50:21 sync.go:670: sync websocket closed
I 2023/11/16 09:50:22 conf.go:534: exited kernel
```

**Comment by zxhd863943427** [comment]
可复现

**Comment by awut-star** [comment]
> 可复现

可以

**Comment by Vanessa219** [comment]
需要把内容撑高以后才会出现

<img width="269" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/54b70d3a-d0b3-48c4-883f-9927b4ca6218">

**Comment by awut-star** [comment]
> 需要把内容撑高以后才会出现
> 
> <img alt="image" width="269" src="https://user-images.githubusercontent.com/970828/284224879-54b70d3a-d0b3-48c4-883f-9927b4ca6218.png">

![image](https://github.com/siyuan-note/siyuan/assets/90757590/e9dd78ff-9685-406d-a661-6eb22e5028f2)
可以有第三列没合并时的效果吗？

**Comment by awut-star** [comment]
> 需要把内容撑高以后才会出现
> 
> <img alt="image" width="269" src="https://user-images.githubusercontent.com/970828/284224879-54b70d3a-d0b3-48c4-883f-9927b4ca6218.png">

![image](https://github.com/siyuan-note/siyuan/assets/90757590/da646f4e-c00e-4722-8012-ce1b4992db88)
横向的时候没问题

**Comment by Vanessa219** [comment]
意思是高度没有对齐么？试了下 min-height 没有效果，目前还没找到对齐的方案。

<img width="259" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/0e03623c-365d-4248-b420-21b7dfc05d22">

**Comment by awut-star** [comment]
> 意思是高度没有对齐么？试了下 min-height 没有效果，目前还没找到对齐的方案。
> 
> <img alt="image" width="259" src="https://user-images.githubusercontent.com/970828/284283399-0e03623c-365d-4248-b420-21b7dfc05d22.png">

不清楚， 直接在浏览器用 `<table>` 好像也不出来
```
<table border="1">
  <tr>
    <td>1-1</td>
    <td rowspan="3" class="b">1-2</td>
    <td rowspan="3" class="b">1-3</td>
  </tr>
  <tr>
    <td>2-1</td>
    <!-- <td>2-2</td> -->
    <!-- <td>2-3</td> -->
  </tr>
  <tr>
    <td rowspan="2" class="a">3-1</td>
    <!-- <td>3-2</td> -->
    <!-- <td>3-3</td> -->
  </tr>
  <tr>
    <!-- <td>4-1</td> -->
    <td>4-2</td>
    <td>4-3</td>
  </tr>
</table>
```
![image](https://github.com/siyuan-note/siyuan/assets/90757590/b565b2e5-c336-4e6c-89a4-ae40e6f9cc00)

**Comment by Vanessa219** [comment]
嗯，那先这样吧，用点空行顶顶，后续有好的解决方案我们再改进。
