### ISSUE TITLE
展开标题 产生副本 

### ISSUE THREAD

**Issue by Yuki-J1** [siyuan-note/siyuan#9684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/41263770/19018be5-15ed-45b6-8a54-c901352eb3d0)
原来标题下内容只有红色框部分，但是展开标题后，会自动出现好多的副本。
字符数增大，卡顿。

### Expected result

标题展开后不产生副本

### Version environment

```markdown
- Version: v2.10.15
- Operating System: 
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13400016/siyuan.log)

### More information

https://drive.google.com/file/d/1rsNi_bWz7A9ihIdbQd7s0fAdOiFY8nT8/view?usp=sharing

**Comment by 88250** [comment]
和社区这个帖子是同一个问题吗？

https://ld246.com/article/1700306148133

**Comment by Yuki-J1** [comment]
> 和社区这个帖子有相同问题吗？
> 
> https://ld246.com/article/1700306148133

感谢D回复。
是的在滴链社区有开了个提问，所以这边issue就关闭了。
并且找到了暂时解决办法。
https://github.com/siyuan-note/siyuan/assets/41263770/41932a4c-3cdb-4646-813e-45cc813d9e7d
