### ISSUE TITLE
Improve image export when line breaks have background

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

in siyuan
![image](https://github.com/siyuan-note/siyuan/assets/60436214/2e5a3412-d374-4055-ae64-6ee47a87bd0a)
export to picture
![image](https://github.com/siyuan-note/siyuan/assets/60436214/417aed71-c24d-4ba7-b918-2fb9ca2330a5)

### Expected result

style in exported picture can be the same with that in siyuan

### Version environment

```markdown
- Version: 2.10.15
- Operating System: Win11
- Browser (if used):
```

### Log file

none

**Comment by Achuan-2** [comment]
@Vanessa219 是导出图片，不是导出pdf

**Comment by Achuan-2** [comment]
@Vanessa219 能否也加上链接呢，因为有些主题会给链接加下划线，导出图片也是有问题的
![image](https://github.com/siyuan-note/siyuan/assets/60436214/981507d1-062b-435c-8874-a3e5d4691a4e)

**Comment by Vanessa219** [comment]
这样任何元素都会有这个问题，建议在代码片段中重置 css 或者修改主题。

**Comment by Achuan-2** [comment]
> 这样任何元素都会有这个问题，建议在代码片段中重置 css 或者修改主题。

好滴

**Comment by Vanessa219** [comment]
@tcmtom 麻烦发一下 .sy 文件。这个仅修改了行内标记元素。
