### ISSUE TITLE
Baidu input method double quote completion compatible

### ISSUE THREAD

**Issue by grandsong** [siyuan-note/siyuan#9686]
【功能冲突】百度输入法下，双引号的光标位置错误

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

该问题已经被人提交了  #9651 。但结果 @88250  认为只是百度输入法本身的缺陷，所以不解决。
我补充一下情况：
同样是用百度输入法，按下`Shift+'`，得到一对**双引号**时，光标最终停在了**左引号的左边**。
但是，如果按下`'`，输入的是一对**单引号**，光标却**正确地停在了两个引号之间**！
所以我怀疑，还是**因为思源笔记做了什么，或者有什么特性**，导致了双引号特有这个问题。
我个人用百度输入法挺久了，在各种在线文档产品（基于HTML）中，都没有遇到双引号光标问题，而**只有思源笔记才有**。

### Expected result

恳请维护思源笔记的某位高人，认真地研究一下，以确认到底**是不是思源这边的原因**？
如果是，请修复。

拜托了！
由于一些原因，我只能使用百度输入法，而无法改用别的。所以这对我真的很重要！

### Version environment

```markdown
- Version: 2.10.11
- Operating System: windows 11
- Browser (if used):
```

### Log file

（以下是只截取了今天的部分）
I 2023/11/19 06:19:36 box.go:79: auto stat [trees=388, blocks=6495, dataSize=444 MB, assetsSize=273 MB]
I 2023/11/19 06:19:36 disk.go:33: disk usage [total=500 GB, used=344 GB, free=156 GB]
I 2023/11/19 06:21:28 broadcast.go:80: close broadcast session in channel [test] with status code 1001: 
I 2023/11/19 06:21:28 broadcast.go:80: close broadcast session in channel [test] with status code 1001: 
I 2023/11/19 06:21:28 broadcast.go:80: close broadcast session in channel [test] with status code 1001: 
I 2023/11/19 06:21:28 broadcast.go:80: close broadcast session in channel [test] with status code 1001: 
I 2023/11/19 07:36:19 index.go:133: rebuilt database for notebook [20210808180117-czj9bvb] in [0.07s], tree [count=64, size=1.2 MB]
I 2023/11/19 07:36:19 index.go:206: resolved refs [31] in [362ms]

**Comment by 88250** [comment]
@Vanessa219 有空的话看看能否兼容。
