### ISSUE TITLE
your tab open and  close stragtegy is wrong

### ISSUE THREAD

**Issue by Foundation-Maker** [siyuan-note/siyuan#9687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1. What is your tab page opening and closing strategy?
2. What is the reason for allowing tabs to be displayed outside the window?
3, 1, 2 strategy why not be consistent with Google Chrome? In general, I think your product design is not as good as that of large companies, but there will be exceptions, if you have a reason, can you tell us?

[issuse](https://github.com/siyuan-note/siyuan/issues/9675#issuecomment-1816057679)

### Expected result

1. A new tab appears at the end of the tab
2. When closed, it will be opened in order, not in browsing order

### Version environment

```markdown
- Version: All
- Operating System:  PC and Mac
- Browser (if used):
```

### Log file

no

**Comment by 88250** [comment]
SiYuan supports multiple windows and multiple tabs. After splitting the screen, multiple windows are formed. Each window can contain multiple tabs, so it is not exactly the same usage habit as a browser.

I will close this issue, thank you.
