### ISSUE TITLE
闪卡复习界面可以移除闪卡

### ISSUE THREAD

**Issue by Leberabit** [siyuan-note/siyuan#9689]
### In what scenarios do you need this feature?

如题，有时候闪卡已经无用了，需要删掉。
思源目前只能通过移除块的方式移除闪卡，但大部分时间需要保留原块。

### Describe the optimal solution

在左上角添加一个选项（即使需要在设置里开启也行）

**Comment by 88250** [comment]
在管理界面可以移除闪卡，复习界面不考虑加入管理功能了，感谢反馈。
