### ISSUE TITLE
缩放图片提供常用缩放百分比

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#969]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

* 大量图片需要缩放，一直来回滑动太累了，希望像typora一样，提供常用缩放百分比。
![image](https://user-images.githubusercontent.com/69628966/103875004-d16d7100-510c-11eb-9413-667ce8990c1c.png)
* typora的缩放格式如下，如果提供的百分比还不满足需要，可以自行修改，很方便。
![image](https://user-images.githubusercontent.com/69628966/103875418-5c4e6b80-510d-11eb-9e35-2febb25b7a26.png)

**Comment by yeshaopeng6688** [comment]
另外，siyuan的快捷键是加了alt + m么 = =
我在idea写代码，用的快捷键alt + m向下，siyuan就缩小界面了，有时还会新开一个siyuan。。

ps : D大，跪求 = =  。。第n次强烈安利，提供上下左右的快捷键把。。

**Comment by 88250** [comment]
你好，最小化到托盘注册了全局快捷键 alt m，后续会提供自定义该快捷键。

你说的上下左右快捷键是什么？

**Comment by yeshaopeng6688** [comment]
= =。。就是键盘上的方向键。
![image](https://user-images.githubusercontent.com/69628966/103889588-a2adc580-5121-11eb-8a62-920e34c55b21.png)

**Comment by 88250** [comment]
哦，这个太极客了，估计不会引入……等专家模式考虑吧。

**Comment by yeshaopeng6688** [comment]
哈哈，其实这个一点也不极客。求D大一定要考虑啊~
方向键这个功能，不是像加粗、高亮这一类属于 强调功能性的快捷键，它更多类似于**辅助**，使得**更自然的输出**。
比如标签、emoji、文字，通常输出这些之前，都需要先进行一步选择。
* 输出#，我要选择哪个常用的标签；
* 输出:以及前面的字符，我要选择准确的emoji；
* 修改时，我要选择在附件哪个位置，删除、添加文字。
之所以强调**方向键**不是功能性的快捷键，是因为我认为它**的键位设置要很自然**，自然到忘记了它的键位设置。否则像加粗ctrl + b，斜体ctrl + i，两个键位相差十万八千里，我都直接设置鼠标宏了。。所以，我个人的推荐是：
* left: alt + f
* right: alt + j
  *  `alt`相对`ctrl`，左手大拇指按`alt`比左手小拇指按`ctrl`更省力。所以选择alt + ...组合
  * 双手放键盘上，必定是 左手食指放在`f`，右手食指放在`j`定位，因为有突起，第一顺位。
* down: alt + m
  *  没有这样设置之前，idea经常需要移动右手按 down 来选方法，所以肌肉记忆，选择右手食指的第二顺位。
* up: alt + c
  * up的需要使用较少，对应down， 选择左手食指的第二顺位。

**Comment by 88250** [comment]
这些快捷键基本都已经被用了……

PS 试试 HHKB 键盘 :trollface:

**Comment by yeshaopeng6688** [comment]
提供方向键的设置就好，上面只是我个人的习惯。
键位设置那，肯定还是方向键自己默认的键位~ 所以不会键位冲突啦~😆😆😆

等手上的雷蛇退役了就去试试~~
