### ISSUE TITLE
是否考虑设计用户权限模块满足多人协作需求

### ISSUE THREAD

**Issue by toint-cn** [siyuan-note/siyuan#9691]
### In what scenarios do you need this feature?

目前个人维度，已全面基于思源笔记建设个人知识库。

但是团队模式下，无法很好的把思源给用起来，无法满足作为团队知识存储库。比如权限控制、多端同时写入等情况。

### Describe the optimal solution

无

**Comment by 88250** [comment]
你好，目前思源笔记主要是面向个人使用，所以暂时不考虑团队协作场景，感谢提议。
