### ISSUE TITLE
闪卡复习界面修改长文本（5w字）有较严重卡顿（3s）

### ISSUE THREAD

**Issue by Leberabit** [siyuan-note/siyuan#9692]
### In what scenarios do you need this feature?

如题

### Describe the optimal solution

如题

**Comment by Leberabit** [comment]
甚至滑动也会产生卡顿

**Comment by 88250** [comment]
在编辑器界面不卡吗？

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
