### ISSUE TITLE
What the hell is this a sorry attempt of copying Obsidian.md xDD

### ISSUE THREAD

**Issue by MalxWare47** [siyuan-note/siyuan#9693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Its COPYING OBSIDIAN but it will never be obsidian xD 

### Expected result

WHAT IS THIS OBSIDIAN 2.0😆

### Version environment

```markdown
- \
- Version: 2.0
```

### Log file

no

### More information

even your website screams obsidian xD inspiration is one thing but this is copy Nd paste (x

**Comment by 88250** [comment]
SiYuan is not a copy of Obsidian/Notion. If you understand it carefully, you will not see it this way, but if you insist on thinking so, we will not argue with it, thank you.

**Comment by Temacc0531** [comment]
SiYuan and Obsidian are arguably different except that they are both offline. If you had actually downloaded and used SiYuan, you wouldn't have said such a laughable thing.

**Comment by 88250** [comment]
Let's see what others think and keep it pinned for a week.

**Comment by edward-kyle** [comment]
If you think so, then you think so. However, issue is not the place for you to make statements in the fan circle. Nobody cares what you think.

**Comment by definitelynotrazu** [comment]
If SiYuan is copying Obsidian then Obsidian is copying notepad :skull:

**Comment by andyer1511** [comment]
It only proves that you know neither Siyuan nor obsidian.

**Comment by netdog2019** [comment]
It only proves that you know neither Siyuan nor obsidian.

**Comment by zuoez02** [comment]
useless issue, should close

**Comment by litcu** [comment]
Yes, you are right. SiYuan copied Obsidian's unsatisfactory editor, incomplete core functionality, and slow update speed. Are you satisfied now?

**Comment by gaoluji** [comment]
You're right, but Genshin is a...
