### ISSUE TITLE
Please 块引用面包屑显示不全

### ISSUE THREAD

**Issue by leommjj** [siyuan-note/siyuan#9697]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/101880110/fb16c28e-995e-4427-85a0-7e8ea5e86e01)

### Describe the optimal solution

建议内容多的时候可以换行显示；或者省略一部分文字，但是层级结构显示完整！

**Comment by 88250** [comment]
你好这个长度主要是界面代码缩略的，如果需要调整，请尝试通过自定义主题或者 CSS 代码片段解决，谢谢。
