### ISSUE TITLE
Supports configuring data sync index time-consuming prompts

### ISSUE THREAD

**Issue by UltramarineSky** [siyuan-note/siyuan#9698]
允许关闭启动时的清理数据仓库提示

### In what scenarios do you need this feature?

之前已经在设置-关于那里清理过数据仓库了，可能是因为数据量比较大或者电脑性能原因，每次启动还是会弹窗提示清理数据仓库，去按提示清理也就几kb，希望可以设置关闭清理数据仓库提示，或者允许自定义超时时间

### Describe the optimal solution

希望可以设置关闭清理数据仓库提示，或者允许自定义超时时间

**Comment by 88250** [comment]
移动端上正常吗？

**Comment by 88250** [comment]
另外，麻烦上传一下日志。

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/9613

**Comment by 88250** [comment]
下个版本可通过如下两种方式配置：

* 环境变量 `SIYUAN_SYNC_INDEX_TIMING`，例如 `SIYUAN_SYNC_INDEX_TIMING=30000`，单位是毫秒
* 直接修改 conf.json `repo.syncIndexTiming`

启动时会优先读取环境变量覆盖 conf。

**Comment by UltramarineSky** [comment]
> 另外，麻烦上传一下日志。

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13415604/system-log.zip)
抱歉，才看到

**Comment by 88250** [comment]
没事，稍后看，多谢。
