### ISSUE TITLE
关系图无法关联

### ISSUE THREAD

**Issue by zhl111** [siyuan-note/siyuan#97]
这块我弄了半天没弄明白，块和链接并没有通过引用发生关系呢？
![test1](https://user-images.githubusercontent.com/29135984/94335263-e9f9c580-000c-11eb-8682-db0b392454a0.gif)

**Comment by zhl111** [comment]
我将所有凯恩斯指向一个文档中的凯恩斯，关系图如下，并未发生全部关联
![image](https://user-images.githubusercontent.com/29135984/94335556-00a11c00-000f-11eb-9a4e-0b1bc5dd938e.png)

**Comment by 88250** [comment]
重启一次看看，如果正常的话那就是 https://github.com/siyuan-note/siyuan/issues/89 这个问题，会在 v0.2.3 中修复。如果重启后还是没有在图上反应出关联关系，那应该是其他问题，请帮忙找一下重现步骤，谢谢。

**Comment by zhl111** [comment]
![test2](https://user-images.githubusercontent.com/29135984/94336209-de5dcd00-0013-11eb-8529-4b677f2fb9d0.gif)
重启了，还是有未关联的。
另外有个疑惑：ob里会根据凯恩斯形成一个以它为中心的关系图，而思源我不知道这么多个凯恩斯我该关联谁，第一个建立的？还是像现在我设置的只关联一个？但它们并没有逻辑关系，只是相关关系，我该引用谁才好？于是我单独新建了页面起名凯恩斯，但发现不能关联文档名，在文档里输入凯恩斯后才能发生关联，但目前的情况又不能全部关联，有点晕。

**Comment by 88250** [comment]
思源笔记里是通过 id 进行关联的，如果引用了同样的块 id，那引用点就会关联到同一个块上。

**Comment by zhl111** [comment]
问题是我引用的都是一个id，但并没有全部发生关联啊

**Comment by 88250** [comment]
你好，请等 v0.2.3 发布以后再试试看，谢谢。

**Comment by 88250** [comment]
@zhl111 你好，v0.2.3 已经发布，请更新到新版本帮忙测试，谢谢！

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/94357990-2a6e4780-00d0-11eb-8844-bb6f59962f5f.png)
引用的关联大致可以了。几个不关联的点代表的是整篇文档，在关系图中的作用是什么？似乎只能单独存在，若要存在的话可否显示文档名字？

**Comment by 88250** [comment]
嗯，关系图这块目前还是有点乱……我们计划有两个改进：

* 单独提供文档块/标题块级的关系图，类似 ob 的呈现 https://github.com/siyuan-note/siyuan/issues/62
* 在现有关系图上默认加上文档块/标题块的文本 https://github.com/siyuan-note/siyuan/issues/68

**Comment by 88250** [comment]
这个我先关闭了，谢谢反馈和讨论。
