### ISSUE TITLE
希望提供文档内嵌PDF的功能

### ISSUE THREAD

**Issue by muhanstudio** [siyuan-note/siyuan#9704]
### In what scenarios do you need this feature?

我观察到思源支持渲染PDF在新页签，但是很多时候我们需要将PDF嵌入显示在文档里面，就像插入一个图片一样，通过与群友交流，目前想在文档内嵌PDF的方式只有两种，一种是自己插入一个html块，将PDF的src放入ifame里面，调用浏览器渲染，一种是通过配置js解析器，通过“/”调用快捷指令插入解析后的ifame链接，这两种嵌入方式首先不够便捷，且无法索引本地的PDF文件，只能手动先获取想插入的文件链接，再进行html代码的编写，再者，直接将普通用户内嵌PDF的门槛拉到很高，很多用户甚至不知道文档可以内嵌PDF，只能通过点击链接新打开一个PDF窗口进行查看

### Describe the optimal solution

希望在快捷指令里面加入“嵌入PDF文件”选项，可以直接选择本地PDF进行嵌入

**Comment by 88250** [comment]
你好，这个场景目前需求并不多，另外就像你说的，目前已经有替代方案了，所以暂时不考虑单独进行支持了，感谢提议。

**Comment by mozhux** [comment]
其实还是挺有需求的，替代方案无法解决手机上的查看问题。添加也不方便，希望能支持。引申出来就是，希望插入的PDF链接，旁边有个按钮可以按嵌入显示或链接显示。

**Comment by 88250** [comment]
PDF 超链接或者注解引用是行级元素，嵌入不了。手机上显示 PDF 估计还得先考虑已有的 PDF 页签实现。

**Comment by mozhux** [comment]
> PDF 超链接或者注解引用是行级元素，嵌入不了。手机上显示 PDF 估计还得先考虑已有的 PDF 页签实现。

可能理解错意思了，其实只是要手机上查看PDF，目前是点击下载用第三方打开，但pdf.js本身是有嵌入功能的，只需要能在手机上实现嵌入显示这个PDF就行。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/0ec48b96-54b6-41b7-93ba-67d95e871aae)

**Comment by 88250** [comment]
嗯，这个需求是比较多的，迟早需要支持。

**Comment by TCOTC** [comment]
用户需求：

![Screenshot_2024-09-04-11-26-14-82_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/user-attachments/assets/a4d8b088-13d9-406b-8350-0ea3874d9cc7)

**Comment by Chenm4** [comment]
这个需求我觉得挺好的，pdf，思维导图，都可以放在文档目录中。不过文档的图片我不建议直接显示在里面，因为我担心误删，obsidian把图片文件夹也显示在里面了我感觉不是很好。

**Comment by 88250** [comment]
楼主的插件已经支持了 https://github.com/muhanstudio/siyuan-plugin-embedding-pdf 

原生支持就暂时不考虑了，谢谢。

**Comment by TCOTC** [comment]
用户需求：

- https://ld246.com/article/1735516665750 第4点
