### ISSUE TITLE
Ability to run the Docker container as a defined user instead of ‘siyuan’

### ISSUE THREAD

**Issue by Tim040** [siyuan-note/siyuan#9707]
### In what scenarios do you need this feature?

In my current setup I would prefer to not have an extra user to grant access to folders.

Having the ability to run the container from a custom defined PUID / PGID would be great to prevent this.

### Describe the optimal solution

Use the environment options to set a PGID / PUID that is used to run the container

**Comment by 88250** [comment]
Hello, this is a good suggestion, but we don’t have time to study the implementation resolution at the moment. If you have a mature resolution, you are welcome to PR, thank you.

**Comment by 88250** [comment]
Fixed in https://github.com/siyuan-note/siyuan/pull/12596
