### ISSUE TITLE
建议保存搜索的排序和分组设置

### ISSUE THREAD

**Issue by qxj** [siyuan-note/siyuan#9711]
### In what scenarios do you need this feature?

打开搜索后，只有“布局”设置选择完能够保存，而“排序”和“分组”设置用户选择完之后（比如选择“按文档分组”），下次打开还是恢复原状（默认是“不分组”），不太符合预期。

<img width="283" alt="image" src="https://github.com/siyuan-note/siyuan/assets/225400/fac3f5fe-a1f5-49c5-83b4-6ad434d3f7a8">

### Describe the optimal solution

建议“排序”和“分组”用户设置完之后也能保存。

**Comment by Vanessa219** [comment]
排序和分组属于查询条件，布局属于外观显示。

需要保持排序和分组的话可以点击保存查询条件，后续再打开就可以进行保存了。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
