### ISSUE TITLE
优化未找到块的处理逻辑

### ISSUE THREAD

**Issue by woniuxia** [siyuan-note/siyuan#9712]
### In what scenarios do you need this feature?

![02c6539b7a3b0d20ff01decc77f1fdc2](https://github.com/siyuan-note/siyuan/assets/16383685/839ab2f6-ab45-4ba2-9588-869782f88a9a)
提示未找到块，当前的解决方案好像只有重建索引，不过重建索引这个功能，很多人都不太知道，如果出现了这个错误，希望给以足够的提升，让用户能够自行重建索引。

### Describe the optimal solution

提升重建索引可以解决问题，并说明重建索引功能的位置。

**Comment by 88250** [comment]
感谢反馈，但是这个不一定是索引的问题，有可能是用户确实删除了块，程序无法判断，所以也就无法给出具体解决提升。

**Comment by woniuxia** [comment]
那给一些处理建议如何呢？
在用户指南中说明，然后再提示中可以点击直接跳转过去

**Comment by 88250** [comment]
没有有效建议可以给，暂时先这样吧。
