### ISSUE TITLE
 v2.10.16 数据库  `数字` 字段，无法写入内容,见下面动图

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/siyuan#9713]
![数据库数字字段无法正确存储](https://github.com/siyuan-note/insider/assets/53116704/32b2ea0d-add0-49e7-b09e-81e083df192d)

**Comment by 88250** [comment]
感谢反馈，在 70b3406e03e95689f35874eb7f06f44f5e010d8a 中修复。
