### ISSUE TITLE
Unable to "Quit the application" when no document is opened on mobile

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9717]
Hello all, I think I found a new bug which is related to this post.  
Here is details: https://ld246.com/article/1700581893083  
Could be this one or https://github.com/siyuan-note/siyuan/issues/9680, and I'm still researching it.

_Originally posted by @zxkmm in https://github.com/siyuan-note/siyuan/issues/9678#issuecomment-1821240254_

**Comment by zxkmm** [comment]
好像同样的问题也发生在点击搜索中的结果时候，不管是不输入内容还是输入内容搜索

**Comment by Vanessa219** [comment]
是这样操作么？

https://github.com/siyuan-note/siyuan/assets/970828/0319a5b8-929e-4017-b0ac-a526ba776deb

**Comment by zxkmm** [comment]
是的。这个只发生在没有文档打开的时候与启用启东市关闭所有页签的时候。平常是正常的。

**Comment by Vanessa219** [comment]
没太明白

1. 不是说搜索后也无法关闭么
2. 移动端没有关闭所有页签

没有 get 到你说的问题。

**Comment by zxkmm** [comment]
> 不是说搜索后也无法关闭么   

抱歉，是我没有描述清楚。问题是“当没有打开编辑器时，搜索里面的条目点不动”(和这个issue近似） 而不是“当点击过搜索条目以后，app不能安全退出”。   

> 移动端没有关闭所有页签  

移动端有这个功能的。需要在伺服网页版启用开关后就能用了。我从下载思源开始就在用这个功能了。

**Comment by zxkmm** [comment]
https://github.com/siyuan-note/siyuan/assets/24917424/19f11cf4-2c34-48d8-ae8d-a4c07313de93

**Comment by Vanessa219** [comment]
哦，明白了，下个版本继续修复。谢谢。

**Comment by zxkmm** [comment]
谢谢，那我把录屏删除了🙏
