### ISSUE TITLE
ipad同步失败

### ISSUE THREAD

**Issue by primejava** [siyuan-note/siyuan#9721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

ipad同步失败，两台电脑互相同步正常，ipad能下载下来大部份的文件，但是一直会报如下错误，有几个十几m的pdf文件均未成功下载
![image](https://github.com/siyuan-note/siyuan/assets/10646824/521e4424-4531-46d4-954e-c825c657a1e9)

### Expected result

希望可以正常同步

### Version environment

```markdown
- Version: 2.10.15
- Operating System: ipad
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13440083/system-log.zip)

**Comment by 88250** [comment]
从日志上看是下载分块超时了，iOS 系统上需要保持亮屏并且不能切换应用，否则思源会被休眠导致无法下载数据。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by primejava** [comment]
> 从日志上看是下载分块超时了，iOS 系统上需要保持亮屏并且不能切换应用，否则思源会被休眠导致无法下载数据。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

你好，我在同步过程中一直保持亮屏并进行观察，没有切换应用，在应用的左下角提示签出数据仓库即将完成的时候报出的以上错误。在最新版的2.10.16上也存在这个问题

**Comment by 88250** [comment]
可以看一下是不是服务端的问题，日志上报错是请求超时。
