### ISSUE TITLE
设置界面出现许多undefined

### ISSUE THREAD

**Issue by w91** [siyuan-note/siyuan#973]
### 描述问题 Describe the problem
从0.4.5升级到0.5.7设置界面出现undefined
看起来原因就是升级后~/.siyuan下面的配置文件没有被更新导致，我直接复制0.5.7安装包里的zh_CN.json内容替换.siyuan目录里的就正常了。
这一块更新检查的逻辑可能需要修改下

PS: 什么时候支持下自动更新。。。

### 截屏或录屏演示 Screenshot or screen recording presentation
![image](https://user-images.githubusercontent.com/2599455/103880089-a1759c00-5113-11eb-916f-b709a2a55b74.png)

### 版本环境 Version environment

* 版本 Version：0.5.7
* 操作系统 Operating system：chrome 10.14.6

**Comment by 88250** [comment]
代码应该没有问题亲，可能还是卸载重新安装的问题，我关闭了，谢谢。
