### ISSUE TITLE
the pre-space of inline code left in previous line (break into 2 lines)

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

see the image

### Expected result

they should be at same line

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/31495943/c4a867ef-061c-45b5-968c-115ebe2a32d8)

### Version environment

```markdown
- Version: 2.10.16
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
Sorry, there is still no way to solve this problem, we have tried it before https://github.com/siyuan-note/siyuan/issues/8104
