### ISSUE TITLE
[FR] database support tag, name, alias, memo?

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9733]
### In what scenarios do you need this feature?

there already have tag for a document, when it is add to a database, still need to add the tags again.
it is neither convinient nor consistency.

### Describe the optimal solution

is it possible to add these info. into database by template column?

**Comment by 88250** [comment]
Tags cannot be rendered via template columns. Name, aliases and memos are block-level attributes that can be rendered through template columns, please refer to https://github.com/siyuan-note/siyuan/issues/9401

**Comment by XinLi0111** [comment]
Thanks for your quickly reply.  

The name, alias have already showed aside the block, so why the tag can not do the same, so that it can be add to the database.

The possible reason maybe the tag need input directly in blocks.

But the tag is marked with "#", do you consider to parse tags into block attributes? and sync between inline tag and atrribute tag.
* `#tag#`  ➔ tag
* `#n:name#` ➔ name
* `#a:alias1,alias2#` ➔ alias1,alias2 (pop confirm windows if exists alias)
* `#m:memo#` ➔ memo
* `#status:doing#` ➔ custom-status: doing

Or, parsed tags only the first time, then the tag acts like other attributes (click to show the attribute panel for edit).
In the panel, you can also provide a pop window to show the tag list for adding new tag.

**Comment by 88250** [comment]
There are no block-level tags in the design because block-level tags are actually custom attributes.

**Comment by XinLi0111** [comment]
> There are no block-level tags in the design because block-level tags are actually custom attributes.

Sorry for my stupid, does this tag "custom attributes" with same name but different with current known custom atrributes like "custom-*"?

Is there some technical considerations to keep them separated alone?

**Comment by 88250** [comment]
What I am referring to is `custom-*`, its function is to set different attributes for each block, and the attributes include the function of the tag.

Inline tag elements and block-level attributes exist independently and have different functions.

**Comment by XinLi0111** [comment]
Thank you, I have understood it.
