### ISSUE TITLE
block icon of database row is showed out of boundary when editor width  narrow

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/31495943/ba5c8b91-abf3-4d74-bfa8-ebd6ed6bb7df)

### Expected result

-

### Version environment

```markdown
- Version: 2.10.16
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by Vanessa219** [comment]
这个行距离比较近，弄成两行好像很违和，比较难确认到底是哪一行。目前没有找到好的解决办法，只能先这样了。
<img width="346" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/b0f843f6-b19d-4172-87fb-5ca348cade78">

**Comment by XinLi0111** [comment]
确实。而且也不太影响使用。
弄个边框装起来呢，是不是有点丑

**Comment by Vanessa219** [comment]
估计也不好看
