### ISSUE TITLE
Abnormal behavior after customizing the shortcut key for inserting a code block on Windows

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#9735]
自定义插入代码块快捷键后行为异常

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

C-d 原本是重复的快捷键，把他去掉
把C-d设置到插入代码块上

比如如下的三行文本
```
aaaaaa
bbbbbb

cccccc
```
会有以下的异常情况（就是最近几个版本才有的，以前用着很正常）
1 把光标放到aaaaaa的末尾，按C-d，bbbbbb会退格到第一行去变成这样
```
aaaaaabbbbbb

cccccc
```
2 在第三行空白按C-d 的话，cccccc会跑到第三行变成如下这样
```
aaaaaa
bbbbbb
cccccc
```

只有在后面没有任何文本的情况下按C-d才会插入一个代码块。不过奇怪的是，我用原生快捷键，或者设置一个其他的快捷键，比如alt-d，也没有这个问题

### Expected result

1 当前行有内容的时候，按 C-d 创建代码块，插入当前行的内容
2 当前行是空行的时候，按 C-d 创建代码块到当前行

### Version environment

```markdown
- Version: 2.10.16
- Operating System: windows 11
- Browser (if used):
```

### Log file

应该不用log

**Comment by Vanessa219** [comment]
是这样操作么？

https://github.com/siyuan-note/siyuan/assets/970828/7956246d-06a8-4ab1-ba71-bb08f5011bea

**Comment by heheda123123** [comment]
https://github.com/siyuan-note/siyuan/assets/97490782/5b59321c-dc9d-41fe-909f-658ad2a3af9d

**Comment by heheda123123** [comment]
我是用的windows，不知道其他平台有这个问题没

**Comment by 88250** [comment]
我这里 Windows 可以重现了，感谢反馈。
