### ISSUE TITLE
Add plugin method `openMobileFileById`

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9738]
### In what scenarios do you need this feature?

近期更新后， createdDailyNote API 的实现发生了变化。

https://github.com/siyuan-note/siyuan/blob/fad7f0512cee8525a1be805cd87900046346cad2/app/src/util/mount.ts#L13

![image](https://github.com/siyuan-note/siyuan/assets/27268127/b10486f3-ca58-4e5c-a13a-effe800a6515)

 openMobileFile 方法没有对外开放，导致无法通过插件在移动端打开文档。https://github.com/frostime/siyuan-dailynote-today/issues/179

### Describe the optimal solution

新的API，可以在移动端打开指定 id 的文档。

**Comment by Vanessa219** [comment]
fetchNewDailyNote, openMobileFileById, openFileById 这几个都没开放

**Comment by frostime** [comment]
> fetchNewDailyNote, openMobileFileById, openFileById 这几个都没开放

这几个是没开放，我是自己实现，通过访问后端 createDailyNote 然后调用 openTab 打开对应的日记。

但是在移动端目前缺少一个打开文档的 API，在 createDailyNote API 的行为改变之后，无法通过程序在移动端打开文档了。

**Comment by Vanessa219** [comment]
`openMobileFileById`
