### ISSUE TITLE
Preserve links when exporting to Markdown

### ISSUE THREAD

**Issue by definitelynotrazu** [siyuan-note/siyuan#9743]
### In what scenarios do you need this feature?

When exporting notes to Markdown, the links between notes are not preserved / converted to Markdown links. While I understand block links aren't supported in common Markdown and therefore not all links can be converted, I think it would be very valuable to be able to have at least note links, e.g. [MyProjectNote](projects/projectnote.md) when exporting notes that have links to other notes. 

This would be very useful for sharing notes with people who use other software, such as Obsidian, Logseq, Neovim, Helix, etc. And would increase interoperability in team scenarios. 

### Describe the optimal solution

When exporting a note that has a link, e.g. exporting Note_A in "Projects" which has a link to Note_B in "Projects", have the link be included in the exported file, so that the exported file will have [Note_A](Projects/Note_B.md)

**Comment by 88250** [comment]
Sorry, converting references to relative paths to Markdown files is not supported.

Some of the existing reference export modes can be seen in Settings - Export:

![image](https://github.com/siyuan-note/siyuan/assets/873584/e1e41aa0-79d4-431c-b055-720bb1339362)
