### ISSUE TITLE
Flathub安装的思源笔记：获取内核服务端口失败 Failed to get kernel serve port

### ISSUE THREAD

**Issue by Wenjungang** [siyuan-note/siyuan#9747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Flathub安装的思源笔记
获取内核服务端口失败 Failed to get kernel serve port
获取内核服务端口失败，请确保程序拥有网络权限并不受防火墙和杀毒软件阻止。
Failed to get kernel serve port, please make sure the program has network permissions and is not blocked by firewalls and antivirus software.

### Expected result

正常使用 

### Screenshot or screen recording presentation

![图片](https://github.com/siyuan-note/siyuan/assets/40133855/3b596315-7ab1-41dc-a910-805d1790527c)

### Version environment

```markdown
- Version: 2.10.16
- Operating System:Debian12.2 
- Browser (if used):
```

### Log file

E 2023/11/26 20:41:06 working.go:420: lock workspace [/run/user/1000/doc/a8261891/siyuannote] failed: function not implemented
E 2023/11/26 20:41:36 working.go:420: lock workspace [/run/user/1000/doc/a8261891/siyuannote] failed: function not implemented

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13466779/siyuan.log)

**Comment by 88250** [comment]
你好，使用 appimage 或者 tar.gz 的版本可以正常启动吗？

**Comment by Wenjungang** [comment]
appimage没问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月26日(星期天) 晚上8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [siyuan-note/siyuan] Flathub安装的思源笔记：获取内核服务端口失败 Failed to get kernel serve port (Issue #9747)





 
你好，使用 appimage 或者 tar.gz 的版本可以正常启动吗？

**Comment by 88250** [comment]
使用 appimage 的时候工作空间路径也是 `/run/user/1000/doc/a8261891/siyuannote` 这个吗？因为从报错信息来看可能是文件系统格式不支持：

`E 2023/11/26 20:41:36 working.go:420: lock workspace [/run/user/1000/doc/a8261891/siyuannote] failed: function not implemented`

**Comment by 88250** [comment]
我先关闭了，如果还有信息补充请继续跟帖，谢谢 :pray:

**Comment by adhamsalama** [comment]
The same issue happened to me.
I was using SiYuan normally a couple of days ago, now I got the same error.

**Comment by adhamsalama** [comment]
@Wenjungang Okay I tried it with Flatpak and the issue is that I didn't give it user files access, so I enabled it using Flatseal and now it's working.

**Comment by Wenjungang** [comment]
Thank you!



---原始邮件---
发件人: "Adham ***@***.***&gt;
发送时间: 2023年12月1日(周五) 中午1:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] Flathub安装的思源笔记：获取内核服务端口失败 Failed to get kernel serve port (Issue #9747)




 
@Wenjungang Okay I tried it with Flatpak and the issue is that I didn't give it user files access, so I enabled it using Flatseal and now it's working.
