### ISSUE TITLE
Database "Number" type doesn't save

### ISSUE THREAD

**Issue by monsterfurby** [siyuan-note/siyuan#9749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

When entering values into a database column of the type "Number", the number can be typed in normally, but after confirming via Return, the cell remains empty. This also occurs with the up/down selector: while being selected, a number appears, but the value is not saved.

This occurs to me regardless of plugins, theme, and operating system (tested on both Win10 and macOS).

### Expected result

Valid numbers (integers) should remain in the cell after commit.

### Screenshot or screen recording presentation

![errorgif_number](https://github.com/siyuan-note/siyuan/assets/26794051/9a42916e-328e-42d2-8c27-537001f8a35e)

### Version environment

```markdown
- Version: 2.10.16
- Operating System: Windows 10 / macOS Sonoma
- Browser (if used): -
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13467408/siyuan.log)

**Comment by 88250** [comment]
Hello, thanks for the feedback, this bug will be fixed in the next version (v2.11.0).
