### ISSUE TITLE
引用链接超过 7 个显示异常

### ISSUE THREAD

**Issue by GlowBlur** [siyuan-note/siyuan#975]
### 描述问题 Describe the problem
升级到最新版本0.5.7版本后文档部分引用链接名称显示异常

### 截屏或录屏演示 Screenshot or screen recording presentation

![屏幕截图 2021-01-07 194457](https://user-images.githubusercontent.com/42575324/103889386-49de2d00-5121-11eb-9d4b-38e692830952.png)‘
![屏幕截图 2021-01-07 201045](https://user-images.githubusercontent.com/42575324/103891305-937c4700-5124-11eb-8478-6c11c316f0c3.png)
![屏幕截图 2021-01-07 201110](https://user-images.githubusercontent.com/42575324/103891322-970fce00-5124-11eb-9911-5e3085b80952.png)

经过反复测试，页面引用超过7个块就会出异常问题
![屏幕截图 2021-01-07 210703](https://user-images.githubusercontent.com/42575324/103896172-87948300-512c-11eb-92d5-757b8bcd8128.png)

### 版本环境 Version environment

* 版本 Version：0.5.7
* 操作系统 Operating system：Windows 10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/07 19:46:10 main.go:121: kernel [v0.5.7] is booting, runtime mode is [prod], working directory is [C:\Users\zhenghui\AppData\Local\Programs\SiYuan\resources], temp directory is [C:\Users\zhenghui\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/07 19:46:10 lang.go:67: initialized languages
D 2021/01/07 19:46:10 conf.go:89: loaded conf [C:\Users\zhenghui\.siyuan\conf.json]
I 2021/01/07 19:46:10 conf.go:176: local serve path [http://192.168.1.104:6806]
I 2021/01/07 19:46:10 conf.go:180: initialized conf
I 2021/01/07 19:46:10 main.go:162: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/07 19:46:10 webdav.go:37: initialized WebDAV server
I 2021/01/07 19:46:10 box.go:363: indexing [96] trees, cpus [16]
W 2021/01/07 19:46:10 tpl.go:173: parse ref text template failed: template: :1: unexpected bad character U+2014 '—' in command
W 2021/01/07 19:46:10 tpl.go:173: parse ref text template failed: template: :1: unexpected bad character U+2014 '—' in command
D 2021/01/07 19:46:11 box.go:398: indexed box [http://127.0.0.1:6806/siyuan/siyuan/Knowledge/]
I 2021/01/07 19:46:11 conf.go:297: initialized box
I 2021/01/07 19:46:11 repo.go:39: initialized git repo

**Comment by 88250** [comment]
你好，请展开节点看下 id 是否和定义块 id 相等。

**Comment by GlowBlur** [comment]
ID不同，而且可以显示被引用页面，但是就是不显示对应的文本

**Comment by 88250** [comment]
如果原始 .md 中出现了 `undefined))` 麻烦用其他编辑器批量替换，替换前先关闭思源，如果 kernel 进程没有退出手动 kill，然后重装一次，辛苦了。

**Comment by GlowBlur** [comment]
@88250 好的，我VS Code处理掉
W 2021/01/07 19:46:10 tpl.go:173: parse ref text template failed: template: :1: unexpected bad character U+2014 '—' in command
这个错误后续是否Fix掉

**Comment by 88250** [comment]
`—`  这个字符我这里放在锚文本里没有报错，定位不到问题。

**Comment by GlowBlur** [comment]
@88250 经过反复测试，所有标题引用块都有以上问题，但是文档引用没有问题，我看那个-是不是因为我有2021-01-01这样的文档名？

**Comment by GlowBlur** [comment]
@88250 我先回退到0.5.6一切正常
![Uploading 屏幕截图 2021-01-07 204741.png…]()

**Comment by 88250** [comment]
麻烦用默认主题试下是否有问题。

**Comment by 88250** [comment]
我这里在列表里引用标题重现不了……

![issue](https://user-images.githubusercontent.com/873584/103895029-b6115e80-512a-11eb-936e-63f84c023785.gif)

**Comment by GlowBlur** [comment]
@88250 老大我测试出来了，只要本页引用超过7个就会出错

**Comment by 88250** [comment]
@GlowBlur 感谢老铁花时间帮忙定位问题，我大概知道哪里有问题了，之前有个控制递归深度的计数变量用在广度上了……

**Comment by GlowBlur** [comment]
@88250 没事儿，我也是搞开发的，我懂

**Comment by 88250** [comment]
这问题 v0.5.8 没有修复，v0.5.9 继续解决。

**Comment by lowwor** [comment]
0.6.0 这个问题仍然存在

**Comment by lowwor** [comment]
重启以后好了。
