### ISSUE TITLE
[feature request] make setting window dragable

### ISSUE THREAD

**Issue by realysy** [siyuan-note/siyuan#9752]
### In what scenarios do you need this feature?

Currently the setting window is just above the center of the software, but when I need to make some changes of the setting according to my note document, it is good to have a draggable setting window so that I can drag it aside not covering note document.

### Describe the optimal solution

Make the setting window draggable. A better improvement is to make the setting window seperate from the main window - user can focus on the main window even after the setting window has been opened.

### Other information

version: 2.10.16
win10

**Comment by Vanessa219** [comment]
Currently, the size and position can be adjusted by dragging the four corners.

The dragging of the entire panel can only be added to the red box position in the picture below.

<img width="813" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/c5a55497-5ea8-4a80-b65c-7d3347ac06c1">

**Comment by realysy** [comment]
Great, add to the red box region is intuitive. 

If the main window of Siyuan notes is not maximized, is it possible to drag the setting panel out of the border of main window (in the future)? 

![图片](https://github.com/siyuan-note/siyuan/assets/55436543/6747ecb5-3928-4dc8-986f-b86348fe0139)

**Comment by Vanessa219** [comment]
We will consider it in the future after all important issues have been done. Thank you for your suggestion.
