### ISSUE TITLE
SiYuan WeChat assistant convert amr to mp3

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9753]
https://ld246.com/article/1701005184099

**Comment by pisceswb** [comment]
👍

**Comment by pisceswb** [comment]
请问D大能否给收集箱增加右键菜单，图片上点击右键时，允许复制图片地址，允许复制图片png；语音上点击右键时，允许使用本地播放器播放或直接点击就使用本地播放器播放

**Comment by 88250** [comment]
@pisceswb 图片的话应该可以做复制 PNG，但是语音文件不行，我们先转成 wav 看看，转了以后应该可以使用浏览器直接播放。

**Comment by pisceswb** [comment]
> @pisceswb 图片的话应该可以做复制 PNG，但是语音文件不行，我们先转成 wav 看看，转了以后应该可以使用浏览器直接播放。

收到，谢谢D大！

**Comment by 88250** [comment]
wav 太大了，转 mp3 吧，[mp3 的专利过期](https://zh.wikipedia.org/wiki/MP3#%E5%B0%88%E5%88%A9%E9%81%8E%E6%9C%9F)了。
