### ISSUE TITLE
Add some `Protyle` methods to the plugin API

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9762]
* turnIntoOneTransaction
* turnIntoTransaction
* updateTransaction
* updateBatchTransaction
* getRange
* hasClosestBlock
* focusBlock

_Originally posted by @Vanessa219 in https://github.com/siyuan-note/petal/issues/21#issuecomment-1829400779_

**Comment by suka233** [comment]
v姐，`turnIntoOneTransaction`可以改为静态方法调用吗？目前好像必须要正确实例化Protyle后才能调用，但是我想要直接`Protyle.turnIntoOneTransaction()`这样调用。这样会更灵活一点
@Vanessa219

**Comment by Vanessa219** [comment]
转换时会产生历史提供给编辑器撤销使用，目前无法移除编辑器实例。
