### ISSUE TITLE
希望移除锁屏页的授权码提示，并实现授权码加密存储在本地

### ISSUE THREAD

**Issue by primejava** [siyuan-note/siyuan#9763]
### In what scenarios do you need this feature?

需要防止别人在我不知情的情况下浏览我的笔记内容。完全无法理解目前锁屏页为什么会设计成这样，好比是锁上大门后还找个醒目的位置把钥匙挂上

### Describe the optimal solution

直接移除锁屏页的授权码提示，并实现授权码加密存储在本地。

**Comment by 88250** [comment]
请参考 https://github.com/siyuan-note/siyuan/issues/6892
