### ISSUE TITLE
Flatpak issues on Wayland

### ISSUE THREAD

**Issue by solariz** [siyuan-note/siyuan#9764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

If I run SiYuan as Appimage it works fine. But if I use the Flathub version I cannot use it. The App starts but all click coordinates of the mouse are off. So the scaling is broken. For Example; If I want to click on a button the actually click region of it is shifted by 10-30% to top left. Makes the whole app unusable.

In Browser Version works fine, so currently running the siyuan as 127.0.0.1 server and using it in browser fully but cant use electron UI.

### Expected result

Working in Flatpak either using xwayland or wayland native.

### Version environment

```markdown
- Version: 2.10
- Operating System: Linux 6.6, KDE wayland 


OS: Nobara Linux 38 (KDE Plasma) x86_64
Kernel: 6.6.2-201.fsync.fc38.x86_64
DE: Plasma 5.27.9 [wayland]
Resolution: 2560x1440  150% scaling
Flatpak 1.15.4
```
```


### Log file

https://pastebin.com/mrP0y1XV

### More information

_No response_

**Comment by 88250** [comment]
Sorry, we are currently unable to locate this problem. Please try adjusting the system screen zoom to a normal ratio to see if it is normal.

If it still doesn't work, you can only use the Appimage version for now, sorry.
