### ISSUE TITLE
Improve Android soft keyboard hiding compatibility

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9765]
最新版移动端键盘关闭后快捷栏仍然显示（百度输入法）

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

1、点击
![5dc6bd78c52ce7d5669a0e62e8403a8](https://github.com/siyuan-note/siyuan/assets/67137548/b0a2a1c5-69f6-4d13-a73f-8f19395d1f1a)

2、
![59cf3e139cb2056ca571fa9213e2c72](https://github.com/siyuan-note/siyuan/assets/67137548/50546b39-6fae-49ea-bdb8-e87caeaa7c57)

3、如果点击快捷栏自带关闭按钮

快捷栏会同键盘一同关闭，但是再次唤醒键盘时，有概率出现：

![c84dbb735cdd370fe735b9006ac02b1](https://github.com/siyuan-note/siyuan/assets/67137548/707e284c-4dcc-4cc2-bd15-8eb3f3f4cdf2)

### Expected result

无

### Version environment

```markdown
- Version: 最新（上版本不这样）
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
感谢反馈，是因为解决 https://github.com/siyuan-note/siyuan/issues/9726 这个的时候引入的 @Zuoqiu-Yingyi 有空的话麻烦跟进看看，谢谢。
