### ISSUE TITLE
Add plugin event bus `mobile-keyboard-show` and `mobile-keyboard-hide`

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#9773]
### In what scenarios do you need this feature?

近期开发了移动端底部导航栏插件。为了优化交互效果，需要是否知道键盘是否会弹出。

### Describe the optimal solution

目前思源插件已经有了 EventBus 机制，并且官方的 KeyboardToolBar 已经实现了键盘的监听效果，只需要在相关逻辑里提供对应的事件类型就可以了。不知道这个事件类型否能够提供？

### Describe the candidate solution

目前我是用监听 keyboardToolBar 的显隐状态实现的这个功能。
<img width="848" alt="image" src="https://github.com/siyuan-note/siyuan/assets/16909518/0039a05a-7864-4f16-bde6-9ea960f4b8b9">

### Other information

由于近段时间刚开始加入思源笔记的开发，所以很多内容并不了解，如果有什么内容属于我自己遗漏了，还请D大和V姐见谅。

**Comment by Vanessa219** [comment]
主要是实现一个什么功能？

**Comment by 88250** [comment]
楼主还在吗？

**Comment by Wetoria** [comment]
> 楼主还在吗？

在的 D 大。我 GitHub 上的不勤快。我去改一下代码，提供一下说明。

**Comment by Wetoria** [comment]
> 主要是实现一个什么功能？

V姐，目前的话，我是个人用插件实现了移动端底部导航栏的功能。但是在键盘弹出的时候，这个导航栏有点碍事。

所以我就出现了“需要知道键盘弹出状态”这样一个能力。我看到目前移动端是会根据键盘弹出状态显示 *工具栏* 的，所以用监听了 *工具栏* 的显示状态实现了一版。

由于系统级已经实现了键盘的监听，所以看看是不是可以考虑提供一个事件类型。

![image](https://github.com/siyuan-note/siyuan/assets/16909518/1522f1a6-fcf9-4fb9-ad00-89eb09e3bfbf)


![IMG_2754](https://github.com/siyuan-note/siyuan/assets/16909518/02542710-58cb-41e9-9eb6-2a9d5c75bea5)

**Comment by Wetoria** [comment]
> 直接把插件 HTML 插入到工具栏的 DOM 里面可行否？

直接插入似乎是不行的，因为导航的出现逻辑跟工具栏正好是相反的。
