### ISSUE TITLE
header block doesn't show in outline panel when it was included in a quote block

### ISSUE THREAD

**Issue by XinLi0111** [siyuan-note/siyuan#9774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

the outline panel doesn't show the header blocks when it was included in a quote block

### Expected result

the header blocks show in outline panel

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/31495943/64ead4a8-199b-4db7-b3cf-d3d358d6ee9d)

### Version environment

```markdown
- Version: 2.11.0
- Operating System: win11
- Browser (if used):
```

### Log file

-

**Comment by 88250** [comment]
Hi, this is by design, the headings within the blockquote do not count towards the outline.
