### ISSUE TITLE
侧边栏悬浮模式下，将鼠标移至区域外就自动收起的触发条件放宽一点

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9777]
### In what scenarios do you need this feature?

侧边栏在不钉住的情况下，似乎有点过于敏感了。
![image](https://github.com/siyuan-note/siyuan/assets/27268127/711489a3-27e9-4822-9d9f-d2986510782c)

只要鼠标离开区域哪怕一点点就收起了，但是有时候我只是不小心移出去了而已，希望可以把这个判定条件放宽松一点。

### Describe the optimal solution

两个思路：

1. 把判定范围加大，比如要鼠标移动到边缘外多少距离才收起
2. 用一个定时器，移出后 setTimeout 设置 500ms 或者 1s 之后才收起，而如果在此期间重新移入了就取消定时器

**Comment by Temacc0531** [comment]
关联 #9136

**Comment by 88250** [comment]
暂时不考虑修改了，请参考 https://github.com/siyuan-note/siyuan/issues/9136#issuecomment-1710950307
