### ISSUE TITLE
特殊场景下，文字被吞。

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#978]
### 描述问题 Describe the problem

![s1](https://user-images.githubusercontent.com/69628966/103970555-82264f80-51a3-11eb-8d3a-e5c1c7f3546e.gif)

### 版本环境 Version environment

* 版本 Version：0.5.7
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，我这里重现不了问题，请升级到最新版后再试试，谢谢。
