### ISSUE TITLE
关于“光标所在块钱插入空块”

### ISSUE THREAD

**Issue by Chenm4** [siyuan-note/siyuan#9782]
### In what scenarios do you need this feature?

如图一所示我在光标处使用向前插入空块效果如图二所示，但是这个功能我觉得应该在最外层插入，因为在这个位置我不使用向前插入空块的方式我直接回车效果也是一样的，但是我想在顶层列表前插入就比较麻烦需要把光标移动到列表的上一个块然后可能还需要多次回车因为列表块的上一个块可能是嵌套的列表块
![image](https://github.com/siyuan-note/siyuan/assets/98648589/a6ed5cfe-a92f-4210-9c53-64216009c4de)
![image](https://github.com/siyuan-note/siyuan/assets/98648589/32013a05-e671-4491-a4fb-919869305fd8)

### Describe the optimal solution

同时我在思考一个问题时如果是列表块的向上插入一个块是否插入一个父列表的形式会更好，图一是插入前，图二是插入后的，但是我觉得插入后的效果是否应该变成图三的形式会更好？因为我如果不想要这个列表我直接enter或者shift+tab都可以直接变成图二形式都很方便，但是如果我想要一个父列表就会很困难，首先要新建一个列表然后还要再拖动列表变成新列表，这个还有一定概率内核异常
![image](https://github.com/siyuan-note/siyuan/assets/986
![image](https://github.com/siyuan-note/siyuan/assets/98648589/f7044a07-27f9-4d7c-8fa0-dbce28732a41)
48589/c0048731-e44a-4ca9-8c46-48d7141f8eb1)
![image](https://github.com/siyuan-note/siyuan/assets/98648589/002ea115-0858-4568-9c94-6535dbbda423)

**Comment by Chenm4** [comment]
简而言之就是痛点在于如何在下图所示的位置快速插入一个列表块，当前的操作都需要好几步骤（可能我这个格式比较怪，列表直接嵌套引用，我这个是用的quickadd的那个功能，我感觉很好用
![image](https://github.com/siyuan-note/siyuan/assets/98648589/712eca56-d80f-4935-9d70-f95194a3b53c)

**Comment by 88250** [comment]
可以先用 Shift+↑ 多选几次后扩选到列表，然后再按 Ctrl+Shift+B 插入。

**Comment by Chenm4** [comment]
> 可以先用 Shift+↑ 多选几次后扩选到列表，然后再按 Ctrl+Shift+B 插入。

哦哦哦，确实可以，感谢

**Comment by Chenm4** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/98648589/bbcc736f-f128-48f3-abca-7190a2987dfe)
一个新的疑惑是我整理笔记的时候想在上图光标的位置回车让光标后面的链接变成子列表，但是回车后变成下图所示
![image](https://github.com/siyuan-note/siyuan/assets/98648589/e247c704-319d-40e3-b15d-eb3cd47a4891)
下面这个图是我想实现的效果(我目前只能通过剪切掉后面的内容然后回车来实现，所以不太理解为什么后面有东西和没有东西不一样)。我觉得痛点在于如果是下图这种形式我能很快速的转换为上图的形式直接通过shift tab即可，但是我不知道有没有办法通过上图形式快速转成下图
![image](https://github.com/siyuan-note/siyuan/assets/98648589/5dccef17-0a2d-4288-9dc4-4295e45e7558)

**Comment by Vanessa219** [comment]
所有列表项中的块回车都会形成一个新的同级列表项，没有办法回车直接成为子项。

**Comment by Vanessa219** [comment]
@Chenm4 翻看了一下，大致原因如下： https://github.com/siyuan-note/insider/issues/363

**Comment by Chenm4** [comment]
> @Chenm4 翻看了一下，大致原因如下： [siyuan-note/insider#363](https://github.com/siyuan-note/insider/issues/363)

2.11.2版本的列表出现了问题
![image](https://github.com/siyuan-note/siyuan/assets/98648589/f61dd827-b601-45c8-9b91-309d916b7df9)
此类列表加引述选择转为段落功能后好像百分百复现内核异常退出

**Comment by Chenm4** [comment]
最新版本的插入块的api好像也有点问题了，不过我最近比较忙没空具体测，回退到2.10版本正常了，应该就是最近两个版本的问题（顺便说下插入块2.10也有时候出错，有时候就插入重复或者插入错地方或者插入速度有时候快有时候慢，平均一天用的多的话可能好几次重建索引），最新版的插入在我这基本不可用，不知道什么原因，如果排查不出的话我过段时间再详细看看 @88250

**Comment by 88250** [comment]
试试 dev版，应该已经修复。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月21日(周四) 中午1:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 关于“光标所在块钱插入空块” (Issue #9782)




 
最新版本的插入块的api好像也有点问题了，不过我最近比较忙没空具体测，回退到2.10版本正常了，应该就是最近两个版本的问题（顺便说下插入块2.10也有时候出错，有时候就插入重复或者插入错地方或者插入速度有时候快有时候慢，平均一天用的多的话可能好几次重建索引），最新版的插入在我这基本不可用，不知道什么原因，如果排查不出的话我过段时间再详细看看 @88250
