### ISSUE TITLE
Improve search UI

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9788]
https://ld246.com/article/1700965006430/comment/1701047908461?r=Vanessa#comments

<img width="675" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/d51c00bf-0e9b-49d2-9455-276439fd0217">

**Comment by mozhux** [comment]
搜索那个纪录支持一下删除吧，就是点图标后的搜索纪录，加一个清除所有呗。

**Comment by royc01** [comment]
单项吧，跟Google那些一致就好

**Comment by mozhux** [comment]
> 为了隐私的话是不是清除单项更好？

合理的方式是每个纪录后面有个x，然后还有一个清理所有的。参考微信。
![80ec9677e36df0b7b1cdca0896b1a19](https://github.com/siyuan-note/siyuan/assets/46953371/06b5dc5c-8e17-429b-9c3c-1def9d0c668f)

![72cbb904286cafb0956ade4619b0c68](https://github.com/siyuan-note/siyuan/assets/46953371/d66cc273-9e2d-48fc-9ba1-8f0886adbb49)

**Comment by Vanessa219** [comment]
`清除所有`放在列表上的话可以能误删，给确认的话又太多余。有没有什么好的建议？

**Comment by royc01** [comment]
列举最近的10条，每条后面有个x，应该可以满足

**Comment by mozhux** [comment]
> `清除所有`放在列表上的话可以能误删，给确认的话又太多余。有没有什么好的建议？

我的建议是彻底改革这个搜索框，有以下几点建议：
1. 点击搜索界面的输入框，自动弹出搜索历史方便使用；
2. 搜索历史默认只展开2行，多少条根据宽度来。
3. 单个搜索历史鼠标悬浮后增加删除按钮（移动端为长按），整体页面右上角增加清空所有按钮。 界面类似闪卡管理。
4. 搜索界面增加控制区分大小写的按钮或者过滤类型。目前只能全局控制不方便。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/a01c841d-ea6e-4d15-a751-8ffea6db77cb)

**Comment by 88250** [comment]
4. 大小写那个需要重建索引，所以不提供实时切换。

我们暂时就只在目前的基础上，加上搜索记录每条后面 x 删除功能吧 https://github.com/siyuan-note/siyuan/issues/9794

**Comment by mozhux** [comment]
> 4. 大小写那个需要重建索引，所以不提供实时切换。
> 
> 我们暂时就只在目前的基础上，加上搜索记录每条后面 x 删除功能吧 #9794
每条都有了，再来个清空所有吧

**Comment by 88250** [comment]
清空所有没有地方放，估计只能放在下拉列表的第一项？

**Comment by mozhux** [comment]
如果不想改动那么大，我是觉得点开后，加一个文字和按钮，
文字 最近搜索纪录  然后旁边是一个删除垃圾桶图标
![image](https://github.com/siyuan-note/siyuan/assets/46953371/1ec114bb-7611-4667-80eb-e9bdb22a0f79)

**Comment by 88250** [comment]
我的意思是放在这里：

![image](https://github.com/siyuan-note/siyuan/assets/873584/7a9114cf-45cd-40c5-9144-2faf894d795f)

**Comment by mozhux** [comment]
> 我的意思是放在这里：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/286948417-7a9114cf-45cd-40c5-9144-2faf894d795f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTE5NDAsIm5iZiI6MTcwMTM1MTY0MCwicGF0aCI6Ii84NzM1ODQvMjg2OTQ4NDE3LTdhOTExNGNmLTQ1Y2QtNDBjNS05MTQ0LTJmYWY4OTRkNzk1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxMzQwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmI1YjUxODRlYWJhYTY1NjZjZDgxMjg5ZGU5ZGYzYzRkNmZmNzBhZjZkZWVmNDQ2YzllODViMzVkZTg5MzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._CMvxfacGD9s-D5Z19L4Lk9m9z--tqiaal_9R2HtMl8)

意思是这样，整体下移，UI也好看点
