### ISSUE TITLE
056, 057版本无法搜索到单引号里面的内容

### ISSUE THREAD

**Issue by kiritocode** [siyuan-note/siyuan#979]
### 描述问题 Describe the problem

056, 057版本无法搜索到反单引号里面的内容。
比如下面这句话

> 这段代码的核心函数是`build_graph`

我要在后面引用它，无论是 (( 触发的搜索，还是直接用 CTRL-P 搜索都没法找到。

在0546版本里没有这个问题。

我使用siyuan笔记分析代码，描述各个函数调用关系，经常会在后面一段用 (( 去插入前面写过或提到过的代码解释。
能够搜通 *反引号* 下的 *函数名，变量名* 这个功能很重要。

如果和现有架构冲突，是否能考虑增加这样一个option到setting里，不需要这个搜通行为的用户可以关闭，需要的就打开。

### 期待的结果 Expected result

能够恢复0546版本的行为。

### 截屏或录屏演示 Screenshot or screen recording presentation

057版本的截图（无法搜到，不论加不加反引号）：
![5_7_0_inline](https://user-images.githubusercontent.com/77135994/103980207-67aba080-51ba-11eb-9007-9d7a95473eb2.png)
![5_7_0_search_without_quote](https://user-images.githubusercontent.com/77135994/103980213-6b3f2780-51ba-11eb-8ddd-41078ad05dfd.png)
![5_7_0_search](https://user-images.githubusercontent.com/77135994/103980217-6c705480-51ba-11eb-85f5-4610442b1411.png)

0546版本（希望能恢复到此）的行为截图：
![5_4_6_inline](https://user-images.githubusercontent.com/77135994/103980311-9de92000-51ba-11eb-8d02-21d8ca84c3f4.png)
![5_4_6_search](https://user-images.githubusercontent.com/77135994/103980315-9f1a4d00-51ba-11eb-917e-c7a060bf7baf.png)

### 版本环境 Version environment

* 版本 Version：056 and 057
* 操作系统 Operating system：Win10
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/08 14:06:28 main.go:121: kernel [v0.5.7] is booting, runtime mode is [prod], working directory is [D:\gnu\siyuan-0.5.7-win\resources], temp directory is [d:\TEMP\siyuan], read only [false]
I 2021/01/08 14:06:28 lang.go:67: initialized languages
D 2021/01/08 14:06:28 conf.go:89: loaded conf [C:\Users\admin\.siyuan\conf.json]
I 2021/01/08 14:06:28 conf.go:176: local serve path [http://172.16.1.1:6806]
I 2021/01/08 14:06:28 conf.go:180: initialized conf
I 2021/01/08 14:06:28 main.go:162: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/08 14:06:28 webdav.go:37: initialized WebDAV server
I 2021/01/08 14:06:28 box.go:363: indexing [1] trees, cpus [8]
D 2021/01/08 14:06:28 box.go:398: indexed box [http://127.0.0.1:6806/siyuan/1608607080604/bug_tracking/]
I 2021/01/08 14:06:28 conf.go:297: initialized box
I 2021/01/08 14:06:29 repo.go:39: initialized git repo
I 2021/01/08 14:06:29 updater.go:79: auto update is disabled
I 2021/01/08 14:06:37 setuilayout.go:43: set ui layout done
I 2021/01/08 14:06:38 process.go:71: ui process exited, exit kernel process now
I 2021/01/08 14:06:38 conf.go:228: exited kernel

### 更多信息 More information

**Comment by 88250** [comment]
你好，后面的版本搜索结果只会展现根一级上的块，子块需要使用类型过滤，谢谢。

**Comment by kiritocode** [comment]
类型过滤对里面提到的问题好像没用，我想要搜出来的块是个普通的文本块，不是代码块；
只是这个文本块里面包含的关键字是用反引号括起来的（一般是个函数或变量名），
开启比如`c:`这样整体过滤除可以应对一个完整的代码块，但无法处理普通块里包含的代码。

事实上，现在用反引号包裹的内容就成了一个“黑洞”了，无论如何都搜不出来，
不论加上反引号，还是加搜索条件，都没有办法。

**Comment by 88250** [comment]
v0.5.9 https://github.com/siyuan-note/siyuan/issues/993

**Comment by kiritocode** [comment]
好的
