### ISSUE TITLE
v202311301647表格大小无法调整

### ISSUE THREAD

**Issue by hackerhui** [siyuan-note/siyuan#9795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

v202311301647表格大小无法调整

### Expected result

应当可以调整表格的列宽

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
感谢反馈，稍后修复。
