### ISSUE TITLE
Support base64 encoded/decode images

### ISSUE THREAD

**Issue by scatyf3** [siyuan-note/siyuan#9796]
### In what scenarios do you need this feature?

当我们从剪藏网页时，有一些网页的内嵌图片是base64编码的，如:
```
[  ](https://oi-wiki.org/edit-landing/?ref=/search/alpha-beta.md "编辑此页")此页面将简要介绍 minimax 算法和 ![](data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7 "\alpha-\beta") 剪枝。
```

能否在siyuan笔记上增加解码并显示base64编码的图片，甚至在导出的时候支持把全部图片转为base64格式内嵌呢？

### Describe the optimal solution

- 在siyuan前端增加一个base64解码器，比如[这个stackoverflow提到的代码片段](https://stackoverflow.com/questions/53129002/converting-image-to-base64-string-in-typescript)
- 在剪藏插件中将base64解码为图片，然后在siyuan本地仍引用图片

### Other information

另：我理解开发组工作不易，如果不增加这个功能也非常理解。还想请问这个功能适合新手贡献吗？若是适合的话，比较想自己试试贡献siyuan项目

**Comment by 88250** [comment]
你好，如果是导入 Markdown 文件的话已经支持 base64 编码的图片自动转换为文件，其他情况考虑到会引起性能问题所以不做实现，感谢提议。

相关代码可以在 kernel/model/import.go 文件中搜索 `base64` 关键字，谢谢。
