### ISSUE TITLE
Add plugin eventbus `sync-start`, `sync-end`, and `sync-fail`

### ISSUE THREAD

**Issue by zuoez02** [siyuan-note/siyuan#9798]
[Plugin event request] Request new event "sync-start", "sync-finish"

### In what scenarios do you need this feature?

Get sync finish and refresh file list from /data/public

### Describe the optimal solution

Add two event in eventbus

**Comment by Vanessa219** [comment]
监听 "ws-main"
data.cmd === "syncing" 
data.code === 0  // syncing
data.code === 2    // error
data.code === 1   // success

这样是不太方便还是有其他问题？

**Comment by zuoez02** [comment]
不方便，而且这需要插件全程监听这个同步过程，过于复杂了，还是思源包装好比较好，按照插件已有的事件形式比较方便。ws main事件信息量太大了😂

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: V ***@***.***>
发送时间: Saturday, December 2, 2023 1:00:34 PM
收件人: siyuan-note/siyuan ***@***.***>
抄送: Luto Yvan ***@***.***>; Author ***@***.***>
主题: Re: [siyuan-note/siyuan] [Plugin event request] Request new event "sync-start", "sync-finish" (Issue #9798)


监听 "ws-main"
data.cmd === "syncing"
data.code === 0 // syncing
data.code === 2 // error
data.code === 1 // success

这样是不太方便还是有其他问题？

**Comment by Achuan-2** [comment]
@Vanessa219 sync-end能否知道同步方向，如果能判断同步只是上传文件，插件就无需获取并更新文件内容了

**Comment by 88250** [comment]
@Achuan-2 自动同步模式下是双向合并的，没有同步方向这个概念。

**Comment by TCOTC** [comment]
手动同步也是双向合并

**Comment by TCOTC** [comment]
> 如果能判断同步只是上传文件，插件就无需获取并更新文件内容了

@Achuan-2 你说的是插件的文件还是什么文件？petal 里的文件更新有提供 [onDataChanged](https://github.com/siyuan-note/plugin-sample/blob/9a287d302f3cc934a54833e940d290637befdacb/src/index.ts#L271-L275) 方法，可以在执行方法时重新 loadData，不添加方法的话会自动重新加载插件。

**Comment by Achuan-2** [comment]
插件文件

为了减少插件读取文件，插件缓存数据，但是多端同步后，这样可能会导致没有加载同步数据，导致同步的数据又被原来缓存数据覆盖，所以需要监听同步事件，同步下载文件后需要再加载数据

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TCOTC** [comment]
那就用我说的这个方法就行了

**Comment by Achuan-2** [comment]
> 那就用我说的这个方法就行了

谢谢，不过onDataChanged  在我这里（思源v3.5.4）测试，无法定义，定义了函数完全没作用，console.log也不输出，插件依然禁用又启用，不过既然目前插件会自动禁用又启用，没有数据覆盖问题那就先不管了

**Comment by TCOTC** [comment]
我这里最新的代码测试自动同步模式和完全手动同步模式没有问题。

插件代码：

```ts
import {Plugin} from "siyuan";
export default class PluginSample extends Plugin {
    async onload() {
        console.log('PluginSample onload');
    }

    async onLayoutReady() {
        await this.saveData("data", Math.random().toString())
        const data = await this.loadData("data")
        console.log("data:", data);
    }

    async onunload() {
        const data = await this.loadData("data")
        console.log("data:", data);
    }

    async onDataChanged(): Promise<void> {
        console.log('onDataChanged');
        const data = await this.loadData("data")
        console.log("data:", data);
    }
}
```

同步之后的控制台输出：

![Image](https://github.com/user-attachments/assets/e276ac7c-2fd0-40d5-b3a5-634aa126cb82)

**Comment by Achuan-2** [comment]
@TCOTC 哦哦，是我之前为了测试功能，修改了系统时间到未来，导致一同步，思源云端就认为我这边是旧数据，只要一同步就会覆盖我的本地数据，导致插件代码都恢复为原样了。老实说这个同步算法太暴力了，只能改为手动同步，强行覆盖云端数据，否则当前数据都会被覆盖，无法保存，同步多少次都会被覆盖
