### ISSUE TITLE
序号在开头键入换行后自动消失

### ISSUE THREAD

**Issue by Jamie-Wan** [siyuan-note/siyuan#9799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

https://ld246.com/article/1701341424499
这个链接里对问题进行了描述。另外，如：1.思源笔记，在“1.”后面换行后依旧会导致序号消失。注意，不是有序列表，只是单纯使用序号。之前使用是没问题的，但不清楚是哪一版本的更新产生了这个bug。

### Expected result

希望这一bug能够解决

### Version environment

```markdown
- Version: 2.11.0
- Operating System: win11
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
已在社区原贴中回复，谢谢。
