### ISSUE TITLE
小优化：建议大纲默认展开，或增加可选项

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#980]
因为大纲默认折叠，展开的小三角也只有在鼠标悬浮时才显示，这样刚跳转到一个长文件的时候无法一眼看出文件里有哪些具体条目

![image](https://user-images.githubusercontent.com/32661922/103979179-29ad7d00-51b8-11eb-9715-b6d5171a7ace.png)

**Comment by 88250** [comment]
谢谢反馈，请关注 #564 。
