### ISSUE TITLE
为什么我只要按下7个空格就能对齐？

### ISSUE THREAD

**Issue by gffgvfgvf** [siyuan-note/siyuan#9806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

一般不是8个空格才对齐吗，但我的只要7个就能对齐，导致不管怎么调TAB，都不能完美对齐

### Expected result

希望能增加TAB空格数量自定义

### Version environment

```markdown
- Version: 2.11.0
- Operating System: WINDOWS11
- Browser (if used):
```

### Log file

[Uploading siyuan.log…]()

**Comment by gffgvfgvf** [comment]
> 设置 - 编辑器 - Tab 空格数
> 
> 另外，这个和字体有关系，需要等宽字体才能对齐。


我是用的默认字体，这个等宽字体要怎么调节？

**Comment by 88250** [comment]
默认字体的话代码块中的等宽字体用的是 JetBrainsMono，这个字体文件是软件自带的，可以 F12 后看下网络请求加载是否正常，代码块字体族：

![image](https://github.com/siyuan-note/siyuan/assets/873584/c85a65d9-7afe-4c38-9bb5-9a2043d19594)

**Comment by 88250** [comment]
默认主题不按照任何插件扩展和代码片段就是这个效果。

**Comment by gffgvfgvf** [comment]
> 默认主题不按照任何插件扩展和代码片段就是这个效果。

我设置过其他字体，都是正常的，就是这个字体有问题，请问要如何解决？

**Comment by 88250** [comment]
这个估计只能你自己看下了，用等宽字体才行。

**Comment by gffgvfgvf** [comment]
> 这个估计只能你自己看下了，用等宽字体才行。

好的，麻烦了。
