### ISSUE TITLE
希望插件详情页面有插件的地址

### ISSUE THREAD

**Issue by heimi98** [siyuan-note/siyuan#9808]
### In what scenarios do you need this feature?

希望插件详情页面有插件的地址，而不只是作者的主页地址，方便给对应的插件提 issue。

### Describe the optimal solution

插件详情页面有插件的 github 地址

**Comment by shuojie819** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/72399630/c8e72f3f-151e-4f71-834e-4d2b02e29898)
