### ISSUE TITLE
图片宽度异常

### ISSUE THREAD

**Issue by coff11** [siyuan-note/siyuan#9809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

笔记中的一些图片，在 PC 端无法拉宽，在移动端显示超过右侧边界。已经在论坛发过贴了： [有没有小伙伴遇到图片宽度显示不正常的](https://ld246.com/article/1701600888777)

### Expected result

图片应该可以调整尺寸，且在移动端正常显示。

### Version environment

```markdown
- Version: 2.11.0
- Operating System: macOS 14.1.2 (23B92)
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13538994/system-log.zip)

### More information

应该是内联在元素上的固定 `px` 的 `max-width` 导致的问题，但我不知道什么时候会添加这个属性到元素上，辛苦开发者排查一下。

**Comment by 88250** [comment]
非常抱歉，这个应该是以前版本的遗留问题。可以直接修改 .sy 文件后点击重建索引试试。 by V
