### ISSUE TITLE
超级块无法折叠

### ISSUE THREAD

**Issue by Duan-Wuya** [siyuan-note/siyuan#981]
### 描述问题 Describe the problem

超级块折叠之后只是全部变暗

### 期待的结果 Expected result

折叠之后仅保留第一行文字，同时取消 {{{ 的显示，左侧可以常驻S图标。

### 截屏或录屏演示 Screenshot or screen recording presentation

![image](https://user-images.githubusercontent.com/59379633/103989197-4d79be80-51ca-11eb-8c6d-88bf87f68f8e.png)

### 版本环境 Version environment

* 版本 Version：0.5.7
* 操作系统 Operating system：Windows
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5785866/siyuan.log)

**Comment by 88250** [comment]
你好，已在 https://github.com/siyuan-note/siyuan/issues/972 中改进，谢谢。
