### ISSUE TITLE
嵌入块支持按原文排序

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9817]
### In what scenarios do you need this feature?

之前在评论区问过，大佬说搜集下需求，我先记录下，免得完全忘了(๑>؂<๑）

### Describe the optimal solution

无

**Comment by 88250** [comment]
目前没有收到类似需求，先关闭了，有的话会考虑重开，谢谢。

**Comment by Jiangshuon** [comment]
关联一波，还有希望，继续收集，https://ld246.com/article/1708778493551/comment/1708779336283
