### ISSUE TITLE
Improve database table view filter

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9820]
https://ld246.com/article/1701755150869

**Comment by 88250** [comment]
你指的点一下是点哪里？

**Comment by Foundation-Maker** [comment]
排序的时候，为空的属性，排在了最前面呢

**Comment by zxhd863943427** [comment]
> 你指的点一下是点哪里？

就是点属性所在的单元格。

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/113923d8-1f7b-4b47-a049-98f9d7d2eb6d)

必须手动点一下才能在属性面板见到对应的属性

**Comment by 88250** [comment]
有可能的，比如数字列为空的话可以认为是 0



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 6, 2023 14:13 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Improve database table view filter (Issue#9820)




 
排序的时候，为空的属性，排在了最前面呢
