### ISSUE TITLE
Soft line break key on mobile is invalid

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9822]
移动端软换行键失效

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

百度输入法

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
在文本中间（不要在末尾）能使用吗？

**Comment by Jiangshuon** [comment]
哦哦，这样啊，中间可以用
