### ISSUE TITLE
Support converting network assets to local

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9826]

**Comment by pisceswb** [comment]
试用了该功能，感觉并不够好用。步骤有点麻烦：
1. 收集箱中移动资源到本地。
2. 从文档树中找到这条资源
3. 从菜单中找到选项，下载网络资源。
感觉步骤太繁琐了，其实在收集箱的菜单中，添加一个选项就挺好用的。例如“移动”，“下载并移动”。
当前，将收集箱资源移动到本地后，不一定要对这个文档立即编辑，也可能只是为了保存下来，不用去查看。如果移动多条收集箱内容的话，还得找到每个文件，然后再逐个下载资源，有点麻烦。

**Comment by 88250** [comment]
暂时不加其他选项了，这里有过解释 https://ld246.com/article/1701784600834
