### ISSUE TITLE
闪卡管理界面左边能否支持文档树方式显示条目

### ISSUE THREAD

**Issue by 397334469** [siyuan-note/siyuan#9828]
### In what scenarios do you need this feature?

现在是一行一行的
![image](https://github.com/siyuan-note/siyuan/assets/51410244/35d79dbd-eedf-49d5-840f-624ba65f6d1b)
希望能够支持跟搜索一样的，文档树方式显示，主要是方便管理，现在条目一多，不好找
![image](https://github.com/siyuan-note/siyuan/assets/51410244/54c97d42-e83b-4742-ba5c-9673c5f4e343)

### Describe the optimal solution

如上

**Comment by 88250** [comment]
你好，这个不考虑了，感谢提议。
