### ISSUE TITLE
Add internal kernel API `/api/setting/refreshVirtualBlockRef`

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#9829]
Does VirtualRef job time can become a config?

### In what scenarios do you need this feature?

在阅读场景下，新接触的词汇，希望虚拟引用能够及时生效，而不是可能 10 分钟后才能看到。

### Describe the optimal solution

提供一个按钮，或者是一个快捷键，能够让用户自动选择刷新虚拟引用的缓存。

### Describe the candidate solution

将虚拟引用的 job 时间，改成一个可以配置的选项。

### Other information

目前虚拟引用的 job 是固定的 10 分钟。虽然是有性能方面的考虑，但是对于我这样电脑还过得去的用户来说，10 分钟的时间太久了。

两种方式，我更倾向于在我选择词汇创建完双链以后，使用快捷键能够立马刷新当前文档的虚拟引用，这样在后续阅读的时候，可以及时得到提示。

**Comment by frostime** [comment]
资瓷一下

**Comment by zuoez02** [comment]
资瓷一下

**Comment by 88250** [comment]
我们提供一个用于刷新虚拟引用的 API 吧，界面不考虑了，请社区开发者制作插件，感谢。

**Comment by Wetoria** [comment]
> 我们提供一个用于刷新虚拟引用的 API 吧，界面不考虑了，请社区开发者制作插件，感谢。

这个方案也行。我也考虑过自己加，但是目前在思源主体上的开发经验还不够，所以没有提交 PR。

D大你们怎么方便怎么来吧。

**Comment by IAliceBobI** [comment]
这个好啊，配合命令面板，刷起。
