### ISSUE TITLE
编辑器内搜索无法定位表格中的内容

### ISSUE THREAD

**Issue by MistRay** [siyuan-note/siyuan#983]
### 描述问题 Describe the problem
编辑器内搜索无法定位表格中的内容

### 截屏或录屏演示 Screenshot or screen recording presentation
![录屏](https://user-images.githubusercontent.com/34370155/103992089-96337680-51ce-11eb-99e4-a48993df1e47.gif)

### 版本环境 Version environment

* 版本 Version：0.5.7
* 操作系统 Operating system：win10
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
感谢反馈，请关注 https://github.com/siyuan-note/siyuan/issues/922
