### ISSUE TITLE
macos boot up stuck, no active UI proc

### ISSUE THREAD

**Issue by jibwf** [siyuan-note/siyuan#9832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Boot up stuck, no ui

I 2023/12/07 11:07:47 runtime.go:74: kernel is booting:
    * ver [2.11.1]
    * arch [amd64]
    * os [darwin]
    * pid [11306]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/bowji/Documents/SiYuan]
I 2023/12/07 11:07:47 conf.go:403: user has enabled [Automatically upload error messages and diagnostic data]
I 2023/12/07 11:07:47 runtime.go:128: use network proxy [system]
I 2023/12/07 11:07:47 serve.go:119: kernel [pid=11306] http server [127.0.0.1:56124] is booting
I 2023/12/07 11:07:48 pandoc.go:132: built-in pandoc [ver=2.19.2, bin=/Users/bowji/Documents/SiYuan/temp/pandoc/bin/pandoc]
I 2023/12/07 11:07:48 conf.go:957: pandoc initialized, set pandoc bin to [/Users/bowji/Documents/SiYuan/temp/pandoc/bin/pandoc]
I 2023/12/07 11:07:48 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
I 2023/12/07 11:07:48 sync.go:140: sync before boot
I 2023/12/07 11:07:48 ref.go:52: got local latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:49 ref.go:52: got local latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:50 ref.go:52: got local latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:51 webdav.go:104: downloaded object [main/siyuan/repo/refs/latest]
I 2023/12/07 11:07:52 webdav.go:104: downloaded object [main/siyuan/repo/indexes/c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a]
I 2023/12/07 11:07:52 sync.go:1512: got cloud latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:52 repository.go:1141: boot get sync cloud files elapsed [3.25s]
I 2023/12/07 11:07:52 blocktree.go:494: read block tree [15 MB] to [/Users/bowji/Documents/SiYuan/temp/blocktree], elapsed [0.07s]
I 2023/12/07 11:07:52 conf.go:735: database size [182 MB], tree/block count [457/57676]
I 2023/12/07 11:07:52 working.go:183: kernel booted
I 2023/12/07 11:07:52 box.go:79: auto stat [trees=457, blocks=57676, dataSize=1.7 GB, assetsSize=1.6 GB]
I 2023/12/07 11:07:52 disk.go:33: disk usage [total=500 GB, used=326 GB, free=174 GB]
W 2023/12/07 11:08:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:09:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:09:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:09:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:10:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:10:22 process.go:76: active UI proc count [8]

### Expected result

Boot up successful

### Version environment

```markdown
- Version: 2.11.1 desktop app
- Operating System:macos 14.1.2 
- Browser (if used): edge
- Default theme and no extension
```

### Log file

I 2023/12/06 23:13:24 database.go:1218: closed database
I 2023/12/06 23:13:24 conf.go:892: cleared workspace temp
I 2023/12/06 23:13:25 sync.go:672: sync websocket closed
I 2023/12/06 23:13:25 conf.go:550: exited kernel
I 2023/12/07 11:07:47 working.go:145: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/12/07 11:07:47 runtime.go:74: kernel is booting:
    * ver [2.11.1]
    * arch [amd64]
    * os [darwin]
    * pid [11306]
    * runtime mode [prod]
    * working directory [/Applications/SiYuan.app/Contents/Resources]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/Users/bowji/Documents/SiYuan]
I 2023/12/07 11:07:47 conf.go:403: user has enabled [Automatically upload error messages and diagnostic data]
I 2023/12/07 11:07:47 runtime.go:128: use network proxy [system]
I 2023/12/07 11:07:47 serve.go:119: kernel [pid=11306] http server [127.0.0.1:56124] is booting
I 2023/12/07 11:07:48 pandoc.go:132: built-in pandoc [ver=2.19.2, bin=/Users/bowji/Documents/SiYuan/temp/pandoc/bin/pandoc]
I 2023/12/07 11:07:48 conf.go:957: pandoc initialized, set pandoc bin to [/Users/bowji/Documents/SiYuan/temp/pandoc/bin/pandoc]
I 2023/12/07 11:07:48 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
I 2023/12/07 11:07:48 sync.go:140: sync before boot
I 2023/12/07 11:07:48 ref.go:52: got local latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:49 ref.go:52: got local latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:50 ref.go:52: got local latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:51 webdav.go:104: downloaded object [main/siyuan/repo/refs/latest]
I 2023/12/07 11:07:52 webdav.go:104: downloaded object [main/siyuan/repo/indexes/c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a]
I 2023/12/07 11:07:52 sync.go:1512: got cloud latest [device=FC3FF936-4EA0-5D5C-A2F4-3794409DC622/darwin, id=c5dfb93a62e593cbc625d5f6b5b93bf6d79ca32a, files=8382, size=1.7 GB, created=2023-12-06 17:29:02]
I 2023/12/07 11:07:52 repository.go:1141: boot get sync cloud files elapsed [3.25s]
I 2023/12/07 11:07:52 blocktree.go:494: read block tree [15 MB] to [/Users/bowji/Documents/SiYuan/temp/blocktree], elapsed [0.07s]
I 2023/12/07 11:07:52 conf.go:735: database size [182 MB], tree/block count [457/57676]
I 2023/12/07 11:07:52 working.go:183: kernel booted
I 2023/12/07 11:07:52 box.go:79: auto stat [trees=457, blocks=57676, dataSize=1.7 GB, assetsSize=1.6 GB]
I 2023/12/07 11:07:52 disk.go:33: disk usage [total=500 GB, used=326 GB, free=174 GB]
W 2023/12/07 11:08:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:09:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:09:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:09:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:10:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:10:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:10:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:11:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:11:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:11:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:12:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:12:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:12:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:13:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:13:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:13:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:14:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:14:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:14:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:15:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:15:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:15:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:16:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:16:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:16:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:17:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:17:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:17:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:18:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:18:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:18:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:19:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:19:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:19:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:20:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:20:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:20:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:21:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:21:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:21:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:22:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:22:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:22:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:23:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:23:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:23:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:24:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:24:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:24:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:25:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:25:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:25:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:26:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:26:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:26:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:27:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:27:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:27:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:28:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:28:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:28:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:29:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:29:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:29:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:30:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:30:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:30:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:31:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:31:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:31:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:32:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:32:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:32:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:33:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:33:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:33:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:34:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:34:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:34:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:35:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:35:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:35:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:36:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:36:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:36:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:37:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:37:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:37:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:38:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:38:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:38:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:39:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:39:22 process.go:76: active UI proc count [8]
W 2023/12/07 11:39:52 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 11:40:07 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 11:40:22 process.go:76: active UI proc count [8]
W 2023/12/07 12:10:46 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 12:11:01 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 12:11:16 process.go:76: active UI proc count [8]
W 2023/12/07 12:11:46 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 12:12:01 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 12:12:16 process.go:76: active UI proc count [8]
W 2023/12/07 12:12:46 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 12:13:01 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 12:13:16 process.go:76: active UI proc count [8]
W 2023/12/07 12:13:46 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 12:14:01 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 12:14:16 process.go:76: active UI proc count [8]
W 2023/12/07 12:14:46 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 12:31:18 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 12:31:33 process.go:76: active UI proc count [8]
W 2023/12/07 12:38:33 process.go:66: no active UI proc, continue to check from attached ui processes after 15s
W 2023/12/07 12:38:48 process.go:72: no active UI proc, continue to check from all processes after 15s
I 2023/12/07 12:39:03 process.go:76: active UI proc count [8]

**Comment by jibwf** [comment]
it is not happen every boot up. It seems happen after sleep. 
[Uploading siyuan.log…]()

**Comment by jibwf** [comment]
> > the only workaround is reload.
> 
> I don't quite understand what "reload" you mean?

Restart my macbook

**Comment by 88250** [comment]
Hello, we have closed this issue for now. If you have any additional questions please feel free to post directly. Thank you very much.

**Comment by jibwf** [comment]
Ctrl+Shift+I did not open developer tool. 
I uninstall displaylink, then issue gone. It seems displaylink conflict with siyuan.

**Comment by jibwf** [comment]
> You can try pressing Ctrl+Shift+I in the white screen window to open the developer tools, and then press Ctrl+R to refresh.

Ctrl+Shift+I did not open developer tool.
I uninstall displaylink, then issue gone. It seems displaylink conflict with siyuan.

**Comment by AnexiledPKUer** [comment]
> > You can try pressing Ctrl+Shift+I in the white screen window to open the developer tools, and then press Ctrl+R to refresh.
> 
> Ctrl+Shift+I did not open developer tool. I uninstall displaylink, then issue gone. It seems displaylink conflict with siyuan.

I encountered the same problem as you. Inspired by you, I reinstalled the NVIDIA drivers and then reinstalled the program, which succeeded. Therefore, I suspect that this issue occurs when the display device changes.
