### ISSUE TITLE
重复重启siyuan，但是使用一段时间就会提示数据库被锁，有其它进程占用

### ISSUE THREAD

**Issue by livevol89** [siyuan-note/siyuan#9834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

重复重启siyuan，但是使用一段时间就会提示数据库被锁，有其它进程占用
我已经删除了所有siyuan笔记安装的程序的文件夹多次，重新卸载安装后依然有问题。
![image](https://github.com/siyuan-note/siyuan/assets/42825552/8503849f-1294-4329-9ee7-d4a346c98906)

并且为了排查原因，下载powertoys，发现并未有任何其它程序占用workspace,

![image](https://github.com/siyuan-note/siyuan/assets/42825552/d206b7aa-ac34-4129-88d1-c5a8c610ba1b)

### Expected result

正常使用

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/42825552/f6ac3009-ba5b-4b71-8d29-bec9b1d99645)

### Version environment

```markdown
- Version: 2.11.0
- Operating System: win10
- Browser (if used): 下载程序使用
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13596046/siyuan.log)

**Comment by livevol89** [comment]
2023/12/07 13:58:08 database.go:1322: database disk image [D:\0_SY\temp\siyuan.db] is malformed, please restart SiYuan kernel to rebuild it 是这个问题的原因嘛？ @88250

**Comment by livevol89** [comment]
谢谢，我删除了temp文件夹，重建索引，目前开启的程序没有异常退出。

**Comment by 88250** [comment]
抱歉，只能用内置的内部存储作为工作空间路径。
