### ISSUE TITLE
闪卡页面闪卡块右侧不显示闪卡标识（黄色竖线）

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![6571552f2240fbeb4914325a](https://github.com/siyuan-note/siyuan/assets/67137548/335e4147-e3ef-40ae-a3ff-138086b4e76b)

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
闪卡页面都不显示，不然都是标识。
