### ISSUE TITLE
Ctrl+D abnormal behavior

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#9841]
windows上，自定义插入代码块快捷键产生异常行为在 2.11.1 版本又出现了

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

之前提过issue https://github.com/siyuan-note/siyuan/issues/9735
后面的版本就解决了，但是到了2.11.1，问题又出现了

### Expected result

正确处理

### Version environment

```markdown
- Version: 2.11.1
- Operating System: windows
- Browser (if used):
```

### Log file

应该不用

**Comment by 88250** [comment]
和这个问题是同一个吗？ https://ld246.com/article/1702001482861

**Comment by Vanessa219** [comment]
非常抱歉，由于 https://github.com/siyuan-note/siyuan/issues/9770 这个问题忽略了。下个版本继续改进。
