### ISSUE TITLE
希望数据库增加时间列

### ISSUE THREAD

**Issue by shuojie819** [siyuan-note/siyuan#9843]
### In what scenarios do you need this feature?

感觉时间列还是很有用的，例如：想做一个火车票的表格，几点出发到几点到达（13:15 👉 15:31），……还有很多都需要时间列。可以用来排序……

### Describe the optimal solution

希望数据库增加一个时间列（不包含日期的，只有时间）

例如：00:00:00、00:00

**Comment by 88250** [comment]
参考现有的类 Notion 产品似乎都没有时间列，为保险起见，我们暂时也不考虑添加了，感谢提议。

**Comment by shuojie819** [comment]
> 参考现有的类 Notion 产品似乎都没有时间列，为保险起见，我们暂时也不考虑添加了，感谢提议。

难道这个功能不是为了更好的记录吗！！！
不需要非得按照Notion搬吧🥲！！！

1. 我是真的很想很想很想……要这个
2. 我觉得真的没必要按照Notion来吧，比Notion更强大不是更好吗🤔
3. 还是希望大大可以考虑一下，真的不太懂为什么要按Notion来！！！

**Comment by 88250** [comment]
其他产品没做应该是有原因的，我们得仔细考虑一下。

**Comment by shuojie819** [comment]
> 其他产品没做应该是有原因的，我们得仔细考虑一下。

哦哦，好的，希望有朝一日思源最强大😁（不要忘了这个需求呀！）
