### ISSUE TITLE
No longer force using discrete GPU on desktop

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9845]
https://github.com/siyuan-note/siyuan/issues/9694

**Comment by Chenm4** [comment]
我感觉强制使用独显可能会更好一点，因为如果思源卡那么用户就只会觉得思源很烂而不会考虑这是为了续航好，但是如果电脑续航差用户只会觉得电脑不行，大部分用户不会想到是不是思源太耗电了，让少部分对续航敏感的用命令禁止独显可能更合适一点？我主要是觉得大部分情况下使用思源的场景都是插电。
以上仅个人建议，ld的讨论我也看了，仅发表下个人看法

**Comment by 88250** [comment]
独显在有的系统上会有莫名其妙的问题，所以还是回复默认好，有需要独显的场景自己加参数吧。
