### ISSUE TITLE
导出文档时，能否屏蔽某些内容？

### ISSUE THREAD

**Issue by IAliceBobI** [siyuan-note/siyuan#9847]
### In what scenarios do you need this feature?

有些文字是给自己看的，导出时不需要导出，就像代码里面的注释，不需要编译。

### Describe the optimal solution

比如约定个属性

**Comment by 88250** [comment]
这个大概是不行，复制后重新编辑导出吧，感谢提议。

**Comment by IAliceBobI** [comment]
> 这个大概是不行，复制后重新编辑导出吧，感谢提议。

感谢回复。
