### ISSUE TITLE
Improve database table view UI to differentiate between bound and unbound row

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9849]
修改数据库属性块 UI 已区分绑定和未绑定块的行
https://ld246.com/article/1702089774253

**Comment by mozhux** [comment]
这个下划线离文本太近了。不仔细看都看不清，也很丑，建议有点间距。
![image](https://github.com/siyuan-note/siyuan/assets/46953371/ed04d04d-a10b-42be-b9f6-c4d1c544e65c)

![image](https://github.com/siyuan-note/siyuan/assets/46953371/bf3a1080-a840-4bcf-bed7-6562a7bbfd3b)

暗黑模式更看不清
![image](https://github.com/siyuan-note/siyuan/assets/46953371/b1f9f642-37a9-4d55-bf52-532e82d81b63)

**Comment by TCOTC** [comment]
看图片，感觉线段应该稍微往下一点，并且更亮一点

**Comment by Vanessa219** [comment]
这样如何？
<img width="278" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/f69c8980-de45-4485-ab8c-0194e5c4606a">

**Comment by TCOTC** [comment]
感觉还不错

**Comment by mozhux** [comment]
又稍微有点太亮，可以放多几个例子，绑定和不绑定交错的，10行那样看下效果，可能要稍微暗一点点。间距是够了

**Comment by Vanessa219** [comment]
准备发版了，不行的话下个版本再改

**Comment by mozhux** [comment]
> 准备发版了，不行的话下个版本再改

发测试版吗？dev5在我这数据库都是废的了，添加行无法添加，只能每次添加一次刷新一次才行。

**Comment by Vanessa219** [comment]
呃，正式版。这个要怎么重现？
