### ISSUE TITLE
导出PDF文档，块如图片一样，造成大量空白半页

### ISSUE THREAD

**Issue by geyk** [siyuan-note/siyuan#9852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

当导入pdf时，换页时遇到块不切割，另起一页，只有当一个块大到超过一页时被迫分割这个块。群里已经复现
换个说话就是导入pdf时，块就如图片。
2.11.1导出效果如下图：
![Snipaste_2023-12-11_12-43-13](https://github.com/siyuan-note/siyuan/assets/12878086/8bdaa2ac-e621-4e36-9771-958c1bb1af88)

### Expected result

期待结果如下图（2.77导出pdf的结果）：
![Snipaste_2023-12-11_12-44-41](https://github.com/siyuan-note/siyuan/assets/12878086/c1b9231f-6e58-4dc6-99c0-a37eb78dfb1a)

### Version environment

```markdown
- Version: 2.77之后的所有版本
- Operating System: windows 10, 11
- Browser (if used):
```

### Log file

1

**Comment by 88250** [comment]
这个暂时是没有办法了，因为 Electron 升级以后改变了 PDF 渲染的逻辑，只能寄希望于后续升级 Electron 能有所改善了，我们先关闭了，谢谢。
