### ISSUE TITLE
底栏的内容会超出

### ISSUE THREAD

**Issue by chenshinshi** [siyuan-note/siyuan#9853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

默认主题可以复现
![5a09df0b26ed3be3c9d6a40813da7578](https://github.com/siyuan-note/siyuan/assets/125173405/88892402-a4d9-46a3-8b1d-f246e772aa70)

### Expected result

希望修复，似乎是2.10.16版本以来就有的问题

### Version environment

```markdown
- Version: 2.11.1
- Operating System: 
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
请提供一下重现步骤，谢谢。

**Comment by Vanessa219** [comment]
是不是主题或插件问题导致，我这里是正常的  
<img width="785" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/45001daa-549b-46e5-8d1f-a78b3f8e4602">

**Comment by chenshinshi** [comment]
确实是插件的问题，但没搞明白咋冲突的，回头和插件作者反馈下，谢谢v姐
