### ISSUE TITLE
反向链接的冗余信息太多了，怎么解决？

### ISSUE THREAD

**Issue by asasn** [siyuan-note/siyuan#9858]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/48091517/31919005-1041-46cb-a74e-e72ec586153a)

看这图，几乎就是
信息1111111
信息1111111
信息2222222
信息2222222
信息3333333
信息3333333

### Describe the optimal solution

**有没有什么办法能够屏蔽或者改良多余的信息？比如设置，css之类？**

**Comment by Temacc0531** [comment]
关联#7296

**Comment by 88250** [comment]
面包屑目前还是有必要保留的，否则较为复杂的情况无法快捷跳转和预览。

暂时没有更好的方案了，自定义 CSS 的话可能可以解决部分问题，我关闭 issue 了，谢谢。

**Comment by 88250** [comment]
后续改进见 https://github.com/siyuan-note/siyuan/issues/12862
