### ISSUE TITLE
Enable or disable all CSS and JS code snippets

### ISSUE THREAD

**Issue by Vanessa219** [siyuan-note/siyuan#9860]
为 CSS / JS 代码片段添加禁用和启用所用片段功能
https://ld246.com/article/1702140066419

**Comment by littlecoby** [comment]
要不要再加个导出所有片段的功能？方便编辑和备份。现在设置里的浏览区域只有一两行，不大方便编辑。

**Comment by luo-chuan** [comment]
建议做成安全模式

**Comment by chenshinshi** [comment]
> 要不要再加个导出所有片段的功能？方便编辑和备份。现在设置里的浏览区域只有一两行，不大方便编辑。

其实可以拉长的，你把鼠标挪到浏览区域的右下角

**Comment by 88250** [comment]
> 建议做成安全模式

这个不一样，一键关闭的话主要是为了某些情况下方便定位问题。安全模式之前有个 issue https://github.com/siyuan-note/siyuan/issues/8369

**Comment by littlecoby** [comment]
> > 要不要再加个导出所有片段的功能？方便编辑和备份。现在设置里的浏览区域只有一两行，不大方便编辑。
> 
> 其实可以拉长的，你把鼠标挪到浏览区域的右下角

原来是这样

**Comment by luo-chuan** [comment]
> 这个不一样，一键关闭的话主要是为了某些情况下方便定位问题。安全模式之前有个 issue #8369

感觉和我想的不是一回事。我的意思是用户自己玩CSS或者JS容易把软件玩崩，比如把所有div都display:none之类的，想撤销都不行了，因为按钮都不显示了。这时候就需要通过安全模式来重启思源，也就是启动时禁用所有代码片段和插件，然后用户自行删除有问题的代码片段和插件。
在PC端，可以通过命令行带参数启动，就像这样“siyuan.exe -safe”。 安卓端的话，就在桌面 APP 图标位置增加长按选项来安全启动，并且可以通过伺服，在浏览器中带 url 参数来安全启动，比如"?safe=true"。

**Comment by 88250** [comment]
@luo-chuan 这样太复杂了，如果出现这样的问题，PC 端最简单的方案应该是直接移走 工作空间/data/snippets/conf.json 就行了，移动端的话靠数据同步。
