### ISSUE TITLE
请问能否增加在线OCR功能

### ISSUE THREAD

**Issue by pisceswb** [siyuan-note/siyuan#9861]
### In what scenarios do you need this feature?

tesseractOCR使用具有一定的门槛，且对含有底色的图片识别效果极其差，几乎完全不能识别。如果在PDF文件中加底色标注了一句话，将其截图到思源笔记中，识别内容几乎不具有任何参考或搜索价值。

### Describe the optimal solution

增加百度在线OCR功能

### Describe the candidate solution

谢谢

### Other information

谢谢

**Comment by 88250** [comment]
目前暂时没有计划，后续如果有会重开 issue，感谢提议。

**Comment by pisceswb** [comment]
尝试使用百度ocr直接识别assets文件夹中的图片，将得到的文本内容写入ocr-texts.json中，然后在思源笔记中重建索引，发现思源笔记中的图片ocr内容并没有改变，方法不可行。
请问D大这样具有可行性吗？能否指导一下怎样可行，谢谢！
目的是为了搜索图片中的内容🙏

**Comment by 88250** [comment]
应该是可行的，你试下重建索引。

**Comment by pisceswb** [comment]
我可能知道是哪儿的问题了，重建索引后再次打开ocr-texts.json，图片重新被识别回了原来的不正确内容。可能把tesseractOCR卸载了就好了，我试一下。谢谢D大

**Comment by pisceswb** [comment]
关闭了tesseractOCR还是不行。好像重建索引的时候，会优先把思源笔记图片ocr框中的内容复制到ocr-texts.json中进行替换，而不是把ocr-texts.json中的内容复制到思源笔记的图片中

**Comment by 88250** [comment]
我这里测试没有禁用 TesseractOCR，外部修改 ocr-texts.json 后再启动思源，然后重建索引，可以搜索到修改以后的数据。

你看下是不是同步或者什么其他情况覆盖了 ocr-texts.json 了，正常情况这个文件只有 OCR 或者在图片上右键手动设置 OCR 结果的时候才会写入的。

**Comment by pisceswb** [comment]
关闭思源，修改ocr-texts.json，重启思源，没有重建索引就可以了，感谢感谢！👍
