### ISSUE TITLE
.md 内链跟随系统设置

### ISSUE THREAD

**Issue by scvoet** [siyuan-note/siyuan#987]
### 描述问题 Describe the problem

.md 内链打开跟随了我系统的设置由 vscode 打开，而非使用思源打开。

### 期待的结果 Expected result

由思源打开并至新页签。

### 版本环境 Version environment

* 版本 Version：0.5.8
* 操作系统 Operating system：Windows 10 （20H2）
* 浏览器（如果使用）Browser (if used)：

**Comment by 88250** [comment]
你好，`[foo](bar)` 的链接会调用默认的程序打开，即使是 .md。
