### ISSUE TITLE
导入typora markdown，调整过比例的图片会丢失

### ISSUE THREAD

**Issue by wlthat092** [siyuan-note/siyuan#9871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

typora编写的markdaown，里面有修改过显示比例的图片，导入思源后图片会丢失
![image](https://github.com/siyuan-note/siyuan/assets/38549218/8050a47f-2637-4aa5-8b46-6bfe4462a938)
typora如下
![image](https://github.com/siyuan-note/siyuan/assets/38549218/baa740d3-516d-4b97-855f-a855e3dc9daf)

### Expected result

可以正确导入

### Version environment

```markdown
- Version: 2.11.1
- Operating System: windows
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13663158/siyuan.log)

**Comment by 88250** [comment]
这个不是标准 Markdown 的图片语法，目前无法兼容，见谅。
