### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by adocampo** [siyuan-note/siyuan#9872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

On the default theme I cannot see a lot of icons, many of them are just a square and other are simply empty

### Expected result

I should be able to see the icons 

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/2266612/bcb8b7fd-3a30-4cee-aefe-5dcb34328c18)

### Version environment

```markdown
- Version: 2.11.1
- Operating System: Arch Linux
- Browser (if used):
```

### Log file

```
I 2023/12/14 01:12:46 working.go:145: 
      ___                                   ___           ___           ___
     /  /\        ___           ___        /__/\         /  /\         /__/\
    /  /:/_      /  /\         /__/|       \  \:\       /  /::\        \  \:\
   /  /:/ /\    /  /:/        |  |:|        \  \:\     /  /:/\:\        \  \:\
  /  /:/ /::\  /__/::\        |  |:|    ___  \  \:\   /  /:/~/::\   _____\__\:\
 /__/:/ /:/\:\ \__\/\:\__   __|__|:|   /__/\  \__\:\ /__/:/ /:/\:\ /__/::::::::\
 \  \:\/:/~/:/    \  \:\/\ /__/::::\   \  \:\ /  /:/ \  \:\/:/__\/ \  \:\~~\~~\/
  \  \::/ /:/      \__\::/    ~\~~\:\   \  \:\  /:/   \  \::/       \  \:\  ~~~
   \__\/ /:/       /__/:/       \  \:\   \  \:\/:/     \  \:\        \  \:\
     /__/:/        \__\/         \__\/    \  \::/       \  \:\        \  \:\
     \__\/                                 \__\/         \__\/         \__\/
I 2023/12/14 01:12:46 runtime.go:74: kernel is booting:
    * ver [2.11.1]
    * arch [amd64]
    * os [arch]
    * pid [137820]
    * runtime mode [prod]
    * working directory [/usr/lib/siyuan-note]
    * read only [false]
    * container [std]
    * database [ver=20220501]
    * workspace directory [/home/malevolent/SiYuan]
I 2023/12/14 01:12:46 conf.go:253: upgraded from version [2.11.0] to [2.11.1]
I 2023/12/14 01:12:46 conf.go:382: OpenAI API enabled
    baseURL=https://api.openai.com/v1
    timeout=30s
    proxy=
    model=gpt-3.5-turbo
    maxTokens=0
I 2023/12/14 01:12:46 runtime.go:128: use network proxy [system]
I 2023/12/14 01:12:46 serve.go:119: kernel [pid=137820] http server [127.0.0.1:38591] is booting
I 2023/12/14 01:12:46 tesseract.go:166: tesseract-ocr enabled [ver=5.3.3, maxSize=2.0 MB, langs=osd+spa]
I 2023/12/14 01:12:46 blocktree.go:494: read block tree [600 kB] to [/home/malevolent/SiYuan/temp/blocktree], elapsed [0.00s]
I 2023/12/14 01:12:46 conf.go:735: database size [7.0 MB], tree/block count [65/2049]
I 2023/12/14 01:12:46 working.go:183: kernel booted
I 2023/12/14 01:12:46 box.go:79: auto stat [trees=11, blocks=284, dataSize=7.5 MB, assetsSize=4.4 MB]
I 2023/12/14 01:12:46 disk.go:33: disk usage [total=3.9 TB, used=3.0 TB, free=723 GB]
I 2023/12/14 01:12:46 index.go:133: rebuilt database for notebook [20210808180117-6v0mkxr] in [0.01s], tree [count=61, size=1.1 MB]
I 2023/12/14 01:12:47 serve.go:132: reverse proxy server [127.0.0.1:6806] is booting
I 2023/12/14 01:12:47 pandoc.go:155: initialized built-in pandoc [ver=, bin=/home/malevolent/SiYuan/temp/pandoc/bin/pandoc]
I 2023/12/14 01:12:47 conf.go:957: pandoc initialized, set pandoc bin to [/home/malevolent/SiYuan/temp/pandoc/bin/pandoc]
```

### More information

I've installed siyuan from arch linux AUR, package `siyuan-note-bin` , version 2.11.0 and the problem still continues on version 2.11.1

**Comment by Temacc0531** [comment]
应该是系统缺少Emoji字体导致，集市里面下载一个Emoji表情插件试试

**Comment by 88250** [comment]
Please try to install Emoji fonts, or use the Emoji plugin from the community market, thank you.

**Comment by adocampo** [comment]
Yeah, that did the trick.
Thank you!

**Comment by siysuy** [comment]
For those on linux based Operating systems a helpful guide when emoji's are not rendered as expected:
1. Make sure Fontconfig library is installed
2. Simply rescan/update font cache using `fc-cache` command. Run the command withour arguments to rescan all font directories on the system or point it to one of the below folders:
- /usr/share/fonts
- /usr/share/X11/fonts/Type1
- /usr/share/X11/fonts/TTF
- /usr/local/share/fonts
- ~/.fonts
3. Additional step using `fc-list` command to check if a specific font is installed on the system


```
sudo apt update && sudo apt upgrade -y && sudo apt install fontconfig -y
fc-cache /path/to/font-folder
fc-list | grep 'Noto Color Emoji'	
```

I had this emoji render issue on siyuan version 3.0.0 and 3.0.4, but this issue is not related to siyuan, rather it is related to an issue on the operating system. Above commands solved issue without having to download and install new emoji fonts on system or inside siyuan's Market Place.
