### ISSUE TITLE
修改表格导致块被删除

### ISSUE THREAD

**Issue by AlvinCR** [siyuan-note/siyuan#9873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

web端表格无法修改，修改任何内容直接会导致表格被删除。使用windows本地安装的则没有这个问题，但是web同步过去之后再进行"将网络图片转化成本地"操作后，表格同样会被删除。(已禁用所有插件)

### Expected result

正常使用web端表格，而不出现丢失情况

### Version environment

```markdown
- Version: 
- Operating System:  
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13667077/siyuan.log)

**Comment by 88250** [comment]
你好，请使用最新版，应该已经修复。

**Comment by AlvinCR** [comment]
你好，我使用的是最新版界面，v2.11.1，问题仍没有解决
![image](https://github.com/siyuan-note/siyuan/assets/77268542/dd84d17d-db70-4a81-8e36-333f0684db5c)

**Comment by 88250** [comment]
麻烦录屏演示一下操作。

**Comment by AlvinCR** [comment]
您好，经测试发现：
1.web端直接使用/table创建的表格修改，并没有出现异常
2.将excel中的表格复制过来，然后在web端修改会直接清除，但是windwos端没有问题
请问是否出现过此类BUG，如果没有我录一下视频

**Comment by 88250** [comment]
麻烦录屏并上传一下 Excel 以便测试。
