### ISSUE TITLE
安卓端闪卡复习加入复习手势

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9876]
### In what scenarios do you need this feature?

正面左右滑显示背面，背面往左滑功能为点击第一个按钮，右滑为点击第三个按钮。具体功能可以参考ankidroid

### Describe the optimal solution

安卓端闪卡复习加入复习手势，手机端复习起来总体而言比较难受，现在各种复习软件都加入了手势来便利复习的过程，这也说明复习手势是一个必要的功能。希望早日添加。

**Comment by 88250** [comment]
暂时不考虑了，感谢提议。

**Comment by Aiviokoo** [comment]
思源闪卡功能的持续进步得多仰仗老铁的反馈啦（冷知识：提的人多了官方很可能就考虑了），加油👏，感谢老铁的反馈

**Comment by QQQOrange** [comment]
> 思源闪卡功能的持续进步得多仰仗老铁的反馈啦（冷知识：提的人多了官方很可能就考虑了），加油👏，感谢老铁的反馈

笔芯
