### ISSUE TITLE
Support using `Space` and `Enter` for spaced repetition `Good` scoring

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9878]
希望电脑端闪卡页面有类似anki的按键逻辑

### In what scenarios do you need this feature?

大概就是space和enter在卡片正面按下，都能够呈现卡组的背面。而在卡组的背面点击这两个按键，功能都是触发第三个按钮，这是anki长期以来的逻辑。

### Describe the optimal solution

很多的闪卡用户都是有着长期的anki使用经历的。而anki和supermemo都是长期存在这样的操作逻辑的。这也说明这样的操作逻辑，是符合直觉，并且长期为人们所接受的，我当然可以使用anki而抛弃思源，但首先思源笔记的渐进阅读功能非常优秀，并且简易。其次在于，思源的使用更加的符合直觉。也是希望能够在一些小的瑕疵上予以修改。

**Comment by 88250** [comment]
> 功能都是触发第三个按钮

麻烦说下“第三个按钮”指的是？

**Comment by QQQOrange** [comment]
指的是良好按钮

**Comment by 88250** [comment]
收到，我们后续考虑下看看，谢谢。
