### ISSUE TITLE
使用 insertBlock 插入md  `## [ ] title ` 无法如预期显示多选框

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#9880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

使用 insertBlock 插入md  `## [ ] title ` 无法如预期显示多选框
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/6f2a4f3a-ee9c-4ec7-be0b-7bdca0e6ef2c)

### Expected result

在编辑器内按顺序输入  `## [ ] title `  是可以正常工作的
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/24330a33-2f3e-47eb-b794-e839a25f7351)

### Version environment

```markdown
- Version:  v2.11.1
- Operating System: windows
- Browser (if used):
```

### Log file

无需

**Comment by 88250** [comment]
使用 `* [ ] # foo`。
