### ISSUE TITLE
提供刷新文档的 api

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#9881]
### In what scenarios do you need this feature?

当插件使用  insertBlock 之类的 api 修改了已打开的文档，无法在SiYuan中查看到修改，需要刷新才能看到

### Describe the optimal solution

提供api可以将已打开的文档进行刷新，例如 updatePageAll 、updatePage（pageID）

**Comment by 88250** [comment]
正常情况下内核 API 调用完界面会自动同步的，主动刷新的话暂时不考虑了，除非是前端发起的整个界面 reload，用前端 API。

**Comment by 88250** [comment]
我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by 2234839** [comment]
> 正常情况下内核 API 调用完界面会自动同步的，主动刷新的话暂时不考虑了，除非是前端发起的整个界面 reload，用前端 API。

感觉很慢，我先用用一些前端hack吧
