### ISSUE TITLE
Completes the missing move up button on mobile

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9882]
移动端缺少上移块按钮

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

应该还有个上移块的按钮
![7432103ddcf2a75f52aa6870576a2e6](https://github.com/siyuan-note/siyuan/assets/67137548/bf7b1e05-6734-44b2-893c-7684dfb4796c)

 当为列表块时，该按钮才会显示

![fb5c030c2c4a6de3977ea5e33173d69](https://github.com/siyuan-note/siyuan/assets/67137548/338699b6-c147-4d9b-bad6-203d20400fa9)

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by Jiangshuon** [comment]
@Vanessa219 另外大佬，按钮顺序似乎不合理，块菜单按钮明显比块移动按钮更为常用。
但是现在顺序在后面，导致当为列表块时，需要左滑才能冒出来

![ee8b87484d22eff2ef1a0551f021c0f](https://github.com/siyuan-note/siyuan/assets/67137548/470954a1-ea54-4fe7-b951-55ae61960006)

**Comment by Vanessa219** [comment]
确实，把它调整到添加后面。
