### ISSUE TITLE
siyuan v2.11.2 docker版本无法正常启动

### ISSUE THREAD

**Issue by benz9527** [siyuan-note/siyuan#9883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/109717800/cd4744d4-0387-4b23-b481-4e7ebaa6560c)

### Expected result

docker版本正常启动

### Version environment

```markdown
- Version: v2.11.2
- Operating System: Docker alpine
- Browser (if used):
```

### Log file

exec /opt/siyuan/kernel: no such file or directory

**Comment by 88250** [comment]
刚刚打包的最新镜像应该已经修复。

**Comment by benz9527** [comment]
这么快
