### ISSUE TITLE
同步实在是太慢了

### ISSUE THREAD

**Issue by HumanMus1c** [siyuan-note/siyuan#9889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

已经同步数据快照，耗时50.89s
![image](https://github.com/siyuan-note/siyuan/assets/46023154/85a01c06-7fa1-4281-a491-95b85d113ba1)

### Expected result

希望可以改进一下云同步，我直接访问Webdav服务器把数据下载下来都比这快

### Screenshot or screen recording presentation

![image](https://github.com/siyuan-note/siyuan/assets/46023154/5d34b145-2e7e-496c-b12b-b24cd9757007)

### Version environment

```markdown
- Version: v2.11.2
- Operating System: Windows 11 专业版 23H2 22631.2861
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13682146/siyuan.log)

**Comment by 88250** [comment]
从日志上看是当时下载速度太慢，建议看下是不是带宽不够。

**Comment by HumanMus1c** [comment]
> 从日志上看是当时下载速度太慢，建议看下是不是带宽不够。

我用的airliveDrive挂载的同一个webdav接口，本地网络没有开启任何加速器和代理上下行都有至少7MB/s。
![image](https://github.com/siyuan-note/siyuan/assets/46023154/d79547b6-c872-47aa-913d-f2169f886170)

**Comment by 88250** [comment]
单个大文件可能可以跑满，但是思源是非常多的小文件，你可以测试一下这种场景下的情况。

另外，WebDAV 性能本来也不好，能用 S3 的话建议用 S3。
