### ISSUE TITLE
标题块折叠优化

### ISSUE THREAD

**Issue by lss6378** [siyuan-note/siyuan#989]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
- **当前的内容块折叠有两个入口：**
  - 快捷键折叠
  - 通过右键菜单折叠

- 遇到的主要问题是：
  - 快捷键折叠需要一定记忆成本
  - 右键菜单折叠入口较深，需要多步操作，比较繁琐

- **日常使用频率较高的内容块折叠需求：**
  - 标题块的折叠
  - 列表块的折叠
 
> 至于其他类型内容块的折叠，个人的使用频率并不高

### 描述最优的解决方案 Describe the optimal solution

希望增加鼠标折叠入口，类似文件树或者大纲折叠操作：
- 标题块折叠
  - 鼠标靠近标题，显示折叠图标，离开标题，隐藏折叠图标
  - 可折叠显示“V", 可展开显示 “>”
**Obsidian** 的折叠操作
![标题折叠](https://user-images.githubusercontent.com/15924513/104022438-40c18e80-51fb-11eb-9955-263edd111fa3.gif)

**语雀** 的折叠操作
![语雀折叠](https://user-images.githubusercontent.com/15924513/104025386-82eccf00-51ff-11eb-979b-2b1fe442d8d4.gif)

- 列表块折叠
  - 常见议题 https://github.com/siyuan-note/siyuan/issues/961#issuecomment-756752737

- 参考文件树的折叠，内容块的折叠也是类似，标识明确，符合直觉
![文件树折叠](https://user-images.githubusercontent.com/15924513/104022721-a150cb80-51fb-11eb-9fb2-4309eaddde4f.gif)

### 其他信息 Other information
- 思源版本： 0.5.8
- 操作系统：Win10

**Comment by 88250** [comment]
感谢感谢，后面逐步优化。

**Comment by 88250** [comment]
v0.6.6 可以按住 Alt 来折叠了，欢迎试试，我关闭了，谢谢。

**Comment by lss6378** [comment]
> 
> 
> v0.6.6 可以按住 Alt 来折叠了，欢迎试试，我关闭了，谢谢。

试了一下，目前 Alt  + 点击的方式，还挺方便 ^_^
