### ISSUE TITLE
Create doc failed on Linux

### ISSUE THREAD

**Issue by yunyouu** [siyuan-note/siyuan#9890]
创建下级失败，排除过当前数据以及插件问题。

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Docker 自部署版本创建下级失败，排除过当前数据以及插件问题。使用 docker 新建了一个空实例，直接点击也会导致崩溃。
<img width="550" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/6478ae42-79a1-44b5-870f-4ec410726037">

<img width="1339" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/30b7778f-1386-48e2-a8ca-3f9aad5134d3">

### Expected result

希望可以正常新增页面。

### Version environment

```markdown
- Version: 
v2.11.2
- Operating System: 
MacOS 14.2
- Browser (if used):
Chrome 120
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13682485/siyuan.log)

**Comment by InEase** [comment]
docker容器给了权限嘛？参考帮助文档：`/请从这里开始/通用操作/Docker 伺服`

> ## 用户权限
> 
> 镜像中是使用默认创建的普通用户 `siyuan`（uid 1000/gid 1000）来启动内核进程的，所以在宿主机创建工作空间文件夹时请注意设置该文件夹所属用户组：`chown -R 1000:1000 /siyuan/workspace`，在启动容器时需要带参数 `-u 1000:1000`。

**Comment by 88250** [comment]
从日志上可能是工作空间数据卷挂载不正确导致的。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by yunyouu** [comment]
> docker容器给了权限嘛？参考帮助文档：`/请从这里开始/通用操作/Docker 伺服`
> 
> > ## 用户权限
> > 镜像中是使用默认创建的普通用户 `siyuan`（uid 1000/gid 1000）来启动内核进程的，所以在宿主机创建工作空间文件夹时请注意设置该文件夹所属用户组：`chown -R 1000:1000 /siyuan/workspace`，在启动容器时需要带参数 `-u 1000:1000`。

我核对了下，文件权限是正常的。

**Comment by 88250** [comment]
请试试重建索引以后能否重现问题。

**Comment by yunyouu** [comment]
> 从日志上可能是工作空间数据卷挂载不正确导致的。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏
<img width="625" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/64b2e5da-9973-4d76-9bb2-92669c5b0a98">
<img width="1349" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/e0bf40bf-5384-4673-8611-ae1adbf04343">
使用和上面测试相同的配置，我手动拉去了 2.11.1 到镜像 tag 为 latest 之后再启动起来行为正常了，可以加页面了。
<img width="1048" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/cdf9821b-2234-4969-a48b-79219d960f8f">
再用 watchertower 保存原来的配置升级到 2.11.2 就会导致这个问题。
<img width="1415" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/4ecdedc0-95c3-4524-843f-826fd7107dcd">
<img width="778" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/73c43093-71c5-4e6e-95f8-b11b86d0df33">

**Comment by yunyouu** [comment]
> 请试试重建索引以后能否重现问题。

重建索引和强制退出都无效，再次操作还会有这个问题。

**Comment by yunyouu** [comment]
> > 请试试重建索引以后能否重现问题。
> 
> 重建索引和强制退出都无效，再次操作还会有这个问题。

看看我还可以提交什么相关的可以帮忙解决这个问题的，谢谢各位了。
目录权限有问题的话我理解应该是所有文件都访问不到，我这个时候 workspace 目录下是有部分文件的。
<img width="943" alt="image" src="https://github.com/siyuan-note/siyuan/assets/32095100/80f74170-12fe-4650-bc55-9480f7151447">

**Comment by 88250** [comment]
能帮忙测试一下桌面版吗？

**Comment by 88250** [comment]
好的，那再看看 docker 部署的情况。试下新建笔记本后新建文档。

**Comment by 88250** [comment]
我这里目前可以在 Linux 上重现问题了。

**Comment by 88250** [comment]
Fixed in 0547f278399bd09681fd74603c6743c7ce471cdd
