### ISSUE TITLE
编辑某些旧文档时换行相关的操作会触发翻页

### ISSUE THREAD

**Issue by heheda123123** [siyuan-note/siyuan#9891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

录了个视频如下
对于某些旧文档，只要回车，或者删除换行，都会触发翻页，普通输入文本不会翻页
我进行了如下测试
1 新建一个文档，复制这个文档的全部内容过去，不会有这种bug
2 找其他老文档，也不会触发这个bug
[1702629432828.zip](https://github.com/siyuan-note/siyuan/files/13683009/1702629432828.zip)

### Expected result

不翻页

### Version environment

```markdown
- Version: 2.11.2
- Operating System: windows 11
- Browser (if used):
```

### Log file

应该不用

**Comment by heheda123123** [comment]
目前的解决方法是把全部内容复制到一个新建的文档里面
不过还发现一个奇怪的现象
原文档 ，字符数5208 ，字数1340 链接3
![image](https://github.com/siyuan-note/siyuan/assets/97490782/48e71608-6499-40f3-a3e5-7be565ce57db)
新文档，内容一样，字符数7124，字数1917 链接5
![image](https://github.com/siyuan-note/siyuan/assets/97490782/6bc8e922-1e37-45dd-b900-389effe98636)

**Comment by Vanessa219** [comment]
可以把这个能重现的老文档发一下么？我导入看看是否能重现。谢谢

**Comment by Vanessa219** [comment]
过 16s 后输入还会这样么？

**Comment by heheda123123** [comment]
> 可以把这个能重现的老文档发一下么？我导入看看是否能重现。谢谢

我去，我刚删了。不过我又找到另一个文档有这个问题
[msys2.sy.zip](https://github.com/siyuan-note/siyuan/files/13683283/msys2.sy.zip)

**Comment by heheda123123** [comment]
咦，不过msys2这个文档我导出之后又无法复现了，我也不知道是导出过，还是过了一段时间造成的
不过之前那个文档，等了很长的时间也还是存在这个问题，我再找找其他文档有没有这个情况的

**Comment by heheda123123** [comment]
咦，还真是，我又找到一个文档有这个bug。不过过了差不多十几秒之后就没这个情况了

**Comment by Vanessa219** [comment]
哦，那我知道了。上个版本改进过，由于图片、图表、数学公式等加载会导致才打开的页面定位不准确，所以 16s 内高度变化的话都会重新定位。我把时间再缩短一点看看吧。主要想着才打开没有人会回车或删除之类的操作。

**Comment by Geo123abc** [comment]
这个bug有点紧急啊，很影响编辑

**Comment by Vanessa219** [comment]
动态滚动的时候是有一点问题，感谢反馈，马上进行处理。

**Comment by IAliceBobI** [comment]
@Vanessa219   `v2.11.3`

现在还有这个问题。但我也不知道规律。

回车就往下跳。

一开始以为是自己插件搞的，但禁用全部插件后依然能复现。

下面是复现的步骤，但不是稳定复现。我也不知道规律。

找一个长文档，要分段加载的。
在中上部定位，我是打个空白行。
关闭文档。
ctrl+shift+I , F5
ctrl+e 找到刚才的文档，在之前位置点击。
ctrl+end ， 在末尾几个空行中随便敲个回车。有时会跳到好远上面。

有时ctrl+end后，再用滚轮定位到上面，找个地方敲回车也会跳，向下跳。

总之，就是随意多试试几次。有时随意的：F5，上下滚动，回车组合也触发。不分文档，长的不能一次加载完的就可以。

**Comment by Vanessa219** [comment]
F5 上下滚动: a3ec74f72c07fa360caeb0cec455358a20717e22
回车组合指的是 shift+Enter？
ctrl+shift+I 的功能是？

跳过 ctrl+shift+I  按照上面的步骤操作无法重现。

**Comment by IAliceBobI** [comment]
@Vanessa219 不好意思，没说具体。 ctrl+shift+i 组合  f5就是要重新加载页面。把开发者工具调出而已，在js日志的地方 f5就刷新，重新加载了。

重新加载就是未来从一个新的状态开始尝试。

这个确实不好复现。目前我也找不到规律，先这样，等我发现了告诉您。

**Comment by Vanessa219** [comment]
好的，谢谢。
