### ISSUE TITLE
Breadcrumbs cannot display "_" in Windows

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#9893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem
嵌入块的面包屑无法展示下划线
见截图

### Expected result

能够看见下划线

### Screenshot or screen recording presentation

![图片](https://github.com/siyuan-note/siyuan/assets/28727933/122f82f8-b46e-4341-acb4-548093045ca0)

### Version environment

```markdown
- Version: v2.11.2
- Operating System: windows11
- Browser (if used):
```

### Log file

无用

**Comment by Vanessa219** [comment]
是 `_` 嘛？
<img width="927" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/15830429-73b4-4c89-9cd8-e1503eede80d">

**Comment by 2234839** [comment]
应该不会是有奇怪字符，手机端看着还正常，右侧是从手机端复制粘贴的，： 崮生_子虚
如果你那能正常显示的话，我明天在深入看看是不是其他问题

**Comment by 2234839** [comment]
还有我这个是文档名，不知是否会有这方面的因素

**Comment by Vanessa219** [comment]
字体、缩放、主题什么的有没有设置过？
<img width="560" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/af9ab911-980a-4691-ab7e-0b9dc6dab29f">

**Comment by 2234839** [comment]
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/3c65c126-81ce-43a8-b773-95b07b526554)
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/3495791a-b879-4bac-b57d-f7eaad1ee679)
我一直采用的是默认主题。没有自定义css js
