### ISSUE TITLE
安卓闪卡页面的跳转链接点击无效 电脑可以

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，这个链接指的是思源笔记内部的文档跳转链接

### Expected result

安卓客户端可以跳转

### Version environment

```markdown
- Version: 2.11.2
- Operating System: 安卓
- Browser (if used):edge
```

### Log file

这个日志没有

**Comment by Vanessa219** [comment]
电脑点击会打开新页签，移动端上没有页签。关闭闪卡后编辑器其实已经跳转了。

**Comment by QQQOrange** [comment]
> 电脑点击会打开新页签，移动端上没有页签。关闭闪卡后编辑器其实已经跳转了。

也就是说手机上为了看闪卡引用的文档，就必须在点击后退出闪卡复习页面，看完后文档后，再进入闪卡复习页面复习吗

**Comment by 88250** [comment]
目前是这样的，因为移动端没有多页签。
