### ISSUE TITLE
Find replace supports selecting element types

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9895]
* text, imgText, imgTitle, imgSrc, aText, aTitle, aHref, code, em, strong, inlineMmath, inlineMemo, kbd, mark, s, sub, sup, tag, u
* docTitle, codeBlock, mathBlock, htmlBlock

**Comment by mozhux** [comment]
I hope these options can be sorted in two columns, making good use of space
![image](https://github.com/siyuan-note/siyuan/assets/46953371/e2b9ffc7-6d66-4c07-83cd-7bd1065a64ec)
