### ISSUE TITLE
在内容块中未选中文本按Ctrl+C复制会全选块复制

### ISSUE THREAD

**Issue by HopeLHP** [siyuan-note/siyuan#9897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在内容块中未选中文本按Ctrl+C复制会全选块复制，这样会干扰剪贴板。
有时候未选中状态是想要执行Ctrl+V粘贴但是不小心按到了+C导致变成了复制整个块到我的剪贴板，这样我按错一步就得导致我回去重新复制再粘贴或者打开我的剪贴板选择历史剪贴板粘贴。

### Expected result

未选中文本复制不应该多此一举帮用户复制

### Version environment

```markdown
- Version: 2.11.1
- Operating System: win11
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13691728/siyuan.log)

**Comment by 88250** [comment]
目前是设计如此，谢谢。

**Comment by HopeLHP** [comment]
可以请教一下此设计的目的或初衷吗？设计此特性是基于广大用户的需求吗？他的外部性什么，正外部性能抵消负外部性吗？
作为用户，还是想了解一下开发者的思路。

**Comment by 88250** [comment]
方便复制块，不用选择就可以复制整个块。

**Comment by HopeLHP** [comment]
。。。好吧。。。
这个操作不符合操作直觉，未选择内容就能复制出内容不太符合习惯吧。
Ctrl+A再加C就能复制整个块，鼠标点击三下就能全选整个块，很多其他办法就能复制整个块。
我只能说建议如果新增一个特性，会产生负面效果，请多考虑这个特性的需求用户面和实际使用频次。

**Comment by frostime** [comment]
> 。。。好吧。。。 这个操作不符合操作直觉，未选择内容就能复制出内容不太符合习惯吧。 Ctrl+A再加C就能复制整个块，鼠标点击三下就能全选整个块，很多其他办法就能复制整个块。 我只能说建议如果新增一个特性，会产生负面效果，请多考虑这个特性的需求用户面和实际使用频次。

这个其实在编程 IDE 里面很常见，很多 IDE 就是 Ctrl +C 不选择任何东西就默认复制一整行代码，我觉得可能是源自这个习惯。

**Comment by 88250** [comment]
当设计上出现不确定的时候，最稳妥的方案就是借鉴成功产品，比如 Notion :trollface:

**Comment by HopeLHP** [comment]
> 这个其实在编程 IDE 里面很常见，很多 IDE 就是 Ctrl +C 不选择任何东西就默认复制一整行代码，我觉得可能是源自这个习惯。

@frostime 我一般是用vim或quicker扩展热键实现全键盘选词选段操作，我倒是觉得代码的编辑逻辑和笔记软件的文字编辑逻辑不太相同，代码复制很多情况可能是一整句才是有用的，且有些语句的重复性比较高，而笔记软件的内容是复杂的，我个人认为两者不能直接套。


> 当设计上出现不确定的时候，最稳妥的方案就是借鉴成功产品，比如 Notion :trollface:

@88250 当设计产品最初的时候，最稳妥的方案是“借鉴”成功产品。但毕竟成功产品也有槽点，所以当设计出现不确定的时候，最稳妥的方案是实践和调查，从群众中来到群众中去。

---
当然说远了，我只是提了建议，你们听到了考虑过了，这就足够了。
