### ISSUE TITLE
Attribute View adds addAttributeViewRow API

### ISSUE THREAD

**Issue by RainBoat** [siyuan-note/siyuan#9898]
### In what scenarios do you need this feature?

在开发文档模板的时候，希望能够直接在套用模板时将该文档与指定数据库实现双向挂载，现在通过查询custom-avs和getAttrtibuteViewKey仅能够实现查询当前文档是否挂载至某个数据库及对应字段值，但没有办法同步实现在数据库中挂载某个block

### Describe the optimal solution

增加将块插入行的API

**Comment by 88250** [comment]
需要插入块到数据库中吗？

**Comment by RainBoat** [comment]
sorry表述有误，是行

**Comment by 88250** [comment]
目前还无法提供数据库相关的 API，因为目前数据库特性还在开发中，API 无法保证稳定。如果你需要开发插件相关需求的话可以试试 transaction 相关的内部 API，不过建议暂时还是不要搞，维护起来比较麻烦。

我先关闭了，等后期数据库上线后一段时间较为稳定了我们再考虑提供 API，谢谢。
