### ISSUE TITLE
数据库多视图功能不正常工作

### ISSUE THREAD

**Issue by andyer1511** [siyuan-note/siyuan#9899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

点击数据库多视图添加按钮，会复制前一个数据库，而不是新建视图。

### Expected result

点击数据库多视图添加按钮，生成新的空白的数据库。

### Version environment

```markdown
2.11.2
win10 ltsc
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13692083/system-log.zip)

**Comment by royc01** [comment]
多视图是指同一个数据库的多种视图，如果需要新的数据库需要另开一个库。

**Comment by andyer1511** [comment]
是2.11.1新增的功能 #9751

[20231216174600.webm](https://github.com/siyuan-note/siyuan/assets/18610532/879d3eef-9484-4120-a708-9a61c6aabcf5)

**Comment by royc01** [comment]
我是说同一个数据库添加视图，肯定是复制前面的表格数据啊，用于不同的排列筛选，不会是空白的，现在是没有其他种类的视图。

**Comment by andyer1511** [comment]
好的那我理解错了
