### ISSUE TITLE
小优化：标签补全提示

### ISSUE THREAD

**Issue by deerainw** [siyuan-note/siyuan#990]
是一个干扰我比较久的问题，当我想写一个一级标题，于是我在行首打下一个 `#` 号，此时标签补全列表弹出。

但因为我实际上是想写一级标题，所以我又打一个空格，但此时标签补全列表继续存在：

![image](https://user-images.githubusercontent.com/32661922/104021342-8f6e2900-51f9-11eb-80d9-efd6e6ad5203.png)

我觉得此时已经不该再继续显示标签补全列表了，因为这个空格已经表明了接下来要输入的是标题而不是标签。

包括在输入 3 级标题的时候，前面已经有 3 个 `#` 号，标签补全列表也一直存在：

![image](https://user-images.githubusercontent.com/32661922/104021712-30f57a80-51fa-11eb-8040-b2dba92a0d18.png)

标题的输入很频繁，而且肯定比标签更频繁，所以我感觉现在标签补全列表的显示干扰很大。标签的补全列表什么时候出现，我觉得可以参考 obsidian 和 zettlr 的编辑器：

情形1、如果 `#` 在行首且光标紧随其后，就显示标签补全列表，继续打个空格就不再显示

![image](https://user-images.githubusercontent.com/32661922/104022590-75cde100-51fb-11eb-8033-0266588e00bd.png)

情形2、如果 `#` 不在行首，那 `#` 号的前面得有个空格才行，否则不把它视作标签的起始；打空格后补全列表应该消失
![image](https://user-images.githubusercontent.com/32661922/104023012-03113580-51fc-11eb-87f0-466d07c815b0.png)

---

补充一个问题，懒得新开一个 issue 了 😂 ，在给上面截图的时候，发现一个标签补全列表的搜索问题，比如有一个标签叫 `注意事项`，在搜索过滤的时候，只有输入 `注` `注意` `注意事` 这些开头文字才能把这个标签搜出来，如果用的时候只想起了 `事项` 这个关键词就没法把 `注意事项` 搜出来：

![image](https://user-images.githubusercontent.com/32661922/104023695-fb9e5c00-51fc-11eb-94f3-f81d6d5c0275.png)

![image](https://user-images.githubusercontent.com/32661922/104023740-0b1da500-51fd-11eb-8069-e3f08e994700.png)

**Comment by 88250** [comment]
的确这个问题很干扰打字，类似的补全候选列表问题还会出现在代码块、公式块等地方。但是标题和标签的问题是最为明显的，我们尽量先解决一下标题和标签的问题。

后面的搜索匹配问题也会一起改进，谢谢。
