### ISSUE TITLE
闪卡管理里面有批量管理功能，最好还能一页显示所有闪卡

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9901]
### In what scenarios do you need this feature?

经常会出现不符合格式的闪卡，这样的卡留着没意义，要删掉，但是现在的删除流程非常繁琐，要一张一张的删除，如果有批量处理功能就太好了。最好还能一键删除所有不符合格式的闪卡

### Describe the optimal solution

经常会出现不符合格式的闪卡，这样的卡留着没意义，要删掉，但是现在的删除流程非常繁琐，要一张一张的删除，如果有批量处理功能就太好了。最好还能一键删除所有不符合格式的闪卡

**Comment by 88250** [comment]
这个暂时不考虑更改了，因为对于删除来说，批量也是要选择的，选择的点击和直接删除点击差别不大。

另外分页也是必须的，否则界面可能会卡。

**Comment by QQQOrange** [comment]
> 这个暂时不考虑更改了，因为对于删除来说，批量也是要选择的，选择的点击和直接删除点击差别不大。
> 
> 另外分页也是必须的，否则界面可能会卡。

那可以出现一键删除失效卡片的功能吗

**Comment by 88250** [comment]
> 那可以出现一键删除失效卡片的功能吗

不考虑了，谢谢。
