### ISSUE TITLE
闪卡复习页面的这个漏斗可以按照文档来筛选

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9903]
### In what scenarios do you need this feature?

图中数字旁边的那个按钮，点击后就是筛选卡包，当卡包功能没开的时候也是这样，能不能改为筛选制作闪卡的文档呢。
例如我在文档a中制作了100张闪卡，再文档b中制作也制作了100张，但有时候只想复习文档a中的闪卡，不想复习文档b中的，这时候就通过这个筛选功能，选定文档a，这样就可以只复习文档a中的闪卡了。

### Describe the optimal solution

图中数字旁边的那个按钮，点击后就是筛选卡包，当卡包功能没开的时候也是这样，能不能改为筛选制作闪卡的文档呢。
例如我在文档a中制作了100张闪卡，再文档b中制作也制作了100张，但有时候只想复习文档a中的闪卡，不想复习文档b中的，这时候就通过这个筛选功能，选定文档a，这样就可以只复习文档a中的闪卡了。

### Describe the candidate solution

![image](https://github.com/siyuan-note/siyuan/assets/62794181/4325a97f-1cb8-47f3-bd89-1ee89bdd5019)

**Comment by mozhux** [comment]
这个点开不是有文档树的吗

**Comment by QQQOrange** [comment]
> 这个点开不是有文档树的吗

我没发现 尴尬 谢谢老哥

**Comment by 88250** [comment]
没问题的话我们关闭了。
