### ISSUE TITLE
多表格视图可以直接拖拽排序

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9906]
### In what scenarios do you need this feature?

建立多个表格视图，设置不同的筛选条件方便快速查看，这时候就有一个需求，可以通过拖拽视图名称，进行排序
![image](https://github.com/siyuan-note/siyuan/assets/60436214/b1a3060c-2156-4a0f-840f-f23d8e97328f)

### Describe the optimal solution

多表格视图可以拖拽排序

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/2c84d119-a107-436d-b526-4a362be6dd94)

先通过这里排序吧。

**Comment by Achuan-2** [comment]
好的

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/11102
