### ISSUE TITLE
搜索面板点击块引关闭搜索面板

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9907]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/60436214/c0ab1f5e-db73-4e35-91bb-315a3f236702)
搜索面板点击文档，搜索面板会自动关闭
然后点击块引，面板是不会自动关闭的，希望搜索面板也能自动关闭
如果用户希望不关闭搜索面板，可以点击【在后台页签打开】

### Describe the optimal solution

搜索面板点击块引关闭搜索面板

**Comment by 88250** [comment]
> 搜索面板点击文档，搜索面板会自动关闭

“点击文档”指的是双击？

**Comment by Achuan-2** [comment]
@88250 是双击，抱歉描述不清楚

**Comment by 88250** [comment]
在编辑预览区点击引用元素的话是后台打开，这个目前不考虑改变了，谢谢。

**Comment by Achuan-2** [comment]
主要除了搜索指定文档外，我的大部分笔记是用Moc来组织的，有时候直接搜索某个笔记不方便，所以常常会去搜索相关话题的Moc笔记，然后再点击块引打开指定的笔记

**Comment by 88250** [comment]
用搜索页签（在新页签中打开）顶顶。

**Comment by Achuan-2** [comment]
好的
