### ISSUE TITLE
Support converting list blocks to paragraphs

### ISSUE THREAD

**Issue by Aiviokoo** [siyuan-note/siyuan#9908]
批量选中多个断开的无序列表（有序列表，任务列表，引述）后不能一次性转换成段落块

### In what scenarios do you need this feature?

有时候想要更方便的把多个断开的列表块合并。【本着万物基于段落块提的（想咋转咋转），因为觉得直接合并断开的列表块（有序列表，任务列表，引述）可能比较难做，如果能直接合并当然更好】

### Describe the optimal solution

![IMG_0371](https://github.com/siyuan-note/siyuan/assets/87182333/541cbf6c-538e-4ee2-9446-2f8e698a4da0)
如果需要把 123,456 也转换成段落块就全选后再转换一次。

**Comment by 88250** [comment]
@Vanessa219 还有个问题，菜单点了不消失

![1f6a9f04e9cd5032bf03bde276aa4d27](https://github.com/siyuan-note/siyuan/assets/873584/b0202137-ddc9-41c9-865e-0b2b88aa057f)

**Comment by Achuan-2** [comment]
@Aiviokoo 多个断开的列表块合并，我用的是剪贴板工具是copyq，在思源里复制多个相邻的列表块，再粘贴copyq的剪贴板，就自动合并了

**Comment by Aiviokoo** [comment]
D 大、V 姐，刚刚我下载了 dev 版，已经用上了，效果还是棒的，感谢，已经基本满足了我的需求。我之前这种的比较多，已经能行啦。❤️
![1703154583489](https://github.com/siyuan-note/siyuan/assets/87182333/cdc26836-cdba-46bd-a469-dbb0d47e9efd)
下面是一些合理但非必须的改进，暂时就不管吧，只是提在这里。
![Snipaste_2023-12-21_17-45-31](https://github.com/siyuan-note/siyuan/assets/87182333/77887f1f-2d94-4d11-8ef2-d338f3ce51b0)
这种复杂的都可以转的目前都可以转的。（因为中间没有夹杂段落块，夹杂着的就不行）
转换前
![1703152701166](https://github.com/siyuan-note/siyuan/assets/87182333/77dcdc3b-bd07-4f0b-8821-f804b4064bca)
转化后
![1703152739458](https://github.com/siyuan-note/siyuan/assets/87182333/e24f38f0-bfa1-49cc-9690-a57c58060b60)

**Comment by 88250** [comment]
收到，暂时就只能这样了，后面看情况，我们可能会重新设计实现类型转换。



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 21, 2023 18:33 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [siyuan-note/siyuan] Support converting list blocks to paragraphs(Issue #9908)




 
D 大、V 姐，刚刚我下载了 dev 版，已经用上了，效果还是棒的，感谢，已经基本满足了我的需求。我之前这种的比较多，已经能行啦。❤️
 1703154583489.png (view on web)
 下面是一些合理但非必须的改进，暂时就不管吧，只是提在这里。
 Snipaste_2023-12-21_17-45-31.png (view on web)
 这种复杂的都可以转的目前都可以转的。（因为中间没有夹杂段落块，夹杂着的就不行）
 转换前
 1703152701166.png (view on web)
 转化后
 1703152739458.png (view on web)
