### ISSUE TITLE
Improve kernel stability

### ISSUE THREAD

**Issue by hscui** [siyuan-note/siyuan#9912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

更新到2.11.2后在三台电脑上均出现此问题：
![图片](https://github.com/siyuan-note/siyuan/assets/7949195/dc635406-e2e6-4015-8bb9-97968006eda3)

已尝试关闭插件，回复默认主题、清空本地与线上数据库（目前使用的是腾讯S3）；均无用

### Expected result

修复BUG

### Version environment

```markdown
- Version: 2.11.2
- Operating System: WIN10，WIN11
- Browser (if used):Firefox
```

### Log file

无法上传；有需要可发一个邮箱。

**Comment by hscui** [comment]
降至2.11.1版后可正常进入，并且重建索引无问题。

**Comment by hscui** [comment]
刚才尝试更新到v202312180011也是一样出现这个问题。

**Comment by 88250** [comment]
抱歉，我们这里无法重现问题。日志可发送至邮箱 845765@qq.com

**Comment by hscui** [comment]
> 抱歉，我们这里无法重现问题。日志可发送至邮箱 [845765@qq.com](mailto:845765@qq.com)

已发送。

**Comment by 88250** [comment]
你好，从两份日志中没有发现相关问题，建议检查一下是否是杀毒软件或者其他程序影响。

另外，可以观察一下内核进程的内存占用情况。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:

**Comment by hscui** [comment]
> 你好，从两份日志中没有发现相关问题，建议检查一下是否是杀毒软件或者其他程序影响。
> 
> 另外，可以观察一下内核进程的内存占用情况。
> 
> 我先关闭了，如果还有问题请继续跟帖，谢谢 🙏

因为在三台不同配置，不同系统（WIN10正常，WIN10精简，WIN11）上均是在重建索引这步出现的问题，是否与我的笔记内容有一定关系？比如某个笔记在重建时触发某个问题导致的；
使用S3与重建索引的关系应该是没有的吧。

**Comment by 88250** [comment]
同步方式不影响。估计需要数据才方便排查了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月18日(周一) 下午2:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 2.11.2版本重建索引后就出现内核因未知原因退出 The kernel exited for unknown reasons；再也无法正常进入 (Issue #9912)




  
你好，从两份日志中没有发现相关问题，建议检查一下是否是杀毒软件或者其他程序影响。
 
另外，可以观察一下内核进程的内存占用情况。
 
我先关闭了，如果还有问题请继续跟帖，谢谢 🙏
  
因为在三台不同配置，不同系统（WIN10正常，WIN10精简，WIN11）上均是在重建索引这步出现的问题，是否与我的笔记内容有一定关系？比如某个笔记在重建时触发某个问题导致的；
 使用S3与重建索引的关系应该是没有的吧。

**Comment by 88250** [comment]
我们定位到一个相关问题，请等 v2.11.4-dev1 发布以后帮忙测试看看，谢谢。

**Comment by hscui** [comment]
> 我们定位到一个相关问题，请等 v2.11.4-dev1 发布以后帮忙测试看看，谢谢。

我也确认是我6月的日记的问题（目前在排查是哪一篇），确认是哪一篇问题后是否需要把日记打包发你一下。

**Comment by 88250** [comment]
还是发一下吧，辛苦了。

**Comment by 88250** [comment]
收到数据集了，已经确认问题，下个 dev 版本就修复，感谢 :heart:

**Comment by 88250** [comment]
766454154d0d63e8e6bd4dd6d6d3f4e69e133d04
