### ISSUE TITLE
数据库中在输入框时，点击新增按钮，无法插入新的行。

### ISSUE THREAD

**Issue by lushan2866** [siyuan-note/siyuan#9913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

详见GIF。
![GIF 2023-12-18 15-12-50](https://github.com/siyuan-note/siyuan/assets/5708881/b90e7aa6-0894-4a5b-a4c6-2bf8af283538)

### Expected result

详见GIF。

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
应该已经修复，方便的话请使用 dev 版测试，我先关闭了，谢谢。

**Comment by lushan2866** [comment]
Get
