### ISSUE TITLE
闪卡复习时文档树可以放置于闪卡复习窗口的旁边

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9915]
### In what scenarios do you need this feature?

原因在于，闪卡复习是所有来源的闪卡混在一起复习的。为了复习时思路的一致性，需要经常在文档树里选择好相应的文档后再复习。
需要复习的文档多了之后，每次点击特别麻烦。
而且特别多的文档都是在层层的子文档下面，选择起来也是十分的费劲。

### Describe the optimal solution

要是可以在闪卡复习的时候旁边就是文档树，复习的时候可以自动定位所在的文档，同时也可以方便的选择想要优先复习的文档。
希望早日补充此功能，也希望思源越做越好

**Comment by 88250** [comment]
可以试试在页签中复习。

![image](https://github.com/siyuan-note/siyuan/assets/873584/4df43264-9027-4928-9c26-dbe1926b7364)

**Comment by QQQOrange** [comment]
> 可以试试在页签中复习。
> 
> ![image](https://private-user-images.githubusercontent.com/873584/291294301-4df43264-9027-4928-9c26-dbe1926b7364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDcyMjksIm5iZiI6MTcwMjkwNjkyOSwicGF0aCI6Ii84NzM1ODQvMjkxMjk0MzAxLTRkZjQzMjY0LTkwMjctNDkyOC05YzI2LWRiZTE5MjZiNzM2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxMzQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjBkNzk1ZmE3OTQwMjJiODFiMGQ5ZmZkMTk1Mjk1M2RkNGEyYTIwNzQ1MzRjNThhYTA5MDZhZWUyMTA5NmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gYshY9yo_X95ti5SPyS1NermI1Bi91wPz3m5M8C19Tg)



> 可以试试在页签中复习。
> 
> ![image](https://private-user-images.githubusercontent.com/873584/291294301-4df43264-9027-4928-9c26-dbe1926b7364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MDcyMjksIm5iZiI6MTcwMjkwNjkyOSwicGF0aCI6Ii84NzM1ODQvMjkxMjk0MzAxLTRkZjQzMjY0LTkwMjctNDkyOC05YzI2LWRiZTE5MjZiNzM2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxMzQyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjBkNzk1ZmE3OTQwMjJiODFiMGQ5ZmZkMTk1Mjk1M2RkNGEyYTIwNzQ1MzRjNThhYTA5MDZhZWUyMTA5NmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gYshY9yo_X95ti5SPyS1NermI1Bi91wPz3m5M8C19Tg)

这并不具有我描述的这种功能

**Comment by 88250** [comment]
不考虑添加新特性了，谢谢。
