### ISSUE TITLE
复制文本进思源，会删除字符

### ISSUE THREAD

**Issue by zy-dys** [siyuan-note/siyuan#9918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

测试文本：minoiasldfja$lskajflkaj$lksajflkaj1231%$lksjaf
复制后的文本：minoiasldfjalskajflkajlksajflkaj1231%\$lksjaf
直接粘贴或者粘贴纯文本都无法正确复制

### Expected result

无

### Version environment

```markdown
- Version: 版本2.11.0 (2.11.0)
- Operating System: macOS 13.5
- Browser (if used):
```

### Log file

百分百复现，无需日志

**Comment by 88250** [comment]
`$` 符号包裹的文本会被解析会行级公式。

**Comment by zy-dys** [comment]
但是只是文本不是公式啊

**Comment by 88250** [comment]
可以试试粘贴纯文本或者转义文本。

**Comment by zy-dys** [comment]
我试过，纯文本粘贴出来少字符，转义文本粘贴出来多了转义斜杠\

**Comment by 88250** [comment]
* 粘贴纯文本就是去掉 Markdown 标记符，只粘贴内容
* 粘贴转义文本我这里测试没有问题 
  ![image](https://github.com/siyuan-note/siyuan/assets/873584/221f1fff-d183-4cce-92ce-147c0c551f99)

**Comment by zy-dys** [comment]
是需要修改什么配置吗，我贴出来不一样
![WX20231219-100854@2x](https://github.com/siyuan-note/siyuan/assets/34826507/9cca0ea9-5110-427b-af62-ab394c4cb1d5)

**Comment by 88250** [comment]
更新最新版试试。

**Comment by zy-dys** [comment]
可以了，感谢大佬！
