### ISSUE TITLE
转义符后面粘贴内容,希望能自动转义

### ISSUE THREAD

**Issue by o-ut-man** [siyuan-note/siyuan#992]
现在转义符后的内容必须手动输入,才会转义 
复制粘贴的内容不会转义,只能手打,很繁琐

**Comment by 88250** [comment]
你好，我没有看明白问题，请稍微详细一点说明，谢谢。

**Comment by o-ut-man** [comment]
比如我要输入纯文本"<h1>"
那么我就需要手动输入"\<h1>"
如果我是先输入“\”，然后在后面复制粘贴“<h1>”，那么<h1>会直接生效，而不是被转义。

所以需要转义的场景，就只能纯手打了

**Comment by 88250** [comment]
你好，纯文本的话如果是需要转义的部分是只能通过手动转义的，这部分似乎没有更好的处理方式了，抱歉。
