### ISSUE TITLE
Add new code snippet at the top

### ISSUE THREAD

**Issue by TCOTC** [siyuan-note/siyuan#9921]
### In what scenarios do you need this feature?

1. 添加代码片段的按钮在最上方，点击后也应该在最上方新增。
2. 代码片段多了之后，每次新增都要翻到最后，每次调试刚加的代码片段都要频繁地划到最后面，不方便。

### Describe the optimal solution

![image](https://github.com/siyuan-note/siyuan/assets/78434827/d214b6e8-5c09-43e7-9313-69c4e4428550)

### Other information

相关：#9860

**Comment by TCOTC** [comment]
> Add a create button at the top of the code snippet settings

这个 issue 的标题是改错了吗？应该是将新增的代码片段移至顶部，而非在顶部新增一个按钮

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/d51376b5-8214-4cd1-9c63-85464f87d5f1)

**Comment by TCOTC** [comment]
这个按钮在上个版本就有了

**Comment by 88250** [comment]
那可能是我改错标题了 @Vanessa219 看一下
