### ISSUE TITLE
希望增加：文章大纲功能、标题自动加入索引功能

### ISSUE THREAD

**Issue by KXO1234** [siyuan-note/siyuan#9922]
### In what scenarios do you need this feature?

有的时候一片文章很长，而想快速定找到想要阅读的片段需要翻很久，可参考typora 在新建标题时，根据标题的级别，自动添加分级标题的序号，然后在右上角或者左上角 悬浮整个文章的大纲。形成具体案例如下图所示：
<img width="1536" alt="image" src="https://github.com/siyuan-note/siyuan/assets/153578040/e213ecaf-9e81-4cf6-8571-65e4f53debc4">

### Describe the optimal solution

有的时候一片文章很长，而想快速定找到想要阅读的片段需要翻很久，可参考typora 在新建标题时，根据标题的级别，自动添加分级标题的序号，然后在右上角或者左上角 悬浮整个文章的大纲。形成具体案例如下图所示：
<img width="1536" alt="image" src="https://github.com/siyuan-note/siyuan/assets/153578040/e213ecaf-9e81-4cf6-8571-65e4f53debc4">

**Comment by KXO1234** [comment]
这样在阅读的过程中，可直接定位到想阅读的章节，大大的提高效率

**Comment by 88250** [comment]
你好，自动标题序号目前暂时不考虑支持，如果有需要可以在集市中找下插件；悬浮大纲可以试下将大纲图片移动到右侧停靠栏，然后取消钉住停靠栏。
