### ISSUE TITLE
文档树展开提议

### ISSUE THREAD

**Issue by muhanstudio** [siyuan-note/siyuan#9924]
### In what scenarios do you need this feature?

在打开级数较深的子文档时，PC打开了太多不需要打开的文档，同样移动端则需要一下一下左滑继续点击才能继续向下展开

### Describe the optimal solution

有时候顺着文档树找子文档，一路上开了一堆其他不需要打开的父文档，希望加一个文档树的展开逻辑，对于没有子文档的文档，单击会直接打开，对于有子文档的文档，单击展开，双击打开

### Describe the candidate solution

希望在将来可以将该逻辑加入可选择的设置项，更有利于树形结构的展开

**Comment by 88250** [comment]
双击的逻辑之前讨论过了，不考虑了，谢谢。
