### ISSUE TITLE
安卓端闪卡设置不会与pc端同步

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

新闪卡数量、复习闪卡数量以及留存率之类的，电脑设置好了，同步后安卓端不会一起同步

### Expected result

能够一起同步

### Version environment

```markdown
- Version: 2.11.2
- Operating System: 安卓
- Browser (if used): alook
```

### Log file

这个没有

**Comment by 88250** [comment]
设置都不同步的，是设计如此，我关闭 issue 了。

**Comment by QQQOrange** [comment]
> 设置都不同步的，是设计如此，我关闭 issue 了。

这样的话 留存率不同 需要复习的卡片数量每天都不一样啊 至少这一项要同步吧

**Comment by 88250** [comment]
分开设置一下吧。
