### ISSUE TITLE
Unordered list, repeated paste and undo operations can cause crashes.

### ISSUE THREAD

**Issue by MoonBottle** [siyuan-note/siyuan#9927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Unordered list, repeated paste and undo operations can cause crashes.

![PixPin_2023-12-19_18-03-16](https://github.com/siyuan-note/siyuan/assets/12904505/de7c7491-77f9-4aa5-9074-9cfedcea8d4a)

### Expected result

do not crash

### Version environment

```markdown
- Version: 2.11.2
- Operating System: win11
- Browser (if used):
```

### Log file

no log

**Comment by 88250** [comment]
Hello, can you download the latest dev version to help test it? This problem should have been fixed.

#9912

**Comment by MoonBottle** [comment]
I have tested it with the dev version and there are no more crashes.

**Comment by 88250** [comment]
Thanks.
