### ISSUE TITLE
2.11.2闪卡页面可以通过二级菜单删除当前卡片，2.11.3二级菜单没了

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

二级菜单没了，不能在复习闪卡时通过二级菜单删除当前卡片了

### Expected result

回复此功能

### Version environment

```markdown
- Version: 2.11.3
- Operating System: win11
- Browser (if used):edge
```

### Log file

无

**Comment by Vanessa219** [comment]
是这个菜单么？再点击一下就可以取消当前卡片了。
<img width="443" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/91e0c7e1-715d-4412-861c-58facd57d2bf">

**Comment by QQQOrange** [comment]
> 是这个菜单么？再点击一下就可以取消当前卡片了。 <img alt="image" width="443" src="https://private-user-images.githubusercontent.com/970828/291609367-91e0c7e1-715d-4412-861c-58facd57d2bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzA0NTMsIm5iZiI6MTcwMzAzMDE1MywicGF0aCI6Ii85NzA4MjgvMjkxNjA5MzY3LTkxZTBjN2UxLTcxNWQtNDQxMi04NjFjLTU4ZmFjZDU3ZDJiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQyMzU1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmQ2OTViYWY1YWRkNzU3NTI3NmZhZDFlZjNiNDQyZDkxYmNjNGU5ZjkwMGQ0ZWVmZWJkMzY2OGU1YjM3Y2EyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gKf86ugSphUrKvOcnG9i1Wtxzx6bMNtJOc9X0uUJL60">

不是这个 是在闪卡复习页面点击筛选按钮附近的一个按钮，会出现一个删除选项，点击后这张卡片就被删除了。现在这个按钮没了

**Comment by Vanessa219** [comment]
那里是没有删除按钮的，只有管理页面有
<img width="1252" alt="image" src="https://github.com/siyuan-note/siyuan/assets/970828/f4bebcec-53fc-4c64-a0a5-032fb42a613f">

**Comment by QQQOrange** [comment]
> 那里是没有删除按钮的，只有管理页面有 <img alt="image" width="1252" src="https://private-user-images.githubusercontent.com/970828/291745469-f4bebcec-53fc-4c64-a0a5-032fb42a613f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzU1NzAsIm5iZiI6MTcwMzAzNTI3MCwicGF0aCI6Ii85NzA4MjgvMjkxNzQ1NDY5LWY0YmViY2VjLTUzZmMtNGM2NC1hMGE1LTAzMmZiNDJhNjEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwMTIxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MThjYzE2MTVlZWY0OTg0NzFiZDFiMDU3ODI1YzhiNmRhMTk1OWIwNmZkNjJkZmU3Yjk4ODFmY2QwOGU5OWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RWKXB88IDBZZ41HX4oYN4ImoKTnXw_C-gOWOm_BHOEM">

好的
