### ISSUE TITLE
`Convert network images to local` supports URL-encoded local file names

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#9929]
网络图片转换为本地图片BUG

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

文字和图片是从sublimetext的markdown preview中复制过来的
点击下网络图片转换为本地图片时，无法下载`file://`开头的问题，提示：该文档中不存在网络文件

<img width="507" alt="SCR-20231219-rqaz" src="https://github.com/siyuan-note/siyuan/assets/20038464/cf3d0778-6b23-4af6-a933-07bce90b40e4">
<img width="507" alt="SCR-20231219-rpzg" src="https://github.com/siyuan-note/siyuan/assets/20038464/69bfa3d3-8292-4268-b7fd-ef21027aa771">

### Expected result

希望能复制图片到思源内部的本地图片目录中

### Version environment

```markdown
- Version: 2.11.3
- Operating System:  MacOS BigSur
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
麻烦制作一个可重现问题的最小数据集上传以便测试，谢谢。

**Comment by 88250** [comment]
![image](https://github.com/siyuan-note/siyuan/assets/873584/520c7b45-fffb-4e30-b1c8-71b5180cfb22)

这个路径上的文件名是编码后的还是？

**Comment by kylehz** [comment]
file:///Users/bigsu/Downloads/siyuantest/%E4%B8%AD%E6%96%87/2.png
路径是url编码的
[siyuantest.zip](https://github.com/siyuan-note/siyuan/files/13721860/siyuantest.zip)

**Comment by 88250** [comment]
好的，我这里测试正常了（昨晚发布的 dev），谢谢。

**Comment by kylehz** [comment]
我测试了dev2

1、点【网络资源文件转换本地】这个按钮还是报文档中不存在网络文件
<img width="328" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/556b4c48-89ad-48df-95bd-1a75f3b8c589">
<img width="1065" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/fd0394f3-eeaa-4c06-a718-f18fcfccaca8">

2、还有就是从sublimetext的markdown preview复制过来的时候图片路径没有`file://`前缀，希望把这个图片直接复制到思源本地文件
<img width="1175" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/b261a968-f9cd-49f4-bdae-f9b10435dd6a">
<img width="714" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/43ec09c9-4aea-4e22-bff1-42aacf1d33a0">

[siyuantest.zip](https://github.com/siyuan-note/siyuan/files/13721860/siyuantest.zip)

**Comment by 88250** [comment]
1. 收到，稍后再改一下转换资源文件
2. 这样复制的话只能做到复制地址

**Comment by kylehz** [comment]
> 1. 收到，稍后再改一下转换资源文件
> 2. 这样复制的话只能做到复制地址

问题2还是中文路径的问题，我试了英文路径是可以直接复制到思源本地文件的

**Comment by 88250** [comment]
好的，稍后我确认下，谢谢。

**Comment by 88250** [comment]
已经确认这两个改进可以完成，请等下个 dev 版发布再帮忙测试看看，谢谢。

**Comment by kylehz** [comment]
> 已经确认这两个改进可以完成，请等下个 dev 版发布再帮忙测试看看，谢谢。

dev3已经测试了没有问题
