### ISSUE TITLE
导入 markdown 目录时崩溃

### ISSUE THREAD

**Issue by SHACHEN001** [siyuan-note/siyuan#9931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

引起问题的MarkDown目录： https://github.com/0voice/linux_kernel_wiki/tree/main/%E6%96%87%E7%AB%A0
1)下载到本地，
2)在SIYUAN中选择 "导入" -> "Markdown 文件夹"
3)程序崩溃 （当前版本 v2.11.3）
我的EMAIL: shachensg@gmail.com

### Expected result

能够正常导入多个 MarkDown 文件

### Screenshot or screen recording presentation

![Untitled](https://github.com/siyuan-note/siyuan/assets/12188060/3326f9d1-7c4b-47ac-9b3e-253a16a8a0db)

### Version environment

```markdown
- Version: v2.11.3
- Operating System: windows
- Browser (if used):
```

### Log file

[siyuan.log](https://github.com/siyuan-note/siyuan/files/13717158/siyuan.log)

**Comment by 88250** [comment]
你好，是否能下载一下最新的 dev 版本帮忙测试看看，这个问题应该已经修复。

#9912
