### ISSUE TITLE
在闪卡复习页面能使用ctrl+delete删除当前卡片

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9933]
### In what scenarios do you need this feature?

在渐进阅读过程中会制作非常多的卡片，复习时候发现其中的某些是无意义的，因此就可以随手删除。
现在的闪卡复习中如果要删除当前卡片，非常复杂，要么在管理中删除，这样很难定位到具体想删除的卡片，要么在复习页面中通过二级菜单删除，这样非常繁琐。

### Describe the optimal solution

要是在复习过程中能够使用ctrl+delete快捷键删除就会十分的简易。
PS：这个删除当前卡片的快捷键也是anki长期以来使用的。

**Comment by 88250** [comment]
快速制卡有快捷键的 Ctrl+Alt+F

**Comment by QQQOrange** [comment]
> 快速制卡有快捷键的 Ctrl+Alt+F

这个快捷键不能删除当前卡片

**Comment by 88250** [comment]
这个可以取消制卡的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月20日(周三) 晚上6:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] 在闪卡复习页面能使用ctrl+delete删除当前卡片 (Issue #9933)




  
快速制卡有快捷键的 Ctrl+Alt+F
  
这个快捷键不能删除当前卡片

**Comment by QQQOrange** [comment]
> 这个可以取消制卡的。
> […](#)
> --- 原始邮件 --- 发件人: ***@***.***&gt; 发送时间: 2023 年 12 月 20 日 (周三) 晚上 6:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [siyuan-note/siyuan] 在闪卡复习页面能使用 ctrl+delete 删除当前卡片 (Issue #9933) 快速制卡有快捷键的 Ctrl+Alt+F 这个快捷键不能删除当前卡片 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

我试了一下 卡片还在 但是哪一个超级快被制成卡片了…… 能不能设置一个纯删除卡片的快捷键呢，现有的这个一来功能不直观，二来功能应用范围难以把握

**Comment by 88250** [comment]
要选中块再按，选块逻辑和其他地方是一致的。

**Comment by QQQOrange** [comment]
> 要选中块再按，选块逻辑和其他地方是一致的。

试了几次还是不行 每次都是被制成新卡
![image](https://github.com/siyuan-note/siyuan/assets/62794181/cbe6b29b-eb20-4b66-915b-e77ed6208328)
要么是点左边的那两个一样的小方块，要么就是直接右键块，完全删除不了当前的卡片

**Comment by 88250** [comment]
是容器块的话需要扩选，比如使用 Shift+↑ 选择。

**Comment by QQQOrange** [comment]
> 是容器块的话需要扩选，比如使用 Shift+↑ 选择。

不能设置一个统一的方式来删除卡片吗。一种类型对应一种删除卡片的方式，这不是要老命了。思源刚出来就用了，也算是早期勇士之一，结果用这个也用不明白。要是新人该咋整啊

**Comment by 88250** [comment]
不能啊，制卡要选中块才行，容器块支持嵌套，不是出一个按钮就能选择到你想要的块的。

**Comment by QQQOrange** [comment]
> 不能啊，制卡要选中块才行，容器块支持嵌套，不是出一个按钮就能选择到你想要的块的。

脑溢血了
