### ISSUE TITLE
一键删除闪卡管理中全部“不符合条件的内容块”

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9934]
### In what scenarios do you need this feature?

随着渐进阅读制作的闪卡增加，以及复习周期的延长，部分的文章失去了复习的价值，删除相应的文章后，其闪卡不会一起删除，而是会在管理中显示为“不符合条件的内容块”，并且其以一种无序的形式排列，这样想要删除所有的这部分卡片，几乎需要把闪卡管理整体过一遍。但是闪卡数量的增加，使得这一过程变得难以完成，因此需要一键删除闪卡管理中全部“不符合条件的内容块”。

### Describe the optimal solution

在管理中添加此功能。

**Comment by 88250** [comment]
* Duplicate of https://github.com/siyuan-note/siyuan/issues/9901
* https://github.com/siyuan-note/siyuan/issues/8794
