### ISSUE TITLE
更新2.11.3后 闪卡复习页面的这个图标没有了

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![image](https://github.com/siyuan-note/siyuan/assets/62794181/6b6d0374-8fcb-4419-9cb1-c47ccda9036c)
在锁的图标旁边的那个 点击出现菜单的图标消失了

### Expected result

希望能够恢复这个图标，在闪卡复习页面，不是闪卡管理页面

### Version environment

```markdown
- Version: 2.11.3
- Operating System: win11
- Browser (if used):edge
```

### Log file

![image](https://github.com/siyuan-note/siyuan/assets/62794181/cc9c5c31-f335-4c42-944e-cf280394fc45)

**Comment by 88250** [comment]
你指的是这个图标吗？

![image](https://github.com/siyuan-note/siyuan/assets/873584/b12a3823-743f-4654-a6eb-5a2e0cd9f4ce)

我这里测试正常：

![image](https://github.com/siyuan-note/siyuan/assets/873584/64898586-9712-4402-b556-69bb5d442546)

**Comment by QQQOrange** [comment]
> 你指的是这个图标吗？
> 
> ![image](https://private-user-images.githubusercontent.com/873584/291911237-b12a3823-743f-4654-a6eb-5a2e0cd9f4ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTI2MzMsIm5iZiI6MTcwMzExMjMzMywicGF0aCI6Ii84NzM1ODQvMjkxOTExMjM3LWIxMmEzODIzLTc0M2YtNDY1NC1hNmViLTVhMmUwY2Q5ZjRjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQyMjQ1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2Y2NWEyOTU1NjRhOGI5MTc1N2Y3YzhiZDI3ZDczMDdhOWY4NGNlZjlmY2I1MjRmN2JjYzk0NzI5OTM3ZDRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u21hYUIV4dbnvV0j6BVSJq6sXrYZtFuv9T04aI6wJh8)
> 
> 我这里测试正常：
> 
> ![image](https://private-user-images.githubusercontent.com/873584/291911299-64898586-9712-4402-b556-69bb5d442546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTI2MzMsIm5iZiI6MTcwMzExMjMzMywicGF0aCI6Ii84NzM1ODQvMjkxOTExMjk5LTY0ODk4NTg2LTk3MTItNDQwMi1iNTU2LTY5YmI1ZDQ0MjU0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQyMjQ1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGRkMDM2YWIzYWE1M2IwODRiN2E4ZmQxM2VjNjYyOTRmM2Y0ZGM2NzM0YTdhZmFjNWU2OGZjYzVlNDAwYWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wUjxrEBM5ikw_7rcBMc6m2LPAKx0UIOF9vG0FaxYEck)

是的

**Comment by 88250** [comment]
请检查是否是主题或者插件等扩展影响，我先关闭 issue 了，如果还有问题请随时跟帖，谢谢。
