### ISSUE TITLE
Concurrency control when requesting the kernel API

### ISSUE THREAD

**Issue by zxhd863943427** [siyuan-note/siyuan#9939]
并发执行api失败

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![图片](https://github.com/siyuan-note/siyuan/assets/74853597/edac04a0-7b6e-4ec6-8058-3da44f486967)

最终的结果是块中缺失属性。

### Expected result

两者都能正确地执行

### Version environment

```markdown
- Version: 2.11.3
- Operating System: win10 
- Browser (if used):
```

### Log file

无需日志

**Comment by 88250** [comment]
我看好像返回状态是 200 哦，具体是什么表现？

**Comment by zxhd863943427** [comment]
api调用成功，但是查看块属性时发现并没有成功设置属性。

**Comment by 88250** [comment]
是被覆盖了还是？

**Comment by 88250** [comment]
暂时无法确定重现步骤，我先关闭了，后续如果有测试代码或者重现步骤请随时跟帖，谢谢。

**Comment by zxhd863943427** [comment]
最简单的方式：
```js
fetchSyncPost('/api/riff/addRiffCards',{"deckID":"20230218211946-2kw8jgx","blockIDs":["20230428155440-s8hzxrz"]})
fetchSyncPost('/api/attr/setBlockAttrs',{"id":"20230428155440-s8hzxrz","attrs":{"custom-attr1":"true"}})
fetchSyncPost('/api/attr/setBlockAttrs',{"id":"20230428155440-s8hzxrz","attrs":{"custom-attr2":"true"}})
fetchSyncPost('/api/attr/setBlockAttrs',{"id":"20230428155440-s8hzxrz","attrs":{"custom-attr3":"true"}})
fetchSyncPost('/api/attr/setBlockAttrs',{"id":"20230428155440-s8hzxrz","attrs":{"custom-attr4":"true"}})
```
大概率属性会缺失。
这是我这边的执行效果：
![图片](https://github.com/siyuan-note/siyuan/assets/74853597/f9623422-417c-413d-9da5-ee271bc9b740)

**Comment by 88250** [comment]
好的，稍晚点我试试。

**Comment by 88250** [comment]
可以重现问题了，下个版本改进，感谢反馈。
