### ISSUE TITLE
每次更新后保持任务栏固定

### ISSUE THREAD

**Issue by dream-tentacle** [siyuan-note/siyuan#9940]
### In what scenarios do you need this feature?

我习惯将常用的软件固定在windows任务栏，但每次思源笔记更新后都会取消固定，于是只好每次从桌面点击打开

### Describe the optimal solution

希望可以让思源笔记更新后可以不会从任务栏的固定中取消掉；或者更新前检测是否固定了，更新后做出相应自动设置（某种替代解决思路）

**Comment by 88250** [comment]
Duplicate of https://github.com/siyuan-note/siyuan/issues/3773
