### ISSUE TITLE
应用提供系统代理选项

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#9942]
### In what scenarios do you need this feature?

例如使用 /api/network/forwardProxy 访问 https://www.v2ex.com/index.xml 的时候，会返回超时
```
forward request failed: Get \"https://www.v2ex.com/index.xml\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

### Describe the optimal solution

类似：
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/d25d9562-d593-4267-a193-cad1004979c5)

**Comment by 88250** [comment]
设置关于里有网络代理配置的，选择 直接连接 是不启用代理，默认应该会走系统的网络配置。

**Comment by 2234839** [comment]
好的，提一个优化点
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/771f3db2-692d-4aa4-a29d-9080ddd84590)
我搜索之后完全没有注意到左侧面板

**Comment by 88250** [comment]
@Vanessa219

**Comment by 2234839** [comment]
我尝试了几次配置都似乎并没有走代理，代理软件中看不到相关的日志，请求依旧超时
