### ISSUE TITLE
Set `plugin.name` to read-only

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#9943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题

### Expected result

关闭插件后应该卸载掉它注册的命令。
现在只能靠重启

### Version environment

```markdown
- Version: v2.11.3
- Operating System: windows
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
如下操作是可以移除的，麻烦说一下重现的操作步骤。

https://github.com/siyuan-note/siyuan/assets/970828/b1c6b22d-13bc-4cf4-be13-6ebaf0157f46

**Comment by 2234839** [comment]
会和我的实现有关系吗
 https://github.com/2234839/feed_siyuan_plugin/blob/91b9c439f701a15802469a26aa47575516670bc1/src/index.ts#L69C1-L76C8

因为没有找到注销的命令，在 unload 中我尝试了
https://github.com/2234839/feed_siyuan_plugin/blob/91b9c439f701a15802469a26aa47575516670bc1/src/index.ts#L81C1-L81C24
但没有用

[插件命令没有注销.webm](https://github.com/siyuan-note/siyuan/assets/28727933/21267289-3661-4806-a6a4-0ab564050e31)

**Comment by Vanessa219** [comment]
name 是唯一标识，只能读，不可修改，稍后我改一下。
