### ISSUE TITLE
新建子文档，提示报错，未找到 id为x 的内容块；重启，重建索引，重新导入data都无效。

### ISSUE THREAD

**Issue by tonyltl** [siyuan-note/siyuan#9944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

新建子文档，提示报错，未找到 id为x 的内容块；重启，重建索引，重新导入data都无效。
![111111](https://github.com/siyuan-note/siyuan/assets/30629793/e2c8c108-d68d-4b7c-887e-6f5e25287b70)

### Expected result

不报错

### Screenshot or screen recording presentation

![22222222](https://github.com/siyuan-note/siyuan/assets/30629793/cb765636-d063-416f-9283-fc7cae5fc7b8)

### Version environment

```markdown
- Version: 2.11.2
- Operating System: docker 群晖
- Browser (if used):Edge
```

### Log file

![111111](https://github.com/siyuan-note/siyuan/assets/30629793/6d576276-e08b-446c-aaf4-bf52c2c5fea7)

**Comment by tonyltl** [comment]
在对应目录下手动创建一个同名sy文件，还是会报错，提示未找到id为y（另一个id）的内容块

**Comment by gakkiyomi** [comment]
我也是

**Comment by gakkiyomi** [comment]
当前版本 v2.11.2
[屏幕录制2023-12-21 14.43.11.zip](https://github.com/siyuan-note/siyuan/files/13737075/2023-12-21.14.43.11.zip)
复现视频
[system-log.zip](https://github.com/siyuan-note/siyuan/files/13737077/system-log.zip)

**Comment by gakkiyomi** [comment]
@88250 D哥帮忙看看,这个现在好频繁出现

**Comment by tonyltl** [comment]
我被这个问题整不会了，重建索引丢失了一整篇文档，1万多字。。。
还有就是现在无法新建文档，只能暂时记录在旧文档上面。
希望大佬尽快解决，辛苦了~

**Comment by 88250** [comment]
你好，请下载 dev 版，应该已经修复。

我先关闭了，如果还有问题请继续跟帖，谢谢 :pray:
