### ISSUE TITLE
书签所在块已被删除，但书签还在数据库中

### ISSUE THREAD

**Issue by 2234839** [siyuan-note/siyuan#9945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![图片](https://github.com/siyuan-note/siyuan/assets/28727933/c4d554f0-4536-46db-9e9a-343c50daae34)
![图片](https://github.com/siyuan-note/siyuan/assets/28727933/e62b7895-4db2-44c0-8e8f-e792765109c3)

### Expected result

块被删除了书签记录也应该被删除

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
版本是 v2.11.2 吗？

**Comment by 88250** [comment]
在 v2.11.3 上已经修复了，关联 https://github.com/siyuan-note/siyuan/issues/9875

我这里刚刚测试无法重现该问题，先关闭了，如果你那里能在最新版上重现，麻烦继续跟帖，谢谢。
