### ISSUE TITLE
  希望可以支持网站子路径指向siyuan的web界面

### ISSUE THREAD

**Issue by nxdong** [siyuan-note/siyuan#9946]
### In what scenarios do you need this feature?

比如我有一个域名叫 abc.com  我希望可以通过配置nginx 使  abc.com/note  指向思源的web。 

### Describe the optimal solution

trilium 是可以实现这个功能的，之前用这个配置成功过。

### Other information

通过一些Nginx 配置，我可以重定向一些请求到siyuan服务器， 但是不能完全成功。
`location /n/ {
        proxy_pass http://172.17.0.1:18888/;
        #proxy_set_header Host $host;
        proxy_set_header Host 172.17.0.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 重写 Location 值，将 / 替换为 /note
        proxy_redirect / /n/;
       }
      location /api/ {
        proxy_pass http://172.17.0.1:18888/api/;
        #proxy_set_header Host $host;
        proxy_set_header Host 172.17.0.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 重写 Location 值，将 / 替换为 /note
        proxy_redirect / /n/;
       }

       location /ws {
        proxy_pass         http://172.17.0.1:18888/;
        proxy_read_timeout 60s;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
    }
`

这样配置无法解决登录auth之后的网站跳转。
根据我观察代码 https://github.com/siyuan-note/siyuan/blob/fd0e44fbf0ef3f8e9919859303e6f748754ae2a8/app/stage/auth.html#L478

发现有一些hardcode的请求路径。 
希望这些硬编码的请求路径可以使用相对路径，比如使 ws、api、herf 的路径使用相对路径。

**Comment by 88250** [comment]
你好，路径目前不考虑支持了，请使用二级域名。
