### ISSUE TITLE
代码块复制不带 ```lang

### ISSUE THREAD

**Issue by banjuer** [siyuan-note/siyuan#995]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

在复制出代码框内容后, 有些场景可能是要直接执行, 带上```lang往往执行报错

### 描述最优的解决方案 Describe the optimal solution

提供一个关于代码框复制的设置, 用户可以选择复制出内容是否带上```lang

### 描述候选解决方案 Describe the candidate solution

或者修改某个config.json里面配置能达到相同效果

### 其他信息 Other information

暂无

**Comment by 88250** [comment]
感谢建议，后期考虑。
