### ISSUE TITLE
Support searching assets by file name

### ISSUE THREAD

**Issue by HowcanoeWang** [siyuan-note/siyuan#9952]
数据库资源选项卡无法通过文件名搜索到

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

如题，想在数据库的资源类表格中，添加之前已经存在的图片，比如图片地址：`assets/2013811214753-20230430212101-if0jvid.jpg`
![image](https://github.com/siyuan-note/siyuan/assets/19968935/acbb18e6-255d-4185-bdc0-789c1c8ae170)

发现添加的时候，搜索功能搜文件名找不到图片
![image](https://github.com/siyuan-note/siyuan/assets/19968935/e76abe5a-97c4-4f0a-a3cf-e3b829c726d9)

似乎该搜索功能，只对图片的提示文本起作用
![image](https://github.com/siyuan-note/siyuan/assets/19968935/1e264f6b-f157-4e37-afae-6bf6ac921dcd)

### Expected result

也能通过文件名搜索到已存在的资源图片

### Version environment

```markdown
- Version: v2.11.3
- Operating System: Manjaro
- Browser (if used): NA
```

### Log file

Not applicable

### More information

PS: 希望也能支持修改已添加资源的图片地址，来方便实现数据库中图片的快速替换

**Comment by 88250** [comment]
修改数据库资源文件列暂时不考虑了，请删除后重新添加。

**Comment by HowcanoeWang** [comment]
> 修改数据库资源文件列暂时不考虑了，请删除后重新添加。

以及有精力的话，考虑支持修改资源文件中的链接~

**Comment by 88250** [comment]
暂时不考虑了……
