### ISSUE TITLE
从思源笔记复制generate_204到任意位置会变成generate\_204

### ISSUE THREAD

**Issue by rainin9** [siyuan-note/siyuan#9954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

从思源笔记复制generate_204到任意位置会变成generate\_204

### Expected result

正常复制

### Version environment

```markdown
- Version:  v2.11.3
- Operating System: win10 22h2 19045.3803
- Browser (if used):
```

### Log file

..

**Comment by 88250** [comment]
你好，这是因为 `_` 是 Markdown 标记符，所以前面需要加 `\` 进行转义，如果需要正确复制有两个方案：

* 使用代码元素，这样复制的内容就是原样的
* 使用 复制纯文本，这样复制的内容只会包括纯文本

感谢反馈。
