### ISSUE TITLE
Does plugin can goBack or goFoward?

### ISSUE THREAD

**Issue by Wetoria** [siyuan-note/siyuan#9957]
### In what scenarios do you need this feature?

插件需要有切换上/下一篇文档的能力。

### Describe the optimal solution

为了减少对思源主体的侵入性，以及不影响主体功能，需要为插件中暴露图中两个按钮的方法。
![image](https://github.com/siyuan-note/siyuan/assets/16909518/05fd1084-3bed-4758-b3a9-79abfac04dad)

### Other information

移动端在阅读的时候，不能够方便的返回到上一篇文档。D大有说过侧滑可以返回，但是在ios端，左右滑动只能滑出文档树和设置页面，并且这两个操作很容易误触发。我记得D大已经了解过这个事情了。

我在enhance插件里，自行监听了文档的切换，然后提供了下图两个按钮可以切换上/下一篇文档。

![image](https://github.com/siyuan-note/siyuan/assets/16909518/a038a33f-e058-4aab-94f0-d31b26cd40eb)

但是使用这种方式，打开的时候都是跳转到文档的顶部，而不是像桌面端一样，可以记录上一次光标的位置，能否将相关的方法暴露出来？这样我在插件中实现相同功能，就不需要自己hack了。并且也能保证跟思源主体的逻辑是一致的。

**Comment by 88250** [comment]
@Vanessa219

**Comment by terwer** [comment]
我的理解插件自己实现路由可以做到，内置的插件api貌似没有。而且目前的插件实际上是页面的一部分，直接用window的back是不行的，除非嵌套iframe。例如：发布工具插件就是插件自己实现了返回功能。



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/23/2023 10:07 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [siyuan-note/siyuan] Does plugin can goBack or goFoward? (Issue #9957) |

@Vanessa219

**Comment by Wetoria** [comment]
> 我的理解插件自己实现路由可以做到，内置的插件api貌似没有。而且目前的插件实际上是页面的一部分，直接用window的back是不行的，除非嵌套iframe。例如：发布工具插件就是插件自己实现了返回功能。
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 12/23/2023 10:07 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | Re: [siyuan-note/siyuan] Does plugin can goBack or goFoward? (Issue #9957) | @Vanessa219 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

桌面端实际上已经有现成的功能了，只是需要把api给暴露出来。或者已经暴露了，但是我不知道。我接触思源的开发才一个月不到，很多东西还不是特别了解。

**Comment by Vanessa219** [comment]
这两个按钮是上一个光标和下一个光标，不是文档。移动端的文档历史在 `siyuan.backStack` 中。

**Comment by Wetoria** [comment]
> 这两个按钮是上一个光标和下一个光标，不是文档。移动端的文档历史在 `siyuan.backStack` 中。

在表述上我有点问题。

如果这两个按钮的功能，在移动端能实现光标的跳转的话，希望能够将这两个按钮的功能做成API提供给插件。有可能么，V姐。

**Comment by Vanessa219** [comment]
PC 端的这两个按钮无法在移动端使用。主要由于移动端没有页签，只有唯一一个主编辑器。

**Comment by Wetoria** [comment]
> PC 端的这两个按钮无法在移动端使用。主要由于移动端没有页签，只有唯一一个主编辑器。

了解了，那就先不提供吧。
