### ISSUE TITLE
内核连接中断

### ISSUE THREAD

**Issue by itspanther** [siyuan-note/siyuan#996]
### 描述问题 Describe the problem

界面与内核的连接中断

### 期待的结果 Expected result

这几个版本以来到v.0.5.8都出现此问题，希望解决。

### 截屏或录屏演示 Screenshot or screen recording presentation

![360截图20210109163917329](https://user-images.githubusercontent.com/72199875/104087437-ae70c780-529a-11eb-9242-c85c182935f8.jpg)

### 版本环境 Version environment

* 版本 Version：v0.5.8
* 操作系统 Operating system：win7旗舰版64位
* 浏览器（如果使用）Browser (if used)：

### 日志文件 Log

[siyuan.log](https://github.com/siyuan-note/siyuan/files/5790373/siyuan.log)

**Comment by 88250** [comment]
你好，请尝试删除配置文件夹 ~/.siyuan/ 后重启。

**Comment by itspanther** [comment]
删除配置文件夹后还是老问题

**Comment by 88250** [comment]
请再贴一下日志。

**Comment by itspanther** [comment]
应用打开，不打开任何文件夹和文件，一直正常；只打开帮助，问题又出现了。
[siyuan.log](https://github.com/siyuan-note/siyuan/files/5790826/siyuan.log)

**Comment by 88250** [comment]
你好，这个问题是因为打开笔记本后，思源要写如配置文件，但是写入的时候报错了：

> F 2021/01/09 19:53:56 conf.go:254: write conf [C:\Users\Administrator\.siyuan\conf.json] failed: open C:\Users\Administrator\.siyuan\conf.json: The requested operation cannot be performed on a file with a user-mapped section open.

如果写入配置报错的话，思源会自动退出内核进程。这个报错我查了下，似乎是因为系统设置的原因，所以我们这边可能搞不定，可能和 C 盘安全设置相关。

可以试下把配置文件夹 .siyuan 整个复制到安装目录下面，思源会优先使用安装目录下的配置，这样也许就能正常写入了。

**Comment by windoversnow** [comment]
配置文件夹 .siyuan 整个复制到安装目录下面，最近还是内核中断的太太太频繁了，快受不了了，几乎不能工作

**Comment by windoversnow** [comment]
@88250

**Comment by 88250** [comment]
@windoversnow 你好，本地是否启动了代理软件？

**Comment by windoversnow** [comment]
> @windoversnow 你好，本地是否启动了代理软件？

我压根不知道啥是代理软件 没用过啊

**Comment by 88250** [comment]
麻烦试下 v0.6.0 看看是否能启动好，如果不能的话请贴一下日志。

**Comment by 88250** [comment]
你好，你是把 .siyuan 配置文件夹拷贝到了安装目录下面么？

**Comment by windoversnow** [comment]
> 你好，你是把 .siyuan 配置文件夹拷贝到了安装目录下面么？

是的
放在用户目录和安装目录都出现过问题

**Comment by windoversnow** [comment]
也试过一般打开和以管理员权限打开

**Comment by 88250** [comment]
@windoversnow 麻烦放在用户目录下再启动贴下日志，谢谢。

**Comment by windoversnow** [comment]
很给面子的，一次启动就成功出现中断了，(⊙o⊙)…
![image](https://user-images.githubusercontent.com/75920913/104714123-c6938b80-575f-11eb-8c39-72aa81075408.png)
  ____    _  __   __
 / ___|  (_) \ \ / /  _   _    __ _   _ __
 \___ \  | |  \ V /  | | | |  / _` | | '_ \
  ___) | | |   | |   | |_| | | (_| | | | | |
 |____/  |_|   |_|    \__,_|  \__,_| |_| |_|

I 2021/01/15 18:29:27 main.go:122: kernel [v0.6.0] is booting, runtime mode is [prod], working directory is [E:\okokok\SiYuan\resources], temp directory is [C:\Users\967\AppData\Local\Temp\siyuan], read only [false]
I 2021/01/15 18:29:28 lang.go:67: initialized languages
D 2021/01/15 18:29:28 conf.go:89: loaded conf [C:\Users\967\.siyuan\conf.json]
I 2021/01/15 18:29:28 conf.go:179: local serve path [http://10.12.70.6:6806]
I 2021/01/15 18:29:28 conf.go:183: initialized conf
I 2021/01/15 18:29:28 main.go:186: kernel HTTP server is booting [http://0.0.0.0:6806]
I 2021/01/15 18:29:28 webdav.go:37: initialized WebDAV server
I 2021/01/15 18:29:28 box.go:362: indexing [68] trees, cpus [16]
D 2021/01/15 18:29:28 box.go:397: indexed box [http://127.0.0.1:6806/siyuan/1607934760589/SIFORME/]
I 2021/01/15 18:29:28 conf.go:300: initialized box
I 2021/01/15 18:29:29 repo.go:39: initialized git repo
I 2021/01/15 18:29:29 updater.go:79: auto update is disabled
F 2021/01/15 18:29:48 conf.go:257: write conf [C:\Users\967\.siyuan\conf.json] failed: open C:\Users\967\.siyuan\conf.json: The requested operation cannot be performed on a file with a user-mapped section open.

**Comment by 88250** [comment]
@windoversnow 请问 Windows 的版本是？

**Comment by windoversnow** [comment]
> @windoversnow 请问 Windows 的版本是？

![Uploading image.png…]()

**Comment by 88250** [comment]
@windoversnow 麻烦重新传一下图片，裂了……

**Comment by windoversnow** [comment]
> @windoversnow 麻烦重新传一下图片，裂了……

好的

![image](https://user-images.githubusercontent.com/75920913/104722034-9dc3c400-5768-11eb-9d2b-795f59ee0928.png)

**Comment by windoversnow** [comment]
https://s3.ax1x.com/2021/01/15/s0qMCT.png

**Comment by 88250** [comment]
@windoversnow 我们进行了一定修复，但不确定是否能完全解决这个 bug，请等 v0.6.1 发布以后再帮忙看看，谢谢。

**Comment by windoversnow** [comment]
> @windoversnow 我们进行了一定修复，但不确定是否能完全解决这个 bug，请等 v0.6.1 发布以后再帮忙看看，谢谢。

谢谢你们的辛苦付出

**Comment by windoversnow** [comment]
> @windoversnow 我们进行了一定修复，但不确定是否能完全解决这个 bug，请等 v0.6.1 发布以后再帮忙看看，谢谢。

我自己想过一种可能，我家里的电脑**貌似**内核中断连接的几率低一点（当然在家用的时长也短，一天的主要时间在公司电脑上，所以有待进一步验证），家里电脑也是win10，但跟公司电脑不同的是，家里电脑当然是完全独立自主的，本地管理员账号，而公司电脑加了域，我们默认登录的并不是administrator账号，而且思源笔记能在局域网内发布到浏览器，使用别的终端浏览编辑，我不是程序员，不懂内部细节，只是想会不会当内核在后台访问某些地址时，哪里有冲突了？

再一个可能是，我发现某些文章/笔记文件，就特别容易“触发”内核崩溃。
思源从之前的某个版本开始，不自动添加中英文之间的空格了（ **对了，这还是个问题，我现在的笔记依旧会自动添加空格** ），这个变化导致我的一些标签，有些中间有空格，有些没有空格，就成了两个标签，我在集中修改这些标签时，总是容易在某个文章崩溃，先修改别的文章，然后改这个问题文章，这时它崩溃了，先改问题文章，它直接崩溃了

@88250

**Comment by 88250** [comment]
@windoversnow 那有可能是系统安全相关的配置导致的，因为日志中出现这个，这个不是程序内部能解决的。

> The requested operation cannot be performed on a file with a user-mapped section open.

修改时如果造成内核崩溃，请帮忙留意，发生后请发日志给我们，谢谢。

**Comment by windoversnow** [comment]
> @windoversnow 那有可能是系统安全相关的配置导致的，因为日志中出现这个，这个不是程序内部能解决的。
> 
> > The requested operation cannot be performed on a file with a user-mapped section open.

如果是这个原因，应该去排查电脑上哪些设置？

**Comment by 88250** [comment]
抱歉了，这个我也不知道……
