### ISSUE TITLE
最近文档页面边框大小不正常

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

这个大小是不是不太正常，好瘦啊
![image](https://github.com/siyuan-note/siyuan/assets/67137548/45ba66d8-5aad-4523-85f3-cb80a4c964e0)

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
是不是拖拽过？dev 版本打开会保存宽度和大小。

默认宽度我再调整大一点。
