### ISSUE TITLE
Support adding the watermark on export PDF

### ISSUE THREAD

**Issue by 88250** [siyuan-note/siyuan#9961]
* https://ld246.com/article/1700462282305
* https://ld246.com/article/1643167282883

这是一个 功能特性。This is a PRO feature.

**Comment by 88250** [comment]
图片再议吧，先考虑 PDF 的。

**Comment by 88250** [comment]
实现不一样的，图片暂时不考虑了哦。

**Comment by mozhux** [comment]
有一说一。。图片也有需求啊。生成图文分享发朋友圈有是一种情绪需求

**Comment by 88250** [comment]
图片的需求后面考虑吧。

**Comment by 88250** [comment]
导出图片水印 https://github.com/siyuan-note/siyuan/issues/9992
