### ISSUE TITLE
```代码块``` 选择语言时，能否将最近使用过的语言放在列表最上方？

### ISSUE THREAD

**Issue by dusdong** [siyuan-note/siyuan#9964]
### In what scenarios do you need this feature?

在 `代码块` 中选择语言时，能否将最近使用的语言放在列表最上方？其实每个人常用的语言就那么几个，每次都要录入搜索，挺麻烦的。
![image](https://github.com/siyuan-note/siyuan/assets/3461709/63e004be-166c-47f4-af17-b7a966773eac)

### Describe the optimal solution

希望可以将最近选择的语言放在列表最上方，或者可以自定义需要置顶的语言，谢谢~

**Comment by 88250** [comment]
暂时不考虑了，请参考 https://ld246.com/article/1678543234876

**Comment by dusdong** [comment]
我更多是从网页上发送到思源笔记，整理的时候就只能每次选择语言，有点麻烦

**Comment by 88250** [comment]
暂时只能这样了，见谅。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月26日(周二) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [siyuan-note/siyuan] ```代码块``` 选择语言时，能否将最近使用过的语言放在列表最上方？ (Issue #9964)




 
我更多是从网页上发送到思源笔记，整理的时候就只能每次选择语言，有点麻烦
