### ISSUE TITLE
Support the use of WPAD as a proxy server

### ISSUE THREAD

**Issue by walklty** [siyuan-note/siyuan#9969]
### In what scenarios do you need this feature?

![image](https://github.com/siyuan-note/siyuan/assets/47232102/396acb3e-b393-43e9-92aa-d663c419c01b)
In a company domain-managed environment, I can access and view files on b3logfile.com through a browser. However, the Windows client is unable to connect to the server.

Other software can establish an internet connection if they support "Use browser configuration" option.

### Describe the optimal solution

also support this.

**Comment by 88250** [comment]
使用 `直接连接` 时走的就是浏览器的系统代理设置：

![image](https://github.com/siyuan-note/siyuan/assets/873584/9f694beb-e38c-416f-8502-a9cf4bdea5e0)
