### ISSUE TITLE
大纲支持标题块的层级和顺序快捷调整

### ISSUE THREAD

**Issue by wo4wangle** [siyuan-note/siyuan#997]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

写笔记发现已记录的笔记的标题块需要进行调整的时候
![image](https://user-images.githubusercontent.com/46141646/104087555-8a61b600-529b-11eb-9c74-698c15a4fa84.png)
如图，这是我一篇真实笔记的大纲视图，可以看到最深的是**5级标题**
但是这个大纲的结构的形成是**不断手动调节**各个标题块层级做到的

有时候需要对大部分标题块做整体的降级：
比如写到“被动关闭”时候发现上方一系类都是“主动关闭”的内容
遂手动调整， **这样的操作只是机械的给标题加 #**

有时候需要对大部分标题做整体的升级：
“比如线程池的处理”及其子标题块的内容太多了，希望单独作为一个文件
手动复制出去又需要**对每个标题块进行 # 的相应删除**

这样的操作在维护笔记的过程中**几乎一直在发生**
因为笔记的结构往往是**不断整理**出来的
而不是一开始就确定的，尤其是主动思考形成的笔记

### 描述最优的解决方案 Describe the optimal solution

允许在大纲视图中ctrl选中多个大纲标题行
通过“enter\shift enter”的快捷方式进行标题级别的 降\升
或右键菜单提供 降\升 级选项

后台的本质就是 找到对应的标题 进行批量的 删\增 #

### 其他信息 Other information

标题块的**顺序**也希望一并给与可调整的功能：大纲视图采用类似文件夹的拖放来做
顺序的手动调整就是大量手动的复制和粘贴

顺序和等级的调整 相当于 调整 思维导图中的 主题顺序和等级
都是高频操作

谢谢！！

**Comment by Andy-AO** [comment]
希望这个功能能尽快得到支持，对于重度笔记用户来说，真的非常重要!

**Comment by 88250** [comment]
在大纲上调整估计后面，目前正在实现脑图编辑模式，用这个模式可以通过操作导图来快速调整层级和顺序。

另外，文档编辑模式下可以考虑使用标题块和文档块互转来实现标题层级重构，谢谢。

**Comment by wo4wangle** [comment]
> 在大纲上调整估计后面做，目前正在实现脑图编辑模式，用这个模式可以通过操作导图来快速调整层级和顺序。
> 
> 另外，文档编辑模式下可以考虑使用标题块和文档块互转来实现标题层级重构，谢谢。

冒的问题，D大 辛苦了

**Comment by 88250** [comment]
暂时不考虑了，现在重构标题层级已经有两个方法：

* 编辑器内折叠标题后移动
* 标题文档互转

大纲树主要还是以导航为主，我关闭了，谢谢。

**Comment by TCOTC** [comment]
> 允许在大纲视图中ctrl选中多个大纲标题行
> 通过“enter\shift enter”的快捷方式进行标题级别的 降\升
> 或右键菜单提供 降\升 级选项
> 
> 后台的本质就是 找到对应的标题 进行批量的 删\增 #

> 标题块的顺序也希望一并给与可调整的功能：大纲视图采用类似文件夹的拖放来做
> 顺序的手动调整就是大量手动的复制和粘贴

感觉还是这样方便，现在的操作好麻烦

**Comment by TCOTC** [comment]
[【需求】在大纲面板拖动标题，能改变实际内容的顺序。 - 链滴](https://ld246.com/article/1710843885357)

**Comment by TCOTC** [comment]
如果能增加这个功能的话，还可以实现批量把一级标题转换为二级标题

**Comment by 88250** [comment]
@TCOTC https://github.com/siyuan-note/siyuan/issues/7957

**Comment by TCOTC** [comment]
两个 issue 略有不同，这个 issue 还多一个批量调整标题层级

**Comment by 88250** [comment]
7957 里包含了调整层级的。

**Comment by TCOTC** [comment]
好吧，虽然实现方式感觉有点不一样（用 Ctrl 任意多选 / 用鼠标拖拽），但确实能达到相同的效果。
