### ISSUE TITLE
闪卡适配最新的FSRS 4.5算法

### ISSUE THREAD

**Issue by QQQOrange** [siyuan-note/siyuan#9970]
### In what scenarios do you need this feature?

 新的算法意味着更好的记忆效率，目前fsrs算法已经迭代到了4.5，希望思源早日跟进

### Describe the optimal solution

适配最新算法

**Comment by 88250** [comment]
目前已经是 go-fsrs 的最新版了 https://github.com/open-spaced-repetition/go-fsrs 如果还有更新的话，需要等上游库升级，谢谢。
