### ISSUE TITLE
v2.11.4-dev6 创建数据快照失败

### ISSUE THREAD

**Issue by Achuan-2** [siyuan-note/siyuan#9971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

在正常编写笔记过程中，会突然弹出创建数据快照失败的警告
![image](https://github.com/siyuan-note/siyuan/assets/60436214/7d8124dd-6e7b-43f9-a897-19f4b0482ad3)

### Expected result

想知道原因，是bug还是其他问题导致的

### Version environment

```markdown
- Version: v2.11.4-dev6
- Operating System: Win11
- Browser (if used):
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13765524/system-log.zip)

**Comment by mozhux** [comment]
我快速编辑数据库，然后撤回会弹这个

**Comment by 88250** [comment]
https://github.com/siyuan-note/siyuan/issues/9941 中改的，打快照的时候会校验文件写入时间，稍后再调整一下，感谢反馈。
