### ISSUE TITLE
Rebuilding index causes kernel exiting for unknown reasons

### ISSUE THREAD

**Issue by airium** [siyuan-note/siyuan#9972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

Rebuilding index on version 2.11.2 and 2.11.3 will crash the program, prompting "The kernel exited for unknown reason" (see screenshots). Version 2.11.1 has no such issue.

Upgrading to v2.11.2/3 does not trigger the issue immediately, but the program crashes as soon as "Rebuild Index" is clicked and started manually, and on every subsequent startup. Downgrading to 2.11.1 resolves the issue with no damage to data.

Can be reproduced on three different machines.

### Expected result

Rebuilding index should not trigger kernel exiting/program crash.

### Screenshot or screen recording presentation

On version 2.11.2 and 2.11.3, click on "rebuild index":

![Screenshot 2023-12-25 170648](https://github.com/siyuan-note/siyuan/assets/38249940/92d6ab3b-a4d5-4627-87d7-b37169f14d92)

The program will then start rebuilding index, it will crash in a few seconds:

![Screenshot 2023-12-25 170138](https://github.com/siyuan-note/siyuan/assets/38249940/c4f9149d-4b86-483a-af5d-eb4b6674f362)

Screen recording:
![Animation](https://github.com/siyuan-note/siyuan/assets/38249940/6d5b4717-5ab6-4559-9328-5ac4dc3451e6)

description for the screen recording:
1. showing no issue with 2.11.1
2. then install 2.11.3 and the first startup is OK
3. rebuild index with 2.11.3, then crash
4. once crashed, later startup with 2.11.3 will crash too
5. installing 2.11.1 back resolves the issue

### Version environment

```markdown
- Version: 2.11.2 and 2.11.3
- Operating System: Windows 10 22H2
```

### Log file

[system-log.zip](https://github.com/siyuan-note/siyuan/files/13766888/system-log.zip)

### More information

No anti-virus software is used.
Windows defender has been disabled.

**Comment by airium** [comment]
I think I can reproduce the issue on Android version as well. The app can be launched but will crash in a few seconds.

The crash happens when the program is doing the final indexing loop through every file.

**Comment by 88250** [comment]
Hello, this problem will be solved in the next version, thank you for your feedback.

Please update after the new version is released. If you can still reproduce the problem, please feel free to reply and tell us, thank you.
