### ISSUE TITLE
Memorize last choice of flash card document tree /闪卡记忆上一次文档树的选择

### ISSUE THREAD

**Issue by AvoidantPerDis** [siyuan-note/siyuan#9973]
### In what scenarios do you need this feature?

如果用户在闪卡指定了文档，应该就是想专注于这个文档，可以复习完提示切换？

### Describe the optimal solution

默认打开/加个开关

**Comment by 88250** [comment]
暂时不考虑了，因为文档树上可能是多个文档路径下都有制卡的，所以复习时还是手动选择比较好，感谢反馈。
