### ISSUE TITLE
交互优化：带链接文字复制到微信聊天窗口无法带上链接。

### ISSUE THREAD

**Issue by lushan2866** [siyuan-note/siyuan#9975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

思源页面：![image](https://github.com/siyuan-note/siyuan/assets/5708881/2000a79d-b9f0-47e2-882e-1e25b1efcab4)

复制到QQ聊天窗口：
![image](https://github.com/siyuan-note/siyuan/assets/5708881/daaf434b-8000-471e-be7a-d026f99373e1)

复制到微信聊天窗口：
![image](https://github.com/siyuan-note/siyuan/assets/5708881/7443b1d9-4fdd-4133-bca4-e2f80c6b7dd8)

### Expected result

如题

### Version environment

```markdown
- Version: 
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by 88250** [comment]
这个应该是粘贴方软件处理的，我先关闭了，感谢反馈。

**Comment by lushan2866** [comment]
好的，不好意思，造成困扰了。
