### ISSUE TITLE
无序列表无法追加项的问题

### ISSUE THREAD

**Issue by kylehz** [siyuan-note/siyuan#9976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

先输入无需列表bbb,ccc，然后在最前面输入aaa，无法把bbb，ccc放到aaa下，aaa和他们是割裂的
<img width="654" alt="image" src="https://github.com/siyuan-note/siyuan/assets/20038464/8c0d061f-8ce4-413c-a65e-c6329c7f18ec">

### Expected result

希望无序列表能任意追加

### Version environment

```markdown
- Version: 2.11.3
- Operating System: MacOS bigsur 11.7
- Browser (if used): 客户端
```

### Log file

[test.sy.zip](https://github.com/siyuan-note/siyuan/files/13769332/test.sy.zip)

**Comment by 88250** [comment]
这种情况下请使用拖拽移动块：

[issue.webm](https://github.com/siyuan-note/siyuan/assets/873584/3a03380c-b49b-4fef-a642-33f1291ad64c)
