### ISSUE TITLE
Improve `//!js` query embed block result sorting

### ISSUE THREAD

**Issue by frostime** [siyuan-note/siyuan#9977]
让 `//!js` 查询结果的顺序和 includeId 完全保持一致

### In what scenarios do you need this feature?

我自己测试的时候发现，js 查询的结果似乎并不会保证和 //!js 代码块返回的 id list 顺序保持一致。

![image](https://github.com/siyuan-note/siyuan/assets/27268127/d4c6d562-773d-47fc-9578-6f6d078a8c65)

### Describe the optimal solution

在 getEmbedBlock 函数最后加一个排序操作
https://github.com/siyuan-note/siyuan/blob/171b91513423811cf1eedc827cf48e3a28c293b6/kernel/api/search.go#L199

根据 includeId 的顺序重新排列一下 block 的顺序

![image](https://github.com/siyuan-note/siyuan/assets/27268127/5b3d2e52-a372-4490-a9a7-dd31054df22a)

**Comment by 88250** [comment]
等发 dev 版后请帮忙测试，谢谢。

**Comment by frostime** [comment]
dev版本测试了一下，应该是没问题了 👍 
![image](https://github.com/siyuan-note/siyuan/assets/27268127/e310cfb8-ca38-4d28-9082-dee4b2bc8507)
