### ISSUE TITLE
Improve `inline code` markdown editing

### ISSUE THREAD

**Issue by idea-zone** [siyuan-note/siyuan#9978]
/api/block/updateBlock  行内代码块无法写入 ## 字符的问题

通过  POST /api/block/updateBlock 
{
​	id: id,
​        dataType: 'markdown'
​        data: '`#[ ]#`     `#ni#`'
}

更新后，结果变成了 ：  `[ ]`     `ni`

**Comment by 88250** [comment]
和这个改动相关 https://github.com/siyuan-note/siyuan/issues/9805 

稍后继续完善，感谢反馈。
