### ISSUE TITLE
控制语言版本

### ISSUE THREAD

**Issue by yeshaopeng6688** [siyuan-note/siyuan#998]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

有些句子，需要反复使用。
比如前面得出某些结论，后面需要用到。
为了全局一致，经常需要回过头去复制。
如果这些结论需要修改，又要搜索替换，一处一处修改很麻烦。
### 描述最优的解决方案 Describe the optimal solution

非常类似标签。
语法：使用某个符号包裹句子。
输出：输出某个符号和提示词，能选择需要的句子。
左侧控制面板上，设计一个界面用来显示所有的句子。在这个界面处，可以修改句子，然后全局替换。保持一致。
![image](https://user-images.githubusercontent.com/69628966/104111887-c4c26600-5322-11eb-9058-08f7c796518e.png)

### 其他信息 Other information

全局替换，无法满足 输出时可以选择 的需求。
双链又感觉太重，适合某个段落、某个列表等较大的内容块显示，不太适合一个段落中单单某个句子的显示。而且不是所有地方都需要用到双链。需要类似标签较轻的显示。

**Comment by 88250** [comment]
你好，行级的粒度太细了，这个场景还是用标签语法比较适合，后续会提供标签重命名 #844 谢谢。

**Comment by yeshaopeng6688** [comment]
好的~
