### ISSUE TITLE
Improved position when reopening document on mobile

### ISSUE THREAD

**Issue by Jiangshuon** [siyuan-note/siyuan#9981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

不清楚是不是bug，有些奇怪

![f3518664aad104ed5ba0e2607ab408b](https://github.com/siyuan-note/siyuan/assets/67137548/23960728-4d8b-4d35-bfd3-6c94895951da)

### Expected result

无

### Version environment

```markdown
- Version: 最新
- Operating System: 
- Browser (if used):
```

### Log file

无

**Comment by Vanessa219** [comment]
这个是定位，告诉用户上次光标在这个块。是不是有点多余，这个问题也有用户反馈过。

**Comment by Jiangshuon** [comment]
哦哦，原来是这个意思。多余与否我也不太确定。

不过我测试了下，发现移动端永远只会高亮第一个块，和上次光标所处位置无关。这有点问题。

另外就是，移动端现在从A文档切换到B文档，再切换到A文档，不能记住A文档上次的阅读位置（之前好像可以像桌面端一样记住每一个文档上次阅读的位置）。

如果不能记住上次阅读的位置的话，那么永远会回到文档开头，也就是永远会高亮第一个块了。
