### ISSUE TITLE
快速跳出行级排版语法

### ISSUE THREAD

**Issue by Mocuishle-Zuiren** [siyuan-note/siyuan#999]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

当我使用快捷键生成 md 的语法时，例如像生成粗体 ****，我的光标定位在粗体语法的中间写内容，写完之后，总是要用右箭头符号按两次出来，或者使用鼠标跳出粗体的语法，才能继续写我的内容，我需要一个快速跳出语法的快捷键

### 描述最优的解决方案 Describe the optimal solution

个人认为按下回车键就跳出 md 语法，这个我个人还是蛮接受，最好是只要按一个键就跳出去

**Comment by 88250** [comment]
谢谢，后续我们考虑下如何改进。

**Comment by yeshaopeng6688** [comment]
> 谢谢，后续我们考虑下如何改进。

这个场景可以考虑”给方向键设置快捷键“的提议~跟idea中跳出`)`、`""`的需求一样~

**Comment by Vanessa219** [comment]
感觉按两下右键应该比按组合快捷键要快，而且不需要去记忆。没有更好的方案就先不优化了。
