### ISSUE TITLE
属性视图支持单击切换单元格

### ISSUE THREAD

**Issue by Temacc0531** [siyuan-note/siyuan#9994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

选中一个单元格后再点击切换到其他单元格需要双击，不太顺畅，建议改成单击就可以切换

### Expected result

单击切换单元格

### Version environment

```markdown
- Version: v2.11.4
- Operating System: Windows 11
```

### Log file

null

**Comment by 88250** [comment]
单元格处于编辑状态时切换需要点击两下，第一下是确认当前单元格修改，第二下才是切换。

可参考 Notion 对比，交互应该是一样的，感谢反馈。
