### ISSUE TITLE
Information on Team Management and Workspace Configuration

### ISSUE THREAD

**Issue by Escapshion** [siyuan-note/siyuan#9996]
### In what scenarios do you need this feature?

As a new user transitioning from Notion to Siyuan, I am exploring Siyuan's potential for my personal and team management needs. Siyuan's self-hosting capabilities, security features, and the ability to set a custom domain are appealing, making it a strong candidate for my use case.

While testing Siyuan, I encountered a limitation in team management features. It seems that Siyuan is primarily designed for personal use, and I couldn't find any settings or configurations related to team collaboration. Specifically, I'm looking for functionalities such as creating multiple workspaces within a single container or environment, and the ability to share pages by publishing them online, similar to Notion's collaborative features.

I would like clarification on whether Siyuan is primarily focused on personal management or if there are features I may have overlooked for team collaboration. If Siyuan is intended to support team management, I would appreciate the addition of functionalities like multiple workspaces and online publishing of pages to enhance collaboration within a team environment.

### Describe the optimal solution

1. Ability to create and manage multiple workspaces within a single Siyuan container or environment.
2. Features for sharing and publishing pages online for collaborative team use.

**Comment by 88250** [comment]
Hello, Siyuan is mainly for personal use scenarios and does not support team collaboration.
