### ISSUE TITLE
希望可以取消限制动态加载块数的上限

### ISSUE THREAD

**Issue by acrlw** [siyuan-note/siyuan#9997]
### In what scenarios do you need this feature?

当前的动态块加载的上限限制是 1024 。我习惯于写长的blog，想一次性加载完全部文档，不想要动态块加载。遇到内容跨块加载的时候，编辑体验很割裂。

### Describe the optimal solution

取消限制

**Comment by 88250** [comment]
这个限制还是需要的，主要考虑到在极端情况下也能保证正常进入编辑器。

如果一定要改的话估计只能考虑 fork 源码自行编译了，感谢反馈。

**Comment by Mctalos** [comment]
我写了个相对较长的工作札记，用的都是list块，结果偶然发现，文档加载不全，以为笔记坏掉了，找半天，发现默认加载256。
默认最大1024感觉比较保守，纯文字编辑，用list为主，经常无法全部加载。

**Comment by 88250** [comment]
@Mctalos 最近两个版本动态加载算法有缺陷，请升级到最新 dev 版测试看看，谢谢。
