### ISSUE TITLE
Improve some inline elements Markdown editing

### ISSUE THREAD

**Issue by acrlw** [siyuan-note/siyuan#9999]
对加粗文字前后加空格后导致空格被加粗

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Can the issue be reproduced with the default theme (daylight/midnight)?

- [X] I was able to reproduce the issue with the default theme

### Could the issue be due to extensions?

- [X] I've ruled out the possibility that the extension is causing the problem.

### Describe the problem

![bold-copy](https://github.com/siyuan-note/siyuan/assets/13927622/6467d667-2020-404d-bb66-fdcb90e0d656)

### Expected result

这是一段 **加粗文字** 但是我不想让后面的文字加粗

### Version environment

```markdown
- Version: 2.11.4
- Operating System: Windows 11
- Browser (if used):
```

### Log file

null

**Comment by 88250** [comment]
再按一次 Ctrl+B 就可以取消加粗，然后继续输入。

按空格后空格字符被包含在加粗元素中的问题稍后改进，感谢反馈。
